### ISSUE TITLE
BlendSpace2D Sync does not work with `BlendModeDiscrete`

### ISSUE THREAD

**Issue by fwilliams42** [godotengine/godot#100009]
### Tested versions

Reproducible in 4.3 stable.

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.5222) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

The sync option should play the animation starting from the last frame of the previous animation. This works correctly when using the continuous blend mode, but not when using discrete. This is readily apparent when using pixel art sprites that face the cardinal directions. 

Using the BlendSpace2D in discrete mode to transition between run animations based on velocity, where continuous mode is inappropriate but maintaining timing between footsteps played on the animation, or attack frames when turning during an attack, is important. [There seem to be other users affected by this as well](https://www.reddit.com/r/godot/comments/1ecl1fk/is_the_blendspace2d_sync_option_broken/).

![Image](https://github.com/user-attachments/assets/e014d110-4bb9-465e-8e27-410ad9bf17b3)

### Steps to reproduce 

The minimal example project has a player that can move using WASD. They use their velocity and last facing direction to determine if they are in the idle or walking animation, and in which direction by using a BlendSpace2D. All of the walk animations have the same number of frames, and the walk animation on the first frame plays a footstep sound effect. The BlendSpace2D is in Sync and Discrete modes. 

Notice when changing direction while still moving the sound effect is played rapidly, indicating it is playing the first frame of the animation immediately always, despite the fact that Sync is on. Now switch to Continuous mode and perform the same task, noting that the sound animation is not played immediately on changing directions but at the expected regular interval, indicating that Sync is working correctly.

I suspect the issue occurs for BlendSpace1D as well from limited testing.

### Minimal reproduction project (MRP)

[blendspace2dbug.zip](https://github.com/user-attachments/files/18008918/blendspace2dbug.zip)

**Comment by TokageItLab** [comment]
The issue of Sync is broken and plays from the beginning does indeed exist, and that is fixed in https://github.com/godotengine/godot/pull/100373.

However, as a problem specific to your MRP, the transition to idle occurs during the change of direction, so the issue remains because the Transition is set to Reset.

![Image](https://github.com/user-attachments/assets/60ea0ee7-7377-45b1-b624-94a754e1a87f)

I'm also concerned about CallbackProcess mismatch due to _physics_process() vs Idle.

![Image](https://github.com/user-attachments/assets/bd4a9320-1fc2-4ec9-b43c-09f3f210b234)

After applying https://github.com/godotengine/godot/pull/100373, you should consider rethinking the Transition condition or disabling the Reset option.
