### ISSUE TITLE
a method to return the files[] being drag and dropped onto app window on mouse enter (hover) event

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#10002]
Basically I want to have a way of showing the user a nice hint and info of where in the GUI to drop the files they are dragging (also how many items they are dragging) - when they are dragging it onto the application's window.

In order to do that, I need to tell the application how many items are being dragged onto the window on a mouse enter event - when the mouse is hovering over the window while dragging items from file explorer.

Currently godot can only return the files being dragged array only when you release the mouse cursor - after the files are already dropped. Unfortunately with that alone it is impossible to implement drag and drop hints appearing while a drag and drop event is happening

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
