### ISSUE TITLE
Editor help doesn't scroll to where it should

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#100087]
### Tested versions

v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.4.dev6 - macOS 15.1.0 - Multi-window, 1 monitor - Metal (Forward+) - integrated Apple M1 Max (Apple7) - Apple M1 Max (10 threads)

### Issue description

I use help search all the time and never had any problems with it until recently, so I assume https://github.com/godotengine/godot/pull/96449 broke it

No matter what I search it always scrolls to the very bottom:

https://github.com/user-attachments/assets/5113f8e6-d00c-4ec9-8ff1-6b38ba4da849

### Steps to reproduce

Search help. I don't know why it's reproducable for some people but not for other, so just opening an issue for now

### Minimal reproduction project (MRP)

N/A

**Comment by jinyangcruise** [comment]
Reproducible in Godot v4.4.dev6 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 32.0.15.6094) - 13th Gen Intel(R) Core(TM) i5-13600KF (20 threads).

Except that I have been seen this problem all the time not only in 4.4.dev6.

**Comment by ydeltastar** [comment]
> Except that I have been seeing this problem all the time not only in 4.4.dev6.

Same for me. What the video shows has happened since before 4.3 official release. The issue continues after https://github.com/godotengine/godot/pull/96449 too but with less frequency.
Since half of the reports say they can't reproduce it, I'm starting to think it has something to do with the monitor refresh rate (I use a 160hz monitor).

Godot v4.4.dev (ef6888cb2) - Windows 10.0.22621 - Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.4633) - AMD Ryzen 9 7950X 16-Core Processor (32 threads)

**Comment by jinyangcruise** [comment]
I use a 60hz monitor
