### ISSUE TITLE
AnimationTrees' progress with Ping-pong loop are corrupted when there are multiple instantiated same AnimationTrees on the scene

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#100018]
### Tested versions

Reproduced on 4.4 dev 5 and 4.3 Stable

### System information

Godot v4.4.dev5 - Windows 10.0.22631 - Single-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 32.0.12019.1028) - Intel(R) Core(TM) i3-10105F CPU @ 3.70GHz (8 threads)

### Issue description

Animation pace is inconsistent, and at times just goes to hell.

The first video showcases the animation pace inconsistency

https://github.com/user-attachments/assets/8c5b12cc-af2c-4c51-9e24-d221b0fe3df9

The second video I've also seen happen in the MRP at times, but only have a video of it happening in my game dummy scene, Observe Walk Calm in animation tree not completely bouncing going between 0 and 1, also at the start it may feel stuttery, but that's because it's a 30 fps video of a 60hz setup, and it's actually not visible but the animation was very aggressively switching back and forth from frame to frame

https://github.com/user-attachments/assets/78787d64-ea68-4e53-85c5-ed574fc494f4

### Steps to reproduce

Inconsistent behavior, with no good steps to reproduce found yet beyond it seeming like it has something to do with the Transition node in Animation Tree. Animation Player animation runs smoothly consistently. the MRP at times may or may not produce the broken results.

### Minimal reproduction project (MRP)

[Bug.zip](https://github.com/user-attachments/files/18012310/Bug.zip)

**Comment by TokageItLab** [comment]
Since there seems to be a mix-up in the issue, let's separate them:

1. If there is more than one AnimationTree, each one is misaligned
- This is not a bug. It is the intended behavior because each AnimationTree is getting a different delta. If you want to process the same delta correctly, set CallbackModeProcess to Physics and this problem will not occur

![Image](https://github.com/user-attachments/assets/91022576-bef8-46c1-9213-4d251b4ca500)

2. The AnimationTree progression is broken “when opening the AnimationTreeEditor”
- This is definitely a bug. However, it is a bug only in the editor. Perhaps, as with A, there is a confusion of pointers for what is passed to the editor

So the former is not a bug, only the latter needs to be fixed.

**Comment by mrjustaguy** [comment]
The problem does occur with callback on Physics on all animationtrees

https://github.com/user-attachments/assets/c3dade1e-9537-44e4-84db-6293c7d60875

**Comment by TokageItLab** [comment]
The following MRPs confirm that the problem of the 2 occurs outside the editor.

[at-bug.zip](https://github.com/user-attachments/files/18022665/at-bug.zip)

In conclusion, simply the `backward` flag is not parameterized, which is why each AnimationTree had the same reference. Therefore, this problem should be specific to ping-pong.
