### ISSUE TITLE
`Joint2D` in new `World2D` doesn't work

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#100094]
### Tested versions

- Reproducible in: v4.3.stable.official.77dcf97d8, v4.4.dev6.mono.official.1f47e4c4e

### System information

Ubuntu 24.10 Vulkan 1.3.280 - Forward+ - Using Device #0: NVIDIA - NVIDIA GeForce RTX 2060

### Issue description

I'm trying to create a character skin with independent physics per entity. For this I'm using a `SubViewport` so I can assign a new `World2D` to it. The problem is that `Joint2D` doesn't seem to work in a new `World2D`, I need the different segments to stick to each other.

It may apply to `World3D` as well? Haven't checked.

### Steps to reproduce

1. Open the attached project.
2. Run the project (`F5`).
3. There are two identical setups with a `PinJoin2D` node sticking the `AnimatableBody2D` & `RigidBody2D` nodes together.
  - One with physics under `SubViewport` with a new `World2D`.
  - One with physics under `CanvasGroup` which uses the default `World2D`.
4. We animate the `AnimatableBody2D` with a `Tween` up & down. Notice that the setup under `CanvasGroup` behaves correctly, while the `SubViewport` setup doesn't.
5. You can also check by commenting out line 10 that `SubViewport` will also work correctly if no new `World2D` is assigned to it.

### Minimal reproduction project (MRP)

[godot-dbg.zip](https://github.com/user-attachments/files/18037363/godot-dbg.zip)

**Comment by rburing** [comment]
This is because the `_ready` method (where you're setting the `world_2d` property) gets called *after* the child nodes are ready (by that time, they will have been added to the other physics space). As a workaround, you can save the nodes under `SubViewport` into their own scene, remove the instance of that scene in the editor, and instead instantiate that scene dynamically and add it as a child *after* setting the `world_2d`:

```gdscript
	skin_sub_viewport_container_sub_viewport.world_2d = World2D.new()

	skin_sub_viewport_container_sub_viewport.add_child(load("res://node_2d.tscn").instantiate())

	var skin_sub_viewport_container_animatable_body = $SkinSubViewportContainer/SubViewport/Node2D/AnimatableBody2D
	var skin_canvas_group_animatable_body = $SkinCanvasGroup/Node2D/AnimatableBody2D

        ...
```

It's strange that `world_2d` can't be set in the inspector, seems inconsistent with 3D.

**Comment by razcore-rad** [comment]
Indeed, thanks, I can confirm that this fixes it. Also yes, `world_2d` can't be set from Inspector so it is an inconsistency :)
