### ISSUE TITLE
Multiple-type exported vars

### ISSUE THREAD

**Issue by AWKgamedev** [godotengine/godot#10016]
Right now exported vars can only be of one type which makes things awkward if you want to set up a var to possibly have multiple functions, having the option to pick their type would be very useful.
Exported Arrays already have a Type dropdown menu for each value which serves a similar purpose:

![2642277](https://user-images.githubusercontent.com/10258315/28835778-f262e120-76bc-11e7-8c87-4ea6d65dbf31.png)

Listing all possible types for all exported vars would be cumbersome so the list of possible types for a variable could be defined by an array like so:
```GDScript
export([Vector2, int, String]) var test_variable
```
The exported var would default to the first type (Vector2), and it would have a dropdown to select the other listed types.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
