### ISSUE TITLE
Sprite3d is not displayed correctly

### ISSUE THREAD

**Issue by Mister-Ky** [godotengine/godot#100258]
### Tested versions

4.3 stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 630 (Intel Corporation; 31.0.101.2111) - Intel(R) Pentium(R) Gold G5500 CPU @ 3.80GHz (4 Threads)

### Issue description

The sprite is not displayed correctly, and its display depends on the camera angle

### Steps to reproduce

put some 3d sprites and try to do what's on the video

https://github.com/user-attachments/assets/0ce7f8e9-fd6d-49d5-ab18-27aeb36967b7

### Minimal reproduction project (MRP)

[demo.zip](https://github.com/user-attachments/files/18087069/demo.zip)

**Comment by clayjohn** [comment]
This is a classic limit that comes from sorting transparent objects and is well documented here: https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting

Basically, game engines have to sort transparent objects so that you can see the objects through other objects. But, sorting happens from a single point, so at certain angles the sorting becomes incorrect. Godot has many tools to deal with this and they are described in the doc I linked above

In your MRP you could simply turn off transparency and the quads would be correctly sorted.
