### ISSUE TITLE
SceneTreeDock: dragging node by column != 0 reparents wrong node

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#10026]
**Operating system or device - Godot version:**
Antergos x86_64 - daad16b

**Issue description:**

Expected: Column other than the first undraggable, or reselect node when dragging other column
Happened: Node selected gets reparented instead of node dragged

**Steps to reproduce:**
1. Create some nodes with toggle visibility (eye) icon
2. Select one node
3. Drag another node TreeItem by its toggle visibility icon
4. Notice that the drag preview is of selected node
5. Node selected gets reparented instead of node dragged

**Comment by qonnop** [comment]
Additionally, you can observe that
- whatever button is pressed, always the _selected_ TreeItem(s) are reparented
- when nothing is selected, nothing is reparented but the visibility button toggles
Does it actually make sense to trigger drag/drop when clicking on/dragging a _button_ at all? According to the source code, reparenting tries to move the _selected item_ to a new one; but selection does not change on button press. A solution to the problem could be to suppress the drag/drop functionality when clicking on the button instead of the label?

**Comment by albertomjp10** [comment]
working in on it

**Comment by albertomjp10** [comment]
@qonnop hey, I agree with your solution, do you think you could indicate me te code to look at to fix this issue, thank you!

**Comment by qonnop** [comment]
It seems to me that `godot\editor\scene_tree_editor.cpp` implements the scene tree editor, e.g. in `_cell_button_pressed` there is a check for the button id `BUTTON_VISIBILITY` and there are also three methods related to drag & drop (`get_drag_data_fw`, `can_drop_data_fw`, `drop_data_fw`).

**Comment by albertomjp10** [comment]
thank you so much, i appreciate it!
