### ISSUE TITLE
Clip index problem when changing “Initial Clip” value other than 0

### ISSUE THREAD

**Issue by ClemiDouce** [godotengine/godot#100514]
### Tested versions

- Reproducible in : v4.3.stable.official [77dcf97d8], v4.4.dev6.official [1f47e4c4e]

### System information

Godot v4.3.stable - Windows 10.0.26100 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.6614) - 11th Gen Intel(R) Core(TM) i9-11900 @ 2.50GHz (16 Threads)

### Issue description

When trying to change the value of parameter "Initial clip" in an AudioStreamInteractive ressource and launching a scene, an error appear and the clip played is the first clip in the list of clip:
```
"E 0:00:00:0793   set_initial_clip: Index p_clip = 2 is out of bounds (clip_count = 0).
  <C++ Source>   modules/interactive_music/audio_stream_interactive.cpp:89 @ set_initial_clip()
```

### Steps to reproduce

- Open a project
- Create a scene with a root node and an AudioStreamPlayer
- Add an AudioStreamInteractive ressource
- Add clips and stream
- Change the value of “Initial Clip” on any clip except the first in the list
- Launch the scene
- Error appear

### Minimal reproduction project (MRP)

N/A

**Comment by mdelorme** [comment]
It seems that when the `AudioStreamInteractive` is initialized it goes through the property `initial_clip` before the actual `clips`. 

When trying to set the value of the initial clip, since no clips have already been initialized the the initial clip is reset to 0.

Changing the order of the properties in the editor corrects the problem. But I'm not sure that's the best way to go.
