### ISSUE TITLE
New scene instance type - Background.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#1006]
In a basic sense, you would have a scene instance with an option that sets it as a background for the current gameplay scene. It would work as follows...

---
- Anything in the background type will be drawn after everything else, meaning that objects and textures in it will only appear whenever there is empty space showing through in the main scene (where the skybox would otherwise be).
- Have an option to allow the background scene's sky texture and/or environmental settings override that of the main scene
- Objects in general in the background scene would not be able to collide with objects in the main scene, however, you can move objects in the background scene (such as basing their movement on an object in the main scene).
## Uses
1. Using it as a true 3D perspective background in a 2D game
2. Using it as a skybox with animation and dynamic properties
3. Using it as a 3D background with 3D games
4. Dynamic muiti-layered background effects using more than one background scene

Please respond if you think this or something similar would be a good idea to add to Godot

Thanks.

**Comment by akien-mga** [comment]
> For 1.2 the plan is to completely overhaul the 3D renderer and implement
all these things.

This is now more for the 3.0 milestone actually.

**Comment by akien-mga** [comment]
@reduz What's the status on this for 3.0?

**Comment by toger5** [comment]
Would that kind of layer support also allow to apply post processing to only one layer

**Comment by reduz** [comment]
Yeah this is pushed to 3.1 unfortunately, it needs a lot of group thinking as well as trial and error.

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by Galaxy613** [comment]
I have a space sim where I want the skybox to be a scene unto itself, this issue is exactly what I need - a scene that is rendered before everything else.

**Comment by clayjohn** [comment]
@Galaxy613 if it is just a skybox you need then you can render it to a Viewport then set the Viewport to the sky in your WorldEnvironment. 

This issue is more about having an entire scene running and interacting with the main scene + drawing after the main scene to optimize rendering. However, if its just a skybox you need, its perfectly doable now.

**Comment by Galaxy613** [comment]
True, I have a skybox up and running now, but having that whole extra scene for the skybox is what I really want for my game. I can think of many other ways to do it, but it would be so much better if Godot had a built-in way to handle background scenes.

**Comment by Flarkk** [comment]
Hi Godot team, just to know if this background scene feature was still in your plans for 3.2 milestone.

**Comment by aaronfranke** [comment]
It might make sense to do this as part of adding support for multiple cameras for viewport, which will need to wait until Vulkan is added (which was why #8215 was closed). I suggest bumping to 4.0.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by akien-mga** [comment]
Superseded by #355.
