### ISSUE TITLE
Have .tscn and similar files be standard TOML?

### ISSUE THREAD

**Issue by nicholatian** [godotengine/godot#10069]
- __Platform:__ All platforms
- __Godot version:__ 3.0 stable (intended)

At the moment, Godot seems to use its own derivative of TOML for nice, human-readable configuration files... but this is not standard. IMO, it would be healthy for Godot to use standards-compliant TOML to allow for easier automation and external reach. I think these are the things still left after you take out readability (both have it) and semantics (also irrelevant).

Also, another thought I had: perhaps schemas could have their extensions prepended to the `.toml` file extension, a la `.tar.gz` or `.pkg.tar.xz` or similar. This would mean the scene schema would become `.scn.toml` rather than `.tscn` (short for "text scene", right?), and `.scn` alone would still unambiguously mean the binary format in use.

I know Godot already supports XML, but as KidsCanCode pointed out earlier on the Discord server it's not exactly VCS-friendly (nor as easy to read)... but right now it seems to be the only option for a "standard" format for project metadata. Moving to standard TOML therefore kills two birds with one stone, making XML less relevant.

**Comment by reduz** [comment]
we use a pseudo.ini format with variables serialized in our own format
intended to be vcs friendly. There is zero benefit to adhering by the toml
standards, as no other application will be able to parse the godot
datatypes. I suggest closing this.

**Comment by nicholatian** [comment]
I was unaware that the format wasn't intended for any sort of intercompatibility, so I guess my suggestion is moot. Thanks for the insight 🙂

**Comment by rosshadden** [comment]
@reduz What about TOML is not vcs friendly?  There are many applications that a lot of use to read/write the data files, such as vim, emacs, atom, etc.  Also I am currently making a Godot data format parser, and I wouldn't have to if it used standard TOML because there are many tools to parse and write that.  I wouldn't have to create a custom syntax definition for vim that plays well with the comments, and whatever else.

I guess put another way, even if there is no benefit to adhering to an existing standard in your mind, what is the benefit to using your own?  So far one major difference I have seen in the formats is comments being `;` instead of `#`, which is just a stylistic change.

**Comment by punto-** [comment]
Ours is called JOML

**Comment by reduz** [comment]
@rosshadden Never implied TOML is not VCS friendly. The benefit of using our own is that we have a strict format for the data saved to it. If incorrect, our parser will explain exactly what is wrong and on which line of code.

A TOML parser is more general purpose and the format is more broad, almost anything is allowed.
