### ISSUE TITLE
Project Manager shows `(DEBUG)` as title

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#100727]
### Tested versions

v4.4.dev7.official [46c8f8c5c]

### System information

Godot v4.4.dev7 - Arch Linux #​1 SMP PREEMPT_DYNAMIC Mon, 09 Dec 2024 14:31:57 +0000 on X11 - X11 display driver, Multi-window, 2 monitors - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 3060 Ti (nvidia; 565.77) - 13th Gen Intel(R) Core(TM) i5-13400F (16 threads)

### Issue description

The title is the correct `Godot Engine - Project Manager` when loading (showing the splash screen). It turns into `(DEBUG)` when loading is done:

![Image](https://github.com/user-attachments/assets/9b3b8b39-6023-44d8-b375-6406a7562ee5)

### Steps to reproduce

Open the project manager.

### Minimal reproduction project (MRP)

N/A

**Comment by Giganzo** [comment]
Doesn't happen on v4.4.dev5.official [9e6098432]

**Comment by mdelorme** [comment]
Bisecting seems to show the culprit is commit ff6eea5

What's happening is : 
1. The project manager window is given a title at creation by directly going through the `DisplayServer` without using the `Window` node [here](https://github.com/godotengine/godot/blob/master/editor/project_manager.cpp#L1142))
2. The scene tree is initialized with everything.
3. Post "enter tree", commit ff6eea5 sends a `NOTIFICATION_TRANSLATION_CHANGED` to the nodes
4. The `Window` node receives the notification, and re-translates the title [here](https://github.com/godotengine/godot/blob/master/scene/main/window.cpp#L1436). However, to do so it uses the `title` variable that has never been set.

I'm really not sure how to proceed to fix this, because by the time the title is first set, the `Window` node does not exist and so we cannot set the `title` variable properly.

**Comment by AThousandShips** [comment]
Then the older more extensive solution I had might have been required, this particular change can't really safely be reverted as it solves a pretty serious crash

Can't really work on a fix for that part right now, but it shouldn't be relying on that detail I think, so something else is likely wrong

**Comment by AThousandShips** [comment]
Some other changes must have happend to cause this particular problem as the translation update *used* to be in this part of the initialization process, so something else must have shifted to make this a problem, the `title` has to be updated correctly probably at an earlier phase

**Comment by mdelorme** [comment]
Ok, I think we can solve simply the problem. I made a mistake : the root of the scene already exists when we give the title to the project manager initially. So we can give it a title instead of going directly to the `DisplayServer`. I'm testing a few more things and if that works I'll try to push a fix.
