### ISSUE TITLE
macOS export error: Couldn't load game path '.'

### ISSUE THREAD

**Issue by zedutchgandalf** [godotengine/godot#10086]
**Operating system or device - Godot version:**
macOS Sierra 10.12.6 - Godot 3.0 Alpha 1

**Issue description:**
Whenever I export a game to macOS and try to run it, it immediately crashes. This happens both with an export made from Windows and one made from macOS. When I use Terminal to execute the binary itself (under Content/MacOS/), I get the following error: "error: Couldn't load game path '.'".  
I can however execute the .app file if I do so from within the godot project folder. It's only when I move it somewhere outside of that folder that it no longer works.  
I'm using Godot 3.0 Alpha 1 and I'm sure I'm using the right export templates.  

**Steps to reproduce:**
1. Create a new, empty Godot project
2. Export the project for macOS with the default settings
3. Move the exported .app file to another folder
4. Try to run the .app file

**Link to minimal example project:**
[Godot_empty.zip](https://github.com/godotengine/godot/files/1200601/Godot_empty.zip)

**Comment by BastiaanOlij** [comment]
Owh weird, I have to give this a try when I'm home.

**Comment by reduz** [comment]
@BastiaanOlij Did you ever get home?

**Comment by akien-mga** [comment]
FWIW, this error means that the data pack is missing.

**Comment by BastiaanOlij** [comment]
@reduz lol, yeah I did but completely forgot about this.. Just tried it and something has indeed changed.

As far as I can see, it does create the package properly, puts the data pack in resources but when started it doesn't load it. Godot does tend to crash in this scenario, I fixed a bunch of things around this on Iphone, never got around to checking it for OSX. 

I don't know what has changed in the loading procedure however. I'll do some more testing.

**Comment by BastiaanOlij** [comment]
Ok, finally had a bit of time to investigate this further.

I don't know if these also apply to 2.1.4, I've only tested this in 3.0.

On OSX you place the data pack in the resources folder of the application bundle. For this there is code in godot_main_osx.mm which will change the current path to the resources folder. Because we now use the executables name for the data pack name it is extracted by calling get_basename which instead of just returning the base name also returns the path. It is thus ignoring the current directory and it can't find the data pack. Also get_basename searches for the last . to strip of the file extension but this is often not used on OSX so its strips off everything until the app bundles .app.

That said, it looks like Android and iOS have similar issues with placing the datapack and someone made a much more elegant solution by adding a get_resource_dir function to the OS.

I'm going to change the code in OSX to have this return the resource folder. That should fix this.

**Comment by BastiaanOlij** [comment]
One small foot note on this btw, @akien-mga, @reduz , there is an additional issue with get_basename.

As it searches for the . and therefor strips of the whole pack to get the name of the application bundle, that is a name that someone can easily change breaking the load.

It really should first strip off the path to get the executable name, and then search for the . in the resulting string. That is what I would expect get_basename to do anyway, its usually a function that returns the name of a file excluding path?

**Comment by akien-mga** [comment]
Fixed by #11062.
