### ISSUE TITLE
Make it possible for Light2D light to penetrate into obstacles until hitting a backface.

### ISSUE THREAD

**Issue by Asmageddon** [godotengine/godot#10092]
Example of the desired effect from a toy of my own:

![](http://i.imgur.com/rKiJ3EJ.png)

Includes penetration distance limit(in pixels) for large occluders, and a (broken) option to skip short gaps.

**Comment by eon-s** [comment]
That is not what cull mode does? (which, by the way, does not look good on Godot 3)

**Comment by Asmageddon** [comment]
Uh, I've opened a build of 3 and testing now, but no, I don't believe so. Which feature do you mean? Cull Mode on `OccluderPolygon`, Item Cull Mask on `Light2D`, or something I am missing?

**Comment by Asmageddon** [comment]
Here's a better example from a later version of my toy:

![](http://i.imgur.com/0xI8T2D.png)

**Comment by eon-s** [comment]
On 2 and 3, if you edit the occluder polygon, there is an option for cull mode cockwise and counter clockwise, and depending on how the occluder shape was made it will be the way it casts shadows.

![cullmode](https://user-images.githubusercontent.com/10215987/28987906-c5ed9534-7943-11e7-896a-9a2a45d4f622.png)

**Comment by Asmageddon** [comment]
As far as I can tell, that's incidential and doesn't work with every polygon either.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
