### ISSUE TITLE
_unhandled_key_input() is buggy when moving CharacterBody2D

### ISSUE THREAD

**Issue by The-oldone** [godotengine/godot#100966]
### Tested versions

- Reproducible in : v4.4-dev7, v4.3-stable, v4.2.1-stable(old)

### System information

Godot v4.3.stable - Windows 10.0.26100 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2050 (NVIDIA; 32.0.15.6636) - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

When using a velocity related computation in _physics_process(), if you modify velocity using _unhandled_key_input() and are using event.is_action_pressed(), the computation only repeats around 31 times if you hold the key for longer than 31 frames(it repeats more or less times sometimes)

### Steps to reproduce

1. Create a scene with the following hierarchy:
 ```
┖╴Node2D
    ┖╴CharacterBody2D
       ┠╴Sprite2D
       ┖╴CollisionShape2D
```
2. Attach a script to CharacterBody2D with the following code:
```gdscript
extends CharacterBody2D

var speed = 200
var i = 0

func _physics_process(_delta: float) -> void:
	if velocity.x != 0: #it works without this, but this block tells how many times the input is processed
		i += 1
		print(i)
	move_and_slide()

func _unhandled_key_input(event: InputEvent) -> void:
	velocity.x = 0
	if(event.is_action_pressed("ui_left")):
		velocity.x -= speed
```

3. Press the left arrow key for some time

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
I think you're confusing the methods `InputEvent.is_action_pressed` (what you're using) with the one from `Input` singleton `Input.is_action_pressed`

This is the docs from `InputEvent`
![Image](https://github.com/user-attachments/assets/9342a1e7-f542-419d-9daa-56731821e8fd)

This is the docs from `Input`
![Image](https://github.com/user-attachments/assets/c1c15228-7e98-4c31-861e-800ad545a052)

<br>

Look how in the InputEvent docs says about the event don't be an echo event, an echo event is when a key was already pressed and the pressed event is emited again, that means the key was already pressed when the second event was emited. That explains why work for a time and stops after, because is the time between the first event and the second event.

What you actually want to use is the `Input.is_action_pressed`, this one don't care about if is an echo event or not, just needs the correct key to be pressed.
