### ISSUE TITLE
Removed scene is recreated

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#100940]
### Tested versions

- Reproducible in v4.4.dev7.mono.official [46c8f8c5c]

### System information

Godot v4.4.dev7.mono - Windows 10 (build 19045) - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 threads)

### Issue description

Already deleted scene is recreated on scene save.

### Steps to reproduce

1. Open reproduction project.

![Image](https://github.com/user-attachments/assets/fc94f45e-ec2c-4f2c-b3a8-0a2049eda254)

2. select `myscene.gd` and `myscene.tscn` in the FileSystem view.
3. Select "Delete" from popup menu 
4. Confirm deletion by pressing "Remove" 
=> `myscene.gd` and `myscene.tscn` disappear from FileSystem view as expected. But the deleted scene is still visible in the scene tree.

![Image](https://github.com/user-attachments/assets/4f55c9b4-ee07-44d7-baf7-eca0d9ca461a)

5. Press `Ctrl-S` to save scene

**=> BUG**: `myscene.tscn` is back in FileSystem:

![Image](https://github.com/user-attachments/assets/b92e0e56-f405-4eb5-9d5b-987408d60b0a)

### Minimal reproduction project (MRP)

- created project
- created root node and a folder for myscene
- created myscene, added sprite and script

`.godot` folder (without `shaders` and `mono`) is included. It looks like that removing `.godot` folde will prevent scene recreation happening.

[scene_removing.zip](https://github.com/user-attachments/files/18276655/scene_removing.zip)

**Comment by kOyCHFqLJYDV** [comment]
It is still visible in the screen tree because you have the deleted scene still opened. As in, prior to deleting a scene, you should first close that scene in the scene editor. And it is also thus why it is re-created. Because it is still viable scene, as it is still open in the scene editor.

It has exhibited this behavior for quite some time now.

A solution would be to automatically close the scene in the scene editor when the user opts to delete the scene from the file system tree.

**Comment by tetrapod00** [comment]
The current behavior is intentional.

There is an open proposal for changing the behavior: https://github.com/godotengine/godot-proposals/issues/1550. And a prior PR to close open scenes when deleting the file was declined: https://github.com/godotengine/godot/pull/42885. However, at some point since that proposal was written (apparently https://github.com/godotengine/godot/pull/40647, though I didn't check), deleting a *script* file now also removes the script from the script list. So there now is an inconsistency between scripts and scenes, at least.

I'd suggest using that linked proposal to continue discussion.
