### ISSUE TITLE
Editing a custom `ArrayMesh` from the inspector steals mouse control and interrupts the edit

### ISSUE THREAD

**Issue by MajorMcDoom** [godotengine/godot#100917]
### Tested versions

Reproducible in 4.3.stable and 4.4.dev5

### System information

Godot v4.4.dev5 - Windows 10.0.22631 - Multi-window, 1 monitor - OpenGL 3 (Compatibility) - NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 32.0.15.6636) - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 threads)

### Issue description

When using the mouse to drag a value for a custom `ArrayMesh`, and the custom mesh's script uses  `ArrayMesh.add_surface_from_arrays` to regenerate the mesh, it causes the mouse to lose grip of whatever control it was interacting with, and snap to the middle of the screen.

The use case here is implementing a custom, parametric mesh type. This bug makes it impossible to tweak the mesh with the mouse. You have to manually type in values.

Notes:
- This bug also happens if you use something like `MeshDataTools` or `SurfaceTool` to modify the mesh.
- This bug does _NOT_ happen if you use something like `ArrayMesh.surface_update_vertex_region`, but that does not perform all the necessary operations of generating a mesh (e.g. adding new vertices, triggering an AABB recalculation, etc.).
- UPDATE: This bug does _NOT_ happen if you use `RenderingServer.mesh_clear` and `RenderingServer.mesh_add_surface_from_arrays`.

![Image](https://github.com/user-attachments/assets/2bef0984-b262-4cd7-b260-020208a8c03b)

### Steps to reproduce

- Open the attached project/scene.
- Select the `triangle` node, and inspect its mesh, which has a `custom_mesh.gd` script attached.
- Use the mouse to edit its `Size` property.
- Observe that the value only changes by a small amount before the cursor is stolen away.

### Minimal reproduction project (MRP)

[bug-report.zip](https://github.com/user-attachments/files/18271228/bug-report.zip)

**Comment by smix8** [comment]
The reason drag does not work here is because you are replacing the entire mesh and redrawing the full resource inspector. So basically what you try to drag you remove. You just don't see it because it gets replaced so quickly.

When you use the `ArrayMesh.surface_update_vertex_region` you are actually only updating part of the existing Mesh which is why it works.

**Comment by MajorMcDoom** [comment]
> The reason drag does not work here is because you are replacing the entire mesh and redrawing the full resource inspector. So basically what you try to drag you remove. You just don't see it because it gets replaced so quickly.
> 
> When you use the `ArrayMesh.surface_update_vertex_region` you are actually only updating data parts of the existing Mesh which is why it works.
> 
> You would need to use a custom inspector that can keep your properties and does not target the resource directly. You can't use the generic resource inspector when the resource gets replaced on changes. E.g. Skeleton3D and others all use custom inspectors for this very reason. This is an older issue that I have seen before around here so there are some duplicates to find.

I'm not understanding why recreating a surface in an `ArrayMesh` would replace the entire resource. Why is that necessary?
Also not understanding the `Skeleton3D` comparison because that's a node, not a resource.

**Comment by MajorMcDoom** [comment]
UPDATE: Replacing the calls with the `RenderingServer` equivalents does _not_ cause this bug! 😲
```gdscript
RenderingServer.mesh_clear(get_rid())
RenderingServer.mesh_add_surface_from_arrays(get_rid(), RenderingServer.PRIMITIVE_TRIANGLES, arrays)
```

**Comment by MajorMcDoom** [comment]
**UPDATE 2**:
It seems like the culprit is `notify_property_list_changed()` being called in `ArrayMesh`'s native methods.
So this is a general issue of mouse control being taken away whenever the inspector has to be rebuilt as a consequence of `notify_property_list_changed()`. As such, I think this bug can be closed. I'm not sure if this is fully avoidable, but at least there's the workaround of using the `RenderingServer`.

**Comment by smix8** [comment]
To add to this yes `notify_property_list_changed()` causes a redraw of the resource inspector and since a mesh has a lot of "dynamic" properties for the surfaces a new drawn resource inspector has no track of the old slider that was e.g. dragged so the focus and input gets lost.

Skeleton3D was just one example for a custom inspector and why a simple resource inspector often does not work for more complex things. E.g. something touches a bone transform and the entire skeleton inspector would need to redraw. That would be even worse than this issue here with the ArrayMesh.
