### ISSUE TITLE
Edit an exported scene var from the inspector's dropdown menu

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#10145]
If you export a variable to get another scene reference in current one. You get a nice line in the inspector representing the scene. But if you want to edit it, you are to open it manually, though it is right there. It would be a nice feature if user could be able to open/edit the scene from the dropdown menu in the inspector. Fro now you can only 'Edit' the resource properties of the scene, which is not quiet what is expected.

Is applicable for both 2.x and 3.x branches.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by akien-mga** [comment]
This is already possible:
```
export(PackedScene) var myscene
```
![Screenshot_20200526_155054](https://user-images.githubusercontent.com/4701338/82908739-b2004a00-9f68-11ea-9862-0f8e5e839cab.png)
