### ISSUE TITLE
OS.execute doesn't run all the programs

### ISSUE THREAD

**Issue by samvila** [godotengine/godot#10172]
**Operating system or device - Godot version:**
Godot 3.0 Alpha 1

**Issue description:**

Using something like this works:

OS.execute("notepad", StringArray([]), false)
OS.execute("calc", StringArray([]), false)

but something like this doesn't:

OS.execute("regedit", StringArray([]), false)
OS.execute("cmd", StringArray([]), false)
OS.execute("powershell", StringArray([]), false)

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by samvila** [comment]
I figure out the problem, I had to run Godot using administrator rights. You can close this ticket.

**Comment by samvila** [comment]
I tried to run cmd.exe or powershell.exe using Godot as admin and I couldn't make it work. Regedit works fine.

**Comment by deltasquad451** [comment]
So when launching Godot on MS Windows you will have a two windows pop up the command prompt and the Godot editor, so when you do OS.execute("cmd", StringArray([]), false) or OS.execute("powershell", StringArray([]), false) it creates another cmd/powershell within the currently existing command prompt:
![image](https://user-images.githubusercontent.com/5035101/29154378-0a85610a-7d49-11e7-9f9c-e86597aa996a.png)

**Comment by bojidar-bg** [comment]
You might have searched online for solutions.
Here is a [Stack overflow question](https://stackoverflow.com/questions/9392874/bat-file-open-new-cmd-window-and-enter-code-in-there), which seems related to what you ask.

Basically, you should do something like this, in order to pass `cmd.exe` the `/K` flag, which would cause it to start up a new window.
```gdscript
OS.execute("cmd", StringArray(["/K"]), false)
```
Additionally, to start powershell, you __might__ have to do this:
```gdscript
OS.execute("cmd", StringArray(["/K", "powershell"]), false)
```

(Note that the above code is untested, as I'm on linux)

**Comment by samvila** [comment]
@deltasquad451 Thanks, now I understand why I couldn't see any result on screen. I though it was a bug or a limitation on Godot. I will close this ticket. Thanks again.
