### ISSUE TITLE
Editor Usability

### ISSUE THREAD

**Issue by Causeless** [godotengine/godot#10201]
Hey, I didn't create this video (nor have any Unity experience) but I found this which highlighted a couple usability issues within Godot.

https://youtu.be/lRbefcsYDi4

* Difficulty selecting desired node
* Arrow keying through scene graph doesn't highlight current node
* Moving objects must be done per axis instead of on a plane
* Cannot drag/drop scenes directly into the editor view window
* No easy way to move objects large distances (i.e move to mouse position)

Understandably these are minor and all have easy workarounds within the engine if you know what you're doing, although given that one of Godot's main themes is ease-of-use I feel like some changes here to make some operations more intuitive wouldn't be a bad idea.

**Comment by Zireael07** [comment]
It's been already posted as a comment on #2852 but I guess it'll get more visibility as a separate issue.

**Comment by Zylann** [comment]
Could use 3D color picking?

**Comment by tagcup** [comment]
> Moving objects must be done per axis instead of on a plane

I might be wrong but I vaguely remember there is a "secret" keyboard shortcut for this in the property editor (change the value in one of the axes and press shift+enter), although that's not with mouse and only works in the global axes and not in the local axes.

**Comment by toger5** [comment]
@Causeless would you mind changing this to a check list since a lot of that is fixed:
```
 - [x] Difficulty selecting desired node
 - [ ] Arrow keying through scene graph doesn't highlight current node
 - [x] Moving objects must be done per axis instead of on a plane
...
```

**Comment by toger5** [comment]
just checked the current master state:
Honestly I think this issue can be closed.

 - [x] Difficulty selecting desired node
 - [x] Arrow keying through scene graph doesn't highlight current node
 - [x] Moving objects must be done per axis instead of on a plane
 - [x] Cannot drag/drop scenes directly into the editor view window
 - [ ] No easy way to move objects large distances (i.e move to mouse position)

All of that is fixed. and works (just tested)
the last one is a little ambiguous anyways.
So I would propose closing this one and adding a issue which proposes how the movement over long distances should work.

> issues should usually only consist of one issue at a time. Makes it much easier to organise them.

(selling this as a quote... I don't know if someone has said that before. but I think I hear it once or twice)
