### ISSUE TITLE
MultiMesh does not change color of instances

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10217]
**Operating system or device - Godot version:**
windows, e8192d4

**Issue description:**
i'm using this code
```
    var mm = MultiMesh.new()
    mm.transform_format = MultiMesh.TRANSFORM_3D
    mm.mesh = test
    mm.color_format = MultiMesh.COLOR_FLOAT
    mm.instance_count = 1
    mm.set_instance_color(0, Color(1,0,0,1))
    var mmi = MultiMeshInstance.new()
    mmi.multimesh = mm
    add_child(mmi)
```
but it changes nothing at all
actually there was the same issue for 2.1, but it was not confirmed for 2.1
https://github.com/godotengine/godot/issues/5565

**Link to minimal example project:**
https://www.dropbox.com/s/qn6nhhjs60n0m1x/multimesh.zip?dl=0

**Comment by kubecz3k** [comment]
I'm able to confirm in 6efd777faeb11b42c41d8eccf29274defb20acd9 build

**Comment by henkz1** [comment]
There's no bug. The color is vertex color so you need set vertex color->use as albedo in your SpatialMaterial to see any change.

**Comment by kubecz3k** [comment]
@henkz1 wow you are right! Thank you very much! :beer: 
I was putting some time recently into looking at MultiMesh code because of this issue recently :) 
I'm attaching working sample for anyone interested: 
[multimesh_color.zip](https://github.com/godotengine/godot/files/1296677/multimesh_color.zip)
