### ISSUE TITLE
Godot should look for export template at system-wide level too

### ISSUE THREAD

**Issue by shackra** [godotengine/godot#1026]
that's all :)

**Comment by akien-mga** [comment]
+1 for this, I'm currently looking at packaging Godot 1.0-stable for Mageia, but this issue is what is stopping me so far.
I've been thinking of putting system-wide templates in ```/usr/libexec/godot```, this has the advantage of being arch-independent (so you can have both 32bit and 64bit templates in the same folder) and made for binary content (contrarily to ```/usr/share/godot``` that would be more for noarch stuff).
