### ISSUE TITLE
Can export to Wii U

### ISSUE THREAD

**Issue by Plasmmer** [godotengine/godot#10269]

**Comment by reduz** [comment]
This is not legally possible, Nintendo SDKs are secret and you have to sign a license to use them. We can't provide a port here for their platform without breaking the law.

**Comment by Plasmmer** [comment]
Then how can Scirra supports Wii U export with Construct 2?

**Comment by BrainBlasted** [comment]
@Plasmmer Scirra made a deal with Nintendo, probably, and you still need to be a registered Wii U developer, with access to the official Wii U dev forum.

**Comment by MacAddict81** [comment]
What about porting Godot Engine using [WUT](https://github.com/devkitPro/wut)? It's GPL-2 Licensed, and even thought it doesn't provide a pathway for developers to port to the Nintendo Wii U eShop, it would provide hobbyists a pathway for Homebrew Games developed for the platform.

**Comment by FoxbitDreamtail** [comment]
> What about porting Godot Engine using [WUT](https://github.com/devkitPro/wut)? It's GPL-2 Licensed, and even thought it doesn't provide a pathway for developers to port to the Nintendo Wii U eShop, it would provide hobbyists a pathway for Homebrew Games developed for the platform.

I want to add on to this, I recently was searching if anyone had thought that it would be possible to do that and I wanted to create a Luigi's Mansion fan port for Wii U because it never happened, I thought that Godot would be the perfect engine for it, however seeing that they're not even interested in Homebrew is sad, especially considering that here in the future, the eShop is even discontinued.
