### ISSUE TITLE
Can export to Nintendo 3DS

### ISSUE THREAD

**Issue by Plasmmer** [godotengine/godot#10270]

**Comment by reduz** [comment]
You did not mention Switch, man, are you trolling? Read previous issue, anyway.

**Comment by calegxm999** [comment]
https://gbatemp.net/threads/wip-godot-engine-for-3ds-homebrew.446385/
There's a godot engine for 3ds. Read this...

**Comment by sonic2kk** [comment]
That project has been long since abandoned, even when this ticket was opened the project was [still abandoned](https://github.com/Cruel/godot/tree/3ds). The last commit was on October 27th 2016 and it is over 22,000 commits behind!

An interesting concept for Homebrew, I wonder why no one picked it up again.

**Comment by LikeLakers2** [comment]
You two should check out the documentation's answer on this: https://docs.godotengine.org/en/stable/tutorials/platform/consoles.html It should help you understand why Godot doesn't (and probably never will) officially support consoles.
