### ISSUE TITLE
Project manager's file system box should be updated to match the ones within projects

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#10301]
The "file system" dialog box used when creating/importing a project is pretty barebones compared to the one used within projects:

File system box seen when importing a project within the project manager:
![bad](https://user-images.githubusercontent.com/27100585/29240704-062e297c-7fae-11e7-8e80-7e8b87b73d74.png)

File system box seen when loading a Sprite node's texture within a project:
![good](https://user-images.githubusercontent.com/27100585/29240707-0d43d7e8-7fae-11e7-9fb5-3fb74ff06902.png)

The navigation icons at the top-left alone would go a long way towards improving its usability, but I think it could also use things like the darkened background (I expect this will be added down the line anyway), an icon view, and even a favorites panel.

**Comment by Cradmon** [comment]
This would be helpful to consistency through the editor.
Although, the file system box could do with an update, for example:

- The icon view should probably be a toggle button, to be consistent with the file system dock.
- And why is there a ./ folder? (Much appreciation to anyone who could explain its purpose).

**Comment by KoBeWi** [comment]
Looks like the file dialog in project manager changed a bit since the issue was created. What else could be done to close this issue, or is that enough? (from mentioned stuff, it's still missing two navigational arrows in the top-left)

**Comment by homer666** [comment]
Somehow I forgot to reply to this.

I think the navigational arrows are still important (though it's not like I spend enough time in the project manager to be really bothered by it). I don't know if an icon view is really worth it since I don't think there'll be any thumbnails for anything outisde of a project (since they won't be imported resources). The recent/favourites panels are probably more effort than they're worth.

I'm gonna leave this issue open, since I'll probably get around to implementing the navigational arrows myself someday.

**Comment by Anutrix** [comment]
This seems to have been fixed in master. This is file system dialog seen when importing a project within the project manager::
![image](https://github.com/godotengine/godot/assets/11459028/015106f5-b240-47f6-8475-57663c4a55ac)
