### ISSUE TITLE
When closing a scene, its built-in scripts may stay in the Script Editor

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#10423]
**Ubuntu 17.04 - Godot build: 95f5470**

**Issue description:**
Normally, when closing a scene, its built-in scripts are removed from the Script Editor. But sometimes they may stay after the scene is closed.

It seems to aways happen when closing the main scene.

**Comment by YeldhamDev** [comment]
@akien-mga Sorry to bother you again, but could add this to the milestone?

**Comment by akien-mga** [comment]
> could add this to the milestone?

I add to the milestone things that *must* be fixed before the release. This one can be fixed anytime by a contributor, but it doesn't look that bad to me that it should prevent releasing 3.0-stable.

**Comment by LikeLakers2** [comment]
I never thought this was an issue. Is it an issue? I was fairly sure specific scripts aren't completely linked to a scene, as you can reuse the same script for multiple objects and such. (Or at least, Godot makes no attempt to prevent you from doing such a thing) Thus I'm not sure it's an issue that scripts aren't removed when a scene is closed, since they're supposed to be linked and not really exactly require each other.

**Comment by YeldhamDev** [comment]
@LikeLakers2 It happens with built-in scripts, so yeah, these should go when the scene is closed.

**Comment by LikeLakers2** [comment]
@YeldhamDev Ohhhh, okay. My bad, feel free to ignore me. I'm used to storing scripts in their own files rather than as built-in scripts.

**Comment by KoBeWi** [comment]
This happens when the scene using built-in script is instanced on another opened scene. The reference to the script isn't freed, so it's not closed.

**Comment by KoBeWi** [comment]
I also noticed that it always happens when closing a tab that isn't currently focused, e.g. when middle-clicking another tab or using "Close tabs to the right" etc.
