### ISSUE TITLE
rand_from_seed needs a cleanup

### ISSUE THREAD

**Issue by iajrz** [godotengine/godot#1043]
As far @grabiller and I could work out from rand_from_seed in math_funcs.cpp, there are some inconsistencies in the function; among those:
- line 50 winds up being s = -2836*s/127773
- the condition in line 51 can never be true, therefore line 52 never executes

**Comment by akien-mga** [comment]
@iajrz Looks like you never got to make this PR?

**Comment by iajrz** [comment]
@akien-mga The HDD I was working on died before I pushed the changes to my remote repo. I am still in pain over that. It's a bit unlikely that I set the dev-env up and write the code again 'cause of what I'm doing [now](http://www.iajrz.com/now), but if/when I find the time to do it, I'll let you all know in this thread.

**Comment by SuperUserNameMan** [comment]
@iajrz :
Wow ... I hope there is no curse on ``Math::rand_from_seed()``, because I definitively don't want my HDD to die if I manage to successfully succeed you on this task :-/

I tried to improve the randomness of the baking light baker here #6683 by replacing ``rand()`` by a multithread-safe and non c++11 cross-platform PRNG.
I tried with the godot's ``Math::rand_from_seed()`` and found it was giving poor randomness compared to MT19937 or XONOROSHI128PLUS.
And I've added and set MT19937 as default for the baker.

Now, I would like to improve ``Math:rand_from_seed()`` to gives better characteristics (like higher periodicity).
But the first problem i'm encountering, is that I find difficult not to break the API.

The seed of ``Math::rand_from_seed()`` that is passed as parameter and returned as result is not just a seed, it's also the 32bits state of the PRNG.
And in most other PRNG algorithms that I tried in #6683, the smallest state is 64 bits.

For instance, the suggested Mersenne Twister PRNG, standardized as MT19937, has a state of 20000 bits (2500 bytes), which would be difficult to pass and return through ``Math::rand_from_seed()``.

Could you try to remember how you proceeded to improve ``Math::rand_from_seed()`` without breaking API ?

**Comment by SuperUserNameMan** [comment]
Wow ... I hope there is no curse on ``Math::rand_from_seed()``, because I definitively don't want my HDD to die if I manage to successfully succeed you on this task :-/

So a 32bits Xorshift PRNG : 
````
uint32_t seed = 7;  // 100% random seed value

static uint32_t random()
{
  seed ^= seed << 13;
  seed ^= seed >> 17;
  seed ^= seed << 5;
  return seed;
}
````
found here : http://excamera.com/sphinx/article-xorshift.html

**Comment by SuperUserNameMan** [comment]
well, given that ``Math::RANDOM_MAX`` is ``0x7FFFffff``, the periodicity of this Xorshift32 PRNG "might be" 2^31 - 1.

I say "might be", because i'm not good enough with mathematics to understand if masking the returned seed with ``Math::RANDOM_MAX`` actually change Xorshift32 into Xorshoft31 ...

````
uint32_t Math::rand_from_seed(uint32_t *seed) {
	if ( *seed == 0 ) *seed = Math::RANDOM_MAX;
	(*seed) ^= (*seed) << 13;
	(*seed) ^= (*seed) >> 17;
	(*seed) ^= (*seed) << 5;
	return (*seed) & Math::RANDOM_MAX;
}
````

**Comment by iajrz** [comment]
I'll just test the periodicity for your function... been looking for an excuse to test CLion :smile:

**Comment by iajrz** [comment]
@SuperUserNameMan: with the masking you're using, I've found seed 6873698 has a period of 127. I think that is too low. 😢 

This is what I used to find it:

```
uint32_t rand_from_seed(uint32_t *seed) {
    if (*seed == 0) *seed = 0x7FFFffff;
    (*seed) ^= (*seed) << 13;
    (*seed) ^= (*seed) >> 17;
    (*seed) ^= (*seed) << 5;
    (*seed) &= 0x7FFFffff;
    return (*seed);
}

long long period_for_seed(uint32_t seed,long long worst) {
    auto current_value = seed;
    long long i = 0;
    do {
        rand_from_seed(&seed);
        i++;
    } while (current_value != seed && i < worst);
    return i;
}

int main() {
    uint32_t current_seed = 0;
    uint32_t worst_seed = 0;
    long long worst_period = 1806079066;

    while (current_seed < 1806079066) {
        current_seed++;
        long long current_period = period_for_seed(current_seed,worst_period);
        if (current_period < worst_period) {
            worst_period = current_period;
            worst_seed = current_seed;
            std::cout << current_seed << "; seed: " << worst_seed << " period: " << worst_period << std::endl;
        }
    }
    return 0;
}
```

**Comment by iajrz** [comment]
A good question is: why, if the function returns a uint32_t, is the value truncated to 31 bits? I would understand if it were signed. Any ideas?

**Comment by iajrz** [comment]
This code is only ever called by gdscript and visualscript, and I see both the truncated value that is returned, and the non-truncated value that is set into the seed, passed as an array. I can't make time to trace the code any further, but the reason behind that should probably be cleared up before we keep playing around with this.

**Comment by SuperUserNameMan** [comment]
Well, I guess that ``Math::rand_from_seed()`` was masked to 31bits to keep it compatible with GDscript signed integers.

I will investigate a little further later this week when i'll have more free time to focus on it.

**Comment by iajrz** [comment]
I think I understood what's happening with the return value and the one set on the seed's memory: the value is masked, but the seed is not, so that the 32-bit algorithm can work properly. If when you check this holds true, it would mean that you could use the 32-bit algorithm you found in this form:
```
uint32_t rand_from_seed(uint32_t *seed) {
    if (*seed == 0) *seed = 0x7FFFffff;
    (*seed) ^= (*seed) << 13;
    (*seed) ^= (*seed) >> 17;
    (*seed) ^= (*seed) << 5; /* seed is 32 bits, and is going to be used in the future. */
    return (*seed)&0x7FFFffff; /* current value is signed int (thus, masking the 32nd bit to 0 to keep it positive)*/
}
```

**Comment by SuperUserNameMan** [comment]
What bothered me was the ``int / uint32_t`` castings involved between C++ and GDscript in ``rand_seed()`` ...

As I did not code in C for long time, I forgot that the casting between signed and unsigned was not destructive. 

So, yes, the masking can be applied only to the returned result and not to the stored seed.
I'm going to update the PR.

**Comment by SuperUserNameMan** [comment]
Well, as for the periodicity of this PRNG, as long as the stored seed remains 32bits, it should remain 2^32 - 1.
The natural periodicity of Xorshift32 will be altered only if the stored seed is altered somewhere between the signed/unsigned int conversions that happen between C++, Variants and GDscript.
  
````
uint32_t rand_from_seed(uint32_t *seed) {
    if (*seed == 0) *seed = 0x7FFFffff;
    (*seed) ^= (*seed) << 13;
    (*seed) ^= (*seed) >> 17;
    (*seed) ^= (*seed) << 5; 
    return (*seed)&0x7FFFffff; 
}
````
