### ISSUE TITLE
default light option does not exist anymore.

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10451]
<img width="253" alt="screen shot 2017-08-19 at 18 01 26" src="https://user-images.githubusercontent.com/16718859/29488315-7313dee2-8508-11e7-9e62-a8f3e1a34beb.png">
<img alt="screen shot 2017-08-19 at 18 01 26" src="https://s10.postimg.org/pp3qxti15/Untitled_1.jpg">

so the game looks lighter in editor...

_editor screenshot_
<img width="809" alt="screen shot 2017-08-19 at 18 02 55" src="https://user-images.githubusercontent.com/16718859/29488330-d0243302-8508-11e7-9c6e-2c32698bf41f.png">

_game screenshot:_
<img width="1093" alt="screen shot 2017-08-19 at 18 03 53" src="https://user-images.githubusercontent.com/16718859/29488331-d048aebc-8508-11e7-8ac0-b91d1158a5c0.png">

**But the weirdest part is:**
when I start the scene from the camera perspective preview it is using the same color than in the editor:

_game screenshot:_
<img width="1008" alt="screen shot 2017-08-19 at 18 03 01" src="https://user-images.githubusercontent.com/16718859/29488342-0481a198-8509-11e7-9421-9b48fe6b1119.png">

It makes not difference when starting the project or the scene

**Comment by Zylann** [comment]
I remember it was removed because it could cause confusion or something...

However, I think it should be added back, because everytime I edit a 3D scene (character, projectile, prop...) it often has no lights in it because I put them in levels/world instead. As a result, almost all my scenes are in darkness:

![image](https://user-images.githubusercontent.com/1311555/29488895-8d5cff70-8514-11e7-9ca4-984fdd0015bd.png)

**Comment by Zireael07** [comment]
Me too, I have a ton of child scenes with no lights since the only lights I need are in the world scene...

**Comment by novemberist** [comment]
Doesn't the "Ambient light" setting in the default environment sort of do the same job?

**Comment by toger5** [comment]
@novemberist yea this is probably the best solution for now and maybe a pretty good one. since you always can use a custom env for your mains scene.

But there is definitely something buggy going on: 
the I restarted the project the editor viewport also used the darker version.
and the "going into camera perspective makes it bright/(the same than the editor)" is also buggy

**Comment by reduz** [comment]
This is intended. There is no more default light. It was always confusing.

I was thinking about changing the Light options so besides being optionally
editor only, making it local-scene only.

This way you can instance a light and use it for preview, so it is only
enabled when editing that scene.

On Aug 19, 2017 9:43 PM, "Timo" <notifications@github.com> wrote:

@novemberist <https://github.com/novemberist> yea this is probably the best
solution for now and maybe a pretty good one. since you always can use a
custom env for your mains scene.

But there is definitely something buggy going on:
the I restarted the project the editor viewport also used the darker
version.
and the "going into camera perspective makes it bright/(the same than the
editor)" is also buggy

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/10451#issuecomment-323556075>,
or mute the thread

**Comment by Zylann** [comment]
@toger5 @novemberist  Ambient light is not useful, because when set to a light color, models have no shading at all.

![image](https://user-images.githubusercontent.com/1311555/29491265-2cbcf49e-8556-11e7-842d-bdc340ba65fc.png)

![image](https://user-images.githubusercontent.com/1311555/29491269-4bdb73be-8556-11e7-96cb-5f6f0ee87b00.png)

**Comment by fracteed** [comment]
Having some sort of default light option would also be very useful when working on a scene that is lit only by only illuminated textures/giprobe. When setting up such a scene you have to add dummy lights just to be able to work in the scene, since there is no light from an ambient sky environment or lights.

Would also be very useful to have a combination display mode of unshaded and wireframe :)

**Comment by reduz** [comment]
@fracteed, @zylann I don't want to add a default light because it is very confusing for users to have it appearing by default while editing. It can be misleading. It is also annoying to have to disable it every time it was not needed.

Adding a dummy light and set it only for it to be enabled  while on editor and while editing the scene it belongs to seems like a more reasonable choice to me.. and just a couple of seconds per scene imported..

**Comment by reduz** [comment]
Sorry, misclick in mobile browser

**Comment by fracteed** [comment]
@reduz, sounds like a good solution, especially if these dummy lights do not contribute to the giprobe calculations. I guess that one of the main advantages to a default light in most 3d packages is that the default light is parented to the viewport camera. Whereas your solution would probably require several lights (depending on the scene). Having said that your solution is much more flexible, so I would be happy with it! Btw, is a combined unshaded/wireframe display mode a possibility?

**Comment by toger5** [comment]
I close this one since the proposed solutions are good enough. (if not better than default light.)

For anybody running into the same issue:
<img width="208" alt="screen shot 2017-09-25 at 12 10 13" src="https://user-images.githubusercontent.com/16718859/30803615-880bae2a-a1ea-11e7-8edb-ed3b535b7752.png">

this is what you are supposed to use now.
