### ISSUE TITLE
ShortCut can be used only with InputEvents

### ISSUE THREAD

**Issue by groud** [godotengine/godot#10497]
While working on the CanvasItemEditor, I figured out that a lot of keyboard "shortcuts" were hardcoded into the code, and thus could not be modified in the editor preferences. 

The problem is the following: the `ShortCut` node (scene/gui/input_action.h) has an` is_shortcut(const Ref<InputEvent> &p_event)` function to test whether or not an InputEvent corresponds to the recorded shortcut. However, there is no way to test is the keys in the shortcut are currently pressed or not (like with `Input::get_sigleton()->is_key_pressed()`), unless using something like in `spatial_editor_plugin.cpp`:
```
int key_left = ED_GET_SHORTCUT("spatial_editor/freelook_left")->get_shortcut()->cast_to<InputEventKey>()->get_scancode();
if (input.is_key_pressed(key_left)) {
...
}
```
The problem is that this code does not handle shortcuts with key modifiers (ctrl, alt, shift) :/. Also, shortcuts using mouse buttons instead of keyboards key would not work. 

I can see those two solutions to the problem:
- We implement a `is_pressed()` function in the ShortCut interface.
- We implement an `is_key_pressed_with_modifiers()` function in the `Input` interface

**Comment by Hinsbart** [comment]
What's the problem with using `is_shortcut`? That's the way it's done everywhere in the editor and it also handles modifiers.

If we add a function to get the shortcut state outside of  `_input()` you won't be able to set the events as handled for the node that checks it, making overlapping shortcuts for different parts of the editor impossible. (Or very hacky I guess)

**Comment by groud** [comment]
The problem is that with `is_shortcut`, you need an InputEvent. 

If you have a look to `editor/plugins/canvas_item_editor.cpp` (I am working of this file :) ) you can see there are actually a lot of keys checked with `Input::get_singleton()->is_pressed(KEY_...)`, especially when dealing with mouse events. As an example, when moving the mouse with button left pressed, we check if the space bar is pressed or not to check whether to pan the view or not. Thus, while we are dealing with a mouse motion event, we need to poll the keys state. If we want to make the KEY bindable within the editor preferences, we have no other way to use `ED_SHORTCUT(...)`, which keys cannot be polled for the current states as it needs an InputEvent. 

Indeed, we could use a boolean to store the status of the shortcut (set to true when we detect a pressed event, and to false when we have a release one), but this is tedious in most cases.

> If we add a function to get the shortcut state outside of _input() you won't be able to set the events as handled for the node that checks it, making overlapping shortcuts for different parts of the editor impossible. (Or very hacky I guess)

I dont know for that, if we define the shorcut with ED_SHORTCUT, probably that the event get caught anyway.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
