### ISSUE TITLE
Changing transform values in property editor doesn't update dependent values

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#10574]
Changing scale or rotation doesn't update how the transform matrix part looks like in the property editor:

![screenshot_20170822_204601](https://user-images.githubusercontent.com/16531565/29593865-f997853a-877a-11e7-965b-62961edab6a3.png)

(the first number in Transform should be 2).
Converse isn't true though: changing a value in the Transform updates translation, rotation and scale.

**Comment by tagcup** [comment]
Also a little bit tangential but it would be nice to have a small reset button near each of those, which would return them to their default values.

**Comment by tagcup** [comment]
@reduz Do you think this can be fixed with the new inspector in place?

**Comment by DualMatrix** [comment]
Still relevant in master

**Comment by rogeriodec** [comment]
Same here:

![](https://i.imgur.com/LlykTNB.png)

**Comment by aaronfranke** [comment]
I'll pile on two additional issues with Transform in the inspector, since they should probably all be solved at once due to being related:

* Showing the origin vector is pointless due to it being guaranteed to be the exact same as the "Translation" section above. Instead, it should only show the `Basis` part.

* The matrix is displayed transposed. The columns of the matrix are displayed here horizontally, and the rows of the matrix are displayed vertically. This is quite confusing.

**Comment by akien-mga** [comment]
The OP has been fixed in 3.0 with #8248, and https://github.com/godotengine/godot/issues/10574#issuecomment-471227244 was fixed in 3.2 by #34019.
