### ISSUE TITLE
Box2D physics engine implementation ?

### ISSUE THREAD

**Issue by rcmz** [godotengine/godot#10592]
I've heard multiple times that implementing Box2D would not be great but I don't understand why ?
If you know the reason, can you explain it to me ?

I am currently developing a module to add Box2D as an option. But I only have a very basic level in C++ so I doubt I can do it. I think it would be a great way to fix the poor physics wile adding tones of features (specially joints)

Let me know what you think of all of that !

**Comment by reduz** [comment]
Current 2D physics engine is much easier to fix, will be fixed in 3.1.
You already have joints btw.

**Comment by nhydock** [comment]
I feel like Box2D is one of those things that just because everyone uses it doesn't mean it's good.  Horror stories of the drawbacks of Box2D pop up frequently about how glitchy or slow it is, how it's rarely ever suited for the kinds of physics that people want to develop games around, and its API is far from friendly.  It's used for prototyping in the beginning but more often than should really be the case people stop using it and spin up their own physics solution instead.  

Godot's 2D physics, while not "industry standard", are easy to jump into and use, and offers decent performance.  I don't want to see a lot of effort mainline focusing on replacing the current physics implementation with another one that people are going to replace themselves anyway.

**Comment by eon-s** [comment]
I would prefer a review of what is lacking of the current 2D physics engine (like better constraints, fractures, soft bodies, liquid sim, etc.) and try to fill the gaps.

But you are free to try, if you can implement something and test performance like all the work that was made with bullet before presenting the PR, it may get the attention of other devs.

While Box2D code is not hard to grasp, it may give you some extra work to bring to Godot since I believe it is made for C++11.

**Comment by curly-brace** [comment]
In my opinion the best 2d physics is NAPE, but it is written in HAXE (may be translated to c++ tho), but it is abandoned. so yeah, i think too, that godot's 2d physics is better then box2d

**Comment by rcmz** [comment]
Ok thanks to all of you for your responses
I will concentrate my efforts onto making the current physics engine better 
Is there a guide on how the physics engine works beside reading the API ?

**Comment by RandomShaper** [comment]
@rcmz, just study the sources. As an starting point, it's interesting to understand everything has a front side (nodes in scene) and a back side (stuff in the physics server) and how both sides interact.

Another interesting thing is a broad phase comes first, then a detailed phase (not called as such in the code).

Then you can trace test projects where collisions, etc. happen and watch where the code flows along.

**Comment by rcmz** [comment]
Ok tanks for your suggestions
I'm trying to solve this issue : https://github.com/godotengine/godot/issues/10580
I did a bit of investigation an I'm pretty sure the issue does not come from the GrooveJoint2DSW::solve function

**Comment by RandomShaper** [comment]
Anytime! Good luck!

Physics are a bit involved, but as soon as you start to feel comfortable with the implementation, the feeling is very satisfying.

I've learnt a lot with that.

**Comment by novemberist** [comment]
Since it looks like we might be getting Bullet as an alternative/replacement for Godot's 3d physics engine soon, does anyone know how well Bullet actually supports 2d physics? maybe it's good enough to be used for 2D physics in Godot as well...

**Comment by rcmz** [comment]
![](http://i.imgur.com/l9LgEp1.png)

(sorry for the dirty screenshot)

**Comment by novemberist** [comment]
Mhm, I could swear I recently read somewhere, that Bullet does have some amount of 2d support. But I guess the devs will know better :)

**Comment by curly-brace** [comment]
Well Nape is not written in c++, but haxe allows to translate into c++ using hxcpp toolchain. But Nape is abandoned.

**Comment by eon-s** [comment]
@curly-brace I don't remember how 2D appeared on the bullet pr but yes, not sure if worth that or just copy features or techniques (like scaling, portals, soft bodies, etc.).

**Comment by rraallvv** [comment]
I just wanted to point out that Apple SpriteKit and Unity both use Box2d under the hood for 2d physics, and also Apple contributed SIMD and Neon optimizations for macOS and iOS to the Bullet source.

So, adding Box2d as an option like @AndreaCatania did with Bullet would make it easier later on to take advantage of whatever gets added to Box2d, like for instance fluid simulation.

**Comment by reduz** [comment]
@rraallvv: For 2D I will keep working on that physics engine, as It's easier to optimize and tweak for usability. If anyone wants to implement Box2D eventually via GDNative, feel welcome, but it's not really going to happen.

**Comment by rraallvv** [comment]
@reduz I see... nevertheless, I updated my fork to see if I can help with something. Keep up the good work.

**Comment by mhilbrunner** [comment]
@Hinsbart This can be closed.

**Comment by Hinsbart** [comment]
Ok, closing this as it won't be added to the core.
But as @reduz mentioned already, feel free to implement it via GDNative.
