### ISSUE TITLE
Stretch ratio spinbox/slider on Control nodes doesn't work as expected.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#10627]
Debian 64 bit, 3.0 alpha 1

In any control node, in the properties under "Size Flags" there is the "Stretch Ratio" option. The spinbox doesn't increment. Entering a number with the keyboard results in the spinbox displaying that number minus 1. The slider also doesn't work as expected. Clicking on it will display a number in the spinbox, but dragging doesn't changed the displayed value. If you use one of these methods to get the value higher than 1, the spinbox will decrement as expected.

Played with and found that the functionality appears to be fine. It's just the UI input.

**Steps to reproduce:** Add any node that inherits from Control and try to use the Stretch Ratio option.

**Comment by akien-mga** [comment]
Is this still reproducible in Godot 3.0 RC1?

**Comment by RodeoMcCabe** [comment]
The increment buttons and also keyboard entry is working as expected in rc1, they appear to be fixed.

However, the slider sill exhibits some funny behavior. It works fine on nodes that are the only child of their parent (I guess because it's not doing anything).

If you have a few sibling nodes in a container such as Vbox or Grid and are trying to use the slider, it does funny stuff. This happens regardless of whether the stretch ratio has any effect on the nodes, i.e. if their size flags all have Expand unchecked. With any size flags the actual functionality of size ratios is working, as is keyboard input and the up/down increment buttons.

Here's an example project. Play with size ratio slider on the Label, LineEdit, and Button nodes to see the strange behavior.

[godot-slider-test.zip](https://github.com/godotengine/godot/files/1633461/godot-slider-test.zip)

**Comment by KoBeWi** [comment]
Compared to 3.0, the slider in 3.1 appears to be working correctly.
