### ISSUE TITLE
Suggestion: Create Sprite dragging to Scene panel

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#10684]
Dragging an image resource from the FileSystem panel onto a node in the Scene panel should create a Sprite node whose texture is the dragged file, where its position is 0, 0 relative to its parent.

My reasoning is thus:
1. This behavior is intuitive, and having more ways to do the same thing accommodates more users.
2. It doesn't override any existing behavior.
3. To my knowledge, the fastest existing way to create a Sprite child node at 0, 0 with the desired texture (which IMO is the most common desire for Sprites) is to use the manual insert child node menu, selecting Sprite, and choosing the texture property manually; or to drag the texture resource to the editor while its desired parent is selected, and then manually changing the position to 0, 0 in the Inspector panel.

**Comment by RandomShaper** [comment]
In 2.1 this works and even allows you to change the type of the created node between certain sensible options.

Was this removed in 3.0?

**Comment by eon-s** [comment]
@RandomShaper what works now is dropping on the visual scene editor, not the scene tree panel.
This is something that can be done already with scene files.

It may need to detect if parent if a spatial to create a Sprite3D instead too.

**Comment by RandomShaper** [comment]
Oh, I misread.

**Comment by razvanc-r** [comment]
@Oranjoose this is a bad idea, a much better solution would be to create a reset/clear position button as suggested in #8917. In fact I think most if not all properties in the inspector should have such a button, not just the resources.

Reason is, if you want to create an environment using modular assets you absolutely don't want for the sprite to be placed at 0, 0. Or at least have toggle button that defines the behavior for future drag operations.

**Comment by Oranjoose** [comment]
@razvanc-r I don't see how this suggestion and your suggestion are mutually exclusive. If you want the sprite to be offset from its parent, you can still just drag it into the viewport as usual. This suggestion doesn't override that. You can have property reset buttons too without conflict.

Do you understand the suggestion?

**Comment by razvanc-r** [comment]
Oh sorry, I missed your point which is about dragging to scene the title.. dooh :)). I was concentrating to much on dragging to viewport...

**Comment by KoBeWi** [comment]
I guess it would conflict with #16464, so we'd probably need another hotkey if both were added.

Also, a button for resetting position is already implemented:
![image](https://user-images.githubusercontent.com/2223172/53701755-5ba56980-3e00-11e9-9158-f10460672e89.png)

**Comment by Oranjoose** [comment]
@KoBeWi The suggestion on this issue is for dragging a texture on a **node** in the **Scene dock**, not the Inspector dock, so the issue that you reference is separate. Currently nothing happens when you drag a texture anywhere on the scene dock. I observe beginners and what they think to do intuitively, and dragging a graphic to the Scene dock is something I think feels natural to some beginners.

**Comment by KoBeWi** [comment]
XD
Sorry, I misread the issue I linked. I thought it's about dropping resources on a node, so it's assigned to corresponding property. It's based on idea I had long ago.

Nevermind anyways.

**Comment by hubbyist** [comment]
By quoting @KoBeWi "dropping resources on a node to assign them to corresponding property" may be a better fit as subject may be. But this may enlarge the scope a little as well.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
