### ISSUE TITLE
Shader TIME in editor

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#10756]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04 - Godot v3.0.alpha.custom_build.3ae1cff

I don't think it's desirable to have the TIME variable behave in editor as I'm game. There's two options either turn off TIME in editor or have a way to reset the time to 0 through a button or something. I think 2nd option would be better for users

**Comment by Zylann** [comment]
Something also annoying is the fact that, if you prototype a shader using TIME, you just can't use "update changes" mode, because the shader will animate only when you do things in the editor, so it's better to use "update always".

**Comment by Calinou** [comment]
Note: The feature described here was implemented in https://github.com/godotengine/godot/pull/31070, but it wasn't merged.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
