### ISSUE TITLE
Change Type of add_custom_type'd node does not change icon

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#10798]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0, Windows x64

**Issue description:**

I used an EditorPlugin to add a custom type. When attempting to use the Change Type option in the context menu when right-clicking on the node in the hierarchy, the icon to the left of the node did not update to reflect the change.

**Steps to reproduce:**
1. add a new type.
2. create a node of that type.
3. use the Change Type option in the node's context menu to switch to a different node type.

The icon will not update itself.

**Comment by reduz** [comment]
This happened because the custom icon goes into the node metadata. I suppose the change type dialog should clear this metadata.

Replace code is here:
https://github.com/godotengine/godot/blob/master/editor/scene_tree_dock.cpp#L1434

And for reference, metadata for custom type is added here:
https://github.com/godotengine/godot/blob/master/editor/create_dialog.cpp#L418

**Comment by willnationsdev** [comment]
I might be able to check this out in some days (got some stuff going on at home atm, but after things settle...). Thanks for the input.
