### ISSUE TITLE
Add Support for Geometry Shaders

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10817]
they are part of specification from OpenGL 3.2, so would be fine to add them to godot?

they will allow to make some geometry complexity modifications (because tessellation shaders aren't available for us, because they are OpenGL 4 feature), they will allow creating good grass on the fly, trees, fur. controlling LODs from the shader itself. and some people even create performant voxel engines using them.

and last but not least, it will allow to recalculate normals on the mesh that was changed by vertex shader.

**Comment by reduz** [comment]
this should not be too difficult to do, but leaving it for after 3.0..

**Comment by akien-mga** [comment]
Geometry Shaders seem to only be in OpenGL ES 3.2 though, IINM.
https://en.wikipedia.org/wiki/OpenGL_ES#OpenGL_ES_3.2
https://www.khronos.org/registry/OpenGL/extensions/OES/OES_geometry_shader.txt

**Comment by curly-brace** [comment]
@akien-mga oops. i haven't looked at ES specs 😞

**Comment by BastiaanOlij** [comment]
Something probably to make optional as even when it is supported, on older hardware it can be slow. I don't know what mechanism we're thinking off later on to switch back to say OpenGL ES 2 for older devices but maybe that can be applied here too?

I've had some great fun with geometry shaders and would love to play around with those in Godot :)

**Comment by curly-brace** [comment]
well, talking about supporting different features for different platforms, i think adding gl4 support would be very cool because it will add tessellation shaders and compute shaders which may allow creating very nice graphics.

this is somehow done in mainstream engines? they support themselves high-end features, but allow to export to low-end platforms. i don't know how it is done, but may be they just throw away parts that aren't supported on target platform? and it is up to game developer to manage this, so that graphics aren't to bad without tessellation for example.

**Comment by koopa** [comment]
This discussion was the first thing I found when I searched for Godot geometry shader support. Seeing as it's still open I hope you don't mind me just going ahead and asking some of those question right here.
Firstly, related to this discussion: I am looking whether or not we can use own geometry shader programs in godot 3+. Is there any updates/progress on that? 

And more generally, where would I go to find out about the status of specific features like this one and what other people are working on or interested in without actually browsing their branches? 
Is there maybe even some sort of feature voting system where people can vote for the features they most want to see or is it all handled in this github issue system? Apologies if those last few questions don't belong here but thanks for any information.

**Comment by reduz** [comment]
Not supported, but should not be difficult to add eventually in 3.0. Just
not a priority unless somebody wants to work on it

**Comment by Zylann** [comment]
Could we add tessellation shaders though? They seem to be more efficient and used in games rather than geometry shaders

**Comment by frankiezafe** [comment]
@reduz : hello, as i need geometry shaders for the code i'm working on for the moment, could you point classes to be adapted? it would save several of hours of guessing :) - thanks in advance!

**Comment by frankiezafe** [comment]
@reduz : hello, as i need geometry shaders for the code i'm working on for the moment, could you point classes to be adapted? it would save several of hours of guessing :)
The main issue should be:
- loading the shader from the harddrive,
- binding it correctly (https://learnopengl.com/Advanced-OpenGL/Geometry-Shader),
- ensure the communication with vert & frag parts,
- and making the whole stuff optional (auto detection if possible).
Am i right?

**Comment by AndreaCatania** [comment]
What's about this feature proposal? I'm moving it to 3.2

**Comment by ConnorBP** [comment]
I'm guessing nobody decided to add this?

**Comment by bfishman** [comment]
definitely interesting, along with compute shader support

**Comment by Chaosus** [comment]
I guess, now it is pointless to add until Vulkan will be supported

**Comment by ConnorBP** [comment]
> I guess, now it is pointless to add until Vulkan will be supported

Is Vulkan even arriving any time soon?

**Comment by Chaosus** [comment]
> Is Vulkan even arriving any time soon?

No, it planned to 4.0 which planned to the end of the year (maybe + another year). The GLES3 renderer which currently may support geometry shaders, however, may be stayed until it properly implemented - afterward, it will be removed. Maybe it's not so pointless and not so linked to the renderer, at least for shader language.

**Comment by ConnorBP** [comment]
Yeah I think it is definitely worth it if anyone decides to take on the task. It is a very important feature for modern engines and if someone already knows how the Vulkan system works then they could write it keeping in mind how they would need to change it for Vulkan later so that there would essentially already be support waiting for the new render-er-er when it eventually comes way down the road. Both render systems were made by the same group so even though Vulkan is fundamentaly different it shouldn't be an impossible task to abstract a few things so they can be "easily" *ish* plopped into Vulkan later.

**Comment by ConnorBP** [comment]
For now custom modules would be the way to go i suppose. Not as nice as built in engine support however in terms of prototyping, iteration, accessibility etc.

**Comment by TheRealNOIG** [comment]
I noticed a comment from Reduz in merge request [#28237](https://github.com/godotengine/godot/pull/28237)
"For Godot 4.0, the plan is to create compute shaders that do a similar functions, but merging this for 3.x branch does not make much sense if it's going to be removed in 4.0 months later."
Would this make this feature request obsolete due to the lead engineer closing the merge request for 3.X and saying they will not support geometry shades in 4.0? Or is there still potentail of geometry shades being support in later version of Godot.

**Comment by akien-mga** [comment]
Indeed, thanks for the reminder. This feature proposal should be closed as #28237.

Geometry shaders were added in OpenGL 3.2, but since we're going to remove the OpenGL 3.3 renderer to replace it by Vulkan (and the more flexible compute shaders), it doesn't make sense to implement geometry shaders support indeed.

If anyone really needs it in 3.2, the PR #28237 can likely be cherry-picked in your local branch and further improved to be usable in production.

**Comment by sboronczyk** [comment]
https://github.com/sboronczyk/godot-opengl-4

OpenGL 4.6 branch, geometry and tesselation supported
