### ISSUE TITLE
Some visual issues with new theme changes

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#10828]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot master

**Issue description:**

some unwanted effects were introduced along with the new white theme

before
![screenshot from 2017-08-31 12-26-46](https://user-images.githubusercontent.com/1103897/29936664-a2930e6a-8e48-11e7-924d-072cf3cc8ad1.png)
![screenshot from 2017-08-31 12-26-57](https://user-images.githubusercontent.com/1103897/29936667-a4e625d0-8e48-11e7-92f4-6ba2f64dcbc4.png)

after
![screenshot from 2017-08-31 12-32-51](https://user-images.githubusercontent.com/1103897/29936680-abde96ec-8e48-11e7-9641-4e3c088fcf06.png)
![screenshot from 2017-08-31 12-35-00](https://user-images.githubusercontent.com/1103897/29936720-d76a7272-8e48-11e7-992f-eb925995bc69.png)

1.  of all most of the elements are bigger now, this is unwanted, it actually even though this does not look that bad, it reduces the number of element in lists (at least should be configurable).

2. buttons are brighter

3. Inputs do not have borders even though my settings are set to have 1px border.

@toger5 this is the problem with including sneaky changes, next time it would be better to include such changes on different PRs

im not sure if there are other changes like that, but please @toger5 try to not include sneaky changes, i spend quite some work making sure that metric are correct and colors are not very odd, and including this changes would make me repeat my changes (which is not fun).

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by volzhs** [comment]
about the number 1, it's because of changing the default font.
see this one. https://github.com/godotengine/godot/pull/10690#issuecomment-325294077

**Comment by djrm** [comment]
@volzhs that what i was suspecting

**Comment by toger5** [comment]
@djrm yea I definitely did touch the buttons. I needed too since all colors are generated based on dark/light theme.
I think I also changed disabled buttons since they were almost the same than normal buttons. (I'm not sure though)
I will check the button border color
For the lineEdit border color it seems I didn't do the color conversion properly. it should be light not dark...

**Comment by toger5** [comment]
@djrm I think the issue for the line edit is, that I removed set_border_width_all...

For the buttons: what exactly is the problem. Is the border too bright? (I think the font color is the same the font is just bigger.)

**Comment by djrm** [comment]
@toger5 yeah just the button border, it used to be more subtle, also the disabled color is like the speakers button on the first image, and on the second image it does seem like it is active.

**Comment by toger5** [comment]
@djrm I don't try to introduce 'sneaky' changes. I did some changes to the theme overall. but I mentioned them in the commit log. (or/and the pr)
And since I changed a couple of variables (mostly since naming didn't made sense with the light theme. variables called light were often dark...) I might also have changed colors by accident. that happened to the buttons I think...
I really like the current look (before the white theme) so I will help clean up whatever I broke!

**Comment by djrm** [comment]
@toger5 thats nice to hear, sorry for the misunderstanding.

**Comment by djrm** [comment]
@toger5 the alignment of the icon is my fault, i hardcoded the metrics, so im going to fix it to match any metric

**Comment by tofuhead** [comment]
also, using grey-theme, this is what animation view looks like:
![godot-anim-grey](https://user-images.githubusercontent.com/8156935/30055045-d7801428-9236-11e7-8a82-d12ca358ee37.png)

it's a bit hard to see the text :)

**Comment by toger5** [comment]
@tofuhead.
Also good to know!
Grey theme in general has some issues since the highlight color is pretty darmto andhas little contrast to the base color. Maybe we change it to white? (the highlight color? @djrm)

**Comment by toger5** [comment]
Im refering to just the setting in the preset switch statement (@djrm)

**Comment by tofuhead** [comment]
well, I'm using my custom theme, which is basicly the grey one, but darker grey... and for highlight I chose sort of orange because.. well, matches my blender :)  
![godot-anim-grey1](https://user-images.githubusercontent.com/8156935/30100107-57d84d98-92f0-11e7-81fd-ef119187dc41.png)
![godot-anim-grey3](https://user-images.githubusercontent.com/8156935/30100108-57dd2d90-92f0-11e7-8dff-56b6265d6d33.png)

although, theme manager seems to mess the orange a bit when highlighting something in browsers. orange becomes sort of brown...  I wonder why is that.. 

![godot-anim-grey4](https://user-images.githubusercontent.com/8156935/30100135-781a7bbc-92f0-11e7-862d-6f0438690e77.png)

.b

**Comment by toger5** [comment]
@tofuhead there are multiple versions of the highlight color. for different situations.
when using it as a background it gets changed to something a little bit darker so the contrast between the white font and the highlight (in  your case orange) is guaranteed.
the issue which definitely has to be fixed is that the animation editor apparently uses the highlight color. it should use the font color since that color will always have contrast to the background. (even on light themes)
@tofuhead why is the text `MwahInstance.rotation_deg` orange in one screenshot and grey in the other. (what do you do to change the color?)

**Comment by toger5** [comment]
This is what it looks like in with #11020 merged:
<img width="1222" alt="screen shot 2017-09-07 at 17 53 45" src="https://user-images.githubusercontent.com/16718859/30172575-898c7de0-93f5-11e7-8786-360440f467ea.png">
readable.

**Comment by tofuhead** [comment]
@toger5  I think the orange color comes when the object that has animations is selected is scene browser..

**Comment by toger5** [comment]
@tofuhead yea I also figured that. I changed it to be white in the pr linked.

**Comment by tofuhead** [comment]
@toger5 compiled and tried it now.. yes, readable now... but for some reason most of the text now is pure white, in all browsers... was that intentional?  how about giving user possibility to choose text color.. you know, normal/disabled/highlighted colors?

**Comment by toger5** [comment]
@tofuhead what do you mean with browsers?
But it is intentional that most text is just white. Only the script editor and help should have color. (and some buttons in clicked state)
Where do you miss the color where it was before.

The idea of making color as a setting is interesting. There are already a lot of settings though. And since other colors don't make that much sense the setting would mostly be unchanged...
Also changing to a white theme would require you to also change the font color setting. 

Changing basic theme should be easy and not require you to change multiple settings to make it usable.

**Comment by tofuhead** [comment]
@toger5 oh, sorry.. by browsers I mean the inspector  / scene / import / node / filesystem things...  they used to be sort of grey, not bright white, which can be a bit much on the eyes...  I understand the logic here, that only couple of settings to make it simpler.. but for font color you now have auto/dark/light.  what if instead of that you just had color picker, like you have for Highlight color (that affects fonts too) 

the Project Manager view looks quite nice now, with the base text being grey, and then you have bright for project names and selected tab..

**Comment by toger5** [comment]
The grey color was part of all the trees. the grey was not intentional actually..
I think the contrast for the font will stay.

**Comment by toger5** [comment]
Also the option auto light dark makes most sense since with auto you don't need to change anything else when swtiching theme. there is also more behind it than just a color. there is a icon color conversion map which is only for the dark version... nothing in-between.
