### ISSUE TITLE
Create a tool for adding documentation

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#10827]
It would be amazing to have a tool to document godot.
I'm imaging an xml parser which than gives me a list of all classes and documentable item.
I can than just type in whatever is approprite to describe something. It changes the xml and saves it.
I can commit and done.
So no user errors when editing the xml and no fighting with the size of the file.

## web app
it could be a web app with the advantage, that it is accessible to everyone.
Te server could handle:
 1. Compiling godot for the docs tool (every second day)
 2. than updating the class reference.
 3. opening pr's for the newly added documentation (also every second day)

everyone could go to the website an edit the docs with all the new (introduced two days ago) functions and params.

## an app created with godot.
 1. that also would be cool and easier to do.
 2. it would be a project made with godot just to edit the xml file
 3. all updating + committing + creating pr would still be handled by the user...

## It could be build into the editor!
the editor could have the option to edit the docs right inside of it. (only works when connected to internet) than a http request would be made and a server would handle the rest (creating pr...)
If no internet connection is provided the editor could have the option to create a classes.xml so users can create the pr themselves.

**Comment by Noshyaar** [comment]
Built-in docs editor can be a nice addition.

BTW, just throwing this idea out there, can Weblate be used for this stuff? It's like translating program code into English and other languages.

**Comment by vnen** [comment]
> It could be build into the editor!
> the editor could have the option to edit the docs right inside of it. (only works when connected to internet) than a http request would be made and a server would handle the rest (creating pr...)

A hundred times please NO! That would be caos. We have a lot of PRs already to manage, imagine a lot coming from small changes in the docs... I'm all for facilitating the process of documentation, but don't make this be more of a burden for us than a helpful tool for users.

----

A web tool (similar to Weblate) would be interesting, especially if we can manage the results there and only update the repository when we want. Though that be quite an effort to make, I imagine.

**Comment by vnen** [comment]
P.S. I think I've seen an issue about this in the past, but couldn't find with a quick search.

**Comment by reduz** [comment]
An hybrid solution could be good, with a link in empty functions that takes
you to a webpage where you fill a form to submit this..

On Aug 31, 2017 3:12 PM, "George Marques" <notifications@github.com> wrote:

It could be build into the editor!
the editor could have the option to edit the docs right inside of it. (only
works when connected to internet) than a http request would be made and a
server would handle the rest (creating pr...)

A hundred times please NO! That would be caos. We have a lot of PRs already
to manage, imagine a lot coming from small changes in the docs... I'm all
for facilitating the process of documentation, but don't make this be more
of a burden for us than a helpful tool for users.
------------------------------

A web tool (similar to Weblate) would be interesting, especially if we can
manage the results there and only update the repository when we want.
Though that be quite an effort to make, I imagine.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/10827#issuecomment-326378456>,
or mute the thread

**Comment by Oranjoose** [comment]
I have a lot of professional experience with technical writing/instructional material development and am working on thorough documentation. I am not yet ready to share what I have, but I am hoping it would help supply Godot with adequate traction for newcomers that it might contribute toward catapulting Godot into more mainstream exposure.

**Comment by toger5** [comment]
@Oranjoose that sounds great.
What do you mean with working on documentation. Working on tools to increase the documentation speed. Or are you actually writing documentation?
Either way would be great!!!

**Comment by Oranjoose** [comment]
@toger5 Both if all goes well.

**Comment by NathanLovato** [comment]
@Oranjoose we meet every week-end with most of the active docs contributors on Discord, #documentation channel: <https://discord.gg/8FE9RmX>
Help and discussion is always welcome!

**Comment by Calinou** [comment]
I don't think there's still a need for this, as contributing to the class reference is now a [well-documented process](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html).

**Comment by akien-mga** [comment]
Agreed.
