### ISSUE TITLE
Add camera dolly to Godot editor's 3d viewport

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#1084]
Somehow I always manage to hit this issue, it happened to me using blender and maya, and now with Godot editor too, it's when the viewport's camera gets too close to its pivot. A workaround for this is to use the camera dolly zoom, which moves the camera in a direction perpendicular to the screen but uses a parameter independent of the camera's position with respect to its pivot. For that, the camera's focal length would be ideal, because it's independent of the aspect ratio, so the distance that the camera dolly is displaced would be the focal length multiplied by a constant factor, that constant factor could be configurable too.

![untitled-1](https://cloud.githubusercontent.com/assets/1840524/5592653/d342e6ca-91ac-11e4-95f0-523b9aed1f6b.jpg)

**Comment by akien-mga** [comment]
Why not make a pull request of your changes?

**Comment by akien-mga** [comment]
Ping.

**Comment by akien-mga** [comment]
Closing as the issue is stale and did not generate a lot of traction. I think it would be an interesting feature to have, but hidden in the depths of the issue tracker doesn't help gather interest.

Feel free to comment if you would be interested in this feature too, it could be reopened and eventually worked on by a contributor.
