### ISSUE TITLE
GDScript: Make 'export' keyword serialize the field

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#10851]
currently `export var x = 5` will just save the field along with scene file and show that variable in the editor.

there is `to_json()` function that can serialize any object, but feeding it a node with script just returns a class of the node, not even a name. (`"[Sprite:917]"`) which is useless.

so it would be very convenient if `export` will make a field serializable by `to_json()`.
for example i have a node somewhere on the scene with a script having export variables like:
```
extends Node

export var name = 'it's me, mario'
export var health = 99
```
and i want to save the current state, i just call `to_json(get_node('mario'))` and it will return those two variables as json, that i can add to the save file

**Comment by razvanc-r** [comment]
This does't make much sense, `to_json` is a `Dictionary` function. I think the current way of doing things is as good as it gets, you want some stats to be saved? Just make a dictionary and call `to_json` on it. Don't think it makes sense for this function to operate on nodes directly and why only `export` variables? Why not all variables? What should happen with the variables that are initialized in `_ready`? What if you don't want to store all export variables?

The dictionary method is good because it forces you to think about these questions, it's explicit.

**Comment by curly-brace** [comment]
it was a dictionary function in 2.1, but in 3.0 it is a global scope function that accepts Variant type as a parameter.

the thing is that there could be lots of variables that aren't important for a state save, and vars initilized in _ready and being declared in global scope with 'export' will be serialized fine.

**Comment by Zylann** [comment]
It might be my use case only, but I would not directly serialize a node directly for a savegame, because variables with `export` and those that need saving aren't necessarily the same. `export` currently means more than that. Also, you could end up serializing things from the base classes without control over it.

**Comment by Brickcaster** [comment]
I would like a simple method of building the dictionary for to_json.

At the moment I'm creating a savedata array that contains the name of persistent vars so that I can do this:
```dict = {}
for data in savedata:
  dict[data] = get(data)
save_to_disk(dict.to_json())```

I can manually create savedata, or update it via a simple regex find/replace script I run externally.  I would merely like a way to skip this step if possible.

**Comment by akien-mga** [comment]
As outlined by @razvanc-r and @Zylann, I think this is outside the scope of `export` which may or may not define a variable that you want to serialize at all. And you might want to serialize non-export variables. So using `export` for that seems like a bad workaround.

@Zylann gave a lot of details on how to properly do save games, so closing.
