### ISSUE TITLE
Debug option "Visible Navigation" doesn't work in tilemaps

### ISSUE THREAD

**Issue by lorenzobeccaro** [godotengine/godot#10898]
Windows 10, official stable download (2.1.4)

If "visible navigation" is on but navpolys are in a tilemap they aren't visualized at runtime.

**Comment by beniwtv** [comment]
I noticed the same problem for 3.0 alpha compiled this Sunday (Oct 1st. 2017)

**Comment by Listwon** [comment]
@lorenzobeccaro @beniwtv Could you please attach the minimal example projects?

**Comment by beniwtv** [comment]
[tilemap-navpolys.zip](https://github.com/godotengine/godot/files/1352178/tilemap-navpolys.zip)

Here you go (3.0 alpha project, compiled today).
I've included two scenes: One with the tileset (not displaying navigation when running), and one where it works without being a tileset.

Note: I had to create the tileset with Godot 2.1.4 stable, as 3.0 would freeze when adding a NavigationPolygonInstance as a child of a sprite.

**Comment by Listwon** [comment]
@beniwtv Thanks! You're right, I tried that and it freezed ;) But if you add Navigation2D as a child of a sprite and then a NavigationPolygonInstance as its child, it works. Still doesn't show debug navigation.

**Comment by Listwon** [comment]
@beniwtv Ah, I see, it omits NavigationPolygon added as a Navigation2D child when exporting to TileSet.

**Comment by beniwtv** [comment]
Yes, as far as I could see, NavigationPolygon has to be a child of the sprite for it to show up in the final tileset.

**Comment by beniwtv** [comment]
So I've been trying to wrap my head around this issue, and was unable to find where the TileMap draws the polygons when debugging is enabled.

So I am no longer sure if this is a bug, or a missing feature (considering it doesn't work both in 2.1.4 and 3.0 compiled today).

**Comment by beniwtv** [comment]
So I have been working on implementing this, and it already seems to be working well for "square"-type tilemaps. However, I'd like to get feedback from the developers because I have found cases where it doesn't seem to get the correct transform for placing the polygon.

My work is here at the moment:
https://github.com/godotengine/godot/compare/master...beniwtv:tilemap-navigation-debug

Specifically, it seems to be off then switching to a isometric tilemap. I think the problem resides in this line: https://github.com/beniwtv/godot/blob/aa2760532b750a263ade17c22485f272a06bc250/scene/2d/tile_map.cpp#L546

I haven't found out why this happens yet, since the code looks to me like it is already compensating for navigation offsets and tile center.
