### ISSUE TITLE
Add donors to the editor About box

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#10922]
As promised in the perks of the [Patreon campaign](https://www.patreon.com/godotengine), donors of $10+/month should be added to the About box, with:
- Platinum sponsors first (currently there are none, but the logic for them should be implemented)
- Gold sponsors then
- All donors at $14+ then
- All donors at $10+ afterwards

I've added a `DONORS.md` file in 2753044d06bec370b6379fde5f69a39af4a468ad that should be parsable like we do for `AUTHORS.md` to populate the About box. There should likely be a separate "Donors" tab for it.

CC @Noshyaar who did a great job on the AUTHORS.md stuff already.

**Comment by akien-mga** [comment]
Note that the "Gold donors" are in separate chunks based on their Patreon tier (higher comes first), but they don't have to be listed as separate groups in the about box, you can just list them all in that order.

**Comment by neikeq** [comment]
Would `DONORS.md` contain only the active donors at the time of a release? The problem I would see with that is that there could be donors that stopped donating before that point, and it would be unfair to not list them.

IMO we should go with one of the following:
- A static list at the time of release that lists all donors that donated at least once since the last version.
- A dynamic list that is fetched by the editor of the current active donors. Does Patreon have an API for this?

**Comment by eon-s** [comment]
I think a static list won't represent the real donors because they are dynamic by Patreon's nature, and instead using Patreon servers could use something like the asset lib and update the list not in real time but from a set period (every X weeks/months), including other types of donors too.
