### ISSUE TITLE
Tooltip problem on PopupMenu

### ISSUE THREAD

**Issue by Paluth** [godotengine/godot#10930]
Hello,

I'm on Windows 10 64bits, using godot 2.1.4
[MenuButton.zip](https://github.com/godotengine/godot/files/1273068/MenuButton.zip)

I add a menu button to an empty scene. I have the following code:

```
extends MenuButton

func _ready():
	var pop = get_popup()
	pop.add_item("Option 1", 0)
	pop.set_item_tooltip(0, "Tooltip 1")
	pop.add_item("Option 2", 10)
	pop.set_item_tooltip(10, "Tooltip 2")
```

But the tooltip for item with id 10 (Option 2) doesn't show. However if I give ID 1, it shows. I seams to be expecting a sequential id starting from zero instead of an arbitrary id. 

But if there is an option to pass an ID, then it should work with the id provided.

**Comment by Paulb23** [comment]
related to #2861 #3188

The way popup menu works and from the discussion in the other issues, the ID is for working with enums  ect. Instead the index collected with `get_item_index(int p_ID)` should be used.

As this point I'd guess its more of a documentation update to change the argument binds to say `index` instead of `idx` and possiby add some extra text explaining its uses to make it clearer.

**Comment by EricEzaM** [comment]
Needs tag: `documentation`. The behaviour is intended, just not very clear.
