### ISSUE TITLE
Macros in GDScript

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#10948]
The question of course debatable, but what about macros?

```
# Without macros
extends Node

onready var node = $'Label'

func _ready():
	node.text = "Value \"%s\" from macros" % 12
```

```
# With macros
macros
extends Node

@ovar = onready var
@BAD_TEXT (val):
	return ("Value \"%s\" from macros" % val)

ovar node = $'Label'

func _ready():
	node.text = BAD_TEXT(12)
```

This option is very primitive and not very comfortable, but it is one of variants of my vision macros.
It is clear that language and so is very convenient, but to solve routine parts of the code sometimes is very convenient.
So it seems to me that the parser can handle macros even while writing the script itself (as a function or vars ).
Sometimes there are things that cannot be replaced by functions or other designs.

P.S.: Sorry if you strongly disagree with my thoughts. This is just a suggestion.

**Comment by Zylann** [comment]
I don't see any advantage for this usage of macros, it makes the code more confusing. Using functions is the actual language and does the same thing. I'm curious which bottleneck you find that can't be solved without macros?

**Comment by vnen** [comment]
Considering that there's not really a shared context between scripts, where would macros be defined?

I don't like the idea because there's no clear benefit in that. In the example, you change a keyword, which makes the code harder to read (since it's scoped to your project). The other one could be solved with a function.

> Sometimes there are things that cannot be replaced by functions or other designs.

Do you have some real-world examples of that?

**Comment by Andev08** [comment]
> Considering that there's not really a shared context between scripts, where would macros be defined?
In a place similar to where the key bind inputs are?

> Do you have some real-world examples of that?
Anything that uses an ID system seriously benefits from macros. For instance in networking, packet header referencing. "Packet_WorldData" is much easier than "125", especially when you have 124 other IDs in the mix too.

Another example is states, maybe for example a.i. state. Resting, Disturbed, Hunting, Sleeping, Listening, Waiting, Sneaking, etc etc. You could always use a string instead of a macro, but in other languages, strings are slower to work with than reals. 

The last example that immediately comes to mind, is when you will be using a value a lot across the entire game, that you intend to change in the future. For instance if you're making a block/chunk based game, you might store the block size in a macro. That way, if you do end up changing the size, all the collision math, the offsets, the gui, and god knows what else reliant on the blocks being thay size, get updated correctly in one value change.

**Comment by Zylann** [comment]
You can define IDs using `const`, they do what you just described.

**Comment by Andev08** [comment]
To be honest I didn't know there was a difference between macros and constants. Are they global across the project?

**Comment by Zylann** [comment]
No script is global per se, but it's possible to either `preload` it (just like an `import` in Python, I defined my groups this way in my game), or make it a singleton with auto-load. Both techniques let you access constants anywhere.

**Comment by Andev08** [comment]
I guess that's one way of dealing with it. What's the overhead on that like though? Especially if you've got hundreds or maybe even thousands of constants?

**Comment by Zylann** [comment]
The overhead of constants is near zero. I think they are converted to the actual values when parsed, to some extent (like, it's impossible to do that if you use `load` instead of `preload` because `load` is dynamic, so not parse-time optimizable). You can profile it to be sure.

**Comment by Andev08** [comment]
> I think they are converted to the actual values when parsed

Well if they are, then macros are technically already implemented?

Preload = Macro
Load = Const

I think the fastest way to confirm that would be to look at the source

**Comment by hpvb** [comment]
The GDScript parser will make everything that is constant simple a thing of that type in the parse tree. At runtime there's literally no difference between '2+3' and the constant '5' for instance. There are cases where this is not the always the case, function results need to be marked so that they can be converted into constants for instance, but for the most part I think GDScript already does what you're asking for.

**Comment by Zylann** [comment]
This, though: https://github.com/godotengine/godot/issues/7047

**Comment by Boothand** [comment]
A convenient way to use macros could be with yield functions. You can't make a convenience function for something like `yield(get_tree().create_timer(time_to_wait), "timeout")`. Wrapping it in a func and calling the function won't yield the function it's called from, but wrapping it in a macro and calling that would solve it.

e.g `define wait(time_to_wait): yield(get_tree().create_timer(time_to_wait), "timeout")`

**Comment by Boothand** [comment]
Would there be any difference between `await some_function()` and `yield(some_function(), "completed"`, other than verbosity?
I'm not too familiar with await. But you could nest these yields at least.

**Comment by Zylann** [comment]
@Boothand the main problem I have with `yield` is, it was designed to wait for a signal. As such, you cannot nest it without creating more signals (you cannot wait for a yielding function).
`await` would designed for waiting for the actual completion of a function that may not return immediately, and also the ability to return a value. An analogy would be the C# `await`.

**Comment by Boothand** [comment]
@Zylann Do you mean if a function yields execution (without a signal) before it has reached the end, and that 'await' would wait for any such yield?
With the example I mentioned, which waits for a function to finish (`yield(some_function(), "completed")`), "completed" is not a signal manually made by the user. It's automatically emitted from the object returned by the yield, when the function completes, so you can nest these without making new signals.

**Comment by Boothand** [comment]
@Zylann For what it's worth, you can do:

`
func _ready():
	var return_value = yield(wait(2), "completed")
	print(return_value)

func wait(seconds):
	yield(get_tree().create_timer(seconds), "timeout")
	return 42
`

This printed 42 (after 2 seconds).
The await looks better though, and there may be other await features I haven't thought of.

**Comment by vnen** [comment]
Co-routines in GDScript is a problem on its own (since it works kind of backwards compared to other languages). And asynchronous processing is related, but not really the same thing. I do think it could be beneficial in some cases and simplify the code a lot. But that's another discussion.

In any case, macros won't help you with this.

**Comment by OvermindDL1** [comment]
Playing devils advocate, a Staged Macro system (not what was proposed above) would be useful for code generation, say by loading in entity data via json and generating optimized code for each into a tightly packed array as one example.  You can already do it via tools, just significantly more irritating and difficult to do, but it is already possible.

**Comment by Zylann** [comment]
@Boothand hang on, according to docs, I thought `yield` returned a GDFunctionState? How are you getting the return value? If your snippet works maybe the doc needs to be clarified.

**Comment by vnen** [comment]
@Zylann Yeah, the signature in the doc isn't particularly helpful, it's even misleading (IMO it shouldn't even be there, it's not a function, it's more of a special keyword). `yield` does not return a state, instead the *function* return a state. Which then the caller can use to call `resume(value)` and that will be what `yield` returns as the function is resumed

**Comment by char0xff** [comment]
Imagine doing an RPG and everytime you have to show a messagebox you would do:
`yield(messagebox("Hello, world!"), "messagebox_end")`
With macros you could do
`message("Hello, world!")`
Or, if the macro implementation is super good:
`message "Hello, world!"`
https://github.com/godotengine/godot/issues/10948#issuecomment-398348347

**Comment by OvermindDL1** [comment]
> Or, if the macro implementation is super good:

Ew, why get rid of parenthesis...  o.O

**Comment by char0xff** [comment]
> Ew, why get rid of parenthesis... o.O
Faster to type. Thinking, again, for an RPG game. But with parenthesis it would be good enough.

**Comment by vnen** [comment]
@char0xff if I were doing and RPG I wouldn't have all my messages mixed with code, and the abstraction would make this construct happen only once or a few times at most, so a macro wouldn't be justified.

I'm still against macros because: 1) it's another complication for GDScript, which is supposed to be simple, 2) it can easily lead to sloppy code (same with globals), and 3) Almost all of the time they can be replaced by a simple language construct, and the other cases are so rare that it's not worth it.

**Comment by wingedadventurer** [comment]
What about macros where you record your action and can replay it, using some shortcuts (ex. `Ctrl + 1`)?

For example, in Notepad++ you can start recording, type `Console.WriteLine("")`, move your cursor inside string quotes, and end your recording.
Then you can play that recording anytime and it will type the code above and put your cursor inside the string.

I would find this very useful in Godot (or in any text editor actually). I find myself typing this code a lot:

```
for child in get_children():
	if child.is_in_group(""):
		// ...
```

It would be nice to make a macro for this, and end my cursor position inside string for naming the group children belong to. Then I can press `Ctrl + 1` anytime and save me time finding it and copy-pasting, and placing the cursor where I want.

**Comment by WarrenMarshall** [comment]
This got lost in all the side discussions about yielding and whatever else, but anyone who has done any amount of programming in other languages can attest to the usefulness of macros (which support arguments).  There are a lot of advantages.

**Comment by Timofffee** [comment]
Yes, I'm sorry. Now it seems extremely stupid to me. GDScript 2.0 looks just gorgeous
