### ISSUE TITLE
Inspector selection behavior consistency

### ISSUE THREAD

**Issue by aegarpyke** [godotengine/godot#1096]
Right now, if I click on a value in the Inspector, it first highlights that value but doesn't enter into edit mode for that value: http://puu.sh/e005z/19407efbe3.png

I have to click it again in order to start editing it: http://puu.sh/e007D/2d3e328b52.png

For other field types, such as dropdown selections and multi-field selections, it immediately starts editing with one click: http://puu.sh/e00cb/897c2d2830.png

To make it consistent, I think ONE click should immediately start editing no matter what.

####

Along the same lines, once you've finished editing a value and you click somewhere else, the value doesn't deselect: http://puu.sh/e00lz/262abd34b2.png

I think it would feel better if finishing with editing a value would deselect the value that was being edited.

**Comment by akien-mga** [comment]
The first part of this issue is no longer true in the current master branch, clicking on any value instantly brings up an editbox.

For the second part, it's still valid but it could be that it's a feature? So that if you edit a given value in a node of a certain type, the same value is already selected in the other nodes of the same type, so that you can easily change them too.
