### ISSUE TITLE
Issues with the new white theme

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#10969]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3873362b3df0c1c03746225f8e43b629bd0864cc

**Issue description:**

There are some issues and some concerns about the new white theme. ping @toger5 

first the issues (should be easy to solve):
1. The icons generation time is increased, as i suspected, the color replacement takes some time, so according to my measurements, the icon generation time for the white theme is 0.37 s whereas for the dark theme is 0.26 s, i know it is not much of a increase but this time is added to the editor and project manager boot time, (it should be less with release mode), (also there is room for optimization in color replacement).

2. visual issues: the ones i found so far
![screenshot from 2017-09-04 13-05-07](https://user-images.githubusercontent.com/1103897/30035756-04132ee0-9173-11e7-85fa-965a6e193be9.png)
![screenshot from 2017-09-04 13-05-35](https://user-images.githubusercontent.com/1103897/30035762-07c4c7c4-9173-11e7-97df-0a56fa9ada3a.png)
![screenshot from 2017-09-04 13-05-55](https://user-images.githubusercontent.com/1103897/30035764-09968d58-9173-11e7-836f-167d7a27505f.png)

3. this is not related with white theme, but it is a change introduced by it
contrast_colorx for variable naming is not very good, the thing is that there are just to variant for contrast
dark and light, thats way more explicit than, since usually you dont choose full black or **full white** as base color

4. white as a base color might no be a good idea.
white should not be used as base theme,  because you are loosing the light contrast variation, instead a more greyish color should be used (people can still set that as a base color, but with poor results).

concerns (should be a little harder to solve):
My main concern about supporting the white theme, is that now we have to focus in making sure that everything we do works on light and dark themes (this is hard), there are several hardcoded colors, and several style rules, also element that were designed for a dark theme do not match exaclty when presented on dark themes (and vice-versa), increased effort in new visual features, now we have to test on both variations (something that apparently has not been done so far). @toger5 i know you use the light theme, and when you do changes you focus mostly on the white theme, and i do stuff for the dark theme (which is the official flavor). so @toger5 we have to figure out a way to avoid throwing dirt on each other (meaning when you fix something for light, it breaks something for dark and vice-versa). also first and foremost we have to focus our efforts in the official flavor (which is dark).

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by toger5** [comment]
### about 1: 
Since both 0.26 or 0.36 Is a lot. I was considering adding a texture atlas buffering the textures anyways. this atlas could be recreated each time the user changes the theme. or on first startup.
that would. Because on MacBook (2015) hardware this takes even longer:
```
SVG_GENERATION TIME: 0.828561 (light theme)
SVG_GENERATION TIME: 0.697271 (dark theme)
SVG_GENERATION TIME: 0.82234 (light theme)
SVG_GENERATION TIME: 0.681623 (dark theme)
```
so about ~18% percent increase for the light theme/ for the color conversion.
but almost a second in general so the atlas would be a good idea anyways.

### about 2
the first screenshot is referring to the lack of contrast for the font? this is fixed in the other pr I made for fixing white theme issues.
the second screenshot might use hardcoded colors. (will need to investigate. can't tell why the font is white now)
the last screenshot should be solved similarly to  #10901 I guess. (I don't know if it uses an RTL though...)

### about 3
contrast color makes a lot of sense (as a variable name) since it is a color which Is contrasting to the base color. is the default color dark than the contrast color is a bright version of the base color.
is the base color light than the contrast color is a dark version of it. -> so that there is contrast!
Before it was called light color. which also was a contrast to the dark theme (which was to only option before...)
than there are dark_color_1 - 3 which are actually darker versions of the base_color. for both light and dark theme.

### about 4
here the Answer is basically the same then for 3. there is no light version of the color anymore. as you are pointing out than it would make no sense to choose #ffffff as a base_color. 
since we need other versions of the base color there is contrast color now.

### about concerns
The only thing when I touched the appearance was chaining the button border to a little brighter value for the light theme which you didn't like. (and I agreed, it was nice with the previous colors)
But that was it. (I also removed the border for line edit which was a 'user error' though and not for the favour of the white theme. happened because I made a lot of theme changes and was focused on other things.)

I wouldn't say that I do theme changes for the white theme though (except implementing it...).
most recent pr's I did were for the editor in general. I wouldn't say no-one is only doing one theme (light/dark).
It tried and will continue trying to create the light theme in a way, that it is completely independent and adapts automatically.
Of course for theme changes we need to have both in mind but that is basically as easy as only using predefined colors and don't hard code any colors. The rest should than work automatically! (even now that should already work pretty well)

And that there are still errors with the white theme in gerenal is also more than expected. I think I even mentioned that in the pr. It would be a huge amount of work to go through every ui and clean up everything. Not because that would take that long BUT because that would result in me having to rebase A LOT. which was time consuming with the light theme change. (Thank you! @akien-mga for merging already!)

So issues like this one are great (and expected) so that I can tackle them!

> so @toger5 we have to figure out a way to avoid throwing dirt on each other (meaning when you fix something for light, it breaks something for dark and vice-versa). 

I am already working on that. (adding contrast color was one of those adaptions) And I think we are pretty close. Especially since we almost have no hardcoded colors anymore. so using all the colors listed at the top of the editor_themes.cpp file should work great in light and dark theme.

> something that apparently has not been done so far

of course this statement could refer to multiple things.
It could refer to the border feature where you didn't like the bright border, or It could refer to the white theme where I changed the button. In one case I checked and posted the dark version.
In the other case it was more or less a mistake.
what makes you think that we haven't tested both version?
Maybe you mean something else than feel free to correct me and I will apologise!

**Comment by djrm** [comment]
@toger5 
about 1: yeah we definitely need a way to cache the generated rasters

about 2: those are actual issues, but not much of a problem (they should be easy to fix, just pointing out so you now they exist).

about 3: we really need to get to an agreement about the colors usage, currently it a mess (for example what does contrast means, in white it mean black, even though i already have dark color? does not make much sense) also keep in mind that those colors are used outside the editor_themes, so it would be nice to have something self explanatory, but yeah we need to work on this stuff (also we must create color variables to replace all the hardcoded colors in the editor but thats another topic).

about my concerns, dont take it the wrong way, i just pointing out that two themes = two times the effort, but yeah we will handle that in the best way possible in order to avoid to increased work

**Comment by toger5** [comment]
What about creating a 'style guide' which collects information about creating UI for the godot editor and how the theme is structured.
This could be really useful for plugin developers too!

I think the colors make okay sense right now. I think I would like to work on the stylesheet so I could spend some time looking at the current color options we have. (and maybe proof me wrong ;) )

**Comment by toger5** [comment]
<img width="586" alt="screen shot 2017-09-05 at 00 53 14" src="https://user-images.githubusercontent.com/16718859/30039738-75e0a5b8-91d5-11e7-8f19-c7eef58cdafa.png">
2 seems to be partially fixed.

**Comment by toger5** [comment]
I need to work on the output though

**Comment by toger5** [comment]
@djrm output also is fixed. #10985

**Comment by toger5** [comment]
I think we can close this one and open another issue just for the icons generation time.
There we can discuss If we want the atlas or improve the color conversion performance.

**Comment by Calinou** [comment]
Some additional note from testing: I think the blue tone which is used to highlight selected controls should be a tad brighter, to make it less "obnoxious" compared to non-selected controls (but it still should be noticeable enough).

**Comment by toger5** [comment]
@calinou do you mean highlighting in the node tree? Or highlighting of the different control options (scale rotate...)

**Comment by toger5** [comment]
@djrm 
I did some optimisation for the color conversion since the current version was really poor. especially creating the replacement array for each icon.
current results are much better

SVG_GENERATION TIME: 0.687413 (light)
SVG_GENERATION TIME: 0.67162 (dark)
SVG_GENERATION TIME: 0.671937 (light)
SVG_GENERATION TIME: 0.66236 (dark)
SVG_GENERATION TIME: 0.698043 (light)
SVG_GENERATION TIME: 0.691484 (dark)

I just was so happy to finally have figured out how nanosvg handles color that I was willing to do performance stuff. just made it as readable as possible to make it easier to get the colors working.

now it also makes sense form an optimisation point of view.

**Comment by toger5** [comment]
@djrm 
I finally found time for the needed optimisation for the color conversion.
I just made the code as easy to understand as possible to figure out how nsvg handles color.

so those are the new values I get for conversion:

```
SVG_GENERATION TIME: 0.680435  (with conversion)
SVG_GENERATION TIME: 0.690145  (without conversion)
SVG_GENERATION TIME: 0.677619  (with conversion)
SVG_GENERATION TIME: 0.719461  (without conversion)
SVG_GENERATION TIME: 0.694041  (with conversion)
SVG_GENERATION TIME: 0.669586  (without conversion)
SVG_GENERATION TIME: 0.685164  (with conversion)
```

**Comment by djrm** [comment]
@toger5 wonderful, i knew there was some room for optimization, i was going to try it out, but currently im woking to improve editor_themes.

**Comment by toger5** [comment]
@nice that is great. Inprove in terms of : clenaing up and making it easier to understand.

**Comment by djrm** [comment]
it seems everything has been fixed
