### ISSUE TITLE
Reroute for graph node editors connections.

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#11001]
Very useful feature for graph node based tools:

![2017-09-05 17_55_41-2dsidescrollercharacter_](https://user-images.githubusercontent.com/6152134/30070662-78a6d6de-9264-11e7-8ada-43dc6a499cb0.png)

**Comment by reduz** [comment]
if anyone wants to work on this, feel free :D

**Comment by Jummit** [comment]
Concept I made:
![img](https://user-images.githubusercontent.com/28286961/56393199-f1bc1480-6233-11e9-87ca-7e46058f695a.png)

**Comment by Jummit** [comment]
[Implemented in the VisualScript custom node library](https://github.com/swarnimarun/visual-scripting-node-library/pull/8). It's pretty handy, I use it all the time!

**Comment by fire** [comment]
Discussion in https://github.com/godotengine/godot/pull/28443.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
