### ISSUE TITLE
ButtonGroup can only align buttons in separated rows, can it be possible to position buttons without limitation?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#11010]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
godot 2.*

**Issue description:**

ButtonGroup is very useful, but it seems all children in it will align in separated rows, they can not placed in one row, or any other positions. it's a limitation.
Could it be add a option to disable this limitation?
Thanks.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by volzhs** [comment]
it's limited with 2.x
but it's not with 3.0 now, ButtonGroup is a resource for 3.0.

**Comment by akien-mga** [comment]
As mentioned by @volzhs, it should be fixed in the master branch as the ButtonGroup node was removed and replaced by a more flexible resource.

At this stage I don't expect a lot of development to happen to implement this only on 2.1 in a backward-compatible way, so closing as fixing in 3.0. A PR implementing it for 2.1 could still be reviewed though.
