### ISSUE TITLE
RichTextLabel has opaque background 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#11014]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
6efd777faeb11b42c41d8eccf29274defb20acd9

**Issue description:**
This is quite recent behavior. RichTextLabel have a background and I haven't found way to disable it:
![richtextlabelscreen](https://user-images.githubusercontent.com/6129594/30114496-46f3912c-9318-11e7-92f3-03af83f0429d.png)

**Steps to reproduce:**
Add RichTextLabel to the scene

**Comment by akien-mga** [comment]
CC @toger5

**Comment by toger5** [comment]
I implemented a style box for it. I gave it the default panel style box. 
you can give it a style box empty here:
<img width="252" alt="screen shot 2017-09-06 at 16 09 40" src="https://user-images.githubusercontent.com/16718859/30116436-d67097dc-931d-11e7-9af4-a4851cad673e.png">

I thought it would make sense that there is a default style box since a stylbox seems to be useful in most cases. (a rich text label would be used for some kind of info box so a border panel seems to be appropriate)
Of course this is confusing for everyone used to the old behaviour. So maybe we just make the default a style box empty (it's one line of code change...)
If that is requested ill immediately do the pr for that.

**Comment by toger5** [comment]
another option would be to additional add a flag. `draw style box`. or `draw background`?

**Comment by kubecz3k** [comment]
@toger5 well in my opinion in real game development (not tool/editor development) it's not helpful. Im usually putting richtextlabel as a part of some graphic/texture. I rather rarely use custom styles in real games.

**Comment by kubecz3k** [comment]
But if you think it should be like that, then I would go with additional flag approach :)

**Comment by akien-mga** [comment]
It should default to an empty stylebox IMO.

**Comment by toger5** [comment]
I have a little prejudices against additional flags. I proposed it since it is available for menuButtons. And I recently spend multiple hours to find out that the style box is not drawn since the set_flat flat is set to true... so it can be frustrating. My preferred solution would be to only have style boxes and ppl would get used to first check the style settings when trying to change remove the background...
that rtf has a stylebox definilty makes sense since it allows more simplicity in some situations and does not really hurt.
so maybe the default to empty is better...

**Comment by toger5** [comment]
should be fixed with #11015

**Comment by akien-mga** [comment]
Fixed by #11015.
