### ISSUE TITLE
Cannot build Godot on Windows

### ISSUE THREAD

**Issue by fredlim** [godotengine/godot#1104]
After sync to github, it failed to build on Windows.

scons: *** [drivers\drivers0.windows.tools.lib] The system cannot find the file specified.
scons: building terminated because of errors.

**Comment by UsernameIsAReservedWord** [comment]
same here, using MSVC 2010 express.

**Comment by UsernameIsAReservedWord** [comment]
If I look into the godot/drivers dir, this file exists. 

    03/01/2015  15:53           139 250 drivers.windows.tools.64.lib
    03/01/2015  15:54         9 084 514 drivers0.windows.tools.64.lib

Seems scons forgot to insert the 32 or 64 field into the file name it is looking for.

**Comment by TheoXD** [comment]
Just a note, this is the commit that broke the build: dfa34a6

**Comment by reduz** [comment]
i moved this somewhere else and should not exec on msvc, does it work now?

**Comment by UsernameIsAReservedWord** [comment]
@reduz : I've just tried.

If I want scons to actually generates an .EXE file, I have to run scons 3 times.

    scons p=windows bits=64 -j 4

At the first try, I get a fatal error C1083, because **copy.glsl.h** is not found :
	
    C:\...godot-master\drivers/gles2/rasterizer_gles2.h(55) :
	fatal error C1083: Cannot open include file :
	'drivers/gles2/shaders/copy.glsl.h' : No such file or directory

If I run scons again with the same parameters, I get an other fatal error C1083 because **doc_data_compressed.h** is not found :

	tools\editor\editor_help.cpp(33) : fatal error C1083:
	Cannot open include file : 'doc_data_compressed.h' : No such file or directory
	
Then, if I run scons a third time, then I get the .EXE file compiled.

Got the same behavior with 1.0stable source code.

**Comment by reduz** [comment]
this is something weird from scons and i'm not sure if it can be fixed that
easily
it only happens when you use -j >1 on a clean build

**Comment by reduz** [comment]
it's probably my fault though as those generated files are not treated as
dependencies somehow

**Comment by UsernameIsAReservedWord** [comment]
@reduz : I've just noticed that scons warned me about pywin32 extension at the begining of the compilation. Maybe this explains this strange behavior ?

    scons: warning: you do not seem to have the pywin32 extensions installed;
        parallel (-j) builds may not work reliably with open Python files.

**Comment by UsernameIsAReservedWord** [comment]
@reduz : 
I confirm that this compiling behavior I mentionned occurs because of a missing pywin32 extension.
It was not mentionned into the requirements of the compiling_windows wiki (https://github.com/okamstudio/godot/wiki/compiling_windows)

For a python2.7 32bits install, one has to install pywin32-219.win32-py2.7.exe (even if the OS is 64 bits)
For a python2.7 64bits install, one has to install pywin32-219.win-amd64-py2.7.exe.

pywin32 is available here : http://sourceforge.net/projects/pywin32/files/

**Comment by SolarLune** [comment]
I was getting this problem earlier yesterday, I believe. However, after the recent commits, it seems to be resolved.

**Comment by Murii** [comment]
Total out of topic but @SolarLune  if that is really you than please leave Blender Engine and come here!

**Comment by akien-mga** [comment]
This has likely been fixed long ago.
