### ISSUE TITLE
New script temperature makes the names almost unreadable

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11059]
**Ubuntu 17.04, Godot Build: 5666857**

**Issue description:**
The new look of the script temperature feature makes the script names almost unreadable.

![screenshot at 2017-09-07 17-30-38](https://user-images.githubusercontent.com/30739239/30187235-2783a6d2-93ff-11e7-9047-e6c873642aec.png)

**Comment by homer666** [comment]
The issue is that your theme colours haven't been updated to the new defaults. In your Editor Settings, under Open Scripts, you want to change the three colour values to these:

```
Script Temperature Hot Color: ed5d5d
Script Temperature Cold Color: 4cffffff
Current Script Background Color: 7fffffff
```

Just click on each colour and paste those hex codes into the text field at the bottom-right of the boxes. Once you're done it should look something like this:
![image](https://user-images.githubusercontent.com/27100585/30187745-47b1fa5c-946e-11e7-8660-21b85288f6e1.png)

**Comment by YeldhamDev** [comment]
Thanks, closing it then.

**Comment by toger5** [comment]
@YeldhamDev currently in this early stage it makes sense to delete the settings file in .godot from time to time anyways since there are a lot of changes to the settings anyways...
