### ISSUE TITLE
Animation lines/keys are off centered

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11093]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 latest, W7 64-bit, RX 480

**Issue description:**
![](https://i.gyazo.com/2a934a4be471547ea8e111aac3eca9dc.png)

Not sure if already reported, but  yeah :)

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
