### ISSUE TITLE
Ability to run editor at monitor refresh rate

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11092]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0 latest

**Issue description:**
When dragging stuff around in the editor, there is a noticeable delay/lag
![](https://i.gyazo.com/b7ffa3dc79dc6b2ad9079b5397605b92.gif)

I know a lot of people don't have 144hz monitors so it might be hard to tell however I think it'd be amazing to have an option in the editor settings to run the editor outside of the fixed interval (60fps)

Would make moving objects in the scene much smoother for us 60hz monitor and higher users!

**Comment by Zylann** [comment]
Similar to https://github.com/godotengine/godot/issues/11030 ?

**Comment by Calinou** [comment]
> Similar to #11030 ?
> (note that 60Hz+ is barely noticeable to the human eye)

This issue isn't entirely the same – #11030 is about reducing the stuttering caused by the redraw checker (it performs checks every so often to see if there is a need to redraw the viewport). This issue is about changing the viewport FPS limit (ideally automatically, based on the monitor refresh rate – it can be acquired using `xrandr` on Linux, and there surely is an API on Windows for this).

**Comment by Dillybob92** [comment]
@Zylann I cannot go back to 60hz monitors now it looks like 20fps :P the difference is night and day imo, but yeah

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
