### ISSUE TITLE
primitive mesh + collision shape orientations

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#11150]
**Issue description:**

when adding a collision shape (or primitive mesh) some of them are in awkward orientations.
planes are not parallel to the ground. so when adding a plane as a floor (which I think is most usual case) it needs to be rotated (x: -90). (also bender adds planes parallel to the ground)
capsule shapes and capsule mesh are mostly used as character placeholders. but they are added sideways. (as if the character was laying on the ground) which is also inconvenient because It needs to be rotated.

**Steps to reproduce:**
add a collision shape and/or a mesh instance. try all the different collision shape resources and primitive mesh recources. some will be rotate different than what would be practical.

**Comment by n-pigeon** [comment]
Duplicate of #9242?

**Comment by n-pigeon** [comment]
I would also prefer Capsule to "stand" :D

**Comment by toger5** [comment]
sorry did see you one...

**Comment by novemberist** [comment]
I totally agree about the capsule, however, I can't reproduce what you say about the plane. It gets positioned just fine from what I can see....

**Comment by toger5** [comment]
If the plane is fine i mean the quad mesh.
Havent tested during writing the issue. Just had in mind that there was an issue with me needing to rotate a plane (or apperebtly a wuad mesh)
Ty for correction

**Comment by BastiaanOlij** [comment]
The quad mesh is mostly there for backwards compatibility but also because it can be used internally for billboarding, in which case it defaulting to as a vertical plane instead of a horizontal plane makes much more sense.

The plane mesh object does default to a horizontal plane as its most common use case is as a floor plane. Especially in combination with higher tesselation settings and a vertex shader that applies a height map :)
