### ISSUE TITLE
Exposing more editor-features and -plugins to EditorPlugin

### ISSUE THREAD

**Issue by kerskuchen** [godotengine/godot#11173]
Hey! After trying and somewhat failing to achieve some editor-customizations with the EditorPlugin and tools scripts (mainly with [tilemaps ](https://godotengine.org/qa/17659/tool-mode-possible-notified-tilemap-cell-was-changed-editor)) I dabbled a little with Unity and had a look at its very nice editor extensibility. You can look at the official [API](https://docs.unity3d.com/ScriptReference/SceneManagement.EditorSceneManager.html) and some presentations of [cool](https://www.youtube.com/watch?v=sNVT7hynBYw) and [useful](https://youtu.be/s1o0gZwJS-4) extensions some gamedevs wrote on youtube to get an idea of its possibilities.

I want to ask if it is possible to expose more of the API of the editor to achieve similar things in Godot. Some examples of what would be cool to access from GDScript:
- Inspector for custom formatting and input of node properties (i.e. float-ranges, arrays of strings as 
  comma separated string, drop-downs for Enums and custom types, etc.)
- Main viewport for easier drawing of gizmos and debugstuff from a plugin and manipulation of position
  and orientation of the camera. I know you can get the viewport from the EditorPlugin but drawing did 
  not really work for me due to me having coordinate system issues. Drawing from a tool node on the 
  other hand worked without a flaw. 
- TileMapEditor plugin for receiving events of cell filling for doing things like autotiling or doing custom 
  patterns
- ScriptEditor for custom refactoring, code generation and annotation tools
- AnimationPlayerEditor plugin for various visualizations and annotations
- Opening, closing, saving and editing of scenes in background or loading multiple scenes in and out of 
  the current scene
- Selection and deselection of nodes that also notifies corresponding plugins (like closing/opening 
  the TileMapEditor when a TileMap node is deselected/selected **from code**)
etc.

I think this would be a huge benefit for the community, as the most important thing for productive gamedev is to have really good tools that are tailored to the game you are making or an easy way to build those on top of almost perfect tools.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
