### ISSUE TITLE
Node "Change Type" from TextureFrame to Button - Button ignores mouse

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#11194]
Godot 2.1.4 stable
Kubuntu

Steps:
1.
![image](https://user-images.githubusercontent.com/4741886/30336814-956694b2-97e6-11e7-80a8-4dd1414d7b4b.png)
2. Right click "change type" to Button
3. Run project see that button is not clickable

TextureFrame
![image](https://user-images.githubusercontent.com/4741886/30336907-f2da4d46-97e6-11e7-9846-8db26b0e1404.png)

After "Change Type" the ignore mouse setting from TextureFrame is still there(Default in TextureFrame)

**Comment by hpvb** [comment]
Hmm... Is this a bug? If you 'change type' what should happen? You don't want any of the changed properties to change otherwise the function would be the equivalent of 'replace node' not 'change type'

I suppose what could be done is to change all node settings that aren't the default for the source node type to the defaults of the target node type. 

Does that make sense to anyone? :)

**Comment by Noshyaar** [comment]
I'm not sure about how to fix this because it is a "feature". There are some properties you might want to keep when changing type, but changing to a button kinda implies that it should be clickable IMO.

Maybe have an option to not keep settings inside the change type dialog?

**Comment by AlexHolly** [comment]
Godot Master

Maybe related

1. Create "AcceptDialog".
2. "Change Type" to "ConfirmationDialog".

Result:

![image](https://user-images.githubusercontent.com/4741886/35465909-c93de482-02ff-11e8-951a-26957922ae96.png)

Expected:

![image](https://user-images.githubusercontent.com/4741886/35465927-e2c6849a-02ff-11e8-9be0-ffa22a82e091.png)
