### ISSUE TITLE
Default camera inertia in freelook mode is too much

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#11216]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
5cb90ad67ed16115b53da4fb0865be612afed2ac

**Issue description:**

The camera keeps moving for a lot of time, even when gently moving or pressing move keys (like in freelook mode)

**Steps to reproduce:**
Move around in Freelook mode

**Link to minimal example project:**

**Comment by toger5** [comment]
yea I agree that freeload mode is much too fast atm. and inertia too heigh.
But maybe you also still have older settings. I changed the behaviour recently and this change expects different numbers (0 - 0.5 Is about reasonable) before it used integers I think...
so maybe you have an old settings file?

Freeload also takes the zoom lvl into account. I find that confusing sometimes, since that can make the movement really fast...
@Zylann is that the zoom dependant speed commonly used. I mean it makes sense but I feel it has a too big influence.

**Comment by Zylann** [comment]
@toger5 it is proportional to the speed used for panning, but maybe the factor to calculate is too high? In fact it's a user setting https://github.com/godotengine/godot/blob/master/editor/plugins/spatial_editor_plugin.cpp#L1716

**Comment by toger5** [comment]
@Zylann and @djrm did one of you guys test the current defaults. I have recently and I think they are okay. except the movement speed for freeload is too much for my taste. it can be really low I think since there is the option to just use a high speed multiplayer.

Lets use that pr to discuss defaults and than one of us can make a pr with the discussed values. 

I will try really soon on a higher performance machine so I have smooth fps and give you my values

**Comment by toger5** [comment]
I had the best experience with:
```
orbit inertia 0.1
zoom inertia 0.1
Freelook inertia 0.2
Freelook base speed 0.1
Freelook Modifier speed 3
```

but the zooming doiring freeload still is weired. it has a HUGE impact on speed and only little impact on fov... so it is really import to know that the mouse wheel affects the speed...
But it still has effect on the zoom when not moving.
I think we should disable zooming in Freeload. and just adapt the speed with the mouse wheel.
and there should be a little explatnation in the top right corner how to use freeload 
```
mouse wheel: speed
wasd: movement
qe: up down
mouse: look around
```

**Comment by Zylann** [comment]
Note that zoom doesn't impact fov, it just makes camera closer to focus point. Also, again "HUGE" impact on speed is how experience feel, because you can also say zoom has a "HUGE" impact on panning currently^^

I left the speed modifier for people who are used to have it rather than mouse wheel, I personally only use the wheel and never press that modifier.

So you want to decorrelate freelook speed and orbit zoom? At the time I was unsure if that should be done because I eventually got used to the current system, so I just mentionned it as a comment a while ago  https://github.com/godotengine/godot/issues/10516#issuecomment-323880273

I'm not a fan of controls shown in corner of screen, it's useful for one or two days then it becomes wasted space once you know it on longer term. It should also reflect the actual control map.

**Comment by toger5** [comment]
@Zylann good points. I just recently used a mouse for the first time. with a trackpad you can't zoom during freelook.

So the concept was kind of new to me thats why I asked.
But you are right it is much better than the modifier! 
But it was still confusing to me that it changed the focus point. It was kind of hard to control for me.

So I would prefer that you just use `w` and `s` for zooming and only use mouse wheel for speed...

Is there any advantage in having the mouse wheel to "zoom out"/ change the `distance` in freelook?

**Comment by rminderhoud** [comment]
I think the default free look speed is fine but the inertia should be much lower. The change was pretty jarring and I personally set it to 0. However, setting it to _almost_ 0 would be a good indication to the user that the feature exists.

**Comment by Zylann** [comment]
@toger5 I explained the intent in the comment I linked above, it's taking the size of the reference frame into account (this is why I compare it to panning, which does the same). In practice, I had this idea from the fact that when moving around, then switching back to orbit, it required re-adjustment of zoom level because orbitting could jump too far away or be left in near-fps mode in midair. Conversely, when using freelook very close to a scene or far away, it would start moving too fast or too slow, because it has no info to adjust, except zoom... so I interpreted cursor distance as a basis for translation speed in general.

**Comment by toger5** [comment]
actually makes a lot of sense. it's just cumbersome for ppl with trackpad. but it is cumbersome with a trackpad anyways so we should not optimise for it...

I played around with it a little longer and your design makes more and more sense. it's actlually pretty good!!

So no changes to the behaviour. except.. it is zooming in the wrong direction.

**Comment by Zylann** [comment]
I think freelook should accelerate if you bring your finger forward as you move the wheel.

**Comment by toger5** [comment]
@Zylann jea that is a pretty good point.
I still would prefer if the zoom is correct. If you scroll in orbit mode and than go back to freelook you will also be faster when zooming out.
Its probably just something i have to get used to.
Would you at all consider changing it?
If you got used to it and say that it is really comfortable to use we can keep it.

**Comment by Zylann** [comment]
When I implemented it I didn't touch the way orbit worked, but as a result wheel directions are different in both modes (I referred to Blender's fly mode for this).
I think it's fine as it is, but that's my subjective advice^^

**Comment by toger5** [comment]
Oh even blender is doing it this way. (I'm not using the fly mode. didn't even know it exists (damn it)).
I think going with the same setup than blender does is always a good idea since a lot of ppl are going to use it together.

**Comment by n-pigeon** [comment]
I think problem is that non-freelook camera zoom level is tied to speed of freelook camera.
It's the same as in Blender but I think this design is broken :)

I think we should make freelook camera speed consistent and predictable, not tied to normal view camera zoom level.

**Comment by toger5** [comment]
@n-pigeon now would you than handle da/acceleration?

**Comment by n-pigeon** [comment]
@toger5 
FOV - both View and Freelook cameras should have it tied so when you move from one mode to other perspective looks the same.
Position - both cameras should overwrite it so where each stops, stays there.
Focus point - it should be lost when entering Freelook (F-key should be used to reassign it again).
Freelook speed - those are constant in world units, so no other setting in any camera has impact on it. Speed can be tweaked (scroll wheel or keys) current speed value should be visible somewhere for user as reference.

**Comment by toger5** [comment]
That is the idea behind the zoom speed correlation. On the left there is the zoom bar which mutates to a speed indicater in freelook.

**Comment by Zylann** [comment]
I don't understand how Fov came here^^"

**Comment by reduz** [comment]
I already adjusted this, and added separate settings for manipulation and
view switching. Please give it a try.

On Sep 18, 2017 9:41 AM, "Marc" <notifications@github.com> wrote:

I don't understand how Fov came here^^"

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/11216#issuecomment-330207204>,
or mute the thread

**Comment by djrm** [comment]
@reduz, in orbit mode the controls are great, but freelook, still really bad (at least with default settings)

**Comment by toger5** [comment]
@djrm would you mind trying #11222 I think @reduz is not planning replace his commit. So I would adapt it to only do the things which are not in reduz change (mainly the touchpad behaviour.)
but if you prefer those default values. I will also update them.

**Comment by djrm** [comment]
i think this is fine now
