### ISSUE TITLE
Initial project creation could be streamlined

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11215]
**Issue description:**
When you create a new project in Godot, there's a lot of time wasted messing around with the directory. The folder explorer always starts the somewhere obscure (on mine, buried a good few folders deep within the actual godot.app bundle). This also applies to any dialog prompt that requires a file to be located. 

**Example**
I really like the way Game Maker Studio deals with projects. It has a _pre-filled_ directory, pointing to documents>gamemaker>[projectname]. And that default directory can later be customized in settings.

It also creates all the assets folders for you, for your sprites, sounds, scripts, etc. But I understand people will have their own conventions, and this might be annoying. But on the flipside, standard conventions are never a bad thing to introduce. It could perhaps be an option.

**Also**
Macs have this neat feature, where you can drag a directory or a file into the load window, and it will automatically go to that path. You can't seem to do that on the Godot loading windows.

**Comment by vnen** [comment]
> The folder explorer always starts the somewhere obscure (on mine, buried a good few folders deep within the actual godot.app bundle)

Pretty sure this was fixed by #10766.

> It also creates all the assets folders for you, for your sprites, sounds, scripts, etc.

[Godot documentation](http://docs.godotengine.org/en/stable/learning/workflow/project_setup/project_organization.html) explicitly orient you to avoid using asset formats as folders. Instead, you should organize things semantically in your game. So it would be characters, levels, etc., which might vary too much between games, decreasing the gain of a default structure.

**Comment by mhilbrunner** [comment]
Closed by https://github.com/godotengine/godot/pull/10766.
