### ISSUE TITLE
Allow for multiple axis transformations

### ISSUE THREAD

**Issue by Andev08** [godotengine/godot#11236]
**Issue description:**
In blender, you can hold shift to select multiple transformation options, to create combinations like this for instance:
![image](https://user-images.githubusercontent.com/31744099/30380497-b51e9af6-9891-11e7-988a-4775b6383735.png)

Adding this would allow for the mouse pointer button to be removed (which is essentially just translate and rotate together). Speaking of which, it confused me at first, because I remembered seeing translate and rotate together, but once I'd switched to scale, I couldn't figure out how to get them both back.

**Comment by fracteed** [comment]
You can already get rotation and translation on the same widget by using the first select mode (hotkey q).

**Comment by Andev08** [comment]
> You can already get rotation and translation on the same widget by using the first select mode (hotkey q).

I know, I touched on that in my original post. But you can't get other combinations. I was also suggesting that the first select mode could be replaced by holding shift for both modes. It would make the GUI a bit tidier, and pushes a more intuitive and functional control scheme (but that's a subjective issue).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
