### ISSUE TITLE
AcceptDialog and its children appear corrupted

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11250]
**Ubuntu 17.04, Godot Build: f0754b2**

**Issue description:**
The AcceptDialog node and the nodes that inherit from it are appearing corrupted:

![screenshot at 2017-09-13 19-24-42](https://user-images.githubusercontent.com/30739239/30403694-44c09b2e-98b9-11e7-96dd-967bab82b2ec.png)

**Comment by bojidar-bg** [comment]
CC @toger5, @djrm

**Comment by toger5** [comment]
seems the texture for the sb could not be found...

**Comment by toger5** [comment]
any idea when this got introduced?
it should be this image
`popup_window_png`
which exists in `theme_data.h`
and is properly assigned in `default_theme.cpp`
I will try if I can reproduce and maybe figure out whats wrong with breakpoints...

**Comment by volzhs** [comment]
maybe it's regression from https://github.com/godotengine/godot/commit/1e8048dd45149b8d574cf983e12ff5886d109da0#diff-0f2d5f8b708eeeac121058c71f5c1428R198

**Comment by toger5** [comment]
good job volzhs.
the issue is exactly that. the sb can't be found when searching for it..
there is actually an issue with the get_stylebox function which could be fixed. when there is a custom style, it loops through parents until it finds the correct sb. when there is no coustom style though, it just takes the default theme... (without looping)
but stepping through the code I also had situations where it was just looping to Object type... which is bad. so it didn't realise that there is a style box for WindowDialog. although there is none For AcceptDialog...

I'm trying to find a solution to make it find the parent sb if there is none. but otherwise we just add the type back got the get_stylebox function in the Dialog draw notification.

**Comment by djrm** [comment]
@toger5 damn.

**Comment by toger5** [comment]
@djrm I think it is a good thing that you removed it. since it should work like this...

And I think I have a solution so that it works like that... Haven't tested yet though...
