### ISSUE TITLE
Can't add items to dictionary variable in Visual Scripting

### ISSUE THREAD

**Issue by tungkradle** [godotengine/godot#11284]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 64 bits
Godot 3.0 Alpha 1
(and also tested in Godot 3.0 latest daily build)

**Issue description:**
When using visual script, I can't add items to a dictionary variable

**Steps to reproduce:**
Create a new variable in member panel, right click to edit it. After changing to _dictionary_ variable type, the value field becomes uneditable, there's also no icon to expand or make it editable in inspector panel like other types.

**Screenshot:**
![image](https://user-images.githubusercontent.com/24779254/30462468-19b6aa3a-99f0-11e7-93d4-49a67d42aeba.png)

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
This should be fixed now, given PropertyEditor is gone and Inspector does allow it, so closing.
