### ISSUE TITLE
Animator improvements (AnimationEditor/AnimationPlayer)

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#11359]
- The animator should let copy and paste a keyframe (all tracks in a moment) between animations.
- Godot should restart all animator's nodes properties to their original value before change the animation in editor.

**Comment by rminderhoud** [comment]
Some more:

- adding a key should be more consistent (sometimes pressing the green + does nothing)
- individual tracks should have enable/disable functionality
- closing/deleting an animation does not clear the animation window

**Comment by jedStevens** [comment]
I would love to help in making the anim UI much better, I'm not sure if this is possible but it would be cool to use something like blender curves etc.

Also it would be cool if the clock on the animation editor worked like time instead of a decimal number, much more intuitive, even if we opt to keep an option to show a float instead. "1.32 vs 1:32" I know these aren't the same time I just didn't want to figure it out.

Any thoughts?

**Comment by dploeger** [comment]
I'd like to add one other point:
* the keyframe editor should be resizable. It's wayyyyy to narrow.

**Comment by Calinou** [comment]
The first point is already being tracked in https://github.com/godotengine/godot-proposals/issues/302. Other points are likely also being tracked in other issues and proposals.

I'll close this issue as we prefer to have one proposal per point that should be improved.
