### ISSUE TITLE
YSort node invert function and customizeable axis

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#1135]
Hey, there. So, I think the YSort node could be reworked a bit.

1) Invert function. The ability to invert the effect (for placing objects further up on the Y axis on top of others) would be really useful for platforming views.

2) Customizeable variable. I think it might be nice to rework "Y-Sort" into just a "Sort" node, allowing you to sort the collection of children node based on whatever you need (for example, sorting by a custom variable, or even a custom function).

**Comment by not-surt** [comment]
Ideally sort by projection onto an arbitrary axis.

**Comment by bojidar-bg** [comment]
That sounds like a nice idea...

**Comment by akien-mga** [comment]
Old issue, but what do you think of this proposal @reduz? If it has your blessing, we could mark it as `pr welcome`, otherwise better close it if not meant to happen for technical reasons.

**Comment by menip** [comment]
This seems like would be fun. Could imagine playing with something like a circle sort, where nodes closer to center are on top of those further away.

**Comment by hidemat** [comment]
This would be a nice feature.

**Comment by aaronfranke** [comment]
Perhaps we can utilize similar logic to [Array's sorting methods](https://docs.godotengine.org/en/latest/classes/class_array.html#class-array-method-sort-custom)? `sort_custom` uses a custom method which is provided two elements for comparison. Users could define their own sorting method, or if none is present, it would default to the current behavior. This would be extremely flexible while not overcomplicating `YSort` (which could be renamed `Sort` if this change is added).

**Comment by bojidar-bg** [comment]
The problem with using a custom method (especially one which is not a native function) is that the sorting happens in the RenderingServer right before rendering. This is likely on a separate thread, and needs to be performant.

**Comment by Calinou** [comment]
Maybe we should just implement an Invert property for now?

**Comment by SolarLune** [comment]
You could also make it so that there's a toggle that sorts depending on the distance to a custom Node2D. That way, the user could make the axis whatever they wanted it to be by simply moving the Node2D to the extent of whichever axis you want, if I am envisioning it correctly. For example, put the Node at Y=-1000000, and objects would be basically sorted by Y position. Put it at 100000, and objects would be effectively sorted inversely. Put it on a moving object, and everything sorts according to the distance to that object, which might be useful for certain perspectives. If one needs more control, you can just manually modify the z_index variable of Node2Ds.

If this won't work, then yes, an inversion toggle would be OK.

**Comment by SolarLune** [comment]
Never mind, that option wouldn't work because objects would sort differently because of the distance to the object on the perpendicular axis (i.e. if the node was at 0, 0, then objects would sort from right-to-left). An alternative would be to just have a Vector2 exposed by code and by the editor to sort by. Have it default to 0, -1, and that should be it.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
