### ISSUE TITLE
"Keep Debugger Open" conflicts with "Always Open|Close Output On Play|Stop"

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#11371]
**Issue description:**

This two settings:
![2017-09-17-165430_700x63_scrot](https://user-images.githubusercontent.com/1387165/30524380-e5537a5e-9bc8-11e7-8f61-9f285c11aa4c.png)
conflict with this:
![2017-09-17-165324_243x185_scrot](https://user-images.githubusercontent.com/1387165/30524376-d181f898-9bc8-11e7-888a-49966f560d29.png)

- ~The option "Always Open Output On Play" not really works because when some print occurs the output always open.~ Fixed by #15869 
- When I am in debugger, for example in tab "Monitors", and I stop the game I always go to first tab, can we change this behavior to not do it?

I think we need to simplify this options some way.

**Comment by Calinou** [comment]
This is still relevant as of https://github.com/godotengine/godot/commit/79947dfef1db52462ce25f370696e3eb926fa627, although I don't know exactly how the options relate to each other now.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
