### ISSUE TITLE
Add more useful 3D viewport rendering modes

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#11392]
Now that Godot includes [a wireframe mode for the 3D viewport](https://user-images.githubusercontent.com/180032/30556362-e57c2336-9caa-11e7-859c-008b9f82f994.png), more viewport rendering modes could be added for the convenience of developers and artists alike.

## Outline mode

![Outline mode example](https://user-images.githubusercontent.com/180032/30556407-0d331c04-9cab-11e7-85a5-7e0443160779.png)

This mode displays materials as usual, but displays a wireframe *on top* of them. The color should be settable by the user, but probably should default to a white or light gray color.

**Example use case:** Displaying geometry complexity while still being able to freelook through a level easily.

## Lighting mode

![Lighting mode example](https://user-images.githubusercontent.com/180032/30556373-ebd30042-9caa-11e7-8ccd-9a3890bb1549.png)

This mode sets the normal map strength of all materials to 0, sets the albedo texture and color to pure white (`#ffffff`), disables specularity, sets roughness to 1 and metallic to 0.

**Example use case:** Analyzing lighting conditions in a level, regardless of the applied materials.

___

*Footnote: the screenshots come from [Cube 2: Sauerbraten](http://sauerbraten.org/), I am not working on an implementation of these modes in Godot.*

**Comment by blurymind** [comment]
Do we have wireframe mode?

**Comment by Calinou** [comment]
> Do we have wireframe mode?
> Just wires, no materials, no faces

Yes, Godot already supports this (in 2.1 and 3.0, I think).

**Comment by SpoopyUI69** [comment]
Another one, Viewport movement locking when using a Quad setup.

**Comment by fracteed** [comment]
The main issue with wireframe mode at the moment is that it is always fully shaded. If there are no lights or gi generated in the scene you will see no wires, unless objects have a luminant texture. As can be seen in the first image with full lighting, all wires are visible and this actually looks really cool (haven't seen this style of wireframe mode in a 3d app before). The problem is this same scene, before any lighting is added looks like the second image. It would be totally black if there were no luminant meshes.

![wire1](https://user-images.githubusercontent.com/7741669/30680707-7d856940-9ee4-11e7-9d47-686a58715825.jpg)

![wire2](https://user-images.githubusercontent.com/7741669/30680710-84f83c3e-9ee4-11e7-98ac-30a92fc1ff50.jpg)

There are workarounds, like putting in some temp directional lights, but there is a great need for a solid color wireframe mode that can optionally pick up the albedo solid color to use per mesh. Would be great to keep the existing wireframe mode (called wireframe shaded) and have an additional wireframe solid option(like traditional wireframe looks). Since the current wireframe mode does look solid for meshes with luminant textures, I am guessing this is possible?

I agree that a combined unshaded + solid wire mode would be VERY useful! I would mostly use a mode such as this to lay out levels. Currently I mostly use unshaded, with some wireframe or overdraw as needed. The main issue with unshaded is that it is difficult to see any separation between separate meshes, which an overlaid wireframe (or even better just an outline of each mesh) would help rectify.

**Comment by nunodonato** [comment]
@fracteed I also had the same "wow" reaction when I saw that kind of wireframe for the first time. it does look cool, but is it useful? Usually when we need to go into wireframe mode, you dont want to get lighting problems in the way of debugging.

I would say to keep a standard wireframe would be more useful, but maybe we can have both? A cool wireframe and a clean wireframe? :D

**Comment by fracteed** [comment]
@nunodonato I agree that the current wireframe mode is not very usefull. A non-shaded wireframe and a wireframe over unshaded mode would be preferable. I also like that clay mode option you mentioned. To take that idea further, I would love to see a "matcap" option as can be used in Blender or Zbrush. This is very useful to see all models with uniform shading/lighting with some added cavity shading to simulate SSAO.

**Comment by nunodonato** [comment]
according to comments I read in other issues, by @akien-mga  and @reduz , it seems the gizmo problems won't see a fix before 3.2 when we have render layers. So I guess that for now maybe this isn't a showstopper?

would it be useful to do a PR with a different wireframe and clay mode?

**Comment by akien-mga** [comment]
Assigning to @reduz as per https://github.com/godotengine/godot/pull/20333#issuecomment-446246476 and IRC discussion.

**Comment by aaronfranke** [comment]
Considering this has to do with rendering, should it have the 4.0 milestone?

**Comment by clayjohn** [comment]
Lighting mode has been added. Still need to improve wireframe mode to close this.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1000, as feature proposals are now tracked on the Godot repository.
