### ISSUE TITLE
Textures appear to have strange colors.

### ISSUE THREAD

**Issue by antonyjones67** [godotengine/godot#11394]
Godot Engine v3.0.alpha.custom_build.41715c1

Using Sponza Model: Brick appears to be yellowish in color.

Just load Sponza model from Crytek. Exported from Blender using Better Collada Exporter.

![image](https://user-images.githubusercontent.com/3905646/30559254-4897766c-9c71-11e7-9c86-6553b78406c6.png)

This keeps printing repeatedly in Console.
   At: drivers\gles3\rasterizer_gles3.cpp:122
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 1282        Severity: High  Message: GL_INVALID_OPERATION error generated. Texture name does not refer to a texture object generated by OpenGL.
   At: drivers\gles3\rasterizer_gles3.cpp:122

**Comment by henkz1** [comment]
> Just load Sponza model from Crytek. Exported from Blender using Better Collada Exporter.

There seem to be quite a few steps not described here, could you share the project or a smaller example of the same issue? Also it would seem like a good idea to mention gfx card, drivers and os when the issue is about rendering..

**Comment by antonyjones67** [comment]
Windows 10. Intel I7. Geforce GTX 1060. The project is too big to upload. The Sponza model can be found here. http://www.crytek.com/cryengine/cryengine3/downloads.

**Comment by antonyjones67** [comment]
[Sponza.zip](https://github.com/godotengine/godot/files/1312464/Sponza.zip)
Here is the Collada file without textures.

**Comment by Calinou** [comment]
I can reproduce this with the Sponza model and textures found on the link above.

This is because the first material uses the same texture for both albedo and normal map. Therefore, Godot imports the texture as RGTC, which only contains red and green channels. Thus, the albedo is displayed with a "yellow" tint. If you disable **Normal Map** in the texture's import dialog, it will look bad because the normal map also uses that texture. So, you also need to change the material's normal map texture to the actual normal map, which is `spnza_bricks_a_ddn.tga`.

I'm not sure if we should leave this open – it might be a Godot-specific bug, I'm not sure.

**Comment by reduz** [comment]
This is not a bug, if the project uses the same texture for albedo and normal map, this will happen.
You may see this bug from time to time in OBJ files, because OBJ does not really use normalmap but bump map.
