### ISSUE TITLE
NinePatchRect doesn't work as expected with shaders

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11483]
(using current master)

There doesn't seem to be a way to use add shader effects to a NinePatchRect in a straightforward manner (unless I'm missing something), as it starts behaving like a stretched texture:

![screenshot_20170921_234908](https://user-images.githubusercontent.com/16531565/30728669-9a90864e-9f27-11e7-9b90-07ffd92e95a3.png)

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.
