### ISSUE TITLE
Bug in shader with alpha and double sided on

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#11491]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
master branch

**Issue description:**

I'm trying to do a dissolve shader with double sided actived like this:
![2017-09-22-075826_232x231_scrot](https://user-images.githubusercontent.com/1387165/30741623-e5ae6206-9f6b-11e7-9443-a56c082888d7.png)

But when I try to use alpha with cull_mode disabled this happens:
![2017-09-22-075314_468x445_scrot](https://user-images.githubusercontent.com/1387165/30741431-1c922952-9f6b-11e7-83d9-35014cc9f1b0.png)

If I set cull_mode to back, that bug not happens:
![2017-09-22-075324_468x427_scrot](https://user-images.githubusercontent.com/1387165/30741426-1ab590f6-9f6b-11e7-8dfa-490950c51f2a.png)

**Steps to reproduce:**
Set Transparent to on and cull_mode to disabled.
![2017-09-22-075633_226x437_scrot](https://user-images.githubusercontent.com/1387165/30741733-5f026738-9f6c-11e7-96af-a0be7464c87b.png)

**Comment by guilhermefelipecgs** [comment]
Apparently, when use alpha, depth test is ignored, even without selected.

**Comment by hi-ogawa** [comment]
Hi @guilhermefelipecgs , I think in your case, "Depth Draw Mode" has to be "Opaque Pre-Pass" because otherwise alpha material doesn't write into depth buffer even though depth test is actually enabled.
Please check the screenshot below:

![double_face_transparent_depth_draw](https://user-images.githubusercontent.com/4232207/31756836-158f4be0-b4e1-11e7-96bb-d0de585965b0.png)

Could you try it? Let me know if it works.

**Comment by guilhermefelipecgs** [comment]
Works nice.
Thanks!
![2017-10-19-144324_603x566_scrot](https://user-images.githubusercontent.com/1387165/31783117-e2bc4218-b4db-11e7-9e5a-6bdcbd737994.png)
