### ISSUE TITLE
Get-function for VehicleWheel::m_skidInfo

### ISSUE THREAD

**Issue by dracc** [godotengine/godot#11531]
Linux, seems platform independent
Godot 3.0-alpha d3ea922

**Issue description:**
I can't seem to find any way to fetch VehicleWheel::m_skidInfo in GDscript. This seem to be rather useful if creating a vehicle-based game.

**Steps to reproduce:**
Use editor, try to find m_skidInfo value of a VehicleWheel

I'm not sure this should be considered an issue but was asked to post here by Odino on IRC.

**Comment by dracc** [comment]
@AndreaCatania

**Comment by ArdaE** [comment]
Looks like a `get_skipinfo()` method was added a few days after this issue was created, mostly likely in response to it, but it looks like the contributor forgot to mention that here.

The function works the opposite of its documentation (1.0 seems to indicate no skidding, and 0.0 complete skidding) for both Bullet and GodotPhysics. Also it seems to be valid only when is_in_contact() is true (as it returns the value for "no skidding" when the wheel isn't touching anything), but those are outside the scope of this issue entry. I think this issue can be closed.

**Comment by akien-mga** [comment]
Fixed by #11713.
