### ISSUE TITLE
Line2D node rare behave

### ISSUE THREAD

**Issue by zarsystem** [godotengine/godot#11533]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
 On OpenSuse tumbleweed and Godot version 3.0.alpha.custom_build

**Issue description:**
Line2D node behaves like following video when using "Joint mode: Sharp"

**Steps to reproduce:**
1- Create a Line2D node and set width = 10
2- Set the "Joint mode: Sharp"
3- Try to do following action

![ezgif com-optimize](https://user-images.githubusercontent.com/3175411/30780694-f613d5d2-a11d-11e7-869b-fc01217e2725.gif)

**Comment by Zylann** [comment]
Can you describe your action? It's been a week I am unable to see images on Github

**Comment by zarsystem** [comment]
OK, I attached that video here, download it please. 
[line2D.zip](https://github.com/godotengine/godot/files/1327327/line2D.zip)

**Comment by Zylann** [comment]
Unfortunately I can't download it either, my ISP seems to block Github content, because reasons

**Comment by Zylann** [comment]
I asked someone to repost it somewhere else so I saw the gif.
Two things are going on, one of them is a bug:

1) The big corner on the left is cut when the angle is too small, this is intented because otherwise it would be too big, eventually causing a divide by zero, but there is a threshold to configure this

2) One of the segments is folding on itself, that one is a bug. There must be somewhere in LineBuilder where two points need to be swapped (or not be swapped) in this case

**Comment by zarsystem** [comment]
OK, so thanks. 
In rounded joint mode anything is OK.
