### ISSUE TITLE
Syntax highlight for the $ get node synatax.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#11554]
Currently when using $ to get a node, the node's name is highlighted with the default syntax highlighting, which can make it inconsistent with default node names
![](https://i.imgur.com/JxQ2Uy9.png)
The word after the $ should have its own color to differentiate it from other things in the code.

**Comment by paezao** [comment]
Anyone already working on this? Id like to give it a shot.

**Comment by Paulb23** [comment]
I don't think this one should be a Junior job, its part of a larger issue to do with Syntax highlighting as its too specific to GDScript. 

I think for now it would be better to de-highlight a keyword if it starts with a '$'. Unless we start adding flags into `text_edit.cpp` for different languages?

**Comment by paezao** [comment]
De-highlighting would definitely be a lot easier. Should I do that or leave this one for someone with more experience?

**Comment by Paulb23** [comment]
@paezao Feel free to have a go!

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.
