### ISSUE TITLE
3D Particles, move emission mesh creation menu to Inspector

### ISSUE THREAD

**Issue by curly-brace** [godotengine/godot#11566]
there could actually exist a way if arrays were available as shader's uniforms, one can pass an array of verts and their normals to the control shader and it will place particles on random verts.

but i think particle system needs a better way for this, i think user should specify emitting shape in the particle system's settings, not the control shader, so that control shader runs on already properly placed particle

**Comment by akien-mga** [comment]
You mean like this?
- https://twitter.com/reduzio/status/850062714424709121
- https://twitter.com/reduzio/status/850077188275798018

**Comment by curly-brace** [comment]
@akien-mga yeah, but how to do it? i don't understand.

**Comment by akien-mga** [comment]
No idea :o)

**Comment by sezit** [comment]
1. Select Particle node.
2. Select one of two options.
3.???
4.PROFIT!
![pic](https://user-images.githubusercontent.com/6241034/30803518-87ee6fd8-a1f2-11e7-8e6b-67c9013b82b3.png)

**Comment by curly-brace** [comment]
@sezit holy molly! it is again so counterintuitive! all the cool stuff is always hidden on the toolbar 🤣

**Comment by akien-mga** [comment]
Reopening, as it is indeed quite counter-intuitive. The toolbar should be for actions, not options - the latter should go as properties in the inspector.

**Comment by groud** [comment]
> Reopening, as it is indeed quite counter-intuitive. The toolbar should be for actions, not options - the latter should go as properties in the inspector.

I don't know, actually the entry says "Generate Emission point from Mesh". So it is kind an action.

**Comment by curly-brace** [comment]
then may be my suggestion about reworking the system structure?

because i see that emitting from the mesh is available indeed, but only using standard control shader, but how to use it in custom control shader?

if emitting mesh will be specified in global particle system setting (where lifetime and count is), control shader will work directly with some particle that is already placed properly and has may be an initial normal passed as built-in

**Comment by reduz** [comment]
you can pass a custom array of emission points so you can actually do whathever you want for more custom behaviors

**Comment by reduz** [comment]
@akien-mga the toolbar problem is quite common, but I prefer to wait until inspector is properly rewritten so we can put most of the options together in the inspector. Unity does this pretty well.

**Comment by NathanWarden** [comment]
@reduz Making the inspector (and the rest of the editor) as robust as Unity's would be very very very useful, especially for being able to write custom systems that don't really belong at an engine level. I'm not sure how familiar you are with it, but you can basically completely override the inspector for a particular script and use their immediate mode GUI to manipulate any "exported" values however you want.

If you ever want a quick rundown of it, I'd be happy to make a short video covering essentially all parts of what you can do with the Unity editor. I've spent a lot of time in it (since Unity 1.x until today).

IE, for the inspector:
1) Instead of showing an array of numbers the developer can write their own editable graph that would show instead.
2) You can have a boolean and whether it's true or false you can show other particular exported properties. A common use case in some scripts is that the programmer will have a boolean called "Advanced Mode". When clicked the inspector will show advanced options, if unchecked it will show basic options.
3) You could show a button that when you press it it will create a new Node where you tell it to.

... and lots of other stuff :)

In Unity, the customization goes beyond just the inspector though. Imagine being able to create the node based shader editor all in GDScript/C#/etc.

**Comment by reduz** [comment]
@NathanLovato The idea is similar but definitely not the same as what Unity does (and definitely not using Immediate mode GUI). IMO I think the rest of the Godot editor is pretty robust already, only the inspector is lagging.

**Comment by NathanWarden** [comment]
@reduz I haven't dug into the rest of the editor quite yet, but will get there eventually. ;) The inspector to be more robust would be huge! :)

And I agree, IM GUI is pretty poor performing, is annoying since your drawing and input don't always match up, causes lots of garbage collection when coupled with Mono/C#, etc. It's just what Unity happens to use for their inspector and I think they would get rid of it if they could.

**Comment by NathanWarden** [comment]
@reduz I started writing an AI system (Behavior Tree) for Godot about 2 years ago and got pretty far, but it became very evident that internally really isn't the place for it. I think if I could move it over as a "plugin" of sorts via scripting and be able to draw essentially whatever I want into the inspector that would be a big win for systems like this.

https://github.com/NathanWarden/godot/tree/ai

IE. In Unity I can create a custom inspector where I can draw and edit data for child objects by selecting the parent object. As an example in the case of AI, if I click on the Behavior Tree's brain I could also show/edit/add/change it's children all in one place instead of having to click on individual child behavior nodes. Unity uses somewhat of the same process for the sub emitters in it's particle system.

I don't know if you mean to make it robust in this sense, but just food for thought.

Anyway, back to porting one of our support projects from Unity to Godot. It loads a bunch of images. For one set of images Godot takes 155MB *in total* and Unity takes 520MB for *just the images* :)

Here's an image of what I'm talking about for another AI system I wrote.

![custominspector](https://user-images.githubusercontent.com/629422/31238301-2d7b70da-a9bf-11e7-95f7-82ed36bd5397.png)

**Comment by reduz** [comment]
@NathanWarden  You can already do this with Godot easily with a plugin. Instead of the inspector. You can add a custom dock or use a bottom panel for whathever you want. You can even edit the GUI for your plugin with Godot itself.  Doing it in the inspector may help, but it's not the intended use case.

**Comment by NathanWarden** [comment]
@reduz Good to know. I really need to dig into it the plugin system and see what I can get done with it :)

**Comment by kubecz3k** [comment]
Changing milestone to 3.1 (3.x) based on reduz statement that new inspector could/should handle this.
