### ISSUE TITLE
Talking about current EQ and AudioEffectFilters

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#11606]
This issue is to talk about the AudioEffectEQ and AudioEffectFilter.

I'm on writting the AudioEffects doc and I need some opinion about the differents Filter effects and EQ :
For now, there is 3 AudioEffects equalizers (EQ6, EQ10 and EQ21) at fixed frequencies without possibility to set the filter type of each. Added to that there is 7 AudioEffects with specific EQ type (BandLimitFilter, BandPassFilter, HighPassFilter...) having one unique frequency. If you want a very fined audio shape you have to add a lot of AudioEffects on a single bus.
I think this system isn't the good way to do this because it can be a mess to use and isn't the standard in other audio Apps.
Better would be to have a "AudioEffectEQParametrable" with configurable frenquency AND filter type, avoiding  the mess of lot of filter like BandLimitFilter, BandPassFilter, HighPassFilter for just one audio bus.

talked about that with @Zylann, @vnen, Masterizer and oneoh on Discord.

Exemple from Reaper :
![image](https://user-images.githubusercontent.com/7358899/30856890-1b231dd6-a2ba-11e7-84ac-c149eaa4f706.png)

One EQParametric like this with some EQ 6, EQ 10, EQ21 presets can avoid all others Godot EQ.

**Comment by vnen** [comment]
Is "Parametrable" an English word? This type of EQ is called "Parametric".

Just to be clear, I don't think any of the other EQ effects should be removed, since they can be used standalone without the need for a full parametric effect. In any case, configuring it all in one effect can be useful sometimes.

**Comment by Zylann** [comment]
Tbh I see this like a UI-only issue, since the functionality such UI exposes can be replicated using the multiple effects stacked in a bus, except the UI gives better overview than the bus effect list.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
