### ISSUE TITLE
Same shader applied on lines and plane outputs different color

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11645]
Godot 3.0 master
Windows 10 64 bits
nVidia 940M

I noticed that if I output pure white as ALBEDO in a shader, it shows white on a plane, but dark blue on lines in a test project with default environment and a directional light, as if it was constantly in shadow. Same with an empty environment: quad is white, lines are black.
It's fairly minor though, because using `shader_mode unshaded;` let you output the color directly, bypassing shadows.

![image](https://user-images.githubusercontent.com/1311555/30943849-1bb397ea-a3f4-11e7-86c0-0ead28db2877.png)

Shader:
```
shader_type spatial;

void fragment() {
	ALBEDO = vec3(1,1,1);
}
```

Project:
[LineColorShader.zip](https://github.com/godotengine/godot/files/1339070/LineColorShader.zip)

**Comment by BastiaanOlij** [comment]
Keep in mind that the brightness is determined by the angle at which light hits compared to the normal of the surface the light hits on.

With a quad the normal is straight up.

With a line.... uhm.... line..... there really isn't a sensible normal on a line, so it could really be any direction perpendicular to the line, it's likely just pointing flat in the X or Z direction instead of pointing up like the normal on the plane. And thus the lighting is different, and thus the color is different.

You probably want to make the material an unshaded material. I'm not sure if you have any sure way to set the normal of your lines to point upwards.

**Comment by Zylann** [comment]
yeah it's fairly minor due to "unshaded" getting rid of the lighting burden, however I also found that my lines don't have normals so that's another reason why^^
Also it can make sense for lines to have a normal if they represent a surface (wireframe mesh for example), so in the end it looks more like a misunderstanding of the rendering pipeline, since it just needs a different approach.

**Comment by BastiaanOlij** [comment]
It's a hard one I think. You could also argue that with a line the normal should always be perpendicular to the line but adjusted to the plane the light vector is in. In theory a line is an infinitely small tube. Not having a normal at all, hmm thats a pain...

Wireframe is a different scenario. Proper wireframe you aren't rendering lines but just the edges of the polygons so the lighting is still applied exactly equal to the lighting of the plane. The lines will never have the amount of information needed to approximate that, especially with more involved shaders.

I'm not really sure there is a right way to it, but not having taken a close look at how lines are being rendered I don't know if there is a easy fix that makes decent sense.

**Comment by Zylann** [comment]
I understand the engine just works the same with lines and triangles, my issue was either 1) not using unshaded mode, 2) not defining normals, so I'll close the issue :)
