### ISSUE TITLE
Implement Sheen in the spatial material

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11647]
Sheen wasn't properly explained in Burley's 2012 paper, but [Disney's BRDF Explorer has a reference implementation](https://github.com/wdas/brdf/blob/master/src/brdfs/disney.brdf), according to which sheen simply means the linear interpolation between 1.0 and albedo tint (that is, linear color per luminance) in the amount of sheen tint. Looks like we can simply implement this within the spatial material.

As a side note, Blender seems to have adopted it as-is.

@reduz WDYT?

**Comment by reduz** [comment]
I could not find any information in how sheen is supposed to look. I
implememted Rim, which not sure if it's the same and I quite like how it
looks... But not sure if it's the same

On Sep 27, 2017 10:53 PM, "Ferenc Arn" <notifications@github.com> wrote:

Sheen wasn't properly explained in Burley's 2012 paper, but Disney's BRDF
Explorer has a reference implementation
<https://github.com/wdas/brdf/blob/master/src/brdfs/disney.brdf>, according
to which sheen simply means the linear interpolation between 1.0 and albedo
tint (that is, linear color per luminance) in the amount of sheen tint.
Looks like we can simply implement this within the spatial material.

As a side note, Blender seems to have adopted it as-is.

@reduz <https://github.com/reduz> WDYT?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/11647>, or mute the thread

**Comment by tagcup** [comment]
The main differences as 1) he uses Schlick for angular dependence rather than a roughness dependent power 2) he varies over L.H rather than N.V 3) uses tint rather than diffuse 4) has an overall 1-metallic factor.

It's more art than science of course, but it looks like to be that rim probably needs a roughness-dependent normalization factor to preserve energy, since it appears in the exponent.

**Comment by reduz** [comment]
I remember trying the sheen parameter from BRDF explorer and, honestly, it
didn't look very good. Either the implementation is not the same as Disney
uses or it's just not good enough.

For simulating fabrics, the RIM implementation I added, while not energy
conserving (well, this could be added I guess) looks nicer IMO.
I suppose workst case, sheen could be added but I still havent seen good
use cases where it look good.

**Comment by tagcup** [comment]
I can add a normalization factor for rim (FYI, it involes a hypergeometric function thanks to cos power), but to ensure that it makes sense physically, I'd need 1) to do this for flux due to rim, meaning before we multiply other flux terms with attenuation etc 2) the normalization factor will be different with diffuse and diffuse+rim cases

**Comment by reduz** [comment]
yeah, normalization makes sense to make it energy conserving, and yes i
guess you will have to change the order for this, but it should be not that
difficult.

**Comment by tagcup** [comment]
Having rim contribute to flux rather than diffuse would be straightforward to do, but I guess the difficulty lies in artistic aspect, because flux will get attenuated and mixed etc which is not happening to rim at the moment

**Comment by tagcup** [comment]
BTW I can probably find an approximating function for the hypergeometric function which overestimates (in fitting errors) the normalization factor such that errors would lead to energy loss rather than gain.

**Comment by reduz** [comment]
The idea of rim is to simulate this effect on fabrics (in this image, this is very exaggerated because hair strands are obviously visible). On fabrics with much smaller fur it looks similar but smoother.

![image](https://user-images.githubusercontent.com/6265307/31022892-944eeeee-a510-11e7-9b28-1fcc4e684523.png)

I'm not exactly sure how to make it energy conserving, because technically it's like a wrap, but it isn't at the asme time.. so it's just an approximation.

**Comment by tagcup** [comment]
But don't you think we can change rim code slightly such that it contributes to BRDF? Because energy conservation is straightforward then (we just evaluate a single integral with *total* BRDF)

**Comment by reduz** [comment]
i think, as you mention that normalization on diffuse should more or less
work, i just can't think of a good way to do it

**Comment by tagcup** [comment]
Ah, no, what I'm saying is, we need to do normalize the BRDF itself, before it weights incoming light and produces diffuse. Thus meaning can we change rim code such that it contributes to light_amount rather than diffuse?

**Comment by reduz** [comment]
oh yeah that should be fine, though light_amount will have to always be a
vec3 in this case.

**Comment by tagcup** [comment]
Great
Ah yeah that makes sense since a BRDF can weight different colors differently in general

**Comment by tagcup** [comment]
BTW can rim contribute from back like transmittence? And if yes, would you say front and back contributions to light are totally different? Just asking since it determines the bounds of the integral

**Comment by tagcup** [comment]
If they're different I guess we can do front in the BRDF and add the back contribution in transmittance for example

**Comment by tagcup** [comment]
Sorry about such basic questions BTW, I just recently started reading about computer rendering and PBR light is about the only thing easy to understand with my background

**Comment by reduz** [comment]
The problem with transmittance is that it's not completely implemented yet.
I need to add thickness support for it, so it works nicely together with
subsurface scattering. Once that is supported, it will be way too difficult
to properly make it conserve energy, so it will most likely not be worth it.

**Comment by reduz** [comment]
To make it a bit clear, right now transmittance works 100% for all incoming
light. This effect needs an extra parameter named "thickness" that is used
together with shadow mapping to determine the distance from the back-side
to the front size, and only allows light to pass through beyond that
certain amount.

It is an approximation for sub surface scattering effects like the ones you
see in ears or fingers when exposed to a light and, while it's difficult to
make it energy conserving, it's probably not really worth it either as it
can easily be artist adjusted.

**Comment by tagcup** [comment]
OK, I'll try to look up how rim/sheen physically works (at this point I just don't know what it exactly is) during the weekend, and maybe it'll just turn out that only the front contributes.

If I recall correctly, currently, rim contributes only in the upper hemisphere anyway, so everything should be fine. Either way, it's not actually hard to make it energy-conserving, we just need to calculate the normalization factor for the total BRDF

**Comment by tagcup** [comment]
assuming that it's integrable of course (which happens to be the case here)

**Comment by tagcup** [comment]
Aside from making it contribute to light_amount, I realized that rim code currently isn't symmetric and missing N.L term. To make it a BRDF that can be normalized, the contribution needs to be in the form `rim(L,V) N.L` where rim(L,V) is the BRDF function which satisfies rim(L,V) =rim(V,L) (which is essentially Helmholtz reciprocity).

There are velvet BRDFs in the literature which I can play with and try to tune to get something similar. Does this sound good to you?

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
