### ISSUE TITLE
Connected signals will be disconnected if the target node changes its type

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#11673]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/4f39ce32b9195405f934445b20059e86632b47f9

**Issue description:**

When changing the type of a node all connected signals to that node will be disconnected.
![https://i.imgur.com/s0h1LVZ.gifv](https://i.imgur.com/s0h1LVZ.gif)

**Steps to reproduce:**
1. Create two nodes
2. Connect a signal from one to another
3. Change the type of the target node

**Comment by reduz** [comment]
I honestly see the code to reconnect the signals here, so it may be bugged.
https://github.com/godotengine/godot/blob/master/editor/scene_tree_dock.cpp#L1434
If anyone wants to test this and get it to work, feel free.

**Comment by AyeTbk** [comment]
(I am currently on Godot 3.0 master ec77ccc)
While trying to reproduce this, I found that the problem occurs when the method the signal is connected to comes from an attached script. If the signal is connected to a method of the node itself (rather than of the attached script), the problem doesn't occur: the signal remains connected.

When the problem occurs, Godot tells us:
[`scene/main/node.cpp:2425`](https://github.com/godotengine/godot/blob/ec77cccb1dab35a6f655cf5946a48cbfc1f598cf/scene/main/node.cpp#L2425)` - Condition ' !p_new_target->has_method(c.method) ' is true. Continuing..:`
Looking at that line, if `Node::has_method` returns `false`, the signal is not reconnected on the new node.

`p_new_target` does not have the method because its script instance is set to a placeholder (I checked with `ScriptInstance::is_placeholder`). It's created at [scene_tree_dock.cpp:1441](https://github.com/godotengine/godot/blob/ec77cccb1dab35a6f655cf5946a48cbfc1f598cf/editor/scene_tree_dock.cpp#L1441) and is never given a script instance.

I don't know how to properly give it the right script instance. I thought I could do something along the lines of `p_new_target->set_script_instance(get_script_instance())`, but then both Nodes use the same script instance (which is problematic because one of them might end up freeing the script instance's memory, such as when the node is destroyed or when you try to set its script instance to something else).

Should the script instance be copied? Should it be moved in some way to prevent (what I think is) unnecessary copy?
