### ISSUE TITLE
Schlick-GGX F0 value is hardcoded to 1

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11677]
I believe this was read from a texture a some point. The current value is quite off for dielectrics.

**Comment by reduz** [comment]
@tagcup Is this still valid?

**Comment by tagcup** [comment]
Yes

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by clayjohn** [comment]
@akien-mga this was fixed by PR #22483, it can be closed.

**Comment by akien-mga** [comment]
Thanks, closing.
