### ISSUE TITLE
Materials look very different in Godot compared to Substance Designer

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#11685]
![Rendering in Godot 3](https://user-images.githubusercontent.com/180032/31014300-6c28a194-a51a-11e7-8cfa-0d4cd52b5cdd.png)

The rendering looks much more "bland" in Godot compared to Substance Designer. (Disregard the lack of depth, it doesn't work well with CubeMeshes.)

![Rendering in the Substance viewport](https://user-images.githubusercontent.com/180032/31014213-0a803632-a51a-11e7-9274-571e3f3044c5.png)

**Link to minimal example project:** [yamt.zip](https://github.com/godotengine/godot/files/1344141/yamt.zip)

**Comment by quantum-entangler** [comment]
To better measure any real difference between substance designer and godot 3 shouldn't you start by replicating the lighting set-up/condition as precisely in godot as possible?

**Comment by gamergamesz** [comment]
manually adding it solves thingies right now metal value is .4 in demo

**Comment by Calinou** [comment]
> manually adding textures solves thingies, right now metal value is .4 in demo and it should be 1

I tried many other metallic values (including 1), but this made the material look too dark and contrasted (compared to the rendering in Substance).

**Comment by gamergamesz** [comment]
Well i also use environment correction and changed color management to filmic and normal is -1

**Comment by gamergamesz** [comment]
Well i also use environment correction and changed color management to filmic and normal i changed normal to -1

**Comment by fracteed** [comment]
@Calinou , I had a look at your project. Nothing seems to be wrong with the textures other the normal map is somehow reversed (it shouldn't need to be at -1 with Godot). You need to keep metallic and roughness at a value of 1 when using maps. Specular should almost always stay at the default 0.5 (which means the facing reflections are at 4%), although for a metal material such as this it makes no difference what value you use. Still a good habit to get into though.

You will always get better results if you use a HDR, as your environment image is just a jpg (LDR). Keep in mind that metallic surfaces are totally dependant on reflections from their environment (hdr map and/or reflection probes) so they will only ever look as good as what they reflect! If comparing between Substance and Godot, you will need to use the same HDR and angle in both. I have done tests and Godot is very close, though I have noticed that recent commits by tagcup and reduz could get it closer (Burley default amongst other fixes).

It is harder to get things to look metallic on all flat surfaces, so also test on spheres/capsules. It is also a good idea to combine your metallic/roughness/AO into one map ala UE4 since you will then only need 3 maps for most objects (base color, normal, AO/Ref/Met).

You can see it looks better in the following image. Have also added a couple of omnis for better highlights:

![metal1](https://user-images.githubusercontent.com/7741669/31065549-e70c69ee-a791-11e7-91b7-36d15221c1b2.jpg)

**Comment by mhilbrunner** [comment]
Is there anything concrete that needs to be fixed or can this be closed with regards to **fracteeds** comment above?

**Comment by Calinou** [comment]
Based on @fracteed's input, I guess this can be closed. Thanks :smile:
