### ISSUE TITLE
Support for #include in shaders

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#11691]
In Godot 3.0

It would be useful to have #include functionnality in shaders for easy re-use of functions (I found this: https://github.com/godotengine/godot/pull/4505 but it only concerns built-in shaders).
I'm pretty sure this was suggested at some point when discussing on the new shader langage, but I could't find an issue about it.

**Comment by TheAspiringHacker** [comment]
Should the #include handled by a preprocessor or during the compile step?

**Comment by justinluk** [comment]
This is becoming a huge issue for me. Shaders quickly become unwieldly without being able to include.

**Comment by alex-evelyn** [comment]
I want to be able to include files in Shaders. I just got permission from the author of [this ShaderToy shader](https://www.shadertoy.com/view/3lXXWX) to use in my game. I am now working on porting the shader to Godot, but I have yet to figure out how to include the "Buffer" shader that is used by the main file.

**Comment by Zylann** [comment]
@alex-evelyn I think what's in `buffer` in this shadertoy is sound, you probably don't need it

**Comment by Hidden-Abstraction** [comment]
This becomes necessary to reuse code, it is very useful to have custom libraries.

**Comment by Calinou** [comment]
@Hidden-Abstraction Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
