### ISSUE TITLE
Add script dialogue class name (probably?) shouldn't get disabled

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#11715]
In the add script dialogue, selecting a script file disables Class Name input box, but it's contents are apparently important because when the class name if empty, you get "Invalid Class Name" in red below.

**Comment by akien-mga** [comment]
I wonder, does the class name serve any purpose at all, apart from suggesting a file name?

**Comment by neikeq** [comment]
It's needed for languages like C#.

**Comment by Oranjoose** [comment]
@neikeq Yes, but doesn't C# require that both the class name and the script name be the same? If that's the case, then an editable class name field is useless, since the script name implies it.

**Comment by neikeq** [comment]
Yeah, we were talking about that the other day, it's no longer using it on master anymord.
I think it's needed though, for GDNative.

**Comment by akien-mga** [comment]
Fixed now AFAIK.

**Comment by neikeq** [comment]
Are you sure? Which commit fixed it?

**Comment by akien-mga** [comment]
I thought you had fixed it, must have been dreaming :)

**Comment by reduz** [comment]
I dont understand how this is a bug

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
@willnationsdev I know you worked on this, is it still an issue?

**Comment by akien-mga** [comment]
I also still don't get what's the problem here, so closing.
