### ISSUE TITLE
Add signal for when AnimationPlayer has processed an animation frame, 

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#11746]
There should be an equivalent of get_tree()'s "idle_frame" for the AnimationPlayer (or AnimationTreePlayer?), just when it has finished the update for the current frame. This would make it possible to override animation transformations during coroutines. At the moment, we can resume execution at what I assume is the start of each frame (idle_frame), but not the end. So an alternative to adding the signal to AnimationPlayer, could be to add a signal for when all objects have updated, something like "idle_frame_post".

Problem example:
```
func _start_cursor_aim_routine():
    var timer = 0
    var duration = 1
    var start_angle = some_obj.rotation_deg
    while timer < duration:
        var end_angle = rotation_towards_cursor
        timer += get_process_delta_time()
        some_obj.rotation_deg = lerp(start_angle, end_angle, timer/duration)
        yield(get_tree(), "idle_frame")
        [animation updates after each time this function resumes, thus overriding everything we do here :( ]
```

To work around it using booleans and _process() is a huge hassle, as it required me to create at least 8 class variables compared to only local variables

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
