### ISSUE TITLE
Add timeseek_node_get_seek in AnimationTreePlayer.

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#11771]
Currently we can only set the seek in an animation node by using timeseek_node_seek but we do not have any way to get the position of the animation.

Other animation nodes have set get methods but this one does not.

It seems reasonable to rename the method timeseek_node_seek to timeseek_node_set_seek and create a new method timeseek_node_get_seek.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
