### ISSUE TITLE
3D editor freelook does not work correctly before changing editor shortcuts on non-QWERTY keyboards

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#11777]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Any OS, godot 3.0

**Issue description:**
Keys binded to the 3D freelook are wrong with [AZERTY keyboard](https://en.wikipedia.org/wiki/AZERTY ).

Solution : 
* auto-detect the keyboard type (or use current user language) to sets propers key for logic freelook 
* Allow the user in Editor settings to changes keys for freelook
* Bind freelook to LEFT UP RIGHT DOWN keys

**Comment by toger5** [comment]
I think LEFT UP RIGHT DOWN should be added. that is useful anyways and the easiest fix.
How are other applications (games) handling AZERTY keyboards? Do they autodetect and remap the keys?
If not I would just expose the freeload keys to the shortcut section. If all of them do and ppl using AZERTY are used to that it might be worth it to add a auto detection.

**Comment by Zylann** [comment]
All freelook keys can be rebound in editor shortcuts. If you have problems with AZERTY, it doesn't only concerns freelook, but all shortcuts involving character keys.
@toger5 freelook, not freeload, you do the mistake so many times :D

**Comment by toger5** [comment]
@zylann i do? Damn it...
I really should stop using github on my phone...
Akien mga also blamed me already for not beeing able to type correctly...

Cool that remapping is already supported.
@Jerome67000 is that already a solution for u?
I think we also could add the additional UpDownLeftRight keybindings...
If you guys think thats a good improovement.
Otherwise other keyboard types need to remap (or just switch to us keyboard (thatd what i did ;) ))

**Comment by bruvzg** [comment]
Some keyboard type detection and [remapping code](https://github.com/godotengine/godot/blob/bd282ff43f23fe845f29a3e25c8efc01bd65ffb0/core/os/keyboard.cpp#L529) for [Window](https://github.com/godotengine/godot/blob/372cdc20705dab7c2227b89d8bc4d425ffd3e8a4/platform/windows/os_windows.cpp#L2171) and [macOS](https://github.com/godotengine/godot/blob/9a70ecfb9045ff3587d0f9559c949cf8ccbd88e4/platform/osx/os_osx.mm#L1783) already there, but it is used only on [macOS](https://github.com/godotengine/godot/blob/9a70ecfb9045ff3587d0f9559c949cf8ccbd88e4/platform/osx/os_osx.mm#L750).

**Comment by Calinou** [comment]
This bug occurs in both the editor and exported games. It's really annoying (I'm an AZERTY user as well), since it requires you to re-bind most keys in programs which don't support keyboard layout translation.

**Comment by Jerome67000** [comment]
@toger5 yes this solution can be viable :).

Just in case we change for LEFT UP RIGHT DOWN, be care because for the moment it's used to switch from 3D view to the left or right panel. BTW I don't think that is the best way to solve this problem. Using auto detect to setup freelook to QZDS when AZERTY is a smatter way and user don't need to setup manually/user don't think "whats this buggy engine" :).

**Comment by akien-mga** [comment]
Well it's not a bug, just a missing functionality. AZERTY users (of which I am) know well enough that they can't expect software to cater automatically to their buggy keyboard layout, especially FPS/TPS using WASD for movement (and incidentally, our freelook controls).

Either we implement keyboard type detection and conversion logic on all platforms as outlined by @bruvzg (in which case it's a feature request that goes far beyond the scope of the freelook usability), or we can add presets in the editor settings for QWERTY / QWERTZ / AZERTY to automatically swap the relevant keys. The former would be the best solution, and could be exposed for games and make internationalization a lot easier, but should likely be discussed in its own issue.

**Comment by Zylann** [comment]
Fun fact: I am an AZERTY user and I coded the part where it polls the keys, and I set the default values to be QWERTY because I could set only one default layout of keys (just like other hotkeys assume this layout to nicely line up). All of that knowing that these are rebindable anyways, because it's the simplest solution.
It would be nice though if EditorSettings could get the editor's language and setup the *default values* with keyboard layout in mind.
Another solution is to simply bind arrow keys (though nobody use them in first-person so people would want to rebind anyways)

**Comment by green-coder** [comment]
Hi, I am using the QWERTY-born keyboard of a MacBookAir which I converted into the "Programmer Dvorak" via physical key relocation (I moved them, physically) and via software (I am using the Programmer Dvorak layout in the MacOSX settings).

Most of the other programs don't have any issues reading the correct keys, but the editor of Godot 3.0.2 still think that I am using the QWERTY layout. There must be some ways to read the keyboard in a world-friendly and compatible way.

It is very hard in my case to guess where are the QWERTY keys. It's not as easy as using an AZERTY recognized as a QWERTY.

**Comment by bruvzg** [comment]
@green-coder Dvorak layout selected from macOS settings works ok form me (3.1 master and 3.0.2 stable), key are detected as they displayed in settings preview, both in editor input and key mappings. macOS 10.13.3 (17D102), with QWERTY PC keyboard.

**Comment by bruvzg** [comment]
@green-coder That's standard Dvorak, if you have "Programmer Dvorak" variant with `;` in the start of first row instead of `'`, I guess it won't be detected correctly, Godot currently detect only limited set of layouts ([os_osx.mm#L2125-L2137](https://github.com/godotengine/godot/blob/master/platform/osx/os_osx.mm#L2125-L2137)), everything else is detected as QWERTY.

**Comment by green-coder** [comment]
Hi. I moved my comment to #808.

**Comment by green-coder** [comment]
Ctrl+S is not recognized properly, I have to press Ctrl+O instead (that's the position of the S in QWERTY and AZERTY).

**Comment by bruvzg** [comment]
@green-coder please test #17827 with your keyboard.

**Comment by fire** [comment]
This issue still happens.

**Comment by clarfonthey** [comment]
I feel like the best way to deal with this would be to separate scan codes (physical key locations) with symbols (what's drawn on the key). Action mapping should be done by scancode (i.e. pressing A on AZERTY would be the same as pressing Q on QWERTY) whereas events will still have the symbol for when you actually want to type something.

**Comment by Calinou** [comment]
@clarfonthey Physical scancodes will be supported in Godot 4.0, but aren't supported in 3.2. (This most likely won't be backported due to significant changes to the input system required.)

**Comment by clarfonthey** [comment]
Oh, nice!

Yeah, physical scancode support is definitely the solution for this, and I'm glad it's coming to 4.

**Comment by starry-abyss** [comment]
> Also, we need to handle conflicts with other non-physical keys that may be bound by default.

What conflicts? Is it not possible to convert ***all*** shortcuts of Godot to layout-independent and only leave the things related to texts (like input fields)?

**Comment by Calinou** [comment]
As of 4.0.beta17, the editor now allows assigning physical key shortcuts in the Editor Settings' Shortcuts tab. The main challenge for providing this configuration by default is assigning shortcuts that use physical key inputs by default. It should be possible but not trivial – you will need to create the Shortcut manually, rather than use a predefined macro.
