### ISSUE TITLE
Android touch errors

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#11798]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 build 6dc1025

**Issue description:**
On android sometimes one touch is stuck in case of multi tap swipe or pinch and produce the following error:
```
10-03 13:36:35.322: E/godot(32648): **ERROR**: Condition ' touch.size() != p_points.size() ' is true.
10-03 13:36:35.322: E/godot(32648):    At: platform\android\os_android.cpp:406:process_touch() - Condition ' touch.size() != p_points.size() ' is true.
```

**Steps to reproduce:**
Try pinch in game

**Comment by sionroberts** [comment]
I also have this problem. Multi-touch isn't working like it did in v2.1. I have attached a test project.

Problem exists in Godot 3. Can't test 3.1 due to #14928. 

Run the attached project on Android. There are two buttons, left and right. There is a label that that tells which one is pressed. Try experimenting with pressing buttons, single and multi touch, holding down on one and pressing the other on off etc. It soon goes wrong. Try holding left down, then tap right a few times.

[touchtest.zip](https://github.com/godotengine/godot/files/1583107/touchtest.zip)

Godot 3.0 beta (Windows 10 x64)
Android 6.1
Motorola G 2nd Gen
GPU: Adreno 305 @450 MHz GPU

Thanks!

**Comment by volzhs** [comment]
@sionroberts there is no 3.1 currently.

**Comment by sionroberts** [comment]
Sorry, I meant v3.0 Beta 2.

**Comment by volzhs** [comment]
I found it is regression from #11775
I tried to fix it in various way without reverting that PR about processing touch.
but I can't find out proper way to fix this.

@endragor do you have an idea about this issue?

**Comment by volzhs** [comment]
@endragor I'm testing in a various way, including revert #11775
but problem is not going away. can't specify what causes this so far. :(
