### ISSUE TITLE
one issue to build godot on Solus Os

### ISSUE THREAD

**Issue by swipis** [godotengine/godot#11833]
Hello,
Not sure I am in right place to tll about this issue but here I go - I tried to build Godot 3.0 alpha on **Solus Os** and get error that _GL/glx.h_ not found. To build Godot I was needed to install **_mesalib_devel_** (not sure for other Solus os users but for on my machine GL/glx.h was missing).

**Issue description:**
 was needed to install _mesalib_devel_ package

**Comment by Hinsbart** [comment]
Hi, thank you for taking the time to report this :)

>Not sure I am in right place to tll about this issue but here I go

Yes, this issue would be better suited for the [godot-docs](https://github.com/godotengine/godot-docs) repository. 
There's already [a list of required packages](http://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html#distro-specific-oneliners) for solus but it says `mesalib` instead of `mesalib-devel`.

**Comment by akien-mga** [comment]
FYI, I fixed the docs.
