### ISSUE TITLE
Repeating TileMaps

### ISSUE THREAD

**Issue by not-surt** [godotengine/godot#1186]
An option to repeat the rendering of a TileMap along one or both axes.

Uses:
Wrap-around maps.
Endless parallax layers. No need to worry about running out of parallax.

**Comment by Wiering** [comment]
Even better, let each tile map have a horizontal and a vertical repeating mode:

- none
- tiled (complete map repeats)
- extend edge tile (last tile keeps repeating, mostly useful for vertical)
- mirror map (map repeats, but every 2nd copy is mirrored, so it will always be seamless)
- mirror tiles (same, but also mirror all the tiles in the mirrored map)

**Comment by bojidar-bg** [comment]
BTW, how are collisions with a repeating tilemap expected to be handled? I guess it would be slow to repeat the collision shapes till they cover some maximal world bounding box, but it would be inconsistent to make them just cover the screen... (as then far-away enemies would simply drop down)

**Comment by Wiering** [comment]
This feature would generally only be used for parallax scrolling backgrounds, usually without any objects or collisions. 
But the map itself stays as small as it is. When drawing in areas beyond the map, you just get a visual copy of the corresponding part (while rendering, you need a function that would map any coordinates to an existing position in the map, depending on the mode, for tiled mode that would simply be position modulo size). 
Objects would only exist in the actual map, but they are rendered in each copy of the map, so you get to see the same repeating objects. You would see collisions, but they are actually only happening in the real map. If an object would go off the map, it would simply disappear everywhere (though you could decide to make objects wrap around the map in this mode).

Personally, I wouldn't mind if objects and collisions aren't supported in repeating maps. I had something very similar in my own game engine and was planning to implement objects as well, but never needed it. But the repeating backgrounds I used all the time (usually tiled for horizontal and extend for vertical).

**Comment by bojidar-bg** [comment]
@Wiering ~ Just to mention, Godot's tilemaps don't have objects... unless you mean children nodes, but the tilemap isn't supposed to even touch those :smile:

**Comment by davidpgil** [comment]
I am wondering how I can do non-parallaxing, non-camera based repeating/tiling scrolling of a Sprite and/or TextureFrame. I have a 256x256 background that is part of a cutscene that I need to use AnimationPlayer to scroll and repeat. Is this something Godot can do?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
