### ISSUE TITLE
SVG import settings shown and saved for non-SVG textures

### ISSUE THREAD

**Issue by sbeca** [godotengine/godot#11928]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Latest master

**Issue description:**
The SVG import setting "svg/scale" is shown for all texture formats, not just SVG files. This is confusing for users as I feel that the expected behaviour would be that this setting is only shown for textures of the SVG type, i.e. textures with the extension `.svg` or `.svgz`.

This setting is also saved to the `.import` file of all texture formats, which causes a large amount of version control noise when people upgrade a project to Godot 3.0 as every texture, SVG or otherwise, gets their `.import` modified to add this setting. My gut feeling is that only SVG files should have this setting saved to their `.import` file but I'm new to Godot so this might not be in line with standard Godot practice.

cc @djrm as I believe he implemented SVG support in Godot

**Comment by djrm** [comment]
unfortunately hiding that parameter will require some changes to all the importers, so for now it has to be like that.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.
