### ISSUE TITLE
GTX 950 has 2-3 second delay on previewing scenes (windows)

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#11939]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4

**Issue description:**
Okay, so my old github issue was [here](https://github.com/godotengine/godot/issues/10977), however, Reddit was wrong.  I was wrong.

There is a bug with the GTX 950 with Godot on Windows. I have proof. It's not about memory bandwidth whatsoever.

Check this out:
https://www.youtube.com/watch?v=m79rB3TnkTY

He previews scenes instantly and I asked what his specs were, he replied: 
> AMD Phenom(tm) II X4 955 Processor × 4
GeForce GTS 250

A GTS 250 has far less memory bandwidth than a GTX 950

Also, this user posted an issue in the discord help channel, of this video: https://cdn.discordapp.com/attachments/342056330523049988/366511629501857792/2017-10-08_11-03-41.mkv

His scene previewing is instant. So I pm'd him and asked what his specs are, he replied with:
> Hi, i use Ubuntu 16.04, Intel® Core™ i5-4440 CPU @ 3.10GHz × 4 ,  Intel® Haswell Desktop

Asked if he wasing the integrated graphics card, he said yes.

# Conclusion

It doesn't make sense that an integrated graphics card has instant previews compared to a dedicated graphic card like the GTX 950.  And also the GTS 250 is 70 GB/s compared to the 90 GB/s GTX 950 and still has instant previews.   It has to be a Windows issue with the GTX 950

**Comment by Zylann** [comment]
This issue remembers me of #10980, in which I also mentionned a startup lag in 2.1.4.

Did you test in 2.1.3?

**Comment by Dillybob92** [comment]
@Zylann Yes sir, even did 2.1.2

Tested on 3.0 latest stable (whatever it was at the time) too back when I had the gtx 950 on my main pc.

[This](https://camo.githubusercontent.com/b4160e85e96c318f0e2ff863d46b840b9563ea95/68747470733a2f2f692e6779617a6f2e636f6d2f33356134333763613363376362313561353831363364633331633164353232652e676966), is basically the issue but only with the GTX 950 on Windows.

What are your specs may I ask, and was yours under windows as well?

**Comment by Zylann** [comment]
I have a nVidia GeForce 940M, so maybe this issue isn't about the GPU, but the debugger? Did you see this lag *not* happen in another Windows machine?

**Comment by Dillybob92** [comment]
If using a different card on Windows (rx 480 for example), it doesn't lag. So definitely **nVidia issue here on Windows ONLY**

Because that guy in my op is using Linux with the GTS 250 and no lag. I bet if you tried Godot on Linux with your 940M there will be no lag.

So. Windows+Nvidia issue only. Now, how do I go about troubleshooting this to give more information? No errors are in the console whatsoever when this happens?

**Comment by Zylann** [comment]
What is the value of `Settings/Network/Debug Host` in editor settings?

**Comment by Zylann** [comment]
I'm not sure, I would put prints in the engine in many places to find the culprit maybe

**Comment by Zylann** [comment]
UPDATE: This is not just GTX. I tested again an empty project by paying more attention, and I realized that I DO HAVE a white frozen window too, which lasts for 1 second, even if the scene just contains one Node2D.
I realize this now, because as @Dillybob92 linked the video of someone on Linux, they can launch their game instantly with no startup lag AND NO WHITE SCREEN LASTING 1 SECOND (pay attention to the detail :p)
Would be nice to nail this down!

**Comment by Dillybob92** [comment]
Yeah, GTX is basically nvidia right? So this is definitely a nvidia+windows ONLY issue.  Looks like happens on the 940M, and GTX 950 and probably countless more.

**Comment by Zylann** [comment]
@groud this also happens in 3.0. For me it opens a white window, freezes 1 second, then shows the Godot splash logo for 0.2 seconds and then the game starts.

**Comment by sketchyfun** [comment]
yeah, I get this in Windows 7 64bit with GeForce 760 GTX running Godot 3.0, can't remember if it's the same with 2.x, although I recall it varying between game runs.

**Comment by x1212** [comment]
I remember having read something about the nvidia driver parsing some lists of profiles on initialization ... so if that is the case, then probably this can't be fixed in godot that easily ...

Here is something I found when searching for where I might have read that https://hero.handmade.network/forums/code-discussion/t/2503-%5Bday_235%5D_opengls_pixel_format_takes_a_long_time#12672
The numbers seem pretty similar (ca. 3 seconds) and it seems to be a Windows NVidia only thing ...
There also seems to be a workaround involving replacing files read by the driver with smaller ones from older versions ... I mostly use Linux and not Windows so I can't try and confirm it if that really works right now ...

**Comment by Jerome67000** [comment]
Same here with Godot 3.0 and Windows 10. I have a GeForce GTX 980.
With linux and the same CG card I don't have this issue (proprietary drivers).

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
