### ISSUE TITLE
GridMap::set_clip() has no effect

### ISSUE THREAD

**Issue by dsaltares** [godotengine/godot#11936]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot master 0fb22b1d2403b6f380d953237b99d99e5c02b2e7

**Issue description:**
`GridMap::set_clip()` sets some properties on the grid map that are entirely ignored. The only time these properties are read is inside `GridMap::_octant_update()` but nothing is done with their values.

```cpp
if (clip && ((clip_above && cellpos[clip_axis] > clip_floor) || (!clip_above && cellpos[clip_axis] < clip_floor))) {
} else {
}
```

`GridMapEditor` seems to be calling `GridMap::set_clip()` and it seems those parameters are exposed via the UI.

![clip_ui](https://user-images.githubusercontent.com/570314/31316001-e8db37d0-ac1b-11e7-8210-eb7fd933e48f.PNG)

**Next action**
Either delete the functions and the options from the UI or actually implement the functionality. Otherwise it can be misleading/confusing for users.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
I am going to give some rewriting to GridMap after 3.1 is out, this is currently too difficult to implement.. so kicking to next version.

**Comment by Wavesonics** [comment]
Is this still an issue? There are no docs explaining exactly what `set_clip` is supposed to do, so I'm not sure if it's working or not.

**Comment by Calinou** [comment]
@Wavesonics Looking at the source code, it still appears to do nothing. It should probably be removed now.
