### ISSUE TITLE
Playing scenes sometimes don't close

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11972]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.04

**Issue description:**
When either by trying to close the window or by clicking "stop" in the editor, sometimes the game window just stays there until clicking "play", which restarts it.

**Comment by groud** [comment]
Godot 3.0 or 2.1 ?

**Comment by YeldhamDev** [comment]
@groud 3.0, since a long time.

**Comment by eon-s** [comment]
Affects 2.1 too, but is hard to reproduce.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by YeldhamDev** [comment]
It has stopped happening to me since a long time, closing it. Please reopen if someone else still suffers from this.
