### ISSUE TITLE
Connected method from "sort_children" not found when opening scene

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#11988]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
[Build](https://bintray.com/calinou/godot/editor) fcd0398 

**Issue description:**
When opening a scene with a Container node with a signal connect from "sort_children()", the Output will print the following error:
`core/object.cpp:1127 - Error calling method from signal 'sort_children':`
`'Node::[Method Name Here]': Method not found.`

**Comment by jagt** [comment]
I found that the error is happening because `sort_children` is calling into a `PlaceHolderScriptInstance` in editor, as editor will not instance actual scripting instances. But I'm not sure how to fix this.

Should errors like these be ignored, or maybe `emit_signal` in editor shouldn't call into place holder scripts?

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by YeldhamDev** [comment]
@reduz Yes.

**Comment by DualMatrix** [comment]
It's likely this has been fixed by #22297, does it still happen in master?

**Comment by YeldhamDev** [comment]
@DualMatrix Can't reproduce it anymore, looks fixed. Closing it.
