### ISSUE TITLE
Godot binaries aren't code signed for macOS

### ISSUE THREAD

**Issue by kvanbere** [godotengine/godot#11984]
Mac OS X 10.12.6 Sierra

**Issue description:**
Downloaded version 2.1.4 of Godot from website. Can't run it _at all_. Running default security preferences.

<img width="422" alt="screen shot 2017-10-10 at 3 17 09 pm" src="https://user-images.githubusercontent.com/1356959/31369143-2c8f45d0-adce-11e7-9bea-5b1b4cf654db.png">

**Comment by TomWor** [comment]
You'll have this issue with many open source applications, because the developers often don't have an Apple developer account that's required to sign those binaries.
You'll have to adjust your security preferences.

**Comment by donkeybonks** [comment]
On contrary, this is the first time I've ever had this problem, most developers just sign the apps.

What's the issue? the cost?

**Comment by TomWor** [comment]
You're right and I don't know what the status is on that front.
I guess it should be done for Godot 3 as I guess there will be quite a bit of news coverage and it'll be quite a bummer for Mac users to run into that.

**Comment by sbeca** [comment]
This doesn't solve the actual problem, but as a workaround you should be able to right-click on the app and select `Open`. Doing so will bring up the same warning dialog but should show an extra button that lets you continue on and open the app.

**Comment by donkeybonks** [comment]
You're right, that does work as a workaround.

**Comment by akien-mga** [comment]
Likely won't change for 2.1.x, but yeah for 3.0 we should start looking into paying the Apple and Microsoft mafias to get our binaries "certified"...

**Comment by akien-mga** [comment]
Sadly I don't think I'll manage to get a certificate before the 3.0 release in January, so this will have to wait for a future release.. It's impressive how convoluted and badly documented this process is for FOSS projects.

**Comment by donkeybonks** [comment]
Isn't it just a case of paying ~$100 yearly ? Surely the Godot project can source that from Patreon

**Comment by akien-mga** [comment]
It's not just "paying", otherwise any cracker could get a certificate for their virus. You need to verify your identity as a legal person, send a copy of your ID card to a CA, receive a USB stick that can be used to generate a certificate, and then you can start thinking about integrating that certificate into your buildsystem so that you binaries actually get signed. That's not something I can do on my free time in two weeks, so it will have to wait.

**Comment by nicholatian** [comment]
It’s been 9 months since the last response, so what’s the status of the bug? Are there still plans to have the executables signed, or is that no longer on the roadmap?

**Comment by akien-mga** [comment]
That's still a work in progress, bureaucracy takes time but we should have it working for 3.1-stable.

**Comment by akien-mga** [comment]
As of Godot 3.1 beta 6, Windows binaries (both editor and templates) are signed using @hpvb's company certificate (as approved by the Godot leadership): *Prehensile Tales B.V.*

macOS builds will soon be signed too.

**Comment by akien-mga** [comment]
> As of Godot 3.1 beta 6, Windows binaries (both editor and templates) are signed using @hpvb's company certificate (as approved by the Godot leadership): _Prehensile Tales B.V._

Before someone asks: the reason why we're using a certificate from @hpvb's company and no one from a "Godot company" is because there is no Godot company :)
It could be clearer for end users if we had a certificate attributed to Software Freedom Conservancy, our legal sponsor, but discussions on that topic are not progressing so far so we have to use our own solution.
Neither Juan nor I wish to use a certificate attributed to us personally, this has to be non-natural person (company or organization).

**Comment by justinluk** [comment]
Is there a way I can sign my own exported games using my own company? It seems like people should be responsible for signing their own games instead of relying on @hpvb's company.

I've done signing with other game engines and frameworks but I'm not sure how you'd go about doing this with Godot.

**Comment by nicholatian** [comment]
I don't believe exported games have anything to do with this. While I don't know what utilities Godot provides for signing exported programs (if any), I'm pretty sure that's still in your court to do as a developer.

**Comment by donkeybonks** [comment]
This issue is for Godot itself.

**Comment by jamie-pate** [comment]
For Catalina this situation just got more desperate, It seems like Gatekeeper is now _removing_ +x permissions after extracting the zip!

https://appleinsider.com/articles/19/06/03/apples-macos-catalina-is-first-to-require-app-notarization-by-default

**Comment by tavurth** [comment]
I'm now getting this more daunting message.

Example image:
![example image](https://user-images.githubusercontent.com/100964/77408308-a31ddf80-6ddf-11ea-9419-7cb70f791a23.png)

<img width="272" alt="Screenshot 2020-03-24 at 14 57 12" src="https://user-images.githubusercontent.com/100964/77408384-bf218100-6ddf-11ea-80cd-ee160e05e5da.png">

**Comment by akien-mga** [comment]
To clarify, while we could sign the macOS binaries relatively easily now, macOS Catalina's new requirements that signed binaries should also be notarized (i.e. every single build should be sent to Apple so that they review it) is a pain that we don't plan to cope with for the time being.

Many developers of cross-platform applications use the same approach and hopefully Apple will one day figure out that their developer-adverse policies do more harm than good for their customers.

For Godot users, beyond the hoops you have to jump through to use the editor itself, it's your own responsibility to sign and notarize your own exported app bundles - if you wish to put up with Apple's requirements for the sake of your own customers.

**Comment by toddhd** [comment]
Figured I'd mention that I came here with the exact same problem. If enough people ask for it, you never know. Just FYI, the "right-click and select open" fix no longer works in the latest version of the OS. I do use Unity but thought that Godot looks interesting.

**Comment by Calinou** [comment]
Can this be worked around by installing Godot using Homebrew?

```text
brew cask install godot
```

**Comment by toddhd** [comment]
> Can this be worked around by installing Godot using Homebrew?
> 
> ```shell
> brew cask install godot
> ```
> 
> If so, we should make this more prominent on the Download page.

No, makes no difference. The problem isn't with the installation, that works just fine, the problem is that it isn't signed, and Mac isn't happy with that.

**Comment by jamie-pate** [comment]
Not just signed, signed and **notarized**.

**Comment by donkeybonks** [comment]
It can't be *that* difficult, because all the other open source apps have signed mac binaries?

**Comment by Calinou** [comment]
@donkeybonks Keep in mind the Steam version should work out of the box in the foreseeable future.

**Comment by b-hayes** [comment]
Still having this issue. Keep giving up and coming back again see if I can get it to run. So far month has gone by since I wanted to try Godot and this is the barrier for entry.

**Comment by tavurth** [comment]
> Still having this issue. Keep giving up and coming back again see if I can get it to run. So far month has gone by since I wanted to try Godot and this is the barrier for entry.

Can you right click on the Godot application, and then click open?
(Or control + click -> open, if you have no right click)

**Comment by TomWor** [comment]
Is the Steam Version notarized by Valve or why does that work?

Also, I know it the notarization thing with Apple is appaling and a PITA, but can't you take some of the donation money to just buy an Apple Developer license? Otherwise, just dropping MacOS support officially would be the cleaner cut than just having Godot users hang in limbo IMO.

**Comment by Calinou** [comment]
> Is the Steam Version notarized by Valve or why does that work?

It works because Steam got a free pass for distributing unsigned binaries somehow :shrug: 

It's the same on Windows.

**Comment by TomWor** [comment]
> It works because Steam got a free pass for distributing unsigned binaries somehow 🤷
> It's the same on Windows.

That does not seem to be true (anymore):
https://www.reddit.com/r/gamedev/comments/di61ms/have_a_mac_game_on_steam_heres_a_guide_to_signing/

Can someone confirm wether Steam Godot works on Catalina?
I'm still on Mojave, for obvious reasons...

> > Otherwise, just dropping MacOS support officially would be the cleaner cut than just having Godot users hang in limbo IMO.
> 
> Uh, that's quite a stretch…

I didn't know the Steam version could still work on MacOS without notarizing, I guess then this version should be referred to from the downloads page.
If even that way doesn't work anymore, over time, the complaints about Godot not working will skyrocket with Catalina user adoption. Therefore I think it would be better to have clear statement being made on the downloads page about that there is no way to use Godot on the Mac with Catalina or later MacOS versions - instead of dangling a carrot in peoples face it might be coming soon.
I think the Godot release team are doing a fantastic job btw. - I'm just proposing this because we could really close the case on this and save some people the trouble of figuring it out via this Github issue.

**Comment by Calinou** [comment]
> Therefore I think it would be better to have clear statement being made on the downloads page about that there is no way to use Godot on the Mac with Catalina or later MacOS versions - instead of dangling a carrot in peoples face it might be coming soon.

Aren't there more involved hacks to bypass this? We should probably document them instead.

**Comment by akien-mga** [comment]
> Therefore I think it would be better to have clear statement being made on the downloads page about that there is no way to use Godot on the Mac with Catalina or later MacOS versions - instead of dangling a carrot in peoples face it might be coming soon.

Well there is a way to use Godot on Catalina, just add an exception to let macOS run it.

See last section on https://support.apple.com/en-us/HT202491

> In macOS Catalina and macOS Mojave, when an app fails to install because it hasn’t been notarized or is from an unidentified developer, it will appear in System Preferences > Security & Privacy, under the General tab. Click Open Anyway to confirm your intent to open or install the app.

**Comment by tavurth** [comment]
> Can someone confirm wether Steam Godot works on Catalina?
@TomWor 

I'm using Godot on Catalina, I had some troubles while opening it but:
`Ctrl + right click` opened it fine.

After that it runs everytime without the warning as usual.

If others have difficulty, try going into:
- `System preferences --> Security and privacy`

There should be a small box saying: "Godot application was untrusted", 
click the orange lock button on the bottom left and then you should be able to allow Godot.

**Comment by jamie-pate** [comment]
Part of the problem is that gatekeeper will prevent the executable from having the +x bit when you extract it from an archive. Not sure if this is affecting the Godot download, but you have to go into the extracted .app and `chmod +x <binary>` before the system will even let you right click to run

**Comment by donkeybonks** [comment]
Also, if you can sign the app then the barrier to entry for distributing it on the App Store is suddenly a lot lower.

**Comment by b-hayes** [comment]
> > Still having this issue. Keep giving up and coming back again see if I can get it to run. So far month has gone by since I wanted to try Godot and this is the barrier for entry.
> 
> Can you right click on the Godot application, and then click open?
> (Or control + click -> open, if you have no right click)

Nope, the same dialogue appears nothing different from just double-clicking it. Move to bin is the only option.

**Comment by jamie-pate** [comment]
> you **also** have to go into the extracted .app and `chmod +x <binary>` before the system will even let you right click to run

**Comment by tommywalkie** [comment]
Adding this [Defold forum post link](https://forum.defold.com/t/macos-app-store-signing-notarization/63512/8) for reference, which provides a screenshot some insights from a Steam admin about this subject [in a Steamworks Steam group post](https://steamcommunity.com/groups/steamworks/discussions/0/1629665809935285504/), but the group apparently exceeded member limit so I can't check it by myself.
![mikela's post](https://forum.defold.com/uploads/default/original/3X/b/1/b18d6112089daedd79599ada62d8aac5fdea0b57.png)

**Comment by bruvzg** [comment]
Apples Gatekeeper is not checking signature of the user mode apps without `com.apple.quarantine` extended file attribute, most browsers and archive extractors are setting it for all downloads, Steam do not. Also, you can unset it using `xattr -r -d com.apple.quarantine AppName.app` command.

**Comment by kthornsbury** [comment]
> Apples Gatekeeper is not checking signature of the user mode apps without `com.apple.quarantine` extended file attribute, most browsers and archive extractors are setting it for all downloads, Steam do not. Also, you can unset it using `xattr -r -d com.apple.quarantine AppName.app` command.

This solved my problem with nothing else would. Thank you so much!

**Comment by shayneoneill** [comment]
The Notarized stuff might well end up being the thing that gets apple zapped for anti-competitive behavior, if they extend it to the mac as already regulators are sniffing about asking "What happens if someone wants to use a non-apple app store?". 

Although I'm *very* concerned they may well just do that for these new ARM based macs.

**Comment by karismatic-megafauna** [comment]
Wow, sorry @akien-mga for this nightmare Apple has put you through. What ridiculous policies and a terrible experience for developers.

The best way to get around this issue for me was what was posted by @kthornsbury ->
`xattr -r -d com.apple.quarantine /Applications/Godot.app`

If you are having similar issues, give this a shot!

**Comment by tavurth** [comment]
I have this issue every time I re-download the app, however as a game developer I've not found it to be much trouble to bypass on OS Catalina:

Right click -> open (first time it'll complain that it's not signed)
Right click -> open (second time gives option to open)

Seems like Apple makes this as difficult as possible, and I understand Godot's perspective.

if others are still having trouble with this, try downloading [Godot from Steam](https://store.steampowered.com/app/404790/Godot_Engine/)!

**Comment by Calinou** [comment]
I made a website about disabling macOS Gatekeeper: https://disable-gatekeeper.github.io/

**Comment by bruvzg** [comment]
On macOS Big Sur running on ARM all executable must be signed or won't run at all, ad hoc signature is sufficient (as long as Gatekeeper is disabled/bypassed as described in the previous comment).

https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-universal-apps-beta-release-notes

**Comment by bruvzg** [comment]
Starting from Godot 3.3, macOS editor binaries are signed and notarized.

**Comment by kvanbere** [comment]
Well done guys.

**Comment by kthornsbury** [comment]
I appreciate you all! Thanks!
