### ISSUE TITLE
A modified scene deletes all changes on scene load or GoDotEngine exit. Also "Autosave Interval Seconds" is not working.

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#1200]
When you modify a scene, then press the play button, it will automatically save the scene.
But when you modify a scene, then load a different scene it will delete all your changes without any popup.
Also when you modify a scene, then close out of GoDotEngine, it will delete all your changes without any popup.

Look at "Settings" > "Editor Settings" > "Text Editor" > "Autosave Interval Seconds"
This feature doesn't even work. My scripts nor my scene is auto saving.

Please display a popup to save on exit and scene changes for both the scene and any modified scripts. 
Also please add an option in "Settings" > "Editor Settings" to Auto-save instead of prompting (This should be automatically checked and grayed out if "Autosave Interval Seconds" is checked because if you have it set to auto save every X seconds you also want it to autosave before you exit.)

**Comment by mamarilmanson** [comment]
:+1:

**Comment by akien-mga** [comment]
I believe this issue is no longer valid in the current master branch, the editor asks to save changes when trying to close the editor with unsaved changes, and changing scenes in the new multiscene editor does not lose changes.

For the autosave question, please open a new ticket if it's still relevant, it's hard to track several issues in the same ticket.
