### ISSUE TITLE
Ability to set a Max Speed for Vehicle Bodies

### ISSUE THREAD

**Issue by zicklag** [godotengine/godot#12013]
**Ubuntu 16.04, Godot 2.1.3:**
 
**Issue description:**

It would be nice if there was the ability to set max speed for VehicleBody's. Even in a *very* basic car or racing game it wouldn't make a whole lot of sense to have a vehicle that could go faster and faster unlimitedly. I was thinking of manually implementing a top speed by setting the linear velocity every time that it went above the max speed, but vehicle bodies don't have that ability either. #10663 already addresses that issue.

**Comment by raymoo** [comment]
Could also add a air friction force

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by Zireael07** [comment]
I believe it's still relevant, VehicleBody lacks any sort of a max speed cap and/or air friction. Max speed cap can be implemented manually fairly easily, but air friction/drag not so much.

**Comment by akien-mga** [comment]
Might be something of interest for @BastiaanOlij :)

**Comment by BastiaanOlij** [comment]
My gut feeling is that you would simulate this by setting linear damp but you would have to increase the value the faster the vehicle is moving. At some point engine force and linear damp will end up cancelling each other out.

In my vehicle simulation for max speed I've gone in a totally different direction because I implemented engine RPM and am setting engine force based on a curve derived from RPM, once max RPM is reached I simulate a revlimiter. Hopefully will get there at some point with my tutorials :)

**Comment by creikey** [comment]
I think it would be useful to have this in every RigidBody to make it quick and easy to implement terminal velocity, even though it's physically incorrect. Maybe there is another more physically accurate method that varies linear dampening via current velocity such as an "air resistance" property.

**Comment by creikey** [comment]
What would be better is if a property was exposed as `terminal_velocity` then the engine calculates the air resistance constant via:
```gdscript
var k = (mass*state.total_gravity.length())/terminal_velocity
add_central_force(-state.linear_velocity*k)
```

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
