### ISSUE TITLE
Some "Quality of Life" enhancements

### ISSUE THREAD

**Issue by rishavs** [godotengine/godot#1205]
I know these will be low priority but I'd really like some of these to be picked up.

* dont autosave on exit
* give save dialog on exit if the edits weren't saved
* drag and drop for nodes in the scene list. allows for quick ordering or changing parent-child relationships
* allow option for auto-update. its hard to keep track of binaries for fast moving codebases. we can have it switched off by default for people who dont prefer auto updates for their frameworks.
* hide the Godot console on windows (via settings. or allow to redirect stream to log file. I am sure we dont want to disable it as it helps debug issues in the editor). it is just irritating to see a console in the background which i never need to look at.
* ability to detach the output panel from the main editor (or direct output stream to a console)
* allow context menu use/native os commands for resources/file system items (eg. i can right click a png file in the resources list and get the normal windows context menu. this allows me to quickly edit it in an image editor)
* while editing values, the value should be preserved when the focus is removed from the field. currently the edited value is lost unless user presses enter.
* allow selecting multiple nodes in the list for drag and drop and reassigning relations. currentl only ctrl + select is supported. shift + select should also be supported. mouse drag and select should also be supported. 
* option to hide "Process being debugged exited". this shouldnt be shown evertime i close the game view. else we can have this message shown in the output panel rather than in an alert.
* ability to open the project manager from inside the editor
* when trying to run a scene without having saved it, instead of the popup saying that the scene wasn't saved, just open the save scene dialog.
*  Adding a scene (*.scn) directly as a tilemap without having to export it as a resource first.

There are a few more, but i'll add them later on.

**Comment by mamarilmanson** [comment]
+1

**Comment by Kjarrigan** [comment]
+1 for Drag&Drop nodes
A few days ago I did my first steps in godot (it's awesome btw) and tried to Drag&Drop a node I created with the wrong parents selected. Had to look in the Wiki how to change parent to get it done.

**Comment by bojidar-bg** [comment]
+2 for all

**Comment by Ace-Dragon** [comment]
Agree with everything related to saving and the "Process being debugged" dialogue. Last I read one of the focuses for version 1.1 is usability improvements, I think giving the user full control over autosave and the like would fit well here.

Also, may I add, instead of the engine giving the "Process being debugged exited" dialogue whenever there's an invalid node parenting setup. The engine should instead have a dialogue saying "invalid node setup, exiting" and a visual showing the cause within the node tree (or better yet, if the engine can auto-detect invalid setups, it can show the user while he's working on it).

**Comment by SolarLune** [comment]
+1 for a lot of these. I don't agree, though, with diabling the Godot console. I think it can be useful, so just making an option to disable it should be useful.

**Comment by rdirksen** [comment]
+1 while editing values, the value should be preserved when the focus is removed from the field. currently the edited value is lost unless user presses enter.

**Comment by shackra** [comment]
> hide the Godot console on windows (via settings. or allow to redirect stream to log file. I am sure we dont want to disable it as it helps debug issues in the editor). it is just irritating to see a console in the background which i never need to look at.

I've been surprised by the fact that when a GDScript error occurs on my projects, the error is printed to such console instead of the Godot's internal console. On GNU/Linux, we don't see such console unless you ran Godot from a terminal, and that's problematic.

**Comment by reduz** [comment]
That will change when more work is put into the debugger

**Comment by SolarLune** [comment]
A nice QOL enhancement would be not to discard any attempt to add a node without one currently selected to parent it to. If a node isn't selected and you choose to add a new node, it should automatically parent to the base node in the scene (if there is one). Otherwise, I imagine it should become the base node in the scene (which is how it works now, I think).

**Comment by not-surt** [comment]
Somewhat related: add node from scene tree context menu.
Need to add a context menu first, of course.
New node gets added to the node that the context menu was opened on.

**Comment by rishavs** [comment]
added one more;
Adding a scene (*.scn) directly as a tilemap without having to export it as a resource first.

Though I am pretty sure this one is planned.

**Comment by CombustibleLemonade** [comment]
"option to hide "Process being debugged exited". this shouldnt be shown evertime i close the game view. else we can have this message shown in the output panel rather than in an alert."
PSA: if you press f8 to close the game, you won't get that popup.

Also, perhaps you could add this one:
When I hover over an array or a dictionary with the cursor in a script while debugging, It shows the content in the tooltips. However, the tooltips often go off the screen, and it doesn't show in the variable list in the debugger. Create some convenient way to view the contents arrays and dictionaries while debugging.

**Comment by kubecz3k** [comment]
We are in the process of sorting and cleaning github issues. I'm really sorry but this issue is to general and don't really help in discussion or development. Please open smaller well subject oriented issues for each idea/problem (but also please don't duplicate already existing bugs).
