### ISSUE TITLE
Mono - problem with signal methods  auto generated by godot 

### ISSUE THREAD

**Issue by Tommel1234** [godotengine/godot#12120]
With a fresh Godot 3 build with mono, there is a little problem when auto generated method by connecting a signal to a C# scripts with Godot.

It happen when I connect an area2D with the signal area_entered with the interface.. The generate method don't works
It generate a method like:
private void _on_area_enter(object area:Object){
}
Sorry for my bad English! If needed, I can share my project files!

**Comment by neikeq** [comment]
The PR above fixes this. However, keep in mind this feature is still incomplete. Right now, it will only append the method to the end of the file, and it does not work with external editors (both Godot API limitations).

**Comment by Tommel1234** [comment]
Good ! that is what i was thinking. Good job by the way, I have tested a lot this past few days and it works very well. Except when I have tried to create a built-in C# scripts and that can't find a way to use "yield" like in GDscript, everythings work fine !

**Comment by kryztoval** [comment]
As @neikeq mentioned, it will add the method outside of the class when it needs to be inside the class

But there is a secondary issue, there will be a warning saying that the connected method is missing because it is expecting it outside the class as well.

Should this be created in a new issue? The autogenerated signature is infact fixed now, but those two things are still present on 4.2.1 Mono Windows edition.
