### ISSUE TITLE
Bug with remaping recources

### ISSUE THREAD

**Issue by DmitriySalnikov** [godotengine/godot#12127]
sorry for bad english :-)
**Operating system or device, Godot version:**
Windows 10, Godot 3.0.

**Issue description:**
If remapped resource have remap to your system language then you can't change language in game.
TranslationServer.set_locale([LANG]) affects only the translation of the text.
But if you create remapped resource based on your system language everything will be fine.

**Steps to reproduce:**
Download the sample and open it. If your system language is among the supported by the example, then it will be impossible to change resources depending on the language.
Supported languages: English, Spanish, Japanese, Russian.

<details> 
<summary><b>Example</b></summary>
remap for flag_uk.png:
<a href="https://user-images.githubusercontent.com/7782218/31587945-61f95336-b1f3-11e7-8053-4cbaf8b03bc3.png" target="_blank"><img src="https://user-images.githubusercontent.com/7782218/31587945-61f95336-b1f3-11e7-8053-4cbaf8b03bc3.png" alt="first pic" style="max-width:100%;"></a></br>
and for flag_def.png:
<a href="https://user-images.githubusercontent.com/7782218/31587949-66290f5a-b1f3-11e7-8190-29617335025c.png" target="_blank"><img src="https://user-images.githubusercontent.com/7782218/31587949-66290f5a-b1f3-11e7-8190-29617335025c.png" alt="second pic" style="max-width:100%;"></a></br>
this happens if remap includes system language:
<a href="https://user-images.githubusercontent.com/7782218/31587979-174f378c-b1f4-11e7-9723-e81bf660fc84.gif" target="_blank"><img src="https://user-images.githubusercontent.com/7782218/31587979-174f378c-b1f4-11e7-9723-e81bf660fc84.gif" alt="first gif" style="max-width:100%;"></a></br>
this happens if remap based on system language:
<a href="https://user-images.githubusercontent.com/7782218/31587984-1ff30594-b1f4-11e7-8093-3ccca1f0ebb4.gif" target="_blank"><img src="https://user-images.githubusercontent.com/7782218/31587984-1ff30594-b1f4-11e7-8093-3ccca1f0ebb4.gif" alt="second gif" style="max-width:100%;"></a></br>
</details></br>

**Link to minimal example project:**
<a href="https://github.com/godotengine/godot/files/1385718/translation.zip">translation.zip</a>

**Comment by mrcdk** [comment]
I think I found the issue but I don't know how to fix it. The issue comes from here:
https://github.com/godotengine/godot/blob/master/core/resource.cpp#L76-L77

When the resource gets loaded it tries to cache the path into `path_cache` which will return when calling `get_path()`. I'm not yet sure why but when dealing with the translation resources remapping it somehow triggers that error the first time it loads the scene. At that point (when the error is triggered), the `path_cache` is an empty string and the `ERR_FAIL_COND` will return without setting the correct path into `path_cache`

So, everytime it tries to reload the asset it will try to confirm that the path (`path_cache`) is a correct resource path (which it's not in our case, it's an empty string):
https://github.com/godotengine/godot/blob/master/core/resource.cpp#L123

And will never be able to reload the asset with the correct resource.

Commenting out that `ERR_FAIL_COND` will solve this issue but I have no idea what the implications are if we do that.

Pinging @reduz because he'll know what to do.

**Comment by mrcdk** [comment]
This got fixed at some point. It's working on Godot 3.0 rc1.

**Comment by akien-mga** [comment]
Thanks for checking, closing then.
