### ISSUE TITLE
NumPad number keys act as numbers and arrows simultaneously. [macOS]

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#12154]
**Operating system or device, Godot version:**
macOS 10.13, Godot 3 (latest master)

**Issue description:**
NumPad number keys act as numbers and arrows simultaneously. macOS specific, can't reproduce on Windows and Linux.

![output_quick](https://user-images.githubusercontent.com/7645683/31620253-6e57905a-b29f-11e7-8938-5004faab9020.gif)

**Steps to reproduce:**
Type 1024 on NumPad into any input control (will input 1042 instead).

**Comment by reduz** [comment]
@BastiaanOlij would you like to give a check to this?

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.
