### ISSUE TITLE
Vector.rotated() rotates in different direction for godot2 vs godot3

### ISSUE THREAD

**Issue by BeayemX** [godotengine/godot#12163]
Given this code:
```
var v1 = Vector2(1, 0)
var v2 = v1.rotated(PI * 0.5)
print("v2", v2)
```
the result for 2.1.4 is `v2(-0, -1)`
and the result for 3.0 is `v2(-0, 1)`

Is this a bug or did something change internally?

**Comment by akien-mga** [comment]
There were quite a few changes to the math conventions in 3.0 to make them more consistent, so this one is expected.

Since the 2D space is a left-handed system (X+ towards the right, Y+ towards the bottom), a positive rotation (trigonometric position direction) would be from X+ towards Y+, so it's expected that (1, 0) rotated by PI/2 would land on (0, 1). In 2.1 it was wrong, as the rotation was in the "classic" direction we know from our math classes using right-handed systems.
