### ISSUE TITLE
Compile godot for windows error

### ISSUE THREAD

**Issue by Cyber-host** [godotengine/godot#12187]
Windows 10
Install Visual Studio 2017 community
Python 3.6.2
Scons  v3.0.0.rel_3.0.0:4395:8972f6a2f699

Try compile (Cross Tools Command Prompt for VS 2017):
```
scons p=windows
```

Got error:
```
c:\godot\drivers\png/image_loader_png.h(35): fatal error C1083: Cannot open include file: 'png.h': No such file or directory
```

**Comment by akien-mga** [comment]
What's the full compilation command that should be printed before that error, with the include paths?

**Comment by Cyber-host** [comment]
@akien-mga Just clone godot master and run `scons p=windows` in the root folder

```
C:\godot>scons p=windows
scons: Reading SConscript files ...
Detected MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
cdir is: C:\godot
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform\windows\godot_win.cpp
godot_win.cpp
c:\godot\core\list.h(226): warning C4291: 'void *operator new(::size_t,void *(__cdecl *)(::size_t))': no matching operator delete found; memory will not be freed if initialization throws an exception
```
...
...
...
```
[Initial build] Compiling ==> drivers\register_driver_types.cpp
register_driver_types.cpp
c:\godot\drivers\png/image_loader_png.h(35): fatal error C1083: Cannot open include file: 'png.h': No such file or directory
scons: *** [drivers\register_driver_types.windows.tools.32.obj] Error 2
scons: building terminated because of errors.
```

**Comment by akien-mga** [comment]
Can you build with `scons p=windows verbose=yes`?

**Comment by rcurtis** [comment]
Experiencing the same issue today on Windows 10.

`1>editor_icons.gen.cpp
1>editor\editor_icons.gen.cpp(1): fatal error C1083: Cannot open include file: 'editor_icons.h': No such file or directory
1>scons: *** [editor\editor_icons.gen.windows.tools.32.obj] Error 2
1>scons: building terminated because of errors.`

**Comment by rcurtis** [comment]
output from verbose=yes

`[ 60%] cl /Foeditor\editor_icons.gen.windows.tools.32.obj /c editor\editor_icons.gen.cpp /TP /TP /nologo /Z7 /DDEBUG_ENABLED /DDEBUG_MEMORY_ENABLED /DD3D_DEBUG_INFO /Od /EHsc /MT /Gd /GR /nologo "/IC:\Program Files (x86)\Windows Kits\10\/Include" /DWINDOWS_ENABLED /DOPENGL_ENABLED /DRTAUDIO_ENABLED /DWASAPI_ENABLED /DTYPED_METHOD_BIND /DWIN32 /DWINVER=0x0601 /D_WIN32_WINNT=0x0601 "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "/IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\ucrt" "/IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\shared" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\um" "/IC:\Program Files (x86)\Windows Kits\10\include\10.0.15063.0\winrt" /I /w -DFT2_BUILD_LIBRARY -DZLIB_DEBUG -DFREETYPE_ENABLED -DRECAST_ENABLED -DSVG_ENABLED -DDEBUG_MEMORY_ALLOC -DSCI_NAMESPACE /DMSVC /GR -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DXML_ENABLED -DGLAD_ENABLED -DGLES_OVER_GL /Icore /Icore\math /Ieditor /Idrivers /I. /Iplatform\windows /Ithirdparty\zstd /Ithirdparty\zstd\common /Ithirdparty\zlib /Ithirdparty\rtaudio /Ithirdparty\glad /Ithirdparty\freetype /Ithirdparty\freetype\include /Ithirdparty\libpng /Ithirdparty\recastnavigation\Recast /Ithirdparty\recastnavigation\Recast\Include /Ithirdparty\nanosvg
editor_icons.gen.cpp
editor\editor_icons.gen.cpp(1): fatal error C1083: Cannot open include file: 'editor_icons.h': No such file or directory
scons: *** [editor\editor_icons.gen.windows.tools.32.obj] Error 2
scons: building terminated because of errors.`

**Comment by rcurtis** [comment]
It seems this has to do with a generated file that scons does not clean up after a build.  Now that I'm looking at build output, scons is just littering the entire repo with .gen files and obj files all over the place.  I would have expected scons to either use a /temp build directory or at least clean up after itself.

Anyway, to solve this issue, delete the editor_icons.gen.h and editor_icons.gen.cpp files.

**Comment by Cyber-host** [comment]
Works after reinstall python to 2.7.14

**Comment by akien-mga** [comment]
> Experiencing the same issue today on Windows 10.

That's unrelated.

**Comment by akien-mga** [comment]
> Works after reinstall python to 2.7.14

Great, closing then.
