### ISSUE TITLE
File Preview Image Corruption

### ISSUE THREAD

**Issue by BrainBlasted** [godotengine/godot#12220]
**Operating system**: Arch Linux
**GPU:** GTX 1050M
**Driver:** nvidia-dkms 387.12-2

**Issue description:**
Getting strange texture corruptions on the left file preview. On the *right, the preview seems just fine.
<br/> 
![Image Preview Corruptions](https://i.imgur.com/zHbhlcM.png)

**Comment by abaky** [comment]
happens on Win10 64bit also

**Comment by Noshyaar** [comment]
Can confirm. Probably something specific to that project because when I moved it to a blank project, it rendered correctly.

>On the left, the preview seems just fine.

You meant 'right'?

**Comment by BrainBlasted** [comment]
Ah, crap, always get those mixed up.

**Comment by abaky** [comment]
@Noshyaar I have a personal project with my own assets, and normal texture imported correctly and displayed correctly in the file preview, but somewhere down the line the preview turned to pixelated funky texture.

**Comment by reduz** [comment]
The yellow green is OK because the texture is RG, but it seems what breaks is the normal (RG Texture) decompression code. If anyone wants to give it a try, code is here: 

https://github.com/godotengine/godot/blob/master/modules/squish/image_compress_squish.cpp#L64

It seems fine to me, it may even be a Squish bug, or maybe the blue pixel is unassigned, I dont really know, but its worth checking.
