### ISSUE TITLE
Add MIDI playback support

### ISSUE THREAD

**Issue by ki4jgt** [godotengine/godot#12238]
Hey guys,

Got another feature request for you all:

I'd like to see MIDI support in the players. That would be awesome. They make the games sound retro and they take up a smaller file size. Not to mention, they can be composed with programs like Musescore. I think MIDI support would be a great addition to the gaming platform you guys already have.

Thanks again for this awesome tool.

**Comment by manokara** [comment]
The MIDI format by itself does not output sound, only notes, which are sent through a midi service that will play the appropriate instrument and note in a soundfont, which Windows provides by default, but other platforms don't (but it's configurable). 

With that in mind, as Godot is a cross-platform engine, MIDI support would not work the same on all platforms... But I dunno, maybe someone has a better idea that covers that situation. There used to be MOD files support in 2.1 at some point, but apparently it was removed?

**Comment by Zylann** [comment]
@manokara it doesn't need to be played by the OS though. MIDI is much more than that. Providing soundfont assets support would make the feature complete IMO.

**Comment by manokara** [comment]
Wouldn't bundling the soundfount increase the size of the game significantly? FluidR3 GM for example is 150MB, so if the game had six songs in high quality OGG it would be roughly 60MB total. Unless the game has a lot of songs, or the soundfont is just a selection of the used instruments.

**Comment by Zylann** [comment]
@manokara it all depends how you make the soundfont, they can be very small if sounds are cheap and tailored to your needs. I was making the comment because forcibly relying on the OS would be limited and unreliable if only one use case is considered.

**Comment by RichardEllicott** [comment]
it would be so cool if there was some facility for this (i don't care about soundfonts myself, just the midi)

it's also especially cool educationally, java had built in midi systems for this reason..... so i see that non-music people likely wonder why the hell people even want this stuff

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
