### ISSUE TITLE
Mono: a way to test the existence of a texture

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#12271]
(Background: All exported texture variables assigned through property editor are invalid #12200.)

I may be missing something in the existing API but right now, it doesn't look like we can test the existence of a `Texture`. In C++, we'd typically pass references and we'd just do `tex.is_valid()`. In Mono, a check `tex == null` doesn't work.

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by neikeq** [comment]
Oh, I missed this one. I think this was fixed by #12326. Now the `null` check should work.

However, there is still the possibility of the native instance being freed while the managed instance is still referenced. A `null` check won't work in those cases. This is similar to GDScript, where you would use `weakref`. In C#, although you can use `WeakRef`, it's recommended to use the `NativeInstance` property, which is set to `IntPtr.Zero` when the native instance is destroyed. Just like in GDScript, you don't need this for Reference derived types.

**Comment by tagcup** [comment]
Ah, great. I think it'd be nice to document this somewhere though
