### ISSUE TITLE
Editor 3D scene view: Fade out grid with distance

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#12324]
Currently, the grid used by the 3D scene view becomes quite messy in the distance due to perspective.
Other engines fade out the grid with increasing distance.

Comparison:
https://imgur.com/a/j9pzE

Additionally, the Godot lines used for the Grid and X, Y, Z lines tend to alias way more.

**Comment by Zylann** [comment]
I used to work on a prototype for Godot but never took the time to do a PR https://www.youtube.com/watch?v=6jHafwiaFAE&feature=youtu.be

This uses a shader that fades the grid using pixel depth, so it both handles fading in the distance + infinite grids

**Comment by mhilbrunner** [comment]
Very shiny. I'd love to have that in Godot :)

**Comment by mhilbrunner** [comment]
Update: Because of transparency issues (Z glitches) fading out with distance as in Zylann's prototype above is currently not possible.

Maybe at least a hard cutoff after some distance, maybe based on a circle/oval mask centered on the camera position would be better than the current situation?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
