### ISSUE TITLE
translation removes newlines

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#1232]
I've got a csv file with translations in it.  When I copy the text from the file into a label's text field, the newlines work correctly.  When I put the translation's key into the field and let it grab the translation, the newlines are missing.

**Comment by jfbilodeau** [comment]
Same deal here. Using escapes such as \n or \t do not work, and carriage returns in the CSV are removed. How can we include carriage returns in translations?

**Comment by akien-mga** [comment]
Likely a CSV parsing issue. I *think* it might be relatively easy to fix so labelling as a junior job so far, of course I stand to be corrected :-)

**Comment by Necco-Z** [comment]
I'm still having this problem with both version 3.0.6 and 3.1 beta 2. I've built a simple scene with four `Label` objects:

1. Entering `\n` in text attribute at the inspector to separate lines;
2. Entering a translation key at the inspector fetching a translation with `\n` to separate lines;
3. Using a script to call `tr(KEY)` to fill the text with the same translation;
4. Assigning the same text of the translation to the last label through script.

The first one should be the only one not working (since you can use Enter when typing from the inspector), but what actually happens is that label 2 and 3 can't handle the line break as well. The `\n` is only read correctly when I write it directly in the script.

[This is a zip file of the project shown on the pics.](https://github.com/godotengine/godot/files/2799743/Label.test.zip) 
First picture is of the editor, second picture is of the scene running:
![clipboard02](https://user-images.githubusercontent.com/41708431/51796181-30f63e80-21cc-11e9-988f-8f69831c1b1c.png)
![clipboard04](https://user-images.githubusercontent.com/41708431/51796182-30f63e80-21cc-11e9-830b-21ac9e4c991f.png)
