### ISSUE TITLE
Non-constrained mode for gridmap edition

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#12338]
I would like to propose an alternative edition mode for GridMap:

Currently, editing a gridmap requires to work floor by floor, aligned to a given axis, which is equivalent to tilemap edition inside a plane. It's pretty generic, but I find this design to be impractical depending on the type of map/game.

The mode I'm proposing would allow to place or remove blocks in an intuitive way, by placing them directly on top of what the mouse points at, much more similar to how Minecraft, Robocraft or MagickaVoxel works.

Example in Robocraft:
https://www.youtube.com/watch?v=NJtRJz9bbvk

Some rough work-in-progress I've done in Godot to try it out:
https://www.youtube.com/watch?v=UPadosT1xok

I only use the mouse in both videos.

WDYT?

**Comment by ScottMakesGames** [comment]
I think the current gridmap workflow is slow to use because of this. Your solution would be a fantastic addition to the workflow.

**Comment by groud** [comment]
A great idea!

**Comment by adtofaust** [comment]
Hi @Zylann , any progress with this feature? It would be great to see it in final 3.0.

**Comment by Zylann** [comment]
@adtofaust I have a branch hanging on my fork, but didn't work on it recently. I could do a WIP PR for people to try this out and see which advantages/shortcomings it introduces

**Comment by adtofaust** [comment]
@Zylann if you decide to do so, I can test it in the upcoming weekend

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
