### ISSUE TITLE
Directory.get_current_dir behaves differently in editor and exported games (res:/// paths with three slashes)

### ISSUE THREAD

**Issue by magyar123** [godotengine/godot#12459]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 Godot 2.1.4 stable

**Issue description:**
I would like to open all .txt files in a directory.
I use the Directory class to find them and it lists all files perfectly. But when I try to open them with the file class, it says it can't find the file. Neither open or file_exeists can see them. I added the *.txt filter and even selected export all files in the project folder in the export settings.
All of this works well in the editor.

**Steps to reproduce:**
Open the linked project
Run with editor
On the output it will say "File opened succesfully: True" 
Run the exe file in the zip ( its the same project just exported )
On the output it will say "File opened succesfully: False"

**Link to minimal example project:**
[file_error.zip](https://github.com/godotengine/godot/files/1424279/file_error.zip)

**Comment by magyar123** [comment]
OOOOOOOOOOOh never mind i got it.
Its a bug in the directory class.
The `get_current_dir` function returns the path like this `res:///folder/folder` with three "/"

**Comment by marcelofg55** [comment]
It's not a bug, it's "res://" + "/" which is the root path. It's unix style path.

**Comment by magyar123** [comment]
OK, but the File.open and File.file_exists functions can't deal with it.
So it's still bug but i an other place

**Comment by magyar123** [comment]
Anyway it's pretty strange that file paths behave so inconsistently.
Btw I also found that ImageTexture.load can't handle this unix style neither

**Comment by Ranoller** [comment]
This issue is related with this: 
https://godotengine.org/qa/18047/how-to-get-an-internal-resource-path-in-exported-binary

I had same problem with a module: 
https://github.com/kestrelm/Creature_Godot/issues/5

Problem is that godot binary search in the same directory that it is. This is "res://" for resource searching for godot. If you copy your "test" directory in the same place of your exported binary and execute you will understand that.

**Comment by akien-mga** [comment]
I could confirm the issue on Linux with 3.0.2-stable, and I assume it's still the same in the master branch.

To be clearer, this issue is not about `File.file_access` not finding *resources* in exported games because they were remapped and `FileAccess` does not take remappings into account (that would be #18740).

This issue is about `Directory.get_current_dir()` potentially returning a path starting with `res:///` (three slashes) instead of `res://`, which is then badly parsed and results in not being able to go through the directory.

**Comment by Zireael07** [comment]
Oh, my bad then. I don't think I saw three slashes, I believe I saw two, but I can double-check.

**Comment by reduz** [comment]
This is not a bug, the file is simply not exported because it's not a resource.
I added a small fix to get_current_dir to avoid the three slashes though in da1f53c8d
