### ISSUE TITLE
Fog appears to add color to distance rather than fade distance to color 

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#12454]
Based on my experience in other video games, fog usually fades distance to a specific color. Used to hide  far away geometry so you don't have to draw it. 

But in Godot fog simply adds color on top of the image  but the distance geometry remains visible 

In fact to get what I want I need to set ambient light to 0

But what if I want to use both ambient light say moon light and fade the distance to black? Is not possible!

Also oddly some colors work better than others. 

![a2](https://user-images.githubusercontent.com/6987027/32132625-fdc2e58e-bb94-11e7-8fbe-dd0928e22fea.gif)
![a](https://user-images.githubusercontent.com/6987027/32132626-ff9d8b20-bb94-11e7-8f78-2a43793f6fe0.gif)

I don't know if this is by design or not but can it be made to also work this way optionally? Just wondering. Thank you for your consideration. 

User mago from Discord investigated and fount the issue might be 
emission = emission * rev_amount + fog_color * fog_amount;
https://github.com/godotengine/godot/blob/master/drivers/gles3/shaders/scene.glsl
Fog appears to be additive rather than multiplicative.

**Comment by Calinou** [comment]
> Used to hide far away geometry so you don't have to draw it.

Fog doesn't work like this in modern games (you can, however, set a far clip plane yourself, provided the sky is an uniform color so that it "blends" with the fog).

**Comment by trollworkout** [comment]
But how do I make a smooth transition between normal image and distance with a clipped plane?

**Comment by Calinou** [comment]
> What can I use in Godot at the moment to get a smooth gradient transition between normal image and a color of my choosing in the distance?

You currently can't, since there's a bug in the fog shader, as you described.

**Comment by akien-mga** [comment]
Can this still be reproduced in the current master branch?

**Comment by trollworkout** [comment]
@akien-mga  is still present in rc2 i don't know about rc3 yet

**Comment by trollworkout** [comment]
RC3 has the same issue yes

**Comment by trollworkout** [comment]
red 
![image](https://user-images.githubusercontent.com/6987027/35342685-af02c458-00f6-11e8-9e72-3ad9422cfad4.png)
black
![image](https://user-images.githubusercontent.com/6987027/35342709-bdb57996-00f6-11e8-97a9-104dd3c51e94.png)

depth curve seems to affect the whole fog not just the transition

**Comment by DEF7** [comment]
@trollworkout The fog works perfectly fine. Your fog depth curve is too low (0.02, yikes) and you may need to reconsider your far clip plane. Looking at the shader the fog is *not* additively blended. The line you mentioned from the shader as evidence that it was:

> emission = emission * rev_amount + fog_color * fog_amount;

is preceeded by:

> float rev_amount = 1.0 - fog_amount;

which effectively recalculates 'emission' to be interpolated between it's existing value and the fog color, per on fog_amount, i.e. mix(emission, fog_color, fog_amount). You can rest assured that it's not just being blatantly added to the fragment color willy-nilly. You *can* have black fog that's neither additively nor multiplicatively added, but alpha blended.

Also, you may want to turn off transmission in your fog options (Transmit Enabled = off) which will reduce the opacity of the fog in order to produce the effect of light being able to carry through the fog more realistically.

Here's an example of having a blue ambient 'moonlight' and black fog, with a gray sky/background to show you where the geometry is, I added a directional light and an omnilight so you can see illuminated vs ambient and how the fog interacts with both:

![image](https://user-images.githubusercontent.com/11559157/38771688-546cb2c2-3fdc-11e8-9d83-bead23d1d445.png)

..here's the same scene with a black sky, so you can see the geometry is fading out into the background just as you would see in all the games that use fog to hide the far clip plane (with the ambient light color we wanted):

![image](https://user-images.githubusercontent.com/11559157/38771712-b9adb744-3fdc-11e8-8aec-ad63ee86e141.png)

..and here's with the depth curve turned down to make the fog thicker:

![image](https://user-images.githubusercontent.com/11559157/38771722-ed7956be-3fdc-11e8-82fe-762f31b5192c.png)

The far clip plane *does* affect the density of the fog, which is kinda silly. It should be decoupled from the clip plane entirely. I think having a near/far fog is much more intuitive, maybe not from a coding standpoint (if you want exponential fog) but not impossible by any means. A closer far clip plane produces a denser fog.

Admittedly there's perhaps an issue where the Depth Begin immediately transitions to a non-zero fog amount if the Depth Curve is < ~0.3, which perhaps could be looked at, but I don't consider it to be exactly breaking anything, because you can still create just about any exponential fog effect you want. I'd wager that the far clip plane affecting the fog is a much more important issue. Here's having the fog begin at 20 units away, and the depth curve turned down only to 0.1. There should still be a gradiation between no fog starting at 20 units and then an abrupt transition into fog, albeit a smooth one, but instead it just starts in at a pretty dense fog, resulting in a hard fog edge:

![image](https://user-images.githubusercontent.com/11559157/38771782-0ec80da0-3fde-11e8-92b6-26844d89f878.png)

I just avoid the issue altogether and typically use a Depth Begin of zero, because that's how fog works in reality (when you're actually in the fog), and then tweak the other settings to get the fog to accumulate into the distance how I want.

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
@DEF7 I think the problem is that the fog uses Camera "far" variable to compute the fog draw distance and you cannot independently tell the fog to draw from distance A (begin) to distance B (end) . There needs to be a `Depth End`  in addition to `Depth Begin` much how Height has `Height Min` and `Height Max` so fog settings remain independent of Camera and View port.
