### ISSUE TITLE
Fullscreen window does not toggle on the first click, if opened in fullscreen

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12465]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
2.1.4 and in 3.0 latest compiled
Windows 7, 64-bit

**Issue description:**
In the Godot examples ( `window_management` ), set fullscreen to true in project settings.

Now preview the scene and click on the fullscreen button. It stays fullscreen and doesn't toggle on the first click.
You have to click it 3 times for it to toggle. 

**Only happens when the game is opened in fullscreen mode.**

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
