### ISSUE TITLE
Text is missing from PopupMenu only on exported projects

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#12481]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
3.0, w7 64-bit, using October 28th's binaries  from: http://godot3builds.digitecnology.com/

 
**Steps to reproduce:**
Create a line edit node, then export the project. Right click it, the context menu (inherits popupmenu class) is missing the text for the options:
![image](https://user-images.githubusercontent.com/10387670/32143907-360c6b2a-bc6e-11e7-9b05-9b4cf00298fb.png)

It does work however when you preview the scene, but doesn't show on **exported projects only**

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
