### ISSUE TITLE
[DOCS] Nil constructors docs

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#12520]
The constructors for `Nil` show up in the docs, even though they seem to be inaccessible and do nothing (being void, not returning anything):

http://docs.godotengine.org/en/latest/classes/class_nil.html

Should those be removed somehow?

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by exts** [comment]
Yeah, I ran into this with RichTextLabel, was confused on what the `meta_clicked`

**Comment by neikeq** [comment]
@exts This is a problem in `EditorHelp`. `meta_clicked` is defined with `PROPERTY_USAGE_NIL_IS_VARIANT` in the first parameter, meaning it takes `Variant` (anything).
