### ISSUE TITLE
FileSystem dock can't open files

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12554]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/7a5594bdb79f0859ce67166b7fb6ed89098e5bcc

**Issue description:**

![https://i.imgur.com/LLGrNtx.gifv](https://i.imgur.com/LLGrNtx.gif)

I'm guessing this PR broke it https://github.com/godotengine/godot/pull/10261

**Steps to reproduce:**
1. Try to use the filesystem dock to open a file

**Comment by akien-mga** [comment]
Ping @Cradmon

**Comment by akien-mga** [comment]
Tested with a local revert, I can confirm that the regression comes from #10261.

**Comment by Adinimys** [comment]
If I'm not mistaken the issue comes from files->get_item_metadata(p_idx) in FileSystemDock::_select_file(p_idx)
When I select my file "Character.tscn" in my folder "Characters", the function returns a string with "res://Characters/Character.tscn" in the old code whereas I get "res://Characters" with the new one thus having an error saying that "res://Characters" cannot be found

**Comment by Cradmon** [comment]
Just had a look at the error, and found the mistake.
It was due to renaming a variable in '_select_file'.
I'll submit the PR.

**Comment by Adinimys** [comment]
Nice, I was stuck with this issue myself ^^

**Comment by Cradmon** [comment]
@Adinimys I made the original commit, so it was easier for me to backtrace the error. Your comment on the return string was extremely useful in quickly finding the mistake I made.
