### ISSUE TITLE
New Theme: code completition tooltip not completely visible

### ISSUE THREAD

**Issue by the-mech** [godotengine/godot#1257]
I think the screenshot  says everything :)
![image](https://cloud.githubusercontent.com/assets/10233279/5791112/fca36af0-9ebb-11e4-8ba2-f151ccaf26a4.png)

**Comment by okamstudio** [comment]
hmm dang, thanks for the report

On Sat, Jan 17, 2015 at 5:48 PM, Roman Nekrassow <notifications@github.com>
wrote:

> I think the screenshot says everything :)
> [image: image]
> <https://cloud.githubusercontent.com/assets/10233279/5791112/fca36af0-9ebb-11e4-8ba2-f151ccaf26a4.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/1257>.
>



-- 

*OkamStudio*

**Comment by mamarilmanson** [comment]
I think... just maybe... you can tighten the space between windows? and maybe reduce the window split indicator to just one vert/horizontal dotted line...

**Comment by akien-mga** [comment]
This issue is still valid, the tooltip should be made to be on top of all docks (not forgetting the scrollbar of the TextEdit). It should also be made sure that it won't go out of the window if it's too long.
![tooltip](https://cloud.githubusercontent.com/assets/4701338/11020645/b0faed7e-8625-11e5-8d3b-4b7bf7bc6b79.jpg)

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by neikeq** [comment]
I would label this as a bug, instead of enhancement.

**Comment by bojidar-bg** [comment]
@neikeq There..
