### ISSUE TITLE
Add regex search/replacement capability to the text editor

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#12661]
I use regex quite a bit when re-factoring/re-formatting code "by hand". For instance replacing "[ \t]+$" by "" will help remove the trailing white spaces and tabs. Or replacing "#[^ ]" by "# " will add a leading space in all comments. So, it'd be great if one wouldn't have to open the text file in some other editor to do those changes. Cheers!

**Comment by Calinou** [comment]
In the meantime, you may want to use the command-line tool [sd](https://github.com/chmln/sd) (or good old sed).

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
