### ISSUE TITLE
Texture Region dock doesn't resize when the windows resizes

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#12679]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 master https://github.com/godotengine/godot/commit/9a78efc7c270211e49fd7b2f071b61c706febffc

**Issue description:**

![https://i.imgur.com/7z0qdIU.gifv](https://i.imgur.com/7z0qdIU.gif)

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by MarianoGnu** [comment]
Yes this is caused because of the toolbar, wich fixes the minimum size.
Maybe it would be possible to move the snap options to the inspector on a bottom control? (like the mesh previews)
