### ISSUE TITLE
Scrubbing The AnimationPlayer Timeline Should Play AnimatedSprites

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#12672]
I am working on a game that uses lots of frame animation in cut-scenes. The only way I can preview AnimatedSprite nodes is by hitting the play icon. I would like for it to play AnimatedSprite nodes if you scrub the AnimationPlayer play head by clicking and dragging the mouse.

**Comment by aaronmzn** [comment]
The way AnimationPlayer works is by keyframing, so in order to use AnimationPlayer timeline with AnimatedSprite is by keyframing the frames in AnimatedSprite like you would do with Sprite node

**Comment by davidpgil** [comment]
...So, the enhancement I am asking for means that if inside the AnimatedSprite node there is a looping animation, then I want to see the keyframes that would come from the FPS setting in the node. If I set the FPS to be 15fps, then when I go back to the AnimationPlayer I would see the keyframes. Perhaps they can be a different color to indicate they are "generated" keyframes from AnimatedSprite.

**Comment by aaronmzn** [comment]
oh, I see what you mean, well the only solution I see for now is using AnimationPlayer to remade the animations from AnimatedSprites, just keyframe the frames you want for a certain animation on AnimationPlayer and change the lenght value as it is the number of frames then if you want to use them in code:
AnimationPlayer.play( ”animation_name”, -1, speed_value=1) the defaul speed is 1, that's the way of changing the animation speed in this node.

you could use AnimationPlayer.play( ”animation_name”) and then AnimationPlayer.set_speed ( speed_value ) to change the speed easily

Honestly doing frame animations in godot is a bit harder than it should, AnimationPlayer is made for 3d and cutout animations, AnimatedSprite is easier for this animations but if you use it you'll miss the Keyframe feature.

**Comment by davidpgil** [comment]
I am already aware of what I could do to work around these things. I have. I posted this issue as part of my post-mortem of a project I already completed. If I was a good enough C++ developer I would be helping with this, but as of right now I better serve as a user with lots of real industry experience.

**Comment by akien-mga** [comment]
See also #10468.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
