### ISSUE TITLE
Usage of ARToolKit / artoolkitX as alternative to ARKit 

### ISSUE THREAD

**Issue by msmshazan** [godotengine/godot#12714]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

**Issue description:**

Usage of ARtoolkit (https://artoolkit.org) instead of apple's arkit since the ARtoolkit is open source
If you're curious about the license ```ARToolKit versions 5.2 and later are made available freely under the GNU Library General Public License version 3 (LGPLv3), with the addition of a special exception permitting static linking.```
**Steps to reproduce:**

**Link to minimal example project:**

**Comment by BastiaanOlij** [comment]
Just cross posting my remarks on this I made to @msmshazan on the godot_openvr repo

--
It would be interesting to look into implementing this as an ARVR plugin. I've started work on enhancing the Camera Feed logic that is still in development to be extendable through GDNative. That would allow the camera feed from a GDNative implemented AR solution to provide a background image.

Not knowing anything about the internals of the ARToolkit, in theory the rest should be possible as a GDNative module. Only downside is the same as with ARKit, apple does not allow deployment of dynamic libraries on iOS.

The problem of static linking lies more on the Godot side of life. One of the things we're trying to minimise is bloating the core of Godot with a lot of logic people won't be using.

Dynamic libraries such as the OpenVR plugin make it so that only developers who actually want to publish a VR game will include the code.

As ARKit is part of the OS the additions to Godot are minor but ARToolkit is a complete full featured package which would result in a relatively huge increase of the Godot executable size while most developers won't be developing for AR.

So the preference would be to develop an ARToolkit GDNative plugin but that would be hard to deploy. Endragor and Karroffel were discussing options the other day on how we could make it optional to statically link a GDNative plugin when required.
--

Anyway, my plate at the moment is pretty full so at this point in time I can only offer advice. Have a look at #9967 to see how ARKit is implemented. That should should provide a lot of the basis of implementing ARCore or ARToolkit.

**Comment by razcore-art** [comment]
So this artoolkit doesn't seem to be available any more or at least I couldn't find it at the redirected page: https://daqri.com/. This issue should be either updated or closed unless someone actually does find where this artoolkit is hiding.

I was looking at [google's arcore](https://developers.google.com/ar/) which seem to have support for android and ios. I haven't looked too deep, didn't see any visible license, it's probably in some github repository but in any case I think it's worth looking into. They already have support for unity & ue.

**Comment by akien-mga** [comment]
ARToolKit as owned by Daqri seems indeed to be more or less dead, at least they do a great job at hiding information about it. There's still a GitHub repo though: https://github.com/artoolkit/artoolkit5

But apparently the original devs of ARToolKit forked it into artoolkitX: http://www.artoolkitx.org/
They maintain two projects:
- Continuation of ARToolKit 5, with a 5.4 release: https://github.com/artoolkitx/artoolkit5 http://www.artoolkitx.org/docs/downloads/
- artoolkitX, their new project, now at version 1.0.2: https://github.com/artoolkitx/artoolkitx

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
