### ISSUE TITLE
Duplicating a node via the editor doesn't duplicate its signals

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#12750]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot Build: b279f641c

**Issue description:**
I don't know if it's really a bug, or how it's supposed to work. But I find strange that signals aren't duplicated when duplicating nodes.

**Comment by akien-mga** [comment]
Steps to reproduce? There are many ways to "duplicate" nodes, you need to be more specific.

**Comment by akien-mga** [comment]
BTW @RandomShaper, we're duplicate signals twice it seems, both in `Node::_duplicate(p_flags)` and in `Node::duplicate(p_flags)` which calls the former. 4e22b6acd did not fix it, just put the duplicated duplication behind the DUPLICATE_SIGNALS flag.

**Comment by YeldhamDev** [comment]
@akien-mga 
![bug](https://user-images.githubusercontent.com/30739239/32604621-61b070da-c535-11e7-9bc1-386cc7aad3b1.gif)

**Comment by akien-mga** [comment]
The problem is specific to the editor, as it uses `SceneTree::_duplicate` instead of `Node::_duplicate` and thus does not respect the `DUPLICATE_SIGNALS` flag: https://github.com/godotengine/godot/blob/c755b68/editor/scene_tree_dock.cpp#L824

Related to #11182 - fixing #11182 by making `SceneTree::_duplicate` use `Node::_duplicate` in the non-instance case would fix this issue.

**Comment by akien-mga** [comment]
Fixed by #12893.
