### ISSUE TITLE
Visually linking exported Nodes in the editor

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#12776]
See #6015.

Being able to connect two nodes visually in the editor would help immensely with level design clarity and game logic bug tracking.
It's a lot more obvious to every level designer when a lever is connected to the wrong door with a line than when it's hidden as a property that only shows up when clicked on, to give a really simple example.

I think https://github.com/godotengine/godot/issues/6015#issuecomment-241388278 had a really good idea of how to expose this functionality through export parameters, since exporting a NodePath is the only realistic usecase I can think of where linking would be useful:
```GDScript
export(NodePath, "#FFFFFF") var attack_entity = @""
```
Optionally a few line styles could be supplied as well, such as solid, dotted, dashed etc. to give the user more control over indicating what each connection means. A dotted line could indicate which entity a lever is attached to, while dashed lines could show warp destinations, where a white line is a warp for the player and a red line is a warp for enemies, etc.

Example of how it could look by @bojidar-bg:
![8b855024-5989-11e6-85e9-1eaa72328706](https://user-images.githubusercontent.com/20242421/32606904-47eb3ea6-c557-11e7-9bc9-c5d8b1dd1517.png)

**Comment by eon-s** [comment]
It can be easily done with tool mode (even with a helper custom node), not sure if will be good to add for this kind of specific use case.

**Comment by akien-mga** [comment]
Am editor plugin as @bojidar-bg had started to work on would do the trick IMO.

**Comment by leoddd** [comment]
A plugin would work of course, but I feel like wanting to visually connect two nodes is a thing that pretty much every game that exports a NodePath to the editor could make use of, and I'm not actually sure how one would configure such a plugin to show the right kind of connection style if one can't use the export hints for that.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
