### ISSUE TITLE
Camera icon is too big and obstructs gizmos

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#12792]
**Godot version: master 9437db7**

**Issue description:**
Camera icon is too big when going far from it and obstructs the gizmos and everything near making hard to see the camera details.

I don't know how could this be better, maybe a set of toggles for icons (including others like sound).

**Steps to reproduce:**
Zoom out in a 3D scene with a camera and see how the icon thinks is more important than the node's visual details.

![whereismycamera](https://user-images.githubusercontent.com/10215987/32636041-c531d962-c591-11e7-8c62-086bdf5929e4.png)

**Comment by djrm** [comment]
the icon might be more important under some circumstances, if the icon gets smaller, then you will find another zoom level were it is too big, maybe the gizmo should be drawn on top.

**Comment by Zylann** [comment]
Or maybe gizmos should have a mode in which they keep their size regardless of zoom? I use this option a lot in Unity3D, it's very useful.

**Comment by groud** [comment]
> Or maybe gizmos should have a mode in which they keep (or not keep) their size regardless of zoom? I use this option a lot in Unity3D, it's very useful.

Good idea (But please, don't make it an editor option! ^^)

**Comment by Zylann** [comment]
@groud well it usually consist of two controls in the viewport, one for keep/not keep and another for size 
![image](https://user-images.githubusercontent.com/1311555/32653378-9ce77e58-c5ff-11e7-8222-91cf4f97cef5.png)

**Comment by groud** [comment]
Yeah, but do you use it that often ? Or just set it once and never touch it ?

**Comment by Zylann** [comment]
@groud it depends a lot about what I'm doing in the viewport. In very busy scenes I tend to use 3D (because in the distance they all stack on top of each other), in small scenes or 3D UI I use the other.

I also find that in Godot, only icons are zoom-independent, and it can be a bit problematic because for example, I had to adjust a directional light on a huge scene recently, and I was constantly forced to zoom on it (and loose focus on where I was before) just to see where it points at because the arrow is 3D.

**Comment by KoBeWi** [comment]
This looks like #16221, which was fixed

**Comment by akien-mga** [comment]
Closing as fixed.
