### ISSUE TITLE
 I recommend the Godot game engine to support the Lua programming language

### ISSUE THREAD

**Issue by CyangYu** [godotengine/godot#12808]
Lua is a fast and light language, at the same time, the c/c++ function can be easy invoked by lua

**Comment by reduz** [comment]
We used to support Lua many years ago and then dropped it.

Problem with Lua is:
* Does not support multiple threads due to single stack approach
* Custom type support (ie, Vector2,Vector3, etc). is not very fast
* Binding code is extremely complex and prone to bugs
* Garbage collector can cause stalls 
* Lack of proper class system results in hacks with tables and fallbacks that are slow

GDScript does not have any of these problems, and integrates very well to Godot. I recommend you learn it.

More informaiton here:
http://docs.godotengine.org/en/stable/about/faq.html
