### ISSUE TITLE
Method calls in mono, using custom c++ module not working.

### ISSUE THREAD

**Issue by nextdimension** [godotengine/godot#12851]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Win 10x64 Godot 3.0 Master

**Issue description:**

Made custom c++ module. Compiled, tested with GDScript -working, tested with mono. I can instantiate the Object but method calls are giving "does not contain definition".

**Comment by Hinsbart** [comment]
Did you re-generate the glue after adding your module?

**Comment by nextdimension** [comment]
yes I did regenerate the glue.

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by neikeq** [comment]
@nextdimension Can you share an example module?

**Comment by nextdimension** [comment]
The ones that come with the engine, for instance the enet module.

**Comment by Calinou** [comment]
@nextdimension Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
