### ISSUE TITLE
No light from emission texture

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#12874]
(Using current master on Arch Linux with Intel GPU [Haswell 4770K], mesa 17.2.5)

An emissive material doesn't seem to work as a light source.

[emission.zip](https://github.com/godotengine/godot/files/1465207/emission.zip)

**Comment by reduz** [comment]
in the objects using the GI Probe, you have to enable "use in baked light"

**Comment by fracteed** [comment]
@tagcup sounds like this is related to #10534

**Comment by tagcup** [comment]
@reduz I forgot that in the example project I attached, but no, the problem is there with "use in baked light" checked. I updated the example project just in case.

@fracteed I'm seeing this problem with and without GIProbe. I just couldn't get an emissive object light its surroundings so far.

**Comment by reduz** [comment]
Without GIProbe it's impossible to make emissive materials to emit light.
Having baked lightmaps will eventually help too after 3.0

On Nov 12, 2017 8:42 PM, "Ferenc Arn" <notifications@github.com> wrote:

@reduz <https://github.com/reduz> I forgot that in the example project I
attached, but no, the problem is there with "use in baked light" checked. I
updated the example project just in case.

@fracteed <https://github.com/fracteed> I'm seeing this problem with and
without GIProbe. I just couldn't get an emissive object light its
surroundings so far.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/12874#issuecomment-343778548>,
or mute the thread

**Comment by tagcup** [comment]
Ah, OK, good to know. So I guess this is indeed a duplicate of #10534 then, with uniform color, I can indeed see emission.
