### ISSUE TITLE
Tilemap Fake Shadow Layer

### ISSUE THREAD

**Issue by RaXaR** [godotengine/godot#12905]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
PC, Win 7 x64, nVidia GTX 680

**Issue description:**
I created a TileMap to act as a 'shadow' layer. (I placed it below my 'walls' TileMap.)
I placed a bunch of black, tiles on the layer, some of the tiles have pixels that overlap.
I then set the shadow TileMap's opacity to 0.5.
The intent was to have all the tiles (even overlapping pieces) render at the same opacity. The effect I was hoping for was for all the black pixels to 'combine' across the shadow layer.

I'm guessing that I'll need a custom shader or something to achieve this but thought I'd ask here first.
So can this be achieved with Godot's built-in mechanism? If not, could someone point me in the right direction please.

Thanks for any help.

EDIT: link to image 
![shadow_issue](https://user-images.githubusercontent.com/216180/32755867-ee5c40ec-c8df-11e7-8853-4bf925ee8b92.jpg)

**Comment by girng** [comment]
david brevik implemented something like this in It Lurks Below. iirc, he said it was a shader

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
