### ISSUE TITLE
Suggestions and questions about Godot and the asset store

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#12918]
I have a few suggestions to improve the Godot Game engine

I have a few suggestions to improve Godot which are:

- Have a built in modeling tool
- Have a built in tool that converts anything made in Unity (such as the scripts made in Unity) and convert to something  that Godot understands.

I wanted to ask you some questions.

One of them is when is Godot 3.0 stable build is going to be released?

The other question is that who regulates Godot's assets that are stored in the assets store? Is it Github or is it the owners of Godot?

Are the users able to upload whatever they want to for the asset store or does it have to go through a mediation/review?

**Comment by NullConstant** [comment]
>Have a built in modeling tool

Godot is a game engine, and apart from maybe something like a built-in level or terrain editor (the latter of which is being worked on as a module somewhere), that seems to be out of its scope. Use Blender or something else instead.

>Have a built in tool that converts anything made in Unity (such as the scripts made in Unity) and convert to something that Godot understands.

Apart from the fact that this would be extremely difficult to do on a technical level simply because of the architectural differences between Godot and Unity (which you can read about [here](http://docs.godotengine.org/en/stable/learning/editor/unity_to_godot.html)) for anything but the absolute most trivial projects (not to mention keeping it up to date as both Godot and Unity advance and improve), it just doesn't seem like something that is necessary at all.

Godot is Godot, not open-source Unity. It never even tried to maintain any sort of compatibility with it, and certainly shouldn't go to that great of a length to achieve it.

As for the asset ~~store~~ library, I don't exactly know what the process is like, though I do believe there's at least some sort of review process, if only so that people don't upload things that just plainly don't work in Godot, or act as malware. I could however be wrong, though.

**Comment by akien-mga** [comment]
This is an issue tracker for bug reports and enhancement requests, not to ask general questions or ask for very broad things like modelling tools or becoming a Unity clone. I would advise you to discuss such things directly [with the community](https://godotengine.org/community) to pre-filter what might be relevant for an issue tracker used by engine developers.
