### ISSUE TITLE
Renaming a .cs file does not edit the .csproj file

### ISSUE THREAD

**Issue by zedutchgandalf** [godotengine/godot#12917]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 8.1 - custom Godot build (2cdfef5)

**Issue description:**
When you rename a .cs file from within the editor, the .csproj file doesn't get changed. This makes it so you have to open the mono project file manually to change the filename there too before you can run your Godot project again.

**Steps to reproduce:**
1. Create a new project
2. Add a C# file
3. Change that file's name to something else

**Comment by akien-mga** [comment]
Related to #12917.

**Comment by zedutchgandalf** [comment]
@akien-mga Of course it's related, it's the same issue :P

**Comment by Zylann** [comment]
I remember an issue exists but I cannot find it, I had commented on it about the fact that using an IDE was usually recommended with C# (because IDEs will rename file and update csproj accordingly as well as preserving all build options)

**Comment by eska014** [comment]
This is the related issue: #12415

**Comment by reduz** [comment]
@neikeq

**Comment by NathanWarden** [comment]
My opinion is still that we just have a solution and project called something like GodotProject.sln/csproj. More things need to be renamed when a project needs to be renamed than just the files. Also the assembly output needs to be renamed. It seems much more straight forward to just have a static name for the main solution and project file.

I'm not stuck on this idea, but if the renaming bug isn't moving forward (and I also have no time/motivation to take a stab at it) then I think the easiest thing is to just have a static solution and project naming scheme.

**Comment by Marshal313** [comment]
@NathanWarden Please no static solutions (Project is less problematic !). Unity does the same, And it doesn't let you work on any additional projects in the solution.

@Zylann I think your solution (Always using an IDE for C#) is better, because there are lots of IDEs for C# out there, why reinvent the wheel inside the engine ? The only problem here is that if the script file is renamed from the IDE, then the Engine loses the file and therefore makes its content (The C# codes) a built-in resource on the node it was attached to.
I think we need a way to either :

1. Track file path changes (including move and rename) from IDE and apply them in Engine (That I think is not possible without plugins for the IDE)
2. Make the engine change the path to that specific files in .csproj project config file, And hope that it works on the IDE. (Both MonoDevelop and VS refresh the project as soon as you switch to the IDE, So unless people are willing to use Notepad++ to write C#, I think it would works perfectly)

**Comment by Nufflee** [comment]
I can try working on this, I'll try to make it not regenerate or overwrite the .csproj file.

**Comment by Scellow** [comment]
Why not move to the new .csproj format 

So we don't have to have to deal with that kind of issue

Mono can build projects that uses the new .csproj format

**Comment by Nufflee** [comment]
@Scellow opened an issue [here](#20305).

**Comment by Svetomechc** [comment]
Yeah, why not just use new .csproj format? This issue would automatically be gone then.

**Comment by aaronfranke** [comment]
This issue might disappear if we switch to the new csproj format, but as far as I know this is only available in .NET Core, which we don't use. Perhaps if we switch to .NET 5 in the future?

In any case, not going to be done for 3.2, and I assume won't be done for 4.0 either. Perhaps 4.1?

**Comment by nonunknown** [comment]
using godot 3.2.1 and this error still happends ->
![remove](https://user-images.githubusercontent.com/58845030/76527473-0c037000-644e-11ea-9b33-33cd1af97823.gif)

aimed for godot 4? @aaronfranke 

godot plz fix!

**Comment by Calinou** [comment]
I think the plan is to move to the new `.csproj` format by the time Godot 4.0 is released, so this should hopefully be fixed.

**Comment by neikeq** [comment]
Although this won't be a problem with project SDKs in 4.0, this still needs to be addressed for 3.2.

The callbacks for files being renamed/moved/removed in the Godot file system dock have been there for quite some time. I feel bad because they were added to my request, but I never got to use them to fix this.
