### ISSUE TITLE
OS window management

### ISSUE THREAD

**Issue by leonkrause** [godotengine/godot#12926]
Currently there is `OS::set_window_fullscreen`, `set_window_maximized` and `set_borderless_window`. Several combinations of these don't make sense, so this should be changed to `set_window_mode` with modes `WINDOW_MODE_WINDOWED`, `*_WINDOWED_BORDERLESS`, `*_MAXIMIZED`, `*_MAXIMIZED_BORDERLESS` and `*_FULLSCREEN`.

The `fullscreen` project setting should be changed to `window_mode` accordingly and offer the same choice.

What happens when `OS::set_window_size`, `OS::set_window_position` and `OS::set_window_resizable` is called when window_mode is not windowed or windowed_borderless should be unambiguously defined so that this works the same in different platforms.
I propose these setting are not applied but saved for the next time or windowed or windowed_borderless is entered.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
