### ISSUE TITLE
Viewport / Scene Tree Drag-and-drop improvements

### ISSUE THREAD

**Issue by Web-eWorks** [godotengine/godot#12931]
Version: Godot 3.0 Master (66c1d9e4)

When dragging and dropping a scene or mesh onto an empty scene (no root node), the default behavior should be to create the dropped object as the new root node, similar to the behavior of the Add Node button in the Scene Tree. Currently this fails with an error about an empty selection.

Dragging and dropping a mesh/scene onto a scene with no selected node should instance it as a child of the root node by default, rather than complaining about an empty selection.

Additionally, dragging and dropping a mesh into the Scene Tree should instance it in the same way that a Scene is currently instanced.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
