### ISSUE TITLE
BMFont format outline color

### ISSUE THREAD

**Issue by arcanis** [godotengine/godot#12935]
**Godot version:** master

PR #12619 by @DmitriySalnikov adds support for loading fnt files through the the "Load font data" settings in the editor (by going through the `create_from_fnt` hook). Unfortunately, it means there's currently no way to set the outline color like there was before (at the time it was possible to do so through the import window).

**Comment by DmitriySalnikov** [comment]
[editor_font_import_plugin.cpp](https://github.com/godotengine/godot/blob/2.2-legacy/tools/editor/io_plugins/editor_font_import_plugin.cpp)
it seems that this file contains the importer.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
