### ISSUE TITLE
Convex/concave collider creation inconsistency

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#12964]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 4d08e7c

**Issue description:**
I'm very new to physics in Godot, and spent several hours trying to make convex/concave colliders from meshes (creating the CollisionShape node manually):

![default](https://user-images.githubusercontent.com/11571820/32889388-d1ff3794-cadb-11e7-8cef-c6aa3496412f.png)

The right method was here (select the MeshInstance node first):

![default](https://user-images.githubusercontent.com/11571820/32889473-2ecdbb08-cadc-11e7-9d1d-e965552fdae4.png)

I suggest adding the possibility to generate colliders from the menu on the first screenshot too, by analogy from creating primitive colliders.

**Link to minimal example project:**

[godot-mesh-collider-create.zip](https://github.com/godotengine/godot/files/1478434/godot-mesh-collider-create.zip)

**Comment by starry-abyss** [comment]
Would be great to see the very menu moved/duplicated to the inspector, and not only for CollisionShape. At least that should fix part of the issue - where the user doesn't even notice that there exists such menu.

**Comment by vnen** [comment]
The problem I see here is that the toolbar menu appears when you select the Mesh, but the Inspector menu will be shown only when the CollisionShape is selected, so to which mesh it should refer? You could say to  pick the sibling, but there could be lots of those too.

This would require increasing the complexity of the inspector, since it would have to check for specific types and properties to add options to this menu.

**Comment by starry-abyss** [comment]
Appear in the inspector in the same case as in top menu (after selecting mesh). But yes, it's a bit diferent thing than the original issue...

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by starry-abyss** [comment]
Just in case, this looks like a solution to my issue: https://github.com/godotengine/godot-proposals/issues/3550

**Comment by pycbouh** [comment]
@starry-abyss That proposal won't add anything to the inspector, but it will hopefully make the contextual tools more obvious, yeah.
