### ISSUE TITLE
User-created framebuffers? (Implementing a 3d outline shader in Godot 3)

### ISSUE THREAD

**Issue by zejji** [godotengine/godot#13048]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS: Windows 10
Device: Dell XPS 15 9560
GPU: Nvidia GTX 1050
GPU Driver: 388.00
Godot version: 3.0 alpha 2

**Issue description:**

I was hoping to implement an 3d outline shader in Godot 3. It would be used in order to highlight the outline of a selected object in the context of an adventure game. However, if my understanding is correct, there does not appear to be any way to do so!

I have read the article on Godot 3's renderer design [here](https://godotengine.org/article/godot-3-renderer-design-explained) but I could not see it describe any way in which the user can output custom information to additional framebuffers or access this information in a subsequent fullscreen pass. I note that the article describes an "Opaque sort" pass which outputs, among things, the material index, but presumably this framebuffer information is not available to the user either?

Is there any way to achieve this effect in Godot 3? Alternatively, if the end-user cannot generate such effects by using a custom shader, is there any prospect of commonly-used effects such as outline shading being built into the engine?

**Edit** - here is an example of the kind of effect I am trying to achieve:

![silhouetteoutline1](https://user-images.githubusercontent.com/3524191/32994548-d667dc78-cd60-11e7-99f2-9d5b5bd7f340.jpg)

**Steps to reproduce:**

N/A

**Link to minimal example project:**

**Comment by hoelzl** [comment]
You can use the `grow` parameter of spatial materials to achieve a similar effect, see
http://docs.godotengine.org/en/latest/learning/features/3d/spatial_material.html

**Comment by zejji** [comment]
@hoelzl 

Many thanks for pointing me in that direction - it works fairly well and is very easy to set up.

However, the effect looks a little bit 'rough around the edges' (see example picture below). It would still be great if it were possible to be able to use framebuffers within Godot too (as an advanced feature) for added flexibility.

![grow_test](https://user-images.githubusercontent.com/3524191/32997669-d93a820a-cd8a-11e7-9c99-6fd1a80e2d8d.jpg)

**Comment by hoelzl** [comment]
I absolutely agree, but unfortunately I have no idea how difficult it would be to add this to the Godot renderer.

**Comment by x1212** [comment]
It might look a little bit better if the model you are using the effect on doesn't have sharp edges but some additional egeloops that make multiple soft edges together look like they are a sharp edge. (in blender the bevel tool should be able to do that for you)
That way vertices with the same original position will also be shifted by the same normal resulting in the same end position removing those holes in the outline.

**Comment by blurymind** [comment]
One of the demos had an outline 2d shader, there is probably a way to make one for 3d too..
https://godotengine.org/qa/4547/outline-shader
somebody has asked this before btw

**Comment by eon-s** [comment]
Is this an issue or something for Q&A?

In the case of the later, you may need to do some research and/or try to adapt existing outline shaders, it should be possible (look at shadertoy and other similar sites).
Also check the toon example on the material tester demo which is close to an outline using built in material options.

**Comment by zejji** [comment]
@blurymind @eon-s 

Yes, this is an issue, not just a Q&A. The point is that you can't implement a post-process outline shader for 3d objects without access to an additional framebuffer storing the shape of the object you are trying to outline. (I already know how to implement a shader along the lines of the 2d outline shader.)

However, I think the solution suggested by @x1212, i.e. using a higher-detail model is probably the only workable solution at present.

It would, however, be great if the user were given some additional control over framebuffers in future versions of Godot.

**Comment by Gibbz** [comment]
Id like to see a way to do an outline effect via shader. Using a mesh to create an outline has to many poor side effects. 
Even if it was for now some kind of built in shader?

**Comment by reduz** [comment]
Will be added in 3.1

**Comment by Demmios** [comment]
![shadows](https://user-images.githubusercontent.com/35068082/34533968-8a89b2a2-f0a3-11e7-9b00-817873d9f078.png)

Would this framebuffer help me on this case above where i have opacity shadows that overlaps each other creating an undesired darker shadow? Could i use the frame buffer to render and have all the overlaps at the same opacity and draw them back to the main game? If so will be a great adition

**Comment by path9263** [comment]
> Will be added in 3.1

Just clarifying... is access to framebuffers being added or just some kind of special shader for outlines?  I would really like access to framebuffers (namely the stencil buffer) in order to make a cross section shader similar to [this one](http://glbook.gamedev.net/GLBOOK/glbook.gamedev.net/moglgp/advclip.html).  Thanks!

**Comment by akien-mga** [comment]
> Will be added in 3.1

Didn't happen eventually and we're now in feature freeze for Godot 3.1. Most new rendering features have been pushed back to the Vulkan renderer work in 3.2 / 4.0.

**Comment by mart368b** [comment]
So something like this?
![image](https://user-images.githubusercontent.com/22445645/61492999-dbe4f980-a9b2-11e9-8123-53e6c0fcb17f.png)
[shader_outline.zip](https://github.com/godotengine/godot/files/3408482/shader_outline.zip)

What i did was
* Create a ViewportContainer that covers the entire screen
  * Add a outline ShaderMaterial like the demo suggested
* Create a Viewport with a transparent background
* Create a Camera that only draw one layer using the cull mask
* Set all the outlined Nodes to be draw on the specified layer

**Comment by path9263** [comment]
Does that mean that the whole of all your highlighted objects get drawn on top of any other objects in the scene?  If you put your outlined node behind another does it look like this image? 

![outline](https://user-images.githubusercontent.com/3977110/61599347-f8647a00-abdc-11e9-91be-4c7a15a01192.png)

**Comment by mart368b** [comment]
Yes
![billede](https://user-images.githubusercontent.com/22445645/61975946-c000d980-afea-11e9-99af-804ed29eb04a.png)
just remember to have the second camera have the same transform and settings as the first one.
Otherwise this will happen
![billede](https://user-images.githubusercontent.com/22445645/61975988-de66d500-afea-11e9-9a71-2ddab74eb3cc.png)

**Comment by creikey** [comment]
![image](https://user-images.githubusercontent.com/28424206/81135268-42201600-8f0c-11ea-8718-2f39e4913696.png)
I would also like to point out that although I'm not entirely sure how this works, the method to accomplish this from @mart368b also seems to put the object with an outline behind the other object. @akien-mga maybe this issue can be closed if viewports already provide the functionality of a framebuffer?

**Comment by Calinou** [comment]
Closing per @creikey's comment.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
