### ISSUE TITLE
If the game is paused, then the SceneTree is reset, should it still be paused?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#13087]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Ubuntu 17.10 64-bit, 3.0 build 341bf71.

**Issue description:**
When a game over situation is reached, the main application pauses (except for the "game over" scene and its attached nodes and code). The "game over" scene has code that watches for any key press, then restarts the application. However, unless explicitly told before restarting, the application remains paused.

**Steps to reproduce:**
Have a game pause and then restart via `get_tree ().reload_current_scene()` without unpausing.

**Link to minimal example project:**
https://www.dropbox.com/s/xe1zbl0zjoodg6q/13084_demonstrator.webm?dl=0 - remove the `get_tree ().set_pause (false)` statement in Source/Scripts/UI/game_over.gd to watch this.

**Comment by akien-mga** [comment]
I have no strong opinion, I guess both behaviours can be wanted; e.g. you could pause, reload the scene, but want it to stay paused until the user presses a key to actual start playing the reloaded level.
Which would still be possible if the proposed change is implemented, such users would just need to call `get_tree().set_pause(true)` again after reloading the scene. So either way is fine, the question is which is more common :)

**Comment by Sslaxx** [comment]
Maybe this could be a project setting?

**Comment by akien-mga** [comment]
No, core engine logic should not be a project setting.

**Comment by Sslaxx** [comment]
Same issue also applies to singletons. Their values do not get reset by `get_tree ().reload_current_scene()` either.

**Comment by vnen** [comment]
Singletons aren't part of the current scene. That's the point of singletons, they're available even when you switch scenes.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
