### ISSUE TITLE
camera2D rotating is not rotating drag-margin bounds

### ISSUE THREAD

**Issue by Th0r12356** [godotengine/godot#13154]
**Issue description:**
Rotating a camera2D is not rotating drag-margin-bounds, but this behavior is shown in the editor.
My desired margin is uneven and relative to the cameras rotation. Drag-margin:(0.75, 0.2, 0.75, 0.2 ).

I've tried:
-camera as child of a body
-camera follow manual by _process. global_rotation and rotation makes no difference.

**Steps to reproduce:**
1.create a turnable object the camera should follow.
2. add a camera as child (current, rotation, dragging = checked)
3. add drag-margin on camera
4. move around and rotate

**Link to minimal example project:**

[cameraRotationIssue.zip](https://github.com/godotengine/godot/files/1492877/cameraRotationIssue.zip)

-arrowkeys for controlling

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
