### ISSUE TITLE
Show a GUI error message when attempting to run a project referencing nonexistent resources

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#13155]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 7 64, Godot 3.0-alpha2

**Issue description:**

[Enhancement/Usability]
Removing or moving resources causes Godot runtime to silently crash when attempting to run the project. 
Console throws `Error: [ext_resource] referenced nonexistent resource at: res://....` but I think most users will be expecting a GUI error message since it is the case with most errors. Beginners may fail to notice the console message and be puzzled as to why the project fails to run. 

**Steps to reproduce:**
1- Reference resource in some node(for example a sprite texture or stream player stream)
2- Remove or move resource in filesystem
3- Attempt to run the project

**Link to minimal example project:**

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
