### ISSUE TITLE
3D Rigidbody slides buggy on tri mesh static body

### ISSUE THREAD

**Issue by fxdave** [godotengine/godot#13165]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot_v3.0-alpha2_win64

**Issue description:**

I made a road mesh that I wanted to use as a collider. So I generated a tri mesh static body.
I made a flying car rigid body with box collider
I move my car with translate() function.

**Steps to reproduce:**
1. make a RigidBody with a box collider
2. import a big straight mesh and generate static body from it
3. make a script that uses the translate() function to move your RigidBody 
4. approach the edges of the collision object

**Video:**
https://www.youtube.com/watch?v=4DAyONdf4-k

**Link to minimal example project:**
[New Game Project - Copy.zip](https://github.com/godotengine/godot/files/1493603/New.Game.Project.-.Copy.zip)

Edit: I changed gravity to 9.81, I think it makes sense

**Comment by kubecz3k** [comment]
You should never use translate() function to control movement of your for rigid body (unless it's in kinematic mode). It's simply prohibited. If you are using rigidbody as your character that means you decided to deal with physics manually, and only manipulation you can do is by modifying forces inside manual_integration. 

You probably should use KinematicBody instead, if you want to have such kind of control. If you for some reason don't want to have full control of you body then use manual integration and modify state of the body inside `_integrate_forces`.

**Comment by fxdave** [comment]
Same issue with adding force by _integrate_forces(state).

**Comment by kubecz3k** [comment]
@fxdave if you update the reproduction project so it will not use `set_translation` I will take a look

**Comment by fxdave** [comment]
@kubecz3k Thank you for that!
[New Game Project - Copy.zip](https://github.com/godotengine/godot/files/1496827/New.Game.Project.-.Copy.zip)

**Comment by kubecz3k** [comment]
I checked your project. I think you quite decalibrated the physics engine by setting gravity 10 times stronger than earth (gravity scale scales base gravity, so your was 9.8*9.8) and putting at the same time very strong acceleration and dumping.  
Also in dynamic character controller we usually use rayshapes exactly to compensate for various kind of problems (I don't quite think you can expect that you will push rigidbody boxes through such shape and expect from them to just works (but with properly implemented `kinematic body` it would work!)).

Anyway you can check fixed project which I uploaded here:
[New Game Project - Fixed.zip](https://github.com/godotengine/godot/files/1497526/New.Game.Project.-.Fixed.zip)

Also keep in mind that usually there is needed some experience when it comes to controlling rigid bodies that way. Also I never wrote 'real' game with automobiles, but there is special node in godot to simulate physics of such vehicles. It's called VehicleBody (just letting you know). 
And lastly I would check demos since as far as I know there are some nice samples of kinematic body control scheme there: https://github.com/godotengine/godot-demo-projects/tree/master/3d

**Comment by kubecz3k** [comment]
@fxdave You might be interested in this issue: https://github.com/godotengine/godot/issues/13207 it's possible you experienced it when you ported your project to kinematic body

**Comment by fxdave** [comment]
Thank you! I have taken a look at your fix, and you have set the custom integrator to true, but if you do it then the car doesn't move for me. Did it work for you?

**Comment by kubecz3k** [comment]
@fxdave alpha 2 is old and buggy... especially in physics area (it was freshly after merging bullet). You should compile current main or wait couple days for beta (I encourage you to compile :))

**Comment by kubecz3k** [comment]
However never did compilation on Windows... On Linux its easier from what I heard.

**Comment by kubecz3k** [comment]
If you are interested here are the docs: 
http://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html

**Comment by kubecz3k** [comment]
Oh you can also download unofficial daily builds from here: 
http://godot3builds.digitecnology.com/

**Comment by fxdave** [comment]
Awesome! Thank you!
