### ISSUE TITLE
Instance placeholder not counted in the scene dependencies (moving the file causes broken scene).

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot#13172]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Fedora 27, master branch (beta), Nvidia 930M

**Issue description:**
Dependency list should show files of placeholder scenes so that they can be fixed when the path is broken.

**Steps to reproduce:**
1. Instance a scene and set it as placeholder.
2. Move/rename/delete it (using godot or filesystem).
3. Re-start the project.
4. The scene is now broken and can only be fixed by using a text editor to manually fix the broken file path.

**Link to minimal example project:**

**Comment by vandalk** [comment]
Still Happening on 3.1, added a MRP below but it's the same description as the issue itself.
[Placeholder_MRP.zip](https://github.com/godotengine/godot/files/3833386/Placeholder_MRP.zip)

The MRP is already with the broken dependency. If you press F5 the project runs normally, but if you try to open the "Main" scene it fails. 

If you move the "godot_icon.tscn" from the "items" folder to "res" the Main scene opens again. Either that or you have to edit the Main.tscn file in an external editor and remove the placeholder or fix the path from the line:
`[node name="GodoIcon" parent="GridContainer" instance_placeholder="res://GodoIcon.tscn"]`

If I move the godot_icon.tscn file with the Main scene open, it doesn't allow me to save anymore, but it doesn't tell me the problem is the instance_placeholder
