### ISSUE TITLE
Ability to increase amount of physics collision layers

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#13186]
**Issue description:**
It would be great to have the ability to increase amount of collision layers. 
From talk on irc with @AndreaCatania it should be customizable inside Project settings and the default value should be 20 (the same amount as currently).

**Comment by Zylann** [comment]
isnt there a limit for this amount though?

**Comment by akien-mga** [comment]
The internal limit is 32, and you can already use up to 32 layers from script AFAIK, but only 20 from the editor. Showing all 32 of them in the editor would make it cumbersome, but might still be needed for some projects, hence the proposal to make it configurable.

**Comment by akien-mga** [comment]
Maybe the default value could be decreased to 16 if there's now an easy way to change it, as I suppose most games will still only use between 2 and 8 layers.

**Comment by AndreaCatania** [comment]
The best thing is to increase or decrease by step of 10, In this way we don't have to change interface in order to fit this needs.

**Comment by akien-mga** [comment]
Ah you mean to just add rows instead of adding columns. Why not. But then I'd use a step of 8 to be able to select 8 (one row), 16 (two rows), 24 (three rows) and 32 (max, four rows).

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
