### ISSUE TITLE
plugin.gd --> enter_tree() --> add_custom_type does nothing if the custom type extends ReferenceRect

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#13189]
Try creating a custom type node addon that extends ReferenceRect, godot will not add it to the nodes list.
Change it to extend from Control instead and it will work again.

Latest godot 3

**Comment by kubecz3k** [comment]
ReferenceRect you mean?

**Comment by blurymind** [comment]
Ah yes, sorry. ReferenceRect is the node class

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
The way to create custom nodes has changed, so this should be irrelevant now, so closing.
