### ISSUE TITLE
All mono builds fail

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#13215]
In TileMap.cs bindings, Vector2 defaults to false, failing all mono builds
`public void SetCell(int x, int y, int tile, bool flipX, bool flipY = false, bool transpose = false, Vector2 arg6 = false)`

Similarly in TileSet.cs
`public void TileAddShape(int id, Shape2D shape, Transform2D shapeTransform, bool oneWay, Vector2 arg4 = false)`

**Comment by neikeq** [comment]
The `bind_method` call is missing the last argument and its default value. Also, I think we should change `bind_method` to fail in such cases and show an error, instead of adding the missing arguments.

**Comment by akien-mga** [comment]
That's because @MarianoGnu added a new argument to those methods, but without changing the ClassDB bindings:
https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp#L681
https://github.com/godotengine/godot/blob/master/scene/2d/tile_map.cpp#L1503

Either that binding should be exposed to scripting languages if relevant for users (and then also in `set_cellv`), or `set_cell` should be renamed to `_set_cell`, and a new `set_cell` without the new argument should be used as binding.

**Comment by MarianoGnu** [comment]
new argument is optional, probably just wrongly exposed (looks like it belives it's a float instead of a Vector2, this causes ocmpilation error)

**Comment by Noshyaar** [comment]
Fixed by #13231?
