### ISSUE TITLE
[2.1.4] Input not handled by GUI on Android

### ISSUE THREAD

**Issue by plucian** [godotengine/godot#13256]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10 / Android

**Issue description:**
Input should be set as handled by GUI elements and not propagate as un-handled input.
This works as intended on Windows but fails on Android.
Linked also to this question:
https://godotengine.org/qa/20057/prevent-background-touch-events-on-ui-interaction

[handle_input_issue.zip](https://github.com/godotengine/godot/files/1502585/handle_input_issue.zip)
 

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Calinou** [comment]
@plucian Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
