### ISSUE TITLE
Add a Microphone API

### ISSUE THREAD

**Issue by Grabli66** [godotengine/godot#13268]
Please, add the posibility to record audio from microphone.
It's needed for creating music applications, such as i do :)

**Comment by hungrymonkey** [comment]
@Grabli66  if you wish, i can write a simple c++ signal mic module for you in the meantime using SDL 2.0.5 or greater. 

[dummy_audiostream.zip](https://github.com/godotengine/godot/files/1515081/dummy_audiostream.zip)


I am just using a mic for an unrelated purpose. As you can see in the code, I really do not care about usability other than my use case. I would modify the code for you use case


https://forums.libsdl.org/viewtopic.php?p=51881

either way, I would never expect this code to be committed because it only meant for me.

**Comment by Grabli66** [comment]
Thanks.
But I don't want temporary solution.
I'll will wait.

**Comment by DEF7** [comment]
I second the request for this functionality, in my case for purposes of streaming the audio in a VR game to other players over the network (which would obviously require some kind of realtime audio codec for low latency/bandwidth transmission).

**Comment by mad-tzar** [comment]
Hi - first time poster. 
I am growing really fond of GODOT for making 2d games! 

I have a great idea for a small game series that utlize audioinput like "scream hero". Unfortunately I just saw that there is no support for microphone input. 

I would love to get that feature!

**Comment by mad-tzar** [comment]
@hungrymonkey I just gave your link a quick look! How easy is it to implement? 
Do I need to make my own branch of the GODOT 3 engine or can it interact with the stable version?

**Comment by hungrymonkey** [comment]
@mad-tzar 

its currently not registered into GDScript. But that is easy too.

copy the module over and compile basically

the audiostream is currently crappy since i do both memory allocation and block the audio stream. 

The mic is ok, it is basically an event base mic. a few lines of code can change it into a float base

**Comment by fahrstuhl** [comment]
Thank you for your SDL mic code, @hungrymonkey ! I adapted it for a small project of mine and it worked very well.

**Comment by zvoislav** [comment]
Hi, 
I really need a audio record feature. Can you @fahrstuhl or somebody else explain me how to implement this SDL module and how to use it. 
Thank you in advanced.

**Comment by hungrymonkey** [comment]
I already provided a link

https://github.com/godotengine/godot/files/1515081/dummy_audiostream.zip

its just not registered to gdscript. You just have to add it to my modules.

If you wish you can take a look at the official mic 

https://github.com/godotengine/godot/pull/19106/files/d91183be524c2a2d13d5c40473297cbc713f43da..f045534f866204b5458b9ef32f7a5b5996253839

**Comment by akien-mga** [comment]
Fixed by #19106.

**Comment by Colorfingers** [comment]
Please add microphone support... this is pretty much a standard feature on all platforms.  Thank you...

**Comment by Calinou** [comment]
@Colorfingers This was implemented in https://github.com/godotengine/godot/pull/19106 and will be available in 3.1 :smiley:
