### ISSUE TITLE
Option to show generated GLSL code

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#1326]
It would be hugely helpful if we could see the generated GLSL for diagnostic purposes.

Here is some context: I'm having trouble with this (reduced) code for a 2D fragment shader:

```
vec3 s = tex(TEXTURE, UV).rgb;
s = pow(s,  1.0);
COLOR = color(1.0,1.0,0,1.0);
```

If you comment out the 2nd line it works. Otherwise, you get nothing + a strange glitch that lasts for a moment.

**Comment by akien-mga** [comment]
Please open one issue per suggestion/bug next time, as having several different topics in the same issue makes it harder to address as a whole.

**Comment by seadra** [comment]
Okay.
As for this issue, scratch other stuff. I'm only asking for an "option to show generated GLSL code". This should help tracking the shader codegen issues.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
