### ISSUE TITLE
Subviewport doesn't draw in parent control

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13271]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux mint 18.2 (ubuntu16.04) godot master (mono support)

**Issue description:**

The subviewport feature does not seem to work like it is documented here http://docs.godotengine.org/en/latest/learning/features/viewports/viewports.html#sub-viewport ?

> if the viewport is a child of a control, it will become active and display anything it has inside

I can't get it working, and in the demo project they use a sprite, and some code to forward texture between viewport and sprite.

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by djrm** [comment]
now it only renders to viewport container, and it does not render automatically in sprites, i guess the docs have to be updated

**Comment by akien-mga** [comment]
Two things:
- The docs should be updated as mentioned above
- The editor should show a warning/hint when a Viewport is in the SceneTree without correspnding ViewportContainer as parent (see e.g. the warning system used by CollisionShape when instanced without a CollisionObject)

**Comment by reduz** [comment]
keep in mind that, for sprites, the issue was fixed.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by KoBeWi** [comment]
The docs are already updated (see https://github.com/godotengine/godot/issues/15737#issuecomment-478374461). I don't think we need the warning, because there are multiple ways to display a Viewport (like ViewportTexture, which can be assigned in a script) or you might want to not display it at all. We could warn if the Viewport is a child of non-ViewportContainer Control node, but it's unlikely someone would try this anymore.
