### ISSUE TITLE
Deleting script with external file manager makes editor to continously ask for file reload

### ISSUE THREAD

**Issue by Max9403** [godotengine/godot#1334]
This only happens when the script is still open inside godot, if the scripts windows is closed manually it is resolved (this resolves the constant asking to reload but references to the file persist)

When a script is deleted manually from the file system, godot detects that something happens to the file and continuously prompts to reload the file however it no longer exists. The file is recreated if the project is reopened.

(running crunchbang sid)

Errors are returned in command line (test.gd being the deleted file):
```
ERROR: _get_modified_time: Method/Function Failed, returning: 0
   At: drivers/unix/file_access_unix.cpp:233.
ERROR: set_path: Another resource is loaded from path: res://erro.gd
   At: core/resource.cpp:177.
ERROR: load_source_code: Condition ' err ' is true. returned: err
   At: modules/gdscript/gd_script.cpp:2017.
ERROR: load: Condition ' err!=OK ' is true. returned: RES()
   At: modules/gdscript/gd_script.cpp:2648.
ERROR: load: Failed loading resource: res://test.gd
   At: core/io/resource_loader.cpp:204.
ERROR: _reload_scripts: Condition ' !rel_script.is_valid() ' is true. Continuing..:
   At: tools/editor/plugins/script_editor_plugin.cpp:522.
```

**Comment by kubecz3k** [comment]
Currently in 2.0 alpha in case of file modification or deletion the window will appear with 3 possible actions "resave" , "reload" or "cancel". If the file is deleted "reload" do nothing and the prompt will reappear. "Resave" saves this file on the disk again. If we decide to close project after deleting file it's resaved on the disk. 
Not sure what be proper behaviour should be but it seems there is no sense in this case for "resave" button since it doesn't do anything. 
Maybe in case when editor detects that file that's loaded into memory get deleted by user from outside of the editor there should be an option to "reload current scene". This way another prompt would appear "Scene failed due to missing dependencies" and this prompt is giving us an option to fix dependencies.

**Comment by reduz** [comment]
I was testing and this no longer seems to happen, closing
