### ISSUE TITLE
Erratic PathFollow2D movement

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#13361]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0beta d992eb1

**Issue description:**
Movement along path2d is jumpy and erratic:
![pathtest_r](https://user-images.githubusercontent.com/3812514/33306732-8fa8d2f6-d3c8-11e7-8c9d-0b4709e8a564.gif)
Problem is also visible in the editor when manually adjusting the offset:
![pathtest_i](https://user-images.githubusercontent.com/3812514/33306751-a343dc0c-d3c8-11e7-945d-8f319866eb5e.gif)

Problem seems to have arisen within the last week or so, as I was working on a project using PathFollow2D that wasn't exhibiting this behavior prior to that.

**Steps to reproduce:**
Draw a Path2D, add PathFollow2D and Sprite for visibility.
Drag the "Offset" or "Unit Offset" sliders in the Inspector.

**Comment by eon-s** [comment]
Can you check if happened before #13049?

**Comment by cbscribe** [comment]
Indeed, reverting that change goes back to smooth following behavior.

**Comment by eon-s** [comment]
I see, but reverting should be the last thing to try, parallel transport is supposed to fix an issue concerning the transition between last and first points.

This bug seems related to something in the transform when apply that transition, should be tested on 3D too with locked z axis to see if everything is ok there.

**Comment by akien-mga** [comment]
CC @tagcup since the bug was caused by #13049. (*Note:* I know you decided to switch to Unity for your current project, so feel free to tell me if you'd prefer not to be at-mentioned in issues related to your past contributions - still, it's of course much easier to get an issue fixed when the author is around :))

**Comment by tagcup** [comment]
Looks similar to #3713 except this is not just rotations but position.
I can take a look if there's an example project, shouldn't be hard to fix.

**Comment by tagcup** [comment]
But to reiterate #3713, you *will* get jerky rotations if you don't have a smooth curve like in the picture above in the original post.

**Comment by cbscribe** [comment]
Here's a test project. It's especially apparent if you change the offset in the Inspector, but you can see it both in the smoothed and sharp intersections.
[path_test.zip](https://github.com/godotengine/godot/files/1515290/path_test.zip)

**Comment by tagcup** [comment]
I looked into it a bit but it's not making any sense.

If I do set_rotation followed by a set_position, rather than doing it with set_transform, things work OK. Something makes things go awry set_transform, could be some bug elsewhere.

Anyway, I also changed the h_offset/v_offset thing to match the old behavior since you were complaining about it too. In 2D, I'm guess it means how far we should be away from the line, in the global XY plane.

In 3D, I don't know what it means. Yes, we have a h and v offset, but in what plane? In the local XY plane of the object (which is the current behavior and differs from the 2D behavior, in case anyone want to work on that) or a particular global plane? The old behavior for 3D (before parallel transport), by the way, was different because the object's orientation was locked with the path at each point, so I can't say it was better either.

**Comment by tagcup** [comment]
To be clear, for 3D, the old behavior for h_offset v_offset was to shift it on the plane which runs perpendicular to the path at that point; since the object's z-axis was also force-aligned along the path as well, it may make sense, but since they're not locked anymore, the usefulness of the plane that is determined by the object's orientation is questionable and h_offset/v_offset probably isn't much useful on their own. It could make sense to add a new parameter to PathFollow3D to define a (global?) plane on which h_offset/v_offset displaces.

**Comment by IAmM1ne** [comment]
Hi! In Godot 3.0 beta 2 it still does not work properly! I am trying to make “Dodge the Creeps” (step by step) and it still works erratic. My system is macOs.

**Comment by cbscribe** [comment]
I just tested with the reference version and I'm not seeing any problems.

FYI, I put the version used to make the tutorial here: https://github.com/kidscancode/Godot3_dodge

Please check your code. If you find any issues with the written docs, open an issue at https://github.com/godotengine/godot-docs

**Comment by IAmM1ne** [comment]
Hi! you are right, it works properly. I had a mistake in my code.

Sorry and thanks!

2017-12-27 18:20 GMT+01:00 Chris Bradfield <notifications@github.com>:
