### ISSUE TITLE
Area and plane collision shape signal not working 

### ISSUE THREAD

**Issue by carlosmarti** [godotengine/godot#13385]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10
Godot 3.0
Nvidia Gtx 660

**Issue description:**

Area3d did not send signal when other body object passed through the collision shape set as plane. I expected for the signal to be work when a object passed through it.

**Steps to reproduce:**
add Area3d 
attach collision shape 
set collision to plane 
set signal for Area3d to body entered
Have a different Physics object touch the Area3d

**Link to minimal example project:**

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
