### ISSUE TITLE
Add Abstract override support for Script types.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#13401]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0

**Issue description:**
Scripts already have a virtual `can_instance()` function to be implemented, but the implementation in the derived Script types never seem to take into account information that users can define for the Script.

    // modules/gdscript/gdscript.cpp
    bool GDScript::can_instance() const {
        return valid || (!tool && !ScriptServer::is_scripting_enabled());
    }
    
    // modules/visual_script/visual_script.cpp
    bool VisualScript::can_instance() const {
        return true; //ScriptServer::is_scripting_enabled();
    }

I would've expected some sort of `call("can_instance")` statement to be included in these implementations so that users can define for themselves whether a Script is instanceable (or just a boolean flag that shows up as a `CheckButton` in the case of VisualScript).

It doesn't make sense for a method of this kind to be exposed to the scripting API, but for the method to effectively be an "is this script valid" function, which, if you are calling it validly through the script, is obviously going to be true. The only way for it to have any meaning would be to create implementations for all types of scripts that take into account some scriptably-overrideable method of evaluating the function.

Edit: By the way, I tested whether overriding the function in GDScript, static or non-static, true or false, would have any effect on my ability to call `.new()` on the `Script`...it had no effect whatsoever. So, that's probably a bug if nothing else.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
