### ISSUE TITLE
Mouse Cursor lag

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#13423]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux debian buster, Godot engine 2.1.4, AMD Radeon R9 290 (AMDGPU + radeonsi)

**Issue description:**

Since [this bug](https://github.com/godotengine/godot/issues/6929) has been closed, and I still need to create a custom cursor for my project, I (re)open a bug about the laggy mouse cursor.

As you can see, the custom cursor is one frame late.
![mouse-lag](https://user-images.githubusercontent.com/6616005/33455802-3a4ad1ae-d5eb-11e7-8efc-f57c310b4e9a.gif)

**Steps to reproduce:**
1. Create a new project
2. Create a new scene with only one Control node inside. Save it as main.scn and put it as autoload in the project.
3. Attach the following script to the node
```python
extends Control

# Declare a custom cursor here
const MOUSE_CURSOR = preload('res://icon.png')

func _ready():
  Input.set_custom_mouse_cursor(MOUSE_CURSOR, Vector2(11, 5))
  Input.set_mouse_mode(0)
```
4. Run the scene

**Comment by lakpo** [comment]
it's really annoying for a desktop game

**Comment by Pegus1936** [comment]
this issue was reported over a year ago IIRC and it's still not fixed

must not be "high priority" ![](http://forums.d2jsp.org/html/emoticons/rofl.gif)

**Comment by Calinou** [comment]
Once merged, this [pull request](https://github.com/godotengine/godot/pull/12814) will solve this issue as hardware cursors do not suffer from an one-frame delay.

**Comment by MoriMalandro** [comment]
(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by Hello445** [comment]
This is not a high priority at all.

Voting to close, no need for this feature.

**Comment by xsellier** [comment]
Since I'm working on a patch, it's a bit frustrating to read that @Hello445.

**Comment by Hello445** [comment]
@xsellier I'm being facetious sir. See this:

(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by JuanDidNothingWrong4** [comment]
This is not an issue whatsoever. The lag is completely normal for games when using a custom mouse cursor image.

Voting to close (Juan told me on reddit)

Sorry!

**Comment by MoraleIsNone** [comment]
@lakpo It's also a core functionality (low level as fuck) for a game engine, however, Juan continues to push it for 3.1 and beyond. When it should be done ASAP, because it should be essential for all game engines. Hell, Game Maker, Love2D, and even fucking Atomic Game engine support hardware level mouse cursor. If $3,000/m is not enough, I don't know what is.

**Comment by JuanNeedsToRepent** [comment]
Not a high priority at all, voting to close this... Low level hardware cursor functionality (apparently to Juan) is not important.
