### ISSUE TITLE
Project templates (ability to create project from the template, fps/platformer/rts etc)

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1343]
Well, I think to myself that Godot should write games itself. Really, why not?
Sometimes I'm really lazy to write any games, really. I'd like to select from menu
Make FPS game/Make 3rd view game (3rd view camera setup)/Make 2d RPG tiled game/etc.,
optionally fill-in content, and sell it^W^Whave some fun.
Any thoughts?

**Comment by okamstudio** [comment]
Yeah i noticed las month when i got unreal that it has several simple
templates, should work with n spmething similar

**Comment by not-surt** [comment]
This plus a library of drop-in ready-to-use elements would go a long way to making Godot more newbie friendly.

**Comment by TheoXD** [comment]
Definitely a better idea than turning godot into a constructor. In that case some sort of dependency is needed, so that the project could include additional projects with some pre-made stuff in them.
So there can be an additional zip package to install, "game templates". Project manager can have two tabs, recent projects (current one) and actual game templates that when you click on any of them - it creates a copy of that template in a user defined folder. Template preview can be a nice wide screenshot, because there is no need to show the path or name.
All of that should probably wait until after 1.2

**Comment by slapin** [comment]
I think ability to generate "template project" from existing one, and generate project from template
is enough (with some fancy things to specify in templates during project generation).
At least this should be done and then improved IMHO. Probably ability to process templates with scripts during generation, should be implemented from start.

**Comment by adolson** [comment]
somewhat similar/related to #954

**Comment by kubecz3k** [comment]
Archived https://github.com/godotengine/godot/issues/954 since discussion here seems to be greater..
@adolson wrote there:
*Every time I make a new project I have to go through the settings and change everything in there, then in the input map, etc. It would be nice to let us create a project template, then save it somewhere in ~/.godot/skeleton/ or something, and have that used as the defaults whenever we start a new project.
Bonus: let us edit the default GDScript template as well.*

**Comment by akien-mga** [comment]
This has been implemented in 2.1-beta via the asset sharing platform. It likely still needs some polishing (and first of all actual templates to use), but that should be addressed in new specific issues.

**Comment by slapin** [comment]
Any documentation? I can't consider it implemented until someone can
actually use it. This all asset
sharing is still some under-carpet business to me. Or under-advertised for
that matter.

**Comment by akien-mga** [comment]
You can already use it if you host your own instance of the server and populate the database: https://github.com/godotengine/asset-library
For the official instance, we have some concerns of security and quality that we want to address first before advertising the implemented features. You can already download the game Minilens from the project manager, and replacing this full game by project templates is just a matter of having content to put in the database.
