### ISSUE TITLE
Sometimes when a scene is previewed, custom actions doesn´t load

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#13444]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot3 beta 1, win7 32bit

**Issue description:**

Second time i execute the preview of a scene with a custom action (configured in editor) godot doesn´t load this action, but the input ("mouse button") is handled.

More info: 
Scene with custom action catched throws this error 116 times:
Expected 'shader_type' at the beginning of shader
Condition 'err!=OK' is true.

Scene with custom action not loaded doesn´t throw any error.

I think that the project doesn´t have any shader. If you delete the particle2d attached to the "godotlogo-bunny" this error stops (is related with particles2D material), but intermittent "not catched" actions still happends.

More more info (and very strange):

When error happends, fps seems to be cap to 60, like it has V-sync on, no matters is V-SYNC is ticked or not. (And V-sync doesn´t seem to work... i open other issue with that).

**Steps to reproduce:**
Open attached project and execute main.scn with F6 (preview scene not entire project) several times, in any of the executions, custom action is not loaded. (See the console, the mouse input is registered)
[godot3-ActionsIntermittentFails.zip](https://github.com/godotengine/godot/files/1521246/godot3-ActionsIntermittentFails.zip).
Executing with F5 seems to be OK (I do that 20 or 30 times and can´t reproduce), is something related with scene preview, custom actions and "strangely" V-Sync.

#

**Comment by JuanDidNothingWrong2** [comment]
(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :( 
(Since Noshyaar keeps closing this, I am going to continue to post it until one thread remains visible for discussion, no need to censor)

![](https://i.gyazo.com/364f1b11bc57924374d0a8c81df1eeab.png)

Lead developer sent this message after a user was giving his honest feedback via this [reddit thread](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqk9nel/).

They also said (I kid you not) -- giving feedback is "**bullying**",  a "**professional whiner**", and "**ranting**". Reduz's passive aggressive tone and insulting behavior is rampant there.  I already terminated my patreon account because of this, and not saying you should either (FLOSS projects) are great, however, for the lead developer to act like this towards people giving feedback.. is not okay!

Let me re-iterate, not saying that you should stop giving feedback, but I just want this message to be seen across github and reach as far as possible. Because this kind of communication and how the lead developer treats a regular Godot developer is not right at all. I've never seen this behavior from a FLOSS project lead developer.  It's a shame, because the guy giving feedback is just a random person anyway, and the way the project managers and lead developers took it so personally like it was an attack (when it wasn't), means the lead developers/contributors are possibly not viewing your issues with the right mindset.  

Also, after reading the last paragraph from [this post by akien](https://www.reddit.com/r/gamedev/comments/7gmtxl/godot_30_beta_1_is_there_right_in_time_for_ludum/dqlqj2v/)
> From here on, we will avoid responding to xxx's threads on the various Godot communities, and focus instead on the huge amount of constructive feedback and bug reports that we get from other users. This will likely overlap with some of the issues mentioned above, which will thus be fixed eventually, but we won't accept being bullied into working on them now when we have different priorities. Users are free to disagree with our priorities, but in the end the contributors are the ones making the call.

He's saying they will now favor/prioritize issues based on the user reporting it, and not the issue itself. (Extreme prejudice), which will not be good for the project because the issue should be irrelevant to the user reporting it. Just because if a user who has a snotty attitude that is reporting a huge client crash error, doesn't mean that client crash error should not be taken lightly.



He's also stating that anyone giving hard feedback is now "bullying" them. Which is not true whatsoever.

Just wanting to post this to get the word out there, hopefully some things change. @reduz @akien-mga  This is just unbelievable :(

**Comment by vnen** [comment]
Can you test again with the latest master? This likely have been fixed by #13989.

**Comment by Ranoller** [comment]
Problem is semi-fixed.  Custom action not connecting not happend yet (Godot3 win64 release_debug compiled at 06_12_2017 20:00h), but custom action connecting delays between 70-90 frames from start game loop (Input can be catched from frame 0-1, actions not). If this is expected behavior I close the issue. Thanks.
