### ISSUE TITLE
Multiple yield()s cut off code

### ISSUE THREAD

**Issue by Spooner** [godotengine/godot#1386]
After a certain number of yields (which seems to be inconsistent, can be 2 or more that triggers the end in my tests), the remaining code in the coroutine is not run!

This script is run in a completely empty project (attached to the root node):

``` gdscript
func coroutine():
    print("2-1")
    yield()
    print("2-2")
    yield()
    print("2-3")
    yield()
    print("2-4")

func _ready():
    print("Starting")
    var co = coroutine()
    while co.is_valid():
        co.resume()
    print("Complete")
```

The output is:

```
Starting
2-1
2-2
Complete
```

**Comment by reduz** [comment]
interesting, will give it a check as soon as i can

**Comment by akien-mga** [comment]
Is this bug still reproducible?

**Comment by akien-mga** [comment]
I can reproduce the bug in the current master branch with the above code snippet.

**Comment by bojidar-bg** [comment]
I can confirm that this code snippet does not work in master, but it is actually incorrect.
Here is a slightly-modified _working_ code: (Original changed lines are commented out)
```gdscript
func coroutine():
    print("2-1")
    yield()
    print("2-2")
    yield()
    print("2-3")
    yield()
    print("2-4")

func _ready():
    print("Starting")
    var co = coroutine()
#   while co.is_valid():
    while co and co extends GDFunctionState and co.is_valid():
#       co.resume()
        co = co.resume()
    print("Complete")
```


Therefore I think this should be closed, since `GDFunctionState::resume()` is [explicitly stated in the docs](http://docs.godotengine.org/en/stable/classes/class_gdfunctionstate.html?highlight=returns#class-gdfunctionstate-resume) to return the new state if `yield`-ed again (not sure if it was at the time the issue was opened).

> This function returns what the resumed function call returns, possibly another function state if yielded again.
