### ISSUE TITLE
I have a few suggestions to help improve Godot

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#13942]
Here are a few suggestions:

- Integrate Blender (a 3D modeling software) tools with Godot. This is very useful so that users can modify any assets on the fly without having to reimport the items (since Blender likes to have the Z axis placed in a vertical axis instead of using the Y axis, make a small change to replace the Y and the Z axis)

- Have a _learning mode_ in Godot. This includes teaching users how to create models, programming using any of the supported languages, setting up the scenes etc. The teaching method should be similar as to CodeCademy. This is important in order to make it as easy to as possible for new users to easily get familiar with Godot, thus resulting higher attraction towards this game engine.

- Integrate a tool in Godot that allows users to convert their Unity made games to Godot if people wanted to start using Godot.

**Comment by leoddd** [comment]
Integrating blender is uh.. not really needed. Just use Blender. If anything, Godot would likely get its own tools, not blender's.

A learning mode sounds like a real nightmare to maintain. Just read the docs, look up tutorials and demos and use your noggin, there really isn't much that's so difficult to figure out that you would need to be handheld through it on your first pass.

Integrating a Unity converter is a silly idea that'll never happen. Someone can make an external program for that, sure, but that has nothing to do with Godot's codebase itself (and will likely never happen either because it'd be incredibly complex).
If people want to start using Godot they should just create new games in Godot. If you started making it in Unity, then keep using Unity or port it over manually if you absolutely need to (you probably don't).

**Comment by vnen** [comment]
I suggest you first read [our FAQ](http://docs.godotengine.org/en/stable/about/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think), in the linked section which is about suggestions.

Anyway, your addressed points aren't really feasible:

* Integrating Blender inside Godot is pretty much impossible and not even needed. Godot 3 (soon to be released) has automatic reimport of assets.
* What this "learning mode" consist of? Creating models is outside the scope of Godot. It's easier for the users to just follow the documentation guides. We intend to improve the documentation.
* Converting from Unity ain't gonna happen, at least not in any official capacity. Unity and Godot follow different paradigms and automatic conversion would be very hard if not impossible. It would also need to be updated in every Unity and Godot release. We prefer to use the time to document the differences between the engines and provide a transition workflow that users can follow manually.

**Comment by NathanWarden** [comment]
I think #2 would be a good idea to implement at some point in the future in the sense of maybe having a splash screen link to a tutorial site or a YouTube playlist.

I would vote against 1 and 3 though.

#1 would probably have to be done in such a way that it requires the end user to have Blender installed since you can't embed the code due to it being GPL. I would vote against this simply because it means that team members who don't use Blender also have to install it. It would probably lead to creep into other 3D application like Max and Maya as well which means that when a client project gets handed off to another contractor they suddenly need to install Max and Maya as opposed to the project just working. I'm saying that last point from experience. This is a feature that a lot of people praise Unity for but it's really only good for individual developers but is detrimental to team projects.

#3 I'm writing a script compatibility library from Unity to Godot (https://github.com/NathanWarden/UnityGodotCompat) which will help you bring over quite a bit of code, especially isolated components, but it's very clear to me that converting scenes and scripts wouldn't get you the results you would like to have. Many things can be translated, but the end result would be *very* buggy... better to start from scratch on your scene setups.

**Comment by djrm** [comment]
a native blender importer would be cool though.....

**Comment by mhilbrunner** [comment]
I agree that 2 and 3 are ill-advised for the stated reasons.

However, I think you all misunderstand what was meant by "Blender Integration". I first wanted to respond how you did, however, after reading it:

Requested is just a Blender importer, so you can live-edit a file in Blender and have it reimport automaticall without having to do/configure anything.

I think thats a cool idea.

**Comment by QbieShay** [comment]
Hi, what kind of blender features you expect to be present in Godot? I understand that you want an automatic .blend importer, but what exactly you'd expect to be transposed in godot? Would it have to support particle, physics, armor constraint, materials?

I am not sure that it would be a great idea, because you would need to specify which part of the blend files are blend only and which parts are not. Users would expect cloth based animation to work, but afaik that is not possible

**Comment by Raj2032** [comment]
Hi Qbie,

I mean like simply copying all the features Blender has and implement it in
Godot such as the ability to rotate, scale, create, add materials etc.

**Comment by QbieShay** [comment]
Which Blender features? Like **ALL** of them?

**Comment by Raj2032** [comment]
Yes all of them (except to their built in game engine as it is worse than
Godot), like isn't it possible to copy and paste all the features from
Blender?

**Comment by QbieShay** [comment]
I am sorry, but that's not how software works. Don't get me wrong, it would be awesome, but sadly that's not possible.

You also need to consider that blender is not focused on realtime rendering, just try to enable cycles render and you will see how long it takes.

Do you know exactly which features you would like to see in Godot? Do you have a precise list?

**Comment by Raj2032** [comment]
Do correct me if I am wrong but somebody created this
http://www.rpginabox.com which integrates Voxel with Godot.

Here is a list of what I would like to see,


   - The ability to do modeling just like Blender
   - The ability to create animations just like in Blender
   - A 'learning mode' for Godot
   - The ability for Godot to read Blend files just like in Unity

**Comment by reduz** [comment]
@Raj2032 There is no need to replicate the whole Blender in Godot. As long as scenes, materials and animations can eventually exported from Blender to Godot it should be good enough.

Maybe you should also give a chance to this - http://armory3d.org/ which seems to work as you describe.

**Comment by Zireael07** [comment]
@Raj2032: A learning mode is possible. Not too sure about blend importer because it depends on licensing.

For the other two points, just use Blender. Godot is a game engine, not a modeling program.

**Comment by QbieShay** [comment]
@Raj2032 @Zireael07 i don't see how Godot would need a leaning mode. 
Godot docs are well made, maybe they'd benefit from a little bit of search engine optimization, but that's another topic of discussion.
Godot even has a Unity3D to Godot guide ( a little bit outdated i think ).

Why would you need a .blend importer? You can just re-export yout 3D stuff in Collada or glTF, it's one click away exactly like saving.

**Comment by Zireael07** [comment]
@QbieShay I didn't say Godot needs one, I said it's "possible". And I agree that Godot docs and guides are fairly good!

**Comment by marsmoon** [comment]
If there was a tutorial teaching how to program a simple game from scratch that would be pretty useful to people who have never made a game before. It could be step by step, but it could also encourage people to look into the documentation. Everyone would be able to make a game in Godot! Imagine how could that would be.

**Comment by MoraleIsNone** [comment]
Has a few suggestions, but gets downvoted -3 and publicly shammed.

Lovely community here

**Comment by marsmoon** [comment]
If you read the responses you will notice that everyone gave an explanation to why implementing those features might not be a good idea.

**Comment by leoddd** [comment]
The Godot docs have that.

**Comment by marsmoon** [comment]
Of course, but it's not an interactive tutorial. Raj2032 mentioned https://www.codecademy.com.

**Comment by mhilbrunner** [comment]
Closing this for now, as:
- this is not likely to be implemented or feasible (see vnen's comment and others)
- this contains multiple non-related issues (which are quite vague as well)
- there does not seem to be much support for this from the discussion

If you feel some of this still needs to be discussed, please ping me to reopen this or better create one issue per singular feature request.
