### ISSUE TITLE
Visual scripting : refresh problem

### ISSUE THREAD

**Issue by matrem** [godotengine/godot#13969]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
linux mint 18.2, master 

**Issue description:**

There is some node refreshes problem : 
- change a variable name or type : the node won't refresh
- add a call to a function and then change the function name or ags : call node does not refresh
- vector3 construct node by default construct a null vector even if the node show (0, 0, 0), One have to edit each 0 field and validate them in order to have a vector3(0, 0, 0).

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by fire** [comment]
Renaming a variable does not change nodes in the graph to the new name. Bug still exists.

Same as above for functions.

Third point is fixed by #22944.

**Comment by fire** [comment]
The first two points are better described by https://github.com/godotengine/godot/issues/19954
