### ISSUE TITLE
Monitor ID in Editor Settings is different from monitor ID in Windows/nVidia Control Panel

### ISSUE THREAD

**Issue by amirea** [godotengine/godot#13975]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10, Godot v3.0 beta 1 win64, nVidia GeForce GTX 1050, driver 388.31

**Issue description:**
Setting same monitor as the editor, for the game window works as expected but setting a specific monitor (1, 2, etc.) displays the window on the wrong monitor. This is the "function":
set 1 -> displayed on 3
set 2 -> displayed on 1
set 3 -> displayed on 2
set 4 -> displayed on 4

**Steps to reproduce:**
Set the monitor to display the game window to a specific number monitor in Editor>Editor Settings

**Link to minimal example project:**
n/a

**Comment by Calinou** [comment]
@amirea Can you still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

Note that I'm not sure whether this can actually be fixed. Maybe the NVIDIA Windows driver uses its own monitor ordering system.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
