### ISSUE TITLE
Change the parameter types in collision events (Mono API)

### ISSUE THREAD

**Issue by Vega-KH** [godotengine/godot#14345]
EDIT: per discussion below, a more reasonable solution is to change the parameter types on collision signals. Basically, the body_entered signal on a RigidBody2D or Area2D should return something like a CollisionObject2D, rather than a Godot.Object, which must always be downcast to be useful. Same for 3D collision objects.

------------ end edit -----------------

In the Mono API, I think there should be virtual functions in the base Godot.Object for all of the functions that are common to inherited objects.  As it is now, an object has to be downcast to the correct type to do anything with it.  For example, this SHOULD work:

`
GetNode("tree").SetTransform(new Vector2(0, 0));
`

But that doesn't work, because GetNode returns a Godot.Object, which doesn't have a SetTransform method. So instead you have to down cast it, something like this:

`
(GetNode("tree") as Sprite).SetTransform(new Vector2(0, 0));
`

And maybe that doesn't seem too bad, but what if you don't know in advance the type of object it will be (for example in collisions?) You have to call GetType, then downcast it to the correct type before you can doing basic things like SetTransform, QueueFree, etc.

Some examples of functions I would like to see as virtual functions in the base Godot.Object:
GetTransform, SetTransform, GetScale, SetScale, GetRotation, SetRotation, GetName, QueueFree, AddChild, AddToGroup, GetChildren, GetChild, Call, CallDeferred, etc.

**Comment by Zylann** [comment]
You may not be sure of the type you get, but you are at least *expecting* a given type (same in GDScript). So if you have a `OmniLight` or `MeshInstance`, you can downcast to `Spatial` if all you need is to change the transform.

I'm against "bloating" the bound Object class with functions this way, it could cause confusion, and even in engines like Unity you need a cast (nicely hidden behind GetComponent<T>()).

I think GetNode() should `at least` give a `Node`, because there is just no way for it to return something higher in the class hierarchy (like Object).

**Comment by Vega-KH** [comment]
You're right. After further thought, there is no reason to have these on the base object.  What would be more beneficial is this:

1. On collisions, return the lowest common denominator. The OnBodyEntered method of CollisionObject2D currently passes in a Godot.Object. But isn't it correct to say that the ONLY things that can collide with a CollisionObject2D are other things that inherit from CollisionObject2D? So why not pass that, instead of a base object. Or maybe even pass a Node2D. This would drastically reduce the number of downcasts needed.

2. Add SOME additional virtual methods on node, that are common to every inherited object, such as set/get rotation, translation, scale, etc. It doesn't seem it would clutter the node API that much and would simplify common tasks.

**Comment by Zylann** [comment]
I still don't agree with 2), not every node has a transform, and there are multiple types of transforms anyways, and my idea of extension methods still elegantly solves this.

**Comment by neikeq** [comment]
> 1. On collisions, return the lowest common denominator. The OnBodyEntered method of CollisionObject2D currently passes in a Godot.Object. But isn't it correct to say that the ONLY things that can collide with a CollisionObject2D are other things that inherit from CollisionObject2D? So why not pass that, instead of a base object. Or maybe even pass a Node2D. This would drastically reduce the number of downcasts needed.

I can't find `on_body_entered` anywhere, nor a `body_entered` signal anywhere? Did you mean RigidBody2D's `body_enter`?

> `(GetNode("tree") as Sprite).SetTransform(new Vector2(0, 0));`

I was thinking of adding an alternative generic method for (at least) `GetNode` to improve this so you could do: `GetNode<Sprite>("tree").SetTransform(new Vector2(0, 0));` (well, not really `SetTransform` :smile:).

**Comment by Vega-KH** [comment]
The reason I said CollisionObject2D is because both Area2D and RigidBody2D have a body_entered event, and both inherit from CollisionObject2D. The point is that only descendants of CollisionObject2D  are detectable in 2D collision events, so why pass a much higher level Object?  We know for sure that the other body is at least a descendant of CollisionObject2D. Pass that in instead, it is much more useful.

And you are correct, the actual signal is called body_entered (obviously this is what I was referring to.) I am trying to stick to C# naming conventions so I have been renaming my functions as such.

**Comment by neikeq** [comment]
These signals are declared there:

Area2D: https://github.com/godotengine/godot/blob/b38378dd6c963d71d0c1ad40c53b29588e581757/scene/2d/area_2d.cpp#L658
RigidBody2D: https://github.com/godotengine/godot/blob/b38378dd6c963d71d0c1ad40c53b29588e581757/scene/2d/physics_body_2d.cpp#L910
Area: https://github.com/godotengine/godot/blob/b38378dd6c963d71d0c1ad40c53b29588e581757/scene/3d/area.cpp#L703
RigidBody: https://github.com/godotengine/godot/blob/b38378dd6c963d71d0c1ad40c53b29588e581757/scene/3d/physics_body.cpp#L869

As you can see, Area2D already declares `body_entered`'s parameter as a PhysicsBody2D. Looks like the same should be done for the rest (as well as `body_exited`), but I can't say for sure.

I guess the reason for these signals not to be declared in PhysicsBody is because KinematicBody, StaticBody and VehicleBody don't use them.

**Comment by neikeq** [comment]
Oops, wrong issue :)

**Comment by aaronfranke** [comment]
While the signals should be changed to be more specific, for the Mono API specifically, does having a generically typed GetNode method (and GetChild etc) help? https://github.com/godotengine/godot/pull/17720

**Comment by akien-mga** [comment]
Is this still relevant in the current master branch?

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
