### ISSUE TITLE
Document gdignore exclusion for automatic import

### ISSUE THREAD

**Issue by letheed** [godotengine/godot#14369]
Since import is always on and done automatically, it'd be nice to have a project setting to exclude some directories that contain media irrelevant to the game itself. Eg. screenshots, documentation, HTML5 exports, etc.

**Comment by reduz** [comment]
if you add a .gdignore file to a directory, it will be ignored.. I wonder
how this could be better documented

**Comment by letheed** [comment]
Ah! Thanks that's great. Yes documenting that would be good, I'll rename the issue.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by brainsick** [comment]
The first place you're "introduced" to the concept of an asset is [here](http://docs.godotengine.org/en/latest/learning/step_by_step/instancing.html#instancing-step-by-step).  It's completely glossed over as the user is downloading a prepared sample project.  But the first opportunity to introduce the gdignore concept would be here; include one in the sample.  There are a couple other sample projects that it could be added to in the step by step learning series.

We finally get to resources and the file system [here](http://docs.godotengine.org/en/latest/learning/step_by_step/filesystem.html).  Seems like a gdignore mention would be proper?

**Comment by akien-mga** [comment]
Fixed by #964.
