### ISSUE TITLE
set_contact_monitor set to false is not working

### ISSUE THREAD

**Issue by steelxtreme** [godotengine/godot#14393]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

Os: Open Suse Leap 42.2
Godot Version: 3.0 beta [

**Issue description:**

 
Using RigidBody2D I set false in set_contact_monitor and value still true calling is_contact_monitor_enabled()
**example**
[rigidbody2dbug.tar.gz](https://github.com/godotengine/godot/files/1544844/rigidbody2dbug.tar.gz)
](url)
**Steps to reproduce:**

set_contact_monitor(true)

Edit: Update with example, and notice that happens in signal body_entered(
set_contact_monitor(false)
is_contact_monitor_enabled() is returning true

**Comment by karroffel** [comment]
cc @AndreaCatania since this is probably bullet related.

**Comment by AndreaCatania** [comment]
@karroffel bullet is working just for a 3d part

@steelxtreme also if you can, upload a sample project so we can check it easily

**Comment by karroffel** [comment]
@AndreaCatania Ohhhh ups, missed that, sorry

**Comment by akien-mga** [comment]
The debugger tells you why:
![spectacle cj7814](https://user-images.githubusercontent.com/4701338/33821270-877889f6-de53-11e7-8cbd-234555aebbc4.png)

This works:
![spectacle ea7814](https://user-images.githubusercontent.com/4701338/33821311-a91de240-de53-11e7-8f93-01653fd50b63.png)

(you can't check if the value changed in the signal callback itself, since the value will only change for the next physics frame)
