### ISSUE TITLE
"Sort Scripts by Name" does not seem to work

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#14400]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Windows 10. Godot 3 beta 1.

I was a bit surprised to not find an open issue for this, perhaps I missed it?

Sorting open scripts by name simply does not work, new scripts are always added to the bottom of the list when they are opened.

**Comment by volzhs** [comment]
I think "Group Help Pages" also doesn't work after adding functionality to rearrange script list by DND.

**Comment by letheed** [comment]
Noticed this too, new scripts are added to the bottom indeed.

**Comment by CowThing** [comment]
This is still a bug in the current master. The sorting does work if you right click on a script and press "sort". But when opening a new script or new help page it does not automatically sort.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
Script editor is in this file:
https://github.com/godotengine/godot/blob/master/editor/plugins/script_editor_plugin.cpp
