### ISSUE TITLE
focus selection change proposal 

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#14418]
In the 3d view, when you focus on selection, the camera seems to focus on the origin of the selected node. It would be more convenient to focus on the middle of the bounding box, if the node has objects that have spacial characteristic such as meshes, particles, etc. That way when you focus on selected, the entire object is in focus and not just the lower part of it. 

Another thing that I would like to bring into light here is the camera zoom amount, when you hold ctrl + mmb, you adjust zoom level. That concept is a little foreign to me, not really sure why that would be something that you would want to adjust (maybe someone can explain this to me), but if you zoom way out and focus on the object, camera keeps the zoom distance to the object, and vice versa, zoom way in and when refocusing on object, camera is super close to that object. The zoom out part seems logical to me, but I think it would be nice if you zoom way in and try to refocus on a particular object, camera zooms out enough to completely frame the bounding box of selected node.

**Comment by vnen** [comment]
Please use capital letters when you begin a sentence and split different topics into paragraphs. It's quite hard to read the way the text is formatted.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
