### ISSUE TITLE
Mesh splitting to reduce memory consumption by morphing+skeleton

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#1442]
Skinning buffer for meshes with skeleton tends to be enormously large. Some optimization like mesh splitting during import is required for more effective memory usage.

Example: Hman mesh controlled by skeleton and a few small morphs, mesh size 23K verts, consumes 8MB RAM.

**Comment by reduz** [comment]
this is generally done by artists. Apps like Maya and Max allow you to
split and keep normals. I think Blender added that recently?

**Comment by bojidar-bg** [comment]
Bump, this is terribly stale. It this something that we should support (do other engines support it?), or is it something that artists should do?

**Comment by slapin** [comment]
Well, Unity supports it as I can import Makehuman models directly and they
work out of the box.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
