### ISSUE TITLE
Mouse input in editor not working

### ISSUE THREAD

**Issue by MrHankey** [godotengine/godot#14427]
**Operating system and version:**
x64 Ubuntu 17.10 (using X.org not Wayland), master@2c6af835a1fa5518e95d874559bdcd90ce5cb24e

**Issue description:**
The editor has recently stopped registering any mouse input events (clicks, mouse over). Keyboard works fine.

I've tracked the issue down to the following commit: [b87abeb9f9976b2b4559753de3a3b95e29ce043c](https://github.com/godotengine/godot/commit/b87abeb9f9976b2b4559753de3a3b95e29ce043c)
The issue does not occur when compiling master before that.

**Steps to reproduce:**
Compile from master (Options used: platform=x11 target=debug)
Start editor
Mouse input should already be broken in project selector.

**Comment by akien-mga** [comment]
The commit you narrowed down doesn't make sense for this bug (it only modifies iOS stuff), it must be something else.

A current master build works fine for me on Mageia 6/X11.

**Comment by MrHankey** [comment]
I figured as well that the commit seems completely unrelated but strangely enough it is 100% reproducible on my side.

**Comment by DavidMeagher1** [comment]
The same think is happening for me with the current master build on ubuntu 16.4

**Comment by RandomShaper** [comment]
Maybe related to the multitouch implementation. Researching now.

**Comment by MrHankey** [comment]
Ok somehow https://github.com/godotengine/godot/commit/94a573bb3987957f9d63d94a298da0c2e296c878 has changed things for me.

Now mouse input works initially **until** some sort of WM event happens (e.g. clicking the editor window's top bar or buttons, alt-tabing to another application and back). After that the editor looses any ability to register mouse input again.

**Comment by timkrief** [comment]
> Ok somehow [94a573b](https://github.com/godotengine/godot/commit/94a573bb3987957f9d63d94a298da0c2e296c878) has changed things for me.
> 
> Now mouse input works initially **until** some sort of WM event happens (e.g. clicking the editor window's top bar or buttons, alt-tabing to another application and back). After that the editor looses any ability to register mouse input again.

I don't like to comment on a closed issue but what is described here still randomly happens to me randomly some times. It's hard to debug and I have no idea what exactly is causing it. It might be alt-tabbing in and out of Godot. I'm using Godot 3.4.stable on Ubuntu LTS 20.04

**Comment by Calinou** [comment]
@timkrief Does it occur if you use a different desktop environment/window manager? Try installing Xfce or KDE, switch to it and use Godot for a bit.

**Comment by timkrief** [comment]
Before trying that kind of thing, I'll let you know some more details.
- I'm not able to reproduce the issue consistently, for instance, for the time being, it's not happening anymore.
- It might be linked to playing a scene since it's happening a lot when I try to refocus after I played a scene.
- It doesn't seem to be caused by the system or DE/WM, because the input is still taken into account when I try to exit and it displays the exit prompt, or even other kind of prompts (for instance the prompt telling that the scene have been updated outside of godot). I can then interact normally with those prompts/
![image](https://user-images.githubusercontent.com/14089949/141999839-3aa4dc9b-cf80-40c9-823f-675fe599a751.png)
- Godot is definitely not crashed or frozen since I can see animations being played or even resize the window and it will update its size.
- I tried using tab or shift-tab to get keyboard control but this doesn't work
- It's not the click that is not detected but the mouse altogether since it won't highlight things on hover etc.

Hope this feedback is useful. When it happens again I'll do more testing. It usually happens in bursts, no issue for days or weeks and then a full hour with the issue so it might be linked to having a specific process running, window open etc. Despite all the love I have for xfce, I'm not sure I want to use xfce for weeks to potentially have more info on this :sweat_smile: . If I end up being able to find a way to reproduce, I'll test on different configs.
