### ISSUE TITLE
Changing a bone's rest pose does not redraw the bone

### ISSUE THREAD

**Issue by rminderhoud** [godotengine/godot#14517]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Linux, godot 33a59993945fb313309c8a68fe5d6e48b2bd1874

**Issue description:**

- Changing the bones rest pose does not update the current scene. 
- Changing the rest pose and then changing the pose will cause the old rest to be used in pose

**Steps to reproduce:**

1. Create new scene with bone
2. Change rest, bone will not be re-drawn with new rest
3. Change pose, old rest will be used to pose bone

**Link to minimal example project:**
[bone_draw.zip](https://github.com/godotengine/godot/files/1545808/bone_draw.zip)

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
