### ISSUE TITLE
texture.set_flags does not work

### ISSUE THREAD

**Issue by dploeger** [godotengine/godot#14526]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

macOS 10.13.1, Godot3 #bf45e569c 

**Issue description:**
When using a Stream Texture, the set_flags method isn't working. This might be something about the new import workflow, but I'm using that to ensure, that Texture.FLAG_REPEAT is set in my Scrolling Background plugin.

I've attached a sample project, that outputs the current texture flags, modifies them and outputs them again. There's no change in the output value.

**Steps to reproduce:**
* Add a Sprite
* Select an image as a texture (I guess, this creates a StreamTexture)
* in the script use set_flag to alter the texture flags to add the FLAG_REPEAT to it
➡️ No change

**Link to minimal example project:**
[TestSetFlags.zip](https://github.com/godotengine/godot/files/1546040/TestSetFlags.zip)

**Comment by kubecz3k** [comment]
I tested on Ubuntu 17.04, changing texture flags in runtime don't seems to have any impact on the Sprite node in 237be766d4b0247d7ded0a9b85da12a989c561c8:
![repeat_flag](https://user-images.githubusercontent.com/6129594/33845786-dd66895c-dea4-11e7-923a-301d87cd8174.png)

I'm unsure if this is normal in current import work-flow, but since we still have `set_flags` method inside Texture then I assume it should be usable...
