### ISSUE TITLE
UX suggestions for the Pivot tool

### ISSUE THREAD

**Issue by NathanLovato** [godotengine/godot#14563]
For @groud, who opened a poll on Facebook:

```
Hi guys, working on the 2D editor, I have found that you can drag a node's pivot by pressing shift+V (the pivot is set when you click). Just pressing the V key set it directly at the mouse position.
I think this shift+V option is unintuitive and quite useless, and that it would be better just to remove it, and make the V key alone set the pivot when you release it (thus you drag the pivot by holding V).
I just wanted to know if some of you use the shift+V option, or can I replace it by the above behaviour.
```

## The pivot tool now

- The way you set pivot is imprecise at the moment. You often need to nudge it around by a few pixels
- No other interactive tool works the same way where shift + key lets you drag something around. With the pivot it's shift + V

## Suggestion

I'd suggest to try and make it work closer to how the move tool works: `V` for pivot mode, in which mouse clicks, mouse click and drag and arrow keys all move the pivot. The advantages:
1. Works like other modes
2. Can precisely place the pivot with the arrow keys: no need to zoom in a lot anymore, no need to go tweak the position in the Inspector

I'd doubt everyone even knows V changes the pivot's position.  Yet the pivot tool is very important for animation: you've got to place the pivot right on everything you're going to rotate and scale. There are many cases where you don't want to add a skeleton and clutter your node tree: UI, simple background elements... in which case you rely on the individual nodes' pivot. Until you animate a lot you may not see the need for it but as soon as you do it becomes an important tool.

Thanks for your time and help :)

**Comment by mhilbrunner** [comment]
Psst, a word got lost: "tweak the position in the [porperties]"? :)

And yeah, agreed, this would be quite useful.

**Comment by reduz** [comment]
There is a dedicated tool mode for setting the pivot, i have no idea how it can get more discoverable than that..

![image](https://user-images.githubusercontent.com/6265307/33866483-bade5f8c-ded5-11e7-8a16-b23e03489297.png)

**Comment by NathanLovato** [comment]
@reduz True, forgot about it ^^. I just copy pasted a quick facebook reply

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
