### ISSUE TITLE
Function list does not go to the right line if some code is folded

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#14572]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
Godot 3.0 aa5f519

**Issue description:**
If some code is folded, the list of functions below the script list doesn't go to the correct line, it goes to some lines below (I suspect it's the same amount as hidden lines).

**Steps to reproduce:**
* Create a script
* Add multiple functions
* Fold some code
* Click in a function from the list to go (below the folded code)

cc @ianb96

**Comment by voithos** [comment]
I think I found the issue. [This method](https://github.com/godotengine/godot/blob/c68b031b052467096a6d8f059e791facb09d82fa/editor/plugins/script_editor_plugin.cpp#L1333) in `script_editor_plugin.cpp` sets the `scroll_position` of the editor to be the line number, but that's incorrect since some lines might be collapsed.

It seems to work well if we switch it to use `goto_line()` instead of `set_edit_state()`, but then the code gets unfolded (although that actually seems like useful behavior? If you're trying to jump to a function, then ostensibly you also want to see what's in it and/or edit it).
