### ISSUE TITLE
More descriptive default names for built-in scripts in the script editor

### ISSUE THREAD

**Issue by leoddd** [godotengine/godot#14577]
When using built-in scripts, they show up in the script editor as `GDScript(#####)`, which is very non-descript and gets very confusing very very quickly once you have multiple opened at once.

Since they are tied to a single Node or Resource, each of which can only have one Script, I think it would be a lot better if they were named after the path of the object they are attached to.
For example, a script might be attached to the node `@"level/entities/fire 1"` inside a scene called `map1`, so its name in the script editor could be `map1:level/entities/fire 1`, or something to that effect.

Since we're not including the full scene path in the name, there might still be duplicates (imagine two scenes both names `map1` in different directories with the same `fire 1` node), but that is by far better than the current solution in which they all look the same.

If that naming convention seems too long to be useful (some trees nest really deeply), we could probably limit it to only include the first parent of the node, like `map1:entities/fire 1`, which would result in more possible duplicates than the full NodePath, but should still be far easier to oversee.
And if someone truly has two identical Nodes with identical parents in a scene, it might be worth it to branch that setup into its own scene and instance this anyway.

Since there are multiple script types now, we could just put a "fake" extension at the end of the name in the script editor to indicate that for consistency, like `map1:entities/fire 1.gd`.

**Comment by vnen** [comment]
You can set the resource name on the Inspector. Maybe there could be a default name set when creating it.

> Since they are tied to a single Node or Resource, each of which can only have one Script

While this is true, the same script can be used in multiple nodes (yes, even built-in ones). There's no way to reference a node from its script, the connection is one-directional. Well, maybe with the dependency walker, but I'm not sure how that would work.

I don't think duplicate names is an issue. If you have script files with the same name in different folders, they'll look the same in the script editor too.

> Since there are multiple script types now, we could just put a "fake" extension at the end of the name in the script editor to indicate that for consistency, like `map1:entities/fire 1.gd`.

No, the fake extension is misleading. The absence of it is an indication of a built-in script.

----

Built-in scripts are rather discouraged and should be used sparingly if ever. But I guess a default name wouldn't be so bad. Even so, it should be simple: only the node name or at most the scene file name plus the node name (the latter can only be done after the scene is saved, so at first the empty name would be unavoidable).

**Comment by leoddd** [comment]
Oh, the script editor actually uses the resource name? That's good to know and solves most of my issues already!
I suppose simply giving it a more descriptive default name is pretty much the best I could be asking for, then.

**Comment by KoBeWi** [comment]
Just writing here to say that having this feature would be very appreciated. Even if we can change the name, it might be tedious to do this for every single script when there's more of them. However, maybe the name could be configurable, because some people will care about repetitions, while personally I'd need only node name. Also...

> Built-in scripts are rather discouraged and should be used sparingly if ever.

I don't really see why. After using Godot for some time, I think it should be opposite. Lots of nodes need different scripts and almost all of them are used only in this particular node. This eventually creates a huge clutter where you have tens of scripts, some of them have just few lines, and only like 5 of them actually need a separate file, because they are "configuration" scripts or aren't attached to anything, but only inherited. I know it's a matter of managing them properly, but having built-in scripts is sort of management too, right? The only "disadvantage" of built-in scripts I see is that you can't open them directly from file. But if you have hundred of scripts, it doesn't matter if you open them from script file or from scene node.

**Comment by KoBeWi** [comment]
Looks like this issue was incorrectly marked in PR, so it didn't auto-close. It was resolved long time ago.

**Comment by akien-mga** [comment]
Fixed by #18930.
