### ISSUE TITLE
Allow multiple material overrides for a MeshInstance (where underlying Mesh has multiple materials)

### ISSUE THREAD

**Issue by zejji** [godotengine/godot#14588]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**

OS: Windows 10 64-bit
Godot version: Custom build of latest master

**Issue description:**

Currently Godot permits a single material override per MeshInstance.

Where the underlying mesh has multiple materials, it would be very useful to be able to override any of those materials for a specific MeshInstance. This is essential e.g. for outline highlighting (see issue [here](https://github.com/godotengine/godot/issues/13048)).

See also the discussion [here](https://godotengine.org/qa/7350/how-to-change-materials-in-a-single-instance).

**Steps to reproduce:**

Create several instances of a MeshInstance where the underlying Mesh has multiple materials. Attempt to override e.g. the Mesh's second material only for a single MeshInstance.

**Link to minimal example project:**

n/a

**Comment by Zylann** [comment]
I saw a confusing post on QA today: https://godotengine.org/qa/24035/universal-common-effect-shader-material-different-modeling

But it reminded me of this limitation, it would be really nice to have that.

**Comment by clayjohn** [comment]
Not sure what the MeshInstance was like when this was written. But now there is an override per-material in the MeshInstance, it can be set through the editor, or through GDScript with ``set_surface_material()`` (http://docs.godotengine.org/en/latest/classes/class_meshinstance.html#class-meshinstance-method-set-surface-material) This overrides on a MeshInstance basis. I have proposed that this function be renamed for 4.0 due to the confusion between it an ``Mesh.surface_set_material()``.
