### ISSUE TITLE
intersect_ray that returns multiple results

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#14608]
I am using intersect_ray for screen picking. The problem I have is that I don't just want the first object the ray hits, but I want them all, sorted in an array by distance from the start so I can iterate over them and determine which one to pick.

I have to work around this at the moment by doing multiple raycasts and using the exclusion list until nothing more is detected. Obviously this is going to be slower than a singular raycast that would return multiple results.

**Comment by Zylann** [comment]
Maybe you could use intersect_shape with a LineShape, though I'm not sure in Which order the hits will be (though they can be sorted easily witb array.sort_custom)

**Comment by eon-s** [comment]
@Zylann a segment shape, not line.

And ray must return only one result because that are rays for.

**Comment by supagu** [comment]
so Zylann's approach is the legitimate/proper way to do what I want?

**Comment by supagu** [comment]
I stepped through the engine code and noticed that the engine does most of the work already for this.
The difference between a ray_cast and intersect_shape is that intersect shape does not return the intersect point and normal.

So having a method like ray_cast that returns an array of hits I is still very helpful!

**Comment by eon-s** [comment]
Shapes can do that:
http://docs.godotengine.org/en/stable/classes/class_shape2d.html#class-shape2d-collide-and-get-contacts

**Comment by supagu** [comment]
3d shapes? Or just 2d shapes?

**Comment by eon-s** [comment]
2D shapes, 3D do not have that option. 

Maybe PhysicsServer/PhysicsDirectSpaceState can add/expose some extra functions using Bullet, I think it is possible to do something similar to `collide_and_get_contacts` with it.

**Comment by reduz** [comment]
A dirty solution for now could be a while loop that casts ray, and adds
whathever you find to the exclude list and cast again

**Comment by supagu** [comment]
Yea that's what i have been doing to hold me over.

**Comment by jakeonaut** [comment]
The dirty solution of using a while loop and adding objects to the exclude list is currently not possible if your ray ever intersects a GridMap due to https://github.com/godotengine/godot/issues/27282

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
