### ISSUE TITLE
Tile lighting and emissions

### ISSUE THREAD

**Issue by Kyle873** [godotengine/godot#14615]
For reference, I'm currently working with Godot 3.0 Beta 1. My use case for this is fairly simple in nature. I have a bunch of tiles in a TileSet that should have fully or partially lit pixels regardless of how much light is affecting them, given an emission texture to determine the pixels of the texture which should be fully or partially lit.

Now my first idea was to use Light2Ds to accomplish this effect, since this is the kind of thing they appear to be useful for. However, there are two problems I immediately see with this approach:
1. Light2D nodes are not saved into TileSet data like collisions are.
2. If they were saved into the TileSet data, this still brings up the issue of the effect not being achieved properly due to the light being casted "down" onto other nodes which may occupy the tile's space. However, I believe this issue would be resolved via some sort of layering or sorting feature that I may not be aware of currently.

I attempted to write my own shader to solve this problem, but I was unable to do so due to my limited knowledge of shaders and the fact that an unrelated bug may be preventing ShaderMaterials from applying properly to tiles in-game, but working fine in the editor.

My next solution was to have a separate, additive tilemap which I use to manually overlay the emission textures overtop of existing tiles to fake the effect, but this approach seems extremely cumbersome and irritating for the map designer.

Ultimately, I see two solutions to this problem:

1. Light2D nodes are embedded into TileSets. However, this doesn't solve the problem of the effect not being produced properly, but I imagine some sort of layering or sorting could fix that, as I mentioned above. Regardless, this may be useful for other effects or use cases.
2. Allow tiles to have an emission texture along with the regular texture and the normal map texture which the engine knows how to use automatically to create the emission effect.

I'm open to other ideas on how to accomplish this effect or discussing a good way to implement it into the engine in a user-friendly way.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
