### ISSUE TITLE
make editor preserve signal connections when replacing a target node by an other

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#1461]
Hi,

I have a bunch of buttons that have their "pressed" signals connected to the script of the root-scene node.

If, into the Editor, I replace the scene-node by an other node type (for instance Node2D by Spatial node), then, all buttons signal connections are lost, and I have to reconnect them all manually.

It would be cool if signals connections were preserved when a node is replaced by an other into the Editor.

**Comment by ScyDev** [comment]
I noticed this too.

I wouldn't call this a feature request, it's a bug.

**Comment by akien-mga** [comment]
I agree that this would be a nice feature. And when the signal has no counterpart in the new node type, it should show a dialog to notify the user about the soon-to-be-lost connections. Right now I'm connecting my signals preferentially via GDScript due to this annoying behaviour when using the GUI.
