### ISSUE TITLE
Shortcuts menu expand/collapse bug

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#14628]

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by hpvb** [comment]
Closing due to vandalism.
