### ISSUE TITLE
Allow autogenerated lightmap UVs to be added to existing Mesh .tres files

### ISSUE THREAD

**Issue by zejji** [godotengine/godot#14705]
The new lightmap feature is a great addition, but it generates a few workflow issues!

I have an existing project with many *.tres Mesh files which have been generated by extracting (and, from within the Godot editor, adding materials to) meshes which were originally contained in imported *.dae scenes.

However, it appears that the only way to add autogenerated lightmap UVs to these *.tres files is to reimport all of the *.dae scenes, re-save the individual meshes as *.tres files and then recreate the materials (if they have not already been saved to a separate file). This will be a very time-consuming process given the number of meshes in my project!

(Just in case anyone is wondering, the reason I have extracted the Meshes from the *.dae scenes separately is that (a) the *.dae scenes include a lot of unnecessary nodes, such as AnimationPlayers etc., even when I disable animation exporting in the BetterCollada plugin; and (b) I have generated the materials for the Meshes from within Godot.

Have I misunderstood something about the correct asset-creation workflow, or is this the only way to add a lightmap UV channel to an existing *.tres file? If so, it would be great if a feature could be added whereby autogenerated lightmap UVs can be added to existing Mesh *.tres files.

\-----
**Update:** I missed the 'Import Animation' checkbox in the 'Import' dialog, which is enabled by default :( I think the general question is still relevant though, because I still needed to add materials to the Meshes from within Godot and then save the edited Meshes as resources.)

**Comment by Calinou** [comment]
The upcoming [new lightmapper in Godot 4.0](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper) might make this feature obsolete. Please check before opening a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
