### ISSUE TITLE
Int/Float Export hint not stepping correctly

### ISSUE THREAD

**Issue by menip** [godotengine/godot#14718]
Godot 3

**Issue description:**

Ints and Floats are not stepping correctly in export hints.
`export(int, -1, 1, 2) var num`
Expected options: -1, 1.
Actual: 0, 1

**Steps to reproduce:**
Include `export(int, -1, 1, 2) var num` in any script attached to a node, then try to set `num` to something.

**Link to minimal example project:**
[exporthint.zip](https://github.com/godotengine/godot/files/1563901/exporthint.zip)

**Comment by menip** [comment]
I'm trying to investigate this, and currently looking at how scene/gui/range works. Would be great if people could push me in the right direction. 

An observation from testing: seems like max values are correctly stepped from the lowest allowed, but min values are stepped from zero if they are negative. So `export(int, 2, 4, 2)` gives correct possible values of 2,4, but `export(int, -1, 1, 2)` gives 0, 1. 0 actually should not even be part of the possible values.

**Comment by menip** [comment]
Update: Tested right now, and float now skips zero correctly, but int still broken. With `export(int, -1, 1, 2)` 0 is still shows up as on of possible options.

**Comment by menip** [comment]
Tested again in 9e43129
Float one is initialized at zero, which while not in range may be ok default.
Int still not stepping correctly.

**Comment by Chaosus** [comment]
According to http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports there is no export(min, max, step) for integers, only floats have this, note the export(int, 2, 4, 2) now gives you 2,3,4 because third number dont take to account(which I think, is bug and there should be error emitting). Its suggested to use the enum instead stepped integer. @akien-mga Dont know, should I close it, or not, I leave it to your decision, maybe @reduz can describe it better.

**Comment by akien-mga** [comment]
IMO it should be fixed to support `export(int, min, max, step)` properly as well as `export(float, min, max, step)`, since the EditorSpinSlider can handle that.

**Comment by menip** [comment]
What file(s) are exports/stepping implemented in?
