### ISSUE TITLE
Two colliding KinematicBody2D might push one another

### ISSUE THREAD

**Issue by atedja** [godotengine/godot#1472]
Create a scene file that contains the following:
- KinematicsBody2D
  - Sprite
  - CollisionShape2D

Set the CollisionShape2D to a reasonable size (in my case, it was 16x48 as my sprite is 32x96).

From another scene, instantiate this scene using the + button that says "Instance a Node from scene file".  Create two instances of this scene, let's call them A and B, and put them side by side, separated by a couple hundred pixels or so.

Create a script for instance B, and instruct it to move toward A.  This is an example script that instructs B to keep moving to the left:

    extends KinematicBody2D

    var speed = 100.0
    var movement_vector = Vector2(-1, 0)

    func _ready():
	    set_fixed_process(true)
	    pass
	
    func _fixed_process(delta):
	    var motion = move(movement_vector * speed * delta)

Then create another script for A that takes input from player and have it move up and down.

    extends KinematicBody2D

    var movement_speed = 100

    func _ready():
      set_fixed_process(true)
      pass
      
    func _fixed_process(delta):
      if Input.is_action_pressed("ui_up"):
        move(Vector2(0, -movement_speed) * delta)
      if Input.is_action_pressed("ui_down"):
        move(Vector2(0, movement_speed) * delta)

Run the scene.  Wait until B hits A, both objects will collide and stop moving.  Then wiggle A by pressing up and down repeatedly, you will notice B will slowly push A on the X axis to the side, even though A isn't supposed to be moving along the X axis.

**Comment by eska014** [comment]
This is intended behaviour, see https://github.com/godotengine/godot/issues/3719#issuecomment-184716900:
> This is not a bug, just don't move the platform with move() if you don' t want collisions to affect it. Set the transform normally from code or animate it with an AnimationPlayer

**Comment by RebelliousX** [comment]
DAMN! AND I SPENT THE LAST THREE DAYS TRYING TO FIGURE OUT WHY THE HELL KINEMATIC BODIES SHAKE LIKE HELL WHEN THEY COLLIDE!?! Like pushing a crate exactly 16 pixels ends up 17.984 which ruins the grid movements.

Sorry for screaming, but really.. I am trying to implement a grid like movement in a pixel perfect game port. Godot is not so nice for such type of games with lots of numerical imprecision. It doesn't say that in the tutorial. I really like Godot, but I might switch to Game Maker since it more friendly to pixel perfect sprite games.
