### ISSUE TITLE
One way platforms don't detect collision correctly on the edge

### ISSUE THREAD

**Issue by GraffixGames** [godotengine/godot#14724]
OS: Windows 10
Godot Version: Godot 3.0 Beta 1, 
**Problem:**
![This](https://user-images.githubusercontent.com/28675778/34062748-42e7d87a-e1bc-11e7-9b8e-2b699c019c97.gif) This happens when I use a one way platform.

**Steps to reproduce:**
create a basic platform character, and create a one way platform, it is pretty simple

**Link to minimal example project:**
[Example of Player Character](https://gist.github.com/GraffixGames/7407fc98a48d07dfc717ed1305899309)

**Comment by dherring** [comment]
May be related to issues #9399 and #11357

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by reduz** [comment]
This may have been fixed by 64f649a80. You example project is not really a project and I don't have time to build one around your player code. Feel free to reopen if the problem persists.

**Comment by sicienss** [comment]
This is still a problem in 3.1.

Collision detection for rectangular physics objects right on the edge of one way platforms is not consistent.

I will build and send an example project later today.
