### ISSUE TITLE
Editor Settings search bar is not working properly.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#14737]
> Is godot designed for children with learning disability?

they erased this message. there was no swearing.

**Comment by RayKoopa** [comment]
This also doesn't work properly when searching for the actual internal names of properties.
Typing "auto_indent" for example should list the "Indent" category with the "Auto Indent" option visible, but while the category is visibile, the setting is not.
![image](https://user-images.githubusercontent.com/9631152/34082015-1720d358-e357-11e7-8e45-a6af1081ea44.png)

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by hpvb** [comment]
Closing this issue due to vandalism @RayKoopa if this is still an issue could you please create a new issue with the appropriate information?
