### ISSUE TITLE
3D Camera keep asepect issue(Godot 3.0)

### ISSUE THREAD

**Issue by akanewf** [godotengine/godot#14777]
**Operating system or device, Godot version, GPU Model and driver (if graphics related):**
archlinux

**Issue description:**

set keep asepect in orthogonal camera.
when i set keep_width the camera preview looks right, but play game give me the keep_height result.

camera get_vaspect should be the opposite.

the docments said "<member name="vaspect" type="bool" setter="set_vaspect" getter="get_vaspect">
			A boolean representation of [member keep_aspect] in which [code]true[/code] is equivalent to [code]KEEP_WIDTH[/code].
		</member>"

vaspect = true equivalent to KEEP_WIDTH

enum KeepAspect {
                    KEEP_WIDTH,
                    KEEP_HEIGHT
 };

KEEP_WIDTH = 0
KEEP_HEIGHT = 1
call Camera::set_vaspect(true)

in scene/3d/camera.cpp line 410: 
void Camera::set_vaspect(bool p_vaspect) {
//set_vaspect(true)
         set_keep_aspect_mode(p_vaspect ? KEEP_WIDTH : KEEP_HEIGHT);
//true ? 0: 1 is 0, so keep_aspect = 0(KEEP_WIDTH) and vaspect = true
         _update_camera_mode();
}

 bool Camera::get_vaspect() const {
        //return keep_aspect == KEEP_HEIGHT; // 0 == 1 return false, but we set keep_aspect = KEEP_WIDTH and vaspect = true
          return keep_aspect == KEEP_WIDTH; //<----fixed
 }

so we set vaspect to true but get false!!!

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by Calinou** [comment]
I'm not sure if this is what this issue mentions, but vertical FOV (**Keep Height** mode of a Camera node) isn't working for me anymore; it looks the same as **Keep Width** now (horizontal FOV).

**Comment by djrm** [comment]
I also noticed this it seems to be caused by this d9cb00151bd662a25016ecab69433b2d4c146f6e, it also introduces a somewhat cryptic parameter that seems to be useless `vaspect` you cant modify it and it just mirrors what is stated in the keep aspect property.

![screenshot from 2017-12-22 13-49-27](https://user-images.githubusercontent.com/1103897/34310761-f504faee-e71e-11e7-8d77-1109f4434231.png)

this might be related to #14939
