### ISSUE TITLE
`split` returns no more than 2 substrings by default (argument parsing bug in VariantCall)

### ISSUE THREAD

**Issue by MednauN** [godotengine/godot#14799]
**Godot version:**
3.0 commit 0a762a0e393295c200e61e323a74eda47948f509
UPD: checked at d9f7fa4557297f506ee3015fa827d3da9bd39884 - still exists

**Issue description:**
Code:
```
var text = "One Two Three"
print(text.split(" "))
print(text.split(" ", true))
print(text.split(" ", false))
print(text.split(" ", "WAT"))
```
Output:
```
[One, Two Three]     <--- There's only 2 elements in array
[One, Two, Three]
[One, Two, Three]
[One, Two, Three]
```
I tried to look with debugger - there is something wrong in default argument substitution, but I didn't go any further.

**Comment by akien-mga** [comment]
That's what happens when devs get lobbied for core changes post-beta...

CC @Krakean

**Comment by Krakean** [comment]
@akien-mga I'll take care of this issue, don't worry!

**Comment by akien-mga** [comment]
> I'll take care of this issue, don't worry!

No worry, I was mostly joking :D
It's not a core change that would break stuff apart from itself, so it was fine to merge.

**Comment by Krakean** [comment]
@akien-mga 
Can't figure out root of issue. :-\
Can assume that may be a problem somewhere in variant_call.cpp or variant.cpp on stage where default arguments are handled, may be @reduz can take a look.
At least, if take a look on actual commit implementing third argument for split (https://github.com/godotengine/godot/pull/14580/commits/5302fd125b36d453615483f6ced4e40e973c499a), I suppose everything was made correctly (on variant_call part) about adding third parameter. 
So assume a problem is laying somewhere else, and not related to split() directly.

**Comment by ibrahn** [comment]
Can't get to a compiler at the moment and I'm not sure if I've read it all correctly, but
at around 1450 in core/variant_call.cpp
`ADDFUNC3R(STRING, POOL_STRING_ARRAY, String, split, STRING, "divisor", BOOL, "allow_empty", INT, "maxsplit", varray(true, 0));`
Do the default parameters not need to be in reverse order?

**Comment by akien-mga** [comment]
>  `ADDFUNC3R(STRING, POOL_STRING_ARRAY, String, split, STRING, "divisor", BOOL, "allow_empty", INT, "maxsplit", varray(true, 0));`
Do the default parameters not need to be in reverse order?

Indeed, default arguments are specified from last argument to last non-mandatory argument, so this should be reversed.

**Comment by akien-mga** [comment]
> Indeed, default arguments are specified from last argument to last non-mandatory argument, so this should be reversed.

Or not actually, I was wrong. It's the case when using `DEFVAL(val1), DEFVAL(val2)`, but not for `varray(val1, val2)` it seems.

**Comment by Krakean** [comment]
@akien-mga 
@ibrahn 
Oh dear, shame on me. Didn't know that they are in reverse order... 
Will fix it.

**Comment by Krakean** [comment]
@ibrahn nope, reversing them do not fix a problem :-\\

**Comment by ibrahn** [comment]
also variant_call.cpp 105-106
```
for (int i = p_argcount; i < arg_count; i++)
    newargs[i] = &default_args[defargcount - (i - p_argcount) - 1]; //default arguments
```
looks a bit off. The index: `defargcount - (i - p_argcount) - 1`
should probably be: `arg_count - i - 1`

Sorry I can't PR at the moment, at the wrong machine for today

**Comment by akien-mga** [comment]
So, it seems indeed that with the current code, not specifying optional arguments (so `text.split(" ")`) gives us `text.split(" ", 0, true)` instead of `text.split(" ", true, 0)`. On the other hand the documentation is correct, so the docs and VariantCall don't parse the `varray()` stuff the same way...

When reversing the order of arguments, it works fine for `text.split(" ")`, but it then breaks for e.g. `text.split(" ", true)` or `text.split(" ", false)` which seem to end up as `text.split(" ", true, 1)` and `text.split(" ", false, 1)` respectively... so there's definitely something wrong in the argument parsing.

So I blamed @Krakean, but he only exposed an existing bug it seems :)

**Comment by Krakean** [comment]
@ibrahn 
>also variant_call.cpp 105-106

Yep, thats place I meant by saying that more likely a problem "on stage where default arguments are handled". But since its a very core thing (and thus, fix from godot newbie like me can accidentally impact on (already in development) projects) , I hope that @reduz can take a look, or someone more experienced with godot codebase and solid tests projects base.

@akien-mga 
>So I blamed @Krakean, but he only exposed an existing bug it seems :)

Sorry, my bad :)

**Comment by ibrahn** [comment]
Submitted PR to fix the ordering of default arguments in VariantCall.

As per @akien-mga, the arguments are specified in forward order
> > Indeed, default arguments are specified from last argument to last non-mandatory argument, so this should be reversed.
> 
> Or not actually, I was wrong. It's the case when using DEFVAL(val1), DEFVAL(val2), but not for varray(val1, val2) it seems.

So no change needed on the String.Split side of things
