### ISSUE TITLE
Display composition helpers (rule of third) in 3D camera preview

### ISSUE THREAD

**Issue by TBDEV** [godotengine/godot#14825]
_**This is a minor request for layout and compositing, specifically for GUI's or scene compositions.**_

**1.** Draggable guidelines in the 2D mode, with possible snapping as found in most graphic editors.

**2.** Rule of Thirds guides for both 2D and 3D mode, useful for compositing. Blender has some nice 
    options for it under its camera settings.

**3.** Responsive layout features as seen in CSS3/Bootstrap such as grid, viewport width(vw) and height(vh), 
    so games or applications created in Godot can change GUI layouts based on resolutions.
<br>
_I'm a new user, so if some of these features exist, please let me know._

**Comment by RabbitB** [comment]
I can't speak for `2` and `3`, but `1` already exists. Rulers are on by default now, and just like most graphic editors, you can drag guides out of the rulers, and delete them by dragging them back onto the ruler.

Although you can't grab within the scene; you need to grab where it goes into its perpendicular ruler.

```i.e. A vertical guide can be created by dragging from the vertical ruler into the scene, and the guide then destroyed by grabbing it from where it overlays the horizontal ruler, and dragging it back over the vertical ruler.```

**Comment by mhilbrunner** [comment]
1 is already done.

3 is mostly done / done in a different way, see [UI tutorial](http://docs.godotengine.org/en/latest/learning/step_by_step/ui_game_user_interface.html) - though I don't think there is a nice tutorial on scaling UI with resolution yet.

**Comment by TBDEV** [comment]
@RabbitB @mhilbrunner XD Ok I didn't notice the view settings for the Rulers and Grid. Rule of Thirds would still be nice, especially for cutscenes and other game compositing. Thank you for the help.

**Comment by mhilbrunner** [comment]
I'd agree it could be useful, although probably more for 3.1+ at this point.

**Comment by groud** [comment]
Maybe the rule of third can be implemented in the preview mode for a camera.
The two others are already here, thus I change the issue title. :)

**Comment by TBDEV** [comment]
@groud Thank you.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
