### ISSUE TITLE
Godot file explorer : backspace key don't work

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#14865]
**Godot version:**
Godot 3.0 beta 1, windows 10

**Issue description:**
In godot file explorer the backspace key don't allow to return to the parent folder. All other keys for navigation are working like arrow left, arrow right and return. Would be great to have the backspace working for have a full navigation at keyboard.

**Steps to reproduce:**
In godot, `Scene > Open Scene` (or all other file picking)
Select a folder and try to go back with backspace key.

**Comment by vnen** [comment]
I don't like Backspace to go back, and even less to go to parent. This isn't a common behavior AFAIK.

**Comment by Noshyaar** [comment]
I think the new/default 'back' and 'forward' keys are Alt+Left and Alt+Right respectively, which aren't supported either.

**Comment by vnen** [comment]
Alt+Up is the shortcut to go the parent folder. If something is not working, I think that a specific issue should be opened.

**Comment by Jerome67000** [comment]
based on the fact that most of the file browsers and web browsers use the backspace  to go to parent folder and that return key is used to go to selectionned folder, maybe Alt+Up isn't the best.

Maybe a poll in facebook group can give the best key to use for the community

**Comment by RabbitB** [comment]
> based on the fact that most of the file browsers and web browsers use the backspace to go to parent folder 

Every browser I've used has backspace take you to the last page, and it's the worst *feature*. The number of times I've erroneously gone back is tremendous. In Godot, I'd much rather the shortcut to go to the parent folder be a multi-key shortcut that requires deliberate thought to use.

**Comment by Calinou** [comment]
Is there still support for this? <kbd>Alt + Left</kbd> and <kbd>Alt + Up</kbd> can be used to go to the previous/parent folder (respectively).

**Comment by hsandt** [comment]
So, two points: existing app shortcuts (just for info), and the actual bug (what matters for the issue tracker).

# Existing app shortcuts

I found this:
- Windows Explorer: Backspace/Alt+Up to go up, Alt+Left to go back, Alt+Right
Windows XYplorer: Backspace/Alt+Up to go up, Alt+Left to go back, Alt+Right, Alt+Down to go one level down in the breadcrumb (even if you select a different folder after Alt+Up, Alt+Down will bring you back to the inner folder where you were)
- Linux Nemo: Backspace/Alt+Up to go up, Alt+Left to go back, Alt+Right, Alt+Down to enter selected folder
- OSX file browser: Cmd+Up/Cmd+Down to go up and down in folders (I remember using Backspace too, but not sure if I was using a plugin). Not sure about go back/forward.

So ideally Godot should use, for each OS, one of the conventional shortcut by default. Now I don't know if Godot has a way to change default settings based on the OS. If not, just sticking to one is fine. In this case, probably not Cmd/Meta shortcuts because it's harder to do on non-OSX platforms without invoking some desktop shortcut. Otherwise, it seems Backspace and Alt+Up are equally used. So ideally we would have both, but since Godot doesn't support multiple command bindings, I'd go for Alt+Up to match Alt+Left and Alt+Right. Yeah, that's exactly the current defaults, I guess the designer had a similar reasoning.

Without per-OS defaults, not all users will find the right shortcuts on the first try, but at least they are customizable in the Shortcut settings.

_Just for info, on the web browser side, I found Firefox (Linux) to go back on both Backspace, and Alt+Left, and go forward on Shift+Backspace and Alt+Right; but the Backspace actions can be disabled in about:config. With some plugin you can even go one URL level up with Alt+Up; although that is less a convention and different plugins may provide different default shortcuts._

# Bug: unresponsive directional shortcuts

Now the biggest issue: in the File Dialog, directional-based shortcuts (Alt+Left, Ctrl+Shift+Up, etc.) do not respond properly when focusing on the Directories & Files pane (at least on Linux). If no file/folder is selected, Up and Down-based shortcut will work, but Left and Right-base shortcuts will not. If a file/folder is selected, the shortcut will only work if there is nothing in that direction to select. Else, it will move selection to that direction instead. Backspace seems to work fine in any case.

This means the default shortcuts and not doing their job consistently. And even if we bind Go Up to Backspace, the issue remains with Go Back (Alt+Left) and Go Forward (Alt+Right).

This is what needs to be fixed, and is actually part of a bigger topic in Godot: keybinding conflicts. Except instead of being a conflict between actual keybindings, it's a conflict between a keybinding and a native binding (navigation arrows in File Dialog). But it's also an issue of context and priority.

I suggest to rename the issue title to "Godot File Dialog: Alt+Left/Right/Up do not always work for Go Back/Forward/Up". Alternatively, open a new issue since the description kinda changed too.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by hsandt** [comment]
Some update on Godot 4.4.1 where many things have changed:
- all the bugs I've mentioned in my previous post have been fixed. Whether a file/folder is selected or not, Alt+Up/Left/Right will properly work. There is no Alt+Down to "go back one level deeper" contrary to what I thought, you'd have to Alt+Left to go back where you where after Alt+Up.
- https://github.com/godotengine/godot-proposals/issues/7725 was implemented for Godot 4.3 which allows to use the native file browser window and use your favorite shortcut (in exchange for a possibly heavier window and missing some convenience from the Godot custom file prompt such as display options and recent Godot folders). Ironically, I found out that on Linux Ubuntu + Nautilus at least, Backspace was *disabled* during file prompt specifically, and didn't allow to go to parent folder as usually when exploring files outside file prompt. But it may still work on Windows. In counterpart, Alt+Down will work in Nautilus prompt mode to go deeper in the recorded breadcrumb path.

Backspace has still not been implemented as an alternative shortcut for Alt+Up in Godot 4.4, so it is still worth opening a feature proposal on the other repository (see automatic post above) for those who are still interested in it.
