### ISSUE TITLE
Add Create movies feature like UE4.

### ISSUE THREAD

**Issue by sersoong** [godotengine/godot#14887]
proposal:
UE4's sequencer can create movies and render output as a video file.
Maybe godot can add this feature too.
[sample](https://www.youtube.com/watch?v=RqWaa08V_dw)
[sample](https://www.youtube.com/watch?v=tYPe-C6VDVo)

**Comment by Ace-Dragon** [comment]
I think there's a lot of stuff to develop in terms of Godot as a game engine yet.

Moving the engine into film (when we already have Blender) would only siphon development away from what most people are using it for, and the film direction isn't necessarily popular among Unity users either (with some, according to blog comments, feeling shafted as they use the engine to make games).

**Comment by willnationsdev** [comment]
Yeah. I wouldn't say this something that could never be added, but I think the priority for the devs is going to be stuff that enhances Godot as a game engine specifically.

**Comment by sersoong** [comment]
Have you ever considered the animation of the transition levels？
Then store it to disk.

**Comment by sersoong** [comment]
The real-time CG animation like Final Fantasy or The Witcher 3.
How did you make the shot?
Make it in blender?
:p

**Comment by willnationsdev** [comment]
real-time animation is generally done using tiered sets of `AnimationPlayer`s and `AnimationTreePlayer`s. For example, one AnimationPlayer that moves a limb on a character, another for animating sets of limbs (by animating calls to the previous AnimationPlayer's animations), and then a 3rd one for animating sets of characters for entire levels.

Furthermore, A "director" mode is a planned feature for the 3.1 relase (as stated on the [roadmap](https://docs.google.com/document/d/1hNrID0N1-6lo_NMNdGmPfQKckWfntJ24ycP8xlIabFg/edit)) to simplify the creation of CG, real-time animated performances. Note that the roadmap's timeline is off.

I'm sure many people would like to have better animation systems, but what you specifically requested here is the ability to output animated content as a video file. Depending on how easy that is to implement with existing features, that may actually end up in 3.1, especially if someone motivated (like you?) implements the functionality on their own and merges it in.

**Comment by willnationsdev** [comment]
In fact, it's quite simple already to create a video out of animated gameplay content (including cinematic animations in Godot) using something as simple as OBS that can track and record the video output of another program already.

**Comment by blurymind** [comment]
There is a lot of gamedev features that godot is missing. I would very  much prefer if developer effort is focused on those. A sequencer could be added to the timeline some day, but its far from a point where it should be a priority. We still miss a number of key animation features that Unity and Unreal has had for a long time.

**Comment by Calinou** [comment]
For those interested, I made a proof of concept of this: https://github.com/Calinou/godot-video-rendering-demo

There are many things that should be improved for it to be more usable (better usability, faster frame saving), but it's a start.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
