### ISSUE TITLE
Creation of the car. Bugs and many other things

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#1489]
Today I decided to be engaged in project development. I am familiar with Godot from first week of its birth (spring 2014). 
Looking at a demo I started replenishing gradually the project models. Everything went rather well. 
Oh well! prehistory will be enough!
Here to you directly list:

**To add:**
1. The script of your car can gather fighter speeds, but for some reason can't go back. At me (for my purposes) everything was solved very simply. I wouldn't want that other people got on so low-quality demo. If you not against, I can make the new version of a demo of the car.

**Bugs:**
1. Where without bugs. We will begin with the most ancient and long ago moss-grown. Tremesh collider still doesn't work. To what it is connected I don't know. If I would know at the time of prerelease 1.0stable that this bug lives still, I not simply would write here, but also on mail and to personal messages in facebook. For example my route perfectly works with a similar collision, but it is impossible to use it on the car.
2. One more old bug (itself I came across it and even I wrote about it is mute at a forum). Convex collider very strongly loads system if to deliver it child to the car. In case of collisions my notebook starts being buggy very strongly. Also I ask to correct. Of course I don't give a demo, but I think you and you will be able to check it.

**To correct:**
1. I stayed some months on Unity3D and returned back to Godot only because I was enticed by physics of the car. Today I stayed the whole day behind the project and the working prototype of behavior of the car tried to make. I almost managed it. The first that to me was evident it twitching of a wheel (as in the same Unity), but also sharp response of the car to all these actions isn't simple.
2. And again physics of the car. It not especially hinders, but the realism and ideas of friction kills at all. If to go on the car along a wall, the car sharp breakthrough turns approximately on 10-15 degrees to the opposite side from a wall. I Predlogat also to reconsider this slice of a code of physics.
3. Third point and... (what?) Of course I will speak again about a car physics nedodelannost. In settings of a wheel there are ticks which are responsible for characteristics of a wheel (turn and pull). My car falls to the ground and jumps up on back wheels (it normally. settings such) but if to click gas, the machine will go., It seems, anything surprising as the machine concerns back wheels of the earth. All problem that on back wheels the tick "pull" isn't necessary... Having a little thought I came to a conclusion that the car receives force not on wheels, and on a cabin. I would like to see impact of physics on wheels.
4. "Fig. One more point. Likely again about car physics!". Absolutely truly! Again point about dirty linen! It could be carried in the section "Add", but it is rather a defect which can't be corrected without correction of point 3. The essence of this "bug feature" is that the car, crashing into a hindrance doesn't go any more and wheels aren't twisted soovetstvenno. Everything is seemingly normal, on as opportunities "To burn down tires", "to start with a place, reserving a trace"? all this can be made, but what sense if the wheel isn't twisted?

**Inference:**
I bring the apologies for inexact names. The text is translated by means of the site as I very badly know English.
It would be desirable to hear your judgement and a sentence concerning a car demo.

**Comment by TheoXD** [comment]
Spent some time reading this blog post of yours, want to note that issues/additions/corrections should be separated, they're easier to manage and reference. Your issue contain dozen different issues, half of them are related to the car demo, other relate to engine itself, some of them are not even issues. And it's always a good idea to consult on IRC or forum before posting an issue.
Sorry if I do not read you correctly, in fact I used google translate to translate back to Russian in order to understand better.

To add:
  1) Demos are supposed to get you started, and avoid complications as much as possible. For real car you normally add gears and stuff, people who just want to know how to use the vehicle node - do not care about that stuff.

Bugs:
  1) Trimesh works on car, it is not showing in the editor though. You simply select a mesh instance and press "Mesh->Create Trimesh Collision Sibling".
  2) Convex/Trimesh collisions are known to be heavy, since it calculates collision per triangle. Use much simpler shapes.

To correct:
  1) Welcome back! If you mean that wheels in the demo are not rotating smoothly - you're rignt, they do not, probably to keep demo as simple as possible.
  2) Never had issues with friction against the wall, sorry. Keep the friction minimal for the car body.
  3) Sounds like your center of mass is somewhere else, but if you say it's normal - fine by me. And sounds like you want to make an American Muscle car that lifts the nose up in the air. The problem with car physics in games is that everything you see - is fake, for performance reasons. Wheels are basically rays, they are helpers, so it's car body that is moving, wheels just tells it when and where. For the record, some parts of car physics were actually taken from Bullet Physics engine.
  4) As mentioned above - everything you see is fake. Wheels will stay oriented in the same direction until you turn them yourself. I would probably just simulate this behavior using joints, operating in a different layer. Then orient wheels using rotation of the joints.

**Comment by akien-mga** [comment]
This issue is indeed too difficult to work with efficiently, there is just way too much stuff for any contributor to fix. Each issue should be atomic and able to be fixed in one pull request, such a "list it all" issue is actually not so helpful, because honestly, most contributors won't even try to read it.

@TheoXD did it though, so I would advise it to read his answer, and then create one issue for each point that is still relevant in the current master branch/nightly builds and that you want the community to work on.
