### ISSUE TITLE
"if (has_node (name))" is not the same as "if ($name)"?

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#14920]
**Godot version:**
3.0 3068ccc

**OS/device including version:**
Ubuntu Linux 17.10 64-bit.

**Issue description:**
I have this code in my project:
```
if (has_node ("/root/Level/hud_layer/Lives_Counter")):
	$"/root/Level/hud_layer/Lives_Counter".set_text (var2str (lives))
if ($"/root/Level/hud_layer/Ring_Count"):
	$"/root/Level/hud_layer/Ring_Count".set_text (var2str (rings))
```

Now, the second if statement - `if ($"/root/Level/hud_layer/Ring_Count"):` works the same as the first if statement, except that it generates endless `Node not found: /root/Level/hud_layer/Ring_Count` error messages when the scene it's attached to runs. The first statement does not.

If `if ($"/root/Level/hud_layer/Ring_Count"):` is not valid syntax, it'd be handier if it gave an error message before trying to run the scene. If it is supposed to be the same as the `if (has_node ("/root/Level/hud_layer/Lives_Counter")):` statement then this behaviour is a bug.

**Steps to reproduce:**
Try using a `if ($<node name here>)` type statement instead of `if (has_node (<node name here>))`.

**Minimal reproduction project:**
https://www.dropbox.com/s/ag6wav8m6fbuunh/14866_demonstrator.7z?dl=0 - although created for a different issue, this project should demonstrate said issue by running the hud_layer scene on its own.

**Comment by akien-mga** [comment]
Well it's not related to the `$` operator, it's just `has_node` vs `get_node`. `get_node` will print an error if the node is not available.

**Comment by Sslaxx** [comment]
But the statement is using the `$` notation here like `has_node`. If this is not correct, i.e. `$` is only to be used in the same situations `get_node` should be, shouldn't there be some kind of error about it?

**Comment by akien-mga** [comment]
> But the if statement is using the $ notation here like has_node. If this is not correct, i.e. $ is only meant to be used in the same situations get_node should be, shouldn't there be some kind of error about it?

Well `if (get_node("nodepath"))` is valid, it returns either a Node (`True`) or `null` (`False`). It's a bad idea as it will indeed throw an error if there is actually no node at this path, but it's valid GDScript so no reason to throw a compile error.

> Also, note that other than the incessant error messages, it works the same as the has_node line. Is this also incorrect?

It probably doesn't work at first (while spamming the error), then ends up working when the node gets instanced.

**Comment by Sslaxx** [comment]
In that case, why not silence the error? The two statements are functionally identical.

**Comment by akien-mga** [comment]
> In that case, why not silence the error? The two statements are functionally identical.

They're not identical. One of them returns a boolean to say "yes, this node exists", the other one returns the node itself. If you just want to know if the node exist, you should use `has_node`, not `get_node`. If you do use `get_node`, it's a *bug* when the node is missing and should be signaled as such.

**Comment by letheed** [comment]
I've wondered about this before. `has_node(x)` is basically `get_node(x) != NULL`. Is has_node actually faster? I thought that when using a shallow node it didn't matter much but if the node is deeper it was a bit of a waste to retrieve it twice.

I've found myself wanting to write stuff like:

```rust
if var Some(node) = get_node("path/to/node"):
    ...
```

like in I would in rust ^^ Not that there's really a need for tagged unions in GDScript otherwise.

**Comment by volzhs** [comment]
I tested this code

```gdscript
if $"node_name":
    print("ok")
if get_node("node_name"):
    print("ok")
```

those 2 make the exact same error because `$` == `get_node()` if there is no `"node_name"` node.
`$` != `has_node()`

and `has_node()` does actually the same with `get_node()`

```cpp
Node *Node::get_node(const NodePath &p_path) const {

	Node *node = _get_node(p_path);
	if (!node) {
		ERR_EXPLAIN("Node not found: " + p_path);
		ERR_FAIL_COND_V(!node, NULL);
	}
	return node;
}

bool Node::has_node(const NodePath &p_path) const {

	return _get_node(p_path) != NULL;
}
```

https://github.com/godotengine/godot/blob/master/scene/main/node.cpp#L1515-L1528

so, what about just having `return NULL;` in `get_node()`?
because the `_get_node()` should be called multiple times if wants to avoid error messages.

this will call `_get_node()` twice
```gdscript
if has_node("node_name"):
    var node = $node_name # or get_node("node_name")
```

this will call `_get_node()` once, but it will print an error message.
```gdscript
var node = $node_name # or get_node("node_name")
if node == null:
    pass
```

**Comment by voithos** [comment]
I imagine there are many cases where we'd *want* `get_node()` to throw an error (if we expect the node to be there, and it isn't, then throwing an error is a form of early feedback that will help debug during development). On the other hand, it seems like there's also a desire to be able to avoid a separate `has_node()` check.

What about having what's effectively a `get_node_or_null()` (or a better name) - similar to the normal `get_node()`, but one that doesn't throw errors. Then we could consider whether it makes sense for the `$foo` syntax to default to calling `get_node("foo")` or `get_node_or_null("foo")`. If it called the latter, then the `if $foo:` syntax would work as expected, right?

I guess in a sense that isn't better than `has_node("foo")` at all, since presumably we'd follow up the `if` check with other references to `$foo`, which I'm guessing would trigger the `get_node_or_null()` call again.

**Comment by voithos** [comment]
I'd say that the error is more helpful than just a null reference error. First, it's more specific; seeing something like "Node 'foo' not found" gives more information than some nondescript null reference error. Second, it keeps the error localized; if, say, a script did something like `some_script_method(get_node("foo"))`, it would potentially end up propagating a `null` through several functions, perhaps even in other (extended) script files, before finally blowing up in some unrelated part of the code.

**Comment by bojidar-bg** [comment]
What about transforming `$node` to `has_node(@"node")` when used as a sole expression in an if statement, similar to how `is` expressions are used for type hints?

**Comment by reduz** [comment]
The current behavior is intended. You make your own scenes, so using $ will pretty much ensure the node is there like, 99.99% of the times, unless you do some funny code. 

If you need to check that a node exists, that is by far the exception and not the rule, so it's perfectly fine that both $ and get_node() return error on a node not found. You expect to find it in most cases, so the error is welcome.

**Comment by akien-mga** [comment]
Agreed, that's also what I had answered initially. Closing then.
