### ISSUE TITLE
Video in VideoPlayer stops working after moving it to a different folder (after clearing and reassigning)

### ISSUE THREAD

**Issue by cyaoeu** [godotengine/godot#14956]
**Godot version:**

Godot 3.0b2(64 bit)

**OS/device including version:**

Win8, GTX1070

**Issue description:**

Video in VideoPlayer stops working after moving it to a different folder after clearing and reassigning. What this means is that you import and load video A in a VideoPlayer. It plays fine. You then clear the stream and create folder B and then move video A to folder B. You then load the video again (in the new folder) but the picture doesn't show in the editor and indeed when playing the video doesn't play. If you move the video back it plays again.

**Steps to reproduce:**
- Import a video.
- Create a VideoPlayer and load the video.
- Confirm that the video plays when playing inside the Godot editor.
- Create a folder.
- Clear the loaded video in the VideoPlayer.
- Move the video into the created folder.
- Load the video (in the new location) in the VideoPlayer again.
- Play the game, the video doesn't play.
- Move the video back to its original location. It plays again.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+)
  for potential duplicates.

**Comment by mrcdk** [comment]
More info: if you reimport the file after moving the file it works correctly. This is a bug, it shouldn't need to be reimported.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by akien-mga** [comment]
I fixed this in #19937.
