### ISSUE TITLE
"Requested file format unknown" error when saving an edited Mesh

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#14967]
**Godot version:**
built 23rd dec off github

**OS/device including version:**
linux manjaro
amd rx580

**Issue description:**
open a dae, or glft or glb in the editor
move the mesh
the file shows in the editor with a (*) indicating its not been saved
press the play button
a dialog opens saying "Requested file format unknown" and the game fails to load

**Steps to reproduce:**
ops, as above :)

I'm assuming this is trying to save over the mesh file, as when i close that tab it all runs fine....

**Comment by Noshyaar** [comment]
>built 23rd dec off github

It'd be simpler to include the shorthash from the engine version. :)
Like so: 5c8aba2
![image](https://user-images.githubusercontent.com/26753932/34316206-9a270154-e7c2-11e7-8022-80daa8929cde.png)

**Comment by Gibbz** [comment]
Ah i didnt realize the version number was on the about screen!
Thanks

Version: 32d8b99

**Comment by reduz** [comment]
The error is technically valid, I wonder how it could be handled better..

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by TutorialDoctor** [comment]
I'm getting the same issue when trying to save a scene that contains a mesh file. The file-type is .dae exported using Blender's Collada exporter (not the better colada exporter). Since the collada format is likely to be the best format for working with 3D models in Godot 3.0, I think it warrants further investigation. I can't even save the scene.

**Comment by reduz** [comment]
@TutorialDoctor Yes, you can't save the scene and it explains you why. I'm not sure what else could be done..

I am still not sure this is a bug, how could it be improved usability wise?

**Comment by KoBeWi** [comment]
Not sure when it was changed, but when trying to open a mesh now, Godot suggests you to create an inherited scene instead, which is the "correct" workflow. The only thing we could do more is prevent opening mesh scenes at all.

**Comment by akien-mga** [comment]
Closing as fixed as per the above.
