### ISSUE TITLE
Revert button consistency

### ISSUE THREAD

**Issue by realManix** [godotengine/godot#14961]
**Godot version:**
Godot 3.0 beta 2 Mono

**OS/device including version:**
Windows 10 professional, 64 bit.

**Issue description:**
When you create a script (GDScript/C#) with _export variables_ for a node and make changes to them in the inspector, a revert button would appear next to individual variables you made changes to. When you save that node as a scene and instantiate it from another scene, the revert buttons remain for variables whose values differ from the original "placeholder" values hardcoded in the script, like in the original scene where node resides, even though clicking on the revert button in the new scene where the original scene is instantiated will not do anything, unless you make changes to the variable in the new scene, where the value would be reverted to one in the original scene.
This behaviour is kind of confusing, so I think it should be changed so that in the new scene where the original scene is instantiated, revert buttons should not appear next to variables whose values do not differ from those of the original scene, even if they differ from hardcoded values in the script, or use two distinct indicators to reflect the differences in the values at the new scene, the old scene, and the script.
(24/12/2017 Edit) Also, I noticed that when you change a variable's value in the inspector in the original scene, the change is not automatically reflected in the scene where the original scene is instantiated, storing the value in the script.

**Steps to reproduce:**
In an empty scene, create a node and attach a script (GDScript/C#), create an _export variable_ and assign an arbitrary value. In the inspector, change that value and note the revert button appearing next to it. Clicking that button would revert the value to the hardcoded one in the script.
In another scene, instance the first scene and note the revert button next to the variable we created previously. Clicking the button would not do anything unless you change the value in the new scene, in which case the value would be reverted to the value assigned in the original scene, not the hardcoded value.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+)
  for potential duplicates.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
