### ISSUE TITLE
Double function call when using AnimationTreePlayer transition node

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#15018]
**Godot version:**
Godot.v3.beta2

**OS/device including version:**
Ubuntu 17.04

**Issue description:**
Only when the function is called on the last frame of the animation this happens. See attached project. Run project, press SPACE once, close game (after at least 0.5 sec), look at output log and see `TEST_END` twice. As far as I can tell this only happens when using the AnimationTreePlayer transition node.

Expected behavior is that output should be:

```
TEST_START
TEST
TEST_END
```

but instead it's:

```
TEST_START
TEST
TEST_END
TEST_END
```
[godot-dbg.zip](https://github.com/godotengine/godot/files/1585098/godot-dbg.zip)

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
