### ISSUE TITLE
Shouldn't TouchScreenButton inherit from Control instead of Node2D?

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#15039]

**Comment by Noshyaar** [comment]
Why?

**Comment by razvanc-r** [comment]
Because all other button nodes are descendants of Control. Why is TouchScreenButton special? Control nodes have the property of drawing on top of everything else and you can place them in nice containers etc.

**Comment by Noshyaar** [comment]
If you need to use containers, use Button. The main difference between Node2D and Control is positioning. It's the same reason why you'd want to use Sprite instead of TextureRect.

**Comment by volzhs** [comment]
maybe it's behavior is different from `Control`.
like, moving(dragging) a finger from "<" and ">" button on screen acts like press it.

**Comment by groud** [comment]
Honestly, I don't even know why a TouchScreenButton is needed. The normal button should also handle touche events.

**Comment by reduz** [comment]
TouchScreenButton is different than a Control because it does not captute
the input. It just activates when you slide the finger over it or press it

**Comment by Zylann** [comment]
Ooh ok that might cause confusion then https://godotengine.org/qa/35806/how-to-stop-overlapping-button-pressed-trigger

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by hafizosina** [comment]
here in 4 year later Touchscreen button still Under Node2D and regular button still does not work on multitouch
