### ISSUE TITLE
UV mouse coordinate in shaders

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#15038]
I was going over [The Book of Shaders](https://thebookofshaders.com) and they have examples with mouse interaction too, the mouse coordinate is an input like UV (in godot shader language) and got me wondering why this isn't the case in godot. Sure we can send the data from script through uniforms, but like TIME I think it makes sense to have something like MOUSE_UV or MOUSE_COORD or something.

**Comment by reduz** [comment]
This will be handled with global uniforms and scene shaders, hopefully in
3.1

**Comment by akien-mga** [comment]
I'm not sure what @reduz referred to exactly in the above comment, but I don't think this can be considered "solved" in 3.1 nor 3.2 so far.

Yet, there's quite a few details to discuss so I think it would be better to move this to a proposal on https://github.com/godotengine/godot-proposals, so that we can define what should be implemented, if anything. There's also the question of what to do on devices without a mouse, and whether touch coordinates should be included too.
