### ISSUE TITLE
Symbol completion problem in built-in code/script editor

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#15088]
**Godot version:**
Godot 3 beta 2

**OS/device including version:**
Dev OS: Windows 8.1

**Issue description:**
Symbol completion (Ctrl + space) not showing in some case.
Example:
Completion for variables with values, as example I use string
![symbolcompletion3b2](https://user-images.githubusercontent.com/8316851/34372393-e023783a-eb06-11e7-8db3-f660fb49ba87.JPG)
In previous version (2.1.4) it works:
![symbolcompletion214](https://user-images.githubusercontent.com/8316851/34372407-fe2a4214-eb06-11e7-9291-942415b82018.JPG)
Also happen with other variable type like Array, Vector2, etc

Note:
Completion work when accessing node member.
Tho completion not showing, but the script work when you type it yourself (manually)

**Steps to reproduce:**
Just type script in build-in script editor

**Minimal reproduction project:**

- [ ] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+script+completion) for potential duplicates.

**Comment by earlroxas13** [comment]
Update:
This issue affect local variables.
The completion work just fine with class variables.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by earlroxas13** [comment]
@akien-mga 
Sorry for late comment.

This issue affect productivity / usability for programmers, i mean some of us is lazy enough to type the code ourself and relying the auto-completion a lot. :)

If no other one complain about this issue, I think it's ok to move it to 3.1 milestone. 
I myself happy enough if this issue fixed in maintenance release for 3.0 (3.0.X)
