### ISSUE TITLE
Add global scope scene merging

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#15095]
Currently it is only possible to import scenes within the same project and no directory above `res://` is accessible through **Merge from Scene** I think it would be a great idea for reusability and to provide more modularity and best workflow to enable the access into global scope for importing a scene.

Somo user case I've been into: I'm creating a small library of base code and I'm structuring bunches of scenes and in order to use it into new projects I have to copy-paste the scene using OS filesystem, I think it would be more friendly to have the possibility to import a scene from other projects using the same workflow as I do within the same project.

**Comment by LeonardMeagher2** [comment]
Does godot work well with symbolic and hard links?

**Comment by henriiquecampos** [comment]
@LeonardMeagher2 
> Does godot work well with symbolic and hard links?

I don't know, but merging scenes don't make references, they basically copy-paste the .tscn data into the new scene, so I thing it is pretty OK. Unless I misunderstood what "symbolic and hard links" means

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
