### ISSUE TITLE
Editor mesh-view-uv glitch

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#15123]
**Godot version:**
7f1265b41fc52def42c433e5d324070bc6454d6b

**OS/device including version:**
x11

**Issue description:**
The window content should scale to the max. uv-map size. 

blender:

![uv-issue1](https://user-images.githubusercontent.com/4047289/34413469-0f308ee6-ebe4-11e7-83a0-ed755e08f145.png)

godot3:

![uv-issue2](https://user-images.githubusercontent.com/4047289/34413883-7a01073a-ebe6-11e7-95a0-03fe2f465204.jpg)

![uv-issue3](https://user-images.githubusercontent.com/4047289/34413506-3b5cf6ee-ebe4-11e7-9acf-c67c1bdca141.jpg)

**Comment by Toshiwoz** [comment]
![image](https://user-images.githubusercontent.com/21297356/39666487-d5a0b8f0-5069-11e8-92ae-a21c211daf6c.png)
I found a related issue, it's a code generated UV, that's clearly wrong but still, the editor should probably cut down the part that goes outside the dialog window.

**Comment by Calinou** [comment]
@capnm Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
