### ISSUE TITLE
Mono fails to build with Error 47

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#15128]
**Godot version:**

Current Head: 7f1265b41fc52def42c433e5d324070bc6454d6b

**OS/device including version:**

Ubuntu 16.04

**Issue description:**

Make a bare bones project with a single script. It won't compile even with a brand new project.

**Steps to reproduce:**
1) Make a new project using the Mono version
2) Add a script
3) Try to build
4) It fails with "Error 47"
Note: nothing seems to print to the terminal when run from it.

![screenshot from 2017-12-28 12-26-24](https://user-images.githubusercontent.com/629422/34418410-f56ef0b4-ebcb-11e7-9783-dae71d880427.png)

**Minimal reproduction project:**

[MonoBuildFail.zip](https://github.com/godotengine/godot/files/1591750/MonoBuildFail.zip)

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by neikeq** [comment]
There must be an error in the terminal.

**Comment by NathanWarden** [comment]
I tried running it through Windows 10 and got this:

```
ERROR: EditorData::get_edited_scene_root: Index current_edited_scene=-1 out of size (edited_scene.size()=0)
   At: editor\editor_data.cpp:607
ERROR: BindingsGenerator::_generate_cs_property: Condition ' !setter && !getter ' is true. returned: ERR_BUG
   At: modules\mono\editor\bindings_generator.cpp:1016
ERROR: Failed to generate property 'messages' for class 'Translation'
   At: modules\mono\editor\bindings_generator.cpp:812
ERROR: ResourceFormatSaverCSharpScript::save: Cannot add res://EmptyScript.cs to the C# project because it could not be created.
   At: modules\mono\csharp_script.cpp:2015
```

**Comment by AllanDaemon** [comment]
I got this error too.

But I found the https://github.com/godotengine/godot/issues/12466 issue first, but I get this error with the latest code (https://github.com/godotengine/godot/commit/f11a1385054376bdc4cc01e6aa20d63508a5e6d4).

**Comment by EugenEistrach** [comment]
@neikeq 
Compiled latest master branch with manually edited file with the changes from your pull request (https://github.com/godotengine/godot/pull/15136) since it wasn't accepted yet. 

It fixed this issue but I got a new issue. I created a new project with one node and a script attached to the node. The script has this two lines in the _Ready Method:

`var dir = new Directory();`
`dir.Open("res://");`

The second line crashes the game with following console output:

> CrashHandlerException: Program crashed
> Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
> [0] <couldn't map PC to fn name>
> [1] <couldn't map PC to fn name>
> [2] <couldn't map PC to fn name>
> [3] <couldn't map PC to fn name>
> -- END OF BACKTRACE --

Before I compiled the engine (64bit) I cleaned the scons cache and followed the steps [here](https://godot.readthedocs.io/en/latest/development/compiling/compiling_for_windows.html) and [here (for mono)](https://godot.readthedocs.io/en/latest/development/compiling/compiling_with_mono.html)

Did I do something wrong or is this crash reproducable?
