### ISSUE TITLE
Docs: [code] adds \ unnecessarily

### ISSUE THREAD

**Issue by Noshyaar** [godotengine/godot#15156]
**Godot version - OS/device including version:**

f11a138 - Antergos x86_64

**Issue description:**

XML: `[code]CONNECT_*[/code]`
Expected: `CONNECT_*`
Happened: `CONNECT\_\*`

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by akien-mga** [comment]
Are you talking about the RST output or the in-editor docs?

**Comment by Noshyaar** [comment]
Sorry, forgot a link. I meant RST output as seen here: http://docs.godotengine.org/en/latest/classes/class_object.html#class-object-connect

**Comment by akien-mga** [comment]
So the issue is not that `[code]` adds it, it's that the converter adds it everywhere, but it should not be added from `[code]` and `[codeblock]`.

**Comment by akien-mga** [comment]
Escapes are added here: https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py#L156-L175

Since it needs to be made context-sensitive, it should be reworked to be moved as part of the main while loop: https://github.com/godotengine/godot/blob/master/doc/tools/makerst.py#L177
(An alternative is to keep it as is, and then remove the escapes when in `[code]` and `[codeblock]` tags, but that might be error prone if a user did want to use `\_` or `\*` in a code example.

**Comment by KidRigger** [comment]
Mind if I take this?

**Comment by KidRigger** [comment]
(An alternative is to keep it as is, and then remove the escapes when in [code] and [codeblock] tags, but that might be error prone if a user did want to use \_ or \* in a code example.)
The code will convert user's \_ to \\_ and \* to \\* anyway, so I suppose even the alternative method is not a bad deal.
