### ISSUE TITLE
Light2D Texture doesn't properly use .atex files.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#15194]
I'm using the Windows version of Godot 2.

The Light2D texture resource isn't using the region rectangle when given it an atlas texture.

Instead of using the region of the source texture, the light will use the whole source texture.

This happens when set in the editor properties panel and when set by script.

**Comment by reduz** [comment]
This is expected, not a bug.

On Dec 30, 2017 11:34 AM, "avencherus" <notifications@github.com> wrote:

I'm using the Windows version of Godot 2.

The Light2D texture resource isn't using the region rectangle when given it
an atlas texture.

Instead of using the region of the source texture, the light will use the
whole source texture.

This happens when set in the editor properties panel and when set by script.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/15194>, or mute the thread

**Comment by timoschwarzer** [comment]
Then this should be documented / noted somewhere

**Comment by Ranoller** [comment]
Probably this should be allowed to maintain some asset pipeline uniformity. I will reference here this #13923 because is releated. If some image based node in 2D not allow to select texture region, using asset texture lost some sense (why should i have atlas textures in my project if i need to have some of this assets duplicated?)@@

**Comment by reduz** [comment]
It's more like, atlas is only valid for drawing 2D textures as textures.

On Dec 30, 2017 8:51 PM, "Ranoller" <notifications@github.com> wrote:

Probably this should be allowed to maintain some asset pipeline uniformity.
I will reference here this #13923
<https://github.com/godotengine/godot/issues/13923> because is releated. If
some image based node in 2D not allow to select texture region, using asset
texture lost some sense (why should i have atlas textures in my project if
i need to have some of this assets duplicated?)@@

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/15194#issuecomment-354575577>,
or mute the thread

**Comment by Ranoller** [comment]
Anyway, nodes should not expose functionality that doesn't have. It's confusing.

**Comment by eon-s** [comment]
Lights should at least throw a warning when using unsupported texture types.

**Comment by reduz** [comment]
Can easily disallow that texture type in lights I guess.
