### ISSUE TITLE
StreamPeerTCP::put_utf8_string instert bytes on stream

### ISSUE THREAD

**Issue by Schweigert** [godotengine/godot#15228]
**Godot version:**
Godot 3.0 beta

**OS/device including version:**
Debian

**Issue description:**
```gdscript
	var a = StreamPeerTCP.new()
	a.connect_to_host('localhost', 3030)
	a.put_utf8_string('1.0\n')
	a.put_utf8_string('hehehehehehe\n')
	a.put_utf8_string('hehehehehehe\n')
```

Ruby Server:
```ruby
require 'socket'

a = TCPServer.new 3030
b = a.accept
b.gets
=> "\x04\x00\x00\x001.0\n"
b.gets
=> "\r\x00\x00\x00hehehehehehe\n" 
b.gets
=> "\r\x00\x00\x00hehehehehehe\n"
```
`\r\x00\x00\x00` is trash! In 2.1 it's work fine.

In godot 2.1:
Ruby Server:
```ruby
require 'socket'

a = TCPServer.new 3030
b = a.accept
b.gets
=> "1.0\n"
b.gets
=> "hehehehehehe\n" 
b.gets
=> "hehehehehehe\n"
```
- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.

**Comment by volzhs** [comment]
> In 2.7 it's work fine.

you mean godot 2.1?

**Comment by Schweigert** [comment]
Yes, I wrote wrong

**Comment by Dillybob1992** [comment]
Made a report about this I believe, but was told it was intended behavior. However, am not really sure

streem_peer.cpp:
```
void StreamPeer::put_utf8_string(const String &p_string) {

	CharString cs = p_string.utf8();
	//put_u32(cs.length());
	put_data((const uint8_t *)cs.get_data(), cs.length());
}
```

Uncommenting out that line seems to fix it

**Comment by raymoo** [comment]
I think this is because Ruby's TCPServer expects a null-terminated string, while Godot prepends the length. Is null-terminated strings a standard for TCP communication?

**Comment by raymoo** [comment]
By the way '\r\x00\x00\x00' is 13 in little endian, the length of the string you sent.

**Comment by Schweigert** [comment]
It is not a good idea to throw garbage on the network by taking up 4 more bytes with each string you send to be thrown away. :sob:
It would be good to separate in 2 methods, one that only writes the string, and another that writes the string next to its size.

**Comment by raymoo** [comment]
First I was wrong about how it was working in your Ruby example. What is actually happening is that gets treats the TCP stream as a text input and gets one line. You may already know this, I just wanted to clear up that you can ignore what I said about nul-termination earlier.

The length is not garbage because it is needed to know where the string ends. In your example you are treating the tcp stream as one long text input (like console input), but in game protocols it is common to structure the stream by mixing different kinds of data, including sending integers as their machine representation, not a text representation like "123".

Sending the string length first also gives a cleaner way to separate string messages, compared to using delimiters like newlines or the nul character, because you don't have to avoid use of the nul-character within the string. This is good for cases where the strings are user-provided, because then you don't have to come up with escape sequences to avoid processing the delimiter character.

I'm not super familiar with ruby, but I believe this is how you would read a Godot network string if you weren't allowed to make assumptions about delimiters:
```
# b is a TCP connection
string_length = b.read(4).unpack("L<") # Godot sends little-endian sizes
the_text = b.read(string_length)
```
This would probably go in some function or as a method of a custom class inheriting Ruby's TCP classes.

**Comment by Schweigert** [comment]
But 4 bytes are 3 bytes more than one ('\n') to delimite a string. It's are a good choise? :cowboy_hat_face:

**Comment by Schweigert** [comment]
It's working fine

```ruby
string_length = b.read(4).unpack("L<").first
 the_text = b.read(string_length)```
