### ISSUE TITLE
TileMap tile centering is changed compared to 2.1

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15249]
Godot 3.0
Windows 10 64 bits

I just gave a go at the tilemap node in 3.0 master and I quickly noticed that I was unable to reproduce the same tiles the same way as in 2.1, when they are centered. Was it intented?

Here is how my tiles look like in 2.1:

They are all centered,

![image](https://user-images.githubusercontent.com/1311555/34469821-b043a4e0-ef26-11e7-9762-952f7ec1b3d1.png)

And when a tile has bigger height, I move the center down to the "main" part of the tile:

![image](https://user-images.githubusercontent.com/1311555/34469826-cba0e3e2-ef26-11e7-93d8-1e5d4e93897f.png)

Which gives the following desired behaviour in a TileMap, once "tile origin" is set to "center":

![image](https://user-images.githubusercontent.com/1311555/34469830-f2ed0d36-ef26-11e7-869c-6a700c02952d.png)

Now, in 3.0, I tried the same setup and got different results.
That's what the issue is about: ground tiles get offset, as if the tile's center was actually top-left (which none of them are):

![image](https://user-images.githubusercontent.com/1311555/34469832-fa549b98-ef26-11e7-9f9b-2f65add03a12.png)

And wall tiles too:

![image](https://user-images.githubusercontent.com/1311555/34469837-08d62d76-ef27-11e7-95d1-239470294d83.png)

The only way I could remake this was to change all tiles in my tileset to have a top-left origin:

![image](https://user-images.githubusercontent.com/1311555/34469897-5fff0a46-ef27-11e7-8ccd-c55065dd39ab.png)

Which results in the same placement I expected.

**Comment by hoelzl** [comment]
This is probably not intentional. I believe this is the same problem that was mentioned in the last comment of @oreismatheus in issue #13062.

**Comment by Zireael07** [comment]
You mean get rid of centering tiles?

**Comment by Ranoller** [comment]
> Getting rid of alignment and offsets, with the new editor it's easier to create polygons now.
The changes on centering was intentional, someone thought that it was a good idea to align the rects instead of the tile pivot point... i dont agree with this since it's kind of more difficult to see mentally how things would fit.
I still think it's okay to have a pivot point (not a rect, like before) but having several offsets for collision oclusion and navigations is overkill and not needed.
I'm not sure if this could be solved meanwhile adding a process on the 2.1 to 3.0 export process to recalculate offsets of the collision, occlusion and navigations shapes and modivy the pivot to make sure it works now, but would actually depend on how the person who did the tilemap is aligning the tiles in the TileMap, so i'm not sure if that could be done

I´m too agree with that. Origin point meaning should be calculate the Z-Order point in the tilemap with other objects inside that tilemap and self, not offset texture and shapes. For me it can´t be kiked to 4.0 because I needed. There is no option to perform some kind of isometric and top-down games with actual behavior.  Offset individually every shape has no meaning. Offset texture with "Origin Point" has no meaning. This is the actual chaos of tilemap:
![TileMapChaos](https://user-images.githubusercontent.com/11712737/56079762-ce8b0280-5df8-11e9-9516-0216fe8a349a.png)
I have some "hacks" to fix this, i will try to accomplish a meaningful behavior to all of this. I´m trying to follow godot history from the beggining of the "chaos", it took me time to have a "pushable" solution because c++ and are "THE PAIN", but i can´t whait to 4.0 to finish and test my map generator.
I will follow the issue in this thread: 
https://github.com/godotengine/godot/issues/22989

**Comment by Ranoller** [comment]
Well.... it cost to me a lot (beeing not real programmer) but i change tile_map.cpp and tile_map_editor_plugin.cpp to get this result (left actual, right modifications):
![TileMapFix](https://user-images.githubusercontent.com/11712737/57331856-dd27b980-7119-11e9-88e7-aaeb372b4123.png)
I have to adapt to a recent master... and i implore for the grace of the gods for a merge in 3.2 no mathers if this will be killed and rewrited for 4.0. because in the actual state... i think that if tilemap remains in the actual state, version 3 of godot will end their cycle without a real TileMap.
