### ISSUE TITLE
Node relocated when changing anchors

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#15267]
**Godot version:**
Godot 3.0 Beta 2

**OS/device including version:**
Windows 10

**Issue description:**
When changing anchors of a node, upon update (like dragging the node or resizing its parent) it will change position. Maybe that is an expected behavior, but it's not beneficial to the workflow.

['Before' screenshot](https://i.imgur.com/nuxWwfB.png)
['After' screenshot](https://i.imgur.com/Z7cZAgq.png)

**I'm not talking about 'Layout'. This is about changing anchors through 'Anchors only' or directly in the inspector.**

**Comment by bojidar-bg** [comment]
Please make this an option, even if it on by default 😃

**Comment by groud** [comment]
> Please make this an option, even if it on by default :smiley:

What ? This is not a feature, it's definitely a bug.

**Comment by bojidar-bg** [comment]
I think I might have misunderstood something. I was speaking about #3979 (margin changing with anchors).

Managed to reproduce the bug as well -- setting "Left" sets "Right" as well.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.
