### ISSUE TITLE
AnimationPlayer: Allow randomized start positions of animations

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#15271]
Feature request:

Allow animations in AnimationPlayer to start at a randomly chosen point instead of at 0.
This could be a dice icon next to "Autoplay on Load".

Use case:
Imagine you have a animation that occurs multiple times in the same scene. (Candles, fire, or other character or environment idle animations)

Currently, they all start playing the same animation synchronized, which looks strange. Of course you can manually create a script to `seek()` to a random position on each node where that is required, but that is cumbersome.

**Comment by puppetmaster-** [comment]
This is my solution for a torch:
1. create AnimationPlayer with a func track
2. call randomLight() function
3. set AnimationPlayer to autoplay and repeat
this is the script part

```
extends Node2D

onready var light = get_node("Light2D")
onready var animationPlayer = get_node("AnimationPlayer")

func _ready():
	randomLight()

func randomLight():
	animationPlayer.set_speed(rand_range(8.0,10.0))
	light.set_texture_scale(rand_range(0.3,0.6))
	light.set_energy(rand_range(0.2,0.8))
	light.set_pos(Vector2(rand_range(-4.0,4.0),rand_range(-4.0,4.0)))
```

**Comment by volzhs** [comment]
https://twitter.com/reduzio/status/941799197774315525
from @reduz tweet

![image](https://user-images.githubusercontent.com/8281454/34514176-55eb5508-f0af-11e7-81f7-1afae44f14d9.png)

in my case, I have never needed this feature.
so... i think, it's not common use case.
and can be covered a few lines of code.

**Comment by noidexe** [comment]
You can create a single script that does `seek(rand_range(0, get_current_animation_range() ))`  on _ready. 
Attach that to any Animation nodes where you need that behavior. 
If you use scenes for candles, fire, etc. You only need to attach the script once per scene.

**Comment by mhilbrunner** [comment]
@volzhs Of course, thats the raison d'être for this issue: to discuss whether this is a common enough behaviour to warrant a PR.

Personally, I used this a lot in past games with idle animations for chars or environment, and when I started using AnimationPlayer and used a script like suggested above for both of my first two animations, I just thought "Huh, this may be common enough to warrant a one-click button?", seeing as it is fairly game-agnostic.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by idbrii** [comment]
This issue had high page rank, so now that I have a solution, I'll post it here. I was using Godot 4.3.

```gdscript
extends AnimatedSprite2D

func _ready():
    var max_frame = sprite_frames.get_frame_count(animation)
    play(animation)
    set_frame(randi_range(0, max_frame))
```

You pick the animation as normal in the Node, but this makes it start at a random frame instead of the one set in the inspector.

**Comment by ErraticUnicorn** [comment]
For people using AnimationPlayer:

```
func _ready() -> void:
	var animation_length: float = animation_player.get_animation("[YOUR_ANIMATION]").length
	animation_player.play("YOUR_ANIMATION")
	animation_player.seek(randf_range(0.0, animation_length))
```
