### ISSUE TITLE
FileSystem Tab default OS rename key shortcut

### ISSUE THREAD

**Issue by Demmios** [godotengine/godot#15289]
Godot version:
v3.0.beta.build2

Issue description:
If the FileSystem TAB is selected (not the viewport) when you hit the F2 key to rename the folder the Scene tabs change to 3d mode instead of allow to rename the file - by using F2 is a standard rename folder in windows maybe some aproach may be used for others OS

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/f9e9cc94cdfcf1bc1dd43e9d61e1394908835099.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
