### ISSUE TITLE
Double click on Signals action improvement

### ISSUE THREAD

**Issue by Demmios** [godotengine/godot#15287]
How about if you open the signals tab than you double click the signal and it jumps (or opens the script in the line you clicked) automaticaly to the referenced node.

**Comment by Dillybob1992** [comment]
This actually happens already but recently, it has been a bit buggy sometimes after double clicking on the signal it doesn't go to the method.  Can't seem to create an isolated example of it yet

**Comment by groud** [comment]
I mark this as a bug then

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by ibrahn** [comment]
if this is the same as #19527 then #20131 should fix it

**Comment by akien-mga** [comment]
Assuming fixed by #20131 then.
