### ISSUE TITLE
Disconnect and delete Signal script user option

### ISSUE THREAD

**Issue by Demmios** [godotengine/godot#15295]
**Godot version:**
3.0

**Issue description:**
Right now we can disconnect a signal by selecting the signal and clicking the button "disconnect" my suggestion would be to have another button maybe on its side with the option to disconnect and automaticaly delete all the signal script atatched to it or a popup message asking if the user wants to delete all the code related to that signal

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
