### ISSUE TITLE
wav reimport is inconsistent

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#15316]
**Godot version:**
Godot 3 59ce1757670ffc6ad5a9091b8def798880a1b1b5

**OS/device including version:**
macOS 10.12.6, Windows 10 x64

**Issue description:**
Some wav files files produce different result each time they are reimported. Import algorithms are supposed to be deterministic. Current behaviour causes people in the team commit modified .import files all the time.

**Steps to reproduce:**
Can be reproduced on this project: 
[project.zip](https://github.com/godotengine/godot/files/1603133/project.zip)

Delete .import folder to force reimport and watch how dest_md5 of the .wav file changes.

**Comment by NathanWarden** [comment]
I still think these hashes should go into a temp folder/file of some sort. There's no real need to commit them with the [asset_name].import files. I understand not having them in the .import folder since I believe that gets exported when the project is built. I personally don't mind having another ghost folder called .hashes or even .temp/hashes something like that. Probably a .temp folder so if there's any other throw away stuff in the future it can just be put in there.

**Comment by reduz** [comment]
@NathanWarden I don't really see any problem with the current approach. The .import file has a dependencies section where reimport happens if dependencies are modified, any other way seems more unnecesarily complex to me.

**Comment by NathanWarden** [comment]
It has given me essentially the same issues when importing on say Windows and Linux. Unless I explicitly add in eol rules for my dae files they are pulled out of git differently, so when I import it on Linux it shows up with hash A since it has LF endings, then when I import it on Windows it shows up with hash B since the working copy has CRLF.

It's not a problem for people more savvy with git, but I can easily see some development teams not realizing it's just line endings causing this and they'll blame Godot instead. They will constantly see all of their [dae].import files changing if they have either mixed OSes or people have configured Git differently during installation.

If these are stored in a ghost directory this problem is a non issue to everybody.

**Comment by reduz** [comment]
@NathanWarden I understand, but the problem you describe would fail anyway. As far as I know also, Git does not change EOL automatically unless you ask it do, doesn't it?

**Comment by NathanWarden** [comment]
@reduz The default setting when installing for Windows is that is automatically converts text based files to CLRF. The default on Linux converts to LF. So it will definitely cause issues. I used defaults on all my stuff and I noticed the issue immediately.

**Comment by NathanWarden** [comment]
Since you probably won't see it if you try and install Git again, instead if you watch any how-to install Git on Windows (on YouTube) you'll see the default option when installing Git on Windows is "Checkout Windows-style, commit Unix-style line endings". If the default was "Checkout as-is, commit as-is" then this wouldn't be an issue.

**Comment by QuentinCaffeino** [comment]
We have almost same issue but everyone in our command is using Linux (Ubuntu-based and Arch).
Each time I get an image and an .import file for it, it gets reimported and only md5 hash for .stex file is changed. We don't share .import folder. Shouldn't md5 be the same?

**Comment by akien-mga** [comment]
@QuentinCaffeino Would be better to open a new issue, this one was specific to WAV reimport and has been fixed.
