### ISSUE TITLE
Viewport rect of a viewport child of a control doesnt get updated when control resizes and viewport is set to render target

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#15322]
**Godot version:**
2.*, 3.*

**OS/device including version:**
any

**Issue description:**
Viewport node's rect value automatically updates whenever the viewport is a child of a control node- it updates to the parent control node's size.

This however doesnt work when the viewport is set to be a render target
This is a problem if you want to use a design that requires a viewport sprite to clone the viewport

**Comment by Calinou** [comment]
@blurymind Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
