### ISSUE TITLE
Signal connection editor: add a script icon next to nodes that have a script attached to them

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#15339]
signal connection editor- add a tiny script icon next  to nodes that have a script attached to them

Here is a mockup:
![mockup](https://user-images.githubusercontent.com/6495061/34579537-4ee547aa-f181-11e7-9525-d4d6199a742c.png)

It should make it much easier to find the intended node to connect signals to..

If you want to get even fancier- you could also add a connection icon on nodes that have connections already from the current node.
You can also set the script icon's tooltip to the name of the script file attached to it

**Comment by kareed44** [comment]
The common SceneTreeEditor control used in the connection dialog already has some logic to put icon buttons on tree items when  a script is attached. It's close to what we would need but cant be used directly because it would make other undesired changes. Does it make sense to organize and break up SceneTreeEditor::_add_nodes(), where the logic is, to facilitate an extension of SceneTreeEditor just for the connection dialog? This would us to override _add_nodes() to get the behaviour we need.

**Comment by nipunG314** [comment]
Making changes directly to SceneTreeEditor would lead to an inconsistent UI. If I am not wrong, the icons on the right side of the Nodes are intended as buttons.

What about colour coding each of the Node names that have Scripts attached to them? It would be like #24435, but in the other direction. Instead of hiding nodes with no scripts attached, we can highlight the ones that do have them.

**Comment by nipunG314** [comment]
This is what I have managed to do. The highlighter is completely optional and the user can select a custom color.

![script highlight 3](https://user-images.githubusercontent.com/24457793/52489594-a6a8d400-2be8-11e9-97c3-22145bf44093.PNG)
![script highlight 4](https://user-images.githubusercontent.com/24457793/52489595-a7416a80-2be8-11e9-9914-a8e25ea23e8d.PNG)

**Comment by kareed44** [comment]
I don't think this is a great solution. If anything, this is exactly what you aimed to avoid, an inconsistent UI. Highlighting does not immediately suggest that the node has a script attached, an icon does. It also add complexity and extra settings that don't seem necessary. Again, I think organizing and reusing the code in SceneTreeEditor that adds icon buttons to nodes makes sense. To be clear, I'm not suggesting adding the icons _as buttons_, just the icons would suffice. I'm just suggesting to reuse code that does almost the exact same thing as what we want with slight variation in this particular use case of SceneTreeEditor.

**Comment by blurymind** [comment]
You can use a different design for the indication icons than the one used for the button. Or make the icon slightly greyer/transparent so as to indicate that it is not clickable there

**Comment by KoBeWi** [comment]
Fixed in new connection dialog for 3.2
![image](https://user-images.githubusercontent.com/2223172/57171507-38556580-6e15-11e9-8e18-611e68ad27f0.png)
