### ISSUE TITLE
Inconsistent hover to focus dock

### ISSUE THREAD

**Issue by ianb96** [godotengine/godot#15353]
**Godot version:** 3f9f0b3db (2018-01-04 master)

**OS/device including version:** Windows 10

**Issue description:** 

The 2D Viewport, 3D Viewport, and the Animation Timeline all get focus when the mouse is hovered over them (except from a text field), but no other dock does. Other docks must be clicked on to receive focus. This is important for keyboard shortcuts as the Control that is in focus will receive the keyboard event first.
So, Should all docks get focus when hovered over, or just ones with keyboard shortcuts, or none?

**Steps to reproduce:**
Hover mouse over different parts of the editor.

**Minimal reproduction project:**

- [x] I searched the existing [GitHub issues](https://github.com/godotengine/godot/issues?utf8=%E2%9C%93&q=is%3Aissue+) for potential duplicates.
possibly related to #13237

**Comment by Calinou** [comment]
We should probably settle on one style or another by default (between "focus on click" and "focus follows mouse").

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
