### ISSUE TITLE
Incorrect work of HTTPClient.poll()

### ISSUE THREAD

**Issue by VitaZheltyakov** [godotengine/godot#15369]
**Godot version:**
All versions (2.1.x and 3)

**OS/device including version:**
All

**Issue description:**
The procedure HTTPClient.poll() does not change the Status, if there was a successful connection before (STATUS_CONNECTED) or there was an error before (STATUS_CANT_CONNECT).
As a result, the work of HTTPClient is incorrect for network failures. This can lead to critical errors!

**Steps to reproduce:**
- Create example of using the HTTPClient class (http://docs.godotengine.org/en/stable/learning/features/networking/http_client_class.html). 
- Perform one successful request (you get STATUS_CONNECTED). Not close application and HTTPClient.
- Disconnect your PC.
- Try the following request (you get STATUS_CONNECTED).

or 

- Create example of using the HTTPClient class. 
- Disconnect your PC.
- Perform one error request (you get STATUS_CANT_CONNECT). Not close application and HTTPClient.
- Connect your PC.
- Try the following request (you get STATUS_CANT_CONNECT).

Look at the work of the code HTTPClient.poll() (https://github.com/godotengine/godot/blob/master/core/io/http_client.cpp) and you will understand everything yourself.

**Comment by reduz** [comment]
I'm not quite sure I understand the problem. If it's not too difficult to fix feel free to submit a PR

**Comment by christopherjsmith** [comment]
I understand the issue here, but I'm not sure what approach we want to take on handling this.

* Connect
* Call `HTTPClient.poll` ->  STATUS_CONNECTED
* Disconnect PC from internet
* Call `HTTPClient .poll` -> STATUS_CONNECTED

Because the `poll` function doesn't actually do anything on some states, simply reports the last observed status from other commands, such as `request` etc. 

In the case of `STATUS_CONNECTED`, determining the best approach to identify the connection dropped is worth while.

For `STATUS_CANT_CONNECT`, we can basically try and connect again, i.e call `connect_to_host` again before reporting the status back.

**Comment by VitaZheltyakov** [comment]
The `poll` function must return the actual value, not the last status.

This bug allows you to perform a request when a connection is lost. This leads to a critical error.

Or this bug does not allow requests when communications are restored.

**Comment by reduz** [comment]
Oh, the bug is that disconnection is not detected? But as far as I know,
its perfectly valid to disconnect and reconnect a PC and expect TCP
connections to survive..

**Comment by VitaZheltyakov** [comment]
But because of this bug, we can do the request when the connection is lost. This leads to a critical error and the application hangs.

**Comment by VitaZheltyakov** [comment]
https://github.com/godotengine/godot/issues/15393

**Comment by VitaZheltyakov** [comment]
I tested this problem in Godot version 3.0.6 - the application does not crash anymore after the request.

**Comment by VitaZheltyakov** [comment]
I prepared a demo of the error.
[Error Demo.zip](https://github.com/godotengine/godot/files/2320408/Error.Demo.zip)

**Comment by akien-mga** [comment]
CC @godotengine/network

**Comment by Faless** [comment]
As I explained also in #4157 there is no way to detect a broken TCP connection without writing it.
This is HTTPClient, we can't have a keepalive mechanism, we cannot send random stuff to the server, and expect everything to work fine after that.
We can't send an HEAD request every time we do poll.
There is really nothing to do about this that I know of.

> This leads to a critical error and the application hangs.

Network failures happens, every day. What happens when the network disconnects between the moment you check the status and the moment you do the request. It will hangs all the same? How are we supposed to fix that? I think, if your application has a "critical error" when a network request fails (which again happens.. everyday.) then you should fix your code.

> Or this bug does not allow requests when communications are restored.

If you do a request, and that request fails, the status will then either be DISCONNECTED or ERROR.
If that's not the case, then it's a bug.
At that point you MUST, of course, reconnect before making another request.
A request as such should work (assuming the network actually came back up).

**Comment by VitaZheltyakov** [comment]
I wrote above that since version 3.0.6 the application does not hang.

You suggest not fixing problems, but writing additional code to bypass them. This is a wrong approach.

I want to remind you that this problem (updating the connection status) does not exist in Unity, no in UE, not in all browser-engines. So why should Godot work differently?

**Comment by Faless** [comment]
> You suggest not fixing problems, but writing additional code to bypass them. This is a wrong approach.

I'm telling you to EXPECT network request to fail from time to time, which is the CORRECT approach.
This is really BASIC networking best practices.

> I want to remind you that this problem (updating the connection status) does not exist in Unity, no in UE, not in all browser-engines. So why should Godot work differently?

I don't know, you tell me, you seem to be the expert on Networking, Unity, UE, Browser, you surely know the solution.

**Comment by VitaZheltyakov** [comment]
> I'm telling you to EXPECT network request to fail from time to time, which is the CORRECT approach.
This is really BASIC networking best practices.
Your decision is primitive. It excludes the use of a longpolling.

> I don't know, you tell me, you seem to be the expert on Networking, Unity, UE, Browser, you surely know the solution.
This problem is much more than it seems. It affects many parts of the engine. A simple solution does not exist.

**Comment by Faless** [comment]
> This problem is much more than it seems. It affects many parts of the engine. A simple solution does not exist.

I'm still waiting for any suggestion.
Because up until now it's been: `you are wrong` `your decision is bad` `others do it better`, `this is incorrect`.
Never once it has been `calling this function would solve the problem`, `implementing this algorithm would solve the problem`, `there is an example on how to do something similar here`.

It seems to me, you are complaining a lot, but have very little knowledge of the subject.
Again, if I'm wrong, and you know of a way to detect half open connection which can be implemented in an HTTPClient please tell me what it is.
Otherwise you are just wasting my time as I already spent hours trying to explain what the issue is, and why detecting half open connections cannot be done.

**Comment by VitaZheltyakov** [comment]
First, you suggest creating a new connection for each request. This does not allow the use of a longpolling. Therefore, I called your decision primitive.
Second, the following code should return the connection status:
```
http.poll()
http.get_status()
```
It returns the last status, but not the current one. It is not right. This problem does not allow the use of a longpolling.

I understand that the solution is not travial. Perhaps we need to add a new functionality to check the real status of the connection.

**Comment by Faless** [comment]
> First, you suggest creating a new connection for each request.

No, I suggest using the same connection, and reopen the connection if a specific request fails.

> I understand that the solution is not travial. Perhaps we need to add a new functionality to check the real status of the connection.

Perhaps you should do some research and learn that you can only detect cleanly closed connections, but not half-open/half-closed connection (like when you disconnect the cable) without writing on it.

**Comment by VitaZheltyakov** [comment]
> No, I suggest using the same connection, and reopen the connection if a specific request fails.

How are you going to do this? If the connection status is not updated, then this becomes problematic.

> Perhaps you should do some research and learn that you can only detect cleanly closed connections, but not half-open/half-closed connection (like when you disconnect the cable) without writing on it.

I agree with what you say, but it does not solve the problem. So I think that we need to add a new functionality to test the real status of the connection. This will be the easiest way to solve the problem.

**Comment by Faless** [comment]
> How are you going to do this? If the connection status is not updated

It is, when the request fail.

**Comment by VitaZheltyakov** [comment]
You do not understand the situation.
I will explain it in steps:
- We are establishing a connection.
- We send the request.
- We do not close the connection, because we use longpolling.
- The connection is physically broken.
- We see that there is a connection.
- We send a request and it hangs. We will not get an error.

**Comment by Faless** [comment]
First you say:

> This leads to a critical error and the application hangs.

Then you say:

> I wrote above that since version 3.0.6 the application does not hang.

Then you say:

>     * We send a request and it hangs. We will not get an error.

Does it hang, or does it not hang? Which one is right? I'm really confused.

In any case, can you provide example code that shows the error?

**Comment by VitaZheltyakov** [comment]
[Error Demo.zip](https://github.com/godotengine/godot/files/2394218/Error.Demo.zip)
I'm confused.
I made a simple demo. But I can not make a repeated request using a longpolling.

You can receive application hangup as follows:
Connect.
Manually break the connection.
Make a request.

**Comment by Faless** [comment]
@VitaZheltyakov 

The application hangs because you are doing busy wait in the GUI Thread.
If you, for example, use a timer for polling instead (and don't use a `while` loop) the application won't hang.
As I said, if you sever the connection, you don't get a clean close, and you can't detect it until the timeout is reached.
```gdscript
func connect():
	if (http.connect_to_host(host, port) != OK): return false
	# Busy wait on main thread!
	while(http.get_status() == HTTPClient.STATUS_CONNECTING or http.get_status() == HTTPClient.STATUS_RESOLVING):
		http.poll()
		OS.delay_msec(pollTime)
	return true
```

Additionally, I'm not sure what you are trying to do, but longpolling is usually a different thing.
See here for more info: https://www.pubnub.com/blog/2014-12-01-http-long-polling/

NOTE
---
I'm not denying that the HTTPClient is doing the proper polling (there is actually a PR for that #22191 ).
What I've been trying to tell you, is that **it is not possible to detect a severed TCP connection without writing on it** unless you wait for timeout (which is usually few minutes).

**Comment by VitaZheltyakov** [comment]
I understand your remarks. But we need to look at the situation from the practical side:
The application hangs on until the server time expires.
If we use longpolling, then this time is increased. That is, hang can be very long.

I agree that the use of waiting is not the best solution. But the use of a timer is also not the best solution. The correct solution is to use signals, but they are not in the HTTPClent.

The gist of the problem is that there are no connection testing functions in Godot
