### ISSUE TITLE
Add support for linking using gold

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#15364]
[gold](https://en.wikipedia.org/wiki/Gold_(linker)) is an ELF linker which can be faster than the traditional `ld`.

**Comment by est31** [comment]
[lld](https://lld.llvm.org/) is even faster than gold. You can see a talk on it [here](https://www.youtube.com/watch?v=yTtWohFzS6s).

**Comment by vnen** [comment]
Isn't this just a matter of setting the `LINK` option in the SCons command?

**Comment by akien-mga** [comment]
> Isn't this just a matter of setting the `LINK` option in the SCons command?

I've tried this (btw we wrongly use `LD` for this currently, but it does indeed seem that `LINK` is the proper variable), but it fails as we currently use `g++` as linker (on Linux) and not `ld` directly (`ld` is used behind the scenes by `g++`, but the call is slightly different so it fails with our `LINKFLAGS`).
So I'm not sure how to properly define what linker should be used by `g++` or `clang++` with our current setup using builtin variables.

On the other hand `gold` can be used by setting `-fuse-ld=gold` as linkflag:
```
scons p=x11 verbose=yes LINKFLAGS="-Wl,-verbose -fuse-ld=gold"
```
Just using `-Wl,-verbose` to actually see that gold is being used:
```
/bin/ld.gold: Attempt to open /usr/lib/gcc/x86_64-mageia-linux-gnu/5.4.0/../../../../lib64/crt1.o succeeded
/bin/ld.gold: Attempt to open /usr/lib/gcc/x86_64-mageia-linux-gnu/5.4.0/../../../../lib64/crti.o succeeded
/bin/ld.gold: Attempt to open /usr/lib/gcc/x86_64-mageia-linux-gnu/5.4.0/crtbegin.o succeeded
/bin/ld.gold: Attempt to open platform/x11/godot_x11.x11.tools.64.o succeeded
/bin/ld.gold: Attempt to open platform/x11/context_gl_x11.x11.tools.64.o succeeded
...
```

**Comment by akien-mga** [comment]
Just an example of how the MongoDB team implemented a preference for `ld.gold` when available in SCons: https://jira.mongodb.org/browse/SERVER-17995
It's non trivial as they test compiling a simple program to check if the linkflag is supported.

**Comment by Web-eWorks** [comment]
Maybe I'm missing something, (and I don't really know SCons) but it seems like the solution is to add a `use-gold` option that adds `-fuse-ld=gold` to `LINKFLAGS` and whoever's building it can enable it at their discretion.

**Comment by Valentactive** [comment]
I added in my local repo an option to use LLD when using clang (if you don't tell it, it defaults to the default linker and that's often the one from GCC). I did basically what @Web-eWorks said here but for LLD instead of gold and added the check only when **"using_llvm"** is set too. In my case I set **"use_lld"** to false per default as not everyone who uses Clang also uses LLD (support still varies on the 3 big desktop platforms).
I did it only for Linux as I can't test for other platforms right now, but it would be basically the same for each platform two lines or so. Could be done the same for using gold.
Here my repo:
[https://github.com/Valentactive/godot/tree/add-lld-linker-option](url)

**Comment by hpvb** [comment]
lld can't be used together with gcc's LTO. IT makes little sense to make this a default in any way.

**Comment by Calinou** [comment]
> lld can't be used together with gcc's LTO. IT makes little sense to make this a default in any way.

I guess it would still be useful to support it for development purposes (where you don't use LTO), so one can iterate faster when working on Godot.
