### ISSUE TITLE
Node._ExitTree/Dispose not invoked when exiting play mode

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15391]
**Godot version:**
`master` / 8e8240450edc48f4fb379e593a4ef7f54ab656b7 (with the fix applied from #15385)

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
When the editor exists play mode, neither `Dispose` nor `_ExitTree` methods of active nodes which are loaded in the scene get invoked.

It could be problematic in certain scenarios, like when a node holds a reference to an external resource (i.e. database connection) that needs to be released explicitly.

I'm not sure if it also happens when an active scene is replaced with another one without stopping the game itself.

Ideally, it'd be better if nodes can get such a notification in a cascading manner in both of the scenarios.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
