### ISSUE TITLE
The deleted nodes are hanging in the inspector.

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15416]
**Godot version:**

**OS/device including version:**

**Issue description:**
inspector doesn't refresh when delete a node. 

**Steps to reproduce:**
1. delete a node
2. click another scene tab
3. back to scene

![rf2](https://user-images.githubusercontent.com/33985414/34644281-721af73c-f344-11e7-95a5-dd8c57470d1d.gif)

**Minimal reproduction project:**

**Comment by icnikerazah** [comment]
latest build on macos. sorry

**Comment by bfloch** [comment]
I think I got this one. Deleting does not update the editor_history.
I can come up with a fix I guess, however I am not sure how the undo could work if the editor_history is being changed.
Since I am new actually knowing what editor_history does might help :-)
I am glad for any hints.

**Comment by bfloch** [comment]
I think we've hit watergate.

This bug manifests itself not only when switching scenes. Pretty much the whole concept of editor_history is a bit leaky.
You can for example create a node, remove it and still go back and forth with the history to it in a similar fashion.

Now comes the fun part: It seems that the reason is the _cleaup_history does not work, because it checks for invalid references. But it seems to hold a reference itself :)

If I am not mistaken this means **you can never properly delete ANY node in godot editor**. It will always "leak" in the history. This seems to be true even in Godot 2.1. It's a matter of time before a godot session explodes.
Since history is not stored this probably never bothered anyone as after restart it is clean again.

So the proper fix is to fix the EditorHistory from what I can tell.

**Comment by bfloch** [comment]
The "leaked" nodes after deletion seem to not be related. I worked around it in the PR by checking if a node in history is still in the tree. That fixed this issue.

**Comment by akien-mga** [comment]
Fixed by #15481.
