### ISSUE TITLE
Allow globally intercepting instantiation process of nodes in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15434]
**Godot version:**
`master` / 0e6e98a65f26c915b5717992ba881cf33406c8bf

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
It's more of a feature request than an issue. I think it'd be nice to have some way to customize the way nodes are created by Godot in C# project.

One use case would be implementing a dependency injection layer on top of Godot, which I'm trying to achieve in my project at the moment.

Ideally, we could intercept the instantiation process somehow, then inspect what dependencies the node declares then resolve and inject them before we passes it back to the engine.

It'd also be used to extend functionalities of the engine by returning a subclass of the created node instead. This way, you don't have to find and replace every nodes that you want to customize manually , and also could be useful in such a scenario like modding an existing code base.

Probably, a simple factory or filter type API would be sufficient to satisfy such requirements.

**Comment by Zylann** [comment]
Why can't it just be a custom function you make in C# instead of calling the engine directly? (That's how it works on a Unity project I work on)

**Comment by mysticfall** [comment]
@Zylann Because, in that case I need to modify every source code of `Node` derivatives, which could be cumbersome or even impossible (in case of modding, etc).

**Comment by Zylann** [comment]
@mysticfall I don't see where is the problem even for modding though... if you mod a game making use of a custom injection framework, the modders have to account for that system too anyways.
Also, why do you need to modify every Node derivatives? Changing Godot to use injection everywhere could be a quite involved task... I thought you wanted that for your scripts only (which could easily make use of C# attribute that your framework detects).
Also, note that since every Object in Godot is scriptable, you would need to track the instancing of everything (nodes, resources, objects). Personally I don't see why the engine needs to change for making such framework possible, but that's just my opinion^^

**Comment by mysticfall** [comment]
Let's say I have a DI framework that can resolve and inject dependencies of a node by calling `Context.Resolve(this)`.

To do this, one first need get a reference to the `Context` object by referencing it by node path then invoke `Resolve` from `_Ready()` or `_EnterTree` callback.

Of course, it's not a terribly complex thing to do. However, the problem is you need to do that for every single node you create in you game that needs DI feature. Maybe you can write a base class that does that for you, but in that case you also need to write it for each specific type since C# doesn't support mixin or inheriting from a generic type (i.e. `class DIBaseNode : T where T : Node`).

Another problem is, when dependencies are usually injected in the constructor of a class, because it's considered a best practice, there's no way to achieve that using the above mentioned method.

On the other hand, modifying Godot to address this issue doesn't involve anything about implementing its own injection system (though it could be useful in future) or something similar.

Rather, all it needs to do is letting the user register an implementation of a callback or factory class somewhere and simply invoke it with a newly instantiated class before the engine call it's `_Ready()/_EnterTree()` or delegate instantiation itself to it when specified.

Admittedly, it's not a feature that would be needed for many users but for the amount of work that is needed, I suppose it could open up interesting possibilities for those who want to build framework type system on top of Godot.

**Comment by Fido789** [comment]
Just for the record, I support this issue. Proper DI is essential for any modern framework.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
