### ISSUE TITLE
Export Arrays & Lists in C#

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#15467]
It doesn't look like you can export arrays and lists in C#, so this would be a nice feature to have.

**Comment by redxdev** [comment]
You can export arrays in C#, just only of specific types.

All of the following work as exports:

```csharp
[Export]
int[] foo;

[Export]
string[] bar;

[Export]
float[] baz;
```

It seems that most "basic" types (numeric, string, etc) work fine, but nodes/resources/NodePath/etc don't work (do they work in gdscript?). Also, `List<T>` doesn't seem to be supported.

**Comment by 11clock** [comment]
@redxdev More types would be wanted. I have an array of packed scenes I need exported.

**Comment by nmearl** [comment]
Any hope this will be considered for 3.1?

**Comment by Radbuglet** [comment]
Disclaimer: I never did C++ before and I'm kind of incompetent when it comes to Godot engine development.

I'm trying to implement this because lists of `PackedScene`s are very useful to me.

I think I know the following things:
- [`csharp_script.cpp::_update_exports `](https://github.com/godotengine/godot/blob/a0180fa86ec54ac4f7e1b7c8f154364f0525b76a/modules/mono/csharp_script.cpp#L1966) takes the exported property/member and returns a `PropertyInfo` instance which is used by `EditorInspectorPlugin`s which, given a valid node and export `hint` and `hint_string`, provide the `Control` nodes necessary for the inspector.
- `PropertyInfo`s are constructed with a reference to an `Object` and a property name. The property that is referenced must be a `Variant` type.
- Variant arrays, dictionaries, etc don't actually have a fixed type for their elements, rather, a hint is provided for convenience in the editor so the users have the "illusion" of a typed array.
- Hints are specified via two properties: `hint` and `hint_string`. `hint` is an enum of `PropertyHint` (defined in [`core/object.h`](https://github.com/godotengine/godot/blob/master/core/object.h#L54)) that can be viewed as a sort of type of exported data that can be handled via `EditorInspectorPlugin` using the second property, `hint_string`, which is sort of like a glorified storage of arguments.
- The `PropertyInfo` generated by the [`gdscript_parser.cpp`](https://github.com/godotengine/godot/blob/a0180fa86ec54ac4f7e1b7c8f154364f0525b76a/modules/gdscript/gdscript_parser.cpp#L4454) is different from the one generated by [`csharp_script.cpp`](https://github.com/godotengine/godot/blob/a0180fa86ec54ac4f7e1b7c8f154364f0525b76a/modules/mono/csharp_script.cpp#L2295) given equivalent code (the later doesn't even include `PackedScene` in it!)

Here's what I'm confused about:
- There's no `PropertyHint` for arrays. Instead what seems to be used is a `PROPERTY_HINT_TYPE_STRING` where `hint_string` seems to be used to specify that it is, for example, an array of `PackedScene`s. I couldn't find any documentation for the format of the `hint_string` in this context so if anyone can point me to some form of documentation, that would help me very much. What seems odd is why not use property hint mode `PROPERTY_HINT_TYPE_STRING` for everything? What if you want an array of `PROPERTY_HINT_MULTILINE_TEXT`? Wouldn't `EditorInspectorPlugin`s have to check two things instead of one? Is this a design oversight or was this a deliberate choice?

Any thoughts?

**Comment by Radbuglet** [comment]
I did a lot of searching around in the game engine to figure out how arrays were handled in the inspector. This post will describe how everything works as well as pinpoint what code needs to be changed to fix this bug.

# Important Classes
## Variants
[Variants](https://github.com/godotengine/godot/blob/a0180fa86ec54ac4f7e1b7c8f154364f0525b76a/core/variant.h#L79) are the base classes of Godot which almost everything extends. _Eg: A `PackedScene` inherits `Resource` which inherits `Reference` which inherits `Variant::Object`._

## PropertyInfo
[`PropertyInfo`](https://github.com/godotengine/godot/blob/04847ef5f98d9a20a72286c44cc26302ec82dec5/core/object.h#L160) allows you to declare a property belonging to a class. It takes in the `variant type` of the property, a [`PropertyHint`](https://github.com/godotengine/godot/blob/04847ef5f98d9a20a72286c44cc26302ec82dec5/core/object.h#L54) enum value named `hint` used to change the behavior of how the inspector renders this property and a `hint_string` passed to whatever implements the hint.

## EditorProperties
The [`EditorProperties` class](https://github.com/godotengine/godot/blob/cce2e4b07c1c4b6f2f9d72cac340d9f9ecbb790e/editor/editor_properties.cpp#L2850) handles the creation of the inspector value management control nodes.



# Relevant variant hint handlers

**Variant::ARRAY** where `hint= PROPERTY_HINT_TYPE_STRING` and `hint_string={default variant type of nil array elements}/{hint to be used when rendering elements in inspector}:{hint string to be used when rendering elements in inspector}` creates an [`EditorPropertyArray` instance](https://github.com/godotengine/godot/blob/c8994b56f95c2623f60e48cd86d6e2368708e3ca/editor/editor_properties_array_dict.cpp#L451).

**Variant::Object** where `hint= PROPERTY_HINT_RESOURCE_TYPE (ignored)` and `hint_string={ResourceTypeClassName as a String}` create an [`EditorPropertyResource` instance](https://github.com/godotengine/godot/blob/cce2e4b07c1c4b6f2f9d72cac340d9f9ecbb790e/editor/editor_properties.cpp#L2619).


# Example of `PropertyInfo` generated by GDScript

The following GDScript code exports an array of `PackedScene` resources:
```gdscript
export (Array, PackedScene) var packedScenes
```

The `PropertyInfo` is constructed as so:
```cpp
PropertyInfo(Variant::ARRAY, "packedScenes", PROPERTY_HINT_TYPE_STRING, "17/17:PackedScene")
```

The `hint_string` is parsed as follows:

The 1st `17` is the int value of the [`Variant::Type` enum](https://github.com/godotengine/godot/blob/04847ef5f98d9a20a72286c44cc26302ec82dec5/core/variant.h#L82) which corresponds to `Variant::Object`. (`PackedScene` inherits `Resource` which inherits `Reference` which inherits `Variant::Object`)

The 2nd `17` is the int value of the [`PropertyHint` enum](https://github.com/godotengine/godot/blob/04847ef5f98d9a20a72286c44cc26302ec82dec5/core/object.h#L54) which corresponds to `PROPERTY_HINT_RESOURCE_TYPE`.

Everything after the `:` is the `hint_string`. In this case, we're passing `PackedScene` to the handler for `PROPERTY_HINT_RESOURCE_TYPE`.

In mono, the equivalent code constructs the `PropertyInfo` as follows:
The `PropertyInfo` is constructed as so:
```cpp
PropertyInfo(Variant::ARRAY, "packedScenes", PROPERTY_HINT_TYPE_STRING, "17:")
```

The editor currently treats this as an array of variants. In order to fix this, we must fix the creation of `hint_string` in [csharp_script.cpp](https://github.com/godotengine/godot/blob/cce2e4b07c1c4b6f2f9d72cac340d9f9ecbb790e/modules/mono/csharp_script.cpp#L2292).

**Comment by Radbuglet** [comment]
Turns out in mono, you can optionally pass in a `PropertyHint hint` and `String hintString` into the `Export` attribute. However, `PROPERTY_HINT_TYPE_STRING` doesn't exist in the mono version of the enum so you have to do some evil wizardry like so:

```cs
[Export((PropertyHint) 24, "17/17:PackedScene")]
public Godot.Collections.Array<PackedScene> specialPackedScenes;
```

Still annoying to do so I'm going to try and fix the creation of the mono Array hint string.

**Comment by neikeq** [comment]
This is already supported on latest master and will be available in 3.2.

@Radbuglet From what I understand, the problem you describe is that exported resources of an specific type don't include information about the specific type, right?

**Comment by neikeq** [comment]
All right, so #26662 together with #28519 most arrays are supported. The only thing missing is support for `IEnumerable<T>`. We already support `IEnumerable` but we can't get type hints from that.

**Comment by aaronfranke** [comment]
I don't seem to be able to export node arrays:

```
    [Export]
    public Node test1;
    [Export]
    public Node[] test2;
    [Export]
    public int test3;
    [Export]
    public int[] test4;
```

![1](https://user-images.githubusercontent.com/1646875/57063493-732e9080-6c91-11e9-9f73-97985fecf107.png)

**Comment by bojidar-bg** [comment]
@aaronfranke That's expected. See #7821.

**Comment by neikeq** [comment]
#28974 fixed several bugs and added support for `IEnumerable<>` and `IDictionary<,>` with type hints (although the Godot inspector doesn't support type hints for dictionaries yet). As such, this issue can be closed.
