### ISSUE TITLE
Can't cancel polygon/line editing with right click

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#15474]
**Godot version:** fe841fe

**Issue description:**
In Godot 2 you were able to right click to stop editing a polygon object in the editor. In Godot 3 there's no way to stop editing a Line2D/polygon shape without clicking on a different node first.
You should be able to right-click or press ESC to cancel line drawing.

**Comment by poke1024** [comment]
Right click to end adding point works for me (on 1748ce74cc10fd0bf79f3258f74509e5ad8cc4f7). Key input (i.e. esc) is still not working yet, but soon I believe (see https://github.com/godotengine/godot/issues/12505).

**Comment by reduz** [comment]
I changed right click to cancel, for consistence with the rest of the editors. ESC and RMB will cancel, while ENTER (or cllicking on the first point) will close the polygon.

**Comment by rosshadden** [comment]
@reduz I really liked RMB closing the polygon. I didn't know Enter closed it too until reading this and will obviously use that now if RMB isn't changed back to closing polygons, but I want to make a case for changing it back:

Our hands are necessarily already on the mouse when drawing the polygons because points are drawn with LMB, so having to move the hand from the mouse to the Enter key every time we draw a polygon is not a great user experience. When RMB closed the polygons, the process was not disjointed. Since this workflow applies every time a polygon is drawn, what may seem like a slight inconvenience from a get-off-my-lawn Vim user with RSI pain really does add up over time into what I consider a significant accessibility decrease.

Doesn't making Escape cancel already satisfy the issue here, as the OP says "You should be able to right-click **or** press ESC to cancel line drawing"?

**Comment by rosshadden** [comment]
As a follow-up, I instinctively just tried hitting Enter on my number pad to close a polygon because it is at least a lot closer to my mouse, but discovered that only the main Enter key closes them. If you don't agree with the points I raised above and don't want to change it back to increase accessibility, I will at least make a PR to add numpad Enter support.
