### ISSUE TITLE
AnimatedSprite with "Playing" enabled in the editor causes changes to scene files on every save.

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#15479]
**Godot version:**
beta2 mono

**OS/device including version:**
Windows 10 1709

**Issue description:**
An AnimatedSprite with "Playing" enabled will have its frame property changed in the editor. This is expected, however saving the scene will save the new value of the frames property. This becomes a problem when using source control, as you end up with unnecessary changes to scene files.

This is made even worse by the fact that the scene is saved whenever you click the "play" button in the editor, and even if the scene hasn't changed as long as the frames property is currently different it will still save.

**Comment by akien-mga** [comment]
That's "normal", but definitely annoying. So it would be nice to find a way to prevent that.

**Comment by Ranoller** [comment]
Mmm... There is not yet an option to not save scene in previsualization?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
