### ISSUE TITLE
(2D) Crash on drag and drop scene file on empty scene

### ISSUE THREAD

**Issue by Shockblast** [godotengine/godot#15470]
**Godot version:**
3.0B 37ca542d2bfd9aac296e82e30a76117090dea08e
Compiler VS2017
SCons 2.5.1
Python 2.7

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
When I drag a scene (not empty and previously saved) to a completely empty new scene (2D) a dialog box appears with some options, when I choose one and click on "Ok" godot crash.
Could the same thing be done when a scene is instantiated as a Node? as a suggestion (when the scene is empty in 2d and 3d)
![godotcrash](https://user-images.githubusercontent.com/5357217/34655482-5d20c3b6-f3e9-11e7-8f22-747c2260a773.gif)

**Steps to reproduce:**
Create a project
Create a new scene, add a node and save file
Create a empty scene (no add nothing)
Drag from file system the scene created (with node) and drop to a empty scene (In 2D)
select any option from the menu and crash >:D !

**Minimal reproduction project:**
just create a empty scene and drag an drop the scene file in 2d mode
[GodotBeta.zip](https://github.com/godotengine/godot/files/1610325/GodotBeta.zip)

**Comment by akien-mga** [comment]
Related to the merged #13166. CC @Krakean

**Comment by Krakean** [comment]
@akien-mga
Can take a look only on 13th January, currently on vacation without pc :-/

**Comment by bfloch** [comment]
I think I got the fix. Will do some more testing and send a PR later tonight.

**Comment by bfloch** [comment]
I hope the PR is what users would want/expect.

As to the bug:
The reason was throwing a PackedScene onto a scene without root.
Instead of failing instead I do the behaviour of "File -> New Inherited Scene".
You will get an error dialog if you try to drop multiple files on a scene without root.  

Along the way I try to improve/fix minor things.

- New: Allows for multiple files to be dragged over
- Added error when multiple nodes are dropped in scene **without** scene root
  - Removed TTR: "This operation requires a single selected node.", "I see.."
  - Introduces TTR: "Can not instaniate multiple nodes without root."
- Fixes "Can't add_child, already got a parent" error
- Reduced multiple resource loading by casting
- Make sure to not _show_resource_type_selector if only PackedScenes are being dropped

Give it a test. Here in action:

![fixed_issue_15470_crash_dropping_empty_scene-min](https://user-images.githubusercontent.com/2116566/34707426-7595b5c6-f4db-11e7-8f58-61d04f3bd00f.gif)

**Comment by henriiquecampos** [comment]
This solution seems better than expected, it makes all sense to inherit a scene when instantiating a packed scene into empty scenes. well thought. Thanks for that!
