### ISSUE TITLE
Deleted nodes not freed in editor

### ISSUE THREAD

**Issue by bfloch** [godotengine/godot#15481]
**Godot version:**

Godot 3.0 beta 2, latest 37ca542d2bfd9aac296e82e30a76117090dea08e but also Godot 2.1.4

**OS/device including version:**

Fedora 26 - x86_64

**Issue description:**

Memory of deleted nodes is not freed.

**Steps to reproduce:**
- Create many nodes (duplication)
- Watch the memory growing
- Delete the nodes
- Memory still at highest point 
- Note: Internally ObjectDB still returns the instance from the id

**Minimal reproduction project:**

Probably not necessary.

This is partially related to #15416 where the issue was found.

**Comment by bfloch** [comment]
Btw: If the nodes are not freed because of undo or similar, at least we should be cautious with checks against ObjectDB for deleted objects.
I still wonder if undo/redo will be able to free these objects eventually.

Feel free to close this ticket if it turns out to be by design.

**Comment by akien-mga** [comment]
Yeah I was thinking this might be due to `UndoRedo`. I don't think there's a system that cleans up the UndoRedo stack, so you can in theory undo everything you did in your session (albeit since UndoRedo tends to be a bit buggy, it might break before you manage to do that :P).
But it does make things hard to check for deletion indeed if they continue living on in the UndoRedo stack, not sure how to improve that.

**Comment by akien-mga** [comment]
I discussed it with @reduz and he confirmed that deleted nodes are kept in memory for UndoRedo. They're eventually freed when the UndoRedo's stack is cleaned, or when the editor is closed.
