### ISSUE TITLE
HTTPClient.query_string_from_dict does does not handle nested dictionaries

### ISSUE THREAD

**Issue by VitaZheltyakov** [godotengine/godot#15503]
**Godot version:**
All versions (2.1.x and 3)

**OS/device including version:**
All

**Issue description:**
`HTTPClient.query_string_from_dict` does does not handle nested dictionaries (see examples). Now the nested dictionaries are transformed into an unconvertible construct.

**Steps to reproduce:**
Now:
`var dic = {
	'arg1' : 'foo',
	'arg2' : {
		'sub1' : 'boo',
		'sub2' : 'koo'
	}
}
print(http.query_string_from_dict(dic))`
Return `arg1=foo&arg2=%28sub1%3Aboo%29%2C%20%28sub2%3Akoo%29`. This is wrong. 
Need: `arg1=foo&arg2=sub1%3Dboo%26sub2%3Dkoo`

**Comment by bojidar-bg** [comment]
Generally, this is server implementation dependent.
For example, PHP would expect it as: `arg1=foo&arg2[sub1]=boo&arg2[sub2]=koo`.
Node.js's core library would encode it as: `arg1=foo&arg2=`.

Not sure what should be done in this case.

**Comment by VitaZheltyakov** [comment]
@bojidar-bg Does URLdecoding not work the same way? on PHP and Node.js

**Comment by vnen** [comment]
> Does URLdecoding not work the same way? on PHP and Node.js

No, there's no standard specification for collections. PHP has a convention and for Node.js it depends on what lib you use for URL decoding. I've used Node.js libraries in the past that didn't support any array/dictionary format.

In the case of Godot, it encodes as something that Godot itself can recognize. I don't  think this is a bug.

**Comment by VitaZheltyakov** [comment]
Oh my god ... what are we talking about ...
Now Godot transforms the enclosed arrays into an incomprehensible construction. This construct does not understand for PHP and does not understand for Node.js.
Is not this a bug?

**Comment by Faless** [comment]
> Oh my god ... what are we talking about ...

They are talking about the standard, which as they both tried to explain, do not include encoding complex data types. URI scheme is byte-level and talks only chars ([see RFC](https://tools.ietf.org/html/rfc3986#section-2.1)) while HTML forms do not use any special dict/array encoding either as they do not support them (see [www-url-encoding specification](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1)).

As an example, here is what happens when testing with Javascript:
```javascript
var params = new URLSearchParams()
params.append('key1', 'val') // key1=val
params.append('key2', 42) // key2=42
params.append('key3', ['a','b','c']) // key3=a%2Cb%2Cc& (a,b,c)
params.append('key4', {'sub1': 'a', 'sub2': 'b'}) // key4=%5Bobject+Object%5D ([object Object])

console.log(params.toString()) // prints: key1=val&key2=42&key3=a%2Cb%2Cc&key4=%5Bobject+Object%5D


// Testing your "Need"
var params = new URLSearchParams('arg1=foo&arg2=sub1%3Dboo%26sub2%3Dkoo')
console.log(params.get('arg2')) // prints: sub1=boo&sub2=koo (a string, not an array nor object of some kind)
```

Whatever we do in this case would be non standard. We could just return an error when encoding non standard data types, but I think it's also fine this way where we encode using `var2str`, in the end, that's what JS does.

**Comment by VitaZheltyakov** [comment]
First, in your example, the mapping of nested arrays does not take place correctly (`key4=%5Bobject+Object%5D`).
Secondly, to work with JavaScript, it's better and more logical to use JSON.
Thirdly, I think that it would be correct to make a separate transformation for PHP and node.js

**Comment by Faless** [comment]
> First, in your example, the mapping of nested arrays does not take place correctly (key4=%5Bobject+Object%5D).

Which is exactly my point, because there is no standard mapping for object/dictionaries, so JS just use use `toString` (which for object is `[object Ojbect]`).

> Secondly, to work with JavaScript, it's better and more logical to use JSON.

Same when working with Node.js (which is JavaScript btw) and PHP

> Thirdly, I think that it would be correct to make a separate transformation for PHP and node.js

No, it would be wrong, because they are not a standard.
We are not going to implement some PHP specific functionality.
