### ISSUE TITLE
Provide way to customize generated core Mono source files

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#15548]
**Godot version:**
`master` / 3c0dd37744cb0d84d5bbbb4c50263951f888cae3

**OS/device including version:**
_Manjaro Linux 17.1-rc2_

**Issue description:**
It's somewhat related to #15434 in motivation, and like that issue this is also a feature request rather than a bug report.

Currently, source codes of the core API types (like `Node.cs`) for C# binding is automatically generated during the build, and thus cannot be easily customized.

Normally, it wouldn't be much problem for most of users who just want to create their games with the engine. But there could be others who want to customize Godot to suit their specific needs, or to experiment with it before they submit a pull request for new features.

To be specific, I'm currently doing such experiments to find a way to make Godot to be more conforming to the idiomatic C# approach, and my own personal preferences.

For example, I'd like to experiment with exposing node notifications like `_Ready`, or `_onInput` as C# events or even Rx `IObservable`s. Or I want to write some DI layer and integrate it with Godot, which involves extending some of the base types like `Node` or `Object`.

I think one of the greatest advantage of Godot over other proprietary game engines is that it's completely open source, so it allows you to customize the engine in a way you best see fit.

So, I believe if we could provide a way for a user to modify the core C# API and do experiments with it, it might attract those who have specific requirements, and encourage people to contribute more to improve Godot's C# API to make it feel more natural and easy to use for those who are familiar with the language.

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by PJB3005** [comment]
Even if it's not for personal use, IMO we should definitely still have this if only for the main engine to allow adding methods you can't really describe in the regular Class DB, such as things using generics.

**Comment by neikeq** [comment]
I've been thinking of making the generated classes `partial` and somehow allow customizing the API generation process. Also adding an option for those who want to have the API project inside the Godot project with a `ProjectReference` instead of an assembly `Reference`. All of this is low priority though.

**Comment by mysticfall** [comment]
@neikeq That sounds like a reasonable approach to me. We'll probably have some time before the whole C# support to stabilize, so I'd be happy if such a feature will be implemented before people starting to think about building more advanced stuffs in C#.

**Comment by exts** [comment]
Can this be closed? I believe this is supported now for the most part. https://github.com/godotengine/godot/tree/master/modules/mono/glue/Managed

**Comment by mysticfall** [comment]
@exts It looks like it became much easier to work with the core files. But does it include @neikeq's idea with using `partial` keyword or allowing project reference to the core project?

If not, I wouldn't mind waiting for another few versions before seeing those features included since they could be quite useful for certain use cases while being low priority issues.

**Comment by neikeq** [comment]
Generated classes are `partial` now, but I didn't add any way to extend/customize the bindings generator, nor a way to use a `ProjectReference` to reference the API project.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
