### ISSUE TITLE
c# support exporting user-defined structs to gdscript

### ISSUE THREAD

**Issue by vzex** [godotengine/godot#15547]
version :  Godot 3.0 beta 2
in c#:
i want to EmitSignal with user-defined strucst to gdscipt, but in gdscript, there are only a few inner types supported,like numbers, strings,..etc
where to use:
case 1:
  ```
 c# script:
        struct userT;
        AddSignalXXX
        EmitSignalxxx(string, int, userT)
   gdscript  : 
        bind signal xxx: 
        func __onxxx_callback(string, int, userT(this is always null now))
```
case 2:[serialize structs and deserialize during transdata in c/s(online) games ]
  ```
 c# script:
        struct userT; -> and register userT to gdscript(like tolua++)
        network recv() -> parse into struct(userT) -> trigger callback in gdscipt and pass userT->process data in gdsript   
```

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
