### ISSUE TITLE
Control node margin properties not conforming to standards

### ISSUE THREAD

**Issue by UgisBrekis** [godotengine/godot#15569]
**Godot version:**

Godot 3.0

**OS/device including version:**

**Issue description:**

Currently the way godot handles margins doesn't conform to the standards in a way, that setting all the margins to let's say 100 doesn't create a gap between the parent and the child controls of 100px, but rather moves the child control 100px to the left and 100px to the bottom.

I added images to better describe the issue in action and what should be the expected result(keep in mind that in the example images top and bottom margins are 100; left and right 200)

Blue box is parent Control node
Green box is child Control node
Yellow box is child control

![godot_margin_comparison](https://user-images.githubusercontent.com/9309589/34792979-c238fba6-f641-11e7-9404-7eeb3dbe8509.jpg)

![godot_margin_proposal](https://user-images.githubusercontent.com/9309589/34792856-52696018-f641-11e7-9d4f-041aef83f39b.jpg)

If you guys agree on this, I'd be happy to fix this and submit PR. :)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
AFAIK that's by design, but @groud can tell more about it.

**Comment by groud** [comment]
This was the previous design, but it does not fit the floating anchors design.

The current way of defining margin is more consistent, independently of the anchor's position, the node's side is at `margin` pixels of the anchor position, whether it's positive on negative. Effectively, this is counter-intuitive when the anchors are set at the parent's boundaries. But when the anchors are at the top left for example, it is understandable that all margins are positives, since the node is at the right of the anchor.

Honestly, the current design is a lot easier to explain than the one you propose: "the margin values are just offset relative to the positions anchors, defining the position of each node's side." And to be honest, the "margin" name is quite misleading, maybe it should be called "offset" or something like that.

**Comment by UgisBrekis** [comment]
Alright, thank you guys for the input.

I don't really agree that my proposal is harder to explain, since basically term "margin", as far as I've encountered it, is always is being used the way I explained, however what you said @groud it makes absolute sense. Usually the user sets margin for a container and then its children are being offset by that value, however in this case it is the container itself that is being offset which leads me to saying that just as you mentioned, I think the biggest issue is the term "margin" rather than the logic (also it is easier just to rename the property in case a lot of people feel the same way as I do about this rather than change the logic).

Would love to hear more opinions on this.

**Comment by groud** [comment]
Yeah, personnaly I would say renaming to "offset" should be a good idea, but I think its too late now. Maybe for 4.0.
The renaming would also avoid the confusion with styleboxes, as their margins are all positive and correspond to to the case you describe.

**Comment by Linicks** [comment]
As a new Godot user, I would say that using the word "margin" is very misleading. The current behavior in Godot isn't consistent with other UI development environments, making it harder to understand.  The word "offset" is much better at describing the actual behavior.   The illustrations presented in this proposal would also be a nice addition to the documentation, and would help clarify the intended behavior.

**Comment by coppolaemilio** [comment]
As a Godot user and tutorial maker coming from CSS the use of the word margin is very misleading indeed. I like the proposed idea of renaming it to something else, and since the web (specially css) is so widely adopted I would try to adopt those terms to reflect the same kind of behavior.
I'm not saying to copy all css properties to control nodes, but at least margin and padding would be nice to behave the same in Godot.

**Comment by Calinou** [comment]
Control's `margin` property has been renamed to `offset` in the `master` branch to avoid confusion with CSS.
