### ISSUE TITLE
Automatic conversion of TileSet source scene to TileSet resource on save

### ISSUE THREAD

**Issue by Bladum** [godotengine/godot#15577]
**Godot version:**
3,0 Beta 2 

**Issue description:**
Auto export tileSet to tres file on tileset save would be nice feature.

**Steps to reproduce:**
Create tileset as usual. Export it to Tres file using menu. New Tres file is created but its manual process. Automatic export on Save of tileset would be nice.

**Comment by eon-s** [comment]
I guess you mean the engine to remember the tscn was exported to a tileset, but what if the changes you made were for another new tileset? 
Or what if you do not want to merge but overwrite?

**Comment by Zylann** [comment]
Tbh this would be a non-issue if we had a dedicated tileset editor (getting there with the autotile dock though)

**Comment by vnen** [comment]
Another option is to accept Scenes as TileSets with the new import system.

**Comment by blurymind** [comment]
@vnen I though about the same thing - it would definitely simplify the process

@MarianoGnu mentioned in another issue that there is a plan to allow the new tile editor to directly load atlas image files - that would be even better to have
Since the autotile editor can be used to set collision, occlusion, pathfinding and everything else that we would use in 99% of the cases - there will be no need to even create a new tileset scene in most cases. Just load the tiles image file straight into the new tile editor. Of course we can still keep the option to use custom tileset scenes

**Comment by MarianoGnu** [comment]
@blurymind i'm not sure about what do you mean with "directly load atlas image files", TileSet loads textures and then you select a region, that's exactly what an atlas is...

There's an open PR for allowing edit every tile on the new Autotile/Tileset Dock ( #15262 ) but it has been kicked to 3.1, maybe you can convince @akien-mga to merge it in 3.0 if finished (since it's an usability improvement rather than a new API feature)

**Comment by blurymind** [comment]
@MarianoGnu I am referring to the ability to load an image file as a resource into the TileMap node without the requirement to create a new scene file, set nodes in it to be tiles and then export from it another file. The current workflow makes it a pain to setup and update tilesets - even with the new autotile editor

You noted in another comment that it is a planned feature:
https://github.com/godotengine/godot/pull/15262#issuecomment-354762925

**Comment by MarianoGnu** [comment]
@blurymind you can already do this from TileSetEditorPlugin's toolbar button, adding a Tile will add an empty tile to the tileset, you can also merge from scene using this menu instead of selecting the file to merge, this is better since you can can reload the file without saving it. Only missing feature is displaying on inspector only current tile instead of all (maybe hundreds) of them
![imagen](https://user-images.githubusercontent.com/1776044/35072075-da528e3e-fbc1-11e7-82e2-6961efcab8cb.png)

**Comment by MarianoGnu** [comment]
none of these improvements are being worked on right now because feature freeze, they wonr make it in 3.0 no matter how many PR we make, that's we we try to focus on bugfixes

**Comment by phil123456** [comment]
"create from scene is the dumbest thing ever" you have to create scene and every tile so this is bloody useless
is it so hard to have a built in function that slices a bloody images grid like and create the tile set automaticaly ?

**Comment by MarianoGnu** [comment]
@phil123456 now that autotile editor is kind of functional this can be done much more easily, Damar Indra have plans to make an sliced tile to work this case out

**Comment by blurymind** [comment]
@MarianoGnu we need a "Create from Image file" function. And when the artist updates the image file, so should the tileset

The intermediate scene should be optional, not required imo

**Comment by akien-mga** [comment]
What's the status on this @MarianoGnu? Is it addressed by recent changes, or should it be moved to the 3.2 milestone?

**Comment by MarianoGnu** [comment]
Well, importing tilesets from scenes makes no sense anymore imho, making tiles is much faster with the new editor than creating thousands of sprites in an scene, also the scene converter doesn't support TILE_ATLAS or AUTOTILE by default, the only thing that this can do and the tileser editor can't is setting the pivot.

@reduz have mentioned that he wanted to rework the TileSet/TileMap completely to make it more straightforward (maybe making different kinds of resources and nodes for every kind of cell/isometric/hex maps)so i dont know. At least i dont import

**Comment by akien-mga** [comment]
Indeed, this is no longer so relevant now that we have the new TileSet editor, so closing.
