### ISSUE TITLE
Tile Set  with option to insert new Tile + update existing Tile Maps using this tileset

### ISSUE THREAD

**Issue by Bladum** [godotengine/godot#15575]
**Godot version:**
3.0 Beta 2 

**Issue description:**
When adding new tile to tile set its indexed are reorganized. When working dynamically changing both tile map and tileset, tile map becomes corrupted once tileset has new tile IDs. 

Option to add or insert new tile ID to tileset would be useful, that will reorder IDs of tiles used on the tile map with used same tileset. 

**Steps to reproduce:**
When adding new tile to tileSet somewhere in the middle of the tileSet, then all tilemaps that are using this tileset will have its tile broken as different IDs are used now.

**Comment by akien-mga** [comment]
Normally when you export the TileSet, there's an option to merge with the existing one (ON by default) that prevents this. Is it not working?

**Comment by Bladum** [comment]
Well the point is that tilest is ok. Tilemaps that uses this tileset is not aware about that change and displays wrong tile once its merged. Its a problem if you have dynamic both tilemaps and tileset. Point is to make two functions that add or insert a tile into tileset and synchronize tile id with tilemaps

**Comment by akien-mga** [comment]
No, what I mean is that the merge function ensures that the IDs of existing tiles are not modified. So if you add new tiles, they are appended at the end of the tileset (even if they're inserted in the middle in the source scene), so TileMaps using the tileset aren't modified.

**Comment by Bladum** [comment]
What about order of tiles in tileset ? Key feature here is to add them into existing list ( they are grouped by functionalitY) so they can be in any order both on tileset node tree ( when adding them) when using them on tile map and still maintain proper id number for existing tilemaps

**Comment by ElfEars** [comment]
Yeah, I'd agree that this problem needs to be fixed. I'm a guy who builds all his levels in tiles and I get it... A LOT.
Rearranging tiles without destroying every map in the game needs to be a thing.
As for the merge option with rearrangement. Last time I checked it annoyingly just added a duplicate set onto the end. Will have to check the latest version.

**Comment by hadbabits** [comment]
I've also found this to be bothersome. I keep my tiles arranged under separate nodes like 'Walls','Roofs', etc. And inserting a new one usually breaks my tilemap one way or another.

At least now I know about the Merge option so I can **uncheck** it: Otherwise it leaves tiles I've edited or deleted. 

Glad Godot is suited with some tile tools, but it's got a ways to go methinks.

**Comment by Calinou** [comment]
PS: Please check whether this feature is still missing in Godot 3.2.1 before creating a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
