### ISSUE TITLE
GdScript Extension methods

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#15586]
I often find that I want to add functionality to an existing class but want to call it in a traditional method.
Yet I cant.

For example, the node class has something like get_child which is called like so:
my_node.get_child("blah");

Now, I want to add some additional methods to node what I have to do at the moment is:
Util.my_custom_node_method(my_node, "blah");

I have a static class which takes the node and any parameters and does what I need to do.
Ideally I want to write:
my_node.my_custom_node_method("blah");

The idea is for the user to be able to extend existing classes. C# has such functionality, and calls them extension methods:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

Something like extension methods for gdscript would clean up a lot of code for me.

**Comment by vganin** [comment]
This is very useful in Kotlin: https://kotlinlang.org/docs/reference/extensions.html

Basically this is a simple syntactic sugar which puts the first argument of a function to the position of so called _receiver_:
```kotlin
fun oldEnsureOk(error: Error)
fun Error.newEnsureOk()
```

The most cool property of this is that it allows to make proper call chains with non-member functions
```kotlin
// Old ways
fun translate(matrix: Matrix): Matrix
fun scale(matrix: Matrix): Matrix
fun rotate(matrix: Matrix): Matrix

fun main() {
    val matrix = rotate(scale(translate(Matrix())))
}

// New way
fun Matrix.translate(): Matrix
fun Matrix.scale(): Matrix
fun Matrix.rotate(): Matrix

fun main() {
    val matrix = Matrix().translate().scale().rotate()
}

**Comment by mnn** [comment]
Too bad the PR never made it. I would like to see this feature as well. There are possible workarounds, but they have their downsides.

In [Golden Gadget](https://gitlab.com/monnef/golden-gadget) I am using a wrapper to supply new functionality for arrays:

```gdscript
var weak_alive_monsters = G(monsters).filter("x => x.is_alive && x.hp < 10").map_fld("name").val
```

It's not bad, but there is a cost of creating the wrapper object/instance (the `G` creates an instance). Also a user may easily forget to unpack the value (`.val`).

Second approach is more traditional FP via function composition/application (and its reverse varitants):
```gdscript
	var text_input = "Morbi id mauris pep erisus. Aenean."
	var three_words_capitalized = GG.pipe_(text_input, [\
	  GG.words_raw, # ["Morbi", "id", "mauris", "pep", "erisus.", "Aenean."]
	  [GG.take, 3], # ["Morbi", "id", "mauris"]
	  [GG.map, GG.capitalize], # ["Morbi", "Id", "Mauris"]
	  GG.unwords # "Morbi Id Mauris"
	])
```

While more universal (works for any values) and doesn't require unpacking, it has its share of downsides. One is that GDScript doesn't allow importing functions nor supports global functions, so one has to always state the "namespace" (autoloaded singleton, the `GG`). Since this approach relies on passing functions, and GDScript doesn't support referencing functions directly, there has to be for every function its `FuncRef` counterpart, or this approach is not really practical (forcing user to create `FuncRef` for every function use is verbose and tedious - `GG.unwords` vs `funcref(GG, "unwords_")`).

```gdscript
func unwords_(xs: Array) -> String: return arr(xs).join(" ")
var unwords = funcref(self, "unwords_")
```

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/758, which is related to this feature proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
