### ISSUE TITLE
Custom selection region for a node

### ISSUE THREAD

**Issue by Bladum** [godotengine/godot#15599]
**Godot version:**
3 beta 2

**Issue description:**
Is it possible to define custom region usually its a rectangle to a node that will be used to select node in editor by mouse click ? 

My custom node is inside tileset and has unique shape that overlap others. Its hard to select them easily in editor. 

Do we have to add one node more to achieve that effect ?

**Comment by Bladum** [comment]
In case desired boundary is not rectangle then we cannot use existing node functionality to cover that

**Comment by akien-mga** [comment]
CC @groud, looks like another user wanting to override `_edit_get_rect` :)

**Comment by groud** [comment]
The question is, shall we open the `_edit_* ` functions to GDscript. And if so, how should be do it ?

**Comment by groud** [comment]
Also, now we have the `_edit_is_selected_on_click` for custon shapes, but it still cannot be overriden via GDscript.

**Comment by akien-mga** [comment]
Well we currently fake virtual functions like that by prefixing them with `_` (done already), and then making the engine check if `_my_virtual_function` is defined in the script and call it if yes; otherwise default to the internal value.

See e.g. how `get_item_rect` was implemented for Node2D in 2.1: https://github.com/godotengine/godot/blob/2.1/scene/2d/node_2d.cpp#L217-L226
(note that it's actually a virtual method defined in CanvasItem itself)

**Comment by remorse107** [comment]
I'm also working on a plugin.  My thought is that if there is this push to not bloat the engine and that we should extend by use of plugins, then the plugin interface needs the ability to allow for node selection as it does for built-in node types.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Giwayume** [comment]
https://github.com/godotengine/godot-proposals/issues/5289
