### ISSUE TITLE
Godot analytics driven design of new features

### ISSUE THREAD

**Issue by Bladum** [godotengine/godot#15602]
**Godot version:**
3 beta 2

**Issue description **
Do we have or plan any kind of analytics that track developer activity in editor in regards to:

1) automated bugs logging to godot server ( as option in debug panel) during game testing inside editor itself
2) automated nodes usage tracking to know how each standard node is actually used (popularity amongst developers)

1+2=3

And 3 is data used to define on which focus further development ( buggy level * popularity ) from whole engine perspective

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
There is currently no such thing as "telemetry" in Godot. Remember that automated analytics reporting has inherent privacy issues, so I don't think it will be considered.

Besides, node "popularity" wouldn't be a very useful metric, as any node in Godot is potentially useful, even to a small number of users.

**Comment by vnen** [comment]
> automated bugs logging to godot server ( as option in debug panel) during game testing inside editor itself

That's useless. We have over 2500 open issues here and not enough manpower to sort them. Almost all of the errors shown in the debug panel are a problem in the game logic, not an issue with Godot itself, we would gain nothing by knowing them.

> automated nodes usage tracking to know how each standard node is actually used (popularity amongst developers)

And? What can we do with this info? I'm pretty sure Sprite is used way more than Viewport, but just because their functions are wildly different and you need many of one but only few of the other.

----

You have to understand that Godot is not a business where users are their clients. The software is provided as is, and people work on it on free time. Godot developers do hear the request of users, but only to an extent. The development follows a pretty much fixed roadmap while trying to solve the issues with the current engine. That's only so much we can do, having more data won't help to solve the issues.

**Comment by mhilbrunner** [comment]
Have to say I mostly agree with vnen and Calinou. Although keep in mind even nonprofits like Mozilla use analytics heavily to drive descisions on development :)

Maybe it would be useful to have data during discussion on whether certain features should be added (or remain) in core or be done as plugins - or be deprecated.

But yeah, privacy issues, public image issues & development effort is currently more needed elsewhere I think.

**Comment by groud** [comment]
The only reason why I think analytics would be useful would be retrieve data about the editor's tools and settings usage. That would allow removing unused tools/options, determine which buttons to move from menus to the main interface etc...

**Comment by Bladum** [comment]
@groud this is what i was talking about only for editor

**Comment by LinuxUserGD** [comment]
I think automated bugs logging makes sense in case of "Please include this when reporting the bug on https://github.com/godotengine/godot/issues" (Output)

**Comment by akien-mga** [comment]
Automatic bug reports are useless, as most of the time they will come without steps to reproduce and minimal example project, making them very hard to fix since we won't know what the actual bug is.

**Comment by akien-mga** [comment]
Time has passed but I still think we don't need to add such telemetry for the time being - as for driving the design of new features, this GitHub issue tracker and the interactions we have with users on other channels give us plenty of material to define the roadmap already :)
