### ISSUE TITLE
Can't update position in animation editor

### ISSUE THREAD

**Issue by thankjura** [godotengine/godot#15646]
**Godot version:**
3.0.beta.custom_build.702e28f

**OS/device including version:**
gentoo/gtx1070/nvidia-drivers-390.12

**Issue description:**
Can't update pose in animationplayer editor

**Steps to reproduce:**
create animation, move cursor in timeline

**Minimal reproduction project:**
[anim_bug.zip](https://github.com/godotengine/godot/files/1627852/anim_bug.zip)

![peek 2018-01-13 02-51](https://user-images.githubusercontent.com/2144212/34899903-c93b82c6-f80c-11e7-9c67-cfdcd9a5cb1a.gif)

**Comment by bfloch** [comment]
I can replicate this.

Must be a regression within the last days' commit.
Specifically this falls through now:
https://github.com/godotengine/godot/blob/master/editor/plugins/animation_player_editor_plugin.cpp#L992

@bojidar-bg You think this is related to 9b8e8b2220b4e2bac3310262d3d1cd7a8eb3b0a5 ?

**Comment by capnm** [comment]
The commit 9b8e8b2220b4e2bac3310262d3d1cd7a8eb3b0a5 last altered the editor and probably broke it …

**Comment by bojidar-bg** [comment]
Grr, knew something was wrong with the current_animation...
Will be able to fix it later tonight, but if someone wants to fix it earlier, there are a two main options:
1. [easiest] AnimationPlayerEditor should set some metadata about the current animation, instead of relying on set/get_current_animation, or
2. [best] AnimationPlayer should get a new `get/set_assigned_animation`, which would unconditionally return `playback.assigned` and would execute those commented lines when set: https://github.com/godotengine/godot/blob/587645741035e0325ddb6b7d191c8b1d14f3729a/scene/animation/animation_player.cpp#L991-L994

**Comment by thankjura** [comment]
Any news?

**Comment by bojidar-bg** [comment]
Yes, starting to work on it now. Seems like Saturday night is not the best time to promise things for..
