### ISSUE TITLE
Track all resources with a unique ID instead of a res:// path

### ISSUE THREAD

**Issue by NathanWarden** [godotengine/godot#15673]
What I think would be a better generalized solution for all resources, would be for each resource whether script/mesh/material/etc to simply have a unique id that would be stored in an import file. So, each resource would have the unique ID instead of a file path. The unique ID could then be associated with each resource. So if a script of any type, material, texture, audio file, etc would no longer be dependent on a specific path.

This would allow a user to rearrange their project even very far into development without having to "Fix Dependencies" since everything would be automatically know where every resource is internally.

This would require Godot to scan the project when you load it and create a Map of each asset ID and it's path, and then when a script/material/audio slot has UniqueID in it, it will internally know that ID X belongs to path X. If an asset is moved, then it's import file is also moved and the Map is updated with the new path.

This would allow all resources to be moved around and literally nothing would ever break.

So assets would be loaded via the following pseudo code:
`// This will not break if the user moves the material`
`mesh.material = LoadResource(resource_paths[material_id]);`

instead of:
`// This will break if the user moves the material`
`mesh.material = LoadResource(material_path);`

**Comment by Zylann** [comment]
Ah, someone finally raised the question xD
I've been thinking about this for a long time, but never posted because it's quite debatable, and if it were to happen it would at least be for Godot 4.0, unless you are talking about a system where people define their ID manually, asset by asset... though I had that too in my notes.

I had a TXT to note stuff about this, here it is, sorry if it's quite long:

https://pastebin.com/tXnLgCaB

This thread is about considering GUID-based asset management for Godot, aka Unity3D-like (you'll see comparison a lot).
 
I'm pretty sure this was thought about at some point, and I know it may not happen anytime soon,
but I couldn't find any discussion about this here, at least to see why it wasn't considered, or even if people realize what this is.
 
I gathered my thoughs after all this time working with Godot. Even if a GUID system is rejected, these concerns remain valid.
Paths are not a bad decision, it's simple and makes sense... up to a point.
 
Here is why I think using paths gets limited in the context of a game engine:
 
 
1) Moving or renaming assets in Godot is a dilemma, even more for non-coders.
    This is the biggest asset design issue in Godot IMO, and still going to be AFAIK.
    Even if the editor attempts to update references when files are moved from dock, there are still issues with the design itself.
    Importance given to file path of everything is too high, especially in such a collaborative and dynamic domain.
 
2) The editor doesn't update all refs when using the filesystem dock (related to some existing issues)
 
3) The editor can't deal with files moved externally (from file explorer or version control)
    How do you git mv?
 
4) Resolving dependencies on scene opening takes time, especially on large projects
 
5) Resolving dependencies is not recursive (so all referenced scenes and resources need to be manually opened and fixed)
 
6) Resolving dependencies manually is prone to embarrassing errors
    For example, swapping a scene to another, which fucks all instances, and need to re-resolve the scene again
 
7) Even if some scenes (TSCN) are readable, mostly experienced coders and eventually some artists will modify them directly
 
8) Resolving dependencies requires to modify too many files.
    This produces version control diffs and conflicts in  files that usually have nothing to do with the assets being moved,
    and other people end up having to merge them (in real life, not everyone is good or even willing to do this).
    This just never happens with GUIDs.
 
9) External resources have an indirection ID in TRES/TSCN
    This produces even more unwanted version control diffs and conflicts when a reference is added or removed,
    because it shuffles the secondary ID everywhere.
 
10) Although good organization always helps, things always change. Paths don't always scale well on big projects.
    Making games takes a long time, collaboratively and things can change very often.
    in real life projects with medium to large teams can't afford a full-freeze of the project just to rename and move files around.
    Sure it doesn't prevent some teams to succeed with just file paths, and like all things, with experience you get around it...
    but you can't get around the very design of it, which can improve.
 
bonus) Since Unity became mainstream, many users nowadays take for granted that moving assets just works.
    this can make teams on big projects freak out when considering Godot over Unity3D.
 
 
 
Now, here is why I think GUIDs as primary asset referencing would improve Godot:
 
 
 
1) GUIDs make an asset globally identifiable regardless of its path or even its project.
    It makes the asset easy to move around and share across projects.
    Even embedded resources can be fetched identically, because a GUID is not tied to a particular storage logic.
 
2) Moving an asset doesn't produce any version control diff beyond itself, because the GUID doesn't have to change.
    Only people working specifically on the file will have to deal with conflicts
 
3) Moving an asset can be done from anywhere (editor, system, VCS...), and the editor has no work to do
 
4) Storing a GUID needs a companion .meta file of some sort.
    It can also contain what in Godot we used to store as .import or .flags.
    This meta file has to be moved/renamed too when the asset is moved/renamed.
    In worst case, not doing this makes the engine generate a new GUID and produce the usual dependency fix dialog open.
    Many Unity users know this by experience, and Godot also has already a similar gotcha with .import files anyways.
 
5) GUIDs can be read in TSCN once you know how it works.
    They are just a character sequence that "names" the asset uniquely, so they can be read or even written as part of a text resource to reference another.
 
6) People don't have to deal with GUIDs directly. A drag-and-drop workflow perfectly works.
    The only time you would have to, is when you merge a conflict in a resource involving a GUID.
    In best case you can solve this with proper diff tool that tells you which GUID is what,
    in worst case you grep the GUID to know which asset is concerned.
 
7) GUIDs can coexist with fetching assets by path.
    Coders can still preload() and load() with a path if the resource filesystem is important.
    The path is also still accessible obviously, if the resource comes from a file.
    There can be an alternative path format, "id://the_guid", to get an asset by GUID (just a wild proposal),
    which the editor would use by default when resources get assigned from within the UI
 
8) GUIDs would be the primary resource referencing system used by the engine.
    It has to be only one. However, as point 6) states, it doesn't mean we can't fetch by path ;)
 
9) Looking up assets by GUID just needs the engine to parse the project files without even loading the assets.
    The editor does this anyways, for other reasons though.
 
10) A uniquely identified resource doesn't need further indirection (which is the case in TSCN/TRES format)

**Comment by NathanWarden** [comment]
> I've been thinking about this for a long time, but never posted because it's quite debatable, and if it were to happen it would at least be for Godot 4.0

@Zylann I'm glad to know I'm not alone desiring this. I thought about it having to wait until 4.0 too and that was my first impression, but after some thinking I don't think that's actually the case. It's not API breaking and there's a pretty straight forward way of dealing with resources that are already tracked via res://path and that's simply by checking if the resource path/id data starts with res:// or not. If it starts with it then it needs an ID, then it can continue the load process. That could all happen transparently without user interaction as well.

I'm happy to read your thoughts on GUIDs... thanks :)

**Comment by hsandt** [comment]
I'd like to mention a few alternative approaches to feed thought, although I would also be inclined to use GUID everywhere.

(note that imported resources already use a kind of GUID suffix in the .import folder (e.g. `icon.png` asset -> texture in `res://.import/icon.png-487276ed1e3a0c39cad0279d744ee560.stex`), so this about other resources like scene files)

### Redirectors

Unreal Engine leaves a virtual Redirector at the initial location of a moved asset. This allows referencing assets to continue reference the old path. However, this causes some issues:

1. It adds one level of indirection (discussion above is about avoiding that)
2. The user may think that the reference paths have not been updated and think it's a bug (esp. if the Redirector is invisible)
3. The Redirector must be made visible to show to the user what happens under the hood, but that also pollutes the Assets panel. Depending on the implementation, the Redirector may store as a file at the old location (which will be seen in VCS), or defined inside the project description (also visible in VCS, but many redirectors will be seen as one file change).

The advantages:
1. Referencing assets are not changed
2. It's possible to resolve the indirection at any time (typically when the user has more time to afford a scanning) so old references are updated, and this can then be committed in VCS separately from the change that moved the assets in the first place (if it was a big change, this can help not making it even bigger). This corresponds to a Fixup in Unreal.

Reference: https://docs.unrealengine.com/en-us/Engine/Basics/Redirectors

### Recursive/neighborhood scan

This one comes from iTunes (!). If you moved a track in another location, iTunes will add a `(!)` mark near the track when it detects it. When you try to play the track, iTunes suggests you to Locate the missing file by selecting a new path.
Once you have done that, iTunes will also search for other missing files with similar original paths (e.g. in the same album), searching moved files in the new path. It also seems to be able to find missing files in subfolders and sibling folders.

This method doesn't change the way Move is handled, only makes scanning more performant if you have moved many files.

I couldn't check if Godot is not already doing something similar though, because I don't have an example where you would move many non-imported resources (I only have PNGs to work on...).

---

My first issue was actually with moving the Main scene (set in Project settings > Application > Run) as it is only referred to by path. To create a working example, we could prepare a set of nodes referring to many scenes and move all those scenes elsewhere? What other resources are non-imported so we can demonstrate the issue?

**Comment by willnationsdev** [comment]
> What other resources are non-imported so we can demonstrate the issue?

Scripts are another non-imported resource. If we suddenly decided to use GUIDs, then I assume we'd have to have some kind of .meta file that goes along with it though. Or perhaps we could get away with a .meta folder at the project root so we don't have to move pairs of files around all the time? Idk how most of that works with .import files atm, so I'm not sure.

---

Related to #7402 and my WIP PR #22181. All CustomTypes do is allow us to map a name to a file path and bind an optional icon to it. And it only works in the editor. If we really did have a GUID system, then I believe we could also allow users to optionally bind a name and/or some metadata (via #18591 ?) to it that would allow users to specify names for *any* resource, even at runtime.

One of the things that Godot is missing is some way of referencing reflection data for user-defined types (basically anything that ClassDB can do for engine types). Having a centralized, runtime-accessible system that knows the names of scripts *and* scenes would finally allow us to write logic that allows us to perform operations that reference specific types without having to load scripts by path to perform type checks or iterate through a project and catalog all of the scripts and scenes that exist which extend a particular script.

And with the introduction of #20318, we'd be able to add reflection data to scripts using annotations, effectively allowing us to mirror other ClassDB methods for scripts like getting a list of properties affiliated with a class by name alone. These are important resources to have if one wishes to make data-driven applications, especially ones that have editors included.

So, I believe this Issue is related to many problems people have found related to gathering data about user-defined types.

**Comment by lexum0** [comment]
How about doing it like Xcode? The file is internally linked to the file's UUID in the project file and the filename must be unique, if two are found then it uses the first one. The UUID is generated upon import.

So that way it's very simple to use, every filename is it's own ID with an internal UUID for internal referencing and if you need to differentiate files you do it by name. Otherwise it's very confusing to have two files named the same and having a different purpose.

**Comment by silkentrance** [comment]
How about splitting this one up into an API that will give us instances of UUID or UUID strings, and the other stuff that makes use of it?

Here is a link to a cross platform UUID/GUID library: https://github.com/graeme-hill/crossguid/blob/master/src/guid.cpp

Perhaps this can be included with the OS singleton interface, e.g. OS.uuid() : Uuid/String?

**Comment by MuffinManKen** [comment]
The bits about decoupling the res: paths would be nice, but I would be **thrilled** if the sequential resource IDs were replaced with a UUID.  My git history is nearly unreadable at times and merging branches with scenes can be nearly impossible.

**Comment by Xrayez** [comment]
## Workaround

Note that currently you can use a [`ResourcePreloader`](https://docs.godotengine.org/en/latest/classes/class_resourcepreloader.html) node which can act as a resource database mapping a resource name of your choosing to an actual `res://` path. It still tracks any resource by path but this also has a surprising benefit: when you move those assets, the refactoring system already implemented in Godot would rename those paths in any `ResourcePreloader` node for you, and you can fetch any resource just by name then:

```gdscript
var my_scene = $preloader.get_resource("my_scene") as PackedScene
```

![godot-resource-preloader](https://user-images.githubusercontent.com/17108460/71169823-8911b580-2262-11ea-8016-6887c3b33be1.png)

You can have multiple resource preloader nodes to group specific assets, and wrap them in a singleton for quick access.

---

Note that any exported resource via script `export(Resource) var` can also be handled by the refactoring system similarly so that the path doesn't need to be hardcoded into a script.

Talking about IDs, paths and scripts which seems to be related: #33360.

**Comment by Zylann** [comment]
@Xrayez this only solves part of the issue. You have to add such node to scenes or as a singleton (to preload ALL assets of the game?). Moving assets outside of Godot still causes trouble, VCS will still have extra diffs, they would not be portable between projects if paths change, and you still have to give a somewhat readable (and unique) name to every asset which means one day it may need to change too. Also, all the work Godot currently does parsing the entire filesystem to find paths to rename could be made unecessary by using IDs.

**Comment by Xrayez** [comment]
> to preload ALL assets of the game?

Given some limitations as in #13954, preloading most commonly used assets may be a decent compromise between slow game startup times and the smooth gameplay experience at run-time.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/471, as feature proposals are now tracked on the Godot proposals repository.

**Comment by ignaloidas** [comment]
> Closing in favor of [godotengine/godot-proposals#471](https://github.com/godotengine/godot-proposals/issues/471), as feature proposals are now tracked on the Godot proposals repository.

I don't think this issue and that proposal are the same solution. My proposal concerns internal representation in in .tscn files to make them friendlier to VCS's, while this is a wider scope proposal concerning usage inside scripting as well.

**Comment by willnationsdev** [comment]
@ignaloidas I would recommend that a new proposal is opened to explicitly account for that subtly different case then.

**Comment by Xrayez** [comment]
Some issues which could be prevented if we had such a system: #31045, #26188, #40991 (mainly talking about resource remapping system which relies on having different file paths).

**Comment by Flavelius** [comment]
This issue should probably be reopened as the linked proposal is not related and the issue of res based paths is still in effect throughout godot.

**Comment by Calinou** [comment]
@Flavelius A new proposal should be opened for this instead :slightly_smiling_face:

**Comment by Zireael07** [comment]
@Calinou: I was sure we have a proposal for that, and we do afaict: https://github.com/godotengine/godot-proposals/issues/471

**Comment by Flavelius** [comment]
@Zireael07 https://github.com/godotengine/godot/issues/15673#issuecomment-648466264

**Comment by Calinou** [comment]
For people stumbling upon this issue from a search engine, note that this is being addressed by https://github.com/godotengine/godot/pull/50676.

**Comment by Zylann** [comment]
I'm not sure the full extent discussed here is being solved by that PR, it seems focused on a particular case (sub-resources). Or maybe it requires some explanation because I might miss something.
