### ISSUE TITLE
Add is_on_left_wall() and is_on_right_wall() to KinematicBody2D

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#15683]
Currently KinematicBody2D has the function `is_on_wall()`, but no `is_on_left_wall()` or `is_on_right_wall()`. Sometimes the specification is necessary and in such cases we have no choice other than to look through slide collisions.

**Comment by ElfEars** [comment]
Maybe just make it return something like the other movement related functions?

(Although you can already check via the collision normal)

**Comment by mrcdk** [comment]
It doesn't make sense to have specific `is_on_right_wall()` or `is_on_left_wall()` because a wall can be anything in your game like if your game is a top-down one, or you mess with the gravity to be different,... You have different information you can get from the collisions to be able to deal with that and you should use them.

**Comment by mateusak** [comment]
@mrcdk Uhh, you can specify the normal... If you couldn't it wouldn't make sense to have `is_on_floor()` or `is_on_ceiling()` either. Your comment makes no sense.

**Comment by wookoouk** [comment]
Agreed, if we are able to check floor + ceiling collision then we should be able to do the same with the left/right wall, although I think there may need to be a better naming convention (for top down games for example) e.g: collides_top, collides_bottom, collides_left and collides_right. (or something to this extent)

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
