### ISSUE TITLE
Keywords are underlined when [Ctrl] is pressed, and clicking on them does nothing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#15686]
Godot 3.0 master 6a4521da2ae0b08f42001c2c38396b28a2549c14

When I press CTRL, GDScript keywords are highlighted and I can click on them like links, but they don't do anything (no help opens). If they are not supposed to link to anything, they shouldn't be underlined.

**Comment by capnm** [comment]
The same issue is also in the shader editor.

**Comment by Grosskopf** [comment]
you mean var, func, export and stuff like that, right? :)

**Comment by bojidar-bg** [comment]
Yeah, those things are keywords :)

**Comment by reduz** [comment]
@Paulb23

**Comment by KoBeWi** [comment]
I guess everything that can't be opened shouldn't be underlined.

**Comment by akien-mga** [comment]
Still reproducible in the current master branch. It seems like beyond keywords, any word in a comment is also underlined and clickable (without effect), and numbers or math operators also show the pointing hand icon (though they don't appear underlined).

Moreover, things like `$Timer` are also underlined and clicking them will do a search against the classref, so `$Timer` will bring you to the Timer docs, but `$MyRenamedTimer` won't.

**Comment by nikibobi** [comment]
The underline thing comes from `TextEdit` `select_identifiers_enabled` option. The node has no context on what the word we are hovering over is (when holding CTRL). It only checks after we mouse click on it and send a `symbol_lookup` signal. The handler is in `ScriptTextEditor` that has context info for the specific language. So to fix this either an additional signal has to be added to `TextEdit` that checks if the word we are hovering over can be looked up or not so that it knows whether or not to underline it.

**Comment by Janglee123** [comment]
@nikibobi  I assume symbols like `var`, `for`, `if` should be ignored. Other keywords are supposed to be defined elsewhere If I'm not mistaken. We can get these worlds from a predefined list instead of adding new signal.
