### ISSUE TITLE
Misaligned page navigation

### ISSUE THREAD

**Issue by Omicron666** [godotengine/godot#15705]
**Godot version:**

Build date: 2018-01-13 19:42:27
Git commit id (short): c01575b31

**OS/device including version:**

Win10 64 bits

**Issue description:**

Page navigation : numbers and texts aren't correctly aligned.
See this : ![](https://i.imgur.com/lQxCLQr.png)

**Steps to reproduce:**
Just open AssetLib in Godot editor.

**Comment by amhndu** [comment]
I think this might be because LinkButton doesn't add any offset from style, unlike Label, which is what leads to the inconsistency.  
However, even after I added it with `style->get_offset().y`, it is still off by a few pixels since for some reason, the offset comes out to be different for LinkButton and Label, 2 and 4 respectively.  
I've tried only using `style = get_stylebox("normal");` as well as properly selecting it depending on the cases, but no luck.

**Comment by supragya** [comment]
Seems as if there is a disparity in `Label` and `LinkButton`, for reference, look at `/editor/plugins/asset_library_editor_plugin.cpp`

**Comment by Crazy-P** [comment]
As @amhndu mentioned. There is no offset to LinkButton's style. But a default offset of 4 exists for Label.

So could be solved by doing something like this (tested and working):
`float y_ofs = no_y_ofs ? 0.0 : style->get_offset().y;`

in https://github.com/godotengine/godot/blob/master/scene/gui/label.cpp#L211
