### ISSUE TITLE
Line thickness of CollisionPolygon2D is too thick compared to Polygon2D

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#15719]
**Godot version:**
Godot_v3.0-rc1

**OS/device including version:**
Windows 7

**Issue description:**
The line thickness of CollisionPolygon2D is too thick compared to Polygon2D.

![line_thickness_collisionpolygon2d](https://user-images.githubusercontent.com/10463138/34920448-360978f6-f973-11e7-95a3-bc3a64dd5dfb.gif)
I love to create my projects in low resolution and with these thick lines I can't see anything and the accuracy is not readable anymore.

![image](https://user-images.githubusercontent.com/10463138/34920496-dd897c20-f973-11e7-8c9c-69fe1cdda411.png)

**Comment by poke1024** [comment]
Is this about the thickness of the lines while editing the polygons?

Then we'd need to change/make configurable the `2 * EDSCALE` inside `AbstractPolygon2DEditor::forward_draw_over_viewport`.

**Comment by puppetmaster-** [comment]
If you draw the polygon everything is OK, but afterwards the line is drawn much too wide.

**Comment by poke1024** [comment]
OK, I see, you're working in zoomed mode.

We're talking about this guy in `CollisionPolygon2D::_notification`:

`draw_line(p, n, Color(0.9, 0.2, 0.0, 0.8), 3);`

which should be

`draw_line(p, n, Color(0.9, 0.2, 0.0, 0.8), 1);`

for your use case.

The problem happens because line width 3 actually draws a polygon that gets scaled when in zoom in the editor, while line width 1 draws a line that is independent of editor zoom. I'm not sure what's a good general solution for this; probably we should change 3 to 1.

**Comment by Nao-fox** [comment]
I also have the same problem in 3.0.
But It seems the actual collision shape becomes thick by the line.

**Comment by NilsIrl** [comment]
This should be closed as it was fixed by #17114.
