### ISSUE TITLE
Light groups for BakedLightmap

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#15727]
**Godot version:**
109242c

**OS/device including version:**
Debian GNU/Linux 9.3

**Issue description:**
Currently, with BakedLightmap, we can only change the energy of the overall BakedLightmap, but we can't change the energy of only certain lights in it. Using separate BakedLightmap may not be an option when the lights we want to control separately are in close proximity with each other.

As mentioned in #4136, this is useful, for example, for flickering lights.

A solution to this problem can be to have a mechanism to specify which light sources should be baked for each BakedLightmap. This way, users can use multiple lightmaps which may overlap (when the lights are close to each other) and control the energies of each BakedLightmap instance separately to control the energy of individual lights, or groups of them, as they need.

**Steps to reproduce:**
Add multiple light sources and bake the BakedLightmap. When you change the energy of a light source after bake, it has no effect.

**Comment by reduz** [comment]
If you want to leave the issue opened, feel free but I don't really think this is going to be addressed any time soon. You can still flicker a light if you are using it as direct. It seems way too much effort (having a lightmap per light) for a feature that will likely not be used that much.

**Comment by seadra** [comment]
> You can still flicker a light if you are using it as direct.

Can you elaborate on that?

If I'm not missing anything here, Godot doesn't have a light source whose shape can be changed, which is needed for ceiling lights like in [this video](https://www.youtube.com/watch?v=Op-tys_98Ek) unlike [Unreal](https://docs.unrealengine.com/latest/INT/Resources/ContentExamples/Lighting/5_3/), so one has to use emission textures. Alas, in current implementation, emission textures don't emit any direct light.

**Comment by reduz** [comment]
As far as I know, in Unreal, enlongating the light only works for the specular lobe. In fact, in the video you link, you can clearly see that the lights on the floor are round..

**Comment by seadra** [comment]
Even if it's just for reflections, if used well in-doors, it doesn't look bad in my opinion.

So but, back to my question, how can I can flicker an emissive material in Godot? I haven't seen Do Godot have an option to make some materials emissive realtime?

**Comment by reduz** [comment]
no, you definitely can't flicker emissive materials, you'll have to combine it with a direct light.
Alternative, keep in mind you can use negative lights in Godot, so you could darken an area to simulate flickering.

**Comment by seadra** [comment]
Using negative light sounds interesting, thanks for the tip.

Generally speaking, emissive and direct light aren't mutually exclusive. For example, in Unity, [emissive materials](https://unity3d.com/learn/tutorials/topics/graphics/emissive-materials) have the option to be baked or realtime (similar to direct/omni/spot light nodes in Godot do). Are there any plans to allow direct/realtime emissive lights in Godot?

**Comment by reduz** [comment]
In enlighten you can modify emissive materials and they change in real-time. This could be added in Godot without too much work in GIProbes, but we needed to set a feature limit or we would never release 3.0.. for baked lightmaps this is impossible, makes sense maybe for how Enlighten works.

**Comment by seadra** [comment]
That'd be something to look forward for 3.1+. I'll open an issue for that to track it.

**Comment by Calinou** [comment]
While the upcoming new lightmapper in 4.0 is much more powerful than the previous implementation, it doesn't feature support for light groups/lightstyles. 

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by seadra** [comment]
> While the upcoming new lightmapper in 4.0 is much more powerful than the previous implementation, it doesn't feature support for light groups/lightstyles. Still, since Godot now supports projector textures for OmniLight and SpotLight, the original use case should now be covered.

Can you elaborate on how the projector textures cover the original use case, which is an issue more about Lightmap rather the lights itself?

**Comment by Calinou** [comment]
@seadra I was referring to this comment:

> If I'm not missing anything here, Godot doesn't have a light source whose shape can be changed, which is needed for ceiling lights like in this video unlike Unreal, so one has to use emission textures. Alas, in current implementation, emission textures don't emit any direct light.

**Comment by seadra** [comment]
Yes, I agree with that, although that's a side discussion and not the original use case.
