### ISSUE TITLE
Asset Library when no project in Project Manager

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#15720]
**Godot version:**
Godot 3.0rc1 on Windows10

**Issue description:**
If no project in Project Manager, clicking "Open Asset Library" in the popup doesn't load properly. Manually clicking at "Template" tab is working fine.

![image](https://user-images.githubusercontent.com/7358899/34920931-26a2ff2e-f97b-11e7-9649-073e941bb293.png)

![image](https://user-images.githubusercontent.com/7358899/34920941-470b313c-f97b-11e7-937b-e36f71e32f86.png)

**Comment by akien-mga** [comment]
Seeing #15735, it appeared that this is in fact not a bug but a yet-unused feature. This dialog disables the "Community" category (where all assets are currently) so that only "Official" assets are display. Those are meant to be the official demos, but they haven't been uploaded yet (should be done before 3.0).
