### ISSUE TITLE
RigidBody with PinJoint acts differently with Bullet and GodotPhysics

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#15744]
**Godot version:**

Godot 3.0 RC1 05b184381

**OS/device including version:**

Ubuntu 17.10

**Issue description:**

![swing](https://user-images.githubusercontent.com/8281454/34943916-f10e5720-fa40-11e7-8229-16189d0bbdd2.gif)

Swing is not slowing down with Bullet.
actually it is, but it looks like swings forever.
but i can see swing noticiblely slows down with GodotPhysics.

**Steps to reproduce:**
here is scene setup
![screenshot from 2018-01-15 22-16-16](https://user-images.githubusercontent.com/8281454/34944132-be00407c-fa41-11e7-844f-fb581bd629b4.png)

**Minimal reproduction project:**

[Test Physics 2.zip](https://github.com/godotengine/godot/files/1631708/Test.Physics.2.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by reduz** [comment]
This probably has to do with rotation and translation damping, values are
likely different in Godot and Bullet

**Comment by AndreaCatania** [comment]
@volzhs yes bullet and godot doesn't produce the exact same behavior even with the same parameters. However in order to slowdown it (with both physics engines) you should set angular damp of body

**Comment by akien-mga** [comment]
So as I understand it there's just some documentation needed for the PinJoint node to mention the differences between GodotPhysics and Bullet behaviour.

**Comment by AndreaCatania** [comment]
@akien-mga yes

**Comment by AndreaCatania** [comment]
@akien-mga or more in general is better to say that Godot physics can differ a bit from Bullet physics.

**Comment by ArdaE** [comment]
Another difference I've noticed is that GodotPhysics seems to use the collision polygon/shape's translation for the center of gravity (or the geometric center of the translations of the collision polygons/shapes if there are more than one), while Bullet uses the parent node's translation. This is based on a quick observation of behaviour, so it's possible I may be wrong (I haven't looked at the code at all). Based on this observation, I like Bullet's approach much better as it not only provides user control over the simpler CollisionShape's center of gravity (unlike GodotPhysics), but it also provides better/explicit control of center of gravity if there are multiple collision polygons/shapes.

In light of this, check the translation of each of your RigidBody instances when you use Bullet. If it's not within a physically possible area for the collision shapes/polygons nested under the RigidBody, then Bullet produces some really strange results that don't settle (probably correct physics for a physically impossible case). The fix is easy in that case, which is to bring the center of gravity where you need it. So Bullet gives more power to the user, but it can also cause issues if you set up something that's physically impossible. Note to Andrea & Juan: Please keep Bullet's behaviour; it's great to have explicit control over the center of gravity, but this should be documented if it's not already.

**Comment by AndreaCatania** [comment]
The 3D physics documentation is completely missing. (Or I didn't found it yet). So it should be written

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-docs#2161.
