### ISSUE TITLE
Can't access class propertys 

### ISSUE THREAD

**Issue by christianbender** [godotengine/godot#15791]
**Godot version:**

Godot 2.1.4

**OS/device including version:**

Linux Mint 18

**Issue description:**

I extends from Label but I can't access to the property ```text``` 
I became the message ```Parser Error: Identifier not found: text```

I expected access to the property ```text```

![screenshot](https://user-images.githubusercontent.com/23243382/35010843-85036448-fb04-11e7-9cdf-89b32789fdc5.png)

**Steps to reproduce:**
See screenshot above

**Minimal reproduction project:**

**Comment by volzhs** [comment]
I guess we need to put something to clear it's 3.0 document on the docs page.

**Comment by christianbender** [comment]
@volzhs If you tell me where I can found the doc-page then I can put in a comment.

**Comment by robfram** [comment]
Oops. I think the problem is the link in the doc web is wrong. I mean this (URL and main title shown):

[http://docs.godotengine.org/en/2.1/](http://docs.godotengine.org/en/2.1/) loads **Godot Docs – 2.1 branch**.
[http://docs.godotengine.org/en/stable/](http://docs.godotengine.org/en/stable/) loads **Godot Docs – master branch**.
[http://docs.godotengine.org/en/latest/](http://docs.godotengine.org/en/latest/) loads **Godot Docs – master branch** again.

And, as pointed, no reference to 3.x in any of them, so anybody who doesn't follow the news or dev doesn't know there is a brand new 3.x version in the oven.

**Comment by cbscribe** [comment]
This just happened today. Something went wrong with the version URLs on the docs site. It's being addressed, so wait until we hear from @akien-mga

**Comment by eon-s** [comment]
Every page should have a link to the other versions, like Unity does

**Comment by mhilbrunner** [comment]
@eon-s Every docs page allows you to switch in the lower left section/menu, but its a little hidden.

So this can be closed? Links seem to work fine again.

**Comment by eon-s** [comment]
@mhilbrunner yes, and since 3.1 may bring extra features, a message showing the version on top of the page may be necessary.

This can be closed and maybe open one about versions on docs repo.
