### ISSUE TITLE
Collision offset

### ISSUE THREAD

**Issue by thankjura** [godotengine/godot#15806]
I can not do that the rigidbody would fall to different heights.
Maybe add option like as offset?
![7cb1yjz](https://user-images.githubusercontent.com/2144212/35040778-7821c67c-fb93-11e7-8457-7de76ab60c08.gif)

What I want:
![w](https://user-images.githubusercontent.com/2144212/35040802-90cd59c0-fb93-11e7-81d3-407d2765396a.png)

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
