### ISSUE TITLE
There is no "Disable Boot Splash" option

### ISSUE THREAD

**Issue by icnikerazah** [godotengine/godot#15838]
**Godot version:** https://github.com/godotengine/godot/commit/b10172610

**OS/device including version:** macOs sierra

**Issue description:**

there is no "disable Boot Splash" option in project settings or editor settings.

<img width="697" alt="ekran resmi 2018-01-18 14 32 07" src="https://user-images.githubusercontent.com/33985414/35096787-88df085a-fc5e-11e7-94e5-257c7e5459f6.png">

Do I have to use the Splash Screen? Every time I run the project or open editor it slows down the execution.

![splash](https://user-images.githubusercontent.com/33985414/35097381-e8647cfe-fc60-11e7-8cca-4548264bca03.png)

**Minimal reproduction project:**

**Comment by reduz** [comment]
Make a small custom one, loading an image has too little cost for you to feel the impact.

**Comment by icnikerazah** [comment]
i made one pixel image and still waiting 1 second

**Comment by reduz** [comment]
are you waiting one more second than with the default splash?

**Comment by reduz** [comment]
Just to clarify, the splash screen in Godot is not forced. It's simply there while the engine initializes but there is not any forced delay.  If you have a really fast computer, the splash is barely seen.

**Comment by reduz** [comment]
I'm sorry but it's not clear to me what your problem is.

-Is it the time it remains open?
-Is it that there is a Splash screen?
-Is it that setting a custom splash screen takes longer to load than the built-in one?

Please help me make some sense of the issue.

**Comment by icnikerazah** [comment]
it is that thete is a splash screen

**Comment by karroffel** [comment]
It could be disabled by a setting (that would change the value of `show_logo` here)

https://github.com/godotengine/godot/blob/9d45b719d4ed1f50c93f3234b31233ae5039987c/main/main.cpp#L1033

As reduz said, there is no forced delay. We don't show the splash screen because we think it's so pretty, it's shown *while the engine initializes* so there is at least something on the screen.

This is not false advertisement, you **can** set a custom image, so it's not *forced* that you use the default splash screen.

And again: the duration of the splash screen is not forced somehow, it's just the startup that happens, there is not much we can do to speed that up.

**Comment by icnikerazah** [comment]
i dont like slow execution time

**Comment by karroffel** [comment]
> i dont like slow execution time

Neither do I, but there is some work being done when the engine starts, it's not immediate.

The splash screen **does not** artificially slow down the engine startup.

**Comment by reduz** [comment]
Well, the engine has to initialize at some point, and a second to initialize is pretty fast compared to other engines. There is ongoing work to further improve initialization time, but so far it's pretty optimal.

If you don't want to see the Godot splash logo while it initializes, set a small custom one, it will not have any meaningful impact in initialization time.

**Comment by icnikerazah** [comment]
you dont understand. i  dont want to use splash screen completely. i dont want custom image.

**Comment by akien-mga** [comment]
> you dont understand. i dont want to use splash screen completely. i dont want custom image.

Yes, and it could be added as an option, but you don't understand that it won't speed up the execution time. Instead of seeing a Godot logo or a custom image, you will see nothing, but wait the same time.

**Comment by icnikerazah** [comment]
for example. love2d  execute whole game in milisecond.

**Comment by akien-mga** [comment]
And Love2D is a lightweight 2D framework, not a complex 3D game engine...

**Comment by akien-mga** [comment]
But feel free to fork Godot and remove the splash screen for yourself and see if it starts in milliseconds.

**Comment by reduz** [comment]
@icnikerazah Love2D is tiny compared to Godot. of course it will initialize faster.

**Comment by icnikerazah** [comment]
@karroffel thanks for code.  this is what i want.

**Comment by reduz** [comment]
Oh by the way, to clarify the splash screen appears while the engine initializes AND your main scene loads.
If your main scene is big, it will have to load it and that will take longer.

**Comment by reduz** [comment]
Still on my AMD A8, godot takes waay less than a second to initialize, it's pretty much instant.

**Comment by akien-mga** [comment]
For the reference, I had a look at making the splash screen optional (still knowing that it *will not* speed up init, as init still needs to happen even if no image is shown), but on X11 at least it shows an empty transparent window instead of showing the splash screen, which is not particularly desirable.

I'll check one day if we can delay the window init a bit to prevent that and allow an engine + main scene init with no visual feedback until the window actually needs to spawn... but that might introduce issues so that will have to wait for after 3.0.

**Comment by icnikerazah** [comment]
the only problem is not slow opening. the opening time is uncontrollable. as aesthetically

**Comment by Calinou** [comment]
Once the splash screen is fully disableable, you will be able to use your own splash scene in a seamless manner – in fact, you can already do so, provided the first frame of your custom splash scene matches the splash image exactly.
