### ISSUE TITLE
Tag betas, release candidates, etc

### ISSUE THREAD

**Issue by redxdev** [godotengine/godot#15907]
As far as I can tell, betas and release candidates have not been tagged, and this would be nice to have for the future (if not for past releases).

This should be a part of the release process, especially since commits have _not_ been listed in each of the [past](https://godotengine.org/article/dev-snapshot-godot-3-0-rc-1) [announcements](https://godotengine.org/article/dev-snapshot-godot-3-0-beta-2). In fact, the only 3.0 announcement with a listed commit seems to be the recent RC2 announcement, unless I'm missing it hidden away somewhere.

**Comment by akien-mga** [comment]
I don't want to tag pre-releases, as such tags are useless as soon as the stable release is tagged (who needs to know what commit was 2.0 alpha 1 today?). And I'm not fond of adding tags to delete them later on, as it means that most users will end up with local tags which differ from the remote, which could be problematic if some of them with write access want to push tags with `git push --tags` and thus re-push old obsolete tags they still had locally.

Alphas, betas and RCs are *development snapshots* of the master branch, not formal releases undergoing QA and denoting a "more stable than usually" commit. They're the same as any unofficial nightly build, apart from the fact that they feature export templates for all supported platforms. As such, I don't think they deserve a particular mention among our [releases](https://github.com/godotengine/godot/releases).
Such pre-releases are also not meant for Linux packaging or any kind of thirdparty redistribution (even though it's allowed of course) which would require an absolute reference like a git tag.

As for knowing which commit(s) was(were) used for a given dev snapshot (can be several references since some platforms might fail building and therefore require a hotfix commit - or even an untracked patch in some cases), they are all documented in the README files that are included in all pre-release folders: [alpha1](http://downloads.tuxfamily.org/godotengine/3.0/alpha1/README.txt), [alpha2](http://downloads.tuxfamily.org/godotengine/3.0/alpha2/README.txt), [beta1](http://downloads.tuxfamily.org/godotengine/3.0/beta1/README.txt), [beta2](http://downloads.tuxfamily.org/godotengine/3.0/beta2/README.txt), [rc1](http://downloads.tuxfamily.org/godotengine/3.0/rc1/README.txt), [rc2](http://downloads.tuxfamily.org/godotengine/3.0/rc2/README.txt).

**Comment by akien-mga** [comment]
Keeping it open as I'm still open to discussing it if there are strong arguments in favour of tagging dev snapshots. The only positive one I found is that it shows that the project is quite active - but the master branch git history and the website show it quite well already IMO.

**Comment by rcorre** [comment]
I just ran up against this today, wanting to try 3.1. I see a number of snapshots at https://downloads.tuxfamily.org/godotengine/3.1/, but I wanted to build from source and was dismayed to find that none of the releases are tagged.

I wouldn't call such tags useless. The fact that you package certain prerelease commits _does_ give them a sort of special status, as a kind of checkpoint.
Tagging the commits used for such builds is useful from a historical record-keeping perspective. There's no need to delete them (I'd even say that would be mildly evil), as tags with [pre-release metadata](https://semver.org/#spec-item-11) (e.g. `-alpha.1`) is a pretty common convention, and such tags are understood to sort before actual releases (e.g. `1.0.0-alpha < 1.0.0`).

I do see the other side of the argument though. If grabbing one of these releases doesn't get you anything more stable than an arbitrary commit on master, maybe they shouldn't be tagged. But it is certainly surprising to the uninitiated.

**Comment by GammaGames** [comment]
How much work would it be to make an official "pre-release" mirror that syncs with the primary repo automatically, but has release tags for alpha/beta/rc? GitHub has a nice API, and there are some use cases that would make the tags nice:

* I read github releases far more frequently than blog posts
* A [version manager](https://github.com/eumario/godot-manager) has to scrape tuxfamily for release information

**Comment by Calinou** [comment]
> How much work would it be to make an official "pre-release" mirror that syncs with the primary repo automatically, but has release tags for alpha/beta/rc? GitHub has a nice API, and there are some use cases that would make the tags nice:
> 
>     * I read github releases far more frequently than blog posts
> 
>     * A [version manager](https://github.com/eumario/godot-manager) has to scrape tuxfamily for release information

We were discussing creating a separate repository to host official nightly builds, but I wouldn't go as far as creating yet another repository only to store prerelease tags.

**Comment by rcorre** [comment]
I'm not sure having tags in a separate repo would help at all. At least for me, the use case is:

- I install prerelease x.y.z-beta1
- I encounter a bug / wonder how something works / want to tweak something and build from source
- I go to my local copy of `godot` ... how do I figure out which commit the prerelease was built from?

**Comment by Calinou** [comment]
> I go to my local copy of godot ... how do I figure out which commit the prerelease was built from?

Official releases now contain commit hashes in the project manager or About dialog, so you can click the version identifier there to copy it (including the commit hash).
