### ISSUE TITLE
Strange pathfinding with NavigationPolygon

### ISSUE THREAD

**Issue by guassmith** [godotengine/godot#15919]
**Godot version:**
Godot 3.0 final

**OS/device including version:**
Windows 10 x64

**Issue description:**
Using Navigation2D's get_simple_path() produces strange and inefficient paths, especially when navigating around inside polygons. For example: 
![bad_navigation](https://user-images.githubusercontent.com/15133020/35189497-7d1df0c6-fe43-11e7-940b-c48653825a41.png)
The dots represent the path connecting the sprite to the mouse, for some reason it decides to go around the square even though it could reach the mouse by going straight towards it.

**Steps to reproduce:**
Just create a hole in a NavigationPolygon and try to path near it. Sometimes the path isn't too inefficient, it depends on the exact shape of the polygons.

**Minimal reproduction project:**
[navigation.zip](https://github.com/godotengine/godot/files/1649423/navigation.zip)

**Comment by hinasis** [comment]
!!!!!!!!! I have the same problem! Was about to post the issue, but it's very similar!
It doesn't return the straigth path, it strangely take the longest route around the squad!

It also only happens from that position, from the upper right side of the squad to the down side of the squad and from the inverse route too. If I do it from the left side, it has no problems.
Also the problem is related to the X axis I think, because moving from further X, to a landing further X, it take the straight way.

**Comment by guassmith** [comment]
@hinasis 
I did some more testing, in the project I linked it seems that making the left edge of the large polygon completely straight (using snapping) solves the issues almost entirely. In my other projects with more complicated polygons this didn't help but I found a workaround that seems to be working for now. Instead of adding a new polygon inside the larger one, you make a dent in the original polygon and then close it up by dragging the vertices exactly together (you'll need to enable snapping to get it just right). It should look like this:
![better_polygon](https://user-images.githubusercontent.com/15133020/35736771-29715426-0821-11e8-8f59-7b9e77f41ed5.png)
I still don't think the paths created with this are as efficient as possible, but at least they're not as blatantly bad as in the original picture.

**Comment by hinasis** [comment]
In my case I did the navpoly by code, so they all were completely straight, I don't belive it's the problems.
Any way, your solution doesn't work for my case, because I add the holes by code using bodies as reference (it's a sandbox like battle arena where you can spam structures)

Hope they fix the Nav2D..

P.S: This issue is so buried, it's posible they never read it.

**Comment by robojumper** [comment]
I added a bit of code to visualize the polys of the NavMesh in the example project, and noticed two problems:

![grafik](https://user-images.githubusercontent.com/14299449/41507535-52e87348-7234-11e8-8a66-cbe038cd0856.png)

The A* cost heuristic is not admissible, it may overestimate the actual distance:

https://github.com/godotengine/godot/blob/a74e1514206af1b8456ece2cf009b841b86b72f1/scene/2d/navigation2d.cpp#L390-L405

... since it considers the distance from the poly center point to the end point. This is a big problem here, as the poly with the shortest route is comparatively big, with a center that's far away from the optimal route.

After fixing that, the algorithm still isn't quite ideal, since it does this:

https://github.com/godotengine/godot/blob/a74e1514206af1b8456ece2cf009b841b86b72f1/scene/2d/navigation2d.cpp#L417-L423

The algorithm assumes that the shortest distance to another poly is through the nearest point on the edge to that poly, disregarding the fact that this may make the overall distance longer.

That's a problem with the algorithm itself, since it first finds a (non-optimal) path, and then tries to optimize it using string pulling. I suppose that's why the function is called `get_simple_path` :)

**Comment by reduz** [comment]
Maybe instead of the poly center, it should use the point closest to the target point within the poly to compute distance, that may make more sense, what do you think?
