### ISSUE TITLE
Textures appearing as yellow tinted

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#15920]
**Godot version:** 3.0 rc2 (with mono)

**OS/device including version:** Linux - Xubuntu 16.04 LTS 64-bit

I have a 3D model imported in OBJ format, and a texture in PNG format. I imported the model as a Mesh via MeshInstance. However, the texture looks very yellow! It looks like this in Godot:

![yellow](https://user-images.githubusercontent.com/1646875/35189556-5c265fec-fe12-11e7-9465-d3eeb4e8728b.png)

Note how it's even yellow on the left side file list thing. But the PNG texture file looks like this: 

![astronaut_basecolor](https://user-images.githubusercontent.com/1646875/35189559-652458a6-fe12-11e7-8876-b8d7b061f4a0.png)

This happens in pretty much a brand new project. I don't even think the 3D model is necessary to see the yellowed texture, you can try just importing it and looking on the left side file list. But regardless, here is the model and texture files: [Model.zip](https://github.com/godotengine/godot/files/1649429/Model.zip)

**Comment by Zylann** [comment]
It looks like the blue channel was not parsed. I cannot find any pixel with some blue in it on the FileSystem preview.

**Comment by mrcdk** [comment]
Can't reproduce on RC2 or latest master https://github.com/godotengine/godot/commit/c58891ff4ce9559fb1413d34159d3fb039999402 

![https://i.imgur.com/Jq42UP1.png](https://i.imgur.com/Jq42UP1.png)

Are you sure you didn't import the texture as a normal map?

**Comment by Ace-Dragon** [comment]
Perhaps mention what settings you used when importing the texture (compression ect...) it could be a bug specific to one of them.

**Comment by aaronfranke** [comment]
I also couldn't reproduce on a new project, so I tried renaming the PNG file in my existing project, and that worked, for some reason. Here's the entire project ZIP: [TestingGodot.zip](https://github.com/godotengine/godot/files/1649447/TestingGodot.zip) Seems like a weird anomaly, but still, it's a bug that should be fixed. Textures shouldn't randomly turn yellow.

**Comment by brainsick** [comment]
This might not be strictly an import issue, it might be a workflow one.  Did you possibly use that png in another texture slot before assigning it to Albedo?  How you use an image influences how Godot treats it which is then persisted in the corresponding .import file.  When you renamed the texture, you broke the .import link causing Godot to import it with default settings again.

**Comment by Calinou** [comment]
You can set the **Normal Map** property of the texture to **Disable** so that it will never attempt to detect it as a normal map and use RGTC compression on it (which does not feature a blue channel).

**Comment by ArdaE** [comment]
Looks like this is already fixed in the released version of Godot 3.0, but with one caveat. The fix only applies to newly imported files. I'll explain:

I have the problem you describe when I open a project that was created using an earlier custom-build of Godot 3 (from the beta days) but not when I open a project created using the released version of Godot 3.0. Note that I am opening both projects using the released version of Godot 3.0.

The difference is the import flags set for the .png file. The settings created by the beta-days version of Godot has "Normal Map" set to "Enable", which is what's causing the greenish yellow tint, whereas the settings created by the released version has it set to "Detect", which doesn't have the same issue. However, this is not the only difference. The Flags settings are different too (Mipmaps, Filter, SRBG, etc.), which cause other issues on their own.

You can manually fix the import settings of your old .png, but there's an easier way to ensure the default import settings of the final released version of Godot 3.0: Copy the .png file to a new name, let Godot automatically import it, delete the old .png, and rename the new .png to the original name.

I think this issue can be closed, as it seems to have been fixed. Anyone who lands on this page can use to procedure I've described in the last paragraph above to fix their old projects.

**Comment by akien-mga** [comment]
> You can manually fix the import settings of your old .png, but there's an easier way to ensure the default import settings of the final released version of Godot 3.0: Copy the .png file to a new name, let Godot automatically import it, delete the old .png, and rename the new .png to the original name.

Even simpler is to delete the `.import` files for the PNGs you need to fix, and let Godot recreate them with default settings (and thus reimport them).

**Comment by Temptica** [comment]
Hi, The same bug seems to be back in godot 4.5. Removing the .import fixed the issue. I accidentally put the texture into the normal map and the blue item became yellow.

**Comment by vladkamvl** [comment]
Same thing, the delete .import files solve the problems

**Comment by jopoet** [comment]
Just happened here too on 4.5. Pretty annoying thing.
