### ISSUE TITLE
Something wrong with Depth/Parallax Mapping in Spatial Material

### ISSUE THREAD

**Issue by wlodeqp** [godotengine/godot#15934]
**Godot version:**
Godot 3.0 RC 2

**OS/device including version:**
Ubuntu 16.04 64-bit

**Issue description:**
The default parallax mapping change bump angle when you rotate scene view.

I changed this line of code:
`vec3 view_dir = normalize(normalize(-VERTEX)*mat3(TANGENT,-BINORMAL,NORMAL));`
to this one (removed minus)
`vec3 view_dir = normalize(normalize(-VERTEX)*mat3(TANGENT,BINORMAL,NORMAL))`
and it works but I don't know it is real fix.

**Steps to reproduce:**
Open the project and slowly rotate scene view above the planes

**Minimal reproduction project:**
[Test5.zip](https://github.com/godotengine/godot/files/1649698/Test5.zip)

**Comment by Bauxitedev** [comment]
I had the same problem, I thought it was a problem with my parallax maps at first. Good to know there's a workaround for now.

**Comment by Biliogadafr** [comment]
Looks like parallax also affected by this #16009. I did some tests and I see that different inbuilt geometry (planes, quads) shows different parallax behavior. For example material with fix in test scene from this issue will work for inbuilt Plane, but will not work for Quad and for imported geometry.

**Comment by Calinou** [comment]
Unfortunately, this fix does not work with all meshes. I wanted to submit a pull request (see [this commit](https://github.com/Calinou/godot/commit/fd54b81adcf3e68512ea6a03406f8713dd1bb7dd)) also incorporating changes from https://github.com/godotengine/godot/issues/15794, but while it looks good on a cube exported from Blender, it looks broken on the test mesh from the Material Tester demo.

**Good depth mapping:**
![depth_mapping_good](https://user-images.githubusercontent.com/180032/38200120-6b17e21e-3693-11e8-8840-411c8f67a821.png)

**Broken depth mapping:**
![depth_mapping_bad](https://user-images.githubusercontent.com/180032/38200119-6af78c26-3693-11e8-96ee-b1da840c59eb.png)

**Comment by Biliogadafr** [comment]
Tangents are different everywhere. They affect how normal maps and parallax works. I've tried to unify tangents in my fix #16096 (not merged) to match those from Material Tester and to work correctly with OpenGL style normal maps, like in Material Tester. (But maybe something was changed since then?)

**Comment by reduz** [comment]
I am not really sure about this because, as mentioned before, it really depends on the application, Maybe options to flip binormal/tangent should be added..

**Comment by fracteed** [comment]
After doing a lot of experimenting with parallax maps in Godot, I also could only get them to work using the same method as @wlodeqp , by removing the minus from the binormal code.  As noted by @Biliogadafr in #16009 parallax mapping will not work on Godot's native primitives.

Also, care must be taken to use an actual depth map with white as the furthest depth, as Substance and other engines/renderers use a height/displacement map which has white as the closest depth.

I have attached a project file with 2 parallax materials using the aforementioned steps. Since I posted this on twitter and my website, I have heard no feedback that this approach doesn't work on various hardware configurations. Hopefully this easy fix (removing the negative sign) can be added before 3.1 is released. 

[parallax_heads.zip](https://github.com/godotengine/godot/files/2448878/parallax_heads.zip)


![parallax_heads_screenshot1](https://user-images.githubusercontent.com/7741669/46515217-d1cf8f80-c8a5-11e8-884c-7ccc557c1b7a.jpg)

**Comment by reduz** [comment]
I am not quite sure what to do with this one. Technically, it can fail completely depending on the geometry and how it was created, given tangent space is not warranted to be universal. 

I will add an option to flip x and y in tangent space to make sure it can work with everything, but it needs to be done manually.
