### ISSUE TITLE
Shader Language: Cannot use hints and default values at the same time

### ISSUE THREAD

**Issue by Stoeoeoe** [godotengine/godot#15931]
**Godot version:**
3.0.beta.custom_build.a60898 (should be true for all 3.0 builds)

**OS/device including version:**
Windows 10, 64-bit

**Issue description:**
When writing a shader, it is possible to specify hints for uniforms:
```uniform vec4 color : hint_color;```

In the shader params section of the ShaderMaterial, the control to modify the value is then a color picker. However, in many cases, we may also want to specify default values. Usually, this is possible using the following syntax:

```uniform vec4 color = vec4(1.0,0.0,1.0,1.1);```

However, there appears to be no possibility to combine the two approaches, neither of the two statements work:
```uniform vec4 color : hint_color =  vec4(1.0,0.0,1.0,1.0);```
```uniform vec4 color = vec4(1.0,0.0,1.0,1.0) : hint_color;```

Maybe I missed something, if not, that'd be a really helpful feature, in my opinion.

**Steps to reproduce:**
* Create a MeshInstance
* Assign a new ShaderMaterial
* Create a new Shader:
```
shader_type spatial;

render_mode unshaded;

uniform vec4 color : hint_color =  vec4(1.0,0.0,1.0,1.1);

void fragment() {
	ALBEDO = color.rgb;
}
```
* Realize it will not compile because it expects a semicolon after the hint.

**Minimal reproduction project:**
[shader_hint_default_value.zip](https://github.com/godotengine/godot/files/1649678/shader_hint_default_value.zip)

**Comment by brainsick** [comment]
So, I spent some time digging into this.  I tried a couple things but didn't land on an easy/obvious fix.

```
uniform vec4 color : hint_color = vec4(1.0,0.0,1.0,1.0);
```
The [code](https://github.com/godotengine/godot/blob/59e83af201af5a93c7a13750d781c050c2275c07/servers/visual/shader_language.cpp#L3801) is assuming a ; after it processes the hint, so it won't let us assign a value after.

```
uniform vec4 color = vec4(1.0,0.0,1.0,1.1) : hint_color;
```

We can't do this because the : is being treated as an in-line [operator](https://github.com/godotengine/godot/blob/59e83af201af5a93c7a13750d781c050c2275c07/servers/visual/shader_language.cpp#L2813) ala `condition ? true : false` as it parses the assignment expression.

**Comment by brainsick** [comment]
This seems to work, but didn't actually result in a white default.  But I swear I have that problem with defaults all the time, so I don't know what to think.

<details><summary>Possible fix</summary>

```
todd@todd-ab28d3:~/repos/remote/brainsick-godot$ git diff -w
diff --git a/servers/visual/shader_language.cpp b/servers/visual/shader_language.cpp
index 29c27eee8..49da2a9a6 100644
--- a/servers/visual/shader_language.cpp
+++ b/servers/visual/shader_language.cpp
@@ -3661,6 +3661,8 @@ Error ShaderLanguage::_parse_shader(const Map<StringName, FunctionInfo> &p_funct
                                        //todo parse default value
 
                                        tk = _get_token();
+                                       while (true) {
+
                                                if (tk.type == TK_OP_ASSIGN) {
 
                                                        Node *expr = _parse_and_reduce_expression(NULL, Map<StringName, BuiltInInfo>());
@@ -3796,6 +3798,13 @@ Error ShaderLanguage::_parse_shader(const Map<StringName, FunctionInfo> &p_funct
                                                        tk = _get_token();
                                                }
 
+                                               if (tk.type == TK_OP_ASSIGN) {
+                                                       continue; 
+                                               } else {
+                                                       break;
+                                               }
+                                       }
+
                                        shader->uniforms[name] = uniform;
 
                                        if (tk.type != TK_SEMICOLON) {
```
</details>

**Comment by raymoo** [comment]
Why not make a PR first and update it if it needs changing?

**Comment by brainsick** [comment]
It's more paperwork and I'm not confident that it will be accepted.  It's my first foray into this code and my test results are inconclusive.

**Comment by raymoo** [comment]
The point of a PR is code review. If you want someone to review the code then put it in a PR.

**Comment by brainsick** [comment]
The point of a PR is to request a merge.  Review happens as part of that, yes.

I'm not requesting a merge because I'm not confident in the fix.  Core might decide that this solution and resulting syntax are silly.  They might prefer that the hint follows the default which would necessitate updating the expression parser to recognize the situation.  I wouldn't be interested in pursuing such a fix myself so submitting a PR would be a waste of everyone's time.  And rejection sucks, I prefer to keep a clean score card; I'm still stinging from #15876.

If my inquiries go unanswered, I might then submit a PR in a couple days just to prompt a resolution.

Here's an easy question that would help me.  Do your default values work?  As I demonstrated in the linked video, mine do not.
