### ISSUE TITLE
Bicubic Upscaling For Refraction Shader

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#15987]
**Godot version:**
3.0 hash 14b230f35f6b2498ef1fe93d8947bcc6f54b9261

**OS/device including version:**
Windows 7 Ultimate 64-bit SP1
AMD Ryzen 5 1400
NVIDIA GeForce GTX 1060 6GB

**Issue description:**
When using the refraction shader with a roughness >= 0.5, surfaces that cover a light and dark area create artifacts similar to the "glow" shader with bicubic upscaling off. See the screenshot for an example.

Would it be possible to implement bicubic upscaling for the refraction shader?

![image](https://user-images.githubusercontent.com/1891696/35250112-d84e84b4-ff89-11e7-82c8-113a34f3b518.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
