### ISSUE TITLE
Normal maps displayed incorrectly for inbuilt meshes.

### ISSUE THREAD

**Issue by Biliogadafr** [godotengine/godot#16009]
Godot version: 3.0 59e83af
OS/device including version:
Windows 10, GF970

Normal map produce wrong results with inbuilt geometry.
![crazy_normals](https://user-images.githubusercontent.com/10543859/35299155-77db06e0-0095-11e8-85d7-d6908999aafb.png)
Project:
[crazy_normals.zip](https://github.com/godotengine/godot/files/1657514/crazy_normals.zip)

Steps to reproduce:
Create MeshInstance and set mesh to 'new PlaneMesh' (or quad or box). Create material for it and add normal map. Add light into scene. Normal map will show incorrect results.

**Comment by Biliogadafr** [comment]
I was playing with tangents in the code that generates inbuilt geometry for plane (primitive_meshes.cpp  PlaneMesh::_create_mesh_array)
and...
ADD_TANGENT(1.0, 0.0, 0.0, -1.0);  //this is now. inverted directx normal(bumps look like cavity), wrong displacement 
ADD_TANGENT(-1.0, 0.0, 0.0, -1.0); //good directx normal, wrong displacement 
ADD_TANGENT(1.0, 0.0, 0.0, 1.0);   //inverted opengl normal, good displacement 
ADD_TANGENT(-1.0, 0.0, 0.0, 1.0);  //good opengl normal, inverted displacement 
...and it looks like I used wrong normal maps (DirectX instead of OpenGL). And also Displacement instead of Depth. So I inverted Displacement to get Depth and changed normal map to OpenGL. When I did this I see that now Quad is the one that renders correctly. And also looks like obj importer generates wrong tangents.
This is modified project:
[crazy_normals_new.zip](https://github.com/godotengine/godot/files/1667809/crazy_normals_new.zip)

**Comment by BastiaanOlij** [comment]
This is hella confusing, there seem to be two separate problems. 

The difference between the DX and GL map supplied in the example is that the X axis is swapped. Using the DX map I consistently get proper results (albeit inverted with the primitive meshes, but correct on import) and when I generate the normal map with [normal map online](http://cpetry.github.io/NormalMap-Online/) it seems to use the same orientation as DX map.
However, using the new [materialize](http://www.boundingboxsoftware.com/materialize/index.php) tool I get a normal map with both X and Y axis swapped (which would result in correct primitive meshes but incorrect import). Seeing materialize is new it might be the one that is wrong:)

Seeing I'm consistently getting proper results with the DX map my gut says to go with that. This does mean fixing up the tangents created for the primitive meshes.

The second problem is that whatever we do up above, the normal map logic and the depth/parallax logic in the shader require the calculated bitangent to be inversed. This is why you get proper results with imported meshes if you tick the "inverse binormal" checkbox.

Ergo, the fix I'm working on is to ensure the primitive meshes generate tangents according to mikktspace which will result in the normal maps being applied correctly and I suggest inverting the binormal in the shader for the depth/parallax logic (ticking the invert binormal tickbox will thus undo the inversion). Ticking the invert tangent and binormal tickbox then work in unison to apply a heightmap instead of a depthmap.
