### ISSUE TITLE
Audio effect resource file causing constant disk writes

### ISSUE THREAD

**Issue by lmjk** [godotengine/godot#16017]
**Godot version:**
3.0 rc2

**OS/device including version:**
Fedora 27 x86_64

**Issue description:**
Open a project that has an audio effect resource saved as a file. Godot will begin to constantly writing to disk, about once in second. This can be seen with iotop in Linux. 

Also, if you select a file in the FileSystem view, the file will lose its selection very soon.

**Steps to reproduce:**
Open the attached project or:
1) Create a new project
2) Open the Audio tool
3) Add a Panner effect (or Limiter, or possibly any other) to the Master bus
4) View the effect in Inspector and save it as "audioeffect.tres"
5) Create a Node in the scene so you can save it
6) Quit to Project Manager
7) Reopen the project

**Minimal reproduction project:**
[res_pan_disk_bug.zip](https://github.com/godotengine/godot/files/1658219/res_pan_disk_bug.zip)

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
