### ISSUE TITLE
Add path short-hand for "owner" Node

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#16030]
**Godot version:**
Godot 3.x

**Issue description:**
It would be convenient if, in addition to using "/path" to get a relative path from the root node, and "path" to get a relative path from the current node, you could do another shorthand for accessing a relative path from the owner node (e.g. a local scene root) using something like "//path".

Thoughts?

**Comment by Zephilinox** [comment]
So "//Particle" instead of "../Particle"? doesn't seem like much of a shortcut to me.

**Comment by vnen** [comment]
The owner is not necessarily the direct parent, it can be further up in the tree. Usually the owner is to root of the scene saved to the disk, because the editor sets that automatically.

Note that if you are relying on the owner, for nodes you instance you have to set the owner manually, because it's not set by default.

**Comment by akien-mga** [comment]
I don't think `//path` is readable, and personally I rarely need to get the owner of a node (especially given the limitations @vnen mentioned), so I don't mind typing `get_owner()` every now and then.

Too much sugar causes health issues..

**Comment by burstina** [comment]
I'd rather prefere to have owner as a property in inspector tab. Sometimes it is more convenient ho set owner there instead in node script, expecially when packing node thru PackedScene.pack()

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
