### ISSUE TITLE
Dependency resolution in the import system

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#16055]
**Godot version:**
3.0 (94b88c7b0f8c140667824e70602b25ac5c53f61d)

**Issue description:**

If a resource depends on another, the import system may fail to import on a clean clone because it might try import the dependent before the dependency and not find it.

This is a proposal to set dependencies for a resource (tracked in the `.import` file) and the import system can postpone the import if one of dependencies is not found.

**Use case**

My [Tiled import plugin](https://github.com/vnen/godot-tiled-importer) always fails on a clean import because it can't load the required images, which are not yet imported. Moving around in the file system makes the import re-trigger and then the import is successful, so this is not much of a big deal, but it would be nice to have.

**Comment by vnen** [comment]
Related to this, setting source dependencies would be interesting too, especially if changing a source dependency can also trigger the reimport, and not only the main source.

**Comment by reduz** [comment]
This is why you can set import priority for inporters, which affects the
order

**Comment by vnen** [comment]
> This is why you can set import priority for importers, which affects the order

Didn't know about this but... *how*?

**Comment by vnen** [comment]
Oh, got it now it's here: https://github.com/godotengine/godot/blob/94b88c7b0f8c140667824e70602b25ac5c53f61d/core/io/resource_import.h#L88

But it's not bound to EditorImportPlugin. Gonna try to add this tomorrow (and updated the import plugin tutorial to add this info).

Still multiple sources for lookup would be nice too.

**Comment by reduz** [comment]
I could not think of a better way to do this without making it incredibly
more complex and inefficient.

If you wanted to detect dependencies you would need to parse the file
twice, making import much slower on large scenes.

**Comment by RabbitB** [comment]
I've run into something I think is the same issue, but I'm not 100% sure, so I'll detail it here, and if it is different, I can split it off into its own issue.

Tested on: Windows 10 x64 & Godot 3 Stable x64

The bare minimum project to encounter the bug is completing the [import plugin](http://docs.godotengine.org/en/3.0/tutorials/plugins/editor/import_plugins.html) guide in the docs, with a change I will detail in the `import` method.

The bug itself is when saving more than one resource on import (the imported resource itself, and any other dependent resource generated from it), the editor will say the dependent resources are fine, but the imported resource itself is malformed. It has however actually saved fine, and can even be used without issue. If you reimport, close the editor and launch again, or do anything else that would cause the editor to refresh the file listings, it'll show the previously malformed resource, as perfectly fine.

![bug](https://user-images.githubusercontent.com/6007524/36050895-2030116e-0d9d-11e8-82a8-9243276890b2.png)

Here you can see what happens: `test_material.mtxt` is the imported material, and `test_material.inverted.material` is the additional dependent resource that is produced. Although it shows `test_material.mtxt` as malformed, it's actually fine and fully usable.

Here's the import code; for brevity, I'm leaving out the rest of the code needed to make the importer function, as it's identical to the guide in the linked documentation:

```gdscript
func import(source_file, save_path, options, r_platform_variants, r_gen_files):
	
	var file = File.new()
	var error = file.open(source_file, File.READ)
	
	if (error != OK):
		return error
	
	var line = file.get_line()
	file.close()
	
	var channels = line.split(",")
	
	if (channels.size() != 3):
		return ERR_PARSE_ERROR
		
	var color
	
	if (options.use_red_anyway):
		
		color = Color8(255, 0 , 0)
		
	else:
		
		color = Color8(int(channels[0]), int(channels[1]), int(channels[2]))
		
	var material = SpatialMaterial.new()
	var inverted_material = SpatialMaterial.new()
	
	material.albedo_color = color
	inverted_material.albedo_color = color.inverted()
	
	var inverted_material_path = "%s.inverted.%s" % [source_file.get_basename(), get_save_extension()]
	
	error = ResourceSaver.save(inverted_material_path, inverted_material)
	
	if (error != OK):
		return error
	
	r_gen_files.push_back(inverted_material_path)

	return ResourceSaver.save("%s.%s" % [save_path, get_save_extension()], material)
```

**Comment by vnen** [comment]
@RabbitB I'm not sure if it's the same issue. Try to print the returned value from `ResourceSaver.save`, maybe something went wrong.

**Comment by RabbitB** [comment]
@vnen Both materials return `OK` when saved.

**Comment by RabbitB** [comment]
So that others can more easily explore what's going on and play around with it themselves, I'm uploading a minimum project that reproduces the problem.

[EditorImportPlugin_SaveMultipleFiles](https://github.com/godotengine/godot/files/1721766/EditorImportPlugin_SaveMultipleFiles.zip)

The project already contains an imported `sample.mtxt`, so when you open it, both it and the additional "inverted" material it generates should be valid and already in-use in the sample scene.

To reproduce the issue, simply duplicate `sample.mtxt` in your local file-system (or create a new one) and let Godot automatically import it. You should see that Godot says the imported file is invalid, while the inverted version is fine. If you look at or try to use the "invalid" material, you'll find that it's actually valid. Once you manually reimport or restart the editor, the "invalid" material will now be displayed normally.
