### ISSUE TITLE
It would be usefull if had something like ArrayMesh.surface_get_group_name()

### ISSUE THREAD

**Issue by nadnam** [godotengine/godot#16061]
**Godot version:**
v3

**Issue description:**
ArrayMesh.surface_get_name() right now returns name of material set for a group in .obj model file (even though it might be expected for it to returns group name). It would be very useful to be able to get group name for every surface as well.

It will help for programmatic extraction only of certain groups within model or modification itself (eg. if you have .obj model with player character and 3 types of armor, and want to extract only armor num.1).

**Comment by reduz** [comment]
you can import the OBJ file as scene if you want separate stuff

**Comment by nadnam** [comment]
Thank you, but it is too high level for purpose I work on eg. tool script with exported Mesh var, which upon assigning a mesh, does some job with it (loops trough surfaces, does some recognizing, creates new ArrayMesh-es just from certain surfaces etc.)

I managed to circumvent this limitation but it is not idiomatic.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
