### ISSUE TITLE
Collapsed tabs in project settings are not saved (3.0 RC3)

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#16077]
**Godot version:**
3.0 RC3

**OS/device including version:**
Ubuntu 16.04

**Steps to reproduce:**
![2018-01-26 12-54-04](https://user-images.githubusercontent.com/11325733/35426888-1d73749c-025e-11e8-8e9b-f5621f9c3762.png)

close/open

![2018-01-26 12-54-14](https://user-images.githubusercontent.com/11325733/35426897-2a1bb916-025e-11e8-9762-c309c36eeac5.png)

**Comment by akien-mga** [comment]
I don't see much use for saving this information, but if others would like this feature, it can be saved in project metadata.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
