### ISSUE TITLE
Models imported as Scenes with duplicate mesh nodes AND -col ignore all but one meshinstance.

### ISSUE THREAD

**Issue by Einlander** [godotengine/godot#16097]
**Godot version:**
v.3.0.stable.official

**OS/device including version:**
Windows 10 Pro

**Issue description:**
When importing a .dae or importing a .obj as a scene, any mesh node that has the exact same name and has the -col tag will not be imported except for the first instance.

If you look at the SceneTree the meshes are not imported but the collisions are. Further the collision names are 'MESHNAME -col#' instead of 'MESHNAME# -col'

**Steps to reproduce:**
Import a model with multiple meshes with the same name with the -col tag.

**Minimal reproduction project:**
[Model Import Bug.zip](https://github.com/godotengine/godot/files/1669365/Model.Import.Bug.zip)

**Comment by glaforte** [comment]
As a self-note: background information about the import of collision meshes: 
https://docs.godotengine.org/en/latest/getting_started/workflow/assets/importing_scenes.html

**Comment by glaforte** [comment]
This data set does not come from our "principal" content pipeline using Blender for modeling. Rather, it was exported from AC3D. (http://www.inivis.com)
Could not reproduce the issue in Godot 3.1/master.
Could not reproduce the issue in Godot 3.0.6-official.
I reproduced the issue, as reported, in Godot 3.0-stable.
So, I think this proves that the issue is already fixed. :)

**Comment by akien-mga** [comment]
Awesome, thanks for testing!
