### ISSUE TITLE
request: add option to replace asset with another

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#16109]
**Godot version:**
3.0

It would be very handy to be able to replace an asset with another in all of the owner scenes.
For example. I have made a new mesh, which I want to replace an old version of. If I delete the old one, I have to manually go through and edit all the scenes that the mesh is in, and point it to the new version.

So it would be cool to have an option in the owner and/or in the delete dialog to have an option to update all owners at once.

I hope that makes sense :)

![godot-delete](https://user-images.githubusercontent.com/650506/35470895-6b658c0a-03a1-11e8-8de9-e6cb846000a0.jpg)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
