### ISSUE TITLE
Cast Switch Statements in C# Syntax Error, ':' Expected

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16127]
**Godot version:**
3.0 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Cast switch statements in C# fail to build with a syntax error "':' expected", despite the syntax being correct.

**Steps to reproduce:**
Attempt to build a Mono project that has a cast switch statement.

**Example:**
`Node node = new Position2D();`
`switch (node) {`
`    case Position2D _:`
`        GD.Print("Node is a Position2D!");`
`        break;`
`}`

**Extra Info:**
See this article on switch statement patterns. https://visualstudiomagazine.com/articles/2017/02/01/pattern-matching.aspx
Cast Switch Statement Example From Article:

**Comment by Cygon** [comment]
Godot uses Mono for their C# support.

However, Mono hasn't yet implemented all bleeding edge C# features (this one being from C# 7.0, introduced in March 2017). See [Mono C# Compiler](http://www.mono-project.com/docs/about-mono/languages/csharp/) for a list of which features are supported.

In addition to that, Godot 3.0 will include a specific, stable, Mono version. According to their blog:

> Mono SDK in version 5.x, ideally 5.4.1.7

Though you might be able to compile Godot yourself against newer Mono versions, the official stable build (and thus, export templates, if downloaded rather than built) are likely to only support the features in [Mono 5.4.*](http://www.mono-project.com/docs/about-mono/releases/5.4.0/).

**Comment by 11clock** [comment]
Do you recommend i leave my project in C# 6.0 for now?

**Comment by neikeq** [comment]
What's the MSBuild version on your system?

**Comment by 11clock** [comment]
14, 15 doesn’t work because of a “csc.exe not found” error.

**Comment by neikeq** [comment]
You need MSBuild 15 for C# 7 support. What option do you have specified in `Editor Settings --> Mono --> Builds --> Build Tool`?

I recommend you to set it to `MSBuild (System)`, for which you will need to install Visual Studio 2017, or just [Build Tools for Visual Studio 2017](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15) if you don't want to install just these tools.

I and other people experience the same problem with Mono's MSBuild. Setting the `CscToolsPath` environment variable fixes the `csc.exe` error, but results in a new one (not being able to load assembly `System.IO.FileSystem`).

**Comment by 11clock** [comment]
I was using MS Build Tools 2017 , and I had it set to System in the settings.

Anyways uninstalling MS Build Tools 2017 and reinstalling Visual Studio Community 2017 with the .net desktop tools checked seems to have resolved the issue.
