### ISSUE TITLE
Add a console panel, to allow automating editing, macros, and efficient tool creation.

### ISSUE THREAD

**Issue by Evi1M4chine** [godotengine/godot#1613]
Applications, in general, have the problem that they impede automating one’s work away, as they offer no scriptability of the actions available inside the application. Even though automating one’s work away is the whole point of a computer.

Maya has solved this, by having an in-application Quake-style console, and having every action in the UI be a console command too. Then the user can also do the vice-versa, and just type in console commands, e.g. with loops and variables, to automate repetitive or common tasks.
He can also do editing, then select the resulting console commands, and create a tool from them, including a button.

In Godot this could take the place of the output window (make sure it’s accessible by keyboard only), be a GDScript console, and allow extremely easy and comfortable creation of GDScript tools, which could then be expanded as normal scripts in the normal script editor, if required.

It would also make tasks like “change the property X of all nodes in my selection or of a certain type to Y” very easy, or even sanely possible at all.

The best part is that it is probably very easy to implement.
Godot already has GDScript and the ability to make tools; it already offers editing code on a line with code completion; and everything that can be done in the UI is probably already available via GDScript.

So with a bit of luck, a simple version should be possible to do with a few GUI changes in a single day. — E.g. at first lacking the automatic creation of commands in the console when editing the visual way.

It would also quickly grow the set of available tools and wizards, made by users. :)

**Comment by TheoXD** [comment]
It's good that you've mentioned it just in time, before any work on 1.2 is being done. Currently there is only Scene->Run Script which executes scripts that extend EditorPlugin that isn't as helpful as the API blender provides.

**Comment by bojidar-bg** [comment]
:+1:

**Comment by alketii** [comment]
This looks quite handful even for "normal" users.

**Comment by phoe-krk** [comment]
I do want it. It's tedious to make a game without a responsive and interactive editor and the ability to create stuff live.

**Comment by willnationsdev** [comment]
I think I'd like to tackle this, after I finish my current overhaul of the custom type system.

Namely, I'd like to add support for EditorScript's run method to take in parameters and for it to return a value: something that would allow us to have the engine provide EditorScripts in-house, and allow users and plugins to define additional EditorScripts. And then have the interactive console panel simply be able to chain together all of the defined instructions (perhaps just use the basename of the file as the command name automatically).

**Comment by Anutrix** [comment]
Any updates? Seems like awesome feature. Anyone working on this?

**Comment by willnationsdev** [comment]
Not that I know of @Anutrix. See godotengine/godot-proposals#70 for what I believe is ultimately a prerequisite for this project.

There are one or two console-like plugins out there in the world, but I believe a more fundamental, centralized coordination of editor features is needed before it will be practical/viable.

**Comment by aaronfranke** [comment]
@Evi1M4chine @TheoXD @phoe What is your use case for this feature? Godot's plugin system is very nice, and I have a feeling that this feature might not be desired due to these points in the [proposal template](https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhacement-proposal.md):

> **If this enhancement will not be used often, can it be worked around with a few lines of script?:**

> **Is there a reason why this should be core and not an add-on in the asset library?:**

It's really hard to know exactly what this feature would look like without example use cases, and once we know the use cases we can also explore the feasibility of implementing them using Godot's existing plugin system, possibly even as an asset on the [Godot Asset Library](https://godotengine.org/asset-library/asset).

See also: [Best practices for engine contributors](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html).

**Comment by willnationsdev** [comment]
@aaronfranke 

The use case is summed up as "any reason to use a Linux terminal instead of some GUI application inside Linux". Small apps to solve small problems. Easily share and build small apps together. Easily combine small apps to solve *arbitrary*, **ad-hoc** large problems that appear on the fly.

Let's just take OP's basic example and expand on it:

> change the property X of all nodes in my selection or of a certain type to Y

GUI solution: EditorPlugin. Lots of work, tons of boilerplate, tons of unnecessary bloat, just to do a simple thing.

Godot's alternative? EditorScript. Only, EditorScript can't accept parameters, doesn't return any value, and can only be executed in isolation, without supplying any value to other EditorScripts of any kind. What's more, using EditorScripts for an ad-hoc solution to a problem is already cumbersome enough as it is.

Small problems:

1. Select a collection of nodes based on EditorSelection.
1. Select a collection of nodes based on type.
1. Merge two collections.
1. Map an operation over a collection.
1. Set a property on an Object from X to Y.

All can be achieved with the scripting API. But that means that in order to make reusable solutions for the community, you have to make [utility classes](https://github.com/godot-extended-libraries/godot-next/blob/master/addons/godot-next/global/file_search.gd) that cannot be executed on their own.

1. create an EditorScript file.
1. Go to the ScriptEditor.
1. Open the EditorScript you made.
1. Write the code that actually calls the utility class's logic. and performs the operation you intend to do with that utility class.
    - If you don't already know how the class works, look up documentation, read the source code, w/e. There is no standardized way of doing this at all.
1. Press Ctrl+X to execute it (which often doesn't work for me though, so instead I have to go through the menus, bleh).
1. Now that you are done with your ad-hoc solution to the arbitrary problem you came across, manually delete the file to clean up your mess or build up clutter in your project by leaving it there.

The alternative, ideal case would be to easily and composably put together a solution from reusable mini-programs that can do the work for you, perhaps by headlessly interacting with the Godot Editor:

    $ { getn root -t Control & getn root --selection } | unique | map set x y

Anyone who wants to migrate away from having to use the GUI controls to manipulate the editor and instead use their keyboard with quick commands and scripts of commands will want to use a console like this. In addition, if you could map these various commands to single keystrokes, you get closer and closer to a modal editing experience akin to vim or emacs.

Not everyone who uses Godot likes using a GUI editor to do their gamedev. In fact, I've encountered many on Reddit who specifically ask to what extent they can avoid using the Editor and just rely on their text editor. Right now, it's quite difficult to get away with that, but the more you empower script-based tools for live editing of the Editor state, and the more headless you make it, the easier it'll be to accommodate these users. It also naturally benefits the development of tools for power users who still enjoy using the GUI, but want to more easily automate tasks they want to perform.

As for whether or not it should be part of the engine or not, that's debatable. It would certainly be convenient for it to be part of the engine, but that alone isn't reason enough. Something like this could easily be its own separate application that communicates with the Godot Editor process headlessly and enters a REPL.

The only problem is that doing this kind of thing is still *impossible* to do because Editor operations are not properly centralized, nor are enough of them exposed to the scripting API to empower that kind of flexibility (which godotengine/godot-proposals#70 resolves). You then also need to empower an external application to communicate with a Godot Editor instance (not sure if there is already an Issue/Proposal for that).

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
