### ISSUE TITLE
Intercept URL schemes for communication between apps

### ISSUE THREAD

**Issue by tomwassing** [godotengine/godot#16203]
I would greatly simplify implementing authentication with third parties if it is possible catch 'URL Schemes/Deeplinks' in apps. On iOS it is provided with [URL Schemes](https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10) and [Universal Links](https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html). On Android this is implemented using [intent-filters](https://developer.android.com/training/app-links/deep-linking.html). 

Currently the only way (AFAIK) is to edit the export template, which doesn't seem like the 'maintainable' way to go.

**Comment by LunaSquee** [comment]
YES PLEASE! I thought I was the only one with the idea to authenticate game sessions using URL Schemes, but thankfully I'm not!
I would REALLY love to see this happen, as I own a network which sole purpose is to unite communities with a single login, meaning people wont have to use passwords on my network's services and this would really come in handy because I'm getting into game development and I'd love to see my network extended to games.

**Comment by tomwassing** [comment]
Any updates regarding this issue?

**Comment by NilsIrl** [comment]
What would a possible implementation look like?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
