### ISSUE TITLE
Valgrind smells invalid writes with gles3 renderer on x11-64

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#16214]
**Godot version:**
3.0

**OS/device including version:**
Linux 64 (ubuntu 16.04)
CPU intel i7-6600U with integrated GPU chipset (using driver mesa i965, see glxinfo logs)
[glxinfo.log](https://github.com/godotengine/godot/files/1679781/glxinfo.log)

**Issue description:**
Starting Godot (see enclosed minimal project) with valgrind shows a lot of invalid writes involving the X11 context and gles3 rasterizer. Valgrind even end up telling us:

```
More than 10000000 total errors detected.  I'm not reporting any more.
Final error counts will be inaccurate.  Go fix your program!
```

[godot-x11-64-gles3-i965-leak.log](https://github.com/godotengine/godot/files/1679771/godot-x11-64-gles3-i965-leak.log)

**Minimal reproduction project:**
[project-gles3-leak.zip](https://github.com/godotengine/godot/files/1679776/project-gles3-leak.zip)

**Comment by hpvb** [comment]
This doesn't seem to happen on F27 with RX580 running 17.2.4. 

Would you have any way of testing with a newer mesa version so we can narrow down the problem?

**Comment by bfloch** [comment]
The reported issues are within the mesa intel driver not Godot, deep down in the backtrace. Look at the Godot-side calls. They are pretty normal gl calls and such. I doubt all of them are invalid.

I would suspect these are false positives but if you are curious install debug symbols for mesa and it will tell you where the problem happened.

Either way for sane results on Godot suppress it from valgrind.

**Comment by touilleMan** [comment]
I tried to install the mesa debug symbols (with `sudo apt install libgl1-mesa-dri-dbg`) but failed miserably: there is still no symbols while using valgrind :'(

If someone knows better how to get them I'll appreciate

**Comment by qarmin** [comment]
I created an issue in freedesktop about this issue https://bugs.freedesktop.org/show_bug.cgi?id=111001

**Comment by akien-mga** [comment]
You need to build Mesa with valgrind support enabled (toggled on automatically if you have valgrind build dependencies, and as long as you don't pass `-Dvalgrind=false`).

@reduz also ran into this issue recently, and it turns out that it's not a Mesa issue per se, but a downstream packaging issue. You should open a bug report with Ubuntu instead to have them enable valgrind support in their Mesa package.

See https://twitter.com/reduzio/status/1141356308882427904
and solution: https://twitter.com/Akien/status/1141414741346312193
