### ISSUE TITLE
ItemList Select Mode Single functions

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#16217]
Godot Master

Currently there are a few functions that could be simpler, maybe I am missing something...

Currently
```
# get_item_text
if ItemList.get_selected_items().size()>0: # has_selection()
	ItemList.get_item_text(ItemList.get_selected_items()[0])

# unselect
if ItemList.get_selected_items().size()>0:
	ItemList.unselect(ItemList.get_selected_items()[0])

# add and select
ItemList.add_item("test") 
ItemList.select(ItemList.get_item_count()-1)
```
Suggestion
```
# get_item_text
if ItemList.has_selection(): 
	ItemList.get_item_text() # knows the id since it can be only one.

# unselect
ItemList.unselect() # knows the id since it can be only one.

# add and select
ItemList.add_item("test")
ItemList.select() # default -1 to select the last index
```

I could use the "item_selected" signal for `unselect, get_item_text` but out of the box looks and feels better.

**Comment by Zylann** [comment]
Maybe that's because you can have multi-selection in an `ItemList`.

**Comment by AlexHolly** [comment]
All ItemList functions are made for multi-selection this is not optimal to work with when using single-selection.

I use `get_item_text()` to get the selected text(most of the time), you could still pass the id you want to get.

**Comment by Zylann** [comment]
@AlexHolly it doesnt justify changing existing functions though, otherwise that's an entire feature going away... maybe having additional helpers?

**Comment by guilhermefelipecgs** [comment]
> if ItemList.has_selection():

We have this method ```bool ItemList::is_anything_selected()``` in  c++ but it's not exposed to gdscript.

**Comment by AlexHolly** [comment]
@Zylann I see only one small change for `get_item_text()` when someone is passing -1 and expects an error in return are there any other use cases that would change when `get_item_text(id=-1)`?



@guilhermefelipecgs sounds good.

Any idea why `ItemList` has no variable to manage/remember the selected items?
This would speed up `get_selected_items()` and `is_anything_selected()`

**Comment by Zylann** [comment]
@AlexHolly I don't understand what you mean about this -1 thing

**Comment by Zylann** [comment]
@AlexHolly it's not a good idea to change the meaning of a function like this, I would simply add a `get_selected_item` function (although I'm ok with the current API, it's not that bad to write [0]). Also note that these return IDs because items in this container can have attributes such as icon, text and metadata. You can still add shortcuts for simpler cases but there might be a lot then...

**Comment by puppetmaster-** [comment]
In my Gui I want to show and hide certain elements so that I can do this I need to know the moment when there is nothing selected in an item list.
Is there a trick to finding out? Shouldn't there be a signal for that? Or what is the right approach?

**Comment by AlexHolly** [comment]
There is a signal for 'nothing_selected'(in 3.0) but I had some issues with it maybe it works fine in your usecase.

**Comment by puppetmaster-** [comment]
I looked in the [stable branch](http://docs.godotengine.org/en/stable/classes/class_itemlist.html) but found nothing. I thought stable was the 3.0 version.
The signal is listed in the [latest](http://docs.godotengine.org/en/latest/classes/class_itemlist.html).
Sorry, didn't know it was newly added.

**Comment by AlexHolly** [comment]
@puppetmaster- Looks like "nothing_selected" means "no_item_selected"

Currently
"nothing_selected" : Will fire when you click on a non item area. https://github.com/godotengine/godot/pull/13245

Looks like this behavior is expected but the name is a bit confusing.

Expected
"nothing_selected" : Will fire when ItemList.get_selected_item.size() returns 0

Maybe rename "nothing_selected" to "no_item_selected" and add a new feature for "nothing_selected"?

**Comment by tripodsan** [comment]
btw, this behaviour has some flaws (godot 3.0.6, in single-row selection mode):
- if a selected row is _clicked_ again, it deselects, but no signal is emitted 
- clicking outside the _tree_ signals `nothing_selected` but the selected row doesn't deselect.

is there a way to work around this?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
