### ISSUE TITLE
What about the stale repository branches?

### ISSUE THREAD

**Issue by RiverMesa** [godotengine/godot#16239]
So currently there's six branches in the repo, but only half of them see *any* real activity nowadays, and that's probably not going to change.
`2.0` is completely irrelevant with the `2.1` branch around, `2.2-legacy` is straight-up called a legacy branch (and everything that was planned to go in it is now in `master`, as far as I know), and I don't even know what the purpose behind the `lambda` branch was, but that one is also about as dead as it gets.

I think those stale branches should be deleted entirely, since they really just serve no purpose at this point, unless there's some sort of desire to keep them "for historical reasons" that I'm unaware of.

**Comment by akien-mga** [comment]
The `2.2-legacy` branch could be deleted, but `2.0`  should be kept. It was used to make releases (and has commits which were thus never made on the master branch), and we need to keep this history available. Same for `2.1` once we stop updating it.

`lambda` is a rebased version of a never-merged PR. Since then it got rebased and proposed again in this PR, so the branch could be deleted.

**Comment by Calinou** [comment]
The stale `2.2-legacy` branch has been removed a while ago, closing.
