### ISSUE TITLE
“System Environment Variable” Equivalent

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16248]
Godot uses a file path system for references. This is a simple way of doing it with decent code completion for it as well, but questions arise when you need to move files or change file names. I propose being able to make the equivalent of system environment variables in order to simplify refactoring. I know that you can technically just save paths in a singleton node, but I think that the environment variables could be streamlined like input actions. That makes them easier to manage and also provide a means of auto completing them.

**Comment by Zylann** [comment]
See https://github.com/godotengine/godot/issues/15673

**Comment by Calinou** [comment]
> I know that you can technically just save paths in a singleton node, but I think that the environment variables could be streamlined like input actions.

The ProjectSettings class can achieve this to an extent. However, these are considered variables, not constants, so you can't use them in `preload()` calls which require constant expressions.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
