### ISSUE TITLE
Method List isn't updated if there is a syntax error

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16263]
**Godot version:**
 e7cf2b2

**Issue description:**
The gif will explain it better than I:
![peek 2018-01-31 20-55](https://user-images.githubusercontent.com/30739239/35652100-54b6c228-06c9-11e8-8eb9-a7d585814808.gif)

**Comment by NathanWarden** [comment]
Does it confuse the list because the code was removed, or because the ready function no longer has correct code and therefore it has no idea what the other functions are?

**Comment by NathanWarden** [comment]
I just tried it and put `var i = 0` above `test, test, test` then I removed the code and gave it an second to re-evaluate the code and it find the other methods just fine.

So, it's because your ready function no longer has valid syntax in it and therefore doesn't understand anything under it. So, it seems there's no bug here.

**Comment by LeonardMeagher2** [comment]
needs to add pass under `func _ready():`

**Comment by YeldhamDev** [comment]
@NathanWarden @LeonardMeagher2 The lack of `pass` isn't the problem:
![peek 2018-01-31 22-33](https://user-images.githubusercontent.com/30739239/35655002-e596e02c-06d6-11e8-8c97-61045856ddb3.gif)

**Comment by neikeq** [comment]
@YeldhamDev I think it uses the method line it got the last time the script could be parsed without errors. In your last example, `test1` and `test2` are not moved to a different line, so the old line is still valid.

**Comment by YeldhamDev** [comment]
@neikeq Yeap, did more tests, and seems that changing the lines which methods are doesn't update the list if there is any syntax error at all.

It's still kinda annoying, so I will change this to a request.

**Comment by vnen** [comment]
The method list can't update in this condition because if there's a parse error, the parser can't know what functions are actually defined nor where they are.

The only possibilities is to clear the list, or only show the functions detected until the error happened (which in the given example would be the same as clearing, since the first function errors out). Either one is worse for usability than the current way.

**Comment by YeldhamDev** [comment]
@vnen I see. Well, closing this then.

**Comment by neikeq** [comment]
I think we could detect if the user removes lines previous to the function, and go to `parsed_func_line - num_deleted_lines`. I've seen some IDEs like IntelliJ IDEA do this for SearchAll results.
