### ISSUE TITLE
Variables exported in a C# script don't update during runtime

### ISSUE THREAD

**Issue by divmgl** [godotengine/godot#16302]
**Godot version:**
3.0

**OS/device including version:**
Windows

**Issue description:**
Updating exported variables in a C# script has no effect during runtime.

**Steps to reproduce:**
* Create a project
* Attach a C# script to a Node2D
* Export a `Vector2` from script
* Update position on every frame based on exported variable

The position is not updated because variables don't update during runtime.

**Comment by neikeq** [comment]
Do you mean the value you set in the inspector is never applied when you run the game?

**Comment by divmgl** [comment]
@neikeq From how I have it understood based on the steps to reproduce, the variables from a C# script don't update at all in the Godot editor. I could be wrong though, maybe I forgot to mention that the game needs to be running

**Comment by Calinou** [comment]
@divmgl Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
