### ISSUE TITLE
Custom theme in Project Settings causes Controls to render incorrectly.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#16344]
**Godot version:**
3.0

**OS/device including version:**
Linux 64 bit.

**Issue description:**
Setting a custom theme causes some Controls to be invisble except for a bit of poorly-rendered text that says "ERROR". So far I've confirmed this only with the several controls that are in the example project. I haven't tested further but I suspect it probably affects all Controls.

**Steps to reproduce:**
* Make a theme resource
* Add a default font to it
* Save it as a .tres
* Project > Project Settings > Gui > Theme
* On the row that says Custom, click the folder icon on the right, and click File
* Navigate to the .tres file you just made.
* Run your project and see messed up widgets
* Go back into Project Settings and clear the custom theme
* Your widgets are back!

Or just use the minimal example project! Extract, open, run.

**Minimal reproduction project:**
[CustomThemeBug.zip](https://github.com/godotengine/godot/files/1691376/CustomThemeBug.zip)

**Comment by AaronWizard** [comment]
I have this error too. This is what happens when I have a label while trying to use a custom theme.

![screen shot 2018-02-07 at 5 37 04 pm](https://user-images.githubusercontent.com/33398493/35943041-305b16a8-0c2e-11e8-9db8-66961ff42ba5.png)

I'm not sure if the label's black text is a bug or if I just missed something in my theme. I'm more concerned about the "ERROR" that appears in the background. I've seen this with multiple font TTFs.

My own example project:
[themetest.zip](https://github.com/godotengine/godot/files/1704863/themetest.zip)

**Comment by Mintormo** [comment]
This is not bug. When you make empty theme, value of stylebox in control is null beacause It's used default style value. It's maked from .png with "Error" text.
Here: scene/resources/default_theme/default_theme.cpp: 872
I think this issue is worth to close. Else It's maybe change default style to EmptyStyleBox class.

**Comment by RodeoMcCabe** [comment]
> Else It's maybe change default style to empty style box.

That *definitely* needs to happen. Right now, for example, I have a HScrollBar. I don't want to have increment or decrement icons for it, so I left them blank. But instead it looks like this: 
![godot-theme-error](https://user-images.githubusercontent.com/25570524/39098156-5dc9ddf0-461b-11e8-948d-69f7166c655d.png)

It's kind of dark, but you can see the problem. I don't think it should be necessary to manually set every stylebox that you don't intend to use.

**Comment by AaronWizard** [comment]
I agree. It wasn't clear to me that controls all have a style box, even labels, and that a null style box causes the "error" background.

**Comment by reduz** [comment]
I am wondering whether the error icon should just be a small empty one.. is there much point on showing it?
