### ISSUE TITLE
Switching WindowDialog types leaves garbage buttons

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16350]
**Godot version:**
4ab5227

**Issue description:**
It only appears in the editor and if the project is reopened, it turns back to normal, but still:
![screenshot1](https://user-images.githubusercontent.com/30739239/35767429-49478984-08d3-11e8-9493-e10a80f6fff5.png)

**Comment by Alexander-Alekseev** [comment]
**Godot version**:
Master branch (9f590b460ee8f6e0026b14fbc336b7b7ad977ee0).

**OS**:
Windows 10 x64 Fall Creators Update.

**Steps to reproduce**:
1. Create a new scene;
2. Add AcceptDialog;
3. Select AcceptDialog -> RMB -> Change Type;
4. Select ConfirmationDialog.

**Expected result**: OK button, Cancel button.
**Actual result**: 2 OK buttons, Cancel button.

Possible reason (line 2505):
https://github.com/godotengine/godot/blob/9f590b460ee8f6e0026b14fbc336b7b7ad977ee0/scene/main/node.cpp#L2501-L2506

When we replace AcceptDialog with ConfirmationDialog, we remove all children nodes from AcceptDialog and _add_ them to ConfirmationDialog.
When I commented in the pointed line I don't have the bug, but I'm not sure that it is a proper solution, because it helps us with Dialogs, but may or may not break other types.

Any ideas?

**Comment by akien-mga** [comment]
We'd need a way to distinguish between Node-specific children (like those buttons, which don't appear in the scene tree but are part of the node itself) and custom children (instanced in the SceneTree dock or by script). Not sure how to do that efficiently.

**Comment by zaniar** [comment]
Isn't marking a node as _internal node_ enough?

**Comment by LinkDoyle** [comment]
I think it could be solved by adding child to `p_node` only if the condition `child->is_owned_by_parent()` is true. Can I work on it?
