### ISSUE TITLE
Delta Limit

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16351]
I would like to propose a new project setting that allows you to set a limit for delta. This means that you can effectively have your game slow down if the next frame takes too long to render. I am not sure how this would affect the physics process loop, maybe halt its loop when process hits its limit?

**Comment by raymoo** [comment]
@11clock You could slow down the physics process by reducing the number of times it is called. How many times it is called is already based upon the process delta (essentially the physics processing accumulates time from the variable delta, and "consumes" one physics delta per physics tick executed), so you would just need to use this clamped delta value in place of how the variable delta is used now with physics.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
