### ISSUE TITLE
Intermittent "Insufficient OpenGL/GLES driver support error" causing Godot to crash; requires system restart to remedy

### ISSUE THREAD

**Issue by TylerCompiler** [godotengine/godot#16372]
**Godot version:**

3.0

**OS/device including version:**

OS: Windows 10 Version 10.0.16299 Build 16299
GPU 1: GTX 960M - Driver Version	22.21.13.8528
GPU 2: Intel HD 4600 - Driver Version 20.19.15.4549
 
**Issue description:**

Despite Godot initially loading, and while usable, eventually will no longer respond, and crashes. This is regardless of any specific action ie. there is no one specific task that initiates the crash, nor is there any reliable timeframe in which it will happen, but it always does.

Upon attempting to restart Godot, a series of errors pop up (screenshots provided) which reference a lack of OpenGL support. Again, this is despite the fact that I, up until the moment of crashing, am capable of using Godot without any major issue (I have another ticket open, but deals more with "cosmetic" issues). On top of that, both my Intel HD, and GTX960M support above OpenGL 3.0. Though support on the 4600 may be sketchy, this is not the case for the 960M, and the issue persists even when explicitly running Godot through my 960. The only fix at this point appears to be a full system restart.

**Steps to reproduce:**
None in specific; normal usage.

![error1](https://user-images.githubusercontent.com/12816709/35773278-36e20c04-091b-11e8-99f0-e7c910a28dc1.png)
![error2](https://user-images.githubusercontent.com/12816709/35773279-36f4c376-091b-11e8-8ba3-5d6082d3a829.png)
![error3](https://user-images.githubusercontent.com/12816709/35773280-37017dbe-091b-11e8-8183-d4bd34e0ddbb.png)

**Comment by TylerCompiler** [comment]
So I just noticed something that could possibly be related to this issue (if not, it may be something else to look into):

In the editor, the Update Spinner seems to move/respond to any type of input whether it is mouse/keyboard/etc, completely regardless of any changes happening in the project. When it comes to moving the mouse cursor on-screen while the editor is open, the velocity of the mouse movement seems to correlate with the rotation of the Update Spinner. Upon alt-tabbing from another window back to Godot, the spinner appears to rotate much more rapidly than normal for a few seconds before stopping (at least until there is once more some type of user input).

Furthermore, I've noticed that the crashing appears to be expedited if Godot is no longer the focused window (maybe this is related to my [other issue]( https://github.com/godotengine/godot/issues/16371)?) That said, this does not appear to be a requirement, as the editor will crash even mid-use; it just appears to take a bit longer before the inevitable transpires.

**Comment by BlenderNPR** [comment]
This happens to my system as well. It has Intel HD5300. The whole OS totally freezes (the only way is to pull the plug) or Godot just crash without any sign of error.

**Comment by akien-mga** [comment]
It's "expected" that Godot crashes, but it shouldn't crash the OS... Properly handling #15324 should help with that though.

**Comment by akien-mga** [comment]
Nevermind, just read again and you're all running Godot on OpenGL 3.3-capable drivers. Sounds like something crashes your drivers, which trigger the issues about lack of OpenGL 3.3 support when you try to run Godot again, and may eventually crash Windows 10 as I guess without working graphics drivers it can easily blow up.

**Comment by akien-mga** [comment]
If one of you can build from source and try to get a stacktrace of when Godot crashes in the first place, that would be great. Or narrow down what action triggers that crash.

**Comment by metalDS** [comment]
I was having the same problem so i doctored my PC a bit. I'm not sure if this fixed it and i'm not a computer expert so take my word for granted, but i did two things though COULD HAVE fixed my issue. 

i had an NVIDIA 940M card and i updated the driver to the most recent edition (390.77)

i also messed with regedit to fix the so called PCI express firmware bug. you may have a different driver though: look up the storahci.sys driver bug.

again not saying that these things fixed the problem, godot hasn't crashed since i made these changes. I don't wanna be responsible for bricking someones rig so maybe get a more informed opinion if you decide to try these things

**Comment by FlatBartender** [comment]
I had the same problem up until yesterday too. Today godot seems pretty stable though, so I'm sharing what I did.
In this issue, every people experiencing this crash use a laptop (and so do I) with an nvidia card. So I thought it might be related to the "preferred GPU" setting in the nvidia control panel. While godot said at startup that it was using the nvidia card, in the control panel it was set on the integrated GPU.
I switched it to nvidia GPU and it solved the issue, apparently.

**Comment by kaespr** [comment]
I have the same issue as BlenderNPR:

My GPU is Intel HD 5300 with latest drivers, ( on Lenovo Thinkpad Helix 2nd gen,  Core M-5Y71, 4GB RAM, Win10 x64)  Godot version 3.0.1

After using the editor for 10-15 min the whole system crashes. No BSOD, no console errors, complete freeze. I have to cycle the power to make the computer usable again. This doesn't happen on any other software (example Blender) or in Godot 2.1.4. 

I checked for memory and disk errors, no luck. I know the GPU is on the lower side, but for the time it is working it runs quite smoothly, even 3D demos with default options. 

I tried setting vsync off as mentioned in #15408, that didn't help.

One thing i noticed, if i have a Tilemap node in the active scene the crash happens faster, also 3,01 crashes faster than 3.0 ( under 5 min)

I wanted to open a new issue, but after searching I found this issue. I hope it is ok to post here (new on github) Maybe OPs problem is related to Intel HD not Nvidia?  Would like to help to debug this, but don't know where to start since no logs or dump files are produced.

**Comment by eon-s** [comment]
Windows should have some system report, maybe a driver crash before the slowdown, falls creator update introduced many new bugs with video drivers so maybe can be checked on that too.

**Comment by FlatBartender** [comment]
Windows "logs" (if you can call it like that lol) are there : [godot_crash.zip](https://github.com/godotengine/godot/files/1777200/godot_crash.zip). No idea how to read this file if you're not on windows though.
I compiled godot from source (says v3.1.dev.mono.custom_build.7568a45 in the launcher), but it also happens with 3.0 and 3.0.1. Also, it might be worth mentioning that I've been having problems with the nvidia drivers for quite some time now, it used to bluescreen windows but now apprently windows can handle a crash. It's probably more related to the nvidia drivers than godot since it happens in other apps too.

**Comment by Sesian007** [comment]
Utilicen UBUNTU y se quitan elProblema de encima, Funciona
![image](https://user-images.githubusercontent.com/36307190/40572360-92d77692-606f-11e8-8a46-385913d671b6.png)

**Comment by Zireael07** [comment]
@Sesian007: cual es tu tarjeta grafica?

**Comment by akien-mga** [comment]
A priori all those issues are due to faults in Windows GPU drivers, Godot cannot crash drivers or much less the OS itself. There's sadly not much we can do to fix such OS issues.

With Godot 3.1 you can use the GLES2 renderer which should hopefully not cause your drivers to implode...
