### ISSUE TITLE
RayCast2D exclude parent recursive

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#16378]
Suppose I have a scene setup like this:
Kinematic2D
--> Sprite
----> RayCast2D (exclude parent ON)

I would expect RayCast2D to exclude the Kinematic2D from its collision (or any physics bodies along the way up to the parent), but it doesn't.

Is there a reason for this? I feel like the RayCast2D _should_ exclude the Kinematic2D.

**Comment by Zephilinox** [comment]
Sprite is the parent, not kinematic body.

**Comment by Lucrecious** [comment]
@Zephilinox Right, but I think it would make more sense if RayCast2D excluded the parents recursively - especially since Sprite is not a Node that can be detected by the RayCast2D.

It doesn't make sense to "exclude parent" when the parent is already excluded in the case of Sprite. What I really want from "exclude parent" is _at least_ the first physics body that is the recursive parent of RayCast2D.

**Comment by Zephilinox** [comment]
I think the way godot handles node-relationships is that it's okay to get children recursively, but not parents (at least I can't think of anything that recursively goes upwards)

Why does raycast2d need to be a child of your sprite?

**Comment by Lucrecious** [comment]
It's not a big deal, added my kinematic body as an exception to the raycast works fine, but it's a little inconvenient.

I have tied my ray to move with an animation on the sprite I have. Imagine I have a character that slices his sword, I might animate the ray to line up with the sword as it swings (this isn't the exact situation, but it's pretty close). I use the ray to detect walls and particles spawn at the hit point on the wall.

The problem is when I flip my sprite (to get the player to be able to swing his sword to the left instead of always to the right), the ray doesn't flip with the sprite. So I decided, instead of using flip_h to flip the sprite, I negate the scale.x of the sprite. This works well when the ray is a child of the sprite because the scale affects the ray as well when it "flips" the sprite.

This works exactly how I want except for the ray "exclude parent" not excluding the kinematic body its (not directly) under.

So that's why I have a ray as a child of a sprite, so when my sprite flip so does my ray (and inadvertently everything else under the sprite, which works really well for what I want to do).

**Comment by dijs** [comment]
My use case for this is a `Shooter` -> `LaserGun` -> `Laser` -> `RayCast2D` Node hierarchy.

It doesn't make sense for the `Shooter` to do the business logic of ray casting when it is the Laser's job. Also, upon collision the laser should update it's line points.

My opinion is that the `RayCast2D` in this scenario would exclude the shooter.

Does this make sense?

**Comment by Janglee123** [comment]
`add_exception(owner)` will work for both cases.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
