### ISSUE TITLE
unable to set_surface_material before node is in tree

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#16376]
**Godot version:**
3.0 stable

**OS/device including version:**
windows 10 x64

**Issue description:**
unable to set a mesh with a material before the mesh/material is added to the scene. This is disappointing because that mean the mesh can't have its material applied or changed unless its already apart of the active scene.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by odragora** [comment]
Same problem here.
The following does not changes the transparency of the mesh.

![](https://image.prntscr.com/image/LJYIvurET3GBQUALZSeHuw.png)

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
