### ISSUE TITLE
resource inspector search option - [X] button is missleading

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#16394]
**Godot version:**
3.0 stable official

**OS/device including version:**
Windows 7 32 bit

**Issue description:**
[X] Button function is to "clear search box content"
however [X] icon function, is commonly understood as "close something".
so the user is trying to "close search panel" with it. while additionaly missing its true functionality.

**Steps to reproduce:**
![inspector_search_close](https://user-images.githubusercontent.com/3224132/35779665-4e6baaea-09d1-11e8-961f-2fc0c321d393.gif)

**Comment by Noshyaar** [comment]
Click the magnifier to close. The X is for clearing the search box.

**Comment by Zylann** [comment]
I think the X should be visually embedded in the search box to mean its logic is associated with it. All search boxes having this button do that.

**Comment by avril-gh** [comment]
Then maybe icon should be changed from [X] to something more meaningful (a trashcan, broom ? ect)
since [X] is intuitively understood as "close something".

**Comment by avril-gh** [comment]
closing since theres no more [X] button on search option.

**Comment by Zylann** [comment]
Oh, it was just removed? :/

**Comment by Zylann** [comment]
Too bad, I liked the feature.

**Comment by avril-gh** [comment]
aww. im sowy.

**Comment by akien-mga** [comment]
There is, it's contextual:
![screenshot_20180923_121000](https://user-images.githubusercontent.com/4701338/45926854-9ccc5000-bf29-11e8-8ac0-7251f34a2f7c.png)
![screenshot_20180923_121024](https://user-images.githubusercontent.com/4701338/45926857-a786e500-bf29-11e8-8f69-cf21ddd628ba.png)

It's now included in the search bar itself and shown only when there's text to discard, so I think this issue is fixed.
