### ISSUE TITLE
Create an .app bundle automatically when compiling the editor for macOS

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#16415]
As is done with Android and HTML5 export templates already, an .app bundle should be created when building the editor for macOS.

**Comment by ArdaE** [comment]
I've reported a documentation bug related to this. See my comment https://github.com/godotengine/godot/issues/8653#issuecomment-358750258 under #8653 for a solution. In my approach, the .app bundle is not created by the build system as you request, so it may not be exactly what you want, but it provides the steps needed to create the .app bundle and have Xcode perform those steps automatically.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
