### ISSUE TITLE
Add support for Bullet's btMultiBody

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#16426]
Bullet implements a reduced coordinate system solver via its btMultiBody, which is extremely useful for building models of robots, humans, and creatures. Basically, instead of starting with 6 degrees of freedom (DOF) for a joint and trying to stabilize 5 of those to get something like the knee joint, btMultiBody uses a reduced coordinate system that is able to model a knee joint using a single DOF for very accurate simulation without requiring a super small physics time steps. It is very suitable for game development, and critical for a project I am working on. It would open up a whole world of possibilities in Godot, and I'm sure many users would find it useful if it becomes easily accessible from within Godot.

Please see Erwin Coumans' presentation http://box2d.org/files/GDC2014/ErwinCoumans_ExploringMLCPSolversAndFeatherstone.pdf for more information on this.

P.S. @AndreaCatania, do you already have any plans for this?

**Comment by AndreaCatania** [comment]
I already knew it, and I know how to implement in a way that you just need
only a click to activate it. But I still no have plan about it,since I'm
working on IK and softbody, and other stuff. So i can't tell you when I can
do that

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by AndreaCatania** [comment]
@ArdaE Here the PR to introduce this feature: https://github.com/godotengine/godot/pull/28909
