### ISSUE TITLE
Inbuilt mesh primitives missing

### ISSUE THREAD

**Issue by werty37** [godotengine/godot#16427]
**Godot version:**
2.1.4.stable.official from Steam

**OS/device including version:** 
MacOS High Sierra;  MacBook Pro (Retina, 15-inch, Mid 2015); Intel Iris Pro 1536 MB

**Issue description:**
The default mesh primitives such as CapusuleMesh, CubeMesh etc. are not available. 

**Steps to reproduce:**
New Node -> Spatial -> MeshInstance. In the Inspector panel, clicking on the Mesh drop down only provides with "New Mesh" and "Load" as an option. Please see attached screenshot. 

<img width="1552" alt="screen shot 2018-02-06 at 12 44 17 am" src="https://user-images.githubusercontent.com/22869624/35824368-a908640e-0ad8-11e8-8b60-9c6b38f807a4.png">

**Minimal reproduction project:**
I was following the below tutorial on Youtube. 
https://www.youtube.com/watch?v=-D-IcbsdT04&list=PLTZoMpB5Z4aBOtdBUXOeemKdg2fKxgJjm

**Comment by kubecz3k** [comment]
Given feature is new and it had it's release in Godot 3.0. The tutorial was made for Godot 3.0 and you are using old version 2.1.

**Comment by kubecz3k** [comment]
Fresh version of Godot will be released soon on steam: http://steamcommunity.com/games/404790/announcements/detail/1660008672671562928

**Comment by werty37** [comment]
Thanks for the information.

**Comment by kubecz3k** [comment]
For the record, in Godot 2.1 we were using special node instead, it was called TestCube, but I discourage you from using it if you will want to convert your project to 3.0 later, since it's not available in 3.0, and this node will disappear after the 3.0 conversion. If you are just learning and you have no intention to convert this project to 3.0 later, then it might be good idea to use it (or better, download 3.0 from the Godot website :))
