### ISSUE TITLE
KinematicBody move_and_slide on rotating platform will "shift"

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#16450]
**Godot version:**

Godot 3.0 Stable

**OS/device including version:**

Windows 7

**Issue description:**

KinematicBody on a rigidbody in kinematic mode rotated by animation player will somehow move out of the rigidbody

**Steps to reproduce:**

    Create rigidbody in kinematic mode 
    Create KinematicBody 
    Put KinematicBody above rigidbody 
    Rotate the rigibody by y-axis by animation player
    KinematicBody call move_and_slide()
    After a while, KinematicBody will move out of the rigidbody

**Minimal reproduction project:**

[upload.zip](https://github.com/godotengine/godot/files/1699776/upload.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by madmiraal** [comment]
I'm not sure this is an issue (any more).

Aside from the fact that there was a visual artefact (the ball would jump to the right on each rotation and eventually fall off of the side) which does not appear in 3.1.1, everything else appears normal.

In 3.1.1, the ball slowly moves outwards and eventually falls off the edge. This is a side effect of simulating a rotating platform using discrete physics on a computer, and looks normally if we consider centrifugal forces :-).

I've tried increasing the speed of the animation, and although the ball falls off the side, this again is expected because of the initial step change in the angular velocity, which looks normally if we consider the ball's inertia :-). If I increase the width of the platform the ball stays on and, again, eventually falls off the end due to "centrifugal forces".

I've also tried moving the platform from side-to-side (instead of rotating it) and again, aside from jumps during step changes in velocity, the ball stays on the platform even at very high animation speeds.

Unless I'm missing something, I think this issue can be closed.

**Comment by akien-mga** [comment]
Thanks for the in-depth review, let's close it then.

**Comment by nagasawamaki** [comment]
Sorry to ask a question. Although it may be correct in physics simulation, if I am making a 3d platformer, I think I don't expect my character, who is standing on a rotating platform, eventually will be moved to fall off the platform.

Is there any workaround to disable this "centrifugal forces" effect?
