### ISSUE TITLE
[discussion && suggestion] GDNative Requests / push motivation towards it?

### ISSUE THREAD

**Issue by girng** [godotengine/godot#16457]
i was reading some comments by reduz and @willnationsdev about low level features.

i feel like, there are a lot of PRs that could qualify for this

for example, just off the top of my head after browsing the PRs: #14731, #14888, #7989, and others.

i feel like there should be a "GDNative" page in Godot (there is, but there's no functionality to it right now). 

i suggest: maybe instead of people submitting "PRs", they could also submit "GDRs" (GDNative Requests), and it could be added to the GDNative viewer. and a **godot user can install them in 1 click.**

terrible example, but just a rough sketch of what i'm trying to convey:
![capture](https://user-images.githubusercontent.com/36117592/35889654-624d87f0-0b51-11e8-8e1b-de5591bf99f4.PNG)

that is what will show, when the user clicks "Browse GDNative Libraries", the main `GDNative` page will be the same, and just list the installed gdnative libraries, and then have `Uninstall` under status. obviously just a markup page here, official implementation will be different, but just an idea

- it will allow more developers to freely create their own features without abiding to "low level features"
- doesn't have to go through the same reviewal process before getting merged, since it's a feature (not low level), which will save time for other contributors.  
- allows other godot developers to utilize these GDNative libraries ASAP when they get added (instead of waiting for them to get merged). _however, if a gdnative extension did get merged to the core engine later, the user could also just simply uninstall the gdnative extension._

what do you all think?

**Comment by girng** [comment]
this came to fruition to me after reading all the PRs @poke1024 and other godot developers have been doing, and i would like to utilize their features ASAP. and i also feel sad, some of the features they want, just don't coincide to the entire "low level", "core engine" features. this would solve that problem, and give confidence & joy to the godot developer that's contributing, that their code can be used by others. 

since some PRs have 4+ upvotes, and -4 downvotes. it seems some people want it, some people don't. this will solve that as well.

**Comment by willnationsdev** [comment]
I think I'm confused...you seem to basically want a dedicated section for GDNative-based EditorPlugins of some sort?

GDNative allows us to create submodules that can process external code dynamically. So the NativeScript, PluginScript, and ARVR GDNative-based submodules will allow external code to by dynamically processed by Godot, but the engine itself still needs those submodules to be written into the engine as C++ (the contents of the gdnative folder in `/modules/`). That part still HAS to be done by the engine.

I haven't looked at the other PRs yet, but for my stuff, all of it could more or less be done by creating C++ NativeScripts that derive EditorPlugin (or add a PluginScript). These are things that people can do already and don't require any additional work.

**Comment by girng** [comment]
> I think I'm confused...you seem to basically want a dedicated section for GDNative-based EditorPlugins of some sort?

well, not necessary editor plugins. it could be for any PR, i just randomly chose that PR (and it happened to be an editor one lol)

but yeah. for example, if a user wanted to create an inventory class. they can create their own "GDR" GDNative request, and it gets added to the GDNative viewer almost instantly (after review rules set by akien/reduz. thus, all the other developers can just do a 1 click install, and utilize it ASAP. 

i think that will incentivize more developers like yourself william, to create more high level features that don't necessarily fall under "engine core features".

**Comment by willnationsdev** [comment]
Plus, if contributors all started suddenly writing their code only as NativeScript plugins (which would be the only way you could get them "early", before their PR is merged), many wouldn't even work (no low level access), and for the ones that don't need low level access, I don't think it would be a good idea to split up people's development efforts that way in the first place. All of a sudden you'd have tons of optional features at your disposal, but none of them would be in the engine itself. Then they would have to do EXTRA work just to add it to the main engine.

**Comment by girng** [comment]
@willnationsdev i understand where you are coming from. let me clarify: it's not something to replace pull requests that fix core engine/low level features. it's just a way for developers to let their code be used by other godot developers that are still low level and fast (C++), but not necessarily a "low level features" that needs to be merged into the core of the engine.

**Comment by willnationsdev** [comment]
Well, what you are describing is exactly what an EditorPlugin written in C++ NativeScript is. And I agree, they ARE awesome. But they are already a feature we have. You can set them up as an asset in the Asset Library. The "1-click install" is the same one the editor already supports with the AssetLib workflow.

**Comment by girng** [comment]
problem is, asset library is not low level stuff. just all regular gdscript. this will allow low level code (c++, using GDNative) to be utilized as a high level feature without being bound to "core engine functionality" stuff. if that makes sense.

 for example, some of those PRs, you will see they have +4, and -4 votes, and some people think it should be a core engine feature, and some don't

**Comment by willnationsdev** [comment]
Well, that's kinda the point. The Asset Library is not locked to only supporting GDScript. If someone wanted to, they could easily setup a NativeScript plugin written in C++, as you are stating. I suspect that once the Steam GDNative plugin is fully functioning, that it too will be setup as an AssetLib asset, and you'll be able to download and integrate the Steam SDK with 1 click.

**Comment by girng** [comment]
@willnationsdev true. problem is the developers are developing for what they think are low level core functionality, but then when the PR is made, confusion may happen / disagreements. i think this idea will solve that, because now, they can just release it as a GDNative Extension. their time spent making that PR, can still be beneficial to all.

**Comment by willnationsdev** [comment]
> i think this idea will solve that, because that means, they can just release it as a GDNative Request. now, their time spent making that PR, can still be beneficial to all. without having to pass through the "core engine functionality" test, if you will

@girng Ok, it seems to me like your goal is to allow developers to create a single code base that will be usable as an engine integration OR as a plugin, that way devs can target one "format" of C++ code and have it be accessible immediately. The inline colors in TextEdit concept wouldn't work for that (since it modifies an in-engine C++ class), but the websocket and random number generation content COULD be used this way, if people targeted developing them as GDNative plugins in the first place.

Now, in order for it to be something that works for both early-access plugins, and wait-to-be-merged engine integrations, you would need to have some sort of engine-level subsystem that automatically provides access to these NativeScripts along with the engine. There are two ways this could be done.

1. Rather than storing these NativeScripts within your project folder, they would be stored in the engine folder. Somehow, the engine would then allow your project to "see" these NativeScripts (would probably require a new "res://"-like directory that points to the NativeScripts embedded in the engine.

2. Automatically install each of these NativeScripts whenever the user creates a new Godot project folder. So, you might have a dedicated `gdnative` folder (like the `addons` folder), and the NativeScripts would be copy/pasted into this directory upon project creation. Then your project would be able to see these scripts regardless.

There are a few problems with this technique though. There are SUBSTANTIAL benefits that come from a C++ type being an in-engine type. The ClassDB has an awareness of these types and a lot of embedded functionality comes out of the box just from this alone. Scripts, such as NativeScript, just don't have the same kind of native support. In the long run, if something introduces a new type that SHOULD be a module (like the latter two changes you've linked), it is MUCH more preferable for these types to be introduced as modules instead of NativeScript plugins. And if they are to be modules, then people would need to rewrite them later on to be merged in anyways. It would be a waste of their time to even develop the NativeScript version.

Secondly, there is a lot of work that would need to be done to implement the feature No. 1 I suggested, work that people don't wanna do if the vast majority of "new features" wouldn't really benefit from doing it. (In fact, the only cases that would be doable with a NativeScript ARE the cases that would be better off as modules, unless it really is something that shouldn't be in the engine core, and therefore should be something that is a plugin anyway).

Idea No. 2 isn't very good because it adds a ton of project bloat to people's project folders, and things get even worse if they update their engine and then have all sorts of re-writing going on in every single one of their project folders when it updates the built-in NativeScript plugin data.

All in all, while I really like the motivation behind it, this would just be a very bad idea all around in my opinion.

The rule of thumb should be:

1. If it requires low-level features, it should be a module.
2. If it doesn't require low-level features, introduces a new type, and would still be useful to integrate into the engine, then it should STILL be a module because of all the great benefits that come from doing so.
3. If it doesn't require low-level features and doesn't introduce any new types OR if it does introduce a new type, but wouldn't be useful in the engine core, then it should be a plugin.

**Comment by girng** [comment]
@willnationsdev appreciate the response

>@girng Ok, it seems to me like your goal is to allow developers to create a single code base that will be usable as an engine integration OR as a plugin, that way devs can target one "format" of C++ code and have it be accessible immediately. The inline colors in TextEdit concept wouldn't work for that (since it modifies an in-engine C++ class), but the websocket and random number generation content COULD be used this way, if people targeted developing them as GDNative plugins in the first place.

yes, correct. just one caveat, it doesn't necessarily have to be "usable as an engine integration". it could simply be just a separate GDNative extension by itself not bound to be added to the core. **your conclusion of my idea** (sorry, my fault for not explaining it clearly), is more of an evolved system of my idea, which i do agree with you on.

for a real world example, take a look at #16272's votes. some saying it should be a core feature, some saying it shouldn't. if this was done with a GDR (GDNative Request), that PR could be closed, and then now anyone who wants some low level array functionality with multiplication, can now simply install it via the GDNative Viewer.  that's not the best example, but you get the idea :P 

you have taken my suggestion and evolved it  a bit. as i said, my fault for not explaining myself, but i hope that clears up where i'm at.

**Comment by willnationsdev** [comment]
Well, this is partly why what you seek doesn't really seem to exist. GDNative would not be capable of implementing any of the three suggestions in that PR (\* array multiplication, repeat GDScript global, or repeat Array method). Each of these would require direct engine modifications which isn't something that GDNative can do. GDNative-based NativeScripts can only do their OWN thing, separate from what the engine does. It just also has access to the Engine's scripting API externally (can't mess with any of the internals).

As such, the thing that you are actually talking about, a GDNative-based means of making immediate "changes to the engine" with needing to recompile is the definition of what a C++ NativeScript EditorPlugin is. And these already exist as previously mentioned.

Perhaps I can help to clear up the misunderstanding if you would explain what you think a GDNative Request would actually be, on a technical level.

**Comment by willnationsdev** [comment]
To put it another way, a "GDNative Request" would only ever be able to add things, completely new things, to the engine, rather than modifying, in any possible way, how any of the engine code works. NativeScripts can't modify Array, GDScript, how the Editor messes with any of the editor tools, anything. It can create new tools and new nodes, but it can't change existing stuff

**Comment by girng** [comment]
i thought GDNative could modify everything inside the engine to modify any functionality?

**Comment by willnationsdev** [comment]
A NativeScript can only access the scripting API. A GDNative submodule can expose new engine functionality (on a much deeper level) to external C-based code, but that GDNative code still has to be built into the engine. It just enables external stuff (the stuff that can only touch the scripting API) to execute dynamically.

So, for example, NativeScript itself is a submodule, and it enables you to write external code that can see the scripting API, and the NativeScript submodule  CAN change the editor in amazing ways because it is a part of the GDNative codebase. It enables other things interfacing with the C API to do cool stuff (it's the awesome, powerful, bridging entity). But the stuff that users create, the stuff that doesn't require compiling, can't do any of that amazing engine changing stuff.

**Comment by girng** [comment]
i see, that makes sense. thanks for clearing that up. i kept thinking since GDNative is C++ it could be possible to modify core functionality. that's part of the equation on how this suggestion came to fruition. because i was thinking, let's just add a GDNative Viewer for certain PRs for low level core functionality changes, since some users disagree with the feature. could make everyone happy / be a solution.

**Comment by willnationsdev** [comment]
@girng No problem. Happy to have cleared things up.

**Comment by girng** [comment]
@willnationsdev in any event. it does rub me the wrong way that poke and other developers submit PRs that offer nice, low level functionality changes, but are not usable by Godot devs. (unless, re-compiling from source, etc, etc) -- i still think in a perfect world, i'd like to see developers install PRs with 1 click. but that's beyond the scope of this suggestion (but does hover around it a bit)

**Comment by willnationsdev** [comment]
Well, what you would like is something that can provide to you engine changes (which here you label as "extensions") that can be dynamically added to an existing binary. On a technical level however, this is impossible. At most, a binary can only offer hooks which other binary code could then slip into. On a purely software programming level, what you describing isn't feasible.

The only way to do what you are asking is if the code we're already in a form in which it was developed and executed using the same language (so compiling for different platforms wouldn't be necessary). If developers were writing binary machine code directly, then they would be able to swap out engine level changes dynamically like that. But because they have to be compiled from C++ into object code, and then from object code to machine code, one collection of machine code won't know how to interact with another piece of machine code except through whatever holes to poke through are available in each box of software (the "hooks"). A scripting API is what these hooks are, and Godot enables GDScript to interact with these hooks. GDNative permits other C code to interact with the hooks as well. But ultimately, the two software can only interact either by being built from the ground up together, or by interacting through the hooks.

**Comment by willnationsdev** [comment]
But yes, this would be the perfect world. And it would be doable, if every C++ program compiled the same way, among all compilers, among all operating systems, into the exact same machine code. I think that would do it...

**Comment by akien-mga** [comment]
That's not possible. A PR and a GDNative module are completely different things and require very different code, so you can't ask people making PRs to also prepare a GDNative variant of their PR, with precompiled binaries for all platforms, some of which they likely can't compile themselves.

I see where you're coming from but there's no fast-forward track from PRs to the end user, and there's a good reason for that. If a PR is not merged yet, it might never be, and you should not be using it in your project as you can't be sure it will be merged. If it's not, you will have based your game on a never-released state of Godot, and you'll basically have to maintain your own fork to keep using it.

Usually PRs are merged quite fast, it's only been since December 2017 that we've started being a lot more conservative with what gets merged to get 3.0 stabilized. Now that 3.0 is out, and after a few days to recover, we'll start reviewing and merging/refusing PRs again.

**Comment by girng** [comment]
@akien-mga thank you, yeah it was my misunderstanding of what i thought GDNative could do. and @willnationsdev explained it very well, which basically rendered my suggestion kinda of pointless.  i was thinking gdnative could modify every single c++ / core engine feature. 

i was just trying to find middle ground between some PRs that core developers don't want, but some contributors do. a fully extendable GDNative in a perfect world (where it modifies any c++ core game engine feature) could do that but that's not w hat GDNative is, i learned the hard way ^^

**Comment by willnationsdev** [comment]
Yup. The only way to modify core functionality is to...ya know...change core. XD
