### ISSUE TITLE
Ideas for multidevice 2D/3D navigation and impoved consistency

### ISSUE THREAD

**Issue by lmjk** [godotengine/godot#16453]
Navigation in 2D and 3D editors is currently difficult/strange with restricted input devices such as some touchpads. There are optional settings options to make working with touchpad possible, but at least for me, it took quite long to accidentally learn about the existence of such (not until I searched the issues related to this one today). Also, navigation in 2D is different to most 2D-space applications (#7409), such as many image editors, web browsers, etc.: in Godot you can't pan around with vertical and horizontal scroll.

Another, although possibly not that major, inconsistency is within Godot itself. Constantly switching between 2D and 3D, when you work on a project that needs both, may confuse your nervous system and you end up orbiting all the time in 3D instead of panning. Some useful functionality of 3D is also missing from 2D (at least continuous zoom by ctrl + middle mouse button). Navigation in 2D and 3D editors should be similar where they overlap (pan, zoom), if possible. Of course, this may break Godot's navigation compatibility with either Blender (and others?) or 2D software so there is a need for configuration options, as always. Following the current 3D navigation scheme similar to Blender's however possibly breaks consistency also between traditional pointer touchpads and multitouch touchpads/screens, because the latter do not send scroll events (I don't know, just guessing), if you want to fully utilize these modern devices.

So:
- You should be able to move around with any (common) device combinations by default. No extra configuration should be needed. These device combinations include partially also the case _keyboard only_, because some things are faster/more accurate to do by pressing keys than by first reaching to the mouse or aiming at a distinct value with it.
- Differences between 2D and 3D navigation should be minimal.
- Differences to standard navigation approaches in other related software should be minimal.

And the last two are in contradiction... 

Below are my two different proposals for defaults. A is optimized for 2D compatibility and B for the current 3D. The 2D + 3D columns list actions that can be shared between both 2D and 3D. 

![navigation1](https://user-images.githubusercontent.com/25223253/35866589-4a61fe50-0b60-11e8-8273-5ea4e28dbf49.png)
![navigation2](https://user-images.githubusercontent.com/25223253/35866592-4abbfe14-0b60-11e8-9776-078819800a5b.png)
![navigation3](https://user-images.githubusercontent.com/25223253/35866594-4b1e0e4c-0b60-11e8-9c2a-132998f65b63.png)

You can find there some "new" functionality, too: Forward/backward movement in 3D editor that is accessible only in fly mode now, and keyboard shortcuts for zoom 1:1, and double/halve the current zoom level (those small "+ 1 -" buttons at the upper left corner in current 2D editor). Shortcut `1` (number row) for 1:1 zoom can be found in image manipulation and viewer programs. And finally something that is missing from Godot altogether (AFAIK): zoom to rectangle in both 2D and 3D orthogonal view. The proposed Shift + middle mouse button is used in Inkscape for this.

Keyboard-only mappings for orbiting and forward/backward movement are missing from the table, but they should not. At the moment, the arrow keys are used in 2D editor to move the selected object 1 pixel to the given direction, and with Shift modifier 10 pixels. To enable panning, this functionality could be moved behind modifier keys completely (thus eliminating usage of _modified_ arrows in navigation context and the most intuitive option for keyboard orbiting and forward movement), or one could have a totally different approach to manipulation tools, eg. following #15969.

**Correction:** The column Zoom to rectangle in the first B table should be empty, because Shift + m.mouse is reserved for panning.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
