### ISSUE TITLE
Making it easier to drag & drop resources to properties

### ISSUE THREAD

**Issue by Neicul** [godotengine/godot#16464]
**Godot version:**
3.0

**Enhancement description:**
We currently have the option to drag a resource onto a compatible property in the node inspector to assign the ressource easily.

While that is already a welcome enhancement, it could be made even better:
When dragging the ressource over the inspector, the editor could determine if there are even any compatible properties.
If there is only one, assign it to that one.
If there are multiple compatible ones, open a small popup-window to select the wanted property.

This is really just to make assignment faster and easier. That way, you wouldn't always have to hunt down a specific property and drop the resource on it.
Also, when the property is hidden because the category is collapsed, you have to drop your ressource, open the category, drag and drop your ressource on the property again.
This would completely negate the issue.

EDIT: Another implementation: On Drag start, temporarily collapse all categories but the ones which contain compatible properties, so you have a less cluttered Inspector. On Drop, reset the Inspector view to before the drag.

**Comment by eon-s** [comment]
I like the second idea, to temporarily collapse sections, simple and no automatic decisions or popups.

**Comment by toger5** [comment]
I also really like the temp collaps idea!

Still could have issues when there are too many slots (for example for a meterail with tons of texture slots) but than you have to think about where you want to put the property anyways.

**Comment by UnwarySage** [comment]
I also second the second idea.

**Comment by KoBeWi** [comment]
I prefer the first idea (I was just going to suggest similar thing, but found this one). The pop-up idea is nice, but it could be useful to allow skipping it. My initial idea was to just set "default property" for each resource, but since you might want to quickly assign it somewhere else, maybe make it so holding e.g. CTRL will override the pop-up and put the resource in the first available slot.

In any case, it's better to drop directly into tree, because you can assign something without selecting node. If anything, just allow both options. Also with second option, if the node is selected, filter to show only compatible properties (that way you don't need to scroll expanded lists).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
