### ISSUE TITLE
Inheriting from custom C#-Script is not working in the editor

### ISSUE THREAD

**Issue by Moghedien** [godotengine/godot#16500]
**Godot version:**
Godot 3.0

**OS/device including version:**
Windows 7

**Issue description:**
It is not possible to add a new C#-Script to a Node, that inherits from a custom C#-Script.
_(works fine with gdScript)_

**Steps to reproduce:**
1. Create a new C#-Script
2. Create a scene and add a node
3. Add a new C#-Script to that node that inherits from the script you have created in step one

**Screenshot 1 (C#-Script, not working):**
![screenshot](https://user-images.githubusercontent.com/5713036/35992798-9c8efdde-0d0b-11e8-9680-26d36a02964c.jpg)

**Screenshot 2 (gdScript, working):**
![screenshot2](https://user-images.githubusercontent.com/5713036/35992940-1447365c-0d0c-11e8-9404-10f7d0569a5f.jpg)

**Comment by akien-mga** [comment]
CC @neikeq

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

cc @neikeq

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
