### ISSUE TITLE
GI probe ignores light sources in a scene if nested under a non root node

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16534]
**Godot version:**
`master` / 68f277477b5a5f3003405e36c6b6853720cb91de

**OS/device including version:**
_Manjaro Linux 17.1.1_

**Issue description:**
When GI probe is placed in a deep hierarchy, it ignores other light sources (i.e. directional or omni lights) added to the scene but only calculate indirect light from the environment (i.e. sky).

I'm not sure if it was an intended behavior. But in this case, I suppose we better add an warning to the documentation, because it's not obvious why it is failing to work as expected.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
