### ISSUE TITLE
Auto-complete popup is not big enough

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16542]
Godot 3.0

When getting nodes from a form, I ended up with paths too long for the auto-completion box:

![image](https://user-images.githubusercontent.com/1311555/36065344-c47f6d94-0e99-11e8-9fbc-1e4e30bda87f.png)

Maybe it should expand if paths are too big?

**Comment by bfloch** [comment]
Or it could be smarter with paths like this vim (plugin):
![vim_autocomplete](https://user-images.githubusercontent.com/2116566/36086341-be15dbae-0f99-11e8-87c4-f83460afe35f.gif)

**Comment by hubbyist** [comment]
I had a similar issue #4704 it can be closed if this one is fixed.

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by profan** [comment]
So, with a crude change in https://github.com/godotengine/godot/blob/005b69cf6e276209464cc8c36ebc7376679925b6/scene/resources/default_theme/default_theme.cpp#L485

We can instead get something like this (max width set to 128, not exposed in any settings though):
![image](https://user-images.githubusercontent.com/2816340/41315604-4bc1433a-6e90-11e8-8abb-457ec1ad097a.png)

and when the window is squashed, it shows like this
![image](https://user-images.githubusercontent.com/2816340/41315637-5f828898-6e90-11e8-83ac-6106f6cdd4b6.png)

This small change might be of interest regardless because it doesn't seem to break in face of less-wide windows, but maybe it would be nice to have a smaller max width (60-80?) and maybe just show the beginning + end as suggested, or only the end bits as much as possible?

**Comment by profan** [comment]
Another case where I edited this bit:
https://github.com/godotengine/godot/blob/e9492308379dfc26cd8223ceeaa4c41f98426b56/scene/gui/text_edit.cpp#L1257

To basically just straight up use the actual size it calculates instead of clamp it to a max size, shown here with an absurdly deep hierarchy:
![image](https://user-images.githubusercontent.com/2816340/41316339-60f07288-6e92-11e8-8841-779af7bc77f1.png)

**Comment by AlexHolly** [comment]
I think adding a `h_scroll_bar` to the window is best solution.
I made a version with an ItemList and added h_scoll to it. 
Before I spend more time on it I would like to know what you think.

![peek 2018-08-13 22-26](https://user-images.githubusercontent.com/4741886/44056415-76d93e9a-9f48-11e8-855b-0bd9280a58b4.gif)

**Comment by hubbyist** [comment]
@AlexHolly Is h_scroll_bar responding to left and right arrows as well? Then it seems to be fixing #4707 as well IMO.

**Comment by AlexHolly** [comment]
@hubbyist I dont see any relation to #4707 maybe there is a typo? Currently h_scroll_bar will not move to left/right with arrow keys in #21181

**Comment by hubbyist** [comment]
Issue is #4704 fixed previous post.

**Comment by hubbyist** [comment]
But if mouse is necessary for this to work also shortening with `...` as place holder is necessary so than both end of a node path can be identified while browsing autocomplete list.

**Comment by profan** [comment]
So I kind of just left this and forgot about it, but I did have a version working that showed both ends of the node path and had "..." in the middle, as that seemed the most useful path to go, maybe an option added to ProjectSettings to set the max length of the autocomplete popup could be nice as well so we can have a reasonable default length but then people can configure it if they want something specific. (this is as well as the ... thing, but maybe I can make the second part another PR)

**Comment by Calinou** [comment]
@profan Bump :slightly_smiling_face: Could you make a pull request with your changes? If you don't have time to do this, could you commit something to your fork and link it here so someone else can continue?

**Comment by profan** [comment]
@Calinou Absolutely, sorry I left this for a while in the midst of other things, I'll take a look at it again in a few days 👍 (and PR what I'd done)

**Comment by TheSofox** [comment]
Seems like this has been fixed:

![image](https://github.com/godotengine/godot/assets/3089525/a4e7f508-841c-4bce-b2d8-6498e9d4bda3)
![image](https://github.com/godotengine/godot/assets/3089525/a1149b7c-42ef-4962-9b53-3cc344d4d561)

**Comment by Calinou** [comment]
It doesn't get as wide in 3.5.2: ![image](https://github.com/godotengine/godot/assets/180032/2c439c73-b818-4f4a-84fe-23b7dae90d76)

That said, since this was implemented in 4.0, I'll close this.
