### ISSUE TITLE
No Way to Check if Animation Playing Backwards

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#16550]
I need to be able to check if an animation of mine is playing backwards in an AnimationPlayer, but there is currently no way to check this.

**Comment by LikeLakers2** [comment]
I think the issue here is that `animation_speed` might not be updating at all. Since `play_backwards` is the same as putting `-1` in the playback speed parameter in `play`, I tried that. Neither `play_backwards` nor `play` with `-1` playback speed set `animation_speed`. Only setting the variable itself actually changes the variable.

```
# Plays it backwards properly, but does not set the animation_speed variable
$AnimationPlayer.play("anim", -1, -1)

# Plays it backwards properly, but does not set the animation_speed variable
$AnimationPlayer.play_backwards("anim")

# Plays it backwards properly and sets the animation_speed variable
$AnimationPlayer.play("anim")
$AnimationPlayer.playback_speed = -1
```

**Comment by QbieShay** [comment]
From what @LikeLakers2  said, i think this should be labeled as bug @Noshyaar

**Comment by robfram** [comment]
After working in this issue, I think it is not a bug but a lack of features.

The `AnimationPlayer.playback_speed` property is the global speed scale for the whole `AnimationPlayer`. Calling `play_backwards` is a wrap for calling `play` with `p_custom_scale=-1`. The `play` method sets a custom speed scale for the animation being played, but doesn't modify the global speed scale.

So, when you change the `playback_speed`, you are affecting all theirs animations when playing. But when you call the method `play` with different speeds, you are changing the speed for that one, which will be also modified by the speed scale property. The final movement speed is `global playback_speed * animation custom scale`.

The problem arises because you don't have a way to check what is the custom scale of the current animation being played, as you only can access to the global speed scale of the `AnimationPlayer`.

My PR will add a new method, `get_playing_speed`, to return the final speed of the animation being played (`global speed scale * animation scale`) or `0` if there is no playing at all.

I don't know if anyone has a better way to approach this issue.
