### ISSUE TITLE
Create script is in a weird position in the UI

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#16559]
**Godot version:** 3.0

**Issue description:** Create script, for more logical consistency, should be in the Node inspector panel. I know it is possible in the inspector (at the bottom), but scrolling all the way down is annoying and the button on top hints to something that is more scene-specific rather than node-specific.

![image](https://user-images.githubusercontent.com/7917475/36073191-9aeda7f0-0f2c-11e8-90a9-57b0a95cd151.png)

**Comment by Noshyaar** [comment]
I'm against this for these reasons:
 - Inspector is also for things that aren't nodes (Resources, core types etc.) and adding script to those has little gain, while Scene Dock is about Nodes only.
 - New Script button attaches script to the currently selected Node in the Scene Dock. It doesn't create free script. Free script can be created using Inspector "New Resource" button (or Script Editor). Moving this button there would imply (for me at least) that it creates free script.

IMO, this button is more closely related to Scene Dock than Inspector. (Btw, I never use that button, I right-click the node and attach script from the context menu.)

**Comment by QbieShay** [comment]
In my opinion it would be better because

1.  Scene dock is about Nodes only, yes, but treats them in "group", while inspector is dedicated to a single Node, so it makes more sense to me that when you create a script you create it for a single Node.
2. Free scripts should be created from the Script tab File>New. Creating them from a specialized scene is counter-intuitive, because you are working on a scene/node.

**Comment by karroffel** [comment]
The Inspector works for all kinds of Objects, not only Nodes. 

This is where this proposal is actually good - scripts get attached to *Objects*, not Nodes. Nodes happen to be Objects, but yet a "proper" UI is only available for Nodes. So I think this proposal is actually good since it discriminates less against non-Node types.

**Comment by groud** [comment]
> scripts get attached to Objects, not Nodes

What are scripts attached to Object useful for ? If it is possible but never used, I would keep the UI as it is for now.

**Comment by karroffel** [comment]
When I work with NativeScript I attach scripts to `Resource`s **all** the time. Granted, I do that by using `NativeScript::_new()` and let that handle that, but every once in a while I do attach scripts to stuff in the property editor because it's not a Node.

**Comment by groud** [comment]
Are you using them to make game or work on the editor ? ^^
I'm not against it, but for now the UI seems more appropriate as most of the time scripts are attached to nodes. I believe there should be a real use case before changing that, as it should not worse the workflow for the sake of consistency.

**Comment by QbieShay** [comment]
Groud, while it might be obvious for an experienced Godot user, I still find it counter intuitive. The scene dock is there to manipulate the nodes between one another, organize them and sometimes multiple editing of properties. Since you can't instance a script on his own in the scene but you need to attach it to one node, I think it's more logically consistent if it is in the inspector. When I say logical consistency, I am talking about "where I expect it to be as a user", not something theoretical :)

**Comment by groud** [comment]
Well, on the other hand, by now the button to access a node's script is on the node panel (on the same line as the node). Having to go down the inspector to add a script is as unintuitive as having it on the top of the tree window.
If we move the "add script" button down to the inspector, we should also provide a way to open it, and to signify in an obvious manner that a resource/a node has a script attached to it. And as it is quite useful there, we should not remove the open script button in the node tree.

**Comment by QbieShay** [comment]
I don't think so, because the script edit button on the node in the scene dock server also as an overview of which nodes are specialized and which nodes are regular nodes. Editing the script from that button makes the interaction straighforward, while i don't think that the add script on top makes the interaction straightfoward. i might want to specialize the root node (which is generally the case when you make a scene, at least for me) and have another node selected. In that case, the editor would create the script for a different node than the one i wanted. If it is moved to the inspector is clear that it is referred to that particular node

**Comment by Calinou** [comment]
Note: Judging by the conversation above, there doesn't seem to be much support for this proposal. It may have to be rethought before you can open a new proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
