### ISSUE TITLE
AssetLib design/layout proposal

### ISSUE THREAD

**Issue by Nohac** [godotengine/godot#16665]
Even though the current AssetLib is functional and usable, it felt like the layout and general usability could use a bit more work, so a made a quick mockup as a suggestion. Any feedback and improvements are welcome.
![design](https://i.imgur.com/ie5YYOg.png)

**Comment by Calinou** [comment]
I'm not sure if GitHub can be quiered for the number of stars directly, as [the API is rate-limited to 60 requests by hour if not authenticated](https://developer.github.com/v3/#rate-limiting).

**Comment by vnen** [comment]
Also, does the other providers (GitLab, BitBucket) have stars too?

**Comment by akien-mga** [comment]
This looks great, thanks for the proposal!

> I'm not sure if GitHub can be queried for the number of stargazers directly, as the API is rate-limited to 60 requests per hour when unauthenticated.

We could query it every 20 minutes or so from the server and cache the results, and let the in-editor assetlib query our cached results.

> Also, does the other providers (GitLab, BitBucket) have stars too?

GitLab does: https://gitlab.com/osslugaru/lugaru
Not Bitbucket, but maybe "Watchers" could be used instead: https://bitbucket.org/heldercorreia/speedcrunch - or the option could be disabled for such assets

**Comment by noh4ck** [comment]
Lot's of good points about the github stars, I probably didn't think that through. The main reason I included it in stead of the 5 star system that's currently in place, is because I've personally never seen a useful and actively used 5 stars rating system before. 

I think people uses stars on github as an indication of how useful/popular a repository is, and as a way to bookmark the repo to check out later. I don't think most people would take the time to properly review assets and give them a meaningful star rating.

**Comment by bojidar-bg** [comment]
We might count downloads as well.

I'm not sure about using repository stars, because GitHub repositories are going to get a disproportionately higher amount of stars compared to GitLab repositories.

But yeah, dropping the 5-stars rating system is currently unimplemented, so dropping it wouldn't be a problem.

**Comment by Geequlim** [comment]
How about integrate the webview like the CEF as a GUI Control for the editor. Then the AssetLib can be made with modern web UI.

**Comment by Calinou** [comment]
> How about integrate the webview like the CEF as a GUI Control for the editor. Then the AssetLib can be made with modern web UI.

That's not going to happen, the CEF is way too large to be embedded into Godot. Moreover, a WebView will never provide an user experience as good as a native GUI can.

**Comment by menip** [comment]
Do we have a way to "Favorite" things right now? Would be welcome as polish

**Comment by Calinou** [comment]
@menip Support for marking assets as "favorites" is being tracked in #5229.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
