### ISSUE TITLE
Possible inconsistency between layer_names and bits?

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#16688]
**Godot version:** 3

The collision_layer of PhysicsBody2D  and other such layers work by toggling bits, starting with bit 0. This may be inconsistent with the layer_names that start with Layer 1, as defined in this code:
`GLOBAL_DEF("layer_names/2d_render/layer_" + itos(i + 1), "");`

Would it make more sense to have the layer names start from 0 so that the editor shows the same bit position used by functions like set_collision_layer_bit()?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
