### ISSUE TITLE
Custom scene thumbnails

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#16682]
This is a featurw request.

It would be great if there woukd be the optumion to add a coustom png as a scene thumbnail (right now it always uses the generated one which look are grey in a lot of cases)

This is mostly a feature for addons. They could than use coustom icons for the scenea/nodes that are meant to be used by the addon-user with a more meaningful thumbnail.

This thumbnail than alos could be used in the scene tree so that it kind of douvles as a coustom node icon.

**Comment by groud** [comment]
I would first improve the scene thumbnail generation for now, as it is really bad.

**Comment by toger5** [comment]
In which way do you want to inproove them?
Render quality of the image or smarter perspective so it looks less ... Empty?

**Comment by groud** [comment]
So that they look less empty and similar to each other.

**Comment by expat1999** [comment]
What if scene thumbnails could, say, ignore the lighting of the scene?  That way you could actually see the color of the objects without having to place down a light.  Any settings related to this could fall under the View drop-down menu in the viewport.

**Comment by KoBeWi** [comment]
The problem with scene thumbnails is that they aren't generated from actual view, but rendered at some viewport point, which isn't always accurate. It would be nice if they just "screenshotted" the current view.

**Comment by dreamsComeTrue** [comment]
Well, maybe we should allow user to create his own thumbnail, like in UE, by clicking on it with some modifier (like Shift + Alt for example) and drag around inside its boundaries - moving/panning/rotating virtual camera that way to choose the best shot.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
