### ISSUE TITLE
Instancing a Node with Unique/Unlinked resources

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#16680]
**Godot version:**
Any

**OS/device including version:**
Any

**Issue description:**
Whether you duplicate or instance an object its resources are always linked back to the original node/scene. This means that technically you never really  get a 100% unique object. This is a problem because if you wanted to tweak the object at run-time you basically have to hack together something every time to further duplicate/unlink the resources, which doesn't always work either at that. Having 

**Steps to reproduce:**
Having the ability to create a complete copy and not just a half referenced clone really is a must have feature. I can't think of a reason why you won't want this functionality.  maybe an extra parameter in the "instance" method to specify a complete copy?

**Minimal reproduction project:**
There might be another similar thread but not sure about it.

**Comment by LinuxUserGD** [comment]
Take a look at
https://github.com/HugeGameArtGD/Solus-Stunts/blob/95b4beaad498732e57d4ea231731e0b18fed78d7/source/car/car.gd
It's possible to create a new ressource (e. g. Spatial Material) and assign values to it. This ressource is unique and can be applied to the object.

**Comment by vnen** [comment]
Looks the same as #1213.

**Comment by vonflyhighace2** [comment]
That thread seem to talk about duplicating an existing node in the tree. I on the other hand want a 100% on-tethered copy of an instanced/packedScene. Different context I suppose.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
