### ISSUE TITLE
Add a command line flag to trigger Mono project build

### ISSUE THREAD

**Issue by xfactor2000** [godotengine/godot#16720]
**Godot version:**
Godot 3.0.mono.official

Hi,
please add a command line option to rebuild Godot Mono project before running it. Right now, when I make code changes in VSCode/other external IDE, and run Godot through a hotkey to test, I don't see changes because Godot runs the pre-compiled files. I need to manually press "Play" in Godot editor and only then it will compile the sources.

Thanks.

**Comment by NathanWarden** [comment]
I haven't dived into editor scripts quite yet, but it might be possible if my PR is accepted to call "call_build" on an editor node. It may need a script binding first? Also, I'm not quite sure if it's possible to add a key-binding from a script, but I'd like to know :)

If that's true it would be super easy to implement.

**Comment by NathanWarden** [comment]
One confusing thing is that your title and feature request seem to be different from each other. Do you just want:

1. a command line option to recompile when you first open Godot, which is what a command line flag would do, or
1. do you want something where you can recompile your code with a hotkey?

I already have a PR if you mean to compile when it first opens: https://github.com/godotengine/godot/pull/16098

If you mean the second (to recompile whenever with a hotkey) I don't think a command line option is the solution, but maybe an editor option that will auto-recompile whenever a change is made to a *.cs file, kind of like how Unity does it.

Another idea, if it isn't already available, would be to be able to have an editor script that gets notified whenever *any* file within your project changes, kind of like how Unity's `OnPostprocessAllAssets` works, in which we could be able to call `call_build` from EditorNode as I mentioned before.

https://docs.unity3d.com/ScriptReference/AssetPostprocessor.OnPostprocessAllAssets.html

**Comment by neikeq** [comment]
If the editor already built and copied the API assemblies to your project, then running `msbuild <ProjectSolutionPath> /p:Configuration=Tools` will be enough. The solution path is optional if the working directory is the same as the solution.

**Comment by xfactor2000** [comment]
Hi, I meant the first option, and your solution seems fine. Should I close
my request?

**Comment by xfactor2000** [comment]
> If the editor already built and copied the API assemblies to your project, then running msbuild <ProjectSolutionPath> /p:Configuration=Tools will be enough. The solution path is optional if the working directory is the same as the solution.

Thanks for the tip, but it's rather a workaround than solution.

**Comment by Dieselpirat** [comment]
+1

My workaround is even worse, I've been using Auto HotKey to Alt+Tab, F5. I hope there will be a proper solution soon.

**Comment by xfactor2000** [comment]
You can use vscode automatic build task  to compile solution using  msbuild
and then running godot. See how to compile with msbuild in previous
comments.

**Comment by Dieselpirat** [comment]
@xfactor2000 
I've tried that before and it's complaining about 
`(CoreCompile target) ->
  C:\Program Files\Mono\lib\mono\msbuild\15.0\bin\Roslyn\Microsoft.CSharp.Core.targets(84,5): error MSB6004: The s
pecified task executable location "\\csc.exe" is invalid. [PathToCSProjFile]`

I had two warnings too, which were fixed by putting the GodotSharp.* and GodotSharpEditor.* files into the \Program Files\Mono\lib\mono\msbuild\15.0\bin\ folder, which feels a little dodgy though. But the csc.exe issue still persists. 
Running from within godot works fine, that's why I chose to use AHK for now. Tampering with Windows 10 has been horrible so far 🤢

**Comment by Dieselpirat** [comment]
I've tried that and it's giving me an error about "csc.exe" path is invalid. I've just noticed that hgouveia posted a tasks.json in #16327 to manually trigger a rebuild: 
https://gist.github.com/hgouveia/134f4007e9ed65aafad76e5808f7f543

**Comment by xfactor2000** [comment]
Can't help with that, sorry, on Linux it works fine.

**Comment by Dieselpirat** [comment]
@xfactor2000 Nevermind, thank you anyway! I've edited my post, probably while you where typing. I think the csc.exe thing is due to a missing value in the windows environment variables, but I'm over it for now^^ It sucks being dependant on an OS like this, but hgouveia forwarded a solution, which works perfectly for me.

**Comment by NathanWarden** [comment]
@xfactor2000 If this was the solution to your problem it has now been merged and you could close this :)

https://github.com/godotengine/godot/pull/16098

**Comment by xfactor2000** [comment]
Thanks, Nathan, will do :)

**Comment by xfactor2000** [comment]
#16098
