### ISSUE TITLE
FileSystem Dock: Add filters

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot#16741]
**Godot version:**
3.0

**Issue description:**

FileSystem Dock: Add filters

In current implementation all files ordered by names. If number of files significantly increase then the file dock become cluttered. Please add some filters in to Header of file dock:
Sort by Name
Sort by Type
Sort by Date Created

**Comment by vnen** [comment]
FYI you can attach an image directly into the issue, no need to put in an external link.

**Comment by JFonS** [comment]
I can work on that. I already managed to sort files by type and date, but I'm not sure how the UI should look like. Any insight @groud?

**Comment by BBric** [comment]
And a way to ignore some files/folders.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
