### ISSUE TITLE
No way to easily place collision segments across a line

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#16765]
Godot 3.0 stable

I didn't find a way to place collision segments easily along a line.

Stupid example:
![image](https://user-images.githubusercontent.com/1311555/36336653-1569de84-138a-11e8-9054-acc7850cf0a7.png)

The `CollisionPolygon2D` has a Segments mode, but it still wants to be closed.
There is a `Segment` collision shape but placing many of them along a line is a PITA compared to the workflow offered by `CollisionPolygon2D`.

**Comment by eon-s** [comment]
Segment is for segment based shapes (not filled, and many bugs), polygons are closed by definition.

Something like Line2D to make segment-based collision shapes could be nice, and can be used to make solids based polygon shapes too if a width is taken into account (sharing Line2D properties can make a good couple for level prototyping).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
