### ISSUE TITLE
Collisions exception with a group

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#1678]
It could be nice to do collision exception with a group. 
add_collision_exception_with_group()

Thanks.

**Comment by n-pigeon** [comment]
:+1:

**Comment by eska014** [comment]
Is guess this is about collision filtering in 3D? Collision layers and masks are planned to be ported from 2D to 3D for release 2.0 (See #1759).

Some words on this since this just came up in IRC (and #2738):
I don't think collision exceptions by group make a lot of sense.
To have different kinds of objects collide (or not collide), collision layers and masks should be used. Since they're bitflags, they're quite efficient. They will be implemented in 3D as stated above.
Exceptions are more useful for stopping something from colliding with itself, for example when using raycasts from within a CollisionObject.

**Comment by akien-mga** [comment]
Since there are now collision layers and masks for both 2D and 3D objects, I think this issue is no longer relevant.
