### ISSUE TITLE
Right-clicking the script or visibility icons in the editor's scene tree will erroneously give them a "selected" appearance

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#16786]
**Godot version:** Git https://github.com/godotengine/godot/commit/2d0c07bd5ab363997a210f98fb14d638414dea1a

**OS/device including version:** Fedora 27

**Issue description:** Right-clicking the script or visibility icons in the editor's scene tree will erroneously give them a "selected" appearance. This is a purely cosmetic issue; the "selected" appearance disappears if one left-clicks anywhere else in the scene tree panel. See below for screenshots.

**Normal selection:**

![node_selection_normal](https://user-images.githubusercontent.com/180032/36346093-f260282c-1437-11e8-8a61-7c93685751a0.png)

**"Fake" selection of the script button (with an unselected node):**

![node_selection_fake_1](https://user-images.githubusercontent.com/180032/36346091-f22a7a38-1437-11e8-947e-ccce55df2277.png)

**"Fake" selection of the script button (with a selected node):**

![node_selection_fake_2](https://user-images.githubusercontent.com/180032/36346092-f245987c-1437-11e8-851c-98a511f3efd5.png)

**Steps to reproduce:** Right-click a script or visibility icon in the editor's scene tree.

**Comment by Alexander-Alekseev** [comment]
Also reproducible with 9f590b460ee8f6e0026b14fbc336b7b7ad977ee0 on Windows 10 x64.

As I think the reason is that there is no difference between LBM and RMB _in general_ (only specific logic for Left/Right click later):
https://github.com/godotengine/godot/blob/d5eba83fd57005c110ef594f90c84016b758a0d5/scene/gui/tree.cpp#L2566-L2568

Then there is a `propagate_mouse_event` call:
https://github.com/godotengine/godot/blob/d5eba83fd57005c110ef594f90c84016b758a0d5/scene/gui/tree.cpp#L2607

, which 'selects' script/visibility icon.
https://github.com/godotengine/godot/blob/d5eba83fd57005c110ef594f90c84016b758a0d5/scene/gui/tree.cpp#L1707-L1714

Don't know what to do next yet.

**Comment by Calinou** [comment]
I can still reproduce this issue in Godot 3.2.1.

**Comment by tianer2820** [comment]
Still exists in Godot 3.4 stable.

**Comment by KoBeWi** [comment]
No longer exists in 4.3.
