### ISSUE TITLE
Syntax highlighting should differ between class variables and local variables

### ISSUE THREAD

**Issue by gamesoil** [godotengine/godot#16799]
**Godot version:**
 3.0

**OS/device including version:**
Issue is platform agnostic

**Issue description:**
Both class member variables and local function variables use the "Text Color" syntax color value (and not the "Member Variable Color"?).

Distinguishing these colors, even in relatively small scripts, can be helpful. For comparison, see:

GDScript:
<img width="329" alt="GDScript variable colors" src="https://user-images.githubusercontent.com/36570332/36355314-1f04c85c-1496-11e8-881e-aeff3061e900.png">

IntelliJ (Java):
<img width="329" alt="IntelliJ variable colors" src="https://user-images.githubusercontent.com/36570332/36355371-0ff545de-1497-11e8-8f33-759a07acf031.png">

**Steps to reproduce:**
Just create a script with class fields and local fields in it, e.g.

```
extends Node2D

const CONST_VAR = 10
var class_var = 0

func _ready():
	var local_var = CONST_VAR
	class_var += local_var
```

Expected: `CONST_VAR` and `class_var` should use member variable highlighting, while `local_var` should use text color highlighting.

**Minimal reproduction project:**
Not included, as issue is trivial to reproduce.

**Comment by gamesoil** [comment]
Opening an issue to see if the team agrees with the issue as written, before I spent too much work digging into it.

I've also tried to take a look at the code to see if this would be trivial or not, but I'm still learning and can't tell. It might be tricky if the syntax coloring phase happens before we know whether a variable is a class variable or local variable.

Also, what is the "member variable color" for, if not currently used for member variables?

**Comment by Zylann** [comment]
@gamesoil it's probably for this syntax:
```gdscript
obj.member_var
```

**Comment by gamesoil** [comment]
Ah, thanks, you're right. If I type `self.class_var`, it's colored correctly.

I still think it would be nice if it was possible to color other class variables the same way. Especially I noticed when I was going through sample code, it was hard at a glance to know which functions were part of the function and which were part of the class.

For example, glancing at code like this (extracted from the Instancing 2D sample):

```
if ...:
   jumping = false
if ...:
   jumping = true

prev_jump_pressed = jump
```

is `jumping` local? Is `jump` local? Is `prev_jump_pressed` local? It's not the hardest thing to figure out, but you have to scroll around the file to find out, which results in losing focus for a few moments to answer what should be a simple question.

It could also help identify if someone accidentally shadowed a class variable with a local variable:

```
var should_jump = false

func _physics_process(delta):
   ...
   var should_jump = false // Whoops! Someone added without realizing the collision
   ...
   should_jump = true // Potentially subtle bug...
```

My suspicion is we don't know this information at coloring time, however.

**Comment by KoBeWi** [comment]
Related (duplicate?) to #8080

**Comment by ZodmanPerth** [comment]
I see value in coloring variable names at different scopes in different colours/shades.  However my biggest issue presently is distinguishing `const` from mutable variables.

I would dearly love if the names of `const` variables were a different colour.

**Comment by Calinou** [comment]
@ZodmanPerth The [convention](http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_styleguide.html) is to use `UPPER_SNAKE_CASE` for constants, so they're distinguished by their casing.

Personally, I'd value distinguishing local and member variables over distinguishing mutable and immutable variables (even if we do add actual immutable variables in the future). Having both is probably not a good idea, we don't want to use too many syntax highlighting colors to preserve visual consistency.

**Comment by KoBeWi** [comment]
> we don't want to use too many syntax highlighting colors to preserve visual consistency.

It wouldn't probably hurt to have them as an option, with defaults having same colors in some cases.

**Comment by ZodmanPerth** [comment]
Conventions are personal and shouldn't be enforced (or required) by the framework.  Coming from a C# background I use different conventions for casing than someone from Python (for example).

`const` symbols are special, and deserve their own highlight colour.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by yatesm4** [comment]
Since no one wrote a proposal for this it seems, I've gone ahead and submitted one - in case anyone ever revisits this thread.

https://github.com/godotengine/godot-proposals/issues/6428
