### ISSUE TITLE
Particle2D Node Frame Property

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#16811]
Suppose you want to create a particle 2d node that works for multiple textures.

For example, say you have two smoke machines, one smoke machine spews brown smoke and the other spews out white smoke (let's say they're just different textures). Both smoke machines have the exact same behaviour and are only one frame on the texture.

It'd be nice to be able to use the same texture but just change the "frame" like I would in Sprite. I get that there's already an Animation property panel in the ParticleMaterial resource, but unless I make that unique on an instanced Scene, I can't change its properties.

At the same time, I want to "inherit" in the rest of the ParticleMaterial properties, but just change one thing.

I tried using a TextureAtlas, but that doesn't seem to work, and I read [here](https://github.com/godotengine/godot/issues/15194) (referenced from [here](https://github.com/godotengine/godot/issues/13923)) that that's the intended functionality.

The only other solution I guess would be to have a whole separate texture for the brown and white smoke. But it'd be nice to have all particles in one texture to conserve memory and optimize rendering.

**Comment by Ranoller** [comment]
I am satisfied with the response of reduz in the topics you reference respect to light2D, but I still consider a bug the problem in Particles2D ... The texture shows the region, and region should be showed in canvas. If is not intended, there are two options:  Eliminate option to select region, or incorporate to particles system (like godot2). Nobody tagged my issue like a bug, but is a bug without any kind of doubt.

**Comment by Lucrecious** [comment]
@Ranoller What was his response?

What's the solution to wanting to use one particle behaviour for multiple textures on the same atlas? Or is it just using different textures?

I'm not completely sure what reduz was suggesting in respect to Light2D.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
