### ISSUE TITLE
Ability to change the rest position of PinJoint2D

### ISSUE THREAD

**Issue by viiragon** [godotengine/godot#16818]
**Godot Version:** 3.0 official

**Feature Proposal**
An ability to change the rest position of a PinJoint (I mean a relative position between node A and B, that the joint tries to achieve, that is set up when it's created) after it's been created and attached.

I think it would be really convenient when creating and using complex structures that are composed of it (*Like I do~*)

**Comment by raffomania** [comment]
I just came here from a long search through docs, tutorials and FAQs. There should definitely be a hint in the docs that this is not currently possible.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
