### ISSUE TITLE
Render to texture functionality on demand

### ISSUE THREAD

**Issue by gtsiam** [godotengine/godot#16828]
I am trying to implement a ping pong texture (a texture that is sent to the gpu, goes through a shader, and again, and again, and so on).

I know it is possible to do by setting up multiple Viewports and ViewportTextures, but it is a bit wasteful. if you want to do a few of those per frame.

So maybe it would be a good idea to have viewports that can render on demand. Compute shaders would be nice, but I assume it is a bit too much to implement.

I am willing to work on this myself, ~~but I would like a few pointers, since I am not too sure where the rendering happens in the engine~~ (or to know if there is an obvious alternative method I missed).

EDIT: Actually, I just remembered [this](https://godotengine.org/article/godot-3-renderer-design-explained) post, so I can probably do without the pointers...

**Comment by Zylann** [comment]
I kind of miss this, everytime I have to use shaders for texture generation. It is very inconvenient to setup a bunch of viewports and have them working in order to execute a series of steps, sometimes with multiple iterations, and even worse if you need to have that output fed into further passes.

My current use case is terrain generation: I want to support erosion in my editor, but this requires to run a directional blur shader a lot of times on the same image, and the more I tweak my generator, the more I think I'll need a node-based system which however feels very cumbersome to setup with the current viewports, because unlike the typical shader editor which only has to generate one shader to one output, it would need to plug outputs of different shaders to the inputs of others...

**Comment by Calinou** [comment]
> So maybe it would be a good idea to have viewports that can render on demand. Compute shaders would be nice, but I assume it is a bit too much to implement.

Godot 4.0 makes use of compute shaders and will likely expose a compute shader API of some sort.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
