### ISSUE TITLE
Input map action reordering

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#16833]
**Godot version:**
3.0 Stable

**OS/device including version:**
Windows 10

**Issue description:**
It would be nice to be able to reorder the input map actions. As the actions get more complex, being able to drag and drop the order of them to keep them neatly organized would help to make sure that you aren't missing any actions.

**Steps to reproduce:**
Open the Project Settings and click on the Input Map tab. There is no way to reorder the input actions.

**Comment by justinluk** [comment]
Ooh thanks @Dumbeldor! Looking forward to seeing what you've done.

**Comment by ludorverr** [comment]
+1

At the moment you are constantly forced to scroll past all this junk every time in order to see your game's controls which are more important.

![input map](https://user-images.githubusercontent.com/15337628/54400888-201c7080-4719-11e9-9fe2-3e687a3e314b.png)

@Dumbeldor may be too busy to work on this

**Comment by Dumbeldor** [comment]
Yeah, for now i'm too busy :(
But i want to finish my PR :P

**Comment by girng** [comment]
eh, i rarely spend that much time in the Input Map tab. you can just add your action at the top, the only time you really need to scroll down is if you need to edit a action. of which you do so very rarely already.   i have never felt "constantly forced to scroll past" down to the bottom..
