### ISSUE TITLE
GDScript "in"-operator inconsistency with "null" custom properties

### ISSUE THREAD

**Issue by ILoveGodot** [godotengine/godot#16849]
**Godot version:** Godot 3.0

**Issue description:**
The GDScript "in"-operator returns false if it tries to access custom properties that have a value of null by using an overridden "_get()" function. Maybe it should look up the variable by using "_get_property_list()" instead?

Related issue: #16729

From the docs:

>void _get ( String property ) virtual
>Returns the given property. Returns null if the property does not exist.

Just because the property value is null doesn't mean that the property doesn't exist.

**Steps to reproduce:**
- Add the script to a node:
```gdscript
extends Node

func _ready():
	var a = A.new()
	
	print('b' in a) #True
	print('c' in a) #False, should be true
	print('d' in a) #True

class A:
	var b = null
	var e = { c = null, d = 123 }
	
	func _get(property):
		print('Getter') #Only called if it's not a class member
		return e[property]
	
	func _get_property_list():
		print('Get property list') #Never called
		
		return [
			{
				'name': 'c',
				'class_name': '',
				'hint': PROPERTY_HINT_NONE,
				'hint_string': '',
				'type': TYPE_NIL,
				'usage': PROPERTY_USAGE_SCRIPT_VARIABLE
			},
			{
				'name': 'd',
				'class_name': '',
				'hint': PROPERTY_HINT_NONE,
				'hint_string': '',
				'type': TYPE_NIL,
				'usage': PROPERTY_USAGE_SCRIPT_VARIABLE
			}
		]
```

GDScript solution:
```gdscript
static func has_property(instance, property):
	for element in instance.get_property_list():
		if element.name == property && element.usage & (PROPERTY_USAGE_STORAGE | PROPERTY_USAGE_SCRIPT_VARIABLE):
			return true

	return false
```

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by dreadpon** [comment]
Still the case in Godot 3.5.2
From the docs it appears that it's not a bug, but fully intentional. I strongly disagree with this decision.

This weirds me the hell out, because "not having a property" and "property is null" are two very distinct things in my mind.
But current implementation does not allow a property to be stored in a dictionary and exposed via `_get_property_list()` and `_get()` and have a value of null.

This completely prevents the use of dot syntax `object.property` if `property == null` (and throws an unfixable error `Invalid get index 'property' (on base: 'Node (object.gd)').

**Comment by alexmunoz502** [comment]
This is also still the case in 4.0.2

> This weirds me the hell out, because "not having a property" and "property is null" are two very distinct things in my mind.
But current implementation does not allow a property to be stored in a dictionary and exposed via _get_property_list() and _get() and have a value of null.

@dreadpon  I completely agree.

I overrode `_get_property_list()` to include my custom property with a null value, and even though it shows up in the property list when I `print(get_property_list()`, trying to access the property still results in an error.

**Comment by dreadpon** [comment]
> I overrode `_get_property_list()` to include my custom property with a null value, and even though it shows up in the property list when I `print(get_property_list()`, trying to access the property still results in an error.

Yup, that's exactly how I learned about this problem myself in 3.5.2
