### ISSUE TITLE
KinematicBody2D get's stuck when sliding up a ramp while touching a one-way collision body

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#16892]
**Godot version:**
08fbe0d

**Issue description:**
This will probably explain it much better:
![peek 2018-02-21 11-55](https://user-images.githubusercontent.com/30739239/36486848-4d15d9f6-16fe-11e8-94ca-94fb5eacb9a5.gif)

**Comment by eon-s** [comment]
Have you set the angle limit and slope minimum velocity? Are you sure is not wall when get stuck?

Can you add an example project to test this properly?

**Comment by YeldhamDev** [comment]
@eon-s It's not that. Even with very plane slopes this happens:
![peek 2018-02-21 22-12](https://user-images.githubusercontent.com/30739239/36514787-fc4eb2d4-1754-11e8-82fb-f54311873e19.gif)
Here is the code for the character, with the parts not related to movement stripped away:
```
extends KinematicBody2D

const GRAVITY = 2800
const FLOOR_NORMAL = Vector2(0, -1)

const SPEED_RUN_MAX = 350
const SPEED_RUN_STEP = 0.15
const SPEED_GRAVITY_MAX = 2500

var _speed_current = Vector2()
var _speed_remaining
var _speed_previous

var _direction

func _physics_process(delta):
	_direction = 0
	if Input.is_action_pressed("player_run_left"):
		_direction -= 1
	if Input.is_action_pressed("player_run_right"):
		_direction += 1
	
	_speed_current.x = lerp(_speed_current.x, SPEED_RUN_MAX * _direction,
			SPEED_RUN_STEP)
	if _speed_current.y < SPEED_GRAVITY_MAX:
		_speed_current.y += GRAVITY * delta
	
	_speed_remaining = move_and_slide(_speed_current, FLOOR_NORMAL)
	_speed_current.y = _speed_remaining.y
	if not is_on_floor():
		_speed_current.x = _speed_remaining.x
```

**Comment by eon-s** [comment]
I have made a sample project, reduced the high gravity and simplified the code to reduce places for where to look for the problem.

The issue is noticed more the smaller is the safe margin value, with safe margin high the body moves well against the one side collision, it seems to be related to the lack of an equivalent to the "max depth" option that was present on Godot 2, there may be other issues related to this one.

[kinematicmasoneside.zip](https://github.com/godotengine/godot/files/1746348/kinematicmasoneside.zip)

**Comment by Calinou** [comment]
@YeldhamDev Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by YeldhamDev** [comment]
@Calinou Nope! Not able to reproduce it on the latest beta.
