### ISSUE TITLE
File get_var() / eof_reached() problem

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#16919]
**Godot version:**

Godot 3 - Godot 2.1

**OS/device including version:**

Win 7 32 y 64 bit

**Issue description:**

What happened:

If I try to iterate in a file with **file.get_var()** until **eof_reached()** is true, no matters i put this condition up or down to **get_var()**... **eof_reached()** always is triggered after get_var is trying to get an non existinting var and returns **ERR_INVALID_DATA**.

The behavior that i expect is **eof_reached()** going "true" in the same moment that the last var was reached and getted, not in the moment that get_var() is trying to get the "total_numbers_of_var"+1, because the "LEN < 4" error is unskippable (and eof_reached becomes useless with get_var())

(I know other ways of parse the file without use eof_reached(), this issue is not asking for help to do that, is to report a behavior that i think is wrong  and to know if behavior is expected)

**Steps to reproduce:**
Iterate a file getting all vars until eof_reached() is true (not do "for" loop or similar and don´t filter with any comparison, only get all vars until eof_reached() is true with while or similar), eof reached allways becomes true after get_var returns: decode_variant: Condition `len < 4`is true. returned: ERR_INVALID_DATA.

**Minimal reproduction project:**

**Comment by bruvzg** [comment]
EOF checks in filesystem drivers are inconsistent, [Unix driver](https://github.com/godotengine/godot/blob/master/drivers/unix/file_access_unix.cpp) check for EOF only after buffer read and failed seek, [Windows driver](https://github.com/godotengine/godot/blob/master/drivers/windows/file_access_windows.cpp) on every `eof_reached()` call. [Buffered](https://github.com/godotengine/godot/blob/master/core/io/file_access_buffered.cpp#L92) and [Memory](https://github.com/godotengine/godot/blob/master/core/io/file_access_memory.cpp#L138)  file access probably should use `>=` instead of `>`.

EOF is insufficient condition to break the loop, in construct like `while !eof_reached():` file handle may become invalid before reaching EOF and cause infinite loop.

**Comment by Ranoller** [comment]
Another way is catch the error and compare... but after this commit #11388 you can not check if get_var() == ERR_INVALID_DATA  (And get_var() shows in "print" that var catched in LEN < 4 is "null", like probably others in the file), so without knowing previously the number of vars in file i don´t find a system to iterate to the end of file with the security of cached var´s are existing var´s, and not existing var´s +-1...  I think that this should be at least rethinked.

**Comment by Ranoller** [comment]
if get_var() could return a string "ERR_INVALID_DATA" to script system the first time that fails, you can test typeof var and if string compare to that, and have the security that at least you don´t have more variables that the file has (If there is minus... well, that´s other history)

**Comment by char0xff** [comment]
So what's a workaround for this bug if I don't know the size of the file?

**Comment by char0xff** [comment]
Ok, after the first read of the loop I did:
`	if file.eof_reached():`
`		break`

**Comment by avencherus** [comment]
Yep having this issue in 962c142 Win10 64bit.

Seems like end of file isn't known until it attempts erroneously.

![image](https://user-images.githubusercontent.com/13004169/52912320-7df39f00-32b8-11e9-8146-cc1bc9a01972.png)

```gdscript
extends Node2D

func _ready():
	
	
	var data = { a = 100, b = 200, c = "300" }
	var arr = [data, data, data]
	
	var f = File.new()
	f.open("res://test.txt", File.WRITE)
	
	for i in range(3):
		f.store_var(arr)
		
	f.close()
	
	f.open("res://test.txt", File.READ)
	

	while(not f.eof_reached()):
		print(f.get_var())
		print(f.get_error() == ERR_FILE_EOF)
		
	f.close()
```

Example Project: 
[3.1 Get Var Issue.zip](https://github.com/godotengine/godot/files/2872897/3.1.Get.Var.Issue.zip)

**Comment by reduz** [comment]
@Ranoller 
> The behavior that i expect is **eof_reached()** going "true" in the same moment that the last var was reached and getted, not in the moment that get_var() is trying to get the "total_numbers_of_var"+1, because the "LEN < 4" error is unskippable (and eof_reached becomes useless with get_var())

Me too, but this is how it works in every operating system at the low level, so nothing can be done about this. Libraries wrapped to Godot so they can use Godot filesystem API all also expect it to work with way (minizip, ogg, etc).

@bruvzg 
> [Buffered](https://github.com/godotengine/godot/blob/master/core/io/file_access_buffered.cpp#L92) and [Memory](https://github.com/godotengine/godot/blob/master/core/io/file_access_memory.cpp#L138) file access probably should use `>=` instead of `>`.

The use of `>` is correct. It would break otherwise.

This should be documented though, as I don't see it in the reference, so changing this issue to documentation.

**Comment by reduz** [comment]
@avencherus and @char0xff You can request position and size of the file via the File API, so if you want to implement the logic yourself for checking if at the end, it should work fine.

**Comment by avencherus** [comment]
@reduz I see, good to know, thanks for clarifying.  I think I inferred it to be the intention from seeing code examples like: https://docs.godotengine.org/en/latest/tutorials/io/saving_games.html
