### ISSUE TITLE
AnimationTreePlayer gets duplicated when inheriting a scene

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16938]
**Godot version:**
`master` / 6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When creating an inherited scene from a parent with an `AnimationTreePlayer`, all the contained nodes are duplicated into the child scene which causes the following error per each node:

```
ERROR: add_node: Condition ' node_map.has(p_node) ' is true.
   At: scene/animation/animation_tree_player.cpp:920.
```

**Comment by mysticfall** [comment]
I got the error while I was manually bisecting commits between 14 Feb and 19 Feb which means building and installing (via Arch Linux package) different revisions between that timeframe.

I used the same project to test the build and I found that sometimes installing different build causes a scene with `AnimationTreePlayer` threw such an error.

When I removed and recreated it again manually, the errors disappeared. But when I kept testing with different revision, the errors again show up, and after that I can reproduce it evertime I run the scene.

**Comment by mysticfall** [comment]
Found a more accurate cause of the issue, so I edited the description with the updated information.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
