### ISSUE TITLE
Add move to next/previous keyframe in animation view

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16940]
**Godot version:**
`master` / 6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** (This issue is a feature request)

When working with animations, sometimes you need to add a key to a track at the exact position where other keys from different tracks exist.

We already have move to next/previous frame feature, but it simply moves between quantized positions so it's not very useful when intervals between the keys are not in neat values like 0.1.

What could be a more useful feature in such scenarios would be 'move to next/previous keyframe' featuure, which moves the playback cursor to the adjacent point where the closes keys from other tracks exist.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
