### ISSUE TITLE
Prepass or a separate Render Texture in Shaders.

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#16953]
It's more of a question on my part, I am not an expert in Shader Programming and relatively new to Godot but how do we do the Prepass and RenderTexture Stuff in Shaders in Godot.

I am looking for features similar to Unity, probably it will be nice someone also tells me how to get screen and display from Cameras that aren't set to _current_. That's what I have most experience with.

And I did try BackBufferCopy but it only works over things rendered before it(I learned this when I tried playing with Z-Index), and is likely nothing more than a way to resolve multiple shader conflicts. So any help.?

Hope I was clear enough.

**EDIT:**

### My feature request:

1. Ability to create Render Textures and Use them to create various effects.
2. Ability to use multiple cameras to render different layers of the scene.
3. Ability to take input from multiple cameras even if not set to current using some function. Or just make them similar to BackBufferCopy but with ability to choose the layers to render, just no necessity to display anything.

**Comment by mhilbrunner** [comment]
Maybe try asking in #godotengine-dev on Freenode IRC. 

Also, cc @reduz

**Comment by Calinou** [comment]
PS: Can't this be achieved with Viewport and ViewportTexture?

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
