### ISSUE TITLE
Add new node at the viewport center in animation tree player view

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16968]
**Godot version:**
`master` / 6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
Currently, when you add a new node in the animation tree player it is added near the top left part of the area, regardless of the scrollbar position.

This behavior is problematic, since as the tree grows it becomes increasingly more cumbersome to scroll back to the top left position to find the new node and drag it all the way back to the where you were working at the moment.

To improve the situation, it'd be better if we add newly created nodes at the center position of the current viewport (currently visible part of the area when it is scrolled) instead.

(I know `AnimationTreePlayer` will be rewritten soon, so I reported this issue simply as a reminder rather than as a request to fix the current version as it is.)

**Comment by vnen** [comment]
The ATP is long due for a rewrite. Not sure when it'll happen though, unless someone in the community decides to step up and do it.

**Comment by mysticfall** [comment]
@vnen I heard it would happen "very soon" (#16965) :smile:

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
