### ISSUE TITLE
Allow setting value of Mix/Blend* nodes in AnimationTreePlayer by typying

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#16965]
**Godot version:**
`master` / 6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
Currently, input values of `Mix`, `Blend2`, `Blend3`, or `Blend4` nodes in the animation tree player view can only be changed by moving a slider.

As there's no way of knowing what current value is or specifying numbers directly, it is almost impossible to set such values to an exact number. And in such situations like when you blend looping animations, any deviation from the neutral position might result in the character's twitching, so you have to reset those values from code manually to avoid it.

To improve the situation, we might add an input field for each of such nodes besides the existing sliders, so that we can both see and change input values as exact numbers.

**Comment by reduz** [comment]
Will rewrite this very soon, will hopefully be possible.

On Feb 23, 2018 21:50, "Xavier Cho" <notifications@github.com> wrote:

*Godot version:*
master / 6e200b1
<https://github.com/godotengine/godot/commit/6e200b1fe0b03bc0acc6d7ab097750d87aa7ac67>

*OS/device including version:*
*Manjaro Linux 17.1*

*Issue description:*
Currently, input values of Mix, Blend2, Blend3, or Blend4 nodes in the
animation tree player view can only be changed by moving a slider.

As there's no way of knowing what current value is or specifying numbers
directly, it can be very almost impossible to set such values to an exact
number. And in such situations like when you blend looping animations, any
deviation from the neutral position might result in the character's
twitching, so you have to reset those values from code manually to avoid it.

To improve the situation, we might add an input field for each of such
nodes besides the existing sliders, so that we can both see and change
input values as exact numbers.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/16965>, or mute the thread

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
