### ISSUE TITLE
Feature Suggestion for Node AnimatedSprite: "Edit each frame's position"

### ISSUE THREAD

**Issue by alexbosquin** [godotengine/godot#16985]
In a lot of cases whe need to move the sprite on a frame, because the sequence is not correctly positioned on the image, like the following :

![test](https://user-images.githubusercontent.com/8551379/36633710-e933b822-1978-11e8-9a11-7c383e20a059.gif)

If the user could change each frame's position would be a lot easier

**Comment by girng** [comment]
if the sequence is not correctly positioned, that's a prop with the individual frames, or spritesheet my man.

however, if you need pixel perfect positionings, you will need to do a regular animation and just keyframe them in manually with the position

**Comment by alexbosquin** [comment]
Yes, you quoted the two ways to solve the problem, and I know that, but i had this idea just for hand on wheels :)

**Comment by RabbitB** [comment]
I see this suggestion as a quality of life improvement for animators. It should also be brought up, that allowing positional adjustment of frames, would allow for better sprite-sheet packing for animations just like this example, where there's a lot of movement baked into the sprite itself. Instead of having all that empty space, the sprite-sheet could be compacted and each individual frame adjusted to where it needs to be.

**Comment by girng** [comment]
If someone is editing frames in an AnimatedSprite for positional changes, they might as well just as an AnimationPlayer with keyframed sprites

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/665, as feature proposals are now tracked on the Godot proposals repository.
