### ISSUE TITLE
Is it possible to use Camel case for all the languages as well as to keep the snakecase?

### ISSUE THREAD

**Issue by Raj2032** [godotengine/godot#16998]
Camel case speeds work up as there is less typing involved and other programmers prefer camel case over snake case. I am not proposing to replace snake case with camel case but instead I am suggesting to _also_ have built in functions that are camel case which does exactly the same thing as snake case.

**Comment by mysticfall** [comment]
I have to disagree on this one. In any programming language, having a consistent naming convention is very important, especially for such a big framework/platform type project like Godot.

In order to keep the codebase maintainable, and to promote users to follow the best practice without getting confused, I believe we should provide them a single consistently named API per each language as we do currently.

**Comment by akien-mga** [comment]
> Camel case speeds work up as there is less typing involved

I always love this argument. How many lines of code do you type each day? Is that big enough that reducing the number of keystrokes would matter, especially when everyone uses autocompletion? Would we have released 3.0 faster if Godot's source code was written in camelCase? ;)

BTW, it's not less keystrokes. Pressing <kbd>Shift</kbd> to make an uppercase letter is one keystroke, just like pressing <kbd>_</kbd>.

More seriously, as @mysticfall said, what's important is consistency. It would be terrible to have twice the documentation and twice the results in the autocompletion because some want camelCase at all costs. And it would end up with very confusing mixes of styles in same scripts.
We already have the situation with GDScript vs C#, but it's not too bad as they're different languages with different coding guidelines. But mixing it in the same language is a very bad idea.

**Comment by sudoio** [comment]
Well, technically speaking, to enter `_` you use **two** keystrokes: **<kbd>Shift</kbd> + <kbd>-</kbd>**, so camelCase still uses less keystrokes :)

Case | Keystrokes
---|---
`caseMatters` | <kbd>c</kbd><kbd>a</kbd><kbd>s</kbd><kbd>e</kbd> **[<kbd>Shift</kbd>+<kbd>m</kbd>] (`M`)** <kbd>a</kbd><kbd>t</kbd><kbd>t</kbd><kbd>e</kbd><kbd>r</kbd><kbd>s</kbd>
`case_matters` | <kbd>c</kbd><kbd>a</kbd><kbd>s</kbd><kbd>e</kbd> **[<kbd>Shift</kbd>+<kbd>-</kbd>] (`_`)** <kbd>m</kbd><kbd>a</kbd><kbd>t</kbd><kbd>t</kbd><kbd>e</kbd><kbd>r</kbd><kbd>s</kbd>

**Comment by akien-mga** [comment]
Not on my AZERTY keyboard :)
