### ISSUE TITLE
Add support for DirectInput Force Feedback

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#17002]
**Godot version:**
All 3.0 branches (stable/master)

**OS/device including version:**
Windows

**Issue description:**
Godot lacks DirectInput Force Feedback support, it uses only XInput for Force Feedback, allowing only XBox Gamepads to be supported for vibration and old gamepads discarded.

Files involved:

https://github.com/godotengine/godot/blob/master/platform/windows/joypad.h
https://github.com/godotengine/godot/blob/master/platform/windows/joypad.cpp

Functions involved:

```
void joypad_vibration_start_xinput(int p_device, float p_weak_magnitude, float p_strong_magnitude, float p_duration, uint64_t p_timestamp);
void joypad_vibration_stop_xinput(int p_device, uint64_t p_timestamp);
```

Please, add support for DirectInput vibration (Force Feedback) to keep old joysticks vibration system work.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
