### ISSUE TITLE
Change the default folder that plugins are found in for consistency

### ISSUE THREAD

**Issue by justinluk** [godotengine/godot#17007]
**Godot version:**
3.0 Stable

**OS/device including version:**
Windows 10

**Issue description:**
Currently, plugins are found inside of the 'addons' folder. This is inconsistent with the name of the tab 'Plugins' in project settings menu. It would be great to rename one or the other in order to keep things consistent. Even better would be to be able to define a custom location for where plugins are found.

**Steps to reproduce:**
Try to add plugins into any other folder than 'addons' and they won't be found.

**Comment by vnen** [comment]
Related #4279

**Comment by Calinou** [comment]
Note: We consider that not all add-ons are plugins, so the current name is most likely fine as it is. (This is because we recommend containing third-party resources into an `addons/` folder, even if they're not editor plugins.)

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Shadowblitz16** [comment]
@Calinou Please reopen this, my main issue is this...

I am using C# and C# requires that files names are the same as class names...
but then my scripts start with a capital letter and my folder's don't...
unless I capitalize my folder's first letter but then plugin's folder name is hard coded.
