### ISSUE TITLE
Add dithering effect to prevent color banding

### ISSUE THREAD

**Issue by zappedfish** [godotengine/godot#17006]
More about banding here: http://loopit.dk/banding_in_games.pdf

Unity includes dithering effect in it's post-processing stack by default: https://docs.unity3d.com/Manual/PostProcessing-Dithering.html

**Comment by jahd2602** [comment]
Is there any workaround for this right now? Like changing to sRGB? I suffering from this problem when using gradients or vertex colors in Polygon2D. I am trying all settings and nothing fixes it.
![captura de tela 2018-04-19 as 14 56 04](https://user-images.githubusercontent.com/2841740/39009428-fa586d44-43e1-11e8-8722-ace035b24e6d.png)

**Comment by DynasoulStudio** [comment]
![image](https://user-images.githubusercontent.com/12684381/44983757-526a3b80-af48-11e8-9e24-739e67c6aaab.png)

**Comment by zappedfish** [comment]
Extremely sorry for bumping, but maybe this could be milestoned for 4.0? 😉

**Comment by jahd2602** [comment]
Or even better: could this be milestoned for 3.2? 😀

**Comment by Calinou** [comment]
@jahd2602 The renderer is unlikely to go to hrough changes until 4.0, so I doubt it.

**Comment by Firepal** [comment]
...please

**Comment by Calinou** [comment]
@Firepal Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by Calinou** [comment]
By the way, it should already be feasible to use a debanding shader in Godot. 
Create a ColorRect node that spans the whole viewport by setting its Layout mode to **Full Rect**, then add a shader to the ColorRect node with the following contents:

```glslshader_type canvas_item;

const float QUARTER_COLOR = 0.0009765625; // 1.0 / 1024.0

void fragment() {
	COLOR = textureLod(SCREEN_TEXTURE, SCREEN_UV, 0.0);
	vec4 col = COLOR;

	// Increase/decrease the pixel colour values slightly in a 
	// chessboard pattern to achieve a simple dithering against banding.
	// Assume 8-bit RGB values and offset values a bit to affect rounding.
	if (mod(FRAGCOORD.x + FRAGCOORD.y, 2) == 1.0) {
		COLOR.rgb += vec3(QUARTER_COLOR);
	} else {
		COLOR.rgb -= vec3(QUARTER_COLOR);
	}
}```

(This is a crude debanding shader, there are better shaders for doing this out there.)

**Comment by Zireael07** [comment]
Full screen shader is a nice trick, but it causes anything using transparency/alpha to effectively disappear...

**Comment by Calinou** [comment]
@Zireael07 I'm working on adding a built-in debanding option to Viewport in the `master` branch so this won't be an issue. Hopefully we can include a more advanced algorithm as well.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by bluenote10** [comment]
@Calinou I see that you have already made great progress on the attached PR. Is it still necessary to move that to the proposal issue tracker, or is this basically done?

**Comment by Calinou** [comment]
@bluenote10 I don't think there's much point in creating a proposal for this feature by now.
