### ISSUE TITLE
Editor lock vs Scene lock indication

### ISSUE THREAD

**Issue by colludium** [godotengine/godot#17017]
**Godot version:**
Godot_v3.0-stable_win64

**OS/device including version:**
Windows 10

**Issue description:**
Small beans, but it's an inconsistency in how buttons are presented.  The node locked indication at the top of the editor window shows you what you're going to win when you press the padlock button (it does not show you the locked status of what you have selected in the scene panel).  The icon in the scene panel is displayed only if a node is locked.....  Click on a locked icon in the scene panel and you unlock your node; click on a locked icon above the editor window and you lock the node.  These appear to use the same icon to cause exactly opposing commands.

**Steps to reproduce:**
Create a node and lock it.  View both buttons in scene panel and editor window.

**Minimal reproduction project:**
Not required.

**Suggestion**
Just have the same display philosophy for both buttons.  My preference would be "this is what you've got" for both.  The mouse-over popup info could change to something like "toggle locked status".

This really is triv, and the rest of the editor is outstanding!!

**Comment by groud** [comment]
I think this has already been discussed somewhere. 
I believe we should organize a vote for that, I'm personally ok with the current implementation but if other people are not comfortable with it we can change it.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
