### ISSUE TITLE
Memory leak in [platform/android/export/export.cpp:1523]

### ISSUE THREAD

**Issue by gangfan** [godotengine/godot#17030]
**Godot version:**

79a225ac2a2f2353f2f626809b56229397dfe52d

**OS/device including version:**

**Issue description:**

We find a memory leak defect in the file  tools/winebuild/po.c.
I've uploaded a screenshot of the leak trace.

Gang
Sourcebrella

**Steps to reproduce:**
![screenshot from 2018-02-26 16 41 38](https://user-images.githubusercontent.com/1679432/36660726-2342d344-1b14-11e8-819c-93d2a8d73077.png)
![screenshot from 2018-02-26 16 42 05](https://user-images.githubusercontent.com/1679432/36660728-25cd0d00-1b14-11e8-82cc-c003ca7c957a.png)
![screenshot from 2018-02-26 16 42 16](https://user-images.githubusercontent.com/1679432/36660730-281b2ccc-1b14-11e8-97c4-19ce1f395330.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
We've had many contributors go over Godot's codebase to fix memory leaks, so I'll assume this one has been fixed since this issue was opened in Feburary 2018. Thanks for reporting this leak :slightly_smiling_face: 

If you can find other leaks in the current Godot `master` branch, feel free to create new issues.
