### ISSUE TITLE
Filter to export non-resource files should accept full file names instead of always requiring wildcard selectors

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#17053]
**Godot version:**

3..0.1

**OS/device including version:**

Windows 10

**Issue description:**

While exporting the game, there's a filter to list the non-resource files that you still want to get packed along with the game resources. However, this field only accepts wildcards entries. I think it would be great if it also accepted individual full names. Say I want to export `error_list.txt`.

This works.
![image](https://user-images.githubusercontent.com/33685433/36687624-20275e2c-1b65-11e8-86ac-80c929f1e898.png)

This doesn't work.
![image](https://user-images.githubusercontent.com/33685433/36687555-f6167bb8-1b64-11e8-9bb5-5cb9da3ef918.png)

This also doesn't work but it would be nice if it did just for those edge-cases.
![image](https://user-images.githubusercontent.com/33685433/36688286-e79df730-1b66-11e8-9f40-0f442fe830c5.png)

It's generally just a small QoL improvement over the currently implemented one.

**Comment by aaronfranke** [comment]
There doesn't appear to be a way to filter for folders or paths either, this doesn't work:

![1](https://user-images.githubusercontent.com/1646875/52923821-a18a0a00-32f7-11e9-850d-dc41ac66fddc.png)

**Comment by neikeq** [comment]
Does prefixing the folder with res:// work?

**Comment by aaronfranke** [comment]
@neikeq Yes, it does. `res://Assets/*` works, this fixed some of the issues I was having with exports.

**Comment by Ranoller** [comment]
This filter works bad.
.json files are always exported, no mathers if are in this filter
.txt files are included if are in the filter
other personal extensions (EJ: .ajson, .tjson) never exports, no mathers if are in the filter.
This should be fixed for 3.2.... 

Related (buggy, not fully accomplished) https://github.com/godotengine/godot/issues/9860

**Comment by kone9** [comment]
I am testing this problem in Godot 3.2 stable and in linux mint 19.02 it does not export the folder separately, in my case I want to use a .txt file from the application but it does not export the file.txt

![Captura de pantalla_2020-02-05_17-51-39](https://user-images.githubusercontent.com/12847027/73882033-2db27b80-4840-11ea-8188-05d46130c4b9.png)
![Captura de pantalla_2020-02-05_17-52-00](https://user-images.githubusercontent.com/12847027/73882089-3b680100-4840-11ea-9af5-e923a3954144.png)
![Captura de pantalla_2020-02-05_17-52-38](https://user-images.githubusercontent.com/12847027/73882139-50dd2b00-4840-11ea-8adb-f95906b06f95.png)

If I export the project by choosing only the scenes and since I am using a .txt file for reading reading to test directly, the program closes
![Captura de pantalla_2020-02-05_17-54-06](https://user-images.githubusercontent.com/12847027/73882284-8bdf5e80-4840-11ea-8b37-a8ea97f1745c.png)
![Captura de pantalla_2020-02-05_17-55-17](https://user-images.githubusercontent.com/12847027/73882369-af0a0e00-4840-11ea-9130-ac5c70a0fbb2.png)

Console
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
``ariel@ariel:~$ '/home/ariel/Escritorio/exportado yousef/index.x86_64'
Godot Engine v3.2.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce 9800 GT/PCIe/SSE2
 
ERROR: load_interactive: Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
   At: scene/resources/resource_format_text.cpp:1228.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: SceneTree: Default Environment as specified in Project Settings (Rendering -> Environment -> Default Environment) could not be loaded.
   At: scene/main/scene_tree.cpp:2115.
ERROR: load_source_code: Condition "err" is true. Returned: err
   At: modules/gdscript/gdscript.cpp:806.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: modules/gdscript/gdscript.cpp:2244.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: start: Condition "res.is_null()" is true. Continuing.
   At: main/main.cpp:1684.
WARNING: _update_root_rect: Font oversampling only works with the resize modes 'Keep Width', 'Keep Height', and 'Expand'.
   At: scene/main/scene_tree.cpp:1153.
ERROR: load_interactive: Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:986.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: Method failed. Returning: error
   At: core/io/resource_format_binary.cpp:655.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://escenas/suelos/solo_suelo/roca.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://escenas_importadas/suelos/roca.glb
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://escenas/suelos/suelos_terminados/mosaico_roca.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://escenas/suelos/solo_suelo/roca.tscn
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://escenas/Escena_principal.tscn:6 - Parse Error: [ext_resource] referenced nonexistent resource at: res://escenas/suelos/suelos_terminados/mosaico_roca.tscn
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: start: Condition "!scene" is true. Returned: false
   At: main/main.cpp:1864.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ariel@ariel:~$

**Comment by Calinou** [comment]
@kone9 You should include just `base_de_datos/*` instead of `res://`. We should throw an error about this :slightly_smiling_face:

**Comment by kone9** [comment]
> @kone9 You should include just `base_de_datos/*` instead of `res://`. We should throw an error about this

![Captura de pantalla_2020-02-05_17-59-22](https://user-images.githubusercontent.com/12847027/73882707-4ec79c00-4841-11ea-876d-d510d37b0f6b.png)
![Captura de pantalla_2020-02-05_17-59-41](https://user-images.githubusercontent.com/12847027/73882712-5129f600-4841-11ea-98ca-f9a805faddd0.png)

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
![Captura de pantalla_2020-02-05_18-00-51](https://user-images.githubusercontent.com/12847027/73882798-83d3ee80-4841-11ea-9e2d-e5098b323082.png)
![Captura de pantalla_2020-02-05_18-02-07](https://user-images.githubusercontent.com/12847027/73882880-a403ad80-4841-11ea-8db8-c3cc4a290bdc.png)
![Captura de pantalla_2020-02-05_18-01-51](https://user-images.githubusercontent.com/12847027/73882881-a6660780-4841-11ea-89ba-44212a4c0b65.png)

In this case, the program closes and the console shows this.
``ariel@ariel:~$ '/home/ariel/Escritorio/exportado yousef/index.x86_64'
Godot Engine v3.2.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce 9800 GT/PCIe/SSE2
 
ERROR: load_interactive: Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
   At: scene/resources/resource_format_text.cpp:1228.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: SceneTree: Default Environment as specified in Project Settings (Rendering -> Environment -> Default Environment) could not be loaded.
   At: scene/main/scene_tree.cpp:2115.
ERROR: load_source_code: Condition "err" is true. Returned: err
   At: modules/gdscript/gdscript.cpp:806.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: modules/gdscript/gdscript.cpp:2244.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: start: Condition "res.is_null()" is true. Continuing.
   At: main/main.cpp:1684.
WARNING: _update_root_rect: Font oversampling only works with the resize modes 'Keep Width', 'Keep Height', and 'Expand'.
   At: scene/main/scene_tree.cpp:1153.
ERROR: load_interactive: Condition "err != OK" is true. Returned: Ref<ResourceInteractiveLoader>()
   At: core/io/resource_format_binary.cpp:986.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: Method failed. Returning: error
   At: core/io/resource_format_binary.cpp:655.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://escenas/suelos/solo_suelo/roca.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://escenas_importadas/suelos/roca.glb
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://escenas/suelos/suelos_terminados/mosaico_roca.tscn:3 - Parse Error: [ext_resource] referenced nonexistent resource at: res://escenas/suelos/solo_suelo/roca.tscn
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: poll: res://escenas/Escena_principal.tscn:6 - Parse Error: [ext_resource] referenced nonexistent resource at: res://escenas/suelos/suelos_terminados/mosaico_roca.tscn
   At: scene/resources/resource_format_text.cpp:440.
ERROR: load: Condition "err != OK" is true. Returned: RES()
   At: core/io/resource_loader.cpp:208.
ERROR: _load: Condition "found" is true. Returned: RES()
   At: core/io/resource_loader.cpp:278.
ERROR: start: Condition "!scene" is true. Returned: false
   At: main/main.cpp:1864.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112.
WARNING: cleanup: ObjectDB Instances still exist!
   At: core/object.cpp:2071.
ariel@ariel:~$

**Comment by kone9** [comment]
> @kone9 You should include just `base_de_datos/*` instead of `res://`. We should throw an error about this

Even if the name changes, the exact same problem happens ..
Will it have to do with the file system?

**Comment by kone9** [comment]
I made this small project to change the numbers directly from the ".txt" and I leave it to test in my case in linux mint xfce 19.02 I could not export, I will have to install windows 10.
[prueba exportar archivo godot.zip](https://github.com/godotengine/godot/files/4167182/prueba.exportar.archivo.godot.zip)

**Comment by aaronfranke** [comment]
Is this bug still a problem in Godot 4.x?

**Comment by Daniel-The-Fox** [comment]
For me, in version 4.1.3, unfortunately yes... 😢

**Comment by sungmini** [comment]
Same thing in 4.2.1... Is there a solution to this?

**Comment by KoBeWi** [comment]
File filters use `String.matchn()` against full path, thus you can provide full file path if you don't want to use wildcards.
If that's not sufficient, open a [proposal](https://github.com/godotengine/godot-proposals).
