### ISSUE TITLE
Godot development calling it quits on certain hardware/platforms, might be needed?

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#17084]
In response to the recent news regarding development, I have made this reply to the big Godot thread on Blenderartists.

> By the looks of things, new 3D rendering features have again been put on hold and WebGL support may actually be downgraded (due to issues with slow adoption and compatibility).
> 
> It also looks like that Android has become a massive anchor in terms of advancing the world of gaming on mobile (so for gaming purposes, Google could start to face a sinking ship in wealthier countries if it doesn't get the massive fragmentation under control). Then you have Apple trying to push its own proprietary API, which could've become a major problem for commercial and free game engines alike if not for recent moves to try to ease the ability to work with both Vulkan and Metal.
> 
> In a way, I'm starting to wonder if the Godot devs. should just have a cut down feature set for mobile at the moment. Android is fragmented in a huge way and it's difficult for developers to make any money on that platform (and in some cases even making games that work). Apple is increasingly fragmenting their ecosystem (now you have an exotic "notched screen" format) as well as the occasional rule change that catch devs. in the crossfire (no guns in the game icon including fantasy weapons, the kneejerk reaction that removed American Civil-war games, ect...). Microsoft continues to stumble and is continually changing their ideas of how to get Windows adopted by more people. By the looks of things, mobile is increasingly becoming a messy platform which is even making the PC look stable (despite differences in hardware).
> 
> Onto the compatibility thing, the Godot devs. may need to figure out when to just pull support for certain platforms and hardware **(trying to support everything under the sun with the same feature set may be a lot more work than it should be)**.

The reason for this is that while it would be true that some choices would be unpopular, the attempt to support every platform and all of their configurations may just be too much for the level of resources that Godot as a project has now. Trying to do this has plagued other game engine teams as well (even big ones with billions of dollars like Unity) and some have made the decision to either call it quits on a platform or configuration or have it only support a cut down feature set.

Oh, and this by the way does not mean the devs. shouldn't go ahead and finish the OpenGL ES2 renderer for Godot 3.1 (as that was planned all along and is actively being worked on, compatibility with more platforms is generally a good thing if it doesn't prove to be a major thorn in development and overall becoming a major blocker in moving Godot forward).

Comments?

**Comment by reduz** [comment]
There is something a lot of people does not really understand and it's that we are not some a company that allocates employees to work on tasks decided by management.

All our contributors work on what they want, when they want. Neither I or anyone else gives them orders or decide what has to be supported and what doesn't. It just doesn't work like this so please stop assuming it. 

I work mainly on the high end rendering back-end and Thomas works on the low end one (GLES2). It's not "wasted resources" to support mobile. It happens because contributors want it to happen.

**Comment by akien-mga** [comment]
Godot is mainly used for mobile games so far, dropping mobile support when we could just implement a GLES2 renderer doesn't make any sense.

So what should we drop? Desktop? Then we can't run the editor.

Then yeah, we could drop web support. But it's not like it takes all our focus, it's mainly @eska014 working on it because he's interested in it.

**Comment by Ranoller** [comment]
If someone decide to drop desktop i kill myself and drops all of you with my blood. I'm reading a lot of c++ to the case i regret.

**Comment by akien-mga** [comment]
Ok, let's not get pointlessly emotional here.

**Comment by Ranoller** [comment]
Jajaja, you have the forms of "project manager" even with the jokes, man!
