### ISSUE TITLE
TextureProgress not working when the value is bigger than 62

### ISSUE THREAD

**Issue by CCODE05B** [godotengine/godot#17102]
The same issue : https://github.com/godotengine/godot/issues/17011
and for some reason no one set it as a bug

**Godot version:**
Godot 3.0.1 Stable and Godot 3.0.2 RC1

**Issue description:**
when seting TextureProgress Fill mode to : Clockwise or to counter Clockwise and set the value more than 62 .. it does not render and there is an error say : Bad polygon 

the value from 0 to 62 work fine , from 63 to 99 not working , and 100 work fine
in Godot 3.0 stable works fine

**Steps to reproduce:**
add TextureProgress node , add your progress texture to it , set the value more than 62 .. it's not rendering and if you run the project you will get an error say Bad polygon !
set it to 100 or less than 63 it will work fine

**Minimal reproduction project:**
[TestProgressTexture.zip](https://github.com/godotengine/godot/files/1766889/TestProgressTexture.zip)

**Comment by volzhs** [comment]
```
ERROR: canvas_item_add_polygon: Bad Polygon!
   At: servers/visual/visual_server_canvas.cpp:675.
```
confirmed this error occurred.

**Comment by volzhs** [comment]
it's regression from #16419
91215e191992f3cbbbf4fe047b000ac5a403085c master branch
a0e59a7259990a8c55ddfaec5eb5481373172a5a 3.0 branch

@nical do you have an idea what is wrong here?

**Comment by nical** [comment]
I'll have a look in the next few days.

**Comment by volzhs** [comment]
@nical Thank you :smile:

**Comment by hpvb** [comment]
I've added this bug to the 'known bugs in 3.0.1' section of the [release notes](https://godotengine.org/article/maintenance-release-godot-3-0-1#known-bugs).

**Comment by nical** [comment]
The bug is caused by the first check in `Triangulate::snip` 

```
	if (CMP_EPSILON > (((Bx - Ax) * (Cy - Ay)) - ((By - Ay) * (Cx - Ax)))) return false;
```

Which tries to rule out triangles that are negative or zero-area.

If the expression on the right hand side is negative it means the winding is wrong and the triangle is outside the shape. If it is zero, it means we have a zero-area triangle (the 3 points are aligned).

The problem is that it can happen that the last three points at the end of the triangulation are indeed aligned, and in this case the test prevents the triangulation from completing. In practice, zero area triangles (while not very useful), aren't problematic when it comes to rendering correctness, so I believe we should relax this check and accept them.

The easiest way to go about it is to just relax the check for all triangles. It is a simple change but will potentially generate several zero-area triangles if there are many aligned vertices in the polygon. We can try something a little more complicated to mitigate that, for example relaxing the check only if we have exhausted all combinations. I'll submit a pull request that does the latter, but we can also chose to go for the simple fix if degenerate triangles aren't an issue.
