### ISSUE TITLE
Add Simulated property to RigidBodies

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [godotengine/godot#17100]
**Godot version:**
All 3.0 branches (stable/master)

**OS/device including version:**
All

**Issue description:**
Needs to add a Simulated property to RigidBodies and KinematicBodies to allows disable from physics system. Unity has it (https://docs.unity3d.com/ScriptReference/Rigidbody2D-simulated.html). It allows to disable/enable the rigidbody from the physics processing.

**Steps to reproduce:**
- Create a rigid body with some shapes and a texture.
- Try to disable it from the physics system.

**Comment by mysticfall** [comment]
Is setting the proposed `simulated` property any different from changing `RigidBody.mode` to `MODE_STATIC` or `MODE_KINEMATIC`?

**Comment by Alexia-AT-Digitecnology** [comment]
Yes, it's totally different @mysticfall, Is disabling entirely the body from the physics system, not changing the body type.

**Comment by KoBeWi** [comment]
Setting it to MODE_STATIC and disabling colliders should have the same effect.

**Comment by Calinou** [comment]
See also KoBeWi's answer above for a possible solution.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
