### ISSUE TITLE
2 ortogonal axis projection - a.k.a. Tibia or Ultima VII pesperctive

### ISSUE THREAD

**Issue by Sposito** [godotengine/godot#17128]
I am beating my head a little bit here for a while but I still could not find a way to set up my game to look like Tibia pesperctive: [exemple](https://i.stack.imgur.com/luwBF.jpg)

Reading on tutorials on internet I could figure out how a normal orthographic perspective works, but tibia's one is kind of odd.

Digging over webs I found in [here][2] a guy (Clint Bellanger) who describes really well how to get the same perspective in blender's render according to him:

> Start with a scene in 45 degree isometric.  Video game style, where
> the camera angle is Blender (60,0,45).
> 
> In Blender if you look at Buttons Window -> Scene -> Render Buttons ->
> Format, you can set the render aspect ratio.  Set AspY to half of
> AspX.  This is the same as taking regular rendered output and scaling
> X by 50%.  If you rendered a cube, the top of the cube will be a
> perfect square (though at a 45 degree angle).
> 
> We can then use Blender nodes to rotate the result 45 degrees.  The
> output: 
> 
> Note this started as a cube, so there's a lot of "vertical"
> distortion.  So you might have to scale meshes to 50% Z before using
> this method.  Also notice the Edge seems to be applied after the
> Aspect, so the edge isn't distorted.
> 
> Blend file: http://clintbellanger.net/images/temp/UltimaVII.blend (I'm
> a Nodes noob so there might be a smarter setup).
> 
> For kicks, here is that tower again.  I pulled it into the above
> workflow scene and scaled Z by 50%.  Click "Re-render this layer" on
> the first node to create the composite.

On his method, he used stuff like rescaling the render and changing the scale of models, Im convinced I could get along just with the 4x4matrix but different from Unity Godot doesn't expose it apparently (anyhow I could not get it right how to configure this matrix)

Hope someone more experienced with perks of 3D maths could help me to figure it out. Thank you! =D

  [2]:https://opengameart.org/forumtopic/reverse-engineering-ultima-vii-isometrics-wip

**Comment by Zylann** [comment]
Tibia look like a 2D game, so why are you trying to do this in 3D? This looks fairly doable using a 2D tilemap.

**Comment by Sposito** [comment]
I think you missed my point. Maybe I haven't explained myself well enough. Tibia is a 2D game(that emulates a 3D ortogonal pesperctive), what I want is a ortogonal projection to give to my 3D game that  nostalgic feel. Besides of that is an really useful pesperctive since for having two ortogonal axis it emulates well this grid feeling.

**Comment by gaudecker** [comment]
I'm actually researching the same exact feature. It seems like it's the render output aspect ratio scaling that is required.

**Comment by FlowOverFail** [comment]
I know this is old, but any updates on this?
I saw a recent post on a project for a Tibia client using Unity: https://github.com/slavidodo/OpenTibia-Unity

This inspired me to think back on GoDot, to see it something similar could be done. If anyone has tried this, has any insights, or could point me in the right direction, I would greatly appreciate it!

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
