### ISSUE TITLE
GDScript: Overriding get_property_list() directly

### ISSUE THREAD

**Issue by ILoveGodot** [godotengine/godot#17122]
**Godot version:** 3.0.1

**Issue description:**
The return value of an overridden _get_property_list() function seems to get added to an existing property list instead of replacing it. I really need full control of the property list because I don't want certain items to be in there. It would be nice if we could just override get_property_list() directly.

**Steps to reproduce:**
-Add this script to a node:
```gdscript
extends Node

func _ready():
	print(get_property_list()) #Prints populated array

func _get_property_list():
	return []
```

**Comment by Zylann** [comment]
I would not want that. Or at least, not have `_get_property_list` override everything. There are often many properties you would have to fill anyways, including those exported by the base C++ nodes, and important ones such like `script` and `filename` for example. They need to, because properties from this list not only describe their visibility in editor, but also their serialization behavior.

**Comment by ILoveGodot** [comment]
I'm not asking to change the behavior of `_get_property_list`. But rather make `get_property_list` virtual as well to be able to avoid unnecessary properties. I need this because I'm writing an editor plugin and I need to hide some properties in the inspector because the user is not supposed to change them. I don't think that this would mess anything up. Even if that was the case I could still add the required properties manually and just set their usage flags to `PROPERTY_USAGE_NOEDITOR` so they stay hidden.

**Comment by Zylann** [comment]
So yeah... you will need to redeclare all the properties your node inherit, with the correct hints and types, only to have them hidden.

**Comment by ILoveGodot** [comment]
Another solution would be being able to override specific properties returned by `get_property_list`. For example the `script` property is always automatically returned by `get_property_list`. It doesn't matter if `_get_property_list` returns `script` as well. Then `get_property_list` will return two `script` properties instead of only one. But it would be nice and make sense if properties returned by `_get_property_list` would override properties returned by `get_property_list` instead of just adding an additional `script` property to the returned array. That way I could just override the `script` property with a new `script` property with the usage flag `PROPERTY_USAGE_NOEDITOR` to hide it in the inspector. Because if the user modifies the script property, everything would be messed up in my plugin and the editor would crash.

**Comment by willnationsdev** [comment]
Maybe what could be done instead is to also expose `_get_script_property_list()` with an additional `p_inherited_properties` boolean flag for only returning the current script's data if `false`? That would allow him to "get" only the subset of properties that are related to his particular script, which is what the `_get_script_property_list()` method handles. Right?

**Comment by beeryt** [comment]
I can use `_get_property_list()` to create a `PROPERTY_USAGE_GROUP`, but it only appears to group properties which are returned from `_get_property_list()`. I would like to either
- a) move a property from `get_script_property_list()` into `_get_property_list()`
- b) add a `PROPERTY_USAGE_GROUP` property to `get_script_property_list()`

As far as I can tell in 3.2.1 I can halfway accomplish this by duplicating the property in `_get_property_list()`. This can be seen where I have
```
export var value_count := 1
func _get_property_list() -> Array:
    var properties = []
    properties.append({
        name = "Values",
        type = TYPE_NIL,
        hint_string = "value_",
        usage = PROPERTY_USAGE_GROUP | PROPERTY_USAGE_SCRIPT_VARIABLE
    })
    properties.append({
        name = "value_count",
        type = TYPE_INT,
        usage = PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_SCRIPT_VARIABLE
    })
    return properties
```   
![image](https://user-images.githubusercontent.com/14947602/87591788-b5c56880-c69d-11ea-94b9-546996c4ac39.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
