### ISSUE TITLE
Using Viewport with ViewportContainer for scene transitions gives huge performance hits

### ISSUE THREAD

**Issue by footurist** [godotengine/godot#17136]
The problem is on android device only (Vernee Mix 2). Is that a common problem with ViewportContainers? I am using Viewports inside ViewportContainers for all my scenes for having the sprites not overlapping each other. Then I have 2 scenes active some time before the transition and, well, transition them. However, this leads to huge performance hit even for a simple 2d game like mine (replika of Gibbets:Bow Master). When I use normal Node2Ds performance is a lot better (still a little stutter during transitions...why?), but obviously the sprites are overlapping again...any idea what's causing this? I mean, 2 simple 2d scenes can't really be Godot's limit right?

 I am using Godot 3.0, Android 7.0 for this.

**Comment by Footurist** [comment]
@Zylann talked to me about the issue in Q&A and he suspects it's because this strucutre result in having the doubled amount of pixels drawn in the end (original scene and viewport texture). So, if someone can confirm this, this can probably be closed with me keeping in mind that viewports will always be costly for mobile apps, unless someone considers it a good idea to try to change how viewports work, because of this (probably not xD).

**Comment by Zylann** [comment]
I'd be curious to know if they really are supposed to cause mobile perf decrease. Maybe it would not matter if they are to be rendered directly on screen (no need for an additional buffer so no double draw?) but I'm not sure of this

**Comment by Calinou** [comment]
You can probably set the first viewport's update mode to Once so it doesn't keep rendering while the second viewport is rendering.
