### ISSUE TITLE
InputEventScreenDrag.relative does not work properly under "Emulate Touchscreen"

### ISSUE THREAD

**Issue by JPTeasdale** [godotengine/godot#17131]
**Godot version:**
3.0

**OS/device including version:**
All devices. 

**Issue description:**
According to the docs: 
InputEventScreenDrag.relative is relative to the position the touch began. 
InputEventMouseMotion.relative is relative to it's position in the previous frame. 

[ in /main/input_default.cpp Line: 298](https://github.com/godotengine/godot/blob/612ab4bbc6f2396f4dcd68c3f142f7dfa2f5f0a5/main/input_default.cpp#L298)

You can see the relative prop of the mouse event being directly copied into the relative prop of the touch event.

**Comment by Calinou** [comment]
@JPTeasdale Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
