### ISSUE TITLE
No support for aarch64 for X11 platform

### ISSUE THREAD

**Issue by bkeys** [godotengine/godot#17197]
**Godot version:**
Master

**OS/device including version:**
Fedora 27

**Issue description:**

I got this from the compiler
```
In file included from thirdparty/thekla_atlas/nvcore/nvcore.h:23:0,
                 from thirdparty/thekla_atlas/nvcore/Memory.h:7,
                 from thirdparty/thekla_atlas/nvcore/Memory.cpp:3:
thirdparty/thekla_atlas/poshlib/posh.h:538:4: error: #error POSH cannot determine target CPU
 #  error POSH cannot determine target CPU
    ^~~~~
In file included from thirdparty/thekla_atlas/nvcore/Memory.h:7:0,
                 from thirdparty/thekla_atlas/nvcore/Memory.cpp:3:
thirdparty/thekla_atlas/nvcore/nvcore.h:118:5: error: #error "Unsupported CPU"
 #   error "Unsupported CPU"
     ^~~~~
In file included from thirdparty/thekla_atlas/nvcore/Memory.cpp:4:0:
thirdparty/thekla_atlas/nvcore/Debug.h: In function 'bool nv::isValidPtr(const void*)':
thirdparty/thekla_atlas/nvcore/Debug.h:203:38: error: cast from 'const void*' to 'uint32 {aka unsigned int}' loses precision [-fpermissive]
      if (reinterpret_cast<uint32>(ptr) == 0xcccccccc) return false;
                                      ^
thirdparty/thekla_atlas/nvcore/Debug.h:204:38: error: cast from 'const void*' to 'uint32 {aka unsigned int}' loses precision [-fpermissive]
      if (reinterpret_cast<uint32>(ptr) == 0xcdcdcdcd) return false;
                                      ^
thirdparty/thekla_atlas/nvcore/Debug.h:205:38: error: cast from 'const void*' to 'uint32 {aka unsigned int}' loses precision [-fpermissive]
      if (reinterpret_cast<uint32>(ptr) == 0xdddddddd) return false;
                                      ^
thirdparty/thekla_atlas/nvcore/Debug.h:206:38: error: cast from 'const void*' to 'uint32 {aka unsigned int}' loses precision [-fpermissive]
      if (reinterpret_cast<uint32>(ptr) == 0xffffffff) return false;
                                      ^
scons: *** [thirdparty/thekla_atlas/nvcore/Memory.x11.tools.64.o] Error 1
scons: building terminated because of errors.
```

**Steps to reproduce:**
Go through the compilation instructions 
http://docs.godotengine.org/en/latest/development/compiling/compiling_for_x11.html
on any aarch64 machine. A guy made a patch but his issue seems to be dead
https://github.com/godotengine/godot/issues/15948

**Comment by bkeys** [comment]
I made a pull request to thekla_atlas, my fork builds locally on my aarch64 box.
https://github.com/Thekla/thekla_atlas/pull/13

**Comment by reduz** [comment]
I don't think this is a bug, probably should be an enhancement?

**Comment by Bucklandevelopment** [comment]
Hello everyone, yesterday i was trying to compile godot in a devboard Nvidia Jetson Tx1, my uname -a says
Linux tegra-ubuntu 4.4.38-tegra #1 SMP PREEMPT Thu Mar 1 20:44:58 PST 2018 aarch64 aarch64 aarch64 GNU/Linux

i follow the instructions for x11 debian ubuntu oneliner, and then a simply scons platform=x11

The compilation prompts me this error

[Initial build] Linking Static Library ==> core/libcore.x11.tools.64.a
Ranlib Library         ==> core/libcore.x11.tools.64.a
[Initial build] Linking Program        ==> bin/godot.x11.tools.64
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmGetDevices2'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmCloseOnce'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmMap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmOpenOnce'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmUnmap'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmFreeDevice'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmGetDeviceNameFromFd2'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmGetDevice2'
/usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/libGL.so: undefined reference to `drmFreeDevices'
collect2: error: ld returned 1 exit status
scons: *** [bin/godot.x11.tools.64] Error 1
scons: building terminated because of errors.

reading similar issues, i found the issue #16000, but cant apply to aarch64, so reading devtalk.nvidia.com i read this solution.

cd /home/ubuntu/NVIDIA_CUDA-7.0_Samples/common/lib/linux/aarch64
rm libGL.so
sudo ln -s /usr/lib/aarch64-linux-gnu/tegra/libGL.so libGL.so

So i think that maybe with this softlink, the problem maybe will be solved. Is that correct? 
Cause looking for libGL.so in /usr/lib/aarch64-linux-gnu says me

lrwxrwxrwx  1 root root        16 Dec 16 10:42 libGL.so -> tegra/libGL.so.1

But my questions are, must i change something in the source code in relation with SConstruct file? Must i use llvm instead gcc? Must i copy the softlink in the /usr/lib/gcc/aarch64-linux-gnu/5/../../../aarch64-linux-gnu/ folder? 

Thanks in advanced for the answers!!

**Comment by Bucklandevelopment** [comment]
After copy the file...
 
sudo cp /usr/lib/aarch64-linux-gnu/libGL.so 

I use 

sudo scons -c .

and then 

sudo scons platform=x11 

All compiles very fast saying 

scons: Reading SConscript files ...
Enabling ALSA
Enabling PulseAudio
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[100%] progress_finish(["progress_finish"], [])
[100%] scons: done building targets.

Executable works but have some errors on creating projects etc

**Comment by akien-mga** [comment]
For the reference, I could build Godot 3.0.6 out of the box on Mageia (Cauldron) and Fedora's (EPEL7, FC27, FC28, F29 and Rawhide) official aarch64 build target. So this seems fixed.

@Bucklandevelopment The issue with the Nvidia libGL.so is unrelated and should probably be raised with your distro's maintainers, it's a packaging issue.
