### ISSUE TITLE
Add a feature to automatically convert animations for humanoid characters

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17201]
**Godot version:**
`master` / 3d03bcd0636aacfe530c52fc1cdc32c2edffea04

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
When creating a 3D game, many indie developers who don't have a strong design background find it difficult to create animations for their characters, especially if they aim for a game which shows more realistic human movements.

Unity tries to mitigate this problem by one of their key features called 'Mecanim', which is an animation system that supports automatically converting animations between generic humanoid characters:

 * https://docs.unity3d.com/Manual/AvatarCreationandSetup.html

As explained in the above documentation, it works by letting the users to create a metadata (called an 'Avatar') for the source and target rigs, specifying default poses for each limbs and rotational limitations.

Provided a model has a properly configured Avatar, it can use any animations originally created for different humanoid characters with minimal tweakings.

It can be especially useful, combined with their marketplace where people can purchase animations created by those who are more experienced in 3D modelling.

Even though there are not many games made with Godot that features realistic human movements and our asset repository is rather small, it'd be reasonable to assume that the situation could change with the growing popularity of the engine.

I think having such a system can help our users to create high quality games with more realistic animations and encouraging them to share their assets with other people.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
