### ISSUE TITLE
Feature: AnimationPlayer track type for boxes and other spatial metadata

### ISSUE THREAD

**Issue by admiralzeech** [godotengine/godot#17223]
Hi, in many games, each frame of animation has some spatial metadata associated with it, in the form of boxes, spheres, points etc.  For example, in fighting games, we have hit boxes and hurt boxes:
https://goo.gl/images/7XWqvk

What's the best way to do this in Godot?  Would it be a good idea to add a new type of track into AnimationPlayer (in addition to Normal, Transform, and Call_Func tracks)?  Let's call it "Spatial Meta"

When you add a Spatial Meta track, you give it a name, and then add a single shape to the track.  It could be a point, 2D shapes like rects and circles, or 3D shapes like spheres and boxes.   You can use the discrete/continuous setting to tween the location/size of the shape between frames, or to set it directly on exact frames.

From the code, you can refer to the track by name, get the type of shape it contains, and obtain the current location and dimensions.

In the above, you have one track per shape.  Alternatively, we could make the feature more complex and support multiple shapes per track.  In which case you would need to be able to name each shape.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
