### ISSUE TITLE
Bullet Physics buggy rigid body rotation

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#17231]
**Godot version:**
3.0.1

**Issue description:**
Setting rotation on rigid body that has linear velocity causes it to jitter with Bullet physics.
This problem doesn't happen when switching to `GodotPhysics` in the project settings.

It doesn't happen when using `angular_velocity` instead of rotation/rotate.

**Steps to reproduce:**
Use this script on a rigid body (with disabled gravity so it wont fall away)
```
extends RigidBody

var move_speed = 50
var rotation_speed = 5

func _physics_process(delta):
	rotate_y(rotation_speed * delta) # buggy with bullet physics
	#angular_velocity.y = rotation_speed # works fine
	var move_direction = Vector3(move_speed, 0, 0).rotated(Vector3(0,1,0), rotation.y)
	linear_velocity = move_direction
```

**Minimal reproduction project:**
[BulletPhysics.zip](https://github.com/godotengine/godot/files/1777882/BulletPhysics.zip)

**Comment by mrcdk** [comment]
You can't modify rotation or position directly in a `RigidBody` because that's managed by the physics system, you will need to use `_integrate_forces()` to safely modify the state of the object http://docs.godotengine.org/en/3.0/classes/class_rigidbody.html#class-rigidbody-integrate-forces

**Comment by LinuxUserGD** [comment]
```
extends RigidBody

var move_speed = 50
var rotation_speed = 5
var move_direction = 0


func _integrate_forces(state):
	angular_velocity.y = rotation_speed
	move_direction = Vector3(move_speed, 0, 0).rotated(Vector3(0,1,0), rotation.y)
	linear_velocity = move_direction
```

**Comment by Enhex** [comment]
I see, thanks!

**Comment by aaronfranke** [comment]
I can confirm this issue. Switching to GodotPhysics fixes the issue. The `_integrate_forces` method only works if I change the RigidBody mode to "Character", since when it is "Rigid", it ceases to be called if the object does not experience any movement or physics after a certain time.

We should consider adding documentation about this to the [RigidBody](http://docs.godotengine.org/en/3.0/classes/class_rigidbody.html) page. Currently, there is a warning under the `linear_velocity` property about using `_integrate_forces`, but it does not mention that it's important to change the RigidBody type for this function to always run. In fact, the "Rigid" mode even says it can "be affected by user code" which is misleading.

**Comment by arigoru** [comment]
So is there any proper workaround for this?   
  
None of suggested solutions work in case were you need to lock angular rotation of that body for physics. So if you have RigidBody that has Y axis locked, you can not rotate it anymore, because current suggested workaround involves rotating it via physics, and you can only do that if you are not locking that angular axis.    
   
I have RigidBody that is not supposed to rotate via physics, and rotating it manually blocks all other physic interactions, while using angular velocity or torque defeats the purpose because it requires unlocking that axis for all other physic interactions as well, not just your rotation.   
   
So how am I to rotate RigidBody along Y axis, if I need to have `axis_lock_angular_y = true` to stop it rotating due to collisions?
