### ISSUE TITLE
Black spots when using normal maps.

### ISSUE THREAD

**Issue by OscarOG** [godotengine/godot#17239]
**Godot version:**
3.0.1

**OS/device including version:**
Windows 10

**Issue description:**
Black spots when using texture normals. [Black spots](https://ibb.co/b8Cdxn)

**Steps to reproduce:**
Using 128x64 png texture and a normal map.

**Comment by OscarOG** [comment]
**Mode:** Video RAM
**Lossy Quality:** 0.7
**HDR Mode:** Compress
**Normal Map:** Detect

**Comment by quantum-entangler** [comment]
And have you tried other selections, such as lossless/uncompressed? What about adjusting the "Lossy Quality"?

**Comment by OscarOG** [comment]
Yep, i tested changing all other options but none solved it. I thought it may happend only when normal mapping small resolution textures because thats not the only texture happening this but dont know if this may be a Godot limitation/problem or a more general issue. I dont know if there is a minimun recomended size for normal mapping use. Any ideas?

**Comment by OscarOG** [comment]
Well, i dont know how [Atomic](https://github.com/AtomicGameEngine/AtomicGameEngine) handle textures, its more simplest/basic than Godot.

[Example Scene](https://mega.nz/#!3SQ0WRZB!LTCGyvBnaknQoMBShoVxQKllwWy-9myvRw4ztUoa-mg)

**Comment by quantum-entangler** [comment]
Ok now when you changed the texture import settings did you also hit Reimport afterwards?

Because I just opened your example, then in file browser clicked on the normalmap then in the import panel changed to lossless and hit Reimport and voilà:
![CompressedVsLossless](https://picload.org/image/daooawgw/normalmap_compressedvslossless.png)

Next I decided to try Video RAM compression again however with HDR setting changed to force RGBE:
![ForceRGBE](https://picload.org/image/daooawrr/normalmap_compressed_hdr_rgbep.png)

This I tested with both 3.0.0 and 3.0.1

**Comment by OscarOG** [comment]
Yeah you are right. I was changing and reimporting the albedo texture, not the normal map one, which is the affected... silly mistake. Very sorry. :(

**Comment by quantum-entangler** [comment]
I do have to say though, you are at least the third person I've run into within the last 30 days to have problems with the default normal map compression settings.

**Comment by OscarOG** [comment]
Then maybe default settings are good for albedo textures but not for other specific ones. By the way, i had to use the **lossless** compression mode because forcing RGBE in Video RAM caused undesirable effects on the texture. It turned the texture completely black when walking little away from it.

**Comment by Calinou** [comment]
> Then maybe default settings are good for albedo textures but not for other specific ones.

Godot tries to detect whether you're importing a normal map or not, but the detection occasionally fails.

**Comment by OscarOG** [comment]
@Calinou 
Ok but after detecting its a normal map, what are the settings (compression mode, etc) Godot set by default to it that differs from albedo defaults settings?

**Comment by skelewir** [comment]
I have a similar issue but changing import settings does not help.
There are still black artifacts.

![image](https://user-images.githubusercontent.com/25341266/38171328-94f4b326-35a0-11e8-8ac6-242139e042ad.png)

![final_mesh_defaultmaterial_normal](https://user-images.githubusercontent.com/25341266/38171318-168f63a0-35a0-11e8-9d05-4392183e9178.png)

**Comment by Megalomaniak** [comment]
@skelewir I'm going to make a guess and say that you baked this texture in blender and saved into .png without removing compression so what you are seeing are in fact compression artifacts.

**Comment by skelewir** [comment]
@Megalomaniak Thanks, a few questions then.
1. But the actual texture looks good. So, where that compression comes from?
2. Why does it look fine when used in blender?
3. I did not make the texture myself, got it from a friend. So how can I fix this?

**Comment by Megalomaniak** [comment]
> Thanks, a few questions then.
>  
> 1. But the actual texture looks good. So, where that compression comes from?
> 2. Why does it look fine when used in blender?
> 3. I did not make the texture myself, got it from a friend. So how can I fix this?

1. Could be very subtle noise.
2. Blender is different in handedness and might do further(more costly) filtering.
3. Try inverting the red and green color channels in GIMP or Photoshop.

**Comment by skelewir** [comment]
@Megalomaniak Trying to understand the nature of the issue. I still can't figure out how can a subtle difference in texture cause black artifacts. Could you point me in right direction.
I'm a programmer fairly new to 3d graphics.

**Comment by Megalomaniak** [comment]
16bpp would technically be better than 8.

In a sense the normal map bends the mesh normals(per pixel sampled) so as to make a low polygon mesh seem higher poly-count. In other words it hold geometric data, sort of. Its only used for light calculations and since we are not dealing with full on multi-bounce raytracing in case of very strongly bent normals it might end up hitting no light sources but instead interpret the ray hit as shadow. Thats one way you could end up with these black spots. Try lowering the bump strength, if this is the issue that should solve it. This is a fairly rare issue however so I doubt thats it, but it's worth ruling out, I guess.

It could also be that you have actually hit a bug in the renderer perhaps, but it's always good to rule other things out first. Might also be simply an issue stemming from the fact that the normal map during baking didn't get anti-aliased(the cycles renderer afaik lacks AA for baking).

**Comment by skelewir** [comment]
I still think it's a render bug.
Adjusting the normal map scale param does not affect artifacts in any way. So it seems those dot's have zero normal, which should only be possible if I had black dots in my texture.

![default](https://user-images.githubusercontent.com/25341266/38196053-83c67848-3689-11e8-8914-ae849bc13dcb.png)

![default](https://user-images.githubusercontent.com/25341266/38196092-c206b366-3689-11e8-86c2-821f5f755107.png)

![default](https://user-images.githubusercontent.com/25341266/38196074-9ec7b5f8-3689-11e8-8d36-29ae36177074.png)

**Comment by Megalomaniak** [comment]
Ok, since I'm replying from my workstation today, pulled your normalmap into blender's compositor and squeezed the blue channel:

![Squeezed Blue Channel](https://picload.org/image/dapapwil/normalmap_blue_squeeze.png "Click on image to see full size.")

How much you willing to wager that noise matches up with your black spotty noise?

**Comment by Megalomaniak** [comment]
Sure, as long as there is an option to turn that off. IMHO. ;)

**Comment by vnen** [comment]
Yeah, it looks like it's not a bug with the rendering engine, but rather a usability thing with the import settings. If anyone wants to improve the import, feel free to open a new issue.

**Comment by istemihan90** [comment]
https://www.reddit.com/r/godot/comments/nbqrxn/godot_33_how_to_enlighten_ever_part_of_the_map/

https://youtu.be/xC-U-xAnbaA

Hello, I run into the same problem, but I could not understand from the post what is the actual problem? I tried reimporting all the normal textures with lossless optoion but still having the problem. Is there any update on this?

**Comment by Megalomaniak** [comment]
No that is a completely different issue. Check your camera clipping settings.

**Comment by istemihan90** [comment]
camera -> far property. It was set to 100. When I change it to 1000 it was solved. Thanks.
