### ISSUE TITLE
Indent tabs vs. spaces: different settings per language

### ISSUE THREAD

**Issue by garyo** [godotengine/godot#17240]
In #8424, the editor was made configurable with tabs vs. spaces for indent, which is great.
However, the Godot standard is 4-space tabs, but Python recommends (in https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) 4 spaces, and _never_ tabs.

It would be great if the editor had (optional) per-language indent settings, so python could default to 4 spaces but other languages could be kept as they are. My reason for this is there's a _lot_ of existing python code out there; editing it into the Godot editor adds tabs, and python rejects them. And setting my entire world to 4 spaces just for python's benefit seems like the tail wagging the dog.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
