### ISSUE TITLE
Bullet Physics convexSweepTest

### ISSUE THREAD

**Issue by Enhex** [godotengine/godot#17253]
It's like ray cast, but with a convex shape so it has volume:
http://bulletphysics.org/Bullet/BulletFull/classbtCollisionWorld.html#aeeee096b94a5eb31e8c88a29b6c69d37

It would be really useful to provide API for it.
Ray casts aren't reliable when you need to handle volumes.

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
We already have it: https://github.com/godotengine/godot/blob/4b9ab27deabf52de85e86bf69946814ec766c3e1/modules/bullet/space_bullet.cpp#L152-L196

**Comment by Enhex** [comment]
Thanks!

I couldn't find it when I tried looking for it, perhaps it should be explained in the physics tutorial.

**Comment by jitspoe** [comment]
That function is very limited, or at least very unintuitive.  Normally you want to sweep a shape and see what it hit (and where).  Would be nice to have a straightforward "shapecast" or "sweep" function that took a shape, start, and end position and returned a KinematicCollision.

As it is now, I guess you have to call cast_motion, calculate based on one of the floating point values returned how far to move it, then call get_rest_info() and hope it's overlapping the contact point and not off by some floating point precision issue, then pull the values you want out of the returned dictionary?  I fundamentally hate the idea of trying to place something exactly at the point of contact as opposed to doing a sweep past it then determining the point of contact.  The latter should be far more reliable.

Side note: I recently discovered that you can use move_and_collide() with the last parameter (test_only) set to true to do a sweep but not move, so that might come in handy.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
