### ISSUE TITLE
Custom actions in the property editor for some nodes

### ISSUE THREAD

**Issue by poke1024** [godotengine/godot#17276]
Not a bug issue, but a discussion issue.

I recently came across an annoying problem having to do with transforms in `Polygon2D`. My problem was, in short, that I wanted the polygon to have a neutral transform due to some display problems. Unfortunately, there currently seems no way to neutralize a polygon's transform by applying the current transform to all its vertices and setting the transform to identity then.

I started wondering where such a function could be made available. Could the property editor get an `Actions` group for predefined editor actions adhering to some class, such as - for `Polygon2D` - neutralize the transform? Here's a mockup:

<img width="334" alt="neutralize-transform-action" src="https://user-images.githubusercontent.com/11859538/36968748-c03570ea-2063-11e8-88ea-70df98360c9c.png">

What do you guys think?

------

Details of my original problem (just for completeness, sort of unrelated to the proposal above):

I had a sprite nested inside a polygon and had a polygon scale of `(2, 1)`:

<img width="143" alt="bildschirmfoto 2018-03-05 um 10 50 25" src="https://user-images.githubusercontent.com/11859538/36968649-73809e8c-2063-11e8-9ef7-05b322cc266b.png">

This produces nasty skewing in the sprite:

<img width="532" alt="bildschirmfoto 2018-03-05 um 10 50 09" src="https://user-images.githubusercontent.com/11859538/36968665-85e54316-2063-11e8-89b3-bd4618eaf6d0.png">

**Comment by groud** [comment]
I don't think it is necessary to have a system dedicated for actions since the planned Inspector rework will probably allow for custom interfaces (and thus specific actions).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
