### ISSUE TITLE
Suggestion - When Attach Script

### ISSUE THREAD

**Issue by alexbosquin** [godotengine/godot#17282]
_(Sorry for my english)_
To Make Attach Script better, i have some ideas , simple but cool:

![capture](https://user-images.githubusercontent.com/8551379/36982677-2bdf961c-206f-11e8-82ea-7b62fbf8feb7.PNG)

As you can see, when user select C# as langague the following has to happen:
1) **Inherits None Instead of the Node name, the Option None is a clean class without inherits**
2) **The default template is:**

```csharp
using Godot;
using System;

public class ClassName : NodeName
{
    // Member variables here, example:
    // private int a = 2;
    // private string b = "textvar";

    public override void _Ready()
    {
        // Called every time the node is added to the scene.
        // Initialization here
        
    }

//    public override void _Process(float delta)
//    {
//        // Called every frame. Delta is time since last frame.
//        // Update game logic here.
//        
//    }
}
```

The None template shoud be:
```csharp
using Godot;
using System;

public class ClassName: NodeName
{

    public override void _Ready()
    {
    }
}
```
* **The Namespace if marked, in this example must result:**
```csharp
namespace Game.PlayerFeatures
{
     public class ClassName: Control
     {
          public override void _Ready()
         {
         }
      }
}
```

* **The path always make the class name as the node name, this results on conflicts**:
```csharp
public class Node : Node
```
the correct way:
```csharp
public class RandomName : Node
```

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
