### ISSUE TITLE
VideoStream - get length, get dimensions , set playback speed methods

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#17335]
It would be very helpful for interactive apps using that file to be able to get some of the stream's data. 

3 very key methods are missing at the moment:
- ability to get the video's length (in a value compatible with stream_position)
- ability to get the width and height of a video 
- ability to set the playback speed dynamically while the video is running 1= normal 0.5 = slower 2=faster

Probably related to it- we have a method for setting stream position that does nothing:
https://github.com/godotengine/godot/blob/13c2ff9/modules/webm/video_stream_webm.cpp#L222-L225

```
void VideoStreamPlaybackWebm::seek(float p_time) {

	//Not implemented
}
```
Seems like a bug, because the documentation doesnt state that this is not implemented yet

**Comment by blurymind** [comment]
Unity and Unreal are both putting a lot of effort in supporting video atm:
https://unity3d.com/solutions/360video
https://assetstore.unity.com/packages/tools/video/vr-video-player-82597

because it has huge potential for vr content creation

Think of the possibility

**Comment by oap-bram** [comment]
Stumbled on this with the same problem. Getting the size of the video is fixed through [get_video_texture()](https://docs.godotengine.org/en/3.2/classes/class_videoplayer.html?#class-videoplayer-method-get-video-texture)
```gdscript
$VideoPlayer.stream = stream # Your stream
var texture = $VideoPlayer.get_video_texture()
var size = texture.get_size()
```

The two missing features is getting the video length and setting the playback speed.

**Comment by TheMoye** [comment]
Three more useful additions:

- support for the WebM VP9 codec
- alpha channel support
- the ability to loop (without freezing artifacts between loops)

**Comment by Calinou** [comment]
> support for the WebM VP9 codec

This is already supported since Godot 3.0, just like VP8 :slightly_smiling_face: 

That said, I would discourage using it due to the sheer amount of CPU power required to decode it.

**Comment by TheMoye** [comment]
> 
> 
> > support for the WebM VP9 codec
> 
> This is already supported since Godot 3.0, just like VP8 🙂
> 
> That said, I would discourage using it due to the sheer amount of CPU power required to decode it.

Strange, I couldn't play a WebM VP9 video exported from Blender or downloaded from Youtube.
The same VP8 encoded video works.

**Comment by oap-bram** [comment]
> I think the way forward would be to go oldschool and integrate MPEG1 decoding support using [pl_mpeg](https://github.com/phoboslab/pl_mpeg). It results in larger files if you want good quality, but it's _very_ lightweight on the CPU. Looking at benchmarks, it should work well even on mobile/Web platforms.
> 
> MPEG2 would allow for better quality as it's patent-free since 2018, but I'm not aware of any open source decoding library that's easy to integrate into something like Godot.

Isn't there a way to do it with the [GDNative videodecoder](https://github.com/kidrigger/godot-videodecoder) project already? I couldn't find any examples tho. Some of you might know? Maybe someone could add that to the docs as well.

**Comment by Calinou** [comment]
@oap-bram Yes, but I don't think that plugin is currently working with the latest Godot version. You also have to deal with FFmpeg's complexity and licensing restrictions (LGPL or GPL).

**Comment by TheMoye** [comment]
I'm currently editing my project under Linux and the VideoPlayer can't play the WebM VP8 file. I just have a black screen.

In summary : 
Under Windows 10 the WebM VP9 video played by the VideoPlayer is black and makes the application crash but works in WebM VP8.
Under Linux neither the WebM VP9 nor the VP8 file is displayed. The application does not crash. 🤷‍♂️

![linux](https://user-images.githubusercontent.com/46683101/78330822-1d3f2880-7585-11ea-96bd-a0cda4e4c95b.png)

**Comment by akien-mga** [comment]
@TheMoye This has been fixed already in 3.2.1: https://godotengine.org/article/maintenance-release-godot-3-2-1

**Comment by BrodyEller** [comment]
I'm working on a project that makes heavy use of the `VideoPlayer` node so I'm looking to implement major improvements to it, especially since it seems to be of low priority. 

[Over on my fork](https://github.com/BrodyEller/godot/tree/VideoPlayerImprovements), I've added three improvements so far, a `get_stream_length` method, a `get_stream_dimensions` method, as well as a Stretch Mode property that's basically copy-paste from the `TextureRect` node. I wanted to get some feedback here before I continue going about this. I have some questions first:

1. Why doesn't `VideoPlayer` inherit from `TextureRect`? It seems like `TextureRect` covers the aspect ratio needs of `VideoPlayer` and would work in largely the same fashion as now, without duplicated stretch code.
2. I'd like to see a `get_stream_fps` method as well. Many video libraries use two numbers to represent this, the numerator and denominator. Should the function return a float or `Vector2`?
3. Should I be making changes to the 3.2 or master branch? My fork is of the 3.2 branch.

I'm also looking into finishing the ogv and webm implementations. I've only been looking into libtheora so far, but `get_stream_length` isn't trivial to implement because that data isn't in the header. You have to get it from the `granulepos` of the last frame.

**Comment by Calinou** [comment]
> Should I be making changes to the 3.2 or master branch? My fork is of the 3.2 branch.

Pull requests should be opened against the `master` branch whenever possible, unless the feature in question is currently not working in the `master` branch.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
