### ISSUE TITLE
Allow values scrolling of the node numeric properties

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#17371]
For node properties, using lists or numeric values in a certain range, it would be convenient to change simply by hovering over the value and scrolling the mouse wheel, instead of spending at least 3 clicks.

**Comment by toby3d** [comment]
@groud To scroll the inspector, just hold the cursor in the left half (where the keys are located), or scroll the slider on the right side. I do not think that this completely breaks the concept of scrolling.

Alternatively, you can activate scrolling only when the value change is initialized. In any case, now the developer is still obliged to make clicks on the slider or enter a value from the keyboard. This in itself is too much action to change one value that could be scrolled with a wheel.

**Comment by toby3d** [comment]
Also, I would leave both of my suggested options, but allowed me to enable and disable something (or all) of them in the editor's settings.

**Comment by groud** [comment]
> just hold the cursor in the left half (where the keys are located),

This is a pain to work with.

> Alternatively, you can activate scrolling only when the value change is initialized. In any case, now the developer is still obliged to make clicks on the slider or enter a value from the keyboard. This in itself is too much action to change one value that could be scrolled with a wheel.

Well yes, changing a value is something that should be done on purpose. So no, a click is not too much to do such change, else people are going to complain because the values changed when they didn't want to. A good UX is not defined by how many click or actions you have to do to achieve what you want. 

My proposal is not to have to use the slider: you click on the field, then drag up or down to change the value. Like blender does actually.

**Comment by toby3d** [comment]
@groud Okay, right. We can use Blender mechanism (long press with moving up/down) without click and "click-on-value" with scrolling value via mouse wheel too. That's okay?

**Comment by groud** [comment]
> and "click-on-value" with scrolling value via mouse wheel too

You mean like if you're currently editing the field ? I guess it could make sense, since in that case we're sure you want to edit the value.

**Comment by alexbosquin** [comment]
Nice Suggestion, for me the best mechanic is from premiere pro, you click and hold on the number and then move mouse left or right to increase/decrease

**Comment by toby3d** [comment]
> You mean like if you're currently editing the field ? @groud 

Yep.

**Comment by wingedadventurer** [comment]
I would have to agree with Noshyaar. Scrolling when cursor is above a property is way better than current method. An awesome addition would be to copy Adobe Illustrator's style where if you just scroll, you change the value by 1, if you hold Shift you change it by 10, and if you hold Ctrl you change it by 0.1.

It is way more precise and faster when you need to get to certain value. I can feel and physically count the amount of scrolls I make as opposed to the distance covered when dragging. Scrolls are discrete and precise, dragging is continuous and unprecise. If I want to set a value to 13.4, I know it will take 1 + 3 + 4 = 8 scrolls to do so.

Another suggestion I have is to click with scroll wheel to reset the property to original value so we can remove the "reset" button and have more space for the value itself.

Since we have mixed preferences about this, it would be good it there was a setting to define your way of quickly changing properties.

**Comment by Noshyaar** [comment]
>I would have to agree with Noshyaar
I didn't say I support this. I just link issues. :stuck_out_tongue:
But I do agree about it being in the editor settings as we frequently use this operation and everyone has their preferred way.

**Comment by breakmt** [comment]
I think it should be like that - you click in field and than you can scroll mouse wheel up/down to change value. I think in Unity done like that and it pretty handy for me.
Drag mouse left/right with LMB pushed is ok too... But it not very convient at least for me.

**Comment by ScepticDope** [comment]
I'd like support for scrolling but also for the arrow up and down keys. I use a fly wheel and sometimes I like a bit more more precision, for instance when I only want to increase or decrease one tick. This workflow works in most software that support these sort of value boxes.

Also I noticed some random value boxes in the editor already support scrolling but that might have been some extreme wishful thinking. :disappointed:
