### ISSUE TITLE
Stop method of AnimationPlayer clears the animation

### ISSUE THREAD

**Issue by alkhimey** [godotengine/godot#17423]
Related to Godot 3.0.

Look at the documentation of `stop` method of `AnimationPlayer`.
 
It looks that it was the intention that when the [`reset`](http://docs.godotengine.org/en/3.0/classes/class_animationplayer.html#stop) parameter is set to false, then the method would act as a pause.

> Stop the currently playing animation. If reset is true, the anim position is reset to 0.

Setting `reset` to `false` does preserve the position of the animation but the issue here is that it clears the animation itself. 

```
	print("* Initial values")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)

	$PlayerAnimation.play("walk_up")
	$PlayerAnimation.seek(3.14)
	
	print("* After play+seek")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)
	
	$PlayerAnimation.stop(false)

	print("* After stop")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)
	
	$PlayerAnimation.play("walk_up")
	
	print("* After another play")
	print("animation: ", $PlayerAnimation.current_animation)
	print("position: ", $PlayerAnimation.current_animation_position)
```

Output:

```
* Initial values
0
* After play+seek
3.14
walk_up
* After stop
3.14
* After another play
animation: walk_up
position: 0
```

I don't think, there is any other no built-in way to pause an animation, but there is an easy workaround:

```
var last_anim_pos = 0.0
var last_anim = null

func pause_animation():
	last_anim_pos = $PlayerAnimation.current_animation_position
	last_anim = $PlayerAnimation.current_animation
	$PlayerAnimation.stop()

func continue_animation():
	$PlayerAnimation.play(last_anim)
	$PlayerAnimation.seek(last_anim_pos)
```

**Comment by agameraaron** [comment]
I have a different use-case wherein I ran into this bug. It is not just to pause and restart an animation, but I do some code to animate manually after the animationplayer does so. I use this with my transitions so that if a user skips the splash screens, it will override the current animation with the skip code instead.

In 2.1 I could stop an animation and it would do more like a 'pause' (what stop(false) is supposed to do), but now as expected based on what the docs say, it will now reset back to zero.

I got it all working with stop(true) and storing the opacity before I stop the animation, but stop(false) **not only** resets back to zero and delete the animation, it seems to prevent gdscript from modifying some values. I can't change the alpha channel through gdscript at all once I perform stop(false).

I don't know how far reaching this is, if it affects other variables or whatever other consequences of this but even if it deletes the animation as alkhimey suggests then how could this be a side-effect? I am not sure how relevant this bug is or what exactly is going on. More testing might need be done. I've got it working on my end with a little workaround thankfully but if any dev trying to fix this needs an example, gimmie a response here. Hope fixing alkhimey's bug somehow fixes this one in the process.

**Comment by bojidar-bg** [comment]
Sorry, this seems to stem from my changes of AnimationPlayer.

Basically, `current_animation` is `""` when `playing` is false, and `assigned_animation` otherwise.
In order to use the `stop(false)` feature, you should call `play()` without arguments to resume.

**Comment by luizcarlos1405** [comment]
Calling `play` without arguments also resets the animation.
