### ISSUE TITLE
Add color to dimming effect for modal dialogs in the editor

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#17434]
This improvement adds a canvas item to render the dimming effect, in contrast to how it's done currently, which is by changing the `modulate` property of the canvas item used for the editor.

This canvas item would sit on top of the editor but beneath a modal dialog and is rendered with a solid color, configurable in the editor settings. The dimming effect is accomplished by modulating the alpha component for the color in this item.  

[This is how it looks](https://youtu.be/X6d3FkgaPEY).

The commit that has the changes is [this one](https://github.com/rraallvv/godot/commit/4015212a38bab403ec30d1bcfe4e6bf54bf8ebf9).

The credit goes to @Hinsbart since this improvement builds on top of [his code](https://github.com/godotengine/godot/pull/7970) for the original dimming effect.

Maybe, we could have an option in the editor settings to switch between modulating the editor color (how it's done currently) and adding a overly with a custom color (how it's done in the changes I'm suggesting)

Please let me know if you are interested.

**Comment by rraallvv** [comment]
@mhilbrunner, I haven't done a PR yet because of @akien-mga's comment in this [PR](https://github.com/godotengine/godot/pull/12937) where he says:

> [it's] best [to] discuss them first before spending too much time on a PR

By the way, I totally agree, which bring's me to what I was asking [here](https://godotdevelopers.org/forum/discussion/18749/what-about-a-dedicated-site-for-feature-request-and-voting) about a dedicated site for feature requests and voting. Those requests wouldn't necessarily have to compete or conflict with the ones at patreon.com, maybe something like https://xamarin.uservoice.com or https://expo.canny.io but hosted at a free third party dedicated website.

**Comment by mhilbrunner** [comment]
Haha, no worries :) I just meant because there already is a commit with code.

But yeah, usually its best to discuss beforehand, so you don't do any work for PRs that are going to be rejected.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
