### ISSUE TITLE
Disable showing editor for selected node on scene tree

### ISSUE THREAD

**Issue by rraallvv** [godotengine/godot#17444]
Sometimes when I'm editing a script I run the game right away to see the changes, instead of looking at the 3D/2D scene editor, and want to be always on the script editor.

The problem is that if I select a different node in the scene tree panel, Godot shows the default editor for that node and I have to be constantly switching back to the script editor.

This improvement add an option to the editor settings to disable that behavior, so no matter what node I select on the scene tree, the editor that is currently active will remain so.

It's useful for live editing too and also for scripts that have exported properties or access other nodes in the hierarchy, so that if one needs to tweak some properties in the attributes editor while still editing the script, Godot won't switch the editor when selecting a different node (also related to [this usability issue](https://github.com/godotengine/godot/issues/12721))

The changes that need to be done are in [this commit](https://github.com/rraallvv/godot/commit/f16e5de099ccda44d857d5f8383b1fa713fd35d4).

**Comment by rraallvv** [comment]
I made [some modifications](https://github.com/rraallvv/godot/commit/becc9a15f5d41aeb2855dbd0666119c1b8484fa3) so that double-clicking on a node in the scene tree still show the default editor for that node, although showing the editor with only one click can be disabled from the editor settings.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
