### ISSUE TITLE
Tween causes game lag when calling "interpolate_property(...)" and "start()" huge number of times

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#17452]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
So, it seems that interpolating some property (and starting it, of course) for a very large number of times causes game FPS to drop drastically. I have discovered this by accidentally calling the said two methods in "_process(delta)", therefore calling it every step, and I did it for about 100 nodes at a time.

This might not seem like an issue since nobody will use the tween every step, but what if a player leaves his game open for a few hours in the level which contains many objects that use tweens? It could cause unexpected lag.

I haven't explored it deeper. I only found out that it doesn't lag when you don't call "start()" method.

If you want to explore, start off with the minimal reproduction project.

**Steps to reproduce:**
Call "interpolate_property(...)" and "start()" huge number of times (put it in the "_process(delta)") and wait some time. The game should lag. Increase the number of nodes for faster results.

**Minimal reproduction project:**
[Tween Lag Test.zip](https://github.com/godotengine/godot/files/1800698/Tween.Lag.Test.zip)

**Comment by bojidar-bg** [comment]
Note that calling `interpolate_property` and then `start` will not stop previous interpolate_property-es. Since the time for each interpolation is 50 _seconds_, and `_process` is called around 60 times per second, in the ideal case you are going to get `50 s * 60 / s = 3000` `interpolate_property` calls running at the same time, per tween; with the 72 tweens in the project, it becomes 216 000 tweenings to do.

Just adding `$Tween.remove(self, "rotation_degrees")` before calling `interpolate_property` gets the FPS back to normal.

**Comment by wingedadventurer** [comment]
@bojidar-bg I'm stupid. I didn't realize it's 50 **seconds**, not milliseconds. 🤦‍♂️  Because of that I assumed that previous interpolations didn't end.
