### ISSUE TITLE
Allow animation keys to handle rotation/translation/scaling separately

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17477]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Currently, an animation key holds changes in rotation, translation, and scaling of the target object for the keyframe which work good in simple use cases.

However, it is sometimes desired to keep an animation track to handle certain type of changes while using another track for other type of changes and mix them.

One of the common scenario would be creating a character designer which morphs the characters body shapes by scaling its various bones, either from code or animations.

When playing a normal animation (i.e. walking) with such a character, all the applied morphs would be lost because keyframes in the played animation contain scaling information even if it's not needed.

Blender (and possibly other animation creating tools also) supports specifying only selective type of changes (rotation / translation / scaling) for each keyframe, but when exported to Godot, every keyframes contains all three of the change types thus making such kind of a use case impossible.

Currently, it is inevitable to keep the morph informations and apply them in every frame after the animation player advances to make it work which is both cumbersome and potentially a performance problem.

Ideally, we need some way to either preserve what changes each keyframe contains when an animation is imported into Godot, or add an filter which can ignore unused changes per each track.

**Comment by YeldhamDev** [comment]
I may be understanding the report completely wrong, but having a track edit exclusively rotation/translation/scaling values is already a thing, right?

**Comment by mysticfall** [comment]
@YeldhamDev It's as much as possible that I may be completely ignorant of an existing feature :)

When I click on a key in a transform track, I don't see how I can filter out any of the translation, rotation, or scale properties so it won't affect any previously applied transformation.

If there's already an way to do that, could you tell me how I can achieve that?

**Comment by YeldhamDev** [comment]
Why not just track the the rotation/translation/scaling values directly?
![screenshot1](https://user-images.githubusercontent.com/30739239/37319029-20425afa-264c-11e8-805f-9369de41994f.png)

**Comment by mysticfall** [comment]
I can see how it can be used in certain situation, but it's not applicable to rigged 3D characters though.

First of all, there's no way to select individual bones in a skeleton since they are not `Spatial` nodes. And even if they were, it is often the case that animations would be created outside Godot and if they contain keys that only selectively changes the transform, such information should be preserved when they get imported.

**Comment by YeldhamDev** [comment]
About Godot preserving the keys in importation, this really should be looked at.
But about changing parts of the transforms in bones, couldn't you try using `Call Func` tracks and use the `rotated`/`scaled`/`translated` functions with it?

**Comment by mysticfall** [comment]
It's possible in theory, but it would be close to impossible to create any complex animations that way. 

Imagine creating a simple walk cycle that way, by adding a few hundred keys that call functions to rotate each bones (left upper leg, right foot, etc.) by code rather than using something like Blender or Maya.

It's wose than drawing textures for a realistic 3D game with MS Paint, so shouldn't be a recommended workflow for anyone, IMO.

**Comment by JayFontenot** [comment]
I really need this honestly. I can't think of any alternative/workaround with this that isn't massively painful and overcomplicated

**Comment by dberickson** [comment]
Since I didn't see this addressed in the latest changelog so I thought it would be good to comment on again - this is a significant limitation with Godot. I believe the basic functionality required is to be able to keyframe individual axis within the transform, scale, or rotation (and other parameters as well, such as an alpha value in a color value). You can do this in Blender and other tools. A use-case for this would be something like a "pickup" object where you want to embed an animation in the the object to make it bounce vertically (y axis only) when hit but you want the x and z to remain where the "pickup" was placed in the scene. You can get around this by attaching each "pickup" to another spatial node but this is unnecessary work and additional objects to track. Same applies for rotation and scale and many other parameters.

**Comment by JayFontenot** [comment]
Tried my hand at it https://github.com/JayFontenot/godot/tree/better-skeleton-animation

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
