### ISSUE TITLE
Sparse Texture Support

### ISSUE THREAD

**Issue by Type1J** [godotengine/godot#17470]
A.k.a. Mega Texture

Unity currently has this feature. (https://docs.unity3d.com/Manual/SparseTextures.html)

It may have to wait for the move to Vulkan.

**Comment by Megalomaniak** [comment]
Yes, needs either higher GLES version or Vulkan.

**Comment by YeldhamDev** [comment]
I may be completely wrong, but isn't [LargeTexture](http://docs.godotengine.org/en/latest/classes/class_largetexture.html) that?

**Comment by Megalomaniak** [comment]
AFAIK not exactly, no. If you've ever played RAGE from id Software you likely have seen MegaTexturing. If not, perhaps you have played Assassins Creed: Unity it features Sparse Textures. They dynamically stream MIPs from disk.

Sparse Texture is GLES 3.1:
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_sparse_texture.txt

**Comment by Chaosus** [comment]
> GLES version or Vulkan.

Indeed it needs a Vulkan, we are moving to it from GLES, pushed to 4.0

**Comment by Type1J** [comment]
I was hoping that it might work in WebGL with GLES3: https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_sparse_texture.txt
Maybe that's too much to hope?

**Comment by Calinou** [comment]
@Type1J The specification says:

> OpenGL ES 3.1 is required.

WebGL 2.0 is roughly equivalent to OpenGL ES 3.0, and we're dropping GLES 3.0 for Vulkan and GLES 2.0 eventually. OpenGL ES 2.0 roughly matches WebGL 1.0, which is far more supported in browsers and graphics hardware (compare [WebGL 1.0](https://caniuse.com/#feat=webgl) and [WebGL 2.0](https://caniuse.com/#feat=webgl2) support on Can I Use).

**Comment by Type1J** [comment]
I think that that's probably best. We'll just have to wait for [WebGPU](https://www.youtube.com/watch?v=CCRI4TY1v08&t=91s) to catch on before doing sparse textures in browser. I have an issue open for that as well: #23764.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
