### ISSUE TITLE
Give us an option to let the user import and manage his files manually.

### ISSUE THREAD

**Issue by gmarais** [godotengine/godot#17498]
**Godot version: 3**

**About the `.import` directory, It is not about how and where to hide the files it is about why do you have to hide the files in the first place...**

I do not want Godot to generate files with a horrible hashed name in a hidden folder where the user should not look (if it sounds bad that usually means it is).
Let this be the horrible .meta files way of other game engines that hide away as much as they can from their users, I ditched these mainly for that exact reason.

When I work on a game I want to have full control over what it is doing the way it is doing it and what/how/where the files are.
I do not want to have semi-important hashed name zombie files in a directory I did not create in my repository because I replaced some materials with other materials or imported a new texture or whatever you can think of as a reason why they would appear and not be cleaned after.

Hiding behaviors and files away from the user is not a clean solution and I feel it does not make it easier for the users to understand what is happening overall if that was the though process behind that decision.
Just searching the Q&A for questions relative to import at least gave that away people are still pretty much lost.

If a file is needed/useful/important to configure and have our asset in the engine we should know why and how to make the best of it, and then manage it within a clean and understandable way.
Not having it hidden away like it is not our concern.
I would like Godot to let us manage our filesystems and assets and figure our for ourselves what we should be doing with all of these .mesh and .other .scn .stx files and configure them/delete/whatever if we so want.

If you are not going to ditch the "A la Unity" way of hiding things from the user at least **give us a settings to disable that behavior.**
As far as I am concerned it is unneeded and unwanted and I fear that it could lead to disastrous design decisions.

I intentionally kept the subject general I am talking about .import but it could be applied to a lot of design decisions in the future. I would really love it for Godot to always care and make sure to never hide/encapsulate away behaviors from the users over his added contents/assets and to always give him full control over his  filesystem.

I thank you for all the time and effort the team puts into the engine!
This is one issue/feedback that I felt deserved some attention but otherwise the engine is looking very good and the 3D looks great now!

**Comment by Omicron666** [comment]
You can see it as a cache. You can delete it at any time.

**Comment by gmarais** [comment]
I do see it, I do not understand why we have to have it and why we cannot manage these files ourselves like we used to in 2.1.
I do not see how it helps the workflow, and to be honest I would rather manage the .mesh and these other files and their dependencies myself in a more clean/understandable fashion and be able to make sure Godot never does that again.

**Comment by mhilbrunner** [comment]
>I do not want to have semi-important hashed name zombie files in a directory I did not create in my repository

You don't have to, you can safely .gitignore the .import/ folder.

**Comment by Ranoller** [comment]
Is there some way to have same file with different import flags to different scenes?

**Comment by rminderhoud** [comment]
Why don't you create a directory and use a `.gdignore` file to block importing.

**Comment by groud** [comment]
I have no clue what is your problem here. The import folders stores the import settings of your assets, settings that can should be changed through the import tab. This folder is hidden because the user SHOULD use the import tab to modify those files, and not modify them by hand. 

And if a user really needs to change something by hand, for debugging reasons, he should understand that it is not the way you are usually suppose to deal  with this files. So hiding the folder is better, avoiding misuse from typical users.

**Comment by groud** [comment]
And in general, I completely disagree. One of Godot's strength is its ability to hide the complexity of making a game to the user. There's no point in making every technical consideration available, this is definitely the worst UX you can offer. Godot is a simple software, I don't want users to wonder "What is this import folder about ?" -> In the general case, you never have to modify it, so we hide it.

However, I think all those technical thing should be well documented, so that if users ask "What is the import folder for ?", they should find an answer easily.

**Comment by gmarais** [comment]
As I said it is not making things simpler to just move them away and hide them in a corner. To me that's a cheap solution.

I don't want users to wonder "What is this import folder about ?" Well then don't create it for him in the first place let him manage his files maybe and most likely he can handle it especially if you provide him with the tools to do it.

When you design a good tool you don't usually make it so that there is only one way to use it.
I feel like these statements:

> "the user SHOULD use the import tab to modify those files"

> "he should understand that it is not the way you are usually suppose to deal with this files"
Are a proof that you think it is a good idea to force the user into one way of doing things which was not Godot's way before we used to have complete control over our files and contents.

You may not care having full control over your files and the way the engine uses/sorts them.
As much as I respect the fact that you might want to keep that away from you and not manage your files by hand I would like to point out that it may not be the case of everyone and that some people including myself pretty much adopted this engine for its filesystem and the level of control it provided.

All I ask is a way to disable the automatic creation/use of that directory and files and be able to do things manually like I used to before.

And yes the engine generates zombie files.

In the engine as it is right now I  cannot import a file from outside my project so having shared resources between multiple projects or different .mesh files for one model.
It seem to be "Not the way the user is supposed to" well sorry that is the way I like to work I like clean/dry/minimal and flexible tools...

I used to have my .obj and .dae outside and in the project I would import them as .mesh .scn or else and move them around instantiate them etc. And the .obj and .dae files as well as other files would be untouched and outside of the scope of the project.

I understand you may say it is not your way or whatever, yet I had no unnecessary duplication and a very dry and clean project overall with well defined directories understandable and self chosen naming conventions.

I understand that you might feel like it is just some guy that refuses to adapt and is being picky, I am asking you to keep an open mind on that matter.
In the end underlining a real opinion over what direction the engine is taking and how it may be hurting it.
In my case this is really something that can drive me away, as much as I love working on this engine full user control means everything to me.

> I don't want users to wonder "What is this import folder about ?"
As a matter of fact indeed we disagree on one crucial point I think users should be wondering "What is this import folder about ?".
The more people wondering and the more people looking at how it works the cleaner and the better it becomes and the better people get at using it and take advantage of it.

**Comment by groud** [comment]
Well no, Godot does not allow you to do whatever you want with your file structure, that's it.
The way you have to organize your files is part of Godot's design. Godot needs a project.godot file and an import folder. You remove them, your project does not work. Exactly like git requires a .git folder, a .gitignore and so on, it's part of the software design.

> When you design a good tool you don't usually make it so that there is only one way to use it.

Yes you do, if you provide several ways of dealing with a specific problem, you make it harder to anyone understanding how to make something. A good software design just provides you with a single and easy way to deal with your problem (that can be documented and all). But if there's no use case in making this more flexible, there's no reason to do it.

> In the engine as it is right now I cannot import a file from outside my project so having shared resources between multiple projects or different .mesh files for one model.

Well, you might prefer that yeah, but once again this is a design decision. If you want to import a file, it should be in the project folder. And allowing to load files from outside has been discussed several time.

> And yes the engine generates zombie files.

They are not zombie files, import files describe how your assets should be imported. They contain several important information. Such as the filters you apply on sprites or things like that, they're more like metadata files than a cache.

**Comment by bojidar-bg** [comment]
> The import folders stores the import settings of your assets, settings that can should be changed through the import tab.

Just to mention, this is not quite correct. Actually `*.import` files store the import settings in a .ini-esque format, while the `.import/` folder stores cached imported files.

The user isn't required to use the import tab, just as he isn't required to use the editor to write .tscn files. But, fact is, it is much simpler to use the import tab and the editor, as compared to editing by hand.

The idea behind the new import system was to make importing much less painful. In the previous versions, you had to worry about remembering to import files, while the new version imports automatically for you.

Now, there are likely some cases in which manual import is needed. We would like to support only automatic import now, for the sake of consistency, so we would view such cases as more-or-less bugs. Similar to package management solutions, you don't really want the user to have to mess around with files manually, when there is an automatic and (hopefully) bug-free method available.

So, removing the import folder for the sake of not having an import folder, or giving an option to manually import for the sake of manual import is a no-go. As [the FAQ explains](http://docs.godotengine.org/en/3.0/about/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think), you have to mention the problem you have, instead of just ranting how the new version is worse and the old one is better.

**Comment by gmarais** [comment]
> They are not zombie files

Steps to reproduce: add an asset remove it after the import directory is created: watches how the import directory still has the files inside it.

> They contain several important information.

These informations are important yes let me play with them. You like to hide your toys under your bed I like them sorted and in boxes that I manage myself why cant we have it both ways? 

> Well, you might prefer that yeah, but once again this is a design decision.

Yes it is what I am talking about how bad this design decision is and how it affects flexibility and users control in the end.

You want meta data files look at Unity3D they did it and that is the reason I came to Godot I wanted a open source and simple and minimalist engine, with no meta files and shadow area that you should not look at, with full user control. You are taking that away...

**Comment by akien-mga** [comment]
What this issue misses is that the new import system is not just "hiding complexity from the user", it's actually *removing* complexity which was a big hurdle for many users.

Before Godot 3, assets had to be imported manually, one by one, by using import dialogs in the editor to set the import properties, etc. Then you would end up with imported files in a format proprietary to the engine (.scn, .res, .tex, .msh, .smp, .fnt, etc.), and many users were confused about whether they should keep the source files in their project folder (.png, .dae, .obj, .ogg, .wav, .ttf, etc.). And as a matter of fact, for some of them they should (IIRC .fnt had hardcoded reference to the path to the .ttf, so if you moved the .ttf, it would throw a warning), for others it was not needed.

You want everything to be explicit to the user, but what is relevant to the user when handling sound effects? The imported binary .smp file they can't read outside Godot, or the source .wav file they can edit in Audacity and have re-imported on the fly with the import options they defined (loop, etc.)?

Sure there are advantages and drawbacks to both systems, but the new system is a *huge* usability improvement for most users, and we get a lot less complaints from users than we used to with the Godot 2 import system. Actually, the only users who complain are previous Godot 2 users who were used to the old system and unsettled by the new one. New users seem to be perfectly fine with how Godot 3 works.

> Steps to reproduce: add an asset remove it after the import directory is created: watches how the import directory still has the files inside it.

That's a bug, and should be fixed. The previous system was not bug-free either :)
A workaround is to just delete your `.import/` folder and get it regenerated with only what's actually in use.

**Comment by girng** [comment]
> you have to mention the problem you have, **instead of just ranting**

 
@gmarais i don't believe **you are ranting** my friend.
 
Just to add: one thing that should help a  lot, is never, EVER edit files inside the godot directory through an operating system's window. always manage your files (edit, rename, etc) inside the `Filesystem` tab. this way, when deleting or managing an asset, it will delete the referenced file in `.import`.

**Comment by sdfgeoff** [comment]
The question is: is having user control over these files useful? Or: what will a user do with these files (other than organize them - which is potentially-unneeded work).

To answer that, we need to know what is in those files - something I haven't seen come up in this discussion. So what is in these files? It is the imported form of more human-readable files.
If you have an obj file, then you get a mesh file. If you have a tscn file, it turns into a binary scn file. Why? To decrease the startup time of the game by pre-converting the assets into the format needed when the engine is running.

These files have two important properties:
 1) Non-human-editable (they are in a binary format unique to godot)
 2) Automatically generated from human-editable assets (and the assetname.import files).

And so it's kind-of like what happens with compiled software. You don't version control the binary files because they are something the user can generate and they aren't directly editable. As a result, you only "care" about the source files and the final output program/library, not all the .o and .a files in-between. With this system, we care about the source files (assets) and the final output program (the .pck), and so long as there aren't issues, there's no reason to bother with the files in-between (things in the .import folder).

Allowing the computer to manage these generated files shifts the organizational work off the developer's brain, and into the computer (which excels at repetitive tasks)

Other notes:
 - Never bother to version control the .import folder.
 - Control over items in the import directory is determined by the textual <assetname>.import file in the main directory.

----------------

> The problem I have: I want to be able to import my assets from where I want the way I want.

You can. You can control all the import settings _except_ the output path. Why not the output path? Because from inside godot, you address the source file directly.

--------------------------
@gring
Unfortunately you can't always help that. Version control systems need to be able to create/destroy files to be able to do there job.

**Comment by gmarais** [comment]
I am not saying I want you to remove the .import thing if you feel it is a great improvement for beginners so be it.

I just want a way to import my files from outside and manage them myself if I want to, like a enable manual import checkbox in the settings or something.

Just like granularity you can have multiple levels of abstractions without having them conflict with each other at all.

I really like Godot's way to have its own mesh files and imported resources files (copies) that he works with and the original files to stay untouched in a different place. I feel it is a workflow that has great potential and is both clean and data safe.
Then to me finding and sorting these imported resources is not more complex than sorting other files.

**Comment by groud** [comment]
If your need is to import files form outside the project folder, creating a symbolic link should work.

**Comment by gmarais** [comment]
So yeah talking about it now I think it could be resumed that way:

Behind the curtain the engine uses and works on "copy files" (.mesh etc) and leave the original files untouched (they are not used by the engine).
People get confused because they see two files (one original file .obj and a copy .mesh).

A decision was made to hide away the copies to make it less confusing.
I do believe from that perspective if we had to hide one file maybe it should have been the originals from within the editor as it is not the files we work on and the engine really do not need the file anymore since it was imported and the file wont be used.
Thus reflecting more accurately what is really happening behind the curtain and making it easy to understand at the same time.

That way you don't even have to create a import folder you just hide .dae, .obj files inside the engine and only show their automatically imported copies.

Users can still drag one or multiple .obj file(s) at drop it in their project it will keep the file in place and create a imported copy .mesh file that the user can manage and work with.

That way you have the same level of complexity while making sure users know from the get go what is happening and what they are really doing.

**Comment by Omicron666** [comment]
Check http://docs.godotengine.org/en/3.0/getting_started/workflow/assets/import_process.html
.import folder is hidden because only Godot is using it, but the process is known and explained.

If you really want to disable automatic reimporting when your assets are modified from 3rd party, you can disable that behavior here: ![image](https://i.imgur.com/yvkq1qK.png)

Projects are self-contained.
If you need your assets to be shared from somewhere else, make symbolic links in your project directory, to your asset directory.

**Comment by fracteed** [comment]
I do think that it would be a good option to be able to have a folder outside of the project folder for the cached .import files. Most DAW's and video editing software will give an option to store cache files in a general cache folder. It is not a huge problem but would be nice.

I do understand what the OP is asking and I somewhat agree with him, as I like to limit the number of extraneous file in a project structure. Though as Akien says, there are advantages and disadvantages to the old Godot2 way and the new Godot workflow.

I manually convert all my obj imported to .mesh files and delete the original objs as I find it much cleaner to look through folders with just the .mesh files, especially when you have dozens in one folder(my city folders have 100 meshes in each). I am also do a lot of procedural loading of meshes in my game, so I just need to load in the .mesh directly and have no need for the original objs. Hence my feature request of direct .mesh export from Blender (alongside the .etscn option) which would be very useful :)

**Comment by gmarais** [comment]
@fracteed Yes exactly what I am saying Godot does not need source files in its project directories.
It is misleading to let the developer think he should care about them. Here is the thing: I am not asking to be able to move the .import file elsewhere I am asking to not have it at all.
Because it is misleading it makes you think original files are the ones that matter when really the copies are the ones the engine uses and it is fine, and cleaner to just go with it completely.

You say some original files do need to be in there lets just fix these exceptions.

Right now you import meshes they get stored and copied in the .import folder then you have to copy them again to modify them in Godot and not have that "changes may be lost" thing. So in order to be able to import it and make changes to it in the editor you have to copy it once then you make your changes on a node that has the copy but not on the copy so you need 3 layers of abstraction where really if you do allow the developer to work with the copies you really need only 1.
Just because we try to make the user believe his original file is the one the engine uses.

I agree with fracteed here it is ok to have our own file formats and will be less misleading to assume it even if it means having our own Blender export yeah why not I would back that idea!

**Comment by Omicron666** [comment]
First, there is a proposal on GSOC 2018 project idea list for a Blender exporter: https://github.com/godotengine/godot-roadmap/blob/master/GSOC-2018.md

- The "Your modification may not be saved" part  could be reworked. So it displays options that are actually import settings.
- Actually, the good point about your topic (because I care about any constructive part) might be the "import" process part and its _naming_. That could just be named "asset configuration". So Godot doesn't make believe user can work with such "imported" cached files. And remove the option of importing automatically, makes the only (internal) way Godot works.

- Now Godot has its own internals, if it requires cached or working files anywhere, you can't just ask it not to use them at all! The question, though, is, could it cache less files on disk ? That might really impede time opening and loading projects, but saving disk space. Question remains open.

- In its current state, if you want not to have a ".import" folder content directly in your project directory, you might use a symbolic link for it too.

- It is normal for any software to hide some part to the user, too. That's not necessarily for any dubious reasons. As said by @groud [#issuecomment-372959647](#issuecomment-372959647)

**Comment by gmarais** [comment]
> Now Godot has its own internals, if it requires cached or working files anywhere, you can't just ask it not to use them at all! The question, though, is, could it cache less files on disk ? 

Well that is the point of having your own extensions, it means you can use them to store and have that extra level of cached information as well as making the data more digest for the engine.
These Godot extensions were the reason we did not have to have that .import directory in the first place in previous versions.

People can be unhappy that Godot uses its own extensions and it looks like it was what motivated this change in design.
But that is the way it was and I found it way cleaner and more honest. Having application specific extensions is also a very common way to deal with that problem actually a lot of good software do have their own extensions (.blend, .kra, etc...) why not a game engine since when is that a problem?

If people want to work only with their raw files (obj etc) that is just never going to happen they are just not sufficient and adapted enough, the cleanest solution to that problem is to get your own extensions the way Godot does (.mesh etc).
Hiding them away in a different place wont change that fact. But it opens the way to more shadowy and less efficient meta files and all the messy stuff that comes with them.

I understand it is something people, coming from engines that use meta files to handle that problem, might at first be asking: "why we need our own extensions". And can be a bit salty about.
Now if you tell them that this is either having application specific extensions or having disgusting meta files all over the place they might understand why Godot's way is more honest and cleaner and why they might want to stick with it.

Now people coming from other engines like Unity might be accustomed of having unclear and polluted Filesystems this is not my case as I pretty much ditched Unity over Godot because of these meta files,  and unclear/inefficient way of dealing with my assets, Godot was just so much cleaner about it.

Now I understand there was a switch in the design direction and we are on the edge of ditching extensions for the meta way of doing things.

I rarely ever speak up but I felt this was sufficiently important for me that I had to.
Sorry if I annoyed you you guys are free to take it or not. I know how critics can be tough to take at the same time if we never express our opinions...

**Comment by Gfurst** [comment]
Let me go back to this topic as I agree @gmarais on the subject. First time I tried to migrate to godot3 I was quite upset with it, specially because I have tons of individual small png files, and the initial process is impending and cannot be stopped. You can disable re-importing from altered files, but disabling the importing altogether which is unsettling, and basically godot would continue to use the old imported asset in that manner...

Though I see what the advantage of having the .import folder there, I fail to see why automating the process helps, making it seamless for the user, which in this case, the user of the godot editor is a developer, he should know and understand fully well how the process and what he is doing with the project resources. (and lets not even get into game optimization)

But I do propose a solution, make the initial importing a manual process, in which the developer chooses the import parameters, but after that it takes advantage of the .import handling system, auto importing the resource on change or seamlessly getting the already processed resource from code. This is better because I can think of two use cases where it fits:

1. when the default option do not fit your project and you simply have to re-import everything again, which is just wasted time
2. when you want access to the original file in its format, like an image or audio file without conversion
 
And finally on the subject of "making it easier" for the user, just don't. We're developers here, and people who get into this trade should understand what they're doing, Godot is already super simple to get without effort, just put more effort into documentation instead. And besides, you don't want to get the fame of (nor compete with) Unity.

**Comment by wildwinni** [comment]
Okay okay - this discussion is getting heated and I'd like to way in on the "More control" aspect of the importing but for different reasons than many of the above.
The first and key reason is the development of GDScripts and the changing of images and resources via code. 

When a project is compiled most of the time the compiler does not include the PNG, JPG files etc in the project, if you do you have to use different coding options to access them, however you do Not require to access these files directly with the import system because the Load mechanic is superseded and unclear. 

**Steps to produce.**
1. I create a project like say a gallery selection. The project contains thumbnails in a control - they were added by the client they appear normally.
2. I then add a bunch of images into the folder that are Not assigned into any texture, they are not currently a part of the project. ie "image1.png, image2.png, image3.png" etc
3. Expected behaviour - in the GD Script when I Load "image1.png" and assign the sprite or texturerect to the resulting texture from Load - it works in the project.
4. I compile the resulting project.... Loading of image fails.
5. I attempt to include the file in my project - bloating the file. Compile it. Loading fails.

Alternatively I can use the Correct and simplified behaviour.
1. I take all of my image1.png, image2.png etc and import them.
2. I then find the resulting .tex files in the .import folder. I copy them out and rename them to image1.stex image2.stex etc.
3. In my code I use Streamtexture to load those files directly, bypassing the complications of using two different formats.

**conclusion :** 
:: If I keep ALL of my data files as stex oggstra sample etc and use them in that format only - bypassing the automatic import feature it simplifies coding my GDScripts, and it doesn't penalize me in the slightest when I use those file formats via the interface. Meaning it's better for me to NOT leave my source files in the project folder. Plus by using only pre-imported files in my project with consistant namings, and manually updating the files myself I keep my workspace clean.

**My Suggestions**
For those who want to keep their work-spaces clean there should be a means of importing/converting the files that does not involve leaving source files in your folder structure. For example

- Working Directory
- - Source Files
- - - Images
- - - - File 1.png
- - - Sounds
- - Game Project
- - - Images
- - - - File1.stex
- - - Sounds

The client should if the developer wishes to do so provide a dialog where I can select "File 1".png from out outside project and create the file "File 1.stex" wherever I want to put it. By including this manual import as an option in the system but Not removing the auto-import mechanic for those who are used to it you literally have the best of both worlds,

**Comment by Calinou** [comment]
> That could also be useful - being able to tell the project which folders it can ignore in it's scans.

You can create a file named `.gdignore` and place it in any directory. It will tell Godot not to import the files located inside.
