### ISSUE TITLE
Click shortcut to focus 3D camera distance?

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17517]
Godot 3.0.2

Unity3D does something really clever that I ended up using a lot of times since I discovered it:

If you middle-click anywhere in the viewport, the editor takes the depth of the pixel you clicked on (if there is an object there), and recalculates the camera focus to that point, but without changing your current distance from it (so it's quite seamless, it only strafes left/right/up/down to it). Then, next time you orbit or zoom, the camera will rotate around that point, strafe and zoom at adapted speed using that point as reference.
This is not the same as F because it uses the point you clicked on (no need for exact precision though, we don't fly planes with this).

This is a subtle feature, but very useful in particular when working on environments where the objects aren't much localized and fill a lot of space, like buildings, terrains or gridmaps. I am currently needing it while working on a large terrain: I use freelook to move around and look closely at the ground while I work on the shader, which is fine for that type of edition, but as soon as I use mouse wheel or strafe, the camera jumps super far away because my focus point is fucked up, and I can't place it on any particular object because the only object in the scene (the terrain) is just too huge.

Currently I could use the speed/zoom link option I left after implementing freelook, but it seems to no longer perform like it was intended (it reverts too high speed)

**Comment by groud** [comment]
I agree that the current way of dealing with the camera is not super obvious. Your proposal seems to be a good enhancement

**Comment by Calinou** [comment]
Should this middle click action be placed behind a modifier? It will make it easier to pan around a model without accidentally "drifting" away from the model due to you not clicking exactly at the center.

**Comment by Zylann** [comment]
@Calinou this is not supposed to be an issue because like I've seen in other software, panning is a dragging operation and could only start after moving the mouse by a small amount of pixels (something I haven't seen enough in Godot, sadly). Middle-clicking is supposed to be under that threshold because it would register only if the mouse doesn't move (or by only 1 or 2 pixels if you are hasty).
It could be behind a modifier sure, but it feels unnecessary.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
