### ISSUE TITLE
Geometry and Texture streaming

### ISSUE THREAD

**Issue by HeadClot** [godotengine/godot#17556]
Would it be possible to get geometry and texture streaming implemented into Godot?

**Why I need this?**
I would need this feature for a project that I am working on to stream geometry and textures in and out as needed to keep performance high.

**What would this solve?**
It would make it possible to have larger and more complex Scenes / Worlds in Godot.

**Example / Demo**
Here is a [link](https://cesiumjs.org/) to a project that makes heavy use of geometry streaming, texture streaming and LOD meshes. It is written in JavaScript and not made in Godot but does provide a good idea of what I am after.

**Comment by Zylann** [comment]
Which kind of streaming are you thinking about? Do you mean, unloading meshes if they are too far away, and load them back if they get close?

I'm asking this because I'm also implementing a terrain system, which may use a different streaming method that the one you would use for models.

For texture streaming it could use partial texture update in different ways
- Load textures partially in chunks to not stall the GPU with big uploads
- Load lower mips first, then higher ones in chunks using the feature described above

**Comment by HeadClot** [comment]
Hey - really sorry for the delay for the reply on this issue. Today has been really busy.

Currently I am using [grid maps](http://docs.godotengine.org/en/3.0/tutorials/3d/using_gridmaps.html) due to the lack of a built in terrain system into Godot 3.X.

Anyway here is the issue I am facing is that I am currently needing to page geometry and textures on the  meshes in and out as needed to keep performance high. I also need this to work in a multi player environment. You are right about physics and sounds. I am just not sure how to go about doing that.

**Comment by Calinou** [comment]
Support for LOD and texture streaming is planned in Godot 4.0.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
