### ISSUE TITLE
C# can't cast GetFont() to DynamicFont

### ISSUE THREAD

**Issue by Jarodwr** [godotengine/godot#17554]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Unable to cast Font to DynamicFont when using label.GetFont()

**Steps to reproduce:**
1. Create a label
2. Add a dynamic font to the label
3. Call label.GetFont() and try to cast the result to DynamicFont

**Minimal reproduction project:**
[monoCastFont.zip](https://github.com/godotengine/godot/files/1818596/monoCastFont.zip)

**Comment by PJB3005** [comment]
This seems to be an error in your code.

Your code:
```cs
public class LabelScene : Label
{
    public override void _Ready()
    {
        DynamicFont dynamicFont = (DynamicFont) GetFont("Code-Bold");
    }
}
```

with a font theme override on the label set to the dynamic font you want. The problem is that you're using the name of the font, not the name of theme variable. You want to use `"font"` in the case of label, like this:

```cs
public class LabelScene : Label
{
    public override void _Ready()
    {
        DynamicFont dynamicFont = (DynamicFont) GetFont("font");
        GD.Print($"{dynamicFont.Size}");
    }
}
```

This works perfectly fine.
