### ISSUE TITLE
Get an error when using StoreVar to Save a List in C#

### ISSUE THREAD

**Issue by Ron5s** [godotengine/godot#17565]
**Godot version:**
Godot 3.0.2 Mono Stable

**OS/device including version:**
Windows 7 and 10

**Issue description:**
Im trying to save a list in c# with the StoreVar() function. Its a list of Vector3 arrays. Im getting this error:

0:00:22:0269 - Attempted to convert an unmarshallable managed type to Variant. Name: 'List`1' Encoding: 21

Type:Error
Description: Attempted to convert an unmarshallable managed type to Variant. Name: 'List`1' Encoding: 21
Time: 0:00:22:0269
C Error: Method/Function Failed, returning: Variant()
C Source: modules\mono\mono_gd\gd_mono_marshal.cpp:593
C Function: GDMonoMarshal::mono_object_to_variant

**Comment by Hinsbart** [comment]
`File.StoreVar()` can only store Godot Variants and there's no marshalling for Collection types yet, so the exception is expected. So I'm re-tagging this as a feature request.

**Comment by Hinsbart** [comment]
As a workaround you can save it with `list.ToArray()`

**Comment by Ron5s** [comment]
@Hinsbart  Thank you for your help.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
