### ISSUE TITLE
Naming oddity under AcceptDialog node

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17573]
Godot 3.0.2

You can't name a node `HBoxContainer` if it's child of an `AcceptDialog`, even if the scene tree doesn't show any other child in the editor.
This probably happens because `AcceptDialog` internally creates a node of that name, which is quite an odd behaviour when experienced in the editor, even though I understand why it happens behind the scenes, as someone who saw the C++ source code.

Repro:
1) Create a `AcceptDialog`
2) Add an `HBoxContainer` as first child: notice it gets renamed `HBoxContainer2`.
3) You cannot rename it `HBoxContainer`

**Comment by Noshyaar** [comment]
Some more observation: at runtime, internal nodes get renamed to `@@some_integer` and you can rename `HBoxContainer2` to `HBoxContainer` just fine.

**Comment by reduz** [comment]
Not a bug, controls usually have built-in controls you can't see in the inheritance. Question is whether they should use some private naming or something.

**Comment by Zylann** [comment]
> at runtime, internal nodes get renamed to @@some_integer and you can rename HBoxContainer2 to HBoxContainer just fine. Relevant code:

This is what usually deals with the name occupancy. I don't understand why it's not the case here.

**Comment by bojidar-bg** [comment]
> I don't understand why it's not the case here.
Likely because the code applies to all nodes created in the editor process, not just those created manually / through script.

**Comment by dominiks** [comment]
I checked this in 3.2.1 and 3.2.2beta4 and can confirm this. The children of the ``AcceptDialog`` are in fact anonymously named ``@@2``, ``@@3`` and ``@@4``. You can add an element with the name ``HBoxContainer`` via script without any problems (adding another one with this name will result in the second element being renamed to ``@HBoxContainer@8``).

The problem also occurs when you add a ``Label`` and a ``TextureButton``. I think the problem here lies with the scene editor.
