### ISSUE TITLE
Add modality to popup dialogs in the editor

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#17580]
**Godot version:** Any

**OS/device including version:** Windows/Mac/Linux

**Feature description:**
It would be nice to have modality for popup dialogs (Settings, Open/Save, Import project, etc.) 

**Reasons:**
1) Mouse click outside current popup dialog makes the dialog disappear without any option to bring it back, other than opening it again. Which leaves an impression of memory leak and inconvinient and unconventional flow.
2) Keyboard input (Enter key e.g.) is captured by the parent window
E.g.:
* In project manager select any project in the list
* Hit import button
* Hit browse and try to navigate usign the adress bar (type in any sub directory name and hit Enter)
In the case one would expect to be navigated to the directory specified, but previously selected project is being opend instead.

Thus I think implementing the modality of dialogs would fix this issues (and any others yet unknown).

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(btw, the Project Manager bug was already fixed)
