### ISSUE TITLE
Expand onready keyword to export variables

### ISSUE THREAD

**Issue by DualMatrix** [godotengine/godot#17596]
# Why would it be useful

I often stumble upon the following problem when working with export vars:

I've got an _export_ var set up with a set and get function using _setget_. In the set function I would like to access the scene tree or emit a signal. 

The problem comes in when the node loads and the set function gets called for the first time with its default value, because the node isn't ready yet you can't access the scene tree and signals you send might not be received due to the connections not being set up. This is a mayor problem when using _export_ vars with _setget_ functions.

Making the _onready_ keyword work with _export_ variables would solve this issue since the set function should be called for the first time when the node is ready and thus everything you would want (Like access to children, correctly emitting signals or accessing the scenetree) is now available in the set function.

There's no real clean way to work around this this issue at the moment.

# How it would work

Adding the _onready_ before an _export_ variable would work the same as it does for regular variables, the value of the variable would be set on ready and not on load.

## It's a relatively simple addition

Since the _onready_ keyword already exists, expanding it to _export_ variables wouldn't be a big change since it wouldn't require extra keywords or features and the documentation would be easy as well. It would also be easy to understand since its just the same functionality as it as regular _onready_ variables.

**Comment by bojidar-bg** [comment]
Note that you can currently use onready + export, though in a weirder and bug-prone way:
```gdscript
onready export(NodePath) var other_node = get_node(other_node)
```

**Comment by arthurferrai** [comment]
I can't see a way that it could work if you add `tool` to the script

**Comment by razcore-art** [comment]
Yeah, the way I solve it is to test if the nodes I'm accessing in settes/getters are ready with `has_node`. Out of curiosity, have you tried
```gdscript
export(int) onready var a = 3 setget _set_a
```
or something similar? because this code doesn't give any errors, I just don't know what's the behavior cause there's no documentation. Karroffel says it the value gets overwritten and `onready` is unpredictable here, but don't remember the details, it was a late night chat

**Comment by DualMatrix** [comment]
@razcore-art The onready keyword doesn't seem to do anything in your case.

**Comment by arthurferrai** [comment]
I think the main problem is the editor inspector needs to call `set`/`get` functions while the project isn't even running (so no scene tree is created).

**Comment by DualMatrix** [comment]
@arthurferrai 

Now I'm not a godot expert but in theory the inspector could wait to call `set`/`get` of `onready export` values until after the node is ready right?

**Comment by vnen** [comment]
The `onready` keyword simply postpone the initialization to the `_ready()` function (instead of the `_init()` function that happens by default). The `export` keyword is about serialization, i.e. the data is saved in the scene and set into the script after instancing it (right after `_init()` is called).

So both `onready` and `export` are a syntax sugar for what is already available in other ways.

For the `export` keyword be aware of the `onready`, we'd have to add a way to make the values not set at loading and wait until the node is actually ready to set it. It would require a whole new mechanism to deal with it, storing the deserialized values in a temporary storage or something.

This is also gets into the unintuitive territory. It's harder to tell what the behavior will be. Some people say that the export should not even trigger the setter function (see #6916).

**Comment by DualMatrix** [comment]
Yeah any solution would at least be a little wonky. To me this:

> we'd have to add a way to make the values not set at loading and wait until the node is actually ready to set it

seems to be the best way but it would indeed require some work.

In any case the editor should make clear if it's possible or not, unlike how it is now where the editor accepts it but the onready part just doesn't seem to do anything.

**Comment by SuperSamus** [comment]
I think that the source file that has to be modified is https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_parser.cpp

**Comment by KoBeWi** [comment]
Closing in favor of this proposal: https://github.com/godotengine/godot-proposals/issues/325
