### ISSUE TITLE
Add a 'plugin' keyword similar to 'tool'

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#17592]
## The problem

While developing plugins you have to add the the `tool` keyword to every script. The problem is that if you open an scene file belonging to the plugin, it runs and if you save it, you are effectively saving a runtime state of the GUI (lists populated, controls enabled/disabled and so on). Because of that I'm having to remove/re-add `tool` many times.

I know there is `Engine.editor_hint`, but I think that allows only to check if your code is running on the editor (both for editing and a running plugin) instead of as part of a running project.

## The proposal

Adding a new keyword (let's say `plugin`) that you can use instead of `tool` that enables the script only if it's part of _a running plugin_. In other words, these would be the semantics for all cases:
- No keyword => Run script only if the project is actually running
- `plugin` keyword => Run script only if it has been loaded as part of a running plugin
- `tool` keyword => Run script everywhere

I think I can implement this myself if is makes enough sense and there's no a good way of achieving it currently.

**Comment by Zylann** [comment]
I design my plugin's UI through the editor, and I thought of this as well. I likely avoided it by chance so far since my UIs basically do nothing if they aren't *told* to do so by their owner (which doesn't exist within the edited scene so the logic stays idle), but I may end up having the same problem in the future...

Initially I wanted to have a way to check if the scene root was the edited scene root and then discard any logic, but that would be quite cumbersome in addition to the `is_editor_hint()`...

**Comment by vnen** [comment]
I bumped into something like this too. I have to carefully not save the scene or delete everything from an ItemList that was populated by the script before saving. I also have issues with stuff that needs the plugin reference which is not available in design-time.

Signals aren't really a problem unless you connect them as persistent (which wouldn't make much sense anyway).

The alternative is not to use the tree callbacks (`_ready`, `{enter,exit}_tree`) to avoid anything being called in editor. But this doesn't look idiomatic to me, it's just a workaround. I add and remove stuff from the tree in many places and having to remember to call the initialization function every time is error-prone (especially because it's not need for game scenes).

I would be satisfied by something to `editor_hint` that says whether the scene is being edited or running in the editor. I like the `plugin` keyword though, it looks cleaner and avoids a workaround.

**Comment by RandomShaper** [comment]
@Zylann, I agree that you can split responsibilities in such a way that you avoid the issue, if I have got your point. Probably doable in every situation, but for simple plugins you may prefer to mix UI and logic.

**Comment by RandomShaper** [comment]
Now I'm wondering if it wouldn't be better to let plugin writers have something like `tool # plugin` in order to preserve compatibility.

**Comment by vnen** [comment]
I would just allow both `plugin` and `tool` for plugins. I imagine that some scripts might run both as plugins and as editor tools.

I'm still not sure if a new keyword is the best solution (I'm always wary of adding stuff to GDScript). I can't think of anything else, though.

**Comment by bojidar-bg** [comment]
We might have it as `tool(PLUGIN)`, similar to `export(int, ENUM)`

**Comment by Zylann** [comment]
I'm now having this problem in a constraining situation.

I have a dialog window that contains a viewport, and I assign its ViewportTexture to a TextureRect in the window.
And now I end up saving a ViewportTexture inside the .tscn file.

**Comment by willnationsdev** [comment]
@Zylann The [EditorInterface class has a `get_edited_scene_root()` method](http://docs.godotengine.org/en/latest/classes/class_editorinterface.html#class-editorinterface-get-edited-scene-root) which sounds like it would give you exactly what you were looking for. No? If you emit a signal that connects to your `EditorPlugin`, then it can tell your node what's going on.

**Comment by Zylann** [comment]
@willnationsdev but that's the problem. It's on `EditorInterface`, which I can't access and test from any node of my tool's scene...

**Comment by willnationsdev** [comment]
Would you prefer that `get_editor_interface` be accessible to every Node, but return null for non-tool scripts? That'd be cool...

**Comment by Zylann** [comment]
@willnationsdev this is not an option because I can't access the EditorPlugin in the first place. There might be a way by changing the `handles` function of my own plugin to handle every possible node but that's incredibly tedious and hacky.

**Comment by avencherus** [comment]
Been using the following.  So far haven't had issues with it since I call it in the root node scripts that need it, but maybe it has holes in it.
```
func scene_being_edited(scene):
	return scene == get_tree().edited_scene_root
```

**Comment by Zylann** [comment]
OMG, for some reason I thought this was a boolean. That will improve my utility function to get that info, then :)
```gdscript
static func is_in_edited_scene(node):
	if not node.is_inside_tree():
		return false
	var edited_scene = node.get_tree().edited_scene_root
	if node == edited_scene:
		return true
	while node.get_parent() != null:
		node = node.get_parent()
		if node == edited_scene:
			return true
	return false
```

**Comment by avencherus** [comment]
`is_a_parent_of()` works in some of these situations too, and I've been able to avoid those while loops.  If it's safe to do so you might even just write it like: 

```
# Haven't tested this.  X)
static func is_in_edited_scene(node):
	var edited_scene = node.get_tree().edited_scene_root
	return node.is_inside_tree() and (node == edited_scene or edited_scene.is_a_parent_of(node))
```

**Comment by Zylann** [comment]
Close :)
Tested this:
```gdscript
static func is_in_edited_scene(node):
	if not node.is_inside_tree():
		return false
	var edited_scene = node.get_tree().edited_scene_root
	if node == edited_scene:
		return true
	return edited_scene.is_parent_of(node)
```

**Comment by Zylann** [comment]
I just read in https://github.com/godotengine/godot/pull/23651#discussion_r241786031 there is a `get_tree()->is_node_being_edited()`, which is however not exposed to GDScript (also I wonder why it's a SceneTree method Oo)

**Comment by avencherus** [comment]
The wheel reinvented.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by aftamat4ik** [comment]
> Close :) Tested this:
> 
> ```gdscript
> static func is_in_edited_scene(node):
> 	if not node.is_inside_tree():
> 		return false
> 	var edited_scene = node.get_tree().edited_scene_root
> 	if node == edited_scene:
> 		return true
> 	return edited_scene != null and edited_scene.is_a_parent_of(node)
> ```

works for me. c# version:
```c#
if(SourceNode.IsInsideTree() == false)
    return false;

var EditedScene = SourceNode.GetTree().EditedSceneRoot;
if(SourceNode == EditedScene)
    return true;

return EditedScene != null && EditedScene.IsAncestorOf(SourceNode);
```
