### ISSUE TITLE
3D raycasting does not provide UV coordinates or triangle index

### ISSUE THREAD

**Issue by darkf** [godotengine/godot#17665]
**Godot version:**

3.0.2

**OS/device including version:**

N/A

**Issue description:**

Raycast results only return the hit position and normal, and does not give the hit UV/UV2 coordinates or the triangle index.

This is very useful and basic information to have, and it's not allowing me to achieve effects I'd like to.

[Unity has both](https://docs.unity3d.com/ScriptReference/RaycastHit.html) (textureCoord, textureCoord2, triangleIndex), barycentric coordinates in the triangle, and more.

**Steps to reproduce:**

Add UV/UV2 coordinate and triangle index to raycast results. Consider barycentric coordinates as well (as they're likely used to compute the UV coordinates anyway.)

**Comment by Zylann** [comment]
For this to work, you would need 1) the physics engine to support extra data in mesh colliders specifically, and 2) either use the exact same mesh for rendering and physics, or generate a low poly version that retains the same data

**Comment by darkf** [comment]
Yeah. It might be worth looking into how Unity, Three.js and Babylon.js (among other rendering engines) handles this. (The latter two don't even include physics engines.)

With Godot it could at least be done easily with Bullet.

Once you have the tri index you could compute the UVs from that.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
