### ISSUE TITLE
Add flag manipulation utility methods to GDScript

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#17708]
**Godot version:**
Godot 3.x

**Issue description:**
I feel like the use of flag integers is not all that intuitive to beginner programmers, nor is seeing bitwise operators terribly readable, especially if they get more complicated.

I think GDScript could benefit from having some simple global utility methods for interacting with integer flag variables.

Examples:

    var flag
    
    # flag = fset(flag, CONST)
    func fset(p_flag, p_value):
        p_flag |= p_value
        return p_flag

    # flag = fclear(flag, CONST)
    func fclear(p_flag, p_value):
        p_flag &= ~p_value
        return p_flag

    # if ftest(flag, CONST):
    func ftest(p_flag, p_value):
        return (p_flag & p_value) == p_value

    # flag = ftoggle(flag, CONST)
    func ftoggle(p_flag, p_value):
        p_flag ^= p_value
        return p_flag

On a side note, if people like the idea, would it be possible to somehow pass the integer flag by reference so you don't have to assign the return value just to get the changed data? Not sure if you can do that for primitive values in GDScript...

What do you all think?

**Steps to reproduce:**
Add the related methods to the `gdscript_functions` content.

**Comment by willnationsdev** [comment]
Well, there is a bit of a ambiguity when it comes to the word "flag". A bool, true/false, you're already familiar with I'm sure. A boolean flag is simply a boolean value that someone is using to "flag" when a particular state has been reached. Used in that manner, the terms are largely interchangeable.

Now, an integer flag, typically associated with enums, is a completely different concept. It is effectively using the individual bits of a 4-byte integer value to store up to 32 booleans in one variable, and then to be able to check any of their state, even in combination, with a single calculation. Interactions with the integer's bits are made using bitwise operators (examples of which are illustrated in the opening post).

Here is an [in-depth illustration](http://www.alanzucconi.com/2015/07/26/enum-flags-and-bitwise-operators/) of them in action in Unity. 

And here is a section in the docs illustrating how to [export an enum flag](http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#exporting-bit-flags) in GDScript.

**Comment by romlok** [comment]
Suggestion:
```GDScript
bitflag AttackType {
    ATTACK_PHYSICAL,
    ATTACK_FIRE,
    ATTACK_COLD,
    ATTACK_ACID,
}
# Similar to an enum, this would create:
const ATTACK_PHYSICAL = 1
const ATTACK_FIRE = 2
const ATTACK_COLD = 4
const ATTACK_ACID = 8
# And the AttackType object, where you can reference the values
var my_attack = AttackType.ATTACK_PHYSICAL | AttackType.ATTACK_FIRE

# BUT ALSO!
# Can be instanced to expose meaningfully-named methods
my_attack = AttackType.new()
my_attack = my_attack.set(ATTACK_PHYSICAL)
my_attack = my_attack.clear(ATTACK_FIRE)
my_attack = my_attack.toggle(ATTACK_ACID)
var is_frosty = my_attack.has(ATTACK_COLD)
# And maybe
if ATTACK_FIRE in my_attack:
    burn_stuff()
```

**Comment by willnationsdev** [comment]
Would be especially good if the set/clear/toggle methods were vararg methods, letting you just provide a list of the constants, or even another bitflag object as a parameter. Would also be nice to be able to use the set method as part of a vararg constructor for the new() function, though I'm. It sure if that can be done.

Loving your take on this @romlok. This looks much, much cleaner than what I had been thinking of.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
