### ISSUE TITLE
Itertools Python library for GDScript

### ISSUE THREAD

**Issue by Ocete** [godotengine/godot#17707]
**Issue description:**
Hey Godot people!

I'm a student interested in working on a little project for Godot during the Google Summer of Code (more info here: https://summerofcode.withgoogle.com/ ). The project would consist of implementing Itertools Phyton library, which has different utilities to work very efficiently with iterators, for Godot. The original idea comes from this issue #9264. Itertools official documentation can be found here: https://docs.python.org/3/library/itertools.html

Now the question is, do you think it would be useful to have these methods in GDScript? Of course, this project has no sense if they aren't useful.

Additionally, I was thinking about other related features that could be useful too, as the Slicing in Python (https://docs.python.org/2.3/whatsnew/section-slices.html). Would that one be useful? 

Finally, do you have any other ideas for functionalities from other programming languages that you miss when you work on GDScript?

Thanks!

**Comment by vnen** [comment]
This probably have a limited utility, that's why we ended up removing from the ideas list. Well, I know now it's too late to propose anything for GSOC, but if you did submit a proposal with this project it will be evaluated by its own merit like every other proposal.

In any case, the GitHub issue tracker is not the place to discuss that and the original feature proposal is already tracked by #9264. So I'll archive this one.
