### ISSUE TITLE
Follow the steps of godot website to compile for android, but didn't work

### ISSUE THREAD

**Issue by marcusViniciusMP** [godotengine/godot#17710]
**Godot version:**
2.1.4

**OS/device including version:**
Thinkpad X220, Lubuntu 17, 64bits

**Issue description:**
i follow this:

http://docs.godotengine.org/en/3.0/development/compiling/compiling_for_android.html

and i got this:

scons platform=android target=release
scons: Reading SConscript files ...
Godot Android!!!!! (armv7) (with neon)
scons: done reading SConscript files.
scons: Building targets ...
[  4%] Compiling shared ==> platform/android/os_android.cpp
sh: 1: /home/marcus/android-ndk-r13b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: not found
scons: *** [platform/android/os_android.os] Error 127
scons: building terminated because of errors.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by marcusViniciusMP** [comment]
forget ir was my mistake sorry !

**Comment by austinirvine** [comment]
@marcusViniciusMP How did you fix it?

**Comment by emocanmimocan** [comment]
i have same problem

**Comment by ulvido** [comment]
same here. how to fix. what is ir?

**Comment by Calinou** [comment]
@ulvido This issue tracker is now only used for bug reports. Please ask on one of the other [community channels](https://godotengine.org/community) instead.

**Comment by ulvido** [comment]
ok figured it out. here is a bug report. if you installed ndk from android studio on linux system scons cant figure out paths correctly. let me explain. 

installed ndk from android studio default installer. it puts the ndk inside sdk folder (side by side)

![2020-09-04 18-47-12 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/92258336-56d2e180-eedf-11ea-8ec3-ef233b9fb04a.png)

so I add paths to my environment as explained [here](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_android.html#setting-up-the-buildsystem). here is my .zshrc

![2020-09-04 18-53-36 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/92260151-250e4a80-eee0-11ea-94c3-2d5426f79905.png)

but scons still cant find the ndk. why? because android studio installs ndk in a version folder. like this:

/Android/Sdk/ndk/**21.31241**/here-are-ndk-files

ok no problem. I will give the path of the version number and everything will be ok. like this:

![2020-09-04 19-00-42 ekran görüntüsü](https://user-images.githubusercontent.com/27722274/92260766-183e2680-eee1-11ea-87d0-769c8b39f8b7.png)

this time first error is gone. able to find ndk but compile failed 1 step later. the error was:

...Android/Sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: not found

but I gave the correct path it should look with the path in the environment

.../Android/Sdk/ndk/**21.31241**/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++

I dont know maybe that path is harcoded or something. I overcome the problem with copyin all files one folder above (under ndk folder) and deleted the version folder. and gave the path in the first picture.

.../Android/Sdk/ndk/here-are-ndk-files
