### ISSUE TITLE
Animation with invalid track path errors on wrong (valid) track

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#17718]
**Godot version:**
Master (01bb39a), likely affects 3.0 too but untested

**OS/device including version:**
Mageia 6 Linux x86_64, but not system-specific.

**Issue description:**
Whenever an animation has an invalid track path (e.g. `Sprite:visibletypo` instead of the valid `Sprite:visible`), it will output an error mentioning the track *above* the invalid one. Likely a simple off-by-one error in the code that triggers this error.

For example this animation:
![screenshot_20180323_120119](https://user-images.githubusercontent.com/4701338/37825946-ea269000-2e91-11e8-8640-01080928d25f.png)
Will trigger this error:
```
ERROR: _animation_update_transforms: Failed setting key at time 0 in Animation 'New Anim' at Node '/root/Node2D/AnimationPlayer', Track 'Sprite:modulate'. Check if property exists or the type of key is right for the property
   At: scene/animation/animation_player.cpp:622.
ERROR: _animation_process_animation: Failed setting track value 'Sprite:modulate'. Check if property exists or the type of key is valid. Animation 'New Anim' at node '/root/Node2D/AnimationPlayer'.
   At: scene/animation/animation_player.cpp:432.
ERROR: _animation_process_animation: Failed setting track value 'Sprite:modulate'. Check if property exists or the type of key is valid. Animation 'New Anim' at node '/root/Node2D/AnimationPlayer'.
   At: scene/animation/animation_player.cpp:432.
ERROR: _animation_process_animation: Failed setting track value 'Sprite:modulate'. Check if property exists or the type of key is valid. Animation 'New Anim' at node '/root/Node2D/AnimationPlayer'.
```
(the :432 error then loops over and over again as the animation loops)

**Steps to reproduce:**
Run attached project.

**Minimal reproduction project:**
[animplayer_track_warning.zip](https://github.com/godotengine/godot/files/1841244/animplayer_track_warning.zip)

**Comment by chanon** [comment]
I was just about to create this issue myself!

I would like to add that, it doesn't report the track above, rather it reports the *first* track in the animation.

**Comment by Alexander-Alekseev** [comment]
I suppose that caching is a problem.

This -
https://github.com/godotengine/godot/blob/098c7ba4f9c49b472b9417819144378081996874/scene/animation/animation_player.cpp#L239
returns the same `node` for both tracks plus empty/not valid `resource`.

That's why this -
https://github.com/godotengine/godot/blob/098c7ba4f9c49b472b9417819144378081996874/scene/animation/animation_player.cpp#L244
returns the same `id` for both tracks.

That's why `key` is the same -
https://github.com/godotengine/godot/blob/098c7ba4f9c49b472b9417819144378081996874/scene/animation/animation_player.cpp#L261-L262
and `node_cache_map` has only one element. When this first and only element gets created, `path` gets set to the path of the first track:
https://github.com/godotengine/godot/blob/098c7ba4f9c49b472b9417819144378081996874/scene/animation/animation_player.cpp#L270-L273
For the second and further tracks the following code gets executed:
https://github.com/godotengine/godot/blob/098c7ba4f9c49b472b9417819144378081996874/scene/animation/animation_player.cpp#L265-L268

That's why all `path`s of all `node_cache` elements point to the first track path.

Maybe the root cause is in `Node::get_node_and_resource` method?

**Comment by reduz** [comment]
animtree is here:
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp
