### ISSUE TITLE
Networking classes do not handle cookies

### ISSUE THREAD

**Issue by notamonopoly** [godotengine/godot#17711]
**Godot version:**
3.0.2 Stable Official

**OS/device including version:**
Windows 10

**Issue description:**
I do not see any method for dealing with cookies using HTTPClient or HTTPRequest in godot. Before I can make rest calls to a third party site I need to authenticate users and retrieve an authorization key. This is done by taking the entered credentials and posting them to a webpage. This page then returns a redirect response and sets session info via set-cookie in the header. The page it redirects to takes the session info that was set in the cookie and generates an authorization key which is returned in the final response. I have to get this key in order to make any further calls.

I am currently doing this without issue on my website using php and curl, but I am trying to do this in godot without success.

**Steps to reproduce:**
Have a webpage that sets a cookie and redirects via the location header to another page that displays the cookie information (for the sake of testing) in the body. Call the first page from godot using either HTTPRequest or HTTPClient and you will not see the cookie information as it was not passed along on the redirect.

**Comment by bojidar-bg** [comment]
Note that this is likely the original cause of #6434.

**Comment by Faless** [comment]
@notamonopoly Well, for now you can (as inconvenient as it is) set `max_redirects = 0`.
You will receive a `_request_done` signal with `RESULT_REDIRECT_LIMIT_REACHED`, empty body, but the headers set.
In the `headers` you will find the `Set-Cookie` directives from the server and the `Location` directive to where to go.
You can then set read cookie value yourself. E.g.
```gdscript
extends HTTPRequest

func _ready():
	max_redirects = 0
	connect("request_completed", self, "_done")
	request("https://my-website.com", PoolStringArray([]), false, HTTPClient.METHOD_GET)

func _done(result, response_code, headers, body):
	if result == RESULT_REDIRECT_LIMIT_REACHED:
		print("Getting location and cookies")
		var loc = ""
		var cookies = PoolStringArray()
		for h in headers:
			if h.to_lower().begins_with("location"):
				loc = h.split(":", true, 1)[1].strip_edges()
			elif h.to_lower().begins_with("set-cookie"):
				cookies.append(h.split(":", true, 1)[1].strip_edges().split("; ")[0])
			print(h)
		print(response_code)
		print(loc)
		print(cookies)
		# Reset max_redirects to infinity
		max_redirects = -1
		var cookie_header = "Cookie: %s" % cookies.join("; ")
		print(cookie_header)
		if loc != "":
			# Make redirected request with cookie header
			request(loc, PoolStringArray([cookie_header]), false, HTTPClient.METHOD_GET)
```

That said, maybe some cookie handling functions would be useful, but getting them right might be tricky.

**Comment by notamonopoly** [comment]
@Faless Thanks for the example, it's cleaner than my own implementation. I had attempted to manually follow the url previously but kept getting a 404 response. What I didn't realize is that redirects by default are GET and I was trying to call it with POST. One I switched the method it worked fine. So while it would be nice to have cookie handling built in, it isn't a lot of work to just deal with manually.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
