### ISSUE TITLE
Add a method to find ArrayMesh's surface or blendshape index by its name

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17749]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
Currently, `Array` supports resolving the name of a surface or blendshape by its index, but not vice versa.

As it's likely that users would recognize a material surface or blendshape by its name, rather than by the index, it'd be better to add an option to easily resolve such an index from a name which can be entered by a user from the inspector UI.

In comparison, `Skeleton` already supports a two way resolving between bone names and their indexes, so it'd make sense to add a similar level of support for other elements from a consistency standpoint also.

**Comment by BastiaanOlij** [comment]
Not sure if finding the blend shapes index makes sense as this is just an array of names, but I needed the feature to find a surface by its name so: #20532

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
