### ISSUE TITLE
Expose load/import methods for use with file from user directory

### ISSUE THREAD

**Issue by bartosz-m** [godotengine/godot#17748]
**Godot version:**
3.0.2

**Issue description:**

I was trying to import audio "resources" from user directory using `user://` but I could find how to do that from gdscript. `load` functions generates error for ogg,wav,opus

    No loader found for resource: user://sample.ogg

I can successfully load file content as a `PoolByteArray` but I wasn't able to find a way to create from it usable resource. 
I'm guessing that there are method that could import those file as resource at runtime, but are living in c++, so maybe they could get bindings for the gdscript side?

**Steps to reproduce:**
`var user_sample = load("user://sample.ogg")`

**Comment by LinuxUserGD** [comment]
You could try to import the file under ```res://``` and move the audio file together with the ```.import``` file to user://.
This may require editing the ```.import``` file manually.

**Comment by bartosz-m** [comment]
Those files are generated at runtime so i don't think it is possible to import it that way (I'm new to godot so correct me if I'm wrong). But could it be possible to manually generate import files?

**Comment by LinuxUserGD** [comment]
Ok, think that this is impossible now. The .import files are generated from the Godot Editor while tragging a file into the project directory.
E. g. https://github.com/godotengine/godot-demo-projects/blob/master/2d/physics_platformer/music.ogg.import
But it seems like the .import  file links to a .oggstr ressource that is only available on runtime.

**Comment by bartosz-m** [comment]
Tell me if I understand correctly. Importing and resource generation is implemented as part of editor functionality and not game engine so it cannot be done at the runtime?

**Comment by hubslave** [comment]
In v3 you can't add any resource without first importing it (a process that loosy re-compresses the asset and put's it in the .import folder) by design and from what I've seen the authors won't implement the direct access to assets as was the norm in v2 for no good reason they could give ...
In addition they are ignoring major bugs in the import system and not even notifying the users of them - for example: https://github.com/godotengine/godot-docs/pull/1256 & https://github.com/godotengine/godot/issues/17726

Let's see how long are they going to take to fix or notify the developers about that "little" bug. and don't get me started on some other "features" they don't intend to even consider fixing ...

**Comment by LinuxUserGD** [comment]
Is it possible to initialize the import procedure at runtime via GDNative so the generated ```.import``` files could be saved in the ```user://``` directory? Not sure about shortcuts...

**Comment by mrcdk** [comment]
What you are trying to import isn't a resource that godot recognizes. Resources for godot are files that have been imported via any of the import mechanims there are and have extra information and metadata that the original file doesn't have. 

For example, a imported .png will not only import it with whatever import options you give it but it will automatically compressed and prepared for the different compress formats you select in the project settings. It doesn't modify the original .png file.

If you need to load a external file a successful loading will depend on what the file is but you will have to do it manually. The old 2.x import system wouldn't let you load it either.

You can load an external ogg file like:
```gdscript
func load_ogg(file):
	var path = "Z:\\godot_projects\\%s.ogg" % file
	var ogg_file = File.new()
	ogg_file.open(path, File.READ)
	var bytes = ogg_file.get_buffer(ogg_file.get_len())
	var stream = AudioStreamOGGVorbis.new()
	stream.data = bytes
	$AudioStreamPlayer.stream = stream
```

**Comment by bartosz-m** [comment]
This is really helpful piece of code `stream.data =`. Base on that I was able to load .wav file. Thanks!

**Comment by hubslave** [comment]
> @mrcdk For example, a imported .png will not only import it with whatever import options you give it but it will be automatically compressed and prepared for the different compress formats you select in the project settings. It doesn't modify the original .png file.

You should definitely double check you're comment because right now I can't use PNG files without importing them, and when I do using "Compress Lossless (PNG)" method the result is a Loosy compressed PNG file with **data and quality lost during the import process** ...

**Comment by LinuxUserGD** [comment]
@bartosz-m Is this issue solved now? Maybe it's better to change the title to make clear if it's a feature request (@hubslave comment)

**Comment by bartosz-m** [comment]
I've been able to overcome my problem and it looks like the main issue was different than that in the title I wrote. Problem was **missing documentation** for `data` property of audiostreams.
Now I've got a question should I change title of this issue or create new one.

**Comment by LinuxUserGD** [comment]
@hubslave There isn't just one solution for all assets, e. g. a video can't be compressed like a png but needs much space in the exported .pck
So it's better to seperate documentation issues from issues in the engine's code.

And @mrcdk fixed @batosz-m problem within two hours (--> documentation issue)


Image artifacts should be an engine's issue.

And dynamically importing assets (media/ meshes) is a feature request, because Godot doesn't support it yet (--> Waiting for Godot)


Conclusion: Better close this issue and create seperate ones

**Comment by bartosz-m** [comment]
Before closing this issue I would like to ask where create new one about missing documentation: here or on [godot-docs](https://github.com/godotengine/godot-docs)?

**Comment by LinuxUserGD** [comment]
godot-docs (not engine code specific)

**Comment by bartosz-m** [comment]
As advised I'm closing this issue
