### ISSUE TITLE
EditorPlugins should be able to display modal progress bars

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#17763]
Godot 3.0.2

EditorPlugins that can execute lengthy tasks need to be able to display modal progress bars, similar to those we have for importing resources or saving scenes.
I currently need this in my terrain plugin.

Note 1: Godot might execute tasks like this as part of the plugin task. For example, if the task generates textures, Godot may import them at the same time.

Note 2: the lengthy task may, or may not involve threads. For example, a part of the operations might involve saving big textures to disk (thread), or the GPU can be used spreading over multiple frames (no thread).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by hsandt** [comment]
I found two possibly matching proposals that were opened in the meantime:
https://github.com/godotengine/godot-proposals/issues/14602
https://github.com/godotengine/godot-proposals/issues/14255
