### ISSUE TITLE
Provide interfaces for common Node API functionalities in C#

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#17791]
**Godot version:**
`master` / dad47d8876de45132226985dbbd079e060f6facc

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:** _(This issue is a feature request)_
It'd be useful if we provide C# interfaces for various functionalities of `Node` class, like `INodeSelector` for such methods like `GetNode`, `GetChildren`, and so on, or `IGrouped` for methods like `AddToGroup`, `RemoveFromGroup`, and such.

Aside from making the overall design more comforming to the OOP principles, it can also bring some actual benefits when combined with C#'s extension method feature.

For example, if I want to use Godot's node group feature as a tagging system, I can define `ITagged` which inherits from `IGrouped` as mentioned above. Then, I can write all the necessary implementation code as extension methods to the said interface, in which case I can just make any arbitrary node to have a tagging feature without having to write any additional code.

It's also a relatively safe change, since there'd be no actual implementation or behavioral changes involved to add this feature to the current `Node` API.

**Comment by mysticfall** [comment]
According to @paulloz, it seems that it can't be done with the current glue generation process we have, so in that case, I guess #15548 would be a prerequisite for this issue.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
