### ISSUE TITLE
Setting member OS.window_size behaves differently on OSX

### ISSUE THREAD

**Issue by acfaruk** [godotengine/godot#17817]
**Godot version:**
3.0.2

**OS/device including version:**
Only on OSX

**Issue description:**
Setting the member OS.window_size seems to call the _draw method after it finishes. This only happens on OSX though. Calling the same method on a Windows machine doesn't do this.

**Steps to reproduce:**
Create a script with a _ready() method which sets OS.set_window_size to something.
Also create a _draw method to step into. Debug the program and step into the assignment. On OSX it will jump to the _draw() method while on Windows it will not.

**Reproduction project:**
[gd-snake-0.1.zip](https://github.com/godotengine/godot/files/1855721/gd-snake-0.1.zip)

**Comment by bruvzg** [comment]
`force_redraw()` call on resize was added in #9836 to fix #9546.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
