### ISSUE TITLE
Add method to reverse tween

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#17838]
An option to reverse a tween to tween back to the initial value(s) would be great.

**Comment by girng** [comment]
+1, just ran into this

how i do a "reverse tween" (really just going back to the initial value, not a full reverse)
```
	var previous_position = global_position
	attack_tween.interpolate_property(self, "global_position", global_position, attack_who.global_position, 0.2, 1, 1)
	attack_tween.start()
	yield(attack_tween, "tween_completed")
	attack_tween.interpolate_property(self, "global_position", global_position, previous_position, 0.2, 1, 1)
	attack_tween.start()
```

seems a bit verbose, however.. it does work great..

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(btw 4.0 will introduce [overhauled Tweens](https://github.com/godotengine/godot/pull/41794), which allow for very easy chaining, so this should be possible manually without much problem)
