### ISSUE TITLE
Godot text editor lacks theme options

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#17873]
- [ ] Built-in constant color
- [ ] User defined constant color
- [x] Function declaration color
- [x] Function call color
- [ ] Function argument color
- [ ] Class name color
- [ ] Possibility to italic or underline

But mainly the separation between function call and declaration.
Because this
![unclear](https://user-images.githubusercontent.com/18586380/38147674-afa5d13c-3429-11e8-9fe9-a11ffd836bd2.png)
Is not as clear as this
![clear](https://user-images.githubusercontent.com/18586380/38147679-b5b36396-3429-11e8-81ef-59c88eec943f.png)

**Comment by Calinou** [comment]
This is partially implemented thanks to https://github.com/godotengine/godot/pull/18183 – function definitions can now be colored separately from function calls.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
