### ISSUE TITLE
Visualscript property dragging

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#17874]
**Godot version:** 3.0.2.stable.costum_build

**OS/device including version:** Linux Mint 18.3

dragging properties with/without Ctrl should be switched

I think it would be more intuitive to drag a get-node without pressing Ctrl, since you want to put the value into the script
and to drag a set-node with pressing Ctrl, since you want to set (control) the value through the node.

now it's the other way around, could you switch it?
right-click-drag would also work well for set.

This property-drag-system could also be useful in gdscript and native script.
Properties would be a better name for "Inspector", it just sounds like a tool.

**Comment by fire** [comment]
Dragging a node from the properties searches functions, while holding control gets a reference to the node.

Is this acceptable?

**Comment by TrickMe** [comment]
My original intention was to switch the drag and Ctrl-drag behavior when dragging a property from the Inspector to the script. It's more intuitive and easier to get used to.

Think of it this way:
In the Windows Explorer, if you drag a file to another destination, you perform the default action.
If you drag a file with the right mouse button, you have the choice to ether copy, move to or create a link in the destination.
Dragging -> simple
Dragging + ctrl / right mouse dragging -> advanced

**Getter / Reference when dragging a Inspector property / Node
(the expected action with most graphical UIs)
Setter / Advanced selection while holding control / when dragging with the right mouse button (if possible)**

I like your approach to drag a node from the scene tree to speed up access to properties and functions, but I would also switch reference and search functions.

Sorry, but I'm not good at explaining things.

**Comment by DavidCambre** [comment]
wanted to reference #28226
To me it feels good the way it is. By default you try to set something on a node end get some value from the script.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
