### ISSUE TITLE
Allow users to select, drag, and drop text with a mouse within the script editor

### ISSUE THREAD

**Issue by Two-Tone** [godotengine/godot#17881]
**Godot version:**
3.0.2

**OS/device including version:**
Win 7

**Issue description:**
In almost every graphical program I've ever used where you can edit text I've been able to drag and drop text around. The only two programs I can think of that don't have this feature are Godot's script editor and Notepad. 

It's such a standard feature that it seems strange and out of place to not have it.  Plus there are users, like me, who only have 1 fully working hand, so we try and minimize the need to swap between mouse and keyboard as doing that is slow.

**Comment by girng** [comment]
wait, you mean like dragging code blocks, or individual characters/words in the editor?

**Comment by Two-Tone** [comment]
Anything that is text.  You can cut and paste, but thats much slower than
drag and drop.

Right now if I try to drag and drop, instead of the expected behavior, I
just start a new selection of text.

**Comment by girng** [comment]
"Fix Indent, eh" lol yeah. ty for the gif!

**Comment by Two-Tone** [comment]
Thanks for making the gif, Bojidar, and sorry girng for not being
descriptive enough.

**Comment by girng** [comment]
@Two-Tone no problem, im just very talkative on github, i was just clarifying ^^

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
