### ISSUE TITLE
Visual Problem with Gridmaps

### ISSUE THREAD

**Issue by ArgentArts** [godotengine/godot#17898]
Godot v3.0.2

Windows 10, GeForce 1070

There's an issue with the Gridmap node not displaying the correct geometry when you go to place it in the viewport IF you have more than one Gridmap node in your scene.

- Create two Mesh Libraries with different geometry in both
- Create a new scene with a Spacial node
- Create a child node under Spacial that is a Gridmap (name it as you like, such as Gridmap1)
- Load the first Mesh Library into your first Gridmap
- Create a second Gridmap as a child of Spacial (name it as you like, such as Gridmap2)
- Load the second Mesh Library into your second Gridmap
- Select the first Gridmap and the first object and place a few in the viewport
- Select the second Gridmap and the first object and go to place one in the viewport

When you do this, you should notice that the viewport displays the first object from the FIRST gridmap (Gridmap1), but places the object from the second gridmap (Gridmap2) when you click. So, the function is correct (the correct object is placed), but the display is incorrect (the first object is displayed).

I am using multiple Gridmaps for two reasons - 1) to better categorize my geometry and 2) when I use another Gridmap, it allows me to actually "overlap" geometry. #2 is important to keep as it allows me to use Gridmaps to quickly place items in my game by "brushing" them into place. So, I don't want to lose the functionality of #2, but I definitely need to see the object I am placing, especially if I need to rotate it.

Thanks.

**Comment by SilverSurfer1221** [comment]
Additional Info:

This problem happens if you select the geometry that is in the same "slot". For example, if you select the first object in Gridmap1 and place a few in the viewport, then select the first object in Gridmap2, then the viewport will display the geometry from Girdmap1. However, if you go back to Gridmap2 and select the second object (or any other object) then the correct object will be displayed in the viewport. If you select the second object in Gridmap2, place a few, and then go to Gridmap1 and select the second object, then the incorrect object will be displayed. 

It does not matter what the names of the objects are. It seems that Godot gets confused and displays the object from the same "slot", regardless of name.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
