### ISSUE TITLE
Editor becomes unusable if right mouse button is clicked while dragging a parameter

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#17891]
**Godot version:**
3.0.2 mono

**OS/device including version:**
KDE Neon 

**Issue description:**
If you drag a numeric property with your left mouse button, and while dragging click the right mouse button, the editor becomes unusable. The cursor disappears and you can't click on anything anymore. Only keyboard shortcuts work. Only method to fix it so far seems to close and re-open Godot.

Might be related to this issue, but not sure: https://github.com/godotengine/godot/issues/17810

**Steps to reproduce:**
1. Open a Godot project
2. Drag a numeric property
3. While dragging, click the right mouse button and then release the left mouse button
4. Observe results

**Comment by Zylann** [comment]
Where is the mouse when you press right-click? Is it above the viewport?

**Comment by Bauxitedev** [comment]
@Zylann It doesn't matter where the mouse is at the time you press right mouse button, as long as you dragged at least a pixel away from the point you started dragging the bug is triggered.

**Comment by Zylann** [comment]
Actually... did you try while the 2D or Script mode is active? I have a guess that because this scrolling changes mouse mode like an "FPS", it warps the mouse at the middle of the screen, which also happens to be the 3D viewport (if selected), which means it miiiight trigger auto-focus on it, and in turn, trigger freelook. If that's what happens, then we should make sure the viewport doesn't mess with focus when dragging a field.

**Comment by Bauxitedev** [comment]
@Zylann Yeah, it happens in 2D and Script mode as well.

**Comment by Zylann** [comment]
Could be related to the same bug that causes https://github.com/godotengine/godot/issues/14373, where basically the release event for the second touched buttons of the mouse don't get sent.

**Comment by mhdchehade** [comment]
Yes, and when pressing esc key while dragging a value in project settings for example.

**Comment by nobuyukinyuu** [comment]
Since my version of the issue was closed, I hope to point out that this doesn't just seem to occur with SpinBoxes, although SpinBoxes are the only place I've been able to consistently observe this behavior both in editor and at runtime.  I've also had it happen while editing arrays of colors in the inspector (notably `Gradient`s), so this might involve `ColorPicker` as well.
