### ISSUE TITLE
Growing backlog of pull requests, will this be addressed soon for version 3.1?

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#17928]
What I mean is that up to this point, the Godot team has done a stellar job in getting patches reviewed and committed within days (and kept the backlog from moving too far above 100). This was even highlighted as a strength on the Godot main page within the last week or so.

However, the number is now at nearly 250 and growing (with a number of them sitting there since a month), and it includes a number of bugfixes that would help get the issue tracker back under control. It may be me being used to the rapid rate of merged pull requests, and it may be that GDC and GodotCon has taken precedence for March, but maintaining Godot's momentum assumes that there will soon be an effort to get as many of the good ones committed as possible.

Apologies if a massive review/committing sweep is already planned, just that Godot currently has one of the best track records in all of FOSS and I would like to see it say that way.

**Comment by eska014** [comment]
March was busy with the industry's largest event for professionals, now it's just two days into April and it's a holiday in many countries. These are real humans with private lives working on the project.
Pull requests will start getting merged again sometime this week.

**Comment by reduz** [comment]
I came back from GDC two days ago and It's long holidays in most of Europe
and many other places, so most contributors are not around.
Expect most of them to be reviewed/merged (when it applies) this week.

**Comment by akien-mga** [comment]
The current PR backlog is basically due to:
- Feature freeze (no new features) in December 2017 for Godot 3.0. Contributors continued making PRs with new features, which therefore had to wait for the 3.0 release to be considered.
- Release freeze (no new enhancements or small bugfixes) in January 2018 for Godot 3.0. Same story, contributors continued making PRs.
- 3.0 release at the end of January, followed by FOSDEM and GodotCon + a few weeks recovering from the past months of hardcore development towards 3.0.
- Just when we started getting back on track, reduz was sweeped away by GDC preparations and participation until a couple days ago, and I was quite busy with moving, GSoC, and various other tasks.
- And on top of that, Godot gets increasingly popular and the rate at which we get new issues and PRs keeps increasing.

So yeah, still not fully recovered yet, but April will be mostly about reviewing and merging PRs.

**Comment by BrentAFlynn** [comment]
> These are real humans with private lives working on the project.

And receive around $7,792 (last I checked) in total donations, with two full-time developers.

**Comment by reduz** [comment]
I have no problem discussing any issue, but If you are going to troll, could you please use at least your real user account instead of creating a new one?

**Comment by akien-mga** [comment]
>> These are real humans with private lives working on the project.

> And receive around $7,792 (last I checked) in total donations, with two full-time developers.

That's correct, but that doesn't contract the fact that we are "real humans with private lives". :)

Anyway, I don't see a need for more discussion on this topic, I've explained the current situation fully already.
