### ISSUE TITLE
Semi-Transparent When Placing Item from GridMap

### ISSUE THREAD

**Issue by ArgentArts** [godotengine/godot#17920]
Godot 3.0.2

Windows 10, Nvidia GeForce 1070

Currently, it's a bit difficult to see where you are getting ready to place an object or delete an object when using GridMap and this is because the object is completely opaque. It would be easier to use GridMaps, place pieces, and delete pieces, if the end-user could see through the object that stays with their cursor.

Steps:

- Create a GridMap with an object in it
- Select the object and place a few of them in the viewport
- Move the cursor over one of the objects to delete it using SHIFT+RMB
- Don't move the cursor ... 

You can't see that you've deleted the object previously placed because a fully opaque object is attached to the cursor. The object is to tell the end-user what they are placing and allows them to visually see the object as they are "brushing" in their grid items. However, since it is fully opaque, it gets in the way at times, especially when trying to delete something as it can initially seem like the deletion didn't happen.

I propose that the item/object that moves with the cursor be semi-transparent so that the end-user can see the difference between objects already placed in the viewport and the object that is always where the cursor is.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
