### ISSUE TITLE
gltf2 importer keeps -col suffix in animation but not in nodes

### ISSUE THREAD

**Issue by legione** [godotengine/godot#17922]
**Godot version:**

Godot 3.0.2 stable

**OS/device including version:**

Windows 10, linux

**Issue description:**

When meshes with animations using the suffix -col are imported the animation tracks keep the -col suffix, while the meshinstances don't. Both animation tracks and meshinstances need to have the same name to work. 

This is similar to #6582

**Steps to reproduce:**
1. Create a mesh in blender that has the suffix -col in the name
2. Animate the mesh (no need of armature, just insert a keyframe, translate and insert another keyframe)
3. Export as gltf2 and import in Godot
4. The animation doesn't work because it references the nodes with -col suffix, while the nodes are without it

**Minimal reproduction project:**

[godot-suffix-bug.zip](https://github.com/godotengine/godot/files/1867858/godot-suffix-bug.zip)

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
