### ISSUE TITLE
Allow explicit scene preview image saving

### ISSUE THREAD

**Issue by samdze** [godotengine/godot#17932]
**Godot version:**
Godot 3.0.2 official.

**OS/device including version:**
Windows 10 64 bit

**Issue description:**
The preview image displayed for a scene is updated **every** time the scene is saved.
This can lead to messy previews since scenes can be saved while the viewport isn't displaying the right portion of the scene or to wrong previews if other tabs are currently open. #12686

I think there could be an editor setting that lets the user choose if the preview is always updated on save or only explicitly through a button or a special save option.

With the aforementioned option enabled, the user doesn't risk having broken scene previews.

**Comment by lukruh** [comment]
Any workarounds or plans to implement this? It would be very nice, to save previews manually to get better thumbnails (also optionally disable gizmo and grid). Especially when working with others, who might not created the scenes and don't want to open every single scene to find the one they are looking for.
I'm absolutly beginner in godot, if I could I would try to implement it myself.

**Comment by Calinou** [comment]
This could be done by placing a Camera/Camera2D node in the scene with a special property enabled. The editor would use it automatically to generate the thumbnail when saving the scene.

**Comment by lukruh** [comment]
yeah adding a camera property and/or a specific subclass like "ThumbnailCamera" would be awesome. Is it possible to achive this with a class extending the camera? I've not created any editor scripts / tools yet, but if there are something like _on_scene_save() events and somebody redirects me to related docs I would give it a try..

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
