### ISSUE TITLE
Export Game failed on OSX

### ISSUE THREAD

**Issue by eduardonunesp** [godotengine/godot#17976]
![image](https://user-images.githubusercontent.com/582516/38328344-06d30f9c-3821-11e8-9ead-bd4accaa777b.png)

macOS 10.31.3

Failed to export game on OSX

- Download the GODOT from `brew cask`
- Open GODOT
- Download the template Isometric Game
- Download the export templates
- Export to OSX and it fails

![image](https://user-images.githubusercontent.com/582516/38328479-6eac3e4a-3821-11e8-9ad5-cad4fef1cb48.png)

![image](https://user-images.githubusercontent.com/582516/38328320-f6268d68-3820-11e8-996c-6ad71541ed6c.png)

The errors said something about a file exists but the export failed everytime

**Comment by flashyincceo** [comment]
Hi! I can replicate this bug, and it is caused by leaving the file name blank when exporting the .dmg file for OSX (after clicking the "Export Project" button). 

![screen shot 2018-04-17 at 9 16 19 am](https://user-images.githubusercontent.com/18668880/38875746-b4401414-4220-11e8-80c3-3f36fc1c19db.png)

When I specified a file name the .dmg file was exported successfully, although I did still get the `trashItemAtURL` error.

![screen shot 2018-04-17 at 9 10 10 am](https://user-images.githubusercontent.com/18668880/38875822-db74e4ce-4220-11e8-9460-3e2c16cbfac7.png)

I think the editor should prevent this from happening, and I will look into it. 

@eduardonunesp can you confirm that providing a file name for the .dmg file solves the issue?

**Comment by eduardonunesp** [comment]
@flashyincceo confirmed the error happened when export without a name, to fix that the IDE shouldn't allow proceeding without a valid path. Thanks for the feedback.
