### ISSUE TITLE
Allow specifing the length of arrays in ArrayMesh.add_surface_from_arrays

### ISSUE THREAD

**Issue by timower** [godotengine/godot#17973]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
All (I'm on X11/linux)

**Issue description:**
For mesh generation I currently store one PoolVector3Array for vertices and then update the mesh using ArrayMesh.add_surface_from_arrays.
This is reasonably efficient but whenever the amount of vertices changes I need to resize the PoolVector, which causes extra allocations.
It would be beneficial to be able to specify the length of the arrays in add_surface_from_arrays, this would allow me to use one large buffer for all vertices.

Is this something worth adding, I could probably create a pull request?

**Comment by Zylann** [comment]
Are you sure that resizing a PoolVector causes extra allocations? Last time I checked, regular Vector<T> had a capacity system which prevents more allocations if not needed, isns't it the same for PoolVectors?

**Comment by timower** [comment]
Yes, currently PoolVectors seem to always use memrealloc, which might cause allocations to happen.

I also don't understand the check if memory_pool is initialized [here](https://github.com/godotengine/godot/blob/3.0/core/dvector.h#L570), this seems to be uninmplemented making PoolVectors just worse versions of regular Vectors.

**Comment by poke1024** [comment]
@Zylann Seems to be different for PoolVectors, they don't seem to have the `realloc` next-power-of-2 padding that Vectors have.

**Comment by Calinou** [comment]
Note that Godot 4.0 replaces PoolArrays with PackedArrays. Please check if the new data structure suits your performance needs before opening a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
