### ISSUE TITLE
Particles2D freezes game on Chrome

### ISSUE THREAD

**Issue by acfaruk** [godotengine/godot#17972]
**Godot version:**
3.0.2

**OS/device including version:**
WebGL Chrome 65.0.3325.181

**Issue description:**
Whenever a particle system is running on chrome, the game freezes.
This does not happen on Firefox. You can try this out with the deployed test project:
[Deployed Site](https://gd-particles-test.netlify.com/)

**Steps to reproduce:**
Put a simple Particles2D in a scene, give it a particle material and export it for html5.

**Minimal reproduction project:**
[particles-test.zip](https://github.com/godotengine/godot/files/1876542/particles-test.zip)

**Comment by eska014** [comment]
Thanks for the report, we're tracking this bug in #16281

**Comment by jroy7110** [comment]
Intel McAfee Activate is creating those solutions, bringing together the experience and expertise of McAfee? with the innovation and proven performance of Intel. McAfee products have earned a position in eight of the Gartner Magic Quadrants. CRN ranks McAfee in its top 25 Best Companies to Partner With. And we're committed to continuously driving disruptive growth in the global McAfee Activate market.

We're building a safe, secure digital world with products that seamlessly integrate McAfee Activate to protect every layer of computing-from the chip to the cloud. Join us today and start securing your success.
<a href="http://quick-mcafeecom-activate.com">Mcafee.com/activate</a>|<a href="http://macfeemcafee.com/">www.Mcafee.com/activate</a>

**Comment by jroy7110** [comment]
Norton Antivirus gives overall protection to the system and it regularly scans the entire computer. This antivirus instantly blocks all the sites which have malware content in it. As all the viruses damage the files in the device, but it removes the infected content by scanning intensely in the device. When you are using any mail account on the default browser, it also scans the entire emails and blocks the harmful links provided in the mail. Norton Antivirus should be updated and upgraded regularly so that you get a proper scanning of the device.<a href="http://uk-norton.com">norton.com/setup</a>
