### ISSUE TITLE
mouseclicker is hard to use

### ISSUE THREAD

**Issue by JoeyCheung** [godotengine/godot#17986]
**Godot version:**

**OS/device including version:**

AMD Vega64

**Issue description:**

Tried using mouseclicker and couldn't find any resources to doing it and tried many methods. Here is an example of what I tried to do.

func _input_event(viewport, event, shape_idx):
    if event.type == InputEvent.MOUSE_BUTTON \
    and event.button_index == BUTTON_LEFT \
    and event.pressed: 
               $CollisionShape2D.position = get_viewport().get_mouse_position()

I'd like an online tutorial to use Area2D with mouseclicker
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by groud** [comment]
This not the place for asking for help. If you think that deserves an official tutorial, you might want to open an issue in the [godot-docs repository](https://github.com/godotengine/godot-docs) for that.
But since your problem is quite simple, I would just recommend you to ask your question on the several [community channels](https://godotengine.org/community) (facebook, discord, Q&A...)
