### ISSUE TITLE
TextEdit - expose "set_word_under_cursor() to replace it" to gdscript - also ability to get it's start and end position

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#18000]
Right now double clicking on a word in the TextEdit node selects it and highlights it.
I am working on an addon that needs to be able to replace a word that is under the cusor, without the need to double click on it from the user.

Would it be possible to add a setter function in Godot to also change the word under cursor with another word please?

Was wondering if there is a good way to do it with the current api 

we have get_word_under_cursor(), but no set_word_under_cursor().

I can get the cursor's overall position, but not it's position inside the word - which makes it extra hard to figure out an overall selection start and end on the line. Maybe I need to have a look how it was implemented upon double clicking and try to replicate with gdscript somehow

**Comment by blurymind** [comment]
It looks like textEdit in C++ has a selection mode for selecting entire word:
https://github.com/godotengine/godot/blob/5ede505f14877e3ede60eb4766a62c36d9f3b87f/scene/gui/text_edit.cpp#L1837

Can't seem to find it in gdscript though

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
