### ISSUE TITLE
Godot 2.1.4 Crash on iOS with godot_opt.iphone: AudioServerSW::_thread_func(void*) + 244

### ISSUE THREAD

**Issue by megasoft78** [godotengine/godot#18017]
Hi,
I just attached the crash that happen on my game on iOS.
It seems to be related with AudioServer.
[Cal_h_jO8I15VT-eW07Vc6.xccrashpoint.zip](https://github.com/godotengine/godot/files/1883154/Cal_h_jO8I15VT-eW07Vc6.xccrashpoint.zip)

**Comment by Calinou** [comment]
@megasoft78 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
