### ISSUE TITLE
AnimationTreePlayer OneShot node mode selection area too small and un-aligned

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#18035]
**Godot version:**

3.1.dev.custom_build.eaa5dfb, also 3.0 stable

**OS/device including version:**

Arch Linux, but happens on other OSs as well AFAIK.

**Issue description:**

When using a `Oneshot` node in the the `AnimationTreePlayer`, a mode can be selected that determines wheter or not two animations will blend together or mix "additively". The selection of those modes is difficult as the trigger area for the options is a lot smaller and also slightly displaced.

(sorry for the large GIF, I don't know how to "scissor" the video properly before converting to GIF, click to see it in full size)
![animationtreeplayer-oneshot-ui-offset](https://user-images.githubusercontent.com/5209613/38449618-6ce1d60a-3a11-11e8-9e60-bc33e9643268.gif)

Related to #17519

**Steps to reproduce:**
In an `AnimationTreePlayer` while using an `Oneshot` node try to select one of the modes, notice how it's almost impossible to select "Blend" and pretty hard to select "Mix".

Also the rest of that popup looks kinda off as well.

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
