### ISSUE TITLE
AnimationPlayer rotation direction

### ISSUE THREAD

**Issue by yonaskolb** [godotengine/godot#18049]
**Godot version:**
3.0.2

Currently when animating 2d rotation with `rotation_degrees` in `AnimationPlayer`, rotation is interpolated by value.
Is there a way to get it to interpolate it to the nearest angle? For example if going from `-350` degrees to `10` degrees, making it go the shortest path, instead of going through `-100`.
We have animations files that rely on this "closest angle" behaviour.

Would this require a new track type? I assume similar behaviour would be useful in Tween

**Comment by yonaskolb** [comment]
Just noticed a QA question regarding something similar just got submitted as well. Nice timing 😄 
Linking here for added context: https://godotengine.org/qa/27051/lerp-rotation-above-180-degrees

**Comment by yonaskolb** [comment]
Does anyone have an answer or a workaround for this?

**Comment by bojidar-bg** [comment]
For a workaround, try to animate to 370 degrees.

**Comment by yonaskolb** [comment]
@bojidar-bg yeah that's a sort of workaround. Trouble is it's not scalable. Say something rotates part of the way around in the same direction every x secs indefinitely. Eventually the number will get too big and we'll crash.

Also we have existing animation files that we wouldn't want to change by hand

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
