### ISSUE TITLE
Instance grid duplication

### ISSUE THREAD

**Issue by cronayu** [godotengine/godot#18074]
#**Godot version:**
3.0.2

I've been trying out godot and I like it. The thing is, theres some "quality of life" features/gui details that makes me wonder if the feature is not there, or i'm not seeing it.

For instance, being able to "grid duplicate" an object, as some may know from MMF2. 

![sin titulo](https://user-images.githubusercontent.com/17664109/38473832-84382f02-3b42-11e8-8971-343fda5cbd21.png)

I was following a tutorial on youtube (a bit outdated, so might be just that), and he had to duplicate manually brick by brick, on a Breakout/Arkanoid kind of game. AFAIK, theres only a manual duplication (ctrt + D)  and it stacks the duplicated instances on top of eachother, making more of a mess to handle.

**Comment by groud** [comment]
This can easily be done with a simple script. IMHO, this is to corner case to be added to the core.

**Comment by bojidar-bg** [comment]
See also #9180.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
