### ISSUE TITLE
Timer.set_wait_time(0) does nothing with no feedback

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#18097]
**Godot version:**
3.0.2 and 3.0.3b

**OS/device including version:**
Linux Mint 17.3

**Issue description:**
When set_wait_time() is set with zero, it ignores it, possibly as it may be an invalid number. It provides no feedback however. It's probably an edge case, but for my simple timer application it became a minor snag to not be able to set it to zero. Instead to work around it I set it as a super low number for it to start with. Otherwise it's either the last number it was set to or the default if not modified since startup. In my case the default being 1. I noticed I can't set the default to zero either, but instead it inputs '0.01'.

**Expected result:**
I can see how this might have come to be decided, but it seems very strange for something to be able to count toward and reach zero to also not be able to be set as zero.

**Code:**
```
countdown_timer.set_wait_time(0.0)
print("why: "+str(get_node("countdown timer").get_wait_time()))
```
**Result:**
`why: 1`

**Comment by mrcdk** [comment]
It does show an error:

![https://i.imgur.com/fNG7rNJ.png](https://i.imgur.com/fNG7rNJ.png)

(the second error is not related)

**Comment by agameraaron** [comment]
I guess that means... Can we change this issue into a feature request then to allow for zero to be used?

**Comment by mrcdk** [comment]
I'm not sure, does it make sense to have a timer with a wait time of 0 seconds? why don't you call the timeout function directly if that's the case? 

Setting it to 0 seconds would delay the call to the next frame and it would probably spam it if the timer is on repeat.

**Comment by agameraaron** [comment]
`Timer.emit_signal('timeout')`
This did the trick, just be sure if anyone else uses this as a way to workaround this issue to be sure to stop the timer before doing so

**Comment by ducklin5** [comment]
Allowing the wait time to be set to 0 would be useful in the case of syncing clocks over a network for example.

**Comment by hsandt** [comment]
Also, when using a dynamic parameter as wait_time. In my game, I let the player set the delay of an event through the UI. It's very easy to set this up use a HSlider with a value in seconds, min = 0, max = 2, step = 0.5. Except the value 0 will not work, and the step prevents me from just keeping the min at something like 0.1.

I have to manually detect value 0 in code and replace it with 0.01 (even to trigger event next frame), or manually call the event callback for an immediate event, but that would be slightly redundant in code.

**Comment by hsandt** [comment]
Just noticed that if `set_wait_time` shows an error message, `start` doesn't:

https://github.com/godotengine/godot/blob/master/scene/main/timer.cpp#L109
```cpp
void Timer::start(float p_time) {

	ERR_FAIL_COND_MSG(!is_inside_tree(), "Timer was not added to the SceneTree. Either add it or set autostart to true.");

	if (p_time > 0) {
		set_wait_time(p_time);  // will *not* be entered if p_time <= 0, so no error message
	}
	time_left = wait_time;
	_set_process(true);
}
```

More exactly, it will just reset time_left to wait_time, if we were in the middle of the countdown. So it will be doing something, but probably not what we want (setting time_left to 0 and immediately trigger the event).

I suggest renaming this issue to `Timer.start(0) does not set time_left to 0` or something similar. Or to open a different issue since it's a bit different now (`start` does something, but somewhat unexpected).

**Comment by KoBeWi** [comment]
The `start()` method is properly documented. It says that the time argument needs to be greater than 0 to have effect. If you want a 0-time Timer, open a [proposal](https://github.com/godotengine/godot-proposals).

**Comment by hsandt** [comment]
Indeed, I see that start's time_sec parameter defaults to -1, so time_sec <= 0 are valid and just mean "reuse current wait_time", and 0 simply happens to be handled like -1.

In the meantime I checked wait_time and read that low wait times (< 0.05 seconds) are not recommended due to how processor works, and should be handled with a custom process loop or so.

So it seems that in my case, the solution is either to clamp low wait times to a minimum like 0.05s, or, if we need frame precision (at 60 FPS that would be 0.01s), handle low wait times provided by the slider with custom code, using `Timer.emit_signal('timeout')` (suggested by @agameraaron) or even a direct function call.
