### ISSUE TITLE
Collision layer  and mask can not exported to tileset?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#18101]
**Godot version:**

3.0

**OS/device including version:**

**Issue description:**

Make a scene with static body and set the collision layer and mask to a value, after convert to TileSet, the collision layer and mask is lost. 
Only default value of 1 is allowed for collision objects in tilemap?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by AndreaCatania** [comment]
This is not a real bug, and probably support this feature is not so convenient.

> Only default value of 1 is allowed for collision objects in tilemap?

Nope

**Comment by alexzheng** [comment]
Another issue confusing me is that when collide with a tile ,the reported collider is always the tile map,which make it not so easy to draw collectable or breakable objects by tiles.

**Comment by vnen** [comment]
Yes, you need 2 tilemaps. The collision layer/mask can only be set in the TileMap.

**Comment by naturally-intelligent** [comment]
Is this tutorial no longer valid?

http://docs.godotengine.org/en/3.0/tutorials/2d/using_tilemaps.html#collision

Exporting to tileset gives "0/shapes = [  ]" for every shape.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
