### ISSUE TITLE
Suggestion: transition to fixed-point coordinates

### ISSUE THREAD

**Issue by dherring** [godotengine/godot#18136]
There are a number of proposals for compiling Godot with double-precision floats.  People see collision errors, tiles not lining up, and other weird things far from the origin.  #17971, #17820, #17307

Many hope that doubles will fix such issues by increasing the resolution past where issues are noticeable.  There have been a number of efforts in this direction.  #288, #334, ... #17134

Unfortunately, the multi-resolution capability of floats causes all sorts of odd behaviors.  Here is a paper showing some examples.  Just look at the raster figures to start.

https://www.mpi-inf.mpg.de/~mehlhorn/ftp/classroomExamplesNonrobustness.pdf

Fixing floats is very hard.  See the lengths CGAL goes to.

https://www.cgal.org/exact.html

Instead of switching to double, I recommend switching to a fixed point coordinate system.  The initial conversion would be harder, but the final result should be much more robust, always giving exactly the same results no matter where things are in the coordinate system.  Snapping coordinates to a uniform grid is fairly straightforward, and floats do use a non-uniform grid...

Here are some relevant links.

http://aigamedev.com/open/tutorial/robust-fixed-point-navigation/
https://gmod.facepunch.com/f/nerds/pepj/Why-floats-suck/1/
http://www.pathengine.com/Contents/Overview/FundamentalConcepts/WhyIntegerCoordinates/page.php
https://www.codeproject.com/Articles/63278/Heresy-I-Why-Floating-Point-Coordinates-are-Wastef

There is also the hybrid "far position" approach suggested by Peter Freese's article "Solving Accuracy Problems in Large World Coordinates" in Game Programming Gems 4 from 2004.

**Comment by aaronfranke** [comment]
Interestingly enough, one of the easiest ways to implement this is to first implement double-precision. `float` and `double` share many similarities, and supporting both means that Godot's code completely uses abstract the abstract `real_t` type with appropriate casting when required.

And, I would like to know how you propose to implement such a system. As far as I know there isn't a fixed-precision decimal-number type in C++ or C#. We would have to use integers and then scale them, correct? And even if we did use math to make it a local calculation (and therefore high precision), the act of scaling would turn it back into a floating type anyway. Furthermore, concepts that we use with IEEE floating numbers (such as Infinity and NaN) don't exist with integers.

Implementation aside, what problems would fixed precision solve that `double` does not? Double precision numbers are accurate to the millimeter at scales of trillions of meters, a size so large that it would take ridiculous amounts of in-game time to traverse. A fixed-precision using 64-bit integers at a scale of 10,000 units to 1 meter only allows a few orders of magnitude more.

In general I don't think fixed precision is a good idea, and certainly not one the Godot devs would implement anytime soon (we're still working on double support...)

But I would definitely approve of integer-based classes for positioning, for manually doing such math yourself, at least for now. See: https://github.com/godotengine/godot/issues/3286 https://github.com/godotengine/godot/pull/17766 and https://github.com/godotengine/godot/pull/18096

**Comment by fire** [comment]
Godot Engine does have a 128 bit fixed point math library. https://github.com/godotengine/godot/blob/master/thirdparty/misc/r128.h

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
