### ISSUE TITLE
No way to create a ViewportTexture from an existing RID

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18155]
Godot 3.0.2

I am using VisualServer to manage some of the internals of my plugin for practical reasons, but `VisualServer.viewport_get_texture()` returns a RID, and I couldn't find a way to create a `ViewportTexture` resource from an existing RID. I need to do this because then I need to pass it to actual nodes that require a resource object.

Basically I render things offscreen, then I want to provide a Texture which is the result of this rendering, in realtime. But I can't do it without creating `Viewport` nodes that would need to occupy a place somewhere in the tree...

I didn't actually try yet, so unless there is some magical RID/resource cast operating under the hood, I can't do the above.

**Comment by ShyRed** [comment]
`ViewportTexture` is actually just a proxy / frontend for a `Viewport`. Pretty much all calls to it get redirected to the actual `Viewport` and the `RID` it provides is the one of the Viewport-Rendertarget:
https://github.com/godotengine/godot/blob/3a5b25d5b489ad88c2861c9c37b56469580fbf03/scene/main/viewport.cpp#L104-L113

`VisualServer.viewport_get_texture()` returns the RID of the actual rendertarget (of a `Viewport`?). I'm not sure, if it is easily possible, but you would need to find out which `Viewport` the `RID` from `VisualServer.viewport_get_texture()` belongs to so you could set up a `ViewportTexture` referencing the `Viewport` that references that rendertarget...

**Comment by Zylann** [comment]
Ugh... a resource (especially a graphics resource) referencing a node sounds like a bad design... I really like the fact you can sometimes bypass the scene tree layer for more control and performance from the scripting layer, but that kind of stuff makes the two worlds impossible to communicate.

**Comment by ShyRed** [comment]
No idea what the idea behind this is / was unfortunately. :disappointed: 

The current design is problematic as it is very hard to use. You need to setup a lot of specific things like making it local to scene and also make sure the Viewport node is created before anyone is using the texture. See #18159 / #17510 for example. There was a basic bug that made the backend use the wrong texture. The bug however exposed the general problem of build order and timing. The example project created an environement which referenced the ViewportTexture. Problem: the Viewport does not exist at that time. The calls against ViewportTexture ended up failing, because it could not find a Viewport to direct the calls to.

**Suggestion:**
Maybe one could make `ViewportTexture` standalone so that it basically is just a rendertarget texture. You could then assign that rendertarget to materials / sky like it was a normal texture. If the rendertarget has not been rendered into, then it is just an empty image and does not cause any errors.

You then would need to either render stuff into that texture manually or assign that texture to a `Viewport` so the `Viewport` renders into it.

Problem of build order / getting back to texture by RID would be solved.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
