### ISSUE TITLE
Node2D does not allow child nodes to use Anchor to fit Canvas

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#18166]
**Godot version:**
![Version](https://i.imgur.com/ZxRNl50.png)

**OS/device including version:**
Windows 10, 64 bit

**Issue description:**
Node2D does not allow CenterContainer's Anchor points use the canvas size.

**Steps to reproduce:**

1. Add a Node2D as root.
2. Add CenterContainer as child of root.
3. (Optional) Add a visible node to see the center position
4. Set Anchor->Right and Anchor-Bottom to 1 in the Inspector for CenterContainer

**Result:**
![Node2D as Root](https://i.imgur.com/FfYWIhk.png)

**Temporary Fix to problem:**
Use Node instead of Node2D.
![Node as Root](https://i.imgur.com/X5PgP2f.png)

**Comment by Noshyaar** [comment]
cc: @groud

**Comment by bojidar-bg** [comment]
Not sure if this is a bug, but it is not intuitive enough anyway.

**Comment by groud** [comment]
I don't think it's a bug. 
The Control use the parent as reference if that one extends CanvasItem (thus a Node2D or a Control node). If the parent extends Node2D, only the position is considered, both size and position for Control. If the parent is not of on of those types, it uses the viewport properties (this is what happens with the normal Node).

Consequently, you're asking here so that both the Node2D position and the Viewport size are considered at the same time, which would lead to inconsistencies in the system and would probably be hard to deal with.

In your situation, I would just advise you to use a basic container (like center container or margin container maybe) as a root node.

**Comment by Noshyaar** [comment]
What would the size be if that PR gets merged? If it's 0,0 then the anchors would be meaningless in that case, right? Hopefully this is documented.

**Comment by ivanskodje** [comment]
I feel that I should add, that the reason I **personally** would benefit from being able to make the Node2D fit to the canvas, is that to my knowledge, this is the easiest  (light weight) way to have a Node that can be hidden or displayed via hide() or show() as a root node for a Scene.

**Comment by Noshyaar** [comment]
I think you want to use generic Control node for that. It extends CanvasItem and can use `hide` and `show`. (hiding the CenterContainer itself might work too, but might be harder to work with when it's a Scene root)

Node2D has no boundary. If you want it for the position, it's okay. But if you want the size of the Viewport, it'd be a bit confusing as now the child has inherited both Node2D's and Viewport's properties.

**Comment by groud** [comment]
You can use a basic control node set to Full Rect (in the layout menu) that should work perfectly

**Comment by KoBeWi** [comment]
Looks like the issue didn't gain much support and there's no consensus that something should be changed. Also it's easy to workaround.

So closing, feel free to [reopen it as a proposal](https://github.com/godotengine/godot-proposals) if you feel it's still important.

**Comment by chucklepie** [comment]
Well, I've been at my screen staring for 30 minutes then gave up and found this. Yes, it may be logical if you think deep enough and know how godot works inside and out, but for everyone else, it makes absolutely no sense. At least update the documentation to state how size and anchors work in the real world instead of just the basic auto docs...

**Comment by bojidar-bg** [comment]
To cite the previous response:

> So closing, feel free to [reopen it as a proposal](https://github.com/godotengine/godot-proposals) if you feel it's still important.

Issues for non-bugs are to be moved to the proposals repostitory. This does not have to be done by the original author; instead we rely on the next person interested in the topic to create a proposal which outlines the problem and gives a possible solution.

**Comment by KoBeWi** [comment]
The last comment actually suggests a documentation issue. Not sure where should it be mentioned though.
