### ISSUE TITLE
Color of the node emitting the signal in Connecting Signal dialog is confusing

### ISSUE THREAD

**Issue by kenneth-leblanc** [godotengine/godot#18162]
**Godot version:**

v3.0.2

**OS/device including version:**

All

**Usability Enhancement:**

When connecting a signal in the Connecting Signal dialog. The node emitting the signal is bright red. This can lead to confusion as to whether or not a signal can be connected to it since red is generally used to indicate things that are bad. I suggest switching the color to a more friendly color or making it a bolded version of the normal color and add the word (Emitter).
This is how it currently is. Note how it can be perceived as incorrect to connect a signal to that node.
![godotcolor](https://user-images.githubusercontent.com/4635469/38710386-456ba75a-3e8e-11e8-8666-66df776227d5.png)

Just an example color to show how it doesn't feel wrong to connect a signal to this node now.
![godotcolordifferent](https://user-images.githubusercontent.com/4635469/38710453-9686183c-3e8e-11e8-8e01-f9c78b1bdd61.png)

Last example to show it white with the added word (Emitter). This to me is the clearest and doesn't indicated that it should be connected or that it shouldn't be connected. Note: On discord it was also mention to possible add the emitter icon as well.
![godotcolordifferent2](https://user-images.githubusercontent.com/4635469/38710474-b2d33150-3e8e-11e8-82d7-15c3371d5782.png)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Mintormo** [comment]
Hm, I can't find where set color of this red item list :( I find NodeDock class and ConnectionsDock class. I saw editor color setting. Nothing. Need help.

**Comment by kenneth-leblanc** [comment]
I was also interested in chasing this one down, I might start looking in connections_dialog.cpp. I'm not sure though, I literally just downloaded the source code.

**Comment by giladbau** [comment]
Same here. I think the actual list is created in another class. Look at lines 262-264 in connections_dialog.cpp.

**Comment by Mintormo** [comment]
> Look at lines 262-264 in connections_dialog.cpp
Nothing. :(

**Comment by Mintormo** [comment]
I find where is it. Method SceneTreeEditor::_add_nodes. Line 172, 207, 214. What color (or title) should I choose?

**Comment by kenneth-leblanc** [comment]
My personal preference is to leave the color the same as the rest of the text. Make the text **Bold** and add the word (Emitter)
Like: **Area2D (Emitter)**

**Comment by Mintormo** [comment]
I suggest this:
![godot1](https://user-images.githubusercontent.com/2286710/39094579-37bb7492-463a-11e8-88c0-4ca6d8f0ae05.png)
![godot2](https://user-images.githubusercontent.com/2286710/39094580-380609c6-463a-11e8-9360-b6d8951fc155.png)

**Comment by Mintormo** [comment]
> My personal preference is to leave the color the same as the rest of the text. Make the text Bold 
It's not contrast. I think the color should attract the eye.

**Comment by kenneth-leblanc** [comment]
The contrast is too much. You don't want to draw the users attention so much. It is really only there for informational purposes. You need to save high contrasts color for when it is really important. This isn't important, there really is almost no reason to highlight the emitting node. So I think it should be subtle.

**Comment by AlanLynn** [comment]
I'm happy that a change is being made, and green is definitely an improvement over red. But I'm inclined to agree with @kenneth-leblanc that giving the emitting node a special color can mislead the user into believing that something important is happening.

Correct me if I'm wrong, but I believe the reason for trying to make the emitting node stand out is because it's common to want to connect a signal to the emitting node. So the current process for this is:

1. Click "Connect..."
2. Look for the special color to find the emitting node.
3. Select the emitting node.
4. Click "Connect".

My thought is, if this is common, why not simplify the process of connecting a signal to self:

1. Click "Connect..."
2. The Connect dialog selects the emitting node as the initial selection.
3. Click "Connect".

This would remove the need to make the emitting node stand out so much, and the emitting node could be styled less conspicuously - maybe bold white. This would make the interface less confusing, and there would be one less step when connecting a signal to self.

Am I on the right track here, or is the emitting node colored for a reason other than what I mentioned?

**Comment by homer666** [comment]
@AlanLynn I was actually thinking of the same thing, but then I realised that my signal connections went to the root node of the scene just about as often as to itself. Changing the behaviour would just move the extra click to when you want to select the root node, so I don't know if it would make a difference in the long run. Not that I would really mind the change.

From what I can gather, the emitting node was indicated in a different colour only so you could orient yourself a little better, pretty much. It should definitely be changed to something less conspicuous, like being bolded or having extra text indicating that it's the emitting node.

**Comment by ComradeSparklePony** [comment]
There appear to be several proposed options for fixing this, including changing the color, adding text to mark the node, bolding the text, or some combination. I personally think changing the color is the best approach because it provides the least dramatic change while still fixing the problem, but I'd appreciate some input before I make a pull request.

<sub>This is my first time contributing to a project other than one of my own, so if I'm doing anything wrong, please let me know.</sub>

**Comment by akien-mga** [comment]
Fixed by 9f4b5a9.
