### ISSUE TITLE
Filmic tone mapping does not work correctly

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18181]
Godot 3.0.2

Windows 10, GTX 1070

I have compared Filmic with Blender and the tone mapping in Godot with an HDRI map and Godot is not correct, the result is almost the same as the Linear tone mapping. I have used it in a new project with all the default settings (so the panorama is in HDR).

Here are the two software with Filmic, at the left it's Blender with the correct tone mapping:

![filmic comparison](https://user-images.githubusercontent.com/30020215/38745889-32d1a2b2-3f46-11e8-9532-8fb91f70d9b5.png)

You can download the .HDR map to test it here: https://hdrihaven.com/hdri/?c=skies&h=kiara_1_dawn

**Comment by CptPotato** [comment]
The main (but not the only) problem is that you can't set the whitepoint high enough because Godot is limiting the value to a maximum of 16.0 - which in this implementation is definitely not enough to soften the highlights (it basically looks like there's no tonemapping).

Tonemapping and Bloom in general is implemented pretty badly in my opinion. None of the Tonemapping operators provides a high enough whitepoint, the ACES operator plain out ignores it and the implementations of all of them inside the shaders look *very* copy-pasty.

Bloom is also blended in a way that doesn't make a lot of sense to me. Internally it uses HDR but it's blended *after* the tonemapping with weird blending modes, loosing all the benefit from it and taking away the "physically based" aspect.

I once changed those things in a test and got much better results:
[built-in filmic tonemapper](https://user-images.githubusercontent.com/3957610/40438756-28d81ae2-5eb9-11e8-8c5f-0e7c2bea1217.png) vs [custom ACES tonemapper w/ better bloom](https://user-images.githubusercontent.com/3957610/40438755-28b98546-5eb9-11e8-88e6-cda63eb05619.png)

I might create an issue collecting and addressing those problems but I'm having trouble getting it all together without requiring to change large parts about the shader.

**Comment by volzhs** [comment]
so... #20096 fixed this issue? or is there something to be done? cc @CptPotato

**Comment by volzhs** [comment]
Thanks for the explanation. :smiley:

**Comment by tinmanjuggernaut** [comment]
I'm experiencing this same issue in 3.1.1 and a recent build from master: 
Godot 3.1.1 and 3.2.dev.custom_build.df17cf0
Windows 7/64
Intel HD 4400
Glow is off. 
Project: 3D materials demo with items hidden, rotate to look at the sun.

On the right of the image below are all four tone mapping modes in Godot. The HDR is a little underexposed, so the last one is Filmic w/ exposure at 2. The sky is blown out in all.

On the left is blender showing the default view is blown out and over saturated mode, filmic mode, and filmic w/ light strength at 2. The latter two being what I would hope to see in Godot. 

Color representation looks fine in Godot, but the tone mapping does not. Is there a setting I need to turn on or off?

![filmic-color](https://user-images.githubusercontent.com/632766/58533100-826a1500-8222-11e9-9b78-b4c3d309c132.jpg)

**Comment by CptPotato** [comment]
Increase the white value, that should do the trick.

**Comment by tinmanjuggernaut** [comment]
Indeed it does. I bumped it up and got the expected results. Thank you sir!

**Comment by Linko-3D** [comment]
The maximum white value should be calculated automatically like other engines do. Also the HDRI is still not displayed correctly in your screenshot, maybe the lighting in the scene too.
