### ISSUE TITLE
VideoPlayer wrong color space when played back on a texture and viewed in 3D

### ISSUE THREAD

**Issue by f-rank** [godotengine/godot#18208]
Godot version: 3.0.2

Windows 10.0.16299.371
nvidia 1070 running 391.35 drivers

Using VideoPlayer to play webm or ogv does so in the incorrect color space.
![image](https://user-images.githubusercontent.com/1836566/38773314-09c4704c-4041-11e8-866d-c735880d0ee2.png)
On the left side the correct color space is used and reproduced in all players tested, to the right the video how it is played in Godot. Tested with both webm and ogv files that play correctly on other external players.

**Comment by blurymind** [comment]
It would be awesome if the seek function worked too :)
https://github.com/godotengine/godot/issues/14430

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Ruthoranium** [comment]
I'm a newbie at Godot, so idk if I'm doing something wrong but I'm having this problem in 3.3.4
I am using a ogv file for this. the 2d version works but the colors are flushed out in 3D one, using viewport.

Here's the project that this is happening with.
[color_bug.zip](https://github.com/godotengine/godot/files/7461525/color_bug.zip)

**Comment by Calinou** [comment]
@Ruthoranium Can you reproduce this after switching to the GLES2 renderer?

**Comment by Calinou** [comment]
I tested this on Godot 3.5.rc5. This is not a bug; it's due to incorrect configuration. You need to force sRGB on the material displaying the ViewportTexture, similar to what's done in the [GUI in 3D](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/gui_in_3d) demo.

I recommend using a MeshInstance with a QuadMesh and a ViewportTexture assigned, but if you want to keep using Sprite3D, you can assign a material override with the **Unshaded** and **Albedo Tex Force Srgb** flags enabled. Enable **Local To Scene** on the SpatialMaterial's Resource section, then set the ViewportTexture within the Albedo property. (You need to keep the Texture property set on the Sprite3D for its size to remain correct.)

![image](https://user-images.githubusercontent.com/180032/177422289-eeedf349-f53e-4fb0-a04b-5f0b9f822d99.png)

[color_bug_2.zip](https://github.com/godotengine/godot/files/9049899/color_bug_2.zip)
