### ISSUE TITLE
Distance fade causing objects to render in incorrect order

### ISSUE THREAD

**Issue by Mr-Slurpy** [godotengine/godot#18209]
**Godot version:**

v3.0.2 no mono

**OS/device including version:**

Window 10, Nvidia GTX 780ti, Driver 388.59

**Issue description:**

Distance Fade renders objects in the incorrect order when viewed from a specific angle.
![bugmaybe](https://user-images.githubusercontent.com/15792219/38773556-89a62c70-401d-11e8-95c2-a8f6feec3771.PNG)

**Steps to reproduce:**
Step 1: Place 2 meshes
Step 2: Enable distance fade on both
Step 3: Angle camera in a way such that one object is closer to camera than other but, the farther object is closer to the plane perpendicular to the camera direction.

**Minimal reproduction project:**

[bug.zip](https://github.com/godotengine/godot/files/1911477/bug.zip)

**Comment by Calinou** [comment]
I'm not sure if this can be solved without introducing a significant slowdown due to the use of order-independent transparency. Remember that enabling proximity fade or distance fade will always make the object transparent, which means it has to be sorted properly (which is a difficult thing to do).

**Comment by Mr-Slurpy** [comment]
Ok a month later I figured out what was going on. Distance fade was turning the material into a transparent one so I had to set `Depth Draw Mode` under `Parameters` to `Always`. No problem here.
