### ISSUE TITLE
No way to add items to the top-left toolbar

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18207]
Godot 3.0.2

Plugins can register new controls in the top toolbar, by using `add_control_to_container(CONTAINER_TOOLBAR, control)`.

![image](https://user-images.githubusercontent.com/1311555/38772968-174f21ec-4043-11e8-80bc-1e8d63ce0412.png)

However, it always add them on the top-right menu, which is one of the least looked-at regions in terms of interface conventions, and I'd like to add menus to the top-left part instead because it looks out of place.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
