### ISSUE TITLE
Cloning down at end of file in script editor fails with error

### ISSUE THREAD

**Issue by krogank9** [godotengine/godot#18206]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Linux/Ubuntu 1710

**Issue description:**
Clone down (Ctrl-B by default) in script editor fails and generates an error if you clone a Multi-line selection which includes the last line of the file

Gives this error, this is for 2 a line selection. It produces 5 errors for 5 lines etc:
`scene/gui/text_edit.cpp:3300 - Index p_line=22 out of size (text.size()=22)
 scene/gui/text_edit.cpp:3300 - Index p_line=23 out of size (text.size()=23)`

It gives the above error and adds a newline to the end of the file.

![screenshot from 2018-04-15 11-51-32](https://user-images.githubusercontent.com/12469653/38780394-8991f1d4-40a3-11e8-81f4-6a106e165dda.png)

**Steps to reproduce:**
Make a selection spanning 2 or more lines touching the bottom of the file and Clone Down.

**Minimal reproduction project:**
Any script file

**Comment by ericmccarthy7** [comment]
I'm trying to tackle this to get a handle on the codebase.

I've noticed that this problem is happening here: https://github.com/godotengine/godot/blob/master/editor/plugins/script_text_editor.cpp#L1018

It seems like we're not checking if the next line exists or not and just using the value directly.

Since this would be my first contribution I would love some input on next steps or if I'm on the right path. I'm going to look through other _edit_option cases to see if a similar situation arises and how the problem is solved.
