### ISSUE TITLE
Gdscript - Ability to leave midline comments

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#18228]
Right now we can add a code comment on an entire line:
```
func _ready():
       ## this is a comment
	connect("text_changed",self,"textChangeFunc") 
```
Or at the end of a line, like this:
```
func _ready(): ## this is another comment
	connect("text_changed",self,"textChangeFunc")
```
But it seems to be impossible to leave a comment in the middle of it. 
```
func _ready():  
	set_position(/*expects Vector2*/)
        myFunction(/*expects float*/)
```
This would be very useful for an addon that I am working on at the moment here:
https://github.com/godotengine/godot/issues/17795

**Comment by ianscottcamp** [comment]
Correct, you can not put comments in the middle of code. Just put an explanation comment above your code or right next to it. In your example the engine would not even compile because it would look for appropriate variable types even if you aren't ever using the functions. you could also put place holder variables if you aren't using them yet. 
func _ready():  #comment
	set_position( Vector2(0,0) ) #set_position(expects Vector2) 
 #myFunction(expects float)
        myFunction( float(0) )

**Comment by blurymind** [comment]
The comments being left midline can also be used as a meta-tag placeholder space for something to be replaced or generated by an addon - so I see this as a potentially powerful tool for doing interesting new ways to generate gdscript code. I will present a practical example soon hopefully.Still working on parsing gdscript to bbcode label and back. Maybe if this is not possible, I will come up with another way to do it

Not sure if other programming languages can do it - python certainly doesnt allow it

**Comment by blurymind** [comment]
I am going to close this request since the pull request implementing it was not accepted
