### ISSUE TITLE
ParticlesAttractor2D missing in Godot 3

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#18223]
**Godot version:**

Godot 3 All systems

**OS/device including version:**

All systems

**Issue description:**

I know that it was removed due incompatibilities with the new particles system. But there is no issue opened for that and there is risk of forgot this awesome feature left in the way. So there is the issue to remember that.

**Comment by girng** [comment]
remember @bojidar-bg saying that it might be possible to create the same effect with the new particle system. however, still think maybe a particle attractor node would be ideal.

**Comment by Ranoller** [comment]
I try to emulate this node very hard. It´s not casuality that i remember that, i was trying to adapt a menu screen from godot 2 that uses this node (attract or reject the particles at some variable position in the canvas), and there is no substitute, behaviour seems impossible to emulate... but if nobody knows how, please document. (I really think is not possible)

**Comment by Bauxitedev** [comment]
You can sort of emulate it by setting Radial Acceleration to a negative number. This will cause the particles to be sucked towards the center of the particle emitter.

![img](https://user-images.githubusercontent.com/31383123/38803203-c3161b8a-416e-11e8-892b-736bb2ccee80.png)

But, of course it's not ideal, because you want to be able to change the attraction point separately from the emission point.

**Comment by eon-s** [comment]
Maybe it could be possible to feed the particles shader with a texture that can be used to affect the velocity to simulate attraction.

**Comment by girng** [comment]
https://github.com/godotengine/godot/commit/cf834a22dc78950a9fba484a7f9db98da84cae59#diff-531cda3564322c1a2ce4d0a3b33f5852

Please for the love of god let's get it back!!

**Comment by eon-s** [comment]
Is on the roadmap
https://github.com/godotengine/godot-roadmap/blob/master/ROADMAP.md

But I guess this will be for 3.2 or 4.0...

**Comment by girng** [comment]
Lol, dang. I was just thinking it could be re-added since there is the CPUParticles2D  now (w/o a re-write/port).  I assume the CPUParticles2D is not the same as from 2.x versions then. Which that makes sense. Man, one of my favorite nodes and  very underrated  imo. You could create amazing stuff with that attractor.

**Comment by clayjohn** [comment]
This is still planned for 4.0! But we are now tracking 4.0 changes to the particle system in the proposals repo here https://github.com/godotengine/godot-proposals/issues/815. Further discussion should take place there.

And yes, particle attractors were mentioned there already, so no need to add another comment :)
