### ISSUE TITLE
Add chocolatey option to download client

### ISSUE THREAD

**Issue by Handja** [godotengine/godot#18220]
**Feature Request**
I use chocolatey to download package on Windows, not Scoop.
It would be great if this option is available to download Godot

**Comment by vnen** [comment]
I don't think this is something we should get involved with. The same way we don't get involved in providing packages for every package manager across Linux distributions.

The most we can do is put a reference in the website if someone is maintaining the package.

**Comment by Handja** [comment]
I understand, thx you.

**Comment by necrose99** [comment]
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer

a number of chocolatey packages use zip.
exile game... I think is one. 

can rework,  for godot. publish to chocolatey.org and done. , exe to msi.. can record install to msi. 
can do msi install via chocolatey even easier. 

start10 I basically reworked from start8. 


stepson is game dev student. 
chocolatey+boxstarter + (chef /ansible/pupet/salt) ntlite.. base windows10 iso..  can easily deploy w10.. rest will automatically dl. and install via pxe boot over lan.  not having to rot all day on a Saturday fixing his laptop due to (ransomware/virus/drive failure or other issues)  priceless...
add zfs Service to lan with resillosync can keep profile in sync.  and stream restoration.
