### ISSUE TITLE
Preview viewport

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#18244]
Writing a shader yesterday that generates a procedural texture to be consumed elsewhere I need to render a rectangle using that shader to a viewport.

The downside of this is that you can no longer see the output of a shader unless you place that viewport into a viewport container. 

It would be a nice feature to be able to select a viewport and "preview" that viewport in one of the editor windows in the same way that you preview a camera. 

Any UI guru know if this is feasible?

**Comment by eon-s** [comment]
Maybe something like the atlas or texture region view on the bottom panel?

**Comment by Zylann** [comment]
I would expect this to show in the inspector, or a subwindow of the viewport maybe?
A bottom or side panel would waste space.

**Comment by Megalomaniak** [comment]
I generally don't like these kinds of things in inspectors/property editors and would rather preview textures including procedural ones in the viewport, however if it can't be helped...

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
