### ISSUE TITLE
Connecting signals to other signals

### ISSUE THREAD

**Issue by ttencate** [godotengine/godot#18268]
**Godot version:** 3.0.2

The [Qt](https://www.qt.io/) toolkit has a notion of signals very similar to Godot's. One useful feature they offer is that a signal `a` on object `A` can directly be connected to signal `b` on object `B`. If `a` is emitted, this will also cause `b` to be emitted, with the same arguments.

This helps with encapsulation, in case a node just wants to pass on (expose) a signal from one or more of its children unmodified.

We can do this today, but we have to add a script. The behaviour is the same as if we wrote a function to pass on the signal:

```
# Using a function, in today's world:
A.connect("a", self, "_on_A_a", [B, args])
function _on_A_a(B, args):
    B.emit_signal("b", args)

# Connecting signals directly, in a possible future world:
A.connect("a", B, "b")
```

It seems we can currently have a signal and a function with the same name, so this syntax might be ambiguous. I feel it should be forbidden to have two things with the same name like that, but if it has to remain, then I think connecting to the function should take precedence over the signal.

**Comment by ttencate** [comment]
@steincodes Like I said, encapsulation. Suppose this is my scene:

    player
    +- body    # can emit on_hit signal
    +- shield  # can emit on_hit signal

Suppose we want to flash the screen red when any part of the player is hit, either `body` or `shield`. But we don't want this red-flashing system to know about the internals of `player` (its child nodes), so we want to add an `on_hit` signal to `player`, and connect the screen flash to that. This is why we would need to forward the `on_hit` signal from the child nodes up to the `player` node.

**Comment by vnen** [comment]
I'm not sure about this one. On one hand I had a similar need in the past, it really helps encapsulation of scenes. OTOH you'd have to declare a signal in `player` anyway, so you'd need a script there. And there's a few cases where this might be problematic, like when the arguments of the signals do not match. I feel like most of the time the arguments wouldn't be same, so you'd have to roll your own system anyway, since it's much more flexible.

**Comment by ttencate** [comment]
> OTOH you'd have to declare a signal in player anyway, so you'd need a script there.

True, the savings are just in the function definition.

> And there's a few cases where this might be problematic, like when the arguments of the signals do not match.

This is no different than with functions, isn't it? You just get an error at runtime.

> I feel like most of the time the arguments wouldn't be same, so you'd have to roll your own system anyway, since it's much more flexible.

Most of my signals have either zero or one argument, so I don't see a big problem here.

**Comment by bojidar-bg** [comment]
BTW, just to mention it, you can connect directly to internal functions:
```gdscript
for child in get_children():
    child.connect("on_hit", self, "emit_signal", ["on_hit"])
```
Unfortunately, since all bound signal parameters are passed after the normal parameters, it is impossible to use this method for forwarding signals with parameters.

To make it possible to pass parameters to the start of the argument list, there are a few things which might be done:
1. Add a CONNECT_BIND_START constant to the ConnectFlags enum, which would make all binds go as the first N parameters of the specified function.
2. Add some "neutral" separator value we can pass in the binds array, which would default to the start of the array if not found. In order not to break compatibility, it would have to be either some singleton object value, or `null` along with another connect flag.
3. Add a second array of binds, so that one might do e.g. `connect(.., [1], [2], flags)`. Since that would likely break compatibility, it might have to be a new method.
4. Something else, but I'm not sure what...

**Comment by voithos** [comment]
Could something like this apply to things other than signals? I'm not sure if it's a good practice or an anti-pattern, but I've sometimes wanted to "forward" properties from child nodes onto the parent node, and have worked around it by adding setter methods, etc, instead.

So I suppose my general thought is, if we think we can come up with a more generalized forwarding/encapsulating mechanism that is easier to use, then I think that would be worth exploring. If not, I think I may agree with @vnen, in that it may be best to just manually do it when necessary instead of adding another feature to the language/library.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
