### ISSUE TITLE
Add some way to control edge hardness

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godotengine/godot#18276]
This is desired for Godot's internal (parametric) models (eg spheremesh), particularly when turning the settings low to get generic-looking low-poly objects.

The simplest way of doing this would be offering a 'hard edges' option to either the model setting (for internal models only) or as a spatialmaterial flag.

It also could be an angle setting (normal angle) either in the mesh settings (of any model's mesh), a mesh import setting, or as a material setting. Although this is likely more niche, but I could see simply having the ability to force hard edges onto any existing models as a more useful feature (like human characters with smooth edges and 'cpu' characters with hard edges).

I haven't tried anything, maybe someone could comment why they would need full angle control rather than just forcing hard edges.

**Comment by Zylann** [comment]
What do you mean by "hard edges"? Do you mean faceted, without smoothing?

**Comment by insomniacUNDERSCORElemon** [comment]
@Zylann yes, that's exactly what I mean. The sort of thing you think of with low-poly.

For materials, I assume it'd just throw out the normal data and re-interpret it as... normal normals (outward facing and perpendicular to faces) with hardness either all-on or specified by your 'normal angle' setting (if that were implemented).

**Comment by Zylann** [comment]
What I don't understand with the material option is, how can you dynamically turn one shared normal (which is what smooth meshes are usually made of) into multiple per-face non-shared normals, without touching the mesh data. You could eventually never share any normals, but that would mean to not share any vertex, which is quite inefficient on the rendering side.

**Comment by mjheikki** [comment]
Is there a particular reason why you would want to do this inside the engine, instead of splitting the edges in a 3D package like Blender where it's easy to control which edges get split (and use a modifier for the splitting)?

**Comment by insomniacUNDERSCORElemon** [comment]
@Dogpot my main intention of this is for Godot's generated meshes, so you can make a game without exporting basic shapes like cubes/pyramids/diamonds (or icosahedrons if it were possible) etc.

As I mentioned it might _possibly_ be desired to have the ability to switch between hard and soft edges for a quick effect. I mentioned human vs CPU in the OP, another use might be conveying something like a frozen or hardened/thorny status effect. Or alive vs petrified (or real vs statue, real vs computer game/bad memory etc.

As in a low-cost effect, rather than requiring an entirely new model that only has different normals.

**Comment by sdfgeoff** [comment]
Switching flat vs smooth is not something trivial. If you have a cube with smooth shading, then you have 8 vertices because all the vertices share normals. If you have a cube with flat shading then you need 24 vertices because the vertices at the edges/corners do not share normals. 
So while this is possible at the geometry level, it isn't possible at the material level.

**Comment by Bauxitedev** [comment]
You can actually do this in a shader using interpolation qualifiers.
E.g. if you use a shader like this...
```
shader_type spatial;

varying flat vec3 norm;

void vertex()
{
	norm = NORMAL;
}

void fragment()
{
	NORMAL = norm;
}
```

...you can get flat normals on the built-in sphere:
![img](https://user-images.githubusercontent.com/31383123/38992635-a0de02ec-43e1-11e8-8c88-053174aa23c1.png)

**Comment by insomniacUNDERSCORElemon** [comment]
This can be marked as fixed because of the 'smooth faces' option present within the CSGPrimitave nodes (in 3.1 alpha 4 at least, not sure when it was first implemented).

Thank you.

**Comment by Zireael07** [comment]
CSG is a nice workaround, but built-in primitives != csg.

**Comment by insomniacUNDERSCORElemon** [comment]
@Zireael07 I'm not sure what you're saying. Are you nitpicking the term because a single element is not "constructed"?

Otherwise, the older parametric models (the ones now used through CSGMesh) do offer a bit more options (particularly cylinder upper/lower height, capsules, hemisphere mode) yet those still don't have the smooth faces option. Those are relevant to this because this issue is related to quick prototyping (or actually using parametric models, like for a minimalist look) but would be best for another issue.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Wolfe2x7** [comment]
I found this issue while searching around, but I ended up figuring out how to make a hard-edged copy of a primitive with a quick script. I'll share it here for future seekers:

```
# Create array mesh from primitive
var prim_mesh = ArrayMesh.new()
prim_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, mesh.get_mesh_arrays())

# Create MDT to read mesh and ST to create copy
var mdt = MeshDataTool.new()
mdt.create_from_surface(prim_mesh, 0)
var st = SurfaceTool.new()
st.begin(Mesh.PRIMITIVE_TRIANGLES)

for f in mdt.get_face_count():
    for v in 3:
        st.set_normal(mdt.get_face_normal(f))
        st.add_vertex(mdt.get_vertex(mdt.get_face_vertex(f, v)))
    var arr_mesh = st.commit()
    ResourceSaver.save(arr_mesh, "res://output.tres")
```
