### ISSUE TITLE
HTML5 template is broken in 1.1rc2

### ISSUE THREAD

**Issue by vkbsb** [godotengine/godot#1828]
The html file exported refers to a js file that is generated at compile time. 
The js file is renamed while packaging the template. This should be done in the html file as well.

Please  use the following url to update building the template for html5.
https://github.com/vkbsb/godot/wiki/export_html5

Also here are the compiled javascript exporters for 1.1rc2
https://drive.google.com/folderview?id=0B_En8WVyy_2SflRHc3pzTFFfdUp5NmJSbmF1SHphNi1VX2c4NDdfV1RQNldvdlY3WVRJOTg&usp=sharing

**Comment by Angluca** [comment]
Well, It's ok! I can run game on the browser now.

**Comment by OlexiyKravchuk** [comment]
I did try to export it in different systems ... Windows Vista x32 and Windows 7 x64, the windows 7, exported game just open the browser, but there was only black text box, and Vista x32, Godot told that there is no template debug version, but it was there on the spot, then I copied it to another folder, and pointed the way by hand, and then I got the same result as in windows 7.
What do you recommend me? I have been unable to run the game, for testing I used the latest version of the demo (platformer) 2D, with a (robot).

**Comment by reduz** [comment]
vkbsb: What version of emscripten are yo using? I think mine may be outdated

**Comment by vkbsb** [comment]
@olexy ..use the templates from the url I provided in my comment.

@reduz I'm using 1.29 the latest one.

**Comment by Angluca** [comment]
@reduz 
Maybe you can use emsdk.
https://github.com/juj/emsdk
I often use it compile another projects.

**Comment by vkbsb** [comment]
This is where i downloaded from.. http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html

**Comment by OlexiyKravchuk** [comment]
@vkbsb
Exactly what I use, because the one that was in the delivery set on the download page, generally refused to work, anyway.

**Comment by OlexiyKravchuk** [comment]
that's what I see when I try to run ...
http://snag.gy/7dTXF.jpg

**Comment by reduz** [comment]
@vkbsb think you could go into irc at some point these days and lend me a hand? as I'm unable to create working templates and i'm not sure why

**Comment by vkbsb** [comment]
Let me know the time..I live in India hard to get overlap time..

**Comment by vkbsb** [comment]
Reduz is this done?

**Comment by reduz** [comment]
nope, I still don't understand what to do and seem to have forgotten how to
make it work...
Is the filesystem thing used in the old versions still useful? what steps
did you follow to get the template working?

**Comment by vkbsb** [comment]
Yes the filesystem js still works. 
Have you been through this https://github.com/vkbsb/godot/wiki/export_html5

**Comment by trond** [comment]
I fixed it by adjusting the exporter for javascript (https://github.com/trond/godot/commit/7c653550a63c13cbfe83a925ff4a63519d6b42a0), but your solution seems cleaner @vkbsb.

As a workaround for now, I don't think you actually have to rebuild the templates from source to fix it (which turned out to be horribly difficult, so far I've only been able to do it on MacOSX), an easier way could be to do only the last part of your guide:

* locate javascript_debug.zip and javascript_release.zip in "~/.godot/templates" or "%APPDATA%\Godot\templates"
* extract javascript_debug.zip
* edit godot.html at the bottom by changing src="godot.javascript.opt.js" to src="godot.js"
* re-zip godot.html filesystem.js godot.js into javascript_debug.zip
* do the same for javascript_release.zip

I guess it's important that when you do "extract here" no folders should be generated.

I tested this on MacOSX after installing official templates. Should work on Linux too, I guess.

    cd ~/.godot/templates
    unzip javascript_release.zip
    sed -e 's/godot.*js/godot\.js/' godot.html > godot_result.html && mv godot_result.html godot.html
    zip javascript_release.zip godot.html godot.js filesystem.js

    unzip javascript_debug.zip
    sed -e 's/godot.*js/godot\.js/' godot.html > godot_result.html && mv godot_result.html godot.html
    zip javascript_debug.zip godot.html godot.js filesystem.js
    
    rm godot.html
    rm godot.js
    rm filesystem.js

**Comment by punto-** [comment]
So this would be a patch to the script here:
https://github.com/okamstudio/godot/wiki/compiling_batch_templates ?

**Comment by trond** [comment]
Yeah, didn't think of that, I guess you could do the "sed" command instead of the copy:

    #cp bin/godot.javascript.opt.html godot.html 
    sed -e 's/godot.*js/godot\.js/' bin/godot.javascript.opt.html > godot_result.html

**Comment by trond** [comment]
Turns out that more recent versions of Emscripten generates another file, **something.html.mem**, by default, for example **godot.javascript.opt.html.mem**, which then is referenced from **godot.js**. This also needs to be handled by the packaging script (including it in the **javascript_config.zip** files), otherwise the runtime will fail with the following error:

    http://localhost:8000/godot.javascript.debug.html.mem 404 (File not found)

If you want it to be renamed like the rest on export from the editor, **export.cpp** needs some modification as well. Looks like it's possible to disable this extra file, but apparently it's good for loading times and other issues. See **Memory Initialization** here: https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html

**Comment by eska014** [comment]
I think this is fixed since around 0fb7b5aa0c023d60880d259e70f7641152460aa6. Please comment if this same error persists or open a new issue.
