### ISSUE TITLE
Playing = True in AudioStreamPlayer in editor plays to primary audio device

### ISSUE THREAD

**Issue by serapth** [godotengine/godot#18301]
**Godot version:**
3.0, Windows version with Mono, although I doubt it matters

**OS/device including version:**
Windows 10 Pro

**Issue description:**
The editor audio will play on your device ( AKA, my laptop speakers ), even though I've set primary audio device to bluetooth headphones.  All other audio is redirected to the headphones normally, as is game audio when run.

**Steps to reproduce:**
At least on Windows 10, create an AudioStreamPlayer2D, assign an audio file to it, set it to loop = on and playing = on.

**Comment by marcelofg55** [comment]
I've just tested this on latest master and it worked as expected: I've played some audio on the editor, changed default device and the editor kept playing the audio on the new default device.
Can you test this again with latest master?

**Comment by Calinou** [comment]
@serapth Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
