### ISSUE TITLE
Add support to open offline documentation from engine.

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#18309]
**Godot version:**

Godot 3

**Description:**

This is not bug. Well it as a suggestion to improve the engine.

In the current version when you click Online Docs in script view you will be redirected to http://docs.godotengine.org/ and also the Online Tutorial section in the build-in class reference also redirect to online doc. If this implemented it, instead of redirected to online docs it will redirect you to downloaded documentation.

**Reason why this feature should be implemented**
1. You can download the tutorial and documentation (as html) from http://docs.godotengine.org/
2. The build-in class reference is very great, but it not cover the Tutorial part.
3. There are users who work with the engine while not connected to Internet.
4. It is optional, so if you dont want to download the tutorial documentation you dont have to do it.

**Suggestion how it should be implemented**
1. New field to target the offline documentation file should be added to Editor Setting. "Offline Documentation Path" for example.
2. When the above field is default, Empty, or not valid the Online Docs button at the Script View and also the Online Tutorial section in class reference will be redirected to http://docs.godotengine.org/
Else, it will redirect to the downloaded docs.

That's all, you should consider to implement this feature. Thank you.

**Comment by GameingTwist** [comment]
+1 
i agree we need to have something like this

**Comment by Phoenix1747** [comment]
Aggreed, why not bundle the latest documentation and offer it for download like the export templates.

However, there is a big downside to this. Firstly, the documentation get's updates independently from the engine updates, so this would lead to partly outdated or incomplete documentation on the long run. Secondly, you have to have another maintainer doing all the documentation releases, i.e. packaging and uploading them.

If what's your suggestion is that you enable the offline doc in the settings and then everytime your machine get's access to the Internet it is queried for the latest files and updates them for offline use, then OK :D

**Comment by earlroxas13** [comment]
@Phoenix1747 By Bundle the latest doc, did you mean it should be opened in godot engine not opened in web browser as html?

if you want to download the documentation as pdf, html, or epub you can just download it from the doc page.
![image](https://user-images.githubusercontent.com/8316851/39221942-0a09bd3e-4864-11e8-9ce2-ffdace7baf45.png)

Regarding querying latest files, can it be done by Sphinx or Read the Doc? I dont know how they works tho.

**Comment by mhilbrunner** [comment]
Would be kind of solved by https://github.com/godotengine/godot-docs/issues/252
Also, be aware not everything currently works in the offline PDF/EPUB downloads: https://github.com/godotengine/godot-docs/issues/1352

**Comment by akien-mga** [comment]
If you want offline docs, it's already possible as mentioned, since you can download them in HTML, PDF or Epub. Of course, you won't get updates from the many changes done in the docs repo.

You can also build them from source in HTML, PDF, Epub or more with Sphinx: https://github.com/godotengine/godot-docs
This way you can keep them offline + relatively up to date if you compile e.g. once a week to get changes.

For all of the above, no change is needed in the editor.

Now, for the proposal to make the link to the online docs a configurable link to the offline docs, I don't see much point to be honest. That link is there for discoverability, so that people know that the docs exist. If you downloaded docs offline, you do know that they exist, and you can set your own bookmark in your favourite browser to open them easily, or even a shortcut on your desktop.

What would be useful is to have the docs displayed *in Godot* like the API reference, but that would mean either:
- Parse all the content from the .rst files in the godot-docs repo to generate something that can be compiled into Godot and displayed using native Controls (*huge* work)
- Integrate a web rendering engine in Godot (*huge* dependency, bloat and security burden)

So all in all the cons outweigh the pros, and since it's simple enough to get offline docs already from outside the editor, I don't think more work will be done in this area.

As @mhilbrunner mentioned, there are also some nice offline doc readers available for which the Godot documentation could be packaged, but this is to discuss in the godot-docs repo.

**Comment by spazmantiz** [comment]
the are outdated

**Comment by bbugh** [comment]
There is no longer a Download link on the godot docs, is there a different way to download them now?

<img width="305" alt="image" src="https://user-images.githubusercontent.com/438465/160247199-93675a61-632a-4e77-aff9-da56901f95c3.png">

**Comment by akien-mga** [comment]
See this part on the landing page:
![image](https://user-images.githubusercontent.com/4701338/160247536-9f9d194b-8225-4d26-aabc-a01624aad169.png)

https://docs.godotengine.org/en/stable/

**Comment by Zireael07** [comment]
Can this info get put somewhere in the editor itself? (The About screen, or a tooltip on the Docs button strike me as good places)

**Comment by Calinou** [comment]
> Can this info get put somewhere in the editor itself? (The About screen, or a tooltip on the Docs button strike me as good places)

The download link isn't guaranteed to be permanent (e.g. if [nightly.link](https://nightly.link) shuts down), so I'd prefer not.

**Comment by akien-mga** [comment]
> The download link isn't guaranteed to be permanent (e.g. if [nightly.link](https://nightly.link/) shuts down), so I'd prefer not.

And it's also only valid for the current `stable` docs, so any older Godot version would actually be linking to a version of the offline docs which might be too new and incompatible.

**Comment by bbugh** [comment]
Yeah, I'm looking for branch-specific docs. [build_offline_docs.yml](https://github.com/godotengine/godot-docs/blob/master/.github/workflows/build_offline_docs.yml) doesn't exist on any of the version branches like [3.4](https://github.com/godotengine/godot-docs/blob/3.4/.github/workflows/build_offline_docs.yml) so nightly.link doesn't work for those. It does have [stable](https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master) on though. 

Seems like the only way to get version-specific ones now is to download and build them.

**Comment by Calinou** [comment]
> Yeah, I'm looking for branch-specific docs. [build_offline_docs.yml](https://github.com/godotengine/godot-docs/blob/master/.github/workflows/build_offline_docs.yml?rgh-link-date=2022-03-26T19%3A06%3A06Z) doesn't exist on any of the version branches like [3.4](https://github.com/godotengine/godot-docs/blob/3.4/.github/workflows/build_offline_docs.yml?rgh-link-date=2022-03-26T19%3A06%3A06Z) so nightly.link doesn't work for those. It does have [stable](https://nightly.link/godotengine/godot-docs/workflows/build_offline_docs/master) on though.

Scheduled workflows only run on the repository's default branch, so the `master` branch builds both `latest` and `stable` offline docs.
