### ISSUE TITLE
Suggestion: Upload releases to Github

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#18329]
***Bugsquad edit: Use [this unofficial mirror](https://archive.hugo.pro/godot-tuxfamily/) if TuxFamily is too slow.***

___

I've noticed that both tuxfamily and op.godotengine.org very often offer very poor download speed (sometimes less than 100KB/s). Maybe this happens only in Argentina but I've tested it with different machines and different ISPs. I've spent an hour downloading export templates with the same connection that would otherwise download the same amount of data in a couple of minutes. 

I never had issues downloading releases from the release tab on github projects. Github allows creating releases and uploading binaries of up to 2GB. Is there a reason why you're not using that feature?

More info: https://help.github.com/articles/about-releases/

**Comment by mhilbrunner** [comment]
Definitely doesn't only from Argentina, experienced that from germany and UK sometimes as well. Made a bad first impression on my initial download.

**Comment by Shin-NiL** [comment]
Yeah, very slow download from here too (Brazil).

**Comment by ShyRed** [comment]
Might want to start to include source tarball as requested in #18347 while we're at it...

**Comment by Phoenix1747** [comment]
Also experienced slow downloads before, but it's quite random. Sometimes it downloads with my typical internet speed and sometimes it's just like 200 KB/s.

Your suggestion to upload releases to Github applies to the export templates right? Because the engine release are indeed on Github. Maybe the Godot team should consider adding the export templates to the individual releases and linking the website downloads to the releases here on Github.

**Comment by mhilbrunner** [comment]
The download link on the website points to https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_win64.exe.zip for me. Not GitHub.

Also yes, it varies a lot: sometimes it saturates my workplaces fiber connection, sometimes its < 20kb/s.

**Comment by Phoenix1747** [comment]
> The download link on the website points to https://downloads.tuxfamily.org/godotengine/3.0.2/Godot_v3.0.2-stable_win64.exe.zip for me. Not GitHub.

Yeah but they are already (also) here on Github https://github.com/godotengine/godot/releases

**Comment by mhilbrunner** [comment]
They aren't? That are only the sources, as far as I can see, not compiled binaries.

**Comment by Phoenix1747** [comment]
That's true but you can easily compile the sources, you don't need precompiled binaries ;)

**Comment by Phoenix1747** [comment]
It's much more easy to compile on Linux than on Windows because you already have most if not all requisits. And because Windows has the biggest market share on the PC market and not at last because it's unnecessary you have binaries. Although I have to say having a bit of backend experience doesn't harm you if you seriosuly want to create your own game from scratch.

If you're really annoyed by the extremely slow download speeds then just download the source from github and take your time to compile it, maybe that's faster for you ;)

**Comment by mhilbrunner** [comment]
>If you're really annoyed by the extremely slow download speeds then just download the source from github and take your time to compile it, maybe that's faster for you ;)

On a first compile? Thats slow too. Honestly, *if I'm annoyed by the extremely slow download speed*, the solution is to *fix the download speed*. Because otherwise, I'm not going to try to fix it by compiling myself, I'm just going to download *<competing engine that seems to care about UX and my experience, including the download speed>*. Not sure why this is an argument.

**Comment by Phoenix1747** [comment]
1. I've never said "just compile it and fix it yourself".
2. Compiling didn't take very long at all on my rather slow laptop.
3. Servers cost money and sometimes they can slow down because of too much traffic.
4. If the download speed's the only thing keeping someone from switching to another engine then they should just leave.

Anyways, I'm genuinely sorry to have mentioned compiling as an option.

**Comment by noidexe** [comment]
@Phoenix1747 I'm trying to say this as politely as possible so I hope it doesn't offend you. There is always at least one person and usually more than one with that "RTFM" attitude in every OSS project and it drives users away much more effectively than download speeds and asking every user to waste time learning how to fix what could be easily solved from the developer end is just [bad engineering. ](http://www.catb.org/esr/writings/cups-horror.html).

So:
1 - Yes you said exactly that [here](https://github.com/godotengine/godot/issues/18329#issuecomment-383879594) and [here](https://github.com/godotengine/godot/issues/18329#issuecomment-383884971)
2 - It doesn't matter how fast it compiles. We already have prebuilt binaries for every release. Why on earth would you force the user to learn how to do it when it's not necessary. 
3 - AFAIK Github doesn't charge for hosting binaries so this is irrelevant
4 - Hell no. If your users have a problem and you can easily fix it you fix it you don't blame them.

**Comment by mhilbrunner** [comment]
@Phoenix1747 Sorry if I got you wrong then, I agree that compiling from source is a good way to avoid the download if someone is comfortable with it. 

But we should see to it that downloading is a good experience too.

**Comment by Shin-NiL** [comment]
If there's no charge from github for hosting the binaries I don't see why don't have a mirror here.

**Comment by eon-s** [comment]
I have issues only downloading templates from the game engine, not outside (still slow but not slow as downloading from the engine).

Maybe, as an extra option, some releases of GodotBuilder can be linked on this repository and official site.

**Comment by vnen** [comment]
@akien-mga you can get the download count of release assets using the GitHub API.

**Comment by Phoenix1747** [comment]
@akien-mga You can look up individual release downloads and total downloads via the Github API, e.g. Shields.io uses this too.
Am 01.05.18, 18:09, George Marques <notifications@github.com> schrieb:
@akien-mga you can get the download count of release assets using the GitHub API.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/godotengine/godot","title":"godotengine/godot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/godotengine/godot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@vnen in #18329: @akien-mga you can get the download count of release assets using the GitHub API."}],"action":{"name":"View Issue","url":"https://github.com/godotengine/godot/issues/18329#issuecomment-385710669"}}}

**Comment by Calinou** [comment]
I've set up an unofficial mirror for Godot releases [here](https://archive.hugo.pro/godot-tuxfamily/), in case anyone stumbles upon this page because downloads from TuxFamily are slow.

**Comment by Xyrio** [comment]
github shows downloads using the api which is publicly accessible. so unless you want to keep it a secret you can see download counts like so:
https://api.github.com/repos/electron/electron/releases/tags/v8.0.0-beta.9
https://api.github.com/repos/godotengine/godot/releases/tags/3.2-stable

**Comment by Calinou** [comment]
@Xyrio I noticed this yesterday after setting up [Refined GitHub](https://github.com/sindresorhus/refined-github) with an API key :wink:

**Comment by Xyrio** [comment]
just for clarification, the links dont need an api key.

**Comment by decepticlown** [comment]
@Calinou any chance for those unofficial links to become official? Like, integrated in Godot?

**Comment by Calinou** [comment]
@decepticlown I don't think so, Akien still needs to look at setting up a proper mirror infrastructure.

**Comment by Xyrio** [comment]
*sigh* and again waiting hours to download 56.5 MB

**Comment by nikhilCad** [comment]
I only get 80kBps on a fast wifi connection. Please fix this issue. Unity is so easier to download despite its huge size because of fast servers.

**Comment by Calinou** [comment]
@nikhilCad Use the mirror linked in the first post in the meantime :slightly_smiling_face:

**Comment by wmnnd** [comment]
@Calinou Thanks for the mirror. After waiting over 20 minutes for the official download, I was almost about to give up on *Waiting for Godot* :wink:

**Comment by Jacalz** [comment]
I don't mean to be rude, but this has been open for two years now and I think this really needs to be solved. When I tried to download Godot 3.3 Win64 today, I just could not download them from the linked site because the connection is insecure.

![image](https://user-images.githubusercontent.com/25466657/116530333-30ced700-a8de-11eb-813a-a0588b265002.png)

This leads to a very poor user experience when downloads are impossible for users to download. Adding the binaries to GitHub should not be a very hard thing to do. Also feel way less sketchy than downloading from an old-looking third-party site like https://www.tuxfamily.org/. I hope you can consider doing this change.

**Comment by Calinou** [comment]
The certificate of downloads.tuxfamily.org appears to be invalid here:

![image](https://user-images.githubusercontent.com/180032/116556522-d2b1ec00-a8fd-11eb-829c-c9b7aad70014.png)

Are you using a third-party antivirus program or something that may interfere with SSL?

**Comment by Jacalz** [comment]
I suspect that my school network might be doing something strange then. I can reach the main site but the download links are not working.

Your mirror @Calinou, mentioned above, saved me. Thanks 👍

**Comment by Zireael07** [comment]
School or university networks often run 3rd-party firewalls or site blockers, often not even hosted on premises so if you run into issues, they can't help you (speaking from experience, back when I was at school I used the internet extensively as it was a mile better than what I had at home - and I often had completely normal sites blocked, like RPG/fantasy forums, while the firewalls did let p0rn and/or viruses through on at least two occasions)

**Comment by Xyrio** [comment]
fyi: another (torrent) way to download godot including the bigger downloads:
https://fosstorrents.com/games/godot-engine/

**Comment by Calinou** [comment]
Files for 3.3.2 and 3.3.3 are now mirrored on GitHub Releases: https://github.com/godotengine/godot/releases
