### ISSUE TITLE
Alpha channel in WebM files is not used during the compositing

### ISSUE THREAD

**Issue by Francois-Grassard** [godotengine/godot#18337]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10 x64
GPU : GTX1080

**Issue description:**
I try to use some WebM video files in my project, but more precisly WebM with Alpha Channel. This is super useful when you want to live composite some "lowerthird" other background elements (or other video streams).

I'm a professionnal broadcast engineer who try to integrate Godot 3 in my workflow for realtime purpose.

I already read the whole topic about the integration of WebM in Godot (thank you for that, Zaps166 !) : 
https://github.com/godotengine/godot/issues/5886

**Steps to reproduce:**
Load the provided project and run it

**Minimal reproduction project:**
I provide a really simple test project, containing a WebM file with an alpha channel. The RGB channels was written in "Straight" mode (not premultiplied), so you don't have to divide the color values by the Alpha (to unpremult the color) before the compositing. By this way, I guess it should be easier for you to implement this feature. 😃

[WebM_AlphaChannel.zip](https://github.com/godotengine/godot/files/1934683/WebM_AlphaChannel.zip)

You can drag and drop this *.webm file in Google Chrome to check the content, premultiplied by the alpha. Thank you for your wonderful work !

**Comment by ShyRed** [comment]
Might be related to #8334 ?

**Comment by LinuxUserGD** [comment]
https://godotengine.org/qa/25657/webm-video-with-alpha-channel

**Comment by Francois-Grassard** [comment]
Thank you for you feedbacks ! I'm happy not to be the only one to ask for this feature :)

**Comment by Crystalwarrior** [comment]
Any progress on this feature?

**Comment by Calinou** [comment]
@Crystalwarrior There's no ETA on this feature. Anyway, we're now closing feature proposals as they need to be reopened on the Godot proposals repository :slightly_smiling_face: 

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
