### ISSUE TITLE
godot editor make my mac air hot

### ISSUE THREAD

**Issue by zhuofeijian** [godotengine/godot#18375]
**Godot version:3.0

**OS/device including version:10.13.4

**Issue description:it takes about 60% cpu

**Steps to reproduce:when editing the dodge_3.0 main scene

**Minimal reproduction project:https://github.com/kidscancode/Godot3_dodge/releases v1.3

**Comment by ShyRed** [comment]
Hi @zhuofeijian ,

Godot 3.0 is outdated. Please make sure to use the newest version which is Godot 3.0.2 as it has a lot of bugfixes and new features.

That being said, it seems that the game might be leaking objects? No idea, if it is a bug in the game or in the engine, though.

Tested with master @ 06c5a9e

![image](https://user-images.githubusercontent.com/1138805/39136449-91b32c92-471b-11e8-8912-6f7cb5a95d0c.png)

**Comment by ShyRed** [comment]
This is **not** a bug in the engine.

Turns out that the method

```
func _on_Visibility_screen_exited():
	queue_free()
```

in Mob.gd is not connected to anything. Enemies are getting spawned and never freed. Solution is to connect the Visibility-node's `screen_exited` event in the Mob.tscn to this function.

You might want to get in touch with @cbscribe to fix the bug or just fix it yourself and do a pull request to the https://github.com/kidscancode/Godot3_dodge repository yourself.

**Comment by ShyRed** [comment]
Sorry for spamming this issue. I just noticed that you were talking about the editor and not the game itself.

I can confirm that the Main scene is quite heavy on the CPU. It nearly eats a complete core on my AMD Phenom II X6 1090T (debug build of Godot).

Looking into the scene the CPU usage goes down to nearly zero when turning off visibility of the player. The player's particle system seems to eat **a lot** of CPU. It would be really nice, if we could tone down CPU usage or at least pause the particles.

Related to #16397

**Comment by Zylann** [comment]
Is it only the particles though? They not only render, but they cause the editor to redraw.

**Comment by Phoenix1747** [comment]
Just tested it and it's the `Particle2D` Node for your player's "Trail". Hiding that immediately improves performance by like 90%. Also you're right @Zylann, the Editor has to constantly redraw because of this which is the reason for the performance hit.

I don't exactly know why the editor repaints this often though.

**Comment by akien-mga** [comment]
This issue is a bit difficult to work with as it mixes project-specific issues (which should be reported at https://github.com/kidscancode/Godot3_dodge ), and discussion on the performance cost of having `Particles2D` running in the editor. I'd suggest to move the discussion on that latter point to #16397 instead.
