### ISSUE TITLE
More 2D joints/constraints

### ISSUE THREAD

**Issue by xerosugar** [godotengine/godot#18389]
Godot currently only has 3 types of 2D joints/constraints (Pin, DampedSpring, Groove). Having used other 2D physics libraries, I think the list could be expanded a bit. The one I have the most experience with, is one called 'Nape' and this is the list of constraints for that library:
http://napephys.com/help/manual.html#Constraints #

**Comment by ElfEars** [comment]
I'm still not sure why hinge is 3d only tbh. Hopefully we can get a 2d version of that as well as some of these cool joints :)

**Comment by pwab** [comment]
I'm also interested in getting more convenient joints/constraints for 2D. WeldJoint and PulleyJoint from Nape would be quite interesting for Godot too.

As the website for napephys has changed, here is the updated link:
https://joecreates.github.io/napephys/help/manual.html#Constraints

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot-proposals/issues/756 for PulleyJoint and https://github.com/godotengine/godot-proposals/issues/86.

__

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
