### ISSUE TITLE
Godot should have native support for Google Play Games like it has for Apple GameCenter

### ISSUE THREAD

**Issue by munirehmad** [godotengine/godot#18392]
**3.0:**

**OS/device including version:**
Android/Any

**Issue description:**
It's really a huge deterrent to compile Godot just to use a module for Play Services written by someone else, and IMO a huge turnoff for new people, specially people that want to use Godot for Mobile Game dev and want to ditch Unity for good.

Since Godot is already providing [Android In-App Purchases](http://docs.godotengine.org/en/3.0/tutorials/platform/android_in_app_purchases.html#android-in-app-purchases), and [iOS Game Center integration](http://docs.godotengine.org/en/3.0/tutorials/platform/services_for_ios.html), the Android services can easily be extended by adding support for Play Games Services.

**Comment by munirehmad** [comment]
I can try to implement this if there's enough need for it tho. As I need it for my games going forward..

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
