### ISSUE TITLE
Unshaded + Ambient Occlusion + Outlines viewport mode

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18418]
For level designing it's a bit hard to see in Unshaded mode when several objects have the same color, to see if the objects touch eash other. An Unshaded + AO + Outline option would fix that and an option for pseudo colors (uses a random color for each object). Something similar to the Workbench engine of Blender: https://twitter.com/tonroosendaal/status/991709311293448192

![unshaded](https://user-images.githubusercontent.com/30020215/39538766-26a570ca-4e3e-11e8-86e9-2163a222a95a.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
