### ISSUE TITLE
Feature suggestion: re-snapping automatically the selected assets

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18419]
To level design with modular assets we use the snapping to place the assets, but sometimes we forget to snap an asset correctly and all their duplicates aren't on the grid. I suggest a useful feature like in Unity to re-snap every selected assets. The snapping can also work with rotation, for example with an angle of 15 it will only use a multiple of this value, same for the scale.

The default values should be: translation at 1/1/1, scale 0.1 and rotation 15 degrees.

![snap selection](https://user-images.githubusercontent.com/30020215/39256658-be25e3e2-48af-11e8-8afa-58fd947d91a1.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
