### ISSUE TITLE
World texel density for the lightmap baking

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18420]
Currently we need to specify the texel density of each asset, if we want to double it we need to edit the value for every assets one by one. It would be good to have a setting in the lightmap bake node to set the texel density per grid unit and it would generate the same quality between every assets in the scene.

**Comment by Calinou** [comment]
Note: This may have been implemented in the upcoming [new lightmapper for 4.0](https://godotengine.org/article/godot-40-will-get-new-modernized-lightmapper), but I'm not 100% sure. Please verify this before opening a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
