### ISSUE TITLE
FPS mode in the viewport with gravity and collisions

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18424]
Godot allows to navigate in the viewport while holding the right mouse button and using WASD and Shift, but I could suggest to have a shortcut to enter in FPS mode like Blender's Shift + f shortcut and to have an option to enable the gravity and collisions. This would allow to test our level and the proportions of the assets, the size of the corridors, etc.

**Comment by Zylann** [comment]
There is an alternative shortcut already to toggle fly mode, which is Shift+F too.

However, if you want to use that mode to play as a character in a level, there are quite a lot of things to consider:
- Your scene needs colliders
- Your scene needs to be playable
- The editor needs a way to figure out how big your character would be
- Why not just drop a character controller scene and play the scene?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
