### ISSUE TITLE
Spatial editor's view settings aren't applied immediately after changing them

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#18430]
**Godot version:** Git https://github.com/godotengine/godot/commit/e8ff602381edc2bf8ba56de85b50c275c17f9a0c

**OS/device including version:** Fedora 27

**Issue description:** The spatial editor's view settings aren't applied immediately after changing them, or even after clicking the Close button of the Settings dialog. Changes will be displayed only once the editor camera is moved by the user somehow, even if the editor update mode is set to **Update Always**.

**Steps to reproduce:** Switch to the editor's 3D view, go to the **View** → **Settings** menu at the top of the 3D viewport, adjust FOV/Z-Near/Z-Far values then close the settings menu. The displayed values won't change until the editor camera is moved somehow (for instance, by looking around or zooming).

**Comment by Amssat221** [comment]
@MelvinWM 
Hey, for this issue, should we also add a refresh button for this one?

**Comment by Calinou** [comment]
I can confirm this issue is still present in https://github.com/godotengine/godot/commit/cdcdba704b989aa9d7decc40d3181f8378378512, by the way.

@Amssat221 It would be better to fix the original issue rather than adding a Refresh button (which would be a workaround that makes the GUI more complex).

**Comment by MelvinWM** [comment]
@Amssat221 I agree with @Calinou , it makes sense to add a button in the other issue reg. editor settings, since the editor settings there cyclically affects the GUI for the editor settings themselves, while that is not the case here. I imagine a good solution might be to instruct the 3D view to update or similar when pressing OK or exiting and saving the settings some other way.

(as a side-note, pressing 'Cancel' in the settings for the 3D view after making some changes seemingly still applies the changes as seen when zooming in or out, instead of having the changes dropped, which seems wrong).

**Comment by Amssat221** [comment]
I will work on that. Thanks

**Comment by Amssat221** [comment]
@Calinou, I went over the problem of the cancel button not working and it makes me believe that the issue is related to ConfirmationDialog in dialogs.cpp. Could you please confirm it
