### ISSUE TITLE
Add Post-Processing Exception Flag to Materials

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#18445]
(This is a feature proposal for rendering)
Currently, all materials are affected by the post-processing shaders. This makes using 3D editor elements difficult, such as when the 3D gizmo overlays a depth-of-field effect. I think that editor tools should be made exempt from post-processing shaders, and that functionality should be exteneded to user-made ShaderMaterials and SpatialMaterials.

![image](https://user-images.githubusercontent.com/1891696/39311692-776830ea-4922-11e8-8fa1-3111e7837e39.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment]
Aren't gizmos already excepted from post-processing in master?

**Comment by Calinou** [comment]
@Zireael07 Last time I checked in `master` (https://github.com/godotengine/godot/commit/24ad4894ccf38a904f4bc931ffd4c1d63d382dcc to be precise), they were still affected by depth of field at least:

![image](https://user-images.githubusercontent.com/180032/82933684-99089080-9f8a-11ea-897f-25d9048168d5.png)
