### ISSUE TITLE
Image.bumpmap_to_normalmap issues

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18490]
Godot 3.0.2

I had a look at this merged PR https://github.com/godotengine/godot/pull/16898/files
Which adds a way to convert a bumpmap into a normal map, and I see issues with it in the context of making heightmap terrains, especially when baking normals.

1) It only works on `float` images

I am baking normals in GDScript in my terrain plugin when the terrain is painted, which is one of the performance bottlenecks. I was interested in this PR because it allows me to offload this to the C++ implementation in Image. However, my heightmap uses a 16-bit image. In other words, I use `half`, or `unsigned short`, not `float`. So I can't use this method... (or at least, not efficiently since I need to convert back and forth everytime)
EDIT:
Actually, it might be faster that way because accessing half-precision floats is slower than float, I think. However, that means the function scales very badly in memory if the image is super big, as it requires to copy the image (hence why a chunked approach is best anyways)

2) It performs wrapping, with no option to clamp

The function wraps pixels so that the resulting normalmap tiles. This is good, but again, I have to dodge it in my terrain system because my textures don't need to wrap, they need to be clamped instead because I process them in chunks and the terrain doesn't wrap, so I end up working with a margin, which works except for map borders and for streamed maps (wich aren't made of a single texture, but many).

3) It derivates the bumps in +X and +Y only

I'm not sure if that's really an issue, but I noticed the method generates the normalmap by only looking at the current pixel, the one on the right and the one on the top. Last time I tried this in my terrain system, it produced directional artifacts. For example, the top of a symetric mountain would be brighter on one side than the other (it's quite subtle though, and mostly noticeable when you do heightmaps). I changed my implementation to also look at the left and bottom pixels, which fixed that.

**Comment by akien-mga** [comment]
CC @Lerc

**Comment by Lerc** [comment]
1. Seems to be due to the lack of a FORMAT_L16 or similar.   This, I think, means we might need a discussion about what the Image class is for.    Its primary use is wrangling textures to pass to the GPU, but it also has a secondary use as a general image manipulation class.   (blit_rect, get/set_pixel,  expand_x2_hq2x, flip_x,flip_y, normalmap_to_xy) are examples of that secondary use.   

There isn't a lot of need for a FORMAT_L16 on the GPU side, but it is clear that it can be useful on the image manipularion side.    Similarly I wasn't entirely happy using FORMAT_RF for bumpmap_to_normalmap but it was the only single value float format available.   I would have preferred to have a FORMAT_LF  if for no other reason than when converted to FORMAT_RGBA8 it becomes grey instead of red. 

2. Seems a valid issue,  clamp/wrap seems to be a choice that all image manipulation functions might need.   Almost to the point where I'd think wrap/clamp/zero should be part of Image state.   While it would be cool to support it for things like blit_rect, implementing it would be less so.  I should note that it wouldn't fix the chunkedterrain issue (both wrap and clamp would generate artifiacts without sampling the broader area)

3.  More samples, good, but slower.  Might be worth.

**Comment by Zylann** [comment]
FORMAT_L16 is useful as heightmap, even on GPU. In fact I probably would have used that if I could, instead of RH, because halfs loose precision over distance and are slower to manipulate on CPU. (only difference is, it needs explicit min/max mapping).

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot-proposals/issues/659.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
