### ISSUE TITLE
Front view is confusing

### ISSUE THREAD

**Issue by rminderhoud** [godotengine/godot#18517]
**Godot version:**
6faa96fb89ab33fe3a6b37eecca1c7cf2934ff75 (April 24th)

**Issue description:**
Switching to the "Front View" in the 3D viewport points down -Z but as far as I understand the -Z is used as the forward direction (e.g. in `look_at()`) so you are technically looking at object from the back? So if you orient your mesh to the "front view" and then technically your mesh is backwards.

Causes confusion:
* https://github.com/godotengine/godot/issues/16088
* https://github.com/godotengine/godot/issues/15283
* https://www.reddit.com/r/godot/comments/7uliqi/look_at_looks_exactly_at_the_opposite_direction/

**Steps to reproduce:**
Transform: 0, 0, 0
Rotation: 0, 0, 0
Mesh facing +Z

![image](https://user-images.githubusercontent.com/1752584/39412512-ffb02094-4be2-11e8-8f0b-5f1f87a1a965.png)

**Comment by romlok** [comment]
Perhaps it would be less confusing if "front" were renamed to "forward"?

Unfortunately, that might then cause confusion over whether the "right" view is the view *to* the right (same context as "forward", but incorrect), or *from* the right (same context as "top", and correct).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by hawkerm** [comment]
I will say this is still really confusing, and I didn't find the docs helpful here.

The right-handed graphic makes it seem like +Z should be coming out of the screen towards you, which is what you would think the 'front view' would be showing you, especially when it's gimble clearly shows a 'Z' and not a blue dot:

![image](https://user-images.githubusercontent.com/8959496/226820598-ced99061-6cd0-44f3-b2e9-e14696ec0aea.png)

But as soon as you grab it and manipulate it, you indeed see that +Z is going 'into' the screen:

![image](https://user-images.githubusercontent.com/8959496/226821060-a9e5656e-8455-4c64-8b2c-8bc3929e88d5.png)
