### ISSUE TITLE
Option to set Linux WM Class on export

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#18510]
**Godot version:**
All versions

**OS/device including version:**
Ubuntu etc...

On Linux based systems the application indicator is identified by something called a WM Class, it's used to group linked windows to the same launcher icon. When exporting a project to Linux the exported projects keeps the same WM classes : `WM_CLASS(STRING) = "Godot_Engine", "Godot"`

What would be great is the possibility to set a custom WM_CLASS on export, this would make it easier to create .desktop files for the exported projects and would prevent the exported project to be grouped with the actual engine editor.

How it is now:
![image](https://user-images.githubusercontent.com/30960698/39407103-49abdd36-4bc1-11e8-8cb5-aa91130905e4.png)

Proposition: 
![image](https://user-images.githubusercontent.com/30960698/39407201-86b6109c-4bc2-11e8-8d40-c46da2d7723a.png)
![image](https://user-images.githubusercontent.com/30960698/39407262-8677de8e-4bc3-11e8-8d8b-8a7dbaceb3a6.png)

**Comment by LikeLakers2** [comment]
Just throwing my two cents here, perhaps we should have a more friendly name than WM_CLASS for this. Perhaps "Window Manager Identifier"? Combine that with a good hover-over note and it won't seem so advanced to newbies.

**Comment by LikeLakers2** [comment]
I'm cool with "Window Group". I'm just concerned using the "Class" terminology might be confusing, potentially making some developers (especially new people) think it has to do with how the engine itself works, when it very clearly doesn't affect the engine besides making it separate on the taskbar.

**Comment by guilhermefelipecgs** [comment]
How about use `application/config/name` for the `WM_CLASS` automatically, just replacing spaces with underscore (because I don't know if `WM_CLASS` allow spaces)?

**Comment by ni-code** [comment]
@LikeLakers2 @Two-Tone , Using other name than "WM_CLASS", would be confusing for me. I think stuff like this should be named with their real names instead of something else.

**Comment by LikeLakers2** [comment]
@ni-code I mean, sure, but I personally don't think "WM_CLASS" is really a friendly name to people new at developing for Linux/X11. I'm not saying we can't refer to it as "WM_CLASS" in something like the hover-over tooltip, just that we should consider that new developers (especially those who know next to nothing about Linux development) might misinterpret what "CLASS" means in this context.

**Comment by bojidar-bg** [comment]
What about just writing "Window Manager Class"?

**Comment by neikeq** [comment]
I agree with @ni-code.
I can't think of any name that would be detailed enough to remove the need for user to do a search in order to understand the concept. When it comes to searching, a different name like (for example) "_Window Managet Class_" will add a lot of undesired search results, while "_WM_CLASS_" will give you just what you are looking for.

I'm not against "_Window Managet Class_", but include "_WM_CLASS_" in the name, e.g.: "_Window Managet Class (WM_CLASS)_".

**Comment by akien-mga** [comment]
> How about use application/config/name for the WM_CLASS automatically, just replacing spaces with underscore (because I don't know if WM_CLASS allow spaces)?

Definitely, this should be the default setting if empty, as we can assume 98% of devs will miss this setting and would otherwise have all games grouped together if the default was e.g. "GodotGame".

This would need to be double checked against the X11 spec, but something similar to the way we generate the `user://` path when no custom one is given could do the trick: https://github.com/godotengine/godot/blob/c45f44d85635a1d16a93c00cd8cb17f60dfa6336/drivers/unix/os_unix.cpp#L440

**Comment by cassidyjames** [comment]
I just ran into this when packaging a game up for the @elementary AppCenter. It would be great to be able to associate the game with its own icon instead of the Godot icon!

**Comment by Web-eWorks** [comment]
For information, the WM_CLASS is currently set in https://github.com/godotengine/godot/blob/23b4b7d53a8dabf822cf07074c3b72de43cf649c/platform/x11/context_gl_x11.cpp#L87

The issue is two-part; first, `OS_X11::set_context` needs to be updated to unmap the window before setting the class (and remap it after), and then a project setting can be added to set the class hint.
