### ISSUE TITLE
Remove Light Shaders in favor of Fragment Shaders?

### ISSUE THREAD

**Issue by nodefish** [godotengine/godot#18538]
**Godot version:**
3.x

Apologies if this is kind of a radical suggestion from someone who is a noob to this community. I have nonetheless been using Godot for a while now and realized that Light Shaders are a constant pain point whenever trying to do anything interesting. Please let me know if this suggestion is totally out of line.

- They don't seem to work correctly and I can't find an example of a "default" lighting shader, and I searched various community forums and there does not seem to be a testable, normal Phong light shader code that is confirmed to work in Godot

- Setting DIFFUSE_LIGHT seems to cast no shadows. Shadows only appear when SPECULAR_LIGHT is set

- Attempting to adapt the typical GLSL lighting code into a Godot Lighting Shader results does not seem to work properly and it's hard to identify why.

- Built-ins are split between Fragment and Lighting shaders, so sometimes useful variables are not available (sorry, I don't have specific examples here as I tend to just try to work around things when they don't work).

Suggestion:

- Add array support in shaders

- Provide all scene lights and their associated built-ins as an array that can be accessed from Fragment shaders

- Remove Lighting shaders

**Comment by swarnimarun** [comment]
Well i have been thinking the same thing but I believe it's not so you can always use varying and there are other ways to access things that you might need although I would really like at least a doc update on the topic of Lighting Shaders, cause I fail to understand how they have been integrated into the Godot Shading System.

**Comment by raymoo** [comment]
I'm not sure that Godot's rendering architecture is compatible with giving arrays of lights to the fragment shader. Or at least the performance would be significantly worse.

**Comment by nodefish** [comment]
Isn't it already looping through the lights internally here: https://github.com/godotengine/godot/blob/ec7a8e7d63e31cca5472b662170faab7935482f1/drivers/gles3/shaders/scene.glsl#L2016

Could the light_compute method not simply be exposed in Godot shaders and allow users to override it?

**Comment by raymoo** [comment]
@nodefish I think Godot uses a clustered rendering architecture which gives each fragment only a subset of the scene's lights, but it's true that it should be possible to expose.

**Comment by BastiaanOlij** [comment]
If it loops through every light in your scene, and you have anything approaching the type of lighting you have in a serious game, be ready for framerates in the 1fps range.

Godot, as well as many other engines, will limit the number of lights it needs to evaluate per fragment and just evaluate those which if I am not mistaken is indeed done with a clustered rendering approach in Godot 3.0 as Raymoo suggests.

The way the shaders are implemented in Godot make a lot of sense. If you merge the fragment and lighting shaders into a single shader all you end up doing is recreating exactly what it does today.

The question then is, what are you attempting to do and are you doing it in the right place? There are very few scenarios I can think off where you would want to write your own lighting shader.

The lighting shader is responsible for taking the colour output of the fragment shader and applying the calculations so that it is properly lit by the light it's handling. If 5 lights effect the fragment, the lighting shader is run 5 times and the accumulation of lighting of the 5 lights is added together to get the final colour. The shadow calculation should be handled after your code ends and is determined by the LIGHT_VEC output. If you never change that its default value should result in normal shadow calculations being applied.

**Comment by nodefish** [comment]
Thanks for the detailed writeup. I guess my understanding of Godot's lighting shaders is probably limited.

One thing that I was struggling with was implementing simple banded lighting, without modifying LIGHT_VEC, and only writing to DIFFUSE_LIGHT, yet shadows were eliminated and the results were off and somewhat hard to debug.

I think I'm better off closing this issue and reporting any individual issues I encounter when working with Light shaders.

Thanks
