### ISSUE TITLE
Godot 3.0.3-rc1: a dll missing on windows 7

### ISSUE THREAD

**Issue by Tzoop** [godotengine/godot#18578]
Godot version: Godot_v3.0.3-rc1_mono_win64 and Godot_v3.0.3-rc1-mono_win32
OS: Windows 7 ultimate service pack 1

Issue description:
i can not run the executables because a dll file is missing. when i searched the internet i found out that maybe this dll is not included in my windows, it seems to be a windows 10 thing.

https://stackoverflow.com/questions/37096393/api-ms-win-core-synch-l1-2-1-dll-is-missing-from-your-computer#37097066
https://msdn.microsoft.com/en-us/library/windows/desktop/mt657574(v=vs.85).aspx

Steps to reproduction: doubleclicking the exe-files (both do not work for me)
![godot_api_missing_win7_64](https://user-images.githubusercontent.com/6698415/39558769-abf1dcac-4e91-11e8-9ac7-2e4c6a92a5ca.PNG)

**Comment by akien-mga** [comment]
Do you get the same error with the classical (non-Mono) build? The missing dependency might be pull in for some of the bundled Mono DLLs.

**Comment by KellyThomas** [comment]
On my windows 7 PC this error occurs only when launching Godot_v3.0.3-rc1_mono_win64.
It does not occur when launching Godot_v3.0.3-rc1_win64.

**Comment by hpvb** [comment]
I just purchased a Windows 7 license. I should be able to fix this before rc2. I'll try to supply a test build asap.

**Comment by Tzoop** [comment]
@akien-mga the non-mono builds (win32 and win64) both do not show this message on my pc (win7).

**Comment by hpvb** [comment]
I have reproduced the issue on my Windows 7 VM. I've rebuild Godot using Windows 7 and the resulting binary has the same problem. I'm investigating this further.

**Comment by hpvb** [comment]
so, this took a little while to figure out. It turns out that the official mono distribution's static version of the runtime is linked against the windows 10 SDK. Specifically it uses GetFileVersionInfoSizeW() from Windows 10. This is also implemented in the DLL that is reported missing. 

For 3.0.3 I'll build the Windows binaries against a shared version of mono (so we will ship the .dll). I'll try to have a build environment for Windows 7 that can build Mono itself so that for 3.0.4 we can build static Windows binaries that will work on all supported Windows versions.

Expect 3.0.3 rc2 to work for you.

**Comment by hpvb** [comment]
I think this is fixed
