### ISSUE TITLE
Repeated GPU drivers crash on Windows 10

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#18617]
**Godot version:**
bf561c4

**OS/device including version:**
Windows10/GTX1060

**Issue description:**
I develop my first huge project, and suffer from constantly appearing bug. It occurs in 1 hour probably, and only rebooting PC helps me.
First it show this message

![image](https://user-images.githubusercontent.com/3036176/39650733-0419f82c-4ff2-11e8-9a48-60ba92548f8c.png)

-it dissallow me to continue debug and run my project
-it allows me to close editor and save files, but after trying run editor again it show me the message above again, and console window show me this output

![image](https://user-images.githubusercontent.com/3036176/39650819-5358d0fc-4ff2-11e8-83e7-166fa60f82fb.png)

![image](https://user-images.githubusercontent.com/3036176/39650834-607373fa-4ff2-11e8-8584-78fa0bb86f5e.png)

after some investigation I uncomment _WGL_CONTEXT_DEBUG_BIT_ARB and the message above show me this log

![image](https://user-images.githubusercontent.com/3036176/39650922-a04ac71c-4ff2-11e8-94df-755e3695d898.png)

**Steps to reproduce:**
It may my PC problem, I dont know
PS - I uses ultra-wide monitor with 2560x1080 resolution

**Comment by Chaosus** [comment]
probably related #4029

**Comment by akien-mga** [comment]
The errors you get are because your Windows GPU driver crashed, and therefore no longer provides OpenGL support. A reboot fixes it.

The question is what makes it crash. Several Windows 10 users are experiencing it, given recent history of quite bad Windows 10 updates I wouldn't exclude a driver fault, but it would be good to catch debug information on the actual driver crash to see what Godot call might cause it.

**Comment by Chaosus** [comment]
Yeah, after used an instruction I found here - https://support.microsoft.com/en-ph/help/929833/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system this problem looks not happened again
