### ISSUE TITLE
Add the ability to scale UVs from the center

### ISSUE THREAD

**Issue by anasofgo** [godotengine/godot#18611]
Currently UVs could be scaled in godot, but the scale origin is set to the top left corner of the UV... It would be great if we are able to scale UVs from the center.
I know a workaround is to scale then offset the UVs.. but It is inconvenient, especially when you want to animate the UVs.

**Comment by Zylann** [comment]
Shouldn't it be a 4x4 matrix to transform UVs? (so UVs can be scaled, translated and rotated with any center)

**Comment by anasofgo** [comment]
![casdddcapture](https://user-images.githubusercontent.com/11005460/39640495-cb791750-4fd3-11e8-9fac-03d6b95d0dfa.PNG)
Yes, I am talking about the GUI scale property for SpatialMaterial

**Comment by anasofgo** [comment]
Here is a simple code I wrote that can be attached to any node (that inherits spatial) and it will add the ability to scale the UVs from the center (for any Spatial Material loaded) directly in the editor:

`tool
extends Spatial
export var scalefromcenter = Vector3(1,1,1) setget changed
export(Material) var res

func changed(newVar):
	scalefromcenter = newVar
	if typeof(res)!= TYPE_NIL :
		res.uv1_scale = newVar
		res.uv1_offset = -(newVar-Vector3(1,1,1))/2`

![as](https://user-images.githubusercontent.com/11005460/39666385-96b8b0f6-50ab-11e8-8795-946b706db7a9.png)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
