### ISSUE TITLE
When moving a file with the editor, if there is a file with the same name it replaces it without any notice

### ISSUE THREAD

**Issue by salvob41** [godotengine/godot#18622]
**Godot version:**
Godot 3.0.2.stable.official

**OS/device including version:**
MACOSX

**Issue description:**
if I move a file with the same name of another file in a target directory, this one will be replaced without any notice.
![image](https://user-images.githubusercontent.com/6097015/39658127-19aced34-5010-11e8-91d6-1779dcee38b5.png)

**Steps to reproduce:**
Moving a file with the same name of a target directory

**Minimal reproduction project:**

**Comment by swarnimarun** [comment]
Confirmed on all OS, Ubuntu and Manjaro(Linux) and also on Windows 10.

**Comment by swarnimarun** [comment]
Any ideas how it should be implemented, probably it should only ask if you want to overwrite or not, or should it also ask for renaming on being denied overwrite.? So some other way.

**Comment by helle253** [comment]
We should probably front-load the options in the first pop-up, rather than having the user rename when selecting the 'don't overwrite' option. It would save the user time clicking through dialog boxes and imo would be slightly less annoying. I would imagine the options would probably look like the following.

Notify the user that they are trying to overwrite a file. Give them 3 options:
1. Overwrite the file
2. Rename the file manually the user is trying to save
3. Don't overwrite.

Would it be neccesary to cover the case where the user is moving multiple (potentially many) files? If so, the options would probably look like this:
1. Overwrite this file
2. Overwrite this file and all following files
3. Rename the file the user is trying to save
4. Don't overwrite this file
5. Don't overwrite this file and all following files.

**Comment by akien-mga** [comment]
Fixed by #19245.
