### ISSUE TITLE
Add a way to filter backfaces on raycasts

### ISSUE THREAD

**Issue by malucard** [godotengine/godot#18649]
It's really useful for 3D level editors and such. Maybe an option in the Project Settings called "Rays Hit Backfaces", with a function to go with it, or a "Cull Mode" option in Shapes (with a setting to change the default).

**Comment by AndreaCatania** [comment]
I don't know what you mean exactly, because only the mesh shape could have something similar... Can you please explain why do you need something similar?

**Comment by jv110** [comment]
This is possible in Unity with `Physics.queriesHitBackfaces`.
I need it because I'm making a level editor for my 3D game. The camera is usually outside the level, and walls disappear (because they're now backfaces). You can select walls by clicking on them, and push/pull with buttons. It works perfectly, but when the camera is outside the level (which is usually the case), walls can't be selected, because it hits the other wall. If I could ignore backface hits, it would be possible to only hit the visible wall.

**Comment by AndreaCatania** [comment]
This is interesting, I will work on that

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
