### ISSUE TITLE
Please remove Particle Material parameter caps

### ISSUE THREAD

**Issue by qrilin** [godotengine/godot#18643]
**Godot version:**
v3.0.2 stable official

**Issue description:**
ParticlesMaterial parameters (e.g. damping, linear accel etc.) have a seemingly arbitrary minimum/maximum cap of 100.

It's not that uncommon to use high velocity particles, and these caps severely limit the capabilities of the particle systems for these use cases without an apparent reason (except maybe that the values could be set by slider in the inspector)

Please consider removing these caps.

**Comment by Ranoller** [comment]
This caps are for 3D, but shares code with 2D. I ask in another issue to separate both codes to no affect 3D with the bad binded parameters in 2D. In the moment that somebody with sufficent knowledge of the engine split both codes... I fix bad binded parameters.

**Comment by clayjohn** [comment]
This is an issue throughout the code base right now. Many values are arbitrarily capped at 100 by the editor. This is usually so that the slider will not give users values way outside the range they expect, however it makes no sense for most use cases, oftentimes the slider is not even used and yet the value is still capped by the editor. I raised the same issue earlier in regards to the size of meshes being capped at 100 in issue #18555 . 

Right now the only solution is to set your values from code. It is easy enough to attach a script that will set the values manually. But this solution feels very hacky. 

What is really needed is a way of restricting the slider range without restricting the range of values that can be entered into the input field by the user.

**Comment by akien-mga** [comment]
This can be fixed in a similar way as #19459.

**Comment by clayjohn** [comment]
Yes! I was actually planning on doing that today. Look forward to a PR in the next couple hours.
