### ISSUE TITLE
Add a way to change an animation FPS in a easy way.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#18652]
Hi, There's something that I would love to have.

An easier way to have change the FPS of animation in the animation tree after I've made the animation and not just having to set a new FPS and then have to move every keyframe to their correct newer timing.

That will allow to test diferent animation FPS velocities without much problem.

Also, allow to set a single keyframe to be slower or faster than the other keyframes, like I want this keyframe to last 1.5 frames of the other keyframes (to give a more solid feeling in a melee attack, by example).

**Comment by ca3games** [comment]
Let's say you've made an animation using a certain framerate or time delay, maybe on a single animation or several animations and you now want to make it faster or slower.

So far I haven't seen a way to change all frames of an animation at once, like moving them to the nearest place the newer framerate will put their frames.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
