### ISSUE TITLE
Add a way for the animator tree to request variable values from nodes

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#18651]
Hi, I think it would be neat if your could request a variable number from a node script inside the animator tree.

By example, It would be neat to get from a node script the velocity based on gameplay loop of player or enemy status and update a keyframe value based on it.

Maybe that way you could have diferent power ups with diferent rigidbody velocity keyframes using a single animation.

Maybe some conditional logic and the same animation could be dyed red or another color based on a powerup variable.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
