### ISSUE TITLE
Video scaler in the Project Settings Quality options

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#18661]
A video scaler can be very useful, for example we could have an internal resolution and a display resolution. The internal resolution could be high then scaled down to fit the screen to remove the aliasing. A very low internal resolution that is upscaled could allow to create pixelized games, the upscaling should have an option to keep the pixels sharp. This would allow to create a pixel art effect like this: https://youtu.be/1ShSYfo08Zs?t=7m

![pixelate](https://user-images.githubusercontent.com/30020215/39676851-8e26c60a-5171-11e8-9e4c-7ce4cf9459ef.gif)

This would be very useful for an orthographic 2.5D games like an old school RTS game with 3D assets.

See also reducing the number of colors: https://github.com/godotengine/godot/issues/18662

**Comment by Calinou** [comment]
This is already partially supported. You can set the project's scaling mode to `viewport` and the aspect scaling mode to `keep`, which will result in the viewport scaling to higher window resolutions using nearest-neighbor filtering (linear filtering isn't supported yet).

**Comment by bojidar-bg** [comment]
This should be doable by manually managing a viewport.
To do it, you would need a scene structure like this:

- TextureRect( texture = ViewportTexture )
    - Viewport( size = Upscaled size )
        - Rest of the game

In project settings, configure scaling mode to "viewport", and aspect mode to "keep". Alternatively, you might setup a shader on the TextureRect similar to the pixelize shader from the shaders demo.

**Comment by Calinou** [comment]
Since we already have `test_width` and `test_height` to set a different window size when running from the editor (independently from its default `width` and `height`), I think we can close this.

There's also the stretch shrink setting which you can set to an integer value in the Project Settings. For instance, if you set it to 2, each pixel will be drawn over a 2×2 surface.

Please [open a proposal](https://github.com/godotengine/godot-proposals) if you have further enhancement/usability requests.
