### ISSUE TITLE
OptionButton's popup should offset when showing so the selection is visible

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18689]
Godot 3.0.2

Hello, this is a request for a minor improvement to OptionButton's behavior.  For large lists where the popup is larger than the viewport, the user can use the mouse wheel to scroll through the options, as expected.  However, the user must scroll to find the option they previously selected from the initial offset each time they spawn the popup.  It would be helpful if the popup "remembered" the previous scroll offset, or in lieu of that, OptionButtons could automatically offset popups larger than their parent viewport to make the current selection visible without scrolling.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
