### ISSUE TITLE
Create a way to move all keyframes more easily (E.g Adding a keyframe at the numbers of the TimeLine)

### ISSUE THREAD

**Issue by DrZanuff** [godotengine/godot#18690]
Godot 3.0.2 Stable

Windows 10 Home 64 Bits

**Issue description:**
I would like to suggest to insert a keyframe in the TimeLine to move all keyframes at same row. Currently you have to drag to select all keyframes, and if you have a lot of keyframes this become troublesome:
![badway](https://user-images.githubusercontent.com/23051495/39721803-06430950-5217-11e8-8c2b-da28f6721251.gif)

In DragonBones, a Skeleton Animation 2D tool, you can drag a keyframe at the timeline to move all keyframes of the same row:

![goodway](https://user-images.githubusercontent.com/23051495/39722017-b4257ce2-5217-11e8-9422-6a14f64cfb3d.gif)

I worked in a long animation on Godot, and this feature would've helped a lot.

**Comment by Zylann** [comment]
We could also have a "ripple editing" mode, it's a nice idea I've seen and used in Reaper timelines: basically when this is enabled, moving an item will also move all items coming at the same time or after it. It makes it easy to add or remove some duration in the animation without having to manually select everything coming after.

**Comment by DrZanuff** [comment]
I liked the idea of the ripple editing. This would help too.

**Comment by DrZanuff** [comment]
I liked the idea of the ripple editing. This would help too.

**Comment by avencherus** [comment]
Yes, the AnimationPlayer could use some more bells and whistles for manipulating and selecting keyframes.  It gets cumbersome for animators once the tracks reach a certain number.

**Comment by takhimi** [comment]
@DrZanuff , I agreed with you. Is there a way to do this right now(Godot 3.1.1  or in next release ? In Spriter it works the same way as Dragonbones or the same way as DrZanuff demoed. Ability to manipulate or move, select or delete all keyframes from timeline would be great instead of needing to select every keyframe per track. Please add this feature...

**Comment by holzmb** [comment]
In 3.2 you can't even move the scrollbar with the selection, like in the first gif.
You can only select keyframes that are on the screen, making the animation extremely cumbersome.
Anyone know if ripple editing would be possible to make with a plugin?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
