### ISSUE TITLE
Using a TileMap without a TileSet

### ISSUE THREAD

**Issue by matty** [godotengine/godot#18694]
**Godot version:**
3.0.2

**OS/device including version:**
Windows 10

**Issue description:**
Currently I create one single TileSet for each Texture that I set cells to. I think it should be possible to set a cell in a TileMap with just providing a Texture and not a TileSet. I have a case where my scenes are dynamically generated in code so this makes sense to me and it may for others.

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
