### ISSUE TITLE
Button->ShortCut->InputEventKey in editor difficult to use

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#18695]
**Godot version:**
3.x (master)

**Issue description:**
Adding an InputEventKey to a ShortCut to a Button in the editor does not provide an easy way to set the key that will be used as the shortcut. 

The available fields where the character is set appear to be **scancode** or **unicode** but they are integer fields with no clear mapping to keyboard characters.

It would be useful if the functionality was similar to that of Project->Project Settings->Input Map where you are given a "press a key" dialog that populates the shortcut.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
