### ISSUE TITLE
ON/Off option is reverse in activating ragdoll

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#18704]
**Godot version:**

9b1fdad

**OS/device including version:**

linux mint

**Issue description:**

I create the physical skeleton by the button and I use physical_bones_simulation(true) to activate it. The result is fine if I don't check simulate physics option of the physical bones in the editor. If I check the bone while using physical_bones_simulation(true), it stops the simulation of that bone. It is off instead of on.

Another problem, I don't know whether it is a bug or not. is it true that I must call physical_bones_simulation(true) to activate the simulation and check/uncheck desire bone with simulation? If I don't call physical_bones_simulation(true) and check the simulate physics of the physical bones option in the editor, nothing happens.

**Steps to reproduce:**
create the physical skeleton
call  physical_bones_simulation(true)
check the simulate physics option of the physical bones in the editor

**Minimal reproduction project:**

**Comment by AndreaCatania** [comment]
Thanks you for your comment, I've improved the API in order to make easy the activation and deactivation of full body or partial.

Also I've removed the possibility to check simulation on physical bone on the editor in order to avoid misunderstanding.

Thanks you for your contribution!

Check this #18764
