### ISSUE TITLE
Allow empty classes with pass

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot#18733]
I'm trying to make Jump Profiles for my character and I have a `JumpProfile class`

Like this

```
class JumpProfile:
	var CanDive = false
	var CanKick = false
	var CanControlHeight = false
	var JumpHeight
	var InitialForwardVelocity
	var Gravity = 35.0
	var MaximumGravity = 30.0
	var Animation

class jumpStandard extends JumpProfile:
	pass
```

But I don't want to declare the values upfront.

And I want to put `pass` like in Python.

But the problem is pass is not allowed in classes in Godot.

Since Godot is inspired by python, it'd make sense to implement the pythonic `pass` even for classes

**Comment by vnen** [comment]
The code explicitly forbids it (removed with a comment). It's there since forever and I wonder if there's a reason for it.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
