### ISSUE TITLE
int(string) should raise an error on invalid input

### ISSUE THREAD

**Issue by Technius** [godotengine/godot#18735]
**Godot version:**
v3.0.2.stable.official

**OS/device including version:**
Debian testing, but probably affects all versions

**Issue description:**

I'm making a GUI for my game, and I have a `LineEdit` that acts as input for a number (I only became aware of `SpinBox` some point after I noticed the issue). I want to be able to warn the player when he or she types in invalid input (e.g. `asdfasdf`), but I noticed from the docs that

> int int ( String from )
>
> Cast a String value to an integer value, this method is an integer parser from a string, so calling this method with an invalid integer string will return 0, a valid string will be something like '1.7'. This method will ignore all non-number characters, so calling int('1e3') will return 13.

`float` also has the same behavior.

I think the default behavior of `int` should be to raise an error on invalid input, for the following reasons:

* In comparison to other programming languages, this is unexpected behavior. I would expect a runtime error or at least the function returning null. For example, Java and Python will each throw an exception. JavaScript will return `NaN` instead of continuing to parse (but the program will continue to run, which makes debugging the error hard).
* It's not possible to tell the difference between `0` and invalid input; this can cause confusing programmer errors. It's like how when `HashMap.get(key)` in Java returns `null`, it's impossible to tell whether the key is actually contained in the map or if the key was mapped to `null` without performing more operations.
* Someone might make a typo and enter what would otherwise be valid input, and the programmer may forget to use `String.is_valid_integer` to check first. For example, someone might mean to type "567" but instead enter "tyu" (one row below on a QWERTY keyboard), which causes `int` to return `0`. This may be especially confusing if the programmer is a beginner. If `int` raises an error instead, then the programmer would become immediately aware of this problem.
* I don't think the current behavior of `int` is taken advantage of enough that a change will break someone's game. If it does, then the current behavior can be emulated by filtering out non-numeric characters and non-sign characters before parsing the string. In any case, it's a good practice to check the validity of inputs are before using them.

**Steps to reproduce:**

Call `int` with any string that does not consist entirely of a number.
Here are a few inputs that I've tried:

| string | what I expected | calling `int` |
|---------|-----------------------|----------------|
| -5 | -5 | -5 |
| --1 | error | 1 |
| aaa1aaaa2aaaa3bbbbb4 | error | 1234 |
| deadmau5 | error | 5 |
| 0xFEEDABBABEEF5ABC | error | 5 |
| 5̦̬͙̤̳͉̱͙̩͖̗̗̂̑̐̏̍ͯ͋̌͘͢͡͝ | error | 5 |
| 4͉̖̫͇̞̟̠̫̱̹̀̐͗͒̋̊̂̀̑̏̈̐͂͐̕͟͞2̸͉̩͙̥̲̭͕̻̭͙̭̈͂̿ͫ͆ͥ̋ͣͩ͘͘ | error | 42 |
| 4̐̀̎ͮ͌̅ͭͧͬ̊ͦͣ͗ͮ̓͗͟͝҉͈̝̳̮͇͙̹̣̟̪͖͍͔̯̱️̡͈̳̙͈͔̯̮̈́̾͋̉̅̑̈́͊ͤ̆̾̅ͯ͢⃣̡̢̣̙͙̤̹̜̥͈̹̫͈̲̞ͣ͆ͭ͛ͦͯ̂̅ͣ̓͑̽̐̽̓̒͛͊͂͝2̴̨̨̨͇̭̗̻͉̠͕͍͉͈̗̻̯̗̞ͥ͑̾ͩ̅̋̉̒͑̓ͭ͢ͅ️̵̨̨̪̝͇̬̲̖͈̮͎̲̙̫͗ͭ̀̈͛̽̄́̃̉͑̈́ͧ̓̀̊͘ͅ⃣̴̸̪͍͇̩̲̝̼ͩ̓͒̒̀͂̋̉̽ͭ̉͟͞ | error | 42 |

**Minimal reproduction project:**

N/A

**Comment by Zylann** [comment]
I used to exploit the fact that `String.to_int` was returning the *next* integer found in a string, so for example `level42` would return `42` and I used that as a indexes in the game. However, while this may seem useful, I didn't expect the cast operator to act this way.

**Comment by eon-s** [comment]
Shouldn't it be NaN instead of error?

**Comment by akien-mga** [comment]
I think an error would be better than NaN.
Here's how Python handles it:
```
>>> int("2")
2
>>> int("Hello2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'Hello2'
>>> int("10e2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '10e2'
```

**Comment by jv110** [comment]
NaN isn't an integer. There's no invalid integer value, either, so if it's going to fail, it must be an error.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by eon-s** [comment]
This issue can be closed then?
