### ISSUE TITLE
Godot 3.0.2 Editor crash on exit

### ISSUE THREAD

**Issue by Osimedias** [godotengine/godot#18746]
**Godot version:**
Godot 3.0.2

**OS/device including version:**
Windows 8.1

**Issue description:**
The editor and the compile game crash on exit

**Steps to reproduce:**
open a project
then try to close the project or the editor
and the editor crash
**Minimal reproduction project:**

**Comment by bojidar-bg** [comment]
Can you try to get a backtrace of the crash? (there is one printed in the console by debug builds of Godot, it might suffice if it lists function names)

**Comment by Osimedias** [comment]
if you mean this
![error](https://user-images.githubusercontent.com/7454459/39899902-0a75917c-5484-11e8-81f4-2db39ffda88d.png)

**Comment by Zireael07** [comment]
I get that occasionally too, Godot 3.0.2

**Comment by neikeq** [comment]
Does it crash or simply prints those errors?

**Comment by Zireael07** [comment]
No Windows notification of a crash, at least for me (Win 7). Just those errors.

**Comment by bojidar-bg** [comment]
> and only happen whit my project

Seems you have some resources lingering after the game quits, probably caused by some reference cycle. A reference cycle is created when you have multiple Reference objects keeping a reference between themselves.

You should probably try to use weakrefs to break such reference cycles, since they do not contribute to the reference count.

**Comment by neikeq** [comment]
Regarding the instance leaks errors at the end, run Godot in verbose mode (`godot.exe -v --path path\to\project -e`) to get more details.

**Comment by Osimedias** [comment]
ok

**Comment by Osimedias** [comment]
![verbose](https://user-images.githubusercontent.com/7454459/39953768-3bdc7650-5578-11e8-8d36-7f73dbe91b1b.png)

**Comment by akien-mga** [comment]
You should quote or escape the path given to `--path`, otherwise it interprets it as two arguments and tries to load `Rodriguez\Documents\...` as a resource.

Given your working directory, just `--path "Documents\GitHub\Generic-RTS"` should work. Or `cd` to that folder and run `..\..\..\Godot3.0.2 -v -e`.

**Comment by Osimedias** [comment]
I find the problem
I use get_tree().change_scene_to(preload(scene)) and that make the errors, i feel stupid
