### ISSUE TITLE
No key release event if window loses focus (Input.is_action_pressed)

### ISSUE THREAD

**Issue by aomimezura** [godotengine/godot#18785]
**Godot version:**

3.0.2

**OS/device including version:**

Ubuntu Linux

**Issue description:**

Input.is_action_pressed continues to return true if window loses focus before key is released. It continues to trigger even when the game regains focus.

**Steps to reproduce:**
check Input.is_action_pressed() in a loop (like _physics_process). Start pressing the key, then click another window to cause the game to lose focus. Input.is_action_pressed() continues to return true, even when returning to the game window. You must press the key again to fix it.

**Minimal reproduction project:**

[input_action_bug_test.zip](https://github.com/godotengine/godot/files/1994082/input_action_bug_test.zip)

**Comment by groud** [comment]
I think that's an expected behavior.

**Comment by puppetmaster-** [comment]
Try this but it only works in Godot 3.

```
func _notification(what):
	if what == MainLoop.NOTIFICATION_WM_FOCUS_OUT:
		Input.action_release(myAction)
```

I don't know why this solution doesn't work in Godot 2.1.5 but maybe a developer can look at it.

**Comment by romlok** [comment]
IMO this should *not* be considered expected behaviour for a function called `is_action_pressed` (rather than `was_action_pressed_last_time_we_had_focus`! ☺).

Would there be any harm to making Godot, by default, implicitly release all inputs when the window loses focus, in a manner similar to that which puppetmaster suggests? I imagine that this is by far the most common desired/expected behaviour for applications.
But if there are edge cases where the behaviour is desirable (I can't think of any, but I'd be interested to know), there could be a project config setting to toggle the behaviour.

**Comment by puppetmaster-** [comment]
@romlok I have created a game for the Ludumdare game jam with godot 2 and I got this problem also in the webrelease (itch.io) and I could not implement a fix to solve the problem because **action_release()** don't work in godot 2. It's a pity but no end of the world.

I think your idea is good. But I lack the technical understanding to judge it.

**Comment by lekoder** [comment]
Usable work-around is:
```
func _notification(what):
	if what == MainLoop.NOTIFICATION_WM_FOCUS_OUT:
		for setting in ProjectSettings.get_property_list():
			if setting.name.substr(0,6) == "input/":
				Input.action_release(setting.name.substr(6, setting.name.length()-6))
```
And is a convoluted, ugly hack. I can't really think of any scenario where described behaviour is desired, hogging controls already came to me as a bug report from game tester. Please reconsider classifying this as bug, handling release of action inside engine will be much cleaner solution.
