### ISSUE TITLE
SceneTreeDock - Selecting Parent w/ Child Causes Right Click Menu to Skip Single Selection Checks

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [godotengine/godot#18787]
**Godot version:**
Master build

**OS/device including version:**
Windows 10

**Issue description:**
Normally, selecting multiple nodes will prevent the user from using certain tools in the right click menu (such as change type). However, by selecting multiple nodes that belong to different "layers" of the hierarchy, you can bypass this single-node check.  It likely has to do with the way EditorSelection::get_selected_node_list() returns the selected elements. It's not a critical error, since tools tend to only work on one node, but creates some room for undefined behaviour. 

**Steps to reproduce:**
Select a parent and child, and right click. You should notice that some tools are not properly filtered from the list.

**Comment by KoBeWi** [comment]
This is actually expected, sort of. There are some functions that still work with hierarchy selected, even if they don't work on multiple nodes. E.g. "Make Scene Root" will work on hierarchy and will just make the topmost node the root.

This happens, because the method that gets selected nodes list will only return nodes with common parent. There are some options like "Rename" that are a bit buggy in this case, so they should probably be handled separately, with full selection.
