### ISSUE TITLE
Sloped one-way platforms do not work consistently

### ISSUE THREAD

**Issue by nmearl** [godotengine/godot#18813]
**Godot version:**

v3.0.2.stable

**OS/device including version:**

Ubuntu 18.04 LTS

**Issue description:**

Collision objects with one-way enabled and placed at an angle do not work consistently.

https://www.dropbox.com/s/cndawsl8pcrj2qv/Screencast%20from%202018-05-08%2017.34.42.webm?dl=0

**Steps to reproduce:**
Create a platform with a `StaticBody2D`, a `CollisionShape2D` with a `RectangleShape2D` and one-way enabled. Rotate. Create a `KinematicBody2D` node with the default movement controls. Note that it will fall through at various points.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@nmearl Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
