### ISSUE TITLE
Fullscreen font rendering bug (space characters)

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#18835]
**Godot version:**
Today's build from https://hugo.pro/projects/godot-builds/

**OS/device including version:**
Windows 10.

**Issue description:**
I haven't used Godot for a while, but coming back to latest nightly builds, something seems to be wrong with font rendering.

Everything looks just as it should in windowed mode, but in fullscreen mode, space-characters are unproportionally large, and even vary in width.

I've tested this with a few different dynamic fonts.

**Comment by isaacremnant** [comment]
I want to confirm there are issues when going fullscreen with RichTextLabel. I'm attaching a [demo](https://github.com/godotengine/godot/files/1999047/WeirdFonts.zip)
, just insert a font of yours in RichTextLabel.tscn since I'm not sure if I'm allowed to post fonts.

Basically, press space three times. The first time, text is added to the RichTextLabel. On the second, the game goes fullscreen and if a custom font is used, the text previously added will be REMOVED, leaving the default bbcode_text value. The third space press just prints more text. This doesn't seem to happen without specifying a custom font.
