### ISSUE TITLE
Have a way to render the scene in another viewport with global shader overrides

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18848]
Godot 3.x

I've been thinking about a feature that could help implement interesting rendering techniques:
Have the ability to create a viewport on which we can render the scene, but from a different viewpoint, different environment and different shaders for all the objects, *without* having to necessarily change (or even touch) all nodes of that scene, which makes it easier to setup.

The use cases for this are:
- Minimap with lighter materials (less overhead due to being a separate render with lighter shaders)
- Realtime top-down mapping, or depth map for use in other materials (ex: a grass painting system based on the height of the depth map)
- Debug drawing (like the unshaded, overdraw and wireframe modes we know, but could also be UV, normal, or other displays)

I thought https://github.com/godotengine/godot/pull/18795 would provide this feature, but this implementation is intrusive and a bit different from what I'm seeking for.

**Comment by sdfgeoff** [comment]
Quick note: Assuming it's an override of a single material for all of the objects in the viewport, then you will not be able to create a minimap unless every object can look the same (or you use vertex color to differentiate them) because of the issue @panzergame mentioned of all materials being the same.

The mentioned PR is not ideal because it does take setup, but there was no solution we could think of that would allow different per-object shaders and not have significant setup. Because most of these things like minimaps will only work at run-time, then automated overriding can be done by adding a script that links to SceneTree.node_added and assigns the shader to any MeshInstances that are created.

**Comment by Zylann** [comment]
Depends how you do the minimap then, but my request really is to override all with a single shader. I was just giving examples (my own use case being top-down mapping for use in shaders).

**Comment by nunodonato** [comment]
related: #9550

**Comment by nunodonato** [comment]
would it make sense to have a "material override" in the world environment? considering that you can choose different world environments per viewport, it could work out

**Comment by nunodonato** [comment]
I did a test today, added a material override per WorldEnvironment, which enables different cameras to render in a different way

![override2](https://user-images.githubusercontent.com/1642015/42956398-c595a21a-8b77-11e8-8500-e346243a345c.png)

**Comment by fire** [comment]
I wish to try this. Did you post a sample anywhere?

**Comment by fire** [comment]
The goal is to implement this as a post process. 

![Nintendo Skew](https://img.haikudeck.com/mg/A2674CB9-CAE9-4701-980A-0B1FA380A35A.jpg)

**Comment by SIsilicon** [comment]
I wonder what's the status on this. Is sounds very useful.

**Comment by SIsilicon** [comment]
Are you sure that solves this issue? That pull request is for global _shader uniforms_, but this about rendering different environments with _different materials_.

**Comment by clayjohn** [comment]
Ah, your right.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
