### ISSUE TITLE
Editor Z Far too small

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18858]
Godot 3.0.2
Win 7 GeForce 960

Hi there,

Godot editor 3D view Z Far setup is limited to 16million units, this is not enough and does not allow to view a full scene when objects are bigger.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/ZmaxValueBug.jpg?raw=true

**Comment by Calinou** [comment]
You should scale down your imported models as they are way too large. In Godot, units should generally be considered as meters, so setting the Z Far plane distance at 16 million units means you can see 16,000 kilometers away. Either way, I believe Z-buffer precision errors will become apparent far before a distance of 16 million units, so it's probably not a wise idea.

Also, unless I'm mistaken, Godot does not handle "huge worlds" for you: floating-point precision will become an issue when the camera is placed far away from the origin – a workaround is to move the world around the camera instead of doing the opposite, but this is not trivial.

**Comment by DevMagicLord** [comment]
I found i didn't zoomed out too much like 16 million units was small in Godot, perhaps i'm wrong.

I agree you need to move the world around to avoid those issues and it should be fine for most games.
