### ISSUE TITLE
Triplanar bug

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18857]
Godot 3.0.2
Win 7 Geforce 960

Hi there,

When i check or uncheck World Triplanar on material flag it does nothing and texture stay stretched.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/triplanarbug.jpg?raw=true

You can download the .obj model and test it assigning a material and checking world triplanar.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/islandV2.zip

**Comment by Calinou** [comment]
This is likely to be a material configuration issue, see [the reply I wrote on the Godot Developers forum](https://godotdevelopers.org/forum/discussion/comment/23303/#Comment_23303).

I'm closing this issue since it does not describe a bug in the engine; please continue the discussion on the forum thread.
