### ISSUE TITLE
3D Particles sometimes show first frame at end of lifetime

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#18850]
**Godot version:**
Recently compiled build based on master

**OS/device including version:**
Windows 7, GTX 760

**Issue description:**
Some 3D particles that use the animation option show the first frame of the sprite at the end of a particles life, even if the loop option isn't enabled. This seems like a rounding error, as if you set the particle animation speed to 0.95 the problem usually goes away.

![Image](https://user-images.githubusercontent.com/10464013/39949903-cc562d14-5575-11e8-9b3d-d378437cc5dc.gif)

**Steps to reproduce:**

**Minimal reproduction project:**
Download and open the attached project, there's only one scene. No need to run the scene either, the effect should be apparent immediately from within the editor

[particle_bug.zip](https://github.com/godotengine/godot/files/1998940/particle_bug.zip)

**Comment by JFonS** [comment]
Found the issue, there's kind of a duplicate option in particle systems. You can set the animation to loop on the process material and also on the spatial material for the particles. @sketchyfun in your case disabling looping in the spatial material fixes the issue.

@reduz  I think we should remove the loop option from either the process material or the spatial material since having them duplicated only creates trouble. I'm inclined to keep it on the spatial material and remove it in the process material, what do you think?

**Comment by sketchyfun** [comment]
Aha! Good find, that's a sneaky one :)

**Comment by JFonS** [comment]
Should be fixed by #22622 so closing.
