### ISSUE TITLE
UV triplanar blending

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#18863]
Godot 3.0.2
Ge Force 960

Hi there,

Triplanar mapping just doesn't work .
With Flag world triplanar "on" , triplanat "on" for UV , whatever i choose values like 10 ; 1 ; 0.5 ;  0.01
It draws buggy lines and texture does no more look like the original and loose it's color

It definitively doesn't work.

https://github.com/DevMagicLord/Godot3/blob/master/bugs/triplanarbug3.jpg?raw=true

**Comment by DevMagicLord** [comment]
It seems to work with Z value same as X and Y.
But we can see blending , is this a bug ? 
https://godotdevelopers.org/forum/uploads/editor/c0/q4134jloifhj.png

**Comment by DevMagicLord** [comment]
It looks like it's how many triplanar shader works.
Getting a better blending would perhaps cost more.

**Comment by DevMagicLord** [comment]
Should we expect a triplanar shader able to do better blending ?

**Comment by bojidar-bg** [comment]
@DevMagicLord From what I can gather from various articles, triplannar mapping is expected to have some problems with angled slopes in general.

For your case, you might consider making a custom shader to implement some ideas from, e.g. https://www.gamasutra.com/blogs/AndreyMishkinis/20130716/196339/Advanced_Terrain_Texture_Splatting.php or other resources on the web.

If there is a generic-enough way to make this, we might consider using it, otherwise, a shader might be provided on the assetlibrary for such uses.

**Comment by DevMagicLord** [comment]
This means Godot triplanar is good enough, for specific needs make your own shader.
