### ISSUE TITLE
get_creation_time() of a file from gdscript

### ISSUE THREAD

**Issue by Achi92** [godotengine/godot#18875]
**OS/device including version:** 
Windows

**Issue description:**
Now is impossible to obtain birth date of a file

**Feature request:**
Need get a creation time of a file

**Minimal reproduction project:**
Want gd-function:

 /**
get_creation_time(p_file)
@filename: String  Full path to file
@return: int  File creation time. In seconds since 01.01.1970. 
*/
uInt64_t File.get_creation_time(String p_file)

Usage:

var ctime= File.get_creation_time(p_file)

**More info:**
I found in godot/drivers/windows/file_access_windows.cpp on line 295 _get_modified_time() it should be possible duplicate that changing this 'return st.st_mtime ' with this 'return st.st_ctime'

I know that is not so easy but what is written above should be enough to explain what I mean

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
