### ISSUE TITLE
Mesh looks too glossy when using a roughness texture

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#18880]
**Godot version:**
`master` / 224d5371ff65a

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
When I created a roughness texture using Substance Painter and used it in Godot, it makes the model look much too glossy compared to how it looked originally.

I don't expect it to look exactly the same between Substance and Godot, however, it feels like the texture must almost look all white to make it not to look too glossy.

I've attached a few screenshots for comparison:
![substance](https://user-images.githubusercontent.com/2367032/40037066-25188c44-5846-11e8-934b-3e7585e65314.png)
This is how my character looks like in Substance Painter. I haven't started to paint rough/smooth areas, so the texture looks quite uniform like this:
![roughness](https://user-images.githubusercontent.com/2367032/40037117-733543b8-5846-11e8-9231-7362ac9b7890.png)
However, when I apply it to a material in Godot, it looks glossy even when the roughness is set to the maximum value:
![glossiness](https://user-images.githubusercontent.com/2367032/40037160-a59c1f66-5846-11e8-892a-36a4a0307f08.png)

I also noticed that the shadow almost highlights glossy area as shown below. I'm not too sure if it's the same problem, so please let me know if I should separate it as another issue.

![glossiness2](https://user-images.githubusercontent.com/2367032/40037235-31854b7e-5847-11e8-8260-bc3ff47e965c.png)

**Comment by jaran** [comment]
karroffel pointed out in discord that godot squares the roughness in it's final calculation.  When we convert the material to a shader and then modify the roughness to equal the sqrt of the old value we get results much closer to substance painter.

Old roughness calculation in shader
`ROUGHNESS = roughness_tex * roughness;`
Modified to
`ROUGHNESS = sqrt(roughness_tex * roughness);`


![preview_sphere_substance](https://user-images.githubusercontent.com/55374/40430341-ccf5fc3a-5e59-11e8-91ad-1dabeafc78f3.PNG)
screenshot from substance painter using default preview sphere project.



![preview_sphere_substance_2](https://user-images.githubusercontent.com/55374/40430342-cd104b76-5e59-11e8-9dcc-4caaeb678ac8.PNG)
screenshot in godot without the sqrt fix.  Very reflective


![preview_sphere_sqrt](https://user-images.githubusercontent.com/55374/40430340-cc7db446-5e59-11e8-8096-dc736d6efe18.PNG)
screenshot with the sqrt fix now looks very close to substance painter

**Comment by tagcup** [comment]
Thanks; if you're still seeing a difference at `roughness = 1`, that sqrt shouldn't be there.

Can you try setting `alpha = (0.5 + roughness/2)^2` in the shader code (drivers/gles3/scene.glsl) and compare? That should at least tell us whether Substance is stuck with the 2012 Burley model or not.

**Comment by jaran** [comment]
@tagcup When I change the scene.glsl to

`float alpha = pow((0.5 + roughness/2), 2);`

and then undo the sqrt in the material shader and change it back to

`ROUGHNESS = roughness_tex * roughness;`

It goes back to being too reflective like the first example without the sqrt fix

![preview_sphere_godot3_core_shader_change](https://user-images.githubusercontent.com/55374/40454967-b4a37ee6-5e9f-11e8-97b2-604958d19377.PNG)
without sqrt.  to reflective.

![preview_sphere_godot3_core_shader_change_with_sqrt](https://user-images.githubusercontent.com/55374/40454984-c32f762c-5e9f-11e8-8ed1-5814aa2c1ba5.PNG)
with sqrt back to looking like substance painter

**Comment by tagcup** [comment]
I'm not sure what the exact problem is (there might be a missing scaling factor somewhere) but adding an ad-hoc sqrt isn't the solution (yes, roughness gets squared in the shader code, but that's what alpha is, you are supposed to square the roughness).

I thought it's possible to access Substance's shader code though, no? That should help pinpointing the problem.

**Comment by jaran** [comment]
I found a bunch of shader docs.  I put what i think are the relevant ones here as i can't seem to find them hosted by substance anywhere.  I do see they do alpha = roughness * roughness in a couple of places.  Hope it helps.

https://www.dropbox.com/sh/31wq4i4bfi8g8zk/AACKSlDZUalolmgdy-maFkvDa?dl=0

**Comment by jaran** [comment]
I got a response from Allegorithmic.  I put the fragment shaders they told me were relevant to this issue in the drop box as well.

"We take the linear roughness value directly from the texture, and use "alpha is roughness squared". We never used Burley's 2012 remapping."

**Comment by jaran** [comment]
@tagcup sorry i just moved it to github from gitlab here

https://github.com/jaran/godot-substance-test

**Comment by karroffel** [comment]
Oh what just came to my mind, this might have two possible causes:
 1. cubemap filtering
 2. specular/diffuse light equations

-----

1 . Roughness of the environment reflection is implemented by taking the skybox and applying a blur to it. The rougher the surface the more blurred the sky needs to be. Maybe the association of roughness <-> blur behaves like `blur = roughness ^ 2` or something similiar. That would cause applying a square root to the roughness to get the proper blur.

2. @mysticfall are there any lights in the scene? Because I noticed that the specular reflection on my GLES2 branch (using Phong) gets way too big with high roughness, that can cause things like skin to look way more shiny than it should be.

**Comment by tagcup** [comment]
I did some comparisons with substance using a metal sphere of varying roughness in steps of 0.1 with a different environment (no lights), and things don't match with sqrt in general either.

**Comment by tagcup** [comment]
@karroffel That could indeed be the case, because I couldn't spot any real differences in the material BRDF.

I guess one way to rule the environment map out would be to repeat the similar experiment with Unity vs Godot in an indoor scene, with an omni light and no background.

**Comment by karroffel** [comment]
I think what could be enough to fix this is change those lines

https://github.com/godotengine/godot/blob/5b7ebf4d04129d55cfaf346b0ce2de1fe8601579/drivers/gles3/rasterizer_storage_gles3.cpp#L1257

https://github.com/godotengine/godot/blob/5b7ebf4d04129d55cfaf346b0ce2de1fe8601579/drivers/gles3/rasterizer_storage_gles3.cpp#L1469

(one of them is not called from anywhere, I don't remember which one it is.)

Applying a `pow(X, 2.0)` on the roughness value should give the desired effects.

**Comment by fracteed** [comment]
Hey guys, I only recently discovered this thread, so thought I would put together a more definitive test scene between Substance Painter, Blender eevee and Godot. I have known for a while that Godot is a bit "off" with my textures from substance, but it can be a hard thing to quantify especially with various lighting conditions. Of course it is unrealistic to expect Godot to look exactly like other renderers, and it still does look pretty good. 

![roughness_test](https://user-images.githubusercontent.com/7741669/43989034-c2817476-9d85-11e8-9722-5cebee602abd.jpg)

As can be seen from this comparison, eevee is much closer to Substance than Godot. Godot is looking particularly off with the more blurred metallics as well as looking very blown out in general on the dielectrics (but that may be a saturation or levels issue?).

They are all in orthographic mode and use the same studio hdr (from HDRI Haven). I have tried to rotate the hdri's in Substance and Blender to match the default HDRI in Godot. Really wish that hdri's could be rotated in Godot!...and yes I did file an issue for this long ago :)

I chose this hdri so that just the blurred highlight of the area light is showing, without too much extraneous detail. On the left are 4 grades of roughness (0, 0.1, 0.2, 0.3, 0.4) with a plastic dielectric material and on the right with metallic ones. 

I have attached a zip of the Substance Painter, Blender 2.8 and Godot files with all textures. Hopefully this may help isolate the issue! 

[roughness_test.zip](https://github.com/godotengine/godot/files/2279976/roughness_test.zip)

**Comment by fracteed** [comment]
@karroffel @tagcup @akien-mga is this something that is likely to be fixed for 3.1? Now that I am aware of it, I am second guessing everything I do in Substance-Godot. Not sure if @reduz knows about this issue?

**Comment by BastiaanOlij** [comment]
Just a really stupid remark, this may have been covered already. Godot when importing textures does an sRGB to linear conversion so the textures are in linear color space for rendering and lighting. After rendering it brings the final result back to sRGB. That is great for albedo textures that hold color information but it would change the balance of these types of textures.  

Does disabling the sRGB setting on importing these textures make a difference?
![image](https://user-images.githubusercontent.com/1945449/44295482-151d7100-a2ed-11e8-9eb1-914ab278a402.png)

**Comment by fracteed** [comment]
@BastiaanOlij , it was certainly worth trying and I had a go, changing this and other settings in the import tab, but to no avail. As can be seen from tagcup's image earlier, the roughness looks wrong as compared to Substance, even without any maps.

Have also attached another image of Godot 2.0.6 with the color down at 50% grey from the default pure white. This is just to show the highlights better as they look blownout on the dielectrics that I posted earlier. As can be seen the 0.1 and 0.2 roughness levels look almost identical, as with the 0.3 and 0.4 levels. If you compare this to the original Substance capture, there is a definite gradation between all levels. Even the Blender test doesn't fare so well for the dielectrics (the ones on the left). 

![tester_50pc_grey](https://user-images.githubusercontent.com/7741669/44297164-57a47500-a310-11e8-8dc5-52488769cfb7.jpg)

**Comment by reduz** [comment]
By looking at this issue, I think what is clear is that roughness is not the issue, but that Substance uses a twice as bigger angle to do sampling from the cubemap. You can tell this by simple duplicating first half values in the screenshot posted:

![image](https://user-images.githubusercontent.com/6265307/44595233-d1b87c00-a79e-11e8-8794-08d5ad1922f6.png)

If this is standard, then Godot has to be changed to use the same angle.

**Comment by mysticfall** [comment]
Now it's finally fixed with #21680.
