### ISSUE TITLE
Add a render mode to output fragments ONLY to the depth buffer

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#18901]
Godot 3.0.2

I came across this QA post: https://godotengine.org/qa/28462/how-to-hide-the-water-plane-inside-a-boat
And I realized I couldn't find a way to have a material that outputs to the depth buffer ONLY, ignoring the color buffer.

This would allow to render the interior of a boat (or multiple boats) below sea level, for example, which was a technique available in Unity 3.4.1 already.
The technique is:

![image](https://user-images.githubusercontent.com/1311555/40068915-0d3085ea-586a-11e8-87cd-de271ec921fe.png)

1) Draw the boat
2) Draw whatever is inside the boat (passengers...)
3) Draw a mesh hull enclosing the boat, but only write it to the depth buffer, no color (not even transparency because that would break draw order)
4) Draw the sea: due to 3), it won't overlap with the inside of the boat's hull.

But that's not possible in Godot without the mentionned feature.

Note: in https://github.com/godotengine/godot/issues/18231 it's about writing custom value to depth, however this issue is different because here we need to output to the depth ONLY.

Note 2: Mayyybe this feature could break any further rendering pass that uses the depth (like SSAO), because it will obviously contain a hull that served as rendering technique, but doesn't reflect what you can see with your eyes. If that's true, then we need to figure out a way because that simple problem is pretty legit and every other solution I thought about was either a PITA or only work in ultra special situations.

**Comment by shartte** [comment]
I need this feature as well, but on a material. Essentially I need to have flags on a material that control `glColorMask` and `glDepthMask`.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
