### ISSUE TITLE
Thread and OS.execute very limited

### ISSUE THREAD

**Issue by Logmytech** [godotengine/godot#18919]
https://godotengine.org/qa/28539/killing-a-thread
https://godotengine.org/qa/28466/unable-to-get-os-execute-result-unless-blocking

1) It'd be cool to have an option to be able to kill a running thread and also `OS.execute()` non blocking which is similar to a thread
There doesn't seem to be a way to do it and if there is, it isn't mentioned in the docs.

2) Need ability to have a call back function or singal for threads and OS.execute on completed, errored etc.
Maybe the callback function could have an argument that is a dictionary which will contain all the details. Or maybe just plain arguments, which might not be all that good, cos unlike Python 3 GDScript is very limited when it comes to arguments(no **kwargs, *args, *, unpacking etc)

**Comment by PostPollux** [comment]
These additions would be awesome. I've started to develop an open source render manager in Godot and this would be pretty essential. I noticed that limitation, too, but I thought maybe it can be bypassed with GDNative. I've never used GDNative though, as I'm new to Godot. So I hope this feature get's implementd.

**Comment by FeralBytes** [comment]
I think this may already be possible. Although a dev would have to confirm that this code does indeed run on a background thread. Here is how I do just this. I have created an AutoLoad Singleton called "Threaded"
```
extends Node

var thread_for_execute = null
var queue_for_execute = []

######## Begin # OS.execute() Threaded ########
func execute(cmd, callback_node, callback_func):
    if thread_for_execute == null:
        thread_for_execute = Thread.new()
    var output = []
    var state = 'waiting'
    var task = [output, cmd, callback_node, callback_func, state]
    queue_for_execute.append(task)
    if queue_for_execute.size() == 1:
        # Only item in the list so start the task.
        call_deferred('defered_start_execute')
        
func defered_start_execute():
    queue_for_execute[0][4] = 'executing'
    var args = [queue_for_execute[0][0], queue_for_execute[0][1], queue_for_execute[0][2], queue_for_execute[0][3]]
    thread_for_execute.start(self, '_threaded_execute', args)
    
func _threaded_execute(args):
    var output = args[0]
    var cmd = args[1]
    var callback_node = args[2]
    var callback_func = args[3]
    OS.execute('/bin/sh', cmd, true, output)
    args[0] = output
    call_deferred('_clean_up_execute_thread')
    return args
    
func _clean_up_execute_thread():
    var args = thread_for_execute.wait_to_finish()
    var output = args[0]
    var cmd = args[1]
    var callback_node = args[2]
    var callback_func = args[3]
    var callable_node = get_node(callback_node)
    var callable_func = funcref(callable_node, callback_func)
    callable_func.call_func(output[0])
    queue_for_execute.pop_front()
    if queue_for_execute.size() > 0:
        # Start the next task.
        call_deferred('defered_start_execute')
    elif queue_for_execute.size() == 0:
        thread_for_execute = null
######## End # OS.execute() Threaded ########
```
I then call the code like below where I am getting the branch name of a git repository.
```
var cmd = ['-c', 'cd ' + str(configuration.Settings.Project.Path) + ' && git rev-parse --abbrev-ref HEAD']
Threaded.execute(cmd, '/root/ProjectScene', 'callback_branch')
```
Now it would be nice if OS.execute had an option for this bultin, but at least there is a way to work around the current limitation.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
