### ISSUE TITLE
Custom Cubemap in Material Options/Settings

### ISSUE THREAD

**Issue by abhaskumarsinha** [godotengine/godot#18925]
Hello Godot Devs,

Here's a small Addition to Material Options of Godot 3.x
**Custom Cubemap**
since the implementation of Reflection Probes in GLES2 Backend of Godot 3.1 is not a Good Idea as it can cause severe Slowdowns.
The best way to fake Reflections is to add Cubemap, but I think that using Environment Cubemap as reflection is not a Good Idea, so, I want a small Implementation of Custom Cubemap

Present Reflection System -
**Outdoor Scene:-** It's using just Environment Paranormal/Cubemap/HDRi as the reflection base, but it's not really a Good idea because for example - Creating a Forest, scene, an Artist will always want reflection of Trees/Grasses/Bushes in the surroundings, like water which is reflective, or metal Gun, but the problem is that if he uses the same cubemap in HDRi which is used in lighting the Surrounding, then there'd be some unwanted Trees and Birds in the sky and the Heavy HDRi file as reflection is known to cause Serious Performance Problems. In case, he wishes to light the scene Manually, then, he can use a sky paranoma as the Cubemap, but it'll lack the reflection of trees, and forest stuff, which is not desired for an in-forest scene game.

**Indoor Scene-** - In case if Indoor Scene, there can be tons of metal/high reflective objects around, and in that case using a Sky Cubemap is not Desired either. Also, Baking Lights would not be enough.

**Solution:-** If an option for Custom Cubemap is added along Roughness, metalness, albedo, Normal Maps/ OA, then it can seriously not only increase the Graphics of the Game but as well as the Workflow, as it will take hours to add cubemap option by writing shaders and Implementing for each material. 

I dun think that it should take too much time to be added

PS - I've tried adding this feature, but failed, probably bugs

**Comment by Calinou** [comment]
Using a custom sky for reflection of a single material sounds useful. Note that that Godot does not use cubemaps, it uses panoramas instead (which have similar results anyway, your suggestion is still possible with panorama skies).

**Comment by abhaskumarsinha** [comment]
@Calinou Also, I think that it's possible to use a paranoma as Environment and another as Reflections as material.

**Comment by abhaskumarsinha** [comment]
Also, I didn't Paranoma because most HDRi come with paranoma, so adding Paranoma in Cubemap reflection can cause Slowdowns, instead Cubemap comes in form of JPEG which can't cause slowdowns. (I know there can also be HDRi in form of Skyboxes and vice versa too),

Feel free to edit

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
