### ISSUE TITLE
New property inspector:  Scripts don't show filename

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#18983]
**Godot version:**
ba134d4

**Issue description:**
This is more of a personal nitpick.  While I find the script thumb preview *marginally* useful, seeing a filename at a glance would be much more useful, or in a tooltip if must be.  I'm assuming this is simply a feature in testing (for supporting property field previews which weren't feasible before?), but nevertheless it seems to be an issue.

**Comment by homer666** [comment]
It's to the right of the thumbnail, same as all other resources. You need to stretch the inspector to see it:

![image](https://user-images.githubusercontent.com/27100585/40218558-0e45dec4-5ab5-11e8-9321-fa8fa4e7c8c9.png)

It's pretty dumb in this case, yeah. Scripts should just show their resource icons rather than massive thumbnails.

**Comment by vnen** [comment]
I don't think it should show the thumbnail at all. It was deliberately removed from the old inspector.
