### ISSUE TITLE
App Store: ERROR ITMS-90725 (apps must be built with iOS 11.0+ included in Xcode 9.0+)

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#18995]
**Godot version:**
Godot 2.1.4

**OS/device including version:**
iOS

**Issue description:**
I submitted a project to the App Store and I got this message:
ERROR ITMS-90725: "SDK Version Issue. This app was built with an unknown SDK. All new iOS apps submitted to the App Store must be built with the iOS '11.0' SDK or later, included in Xcode [9.0] or later. Please update Xcode and rebuild your app."
Are there any plan to release a new iOS template using iOS SDK 11 or later?

**Comment by Zireael07** [comment]
I believe 3.0 comes with SDK 11?

**Comment by zoiba** [comment]
Haven't tried publishing any Godot 3 project on App Store yet, anyway my project must run on low-end hardware too, so I need Godot 2.1.x for now

**Comment by akien-mga** [comment]
CC @BastiaanOlij @endragor, I have no clue how to adapt the `detect.py` to enforce using the SDK version Apple wants.

**Comment by endragor** [comment]
It's supposed to use the latest SDK by default. It seems template builds don't set `osx_image: xcode9.3` for Travis.

**Comment by akien-mga** [comment]
Thanks, I'll change that then.

**Comment by akien-mga** [comment]
I've started a build for 2.1.5 RC2 with Xcode 9.3 for macOS and iOS: https://travis-ci.org/GodotBuilder/godot-builds/builds/380704852

It works fine for `release_debug` builds, but `release` builds fail with a linking error:
```
[Initial build] Linking Static Library ==> modules/freetype/libfreetype_builtin.osx.opt.fat.a
Ranlib Library         ==> modules/freetype/libfreetype_builtin.osx.opt.fat.a
/Applications/Xcode-9.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: i386 file: modules/freetype/libfreetype_builtin.osx.opt.fat.a(ftpic.osx.opt.fat.o) has no symbols
/Applications/Xcode-9.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: modules/freetype/libfreetype_builtin.osx.opt.fat.a(ftpic.osx.opt.fat.o) has no symbols
[Initial build] progress_finish(["progress_finish"], [])
[Initial build] 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Any idea?

**Comment by BastiaanOlij** [comment]
@akien-mga I can't build anymore because on this laptop I'm stuck on 10.12 and I can't install the latest xcode, however one thing to try is to have a look at detect.py. I remember updating that for Godot 3 but never for Godot 2 so it is probably compiling against version of iOS that Apple no longer supports. 

Try bumping up -miphoneos-version-min=7.0 to -miphoneos-version-min=9.0 in detect.py (it appears a lot of times, change each occurence).

**Comment by akien-mga** [comment]
Thanks, I've done the change in this commit: 363497a

I'll upload a new iphone template and ask for testing to confirm that it fixes this issue.

**Comment by BastiaanOlij** [comment]
@akien-mga did that work? Damn that was a pure gamble on my part to be honest.

**Comment by akien-mga** [comment]
@zoiba Could you try this template and see if it works better (or *at all* :P)?

[GodotiOSXCode.zip](https://github.com/godotengine/godot/files/2039265/GodotiOSXCode.zip)

Note that it's only the debug template, I have issues building a release template right now.

**Comment by zoiba** [comment]
it seems my iMac it's too old for updating to latest XCode version, so, I asked a collaborator of mine to give a try. this is what back to me
![snapshoot](https://user-images.githubusercontent.com/5225262/40606965-593bf2ba-6267-11e8-8865-d317fdb6c13f.jpg)

**Comment by akien-mga** [comment]
Can you test with the iOS template in http://op.godotengine.org:81/downloads/2.1.5/_test/ ? It now includes the release binary too, the lack of which might have caused the issue above.

There's also an OSX editor binary and OSX templates in that folder, since I've just changed the buildsystem to use XCode 9.0 (9.3 doesn't work for release templates), I'd be glad if you could give them a try too to ensure they work.

**Comment by zoiba** [comment]
The new template gererates a working ipa. Anyway when we submit it to the app store we get this error.

<img width="1190" alt="schermata 2017-11-29 alle 18 17 58" src="https://user-images.githubusercontent.com/5225262/40783658-6fbc6226-64e3-11e8-8668-51372a71db10.png">

**Comment by akien-mga** [comment]
Too bad :/

Well someone with iOS experience (and Apple hardware...) will need to take it from here, I'm out of clues.

**Comment by zoiba** [comment]
This bug is quite critic because no one can pubblish anymore on appstore by using godot 2.1.x branch

**Comment by akien-mga** [comment]
Could you try with those new binaries built against Xcode 9.2? http://op.godotengine.org:81/downloads/2.1.5/_test/

Please ensure that you build your iOS app in Xcode 9.0 or later on your end too, it might be the reason why the previous binaries (made with 9.0, so in theory fine) did not pass.

**Comment by Delfrank94** [comment]
We are having the same issue, one of the teammembers found this
![image](https://user-images.githubusercontent.com/17836214/41158320-e257c980-6afe-11e8-9100-4e0697d7d205.png) maybe the problem have something to do with this

**Comment by akien-mga** [comment]
Sounds like using the macOS images with Xcode on Travis CI is no longer a viable solution to build official binaries then :|

@hpvb I'll need your help to make the next 2.1.5 round for iOS.

**Comment by akien-mga** [comment]
> Sounds like using the macOS images with Xcode on Travis CI is no longer a viable solution to build official binaries then :|

Though it would mean that 3.0.2 iOS templates should exhibit the same issue too.

**Comment by akien-mga** [comment]
@endragor Maybe parts of your #11783 would be needed in the 2.1 branch too for compatibility with Xcode 9.0+? Namely " - Fixes iOS export to work with Xcode 9 (released recently).".

**Comment by josematiasrivero** [comment]
@akien-mga @zoiba Team at Ensolvers (https://github.com/ensolvers) found an initial solution for the problem when trying to compile the iOS templates from the tag `2.1.4-stable`. Seems that code at `platform/iphone/detect.py` forces to use the "general" iOS SDK  instead of a concrete one. Changing the line 28 in that file from

```
('IPHONESDK', 'path to the iphone SDK', '/Applications/Xcode.app/Contents/Developer/Platforms/${IPHONEPLATFORM}.platform/Developer/SDKs/${IPHONEPLATFORM}.sdk/'),
```

to 

```
('IPHONESDK', 'path to the iphone SDK', '/Applications/Xcode.app/Contents/Developer/Platforms/${IPHONEPLATFORM}.platform/Developer/SDKs/${IPHONEPLATFORM}11.3.sdk/'),
```

we forced to build using the 11.3 SDK, which resulted in the correct SDK info stored in the destination object files:

![image](https://user-images.githubusercontent.com/753602/41508175-b6cce2ea-7216-11e8-9aa7-8e76d3fdee4e.png)

Now we are facing a different problem: we were able to build arm64 architecture following the tutorial at http://docs.godotengine.org/en/2.1/development/compiling/compiling_for_ios.html this way, but building for armv7 (`scons p=iphone tools=no bits=32 target=release arch=arm`) takes literally *hours* in the linking phase and finally throws the error below, so we were able only to generate a .ipa file that supports arm64 - which puts some limits in the testing.

![image](https://user-images.githubusercontent.com/753602/41508215-76fafbce-7217-11e8-9f6c-7dd10516c3f3.png)

@akien-mga Maybe with the info here you will be able to generate object files for release and debug versions

Hope this helps

**Comment by zoiba** [comment]
We just tried to upload a project to the app store and it seems to work. Now the app is in "waiting for verify" state

**Comment by josematiasrivero** [comment]
Glad to read that @zoiba!

We are currently testing the stability of the build with our game, if you have any news about yours just let us know

**Comment by akien-mga** [comment]
Could you guys try this build of the current `2.1` branch? http://op.godotengine.org:81/downloads/2.1.5/_test/GodotiOSXCode.zip

It uses this variant of @josematiasrivero's patch using the cleaner `-sdk_version` linker flag: https://github.com/GodotBuilder/godot-builds/blob/2.1/patches/0001-iphone-Link-against-SDK-version-11.4.patch

The optimization changes are not needed, it's a compiler bug in Xcode 9.3 (and maybe 9.4? didn't test) but it builds fine with Xcode 9.2.

**Comment by akien-mga** [comment]
I got confirmation that `otool` reports `sdk 11.4` for those binaries, so it seems my fix worked :)

Not sure why it appears not to be necessary for Godot 3.0.x so far...

Fixed by e3339862f.

**Comment by stuckthread** [comment]
Getting the same error on a different (unrelated) project. Ugh!

**Comment by Imerion** [comment]
It seems we need a newly compiled godot_opt.iphone (see this #26593).

Is it possible to do that manually in some way?
