### ISSUE TITLE
Result in PhysicsDirectSpaceState to return face index of collision

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#1903]
I was write a painter, but in large mesh I need to write a long code to optimize the face search.
I check that Uni... rival have a face index in return function.

**Comment by akien-mga** [comment]
Kind of related to #684.

**Comment by Calinou** [comment]
@marcosbitetti Is this issue still relevant in the `master` branch?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
