### ISSUE TITLE
Problem with RemoveAndSkip in c#

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot#19048]
**Godot version:** Mono 3.0.2

**OS/device including version:**

Nvidia Geforce 920 m
intel core i7

**Issue description:**

I'm trying to remove a rigidbody2d node and after that this node just teleport to the corner of the screen.
[Zabawy z c#.zip](https://github.com/godotengine/godot/files/2019701/Zabawy.z.c.zip)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@111ukasz111 Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
