### ISSUE TITLE
Support for dynamic autotiling (minitiles)

### ISSUE THREAD

**Issue by lunarfyre7** [godotengine/godot#19059]
I think that a useful addition to the autotile system would be a "minitile" mode, I believe RPG Maker has a similar feature, and would greatly ease the creation of tilesets as long as they are compatible with being corner based. It would behave very similar to the 2x2 bitmask but each tile contains 4 tiles, one for each corner, there would be 5 corner types for different neighbor combinations: corner, inside corner, vertical, horizontal, and solid which are used for generating the required tile based on it's neighbors. With only 5 tiles this technique gives a similar level of flexibility as the 3x3 tile mode, but with a far smaller sprite sheet than the 47 (aprox.) tile sized ones the full 3x3 set. I implemented a proof of concept of this technique in love2d a while ago.

Tile sprite structure:
![Imgur](https://i.imgur.com/grJJor3.png)
[Full image/video set](https://imgur.com/a/RtBKXGY)
[source](https://github.com/lunarfyre7/corner_cutter)
![corner tile demo](https://user-images.githubusercontent.com/15057106/40276035-9cda9602-5bb4-11e8-9483-e9bcfffe2669.gif)

**Comment by isaacremnant** [comment]
You could achieve the same outcome with a 2x2 bitmask at the expense of using four times as many tiles. If you need want based tiles, it's not difficult to extend your sprites to the full 47 tileset (as you(?) posted on reddit). This is a better idea since you'll most likely want to edit the tiles to smooth transitions and so on.

My opinion is that the 2x2 and 3x3 autotiles implementations are sufficient and consistent. To implement what you described directly (without relying on 2x2 and 3x3),  edge-based information would have to be implemented in addition to neighbors (what is done currently with the bitmask).

I think this task is best thought of as asset creation, which I don't think is the goal of Godot.

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by MarianoGnu** [comment]
Slice your 16x16  tileset into 8x8 tileset and configure the bitmasks, it will work like what you describe.
RPG-Maker tileset's was my first idea for implementing tilesets, but has a terrible problem, you have to setup collision shapes for every tile quarter, so in practive is the same than just making your tilesize the half and set the collisions.

**Comment by lunarfyre7** [comment]
Ah, yes I was the one who posted the Reddit thread. The problem I experienced with using a corner tile style sprite as 2x2 tiles scaled down in Godot was the repeating edges were randomly placed. So instead of a pattern like [][][][][] where all the tiles are places in the right order, it would be more like [[][[]]]][]][], which is a problem if each tile depends on being neighbored to another as in the case of corner tiles. 

But I think that you are both right in that it's better to simply assemble a larger tileset and work with that, especially since that can be automated.

**Comment by MarianoGnu** [comment]
you can override the virtual function _forward_subtile_selection with a tool script asigned to your TileSet to pick what tile place while drawing. if gives you information of the tilemap and the tiles around the one you are drawing. There's no explanation on the docs yet, but meybe you can figure it out from the arguments
http://docs.godotengine.org/en/3.0/classes/class_tileset.html#class-tileset-forward-subtile-selection

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
