### ISSUE TITLE
OS.execute not returning a process id.

### ISSUE THREAD

**Issue by romeojulietthotel** [godotengine/godot#19056]
**Godot version:**

git master

**OS/device including version:**

Linux kernl 4.16.9

**Issue description:**

An integer that was not a pid was returned.
An pid integer should be returned that's in the range > 1024 and <= /proc/sys/kernel/pid_max

**Steps to reproduce:**

var pid = OS.execute('ls', ['-l'], true, output)
print(" pid = ", pid)

 pid = -391036616

**Minimal reproduction project:**

**Comment by romeojulietthotel** [comment]
If I place an fprintf right after https://github.com/godotengine/godot/blob/master/drivers/unix/os_unix.cpp#L296

Then I see the correct PID printed to stderr and then I see it prints PID 0. This seems correct as the child is pid 0. But somewhere else the r_child_pid is not right.

In os_unix.cpp pid is pid_t and ProcessId is int64_t.

That's all I know about this.

**Comment by romeojulietthotel** [comment]
I figured out that if blocking == false then we get the pid, but when blocking == true we do not. We should provide the pid for both cases.

**Comment by akien-mga** [comment]
I guess you can just move this out of the `else`: https://github.com/godotengine/godot/blob/master/drivers/unix/os_unix.cpp#L325

**Comment by akien-mga** [comment]
> Some other code path must get followed and I don't know where. Looks like when blocking is true then pid is returned as an uninitialized variable. i.e. a large random + or - integer.

Well yes, that's why I said the code which sets `r_child_id` should be moved out of the `else`, otherwise it's never called when `p_blocking` is true, and thus the variable is returned uninitialized.

**Comment by romeojulietthotel** [comment]
No, the problem (that I've not explained well) is this:

### In gdscript:
Blocking = true

### In os_unix.cpp:
Remove the `else`
Place an` fprintf` in the code to print out the `pid` to stdout

### Now run it and get:
The proper pid gets printed to stdout
Some other value gets printed from gdscript and that value looks like the kind of value
one would see when a variable has not been initialized. So `r_child_id` is getting munged
somewhere.


Also we need to change the code inside `if (p_blocking)` to also check WIFEXITED.

>        WEXITSTATUS(wstatus)
>               returns  the  exit  status of the child.  This consists of the least significant 8 bits of the
>               status argument that the child specified in a call to exit(3) or _exit(2) or as  the  argument
>               for  a  return  statement in main().  This macro should be employed only if WIFEXITED returned
>               true.
>

**Comment by neikeq** [comment]
I think we should separate this into two methods, `execute` for blocking and `spawn_process`/`create_process` for non-blocking.

**Comment by romeojulietthotel** [comment]
Also someone could explain r_child_id, like how/where is it initialized. Basicaly the entire lifetime of r_child_id is unclear to me. But might be to someone that knows the code base.

**Comment by neikeq** [comment]
r_child_id is the process id. It's only initialized if the `blocking` parameter is false. Not sure what you mean by the entire lifetime of r_child_id, but right now there is no way to track the life of a process spawned in a non-blocking way.

**Comment by neikeq** [comment]
The reason the returned pid was -391036616 is because, as you mention above, it's never initialized, and in C++ that means it could contain anything. To fix that, it should be initialized here to something like 0 or -1:
https://github.com/godotengine/godot/blob/46bab3abc71156cd2da95312368f2c72abe7b151/core/bind/core_bind.cpp#L402

The OS class is not an Object derived type, so its `execute` implementation is not what is exposed to GDScript. It actually works like this:

- OS class
  - OS_Unix inherits OS.
  - OS_Windows inherits OS.
  - ...
- _OS inherits Object and wraps the OS class

_OS can be found in core/bind/core_bind.cpp/.h

**Comment by akien-mga** [comment]
As mentioned above, this patch should fix the issue you described initially:
```
diff --git a/drivers/unix/os_unix.cpp b/drivers/unix/os_unix.cpp
index 05dfd69f5..082104d69 100644
--- a/drivers/unix/os_unix.cpp
+++ b/drivers/unix/os_unix.cpp
@@ -320,10 +320,10 @@ Error OS_Unix::execute(const String &p_path, const List<String> &p_arguments, bo
                waitpid(pid, &status, 0);
                if (r_exitcode)
                        *r_exitcode = WEXITSTATUS(status);
-       } else {
+       }
 
-               if (r_child_id)
-                       *r_child_id = pid;
+       if (r_child_id)
+               *r_child_id = pid;
        }
 
        return OK;
```
`r_child_id` IS the process ID returned by `OS.execute` in GDScript.

**Comment by neikeq** [comment]
Note, that would need to be applied to all platform implementations. At least OS_Windows doesn't initialize it either.

**Comment by akien-mga** [comment]
I made this commit: https://github.com/akien-mga/godot/commit/ac75e3d5ac59bc8ba2c3cce5cf33ba240a429245

But actually it doesn't work, because `OS.execute` in `core_bind.cpp` always passes a pipe: https://github.com/godotengine/godot/blob/1433c2cbbb89df1edb0b727c9781481af5705f59/core/bind/core_bind.cpp#L406-L407
So we're in this branch where no PID is even retrieved: https://github.com/godotengine/godot/blob/ce64c2a32e0f1db8f0f75e1091a24d01fd669044/drivers/unix/os_unix.cpp#L264-L294
And with some googling I don't see any easy method to retrieve a PID when using `popen`.

So with the current `OS::execute` implementation, it can't be fixed AFAICT. And since it's mostly useless to get the PID of a process that was executed in blocking mode (because once it returns and gives you the PID, the process was terminated already), I'll just mention this caveat in the documentation.

Improving the blocking mode/allow better threading is tracked in #18919 already.

**Comment by akien-mga** [comment]
Well reopening until documentation gets fixed (in a minute).

**Comment by neikeq** [comment]
IMO, like I said before, this should be fixed the next time we break compatability, by separating it into two methods.

**Comment by akien-mga** [comment]
> IMO, like I said before, this should be fixed the next time we break compatability, by separating it into two methods.

I agree. In the meantime I've added documentation and an arbitrary default PID of -2 for blocking mode in #19266.

**Comment by romeojulietthotel** [comment]
Seems to me this issue should remain open or a new one created to track the progress of this feature or otherwise it will not be visible. Is that the way?

**Comment by akien-mga** [comment]
Well...

> Improving the blocking mode/allow better threading is tracked in #18919 already.
