### ISSUE TITLE
Add support for code regions to GDScript

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19078]
I know its not an urgent issue, but if GDScript will support scrollable regions, like in C#, life become more better.. (and sharp symbol ideally fits in GDScript cuz its already used for comments) 

```
#region Test
.... 
#endregion
```

**Comment by nhydock** [comment]
`#region` in C# is a pretty polarizing feature of the language.  I'm of the boat that thinks it is a bandaid for overly complicated code that should instead be refactored/rethought.  However, I do not entirely mind its presence in general purpose languages, as I'd rather look at poorly written code that has a semblance of documentation than poorly written code with no documentation.

However, GDScript is not a general purpose language, and benefits from keeping things concise.

**Comment by Zylann** [comment]
The only place I see these useful is to delimit code that was generated and should not be edited. But I don't think this use case exists in GDScript.

**Comment by akien-mga** [comment]
For those like me who had no clue what regions are: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region

Note that it's an editor-specific feature (based on a language macro) and not really a language feature per se. Since we already have code folding, I don't see much use case for this. And if it should be *scrollable* instead of just foldable, then it requires a lot of work on TextEdit to be able to have multiple scrollable areas, for what seems to be a quite non-consensual feature.

I'll leave it up to gather some more opinions, but sounds like a "not wanted" so far.

**Comment by Chaosus** [comment]
Yeah, not a good idea really

**Comment by plyoung** [comment]
Those who are not fans of it, you do not have to use it. ;-)
Many of us comming from Unity and C# do use it so would be nice if it can be added when there is time.

**Comment by stilestr** [comment]
> Those who are not fans of it, you do not have to use it. ;-) Many of us comming from Unity and C# do use it so would be nice if it can be added when there is time.

for those of you who are stumbling upon this thread when searching if Godot has regions, this is my workaround, maybe you will find it useful if you are coming from C#

![image](https://github.com/godotengine/godot/assets/4535064/325b8e5a-0a8b-49ad-b972-5b12c8e5d10d)
