### ISSUE TITLE
[WebGL2] "3D Platformer" raises warnings/errors and takes 8minutes to load

### ISSUE THREAD

**Issue by 37TS** [godotengine/godot#19093]
**Godot version:**
Godot_v3.0.3-rc2_win64 (with rc1 export templates because rc2 templates for html5 are missing, though the same happens with Godot_v3.0.3-rc1_win64 too)

**OS/device including version:**
Win10 x64 / R9 280X / Firefox 60.0.1 (64-bit)

**Issue description:**
Multiple errors in the web console when exporting the demo project "3D Platformer".
(attached as text file because they are repeated many times).
Minor/negligible artifacts are present but the game is fully playable and sound works fine too (though, the attached video recording was set to sync at 30 fps out of almost 60fps).
The real bummer is that it takes more than 8 minutes to load the project. As a counterexample I can load quake js in a matter of seconds and it loads through internet, not offline. Offline loading of WASM projects takes even less on my machine.

Here's the video proving the demo loads fine (heavily compressed to 19 megabytes, uploaded on vimeo):

[![3D Platformer Demo](https://i.vimeocdn.com/video/702426680_300x170.webp)](https://player.vimeo.com/video/271195496 "3D Platformer Demo")

The errors are the following (I've marked some in bold):

- Use of nsIFile in content process is deprecated.  NetUtil.jsm:302:12
- Use of nsIFile in content process is deprecated.  filesystem.js:40:9
- Successfully compiled asm.js code (total compilation time 92ms; **unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))**
- Error: WebGL warning: blitFramebuffer: DRAW_FRAMEBUFFER: This operation requires zeroing texture data. **This is slow**.  Platformer%203D.js:4:226275
- Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.  Platformer%203D.js:4:231168
- Error: WebGL warning: drawElementsInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.  Platformer%203D.js:4:231281
- **ERROR**: Index p_bus=32 out of size (buses.size()=3)  Platformer%203D.html:366:6
 At: servers/audio_server.cpp:432:thread_get_channel_mix_buffer() - Index p_bus=32 **out of size** (buses.size()=3)  Platformer%203D.html:366:6

The game **hangs for some seconds** because of the amount of sound related errors leaving the game stuck in gouraud shading, then environment mapping starts loading and the following appears (again):

- Error: WebGL warning: blitFramebuffer: DRAW_FRAMEBUFFER: This operation requires zeroing texture data. This is slow.  Platformer%203D.js:4:226275
- Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.  Platformer%203D.js:4:231168
- Error: WebGL warning: drawElementsInstanced: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE.  Platformer%203D.js:4:231281
- Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)  Platformer%203D.js:4:231281

[3dplatformer_html5__errors.txt](https://github.com/godotengine/godot/files/2024490/3dplatformer_html5__errors.txt)
(I've removed some browser "reflows" from the txt file attached)

**Steps to reproduce:**

- Export the demo "3D Platformer" as HTML5 project
- Do not select a texture compression out of the 3 available because you'll have more errors (s3, etc, etc2)
- Load it in the browser

**Minimal reproduction project:**
Not needed. It's the official, unmodified demo.

**Comment by 37TS** [comment]
@reduz 
Sorry to bother, I was just wondering if somebody had the possibility to analyze these problems.
I'm totally new to Godot and I'm still a long way before I can try to patch the source directly considering the amount of code.
I'd really appreciate any input/direction/suggestion.

**Comment by Zireael07** [comment]
Someone probably can, but you filled the issue only 17h ago.

There is such a thing as timezones and sleep :)

**Comment by 37TS** [comment]
@Zireael07 I didn't expect someone to urge with a fix :P

I was merely trying to start a discussion on hypothetical causes. ;)

I didn't see a lot of (WASM based) 3D exports "flying around", I thought it could be directly related to the problems above.

**Comment by akien-mga** [comment]
CC @eska014

**Comment by LinuxUserGD** [comment]
For me it doesn't run:

<details>
Bootstrapped manifest not allowed to use 'resource' directive. chrome.manifest:2

Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“key_toggleReaderMode” browser.xul

Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul

onboarding-session-end should pass valid session_key OnboardingTelemetry.jsm:378

update.locale file doesn't exist in either the application or GRE directories UpdateUtils.jsm:126

1541065802871	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242

1541065802880	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242

1541065803118	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242

1541065803122	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242

1541065803125	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242

1541065803127	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 121"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:121
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:131
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:313
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:242
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Image corrupt or truncated. 

68747470733a2f2f646f776e6c6f61642e74757866616d696c792e6f72672f676f646f74656e67696e652f6d656469612f73637265656e73686f74732f656469746f725f33645f66726163746565642e6a7067
this._recipeManager is null LoginManagerParent.jsm:85
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 102"  data: no]

Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars2.githubusercontent.com/favicon.ico (“default-src”).

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 102"  data: no]

Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars2.githubusercontent.com/favicon.ico (“default-src”).

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
[Exception... "Component returned failure code: 0x805e0006 [nsIChannel.asyncOpen2]"  nsresult: "0x805e0006 (<unknown>)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 102"  data: no]

Content Security Policy: The page’s settings blocked the loading of a resource at https://avatars0.githubusercontent.com/favicon.ico (“default-src”).
TypeError: Argument 9 of WebGL2RenderingContext.texImage2D is not an object. Solus-Stunts.js:7:294439

uncaught exception: abort(101). Build with -s ASSERTIONS=1 for more info. Solus-Stunts.js:7:27006
uncaught exception: abort(101). Build with -s ASSERTIONS=1 for more info.

Error: WebGL warning: texImage2D: With format DEPTH_COMPONENT24, this function may only be called with target=TEXTURE_2D, data=null, and level=0.
Platformer 3D.js:7:294811

Error: WebGL warning: renderbufferStorage: Invalid `internalFormat`: 0x81a6. Platformer 3D.js:7:293783

Error: WebGL warning: checkFramebufferStatus: Framebuffer not complete. (status: 0x8cd6) 

DEPTH_ATTACHMENT's image is not defined Platformer 3D.js:7:280560

Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) Platformer 3D.js:7:280560
uncaught exception: abort(101). Build with -s ASSERTIONS=1 for more info.
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
uncaught exception: abort(101). Build with -s ASSERTIONS=1 for more info.

Error: WebGL warning: texImage2D: With format DEPTH_COMPONENT24, this function may only be called with target=TEXTURE_2D, data=null, and level=0.
Platformer 3D.js:7:294811

Error: WebGL warning: renderbufferStorage: Invalid `internalFormat`: 0x81a6. Platformer 3D.js:7:293783

Error: WebGL warning: checkFramebufferStatus: Framebuffer not complete. (status: 0x8cd6) DEPTH_ATTACHMENT's image is not defined Platformer 3D.js:7:280560

Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings) Platformer 3D.js:7:280560
uncaught exception: abort(101). Build with -s ASSERTIONS=1 for more info.

InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.

TypeError: this.mm.content is null WebProgressChild.jsm:58:7
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.github.com/_private/browser/stats. (Reason: CORS request did not succeed).[Learn More]
NS_ERROR_ILLEGAL_VALUE: 
</details>

**Comment by clayjohn** [comment]
We are no longer working on the WebGL2 backend due to poor driver support on most systems. We recommend you use the GLES2/WebGL backend instead. 

Unfortunately, that means this bug just isn't going to be fixed in GLES3/WebGL2, sorry.
