### ISSUE TITLE
Implement Voronoi Fracture?

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#19117]
It would be nice for godot to support Voronoi fracture.
I know bullet physics does.

![screenshot from 2018-05-23 14-17-44](https://user-images.githubusercontent.com/19777767/40409157-21badbfc-5e94-11e8-9586-8f09fc81736a.png)

**Comment by akien-mga** [comment]
CC @AndreaCatania @reduz

**Comment by AndreaCatania** [comment]
This is one of the thing that I've to implement, but right now I'm not able to tell you when I can start to work on it. I let you know :grinning:

**Comment by Ashafix** [comment]
I wrote a Godot plugin using the C++ interface for Qhull (http://www.qhull.org/). It works for 2D rectangles and 3D boxes returning a number of defined fragments.

Left corner: Voronoi cells on with random colors and alpha overlaid on sprite.
Main scene: A body which is replaced with Voronoi fragments upon impact.

![Voronoi](https://media.discordapp.net/attachments/466618157935886347/500371104721010731/ezgif-2-5f7ff1b04305.gif)

What would be needed to integrate it into the Godot engine?

### Usage

**2D**

`voro = Voronoi.new()`
`voro.voronoi2d(100)`
Calculate 100 2d Voronoi points inside a square

`voro.get_vertexes()`
Returns a dictionary where the vertex index is the key and the value is a Vector2

`voro.get_faces()`
Returns an array of arrays where the inner array contains all vertex indexes for a face

**3D**
`voro.voronoi3d(25)`
Calculate 25 2D Voronoi points inside a cube

`voro.get_faces()`
Returns an array of arrays which contain the triangles to generate the mesh for the Voronoi fragment.

### Performance

**2D**

i5-2500, Windows 10, compiled with standard settings

| points | msec |
| --- | --- |
| 10 | 6 |
| 25 | 11 |
| 50 | 22 |
| 250 | 104 |
| 1000 | 419 |

**3D**

| points | msec |
| --- | --- |
|10 | 24 | 
| 25 | 68 | 
| 50 | 147 | 
| 250 | 838 |  
| 1000 | 3732 |

**Comment by AndreaCatania** [comment]
Awesome Job.
Would be useful try it in order to understand it and then discuss how to integrate it inside the editor.

Do you think is it possible test it?

**Comment by Ashafix** [comment]
@AndreaCatania an example project is attached
[voro_test.zip](https://github.com/godotengine/godot/files/2526349/voro_test.zip)

If you check out the voronoi branch from my Godot fork (https://github.com/Ashafix/godot/tree/voronoi), the attached project should work (tested on Windows only).

The teleport effect is due to the fact that the edges of the box are of length 2 while the Voronoi box has a length of 1. It obviously needs some more work.

**Comment by AndreaCatania** [comment]
> The teleport effect is due to the fact that the edges of the box are of length 2 while the Voronoi box has a length of 1. It obviously needs some more work.

To be merged we require that you implement it properly. Let us know when it's done

**Comment by Jollyblu** [comment]
Hello there is any chance this will be implemented in Godot 3.2? Also with Lloyd’s Relaxation? It is really useful for procedural generation. Now we have OpenSimplexNoise in Godot 3.1 but alone is not enough.

**Comment by CyanBlob** [comment]
I would love for Voronoi and Lloyd's Relaxation to be native to the engine! They're crucial to an upcoming project of mine and implementing them seems like a huge pain. If I get a good grasp of the algorithms I'll start working on adding them to the engine! I only personally care about the 2d implementation, but if it seems easy to extend to higher dimensions I can give that a go as well

**Comment by Ashafix** [comment]
@CyanBlob I implemented qHull in Godot but didn't find the time to really finish it. Feel free to check my Godot and send me an email if you want to collaborate on it.

**Comment by Wapit1** [comment]
@Ashafix how is the feature going ? I would love to use it in my VR game :)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
