### ISSUE TITLE
Z fighting when you have 2D character on top of a plane.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#19126]
As you can see here:
https://twitter.com/ca3games/status/999311196271599616
https://twitter.com/ca3games/status/997844799855132673
https://twitter.com/ca3games/status/999329780494471169

Whenever I make a 2D character and try to move it on top of a ground plane, sometimes the character dissapears under the ground plane.
Also happens with a Sprytile plane (collada mesh) that gets under the ground plane.

Not sure if that happens because the character and fence planes have transparent textures.

**Comment by CptPotato** [comment]
This doesn't look like a problem with the engine itself but more like the "usual" z fighting artifacts you get when using transparent objects that are close together. In your case the origin of the character gets farther away from the camera than the plane, changing it's sorting order because they are both transparent and the sorting order for transparent objects is back to front.

To my knowledge there's no way to make these work from every perspective. There might be a way to manually sort objects in Godot but I haven't done that yet.

In most cases devs resort to using 1 bit alpha which does not have these problems.

**Comment by ca3games** [comment]
Is there any alternative or work around I can use to have 2D sprites as characters in a 3D scene?

**Comment by Zireael07** [comment]
Alpha scissor checkbox does wonders :)

**Comment by ca3games** [comment]
I already solved it by setting the depth draw mode to depth press pass.

Thanks.
