### ISSUE TITLE
Stack multiple terminal outputs into one entry with count 

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#19121]
Right now if you print out the same message multiple times in a sequence - godot will print out the same line multiple times - easily leading to output overflow and making it harder to find printouts

A solution that many other consoles share to this problem is to stack a sequence of the same message into one line and simply show with a number how many times it has been emited:
![firefox-error-console](https://user-images.githubusercontent.com/6495061/40423876-c1522fca-5e8b-11e8-8225-faf831fcd64e.png)

It would be very helpful - especially for anything emited from an update function or multiple instances of a node and would greatly reduce printout noise

**Comment by PonasKovas** [comment]
My project could really use this, as we're using Godot on our server side, and quite often the logs get flooded so much, that they become tens of gigabytes big, which is completely unacceptable.

If nothing is done about this anytime soon, we will be left no choice but to use something else for the server...

Don't take this as a threat :grin: , but seriously, I don't think this issue is getting the attention it's supposed to get.

**Comment by Calinou** [comment]
@PonasKovas Couldn't this be solved by implementing a custom logger in GDScript on the server-side?

Since we're talking about dedicated servers, you could even output log in a JSON format to parse it in third-party software like [Loki](https://github.com/grafana/loki).

**Comment by PonasKovas** [comment]
@Calinou Most of the time, the built-in errors printed by Godot are the ones that flood everything. And we still want to see those errors, because of debugging, so redirecting the to `/dev/null` won't work for us.

**Comment by Calinou** [comment]
@PonasKovas I don't really see how message stacking can be achieved in a pure command-line fashion though. A few other solutions I can see are:

- Use a built-in timer to prevent error message spam. This could still cause useful information to be lost.
- Set up a log rotation and compression facility. This should be done by the system administrator.

**Comment by PonasKovas** [comment]
@Calinou 

> I don't really see how message stacking could be achieved in a pure command-line fashion though

I think this can be achieved with carriage returns. AFAIK they should work on Windows too.

Basically don't add newlines at the end of outputs, and if something is about to be printed more than once, just add a carriage return `\r` at the beginning and the count at the end.
If it's being printed only once, add a newline at the beginning instead of a carriage return.

These are just my thoughts, there might be better solutions.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
