### ISSUE TITLE
Crappy PhysicsBody2D + ParallaxBackground/Camera2D behaviour. 

### ISSUE THREAD

**Issue by jkb0o** [godotengine/godot#19142]
**Godot version:**

3.0.2 stable & fresh build from master (aee8d26)

**OS/device including version:**

MacOS 10.13.3

**Issue description:**

Crappy PhysicsBody2D behaviour (RigidBody2D/StaticBody2D + PinJoint2D) if they are child of ParallaxBackground/ParallaxLayer with Camera2D. 

**Steps to reproduce:**
Open test project, run it, drag screen with mouse.
Also setting start camera position other then 0,0 ( 500,0 for example) also reproduce this bug.

**Minimal reproduction project:**

[parallax_physics.zip](https://github.com/godotengine/godot/files/2035692/parallax_physics.zip)

**Comment by Calinou** [comment]
@jkb0o Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
