### ISSUE TITLE
An option to use XInput controllers under DirectInput to allow more than 4 XInput controllers.

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#19173]
**Godot version:**
Any

**OS/device including version:**
Windows

**Issue description:**
I'm developing a game that supports up to 8 players on a shared screen. One of our testers tried to use 8 XBox360 controllers, but could only use 4 because of XInput limitations. This limit could be lifted if there was an option to use XInput controllers under DirectInput. He also suggested a possible solution, so let me quote:

> https://github.com/godotengine/godot/blob/master/platform/windows/joypad.h
> 
> It stores a separate array for XInput controllers and directinput controllers.
> #define XUSER_MAX_COUNT 4
> ...
> xinput_gamepad x_joypads[XUSER_MAX_COUNT];
> ...
> 
> When setting up the directinput joypads it skips the XInput ones since they are handled separately via the XInput API:
> BOOL CALLBACK JoypadWindows::enumCallback(const DIDEVICEINSTANCE *p_instance, void *p_context) {
> 
> JoypadWindows *self = (JoypadWindows *)p_context;
> if (self->is_xinput_device(&p_instance->guidProduct)) {
> return DIENUM_CONTINUE;
> }
> self->setup_dinput_joypad(p_instance);
> return DIENUM_CONTINUE;
> }
> 
> So if they could add a setting to disable XInput and at the same time remove the filtering shown above, XInput gamepads could work under direct input.

> They seem to be borrowing some gamepad configs from SDL. The latest configs contain entries for XInput controllers under DirectInput so if they're using that it should simply work.

**Comment by akien-mga** [comment]
CC @Hinsbart

**Comment by Hinsbart** [comment]
IIRC XInput Gamepads have some limitations when used with DirectInput, e.g. both triggers will use the same axis. So in order for XInput pads to be fully usable with DInput, #8368 would need to be implemented first.

Also, how about instead of adding an option to disable XInput, we simply do this:
After the 4 xinput slots are used, initialize each additional xinput device with DirectInput instead.

**Comment by ProbDenis** [comment]
Yes, that's probably the best solution, using DirectInput as a fallback for any XInput devices that exceed the limit of four.

**Comment by supersmo** [comment]
> Also, how about instead of adding an option to disable XInput, we simply do this:
> After the 4 xinput slots are used, initialize each additional xinput device with DirectInput instead.

A problem this approach will run into is that there is no guarantee that the order of enumeration is the same for DirectInput and XInput and you can't get controller ID:s from XInput so you would need to do some input data correlation to figure out which controllers to filter out on the DirectInput side. 

A fix that deals with this correlation (using RawInput instead of DirectInput) is in the works for SDL: https://bugzilla.libsdl.org/show_bug.cgi?id=4477

So if Godot uses SDL for input it can benefit from the fix if it makes it all the way to the main branch.

**Comment by Calinou** [comment]
@supersmo There are no plans to use SDL, see #16470.

**Comment by supersmo** [comment]
Ah OK. 🙂 
I saw some SDL references in the code and also SDL controller bindings so I guessed it was using SDL somehow.
In case someone wants to pursue the more advanced approach of using correlation, here are some more references:
[Jimbly's SDL fork](https://github.com/Jimbly/SDL)
[Discussion on SDL forum](https://discourse.libsdl.org/t/supporting-more-than-4-xinput-capable-devices-on-windows-rfc/25666)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
