### ISSUE TITLE
Proposal: Limit minimal roughness

### ISSUE THREAD

**Issue by CptPotato** [godotengine/godot#19175]
Godot version: **3.0.2**

In the current implementation of physically based rendering (PBR) the **roughness value is allowed to go very low**, causing **extreme flickering of the specular highlights** when moving. Because of the normalization that's used in the specular calculations (energy conservation) you get tiny highlights with an insane brightness that are prone to aliasing.
This sometimes even results in black artifacts (I assume the values go out of range and bleed into a black halo due to the bloom/glow blurring).

Here's a screenshot of how extreme the differences can be:
![flicker.png](https://user-images.githubusercontent.com/3957610/40574398-6e37fdd6-60d1-11e8-8471-2864df394b53.png)

**Reproduce:** Take the [materials demo](https://godotengine.org/asset-library/asset/123) and enable "Glow" in the enviroment node. Then look at the second material "mirror" while moving. You might have to adjust the settings a bit more to get as extreme results as me but it should definitely be visible.

While it's a special case (roughness = 0), this produces too extreme artifacts / flickering in my opinion. Engines usually limit the roughness to a value that's low enough to still allow shiny surfaces while reducing the flickering to a minimum.

**Possible solution:** Increase the minimum roughness limit (if there alredy is one) or add one.
A limit which is adjustable from the editor if needed would be an alternative to hardcoding it.

**Comment by bladesero** [comment]
Yeah, it should add a minimum roughness limit or add an Anti-Flicker option for Glow.

**Comment by homer666** [comment]
A roughness of 1 causes major graphical glitches when the specular mode is set to Phong:

GLES3:
![image](https://user-images.githubusercontent.com/27100585/44746646-4fd5a380-ab4e-11e8-8741-2f876f560704.png)

GLES2 (all materials have Phong specular mode):
![image](https://user-images.githubusercontent.com/27100585/44746670-5fed8300-ab4e-11e8-81b9-32eb34b99893.png)

I'm just relaying info from #21513 here, since they both are a result of extreme roughness values being set. Maybe this issue should be renamed to "Limit extreme roughness values" or something, to better accommodate this (so I can close the other one as a duplicate.)

**Comment by Calinou** [comment]
This should be fixed in Godot 3.2, closing. Note that Godot 4.0 also features an optional screen-space roughness limiter to decrease the amount of visible specular aliasing.
