### ISSUE TITLE
Blender-like design for Editor

### ISSUE THREAD

**Issue by Timofffee** [godotengine/godot#19186]
I don't know English very well, so I'll ask briefly.
Why don't you want to make a Blender-like design for the editor? 
Plugin developers will be given more freedom, ordinary developers will be able to customize their workspaces.

I made 2 sketches in a graphics editor. They are not very good and have some shortcomings, but the General idea should be conveyed. 
![sprite-0004](https://user-images.githubusercontent.com/5556081/40580017-5344e4a4-613e-11e8-8304-f5a270dd9f11.png)
![sprite-0005](https://user-images.githubusercontent.com/5556081/40580018-536ca4b2-613e-11e8-884c-46b4701743b6.png)

I am sure that it is quite easy to implement in reality.

_P.S.: Or at least make more subtle forms of the current design. It is painful to look at the window in which 10% of the area is empty._

**Comment by mhilbrunner** [comment]
>I am sure that it is quite easy to implement in reality.

Submit a PR then.

**Comment by Timofffee** [comment]
I really don't like working with C++.
The implementation itself is simple but extremely extensive. 
I will try to collect as much information as possible during this month and try to implement it all in GDScript... It would be a shame if my efforts are called useless functionality.

**Comment by Omicron666** [comment]
When I read Blender-like UI/UX, I immediately think about a cockpit !

**Comment by Web-eWorks** [comment]
The phrase 'blender-like interface' has little-to-no objective meaning without explanation (especially now, when Blender's interface is undergoing massive changes), and thus means a different thing to every different person.

Please explain, in detail, what exactly you are proposing. Your mockups look interesting, but without text to explain your proposed changes, they are little more than pretty pictures.

> I will try to collect as much information as possible during this month and try to implement it all in GDScript... It would be a shame if my efforts are called useless functionality.

Explain your proposal, get feedback, talk with the community, _work with others_. If you do that, your efforts will ultimately not be for nought. If you charge full steam ahead, alone, _especially_ on such a controversial feature as the entire editor's UI/UX, you are likely to wind up with the 'useless functionality' you speak of.

**Comment by vnen** [comment]
Blender is not known for a friendly UI, it's probably the worst idea to copy from them. But first, take a look a this [FAQ entry](http://docs.godotengine.org/en/3.0/about/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think).

So, "doing like Blender" is not a productive description. You might like it because you use Blender a lot, but in my inexperience with it I always feel lost. Instead, you should point out:

1. The aspects of the current UI that hinders your workflow.
2. What changes do you need to improve specific tasks.

For instance, while the second screenshot show a lot of space *filled*, it does not look *useful* to me. There's too much unrelated information together. Also, Godot has a lot of contextual editors, and things show and hide automatically depending on what you selected. I don't know if putting all together and letting you manage manually is an improvement.

**Comment by reduz** [comment]
> Why don't you want to make a Blender-like design for the editor?

Blender like UI is a pain in the ass. Godot works context based, so you don't really need to have many editors open. With the upcoming improvements in the inspector, context based works even better.

**Comment by swarnimarun** [comment]
I have used blender extensively and still I hate it. I used it for various things from motion design to asset creation.

So where are you coming from is  a mystery to me.

Probably you and more flexible UI that can be dragged and dropped. And the external windows to be a part of Godot as well if so I support that. But anything else will only undermine Godot's UI.

Currently Godot is the most user friendly FOSS tool on the planet. So please reconsider.

**Comment by Timofffee** [comment]
I'm only offering a way to group areas where I can stretch a single panel to full screen, add an unlimited number of duplicates to a single column... and so on.

I have some thoughts on this, but I should think more. 

I don't encourage you to use hotkeys because they work via ass off in Godot.  
I will spend more time adapting this interface to the features of Godot.

Thanks for the criticism and advice.

**Comment by naturbua** [comment]
Even if Blender's UI is currently quite messy, I would still love to see these functions (gif) in Godot since they really improve the workflow and help to keep overview.
![ask for](https://user-images.githubusercontent.com/33326746/40586637-17dd0b58-61c5-11e8-94e6-07d51f6c819e.gif)

**Comment by mhilbrunner** [comment]
@naturbua Thats a good example of way more specific suggestions. Thank you :)

**Comment by swarnimarun** [comment]
@naturbua Yeah that's not there in Godot but that's cause Godot is young and it is still improving. 
And remember doing more things doesn't always make you awesome.
Cause if that was the case there won't a a theme/interface overhaul of Blender in 2.8.

And if it's so show me this,
![new_inspector](https://user-images.githubusercontent.com/19930870/40587058-032d3bb0-61e8-11e8-84c7-c6fe43a4acef.gif)

Please don't try to a point that was never there. People use Godot cause it has a nice UI and if you disagree then why are you using it there are other free game engines.

And the point that can always be proved is Blender is hated for is UI and UX. And that's the reason it's still not the market leader even though it has all the features that would make an awesome tool.

Let's not make Github a gif war-ground.

**Comment by naturbua** [comment]
I just wanted to ask for this specific feature. Sorry but you completely missed my point. I never defendet Blender`s overall UI and I am well aware of the changes comming to it in 2.8

**Comment by Calinou** [comment]
PS: Remember to open one proposal per feature requested. Don't lump unrelated things together :slightly_smiling_face: 

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
