### ISSUE TITLE
Add a way to change font size in editor without having to import a font

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#1919]
It would be easier to have an editor setting to change font size, without having to import your own font.

**Comment by reduz** [comment]
maybe for 2.1 when we add variable sized fonts.

**Comment by razvanc87** [comment]
I'm quite surprised font size can't be changed actually. I thought this is such a basic feature and am also surprised that the engine survived this long without it :d

**Comment by razvanc-r** [comment]
Just found this: http://ftgl.sourceforge.net/docs/html/. Might help if you guys already didn't know about it...

**Comment by OvermindDL1** [comment]
Doesn't Godot support SDF (Signed Distance Field Fonts)?  Why not just use
those instead of pre-baked ones as SDF's can be scaled without re-rendering
to a texture, that way you can save texture memory for fonts by only using
SDF's and you are then able to scale without issue.  Any font artifacts can
be fixed on the SDF itself overtime if anyone notices any.

**Comment by spookdogg** [comment]
I seriously think we should keep bitmap fonts, why not just use the same pixel scaling we use for sprites?
(not saying we should remove sdf either, just saying it would be easier and less resource intensive than replacing bitmap fonts)

**Comment by neikeq** [comment]
Dynamic fonts was introduced in the 2.1 master branch. The editor is not yet using it, but we are one step closer.

**Comment by neikeq** [comment]
Implemented by 3e8eb39 :tada:

**Comment by chris13524** [comment]
I don't understand, how are we suppose to change front sizes now?

**Comment by hasahmed** [comment]
same ^

**Comment by hasahmed** [comment]
@chris13524 on the text label's inspector you can go to rect and change the scale.

**Comment by Aimarekin** [comment]
I'm thinking of not using godot just because it doesn't have support for changing text size. It's such a basic feature and I can't develop without it.

**Comment by Calinou** [comment]
@Aimarekin It is already possible to change font sizes in DynamicFont (you will need one resource per font size, but it's possible to generate them programmatically if you wish).

Note that DynamicFonts can beautomatically oversampled when resizing the window in when using the [`2d` stretch mode](http://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html). This has to be enabled in the Project Settings in 3.0.x, but it will be enabled by default starting from 3.1.

**Comment by nucky9** [comment]
I might be misunderstanding what is being asked about, but what I do is make and save one font resource for each font.ttf file I have. Then, I drag that font into the 'custom font' box of a label. Then, I click the 'Font Data' dropdown, and I 'make unique' that font. Finally, I edit the font, and it will only change for that specific label, rather than changing all the labels that are using that font.tres file.

**Comment by PonySchreck** [comment]
@nucky9 thx for explaining! helped me a lot!  👍 had the same problem xD
