### ISSUE TITLE
Importing from Collada file with shape keys creates a horror game asset

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19195]
**Godot version:**
`master` / 430d84769

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
If I import a Collada(*.dae) file which was created with Godot's Better Collada addon, it will create an instant horror game ready asset when it contains shape keys:

 * https://youtu.be/xrBl6goVQW4

When viewed inside the editor:
![unidentified creature](https://user-images.githubusercontent.com/2367032/40582972-2bc81942-61bf-11e8-954f-9952d6c2362d.png)

Assuming from its physiology, it seems that the creature is of a different species that I found in #16994.

**Steps to reproduce:**
The source material which reproduces the issue is available from the below link, but because of godotengine/collada-exporter#41, you'll need to delete most of the shape keys to avoid a freeze when you export it:

 * https://github.com/mysticfall/AlleyCat/blob/master/Design/Blender/Characters/Human/Female/Body.blend

I checked _'Shape Keys`_ when I export it from Blender, and imported it to Godot with saving meshes separately / no animation settings.

**Comment by mysticfall** [comment]
In my case, I have the warning message as mentioned in #12618, but not the error. I tested again with triangulation applied to the mesh by different methods, and applying triangulation to all faces didn't make any change while using a modifier produced the 'out of size' error.

I could eliminate the warning by checking the triangulation option from the exporter panel, but it just broke the mesh in a different way (as probably mentioned by another issue: godotengine/collada-exporter#69).

**Comment by glaforte** [comment]
I took the Blender file from the link, exported it with the current version of the "Godot's Better Collada" add-on for Blender. I imported it in Godot 3.1 alpha 2. I got the following state:

![image](https://user-images.githubusercontent.com/2227491/48961433-75522d80-ef42-11e8-8d94-4df9ca687a10.png)

This is a difficult issue because of the size of the model! Since the 'current state' of the issue is different than the reporter's, I'll build the old revision marked above - try to reproduce the issue there. Also, I'll investigate why the head mesh is partially visible on the current 'master' branch of Godot.

**Comment by glaforte** [comment]
I built the revision 430d847 of Godot and reproduced the 'current state' of the issue. I checked the 'Godot's Better Collada' add-on code: there's been no relevant changes since May 2018. I checked the reporter's git-hub and the linked Blender file did [change in September 2018](https://github.com/mysticfall/AlleyCat/commit/a0675ae4ef8317b8c4a8e5e36a3e9b7ea2ec7f06#diff-eab2fbc9398a90481b876ac5e42daf29), so that safely explains the difference between the 'reported state' and the 'current state'.

**Comment by glaforte** [comment]
The head mesh is not visible because its base mesh is discarded during the import process.
It is discarded because its morph targets have differing vertex counts after their import.
The COLLADA document is coherent, though.
The different vertex counts in the morph targets come from the Godot COLLADA importer.
The Godot COLLADA importer calls 'SurfaceTool::generate_tangents' for all the morph target meshes.
This function does a lot more than generate tangents, it also matches identical vertices, greatly reducing the total vertex count.

Unfortunately, some of the head's vertices degenerate in only one/some morph targets.
The 'SurfaceTool::generate_tangents' function therefore optimizes the morph target meshes differently.
I tracked it down to the 'mikktspace' library, where the function 'MergeVertsFast' uses the position/normal/tex-coord values to match vertices.

In the past, to fix this kind of issues, I used the indices of the COLLADA polygons to generate the unique vertices, rather than the values. That does not optimize as much, but it keeps the morph target support intact. I'm not keen on making this change within a third-party library and I'm a bit too deep for having just started contributing to this project.

What I can do to finish helping on this issue is to create a new, simpler asset to reproduce the issue...

**Comment by glaforte** [comment]
In this simple data set: the 'PyramidFine' COLLADA document has only the Base and the 1st blend shape, where no degeneration occurs. The 'PyramidDegeneration' COLLADA document has two more blend shapes where 2 vertices approach each other closely, at different distances. 

When the 'PyramidDegeneration' is imported in Godot, the blend shapes just don't work.

**Comment by mysticfall** [comment]
@glaforte I don't have much to add to this issue, since I now use Blender exporter and the problem doesn't exist any more.

But I'm pretty sure there would be people who need to use blend shapes with COLLADA and I know how difficult to track down this type of issues. I just wanted to say thanks to you hard work so, thanks and hope you to get to the bottom of the problem soon! :+1:

**Comment by glaforte** [comment]
@mysticfall Thanks for encouragement! I'll review my assumptions and assertions, this morning. I think there might be something that escapes me still :)

**Comment by glaforte** [comment]
When checking the export option for the "tangent arrays" export option in Godot's Better Collada' export, in Blender, the issue does not occur.

**Comment by glaforte** [comment]
Wrote a fix that removes the 'de-index' and 're-index' steps in the 'SurfaceTool::generate_tangents' function. The callbacks for the 'mikktspace' library are capable of working with the indexed data..
