### ISSUE TITLE
Can't build for Android on Windows 10

### ISSUE THREAD

**Issue by CesarNoll** [godotengine/godot#19211]
Greetings! I'm trying to build Godot for Android using Windows 10, but I get the following problem:

```
MSVC not detected (no VCINSTALLDIR environment variable), attempting MinGW.
Building for Android (armv7) (with NEON)
Could not read source prop file '"C:\Developement\android-ndk-r16b"\source.properties'
Using NDK deprecated headers
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling shared ==> platform\android\os_android.cpp
scons: *** [platform\android\os_android.os] O sistema não pode encontrar o arquivo especificado
scons: building terminated because of errors.
```

"O sistema não pode encontrar o arquivo especificado" simply means it cannot find the file. Is there any solution for this? I'm trying to build Godot 3.0.2 and using CMD as admin.

**Comment by austinirvine** [comment]
having same issue

**Comment by akien-mga** [comment]
What command are you using to build, with what NDK version and is the issue 100% reproducible?

**Comment by austinirvine** [comment]
On Windows 10, using an linux subsystem with an Ubuntu shell for bash. Godot 3.0.5-stable Directory

I'm using this command: `scons platform=android target=release` and I'm running the latest NDK version of 17.1.4828580, which is located in the C:/Android/sdk/ndk-bundle/  file. Should I downgrade to version 16 or lower?

I don't have my exact output right now, but I am getting this as part of my output (from what I can recall):
```
Could not read source prop file '"C:\Android\sdk\ndk-bundle\source.properties'
Using NDK deprecated headers
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling shared ==> platform\android\os_android.cpp
-sh C:/Android/sdk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: No such file or directory
```
then it gives a scons error code 127.

The same thing happens each time I attempt to run it on my laptop, but I am going to test it on my desktop tonight unless it can be solved otherwise.

**Comment by austinirvine** [comment]
Added the Linux NDK directory and it is still not working. 

These are the steps I took and the output I got:
`austin@Frank:/mnt/c/Users/Wave Rider/Desktop/godot-3.0.5-stable$ export ANDROID_HOME=C:/Android/sdk
austin@Frank:/mnt/c/Users/Wave Rider/Desktop/godot-3.0.5-stable$ export ANDROID_NDK_ROOT=C:/android-ndk-r17b
austin@Frank:/mnt/c/Users/Wave Rider/Desktop/godot-3.0.5-stable$ scons platform=android target=release
scons: Reading SConscript files ...
Building for Android (armv7) (with NEON)
Could not read source prop file 'C:/android-ndk-r17b/source.properties'
Using NDK deprecated headers
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling shared ==> platform/android/os_android.cpp
sh: 1: C:/android-ndk-r17b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++: not found
scons: *** [platform/android/os_android.os] Error 127
scons: building terminated because of errors.`

**Comment by vnen** [comment]
Why you're defining the paths with `C:/`? If it's on WSL you should be using the Linux file system paths: `/mnt/c/`. That's probably why it can't find it.

**Comment by austinirvine** [comment]
@vnen Worked like a charm, thank you very much.

**Comment by slyd4r** [comment]
facing the same Issue , how can I solve that problem (on windows) ? help please !!

**Comment by idkaryan** [comment]
For anyone else who faced this problem on windows, here's how mine got solved.
I was using 32 bit NDK on a 64 bit machine. So yeah.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by m4gr3d** [comment]
Seems the original issue was resolved. Feel free to reopen if not.
