### ISSUE TITLE
Plane class enhancement suggestions.

### ISSUE THREAD

**Issue by anakimluke** [godotengine/godot#19236]
1- The constructor `Plane( float a, float b, float c, float d )
` could be removed completely. `Plane( Vector3 normal, float d )` already exists.

2- The member variables `x`, `y` and `z` could be removed as well because the vector `normal` is already exposed.

2.1- `my_plane.x` makes the code look cleaner, but I don't know if it is obvious that it is refering to the normal x, wheras `my_plane.normal.x` makes it obvious. Additionally, if both `my_plane.x` and `my_plane.normal.x` are used in the code, it might seem like they mean different things.

3- The member variable `d` could be renamed to a more descriptive `distance_to_origin`.

I'm not a user of the `Plane` class, so I don't know if these changes would affect some workflow I'm not aware of. Also, it would break backward compatibility.

This topic was originally discussed in #18747.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
