### ISSUE TITLE
Crash when calling within godot_gdnative_init

### ISSUE THREAD

**Issue by Galileo53** [godotengine/godot#19265]
**Godot version:**
Godot 3.0.2 and Godot 3.0.3rc2

**OS/device including version:**
Windows 7

**Issue description:**
I tried to compile and run a GDNative / C++ sample project, which worked well in priciple.
After that, I tried to do some debugging and added a line "Godot::print()" just **BEFORE** the "godot::Godot::gdnative_init(o);" what probably was a mistake or maybe is not allowed at all.
Anyway, inserting this line crashes Godot :

extern "C" void GDN_EXPORT godot_gdnative_init(godot_gdnative_init_options *o)   
{ 
	Godot::print("Constructor");      // <---- this crashes Godot  
	godot::Godot::gdnative_init(o);  
}  

**Steps to reproduce:**
Follow the tutorial on GitHubGist, "willnationsdev/gdnative_guide_windows64debug.md",
called "Creating a GDNative Library (Windows)" from this link:

[https://gist.github.com/willnationsdev/437eeaeea2e675c0bea53343f7ecd4cf](url)

It will work correctly. After that, insert a line "Godot::print("something"); just before Godot::gdnative_init(o);
 
**Minimal reproduction project:**

[SimpleLibrary.zip](https://github.com/godotengine/godot/files/2052661/SimpleLibrary.zip)

**Comment by akien-mga** [comment]
CC @karroffel @willnationsdev

**Comment by karroffel** [comment]
Yes, this is expected because the `Godot::gdnative_init()` function sets up pointers to the proper functions.

As an example, the C++ don't actually know how to construct a `String`, all they do is delegate the work to the Godot binary. This delegation relation is initialized with that `Godot::gdnative_init()` call.

Because of that, everything that does *not* require Godot to work will work before that call, so a simple `printf()` will work.

Since the `Godot::print()` call needs to interface with Godot (construct a `String`, then call the print method that actually prints into the *editor console*) it can only be called after the init call.

I hope that makes sense, this is not a bug, it's expected behavior.

**Comment by Galileo53** [comment]
It's O.K., I already had a suspicion that it is working that way. My intention was more to suggest some kind of "checking" before the crash occurs so that silly people like me don't fall in that pit :-)
But I also understand that this can be an enormous amount of work (checking each end every function?) which is not worth the time and effort.
