### ISSUE TITLE
Can't lock Mutex from a Thread

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#19284]
**Godot version:**
9f40a8d27008c3d8973460b07a7dda7713dabeac

**OS/device including version:**
Debian 9

**Issue description:**
I have Singleton.my_mutex, if I create a new thread in some scene and from the thread do Singleton.lock_mutex() it will not return from that function:

```
func lock_mutex():
   while my_mutex.try_lock() == ERR_BUSY:
      pass
   
   my_mutex.lock()
```

It will stay forever waiting in there... But this happens **ONLY** if called from within a thread. If called from the main thread then no problem.

If the try_lock() check is commented out, it will run no problem, but I guess that is not the point.

**Comment by Faless** [comment]
In the code you provided, you lock the mutex two times:

- when try_lock succedes you exit the while loop. At this point the mutex is locked.

- at this point, you try to lock it again, "lock" blocks until the the mutex can be locked again. Which never happens because you never call mutex.unlock.

What you are doing is conceptually the same as doing:
```
mutex.lock()
mutex.lock()
```

Which **correctly** produces a deadlock.
For more info about mutex please see: https://en.m.wikipedia.org/wiki/Mutual_exclusion
http://docs.godotengine.org/en/3.0/classes/class_mutex.html

**Comment by vicguedez** [comment]
Hello @Faless , it was not clear to me that try_lock would lock the mutex, I thought it would check if it could be locked instead of locking it.

Changed the function to:

```
func lock_mutex():
   while my_mutex.try_lock() == ERR_BUSY:
      pass

   print("mutex locked")
```
It will not print when called from within a thread, it will if called from the main thread.

**Comment by Faless** [comment]
It works perfectly fine for me. See [mutex.zip](https://github.com/godotengine/godot/files/2064491/mutex.zip)
