### ISSUE TITLE
will godot support golang ?

### ISSUE THREAD

**Issue by fastfading** [godotengine/godot#19283]
will godot support golang ?
although gdscript is simple ,  people still don't want to learn it.
It is worthless for a engine, so godot lost users.
golang is simple too , and easy to integrate new feature/externsions.
For example opencv, network protocol , new format support  etc.

there is a 3rd party to support this , however not perfect.
https://github.com/ShadowApex/godot-go

**Comment by mhilbrunner** [comment]
You can also use C# and Visual Script (and if you're experienced enough, C++) instead of GDScript. All officially supported.

There are currently no plans to officially support any languages besides those.

Additional bindings may be provided by interested third parties, such as the Go binding you linked to. These are community efforts.
