### ISSUE TITLE
possible tween memory leak?

### ISSUE THREAD

**Issue by Aarstad** [godotengine/godot#19297]
**Godot version:**
3.0.2

**OS/device including version:**
tested on windows 10 64 bit, linux ubuntu 14.04 64 bit, mac osx high sierra 64 bit

**Issue description:**
Calling tween.interpolate_property on an object in a loop will build up the memory over time.

**Steps to reproduce:**

```gdscript
func someAnimationFunc(objects, tween):
  while true:
    for object in objects:
      tween.interpolate_property(
        object,
        "rect_position",
        object.rect_position,
        Vector2(50, 50),
        1,
        Tween.TRANS_LINEAR,
        Tween.EASE_OUT
      )
    tween.start()
    for object in objects:
      yield(tween, "tween_completed")
```

Stupid and pointless example... but to get rid of the memory build up you have to do something like this:

```gdscript
# call this before appending any new interpolate_property methods!
for object in objects:
  tween.remove(object)
```

Please close if its intended behaviour. I don't see the documentation specifying that this is needed, but someone else posted in a completely unofficial forum (cant remember where) that tweens would remove themselves when completed, which is not the case.

Thanks for the great engine, guys! I really love the workflow godot has to offer!

**Comment by dragmz** [comment]
Seems to be caused by #12284 because concatenated_key does not match p_key in Tween::_remove

**Comment by gotnospirit** [comment]
Hi,
When we [call to `Tween::_remove`](https://github.com/godotengine/godot/blob/15c6adcd5b023ad75cf119f847d28cc4d8a78ed5/scene/animation/tween.cpp#L618) a `NodePath` is used as argument and, because of its the signature, the `NodePath` will be cast into a string.
At [node_path.cpp#L184](https://github.com/godotengine/godot/blob/832e2bfcd38965a01a9149d509169dd197e42f58/core/node_path.cpp#L184), we always prepend ":" and, because this `NodePath` is not absolute and its path is empty, this will result in a string starting with ":".
On the other hand, at [node_path.cpp#L222](https://github.com/godotengine/godot/blob/832e2bfcd38965a01a9149d509169dd197e42f58/core/node_path.cpp#L222), we're only adding ":" after the first pass, which results in a string that does not start with ":". Then both can't match.
The simpliest and safiest fix seems to simply use `data.concatenated_key` instead of the `NodePath` when we call `Tween::_remove`.
What do you think about that?
