### ISSUE TITLE
Javascript as scripting language

### ISSUE THREAD

**Issue by jonorozcoc** [godotengine/godot#19294]
I think it could be easier for people developing games on HTML5 to make games on Godot if it can have Javascript as programming language. It's pseudo-class oriented paradigm can help to organize programming workflow instead of learning a new language.

Thanks for you awesome work building this software.

**Comment by akien-mga** [comment]
Duplicate of #937.

The consensus hasn't changed since then, and we don't need more languages supported officially, GDScript, VisualScript, C# and C (GDNative) are enough.

We wouldn't stop anyone from implementing JS support as community bindings though, like some are doing for Nim, D, Python, C++, Rust and others.

**Comment by Ads20000** [comment]
Sure enough (still in development): https://github.com/Geequlim/ECMAScript
