### ISSUE TITLE
_input is not working in editor but in game (for tool)

### ISSUE THREAD

**Issue by MCrafterzz** [godotengine/godot#19291]
**Godot version:**
3.0.2 Stable

**Issue description:**
I created a tool script:
tool
extends Spatial

func _ready():
	set_process_input(true)
	print("START")
	pass

func _input(event):
	print("TEST 1")

The problem is that it only activates in game and not in the editor that the tool keyword should do. I may have missed something ovious as I'm new to Godot.

**Steps to reproduce:**
1. Create a spacial node
2. Attach a new script
3. Paste in my script
4. Play, it will print
5. Close the play window and you'll se that it doesn't print in the editor

**Comment by Zylann** [comment]
It probably doesn't because if it is in the scene, it will be under a viewport which is not the global editor viewport (aka the Godot window). And as such, won't receive input... (same for controls you place in the scene, they are in C++ so they can't avoid executing in editor, but they don't receive input either)

**Comment by MCrafterzz** [comment]
How do I make it a part of the global editor viewport?

**Comment by MCrafterzz** [comment]
There should be some way to do this...

**Comment by Zylann** [comment]
It should be explained on the doc for editor plugins and the EditorPlugin class. Sorry can't write much cause I'm on a phone, but for editorplugins you can override functions that are named like`forward_input`, something like that. The Godot editor is basically written like a game, so `_input` should work, except on sub-viewports like the edited scene. To make it work on such viewports you have to explicitely forward input to them but it will cause issues with other nodes (like buttons).

**Comment by MCrafterzz** [comment]
That would work but I also found other way: Using the static Input.IsMouseButtonDown(it's maybe called something different) to detect clicks.

I don't know how the backend code looks but would it be possible to get the _input method to work in the editor? As a new user it's very confusing that the tool keyword should make it work the same as in game but the input doesn't. It feels kinda buggy and wierd.

**Comment by Zylann** [comment]
Again, I think it can work. However if you use it, or if you use global Input directly in _process, be prepared to see your code run even when you don't expect (when scene isn't focused for example, or within the script editor). That's why EditorPlugin input functions exist, in order to integrate to the editor's input system.
