### ISSUE TITLE
Opus support is no longer available

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#19303]
**Godot version:**
Godot 3.0.2-stable

**Issue description:**
Godot doesn't detect and import opus files.

**Steps to reproduce:**
Add a opus file to a godot project.
https://people.xiph.org/~giles/2012/opus/ehren-paper_lights-96.opus
(http://opus-codec.org/examples/)

EDIT
> Akien: AFAIK there's no support for importing opus anymore indeed, but the opus module (well actually the compiled thirdparty lib) is still needed for webm support

> Akien: But I'd like Opus support to come back, it would just need a contributor to dig into the API and prove reduz wrong on his assumption that the new audio engine can't work properly with such a lib :p

And by proving reduz wrong, Akien is referring to #7496

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
