### ISSUE TITLE
Allow using Margins to position controls without affecting size

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#19328]
**Godot version:**
3.1 master branch

**Issue description:**
Imagine a UI where I want a left pointing button and a right pointing button. In the center will be the selected item and there is a button on the left and on the right to go to the next/previous item.

I want to position the left and right buttons so they are nicely centered and spaced equally from the left and right side.

See gif below and explanation below
![margins](https://user-images.githubusercontent.com/357737/40872067-f0105484-6671-11e8-85e2-3a1c949efe53.gif)

So I use Layout/Center Left on the left button and Layout/Center Right on the right button.
On the left button I want it to be 200 pixels from the left side, so I set the Left margin to 200. What happens is the position is updated (not immediately but that is a bug / I need to select something else and reselect it to see that the position is changed) which is what I want ... however the size.x is also changed which I don't want.

I try the same with the right button by setting the Right margin on it to -200. Here what happens is the position doesn't change at all and the size gets changed. I don't actually understand the logic of this. I try changing Right margin to -500 and -1000 and it still doesn't budge which is weird.

Godot 3.x's anchors/margins/sizes/positions is a very extensive (ie. complex) design that should be able to support every positioning requirement easily once you understand it .. however, I can't do this basic positioning without having to open up a calculator to calculate where my position would be (eg. position x = screenwidth - buttonwidth - 200) and input that into the inspector.

I know that changing margin is also sometimes used to change the size of a control. Maybe there needs to be a ui toggle to choose whether to lock the size of objects when changing the margin.

**Comment by groud** [comment]
You have a position input field in the inspector. You can use it to move a node without modifying its size.

**Comment by chanon** [comment]
Yes, that is what I meant when I said
>  however, I can't do this basic positioning without having to open up a calculator to calculate where my position would be (eg. position x = screenwidth - buttonwidth - 200) and input that into the inspector.

.... I can manually calculate the correct x position for a right margin of 200 pixels and input that into the position input field in the inspector. But since there is a right margin property already, it would make sense to be able to set that to get the desired margin. Even I'm ok that the size changes, I still can't set a right margin and have it respond as can be seen in the gif above.

**Comment by groud** [comment]
Well, at a given point we cannot provide a tool that covers all corner case situation. You already have the grid tool that can help positionning, you can activate the visual helpers that display the margins while moving the node or you can use the guides with smart snapping to do so.
Honestly, there are enough solutions to this problem. We could provide a "lock size" option or something like that but I fear this is a little bit too much (at least for now)

**Comment by chanon** [comment]
I understand. However, I'm wonder if the behavior when I set the margin to -200, -1000 and -500 in the gif above isn't a bug?

**Comment by groud** [comment]
Yeah, the fact that data is not updating right away is a bug.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
