### ISSUE TITLE
A way to "queue up" or "chain" audio streams on audio players.

### ISSUE THREAD

**Issue by PJB3005** [godotengine/godot#19347]
So I wanted to play audio files sequentially without seam. The problem is that all the audio player nodes use physics process to do stuff like firing `finished`, so it seems impossible to play audio files after each other without seam. User code doesn't run synchronized with the audio system so that's hopeless to do without hitches.

Some way to "chain" or "queue" audio streams to play sequentially immediately would be wonderful.

**Comment by CptPotato** [comment]
It's kind of specific but ani nteresting feature.

The only workaround that I see atm is using an _AudioStreamSample_ as continuous ring buffer and sampling your audio into it manually.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
