### ISSUE TITLE
Command line options for project manager should be passed to edited project

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot#19367]
Godot 3.0.2
Fedora 28,  Iris Graphics 540

If I start Godot with the -f option, the project manager comes up full-screen but when I load a project, the editor comes up simply maximized. This is exactly the opposite of what I want. I don't see an option to always bring up the editor as full-screen.

Please add an option to bring up the editor as full-screen (or have it persist the full-screen state).

**Comment by akien-mga** [comment]
I guess you're talking about the `-f` option, not `-e`?

The options passed work only for the current instance, and when you open a project in the project manager, it spawns a new instance. So to edit a project in fullscreen, you should run `godot -e -f` directly in the project's folder (or `godot -e -f --path path/to/project`).

**Comment by Barugon** [comment]
@akien-mga 
Yes, sorry, I meant the -f option. Is there any way to launch the editor from the project manager as full-screen?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
