### ISSUE TITLE
Microsoft Acquires Github - Discussion

### ISSUE THREAD

**Issue by cwook** [godotengine/godot#19364]
I'm making this topic to start a discussion on [Microsoft's recent acquisition of Github](https://blog.github.com/2018-06-04-github-microsoft/). Some things to discuss:

- What changes are being made to Github's [Terms of Service](https://help.github.com/articles/github-terms-of-service/)?
- Does this harm or hamper the Godot project in any way?
- Should the Godot community consider alternative hosting services for the git repository?

I don't answers to these questions, which is why I'm starting this topic. I'm not trying to cause unnecessary panic, I just think it's prudent to discuss the change in ownership.

Official Godot Forum discussion [here](https://godotdevelopers.org/forum/discussion/19523/microsoft-is-acquiring-github#latest)

**Comment by avril-gh** [comment]
too early to foretell

**Comment by akien-mga** [comment]
There is not much to discuss or act upon at this point to be honest, but I know several users are concerned about this so I'll try to expose my point of view.

Microsoft's acquisition of GitHub does not change anything for us today. The acquisition will not be effective until the end of this year, and when it is, nothing tells us that there would come sizable changes that would push us away from the platform.

Both [Satya Nadella](https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/) and GitHub's upcoming MS-appointed CEO [Nat Friedman](https://natfriedman.github.io/hello/) have expressed that GitHub will stay independent, developer-focused, and technology agnostic. In short, business as usual.

You are free to believe them or not, but until actual changes happen, this acquisition just means that instead of having our code and issues hosted by a privately owned startup running closed source software, it's now hosted by a privately owned tech giant running closed source software. So as far as I'm concerned nothing changes for now.

Of course there are motives to be concerned about the future of GitHub and whether Microsoft will give it the means it needs to continue improving and fulfilling our needs. But only time will tell if this will have a positive or negative outcome, and things won't change in a day.

Our code is already [mirrored on GitLab](https://gitlab.com/godotengine/godot) (and was already for more than a year), so there's no risk of an apocalypse of any sort. As a precaution, I'll also look into how we could backup our issues and PR history, ideally in a format that would allow importing it in other Git hosting solutions if need be.

So to answer the above questions directly:

> What changes are being made to Github's Terms of Service?

Today, none. Once the acquisition is effective (2019), we'll see. We'll review the changes at that time and see if we're still fine with them.

> Does this harm or hamper the Godot project in any way?

No. Actually, we have good contacts within Microsoft due to the work they funded for Mono/C# support, and the new GitHub CEO is the previous Xamarin CEO (Mono authors), so... sounds pretty positive to me so far.

> Should the Godot community consider alternative hosting services for the git repository?

For the @godotengine organization, for now we'll stick to GitHub, and mirror repositories on GitLab. I strongly encourage Godot users to explore other hosting solutions for their own projects though (including non Git-based ones, e.g. Mercurial or Fossil-based hosting), as more competition is healthy in this market (and Microsoft in particular works best when in competition - e.g. VS Code - and not when in a monopoly situation) and fosters innovation.

**Comment by aaronfranke** [comment]
I think we should look into migrating to GitLab, and explore its feasibility, in case GitHub becomes an unsuitable platform for whatever reason.

**Comment by akien-mga** [comment]
> I think we should look into migrating to GitLab, and explore its feasibility, in case GitHub becomes an unsuitable platform for whatever reason.

It takes literally 5 minutes to migrate to GitLab, it's a two-click process :)

But again, there's no need for now.

**Comment by neikeq** [comment]
![calm down](https://user-images.githubusercontent.com/7718100/40943672-45ef82f8-6852-11e8-9130-4c86c414ec90.gif)

**Comment by YeldhamDev** [comment]
@akien-mga And talking about GitLab, there's not harm in updating the repo's logo, as it still uses the old one.

**Comment by BastiaanOlij** [comment]
Just my 2 cents for whatever they are worth. Indeed, let's wait and see what happens first. I think that is the most important thing.

But look at whats behind this, this isn't just the people behind GitHub cashing out, I don't know how well they ran things but running a free Git repository of the size that GitHub became, costs a whoooooooooole lot of $$$$$$$$$. They burned through well over $350 million in VC money. That money was needed for a reason.

So what if everyone jumps ship right now before even knowing if a behemoth like MS will actually screw us over? They might not, they just might see value in supporting developers, many of which who feed back into the MS eco system by making applications, tools and games that are also made available on the windows platform. 

So we all go use the public servers of GitLab, or we all jump to Atlassian, or any of the other free alternatives that somewhere have a business behind them? How long till they crack because suddenly they need to invest in more hardware, more IT staff to maintain it, more support staff to deal with abuse (like dealing with our friendly spammer not that long ago), how long will it take for those free services to start burning through millions of investment? And how long will it take for them to be bought out by MS/Apple/Google/younameit who can afford to blow that kind of money purely for PR?

Or are we going to run our own server? Raise the costs for the Godot organisation for buying and maintaining such servers? Not to mention paying for bandwidth? We're lucky enough some have dedicated hardware for running things like the CI and spending their time maintaining it, but a GitLab instance? With 3000+ forks of the core repo, with thousands of active users pushing changes from all over the world? That might come at a price.. I can't say if that price is worth it or not.. But lets not make rash decisions here...

**Comment by MatteoJoliveau** [comment]
@abhaskumarsinha 
> they added the feature to clone GitHub repos in just a few hours of knowing that Microsoft and Github....

Please do not spread misinformation just for the sake of panic. Importing GitHub repos on GitLab has been there for a really long time. Since [GitLab 9.1](https://docs.gitlab.com/ee/administration/raketasks/github_import.html) actually.
And Godot has been mirrored on GitLab for over a year as @akien-mga stated.

Also, consider that GitLab has serious stability problems (we used it at work and had to monitor the Status Twitter account on a daily basis to check if something broke) and the massive traffic that hit them yesterday has created many service outages. I love GitLab in terms of functionalities, but it's not perfect at all.

Finally, this.
> The whole Github projects (both closed and open source) are going to be merged in Microsoft Cloud, this shows that they can peep into any closed source project's code as well as features. This might not be a problem for Godot, but for Godot Devs, who create Closed Source Games

GitHub was and still is a privately own company running its own closed source platform, with the same ability to "peep into any closed source project's code" and potentially profit on this. Yet they didn't, at least not to the public knowledge. Why should Microsoft behave differently? Just because it's Microsoft? Come on, let's grow up a bit, business has put confidential documents on OneDrive, deployed critical applications on Azure (do you know that GitLab runs mostly on Azure's infrastructure?) and shared confidential informations through Skype or Outlook.
Let's drop the tinfoil hat for once. It's not the same MS from the Halloween documents.

**Comment by swarnimarun** [comment]
I don't get the reason for anyone to be sceptical, yeah they might do this they might do that, but from the perspective of Godot, there will likely never be a major change.

I have only been using GitHub for a couple years now but still I can say this that GitLab doesn't even compare to it's reliability and popularity.
It might a little more adopted now because of some crazy scepticism but you should know that Microsoft has the resources to make the most awesome GitHub of ones dreams possible and let's hope thats what it does.

I personally don't like Microsoft but I use Windows and VS Code, I don't even like Google but I use Chrome and Android.

@abhaskumarsinha GIMP, has not moved to GitLab. For a long time now it has been self-hosted and it still is.
All they did was create a mirror with PR disabled.

And also GitLab ain't FOSS.
It might be Open-Source but Free it's not. They have a dedicated Pricing page.
https://about.gitlab.com/pricing/

**Comment by MatteoJoliveau** [comment]
@swarnimarun GitLab CE is actually free software, under [MIT license](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/LICENSE). You can make free (as in free speech) software that is actually not free of charge, even if in this case GitLab CE is also free of charge.
GitLab EE, however, which is the enterprise edition the online version is based on and the pricing refers to, is open source but not free software, since you cannot use it or redistribute it withouth a valid subscription.

**Comment by swarnimarun** [comment]
@MatteoJoliveau Thanks for the insight.

**Comment by OvermindDL1** [comment]
> GitLab EE, however, which is the enterprise edition the online version is based on and the pricing refers to, is open source but not free software

Is it open source?  At least at one point the EE modules were not available under open-source (viewing or licenses).  GitLab I don't think ever claimed to be open source, only "open core" (their terminology).

**Comment by Elmapul** [comment]
"GitHub was and still is a privately own company running its own closed source platform, with the same ability to "peep into any closed source project's code" and potentially profit on this. Yet they didn't, at least not to the public knowledge. Why should Microsoft behave differently? "

because they did it already, at least twice:
https://www.zdnet.com/article/microsoft-admits-its-gpl-violation-will-reissue-windows-7-tool-under-open-source-license/
https://www.networkworld.com/article/2236556/microsoft-subnet/microsoft-accused-of-being-in-violation-of-gpl-on-hyper-v-code.html

i dont think they will do it again, but i was just pointing something that may be missing otherwise.

" Also, consider that GitLab has serious stability problems "
i'm not a heavy user of github and i dont use GitLab, but i believe in what you said.
the FLOSS comunity sometimes ignore the facts for sheer ideology

**Comment by MatteoJoliveau** [comment]
I didn't dig fully in the source code, the repo for GitLab EE is [here](https://gitlab.com/gitlab-org/gitlab-ee/) if you wanna explore it. It's very plausible that not the full system is open source. [GitLab CE}(https://gitlab.com/gitlab-org/gitlab-ce/), however, is fully FOSS.

But we're going OT so let's stop digressing.

**Comment by MatteoJoliveau** [comment]
@Elmapul I'm not a Microsoft fan at all but I do appreciate some of their work (just pointing out before going out).
MS is surely not a saint and has done horrible things in the past, as you pointed out. But those links are about FOSS license violations, where they used hard-copyleft code inside proprietary software. NOT the other way around (stealing proprietary code to use on their own), which is what we were speculating they could do by having full access to the GitHub platform

**Comment by akien-mga** [comment]
Guys, this is not the place to speculate about what Microsoft may or may not do once they are in charge of GitHub.

For now nothing changes, we can stay alert but there's no reason to be paranoid either. They bought a for-profit startup, not the GNU project.

**Comment by lavaduderDev** [comment]
Why is this closed?

**Comment by swarnimarun** [comment]
@lavaduderDev Because it's useless to discuss this issue, any further and it's unlikely there will be any problems for Godot in the near foreseeable future.

**Comment by volzhs** [comment]
wow... a deleted user... in such a short time...

**Comment by alexwbc** [comment]
Githib flagged my account, my latest two activities are these two issue report:
https://github.com/ValveSoftware/Proton/issues/2329
And 
https://github.com/godotengine/godot/issues/25527


Since my account is flagged, you are required to login through github to be able to see (things may get fixed if they lift the flag; I will keep you updated so anyone can be watchful if there are any "mistakes" that may get you flagged too)
I am waiting to ear what's this about, but since I've migrated all my projects on gitlab already... there's very little activity I've made here (thus, less options). I've written "on gitlab" (direct link to my project page) on my profile status, and this is, I suspect, the reason that got me flagged. **IF** that's the case, this sounds to me more like a petty revenge from github: I doubt they would get that zealot if I had set my status with a Xbox live id.

Since I am on the way, I may add my point of view (to whom may concern). I saw this post earlier, but I didn't concern too much: known there was a gitlab mirror was enough for me. But now Microsoft's github dragged me, unwilling, back to this issue.
Users that get flagged have their issue report hidden: users are required to logged in to access these reports... otherwise "they simply don't exist".
While not extremely dramatic thing, it still shows the company's logic behind this apparently zealot design. It's the facebook /Pinterest  logic: "let me know who you are (login/register) and I'll shows you what's in there". Simply put is a technique of " forced fidelity". Github don't want to behave like your average phpbb forum where admin chose what's private or public: they want to be the superadmin above the loweradmin to chose who and how things can be seen.

Microsoft: there are certainly cool and brilliant people in Microsoft's office. Most of them working with fair amount of freedom and independence... but there's a simple issue some seems to forego: the company design.

Microsoft 's history is blatantly clear for those who remember. Investors don't put money in Microsoft because  like Microsoft's people... they put money in Microsoft because they know Microsoft's infamous model of business around monopolization, unfair practices, infringement of laws (see Wikipedia page about MSvsUSA) and techniques such as EEE. Investors define the design of a company. Its logic, purpose and goal.

You may read this as purely ideological/ethics rambling; but source and scope of money mean something, you may have also problems in thinking companies buy other companies because they are benefactor: Microsoft wants their money worth back. If Github was sold... it mean github's ability to make money wasn't atop.
Microsoft don't need github's know-how or their ability to make money, Microsoft wants the strategic power github had across developers. The reluctance of many rational thinkers (coder) to "stay close to Microsoft" should arise red flag.

You may like the cunning PR from Microsoft; but reality is where money are. Where Microsoft get their money. They are still active into "soft biribe" adopters of open platform like android to "protect them" from their own patents. Yes, cool people in Microsoft's lab made cool tech; nevertheless a kiss from a poisoned creature must be preemptively valued by the blatant outcome, not shown affection.

**Comment by alexwbc** [comment]
Flag was removed: it took the time to write the previous post to have thing fixed and receiving aa kindly answer from the support service. Apparently was an issue with the automated system that marked me as spam. I guess contact the support is what people need to do in this case.

Can't edit my post from mobile; anyway, I stand by my opinion still: awesome people iinside, but awful mother company's design written in Microsoft's past, present and (most) protected in company's future. What investors are paying for only matter (until something don't pierce through their investors)
