### ISSUE TITLE
Add Set signal besides changed.

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#19372]
Most controls in Godot don't emit signals when the value is set by code by calling a function, this is the case of Tree, LineEdit, TextEdit, ComboBox, ItemList, Button, CheckButton, etc.  Only Range does and this should probably be changed (but it breaks compat, forgot to do it in 3.0 :(, will do for 4.0 ). 

For most use cases, it makes sense that this does not happen, as it makes more sense that signals are only emitted based on user input, not code.

That said, in some scenarios, it MAY be useful to get a signal that is emitted when something is changed via code, and saves a good amount of work. I was thinking that, for such cases, we may add a *_set signal to controls, like:

* text_set for LineEdit and TextEdit
* value_set for Range (when we fix it in 4.0)
* item_set for ComboBox or ItemList
* frame_set for Sprite
* animation_set for animationplayer

and so on

etc. This will trigger even if changed by code. Would this be useful to most of you? If so, Anyone would like to volunteer doing it?

**Comment by silkentrance** [comment]
I guess that 4.0 will take quite some time before that it will become available and I need Range to not emit any signal on programmatic change of the value.

What about having a global engine like COMPATs configuration, where one can for example configure Range to use the old behaviour, e.g. RANGE_EMIT_SIGNAL_ON_VALUE_SET=true or not.

That way, you can stay backwards compatible and allow other users to use the new behaviour that is going to be introduced by 4.0.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
