### ISSUE TITLE
shader color value not right

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#19375]
**Godot version:** 
- 3.02 stable 
- 3.03rc

**OS/device including version:**
debian 
**Issue description:**

color set to same value ,but color is not same.

 from hint_color is correct
```c
ALBEDO = albedo.rgb ; 
```
 from value set is not corret
```c
ALBEDO = vec3(0.3,1.0,0) ;
```
that will result color set not right.

**Steps to reproduce:**

![not_hint](https://user-images.githubusercontent.com/12198203/40955400-53f6bb7c-68bc-11e8-889d-5a1e80fb2992.png)
![hint](https://user-images.githubusercontent.com/12198203/40955394-504f6bae-68bc-11e8-847c-fa0ebb23fecd.png)
![hint_set](https://user-images.githubusercontent.com/12198203/40955396-522f236a-68bc-11e8-94bf-48ba3b5edf18.png)

**Minimal reproduction project:**

[godot.zip](https://github.com/godotengine/godot/files/2070842/godot.zip)

**Comment by BastiaanOlij** [comment]
Hey ywaby,

Colors you set in the interface are sRGB.
Colors you set in the shader are linear. 
Colors output to screen are in sRGB.

Rendering has to happen in linear color space because only in linear color space 1.0 is twice as bright as 0.5, kind of important for lighting.

But colors need to be converted from linear to sRGB to look right on a monitor and are assumed to be sRGB in textures and other color inputs so they are converted from sRGB to linear before rendering.

Hence the difference in color in your tests. 
The color set in the interface is in sRGB, it gets converted to linear, then is rendered, and finally converted back to sRGB for display, hence it looks the same.
The color set in the shader is linear, it is rendered as is, then converted to sRGB for display, hence it looks a different shader of green.

https://en.wikipedia.org/wiki/SRGB

**Comment by ywaby** [comment]
@BastiaanOlij 

but that result  texture color not right 
like 
```like
ALBEDO = texture(SCREEN_TEXTURE,SCREEN_UV).rgb ;
```
or from viewport texture
```
ALBEDO = texture(refelct_tex,SCREEN_UV).rgb;
```
I don't know where not convert color.

**Comment by BastiaanOlij** [comment]
Hi ywaby,

The conversion is automatically handled by Godot. 

When you render to viewport the problem is that the color correction is already applied so if you use that as an input for a second step as you are doing with your reflection example you indeed get the wrong result. 

There is a new property on viewports called "keep_3d_linear" that will prevent this from happening but I don't think that is in 3.0, only in 3.1. You would need to tick that on the viewport in which you are rendering your reflection texture.

Note that Godot can do the reflection for you if you use a reflection probe.

**Comment by ywaby** [comment]
thanks answer.I found it in nightly build.
PS.
 I want a plane reflect effect ,  reflection probe is not suit. althoungh I know reflect camera is also suit.

**Comment by BastiaanOlij** [comment]
Only thing Godot still misses for that is the ability to specify a clipping plane. I've been wanting to add that for awhile now

**Comment by ywaby** [comment]
yes，really need this. thanks for your job.
