### ISSUE TITLE
How about expose sound effects to Theme ?

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19381]
**Issue description:**
This would be very cool if its possible to exposing simple SoundEffectPlayer for Theme, as user will be able to play sound effects when clicked on different controls and checking/unchecking buttons. Currently it must be writted through scripts and I suggest more friendly way to handle it.

**Comment by Zylann** [comment]
See https://github.com/godotengine/godot/issues/9327#issuecomment-310615528

**Comment by swarnimarun** [comment]
@Zylann I don't see a relation other than the fact that both are UI based feature requests. 
Although I understand that you might have wanted to point to the fact that Godot devs don't want extra needless features. That are better implemented through code.

I would really like some improvements to the UI like some more exposed features to be able to do things with signals automatically without having to use code.

### Here's an idea
Probably a way to call the Animation Player to play an animation on click or some-other input.
Non-code and more direct way, like a signal to the animation player that makes it play certain animation.
This will allow for all sorts of awesome abilities for the UI.

**Comment by Zylann** [comment]
@swarnimarun I linked the issue because it was about a similar issue, which indeed was rejected because devs didn't want to bloat theming. If there was a way to add functionnalities while keeping Theme working the way it does, that would be great though.

By that, I mean using AnimationPlayer and audio players isn't in line with how Themes where designed.  Theme and StyleBoxes don't depend on the scene tree. They behave like CSS sheets. That would mean that if you want a button to play a sound or animate (even with a single color tween), you would need to modify the theme, AND add AnimationPlayer and audio player nodes in the tree in every place you use that theme, which is really cumbersome and not that far away from the other code method.

So ideally, I think you would be able to optionally play tweens, animations or sounds, but not doing anything more than modify the theme.

**Comment by swarnimarun** [comment]
@Zylann I don't want the UI to have anything that makes it any different but just the ability to be able to call something more than just staying static/fixed.

And I am more towards the idea of UI/Control nodes having some ability to call animations from animation player directly which would make the whole UI much more effective and responsive.

**Comment by Zylann** [comment]
@swarnimarun all I'm saying is, the way a theme works doesn't line up with the way AnimationPlayer works, and you will end up with AnimationPlayer nodes everywhere you have a GUI node. Maybe it would work but that's crowding the tree quite a lot. I don't deny we should be able to do these things without scripting everything, I'm just trying to figure out how to do it without too much hassle or bloat (engine side and game side).

Also, there are points to solve:
Say you hover a button. It plays a scale up animation. But then you remove the mouse before the animation ends playing... what happens? play the animation in reverse? Or play the "hover off" animation?
If you do the latter, you will have a seam (the button will jump to the other animation resulting in a unwanted bumpy effect).
If you do the former, it will go back from where it was, and it will be seamless visually, but what if you placed a mouse on sound at the beginning of the animation? It will end up playing as you mouse off... so that sound might be better as a separate thing.

You also have to consider transitions between all states:
Disabled, enabled, hovered, pressed, hovered+pressed (checkboxes). That's a lot of transition animations to deal with. And given how animations work, if you do one, you have to do another for all other states otherwise your button (or part of it) will linger in a previous state.

**Comment by swarnimarun** [comment]
@Zylann Yeah a broader issue. It seems like a much bigger than just a simple addition of features.

Let propose some solutions,
Each property of UI should call a animation in a specific animaton player,  setup by the user, and if there is none then just call a base quit animation i.e. let previous animation end don't do anything or just stop the animation which could be overriden by creating a new quit animation in the animation player.

Now this should solve all basic issues, with the system. Only problem is the signals would have to call specific animations on animation player as setup by the player or by default using specified names.
So signals, if used plainly will have to know much more than just the arguments but also hold more data.

All of this is not a major problem, probably the most significant problem will be to integrate Animation Player into a proper tool for such tasks. It can likely be implemented to lots of Nodes to create automatic actions that allow for direct animation calling making many animation setups much easier, and faster.

**Comment by Calinou** [comment]
This request sounds very close to https://github.com/godotengine/godot/issues/3608.

**Comment by Chaosus** [comment]
Yeah, seems like a duplicate...
