### ISSUE TITLE
CheckBox and CheckButton ignores hover style when checked ON (pressed)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#19429]
**Godot version:**
3.0.2 and master (3d5aabe7f)

**OS/device including version:**
All.

**Issue description:**
When a CheckBox or CheckButton is checked ON, no custom style is applied.

This was mentioned initially in #8640 by @hickop and @ProbDenis, and I can confirm it:
![screenshot_20180607_221637](https://user-images.githubusercontent.com/4701338/41123879-75541590-6aa0-11e8-92a2-b5177368a9df.png)

From my tests (see attached project below), the issue seems to be that the "pressed" style has precedence on the "hover" style, so when the box/button is ticked ON (pressed), only the pressed style is applied.

I'm not sure if this should be fixed by making the "hover" style have precedence on the "pressed" style (just like it has precedence on the "normal"/unpressed style), or if there should be another "pressed + hover" style. I guess the former might be fine, but were some using this as a feature?

**Steps to reproduce:**
- Add a CheckBox or CheckButton, set `custom_styles` properties
- Tick the CheckBox/CheckButton ON, see that hovering does not override the "pressed" style (or the "focus" style if you still have focus after pressing).

**Minimal reproduction project:**
[checkbox_pressed_hover.zip](https://github.com/godotengine/godot/files/2081982/checkbox_pressed_hover.zip)

**Comment by Soaku** [comment]
In a normal button `pressed` has precedence over `hover` because they are always mixed - if it's pressed then you sure are hovering/focusing it. Checkboxes have a little different logic - a checkbox CAN be pressed but not hovered at once. So, pressed+hover would probably be the most reasonable here, assuming it will be added to checkbox and checkbutton, not to button, IMO.
