### ISSUE TITLE
Enable / disable shadows globally in GDScript

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#19440]
In continuation of themes:
https://godotengine.org/qa/29287/enable-disable-shadows-globally-for-entire-game-via-gdscript

I want to offer a small improvement for Godot. To introduce a global switch for shadows which can be switched from GDScript.

**Comment by akien-mga** [comment]
Doesn't the `rendering/quality/shadows/filter_mode` project setting disable shadows when set to "Disabled"? (genuine question, didn't check)

If so it can already be toggled from script as you can change project settings via the ProjectSettings singleton.

**Comment by DimitriyPS** [comment]
> Doesn't the rendering/quality/shadows/filter_mode project setting disable shadows when set to "Disabled"?
No, this will disable smoothing shadowing. Shadows will be with pronounced artifacts. With such artifacts, better be they were not at all.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
