### ISSUE TITLE
Using ProjectSettings.set inside a tool corrupts the project.godot file

### ISSUE THREAD

**Issue by Fasox** [godotengine/godot#19490]
**Godot version:**  3.0.2

**OS/device including version:** Windows 10 Ultimate 

**Issue description:** If you use "ProjectSettings.set" inside a tool to store an object your "project.godot" file corrupts and the project manager cannot open or parse the project again until you delete what was added by the "ProjectSettings.set".

**Steps to reproduce:** 
- Open the project example
- Activate the plugin "my_dock"
- Close the project
- Open the Project Manager

**Minimal reproduction project:**
[EditorBug.zip](https://github.com/godotengine/godot/files/2088023/EditorBug.zip)

**Comment by Calinou** [comment]
@Fasox Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
