### ISSUE TITLE
'First Person' and 'Third Person' character controller nodes

### ISSUE THREAD

**Issue by 111ukasz111** [godotengine/godot#19506]
Vehiclebody node is cool. So maybe could you add some new. Vechiclebody node speeds up developing process and makes the game less laggy than gdscript code. Many games are using fpp cam and that second. Make something like vechiclebody node but for control characters.

**Comment by QbieShay** [comment]
@111ukasz111 the team is working on a new 3rd person demo that will be available soon. Have you checked the template page when you start Godot? There are some assets there

**Comment by 111ukasz111** [comment]
3rd person controller NODE. Something like vehicle body NODE but for character controllers, not a demo.

**Comment by vnen** [comment]
We are actually thinking about *removing* the vehicle node. There are a thousand and one ways to implement character controllers, it's quite hard to make a node generic enough so it can be used by many projects.

**Comment by 111ukasz111** [comment]
Why removing? It's possible to make fpp and 3rd character controller node to be generic enough so it can be used by many projects.
Why not? Vechiclebody node works well

**Comment by vnen** [comment]
> Why removing?

Well there are many discussions about trimming the base engine (#18822, #19486, #19508). The idea is that it shouldn't be a burden for people who don't use them (in particular for mobile games, which have more restricted space).

Also, I would argue about the "VehicleBody works well" statement. It's not well documented and I've seen a few issues about problems with it.

**Comment by Ace-Dragon** [comment]
I don't think trimming the base engine would be as critical if the project exporter could automatically strip the exported runtime of code related to nodes it doesn't use (as I mentioned in another discussion). Because chances are a lot of games will not come close to using every node.

One other thing to bring up would be making the list of nodes easier to browse through, I don't think it would be as much of a problem if nodes like a character controller and the vehicle were moved to their own 'high level' category that would be done after the stripping is implemented.

**Comment by 111ukasz111** [comment]
Mobile games developers just shouldn't use this controllers. It makes a gdscript games less laggy. See here.
Without vechiclebody node https://youtu.be/EX9C3Gete_Q
With vechiclebody node.
https://youtu.be/uf5E1ztOWNo

**Comment by Zireael07** [comment]
@111ukasz111: mate, both of those use vehiclebody node. The difference between the videos is, one is Godot 2 (truck town demo) and the other is Godot 3.

**Comment by kubecz3k** [comment]
When we are moving about removing vehicle node, we are talking about moving it outside of the core as an official plugin. This will not happen for some time since plugin api and market need some polish. At that time many more 'official' nodes should be available via this official plugin section of the store.

**Comment by 111ukasz111** [comment]
I am sorry, my fault Zireael07.

**Comment by Calinou** [comment]
I'll close this due to lack of support (see the comments above).
