### ISSUE TITLE
Add offset centered option to Control nodes

### ISSUE THREAD

**Issue by alkhimey** [godotengine/godot#19529]
This is a feature request.

I would like to place Control (and actually any CanvasItem) node in a way that makes the center of the node to be at (0,0) and the node, if stretched will keep this center.

Sprite nodes has the centered property which does exactly this.
While it is possible to implement in script, It would be really helpful if other nodes could have this as a property.

**Offset Centered enables:**
![offset_centered](https://user-images.githubusercontent.com/652603/41307817-e50f4068-6e82-11e8-8b82-e2d4b9ea6ad3.png)

**Offset Centered disabled:**
![offset_centered_off](https://user-images.githubusercontent.com/652603/41307911-272ed030-6e83-11e8-9299-5564174f53f7.png)

**Control Node has no such option:**
![control_node](https://user-images.githubusercontent.com/652603/41307869-0b3488ac-6e83-11e8-8ae2-19368b27d3bf.png)

QA question regarding this: https://godotengine.org/qa/24127/sprites-option-centered-collisionshape2d-forced-centered

**Comment by kubecz3k** [comment]
Regarding controls, there is `pivot_offset` property inside rect, that when set to half of the rect size will behave exactly like centered in `Sprite`. 
That said, I think there could be a checkbox to automatically fill offset value with the way control would be centered, since I'm almost always ending in setting this value from script in ready (ofset = size/2) because of how easy it's to forget correcting the `offset` value after changing control size.

**Comment by alkhimey** [comment]
@kubecz3k  That would be great!

Regarding `pivot_offset`, see the third screen-shot, I set the pivot offset to (17.5, 9) which is half of size and the Control did not change it's position. Only the little "+" indicator changed to the center of the Control.

**Comment by kubecz3k** [comment]
@alkhimey yes, the pivot_offset works as offset during rotation and scaling, which is very helpful when animating UI. However, maybe such full 'centered' option is possible to implement not sure, but I imagine it could be quite a hassle since many control elements are positioned by other controls in hierarchy.. in such case I'm not sure if this really is `junior job`

**Comment by Jose-Moreno** [comment]
@alkhimey @kubecz3k Hi, I was just testing Godot today and I agree with the last point made by alkhimey I was trying out a simple button node, and when I used the pivot offset I noticed that the position property continues to work off the top-left corner of the node instead of the offset pivot as it should (and as other engines do). 

I'm not necessarily in favor of the "centered" checkbox though, because I consider that it would be more coherent to have the canvas items / control nodes transforms to be relative to their offset pivot. So for example in this particular case if you put the pivot offset with a rect_size/2 value (i.e in the center of the node) every transform should work relative to that pivot, not only rotation and scale.

**Comment by girng** [comment]
developer can use `rect_pivot_offset` in gdscript as kubecz3k mentioned
also, can just position it in the center.
this is normal because sometimes, when that text changes, it's good to re-update its position so it's center again

this functionality already exists in godot i think

**Comment by aaronfranke** [comment]
I don't understand what is being proposed here that is not already possible. What is missing that you can't do with setting the position to zero and setting the anchor values to 0.5?

**Comment by alkhimey** [comment]
@aaronfranke Of course it is also possible to calculate the desired position manually, but what will happen when the control is resized? It will be required to update the position again.
I just what the point of reference to be the center of the control rather than the corner.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/129, as feature proposals are now tracked on the Godot proposals repository.
