### ISSUE TITLE
Displaying the properties of a keyframe

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#19521]
**Displaying the properties of a keyframe:**

The keyframe properties has been moved from the animation timeline to the Inspector, this is counter productive.
Most of the time when making an animation you are working with multiple values for multiple nodes and this change just makes that process more difficult, more time consuming and ultimately more irritating. You are now required to constantly click back and forth between your keyframes and scene nodes to display the properties of one or the other. Before this change you were able to see both at the same time. 

**Please move the keyframe properties back to the animation timeline.**

**Current workflow (Godot 3.0.2)**
![timeline-03_1](https://user-images.githubusercontent.com/15687516/41280020-3d499bca-6e2e-11e8-8e32-7a56b164b076.jpg)

**New Workflow (Godot 76875ba).**
![timeline-03_2](https://user-images.githubusercontent.com/15687516/41284758-83ec5e94-6e3a-11e8-9477-5ffc5a24dac9.jpg)

**Godot version:**

76875ba

**Comment by kubecz3k** [comment]
I personally like the new way of editing keyframed properties much much more.
Old way for me was very frustrating since the area in which it was possible to edit property was very small and often all the UI was not fitting there. I think the new contextual approach is a lot better: keyframe properties are visible in inspector tab but only when keyframe is selected, when its loosing focus its no longer visible:
![anim_keyframe](https://user-images.githubusercontent.com/6129594/41287979-f79f1caa-6e44-11e8-980c-fc528a8671c9.gif)
I think however that some improvements should be made, currently when keyframe focus is lost by neglecting it (clicking in empty space) the inspector area is rendered as blank, it would be a lot better if instead previous state of inspector could be recreated (node properties):
![keyframe_empty_inspector](https://user-images.githubusercontent.com/6129594/41288123-83b516f4-6e45-11e8-9cd7-bfa9901344ce.gif)
_empty inspector sometimes can force user to 'reclick' his lastly selected node_

**Comment by PullTheStrings** [comment]
I don't agree. Having the keyframe properties in its own window was and is a better solution. Granted the window is too small and the Key/Transition properties need not be split up into two tabs. 
I have included a mockup of how I believe it should look.

![windowopen](https://user-images.githubusercontent.com/15687516/41523205-5be9bf2e-72d9-11e8-8cf2-c4419cca6670.png)

![windowclosed](https://user-images.githubusercontent.com/15687516/41523215-64296608-72d9-11e8-9034-4621ab1955c8.png)

**Comment by Keetz** [comment]
I agree with @PullTheStrings 
First of all I don't have my inspector right next to the animation window, so the information is split very far apart, which is very annoying to me.

Second, my inspector is for displaying properties of a node and its resources, now all of a sudden they disappear and are displaying some other information.

I think it would be better to keep it together with the animation dock.

**Comment by jesperkondrup** [comment]
I agree with PullTheStrings, I don't like the idea that the inspector "changes" into something else. 
In Blender/Unity/3dsmax you would not suddenly have the hierarchy view changing into the animation curve editor view - there is a separate view for that.

**Comment by reduz** [comment]
Apologies, but I won't revert this change. In Godot 3.1, there are plenty of things you can select in the bottom dock that are automatically edited in the inspector such as:

* Visual Shader Nodes
* Blend Tree Nodes
* Blend Space 2D Points
* Blend Space 1D Points
* State Transitions
* Visual Script Nodes
* Audio Bus Effects
* Tilemaps

Animation keyframes is just one more of them. These changes make the editor entirely more coherent.
If somehow this breaks your workflow, let's find a way to make it easier but this will not be reverted.
