### ISSUE TITLE
EditorSpatialGizmo.cs failed - Build project with C# script is impossible - regression

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#19543]
**Godot version:**
ea5512f

**OS/device including version:**
Windows10

**Issue description:**
Try attach c# script and build - you see the error.

**Minimal reproduction project:**
No need - its very simple to reproduce

**Comment by Chaosus** [comment]
I think its regression from - https://github.com/godotengine/godot/pull/19487 
CC @JFonS

**Comment by akien-mga** [comment]
Likely an issue with the doc XML, IIRC Mono still relies on those to generate its classes...

**Comment by akien-mga** [comment]
@JFonS The issue is that you changed the signature of `EditorSpatialGizmo::add_collision_triangles`, but you did not change the bindings in `_bind_methods` accordingly: https://github.com/godotengine/godot/pull/19487/commits/9cd1c20f6aae87e34b45471271062127d385871e#diff-891e37e69eea9a06bd2b0951987a82caR220

**Comment by akien-mga** [comment]
Ah, the issue is likely the buggy DEFVAL added to `add_unscaled_billboard`.

**Comment by JFonS** [comment]
Totally right, I added a new paramater with default value but then changed my mind and removed it. I forgot to remove the DEFVAL. I guess I should make a new PR with the fix?
