### ISSUE TITLE
blend_rect() doesn't draw partially off the map if negative

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#19578]
I was using blend_rect() today and noticed a problem.  
`blend_rect ( Image src, Rect2 src_rect, Vector2 dst )`
<p>
1.  If I pass a "dst" Vector2 where either x or y are negative, the x or y gets clamped to zero and a strange clipping occurs.   </p>
<p>
2.  I took some time to make a picture showing three examples.  I have an image that is filled with black 600x600. </p>
<p>
3.  On top of this image a draw another image of a white sphere.</p>

<p>Ex 1.  -  the dst is Vector2(0, 20)              //this shows the whole white sphere</p>
<p>Ex 2.  -  the dst is Vector2(-100, 300)      //this shows the strange behavior of clipping</p>
<p>Ex 3.  -  the dst is Vector2(550, 20)         //this draws correctly even if image goes beyond</p>

![example](https://user-images.githubusercontent.com/26915986/41449897-1202a3ea-7021-11e8-819a-9892d00b3bb5.png)

**Comment by AlexHolly** [comment]
Master branch?

https://github.com/godotengine/godot/pull/18219

**Comment by KoBeWi** [comment]
A reproduction project would be helpful. Tested in 3.1 and seems to work fine, but I could do something wrong.

**Comment by KoBeWi** [comment]
No reply, assuming resolved. Comment if you can still reproduce in 3.2.2 (and include a MRP)

**Comment by DarkMarmot** [comment]
@KoBeWi This bug is still present in 3.2.2 and quite irksome.

I had a lot of trouble understanding why things were not working as I was manually compositing sprites and only some of them were acting oddly. It turns out, if the destination Vector2 has a negative value, it doesn't perform clipping, but rather clamps against the side of the source rect. The apparent effect is quite confusing.

I was able to bypass this problem in GDScript by wrapping blend_rect with a clipping algorithm that made sure it never attempted to write pixel data outside of the destination image. It would be nice to have that code in the core, though. Thanks!

**Comment by Calinou** [comment]
@DarkMarmot Please open a new issue with a minimal reproduction project attached.
