### ISSUE TITLE
Triplanar spatial material specular bug.

### ISSUE THREAD

**Issue by Gyrth** [godotengine/godot#19577]
**Godot version:**
3.0.3

**OS/device including version:**
Ubuntu Linux 18.04

**Issue description:**
I have this concrete material which is Triplanar. The specular mode is disabled, but I'm still seeing a glitched specular shine sometimes. It's actually black when you turn the specular value all the way down.

![image](https://user-images.githubusercontent.com/14081613/41446884-6e0754c0-7052-11e8-853d-5bf22e6f680a.png)

![peek 2018-06-15 04-10](https://user-images.githubusercontent.com/14081613/41446926-b84e4656-7052-11e8-8e95-e6ef0dfcfc7d.gif)

**Comment by Calinou** [comment]
@Gyrth Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
