### ISSUE TITLE
Plane Collision Shape insta-colliding

### ISSUE THREAD

**Issue by N0hbdy** [godotengine/godot#19580]
**Godot version:**
3.0.3 (stable)

**OS/device including version:**
macOS High Sierra
Version 10.13.4 (17E202)

**Issue description:**
(3D)
Having a rigidbody with a plane-type collision shape completely breaks other rigidbodies.  The other bodies register an instant-collision (even though they shouldn't) and their transform.origin gets updated to (nan, nan, nan).

**Steps to reproduce:**
1. Add a rigidbody with a collision shape of plane
2. Add another rigidbody (I used box collision shape for second)
3. Start game - notice instant collision if reporting is on, and transform is updated to nan.

**Minimal reproduction project:**
[DebugPlane.zip](https://github.com/godotengine/godot/files/2104863/DebugPlane.zip)

As an aside, if somebody can point me to the possible location, I'd be happy to look into it.  Going to poke around a bit anyway, as it seems like planes also don't work with areas which was what I original wanted (but seems to already be a bug #13385)

**Comment by N0hbdy** [comment]
(This also repo'd on an old 3.0 stable as well)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by AndreaCatania** [comment]
If I've understood correctly you are trying to create a rigid body with a plane shape. If you read the documentation  you see that the plane shape has infinite size and this must be used only to create a sort of limit to world.

Also if you think about it there is no way for a shape with infinite size to be a rigid body, if you want you can create a convex shape from a plane mesh. In this case the created convex with plane shape will work correctly because the size will be finite.

**Comment by N0hbdy** [comment]
Got it - works for me, appreciate
