### ISSUE TITLE
len built-in

### ISSUE THREAD

**Issue by Fiona** [godotengine/godot#1960]
I used to wonder why Python had len as a built-in instead of a member but considering that Godot is inconsistent (String has length but Array has size?) I think I see why. It is such a common operation to know how big an object is that it being inconsistent isn't cool. (Principle of least surprise etc..)

I think either consider adding a built-in or making the names for length members consistent.

**Comment by neikeq** [comment]
Quoting **reduz** (from #3126):
> could have been implemented, but now adding that as a keyword would most likely break existing games. Maybe for 3.0

**Comment by AlexHolly** [comment]
+1
get_len() on File
size() on Array
length() on String
I go crazy.. and when there is a case where I can get a String or an Array I have to check the type first that ends in duplicate code and/or useless if-statements.

**Comment by razvanc87** [comment]
I also agree this should have one standard naming. Am not in favor of the `len` keyword tho', just rename the member functions of the proper classes...

**Comment by reduz** [comment]
these just copy the C API. size() and length() actually make sense and are taken from STL, given the C API can allow a bigger size() than length() due to the extra 0 character at the end. The rest of the Godot API uses more or less standard naming.. 

I would leave this as is, and maybe at worse rename the function in FileAccess in case anyone wants..
you guys have time until 3.0 reaches stable :P

**Comment by reduz** [comment]
I'm also not against adding a GDScript len() function that calls the proper function if you guys want also
