### ISSUE TITLE
JsonParseResult return error=0 in some invalid JSON strings

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#19611]
**Godot version:**

3.1 dev compiled last week

**OS/device including version:**

Win 7,8 10 and probably all systems

**Issue description:**

**Using JSON class to import JSON from invalid JSON file can return a valid JSON text.**
Example:

**File:**   test.json
**Content:**   true, false, [1,2,3],

In every JSON validator the mistake is finded behind first "true"  (is expected to reach EOF after true and not ","):

https://codebeautify.org/jsonvalidator

Code to test in Godot:

```
var JsonText = "true, false, [1,2,3],"
var JsonError = JSON.parse(JsonText).error
if JsonError == 0:
  print ("This should be an error", but Json is imported in this way:")
  print (JSON.parse(JsonText).result)
 #This print´s "true", Godot ignores that there is text after true.
```

**Comment by girng** [comment]
was just about to make an issue and saw this, awesome @pbrunet!

**Comment by Ranoller** [comment]
great

**Comment by reduz** [comment]
I would probably do something more akin to this for correctness:
```
	err = _parse_value(r_ret, token, str, idx, len, r_err_line, r_err_str);
	if (err == OK) {

		err = _get_token(str, idx, len, token, r_err_line, r_err_str);
		if (err != OK || token.type !=TK_EOF) {
			r_err_str = "Extra tokens or garbage found after expression";
			return ERR_PARSE_ERROR;
		}

	}
```

**Comment by reduz** [comment]
After the expression was parsed.

**Comment by pbrunet** [comment]
Ok, I got it, this way, we will have the parsing error first as it matter most than this trailing text issue.
Also, my fix certainly failed on trailing whitespaces :-(

As I am looking at this code, I wonder why the p_len is checked in the while loop : https://github.com/godotengine/godot/blob/20664419492c1e38a53963e2c32b4d027f5b8061/core/io/json.cpp#L128

To me, it looks like an infinite loop escaped when a correct token is created. Also in others part of the code, the len is also used in the while condition while the EOF token already do the same job.
I tried to remove all of these len as EOF already do the job. It also fix an small issue with something like "[1, 2," because the while loop escaped because of len check and thus didn't set message to give feedback to user. Now, as it is based on EOF, there is always a message.
Another solution if you don't like this one can be to fix the while condition turning strict comparison to non strict comparison.

**Comment by yjh0502** [comment]
The issue seems to be fixed on `master` branch.

**Comment by akien-mga** [comment]
I confirm that this is fixed in `master`:

```gdscript
func _ready():
	var JsonText = "true, false, [1,2,3],"
	var JsonInst = JSON.new()
	var JsonError = JsonInst.parse(JsonText)
	if JsonError != OK:
		print(JsonError)  # 43
		print(JsonInst.get_error_line())  # 0
		print(JsonInst.get_error_message())  # Expected 'EOF'
	else:
		print (JsonInst.get_data())
```
