### ISSUE TITLE
Game crashes if it has a 3D camera and windowsize is reduced to 1 pixel wide/tall.

### ISSUE THREAD

**Issue by johannesgunnar** [godotengine/godot#19628]
**Godot version:**
Godot 3.0.3

**OS/device including version:**
Ubuntu 18.04 64bit on AMD Cayman (HD 6950) and Mesa 18.0.0-rc5.
Intel® Core™ i5-4570 CPU @ 3.20GHz × 4 

**Issue description:**
In a 3d scene with camera, if scene is played in windowed mode and the user reduces the size of the window to 1 pixel (or less) tall or wide, the game will silently crash.

![tinywindowbug](https://user-images.githubusercontent.com/2924543/41553232-9ee6b4f2-7320-11e8-88a5-c5fdc12ceea8.gif)

This bug gives the following terminal output when launched from Godot editor

```
ERROR: operator[]: FATAL: Index p_index=0 out of size (size()=0)
   At: core/vector.h:138.
handle_crash: Program crashed with signal 4
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f995f509f20] (??:0)
[2] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0xbd5267] (<artificial>:?)
[3] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0xc0af84] (<artificial>:?)
[4] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0xc84ffa] (<artificial>:?)
[5] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x176879d] (<artificial>:?)
[6] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x1769377] (<artificial>:?)
[7] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x1784be0] (<artificial>:?)
[8] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x17872d1] (<artificial>:?)
[9] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x85e435] (??:?)
[10] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x6ce7ad] (??:?)
[11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f995f4ecb97] (??:0)
[12] /home/johannesg/bin/Godot_v3.0.3-stable_x11.64() [0x6dabbe] (??:?)
-- END OF BACKTRACE --
```

This bug gives the following terminal output when the project is exported and launched directly.

```
ERROR: operator[]: FATAL: Index p_index=0 out of size (size()=0)
   At: core/vector.h:138.
Illegal instruction (core dumped)
```

**Steps to reproduce:**

1. Create a new scene with only a 3d Camera.
2. Play the scene
3. Resize window so that it takes up as little vertical or horizontal space as possible. 1 pixel or less.

**Minimal reproduction project:**

[TinyWindowBug.zip](https://github.com/godotengine/godot/files/2112371/TinyWindowBug.zip)

**Comment by malbach** [comment]
Hi,

I can confirm this bug using master from [5c5aafa](https://github.com/godotengine/godot/commit/5c5aafabecfeaa056cae4c3a7fbaa1c52f147930)

I could trace it down to **RasterizerSceneGLES3::_post_process** in file [drivers/gles3/rasterizer_scene_gles3.cpp](https://github.com/godotengine/godot/blob/30caac8ee3b75de660075f07a1f334eed6cd17c7/drivers/gles3/rasterizer_scene_gles3.cpp) 

Here is the result of exporting test project in debug and reducing window's height down to 0 :
![crash tinywindow](https://user-images.githubusercontent.com/8791018/41662834-468ccafc-74a2-11e8-8f2d-c2c74a3994fd.PNG)

Only solution I found to limit this problem was to add 
```C++
	if (storage->frame.current_rt->effects.mip_maps[0].sizes.size() == 0)
		return;
```
just before 
```C++
	if (storage->frame.current_rt->buffers.active) {
		//transfer to effect buffer if using buffers, also resolve MSAA
```
at line 3550
But I think the real solution would be to find why the array **storage->frame.current_rt->effects.mip_maps[0].sizes** becomes null... am I wrong ?

**Comment by taylorjoshuaw** [comment]
I can confirm what @malbach is saying by attaching a remote debugger to a playing scene with a Camera and changing the window size. I will be looking into this further tonight. I can confirm that whatever is causing the behavior is not in the _post_process method, as setting a conditional breakpoint at the top of that method in Visual Studio to break when sizes._ptr is null triggers as soon as I set the window to height of 0. I'm going to investigate the call stack a bit more once I get back home tonight.

I don't know the ins and outs of Godot's Vector class, but I noticed that sizes._ptr is actually set to null. Therefore it might be something worse than just all the elements being dropped (depending on how Vector handles removing items....I'd think it'd keep some capacity around even when it's empty, but maybe that's not the case?). Don't be alarmed about this fact if it's actually expected behavior though. I'm a newbie to this codebase.

**Comment by taylorjoshuaw** [comment]
I also found what @malbach found using Visual Studio's debugger. I verified that the sizes vector is coming into the _post_process method empty when the height of the viewport is set to 0 by setting a conditional breakpoint in Visual Studio at the top of the method for when sizes._ptr is null. **Therefore, it's happening somewhere else in the code base**. I tried a few things, but couldn't find a fix.

**Comment by malbach** [comment]
Hi,
I think it's coming from function [_render_target_allocate](https://github.com/godotengine/godot/blob/6c649bd785b0901b0fcba37673f5256626d3f92d/drivers/gles3/rasterizer_storage_gles3.cpp#L6191) in file drivers/gles3/rasterizer_storage_gles3.cpp

This function returns directly if width or height is <=0, thus not allocating what's necessary for `_post_process`... well I think it is that :sweat_smile:
For me the simplest solution would be to limit the windows's size to (1,1) in Godot but I don't know how to do it :confused:

For reference, this bug has already been reported in [#19207](https://github.com/godotengine/godot/issues/19207)

**Comment by taylorjoshuaw** [comment]
So, I just set a conditional breakpoint on the following line of draw_viewports() in visual_server_viewport.cpp to trigger whenever the viewport size is less than 2:

```visible = visible && vp->size.x > 0 && vp->size.y > 0;```

It triggers when size.y is 1 as expected when I shrink down the window height. What I didn't expect was that the other conditional breakpoint I set in _post_process that triggers whenever mip_maps[0].sizes._ptr is null. So, either the real issue is actually having a window with a height of 1 instead of 0 as we originally thought, or the viewport's size struct's height field (y) is not reporting 0 like it's supposed to be when the window's height is shrunk below 1.

**_I was able to fix the crashing by changing that line I referenced above to the following:_**

```visible = visible && vp->size.x > 1 && vp->size.y > 1;```

I think this is an acceptable and simple enough tradeoff to prevent the crashes for now, and I will likely put in a PR referencing this issue to see what the devs think about making this tradeoff.

**Comment by lekoder** [comment]
I'm at build 1fc7973a0, which includes #20026 and I'm still experiencing this problem (with 2D project) - it crashes as soon as window height is dragged down to 0 with:
```
ERROR: Vector<struct RasterizerStorageGLES3::RenderTarget::Effects::MipMaps::Size>::operator []: 
   FATAL: Index p_index=1 out of size (size()=1)
   At: d:\projects\godot\core\vector.h:138
```
![crash at size 0](https://thumbs.gfycat.com/FirstImmaterialDarwinsfox-size_restricted.gif)

**Comment by malbach** [comment]
Hi,
I'm on me holidays so not able to compile but can someone test this for me : 
in file [rasterizer_storage_gles3.cpp](https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_storage_gles3.cpp#L6311), in function _render_target_allocate(), replace
if (rt->width <= 0 || rt->height <= 0)
return;
by
rt-

**Comment by malbach** [comment]
Hi,
I'm on me holidays so not able to compile but can someone test this for me ?
In function [_render_target_allocate()](https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_storage_gles3.cpp#L6311), replace 
```C++
if (rt->width <= 0 || rt->height <= 0)
return;
```
with
```C++
rt->width = rt->width > 0 ? rt->width : 1;
rt->height = rt->height > 0 ? rt->height : 1;
```

**Comment by lekoder** [comment]
@malbach compiled with patch, didn't help. Still crashed with same error.

**Comment by malbach** [comment]
@lekoder ok thx for the test
did u try my first solution ?

**Comment by lekoder** [comment]
@malbach I did now, it did not help either.

**Comment by malbach** [comment]
Hi,
Looks like a Windows problem, didn't test on iOS, but here on X11 (Xubuntu) it does not crash anymore

**Comment by taylorjoshuaw** [comment]
I'm sorry my fix didn't solve the issue. It stopped crashing for me after making the change in my PR, but obviously there's more to the issue than I had anticipated. I hope someone can figure this out, as I can no longer reproduce the crashing on my computer. I'm on Windows 10 with Intel graphics right now.

**Comment by malbach** [comment]
I should correct my own previous statement : it's also crashing in X11 :cry: 
Thanks to @lekoder narrowing down the problem, I found that it is coming from this line : 
```C++
glBindFramebuffer(GL_FRAMEBUFFER, storage->frame.current_rt->effects.mip_maps[0].sizes[i + 1].fbo); //next level, since mipmaps[0] starts one level bigger
```
in file [rasterizer_scene_gles3.cpp](https://github.com/godotengine/godot/blob/master/drivers/gles3/rasterizer_scene_gles3.cpp) (around line 3931).
The problem is that when the window is reduced to 0 in width or height, the array 
`storage->frame.current_rt->effects.mip_maps[0].sizes` only has 1 dimension, so trying to acces `[i+1]` is impossible, `i` having a value from `0` to `max_glow_level+1`

My first try was simply 
```C++
if (storage->frame.current_rt->effects.mip_maps[0].sizes.size() > i + 1)
    glBindFramebuffer(GL_FRAMEBUFFER, storage->frame.current_rt->effects.mip_maps[0].sizes[i + 1].fbo); //next level, since mipmaps[0] starts one level bigger
else
    glBindFramebuffer(GL_FRAMEBUFFER, storage->frame.current_rt->effects.mip_maps[0].sizes[0].fbo);
```
and no more crash no matter how I resized the window, but it's like the first bug from the OP, I just put a patch, not a solution :thinking:
For the solution, I don't exactly know how to correct it, @taylorjoshuaw could you take a look at it ?

**Comment by akien-mga** [comment]
Cherry-picked a78b42c for 3.0.7.
