### ISSUE TITLE
Support pluginscript reload on save

### ISSUE THREAD

**Issue by onyxblade** [godotengine/godot#19653]
**Godot version:**
master

Currently the reload on save feature for pluginscript is not yet implemented. And for any changes of exported properties I have to restart the editor to get the inspector updated, which is inconvenient.

@touilleMan could this patch work? https://github.com/CicholGricenchos/godot/commit/21c0147712e576c748427c3a25d1b62e9a784978 . It is tested by myself and seems working well but I don't know if it's a proper implementation.

The GDScript's `reload_tool_script` takes care of allocated instances and also reloads the base classes however I cannot tell the necessity of doing so. Under what circumstances these two are needed?

Thanks!

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
