### ISSUE TITLE
Allow signals to be connected (visually) to any node in the project

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19670]
![image](https://user-images.githubusercontent.com/1177508/41654276-38461f84-7489-11e8-8eb1-ae9da3adc7dd.png)

At the moment we have this case, say in *Scene 2* (the `Test`/tree node here):
![image](https://user-images.githubusercontent.com/1177508/41654366-856fc562-7489-11e8-9218-985f675f5412.png)

And say we want to make a child of *Scene 2* inside of *Scene 1*. Then to connect signals (visually) you have to go to *Scene 1*, enable `Editable children` and connect the signal. So you have to repeat this process every time:
![image](https://user-images.githubusercontent.com/1177508/41654572-25a9edfa-748a-11e8-8f99-5ba0a1e58786.png)
*note* that here the timer node also doesn't appear in the list even with `Enabled Children` ticked.

OK so you might say this isn't a good idea cause if you want to run *Scene 2* individually it can't connect the signals because of the missing *Scene 1*. But I'd respond to this that this is anyway the case in code if you want to connect to some parent from another scene, perhaps this can be coded in a different way in the UI to visually identify what signals are connected *within* the current scene as opposed to a *remote* scene.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
