### ISSUE TITLE
Encrypt/Decrypt string variable with GDscript

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#1969]
It would be great to have simple way for encrypt/decrypt string like this.

```
var message = "1234abcd"
var rawarray_encrypted_str = encrypt(message,"key")
var message_decrypted = decrypt(rawarray_encrypted_str, "key")
```

I think it's very useful when send/receive some messages over network.

**Comment by reduz** [comment]
could use aes256 for this, would that be fine?

**Comment by volzhs** [comment]
Yes! I do like that. :+1:

**Comment by gau-veldt** [comment]
Over networks you probably want a Diffie Hellman key exchange to prevent MITM sniffing of the keys used to encrypt passwords.

**Comment by Catprog** [comment]
Currently I am traveling so can't update the branch.

Last I heard the discussion was over the api.

Here are the functions that are needed:

- Set password / Set Key 

password sha256 hashes the input and puts it into the key.
key pads the key to 32 bytes(and hashes it into 32 bytes if longer)

-Use hmac

Is their a hmac at the start of the message(works for encrypting and decryption)

-encrypt_raw
-encrypt_string
-decrypt_raw
-decrypt_string

The meat of the class. 
encrypting always returns a char array
decryption always takes a char array
string and raw refers to the type of input and output. 

Could someone provide me with a suitable api that I can implement when I get home?

**Comment by blurymind** [comment]
this would be very nice to have for encrypting game saves or for implementing anti-piracy measures

**Comment by StraToN** [comment]
If possible, it would be interesting to provide the same functionalities with other algorithms, such as sha-512.

**Comment by gau-veldt** [comment]
@StraToN However the SHA family of algorithms are for one-way hashes (digital signatures, integrity checks, etc.) and not for actual encryption of messages and data.

**Comment by Calinou** [comment]
@StraToN There's already `String.sha256_buffer()`, `String.sha256_text()` and `File.get_sha256()` (in addition to their `md5` counterparts).

**Comment by gau-veldt** [comment]
Are BSD's & linuxes now doing this by default?
Is there a feature proposal to add these alongside String.sha256_buffer() and friends?

**Comment by Malkverbena** [comment]
I got some work to expose the mbedtls functions. Could maybe some of these functions be used in Godot?
Maybe merged on GDscript?
I don't know which way to go and I also don't know intimately the internal mechanisms of Godot.

https://github.com/Malkverbena/cripter

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
