### ISSUE TITLE
Sprite.get_item_rect() returns wrong position

### ISSUE THREAD

**Issue by haimat** [godotengine/godot#197]
I create a Sprite object like this:

```
var tex = get_resource(...)  # 50x50 pixels
var spr = Sprite.new()
add_child(spr)
spr.set_texture(tex)
spr.set_pos(Vector2(100, 100))  # or: spr.edit_set_rect(Rect2(Vector2(100, 100), tex.get_size()))
spr.show()

var rect = sprite.get_item_rect()
print(rect.pos, " - ", rect.size, " - ", rect.end)
```

This gives the following output:
0,0 - 50,50 - 50,50

Shouldn't the first Vector2 in the output ("pos") be 100,100?

**Comment by akien-mga** [comment]
First question, is it still valid in the current master branch?

Then, it looks like the position returned by Sprite.get_item_rect() is relative to the Sprite position, so 0,0 means that the texture is not offset with regard to the Sprite position. I believe this might be by design, @reduz might be able to confirm.

**Comment by akien-mga** [comment]
I've tested and I can reproduce the behaviour described above. On the other as I commented above I'm pretty sure it's by design that the returned position is relative to the Sprite position. If your texture is centred, the return position will then be a negative half-offset (e.g. -16,-16 if you have a centred 32x32 texture).

So, not a bug.
