### ISSUE TITLE
Spellchecker integration for Godot

### ISSUE THREAD

**Issue by Rriik** [godotengine/godot#19706]
**Godot version:**
3.0.3

**OS/device including version:**
Windows 10 x64

**Issue description:**
Godot should have a spellchecker toggle in much the same way Discord adopted one, by integrating with the OS spellchecker. It should be toggle-able on scripts, text field editor popups, etc. (on a case by case basis), such that it would help people creating story-driven games and using the Godot editor itself for text/dialogue scripts, instead of a third party text editor.

**Comment by LikeLakers2** [comment]
When you're making a story-driven game, and especially if you're working in a team, it's more likely you're going to be using a third-party tool such as Google Docs or some other document processor to handle spellchecking, grammar correction, etc.. I'm not sure I'd see many devs or writers wanting to write their game's story using some interface in a game engine editor, when third-party tools already handle the job better than Godot could.

That being said, I'm not against the idea. But I think it should be something exposed to the scripting interface (i.e. `OS.spellcheck('some text')`) for use within games themselves, not just something the editor has.

**Comment by NathanWarden** [comment]
I don't think the idea is a bad idea per se, but I do think it might be overkill as far as maintenance for the engine. For instance, how many languages would it support, and who would maintain each language when a spelling error is found in the spell check list? Are we going to include each of these language packs? Will it go through another open source library? I'm not entirely sold on the idea, but if there's some way to make it without bloating the engine itself and instead pushing the maintenance off to a third party open source system/library I would be much more comfortable with this proposition.

I'm also sure somebody has much better insight than I do as to the scope of this request :)

**Comment by vnen** [comment]
Problem is that OS spellchecker is available only on macOS (maybe iOS too?) and Windows 10 (not older versions). That means it will be quite platform-specific. Usually there's no much interest in things that can be used only in a few platforms, because it becomes somewhat of a burden and the user has to be aware of the availability.

I'm not against the idea itself, but it should be somewhat like @LikeLakers2 said: a custom function from  `OS` that let's you know what's wrong and then you can make a script to show it to user in the way you want.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by DarinDev1000** [comment]
I created a proposal discussion:  https://github.com/godotengine/godot-proposals/discussions/11647
