### ISSUE TITLE
Anyone volunteering to make a new UV Unwrapper?

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#19710]
Godot is currently using [Thekla Atlas](https://github.com/Thekla/thekla_atlas) for unwrapping UVs on mesh import. Unfortunately, this implementation is very slow and quite buggy. We need a replacement, otherwise the current light mapping workflow (which is needed for pretty graphics on low end) will continue to be a hassle.

The only other open source unwrapper is Microsoft's [UVAtlas](https://github.com/Microsoft/UVAtlas), but it's windows-only so it needs porting. Also, it does not support specifying a texel size, which makes it no so useful.

There are a few papers on implementing this algorithm:
* [LSCM](https://members.loria.fr/Bruno.Levy/papers/LSCM_SIGGRAPH_2002.pdf) (2002)
* [SLIM](https://cs.nyu.edu/~panozzo/papers/SLIM-2016.pdf) (2016, more modern)

Would anyone be interested in giving a try of implementing one of these algorithms in Godot, make it work with a texel size parameter, and make it as optimal as possible?

**Comment by AbhimanyuAryan** [comment]
I'll have a week holiday from work. I'll give it a shot. Where can I get any help if needed? Do we have Gitter channel for GodotEngine?

**Comment by avril-gh** [comment]
IRC
chat.freenode.net
#godotengine-devel 
#godotengine-doc
#godotengine

**Comment by laverneth** [comment]
We can team up, I know the computation of injective maps quite well. I just don't really where to start within godot...

**Comment by reduz** [comment]
and Godot has most of the math types and container types in core:

https://github.com/godotengine/godot/tree/master/core/math

so no need to write your own

**Comment by laverneth** [comment]
I can't find support for sparse matrix and sparse linear solver, I can
write my own in the library. Should they be kept separate?

Le ven. 22 juin 2018 à 14:30, Juan Linietsky <notifications@github.com> a
écrit :

**Comment by reduz** [comment]
yeah, godot only has basic linear algebra types, as sparse matrix/linear solvers are not that common or difficult to make generic. If you want to write your own for this and put it within the unwrapper code, it's fine

**Comment by laverneth** [comment]
Well that's seam feasible. Still, I have few questions.
1)What I intent to do is create a new thirdparty lib as theakla and then
wrap it into a module as you sent? Or shoudl I develop everything inside
the module (in that case I guess I can have access to godot classes, such
as meshes)?
2)Is it ok to depend from stl, because for the sparse matrices it would
make my life easier if i can have std::vectors. If I am in the module I'll
depend on godot' vector implementation
3) I'm not sure to understand 100% the use case. Is for uv unwrapping a
single mesh or do we have also to unwrap several patches (seamless
parameterization section6 of the latest article reference you sent)?
4) YOu said Theakla was slow. What's the expected speed ? On which size of
meshes? Would you have one or two testcases (meshes)?

Thank you very much Juan and all



Le ven. 22 juin 2018 à 16:21, Juan Linietsky <notifications@github.com> a
écrit :

**Comment by ddiakopoulos** [comment]
For an initiative like this it might make sense to attempt to validate + profile against a large database of potential input models. One possibility is https://ten-thousand-models.appspot.com/ and another here: http://cvgl.stanford.edu/projects/objectnet3d/. The 10k dataset has many degenerate cases so it's very helpful. What these datasets lack is geometry that is more game-specific (like terrain), but likely to be used for target lightmaps.

**Comment by rotoglup** [comment]
About UVAtlas,

> The only other open source unwrapper is Microsoft's UVAtlas, but it's windows-only so it needs porting. Also, it does not support specifying a texel size, which makes it no so useful.

@reduz Do you need texel size to specify padding/distance between charts ? I saw in [UVAtlas.h](https://github.com/Microsoft/UVAtlas/blob/master/UVAtlas/inc/UVAtlas.h) the `gutter` argument for this case. I may miss something as I don't use Godot or UVAtlas :}

    //  gutter - The minimum distance, in texels between two charts on the atlas.
    //           this gets scaled by the width, so if gutter is 2.5, and it is
    //           used on a 512x512 texture, then the minimum distance will be
    //           2.5 / 512 in u-v space.

**Comment by reduz** [comment]
@rotoglup No.. unless there is something I misunderstood, texel size is needed to compute the actual texture size. When you call the unwrapper, you have to feed it a mesh and a texel size (in the same units as the mesh). As a result, the unwrapper needs to figure out the final texture size.

In UVAtlas, you have to supply texture size beforehand, so it's not possible. Otherwise, I'm not sure how gutter could be of use for that (without having to call unwrap twice)..

**Comment by JFonS** [comment]
The BFF linked by @ddiakopoulos looks very promising and uses the MIT license. So it might be better to try integrating it into godot  (just a part of it) instead of reinventing the wheel.

**Comment by JFonS** [comment]
@reduz also, the texel size is only used when generating and packing a texture. Thekla seems to be using nvidia-texture-tools for that, so it should be possible to integrate a different UV mapping algorithm with this texture packer.

**Comment by laverneth** [comment]
I don't know if that's a problem but BFF uses Cholmod (from eigen) which is
under GPL 2.1 licence for fast performance.
Moreover it only produces conformal maps, whereas the SLIM approach can
also produce isometric map, and other different maps depending on the
choice of energy. It's still up to the community to decide what's best,
just a heads up :-)!

**Comment by reduz** [comment]
@laverneth whathever we use needs to be MIT compatible, else it forces the whole engine to use a more restrictive license. It may seem that BFF is also restricted to manifold with no holes, which is likely a problem. From what I understand, the only two algorithms I know that actually work well are LSCM and SLIM.

**Comment by reduz** [comment]
Slim example is under GPLv3.. I wish people would stop using this license for academic stuf.. :(
https://github.com/MichaelRabinovich/Scalable-Locally-Injective-Mappings

**Comment by laverneth** [comment]
Do we have access somewhere to a svd decomposition, line eigen? I need it
for decomposing the jacobian. Otherwise I will include the TNT but it will
make the module fatter...

Le 23 juin 2018 4:51 PM, "Juan Linietsky" <notifications@github.com> a
écrit :

Slim example is under GPLv3.. I wish people would stop using this license
for academic stuf.. :(
https://github.com/MichaelRabinovich/Scalable-Locally-Injective-Mappings

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/19710#issuecomment-399684063>,
or mute the thread

**Comment by reduz** [comment]
> Do we have access somewhere to a svd decomposition, line eigen? I need it
> for decomposing the jacobian. Otherwise I will include the TNT but it will
> make the module fatter...

No, in general these are implemented per each algorithm depending on the needs. Bullet has code for this, but it's meant mostly for solving physics constraint for a 3D physics engine. Here I imagine you need it for 2D to relax the edge constraints, so i don't think it can be reused.  Worst case, does not seem like it should be too much code to copy from an existing MIT licensed library, if you need that.

**Comment by Calinou** [comment]
> The TNT has no particular license, they juste want to be credited. I will.

If any code is copied, it should be permissivelyy-licensed license with no ambiguity; please contact its author(s) to ask for permission to use the code under the MIT license.

**Comment by hpvb** [comment]
```
* This software was developed at the National Institute of Standards and
* Technology (NIST) by employees of the Federal Government in the course
* of their official duties. Pursuant to title 17 Section 105 of the
* United States Code, this software is not subject to copyright protection
* and is in the public domain. NIST assumes no responsibility whatsoever for
* its use by other parties, and makes no guarantees, expressed or implied,
* about its quality, reliability, or any other characteristic.
```

according to the header files. I don't think anyone needs to be contacted, or legally speaking credited.

**Comment by razcore-art** [comment]
That looks like a license to me, remember a license is just some text, it doesn't actually have to be one of the know ones, eg. MIT or whatever, it just needs to be some text compatible with whatever you're using. The above seems pretty compatible

**Comment by laverneth** [comment]
Can someone explain me when the call to thekla is effectively done? I see
it's done in the lightmap_unwrap, what should I do to trigger this
functions?
Many thanks!

**Comment by reduz** [comment]
Here in the documentation of light mapping you can see the two use cases (manual and on import), basically the most common use case is as an import flag, but the manual method allows you to debug it more easily

**Comment by reduz** [comment]
sorry, forgot link - http://docs.godotengine.org/en/3.0/tutorials/3d/baked_lightmaps.html

**Comment by reduz** [comment]
If you want to iterate faster, remember you can run Godot editor from the command line with a test scene like:

godot -e test_unwrap.scn

**Comment by lassade** [comment]
What about this implementation [http://alice.loria.fr/index.php/software/4-library/23-opennl.html](http://alice.loria.fr/index.php/software/4-library/23-opennl.html) it's under the 3-Clause BSD License, is very compact (4 files) and static linked.

**Comment by jamesdolan** [comment]
I had pretty much have been facing the same dilemma for my own project. Thekla was way too crashy for my liking but UVAtlas seemed to be pretty robust but being Windows only was a bit of a downer.

UVAtlas allows you to run Partitioning and Packing as different steps. The partitioner is resolution independent and I am quite happy with its output, its the packer that needs work. As you point out it doesn't let you set a target density, but its pretty easy to compute surface area before packing and calculate your own scale to target a specific density.

The bigger problem IMHO is that the tetris-style packer does a rather poor job compared to Thekla in my experience. Leaves lots of dead space, specially when there is a large ratio between the biggest charts and smallest charts.

The other nice thing about UVAtlas is its actually under active development and tested in production.

My recommendation after taking a quick glance at feasibility is instead of forking it and porting it, someone should build a compatibility layer that re-defines the macros and types it uses so that its easy to take updates from the mainline and push changes upstream (guessing MS wouldn't take a pull request that de-microsofts it). That is my long-term plan, but not sure when I would get to it... so if someone else does it, even better! :p

**Comment by AbhimanyuAryan** [comment]
@reduz may I ask what bugs are you facing with Thekla Atlas? Are you getting charts with too much distortion, or worse, that self-overlap?

**Comment by jpcy** [comment]
I did some work removing unused code from thekla_atlas a while back [here](https://github.com/jpcy/xatlas). Got it down from about 18kloc to 8kloc.

**Comment by reduz** [comment]
@jpcy oh wow, amazing work! definitely need to give it a check. Are you up for merging fixes? ( think i did a few to thekla that resulted in crashes in bad input geometry )

**Comment by jpcy** [comment]
@reduz After looking through the Godot changes, I added checks for zero length edges and zero area triangles. Zero length edges were definitely causing crashes.

**Comment by laverneth** [comment]
I have been making some progress about implementing the SLIM paper. For the
moment I'm focusing into initializing the (u,v) property by minimizing the
dirichlet energy on the surface by constraining the longest boundary loop
to be immersed one a circle. However I do have some trouble to make a
proper test. I am importing a .obj as a mesh instance but I have some
inconsistent number of vertices and faces. I was wondering if the .obj
import of godot was'nt broken OR the way I have created this file. I have
imported the stanford bunny (file format .ply) inside blender and exported
it as .obj before reimporting it. Does anyone knows anything about similar
issue?
I've checked the .obj file and the number of vertices and facets seems to
be consistent.

Cheers

Le sam. 14 juil. 2018 à 12:51, Jonathan Young <notifications@github.com> a
écrit :

**Comment by laverneth** [comment]
I used the default, which is "Apply Modifiers". I'll check with the
triangulate faces. Thanks! 😀

Le lun. 16 juil. 2018 à 16:26, Hugo Locurcio <notifications@github.com> a
écrit :

**Comment by huxingyi** [comment]
Hi, how is the progress on this? I used Thekla Atlas for unwrapping UVs also, but cannot bear it with the crash on bad meshes. Actually, I looked this issue about two months ago when I was trying to find an alternative, finally I decided write it on my own, I use the [MPL2 licensed libigl](https://github.com/libigl/libigl/blob/master/LICENSE.MPL2)’s parameterization implementation (ARAP and LSCM). It works well on my [project](https://github.com/huxingyi/dust3d).
[Here](https://github.com/huxingyi/simpleuv) is my UV unwrapping library, [here](https://github.com/huxingyi/dust3d/blob/master/src/uvunwrap.cpp) is how it’s been used,
And here is the screen shoot of unwrapping:
<img width="539" alt="screen shot 2018-12-22 at 21 08 26" src="https://user-images.githubusercontent.com/3941597/50374054-93897700-062f-11e9-95ba-ddbb2d3127c4.png">

If you are interested, I’d like to integrate it into godot.

BTW, I saw you @reduz request an alternative for [cork](https://github.com/gilbo/cork), currently, I use CGAL, it works quite well on mesh boolean operations, but I have decided try to write it on my own also, because I cannot go with the CGAL license, here is the [project](https://github.com/huxingyi/simpleboolean), although, empty yet, because I just start it by today :-)

**Comment by laverneth** [comment]
Wow that looks good! On my side I tried to have a look into godot' code to see what was needed to do it inside. My conclusion is the following: we need a proper mesh boundary description to initialize the mapping with the Tutte method and a proper linear solver. Both of those represent a big amount of code (in particular a good linear solver) and I doubt that the godot' community would like to see its codebase grow so much for parametrization code. However, we should ask to Juan, maybe?

**Comment by fire** [comment]
Has anything changed? What is the status of this?

**Comment by huxingyi** [comment]
Thanks @laverneth for the update. And I didn't got any reply from godot since I posted here, so I don't know what's the status of this, and I am quite busy at the moment, so I am out on this issue.

**Comment by KoBeWi** [comment]
Thekla Atlas was replaced by Xatlas, but I don't know any more details.

**Comment by Calinou** [comment]
With Thekla Atlas being replaced by Xatlas and [further tweaks made to optimize Xatlas](https://github.com/godotengine/godot/pull/31728), this issue can be closed.

**Comment by Ben-Mack** [comment]
I've noticed `XA_RECOMPUTE_CHARTS` enabled in xatlas usually results in a lot of small and unnecessary charts. Both original and Godot's modified version suffers from this problem.
It would be great if someone could take a look and discuss ideas to improve: https://github.com/jpcy/xatlas/issues/84
![recompute-charts-on](https://user-images.githubusercontent.com/6309393/98757982-3d2ea880-2400-11eb-8a18-b19f95f50184.png)
