### ISSUE TITLE
New AnimationPlayer bezier editor should be f-curve editor to be useful

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#19722]
@reduz you did a huge improvement on the AnimationPlayer and it's definitely gonna get even better I have a feeling. There are a few usability problems with how things are at the moment (8bf5b50).

The bezier curve editor to be really useful it should be like the f-curve editor in Blender otherwise it's very very difficult to control precisely which needs to be done for good animations. So missing stuff are basically ways to deal with interpolation and snapping. At the moment the key frames are introduced with horizontal default handles and say you want to do a parabola for a jump, it's impossible to do precisely.

Note the default key frames have horizontal handles which means that the X motion is not linear and it's going to be pain to make it linear or at least much more complicated than needed.
![image](https://user-images.githubusercontent.com/1177508/41798785-4424249e-766f-11e8-8875-22050e62ed20.png)

Blender solves these things by giving interpolation options per point (line between current point and next one if there is one)
![image](https://user-images.githubusercontent.com/1177508/41798914-c726aa60-766f-11e8-9cf0-359757520b94.png)

Furthermore there should also be a *vector* handles type in the list where there's: free, balanced, mirror. I think Blender got these things right, perhaps even the extrapolation method could be looked into, instead of the clamp/wrap loop option.

handle types:
![image](https://user-images.githubusercontent.com/1177508/41799003-0f4f65d4-7670-11e8-8187-c1cd3d3f05a1.png)

extrapolation methods
![image](https://user-images.githubusercontent.com/1177508/41799019-202aae90-7670-11e8-9900-512f576ab00e.png)

**Comment by reduz** [comment]
If you want this kind of more custom transitions, then just use a regular
property track, which lets you choose from a wider range of curves. Bezier
curves are more meant for traditional, per component animation.

From my part, no further work will be done on this, as I believe it's by
far good enough, so it's up to anyone else who may want to contribute
improvements.

**Comment by Zylann** [comment]
Note: the Curve resource does have per-point interpolation options ;)

**Comment by NathanLovato** [comment]
Bezier curves are really flexible. The only issues I had trying this out were linked to UX: no time snapping and having to use the interface to toggle between linked and free handles, and the absence of snapping on bezier handles (e.g. hold shift to force horizontal, vertical or tangent handle scaling).

Having hold, linear, and bezier interpolations all in one graph is useful for 3d animators: you often use the hold mode for blocking/posing, the first animation phase, then turn everything into Beziers curves. Now you'll still want to do that in a feature-complete program, where you can rig your characters... for 2d animation, it may not be as essential.

**Comment by razvanc-r** [comment]
@Zylann you mean the curve resource used as bezier curve in the new animation player?

If Godot takes the stance that it isn't meant for animating, but more like just tweaking and quick animations for testing then ya it's fine, if it wants to be more complete then it isn't fine. Again, do a simple experiment of trying to make a parabola work in 2D. You can't do it with the property track because you need to work separately on x & y. I mean sure you can do it, but you'll have to manually key frame each individual frame.

I just noticed that when you select the points on bezier curve track their properties show up in the inspector but if you enter inside of the curve editor the inspector isn't used any longer. I think the key frame properties should be visible when inside the curver editor too, it will be easier to understand what values you want the handles to have if you see them update in real time while in the curve editor instead of jumping in and out of it... should you want to tweak the handles (and possibly key value) in the inspector. And yes, the snapping.

I understand you're not gonna work on improving it any more @reduz, but I think this issue still has merit if only for discussion.

**Comment by reduz** [comment]
Again, the fact I won't do any further work does not mean anyone else can't. I always just write initial implementation of stuff so others can work on top of them and improve them.

If a feature is really wanted and really necessary, community will work out a way and contribute it. If no one works on it, it's usually because there it's not so important. 

If many ask for it and after some time no one contributes to it, I may work on it again. In the meantime I do other stuff. If I were to work on every feature down to the smallest detail every time I implement something, my time would be wasted and this would be a lot less of a community effort.

**Comment by razcore-art** [comment]
@reduz yeah sorry, I think you misunderstood, I didn't mean to imply that you should work on it. I'm just starting a conversation about what I think it's missing.

**Comment by Zylann** [comment]
> @Zylann you mean the curve resource used as bezier curve in the new animation player?

Actually it's not ;) `AnimationPlayer` is brand new.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
