### ISSUE TITLE
Tween signals key names

### ISSUE THREAD

**Issue by razcore-code** [godotengine/godot#19731]
The Tween node passes the keys on emitting its signals. But the keys have `:` as a prefix compared to the "keys" you supply when calling for example `interpolate_property`. E.g:

```gdscript
$Tween.interpolate_property(self, "position:x", position.x, position.x + AMPLITUDE., TIME, Tween.TRANS_LINEAR, Tween.EASE_IN)
```

in a function connected to `tween_completed`, the supplied key is `:position:x` which is inconsistent with the signature call.

**Comment by mhilbrunner** [comment]
Prefix, you mean. :)

**Comment by akien-mga** [comment]
Since it requires breaking compat we can't change it before 4.0 - assigning to 3.2 milestone for now, which *might* end up renamed to 4.0 if we decide to go straight for that after 3.1.

@bojidar-bg Would be the opportunity to drop support for `:` to index properties in NodePath and keep only `.` I guess, now that it's the recommended way to access properties in 3.0+.

**Comment by bojidar-bg** [comment]
The best-case scenario would be getting lambdas/property references for it. A slightly worse case would be getting a PropertyPath type (or dropping compat for nodepaths which don't start with `./`).

> Would be the opportunity to drop support for : to index properties in NodePath and keep only . I guess, now that it's the recommended way to access properties in 3.0+.

NodePath does not support `.` for indexing.

**Comment by KoBeWi** [comment]
The signal was removed with the Tween rework, so this is resolved.
