### ISSUE TITLE
SSR Trace Resolution

### ISSUE THREAD

**Issue by adriansnetlis** [godotengine/godot#19737]
**Godot version:**
v3.0.3

**OS/device including version:**
Antergos with 4.17.2-ARCH kernel
NVIDIA GeForce GTX 1060 6GB with driver 396.24

**Issue description:**
There is no option under SSR to set trace quality. It seems like SSR is set to trace at half resolution. However, it would be very handy if there was option to trace it at full resolution (for better, sharper reflections and reduced chance of artifacts).

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
