### ISSUE TITLE
SignalMap: Signal-based high level layer for VisualScript

### ISSUE THREAD

**Issue by hackini** [godotengine/godot#19750]
As said in #18267, we could split visual scripting in two levels.
- "Inside a node" : It's the current visual scripting : it let us program a node like we would in GDScript or any other language.
- "In-between nodes" : It's basically signals, which defines how nodes communicate with each other.

The first level is being discussed for eg in #1826 , however I didn't see mockups for the higher level. I wanted to know what you think about the following mockup: 

Another view (let's call it "SignalMap" for eg) where you would see which node is connected to which. You could connect signal/functions together from this view (like in the current signal panel, but in a more visual way).

![mockup1](https://user-images.githubusercontent.com/40541048/41819960-28d97ffc-77ca-11e8-9afa-5043132b29fb.png)

With a lot of nodes & signals the graph could become quite dense so we could have the option to filter it and display nodes/signals of the selected node children only : 

![mockup2](https://user-images.githubusercontent.com/40541048/41819998-b04b0802-77ca-11e8-8d95-5cf060aacd1a.png)

When double clicking on a node it could bring up the Script/VS editor. 

Then similarly to what has been proposed for Visual Script, we could have live debugging features such as : 
- Red for node that throws an error
- Highlight edge (eg yellow) when the signal is being used
- etc...

![mockup3](https://user-images.githubusercontent.com/40541048/41820112-c27d1d38-77cc-11e8-8747-c64d73979b42.png)

Is it a feature for completing the current VisualScripting that would be welcome or does the community has another direction in mind ?

**Comment by Nobelix** [comment]
Finally, YES! I was thinking of some kind of system like this and you nailed it

**Comment by swarnimarun** [comment]
I was thinking about creating a re-implementation of parts of Visual Scripting and had a similar idea.
My idea was creating a level wide node system.

And this is the perfect solution it seems.

**Comment by hackini** [comment]
Just to let you know, I proposed the idea to work on it as part of a semester project at my university but this was refused and currently I don't have time to work on it in my free time sorry :/

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
