### ISSUE TITLE
UI/UX improvements suggestions.

### ISSUE THREAD

**Issue by daniel-dietrich** [godotengine/godot#19771]
Here are few inconsistencies and little annoyances in Godot I've noticed that, if fixed could greatly improve overall feel. 

- As for now, Godot has only few 'while covering with cursor' highlights for interactive elements. And those are very important, especially for beginners. Highlights that are present include texts ( white > gray), icons ( white > gray ), resize box lines and unique underline effect for options in menu bar.
Godot lacks hightlights for tabs, items in menus and buttons for changing dock position.
Existing highlights are not consistent and not enought noticable to make a difference for a user, my proposition is to take notes from ex. Visual Studio, in which every interactive text or icon gets visible background on cover.
![oncover](https://user-images.githubusercontent.com/10032237/41870358-232a9efe-78bc-11e8-8e5c-dfb2b80bf6df.jpg)
While I am at it, selected items in FileSystem don't have border, while view of items in it does.

- First thing I've noticed in Godot and still is bugging me till this day, is no dynamic changing menus in menu bar. In every other program I've used, once you click on one item in menu bar and move cursor to the other the menu dynamically changes. In Godot it unfortunatly doesn't work like that. 

- Last, two little improvements apply to code editor. When selecting lines by keeping cursor on line numbers the selection is one line late. Selection should be in the same level as the cursor. Last thing, please make breakpoint a... point.

**Comment by Calinou** [comment]
> First thing I've noticed in Godot and still is bugging me till this day, is no dynamic changing menus in menu bar. In every other program I've used, once you click on one item in menu bar and move cursor to the other the menu dynamically changes. In Godot it unfortunatly doesn't work like that.

This is now implemented since Godot 3.1.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
