### ISSUE TITLE
Keyboard navigation on the interface

### ISSUE THREAD

**Issue by Misignu** [godotengine/godot#19787]
**Godot version:** 3.0.4

**Issue description:** UX failures force the user to switch between mouse and keyboard.

There are several shortcuts present in the API. But I could not locate those who allow me to navigate in it.
![image](https://user-images.githubusercontent.com/28039158/41928007-389b61d6-794a-11e8-872b-8b832411a3d0.png)
Not having access to certain options in the software, makes your use less productive for those who tend to use the keyboard more.

_Case1:_ Many times when I'm working in the Script editor, and I need to check something in the other panels, I end up having to switch to the scene editor, only to be able to navigate freely on the interface; This is not a very intuitive task, in my view.

_Case2:_ The TAB key allows me to move on the GUI, but it is somewhat confusing, as it is difficult to understand which panel is in focus at the moment. Only buttons, or input objects as the text field are highlighted. As a consequence I have to pushing the arrows to see if I can locate myself, and this may end up, move an object from the scene for example. Sometimes I can not access some panels, like the Inspector (one of the always have to be manipulating). And I end up having to opt for the mouse (the villain tendinitis.)

_Case3:_ For some reason the full screen is activated with Shift + F11. Which could lead us to believe that the option does not even exist, if the option Editor > Toggle Fullscreen was not available. The Scape key does not deactivate this mode. _//This is not a big problem, but it is different from the patterns which generates a certain strangeness._

_Case4:_ In the inspector, I found no way to expand/select these options...
![image](https://user-images.githubusercontent.com/28039158/41927070-7e2caa6e-7947-11e8-93a5-3dcdacbf8c8d.png)

Given this, I show below some cases of how problems like this are solved in other softwares:

- The ALT key would allow me to navigate the options bar: the desired option would be represented with a highlighted character, as shown in the examples below 
![captura de tela 550](https://user-images.githubusercontent.com/28039158/41925837-1d27c5d0-7944-11e8-9b9d-726b4501a20f.png)
![captura de tela 551](https://user-images.githubusercontent.com/28039158/41925844-203890f6-7944-11e8-9d28-d434b2c0c985.png)

- _This following solution is present on Godot but it is very strange, sometimes works, others do not._ Navigating between tabs as well as in browsers is performed by pressing CTRL + TAB or SHIFT + TAB, or even CTRL + (1-9 tab numbering).

- In some software, such as Photoshop, some panes (or Windows) have specific shortcuts. Which would make access to the Inspector much quicker and more practical.
![keyboard shortcuts for windows](https://user-images.githubusercontent.com/28039158/41929277-f0eac5bc-794d-11e8-81fe-9626516ec1d2.png)

- F1 in many programs, opens a guide or manual, which is actually not that relevant.

- In canvas, it would make sense if the zoom control was performed with the CTRL + (+,-, 0) keys.

Some problems may seem a bit silly, but they really make a difference when you choose to leave your mouse aside.

If you have more cases or solutions for this type of problem in UX, please feel free to join us in the discussion. I hope someone understands and implements these issues.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
