### ISSUE TITLE
How does Hue Variation work for Particle 2D?

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#19784]
3.0.3 Stable, Windows 10.

I have tried to get the Hue variation to work on my 2D particle system. I can only get it to work in the 3D Particle System by setting the material property to use rgb but a 2D particle is using a sprite and does not have the Spatial material, so how does this work?  

![image](https://user-images.githubusercontent.com/24936603/41926155-daf1bb64-796e-11e8-8e24-5628b8943665.png)

**Comment by Ranoller** [comment]
See gifts in last mesagges of this commit: https://github.com/godotengine/godot/pull/17642

**Comment by akien-mga** [comment]
I'm not sure what the issue is about, I tried Hue Variation and it properly seems to change the hue of particles in the current master branch, for both CPUParticles2D and Particles2D.

So I'll assume there used to be a bug for 2D particles which was fixed. If not and the issue is with understanding what the parameter does exactly, this should likely be reopened on https://github.com/godotengine/godot-docs to improve https://docs.godotengine.org/en/latest/tutorials/2d/particle_systems_2d.html#hue-variation
