### ISSUE TITLE
Support playing audio streams in reverse

### ISSUE THREAD

**Issue by WolfieMario** [godotengine/godot#19804]
**Godot version:**
v3.0.3.stable.official.e649ec7

**OS/device including version:**
Windows 10

**Issue description:**
There currently doesn't seem to be an API for playing audio streams in reverse / backwards.

AudioStreamSample has a LOOP_PING_PONG LoopMode which alternates between playing forwards and backwards. However, you can't _only_ play a sample backwards, and you can't play an AudioStreamOGGVorbis backwards.

Ideally, there would be some API on AudioStreamPlayer (and AudioStreamPlayer2D/3D) to play audio backwards. Perhaps a `reverse` field or an extra argument to play()?
For what it's worth, Unity allows playing audio in reverse by setting pitch scale to a negative value, so that's another idea.

My own use-case is a rewind / reverse-time effect, where (among other things) music and sound effects are played backwards.

**Comment by Zylann** [comment]
Would there be a `play_speed` property which could simply be set to a negative value?

**Comment by WolfieMario** [comment]
As of 3.0.3, AudioStreamPlayer and co. have a `pitch_scale` property which controls play speed (resulting in both time scale and pitch shift, hence the name I guess). However, if you set it to a negative value, the audio just stops playing.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by jonathanMrz** [comment]
......don't have negative pitch

**Comment by foxp552** [comment]
Nope its not closed yet 😈
I Just fund a solution I guess
