### ISSUE TITLE
Multiple resource packs

### ISSUE THREAD

**Issue by empyreanx** [godotengine/godot#1984]
Seamless loading of multiple zip/pck resource packs in a manner similar to [PhysicsFS](http://icculus.org/physfs/).

**Comment by beniwtv** [comment]
+1 for having the ability to create multiple .pck per project.

Specially for large games, say with 500MB or more in assets one .pck is rather unconvenient. For example, if you update your game, the users would have to download the whole 500 GB file again, but you only updated two files...

When exporting your game, Godot could make a fast-lookup index of which resources are in which .pck (obviously editor would need to support specifying in which .pck the file should go), so that resource loading would still be as fast.

(Or load all .pck's on startup? Allthough that also would be a waste of memory resources, and could lead to out of memory problems for very big games...)

**Comment by akien-mga** [comment]
You can also *not* export .pck and directly provide the game's project folder, though of course that means that the code and assets are accessible to everyone (not necessarily open source though unless you provide a corresponding license, but you wouldn't be able to prevent people from inspecting the project and/or edit it for themselves in Godot).

But yeah multiple .pcks might be a nice feature for big projects I suppose, if it's not too hard to implement regarding the res:// filesystem.

**Comment by reduz** [comment]
godot supports using pcks for patching the game, but an UI for creating the
patches was never done.. :|

**Comment by beniwtv** [comment]
Wow! Nice to know! I am always amazed at how much this engine can do :)

**Comment by reduz** [comment]
this is supported already, so closing issue. As an extra bit of info, you can also load zip files as filesystem now.

**Comment by LikeLakers2** [comment]
Was linked here by Calinou, we were just having a discussion on such a feature being added, as it didn't seem like multiple .PCK/.ZIP support was a thing.

>this is supported already ... you can also load zip files as filesystem now.

How would you go about doing this? Will this still be possible in Godot 3.0?

**Comment by neikeq** [comment]
Yes, this isn't supported yet. Godot can load multiple packs and the editor can export patches, but AFAIK the editor cannot export your game as multiple packs currently.
Correct me if I'm wrong.

**Comment by sprite-1** [comment]
>Godot can load multiple packs and the editor can export patches,

@neikeq how exactly can Godot export patches?

**Comment by LikeLakers2** [comment]
> Godot can load multiple packs

Apologies for the bump, but how can Godot load multiple packs? I see ProjectSettings.load_resource_pack, but that replaces the entire `res://` structure rather than adds to it.

**Comment by Calinou** [comment]
Is this addressed by [Exporting packs, patches and mods](https://docs.godotengine.org/en/latest/getting_started/workflow/export/exporting_pcks.html) in the documentation?

**Comment by LikeLakers2** [comment]
@Calinou That documentation seems to address this -- that said, there's still #19815 to be concerned about (check out the newest comment from me there -- as it turns out, `ProjectSettings.load_resource_pack(pck)` ends up causing issues when running the game from the editor, but not when running an exported version of the game).

**Comment by Calinou** [comment]
@LikeLakers2 Thanks for replying :slightly_smiling_face: I'll close this issue then.
