### ISSUE TITLE
AnimationPlayer plays AudioStream two times.

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#19856]
**Godot version:**
3852c5f8a0b439a8c0c6e72433d6fe82e3e596de

**OS/device including version:**
Linux 4.17.2

**Issue description:**
AnimationPlayer plays AudioStream when the timeline arrives at the end and I think this is a bug.
![captura de tela de 2018-06-30 11-29-33](https://user-images.githubusercontent.com/1387165/42126120-e74ddbe4-7c58-11e8-9f89-60b1060fcf92.png)

**Steps to reproduce:**
https://youtu.be/kS_PSVeLbJU

**Minimal reproduction project:**
[Bug Audio 2D.zip](https://github.com/godotengine/godot/files/2151792/Bug.Audio.2D.zip)

**Comment by khairul169** [comment]
This only happens if the track update is set to discrete. If you set it to trigger, it won't happen.

**Comment by guilhermefelipecgs** [comment]
Yeah, I'm already doing this for all tracks with sound.

**Comment by guilhermefelipecgs** [comment]
But still, I think this remains as a bug right?

**Comment by lucabelluccini** [comment]
In the scope of Hacktoberfest, I'm trying to contribute for the first time to Godot.
I've setup KDevelop, cloned master and trying to debug the instance using the project to reproduce.

I've noticed the "Playing" property of an `AudioStreamPlayer2D` stays `on` until we force the refresh of the UI (e.g. clicking on another scene element).

I have a question regarding the `Update Mode`.
- Continuous: Update the property on each frame
- Discrete: Only update the property on keyframes
- Trigger: Only update the property on keyframes or triggers

The problem cannot be reproduced on `Trigger`, but while `Discrete` plays the audio "twice", `Continuous` triggers it every frame or so.

Is it an expected behavior or it should be fixed also in `Continuous` update?

**Comment by guilhermefelipecgs** [comment]
I'm start to think that my issue is not really a bug, as described here in the docs 
 http://docs.godotengine.org/en/3.0/classes/class_animation.html#enums:
"UPDATE_DISCRETE = 1 — Update at the keyframes and *hold the value.". In that case, the original problem was maded by me, to fix that I just need to disable loop when importing the audio:
![captura de tela de 2018-10-09 17-38-55](https://user-images.githubusercontent.com/1387165/46697139-56921480-cbea-11e8-82ce-a258c93ba218.png)

**Comment by guilhermefelipecgs** [comment]
So, I'm closing this.
