### ISSUE TITLE
Visual Scripting needs a better workflow

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19862]
Godot version:3.0.4.stable
OS/device including version: Win7 

Issue description:
There are only 3 zoomout levels and the text gets unreadable at 3. 

Some things that need to change in order to get a good workflow:

-Mousewheel zooming is a must for Visual Scripting. Panning and zooming is done a lot more than scrolling. Imagine it to be more like drawing software. Scrolling isn't really needed when there is a fast pan & zoom. I'd even say those 2 need to be on the mouse, since they are used that much.
-There needs to be a huge zoom-out something like 10.000 not just 3.
-Text needs to be readable in the lower zooms (1 to 10).
-RMB search or at least a keyboard key. It's importance is equivalent to code completion in trad. coding.
-Everything inside a comment node needs to move with it and the comment text needs to be visible at any zoom level. Otherwise there is no way to find, sort and move the huge blocks of code.
-The RMB seems to have 0 functionality atm. there should be at least a pop up menu. The mouse plays a huge role in Visual Coding and thus needs to be implemented really really well.
-Visible Function blocks, not just at the side as text.
-Collapsing selected blocks into a function with in and outputs.

The way the visual scripting is right now it's not really usable, not even for artists. VS is already slower than traditional coding without improvement it's only gonna be good for playing around with.

Steps to reproduce:
Just use the Visual Scripting editor.

**Comment by fire** [comment]
I've been working on these changes for the last two months. https://github.com/godotengine/godot/pull/18867

**Comment by fire** [comment]
This issue is a collection of existing issues.

1, 2 and 3

https://github.com/godotengine/godot/issues/6168

Can use control-f to search for all visual script nodes.

https://github.com/godotengine/godot/issues/20325 Describes a feature where the comment node groups the nodes and moves them as a group.

I tried to use the rmb, but it was deferred until another time.

Visible Function blocks one graph rather than the several currently. This work has been approved but there hasn't been any movement on it.

> Collapsing selected blocks into a function with in and outputs.

https://github.com/godotengine/godot/issues/6353
