### ISSUE TITLE
For exported file variables, give some way to open prompt in an specific file location.

### ISSUE THREAD

**Issue by rnoriega31** [godotengine/godot#19865]
**Godot version:**

For 2.1.5 and 3.1

**Issue description:**

Currently, if you have exported variables for say, music, and scenes, and images, and they are all located in different places then it's quite annoying to navigate the file select prompt. There's the "recently opened" tab but it's not optimal.

I suggest that something like:
```
export (String, FILE, "*.ogg") var BGM = "res://Resources/Audio/BGM/"
export (PackedScene) var any_scene = "res://Core/Modifiers/"
```
would immediately open the select file prompt in "res://Resources/Audio/BGM/" and "res://Core/Modifiers/" respectively.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
