### ISSUE TITLE
Open assets with a global search instead of file dialog

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#19866]
This is a feature proposal, which could be an option and cannot be done as a plugin.

Currently, when you want to assign a resource to a property, you have to navigate a file dialog to find it. In a large project it can be annoying to have to navigate files all the time, and the favourites sidebar isn't useful enough. Also, the file dialog is redundant with the file browser dock, from which we can already drag and drop assets to the property.

The idea is, instead of opening the file dialog when we click `Load`, have a quick-open search dialog instead, in which we can type a part of the name of the resource we want to load, a bit like what we have with `Ctrl+Shift+O`, but working with any resource. It would also display only compatible resources, of course.

This is also what Unity does when you choose to click on the property instead of the file browser, which has a globsearch too. It makes the following scenario very fast: import resource, type its name, find it immediately, assign. If we don't want to default to a globsearch, we could have one in the file dialog when trying to assign an asset.

**Comment by KoBeWi** [comment]
I've seen another issue where someone complained about search dialog in some part of editor and requested a file dialog. I guess there should be some search-file dialog to make everyone happy.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
