### ISSUE TITLE
Allow assigning animation resource to AnimationNodeAnimation

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19877]
**Godot version:**
`master` / 0ffec7daf

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
Since the old `AnimationTreePlayer.AnimationNodeSetAnimation` accepts an `Animation` resource as its argument, it was possible to use the API to override the default animation with a custom animation which wasn't added to the player.

However, the new `AnimationNodeAnimation` only accepts a `string` argument to change its animation, forcing the user to add the animation to the `AnimationPlayer` (which does not seem to work at this moment, as described in #19876).

Such a feature could be helpful, when the game can be extended by many different items with custom animations, for example. So, each item node can reference an `Animation` resource which can be assigned to the same one shot node at runtime.

**Comment by mysticfall** [comment]
I don't mean to be impatient, but is there a chance this may get fixed soon? It's a blocker issue for my use case, so I'd like to know if I better change my design or work on something else until it gets fixed.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
