### ISSUE TITLE
Add API to manipulate animation nodes in AnimationNodeBlendTree

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#19878]
**Godot version:**
`master` / 0ffec7daf

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
It seems that `AnimationNodeBlendTree` currently lacks any API by which one can enumerate child nodes that it contains. The old `AnimationTreePlayer` provided `GetNodeList()` method which can be used for such a purpose.

**Comment by slapin** [comment]
@akien-mga could you please mark this one and #22550 as C#/mono-related things to not confuse general public?
Thanks!

**Comment by mysticfall** [comment]
@slapin Does this (and also the other issue) work in GDScript? I vaguely remember seeing a commit that *may* solve this issue a while ago, which I haven't been able to test yet due to another blocker problem.

I'd less surprised if this issue was fixed in the current master branch than if it turns out it's been working in GDScript all along.

**Comment by mysticfall** [comment]
@slapin Just to make it clear, do you mean that there's an alternative for the removed `AnimationNode.GetInputConnection` API in GDScript?

Also, how do you, for instance, control `AnimationNodeBlend3` without using parameters in GDScript? The only additional members that the class in my current version defines asides from what it inherits are `Sync`, `IsUsingSync`, and `SetUseSync`, obviously not related to blending animations at all.

**Comment by slapin** [comment]
I guess c7e4527a88b90062e1d5fdea50c1b85cea3c8c6c is commit you're talking
about.
All properties bind/unbind setters were removed and replaced by generic
properties.

I never used anything like GetInputConnection ever at all, as I guess it is
something C#-only.
I always used nodes directly. I change "amount" value with all blend nodes.
Look at source code:

class AnimationNodeBlend3 : public AnimationNode {
        GDCLASS(AnimationNodeBlend3, AnimationNode);

        StringName blend_amount;
        bool sync;

protected:
        static void _bind_methods();

public:
        virtual void get_parameter_list(List<PropertyInfo> *r_list) const;
        virtual Variant get_parameter_default_value(const StringName
&p_parameter) const;

        virtual String get_caption() const;

        void set_use_sync(bool p_sync);
        bool is_using_sync() const;

        float process(float p_time, bool p_seek);
        AnimationNodeBlend3();
};

@@ -502,6 +497,7 @@ bool AnimationNodeBlend3::is_using_sync() const {

 float AnimationNodeBlend3::process(float p_time, bool p_seek) {

+       float amount = get_parameter(blend_amount);
        float rem0 = blend_input(0, p_time, p_seek, MAX(0, -amount),
FILTER_IGNORE, !sync);
        float rem1 = blend_input(1, p_time, p_seek, 1.0 - ABS(amount),
FILTER_IGNORE, !sync);
        float rem2 = blend_input(2, p_time, p_seek, MAX(0, amount),
FILTER_IGNORE, !sync);
@@ -511,31 +507,26 @@ float AnimationNodeBlend3::process(float p_time, bool
p_seek) {

 void AnimationNodeBlend3::_bind_methods() {

-       ClassDB::bind_method(D_METHOD("set_amount", "amount"),
&AnimationNodeBlend3::set_amount);
-       ClassDB::bind_method(D_METHOD("get_amount"),
&AnimationNodeBlend3::get_amount);
-
        ClassDB::bind_method(D_METHOD("set_use_sync", "enable"),
&AnimationNodeBlend3::set_use_sync);
        ClassDB::bind_method(D_METHOD("is_using_sync"),
&AnimationNodeBlend3::is_using_sync);

-       ADD_PROPERTY(PropertyInfo(Variant::REAL, "amount",
PROPERTY_HINT_RANGE, "-1,1,0.01"), "set_amount", "get_amount");
        ADD_PROPERTY(PropertyInfo(Variant::BOOL, "sync"), "set_use_sync",
"is_using_sync");
 }
 AnimationNodeBlend3::AnimationNodeBlend3() {
+       blend_amount = "blend_amount";
        add_input("-blend");
        add_input("in");
        add_input("+blend");
        sync = false;
-       amount = 0;
 }

 /////////////////////////////////

-void AnimationNodeTimeScale::set_scale(float p_scale) {
-       scale = p_scale;
+void AnimationNodeTimeScale::get_parameter_list(List<PropertyInfo>
*r_list) const {
+       r_list->push_back(PropertyInfo(Variant::REAL, scale,
PROPERTY_HINT_RANGE, "0,32,0.01,or_greater"));
 }
-
-float AnimationNodeTimeScale::get_scale() const {
-       return scale;
+Variant AnimationNodeTimeScale::get_parameter_default_value(const
StringName &p_parameter) const {
+       return 1.0; //initial timescale
 }

 String AnimationNodeTimeScale::get_caption() const {

Which means renaming "amount" to "blend_amount" for blend3 case.

And having to use $animation_tree["parameters/walk/blend_amount"] which is
sad but true.
I guess it was done this way so that you could make animation out of these
values.
It makes things more complex and simple at the same time and definitely
requires documentation.
And blame me for running custom engine version when testing for bugs.
Stupid me.

I guess SetParameter thing is C# equivalent for above code. I think it
could be bound more nicely into
hashmap-like array for C# for poor devs not to lose sanity completely.
But as you can access nodes, I guess you still can do
node["parameters/blah"] = x or something on the node directly
as they all inherit from AnimationNode. And I agree that change messed
meddy thing even more, so now it definitely
requires documentation.

**Comment by mysticfall** [comment]
@slapin Yes, that was the change that made me report (which I also mentioned above in an earlier comment). So, I believe now we are in agreement that this problem isn't Mono specific, since the commit replaced bindings for such properties like `get_amount`/`set_amount`/`amount`?

As to the `GetInputConnection`, it is required if you want to dynamically construct an animation root, like state machine, for example. Like I explained in the description, this issue specifically deals with such requirements, rather than general usage of `AnimationTree` API (which could be more relevant in the other issue we've talked about).

**Comment by slapin** [comment]
@akien-mga please ignore what I say about C# thing, C# makes thing even more messy, but it is because of change introduced by c7e4527a88b90062e1d5fdea50c1b85cea3c8c6c which prevents code from accessing animation tree node vars directly.

The change requires more testing as it produces some inconsistency in naming of variables.
So I guess the only way is if @mysticfall will look for cheesy stuff in code and finds breakage in there,
as this supposed to be working. Or otherwise just revert the commit and move on. This code needs some more thought and redesign anyway, because of how parameters are implemented. I guess at times they are missed and wrong value set. This happens because nobody still use AnimationTree.

```
commit c7e4527a88b90062e1d5fdea50c1b85cea3c8c6c
Author: Juan Linietsky <reduzio@gmail.com>
Date:   Mon Aug 20 13:38:18 2018 -0300

    Massive rewrite to AnimationTree. Many APIs changed in order to:
    -Reuse resources
    -Expose properties in AnimationTree
```

```#shell
slapin@slapin-pc:~/godot$ LANG=C date
Sat Dec 22 17:18:05 MSK 2018
```
facepalm...

Anyway if you want me to test something on master branch please provide something w/o mono dependency, as last time I built mono-enabled godot I was stressed too much.

**Comment by volzhs** [comment]
https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html
now I see where I should look for the parameters to control with script.

**Comment by mysticfall** [comment]
@volzhs Another option is to select the `AnimationTree` node in the editor and move your mouse over each parameter to see its full name.

I think it's actually quite a convenient feature to be able to control most aspects by specifying string parameters to a single node. It's just that there being no strong typed, node based alternative that makes it awkward in other situations.

**Comment by slapin** [comment]
Well, that doc is a lie - only prop name is reported, no path. Just tested
in current master.

**Comment by slapin** [comment]
The only way I found to find prop names is dump whole tree props and find
which ones are needed. But most of time i have to read C++ source code do
find what I need (i.e. for OneShot node). And sometimes nothing works at
all and I have to dump stuff in debugger to find what is going on. This is
so sickening that I had to revert all patches for props for now, it is not
worth the effort, as my process slowed down to crawl because of this.

**Comment by slapin** [comment]
The main problem is that node path names consist of default names only and
never renamed inside tree, so I have to use something like
"Navigation/OneShot 15/active" instead of how it was named in scene, so
better not to rename any nodes to keep sanity.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
