### ISSUE TITLE
Changing how sub-resource indexing works

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#19889]
I am pretty tired of having to janitor issues related to how Godot sub resources are saved. I think this system eventually needs to change. I think most Godot contributors don't really even understand how this works, so I will write down an explanation and why it needs to be modified:

## Resources and Sub-Resources

One of the neat things about Godot is the fact that resources can be embedded into scenes and other resources. This reduces the amount of files greatly and aids organization.

Resources inside scenes or other resources are stored in the files with an index. A sub-material may have a number (#1), used by a mesh, which will have another number (#2), and so on. Originally these numbers were assigned at the time of saving, but this was changed a few years ago due to complaining that saving was non deterministic and order of sub resources would change every time you saved.

To compensate this, a caching of these numbers inside of the resource was added, and they are assigned when a resource is loaded (via Resource::set_subindex / Resource::get_subindex). When saved, the numbers will be kept, so they are no longer necessarily incremental.

Resources have also a name property, but this property is only decorative as it serves no real purpose. It's not really used much either. It's mostly used when importing 3D geometry to reference the original materials, meshes and animations from the 3D modelling app.

When a resource loader loads a sub-resource (be it text or binary format), it will set the path to "res://path/to_resource.res::index". This is a small hack that is done so, if you load a scene/resource, keep a reference to a sub-resource but delete the original resource.. the next time this original resource is loaded, the sub-resource will not be loaded again and be reused.

## Limitations of the current system

1. Reloading of editor when a scene changes is very hacky, because there is no warranty that a resource in memory will be the same as the one  saved to disk. This leads to many bugs and editor not updating properly if you, as example, update git with the editor open.
2. Referencing an internal resource in a scene from another scene is not possible. You can assign this in the editor, but it will break when saving. Users have requested a few times that they would like to use meshes from an imported scene without having to save each to disk externally. This is not too useful (and maybe should be unsupported?) on text scenes.
3. Doing some export work on sub-resources is not possible. In the future, with Vulkan, it may be desired to make sure some shaders are precompiled before export. If the shader is in a sub-resource, this is not possible.

## Possible improvements

This system needs some clean up, so here are some ideas:

1. Deprecate the indices and use the name, and ensure the name is unique when saving. This will benefit 3D importers mostly, as they will properly reload stuff when the .dae, .gltf, etc. changes. It will allow referencing internal resources as well. This can be done increasing the format version, no need to break compatibility.
2. Allow ResourceLoader::load to load subresources, like "res://somemodel::mesh"
3. Change the editor focus-in code that reloads what has changed on disk (which works like this already), to also reload subresources. This will probably be slower in text resources, which will reopen the file a few times and seek a lot, but I guess it's unavoidable and for the sake of keeping a consistent state.
4. Eventually allow the export plugins to scan for subresource types.

**Comment by jahd2602** [comment]
Is https://github.com/godotengine/godot/issues/19984 related?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment]
I'm not sure - I know subresource id is still in use, and sometimes it changes and throws off version control, but is the proposal still valid or is it out of date?
