### ISSUE TITLE
Proposal: Use Kialo to discuss engine features

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#19885]
I've been looking on github issues for a while and I have a feeling that some discussion post would be better if they were organized in a different way. 
It becomes increasingly hard to keep track of what has been said, arguments and counter arguments. Many things get said twice and it becomes increasingly hard for people to not argument with the same reasons more than once.(For example, #19486)
My suggestion is to use [Kialo](https://www.kialo.com/explore), a platform made for constructive debate.

**Comment by razcore-art** [comment]
I just found out about this platform a couple of days ago as well (you probably did too if I were to guess :P, that's when they promoted it). It looks like really good, they're thinking of adding a subscription plan though, sell constructive debates, just something to keep in mind.

**Comment by toger5** [comment]
I don't know if the better structure for debates outweight the problems that come with using another platform.
Contributers would need to keep track to both. some ppl would not get what it's good for and continue to discuss on github. than we have even more duplicated arguments. (on kialo and on github).

But maybe it's worth a try.
@QbieShay nobody will be able to stop you from creating a discussion (on Kialo) for controversy topics like the plugin system. If it turns out to be used it could be used more frequently. If ppl start complaining it will get used less often.

**Comment by groud** [comment]
Unless it gets integrated with Github, I think moving part of the discussion outside, in another platform, is going to make finding answers even more difficult.

**Comment by akien-mga** [comment]
I think keeping discussions on GitHub is better, and I prefer not adding yet another commercial startup in our workflow, with potential changes to their terms and conditions that could impact our work.

We rarely need to have extensive/very organized discussion of features, as the process is mostly:
- Devs have their own original opinion, can discuss it sometimes on IRC
- Stream of comments from community members on GitHub rarely give a direct consensus (everyone wants something different), but helps developers' opinion grow organically
- Eventually, the consensus comes by itself once it has grown on the core devs, and little further discussion is needed

It's not optimal, but I'm not sure an external platform like Kialo would improve things much. It's hard enough to get a comment from @reduz on GitHub, good luck getting him on Kialo or <next best platform> :)

**Comment by QbieShay** [comment]
Sigh, closing this.
