### ISSUE TITLE
Feature: Ability to export input maps as variable

### ISSUE THREAD

**Issue by jrkd** [godotengine/godot#19892]
**Godot version:** N/A

**OS/device including version:** N/A

**Issue description:** 
This is a feature request to be able to include an additional export type to the existing list (http://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html#exports) 
eg. 
`export (InputMap) var MoveUpAction = "ui-player1-up" #defaults to player 1 map` 
`export (InputMap) var FireAction = "ui-player1-fire"`

This would display a list of currently set up actions from the Project Settings -> Input Map tab and would allow multiplayer games using different inputs for different players to be set via the editor. 

**Steps to reproduce:** 
This could be implemented by binding the existing `InputMap.get_actions()` method to an additional special case for export params.

**Minimal reproduction project:** N/A

**Comment by Shadowblitz16** [comment]
this is a great idea! 
I was wondering how to do this myself.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
