### ISSUE TITLE
CanvasItem should be able to convert any coordinates from global to local

### ISSUE THREAD

**Issue by valentinAlkan** [godotengine/godot#19923]
**Godot version:** 3.x

**OS/device including version:** All

**Issue description:**

CanvasItem should be able to convert any coordinates from global to local. Currently, a CanvasItem can only call get_local_mouse_position() or get_global_mouse_position(), which necessarily return the position of the mouse. It's possible to get around this by cacheing a get_global/local_mouse_position() for later use, but there is already a mechanism to convert mouse coordinates, so it should just be opened up. It's also possible to call make_input_local(), but I ran into this issue by trying to pass a coordinate directly between nodes, and recreating an inputevent just seems like a bad way to do things.

A good way to do it would be to allow those two functions to accept optional parameters, which is either a global or local coordinate, and that coordinate is simply translated if present, otherwise the function works as normal.

for example:
```
arbitrary_local_coordinates = get_local_mouse_position(Vector2 global_position=null)
arbitrary_global_coordinates = get_global_mouse_position(Vector2 local_position=null)
```

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by mrcdk** [comment]
`Node2D` already has a [`to_local()`](http://docs.godotengine.org/en/3.0/classes/class_node2d.html?highlight=Node2D#class-node2d-to-local) and [`to_global()`](http://docs.godotengine.org/en/3.0/classes/class_node2d.html?highlight=Node2D#class-node2d-to-global) functions for that. `Spatial` also has them.

**Comment by valentinAlkan** [comment]
oy. i should have kept going up the chain. thanks.

**Comment by valentinAlkan** [comment]
Wait, no the point still stands. Containers don't inherit from Node2D. So CanvasItem still needs a way to convert coordinates.

**Comment by eon-s** [comment]
CanvasItem does not know about position so it would not be able to do that (does not make sense for that class), Control can copy Node2D methods, though.

**Comment by valentinAlkan** [comment]
So how do you position a graphnode inside a graphedit if the graphedit has no knowledge of where the mouse cursor is?

**Comment by vnen** [comment]
You still can do it by applying math with the transforms.

**Comment by groud** [comment]
> You still can do it by applying math with the transforms

That's exactly how you should handle that. 
IMHO, I think adding helpers for such thing is kind of a bloat. It's flexible & simple enough like that.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
