### ISSUE TITLE
Enable EditorPlugin to add a toggleable sub-toolbar below the main toolbar.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#19922]
**Godot version:**
Godot 3.x

**Problem:**
Currently, if someone does `add_control_to_container(CONTAINER_TOOLBAR, node)`, then it places new elements on the main toolbar (clearly). However, if a single plugin had a toolbar segment with several new buttons on it, this solution doesn't properly scale well when you start adding multiple plugins. The toolbar could get completely clogged needlessly.

An example, from a GDNative builder plugin I am working on:

The rightmost `ToolButton` will toggle the visibility of the toolbar.

![36538512_2070584669618868_3843288013798899712_o](https://user-images.githubusercontent.com/16217563/42191056-44f0357a-7e26-11e8-91c2-565760d9dc4b.jpg)

![36578411_2070584626285539_6879537374733271040_o](https://user-images.githubusercontent.com/16217563/42191043-3389f92e-7e26-11e8-9454-ff857d4d2df4.jpg)

However, there is so much content that it takes up a huge amount of space and even shifts the centered "2D, 3D, Script, AssetLib" buttons all the way over until they're practically only a quarter of the way across the screen.

**Suggestion:**
I recommend we define a section in the toolbar that is allocated for toggleable `ToolButton`s (like the one showcased above) but which are all part of the same `ButtonGroup`. Whenever one of them is toggled on, a control provided by the user is stuffed into a second `HBoxContainer` that exists below the main toolbar and which is only displayed while one of these buttons is toggled on.

Thoughts?

I was originally thinking I would just add this functionality into my plugin directly, but then I figured this feature might actually be really useful for a variety of plugins, so I'd really rather make it a part of the engine rather than create a new plugin dependency that other plugins might use.

I could even implement the PR for it myself. Though I'm not sure where I would store the ButtonGroup resource. EditorSettings maybe?

**Comment by toger5** [comment]
having multiple menue bars at the top is quiet a new concept for the godot ui. Although i see that this would look really cool I might still advocate to just use docks for those kind of things.

Although having the option as a plugin dev is really nice for sure.

What abput just swapping the main top menue bar? So each plugin added to the top bar gets one button and than you can tab through different menue bars.

**Comment by willnationsdev** [comment]
@toger5 

> What abput just swapping the main top menue bar? So each plugin added to the top bar gets one button and than you can tab through different menue bars.

Well, at least, for the plugin functionality I'm going for, I wouldn't want to have to toggle the main menu bar off. I'd want to be able to see both at once. The idea of having to toggle it on to compile the C++ source code, and then toggle it off in order to be able to run the scene sounds weird to me.

**Comment by eon-s** [comment]
A place for custom toolbar would be nice, even if the editor won't use it, docks have no more space to add things (2 columns take too much space already).

**Comment by eon-s** [comment]
And by custom toolbar I meant, something below the editor/play/viewport level, that can be filled with anything (buttons, menus, etc.).

**Comment by willnationsdev** [comment]
@eon-s I'm trying to think what the best way of activating would be though. Assuming we allow users to define their own toolbars, we should probably really just give them free reign to decide when to show/hide it. Leave it to their discretion.

**Comment by aaronfranke** [comment]
This would be a good idea as an option for custom toolbars and buttons, but I think it's best for the default UI to only have a single bar at the top, to keep it simple.

**Comment by willnationsdev** [comment]
It was discussed more in the PR, but I'm pretty sure the decision at this point is that the valid use-case for it happens so infrequently that you wouldn't have enough plugins properly taking advantage of it to keep it from looking bad. Because there are plenty of viable alternatives (I've moved my toolbar into the bottom panel which is honestly working quite well), there isn't much of a need to endorse this feature.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
