### ISSUE TITLE
Deleting video (webm) from editor. Error: Being used by "Godot Engine Editor"

### ISSUE THREAD

**Issue by CloudAlRio** [godotengine/godot#19924]
**Godot version:** 3.1.dev.custom_build.ecee0c9-

**OS/device including version:** Windows 10 x64

**Issue description:** After importing webm video, assigning it to VideoPlayer, can't delete it. 

Not really sure if this is a bug or intended behaviour.

**Steps to reproduce:** Import webm (or any) video. Create scene with VideoPlayer. Drag and drop video into VideoPlayer's VideoStream. Try to delete video from FileSystem view(dock).

**Comment by akien-mga** [comment]
I think it's normal behaviour, Webm videos are played directly from the file, so Godot needs to have a file handle. And Windows won't let you delete a file as long as a program has a handle on it.

It's even more valid after #19937 since video files will no longer be "imported" at all (they were badly imported previously, the "importer" was just assigning the local file to a VideoStream, which is the job of a loader).
