### ISSUE TITLE
_init function of autoload executes when opening editor

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#19935]
**Godot version:**
Current Master

**OS/device including version:**
Arch Linux, updated recently™

**Issue description:**
The `_init` function runs in singleton scripts are running the editor opens. This isn't really a problem as for singletons, `_init` is effectively `_ready`, but I do find it a little strange.

**Minimal reproduction project:**
[singletontest.zip](https://github.com/godotengine/godot/files/2160153/singletontest.zip)
If you open Godot from a terminal, you will see it print "WHY DID I RUN". It does not appear inside godots UI as it runs before the godot editor is open.

**Comment by vnen** [comment]
They are instanced in editor and added to script globals, so they can be easily referenced in scripts. If this is really an issue I can change the system to avoid it.

**Comment by vnen** [comment]
BTW, if you are preloading things in the script, they will be loaded if the script is loaded, even if it's not instanced. So I don't think it's possible to avoid the issues, in this case you should not use `preload()` but `load()` instead.

**Comment by akien-mga** [comment]
> And static checks. But I guess it only needs to be compiled, not instanced. I'll disable the instancing for non-tool scripts then.

Wasn't the idea also that autoloads should be available in the editor for the use of tool scripts?

**Comment by darco89** [comment]
Hello everyone (who's still kicking it after 6 years), 
I understand that this is closed, but I'm just looking for confirmation. 

I have a dbcontroller class (SQLite) that is used by a few EditorScripts of my own. 
Whenever I open this project in Godot, the SQL connection is set and opened (I close it too). I didnt really want this to happen. I can close it, but the connection was made, regardless.

Is this controller's _init function running when I open the editor, just because it is referenced in an EditorScript? 
If so, is there a way to make sure it won't run, until I execute the EditorScript?

Thanks for the clarification in advance, best regards
