### ISSUE TITLE
Suggestion: better way to change variable and function names

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19954]
Godot version: 3.0.4 stable
OS/device including version: Win 7

Issue description:
I'm not sure if any text based editor does this but when creating variables and functions in ue4:
![ue4 variables](https://user-images.githubusercontent.com/40721994/42264358-b5a9eac2-7f70-11e8-9bb1-99e921008536.jpg)

The user creates them in a special drop down menu. The great thing about this is if the name of a function or variable is changed the editor automatically updates the name in the whole project.

I'm somebody that changes var and funct names a lot. They might start as speed then become MaxSpeed then Char1MaxSpeed then Char1MaxYSpeed etc. I hate searching and replacing var and function names
because if I forget to use a name like var_speed searching and replacing speed can destroy the code and then there is a lot of manual searching and fixing involved. I know this is mostly a beginner problem but a feature like this would help beginners and/or scatterbrains like me a lot.
 
I'd love to see this with the Visual Scripting but I think this could also be done in the text based coding editor. 

A user could write something like:
 ** VAR// **

const SOMECONST
var someVar

  ** //VAR ** 

And the editor automatically checks for changes to the names and changes them automatically everywhere in the project.

**Comment by vnen** [comment]
In Visual Script is relatively simple to change all the references in the current script when you change the name of a variable or function.

With GDScript something else must be done and it needs another step to let the user uncheck what was incorrectly detected.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
