### ISSUE TITLE
On Intel Haswell IGPs on Windows 8, materials with normal maps appear overly dark (3D)

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#1995]
This is reproducible with this demo: https://github.com/Calinou/fps-test

This happens in both editor and game.

Note how the pillars are overly dark, but the grass isn't (it has no normal map in use).

**Comment by agameraaron** [comment]
I can confirm this is true for me with a Haswell, but with Linux Mint 17.1
![screenshot-window-2015-05-27-230552](https://cloud.githubusercontent.com/assets/12471157/7853022/072128c2-04c5-11e5-9c3f-0ae78f2b61a0.png)

**Comment by Calinou** [comment]
> I can confirm this is true for me with a Haswell, but with Linux Mint 17.1

I don't think the Platformer 3D demo uses any normal maps.

**Comment by agameraaron** [comment]
Oh okay. I couldn't figure out what was wrong with your demo because I had no frame of reference, but I'm guessing grass was supposed to be there and I saw none. More importantly it runs awfully slow. I could not get it to chug faster than 4 frames a second. Might be on my end as I am not using the best drivers, but the 3D demos that come with it work fine for me.

**Comment by Calinou** [comment]
It seems to affect only TestCubes, not models imported with Better Collada.

I will close this until I get better confirmation of this bug.
