### ISSUE TITLE
Better name for "Makes sure the objects children are not selectable" + tooltip info

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#19951]
Godot version: 3.0.4 stable
OS/device including version: Win7

Issue description:
I've tried to assign the "Makes sure the objects children are not selectable" ui button a keyboard key.
But I can't find it under editor setting -> shortcuts:
![makes sure](https://user-images.githubusercontent.com/40721994/42261373-526628ac-7f68-11e8-8a63-78fff8554936.jpg)

How about disable child object movement or restrict object/node movement?
Also it's used soooo much it needs a keyboard key and an easy way to find it.
Here is how krita and almost every software does this:
![krita movet](https://user-images.githubusercontent.com/40721994/42261669-4348b05a-7f69-11e8-8188-c2bbcbe6f911.jpg)

When hovering above an element/button there is a short description name, the shortkey is shown inside () and the user can find it without any problems to change the button if needed.

This tooltip information is very very important I can't believe you haven't done this already.

Steps to reproduce:
Use the editor

**Comment by guilhermefelipecgs** [comment]
Godot already works like this:
![captura de tela de 2018-07-04 13-17-29](https://user-images.githubusercontent.com/1387165/42287455-c5a1ee54-7f8c-11e8-9691-e98df3f527c3.png)
![captura de tela de 2018-07-04 13-17-58](https://user-images.githubusercontent.com/1387165/42287457-c681d3c0-7f8c-11e8-9dbc-f4d52d6ef553.png)
If you can't find the shortcut it is because it still doesn't exist. In this case, it needs to be created.

**Comment by BrahRah** [comment]
That still leaves the problem that the button can't be found with a search.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
