### ISSUE TITLE
[TRACKER] Improving editor startup time

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#19979]
The editor startup time is not too bad, but there is (of course) play for improvement:

Pls comment below if you have ideas which is slowing down the editor startup and how it can be improved.

### Possible Improvements:
 - [ ] Icon svg to png conversion on every startup could be cached #19887 

### Ideas that could slow down startup:
 - Is there any font preparing done on startup?
 - build with `target=release_debug use_lto=yes` might increase startup time.
 - editor is slower to start on Windows with nVidia cards (driver issue with power mode) #11030

**Comment by Calinou** [comment]
In my experience, the editor starts up faster if you build with `target=release_debug use_lto=yes`.

**Comment by Zylann** [comment]
I know that probably due to https://github.com/godotengine/godot/issues/11030, the editor is slower to start on Windows with nVidia cards. On my laptop if I launch it using the less-powerful Intel graphics I can get it launched a lot faster.

**Comment by toger5** [comment]
It would also be really cool, when we could add some debug prints during startup to see what parts take how long to launch?

**Comment by Calinou** [comment]
A simple way to improve perceived performance when loading the editor would be to adapt the splash screen's background color to match. This should be done dynamically, so that it can match both dark and light editor themes (including gray or solarized variants). When using a light theme, the logo should use dark text as to be readable, and sponsors should be put on a dark background somehow.

**Comment by lawnjelly** [comment]
Just throwing these in here rather than starting a new issue, these are some profiles for master (4.x) I made today for starting the project manager, and the editor. These are release builds on Linux.

**Project Manager**
![profile_master_project_manager](https://user-images.githubusercontent.com/21999379/168653829-96f78f07-7f4c-464a-ac7d-1203e86eb587.png)

**Editor with simple project (GLES3)**
![profile_master_editor_startup](https://user-images.githubusercontent.com/21999379/168653879-2d95b24a-53f2-4ae1-bd83-7cad6ad95419.png)

Notable it seems to spend a good amount of time in the font code.

**Comment by bruvzg** [comment]
#60781 is not intended to make the editor start faster, but to avoid stutters when visual scripts/shaders are used (MSDF fonts are slow to rasterize).

**Comment by KoBeWi** [comment]
This is labeled as tracker, but it's not really a tracker.
Also it's very outdated.

**Comment by lawnjelly** [comment]
Yes I would close this as outdated.

**Comment by KoBeWi** [comment]
Closing. I'd suggest opening a new issue that is up-to-date and is a real tracker. Though it would require some proper profiling to identify causes of slowdown.
The editor is arguably slower to start now, but the startup is more responsive, because all loading steps are properly communicated.
