### ISSUE TITLE
event is InputEventAction fails

### ISSUE THREAD

**Issue by CrazyHat62** [godotengine/godot#19987]
```
func _unhandled_input(event):
	if event is InputEventAction: #this fails - was working
	    if event.is_action_pressed("ui_right"): # doesn't get here anymore
```

Searched other issues but they did not seem to apply
**Godot version:**
Steam  install - Godot Engine v3.0.4.stable.official.d916135

**OS/device including version:**
Windows 10 - 64 bit 

**Issue description:**

The code above worked on the latest version on an existing install. I had installed Godot from steam originally on an earlier version, I has also added keys to the input map. I had upgraded as steam does that automatically.
I freshly installed windows last night, downloaded the same antivirus I used before (avira). I downloaded Steam and installed. I used it to Install Godot 3.
I copied code a saved (yesterdays) godot folder from a 'memory stick' and place in documents and reimported. 
the InputEventAction now needs to be commented out for the code to work.

**Steps to reproduce:**
fresh install of windows. fresh install of steam. install latest Godot 3 (from steam). try the code 

**Minimal reproduction project:**

[RommysGauntlet.zip](https://github.com/godotengine/godot/files/2167517/RommysGauntlet.zip)

**Comment by CrazyHat62** [comment]
I suspect it may be due to a missing dependency 
or the fact that I didn't change the input map yet!

**Comment by akien-mga** [comment]
Are you sure this code ever worked as is? I don't think `InputEventAction` is ever sent directly to `_input` or `_unhandled_input`, otherwise you'd get duplicated events (e.g. if the <kbd>Left</kbd> key is bound to the `ui_left` action, you'd get both an `InputEventKey` and an `InputEventAction` at the same time referring to the actual same event).

You can just remove your `if event is InputEventAction` check and it will work though, as `event` will be `InputEventKey` and its `is_action_pressed()` will check if that key event corresponds to an action in the InputMap.

**Comment by CrazyHat62** [comment]
Thanks - this was my misunderstanding. No, now I'm not sure it ever worked.  Sorry I took so long to respond
