### ISSUE TITLE
Assigning NodePath in an exported array in the inspector crashes Godot (Regression)

### ISSUE THREAD

**Issue by jahd2602** [godotengine/godot#20005]
**Godot version:**
master @ 8bb90fd5f3b9819bc3bc475e8b9f36c012d6c855

**OS/device including version:**
Windows 10 Home Version 1803 Build 17134.147
Processor i9-8950HK
Nvidia GTX 1050 Ti

**Issue description:**

This is a bug related with https://github.com/godotengine/godot/issues/20004
After selecting NodePath with the pencil, and clicking Assign, selecting a node as a value of that variable crashes Godot.
This was working fine in 3.0.2.

**Steps to reproduce:**
1. Create a node with a script with:
```gdscript
export(Array, NodePath) var triggerTargets
```
2. Assign a node to an element of the array
![](https://i.imgur.com/N6KM3pb.jpg)
3. After selecting the node, godot crashes [with this stacktrace](https://pastebin.com/XZVT1bC8)

**Comment by bojidar-bg** [comment]
I remember observing this as well; probably caused by the nodepath editor not knowing from which node/resource to start.

**Comment by OliPerraul** [comment]
I have observed something else. Exporting a regular NodePath in the inspector and retrieving the associated node works. However exporting an array containing nodes and trying to `get_node()` on those returns null.
![image](https://user-images.githubusercontent.com/24371247/45524785-3a8f8480-b79e-11e8-8239-9fd3c5369a2c.png)

**Comment by OliPerraul** [comment]
I have also observed instances where doing get_node(path), from an exported NodePath returns null since selecting the Node in the inspector retrieves a relative path. I believe Godot really needs a better way to achieve dependency injection rather than relying on the Node's paths. Could't this be handled internally? Why coulnt we just assigned a Node as an export variable. This clearly seems to be the most common use case for NodePath and get_node() anyways.
