### ISSUE TITLE
Make enums in @GlobalScope accessable

### ISSUE THREAD

**Issue by JacobTheHeartless** [godotengine/godot#20015]
**Godot version:**
3.0.4(Stable, Official, d916135)

**OS/device including version:**
Machine : LENOVO Lenovo B50-80
OS : Microsoft Windows 7 Ultimate (x64) Build 7601
CPU : Intel Pentium 3825U
RAM : KHX1600C9S3L/4G
GPU : Intel Broadwell-U GT1 - Integrated Graphics
AUDIO : Intel Broadwell PCH-LP - High Definition Audio Controller

**Issue description:**
I can access all values of enums stored in GlobalScope but I'm unable to access enum itselfs. It can be very useful to access enums like Error for bug handling and reporting. Enums JoystickList, KeyList and ButtonList can be very useful because InputEvent contains Id of key/button but not its name. With access to GlobalScope enums I can use `str(KeyList[16777221])` To get "KEY_ENTER". Anyway, why I can't access it ? Access to GlobalScope enums can be very useful in many ways.

**Steps to reproduce:**
Not any, It is request to make enums in GlobalScope accessible

**Minimal reproduction project:**
Again, not any. It is feature request.

**Comment by vnen** [comment]
What you describe is not simply "accessing the enum", but "converting an enum value to string". This is a whole new thing because C++ doesn't provide string names for the enums.

This could be solved by adding magic to the template-binding macros, but it's not simply a flick of a switch to enable.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by cgbeutler** [comment]
Google took me here. Was a proposal ever created for this? I can't seem to find one, but checking just in case.
If this is superseded by changes in 4.0 or something, that would be good to know too...
Currently, named enums can be treated as dictionaries. GlobalScope enums are nameless, so dict operations are, sadly, not usable.
