### ISSUE TITLE
Two files of the same name should be desambiguified in the editor tabs

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20029]
Godot 3.0.4

In a project, when two scripts or two scenes from different locations have the same name, tabs are listing them with the same name, however it makes it hard to tell which is which:

![image](https://user-images.githubusercontent.com/1311555/42415764-79552cb4-8252-11e8-9a12-509785d7e69b.png)

![image](https://user-images.githubusercontent.com/1311555/42415777-00d78ae2-8253-11e8-9102-ab4b8f58ce69.png)

In that case, it would be better if the scene or script editors could desambiguify what tabs are showing, by including the parent folder in the name until all tabs have a different title.

For example:
![image](https://user-images.githubusercontent.com/1311555/42415775-d830e8c2-8252-11e8-867e-790099c0bb8b.png)

**Comment by rileylyman** [comment]
I will take this if no one else has already.

**Comment by rileylyman** [comment]
@MelvinWM sure, go for it.

**Comment by MelvinWM** [comment]
I have looked into it, and I have some comments and questions.

First off, **for scripts in the script overview, there are already options in ```Editor Settings -> Text Editor -> Open Scripts -> List Script Names As``` for showing the immediate folder as well as the full path.** For the script overview at least, this makes it somewhat less useful to support what I will call "disambiguated names" as suggested in this issue, though it would still be useful.

Now, the questions:

**1: Reg. the script overview and the editor settings for "List Script Names As", an open question is how the "disambiguated names" functionality should interact with it.**

![screenshot_editor](https://user-images.githubusercontent.com/26661991/51078531-9c152080-16b6-11e9-9029-6dd88c2d72c9.png)

Should these settings be removed? Should they be preserved and the "disambiguated names" functionality replace the "Parent Directory And Name" option (which always shows the immediate parent folder in the listing, whether needed or not, unless it is a top-level script)? Or replace both "Name" and "Parent Directory And Name"? Should the settings be kept as is and "disambiguated names" be dropped for the script overview?

**2: Implementations of ```get_name()``` for class ```ScriptEditorBase``` typically includes unsaved status indication (the "(*)" appended to script and scene names when not saved).** This will as far as I can see complicate certain aspects of the functionality to be implemented, as seen in #20930, and it would be nice to avoid this complication, especially since it might make it easier to avoid code duplication between the script overview and the scene tabs. One approach would be to remove the addition of the saved status text in  ```get_name()``` and then handle the addition of the unsaved status indication in the different places  ```get_name()``` is used, though that might be overkill (another option would be to rename it to  ```get_name_with_status()``` and create another method called  ```get_name_without_status()``` and handle it from there). This issue is only relevant if the disambiguated names functionality is implemented for the script overview.

There seems to be 3 classes that inheret from ```ScriptEditorBase```, namely ```ScriptTextEditor```, ```TextEditor``` and ```VisualScriptEditor```.

**One overall approach** would be to leave the script overview as is, and then only implement the "disambiguated name" functionality for the scene tabs, preferably in such a way that the functionality can be reused without code duplication later for the script overview (or other) if desired.

**Comment by mitchcurtis** [comment]
For reference, there's some information about how a different IDE solved this here:

https://github.com/godotengine/godot/issues/27978

**Comment by CyanBlob** [comment]
My expectation would be that there's a separate option beneath the "List Script Names As" option. This new option should be a boolean option titled "Disambiguate File Names", or something to that affect. If the user has chosen "Full Path" as the value for the previous option then the new option shouldn't ever affect them, but I don't see the harm in having it be present anyways. I don't think that we need to modify the current dropdown.

**Comment by Zylann** [comment]
Still being bothered by this, and I think that regardless of whatever option there is to display tab names, there could also be a tooltip when moving the mouse over the tab, showing the full path. At the moment, scene tabs show nothing. The only way to know is to right-click and use "show in file system".

**Comment by Calinou** [comment]
I did this for scene tab extensions in #35320.

> At the moment, scene tabs show nothing.

They show a thumbnail, but it's often broken. It would probably be better to show the full path instead.

**Comment by Zylann** [comment]
. They show a thumbnail when hovered, but it's often broken. It would probably be better to show the full path instead.

True. Interesting, because at the time I posted, they showed nothing when I tried to hover them.

**Comment by Zireael07** [comment]
Most of the time thumbnails don't work, so a path would be a better use of the tooltip.
