### ISSUE TITLE
Add a local version of apply_impulse (RigidBody)

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#20031]
https://godot.readthedocs.io/uk/latest/classes/class_rigidbody.html

**Godot version:** 3.0.4

**Issue description:**

Currently, there is no local version of `apply_impulse()`. This function currently only applies an impulse on the global coordinate system. What I would like is for a new function, perhaps named `apply_impulse_local()`, to be added, which applies an impulse in local coordinates. Using `apply_impulse_local(Vector3(0,0,0), Vector3(0,0,-1))` would always push the object "forward", regardless of which direction it was facing.

This would be in a similar vain to `translate()` vs `translate_object_local()`. The first works with the global coordinates, while the latter works with the object's local coordinates. If you used `translate_object_local(Vector3(0,0,-1))` then it the object would move "forward", regardless of which direction it was facing.

My current work-around (note that it's in C#):

    ApplyImpulse(Vector3.Zero, transform.basis.Xform(Vector3.Up * movementScale));

Proposed syntax to do the same thing (also C#):

    ApplyImpulseLocal(Vector3.Up * movementScale);

**Comment by sdfgeoff** [comment]
With applying impulses, specifying "local" can be confusing because:
 - Are both the position and 'force' vectors local?
 - Or is it just the position
 - Or is it just the force?

Do you have four different functions for the four different options? Or do you pass in two flags to set them? Either way, it is likely to confusing. The "workaround" you post is exactly what the engine would do, so to me, it is the correct way to do it.

**Comment by jdjddjdj** [comment]
Am recreating a space game using thrusters - the ability to apply forces locally along the objects z easily would be very useful. (for me)

+1

**Comment by KingKone** [comment]
+1

**Comment by aaronfranke** [comment]
@jdjddjdj @KingKone GitHub has the ability to thumbs-up a post instead of commenting "+1".

**Comment by bitdom8** [comment]
Please, find a solution to this!

**Comment by jdjddjdj** [comment]
Hey Aaronfranke!  yes - will use the thumbs up button next time : ) Doh!

I am a non-coder, but reasonably fluent in Max/msp and QC. All of my scripting is using Visual script - Is there any chance you (or anyone) could show me the "translated into visual script" version of the example you posted at the top?

I have paused my work in godot based on not being able to figure this one single (deal killing) problem out. Attached is a pic my current Visual Script. Everything works exactly as i want except the (non)local nature of the thrust

Your snippet is below
thanks for any suggestions
jd

*************
My current work-around (note that it's in C#):
ApplyImpulse(Vector3.Zero, transform.basis.Xform(Vector3.Up * movementScale));
*************



![Godot Local Thurst problem](https://user-images.githubusercontent.com/37357469/71933819-a43c5a80-3168-11ea-8164-fa4ca85e2506.jpeg)

**Comment by bitdom8** [comment]
@jdjddjdj Thanks. That will fairly nicely work...

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
