### ISSUE TITLE
musl libc compatibility: isnanf vs. isnan

### ISSUE THREAD

**Issue by MazeChaZer** [godotengine/godot#20036]
To determine if a float is not-a-number, glibc offers `isnanf`. musl libc only has `isnan`, which supports floats and doubles. Godot currently uses `isnanf`, which makes it only compile with glibc. Is it possible to check the libc implementation in the preprocessor to handle this better?

https://github.com/godotengine/godot/blob/ea473594086ebc4d0f5ec8d3cb5fac1607909571/thirdparty/thekla_atlas/nvmath/nvmath.h#L202

**Comment by ronchaine** [comment]
finite, finitef, finitel, isinf, isinff, isinfl, isnan, isnanf, isnanl are all obsolete (and have been for quite a while), so the preprocessor should parse nvmath.h as

`#elif NV_OS_DARWIN || NV_OS_FREEBSD || NV_OS_OPENBSD || NV_OS_ORBIS || NV_OS_LINUX`

instead of adding additional `elif NV_OS_LINUX` and then including the obsolete headers.

This works for both glibc and musl.

**Comment by akien-mga** [comment]
@ronchaine Feel free to PR that, and ideally do it upstream too: https://github.com/Thekla/thekla_atlas

**Comment by ronchaine** [comment]
It'll take me until the weekend before I can address this, but yeah, I can do PRs for both.
