### ISSUE TITLE
Logarithmic Z-Buffer

### ISSUE THREAD

**Issue by junky89** [godotengine/godot#20050]
**Godot version:**
Master branch, hash: ecee0c92ff86911fa50e745b4ab98196e0d2afe4

**Issue description:**
I'm developing a planetary game (specifically using a quadtree planet) and I need to achieve better far distance rendering (without z fighting problems) while not loosing too much near clip distance. 
One approach would be to use a logarithmic scale as in [here](http://outerra.blogspot.com/2012/11/maximizing-depth-buffer-range-and.html). 

I would like to implement it in godot, but I'm afraid that this will require little changes over quite a lot of places, I am right? I think it could be a good optional feature for godot, for not a big effort (we just need to control the encode and decode of the depth buffer).

I would like to ask if anyone has tried this before? Any advise? Changing just the drivers/gles3 (I'm only interested in gles3 for the moment) shader code would be enough or there are some hidden code somewhere else? It's even supported to write to the depth buffer in godot (gl_FragDepth)?

Any words of wisdom will be greatly appreciated.

**Comment by MrMinimal** [comment]
I have a need for this as well, three.js has a logarithmic depth buffer as well as a [side-by-side comparison example](https://threejs.org/examples/webgl_camera_logarithmicdepthbuffer.html).
Planet rendering is needed in multiple projects, I see a potential community project here.

**Comment by rileylyman** [comment]
Did this ever get implemented?

**Comment by raymoo** [comment]
I'm guessing that this is something that would now be requested in https://github.com/godotengine/godot-proposals

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
