### ISSUE TITLE
Auto generate(statically) collision polygon2D if the collision shape is scaled

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#20067]
**Proposal**

Have an easy way to generate a collision polygon from a scaled collision shape. (And maybe add a warning that says "Shape is scaled").
If debug collision is enabled, shapes are shown scaled but they collide as if they weren't scaled.

**Comment by Zylann** [comment]
What if we changed gizmos to work like the new 2D collision shapes? They could directly work on the shape rather than the Spatial.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
