### ISSUE TITLE
Input.IsKeyJustPressed that works like Input.IsActionJustPressed (C#)

### ISSUE THREAD

**Issue by ChrisDill** [godotengine/godot#20138]
**Godot version:**

3.0.4 stable

**OS/device including version:**

Windows 10 Home

**Issue description:**

In C#, there is no ```Input.IsKeyJustPressed``` that works in a same way as ```Input.IsActionJustPressed```.
There is ```Input.IsKeyPressed``` but that only checks if the key is held down not just pressed.

**Example:**
```if (Input.IsActionJustPressed("ui_left")```
There should also be
```if (Input.IsKeyJustPressed((int)KeyList.Left)```

**Comment by vnen** [comment]
I believe there's quite an overhead to keep this information for every possible key.

**Comment by Zylann** [comment]
Why not use `_input`? Many people seem to keep using `_process` all the time for some reason.

**Comment by aaronfranke** [comment]
@Zylann Because not everyone is used to the Godot workflow. There isn't an `_input` equivalent in Unity. Users may be confused of how to best structure their game in Godot.

Personally I don't see a need for this. If you use something often, make it an action. Storing the previous state of every key would indeed be a large overhead. I suggest closing.

**Comment by akien-mga** [comment]
I agree that this doesn't strike me as a good addition, as @vnen mentions that would add some overhead for something which most people shouldn't need to use. Actions are meant precisely for such use case.
