### ISSUE TITLE
Add basic template by default when creating new shader file

### ISSUE THREAD

**Issue by msmshazan** [godotengine/godot#20152]
Add basic template by default when creating new shader file inorder to reduce amount of typing.

**Comment by KoBeWi** [comment]
Typing aside, I pretty much always need to look up how to define shader type and how to start, because I forget (XD), so a template would be really helpful.

**Comment by KoBeWi** [comment]
So, anyone ideas how this could work? Obviously we need templates for different kinds of shaders. However, the Shader is a Resource which doesn't have a fancy menu like when creating scripts, so we can't simply add some templates and let the user choose. How to choose them is a problem (single template is useless, because one may need different shaders, and I don't think the shader can tell where it is created from, to have a context).

My 2 ideas are:

- have every new shader include all possible code for different shaders (e.g. both `void vertex` and `void fragment`)
- add a menu in Shader Editor called "Templates" where you can choose a template

The former just sounds cumbersome. The latter would be easy to do and easy to spot, since shader editor doesn't have many menus, but I'm not 100% convinced that would be the best option.
