### ISSUE TITLE
Make scene root needs a warning

### ISSUE THREAD

**Issue by mrcdk** [godotengine/godot#20196]
**Godot version:**

Godot master https://github.com/godotengine/godot/commit/de910f8c26407ea37b97a94a6fb1a8731d3694c6

**Issue description:**

The new `Make Scene Root` functionality needs a warning before being applied. It's a destructive change that, while it can be undone, may be unexpected to the user. A warning popup telling the user of the changes or consequences before applying the changes would help.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
