### ISSUE TITLE
Opening collada file as scene issue

### ISSUE THREAD

**Issue by Rayzorblade23** [godotengine/godot#20224]
**Godot version:**

3.0.5 Mono

**Issue description:**

![image](https://user-images.githubusercontent.com/41338248/42826240-38fdc042-89e4-11e8-9d72-d319ce468690.png)

Can't delete nodes from scene after opening object as "New Inherited" but I can delete nodes when opening with "Open anyway". This seems to contradict the tool tip.

**Steps to reproduce:**
Import a .dae exported from Blender via Better Collada Exporter and open in Godot.

**Comment by KoBeWi** [comment]
This is not a bug, that's just how inherited scenes work. You can't delete nodes from them. It's more like a missing functionality. Proposals are now tracked in the [official proposal repository](https://github.com/godotengine/godot-proposals). If this issue is still important, fill in a new feature proposal (about deleting nodes in inherited scenes).
