### ISSUE TITLE
GDScript: Some way of telling if funcref.call_func is about to be called on a non-existent function

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#20237]
I use funcref quite a bit to convert a string name of a function into a call to the function but from what I can tell there is no way to tell if the initial call to funcref has returned a real function or not. In the absence of a way to catch exceptions, it would be good if there was a way to tell if funcref was dealing with a non-existent function.

**Comment by kakoeimon** [comment]
Checking out the source :  https://github.com/godotengine/godot/blob/34c988cfa92f19c232b65990704816ba1c7d2622/core/func_ref.cpp

You can see at line 43 that it returns a variant if the object is null, otherwise it will return the return value of the called function.

The returned variant is of type nil (null). (The defaul Variant() call is of type nil, you can see this in this file : https://github.com/godotengine/godot/blob/4f5a7ebaecfcf00cf1e5c4af4b20034f0dcecd29/core/variant.h
line 413

I believe that if you check the returned value for null, will solve your problem.

**Comment by bojidar-bg** [comment]
Consider using `has_method` for checking if the method exists.

Maybe `FuncRef::is_valid` would be a nice addition to the API.

**Comment by kakoeimon** [comment]
@bojidar-bg FuncRef::is_valid will be nice, but don't we have this already cause the FuncRef will return a nil variant? Checkout my above post.

I believe that this is just a matter of documentation.

**Comment by bojidar-bg** [comment]
The line mentioned returns an error along with the null, so the calling script would need to use a nonexistent try-catch construct to receive the null.

`is_valid` would also check if the object was freed in the meantime as well as whether the method exists..

**Comment by dodgyville** [comment]
Paraphrasing some of my code:
```
    var fn_name = "nonexistent_function"
    fn = funcref(self, fn_name) 
    if fn == null:
        print("ERROR1: No script")
    if fn.call_func() == null:# execute the script, queue events
        print("ERROR2: COULD NOT FIND SCRIPT ",fn_name)
```
does not hit either print statement, it throws on the call_func
`Invalid call. Nonexistent function 'call_func' in base 'FuncRef'.`

**Comment by dodgyville** [comment]
`has_method ` works, thanks!

**Comment by bojidar-bg** [comment]
Just to mention it, the `Invalid call. Nonexistent function 'call_func' in base 'FuncRef'.` message is wrong, it should mention `'nonexistent_function' in base 'Node'` or something like that.

**Comment by shayneoneill** [comment]
I just came across this bug, and its confusing as hell.

**Comment by KoBeWi** [comment]
The new Callable class in Godot 4 (which replaces funcref) has `is_valid()` method.
