### ISSUE TITLE
Can't inspect dictionary with over 5000 entries in debugger (or node containing it)

### ISSUE THREAD

**Issue by ww2commander** [godotengine/godot#20258]
**Godot version:**
v3.0.4 stable

**OS/device including version:**
Win10, 64gb RAM, GTX1080

**Issue description:**
When playing a project, the game will crash if the editor's inspector tab contains a dictionary with more than 5000 entries (I am not sure on the exact size but its around this mark). 

The size of the dictionary in question stores an entry for each used cell on my game Tilemap. I confirmed it was the dictionary causing the crash by trying different sized tilemaps. At 50x50 cells, the inspector didn't cause an issue, at 75x75 and up, the inspector crashed when inspecting or containing the dictionary.

The crash will occur regardless of whether the actual dictionary is selected in the inspector or the 'Members' branch is collapsed. Selecting another node for the inspector (i.e. not look at the node containing the dictionary) will not result in the crash.

The script creating and appending to the dictionary is Autoloaded (singleton enabled). The dictionary in question comprises the following as example of how I'm using the dictionary (tileXY is a Vector2):
```
			map_data[tileXY] = {}
			map_data[tileXY].owner_id = gc.TILE_UNOWNED_VALUE
			map_data[tileXY].x = tileXY.x
			map_data[tileXY].y = tileXY.y
			map_data[tileXY].terrain_id = adj_texture_id
			map_data[tileXY].terrain_type = terrain_type
			map_data[tileXY].feature_id = -1
			map_data[tileXY].feature_type = gc.UNUSED_FEATURE_TYPE
			map_data[tileXY].tile_index = tile_index
			map_data[tileXY].city = false
			map_data[tileXY].city_texture_id = 0	#TODO: Figure out city textures
			map_data[tileXY].airbase = false		#TODO: Figure out airfields and textures
			map_data[tileXY].units = []
```

**Comment by eon-s** [comment]
I wonder if Inspector and Remote Tree could have some kind of pagination for places with high number of entries (array/dictionary or nodes in the case of the tree) so it can show a fraction only to make it affect less the running game and the editor and make debugging better.

Because even if this crash is solved, browsing that amount of entries will be useless for debugging purposes.

**Comment by akien-mga** [comment]
An example project that triggers the bug would be welcome, otherwise it's hard to debug.

**Comment by DualMatrix** [comment]
Could not replicate with a dictionary of 5000 elements. Once I went  above 10000 elements godot began to act real weird though and started to crash randomly.

**Comment by akien-mga** [comment]
See #22654 (likely duplicate) for a project that reproduces the issue.

**Comment by akien-mga** [comment]
I can't seem to reproduce this or #22654 in 3.2 beta 5 on Linux.

Can you still reproduce this kind of "debugger breaks on big objects" issue @ww2commander @Banderi @Zylann?

**Comment by Zylann** [comment]
Testing once quickly in Godot 3.2 beta 5 on Windows, it did not crash, but it doesn't work either:
![image](https://user-images.githubusercontent.com/1311555/71920516-d9ec3e00-317e-11ea-85b1-0769149dd4cd.png)

**Comment by akien-mga** [comment]
If anyone can still reproduce this (apparently there's no crash anymore, but it still can't be debugged), please attach a minimal reproduction project that can be used to reproduce the issue.

**Comment by DataPlusProgram** [comment]
I have come across a similar problem. I assume it is the same issue.
It appears the debugger will crash when trying display a large array called "vertices"
I have attached a minimal preproduction project which is a stripped down version of the actual project.

If you put a breakpoint on line 80 of "BSP_Map.gd" which is the "parse_vertices" function and step over it then the debugger will crash and a sprite won't be displayed. This has been tested on 3.2.3 stable and 3.3 rc8.

If no breakpoint is present there will be no crash and the sprite will be displayed.

[minimal.zip](https://github.com/godotengine/godot/files/6331991/minimal.zip)

I'm not sure if its better to open a new issue or not since this one is a few years old and might be buried.

**Comment by KoBeWi** [comment]
Seems still valid in 4.0, here's updated project:
[minimal.zip](https://github.com/godotengine/godot/files/8165701/minimal.zip)

**Comment by rossunger** [comment]
I'm having the same issue.

**Comment by Calinou** [comment]
Consolidating in https://github.com/godotengine/godot/issues/36801, as this is due to the same cause.
