### ISSUE TITLE
better Input Map usage

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#20264]
Godot version: 3.0.4

OS/device including version:Win7

Issue description: The current Input Map use is really uncomfortable and slow:
-The standard actions can't be renamed. 
-Actions can't be selected and dragged, thus can't be sorted up or down.
-Actions can't be duplicated. (very useful if the ui uses the same keys as the ingame control. Will save >10min creating actions)

Steps to reproduce: Use the Input Map

**Comment by Calinou** [comment]
> -The standard actions can't be renamed.

They cannot be renamed because the UI system uses those actions to handle keyboard-based navigation.

**Comment by AdrianSima** [comment]
I would also love if when I am adding/editing one input, all the other inputs that I've contracted to remain like that. Right now every time I edit an input all of them open and it's a mess.

**Comment by Xrayez** [comment]
FYI, some ideas are currently discussed at godotengine/godot-proposals#303.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
