### ISSUE TITLE
Mono/C# support on Android

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#20267]
We lacked an issue to keep track of Android export support for Mono/C# projects, so here's one.

@neikeq What are the needed steps to get this to work?

**Comment by nightblade9** [comment]
How will this affect the final APK size?

**Comment by exts** [comment]
I know @hpvb on discord said he'd be looking into the android stuff. Maybe he can chim in some.

**Comment by aaronfranke** [comment]
This applies to iOS too but I'll just post this here for now since we'd likely focus on Android first.

The only framework I'm aware of for creating mobile apps using Mono/C# is Xamarin. Unfortunately, these tools are not available for Linux, which is problematic for if we want to make use of them since Godot is a strongly multiplatform game engine. I submitted a feature request here: https://github.com/mono/monodevelop/issues/5228

**Comment by akien-mga** [comment]
> This applies to iOS too but I'll just post this here for now since we'd likely focus on Android first. The only framework I'm aware of for creating mobile apps using Mono/C# is Xamarin.

Well, isn't Godot itself a framework for creating mobile apps using Mono/C# already? We can build Windows apps from Linux with Godot + Mono (i.e. the Linux-compiled C# assemblies work on Windows), so it should work the same for Android, no? IINM, we just need to find how to include the assemblies in the APK and load them from there. (I might miss something specific to non-desktop platforms that would require us to go through a thirdparty framework though).

**Comment by dunyakilavuz** [comment]
Since #19839 is closed, forwarding my question.
Is there any rough estimations for android exporting functionality?

**Comment by neikeq** [comment]
I will talk about this once 3.1 stable is out.

**Comment by DavidJVitale** [comment]
Although all the official documentation I'm reading on the subject says that `Xamarin.Android` isn't officially supported on Linux, I've noticed that their repository has [instructions for manually building](https://github.com/xamarin/xamarin-android) the bindings, and their CI/CD system even has [automatic builds for Ubuntu](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-linux/) set up with the builds occasionally passing. So it looks like it's theoretically possible to hack something together: although I'm not sure that would be a smart long-term solution. Just making sure this information is known.

**Comment by migueldeicaza** [comment]
We will be happy to make sure that we can produce Xamarin.Android packages from our CI that are suitable for your consumption.    We are trying to setup a communications channel between the Godot folks and my team to make sure we are not blocking you.

While you can certainly produce Android packages natively, I would love to see this use Xamarin.Android, mostly because we productize the latter and can provide support to any users that are running into problems.   And it would be the same on Windows, Mac and Linux.    

But most importantly, because then your C# users could call and consume any native APIs from Android without having to use some sort of module, they can access the entire Android API from C# when they so desire.

**Comment by akien-mga** [comment]
From what I've heard @neikeq and @hpvb are pretty close to get things running on Android, but there's still some work to do. Probably won't make it in time for 3.1.0, but should hopefully be done shortly after and backported to 3.1.x releases.

**Comment by nightblade9** [comment]
This might be a dumb question, but how exactly is this going to work in terms of exporting? Right now, a "hello world" Godot project for Windows clocks in at around 28MB; I just tried a "hello world" Godot/Mono project, and it clocks in at around 42MB. That's quite large, considering there are no game assets in it yet.

When Android works with C#, is this going to be the same, or is there some sort of DCE/compression/something that will be applied to shrink the APK size down?

**Comment by NathanWarden** [comment]
I haven't used it in Godot before, but I believe you'll just have to tick the Apk Expansion flag in the export dialog and you'll be able to have an expansion file. Expansion files can be up to 2GB in size. If a person is using C# it might be because they'll be developing a larger game anyway, so a bigger APK file isn't really a big deal.

**Comment by NathanWarden** [comment]
With that said, I just made an empty Unity build and the APK size was only 16.3 MB and 11 MB with stripping on at the highest setting, so I'm sure there's some sort of stripping and/or compression that can be done :)

**Comment by Calinou** [comment]
> When Android works with C#, is this going to be the same, or is there some sort of DCE/compression/something that will be applied to shrink the APK size down?

Unless you tweak ZIP creation parameters, APKs are already compressed since they're just ZIP archives.

**Comment by nightblade9** [comment]
@NathanWarden thanks, that's promising. I'm not using C# because I'm making a larger game - I'm using it because I'm much more proficient in it (and I can make much more testable games with it).

Hopefully this will work out well, I'll wait for the appropriate release. I know with .NET Core applications, a "hello world" release app is like 60MB; you can use Mono's dead-code compression thing (the name eludes me just now - the one endorsed by Scott Hanselman) to shrink it to around 40MB. If you zip all the files, it shrinks even further.
