### ISSUE TITLE
Add WorldEnvironment custom material override

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#20280]
This is a test I made, following up the discussion of #18848 and as an alternative to #18795 (add viewport custom material override).

The Material is set per WorldEnvironment node, which enabled cameras to have their own custom materials (as mentioned in #18848).

Is this worth trying or is the viewport solution preferred?

![override2](https://user-images.githubusercontent.com/1642015/42957070-7b27387c-8b79-11e8-85eb-e33cb785843d.png)

![override3](https://user-images.githubusercontent.com/1642015/42957580-051b3c4e-8b7b-11e8-9107-00e8a915e26b.gif)

**Comment by nunodonato** [comment]
here's another test, instead of overriding materials, I added this extra material has a pass to all other materials.

![sceneshader](https://user-images.githubusercontent.com/1642015/43015343-5e125aea-8c47-11e8-8eee-9f2d0b303367.gif)

**Comment by Jummit** [comment]
I would really love seeing this in Godot!

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by sairam4123** [comment]
Will this be added anytime soon? I'm waiting for this feature!

**Comment by Calinou** [comment]
@sairam4123 This was reopened as a feature proposal: https://github.com/godotengine/godot-proposals/issues/936

This issue tracker is now used for bug reports only.
