### ISSUE TITLE
Comment node in visual scripting should move all the nodes inside

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#20325]
When placing comment node on the canvas, right now the node itself just serves as an outline block to visually group nodes. What I would like to see is when moving comment node, all the nodes inside the comment box should move with the comment. It would make comment box much more usable and practical.

**Comment by fire** [comment]
> I think the best way for organization would be a 'code collapse box' that could be used in different ways:

> A commented area that can contain nodes, similar to what UE4's blueprints use. You could move or collapse this, and the node would be moved or hidden with it.

> You could edit this node box in its own view. Isolated from anything else, so you don't have to worry about it.

https://github.com/godotengine/godot/issues/18267#issuecomment-382490921

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by fire** [comment]
Fixed by https://github.com/godotengine/godot/pull/54970
