### ISSUE TITLE
TileMap.set_cell very slow in Master (3.1)

### ISSUE THREAD

**Issue by nazgum** [godotengine/godot#20323]
**Godot version:**
Master -  v3.1.dev.calinou.cfcb6e1

**OS/device including version:**
Linux with OpenGL ES 3.0 Renderer: GeForce GTX 670M/PCIe/SSE2

**Issue description:**
Using set_cell on tilemaps is extremely slow compared to 3.0 (Stable).  Running the following loop for updating tiles:

```
var start_time = OS.get_ticks_msec()

for x in 100:
   for y in 100:
      set_cell(x, y, 1)

var end_time = OS.get_ticks_msec()
print("time taken: ", end_time - start_time)
```
On Godot 3.0.x stable, this takes around 11ms.   On master, this takes 660ms (around 60x slower).  Looping through a bigger TileMap makes this worse.

```
for x in 500:
   for y in 500:
      set_cell(x, y, 1)
```

This code takes 385ms on 3.0 Stable.  On Master, it takes 34392ms (around 100x slower).

**Steps to reproduce:**
Run the attached project (or MyMap.tscn) and check the output to see the time taken. 

**Minimal reproduction project:**
[tilemap-slow.zip](https://github.com/godotengine/godot/files/2215861/tilemap-slow.zip)

**Comment by swarnimarun** [comment]
In my builds this was not an issue, but been a while since I tested it.
Have you tried with a different master build?

**Comment by nazgum** [comment]
I first ran into this about 3 weeks ago, as I tried to grab a master build to play around with the new input strength feature.  I tried once more a few days later, then waited til now to see if perhaps it was simply due to the alpha state.  So this happened for me with 3 different master builds, all within July; I haven't tested Master prior to that.

Am making a roguelike, so I loop through tilemaps a lot using set_cell to build the levels; the level creation process goes from about 500ms on 3.0 (Stable) to 5+ minutes on Master.

**Comment by PJB3005** [comment]
> Using the OP project, and running the process twice, the first time took 834ms and the second (over the same tilemap, and same tiles) takes 14ms.

This is to be expected, as the code does an early check to bail out in the second case.

Using advanced profiling techniques :tm: I have determined this commit to be the cause: 69ee7945d70e40c7953e9f587a8d0480db8eda86 #15909
This is because the tile map is recreating its quadrant for the cell being modified EVERY TIME, whereas previously (before that PR) it was deferred so it only happened once. So the tile map is sending & wiping canvas items and such to the 160000 times in my case.

Profiler data here, although it's not that important:

Doing the operation of `set_cell(x, y, 1)` for 400x400 cells:

![image](https://user-images.githubusercontent.com/8107459/43039135-5cc2a3a8-8d27-11e8-9ec9-b7563159c5b0.png)

PS I'm amazed that tile maps use a single map to store all cells instead of storing cells in a chunk basis per quadrant (so, like Minecraft for example). Seems like it'd be much more performant.

**Comment by eon-s** [comment]
Maybe it can be a tilemap setting, to make it update on changes or defer it, also, could be nice to have a way to feed an array of cells instead of one by one.

And yes, it still have room for many optimizations and fixes.
