### ISSUE TITLE
Allow controls to change shape of mouse pointer even when mouse filter is set to 'Ignore'

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#20344]
**Godot version:**
`master` / cfcb6e11f25ad

**OS/device including version:**
_Manjaro Linux 17.1_

**Issue description:**
It seems that `Control.MouseDefaultCursorShape` is only effective when `Control.MouseFilter` is set to either `Stop` or `Pass`.

However, there can be such a scenario when you want one of such controls to indicate an interactable area by changing the mouse cursor, but need to use another node to actually handle the input events.

For such a case, it'd be better if there's a way to make a control to change shape of the mouse cursor without actually blocking the input events.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
