### ISSUE TITLE
GDscript Inheritance issue

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#20340]
**Godot version:**

build from commit 92415365c8586dd0c91b0566d7c00753e0687273

**OS/device including version:**

Windows 10 64bit, Nvidia Geforce GTX 1060

**Issue description:**

Before typed gdscript was added i was able to extend a node2d and use the functions of the derived class KinematicBody2D like move_and_collide. But i added a test function `func dd() -> String: return "get out of my laboratory"` in a completely different script.... and now i am unable to use kinematicbody2D functions in a script that extends a node2D.

**Steps to reproduce:**
1) extend a base node type in a script like node2d and use functions for a class that inherits from that node type like KinematicBody2D (this may already cause the problem)
2) if the problem has not occured yet. make a typed gdscript function in any script

The ability to extend scripts in the manner I have been using has saved a lot of work and keeps me from rewriting the same code over and over.

**Comment by akien-mga** [comment]
CC @vnen

**Comment by Zylann** [comment]
I think being able to use functions from a class you didnt extend was never meant to work.

**Comment by suptoasty** [comment]
Here is an example of what I was doing:
[enemy_weapon.txt](https://github.com/godotengine/godot/files/2216587/enemy_weapon.txt)
[enemy_projectile.txt](https://github.com/godotengine/godot/files/2216588/enemy_projectile.txt)

**Comment by suptoasty** [comment]
Maybe some sort of system like `node_two implements node_one` could be added to work with class_name for this to work instead of just being able to call functions from KinematicBody2Ds inside of a script that extends a Node2d that was assigned to a KinematicBody2D would be better.

**Comment by Zylann** [comment]
@suptoasty problem is it breaks the way OOP works. And because of that, it's going to confuse the editor when it tries to check your code, and confuse devs when they have to handle such case. I can understand how this is useful but that's what you get with an inheritance-based design, and is one thing "OOP-haters" complain about. I can't think of a better solution apart from using composition instead, because the OOP solution would be multiple inheritance (ugh), or mixins (latter being the closest to your need of not repeating code).

Getting to the more technical side, this worked so far because `extends` isn't real inheritance. It just tells that a script can only be placed on a matching C++ class. But when you use it to extend another script, it BECOMES true inheritance in the context of GDScript. I'm curious what GDScript devs think about this...

**Comment by suptoasty** [comment]
Okay...I see your point. It is ultimately up to you guys. I'll just have to make more scripts for different node types. If the other devs don't see this as something that needs to be fixed...they might switch the label to discussion, or i could close the issue?

**Comment by vnen** [comment]
This is related to #16958.

I'm not sure if this was ever supposed to work.

**Comment by vnen** [comment]
Also there's the bigger problem that a script can't know to which node it is attached to. If this is really intended to work like this, I guess I could remove these checks and make them warnings.

**Comment by vnen** [comment]
For what I discussed with @reduz, this behavior is not really intended, but there won't be any changes to it. So it won't be explicitly forbidden but you won't be able to call the specific node function if your script extend a more generic one. The workaround is to use `call`, e.g.: `velocity = call("move_and_slide", velocity)`.

If a lot of people is relying on this they'll complain, and if they do we can try to add a new keyword to work this around in a official way.

Just note that this behavior isn't really sane and might get in the way of future optimizations if we remove the checks.

For now this will be kept closed and we might revisit in the future if need be.

**Comment by suptoasty** [comment]
Thanks!
