### ISSUE TITLE
Blend shapes (via gltf blender exporter) scales up the whole geometry

### ISSUE THREAD

**Issue by Rabocop** [godotengine/godot#20377]
Version:
Godot v3.1.dev.calinou.e2b7a68 in the video below but it happens the same in v3.05 stable

OS/Card
Ubuntu 16.04 / GTX850M 
Ubuntu 18.04 / GTX1060
Issue:

Blend shapes are correctly imported but they scales up the whole geometry  if it's skinned
It doesn't happen if you don't export "skinning" for static models.
Tested also with simple geometry with one bone and checking/unchecking all the export flags possible.
![ezgif-4-ec2ae99e45](https://user-images.githubusercontent.com/7796648/43074357-3c5639ca-8e7d-11e8-8d19-0d1d336184d9.gif)
Steps:
-Create an object and assign some skeleton
-Create blend shapes and export it to godot via gltf (.dae won't import blend shapes by the way)
-Tweak the imported blend shapes in Godot

**Comment by clarkejm** [comment]
Have you checked if your blender scale is in metric? I've found that to fix most of my GLTF import scaling issues (although I haven't tried this case specifically)

**Comment by Rabocop** [comment]
Hi! Yes I tried. I tried

**Comment by WindyDarian** [comment]
I am having the same issue. Tried to debug this but no avail today. For me it only happens when the mesh is skinned and has shape key at the same time.

When the blend shape's weight is 1.0, the mesh scales exactly by 2.0 (as dividing 2 in vertex shader made the size match the original). 

Also in my case the frustum culling and wireframe view have weird behaviors - the mesh becomes invisible as soon as origin is out of the viewport; 

When armature is removed, wireframe view is still corrupt, but shape key deformation looks correct; when shape key is removed, wireframe view and frustum culling look correct.

**Comment by Garrom** [comment]
@Rabocop I know it is off topic but I **really** like your color theme in Blender. I always liked green/blue with black. It looks stylish, little futuristic and darker color cause less eye exhaustion.

**Comment by crantisz** [comment]
looks like it is still an issue for export in HTML

**Comment by Calinou** [comment]
@crantisz Please open a new issue with a minimal reproduction project :slightly_smiling_face:
