### ISSUE TITLE
"Dropper" tool for nodepath variables

### ISSUE THREAD

**Issue by LexiEmory** [godotengine/godot#20427]
**Godot version:**

Godot 3.0.5

**OS/device including version:**

Does not apply

**Issue description:**

I feel like having the option to use a "dropper" tool to select nodepaths would be make the workflow of using exported nodepaths much faster. Currently, when selecting a node path, it pulls up a tree menu that displays all possible nodes. 

**Steps to reproduce:**

1. Make a script with an exported nodepath variable
2. Press the node selection button in the inspector
3. Click on a node in the viewport
I imagine it would look something like this (thank you eons):

![NodePicker](https://cdn.discordapp.com/attachments/212250894228652034/471471231154126889/nodepicker.png)

**Minimal reproduction project:**

Does not apply

**Comment by EmAlexander** [comment]
No, the NodePath export hint would have another option to use a "dropper" tool. The tool would function a lot like selecting a node with the list selector. Once the user selects this option, they would be able to select a node in the Scene preview tab. Whatever they select would become the NodePath in the export hint. In large scenes, this would make it faster to quickly select a node for NodePaths.

**Comment by avencherus** [comment]
Yes. 👍 

I think about this every time I try to use Assign in an export var.  A lot of my scenes can have dozens and dozens of nodes, so the whole tree in un-collapsed form, starting at the top, is very time consuming to setup.

Would also like a way to click the desired node in the tree and have it link to it.  Was thinking at one point that the little brush icon next to it meant that (like in word processors where you copy formatting), but apparently that represents clear.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
