### ISSUE TITLE
Invert YSort on TileMap and YSort nodes

### ISSUE THREAD

**Issue by ShyAnimeGirl** [godotengine/godot#20431]
As everyone knows the TileMap node and YSort node work by allowing objects with a higher Y value overlap objects of a lower Y value. I simply would like a option in these nodes to invert the YSort and allow objects with a lower Y value to overlap objects of a higher Y value. I have drawn a small example of what I mean if it is still unclear. 
![capture](https://user-images.githubusercontent.com/18611423/43179004-7af037ea-8f9e-11e8-9ad1-a066b6e439f7.JPG)

**Comment by TheDuriel** [comment]
@groud Hey, i'd like to hijack this issue for a more refined feature request:

Deprecate YSort and introduce DirectionalSort. DirectionalSort takes a Vector2 unit vector to determine the direction in which to sort.

This would allow for the original proposal to function, and enable games that take place on diagonal grids or that have skewed perspectives to work better. We can also change it on the fly for cool visual effects.

**Comment by groud** [comment]
> enable games that take place on diagonal grids or that have skewed perspectives to work better

Do you have any example where YSort would not be enough ? 

Honestly, I don't see any common use case for that so I don't think it's worth implementing it in the core.

**Comment by bojidar-bg** [comment]
I think this might be possible already by rotating the YSort node so it sorts in the direction you want, and then "unrotating" all its children.

**Comment by TheDuriel** [comment]
I don't think that is a viable solution. Not only do you need a script that unrotates everything, but it _also_ would rotate the coordinate space everything moves in, forcing you to set everything as top level which means global coordinates only, or to rotate all your game logic with it.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
