### ISSUE TITLE
Cubemap is not saving

### ISSUE THREAD

**Issue by gdesecrate** [godotengine/godot#20439]
Godot_v2.1.5-rc2_x11
By default cubemap is not saved correctly to tres scene.

How to reproduce:
If you add WorldEnviroment to scene (camera as well).
Set background to cubemap. Load cubemap with 6 of defauilt godot's icon.png-s the cubemap shows in editor. But If you try to launch it - there is no cubemap shown.
If you save your project and restart godot editor - **you will notice that only 1st of six images in cubemap was saved**.

Good thing there is a way to avoid it:
**It you need to manualy save cubemap to non-TRES format (like xxx.cbm)**

**Comment by eon-s** [comment]
This is an old bug, other issues maybe got closed since there is no more cubemaps on 3, the thing is that cubemaps always try to save the images inside the resource/scene making it too big and corrupting the scene file.

Another workaround is saving the scene with the cubemap as .scn to avoid the size problem which is not present in binary files.

**Comment by WiggleWizard** [comment]
PR #20307 fixes this issue for 3.1. As for 2.1, someone will need to port that fix across probably.

**Comment by Chaosus** [comment]
If its fixed in 3.1, then it should be closed, we are no longer provides non-critical updates for 2.x version
