### ISSUE TITLE
Game crash/server disconnect; editor crash when playback and audio pitch @ 0

### ISSUE THREAD

**Issue by an0mali** [godotengine/godot#20459]
Godot v3.05
Windows 10

If audio pitch is accidentally set to 0 in an AudioPlayer2D node (manually or via AnimationPlayer), game crashes with server disconnect error and no indicator of where error occurred. Enabling playback of an AudioPlayer2D node in the editor in which the pitch is set to 0 (or 0.01) causes the entire editor to crash, again with no indication of where the error occurred or why.

Suggesting a fix to debugger output when a crash is caused due to this that points to the pitch setting of AudioPlayer2D node versus a "server disconnected" error in addition to a fix that doesn't allow the audio pitch to be set to 0/0.01 and instead defaults to a minimum playable value.

**Comment by TiagoJoseMagalhaes** [comment]
Hi, I am going to give a try to fixing this, however I am new to the project and open source in general so I`m if the fix takes a long time to be developed.

**Comment by vnen** [comment]
@TiagoJoseMagalhaes it's not a problem if it takes some time, but it might happen that someone make a fix before you, so you should be disconcerted by that. Come over to the IRC channel (#godotengine-devel at freenode) if you need some help.

**Comment by TiagoJoseMagalhaes** [comment]
@vnen Thanks :), Will do if I need help.

**Comment by TiagoJoseMagalhaes** [comment]
Just opened a PR for this https://github.com/godotengine/godot/pull/20605.
From my analysis of the issue it is caused by the audio stream not sending any packets to the socket when the pitch is too low, and the receiver expecting to receive packets causing it to assume a disconnection and sending the disconnect error. I was not able to pin down why the editor crashes but I would guess its because of some sort of null pointer.
