### ISSUE TITLE
Add feature tags for major version to give control over GDNative plugin export

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#20479]
Due to changes in the ARVR system between Godot 3.0 and 3.1, and now nativescript 1.1 adding features only available in Godot 3.1 it would be nice to add feature tags to the export that are set based on the major version of Godot we're exporting for (/running in).

For GDNative this would allow assets downloaded from the asset library to contain separate Godot 3.0 and Godot 3.1 dynamic libraries with the correct one being used/exported.

**Comment by akien-mga** [comment]
Had a quick look at it and this can likely be done by adding
```
r_feature_list->push_back(vformat("%s-%d.%d", String(VERSION_SHORT_NAME), VERSION_MAJOR, VERSION_MINOR));
```
to the `get_platform_features` for all platforms, but it seems a bit overkill to me to duplicate all this in all platforms.

Maybe the `EditorExportPlatform`-inheriting classes should call their base class' `get_platform_features` so that we only have to add common features in the base class? (Could also avoid duplication of `pc`, `s3tc`, etc. in `EditorExportPlatformPC`-inheriting classes.)

**Comment by karroffel** [comment]
Related: https://github.com/godotengine/godot/issues/8083

**Comment by Calinou** [comment]
GDNative was removed in favor of GDExtension in 4.0, closing.
