### ISSUE TITLE
Preloading scenes slows down editor

### ISSUE THREAD

**Issue by PotatoNato** [godotengine/godot#20529]
Windows 8 Godot 3.0 stable

When i used preload to load in my scenes to my main scene (i had 6 preload scenes) every time i went to edit my main scene script it would lag. I manage to fix my problem by changing the preload to load but i dont think i should have been lagging in the editor if my scenes were set to preload. Maybe preload is trying to load the scene while in the editor.

**Comment by PotatoNato** [comment]
So it is trying to load my preload scenes my script, note that the scene is not playing I'm just in the script editor, doesn't that seem unnecessary. I mean there no reason to load the scene while in script editor.

**Comment by Calinou** [comment]
@PotatoNato Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
