### ISSUE TITLE
How to handle non-QWERTY keyboard layouts?

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#20527]
Following up comments in #18020, I'm making this topic to get better understanding how to handle different keyboard layouts.

Please, take a moment to look at following use cases and users, and answer few questions:

---

##### :large_blue_circle: Application A:
**3D shooter.**
Player movement is controlled with `WASD` keys, `I` key opens inventory.

##### :large_blue_circle: Application B:
**Raster graphics editor.**
Main menu use following shortcuts: `Ctrl(Command) + S` for “Save”, `Ctrl(Command) + A` for “Select all”.

*Developer of both apps was using standard QWERTY keyboard to configure default input maps.*

---

##### :large_blue_circle: User 1:
Keyboard image: (Standard QWERTY keyboard)

![ibm_m](https://user-images.githubusercontent.com/7645683/43341897-8fc79530-91e9-11e8-86aa-e2983ff379db.jpg)

Current selected system keyboard layout: “US English”

##### :large_blue_circle: User 2:
Keyboard image: (Dvorak keyboard, Originally QWERTY keyboard with manually moved keycaps)

![dvrk](https://user-images.githubusercontent.com/7645683/43341905-95b55658-91e9-11e8-8142-95030e618da8.png)

Current selected system keyboard layout: “Dvorak”

##### :large_blue_circle: User 3:

Keyboard image: (Russian JCUKEN keyboard)

![rus](https://user-images.githubusercontent.com/7645683/43341912-9c5282d8-91e9-11e8-920e-527c1ea6aad4.jpg)

Current selected system keyboard layout: “US English”

##### :large_blue_circle: User 4:
Keyboard image: **Same as User 3**

Current selected system keyboard layout: “Russian”

##### :large_blue_circle: User 5:
Keyboard image: (Turkish F keyboard)

![turkf](https://user-images.githubusercontent.com/7645683/43341913-a040b126-91e9-11e8-882d-63a12f05d68d.jpg)

Current selected system keyboard layout: “Turkish F”

---

## Questions:

1. What key-codes/scan-codes highlighted keys (with red border) on each users keyboard should produce?
2. Which physical keys on each users keyboard should move player in the *Application A*?
3. Which physical key on each users keyboard should open inventory in the *Application A*?
4. Which physical keys on each users keyboard should *“Save”* and *“Select”* in the *Application B*?
5. Which characters should be displayed in the menu shortcut for each user? 
![menu_img](https://user-images.githubusercontent.com/7645683/43341919-a51b5c1e-91e9-11e8-9ab3-5c1d7468e046.png)
6. What should be correct return value of `OS.get_latin_keyboard_variant()` for each of the users?
7. If you believe different physical keys should be responsible for *moving backwards* in *Application A*  and *saving* in *Application B*, how these cases should be distinguished in code? In Input Map?
8. In case you are using keyboard layout significantly different from layouts in this topic, please share image of your keyboard and desired handling for aforementioned use cases.

---

Additionally if you are using non-QWERTY keyboard, please try building #18020 PR, and testing input map behaviour with your keyboard layout. I do not have any non-QWERTY physical keyboard and only tested it by switching OS keyboard layouts.

![map](https://user-images.githubusercontent.com/7645683/43360076-adb5711a-92b7-11e8-801a-ad36aa37ae24.png)

Intended behaviour:
* **Key (Remapped)** - respects keyboard layout (same as current Godot input).
* **Key (Hardware)** - always acts like QWERTY keyboard with any layout.

**Comment by bojidar-bg** [comment]
Haven't experienced all cases but..:
**User 4:** (Qwerty keyboard, non-EN layout)
In this case, I expect shortcut keys to work as if the layout is US Qwerty.
So, if the Russian user types <kbd>Ctrl-Ы</kbd>, it should be interpreted as <kbd>Ctrl-S</kbd>.

**Comment by akien-mga** [comment]
I'll add another use case:

:large_blue_circle: User 6:

Keyboard image: (French AZERTY keyboard)

![french_azerty](https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/French_pc_keyboard.svg/800px-French_pc_keyboard.svg.png)

Current selected system keyboard layout: “French (France)”

Particular pain points of this configuration:
- Many games (FPS/TPS) map movement to WASD on en_US layouts, which is unusable on AZERTY where it needs to be remapped to ZQSD
- Number keys are "shifted", you need to hold Shift to input a number unless using the numpad. Particularly painful in games where hotkeys are mapped to number keys and where <kbd>Shift</kbd> + <kbd>&</kbd> for example won't be recognized as a <kbd>1</kbd> key press (and often <kbd>&</kbd>, <kbd>é</kbd> and so on can't be mapped directly to those actions - they can in Godot however).

**Comment by moiman100** [comment]
Same physical location should always do the same thing and UI should show the character from selected system keyboard layout corresponding to that physical location.

Also currently Godot doesn't even support all keys. For example "<" key is unknown on Finnish/scandinavian/nordic keyboards and I would assume on French too because of the same location.

**Comment by romlok** [comment]
I like the idea of there being two different types of key mapping for different uses: hardware and remapped. Though I think it would be clearer to users if they were called something more along the lines of "physical location" and "character/symbol" - reflecting what they are used for, rather than any underlying technical/implementation details.

Another possibility is for Godot to allow multiple layout-specific mappings, chosen based on the current user's locale or settings. This could require more work for the developer (or contractors), but can avoid the issue of unintentionally doubling actions depending on the layout (at least for the layouts explicitly supported). This may also be desirable for when shortcuts are based on a word (eg. Save, Load, Inventory), which may be different depending on the language.

However, there will always be exceptions, and implementing user-modifiable controls should always be encouraged IMO. Perhaps Godot should allow, and automatically check for, a default config file in user:// which can contain custom action mappings? That way, even if no input-GUI is made by the developer, users are able to customise the controls with a text editor.


Also, user 1 is using a US layout on a UK keyboard? That's a capital offence!

**Comment by starry-abyss** [comment]
User 3 and 4, for both Application A & B, I expect it act as QWERTY.
Unless in text input box - then currently selected layout.

**Comment by speckledsea** [comment]
I would like to point out an edge case as well.  There exists a possibility for a "remapped" key action and a "physical" key action to unintentionally both be triggered by same key.  Using a First Person Shooter as an example, on the [Colemak layout](https://en.wikipedia.org/wiki/Colemak)  "r" for **r**eload would collide with physical placement of standard WASD movement setup (WARS on Colemak):

![image](https://user-images.githubusercontent.com/14210621/62392503-36db2c80-b52d-11e9-966a-0a29c21855d6.png)

This would need to be resolved with some kind of logic.  Ignoring it would likely be pretty frustrating/confusing for the player.

**Comment by Yukitty** [comment]
"R" for "reload" is just a _happy coincidence_ because that key happened to be nearby.
It would be more important for the "R" mapping to be replaced by "P" in this layout so that your hand on the "WARS" keys can reach it. In other layouts, the R key might be all the way on the opposite side of the keyboard -- and you would be at a significant disadvantage if you were to constantly have to reach all the way over and press it.

Just use physical scancodes for _everything_. Don't worry about individual keybinds having names.

**Comment by Calinou** [comment]
@Yukitty While this is a sensible idea for games, I don't think this is a good option for non-game applications. Many people are using Godot to make such applications, so we should avoid forcing this change on everyone.

**Comment by Yukitty** [comment]
Fair.

**Comment by bruvzg** [comment]
#18020 was merged, both mapping methods are now available, closing this.
