### ISSUE TITLE
Use _input() return value to automatically  `get_tree().set_input_as_handled()`

### ISSUE THREAD

**Issue by romlok** [godotengine/godot#20520]
I may be misunderstanding how input-event handling should be implemented, but it seems to me that if you have multiple different parts of a game which all may need to handle input events exclusively depending on the game state (eg. toggled mouselook), you can end up calling `get_tree().set_input_as_handled()` in a lot of places.

This seems rather verbose and repetitive, so I suggest Godot make the various input-event handler methods (`_input`, `_unhandled_input`, etc.) allow returning a boolean value which can be used to indicate that the input event should be marked as having been handled.

Eg:
```gdscript
func _input(event):
    if event.is_action("beep"):
        do_beep()
        # As today; this event will continue to beep on other nodes
        return
    if event.is_action("boop"):
        do_boop()
        # This would cause the event to not boop anywhere else
        return false
```

FWIW, my instinct was to have `true` be the value which sets the event as handled, but javascript (at least) uses `false` for this purpose (mostly), so maybe my instinct was wrong and `false` is the way to go.

**Comment by Zylann** [comment]
If you add this, it would be better to make it so existing callbacks dont have to return `true` or `false`, so that it won't break existing code.
More on why and how I use this: I almost never needed to set input as handled, because I exploit as much as I can the way events flow through controls and the game. I rarely use `_input` in the end because it's too "global" and doesn't go through the logic described here: http://docs.godotengine.org/en/3.0/tutorials/inputs/inputevent.html#how-does-it-work. If two parts of the game have `_input` running simultaneously and overlap each other, I would see this a design issue (at least the way I code my games) because unless I exploit tree order (which I don't, too easy to get wrong), I generally don't know (or even care) which one will get the event first. Then, in the worst case, I do `get_tree().set_input_as_handled()`. The result is, I use this very rarely, and I don't see a forced return of `true` or `false` as something useful.

That said... `EditorPlugins` do have such logic of returning `true` or `false`. Not sure why this was preferred here and not elsewhere?

**Comment by KoBeWi** [comment]
This is *technically* doable in a non-breaking way, but it would be super unsafe. `_input()` typically has no return value, but nothing stops you from returning something, which then can be used to handle input. It's unsafe, because you can't have declared return type. Adding return type to `_input()` would break compatibility.

In any case, this should be moved to [proposals](https://github.com/godotengine/godot-proposals).
