### ISSUE TITLE
[Deleted Object]s (free()'d objects) should be treated as null

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#20549]
Currently any `free()`'d objects, when passed to a function or read from a variable, aren't treated as null for the purposes of comparison. It'd be nice to see them treated as null, so I can do `if some_object`, and if `some_object` happens to have been `free()`'d beforehand (that is, when you print that object, it prints `[Deleted Object]`), it will be treated the same as if `some_object` was actually null (since it effectively is null at that point).

**Comment by vnen** [comment]
I'm not sure to which extent this is possible. There is a semantic difference between a freed object and a `null`. And I think this system to detect deleted object isn't present in release builds.

Consider this:
```gdscript
var a = Object.new()
b = a
a.free()
```

At this point should `a` and `b` be set to `null`? For the sake of simplicity for the scripting language, it could be so. Setting both variables effectively to `null` is much better than to just treating freed objects as `null`. But it is not trivial to make it happen for what I understand.

The question is: how to implement this in an efficient way that works reliably even on release builds (without having to check all the time if the object is freed or not)?

**Comment by neikeq** [comment]
That's what `is_instance_valid` valid was added for. The correct way in this case would be checking both for null and `is_instance_valid`.

**Comment by LikeLakers2** [comment]
>And I think this system to detect deleted object isn't present in release builds.

If it's anything, I did encounter `[Deleted Object]` being printed on a release build while trying to figure this out.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by neikeq** [comment]
@reduz Was this implemented when Variant was made to store ObjectID?
