### ISSUE TITLE
int(String) is not same with int(int)

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#20572]
**Godot version:**

3.1.dev 90298ddf0

**OS/device including version:**

not related

**Issue description:**

as title said, int(String) is not same with int(int)

**Steps to reproduce:**
```gdscript
printt(int("1234567890123456789"), int(1234567890123456789))
# it prints "2112454933	1234567890123456789"
```

**Minimal reproduction project:**

**Comment by volzhs** [comment]
probably @vnen knows what's wrong with it?

**Comment by vnen** [comment]
I've noted that kind of inconsistency before, in particular when importing stuff from JSON. I thought I had opened an issue but I guess it slipped my mind.

This is not a GDScript issue though, it's related to how it is converted internally (GDScript just call a function). Maybe the problem is in the String class or in Variant.

**Comment by bojidar-bg** [comment]
I think the problem is here (should be int64_t):
https://github.com/godotengine/godot/blob/5a5614e8adcc49b92621dc2f39364385769d36a0/core/variant_call.cpp#L1154-L1156
and here (should call to_int64):
https://github.com/godotengine/godot/blob/5a5614e8adcc49b92621dc2f39364385769d36a0/core/variant.cpp#L1187-L1195
Potentially, other places calling `String::to_int` should be reviewed.
