### ISSUE TITLE
Disable children editing on request in 3D (locking feature as available in 2D)

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#20596]
**Issue description:**
Editing collision bodies usually is a pain because what happens more often is that, when you have a hierarchy like this:

>Static body
>> Mesh
>> Collision shape

The most common interaction is that you, by accident, move either only the collision shape or only the mesh, and not the StaticBody as whole.

**Proposal**
Have an option to say "disable editing children" (opposite of "editable children" for inherited scenes")

**Comment by vnen** [comment]
Isn't it what this option does?

![screenshot from 2018-07-30 14-15-41](https://user-images.githubusercontent.com/5599796/43412406-7eb86208-9403-11e8-8838-973d33eed2c0.png)

**Comment by QbieShay** [comment]
No, it's not there in 3D :(
I would also make it more coherent with the "editable children" for instanced scenes

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
