### ISSUE TITLE
Implement Motion Matching

### ISSUE THREAD

**Issue by reduz** [godotengine/godot#20606]
Despite the big advances in the [animation system](https://godotengine.org/article/godot-gets-new-animation-tree-state-machine), there is a fairly recent technique called [motion matching](https://www.gdcvault.com/play/1023478/Animation-Bootcamp-Motion-Matching-The), which makes it easier to match 3D animation data with character motion. 

The biggest advantage of this technique is that it's easier to simply move the character in a relatively physically correct way, and animation data will try to match it, making it hugely easier to animate.

This could be implemented as either a separate node, or most likely a node for use in the AnimationTree system that does all the work (and can still be blended with others).

If anyone would be interested in researching this, let me know and I can lend a hand.

Some Resources:

[Original GDC 2016 Presentation](https://www.gdcvault.com/play/1023478/Animation-Bootcamp-Motion-Matching-The) from Ubisoft.
[Link to Slides](https://twvideo01.ubm-us.net/o1/vault/gdc2016/Presentations/Clavet_Simon_MotionMatching.pdf)
[Open source implementation for UE4](https://github.com/Hethger/UE4_MotionMatching-)

If you know more resources, feel free to contribute them!

**Comment by cheece** [comment]
it doesn't look too difficult to implement the problematic part may be getting the motion data

**Comment by reduz** [comment]
@cheece Overall, from away the algorithm does not seem that difficult (of course, implementing it is another thing). The APIs in Godot are pretty easy in general, so obtaining the animations and accessing their data is very straightforward, as well as supplying the motion data from a Kinematic/Physics.

I can imagine getting some test data will be more difficult, I wonder if there is any available.

**Comment by cheece** [comment]
i think generated motion data may be used for the development if actual motion data is not available , may be cheaper

**Comment by MarianoGnu** [comment]
i'm not sure if i'm getting this right, looks doable but i'm not sure how is the dance stamp made or created. is the user suposed to make it within Godot? if i'm correct, this works as a neuronal network where the algorthm selects the best matching pose for the current imput, but i'm not sure.

**Comment by Omicron666** [comment]
There are tons of motion data (search mocap keyword) on the internet if you need them.
Check for example http://mocap.cs.cmu.edu/, for free and commercial use, gratis.

**Comment by reduz** [comment]
@MarianoGnu this works using pre captured/recorded clips. The clips are recorded with root motion (a root bone that actually moves, not in-place animation), so my guess is that motion matching will try to match two things:

1. Character motion (done normally)
2. Current pose

It will try to match the closest motion, and then the closest pose within the animation closest in motion. This is why most likely the approach most likely needs some sort of preprocessing to make searching through all that more efficient.

**Comment by cheece** [comment]
Surely motion data is available on the web but i don't know if the kind of motion data needed,, 1) need enough data for all target movements/inputs 2)  data must include for each frame input parameters like velocity, displacement, angle of the ground, etc.. I don't know how many parametrers can be computed from the motion data alone

**Comment by reduz** [comment]
So, basically some things I can brainstorm are:
1) Motion matching should let you pick which tracks you can use as reference. 
2) As Godot allows any kind of track, you could also motion match custom boolean or float tracks, which can be used for stuff like "aiming" or "tired".
3) Part of what makes motion matching look interesting is the predictive aspect, such as "will hit a wall" or "will hop a fence". I think this should not be the responsibility of the system itself, but the system should allow passing such parameters, so the developer can manage them as is best seen fit.

**Comment by groud** [comment]
The brute force approach to find the closest  matching pose is probably going to require too much computing power.

I suggest we index the input space (animation parameters & all) with a spatial indexing structure like R-tree or something like that.

**Comment by Jimbobbedyjobob** [comment]
As I understand it, a large part of the motion matching pipeline is a UI in which an animator places tags on tracks which indicate specific motion goals/poses.

**Comment by reduz** [comment]
> As I understand it, a large part of the motion matching pipeline is a UI in which an animator places tags on tracks which indicate specific motion goals/poses.

As I mentioned before, this could be doable simply by adding custom tracks to existing animations

**Comment by dodgyville** [comment]
I have access to a mocap session if you need particular data

**Comment by ncthbrt** [comment]
This talk has a bit more implementation details:
https://www.gdcvault.com/play/1023280/Motion-Matching-and-The-Road

**Comment by SaracenOne** [comment]
@reduz, in the interest of looking at what I suppose we could consider the state-of-the-art in 3D game animation, I would also like to draw some attention to this https://www.youtube.com/watch?v=KLjTU0yKS00 since it solves another whole class of animations problems.

**Comment by Avindr** [comment]
It's been 8 months since the last comment here so I'm not sure if anyone is working on this anymore.  I've spent the last year and a half implementing motion matching in Unity and it's almost finished. I'm happy to share my knowledge if anyone is working on it for Godot. I'd love to contribute directly myself but I'm just too busy at the moment.  Let me know and I can even give access to source as an example. 

Motion Matching is a simple concept but there are numerous pitfalls and "hacks" to get the last 20% right.  They don't tell you about that in the presentations...

**Comment by groud** [comment]
Godot 3.1 just went out recently, it means we have been focusing on bugs for quite a long time, not on new features. 
Motion Matching is one of the proposed topic for [GSoC 2019](https://github.com/godotengine/godot-roadmap/blob/master/GSoC/GSoC-2019.md), so we should hopefully have a student to implement it.

**Comment by dodgyville** [comment]
Hey Kenneth that's a really thoughtful offer. Definitely think the godot
community will pick your brains on it as soon as we get organised

**Comment by Cheeseness** [comment]
To make progress easier to follow and give feedback on (in case there's anybody with significant experience with this kind of tech who's recently found themselves with more time on their hands), here's a [GSoC status report](https://godotengine.org/article/gsoc-2019-progress-report-1-part-2#motion-matching) from a couple of weeks ago covering work on a Motion Matching implementation and the repo where that work is being done: https://github.com/Aa20475/godot/tree/godot-motion-matching

**Comment by DevMagicLord** [comment]
If it could help, he made a detailed explanation about how works motion matching on his plugin
[https://www.youtube.com/watch?v=Egp1rQh1FAg](url)

There is a demo to try in description
[https://www.youtube.com/watch?v=cap1QPkEqJs](url)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
