### ISSUE TITLE
Automatically increment name of duplicated resource

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20641]
When you duplicate a node, the clone will automatically have the same name + some number. Duplicating Node will yield Node2. Duplicating Node8 will yield Node9.

This could be useful for resources too. I mean, when you duplicate a resource, by default it has the same name as original. It's useless, since you can't have two files with same name anyways. The name could be incremented like it is with nodes. Looking up all names in directory might be complicated, but if it would work for the current file at least, it could be helpful.

Well, that sounds like totally unnecessary, but I got the idea when I had "Level1.tscn", which had some structure I wanted to copy over to another level. I'd expect duplicate of it to have name "Level2.tscn" and same for all later levels. In that case, auto-naming would save some hassle. Also, right now literally no one uses the default name anyways, because it's impossible and you can't clone to another directory. I know it's very minor, but it's one of these QoL things you appreciate when you need them.

**Comment by AlexHolly** [comment]
I noticed this issue on android I had 2 .png files in different folders. 

I am not sure if it is related to https://github.com/godotengine/godot/issues/20771 the minimal example fits this issue but my case has no duplicate names.

**Comment by tomasantunes** [comment]
In #20771 the files have different paths but the same name. It should work if you rename.

**Comment by gotnospirit** [comment]
Hi,
I don't think these issues are related.
#20771 seems to be a bug while this one is an enhancement.

BTW, if this functionality is desired, I can provide a PR.
I've already got a branch for that in my fork but I should remove "merge commits" before making the PR.
Let me know.

**Comment by KoBeWi** [comment]
> BTW, if this functionality is desired, I can provide a PR.

If you are asking me, then obviously I'd want it xd
Although with all issues I created recently, this is one of least important ones.

**Comment by akien-mga** [comment]
IMO the proposed changed is not desirable. Duplicating files from the filesystem dock and duplicate nodes in the scene tree dock are not supposed to behave the same way: the former will show a dialog letting you pick the new name (defaulting to the original one, so that you can change it as you want), while the latter does not take any confirmation and thus *has* to enforce a unique name.

Most file managers that I've tried seem to work like Godot's filesystem dock: when you duplicate a file/folder, you are asked to pick a new name, which the original name as suggestion (which can't be validated as is, since it conflicts).

**Comment by akien-mga** [comment]
As mentioned in https://github.com/godotengine/godot/issues/20641#issuecomment-413026726 I don't think this is a wanted feature, and IMO definitely not worth adding so much code just for that. But thanks for the contribution!
