### ISSUE TITLE
SpinBox value ignores step

### ISSUE THREAD

**Issue by jotson** [godotengine/godot#20646]
**Godot version:**
3.0.6.stable.official

**OS/device including version:**
Ubuntu 18.04.1

**Issue description:**
- The SpinBox `.value` member ignores the `step` value
- I expect the value to always be equal to what appears visually on the control

**Steps to reproduce:**
1. Create a SpinBox control
2. Set the `step` to `0.1`
3. Enter `1.11111` in the conrol

The control will show 1.1 but `Spinbox.value` is 1.11111. The value_changed signal also gives the unrounded value. Example project attached.

**Minimal reproduction project:**
[SpinBox_Value_Debug.zip](https://github.com/godotengine/godot/files/2247246/SpinBox_Value_Debug.zip)

**Comment by goodyttoor** [comment]
Yes I think the correct behavior should be that display number always match real value (in this case 1.11111)

About the step, I do not think we should round it to step by default. It should be the add/sub value like it is. For example, If it is round to the nearest step, we cannot have a spinbox go like 0.05, 0.15, 0.25, ... 

Although if "rounded" option is on, it may makes sense to round to multiples of step value instead of integer like current. But who know they may want to round to integer. So we may let it as generic and just manually snap it in script.

**Comment by KoBeWi** [comment]
Fixed in 3.1 or 3.2
