### ISSUE TITLE
Remove downloaded tpz file from cache after installing templates

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#20640]
This is a minor thing, but I always find it annoying when new Godot version comes and I eventually need to install templates, but then after installation I have to delete the tpz file. I mean, it's useless anyways, so Godot could just move it to trash afterwards, right?

**Comment by akien-mga** [comment]
If you downloaded the .tpz manually yourself, then no, Godot shouldn't attempt at deleting arbitrary files from your filesystem. Maybe you intend to reuse this .tpz for another self-contained installed later on, or hand it over to a colleague so that they can get templates too without redownloading.

That said, it seems that when you use the option to download the templates, the temporary .tpz file written to the Godot cache is not removed after installation:
```
ls -l ~/.cache/godot/tmp_templates.tpz
-rw-r--r-- 1 akien akien 378178554 Aug 13 08:26 /home/akien/.cache/godot/tmp_templates.tpz
```
This case should be fixed, as Godot downloaded it itself so it should also clean it.
