### ISSUE TITLE
Changing Default Cursor Property not working for RichTextLabel

### ISSUE THREAD

**Issue by R3ality** [godotengine/godot#20719]
**Godot version:**
v3.0.6.stable.official.8314054

**OS/device including version:**
Win7 x64

**Issue description:**
Changed the Default Cursor Property for a RichTextLabel element via the Inspector. Upon hovering the element with the mouse, still the default (Arrow) cursor is displayed

It doesn't seem to matter which Cursor is selected. Setting mouse_filter to "Pass" instead of "Stop" doesn't appear to affect the issue.

**Steps to reproduce:**
1. Create a RichTextLabel
2. From the Inspector, set its Default Cursor Property to anything other than Arrow (Control -> Mouse -> Default Cursor)
3. Play the Scene, hover the element

**Minimal reproduction project:**
[BugMouseCursor.zip](https://github.com/godotengine/godot/files/2259768/BugMouseCursor.zip)

![bugmousecursor](https://user-images.githubusercontent.com/762122/43679910-ced36404-9836-11e8-8fc1-8862e0c82a5e.gif)

**Comment by guilhermefelipecgs** [comment]
`TextEdit` also has this problem. Tested with 7c712a25bc40c4d8e09867b61c941af06c6799f5.

**Comment by ivodopiviz** [comment]
This is an interesting one because RichTextLabel and TextEdit both have to change the cursor themselves in order to work. The current problem is that they're ignoring the base Control cursor data and defaulting to CURSOR_ARROW and CURSOR_IBEAM if they don't have to change it themselves.

Changing this behavior poses two main issues:
1) Default Cursor would only be seen when no custom control logic is hit. This sounds fine to me but I'm not sure it addresses 100% the reporter's issue. Forcing the default cursor seems, however, like a bad idea, specially for TextEdit.

2) Default Cursor is saved in Control's private 'data' struct, we'd need to make this protected for sub-classes to use. Not a huge deal, I guess, but a significant change none the less.
