### ISSUE TITLE
A debug option to display visual instances AABBs

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#20722]
Godot 3

I need a debug option to show the final AABB of visual instances, to make sure they are correct. So far I am trying to implement this in GDScript, but it's hard to make it work without too much overhead, and it's also a hassle, because it requires to hook on every single visual thing you instance and draw the outlines yourself (either with ImmediateGeometry, or a generated cube mesh). It especially gets difficult when your system doesn't use nodes and work with VisualServer directly, as it's not possible to just put a box as child.

So I thought this feature would be useful as a engine `VisualServer` feature, only present in debug versions.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
