### ISSUE TITLE
Search results panel does not show 2-bytes characters

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#20762]
**Godot version:**

3.1.dev 3fa2404a7

**OS/device including version:**

not related

**Issue description:**

Search results panel which is opened by Find in files does not show 2-bytes characters.

![screenshot_20180806_220651](https://user-images.githubusercontent.com/8281454/43718257-0eb0ca82-99c5-11e8-8c95-6cdcfeb5d56b.png)

**Steps to reproduce:**
[Empty.zip](https://github.com/godotengine/godot/files/2262634/Empty.zip)
1. download & open attached project
2. ctrl + shift + f
3. type `asdf` + enter
4. see Search result panel

**Minimal reproduction project:**

**Comment by Zylann** [comment]
`ItemList`'s fault.
Repro:
1) Create a new scene
2) Put an ItemList inside
3) Add an item to it with the following text: `汉语/漢語 `
4) Result:
![image](https://user-images.githubusercontent.com/1311555/43732810-8798816c-99aa-11e8-9c55-8de368f4f29a.png)

**Comment by volzhs** [comment]
@Zylann I'd done that exact same thing too to figure out what's wrong, but with dynamic font (.ttf)
and there isn't a problem with my test.
you tested with an embeded bitmap font I think.

I don't have a clue so far.

**Comment by akien-mga** [comment]
Seems like the wrong issue was closed by mistake.

**Comment by Calinou** [comment]
This appears to have been solved as of commit https://github.com/godotengine/godot/commit/e9f49a6d5ac88a6afca8a16f91a05f4fcdf5a589 and in 3.1.1, presumably because the correct source font is now used for the search results:

## `master`

![image](https://user-images.githubusercontent.com/180032/64488164-e7330380-d244-11e9-8f34-b3ef749bf57b.png)

## 3.1.1

![image](https://user-images.githubusercontent.com/180032/64488173-0a5db300-d245-11e9-8b76-b20a236e13a3.png)
