### ISSUE TITLE
Per-action input feedback

### ISSUE THREAD

**Issue by AnCaPepe** [godotengine/godot#20766]
**Godot version:**
3.1-dev

**Issue description:**
Now that Godot has a input action strength system, allowing to abstract joystick axes, I was thinking if a correspondent vibration/force-feedback could be implemented: instead of using **{start,stop,get}_joy_vibration**, which takes a known gamepad id, feedback could be set for an action and broadcasted to all "subscribed" [haptic] devices. It kind of defeats the purpose of abstracting gamepad input with actions if one still needs to know the underlying device for setting/reading feedback output

**Comment by Calinou** [comment]
Note: Please check whether it works by passing the device ID `-1` or `-2`, just in case.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
