### ISSUE TITLE
visual script enhancement

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20822]
**Godot version:**
v3.1.dev.calinou.9bd5315

**OS/device including version:**
windows 10 x64

**Issue description:**
in visual script :
1) when drag a node (ex: animated sprite) to visual script area it shows a dialog to select properties and when you select one it puts a node with empty function and you select function by hand, but in godot 3.0.5 it shows a list of methods (better and very useful) , just select one and it is ready to go.

2) properties can be draged and droped from the inspector (easy get and set) and its better than show properties in list (when drag a node to visual script area)

3) the window "search visual script" and "select methods" window are small and not resizable.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
