### ISSUE TITLE
Visual script nodes list or automated node path

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#20868]
**Godot version:**
v3.1.dev.calinou.1800664

**OS/device including version:**
windows 10 x64

**Issue description:**
When putting a function node (ex:get position) from nodes in scene(ex: area2d), and change hierarchy (ex:set area2d child to position2d) the path in the function node will be incorrect and needs to change by hand (need to set the "node path" manually).

But in big project changing hierarchy of just one node will affect many function nodes, and they all need to correct the path for each function node manually.

In this situation godot need a list of function nodes that needs to be corrected, and when click on item in this list will select and focus on the specified node.

Or make the nodes in the scene tab has a unique name or ID and the path will point always to the correct node even if hierarchy changed,in this case a list of function nodes is needed too for function nodes without path (node deleted and function node remain).

**Comment by fire** [comment]
The same thing happens in gdscript. I recommend using a export variable.

![godot windows tools_2018-10-11_14-39-52](https://user-images.githubusercontent.com/32321/46835610-89134d00-cd63-11e8-8f1c-58260904edac.png)

It'll save the info inside of whatever scene the vs is attached.

**Comment by sami8github** [comment]
Exported variables are good for organizing , what I mean if you use dragged properties and functions and then you change hierarchy, the project will mess up, and if you don't know the nodes that needs to be fixed then you have to check all nodes ! 
I think Godot 1)need to show the nodes with wrong path (mark visually / list)
                      2)need to show the node where the error happen (zoom to node + mark visually)
                      3)need to show search result for specific node (list of result)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
