### ISSUE TITLE
KinematicBody more advanced test_move() style function that returns KinematicCollision

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#20865]
I think a more advanced version of test_move() for KinematicBody that returns a KinematicCollision would be an extremely useful feature.

I am unsure exactly how collision testing works in the source code but from what I can gather, a collision set to generate a KinematicCollision requires more overhead than a simple yes/no so that is why I am requesting a separate function (as well as to maintain compatability with existing code)

**Comment by creikey** [comment]
maybe `test_detect`?

**Comment by creikey** [comment]
After reading through the method `test_body_motion` I am fairly certain that  returning a `KinematicCollision` causes no penalty to performance, and the `test_move` function simply just doesn't use the functionality... will open a PR later to modify the method.

**Comment by Calinou** [comment]
@creikey If this is submitted for 4.0, we might as well break compatibility to avoid providing the same feature twice :slightly_smiling_face:

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
