### ISSUE TITLE
The ability to change enumerable properties by dragging their labels.

### ISSUE THREAD

**Issue by kpiorno** [godotengine/godot#2086]
Something that I miss in Godot is the ability to change enumerable properties by dragging their labels. Something like Blender, Unity3D or 3DMax does.

**Comment by kpiorno** [comment]
An example: http://dc771.4shared.com/download/Dg_aCyGYba/blender.gif?lgfp=3000

**Comment by neikeq** [comment]
This feature was already added. I think it works with _spin_box_ properties only, so it won't work with Vector2, Vector3 and other numeric properties that use _line_edit_.
It may be a bit confusing because the mouse is hidden and captured when dragging the _spin_box_. The reason for this (reduz words) is to allow dragging unlimitedly (otherwise you would reach the end of the screen).

**Comment by akien-mga** [comment]
Closing as fixed then I guess.
