### ISSUE TITLE
Godot mono crashing on build.

### ISSUE THREAD

**Issue by fadexmusic** [godotengine/godot#20882]
**Godot version:**

v3.0.6.stable.mono.official.8314054

**OS/device including version:**

macOS Sierra 10.12.6

**Issue description:**

I was working on a c# project in visual studio and when I switched to godot, one script got detatched from one node. When I reatached it, the editor crashed on build. So I started playing with deatatching and reatatching the script and commenting some code, and the behaviour seems to be different each time. Sometimes the editor crashes, sometimes the game window crashes, and sometimes it just works.

**Steps to reproduce:**
1. Open the project
2. Open Level.tscn in Scenes folder
3. Try attaching, detaching the Level.cs script in the Scripts folder

**Minimal reproduction project:**

[LogicMovementC.zip](https://github.com/godotengine/godot/files/2277853/LogicMovementC.zip)

**Comment by exts** [comment]
Commenting out these lines:

```
    // PackedScene PlayerPrefab  = (PackedScene)ResourceLoader.Load("res://Instances/Player.tscn");
    // PackedScene ControlPrefab = (PackedScene)ResourceLoader.Load("res://Instances/Control.tscn");
```

Then following these steps:

- delete .mono folder
- remove script from scene
- restart godot
- readd the script to the scene
- play the scene to trigger a rebuild

It should never crash. use `Load` inside `_Ready()`

The issue was godot wasn't refreshing assemblies and it instantly crashed the editor because it had a problem trying execute the assignment of the resource loader.

The underlying problem, I have no clue

**Comment by somnivore** [comment]
I'm also experiencing this issue on d16ce4a8edb26fb4730c51405662479f7ebf6617.  I had a script attached to a node, then decided I didn't need that script anymore so I deleted the script from the project, and removed the nodes with the script.  Now, trying to playtest, or trying to build the project, Godot will crash with this error:

```
ERROR: get_m: FATAL: Index p_index=0 out of size (size()=0)
   At: ./core/cowdata.h:142.
```

**Comment by akien-mga** [comment]
The MRP in OP does not seem to crash in 3.1 beta 6, so it seems to be fixed.
