### ISSUE TITLE
CollisionObject function to get name of shape source node

### ISSUE THREAD

**Issue by ilearain** [godotengine/godot#2089]
String get_shape_source(index)
property to CollisionObject so the name of the node it comes from can be retrieved in runtime

Thanks..

**Comment by aaronfranke** [comment]
@ilearain Can you describe your issue further? Perhaps provide an example usage?

**Comment by kubecz3k** [comment]
_I believe_ it was about an ability to get the name of the CollisionShape node from the shape index. As far as I remember you are able to get an index of the collision shape when the collision is detected (so with this index you can determine which shapes were involved in the collision (if you remember the order of the CollisionShape nodes in the scene tree) 
So I think this issue is about an additional function that would allow you to get the name of the collision shape from this index (so you could write code that's independent of the ordering of the shapes) 
Use case: I remember that in our RigidBody Platformer 3D demo the index was used to determine if we are colliding with the floor or not (if player's RayShape was involved in the collision you were able to assume it was floor collision).

**Comment by akien-mga** [comment]
As this issue is quite unclear and did not get much interaction from other interested users, I'll close it.

If you understand what is requested here and would like something along those lines, please write a proposal on https://github.com/godotengine/godot-proposals.
