### ISSUE TITLE
Index GDScript files for better autocompletion

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#20902]
The GDscript autocompletion is pretty poor. This is natural as it's an interpreted language, but there are ways around this. The most popular solution to this (and the one taken by PyCharm, JetBrains' amazing Python IDE) is to index the script files on first load and cache these indices so that subsequent loads don't need to reindex. This would allow much better autocomplete suggestions. Of course, a file would need reindexed when changed, but this could be an asynchronous process. The last requirement would be to have a convenient way to force a cache invalidation and reindex all files in the project.

**Comment by vnen** [comment]
I can't see how completion is made better by an indexing system. Currently all loaded resources are cached (which includes the scripts) and the code completion lookup for referenced scripts to find suggestions as well. How the index would be different from this?

This is a bit of the XY problem as well: you are suggesting a solution but didn't really state what you're trying to solve. It's simpler if you mention a few cases were completion fails, and then how your suggestion can help in those cases.

**Comment by jonbonazza** [comment]
Usually, the issues I see are that the gdscript editor isn't aware of the type of most variables, so we don't get autocomplete information for hardly anything. This is a natural issue for dynamic typed languages and an indexing system is the usual approach to solve this, as the index can contain the type and properties of all variables so that they can be quickly looked up. I'm suggesting this approach because this is the de facto solution taken to solve this exact problem (along with other problems as well) in many IDEs.

**Comment by jonbonazza** [comment]
When indexing a file, you can infer the type and figure out all of its
properties thats the point of indexing vs just caching. Then autocomplete
just becomes a lookup in the index cache.

**Comment by vnen** [comment]
> When indexing a file, you can infer the type and figure out all of its
properties thats the point of indexing vs just caching.

Sure, but I mean is that it has to improve inference in the first place. Otherwise the end result will be the pretty much the same from the user's perspective.

**Comment by jonbonazza** [comment]
Well, yea, but indexing in the way i am suggesting makes this much easier. And its more than just knowing the type of a variable, you also need to index all of the properties of each type as well. 

At any rate, I if you can come up with a better way to enable better autocompletion, that's fine too. Indexing is just the  usual way this problem is solved. But as it stands,  the current autocomplete is borderline useless. Getting it to a usable state is what's ultimately important to me.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
