### ISSUE TITLE
Provide access to object bounding box in shader

### ISSUE THREAD

**Issue by Jason0214** [godotengine/godot#20900]
**Issue description:**

I am working on godot-blender-exporter,  a lot of blender cycle materials make use of blender's  `Generated Texture Coordinate` (it is an uvw in object's world bounding box) and also `Generated Texture Coordinate` is useful for `anisotropy`. 

- visualize Generate Texture as color
![image](https://user-images.githubusercontent.com/19422835/43986338-625d0338-9cc4-11e8-8d0a-7de3deed7f2a.png)

 If bound box is providing in godot shader script as a builtin, then it is possible to generate the same uvw as  'Generated Texture Coordinate' in godot and it is not costly to do it.

I have found unreal has Objects Bound and Object Position available in shader. https://docs.unrealengine.com/en-us/Engine/Rendering/Materials/ExpressionReference/Vector

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
