### ISSUE TITLE
Better error detection in gdscript editor

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#20903]
As it stands, the gdscript misses more errors than it detects. This results in longer iteration cycles as you end up missing a lot of things that should be easily caught before running the game. There are a couple options to improve this that I can think of:

1. **Live interpretation** - If we interpret the code asynchronously as we type (or even just do it on file save), we can catch a lot more stuff.
2. **Code indexing** - In #20902, I suggested indexing for autocompletion purposes, but this index can also be used to provide better code inspection, allowing us to catch many errors that would normally be detected at compile time by compiled languages.

**Comment by akien-mga** [comment]
CC @vnen @bojidar-bg

**Comment by jonbonazza** [comment]
@akien-mga @vnen @bojidar-bg Any other discussion that can be had here or is this pretty much DoA?

**Comment by bojidar-bg** [comment]
Well, it is a pretty complicated topic to discuss, and since both I and vnen don't seem to want to bikeshed about it, discussions have been pretty low.

That being said, researching how such code analysis can be implemented within the current frame of GDScript, or how other languages and linters do it, can be helpful to the discussion.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
