### ISSUE TITLE
New tileset editor- ability to set a non rectangular area

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#20927]
**Issue description:**
The new tileset editor by @MarianoGnu is fantastic. It seems to however be missing one really important feature- or at least I cant seem to find it by holding ctrl or shift modifiers

That feature is to add to area selection.
as a result we can only set rectangular areas and it fails in cases like this one:
![nonrectarea](https://user-images.githubusercontent.com/6495061/43995526-bfa8e88a-9da6-11e8-9896-0f5dd8503531.gif)

![tf_beach_tileb](https://user-images.githubusercontent.com/6495061/43995546-fe1416bc-9da6-11e8-8dfd-47548e730dec.png)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
