### ISSUE TITLE
User defined global scope methods

### ISSUE THREAD

**Issue by joleeee** [godotengine/godot#20926]
If this should be posted somewhere else, please let me know.

I think it would be useful if the user could make their own methods in global scope.
One example could be a custom random method like choose(var1, var2, var3, ...) but that would be up to the user to implement.

Please let me know if you have any thoughts.

**Comment by Calinou** [comment]
[A pull request implementing this](https://github.com/godotengine/godot/pull/15639) was opened a while ago, but it wasn't merged.

**Comment by vnen** [comment]
I dislike anything in the global scope. It's quite easy to make mistakes and it also has problems dealing with conflicts.

To solve this you already have two options: add an autoload singleton with your functions, or add a script class with static functions. Both need to be called with a namespace (`Singleton.function()` or `ScriptClass.function()`) but at least it doesn't have the ambiguity problem.

**Comment by PetePete1984** [comment]
Adding on to this, there are currently a bunch of useful math functions living in the global namespace that would be better placed in a Math utility class, like the one we have for Geometry already. Backwards compatibility could be ensured through aliases (and optionally deprecation warnings for the future).

**Comment by akien-mga** [comment]
Related to #15586.

**Comment by mnn** [comment]
> Both need to be called with a namespace (`Singleton.function()` or `ScriptClass.function()`) but at least it doesn't have the ambiguity problem.

I personally dislike having to specify namespace every time when it comes to frequently used utility functions. I also believe with types such issues will be caught quickly by "compiler" (not sure what it is called in Godot, type-checker?).

> It's quite easy to make mistakes and it also has problems dealing with conflicts.

They don't need to be global in true sense, in many languages (e.g. Haskell, Scala) you can `import` other module/package (file) and you will get all functions (and other things) visible in current scope (which doesn't need to be a whole file/class, it can be just one function). These languages also support selective importing (e.g. only one function) and renaming to avoid conflicts. I think such solution would be most flexible, user could specify where and what they want to import.

**Scala example**

NumUtils.scala:
```scala
object NumUtils {
  def add(a: Int, b: Int) = a + b
}
```

StringUtils.scala:
```scala

object StringUtils {
  def stress(x: String) = x + "!"
  def shout(x: String) = x.toUpperCase
}
```

Main.scala:
```scala
// import all
import NumUtils._

// import one function
import StringUtils.stress

// import one function and rename
import StringUtils.{shout => myShout}

object Main extends App {
  println(add(1, 2)) // 3
  println(stress("Hello")) // Hello!
  println(myShout("Hi")) // HI
}
```

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
