### ISSUE TITLE
Ability to set collision intensity on a per object basis

### ISSUE THREAD

**Issue by AKashyap86** [godotengine/godot#20938]
What this could accomplish ->
For instance there is a complex object, interactable with the player as well as the bullet.
Then if the intensity of collision is set to some percentage which will round off the value set to a feasible number, then the player could have less intensity and the bullet more, so player will only collide and not get trapped in between small crevices like it usually would , but the bullet due to its size, will easily escape.
so eg 50 percent collision could set the collision points from 8 to 4, for that particular object, using formulae to convert them to a similar polygon.

**Detailed steps to reproduce the scenario -->**

- Open the default rigid body 2d platformer template. Now add few extra tiles but with ground elements which are hinge shaped instead of square shaped. Imagine the hinges facing up.
- Now because of the hinge shape, the player, by default will collide and get trapped inside the hinges if they are small enough.
- If the percentage could be set of the collision intensity for the player, then eg if collision intensity is 40 percent, then the player will feel that hinge shaped platform as a square platform and walk right over it.
- In the same scene, if a bullet's collision intensity is 100 percent, it will feel that hinge shaped platform as it is, and the bullets will go inside the hinges of the hinged platform, like it happens normally.

**Comment by aaronfranke** [comment]
No offense but you need to explain your feature request a lot better. I don't understand your post.

**Comment by AKashyap86** [comment]
Hi I have edited the description, is that ok now ?

**Comment by raymoo** [comment]
What is collision intensity?

**Comment by AKashyap86** [comment]
Hi collision intensity would mean strength of collision meaning.  If some
object has eg an 8 faced box . Then if intensity is 50 percent it will
straight away become a 4 faced box .

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
