### ISSUE TITLE
Option to include the ability to use percentage of tile set and ability to use 2 or more tiles on single grid element

### ISSUE THREAD

**Issue by AKashyap86** [godotengine/godot#20937]
Hi . This could accomplish great things, primarily being the ability to not use redundant tile images, so game size would be less, and game would be quicker to load as well !!

For instance, now I have few different types of end wall elements in the tile set based on different things, like snow, trees on the end wall etc, but if such a function exists, then I could have only 1 tile for the end wall element, say only 20 percent from the far right, then combine with any of my other 80 percent from the far left wall tiles to make an end wall, among other things like practically reducing the count of tiles in my tile set from 150 or so to 50 or so or even less

**Comment by AKashyap86** [comment]
ok but wouldn't that cause more heat ? as 2 different tileset nodes and 2 different images, even if transparent, it will still load the image first. im sorry if this is a stupid question as I am still learning, but thats what I understand . But I will use your solution for now.

**Comment by vnen** [comment]
> ok but wouldn't that cause more heat ? as 2 different tileset nodes and 2 different images, even if transparent,

Could be the same image. You shouldn't worry about performance, unless it's already a problem.

I might have misunderstood what you want. What I understood is that you want to create layers of tiles so you can make compositions of them instead of making a big image with all variations. If that's the case then my proposed solution should be enough. Performance should be about the same and you have way more flexibility: you can do as many layers as you want and you can cut the layers in any shape you want.

**Comment by AKashyap86** [comment]
OK . thanks for the solution, it looks good enough for now. I am not sure I understand you 100%, but I do at least 90 percent and your solution should solve my issue I think. What I get from what you are saying, that on every particular tile space on the main level scene, I can use two and even more tiles and combine them to make the effect I want. ?? Cool . sounds like it I think .

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
