### ISSUE TITLE
Better Character Controller demo with 3D KinematicBody that's ready to use in user project

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2099]
Something like [Unity's Character Controller](http://docs.unity3d.com/Manual/class-CharacterController.html) would be a great addition. It would lower the entry barrier greatly.

**Comment by reduz** [comment]
KinematicBody is much better than Unity's CharacterController already, and
you can use any kind of shape too, not only a capsule.

**Comment by seadra** [comment]
Right, but there is nothing in godot that handles slopes/anti-jitter. I know, there isn't a solution that is going to fit everything other than DIY, but it definitely would have it's uses.

Maybe such basic things can be bundled with godot? (like Unity's prefabs)

**Comment by reduz** [comment]
Maybe a demo

**Comment by LeonardMeagher2** [comment]
@seadra 
You could create your own scene that handles this and share it with others on the forum / facebook group. A scene in godot is a lot like a prefab in unity, but better (imho).

if you haven't seen this
http://www.reddit.com/r/godot/comments/21vp08/i_made_an_fps_demo/

there are a lot of ways you can make this possible.

**Comment by Krzycho666** [comment]
What I love Godot at this moment for is that it is not Unity. All non commercial games on the market started to look and work in the same just way a couple of years ago, when Unity begun to be more and more popular. This is because of the premade prefabs that cover most of the game functions. They are gluted and fixed to each other over and over again giving very thesame output with slightly different graphics.
I will hate the day, that will bring asset store to godot.

**Comment by draxdeveloper** [comment]
using a asset from a asset store is a choice, so if you don't want you
don't need to use it.

2015-06-18 7:21 GMT-03:00 Siewio <notifications@github.com>:

> What I love Godot at this moment for is that it is not Unity. All non
> commercial games on the market started to look and work in the same just
> way a couple of years ago, when Unity begun to be more and more popular.
> This is because of the premade prefabs that cover most of the game
> functions. They are gluted and fixed to each other over and over again
> giving very thesame output with slightly different graphics.
> I will hate the day, that will bring asset store to godot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2099#issuecomment-113100533>.
>



-- 
David Aguiar de Aquino Paiva

**Comment by Krzycho666** [comment]
Yes, but the developer is the one who chooses, not the players. So as far as developers choose to use those, players will have to "suffer" from it. And as you can see, they do use asset stores because of knowlage lacks, resources lacks and so on.
But it's not a good place for such conversation ;)

**Comment by kubecz3k** [comment]
To summarize this discussion:
As far as I understand  the solution for this issue would be to create new demo that demonstrates usage of KinematicBody in controlling 3d character. I assume this demo should be constructed in a way that will allow user to just copy/paste scene with 3d character and choose some parameters for him. I will change title of the issue to better reflect this findings.

**Comment by akien-mga** [comment]
Closing as there hasn't been any real activity nor interest shown in this request, and it can now be easily fulfilled by the community using the asset sharing library.

**Comment by Zylann** [comment]
I'm trying to get my hands dirty with KinematicBody, but I see no `move_and_slide` like in 2D.
So I tried `move()`, but my capsule body doesn't move at all because the velocity is slightly pointing down due to gravity... same result with a slope.

So... I don't see how KinematicBody is better than Unity's CharacterController at the moment. It looks like I have to implement some workarounds and boilerplate to make it work :/

**Comment by CarlGustavAlbertDwarfsteinYung** [comment]
There's no demo or example that  I could find that correctly demos KinematicBody to make is_on_floor and is_on_wall work correctly and remove jitter.
