### ISSUE TITLE
Import Blender grease pencil animations in resolution independent format

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#21056]
**Feature description:**

Blender's new grease pencil is incredible.
https://www.youtube.com/watch?v=pywbPQD9vYU
I keep wondering if it will become possible one day to export grease pencil animations to godot- as resolution independent mesh geometry- all frames in a single file. The next question is of course how. I know that godot now has some support for svg- svg assets. Even though it has some limitations:
https://github.com/godotengine/godot/issues/16180
Svg files however can not store multiple frames. 

Perhaps it would be better if blender exports all frames as a gltf file. It is important to remember that the grease pencil objects still have z-depth.
This needs to be coordinated with blender devs from early on imo. But even if some of the effects get lost on export- it will be quite exciting for animators to see those beautifully rendered resolution independent crispy clean lines working with the same performance in godot

Lets not forget that another open source 3d engine has already added support for grease pencil animations:
![capture](https://user-images.githubusercontent.com/6495061/44165580-06eb0d00-a0c1-11e8-99dd-0dac6b0d56eb.PNG)
https://www.youtube.com/watch?v=d8ytbjLZ8Es
https://github.com/armory3d/armory/search?q=grease&unscoped_q=grease

**Comment by blurymind** [comment]
Perhaps related, @poke1024 is working on an svg rendering framework for godot
https://github.com/godotengine/godot/issues/16180#issuecomment-413356539
However not sure if it can be used for animation 

@reduz also noted on facebook if this is to be imported from blender, it could be done as a tscn file
https://www.facebook.com/groups/godotengine/permalink/1350540425082548/?comment_id=1350699718399952&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by TheYokai** [comment]
Just adding that I'd really love to add grease pencil support. I'll perhaps contact someone at #blendercoders irc to see if we can get the ball rolling on grease pencil support within godot.

**Comment by randombenj** [comment]
This would be very nice in deed. What would be even more awesome is if you could export grease pencil as 3D assets as well:

https://blender.stackexchange.com/questions/175218/export-grease-pencil-to-godot

**Comment by blurymind** [comment]
I think we probably can - if we convert them to mesh data. In that case its a matter of writing a plugin for blender that bakes grease pencil data to mesh and exports it as gltf that godot can consume

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
