### ISSUE TITLE
Add option to copy path/name/value of setting

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21077]
**Godot version:**
3.1 calinou c4e75aa

**OS/device including version:**
Windows 10

**Issue description:**
It would be nice if in settings(both Editor and Project) would be option to copy things by right-clicking, because it is possible to do mistake when rewrite it. 

I think there should be 4 options:

Copy name - Copy only name of setting e.g.       **timestamping_authority_url**
Copy value - Copy only value of setting e.g.      **true** or for colours **#ff22aa**
Copy path - Copy path e.g.      **Export/Android/jarsigner** 
Copy all - Copy path and value e.g.      **Export/Android/jarsigner -> #ff22aa** 

![fffffff](https://user-images.githubusercontent.com/41945903/44208650-479a6300-a161-11e8-83a1-fa281e6a9dd4.png)

**Comment by Zylann** [comment]
Same for the inspector, which should work anyways because it has been re-used in settings.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
