### ISSUE TITLE
Move material attributes from shader declaration

### ISSUE THREAD

**Issue by kosz78** [godotengine/godot#21105]
I have some proposal for shader material optimization.
Currently material properties such as `blend_xxx`, `depth_xxx` and `cull_xxx` are declared in shader code.
It is required create a lot of similar shaders with different combination of these properties that affect on number of shaders and compilation time. 
If these properties will be moved to material properties it will significant reduce amount of shaders and reduce total compilation time.

**Comment by karroffel** [comment]
I am implementing stencil buffer support right now in a fork, for that I want to be able to set the reference values and the mask values via a script without recompiling the shaders, so I am hardcoding a system like this for my usecase right now.

I agree that such a material/shader-wide parameter system would be better than hardcoding the values into the shader source code.

**Comment by akien-mga** [comment]
Moving to the 3.2 milestone where most new rendering features will be considered, it's too late for 3.1.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
