### ISSUE TITLE
Better tileset view

### ISSUE THREAD

**Issue by TheRadMatt** [godotengine/godot#21118]
The current tileset view is not very usable. It's clustered, you can't find anything and tile sorting is confusing. It certainly doesn't work with lots of tiles similar to each other:
![obraz](https://user-images.githubusercontent.com/28545953/44270126-d5944d80-a236-11e8-8c2e-5bac55efa93d.png)

It would be more usable if it looked like this:
![obraz](https://www.download.net.pl/upload/Screeny/rpg1.gif)
(picking tiles directly from the tileset)

**Comment by Zylann** [comment]
A tileset can be created out of separate images, so tileset resources are just a list of tiles in whatever order they come.

For this to work both with atlas imports or even posssibly custom placements, maybe we could include editor-only tile positions in tilesets?

Or have a display mode where we gather all images referenced by the tileset, and have tiles being displayed over it based on their region rect rather than the order in which they appear?
That would apply only on simple tiles though, not sure how autotiles would be layed out.

**Comment by MarianoGnu** [comment]
Yeah, but probably view like the tileset's editor by texture would work....

**Comment by Lucrecious** [comment]
Actually, all this would be perfect if we gave users a "workspace" where they could place their tiles on a grid however they want - kind of like paint on a pallet. They could place them down, then maybe hit a "lock" button so they can't move them around accidentally.

As an extension of that, users would be able to save multiple pallets as presets and pick the correct one for certain level schemes or something. Or even separate presets by tile types: Doors, Ladders, Walls, etc.

Hmm... I might try to implement something like that when I get some free time sometime in August haha

**Comment by bojidar-bg** [comment]
(AFAIR) During the Godot Sprint in Brussels, it was discussed that the tilemapping experience will be redone for 4.0, which would likely allow for palettes and whatnot.

**Comment by Calinou** [comment]
We could solve the issue of tile wrapping by removing the names below each tile (and making them appear in a tooltip instead). However, I fear this may actually decrease usability in some cases. What do you think?

**Comment by Calinou** [comment]
This is addressed in the new TileMap and TileSet editors in 4.0, closing. See also https://github.com/godotengine/godot-proposals/issues/1769.
