### ISSUE TITLE
Automatic Scene/Script Dependency Removal From Scenes

### ISSUE THREAD

**Issue by 11clock** [godotengine/godot#21124]
One of my biggest issues with Godot right now is that, before I can delete a widely used instanced scene or script file, I need to manually go to each scene that uses said resources and remove them one by one. This can be a very painful process, while other engines such as GameMaker and Unity handle all of this for you (you delete an object/prefab, it is removed from all rooms/scenes it is used in).

I recommend an option to automatically remove in-scene uses of an instanced scene or script when you delete the corresponding file. This would save a lot of headache and make it much easier to delete code. Being able to refactor and delete code easily is very important for longterm project maintenance.

**Comment by Zylann** [comment]
> This can be a very painful process, while other engines such as GameMaker and Unity handle all of this for you (you delete an object/prefab, it is removed from all rooms/scenes it is used in).

AFAIK what Unity does actually is to load the script or prefab as an "Invalid Placeholder", rather than preventing the scene from loading at all. So it does not clean up, but at least it allows the asset to be deleted or replaced without locking out half of the project. This also covers a case where a deletion was not intentional, since the placeholders can retain properties.

If we go the route of deleting nodes, note it will also delete child nodes as well. It probably won't be undoable as well.

**Comment by Calinou** [comment]
> Also should this be in proposals?

Yes :slightly_smiling_face: 

Please open a new proposal that follows the template. From a quick search, I couldn't find any existing proposals about this
