### ISSUE TITLE
Multi-line strings and multi-line comments should have different syntax (and color)

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21142]
I think syntax _"""_ serving both as a multi-line string and multi-line comment is a bad design choice.

First reason: same color for two different things: confusing.

Second reason: problems with parsing, e.g:
<code>""" comment """ var x = 0 """ comment """</code>
<code>""" comment """ var x = 0; """ comment """</code>
<code>var x = 0; """ comment """ var y = 0;</code>
<code>var x = 0; """ comment """ var y = 0</code>
These all fails with:
_Expected end of statement after expression._

**Comment by akien-mga** [comment]
> I think syntax """ serving both as a multi-line string and multi-line comment is a bad design choice.

Yeah but it's Python's, and we're trying to stay close to its syntax.

But actually, we don't really support multi-line comments with this syntax. `""" """` creates a multi-line string in Godot, which can incidentally be used as a docstring-style comment in most situations because it's just evaluated as `true`.

So fixing this issue is just a matter of setting the default color for multi-line strings to be the same as for normal strings.

**Comment by ItsAleph** [comment]
Any update?

**Comment by akien-mga** [comment]
This was fixed 5 years ago. If you experience something similar in the latest Godot release, please open a new issue.
