### ISSUE TITLE
When EditorSettings:use_external_editor is on, right-click on a Script icon to open Godot Script Editor

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#21140]
**Feature request!**
Now and then, you'd want the best of both world.
Right-click on Script icon doesn't do anything for now and seems available for this.

**Comment by akien-mga** [comment]
I agree with adding a feature for that, but I'm not sure that right-click on the Script icon would be intuitive for that.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
