### ISSUE TITLE
Hash Set type?

### ISSUE THREAD

**Issue by Dharengo** [godotengine/godot#21143]
**Issue description:**

I'm sorry if this has been suggested before. I tried searching but I couldn't find a similar topic.

Anyway, is there a use for a hash set type? You know the type that's kind of like a dictionary only the value is also the key? It allows for easy (O(1)) checking whether or not an item exists in a set. And also allows you to compare different sets and combine them in different ways. I personally think it would be pretty useful. Or do you think users should just extend Dictionary and write some functions like intersect themselves?

**Comment by Mantissa-23** [comment]
These are really useful for very specific cases, and C# has one as part of the .NET core. Unless anyone's opposed, I'd be interested in implementing this feature for my own personal projects.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
