### ISSUE TITLE
Add duplicate functions in visual script

### ISSUE THREAD

**Issue by sami8github** [godotengine/godot#21170]
**Godot version:**
v3.1.dev.calinou.c4e75aa

**OS/device including version:**
windows 10 x64

**Issue description:**
In visual script:
Please add ability to duplicate functions ,and make the duplicated nodes (inside the duplicated function) unique to the original (when changing parameter of nodes the original stay not changed)

**Comment by fire** [comment]
Can you check if copy and paste does this? Do you want a specific duplicate node menu item?

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
