### ISSUE TITLE
[EditorPlugin] Input map doesn't work

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21218]
v3.0.5-stable_x11.64

It would be nice if Input Map works inside EditorPlugin too.

**Comment by char0xff** [comment]
Project Settings -> Input map allows to create actions and link them to key combinations.
So in GDScript you can do:
<code> Input.is_action_pressed("action_name"):</code>
This doesn't seem to work inside the editor though, when using EditorPlugin.

**Comment by paulhocker** [comment]
I do not think that is appropriate. Instead it should be something you can add to the editor hot keys. Input mapping is Game specific.

**Comment by vnen** [comment]
Have you tried restarting the editor after adding the action?

**Comment by char0xff** [comment]
@vnen Yes.
@paulhocker Yes, any other implementation would be fine.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
