### ISSUE TITLE
LightOccluder not always update shape when is hide

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21227]
**Godot version:**
3.1 calinou faa49c1

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
 When I Create LightOccluder2D and it property Occluder, after hiding it and change coordinates, shape not always is update in Viewport2D

**Steps to reproduce:**
https://streamable.com/nkp5o

**Comment by clayjohn** [comment]
Is this a duplicate of https://github.com/godotengine/godot/issues/21225?

**Comment by KoBeWi** [comment]
@qarmin The video is dead. Can you still reproduce this in [Godot 3.2.3 rc2](https://godotengine.org/article/release-candidate-godot-3-2-3-rc-2)?

The only problem I see is the polygon editor not updating the shape (orange lines) immediately after changing the points in the inspector. It's because the viewport isn't notified to be redrawn and you need to focus it with mouse.

**Comment by qarmin** [comment]
I tried to reproduce this several times, but without video I can't do it so I assume that this was fixed.

Since streamable deleted my first video I'm using embedded GIF's which seems to live longer, so in my newer bug reports missing videos shouldn't be an issue.
