### ISSUE TITLE
Querying inertia tensor from GDScript

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2125]
Is there a (or will there be a) way of querying the inertia tensor of a body? (something along the lines of [this](http://docs.unity3d.com/ScriptReference/Rigidbody-inertiaTensor.html) maybe)

**Comment by okamstudio** [comment]
there is an API, though i'm not sure it's available to scripting

On Fri, Jun 19, 2015 at 6:06 PM, seadra <notifications@github.com> wrote:

> Is there a (or will there be a) way of querying the inertia tensor of a
> body? (something along the lines of this
> <http://docs.unity3d.com/ScriptReference/Rigidbody-inertiaTensor.html>
> maybe)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2125>.
>



-- 

*OkamStudio*

**Comment by okamstudio** [comment]
It's generally kind of useless to mess with this value manually thought,
what do you want it for?


On Fri, Jun 19, 2015 at 6:07 PM, Juan Linietsky <juan@okamstudio.com> wrote:

> there is an API, though i'm not sure it's available to scripting
>
> On Fri, Jun 19, 2015 at 6:06 PM, seadra <notifications@github.com> wrote:
>
>> Is there a (or will there be a) way of querying the inertia tensor of a
>> body? (something along the lines of this
>> <http://docs.unity3d.com/ScriptReference/Rigidbody-inertiaTensor.html>
>> maybe)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/okamstudio/godot/issues/2125>.
>>
>
>
>
> --
>
> *OkamStudio*
>



-- 

*OkamStudio*

**Comment by seadra** [comment]
To calculate the rotation properly with KinematicBody.

**Comment by okamstudio** [comment]
oh I see, you can use apply_impulse for this, but I can understand you want
to calculate something manually, will use this issue to remember to expose
it.


On Fri, Jun 19, 2015 at 6:17 PM, seadra <notifications@github.com> wrote:

> To calculate the rotation properly with KinematicBody.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2125#issuecomment-113647505>.
>



-- 

*OkamStudio*

**Comment by seadra** [comment]
Also, when I override _integrate_forces for a player, I think I will need the inertia tensor again, right?

**Comment by seadra** [comment]
Can we call methods of the base class in gdscript at all?

**Comment by OlexiyKravchuk** [comment]
but apply_impulse () and _integrate_forces () are methods of the rigid body, rather than the kinematics?

**Comment by seadra** [comment]
Yes.
Let me explain it by analogy. Even though rigid body is about dynamics, you still need mass for calculations, right? You calculate change in velocity due to various things that don't come from physics engine (such as input, special items, etc.), and to convert that velocity into impulse, you need to know the mass (vice versa, it can come from other bodies too). This is why get_mass() function exists. But linear velocity is only about the motion of the center of the mass, there is also rotation.

Inertia tensor is like the mass for rotation.

**Comment by akien-mga** [comment]
What's the status on this? Is there now an API that addresses this use case, or do we still need one?

**Comment by seadra** [comment]
There's still no API for this...
Wouldn't Bullet physics allow this? Inertia tensor and it's inverse are defined in btRigidBody class, but we can't access it from GDScript.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
