### ISSUE TITLE
Allow different coefficients for static and kinetic friction

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2127]
How do I stop objects from sliding? They just slide all the way down they can, even when the friction is set to 1 for both of them.

It seems "friction" property in godot only controls kinetic friction. Please consider adding [static friction](http://docs.unity3d.com/Manual/class-PhysicMaterial.html) to the physics engine!

**Comment by seadra** [comment]
I realized that was a mistake by me, sorry! The slope has a non-zero constant_linear_velocity!
About static/kinetic friction, I'm guessing there is only one coefficient representing both in godot, right?

**Comment by seadra** [comment]
I still think it would be nice to have different coefficients for kinetic and static friction coefficients, which are quite different in magnitude in reality as well.

**Comment by bojidar-bg** [comment]
What's the status on this issue? I think it would be nice to have it figured out somehow....

**Comment by enricotj** [comment]
I'm having issues with this as well. After an object gets moving it appears there is no kinetic friction force to slow it down even if no further forces are being applied to it.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
