### ISSUE TITLE
Have in editor options to simulate common forms of color vision deficiency (color blindness)

### ISSUE THREAD

**Issue by Two-Tone** [godotengine/godot#21304]
A decent number of people suffer from being colorblind and as a result a lot of games are considerably harder or even impossible to play unless the devs specifically go out of their way to include colorblind modes.

My suggestion is to have toggles in the editor that lets the developer see what their game looks like if they had deuteranomaly, protanomaly, or tritanomly.  It'll help the devs who want to create color blind modes by letting them see what those users would see.

**Comment by Two-Tone** [comment]
I have no idea how this just submitted while I was still typing the freaking title.

**Comment by akien-mga** [comment]
Related to #15944.

**Comment by MattUV** [comment]
I think someone just watched the last GMTK video ;)

I don't know if it is necessary as part of the engine, but it may be a great plugin for the library!
Probably a rectangle with preconfigured shaders?

**Comment by Two-Tone** [comment]
The shaders to simulate these isn't at all complex (making the burden of maintaining them very small), but I definitely think it should be included by default to encourage devs to consider colorblind users and how their game looks to them. 

And yes, Mark Brown was definitely the inspiration!

**Comment by MattUV** [comment]
I don't know, I remember Juan saying he didn't want to bloat the editor. But I do agree with you, it is a major concern.

Anyway, either a plugin or an integrated option, here is the algorithm used by many tools online that I have encountered. 6 years ago I might have been able to understand everything but I haven't practiced mathematics since 2012 ;)
I leave the link here of someone wants to attack this issue: http://vision.psychol.cam.ac.uk/jdmollon/papers/colourmaps.pdf

**Comment by MattUV** [comment]
Alright, I have studied more deeply the algorithms (it is not that hard actually).
The link (a.) (links below) I have provided in my earlier post is correct, but only treats Protanopia and Deuteranopia. I would have to make more calculus for the Tritanopia. It is not impossible, but tricky. As mentioned here (b.), some algorithms that can be found online are wrong due to the misuse of initial hypothesis from (a.). I will not explain everything here, because (b.) does it better than me.

So, I think it is good to use the algorithm from (b.)
I will summarize it here, but I suggest you visit the link (b.), which is really interesting.

For each pixel of color [R, G, B] (R, G and B in the interval [0,1]), we want to calculate the colorblind equivalent depending on the pathology : 
 * Protanopia [Rp, Gp, Bp]
 * Deuteranopia [Rd, Gd, Bd]
 * Tritanopia [Rt, Gt, Bt]
![methode colorblindness](https://user-images.githubusercontent.com/13215043/44555770-14df0480-a737-11e8-9269-5795df67dad3.png)

 1. Remove the gamma correction to get [Rc,Gc,Bc], where:
   * **Xc = X/12.92** if X<= 0.04045
   * **Xc = ((X+0.55)/1.055)^2.4** if X > 0.04045
 2. Calculate the filtered color depending on the color blindness type :
   * Protanopia : **[Rpc,Gpc,Bpc] = T^-1 * Sp * T * [Rc,Gc,Bc]**
   * Deuteranopia : **[Rdc,Gdc,Bdc] = T^-1 * Sd * T * [Rc,Gc,Bc]**
   * Tritanopia : **[Rtc,Gtc,Btc] = T^-1 * St * T * [Rc,Gc,Bc]**
     * Where T, T^-1, Sp, Sd and St are 3x3 matrices :
![matrices colorblindess](https://user-images.githubusercontent.com/13215043/44554889-faa32780-a732-11e8-9f98-044c533a4053.png)

 3. Reapply the gamma correction to get the final value [Rp,Gp,Bp] :
   * **Xp = 12.92 * Xpc** if Xpc<= 0.0031308
   * **Xp = 1.055*Xpc^0.41666 - 0.055** if Xpc > 0.0031308

Sources:
(a.) http://vision.psychol.cam.ac.uk/jdmollon/papers/colourmaps.pdf
(b.) https://ixora.io/projects/colorblindness/color-blindness-simulation-research/

**Comment by ni-code** [comment]
Just leaving a note here, that there is the scribus.net opensource program that implements it, maybe ppl can take a look how they implement the shader.
Anyways, if possible, I wold like to have this godot.

![color_blind](https://user-images.githubusercontent.com/10292929/44556088-fcb7b700-a72f-11e8-9917-c7aee73e343b.gif)

**Comment by vnen** [comment]
I guess @paulloz was inspired by the same source: https://github.com/paulloz/godot-colorblindness

**Comment by MattUV** [comment]
Ha ha! This is going so fast!

**Comment by paulloz** [comment]
Haha yeah, I wanted to make something like this for a long time as I often struggle with some color choices in games I play. Mark's video was some kind of a reminder: now that I somehow know how to write a shader, I could finally do that.  
I looked for other assets in the library doing this kind of thing and didn't find any. But I didn't think of looking at issues down here. I'm glad other persons think this is important.

@MattUV IINW I approximate linear space [here](https://github.com/paulloz/godot-colorblindness/blob/master/addons/paulloz.colorblindness/colorblindness.shader#L54). I'll have a look at your calculation and see if there's any major difference between the two. Thanks!

Cheers all ❤️.

**Comment by NuclearCookie** [comment]
I see you're hardcoding the gamme corrections. Is there currently no way to change the gamma value in the engine? 
Looking towards the future, I think it would be best to change the gamma computation here so that it works with different gammas.

**Comment by Calinou** [comment]
> Is there currently no way to change the gamma value in the engine?

Not that I know of. It's possible to perform some adjustments in 3D using a WorldEnvironment, but this only affects 3D rendering.

**Comment by Two-Tone** [comment]
I think that the issue of contributing bloat is offset by how small colorblind shaders can be as well as the benefit of making developing for the disabled easier in Godot. 

Even if we ignore all the current issues with the asset library, having this as a plugin greatly diminishes the usefulness of it simply because it's something most people don't consider. Having it in editor and easily discoverable will make it much, much more likely that devs will use the tool and develop for the colorblind.

**Comment by paulloz** [comment]
Trust me, it's (sadly) not something most people will consider whether this is part of the engine or not. It's often not considered even if I'm right in front of the developers in a convention saying that their colour choices aren't right.  
This issue will only be dealt with through educational content, whether tools are available within the engine or as external resources.

**Comment by KlemensStrasser** [comment]
@paulloz - I wouldn't say so. @Two-Tone is right that having it in the engine increases discoverability and thus, raises awareness that this issue even exists. I would argue that many game developers do not even think about something like color blindness. Having an option for a color blindness might be enough to get somebody to look into it. So I would strongly suggest putting it in the engine, even if its just to have feature parity with the [Unreal Engine](https://api.unrealengine.com/INT/BlueprintAPI/Widget/Accessibility/index.html).

**Comment by Two-Tone** [comment]
Ported this over to https://github.com/godotengine/godot-proposals/issues/473, closing here.
