### ISSUE TITLE
Expose Frequency Analysis through Audio API

### ISSUE THREAD

**Issue by nhydock** [godotengine/godot#21329]
Frequency analysis of audio is useful for many applications in games, especially for rhythm games and providing visual effects based on audio.  Analysis typically relies on FFT, and since [FFT utilities are already present in part of the code base](https://github.com/godotengine/godot/blob/89132224a651c0e0d4121270f63decb9a678ff88/thirdparty/opus/celt/kiss_fft.h), and with FFT based calculations already being done within [audio effects](https://github.com/godotengine/godot/blob/27731a86d2003e0b98a217d191dc7e180ddf043b/servers/audio/effects/audio_effect_pitch_shift.cpp), providing a friendly API to access the data could potentially simplify audio effect code, make it reusable, and expose valuable information to scripters.

Example friendly Audio Anaylisis API reference that could be used as a basis
[AnalyserNode WebAPI](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode)

**Comment by Bauxitedev** [comment]
In my [spectral visualizer](https://github.com/Bauxitedev/spectral-visualizer) I did this by using C# and including the MathNet package as a nuget dependency, which has a method to calculate the Fourier transform. It's not ideal, and I'd like Godot to expose this functionality directly, but it's a viable workaround for now.

Additionally, there's currently no way to get the actual real-time audio buffers. My visualizer just reads the entire sound and estimates where the playback head is according to the time spent since the sound started.

**Comment by KoBeWi** [comment]
Is it something like this?
https://godotengine.org/article/godot-32-will-get-new-audio-features

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
