### ISSUE TITLE
Godot should have a dialog editor.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#21323]
Godot should have some kind of dialog editor you could request strings, like some dialog visual manager, similar to unreal blueprints or godot already visual editor.

this could be useful for a lot of games that are heavy text like text adventures, VN, and rpgs.

This could be useful to have a central place to manage your game dialogs and even add translations or load fan translations from a folder, maybe a json file.

Also, this could be useful to add non text translations like maybe visual languages like sign language for deaf people.

**Comment by nhydock** [comment]
A lot of the translation related stuff is already present, along with requesting strings like you want.  Something like dialog or text heavy configuration is probably best suited to an external editor that your team's writer is already comfortable with.  Rendering dialog in your game is a different kind of user experience than just writing it, and there are components in the asset store and on github that can improve that experience for you.

http://docs.godotengine.org/en/3.0/tutorials/i18n/internationalizing_games.html

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
