### ISSUE TITLE
There is no way to disable shader visualization in the 2d mode of Godot.

### ISSUE THREAD

**Issue by Zababon** [godotengine/godot#21361]
**Godot version:**
 Godot_v3.0.6-stable_x11

**OS/device including version:**
Linux Mint 19

**Issue description:**
There is no way to disable shader visualization in the 2d mode of Godot. In 3d mode, you can click on `Perspective` in the upper corner of the workspace and select `Display Unshaded`. But in the 2D there is no such possibility.

**Comment by swarnimarun** [comment]
So you want to remove all the shaders and just show the sprites and also remove the light effects.

Am I correct or is there something more?

I really think wireframe will also look cool in 2D and make it easier to find objects in complex scenes.

**Comment by Zababon** [comment]
@swarnimarun I think there can be different reasons for this. In my case, I'm just tired of the constant vision of shaders. In addition, in case of an error in the shader code, the shader starts to unpleasantly slow down.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
