### ISSUE TITLE
REQUEST:: Cone/Pyramid/Cylinder primitive types for collision/physics bounds

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#2138]
As mentioned, Godot's physics engine is missing a very common shape type for use as a collision bound.

We have fancy shapes like *capsule* and *convex*, but we still lack a trio of basic collider shapes, that is the cone, the cylinder, and the pyramid.

Getting these committed will more or less complete the set as far as collision bounds go, I hope you will find it a good thing to include.

**Comment by reduz** [comment]
Pyramid is not a problem, but the others are not common at all on physics engines, given the SAT algorithm can't be used. They only exist in Bullet, which uses a different collision algorithm called GJK+EPA. I don't like this algorithm much because for games it's a little imprecise and requires users to set-up margins manually to all convex shapes.

As such, this can't be done. Even PhysX does not support cylinders
