### ISSUE TITLE
Improvement Suggestions to the New TileSet Editor

### ISSUE THREAD

**Issue by swarnimarun** [godotengine/godot#21384]
New TileSet Editor was added by,
https://github.com/godotengine/godot/pull/20585

I would like to suggest some improvement ideas for the new TileSet Editor system my list is short at the moment and I hope you guys will suggest more ideas to add to this.
These are all pretty important features that are needed for a proper TileSet Editor. Hope someone adds them before feature freeze. But they aren't major so can be worked on after feature freeze too.

**Suggestions**
- Make modulate property affect the look of a tile in the editor.
- Make the snapping grid a little more visible.
- Allow Ctrl + Scroll to zoom.
- Allow to adjust the texture region in the inspector and have it update in the editor.
- Add multi-tile select so that we can select multiple tiles at once and also ability to change some of there settings at once too
- Allow a button to lock the tile from being changed in size from the editor making it easier for just doing basic editing
- And the editor sometimes(most of the time actually) crashes on creating a new collision shape from the editor at least in my builds will try new ones soon.
- Add options to allow for animations in the tiles as the textures can now have animations, so it's certainly possible.
- Finally, add some grid slice buttons too so that people can directly get their tilesets sliced up and ready. And in the future also the auto-slice but that is not very important.

And so that no one calls me a slave driver I will try to complete as many features from this list as I have free time to do this weekend.

**Comment by paulloz** [comment]
* Bind the *Delete* key to delete the currently selected tile (for now it's still bound to the *Scene Tree* and makes you delete your *TileMap* node).

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by akien-mga** [comment]
Also CC @YeldhamDev and @guilhermefelipecgs who worked on some UX improvements for the new TileSet editor.

**Comment by stormi** [comment]
I would add:
* For autotiles and atlases, allow compound, non-rectangular, selections. I mean, if needed, select the tiles one by one, or allow to select a first rectangle then add to it by holding Ctrl and selecting a tile or another rectangle.
* Better outline which tile or group of tiles is currently selected
* In edit mode, do not default to "region" tool, because it is really too easy to click somewhere in the tileset in the hope that it will deselect the current item, to discover in the end that you just reduced your autotile to a single tile... I would suggest adding a select mode that would be the default
* Select mode would also allow selecting precisely which autotile/atlas/tile you want to edit, when regions overlap (one could argue that in a good tileset regions shouldn't overlap, but sometimes it's handy that they do).

**Comment by Rybadour** [comment]
I would love to see some ease on importing images for a Tileset.

Tonight I was trying to import one of Kenny's isometric tilesets and I found that I had to manually select the entire image as a "tile" and adjust the Tex Offset for each and every tile. All these tiles have identical dimensions and properties so there should be a simple way to import them automatically as tiles.

**Comment by chepulis** [comment]
A very simple autotile interface improvement suggestion:

- After the autotile was laid down, allow to click trough all possible options for that particular tile, always in the same order. That way i could have five tiles on the same bitmask, first click drops a random, second tile #1 and so on. I know that if i double click i get the #1, three times for #2 and so on. Easy to get used to and get wanted tiles quickly.

Alternative — always get another at random, but with Shift+click (or some other key) always lay down in order, including the first one.

**Comment by chepulis** [comment]
In addition: have a modifier key to lock a stroke into vertical, horizontal or 45° only. This is a common feature for graphics software and would allow more precise, intentional tilemap painting with straight rows and columns (and 45° would be useful for the 3×3 tilemap users). Adjust angles according to tilemap mode (Square/Isometric/Custom) and maybe add a nifty visual widget at the origin point of the stroke to feedback to the user that stroke is locked into straight line at this angle.

Adobe Illustrator and Photoshop use Shift for this. As far as i can tell, Krita [has some optional support](https://www.reddit.com/r/krita/comments/68mykl/hold_shift_to_draw_a_straight_line/) for this, also Shift.

**Comment by Calinou** [comment]
Closing in favor of [various proposals](https://github.com/godotengine/godot-proposals/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+tilemap+label%3Atopic%3Aeditor) in the Godot proposals repository, as feature proposals are now tracked there.
