### ISSUE TITLE
AnimationPlayer should be able to call functions in the preview

### ISSUE THREAD

**Issue by Piet-G** [godotengine/godot#21388]
I think it would be really useful to have the AnimationPlayer be able to call functions in the preview like it can edit properties. 
It being unable to makes previews look odd and not accurate when they rely on a function being called in the middle of the animation.

**Comment by PetePete1984** [comment]
This is the case in Godot 2, visible in the old Space Shooter demo: some of the on-death animations include a func track that calls `queue_free()` after 0.9 seconds, which then leads to the entire object deleting itself - after which you have to reload the scene (and don't save!)

**Comment by DualMatrix** [comment]
@PetePete1984 Hmm that is indeed not wanted behavior. 
It might be best to be able to toggle in the track whether it calls functions in the preview?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
