### ISSUE TITLE
ConvexPolygonShape2D can't be edited with mouse like CollisionPolygon2D

### ISSUE THREAD

**Issue by Maykeye** [godotengine/godot#21394]
**Godot version:**
3.1.dev.f72f744 

**Issue description:**
If you select ConvexPolygonShape2D a as collision shape, you can't draw its points with mouse, you can only manually enter their coordinates in the Inspector, which is tedious. 

Compare to CollisionPolygon2D which allows to use mouse to create a polygon.

**Steps to reproduce:**
* Create 2D scene
* Add CollisionShape2D
* Select ConvexPolygonShape2D as its shape
* Click anywhere on the scene hoping to start drawing polygon 
* Nothing happens

**Comment by eggnot** [comment]
It's still true on 3.2.1 stable for both ConcavePolygonShape2D and ConvexPolygonShape2D

**Comment by eggnot** [comment]
And also on 3.2.2 beta1

**Comment by Xrayez** [comment]
Yeah, I recall myself stumbling upon exact issue, but I'm not sure whether this should be a feature, because for polygon-based shape editing Godot has `CollisionPolygon2D` node specifically, which also handles:
- proper orientation of polygon being built (vertices could be set in either clockwise of counterclockwise order, which is important both for rendering and probably physics too, because inertia should be computed from polygon area, see #29867).
- convex/concave polygons, where polygons are decomposed into convex or remain segment-based.

So, there are several options to address this issue:
1. Actually implement it.
2. Remove `ConvexPolygonShape2D` and `ConcavePolygonShape2D` from the resource selection popup.
3. A mixture of (1) and (2), read on.

For simplistic polygon shape editing (which do not relate to physics, perhaps gameplay needs), this does make sense. Yet there are some inconsistencies between `ConvexPolygonShape2D` and `ConcavePolygonShape2D`, namely the former is represented as points, while the latter is represented as discontinuous segments, and makes it somewhat difficult to edit. This might add some extra complexity (which is possible to resolve), yet #32979 aims to fix it anyway.

To be honest, I don't quite see the point of having different convex/concave shapes to begin with, I'd just implement a single `PolygonShape2D`, add perhaps adding an enum to specify and/or calculate the convexity of polygons, just like in `CollisionPolygon2D` node with the `Build Mode` property. -1 class for Godot, less bloat. 😛

**Comment by Xrayez** [comment]
I've also expressed my views in the proposal at https://github.com/godotengine/godot-proposals/issues/1126#issuecomment-651185404, and could likely work on fixing this already in Godot, just need a blessing from other core devs.

**Comment by Xrayez** [comment]
Figured out how to edit concave (as well as convex) shapes through a similar node: https://github.com/GoostGD/goost/pull/2#issuecomment-652667575. I think it would be nice to add this feature to Godot, just because this would promote ease of use for plugins/modules (currently I have to edit the shape through another class, from which the shape is then assigned to `CollisionShape2D`, or it has to be first saved to disk as a resource and then set for both classes to propagate changes, which is not intuitive).

**Comment by Xrayez** [comment]
Upon further research I figured there's `CollisionShape2DEditor` which handle most common types except polygon types:

https://github.com/godotengine/godot/blob/b65ebfc7e720a947d3dab16824aa9975d50c5771/editor/plugins/collision_shape_2d_editor_plugin.cpp#L148-L152

But I find implementing polygon editing directly within this class to be problematic because there's already `AbstractPolygon2DEditor` which has it's own editing logic for that...

So, might be just better and easier to create `CollisionShape2DPolygonEditor` and register the plugin alongside `CollisionShape2DEditor`, and provide some comments about that.

**Comment by Xrayez** [comment]
Some discussion from IRC #godotengine-devel channel:
```
Xrayez> reduz: does it makes sense to fix/implement #21394?
Xrayez> If so I could work on that. Currently it's only possible to do this via CollisionPolygon2D, but not CollisionShape2D.
reduz> Xrayez: i think there is no benefit in doing that to be honest, this is a shape that only makes sense to use via code
Xrayez> reduz: would it make sense to remove ConvexPolygonShape2D and ConcavePolygonShape2D from the resource popup in CollisionShape2D?
Xrayez> so that users don't get confused, and go straight to CollisionPolygon2D node for that.
reduz> No, I would just put a configuration warning if you put a convexpolygon in a collision shape, saying this type of shape can't be edited manually, and suggest using a CollisionPolygon node instead
reduz> I mean we could make an editor, but whats the point
Xrayez> Well that's fairly easy to add since there's a AbstractPolygonEditor.
Xrayez> That's mainly due to https://github.com/godotengine/godot-proposals/issues/1126
Xrayez> Which wouldn't be solved on the core, but would allow consistency between what the core provides and modules.
reduz> not so easy because you need to ensure the polygon is always convex
reduz> so again I would not bother
reduz> adding a warning to avoid confusion imo is best
Xrayez> Ok I'll go for that.
```

**Comment by Mayt38** [comment]
I came here after some googling because the warning is actually confusing. I'd vote for removing the option in the droplist. Unless there is a use-case for not removing it ?

**Comment by Calinou** [comment]
@Mayt38 The option can't be removed from the dropdown as it displays all resources that inherit from the "expecte" type.
