### ISSUE TITLE
ScriptEditor - Export more data for EditorPlugins

### ISSUE THREAD

**Issue by linkpy** [godotengine/godot#21417]
**Godot version:** 3.0.6

This is more a feature request than an issue.

So, I'm actually making a documentation tool for Godot's GDScript (documentation strings, symbol database and all that fancy stuff) and I'll make an `EditorPlugin` for having an editor dock containing the documentation browser.

But, someone on the Discord server said it would be cool to be able to have a popup which displays the auto-completed symbol's documentation (or just the doc of the symbol under the cursor), so naturally I checked the built-in documentation for the `ScriptEditor` class, and there is no way to know where the cursor is in the script (for a very low-level access) or to know what is the symbol under the caret/mouse cursor (for a high-level access).

I'm here to ask if it's possible to make such an improvement of the `ScriptEditor` class for allowing plugins to do some stuff based on what the user is doing inside of the script editor (except for knowing when they changed the script or closed it).

**Comment by DualMatrix** [comment]
Related to the comment of akien-mga in #20569.

**Comment by Zylann** [comment]
It would be really cool to have access to script editors, in particular `TextEdits`, that would allow to hook a lot of interesting features to the script editors (such as code minimap, completion addons, Git diff gutter, expression evaluation, language server for C# etc).

**Comment by Overblob** [comment]
If I'm not wrong the Script Editor node is accessible from an EditorPlugin with:
`get_editor_interface().get_script_editor()`

Link to the [doc](https://docs.godotengine.org/en/latest/classes/class_editorinterface.html#class-editorinterface-method-get-script-editor)

**Comment by Zylann** [comment]
@Overblob yes, but it lacks a lot of functionality

**Comment by PLyczkowski** [comment]
Would love to have it too, to create custom editor macros. For instance: Select variable name foo, RMB, click on custom menu entry called 'Print Selected' (shortcut would work too), macro adds a new line with `prints("foo:", foo)`. Maybe my own version of replace all instances of a string that's faster than search and replace..

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
