### ISSUE TITLE
apply_torque_impulse() problem with Bullet 

### ISSUE THREAD

**Issue by HugoSlt** [godotengine/godot#21487]
**Godot version:**
Godot 3.1 #2928091

**OS:**
Ubuntu 18.04

**Issue description:**
With a simple pendulum (a RigidBody attached with a HingeJoint), if we apply
a single torque impulse, we expect the pendulum to start oscillating.
It correctly does so with GodotPhysics but it doesn't with Bullet. With
Bullet the pendulum starts rotating at constant speed.

Here is a video of the problem, first Bullet, then GodotPhysics.
![apply_torque_prob](https://user-images.githubusercontent.com/42741418/44664458-9bcffd80-aa13-11e8-9274-e2a535a7b2be.gif)

**Steps to reproduce:**
Create a RigidBody attached to a HingeJoint, apply a single torque impulse on it with `apply_torque_impulse()`. Switch between Bullet and GodotPhysics in the project settings
to observe the different behaviors.

**Minimal reproduction project:**
[apply_torque.zip](https://github.com/godotengine/godot/files/2324177/apply_torque.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania

**Comment by TGRCdev** [comment]
Currently testing on a build of ``master`` branch, commit 2db4942

The reproduction project gives the same result as the gif. However, when I tried to recreate the project, I didn't encounter the bug:
![bullet_joint](https://user-images.githubusercontent.com/4079184/44679475-18111380-aa09-11e8-9179-a61db2678b87.gif)

Here's my project recreation: [BulletJoints.zip](https://github.com/godotengine/godot/files/2325234/BulletJoints.zip)

**Comment by HugoSlt** [comment]
I confirm TGRCdev observation, same here : apply_torque.zip has the problem and BulletJoints.zip doesn't.

I think I found where the issue comes from : the centers of our RigidBodies are not at the same place.

In BulletJoints.zip, if you move the children of the `Box` RigidBody (i.e `MeshInstance` & `CollisionShape`) so that when you select the `Box`, the center of the `Box` is aligned with the pivot point like this :
![center](https://user-images.githubusercontent.com/42741418/44690644-ed03df80-aa5b-11e8-871b-0810ea0318b4.png)
then you get the same problem as in apply_torque.zip.

**Comment by TGRCdev** [comment]
Dang, nice find. Looks like Bullet uses the ``RigidBody`` node's position, while GodotPhysics uses the ``CollisionShape`` node's position.

**Comment by TGRCdev** [comment]
So I've looked a bit further into the differences in Bullet and Godot's ``center_of_masses``, and I have a modified apply_impulse.zip to show some of my findings.

[apply_torque_modified.zip](https://github.com/godotengine/godot/files/2326405/apply_torque_modified.zip)

Green Ball = RigidBody's origin
Red Ball = Center of mass

Left Slider = CollisionShape y translation
Top Slider = StaticBody y translation
Right Slider = RigidBody y translation

value of ``center_of_mass`` pulled from ``PhysicsDirectBodyState``
****
# GodotPhysics
![gdphysics_test](https://user-images.githubusercontent.com/4079184/44699380-e8d2c480-aa51-11e8-9f7e-0008cf44976e.gif)
- GDPhysics' center of mass is described in positional offset from the ``RigidBody`` node. (Took me a while to figure this out.)
- The center of mass is located at the center of all ``CollisionShapes`` under the ``RigidBody`` node.
- Multiple ``CollisionObjects`` modify the center of mass
- Changes to ``RigidBody.translation`` are completely ignored
****
# Bullet
![bullet_test](https://user-images.githubusercontent.com/4079184/44699705-74992080-aa53-11e8-95e8-87bb481e0b77.gif)
(The red ball is hidden under the green ball, because the center of mass is the ``RigidBody`` node's origin)
- Bullet's center of mass is described in global coordinates
- The center of mass is located at the RigidBody's origin
- Multiple ``CollisionObjects`` **do not** modify the center of mass, it always stays at ``RigidBody`` node's origin
- Changes to ``RigidBody.translation`` briefly moves the ``RigidBody`` node away from the ``HingeJoint``, but it snaps back after a few frames.

**Comment by HugoSlt** [comment]
Yes it's nice to be able to set the center of mass where we want by adjusting the relative position of the `RigidBody`/`CollisionShapes`.
Should we open a new issue on godot-docs to remember documenting this and close this issue ?
