### ISSUE TITLE
Error when trying to drag anything with a preview (regression from 683c3f2f)

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21493]
**Godot version:**
0565adb

**Issue description:**
When trying to drag a track inside an AnimationPlayer, this error will be spitted out:
`scene/gui/control.cpp:772 - Condition ' get_viewport()->gui_is_dragging() ' is true.`

**Comment by pgruenbacher** [comment]
this is due to a error condition introduced 4 days ago.
https://github.com/godotengine/godot/commit/683c3f2fcf0d9ade35e3f2ef180d42e35f800ad6

**Comment by volzhs** [comment]
it seems every preview for drag and drop is not working.
- dragging a node on scene dock
- dragging a node on filesystem dock
- dragging a track on animation editor
- creating a new node by dragging on visual script editor

**Comment by pgruenbacher** [comment]
lol uh oh.

**Comment by reduz** [comment]
seems to be my fault somehow

**Comment by groud** [comment]
The problem happens every time you need to generate a preview when dragging. The error appears also when dragging files.

@reduz: The problem is probably due to you adding an ERR_FAIL_COND() in 683c3f2fcf. The `Control::set_drag_preview(Control *p_control)` function is called when starting a drag which triggers this error
