### ISSUE TITLE
Drag and Drop object on scene incorrect placement 

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#21562]
[Godot 3.1 nighty builds]
3D project.

Hi there,

Drag and drop a tree on a terrain mesh, the tree is flying on the air far above the terrain mesh instead of beeing placed on top of the terrain where the mouse cursor is (mouse raycast)

**Comment by Calinou** [comment]
@DevMagicLord Please attach an example project where you can reproduce this isssue :slightly_smiling_face:

**Comment by DevMagicLord** [comment]
@Calinou 
This is not an issue, open any 3D project in Godot, drag and drop a prefab on the scene.

Your prefab won't position to other objects collision surface.

**Comment by DevMagicLord** [comment]
Watch the gif
https://github.com/DevMagicLord/Godot3/blob/master/bugs/objectsinscene.gif?raw=true

**Comment by DevMagicLord** [comment]
I hope someone will enhance this to really improve the workflow.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
