### ISSUE TITLE
Gridmap/Tilemap Editor -> Allow placing multiple tiles at one spot in a specific case

### ISSUE THREAD

**Issue by saranvdev** [godotengine/godot#21584]
At the moment it is not possible to place multiple tiles in the same position, no matter what. We need to create gridmaps/tilemaps for that (for example, one for walls, one for floors/decorations/wall decorations/carpets). It is a bit annoying but it works okay.

The problem appears when I want to place the same type of tile multiple times at the same spot.

**One example here:**
![imgur-2018_08_29-19 33 44](https://user-images.githubusercontent.com/15695377/44815803-ccb15d80-abe0-11e8-8657-f5ca76557e65.png)

I want to place three walls at this position and now it is a problem. Creating two more gridmaps and scripting them for just that is... cumbersome.

The other way is to create ~4 more 3D models with the walls positioned as they need to, to cover all possible cases. Again, too much work.

**I suggest to allow multiple tiles at the same position, if at least one requirement is met:**
1. The tile is different than the ones already placed on the map OR
2. The tile's rotation is different than rotation of the ones already placed

What do you think?

**Comment by Toshiwoz** [comment]
I agree that GridMap should be improved, and I know a complete rework is planned.
A way to make tile placement easier is one of them.
I am thinking that maybe a way to achieve what you want woild be to have different layers for the same MeshLib, and being able to switch between them with some shortcut + interface.
Because I had to face the same problem and couldn't find another solition but to use separate GridMaps, and that would probably won't help when using navigation.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
