### ISSUE TITLE
Meta links in a RichTextLabel aren't clickable in a table cell after a cell that has a line wrap

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#21613]
**Godot version:**
2ba42b7

**Issue description:**
When viewing warnings and trying to click in "(ignore)", it may be that sometimes it will be not clickable.

**Comment by vnen** [comment]
Oh, I forgot to open an issue about this, I actually bumped into this when doing the GDScript warnings panel. The issue is that when you have a table in the RichTextLabel and the cell has too much text that it wraps to the next line, when that happens the link in the next cell isn't clickable.

I guess we can re-purpose this issue for this, since it's not related to warnings but a bug in the RichTextLabel node.

**Comment by reduz** [comment]
Meh I wish someone else would adopt richtextlabel, its such a pain to work with :P
