### ISSUE TITLE
Enhance MultiMeshInstance runtime functionality

### ISSUE THREAD

**Issue by dark-penguin** [godotengine/godot#21631]
I realized that as it is now, there is not much use for MultiMeshInstance. To me, the most obvious use case would be generating massive chunks of blocks like in Zylann's Voxel Terrain plugin. However, in order to do that, we'd need at least the ability to hide individual mesh instances (to _easily_ gain performance when we know some of them are not visible, instead of doing proper geometry), add/remove them on the fly, and ideally overriding their materials (or at least textures) per instance. Currently, AFAIK it is not possible to remove a specific instance or add an instance without wiping the whole MultiMesh (and in Godot 3.0, even that works only half of the time and with various glitches).

If I understand correctly, the reason for using MultiMeshInstance is that it enforces using a simgle material for all instances to save resources on shader switching. However, if we only have few materials and few hundred instances, that would still probably be beneficial.

I would suggest adding more functionality:
- Adding instances
- Removing instances
- Overriding more properties of the instances, other than albedo vertex color/alpha and transform (at least material)
- Ability to hide the "original" mesh - to avoid having to treat it diffferently (i.e. currently it ignores overriding)
- By the way, storing instances in an iterable instead of an array would also help greatly (e.g. 3D voxel arrays created in random sequence...)

Does that make sense, or does it defeat the original purpose of MultiMeshInstance? I guess that would still be better than having thousands of MeshInstance-s...

While I'm at it, two more questions about MultiMeshInstance:
- What is the reason behind albedo color of the original affecting instances' color even if it is overridden? Does this make more sense than being able to "cleanly" override it?
- Why not set color_format and transform_format to something that works by default? This way, we'd free 50% users from having to worry about specifying those things before doing anything else.

**Comment by dark-penguin** [comment]
Oops! I missed this one: https://github.com/godotengine/godot/issues/17472
However, that one is only about materials/textures; I'm actually more concerned about adding/removing instances. If necessary, I can create several separate MultiMeshInstance-s per material. Being able to "mine" a specific "block", however, is way more essential, and it doesn't have many drawbacks, as far as I'm aware.

**Comment by clayjohn** [comment]
Multimeshinstances actually work using a special GPU function where all instances are drawn at once using a single shader and a single draw call. It is different than the normal Godot "instancing" where similar objects reuse the same shader. With a MultiMeshInstance  the entire group of meshes is drawn as if it is a single mesh. 

The reason updating just one is so slow is because the entire array of instance data needs to be reuploaded to the GPU every time it is changed. This is not a Godot limitation. If you need to have many instances that update their data quickly, use Particles. Particles use the same things behind the scenes but they calculate the per-instance transforms on the GPU so you dont incur that expensive data transfer. 

I hope that clears things up for you! :)

**Comment by dark-penguin** [comment]
I knew that it's drawn in a single call, but I did not know that it must be reuploaded on every change. However, that's not a big problem; the problem is that currently it's not possible to update a MultiMeshInstance at all (at least the last time I used Godot, which was still 3.0). I don't need to update it every frame, but certainly "adding an instance and reuploading the array" would be much faster than recreating the whole MultiMeshInstance object every time you need to change it. As far as I can tell by my tests, what takes most time is creating objects, so this is what I want to avoid.

**Comment by clayjohn** [comment]
Parts of this proposal are now covered by https://github.com/godotengine/godot-proposals/issues/412 and https://github.com/godotengine/godot-proposals/issues/957

Hiding specific instances is now easier in 3.2 as you can change the total number of instances separately from the number of instances being drawn. 

For the other proposals:

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
