### ISSUE TITLE
Allow AnimationTree's TimeScale animation node to have negative values so animations can be played backwards

### ISSUE THREAD

**Issue by Boothand** [godotengine/godot#21665]
**Issue description:**

It currently cannot go below 0, so can't be used to play animations backwards. The alternative seems to be an additional animation asset just for playing it backwards.
https://i.imgur.com/wysX8mu.png

**Comment by Xrayez** [comment]
I support this feature strongly because many animations are cyclic in nature (walking, falling, jumping cycles) and can be played backwards and therefore easily reused. Having to create another animation just for the character to walk left and right is really time consuming and can become a real workflow bottleneck.

Another reason is that when you change character's moving direction it's much easier to modify time scale dynamically on the same animation in order to remain the walking animation in sync with moving parts instead of having to seek the correct pose in other animation.

**Comment by guzzard** [comment]
@Boothand @Xrayez it's possible to set a negative value through script but it has some issue with looping animations though (#27215).

**Comment by rcorre** [comment]
If this is an "enhancement" rather than a bug, should [the docs](https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#timescale) claim it is possible?

> Allows scaling the speed of the animation (or reverse it) in any children nodes

**Comment by Smashalidis** [comment]
Just came here to support this - the docs claimed it was possible so I've been on a wild goose chase. This would be a very time saving and efficient addition

**Comment by KoBeWi** [comment]
Resolved by #53819

**Comment by KoBeWi** [comment]
Yes it's 4.0 only. Not backported due to difficulties (see discussion in the PR I linked).

**Comment by Ternvein** [comment]
Currently v3.5 documentation claims that negative time scale is possible, but it is not. Either documentation or code should be fixed then. I think that this feature is needed for v3.5 (or at least v3.6) and it's basic in nature.
