### ISSUE TITLE
Change/rename 'class_name' keyword to a single word

### ISSUE THREAD

**Issue by exts** [godotengine/godot#21666]
Today I [found out](https://twitter.com/reduzio/status/1018622630323261444) on discord that 3.1 will introduce a way to export scripts using the `class_name` keyword. The feature is great, but the keyword seems out of place when it comes to other [keywords](http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#keywords) and it's pretty rare to see a keyword with an underscore. It feels out of place.

My suggestion is to change the keyword to something like (a few of us on discord were brainstorming better keywords):

- script
- source
- exported
- register
- class (* read below)

\* Why not just use 'class' as the keyword (exported seems nice as well) because inner class name definitions follow a string and a colon while exported class names don't. So technically wouldn't that be easy to detect when it's being used in the correct context? I get why it also might confuse people, which goes back to why I think `exported` seems like a better keyword. It's very explicit and it's a single word.

eg.: 
- `exported Classname`
- `exported Classname extends Node2D`

**Comment by LikeLakers2** [comment]
I'm not sure I agree with the issue. For me, `class_name` is a lot more specific than anything I can think of, with maybe the exception of `script_name`. I also think it's more specific, more self-documenting than `script`, `source`, `exported`, or `register`; and I don't think making `class ClassName` be the new syntax would really be a good idea either, as that would affect readability.

I'd be all for a new single-word keyword, but right now `class_name` feels fine to me.

**Comment by Zylann** [comment]
> I agree, but my issue is the underscore and how out of place it looks as a keyword.

You won't like writing Godot shaders then :D

To me it felt weird too, not because of the underscore but the fact it's not just `class`. But I know the reason is contrary to languages like C# where files don't matter, GDScript is primarily a file-based-class language. They are also unnamed by default. Even though it has subclass which have names by simply writing the familiar `class Name`, the files themselves already represent unnamed classes and their definition block is the whole file already... hence why `class_name` ended up representing better what it does: naming the class. It also exposes that name to every other scripts as a result, since they live in the same "global" scope (which otherwise would be the filesystem).

**Comment by akien-mga** [comment]
I don't really see any problem with `class_name` myself, and indeed we already have other keywords with underscore like `shader_type`. Godot's philosophy is that explicit is better.

It's too late for such a compatibility breakage change too, as we're close to release candidate for 3.1.

**Comment by exts** [comment]
yeah unfortunate that its too late, this kind of got ignored when it first got introduced
