### ISSUE TITLE
Engine lag when selecting 3D node in heavy scene

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#21684]
**Godot version:**

Godot 3.1 Alpha 1

**OS/device including version:**

Laptop Asus K43SJ
GPU Nvidia GeForce GT 520M
CPU Intel B950 2Core 2.1GHz

**Issue description:**

Engine freeze for several seconds every time I select node (change selection from 1 node to another)
In the previous version I used (Godot 3.0.6) this also happen but only for the first time I select a node, and it freeze less than 2 seconds, so not really a big deal.

I attach the project, the scene is big around 65MB in size.

**Steps to reproduce:**
Just open Scene in the Models folder inside the Project that I upload and do what i describe in this issue description.

**Minimal reproduction project:**

[Godot31AlphaTry.zip](https://github.com/godotengine/godot/files/2343044/Godot31AlphaTry.zip)

**Comment by JFonS** [comment]
Looks like the slowness comes from here: https://github.com/godotengine/godot/blob/a1b578562a6db61db668c0ea620df9f23989d23f/editor/spatial_editor_gizmos.cpp#L2106

I would remove the debug wireframe since it's drawn on top of the mesh and not that usefult to me. Or at least debug lines should be cached the same way as `generate_triangle_mesh()` does.  

Speaking of cache,
https://github.com/godotengine/godot/blob/a1b578562a6db61db668c0ea620df9f23989d23f/editor/spatial_editor_gizmos.cpp#L2116
I think this line shouldn't be there, I don't know if it's left there by error or it has a purpose but I think cache should only be cleared when the mesh is modified.

CC @AndreaCatania

**Comment by reduz** [comment]
@JFonS I am not really sure the debug wireframe is worth it either

**Comment by AndreaCatania** [comment]
I think that the problem is due to SoftBody handles icons

**Comment by JFonS** [comment]
Yesterday I looked into this a little more. If the collision lines are not added everything works fine, so I will remove them. Since the gizmo already has collision triangles it won't make any difference.

**Comment by AndreaCatania** [comment]
Ok nice
