### ISSUE TITLE
Improve error messages when project can't start due to missing resource

### ISSUE THREAD

**Issue by schwitin** [godotengine/godot#21689]
Issue repurposed for related enhancement: the bug below was due to lacking a resource in the exported APK, as it has to be whitelisted manually.

Two things could be done to improve the workflow:
- Make the error reports clearer so that one knows that it's related to a missing file
- Detect such use of non-Resource files in editor, to warn the user about the need to whitelist them in the export manager

-----

**Godot version:**
v3.0.6.stable

**OS/device including version:**
Device: Samsung Galaxy S4 (GT-I9505)
OS: LineageOS 14.1 (latest)

**Issue description:**
My simple game works in IDE without errors. On Android the game wont start. 

**Steps to reproduce:**
- Export the project for android with defaults. 
- Upload APK to the Android device
- Install APK
- Run APK

Expected: I see my game.
Current: I see the splash screen of godot engine and nothing happens

logcat:
`
09-02 12:53:26.889   651   691 I WindowManager: OverscanTimeout run
09-02 12:53:29.112   651   690 I ProcessStatsService: Prepared write state in 3ms
09-02 12:53:29.114   651   690 I ProcessStatsService: Prepared write state in 2ms
09-02 12:53:30.779   651  3887 I ActivityManager: Setting hasTopUi=true for pid=1067
--------- beginning of main
09-02 12:54:54.417 13717 13734 E godot   : **ERROR**: Condition ' !f ' is true. returned: false
09-02 12:54:54.417 13717 13734 E godot   :    At: core/bind/core_bind.cpp:1558:eof_reached() - Condition ' !f ' is true. returned: false
09-02 12:54:54.417 13717 13734 E godot   : **ERROR**: Condition ' !f ' is true. returned: String()
09-02 12:54:54.417 13717 13734 E godot   :    At: core/bind/core_bind.cpp:1653:get_line() - Condition ' !f ' is true. returned: String()
09-02 12:54:54.417 13717 13734 E godot   : **ERROR**: Condition ' !f ' is true. returned: false
09-02 12:54:54.417 13717 13734 E godot   :    At: core/bind/core_bind.cpp:1558:eof_reached() - Condition ' !f ' is true. returned: false
09-02 12:54:54.417 13717 13734 E godot   : **ERROR**: Condition ' !f ' is true. returned: String()
09-02 12:54:54.417 13717 13734 E godot   :    At: core/bind/core_bind.cpp:1653:get_line() - Condition ' !f ' is true. returned: String()

`

**Minimal reproduction project:**

https://github.com/schwitin/math

**Comment by akien-mga** [comment]
You need to define your `tasks.txt` as custom resource in the export dialog (e.g. with the `*.txt` filter), otherwise it won't be included in the apk.

**Comment by schwitin** [comment]
Defining tasks.txt as a custom resource in the export dialog solves my problem.

**Comment by akien-mga** [comment]
I'll repurpose this issue for making the error reporting more useful, as currently unless you're very familiar with this common mistake, it's hard to understand.

**Comment by nightblade9** [comment]
I ran into the very same problem today. Turns out I'm reading from a .txt file and I didn't add it to the export list for non-resources.

Maybe there's a way to make this more user-friendly at export-time? I just get an infinite loop in the debug window that looks like this:

![image](https://user-images.githubusercontent.com/31222662/57055216-fc30d200-6c67-11e9-9db7-725b7544359c.png)

Ideally, I would like this to also fail when I run the game through the editor, with a clear message - that way, it's easy to at least figure out what changed that broke the game.

**Comment by mstfacmly** [comment]
I spent so much time looking to find some error that would help me figure out what the issue was, only to finally arrive here and realize it's because of a .txt file that wasn't exported. 

Godot's debugging tools are really fantastic, and the new warnings are very useful in terms of figuring out why something might not be working correctly, but this situation drove me crazy.

Maybe add a warning in the same vein as the "unused variable" warnings that could check for non-resource files being called by the script? It could be associated to the File function, since that's where it's likely to be used.

**Comment by akien-mga** [comment]
The error reporting has been made clearer already a while ago (it's still not perfect, but improving it further requires a redesign of our error reporting which is best suited for a dedicated proposal).
