### ISSUE TITLE
Mouse modes CONFINED and CAPTURE force cursor to center of window.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21744]
**v3.1.alpha_custom_build.f50dd68**

@capnm @guilhermefelipecgs Possibly some minor cursor issues.

### Ubuntu 18.04.1 LTS 64-bit 

Setting the cursor to confined warps the cursor to the center of the window.  Then when unsetting capture mode it does the same, forces the cursor back to center (perhaps intentionally).

### Windows 10 64-bit 

Windows 10 at least has the capture mode returning the cursor to center.

An example project for testing: [Constrained Cursor.zip](https://github.com/godotengine/godot/files/2347490/Constrained.Cursor.zip)

**Comment by capnm** [comment]
> the cursor back to center (perhaps intentionally).

Yes, on Linux changing the cursor mode to confined and captured moves
the cursor to the center of the window. I think this is a bug.

It only makes sense when you go **from a captured to another** mode,
because the actual coordinates could be somewhere outside the window.
Additionally the captured mode mode seems to be completely broken for
a device in absolute mode e.g. `xsetwacom --set "$DEV" Mode Absolute`

Here is your example that also prints the cursor coordinates:
[i21744-Constrained-Cursor.zip](https://github.com/godotengine/godot/files/2348050/i21744-Constrained-Cursor.zip)

**Comment by avencherus** [comment]
Cool, good thinking.  I was assuming it would always be tracking, but this does expose some interesting differences.  Apparently on Windows the capture drives it right to center, but on Linux it tracks about still.

It looks like another bug was exposed too.  Using this on Ubuntu, the capture mode seems to not keep the cursor trapped.  Though the confined can, so it is possible.

I suppose the expected behavior I had in mind was that both would keep the cursor trapped in the viewport area, but one was visible the other was hidden.  If you were to switch between them, the position would be tracked.

It's not a critical thing of course, but I imagine it can come up if you had some areas that hid and unhid things on mouse over, but you wanted to keep the cursor trapped as well.

I just now learning of this absolute mode.  I'm gathering that a wacom tablet set across screens is just going where-ever, or was it crashing?

**Comment by capnm** [comment]
>  Using this on Ubuntu, the capture mode seems to not keep the cursor trapped.

That is, I think, ok. The coordinates in this mode are mainly used to rotate the 3D camera.
At least my current camera-script wouldn't work if the cursor was trapped …

**Comment by guilhermefelipecgs** [comment]
About "CAPTURE_MODE", maybe this pr #19191 will fix that. Capture mode is very hack on Linux.

**Comment by avencherus** [comment]
@capnm I see, I haven't done much with 3D.  If this is the case and purpose of it, what's going on in Windows?  Looking again at the output in the project you shared, it seems to suggest that CAPTURE in Win10 is always forcing to center, with some occasional flickering.  Does this mess with your camera rotations?

I was going to say something about clamping the cursor to the window rect on leaving capture mode, but that doesn't make much sense to me after reading your response.

It does give me a clearer picture at least of the intention of it.  I wonder if it would be better overall to split the concepts of show and hiding the cursor out of "mode", and make three modes:  NORMAL / CONFINED / CAPTURED.  Then have method like `set_cursor_hidden()` or something like that to deal separately with the visibility.

That way you could mix these behaviors, and perhaps CAPTURED would need some better explanation.  I suppose I would say:  Captures the cursor inside the viewport, so that when the cursor would move outside of the window's border it will still inside the game.

It isn't an interesting concept, it's like having some invisible world viewed through a portal, and you're pushing the cursor just inside of that portal.  X)

@guilhermefelipecgs Nice share, it does look interesting.  Unfortunately I'm not knowledgeable enough with what's going on there that I could reliably merge and test it with the current master.  :(

**Comment by capnm** [comment]
> I see, I haven't done much with 3D. If this is the case and purpose of it, what's going on in Windows?

Sorry, I forgot it completely, my 3D camera-script uses the mouse-event's **relative** coordinates, see the new example https://github.com/godotengine/godot/issues/21751#issuecomment-418619451

Are the global coordinates in MOUSE_MODE_CAPTURED limited to the window size under Windows? The documentation at least does not say that it should be: http://docs.godotengine.org/en/latest/classes/class_input.html#enums

> Looking again at the output in the project you shared, it seems to suggest that CAPTURE in Win10 is always forcing to center, with some occasional flickering. Does this mess with your camera rotations?

See above, it uses the relative coordinates.

**Comment by avencherus** [comment]
It is hard to say what's going on with Windows here.

> Sorry, I forgot it completely, my 3D camera-script uses the mouse-event's relative coordinates, see the new example #21751 (comment)

Using your new version with relative output, this is what I'm getting.  I can't get to move very far, its as if it had a really strong spring on it.

![bc2](https://user-images.githubusercontent.com/13004169/45080784-563fbe80-b0fe-11e8-8f17-c635e6ce9aad.gif)

Then, I don't know how to reproduce this, but it was shifting from captured to normal mode, the relative positive got stuck?

![bc1](https://user-images.githubusercontent.com/13004169/45080750-44f6b200-b0fe-11e8-9e42-e1f58569c7d0.gif)

**Comment by capnm** [comment]
Ok, I checked it with v306 and v31alpha on Windows. In normal and restricted mode, both coordinates seem to work just like in Linux.

In the captured mode the global coordinates stay in the middle of the window.  So then the global coordinates in this mode are useless. That's what you see, you can only use the relative offset for the movement.

![win-i21744](https://user-images.githubusercontent.com/4047289/45089025-25b25180-b10b-11e8-90ac-92e3c07a877e.png)

This is the version I used in Windows:
[i21744-Constrained-Cursor-v4.zip](https://github.com/godotengine/godot/files/2352422/i21744-Constrained-Cursor-v4.zip)

**Comment by cosmicchipsocket** [comment]
There are two ways of reading relative mouse in an application: reading cursor distance, and reading raw input from the device.

When reading cursor distance, it is possible that the cursor will hit the edge of the screen. In this case, any further movement in the direction of this edge will not be detected, because the pointer simply does not move. This can cause serious problems in first-person games which is why the mouse is centered each frame. When reading raw input from the device, the cursor's position is irrelevant. It's simply getting deltas (the same deltas that may or may not be driving the window system pointer, depending on the system).

My PR switches the behavior on Linux from the former (cursor reading) to the latter (raw input). This is done to deal with serious accuracy issues on newer configurations. While it still centers the mouse every frame, this should theoretically not be necessary. I can modify my PR to remove the centering. However, because this behavior is (currently?) reliant on a compile-time option (very old systems may not have XInput 2), it is not guaranteed that you will get the fixed behavior.

The first release of X.org Server supporting XInput 2.0 is version 1.7, released on October 1st, 2009. Would it be acceptable to make this a minimum requirement for building Godot on X11 (and thus guarantee the behavior)?
