### ISSUE TITLE
Transform at top?

### ISSUE THREAD

**Issue by turtletooth** [godotengine/godot#21760]
Is it possible to have the transform at the top of the inspector?  The transform is so fundamental that having to dig for it is cumbersome.  I would also love it if the title could be on the same line as the values.
e.g.
Rotation [   0] [   0] [   0]

Right now in 3D it takes six lines when it could take 3.

BTW- loving the new changes so far.

**Comment by Ranoller** [comment]
Inspector now respect hierarchy of clases, you have on top your class and down, in order, inheritance... this dessign is good, user friendly? well ... user teaching!, and skips the need of use documentation some times... transform could be fundamental for you, other user need modulate a lot, other need signals a lot, other need material shader a lot... inspector dessign now follows one kind of logic, dessign you proposes follow only personal preferences...i don't want transform on top, i want actual class on top.

The other issue you have i think is in editor settings and allow to put members in one line. Name of the property is in other line because in old inspector this was a trouble... too much espace for the name, little space for the values (not all values are int or float), this was discussed previusly. Believe me, you think now it's a good idea: start a project in godot 2 and you will change your mind about this.

**Comment by turtletooth** [comment]
How is what's there currently better than this?
![transform](https://user-images.githubusercontent.com/4576381/45057968-731fb780-b054-11e8-8407-5d359b78f7f6.PNG)

**Comment by akien-mga** [comment]
Did you mean to close this proposal without further discussion?
