### ISSUE TITLE
Node should have "editable_children" and "discard_instancing" methods

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#21777]
Feature request.

The _Node_ class should have GDScript equivalent methods for these scene dock menu entries:
_"Editable Children"
"Discard Instancing"_

Without these, if you work inside the Godot editor with EditorPlugin, I think there is no way to instance a scene via GDScript and then modify it (e.g. changing some of its child nodes). If you save the scene manually all the changes will be lost, because the node is considered an instance.
If we could do
<code>
node.discard_instancing()
</code>
the nodes will be visible in the scene dock and when the user saves the scene, all the changes will be saved.

**Comment by DualMatrix** [comment]
100% Agree, see #20292

**Comment by avencherus** [comment]
Yeah, I'd vote for this too.  I always love to see more improvements to editor functionality available to addons and tools.  You'll never know when you'll need them.  X)

To address this:  https://github.com/godotengine/godot/pull/20569

They probably wouldn't make sense on the nodes, but perhaps some special methods can be added to EditorPlugin or some other editor only classes that can take the necessary arguments, and keep it off the runtime classes.

**Comment by eon-s** [comment]
I think that these are things that SceneTree or EditorPlugin can do, not Node.

**Comment by DualMatrix** [comment]
There is still some need to give Node access to it though, since the beheviour of nodes with a tool script differs between when editable instance is enabled/disabled. So there needs to be some way to check I feel.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
