### ISSUE TITLE
Regression, unmark One Shot when Emmiting is true, doesn't restore particles emitting 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21794]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10 Intel HD 4600

**Issue description:**
Issue is same as #10181 and fixed in #10297 but now this still not working

So when I unmark One Shot when I have Emitting enabled, I expecting restore particles emitting but this doesn't happen. 

_Bugsquad edit: CPUParticles2D is also affected_

**Steps to reproduce:**

![ezgif-5-8312265410](https://user-images.githubusercontent.com/41945903/45152736-3679ca80-b1d2-11e8-9ff8-2f9ef8188269.gif)

**Comment by clayjohn** [comment]
The underlying behaviour is that ``emitting`` is set to ``false`` after the shot is finished. This makes sense as that is the purpose, of ``one_shot``, ``emitting`` shouldn't stay true while it is no longer emitting. The problem here is that *in the editor* ``emitting`` looks like it is true, when in fact it has been switched to false.

This can be easily fixed in the case of CPUParticles* by calling ``_change_notify()`` when ``emitting`` is set to ``false``. However, for Particles* it is not so simple, because ``emitting`` is changed in the drivers, not in the node itself, so there is no way to detect when it is updated in the node other than calling ``is_emitting()`` every frame. 

I will continue looking and see if an elegant solution can be found.
