### ISSUE TITLE
Opening any project creates empty folder in userdata

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#21799]
**Issue description:**
Opening any project in Godot automatically creates an empty directory for user data. My app_userdata is completely littered with random projects I opened over the months. When I eventually need to use the directory, seeing all these random folders just puts me off.
Isn't it possible to create the directory only if it's actually used?

**Steps to reproduce:**
1. Create a project
2. Open it
3. Yet another empty user directory in your collection

**Comment by akien-mga** [comment]
I don't think empty folders in `app_userdata` are that big an issue, but we can think of possibilities to avoid it. The advantage of the current system is that we know that `user://` always exists (the game creates it when starting if missing).

Without this, it means that any time you want to write something to `user://` (be it logs, config or custom data), we need to first ensure that the directory exists and create it if not. So that's one added check on each write operation instead of a single check when starting the application.

**Comment by KoBeWi** [comment]
Maybe have it as per-project setting whether to create the userdata directory? There's just lots of projects, like demos or tutorials or simple games, that don't use it.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
