### ISSUE TITLE
Line2D cannot draw more than 4096 points

### ISSUE THREAD

**Issue by Bauxitedev** [godotengine/godot#21793]
**Godot version:**
3.1 Alpha

**OS/device including version:**
KDE Neon
GTX 1060 (proprietary drivers)

**Issue description:**
When feeding more than 4096 points to a Line2D, the node refuses to draw anything and simply throws the following error into the console:
```
0:00:17:0057 - Condition ' buffer_ofs > data.polygon_buffer_size ' is true.
----------
Type:Error
Description: 
Time: 0:00:17:0057
C Error: Condition ' buffer_ofs > data.polygon_buffer_size ' is true.
C Source: drivers/gles3/rasterizer_canvas_gles3.cpp:361
C Function: _draw_polygon
```

This is very annoying since I am writing a spectrum analyzer, but due to this bug it cannot draw more than 4096 points so its detail is limited.

Demonstration:
![output](https://user-images.githubusercontent.com/31383123/45144772-5784f000-b1bf-11e8-9480-50e4eb652c59.gif)

**Steps to reproduce:**
Check the reproduction project below and drag the slider towards the right. After reaching 4096, notice how the circle disappears and the error spam starts.

**Minimal reproduction project:**
[line2dbug.zip](https://github.com/godotengine/godot/files/2356180/line2dbug.zip)

**Comment by MidZik** [comment]
Try changing the "rendering/limits/buffers/canvas_polygon_buffer_size_kb" setting in Project Settings.

It defaults to 128 kb, which in your case ends up not being enough.

**Comment by MidZik** [comment]
The only documentation for it is hovering over the setting itself. Its description does say that polygons that are larger than the buffer will not render. The discoverability of this documentation is poor though. Maybe relevant settings should be listed on the appropriate objects in the API documentation, such as Polygon2D.

The error only appears because the alpha is build in debug mode. Release mode builds wouldn't even print an error, the polygon would just silently disappear.

There are efforts to document the project settings more thoroughly, and to increase their discoverability. I guess that this issue should be filed under that topic.

**Comment by Calinou** [comment]
Perhaps those limits should also be increased by default? (This needs to be tested on lower-end devices first.)

**Comment by eddex** [comment]
@MidZik Thank you for this answer! I've been searching for the reason why my Line2D just goes crazy after > 2700 points. Now I know :)
