### ISSUE TITLE
Add option to save error messages to file

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21801]
**Godot version:**
3.1 Alpha

**OS/device including version:**
Windows 10

**Issue description:**
When I try to save error messages to file, I must check console and then copy this messages but will be better if option will be an option to copy this on Debugger

It could export this error messages to other than txt file types. For example odt(open document format), to colour text(errors to red, warnings to yellow etc.)

![Download me, seriously I'm not virus, I'm Dolphin](https://user-images.githubusercontent.com/41945903/45158956-c5441280-b1e5-11e8-919e-9edb8748f448.png)

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
