### ISSUE TITLE
Godot fails to load config and creates a new one every time.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#21823]
The the 3.1 alpha f1e5b7c build, it seems like the editor is no longer able to make good use of the editor settings file.  I've wiped it out, and it doesn't even like the new one it creates when I reopen to the project screen.

![godot_master_2018-09-07_05-52-37](https://user-images.githubusercontent.com/13004169/45195961-b2235800-b262-11e8-9e25-340b6febcce7.png)

**Comment by avencherus** [comment]
Did a build of the commit right before my version, 74359a1d1, and that appears to work fine, unless I did something wrong.  So is it really f1e5b7c causing it?

**Comment by turtlewit** [comment]
The bug is caused by the `EditorSettings` class being registered with the `API_EDITOR` api, but being instanced before the editor is ready. I was able to fix the error by modifying line 3085 of `editor/editor_node.cpp` as such:   
```	
ClassDB::set_current_api(ClassDB::API_CORE);
ClassDB::register_virtual_class<EditorSettings>();
ClassDB::set_current_api(ClassDB::API_EDITOR);
```  
This registers the class as `API_CORE` instead of `API_EDITOR`. However, I don't think this is a valid or permanent solution, unless `EditorSettings` was initially supposed to be registered with the `API_CORE` api.

**Comment by Chaosus** [comment]
I renamed this thread for better search..

**Comment by roa-nyx** [comment]
Apologies I'm still having this same issue. I'm trying `godot --export "blah" ..\bin\` from the command line and it pukes out the following:

![image](https://user-images.githubusercontent.com/8572438/62001464-0293e600-b0bf-11e9-8fe8-fe04c4f86fec.png)

I know `blah` is not a valid export but according to the docs:
> [...] try exporting to a non-recognized platform and the full listing of platforms your configuration supports will be shown [...]

In addition I don't think it matters what export I put this error seems to happen regardless.

**Comment by Mithul** [comment]
Facing the same as @roa-nyx for "Linux/X11" as well

**Comment by cur33** [comment]
@roa-nyx I found a workaround with Godot v3.1.1.stable.official on macOS High Sierra (v10.13.6).

I had the same issue when attempting to export, but only if I used the --path option, or if I omitted the project.godot argument. So I managed to fix it by doing this in my build script:
```bash
cd ./my-project-directory
godot project.godot --export <preset-name> <target-name>
cd -   # return to previous directory
```
Now, when I re-open the Godot project list after running this, it still remembers my projects and I don't have to re-scan them all.

**Comment by aaronfranke** [comment]
@nathanwfranke and I can reproduce this, we're for the most part using [this build script](https://github.com/unknown-horizons/godot-port/blob/develop/build.sh). Replacing `--path .` with `project.godot` fixes the problem. I don't know why I had `--path .` in the first place, but at least now we have narrowed down what the problem is.
