### ISSUE TITLE
Error when used as a screensaver

### ISSUE THREAD

**Issue by Appw0905** [godotengine/godot#21825]
**Godot version:** 3.0

**OS/device including version:** Win 10

**Issue description:**
I exported my game as a windows application, but when using it as a windows screen-saver (renaming the file to .scr) or using it in wallpaper engine, it crashes with the same error. When I run it as normal, just the exe and .pck, it works just fine. I also found the error will happen even with a default project consisting of one node and no scripts.

Here is a photo of the error (no scripts, one scene with one node2d, exported as a windows application with default settings, then the exe renamed to scr)
![photo](https://user-images.githubusercontent.com/18514637/45198692-add44c00-b21c-11e8-8a08-ee0ed2f700e1.PNG)

**Comment by krayon** [comment]
In Windows, a screensaver has various command line parameters to launch different parts (screensaver, configuration tool etc). "/S" is one such parameter.  You'd probably need a way to disable command line parameters in Godot but I don't think that exists. Easiest option may be to write a wrapper frontend.

**Comment by akien-mga** [comment]
Using a Godot application as screensaver by simply renaming the binary extension is not supported, as the error shows Windows has specific requirements on what a screensaver application should support.

Eventually I may clean up the argument parsing and make it so that a stray `/S` won't cause a crash, but in the meantime you need to check Windows documentation on how to create screensavers with thirdparty applications.

> I've found to get it to work with wallpaper engine I need to modify the parent window of the godot game's window to a certain PID. Is this possible?

You can probably instance the Godot window as a child of that PID, but that's not really linked to Godot anymore, more to general Windows API usage.
