### ISSUE TITLE
Default Clear Color's alpha affects the entire in-editor scene view, not just the background

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#21827]
**Godot version:**
v3.1.dev.calinou.5df9109

**OS/device including version:**
Windows 10 Home v1803 (April 2018 update) x64
Nvidia GTX 1060 6GB (Driver 399.07)

**Issue description:**
Setting the alpha value in `rendering/environment/default_clear_color` while in the editor causes everything within the scene to be affected, at least in the editor's view:

<details><summary>Default Clear Color alpha at 0</summary>

![image](https://user-images.githubusercontent.com/1008889/45200361-7b3b4b00-b23e-11e8-8178-a4956db236ae.png)
</details><br/>

I would expect the scene view to look more like this:

<details><summary>Expected Result</summary>

![image](https://user-images.githubusercontent.com/1008889/45200478-0288be80-b23f-11e8-8173-36ca6eaa877f.png)
</details><br/>

Additionally, this does not seem to happen while testing a game, as the exports seems to ignore the alpha value:

<details><summary>In-game result</summary>

![image](https://user-images.githubusercontent.com/1008889/45200583-8f337c80-b23f-11e8-9fe9-32e06bbea4d5.png)
</details><br/>

...except when per-pixel transparency is enabled, in which case it still affects the entire viewport, nodes and all.

**Steps to reproduce:**
1. In the project settings, set `rendering/environment/default_clear_color`'s alpha value to anything.
2. Notice that the rest of the scene disappears along with the background.

**Minimal reproduction project:**
[Default Clear Color Bug.zip](https://github.com/godotengine/godot/files/2359684/Default.Clear.Color.Bug.zip)

**Comment by insomniacUNDERSCORElemon** [comment]
Still happens as of 3.1 alpha 5. However, something to note is that this doesn't occur with the GLES2 renderer (both the invisible nodes in-editor and too-transparent in-game).

However, somewhat related (not sure if it's reported) that DOES happen with GLES2 (unclear with GLES3 because of this issue) is that with per-pixel transparency set to on (particularly with splash as well, otherwise transparency doesn't work), partially-transparent elements render as if nothing is behind them. This happens even if the clear color is fully opaque. At least as of alpha 5.

**Comment by akien-mga** [comment]
Confirmed even after a3a537c2 (which sounded like it might have changed things here).
