### ISSUE TITLE
Polygon2D UV should be defined in 0-1 space instead of texture-size space

### ISSUE THREAD

**Issue by jkb0o** [godotengine/godot#21830]
I am confused little bit. Everytime/everywhere I work with UV it never depends on texture size and vary from 0 to 1. But not with Polygon2D. Why should I define Polygon2D UVs based on texture size? It is not universal. Each time I change polygon texture, I should take into account texture size.

**Comment by mineevgleb** [comment]
I also find this very unintuitive. Besides, now when you attach a shader to the Polygon2D its UV property will change each time you assign a texture with different dimensions.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
