### ISSUE TITLE
Color picker corrupts colors set in RAW mode

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#21860]
**Godot version:**
3.1-alpha - 530704375

**OS/device including version:**
Windows

**Issue description:**
When setting a color in RAW mode (in editor) with value >1, it will be set correctly, but it will be eventually corrupted in subsequent opening of color picker.

**Steps to reproduce:**
1. Create a Node2D
2. Set modulate to raw (5,0,0,1)
3. Blur the color picker
4. Click on the color picker again
5. Blur the color picker without interaction
6. Color has changed

**Expected result:**
Color stays same when I'm inspecting it.

**Comment by CptPotato** [comment]
iirc setting colors in raw mode > 1 also doesn't allow you to correctly change the hue (I'm not sure if this is what you meant).

**Comment by chaosdrop** [comment]
I think this might be related, but can't figure out how. 
If you click the # and turn it into a scroll and enter anything than hit enter you get this error:

ERROR: Invalid Color Code: Color(0,1,0)
   At: core\color.cpp:339

Which is an error message for "String Color::to_html" which I would wager shouldn't be being used in raw mode and is part of the issue.

**Comment by chaosdrop** [comment]
So I think what's happening is the HTML field is taking focus when the picker loads regardless of if raw mode is on and it's hidden. which than when you click on anything it executes this:

void ColorPicker::_html_focus_exit() {
	_html_entered(c_text->get_text());
	_focus_exit();
}

Which is what's causing the issue. 
If I delete the above things work fine, except that you have to than press enter when you change an html value for it save rather than it happening automatically when you click away.

I'm sure someone else who knows more about C++ can figure out a way to fix this with out damaging functionally but this at least figures out what is causing it.

**Comment by chaosdrop** [comment]
I think a good way to fix this would be to change this around line 78:
```
void ColorPicker::set_focus_on_line_edit() {
		c_text->call_deferred("grab_focus");
}
```

To:

```
void ColorPicker::set_focus_on_line_edit() {
	if (raw_mode_enabled == false) {
		c_text->call_deferred("grab_focus");
	}
}
```

**Comment by chaosdrop** [comment]
guess not. That only seems to fix it as long as you don't switch to a different node. for some reason raw mode setting is not being saved after node switch.

**Comment by akien-mga** [comment]
Ping @poke1024, it's a regression from #17383.

**Comment by chaosdrop** [comment]
Since we have entered beta and no one has looked at this issue or commented on my pull request to fix it I figured I'd bump it.
