### ISSUE TITLE
Warnings count towards "Too many errors!" message

### ISSUE THREAD

**Issue by Nitroretro** [godotengine/godot#21896]
**Godot version:**
3.1 alpha 1

**OS/device including version:**
Arch Linux

**Issue description:**
Warnings count towards the "Too many errors! $number errors were dropped." message.
This is confusing as the debugger shows a red circle when this happens, even though there's no error.

**Steps to reproduce:**
Cause enough warnings until the message appears.

**Minimal reproduction project:**
[Demo.zip](https://github.com/godotengine/godot/files/2364264/Demo.zip)

**Comment by Ace-Dragon** [comment]
More info...

When you have a lot of scripts and you play your game, you will get a lot of warnings (in yellow) about variables not being used. The problem with this is that it includes variables that aren't used right away, but are still used when under certain conditions (such as entering a new level or colliding with an object).

I don't know if it's worth having this type of warning system if it is burying real errors that need to be fixed, especially since the parser as of now can't know that a variable will never be used if you do a full play session for testing purposes.

**Comment by vnen** [comment]
@Ace-Dragon unused variables that are used later are only possible if they are class variables, and you can disable specific warnings in the project settings if you feel you don't need that one in particular.

**Comment by vnen** [comment]
This is an issue with the debugger protocol, I feel it could handle more errors at once and the "Too many errors" could be only a warning.

**Comment by golddotasksquestions** [comment]
Someone please fix this, as this actively makes debugging nearly impossible if you don't want to turn off all warnings ([Why have them if I need to turn them off to do my debugging?!?!](https://github.com/godotengine/godot/issues/27576)). Having more than 10 Warnings will sum up remaining warnings and Errors without the possibility to expand them. This is the worst idea possible for a debugging system.
![warnings-errors](https://user-images.githubusercontent.com/47016402/55690296-d88faa00-598f-11e9-86f1-18e53e158378.png)

**Comment by pasimako** [comment]
I've got a similar issue (v3.1.1)

![Godot Engine - Drafting Tales - main tscn_001](https://user-images.githubusercontent.com/10180928/56851151-d0c68400-6903-11e9-82e0-68a7ddc3a667.png)

The debugger shows all these errors, but the game runs just fine. When I disable warnings, all errors are gone along with the warnings.

**Comment by ArdaE** [comment]
I'd like to have an option to disable the dropping of messages altogether (i.e. keep all messages regardless of whether they are warnings or errors), especially in debug mode. I can disable any unwanted warnings anyway, so I would always want to see all of the messages I have enabled.

Obviously this would mean that Godot may not be able to run my app/game at real-time speeds whenever it's flooded with errors and warnings, but that's completely okay during development; I'd rather see every warning and error rather than have something flaky running at full speed. Run my app at 0.1 fps if needed, but don't drop my messages in development mode.

**Comment by ArdaE** [comment]
Looks closely related: #4192

**Comment by ArdaE** [comment]
Set the following project setting to a higher value to increase the limit for Warnings and Errors: `Max Messages Per Frame`. This seems to control the limit for both warnings and errors.

P.S. If you want a higher limit for your print statements too, also increase the limit for `Max Chars Per Second`. I don't know what `Max Messages Per Second` does.
