### ISSUE TITLE
Add color highlighting in Script editor

### ISSUE THREAD

**Issue by Azza292** [godotengine/godot#21926]
![screen shot 2018-09-10 at 12 21 05](https://user-images.githubusercontent.com/29055451/45292127-83bcab80-b4f4-11e8-8c53-9872cc008e45.png)

An option to enable **HEX** color highlighting to the script editor.

This might be a helpful feature in a future release.

**Comment by Azza292** [comment]
I might give this a go for my first contribution if someone could point me in the right direction. 😀

**Comment by girng** [comment]
could be something for https://github.com/willnationsdev/godot-next maybe @willnationsdev 
however, not sure if needed for core

**Comment by akien-mga** [comment]
See #14731.

**Comment by willnationsdev** [comment]
@girng Something like this wouldn't be appropriate for Godot-Next since it involves changes the functionality of an existing editor tool, in this case, the ScriptEditor. It wouldn't require changes to core, but it will require changes to scene or editor. Depends on whether the `TextEdit.add_color_region` can accommodate it. If it does work out of the box, then it is just an editor change. If it doesn't work, then the necessary feature will need to be added to TextEdit it in the scene directory before you then use it to add the feature in the editor directory.

**Comment by girng** [comment]
when i say core, i mean   the godot's master  branch

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
