### ISSUE TITLE
Add settings tab to Project Manager

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21936]
**Godot version:**
3.1 master

**Issue description:**
It is little strange to set renderer(GLES2,3) in editor, because we must restart it. For me better idea will be add a tab in Project Manager in which we could choose one.
It also give extra space for other settings, like checking for updates or opening Godot cache/data without opening editor.

![aaasdasdadasdas](https://user-images.githubusercontent.com/41945903/45301046-57168d00-b510-11e8-8ceb-33ed7eb83e33.png)

related a little with https://github.com/godotengine/godot/issues/21065

**Comment by Bauxitedev** [comment]
I'd also like to add there's currently no way to change any of Godot's settings (except a language picker in the top right) without opening a project first. This would be very handy for options that need a restart before they take effect, such as the aforementioned GLES2/3 switcher, but also the option to change the DPI or theme of the editor.

**Comment by Noshyaar** [comment]
Related: https://github.com/godotengine/godot/issues/2771

**Comment by Zireael07** [comment]
GLES2/3 switch in the project list would be awesome, less people experiencing "omg it crashed with GLES3, how do I even change to GLES2 if I can't get the editor to open?"

**Comment by avencherus** [comment]
Seems like a good place to also add it, but probably doesn't need a Settings tab, and it should be left visible in the editor all the same.  It doesn't seem like it would be too much clutter as an option in the container with the project name.  Similar to how the favorite star button functions.

Maybe someone may find themselves in a situation where they have a dozen projects they want to switch to the other type, and this way they could just go down that list and flip the switch without having to open all of them.  X)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
