### ISSUE TITLE
Add a way to reference an Animation resource by its name

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#21946]
**Godot version:**
`master` / ffe158ae8

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
In Godot, animations (or animation resources, specifically) are identified by their names conceptually, like when you select them from a dropdown box in the animation view. The same goes for such APIs like `AnimationPlayer.Play(String name)`.

However, there's no API to get the name of an animation currently, which makes it almost impossible to write an extendible animation system which involves dynamically adding or removing animations.

For instance, if you want to create an item scene which can define a custom animation to play when equipped, it won't be sufficient for the item to have a reference to an `Animation` type resource because there is no reliable way to know its name and almost all animation related APIs require the name of an animation to manipulate.

The closest thing I could find was `Resource.ResourceName` which returns an empty literal by default, or `Resource.ResourcePath` which needs to be parsed manually to extract the name part and can only be used when the resource is stored as a separate file.

This is not an ideal situation, so there should be a better way to manipulate animations from code to allow writing more complex animation related features (i.e. a modding system which allows custom animations).

**Comment by Zylann** [comment]
As far as I toyed with animations so far, I saw that animation names match their file name always, so I end up using that when they are files. Sometimes I wish there could be a way to play animations by reference (you have a `var` with an animation in it and you just play that) but again the player wants a name^^"

**Comment by mysticfall** [comment]
@Zylann Me too. The old `AnimationTreePlayer` allowed specifying an animation resource instead of a name which was removed when the API was superceded by `AnimationTree`.

I wish this functionality to be restored someday, so I opened another issue for that matter (#19877).

At least, it seems that this issue could be resolved a lot sooner than I initially thought it would. (Thanks @DualMatrix!)

**Comment by reduz** [comment]
Some issues here:

1. There is not a concept of a unique resource names in Godot, and there will never be because it goes against the engine architecture (instancing and all that stuff would break).
2. If you want to add a new animation, adding to AnimationPlayer, using a string identifier and then use that identifier in AnimationTree
3. Adding resources directly to AnimationTree is too difficult, because all the validation is done by AnimationPlayer, as well as editing from UI. Maybe a function to add one via code directly in a node could be added though.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
