### ISSUE TITLE
Redesign save scene/script dialog, dropping save_each_scene_on_quit in editor settings

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#21959]
**Godot version:**

3.0, 3.1

**Issue description:**

Continued from https://github.com/godotengine/godot/pull/21854#issuecomment-419999298 because unrelated to the proposal.

Basically, this setting was introduced to experiment with save dialog styles. But recently @akien-mga and I agree that it should be dropped to not bloat the editor settings (since barely anyone else know about it) and the styles should be merged into one.

Akien's proposal in the original thread moved here for references:

>- Save current scene --> then moves on to next scene
>- Save all scenes
>- Discard current scene --> then moves on to next scene
>- Discard all scenes
>- Cancel
> 
> And same for scripts.
> 
> Of course 5 buttons would be too much, but maybe it could be done with 3 buttons + a checkbox "Apply to all scenes". Or if anyone has a better proposal :D

Here's my thoughts. I like how GIMP does it and I think Godot looks and functions similarily (kind of) so it could be based on.
![image](https://user-images.githubusercontent.com/26753932/45331803-fd0cda80-b596-11e8-93f2-30cf86d2dd01.png)

In the list, clicking unsaved image switches the tab on the main window. Clicking save icon acts similarly to 'save' (saves right away if it was written to disk before, or opens 'save as...' dialog if it hadn't been saved yet) then removes it from the list if saving is successful.

**Comment by akien-mga** [comment]
I like the GIMP dialog, we could likely aim for something similar, so:
- An ItemList for scene/script specific operations (save icon, maybe discard icon?)
- Buttons for global operations (affects all scenes/scripts open): Cancel, Discard Changes, maybe also Save All?

**Comment by Noshyaar** [comment]
I'm not sure about:
1. Discard icon in the list. What if we click it and cancel quitting? What would happen to the "discarded" unsaved changes if we ultimately decide not to quit?
2. Save all. Sure, if the scenes have been saved to the disk, we can overwrite it. But what if the scenes were never saved? If I click "Save All", I don't expect any save dialogs after that as it'd be confusing which file we are saving right now. We can also ignore them but there's a risk of losing data.
The way GIMP does solves both issues as it shows that we'll lose those changes, and we know which file we're saving at the moment. When saving file one by one, it is expected to have Save As dialog appear if it is saved for the first time.

**Comment by akien-mga** [comment]
About 1), I have no strong opinion. It probably works just as well without discard icon for individual items, yes.

For 2), the main difference we have with GIMP is that in GIMP you will likely open at most 3-4 projects at a time, while in Godot you could end up with a dozen of open scenes. That said, it's rare that you have unsaved changes in all open scenes, so maybe forcing individual save would be good enough.

**Comment by Rubonnek** [comment]
Related: #21959

**Comment by voithos** [comment]
Overall, I'd suggest opting for something simple that remains intuitive and optimizes for the most common scenario. I feel like in many cases, if the quit was accidental or the user is unsure exactly what to select, the safer thing to do would be to cancel the quit operation and save things individually as needed.

Besides the single-dialog approach that GIMP takes, a few other tools (like Krita, Aseprite, etc) take a slightly different approach: they open individual dialogs with a "Save" / "Don't save" / "Cancel", one for each file. In some sense, this gives greater control and is a bit simpler, but it also seems a bit less clean. Might be OK if we don't expect many files to be in an unsaved state in the common case.

The GIMP approach seems cleanest, but it also doesn't offer to save for you, which is a bit less convenient.

I guess a third option would be to do some sort of hybrid, where we pick a threshold of unsaved files (1?) to show the "Save"/"Don't save" dialog for, but switch to GIMP's style if the count is greater than the threshold. This may be a bit hard for the user to intuit, though, so picking a single approach might be best.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
