### ISSUE TITLE
Add ability to duplicate project in Project Manager

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#21966]
**Godot version:**
3.1 c320d93

**Issue description:**
Sometimes when I try to do something dangerous with my project(e.g. delete some scenes, rewrite some part of game) I must do a copy of project. It will be easier if that would be available via Project Manager. 

Now I must find folder with project, duplicate it, back to project manager and scan/import it. 

I know that git can do this but I think that duplicating is easier
![asfaasfasfasfasfasfafaf](https://user-images.githubusercontent.com/41945903/45349895-d9f02400-b5b2-11e8-9a26-f6b29fbed2dd.png)

**Comment by akien-mga** [comment]
I've never had the need for such a feature myself, I'm not sure it's worth including in the project manager. Duplicating a project is basically just duplicating a folder from your system's file manager, which is better equipped for such operations.

**Comment by RyanStein** [comment]
Revision control's good at handling this with experimental branches.

**Comment by eon-s** [comment]
If you download templates and do not want to download one again, or you have a framework to be used by a game, duplicating could be handy.

I won't put another button, though, maybe a right click menu option.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
