### ISSUE TITLE
GDScript newlines (and thus comments) increase exported .gdc file size

### ISSUE THREAD

**Issue by ArdaE** [godotengine/godot#21980]
**Godot version:**
3.0.6

**OS/device including version:**
macOS 10.13.6

**Issue description:**
Adding more comments into a .gd file increases the size of the .gdc file in an exported .zip file. The contents of the comments seem to be lost (replaced by interleaving sweeps through low range 32-bit integers), but the size increase affects both .zip and .pck exports.

I have tested this via the "Export PCK/Zip" button. I haven't tested if there's a size increase when the "Export Project" button is used for various different types of targets.

Comments in GDScript files should never affect exported files, let alone increase their size.

**Steps to reproduce:**
1. Export a project that contains some .gd file
2. Add lots of comments into the .gd file
3. Export the project again under a different file name and compare the file sizes
4. [Optional] Dig into the contents of the exported files and compare the two different versions of the .gdc file

**Comment by elasota** [comment]
Doesn't appear to export comments, but it does export newlines, which also take up space in the line map.

Maybe consecutive newlines should be compacted on export, or better yet, when tokenizing.  (Would need to be careful about breakpoints on empty lines though).

**Comment by bojidar-bg** [comment]
Related to #6487, maybe we should extend the check introduced #6564 to also apply when exporting a GDScript file.

**Comment by KoBeWi** [comment]
Seems fixed in 3.2 (or even 3.1, but I didn't check)

**Comment by NuclearPhoenixx** [comment]
Sorry to necro this old issue, but I found that newlines are still exported in Godot today and I was wondering why.

The export strips away all the comment text in .gd files, but leaves the newlines untouched, i.e. in addition to newlines that you yourself added in code, empty lines are left where comments were stripped from.

In .gdshader files, not even comments are stripped, much less any newlines, although it would make much more sense there, since the syntax would allow you to place the entire code on a single line.

**Comment by AThousandShips** [comment]
Please open a new issue, especially if this is about 4.x where this system in question doesn't even exist, but even if this is for 3.x please open a new issue as this has been long closed
