### ISSUE TITLE
file compression removes last digit

### ISSUE THREAD

**Issue by yorgje** [godotengine/godot#21991]
**Godot version:**
Godot 3.0.3

**OS/device including version:**
ubuntu 18.04

**Issue description:**
using open_compressed cuts off the last character of files. 

**Steps to reproduce:**
```
func _ready():
var f = File.new()
f.open_compressed('user://asdf.txt', f.WRITE, f.COMPRESSION_GZIP)
f.store_string('asdf')
f.close()
f.open_compressed('user://asdf.txt', f.READ, f.COMPRESSION_GZIP)
var text = f.get_as_text()
print(text) # prints 'asd' instead of 'asdf'
```

**Minimal reproduction project:**
See the code above

**Comment by PetePete1984** [comment]
Interesting. That might explain why a 2.1 project I have tends to crash weirdly when exported as exe + zip instead of exe + pck (even though `open_compressed` isn't available to GDScript in 2.1, but I suspect the underlying functions to be the same when used internally). "Weirdly" meaning "as if some of the files were incomplete" in this case.
