### ISSUE TITLE
Read setting to emulate Numpad

### ISSUE THREAD

**Issue by HugoSlt** [godotengine/godot#21998]
**Godot version:**
3.1, 890fc10

**Issue description:**
On laptops it is particularly handy to be able to emulate the numpad. This option was proposed in #3612 and the issue was closed.

Yet on the current master, in `editor/editor_settings.cpp` the line `448` is commented : 

`// _initial_set("editors/3d/navigation/emulate_numpad", false); not used at the moment`

Commit f328a35 commented this line. If the implementation of emulate numpad is working I think we should re-enable it for 3.1.

**Steps to reproduce:**
Go to editor settings, look for emulate numpad in editors -> 3d. The option is not here.

**Comment by akien-mga** [comment]
There's no more code for emulating numpad in the current master branch:
```
$ rg "emulate_numpad"
editor/editor_settings.cpp
448:    // _initial_set("editors/3d/navigation/emulate_numpad", false); not used at the moment
```
so #3689 was undone and would have to be reimplemented.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
