### ISSUE TITLE
Add relative path support

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#22019]
**Godot version:3.0 

**OS/device including version:**

**Issue description:**

For example: I have a scene in folder A, I want to reuse this scene in another project, I must put the folder to the exactly same directory.
Another example, If I have two projects, then I want to merge these two games into one and keep the files of each game in their own folder.
Current the path is alway start from res://, if relative path is supported, it will be more easy to reuse scenes with their resources.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
