### ISSUE TITLE
Way to get transformed curve from Path2D

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#22025]
I'm using master branch - godot 3.

It would be nice for Path2D/Path3D to have a method which returns a curve that has been transformed such as 
get_global_curve()

internally this should apply the transform to the curve and return a copy.

Also the curve class should have a method to apply a transform to it so this can be done by the user. At the moment it seems I need to do this manually by iterating over the points and transforming them?

**Comment by eon-s** [comment]
I would like that for all point based things, like curves, polygons, lines.
Slightly related #9218

**Comment by groud** [comment]
Note it's done easily with few lines of code:
```
var global_points = []
for p in range(curve.get_point_count()):
	global_points.append(global_transform.xform(curve.get_point_position(p)))
print(global_points)
```

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
