### ISSUE TITLE
Custom Asset Libraries

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#22046]
**Godot version:**
v3.1.alpha.calinou.9c0cc0d

**Issue description:**
Over the past few days, I've been exploring the idea of making a custom asset library for Godot. Barring the work needed to make such an idea work (such as needing to figure out the data that the official asset library's api sends to the client), one issue I found is that I don't see a way to add custom asset libraries while in-editor.

Godot already provides an official asset library (served from `https://godotengine.org/asset-library/api`), and also allows you to access an asset library running on localhost (served from `http://127.0.0.1/asset-library/api`), but so far I don't know of any way to add your own without editing the engine's source.

It would be nice if we could add our own asset library URLs while in-editor.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
