### ISSUE TITLE
Ability to load scenes/resources without loading scripts linked within

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#22049]
**Godot version:**
v3.1.alpha.calinou.9c0cc0d

**Issue description:**
This idea came about as I was thinking about the sandboxing support suggested in #7753, but I believe it would be a good idea regardless of sandbox support as a whole.

The idea is simple: Load a scene, but don't load the scripts that are attached to nodes and resources. When the game gets the resulting PackedScene, it should already not include the scripts. This would potentially make it easier for developers to allow level creation through the engine editor (rather than through an in-game interface) without concern that the level might have scripts attached that could act maliciously.

**Comment by TGRCdev** [comment]
I think it would be easier to modify `PackedScene.instance()` to have an `include_scripts` argument (defaulting to `true`) that, when `false`, skips attaching scripts to newly instanced sub-scenes.

I haven't looked into `PackedScene`'s source, though, so I don't know how `instance()` is implemented.

**Comment by ElfEars** [comment]
This is interesting. I'd personally also like an option that just removes built in scripts as I'd like to allow users to have a bunch of "pre approved" scripts they can use in scenes.

**Comment by ElfEars** [comment]
Doublepost but I've just realized something. You are unable to pre edit PackedScenes. I think that's more then this issue's scope however so I'll make another. It is relevant however.

**Comment by ElfEars** [comment]
Another variation of this would be to load it in but everything is in pause_mode so you can shove it in the tree and unpause it before any errors occur

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by hsandt** [comment]
Looks like a proposal was opened in the meantime by another author:
https://github.com/godotengine/godot-proposals/issues/4925
