### ISSUE TITLE
PathFollow's rotation_mode should be a bitmask

### ISSUE THREAD

**Issue by LikeLakers2** [godotengine/godot#22061]
**Godot version:**
v3.1.alpha.calinou.9c0cc0d

**Issue description:**
It always bothered me that PathFollow's rotation_mode is a selection between None, Y, XY, or XYZ. It seems like three arbitrary choices to me (though I don't use PathFollow myself, so perhaps there's some reasoning behind it).

So I suggest making it a bitmask, which would allow the developer to arbitrarily choose which of the three axis' they want it to rotate on -- just X, just Z, XZ, whatever.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
