### ISSUE TITLE
GDScript warnings proposals

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#22108]
**Issue description:**

1. It's cool we can disable warnings for files and would be even better if we could disable them for whole directory, especially this one
`res://addons`

2. A warning for unused setter function. If a member has a setter it probably should be used. I want to use setter by default and direct assignment in exceptional circumstances.
Maybe getters should get their warning as well.

3. I'm not sure if i should get "argument is never used" in such code:

```
func _init( a ).( a ):
	pass
```
I'm forwarding argument to base class. This warning appears if object gets instanced.

**Comment by vnen** [comment]
1. Could be done, though I'm not sure what's the best way to do it. Add an option for a list of ignored folders?

2. Don't know what you mean, setters are usually meant for external entities. The class itself does not really need to use the setters. I'd like to see some other opinions on this, and even if added should be disabled by default.

3. That's actually a bug, could be made in a report of its own.

**Comment by hilfazer** [comment]
1 : Any chance it can be done for 3.1? I know we're in feature freeze but without this option i'll most likely won't be using warning system. And i really want to use it.

List of ignored folders sounds fine. There could also be a list of unignored folders. More nested folder would have a priority, for example:
ignore-list = "res://ignore_everything_here"
unignore-list = "res://ignore_everything_here/except/this_directory"

But unignore list can be added later. The sooner i can ignore `res://addons` the happier a man i'll be.

2 : I write setters when i need something done everytime a class member changes. If i'm not mistaken that's one of the reason behind setters. Is it not?
Currently it's easy to have a script that makes a direct assignment to its member by mistake, especially since it's a recommended way of writing code.

Let's see what other users have to say. Maybe i'm just strange.

3 : Ok, i'll file a bug report.

**Comment by clayjohn** [comment]
**Note: I think this is actually implemented in 3.2, but I can't remember when it was added.**

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
