### ISSUE TITLE
AnimationNode.GetParameter() throws assertion failure: Condition ' !state ' is true

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22128]
**Godot version:**
`master` / 9af72f0

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
Attempting to read parameter values via `AnimationNode.GetParameter` seem to result in an assertation failure _'Condition ' !state ' is true'_ in `animation_tree.cpp:55`.

This is especially painful since it means there's no way to manipulate an animation node's parameters having a reference of the node itself (#21399).

**Comment by reduz** [comment]
Manipulating parameters from animation nodes is not possible, because they are resources which are shared between all the animationtree instances. The function you tried to use is for writing custom nodes, but for manipulation from the outside. Parameters only exist in AnimationTree node.

**Comment by mysticfall** [comment]
Ok, that makes sense. But then I really wish #21399 could be reopened, since this means you can't do anything useful with an instance of `AnimationNode` derivative.

Say, when you create a new `AnimationNodeBlend2D` node and add it to a parent deep in the hierarchy, you can't do anything with it but should somehow find out the absolute path of the parent and do some string manipulation to use it, provided you also have a reference to the top level `AnimationTree` and find out the exact name and type of all the needed parameters involved.

I know it's not something too difficult, but it's also something very cumbersome to do, especially when you could simply instantiate a node, attaching it to a parent, then invoke its APIs before the refactor, just like how most people would expect it to work.

**Comment by reduz** [comment]
In GDScript the path autocompletes (or you can drag it to the code) so this is not much of a problem, but i definitely can see a problem in C#. 

Maybe a RMB menu on the property to copy the path would be useful?

**Comment by reduz** [comment]
This way you can paste it in the code. I am also not completely sure how the bindings of Set/Get work in C#, but we could make it so it throws an error/exception in run-time if the parameter used or the type are wrong?

**Comment by mysticfall** [comment]
Yes, I think it woul partly mitigate the problem, but not entirely. In my project, there are groups of animation nodes that work like they were a single animation control. For instance, I have such a group consisting of `Animation`-`TimeScale`-`Blend2` which I use to insert to the animation flow to mix partial animations like breathing.

Before the refactor, manipulating such a group was quite straightforward since I could easily get a reference to the `Blend2` node first and resolve `TimeScale` and `Animation` nodes from there. Then all I had to do was simply change such properties like `BlendAmount` whose name my IDE automatically autocompleted and suggested its type info.

But now, I first have to find out the absolute path of `Blend2` node, parsing it to extract the parent path, then add a predetermined name (since now we can't rely on the connection info to find other nodes) to it to know what absolute paths for `Animation` and `TimeScale`. And I should open up the editor and select the `AnimationTree` so I can see what parameters `Blend2` and `TimeScale` have.

Then I need to build absolute paths for all the parameters I want to control using that info, and invoke them like following after guessing the type information:
```csharp
const string TimeScale = "time_scale";
var prefix = "states/idle/breathing";

tree.Set($"parameters/{prefix}/{TimeScale}/scale", speed);
```
I should repeat this for `Blend2` node as well, but the worst part is, the `Animation` node cannot be controlled in this manner so you actually need a node reference in this case.

To resolve an animation node itself is also really painful. If I'm not mistaken, there's no way to directly obtain a reference to an animation node that resides deep in a hierarchy (i.e. `states/idle/breathing/animation`). So you need to write a recursive method for that purpose, and you need to test what exact type of animation root node each level is and cast to it, since there's no common method for `AnimationRoot` to get its child node. (because methods like `AnimationNodeStateMachine.GetNode` and `AnimationNodeBlendTree.GetNode` are not actually related at all, despite they share a common name).

So, with the refactoring, now we have three different ways to control animation tree - 1) type safe API for a node reference, like `AnimationNodeAnimation.SetAnimation`, 2) using a parameter to query a type safe API, like `AnimationNodeStateMachinePlayback` for state machines, and finally 3) using a string parameters to control animation nodes for all other cases.

I think it can be very confusing and error prone (having to cast to something like `AnimationNodeStateMachinePlayback` always is). Also it can be quite painful to use, especially when you have to deal with complex set up of multi-hierarchy animation nodes.

I wish `AnimationNode` would also follow the example of `Godot.Node`, so that each derivative (i.e. `MeshInstance`) would extend its parent's functionalities in a specific manner, and expose them in a type safe API. I believe that's what most of programmers who are familiar with an OOP language would find to be the most intuitive, and I wish such an intuitiveness and ease of use could be shared between `Node` and `AnimationNode`, rather than making the latter to follow a wholly different convention.

I'm not saying that we should revert to the way it was before the refactoring, or implement any changes immediately. But I really wish we would at least acknowledge it to be a potential problem and keep a relevant issue open, so maybe we could add back type safe API in addition to the current parameter based API later, when we have more leisure or contributors.

Sorry for the long rant. But I had to completely scrape my old animation system to replace it with a half working hack because of the changes. So I just don't want any other people would experience the same trouble.

**Comment by lolligerjoj** [comment]
I have been trying to do a similar thing, getting cyclic animations to blend properly in a BlendTree. At first I compiled the code from #34179, which in principle works, but had some issues for me and wasn't as flexible as I'd like (you can only blend between AnimationNodeAnimation).
So I was extremely excited once I realized that it is supported to write your own AnimationNode. The plan was to write a custom cyclic_blend AnimationNode that uses the lengths of the input animations to figure out what seek time to use for the individual animations such that the blend lines up. Due to the way the system works right now though, I have to write my own AnimationNodeAnimation such that I can actually access what animation it plays, to get the length of the animation. As far as I can tell, the built-in AnimationNodeAnimation can not be accessed in any way by the code, not even with parameters.
Also, if I want to put a different node between the cyclic node and the animation (e.g. timescale), I would need to propagate the length through this node. The way I would like to do this is to extend the nodes such that they calculate the correct length from the input animations.
If I had a way to propagate info through connections, this would all be doable. But since all info has to go through parameters, it will be extremely difficult to implement this. Some Godot node that has a reference to the AnimationTree now has to manage all this functionality by passing the necessary info around to all my custom nodes through parameters. And since the parameter strings do not contain info about the hierarchy within a BlendTree itself, I have to hardcode the strings to the relevant parameters, so the flexibility of using custom AnimationNodes is gone. This really defeats the purpose of having a custom AnimationNode, so I probably will just use regular AnimationNodes and have the cyclic logic in a custom Godot Node, with hard coded references to all the places in my BlendTree where I would like cyclic blending.
