### ISSUE TITLE
Some enhancements to AnimationRootNode API

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22129]
**Godot version:**
`master` / 9af72f0

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:**
Currently, both `AnimationNodeBlendTree` and `AnimationNodeStateMachine` provides an identical method `GetNode(String name)` to retrieve child nodes by their names which seemingly better be pulled up to the common parent type `AnimationRootNode`.

Also, `AnimationTree.TreeRoot` returns `AnimationNode` where `AnimationRootNode` would be more appropriate.

I'm not sure if it's a C# specific problem though, but it'd be nice if it could be changed to make the API look more logically structured.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
