### ISSUE TITLE
EditorPlugin's signal "scene_changed" is not emitted when opening/selecting a [new] empty scene

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22123]
**Godot version:**
Master, on Ubuntu

**Issue description:**
EditorPlugin's signal "scene_changed" is not emitted when opening (**+** button) or selecting (the tab of) an empty scene.
This may be intended, but it's just wrong, because the user won't know that the current scene has been changed. It should return a null root node, but it should still be emitted.

**Minimal reproduction project:**
[scene_changed_issue.zip](https://github.com/godotengine/godot/files/2386067/scene_changed_issue.zip)

**Steps to reproduce:**
Play with the scene tabs and read the log output.
Notice how the plugin cannot tell when a new empty scene is being opened.

**Comment by avencherus** [comment]
Yeah, there probably needs to be an method for detecting an empty scene being opened or navigated to.  Feels like a small hole to me, but not sure what would return from the scene_changed signal, since no scene seems to exist until a root node is added.

Some of the documentation for those plugin signals are a little inaccurate currently.

**Comment by char0xff** [comment]
@avencherus
>not sure what would return from the scene_changed signal, since no scene seems to exist until a root node is added.

As I wrote, it can just return _Null_ or an empty reference, so we can at least know that the scene changed. However, yes, if you want to later do something with that scene, you can't because you wouldn't be able to tell when the new root node has been created. There are currently no ways to handle an empty scene.

**Comment by avencherus** [comment]
@char0xff Sorry, I didn't clarify that very well.  I meant more so on the backend of the code, what Godot has access to return to the signal.  I took a look at it, and as luck would have it, it appears it is storing a null in the scene node when the scene is empty at that point before the signal is sent.


https://github.com/godotengine/godot/blob/c1c1fa78fd8fa10f555316a75d15be6a3fc19e13/editor/editor_plugin.cpp#L476-L479

Currently, it is blocking on returning a null with an IF statement.  I'm thinking the intention was one of convenience, but considering what the signal is supposed to be doing, it seems like a bug.  Since this way you can't always know when the scene is being changed, since this prevents it from firing on empty scene selections.



I put up a PR to change it, we'll see how it goes.  https://github.com/godotengine/godot/pull/22178

X)

**Comment by akien-mga** [comment]
Fixed by #22178.
