### ISSUE TITLE
Add signal for state transition in AnimationNodeStateMachine

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#22137]
**Godot version:**
`master` / 9af72f0

**OS/device including version:**
Manjaro Linux 17.1

**Issue description:** _(This issue is a feature request)_
Sometimes, it is needed to monitor state transitions in a state machine for animations (`AnimationNodeStateMachine`).

As Godot supports auto advancing between states, writing a custom event which fires upon invoking `AnimationStateMachinePlayback.Travel()` isn't really an ideal workaround.

To satisfy such a requirement, it'd be better to add a signal to notify state transitions in `AnimationNodeStateMachine`.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
