### ISSUE TITLE
Suggesrtion: Splash screen minimum display time

### ISSUE THREAD

**Issue by Nobelix** [godotengine/godot#22145]
It would be great to be able to set a minimum display time for the splash screen, now as soon as the game is loaded the splash disappears, although if I want to to show some thing to user, like my studio name or brag about using Godot I may want to display it for some amount of time even if the assets are already loaded.

**Comment by girng** [comment]
you can create your own splash screen scene

**Comment by Nobelix** [comment]
Yo sure but it feels really hacky.

**Comment by girng** [comment]
> if I want to to show some thing to user, like my studio name or brag about using

but if you want to show this information you are going to need to create your own custom splash screen though, right?

**Comment by Nobelix** [comment]
yeah, need to create a splash in some image editor, set it as the splash and set a minimum display time, let's say 5 seconds and then if the game is already loaded just run it as usual

**Comment by Chaosus** [comment]
This is pointless, the splash screen is existing only for making a visual appearance when loading internal engine routines, you cannot control its behavior in code, thus making a splash screen scene is valid continuation for this.

**Comment by akien-mga** [comment]
No it's not pointless, I think it's fine to add a minimum display time for people who want it.

But it's a duplicate of #8867.

**Comment by Neur0s1s** [comment]
@Chaosus 

I agree with @akien-mga .  It wouldn't be too much to ask to implement a splash screen timeout Timer.  I spent 20 minutes trying to figure out how to create a splash screen scene and add a timer and a script because the timer and a script to change_scene()  to the main menu screen.  I don't understand how you can come into this thread with such an attitude and close the thread like that just because YOU deem is "pointless".  Seems like there's a bit of an elitist, antisocial vibe about a lot of these tech forums and not only on this site.  I remember first seeing it on hacker chatrooms on IRC and then on StackOverflow and now here.  This is why people are afraid to ask questions and create threads.  Even ones that are using the correct question formats for whichever site.

**Comment by Chaosus** [comment]
Dude, it was several months ago, I'm changed. And this issue is closed due to be a duplicate - whats the problem ?
