### ISSUE TITLE
Double-cliking on Button brings up the connected _on_pressed event in the script

### ISSUE THREAD

**Issue by char0xff** [godotengine/godot#22164]
Minor enhancement, related to #21223.
Double-clicking a _Button_ control inside the 2D viewport of Godot's editor could create an __on_pressed()_ method or, if already existing, switch to the script editor and show the method. If __on_pressed()_ does not exist, it could check for the other methods (__on_button_down()_ / __on_button_up()_ / __on_toggled()_).
This feature exists in the other GUI widgets editors.

**Comment by girng** [comment]
i use double clicking to edit the name of the node

**Comment by girng** [comment]
edit: removed my previous comment. i get what you mean now, visual studio does this

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
