### ISSUE TITLE
Isometric Mode Grid for Tileset Creation

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#22190]
I would like to propose a isometric grid for tile set creation in a similar manner to that of the TileMap grid properties.

Currently, TileMap has: MODE_ISOMETRIC = 1 — Isometric orientation mode.

I think this would make creating isometric tilemaps much easier.

**Comment by Zireael07** [comment]
I fail to understand what you're missing. As you said, isometric tilemaps can already be done...

**Comment by Mikeysax** [comment]
@Zireael07 Yes, they can be done in the TileMap but not in the TileSet region selection. There is no option or parameters for isometric grids in the region selection when creating a TileSet.

**Comment by akien-mga** [comment]
CC @MarianoGnu

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
