### ISSUE TITLE
Tilemap editor feature requests

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22204]
ok so i checked out the new tileset editor, it's pretty amazing so far.
however, there are some bugs i found that could be very annoying  

**current bugs:**
~~- when copying tiles _from atlas tiles_, it copies the first image, not the corresponding atlas tile:
example in action:~~
![](https://i.gyazo.com/e737ddb5231dad5f24f7847dfc688371.gif)

~~-also, when deleting a tile by right click, it deletes and changes the adjacent ones
https://i.gyazo.com/388117a3d12693b23707eb6723f275cd.gif~~

_Bugsquad edit: moved to #22756_

**possible new features**:
- ability to edit the pivot point of a tile (this is good to offset trees with characters in a ysort map). can do this already the old fashion way of making a tileset, but i think it would be beneficial for the new editor.

- please for the love of godot's gods, let us select multiple tiles in the atlas like in tiled! this would increase workflow tenfold and be very benficial! (hold shift to select multiples, maybe?)

**Comment by ByTheQuietLake** [comment]
I got the bug of the adjacent tiles changing on deleting too when dealing with atlas tiles, I noticed it changes the adjacent tiles to the first tile in the atlas set just like atlas copy bug you talked about.

I also found a bug where after you are done creating a new single tile, clicking the new single tile again to add a new tile temporarily offsets the previous created tile by a bit which gets corrected once you select the tile set again. This happens when clicking new auto tiles and new atlas tiles too.
![test](https://user-images.githubusercontent.com/30891267/45668751-96119780-bb3b-11e8-8c8e-f12a3a8d7fb5.gif)
Also this offset bug appears when you delete a tile and click to add a new tile right after that.
![test2](https://user-images.githubusercontent.com/30891267/45668905-fa345b80-bb3b-11e8-9a77-02fc07d04b81.gif)

**Comment by kubecz3k** [comment]
Thank you for the input @girng!
I think that, this issue is a little to broad and it would be better if you could open new distinct issue for each bug and feature request. This will ease the work for any potential contributor since she/he will be able to refer to this specific issue that she/he wants to solve, close it when her/his fixes are merged or eventually read the discussion on the subject that interest her/him.

**Comment by ByTheQuietLake** [comment]
I will create two new issues as suggested. Thanks!

**Comment by girng** [comment]
#24462 fixes the issue, thanks @guilhermefelipecgs 

i think if i wish to make a proper feature request, i should not include bugs, etc. makes it confusing. i also agree with @kubecz3k

**Comment by Calinou** [comment]
Closing, as this functionality is implemented in the new TileMap and TileSet editors in 4.0. See also https://github.com/godotengine/godot-proposals/issues/1769.
