### ISSUE TITLE
Ribbon Particle Trails

### ISSUE THREAD

**Issue by demipixel** [godotengine/godot#22217]
There's already a number of particle features on the roadmap, one of them being "Real Particle Trails". I wasn't sure if this referred ribbon particle trails or not, so I figured I'd make a post about it.

Here's how they're typically generated:
https://doc.xenko.com/latest/jp/manual/particles/ribbons-and-trails.html

i.e. Connect particles by a bunch of quads, smoothing if possible.

Right now, your option with Godot is to write a node that emits particles, then for each of those particles attaches a Line2D to the end. Which is incredibly inefficient.

While specifically adding this feature is an option, there could be a more generalized approach (so that adding this would mean we could do a bunch of other things as well). An example of generalization to make ribbon trails possible would be to:
- Allow access to last particle (or at least its position) from particle shaders (so you know where to connect)
- Support modification of geometry. Not only would this mean you could create a straight or curved path between particles, you could distort existing particles based off things like velocity or rotation, or modify the shape over the life. This would also mean adding a feature for how textures are displayed (e.g. stretched, repeated)
- Support spawning particles from particles (so you could have a "base" particle, e.g. a firework or spark, and then attach your trail particle system to each one). This could also be beneficial to make more complex particle systems
    - Along with this would come access to the parent particle's location (and possibly things like velocity), so the latest child particle could connect the trail to the base particle (otherwise there would be an awkward gap between the trail and the base particle)

**Comment by EzraT** [comment]
+1 This would be really awesome to have built-in.

**Comment by RevampedSpider** [comment]
I hope this gets added. I'm here anyways because my topic was apparently "a duplicate" which makes no sense at all.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Note: there is a request for particle system ideas in https://github.com/godotengine/godot-proposals/issues/815, instead of opening a new proposal, please add your thoughts there**
