### ISSUE TITLE
AnimationPlayer animation_finished signal not firing when started at end position.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22210]
___

***Note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**v3.1 alpha e10ca7b82**

This is probably minor, but it seems like it was undefined.

If you play a non-looping animation at the end point of the timeline (by seeking) , it will:

1. Signal that it started.
2. The animation will stop.
3. It will report as not playing.
4. _But the `animation_finished` signal does not fire._

Example project (**Updated Project**): 
~~[3.1 No Anim Finish Signal.zip](https://github.com/godotengine/godot/files/2391879/3.1.No.Anim.Finish.Signal.zip)~~
[3.2 No Anim Finish Signal.zip](https://github.com/godotengine/godot/files/4496223/3.2.No.Anim.Finish.Signal.zip)

**Comment by avencherus** [comment]
Still reproducible in 3.2.1.

**Comment by akien-mga** [comment]
Reopening as #38086 was reverted for now.

**Comment by NickersWeb** [comment]
v3.3.2 C# this is still happening.

**Comment by Szesan** [comment]
This makes the play animation backwards function completely useless, because the animation_finished never triggers on them.

**Comment by Jeyanthinath** [comment]
The issue is happening for me with `3.2.3.stable.mono.official` with C#. But I am playing the animation player start to end.

```
E 0:00:03.577   emit_signal: Error calling method from signal 'animation_finished': 'Control(Main.cs)::_start_Next_Scene': Method not found..
  <C++ Source>  core/object.cpp:1260 @ emit_signal()
```

I need to load a new scene after the animation player is finished, as a workaround I am using timer with timeout() signal with the same wait time of animation player. It work perfectly fine while attaching the above function.

**Comment by kappa-05** [comment]
Still reproducible in 3.3.3.

**Comment by Leocesar3D** [comment]
Also happening in my game. I am using Godot 3.3.4 stable.

**Comment by KoBeWi** [comment]
As discussed in the PR, the current behavior makes sense. IMO we should just document this and if someone wants `seek()` to emit the signal, they should open a proposal and provide a valid use-case (I'd like to see one). btw you can use `advance()` if you want to skip animation and emit the signal.

> This makes the play animation backwards function completely useless, because the animation_finished never triggers on them.

This is not true.

**Comment by Szesan** [comment]
> As discussed in the PR, the current behavior makes sense. IMO we should just document this and if someone wants `seek()` to emit the signal, they should open a proposal and provide a valid use-case (I'd like to see one). btw you can use `advance()` if you want to skip animation and emit the signal.
> 
> > This makes the play animation backwards function completely useless, because the animation_finished never triggers on them.
> 
> This is not true.

Why are you lying? 

I'm so fed up with this community, what is the point of reporting when you are so desperate to mark everything as "feature" instead of bug! It's so obviously a bug, I've spent quite a lot of time debugging it, because nobody (and by nobody I mean nobody on this planet except you) expects this behavior, it doesn't make sense, except for you! Multiple people confirmed this to be a bug on this very forum! 

I made a demo project to show you, because you obviously couldn't be bothered to test it for yourself
[AnimationPlayerTest.zip](https://github.com/godotengine/godot/files/8698545/AnimationPlayerTest.zip)


I used animatedsprite in the project, but it's the same issue:

If you use an animation specifically to be played backwards and it exclusively used as such, then the animation finished signal is emitted, however as you can clearly observe in my demo project, if you use the same animation back and forth, then the signal won't get emitted, exactly as it's reported here and confirmed by multiple people. Check it out for yourself!

This is why I said that the animation backwards option makes no sense, because if I want to use an animation solely to play backwards, then I can just initially order the frames in a such a manner, and I don't have to play with "backwards" switch. This switch only makes sense, if you want to use it on an animation after you played it forward, and this is exactly the case when it fails to emit the signal. You have to have such a twisted way of thinking if you seriously consider this as an acceptable behavior.

**Comment by Szesan** [comment]
> @Szesan I have to remind you of the Godot Code of Conduct: https://godotengine.org/code-of-conduct
> 
> Please stay constructive and polite. You can disagree with KoBeWi's assessment, but this can be discussed without superlatives, blanket statements or personal attacks.

He accused me of lying by saying that my claim is not true, while it IS true. And it's a constructive, I took my time to setup a proper demo project to demonstrate the issue.

**Comment by akien-mga** [comment]
Saying "This is not true." doesn't imply that you're *lying*, but that you might be mistaken. The person saying that might also be mistaken. Both are fine and there can be a civil discussion ending up in agree about what is actually true.

I just did a quick test and for **AnimationPlayer** the `animation_finished` signal does seem to be emitted properly when playing backwards. The use case you describe (play forwards then backwards) seems to work fine in my demo:

[AnimationPlayerTest2.zip](https://github.com/godotengine/godot/files/8698710/AnimationPlayerTest2.zip)

Maybe there's a bug with **AnimatedSprite**, I'll check.

**Comment by Szesan** [comment]
> Saying "This is not true." doesn't imply that you're _lying_, but that you might be mistaken. The person saying that might also be mistaken. Both are fine and there can be a civil discussion ending up in agreeing about what is actually true. You providing a test project is indeed a positive addition to the discussion so that we can see exactly what you see and why you describe it as a bug.
> 
> I just did a quick test and for **AnimationPlayer** the `animation_finished` signal does seem to be emitted properly when playing backwards. The use case you describe (play forwards then backwards) seems to work fine in my demo:
> 
> [AnimationPlayerTest2.zip](https://github.com/godotengine/godot/files/8698710/AnimationPlayerTest2.zip)
> 
> Maybe there's a bug with **AnimatedSprite**, I'll check.

Thanks, It's easy to check, just start the demo I made. The use case I described is the the use case where it makes sense to use the backwards switch, as I have already explained...

**Comment by akien-mga** [comment]
> Maybe there's a bug with **AnimatedSprite**, I'll check.

I confirm that there seems to be a bug with **AnimatedSprite**... which is not what this issue is about. So @KoBeWi and you are talking about different things.

I would advise to open a dedicated bug report for AnimatedSprite as it's not related to this issue in AnimationPlayer. Whether the AnimationPlayer behavior is good or not is a different discussion but at least for _your use case_, it works flawlessly.

In AnimatedSprite, there seems to be a problem related to the Loop mode. I did get the `animation_finished` signal emitted when Loop is on in my test project but then the behavior is not as I expect it (as the loop and my manual looping conflict with each other).

[AnimatedSpriteTest.zip](https://github.com/godotengine/godot/files/8698793/AnimatedSpriteTest.zip)

**Comment by akien-mga** [comment]
Fair enough, I opened an issue myself: #61078

**Comment by Szesan** [comment]
> Fair enough, I opened an issue myself: #61078

Great, thank you!
