### ISSUE TITLE
Filtering scripts by Scene

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22229]
**Godot version:**
3.1 alpha
All

**Issue description:**
Many times there are so many scripts open in the editor from all different scenes.  Would be helpful to have a checkbox to filter on/off the scripts list by Scene. Always include globals from project autoload.

Also show ALL scripts related to that scene. You can then do a lazy open, when user clicks on script.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
