### ISSUE TITLE
ScrollBar with fixed-sized grabber suggestion

### ISSUE THREAD

**Issue by ykoc** [godotengine/godot#22253]
Godot version: 3.1 master

In a various old-styled interfaces ScrollBars uses grabber with size not dependent on size of full size of container (Hero and Castle lists in HoMM IV are examples of this type of interface). Those ScrollBars can be made using a precious pixel-to-pixel texture of grabbers. But in Godot such a theme is not possible since size of the grabber for ScrollBar is modified by ScrollContainer and there is no way to turn this resizing out.

**Comment by Zach777** [comment]
I think this request would be nice to have. Being able to have scrollbar grabber be indepent from the container size if set to be like that.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by MatthewHinds** [comment]
Would love to see this added. Spent two days before finding out here it doesn't seem supported.

**Comment by AThousandShips** [comment]
If you want this feature please follow the instructions above and open a proposal for it
