### ISSUE TITLE
The name of the exported android build is not localizable

### ISSUE THREAD

**Issue by alemedero** [godotengine/godot#22262]
**Godot version:** 3.0 stable macOS version

**OS/device including version:** Android

**Issue description:** In the export template there is no way of localizing the game name. I mean the name that is shown under de App launcher icon. In the "Name" field under export template window i tried using my localization key (i.e: "KEY_TITLE"), also tried using $genname (since this work in the field Unique Name that is above the field Name) but it doesn't work either. Everything in this field is treated as a String 
<img width="522" alt="screen shot 2018-09-18 at 6 41 56 pm" src="https://user-images.githubusercontent.com/12191251/45778188-4eb80380-bc2e-11e8-9e6e-a6ff5eb0ffff.png">

**Steps to reproduce:** 
Export any project for android and try to localize the name under the app launcher icon.

**Minimal reproduction project:**

**Comment by volzhs** [comment]
it's possible by following old(2.x) way.

![screenshot_20180920_132522](https://user-images.githubusercontent.com/8281454/45795844-bfb3f580-bcd8-11e8-97f3-2f7882cb1207.png)
And click [Add] then you got new field as below

![screenshot_20180920_132551](https://user-images.githubusercontent.com/8281454/45795846-c17db900-bcd8-11e8-9d79-6d7129a417cd.png)
then you can specify localized name of app.

There is a document for it.
http://docs.godotengine.org/en/3.0/tutorials/i18n/internationalizing_games.html#translating-the-project-name

but yeah it's old and maybe there could be better way.

**Comment by alemedero** [comment]
Hey this actually the solution, although it would be better if the Name field in the export template accepted a localization Key so you don't have to create N properties in the project settings.
Also the docs for 3.0 should be updated with an image like the one @volzhs  posted because the one that is in the docs now is a 2.x image and is a little misleading since if you try to create a key like "name_en" it shows "Name En"

Anyway, my bad, this should be closed. Thanks @volzhs !

**Comment by akien-mga** [comment]
Reopening as I agree with @volzhs that this workflow should be made clearer.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
