### ISSUE TITLE
Allow specifying mandatory points for certain routes

### ISSUE THREAD

**Issue by ShadowKyogre** [godotengine/godot#2228]
For Navigation2D and Navigation, there should be a feature that allows the caller of `get_simple_path` to specify possible mandatory points to follow the player. For instance,
![navigation_mandatory_points](https://cloud.githubusercontent.com/assets/673620/8490776/8b544dce-20e3-11e5-8f42-f31d19f05330.png)

The pink dot is the player. The red dot is an enemy. The current navigation classes would probably give path 0 as the best option for the enemy, which might not be possible if the enemy cannot jump that high. So instead, depending on the jumping capabilities of an enemy, a list of possible points*, representing the best places the enemy can follow to reach their target can be fed into `get_simple_path`.

*in this case, the best possible jump position to get to the second platform and some point on the second platform

**Comment by mamarilmanson** [comment]
I think you should indicate where a character can jump...

**Comment by Ace-Dragon** [comment]
And how would this be implemented? There are a ton of moves that a 2D game designer could give to a non-playable object and developing hardcoded move types could limit users.

One might think Godot could have some sort of move/behavior editor for this sort of thing, but this type of pathfinding would need a bit of planning as to how the design would work.

**Comment by ShadowKyogre** [comment]
@Ace-Dragon: I'm not exactly sure myself ><;. It maybe reliant on the generic A* method that @romulox-x said was getting extracted so it can be used on a more standalone basis. 

In the particular use case that I outlined above, I was thinking that there could be a "scan radius" for objects that're higher than the current enemy's height to determine which platforms it can jump to. And every time there's a new platform corresponding to a coordinate, it would then "scan" again for possible connections for paths it could take.

This would be probably dependent on the person who's making the game to code it properly before using the generic A* algorithm. I don't think this would need hardcoded move types, but I'll wait for the other developers to chime in (as I'm also trying to sort out how this works in head).

**Comment by akien-mga** [comment]
I also don't really see how this could be implemented in a generic way that would make sense for all Godot games using Navigation*. The use case you described is very specific and likely needs quite a few lines of code to be implemented, and I think it can only be done on a per-project basis.

You could check for walkable objects in range, and then tell your enemy to get_simple_path() to an object within jump range. If no object is within range, then it needs some more precise AI to decide where to move to so that it can reach platforms that would bring it to the player. In any case, way more complex than just giving mandatory points for pathfinding.

Indepedently of what you are trying to achieve, a ```get_path_via(target_pos, via_pos = [])``` method could maybe be worked on.

**Comment by reduz** [comment]
this is too game specific, if you need more pathfinder tools to do this please feel free to request them
