### ISSUE TITLE
Shader do not work properly for manually drawn shapes.

### ISSUE THREAD

**Issue by ptrnycz** [godotengine/godot#22306]
I have not found something similar in issues found

**Godot version:**
Gdot Engine v3.0.6.stable.official.8314054

**OS/device including version:**
Windows 7, OpenGL ES 3.0 Renderer GeForce GT 750M/PCIe/SSE2

**Issue description:**
Just created two sprites, simple images added to them (icon.png). During "on_draw" event red circle is drawn. Additionally, very simple shader is added, just copying color is added to both of them (no visual effect expected). On first sprite, where no circle is drawn visual effect is as expected, on thecond one, where circle is drawn, circle always is filled out in white color, circle color selected in drawing code does not influence on that. If no shader is added, the circle is drawn correctly (in red).

**Steps to reproduce:**
Please look at demo project.
[ShaderBug.zip](https://github.com/godotengine/godot/files/2404296/ShaderBug.zip)

**Minimal reproduction project:**
Minimal issue reproduction project enclosed.

**Comment by clayjohn** [comment]
This is not a bug. When you assign a shader to a CanvasItem, it applies to the entire node including objects that are drawn in the ``_draw`` function. Circles that are drawn with ``draw_circle`` are not assigned a texture, nor are they assigned UV coordinates because it is intended that they will be drawn with a single color. As a result, the circle appears white even though it it was set to draw red. In the future, if you want to assign a texture to an object drawn in ``_draw`` use ``draw_colored_polygon``.
