### ISSUE TITLE
Merge 3D Tiles to mesh

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#22315]
Have an option to turn 3D tiles grid to a mesh, there is multiple advantages :
- more performance when the level is big 
- navmesh can be baked on the mesh
- Global illumination will work on mesh
- mesh can be exported
- mesh can be modified with CGG

**Comment by FlamyAT** [comment]
Currently it's possible to get the [GridMap](http://docs.godotengine.org/en/latest/classes/class_gridmap.html#class-gridmap-get-bake-meshes) as (a) baked mesh(es) via `GridMap.get_bake_meshes()`. With the `ResourceSaver` this mesh can be saved.
Thus this is nothing new!

**Comment by DevMagicLord** [comment]
It needs a button in the editor for usability, on the grid properties : 
"Grid to Mesh"

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
