### ISSUE TITLE
Tile set collision with grid snapping enabled does not show collision drawing lines

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#22326]
**Godot version:**

on current master branch  ef7b384

**OS/device including version:**

Win 7, Intel HD 4000

**Issue description:**

Collision does not work when snapping is enabled for tileset when editing single tiles. Trying to draw a collision shape on tile shows no response, with at times a single point showing at corners or at most a triangle collision shape with three points. But works when snapping is not selected.

**Steps to reproduce:**
1. Create a tileset resource and add a image to it
2. With snapping enabled create a new single tile
3. Open collision tabs after creating a tile and make sure that snapping is enabled
4. Try to draw a collision shape on that tile
**Minimal reproduction project:**

**Comment by thomasRandall-git** [comment]
Instead of applying the CollisionShape2D onto the tile from your main world, recreate the tileset, then add 2 things inside each tile:
-Sprite
--StaticBody2D
---CollisionShape2D

Then repeat for each tile. Also, make sure that you applied a shape to the CollisionBox within the Inspector menu. Adjust the shape(s) then convert to a Tileset. I'd suggest saving as a scene as well so you can go back to add or edit the tiles.

**Comment by ByTheQuietLake** [comment]
Are you talking about the old way of making tiles? I was actually talking about the new tile set editor which has a collision option within it, which seems not to work? I am surprised no one else seems to have this issue as of yet.

**Comment by thomasRandall-git** [comment]
It is most likely a bug then.

**Comment by ByTheQuietLake** [comment]
I would like to add that, I was able to draw a collision shape with grid snapping on that that takes up the whole tiles if I click and the 4 points fairly close to the edges, so the collision shape drawing with snapping seems to be functional but there is no feedback/indicators(blue lines and red points) when drawing the shape with grid snapping so it looks like that is actually is the problem. Here is a gif showing the lack of indicators and how I drew the collision shape. 
![nocollisionindicator](https://user-images.githubusercontent.com/30891267/46493212-58945600-c82d-11e8-9ef9-ac1ea0c4d2d6.gif)

**Comment by ByTheQuietLake** [comment]
It might just be that the grid lines are drawn on top of the thin blue lines and they just aren't seen because of it? Regardless of the cause, it just doesn't feel right drawing collision without any indicators.

**Comment by ByTheQuietLake** [comment]
I would like to add that this is true for Occlusion and navigation as well.

**Comment by akien-mga** [comment]
The tiles workflow has changed a lot since 2018, both in the 3.x branch and with the brand new tiles editor in the upcoming 4.0.

I haven't checked this issue specifically but it might no longer be relevant in today's supported releases.

If you can still reproduce this issue, I would suggest opening a new issue with a minimal reproduction project that matches the current stable release.
