### ISSUE TITLE
Outdated terms in source code

### ISSUE THREAD

**Issue by SwapnillTek** [godotengine/godot#22356]
When reviewing the project's code I saw the phrase Master/Slave... This kind of terminology can lead to awkwardness and overall is dated terms. Don't you think we can do a little better? What I propose is something like Python just did, which was AMAZING of them. I feel like by keeping this we are excluding and not including everyone. Waiting to hear your thoughts...

Examples of the term slave used:
https://github.com/godotengine/godot/blob/82ff99c18005f67c6d7692abf7594e31fc067f3c/doc/classes/MultiplayerAPI.xml#L152

https://github.com/godotengine/godot/blob/82ff99c18005f67c6d7692abf7594e31fc067f3c/doc/classes/MultiplayerAPI.xml#L153

https://github.com/godotengine/godot/blob/82ff99c18005f67c6d7692abf7594e31fc067f3c/modules/mono/mono_gd/gd_mono_utils.cpp#L130

**Comment by NaymanHohnheimer** [comment]
Definitely agree :)
Outdates stuff like this belongs in the 40's
I also found many terms like "blacklist", "whitelist", "disabled", and more!
If the Godot devs are OK with it, I can join them as chief inclusivity officer, no charge :)

**Comment by PetePete1984** [comment]
Troll accounts upvoting themselves, they're also doing this on the Nim repo over here https://github.com/nim-lang/Nim/issues/9038

**Comment by NaymanHohnheimer** [comment]
> > The master/slave issue was already handled -- [#7986 (comment)](https://github.com/godotengine/godot/issues/7986#issuecomment-421185969) and #22087.
> 
> I like that you're removing it but I still found numerous examples of slave still in the code

Hypocrisy is a big part of alt-right speak



> Trolls or not, I agree that these problematic terms need to be removed, once and for all. We are not in the 1950s anymore, and inclusivity is key in opensource projects.

Thank you so much!

**Comment by neikeq** [comment]
You're a little late. The pandering to the speech police was a week ago. The good news is you won.

**Comment by NaymanHohnheimer** [comment]
Now I realize that a lot of people are trying to be 'indifferent' but the truth is you can't be. You can either be with us, and accept that diversity is very much a good thing, and that removing toxic people (like many of the above protesting) is even better, allowing multicultural experiences to seep into the heart of the project, OR, you can become a little backwards swamp full of white people typing away at their computers, making 'code' without soul. You can't have soul without people of colour, because you don't experience difficulties in your life. So i ask of you to be good people, and accept that diversity is just as important, and even more important, than code. Thank you :smiley: 



> You're a little late. The pandering to the speech police was a week ago. The good news is you won.

We always win. Because we are the good guys. And we haven't won yet. We need to get the Contributor covenant added so that ethnic and sexual minorities finally feel welcome in the group, as opposed to just whites. This project simply won't survive without diversity, just like a nation can't. Thank you :)

**Comment by reduz** [comment]
@NaymanHohnheimer , @nicolascolla, @SwapnillTek : Geeze guys, all your answers in the post linked by @LikeLakers2, including why you can still find mentions to the terms. Do your homework before doing this stupidity.
