### ISSUE TITLE
Replace node does not work on multiple nodes at a time

### ISSUE THREAD

**Issue by agameraaron** [godotengine/godot#2242]
Using Linux Mint, 64-bit.
The "Replace a Node by Another Node Type" feature does not work when you have multiple items selected from the node browser. It would have come in use as I was converting 8 text entries into buttons when I realized buttons be more appropriate for their use. It was no big bother to go one by one though, only a matter of seconds!

**Comment by akien-mga** [comment]
I'm not sure it would be really useful, especially since people might then try to change nodes of different types to a same new node type, so each node would have to be handled differently. I'd actually prefer the node replacement mechanism to be kept for single nodes but improved so that e.g. signals are not lost of common to both the old and new types.

**Comment by bojidar-bg** [comment]
Given that we have `MutiNodeEdit` now, I guess this should be supported.

**Comment by akien-mga** [comment]
Works fine now in the master branch (c48027af).
