### ISSUE TITLE
Adding Support for Numerous languages

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#22428]
I hope to translate my games into more obscure languages, but Godot doesn't support any of ones I'd like to translate to. I tried to import a Neapolitan translation for example, but it wouldn't let me because the locale isn't supported.

Languages I would like to see supported, among others:
Neapolitan (nap)
Corsican (co)
Sicilian (scn)
Jeju (jje)
Ainu (ain)
Okinawan/Ryukyuan (ryu)
Jamaican Patois (jam)
Singlish

I see no reason for the languages to not be supported, as all of the characters used in them are used in languages Godot already supports. In fact, I think it might be beneficial because it gives speaks of these languages another tool to promote these languages.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
