### ISSUE TITLE
Autoloads load even when disabled

### ISSUE THREAD

**Issue by werdnahull** [godotengine/godot#22441]
**Godot version:**
3.0.6-stable

**OS/device including version:**
Windows 10 x64 

**Issue description:**
Scripts selected to autoload still load, even when unchecked in the dialog box.
![image](https://user-images.githubusercontent.com/10228963/46057163-09ea0c00-c109-11e8-92a6-92bd6904f08f.png)

**Steps to reproduce:**

1. Create simple script that prints something
![image](https://user-images.githubusercontent.com/10228963/46057239-78c76500-c109-11e8-87cd-ccc78d3e5631.png)
2. Add script to autoload in **Project Settings -> AutoLoad tab**
3. Uncheck box next to **Enable**
4. Run game, see script output
![image](https://user-images.githubusercontent.com/10228963/46057200-4453a900-c109-11e8-9105-d317808338d6.png)

**Minimal reproduction project:**
[AutoLoadTest.zip](https://github.com/godotengine/godot/files/2418093/AutoLoadTest.zip)

**Comment by akien-mga** [comment]
That's not a bug, what is enabled is the "Singleton" mode, which means that your autoload can be access with the global variable `autoload1` instead of only via its absolute path `get_node("/root/autoload1")`.

There's no feature to disable autoloads for now, apart from removing them from autoloads in the first place.

**Comment by werdnahull** [comment]
@akien-mga  Ah I see, thank you for that clarification! My apologies for creating a false issue.
