### ISSUE TITLE
Support GPU Physics?

### ISSUE THREAD

**Issue by TritiatedWater** [godotengine/godot#22448]
Godot is slow when there are a lot of moving objects with collision in the scene. It would be nice for godot to support GPU physics (via OpenCL).

And also :

> With Bullet as physics backend, new possibilities emerge, such as soft body, cloth support and GPU (OpenCL) physics. This will be added after 3.0 is out, likely for 3.1.

Two down, one to go.

**Comment by nathanwfranke** [comment]
I definitely support this, but it may be important to make the backends as interchangable as possible. Ideally, (other than performance) a physics based game would run the same on either backend.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
