### ISSUE TITLE
ConfigFile.get_value() should accept default_value as 3rd parameter

### ISSUE THREAD

**Issue by alxcyl** [godotengine/godot#2244]
ConfigFile.get_value() should have a 3rd parameter which will be returned if the section & key does not exist.

Suggested edit:

    void get_value( String section, String key, var default_value=null ) const

For example:

    var cf = ConfigFile.new()
    cf.load("user://configs.cfg")
    var user_id = cf.get_value("user", "id", -1)
    # if user/id does not exist, user_id = -1
    # else user_id = whatever value is saved

**Comment by akien-mga** [comment]
That would be cool indeed. In my game I defined a helper function exactly to do that, since ConfigFile.get_value() was not sufficient: https://github.com/akien-mga/dynadungeons/blob/dfc4ea8/scripts/global.gd#L132-L151

```

func set_from_cfg(config, section, key):
	"""Retrieve the parameter from the config file, or restore it
	if it is missing from the config file.
	"""
	if (config.has_section_key(section, key)):
		set(key, config.get_value(section, key))
	else:
		print("Warning: '" + key + "' missing from '" + section + "' section in the config file, default value has been added.")
		save_to_config(section, key, get(key))

func save_to_config(section, key, value):
	"""Helper function to redefine a parameter in the settings file"""
	var config = ConfigFile.new()
	var err = config.load(settings_filename)
	if (err):
		# TODO: Better error handling
		print("Error code when loading config file: ", err)
	else:
		config.set_value(section, key, value)
		config.save(settings_filename)
```

And in my case it only works since I use the same variable names for member variables of my global singleton and for my config file, which is why I can use ```get(key)``` to retrieve a default value in ```set_from_config```.
