### ISSUE TITLE
Particles2D with non-local coordinates on ParallaxLayer have wrong transformation

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#22453]
**Godot version:**
3.1.alpha 5a03d50

**OS/device including version:**
Windows 10

**Issue description:**
`Particles2D` with non-local coordinates that are placed on `ParallaxLayer` have wrong transformation when layer moves:

* Scale of the `Camera2D` is not applied (`ParalaxBackground` is not ignoring camera zoom)
* `ParallaxLayer` offset does not affect particles.

With Local Coords enabled particles behave as expected. Using local coords is not viable workaround when `Particles2D` is expected to be moving on the `ParallaxLayer` and leaving trails of particles.

**Expected behavior:**
![expected](https://thumbs.gfycat.com/CompleteExhaustedKillifish-size_restricted.gif)

**Actual behavior:**
![actual](https://thumbs.gfycat.com/SleepyWebbedAntlion-size_restricted.gif)

**Steps to reproduce:**
Run MRP. Switch local coords to see expected behaviour.

**Minimal reproduction project:**
[Github repo](https://github.com/lekoder/godot-issue-paralax-particles)

Might be related to #16800

**Comment by groud** [comment]
The global coordinates are calculated according to CanvasLayers, not ParallaxLayers.
I believe it's an expected behavior.

**Comment by lekoder** [comment]
Syntax note: to avoid confusion I'm using `code highlight` (`ParallaxBackground`) to name specific classes in Godot, and normal text (parallax background) for generic concept.


@groud while this certainly current implementation and use of `Particles2D` on `ParallaxLayer` was not anticipated, I would argue that behaviour might not be intentional.

* It makes some kinds of particle systems not usable in parallax backgrounds. Typical use case of the particle system is that they are an offspring of a sprite. With one toggle of a boolean suddenly such scene (sprite+particles) becomes unusable on parallax backgrounds. IMO re-usability of nodes in the tree are a big selling point of Godot. Example usage would be puffs of smoke from a steam locomotive moving in parallax background - I would expect that smoke moves in relation to background layer, not the camera.
* Option in named "Local Coords"; while "Global" is viable alternative to local, so are "Parent Coords", "Layer Coords", and "Canvas Coords".
* At very least, particles should respect the scale of `Camera2D` zoom, since they are on `ParallaxBackground` which is **not** ignoring the scale and **is** an `CanvasLayer`.

The core reason seems to be implementation of parallax itself: the `ParallaxLayer` is not actually a canvas layer, but it emulates it. This might also cause other issues (ie. `RigidBody2D` placed on `ParallaxLayer` will probably not behave as expected).

If it is indeed an intended behavior, this is a documentation issue: I would expect inviability of `Particles2D` on `ParallaxLayer` be mentioned in the docs.

If this is not intended, I think possible implementations of fix are:
1. Allowing `ParticleSystem2D` to pick a reference object for coordinates, defaulting to self for local coords.
1. Merging `ParallaxLayer` and `ParallaxBackground` into `ParallaxBackgroundLayer` entity, that's both a `CanvasLayer` and has proper offset and scale of `ParallaxLayer`.

I can actually implement 2 myself on a `CanvasLayer` using game code, but I would expect this to be a part of the engine.

**Comment by avencherus** [comment]
@lekoder I had some bad experiences with ParallaxBackground and CanvasLayers several months ago working in Godot 2.1.  In my case I quickly abandoned them and wrote my own parallaxing nodes on top of Node2Ds, so I never quite got to the bottom of the issues.  It was clearly some very unexpected mixtures of transforms.  Some things taking on transformations, other parts whistling past the camera as if there was no scaling of the positions.  I believe it was also related to the project's viewport mode too, which I couldn't reproduce in the master branch.

I'm sure this is not all that helpful on my part to add, because I didn't have the time to isolate it back then and moved forward.  I also don't have any idea what the state of it is in 3.0 or 3.1, as I'm going to just stay with my own solution, since it is working just fine.

But that said, I will throw in with you that it probably needs some investigation, as it looks like quirks still exist.  

This is definitely promises to be a very harsh surprise for the beginner and intermediate level users of Godot.  Especially if they try to approach a more robust project and then rely on these nodes.  If they don't know how to roll their own parallaxing, they may be left high and dry or resort to a lot of duplicating of work, hacks, etc.

**Comment by akien-mga** [comment]
The MRP still reproduces the "Actual behavior" (unexpected) in 3.5-beta1, and a quick and dirty conversion to 4.0 seems to also show a similar behavior still.

**Comment by QbieShay** [comment]
There's not much that can be done with this issue, since parallax layers move the canvas it's quite expected that world coord particles behave like that (however, should be documented with a warning that global-space particles with parallax layers are not supposed to work).

We can add a configuration warning to the particles if they are a child of parallax layer and their `local_coord` property is set to false.

Bumping to 4.1 since this is a documentation issue and not a bug.
