### ISSUE TITLE
Add ability to clear (unused) cache and userdata via Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#22467]
**Godot version:**
3.1 8fc92ae

**OS/device including version:**
Windows 10

**Issue description:**
Sometimes when I create project to check something fast, I delete it and later create a new with the same name(e.g. "New Game Project") and then errors are occured e.g.
![adas](https://user-images.githubusercontent.com/41945903/46134068-4e2cf780-c242-11e8-9cad-6cceaf15fc38.png)

So I think that should be special buttons (for me the best option will be button in project manager settings https://github.com/godotengine/godot/issues/21936) which can clear all Godot data or just this data which projects are not in Project List.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
