### ISSUE TITLE
Allow relative paths in gndlib files

### ISSUE THREAD

**Issue by javidcf** [godotengine/godot#22491]
**Godot version:**
3.0.6.stable.official.8314054

**OS/device including version:**
Ubuntu 16.04.5 LTS x86_64

**Issue description:**
I am trying to make a plugin that uses NativeScript. The idea is to have a custom type (added on plugin initialization with `add_custom_type`) that is implemented in C++. This much I got working, with the only caveat that the `.gdnlib` file needs to have full paths for the libraries. I mean, you can use a path without `res://`, but it will be treated as an absolute path. I can use `res://addons/my_plugin/bin/x11/my_lib.so`, etc. and _hope_ that the plugin does not have its name changed, but it is not too solid. And in any case, I think it would be useful to use relative paths in general, e.g. if you have some NativeScript with its scene in a directory and then decide to rearrange things, it would be good not having to change the paths.

Looking through the code, it seems it should be a matter of concatenating the base path of the `.gdnlib` file when needed in [`modules/gdnative/gdnative.cpp`](https://github.com/godotengine/godot/blob/3.0.6-stable/modules/gdnative/gdnative.cpp#L143-L148), similar to [how it is done for `preload`](https://github.com/godotengine/godot/blob/3.0.6-stable/modules/gdscript/gdscript_parser.cpp#L448-L449). I am submitting an issue and not a PR because I am not sure if there is any reason _not_ to allow relative paths, because I am not sure whether this is extrapolatable to other platforms and because the file path is not available at that point and I am not sure what would be the best way to implement it cleanly.

**Steps to reproduce:**
1. Make a NativeScript module.
2. Use relative paths in the `.gdnlib` file.
3. Godot cannot find the library.

**Minimal reproduction project:**
Any of the projects in [GodotNativeTools/GDNative-demos](https://github.com/GodotNativeTools/GDNative-demos) should serve, simply changing the paths in `.gdnlib` files.

**Comment by akien-mga** [comment]
CC @karroffel

**Comment by karroffel** [comment]
So technically it does allow relative paths - the question here is "relative to what?"

When Godot loads a library from the gdnlib file, it's the *executable* who basically just forwards the path to the OS. So paths can be relative to the Godot binary.

**Comment by javidcf** [comment]
@karroffel Yes, you are right, I should have been more specific. What I meant is paths relative to the `.gdnlib` file. In the case of plugins, the absolute path may not be completely guaranteed.

I suppose an alternative approach would be creating the [`GDNativeLibrary`](http://docs.godotengine.org/en/latest/classes/class_gdnativelibrary.html) and [`NativeScript`](http://docs.godotengine.org/en/latest/classes/class_nativescript.html) objects dynamically on plugin load, using the [script path](https://godotengine.org/qa/5189/how-to-get-the-relative-path-to-current-folder-script) to define the library paths.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
