### ISSUE TITLE
Perform Skeleton mechanics from gdscript

### ISSUE THREAD

**Issue by r3d9u11** [godotengine/godot#22501]
I found several questions for this theme on the forum and question/answer page, but without answers. Question was asked in irc and chat, also without answers.

**Godot version:**
3.0.6

**OS/device including version:**
Linux Mint 18.3 x64

**Issue description:**
I have a simply IK Chain, in UI Designer I can change position of limbs bone and all bones of skeleton also will change own positions/rotation. But I can't get access to bones from gdscript and perform skeleton mechanics, it would be cool to get it possible _(feature request if it is not possible currently in godot)_.

**Steps to reproduce:**
run project, touch and move the virtual joystick

**Minimal reproduction project:**

[GDScriptIKChain.zip](https://github.com/godotengine/godot/files/2427119/GDScriptIKChain.zip)
![skeleton](https://user-images.githubusercontent.com/15020827/46193297-577f9800-c306-11e8-9223-a5a4b26bea32.png)
![1](https://user-images.githubusercontent.com/15020827/46193252-299a5380-c306-11e8-859a-533995229525.png)

Thanks.

**Comment by r3d9u11** [comment]
Here is some experiments with Godot 3.1
Designer (rest position)
![1](https://user-images.githubusercontent.com/15020827/46211201-a267d280-c33b-11e8-835b-7856c908e1e2.png)
Designer (skeleton deformation)
![2](https://user-images.githubusercontent.com/15020827/46211202-a267d280-c33b-11e8-8426-97574147e1d5.png)
App RunTime (skeleton deformation via gdscript)
![3](https://user-images.githubusercontent.com/15020827/46211203-a267d280-c33b-11e8-8f8b-083e230f43c1.png)
[2D_SkeletalDeformation.zip](https://github.com/godotengine/godot/files/2428339/2D_SkeletalDeformation.zip)

**Comment by groud** [comment]
IK chains at runtime are not implemented yet, so that's an expected behavior. It should be added to Skeleton2D in a future release.

**Comment by r3d9u11** [comment]
@groud thanks for your answer and attention to the topic!

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
