### ISSUE TITLE
Condition ' !is_inside_tree() ' is true. returned: get_transform() C Source: scene/2d/canvas_item.cpp:369

### ISSUE THREAD

**Issue by Ron5s** [godotengine/godot#22596]
**Godot version:**
3.0.6/3.1 alpha 1

**OS/device including version:**
Windows 7/10

**Issue description:**
0:00:00:0953 - Condition ' !is_inside_tree() ' is true. returned: get_transform()

**Steps to reproduce:**
I am instancing a Node2d via gdscript then using the following code:

var node = player.instance()
node.set_global_rotation_degrees(node.get_global_rotation_degrees()

Which give the following error multiple times:

3.0.6
0:00:00:0953 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
----------
Type:Error
Description: 
Time: 0:00:00:0953
C Error: Condition ' !is_inside_tree() ' is true. returned: get_transform()
C Source: scene/2d/canvas_item.cpp:369
C Function: get_global_transform

3.1 alpha 1
0:00:01:0426 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
----------
Type:Error
Description: 
Time: 0:00:01:0426
C Error: Condition ' !is_inside_tree() ' is true. returned: get_transform()
C Source: scene/2d/canvas_item.cpp:362
C Function: get_global_transform

**Comment by DualMatrix** [comment]
I think this means you can only set the global rotation when its inside the tree. Try adding it as a child first.

**Comment by Ron5s** [comment]
Oh thank you.  I thought it was a bug.  You were right

**Comment by smysamet** [comment]
But what about if we want to set position first then add the child?

**Comment by Zireael07** [comment]
@smysamet: You can't, you have to first add the child.

**Comment by huttyblue** [comment]
Working on a project thats using godot instead of bullet physics. 
Setting position after adding to the tree causes a huge lag-spike, probably as it checks all the gridmap tiles between 0,0,0 and the chosen destination.

Setting the position before adding it to the tree doesn't have this problem, but spams this error, while also presumably working fine. 

So there are situations where you would want to set the position before add_child(
Why is an error even thrown if it works regardless?

**Comment by maciejbudzyn** [comment]
> Setting the position before adding it to the tree doesn't have this problem, but spams this error, while also presumably working fine.

No it doesn't work fine, at least there are some side-effects. 

I mean, in Debug, everything was ok, but  after I exported the game to release (tried on android and windows), sprites and collisions in a single tile got different positions. In practise, collisions got some offset and were totally in different place than corresponding sprite.

So if possible, despite looks a bit unnatural, first add the node to the tree, then set its global position.

**Comment by josephmulindwa** [comment]
[Add a comment](https://stackoverflow.com/questions/76922314/i-keep-getting-the-error-condition-is-inside-tree-is-true-returning-trans/78126699#)
0

I had the same problem and here is how I solved it.

Start by making a backup of the script that brings the error OR a copy of the entire project's script.
Convert every print() statement in the code to a push_error(). This will push all printed out statements to the error output window allowing you to see which stage this error occurs at. For this step, you might want to reduce the print() statements so that the output isn't much.
Run the project and see what point the !is_inside_tree occurs. At this point you could already have an idea of how to solve the issue. If no, move on to step 4.
Put a breakpoint on the latest 1 or 2 lines before the !is_inside_tree error as seen in the error output window.
Run the project and run and once the breakpoint is hit, use the step into feature repeatedly until the !is_inside_tree error is printed.
That'll surely help.
