### ISSUE TITLE
Importing Mesh Cache (MDD, PC2, Alembic) 

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot#22592]
Implement the Iporter for _MDD_ / _PC2_ / _Alembic_ (etc.) files with animated _geometry_ _cache_.
It is ideal for transferring animations of complex characters / simulations in 3D scenes. 

For now:
For complex rigs, users are forced to bake animations into bones. Which is very tiring for the creation of extras. Simulations needs to be hand-animated or recreated as particles.

**Comment by fire** [comment]
It should be possible to make an importer for alembic, I don't know if it's possible to do it in gdnative, but it's definitely possible to use a module. 

The second problem of engine bloat shouldn't be as a big of a problem.

One approach is to go the alembic to gltf2 approach. https://github.com/syoyo/tinygltfloader/tree/master/examples/alembic_to_gltf

**Comment by lvottero** [comment]
Alembic can be a powerful way to add content to a game, especially for artists coming from a vfx background. Unity work with Oats studios for example.  Would love to see this format supported

**Comment by fire** [comment]
I put in a bare bones implementation of alembic importing for asset import, but due to lack of interest it only does vertex importing with the same vertex count. 

It doesn't do mesh frames with different vertexes. 

Also it doesn't do uv mapping so textures cannot be loaded currently. 

Lastly, no optimizations have been done yet.

https://sketchfab.com/3d-models/pirate-flag-animate-loop-5baa9f06289c4f3590a17cab212254fb

https://drive.google.com/a/chibifire.com/uc?id=1Ks4w5qVY7QN9gnWBvuh0PzTo54g1krfJ

**Comment by fire** [comment]
![2019-03-30_12-20-48](https://user-images.githubusercontent.com/32321/55280699-5693e700-52e6-11e9-9962-cfe9c8f71c9e.png)

After 4 hours of work, the UV mapping works for Alembic!

**Comment by aidanoflann** [comment]
@fire this is actually something I could dedicate some time to this month. Very interested in getting Alembic importing smoothly to Godot for a VR-scuplted and animated asset pipeline. Would you happen to have any notes or snippets from your work so far; somewhere I could get started? Thanks!

**Comment by fire** [comment]
This is my pull request: https://github.com/godotengine/godot/pull/23837 

https://github.com/godotengine/godot/blob/d9215c1e70f78aeac06ecd94dc012cefbe9be81f/thirdparty/assimp/code/ABCImporter.cpp

**Comment by fire** [comment]
@aidanoflann ping

**Comment by Hopefullyidontgetbanned** [comment]
integration with godot's particle system would be nice

**Comment by Calinou** [comment]
@Hopefullyidontgetbanned Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
