### ISSUE TITLE
Create New Script button is not there in a newly created spatial from the 3D Scene button.

### ISSUE THREAD

**Issue by DualMatrix** [godotengine/godot#22677]
**Godot version:**
3.1 0f4c30f

**Issue description:**
Create New Script button is not there in a newly created spatial from the 3D Scene button.

**Steps to reproduce:**

Create a new scene.
Press the 3D Scene button.
See the Create Script button missing.

**Comment by aaronfranke** [comment]
Confirmed. The problem seems to specifically be that the root Spatial node is not selected properly when using the "3D Scene" button. The transform gizmo does not show up, and you can't right-click it either. If you click elsewhere and reselect the Spatial node in the hierarchy, it works. If you create from a custom node and select Spatial, that doesn't experience the problem.

**Comment by swarnimarun** [comment]
@aaronfranke yep you were correct, seems like we were never adding the new_node to the selection list. Weird why the other nodes were working. Fixed it for now will see why others were working later.
