### ISSUE TITLE
[Mono] Give C# users a way to expose files from within a .pck to be loaded using nuget packages

### ISSUE THREAD

**Issue by exts** [godotengine/godot#22735]
**Godot version:**
All

**OS/device including version:**
Windows/Ubuntu 18

**Issue description:**
Currently if you use any third party nuget package that requires a direct path to a local file it's only possible within the editor. The moment you export your project and try to use a File.GetAbsolutePath (workaround) it'll return an empty string because `res://` is now located inside the pck instead of locally. This becomes a problem when you use nuget packages where you can't load string/byte data and pass it to those packages because they only support direct path loading.

**Suggestion**
Expose a way to temporarily access a file from within the `.pck` file locally (on every os) that can be directly accessed using a direct path (which would also have a class method) using a random filename and then can be manually deleted once you're finished using it or automatically cleaned up with the godot application exits.

**Example where this would be useful**
C#'s Sqlite package only allows direct file access and `:memory:` that can't be modified. Sure you could use gdnative, but not everyone could finesse there way with GDNative to solve an issue like this, plus it opens up a lot more 3rd party nuget packages for C# to be used without needing to have C++ knowledge for gdnative.

**Comment by mysticfall** [comment]
One option is to write a wrapper for `System.IO.Stream` using Godot's `File` API like this:
 * https://github.com/mysticfall/AlleyCat/blob/master/Source/AlleyCat/IO/FileStream.cs

You can do the same for `Microsoft.Extensions.FileProviders` to get directory listings under `res://`, so you can write such a code using that API:

```csharp
var provider = new FileProvider();
var directory = provider.GetDirectoryContents("user://");

for (var file in directory) {
    GD.Print(file);
}

var file = new FileInfo("res://README.md");

using (var reader = new StreamReader(file.CreateReadStream()))
{
    string line;

    while ((line = reader.ReadLine()) != null)
    {
        GD.Print(line);
    }
}
```

**Comment by exts** [comment]
@mysticfall opening the file isn't really an issue, it's accessing a direct path to a file within a pck for nuget packages that need a direct path. packages like newtonsoft.json gets away by loading from string, but now I believe this would allow us to load directly from source.

I wrote a workaround with my idea in C# that I think should be exposed to the main api for instance: https://gist.github.com/exts/1ddf817bb927b4adc0d4ac7b63dc8029 (ignore my messy code)

example usage
```csharp
var pfeFile = new PckFileExposer("res://Data/loot-table.db");

GD.Print(pfeFile.GetDataPath()); // do w/e with the file using 

pfeFile.DeleteTempDataFile(); // this should delete itself, I need to mess around with dispose, currently i just have a destructor
```

again was a wip i created in about 30 minutes, so its messy.

**Comment by mysticfall** [comment]
@exts Yeah, I think I understand the problem so I added a few more lines to my previous comment to avoid confusion.

I think your idea could be a good workaround for such a case where no other choice is available. I'm not strongly opposed to the idea of including such a method to the standard API, but I still believe encouraging third party maintainers to improve their projects to use a more generalized API for accessing files could be a better choice when it's possible.

**Comment by exts** [comment]
If this turns out to be a bad idea, that's cool. Going to post this as a reference for later

https://gist.github.com/exts/641cad4b22d9c24c809ec0852d415fec

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
