### ISSUE TITLE
Disable shadow casting from material

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#22805]
Godot 3.1

I wanted to quickly test how an outline material looked like on my Minecraft-like terrain, so I went for the same approach as material testers demo: I added a next pass material with `grow`, `unshaded`, inverted culling and black albedo.

That worked, however I found a big problem with it:
When shadows are enabled, this slows down rendering tremendously. I made sure there was no shadow projected on the outline, however I did not find any option to prevent the outline from casting a shadow, and I believe this is what makes shadows very slow. Godot is trying to render the terrain 4 times (for all splits), then 4 times again for the outline next passes, which is just a waste of time (and there can be hundreds of these chunks).

Here with exaggerated outlines:
![image](https://user-images.githubusercontent.com/1311555/46573206-a625d580-c989-11e8-8735-fb5f3ae50afc.png)

I found an option to prevent a mesh instance from casting shadows, however can there be a way to set this option on a material? Because my only option right now would be to duplicate the instance and have another material on it like in the old times, so the next pass feature is quite pointless for making outlines because of that waste. And it would still be a waste because those extra instances take up memory and time to setup and cull.

I might take another approach if I want outlines, but I wanted to raise this significant caveat.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
