### ISSUE TITLE
Mutiple selection and edit of points for CSGPolygon, path and related nodes

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#22803]
**Godot version:**

3.1 alpha

**OS/device including version:**

**Issue description:**

I am working on the CSG tutorial and I realize some problem when playing with the tools. I draw a polygon far away from the origin of the CSGPolygon nodes. My initial thought is to move the whole polygon towards the origin, unfortunately, I cannot do so. The only thing I can do is to redraw the CSG polygon near the origin, it is not a complicated shape to redraw but it is not a good experience.

It would be better if I can select all the points or some points and move it around. Being able to scale the selection(only changing the location not actual scale) is also nice feature. I think this feature is beneficial to Path, Path2D, Polygon2D and other nodes that can edit points.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by NewNodeGames** [comment]
What I also miss of CSGPolygon is a snap to grid point edition.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
