### ISSUE TITLE
Add the ability to add points on existing segment of polygon in Polygon 2D Editor

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#22826]
**Godot version:**

3.1 alpha

**OS/device including version:**

**Issue description:**

You cannot add a point on existing segment of a polygon in the editor, you can only draw a new polygon for to add  a new point which is a terrible design... Please add the ability to add points on existing segment of polygon in Polygon 2D Editor.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by avencherus** [comment]
> which is a terrible design... 

It probably wasn't by design, so much as overlooked in its first iterations.  X)

I agree though that it should include or match the functionality provided by the polygon canvas toolbar.  It gets clunky when there is a need for switching back and forth.

I know @groud has this editor in his sights.

You might also be interested in one of my issues regarding the tools being out of sync:  https://github.com/godotengine/godot/issues/22280

**Comment by ZX-WT** [comment]
yeah, I know that it is rough/no design rather than bad design, it is so bare bone. The editor needs some love X)

**Comment by clayjohn** [comment]
Is this issue still present in 3.1?

**Comment by groud** [comment]
I think it has been solved

**Comment by akien-mga** [comment]
Assuming fixed in 3.1, please comment if you can still reproduce the original issue.
