### ISSUE TITLE
Is it time for Godot 3.1 alpha 2?

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#22835]
I'm just wondering, it's been about a month since alpha 1 was released and there has since been a mass slaughter of bugs and issues big and small alike. I think it would be good to have so as to see less reports based on outdated code, and also to deliver a better and more usable snapshot to encourage an even larger number of users to make the jump from 3.0.6 stable.

I'm not sure what the schedule is, but more frequent snapshots, in my opinion, would only be good for Godot's momentum as a project.

**Comment by reduz** [comment]
Probably after GodotCon, since the next week we will be meeting in Poland
(and will be vacationing the next one). The GLES2 renderer is a lot more
stable, so I would appreciate testing it.

**Comment by akien-mga** [comment]
Please don't open such issues, we know what we're doing... (And it's not the first time you do: #17928).

We're well aware of the state of our master branch, and of when we want to make releases. @reduz and I already work 10+ hours/day 7 days a week on the project, so we don't need users to tell us how to run the project.

**Comment by Jeremiah86** [comment]
> so we don't need users to tell us how to run the project.

This is pretty disheartening to hear, then why even have this repo open to the public then? Contributors have every right to ask questions about a project. After looking at Ace-Dragon's profile, he's been a user here since 2014 or so.  

@reduz's reply seemed professional and cordial. To me, it seems like you took offensive over something that was not offensive at all.
