### ISSUE TITLE
Shader globals 

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#22852]
**Godot version:**
All

1) Would be nice if the shader language allowed globals between functions without using the keyword uniform which not only can not be assigned to from code, but also is exposed in Materials Shader.

2) Would be nice to allow Shader Global Constants to be accessible inside functions other than the main function.

Granted, given that this is GPU execution code, I don't know what the difficulties are, or maybe there is a workaround that I could not see in the docs.

E.g.

Similar to this example (view it here) https://www.shadertoy.com/view/ll3BR7

```
float x=0.5;

float get_time(){
    x += 0.1;
    return iTime;
}

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{

    // Normalized pixel coordinates (from 0 to 1)
    vec2 uv = fragCoord/iResolution.xy;

    // Time varying pixel color
    vec3 col = x + 0.5*cos(get_time()+uv.xyx+vec3(0,2,4));

    // Output to screen
    fragColor = vec4(col,1.0);
}
```

**Comment by QbieShay** [comment]
Afaik writing to variables that are accessible from every CPU core is extremely slow because only one core can write/read, meaning that you lost most of the paralellism performance (because the threads need to run one after the other).

**Comment by wyattbiker** [comment]
Just curious, would passing the variables to functions be more efficient? 

Also on point #2, why not allow built-ins to be accessible from other functions. For example TIME or UV are not accessible from other functions other than the main one.

**Comment by SIsilicon** [comment]
If it helps, I could give a suggestion as to how this can be implemented. I'm working on something that's also being affected by this limitation.

So the idea is this. Along with the actual varyings that transfer data between the vertex and fragment shader, the shader language can also add those variables directly into the fragment shader.
Obviously each pair can't use the same names. They could be prepended with a couple characters to keep them unique.

So the actual varying could be prepended with `v_` for example, and the variable inside the fragment shader can have `f_`. Also in the fragment shader, the `f_` variable will be initialized with the varying, and the fragment and light shaders can get from _and_ set that variable; unlike the read-only varying.

**Comment by clayjohn** [comment]
@SIsilicon What you are proposing is just a roundabout way of exposing varyings. It makes much more sense to expose them directly (as we do) and allow users to set them as much as they want. 

Also Global constants have been implemented already (see [Docs](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#constants), and [PR](https://github.com/godotengine/godot/pull/29316)), so this issue can be closed. 

Global variables that can be written to will not be added. This is because Godot exposes all shader stages in one script. However, each shader stage is executed separately in the hardware. If you defined a global value and altered it in the vertex shader, it would not change for the fragment shader (and vice-versa), thius behaviour would be very confusing for users and has no clear benefit, so it will not be implemented. Anything that can be done with a global variable can be done by properly passing values to your functions.

**Comment by SIsilicon** [comment]
> What you are proposing is just a roundabout way of exposing varyings. It makes much more sense to expose them directly (as we do) and allow users to set them as much as they want.

It's more of an extension to the current varying implementation. What I'm proposing still allows users to change the value.



> Also Global constants have been implemented already (see [Docs](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#constants), and [PR](https://github.com/godotengine/godot/pull/29316)), so this issue can be closed.

I thought the issue was about shader globals, and not shader global _constants_. We still don't have a feature to have variables shared across the _entire_ shader.



> Global variables that can be written to will not be added. This is because Godot exposes all shader stages in one script. However, each shader stage is executed separately in the hardware. If you defined a global value and altered it in the vertex shader, it would not change for the fragment shader (and vice-versa),

Isn't that the point of the varyings though? To have a variable that can be used by both vertex and fragment, therefore global?

But I think we're misunderstanding each other. Varyings can't be changed the fragment shader. That's ok since the last stage of the shader. Oh wait. _It isn't_. There is currently no way for the fragment shader to pass data to the light shader. The reason why I made the proposal above is to have the fragment _and_ light shader connected to each other. Just as how the vertex and fragment shader are connected to each other. If you want it to be less confusing though, you could probably just implement a keyword that functions similar to `varying`.
```
lighting vec3 example;
```

**Comment by d-eisenga** [comment]
Has there been any update on the matter of passing values from the fragment function to the lighting function somehow? The capabilities of custom lighting functions seem extremely limited at the moment because it doesn't have access to all the values that the built-in lighting function does, e.g. `binormal` and `tangent`.

**Comment by SIsilicon** [comment]
This feature proposal is relevant.
https://github.com/godotengine/godot-proposals/issues/1057
