### ISSUE TITLE
sort_custom generates parse error with typed array variables

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#22888]
**Godot version:**
3.1.alpha.custom_build.745ae39

**OS/device including version:**
Fedora 28

**Issue description:**
When you use the method custom sort with a typed array variable it generates a parse error:

> Assigned type (Object) doesn't match the function argument's type (Object)

Removing the type declaration causes a correct parsing of the gds file.

**Steps to reproduce:**
use sort_custom on any typed array.

**Minimal reproduction project:**
[parser-sort.zip](https://github.com/godotengine/godot/files/2461284/parser-sort.zip)

**Comment by J08nY** [comment]
Minimal example is:
```
class Test:
	static func compare(a, b):
		return a < b

func _ready():
	l : Array = [1,2,3]
	l.sort_custom(Test, "compare")
```
The problem is that adding the `: Array` type hint enforces the type of the first argument to `Object` while in the parser `Test` has type `GDScript`. See:

https://github.com/godotengine/godot/blob/4c1a5d9cfe2da761bfe17d52126deabc1f1c1bd3/modules/gdscript/gdscript_parser.cpp#L6827

The simplest thing to fix this should be to remove the `Object` type hint of the `sort_custom` method, which is actually wrong, as it takes classes and objects alike.

**Comment by volzhs** [comment]
still valid with 942855a9e
