### ISSUE TITLE
CSGTextPolygon to extrude text dynamically

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#22945]
**Godot version:**
3.1 alpha

**Feature Request**
It would be great if dynamic 3d text could be generated. Either by a new CSGPolygon subclass or an external class that generates a 2d polygon for a text in a certain font that can be passed to CSGPolygon.

Depending on complexity, I will give it a try to implement it. Can someone point me to how I can get polygons from the font infrastructure used in Godot? Is it even available?

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
