### ISSUE TITLE
Many internal void functions unintuitively contain the word "get"

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#22956]
Many of Godot's void functions start with "get", and this seems unintuitive to me. I would expect a function starting with the word "get" to return a value. If the function's purpose is to obtain data from somewhere but not return something, perhaps it would be better to use the word "load" instead of "get".

For a full list (there are quite a few), here's a grep one-liner to search for them (excludes pointer-containing functions and code in thirdparty, since there's lots of Bullet code that does this too):

    grep -Ri "void get_" | grep -v thirdparty | grep -v "*" | grep -i "void get_"

Just to pick one out at random as an example, `void EditorData::get_plugin_window_layout` only operates with the passed-in variable and its own internal field `editor_plugins`. If I understand how this function works correctly, it would make more sense to call this function `load_plugin_window_layout` instead. CC @reduz

**Comment by malbach** [comment]
Hi,
IMHO when you know the "trick" it's not really a problem. For your example and from my POV, "load_plugin_window_layout" would mean that I want to load a layout for a window, when I actually want to get the layout infos of the window (don't know if I'm clear here...)
If it should be modified, I'd like to suggest "fetch_" instead of "load_", as it as the same meaning as "get_" (we still want datas from the function) but will allow to have different meanings for the function's type.

**Comment by starry-abyss** [comment]
Using an argument (pointer/reference) for result instead of function return value is normal. I don't think there should be a different name for this approach.

**Comment by aaronfranke** [comment]
@starry-abyss Which I why I excluded lines containing `*`, or do you mean something else?

**Comment by starry-abyss** [comment]
In the example `void EditorData::get_plugin_window_layout` you mentioned, the argument is a smart pointer (Ref<>). Apparently, the function writes the result to pointed-by memory, so it doesn't also need a second (traditional) return value.
