### ISSUE TITLE
UI: Move Checkboxes in Inspector > Spatial Material 

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot#22971]
Move cheboxes from material sections to sections lables:

Old:

![old](https://user-images.githubusercontent.com/7798042/46894917-d3d5b780-ce7e-11e8-8e86-bb3e411a1183.jpg)

New Prosposal:

![new](https://user-images.githubusercontent.com/7798042/46909453-44daa500-cf3b-11e8-9bc3-f9f525d14faa.jpg)

Profit:
+ Inspector length less
+ User always sees what sections is enabled

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
