### ISSUE TITLE
Some 2d editor tools have no tooltip

### ISSUE THREAD

**Issue by swenner** [godotengine/godot#23008]
**Godot version:**
3.1 alpha (master) fe0db6c4797b8094c64e4ad017e29be866288628

**OS/device including version:**
Debian GNU/Linux 9

**Issue description:**
The two tools marked in the image have no tooltips.

![missing-tooltips](https://user-images.githubusercontent.com/290658/46917121-75662180-cfc3-11e8-9532-2794f43e8e87.png)

**Comment by voithos** [comment]
I'm not sure that the "Layout" button needs a tooltip, as it already has a label, and this matches the pattern for similar buttons, like "View", "Sprite", etc - although I'm not sure why only some buttons have icons and other don't. Probably worth thinking about what criteria we should use for representing a button with just an icon, vs text, vs both icon and text.

The skeleton menu button should have a tooltip, though, since it is just an icon right now.
