### ISSUE TITLE
Add a convenient builtin for forwarding a specific signal

### ISSUE THREAD

**Issue by jonbonazza** [godotengine/godot#23028]
I'd like to propose an enhancement to the scripting API, specifically regarding signals.

When creating Scenes with the intent of reuse, it's often desirable to have all interactions with the Scene go through the root. For example, say you have the following scene graph:

```
|_ Weapon
   |_ AnimationPlayer
   |_ Sprite
   |_ ...
```

This Weapon scene will likely be reused all over the place. For example, a Player scene might contain an instance of the Weapon scene as child:
```
Player (KinematicBody2D)
|_ AnimationPlayer
|_ Sprite
|_ Weapon
|_ ...
```
Now when scripting out the logic for the player, I may want to know when  the weapon is finished attacking (i.e. the animation from Weapon.AnimationPlayer is finished). Of course, the Weapon's animation controller will emit an `on_finished` signal, but as user of the Weapon scene, I shouldn't have to know about what children the Weapon scene has. Instead, it would be ideal if I could connect the signal (possible under a different, more explicit name) directly from the Weapon scene (i.e. `$Weapon.connect("on_finish", self, "_on_finish")` or even better `$Weapon.connect("attack_complete", self, "_attack_complete")`).

Now this can be done today (and in fact, I do this a lot already) by simply having `Weapon` connect to the `AnimationPlayer`s `on_finish` signal and then emitting its own, `attack_finished` signal that is essentially just a pass through, but doing this is a bit more cumbersome that I'd like. For instance in GDScript, you'd have something like:

```
signal attack_complete
func _ready():
    $AnimationPlayer.connect("on_finish", self, "_on_finish")

func _on_finish(args):
    emit_signal("attack_complete", args)
```
This obviously works, but it's a bit its verbosity is less than ideal, in my opinion. Given the elegance of chaining signals and just using signals in general, I would like to propose a new keyword to gdscript (and attribute in C#) for propagating signals (with optional renaming)

As a suggested syntax, I think something simple like putting `propagate on_finish` with an optional second parameter for renaming the signal before propagating, such as `propagate on_finish attack_complete`. 

While I believe that this keyword approach is ideal for consistency with the `signal` keyword, it alternatively could be a builtin function, such as: `propagate_signal("on_finish")` or optionally, `propagate_signal("on_finish", "attack_complete")`. Forwarding parameters I think is fine and if different parameters need to be sent, it should be considered outside the scope of this builtin's use case and a new signal should be declared as it is today to facilitate this use case.

The suggested syntax above is just that, a suggestion, and I am open to alternatives, but I think that this kind of feature would be extremely beneficial to the engine's core scripting API.

**Comment by CptPotato** [comment]
I like the idea of relaying signals in this form.

It could also be implemented with less performance overhead (linking directly to the target signal) than implementing additional signals in gdscript just for the sake of emitting another signal.

**Comment by bojidar-bg** [comment]
Related: #23115.

**Comment by razcore-art** [comment]
I checked the other issues related to the topic and I feel like this solution is the best pick for GDScript, with a built in statement like `propagate signal_name`, it's by far the simplest and most in line with how (currently) GDScript works and the simplicity philosophy.

**Comment by ttencate** [comment]
I don't understand @jonbonazza's proposal. Where would the `propagate` be written? Taking the example:
```
signal attack_complete
func _ready():
    $AnimationPlayer.connect("on_finish", self, "_on_finish")

func _on_finish(args):
    emit_signal("attack_complete", args)
```

This obviously can't be written as:
```
signal attack_complete
propagate on_finish attack_complete
```
... because we're not saying _whose_ `on_finish` signal we're propagating. An object reference is really required here.

As to his alternative proposal, which I think would be:
```
signal attack_complete
func _ready():
    $AnimationPlayer.propagate_signal("on_finish", "attack_complete")
```
This has the same problem, except now the _destination_ object is unknown. (Having it implicitly propagate to `self` would require special handling of the `propagate_signal` method inside the interpreter.)

So to have this actually be feasible, we'd end up with:
```
signal attack_complete
func _ready():
    $AnimationPlayer.propagate_signal("on_finish", self, "attack_complete")
```
... which is very consistent with the `connect` syntax, does not require any special language-level trickery, and seems like it should be straightforward enough to implement.

It is also very close to my proposal on #18268, the only difference being that I suggested overloading `connect` to play the role of `propagate_signal`. But there's something to be said for having two differently-named methods, because it makes it explicit that you're connecting to a signal (GDScript currently allows having a method and a signal with the same name in the same class).

**Comment by razcore-art** [comment]
```
Group
  +- Player
  +- Enemy
```

I personally thought that if say `Player` has `signal "attacked"`, adding `propagate "attacked"` to same `Player` node, instructs the signal to be propagated to the parent. There's no need to know to whom to propagate, it's just about the parent<->child relationship

**Comment by razcore-art** [comment]
> Signals work on all `Object`s, not just `Node`s.
> 
> I think it would be needlessly limiting to only allow forwarding from and to nodes, and only if the destination node is a direct parent of the originating node. What if there is another level of nodes in between? (Doesn't even have to be a separate scene; could just be a `Node2D` containing a `Sprite` containing an `Area2D`, for example.) What if I have an abstract representation of my game state that's not based on `Node`s? What if I want to propagate a signal _down_ the tree, or sideways? (Rare, but conceivable.)
I agree with about the limitation, have only thought about parent<->child relationship. As for the multi-child hierarchy, I don't think it would be a problem, if we have:
```
Group
  +- Player
    +- Area
```
it would just mean to place `signal name` & `propagate name` in all the nodes from `Area` upwards except `Group` which would only define `signal name`.


> Having the _`Player`_ node declaring `propagate attacked` here is a nasty break in encapsulation, because now the child needs to have knowledge of its parent. This would mean we can't use `Player` in another context anymore. No matter what syntax we choose here, it needs to be the target object requesting propagation of signals from the source object, not the other way round.
That's a good point. What about if we could define signal like this: `signal attacked from node` so then on `Player` we'd have `signal attacked` & on `Group`: signal attacked from $Player` & `signal other_signal from $Player/Area` and so on.

> I don't think it's possible for objects to emit a signal that they haven't defined themselves. Where would subscriptions to that signal be stored? How would the interpreter check when you subscribe to a signal, that the signal actually exists?
I agree, that was a bad idea

**Comment by willnationsdev** [comment]
We could even rely on existing keywords. Let's say we have a Node that owns an object instance which emits an "initialized" signal...

   signal object_initialized(object) as initialized in obj, [obj], CONNECT_ONESHOT

   var obj = MyObject.new()

Where the buffered parameter list must refer to member variables or constants. Yes, no?

Or if those options don't work, then we'd have to decide if a different syntax works for scenarios such as this, or whether we just need to assume a default case of no passed in parameters and no connect flags.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
