### ISSUE TITLE
Yield, or ToSignal in GDNative?

### ISSUE THREAD

**Issue by OliPerraul** [godotengine/godot#23040]
Hello, anybody knows if there is a way to achieve yield() from gdscript or await ToSignal(timer, "timeout"); from c# using gdnative. Its seems theres no way to wait for a signal as it stands

**Comment by neikeq** [comment]
Yield and await are language features, so it depends of what language you are using.

**Comment by OliPerraul** [comment]
@neikeq  Just straight up c++ dynamic libraries built from the GDNative bindings.

**Comment by TechnoPorg** [comment]
This isn't possible in exactly the same way, as the C++ language doesn't have asynchronous programming like GDScript and C#. If the code that's supposed to be waiting is on another thread, you could probably set something like the following up: On the waiting thread, pause until a notification is received, maybe using a condition variable. Create a singleton with a function that sends the notification to the waiting thread, and lets it proceed. To the signal you're waiting for, connect that notifying function. You'd definitely want to watch out for all the usual potential dangers of multithreading while doing that, though.

Not that you likely care anymore, since it's been over three years since this issue was created 🙂

**Comment by akien-mga** [comment]
Thanks for the detailed answer. Closing as this was a general question/idea and not a big report.
