### ISSUE TITLE
Support for multiple return variables

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#23055]
It's really not that complicated, here is how it works in Lua (which GDscript is inspired by):
``` lua
function return_three_values()
    return 1, "string", {"an array"}
end

an_int, a_string, an_array = return_three_values()
```

Currently you would just create an array and put your variables in there, but there are three issues with that:
1. You have to pull them out of the array again
2. Its not as easy to read
3. Its not typed

**Comment by Chaosus** [comment]
> in Lua (which GDscript is inspired by):

Actually GDScript was inspired by Python where this feature as in several other languages, called "tuple"

**Comment by Jummit** [comment]
> > in Lua (which GDscript is inspired by):
> 
> Actually GDScript was inspired by Python where this feature as in several other languages, called "tuple"

It also has dictionaries, which are inspired by Lua's.

**Comment by OvermindDL1** [comment]
> It also has dictionaries, which are inspired by Lua's

They are?  They seem *extremely* similar to Python's dictionaries.  Lua instead has Tables, which though conceptually similar to Dictionaries have some pretty fundamental differences that GDScript doesn't seem to have?

**Comment by Jummit** [comment]
> > It also has dictionaries, which are inspired by Lua's
> 
> They are? They seem _extremely_ similar to Python's dictionaries. Lua instead has Tables, which though conceptually similar to Dictionaries have some pretty fundamental differences that GDScript doesn't seem to have?

Oh, It seems like I have overlooked something there. GDscript also supports the lua syntax of dictionaries:
```lua
var table = {
    key = "value"
}
```
instead of pythons

```lua
var table = {
    "key" : "value"
}
```
http://docs.godotengine.org/en/3.0/getting_started/scripting/gdscript/gdscript_basics.html#dictionary

**Comment by nathanwfranke** [comment]
I would opt for python/c# style tuples

```
func get_data():
    return (get_player(), get_health(), get_score())

var player
var health
var score
(player, health, score) = get_data()
```

Also possible support for something like `a, b, c = 5, 6, 7` as in python

**Comment by atbigelow** [comment]
Would love for a Python-esque multiple return syntax.

**Comment by Calinou** [comment]
@atbigelow Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
