### ISSUE TITLE
Nodes copy and Node support multiple output edge in AnimationNodeBlendTree in AnimationTree?

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#23050]
**Godot version:**
master branch

**Issue description:**
Currently I found that each node in AnimationNodeBlendTree in AnimationTree can only have ONE output edge
In which I think I cannot re-use the nodes.

So can nodes have multiple outward edge to increase reusability of nodes in AnimationTree?

Another issue is I found that nodes cannot be copy and paste in AnimationNodeBlendTree.
So if it would be more convenient if nodes can be copy and paste?

Thank you.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
