### ISSUE TITLE
Add support for overriding _call in GDScript

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#23066]
**Godot version:**
Godot 3.2+

**Issue description:**
Is there a reason we can't implement a `_call` method in GDScript the same way we can override `_get`, `_set`, and `_get_property_list`? I tried doing it earlier today and suddenly realized I *couldn't*. I was wanting to say, "if attempting to call method X, instead call X on my child node", and it wasn't a property, so I couldn't just use a `setget` to handle the override.

Just wondering if we could add that as a possibility or if there is some certain reason why it isn't supported.

**Comment by willnationsdev** [comment]
@aaronfranke I mean, if the current master branch is already in feature freeze, then obviously anything I propose as a future feature would apply to some future version of the engine, starting with 3.2 at the earliest. Is it preferred that I just omit that portion of the Issue text entirely? Cause that's pretty much the available option.

**Comment by vnen** [comment]
@willnationsdev it's simpler if you state the current version of Godot you're using, since it's where you're missing the feature.

That said, I don't think it's a bad idea. I think we can do it in an efficient way.

**Comment by aaronfranke** [comment]
This should probably be bumped to the 4.0 milestone since it's a non-vital feature.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
