### ISSUE TITLE
Why  godot is not used  flutter for  mobile

### ISSUE THREAD

**Issue by AttSee** [godotengine/godot#23064]
Why  godot is not used  flutter for  mobile ...I think it would be better  
Why use C# ؟ no need C# ..  godot no use  xamarin, visual studio like xenko

**Comment by groud** [comment]
I am sorry but you will have to be more precise on your issue.

What is your problem? Is there anything you need from Godot that is not there?

**Comment by LikeLakers2** [comment]
> Why godot is not used flutter for mobile ...I think it would be better

It'd be nice if you could compare it to what we use currently, and tell us what you believe the advantages might be to switching. We're open to feedback!

> Why use C# ؟ no need C#

C# is offered as a language option for those who need more performance than with GDScript. If you believe C# isn't needed, then please explain why.

> godot no use xamarin, visual studio like xenko

I'm not sure I understand. Is this supposed to be a bad thing?

**Comment by AttSee** [comment]
Flutter it gives access to native Android and iOS UI components which makes it far better than Flutter
Flutter aims to provide 60 frames per second (fps) performance, or 120 fps performance on devices capable of 120Hz updates.

It is also possible to build applications for the desktop  I did not try that
https://github.com/google/flutter-desktop-embedding
Also
I think will be adding good(dart & Flutter  )

**Comment by LikeLakers2** [comment]
> Flutter it gives access to native Android and iOS UI components

I don't believe we really need that for games, when it's really easy to make our own themed options screens using [Control nodes](http://docs.godotengine.org/en/latest/tutorials/gui/index.html).

> Flutter aims to provide 60 frames per second (fps) performance, or 120 fps performance on devices capable of 120Hz updates.

Most games only need 60 fps, from my knowledge. That said, I believe what Godot has currently is also capable of 120fps.

> It is also possible to build applications for the desktop I did not try that
> https://github.com/google/flutter-desktop-embedding

By the admission of the developers who made that repo (see [here](https://github.com/google/flutter-desktop-embedding/blob/master/Flutter-Requirements.md#flutter-application-requirements)), Flutter is not made to handle desktop applications.

> Also
> I think will be adding good(dart & Flutter )

If you believe Dart would be a good language to use in Godot, then please feel free to create your own bindings between Dart and Godot.

**Comment by AttSee** [comment]
Flutter is owned by google since a while and makes big progress on for mobile. godot and it’s users profit from all new features automatically.

**Comment by LikeLakers2** [comment]
> Flutter is owned by google since a while and makes big progress on for mobile. godot and it’s users profit from all new features automatically.

Okay... but is it any better than the UI system we have already? Have you considered how much we would need to change in order to replace our current UI system with Flutter? Would such a change even bring any worthwhile advantages? Do we even have a reason to want to implement Flutter in the first place?

**Comment by AttSee** [comment]
Yes a big change
I wish godot to choose right path

**Comment by groud** [comment]
To make it clear, if this was only up to me I would simply close this issue.
Dropping any random technology without a use case is not helpful. 

If there is anything Godot lacks that is available in Flutter, please tell us. Else there are no reason at all to integrate support for a technology which would be in no use for Godot.

**Comment by Shin-NiL** [comment]
The only thing I can see that we can get some inspiration from Flutter is its Android export workflow, it's great. But this has already been discussed in #18865

**Comment by AttSee** [comment]
@Shin-NiL  Yeah .. i agree need Flutter for export and AR support 
AR  not yet supported on Flutter   but  It will be in the future

@groud I'm not a professional 
I was talking about
- Mobile Support
-  performance
- Easy solutions instead of using  C++
This is what I want to say I'm done here

**Comment by groud** [comment]
> Mobile Support

This is already there.

> Performance

That's too vague to be considered as an issue. If you have performance problems in a specific situation with Godot please open another issue.

> Easy solutions instead of using C++

You can use Control nodes and GDscript to build your UI, which is simple enough. You don't have to use C++ to make games with Godot.

Well, I believe this issue is going nowhere. I'll close it until strong arguments are given in favor of the support for Flutter.

**Comment by gedw99** [comment]
@groud

I think this is worth revisiting.
I have a fair bit of flutter experience and I see a few incorrect assertions.

Use case :
Flutter run on desktop and mobile very very well.
It can also run on chrome.

Ease. It's easy to put a flute texture in now. Currently use it for video conferencing and it's fast. Mapping the framebuffer from Godot should be easy and I have seen it done.

Great 2d and forms.
Flutter UI controls are independent of the OS. You have very high quality controls that are easy to customise.
2d is easy to do with a flutter texture and already are expletives plugins.

There is an issue in flutter to allow direct calls from flutter to c and c++. It's getting done nowish. At the moment you have to go through a Java or objective c layer.

Plugins are very well supported.
A Godot plugin would once c or c++ embedding is supported as a plugin would be very easy to support.


Please ask for any links you need

**Comment by groud** [comment]
Once again, it is not because a framework works on multiplatform, is easy to use and supports plug-ins that we should integrate it. As good as it is, if it is not useful to make video games, it is not useful to Godot users. And integrating support for another framework is a lot of work, so it has to be worth it. 

Remember we are making a video game engine, not an app framework. So without a strong need for the functionalities flutter offers (which seem mostly to overlap with what Godot already does), this is not going to be implemented.

But if anyone wants to make a plug-in to support flutter, no problem. But it will not likely be built-in.

**Comment by VarolOkan** [comment]
Groud,

I think what would help here would be to be able to call Godot views, and return to the same or a different point in a Flutter app.

This would help propel Godot immediately as the go-to 3D rendering platform for iOS and Android for the current ongoing revolution in mobile programming. 

Likewise I agree that there is no real reason to tightly integrate Godot and flutter or use Dart inside Godots' rendering engine.  

Creating a native interface around any 3D based app  is something that would be of great benefit notwithstanding the availability of Godots' UI Nodes.

I can't imagine that something like this would take more then a few dozen or maybe 100 lines of code. 
How would we go about accessing Godots' API through calls eminating from a Flutter widget ( callback ) ?

**Comment by japalekhin** [comment]
Hey everyone, I'm a huge Flutter fan/developer and I just downloaded Godot today and let me just say this thread does not make sense at all right from the start.

One takeaway though (also the reason why I'm here) is the possibility of using Dart within Godot.

I've grown very fond of Dart and find it really easy to use.

> If you believe Dart would be a good language to use in Godot, then please feel free to create your own bindings between Dart and Godot.

Can anybody point me to a direction so I can start to learn how to do this? (Or if there's already work towards this direction.)

**Comment by LikeLakers2** [comment]
> Can anybody point me to a direction so I can start to learn how to do this? (Or if there's already work towards this direction.)

Sure! Though since you've said you're new to Godot, I advise you to try to learn Godot a bit before jumping right into making bindings. [Here's some documentation to help you get started with Godot.](http://docs.godotengine.org/en/3.1/getting_started/step_by_step/index.html)

With all of that said, I haven't looked into making bindings myself, so I'm not sure how helpful I can be, but I can link you to what I can find from some searching around:

https://github.com/GodotNativeTools/godot_headers (which is what you'll use to make the bindings)
https://github.com/GodotNativeTools (everything else from there except GDNative-demos is a binding)
https://github.com/ShadowApex/godot-go (binding)
https://github.com/SimulaVR/godot-haskell (binding)

There's also https://github.com/GodotNativeTools/godot_headers/issues/36#issuecomment-440971346 which I think(?) should give you a basic understanding of how to make a binding? (again, haven't looked too much into making bindings myself) Barring that, it may be useful to make a issue on that repo with any questions you might have.

You might also benefit from asking for help on some of the [community channels](https://godotengine.org/community). :) 

I hope something out of all this can help you!

**Comment by japalekhin** [comment]
> I advise you to try to learn Godot a bit before jumping right into making bindings.

Yup, that's what I've been doing since I downloaded Godot. I can live with GDScript since I have Python background as well.

Anyway, I realized that adding a language to Godot would seem like a massive task. I would love to do it but would actually prefer to just help if there's a project already in motion.
