### ISSUE TITLE
Colored console output

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#2308]
In an UNIX terminal, you can type this for example:

``` Shell
echo -e "\e[31;1mRed Bold Text"
```

However, this doesn't work in Godot, the sequence will be output as plain text:

``` GDScript
print("\\e[31;1mRed Bold Text")
```

(There are two backslashes in order to actually print one backslash.)

It doesn't work with `printraw()` either.

Either the sequences should be supported, or, better, there should be a cross-platform way of colouring console output, as Windows supports a subset of console colours too. Possible uses are:
- Highlighting errors and warnings
- Easier to read logs

**Comment by OvermindDL1** [comment]
\e in your echo command is not two characters but is instead an escape sequence, thus doing \\e will never work in any case like this.

**Comment by OvermindDL1** [comment]
Also, that is terminal specific, there are ways to use proper colors based on the detected terminal type.

**Comment by reduz** [comment]
yes this is not portable sadly

**Comment by akien-mga** [comment]
I guess we could have a ```print_colored``` statement of some sort that would rely on the OS class to define how to implement colouring on the platforms that support it, or do a plain ```print``` on platforms that don't.

Basically we could use ```\E[#;#m```on Unix (as used for error output as seen in https://github.com/godotengine/godot/pull/2737/files), and SetConsoleTextAttribute for Windows console (as in https://github.com/godotengine/godot/pull/2827/files).

Not sure if it's worth the pain though :)

**Comment by Calinou** [comment]
It looks like it's already possible, even though it's not straightforward:

```
var escape = PoolByteArray([0x1b]).get_string_from_ascii()
var code = "[1;32m"
print(escape + code + "Bold green text")
```

This should support any ANSI escape sequence. I haven't tested this on Windows yet, but Windows 10 is able to interpret ANSI escape sequences so it should work there as well. However, it won't work in the Output panel (escape codes will appear as-is).

**Comment by Zireael07** [comment]
Windows command line on any versions lower than Windows 10 does NOT support ANSI escape sequences, though.

**Comment by fire** [comment]
Remember to be able to disable text colours in the startup flags.

**Comment by lifelike** [comment]
You could use something like the public domain licensed single-file https://github.com/agauniyal/rang library or find something similar. I only tested it in linux, but it is supposed to work for windows as well.

**Comment by Calinou** [comment]
@lifelike Can that library work if you don't use the standard library to print text? Its README states:

> *Rang* uses iostream objects - `cout`/`clog`/`cerr` to apply attributes to output text.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
