### ISSUE TITLE
Adding Qt property binding-like features to GDScript

### ISSUE THREAD

**Issue by Larpon** [godotengine/godot#23115]
Would it make sense to add a [property binding](http://doc.qt.io/qt-5/qtqml-syntax-propertybinding.html)-like language feature to GDScript?

I know GDScript is a very imperative language. And property bindings are used declarative.

I'd like to hear opinions if this would be a nice feature to have or if it would mess up the language - blending things and paradigms. Property bindings, as used in the Qt QML language, are on many Qt programmers top list (including my own) over the most powerful features of QML.

I believe there's a very good reason for this: It's syntactic sugar - but it's darn nice and saves _a lot_ of typing and wrapping. It's a fantastic shortcut for updating most types of values, you can use values from other object's properties and expressions and bind them as you see fit. Now there's a downside - as you loose control of flow in the execution order. This is handed over for the QML engine to decide.

Let me give an example of how a property binding could look like in GDScript. (I'm going to ignore some important things like variable scope and direct access to other entities - this is a head-ache a given implementation must solve somehow)

In game programming you often need a lot of values updated based on other values, right?
The x,y position of a NPC is based on various factors and values from all over the engine, like where's the player heading, do we have a direct line of sight to object A,B and C - is the lights on in the room etc. many factors depending on game type. Now with property bindings you can "bind" all these factors into one expression for any given value you want updated:
```
# pseudo-code sample of an npc's position that is
# always 200 pixels to the right of the player

onready var player = get_node("/root/scene/player")
onready var npc = get_node("/root/scene/npc")
...
# Sample binding syntax
npc.y: player.y
npc.x: player.x + 200

# From this point on, unless broken, the npc object will always have 
# the same .y coordinate as the player - it's .x value is the player object's .x coordinate + 200 pixels.
```

Another example of updating values (mixing in QML syntax):
```
onready var player = get_node("/root/scene/player")
onready var npc = get_node("/root/scene/npc")
...
player.onXChanged: {
    npc.updateAI()
}
player.onYChanged: {
    npc.updateAI()
}

# Here we tell the npc to update it's AI code path 
# every time the player object's .x or .y property changes.
```

Another one:
```
onready var player = get_node("/root/scene/player")
onready var light_source = get_node("/root/scene/light1")
...
player.shade.color: light_source.color
player.shade.opacity: distance_between(player,light_source) * 0.5

# Here we give the shade color of the player the same color
# as some light source found in the scene
```

The Qt docs linked above explains the concepts of property bindings better than I ever could. They can be added and removed (broken) etc. But bindings are not limited to only assigning direct values - it's also expressions among other goodies. So you can throw e.g. easing functions in there or more complex factors - the expressions are re-evaluated every time a property or value _in_ the expression is updated.

What do you guys think? Are there other people coming from Qt or KDE here that have had the same idea? It's probably something of an overhaul but could be very much worth it?

**Comment by Zylann** [comment]
Sounds similar to #6491

**Comment by Larpon** [comment]
@Zylann - you're right. It's similar in that you can observe value changes - but #6491 misses out binding expressions - I've chipped in on the issue.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
