### ISSUE TITLE
Hide private func and variables in editor

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23110]
**Issue description:**
This is more a suggestion and not a bug. We all know that all funcs and variables are public in godot, but it would be great if we could hide wanted funcs and vars from autocomplete from outside the script. For example:

`#my_class.gd
class_name MyClass

var public_var
hide var _private_var
`

`#my_refering_class.gd

var instance:MyClass
`

when refering to instance in the second file I won't get auto-completion for the hidden variables only the non hidden (kinda like a public private but only for auto completion this could work also with funcs)

**Comment by Zylann** [comment]
I though these would almost never popup because they start with `_` and I never write `something._` :s

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
