### ISSUE TITLE
Making run in Android device more convenient

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#23137]
**Godot version:3.x

**OS/device including version:**

**Issue description:**

1. If only one Android  device is connected, just click the android icon to run on that device directly, without one more click to selecting the device.
2.since it take some time  to install and run on device, it would be nice to have an option to make this process running in the background.
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
> If only one Android device is connected, just click the android icon to run on that device directly, without one more click to selecting the device.

This seems to be already a thing in 3.2

**Comment by Calinou** [comment]
Note that `1.` was implemented already.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
