### ISSUE TITLE
Custom BBCode for RichTextLabel

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#23135]
I know there's _draw functions for characters similar to what i'm proposing which make it easier to make your own text rendering engine but I think being able to work with, tweak and extend the higher level tools the engine gives you to suit your needs is more efficient. 
RichTextLabel for instance does a LOT of nice things for you which you would have to re set up in your own implementation. It being based in C++ also makes it faster and being an inbuilt note means it just generally plays nicer with everything else.
This also makes it easier to make custon "control codes" for game specific stuff.
(specifically, control_codes are bbcode that don't parse text and don't need an end tag. They're just there for stuff like shaking the textbox, adding pauses or changing the text speed. All mid sentance or as metadata.)

Everything within square braces could be automatically treated as a bbcode tag and hidden thus requiring escape characters to use square braces them normally (although square braces already cause strange rendering problems so not a big loss).

Here's my idea for a couple of functions and classes for or related to RichTextLabel as an implementation of this feature.

If you don't like the idea of implementing more classes for this most of these could easily just be dictionaries but I think it makes everything far less janky.

function **evaluate_bbcode(string bbcode)**

returns an array containing sets of RichTextString objects for the passed bbcode

class **RichTextString**

Member values:
Dictionary parameters: {"parameter":value} (Dictionary of the parameters passed in the bbcode)
Array characters: (Just an array of RichTextCharacters, the text between the tags)

class **RichTextCharacter**

Member values:
index: position in string (Read only or auto support insertion? Don't know if this would be inefficient and liable to mess things up :0)
offset: (The most "local" local positioning. Relative to where the character would normally be displayed. Auto updates whenever another position value is changed)
local_position: (The character's position relative to the textbox. Auto updates whenever another position value is changed)
globall_position: (The character's position relative to the screen. Auto updates whenever another position value is changed)
modulation: (Color and alpha transparency.)
font: (Controls the character's font. nuff said.)

function **evaluate_control_code(string control_code)**

Like evaluate_bbcode it returns an array. This time full of RichTextControlCode objects for that specific control code
I'm not sure whether it would be more efficient to make control codes their own thing but if they are I'd suggest using < and > to denote their specific tags

class **RichTextControlCode**
int index: (Position in overall bbcode string. Keep in mind that codes don’t take up any characters in the final string)
Array characters: (An array of RichTextCharacters)

Note that I'm not familiar with how bbcode and such is parsed "under the hood" so if anybody else knows a better implementation or something I'm missing please feel free to speak your mind below.
Also, if anyone's used textmesh in unity before and see they handle something better than this pitch, drop it below.

**Comment by girng** [comment]
very well-written. thank you for inspiring yokai

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
