### ISSUE TITLE
Suggestion: Too much clutter when exporting arrays

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23136]
**Godot version:**
v3.1.alpha.calinou.b550f93

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
When an array is exported and an object type is selected... if a resource is added and then "opened"/unfolded. there is too much clutter in the editor inspector:

<img width="245" alt="captura de ecra 2018-10-19 as 11 56 01" src="https://user-images.githubusercontent.com/10358443/47214650-897c9b00-d396-11e8-8d4a-d579924052ce.png">

for example, when compared with the unity approach:

<img width="354" alt="captura de ecra 2018-10-19 as 12 01 13" src="https://user-images.githubusercontent.com/10358443/47214714-bf218400-d396-11e8-9a56-02379a8557f4.png">

The resource "sub-properties" gets to much in the way!
Another question will it be possible in the future to make it so a property in the inspector can be of a custom type for example:

```
class CustomType:
   export(int) var number;
   export(String) var name;
```

and then having it in the explorer without having to create in and drag and drop from the filesytem first!

**Comment by swarnimarun** [comment]
The actual problem is the fact that Godot resources are loaded inside the same context, as a sub-branch. This is useful for some things like shaders and materials but lots of things get problematic because everything tends to get cluttered a lot.

I never liked this UI change much but the main problem is that it has no end, you just keep opening one resource inside the other.
I think we should rather just make it the way it was and give the ability to create custom Inspector stuff with ease and probably use that to make the material and shader UI easier.

At this point, this thread might deserve a discussion tag too.

**Comment by xDGameStudios** [comment]
About your "custom inspector stuff" I actually suggested that in another post!!
I think godot would gain a lot from giving more control over the inspector UI, like for example: 

1) being able to add buttons (for triggering stuff - usefull for realtime debugging). 
2) Renaming labels imagine you want to use a Vector2 and instead of x, and y you want the labels to say "width" and "height" 
3) a bool variables that when true disables another variable input field (or hides it and shows another one).

**Comment by xDGameStudios** [comment]
Maybe we could settle for something like, a "minimal mode" where only the exported variables are loaded... and that could be set for every (sub)-resource type.

This could be a way to hide the "Resource" category along with "Local To Scene", "Path", "Name".

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
