### ISSUE TITLE
DirectX 9+ Support on Windows

### ISSUE THREAD

**Issue by pallavnawani** [godotengine/godot#23166]
Godot only supports OpenGL/GLES. 

But on Windows PC, which is the 90% of all PCs & Workstations, the most widespread and well supported Graphics API is Directx. Furthermore, if you use MS Windows automatic driver install facility, only DirectX drivers are installed, and not OpenGL.

Additionally, many users are non technically aware, and are not able to find and install the correct device drivers for their graphics card.

_This leads to a situation where Godot crashes on start on many devices. Especially so for Casual PC Gamers, who are for the major part middle aged to old aged non technical people._

**So In order to make use of Godot viable for making a game targeting Windows PC platform, godot should support DirectX 9+ as a render backend.**

**Comment by star-tek-mb** [comment]
OpeGL drivers installed by your Card driver. Even with dx9 and no drivers you will get poor performance.
I think dx11 or dx10 must be choosen, not dx9.

**Comment by Ranoller** [comment]
I put an thumb up in your proposal... but i can anticipate to you that your proposal is an clear case of " this will never happen TM "

**Comment by FlamyAT** [comment]
I'm not sure, but I think that the licensing of Direct3D etc. breaks the compability with MIT

**Comment by akien-mga** [comment]
Won't happen for several reasons:
- Godot is cross-platform at its core, and won't bother supporting a proprietary API for a single platform if there are open source alternatives (OpenGL, Vulkan)
- If you don't have OpenGL drivers installed, you likely also don't have DirectX installed either, so that's not a solution. What you're experiencing is probably people who don't have drivers for OpenGL 3.3 (required by Godot 3.0), and those likely wouldn't have drivers for DirectX 10+ either. This will be solved with Godot 3.1 which supports OpenGL 2.1 again, which 99.9% of the market should support.
- Our way forward is to implement a Vulkan backend which is cross-platform and performant, and not spend time on a 15 year old DirectX 9 which cannot support any of Godot's rendering features.
- Eventually, the Vulkan backend could be used together with a portability layer like gfx-rs which would allow to translate to DirectX 10+, Metal and OpenGL if need be - though even then I doubt DirectX 10+ support will be really useful when all hardware capable for DX10 should also support Vulkan.

**Comment by pallavnawani** [comment]
If you are not planning to support DirectX 9 fine. DirectX 10 will do as well, but it is really rather important to have DirectX support, NOT for the developers, but for the people who will be playing the game!

Also, supporting DirectX doesn't prevent Unity or SDL from being cross-platform. **Also, it is indeed pretty much guaranteed that every windows installation will have DirectX drivers installed**, otherwise windows 7 onwards will work in very low resolutions and will slow down to a crawl. If a windows PC is working in resolutions higher than ancient 640x480 then it means it has working DirectX drivers installed.

I recently dropped Godot as the engine of my new in-development game for casual PC gamers because of lack of DirectX support. Having used Godot for long, and because I really liked it, I thought that it would be remiss of me not to offer this suggestion. Thanks, anyway!

**Comment by kn00tcn** [comment]
actually, windows 7 is not low resolution by default, that was only up to vista (or actually vista had 1600x1200, but not 1920x1200)

dx11 would be better than dx9 for performance or visual effect reasons, although i'm not too familiar with ogl performance outside of amd (which is 'always' slower, potentially prone to more crashes)

**Comment by Calinou** [comment]
The lower performance on AMD GPUs on Windows should be less of a concern as the Vulkan renderer (slated for 4.0) should offer more consistent performance.

**Comment by kn00tcn** [comment]
yes, though that's probably at least a year away?

also, vulkan isnt supported before GCN (then again those people havent had a driver in years either, except for linux)

**Comment by Calinou** [comment]
> also, vulkan isnt supported before GCN (then again those people havent had a driver in years either, except for linux)

The GLES2 renderer should be better for those cards, as it targets low-end hardware.

**Comment by kn00tcn** [comment]
well i mean, it's not like 6970 is low end, though most people left by now are lower end laptops

my point was that opengl is losing performance if you wanted to make or run a game with somewhat fancy visuals

there may also be crashes or artifacts that cant get fixed due to no more driver support (though i've found workarounds in the past)

**Comment by OvermindDL1** [comment]
> my point was that opengl is losing performance if you wanted to make or run a game with somewhat fancy visuals

There's no reason for that though.  Using the core direct OGL calls might be more inefficient in some cases than some DX calls, there are cases where the inverse is true as well, and by using OGL extension calls you can regain those advantages regardless.  If a well made OGL program is slower by anything less than an error bar over a well made DX program than that sounds like a driver fault, not a fault of the API, and thus the driver should be fixed.

**Comment by kn00tcn** [comment]
> a driver fault, not a fault of the API, and thus the driver should be fixed

yes, it's well known that ati/amd has had multiple struggles with opengl performance & bugs for a couple decades

radeon dx11 is also not multithreaded, so in certain situations (draw call heavy?), even dx11 performance is lower than it should be

i wasnt blaming the api but describing the windows proprietary driver situation that may have higher importance to some users, plus there wont be new drivers for older gpus that dont support vulkan either

but it's not usually some massive performance hit, maybe 5-15%, bigger concern is if there's a higher chance of crashes (there was a wave of them when driver 10.4 came out, hopefully that kind of situation is long gone)

example citation from a valve developer: https://richg42.blogspot.com/2014/05/the-truth-on-opengl-driver-quality.html vendorA is nvidia, B is amd, C is intel

anyway, just some interesting quirks to be aware of, the need for dx continues to decrease over time, the linux open source driver continues making great progress, dont take my amd comments too harshly since most other aspects of theirs are great
