### ISSUE TITLE
Collisions and bezier curves on Line2D

### ISSUE THREAD

**Issue by NewNodeGames** [godotengine/godot#23194]
**Issue description:**
Could be nice automatic collision support for Line2D node and rounded lines with bezier points for use in game maps.

**Comment by pwab** [comment]
Somehow related to #16765?

> However, it can be combined with Path2D and CollisionPolygon2D with a bit of scripting to do what you describe: Path2D uses Bezier curves that can be used to generate the line points and collision segments.

Oh that is a neat idea. I have to test this out!

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
