### ISSUE TITLE
Enable HiDPI by default

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#23203]
In project settings there's an option to Allow Hidpi. Not sure why, but by default it's turned off, which as a result totally breaks any game when using high resolution with desktop scaling enabled. Every single time I download and load some project, I need to enable the option, otherwise the window appears in weird spot and fullscreen is totally unusable. But what's worse, when you download any game made in Godot, developers aren't usually aware of this option, thus making it pretty much impossible to play it if it's fullscreen.

There was a time when I noticed that this option causes excessive GPU usage, not sure if that's still true. Is there any reason not to enable it by default?

**Comment by Jalu1** [comment]
From what I can tell, it used to cause issues by incorrectly scaling on older versions of windows 10, but it appears to now have been fixed, so sounds good to me. I probably do not know all the facts though

**Comment by Jalu1** [comment]
[Created a fork, set _allow_hidpi true,](https://github.com/Jalu1/godot/blob/3f0a2cc5c934c770070442178eb4d2cfaaa4f344/core/os/os.cpp#L723) not sure if that is all you have to do. Not home ATM, can someone else test the fork?

**Comment by toger5** [comment]
Also read: #8636
The current solution definitly should get improved. I'm not sure if changing the default is enough though.

**Comment by reduz** [comment]
This option will not be enabled by default, the reason is as follows:
1) You make a game (3D generally) in your computer, it runs OK. You monitor is not HiDPI
2) You give it to someone else who has an Intel IGP and HiDPI, the game will run like ass, and the person who made it will not understand why.

You shouldn't enable it unless you know what you are doing. If this fixes a bug, it's fine but the bug should be fixed instead of toggling this on. I suggest a different issue is filed for that bug.

**Comment by reduz** [comment]
Also, I think this issue was fixed eventually ( I remember fixing it for 3.1)
