### ISSUE TITLE
Custom constructor for gdnative classes

### ISSUE THREAD

**Issue by Lucrecious** [godotengine/godot#23260]
As far as I know, there's no way to setup a constructor with parameters on a class in GDNative.

For example
```
class MyClass : public Reference {
     GODOT_CLASS(MyClass, Reference)
public:
     MyClass(int num) {
          this->num = num;
     }

     MyClass() : num(num) {}
private:
     int num;
};
```

Only the MyClass() with no parameters gets called. If I removed MyClass(), then I get an error because a reference instantiates itself with a simple "new T()".

I know the workaround is easy, but I figured since many small improvements have been getting into nativescript, why not this one?

**Comment by bojidar-bg** [comment]
Note that while native Godot classes do not support constructor parameters, GDScript classes support them, so it would be natural for GDNative classes to support them as well.

While [NativeScript::new (_new)](https://github.com/godotengine/godot/blob/cf09952b6bfd93901a38fe3bc398973fbeb9d4f9/modules/gdnative/nativescript/nativescript.cpp#L481) is marked as vararg, it does not use the arguments passed to it.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
