### ISSUE TITLE
Selecting a node in the scene dock, changes the dock width.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#23292]
**Godot version:**

eeee47196c19dc271d6fcf8981946a1a29efd16a

**OS/device including version:**

Linux

**Issue description:**

![peek13](https://user-images.githubusercontent.com/4047289/47530587-4e54fd00-d8ab-11e8-8cc2-507cfa005ad3.gif)

**Comment by YeldhamDev** [comment]
@akien-mga Just checked here, and yep, and can't reproduce it before ground's commit.

Also, I did more testing, and my previous commit (#23290) actually doesn't really work because the docks now handle values completely differently from one another.

**Comment by groud** [comment]
This is probably due to the add script icon pushing the right border. Apparently, the split_offset from hsplit container is calculated from the minimum size, which becomes bigger when the button is visible.

I will investigate what can be done.

**Comment by groud** [comment]
Well, here is what I found out:
- the minimum width of the dock calculated when the button is visible is higher than the custom minimum size I defined.
- this is probably due to the LineEdit field having a minimum size (which I find is weird...), but we cannot change this now as it will be compatibility breaking.

We have two solutions then :
- Encapsulate the top buttons ("Add child node", "Instantiate scene", "search field", "add script") into a control without any minimum size, so that the content of the line is clipped if there is not enough space to display the whole line
- increase the minimum size by the size of a button.

Tell me what you prefer.

**Comment by capnm** [comment]
> this is probably due to the LineEdit field having a minimum size

I think it is not a problem with the minimum size - the line edit just for some reason does not shrink his size:

![peek15](https://user-images.githubusercontent.com/4047289/47559211-30bc7d80-d915-11e8-8f86-2299f7e70729.gif)

**Comment by groud** [comment]
Yes it is. As I said, the split_offset from hsplit container is calculated from the minimum size.
So if the minimum width changes, the splitter positions changes too.
