### ISSUE TITLE
Ability to Pre Edit State of PackedScene (Preferably also without tools compiled in)

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#23341]
Currently you are unable to edit a loaded PackedScene without instancing (and even when instancing editing it requires tools being compiled in)
This prevents a lot of defensive programming which you would otherwise be able to do.

Instancing it also triggers all the code in _init() of all scripts which can cause errors and for untrusted code is very dangerous. Being able to remove anything untrusted or error prone before it's executed is important.
#22049 is very relevant

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment]
I am sure we have either a duplicate issue or a proposal already?
