### ISSUE TITLE
Reload all files from file system

### ISSUE THREAD

**Issue by telaviv** [godotengine/godot#23366]
I often use my git project to do things like `git bisect`. It seems very difficult right now to refresh all the files to their file system values. My current workflow is to change the git code, then restart my godot editor.

**Comment by fire** [comment]
Is this the same as deleting the .import folder?

**Comment by telaviv** [comment]
I'm not sure. Is there documentation about the .import folder?

**Comment by Zylann** [comment]
Do you mean the file explorer in Godot is not updating when you use git to reset the workspace to a given commit?

**Comment by telaviv** [comment]
Yeah that's what I mean. I mean maybe it's not supposed to auto update since you could lose your changes that way. To have an option to force a reset would be nice.

**Comment by Calinou** [comment]
You can reload files to an extent by choosing **Scene > Revert Scene** in the top menu. This may not work for all use cases though.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
