### ISSUE TITLE
When name one node name to space(" "), then rename node, space will disappare.

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#23378]
**Godot version:**
dev.calinou.942e0c4

**OS/device including version:**
win10

**Issue description:**
When name one node name to space(" "), then rename node, space will disappare.

**Steps to reproduce:**
1 name one node name to space(" ").
2 rename node.
3 space will disappare.

**Comment by qarmin** [comment]
This is expected behaviour to cut space between and after name, but giving as name only spaces shouldn't be allowed. When I save this scene and open it later, then name of node back to past.

Also when I try to move this node this error eccurs:

> ERROR: set_name: Condition ' name == "" ' is true.
   At: scene/main/node.cpp:930
ERROR: Node not found: /root/EditorNode/@@5/@@6/@@14/@@16/@@20/@@24/@@25/@@26/@@42/@@43/@@52/@@53/@@5036/@@4901/@@4902/@@4903/@@4904/@@4905/Node2d/
   At: scene/main/node.cpp:1316
ERROR: _focus_node: Condition ' !node ' is true.
   At: editor/scene_tree_dock.cpp:2158

Steps to reproduce:
https://streamable.com/egstb

**Comment by akien-mga** [comment]
The scene tree dock should not allow naming nodes with `new_name.strip_edges() == ""` (i.e. `""` or `"    "` are illegal node names).

**Comment by zhagsenkk** [comment]
I will try to fix it

**Comment by Alien1993** [comment]
This is linked to #23376 I think, if that's the case it should be solved by #23381.
