### ISSUE TITLE
Filesystem dock should have ability to rename multiple files/folders

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23377]
**Godot version:**
3.1 aeddb30

**OS/device including version:**
Windows 10

**Issue description:**
When I try to rename multiple files I must do it with system file manager or one by one in file system dock. I think that should be option to multiple files in filesystem dock just like it is in Scene dock.

For me that renaming should look like in Nautilus in Gnome because is simple and powerful
![aa](https://user-images.githubusercontent.com/41945903/47651020-513d3f80-db82-11e8-8954-a7653d185376.png)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
