### ISSUE TITLE
Add editor setting to use raw (0 to 1) or 255 color range values by default

### ISSUE THREAD

**Issue by xodene** [godotengine/godot#2339]
A reminder to implement - for @reduz

**Comment by akien-mga** [comment]
I don't think that relying on an editor setting for this would be a good idea. It would mean that you project would not work properly on a platform using an editor setting different from yours.

It could of course be made a project setting, but that sounds like a hack to me too. It means your code who only work depending on an editor setting, and if this editor settings was changed it would break. Like high school calculators where you can choose between radians and degrees, and all students get bad results because of forgetting to check this before doing some trigonometry :D

I guess Color() could be defined to accept either (int, int, int) or (float, float, float)?

**Comment by reduz** [comment]
Mariano fixed this already for the color picker. For the engine itself I guess it doesn't make much sense

**Comment by reduz** [comment]
Wait.. i don't think there is any way to distinguish in the constructor, BUT we could add some function like Color8(r,g,b,a) that takes values from 0-255, would this be acceptable?

**Comment by reduz** [comment]
ok did, that, closing
