### ISSUE TITLE
Small animation editor and bones improvements 

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#2340]
This is an issue for small anim editor improvements. After working for quite some time with it following issues appeared for me.
1. It would be nice to move the timeline cursor beyond the animation lenght. Preferable would be a toggle button which can release the cursor or keep it within the limits. Sometimes it is nice to duplicate keyframes beyond the timeline.
   2.Imho it would be good if we just see the node name with pos,loc,rot and not the complete path to the node. Often you cannot see which keys you are editing, because the path is so long. If then pressing on the name you could edit the whole path.
2. There is the clear pose operator. But it is useless for a character because the default pos is at 0,0 scale is at 1,1 and rot at 0. Would be nice if we can define an anim as default pose which this function will use as reference for clearing the pose.
3. I wish we can hide Bone Armatures. Maybe add is as a function into the skeleton menu.
4. Coloring Bones would be awesome too.
5. adding IK with reference bones would be great! So we can for example move the upper body and the feet will always stay at its place
6. constraint bone width to viewport zoom. Currently the width is absolute, which can result in very fat bones when zooming out, so you the character is hardly to see.

**Comment by xodene** [comment]
+1 for hiding bones. Gets really messy animating, so I have to run the scene to really preview the animation.

**Comment by reduz** [comment]
tagging this 2.1, There will be a lot more work in the animation editor for this version

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by therealrobster** [comment]
Just adding a vote for hiding bones.  It would be great to be able to choose draw styles on them also:
- line or current style (maybe others also, boxes etc?)
- opacity of bones (still want to see them, but not so glaring that I can't see my character)
- hide / show bones (with shortcut key so I can quickly preview the animation)

Ex professional animator here, would love to see this stuff.  Loving Godot, keep up the great work.  Thank you

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
