### ISSUE TITLE
wrong rect_position in _ready

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#23471]
**Godot version:3.1 alpha 2

**OS/device including version:**

**Issue description:**

in  _ready the value of rect_position of the Control itself is not correct.

Only after wait a frame  yield(get_tree(), "idle_frame"), its rect_position can be get. 
in 3.0, the value can be get immediately in _ready.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by reduz** [comment]
This is not a bug, it is expected. Controls are not laid out according to their rect or container tree as soon as they enter the tree but a bit afterwards, so it's done in a single pass (otherwise it will be very inefficient).

connect to "resized" signal or check NOTIFICATION_RESIZED instead if you want to know when it gets the actual size.
