### ISSUE TITLE
button->shortcut->make unique   does not work

### ISSUE THREAD

**Issue by mokalux** [godotengine/godot#23577]
**I looked for the opened issues and it seems this bug? has not been reported yet.**

**3.0.6 stable**

**WINDOWS 10 64bits**

I created 2 buttons, then added shortcut to the button1, I copied the shortcut over to button2 then clicked on the second button make unique.
What happened? when I changed the shortcut key of the second button, the same shortcut key was applied to the first button.
What was expected? the new shortcut key should be applied only on the second button.

**Steps to reproduce:**
create 2 buttons
add shortcut key to the first button
copy the shortcut over to the 2nd button
make the copied shortcut of the second button unique
modify the shortcut key of the 2nd button
the new shortcut key of the second button is also applied to the first button!

[x_godot_bug_make_unique.zip](https://github.com/godotengine/godot/files/2558545/x_godot_bug_make_unique.zip)

**Comment by Zylann** [comment]
I think the problem here is that `Shortcut` AND `InputEventKey` are both resources, and first one contains the other. What happened is you made the `Shortcut` resource unique, but the contained `InputEventKey` wasn't made unique. This is by design.

There are several ways to fix it:
- Make the `InputEventKey` unique instead of the `Shortcut` (but that's error prone if one day you want the shortcut to not be a key)
- Make both `Shortcut` and `InputEventKey` unique
- Use `Make Sub-Resources Unique` which makes resources unique recursively:
![image](https://user-images.githubusercontent.com/1311555/48154586-e649e200-e2c0-11e8-91af-01c02d2c4802.png)

However, what I don't like with the last solution is that you cannot decide to run it on a single property. All properties of the button holding a resource (like the texture) will all be made unique.
A nicer alternative would then be to have a `Make Resource Unique Recursively` option (because always making it recursive would have other bad side effects for example if the resource itself holds textures for example).

**Comment by mokalux** [comment]
Thank you Zylann.

So that's not a bug, it's just that I made unique the wrong parameter.

I suggest to close this issue as this is not a bug and there are other issues which require more attention.
