### ISSUE TITLE
Allow root motion to track nodes other than skeleton root bone

### ISSUE THREAD

**Issue by David-Ochoa** [godotengine/godot#23584]
**Godot version:**
Godot 3.1 alpha 2 64 bits

**OS/device including version:**
Windows 10 Intel Integrated

**Issue description:**
I need to import some Mixamo animated characters, they don't have a root bone for motion tracking so when setting root motion track to hip bone the animation looks distorted. I tried to solve it in two ways:

a) Added a Position3D and animated the translation to match the character movement.
b) Added a bone to the character, directly in the COLLADA file, this bone is child of Hip bone, it's not the root bone.

In both cases the root motion tracking doesn't recognize the nodes.

**Steps to reproduce:**
Open attached project and edit WithPosition.tscn
Select the AnimationTree and change the root motion track to root or root_doc

**Minimal reproduction project:**
[ImportRoot.zip](https://github.com/godotengine/godot/files/2559883/ImportRoot.zip)

**Comment by itbrandonsilva** [comment]
Have you found any success with Root Motion at all?

**Comment by David-Ochoa** [comment]
I managed to apply ZX displacement and Y rotation to a new root bone, but it doesn't work as expected because I'm taking it from the hip bone, it works for animations moving forward in a straight line, but I tried  to use it with rotating animations (turn left/right) and the results were not satisfactory.

Because of that it would be nice if root motion could track other nodes, then I could add an import script or add an independent node and animate it to have an accurate transform for root motion.

I'm using Mixamo because I'm not an artist and this is an option to get new models in my game. If you are curious this is my powershell script:
[Mixamo COLLADA Joiner](https://gitlab.com/DavidOC/fragMotionColladaExporter/blob/master/JoinAnimations.ps1)

Upload/Choose a character, download TPose in COLLADA, individual animations should be downloaded without skin and located in the same folder as the TPose file, run script passing main TPose file and output file. If you pass a third parameter (root_rotation) then rotation will be applied but you need to install Math.Net numerics (the script expects the DLL to be located a .\MathNet.Numerics.4.7.0\lib\net40\MathNet.Numerics.dll).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
