### ISSUE TITLE
Android export for GLES2 doesn't include textures unless ETC import is configured manually

### ISSUE THREAD

**Issue by gattila** [godotengine/godot#23650]
Godot Version 3.1 Alpha 2

Android 6.0, Xiaomi Redmini Note 3 
GPU: Adreno 510

Issue description:

I created a little project to test the 3D of GLES2 with android. It is a simple app with a rotating blue cube and when a user tapping the screen appears a spaceship. After I exported it to droid and tested on my device, I found that the blue cube is Ok, but the spaceship not appeared. I checked the logcat, and I found the app did not find some resources. I checked the generated APK file, and I also did not see the incriminated files. I used 64 bit version of windows 10 for development/export. I also exported a windows version from the same project, and it run flawlessly, it seems that the issue related with the Android export only.

I attached the project, the logcat result and the zipped archive of the APK file.

[Playground2.zip](https://github.com/godotengine/godot/files/2569194/Playground2.zip)

[logcat.txt](https://github.com/godotengine/godot/files/2569195/logcat.txt)
[Playground2 _apk.zip](https://github.com/godotengine/godot/files/2569196/Playground2._apk.zip)

**Comment by akien-mga** [comment]
The problem is that Android uses the `ETC` compression format for GLES2 (and `ETC2` for GLES3), but by default only `ETC2` and `S3TC` (desktop) are imported. (See in `rendering/vram_compression` in ProjectSettings).

Enabling `ETC` import and reimporting the `freelancer.jpg` texture fixes it. But those are cryptic settings for most users, Godot should make sure that the correct formats are imported before exporting to a target requiring them.

**Comment by gattila** [comment]
Thank you, it solved my problem.

**Comment by minifigmaster125** [comment]
Tested this out in a sample, project, and the fix works. But should the ETC import option be enabled by default or called out in the docs for people targeting Android GLES2? I'm testing a project I was developing in 3.0, just imported the whole thing into 3.1 alpha 2. I get a whole bunch of scene loading issues which I think are propagating from the failure to load textures, and I don't know a good way of fixing the whole project without reimporting each asset individually. It seems like deleting the import folder might work, but haven't had success so far.

**Comment by akien-mga** [comment]
It's not really a "bug" per se but more a usability issue, and it's not easy to fix. Adding documentation will have to make do for 3.1, and for future releases we should rethink the whole project creation workflow to allow setting the proper default settings from the start (e.g. GLES2 project for mobile -> enable ETC import).

**Comment by akien-mga** [comment]
#25237 should help a lot already.

**Comment by rhossack** [comment]
This likely constitutes a new feature, but I had a head-scratching moment the other day because I wanted to support a workflow that meant using GLES3 on desktop, and GLES2 on mobile (this is for VR development, btw). When I tried switching the project to GLES2 to run on mobile, it crashed. Checking the logs via adb, it was trying to load assets that weren't there. The fix was switching to Etc. IMO, that should either happen automatically, or be a pop-up message when you change the video driver that is an impossible-to-miss reminder.

**Comment by akien-mga** [comment]
Actually I fixed this issue in 3.1 already with #26523, as exporting a GLES2 project to Android now requires `rendering/vram_compression/import_etc` to be enabled. Enabling it requests an editor restarts and triggers a reimport of all textures.
