### ISSUE TITLE
AnimationPlayer keyframe at time 0.0 sometimes flashes an incorrect value.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#23659]
**Win10 64bit - c3023e84c2ec38f43aff872c7f2db473e5bc665a**

Minimal Project: [3.1 Keyframe Time Zero Issues.zip](https://github.com/godotengine/godot/files/2570370/3.1.Keyframe.Time.Zero.Issues.zip)

Was stringing together a sequence of animations from different AnimationPlayers using sprite sheets.  For some of them, they would flash their last keyframe value when starting the animation.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/13004169/48324220-9492b600-e638-11e8-8392-24d19679d61b.gif)

The output reports time zero, and the keyframe values are in correct order, but in game it reports the last keyframe's value.

![image](https://user-images.githubusercontent.com/13004169/48324097-16361400-e638-11e8-8aeb-3f9193721d7f.png)

![keyframe_issue](https://user-images.githubusercontent.com/13004169/48324209-880e5d80-e638-11e8-987d-c690b0c0018d.png)

@DualMatrix Hopefully, not pestering you with these.  Might this be another rounding error?  Or some failure around how/when the looping animation logic may try to interpolate between last and first keyframes?

**Comment by DualMatrix** [comment]
If I print the current_animation_position at the start of the dying animation then it prints the ending position (0.3) as of the second time the dying animation is run. Not sure what to make of that.

**Comment by avencherus** [comment]
Thanks for taking a look at it.  Can that be seen from GDScript?  At least for me at the point of signals and in either processing loop, the time says 0, but the value is one that would be seen at 0.3 (the end of the animation).

I tried moving the keyframe to .3 to see if maybe that had some effect.  The thought being that the loop interpolation code may of been bleeding into non-looping animations.  But no difference in result.  

One odd thing that sort of worked was that if I did a seek(0.1) after play(), it smoothed it out somewhat.  Some values between 0.04 and 0.10 reduced the flickering frame.

I don't know much about it, but curious what the timing of the signals might be in relation to the processing loops.  Maybe not enough things are being set before hand.

It does seem like play() in some conditions is jumping to the end of the timeline for perhaps a single frame of rendering.

**Comment by DualMatrix** [comment]
Yeah that can be seen from GDscript, and yeah I suspect thats whats happening with play.

**Comment by avencherus** [comment]
I can smooth it out with two yields to idle_frame before hiding the old and showing the new.

Though its not a viable workaround, maybe it gives a clue into the timing.

![image](https://user-images.githubusercontent.com/13004169/48458833-9b543100-e7d0-11e8-8deb-053319562f20.png)

**Comment by DualMatrix** [comment]
Allright I did some research and I think this isn't a bug exactly, here's what I think happens:

1. Your dying animation plays the first time, the frame of that sprite ends in 8
2. The second Hurt animation finishes, you start the dying animation again and make that sprite visible.
3. The Dying animation was started but has not yet processed, so the sprite frame is still 8, so when you make that sprite visible again it will flash frame 8 for one frame until the animation processes.

The flicker dissapears when I set the frame of the sprite manually to 0 when it's made visible again.

**Comment by avencherus** [comment]
Firstly, thanks again for taking time to research this.  X)

Very odd finding though.  Does this also mean that depending where you call `play()` in the tree, that it might take effect immediately or behave like a deferred call?

I'm trying to think of a way to test that.

Your work-around is much safer, but has the downside that our mere prototype character has 30+ animations with several to a dozen keyframes each.  The final versions are expected to be more complex.

This means in these types of situations I either have to maintain hundreds of lines of code that initialize every track, vigilantly updating them when names or values change.  

Or, slightly more preferred, scan through all the tracks and search for the first keyframes and apply their values.  I imagine that to be rewriting some part of what the play() function is doing, but for one frame upfront.

Unfortunately, I can't use `seek(0.0)` to do this, because of the problem I had encountered a few days ago:

> One odd thing that sort of worked was that if I did a seek(0.1) after play(), it smoothed it out somewhat. Some values between 0.04 and 0.10 reduced the flickering frame.

So something like `seek(0.1)` prevents the flicker, but chops the animation, and `seek(0.0)` to `seek(0.04)` still flickers.

Is there anything that can be done?  I would believe it to be generally more desirable if play() and seek() took some initial action for certain things rather than waiting for processing.

**Comment by akien-mga** [comment]
Still seems reproducible with the provided project in the current master branch.

**Comment by tom-jk** [comment]
You can workaround this quite effectively with either advance or seek(update=true), eg.

```gdscript
anims[DYING].play("action")
anims[DYING].advance(0)
```
or
```gdscript
anims[DYING].play("action")
anims[DYING].seek(0, true)
```

I think this shouldn't require any per-anim micromanagement; you could probably wrap all your play calls in a play+advance(0) function.

**Comment by KoBeWi** [comment]
This is basically #29187
You play the animation and set sprite visibility at the same time, but the actual animation starts a bit later. Not sure why use such a weird setup for animations, but you can just move showing the sprite to the animation instead of doing it from script.
