### ISSUE TITLE
Crash on project load when trying to load a shape that wasn't set yet

### ISSUE THREAD

**Issue by gra-frogger** [godotengine/godot#2366]
this is output when i have launched godot engine with terminal, system is linux manjaro 64bit:

```
VBoxContainer: 144,108
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:479.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:479.
bind toptions
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:479.
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:296.
```

**Comment by gra-frogger** [comment]
I have used dev version of godot of 4-5 days ago, and I have try with 1.1 and this is output

: /usr/lib/libssl.so.1.0.0: no version information available
: /usr/lib/libcrypto.so.1.0.0: no version information available
freed code id 1

**Comment by MartiniMoe** [comment]
Im having the same issue.
When starting from command line with "godot -e -path my/project/" it starts, but doesnt open any scene. When I open my main scene it crashes with "ERROR: set_current_tab: Index p_current out of size (get_tab_count())."

**Comment by vnen** [comment]
I can tell that both crashes occur in the same line ([link to line with diff](https://github.com/okamstudio/godot/commit/83d9a692be648668b5b363f2424c619e15639843#diff-ee4de0f102ea0c69de5b6535d93973baR120)). It's related with the new update that allow collisions being visible during the game.

**Comment by AlexHolly** [comment]
+1 crash on creating a new CollisionShape2D - master branch

**Comment by akien-mga** [comment]
Can you still reproduce it with the current master branch?

**Comment by AlexHolly** [comment]
CollisionShape2D - looks fixed

Output still there.
ERROR: get_edited_scene_root: Index current_edited_scene out of size (edited_scene.size()).
   At: tools/editor/editor_data.cpp:500.
ERROR: set_current_tab: Index p_current out of size (get_tab_count()).
   At: scene/gui/tabs.cpp:500.

**Comment by akien-mga** [comment]
Thanks. So you get the error output, but no crash? I guess I'll fork this into a new issue then, maybe the initially reported crash did come from the CollisionShape2D issue, and has nothing to do with the error message.

**Comment by akien-mga** [comment]
@AlexHolly Can you open a new issue specifically for this ```set_current_tab``` error message? The first error message is a known issue (#2731). Also please add details about your environment, exact Godot version (nightly build date or commit), how you start Godot and when the error appears, etc., since I can't seem to reproduce the issue.

**Comment by vnen** [comment]
@godotengine/bugsquad: This issue was hijacked by the CollisionShape2D bug that happened afterwards, since the error messages in the console are the same, even though they're not related to the bug. The original issue was about scaled models and it was open before the collision debugging was added and hence before the CollisonShape2D bug was introduced. So we should check if the original issue (about scaled models) is still valid and open another ticket for it.
