### ISSUE TITLE
Simple thread instance in GDScript

### ISSUE THREAD

**Issue by schweigert** [godotengine/godot#23686]
Many languages have a reserved word to start asynchronous code snippets. It would be a good idea to have this word in gdScript.

```gdscript
func _ready():
    var thread = spawn my_method(1, 2, 3)
    # This is the same of Thread.new(....)
    var no_thread = my_method(1, 2, 3)

func my_method(a, b, c):
    # do work
    pass
```

@OvermindDL1 suggest `spawn` word.

This issue is a suggestion to resolve #9924.

**Comment by OvermindDL1** [comment]
A new thread is parallelism, not asynchronousness (which is more of what coroutines are).

**Comment by OvermindDL1** [comment]
`spawn` or something would be more accurate, not `async` as that is an entirely different concept.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
