### ISSUE TITLE
Errors after creating new scene via New Resource

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23705]
**Godot version:**
3.1 37c5aa1

**OS/device including version:**
Windows 10 

**Issue description:**
When I trying to add new scene via new resource, when I created it and trying to open, this error occurs:
``` 
ERROR: open: res://new_packedscene.tscn:3 - Parse Error: Unexpected end of file
   At: scene/resources/scene_format_text.cpp:884
ERROR: load: Condition ' err != OK ' is true. returned: RES()
   At: core/io/resource_loader.cpp:155
ERROR: Failed loading resource: res://new_packedscene.tscn
   At: core/io/resource_loader.cpp:192
ERROR: remove_scene: Index p_idx=1 out of size (edited_scene.size()=1)
   At: editor/editor_data.cpp:564 
```
and popup with this info:
> Alert! Unexpected end of file 'new_packedscene.tscn'

Only one line appear in this file:
> [gd_scene format=2]

**Steps to reproduce:**
https://streamable.com/0uxvr

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

**Comment by mohd874** [comment]
I faced the same bug, but found a workaround to make it work again:

### To reproduce:
1- Follow the steps in @qarmin video above
2- Open the new created scene in a text editor
3- Add the following at the end of the file:
```
[node name="PackedScene1" type="Node2D"]
```
so the full file will look like:

```
[gd_scene format=2]

[node name="PackedScene1" type="Node2D"]
```
4- You should be able to open the scene in Godot now.

I hope this bug is fixed soon.

**Comment by mmxcrono** [comment]
@mohd874 I confirmed this to fix my new scene!
