### ISSUE TITLE
Add support for GDScript Option type/syntax

### ISSUE THREAD

**Issue by gokudomatic** [godotengine/godot#23719]
I would like to suggest a feature that exists in a few modern programming languages and which I think could be very useful. It's a safe navigation operator paradigm where you manipulate an object without having to worry if it's null and that would throws an unwanted null pointer exception. The typical use case is a chain getter calls, like objectA.getObjectB().getObjectC().get... and the wanted result is either the value when all those objects exist or a default value.
Instead of implementing a check for each getter to ensure that the object returned by the previous getter is not null, which would look like:
```
if objectA!=Null and objectA.getObjectB()!=Null and objectA.getObjectB().getObjectC()!=null and ...:
    return objectA.getObjectB().getObjectC().get...
else:
    return defaultValue
```
And even more verbose when there are arrays, instead, it would be much safer, shorter and more convenient to write something like this:
```
return objectA?.getObjectB()?.getObjectC()?.get... ?: defaultValue
```
Instead of throwing an exception for a very special case you didn't foresee in your code, the nullable object could simply return a default value when not found. That would allow to reduce greatly the amount of checks that a variable or result of a method is not null.

I know that in Java it's the class Optional that does such feature, using map to call safely the function. I heard that C# implemented it long ago in a nice way. And groovy and kotlin integrated it also with ?. Either way (with ? ?: operator or a wrapper class like Optional with map()) are fine for me.

**Comment by bojidar-bg** [comment]
Related to #7223

**Comment by gokudomatic** [comment]
bojidar-bg, so far I understand null-coalescing operator it's only a shortcut for if x!=Null then x else something. But here it's not x, it's a chain of multiple method calls which some of them could return null and then throw a null pointer exception (invalid index attribute in 'Nil' in Godot terms). The null-coalescing operator would help with that.

**Comment by bojidar-bg** [comment]
I just linked the other issue, since they are both about null-handling and operators. They are not about the same thing, just about similar things.

**Comment by GammaGames** [comment]
I think this would be a useful feature, here's some more examples in other languages:

* [c++](https://en.cppreference.com/w/cpp/utility/optional)
* [swift](https://developer.apple.com/documentation/swift/optional)
* [C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/nullable-types/)

**Comment by Spartan322** [comment]
Having a nullable shorthand is really necessary since when you implement a specific manner of null into the language especially when it can throw exceptions for accessibility. If Godot plans to implement something akin to Dart's type soundness, it be beneficial to as well to have an Optional or Nullable token.

**Comment by bojidar-bg** [comment]
Related to #27261 as well, consider discussing nullable types there.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by bojidar-bg** [comment]
Proposal already exists as https://github.com/godotengine/godot-proposals/issues/162.
