### ISSUE TITLE
Navigation polygon calculating path to local coordinates instead global

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23717]
**Godot version:**
3.1 66c6dfb

**OS/device including version:**
Windows 10

**Issue description:**
When I move a parent of NavigationPolygon and then run game, then I see that Navigation polygon is drawn in right place, but when I move player, then I see that it ignore parents position and calculating path to it local position instead global.

**Steps to reproduce:**
https://streamable.com/vor2u

**Comment by kubecz3k** [comment]
According to docs, the calculation is made in local coord space by design, so it's user responsibility to translate them to global if they need this for their game. https://docs.godotengine.org/en/3.0/classes/class_navigation.html
Hope this helps, if you think there should be additional api to calculate paths in global coords feel free to open a new issue.
