### ISSUE TITLE
Use different texture resolutions

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#23739]
In continuation of the question https://godotengine.org/qa/35751/how-do-i-use-different-texture-resolutions, I want to offer a new opportunity.

Loading textures or materials in scripts is a bad way. I think I have a good idea how to automate this.

1. Create a global variable that defines the level of texture resolution;
2. Create a new" intermediate " Godot resource, where you can create levels in the form of a list and bind a texture to each level;
3. Add support for a new intermediate resource (point 2) to the material and realize an algorithm for the material to check the global variable (point 1) and load only the specified level texture.

This will automate the support of textures of different resolutions in the game.It is enough to load textures of different resolution levels into the project + add to the game settings, switching one global variable. Textures strongly affect memory and performance. I think this is a very useful function.

**Comment by CptPotato** [comment]
Another approach I could imagine is giving each texture (or mesh) a number representing it's texture detail level. This can be compared against a global reference value (= the quality setting) deciding which resolution to load.
For example if a cube has a texture "detail value" of 2 and the quality setting is set to 1 you would load the texture that is 1/2 of the original one. If you set the quality to 0.5 you would go for 1/4, etc.

This could also be used for advanced things like texture streaming: The visible detail of an object is proportional to 1/distance - which can be used to determine which texture level should be loaded.

**Comment by Calinou** [comment]
@CptPotato Sounds good to me, but there should also be a way to make the global quality factor ignore some textures (such as GUI elements).

**Comment by DimitriyPS** [comment]
No, I'm not talking about changing the texture when exporting! I'm talking about switching the textures in the exported game!

**Comment by CptPotato** [comment]
> No, I'm not talking about changing the texture when exporting! I'm talking about switching the textures in the exported game!
Yes, that's what I meant, sorry if I was a bit unclear.

> Mesh and so have LOD.
That's not quite what I was referring to. I thought about a ***texture*** detail that you can either define on a per-texture or per-mesh basis.

> This makes MIP-MAP filtering. Right?
Kind of, mip maps are lower resolution versions of a texture so they're also handy for this task (no need to create extra textures). Though, what I meant is: if an object is far away (or very small on the screen) you can get away with lower resolution textures - so *if texture streaming is implemented* you could only load the smaller mip levels, saving texture memory. If you get closer you can stream the higher resolution versions.

**Comment by DimitriyPS** [comment]
> Kind of, mip maps are lower resolution versions of a texture so they're also handy for this task (no need to create extra textures). Though, what I meant is: if an object is far away (or very small on the screen) you can get away with lower resolution textures - so if texture streaming is implemented you could only load the smaller mip levels, saving texture memory. If you get closer you can stream the higher resolution versions.

This will allow you to control the maximum size of the loaded texture? Will allow to avoid loading in memory of the big initial texture (will allow not to occupy memory)?

I'm not really that tech savvy aspects. Perhaps this is why I do not quite understand the essence of your proposal. I just want the finished game to be able to be adapted to relatively weak PCs without re-exporting. What would the user can go to the game settings and switch textures 512/1024/2048, etc.and thus significantly reduced the requirement of the game on video memory and render.

**Comment by CptPotato** [comment]
> This will allow you to control the maximum size of the loaded texture? Will allow to avoid loading in memory of the big initial texture (will allow not to occupy memory)?

What I said about the texture streaming method is more of a "would be nice to have"-thing, rather than a suggestion for the next steps towars implementing texture quality settings.

A very basic implementation for the first shot could be a simple scale factor (or mip level factor) without any of the special weighting I've described above. You can decrease the size of *all* textures by 2x, 4x, 8x etc. And of course the large textures should not be moved to the video memory when only the smaller ones are being used.

But as Calinou said, it's important that you can manually exclude/include specific textures from this process to prevent things like UI elements from getting low res and blurry.

**Comment by Zylann** [comment]
One problem with UI and sprites though is that the size of some elements is determined by texture size, so you can't only swap by a lower-res texture, you have to somehow remember which size it should have and stretch it.

**Comment by DimitriyPS** [comment]
Perhaps I do not understand the essence of the proposed implementation...

But I wrote only about the simple forced control textures for 3D objects. It would be great to have a simple, transparent way to choose the texture size.

**Comment by triverske** [comment]
It would be nice if you could set up quality levels similar to unity. As mentioned above some textures shouldn't be scaled and others you might want to scale more/less depending on the asset.

**Comment by Calinou** [comment]
Shrinking all textures when the project loads is already possible, as explained in the [Multiple resolutions](https://docs.godotengine.org/en/latest/tutorials/viewports/multiple_resolutions.html#reducing-aliasing-on-downsampling) tutorial. However, this will apply to everything including 2D/GUI elements, which may be undesirable.

**Comment by Frontrider** [comment]
Can I use the `texture_set_size_override` method on the virtual server to achieve this effect?

**Comment by dioptryk** [comment]
There's a pretty good way of implementing this right now, actually. You simply need to make a patch (pck or zip) including low-res textures (or hires, depending on which do you want the default to be). **These textures must be named exactly the same and their resource paths also must be exactly the same as the originals.**

Now, and this is important, **before any scene loads (!)** (so using an Autoload node may be necessary), you must load the resource pack like so:

```
var pack = File.new()
if pack.file_exists("res://Test1Patch.zip"):
    ProjectSettings.load_resource_pack("res://Test1Patch.zip")
```

As documentation says, the resources in the pack will override those in the main resource file. I just tested this and it works. The only inconvenience is you'll probably need to keep a second project that contains only textures in duplicated paths.

This should work for everything, like models etc. You can also have multiple texture resolution packs this way.

**Comment by Calinou** [comment]
@dioptryk Thanks for the tip :slightly_smiling_face: 

Nonetheless, this should be remade as a proposal since this issue tracker is now used for bug reports only.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
