### ISSUE TITLE
More options for customizing the VisualServer black bars.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#23730]
**Godot version:**
All versions.

**Issue description:**
My suggestion is for more features for the VisualServer black bars. Right now the only thing that can be set is a texture, and it has to be set through code.

* There should be an option to set the texture as tiling so that it properly tiles across all the margins instead of stretching to fill.
* There should be an option to set the color, so that it isn't necessary to create a solid color texture just to change the black bar color.
* All of these options should be able to be set in the project settings, so that you don't have to create a script just to set these one time.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
