### ISSUE TITLE
"export minimal" for resource variables

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23741]
**Issue description:**
A while back I posted a topic on the clutter that could be exporting an array of Resources...
When editing a given resource in the inspector there is a "Resource" category (Local to Scene, Path...) that can (and does) cause clutter. It would be great if we could have a way to create minimal exports in order to hide parts of the data shown in the inspector.

Right now _get_property_list() allows to edit somethings but can only add to the list instead of removing from the pre-existing one.

1) we could have a _get_property_list(dictionary) that would have a pre filled dictionary allowing to remove unwanted entries.

My concern is that _get_property_list might be used for something else other then inspector export... so messing with it (removing entries) would make something in the game break. If that is the case we could have an inspector dedicated virtual functions

2) _get_inspector_property_list(dictionary) this would make it possible to remove entries without breaking other parts of the engine.

Another practical example would be:

What if I need to export an automatically managed array, the array size depends for example on the number of tiles in a TileSet so array "size" property should be hidden from the inspector in order to prevent manual changes... or the same idea but for dictionaries. I don't know what would be the best way to make this work but it would be open to discussion to get to the best implementation possible.

**Comment by bojidar-bg** [comment]
In 3.1 this is already better since categories are closed by default:
![image](https://user-images.githubusercontent.com/5276727/48640321-02473500-e9df-11e8-98d3-945a81ef40f4.png)

**Comment by xDGameStudios** [comment]
> In 3.1 this is already better since categories are closed by default:
> ![image](https://user-images.githubusercontent.com/5276727/48640321-02473500-e9df-11e8-98d3-945a81ef40f4.png)

When inside of an array custom resources don't have a collapsable resource category (at least in the version I'm using... which is d16ce4a)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
