### ISSUE TITLE
When inside array categories cannot be collapsed!

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23759]
**Godot version:**
v3.1.alpha.calinou.37c5aa1

**OS/device including version:**
OSX Mojave

**Issue description:**
When using an array of resources, categories cannot be collapsed.

<img width="383" alt="captura de ecra 2018-11-16 as 23 15 02" src="https://user-images.githubusercontent.com/10358443/48652044-81dffe80-e9f5-11e8-8f62-989f7886c82c.png">

**Steps to reproduce:**
Create an array, set item type to "Object", create a new resource (ParticleMaterial, for example)

**Comment by KoBeWi** [comment]
Still valid in 481151b

**Comment by nathanfranke** [comment]
Since https://github.com/godotengine/godot-proposals/issues/1873 I'm going to add a minor problem, which is that sub-resources are noticably hard to distinguish between/within other sub-resources.

![image](https://user-images.githubusercontent.com/14253836/102012309-4668a900-3d0f-11eb-9ceb-fb3acc48e677.png)

Here is a ShaderMaterial with a Shader selected. Pretty much the only reliable way to distinguish between the first and second "Local To Scene" is their vertical position.

**Comment by Calinou** [comment]
@nathanfranke I'm not sure what could be a good way to solve this issue. Adding more indentation is problematic as most of the time, your inspector dock will be pretty narrow.

**Comment by nathanfranke** [comment]
Call me crazy but what about different colors? I don't think RGB would suit Godot but we can have contrasting shades of the editor color

**Comment by Calinou** [comment]
> Call me crazy but what about different colors? I don't think RGB would suit Godot but we can have contrasting shades of the editor color

I remember this being in place at some point, not sure if it disappeared or was never implemented in the first place.

**Comment by Flavelius** [comment]
I just wanted to mention it here because my issues was closed even though it was only partially related:
The 'script' property is also not showing for nested resources, and this is still an issue in 3.2.4.rc4.

**Comment by fire-forge** [comment]
This is still an issue in v3.5.beta5.official [815f7fe63]. This is a huge usability problem when using resources with lots of properties:

![image](https://user-images.githubusercontent.com/67974470/171279882-30a8ca51-68d9-4f99-9dfd-8cca391fe091.png)
