### ISSUE TITLE
WebGPU support

### ISSUE THREAD

**Issue by Type1J** [godotengine/godot#23764]
This may be long term  but eventually, we will probably want to drop WebGL support in favor of WebGPU support: https://youtu.be/CCRI4TY1v08

**Comment by MickeMakaron** [comment]
It is possible to get started on this in a native development environment using [Dawn](https://dawn.googlesource.com/dawn).

Could perhaps be worked into a RenderingDevice just like the Vulkan renderer.

**Comment by Type1J** [comment]
wgpu's C API may be a good target as well.

**Comment by dkaste** [comment]
Mozilla's WGPU can be found [here](https://hg.mozilla.org/mozilla-central/file/tip/gfx/wgpu) or [here](https://github.com/gfx-rs/wgpu).

Considering they both aim to implement a standard, the functionality provided by Dawn and WGPU is very similar. However, WGPU appears to support DirectX 11 as well as 12, which could be a nice bonus.

**Comment by tangmi** [comment]
Also worth noting that many folks are hard at work on defining and implementing WGSL, which the cross-platform (yes, even Apple!) shading language WebGPU will adopt: https://gpuweb.github.io/gpuweb/wgsl.html

**Comment by clayjohn** [comment]
We definitely hope to add WebGPU support when it is ready. So you dont need to bother opening a new proposal.

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by kelteseth** [comment]
WebGPU is now stable and enabled on default as of Chromium 113 https://developer.chrome.com/blog/webgpu-release/

**Comment by kelteseth** [comment]
See https://github.com/godotengine/godot-proposals/issues/6646
