### ISSUE TITLE
Change current of AnimationNodeTransition scale up then down during xfade time

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#23810]
**Godot version:**
3.1 alpha2 (https://downloads.tuxfamily.org/godotengine/3.1/alpha2/)

**Issue description:**
Change current of AnimationNodeTransition scale up then down during xfade time, see the gif attached.

**Steps to reproduce:**
Model and animation download from Mixamo
Animation is tweaked
Add AnimationTree and new blend tree
Add 2 animation and transition node
Change current of transition node

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/2593124/Project.zip)

![1](https://user-images.githubusercontent.com/28286958/48676960-15a5fc00-eba9-11e8-8e77-f08496ff78a5.gif)

**Comment by IchiroKeisuke** [comment]
![what](https://user-images.githubusercontent.com/13280568/50398445-45fb3000-073d-11e9-8a50-f524172bcce0.gif)

I'm also seeing this in the latest 3.1 (a4) snapshot

**Comment by pipepkr** [comment]
I have the same problem, apparently it happens when mixing animations that have the scale as a parameter, it's very easy to replicate.

https://www.youtube.com/watch?v=aT_8AysFpIE

**Comment by antoniotorresm** [comment]
I'm not able to replicate @pipepkr example on Godot 3.1.1, but I'm experiencing this same issue in my game with 3D models in DAE format, and with anims that don't change the scale property at all... maybe the DAE exporter/importer has something to do?

**Comment by uuuuuup** [comment]
I have same issue. So I tested as below. 
Then, the problem was disappeared.
I do not think this is solution.

--- a/scene/animation/animation_tree.cpp
+++ b/scene/animation/animation_tree.cpp
@@ -952,10 +952,10 @@ void AnimationTree::_process_graph(float p_delta) {
                                                                t->loc = loc;
                                                                t->rot = rot;
                                                                t->rot_blend_accum = 0;
-                                                               t->scale = Vector3();
+                                                               t->scale = scale; // Vector3();
                                                        }
 
-                                                       scale -= Vector3(1.0, 1.0, 1.0); //helps make it work properly with Add nodes
+                                                       //scale -= Vector3(1.0, 1.0, 1.0); //helps make it work properly with Add nodes
 
                                                        if (err != OK)
                                                                continue;
@@ -1241,7 +1241,7 @@ void AnimationTree::_process_graph(float p_delta) {
                                        Transform xform;
                                        xform.origin = t->loc;
 
-                                       t->scale += Vector3(1.0, 1.0, 1.0); //helps make it work properly with Add nodes and root motion
+                                       //t->scale += Vector3(1.0, 1.0, 1.0); //helps make it work properly with Add nodes and root motion
 
                                        xform.basis.set_quat_scale(t->rot, t->scale);

**Comment by akien-mga** [comment]
Seems fixed in the current master branch (at least the project in OP).
