### ISSUE TITLE
Mono: Godot.File.StoreString and File.StoreVar doesn't properly store UTF8 strings

### ISSUE THREAD

**Issue by exts** [godotengine/godot#23836]
**Godot version:**
All

Honestly the file class has a ton of weird issues that needs someone to double check that it's properly working.

**Description**
When downloading an image from the web using something like:

```csharp
using(var client = new ApiWebClient())
{
    client.Encoding = Encoding.UTF8;
    client.Headers.Add("user-agent", "Mozilla/5.0 (Windows NT 6.2; WOW64)   AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11 AlexaToolbar/alxg-3.1");
    var uri = new Uri(card.Image);
    var data = await client.DownloadDataTaskAsync(uri);
    // ... redacted ...
}
```

Then attempting to save the byte[] using File.Store or converting the data like so:

```csharp
file.StoreString(Encoding.UTF8.GetString(imageData));
```
It'll attempt to save the data, but it's an invalid image.

So I tested to make sure it's a godot issue and replaced my download data task (i also tested downloadstring as well) with:

```csharp
await client.DownloadFileTaskAsync(uri, card.SavePath());
```

And it downloaded to my project directory without an issue. Where `card.SavePath()` is now `cache/[ID].png` instead of `user://cache/[ID].png`

This seems like a bug with File and not C#.

**Comment by exts** [comment]
Sorry for the delay, here's a basic reproduction of the issue. Simply run the application and I've setup different exampels of `File.StoreString`, `FileStoreVar` and the working exampling using `DownloadFileTaskAsync`
[DebugImageDL.zip](https://github.com/godotengine/godot/files/2599020/DebugImageDL.zip)

**Comment by bojidar-bg** [comment]
MS's docs about [Encoding.UTF8](https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.utf8?view=netframework-4.7.2) state a few gotchas about it:
* `Encoding.UTF8` always writes a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) at the beginning of the file (a U+FFEF character)
* `Encoding.UTF8` will not throw errors for invalid UTF-8 sequences of bytes, but will replace them with a `?` character.

Try using `File::StoreBuffer()` directly, instead of passing it through a string.

**Comment by exts** [comment]
Wow, I didn't even know `StoreBuffer` was a method after looking for it yesterday. I think I was looking for `StoreByte` or something. Thanks for that. Worked.
