### ISSUE TITLE
Image preview should have ability to resize itself vertically

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#23872]
**Godot version:**
3.1 f2cc969

**OS/device including version:**
Windows 10

**Issue description:**
When I click at the image in File system dock, then in inspector is shown this image preview. I can resize this preview horizontally but not vertically, so I can't see more details in image.

![afafasfasfasfasfasfasfasfasfasfasfasfasfasfasfsaf](https://user-images.githubusercontent.com/41945903/48836889-3b3b2d00-ed84-11e8-94c0-3f39c115d646.png)

**Comment by Calinou** [comment]
Since the image always has to be displayed in full in that preview, it doesn't make sense to be able to resize the image preview vertically. (Otherwise, the dock would have to expand/shrink automatically to account for this, and it'd feel strange.)

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
