### ISSUE TITLE
Hiding categories from inspector via EditorInspectorPlugin

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#23891]
**Godot version:**

**OS/device including version:**
Mac OSX Mojave

**Issue description:**
Even though it is possible to hide properties from the inspector (even builtin ones), using the "EditorInspectorPlugin"

```
extends EditorInspectorPlugin

func can_handle(object):
	if object is Attribute:
		return true;

func parse_property(object, type, path, hint, hint_text, usage):
	match path:
		'resource_local_to_scene':
			return true;
		'resource_path':
			return true;
		'resource_name':
			return true;
		'script':
			return true;
```

the resource category still gets drawn to the inspector is there a way to intersect the inspector draw and avoid drawing the category?! the parse_property function has a bool return that allows that but the category_parse doesn't!! Shouldn't it have that functionality?!
I was trying to remove the "Resource" category from resources while using them in arrays to avoid clutter!

**Comment by stickgrinder** [comment]
This is still open to date. I'm fighting to get this properly with a category I define in custom nodes in my plugin.

Is there another solution that I'm not seeing to hide groups and categories from EditorInspectorPlugin - or another Editor class?

**Comment by YuriSizov** [comment]
Categories were not designed to be conditionally hidden like that. Semantically, categories are designed to represent the class hierarchy, so hiding them doesn't make sense. That said, both categories and groups should get hidden if all of their properties are hidden, since they have no content to display.

**Comment by stickgrinder** [comment]
@YuriSizov the problem to me is that programmatically hiding the property with `_parse_property()` doesn't hide the category, so I end up with an empty category. I took that's a desired behavior for granted, but from what you say, the right path may be fixing this so that if a category has no visible property, it's also hidden.

**Comment by YuriSizov** [comment]
@stickgrinder Hiding properties with `_parse_property()` is not an expected use case for this method. Properties are normally hidden by the class' script itself, using `_validate_property()` and `_get_property_list()`. Just removing or hiding the control from within `_parse_property()` will not lead to the category or the group being hidden as well, we don't handle that.

**Comment by KoBeWi** [comment]
You can now hide properties using `_validate_property()`, which should be working as expected.
