### ISSUE TITLE
ragdoll with AnimationTree

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#23916]
**Godot version:**
`a16d9c6`

**OS/device including version:**
Windows 7

**Issue description:**
I have a `KinematicBody` which animations controled by `AnimationTree` and do the `Create physical bones` for the skeleton.

I found that if I call `physical_bones_start_simulation()` with the animation driven by `AnimationTree`, the ragdoll result is weird. 

**Steps to reproduce:**
-Import a animated dae as `KinematicBody`
-make  `Create physical bones` in skeleton
-make `AnimationTree` and set it active
-run the game and call `physical_bones_start_simulation()` 

you will see the ragdoll system not quite work.

**Comment by slapin** [comment]
I confirm this (was just fighting this yesterday). I just deactivate AnimationTree before ragdoll transition. Not really nice, but you can calculate velocities for your bones and set them just before ragdoll transition and AnimationTree deactivation. Otherwise I agree this should not be like this, at least some helpers have to exist. Some way to blend animation into ragdoll is needed.

**Comment by slapin** [comment]
As I guess there is no code blending animation and ragdoll and
animation directly affects bones. So normally you would request such
feature or implement it and send PR.
Otherwise you can hack-up blending code in GDScript, which might even
work, but performance won't be good.
The approach would be to have 2 independent hidden characters, one
"playing" ragdoll, another playing animation and code blends that to
actually visible one
(free unity-style approach frequently seen on youtube). Looks ugly as
hell but can be used as excuse to not implement this feature (unless
some developers are interested).
Actually as current Godot ragdoll and IK system does not scale to real
characters at all, I'd prefer to use animations instead. The animation
system is powerful enough to replace IK and mimic some ragdoll
behavior. Also you can use physics bones for things like hair, so as
long as it is not full body ragdoll you are good. This way you will
not need to do nightmarish slow setups and still make things work.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
