### ISSUE TITLE
Tilemap corner collision bug

### ISSUE THREAD

**Issue by Jackain** [godotengine/godot#24003]
**Godot version:**
Godot 3.1 Alpha 2

**OS/device including version:**
Windows 10 x64 1803

**Issue description:**
I've created an Autotile with the editor, and a map in a test scene with a player KinematicBody2D
When the play approach a corner on the TileMap, it has a weird behavior, it can not go in the corner and it get snap en the edges (see GIF
![bug03](https://user-images.githubusercontent.com/20475653/49053348-a29e1600-f1a4-11e8-8739-ec17591fdc95.gif)
![bug01](https://user-images.githubusercontent.com/20475653/49053350-a5990680-f1a4-11e8-8f3e-63385700373a.png)

)

**Steps to reproduce:**
Open and play.

**Minimal reproduction project:**

[tilemap_bug.zip](https://github.com/godotengine/godot/files/2617994/tilemap_bug.zip)

**Comment by eon-s** [comment]
The problem here seems that the tileset editor allows to create a concave shape with a convex shape editor.
Apart from that, concave shapes have issues with tilemaps, see #5745

**Comment by Jackain** [comment]
Ok thanks.
So there is nothing I can do for now?

**Comment by CptPotato** [comment]
Shouldn't you be able to just use a `ConcavePolygonShape2D`?

**Comment by eon-s** [comment]
The classic way of making tilesetss used PolygonShape2D, that shape divides the figure into many convex shapes.
I do not know if the new editor allows to use that shape, in my few attempts to modify the tileset only got engine crashes.

**Comment by Jackain** [comment]
Yes i had some crashes too but I don't know how to reproduce them

**Comment by Jackain** [comment]
So how could i modify this convex into concave? 
Autotile is broken for now? Or is there any way to modify this?

**Comment by eon-s** [comment]
The new editor does not give options to make other than convex shapes that allow concave figures...
I do not know how to solve it as it is now, you can try making your tiles in the size of the smallest convex shape (in your case, half the current size).

Maybe @MarianoGnu can help a bit more here.

**Comment by vinterskog** [comment]
Ran into the same issue yesterday and after hours of trying to get around it, I just retreated to Tiled for now which works great. Can't wait for this to get fixed though. Are there any news yet about a potential fix?

**Comment by Jackain** [comment]
It's in the 3.1 milestone :)

**Comment by AlmostBearded** [comment]
This bug basically makes autotiling unusable as it is unfortunately. Any further informations about this or maybe any leads on how it could be fixed?

**Comment by AlmostBearded** [comment]
I'm currently taking a look at the code. I see if I can figure something out and maybe switch the tile collision code to use CollisionPolygon2Ds instead of Shape2Ds. If you have input let me know. I'll keep you updated.

**Comment by AlmostBearded** [comment]
Ok i just spent a long time trying to figure this out but i'm having a hard time. to me it seems that replacing shapes with collisionpolygons was a pretty bad idea because that would require a lot of rewriting if im not wrong. 

It seems like tilesets can already have multiple collision shapes per tile but the tilemap editor can't properly set more than one shape.

I tried to figure out why that would be the case but the tilemap editor is a HUGE class with nearly no comments and the functions are just incredibly long and nested and so it's very hard for me to find the root of the problem. If someone with more insight into this class could take a look that would be amazing.

**Comment by AlmostBearded** [comment]
I implemented a fix for the issue above. The problem is that the close_shape method removes the currently edited collision shape from the collision shapes (line 2162) and if we don't reset the currently edited collision shape when creating a new one this will always delete the previously added shape.
I'm still working on a fix to make multiple shapes selectable in the tile set editor.

**Comment by akien-mga** [comment]
Fixes by #26330.

>  I'm still working on a fix to make multiple shapes selectable in the tile set editor.

Could you open a new bug report for this part?
