### ISSUE TITLE
Enhancements to signal definition

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24013]
**Godot version:**
custom 3.1 11d77386

**Enhancement 1**
It is currently possible to define a signal without specifying the signature of if (and by signature i mean the list of arguments)

```GDScript

signal some_signal
signal some_explicit_signal(param1, param2)

```

In my experience having an argument list for a signal makes the overall code more readable and less prone to errors.
I would also like to add that the signal is not fired properly if there is a mismatch with the arguments it is emitted with and the arguments that are expected by a function connected to it, but this is not reflected in the signal definition (no need to specify the number of parameters)

**Enhancement 2**

It is not possible to define types of the signal arguments, which would be nice for readability.

```GDScript

signal some_more_explicit_signal(param1: String, param2: Object) #<-- will not compile

```

**Comment by QbieShay** [comment]
@vnen

**Comment by vnen** [comment]
> It is currently possible to define a signal without specifying the signature of if (and by signature i mean the list of arguments)

AFAIK you are always specifying the number of arguments, just that in the empty case the number is 0.

> It is not possible to define types of the signal arguments, which would be nice for readability.

I've purposefully omitted for the sake of limiting the feature-set in this initial implementation. Adding types in signals means that there should type-checking somewhere, and I'm not sure how to deal with that yet. It's probably needed to do runtime-checks since it's not always possible to detect the functions connected to a signal.

I do plan to eventually tackle this though.

**Comment by QbieShay** [comment]
You can declare some_signal and then do emit_signal("some_signal", arg1, arg2) that will compile and work

**Comment by vnen** [comment]
Oh, this a problem with `emit_signal()` then.

**Comment by QbieShay** [comment]
@vnen I imagine this breaking tons of scripts if it gets fixed

**Comment by menip** [comment]
So should be left for 4.0?

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2557, as feature proposals are now tracked on the Godot proposals repository.
