### ISSUE TITLE
Ceil function with % and variable works inside editor and with debug build but not with release build

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24035]
**Godot version:**
3.1 b243c26

**OS/device including version:**
Windows 10

**Issue description:**
My project working inside editor and with debug build but not with release build.
Here is screenshoot with working project, exported with enabled debugging
![113](https://user-images.githubusercontent.com/41945903/49155569-8a043c00-f31b-11e8-96d0-1b7b19d1109e.png)

and here is screenshoot with project, exported without enabled debugging
![112](https://user-images.githubusercontent.com/41945903/49155554-82dd2e00-f31b-11e8-90a8-d410faf93089.png)

**Steps to reproduce:**
1. Just export minimal project with debug and without and open it

**Minimal reproduction project:**
[UP.zip](https://github.com/godotengine/godot/files/2624773/UP.zip)

**Comment by marcelofg55** [comment]
Your project will work if you attach your script to your `UP` node and replace this lines:
```
onready var number_of_pages_node : Label = get_node("Tlo/Dokument/OS/IloscStron")
onready var progress_node : TextureProgress = get_node("Tlo/Dokument/OS/CzasDoNastepnejListy")
onready var grid_node : GridContainer = get_node("Tlo/Dokument/SiatkaOfert")

```

**Comment by qarmin** [comment]
Seems that something is wrong with ceil function
This is minimal project([QQ.zip](https://github.com/godotengine/godot/files/2737976/QQ.zip)) or just as script:

1. Create Label with this script:
```
extends Label

func _process(delta : float) -> void:
	var number_of_pages : int = ceil(50)
	set_text(str(5 % number_of_pages))
	
	var newfile : File = File.new()
	newfile.open("/home/rafal/f",File.WRITE_READ) # change directory to correct before start script
	newfile.store_string(str(5 % number_of_pages)) 
```
2. Run script and you will see that "5" is print and in file is also written "5"
3. Export project as Release Build
4. Run project and you will see that "null" is printed and in file is written "7"

As workaround, this line can be change 
```
set_text(str(5 % number_of_pages))
```
to this:
```
set_text(str(5 % int(ceil(50)))
```

**Comment by qarmin** [comment]
Also changing line
```
var number_of_pages : int = ceil(50)
```
to this
```
var number_of_pages : int = int(ceil(50))
```
fix issue

**Comment by Zireael07** [comment]
QQ.zip from the second-to-last comment is too large? O_o

However, good job figuring out the problem!

**Comment by aaronfranke** [comment]
Is there any reason why `%` can't be made to work with floats? It seems backwards in a dynamically-typed language to make people worry about types. For example, `+` works with ints and floats.

**Comment by mnn** [comment]
> Not really, a dynamically-typed language can still be strongly-typed (as GDScript is).

Shouldn't a strongly typed language throw an exception/crash when such error occurs?

I might be wrong, but how is type-checking working in build (exported project) when type information is lost? What about dynamically loaded code? Or is type-checking supposed to be only available for a compilation-time, so allowing unsafe (from typing perspective) code execution at runtime? Wouldn't JIT benefit from keeping type info around?

**Comment by akien-mga** [comment]
Reopening as I reverted #26562.

**Comment by jahd2602** [comment]
I am in 3.1-stable under Linux and this still happens.

This is a huge issue that shouldn't be ignored because it causes bugs that are very hard to solve, especially for beginners coming from other engines. The fact that it only happens on Release, makes it even harder to debug. 

In our team, we spent the best part of a week trying to find a bug related to this issue, instead of implementing features for our game.

**Comment by bojidar-bg** [comment]
Discussing this on IRC, seems like the best solutions would be:
* Adding type information to release builds, as long as it does not cause the resulting binary to grow too much.
* Adding a mode to GDScriptCompiler in which it emits valid code even when type information is not available. That would mean assuming all engine functions are untyped.
  * If this causes too much of a performance impact, compiling GDScript to opcodes instead of just saving the source tokens should help.
