### ISSUE TITLE
Selecting recent node during Node creation selects wrong node

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#24044]
**Godot version:**
3.1 alpha 2

**Issue description:**
Not sure how this happened, but when I select Node from recent nodes, it selects InterpolatedCamera. Happens also when I mess with history and reorder recent nodes.

**Steps to reproduce:**
https://gfycat.com/CalmInformalIndochinahogdeer

**Comment by KellyThomas** [comment]
I was titling a new issue on this when github helpfully proposed this (open) and #6535 (closed) as potential duplicates. Instead of creating that duplicate I will paste my draft here.

**Godot version:**
v3.2.dev.mono.custom_build.d087a9e32

**OS/device including version:**
Windows 10

**Issue description:**

The Create New Node dialog's recent node list can be used to create a node of the wrong type.

**Steps to reproduce:**

1. Create new project
2. Create a root node of type `Particles`
3. Click the "Add Child Node" button
4. Double-click on `Particles` in the recent node types list.
5. Observe that a `CPUParticles` node has been added to the scene tree.

![image](https://user-images.githubusercontent.com/1151394/61388235-28b0cd80-a8ea-11e9-8e22-53787da6154f.png)

![image](https://user-images.githubusercontent.com/1151394/61386950-c2c34680-a8e7-11e9-9488-25c2cf03844a.png)

These steps are consistently repoducing this error on d087a9 but not on 3.1.1 so there may have been a regression since then.
