### ISSUE TITLE
AssetLib shows some files with corrupted icons

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#24070]
**Godot version:**
5b8dde4

**Issue description:**
When showing a downloaded package's contents, the AssetLib will show some files with corrupted icons, likely some error when generating their previews:
![screenshot at 2018-11-19 03-02-13](https://user-images.githubusercontent.com/30739239/49257886-8bbd2500-f42b-11e8-8aa7-8c2400bd4d81.png)

**Comment by duartencar** [comment]
Hello YeldhamDev, can you send me that package so I can check out what the issue is?

**Comment by bojidar-bg** [comment]
Seems like it is http://godotengine.org/asset-library/asset/260

**Comment by Kanabenki** [comment]
It seems that the assetlib importer does not generate preview for the files, it simply set an icon depending on the file type, but the icons it is trying to use don't exist (anymore).

https://github.com/godotengine/godot/blob/5bd0ff003fdd82cf84a557251633ebb83bad4fd5/editor/editor_asset_installer.cpp#L112-L128

**Comment by seandheffernan** [comment]
It is worth noting that due to commit 397b12727cf65a111717142efddb55fd751b1528, the error icon is now blank. 
At the time of the original commit of the asset installer (5dbf1809c6) by @reduz , the editor icons were created from pngs in the file system. While there was an icon_texture.png, there was no icon_material.png.
Furthermore, after the conversion to svg from png (c873661c307eb05dedf2ff07f3cf18e614ba72ec) by @djrm , icon_texture.png was removed but not replaced by an svg version.

Following these discoveries a couple questions arise:
1. Should we create icon_texture.svg and icon_material.svg? 
2. If so, what should the icons look like?
3. Would we need to create dark versions of said icons as well?
4. Given that the current behavior does not imply an error, do we need to even bother creating new icons or just leave it alone? The code would still be failing silently though...

(Tagging @akien-mga to be sure a maintainer sees this)
