### ISSUE TITLE
Make gridmaps support all 3D objects

### ISSUE THREAD

**Issue by Cobradabest** [godotengine/godot#24096]
I wanted to add 3D sprite trees onto a scene, and wanted to use a grid map, but found out that that only supports meshes.

It looks like a thing that would and should support all 3D objects, not just meshes.

Can you make something like this in the future?

**Comment by bojidar-bg** [comment]
Related: #9180

**Comment by packedstack** [comment]
+1.  Being able to use a "scene library" instead of a mesh library for gridmaps would be extremely useful.  Was trying to make some track segments for a racing game using Paths and CSGPolygons, but was unable to export them to a mesh to use in a gridmap.

Lamps with their own light source would be another example where this would be useful.  Collections of animated objects, like windy vegetation, hot stoves, slot machines.  Interactive objects.  Objects with particle effects.  The list goes on.

This would be an extremely useful feature that goes well with Godot's existing scene tree structure.  Basically, what it does now, except being able to lay it all out on a grid.  You can kind of do this now, but it's pretty painful to get heights just right, making sure you're using the right grid snap settings, rotation, and drag-dropping everything from the resource/FileSystem list.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
