### ISSUE TITLE
UI: TextEdit element "focus_exited()"signal not firing

### ISSUE THREAD

**Issue by mastermarkus** [godotengine/godot#24133]
Operating system or device, Godot version, GPU Model and driver (if graphics related):
Windows10 64bit
Godot version: 3.0.6

Issue description:

It's second time of submitting this #11744 issue but now for Godot Version: 3.0.6

PROBLEM:  When i try to use the focus_exited() signal under "LineEdit" or "TextEdit" control node it never seems to fire, but the focus_enter() works just fine. NB: I tried all focus modes (ALL, NONE, CLICK).

Steps to reproduce:
Click on "LineEdit" or "TextEdit" gui control and try to click away or press enter, it never looses focus and is stuck focused forever. NB: Changing Focus Mode between "All" and "Click" didn't change a thing.

Link to minimal example project:
[focus_exited_demo.zip](https://github.com/godotengine/godot/files/2639522/focus_exited_demo.zip)

**Comment by bojidar-bg** [comment]
Looking at `line_edit.cpp`, it should probably be made to not accept events which are of the `"ui_focus_next"` action. That way, tabbing out of the LineEdit will be possible.

Not sure about TextEdt, since needs to consume the Tab character when editing scripts. Maybe it should be optional?

**Comment by mastermarkus** [comment]
Yes i think feature like this should be feature by default  or optional at the very least. For example i'm trying to make Chat-bar which requires me to have way to tell if LineEdit/TextEdit focus was lost. I think it it would benefit a lot of people that try to make input boxes of any kind for their game, without having to do bound checks manually and keep GUI state in custom variables.

**Comment by KoBeWi** [comment]
I tried the MRP and this is expected behavior. You need another control to click to exit focus. Or implement it manually (e.g. unfocus when pressing Esc). All controls work this way, you can try with e.g. a button. If you want to unfocus when clicking away from control, you could try making a screen-sized flat button (clickable but invisible), so it steals focus when you click outside your TextEdit.

That said, this is not a bug. If you think the behavior should be changed, [open a proposal](https://github.com/godotengine/godot-proposals).
