### ISSUE TITLE
Audio effects killswitch / reset

### ISSUE THREAD

**Issue by matwhill** [godotengine/godot#24132]
When changing a scene etc. we generally don't want trailing audio effects (such as reverb) to carry over to the new environment.

I am able to fade effects down using mixer buses with volume attenuation, but I can't find a good way to clear the audio buffers whilst faded down. Turning the effect off-and-on-again doesn't work.

Currently in my game, long reverb tails can be heard during the following scene's fade-up.

Apologies if there is already a solution for this, I have been developing frameworks with both Godot and Unity for a while and never managed to crack this problem! Where necessary, I've ended up baking reverb into sounds, as they can be cleared and reset... obviously this is not a memory-optimal solution.

**Comment by Zylann** [comment]
Perhaps a workaround would be to remove the reverb from the effect chain?

**Comment by matwhill** [comment]
> Perhaps a workaround would be to remove the reverb from the effect chain using a script?

That's a good suggestion for many cases, but as the Audio Mixer's arrangement is effectively global state I wouldn't want to be manipulating it in that way.

**Comment by Zylann** [comment]
@matwhill I mean, if you still want that reverb after, you could add/remove it immediately at the same index? That would effectively reset the states.

**Comment by matwhill** [comment]
That's a good point! In my case I would be 'resetting' from a global manager anyway so it makes sense to create a DSP killswitch that way. I'll test this tonight!

I'm interested to see if anyone wants to implement this anyway. I don't really know what Godot's DSP code-base looks like but if this is trivial, having a mixer.clearBuffers() etc. might be worthwhile!

**Comment by matwhill** [comment]
Sorry the massive delay... can confirm that:
`# could be replaced in future, work-around suggested by: github.com/Zylann
func _kill_reverb():
	for bus in buses:
		var reverb = AudioServer.get_bus_effect(bus, 0)
		AudioServer.remove_bus_effect(bus, 0)
		AudioServer.add_bus_effect(bus, reverb, 0)`
...works fine :)

Gonna leave this open for now as some others seemed into the idea of clearing buffers manually? Feel free to close though!

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
