### ISSUE TITLE
Bug Parameter ' p_node ' is null. when working in bigger project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#24174]
**Godot version:**
3.1 89f8b84

**OS/device including version:**
Windows 10

**Issue description:**
When my project become bigger then I noticed that editor sometimes print this error:
```
ERROR: is_a_parent_of: Parameter ' p_node ' is null.
   At: scene/main/node.cpp:1404
```
every time when I click at some key at keyboard, but only until I click by mouse at editor.

It happens rarely, maybe 1-3 times per day.
Usually it happens in Script Editor, probably when it lost focus.

**Comment by qarmin** [comment]
This bug seems to not appear in empty project but in my project(which I can't attach here but maybe someone could reproduce this) it happens when I trying save with key combination CTRL + SHIFT + S and exit this window, then every single pressed key should show this error

 https://streamable.com/xjd8g

**Comment by Chaosus** [comment]
Yeah, it still sometimes happens(less than few moths ago, however), thank for report

**Comment by Dentrax** [comment]
@reduz 

**Version:** `3.1-rc1_x11.64`

Same issue when i start godot from the terminal and terminated with this command: `./Godot_v3.1-rc1_x11.64` after then, <kbd>CTRL+C</kbd>

**Comment by RobKohr** [comment]
I am getting it too:
``` scene/main/node.cpp:1432 - Parameter ' p_node ' is null.```

**Comment by Bumerang47** [comment]
+1
`scene/main/node.cpp:1418 - Parameter ' p_node ' is null`
**Godot version**: v3.2.beta1.official
**OS**: Mojave 10.14.6

**Comment by allkhor** [comment]
Same here, godot 3.2  096bf87
Error in output panel: scene/main/node.cpp:1430 - Parameter "p_node" is null.
Steps to reproduce:
1) Open any project.
2) Press **F3** to open Script Editor.
3) Press **F3** to open search panel.
4) Press **F5** or **F6** to run scene or project.
5) Press **F8** to stop game.
6) Press **F8** to get error.
Hotkey Fatality: **F3->F3->F6->F8->F8**

**Comment by pycbouh** [comment]
I can confirm, that there is a reliable way to reproduce the same issue in the latest 3.2 build, and it does not matter what size is your project. You can make a new one, save the scene (because you need to run it), attach an empty script (only `extends Node` statement), and you can reproduce it.

The catalyst is the search panel. If it is open before your scene is run, then any key press after that scene is stopped is going to produce an error. Simply holding any keyboard button triggers the message multiple times. As soon as you click on editor window, the issue is gone.

**Comment by pycbouh** [comment]
So, after a bit of investigating, I can tell, what's causing the problem, however I'm not sure of a solution.

Issue comes from `editor\code_editor.cpp` method `FindReplaceBar::_unhandled_input`. Code reaches condition
```swift
if (k->is_pressed() && (text_edit->has_focus() || vbc_lineedit->is_a_parent_of(get_focus_owner()))) {
```

It first checks, whether the event was triggered on button press, and not release. Then it tests if a text input field for the search panel has focus, directly or indirectly. For indirect approach `get_focus_owner()` method is used. Problem here is that after a scene was started, for whatever reason, there is no focus owner and `get_focus_owner()` returns `NULL`, which then causes the error in OP.

Now, there is no problem with focus from simply alt-tabbing or otherwise changing an active window. It seems to be directly related to the fact, that we run a scene. Additionally, it turns out, there is no need to stop your running scene, to have this issue. Just return focus to the Editor window after you start a scene using window header, alt-tab, or system dock, and try to press any button on your keyboard.

One idea I have is that the last focus owner before a scene is run is this little button:
![image](https://user-images.githubusercontent.com/11782833/75959790-f59a6900-5ecf-11ea-87d2-43263d2908ab.png)

This button and other buttons in that panel change as soon as a scene is started. At a glance, it seems to be a simple icon change. But there may be something that I don't see that happens at the same moment and can affect focus owner.

We can handle `NULL` value of `get_focus_owner()` explicitly in `FindReplaceBar`, just to get rid of the error. I'm just not sure, though, if there is an underlying problem, that is going to be covered by it.

**Comment by RustanHakansson** [comment]
This bug still exists, version 3.2.1.

**Comment by NadimD** [comment]
It also happens to me quite often and only restarting the project gets rid of it. In version 3.2.1.

**Comment by owlnical** [comment]
I have the same problem:

     scene/main/node.cpp:1430 - Parameter "p_node" is null.

I can trigger it by following the steps above. At one point I was able to trigger it continuously by simply holding control while in the script editor. I haven't been able to reproduce that yet though.

**Comment by NelsonSMG** [comment]
I have the same problem,
Happens when I close the game and press control, if I click the editor and press control again it doesn't appear anymore.
