### ISSUE TITLE
Don't store the .import file when using the default settings

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#24177]
**Godot version:**
`master` @ 99640ac583f560771d0ceab3cde7e567f5cdff47

I know this has been dismissed before but I didn't find a proper issue about the topic, so I'm reviving the points about it. This is the result of a discussion I had with @jahd2602.

**The problems**
* The `.import` files sitting besides the assets clutter the folders. Essentially we have double the amount of files in the project, making it harder to manage.
* While those files are small, there are many of them and they occupy space in the repository. They also need to be dealt with when doing merges.
* Deleting, renaming, and moving assets require doing the same process to the related `.import` file. Failing to do so make the `.import` live there on its own, since there's no cleanup tool. While doing those operations with the FileSystem dock makes the `.import` file go with it, it's not always feasible to use the Godot editor for this.
* Changing the default import settings to apply to all resources requires you to delete all the `.import` files related to them.
* They occupy space in the exported project, even though the import options are not relevant there anymore.

**The solution**
Don't store the `.import` file when the resource is imported with default settings.

**The problems with the solution**
* We still need the remap information, such as path and type. This can be solved in the editor by asking the importer, but it's still needed on export. And while this information can be generated at export time, it breaks the possibility of running the source project with the release template.
* If the user change the default preset settings it should re-import everything (of the same type), but it's not clear for the editor to know what should be re-imported.
* If the new default is the same as an existing `.import`, it's not clear whether it should be removed.
* If we want the settings of a particular resource to be same as the default but not change with new defaults, it's not simple to force a `.import` file (though there could be UI for this).

**Comment by girng** [comment]
real question is why does .import exist and duplicates my files?

**Comment by eon-s** [comment]
Setting files for some resources like image files were always there (.flag I think?).

Default settings without files could make more confusing without a default settings setup on project creation and defaults manager inside the editor (plus current defaults are not too good).

**Comment by girng** [comment]
imo it's a big deal because all the developer's files (textures, etc) are duplicated in the .import folder. this can drastically increase the project's file size. my example might be bad because it's just one  53kb file, which now the developer will need 106kb of space. i'm trying to say: imagine larger projects with tons of textures.

i think the .import file that sits next to the file should be sufficient

**Comment by volzhs** [comment]
what about having `.default_import` file on project root directory, and `.import` files if the individual file setting is different from the `.default_import`?

**Comment by NathanWarden** [comment]
> imo it's a big deal because all the developer's files (textures, etc) are duplicated in the .import folder. this can drastically increase the project's file size. my example might be bad because it's just one 53kb file, which now the developer will need 106kb of space. i'm trying to say: imagine larger projects with tons of textures.
> 
> i think the .import file that sits next to the file should be sufficient

It's not actually duplicating the files though. It's importing them into a format that can be used by the engine. So, without the import folder your machine would have to re-import these files each time you open the project and then store all of these assets in RAM. So, it's highly necessary to have an import folder. It really isn't that bad as far as space goes. Unity does the same thing. I have countless 3D projects that I've worked on for clients over the years and have plenty of drive space. :)

**Comment by Zylann** [comment]
A note about the space .import takes, I think it has been reported that assets in it are not always cleaned up, so it often grows unnecessarily over time (though I can't seem to find an issue about it?). This in particular should be an improvement to work on as far as space is concerned, but otherwise I agree with @NathanWarden.

**Comment by groud** [comment]
But if you change the default import settings, what happens? All already imported resources are going to have a new .import file so that their import setrings stay the same ?

Honestly the current system is a little bit more clutter but at least it is simple.

**Comment by asheraryam** [comment]
> That's one of the problems. IMO though, if you are importing everything with default is because you want the defaults, even if they change.

I think that's a good enough reason to accept the change.

**Comment by akien-mga** [comment]
I'm fine with not saving default import flags, but *only* if users are asked to select import presets for their resources when they create a new project, and *this* setting is saved (in `project.godot`). This way they know that their import flags won't magically change when upgrading their Godot version, as we'll treat any change to preset defaults as a compatibility breakage.

**Comment by aaronfranke** [comment]
For the last 2 points, perhaps existing files should never be deleted, but new files are not created unless the user changes anything. So then if you want to preserve the existing settings regardless of the defaults changing, you simply change a setting and then change it back.

This would mean that existing projects would have the same files, but...

Perhaps there could be a button in Godot that removes all default-only `.import` files?

**Comment by girng** [comment]
> It's not actually duplicating the files though. It's importing them into a format that can be used by the engine.

well, i don't know how else to word it then lol. i just see a 53kb .png background in my Textures folder. then, there is a file that has the same name of it, inside .import, that is 53kb. i just thought of the word duplicate, but even if it's not a 100% duplicate of the file, it basically does x * 2 on storage space. which imo is not needed. and this was not a  problem in previous godot 3.0 versions AFAIK

**Comment by eon-s** [comment]
@girng 53kb is too much for import flags, even 1kb is a lot
It seems like a bugged import, can you look at it with a text editor?

**Comment by eon-s** [comment]
Oh, files inside the import folder, right...

Maybe the `import` extension needs to be changed to not confuse it with the folder, but that is for another issue...

**Comment by Zireael07** [comment]
@aaronfranke: I was gonna link that issue but I couldn't find it.

**Comment by vnen** [comment]
BTW I did a proof of concept of this proposal. Still don't solve all the issues. I save the `*.import` files inside the `.import/` folder when they have default settings, so they are still there for the remap check but doesn't need to be tracked.

Link to my changes: https://github.com/jahd2602/godot/compare/3882e0d006efbd076bdc6d08fb844e006d30e718...jahd2602:98eb965deda3cfcf2fbd509ca170aa0c36f
f256a

**Comment by VitaZheltyakov** [comment]
The .import file problem is manifested when there are a lot of assets and they are in different directories. This is a big game problem. 
We must respect the developers of the big games and give them the opportunity to choose.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
