### ISSUE TITLE
More support for JSON format

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24186]
**Godot version:**
11d77386221a4d911edee4fdbba5d3b9109a1c6b

**Proposal1:**
Godot has the ability to check which files depends on which files. This is great and I'd love to see it extended to json files, since that is such a common file format.

**Proposal2:**
Have the ability to edit Json files directly inside Godot.

**Comment by akien-mga** [comment]
>  Godot has the ability to check which files depends on which files. This is great and I'd love to see it extended to json files, since that is such a common file format.

Could you be more explicit about how what you have in mind exactly? Do you mean a dependency system between JSON files (is there such a feature in the JSON spec)? Or do you mean treating JSON files as resources owned by scenes/scripts?

>  Have the ability to edit Json files directly inside Godot.

That's possible already in the script text editor, there's support for editing arbitrary text files. It's not well integrated in the File > Open dialog yet though, nor in the FileSystem dock.

**Comment by QbieShay** [comment]
@akien-mga I meant both treating json files as resources owned by scenses/scripts but also the other way around: so that a json file can own other resources (practical example: if the json file contains a path to a tscn or an image, it should be seen as owner of those.)

> That's possible already in the script text editor, there's support for editing arbitrary text files. It's not well integrated in the File > Open dialog yet though, nor in the FileSystem dock.

Then this needs a separate issue.

**Comment by QbieShay** [comment]
@akien-mga I believe this is something that can be done incrementally. Starting with support for full/relative paths.

I believe that full support for dynamic paths is not possible, but keeping track of static ones would already be an improvement

**Comment by swarnimarun** [comment]
@QbieShay I see you ask for JSON to also be able to hold other resources and nodes... 

I think storing path is reasonable, but how would you store scene-nodes in them. What for resources like Image which hold data and aren't necessarily actual images that can be referenced?

And will you parse all the files everytime a change is made like I created a JSON file with an invalid reference and then create some files which make the reference valid will we re-parse all the files? 

Also maintaining cyclic dependencies is gonna be a problem would it not?

**Comment by QbieShay** [comment]
@swarnimarun Godot already has a way to detect cyclic dependencies, i think.

I believe there is a dependency tree somewhere, i don't think everything is parsed every time you move a file.

If a JSON file is opened in the godot editor it can show a warning if it is referencing an non existent file

**Comment by swarnimarun** [comment]
@QbieShay Yes it does but if we do an incremental addition of features I am not sure if the features from Godot can be mirrored one to one. If we add at least all of GDScript features to JSON then it makes sense though.

**Comment by mrcdk** [comment]
IMO, unless you are interacting with external applications, JSON files aren't that useful in Godot. You can already create your own scripts extending `Resource` which can be used as data containers plus they have all the bells and whistles that a `Resource` in Godot has and what GDScript will give you (not only you can keep data but validate and postprocess it with getters and setters for example) and, of course, you can export variables to the inspector so people don't need to get their hands dirty modifying text files directly. 

With the new `class_name` in 3.1 they are even more useful because you can create new ones from the create resource popup.

**Comment by QbieShay** [comment]
I can't really go in detail but I am working on a big project and we are making extensive use of JSON files, some of them generated dynamically.

But thanks for the tip with Resources, I'll see if I can make more use of them :)

**Comment by Zylann** [comment]
I don't know if anyone thought about this, but sometimes I even use plain GDScripts to write data. Last time I wrote my level list in a `level_list.gd`, which was basically very similar to a human-readable JSON file:
```gdscript
const levels = {
    "level0_tuto1",
    "level0_tuto2",
    "level1",
    etc
}
```
Which I can simply access anywhere like this:
```gdscript
var level = preload("res://level_list.gd").levels[index]
```
This way I didn't even need a resource since it's just human-readable data :)

JSON can surely be supported as a resource type, but bear in mind that JSON is JSON, so you won't get `Vector2`, `Resource`, and references in it without breaking the standard, it would become `GodotishJSON` instead.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
