### ISSUE TITLE
Add Get_node_of_type( MyCustomNodeType ) function 

### ISSUE THREAD

**Issue by TextusGames** [godotengine/godot#24193]
Since we now have class_name for custom scipts, could we have  have buid- in funcion like get_node_of_type( type/class_name ). I came here from Unity and Unreal and it was not clear for me how to get custom node by it's type and not by it's name, since nodes can be renamed.

`
# it can be found by this code
var my_custom_node
for node in SomeNode.get_childrens()
    If node is MyCustomNode:
       my_custom_node = node
       break

# but it is much simplier to write
var my_custom_node = SomeNode.get_node_of_type(  MyCustomNodeType )
   
`
I think these need to be a build-in functions.
# returns node by type
get_node_of_type( MyCustomNodeType )
find_node_of_type( Type type, bool recursive=true, bool owned=true ) 
# returns array of nodes
get_nodes_of_types( MyCustomNodeType)
find_nodes_of_type( Type type, bool recursive=true, bool owned=true )  

Than you are getting nodes dynamicly it is a common operation, if you does not know wether node wil have specific node or nodes  as it childrens then you must find them by Type ( or by relative file_name before godot 3.1  i guess ) .
It just better to find node by its type and not by its name since nodes can be renamed and if you have more then one node in same child hierarchy they have to have different name.

**Comment by Zylann** [comment]
I didn't use that often because I always cache children by path, however I often used a variant of this going upwards the tree instead: `get_node_in_parent()`, which would allow to get the first found parent of a given type:
```gdscript
static func get_node_in_parents(node, klass):
	while node != null:
		node = node.get_parent()
		if node != null and node is klass:
			return node
	return null
```
(despite being similar, should it be a different issue? Although I never felt the urge to make one, I felt this was related)

**Comment by akien-mga** [comment]
See discussion in https://github.com/godotengine/godot/pull/24492#issuecomment-524870081, this doesn't appear to be a good idea as it encourages bad design for communication between nodes, with a great performance cost compared to recommended methods that Godot's scene system was designed around.

If there are valid use cases which seem not to be covered by the existing best practices and features of the engine, it would be worth discussing further so that the documentation can be improved to cover them.
