### ISSUE TITLE
Slow loading of images in folder

### ISSUE THREAD

**Issue by damianday** [godotengine/godot#24228]
Godot version:
Godot 3.1

OS/device including version:
Windows 10 64 -bits

Issue description:
When opening a folder to select an image which contains hundreds of images it takes a long time to load.

Steps to reproduce:
Assign any image to a sprite from a large folder of images. 

As a performance improvement, it should only load the visible images in the directory tree, no need to waste time loading every image.

**Comment by Calinou** [comment]
@damianday Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
