### ISSUE TITLE
Add the possibility to minimize and expand docks

### ISSUE THREAD

**Issue by 95camarones** [godotengine/godot#24235]
**Godot version:**

3.0.6

**OS/device including version:**

**Issue description:**

I run Godot on a laptop with a fairly small screen. This means that the docks take up almost half the screen, even at their minimum size. I know there is some flexibility given by rearranging all the docks to one side of the screen, but it would be nice if they could be minimised and expanded on mouseover or click, like the Mac OS X Dock.

![captura de pantalla 2018-12-09 a las 8 40 24](https://user-images.githubusercontent.com/41108485/49695159-7c0db100-fb8e-11e8-98bb-a15af0cc6f95.jpg)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by girng** [comment]
![image](https://user-images.githubusercontent.com/45474847/49695425-9e340e80-fb4f-11e8-9070-cbf9963c8b16.png)

can try this

**Comment by Chaosus** [comment]
You can also use 
![image](https://user-images.githubusercontent.com/3036176/49781530-2965fd80-fd24-11e8-9c34-39207f561e26.png)
to group and hide docks

> On a separate note, does anyone know why this part of the AutoTile panel is partially obscured? I've

Please create a separate issue about it(it may be bug).
Use community channels to ask questions, issue tracker is not a place for them. Closed.

**Comment by Ranoller** [comment]
Well, i been having some discomforts editing because the lateral docks. Sometimes the lateral docks needed to be hidden and the bottom panel need to be showed when editing. Or maybe you need the **Distraction free mode** but with inspector and animation bottom dock, or something like this. Free distraction mode is only useful for scripting, but will be fine to have two more buttons to hide panels in the left and panels in the right. I have this buttons in my plugins but for hide/show my own lateral windows, something like  "<"(left panels)   "<>" (free distraction mode) and ">" (right panels).
I think in two solutions:
- Expose lateral panels to EditorPlugin:
Can´t be accesed for now to hide/show, only to add a plugin.
- Make two more buttons rounding free distraction mode, to show/hide independently lateral panels.
This buttons can flip the sprite to indicate "show" "hidde" state of the socks, and can be restored on push distraction free mode, something like that:
![LateralHideShow](https://user-images.githubusercontent.com/11712737/61171737-26faa900-a57c-11e9-99d6-1ed2ba4f7e7a.gif)

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1441, as feature proposals are now tracked on the Godot proposals repository.
