### ISSUE TITLE
Smarter new scene dialog

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24296]
**Godot version:**
11d7738

**Issue description:**
The new scene dialog is a good addition, but in my opinion it can be improved in the following ways:

1. Add also the "Node" as one of the defaults
2. Add a button for instanced scenes (I think it is common for people to click on "new scene" when they actually want an "inherited scene"
3. Add a list of the last used nodes

The list structure should be like this in my opinion:
- Custom Node ...
- Inherited scene ...
- __________
- 2D
- 3D
- User Interface
- General Node
- __________
- [list of the last 3-4 used nodes]

I believe this layout would improve even more the scene creation, as I noticed for myself that those are the nodes that I am most likely to search for when creating a new scene.
Separators would be a nice to have inside of the list

**Comment by mindinsomnia** [comment]
Personally I'd like to see the new scene dialog also moved into the middle of the stage where the 2D/3D views are located, instead of under the Scene nodes list. Along with a list of recent scenes and thumbnails for quickly reopening something you just had open.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
