### ISSUE TITLE
Dialogs not visible by default

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#2431]
*Bugsquad edit:* Seen in the master branch / 2.0 alpha

What happened with all dialogs (WindowDialog, ConfirmationDialog, etc)? they're all invisible when you run.

**Comment by vnen** [comment]
Do you that they are invisible by default, right? You have to make them visible from code.

**Comment by guilhermefelipecgs** [comment]
Strange, this will be the new default behavior?

**Comment by AlexHolly** [comment]
+1 Doesn't feel right... it should save the previous state.
Why is the location not relativ to the parent node?
I drag the parent node(Node2D) and the WindowDialog is not moving.

**Comment by akien-mga** [comment]
@reduz Bug or feature?

**Comment by reduz** [comment]
feature, a lot of controls have dialogs hidden by default, so they are hidden by default. I changed today something that makes it easier to edit them (so they don't appear always on top when toggled viible)

**Comment by Bonkuraazu** [comment]
The issue for me here is that when i've saved a scene with the dialogs visible, they don't remain visible when I open the scene back up. The engine seems to save the visibility state of other nodes, so it seems like it forces windowDialogs to be invisible whenever they are loaded in any scenario. Shouldn't it only force invisibility upon creating the node, not when reloading it in a saved scene?

**Comment by neikeq** [comment]
@Bonkuraazu The problem is that the right way to show a _Popup_ is by calling the _popup()_ method (or its variants), not by changing its visibility. If you want to do it without scripts, just connect the signal `enter_tree` with the method `popup` from the _SceneTree_. The connection must be in deferred mode (enable the _Deferred_ checkbox), otherwise the game will crash.

**Comment by Bonkuraazu** [comment]
@neikeq Thanks for the reply, turns out I'm just an idiot. However I think I still found a bug at the end. Also where exactly do you put the popup method if you're not using scripts?

**Comment by neikeq** [comment]
@Bonkuraazu I'm not sure if I understood your question. Do you mean where do I connect the signal with this method?

**Comment by Bonkuraazu** [comment]
@neikeq here's what I tried doing. First I clicked on the popup node in the scene tree, then I clicked "edit the node connections." In the Edit Connections window I clicked on "enter_tree()", then Connect. Not knowing what else to do I checked Deferred and hit Connect. I guess I'm missing something because I don't know where or how you can tell it to run the method popup() without creating a script.

**Comment by neikeq** [comment]
The image above has the field _"Method In Node"_. That's where the method name should go. In that image I was connecting to _popup_centered_, which requires the extra _Vector2_ parameter I set to _800, 600_.

**Comment by Bonkuraazu** [comment]
@neikeq Oh, I see! I thought you had to call the method inside the function it would create if you didn't edit the "Method In Node" field. Thank you very much for helping me
