### ISSUE TITLE
Add an optional `delta` parameter to `KinematicBody.move_and_slide()`

### ISSUE THREAD

**Issue by shinyclaw** [godotengine/godot#24322]
Let's assume that we have a client (running at 60 FPS) that is sending inputs to the server each frame. The server (running at 30 FPS) collects these inputs and tries to return the correct position to the client doing the physics calculation on his side. If we try using move_and_slide for this purpose we got an incorrect position because of the difference in the server and client FPS. move_and_slide function should have exposed a delta time parameter, so we can use delta obtained from client.

**Comment by girng** [comment]
if you are sending input each frame, you could end up sending 144++ inputs per second. a fixed network interval rate is ideal. in any event, you could just send the position data at a fixed rate instead. then use lerp, or use move_and_slide with the `new_vector = (incoming_position - player_node.global_position).normalized()`

move_and_slide is not useless in client-server topology imo. i think you mean more of "add delta parameter to move_and_slide for better client->server synchronization" or something.

**Comment by shinyclaw** [comment]
You are absolutely right about the fixed interval rate. It was only example for illustrating the problem. And of course, we can use move_and_slide in this way, but this requires additional code... I just don't understand why move_and_slide does not have exposed delta parameter...

**Comment by shinyclaw** [comment]
Maybe this is a reason:

https://github.com/godotengine/godot/blob/e588c241681032c616a998a9884b30215ea7d4e3/scene/2d/physics_body_2d.cpp#L1240

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
