### ISSUE TITLE
Favourite icon is hard to spot in most of the places where it appears

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24347]
**Godot version:**
11d7738

**Issue description:**
I started looking into "solving" https://github.com/godotengine/godot/issues/24296 and only then i noticed that you can actually star nodes.
In my opinion, the top right star in the node selection pop up is completely invisible and does not suggest in any way that is related to nodes.
I see that it was probably made to match the style of the browser, but I don't think it is visible nor intuitive.
Same goes for the favourite tab when creating a new scene: might be only me, but i discovered its existence while i was digging in the sources of the editor.

**Proposal:**
One of the principles of good UX is affordance: hinting the user that an object has a certain functionality through design.
Following this principle, i believe that each entry of the node list should have a star on the rightmost side that's greyed out for non favourite and that becomes yellow when starred.
This way the star is clearly related to one entry in the list (the one up top suggests that it is related to the list as a whole in my opinion, exactly as the favourite button in web browser: it is not related to a specific piece of content, it is related to the whole page)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
