### ISSUE TITLE
Make Godot Paths configurable with env variables

### ISSUE THREAD

**Issue by fxcalibur** [godotengine/godot#24345]
Feature Suggestion:
It would be great to be able to configure Godot's search paths with env variables.
Right now one can either have per user configs/templates in %APPDATA% / HOME or the self-contained mode.

The former makes packaging Godot impossible, the latter doesn't allow per user local configs in addition to the ones on the server/in the package manager. Also then everything has to be in the same folder relative to the binary and is not at all modular.
I've seen suggestions to set %APPDATA% to a custom location, but if you want to make it accessible for multiple users, then you don't want them to have write privileges there. Also again not modular.

A solution would be to have env variables that modify search paths ( separated by ; )

Example for export templates and editor plugins( inspired by how SideFX Houdini solves this ):
GODOT_EXPORT_TEMPLATES_PATH=//servershare/godot/templates;d:/dev/godot/templates;&
GODOT_EDITOR_PLUGINS_PATH=//servershare/godot/plugA/1.0.0;//servershare/godot/plugB/1.1.0

Godot would then search first in //servershare/godot/templates, then in d:/dev/godot/templates and finally in it's default user home location indicated by &
It would also load editor plugins from plugA/1.0.0 and plugB/1.1.0

- "first come first serve" = modules earlier in the path would take precedence over later ones.
- env variables that are not set, won't affect Godot = it won't affect anyone's current setup
- all paths can be completely overwritten to a location and not allow local data if you leave out the & indicator
- it's flexible! all you need to do is change the env variables before you launch Godot ( make a wrapper )
- multiple Godot versions could have different paths set to avoid incompatibility
- it's more modular and packaging templates / editor plugins would be much easier

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
