### ISSUE TITLE
Kinematic on Kinematic - remove applied force

### ISSUE THREAD

**Issue by alketii** [godotengine/godot#2435]
There should be an option when KinematicBody2D colliding another KinematicBody2D, there shouldn't be any force applied(aka no collision movement).

**Comment by guilhermefelipecgs** [comment]
Do you know Layers and Masks? this aren't enough?

**Comment by alketii** [comment]
No

**Comment by guilhermefelipecgs** [comment]
Try put the Kinematics Body in different layers, like layer 2 and 3, then they will not collide.
![captura de tela de 2015-09-06 14 23 35](https://cloud.githubusercontent.com/assets/1387165/9705696/b8fb0594-54a3-11e5-9131-f7c2f81d5562.png)

**Comment by alketii** [comment]
I know about add_collision_exception_with, layers and masks, but what I need is for applied force to be optional.
Imagine two objects colliding with each other on moving +10 the other one -10
There can be three applied force modes
1. mode="normal", the one currently
2. mode="ghost", it will only detect collision and objects will pass through.
3. mode="strong", none of them will win over the other, they will stand still.

**Comment by reduz** [comment]
I don't see any difference between normal and strong (although strong
doesn't make much sense or I can't understand it). For "ghost" you can set
shapes as trigger.

**Comment by alketii** [comment]
reduz, in some cases they move, though rare.

**Comment by akien-mga** [comment]
Related to #1472.

**Comment by RebelliousX** [comment]
If this issue is solved, it will save me tons of headache and code. The only alternative is Area2D which is not as advanced as KinematicBody for collisions.

**Comment by bojidar-bg** [comment]
Ok, I think I finally understood this issue (hehe). It lies in the fact that when two KinematicBodies move() towards each other, the one that gets it's _fixed_process called first wins. I'm not sure what we can do about it, but it is probably a mild showstopper for some of their nice uses....

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
