### ISSUE TITLE
Group-based, cross-language script interface warnings for the editor

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#24354]
**Issue description:**
Assuming that an editor-wide statically-defined group system is merged (PR #24262), it would open up the possibility of the editor assisting users in enforcing specific interfaces between scripts (even scripts from different languages).

The scripting API exposes the list of method names associated with a class, and the mentioned PR allows us to define all allowed groups for the project (aside from runtime groups). It wouldn't be a stretch to then mandate that, if a list of method names is paired with a group, then any node with that group must be able to implement those methods. From there, we could use `get_configuration_warning()` to report a problem with a node that is in a group, but doesn't have the specified method implemented on it or its script. That way it'll just show a little icon with a tooltip just like an Area2D with no CollisionShape2D children. It's non-intrusive, doesn't create any "hard" errors (since it wouldn't be enforceable at runtime anyway), and is purely assistance that the editor provides.

WDYT?

**Comment by willnationsdev** [comment]
cc @xDGameStudios @Zylann

**Comment by willnationsdev** [comment]
@Zylann Yeah, I was imagining the first implementation. afaik, the only way to implement one's own `get_configuration_warning` method (at this time) is to implement it on a tool script. You'd have to give EditorPlugin some sort of callback that evaluates each Node in the scene dock whenever the scene dock updates itself (solves the "know when to change" bit). You'd then also have to give the EditorPlugin the ability to define its own configuration warning override or addendum (somehow appending any particular editor plugin's warning onto the tooltip (that way you'd have the original tooltip, if one exists already, and each plugin's tooltip).

**Comment by Zylann** [comment]
Could `SceneTree.node_configuration_warning_changed` help implementing such feature as a plugin?

**Comment by willnationsdev** [comment]
Yeah. It'd be nice if one could inject their own "configuration warning" for a node via a plugin. If that were possible, then it would enable this feature as a plugin.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
