### ISSUE TITLE
No document for AudioStreamMicrophone on help

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#24370]
**Godot version:**

3.1.alpha e588c2416

**OS/device including version:**

Kubuntu 18.10

**Issue description:**

No document for `AudioStreamMicrophone` on help
![screenshot_20181215_202926](https://user-images.githubusercontent.com/8281454/50042577-46922780-00a8-11e9-994e-5667e840afb8.png)

**Steps to reproduce:**
open help for `AudioStreamMicrophone`

**Minimal reproduction project:**

**Comment by FlamyAT** [comment]
I don't think this is an issue per se since no documentation has been added to [/doc/classes/AudioStreamMicrophone.xml ](https://github.com/godotengine/godot/blob/master/doc/classes/AudioStreamMicrophone.xml)

Look into [this](https://docs.godotengine.org/en/latest/community/contributing/updating_the_class_reference.html?highlight=commit) if you know how it works

**Comment by Chaosus** [comment]
There are lots of API class documentation is completly missed or not finished.. I dont think that its required to create an issue for each of them. That doesnt means that contribution to them is not welcome of course..

**Comment by akien-mga** [comment]
I think @volzhs thought it was a bug as there is no documentation *at all* (even no empty description for methods). But that's because `AudioStreamMicrophone` has no bound methods of its own, it's just virtual methods from its parent class, so there is effectively nothing to document apart from `description`, `brief_description`, `tutorials` and `demos`.
