### ISSUE TITLE
Open file in Append mode

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#24401]
**Godot version:**

Godot 3 Feature Request / Discussion

**Issue description:**

Currently Godot supports READ (rb), WRITE (wb), READ_WRITE (rb+), WRITE_READ (wb+).
- READ: can't write, file must exist
- WRITE: creates file if not exist, truncates existing content
- READ_WRITE: file must exist
- WRITE_READ: creates file if not exist, truncates existing content

Available modes either require that the file exists or the content be truncated. But `fopen` also has append modes (ab and ab+) that automatically create the new file if it doesn't exist and don't truncate the content. Still, everything this mode can do, you can already do in READ_WRITE mode with a litte bit more code, so I'm not sure if it's worth adding.

**Comment by dreamsComeTrue** [comment]
Yeah, as you noticed:

`
<constant name="**READ_WRITE**" value="3" enum="ModeFlags">
			Opens the file for read and write operations. Does not truncate the file.
		</constant>
`

`
		<constant name="**WRITE_READ**" value="7" enum="ModeFlags">
			Opens the file for read and write operations. Create it if the file does not exist and truncate if it exists.
`

If I get a consent, and will really be useful, I can work on this feature (adding "a" mode to fopen), beacuse, as you point out in fact - currently we have two modes - both of them read & write contents of the file, but none of them do not checks if file exist and DO NOT truncate it, and then set file pointer at the end of the file.

**Comment by mateusfccp** [comment]
I made something experimental:
https://github.com/mateusfccp/godot/commit/d31dd557143a0c3131ca1c87276c427527879dc2

It's untested, but compiling. By this implementation, the function should be called like:
```gdscript
var file = File.new()
file.open("user://foobar.dat", file.WRITE | file.APPEND)
file.store_string("foobar")
file.close()
```

So, instead of making something like `WRITE_APPEND` and `WRITE_READ_APPEND`, I made a single `APPEND` that can be flagged on both `WRITE` and `WRITE_READ`.

I am not sure this works on Android, as I couldn't find anything specific within the source for the implementation.

Also, there maybe some cases that I missed to check.

Finally, I'm in doubt with the following code:

```gdscript
Error _File::open_encrypted(const String &p_path, int p_mode_flags, const Vector<uint8_t> &p_key) {

	Error err = open(p_path, p_mode_flags);
	if (err)
		return err;

	FileAccessEncrypted *fae = memnew(FileAccessEncrypted);
	err = fae->open_and_parse(f, p_key, (p_mode_flags == WRITE) ? FileAccessEncrypted::MODE_WRITE_AES256 : FileAccessEncrypted::MODE_READ);
	if (err) {
		memdelete(fae);
		close();
		return err;
	}
	f = fae;
	return OK;
}
```

I don't know if `p_mode_flags == WRITE` should also include `WRITE | APPEND` or not.

What do you guys think?

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
