### ISSUE TITLE
Prompt to create CollisionShape/Polygon when creating an Area or Body node

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24413]
Much like the QOL improvement which gives a prompt in the Scene dock to create a root node when a new scene is created, it would be nice if the same kind of QOL improvement for shapes and polygon nodes.

Area nodes for example so commonly have a child CollisionShape or CollisionPolygon node that there is a warning in the editor insisting that the user consider making one (because an Area is much less useful without such a child node). As such, it would be nice if there was a shortcut button to make a CollisionShape or CollisionPolygon immediately after an Area (or Body) is created in the editor.

**Comment by Xrayez** [comment]
I know the suggestion is old but still relevant I think.

How do you envision this?
1. Prompt another "Create New Node" dialog right after adding the area/body nodes? Probably need another dedicated dialog with suggestions anyways.
1. Clicking on the warning icon, so that you can choose the type of node you'd like to add?
2. List suggested nodes directly in the popup menu when you right-click on the node?
3. Directly embed a few node suggestions into the node item as icons?

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
