### ISSUE TITLE
BitMap class definition conflicts with macOS Quickdraw.h's BitMap struct

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#24420]
**Godot version:**
Master (4b6e7b5)

**OS/device including version:**
macOS, Xcode 9.4.1 (Travis)

**Issue description:**
The following warning is raised when building with `scons p=osx dev=yes`:
```
./scene/resources/texture.h:91:1: warning: class 'BitMap' was previously declared as a struct [-Wmismatched-tags]
class BitMap;
^
/Applications/Xcode-9.4.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/QD.framework/Headers/Quickdraw.h:61:8: note: previous use is here
struct BitMap {
       ^
./scene/resources/texture.h:91:1: note: did you mean struct here?
class BitMap;
^~~~~
struct
```

Not sure how to fix it, are we forced to use a namespace to work it around?

**Comment by follower** [comment]
Short version, after a chunk of time trying more "proper" solutions (although not namespaces) I ended up with this working for me on Mac OS X 10.9:

```patch
diff --git a/platform/osx/os_osx.h b/platform/osx/os_osx.h
index 212966af1..fe16a7b9b 100644
--- a/platform/osx/os_osx.h
+++ b/platform/osx/os_osx.h
@@ -44,11 +44,13 @@
 #include "servers/visual/visual_server_wrap_mt.h"
 #include "servers/visual_server.h"
 
+#define BitMap QD_BitMap
 #include <AppKit/AppKit.h>
 #include <AppKit/NSCursor.h>
 #include <ApplicationServices/ApplicationServices.h>
 #include <CoreVideo/CoreVideo.h>
 
+#undef BitMap
 #undef CursorShape
 /**
 	@author Juan Linietsky <reduzio@gmail.com>
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index 113c6636f..480dab7c0 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -1426,7 +1426,7 @@ Error OS_OSX::initialize(const VideoMode &p_desired, int p_video_driver, int p_a
 	// setup our display link, this will inform us when a refresh is needed
 	CVDisplayLinkCreateWithActiveCGDisplays(&displayLink);
 	CVDisplayLinkSetOutputCallback(displayLink, &DisplayLinkCallback, this);
-	CVDisplayLinkSetCurrentCGDisplayFromOpenGLContext(displayLink, context.CGLContextObj, pixelFormat.CGLPixelFormatObj);
+	CVDisplayLinkSetCurrentCGDisplayFromOpenGLContext(displayLink, (CGLContextObj) context.CGLContextObj, (CGLPixelFormatObj) pixelFormat.CGLPixelFormatObj);
 	CVDisplayLinkStart(displayLink);
 
 	// initialise a conditional lock object
```

Clearly it's not ideal, but at least Works For Me. :) (And seems to have precedent given the line following. :D )

(The second file patch was not specifically related but was required.)

AFAICT the issue is a result of including this patch on pre-10.14 builds: https://github.com/godotengine/godot/commit/b53f2d1d598193ab1d1c02345fc321be254364ca#diff-fd0e7bd0fd01d2521078755bf719ef24

The additional includes added by the VSync patch cause QuickDraw-related files to be included which includes the `BitMap` struct (none of which is specifically used AFAICT). Given that QuickDraw has been deprecated/obsolete for something like over a decade and a half I feel like the `#define`/`#undef` combo is the "cleanest" quick approach--the other alternative is to only have the VSync patch on 10.14 but that would leave two code paths to maintain.

I've got some more observations/references but wanted to at least post this much now.

**Comment by follower** [comment]
Couple of follow-ups related to my comment above:

 * Explanation of why this conflict occurred: https://github.com/godotengine/godot/pull/33035#issuecomment-546701261
 * The "second file patch" mentioned turned into: https://github.com/godotengine/godot/pull/33116
 * Possible alternative approach: https://github.com/godotengine/godot/issues/33125
