### ISSUE TITLE
Add an overlaps_point method to Areas

### ISSUE THREAD

**Issue by Oranjoose** [godotengine/godot#24434]
Area nodes have an `overlaps_area` and an `overlaps_body` method. An `overlaps_point(Vector)` method would be very nice. Such a method exists in Unity (https://docs.unity3d.com/ScriptReference/Collider2D.OverlapPoint.html), Game Maker, and so on.

**Comment by eon-s** [comment]
Physics/Physics2DDirectSpaceState has that method.

http://docs.godotengine.org/en/3.0/classes/class_physics2ddirectspacestate.html#class-physics2ddirectspacestate-intersect-point

Area do not have to know what a point is (is a trigger type made to interact with other CollisionObjects) so maybe it does not belong to that class.

**Comment by Zylann** [comment]
Also, areas are not the only physics object that could be intersected with stuff, there is also static bodies, rigid bodies, kinematic bodies, both 2D and 3D.
Such functions are indeed all present in PhysicsServer, for point, ray and shape intersection.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
