### ISSUE TITLE
EditorFileSystem consolidation, refactoring FileSystemDock

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#24452]
**Issue description:**

Want to gather opinions on consolidating EditorFileSystem and refactor FileSystemDock functionality out into EditorFileSystem.

The way I see it... FileSystemDock refers to a visual representation of a file system so it shouldn't be FileSystemDock's jobs to handle file related tasks.
Renaming files, removing, creating and moving should be handle by EditorFileSystem.

FileSystemDock would just call the corresponding methods in EditorFileSystem...
this is also related to the new signals added recently... file_remove, folder_remove, file_move, folder_move... should be emitted by the EditorFileSystem and not the Dock

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
