### ISSUE TITLE
WebGL 2: 3D objects appear black

### ISSUE THREAD

**Issue by zaywolfe** [godotengine/godot#24465]
**Godot version:**
v3.1.alpha.official

**OS/device including version:**
Windows 10 64bit
AMD Radeon RX 580 
Driver Packaging Version 18.40.03.01-181010a-334550E-RadeonSoftwareAdrenalin

**Issue description:**
The shader breaks in exported html5 3D projects. It only displays black with the sky background. I didn't change any default settings except project name and starting scenes. The model was created in blender and exported with better collada. . Sprite3Ds also fail to show at all, but are completely transparent.

Everything seems to display correctly for a 2d scene

Here's an image of what I'm seeing.
![screenshot 2018-12-18 20 26 44](https://user-images.githubusercontent.com/16577483/50195687-cc5ede80-0305-11e9-8fcd-ea6db69b2029.png)

The Chrome console outputs:

> **ERROR**: SceneShaderGLES3: Fragment Program Compilation Failed:
> put_char @ pbjs.js:7
> pbjs.js:7 ERROR: 0:1555: '>' : wrong operand types - no operation '>' exists that takes a left-hand operand of type 'uniform highp float' and a right operand of type 'const int' (or there is no acceptable conversion)
> put_char @ pbjs.js:7
> pbjs.js:7 
> put_char @ pbjs.js:7
> pbjs.js:7    At: drivers/gles3/shader_gles3.cpp:173:_display_error_with_code() - SceneShaderGLES3: Fragment Program Compilation Failed:
> put_char @ pbjs.js:7
> pbjs.js:7 ERROR: 0:1555: '>' : wrong operand types - no operation '>' exists that takes a left-hand operand of type 'uniform highp float' and a right operand of type 'const int' (or there is no acceptable conversion)
> put_char @ pbjs.js:7
> pbjs.js:7 
> put_char @ pbjs.js:7
> pbjs.js:7 **ERROR**: SceneShaderGLES3: Fragment Program Compilation Failed:
> put_char @ pbjs.js:7
> pbjs.js:7 ERROR: 0:1555: '>' : wrong operand types - no operation '>' exists that takes a left-hand operand of type 'uniform highp float' and a right operand of type 'const int' (or there is no acceptable conversion)
> put_char @ pbjs.js:7
> pbjs.js:7 
> put_char @ pbjs.js:7
> pbjs.js:7    At: drivers/gles3/shader_gles3.cpp:438:get_current_version() - SceneShaderGLES3: Fragment Program Compilation Failed:
> put_char @ pbjs.js:7
> pbjs.js:7 ERROR: 0:1555: '>' : wrong operand types - no operation '>' exists that takes a left-hand operand of type 'uniform highp float' and a right operand of type 'const int' (or there is no acceptable conversion)
> put_char @ pbjs.js:7
> pbjs.js:7 
> put_char @ pbjs.js:7
> pbjs.js:7 **ERROR**: Method/Function Failed, returning: 0L
> put_char @ pbjs.js:7
> pbjs.js:7    At: drivers/gles3/shader_gles3.cpp:446:get_current_version() - Method/Function Failed, returning: 0L
> put_char @ pbjs.js:7
> pbjs.js:7 **ERROR**: Condition ' !version ' is true. returned: false
> put_char @ pbjs.js:7
> pbjs.js:7    At: drivers/gles3/shader_gles3.cpp:123:bind() - Condition ' !version ' is true. returned: false
> put_char @ pbjs.js:7
> pbjs.js:7 **ERROR**: Condition ' !version ' is true. returned: -1
> put_char @ pbjs.js:7
> pbjs.js:7    At: drivers/gles3/shader_gles3.h:380:_get_uniform() - Condition ' !version ' is true. returned: -1
> put_char @ pbjs.js:7
> pbjs.html:1 [.WebGL-00000215EA9D20C0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: uniform buffers : no buffer bound at index 4
> 128WebGL: INVALID_OPERATION: drawElements: no valid shader program in use
> 127WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
> pbjs.js:7 WebGL: too many errors, no more errors will be reported to the console for this context.

**Steps to reproduce:**
Just export any 3d scene with an OmniLight and a model in it exported with the Better Collada exporter

**Minimal reproduction project:**
[pbjs.zip](https://github.com/godotengine/godot/files/2693047/pbjs.zip)

**Comment by aurodev** [comment]
Also see this with GLES3 and Firefox v62.0 64bit 
Godot version:
Godot v3.1 Beta1

OS/device including version:
Windows 8.1 64bit, 8GB AMD FX 6350 6 core
Graphics Chipset
AMD Radeon HD 7700 Series
Memory Size 1024 MB
Radeon Software Version 17.4.4



![image](https://user-images.githubusercontent.com/7356383/50983032-83e1ad80-14cc-11e9-9cb2-76d3e1e0e7ad.png)




`
Error: WebGL warning: blitFramebuffer: DRAW_FRAMEBUFFER: This operation requires zeroing texture data. This is slow. tmp_export.js:7:333253
Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. tmp_export.js:7:339072
TypeError: this.transport is null: send@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1498:5
_sendEvent@resource://devtools/shared/base-loader.js -> resource://devtools/shared/protocol.js:997:5
Actor/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/protocol.js:971:40
emit@resource://devtools/shared/base-loader.js -> resource://devtools/shared/event-emitter.js:178:37
emit@resource://devtools/shared/base-loader.js -> resource://devtools/shared/event-emitter.js:255:29
addSecurityInfo@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/network-event.js:363:5
NetworkResponseListener.prototype._getSecurityInfo<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:519:5
exports.makeInfallible/<@resource://devtools/shared/base-loader.js -> resource://devtools/shared/ThreadSafeDevToolsUtils.js:109:14
onStartRequest@resource://devtools/shared/base-loader.js -> resource://devtools/shared/webconsole/network-monitor.js:439:5
event-emitter.js:183:13
TypeError: this._extraPools is null[Learn More] main.js:1517:5
Error: WebGL warning: compressedTexImage2D: COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT requires that width and height are block-aligned, or, if level>0, equal to 0, 1, or 2.
tmp_export.js:7:334453
Error: WebGL warning: blitFramebuffer: DRAW_FRAMEBUFFER: This operation requires zeroing texture data. This is slow. tmp_export.js:7:333253
Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. tmp_export.js:7:339072
Error: WebGL warning: drawElements: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: Because the minification filter requires mipmapping, the texture must be "mipmap complete". tmp_export.js:7:339072
Error: WebGL warning: compressedTexImage2D: COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT requires that width and height are block-aligned, or, if level>0, equal to 0, 1, or 2.
tmp_export.js:7:334453
Error: WebGL warning: blitFramebuffer: DRAW_FRAMEBUFFER: This operation requires zeroing texture data. This is slow. tmp_export.js:7:333253
Error: WebGL warning: drawElements: Buffer for uniform block is smaller than UNIFORM_BLOCK_DATA_SIZE. tmp_export.js:7:339072
Error: WebGL warning: drawElements: Active texture 0 for target 0x0de1 is 'incomplete', and will be rendered as RGBA(0,0,0,1), as per the GLES 2.0.24 $3.8.2: Because the minification filter requires mipmapping, the texture must be "mipmap complete". tmp_export.js:7:339072
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! 21752
`

**Comment by aurodev** [comment]
On GLES3 the stock Kinematic Character 3D sample loads slow but shows all textures and works normally.


![kinchar3d](https://user-images.githubusercontent.com/7356383/51058158-dea30400-15b5-11e9-9e08-eb7cdb575eef.PNG)

On GLES2 the sample fails to load at all. 
![errorswgl](https://user-images.githubusercontent.com/7356383/51058164-e4004e80-15b5-11e9-8c62-46ecb2a75b8e.PNG)

**Comment by TIBI4** [comment]
Editor:

HTML5 in GLES2:
- Time loading: Almost instantly (<2s).

HTML5 in GLES2:
- Time loading: Almost instantly (<2s).
- No textures.
![chrome_unxgvioydd](https://user-images.githubusercontent.com/25259582/51884358-b52ff980-2365-11e9-9ab2-b49704071639.png)

HTML5 in GLES3
- Time loading: More than 2mins.
- With textures, but they seem to be with more light.
![firefox_1j5r2vb15r](https://user-images.githubusercontent.com/25259582/51884335-9e89a280-2365-11e9-8c53-4655e5ae6610.png)

**Comment by TIBI4** [comment]
I cant remember their import combinations (Etc2, Etc, S 3 Tc)... But it is working like this for me:

**Editor:**
- Time loading: Almost instantly (<2s).
![godot_v3 1-beta3_win64_rmegi07py5](https://user-images.githubusercontent.com/25259582/51884445-10fa8280-2366-11e9-8556-3f2dcddd4648.png)

**HTML5 in GLES2:**
- Time loading: Almost instantly (<2s).
![firefox_d6qhlmo6c5](https://user-images.githubusercontent.com/25259582/51884433-02ac6680-2366-11e9-9f71-c5cbb9cc45ef.png)


**HTML5 in GLES2:**
- Time loading: Almost instantly (<2s).
![chrome_unxgvioydd](https://user-images.githubusercontent.com/25259582/51884358-b52ff980-2365-11e9-9ab2-b49704071639.png)

**HTML5 in GLES3:**
- Time loading: More than 2mins.
![firefox_1j5r2vb15r](https://user-images.githubusercontent.com/25259582/51884335-9e89a280-2365-11e9-8c53-4655e5ae6610.png)

**Comment by TIBI4** [comment]
### In Godot Beta 3 GLES2:
_The **errors** in the console:_
![image](https://user-images.githubusercontent.com/25259582/51919307-e8a07180-23c1-11e9-8678-0a2fdcc5a7aa.png)
![image](https://user-images.githubusercontent.com/25259582/51919519-59478e00-23c2-11e9-9a2e-3cccca33fa95.png)

_With **these settings**:_
![image](https://user-images.githubusercontent.com/25259582/51919380-0bcb2100-23c2-11e9-8732-7fccafc77ed3.png)
![image](https://user-images.githubusercontent.com/25259582/51919414-1f768780-23c2-11e9-8077-8a499228acc2.png)

**Comment by aurodev** [comment]
Some materials/textures work and some don't;  **panel.material** displays while **floor.material** is full dark.     
[3DCube.zip](https://github.com/godotengine/godot/files/2838191/3DCube.zip)

GLES2 and Firefox v62.0 64bit
Godot version:
Godot v3.1 Beta3

Lighting is odd, the side opposite the directional light vector is overly dark. Multiple directional or omni lights do affect the other dark sides. Ambient seems to have no effect.

![image](https://user-images.githubusercontent.com/7356383/52372855-330b9900-2a27-11e9-82b3-87df1fe99813.png)

**Comment by aurodev** [comment]
**With a rotating directional light**

![html5_gles2](https://user-images.githubusercontent.com/7356383/52493169-d203d280-2b98-11e9-9cd2-f62d11007466.gif)

**Comment by aurodev** [comment]
Seems the spatial mat for gles2 doesn't like Krita's PNG, all black, (tried different color profiles),  seems ok with Inkscape's PNG and Krita's TGA, lighting is still too dark.

**Comment by reduz** [comment]
This is working now, closing.
