### ISSUE TITLE
Better logging Android crashes to Google Play Console

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#24461]
**Godot version:**
Godot 3.1-dev (3c999ae)

**Issue description:**
When the app crashes, it's reported to the Google Play Console only with an empty stack trace that's pretty much impossible to work with (even with `ndk-stack` to remake the proper trace). It's difficult to take an action when that happens and might not even be a bug in Godot but something failing in the project.

Ideally, the log should show roughly where the error happened (last script call) and add that to the report. The simplest way to do so is throwing a Java exception when something happens, but it's difficult to actually get the point in the script, especially since GDScript stack is not populated on release builds.

**Comment by vnen** [comment]
My [(quite hacky) solution](https://github.com/JavaryGames/godot/commit/57fce72bd527d45cb0d33d33e4bc6a13024549c5 ) to this was to create a Java singleton that can throw an exception, then use exception in some places in  C++ prone to crashing to catch them in the GDScript code, and from there call the Java singleton to throw the Java exception with a custom message, showing the source script and line. Java exceptions are reported better in the Play console.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
