### ISSUE TITLE
Mono: Crash when implementing constructor c#

### ISSUE THREAD

**Issue by kvonspiczak** [godotengine/godot#24490]
**Godot version:**
3.0.6 stable, 3.1 alpha3

**OS/device including version:**
Win10 64bit

**Issue description:**
Godot crashes either immediately on opening the project, when running the game, or when clicking "load" in the "attach a script" dialog.

**Steps to reproduce:**
Create a new project
Create a new scene
Add a Node2D
Attach a new C# script
Inside the script add any kind of class member variable and a constructor which takes these parameters.
Like: 
```
public class Crash : Node2D
    {
        private int x;

        public Crash(int _x)
        {
            x = _x;
        }
    }
``` 

**Minimal reproduction project:**
[crash_godot.zip](https://github.com/godotengine/godot/files/2696878/crash_godot.zip)

**Comment by exts** [comment]
[GCrashTest1.zip](https://github.com/godotengine/godot/files/2696983/GCrashTest1.zip)

Reproduced this on windows 10 64bit also.

(cc @neikeq )

**Comment by somnivore** [comment]
Scripts with constructors need to be parameterless; the issue is that, when Godot creates this node (e.g. by loading a scene with it), it's not going to be able to pass whatever parameters you've required for that class to come into existence (even with default values, it seems.)  It's the same story for GDScript, `_init()` must be parameterless for nodes.  The exception appears to be that this node is created exclusively from code, where it seems to be OK with parameters, but it's still trouble if someone happens to attach that script to a node somewhere down the line.

Godot should definitely handle this problem more gracefully, however; it's necessary to delete your .mono folder in order to get the editor to open back up.  It should throw an error if this is detected.

**Comment by kvonspiczak** [comment]
@somnivore thanks for that explanation! indeed, i could only get it to work again by deleting .mono folder everytime godot would not open my project anymore.

**Comment by JohnSilverLong** [comment]
If you also add a empty constructor it won't crash.


```
public Crash()
{
}

public Crash(int _x)
{
}
```

**Comment by akien-mga** [comment]
It doesn't crash for me on Linux with 3.1 beta 6, but it does raise an exception:
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
```

**Comment by neikeq** [comment]
What should we do? Should we fail constructing the instance with an error or should we use another constuctor passing `default(T)` for parameters?

**Comment by neikeq** [comment]
All right, I made it fail with an error if it cannot find the parameterless constructor. You still need to define a parameterless constructor, but it will not crash if you don't.

Feel free to open a new issue if you think this could be done differently or improved.
