### ISSUE TITLE
Bezier editor node for GUI

### ISSUE THREAD

**Issue by MrMinimal** [godotengine/godot#24524]
**Godot version:**
possibly 3.2

**OS/device including version:**
any

**Proposal:**
Would it be possible to have the bezier curve editor from the 3.1 inspector availible as a Control for use in GUI development?
![curve_editor](https://user-images.githubusercontent.com/8739690/50339298-66e23c00-0517-11e9-9503-3d80ea857ef2.png)

Curves can already be created in GDScript, yet editing them over a GUI is not yet possible without significant implementation effort per game.

It would also be interesting for input remapping UIs since, curves are useful for joystick inputs.

**Comment by Zylann** [comment]
I would like to have it too, for making editor plugins.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
