### ISSUE TITLE
Missing "test_data" folder in unit tests

### ISSUE THREAD

**Issue by firefly2442** [godotengine/godot#2454]
The tests in `bin/tests/` seem to be missing some resources.  In particular, `./bin/tests/test_io.cpp` and `./bin/tests/test_gui.cpp` both refer to files in a `test_data` folder that does not exist.

e.g.:

./bin/tests/test_io.cpp:    RES texture = ResourceLoader::load("test_data/rock.png");
./bin/tests/test_io.cpp:    ResourceSaver::save("test_data/rock.xml",texture);
./bin/tests/test_io.cpp:        FileAccess\* z = FileAccess::open("test_data/archive.zip", FileAccess::READ);
./bin/tests/test_gui.cpp:       text->load("test_data/concave.png");

**Comment by AfterRebelion** [comment]
Aside from the folder being relocated (Test are now located in `/main/tests`, not on `/bin/tests`) the issue is still valid.

./main/tests/test_io.cpp still has
[RES texture = ResourceLoader::load("test_data/rock.png");](https://github.com/godotengine/godot/blob/c3bb4edb79db9377b803e88d6385e6842ba0871f/main/tests/test_io.cpp#L89)
[ResourceSaver::save("test_data/rock.xml",texture);](https://github.com/godotengine/godot/blob/c3bb4edb79db9377b803e88d6385e6842ba0871f/main/tests/test_io.cpp#L92)
[FileAccess* z = FileAccess::open("test_data/archive.zip", FileAccess::READ);](https://github.com/godotengine/godot/blob/c3bb4edb79db9377b803e88d6385e6842ba0871f/main/tests/test_io.cpp#L102)

But ./main/tests/test_gui.cpp doesn't seem to have any reference to the `test_data` folder anymore.

**Comment by akien-mga** [comment]
Thanks for the update, I've dropped `test_io.cpp` which doesn't do anything useful without those files.
