### ISSUE TITLE
many nodes in the same position do queue_free(),cause lag.

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#2463]
In platform2d demo,if there are many coins(for me,if number>=5 on my compute) in the same position. When the player eat them at the same time,there will appear a pause.

**Comment by zhagsenkk** [comment]
i would make a Elimination game,but when there are many blocks to queue_free,this will cause a problem.

**Comment by reduz** [comment]
freeing should be quick, but honestly, never checked or particularly
optimized this path. Can you make a small test of doing many queue_free()s
in a situation similar to your game? this way I can give it a check and
make sure it can be properly optimized.

**Comment by zhagsenkk** [comment]
just duplicate the coin in the same position in platform2d demo.Eat it.

I think it is caused by  "Call Func Track" of animation.I imitate this in the elimination game,and lag happens.

**Comment by reduz** [comment]
Fixed the console prints, and can't see the performance penalty.

However, it is very possible that the performance penalty happens because areas can monitor other areas, so having many at the same place causes N*N collision detections. Try disabling the monitorable property on areas if you don't intend that to happen.
