### ISSUE TITLE
Raw deflate stream support in PoolByteArray.decompress()

### ISSUE THREAD

**Issue by jellehermsen** [godotengine/godot#24638]
It would be nice if we could have an extra optional argument in PoolByteArray.decompress that allows it to skip validating the Adler-32 checksum it expects at the end of the array. If we add this, we can have easy and fast zip-file decompression in GDScript. Right now I have implemented an [inflator in pure GDScript](https://github.com/jellehermsen/gdunzip), but it's a tad bit slow. This is of course a feature request, and I understand if it's only a minor edge case, but I'm willing to implement it if others think this is helpful.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by jellehermsen** [comment]
Geachte heer/mevrouw,
Ik ben offline. Op 16 augustus ben ik weer aan het werk en zal ik uw e-mail beantwoorden.

Hartelijke groet,
Jelle Hermsen

--------------------------
Dear sir/madam,
I am offline. I will reply to your e-mail on August 16.

Best regards,
Jelle Hermsen
