### ISSUE TITLE
Syntax Error window occupying too much space on monitor

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#24706]
**Godot version:**
Godot_v3.1-alpha4_win64.exe

**OS/device including version:**
Windows 10 1809

**Issue description:**
Syntax Error window or area occupying too much space on monitor. Hard to explain it in words. See pic.
Just 5 lines of code editor at reduced font of (10 and 10). Hardly 3 line space of code editor at default font sizes(14 and 14). Now way to hide it either
![capture74](https://user-images.githubusercontent.com/11459028/50580158-62037d80-0e71-11e9-8029-c0f8724f39de.PNG)

**Steps to reproduce:**
1. Type code something like `look_at(target.transform.origin,Vector3.UP.x)`. Passed float parameter when Vector3 was required. Only certain syntax errors cause it.
3. Pressing play or run triggers it.

**Minimal reproduction project:**

**Comment by qarmin** [comment]
Duplicate https://github.com/godotengine/godot/issues/22302

**Comment by mateusfccp** [comment]
Here is my proposal:

Instead of adding everything as child of `status_bar`, I turned `status_bar` into a `VBoxContainer` created another `HBoxContainer` within it. The result is the following:

![captura de tela de 2019-01-02 13-04-17](https://user-images.githubusercontent.com/4605213/50597618-28416f80-0e8f-11e9-94d3-c88f3d034bf8.png)

What do you think?
