### ISSUE TITLE
Vector3 returned from lerp treated as float when directly assigned to a Vector3 variable

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#24709]
Godot version:
Godot_v3.1-alpha4_win64.exe

OS/device including version:
Windows 10 1809

**Issue description:**
Vector3 returned from lerp treated as float when directly assigned to a Vector3 variable.
`
var a=lerp(transform.origin, target.transform.origin, delta * followSpeed )
transform.origin=a
`
works.
`transform.origin=lerp(transform.origin, target.transform.origin, delta * followSpeed )`
doesn't work.

Result:
![capture77](https://user-images.githubusercontent.com/11459028/50581778-e14d7d00-0e82-11e9-8fc0-5fcfa4823b50.PNG)
Isn't lines 10,12 == line 13?

Also: Docs says lerp returns float.
![capture75](https://user-images.githubusercontent.com/11459028/50581816-312c4400-0e83-11e9-9ac7-aff5d5d522cf.PNG)

**Steps to reproduce:**
Run the code:
transform.origin=lerp(transform.origin, target.transform.origin, delta * followSpeed)

**Minimal reproduction project:**

**Comment by FlamyAT** [comment]
I think that this is the expected behaviour.

`lerp` is a function returning a `float`.
To interpolate two vectors `Vector3.linear_interpolate` exists with the return type of `Vector3`.

In the first case your variable could be of any type, including `Vector3` so the engine can only determine at runtime which type it is.

In the second case you skip your variable thus the engine strictly knows that you want to change a property from `Vector3` to `float`.

**Comment by akien-mga** [comment]
Indeed, `transform.origin=a` should throw an error of mismatched type at runtime.

**Comment by avencherus** [comment]
@FlamyAT At some point it was changed.  It now takes variants, and can lerp between them.

![image](https://user-images.githubusercontent.com/13004169/51361491-ad0bca80-1ad8-11e9-82bb-2e882c2c2a38.png)

**Comment by akien-mga** [comment]
Indeed, there was actually a bug here. It's the same as #25082 though, so keeping the latter as it's clearer.
