### ISSUE TITLE
Mono builds on Steam

### ISSUE THREAD

**Issue by UnleavenedEagle** [godotengine/godot#24711]
Is there any chance that the build with Mono C# support could be added to Steam as a beta program just like stable-2.0 and stable-2.1? If not, why exactly?

**Comment by akien-mga** [comment]
Because Mono support in Godot 3.0.x is not beta, it's alpha. You need to have the exact Mono version specified on the download page to use it, otherwise it will crash. Steam is a platform of "one click install" where things are expected to work out of the box, so it's not a place for alpha software.

When Mono builds are stable enough and don't need any user-end setup to work, they can be provided on Steam.

**Comment by UnleavenedEagle** [comment]
Any update on this for 3.1 because of the improved C# support? I would just really love to be able to count my hours in Godot on Steam.

**Comment by akien-mga** [comment]
I might add it in the future for a 3.1.x release, but I'd like to see some more usability enhancements made before. We now ship the relevant parts of Mono, so the setup is much better, but there's still the dependency on MSBuild.

Either we should ship MSBuild ourselves if possible, or we need clearer errors and documentation on how to install MSBuild for all supported platforms.

**Comment by akien-mga** [comment]
> I would just really love to be able to count my hours in Godot on Steam.

You can replace the Godot binary for your platform by the Mono binary (+ the Mono SDK folder that comes with it) and it should Just Work(tm).

**Comment by TimCoraxAudio** [comment]
Apologies for bringing up this old thread. Is it possible to add MSBuild as a dependency or something? Usually on the first time playing a game Steam does a little installation of dependencies like c++ redistributables and such
