### ISSUE TITLE
Pause mode "Process" doesn't allow rigidbodies to be moved

### ISSUE THREAD

**Issue by sdfgeoff** [godotengine/godot#24717]
**Godot version:**
Recent Master

**OS/device including version:**
linux (Arch)

**Issue description:**
To pause a game, you pause the whole (singleton) scene tree. This applies to all objects, freezing the process function and holding is still in space. However, you don't always want to freeze all objects, sometimes you want most objects to be frozen, but some not to be (eg the HUD and menu's shouldn't be frozen). For this reason you can set the pause mode to "PAUSE_MODE_PROCESS" which means that the object does not get paused. While this works for the process functions and UI interaction, it does not allow spatial objects to move. For example, if I have a rigid body with the pause mode "process" it will stay stationary regardless.

**Minimal reproduction project:**
[PauseTest.zip](https://github.com/godotengine/godot/files/2720931/PauseTest.zip)

**Comment by sdfgeoff** [comment]
I just found #4001 which appears to be the same (but extremely old). But yeah, I suppose this is more of a feature request than a bug.

**Comment by akien-mga** [comment]
Quoting @reduz from #4001:

> This is not a bug, physics in it's entirety stops being processed during pause, this can't be fine-grained to different bodies since physics engine processes everything at once.

If this still applies, I'm not sure how feasible it would be to change that behaviour. We could imagine cloning the physics state, remove all paused bodies and keep processing the rest, but what should happen on resume? There would be conflicts in the physics simulation between paused and non-paused bodies.

It seems like for your use case, it's probably better to code a custom pause that does not use `SceneTree`'s pause.

**Comment by sdfgeoff** [comment]
> It seems like for your use case, it's probably better to code a custom pause that does not use SceneTree's pause.

In this case it would be nice to have the option for the Scenetree.pause to only affect logic rather than physics: figuring out how to pause all the logic is non-trivial (what if an object already has a set_process(false) and you try resume it. What if an object has call_deferred() etc.). Perhaps splitting the SceneTree.paused" into SceneTree.pause_logic and SceneTree.pause_physics would mean that only the physics handling has to be done manually (as TheYokai suggests, this is likely to be done by making some objects Static).

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
