### ISSUE TITLE
Alternative way to define SpotLight's cone

### ISSUE THREAD

**Issue by 2plus2makes5** [godotengine/godot#24765]
Right now the setting of the cone of a spotlight is troublesome for me, for me the most important part of a spotlight is the "circle" it projects(the circle you can see in the editor) and where it's projected, actually if you alter the length then the circle changes its size, if you alter the angle then the circle goes back or forward.

I don't know if for you it's the same but i would like the circle to be constant, if i alter the length i want the circle to keep its size, if i alter the angle i don't want the circle to go back or forth.

I hope i was clear.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
