### ISSUE TITLE
KinematicBody2D doesn't move unless it has a CollisionShape attached

### ISSUE THREAD

**Issue by alforiumstudios** [godotengine/godot#24775]
**Godot version:**
Godot 3.1 alpha 3 / alpha 4 / alpha 5

**OS/device including version:**
Manjaro Linux

**Issue description:**
Since alpha 3, KinematicBody2D nodes can only be moved when they have a CollisionShape attached to them. I don't know if this is the intended behavior, but, if it is, there should probably be a clearer warning somewhere. Perhaps an error message of some sort? It can be a breaking change for some projects and it isn't simple to figure out.

**Steps to reproduce:**
Create a KinematicBody2D and try to use the mode_and_collide() function. The node won't move unless it has a CollisionShape attached.

**Comment by alforium** [comment]
I've been making some tests and this change has broken my current project's movement system completely, since I use a TileMap grid to check the position of KinematicBodies instead of actual collision. I'd vote for keeping CollisionShapes optional, as they've been until now.

**Comment by timoschwarzer** [comment]
@alforium
1. I think the editor warns you when not having a collision shape attached to your kinematic body.
2. Which advantage does a KinematicBody2D have over a simple Node2D?

**Comment by alforium** [comment]
Yes, there's been a small warning in the node tree for a while... since Godot 3 launched, I think? But, despite the warning, until now it wasn't actually necessary to have a CollisionShape attached, that's why the problem didn't register with me. It's not a very visible warning either. My player and objects just suddenly stopped moving and I didn't know why.

I know I could also use a Node2D, but I've been using KinematicBodies since the beginning because it makes sense from a conceptual perspective (they're bodies that will be moved around, with or without collision handling) and move_and_collide() is very convenient. The thing I like the most about Godot is that you can achieve the same result in a myriad different ways and adapt the workflow to your tastes. :)

I see this has been marked as a bug, thanks! I'll stick to alpha 2 for the moment.

**Comment by timoschwarzer** [comment]
@alforiumstudios 

> move_and_collide() is very convenient

How do you use `move_and_collide()` without a collision shape?

> I've been using KinematicBodies since the beginning because it makes sense from a conceptual perspective

It does not make sense to me because a physical body without an actual _body_ doesn't seem right for me.

**Comment by alforiumstudios** [comment]
You're right. I'll admit that my use of KinematicBody2D is hacky and unnecessary, but I don't want to flood this issue with dissertations on my bad coding habits, haha. If this is a bug, then I'm happy because I won't have to change anything in my code, and if it's the intended behavior, then I'll find a way around it. I just wanted to report it in case it was useful.

Thanks for everything!

**Comment by vinterskog** [comment]
Can't see how it would make sense conceptually to be unable to move a body just because it doesn't have a collision shape. I mean, even if it had one, you could just disable it and the body would still move, right? Surely this is a bug.

**Comment by reduz** [comment]
This should definitely not happen, seems like a bug
