### ISSUE TITLE
CSG auto unwrap feature and UV mapping editing

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#24799]
Godot 3 alpha 5

CSG with a texture applied, when it's scaled in one axis , gets the texture deformed, assets are not usable.
Some option to auto unwrap when a CSG object is scaled in some axis would make CSG something usable with texture to create game assets.
Something like Unity Probuilder plugin, that keeps constant UV mapping units and auto unwrap.
Another feature for CSG would be like Unity Probuilder, some UV editor tool to change UV mapping when needed.

One issue is the default cylinder UV map is not good.
It's not uniform on UV and cylinder caps should be top down view flat mapping.
The auto unwrap option would resolve such issues.

**Comment by Calinou** [comment]
I think @Ace-Dragon is referring to the [triplanar mapping](https://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html#triplanar-mapping) option in SpatialMaterial.

**Comment by DevMagicLord** [comment]
> 
> 
> I think @Ace-Dragon is referring to the [triplanar mapping](https://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html#triplanar-mapping) option in SpatialMaterial. Keep in mind it has a performance cost, which means it should be used only when necessary.

This is why auto unwrap with some option values like angle for auto seams, would be a good option to automatically unwrap the mesh to avoid deformations.
Once unwrap is made there is no need for triplanar shader that have big GPU cost.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
