### ISSUE TITLE
Godot should prompt a dialog when an inherited scene has orphan nodes due to a change in the parent scene

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24817]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
11d77386

**Issue description:**
When working with scenes inherited from external created files (escn, collada, etc.) if the hierarchy is changed externally (fox example in blender) and there are nodes instanced inside the inherited hierarchy, all those nodes are forever lost. I believe Godot has the ability to recognise if there are orphan nodes in a tscn file.
In my specific case, I could not use the most updated escn file, since i was forced to choose between losing all the logic in my tscn file vs. taking the updated model. Of course this can be worked around by not changing the hierarchy in the modeling software, but this method makes the pipeline extremely more fragile, since the loss of the work is silent.
**Related to #16650 #19520**

**Proposal**
If there are hierarchy changes that leave nodes orphan, Godot should prompt a dialog similar to the one for broken dependencies to allow the user to give a new position in the hierarchy to the nodes that would be, otherwise, lost. It would be great if the ability to reparent the nodes is present also for the non orphan nodes (as their position in the hierarchy might have changed)

**Comment by bojidar-bg** [comment]
I agree, and loss of work is bad, especially while doing refactoring (since that acts as a stopping force for fixing badly-spelled names, etc.).

IMO, being able to add nodes, instance scenes, save branches as scenes, or outright delete obsolete nodes would all be nice additions to the broken inheritance dialog.

**Comment by girng** [comment]
oh yeah. experienced this plenty of times just couldn't write it out / explain it. definitely +1 for the warning

**Comment by Flavelius** [comment]
i had this happen to me and wanted to open an issue, then i found this. 
The way unity handles deleted parent nodes from up in the inheritance is it just moves the orphaned children up the hierarchy which i think is a good compromise.

**Comment by Flavelius** [comment]
This is still a huge issue in 3.2.4.rc3, which makes working with inherited scenes quite meaningless (having to ignore a main feature that should be one of godots strengths).

https://user-images.githubusercontent.com/8841352/110289564-e457d100-7fe9-11eb-8cce-a65c0679bf16.mp4

[BugProject.zip](https://github.com/godotengine/godot/files/6099662/BugProject.zip)

**Comment by Calinou** [comment]
reduz has been reworking the 3D workflow to not rely on inherited scenes anymore, so this may be less of an issue in 4.0.

**Comment by Flavelius** [comment]
From reading this https://github.com/godotengine/godot-proposals/issues/1823 it sounds like one way to handle this in 4.0 will be dummy nodes, this sounds like an okayish compromise, but is not a fix (and still leaves 3.2 in a buggy state). In unity renaming and moving children that are 'inherited' in variants works just fine (no problems afterwards), so logically this is doable; i hope someone addresses this for godot as its detrimental to an iterative (standard) workflow.

**Comment by markdibarry** [comment]
I'm not sure if this is the same issue, but I noticed that when a base scene's node is renamed, it's _non-distructive_ to inherited scenes, because no inherited `.tscn` file is changed. This means that every inherited scene file retains all the information for the node hierarchy prior to the change (it just incorrectly references the old name, since it wasn't updated) and is inherently broken until resaved. Resaving ironically "fixes" it by overwriting and destroying the saved information. This is easily avoidable, though. All that needs done is to rename the `[node name="OldNodeName"...` portion to the correct name in the inherited `.tscn` files, preventing data loss. This is very tedious to do manually, but I imagine would be an easy bug-fix to implement as an automatic process when renaming.
