### ISSUE TITLE
Instanced scene child nodes are not displayed when selecting a NodePath

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#24840]
**Godot version:**
3.1alpha5

**Issue description:**
NodePath selection dialog does not allow to select a child of an instanced scene unless "editable children" is turned on.
In my case, i need to reference a special camera that belongs to an instanced scene.
My levels have a fairly similar structure, but in order to keep the project more solid and flexible I use NodePath and not direct referencing (with $Object).
Every time i create a level and i want to reference that camera i need to 
1. Tick on editable children for the camera
2. Assign the nodepath to the camera
3. Tick off editable children.

If every node would be selectable in the NodePath dialog, I could spare quite some clicking and scrolling (expecially when the camera and the nodes i want to assign it to are far away in the level hierarchy)

**Proposal:**
Show also child nodes of inherited scenes in some way (by default, add a checkbox, etc...)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
