### ISSUE TITLE
Allow export(enum, FLAGS)

### ISSUE THREAD

**Issue by isaacremnant** [godotengine/godot#24927]
**Godot version:** 3.1

**(very low priority) Feature request:**
It would be very useful to be able to export enums but have them behave like FLAGS. Basically, I would like to replace:
```
enum TYPES {type1=1, type2=2, type3=4, type4=8, type5=16}
export(int, FLAGS, "type1", "type2", "type3", "type4", "type5") var type_combo
```
with a "shorthand" like
```
enum TYPES {type1=1, type2=2, type3=4, type4=8, type5=16}
export(TYPES, FLAGS) var type_combo
```

**Comment by bojidar-bg** [comment]
`export(Enum, FLAGS)` is already supported, but it does not work very well due to supporting only enums such as:
```
enum Enum { bit_1, bit_2, bit_3 }
```
instead of:
```
enum Enum { bit_1 = 1, bit_2 = 2, bit_3 = 4 }
```

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
