### ISSUE TITLE
Mono: Input.Connect() doesn't exist 

### ISSUE THREAD

**Issue by exts** [godotengine/godot#24953]
**Godot version:**
3.1 Beta1 (probably every version)

**OS/device including version:**
Windows 10

**Issue description:**
If you try to call `Input.Connect()` anywhere it says `Input does not have a Connect definition.`

![image](https://user-images.githubusercontent.com/16387107/51078986-bf26dc80-1684-11e9-963a-7dfcf92e7c70.png)

**Steps to reproduce:**
1. Try adding a joystick connect to any script using this line:
```
Input.Connect("joy_connection_changed", this, nameof(MyMethod));
```

2. Shouldn't compile and auto-completion won't work.

This should exist though because there is a joystick connection signal http://docs.godotengine.org/en/latest/classes/class_input.html#signals

**Comment by piratesephiroth** [comment]
wow, `Input `seems to be inheriting stuff from mscorlib's System.Object instead of Godot.Object...

Here's a list of all the broken classes:
`AudioServer`, `ClassDB`, `Engine`, `Geometry`, `GodotSharp`, `IP`, `Input`, `InputMap`, `JSON`, `JavaScript`, `OS`, `Performance`, `Physics2DServer`, `PhysicsServer`, `ProjectSettings`, `ResourceLoader`, `ResourceSaver`, `TranslationServer`, `VisualServer`

**Comment by neikeq** [comment]
@piratesephiroth every class is derived from `System.Object` in C#.

The way we went with the singleton objects from that image is a static class instead of the singleton pattern. The reason for this is because `Input.Instance` could be too verbose to write. I didn't think any of these classes would declare signals.

The solution I'm thinking of is keeping the current way of doing it and also using the singleton pattern. e.g.: `Godot.Input` would be a static class but it would also have a `Instance` property of type `Godot.Singletons.Input`. The latter inherits from `Godot.Object` as expected.
This way we can keep the shorter version `Input.IsActionPressed("...")` while relying on the other one for this kind of use cases `Input.Instance.Connect(...)`.

**Comment by neikeq** [comment]
Can you check if #26071 does what you need? In the end I went with `Singleton` instead of `Instance` for the property name, as the latter was conflicting with `ClassDB.Instance` (although this method may be renamed in the future to `ClassDB.Instantiate`).

The type of the returned instance is `Godot.Object`.

This may change in 4.0 to something better, but for now this should be enough.

**Comment by exts** [comment]
Works!
