### ISSUE TITLE
Reduce data structure padding

### ISSUE THREAD

**Issue by lupoDharkael** [godotengine/godot#24956]
Some classes in Godot could have better structure aligment for example declaring boleans consecutively so the compiler can pack up to 8 in one byte and save memory.

I know this is a micro-optimization but it could be considered as in most cases it doesn't increase complexity nor deteriorate readability. 

There are some cases where it is not worth it as in parts where the declaration of variables are grouped for clarity in some contexts.

This would be an easy contribution for junior devs.

**Comment by akien-mga** [comment]
I doubt @reduz will like this proposal, but we'll see :)

> This would be an easy contribution for junior devs.

No, that's an important design decision that should be made by core devs, not new contributors.

**Comment by lupoDharkael** [comment]
Sure, there are changes that would require high understanding of memory alignment depending on the OS but there are easy ones too.
I don't think this is realy that important after all but even if someone does it wrong it can be reviewed (if @reduz agrees with the change).

**Comment by aaronfranke** [comment]
Do you have any specific changes in mind? Which structures and/or classes could be optimized?

**Comment by lupoDharkael** [comment]
I think it is only worth it in core types. There are very basic examples, if you group the `bool` member variables of the class `Object` it goes from 232 Bytes to 216 Bytes on my machine (debug build). It could sound very little benefit but a game can have a lot of instances of the class Object and the change required in the code is very small.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
