### ISSUE TITLE
Script Editor focus goes to Inspector panel

### ISSUE THREAD

**Issue by massanchik** [godotengine/godot#24979]
**Godot version:**
3.1 beta1

**OS/device including version:**
Windows 10 and OSX

**Issue description:**
When typing in editor, it losing focus

**Steps to reproduce:**
I'm currently doing step by step tutorial -> Your First Game
I have "export (int) var speed" in Player.gd and typing _process part of the code.
While typing, editor highlites errors("velocity.y -=" -> error), and when I finish line("velocity.y -= 1")
it removes the error as well as focus.
Focus goes to Inspector panel on my speed property.
So when I continue tiping(not aware of losing focus):
on osx my typing goes to speed property field in the insptector panel.
on windows my typing goes nowhere.

And not only with errors. After any text editing operation, focus, after couple of secs, goes to inspector.

**Minimal reproduction project:**
any project

**Comment by reduz** [comment]
This feels odd, if anyone can reproduce and bisect when this started happening, would be very appreciated.

**Comment by massanchik** [comment]
I've encountered this issue on both my windows and mac machines

**Comment by slapin** [comment]
I confirm this happens sometimes, very annoying with undo.  But reproduceability is random.

**Comment by isaacremnant** [comment]
I confirm this on Linux 09d0909 and I can reproduce it reliably.
1. Have the node in the inspector and the attached script in the text editor.
2. Type/Paste `export(bool) var test`. The inspector will steal the focus when it adds a new script variable.
3. Click back into the script and type a few letters. The inspector will steal focus again.

Seems the problem is the inspector grabbing focus when it adds a variable but this doesn't turn off after the first parse.

If you then typo var->va, the script won't parse. Then va->var will parse but since the inspector doesn't change, it doesn't steal focus anymore.

**Comment by somnivore** [comment]
https://github.com/godotengine/godot/issues/22305
