### ISSUE TITLE
Editor gets laggy and unresponsive on high DPI monitor

### ISSUE THREAD

**Issue by grusad** [godotengine/godot#24985]
**Godot version:**

 Godot 3.1 Beta 1

**OS/device including version:**

iMac Retina 5k, 27-inch Late 2015. OS Mojave v.10.14.2.
- AMD Radeon R9 M390 2048 MB
- 3,2 GHz i5

**Issue description:**

When using the editor in GLES3 the editor gets very unresponsive. When using it in GLES2 it gets more responsive but still not as good as in the stable version 3.0.6. 

Moving the godot application from my 5k main monitor to my secondary monitior with less resolution the problem goes away. 
Seems to be a problem with high DPI monitors. Still, the problem does not exist in the stable version 3.0.6.

**Steps to reproduce:**
Open an empty or nonempty project, navigate to the 3D tab. Play around with the editor -> laggy result.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
Note that you can enable half-resolution rendering by clicking the **Perspective** button in the top-left corner of the 3D editor.

I don't know what would cause this regression though, perhaps it's related to the 2D rendering performance (see https://github.com/godotengine/godot/commit/02ffc59270f48dc2ea52ae911bbcb80cf15168cf)? You could try compiling the `master` branch or download a nightly build from [here](https://hugo.pro/projects/godot-builds/), and see if the issue is fixed there.

**Comment by grusad** [comment]
Ok, so by checking the **Half Resolution** it sure fixed the problem, but it still does not need to be enabled in the 3.0.6 version.

Tried the nightly build but still the same problem.

**Comment by grusad** [comment]
Well.. beta 4 seems to be working just fine now... :)

**Comment by akien-mga** [comment]
Is this still reproducible in latest 3.2 builds?

**Comment by Calinou** [comment]
Closing due to lack of response from OP.
