### ISSUE TITLE
Flags in AnimatedTexture, ProxyTexture, MeshTexture and GradientTexture can't be set

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#25045]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/51275087-3f28ab80-19d1-11e9-9d07-1b5a69783710.png)

**OS/device including version:**
Windows 64

**Steps to reproduce:**
Create a new AnimationTexture resource, try to change the flags - they can't be set.

**Comment by akien-mga** [comment]
Both `AnimatedTexture` and `ProxyTexture` have an empty `set_flags`, and I think this might have been on purpose, as they're proxy containers for other `Texture` resources (and only the latter can set their own flags).

There are two solutions:
- Either implement `set_flags` and make it override the flags of all frame textures
- Or override the `flags` property inherited from `Texture` to hide it

**Comment by akien-mga** [comment]
There are some more Texture types where flags can't be set in 3.2.x, like GradientTexture, ExternalTexture, etc. See `scene/resources/texture.{cpp,h}`.

There's a clear UX issue that those flags are exposed but not usable, which is fixed in 4.0 as flags are no longer on the Texture resources, but as properties of CanvasItems and/or materials.

For 3.2.x, the main question is whether this is an actual use case for implementing flags for some of those types - and if so how this should be done. If this issue is only about the UX problem, it could be closed as it's solved in 4.0.

**Comment by KoBeWi** [comment]
Textures no longer have flags in 4.0.

**Comment by jamie-pate** [comment]
> There are some more Texture types where flags can't be set in 3.2.x, like GradientTexture, ExternalTexture, etc. See `scene/resources/texture.{cpp,h}`.
> 
> There's a clear UX issue that those flags are exposed but not usable, which is fixed in 4.0 as flags are no longer on the Texture resources, but as properties of CanvasItems and/or materials.
> 
> For 3.2.x, the main question is whether this is an actual use case for implementing flags for some of those types - and if so how this should be done. If this issue is only about the UX problem, it could be closed as it's solved in 4.0.

My use case is creating a gradient texture that repeats.. I guess that's just not an option?

**Comment by KoBeWi** [comment]
Just enable repeat on the node that you want repeated (Sprite2D, TextureRect etc)

**Comment by jamie-pate** [comment]
I don't think MeshInstances have that?

**Comment by KoBeWi** [comment]
I think for 3D there is a flag in the StandardMaterial

**Comment by jamie-pate** [comment]
The SpatialMaterial in 3.5 doesn't have it.

I achieved my goal by making the uv_scale 0.5 and animating the uv_offset to values between 0 and 0.5 to make it look like it repeats.. but it's not as simple as a repeat flag, and it jumps if you don't have the first half of the texture exactly matching the 2nd half.

If it's fixed in 4.0 obviously that's the priority, and I guess my use case is not a priority since there's a workaround for 3.5 :D
