### ISSUE TITLE
Be able to play in the editor by piping godot into another process

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#25089]
**Godot version:**
3.1 beta1

**OS/device including version:**
4.20.3-arch1-1-ARCH

**Issue description:**
Lately I am having a good amount of issues with rendering and it would be very comfortable to launch godot via renderdoc with renderdoccmd capture directly from the editor.

**Proposal**

It is currently possible to specify custom run args. It would be very nice to have an integrated way to maipulate the command line command in a way that allows wrapping the godot launch command in a bash pipeline.

**Comment by voithos** [comment]
Could it also make sense to integrate directly with renderdoc? According to their website (https://renderdoc.org/), there's engine-level integration with Unreal and Unity already, so it seems integrating with Godot could be possible.

**Comment by QbieShay** [comment]
Turns out that spawning the editor with renderdoc also makes the process spawn by it be attached to renderdoc. Leaving this open anyway because someone might need other processes (Looking in particular at optimus)

**Comment by Calinou** [comment]
> It would be very nice to have an integrated way to maipulate the command line command in a way that allows wrapping the godot launch command in a bash pipeline.

What about using a `%commmand%` placeholder like Steam's run arguments? This way, you could write `renderdoc | %command%` in the custom run arguments.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
