### ISSUE TITLE
ResourceLoader.load() will not reload if using the Godot Editor

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#25083]
**Godot version:**
3.0.6

**OS/device including version:**
Windows 10

**Issue description:**
When using ResourceLoader.load() to reload an asset, it will not reload it until the Godot Editor has reimported the asset.

**Steps to reproduce:**
Execute ResourceLoader.load() repetitively (with a timer for example) on the exact same path. While this is happening, edit the file - for example, edit a .png in MSPaint with an obvious change. Save the PNG, and observe that nothing changed with the sprite. Then, bring the Godot Editor into focus, thus triggering a checksum calculation, resulting in the reimporting of the file. Then, observe that the sprite has indeed changed after this intervention.

EXPECTED:
The sprite should be updated in-game immediately upon saving, instead of after the user clicks on the Godot Editor.

**Minimal reproduction project:**
Create a scene with a sprite, and give it the following script (example attached):
[Sprite.zip](https://github.com/godotengine/godot/files/2771559/Sprite.zip)
While it is executing, edit icon.png and save. You won't observe a change until the Editor (not the game) gets focus.

	extends Sprite

	#Target sprite to reload
	const _SPRITE = "res://icon.png"
	
	func _ready():
		
		#Start reloading the sprite
		_reload_sprite()
		
	func _reload_sprite():
		
		#Reload the sprite using ResourceLoader
		var _sprite = ResourceLoader.load(_SPRITE, '', true)
		
		#Set our texture
		texture = _sprite
		
		#Wait and reload the sprite
		yield(get_tree().create_timer(1.0), "timeout")
		_reload_sprite()

**Comment by mrcdk** [comment]
What are you trying to do? Updating the resources is something that the editor does automatically. You don't have to anything else. Also, your script won't do anything in the editor because it's not a tool script so I'm not sure what you want to do.

**Comment by DevinPentecost** [comment]
This is for a godot application that acts as a image preview - not as a tool/plugin within the editor itself.
ResourceLoader.load() re-uses the .import produced by the Godot Editor instead of actually reloading the asset. Since it must rely on the Godot Editor for the import, it cannot run 'by itself' and instead must wait for the triggered auto-import from the editor to reflect any changes in the asset.

**Comment by mrcdk** [comment]
If you are trying to make an external application then you'll need to load the file yourself because after you export the project the resources won't be available for edition (only the imported converted resources will) and, in some platforms, the resource folder will be read only.

To load an external image something like this should work (haven't tested the code but it's something like that):

```gdscript
var file = File.new()
file.open(image_path, File.READ)
var bytes = file.get_buffer(file.len())
file.close()
var img = Image.new()
img.load_png_from_buffer(bytes) # or img.load_jpg_from_buffer()
var imgtexture = ImageTexture.new()
imgtexture.create_from_image(img)

sprite.texture = imgtexture
```

**Comment by DevinPentecost** [comment]
Hmm, I must be mis-interpreting the signature of ResourceLoader.Load. There isn't any documentation for it:
Resource load ( String path, String type_hint=”“, bool p_no_cache=false )

What is the purpose of no-cache in this context then?

I'll try your example and see if it works for my purposes.

Thanks

**Comment by mrcdk** [comment]
`ResourceLoader` can only load resources, what I'm understanding from your issue is that you want to load external files, not resources, and that's not a task `ResourceLoader` can do. You need to load the file manually.

In godot, resources aren't the same as files. 

A resource links a file with one or more converted files. For example, `res://icon.png` doesn't point to the file `my_project/icon.png` but it will point to the converted files something like `my_project/.import/icon-47---.stex` and `my_project/.import/icon-12---.stex` which are the files that the engine has created from your file and they are the ones that it will use at runtime.

When you export your project `my_project/icon.png` won't be in the exported into `pck` but only the `icon.png.import` file pointing to those converted files.

**Comment by DevinPentecost** [comment]
Got it - looks like I'll find another solution.
However, seems like this is great information to be included in the documentation:

http://docs.godotengine.org/en/3.0/classes/class_resourceloader.html#class-resourceloader-load

Thanks

**Comment by DevinPentecost** [comment]
Closing, as using solution @mrcdk suggested does the trick.
