### ISSUE TITLE
Add a syntax shortcut for groups in GDScript

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#25139]
**Issue description:**
As a lazy programmer, I'd like to have the least verbose way of accessing frequently needed collections of nodes (or individual nodes) in my projects. A great way to get to these nodes is with groups, but messing around with groups tends to be more verbose than I'd like.

    # 1. long method name
    # 2. need to use a string
    # 3. have to use array syntax to access the first value (not a dealbreaker, but...)
    var player = get_nodes_in_group("players")[0]

I would prefer it if, in the same way that we have `@test` as a shortcut for `NodePath("test")` and $test for `get_node("test")`, I'd like it if it were possible to have the same kind of thing for groups. Just as an example (not saying it would have to be this way), having a modulus operator as a prefix, double if wanting the first entry:

    var players: Array = %players # get_nodes_in_group("players")
    var player: Node = %%players # automatically fetches the value at index 0, null if empty
    if player in %players: # would do `is_in_group()` behind the scenes?
        # do something
    %players += player # add_to_group("players")
    %players -= player # remove_from_group("players")

What do you guys think of the idea (in general)?

Edit: changed example so that %players portrayal as an Array value is more consistent.

**Comment by Zireael07** [comment]
In general, the idea is very good. Groups are used a lot in larger projects, and especially so for the first entry, at least in my experience.

**Comment by Zylann** [comment]
I don't find it used as much as `get_node` to justify another language construct. I don't use groups that much though, and even for `get_node` I never use the `$` because I prefer being explicit about what's actually going on.

`%` can also conflict with the modulus operator.

**Comment by groud** [comment]
Once again, trying to access ressources globally is not a good thing. What you propose is a really bad habit and would be very inefficient. 

In general, searching the whole tree for specific kind of nodes ( as there is no general structure to store nodes in each groups, groups being simply a list of string associated to each node) does go against the purpose of composition.

**Comment by willnationsdev** [comment]
@groud 
> Once again, trying to access ressources globally is not a good thing. What you propose is a really bad habit

Is your recommendation to just never use groups at all? I'm confused...

> would be very inefficient.

> In general, searching the whole tree for specific kind of nodes (as there is no general structure to store nodes in each groups, groups being simply a list of string associated to each node) does go against the purpose of composition.

Not sure what you mean. The SceneTree's [Group struct](https://github.com/godotengine/godot/blob/master/scene/main/scene_tree.h#L98) maintains the vector of the nodes in the group, and the groups are [indexed by name in a Map](https://github.com/godotengine/godot/blob/master/scene/main/scene_tree.h#L121). It's decently efficient, especially if there the group's size is small, nor does it "[search] the whole tree" at all.

This would merely be a quality of life improvement for users who use groups. Nothing more.

**Comment by groud** [comment]
Ah indeed sorry, I was wrong on this one. There is indeed a structure to store the nodes in each group. But still, that's on a per-scene basis and I am not sure it can be extended to a runing game. If you have recursive inclusion of scenes, it will be as inefficient as the find_node function (which reduz did not wanted to merge initially due to performance) 

But also, I don't think accessing groups need a GDscript syntax sugar. It is not  needed as often as the get_node function.

**Comment by akien-mga** [comment]
IMO, too much sugar is bad for the health of your codebase. I have a very hard time understanding what the proposed syntax does in the code sample of the OP.
I'm not saying this is a *completely* bad idea, but if you want do advocate for such a feature, don't make an example where both local variable, for loop iterator *and* group all share the same name...

**Comment by willnationsdev** [comment]
> And what is even this?
>     player += %player # add to group
>     player -= %player # remove from group
> `player` is a local variable, and you are *appending* the whole group to it. It's very counterintuitive.

I was simply providing an example that mirrored the existing Node methods.

    player.add_to_group("player")
    player += %player # as in "add group<player> to the Node reference stored in the 'player' variable"
    playret.remove_from_group("player")
    player -= %player # same concept. It's a reference to the individual string tag for the group.

> don't make an example where both local variable, for loop iterator and group all share the same name...

Point well made. I'll adjust the content accordingly.

**Comment by willnationsdev** [comment]
@akien-mga I updated the example. Does that version make it more clear?

**Comment by vnen** [comment]
My problem with syntax sugar is that they are detrimental to readability. The more syntactic structures we have, the least they are proportionally used, since it requires a cognitive effort to remember them all. So in the end they are not used often (because people don't know about it) and makes the code hard to read (people have to check the docs because they already forgot it).

Moreover, I don't think that groups are used enough to justify adding a special syntax for it. Sure *you* may use it a lot, but I'd say most of projects use it sparingly.

I also want to point out that the order of the nodes in a group is not guaranteed (I've seem problems with that assumption before), therefore a syntax for "first in group" might not be what people expect.

**Comment by willnationsdev** [comment]
@vnen Fair points. Didn't realize the order was unreliable though. Aren't they Vectors? Why does that happen?

**Comment by timoschwarzer** [comment]
I, too, think that this syntax sugar is not needed. $ for get_node is another thing because you can't really make a game in Godot without using get_node once and nested node paths can be long sometimes, so saving characters here is a clear advantage. For groups though, as there isn't any nesting, I don't see the point in introducing another syntax sugar to the language. The only reason here is laziness, and that should be fixed with enhancing code completion (e.g. smart abbreviations - typing "%<tab>" expands to "get_nodes_in_group()" and sets the cursor between the parentheses) and not by altering the language.

**Comment by Soaku** [comment]
Why use a sign character for this? I don't think groups can be easily compared to nodes, `$Node` is a clean and understandable syntax, but lets limit the syntax to only one structure of this kind, because it will quickly get confusing.

What I might suggest, is to add a more OOP version of groups:

```gd
var players = Group("player")
players.add(node)
players.call("method")

# Iterable
for player in players: ...

# Index
players[0]
```

Btw, regarding the syntax for getting the first item... I think that's quite missing the point of groups. It's an array, not a variable. Second, `[0]` is quick to type, readable and known syntax.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
