### ISSUE TITLE
Gamepads not working correctly on Android

### ISSUE THREAD

**Issue by alessiodeltrecco** [godotengine/godot#25151]
**Godot version:**
Godot Engine 3.1.beta1.official

**OS/device including version:**
OS: Android 8.0.0

Device: Honor 9 Lite 
Model: LLD-L31

**Issue description:**
I've connected a bluetooth gamepad to my Android device and it gets recognized and it's usable from another app, but my Godot app completely ignores it.
So i've tried another gamepad, this time a USB one connected with a USB OTG adapter, and the analog X and Y axes seems to work with Godot but not the buttons.
Tests on Android with Joypads Demo / Tool from the Templates gives same results.

I've noticed that the bluetooth gamepad gets recognized as a keyboard from Android OS and on the USB one only buttons are not working, so i think the problem is related only to buttons and not to axes.

Of course I tested the gamepads with other applications to make sure it was not a hardware problem.

**Steps to reproduce:**

Connect a bluetooth or USB gamepad to an Android device
Install Joypads Demo / Tool from the Templates to an Android device
Check what's working

**Minimal reproduction project:**
Joypads Demo / Tool

**Comment by akien-mga** [comment]
I just synced gamepad bindings in #25188, could you try again with the current master branch and/or 3.1 beta 3 when it's out?

**Comment by alessiodeltrecco** [comment]
Thank you Rémi

i've repeated the test with the master branch (i've rebuilt both Godot and the Export Template for Android) but unfortunately the problem is still there...

In my application i've added a label to display debug information with this code (GDScript):

`func _input(event):get_node("Label").set_text( str( event ) )`

And this is what appens when i hit a button on the USB gamepad:

![screenshot_20190123-000919](https://user-images.githubusercontent.com/11901319/51573355-2aed1e80-1ea9-11e9-9518-b66db37c7b79.jpg)

the event type is InputEventKey instead of a InputEventJoypadButton and the value keeps increasing if i longpress the button.

The axes are working as before.
The bluetooth gamepad is still completely ignored.

**Comment by alessiodeltrecco** [comment]
Ok, i've done a lot of testing in these days:

I've built SDL2 ControllerMap application on Android and tried to get a decent mapping for my controllers.
To speed up my tests i've modified the **gamecontrollerdb.txt** file contained in the **main** folder and i verified that changes were reflected in **default_controller_mappings.gen.cpp** when building Godot for X11.

Unluckily, nothing changed, my bluetooth controller is still completely ignored and for the USB one there is no way to get buttons working. No matters what button i push, it gives me always an InputEventKey with scancode 183 (always 183).

This are the controllers mappings i obtained with SDL2 ControllerMap:

05000000790000000100000000003f00,DragonRise Inc. DragonRise USB Gamepad,a:b20,b:b21,back:b28,leftx:a0,lefty:a1,leftshoulder:b26,rightshoulder:b27,start:b29,x:b23,y:b24,platform:Android,

050000005c0a000002450000ffff3f00,Trust GMP-02,a:b0,b:b1,back:b4,dpdown:b12,dpleft:b13,dpright:b14,leftshoulder:b9,x:b2,y:b3,platform:Android,

For the Trust GMP-02 (the bluetooth gamepad) maybe is missing the mapping for the **start** because SDL2 ControllerMap acts a little bit strange on Android and sometimes it skips by itself the configuration for some buttons, but i don't think this is the problem...

I've noticed that The DragonRise USB Gamepad mapping is already there for Linux (even if values, like guid, are different) indeed my application works very well on the desktop build with this gamepad.

Another thing that seems strange to me is that if i connect the USB gamepad then start the app on Android, the gamepad is not recognized, conversely if i start the app before plugging in the gamepad it works (only the axes as always).

**Comment by alessiodeltrecco** [comment]
Later today i will try to write a GDScript to understad what joystick Godot is seeing on Android.

I think that using get_connected_joypads, get_joy_guid, get_joy_name, is_joy_known and eventually add_joy_mapping methods of Input API could give a better understanding of what's happening...

**Comment by alessiodeltrecco** [comment]
No way...
I modified the Joypad Demo and thanks to that i noticed that Godot sees a different GUID for my DragonRise USB both in Linux and Android.

Linux GUID: 
Android GUID:

So i wrote this values to gamecontrollerdb.txt in their respective sections, done rebuild for everything and:

on Linux the mapping gets recognized, indeed the label next to Known (based on Input.is_joy_known) in the following screenshots says YES

on Android the same label says NO, even if the GUID is correct

**Comment by pjlg** [comment]
Hi there,

I have got the same reason with two USB gamepads - both of them are working correctly on Android with a NES emulator, but send always the scancode 183 via the InputEventKey (instead of expected InputEventJoypadButton) event in my godot (v.3.1.1) game code on Android.

Are there fix ambitions for next godot releases - may you can put it to the 3.2 milestone list
   https://github.com/godotengine/godot/milestone/8

Thanks :100:

**Comment by wombatstampede** [comment]
I had also a closer look to the Android Joystick code. (as of Godot 3.1 release)

Error 1: Joysticks are ONLY seen when they are added (bluetooth on/pairing/usb plug in etc.) while the Godot app runs. This is so because the app doesn't initialize with the existing devices but instead listens on "onInputDeviceAdded" (GodotView.java). In the GodotView constructor (or elsewhere) there should be an iteration of mInputManager.getInputDeviceIds() on startup.
Error 2: In on InputDeviceAdded() there's no check if that device is actually some kind of keyboard/joystick.
Error 3: The result of mInputManager.getInputDevice is not tested for "null" which is a valid result. (Has already been in Godot 2.x and in my apps ANR/PlayStore Error list the java.lang.NullPointerException in GodotView.onInputDevice is one of the most often occuring errors.
Error 4: While godot behaves nice when I connect a Nintendo Pro Controller it simply restarts when I connect some combined Mouse & Joystick controller. "restart()" is a method of the Godot java class. I have absolutely no idea why it does get called...

**Comment by alessiodeltrecco** [comment]
> Error 1: Joysticks are ONLY seen when they are added (bluetooth on/pairing/usb plug in etc.) while the Godot app runs. This is so because the app doesn't initialize with the existing devices but instead listens on "onInputDeviceAdded" (GodotView.java). In the GodotView constructor (or elsewhere) there should be an iteration of mInputManager.getInputDeviceIds() on startup.

Yes, I confirm this behavior: in my tests I always had to connect the gamepad after starting the app

Error 4: While godot behaves nice when I connect a Nintendo Pro Controller it simply restarts when I connect some combined Mouse & Joystick controller. "restart()" is a method of the Godot java class. I have absolutely no idea why it does get called...

And I can also confirm this problem: sometimes connecting a gamepad after launching the app makes it crash

**Comment by wombatstampede** [comment]
I have done some further testing and I get the impression that the restart() after connecting some devices is somehow "intentional" because some screen/keyboard parameters changed, whatever.

I did some hacking on the 3.1release (not 3.1.1!) code to enable gamepad support. This won't fix the restart issue but should have all gamepads/joysticks ready after you called (!!!) OS.set_window_title("some title here").

What? Why that? Yes, I didn't find any way yet to automatic initialize the devices on startup. The creators and init methods in Godot.java and GodotView.java all led to SIGILL when sending a signal about the new input devices back to the godot core. Apparently Godot isn't ready for those callbacks at that time. So for the sake of testing I added the init code to the otherwise unused OS.set_window_title() and call that i.e. during _ready.

I added a zip with the changed files in case anyone wants to clean that up and add it to the master branch.
[gamepad_test.zip](https://github.com/godotengine/godot/files/3137753/gamepad_test.zip)

**Comment by wombatstampede** [comment]
GDScript is more or less platform independent. Therefore you would need something that does the Android OS calls for you. That would normally be a plugin.

I plan to put up a so called pull-request with this update soon (planning this weekend). I hope that it will get accepted. :-)

**Comment by wombatstampede** [comment]
Today, I had a look at the android joystick mappings code.
And the guid which is passed to input->joy_connection_changed is always "".

Therefore there's also being generated an "improvised" GUID in InputDefault::joy_connection_changed which is incompatible with SDL2s guids. So if I see this correctly: Alle SDL2 mappings in Godot  are void. (concerning Android).

The "improvised" uid is composed of the concatenated hex values of the controllers names ascii values (as delivered by i.e. Bluetooth). Maximum is 16 ascii values -> 32 hex characters.

However, you should be able to add your own mappings via Input.add_joy_mapping(). There are only two problems:
- You need to know the exact name with which the controller announces itself in Bluetooth.
- There will be only one mapping possible if two controller have similar

I added an example script of how could that be done. That script receives SDL mappings in an array. Replaces the uid by the "improvised" uid and then 

[android_joycon_mappings.zip](https://github.com/godotengine/godot/files/3145463/android_joycon_mappings.zip)

@alessiodeltrecco could you please be so kind and share your android build (apk) of SDL2 ControllerMap? Perhaps some more people feel tempted to add their own controller.

At a later time a fix might also be useful to actually use the original SDL2 uids inside Godot. I didn't check the SDL2 code yet to retrieve how the assemble their android UID. (maybe InputDevice.Descriptor or similar)

**Comment by alessiodeltrecco** [comment]
Sure, later today, i'll share it.
I think the problem is the improvised uid like you said, i drew the same conclusion when i looked at the code

**Comment by alessiodeltrecco** [comment]
Sorry but these days i'm very very busy, i hope tonight i can find time to share the apk 😉

**Comment by alessiodeltrecco** [comment]
Finally here it is

[SDLControllerMap_JoyPadDemo.zip](https://github.com/godotengine/godot/files/3156644/SDLControllerMap_JoyPadDemo.zip)

The zip file contains app-debug.apk (SDL Controller Map) and Joypads.apk (modified versione of Godot Joypad Demo)

Hope this helps

**Comment by pjlg** [comment]
@alessiodeltrecco Hi! I have tested your Joypads.apk Demo on my Android with USB gamepad - the buttons still not work, like the original-demo from godot...

**Comment by alessiodeltrecco** [comment]
@pjlg 
Of course
The modifies i made were only to see the UID and the name of the gamepad and to extend the number of button from 16 to 30

**Comment by vickylance** [comment]
Amkette Evo Gamepad Pro 2 controller is not working properly in Godot 3.2.1 @akien-mga its showing weird numbers when I move any of the analog sticks. Whereas Xbox controller is working fine
