### ISSUE TITLE
JavaScript.eval(array) returns Null

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#25158]
**Godot version:** Godot 3.1 Beta 1 (in Beta 2 HTML5 Export is not working)

**OS/device including version:** Windows 10 64-bit

**Issue description:**

`JavaScript.eval()` doesn't seem to return array at all.

**Steps to reproduce:**
1. Open any project
2. Paste the **Minimal reproduction ~~project~~ code**
3. Export to HTML5
4. Run it
5. Open DevTools (F12 on Chrome)
6. See `Array: Null`

**Minimal reproduction ~~project~~ code:**

```
print('Array: %s' % JavaScript.eval('[1, 3, 5]'))
```

**Comment by DleanJeans** [comment]
So my workaround is `JSON.stringify()` and `str2var()`:
```
array = str2var(JavaScript.eval('JSON.stringify([1, 3, 5])'))
print('Array: %s' % array)
```

**Comment by eska014** [comment]
Arrays are not intended to be handled as a valid return value, they're not listed in the documentation either: https://docs.godotengine.org/en/3.0/getting_started/workflow/export/exporting_for_web.html#calling-javascript-from-script

The reasion is that there's no intuitive implementation for arrays. For example, what happens when a value appears in an array that can't be represented in Godot?

By the way, if you want to pass a JSON string from JavaScript, you should deserialize it in Godot using the [`JSON`](https://docs.godotengine.org/en/3.0/classes/class_json.html#class-json-parse) class instead of `str2var`.

**Comment by DleanJeans** [comment]
What's the difference between `str2var` and `to_json`?
I used `to_json` at first before switching to `str2var` when I found it.

**Comment by eska014** [comment]
`str2var` and `var2str` are for Godot's own internal format (`VariantParser`), which has some differences to JSON. For example, JSON only supports double-quotes, doesn't support NaN and doesn't support ordered dictionaries.

The JSON equivalent to `str2var` would be `parse_json` or `JSON.parse` (not `to_json`)
