### ISSUE TITLE
Jittering on wall collision.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25247]
**Godot version:**

4f4e46edd539b0c26a6b086aa19c303b10de66b1

**OS/device including version:**

Win10 64-bit

**Issue description:**

Was testing the fix on this issue: https://github.com/godotengine/godot/issues/25181

In the Platformer 2D demo, I ran Robi into the wall, and there was a lot of jittering and when releasing the arrow, sometimes he gets kicked out and changes facing direction.

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/13004169/51587092-49bed580-1ee8-11e9-8965-2205b5ce0515.gif)

**Steps to reproduce:**

Run the platformer demo, run into a wall and release the key.

**Comment by reduz** [comment]
This is not a bug, this is because for some reason I don't remember (this demo is like 10 years old), the wall-corner tile has an angled collision. Feel free to submit a PR fixing this to the demos repo :P
![image](https://user-images.githubusercontent.com/6265307/51601267-acad6e00-1ee2-11e9-8637-832c15c59ab6.png)

**Comment by avencherus** [comment]
XD

Whew.  Quite unexpected.
