### ISSUE TITLE
Editor should have a button/command for reverting all properties of selected instanced scenes.

### ISSUE THREAD

**Issue by hedgehog90** [godotengine/godot#25256]
Currently, if I have a scene with a load of instanced scene objects with different properties and I want to reset them all, the quickest way to do this currently is by manually editing the tscn file in a text editor (within which they are instanced).

Similar to the way Unity allows reverting of prefabs, there should be a button somewhere in the editor, either in the scene context menu or in the inspector to allow all selected scene instances to revert all their properties (and properties of instanced children) except for the root node's Transform.

It's surprising such a function doesn't already exist.

**Comment by eon-s** [comment]
Sounds good, this could be for every node too to reset to defaults (clean the current scene file data for selected node/s) and can be an option on the inspector.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
