### ISSUE TITLE
Be able to sync Path2D/PathFollow2D to physics just like kinematic bodies

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#25291]
Godot has recently taken steps to help ease the development of platformers by adding a feature to kinematic bodies that allow them to [sync to physic](https://godotengine.org/article/godot-31-will-get-many-improvements-kinematicbody). This improved the ability for players to snap to moving platforms without sliding. This was a huge improvement to game development, but I think we can take it further.

I propose that we add this same feature to PathFollow2D so that any children it contains, such as a platform, will be synced with physics. This will allow users to be able to draw any navigation path for a platform to follow, and retain the benefits of the new features.

**Comment by Bombfuse** [comment]
Yah I've tested that and it doesn't work. I think it's because even though the body will sync to physics, the PathFollow2D doesn't SetPosition in sync with physics.

**Comment by kidandcat** [comment]
This is a very common case when creating moving platforms.

**Comment by Bombfuse** [comment]
Would it be possible to add SyncToPhysics on every node? That would allow more flexibility for the user.

**Comment by Bombfuse** [comment]
Any thoughts on this???

**Comment by Calinou** [comment]
@Bombfuse Does it work if you use an AnimationPlayer with playback mode set to Physics to move the PathFollow2D?

**Comment by Bombfuse** [comment]
I currently don't have any bandwidth to test this, is someone else willing to test it?

**Comment by farism** [comment]
It looks like setting playback mode to Physics on the AnimationPlayer doesn't work either.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
