### ISSUE TITLE
Suggestion: Per-project editor settings

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#25293]
I often have more than one Godot project open at a time. In these cases, I like to have different themes in each editor instance, to easily differentiate between them.

I know that there's per-executable configuration (enabled by the `._sc_` file), but I really see no reason to have a bunch of separate executables. Also, the configurations do not follow when we use versioning.

I propose a hierarquical model: allow us to have `._sc_` files in each project, and look for configurations there. Failing that, look for configurations in the executables directory, and finally in the per-user directory (app-data or /.local/share).

That way, we can customize things like the location of ADB per-user, the editor theme per-project and the configuration of specific modules per-executable.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
