### ISSUE TITLE
Discussion: move global buttons in project manager 

### ISSUE THREAD

**Issue by starry-abyss** [godotengine/godot#25305]
**Godot version:**
3.0.6, 3.1-beta2

**Description:**
Each time I open Godot project manager, it makes me nervous.
The very least that might be done to not drown the user in all the buttons is this:

![project_manager_godot_2](https://user-images.githubusercontent.com/11571820/51718242-81975b80-2055-11e9-8549-073b4ea45a36.png)

Besides moving buttons that are not specific to the selected project, I also moved the "Edit" button  down one row (so it's not in the header) and added a "default" highlight to it in this mockup.

The original one from 3.0.6:

![project_manager_godot](https://user-images.githubusercontent.com/11571820/51718178-26fdff80-2055-11e9-900f-711c4167c4eb.png)

**Comment by girng** [comment]
how is having buttons right ontop of the itemlist where the dev usually double clicks it better than having them on the right? if anything, the buttons look better on the right and allows more space on the left and looks less cluttered

also, there is now `a sort field` next to the name field, so it would look even more cluttered up there.

**Comment by starry-abyss** [comment]
Thanks for feedback!

I had no idea double-click was a thing to be honest! However, availability of shortcuts, either keyboard or mouse ones, doesn't justify the messy menu on the right.

So in my situation, if I wanted to edit my project that I didn't open for a month, I needed to skim all of the buttons on the right back and forth several times until I find the right one, because I didn't remember its position and name ("open"? "modify"?? ah! "edit"!).
Ideally, it should stand out and beg to be pressed (as the most frequently useful here).

> how is having buttons right ontop of the itemlist [...] better than having them on the right? if anything, the buttons look better on the right and allows more space on the left and looks less cluttered

Software is meant to be used, not looked at. :P I suggest moving those things on top because they have more priority.
If I'm going to create a "new project", this is the first button I see top-down left-to-right. Else if I want to do something to an existing project, there is then a list and a corresponding menu to the right (without buttons which don't operate on the selected item in the list).

> you should be feeling giddy not nervous! start working on your game!!

Working on my game involves more C++ module (can be run without Godot) work and paper work recently than in-editor work.
I could move the buttons around however I wanted in my private build (or simply make a script so Godot is auto-opening the project in question), but it's not the point of this thread. :)

**Comment by Calinou** [comment]
[Buttons have been reordered in the `master` branch.](https://github.com/godotengine/godot/pull/41569) Take a look at the linked pull request before opening a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
