### ISSUE TITLE
Area2d checks collision multiple times

### ISSUE THREAD

**Issue by ishidex2** [godotengine/godot#25315]
**Godot version:** 3.0.6

**OS/device including version:** Linux Mint 19.1

**Issue description:** Area2d checks collision multiple times

**Steps to reproduce:** execute my code

**Minimal reproduction project:** 
[min.tar.gz](https://github.com/godotengine/godot/files/2795855/min.tar.gz)

**Comment by bojidar-bg** [comment]
**Steps to fix**:
* Use the `_physics_process` instead of `_process`: Area2D's overlapping bodies list is updated every physics frame, not every time you ask it.
* Use Area2D's `body_entered` signal: it is more resilient to frame timings than asking the Area2D for overlaps every frame.

**Steps to better issues in the future**: :smiley:
* Make sure that reproduction steps don't require the sample project to work. That way other contributors don't have to download it in order to check things.
* Submit .zip reproduction projects. It is a way more supported format, on all platforms.
* Write more text! There is nothing like an "obvious" issue, unless it happens every time on every project.

**Comment by ishidex2** [comment]
Thanks
