### ISSUE TITLE
Update ingame default theme for control nodes

### ISSUE THREAD

**Issue by Overblob** [godotengine/godot#25349]
Currently for every control node the theme defaults to the violet-ish one used before for Godot2

I think it could be nice to update the default colors, boxes, etc to match better Godot3's theme.

![image](https://user-images.githubusercontent.com/31958866/51790189-2323c780-2192-11e9-9262-45176c4b1df6.png)

**Comment by Zylann** [comment]
I would note that these themes have two different uses, so making them the same for the sake of it is not really necessary IMO (not saying it shouldnt be done tho).

The editor theme is meant for the editor, and has been designed to be simple, modern and support the global coloring feature in its settings.

On the other hand, the default game theme rather shows each feature of widgets rather than trying to look like a classic modern app. For example, the editor theme is generally flat and has no window titlebars, but the game one does because it clearly shows the presence of that feature. The fact it is different also helps differenciating and shows how customizable it is.

The only main use case I see is when you make editor plugins, because very often the editor theme has different metrics than the default (although it should not matter if you design the UI by using exclusively anchoring rules instead of fixed placements).

I think there was a few comments along these lines in the past when the new theme got introduced, but I can't find them.

**Comment by volzhs** [comment]
there was discussion for it https://github.com/godotengine/godot/pull/8631#issuecomment-298774326

**Comment by volzhs** [comment]
and there was a PR for it too #12718

**Comment by girng** [comment]
i like #12718 too because  if the dev wants to use the main theme they can just do that. however, this is just my opinion. it's not worth much, but i do agree with Zylann and been using the in-game theme for years 

imo the buttons are way nicer and game-like (especially if you change the theme's button_normal.png to a nice color you like). they have the user experience of actually pressing a button. when the editor's buttons are more of a flat design.   i know you said just control nodes in title, but you'd have to change everything or the theme would be wonky :O

**Comment by Overblob** [comment]
Thanks for your feedbacks!

@Zylann I completely understand your sayings.

IMO the default theme for controls is just a placeholder for prototyping. It is meant to be overriden when you skin your game GUI.
So keeping a different default theme for editor and game shouldn't realing matter.

(And, if I'm not wrong the editor theme and default control theme were shared for Godot2.x) :p

In that sense, this issue would be more about homogeneity, because it feels a bit like the theme transition from Godot2 to Godot3 isn't completely finished yet.

**Comment by Calinou** [comment]
I think a good compromise would be to upgrade the default "game" theme to use StyleBoxFlat (with a neutral gray color scheme, independent of the editor theme). I'm not sure if the current editor theme could be used as a base though (due to how it's organized in the code).

**Comment by Calinou** [comment]
I started work on this for Godot 4.0: https://github.com/Calinou/godot/tree/improve-default-project-theme

I can't give an ETA on when I'll open a pull request for it, but here's a sneak-peek of what it looks like currently:

![image](https://user-images.githubusercontent.com/180032/124191881-bc263d80-dac4-11eb-99eb-9b19d5900213.png)
