### ISSUE TITLE
Using enum as export hint fails for first element, returns default value

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#25357]
**Godot version:**
3.1beta 2

**OS/device including version:**
linux 64, windows 10 64

**Issue description:**
variables exported with enums as export hint are not properly set for the first element

**Steps to repdoduce:**
- export an int using: `export(int, "foo", "bar") var my_var`
- set to foo in the inspector
Expected:
my_var == 0
Actual:
my_var == null

- export an int using: `export(some_enum) var my_var`
- set to first element of enum in inspector
Expected
my_var == 0
Actual:
my_var == null

What the script is doing is returning the default value(null for an uninitialized variable) rather than 0. You can check this by doing `export(some_enum) var my_var = 42` and setting the variable to the first element of the enum. The var will remain set to 42 rather than 0

You get the same issue even if you explicitly declare the first element of the enum as = 0

**Comment by Ace-Dragon** [comment]
To note, this has also been an issue for the alpha builds as well.

For now, it can be worked around (from an ease of development standpoint) by having the first element be something like **None**, **Empty**, or **Nothing**. You are less likely to get an error because you're less likely to write code that checks for it (because there is nothing that requires logic to be executed).

**Comment by noidexe** [comment]
@rcorre In 3.1 it's working differently. If you set it to the first element the reset icon disappears and it is set to the default value. The workaround here would be to set the default value to 0 int the script so it matches.
