### ISSUE TITLE
Issues with CSG and GIProbe

### ISSUE THREAD

**Issue by novemberist** [godotengine/godot#25393]
**Godot version:**
Godot 3.1 master
commit https://github.com/godotengine/godot/commit/0d438c7b18521833be23af37e0d9c1c7a66b669c

**OS/device including version:**
Arch Linux, Mesa 18.3.2, AMD RX580

**Issue description:**
First of all, thank you @reduz for making CSGs work with GIProbes with one of the latest commits. However, for me it doesn't work as expected yet. 

I set up a simple all-CSG test scene containing a closed room, a lamp (emissive material) and a GIProbe (set to interior). When I bake the GIProbe, the whole room turns black and I have to resize the inner, subtracted CSG inwards or outwards to make the GI visible. At its original size, there merely seems to be a black box of GI data. 

![csg_gi](https://user-images.githubusercontent.com/7927471/51808130-12f21200-2290-11e9-8183-def7686b1ca5.gif)

[csg_test.tar.gz](https://github.com/godotengine/godot/files/2800880/csg_test.tar.gz)

**Comment by reduz** [comment]
Make demo project ploz

**Comment by novemberist** [comment]
I have attached my demo project, as shown in the gif. To reproduce, simpy bake the GIProbe. Afterwards scale the inner CSGBox a bit, to see how the room actually should look after baking.

**Comment by novemberist** [comment]
Oddly enough, after reading about issue https://github.com/godotengine/godot/issues/25395 I attempted to test if this is actually true and put the GIProbe as a child of my LightEmitter in the test scene. I have no idea why, but this actually makes the GIProbe work as intended.

**Comment by novemberist** [comment]
Any ideas on this so far? Is this even reproducible for anyone else? I'm beginning to wonder if this is a problem on my end, but GIProbes still don't work right at all with any CSGShapes.

I tried to work around this via script by using get_meshes() on the toplevel csg node and assigning the mesh data to a regular MeshInstance, hiding the CSG mesh and rebaking the GI data at runtime. This at least works to get the lighting right, but doesn't work for previewing in the editor, obviously.

I realised that using get_meshes() in the _ready() function does return an empty array and I have to capture the mesh data somewhere in my _process function. I don't know if this is expected behavior, but I expected it to work once the CSG nodes had entered the scene tree.

**Comment by varkatope** [comment]
3.1 Stable
Win 10 64 bit

I get this error when I try to bake GI with a CSGBox in the scene. The shading also doesn't look right on the CSGBox after baking.

drivers/gles3/rasterizer_storage_gles3.cpp:3774 - Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()

If I remove the CSGBox I don't get the error while baking GI. Not sure if this error message is at all helpful to you, though.

**Comment by novemberist** [comment]
Unfortunately, this bug is still present on the latest 3.2 master. After baking, the correct lighting often shows for a split second, until all the weird black areas appear and remain.

![giprobe](https://user-images.githubusercontent.com/7927471/56225794-52035880-6072-11e9-925c-a65f8f163812.gif)

**Comment by novemberist** [comment]
This is not a big issue anymore since after #27940 you can now enable "used in baked lighting" (from GeometryInstance) and the GIProbe works correctly. Still leaving this open, since there still seems to be a bug here.

Maybe 0d438c7 should be removed? since now if you untick "used in baked lighting" you get wrong baked lighting (instead of none, which would be expected behavior)

**Comment by akien-mga** [comment]
Still seems reproducible in 3.2.3 RC 1. CC @madmiraal @clayjohn

**Comment by madmiraal** [comment]
I'm not an expert on lighting, but as far as I can see it's working as expected, and this issue may be due to a misunderstanding or incorrect use of `GIProbe`; more specifically the `Interior` setting, or even just the (default) sky lighting setting the wrong expectations as to what is "correct".

In the provided demo project, the only light inside the room created by cutting out the inside of a CSGBox with another slightly smaller CSGBox is the emission texture in the ceiling; so the room should be relatively dark. However, without a GIProbe it is bright, because the surfaces are receiving sky lighting from the scene. This may set the expectation for the correct lighting, but it is incorrect lighting:
![No GIProbe](https://user-images.githubusercontent.com/9253928/88555714-0f278300-d020-11ea-9712-9fdf2f90d6c4.png)

When a `GIProbe` is added, and before `Use in Baked Light` is selected (or before #27940 provided that option) the correct lighting (without the benefits of the reflected light provided by the GIProbe) is displayed:
![GIProbe without Baked Lighting](https://user-images.githubusercontent.com/9253928/88557069-ab9e5500-d021-11ea-921c-f57287766fad.png)

The problem arises, when `Use in Baked Light` is now turned on (for the root CSG node) but the `GIProbe` interior property is not checked (the default), because the sky lighting is included again. This may be considered "correct", because it is similar to the lighting without the `GIProbe`, but this is incorrect lighting again:
![GIProbe with Baked Lighting not Interior](https://user-images.githubusercontent.com/9253928/88557814-9ece3100-d022-11ea-8988-5086d76fb41e.png)

Checking the `Interior` property on the `GIProbe` and `Use in Baked Light` on the root CSG node results in the correct, beautiful lighting:
![GIProbe with Baked Lighting and Interior](https://user-images.githubusercontent.com/9253928/88558348-49deea80-d023-11ea-8681-579105d9d135.png)

**Comment by novemberist** [comment]
old issue, which was probably resolved a long time ago
