### ISSUE TITLE
Sponza demo: fire doesn't work with GLES2

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#25414]
**Godot version:**
master (https://github.com/godotengine/godot/commit/70689ebffd95ab34e45bcbfdce3f6389033bfd44)
![sponza](https://user-images.githubusercontent.com/34406967/51840867-838b4400-230d-11e9-9fe2-0d31d23cbf93.png)

**Comment by akien-mga** [comment]
Please report it on the repository of that demo, it's likely using Particles which are not available in GLES2, so that's expected.

Please also include more information in bug reports, the *bare minimal* here would have been a link to that "Sponza demo", there are several ones on GitHub and bug triagers or fixers don't necessarily know what you're talking about.
