### ISSUE TITLE
Facilitate occasional use of external editor

### ISSUE THREAD

**Issue by jabcross** [godotengine/godot#25435]
I tend to switch between editors often, since neither the built-in editor nor the external editor provide all of the features I use, such as git visualization and advanced editing facilities.

I do not believe that the built-in editor will ever cover all of these features, and currently the external editors also have limited usability, because of the lack of a GDScript language server.

Currently, setting up the external editor in Editor Settings completely disables the built-in editor.

I suggest adding a button or a keyboard shortcut that opens the configured external editor in the current file, line and column, even if it's not set as the default editor.

**Comment by WesCook** [comment]
When an external editor is configured, having a context menu on scripts to "Open in internal editor" and "Open in external editor" would also be great.

This would probably require a default setting to prefer internal or external in the Editor Settings as well (eg. when double clicking a script in the FileSystem view).

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Note: A lot of the features you have requested are already in the engine or are coming. So it would be worth evaluating before opening a new proposal!**
