### ISSUE TITLE
Would be more clear to have an InputEventMouseWheel

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25457]
Just a feature proposal, for anyone familiar with this area of input handling.

Currently there is some awkwardness in the mouse input regarding button presses and mouse wheel scrolling.  The `BUTTON_WHEEL_UP `and `BUTTON_WHEEL_DOWN `is kind of tacked on to the `event.button_index` for `_input(event)`, though not really being a button.  (They also seem synonymous with middle mouse button.)

Having it described internally as a button leaves the impression that it could be queried in other ways using the `Input.is_mouse_button_pressed()`.

There is this issue at least:  https://github.com/godotengine/godot/issues/21058

It may be cleaner to split the mouse wheel motion out of the mouse button input.  Perhaps into InputEventMouseWheel.  It would be nice as well if it could track a speed or velocity of the wheel, and report a positive or negative number representing if it is going some speed up or down.
`Input.get_mouse_wheel_speed()`.  It's not so easy to make assumptions of about the wheel speed with what is provided.

There may also be other wheel related features that I haven't considered, those could find a home in this input event as well.

Currently, if you want to try to track the mouse wheel state outside of the `_input(e)`, it takes a little bit of tricky flagging, since there is no falsifying event that you can catch with `event.pressed`.

The process looks like this, even without a wheel velocity algorithm, this feels like it may be a bit non-intuitive for newcomers that just want to know the state of their mouse wheel.

```
var wheel_up   = false
var wheel_down = false

func _physics_process(delta):
	
	printt("----> ", wheel_up, wheel_down)
	
	wheel_up   = false
	wheel_down = false


func _input(e):
	
	if(e is InputEventMouseButton):
		if(e.button_index == BUTTON_WHEEL_UP  ): wheel_up   = true
		if(e.button_index == BUTTON_WHEEL_DOWN): wheel_down = true
```

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
