### ISSUE TITLE
FuncRefs crashing when used inside inner Classes

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#25455]
**Godot version:**

1253b9c038277aebfb5a4cc1

**OS/device including version:**

Win10 64bit (Debug/Tools)

**Issue description:**

GDScript inner classes have issues when trying to use FuncRefs.

![godot_master_2019-01-29_11-06-42](https://user-images.githubusercontent.com/13004169/51896817-f8b25400-23b5-11e9-9f5a-3124c5409f76.png)
![godot_master_2019-01-29_11-04-01](https://user-images.githubusercontent.com/13004169/51896827-fc45db00-23b5-11e9-9672-83c71c4b28ab.png)

**Steps to reproduce:**

Use the following code or the project below.

```gdscript
extends Node2D
class Thing extends Node:

	var callback

	func _init(function): 
		callback = function
	
	func _physics_process(delta):
		print("here") 
		callback.call(delta)

func _enter_tree():

	var a_thing = Thing.new(funcref(self, "callee"))
	call_deferred("add_child", a_thing)

func callee(delta):
	print(delta)
```

**Minimal reproduction project:**

[3.1 Class FuncRef Issue.zip](https://github.com/godotengine/godot/files/2806877/3.1.Class.FuncRef.Issue.zip)

**Comment by vnen** [comment]
The code is wrong, the function to call in FuncRef is `call_func()` instead of `call()`. With this code it's trying to call the function called `0.016667` (which is the `delta` value) on the FuncRef object.

The error message is a bit weird though, it should be a non-existent function and not an invalid argument. I guess the debugger gets thrown off when you pass a non-String to the `call()` function.

**Comment by avencherus** [comment]
@vnen Whoops, yeah, I got crossed up there by the error.  Closing it for now, unless you'd like me to leave it open and modify it to address revisions to the error message.
