### ISSUE TITLE
Export PackedScene could have a compact version

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#25471]
**Godot version:**
Godot 3.1 Beta 3

**OS/device including version:**
Mojave OSX and Windows 10

**Issue description:**
When you export a PackedScene you get a thumbnail, it happens that sometimes (more than less) you may use scenes just as logic containers. It would be neat to have a way to disable the thumbnail

`export(PackedScene, compact_bool = false)`

compact_bool would default to false but could be set to true.
or even using a constant:

EXPORT_VAR_COMPACT

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
