### ISSUE TITLE
[Mono] Stacktraces of marshalling errors could be better

### ISSUE THREAD

**Issue by paulloz** [godotengine/godot#25529]
**Godot version:** 463123a

Debugging marshalling issues can be difficult because the resulting stacktraces do not really display any useful information.
![image](https://user-images.githubusercontent.com/437025/52089734-92912100-25af-11e9-8bd6-c4133f074e07.png)

As it's often calls from the message queue, we don't have much information to hand out to the end user but context about what the call is, where it emanates from or more readable type names would already be a huge step forward.

cc @neikeq as we discussed this a bit earlier.

**Comment by woubuc** [comment]
Same thing happens when an error occurs while creating a scene (either through `GetTree().ChangeScene()` or by `.Instance()`ing a packed scene). No stack trace and no feedback at all. Makes it really hard to track down the issue, especially if the project is getting larger (in our case, around 100 different `_Ready()` functions).
![image](https://user-images.githubusercontent.com/1015540/57539141-1e9eab80-734a-11e9-97f1-5a6f234e30d7.png)

**Comment by akien-mga** [comment]
What's the status on this issue in 3.4.2 / 3.5-beta1 or later?

**Comment by paulloz** [comment]
3.5-beta1: the stacktrace is better now. We can see the original point of the error at the bottom. Looks good to me.
![image](https://user-images.githubusercontent.com/437025/150939930-1f67e444-ec0d-4cd6-8750-ab9109a6b6d6.png)

**Comment by akien-mga** [comment]
Thanks, closing.
