### ISSUE TITLE
Rename NOTIFICATION_INSTANCED to NOTIFICATION_UNPACKED and add a _unpacked() callback to GDScript

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#25538]
**Godot version:**
3.1 beta2

**Issue description:**
If there is some intensive processing during the ready function, the game will briefly freeze when adding an instanced scene to the scene tree.

In many cases, all the computation involves only the sub nodes of the node that was instanced, making it possible to execute the initialisation (or part of it) before entering the scene tree.

It is already possible to do this type of initialization by doing
```
var my_node = my_packed_node.instance()
my_node.super_expensive_initialization()
add_child(my_node)
```
This approach is, however, not obvious.

**Proposal**

add an `_unpacked()` function to GDScript that is called after the whole scene is unpacked.
This is different from _init() because in the _init() function the children of the node are not present.
This is different from _ready() because it is not necessarily executed inside of the scene tree. (for example, it can be done in the separate thread that does the loading)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
