### ISSUE TITLE
RayShape2D sinks into one-way collision shapes, and collides with them from below

### ISSUE THREAD

**Issue by vysmund** [godotengine/godot#25532]
**Godot version:**
Godot_v3.1-beta3_win64

**Issue description:**
I have a KinematicBody2D for a character with two collision shapes: a RectangleShape for the head and a RayShape2D for the feet. When colliding with a one-way collision shape, the RayShape slowly sinks into it. When colliding from below, instead of passing through the one-way shape, it stops.
Possibly related to #25230 but in 2D seems to work fine with normal (non-one way) collision shapes.

**Steps to reproduce:**

- Add RectangleShape and RayShape2D to KinematicBody2D
- Move it towards the (one-way collision) ground with move_and_slide
- The body drops slowly until the Rectangle hits the ground, ignoring the RayShape
- When colliding from below the one-way collision shape, the body stops

**Minimal reproduction project:**
A simple platformer demonstrating the issue:
[BugTest_RayShape2D.zip](https://github.com/godotengine/godot/files/2820088/BugTest_RayShape2D.zip)

**Comment by avencherus** [comment]
Wasn't sure about the one-way from below in your project (turned the platform upside down and no collision), but definitely seeing the sinking problem on the surfaces of both one way colliders.

**Comment by fossegutten** [comment]
Would be nice if all raycasting could be considered in one way collisions. Raycast2D nodes and Physics2DDirectSpaceState.intersect_ray() also collide with Oneway collisions from below. If not, i have to implement custom one way collisions

**Comment by reduz** [comment]
Raycast shapes in KinematicBody2D no longer work with one way platforms. They only work when casted from outside a shape and hitting something, and will not work when casted from inside a shape anyway.

The reasoning is this image:
![image](https://user-images.githubusercontent.com/6265307/52900452-a609d200-31d4-11e9-8ce1-5933b0ee7bf3.png)

Where you can see that if they worked "correctly" the result would be undesired, hence no special caseis needed. The only downside about this is that the same happens if you jump from below the platform instead of the side (there will still be a "hop"), but this can be alleviated by using a shorter raycast.

**Comment by and3rson** [comment]
Just found this issue while searching - we're using raycasts for inverse kinematics of legs and it doesn't work properly when jumping up through a platform with one-way collision enabled: the legs "jitter" when the raycast passes through the platform.

Is this considered "won't implement"? Because it means that raycasts are not consistent with the rest of collision detection.
