### ISSUE TITLE
Project got corrupted after terrible crash

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#25545]
**Godot version:**
3.1 beta3

**OS/device including version:**
Windows 10 x64

**Issue description:**
So uh, just now my laptop decided to randomly crash after running the game. Not sure how much it was caused by Godot, but as a result, my project.godot got completely corrupted, as well as few scene files I had open at the time. By corrupted I mean they were filled by some binary garbage without any way to recover it. Attaching one of the files just to show what happened:
[AvatarEditor.zip](https://github.com/godotengine/godot/files/2821944/AvatarEditor.zip)
No idea what happened and how it happened and if it's even related to Godot, but as some of my files were corrupted, I'm reporting it just in case it's indeed some Godot issue.

EDIT:
Now I noticed that it also corrupted one of the scripts that I had set in autoload.

**Steps to reproduce:**
No idea ;_;

**Comment by groud** [comment]
It is unlikely that the crash is Godot-related. In nowadays OS, a high level software can really hardly crash a computer. What most likely happened is that a driver bug or a kernel issue crashed your computer, while the system was writing in those file. Which resulted in garbage written down into those files.

There is likely nothing we can do about this bug, since it is likely dependent on your machine and its drivers.

**Comment by QbieShay** [comment]
@KoBeWi My only suggestion to use a version control system so that you don't lose too much if you work. Sorry to hear what happened!

**Comment by KoBeWi** [comment]
Closing, because it never happened again.
