### ISSUE TITLE
Expression object does not handle assignment operators

### ISSUE THREAD

**Issue by Kinsman** [godotengine/godot#25554]
**Godot version:**
Version 3.1 beta 3

**OS/device including version:**
Windows 10

**Issue description:**
While the Expression object in 3.1 handles variable lookups, math, and method calls, it doesn't handle assignment operators. Entering '=' or variations such as '+=' leads to a parsing error where Godot expected to see '=='.

I'm not sure if this is a bug, or a feature request. I can understand if Expression was only meant to evaluate, but the ability to call methods implies that it's OK to make changes to the objects it calls; and I think the feature is incomplete without assignment operators.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
