### ISSUE TITLE
Crash when using `new` on a virtual class

### ISSUE THREAD

**Issue by zlsa** [godotengine/godot#25596]
**Godot version:**
Reproduced on Godot 3.1 beta 3 and git master 919fa75803177d0dc8f03c16b6be1360140145e1

**OS/device including version:**
Platforms tested:
* Ubuntu Linux 18.10
  - `uname -a`: `Linux <hostname> 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
  - OpenGL version `4.6.0 NVIDIA 390.87`
* Windows 10

Hardware (same for both platforms):
* AMD Ryzen Threadripper 1950X 16-Core Processor
* nVidia GeForce GTX 1080 Ti/PCIe/SSE2

**Issue description:**
When instantiating a new custom script that extends `InputEvent`, Godot crashes.

**Steps to reproduce:**
1. Create a script that extends `InputEvent`.
2. `preload` it from another file.
3. Call `.new()` on the `preload` variable.

**Minimal reproduction project:**
https://github.com/zlsa/godot-custom-input-event-crash

**Comment by QbieShay** [comment]
Hi! After a debugging session, turns out that you are not supposed to inherit from InputEvent, since it is virtual and virtual classes do not get a constructor assigned (see https://github.com/godotengine/godot/blob/master/core/register_core_types.cpp#L132).

This should indeed be properly addressed in the engine and not cause a crash.
