### ISSUE TITLE
Compiling Godot for Android

### ISSUE THREAD

**Issue by Lucky0710** [godotengine/godot#25603]
Hi everyone,
I recently tried to compile godot for android because i finally created my first game !

But i'm really struggling to do so, and i just can't figure out why it is not working, it seems like a new problems appears right after i find a solution to the previous one... I successfuly built the release and debug apk but when i try to export my project with the new templates, i get a flashing godot icon and the app crash. Also, adb logcat tell me that i have missing symbols in my .so lib files. 

I'm clearly missing something here, so if anyone managed to recently compile godot for android, it would be amazing if he could tell me exactly the process he went through, and the version of the NDK, SDK, JDK, Scons etc, he's using.

I really want to launch this game i've developped for so long, and this would help me so much !
Thanks in advance !

(sorry for my english, it is not my first langage...)

**Comment by avril-gh** [comment]
I'll share how i compile godot 2.x and 3.x on windows.
Maybe it will help someone.


1. Install MSVisual studio 2017 (or MSVStudio build tools 2017 only if you wish)

2. install java - most recent (JRE 1.8.0 201)

3. install JDK - most recent (JDK 1.8.0 192)

4. install python - 2.7.11

5. install scons - 2.4.1

6. install pywin - must be the same version as python so 2.7.11
(this is optional, if you want to use -jx switch to speed up building)

7. install android NDK's
android-ndk-r18b for godot 3.x
android-ndk-r17c for godot 2.x

8. install android SDK manager
Since it seems like google want to force everyone to his android IDE, android SDK manager is no more available for download as standalone tool from google developers site,
However its known to be included as standalone tool in SDK r24.4.1 which can be found around the net.
Therefore if you want just android SDK manager without IDE, you can google for it, or just get it here https://dl.google.com/android/installer_r24.4.1-windows.exe
Then you can update / change your android SDK's with "SDK manager.exe" found within installed package.

In android SDK manager i have installed
android sdk tools 25.2.5
android sdk platform-tools 28.0.1
android sdk build tools 28.0.3
android sdk build tools 27.0.3
sdk platform 28.6
sdk platform 27.3

9. set environment paths or better just make separate BAT files for compiling godot 2.x and 3.x since they require little different settings.

for compiling godot editor 2.x it could be

```
@echo off&cls
call d:\system\dev\ide\MSVStudio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
cd godot-master
TITLE compiling editor
call scons -j3 platform=windows tools=yes target=release_debug
pause
```

for compiling godot editor 3.x it could be

```
@echo off&cls
call d:\system\dev\ide\MSVStudio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
cd godot-2.1
TITLE compiling editor
call scons -j3 platform=windows tools=yes target=release_debug
pause
```

for compiling android templates 2.x it could be

```
@echo off&cls
TITLE [SET ENV][build debug][build release][packaging apk]
call call d:\system\dev\ide\MSVStudio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
cd godot-2.1
set PATH=%PATH%;C:\Program Files\java\jdk1.8.0_192\lib
set JAVA_HOME=C:\Program Files\java\jdk1.8.0_192
set ANDROID_HOME=d:\System\dev\Android\android-sdk
set ANDROID_NDK_ROOT=d:\System\dev\Android\android-ndk-r17c
set ANDROID_NDK_HOME=d:\System\dev\Android\android-ndk-r17c
set NDK_TARGET=arm-linux-androideabi-4.9
TITLE [set env][BUILD DEBUG][build release][packaging apk]
call scons platform=android target=release_debug verbose=no tools=no -j3
TITLE [set env][build debug][BUILD RELEASE][packaging apk]
call scons platform=android target=release verbose=no tools=no -j3
TITLE [set env][build debug][build release][PACKAGING APK]
cd platform/android/java
call "gradlew.bat" build
pause
```

for compiling android templates 3.x it could be

```
@echo off&cls
TITLE [SET ENV][build debug][build release][packaging apk]
call call d:\system\dev\ide\MSVStudio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
cd godot-master
set PATH=%PATH%;C:\Program Files\java\jdk1.8.0_192\lib
set JAVA_HOME=C:\Program Files\java\jdk1.8.0_192
set ANDROID_HOME=d:\System\dev\Android\android-sdk
set ANDROID_NDK_ROOT=d:\System\dev\Android\android-ndk-r18b
set ANDROID_NDK_HOME=d:\System\dev\Android\android-ndk-r18b
set NDK_TARGET=arm-linux-androideabi-4.9
TITLE [set env][BUILD DEBUG][build release][packaging apk]
call scons platform=android target=release_debug verbose=no tools=no -j3
TITLE [set env][build debug][BUILD RELEASE][packaging apk]
call scons platform=android target=release verbose=no tools=no -j3
TITLE [set env][build debug][build release][PACKAGING APK]
cd platform/android/java
call "gradlew.bat" build
pause
```

In these BAT files paths are set to locations where i have installed the "things".
You must of course change them to point to correct locations on your computer.
Theyre left like this just to be easy to understand and change examples.

**Comment by LinuxUserGD** [comment]
Possible duplicate #25531

**Comment by Lucky0710** [comment]
Thanks you so much, i will try it tonight ! I will post the results as soon as possible

**Comment by Lucky0710** [comment]
So i tried compiling it with you method, but i got the exact same issue : Flashing godot at the start of the app, and crash. With adb logcat i get the same result : Libraries (*.so) are missing debug symbols.
I'm definately missing something...

**Comment by aaronfranke** [comment]
@Lucky0710 You need to specify what version of Godot you are using (have you tried multiple and/or the latest master/beta?), what host OS you are using, and what Android version you are using.

**Comment by Lucky0710** [comment]
I'm using the latest version of godot master, I'm on Windows 10, using NDK v18b, and i try to export on many different devices and Android Studio

**Comment by Lucky0710** [comment]
By the way, i want to compile for Godot 3.0.6

**Comment by Lucky0710** [comment]
I've retried a couple of times but i get the same results.. I'm not sure if i'm using the right version of Godot-master but i don't how to downgrade to an acceptable version..

**Comment by Lucky0710** [comment]
sorry but i don't understand where and how to use it

**Comment by Lucky0710** [comment]
Ok i'm testing with an older commit thanks to git reset --hard, i will post the results !

**Comment by Lucky0710** [comment]
another question, how do i find the right commit for Godot-master 3.0.6 ?

**Comment by Lucky0710** [comment]
And by the way, will it be the same if i just download the Godot 3.0.6 source code from github and try to compile it ?

**Comment by akien-mga** [comment]
If you want to build 3.0.6, you should not use the master branch.
You can use `git checkout 3.0.6-stable` or download the zip/tarball from https://github.com/godotengine/godot/releases/tag/3.0.6-stable

**Comment by Lucky0710** [comment]
Thank you very much !
