### ISSUE TITLE
New script dialog should put the cursor at the end

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#25611]
**Godot version:**
629ac20

**Issue description:**
When a project starts having deep folder trees, it is necessary to go at the end of the textbox for the script name in order to edit the script name (never named a script 'new_script' so far).

**Proposal**
Make the cursor jump automatically before "new_script" so that there is no need to scroll in the textbox (which is not so pleasant since it is done by selecting text and waiting)

**Comment by SeleckyErik** [comment]
After a bit of fiddling, I got this behaviour:
![2019-02-05_21-39-34](https://user-images.githubusercontent.com/35656626/52302814-98f81200-298e-11e9-82a9-c89347519ea0.gif)

On the other hand, maybe it would be better to split the "Path" LineEdit into two, one for directory, one for filename. It would be more readable and more familiar to the users, since it is a common approach in other software.

**Comment by QbieShay** [comment]
Seems great!

**Comment by SeleckyErik** [comment]
There's one more bug I have to fix, though. The first time the dialog is open, the size of the LineEdit has not been computed yet, so the view is shifted.
![2019-02-06_01-33-35](https://user-images.githubusercontent.com/35656626/52313639-7cb89d00-29af-11e9-8fa6-04e727d48668.gif)
