### ISSUE TITLE
Display export variables for plugin scripts on the Plugins tab of the Project Settings

### ISSUE THREAD

**Issue by BanchouBoo** [godotengine/godot#25628]
### Problem
---
There is no simple, unified way to have settings for a plugin, currently any plugin developer that wants to have configuration will have to put together their own solution for allowing user configuration, whether that be through a custom dock, a resource, directly editing the script, or whatever else they may think of.

### My suggestion
---
Export variables for the plugin script could be displayed on the Plugins tab in the Project Settings window, the plugin itself could have a toggle to expand and collapse the list of variables to keep the window clean. Below is a rough mock-up of how I think it could be implemented. This would make setting up plugins easier and help prevent clutter with all the different implementations plugins may have with configuration while still allowing developers to implement more complex systems if they need to.

![mockup](https://user-images.githubusercontent.com/32691832/52256051-401f6f80-28e3-11e9-8b02-5bf9a30cbf01.png)

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
