### ISSUE TITLE
A lot of warnings "Property not found:" when trying to rename project

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#25661]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.1 8698876

**OS/device including version:**
Ubuntu 18.04 

**Issue description:**
When I Try to rename project, then this error appears:
```
WARNING: _get: Property not found: rendering/quality/shadows/filter_mode
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/follow_surface
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/weight_samples
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/quality
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/subsurface_scattering/scale
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/quality/voxel_cone_tracing/high_quality
   At: core/project_settings.cpp:193.
WARNING: _get: Property not found: rendering/limits/time/time_rollover_secs
```

**Comment by avencherus** [comment]
Yep, was finally getting around to reporting this.

I'll just tag on that I confirm it in 22ee7ba / 3.1 beta 8 for Win10 64-bit.

![image](https://user-images.githubusercontent.com/13004169/53472697-0ddfd880-3a71-11e9-86a9-6a054d059ade.png)

**Comment by akien-mga** [comment]
Those are all GLES3-only properties. I guess you're trying to rename a project that you converted from GLES3 to GLES2?

**Comment by avencherus** [comment]
They seem to be in GLES3 as far as I can tell.  Haven't done many conversions yet.

![image](https://user-images.githubusercontent.com/13004169/53477452-661cd780-3a7d-11e9-95ae-2e7b03d117fb.png)

**Comment by Anutrix** [comment]
The error message are those because of feature override checks of L202 in https://github.com/godotengine/godot/blob/dfe228a865890931c6da7b98b53b6f0fe2555d15/core/project_settings.cpp#L196-L210.

**Comment by akien-mga** [comment]
Still valid in the current master branch.

**Comment by frewq** [comment]
#29566

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

**Comment by timothyqiu** [comment]
Now in 3.3 rc6, opening the rename dialog for an old project keeps printing `physics/common/enable_pause_aware_picking` even after I close the dialog.

`ProjectSettings` is meant to be used as a singleton, but renaming a project creates another instance, overriding the one created in `Main::setup()`:

https://github.com/godotengine/godot/blob/f50c8062dd9389a76986307402bc8c4538d51f1e/core/project_settings.cpp#L1030-L1034

https://github.com/godotengine/godot/blob/f50c8062dd9389a76986307402bc8c4538d51f1e/main/main.cpp#L366

https://github.com/godotengine/godot/blob/f50c8062dd9389a76986307402bc8c4538d51f1e/editor/project_manager.cpp#L459

The defaults for `physics/common/enable_pause_aware_picking` is also lost because it's set in `Main::setup()`.

https://github.com/godotengine/godot/blob/f50c8062dd9389a76986307402bc8c4538d51f1e/main/main.cpp#L1203

So Godot generates a property missing report each time it tries to access it in `SceneTree::iteration()`:

https://github.com/godotengine/godot/blob/f50c8062dd9389a76986307402bc8c4538d51f1e/scene/main/scene_tree.cpp#L482

Moving the `GLOBAL_DEF` to the constructor of `ProjectSettings` could fix the issue. Maybe there should be a clean up for the `GLOBAL_DEF`s of properties?

**Comment by filipworksdev** [comment]
This still appears to be valid in 3.5 beta

**Comment by filipworksdev** [comment]
I no longer see this in 3.x upstream currently versioned as 3.5. I thought I saw this but I was using older code. It was still there in 3.4. After pulling from upstream I no longer see it. Can anyone else confirm?

**Comment by filipworksdev** [comment]
I no longer see this in 3.x upstream (currently 3.5). Can anyone else confirm?

**Comment by KoBeWi** [comment]
I still get this issue in 3.4 and 4.0 2f41af7. It happens in Project Manager.

**Comment by Florian-Schoenherr** [comment]
on my end, I mostly get this on older projects:
![image](https://user-images.githubusercontent.com/65456722/147823839-1c6e0c53-8396-44e4-9ae1-7a8966614f75.png)
but with 3.4 projects I get mixed warnings:
![image](https://user-images.githubusercontent.com/65456722/147823996-42c670eb-b552-417d-b9dd-f762e7a9b838.png)

**Comment by MuffinManKen** [comment]
This is still an issue in 3.4.3rc2.  I created a brand new, empty project.  Went back to the Project list and hit rename.  A flood of warnings followed.

```
WARNING: Property not found: rendering/limits/time/time_rollover_secs
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/shadows/filter_mode
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/follow_surface
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/weight_samples
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/quality
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/scale
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/lightmapping/use_bicubic_sampling
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/voxel_cone_tracing/high_quality
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/limits/time/time_rollover_secs
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/shadows/filter_mode
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/follow_surface
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/weight_samples
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/quality
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/scale
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/lightmapping/use_bicubic_sampling
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/voxel_cone_tracing/high_quality
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/limits/time/time_rollover_secs
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/shadows/filter_mode
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/follow_surface
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/weight_samples
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/quality
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/subsurface_scattering/scale
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/lightmapping/use_bicubic_sampling
     at: _get (core/project_settings.cpp:217)
WARNING: Property not found: rendering/quality/voxel_cone_tracing/high_quality
     at: _get (core/project_settings.cpp:217)
```

**Comment by MuffinManKen** [comment]
Also in 3.5 beta 1

**Comment by BastiaanOlij** [comment]
As @timothyqiu linked my PR to this one.... :)

The cause of this I believe is that we stopped writing all properties into the `project.godot` file.

When we start Godot we call `GODOT_DEF` to register all the properties we support ensuring that our project settings object is aware of all property types.

However in the project manager we then start loading the `project.godot` file from the selected project resulting in us loosing that information. Now we only load what is in `project.godot` of the project and since we no longer save properties that are set to the default, when we then call `GODOT_GET` we get the unknown property error.

We thus need to somehow retain this data when loading in a new project file instead of clearing our data and assuming we load everything.
