### ISSUE TITLE
extends test should be silent

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#2574]
When an object is `null` or of built-in type, the test `* extends *` should not raise `left operand of 'extends' is not an instance of anything`. 
That is not a syntax error, the result should just be `false`.
The value's type must be compared to TYPE_NIL and TYPE_OBJECT before to use extends, thus this error is useless.

**Comment by reduz** [comment]
GDScript is generally not lax regarding to comparisons, and tries to tread everything that is not common case as an error. It's the complete opposite to languages such as Lua. In this case, I think it's enough to do:

if obj and obj extends class:

Because you are really intending this behavior. In most cases this behavior is not intended and is considered a bug.
