### ISSUE TITLE
Shuffle method for Array

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#2576]
Would be just great to have a shuffle method (like [Fisher-Yates shuffle](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle)) defined on array.

**Comment by reduz** [comment]
do it yourself using code, it's literally 2 or 3 lines of code

**Comment by seadra** [comment]
Well, to be fair, so is `Array.sort()` with quicksort.
Which makes me wonder, how slow is GDScript, say, when compared to native code or Mono implementation of C#? Has anyone done any sort of benchmarks with GDScript?

**Comment by punto-** [comment]
Yeah but shuffle is literally just 2 lines of code, quicksort isn't. Try
this:

for i in range(array.size()):
   array.swap(i, rand() % array.size())

NOTE: there's no "array.swap()" :p That'd be a nice addition.

**Comment by seadra** [comment]
The issue isn't whether it takes 2 or 10 lines though.

**Comment by romulox-x** [comment]
I don't know how it would compare with the C version, but I would imagine if you implement it in-place, meaning you're not copying to another array, or adding/removing elements from the array (causing it to shuffle memory around behind the scenes), it'd be plenty fast.  This is essentially what punto's answer does, even though swap doesn't exist.  I'm sure you can imagine how to implement that swap in gdscript using a temp variable.

**Comment by seadra** [comment]
I already implemented Fisher-Yates shuffle in GDScript (BTW his code is wrong), that's not the issue.

The issue is the size of data I'm shuffling (hence the performance concern), and depending on the size of the world, it can be pretty huge.

Right now, whenever I write some loop which might be large, I'm asking myself "how bad will this scale" because I have no idea at all. I really wonder how performant GDScript is, and this definitely deserves a mention in the docs.

**Comment by reduz** [comment]
If it's too slow, you can do it over many frames or just write a c++ module.
Gdscript is about as fast as python, with faster vector types.

**Comment by seadra** [comment]
Maybe you can add a few lines about the implementation details of GDScript?

* Is GDScript JIT or runs on a VM?
* How performant is it? (Are the some benchmarks numbers? Or is there a benchmarking suite in godot? If not, I think I can work on something like this, if there is a function that tells the absolute time and a function that tells the current allocated memory in the GDScript world)
* Are there bottlenecks in certain constructs? (loops, hash maps, other things?)

**Comment by reduz** [comment]
Look for the same information about python and you will get your answers

**Comment by reduz** [comment]
In other words, you won't get anything from performance figures. If it
works, it works. If it doesn't, use a more efficient algorithm or recode in
c++

**Comment by seadra** [comment]
> In other words, you won't get anything from performance figures. If it
works, it works.

Well, that's a bummer (for stuff that is not just a 2-liner)

BTW there are different implementations of python (ironpython, pypy, cython, jython) and the numbers vary. Similar for Javascript (and pretty much anything else): spidermonkey, v8, jagermonkey perform differently.

**Comment by reduz** [comment]
Cpython, the standard one

**Comment by seadra** [comment]
> Cpython, the standard one

This thread is full of sad news :)

**Comment by akien-mga** [comment]
See also the two duplicates listed above, it seems this is a popular feature request.

**Comment by adolson** [comment]
Shuffling an array seems like pretty basic functionality with many use cases in gamedev... It's puzzling why there is such resistance to having it be a built-in function.

**Comment by reduz** [comment]
mostly because
1) there are too many ways of shuffling an array, depending on the size of
array, amount of randomness, purpose, etc.
2) it's not too difficult to do it yourself

**Comment by silverkorn** [comment]
Add some common implementations in the Wiki?

**Comment by reduz** [comment]
closing this, as it's not going to happen

**Comment by thomasbaijot** [comment]
We are in 2017 and 3.0 is coming soon.
Is this array shuffle built-in function still impossible to implement ?

**Comment by akien-mga** [comment]
It's not impossible to implement, just not wanted, as per https://github.com/godotengine/godot/issues/2576#issuecomment-154153094

**Comment by bojidar-bg** [comment]
Note that it might be added as per #7199.

**Comment by thomasbaijot** [comment]
Could it be re-evaluated by devs ?It's a 2 years old decision and maybe it will appear as useful now...Thanks. 😊


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Rémi Verschelde <notifications@github.com> Date : 15.03.17  10:33  (GMT+01:00) À : godotengine/godot <godot@noreply.github.com> Cc : thomasbaijot <thomasbaijot@gmail.com>, Comment <comment@noreply.github.com> Objet : Re: [godotengine/godot] Shuffle method for Array (#2576) 
It's not impossible to implement, just not wanted, as per #2576 (comment)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/godotengine/godot","title":"godotengine/godot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/godotengine/godot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@akien-mga in #2576: It's not impossible to implement, just not wanted, as per https://github.com/godotengine/godot/issues/2576#issuecomment-154153094"}],"action":{"name":"View Issue","url":"https://github.com/godotengine/godot/issues/2576#issuecomment-286688010"}}}
