### ISSUE TITLE
Physics material name

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#25777]
**Godot version:**
Godot 3.1

**Issue description:**
in Physic material there is Friction , Rough , Bounce and Absorbent , but if you add Name for Example to define what type of this Physic material , for example is it Glass ? is it Metal ? or is it Concrete ? adding this variable will make it very easy to define what surface of that object
this will make it very very easy to make Foot steps sounds maybe ?
or bullets impacts on objects ?

i know there is other ways to do this , but this way is the easier one , like Unreal Engine 4

![phyisc](https://user-images.githubusercontent.com/34812055/52538447-fa472900-2d72-11e9-9a9a-24b2aed2fdbe.jpg)

**Comment by lethiandev** [comment]
You could create a GDScript that extends from PhysicsMaterial and exports name variable or even enumerator, just attach the script with physics materials. Godot Engine is flexible enough to achieve what you're looking simply with scripts.

**Comment by CCODE05B** [comment]
@lethiandev Yep that's work , but i think this does not work on multiple objects , i need to duplicate the PhysicMaterial resource file for each object , but if this variable was already exist , it will be very easy i guess

**Comment by lethiandev** [comment]
Not sure what you mean by keeping it easier by not-duplicating a resource. If you want to share only names between PhysicsMaterial resources with different friction, rough etc. it needs duplication anyway, because the resource is shared between multiple nodes with all related variables, with the name as well.

**Comment by CCODE05B** [comment]
@lethiandev for Example : Physic material name : ice , Friction : 0.2 .. etc
Physic material name : concrete , Friction : 1.0 .. etc
so if the physic material have this "name" variable for example
we will save the time to Create a script and attach it to physic material , duplicate that physic material each time creating new type of material and attach it to that object
instead , we will just press on create new physic material button , set the parameters .. that's it :D

**Comment by lethiandev** [comment]
Ok, i think i get it, also i have an another idea how to improve resource scripts :)

As you can create class-named GDScripts by supplying the script with `class_name` directive, i think the resource dropdown list should also include scripts that extends from the PhysicsMaterial (or any related scripts extending any resource type). For example with the PhysicsMaterial:

If we have script like:
```gdscript
extends PhysicsMaterial
class_name NamedPhysicsMaterial

export var name = "Unnamed"
```

The dropdown in property inspector with "New ..." options should appear as below:
![obraz](https://user-images.githubusercontent.com/5323129/52540918-ef968f00-2d86-11e9-82dd-750f5a37b2a4.png)

It should apply on all scripts that can extends various resource types, not only PhysicsMaterial.

Sadly currently Godot doesn't recognize the extended resources, as the Node creation tree does it perfectly, that resources are not showing up on resource creation dropdown inside the property inspector.

**Comment by CCODE05B** [comment]
This is really great Idea if Godot Supports it !!

**Comment by wombatstampede** [comment]
PhysicsMaterials can be saved as (*.tres) files. So you can load share the same Material for multiple "Bodies". And this (Physics)Material even has a (file)name. Isn't that enough? Maybe I am missing something?

If that isn't sufficient then I think one could create custom types, extending StaticBody/RigidBody/KinematicBody and the PhysicsMaterialType via a plugin. (See demos -> plugins -> custom_node)

**Comment by vnen** [comment]
All resources have name, you can add one if you unfold the `Resource` section.

**Comment by CCODE05B** [comment]
what i mean is : https://github.com/godotengine/godot/issues/25777#issuecomment-462183556
it can be anything not only a name , maybe Enum , maybe array ?
i know there is many other ways to do this , but  just an Idea to make it Easy like Unreal Engine Physic material

**Comment by Zylann** [comment]
You could also just compare the material itself, like `if body.material == glass`, where `glass` could be a preload.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
