### ISSUE TITLE
Stop the CI if static checks fail

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#25836]
I don't really know much about CI but many PRs fail on static checks *cough cough*   
I wonder, is it possible to stop the CI if the static checks are failing? I think this would significantly speed up the godot CI...

**Comment by akien-mga** [comment]
AFAIK it's not possible to stop a Travis build automatically when one specific build job fails. It's a pending feature request: travis-ci/travis-ci#2062.

That being said, I don't think it would be a good idea either to use such feature. Static checks failing mean that the PR can't be merged, but it doesn't invalidate the other build jobs: it's still good to know if the PR will actually build on all tested platforms, even if there's a trailing space somewhere.

If the builds aborted due to style issues, you'd have to do force pushes to fix the style first, and only then find out that it's actually not building at all and do more force pushes to fix that.

**Comment by TechnoPorg** [comment]
Now that Godot uses GitHub Actions, it's possible to stop workflow runs when a job fails.
> It's still good to know if the PR will actually build on all tested platforms, even if there's a trailing space somewhere.

Maybe the [GitHub context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) could be used to only cancel the workflow if it's for a pull request, but on the person's fork of Godot, all tests would still run and they could see what needs to be fixed? Although that would make it harder for reviewers to see any build issues.

**Comment by akien-mga** [comment]
I still tend to agree with past me on this:

> That being said, I don't think it would be a good idea either to use such feature. Static checks failing mean that the PR can't be merged, but it doesn't invalidate the other build jobs: it's still good to know if the PR will actually build on all tested platforms, even if there's a trailing space somewhere.

We have faster CI now with GitHub Actions and I think it's even less of a problem than it used to be. New contributors still tend to do PRs with style issues until they read the relevant documentation to set up style checks locally, but they also often do contributors which break on a given platform, or most frequently forget to update the documentation to reflect their changes. The documentation and unit tests run *after* a full Linux build as they depend on the compiled Godot binary, so aborting builds would be counter-productive as it's better that users see at once that they have to fix style *and* documentation *and* possibly build errors on some platforms they didn't test locally.
