### ISSUE TITLE
theming suggestions

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#25848]
Godot Version: 3.1 beta 4

I have a few suggestions for themes
- sliderbar and scrollbar grabber should be an style with the ability to set icon over it
- sliderbar and scrollbar arrow buttons should be an style with the ability to set icon over it
- color picker hue and value bars should be icons however we should have the ability to set a style around it.
- all theme items should have the a min size constant so that we don't have buttons collapsing in on themselves.

**Comment by Shadowblitz16** [comment]
sorry I wrote this right before going to bed so i kinda summed it up.
I have a few other suggestions for themes.

- sliderbar and scrollbar should have on and off values styles which are separated from the grabber
- sliderbar and scrollbar grabber should have pressed, hover, focus, disabled, and normal styles
- sliderbar and scrollbar 
![styles](https://user-images.githubusercontent.com/2453707/52731684-2af5b100-2f73-11e9-8ce4-72e501da44d9.png)

arrow buttons should have pressed, hover, focus, disabled, and normal styles

**Comment by Shadowblitz16** [comment]
I have some more regarding checkboxes
- make checkbox icon use style and icon 
![example](https://user-images.githubusercontent.com/2453707/52736510-df490480-2f7e-11e9-843f-2521ccd77a0a.png)

**Comment by toger5** [comment]
I love the on/off for the slider bar!
Adding pressed, hover, focus sb's is a great idea as well.
I am not sure if I understand the "icons over it" part. The grabber is a style. so you also can ad a style box texture to have an icon above it. Or do you want a style box (lets say a dark rect with a red color) and than draw a arrow on it in addition, so you don't have to create an icon with a dark bg and red border? This indeed makes it easier to use/setup!

**Comment by toger5** [comment]
I like the general idea of separating style+icon. It also makes it possible to create a theme with less icons. And to just create white icons, add modulation, and the rest of the style is handled by the style box behind it.

**Comment by Shadowblitz16** [comment]
slider bars and scroll bars work differently when they are styled

I was more or less just suggesting combine the two's functionality while allowing for them to be separate controls.

- for example scroll bar can't be positioned by grabbing scroll area they can only be moved with the grabber
- and slider bars grabber takes up the whole half up to the point it is at instead of having 5 part styled for it..
- left arrow,
- left scroll area (can be clicked to position grabber)
- middle grabber
- right scroll area (can be clicked to position grabber)
- right arrow

**Comment by Amssat221** [comment]
We are a team working on this project for a CS class. Could we get assigned to this issue. Our uusernames are gsegovia2018,mattintriago,cniefit,amssat221

**Comment by Amssat221** [comment]
We are a team working on this project for a CS class. Could we get assigned to this issue. Our uusernames are gsegovia2018,mattintriago,cniefit,amssat221

**Comment by groud** [comment]
@Amssat221 we cannot assign issues to people that are not privileged users on the repository, but you are free to work on any issue you want with your team. It is a good idea to say you work on an issue in the comments though.

Regarding this specific issee, I would advise you not to work on such feature requests right away. The changes are still being discussed and might not  be accepted.

**Comment by toger5** [comment]
I thought about the icon + style box approach.
I think it is a good design. It fits to a lot of situations where you can use a sb instead of an icon.
We just need a way to define the style box size.
So there needs to be something like `constant/icons_size_pressed` (example) ... or we extend the style box flat with a inner value property. (currently this is only present for sb texture. and it represents the inner size of the style box so that the texture is not streched.) If we add this kind of property to style box flat we could calculate the overall size of an sb flat with margin + inner size. which than could be used as the size for the area where the stylebox gets drawn under the optional icon.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
