### ISSUE TITLE
AnimationPlayer current_animation remains even when it is finished (regression from #25776)

### ISSUE THREAD

**Issue by kakoeimon** [godotengine/godot#25873]
**Godot version:**

6b184e4d3b4f02c3bb04fa7a36fe65176f89ec3f

**OS/device including version:**

**Issue description:**

The current_animation of an AnimationPlayer remains even when the animation is finished.
The behavior till now was that, when an animation is finished, the current_animation turns to an empty string ("").

**Steps to reproduce:**
Use the reproduction project. And see the script attached to the AnimationPlayer

**Minimal reproduction project:**

[anim_bug.zip](https://github.com/godotengine/godot/files/2865146/anim_bug.zip)

**Comment by akien-mga** [comment]
That's because of #25776, CC @luizcarlos1405.

**Comment by luizcarlos1405** [comment]
`current_animation` resets, but since it is playing the same animation name as `assigned_animation` it resumes the animation (that is currently at its final position) here:

https://github.com/godotengine/godot/blob/89eb79aef1aac645358664a8245afe35b30da130/scene/animation/animation_player.cpp#L1196-L1201

Will make a PR soon.

**Comment by kakoeimon** [comment]
Just checked the pr #25886. It works as expected.
Thanks.

**Comment by akien-mga** [comment]
Reopening as the PR isn't merged yet :)
