### ISSUE TITLE
Plugin : 2d heightmap collision boxes in Godot's 2D editor

### ISSUE THREAD

**Issue by Steph155** [godotengine/godot#25892]
Godot version: 4.x 

Descripition:

"Greetings.
This here is a suggestion or more precisely a feature request for the engine's 3.1 stable release, please read ASAP...
I was wondering if you could add new modules to Godot's 2d editor to help make 2d heightmap collision boxes.
The system would work based on a 2d flat texture that would have various properties like height, depth, opacity, oblique direction, slope... and help simulate 2.5d in a 2d game...
Well, to illustrate how it would work, here's an example video :
https://www.youtube.com/watch?v=Un9urBgX91c&t=510s "

**Comment by groud** [comment]
> This here is a suggestion or more precisely a feature request for the engine's 3.1 stable release, please read ASAP...

3.1 is feature freeze now, we don't accept new features. 

But in any case, what you describe probably better suits a plugins.

**Comment by Steph155** [comment]
Okay. Then what am I to do now ? Oh, of course, if it better suits a plugin, then compatibility with Godot 2.1.5 would be really helpful as well... So, have I done the necessary for the plugin to come later... ?
Should I try to code it myself(if so, a link to a tutorial on plugin coding would help me) ?..

**Comment by groud** [comment]
> compatibility with Godot 2.1.5 would be really helpful as well

Not really, Godot 2.1 is getting old now. And most people are going to use 3.x now.

> So, have I done the necessary for the plugin to come later... ? Should I try to code it myself(if so, a link to a tutorial on plugin coding would help me) ?..

Well I have no clue, if people are interesting in your plugin, maybe someone's going to work on it. But yeah, if you do it yourself, you probably have more changes to get it done soon.
You can read the [engine documentation](https://docs.godotengine.org/en/3.0/index.html), but for learning learning how to code this is another level. You should probably try finding tutorials on the internet about Gdscript (or maybe python, as it is a similar language) I guess.

**Comment by Steph155** [comment]
Nevertheless. Adding the functionality by designing it as a feature would save the life of many gamedevs.
You said Godot 3.1 is feature freeze. Then please bring it in Godot 4.0. I'm talking about extending the Editor's 2D capabilities by adding a perfect or near perfect 2.5D collision box manager...
For the plugin, Good luck to me... I'm not sure I can code it very fast(say less than a year) given my time and lack of resources(docs, articles and tutorials)...
If you have good resources to help me, never hesitate...

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
