### ISSUE TITLE
[Mono] Godot.Collections.Dictionary can't be cast to Godot.Collections.Dictionary<T>

### ISSUE THREAD

**Issue by xKamuna** [godotengine/godot#25906]
Not sure if this is possible in C#, just letting you know about this minor hurdle.

**Godot version:**

Godot 3.1 beta 3

**OS/device including version:**

Windows 10

**Issue description:**

Godot.Collections.Dictionary can't be cast to Godot.Collections.Dictionary<T> after putting it in a Godot.Collections.Dictionary and sending it over the network.

**Steps to reproduce:**
1. Make a Godot.Collections.Dictionary<string, byte[]> `Godot.Collections.Dictionary<string, byte[]> byteDict`
2. Put it in a Godot.Collections.Dictionary `dict["byteDict"] = byteDict`
3. Send it over the network `Rpc("SomeRpc", dict)`
4. Try casting dict["byteDict"] back to Godot.Collections.Dictionary<string, byte[]> `(Godot.Collections.Dictionary<string, byte[]>)dict["byteDict]`
5. Additionally, if you print the type `GD.Print(dict.GetType().ToString())` you'll see that the object is actually a Godot.Dictionary.

**Minimal reproduction project:**

TODO

**Comment by neikeq** [comment]
This is not a bug, it's just the way it is. You may be passing `object` to Rpc but internally it's converted to Variant. When you receive it, you receive a Variant that is converted to a managed object. Since Variant has no notion of generic dictionaries you get a non-generic one.
`Godot.Collections.Dictionary<T>` is just a wrapper around `Godot.Collections.Dictionary`. You have a `Godot.Collections.Dictionary<T>` constructor that takes `Godot.Collections.Dictionary`, and that's how you create one. I made this a constructor instead of a explicit cast operator because I considered the latter could hide the fact that an allocation is being made.

**Comment by xKamuna** [comment]
Ah, good to know.  I figured it was something like that.  Yeah, I agree that an explicit cast operator might hide that allocation and that a constructor is better.  I just didn't think about trying to use a constructor at the time, so I didn't know that constructor existed.  Just write this up as something that could be documented.  Closing.  Feel free to open it back up if you rather it be open for documentation purposes.
