### ISSUE TITLE
Undo/redo history log

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#25919]
**Godot version:**
3.0, 3.1

**OS/device including version:**
all

**Issue description:**
As a UI component for the editor, I think a panel with a history log for all undoable steps is needed.
Why is it important?
To provide certainty for users what steps are undoable, which are not, how many steps users can go back and what is is exactly they are going back to. (or forward to in case of redo)

See example about the confusion about what it is undoable and what not here: (https://www.reddit.com/r/godot/comments/aqr5ja/voice_your_frustration_what_do_you_think_is_the/egili1u)

**Comment by girng** [comment]
i'm personally not a fan of  an undo history component in the editor. however, if it's a toggleable setting, i think it'll help those specific developers. but theoretically, 99.99% of undoable actions should work correctly. if the developer runs into a specific undo issue, a separate issue  for it would most likely get it fixed ASAP. thus, eventually negating the issue

**Comment by golddotasksquestions** [comment]
Yes, I would imagine it as a window panel you can open and close, move around on the screen and dock to other panels (see https://github.com/godotengine/godot/issues/25920)

Another benefit would be be able to click directly on the history state you want to go to instead of pressing Ctrl +Z a million times hoping not to miss it.

"What did I just do"? - a typical beginner situation, would also help the learning process.

Also this could help with the creation of macros, if we ever want that.

**Comment by randibit** [comment]
I would love to see this feature added.  Like Photoshop or Affinity designer, it really helps to see the undo history and being able to choose which action in the list is a nice bonus.  While the undo works pretty well in Godot, there are times where certain actions are not undo-able so maybe this would help or at least reveal them more verbosely.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by golddotasksquestions** [comment]
Discussion on this issue moved over to https://github.com/godotengine/godot-proposals/issues/953
