### ISSUE TITLE
Ability to set delta time scale in project settings

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#25915]
Godot Version 3.0.6
Window 7 Home 64 bit

Please add a option to set a time scale that is applied to delta passed from _proccess and other hooks

Maybe presets for certain types of games
- normal   (delta time is normal )
- frame     (delta time is scaled up to usually be around 1 delta per frame)

**Comment by kaadmy** [comment]
This would probably be better as a node value that would cascade downwards, similar to pause inheritance.

**Comment by Shadowblitz16** [comment]
using different delta time per scene would get confusing I still think it being a project setting would be better.

however it could be both.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
