### ISSUE TITLE
Menu toolbar purpose

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#25918]
**Godot version:**
3.0, 3.1

**OS/device including version:**
all

**Issue description:**
A lot of Godot functionality is not accessible through the menu drop down toolbar.

In my opinion, the menu toolbar is an indispensable vehicle for usability and essential instrument to learn and understand software. It is central as it provides an anchor and a structure, easy to understand and very common place. There is hardly anyone on earth who does not understand how to use or navigate a drop-down menu toolbar.

Yet, Godot forfeits this potential by not using a well known organizational structure and naming conventions.
The most obvious example is the lack of a "Edit->Undo" and "Edit->Redo" even though Godot seems to provide this functionality. 

As I see it, the purpose of the menu tool bar is to provide a common place with a clear structure for all and every operation of a program. Yes, there are other and faster ways to do things (sub menus in panels for instance, right click context menu should be one, editable keyboard shortcut lists). But if you are unsure about what the program you are using is capable of doing, can't remember the nifty way your tutor has done it, or just want to explore functionality of the editor, one click on the drop down menu button and you see everything instead of spending hours and hours digging trough documentation, random outdated online search results, github issues and tutorials.

In theory, even a beginner should be able to operate the program fully through the use of the menu toolbar.
Many beginners and intermediate users will more often use right click context menus, sub menus on panels, and shortcuts while professional users should be able to use the program for 95% of their tasks by the aid of edible keyboard shortcuts and personalisation, however going back to menu toolbar to look for something you might not be in need as often should always be an option.

**Comment by golddotasksquestions** [comment]
Maybe people can comment here what functionality they are missing in the menu toolbar. Another prominent one for me is "Windows" (also known as panels)
I would like to move (dia drag and dock) windows/panels but also hide/show them through a windows drop down menu, or have the reset to a standard location or save as a workspace (see https://github.com/godotengine/godot/issues/25920)
I would like to open the undo history log when going back in history to see where I'm going to exactly. (see https://github.com/godotengine/godot/issues/25919)

**Comment by willnationsdev** [comment]
Just wanted to mention that there is an editable set of editor keyboard shortcuts in the EditorSettings' "Shortcuts" tab, found in Editor > Editor Settings.

**Comment by golddotasksquestions** [comment]
I was looking for it before I posted, I did not find it even after I read your comment for another 3 Minutes! This is exactly my point Will. This has to be done differently. Not because I want tit differently, but because every other program works would have this not ordered in another tab, greyed out almost in the same color and brightness as the background color of the UI. All programs I have EVER worked with have this either directly in the Settings or a lot more common under in the menu toolbar, withing the tab that houses the preferences as well, right next to preferences. Most of the times this menu toolbar tab is called "Edit", sometimes "Options", sometimes it is under "Files".
The fact that Godot has "Project Settings" at one place in the Menu toolbar and "Editor Settings" at another is also an issue.
"Project Settings" is a complete mess and more than deserves a separate UI issue. However I'm not well versed in the engine yet to have a opinion about how it should be fixed. I only know how hard it is to find stuff there, even when you know it is there and have found if before. 😬

**Comment by willnationsdev** [comment]
Yeah, I got your point. :-) I agree, it would help users to find things if they were placed in conventional locations compared to other typical applications, so restructuring the main toolbar to have a lot more features and shortcuts, and making it more intuitive based on experience from other applications would really help to improve the usability.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
