### ISSUE TITLE
Func call not working with AnimationTree + BlendTree as root

### ISSUE THREAD

**Issue by N8n5h** [godotengine/godot#25950]
**Godot version:**
v3.1.beta.custom_build.be98a6e

**OS/device including version:**
OS: Ubuntu 18.04.1

**Issue description:**
Method calls in animation clips are not being triggered when the animation is played on an AnimationTree with an AnimationNodeBlendTree as a tree root.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/2872250/test.zip)

**Comment by wojtasss** [comment]
@N8n5h did you find workaround for this bug?

**Comment by wojtasss** [comment]
@akien-mga why this bug was moved to 3.2 milestone? this is very important functionality

**Comment by torresguilherme** [comment]
@wojtasss @N8n5h I found a workaround that's not very pretty, but basically, if you put another call func track in the function being called at OneShot, it works. Also the "idle" function which calls the animation_started() function in your example needs to be in a loop. The call func track in rotate doesn't have anything on it, but without it the idle call func track breaks. Don't ask me why, but here's a working example.
[animation-tree-bug.zip](https://github.com/godotengine/godot/files/2975372/animation-tree-bug.zip)

**Comment by Calamander** [comment]
Actually problem lies with 3D transform type track and track order, if you remove both transform tracks (or the one from rotate animation) - function call works.
If there is only one animation run by AnimationTree which have 3d transform track preceded somewhere by function call (animation tracks over same node) - call won't work.
But if you run animation from AnimationPlayer then there is no problem - everything works.
Which means processing 3d transform track somehow breaks future function call.

**Comment by Calamander** [comment]
I found source (or at least root) of the problem, but am not sure how to fix it.
Problem is the following: function call is not working indeed because of 3d transformation track, but the reason for that is that both track types lack property name. Tracks caches are stored by paths along with track types (animation_tree.cpp/AnimationTree::_update_caches), but when you create 3d transform type track or function call over same node their default path name is the same - path to the node itself, so godot confuse them for one another, skipping "wrong" track because it's saved type is different from the one cached last.
To fix this 3d transform and function call track types should be given unique names, but I'm not sure which ones, because they aren't real node properties (I don't know where and how to do it, hope someone will pick this up).
As for workaround conflicting names can be set manually across all animations used in AnimationTree like this ".:func1" or ".:tran1" (where "." is target node and ":func1" made up property name):
![2019-03-18_01-49-57](https://user-images.githubusercontent.com/8860283/54500733-33e5f380-4920-11e9-855b-ae3be82a32c8.png)

**Comment by N8n5h** [comment]
@wojtasss Ok, I had time to look at this again and answering your question: I pretty much just gave up and manually timed animation ending in code, which is cumbersome but it works.
@Calamander It's pretty cool that you could find what causes the issue with the minimal project, but with a rig the workaround seems impossible: having to manually rename every track for every anim for every bone it's just impossible. So I hope this gets fixed soon.

**Comment by IllusiveS** [comment]
I do believe i fixed it in #32509
Can someone else confirm it?

**Comment by rcorre** [comment]
@IllusiveS your PR seems to fix it on my end. Great work! This was one of the most annoying Godot issues for me.

**Comment by aclave1** [comment]
Has anyone found a workaround for this? I'm not able to detect when an animation ends without polling the current state every frame

**Comment by aclave1** [comment]
I just tested this on 3.2 and it works with the test scene posted.

**Comment by rcorre** [comment]
Both call method and audio stream tracks are working for me as well. This is great! :tada:

**Comment by akien-mga** [comment]
Great, closing as fixed then.

**Comment by DuncanSparks** [comment]
I still can't get this to work with either a BlendTree or a StateMachine. I've tried it in both 3.2.1 and 3.2.2, and the function call tracks aren't working when used together with 3D transform tracks.
