### ISSUE TITLE
Area2D mouse entered signal does not fire if there is a ColorRect node behind the Area2D node

### ISSUE THREAD

**Issue by D1AS** [godotengine/godot#25964]
**Godot version:**
3.1.beta4.official

**OS/device including version:**
MacBook Pro
AMD Radeon HD 6770M 1024 MB
Intel HD Graphics 3000 512 MB

**Issue description:**
When moving the mouse over the Area2D node the Label node should display the text "Entered" but it doesn't.

**Steps to reproduce:**
Run the sample project and move the mouse over the Area2D node.

Next, delete the ColorRect node and run the project again. Now, the Label node displays the text "Entered" when the mouse goes over the Area2D node.

Note: the project runs as expected when a Sprite node is used in place of the ColorRect node.

**Minimal reproduction project:**
[TestCanvasLayerArea2D.zip](https://github.com/godotengine/godot/files/2872482/TestCanvasLayerArea2D.zip)

**Comment by mrcdk** [comment]
You need to set the `ColorRect`'s `Mouse filter` property to `Ignore`. With `Stop` or `Pass` it will eat all the mouse events because the control's inputs are processed before collision objects inputs. More info about how inputs are processed here https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html
