### ISSUE TITLE
KinematicBody2d move_and_slide function, The value returned by a collision at a particular location is not normal

### ISSUE THREAD

**Issue by myhalibobo** [godotengine/godot#25967]
Godot version:3.1 beta4
Platform:win7
As shown in the figure below, now that my character is jumping up, and the character and platform are in this particular position, my velocity (-800,-484), at which point the character should have moved up.But move_and_slide() returns velocity(-800,0). This is incorrect.This should be a special case
![ep6qqfbk 09ew88jmo_w gq](https://user-images.githubusercontent.com/8662169/52910274-2cefa500-32d0-11e9-9ee4-e9413cbb3c92.png)

Link to minimal example project:
[New Game Project.zip](https://github.com/godotengine/godot/files/2876276/New.Game.Project.zip)

**Comment by akien-mga** [comment]
Can't do anything without an actual project to test on.

**Comment by myhalibobo** [comment]
@akien-mga I've uploaded dome

**Comment by sicienss** [comment]
Yeah, this seems like the same issue I just posted about in #30509, thanks for referencing it @myhalibobo. Thanks also for uploading the minimal example.

**Comment by KoBeWi** [comment]
Still valid in 58f5c2b

**Comment by capnm** [comment]
I can confirm #42574 fixes the issue (broken in 3.2.3.stable) in the 3.2 branch.

**Comment by Rhathe** [comment]
Have another test case showing this particular bug as well as #43012 but for one way collisions, difference is that it's broken in both 3.2.3.stable and the 3.2 branch of #42574.

![snap_on_top](https://user-images.githubusercontent.com/1882199/98316925-5c18df00-1fa9-11eb-9c95-759f7ce339c4.gif)

[test_move_one_way_snap_on_top.zip](https://github.com/godotengine/godot/files/5498433/test_move_one_way_snap_on_top.zip)

**Comment by capnm** [comment]
> Have another test case showing this particular bug

Yes, you can probably construct an infinite number of extreme cases where the physics engine breaks.
Funnily enough, it works well if you just save and run your binary scene blob as tscn ;-)

**Comment by Rhathe** [comment]
> > Have another test case showing this particular bug
> 
> Yes, you can probably construct an infinite number of extreme cases where the physics engine breaks.

Not sure what makes this a particularly extreme case, not that it should necessarily be invalidated even if it was. The velocity isn't that fast(just 8 pixels horizontally and vertically per frame), the angle of approach is just 45 degrees, and aside from one y-value of 292.05, all positions and extents are whole numbers.  

> Funnily enough, it works well if you just save and run your binary scene blob as tscn ;-)

Did test that out, and yes the tscn version somehow works with this for some reason. Doesn't actually fix the bug though, because just changing the y-value from 292.05 to 300 gives this in 3.2.3 stable.

![snap_on_top](https://user-images.githubusercontent.com/1882199/99486577-713f2780-2932-11eb-95b3-d30386bcd4e5.gif)

Which means that now all values are whole numbers, so this would actually show up more readily if you make a game with objects that try to stick to a grid. This version of the test case is not broken on #42574 though.

[test_move_one_way_snap_on_top_stable.zip](https://github.com/godotengine/godot/files/5557913/test_move_one_way_snap_on_top_stable.zip)

**Comment by madmiraal** [comment]
@Rhathe Your examples are duplicates of #43012 i.e. they're not specific to one-way collisions.
