### ISSUE TITLE
Light2D rendering problems with rotating normal mapped sprites

### ISSUE THREAD

**Issue by lajox666** [godotengine/godot#25969]
**Godot version:**
3.1.beta.4official

**OS/device including version:**
Win7-64bit

nvidia gtx 1060 / 23.21.13.8792

**Issue description:**

lighting of rotated sprites looks weird

**Steps to reproduce:**
see project
[Light2D-Bug.zip](https://github.com/godotengine/godot/files/2872936/Light2D-Bug.zip)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
> lighting of rotated sprites looks weird

Could you be more specific on what "weird" is in this context?

I tried the project in the current master branch and it seems to work fine. The only weirdness is that the "wrong" side of the sprite seems to be lit, but that's due to the normal map you're using.
Using a normal map generated by https://azagaya.itch.io/laigter with Invert Y, it works fine.

**Comment by lajox666** [comment]
Seems to work fine with inverted maps. Thanks for looking into this.
