### ISSUE TITLE
Default ui_focus_next and ui_focus_prev Misreport

### ISSUE THREAD

**Issue by Gastronok** [godotengine/godot#2597]
It looks like the default Input Maps for ui_focus_next (Tab) and ui_focus_prev (Shift + Tab) don't work as expected. If you create an empty project with the following code:

    func _ready():
        set_process(true)

    func _process(delta):
        if Input.is_action_pressed("ui_focus_next"):
            print("Tab")
        if Input.is_action_pressed("ui_focus_prev"):
            print("Shift + Tab")

both "Tab" and "Shift + Tab" will be printed if you press either Tab or Shift + Tab. I wonder if the Shift modifier is accidentally being ignored.

**Comment by akien-mga** [comment]
I can confirm the issue in the current master branch.

**Comment by reduz** [comment]
This is not a bug, this is by design. It should behave exactly like this.

Input.is_action_pressed() is intended to handle multiple keys at the same time. It allows common behaviors such as using WASD to move around in an FPS while holding shift to run faster, for example and all key combinations must be detectable.

**Comment by akien-mga** [comment]
But why does pressing "Tab" only trigger the "ui_focus_prev" action which is bound to "Shift + Tab"?

**Comment by reduz** [comment]
The function ignores the modifiers
