### ISSUE TITLE
SailfishOS port

### ISSUE THREAD

**Issue by savegame** [godotengine/godot#26018]
I am using sources from two pull request 
 - https://github.com/godotengine/godot/pull/16470
 - https://github.com/godotengine/godot/pull/9435  

and build Godot engine for SaiflsihOS. 

**What is done**
- export from [Godot Editor](https://github.com/savegame/godot/releases/tag/v3.2.1-stable-sailfish) with SaiflishSDK to native for sailfish RPM package.
- touch screen input
- dynamic orientation events 
- dynamic orientation change
- normal application life cycle 
- sound initialization
- joypad (just compile already exists **libudev** implementation of LinuxJoypad, works nice )
 
**What is not done**
- gyroscope/accelerometer events
- disable screen blanking when application is open ( just need use some dbus interfaces from mce)

Sources are here: 
https://github.com/savegame/godot/tree/3.2_sailfish_sdl2

PR [here](https://github.com/godotengine/godot/pull/38642)

**Comment by eon-s** [comment]
Look here https://docs.godotengine.org/en/3.0/community/contributing/

**Comment by fire** [comment]
I don't know if importing the entire SDL source code will be accepted.

**Comment by savegame** [comment]
I can rewrite it to pure Wayland, or make render inside Qt/QML.  but I have to be sure that my work will not be in vain and the port on SailfishOS will be accepted in Godot ;-) but i really like SailfishOS and Godot Engine looks best game engine for that platform = )

**Comment by fire** [comment]
You may be able to use the wayland implementation for Godot. https://github.com/godotengine/godot/pull/23426

**Comment by savegame** [comment]
Ok, i have an another question:
For build this branch on SailfishOS, need SailfishSDK (or Sailfish Docker image), all build commands are looks like:
```
ssh -i key_for_build_machine cd $workind_directory && sb2 -t  SailfishOS-3.0.0.8-armv7hl  scons -j 8 platform=sailfish target=arm bits=32
```
i mean, **scons** run inside virtual machine, but its not compatible with Godot's CI  (its Travis CI ? )
what i need to do in my side, for making right settings for building in your CI
should all build commands look like this:
```
export SAILFISH_SDK_IP=10.0.2.15
export SAILFISH_SDK_KEY=/home/developer/sailfish_sdk/ssh_keys/root/key
# where we mount Godot Engine sources
export SAILFISH_GODOT_WORKDIR=/home/src/Godot
# then call build
scons -j 8 platform=sailfish target=arm bits=32
```
and inside scons build script call ssh with right parameters ? 

P.S. Really sorry for my English :flushed:

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by savegame** [comment]
Issue moved to https://github.com/godotengine/godot-proposals/issues/914
