### ISSUE TITLE
DirectionalLight2D for global light imitation

### ISSUE THREAD

**Issue by Metalmastery** [godotengine/godot#26013]
**It's a request to implement DirectionalLight2D node**

**Area of usage:**
 - space games
 - top-down "outdoor" scenes
 - platformer\metroidvania games with "outdoor" scenes

**Features desired:**
 - shadow casting 
 - shadow gradient or sharp cutting depending on shadow length parameter
 - zero light  fall-off on any distance from pivot point

**Existing workaround:**
For now it's possible to use a workaround with Light2D with huge `position` numbers like (10000, 10000) and `offset` opposite to position (like (-10000, -10000)). But it requires a lot of adjustments for scaling and positioning to make it work in some acceptable way. Also it's impossible to use `shadow_gradient_length > 0` due to big distance numbers. And the shadows are newer really parallel.

![ezgif-4-ea4a9a95b148](https://user-images.githubusercontent.com/1368619/52950149-e741e380-3386-11e9-9ef8-7f29a6272e7c.gif)

**Comment by AndreiBochar** [comment]
And for isomteric games too. 🥇

**Comment by TotCac** [comment]
Absolutely +1

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
