### ISSUE TITLE
Main Editor: add the ability to save/restore layout across projects

### ISSUE THREAD

**Issue by nathanjwtx** [godotengine/godot#26031]
Godot 3.1 Beta 5 on Windows 10

I'd like the option to be able to "save" my preferred editor layout so that I don't have to drag the various panes etc. around when starting a new project. From asking around on Discord etc. this doesn't seem currently possible.

**Comment by akien-mga** [comment]
You can do this already:
![screenshot_20190219_090702](https://user-images.githubusercontent.com/4701338/52999313-ba90d900-3425-11e9-88b7-8d9c89f45849.png)

You can even override the "Default" layout to get it applied on all your projects using the Default layout.

**Comment by nathanjwtx** [comment]
Whilst this does save my layout, in Beta 9 at least, I have to re-apply my saved settings each time I open Godot. I'd like to be able to set it once and then forget about it.

**Comment by akien-mga** [comment]
That's a bug in beta 9 specifically, already fixed in master.

Le samedi 2 mars 2019, Nathan <notifications@github.com> a écrit :
> Whilst this does save my layout, in Beta 9 at least, I have to re-apply
my saved settings each time I open Godot. I'd like to be able to set it
once and then forget about it.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/AMaG46RZYfB0zAieqL0ltSkVVKOjCxu-dZ29Ouii4kZTyTBjua1ORK2h9qqDO-ArmWItXc-fdmRIs_fI_Mln9gTGalYGBCq_VW3lz9pzZqB_DkE0M8DTPmb0_707z1pdbpDPXdXxXYgcz32-QnfEl-beWw=s0-d-e1-ft#https://github.com/notifications/beacon/AEe8mp80zJ9WlVyCbxaCZjD0at46G1Dmks5vSnbsgaJpZM4bBoiz.gif>
