### ISSUE TITLE
Navigation cost per tile

### ISSUE THREAD

**Issue by Wend1go** [godotengine/godot#2605]
Right now the navigation logic chooses the shortest path possible on a tilemap but under certain circumstances this isn't always the best one.
Imagine the player needs to cross a river. The shortest way would be to wade just right through it. But if there is a bridge in vicinity it would be better to cross the bridge instead of the river (it it isn't blocked some way).
To achieve this tiles would need a property that marks the cost of passing it.

**Comment by reduz** [comment]
Navigation classes, both 2D and 3D are missing a NavigationAgent node,
which can have a cost, manage tunnels, do local obstacle avoidance, etc.

**Comment by kubecz3k** [comment]
If this is the case, then it also should be possible to change cost basing on unit type (car will go faster on the road but for trooper it doesn’t matter if it's a road or a grass)

**Comment by okamstudio** [comment]
maybe, not sure how to implement this though. Something related to
NavigationMesh/NavigationPolygon I guess?

On Thu, Oct 15, 2015 at 9:25 AM, kubecz3k <notifications@github.com> wrote:

> If this is the case, then it also should be possible to change cost basing
> on unit type (car will go faster on the road but for trooper it doesn’t
> matter if it's a road or a grass)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2605#issuecomment-148370342>.
>



-- 

*OkamStudio*

**Comment by kubecz3k** [comment]
Well I didn't use Godot navigation features yet, but I usually had function in agent that takes as parameter navigation node type and returns cost for that type, so from what reduz said maybe it might be a good idea to just add that kind of function to NavigationAgent. (But I don't know how this stuff works in Godot, this is why I deleted my previous post - it was still couple minuters before @okamstudio reply to it. Anyway you can still read my previous if you unfold @okamstudio reply. Sorry for that!)

**Comment by bojidar-bg** [comment]
Is this fixed/workarounded by the recent additions of AStar, and is it still something to be done?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by akien-mga** [comment]
This is fixed in 4.0 by the new NavigationServer.
