### ISSUE TITLE
GDScript: unavoidable warning about unused arguments

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#26056]
**Godot version:**
3.1 beta 4

**OS/device including version:**
Linux 64

**Issue description:**
Signal callbacks must have the same number of parameters as the arguments passed by the corresponding signal, even if some of them won't be used. 
I noticed that using double underscores like this `func _input_event(__, event, __, __, __):` supresses the warning, but I'm not sure if it a bug or an undocumented feature, since I couldn't find it in the docs.

**Comment by akien-mga** [comment]
> I noticed that using double underscores like this `func _input_event(__, event, __, __, __):` supresses the warning

Actually a single underscore should work too, that's indeed the expected behaviour.

I can imagine many users being confused by this warning though. There were already several reports about this.

@vnen Maybe this warning could be made to ignore methods starting with an underscore (typically callbacks with predefined arguments), at least by default. There could be an option (opt-in) to also enable usage checks for arguments of those methods too.

**Comment by noidexe** [comment]
> Actually a single underscore should work too, that's indeed the expected behaviour.
Single underscore gives me a "Parser error: Expected identifier for argument"

**Comment by akien-mga** [comment]
Ah right, it's single underscore + a name. e.g. `func _process(_delta)`.

**Comment by eon-s** [comment]
Is this documented? Is the first time I have seen that (underscore thing).
Maybe the error message can suggest to do it too?

**Comment by Xrayez** [comment]
Single underscore should also work, AFAIK one can [discard](https://docs.microsoft.com/en-us/dotnet/csharp/discards) variables in C# that way.

**Comment by willnationsdev** [comment]
@eon-s The single underscore trick isn't documented [here](https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/static_typing.html) at all. The static typing documentation is also outdated as the GUI pictures displayed no longer exist, and there is no "ignore" shortcut to automatically insert an ignore statement. There isn't even a tooltip or description anywhere detailing what the "key" for the warning is. The warnings panel just displays a description and line number without the `unused_variable` or `unused_return_value` or what-have-you that you would need to type in a `#warning-ignore:`. I have to jump to the ProjectSettings and fish around in the warnings list to identify which rule's name I'm most likely violating. And then I have to memorize those rules (which is ridiculous) so that I don't have to keep looking it up over and over.

**Comment by vnen** [comment]
@willnationsdev which version are you using? Just tested with `master` (a38bf5287) and it does have the warning name and the shortcut to ignore.

![gdscript-warning](https://user-images.githubusercontent.com/5599796/54028640-6f482b80-4184-11e9-8e58-14eff1a31f67.png)

Maybe you are mistaking it with the debugger one (which is only shown when you run the project):

![gdscript-debugger-warning](https://user-images.githubusercontent.com/5599796/54028745-d5cd4980-4184-11e9-915a-f7f14387d128.png)

----

About the issue, what's missing is only documentation, as you can already use an underscore prefix to show you're not using the argument.

**Comment by eon-s** [comment]
Maybe the underscore on parameters should be added by default, is not a breaking change and may save some headaches.

**Comment by akien-mga** [comment]
> Maybe the underscore on parameters should be added by default, is not a breaking change and may save some headaches.

That would defeat the purpose of having checks in the first place.

**Comment by eon-s** [comment]
@akien-mga maybe... but I bet most of the time `_process` is utilizing without the need to use delta, and signal callbacks (like CollisionObject ones) with few or no parameters used.

User made functions are something else, and the warnings will still work there.

**Comment by willnationsdev** [comment]
@vnen ahhh, yes. I was confusing it with the debugger one.

**Comment by Chaosus** [comment]
Related to #21102

**Comment by bojidar-bg** [comment]
Related to #7599 as well.

**Comment by pouleyKetchoupp** [comment]
What about a GDScript function that would be only used to suppress a warning on a specific argument?
```
func _process(delta):
    unused(delta)
```
It could be used to suppress warnings on local variables too:
```
for i in range(0, count):
    unused(i)
    # do something
```
This way could be clearer and easier to find in the documentation.

**Comment by eon-s** [comment]
I have seen too that locally unused but globally used variables also get this warning, it needs some kind of macro or something to ignore those kind of variables in an explicit way.

@pouleyKetchoupp underscore is easier to use than an extra line with a dummy function, gdscript may need a better documentation for the specification, also the debugger.

**Comment by Dragoncraft89** [comment]
I'd propose adding a help statement to the warning.\
Something like: `Consider prefixing with an underscore: _variable_name`

That's exactly what the Rust compiler does, for example.
