### ISSUE TITLE
Using TIME in shader decreases editor FPS

### ISSUE THREAD

**Issue by marcosbitetti** [godotengine/godot#26082]
Godot v3.1.beta.custom_build.9f57939

Linux no GPU (Intel i7 with integrated gpu)

Using TIME in shader decrease performance! See video

I make a shader, just add TIME to fragment expression

![capture](https://user-images.githubusercontent.com/85936/53083756-4403e200-34de-11e9-864d-c7fa50e96435.gif)

**Comment by akien-mga** [comment]
As discussed on IRC with @mrcdk and @JFonS, using `TIME` does not actually significantly impact the performance of the game.

What you see here is the *editor* FPS, and using `TIME` causes the editor to redraw at each frame to take this into account while previewing the shader.

I did a small test locally, and I have the same *running* performance on a simple project whether I use `TIME` or not (surprisingly even *better* when using `TIME`...).

Shader used on a simple `CubeMesh`:
```
shader_type spatial;

void fragment() {
        ALBEDO = vec3(abs(sin(TIME)), abs(cos(TIME)), 1.0);
}
```

**Comment by akien-mga** [comment]
I'll add a tooltip to the Label to make this clear.

**Comment by starry-abyss** [comment]
I don't get it honestly... The time shown should be the time it takes for a frame to be drawn (that is, the value doesn't care how frequently the editor draws a frame).
If it shows something else, even if editor-only, it's probably broken currently??

**Comment by akien-mga** [comment]
@starry-abyss Well, how do you measure the time it takes to draw a frame when the whole editor is a single process, a single window, and thus a single frame?

**Comment by starry-abyss** [comment]
@akien-mga OK. But if TIME really forces more frequent updates, I think then the frame amount without TIME is calculated incorrectly.
I mean, the editor knows on which of the frames updates happen (because it triggers those), so it should be possible to use this actual number for FPS meter instead of the big number.
Well, that would probably mean something like FPS: 1 (1000 ms), but at least less confusing and should hint that low-processor mode should be switched off (I assume) or something?

**Comment by OBKF** [comment]
I can confirm this. my laptop ramp-up the fans when I use `TIME` in shader, and I think this is related to #24705 (Playing AnimationTree causes performance drop in the editor)
Ps: I want to re-open this issue
