### ISSUE TITLE
Allow Spatial Shaders to get current texture data.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#26094]
Hi, I'm currently using an animatedPlayer to control an animatedSprite3D animations and it works.
My problem currently is that I need a shader to replace some of the sprite colors, but It seems Spatial Shaders don't have the TEXTURE value canvas_item shaders have.

I wanna know if there's a way to get the current texture data on a spatial shader, since the texture of the animatedSprite3D node is being overriden by an animationPlayer Node.

**Comment by akien-mga** [comment]
CC @clayjohn in case the feature does exist already.

**Comment by clayjohn** [comment]
It doesnt, you need to create a texture uniform and attach the texture in the material right now.

**Comment by ca3games** [comment]
> It doesnt, you need to create a texture uniform and attach the texture in the material right now.

The animatedSprite3D texture gets overriden with the animationPlayer Animation, I've tried to attach an uniform texture data and it uses the one that was set up by the animationPlayer.

**Comment by clayjohn** [comment]
Maybe i misunderstood the original question. 

Are you asking how you can access a texture bound to an animatedSprite3D in a shader? Or are you asking how to access a texture that has been overriden by another texture?

Im a little confused. Because you seem to be asking for an equivalent to "TEXTURE" but in spatial shaders. But you also seem to be having a different issue and that is that you want to access a texture after it has been overridden from a different node. 

Right now, either way the process is going to be passing in the texture that you want using a uniform sampler2d in a ShaderMaterial.

**Comment by ca3games** [comment]
> Maybe i misunderstood the original question.
> 
> Are you asking how you can access a texture bound to an animatedSprite3D in a shader? Or are you asking how to access a texture that has been overriden by another texture?
> 
> Im a little confused. Because you seem to be asking for an equivalent to "TEXTURE" but in spatial shaders. But you also seem to be having a different issue and that is that you want to access a texture after it has been overridden from a different node.
> 
> Right now, either way the process is going to be passing in the texture that you want using a uniform sampler2d in a ShaderMaterial.

I want to make a Shader to swap colors in a AnimatedSprite3D node, so far I've been able to tint all the sprite by setting the ALBEDO to an uniform vec4 hint_color, however I want to swap only selected colors from the fragment shader if the pixel from the original texture is a certain color.

However I've tried to do this, but since the AnimatedSprite3D animation is controlled by an AnimationPlayer, even if I set the ALBEDO to an uniform texture, it gets overriden by the texture from the animationPlayer.

English is not my native language, so I'm unsure how to properly explain it.

**Comment by clayjohn** [comment]
I think i understand. You want to be able to read the texture that is coming from the animationPlayer in the shader. 

So to confirm, this is not currently possible. But in the future maybe a "TEXTURE" built in could be added similar to the one that canvas_item shaders have.

**Comment by ca3games** [comment]
> I think i understand. You want to be able to read the texture that is coming from the animationPlayer in the shader.
> 
> So to confirm, this is not currently possible. But in the future maybe a "TEXTURE" built in could be added similar to the one that canvas_item shaders have.

Is there any temporary solution to my issue?

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
