### ISSUE TITLE
VideoPlayer stream from URL 

### ISSUE THREAD

**Issue by shawkes** [godotengine/godot#26127]
It appears only local resources can be used (videostream extends resource). So you can't just use an arbitrary filestream. 

I'd assume this is best to tackle if when FFmpeg gets integrated with videostreamgdnative (if deemed a worthwhile feature).

**Comment by hpvb** [comment]
This should be added to the VideoPlayer class, after that GDNative will also get it. I suggest this gets implemented using Godot's internal HTTP client to ensure that we use the same certificates etc for https streams.

**Comment by n-k-chilagani** [comment]
From what I understand is we need to use Godot's internal HTTP client to play videos from the given URL.

**Comment by swarnimarun** [comment]
@hpvb I reviewed the problem a bit not sure if it's really a Junior Job, you might want to add additional details....

**Comment by hbina** [comment]
I would like to work on this problem, care to provide me with some help?

**Comment by jamie-pate** [comment]
I'm attempting to do this in gdscript, but the VideoPlayer, VideoStream interfaces aren't very helpful. :(

So far I can download the first ~6MB of a stream, then start playing it, but the decoder/player/stream give no feedback on whether or not they succeed while playing :(

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
