### ISSUE TITLE
ability to get and set current used stylebox

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#26163]
Godot version: 3.0.6
Windows 7 Home 64 bit

please add a way to set a and get the currently active stylebox of a control.
this would allow for more dynamic overriding of style boxes like so..
	extends Panel

	export(NodePath) var control

	var _is_pressed     = false;
	var _is_focused     = false;
	var _is_disabled    = false;
	var _style_normal   = null;
	var _style_pressed  = null;
	var _style_focused  = null;
	var _style_disabled = null;

	func _process(delta):
		_process_widget();
	func _process_widget(delta):
		if   (_is_disabled): draw_disabled()
		elif (_is_pressed ): draw_pressed()
		elif (_is_focused ): draw_focused()			

	func draw_normal():
		if (_style_normal != null):   $Button.current_style = _style_normal;	
	func draw_pressed():
		if (_style_pressed != null):  $Button.current_style = _style_pressed;	
	func draw_focused():
		if (_style_focused != null):  $Button.current_style = _style_focused;
		yield( get_tree().create_timer(0.5), "timeout" );
		if (_style_normal  != null):  $Button.current_style = _style_normal;
		yield( get_tree().create_timer(0.5), "timeout" );
	func draw_disabled():
		if (_style_disabled != null): $Button.current_style = _style_disabled;	

the way this would work is that instead of switching the stylebox internally with a conditional check it would store it in a variable and allow access to it via gd script

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
