### ISSUE TITLE
AnimationPlayer: play only a section of an animation defined by keys

### ISSUE THREAD

**Issue by Tercus** [godotengine/godot#26174]
**Godot version:** 3.0.6

**OS/device including version:** KDE neon User Edition 5.15

**Issue description:**

You cannot make the animation player play only a certain part of an animation through code. Since the keys signify a change inside the animation, it would make sense to be able to use them as start and endpoint.
You can use seek() to jump to a certain point in time in the animation, but you can't make it stop playing at one (not without an extra timer).

**Steps to reproduce:**
Create an animation with multiple keys.
Try to only show parts of the whole animation

**Minimal reproduction project:**
The user "alvar" asked for help with this problem. The attached file contains a test-scene and shows how difficult a possible solution is.
[alvar - AnimationKeyJumping.zip](https://github.com/godotengine/godot/files/2896284/alvar.-.AnimationKeyJumping.zip)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
