### ISSUE TITLE
AnimationPlayer: copy individual keys through code

### ISSUE THREAD

**Issue by Tercus** [godotengine/godot#26175]
**Godot version:** 3.0.6

**OS/device including version:** KDE neon User Edition 5.15

**Issue description:**
You can't copy an individual key from one animation track to another. You have to "get key data" -> "add key" -> "set new keys data".
It would make sense if I could specify a source animation, source track and source key and copy that info to a target animation, target track and target key.
Keys can be copied in the editor, but not through code.

**Steps to reproduce:**
Create an animation with multiple keys.
create a new animation
try to copy only some keys from the first animation to the empty new animation

**Minimal reproduction project:**
This problem became clear, when I tried to solve a different issue (#26174). The attached file contains a test-scene and shows how difficult a possible solution is.
[alvar - AnimationKeyJumping.zip](https://github.com/godotengine/godot/files/2896284/alvar.-.AnimationKeyJumping.zip)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
