### ISSUE TITLE
Builtin scripts do not respond to "tool" keyword

### ISSUE THREAD

**Issue by xDGameStudios** [godotengine/godot#26178]
**Godot version:**
Godot 3.1 Beta 5

**OS/device including version:**
OSX Mojave & Windows 10

**Issue description:**
Nodes with builtin scripts that inherit from other scripts don't respond to the "tool" keyword
for example:

#test.gd
```
tool
extends Node
class_name MyClass

func _init():
    print("init");
```

if you create a scene with this node every time you save/reload "init" gets printed to output.

#Node with builtin script inheriting MyClass
```
tool
extends MyClass
```

saving/reloading doesn't output anything.
even the code below doesn't work.

```
tool
extends Node

func _init():
	print("a");
```

**Comment by KoBeWi** [comment]
So, this works, but you need to reload the script. For some reason this is sometimes difficult to do, because even if you close the scene, the script is cached somewhere and you have to reload project to make it update (this not always happens though). This is problematic, but the actual problem is more similar to #15406, so closing this.
