### ISSUE TITLE
Center current line when setting cursor position in a TextEdit

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#26206]
Godot 3.1+

When using `TextEdit.cursor_set_line()`, the view almost always end up with that line at the very top or at the very bottom depending on where the cursor was initially. I would like that line to be centered visually, which appears to be done by calling `center_viewport_to_cursor()`, but it's not exposed.

I would also like to have an option to anchor that line at the top instead, so that when I go to that line, the view scrolls in such a way it is at the top, if possible, because sometimes I don't need to show preceding text.

**Comment by akien-mga** [comment]
Related to #24444.

**Comment by tom-jk** [comment]
center_viewport_to_cursor is exposed in gdscript starting in 3.2 (as seen in related issue).

Here's a demo project: [26206.zip](https://github.com/godotengine/godot/files/4997527/26206.zip)

It demonstrates centering and can also make a line appear at the top (jank/hack: it does this by first moving the cursor to the last line, so that it will always travels upwards to the desired line and so is at the top).

**Comment by akien-mga** [comment]
Thanks for testing and making a demo. It seems to me like this issue is pretty much addressed indeed.
