### ISSUE TITLE
No texture alpha on Android/GLES2

### ISSUE THREAD

**Issue by ProbDenis** [godotengine/godot#26211]
**Godot version:**
Godot 3.1 Beta 6

**OS/device including version:**
Manjaro Linux

**Issue description:**
I'm trying to port my 3D game to mobile devices, and it's not going to plan. ;-)
GLES3 is too slow, so I'm using GLES2, which is supposed to run well on mobile. At first the game failed to load any textures, so I disabled ETC2 and enabled ETC compression instead (this should be enabled by default for mobile instead of just failing, but that's a different issue). So now the game does run a lot better on my Android device, but alpha transparency doesn't work any more, and any transparent parts in the textures become black. I suppose this has to do with the texture compression - but is this a bug, or is it intended? Is there anything I can do about it?

**Comment by hpvb** [comment]
This is likely already fixed. Please try our next release, it should drop soon.

**Comment by ProbDenis** [comment]
I just tried it with Beta 7, and it's still the same. No alpha in textures with ETC compression.

**Comment by Calinou** [comment]
According to Wikipedia, [ETC1 does not support compressing images with an alpha channel](https://en.wikipedia.org/wiki/Ericsson_Texture_Compression#ETC1) (unlike ETC2). Perhaps it could be handled internally by creating two textures in the import process instead of one (one with RGB channels, one grayscale that represents the alpha channel)?

**Comment by wombatstampede** [comment]
While using ETC may be possible (see link below) it is as well possible for now to use neither ETC nor ETC2.

@ProbDenis Instead of "Video RAM" remport the alpha textures with "Lossy" (or probably also "Lossless")
I just tried it out with "Lossy" and it worked good on my android device (using GLES2, naturally).
May use more video ram though.

Here's the source for workaround to "enable" alpha on ETC1.
https://web.archive.org/web/20160624152133/http://malideveloper.arm.com/resources/sample-code/etcv1-texture-compression-and-alpha-channels/

**Comment by TIBI4** [comment]
@wombatstampede I can confirm that reimporting with "lossless" will make alphas work again too.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/822, as feature proposals are now tracked on the Godot proposals repository.
