### ISSUE TITLE
VSync in Project Settings and script

### ISSUE THREAD

**Issue by DoctorArst** [godotengine/godot#2621]
Most, if not all, game engines support the ability to toggle vsync on/off from within the system.  If I knew more about OpenGL I would definitely submit a patch, but unfortunately after spending a day trying to understand where to put the following in the Godot source I gave up:

[OpenGL - Swap Interval](https://www.opengl.org/wiki/Swap_Interval)

I know this will only affect Windows and Linux targets, but it's a real pain having the GPU burn unnecessarily just due to some simple switch.  I really wish I could do this myself, but so far I couldn't :( .

Edit: The ONLY way I could get Godot to do vsync was to force vsync globally in the Intel Graphics settings, which is not the most elegant solution since I have to turn it off again for some apps that do not like vsync forced on.

**Comment by Calinou** [comment]
You can already force a maximal FPS count in the project settings. But yes, the ability to force V-Sync should be present in the project settings.

While we're at it, we could have adaptive V-Sync too: make it enabled only if the FPS is above the refresh rate, and disable it when below, to avoid stuttering.

**Comment by okamstudio** [comment]
vsync is forced by the way everywhere nowadays due to compositors. I don't
see any benefit to forcing it off

On Sun, Oct 18, 2015 at 9:33 AM, Calinou <notifications@github.com> wrote:

> You can already force a maximal FPS count in the project settings. But
> yes, the ability to force V-Sync should be present in the project settings.
>
> While we're at it, we could have adaptive V-Sync too: make it enabled only
> if the FPS is above the refresh rate, and disable it when below, to avoid
> stuttering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/okamstudio/godot/issues/2621#issuecomment-149007444>.
>



-- 

*OkamStudio*

**Comment by DoctorArst** [comment]
Setting the maximum FPS doesn't allow for a very smooth exprience when close to the display's sync rate, so that doesn't look good when the display skips a frame every now and again.

On looking at this I think there is something wrong with Intel's driver vsync settings description!  When I have the vsync set to 'Driver Settings' Godot does indeed vsync properly.  But when vsync is set to 'Application's Settings' then Godot loses vsync - counterintuitively!

See attached screenshots.

So to get Godot to sync properly, Intel's vsync setting has to be set to 'Driver Settings'.  I think we can close this, unless someone else has this issue and can't get around it.
![intelhd4600settings](https://github-cloud.s3.amazonaws.com/assets/14952290/10565264/8e89b764-75c4-11e5-9914-0d81c340bfd7.png)
![tetris](https://github-cloud.s3.amazonaws.com/assets/14952290/10565266/939bd4bc-75c4-11e5-804e-f139f668885c.png)

**Comment by romulox-x** [comment]
"vsync is forced by the way everywhere nowadays due to compositors. I don't see any benefit to forcing it off"

(I don't see anything to quote that, so I just copied it...) :)

Forcing it off seems to be of little practical use, except perhaps during testing, but what about forcing it on?

This seems to be the extension for turning vsync on: https://www.opengl.org/wiki/Swap_Interval
If your driver forces it off (like in the above Intel screenshot's "Driver settings", I imagine), there's nothing you can do.  If it's left up to the application, then, it would seem, this gl call works.

Now that I read DoctorArst's post more closely, this sounds like exactly his issue.  If the driver's forcing it, it works.  If it's left up to the application, the driver expects the application to turn vsync on if it wants it.  And we're not doing that.

Any opinions on checking for the platform specific extension at run time to try to force vsync on?

**Comment by tapir** [comment]
I'm working on a fast platformer and I get tears a lot. I was really surprised that when I found out that there were no vsync options in the project settings.

Fixed FPS has absolutely no relevence whatsoever. Vsync means that frame update should wait for the monitor refreshing. Hence the keyword "sync". You can have 60 Hz monitor and spot on 60 fps game yet it doesn't mean they will refresh at the same time.

Libraries like SDL2 and GLFW have swap interval methods. You can just turn vsync on or of easily. To this day, I don't undersand why Godot doesn't use a platform abstraction library. There so much to profit...

**Comment by vnen** [comment]
I'm not diminishing the issue, but want to add a clarification here:

> I don't understand why Godot doesn't use a platform abstraction library.

For what I know, Godot has better multi-platform support than SDL (and had it earlier too). I don't know about GLFW, but with a quick look I don't see it being available for mobile platforms. So that's why Godot has its own abstraction layer.

**Comment by tapir** [comment]
We don't have to use it for every platform. Mobile platforms are OK without SDL2. But sorry for derailing the issue. This is a different one.

Last night, while being brain damaged because of sleep deprevation, I can swear I found a "vsync" option on the Motion Test project options. Was I dreaming @reduz ?  :D

**Comment by adolson** [comment]
+1 for an option to turn on/off vsync. It's broken in virtually every Unity game (despite the option being present in most of them), and it is really, really, REALLY annoying to get tearing.

**Comment by Alex-doc** [comment]
I've added the option in[ this commit here](https://github.com/Alex-doc/godot/commit/1e5b5f4da7911b090a429d8ea50f0f15b424fd41)

I'm not sure if is the neatest way to do this, is for Windows only and defaults to true but someone could find it useful.

Let me know if it is PR worthy.

**Comment by nepitard** [comment]
I get VSync tearing in my platformer too. Hope this commit will be accepted.

**Comment by SuperUserNameMan** [comment]
I'm bringing this one to the surface because I find surprising that vsync is not available into Godot.

Vsync does not just avoid image tearing. It also allow to reduce GPU power consumption and heating.

Vsync is good for the eyes and for the environment. Please someone, save our eyes and the planet by implementing vsync in Godot. 
Thanks for your attention.

**Comment by Alex-doc** [comment]
My implementation seems good so far, but might not be the way everyone wants it, that's why I didn't made a pull-request. If anyone wants to, feel free to use it to make a pull request with it.
(see link in my previous comment for the code).

**Comment by reduz** [comment]
i'll try to give this a check for 2.1

**Comment by stillinthe90s** [comment]
@Alex-doc:
I'm getting the the same "ptrdiff_t" -error as described in this issue's first post: #https://github.com/godotengine/godot/issues/4113 when building for 64bit (using VS 14.0). Could you check if your commit is up to date?

**Comment by Alex-doc** [comment]
I've synced to the latest commit, does it work now?

**Comment by stillinthe90s** [comment]
@Alex-doc: Nope. But I'm not that familiar with GitHub so I may be doing something wrong...
I downloaded the zip archive from [here](https://github.com/Alex-doc/godot/tree/1e5b5f4da7911b090a429d8ea50f0f15b424fd41) and tried to compile it with VS x64 native command prompt.

**Comment by akien-mga** [comment]
Try https://github.com/Alex-doc/godot/tree/master instead.

**Comment by stillinthe90s** [comment]
Works like a charm! Thanks! Exporting seems to be working as well.

**Comment by akien-mga** [comment]
This has been implemented in the master branch.
