### ISSUE TITLE
Dedicated shader editor

### ISSUE THREAD

**Issue by Overblob** [godotengine/godot#26229]
This enhancement proposal is linked to #8069 (and could solve #8746)
However it's not a duplicate since I would like to outline usability problems that Godot users may encounter today (based on personal experience).
I also wanted to keep track here on some IRC comments about this subject.

To put it one way: Godot's shader editor is not user friendly.

I think the bottom panel isn't appropriate for code editing, mainly for 2 reasons:

1.  The bottom panel is context reactive and **autocloses** itself as soon as you click another node. It forces you to reopen it either by opening again the shader file, or by finding it again in the inspector and click the button.

2. Its **height**, while more viable for visual shaders, is  inconvenient for code, which inherently has a vertical layout. And keeping scrolling to find your code is quiet annoying. Okay, you can expand it to occupy the full size of the viewport, but doing so you cannot visualize the shader output anymore.

Being able to see live the results of your shader is too much important to be conceded.

Those issues are kind of flow killers and should be addressed to let better shader coding experience in Godot.

For this I think that shader editor plugins should be implemented as main editor plugins (ie. with 2D, 3D, Script and AssetLib). 
The idea is to take advantage of widescreens to have rather a horizontal layout for code and preview (with horizontal resizing).

For example:
![proposal](https://user-images.githubusercontent.com/31958866/53298582-61171880-3830-11e9-8da2-3f992028c1b8.png)

It could be also useful to add default shapes/meshes to enable quick prototyping:
![proposal_quad](https://user-images.githubusercontent.com/31958866/53298599-9ae81f00-3830-11e9-9ac1-c2d9f7c73514.png)

![proposal_sphere](https://user-images.githubusercontent.com/31958866/53298603-a20f2d00-3830-11e9-87d7-146813fd74df.png)

I quickly discussed theses features earlier with some contributors on IRC.
It had been mentionned that we could benefit from ScriptTextEditor (Gdscript editor layout and functionalities) to keep shader files context and to be able to edit multiple shader files in parallel.
It also had been said that such reworks could/should have to wait for Godot 4.0 for an inspector rework and multi-window support.

I'm not sure if all of this should be implemented at once and thus wait for Godot 4.0. There's maybe other clever ideas or some commitments that could help having such enhancement before. 
But well, I wanted to outline at least those proposals. :)

**Comment by Chaosus** [comment]
The interesting design idea is to merge visual shader and visual script into one dedicated tab "Visual"

**Comment by dreamsComeTrue** [comment]
> The interesting design idea is to merge visual shader and visual script into one dedicated tab "Visual"

yeah baby - let's go with that :D

**Comment by nathanwfranke** [comment]
We should make the "Shader" button invisible until you open a shader file. Then it becomes visible until you close all open shaders. This would keep the top bar simple

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
