### ISSUE TITLE
Add code navigation & history controls and shortcuts

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#26272]
**Godot version:** 3.1 beta 6

I think it would be convenient to be able to go forward and backward through the code history. Currently there is a very limited ability to go through history of opened scripts, but it is not possible to do the same inside a single file.
I came from the Java background and theirs IntelliJ IDEA offers lots of very convenient shortcuts. One of them is `Ctrl+Alt+Left/Right` which navigates you through *places* in the code not only the files.

P. S. In comparison with that IDE the code editor feels very limited, raw and kind of angular. Would it be appropriate to open an issue with list of similar features that current editor lacks?

P. P. S. I can provide a screencast from IDEA if it is not clear enough what kind of code navigation I mean

**Comment by golddotasksquestions** [comment]
> Currently there is a very limited ability to go through history of opened scripts, but it is not possible to do the same inside a single file.
I would really like to be able to assign my 4th and 5th mouse buttons to go back and forth in the cursor position history within a script.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by golddotasksquestions** [comment]
Discussion on this issue moved to https://github.com/godotengine/godot-proposals/issues/954
