### ISSUE TITLE
Error when trying to create a new Image resource from Inspector.

### ISSUE THREAD

**Issue by marmitoTH** [godotengine/godot#26306]
**Godot version:**
Tested in 3.0.6 stable and 3.1 beta 7

**OS/device including version:**
Intel Core i5-6200U/Windows 10

**Issue description:**
I'm trying to write a shader material that creates fake reflections from cubemap, to read the cubemap I'm using samplerCube, on Inspector I've created a new CubeMap for that slot. In CubeMap properties I can't assing textures directly for the sides parameters, so I need to create a New Image resource for each side, the action simply doesn't work and throws this error in console:

`ERROR: set_side: Condition ' p_image->empty() ' is true.
   At: scene/resources/texture.cpp:1337`

This probably happens in other parts of the engine related to this action.

**Steps to reproduce:**
Create a New ShaderMaterial, write uniform samplerCube as parameter, create a new CubeMap resource in material inspector, try to create a new Image resource for any side in CubeMap parameter, read the console.

**Minimal reproduction project:**
I don't think it's project specific, but if it's really needed I can upload an example later.

**Comment by Zylann** [comment]
The problem happens because when you create an `Image`, it starts empty by default (that's what the error is about). To be usable, an image must be given a size, a format and some default fill color.

In 3.1 it is possible to `Load` an image in those slots by changing the import settings of your side images to be imported as Image:
![image](https://user-images.githubusercontent.com/1311555/53416965-7a54cc00-39cc-11e9-9384-a673f41a0d9e.png)

**Comment by marmitoTH** [comment]
Well, yes. I've looked for something like this in 3.0.6 Import tab but not in 3.1, thanks for the info. Anyway, why there's a option for create a new image resource since it's not supposed to work? It still a issue imo.

**Comment by Zylann** [comment]
@marmitoTH the presence of `New Image` is a broader issue which exists for many resource types. For many of them, creating a new instance is almost useless (`AudioStream`, `ArrayMesh`, `Image`, `StreamTexture`, `GIProbeData`...). Maybe in some rare cases it could have its use, but in general those resource types are supposed to be loaded from an existing import rather than created from scratch.

**Comment by clayjohn** [comment]
Sounds like it is fixed in 3.1. Closing.
