### ISSUE TITLE
Can't close game when physics fps are set to 0

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#26321]
**Godot version:**
3.1 beta 6

**Issue description:**
When physics fps are set to 0 the game window can't be closed without code

**Steps to reproduce:**
Set physics fps to 0 and try to close a game

**Comment by KidRigger** [comment]
Found the problem. 
https://github.com/godotengine/godot/blob/60d910b1916305c4b0ac5f92415083995b4f7c7a/main/main.cpp#L1850
The for loop never runs. Since the quit condition is only checked inside the loop, the engine doesn't quit.
Since the quit condition is tied to SceneTree update or idle, can't really let it run. Either the loop can be configured to run atleast once (I don't know the consequences of which) or the physics fps can be set to be constrained to > 0 [Is there a reason to set physics_fps to 0?]
