### ISSUE TITLE
Only duplicate selection when selection is one line

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#26338]
Technically disable #21814/#24574 for multi-line selection.
Now it's just awkward to duplicate multiple lines.

Now:
![godotctrlbnow](https://user-images.githubusercontent.com/12462089/53472350-f6691580-3a99-11e9-82eb-e6ed13bf70a7.gif)

Then:
![godotctrlbthen](https://user-images.githubusercontent.com/12462089/53472352-f8cb6f80-3a99-11e9-9e0b-1e9f3aadbd06.gif)

**Comment by akien-mga** [comment]
CC @SeleckyErik @Paulb23

**Comment by SeleckyErik** [comment]
This seems more like a personal preference to me. I can see reasoning to prefer either of them. Maybe add an editor option to choose which behaviour is used?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
