### ISSUE TITLE
Select the file after opening system file explorer

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26364]
**Godot version:**
3.1 beta8

**Issue description:**
This is a tiny thing, but right now when you right-click file in file system doc and click "Show in file manager", you see this:
![image](https://user-images.githubusercontent.com/2223172/53511759-6939b700-3ac1-11e9-97d6-12e65af5f22b.png)
Yeah, it's just the directory containing the file. Instead of just jumping to directory, wouldn't it be better to also select the file? So e.g. right-clicking icon.png and revealing in explorer shows this:
![image](https://user-images.githubusercontent.com/2223172/53511957-d8afa680-3ac1-11e9-8fa8-ec709f7a1c82.png)

**Comment by groud** [comment]
The idea makes sense, but I am not sure this is possible. That might depends on the OS API to open the file manager, not sure it is supported.

**Comment by KoBeWi** [comment]
In worst case it will require some platform-specific code, but it's possible, as I seen this in Unity.

**Comment by Calinou** [comment]
Note that this requires OS-specific code to be implemented: 
https://forum.qt.io/topic/18157/solved-open-folder-explorer-with-pre-selected-file

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
