### ISSUE TITLE
Implicitly convert to floats in shaders

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26376]
**Godot version:**
3.1 beta8

**Issue description:**
Godot's shading language is designed to be more friendly than normal GLSL, but while it simplifies a lot of things, I get a feeling there's stuff that's still needlessly made more difficult. Something that I always disliked when working with Godot shaders is that you need to write every float operation explicitly. So for example you can't do
`1.0 + 2`
but you need
`1.0 + 2.0`

What's worse, after recent beta Godot enforces you to have all method arguments be of the same type. So my shader with this line
`COLOR = vec4(value, value, 1, max(color.a, 0.5));`
has broken as a result. I know it's not a big deal to add `.0`, but why is it even necessary? Is there any technical reason to not implicitly convert integers to floats where needed, other than for the sake of enforcing type matching? (like in Java, which is terrible on that matter)
Do people care so much about (sometimes unexpected) implicit conversions as to make life harder?

**Comment by clayjohn** [comment]
> Is there any technical reason to not implicitly convert integers to floats where needed, other than for the sake of enforcing type matching?

Yes. It is to be compliant with the GLSL ES3 specification. https://www.khronos.org/registry/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf&ved=2ahUKEwj6mq6bp93gAhUKuJ4KHUa9DiUQFjAAegQIBBAB&usg=AOvVaw3dKLJq9fZByoO6OTRyu4SM

We need to be compliant with the specification so that code written on one computer will work on all others. Before the change, random machines just wouldn't run Godot because they mixed ints and floats. Writing .0 is a small price to pay for being cross-platform. 

> Godot's shading language is designed to be more friendly than normal GLSL

Godot doesnt have its own shading language. It uses GLSL, but it makes shaders easier to write by simplifying shader programs by providing built in functionality, not by using an easier syntax. We are still stuck with raw GLSL syntax.

**Comment by KoBeWi** [comment]
> Godot doesnt have its own shading language. It uses GLSL, but it makes shaders easier to write by simplifying shader programs by providing built in functionality, not by using an easier syntax.

The syntax definitely looks like GLSL, but still has some differences. Don't shaders get some conversion magic before they are sent to GPU, like changing all Godot's symbols into proper stuff etc.? Why wouldn't it be possible to change integers into floats during that conversion?

**Comment by clayjohn** [comment]
> The syntax definitely looks like GLSL, but still has some differences. Don't shaders get some conversion magic before they are sent to GPU, like changing all Godot's symbols into proper stuff etc.?

The variable names are changed slightly so they do not conflict with the built in functions. Other than that, I don't think there is much if anything that happens, other than making sure everything gets inserted into the proper place.

> Why wouldn't it be possible to change integers into floats during that conversion?

It would be possible, but then what if I wanted to use an int and not a float? There are many ambiguous cases where the pre-processor wouldn't be able to tell which to use. Additionally, it would make a shaders slower. 

> I mean, if the editor tells you that it expects float somewhere, it as well could put it itself.

Newer versions of GLSL actually do this for function arguments. It may be possible for function arguments, but you would still be left without it for regular use. But, if it is useful enough for people in may be worthwhile to consider adding implicit conversions in function arguments.

**Comment by KoBeWi** [comment]
> It would be possible, but then what if I wanted to use an int and not a float?

I meant whenever it's needed. Obviously there's no reason to convert all integers, but the one's that would otherwise cause type error.

**Comment by clayjohn** [comment]
> I meant whenever it's needed. Obviously there's no reason to convert all integers, but the one's that would otherwise cause type error.

But there is no way of knowing from looking at the code what it is supposed to be. At some point the pre-processor will have to guess, and then you, the user, will get unexpected output and you won't know why. 

For example take the code ``1+2.0``, from that code, should the result be ``3`` or ``3.0``? Or a more concrete example 
```
if(3.0<2) {
    return max(3.0, 2);
}
```
What would the expected output be? Even inferring what the types are from the function call is impossible. 

That being said. I'm not trying to rain on your parade. I understand your desire for implicit type conversion. I really do. Languages like GDScript are a pleasure to code in. GLSL is much less of a pleasure, however, GLSL is designed to be fast and to give the user full control over the program. Those things are not as easy to provide with implicit type conversion.

**Comment by akien-mga** [comment]
Isn't this fixed by ffb9f342a already?

**Comment by KoBeWi** [comment]
That works only for vector constructors, so fixes only the COLOR line I wrote at the beginning.
`color.g = 1;` doesn't work
`color.g /= 2;` doesn't work
It would be nice if they did.

**Comment by aaronfranke** [comment]
@clayjohn Is this still considered intended behavior, for consistency with GLSL? I think we should just close this.

**Comment by KoBeWi** [comment]
I'd put usability over consistency here. I run into conversion errors every time I write a shader and it's annoying :I
Also I noticed some questions were unanswered.

> For example take the code 1+2.0, from that code, should the result be 3 or 3.0? Or a more concrete example

3.0. Only 1 + 2 would produce 3.

> if(3.0<2) {
    return max(3.0, 2);
}
What would the expected output be? Even inferring what the types are from the function call is impossible.

No output, because the condition is false xd
Right now it produces an error. What I proposed is to convert *mixed* expressions to float. Only integer-only expressions would be processed as integers. So in this example, 2 would become 2.0.

> It would be possible, but then what if I wanted to use an int and not a float?

Then use integers. In (almost?) every programming language, operations with integer and float will result in a float.

**Comment by clayjohn** [comment]
@KoBeWi Thanks for following up. 

I honestly go back and forth on this issue. Some days I feel like it is okay to trade shader speed to make it easier for users. Other days I feel like shaders should be kept fast and powerful so that users who are willing to work with them can get the most out of their shaders. 

I am also concerned that abstracting shaders too much does a disservice to users. GPUs are very particular pieces of hardware. The strangest things can take a shader from running at 60+ FPS to making the GPU crawl. By taking control away from users, we make it more likely they will write shaders that slow down the GPU or outright break rendering in unexpected ways. 

On the other hand. Auto detecting when floats and ints are used together for basic arithmetic should be easy and not slow down the pre-compile process too much. But if we add type-inferenceing for basic arithmetic, users will expect type inferenceing everywhere and then we end up with an extremely slow and complex pre-compiler. 

So, all that to say, I am not sure if this is a good idea or not. At this point it is probably best to go the Godot-Proposals route and see how important this is to other users. Alternatively, we need to test it out and see if it leads to a realistic decrease in speed. In may not.

**Comment by KoBeWi** [comment]
Ok, made the proposal: https://github.com/godotengine/godot-proposals/issues/1223
