### ISSUE TITLE
Changing node type should auto-expand to its current node type

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#26389]
**Godot version:** 3.1 beta 8

**OS/device including version:** Linux, but any/all

**Issue description:**

When I go to change a node's type, the chances are very high that I'm going to be changing it to a similar type. For example, changing a RigidBody to KinematicBody. I am very unlikely to change a RigidBody into a Control or an AnimationPlayer. Therefore, it would make sense to make the "Change Node Type" menu default to having the current type as expanded.

But currently, the "Change Node Type" menu only starts with Node and CanvasItem expanded, so I have to click open Spatial -> CollisionObject -> PhysicsBody to get where I want. This isn't ideal.

Bonus: Changing a type should expand itself, for example, changing a Spatial should auto-expand Spatial, and changing a RigidBody should expand itself to show VehicleBody, etc.

This is very low-priority. Suggested tags: usability, enhancement, topic:editor.

**Steps to reproduce:**

1. Create a node of type RigidBody.

2. Try to change it to KinematicBody.

3. Notice that you have to click through several expandables to get there.

**Comment by veryprofessionaldodo** [comment]
I have been looking into this, but so far unsuccessfully. I'll try again :)

**Comment by veryprofessionaldodo** [comment]
Okay, after a good long look I think I may have got it! I'll issue a pull request, and see if I can do it right the first time. 

After the alterations, when I click to replace, the Change Node Type un-collapses all the direct parents of the node to be replaced. If the selected node is a VehicleBody, then it opens up RigidBody, PhysicsBody, CollisionObject and lastly Spatial. If I choose to replace a Area2D node, it opens up CollisionObject2D and Node2D. Since it Node2D and Spatial are relatively large nodes, it clogs up a bit of space, but I find it counter-intuitive to hide the other nodes that are a part of Spatial or Node2D. 

For that reason I thought it was best to just leave it as it is.

... and only now have I noticed there was already a pull-request. Nicely done.

Oh well, now I'll have mine here too, then you can choose which seems best :)
