### ISSUE TITLE
AnimationTree StateMachine advance conditions to self-disable

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#26408]
AnimationTree state machine transitions can have advance condition. This adds prop which can be set to true/false which enables/disables such transition auto-advancement. This allows for easier enabling transition paths without need to explicitely travel() nodes. However sometimes we need to go into state, wait till it ends and go back. If second transition ("back") is always advances, or enables advcnce condition, the state will be entered again in loop. If both conditions are IMMEDIATE, this will lead to rapid looping. This is not always wanted, but catching condition execution from script by polling to disable it is not possible to do reliably in script. So it would be nice if once triggered, the advance condition could disable itself for second triggering (configurable with parameter). Or some signal to know when transition happens to be able to disable advance condition.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
