### ISSUE TITLE
Separate animation speed

### ISSUE THREAD

**Issue by DDru** [godotengine/godot#26418]
**Godot version:**
3.1

**Issue description:**
The animation speed can only be changed in the AnimationPlayer. In the same animations (like in Unity3D) this can not be done. Because of this, you need to do hardcode in the scripts.
![default](https://user-images.githubusercontent.com/10414783/53598613-ef085000-3bf0-11e9-8066-a338d0029548.PNG)

**Comment by Janders1800** [comment]
If this is referring to being able to change the animation speed per animation in the animation player I can relate.
Right now not being able to do so is a nightmare if you have a considerable amount of animations, or if you just want to tweak just one animation to mach some movement speed etc.

**Comment by avencherus** [comment]
It would be a nice thing to have.  At the moment I don't think Animations explicitly store any speed information.  It's more like something that can be modified as you say, in script, when calling `play()`.  It has an argument to scale the playback.

Currently, the workflow to this is a bit more cumbersome, and involves using the rescaling tool you can find in the Edit menu of an AnimationPlayer editor.

![image](https://user-images.githubusercontent.com/13004169/53623965-4fa28780-3c07-11e9-99d8-bca065dd3205.png)

You select your keyframes, and calculate a scaling, scale it, and change the animation length.  X)

**Comment by DDru** [comment]
@avencherus in Unity, the animation itself also contains only a loop-checkbox. These parameters (speed, mirror) are added to the node in the animation state-machine.
Therefore, one animation can be used several times in different variations.

**Comment by DDru** [comment]
Hello. I see this request cancelled. But why?

Just imaginate simple indie game where for example object can move forward and back with one animations.
In other game engines i can use one animation for these two actions just changing animation speed to positive or negative inside animation state machine with out any coding.
In Godot i can't do it. Me need two same animation but with differend play speed or i should make script where i be set speed.

But what be if i has game with a lot animations? It will be hell.
You can add speed param (as in unity) inside animation node at state machine. And it fixed many problems for user.

![anim](https://user-images.githubusercontent.com/10414783/72688679-5276d580-3b55-11ea-90d4-db8c43788b1f.png)

**Comment by Calinou** [comment]
@DDru This feature request hasn't been "cancelled". It's just that nobody started working on it yet :slightly_smiling_face:

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
