### ISSUE TITLE
Mesh color & custom_data feature from MultiMesh

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#26420]
I've recently implemented MultiMesh support and see it has some extra goodies over a mesh:
-instance_color
-instance_custom_data

I am wondering if we might be able to get these features on a normal mesh also?

**Comment by clayjohn** [comment]
What you are looking for is [uniforms](http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#uniforms). 

Uniforms are the best way to pass data in that will affect the entire mesh. Multimesh only uses instance_color and instance_transform as a way of differentiating meshes because it uses a single draw call. Normal meshes arent restricted in the same way, so you should just use uniforms. They are more flexible and faster.

**Comment by supagu** [comment]
Will that require shader changes to support that? The thing is instance_color in multimesh doesn't need any shader changes to work, I can just tint the model super easy.

**Comment by clayjohn** [comment]
With a spatial material you use the albedo property. And with any spatial node you can set the transform manually.

**Comment by clayjohn** [comment]
Closing as we already have these features.
