### ISSUE TITLE
Autocomplete resource pathes anywhere

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#26479]
**Feature description:**

Would be nice to have editor autocomplete any string starting with `"res://". Since obviously this is a resource path.

**Comment by akien-mga** [comment]
We already do:
![screenshot_20190303_102955](https://user-images.githubusercontent.com/4701338/53693332-4e0bc780-3d9f-11e9-8cb8-fa5d3a702f90.png)

Could you be more explicit about what you want and is not supported yet?

**Comment by drtwisted** [comment]
@akien-mga yes, it's there for `load` and `preload`, but that's it.
I talk about any place in code, like any string, e.g. here:
![example](https://i.imgur.com/Bzn0XPE.png )

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
