### ISSUE TITLE
Parallax background is centered to camera if motion scale set to 0

### ISSUE THREAD

**Issue by breakmt** [godotengine/godot#26470]
**Godot version:**
3.1 beta 9

**Issue description:**
I asked this in Reddit, but still not clear if this behavior is expected or not. 

In short:
If I set ParallaxLayer without mirroring and motion scale x,y = 0 then background is centered to camera center, not where I place it in editor.
![2019-03-02_092331](https://user-images.githubusercontent.com/1552169/53678321-8099bf80-3cce-11e9-8c69-317035ced20b.png)

What I tried to achieve is "static" background, like camera is moving and background still same. 
I can work around this issue and make background centered = true, BUT in this way it will be displayed out of level in editor.

If this expected behavior I will be glad to receive any advice in this theme. Thanks.

**Minimal reproduction project:**
[Parallax.zip](https://github.com/godotengine/godot/files/2921820/Parallax.zip)

**Comment by alexzheng** [comment]
I can confirm the 3.1 stable release still have this bug.

**Comment by MatthewJulian** [comment]
I can also confirm this is still prevalent in the 3.1-stable-release. My version was posted here: https://www.reddit.com/r/godot/comments/b4pu3z/confused_on_how_parallaxlayerthe_camera_work/

**Comment by Xrayez** [comment]
If you set `motion_mirroring` property to something other than `Vector2(0,0)`, this works fine. So for this to work, I set mirroring to `Vector(0.001, 0.001)` just to prevent this. From docs:

> The ParallaxLayer's Texture mirroring. Useful for creating an infinite scrolling background. If an axis is set to 0, the Texture will not be mirrored.

So maybe this should rather be handled via separate properties like `mirror_horizontal_enabled` and `mirror_vertical_enabled` instead. But parallax is buggy enough anyways so yeah something is wrong under the hood.

**Comment by akien-mga** [comment]
Still reproducible in the current master branch.

For 4.0, maybe this API can be reviewed to be made clearer and easier to use?

**Comment by ACB-prgm** [comment]
Still an issue in 3.2.2, but I have a simple solution!

 if you have the Camera2D node's anchor mode set to Drag Center, then the parallax background layers will be offset by the ParallaxBackground's Base_Scale property times offset of the camera from its top-left corner. 

for example, the top left of my camera right now is X:-160, Y:-90 (because my window size is 320x180).  If I set the ParallaxBackground's Base_Scale = 0.5 and I have a parallax layer at the origin (0,0), then that parallax layer will be offset to (0.5*-160, 0.5*-90) == (-80,-45).

Thus, to fix this issue for any given parallax layer, go into the ParrallaxLayer node > Motion > Offset and enter that calculated offset times -1 (so in the above example 80,45).  The reason for multiplying it by -1 is just offset addition. essentially we are offsetting it by the exact opposite amount.

Hope this helps!

**Comment by vix597** [comment]
I ran into this just today trying to get star particles to stay put on a parallax layer by setting the scale to 0, 0. I ran into exactly this issue but fortunately for particles you can check the `Local Coords` off (to be false) and now they stay put while everything else moves around them.

**Comment by Ev01** [comment]
For me this gscript code counteracts the offset to get it in the middle of the camera
```
# Project settings window size
var screen_size := Vector2(1024, 600)

func _ready():
	motion_offset = -(screen_size / 2) + ((screen_size / 2) * motion_scale)
```
This is with camera's anchor set to Drag Center.

**Comment by Ev01** [comment]
When I pause the scene in _ready() the bug does not happen until I unpause the Camera2D.

**Comment by jolsensei** [comment]
I think this is still an issue in 3.5.1
![image](https://user-images.githubusercontent.com/23259484/213509990-318c5f60-b32c-4db3-80ba-598d63071615.png)
![image](https://user-images.githubusercontent.com/23259484/213510293-5f82ca38-7a0c-4303-af2f-b53ab08b4b94.png)

**Comment by madmiraal** [comment]
@jolsensei #58568, the 3.x version of the #58567 fix, hasn't been merged yet.
