### ISSUE TITLE
Remote Node Enhancement

### ISSUE THREAD

**Issue by ndee85** [godotengine/godot#265]
At the moment the Remote Node can control a different node. But always controls all three transformations(Rotation,Position and Scale).
It would be nice if there were 3 checkboxes which can be set. So this way the remote node only controls the checked transformations. Sometimes I want to keep the scale different from the remote node. This way it will give some extra flexibility.

**Comment by eon-s** [comment]
Yesss, I was thinking the same, because found that the node may be useful in many situations if could be restricted to a specific kind of transform.

**Comment by nunodonato** [comment]
I was thinking that the current way that RemoteTransform works is not so good because it totally overrides the position of the target node. Wouldn't it be better if the changes were made on local coordinates?

Right now if my Remote node is in one place and the target node in another, as soon as I move the Remote node, the target node will be teleported to the same position. Wouldn't it be more convenient if by moving the Remote node, the target node would move accordingly, but in its local space?

**Comment by nunodonato** [comment]
or, perhaps, allow two different modes to cover more use cases:

- full transform (as it is now)
- local transform(?) - act on local coordinates and, as requested by this issue, allow to toggle translation/rotation/scale independently

**Comment by bojidar-bg** [comment]
I think Global/Local transform should be separate from toggling translation/rotation/scale... Since both have their uses :smiley:

**Comment by eon-s** [comment]
Yes, "local" option would be useful too.
By default full, local and transform values, if we extend it more, filter by axis too (on 3D may be useful, to move things in a plane o axis).
