### ISSUE TITLE
Android audio input does not properly trigger Microphone permission request

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#26506]
**Godot version:**
bf6398a + #26505 

**OS/device including version:**
Xiaomi Pocophone F1, Android 9
Samsung Galaxy S3, Android 7.1.2

**Issue description:**
When deploying the ["Mic Record" demo](https://github.com/godotengine/godot-demo-projects/tree/master/audio/mic_record) to my Android phones with the "Record Audio" permission checked (and properly written in the AndroidManifest.xml according to `aapt`), Android doesn't seem to ask for this permission during install.

Post-install, the "Microphone" permission is available in the App Info panel, but toggled off by default.
I *think* the normal workflow for a microphone-using app would be to trigger a dialog asking for the permission the first time the feature is used, but this doesn't happen with Godot.

I'm not very familiar with Android permissions yet, so I can't tell if the fault is in the Android port, the audio input feature, the export process or my own misunderstanding :)

Assigning @marcelofg55 but anyone familiar with Android permissions is welcome to chime in.

**Comment by MadEqua** [comment]
Starting on Android 6.0 (API 23) the system does not request permission at install time, the app has the responsibility to ask them at runtime (preferably when actually needed). If the app tries to use some dangerous API without the needed permission will result on a thrown exception.

Running the demo on a API < 23 should request the permissions at install time and everything should work.

The problem is that the Godot exported app is never requesting permissions at runtime.

This [pull request](https://github.com/godotengine/godot/pull/22465) seems to be related but it's not fully functional because it didn't implement anything to request runtime permissions.

To fix this it's probably just a matter of finalizing what was started on that PR and modifying the demo script to request the necessary permissions. I'll try to come up with something.

**Comment by MadEqua** [comment]
With the PR that I submitted above the following code works as expected for the MicRecord demo.

```
extends Node2D

var effect
var recording

var permissions = null

func _ready():
	if Engine.has_singleton("AndroidPermissions"):
		permissions = Engine.get_singleton("AndroidPermissions")
		permissions.init(get_instance_id(), false)
	
	var idx = AudioServer.get_bus_index("Record")
	effect = AudioServer.get_bus_effect(idx, 0)
	pass

# Called when a request dialog is finished
func _on_request_permission_result(request_code, permissions, granted):
	if request_code == 8 and granted:
		record_control()
	pass

func record_control():
	if (effect.is_recording_active()):
		recording = effect.get_recording()
		$PlayButton.disabled = false
		$SaveButton.disabled = false
		effect.set_recording_active(false)
		$RecordButton.text = "Record"
	else:
		$PlayButton.disabled = true
		$SaveButton.disabled = true
		effect.set_recording_active(true)
		$RecordButton.text = "Stop"


func _on_RecordButton_pressed():
	if permissions != null:
		if permissions.isRecordAudioPermissionGranted():
			record_control()
		else:
			permissions.requestRecordAudioPermission()
	else:
		record_control()

func _on_PlayButton_pressed():
	print(recording)
	print(recording.format)
	print(recording.mix_rate)
	print(recording.stereo)
	var data = recording.get_data()
	print(data)
	print(data.size())
	$AudioStreamPlayer.stream = recording
	$AudioStreamPlayer.play()

func _on_Play_Music_pressed():
	if ($AudioStreamPlayer2.playing):
		$AudioStreamPlayer2.stop()
		$PlayMusic.text = "Play Music"
	else:
		$AudioStreamPlayer2.play()
		$PlayMusic.text = "Stop Music"

func _on_SaveButton_pressed():
	recording.save_to_wav($SaveButton/Filename.text)

```

**Comment by akien-mga** [comment]
If we can avoid the need to request permission manually, that would be better. It should be the engine's job to request the permission when using a permission-bound feature.

**Comment by BastiaanOlij** [comment]
Owh! this might explain why I've been banging my head against the wall for the last two weeks, I'm guessing this applies to the camera permissions as well.

**Comment by MadEqua** [comment]
> Owh! this might explain why I've been banging my head against the wall for the last two weeks, I'm guessing this applies to the camera permissions as well.

Yep, it applies  to all [permissions considered dangerous](https://developer.android.com/guide/topics/permissions/overview#dangerous_permissions).

**Comment by FeralBytes** [comment]
@MadEqua I just wanted to point out that I didn't add the additional functionality because I just needed it to have the lowest level framework for notification of permission requests, so that my Java plugin could expand upon the notification to request the permissions that I needed. Glad to see it is getting even more improvements.

**Comment by marcelofg55** [comment]
@akien-mga Can you test #26756? It should be working now, thanks!
