### ISSUE TITLE
WebSocketClient failed to connect to any server other than localhost on Windows

### ISSUE THREAD

**Issue by xtpor** [godotengine/godot#26517]
**Godot version:**
Godot 3.1 beta 10 official build
Godot 3.1 beta 9 official build
Godot 3.1 beta 8 official build
Godot 3.1 beta 7 official build

**OS/device including version:**
Windows 10 Pro 64 Bit

**Issue description:**
I ran the websocket demo found on https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo. The websocket server and client provided by the demo ran just fine. But if I replace the hostname in the url from `localhost` to `127.0.0.1`; or connect to my local server; or `ws://echo.websocket.org/` the demo would no longer work.

I have tested the same project on old versions of beta build and found out that this issue only occurs on godot 3.1 beta 7 and onwards. I think this might be related to the #26189 because I noticed that ipv6 is enabled after beta 7.

**Steps to reproduce:**
1. Download and run the websocket demo from https://github.com/LudiDorici/godot-websocket/tree/master/websocket_chat_demo
2. Type the url `ws://echo.websocket.org/` onto the textbox on the top right hand corner
3. Uncheck `Multiplayer API`
3. Press connect
4. The client would not connect and just hangs

**Comment by starryalley** [comment]
By reverting the change in #26189 I can get websocket to work again on latest master branch. I didn't try the websocket demo though.

**Comment by Faless** [comment]
I am in the awful position of being unable to test IPv6 due to my stupid ISP which not only do not provide IPv6 access, but also exploiting NATing in IPv4 because they are run out of IP address (so I can't even use a tunnel to try it out).
@starryalley would you be so kind to try out this branch:
https://github.com/Faless/godot/tree/net/lws_v6_resolv
(basically commit: https://github.com/Faless/godot/commit/8b6067370cd6b433141603e9cdf090a753fd4abf ) and let me know if that works?
Would you also be able to test if you experience this issue on your IPv6 network #18275? And since you are there maybe this too #17746 ?

Sorry for the many requests, and thank you for reporting this issue, I'll do my best to find a solution to my current inability of testing IPv6 on windows.

**Comment by Faless** [comment]
Actually, it seems to fail on IPv4 network too, I should have assumed as much when the OP said that `127.0.0.1` was not working either. I'll dig deeper in the library and see what I can find.

**Comment by starryalley** [comment]
@Faless  I'm happy to help when you have some progress. Our project is actually on IPv4 only and we had a websocket server running in godot. 

Our websocket client is on another app using javascript, and the client can't even connect to godot with the IPv6 support enabled.

**Comment by Faless** [comment]
@starryalley #26688 should fix this issue. Feel free to try it out :)

**Comment by starryalley** [comment]
@Faless yes it's working perfect. :D Thanks.
