### ISSUE TITLE
White line around tiles

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#2653]
Hi!
Why I have white lines around tiles in this example. I solved this problem in BGE by setting to alpha clip, but I did not see any option in godot.
Here is example file:

http://www.mediafire.com/download/bfoh77ov997472l/white_lines_around_tiles.tar.gz

**Comment by reduz** [comment]
read the importing textures/tilemap tutorial on github

**Comment by alabd14313** [comment]
I used tiled importer plugin.

**Comment by romulox-x** [comment]
https://github.com/okamstudio/godot/wiki/import_textures#blending-artifacts
https://github.com/okamstudio/godot/wiki/tutorial_tilemap#offset-and-scaling-artifacts

Those are the key parts in the texture and timemap tutorials that might help you understand what's happening here.  It's not a bug.  It's just how texture sampling works.  With filtering enabled, it's blending in the color of the neighbor pixels along the edge of the tile.  I typically solve this by arranging my tiles so that there's some extra color along that edge that's ok to mix in, either through careful selection of neighbor tiles, or by extending the tile's color out a bit into the neighboring (unused) pixels.

**Comment by vnen** [comment]
This can be solved by disabling filtering and mipmaps on the project settings. Further questions should be asked in [Godot's forum](http://www.godotengine.org/projects/godot-engine/boards).

**Comment by ricpelo** [comment]
Solved for 2D Platformer Demo in #2522.
