### ISSUE TITLE
Automatically arrange windows to test game side by side - UI Feature Proposal

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#26546]
**Godot version:**
Godot 3.0.6

**Issue description:**
Since the game is run in a separate window, when I'm testing a game I manually set up the window sizes so the game is side by side with the editor and I'm able to quickly test and make changes with "Sync Scene Changes" and "Sync Script Changes".

**Feature Proposal:**
How about a feature for automatically arranging the windows side by side. You just set the width of the editor and the height / aspect ratio for the game (in case you are testing for mobile with a vertical aspect ratio)

**Here's an example of the feature:**
![screen shot 2019-03-03 at 13 40 19](https://user-images.githubusercontent.com/2546522/53700885-ad2c0500-3dbc-11e9-87e4-97f23094973b.png)

**Comment by girng** [comment]
possible dupe / related to #2326

**Comment by hubbyist** [comment]
A starting arrangement selection for game window may be added to project settings may be. Like "center", "avoid overlap", etc ...

**Comment by aaronfranke** [comment]
This feature likely depends on #576 being solved first so that it be done for all platforms at once.

**Comment by Calinou** [comment]
@aaronfranke Couldn't this be done already by comparing the screen resolution to the editor window size and position?

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
