### ISSUE TITLE
Dragged resource file over scene should appear at it's drop position, not be centered at cursor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#26549]
**Godot version:**
3.1 beta10

**Issue description:**
Dragging a scene/texture into scene view always shows it at cursor's position. When you drop said resource, it will then align properly to grid or whatever.

E.g. this:
![image](https://user-images.githubusercontent.com/2223172/53701805-fc942480-3e00-11e9-8f4d-d826d72d7a4f.png)
After dropping you get this (snapping to grid enabled):
![image](https://user-images.githubusercontent.com/2223172/53701807-03229c00-3e01-11e9-9461-5605cb4e135c.png)
which is not exactly where you dropped. It's even worse with placing scenes, because if you happen to have a scene with non-centered root, it will be shifted from the cursor by the root offset:
![image](https://user-images.githubusercontent.com/2223172/53701837-3bc27580-3e01-11e9-93ff-4b72c3b7fd42.png)

IMO whatever appears when you drag a resource over scene, should appear at it's drop position, not some weird cursor offset. Which means that e.g. texture file dragged into scene should snap to grid from start, not after placing it and moving again.

**Comment by akien-mga** [comment]
Snapping to grid can be implemented, but the second part of your issue is a bad idea (and not possible). If your scene's origin is not in the middle of a given sprite, we shouldn't hack it. You probably did this on purpose, you typically have several sprites, etc. If you're dragging a scene, you place its origin, that's normal. Fix the scene's origin if you don't want that.

**Comment by KoBeWi** [comment]
But the problem with changed origin is this: https://gfycat.com/ChillyFreshIndigowingedparrot

**Comment by akien-mga** [comment]
Oh ok, that's buggy then indeed.
