### ISSUE TITLE
Convert scene to script

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#26552]
Godot version: 3.1 beta 8
Windows 7 home 64 bit

I did make a simulare issue here https://github.com/godotengine/godot/issues/25867 but it immediately got closed for no reason.

this suggestion is not the same necessarily. 
this would just be a editor feature where scenes can be converted to scripts using add_child() and setting properties.

this would go along well with the class_name feature where you build your scene and then convert it to a script and then attach it to a root node.

This would only generate code from the children not the root.

this might be able to be improved later to auto generate code getting rid of the line between scenes and scripts
but for now it would just be a conversion option in Scene>Convert To..>Script.

**Comment by girng** [comment]
could have sworn i've seen a feature proposal of something like this before, can't find it though. IIRC, it was closed because it should made as a plugin or something

**Comment by Shadowblitz16** [comment]
I don't even know how to make plugins let alone one specific to this purpose, there doesn't seem to be many good tutorials on doing so.

I don't want to make it as a plugin anyways I just want to convert it to a script
it would allow for more oop style programming.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
