### ISSUE TITLE
How to handle ETC/ETC2 export for GLES3 + "Best" fallback mode

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#26569]
**Godot version:**
a1e73dcc

**OS/device including version:**
Mobile/web platforms.

**Issue description:**
In #26523 I refactored the system for registering ETC and ETC2 feature tags based on the selected rendering backend for mobile/web platforms, after discussing the best solution with @reduz.

One potential issue is that it might prevent the "Best" fallback mode to work when using GLES3.

For reference, the "Best" fallback mode will test if the selected rendering backend is supported on the current system, and if not, fall back to the next best one (currently, this means that if you make a GLES3 game and use the "Best" fallback mode, it will fall back to GLES2 on drivers that don't support GLES3). It's a bit iffy as a GLES3 game does not necessarily run on GLES2 (e.g. if it uses GPU particles or GIProbe), but it *can* work.

With the changes in #26523, it would mean that such a game would only export ETC2, and thus fail when falling back on ETC. I have yet to actually check if the feature tags govern export to confirm.

**Comment by hpvb** [comment]
Can GLES3 use ETC? Maybe that should be the default for a project that's set to 'best'?

**Comment by reduz** [comment]
This is non-issue, and the reason is that GLES2 is NOT designed to be a fallback for GLES3, specially for 3D. 

ETC and ETC2 are compressed texture formats and are used pretty much only in 3D rendering. GLES2 and GLES3 look different in 3D even for the most basic things (a cube and a light), due to different algorithms in GLES2 intended on performance over quality.

Many things also don't work in GLES2 and have to be done different (like CPUParticles).. so in the end this is not really a problem to begin with.
