### ISSUE TITLE
app crashes when adb is not connected

### ISSUE THREAD

**Issue by psoslash** [godotengine/godot#26600]
Godot version:
3.1 beta 10

OS/device including version:
X96 (S905x) tv box (android 6.0.1)
Mali 450 MP gpu

followed from #26424 but not related

beta 10 solved the compatibility issue but for some reason it only works when adb is connected
since it does works when i connect adb i can't provide a logcat

**Comment by akien-mga** [comment]
>  since it does works when i connect adb i can't provide a logcat

`adb logcat` gives you the system's log since the device last booted, so you should be able to make it crash without adb connected, then connect adb and use `adb logcat` to retrieve logs include that of said crash.

**Comment by akien-mga** [comment]
It's not clear what we can do for this issue, but I haven't seen other similar reports so it must have been quite specific.

I'll close for now. If you can still reproduce this issue in latest 3.2 builds, you can retrieve logs since the last boot with `adb logcat`, which should include any Godot crash that happened in between.
