### ISSUE TITLE
Incorrect default Tile when using bucket fill

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#26601]
**Godot version:** 3.1 beta 9

**OS/device including version:** Linux (probably any)

**Issue description:** 
When using bucket fill with auto-tile, all tiles bordering with others are being filled with tile represented as an icon and not the one with highest priority.

**Steps to reproduce:**
1. Create an auto-tile with several tiles set up for for fully filled (2x2) tiles
![auto-tile group](https://i.imgur.com/SMvJ3Bo.png)
2. Assign some priority values
3. Assign an icon (not the tile with highest priority)  to auto-tileset
4. Create a close empty area of tiles with another tile-type
5. Try to fill it with tileset created earlier.

![Tile fill example 1](https://i.imgur.com/sWZSPiX.png)
![Tile fill example 2](https://i.imgur.com/XXe2WcQ.png)

**Comment by MarianoGnu** [comment]
Hi, can you share a picture of your bitmask?

**Comment by drtwisted** [comment]
@MarianoGnu hi, yes, there you go. hope it's ok.
![bitmask](https://i.imgur.com/Y9y5ike.png)

**Comment by MarianoGnu** [comment]
your bitmask looks wrong, since you are missing many variations, when the Editor tryes to draw the edges it uses the default tile on the borders, i undestand this texture doesn't matches what you intend, but the bitmask should look something like this (and work for an upper-level ground)

![image](https://user-images.githubusercontent.com/1776044/54497339-2dcc2480-48d8-11e9-8b41-8e84866e709f.png)

**Comment by MarianoGnu** [comment]
Autotiles doesn't work wrong, they just dont matches your usecase, i can help you do what you intend to do, but meanwhile i'm closing this issue since there's no bug.
