### ISSUE TITLE
C# Rset is broken on extended classes

### ISSUE THREAD

**Issue by Bombfuse** [godotengine/godot#26616]
**Godot version:**
Godot Mono 3.1 Beta 10

**OS/device including version:**
MacOS Mojave

**Issue description:**
A node that extends another networked node should have the full functionality of the base networked node. When the base networked node uses Rset to change its variable, the node that extends that node should also Rset it's variable. However, only the base node will Rset its variable. This prevents users from creating a networked node and extending it with more properties and functionality.

**Steps to reproduce:**
Create a base networked node with a Sync/PuppetSync property. Have the node alter it's property via Rset.

Create a node that extends the previous node.

Run both nodes in a networked environment (Just creating a local server will be fine) and set their network master to 1 (server).

**Minimal reproduction project:**
[networked_node_ext_repro 2.zip](https://github.com/godotengine/godot/files/2928836/networked_node_ext_repro.2.zip)

Press "ui_accept" when running the scene, it will print out the Rset variable and Rpc call and whether or not it succeeded.

EDIT: Fixed reproduction project

**Comment by Faless** [comment]
Thanks for reporting this issue.
It seems to be related to Mono as you mention, since I can't reproduce with GDScript. [NetTest.zip](https://github.com/godotengine/godot/files/2930411/NetTest.zip)
Maybe something in the way class extension is handled in our glue code? @neikeq 


(Just as reference, I've noticed another issue when calling RPCs on a Node without a script which I'm currently investigating).

**Comment by neikeq** [comment]
This was not only an issue with `rset`, but also `set`. I'm surprised there are no more issues about this (or maybe there are 🤔).
