### ISSUE TITLE
Shared Resources proposal

### ISSUE THREAD

**Issue by lexum0** [godotengine/godot#26617]
**Godot version:**
Godot 3.0.6

**Feature Proposal:**
Share resources between projects. Currently you need to copy the files, so improvements in one project are not reflected on the other project. I think the solution would be to add file references / referenced assets, so you can add a file by reference and have it in a different folder or a shared folder. This way improvements are shared across different projects.

In case you move the file outside of Godot, Godot would simply tell you the file is missing and that you need to update its location. Xcode offers a button to assign its current location when this happens and shows the file with red text in the project navigator.

**Comment by vnen** [comment]
What we usually do is to extract common stuff to a different repository and use Git submodules to add it to the projects. This way we can reuse stuff across projects without needing anything special from Godot itself.  There's also a benefit of version control: changing stuff in the common repo doesn't automatically break in the projects, only when you explicit update.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Zireael07** [comment]
Don't we have a related proposal though? Something about sharing code/folders between projects?
