### ISSUE TITLE
Per-layer culling distances

### ISSUE THREAD

**Issue by OBKF** [godotengine/godot#26693]
**Issue description:**
I was looking for ways to optimize my game and I came across this [feature](https://docs.unity3d.com/ScriptReference/Camera-layerCullDistances.html) in Unity.

Basically, it's allowing to customize Near/Far clipping planes for each Render-Layer.
This is extremely helpful for large scenes where you clip small objects first and leave the landscape, it can also be used to add custom clouds with shader on a sphere and make it render really far without clipping.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
