### ISSUE TITLE
Compile Godot tools for Android

### ISSUE THREAD

**Issue by moocow1452** [godotengine/godot#267]
Can the entire program be compiled into a version for Android, so that game development can be entirely completed on the go?

**Comment by akien-mga** [comment]
Someone mentioned successfully building Godot for ArchlinuxARM on IRC a couple days ago.

**Comment by blurymind** [comment]
please note that while they are the same architecture, compiling it for rasberry pie will not allow it to run on Android

**Comment by blurymind** [comment]
From a correspondence on twitter:

> todor imreorov ‏@blurymind  16h16 hours ago
> @reduzio can godot editor run on #android to develop games on mobile like #love2d  can? Would love to have it on my galaxy tab :D 
> 
> Juan Linietsky ‏@reduzio  14h14 hours ago
> @blurymind would not be difficult to do, but not a priority for the main devs. If anyone wants to contribute this work be welcome.

Basically Godot can compile games to android, but the actual editor doesnt have a port yet.
With the rise of android based tablets, I see more and more people use their tablet with a keyboard for work.
As an owner of an android galaxy note 10.1 and someone who spends 4 hours travelling on the train every work day, I started contemplating using that time to do some coding.

Unfortunately there are not many options at the moment, because most game engines have a huge footprint. The only I found that works well is Love2d, but to develop for it you dont have nice things such as code autocompletion on android.
https://love2d.org/

I think that having the editor also work on mobile devices would be a great way to take advantage of it's small footprint and bring to those platforms something that is currently not very available for them.

@reduz  says it's not difficult to do, and work would be welcome.

here is love2d on the google play store btw
https://play.google.com/store/apps/details?id=org.love2d.android
having Godot at the playstore will give it more exposure, as there is currently no competition - apart of love2d.
There is seriously no other game engine editor on there atm.

**Comment by reduz** [comment]
I don't think it will be awesome, but a waste of time. If anyone wants to
do it, be welcome.

**Comment by punto-** [comment]
What's missing if you compile with tools=yes on android at the moment? it
seems like everything should be there, except maybe some specific editor
thing, like where it saves the global configuration.. There's also a flag
on the rasterizer to make it keep a local copy of the buffers, the editor
needs that. I'm happy to put an apk on the google store if we get a working
build..

**Comment by reduz** [comment]
well, you will obviusly not be able to run the game

**Comment by punto-** [comment]
That's true, to spawn a process that runs your game you'd have to do some
Intent/Activity trickery that is too annoying to even think about :p (maybe
the editor can do OS.url_open("godot://path/to/project"), and we register a
player to open that url scheme in android?) But the app could launch in
"project manager" mode, and just let you run or edit every time you launch..

**Comment by blurymind** [comment]
how do you even compile it on android? The thing doesnt even have a terminal

**Comment by punto-** [comment]
You cross compile from any PC? Maybe running it will be an issue too since
the editor with package it like a game, but you actually want an empty
assets directory on the apk, so it launches the project manager?

**Comment by LinuxUserGD** [comment]
This is a very old issue. You can already run Godot on your smartphone with https://godot.online in Chrome, so it's better to change the title to something like "Optimize Godot for mobile" (e
 g. touch and virtual keyboard)

**Comment by alanjds** [comment]
@LinuxUserGD There is 2 issues w/ this:
- godot.online _right now_ is unusable because is frozen pending some approval on Dropbox
- Even if worked, is not usable on commuting (at least on my commuting) because internet does not work on whole tripline. In fact, it works on some spots of the trip only

**Comment by DuskKittyIsHotAF** [comment]
very tolerant and nice commnuity imo. run by great leadership skills, you should be proud juan and akien for leading this great floss project!
![](https://i.gyazo.com/2fd0c035013b3c1bb0652552d35fde92.png)
![](https://i.gyazo.com/e0acd22258872330f342d5d189564f1e.png)
![](https://i.gyazo.com/81b238ce283aa55126e3a2f608583837.png)

**Comment by senteix2** [comment]
@punto- @blurymind , i was wondering if you can use termux (https://github.com/termux) to compile , it allow you to have clang and gcc , it has not X11 though but we can run a ssh server there .. just some ideas . termux is very lightweight

**Comment by LinuxUserGD** [comment]
Termux has support for clang but not for gcc/g++.
Scons isn't in the default package repo, so you have to manually build it via python.
Cross compiling doesn't work as this is intended for creating export templates (tested under X11). It just generates two executables (android_debug.apk and android_release.apk) which are both broken when trying to run them on AndroidX86.

**Comment by david-aranda** [comment]
@LinuxUserGD termux does support gcc/g++ (not officially tough) https://github.com/its-pointless/gcc_termux

**Comment by alanjds** [comment]
@LinuxUserGD: Does not work for Android x86, but does for Android ARM?

**Comment by blurymind** [comment]
@reduz consider this:
https://www.appgamekit.com/news/post/appgamekit-mobile-released
Appgame kit is doing it. You also have this:
https://getchip.com/pages/pocketchip
So is even the Nintendo Switch:
https://www.fuze.co.uk/nintendo-switch.html

Learning to code on a mobile device is trendy

So why not have a stripped down godot on android?
Godot go app- a stripped down godot code editor + runtime - to code on the go. It will get more people onboard- once they get serious about their godot game prototype- move onto the full Godot editor

**Comment by vnen** [comment]
@blurymind porting the whole editor to Android is probably *easier*. Making a special version of the editor just for Android will require much more work, since it needs to be made from the ground up.

The challenge for that, AIUI are: 1) Compile all the libs required by the editor to the Android architecture, and 2) figure out a way to launch the project as another app from the project source.

**Comment by LinuxUserGD** [comment]
Currently get some error when I try to compile source for android: 
scons p=android tools=yes
scons: Reading SConscript files ...
Building for Android (armv7) (with NEON)
Using NDK unified headers
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> editor/editor_node.cpp
editor/editor_node.cpp:5702:27: error: unknown type name 'NavigationMeshEditorPlugin'; did you mean 'NavigationPolygonEditorPlugin'?
        add_editor_plugin(memnew(NavigationMeshEditorPlugin(this)));
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~ 
                                 NavigationPolygonEditorPlugin
core/os/memory.h:97:51: note: expanded from macro 'memnew'
#define memnew(m_class) _post_initialize(new ("") m_class)
                                                  ^
./editor/plugins/navigation_polygon_editor_plugin.h:67:7: note: 'NavigationPolygonEditorPlugin' declared here
class NavigationPolygonEditorPlugin : public AbstractPolygon2DEditorPlugin {
      ^
1 error generated.
scons: *** [editor/editor_node.android.tools.armv7.neon.o] Error 1
scons: building terminated because of errors.

**Comment by unfa** [comment]
godot.online is no longer online. Is there anything similar available right now?

**Comment by aaronfranke** [comment]
Control scheme is not a problem if all we want to target is large Android devices with keyboards. There's also Android-x86 which is Android compiled for x86 desktop computers.

**Comment by tedbrandston** [comment]
Since no one has pointed this out yet, for [vnen's #2](https://github.com/godotengine/godot/issues/267#issuecomment-370960394) I've used [APDE](https://github.com/Calsign/APDE) which lets you compile and run entirely on Android. 

I'm not familiar enough with the under-the-hood of either project, but it seems like it's probably not impossible.

**Comment by HugeGameArtGD** [comment]
I think it should be possible if you use a standard game, compile to the .apk with tools=yes, open it and remove this what would be the .pck. If you set the permission to read/write, maybe you can open a project then. The only problem is running it inside the editor, for that another .apk would be needed with an open with dialogue from the project manager .apk.

**Comment by LinuxUserGD** [comment]
I think it should be possible if you use a standard game, compile to the .apk with tools=yes, open it and remove this what would be the .pck. If you set the permission to read/write, maybe you can open a project then. The only problem is running it inside the editor, for that another .apk would be needed with an open with dialogue from the project manager .apk.

**Comment by LinuxUserGD** [comment]
Now that the new goal for Godot 3.2 is getting the Godot editor to run on a web browser, is there any chance that this will also happen for Android?

**Comment by blurymind** [comment]
Getting it to run is the first step. From there on it's a matter of improving the user experience on a mobile device with touch input

**Comment by Zireael07** [comment]
>  new goal for Godot 3.2 is getting the Godot editor to run on a web browser

What? Where did they say so?

**Comment by LinuxUserGD** [comment]
> What? Where did they say so?
Getting the Godot editor to run on a web browser (ideal for public teaching institutions).
https://godotengine.org/article/godot-3-1-released

**Comment by Chaosus** [comment]
Meh, this issue looks like a big joke, even if the Godot editor is successfully runned into Android, its hard to imagine the amount of work to make right configuration, project settings , debug, export, etc. to make it somehow useful to create complete games (for script demo like https://gdscript-online.github.io/ of course this can be possible but for whole editor...)

**Comment by Deus0** [comment]
Hey, im also looking to run it on my android device. I've got bluetooth keyboard and mouse and a usbc docking bay. So it'd be super convenient to be able to do this on the train and then do it at home on the same device.

**Comment by fahrstuhl** [comment]
Not sure if this is the place to post about this, but I got the Godot editor 3.2 beta2 to start on Android, but couldn't open a project.
**Warning, the following video flickers heavily:** https://gfycat.com/illegalbronzekoala

I basically followed the [compiling for android docs](https://docs.godotengine.org/en/3.1/development/compiling/compiling_for_android.html).
I first set the Android environment with `export ANDROID_HOME=<path to android sdk> ANDROID_NDK_ROOT=<path to android ndk>`, built the editor with `scons p=android tools=yes`, `cd platform/android/java` and created an apk with `./gradlew generateGodotTemplates`.

It didn't install right away, I had to [sign it manually from the command line](https://developer.android.com/studio/build/building-cmdline#sign_cmdline).

Obvious problems are the flickering and its inability to access the filesystem. The apk doesn't ask for any permissions, so that's expected.

**Comment by lawnjelly** [comment]
> Obvious problems are the flickering and its inability to access the filesystem. The apk doesn't ask for any permissions, so that's expected.

The flickering might be due to double / triple buffering and the buffer being swapped on every frame on the android build, and the editor trying to swap buffers on demand (only when the screen changes). It's probably easy to fix.

**Comment by unfa** [comment]
This is exciting!

**Comment by fahrstuhl** [comment]
I (very hackily) got the permissions problem solved: I edited `platform/android/java/lib/src/org/godotengine/godot/Godot.java` and added a `requestPermissions();` into `onCreate()`.
Then I edited `platform/android/java/app/AndroidManifest.xml` and added `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`.

Now it can read and create project directories, but it crashes when trying to edit a project, sadly without any output in the Android log. On Linux, the Godot editor spawns a new window when selecting a project to edit from the project overview. I could imagine this transition being the problem, but I don't know enough Android nor Godot.

**Comment by aaronfranke** [comment]
@fahrstuhl Perhaps, for testing if the editor itself works, you can make Godot open a project directly? The command-line syntax is `/path/to/godot --path /path/to/project --editor`. You can also exclude `--editor` to have it run the game instead of the editor (requires `.import/` to be present).

**Comment by fahrstuhl** [comment]
Okay, I [forked godot and made a branch](https://github.com/fahrstuhl/godot/tree/android_editor) for this.

I managed to fix the flickering, the project manager runs in `low_processor_mode` by default and [this is buggy on Android](https://github.com/godotengine/godot/issues/30417).

I did not manage to pass any command line options to the app on Android.
I think if the editor wouldn't fork from the project manager but just replace the scene tree root, everything should work.
This seems to be exactly what happens when the splash screen switches to the project manager, but I did not manage to transfer this to the switch to the editor, yet.

**Comment by fahrstuhl** [comment]
[I managed to get the editor to run in a _really_ hacky and broken way](https://www.youtube.com/watch?v=TlfEdYqiLqE).

Instead of having the project manager spawn a new process with the editor, [it just switches scenes to the editor node](https://github.com/fahrstuhl/godot/blob/a449e5f363ebf29a618c00d77953e43a9ce1d336/editor/project_manager.cpp#L2026). I'm not sure how much of the project manager state is still around after switching scenes, but I think this method could also be used to switch between the game and the editor on Android.

Apart from that, the editor crashes when I try to attach a script to a node, Android touch screens don't have right and middle click, everything takes quite some time to load, and handling files on Android is very broken. So quite a lot of work left to do, but it does run.

**Comment by thebestnom** [comment]
@fahrstuhl can you elaborate on how do you compile and install it?

**Comment by fahrstuhl** [comment]
[As described here](https://github.com/godotengine/godot/issues/267#issuecomment-559521231), I basically followed the [building for android documentation](https://docs.godotengine.org/en/3.2/development/compiling/compiling_for_android.html). After you build with `scons`, you `cd platform/android/java` and create an apk with `./gradlew generateGodotTemplates`. Then you have the apk files for Android in `platform/android/java/app/build/outputs/apk/debug`, but you need to [zipalign and sign them first](https://developer.android.com/studio/build/building-cmdline#sign_cmdline). 
1. zipalign with: `zipalign -v -p 4 android_debug.apk android_debug_aligned.apk`
2. create a debug keystore to sign: `keytool -genkey -v -keystore debug.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias
`
3. sign the apk with: `apksigner sign --ks debug.keystore --out android_debug_signed.apk android_debug_aligned.apk`.

Then you can install the `android_debug_signed.apk`.

**Comment by thebestnom** [comment]
@fahrstuhl after trying it for a bit, I started to work on it, 
A. And the most critical problem I have is I can't manage to debug the cpp code in the editor which makes everything slow
B. It looks like the editor can't an editor settings because base config is not set and I can't manage to set it (tried implementing get exec path on os_android but because I can't debug I can't find what value it should be for it to work)
C. Same for project res directory which it also seems to not be able to create...
D. For some reason when clicking on the directory button on start screen on existing project it sends a file uri to intent open which crash the app, and I don't know how to fix it without breaking the current system (which I never used so I don't know how normal games use it)

**Comment by thebestnom** [comment]
@fahrstuhl Update
5 days ago I finally been able to debug it, so...
I made script and projects files to work to work,
Also made home screen to save settings (which says that editor settings is being saved)
sorry for not forking from you...

let the testing begin!

**Comment by aaronfranke** [comment]
> do you mind if I open WIP pr?

Please do, assuming you're willing to work on it until it's in a functional and mergeable state.

However, pull requests for new features need to be made against the master branch. I noticed that your `android_editor` branch is currently based on top of the 3.2 branch. If you wish to submit a pull request, you will need to make a branch that is based on master first.

**Comment by thebestnom** [comment]
@aaronfranke that's my intention, porting it till it done
Also I tried working on master, but sometime around 2 weeks ago there was a merge that break the build with tools true (I think, didn't try without it) on android, I would need to investigate it

**Comment by LinuxUserGD** [comment]
@thebestnom
Is android even working with vulkan on master branch? I don't think that GLES2 is ported back yet to use new RenderDevice code so currently it should either fail to compile or to start with or without tools (?)

**Comment by thebestnom** [comment]
@LinuxUserGD to me it failed to compile with tools, so I guess that answers your question?

**Comment by thebestnom** [comment]
Also, is there any chat that godot community use so we don't spam the issue?

**Comment by LinuxUserGD** [comment]
@thebestnom Discord (Godot or Extended Libraries) e. g.

**Comment by fahrstuhl** [comment]
Great to read you're making progress @thebestnom !

I got the impression most of the engine dev talk happens on the [IRC channel](http://webchat.freenode.net/?channels=#godotengine), which also has a [matrix bridge](https://matrix.to/#/#godotengine:matrix.org).

[I asked on the IRC channel about how to best adapt the editor to Android](http://godot.eska.me/irc-logs/devel/2020-01-23.log) (between 13:00 and 16:30) and running each the project manager, the editor and the game as different activities sounded like the best way.

Also [the Android port _might_ change](http://godot.eska.me/irc-logs/devel/2020-02-13.log) to convert nearly all Java code to C++ by making it a [NativeActivity](https://developer.android.com/reference/android/app/NativeActivity):
> [18:16:23] \<Calinou\> we'll look into rewriting the Android port to use NativeActivity
[18:16:33] \<Calinou\> (which means it will have very little Java code and will be mostly C++)

So maybe we should ask about that, too.

**Comment by aaronfranke** [comment]
@thebestnom I personally use [Discord](https://discord.gg/rA54pU7) the most. IRC is best for contacting the lead devs since they hang around there, but Discord is better for casual chatting since it has many channels and preserves history (on IRC you can only see messages posted after you join).

**Comment by thebestnom** [comment]
so where can we open an open channel for android porting?

**Comment by LinuxUserGD** [comment]
https://discord.gg/PDmtUVW

**Comment by thebestnom** [comment]
https://github.com/godotengine/godot/pull/36776 opened a WIP PR opened, let's see how much time it will take me to get it to be fully ported!

**Comment by LinuxUserGD** [comment]
Seems like this is back:
https://twitter.com/godot_online/status/1252688213702930434
Maybe they have some patches that could be used on android native too, not sure.

**Comment by thebestnom** [comment]
@LinuxUserGD the PR is mostly working (3d is broken because android on master is broken) but having the abilty to works with local files is great, and I have git on my termux so I can actually work with it

**Comment by mhilbrunner** [comment]
I'll close this issue, as it's 6 years old now and the initial question was `Can the entire program be compiled into a version for Android?` - the answer is yes, with some caveats, it seems. :)

Great work on figuring out the Android build, and please keep working on it - and if you encounter any specific issues with Godot on Android, open issues or PRs for them!

In the meantime, I'll keep an eye on the open PR - having the editor work on Android out of the box would cool.

Thanks to everyone for the great discussion!

**Comment by nobody5050** [comment]
looks good!

**Comment by 2439905184** [comment]
> 可以将整个程序编译成适用于Android的版本，以便在旅途中完全完成游戏开发吗？

I have tried to compile godot for arm linux. And it can run on android with aidlearing and vncviewer (aidlearing is a app based on termux ,it has full x11 graphics functions) 
https://github.com/2439905184/godot-arm
You can see the release here. I compile it just on android with termux app.

**Comment by 2439905184** [comment]
> Can the entire program be compiled into a version for Android, so that game development can be entirely completed on the go?

网盘下载:https://wwa.lanzous.com/b015or6ti
密码:6kix 
download godot for arm linux here .

**Comment by LinuxUserGD** [comment]
@2439905184 There's native Android support https://github.com/godotengine/godot/pull/36776 (rebased for godot master).

**Comment by idchlife** [comment]
If you guys need testers - my second main machine is Samsung Galaxy Tab S8 with keyboard and touchpad. I'm using it now for over 3 months without touching my main machine, mainly for developing.
I can test anything you want in normal mode, dex mode, with keyboard/touch/mouse mode etc.

**Comment by m4gr3d** [comment]
> If you guys need testers - my second main machine is Samsung Galaxy Tab S8 Ultra with keyboard and touchpad. I'm using it now for over 3 months without touching my main machine, mainly for developing. I can test anything you want in normal mode, dex mode, with keyboard/touch/mouse mode etc.
> 
> Right now Godot Editor is not usable because in 3D viewport it's nearly impossible to move anything, but code editor and most other features look good. Tested for 5 minutes, though, because of lack of usability of viewport.

@idchlife The current version of the Godot Android Editor should work with keyboard and mouse including with the 3D viewport.
Touch support for the viewport however is still being worked on.
Is that the experience you're getting on your tablet?

Also feel free to respond on the https://github.com/godotengine/godot-proposals/issues/3931 proposal instead of this (closed) thread.
