### ISSUE TITLE
GLES2 Depth Texture interfering with z order

### ISSUE THREAD

**Issue by faculezcano** [godotengine/godot#26703]
**Godot version:**
3.1 beta 11

**OS/device including version:**
Arch Linux / Intel Graphics

**Issue description:**
Seems like using DEPTH_TEXTURE is interfering with z order. in GLES2 backend

![gles2_depth_bug](https://user-images.githubusercontent.com/5156989/53878448-aa165c00-3fea-11e9-8a84-5f15277d7d30.jpg)

**Steps to reproduce:**
1. Create a plane with a cube behind
2. Create a ShaderMaterial for plane
3. Output depth texture to Albedo.

**Minimal reproduction project:**
[depth_texture_test.zip](https://github.com/godotengine/godot/files/2936011/depth_texture_test.zip)

**Comment by akien-mga** [comment]
Why close?

**Comment by faculezcano** [comment]
> Why close?

Sorry I figured that depth texture is reaching the shader, but still there is a problem with the z order or something because part of the cube(above the plane) isn't rendering at all.

**Comment by OBKF** [comment]
This is caused only when used in custom shaders, Depth works fine with standard spatial shader (used in Proximity Fade).

Proximity Fade disabled
![normal2](https://user-images.githubusercontent.com/12987951/53881689-9384fa80-4014-11e9-8fd1-775a7b505850.png)

Proximity Fade enabled
![normal](https://user-images.githubusercontent.com/12987951/53881935-36d60f80-4015-11e9-8848-c2d9f85a6aad.png)

**Comment by OBKF** [comment]
@akien-mga @faculezcano  I was looking at [material.cpp](https://github.com/godotengine/godot/blob/74719b8748d338c143a62b3659693af0d82b784c/scene/resources/material.cpp#L846) and I found a solution ( or I would say the bug). and this is the work around:
```
shader_type spatial;

uniform float proximity_fade_distance = 5.0;

void fragment () {
	ALBEDO = vec3(0, 1, 0);
//	float depth_tex = textureLod(DEPTH_TEXTURE,SCREEN_UV,0.0).r;
	float depth_tex = texture(DEPTH_TEXTURE, SCREEN_UV).r;
	vec4 world_pos = INV_PROJECTION_MATRIX * vec4(SCREEN_UV*2.0-1.0,depth_tex*2.0-1.0,1.0);
	world_pos.xyz/=world_pos.w;

	// This is the magical part, I have used a value of 0.001 so it's a tiny clipping margin.
	float depth_clip = clamp(1.0-smoothstep(world_pos.z+0.001,world_pos.z,VERTEX.z),0.0,1.0);
	ALPHA *= depth_clip;

	// Do what ever you want with your depth (like proximity fade in this case)
	float depth = clamp(1.0-smoothstep(world_pos.z+proximity_fade_distance,world_pos.z,VERTEX.z),0.0,1.0);
	ALBEDO = vec3(depth);
}
```
I hope this help fixing it.
![image](https://user-images.githubusercontent.com/12987951/55672687-b1ed4880-5895-11e9-8cb2-1fd28de75a24.png)

**Comment by clayjohn** [comment]
Currently when reading from ``DEPTH_TEXTURE`` depth testing is disabled. This is because, for GLES2 compliant hardware, it is not possible to do both and will result in undefined behaviour at best, and crash the graphics drivers at worst. 

So unfortunately, in order to preserve compatibility with older hardware this cannot be implemented. @OBKF's workaround is your best option for fixing this problem.

**Comment by sadat-s-ahmed** [comment]
@OBKF did you run into any problem where the direction of the camera re creates this clipping issue? I seem to be running into this issue everytime the camera lookat is at the -z . Can you help me with this issue? It only occurs when multiple depth texture reading shaders overlap.
This is the ideal shading.
![ideal](https://user-images.githubusercontent.com/47793077/65920252-593fd800-e400-11e9-9fc0-36a2022cb36d.png)

This is the issue. Can anyone help with this issue?
![issue](https://user-images.githubusercontent.com/47793077/65920258-5cd35f00-e400-11e9-87d2-eaadd8086ec4.png)

I think it might be due to the camera matrix changing the projection depth but I'm not sure about it. a little code snippet on getting the world space depth independent of the camera transform might help. I can't seem to find any reference on that topic in godot.
