### ISSUE TITLE
Abnormal texture on Android

### ISSUE THREAD

**Issue by 316902108** [godotengine/godot#26733]
Export Android. After changing scenes on the mobile phone, the texture loading is abnormal and the screen appears.
![abnormal 1](https://user-images.githubusercontent.com/48303560/53927723-b241ca80-40c2-11e9-98b2-40727a9be09c.jpg)
![abnormal 1](https://user-images.githubusercontent.com/48303560/53927726-b372f780-40c2-11e9-9143-69a012dd1a2e.png)
![abnormal 2](https://user-images.githubusercontent.com/48303560/53927728-b4a42480-40c2-11e9-9702-75bb0bd26ba2.png)

On PC:
![normal value](https://user-images.githubusercontent.com/48303560/53927729-b53cbb00-40c2-11e9-9f68-9e394ee2883e.jpg)

**Comment by akien-mga** [comment]
Godot version? Android device and OS version?

**Comment by 316902108** [comment]
> 戈多版？Android设备和操作系统版本？

Godot3.0 and 3.1 Have tried
Android 9 (API 28)
Android SDK Build-tools 28
JDK and JRE 1.8.0_131
Several Android devices and operating systems have tried

Thank you for your help and reply.

**Comment by akien-mga** [comment]
Godot 3.1 is not released yet, so what exact development version did you try?

Are you using GLES2 or GLES3?

**Comment by akien-mga** [comment]
Can you share a project that reproduces the issue?

**Comment by 316902108** [comment]
Godot 3.1 Beta1--10
GLES2  Flash screen, more serious problem
GLES3  Texture anomaly

I'll share the project with you later. Thank you for your help.

**Comment by 316902108** [comment]
[APK.zip](https://github.com/godotengine/godot/files/2940851/APK.zip)
[XY.zip](https://github.com/godotengine/godot/files/2940852/XY.zip)

This is my project, and the released APK

**Thank you for your help. This problem has troubled me for a long time.

I hope it can be solved.**

**Comment by akien-mga** [comment]
Thanks!

I tried it on my Xiaomi Pocophone F1 with Android 9, and I can reproduce the bug.

- GLES3: Same issue as in the first post, textures are messed up
![screenshot_2019-03-07-13-38-28-898_net gamemk](https://user-images.githubusercontent.com/4701338/53957367-73217280-40de-11e9-8aa9-4a620bc3d011.png)

- GLES2 (after enabling `rendering/vram_compression/import_etc`, otherwise it doesn't include the proper textures for GLES2): It works, though there are some transparency issues:
![screenshot_2019-03-07-13-33-52-450_net gamemk](https://user-images.githubusercontent.com/4701338/53957278-3bb2c600-40de-11e9-82d1-6cb8309f59fe.png)

With some changes to the project you might be able to make GLES2 work as expected, which should also give you better compatibility with older phones which do not support GLES3. But the GLES3 bug needs to be investigated and fixed nevertheless.

**Comment by 316902108** [comment]
Thank you for your reply!

This BUG has been tried on many Android phones, and there are similar mistakes.

**We are Chinese GODOT enthusiasts !
Thank you for your efforts.**

**Comment by akien-mga** [comment]
The issue on GLES3 seems to be with using textures with sizes which are not powers of 2.
For example `Material/UI/UI_Picture/UI_Creat.png` is 1118x663 px, if I resize it to 1024x512 px (both powers of 2), it works fine (of course it breaks the UI scale).

GLES3 is supposed to handle textures with non power of 2 automatically, so it's weird that this bug happens.

**Comment by 316902108** [comment]
I tried your advice (both powers of 2), and BUG still exists.

Although the problem has not been solved thoroughly, thank you very much for your reply and patience.

**Comment by akien-mga** [comment]
Here's how it looks like for me after resizing `Material/UI/UI_Picture/UI_Creat.png` to 1024x512 px:
![screenshot_2019-03-07-14-25-33-888_net gamemk](https://user-images.githubusercontent.com/4701338/53959817-f80f8a80-40e4-11e9-92d5-8b92f7d0d28f.png)
I did it with GIMP which also converted the color profile that it considered non-standard, so that might be another factor.

**Comment by 316902108** [comment]
"Role_Sprite"This is Sprite Animation, How to deal with the texture errors in this animation? 
This animation is normal in other scenes.

**Comment by akien-mga** [comment]
The problem is due to importing textures as Video RAM compressed. If I change the import setting for all PNG files to the "2D" preset (Lossless), then everything works fine.

The issue comes from the `importer_defaults` category defined in your `project.godot` file:
```
[importer_defaults]

texture={
"compress/bptc_ldr": 0,
"compress/hdr_mode": 0,
"compress/lossy_quality": 0.7,
"compress/mode": 2,
"compress/normal_map": 0,
"detect_3d": false,
"flags/anisotropic": false,
"flags/filter": true,
"flags/mipmaps": true,
"flags/repeat": 1,
"flags/srgb": 2,
"process/HDR_as_SRGB": false,
"process/fix_alpha_border": false,
"process/invert_color": false,
"process/premult_alpha": false,
"size_limit": 0,
"stream": false,
"svg/scale": 1.0
}
```

If you remove that and delete the `.import/` folder, all textures will properly be imported as 2D textures, in lossless.

VRAM compression makes sense for 3D games, but not so much for 2D.

If you do want to use VRAM compression nevertheless, you'll have to disable mipmaps (which are the ones causing this bug), or resize all textures to powers of 2.

**Comment by akien-mga** [comment]
BTW, after setting all textures to "Lossless" compression (Texture > 2D preset), it always work flawlessly on GLES2.

**Comment by reduz** [comment]
It seems the problem is that, despite the specification saying OpenGL ES 3.0 supports fully non power of 2 textures including mipmaps, this is not true for ETC and ETC2. This is confusing and was not mentioned in the specification.

@316902108 You will need to re-import your textures (delete .import folder) after using a build with this fix.

**Comment by 316902108** [comment]
I will configure the file"project.godot"
/[importer_defaults]
/"compress/mode"
Set to "0"
Perfect solution to all problems.

**Thank you very much,
I'm sorry to have caused you trouble.**

**Comment by akien-mga** [comment]
>  I'm sorry to have caused you trouble.

You did not cause any trouble, you helped us fix a bug in the engine :)

I hope you'll translate your game in English eventually, it looks very nice!
