### ISSUE TITLE
Usability improvement: please tell me when I need to reimport an asset because I modified it

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#26764]
**Godot version:** 3.0.6 / 3.1 beta 9

**Issue description:**
Godot has a couple of places where you import an asset, make changes to its properties in-editor, and need to re-import them before those changes take effect. For example:

- Add an .OGG file to your project, edit it to turn off looping
- Add a .PNG of some pixel art, turn off filtering so you can zoom in without borders (#26734)

In both cases, the user needs to hit `Import` to reimport the asset before those changes take place. I'm sure I'm not the only one who lost a few hours figuring this out. This is easy to forget (at best) or confusing (at worst - for new users who haven't learned this).

I see a couple of ways we can improve this.

1) Show a little notification icon or popup or something telling the user to re-import. Lower-effort.
2) Auto reimport when the user saves/builds their project. Higher effort.

Please make some sort of improvement in this area.

**Comment by bojidar-bg** [comment]
3.1 should reimport changed assets automatically. The only need to hit the import button is when changing import options.

**Comment by Zylann** [comment]
@bojidar-bg I think that's actually the point of that issue :)

About option 2), a problem I see happening is for textures. They can typically take a long time to import, and it would be cumbersome to have to wait for an auto-reimport each time a property is changed in the dock. So if auto-reimport is considered, maybe it should run when the dock is unfocused, something else gets edited or before the game gets started.

**Comment by capnm** [comment]
> 3.1 should reimport changed assets automatically.

Theoretically yes, but the cache system seems to be broken almost everywhere. Textures, images, materials, external models, grid map libraries, etc. If you're lucky, the update will happen after you reopen a scene or you may need to restart the Godot editor. This is my personal experience in today's attempt to port (git tip) some examples from other engine …

Could someone please prove that the issue #25243 is still broken? It has been closed several times, it may be that I am doing something wrong. Thanks!

**Comment by nightblade9** [comment]
I've never seen reimport broken. Every single time I've updated in image in GIMP and saved it, the Godot editor reimports it. My complaint is - well, I didn't look hard enough and notice the warnings; that turning off Filter wouldn't actually be applied. 

It would be great if Godot's editor could auto re-import anything where you changed settings, perhaps on your next build/run of the app.

![image](https://user-images.githubusercontent.com/31222662/54005092-10ec6000-4126-11e9-9cab-d4d5e233ec94.png)

**Comment by Zylann** [comment]
I also thought it would be more intuitive and less clicks around to have import settings inserted at the top of the regular properties in the inspector, in their own category, instead of having to remember that they are in a separate dock in which re-import is manual, but that could be another issue.

Another thought, if import settings were a popup instead of a dock, that would solve the problem of auto-reimport easily, when it closes.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
