### ISSUE TITLE
Pixel snapping of GUI controls is flawed when its containing control is scaled

### ISSUE THREAD

**Issue by mthreis** [godotengine/godot#26774]
**Godot version:** Godot 3.1 Beta 11

**OS/device including version:** Windows 10

**Issue description:** When moving GUI controls around, the editor takes into account the "global" pixel size/scale (1, 1) instead of the GUI size, which makes it a chore to deal with scaled GUI (for pixel art games, for example). It used to snap to 1 regardless of the control scale, which was ideal but it does not work like that any more.

**Steps to reproduce:** Moving a node in a containing control (hud) whose scale is (1, 1) works as expected:

![e1](https://user-images.githubusercontent.com/31781227/53993682-dc20de80-410e-11e9-9702-5c33b0b179e1.gif)

Now, when you change "hud" scale to (2, 2) -- which is the case for most pixel art games -- instead of snapping to 1, it snaps to 0.5, making it harder to position the nodes correctly.

![e2](https://user-images.githubusercontent.com/31781227/53993792-1ee2b680-410f-11e9-9cf6-593bc8cd671c.gif)

It used to work but it's been changed recently.

**Comment by groud** [comment]
I think that is expected, else people would complain they cannot position their Control nodes pixel by pixel. Pixel snapping is meant to align your control to the pixel grid globally, not to use round units as position.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release? Seems to me like Controls don't snap at all in the inspector now.

**Comment by Calinou** [comment]
I can reproduce this on 4.0.2. However, as described above, this may not be a bug, as the current behavior is likely desired for non-pixel art games.

That said, for UI scaling, you should use the approach described in [Multiple resolutions](https://docs.godotengine.org/en/stable/tutorials/rendering/multiple_resolutions.html) instead of scaling Control nodes. https://github.com/godotengine/godot/pull/75784 will provide built-in support for integer scaling, but in the meantime, you can use the `disabled` stretch mode and set a custom scale factor based on how large the window size is (relative to the base window size).
