### ISSUE TITLE
Provide easy way to select vertices to pin when editing softbody mesh

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#26786]
**Godot version:**
`master` / 8b231b96

**OS/device including version:**
Manjaro Linux 18.0.3 / Nvidia GTX 970

**Issue description:** _(This issue is a feature request)_
In order to make softbody mesh work as intended, one needs to select individual vertices to 'pin' so they can act as anchor points.

However, in certain meshes they can be located in close proximity with each other in which case it's almost impossible to select them individually.

To solve such a problem, either a box or circle selection method similar to what Blender offers could be helpful, especially with an option to select all vertices regardless of their depth.

**Comment by nate066** [comment]
Agreed, being able to select multiple points is needed. tried to add soft body today but would have been to hard due to the amount of points needed to be individually pinned.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
