### ISSUE TITLE
Toggle snap shortcut does not working while moving node

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26855]
**Godot version:**
3.1 RC1

**OS/device including version:**
Windows 10 x64

**Issue description:**
An improvement in use (to stay similar to many editors) would be toggling snap while moving a node.

**Steps to reproduce:**

1. Press W (move)
2. Start moving an object (do not release the mouse button)
3. Press Y (Snap) while moving
4. At this point, the snap should already have toggled and have begun to act in the new snap mode (on or off).
5. But currently, I have to release the mouse, only then the change of the snap is effected.

**Comment by Chaosus** [comment]
CTRL key is already exist for this..

**Comment by Chaosus** [comment]
Ah, perhaps you wanted this functionality for Y shortcut(which is indeed does not working correctly while moving a node), then I should reopen this issue..

**Comment by Janglee123** [comment]
I would like to work on this but don't know where to start as I am just starting to contribute. @Chaosus can you help me? :smiley:

**Comment by Chaosus** [comment]
@Janglee123 Of course, its somewhere in editor\plugins\spatial_editor_plugin.cpp - try found the reason here(I suspect its _edit.snap property) fix it by removing or changing to something else - for all Translation/Rotation/Scale as its seems to be affected for all of them, recompile, and if its worked correctly, creates and send your PR (required instructions for this step located here - http://docs.godotengine.org/en/latest/development/compiling/index.html
