### ISSUE TITLE
Implement British spelling check box in editor.

### ISSUE THREAD

**Issue by MaciejGorczycaGD** [godotengine/godot#26865]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 but applicable to all platforms

**Issue description:**
One of the most annoying thing of differences between American English and British English is spelling of certain common words like Color vs Colour. In Game Maker for example it is not a problem as GML recognises both spellings for build in variables. I think it would be great if build in variables in GDScript were deigned in similar way. Either having GDScript being able to automatically recognised both spelling as valid or have a tick box that allows to switch between different spellings. 

It would be great quality of use for people who spend last 30 or 40 years being used to spelling things one way. 

**Steps to reproduce:**
N/A

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
That won't happen. We can't (and shouldn't) add aliases for core types and many methods just for the sake of supporting British spelling. Otherwise we should add aliases for French, Italian, Russian, Simplified Chinese, Traditional Chinese, Zulu, Farsi... There's no reason to add a feature just for users familiar with en_GB to the disregard of all other users who are not native en_US speakers.

en_US is the lingua franca of Godot's API and of the documentation.

You are free to propose an en_GB localization for the editor and its documentation, but that won't change the API.
