### ISSUE TITLE
Hook methods are being called multiple times when using Script/Class inheritance

### ISSUE THREAD

**Issue by drtwisted** [godotengine/godot#26872]
**Godot version:** 3.1 RC 1

**OS/device including version:** any

**Issue description:**

When inheriting from a script with defined hooks, those hooks are not being overwritten.

**Steps to reproduce:**
```
# parent.gd
extends Node

func _process(delta: float):
    print('Hello from parent')
```
```
# child.gd
extends "res://parent.gd"

func _process(delta: float):
    print('Hello from child')
```
**Expected outuput:**
```
Hello from child
```
**Actual output:**
```
Hello from parent
Hello from child
```

**Comment by Zireael07** [comment]
I believe that is by design.

**Comment by groud** [comment]
Yeah that's expected behavior, that's by design.

**Comment by drtwisted** [comment]
I guess it's not the best and obvious design then. Every other method is being overriden (as is in any other popular OOP language). More over this leads to inconveniences when you, for example want to get rid of parents hook behaviour.

**Comment by akien-mga** [comment]
If the parent's callbacks were not called, none of the nodes you're using would work. All pre-existing nodes work because they do specific stuff in `_draw` or `_process`, or reacting to signals.

The same goes for your own scripts, which allows you to create your own custom nodes with their built-in logic that can be extended further.

If you want to shadow the parent's `_process`, you can do this in the parent:

```gdscript
func _process(delta):
    my_process(delta)

func my_process(delta):
    # this can be overridden in the child nodes
```

**Comment by drtwisted** [comment]
@akien-mga I see know how this works under the hood. Thanks for your help and the work-around solution!
