### ISSUE TITLE
Add options to customize easily HTML5 loading page

### ISSUE THREAD

**Issue by DleanJeans** [godotengine/godot#26913]
Probably in the Export window, to customize the background image, loading bar textures, etc.

**Comment by akien-mga** [comment]
Did you read https://docs.godotengine.org/en/latest/tutorials/platform/customizing_html5_shell.html ?

**Comment by DleanJeans** [comment]
I did, multiple times. I'm not that good at HTML and CSS though I tried to tinker with it.
I don't know, for example, where to add an `<img>` for the splash image without messing the loading screen (like pushing the loading bar to the sides or displaying the image below it or behind it which requires pushing the loading bar down a bit).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
