### ISSUE TITLE
Automatically insert the parentheses of a method or function

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#26923]
**Godot version:**
3.1 rc1

**OS/device including version:**
Windows 10 x64

**Issue description:**
Following the facilities of several good code editors (besides the current "Editor Settings -> Text Editor -> Auto Brace Complete" option), the current AutoComplete option could **automatically insert the parentheses of a method or function**.

**Steps to reproduce:**

Example, typing "vec", the editor automatically suggests "Vector2" and "Vector3". 
Pressing ENTER or TAB, the editor now only has "Vector2".
**My suggestion is that the editor brings the open and closed parentheses after the autocompleted name** "Ex: `Vector2()`" and **automatically place the cursor between the two parentheses.**
This would greatly expedite code insertion.

**Comment by Jimmio92** [comment]
I am 100% against this if it's not completely optional, not that my opinion matters much. xP Editors that type for me have always seemed to just throws me off track for some reason.

**Comment by rogeriodec** [comment]
> I am 100% against this if it's not completely optional, not that my opinion matters much. xP Editors that type for me have always seemed to just throws me off track for some reason.

Obviously, this should be an optional parameter inserted in "Editor Settings -> Text Editor" as in other cases.

**Comment by samH-FIT** [comment]
We are working on it. We've added in the optional setting for now. We still need to add in the functionality.

**Comment by Anutrix** [comment]
What is the optional setting called?

**Comment by Anutrix** [comment]
@samH-FIT What's the status on it?

**Comment by lupoDharkael** [comment]
@akien-mga isn't this already implemented in Editor Settings/Text Editor/Completion/Auto Brace Complete ?

**Comment by dreamsComeTrue** [comment]
The current soultion is half-way trade-off - it uses "Editor Settings/Text Editor/Completion/Auto Brace Complete" but for closing any kind of parenthesis/brackets - but the catch is - you must type opening character first - in my opinion that is good trade-off and issue can be resolved with that solution :)

**Comment by Calinou** [comment]
If this feature is to be implemented, note that parentheses should *not* be added automatically when completing a type hint or an `is` check. This will probably make it significantly harder to implement correctly.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
