### ISSUE TITLE
Add factory method to EditorProperty to instantiate controls for built-in types

### ISSUE THREAD

**Issue by nicktgn** [godotengine/godot#26946]
**Godot version: 3.1 rc2**

**Feature proposal:**
Add a static factory method to [EditorProperty](https://docs.godotengine.org/en/latest/classes/class_editorproperty.html#editorproperty) class to create instances of concrete implementations of `EditorProperty` controls for each built-in type. Considering the most common and logical place to use this method would be inside the [EditorInspectorPlugin#parse_property()](https://docs.godotengine.org/en/latest/classes/class_editorinspectorplugin.html#class-editorinspectorplugin-method-parse-property) of a custom inspector plugin, the signature for this static factory method could replicate the one for `parse_property()`:
```
static EditorProperty build_property( Object object, int type, String path, int hint, String hint_text, int usage )
```
This will make creation of custom inspectors easy and much more flexible, as developers won't need to re-implement custom controls for each built-in type.

**Example use cases**:
1) _Simple_:  A custom inspector for a class with one property dependent on the other one. 
   ```
   # CharacterStats.gd
    extends Resource
    class_name CharacterStats

    export (int, 1, 100) var agility = 1
    export (int) var speed setget set_speed, get_speed

    func get_speed():
         return agility * 2

    func set_speed():
         pass    # make it read-only in code (but this is not properly reflected in the inspector)
   ```  
   We want control for the `speed` property to be displayed in a **disabled** state and update it's value whenever the value of `agility` is changed.

2) _More complex_: A custom inspector for inventory class that displays items from the class bellow as a table, instead of as two separate array properties. 
    ```
    # CharacterInventory.gd
    extends Resource
    class_name CharacterInventory

    enum ItemType {WEAPON, ARMOR, UTILITY}

    export (Array, ItemType) var items_types
    export (Array, String) var items_names  
    ```

This proposal based on previous discussion here #24042

**Comment by nicktgn** [comment]
#24042

**Comment by winNixz** [comment]
This would also be really helpful for loot tables, which contains sets of items and drop chances.
`
extends Resource
class_name LootTable

export(Array, Resource) var items
export(Array, float) var drop_chances
`

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
