### ISSUE TITLE
Move_and_slide_with_snap returning wrong Y motion.

### ISSUE THREAD

**Issue by hardikbhalodi** [godotengine/godot#26959]
**Godot version:**
Godot Engine v3.1.rc2.official

**OS/device including version:**
Ubuntu 18.04.1 LTS

**Issue description:**
Not sure if this one is bug or i missed something but i got strange result when use move_and_slide_with_snap. 
check the GIF when player finished up slope after sometime player automatic do jump.

**Steps to reproduce:**
Try with Move player up slopes few times.

![test](https://user-images.githubusercontent.com/4948894/54192297-9c2a7480-44dd-11e9-8bdb-96b4cb19bc7f.gif)

**Minimal reproduction project:**
[RedRunner.zip](https://github.com/godotengine/godot/files/2956273/RedRunner.zip)

**Comment by TheCire** [comment]
I ran the project with 3.1RC3 and can confirm it still does what is described in the above report.

**Comment by hardikbhalodi** [comment]
@TheCire correct its still there in 3.1 RC3, still not get attention :)

**Comment by turtletooth** [comment]
Confirmed in 3D too.

**Comment by KoBeWi** [comment]
Sooo this is not really a bug. The problem in the project is that it doesn't apply gravity if the player is on floor. When you remove the condition from `fall()`, the jump _almost_ doesn't happen. The reason why it happens is that when you go up slope, the player has velocity upwards, which stays upwards when you reach the flat surface.

Now, there's no reason why `move_and_slide_with_snap` would reset the vertical velocity when on horizontal floor. I mean, it would need to detect that the floor is not a slope, otherwise the player would have problems going up slopes. That said, this not a bug, you can fix it in script. And if you think that the slopes should be handled automatically, [create a proposal](https://github.com/godotengine/godot-proposals).
