### ISSUE TITLE
One click deploy for iOS

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#2703]
I saw somewhere @reduz tried to find a way to implement `one click deploy for ios`.
But, it is not done yet and I leave it here for future task.

**Comment by reduz** [comment]
punto wrote the ios port and he was pretty close

**Comment by romulox-x** [comment]
Was this going to tell xcode what to do, or use the new 3rd party stuff?

**Comment by punto-** [comment]
What is the new 3rd part stuff? If it's reliable (ie Apple is ok with it,
and we don't run the risk of an update that leaves people without the
ability to publish until we fix it) we should use it.. Otherwise I'd say
output an xcode project that can run in debug using the unpackaged project
directory (with the "godot_path" parameter on info.plist), and can also
produce the ipa using the exported data.pck.

**Comment by romulox-x** [comment]
I haven't used the osxcross stuff, but it seems to have been added here: https://github.com/godotengine/godot/commit/b0aa49accbd7e45dae38f1bd43b0fbdd11714211

I share your concerns about reliability.  I don't know the answers to those questions, but I wouldn't be surprised if those turned out to be problems at some point.  This may work flawlessly today, but I'd be afraid of it breaking any time I installed updates on my Mac.  Maybe a "use at your own risk" warning somewhere would be appropriate?

**Comment by volzhs** [comment]
I think current way is good enough.
But it will be better if it's possible. :)

**Comment by reduz** [comment]
if punto can't do this, I will give it a check for 2.1

**Comment by beocat** [comment]
Not sure where this is going but I just noticed a couple of devblog posts from the guys behind Mini Metro about automated build and deploy to connected iphones. Seems to me that the building blocks are there to do the same with Godot, although it requires you to install cfgutil.

http://devlog.dinopoloclub.com/post/138142530760/automated-ios-deployment
http://devlog.dinopoloclub.com/post/138239717055/local-ios-deployment

I might be able to help although I don't really know where to begin - or exactly where we want to end with iOS build and deployment.

**Comment by reduz** [comment]
This is pretty cool, I was thinking of working on this this month

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone. (Though it would be pretty cool to have in 2.1 if @punto- or @reduz can have a closer look at it)

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
