### ISSUE TITLE
perfectly matching 3D objects cannot be composed together because edges are clearly visible.

### ISSUE THREAD

**Issue by avril-gh** [godotengine/godot#27037]
**Godot version:**
godot master branch 775e74e0d41daa9cf3679c2e215f4ef46eee9cbc

**OS/device including version:**
Windows 7 x64, GT720
Issue occurs in both GLES2 and GLES3

**Issue description:**
Cut out objects are widely used in games to create rich environment, saving resources, speed up design time and in many other cases. For example, characters can be composed from separate parts to easly replace outfits, most of game objects can be composed from cut out assets to create many variations ect). Unfortunately, **perfectly matching each other 3D objects are unable to be composed together because edges of these objects are clearly visible**.
Look at simple 1 tile example shown on picture below.
![tiles distorted](https://user-images.githubusercontent.com/3224132/54330051-89ff2200-4614-11e9-8a1e-b878b2acef74.jpg)

**Minimal reproduction project:**
[3d-tiles-edges-distorted.zip](https://github.com/godotengine/godot/files/2964653/3d-tiles-edges-distorted.zip)

**Comment by clayjohn** [comment]
This is an issue with the texture you are using. Not with Godot. 
![tiles_atlas](https://user-images.githubusercontent.com/16521339/54330685-e8f07700-45d3-11e9-84bc-cdcca39455d3.png)

Notice the lines present in your texture? Those are what are appearing. When mip-maps are computed for a texture by blurring successive versions of the same image. Because your image has those lines in it, they get blurred in with the rest of the texture in the successive mip-map levels. You need to edit your texture so that it just has the stuff you want, or you need to disable mip-mapping. This would be the case no matter what engine you use.

**Comment by avril-gh** [comment]
i thought the same, because i used exacly same objects and textures in godot 2.1 and switching mipmaping there solved it.

The problem is i cant find how to disable mipmaping in godot 3.1  Any tips on this ?

**Comment by clayjohn** [comment]
Sure! open the filesystem tab (on my computer its on the right side) and select your texture from there. Then open the import tab (on my computer it is in the top left corner). In the import tab scroll down until you see the "Mip-Maps" checkbox, uncheck it and then press the "re-import" button. That should do it for you!

**Comment by avril-gh** [comment]
wow, **thats exacly what i been looking for**, for like half of hour and couldnt find it.
In godot 2.1 they are in material inspector.
![mipmaps](https://user-images.githubusercontent.com/3224132/54333466-d9e4e580-4622-11e9-81c7-a637f42029ab.jpg)
I allready began to believe these options got completly removed or what, and they just been moved to different place. Awesome! Thanks for showing me it.

closing as resolved.
