### ISSUE TITLE
In the new AnimationPlayer it's harder to see deleted nodes in the Scene

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#27053]
Godot 3.1 stable, Windows 10

I really liked in the old AnimationPlayer that deleted nodes in the scene view would have a red line slapped over them. It made it very easy to see if a path was wrong. Now it changes the path to the full path instead

![animationplayergodot31](https://user-images.githubusercontent.com/24936603/54369622-8a300980-4676-11e9-9197-e6bf2a5e686d.jpg)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
