### ISSUE TITLE
Line ending setting

### ISSUE THREAD

**Issue by Zireael07** [godotengine/godot#27057]
**Godot version:**
3.1

**OS/device including version:**
Ubuntu 18.04 LTS

**Issue description:**
I have several Godot projects. Not all of them have github repositories, so when changing computers I simply copied them over. Unfortunately it means that initing a git repo (or running a command that is sensitive to line endings) shows all files as having ^M (line feed) characters due to their having been copied straight from Windows.
While there are tools to fix this for text files, most files fail to be registered as text by those tools such as dos2unix.
Most IDEs (e.g. PyCharm, Sublime Text 3) have a line ending setting and/or a convert LF to CRLF / CRLF to LF switch.
Could we please get one in Godot, too?

Note that this is distinct from the old issue as this is mostly about new repos, not badly configured old repos (the projects simply do not have a repository yet)

**Steps to reproduce:**
Copy files from Windows to Linux machine, attempt to commit/create a git repo.

**Minimal reproduction project:**

**Comment by kmcphillips** [comment]
I would love to have the line ending be configurable by a flag. That way teams can organize their projects and control the format of the files as they are saved.

I am a programmer but I am not a C++ programmer. I looked at trying to figure this out, but it seems like a substantial feature, and not a great first issue.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
