### ISSUE TITLE
Editor selections are not registered in the undo stack

### ISSUE THREAD

**Issue by ssoher** [godotengine/godot#27098]
**Godot version:**
3.1.stable.official

**Issue description:**
Selection changes are not undo-able currently. For example if I want to do a MultiNodeEdit in a complex scene, I select all the nodes I require for the operation by ctrl + clicking and then if I click on any empty space by mistake, my whole selection is gone. There should be a way to undo this instead of trying to re-select everything very carefully. All the the other engine editors register selection changes to the undo stack, I think Godot should too.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
