### ISSUE TITLE
godot 3.1 exe size

### ISSUE THREAD

**Issue by codz01** [godotengine/godot#27140]
Hi
just noticed that my game size is a little big 34mb 
i am using godot win32 version , maybe thats because godot was compiled using mingw 

i am sure if you build it with MSVC the size will reduced dramatically

**Comment by akien-mga** [comment]
> i am sure if you build it with MSVC the size will reduced dramatically

Try it and tell us :)

**Comment by codz01** [comment]
I dont know how :p

**Comment by reduz** [comment]
you can use UPX to compress your executable by the way
https://upx.github.io/

**Comment by Calinou** [comment]
See [Optimizing a build for size](https://docs.godotengine.org/en/latest/development/compiling/optimizing_for_size.html) in the documentation.

**Comment by akien-mga** [comment]
Well I can already tell you that there is no significant size difference between MSVC and MinGW binaries nowadays. 34 MB is just Godot's size.

We switched from MSVC to MinGW between 3.0.2 and 3.0.3, see the size differences:
https://downloads.tuxfamily.org/godotengine/3.0.2/
https://downloads.tuxfamily.org/godotengine/3.0.3/

The Win32 zip for the editor build did go from 15.9 MB to 17.1 MB (7% increase), while the Win64 zip went from 19.3 MB to 17.3 MB (10% *decrease*).

Godot 3.1 is a bit bigger because it has a lot more features and some more dependencies.

**Comment by codz01** [comment]
yeah , you are right there is no big deference  , i don't know where i get the impression that msvc could generate significant smaller size !

**Comment by avril-gh** [comment]
godot 3.1 MSVC compiled sizes are
```
56 109 056 godot.windows.opt.tools.64.exe
28 927 488 windows_32_debug.exe
25 346 048 windows_32_release.exe
33 345 536 windows_64_debug.exe
29 228 032 windows_64_release.exe
```
