### ISSUE TITLE
Node set_process* as properties

### ISSUE THREAD

**Issue by Naryosha** [godotengine/godot#27154]
**Godot version:**

3.1

**OS/device including version:**

Manjaro x86_64

**Issue description:**

Expected: `node.process = false` is the same as `node.set_process(false)`
Happened: process and the likes aren't properties yet

I checked the source and they seem to be commented out since the beginning.
https://github.com/godotengine/godot/blob/df7d3708c5b535c3696943322a14ec19a175e30c/scene/main/node.cpp#L2852-L2855

They have both setter and getter, so I think it's qualified as a property. Maybe remove the `property_usage_store` flag so it doesn't save to file.

Pros: familiar property set/get syntax, less clutter in docs
Cons: break games that use `process` as var name

![image](https://user-images.githubusercontent.com/43379543/54486649-cb662a80-48bd-11e9-8bb9-bd6609f143e0.png)

**Comment by Byteron** [comment]
if the property syntax is what gd script is going for than that should be changed, imo.
Consistency is important.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
