### ISSUE TITLE
Setting KinematicBody2D.collision/safe_margin < 0.01 causes intersection jitter

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#27186]
**Godot version:**
3.1 stable

**Issue description:**
This is an issue specific to 3.1 that didn't affect 3.0.6, possibly because of changes in how kinematic collisions are handled.  When setting the safe margin to a very small number (such as 0.001), collisions made with `move_and_slide()` create a ton of jitter, but only at specific small float values, such when using analog movement.

![Gif](https://i.imgur.com/7zWWKgn.gif)

**Comment by eon-s** [comment]
This is not exactly a jitter as defined on http://docs.godotengine.org/uk/latest/tutorials/misc/jitter_stutter.html
Looks more like a bounce due to bad separation margin.

I do not see the bug here, but is curious what could have made the difference in the behavior of KinematicBody2D, probably the way input strength is now handled.

Margin property may need tests and better documentation (including the jitter fix and other new options related to physics bodies).

**Comment by nobuyukinyuu** [comment]
Yeah I should've been more explicit, this isn't temporal jitter, it is weirdness in how the restitution seems to work. The body is pushed out / separated by different amounts in a way that appears to get larger as the safe margin and movement vector approach some kinda precision limit.  The behavior is different than that of 3.0, but I'm not sure if it's a more "correct" behavior or not (!)

**Comment by akien-mga** [comment]
It doesn't seem to be a bug to me. The `collision/safe_margin` is specifically designed to avoid this issue, so if you set a margin too low, you run into it. With a too low margin, the body will *enter* the collision shape slightly, and be ejected out at the next frame, hence the physics "jitter" seen here.
