### ISSUE TITLE
Making a custom theme overrides the Godot editor theme

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#27192]
Godot 3.1 stable (GLES 2).

Making a custom theme for a node overrides the engine default theme.
So, you end up customizing the editor buttons if you make a custom theme for your game.

![godot](https://user-images.githubusercontent.com/19626687/54504116-42241780-4900-11e9-852c-0321d2d79c83.png)

**Comment by toger5** [comment]
Can you explain more precisely how u achieve that?
My guess: Create theme (from editor theme) -> create a control node in the current scene -> change the theme -> the whole editor changes.

It would be good to know if that only happens when using the `create form editor theme` option.
Or can u create any theme? 

Probably the create from editor theme does not duplicate all the resources so that you can editor the same resource (sb) that is used by the editor.

**Comment by ca3games** [comment]
> Can you explain more precisely how u achieve that?

I'm not sure how It happened, but I was creating a custom theme for my buttons, so I created a theme on the inspector from the button properties and edited and saved the theme to be reused among multiple buttons.

**Comment by bojidar-bg** [comment]
There was #4587 in the past.

**Comment by CowThing** [comment]
Related to #20123?

**Comment by akien-mga** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

**Comment by valentinAlkan** [comment]
@akien-mga Yes, in 3.2.1 stable mono on windows and 3.2.1 stable on linux. 

To reproduce, create a new scene, create a control root node, select theme, and select create from current editor theme. Without looking at the code, it seems to return a pointer to the current editor theme instead of a pointer to a copy of the current editor theme.

See the below gif. Ignore the yellow bugginess at the end (may be part of the bug? It doesn't do that on my desktop, it's only in the Gif that gifcam captured). The relevent detail is that the LineEdit controls throughout the editor change even though it should be a new theme.

![theme](https://user-images.githubusercontent.com/19651331/86405511-80715180-bc7f-11ea-8147-8ec7ed3ff0c6.gif)

**Comment by dalexeev** [comment]
> and select create from current editor theme

This is not necessary, I get the bug even with this theme:

```
[gd_resource type="Theme" format=2]

[resource]
VBoxContainer/constants/separation = 0

```

![](https://user-images.githubusercontent.com/47700418/94585749-1caff200-0289-11eb-8b1c-f3b4b6c02033.png)

**Comment by Flavelius** [comment]
Still reproducible in 3.2.3, used copy from current editor theme, some elements in the editor are affected.

**Comment by KoBeWi** [comment]
Fixed with new theme editor

**Comment by nathanfranke** [comment]
Is `gui/theme/custom` supposed to override the editor theme? I changed button `h_separation` here.

![image](https://user-images.githubusercontent.com/14253836/189738426-c5328142-9758-4301-add0-6d14d1b3ee97.png)

**Comment by Calinou** [comment]
> Is `gui/theme/custom` supposed to override the editor theme? I changed button `h_separation` here (look at the top editor screens).

No, but this is being tracked in https://github.com/godotengine/godot/issues/60930 already.
