### ISSUE TITLE
AudioStreamSample Editing Enhancements for Looping Audio

### ISSUE THREAD

**Issue by hasahmed** [godotengine/godot#27198]
**Godot version:**
3.1

This is an enhancement suggestion. 

In the properties of the AudioStreamPlayer you can edit the AudioStreamSample.
There are options here to set whether or not the audio should loop, and the bytes where the audio looping should start and stop. I was thinking that ideally you should be able to click somewhere on the track to select where the audio looping should start and where it should stop.
Another solution that may be potentially easier to implement (granted I have no idea) might be to allow the user to input loop_start and loop_stop in seconds. This would be especially nice because the track is displayed at the bottom with a selection cursor showing you the position in seconds already.

**Comment by Zylann** [comment]
If the property is in seconds then it should still be precise enough to select a zero-crossing sample index, otherwise it would cause a click.

**Comment by KoBeWi** [comment]
You can set looping in seconds from import tab. At least for .ogg files.

**Comment by hasahmed** [comment]
@KoBeWi I don't think you can for .wav files.
@Zylann I think some engine magic cross-fade would be awesome.

**Comment by vetu11** [comment]
This should be discussed in the https://github.com/godotengine/godot-proposals/ repository

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
