### ISSUE TITLE
Audio Expansion Request - VST Support

### ISSUE THREAD

**Issue by paulallenbright** [godotengine/godot#27209]
There are a lot of vst processing components out there for audio processing as well as VST instruments.   It would be awesome if this game engine allowed you to load any vst within the game engine and use it to process your game audio, or load a vst instruments and make music using it within the engine.    Just an idea..thanks !!!

**Godot version:**

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zylann** [comment]
I thought VST were widely Windows-based, but it turns out there was recent shift to support Linux: https://github.com/steinbergmedia/vst3sdk

Not sure it would work on mobile platforms though.
I don't know what it would take to implement a VST host in Godot, but it sounds like an optional module should be made rather than making it built-in.

**Comment by paulallenbright** [comment]
Whatever works .. it would be a very cool
Windows feature. 😀

**Comment by toasteater** [comment]
Note that the SDK is proprietary or GPLv3 (copyleft), and Godot is MIT licensed (permissive). Those licenses are not compatible. Thus, it's impossible to include this in Godot.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
