### ISSUE TITLE
Webgl 3d export is black

### ISSUE THREAD

**Issue by smkplus** [godotengine/godot#27223]
my project works correctly but when I export webgl it's black
I'm sure that added light to scene

![aaawddawdaw](https://user-images.githubusercontent.com/16706911/54585466-6894a080-4a2f-11e9-8513-76afab9d4e49.PNG)

![4](https://user-images.githubusercontent.com/16706911/54585405-400ca680-4a2f-11e9-840e-a8ceeebce4f0.PNG)

![5](https://user-images.githubusercontent.com/16706911/54585501-7e09ca80-4a2f-11e9-8707-be08aaf15ee4.PNG)

https://smkplus.github.io/Test/html5/index.html

**Comment by eon-s** [comment]
Fill the template: Godot version, OS, GPU, GLES mode and browsers tested in this case.

**Comment by SiberianCatz** [comment]
So, tried and I got 

> Failed loading file 'Isometric Game.wasm' 

error. But when I uploaded my files to firebase hosting, it worked.

I did some deep research, and I found that when you open inspect element and then -> console, there was error log that says:

`Access to XMLHttpRequest at 'file:///C:/Users/catma/Documents/Godot/Isometric/export/html5/Isometric%20Game.wasm' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

So I guess something blocks the .wasm file which is very important for loading correctly

**Comment by yhydra** [comment]
watching this as id switch to godot if the webgl build works

**Comment by nate066** [comment]
Most web browsers wont load a web app from the file system, the files need to be hosted on a web server before it will load usually.

**Comment by eon-s** [comment]
Without the required details is not possible to say where is the problem.
For example, this is the Platformer 3D demo running on Ubuntu, using amdgpu on r5, firefox, on gles2 mode:

![platformer3d](https://user-images.githubusercontent.com/10215987/54649717-251b5000-4a8a-11e9-8ae4-0b0bc0684c4c.gif)

**Comment by nate066** [comment]
chrome wont load local webgl app for security reasons, you can force it but its not recommended.

https://gamedev.stackexchange.com/questions/117349/unity-5-3-webgl-build-not-working-on-google-chrome
https://forum.unity.com/threads/unity-webgl-not-supported-on-google-chrome.306512/

According to the above two links it will run on firefox as firefox has no issue loading local files.

Although if the above browser isnt chrome or another browser that blocks local files then it could be a godot issue.

Although I have the same issue with chrome with the same errors which are solved by using a web server.  More information is always better, but I think this is the issue specifically because when it was local it did not work but when uploaded to a web host it did. I dont think the issue should be closed yet until we confirm what the issue is.

![nowebserver](https://user-images.githubusercontent.com/11403345/54653356-c4434600-4a90-11e9-9f15-21d151971700.PNG)
![webserver](https://user-images.githubusercontent.com/11403345/54653365-cb6a5400-4a90-11e9-97c5-894cc2cf526e.PNG)

**Comment by eska014** [comment]
As mentioned above, Chrome requires a server, such as Python's local server.
https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html
