### ISSUE TITLE
get_current_dir() trailing "/" inconsistent between platforms

### ISSUE THREAD

**Issue by argento2** [godotengine/godot#27234]
**Godot version:**

3.1

**OS/device including version:**

android and linux

**Issue description:**

`var dir = Directory.new()`
`dir.open("res://test_dir/")`
`print(dir.get_current_dir())`
`dir.open("res://test_dir")`
`print(dir.get_current_dir())`

In linux this code prints "test_dir/" with a trailing "/" the first time and "test_dir" without the trailing "/" the second time

In android this code prints "test_dir" without the trailing "/" two times

I report this as a bug even if it seems a minor issue because in linux my code
`dir.get_current_dir() + file_name`
was working because dir.get_current_dir() already had a trailing "/"

but in android the same code didn't work and it took me a while to understand why:
in android the loader was searching in "res://test_dirresource_name" instead of "res://test_dir/resource_name"

I didn't test this issue in other platforms.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Can you still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-rc2](https://godotengine.org/article/release-candidate-godot-3-2-2-rc-2))?

Note that the solution to your issue is to not rely on the internal representation of directories and use `String.plus_file()` instead, which will add a `/` if it's necessary.

**Comment by akien-mga** [comment]
No answer, so closing. Please comment if you can still reproduce the issue in Godot 3.3 or later.
