### ISSUE TITLE
Support for mp3 audio playback (now that the license program is terminated/patents expired)

### ISSUE THREAD

**Issue by exts** [godotengine/godot#27236]
**Godot version:**
3.2

**OS/device including version:**
All

**Issue description:**
Currently out of the box godot only supports wav and oggvorbis audio playback. Now mp3 being the most popular format and it's licensing program has been terminated and patents expired and aren't being renewed this would mean mp3 is free game now if I'm not mistaken.

https://hackaday.com/2017/05/14/patents-on-mp3-format-due-to-expire/

**Comment by tempdoom** [comment]
I really hope they do add mp3 support. It'd save me from a real headache. If they aren't planning, how possible is it to "manuallly" implement mp3 support?

**Comment by Calinou** [comment]
@tempdoom Wouldn't Ogg Vorbis fit your use case? The only use I see for supporting MP3 audio is using existing MP3 audio (where you don't have a lossless/uncompressed source), which is unlikely when you're legally using such audio.

**Comment by exts** [comment]
Using existing mp3 is my use case personally. I was working on a podcast
player and ran into a wall.

**Comment by tempdoom** [comment]
For me it's that I'd like to allow custom audio files (specifically music) to be imported to the app, and most people's phone music libraries use mp3s. This is more for android than apple, as there are it seems some more hoops to jump through with apple, but that I can do fairly easily. I already use .ogg files in the default app.

**Comment by DeleteSystem32** [comment]
> I really hope they do add mp3 support. It'd save me from a real headache. If they aren't planning, how possible is it to "manuallly" implement mp3 support?

If you're still interested in this, I wrote a rudimentary module for MP3 support through Minimp3: https://github.com/DeleteSystem32/godot-minimp3

Currently working on performance improvements.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
Note that there's already an open proposal about this: https://github.com/godotengine/godot-proposals/issues/85
