### ISSUE TITLE
High performane video codec HAP

### ISSUE THREAD

**Issue by drop1down** [godotengine/godot#27250]
Feature request:

Playing OGV or WEBM Videos is very very slow.
Tested on my machine: 1 Full HD OGV Video and some graphics with 30-60 fps
And WEBM is much slower than that.

But here exist a free ultra high performance video codec that use hardware acceleration: HAP 
https://github.com/Vidvox
https://hap.video/

It is a lot faster than other codecs:
https://hap.video/benchmarks.html
Is should be possible to play 16 Full-HD-Videos at one time.
And transparency is also supported!

HAP is already integrated into ffmpeg for conversion.
HAPs files are big: this is not nice for games, but suitable for "live graphics performance".

Example of HAP for unity:
https://github.com/keijiro/KlakHap

**Comment by girng** [comment]
would be awesome, +1

**Comment by akien-mga** [comment]
You should be able to load those with https://github.com/KidRigger/godot-videodecoder if they're supported by FFmpeg.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
