### ISSUE TITLE
Allow 2D light shaders to do their own normal calculation

### ISSUE THREAD

**Issue by toasteater** [godotengine/godot#27268]
**Godot version:** 3.1 stable

**OS/device including version:** GLES3 backend, 2D renderer.

**Issue description:** Without access to light strength after normal calculation, it's not straightforward to tweak material appearance with light processors. This is possible to work around currently, but is cumbersome and inefficient.

Example use case: For simplicity, suppose that you want your Light2D to have a cel shading flavor to go with flat shaded sprites, you would have to figure out what Godot would multiply with the light, and then counteract it with something like this:

```glsl
void light() {
	// same normal calculation performed later in canvas.glsl
	vec3 light_normal = normalize(vec3(LIGHT_VEC, -LIGHT_HEIGHT));
	float would_be_strength = max(dot(-light_normal, NORMAL), 0.0);
	// trick godot into giving back what we want
	if (would_be_strength > 0.4) {
		float target_strength = 0.5 + would_be_strength * 0.2;
		LIGHT *= target_strength / would_be_strength;
	} else {
		LIGHT *= 0.6;
	}
}
```

This will cause the same normal calculation to be done twice, and is prone to division by zero problems if not careful. It's also a hack that may stop working any time. Instead, we should be able to do away with the extra operations and just output what we like:

```glsl
void light() {
	vec3 light_normal = normalize(vec3(LIGHT_VEC, -LIGHT_HEIGHT));
	float s = max(dot(-light_normal, NORMAL), 0.0);
	if (s > 0.4) {
		s = 0.5 + s * 0.2;
	} else {
		s *= 0.6;
	}
	// FRAGMENT_LIGHT would be a magical built-in that when used, will turn off normal calculation in canvas.glsl via preprocessor
	FRAGMENT_LIGHT = LIGHT * LIGHT_COLOR * s;
}
```

**Steps to reproduce:** N/A
**Minimal reproduction project:** N/A

**Comment by khoulihan** [comment]
This is what I'm after as well, specifically for cel-shading pixel art.

I believe it would also help with another situation I am tackling, which is putting the lights above a game world that is not purely top-down or side-on. There is a demo of this for Godot 2.1, but I believe it would be more straightforward if the output of the custom light shader did not also have light calculated as if it is directly above the canvas.

**Comment by Ijatsu** [comment]
Any news about this?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
> I see this was closed in favor of another proposal. That proposal is 3D though, how does that solve the 2D issue?

I didn't notice that. You can open a new proposal :slightly_smiling_face:
