### ISSUE TITLE
PhysicsDirectSpaceState intersect_ray exclude does not work with GridMaps

### ISSUE THREAD

**Issue by Toshiwoz** [godotengine/godot#27282]
No existing issue was found.

**Godot version:**
3.1 official release

**OS/device including version:**
Windows 10 pro with Mobile Radeon GPU (R5 M330)

**Issue description:**
When using intersect_ray with exclude parameter as an array that includes a series of GridMap nodes I am expecting it to avoid intersecting with that node.
And if I use it with normal static bodies it works as expected.

But, if I do the same with Gridmaps, with a MeshLibrary that is composed of MeshInstances with it's StaticBody+CollisionShape, it doesn't.
Debugging it I was expecting to see that the Collider would not be the GridMap node itself, but it is actually that the node, so I do not think it is a misuse of exclude here.

Here is where it happens in code:
```gdscript
func ray_intersection(_start, _end, _exclude = []):
	var returnpoint =  null
	if space_state != null:
		var ray_intersect = space_state.intersect_ray(_start, _end, _exclude)
                # add brakepoint below
		if ray_intersect.has("position"):
			returnpoint = ray_intersect.position
		return returnpoint
```

![ray_intersect_exclude_debug](https://user-images.githubusercontent.com/21297356/54721766-e12f5600-4b30-11e9-9c88-be359d137e0b.png)
Here in the image you can see that the excluded object (passed as an array), have the same ID as the collider.

In my opinion here it's not working as it should.

**Steps to reproduce:**

- Open the sample project here and click on the plane, see debug on `ray_intersection` function. Works as expected
- Click on the cube, should collide with object behind, the plane, again, but it doesn't.

**Minimal reproduction project:**
Here is the project with minimal content.
[intersect_ray test.zip](https://github.com/godotengine/godot/files/2990274/intersect_ray.test.zip)

**Comment by Toshiwoz** [comment]
It seems also that even if I manage to exclude successfully using collision_masks, and the collider returned is correct, I still get the collision position of the first collidable node encountered.
Will post an update later.

**Comment by eon-s** [comment]
GridMap is not a Body so it will not work. That and TileMap need some reference or something that can be used as body, for this use and for contact callbacks on typed GDScript.

**Comment by Toshiwoz** [comment]
@eon-s I'd agree if it wasn't that it reports contact with that node, it is what is shown in the picture, what is not visible there is the node path, that it matches, together with the same id as the object I'm trying to exclude, looks like an issue.
Or else, how would I exclude it and get the desired contact point?

In my second post I also reported that using collision masks it excludes the object but reports the wrong contact point, another reason to believe that there's a problem.

**Comment by Toshiwoz** [comment]
@akien-mga are you sure this is not a bug instead of an enhancement?
Because, if you apply [this tutorial](https://docs.godotengine.org/en/latest/tutorials/physics/ray-casting.html?highlight=intersect_ray) to 3D it won't work, as far as my understanding of this method goes.

**Comment by Toshiwoz** [comment]
#22891 related?

**Comment by KurtBliss** [comment]
Seems to be still the case for 3.2.3. 

I'm not sure if this would be a solution to this issue, thinking not because it wouldn't take into consideration things not in the gridmap, depending on what you're trying to do. 
https://godotengine.org/qa/67118/3d-how-to-get-gridmap-tile-using-intersect_ray

So thinking best solution to this is just use the raycast node... Not sure what difference they're if any really, just not as convenient to use. 

Hope to know whether this is a bug, or if they instead to making it work this way. Subscribed.

**Comment by skaiware** [comment]
Still an issue with 3.3.2 apparently. And not only with GridMaps : RigidBodies in static mode dont seem to be excluded at all from the raycast, at least when using RIDs.

**Comment by spindlebink** [comment]
This happens with 4.0 as well, and it doesn't have to be `PhysicsDirectSpaceState`--using a regular `RayCast` node and `add_exception` won't ignore `GridMap` collisions either.

[gridmap_ray_test.zip](https://github.com/godotengine/godot/files/7492160/gridmap_ray_test.zip)

**Comment by smix8** [comment]
This should either be closed for Godot 4 or moved back to an old Godot 3.x milestone that still allows to use random objects (that error out silent) with those object/node based add/remove exception functions.

In Godot 4 the exception functions require a valid CollisionObject2D/3D inheriting object/node and both GridMap and TileMap are not CollisionObjects so why should it work with those exception functions.

Instead of using those limited, object based exception functions use `collision_layers` to exclude certain physics objects.
