### ISSUE TITLE
Make true copy and paste as well as Ctrl+C, Crtl+X, Ctrl+V throughout the editor a thing

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#27280]
**Godot version:**
3.1 stable

**Issue description:**
If as a user you think you should be able to cut, copy and paste one thing* to another place, the editor should allow it. 
Ctrl+C, Ctrl+X, Crtl V should copy/cut/paste the entirety of the selected thing(s). Right mouse click on the selected thing should offer only sub-categories or sub-properties of the selected thing to be copied or the whole thing. Pasting should be infinitely possible, without the need to have the selection focus on the thing I want to copy (this would be duplicate)
Pasting allows the user to choose the paste location freely at the current selection focus. Unlike duplicate, there may any number of operational steps in between respective copy and paste, because the copied thing is stored in the clipboard.

The pasted thing should unique by default. (Copy reference/paste reference an option in the right mouse click context menu)

We should implement it not only in already existing features, but should make it a quality requirement when new features are added.

*Thing(s) like: 

- nodes (in the scene panel, 2D, 3D view),
- keyframes (including values and transitions, within tracks, from one track to another, from one animation to another), 
- tracks (within the same animation, to other animations), 
- animations (from one AnimationPlayer to another), 
- files (in the file browser), 
- scripts (via right click on the script symbol, right click on the script browser or when highlighted)
- properties (right click on a node in the scene panel)
- signals (highlight the signal symbol in the scene panel or right click)
... and so on ...

Examples where such functionality is requested:
https://github.com/godotengine/godot/issues/24950
https://github.com/godotengine/godot/issues/3720
https://github.com/godotengine/godot/issues/23024
https://github.com/godotengine/godot/issues/13380
https://github.com/godotengine/godot/issues/7605
https://github.com/godotengine/godot/issues/15029
https://github.com/godotengine/godot/issues/30197
https://github.com/godotengine/godot/issues/11359
https://github.com/godotengine/godot/issues/30137
https://github.com/godotengine/godot/issues/27279
https://github.com/godotengine/godot/issues/27813

**Comment by golddotasksquestions** [comment]
Here is why I think we need this issue (from my reddit post):

I think we need this overarching issue because yes, there already have been implementations of copy and paste throughout the editor, but a) unlike other software it's not a common feature, b) they are all implemented differently. I would not want us to continue down this road.

Sometimes you will find copy and paste only in a context menu, sometimes it's hidden in a drop down, sometimes it is called duplicate and not actually a true copy and paste, sometimes it copies as just reference, even though it says copy. It's not coherent. Having all these different operational paths for the same basic thing is unintuitve, confusing, requires more learning effort for no reason, and worst of all it misses the simple, globally well known "### select thing -> copy (Crtl+C) -> go to paste location -> paste (Ctrl+V)" behavior.

As a novice Godot user, I should learn about nodes, signals and groups, not how to copy and paste.

The goal of this issue is to make Ctrl+C, Crtl+V as common place and straight forward as it is in other editing software and with it make Godot more user friendly and intuitive.

**Comment by golddotasksquestions** [comment]
[](url)

**Comment by golddotasksquestions** [comment]
Damn it, still new to Github. How do I "unclose"? I missclicked.

**Comment by rogeriodec** [comment]
So I have many nodes in a scene. I want to pick just one of these nodes and put it to another scene (because I realize that this node should be in one scene and not another). 

Currently, I have to:
1) Right-click on the source node 
2) Save Branch as a Scene
3) Go to the target node
4) Right-click on the parent node
5) Merge from Scene
6) Delete the previously saved scene

So I think it could be easier with just a copy/paste.

**Comment by ryanhuellen** [comment]
Where is this feature? Over 2 years later and this is still not a thing.

**Comment by clayjohn** [comment]
@ryanhuellen It has barely been two months, let alone two years. Please be patient. 

Features are added when random users decide to add them. Until someone decides they want to take this issue up, the rest of us will just have to wait.

**Comment by Anutrix** [comment]
Should this be implemented separately for each part of the Godot GUI?
Why not create a ClipboardManager class that manages all these stuff? It could even save the clipboard state on close as a feature if needed. Every time something is CTRL+Ced we could send that data to ClipboardManager which will process it as needed depending it's type(text, node, scene, button, resource, etc.).

**Comment by keenfoong** [comment]
Plus one to this. One of my gripes especially with nodes. If nodes can duplicate, why not have a copy paste as well?

**Comment by golddotasksquestions** [comment]
I'm hearing "shallow copy" and "deep copy" right now for the first time. Please, let's not bring even more rare concepts into this!

The purpose of this issue is to do the exact opposite: Make sure incredible well known interaction with software (cut/copy/paste, (Crtl+X)(Crtl+C)(Crtl+V)) is existent and consistent in the Godot editor.
These commands create a duplicate file or piece of data in every operation system and editing software of pretty much any kind. Therefore it's intuitive behavior. It's something we don't have to teach.
Using those commands to establish connections to references files is not even remotely known behavior. There is no reason why we should not have our own set of commands for this functionality. But but the love of Linus, let's please not use the most well known editing commands for something else than they have been used since the dawn of the digital age.

**Comment by Anutrix** [comment]
@golddotasksquestions Shallow copy and deep copy are not rare concepts. You might have heard them about it as some different terms.
You **might**  be right about the copy-paste behavior because I haven't tested it yet, but for now, let's wait and see what other devs and users here think.

**Comment by noname1477** [comment]
Why not just rename 'Merge from Scene' to 'Copy from Scene'? We wouldn't have to introduce a new feature, though it would still be easier for beginners. And everyone else would know what it does.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by golddotasksquestions** [comment]
Discussion on this issue moved over to https://github.com/godotengine/godot-proposals/issues/955
