### ISSUE TITLE
GLES2 shadows are much darker than GLES3

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#27290]
Godot 3.1 stable GLES2
GeForce GTX 750 Ti/PCIe/SSE2
Windows 10 64 bits

When helping someone having issues with shadows on GLES2, I noticed that shadow color is much, much darker than GLES3, as if the color was darkened along a quadratic curve.
Example:

![image](https://user-images.githubusercontent.com/1311555/54757091-6f631500-4be1-11e9-935b-e45c33c1a846.png)

As you can see both have the exact same setup, but the left one is too dark, while the right one matches the color set in the inspector. I didnt expect such a difference on such a basic scene with a default  environment because both renderers support all features used here.

GLES2 project: 
[GLES2_Shadows.zip](https://github.com/godotengine/godot/files/2992344/GLES2_Shadows.zip)

GLES3 project:
[GLES3_Shadows.zip](https://github.com/godotengine/godot/files/2992350/GLES3_Shadows.zip)

**Comment by Calinou** [comment]
Is the color in GLES3 comparable when HDR is disabled in the Project Settings? (HDR is not supported in the GLES2 renderer.)

**Comment by Zylann** [comment]
@Calinou I'm not sure why HDR would make this scene brighter or darker?

**Comment by Garrom** [comment]
@Zylann That is exactly what it does. Technology known as HDR or High Dynamic Range manipulates brightness of various parts of image to create image with not too high or too low brightness. Taking all facts into account, HDR not supported on GLES2 sounds like possible cause of effect we are seeing.

**Comment by Zylann** [comment]
@Garrom I know this, but to me it sounds like if you make a GLES2 renderer, and expose a shadow color property, it should produce shadows of that color, which is far from the result I see.

Another example here, with an almost vertical light, on pure white ground, shadow is way darker than the color set in the inspector:
![image](https://user-images.githubusercontent.com/1311555/54786366-8ffe8f80-4c20-11e9-92ae-af13f9acde9c.png)

**Comment by Garrom** [comment]
@Zylann I see what you mean. Color property is like input and drawn shadows are like output. If is output different from input, mistake must be somewhere in between. I tried to replicate your problem. You won this one, HDR indeed does not have visible effect, however, now it looks like **your** problem because I failed to replicate it. Image below shows how it looks on my computer. GLES 2 is slightly darker but it is not nowhere near effect you are seeing.
![GLES](https://user-images.githubusercontent.com/24418090/54814975-236fa900-4c91-11e9-8aa5-d4f0b033aeaa.png)
I believe I don't have to tell you this, but GLES 2 is missing a lot of stuff compared to GLES 3. But now I believe it can be problem with hardware setup. What shaders do if is feature missing ? It just don't execute it or throws error ? I'm not much into shading but I still want to help. Maybe is GLES 2 implemented poorly on your GPU. For hardware companies is nothing new to treat OpenGL like second or third class citizen.
