### ISSUE TITLE
GridMap `get_cell_item_orientation()` returns an integer instead of a Vector3

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#27314]
Godot 3.1 stable

Ubuntu 18.04

Hey. I use GridMap. I tried `get_cell_item_orientation` and it returned `integer`
But I expected `Vector3`

**Comment by Zylann** [comment]
I think that integer is an index to a sort of packed quaternion, because not only it can orient as an axis, but rotate around that axis, by steps of 90 degrees

**Comment by DimaKiva** [comment]
Thank!

**Comment by DimaKiva** [comment]
```
func orthogonal_hren(value):
	if value == 0:
		return(Vector3(0, 0, 0))
	elif value == 1:
		return(Vector3(0, 0, PI/2))
	elif value == 2:
		return(Vector3(0, 0, PI))
	elif value == 3:
		return(Vector3(0, 0, -PI/2))
	elif value == 4:
		return(Vector3(PI/2, 0, 0))
	elif value == 5:
		return(Vector3(PI, -PI/2, -PI/2))
	elif value == 6:
		return(Vector3(-PI/2, PI, 0))
	elif value == 7:
		return(Vector3(0, -PI/2, -PI/2))
	elif value == 8:
		return(Vector3(-PI, 0, 0))
	elif value == 9:
		return(Vector3(PI, 0, -PI/2))
	elif value == 10:
		return(Vector3(0, PI, 0))
	elif value == 11:
		return(Vector3(0, PI, -PI/2))
	elif value == 12:
		return(Vector3(-PI/2, 0, 0))
	elif value == 13:
		return(Vector3(0, -PI/2, PI/2))
	elif value == 14:
		return(Vector3(PI/2, 0, PI))
	elif value == 15:
		return(Vector3(0, PI/2, -PI/2))
	elif value == 16:
		return(Vector3(0, PI/2, 0))
	elif value == 17:
		return(Vector3(-PI/2, PI/2, 0))
	elif value == 18:
		return(Vector3(PI, PI/2, 0))
	elif value == 19:
		return(Vector3(PI/2, PI/2, 0))
	elif value == 20:
		return(Vector3(PI, -PI/2, 0))
	elif value == 21:
		return(Vector3(-PI/2, -PI/2, 0))
	elif value == 22:
		return(Vector3(0, -PI/2, 0))
	elif value == 23:
		return(Vector3(PI/2, -PI/2, 0))
```

**Comment by Zylann** [comment]
Honestly this should be exposed, writing such a helper is cumbersome xD

**Comment by tetrapod00** [comment]
Looks like this got official helper functions in 4.0:
https://docs.godotengine.org/en/4.3/classes/class_gridmap.html#class-gridmap-method-get-cell-item-basis
https://docs.godotengine.org/en/4.3/classes/class_gridmap.html#class-gridmap-method-get-orthogonal-index-from-basis
https://docs.godotengine.org/en/4.3/classes/class_gridmap.html#class-gridmap-method-get-basis-with-orthogonal-index

In general I think we can consider this issue solved, since there are now official helper functions, and there is no longer any need to document this workaround.

Some of the new descriptions could use improvement, IMO this is a bit unhelpful:
> For further details, refer to the Godot source code.

But we shouldn't repurpose this old issue to track that.
