### ISSUE TITLE
SpriteFrames resource doesn't allow specifying an offset for a frame

### ISSUE THREAD

**Issue by pasquinelli** [godotengine/godot#27328]
**Godot version:**

3.0.6

**Issue description:**

It would be helpful to be able to set an origin point for any frame in an SpriteFrames resource so that the animation could drive motion. Currently you have to add padding to each frame. AnimatedSprite has an offset that can be used, but that's constant across not only all frames but all animations.

**Comment by LeonardMeagher2** [comment]
Shouldn't complex animation like that be done with an animation player? From what I understand AnimatedSprite is meant for really quick and simple animation requirements.

**Comment by pasquinelli** [comment]
Is it? My understanding is AnimatedSprite is for traditional cel animation and AnimationPlayer is for keyframe animation. I know you *can* do cel animation as a keyframe animation but it looks like a pain frankly.

**Comment by QatariGameDev** [comment]
This an essential feature, It will save a lot of tedious works fixing the animation sprites, shouldn't be too complex it add, It’s only an extra parameter for each animation 👍

**Comment by Bropocalypse** [comment]
Yes, this is a feature that would be extremely helpful, to the point that it's disappoint that it's not already a part of it. As-is, you're almost better off using a sprite atlas, and even that in and of itself has its problems.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
