### ISSUE TITLE
Allow calling yourself via rpc

### ISSUE THREAD

**Issue by Dragoncraft89** [godotengine/godot#27332]
**Godot version:**
Godot 3.1

**OS/device including version:**
Debian GNU/Linux 9

**Issue description:**
`get_tree().get_rpc_sender_id()` returns 0, if the rpc was issued by the local peer. #19026 says this is due to the fact that it's illegal to call yourself via rpc (although I don't get an error in the debugger about that).

Therefore if you had code like this:
```gdscript
func _ready():
    # setup game
    rpc_id(1, "_finish_loading")

master func _finish_loading():
    isready[get_tree().get_rpc_sender_id()] = true
```

You need to rewrite it like this:
```gdscript
func _ready():
    # setup game
    rpc_id(1, "_finish_loading", get_tree().get_network_unique_id())

master func _finish_loading(id):
    isready[id] = true
```
which is not a really good solution, because a malicious client could be sending fake ids to the server and therefore control the actions of other players.

Another possibility that works is:
```gdscript
func _ready():
    # setup game
    rpc_id(1, "_finish_loading")

master func _finish_loading():
    var id = get_tree().get_rpc_sender_id()
    if id == 0:
        id = get_tree().get_network_unique_id()
    isready[id] = true
```
But this is quite clunky and apparently not well defined in the engine and therefore may be subject to change

Edit: This will be fixed by #24951

**Comment by and3rson** [comment]
I second this. It's been a pain to write code that can be executed by either player (who hosts a game AND plays it) or headless matchmaking server (who just hosts a game.)

I believe Godot should allow local RPC calls (i. e. `rpc_id(1, 'foo')`) irregardless whether it is executed on network server or client.

One use case that we encountered was this:

```
func on_connected():
    # Send "enter game" request to server.
    rpc_id(1, 'request_enter_game', 'Username')

master func request_enter_game(username):
    prints(username, 'requested to enter the game.')
```

Now this code will work when executed on "headless" server (because all players will be clients) but will not work if one of the player hosts a game (loopback rpc will not get through for him.)

We handled this by writing custom wrapper for all the RPC similarly to how OP described (by sending peer ID with each request), but this is dirty, unsafe & not portable. There should be a better solution to this.

**Comment by Dragoncraft89** [comment]
One way to do this would be:
```gdscript
func on_connected():
    # Send "enter game" request to server.
    rpc_id(1, 'request_enter_game', 'Username')

mastersync func request_enter_game(username):
    prints(username, 'requested to enter the game.')
```

Which works, but the debugger gives an error that it was calling itself. (This is probably a bug)

**Comment by akien-mga** [comment]
CC @Faless
