### ISSUE TITLE
"Global" setting for animations

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#27340]
For some nodes you want their animation to be at the same point no matter when they were spawned in. (Coins. Tiles. etc.)

I propose we add a setting (much like autoplay) to animations to make them "Global" when played.

I consider it a semi "Retro" effect as in old games some animations were all updated at the same time to save on memory however it definitely looks good in a lot of circumstances.
I've seen a many instances where it would have made a game look far better. 
(Generally when you have a lot of the same object onscreen, if the animation timings are inconsistent it's distracting)

**Comment by Zylann** [comment]
For animating sprites, perhaps `AnimatedTexture` should be better suited for it, because it allows re-using it in a natural way in many instances or tilemaps.
In the current state of things I can hardly imagine `AnimationPlayer` doing this on its own, other than having a script or system playing them all at the same time (using groups maybe), which gives the desired effect, without the re-use gain.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
