### ISSUE TITLE
Add subtitle support

### ISSUE THREAD

**Issue by Gallaecio** [godotengine/godot#27350]
Some day I would like to see subtitle / closed caption support in Godot.

The way I picture it: you would be able to associate a subtitle resource (e.g. loaded from an .srt file) to an audio or video resource, and then associate a player to a label, so that when the player plays its audio or video resource, the text of the label is updated accordingly.

**Comment by MaciejGorczycaGD** [comment]
That would be amazing inclusive feature it AudioPlayer could have apart of .play() function had .display_subtitles() you could choose easily when to load those with appropriate audio files.

**Comment by Naryosha** [comment]
I'm not sure I understand correctly. It seems like there are two separate proposals here?
1. subtitle for video/cutscenes (more static, timing is already set): I think a plugin that imports .srt file into an Animation resource that contains timing and texts would suffice and flexible. You can link a label to it easily.
2. subtitle for spoken dialogues (more dynamic, subtitle appears when an audio is played): Object.set_meta seems like a good way to achieve this. By doing something like `audiostream.set_meta("subtitle", "Spoken message here")` and when audioplayer plays it, it searches for this 'subtitle' meta and display the text.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
