### ISSUE TITLE
BUG planes overlap in 3D viewer

### ISSUE THREAD

**Issue by kone9** [godotengine/godot#27354]
**Godot version:**
_Bugsquad edit_ : 3.1 stable

**OS/device including version:**
Windows 7 64 bits,geforce 9800gt,core2quad q8200

**Issue description:**
### English.
In the scene there is a material with alpha channel and another with reflective channels ...
It seems that there is a bug because they get in the way and they do not look good in 3D view.
I leave a video where I show that the move the view are still interposed and this difficulty the assembly of the scenes ..
### Español.
En la escena hay un material con canal alpha y otro con canales reflectivos...
Parece que hay un bug ya que se interponen y no se ven bien en la vista 3D.
Dejo un video donde muestro que la mover la vista se siguen interponiendo y esto dificultad el armado de las escenas..

**Steps to reproduce:**
Look at the project and you will see that when you move the view of the 3D viewer you see everything as weird.
you're going to have to look at alpha materials and water materials.
although no idea why that happens.
anything they ask me ..
### link video reproduction -------> https://youtu.be/0X21AFnhT0s <---------------------

![Captura](https://user-images.githubusercontent.com/12847027/54869048-0eb71200-4d72-11e9-85c9-4379e2a9bee8.PNG)

**Minimal reproduction project:**
https://github.com/kone9/BUG-planes-overlap-in-3D-viewer

I have uploaded the project to github because it weighs 150 mb aprox ... reporting this error took me 2 hours .. I hope they can fix it.

**Comment by clayjohn** [comment]
Hi, sorry no one has responded sooner. This is a known limitation of Godot's renderer (see the [known limitations doc](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting)). 

The reason this occurs is that transparent objects are sorted based on their origin. When you have two large transparent objects like this, you can get conflicts when the origins look like they should be sorted one way, but the location where the objects overlap should be sorted another way. 

In order to fix this, Godot provides a setting called ``render_priority``. ``render_priority`` allows you to modify the sorting to prioritize one material or another. In this case, you want to reduce the priority of the water so it always appears below the plants.

While it is frustrating to have to deal with this sort of limitation, it is not a bug. As the above linked doc says, order independent transparency techniques are still very slow and are not worth adding to the engine right now.
