### ISSUE TITLE
Slerp Vector3 direction and magnitude

### ISSUE THREAD

**Issue by marrameu** [godotengine/godot#27377]
**Godot version:**
 3.1

**Issue description:**
The Slerp function in Vector3 needs both vectors to be normalized, so only works like as a direction.
It would be great if the direction of the returned vector was interpolated by the angle and its magnitude between the magnitudes of vector a and vector b. (Rather as it works in unity: https://docs.unity3d.com/ScriptReference/Vector3.Slerp.html)

**Comment by Toshiwoz** [comment]
#30341 - this should be fix that.
AS a matter of fact this slerp is in the end just a rotation, so there's no need to normalize it.

**Comment by Soul3S8** [comment]
This does not solve the problem, what I'm looking for is more [like this](https://github.com/godotengine/godot/pull/18804#issuecomment-388569235). I thought it could also be "SLERP" (because that's how is called in Unity) but I see it would be a different function.

**Comment by Toshiwoz** [comment]
Magnitude, you're right, we need another function for that.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
