### ISSUE TITLE
Merge import dock and inspector

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#27378]
Godot 4.0?

After seeing several cases of confusion when it's about modifying imported resources (including https://github.com/godotengine/godot/issues/27357#issuecomment-475939849), I've been thinking it would be more useful to remove the import dock, and insert it as part of the inspector, in its own unfolded category, on top of the normal property grid.
This should be possible to do now, because the inspector can show a wider variety of controls than it could back in 3.0.

Moving this in the inspector would be more straightforward, i.e you double-click a resource, and you can modify its properties in the inspector dock, the place where anything with properties is edited (same in Unity). Having to remember it's in another special dock is not obvious from a user standpoint, even with a warning "changes might be lost!". The fact they would be shown on top of the read-only properties helps guiding the user where he uses to do such edits and reduces the number of clicks to get to the other dock.

This is not the same as moving the dock above the inspector, because it would always take space no matter what you edit. This change would make it contextual instead.

Thoughts?

![image](https://user-images.githubusercontent.com/1311555/54881726-c1f33a00-4e4a-11e9-8474-d99fac31dbbb.png)

**Comment by volzhs** [comment]
what about reimporting multiple files?

**Comment by mindinsomnia** [comment]
Another option: Any imported file in the FileSystem tab, add an option to the right click context menu called "Re-import", and present a dialog to change the import settings. Similar to when you select a node, go to Signals, and right click a signal name and choose "Connect to..", and how it brings up a new dialog that floats over the top of and blocks the UI.

There really isn't a need for the Import tab to hang around when you're not importing anything.

**Comment by Shadowblitz16** [comment]
I was actually thinking about this when I was going to bed last night.
I think this is a really good idea

**Comment by fire** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
