### ISSUE TITLE
Enable usage of normal maps with Polygon2D

### ISSUE THREAD

**Issue by toasteater** [godotengine/godot#27403]
**Godot version:** 3.1 stable

**OS/device including version:** Not related, GLES3 backend

**Issue description:** The new [2D skeleton](https://docs.godotengine.org/en/3.1/tutorials/animation/2d_skeletons.html) feature in 3.1 makes use of Polygon2Ds, as opposed to Sprites in the older "cutout skeleton" feature. However, one cannot currently assign normal maps to Polygon2Ds, making the feature less useful for projects making use of normal maps and 2D lighting.

It's not ideal to be unable to use latest animation features along with Godot's 2D lighting system.

**Steps to reproduce:** N/A

**Minimal reproduction project:** N/A

**Comment by azagaya** [comment]
Hi! i can give it a try if this is wanted, and if its suitable for a junior contributor, and if someone points me out where to start. I've been reading polygon2d.cpp, sprite (to see how it's done there) and canvas_item.cpp.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
