### ISSUE TITLE
Gridmap warning about deprecated 'theme' property, even in new project

### ISSUE THREAD

**Issue by JacobTheHeartless** [godotengine/godot#27405]
**Godot version:**
3.1 Stable

**OS/device including version:**
Ubuntu Linux. XFce

**Issue description:**
Warning  `GridMap.theme/get_theme() is deprecated and will be removed in a future version. Use GridMap.mesh_library/get_mesh_library() instead` shows up in Output tab. I'm not using it anywhere, must be inside engine. It actually does not have visible effect on game. It is rather case of annoying thing.

**Steps to reproduce:**
I have no idea. It sometimes shows, sometimes not. Seems random to me but I'm indeet using grid map to build level. There seems to be no other requestment to trigger warning than having active grid map.

**Comment by bojidar-bg** [comment]
Probably some of the levels you have are still using the old `GridMap.theme` inside the scene file, instead of the newer `GridMap.mesh_library`. Just resave those levels or replace the property name manually.
Something like `s/theme =/mesh_library =/` should work.

**Comment by Garrom** [comment]
> Probably some of the levels you have are still using the old `GridMap.theme` inside the scene file, instead of the newer `GridMap.mesh_library`. Just resave those levels or replace the property name manually.
> Something like `s/theme =/mesh_library =/` should work.

Nope, I started developing in 3.1 Stable. Plus, it pops up sometimes which means it pops only when it is called.As I mentioned, I'm not using it anywhere, it must be inside engine. Everything was made in 3.1 stable. I suspect it is leftover from older versions of editor.

**Comment by qarmin** [comment]
To show this warning only need to create and save empty gridmap 
![Zrzut ekranu z 2019-03-26 14-55-20](https://user-images.githubusercontent.com/41945903/55002834-905ba980-4fd7-11e9-8cf7-04eeb2e5d65d.png)

**Comment by KidRigger** [comment]
The problem is caused when the node saving code actually iterates over every property in the GridMap class to get values.
Since theme is still a part of the properties (although deprecated) the get_theme() method is called.
Solutions I can think of:
1. _ignore the warning_
2. Remove the `theme` from the properties - which kinda breaks compatibility (unsure)
3. Workaround to skip deprecated attributes from being called. (A lot of extra effort and modifications that don't feel worth it)
