### ISSUE TITLE
Take into consideration existing edges when drawing polygons in polygon2d editor

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#27400]
Right now in order to draw a polygon, you have to close a shape by clicking on all the vertices that the polygon will use. This requires a lot of repetitive clicking, even on vertices that already have an edge connection between them - from another polygon.

In blender and most other 3d software, as well as dragonbones, spine and the other 2d skeleton animation this is not required - as the software takes into consideration already existing edges and knows to create a polygon without all that extra clicking - by just closing an area.

The request here is to add that to godot - so drawing polygons next to other polygons takes less clicks. It will imo increase workflow speed dramatically 

If you want to take this even further and make it faster to create polygons in the polygon2d editor- you can take some ideas from the existent retopology tools out there
![uploads%2F1533048635201-rf-2 0_polypen](https://user-images.githubusercontent.com/6495061/54920886-51a4f100-4efc-11e9-9543-f737abc95ffb.gif)
![uploads%2F1533048674155-rf-2 0_patches](https://user-images.githubusercontent.com/6495061/54920973-831dbc80-4efc-11e9-9e6a-c9df48ffdfd0.gif)

the current workflow is super slow compared to what is out there

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
