### ISSUE TITLE
Applied torque has no effect if CollisionShape2D starts disabled

### ISSUE THREAD

**Issue by sthiago** [godotengine/godot#27413]
**Godot version:** v3.1.stable.official
**OS/device including version:** Windows 10 Pro

**Issue description:**
This issue was found while working on the Space Rocks example of the Chris Bradfield book.
When the CollisionShape2D starts disabled (either in the inspector or in the _ready() method), applied_torque has no effect. Debugging shows that the torque is indeed applied but the transform matrix doesn't account for it. Forces are applied normally, though. I can thrust forward, but not rotate it.

If the CollisionShape2D starts enabled and then gets disabled (by a timer of 0.01s, for example), enabling it again works as expected (I can rotate it by applying a torque).

I didn't add this interaction in the minimal example, but if another RigidBody2D collides with the player, it is pushed back (force is applied) but no rotation is applied.

The original Space Rocks source, when imported into 3.1, suffers from this aswell. In 3.0.6 it doesn't, though.

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3004746/test.zip)

You can either disable the CollisionShape2D in the inspector or enable it and uncomment _ready() to test both cases.

**Comment by cbscribe** [comment]
I was just looking into this myself. Confirmed torque is applied but the body ignores it when collision shape is disabled.

**Comment by z0mbie42** [comment]
Hi, I encountered the same bug while reading the book, How did you manage to get it working ?

Even with adding timers I can't

**Comment by ulfben** [comment]
This issue is still present in Godot 4.3 Stable. 

[Here's my repo](https://github.com/ulfben/space-rocks/tree/5f0cf1f8c6f1dd10116c71ce3c71ad4d874652ba). Uncomment [line 56 in Player.gd](https://github.com/ulfben/space-rocks/blob/5f0cf1f8c6f1dd10116c71ce3c71ad4d874652ba/player.gd#L56) and you'll notice the player can no longer steer the ship when in the INVULNERABLE state. 

Or more specifically, for as long as the CollisionShape2D is disabled, the Player RidigBody2D has only thrust applied but no torque:

```
func _physics_process(delta: float) -> void:
	constant_force = thrust	
	constant_torque = rotation_dir * spin_power
```
