### ISSUE TITLE
Particle effects (3D) in a viewport blend to black.

### ISSUE THREAD

**Issue by PullTheStrings** [godotengine/godot#2743]
Particle effects (3D) in a viewport with transparent background blend to black. This may just be the way it works but it looks ugly. It would be better if the particles blended with the colour of the pixels behind them instead. 
Screenshot of a viewport with particles and another viewport behind it:

![viewportparticlebug](https://cloud.githubusercontent.com/assets/15687516/10996174/e550db96-8482-11e5-82a2-02cf39f9291b.jpg)

**Comment by romulox-x** [comment]
I'm not sure how you're scene's set up, but I managed to get a similar problem viewing a viewport's render target texture through a ViewportSprite.  The problem went away when I picked PMAlpha for the viewportsprite's blend mode.  Maybe this applies in your situation?

**Comment by PullTheStrings** [comment]
Thanks for the suggestion, but unfortunately no it does not alter the behavior. I think the problem lies in that the particles use an additive shader and are then placed in a ViewportSprite using the Mix shader. It looks like viewports use black as the transparent colour and that's why the particles blend to black. I'm just guessing here though.

**Comment by kubecz3k** [comment]
Helllo, Can you guys retest on 3.0? Thanks!

**Comment by GammaGames** [comment]
Still happening in 3.0.2, I combined the [3d in 2d](https://github.com/godotengine/godot-demo-projects/tree/master/viewport/3d_in_2d) demo with this (bokeh particle shader)[https://github.com/Bauxitedev/godot-particle-dof]

![image](https://user-images.githubusercontent.com/7832163/39227081-dfe4eb6e-4813-11e8-8582-9a8ba434ca41.png)

Here's an example project: [3d_in_2d.zip](https://github.com/godotengine/godot/files/1945499/3d_in_2d.zip)

**Comment by Calinou** [comment]
@GammaGames Can you (or anyone else) still reproduce this bug in Godot 3.2.1 or any later release (e.g. [3.2.2-beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4))?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

Also, does this occur with CPUParticles? What about the GLES2 renderer?

**Comment by GammaGames** [comment]
Using GLES2 with CPUParticles on 3.2.2rc2.official still has the problem:

![image](https://user-images.githubusercontent.com/7832163/85237783-99a81180-b3e6-11ea-8e85-f56668db7c8a.png)

And the above example still has the same problem:

![image](https://user-images.githubusercontent.com/7832163/85237804-ba706700-b3e6-11ea-9f52-82bbf19c3653.png)

Here's an updated project that includes the CPUParticles as well:
[3d_in_2d.zip](https://github.com/godotengine/godot/files/4810528/3d_in_2d.zip)

**Comment by clayjohn** [comment]
@GammaGames I ran your example project and realized that this isn't a bug! I will explain below.

You are currently rendering your particles by adding them to the background (additive blending in the shader). What this does is add your output pixel to the background pixel. Easy enough. 

To make soft particles, you are using a shader that fades the color out to black at the edges. This works great with additive blending because when the pixel is black it adds nothing to the scene!

This assumption breaks when rendering to a transparent viewport. When the background is transparent the black pixel _does_ add something to the scene, alpha!

Normally you don't notice that alpha is being added because the background alpha is always 1 and the shader clamps alpha to a max of 1, so 1+1 = 1. However, when your background is transparent, the alpha changes because 1+0 = 1.

In order to resolve this in your code I only had to add an alpha to the material that draws the particles.
```
ALPHA = max(ALBEDO.r, max(ALBEDO.g, ALBEDO.b));
```
This makes the alpha fade with the background alpha for a proper result. 

![Screenshot (1)](https://user-images.githubusercontent.com/16521339/85238719-cb1fdd80-b3e4-11ea-8837-8e4aaf2519b6.png)
