### ISSUE TITLE
Discussion thread for information regarding filesystem cache implementation for GSoC.

### ISSUE THREAD

**Issue by WarpspeedSCP** [godotengine/godot#27445]
The information given on the [GSoC](https://github.com/godotengine/godot-roadmap/blob/master/GSoC/GSoC-2019.md#a-threaded-and-paged-filesystem-cache) page seems really vague, and I don't completely understand the requirements. Could I have some clarity on the following points?

* How paging would be used here.
  * Is paging used to keep track of memory usage?
  * Is it to manage loading big files in parts? 
* Would it be a good idea to have a different way for Godot to store large assets (Eg, in parts) to implement this?
* What kinds of data would we want to cache?

Thank you in advance!

**Comment by punto-** [comment]
This is meant to replace the OS caching of files that already happens in a "normal" OS, for cases where the OS doesn't do it, or where it doesn't do it in a way that we like it, or where the OS is not aware that we need it or has no way to do it for us (for example when reading files from a network stream). In those cases, we would turn this on, and be able to control how file reads are cached. You could do things like say "I want file X to be ready in 1 seconds (when the current cutscene finishes)". Currently we have the FileAccessBuffered, which reads a chunk of the file in advance, but that's not good enough. A few details on your questions:

* Paging is a better solution than just reading a chunk ahead like the FileAccessBuffered does now. It's better for uncommon cases like when a file is opened and closed multiple times, or if someone reads from random places of a file, including jumping backwards. Also in cases when we know that the underlying hardware works better with reads with a certain alignment, we can do that better with pages.
* This would be used for all files, it's implemented at the FileAccess level, the game could decide if certain files would be cached in different ways using an API we would provide to control things like how long the file will be in cache, how aggressively to read ahead, etc

**Comment by WarpspeedSCP** [comment]
So by paging are we referring to handling the file as if it were composed of parts which we will page in and out of cache memory?

**Comment by fire** [comment]
Have you heard of the term magic streams? The base concept is that for the cache system to record all the assets for a set period of time and then have them packed in order. 

This is in cocos2d. 

http://sol.gfxile.net/#MAGICSTREAMSFORPHYSFS

For example the android app can preload a initial portion suitable for a few minutes of game play and when the player is playing download the rest.

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
