### ISSUE TITLE
Implement a 3D / 2D ruler

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27443]
**Godot version:**
3.1

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
Implement a ruler that shows the distance between 2 points (x, y,z for 3D) or (x, y for 2D).
It is often necessary to measure an object that has been scaled or even the collision distance between 2 or more objects.

**Comment by girng** [comment]
i think this can be done with the `tool` script. but i agree, would be nice to have it on a ruler

**Comment by LeonardMeagher2** [comment]
You could create a node that takes a list of Node paths, and draws geometry or lines to each one of their centers.
If `node is VisualInstance` you could `get_transformed_aabb()` and draw a wire framed cube.

Lots of options with a `tool` script, especially with `class_name` you could even use the nodes for debugging in game

For the Rect of a 2d Node it seems a bit more complicated, it'd be nice if you could get the rect of any canvas item

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
