### ISSUE TITLE
Open Help in Browser

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#27455]
**Godot version:**
3.1

**OS/device including version:**
Windows 10

**Issue description:**
I would like ability to open help in a browsers. So far I can only search help locally in Godot or check online docs but can't do both. 

For instance I am interested what has_method() function does. I have found it via search help in Godot engine. I would like to be able to click and be taken directly to the page online to read more about it. At the moment I have to click Online Docs and then again search for what I am interested in.

**Comment by Chaosus** [comment]
The online and offline API docs are identical. The online docs are formed from offline docs via script. As I understood, you wish a some kind of button or checkbox to force open the online docs through editor ?

**Comment by KoBeWi** [comment]
> The online and offline API docs are identical.

But online docs look better and are more readable. On the other hand, searching docs inside Godot is easier. The proposal makes sense to me.

**Comment by groud** [comment]
> But online docs look better and are more readable

This is the real problem then, not the fact that the online doc should be accessible.

**Comment by Chaosus** [comment]
> But online docs look better and are more readable.

I agree that online docs looks better and have better formating - why not make offline the same ?

**Comment by KoBeWi** [comment]
So I just created related issues:
#27456
godotengine/godot-docs#2304

There's also this thing: #22552

All of it combined make using only one source of documentation much less viable. Personally I use combination of Google and _sometimes_ F4.

**Comment by MaciejGorczycaGD** [comment]
> > The online and offline API docs are identical.
> 
> But online docs look better and are more readable. On the other hand, searching docs inside Godot is easier. The proposal makes sense to me.

This is primary thing for me yes. It's much easier  to search in the godot editor for what I want and then it's much easier to read in browser so I first search in godot editor when I know what I am looking for I search for exact same  thing in online docs.

**Comment by Calinou** [comment]
This should be relatively easy to implement: for instance, AnimatedSprite's documentation is located at:

```
https://docs.godotengine.org/en/3.1/classes/class_animatedsprite.html
```

Therefore, one can retreive the URL of any class page with:

```
https://docs.godotengine.org/en/<version>/classes/class_<lowercased class name>.html
```

The `<version>` field should use the current engine version into account (`3.1` for a stable release, `latest` for any development/alpha/beta release).

**Comment by girng** [comment]
> I would like ability to open help in a browsers. So far I can only search help locally in Godot or check online docs but can't do both.

well, you can't do both because the docs in the editor are client side
i don't think this is an issue. if a dev really wants to look at the "online version" of the docs, they'll just search google an it's within the first 1-3 results. littering the RTL doc space with even more tags and links  for something that rarely happens is not worth it. JMO

**Comment by clayjohn** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
