### ISSUE TITLE
16-bit bone IDs are needed (3D)

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#27483]
Godot currently supports up to 255 bones (or less, can anybody clarify?)
This is not enough for more dense game characters which tend to use 300-400 bones these days. Can we increase the bone ID size so that Godot can be used for that kind of fidelity?
I know you can live with like 30 bones and be happy, but still...

**Comment by fire** [comment]
If you are able to import the model on the upcoming asset import pipeline, the system will split the mesh if it has too many bones.

**Comment by fire** [comment]
16-bit bones already exist for gles3. Not in gles2 though.

**Comment by slapin** [comment]
Where can I have a taste of upcoming pipeline?
Automatic mesh splitting is a good thing. Also can I actually know the bone
limit somehow?
Also what determines the bone count?

**Comment by slapin** [comment]
Also I'm interested in both GLES2 and GLES3, as I have low end targets too.

**Comment by asheraryam** [comment]
@slapin I'm guessing that's referring to this pull request.

https://github.com/godotengine/godot/pull/23837

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
