### ISSUE TITLE
Godot 3.1 is slow in the editor (not a bug).

### ISSUE THREAD

**Issue by sackondeeznuts1** [godotengine/godot#27513]
**Godot version:**
3.1-stable

**OS/device including version:**
$ neofetch
manjaro@manjaro 
--------------- 
OS: Manjaro Linux x86_64 
Host: Vostro 1500 
Kernel: 4.19.28-1-MANJARO 
Uptime: 9 mins 
Packages: 1169 (pacman) 
Shell: bash 5.0.0 
Resolution: 1680x1050 
DE: Xfce 
WM: Xfwm4 
WM Theme: Adapta-Maia 
Theme: Adapta-Eta-Maia [GTK2], Adwaita [GTK3] 
Icons: Papirus-Maia [GTK2], Adwaita [GTK3] 
Terminal: xfce4-terminal 
Terminal Font: Monospace 12 
CPU: Intel Core 2 Duo T8100 (2) @ 2.301GHz 
GPU: NVIDIA GeForce 8400M GS 
Memory: 1469MiB / 5999MiB 

**Issue description:**
Specifically on my laptop, Godot 3.1 runs two times slower than 2.1.5, and this slowness is quite noticeable. Is it possible to tweak the editor somehow so it'll run faster?

**Comment by homer666** [comment]
Have you tried setting the video driver from "GLES3" to "GLES2"? There's a dropdown at the top-right of the editor. Your machine seems really low-end so it could make a pretty big difference.

**Comment by sackondeeznuts1** [comment]
@homer666, it did improve the speed, but not that much.

**Comment by Calinou** [comment]
Your graphics card is pretty slow, there's not much that can be done about this.

However, there are two ways you can improve the situation:

- If working in 3D, click the **Perspective** button at the top-left corner of the viewport then enable **Half Resolution** to render the 3D viewport at a lower resolution.
- Disable V-Sync in the Project Settings to decrease the stuttering effect caused by low framerates (< 60 FPS on most monitors), as it'll also apply to the editor. If you do so, make sure your compositor or graphics driver does not force V-Sync; otherwise, it won't have any effect.

**Comment by sackondeeznuts1** [comment]
@Calinou, reducing the resolution in 3D did the trick, thanks.

**Comment by Calinou** [comment]
@sackondeeznuts1 Should this issue be considered resolved? By the way, were you testing the editor performance with 2D or 3D?

**Comment by Calinou** [comment]
I'll close this issue as there was no response from @sackondeeznuts1.
