### ISSUE TITLE
Parallax layers preview in 2D viewport (Editor)

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#2751]
It is useful to preview parallax layers in 2d viewport of editor, like this:
![tww_parallax_scrolling_sample_2](https://cloud.githubusercontent.com/assets/14325605/11016133/c75475b6-858c-11e5-8c06-72b15130dd5e.jpg)
![tww_parallax_scrolling_sample_1](https://cloud.githubusercontent.com/assets/14325605/11016134/c76ffb9c-858c-11e5-8c3c-82ae108f545c.jpg)
![parallax](https://cloud.githubusercontent.com/assets/14325605/11016160/b71ce272-858d-11e5-89bc-13f923a23c5c.png)
![isometric](https://cloud.githubusercontent.com/assets/14325605/11016559/df487c04-859a-11e5-9d4d-d6428ba05b85.gif)
![iso0](https://cloud.githubusercontent.com/assets/14325605/11016615/e79de4b4-859c-11e5-8962-e571c332cea5.gif)
![gif_unity](https://cloud.githubusercontent.com/assets/14325605/11016798/a55e0594-85a0-11e5-8375-74caa2580ca6.gif)

It makes editing current 3d in 2d feature easier, doesn't it? In extension can be used for isometric scenes preview in editor. 
I tried to show the concepts in above images. My intended purpose isn't a fake(like Ubiart framework) 2d game in 3d viewport. but here is some videos:
https://www.youtube.com/watch?v=uWF9NjsTWtc
https://www.youtube.com/watch?v=y-chi097uV4
https://www.youtube.com/watch?v=XoLpPw864eA

How much works (code) it takes?

**Comment by timoschwarzer** [comment]
As a start, it would be useful if the parallax layers would move with the viewport while editing.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
