### ISSUE TITLE
Add random rotation to grid map tiles.

### ISSUE THREAD

**Issue by RepairUnit3k6** [godotengine/godot#27533]
**Godot version:**
3.1 Stable - Official build

**OS/device including version:**
Ubuntu 18.04 , XFce, Notebook Lenovo B 50-80

**Feature requests:**
I'm using grid maps to build levels. However, if you have small tiles and big landscape you'll see pattern of repeating tiles, which is not really pretty. It would be nice to have "random rotation X" , "random rotation Y" and "random rotation Z" tick boxes in grid map menu. After placing tile it will be rotated by random amount along allowed axes. This would add some randomness into level and make it look less pattern-ish.

Games with big levels are suffering most from this effect. Also sandbox games with worlds made of blocks are suffering from this effect.

**Comment by Calinou** [comment]
Wouldn't this introduce visible seams between tiles?

**Comment by Garrom** [comment]
> Wouldn't this introduce visible seams between tiles (which would be difficult to fix in all cases)?

I don't think so. I already can do this by pressing A,S and D but doing so manually takes a while and does not seems that random. All methods should be already here (placing tiles, rotating tiles) this just automatize and randomize the process.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
