### ISSUE TITLE
Export to Android fails with INSTALL_PARSE_FAILED_NO_CERTIFICATES if debug keystore unspecified

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#27574]
**Godot version:** 3.1

**OS/device including version:** Windows 8

**Issue description:** Running on Android fails. It should succeed (valid APK)

This is similar to #18222. When I run/export on Android, nothing happens. Exporting the APK file and then installing it via ADB shows this error: `Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1971499572.tmp/base.apk: Attempt
to get length of null array]`

The root cause?  I didn't specify a debug key, or I didn't specify the correct user name and password. Specifying those, fixes the problem.

My ask: make the failure reason more clear to the user. (Especially for users without Android experience, it would be best to see the error in a Godot pop-up of some sort.)

**Comment by nightblade9** [comment]
Updated to be a UX "improvement" request now that I figured out the problem.

**Comment by LGLTeam** [comment]
I'm getting the same error when running my app though adb. How come?

**Comment by volzhs** [comment]
@akien-mga I think this is fixed by e3e5a1bb6e
![Screenshot_20201012_223412](https://user-images.githubusercontent.com/8281454/95752574-2b5fc580-0cdb-11eb-8559-1d3915a96b18.png)

**Comment by akien-mga** [comment]
@volzhs I wonder as this commit was included in `3.1.stable` against which this issue was opened, so it seems it's not sufficient.

OP says:

>  I didn't specify a debug key, or I didn't specify the correct user name and password. Specifying those, fixes the problem.

I think not specifying the debug key might indeed be prevented by e3e5a1bb6e3ae3d667eb622003d4c7d0cc713cd0, but maybe it's still possible to export with a debug key and wrong username/password that would trigger this error.

**Comment by Patchcoat** [comment]
I've verified this bug occurs with a specified debug key and the wrong username/password.
![image](https://github.com/godotengine/godot/assets/5828713/753572f4-7613-456a-ba42-df4a22d884fa)

**Comment by Patchcoat** [comment]
I have a fix using keytool and it works.
![image](https://github.com/godotengine/godot/assets/5828713/888ba7b4-a8fc-4595-8448-f58a2f0d6197)
I'm not ready to submit a pull request due to performance concerns. It is quite slow and causing an unusable amount of UI lag. I'm going to try to optimize it, largely by moving keytool into a background task, and then it should be ready.

**Comment by frankhuurman** [comment]
> I have a fix using keytool and it works. ![image](https://user-images.githubusercontent.com/5828713/271865567-888ba7b4-a8fc-4595-8448-f58a2f0d6197.png) I'm not ready to submit a pull request due to performance concerns. It is quite slow and causing an unusable amount of UI lag. I'm going to try to optimize it, largely by moving keytool into a background task, and then it should be ready.

This would be a very nice improvement! thanks for your work on it :)

**Comment by Patchcoat** [comment]
>This would be a very nice improvement! thanks for your work on it :)
Thanks. Regrettably it didn't pan out to a real-time check like shown in the screen shot because I couldn't figure out a good way to optimize it. I moved it to a pre-export check that will stop the export early if the password/username isn't correct and give you an error message telling you what's wrong.

**Comment by nightblade9** [comment]
Nice, thanks for fixing this! (Three years in the making :D )
