### ISSUE TITLE
Code editor improvement: refactoring tools

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#27606]
The following items are used quite regularly by me in other IDEs, I do miss them when using GDScript:

- extract method / field / variable / constant
- inline method / field / variable / constant
- rename method / field / variable / constant / class

others that may be useful as well but not critical:
- migrate type
- override method (opens popup with available methods to override)

**Comment by Zylann** [comment]
> inline method / field / variable / constant

Can you explain what you mean by this?

> rename method / field / variable / class

As you can imagine, GDScript at its core is dynamically typed, so it's hard to get this one right. Recent typing can help make it work on safe sections of code, but it doesn't rule out all cases like statically typed languages do.

**Comment by smedelyan** [comment]
> > inline method / field / variable / constant
>
> Can you explain what you mean by this?

Much better - I can give an example :)
https://www.jetbrains.com/help/idea/inline-method.html
Long story short, it should read as "replace method calls with method body and remove the method". Same for vars / constants

> As you can imagine, GDScript at its core is dynamically typed

I'm not using Python but I used to think that it is dynamically typed as well. And that does not prevent guys from implementing such sort of refactoring. Here's a link to PyCharm docs.
https://www.jetbrains.com/help/pycharm/rename-refactorings.html
I will be fine if this will work for at least typed GDScript

**Comment by Paulb23** [comment]
Somewhat related #23225

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(btw there's already a related proposal https://github.com/godotengine/godot-proposals/issues/899)
