### ISSUE TITLE
These most annoying simple things need to be fixed immediately.

### ISSUE THREAD

**Issue by UTilitieeees** [godotengine/godot#27619]
These most annoying simple things need to be fixed immediately (MacOS High Sierra, Godot 3.1):

1. Remember last path 
Everytime I've seen a File explorer in Godot, I'm starting from nowhere. Godot has only one path, or is not remember the past path.

Every File-Explorer "must" have his own remembered path! It's pure horror to load assets and export to Android.

2. Export to Android
2D Export is working, but any 3D Export...  is working but ends in a Android Device Crash. Every Time. I've switched a lot... OpenGL2, OpenGL3, different Android Devices ... Crash, every time.

3. Complicated Tree + Script Nodes
It's not logical. There is no red line that I could follow. I've seen a lot of YouTube videos, Examples, Code... it's working, but it's not logical. It's not complete rubbish, but it's not logical. It's confusing. Nodes, Instances, Links, Scripts, ...  too much of everything.

4. I have to close Godot to get the Project list? Are you kidding me?

5. Scene, Project, Debug... 
Scene in front of Project? This should be right:  Project, Scene, Debug

6. Calling Scenes / HUDs from script $HUD.
I've tested it, and it fails every time. It's annoying. I can not call or change the Score.

etc. etc.  ... a lot o work.  I linke the idea, and so far a good step, but it's not working in production life.

**Comment by mysticfall** [comment]
First of all, issue tracker is a place to track individual issues, literally. So it's not helpful for anyone if you list up everything you don't like about the project here. There are better places for such things on internet, if you must.

As to individual issues:

1. There's already a feature request for it. You can subscribe to it if you like.
2. Not sure if there is an exsiting issue for this since I haven't work on a mobile project. But try to search existing issues first and report it as a separate issue, if you don't find one.
3. Sorry, it's your problem not Godot's. I'm not trying to be fanboyish, but it's generally acknowledged to be one of the greatest features of the project by many people, so I think the chances are that you just need a bit more time to get accustomed to it.
4. I agree it's a bit cumbersome. Maybe you can open another feature request?
5. I think it could very well be just your personal preferences rather than something must be that way. If you believe otherwise, open a separate feature request and state your reasoning there. You won't persuade anyone by simply saying "this must be changed".
6. Again, this is not a tech support site, so such a problem should be discussed in some other places like our Discord server, or QA forum. And chances are high that it's just your mistake rather than any inherent problem of the engine. At any rate, nobody can help you with such kind of a problem without actually seeing your code.

**Comment by KoBeWi** [comment]
> I have to close Godot to get the Project list? Are you kidding me?

> I agree it's a bit cumbersome. Maybe you can open another feature request?

Really?
Project -> Quit to Project List

**Comment by mysticfall** [comment]
@KoBeWi I understood he/she meant it'd be better if we allow opening the project dialog _without_ having to close the current project first.

For example, in a word processor, you can always choose "Open" menu and just close the dialog without having to save and close the document you've been editing before.

**Comment by NathanWarden** [comment]
To bounce off of what @mysticfall said, @UTilitieeees is on macOS where there's no straight forward way to open two projects at once since you can only have each application open once. @UTilitieeees Is that the issue you're having for your point 4?

**Comment by rogeriodec** [comment]
@UTilitieeees you have joined GitHub TODAY and its ONLY post was the one you are only criticizing.
Godot is an open project with more than 800 active collaborators.
Feel free to join the team and help Godot to become better.

**Comment by DegradedMind** [comment]
@rogeriodec, well, isn't this section for discussing issues? I can agree with points 1, 4 and 5, because I myself noticed these while using Godot. Indeed, he should've checked the nature of his issues and not oblige others to solve problems that arose purely because of his preferences like criticizing a design feature peculiar to Godot like the Node system,

**Comment by Calinou** [comment]
Please open one issue per bug report/feature request after searching for possible duplicates. See the [contribution guidelines](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#reporting-bugs-or-proposing-features) for details.
