### ISSUE TITLE
Seperate node dock into dedicated signal and group docks

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27629]
**Godot version:**

3.1

This reduces the number of clicks required to edit either by one when the previous tab was in focus.

**Comment by TicklesTheBrain** [comment]
On the upside it would allow renaming the "node" dock to something more descriptive and useful. On the down side it would add another unclosable dock to an interface that can already have 7 different types of sub-windows (including things like debugger) at the same time. I think this is a good idea, but the editor layout has to become much more customizable (like the ability to open or close certain docks altogether, more ways to stack things on top of each other, expand and contract. etc.) before it can support additional docks.

**Comment by TheDuriel** [comment]
@TicklesTheBrain Docks already occupy Tabs in one of the 8 slots. Separating the Node dock in to two would not take any additional space, they'd just be Tabs of their Container.

**Comment by TicklesTheBrain** [comment]
Sure, but an additional tab label is still clutter in an already cluttered workspace.

**Comment by IAmActuallyCthulhu** [comment]
@TicklesTheBrain What purpose does it serve to hide information within a sub-menu? An additional dock would not clutter the editor, since both of them still could be stacked in a slot.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by chexmo** [comment]
if you happen to read this thread.... I've made a new one in https://github.com/godotengine/godot-proposals/discussions/9052
