### ISSUE TITLE
[Feature Request] Sprite Texture Progress

### ISSUE THREAD

**Issue by Indie-Siggi** [godotengine/godot#27643]
###

**Godot version:**

**OS/device including version:**

**Issue description:**

Node2D Sprite-Texture-Progress with the same features as Control Node Texture-Progress.

This way progress bars can be used within game view and not only in UI view.
Using Texture-Progress as Sprite replacement disturbs mouse-selection input events

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zylann** [comment]
TextureProgress can be used standalone, it doesn't *have* to be used in a GUI. You can drop one anywhere you want. If you don't want to disturb the mouse, set its mouse mode to `Ignore`.

**Comment by Indie-Siggi** [comment]
Thanks for the fast reply, it works better with mouse ignore, but it is still more like a hack.
TextureProgess also interferes with the collision system, KinematicCollision2D reacts to it.

In the end Control Nodes doesn't integrate well with Node2D components (position systems are also different), so I still think an explicit Node2D SpriteTextureProgress would be useful.

**Comment by Zylann** [comment]
> Thanks for the fast reply, it works better with mouse ignore, but it is still more like a hack.

I wouldn't call setting a property for the purpose it serves as a hack.

> TextureProgess also interferes with the collision system, KinematicCollision2D reacts to it.

I don't understand how TextureProgress interfers here, or what the problem even is Oo
TextureProgress is not supposed to interfere at all if you set it to ignore events.

> In the end Control Nodes doesn't integrate well with Node2D components (position systems are also different), so I still think an explicit Node2D SpriteTextureProgress would be useful.

The difference are the handling of size. A progress sprite has a position and size and is related to a GUI use case, so it makes sense to be a `Control`. IMO there isn't much a point in almost duplicating that node if there isn't a strong reason to do so (to prevent bloat we would have to support a long time after). For example, `Sprite` and `TextureRect` look similar, but `TextureRect` exists because it's not possible (or hard) to setup a `Control` node anchoring to its parent, for which the entire background is a texture.
Which use case does `TextureProgress` make it hard for you? (except for the one you can solve by just setting a property).

**Comment by Indie-Siggi** [comment]
I've made a separate test scene to illustrate the collision problem, but with that scene there is no problem, so my game has a strange bug I must identify and it has nothing to do with `TextureProgress`.

So there is no strong reason for a `SpriteTextureProgress` Node, it would just be nice.

Regarding duplicating, `Sprite` could also be replaced by `TextureRect` ;)

I will close this issue and if there are more people that would like such a node, make your call.
