### ISSUE TITLE
Fullscreen game not focused at start

### ISSUE THREAD

**Issue by andersmmg** [godotengine/godot#27653]
**Godot version:**
3.1.stable.official

**OS/device including version:**
Ubuntu 18.10

**Issue description:**
When launching a game fullscreen from the editor, it shows up fine, but it isn't in focus. I can click anywhere to bring it in focus. In 3D games this is annoying because you can't move around until you click.

**Steps to reproduce:**
Create a project using keyboard input, set to launch in full screen. Input is not accepted until the window is clicked.

**Minimal reproduction project:**
[FullscreenTest.zip](https://github.com/godotengine/godot/files/3040320/FullscreenTest.zip)

**Comment by guilhermefelipecgs** [comment]
This bug is from gnome, not godot, I had this problem too and it affected all the programs.

Gnome was fixed 3 days ago.: https://gitlab.gnome.org/GNOME/mutter/issues/505
Need to wait for Ubuntu to update.

For me it's already fixed, Tested with 5.0.5-arch1-1-ARCH, 40acc3ecdc4ca63040fec3ea30eead21523bade6
