### ISSUE TITLE
OS.window_per_pixel_transparency_enabled strange behaviour

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#27662]
When running OS.window_per_pixel_transparency_enabled  gets changed it causes some strange behaviour, I discovered this while making a state machine, when running the method the rest of the code was executed out of order, instead of executing when it should. This means that if I move the method on top of label label might not be set when the next _process call comes in, causing it to be null.

```
		main_ui.pregame_ui.hide()
		main_ui.ingame_ui.show()
		countdown_time = GameManager.currentGameTimer
		._enter()
		label = main_ui.ingame_timer
		OS.set_window_always_on_top(true)
```

**Comment by Calinou** [comment]
@EIREXE Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
