### ISSUE TITLE
Add wrappers for built-in types to make the most out of optional typing

### ISSUE THREAD

**Issue by CodeDarigan** [godotengine/godot#27675]
3.1

Create a system to allow users to essentially sub-type simple built-in types. 

e.g
`type id = int`

int parameters allow you to pass in a id but id parameters must take an id.

Right now we can do something quite like this by just wrapping the value in a class but this seems unnecessary in a certain situations. 

e.g

```
func record_score(player_id: int, score: int):
```
becomes
```
func record_score(player: id, score: int):
```

There wasn't any reason to do this in 3.0 because optional typing didn't exist but in 3.1 this could lead to catching a number of what would be syntactically correct but logically incorrect code. In case one it would be possible to place score and player_id in the wrong positions whereas in case two it requires the player id to be an id.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
