### ISSUE TITLE
Implement error for remove_child

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#27701]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**

If I try to remove a node using `remove_child` and this node actually doesn't exist, Godot doesn't inform, and the script goes on as nothing happened. 

**Steps to reproduce:**
Try to use `remove_child` with an invalid node tree.

**Comment by akien-mga** [comment]
I get an error:
```
ERROR: remove_child: Parameter ' p_child ' is null.
   At: scene/main/node.cpp:1229.
```
with this code:
```
	var node = NodePath("doesn't exist")
	remove_child($node)
```

Can you be more explicit about your use case?

**Comment by rogeriodec** [comment]
[remove_child.zip](https://github.com/godotengine/godot/files/3053799/remove_child.zip)

(Sample above).

In fact, the error is shown in the debugger, but Godot doesn't stop running to inform the error as should be.

![image](https://user-images.githubusercontent.com/11199752/55716833-5672a600-59ce-11e9-8b40-5c767a771327.png)


![image](https://user-images.githubusercontent.com/11199752/55716844-5bcff080-59ce-11e9-83eb-961ce01552ed.png)

**Comment by akien-mga** [comment]
Godot is designed not to stop execution of your game for errors which are not critical. This is the case here, there's nothing for `remove_child` to work on, but that doesn't prevent your game from running further, so it should continue.
You wouldn't want you published game to crash for your customers due to a non-critical error you made.

As a developer, you should pay attention to the Errors tab and fix those when they pop up.

**Comment by rogeriodec** [comment]
You're right.
Now I'll pay more attention to the Errors tab.
Thanks.
