### ISSUE TITLE
Expose Custom URL Schema In Mobile Apps

### ISSUE THREAD

**Issue by vini-guerrero** [godotengine/godot#27777]
**Godot version**
3.1 Stable

**OS/device including version:**
iOS / Android ( Any )

**Issue description:**
Currently there’s no way to open an .apk or .ipa using custom url schema as described here ( https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app ) 
Fetching URL Params Into Godot

E.g. Facebook Login
By using Accounts.framework, the ios web browser could redirect to `fb<YOUR_APP>://facebook/login` leading to many integrations possibilities.

**Steps to reproduce:**
Create a custom URL Schema and Launch Godot Game
https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

**Minimal reproduction project:**
Any project should work as long as there’s a way to fetch that data from the schema

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
