### ISSUE TITLE
Connect signals to editable children in the editor

### ISSUE THREAD

**Issue by takaturre** [godotengine/godot#27773]
**Godot version: 3.1**

**Feature request:**
   The request is to be able to connect signals to "Editable children" -nodes in the **editor**. Currently any instanced scenes will only display their (greyed) root node, but no editable children - although the "Editable children" option is enabled for the node. [Pic 1: Available signal targets](https://imgur.com/aXz3xq1) [Pic 2: Actual scene tree](https://imgur.com/s5YDafO)
 Note that **NodePath** export variable does support referencing nodes inside an instanced scene with "Editable children" enabled - but signals do not.

**Background / why:**
  I'm trying to build a generalized system for creating NPC's etc. I'm using some "template scenes" as the basis for this, these templates include some scripts and some basic node structure (as if containers), into which further nodes can be inserted in the editor to create specific behaviours etc. ([Inspired by this video.](https://www.youtube.com/watch?v=Ty4wZL7pDME&t))
  In this system, it would be very convenient to connect signals (in the editor) from a node within an instanced scene to other nodes within another instanced scene (both part of the same edited scene). However, when trying to connect a signal in the editor, the available options do not include any "editable children" -nodes - only the nodes who are owned by the main edited scene.

**Criqitue:**
 I'm also thinking that maybe I'm using Godot in an inappropriate way. Because, eg. when the original scene is modified, there is often the danger of all the Editable children (of instances of that scene) and their properties being erased all throughout the project without any kind of undo / fallback.
   .. On the other hand, having a "pre-established" structure with unremovable nodes is otherwise very convenient and also visually clarifies the scene tree nicely (--> grey text implies pre-established structure).

**Workarounds:**
1. I think you can make the connections via script (at least when the game is run).
2. For now, I've in some cases connected the signal to a local node, which in turn has a sort of mini-API that will in turn make the call to the desired action node. (However, the action node might be right next to the signal sender - would be nice to just connect to it straight away, and define the params in the signal.)
3. You can also attach an additional (specific) script to the node and connect it to itself and do whatever with the signal. However, the only purpose of each of these ad-hoc scripts would be to workaround this limitation of the editor, which doesn't sound good. Also, the logic of "what happens" would be "hidden" inside the script - whereas otherwise everything is clear by simply looking at the scene tree and checking where some specific signals are connected to, eg. this trigger triggers this action, etc.)
4. You could also work around this by making a general script with a NodePath export variable (which does support going into Editable children), and attach it to the signal sender node. Then instead of using signals, the script would call the node at the NodePath. .. To define custom params, would use an export array (instead of defining the params in the signal)... Maybe this is the best workaround for now.

**Comment by jaggygames** [comment]
Ah this is exactly what I was looking for.

In my case, I want to connect the `picked_up` signal from the Stick item to a Quest which is a child of the QuestLog but I can't reach the Quest.

I feel it would be intuitive to be able to connect a signal to anything you can see in the scene tree.

![questlog_signal](https://user-images.githubusercontent.com/3285214/65683300-d52ece80-e054-11e9-8e38-97ec4c05767f.PNG)

![questlog_quest](https://user-images.githubusercontent.com/3285214/65683348-f1327000-e054-11e9-93c8-64511821d265.PNG)

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
