### ISSUE TITLE
func _process(_delta) should be default preset instead of func _process(delta)

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#27787]
**Godot version:**
3.1 stable

**Issue description:**
func _process(delta) results in a warning, func _process() is not possible
Hence func _process(_delta) should be the default preset.

When a new user adds a default script to a node the first time, they should not get a warning.

**Comment by isaacremnant** [comment]
I disagree, variables shouldn't be "ignored" by default and I think it's the user's job to choose put the underscore when desired.

**Comment by akien-mga** [comment]
I disagree too.

The proper solution IMO is what I proposed in https://github.com/godotengine/godot/issues/27576#issuecomment-478745395 i.e. split this warning into two warnings:
- One for user-defined methods (ON by default), so `my_method(arg_i_wont_use)` will raise a warning
- One for engine callbacks (OFF by default), so `_process(delta)` won't raise a warning unless you enabled this warning yourself

**Comment by golddotasksquestions** [comment]
> The proper solution IMO is what I proposed in #27576 (comment) i.e. split this warning into two warnings:
> 
>     One for user-defined methods (ON by default), so my_method(arg_i_wont_use) will raise a warning
>     One for engine callbacks (OFF by default), so _process(delta) won't raise a warning unless you enabled this warning yourself

Yes, this sounds like a much better solution!

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
