### ISSUE TITLE
Export float EASE inspector graph is very squashed.

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#27799]
**Godot version:**

f52c294

**OS/device including version:**

Win10 64-bit

**Issue description:**

The editing graph for this export var is difficult to read because it is very skewed.  It isn't clear if there is any way to expand it vertically to make it more square.

![image](https://user-images.githubusercontent.com/13004169/55703652-ddca1480-59e2-11e9-86b8-63d1eb1da559.png)

**Steps to reproduce:**
Using an export var in GDScript.
`export (float, EASE) var easing = 1.0`

**Comment by Calinou** [comment]
We could increase the height of the easing previews, but that would make them take more space in the inspector. Making the height adjustable sounds difficult, especially since you can already drag the easing slider area to change its value.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
