### ISSUE TITLE
3D Workflow Issues

### ISSUE THREAD

**Issue by jeremybullock** [godotengine/godot#27816]
There has been a ton of great work on the 3D side of Godot.  There are still a few things that really limit the speed of the workflow.

- Accidentally selecting the collisionshape or mesh of a rigidbody or kinematic body instead of the parent.  I don't know what the solution would be though.  There might be instances where you would want to be able to select the child (perhaps the player is holding a weapon or item).  This is one of the areas where the node based structure seems to slow down workflow.  
- Inability to scale a parent of a collision shape, or scale a rigidbody.  Having to change the extends of a collision shape and scale the mesh separately is tedious.  Being able to scale one item and scale all of it's children is intuitive and user friendly.
- I would love to have an editor option to put the transform at the top of the inspector.  I reference it more than any other item in the inspector.  
- The ability to snap to vertices of other meshes.  This is a huge time saver when laying out a level.  Again, the node based system might make it a challenge since the mesh we are moving isn't always the parent node, and so we might snap the mesh to the correct location, but leave the parent and collision shape behind.

I love the coding experience in Godot and the UI system works great, but the workflow for 3D just feels like I am fighting against it rather that it working with me.

**Comment by fire** [comment]
Can you talk in detail about?:

> I would love to have an editor option to put the transform at the top of the inspector. I reference it more than any other item in the inspector.

**Comment by turtletooth** [comment]
I understand that the items in the inspector are organized by node inheritance, but having the transform so far down and collapsed by default makes getting to it cumbersome.  I realize that it isn't perfect for every workflow, but I would like to have an option to move (or pin?) the transform to the top.  This is especially important since selecting items in the viewport often selects a node you didn't intend to click.

On a side note, I still think the transform takes up more space than it needs to:
![image](https://user-images.githubusercontent.com/4576381/55742387-c7c15180-59ec-11e9-91e8-0126c5eea682.png)

**Comment by kaadmy** [comment]
Would it make sense to add another panel (similar to the node inspector) that only shows certain properties if they're available? Such as `translation`, `rotation_degrees`, `scale`, etc.

Something like this:
![godot_transform_panel](https://user-images.githubusercontent.com/14076345/55988433-b8ded700-5c58-11e9-8a41-c8e4431d2f3c.png)

**Comment by reduz** [comment]
In far most cases, you don't want to use transform as-is, and just use the gizmos and stuff, so having it all the time visible does not make much sense. If you _really_ want this, you could make an add-on very easily and put it in the asset library.

What I thought for a while that could be done is either a button or an option in the menu to "flip" inheritance, so base classes are first, in case you are editing a lot the base class and not the derived ones.

**Comment by turtletooth** [comment]
The problem with using the Gizmos in 3D is how easy it is to select the wrong node of an item.  I would prefer to use the gizmos, but it's not always user-friendly, and without snapping to meshes, it's sometimes hard to be as precise as you want.

**Comment by fire** [comment]
@turtletooth reduz mentioned doing the inheritance in reverse order is quite easy. Do you think trying a build of it with that would help?

Reduz also wants more evidence it is a problem.

**Comment by fire** [comment]
https://github.com/godotengine/godot/blob/a20235aeb02c0c9e5ce58c0236f88a19865d571c/editor/editor_inspector.cpp#L1456

Change:

"object->get_property_list(&plist, true);" to "object->get_property_list(&plist, false);"

Note the node scripts are in the wrong place, but it's a cool proof of concept.


![NoVOhGX](https://user-images.githubusercontent.com/32321/56011861-88219080-5c9e-11e9-889c-2f6c89714c6d.png)

**Comment by turtletooth** [comment]
@fire Thanks for looking into this.  I'm not sure this is actually any better since there is still so much noise around the transform, such as the Node settings and the Matrix in the transform.  

I think that all of this is just struggles with the Node based system of Godot compared to a component based system such as Unity.  In a component based system, you never have to worry about clicking the wrong node in the viewport - each object is all one thing.  Whereas in Godot, unless you sub-scene everything, it's very easy to get mixed up in the child nodes.  The same goes with the inspector - in a component based system, it's not bound by an inheritance based structure that adds noise and complexity to the interface.  

There is so much I love about Godot- I just think some user experience needs tweaking.  I get that it will never be a component based engine, but surely there are things that can be done to make the workflow smoother.

**Comment by Calinou** [comment]
> Whereas in Godot, unless you sub-scene everything, it's very easy to get mixed up in the child nodes.

This might be related to the inability to lock nodes (and make their children non-selectable) in 3D, like it's already possible in 2D.

**Comment by Zireael07** [comment]
@Calinou: Isn't there a PR for locking in 3D?

**Comment by Duroxxigar** [comment]
Just want to throw my hat in the ring on this, I'm for having the transform at the top too. One of my biggest issues with the inspector is the lack of consistency in placement of the classes. The order will always be the same, but the placement would be different. So, some nodes, the transform would be closer to the top (because the inheritance tree) and other times, it'll be way down, or sometimes in the middle. This creates a fairly jarring experience for me personally. Like @turtletooth, I use the Transform the most so far (I actually just stayed up all night from (9:30 PM to the current time of 8:05 AM. This is GMT - 5 by the way) exclusively working in the 3D section.

@fire & @reduz I for one would appreciate an option to at least invert it. As it appears that I interact with base classes more frequently.

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/81606852-a0278000-9388-11ea-905c-4c2158aa42e0.png)
@Duroxxigar can you contact me about making a proposal for inverting the properties?

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
