### ISSUE TITLE
Allow editable children to be on by default

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#27828]
**Godot version:**

3.1

**Issue description:**

There are some cases where I always want a scene to have its children editable, as they are meant to be changed once the scene is instanced; needing to enable this option one-by-one is tedious.  The following suggestions can help facilitate this:

1. Add an editor option to enable editable children by default; this results in one click to collapse editable children, rather than two to show them.
2. Add an option for `PackedScene`s when right-clicking them to set whether editable children should be on by default.
3. Add an option for nodes when right-clicking them to set whether they should always be editable for an instanced scene, regardless of whether editable children is enabled (e.g. `Always Editable`.)

**Comment by Jummit** [comment]
I'm definitely for 1. Make them not editable by default, but have a little button to easily enable the feature.

**Comment by somnivore** [comment]
@Jummit that's a repeat of suggestion 1, unless you mean keep the existing situation and don't offer any further configuration options, which wouldn't be of any benefit unless you just happen to hate having options.  As I said, it's tedious to enable this option on each instanced scene one-by-one, when you always want it to be enabled from the start; suggesting there should be no change would be like saying there should be no way to configure the import process and you should just set those flags every time you import something, even if you want certain flags to always be enabled.

**Comment by frojo** [comment]
And/or have a toggle in the Project Settings for "Scene instance children are editable by default."

**Comment by volzhs** [comment]
I guess it depends on development style.
I mostly do not use editable children.

**Comment by BraindeadBZH** [comment]
This feature is especially useful when developing a plugin which can modify the scene tree. At the moment it is not possible to save the changes made to a scene node instantiated and modified through a tool script, because you cannot toggle "Editable Children" through script.

**Comment by hilfazer** [comment]
5. Add a context menu option: **Instance Child Scene (Editable)**

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
