### ISSUE TITLE
Problems with reproducible (deterministic) random streams across Godot versions

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#27856]
**Godot version:**
3.1+

**OS/device including version:**
Windows 10 and others

**Issue description:**
According to `RandomNumberGenerator` documentation (Godot 3.2) (#27591):

> The underlying algorithm is an implementation detail. As a result, it should not be depended upon for reproducible random streams across Godot versions.

That's quite unfortunate... I've figured that my unit tests fail each time I rebuild Godot that use procedural generation given the same seed. I wonder whether it's a bad practice to rely on reproducible random streams anyway. I see no way to test procedural generation stuff otherwise, the only way would be to stick to the same Godot version. Having custom modules dependencies in a project leads to rebuilding Godot anyway.

Should probably just drop unit tests that rely on randomness, or make the `RandomNumberGenerator` implementation deterministic not only within a build, but across builds (~~and potentially platforms?~~ too big to ask).

If it also depends on the compiler itself, that would be fine as long as the same compiler is used, I don't see much issue here, just need to pass those tests across builds so I can still be adventurous with Godot master. 

The issue is rather inconvenience rather than a bug, so this can be interpreted as enhancement.

### Implementations

To note, I've been using some thirdparty library to generate noise, and always got the same reproducible noise across Godot builds. It seems like KISS algorithm is used there:

https://github.com/Xrayez/godot-anl/blob/0e6d442cc87e2438ec0cc3de903600def89cd5a0/thirdparty/anl/VM/random_gen.h#L208-L243

**Steps to reproduce:**
1. Build Godot from source.
2. Create random stream using `RandomNumberGenerator` (generate a random array of values)
3. Test that the steam is reproducible given the same seed.
4. Rebuild Godot at different version.
5. The random stream from previous build doesn't match with current build given the same seed.

@toasteater

**Comment by slapin** [comment]
If you rely on random stream determinism you better implement your own simple random number generator and use it instead of one embedded into engine. This way you will be independent of implementations. Godot tries to do that but noody really focused on the subject.

**Comment by Xrayez** [comment]
I don't necessarily need to rely on random stream determinism. The output of "procedural stuff" is intended to be saved externally or transmitted over the network directly (i.e. sending actual collision shapes vs seed alone). It's just that I want to be sure I don't break anything during development, and reproducible randomness across builds would suffice for that purpose.

**Comment by Xrayez** [comment]
Found a plugin that aims to solve this:
[SeededRandomSequence](https://github.com/DevinPentecost/godot-seeded-random-sequence/tree/master/lib/SeededRandomSequence)

The issue is still relevant though.

**Comment by toasteater** [comment]
Godot's RandomNumberGenerator has gone [through](https://github.com/godotengine/godot/pull/22314) [multiple](https://github.com/godotengine/godot/pull/25680) [changes](https://github.com/godotengine/godot/pull/27171) already since its inception. It's never guaranteed to have identical output across versions, it's just never properly documented.

If you want reproducibility, the best way to do it is with code that you control yourself: link to a third-party RNG implementation with a module or GDNative. That way you can rest sure that changes in Godot won't affect your procedural generation.

If you want a frozen PRNG in Godot, you will want to talk to the maintainers, instead of some mere mortal who can't and didn't decide it :)

**Comment by Xrayez** [comment]
@toasteater maintainers are always busy, so mere mortals have to breakthrough the challenges on their own :)

This just defeats the whole purpose of `RandomNumberGenerator` for me, but I always tend to have specific use cases anyway, so no wonder! I can live with that for now.

**Comment by slapin** [comment]
Well, your use case is not specific, but software changes,,,
I still suggest you write your own  small generator which will work
across versions. I have a few written in GDScript even.
Also you can revert changes in tree to keep the same bahavior. In
general at current state of affairs everyone is on their own and all
use cases are specific.

**Comment by Xrayez** [comment]
OK, just rebuilt Godot at recent version, the stream is reproducible and tests passes...

Coincidentally, every time I've rebuilt Godot it always introduced some changes to PCG implementation. 😄
 
Because of this, I just thought that *any* change to the engine leads to the issue. I just can replace my test samples if I see if any changes are made to PCG implementation *and* I see some tests fail because of this, then continue on with other stuff.

Closing, could be reopened for discussion I guess.

**Comment by ttencate** [comment]
I would vote for this to be reopened. Even if @Xrayez got their tests to pass, the documentation still contains this:

> **Note:** The underlying algorithm is an implementation detail. As a result, it should not be depended upon for reproducible random streams across Godot versions.

There should be a way to get a stream that _is_ reproducible across Godot versions. It's not always feasible to save the entire output of procedural generation algorithm, because the output might be very large or infinite (think Minecraft).

For example, allow the user to specify explicitly which PRNG algorithm to use, with a suitable default. The default can then be changed freely in a new Godot version, without breaking anyone who has been explicit about which PRNG they want.

**Comment by Calinou** [comment]
> I would vote for this to be reopened.

Feature proposals should be made on the https://github.com/godotengine/godot-proposals repository now.
