### ISSUE TITLE
Transparency doesn't work on Android using GLES2

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#27857]
**Godot version:**
Godot 3.1 stable

**OS/device including version:**
Android GO 8.1 and Android 5.1

**Issue description:**
Transparency doesn't work on Sprites3d on Android, not even whit a material override (In Godot works OK, only wen exported to a real device this happens)

**Steps to reproduce:**
- Set to GLES2
- Add a Sprite3D to the scene
- Add a texture with transparency
- Run on android

![Screenshot_20190408-180129](https://user-images.githubusercontent.com/27329423/55814004-0e4aa500-5aee-11e9-8a5e-eb1959082217.jpeg)

**Comment by LinuxUserGD** [comment]
Also textured meshes with transpareny enabled aren't transparent in GLES 2 (Android.)

**Comment by Janders1800** [comment]
So basically transparency is broken on Android using GLES2 then.

**Comment by LinuxUserGD** [comment]
> So basically transparency is broken on Android using GLES2 then.

Yes, here is another example:

![bug](https://user-images.githubusercontent.com/34406967/55830798-03097080-5b12-11e9-8204-43f13acc709c.png)

**Comment by Janders1800** [comment]
I've done some digging and it seems like the flag Transparent never applies to Android on GLES2.
Can someone change the tittle of the issue to something like "Transparency doesn't work on Android using GLES2"? Since it seems to describe better the issue.

**Comment by wombatstampede** [comment]
There are certain issues with transparency in GLES2. First of all: ETC compression does not support transparency (without workarounds). So the first step is to re-import your transparent textures with "Losless" compression. (You might try out "lossy" as well)

But "Video RAM" will compress to ETC in GLES2/Android and therefore have to transparency "by design".

But there's still an error that relates to shadows. Transparency will not be present in shadows. But you can use "alpha scissors" as workaround.
See also:
https://github.com/godotengine/godot/issues/26568

**Comment by LinuxUserGD** [comment]
@wombatstampede I don't have any shadow if I activate transparency.

**Comment by wombatstampede** [comment]
@LinuxUserGD, yes, but that also depends on the Depth Draw Mode. Shadows work with Alpha-Scissors and Opaque-Pre-Pass (and non-ETC texture). But Alpha-Scissors is also slightly broken on pre-pass. (Scissors Threshold is ignored/fixed for display but used for shadow...)

**Comment by Janders1800** [comment]
Nice thanks! This should be mentioned in the docs somewhere.
