### ISSUE TITLE
Unable to load Templates

### ISSUE THREAD

**Issue by DaNeubi** [godotengine/godot#27865]
**GoDot Version:**
Godot version: 3.0.6 and 3.1

**Issue description:**
If I start the Godot Engine and want to select a Template the console prints out this:

```
Condition ' !category_map.has(r["category_id"]) ' is true.
   At: editor/plugins/asset_library_editor_plugin.cpp:1203
```

![image](https://user-images.githubusercontent.com/6529346/55824361-fe3dc000-5b03-11e9-9c5e-6506a32b4df0.png)

**Steps to reproduce:**
Literally starting the Engine/Editor without having used it before

**Comment by Calinou** [comment]
@DaNeubi Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
