### ISSUE TITLE
Enums in --gdnative-generate-json-api output

### ISSUE THREAD

**Issue by nadako** [godotengine/godot#27877]
**Godot version:** 3.1

I've noticed that even though some getters return `enum.*` types, their setter counterpart always receive a simple `int`. For example: `Label.get/set_align`. It would be nice to have these aligned because it makes a lot of sense for type safety.

**Comment by nadako** [comment]
@karroffel mentioned on IRC that this might be a binding generation issue, since e.g. `set_align` apparently does take enum as a parameter.

**Comment by raniejade** [comment]
@karroffel I found the bug here: https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/api_generator.cpp#L369

It should be calling `get_type_name` defined in the same file (https://github.com/godotengine/godot/blob/master/modules/gdnative/nativescript/api_generator.cpp#L123) which has special logic with dealing with enums.
