### ISSUE TITLE
Scene editor display node names at node origin

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#27885]
Proposal: Add a view option to the scene editor (2D and 3D) that displays the names of nodes at their origin.

Pinging @fire 

![image](https://user-images.githubusercontent.com/44248915/55852840-d2035d00-5b5e-11e9-8ff5-5838039fe941.png)
Imagine if each tile had its name displayed within the bounding rect.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
