### ISSUE TITLE
GLES2 cull mode inverted (wheel)

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#27900]
**Godot version:**
master

**OS/device including version:**
Antergos (Arch Linux)

**Issue description:**
In GLES2 the wheel disappears if I set the cull mode to back. The wheels are rendered correctly when using GLES3. In the editor it looks correct with GLES2 and GLES3.

**Steps to reproduce:**
See minimal reproduction project.
![bug](https://user-images.githubusercontent.com/34406967/55893059-ce4ff480-5bb7-11e9-8dd4-1376ec8510a8.png)

**Minimal reproduction project:**
By @OBKF
https://github.com/godotengine/godot/files/3219931/gles2_vehicle_wheel_bug.zip

**Comment by OBKF** [comment]
Strange that this happens only on wheels. even for my project and @BastiaanOlij tutorial demo.
I think it has something to do with transformation matrix in the physics.

**Comment by SmartySmart702** [comment]
I have the exact same issue.
Godot 3.1 stable x64
Windows 10 x64

**Comment by clayjohn** [comment]
Can anyone here post steps to reproduce or an MRP? Without either one of those, no one is going to work on this bug. A video/packaged game is not an MRP. Here is a description of an MRP from stackoverflow https://stackoverflow.com/help/minimal-reproducible-example

**Comment by OBKF** [comment]
@clayjohn 
Here I made a small demo project, it's just importing things from Blender.
It looks fine in the editor but inverted in the game.
[gles2_vehicle_wheel_bug.zip](https://github.com/godotengine/godot/files/3219931/gles2_vehicle_wheel_bug.zip)

**Comment by LinuxUserGD** [comment]
@OBKF
Thanks, I updated the description

**Comment by clayjohn** [comment]
Okay, wow. Looking into this has exposed a whole mess in both the vehicle code and the rendering code. 

1. In Vehicle_wheel sets the scale to a negative value for some reason. This inverts the geometry. And causes some other weird stuff https://github.com/godotengine/godot/issues/26627
2. GLES3 forces the scale to be positive so the objects render normally (kind of, normals still have issues: https://github.com/godotengine/godot/issues/26710, https://github.com/godotengine/godot/issues/25696) 

To fix this particular issue, we either need to fix why wheels are using a negative scale. Or we need to make it so that negative scales are okay and will not screw up the geometry. 

What we really need to do is both. 

Regarding the negative scales @Timofffee can you take a look at that? Do wheels absolutely have to use negative scales?

**Comment by BastiaanOlij** [comment]
Nice one @clayjohn , a lot of the vehicle code was copied from an old version of bullet and altered to work with Godot, I'm guessing they did that to make something work without noticing the consequences :)

**Comment by OBKF** [comment]
The vehicle code is actually too bad and does not behave as good as in Bullet (at least the Blender version), so I gave up on it (I am making my own based on a unity opensourced project [Tork](https://github.com/adrenak/Tork), bit arcady but seems good).

I think @AndreaCatania mentioned that he will bind the vehicle code from bullet at some point but I am not sure.

**Comment by LinuxUserGD** [comment]
A bit off-topic but reduz mentioned that the vehicle code won't be part of the engine in coming versions of Godot and instead implemented as a module (asset library).
