### ISSUE TITLE
Add font weight configuration to the "highlighting" option in the text editor

### ISSUE THREAD

**Issue by StragaSevera** [godotengine/godot#27910]
Right now we can customize colors of some code elements:
![](https://i.imgur.com/UCtQZFD.png)
But it would be great to have the ability to change font weight of this code elements, to make it look like so:
![](https://i.imgur.com/5SZVVs0.png)
It is common in the color schemes of IDEs to highlight "code words" like "var" and "func" in bold, and the absence of this feature pushes me off the default code editor. I think it would be great if Godot had the way to make them bold =-)

**Comment by Calinou** [comment]
This requires implementing the ability to use multiple fonts in TextEdit.

**Comment by 40detectives** [comment]
+1.

Some other common IDE usability/readability features include writing function signatures in italics too, which would be nice to have in addition to what @StragaSevera suggested.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
