### ISSUE TITLE
More debug draw modes (discussion)

### ISSUE THREAD

**Issue by kaadmy** [godotengine/godot#27911]
Would more debug draw modes in 3D be helpful for debugging/profiling?

I can think of a few that might be nice to have:

- Light limit: Change the object color depending on how many lights it currently has
- Luminance: Show fragment luminance remapped into a heat range
- Normal: Show fragment normal

Any other useful modes that could be useful?

**Comment by kaadmy** [comment]
It seems that with the current debug draw mode setup, it might be rather difficult to implement normalmap debugging (since the debug draw modes are their own material+shader, so any textures/custom shaders aren't taken into account).

**Comment by kaadmy** [comment]
Implemented light affect in #27914

**Comment by clayjohn** [comment]
Normal has been added in 4.0, as well as lighting (not luminance, but related)

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
