### ISSUE TITLE
Wang Tiles support for Autotile

### ISSUE THREAD

**Issue by novhack** [godotengine/godot#27923]
I love the way new autotile system works but currently I'm working on a top-down RPG game which would really benefit from having a possibility to specify multiple tile types in one autotile. So I think that adding the Wang tiles system to autotile could be really useful.

I won't go into describing the system here because the best description is on this website: http://www.cr31.co.uk/stagecast/wang/intro.html

**Comment by Valeryn4** [comment]
I would like to see the implementation of Wang tiles as in Tiled. (3х3 Wang tiles)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
