### ISSUE TITLE
Class initialization in C# happens 3 times when the game starts

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#27939]
**Godot version:**
3.1

**Issue description:**
A class calls it's constructor 3 times the first time the scene is run. After that it calls once normally.

**Steps to reproduce:**
Create a new scene. Attach a C# class to the root. On the constructor add a GD.Print("Boo"). Run the scene.

**Comment by groud** [comment]
Could you provide a minimal reproduction project ?

**Comment by neikeq** [comment]
Right now, we are creating a temporary instance once that is disposed right away. This is needed in order to get the default value of exported fields we use in the inspector. As of 5e354162f17aa53a09e7f44e1a2948621fb6d61c this temporary instance is only created in the editor, but this commit was made after the 3.1 stable release.

I'm confused as you mention the constructor being run 3 times. Can you provide an example project?

**Comment by Calinou** [comment]
@mateusak Can you still reproduce this issue on [Godot 3.2 beta 6](https://godotengine.org/article/dev-snapshot-godot-3-2-beta-6)? If so, could you upload a minimal reproduction project, please?

**Comment by Calinou** [comment]
I'll close this issue as no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was provided in time. This issue can be reopened if someone uploads a minimal reproduction project.
