### ISSUE TITLE
HDR display support

### ISSUE THREAD

**Issue by ScepticDope** [godotengine/godot#27956]
I'd love to see some more HDR Support. The 2D HDR demo works. But Godot does not tell its displaying HDR content to my video driver.

So I have to force my Windows 8.1 into HDR output mode by opening MPC-HC with MadVR and some HDR content.

Also I can't find any import settings described here: https://docs.godotengine.org/en/3.1/tutorials/3d/high_dynamic_range.html#linear-color-space-asset-pipeline

And I'd very much like to import some HDR .png files for my game. And be able to toggle HDR on and off on viewports that then start using the correct import version of the PNG.

Also at some point would love a HDR Video Content video format support for the `VideoPlayer`.

**Comment by fire** [comment]
I'm curious, what hdr monitor do you use? want to use? I don't think many of the contributors have the HDR hardware. 

There's also varying specifications to deal with.

**Comment by ScepticDope** [comment]
@fire Any certified HDR Monitor: https://displayhdr.org/certified-products/. Message me on Discord for more details?

Here is a good example project and its open source: https://krita.org/en/item/krita-4-2-0-the-first-painting-application-to-bring-hdr-support-to-windows/ *Note that the Windows 10 support only statement is incorrect and windows 8.1 will be mentioned in the upcoming release notes.

**Comment by Corruptinator** [comment]
I'm interested to see Godot be capable of outputting the game display in High Dynamic Range. There are a couple of things to take in consideration:

HDR for Godot would need to be handled in a color profile capable of correctly showing the brightest colors on a capable monitor, such as PQ, HLG, etc. Plus the engine must be able to export the energy of the color itself for the HDR monitor by 1000 nits or more. Probably at around 1000 nits.

Plus godot would need to have its own HDR metadata or signal to allow HDR to pass through HDMI or DisplayPort. Though depending on which OS you use:

Windows needs improvements on HDR,
Linux currently doesn't have HDR.
Mac has implementations of HDR.

Implementing HDR would probably be a challenging goal to pursue since HDR requires really good color management. But what do I know? Wanted to point out something related to HDR.

**Comment by ff7rule** [comment]
I would also like this implemented.

**Comment by Calinou** [comment]
@ff7rule Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by romulasry** [comment]
Linux has support for HDR or is very close, but there aren't any games or applications that use it yet.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by romulasry** [comment]
https://github.com/godotengine/godot-proposals/issues/1004
