### ISSUE TITLE
Visual script node search

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#27973]
There is currently no way to find where which nodes are used. Maybe making it so that if you press Ctrl+Shift+F whilst selecting a node, it will select all the same nodes and show you a panel similar to the script text editor search panel: 
![image](https://user-images.githubusercontent.com/28286961/56076508-53165a80-5dd2-11e9-8297-15b9e7624de0.png)
There could also be settings to match data, connections, where it should be searched etc.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
