### ISSUE TITLE
Add a shortcut for switching between open files in the script editor

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#27976]
Quick Open Script is nice when you have a name in mind and the file isn't already open, but when you're moving between a small set of files, being able to switch between them by tabbing through a list is ideal:

https://gfycat.com/NeedySardonicCassowary

That video was taken in Qt Creator, which uses the following shortcuts for this feature:

- Ctrl+Tab on Windows
- Alt/Option+Tab on macOS

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/22846 (which is about the scene editor).

**Comment by Calinou** [comment]
This is already available with <kbd>Ctrl + Shift + ,</kbd> and <kbd>Ctrl + Shift + .</kbd>. You can reassign those shortcuts in the Editor Settings.

However, reassigning those to shortcuts such as <kbd>Ctrl + Shift + Up</kbd> and <kbd>Ctrl + Shift + Down</kbd> won't work in `3.x` because the script editor will intercept those shortcuts.
