### ISSUE TITLE
Scene parsing error if there is a forgotten conflict

### ISSUE THREAD

**Issue by Dentrax** [godotengine/godot#27984]
**Godot version:**
`v3.1-stable_win64`

**OS/device including version:**
`Windows 10 v1803 (x64)`

**Issue description:**
When we are working with _Git_, If someone accidentally forgot to resolve the conflict in scene _(tscn)_ files, editor throws **parsing error** message. Instead of giving a error message, a conflict message would be better.

**Steps to reproduce:**
Add a simple _Git_ conflict lines to a scene file.

```
<<<<<<< HEAD
script = ExtResource( 10 )	script = ExtResource( 10 )
=======
texture_mode = 3080292
script = ExtResource( 11 )
>>>>>>> fd221dd76g8oo4d9d7833581593f18cb1ac5a855
```

**Minimal reproduction project:**
`N/A`

**Comment by akien-mga** [comment]
Godot has no knowledge of Git currently, so this file is simply a broken one. #25542 would have to be implemented before such Git-specific features can be implemented in the editor.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
