### ISSUE TITLE
GDScript format strings don't work with PoolStringArray

### ISSUE THREAD

**Issue by thebspin** [godotengine/godot#27985]
**Godot version:** v3.1

**OS/device including version:** Windows 10 Version (10.0.17763 Build 17763)

**Issue description:**
When trying to use the print function with a string and an array with words, it gives an error about there not being enough arguments for format string in operator %. When the array of words is being made into a normal GDscript array instead of a static typing array it works fine. I fixed it with putting the Array() function around my array with words.

**Steps to reproduce:**

```python
var words: PoolStringArray = ["baby", "one", "time"]
var song: String = "Hit me %s %s more %s"
print(song % words)
```

**Comment by akien-mga** [comment]
Just to clarify, it's not related to the type hints, but to the use of `PoolStringArray`. This fails without type hints too:
```
print("Hit me %s %s more %s" % PoolStringArray(["baby", "one", "time"]))
```

**Comment by akien-mga** [comment]
`Array` is currently hardcoded in `core/ustring.cpp`, support for `PoolStringArray` (and likely `PoolIntArray`, `PoolRealArray` and maybe `PoolByteArray`) would have to be added.

**Comment by girng** [comment]
Isn't this because PoolStringArray is not a array literal?

You can just do
```
	var words = ["baby", "one", "time"]
	var song = "Hit me %s %s more %s"
	print(song % words)
```

**Comment by KoBeWi** [comment]
In 4.0 you can use `Array[String]` if you really want your format values to be typed. The formatting can't work with PackedStringArray, because it's a different type and adding a special case is not worth it. We could probably mention somewhere in the [format strings doc](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_format_string.html) that PackedStringArray won't work.

If you think that PackedStringArray should be supported, you can open a [proposal](https://github.com/godotengine/godot-proposals).
