### ISSUE TITLE
Allow downloading files from the virtual file systems of HTML games

### ISSUE THREAD

**Issue by Astral-Cyrusa** [godotengine/godot#27992]
**Godot version:** 3.1
**OS/device including version:** Windows 10
**Issue description:**
I would like to make an HTML application that allows the user to move images around to build a map and then download the map as a png image.
This issue is about the downloading part.

For a native application, I would have godot make the map image, and then use the [save_png](https://docs.godotengine.org/en/3.1/classes/class_image.html?highlight=png#class-image-method-save-png) function of the Image class to save it to the user's disk.

But on HTML, Godot does not have access to the user's file system (for good security reasons), so ```save_png``` saves the image to some sort of virtual file system instead (see picture). From there, I would like to be able to have the browser open a download dialog for this file, but I have not found a way to do this in the Godot documentation.

![image](https://user-images.githubusercontent.com/20037940/56083901-77eaec00-5e2b-11e9-83db-db19392dc183.png)

So feature request: a way to tell the browser running an HTML game to open a download dialog for a file present in the virtual file system godot html games have access to.

Related issue: #18947
In this issue, someone suggests using ```JavaScript.eval()```. I tried a few things but the issue is that Javascript does not have access to the game's virtual file system where the png is.

**Minimal reproduction project:**
[HtmlDownloadPng.zip](https://github.com/godotengine/godot/files/3076619/HtmlDownloadPng.zip)

**Comment by LinuxUserGD** [comment]
Maybe this will be possible when Godot will be available on HTML5 as it was previously with godot.online

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Railwanderer** [comment]
Has this been archived? How can I keep track of the development going on?

**Comment by LinuxUserGD** [comment]
> Has this been archived? How can I keep track of the development going on?

By creating a new feature request at https://github.com/godotengine/godot-proposals

**Comment by Calinou** [comment]
File downloading is already implemented in Godot 3.4 with https://github.com/godotengine/godot/pull/48929.

**Comment by berlinnights** [comment]
**1. Version: Accessing buffer directly from Image class**

func Download_File(_img,_filename):
	var buf = _img.save_png_to_buffer()
	JavaScript.download_buffer(buf,_filename+".png")


**2. Version: Accessing buffer from File class, as mentioned above by Calinou**

func Save_PNG(_img,_path,_filename):
	var _err = _img.save_png(_path+"/"+_filename+".png")
	Download_File(_path+"/"+_filename+".png",_filename)
        #Put Error Handling Here

func Download_File(_path,_filename):
	var f = File.new()
	f.open(_path,File.READ)
	var buf = f.get_buffer(f.get_len())
	JavaScript.download_buffer(buf,_filename+".png")
	f.close()
