### ISSUE TITLE
Collisions against HeightMapShape do not work

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#27998]
Version: 3.2-dev

I could not make HeightMapShape work against CapsuleShape (StaticBody vs KinematicBody).
Have anybody tested this?

**Comment by slapin** [comment]
Well, it looks like it works but in unpredictable way. There is always offset, but can't guess how to control it. On the picture character stays on the actual shape but both debug drawing and logic says otherwise. Looks like shape fir bullet is generated incorrectly.

**Comment by slapin** [comment]
This is fixed by the following hack:
```diff
diff --git a/modules/bullet/shape_bullet.cpp b/modules/bullet/shape_bullet.cpp
index b590d63..362bab0 100644
--- a/modules/bullet/shape_bullet.cpp
+++ b/modules/bullet/shape_bullet.cpp
@@ -523,8 +523,9 @@ void HeightMapShapeBullet::set_data(const Variant &p_data) {
                        }
                }
        }
+       float mf = (fabs(l_min_height) > fabs(l_max_height)) ? fabs(l_min_height) : fabs(l_max_height);
 
-       setup(l_heights, l_width, l_depth, l_min_height, l_max_height);
+       setup(l_heights, l_width, l_depth, -mf, mf);
 }
 
 Variant HeightMapShapeBullet::get_data() const {
```

The proper fix will be to calculate the offset from min/max so that shape is properly centered.
Or correct debug geometry. Or use similar approach but using config flag.

**Comment by Zylann** [comment]
I had to fiddle with the way Bullet centers the shape in my plugin as well, because if nothing is done the shape won't be aligned the way you expect.
In my case I have the origin at the (0,0) point, and had to do this to re-center it the way I wanted my API to work: https://github.com/Zylann/godot_heightmap_plugin/blob/master/addons/zylann.hterrain/hterrain_collider.gd#L92

**Comment by slapin** [comment]
Either way the debug geometry is inconsistent with centering; Also this
centering mechanics be better handled by Godot, not end user code.

**Comment by BastiaanOlij** [comment]
Wow, this indeed works really weird. It is indeed centering the shape. Now the quick fix here is to change the debug shape logic to also center the mesh, that wouldn't be hard to do.

But I personally feel we should investigate if we can have the physics engine calculate the offset to the center and adjust the positioning of the collision shape. It is really counter intuitive to a user that the shape gets centered the way it does. I get why it needs to do this from a physics server performance point of view but surely we can solve this by offsetting things?

**Comment by BastiaanOlij** [comment]
@slapin well I did a PR yesterday that ensures the debug shape is now drawn where bullet moves the shape too. It's counter intuitive but its how bullet works. Atleast you can now see what is going on. 
The move and slide should work fine asfar as I'm aware, it's that bullet centers your shape that seems to be the problem.

**Comment by slapin** [comment]
Well, Bullet behaves fine being able to equally spread the shape among
floating point value; it is Godot's job to
properly position Bullet's shape from known user-provided transform to the
needed offset to be intuitive. I think things like
that should be under carpet otherwise having too many nuances makes
potential godot game developer's
head explode. Or at least some helpers should be provided (but I'm not big
fan of low level scripting).

**Comment by BastiaanOlij** [comment]
> it is Godot's job to properly position Bullet's shape from known user-provided transform to the needed offset to be intuitive

Fully agree, however easier said then done. There currently isn't a system in place that allows us to add this offset. It needs to be build. My fix in #28326 purely deals with centering the debug shape. The logic that does that can also be used to calculate the needed offset (seeing I'm applying it in reverse here) but actually making bullet react to this.. I'm still trying to get my head around the way this works :)

**Comment by Zylann** [comment]
@BastiaanOlij I basically did that in my plugin (which only uses servers), so it should be at least easy to do at node level, eventually at servers level.

**Comment by BastiaanOlij** [comment]
> @BastiaanOlij I basically did that in my plugin (which only uses servers), so it should be at least easy to do at node level, eventually at servers level.

It's not hard to do, it's just adding a transform which you've done in your plugin.
But it is hard to add this into the current setup of how the engine works without adding a very dirty solution.

Our heightfield is contained within a shape, that shape has no location information. It isn't until it is added to a collision object that it knows where it's placed in the world. It is that location that is send to the physics server. The problem here is that currently that position is sent before it's even wondered if it may need to be adjusted because of the shape we're displaying.

So the shape object needs to have an offset transform it can give to the collision object. The collision object then needs to add this transform to its own before updating the physics server.
We also need to add a mechanism where the shape object sends a signal to ALL collision objects its used in whenever it's offset changes.

That is a lot of work while this whole mess only applies to the heightmap shape. Might just be easier to require the developer to place the collision object accordingly, but its not friendly.

**Comment by slapin** [comment]
I do not understand why this can't be done via helper object which will
provide server with proper information.
I think you overcomplicate things. The offset data can be provided at time
of introduction of the shape and at time of shape
position update via helper object. Also you have all the information needed
to calculate offset in place. I think you should relax
a few days and give the thing a thought later.

**Comment by BastiaanOlij** [comment]
> I do not understand why this can't be done via helper object which will provide server with proper information. I think you overcomplicate things. The offset data can be provided at time of introduction of the shape and at time of shape position update via helper object. Also you have all the information needed to calculate offset in place. I think you should relax a few days and give the thing a thought later.

Hi @slapin, it's a puzzle alright.

The problem is that the shape is a resource, it has no idea how it's placed in the world and indeed, in theory, it may be placed multiple times in the world. It is the collision shape node that has the transform information that is communicated to the physics server but it is communicated to the physics server through the physic body node. That said, looking at the code there may be a possibility here.

You can see this in the code that assigns the shape to the collision shape node in `set_shape`:
https://github.com/godotengine/godot/blob/master/scene/3d/collision_shape.cpp#L152

First it assigns the shape and registers itself as the owner of the shape, this allows the shape to send all its owners a message when it changes, that's good, this calls the `_shape_changed` method:
https://github.com/godotengine/godot/blob/master/scene/3d/collision_shape.cpp#L230
But all it does is mark the shape as dirty so our gizmo can be updated. 

The other part of the puzzle is that the collision shape node also gets registered with its parent. Our parent is always a collision object (all physics bodies inherit from this). Now this gets interesting and possibly gives us a way to solve this. This whole thing happens in two steps. The first is that our collision shape node gets registered as an owner by calling `shape_owner_add_shape` here: 
https://github.com/godotengine/godot/blob/master/scene/3d/collision_shape.cpp#L82

The second is that our shape gets registered as well by calling `shape_owner_add_shape` here:
https://github.com/godotengine/godot/blob/master/scene/3d/collision_shape.cpp#L84
or here:
https://github.com/godotengine/godot/blob/master/scene/3d/collision_shape.cpp#L167

This means that the collision object node is fully aware of the shape. Now here is the final bit of magic, when the position of our collision shape node changes it communicates this back to the collision object. This happens in a few places by calling `_update_in_shape_owner` but one example is here:
https://github.com/godotengine/godot/blob/master/scene/3d/collision_shape.cpp#L86

Update shape holder communicates our position to our parent by calling `shape_owner_set_transform` which is defined here:
https://github.com/godotengine/godot/blob/master/scene/3d/collision_object.cpp#L224

What we can do is change `_update_in_shape_owner` method to first obtain our adjustment transform from our shape, multiply that with its own transform and then send the result to `shape_owner_set_transform`.
It also means calling `_update_in_shape_owner` from `_shape_changed`.

I'll make a start on this in the PR, might not get to finishing it until tonight as I'm taking the kids out soon.

**Comment by BastiaanOlij** [comment]
Ok, I've implemented the above in a separate commit on my PR, it was easier then I thought and it works but I do believe its fundamentally flawed because we now have logic specific to bullet in our core application. It really should have an fix inside of the bullet module itself.

I think this requires further discussion with input from @reduz and @AndreaCatania

**Comment by Zylann** [comment]
I think such a change should remain isolated in PhysicsServerBullet, as it's really its job to map Bullet to the Godot API the best it can, but I don't know how feasible it is, haven't investigated that myself.

**Comment by BastiaanOlij** [comment]
> I think such a change should remain isolated in PhysicsServerBullet, as it's really its job to map Bullet to the Godot API the best it can, but I don't know how feasible it is, haven't investigated that myself.

I agree but I too don't know the internals of the physics engine well enough yet to know how that can be adjusted. We'd need to store the original transform communicated by Godot and the adjusted transform because we need to be able to re-adjust it when we get new shape data. 
I have a feeling it's all just pass through logic to the bullet engine without it actually keeping state which may make this hard to do.

I hope to find some time to have a look over the weekend.
