### ISSUE TITLE
Auto-compeletion not working in GDScript that use class_name.

### ISSUE THREAD

**Issue by harrisyu** [godotengine/godot#28002]
**Godot version:**
Version that don't work : https://github.com/godotengine/godot/commit/ad1368a62521a31b574acd8c545795d1b64c447e

Version that work : https://github.com/godotengine/godot/commit/f75b9e62468ba65753f2ce49c02f1a129c08b717

**Issue description:**
If you using class_name in your GDScript, auto-compeletion stop working.
When you delete it, it works again.

**Comment by groud** [comment]
Related to #27467

**Comment by akien-mga** [comment]
> Version that don't work : ad1368a
Version that work : f75b9e6

I guess it's a regression from either #27863 or #27876. @bojidar-bg @vnen

**Comment by lupoDharkael** [comment]
I've bisected the problem and it is caused by https://github.com/godotengine/godot/commit/e56f5d5c910f076fd93af71ada7550f441207f45
@vnen

**Comment by lupoDharkael** [comment]
I've found the cause:
https://github.com/lupoDharkael/godot/blob/f137166251c4c734e1fd4d682492168483ccad3f/modules/gdscript/gdscript_editor.cpp#L2465-L2466

It passes an empty string to the self_path of parse() so the condition of https://github.com/godotengine/godot/commit/e56f5d5c910f076fd93af71ada7550f441207f45 self_path.empty() is always true when auto completing.

**Comment by lupoDharkael** [comment]
maybe we should change `complete_code()` to receive the path of the script and not the base path? 
https://github.com/godotengine/godot/blob/f137166251c4c734e1fd4d682492168483ccad3f/editor/plugins/script_text_editor.cpp#L606
That way we would pass `script->get_path()` instead of `script->get_path().get_base_dir()`.
I'm not very familiar with this code to see an alternative to solve this.
