### ISSUE TITLE
First element of an array of multiline strings shows text vertically when uncollapsed

### ISSUE THREAD

**Issue by anonyore** [godotengine/godot#28021]
**Godot version:**
Godot 3.1 stable

**OS/device including version:**
Windows 10 Version 1809

**Issue description:**
When making an array of multiline strings with only one element, the first element will render all of its text vertically in the inspector if you collapse and then uncollapse the array. Clicking on the text box will reset it back to normal. This doesn't happen if there is more than one element in the array.
![MultilineTextBug](https://user-images.githubusercontent.com/37919189/56097438-0447ee00-5ec2-11e9-9586-15f601c3eb1b.gif)

**Steps to reproduce:**
1. Create an exported var with the hints Array, String, and MULTILINE.
2. Add exactly one element and input some text.
3. Collapse the array in the inspector and then uncollapse.
4. The text will be displayed vertically until you click on the text box.

**Comment by piyushdagar** [comment]
I am able to reproduce this but in my case it also happens with more than one element. Scrolling a bit refreshes the screen to the expected behaviour. I will try to fix this.
![Peek 2019-04-21 23-22](https://user-images.githubusercontent.com/30121673/56473704-7ef9a600-648c-11e9-9f3f-4dfcfaa2d77f.gif)

**Comment by jsamar1** [comment]
I've also reproduced and looked into this issue. It happens within `text_edit.cpp`. If you scroll down within the text box when it is vertical, `ERR_FAIL_INDEX_V(0, -1, 0)` is called from the `times_line_wraps` function and throws this error: 
`.TextEdit::times_line_wraps: Index line=1 out of size (text.size()=1)
   At: scene\gui\text_edit.cpp:3806`
I don't think thats neccessarily the issue after looking through the code. 

I found that changing the return value of `line_wraps` to false resolves the issue, so I think the root cause is in `_update_wrap_at` or `get_line_width`. `line_wraps` returns true because wrap_at's value goes from 152 to a negative value after reopening the array. Scrolling causes wrap_at to return to 152 and rerender as a single line. 

I'm not sure how to fix wrap_at's value in general, not to mention any possible side effects that could happen, so any help here is appreciated.

**Comment by norkn** [comment]
It seems to me the problem is that the calculation of `wrap_at` in `_update_wrap_at()` depends on the size of the `TextEdit` object, which changes during the process of collapsing and uncollapsing. After uncollapsing, `wrap_at` gets calculated before the `TextEdit` object is resized to it's uncollapsed state. 

Having `TextEdit` override `Control`'s `_size_changed()` function like so solved the issue for me:
`void TextEdit::_size_changed() {`
`     Control::_size_changed();`
`    _update_wrap_at();`
`}`

I don't know if this is the cleanest option. To override the private function `_size_changed()` of `Control`, I made `TextEdit` a friend class of `Control`.
But I think it generally makes sense for any change in size of a `TextEdit` object to result in and update of it's `wrap_at`. 

I'm new to working on serious open source projects and feedback to this attempt of a fix would be greatly appreciated :) If this seems sensible, i could issue a pull request

**Comment by vortexofdoom** [comment]
@norkn were you going to create a PR for this?

**Comment by norkn** [comment]
@vortexofdoom yes, i'll make one :) i wanted to listen for feedback first and then i forgot about this for a bit, sorry.
