### ISSUE TITLE
UX Papercut: "Perspective" menu contains items not related to perspective.

### ISSUE THREAD

**Issue by mindinsomnia** [godotengine/godot#28035]
(I'm planning to do a few UX feedback issues just supplying feedback on Godot's UI and pointing out anything which seems like it could be improved. Please don't take this critique as an attack, I love Godot and I'm already a donating supporter, I'm just keen to help improve the UX of Godot!)

The UI element that appears in the top left of the editor in my opinion visually appears like it's either a button or perhaps a mode switch for switching between Perspective and Ortho:

![perspective menu](https://user-images.githubusercontent.com/15921126/56102676-dde18b80-5f71-11e9-8353-91c0b3569a5e.png)

I was surprised the first time a few weeks ago when I clicked the UI element to discovered so many options hidden inside of it, many of which don't seem related at all:

![perspective-menu-open jpg](https://user-images.githubusercontent.com/15921126/56102681-e89c2080-5f71-11e9-9d53-1250abb15bce.png)

I think I understand the intent here, to display the current view mode, and also display a menu dropdown option, but to show both joined together visually suggests a relationship that doesn't appear to be there. Separating these elements could improve the UX.

**Comment by Zireael07** [comment]
Separating is IMHO a bad idea, just change the name to something more generic... "View Options"?

**Comment by Calinou** [comment]
Displaying the current view mode is helpful when you use multiple viewports, so you can see which one is facing front, right, top, …

**Comment by Calinou** [comment]
I just tried doing what I said back in April:

![image](https://user-images.githubusercontent.com/180032/64298177-fc720e80-cf74-11e9-80fd-c2b4b9fc450e.png)

There are a few issues with this though:

- The text becomes difficult to read on a light background. This can be solved by adding a translucent background, but then, it starts looking like a button (even though it's just a Label).
- It uses more screen real estate overall, which can become an issue when using 4 split viewports.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
