### ISSUE TITLE
Billboard mode doesn't work for spatial materials

### ISSUE THREAD

**Issue by mryannisp** [godotengine/godot#28054]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10 v1803

**Issue description:**
Billboard mode for spatial material doesn't work
![preview](https://user-images.githubusercontent.com/34424107/56139632-ece03200-5fa1-11e9-880f-e3f9a36d9537.gif)

**Comment by clayjohn** [comment]
Can you try this with a quadmesh? Im not sure this is a bug. Im not at a computer now, but from what i remember billboard makes the Z-direction face you at all times. So you would be looking directly at the edge of the PlaneMesh and wouldnt see anything. Which is expected behaviour. But with a quad mesh the flat side should always face you.

**Comment by mryannisp** [comment]
> 
> 
> Can you try this with a quadmesh? Im not sure this is a bug. Im not at a computer now, but from what i remember billboard makes the Z-direction face you at all times. So you would be looking directly at the edge of the PlaneMesh and wouldnt see anything. Which is expected behaviour. But with a quad mesh the flat side should always face you.

You're right, I had to change the mesh from plane to quad. Still, I thought billboard mode would work with any kind of mesh.

**Comment by clayjohn** [comment]
It does! Which is exactly why you cant see it. The PlaneMesh doesnt have any depth.

**Comment by mryannisp** [comment]
I see. Then I guess this is not a bug, so I'm closing this issue. Thank you
