### ISSUE TITLE
Show changes on screen WHILE DEBUGGING

### ISSUE THREAD

**Issue by rogeriodec** [godotengine/godot#28068]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 x64 / NVIDIA GeForce GTX 1060 6GB / Intel Core i7 4790K

**Issue description:**
Currently, I can't see any changes on the game screen while debugging.
For example, if a script line changes a **node translation**, it should be **automatically updated on the game´s window**...

**This would be extremely useful and would greatly aid the development workflow.**

**Comment by volzhs** [comment]
did you try this option?

![image](https://user-images.githubusercontent.com/8281454/56167273-b5f63480-6012-11e9-83e3-79791f57c0ee.png)

**Comment by rogeriodec** [comment]
> did you try this option?
> 
> ![image](https://user-images.githubusercontent.com/8281454/56167273-b5f63480-6012-11e9-83e3-79791f57c0ee.png)

Makes no difference. Have you already tried? The changes are shown just when the cycle is completed, not per line.

**Comment by Zylann** [comment]
> For example, if a script line changes a node translation, it should be automatically updated on the game´s window...

By this, do you mean that you are on a breakpoint, and stepping over a line which sets a node's translation?
This is not possible, because that means Godot has to render an extra frame before it has finished running scripts. Doing so could introduce state changes in the renderer that will change the behavior of scripts (like render textures, viewport states, frame counter, or failing to access locked resources), and you certainly don't want that when debugging.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
