### ISSUE TITLE
Opening many scenes tabs pushes right panel out of screen

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#2806]
Closing scenes tabs doesn't bring back the panel. See following video : 

https://youtu.be/2Dy9zskLz60

Reference: #2396

**Comment by bojidar-bg** [comment]
Can confirm on master(b08312b30c5fa47bffc2d21d4cb57520b822bf45). Also, note that the panel comes back after you resize the window.

**Comment by reduz** [comment]
Ah right this was never fixed

**Comment by romulox-x** [comment]
I'd add that when you have many tabs open, so you're just about out of tab space, you then can't drag the left or right panels open very much.  They stop dragging when the center area can't shrink any more because it ran out of tab space.  I expect the solution to the original issue will involve the little arrow that lets you scroll to more tabs when you have more than you can show, so I imagine it will have a side effect of letting you drag these out again.

**Comment by StraToN** [comment]
@romulox-x Yes, that tabs-scrolling button will become mandatory very soon. I have some experience with Tabs development, so I should be able to do it. Unfortunately, I don't have enough time at the moment. I expect starting working on this task at the beginning of December 2015.
