### ISSUE TITLE
Duplicating export presets adds a "1" to its name instead of incrementing the number

### ISSUE THREAD

**Issue by johnb-odplot** [godotengine/godot#28091]
**Godot version:**

v3.1.1.devel.custom_build.b75a5ba

**OS/device including version:**

Windows 10 64bit

**Issue description:**

In the export window, duplicating an export preset just adds a "1" to the end of it (Windows Desktop -> Windows Desktop 1 -> Windows Desktop 11 ...)

I expected it to go Windows Desktop -> Windows Desktop 1 -> Windows Desktop 2 ...

**Steps to reproduce:**
Click on a preset in the Export window, duplicate it, then duplicate the duplicate

**Comment by griant** [comment]
https://github.com/godotengine/godot/blob/6697fd9a05859914fc320b4b4321fd9fb6170f71/editor/project_export.cpp#L574-L597

I don't know if it's intended.

**Comment by hbina** [comment]
I think the problem is that when we get the current name, we will "X1", then we try to compare this with "X1" + "1", which is "X11", as expected.
Basically we will always fail to find a duplicate, which I assume is what the code you pasted is trying to achieve?

**Comment by akien-mga** [comment]
I don't think it's intended, the code just needs to be amended to fix the logic.

One should take care not to make "Linux/X11" become "Linux/X12" though, so it should be (pseudo-code) `get_preset_default_name() + " " + itos(attempt)` so that it becomes "Linux/X11 2".

**Comment by sparkart** [comment]
> I don't think it's intended, the code just needs to be amended to fix the logic.
> 
> One should take care not to make "Linux/X11" become "Linux/X12" though, so it should be (pseudo-code) `get_preset_default_name() + " " + itos(attempt)` so that it becomes "Linux/X11 2".

If the user can name the preset using any type of character, I think perhaps instead of incrementing by 'attempt' when duplicating, it makes sense to simply append copy to the name (example: Linux/X11 copy, Linux/X11 copy copy, Linux/X11 copy copy copy)

So I believe the issue was actually intended because we essentially cannot distinguish the difference between a duplicate or the user's actual intended name. For example, if you name it: "Nintendo 64" You would get: Nintendo 64 2, Nintendo 64 2 2, Nintendo 64 2 2 2. We also don't know if it should be incremented to: "Nintendo 65".

What do you think? I think appending "copy" is the best solution.

**Comment by akien-mga** [comment]
Good point indeed. Style wise, I'd suggest to append `" (copy)"`.
