### ISSUE TITLE
Improvements to TextureProgress

### ISSUE THREAD

**Issue by Vultraz** [godotengine/godot#28109]
**Godot version:**
3.1 stable

**OS/device including version:**
Any

**Issue description:**
`TextureProgress` feels very clunky for creating circular progress bars. First, off, there is no built-in geometry texture or similar you can use to tell the engine to generate a circle for the `cover` texture. So, I went into GIMP and created a 512x512 circle, like so (except in white):

![progress_circular](https://user-images.githubusercontent.com/3558659/56256235-7a8f5f00-6113-11e9-9d7c-0ec013aa3686.png)

It needs to be large to retain appropriate crispness. But, since `TexureProgress` simply takes a texture straight, you need to either make sure your `TextureProgress` node's size matches that of your image or scale it down. The scale mode abilities of `TextureRect` would be useful here.

Also, since the image is a static texture, if you scale down too far the bar becomes really thin :(

**Comment by fire** [comment]
I would use svg to make the rasterized circle. I don't understand the usecase though.

**Comment by Vultraz** [comment]
🤔 I didn't consider SVG. That would probably work better...

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
