### ISSUE TITLE
Failed loading file 'projectname(\..+).wasm': File not found

### ISSUE THREAD

**Issue by davincif** [godotengine/godot#28103]
No, it's not a duplicated of [#12498](https://github.com/godotengine/godot/issues/12498). I've  checked that.

Godot version:
3.1

OS/device including version:
Linux Mint 19 Cinnamon x64
kernel 4.15.0-47-generic
AMD Ryzen 5 2600 Six-Core Processor × 6
NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] not graphic related, though
Google Chrome Version 73.0.3683.103 (Official Version) 64 bits

**Issue description:**
After exporting to web, and serving python3 -m http.server, when acessing the .html, it crashes.

**Steps to reproduce:**
1. Configure a project to export for web
2. Name it anything and antes with .anything.html (my case was blablabla.1.0.0-alpha.html)
3. Serve it on localhost, try to access the .html file

**Minimal reproduction project:**
Create any project and export like above

**Comment by akien-mga** [comment]
Seems to work fine in the current master branch.

**Comment by asheraryam** [comment]
I did run into this issue recently with the recent beta builds (I ran a quick re-export to web for all my jam games) so I'll check again soon and see if it still happens. (Can't remember if it was just my VPN or it persisted after).

I also have an issue with the web build not re-building in the editor because of file permissions issue on windows ("Access denied, file in use etc") so I'll open an issue for that later when I have the time.

**Comment by akien-mga** [comment]
> I also have an issue with the web build not re-building in the editor because of file permissions issue on windows ("Access denied, file in use etc") so I'll open an issue for that later when I have the time.

That was fixed yesterday :)

**Comment by asheraryam** [comment]
@akien-mga Nice! I try to keep up with the commits but this repo is on fire lol!
