### ISSUE TITLE
Add a clipboard history feature to the editor

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#28120]
Qt Creator has a nice feature where pressing Command + Shift + V (on macOS) brings up a clipboard history menu:

<img width="188" alt="Screen Shot 2019-04-17 at 12 27 19 PM" src="https://user-images.githubusercontent.com/6002340/56281168-39e01780-610c-11e9-9edf-f9d302a4db8d.png">

So the most recently things you've copied in the editor will show up there, making it really easy to quickly paste in variables etc. you've recently been working with.

**Comment by bojidar-bg** [comment]
Quick note: there are exisiting solutions for clipboard history in KDE (builtin), Gnome (extension), Windows 10 (builtin), and Mac (builtin and apps). Of course, not having to switch context to the desktop shell in order to view the history might still be useful.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
