### ISSUE TITLE
Global Asset Library

### ISSUE THREAD

**Issue by user865** [godotengine/godot#28142]
Been learning about Godot for about a week, and what seems like somewhat of a glaring issue to me is having to recreate basic assets for every new project. Or having to navigate to other projects, search through, pick out what you need (along with dependencies), and drag into the editor or copy and paste to your current project. Either way it's a hassle.

The first solution that comes to my mind is to have a global asset library you could drop all your materials, shaders, meshlibs, textures, etc into, and make them accessible from any project. 

I think it's also important that, if something in the editor appears to be a single object, we have the ability to treat it like a single object everywhere, without having to worry about its parts or dependencies.

**Comment by LikeLakers2** [comment]
I believe you can achieve virtually the same effect by making your own folder (say, on your desktop), which you copy those sorts of things to. Then when you want to add them to a project, you just copy them to that project. This isn't a bad idea, mind you, just... not something I think you'd need the editor to be able to do.

**Comment by isaacremnant** [comment]
How about just a way to link to folders outside of res:// ? I definitely see an advantage in not propagating copies of the same stuff.

I tried to put a symlink in res:// and while Godot is able to scan and import images from the linked folder, it doesn't show in the filesystem. Didn't test export, but there may be problems with that too. Maybe just making sure Godot plays nice with links would be enough for this feature proposal?

**Comment by fire** [comment]
Symlinks don't work on windows very well.

Linking folders outside of res.. There was a brief design to rewritethe plugin system to include an entire project as an addon. The addon will include the entire library. This will avoid symlinks. Not sure if the entire design was completed.

**Comment by willnationsdev** [comment]
A lot of this discussion has been going on in #19846 (that one is a hotpot of several different related discussions, so it's not quite as focused as the discussion going on here). Also relevant is [this comment](https://github.com/godotengine/godot/issues/19506#issuecomment-396680293) from #19506 (apparently there are plans to make the Asset Library host more individual classes in the future, when the API and plugin tooling is more flexible/powerful).

**Comment by KoBeWi** [comment]
@willnationsdev Looks like you referenced wrong issue.

**Comment by willnationsdev** [comment]
@KoBeWi Fixed, thanks.

**Comment by silkentrance** [comment]
Some info about git and handling symlinks on windows using a post checkout hook:

https://stackoverflow.com/questions/5917249/git-symlinks-in-windows

**Comment by menip** [comment]
If you mean locally, then a folder does the trick.
If you mean being able to use other people assets, how is this different from AssetLib? Sure it's in need of serious TLC, but still.

**Comment by paulhocker** [comment]
try this -- its still a WIP but I use it for all my projects

https://gitlab.com/godot-stuff/gs-project-manager/wikis/home

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
