### ISSUE TITLE
Have Scene Tree relationship lines color be configurable again

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#28184]
**Godot version:**
3.1

According to #28174 - the scene tree relationship lines can no longer be configured. I really liked this part of the engine as it very easily allowed you to see the relationship. I preferred to have a dark theme with the lines being a brighter color - such as yellow

This worked find in 3.0.6 and am not sure why it was removed

**Comment by KoBeWi** [comment]
But the lines have bright color, the default opacity is just low. You can configure it in Editor Settings under Interface -> Theme.

**Comment by Duroxxigar** [comment]
@KoBeWi I still prefer for the color to be configurable. Again, I do not understand why it was removed, and I don't recall it being mentioned either.

**Comment by Calinou** [comment]
It was probably removed because it's not a very useful setting in itself. Having the opacity configurable is good enough for most people (so that they can be made more visible for users with poor vision).

**Comment by Calinou** [comment]
Note: Please consider the [added maintenace cost](https://github.com/godotengine/godot/issues/28184#issuecomment-497787407) before opening a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
