### ISSUE TITLE
class_name overrides AutoLoad global name if using the same name

### ISSUE THREAD

**Issue by Reneator** [godotengine/godot#28187]
**Godot version:**
3.1 official

**OS/device including version:**
Windows 7 PC

**Issue description:**
Whenever i use globals and give them a class_name, i cannot access their non-static methods via script, because the script thinks i want to access a class instead of a global, although i have autoload on. But it can be "solved" in two ways:

- remove the class-name
- make the func in the global static (although he seems to still try to access the Object and not the global) But here i have the advantage of not being able to emit signals from the global. Maybe more, but this is the most impactful to me.

I guess this happens only, if the class_name and the script-name are identical.

As i know this now, for me personally this is not too big of an issue, but for newcomers this could put them in front of a problem, that could be deterring them from using godot any further, as its not a direclty "logical" error, if you dont know its cause.

**Steps to reproduce:**
- Add Script to autoload
- add Class_name that is identical to the Name in Autoload
- try executing a non-static method in the global

solve by:
- either make method static
- or delete class_name

**Minimal reproduction project:**
[Reproduction_Project.zip](https://github.com/godotengine/godot/files/3097255/Reproduction_Project.zip)

**Comment by akien-mga** [comment]
It should likely raise an error when `class_name` and the AutoLoad global name conflict. There's no practical reason for using `class_name` in an AutoLoad (at least not with the same name), so we should just forbid it.

**Comment by Atomic-Potato** [comment]
This can be a problem when you're trying to use gdscript in combo with c#. If i have a gd autoload class and i want to reference a static function of that class in C#, i cant because it cant find the class that i want.

**Comment by MartinMajewski** [comment]
> It should likely raise an error when `class_name` and the AutoLoad global name conflict. There's no practical reason for using `class_name` in an AutoLoad (at least not with the same name), so we should just forbid it.

I want to open/push this issue into existence again. It is an issue that Autoload is not allowing class_name definitions when you're using an external editor like Rider. Rider does not know that a script is autoloaded, and because the script does not have an explicit class name, Rider cannot resolve references to it!

The best way to use Autoload would be to enforce the usage of class_name and use this value inside Autoload instead of setting it there. Inside the Autoload menu, only the uid or the path should be used to register a script to be autoloaded.
