### ISSUE TITLE
TextureAtlas importer add black lines on corners

### ISSUE THREAD

**Issue by guilhermefelipecgs** [godotengine/godot#28212]
**Godot version:**
1120b0b2d3f0df34f24d9ca6b086c192ebc1c5b6

**OS/device including version:**
5.0.7-arch1-1-ARCH

**Issue description:**
![Captura de tela de 2019-04-19 17-51-56](https://user-images.githubusercontent.com/1387165/56443620-e3213c00-62cb-11e9-8aa2-9c14df81c9e4.png)

**Steps to reproduce:**
Just create an atlas with godot's icon.

**Comment by akien-mga** [comment]
Seems fixed in the current master branch.

If you can still reproduce it, please provide a project / more detailed steps to reproduce.
What I did:
- Create new AtlasTexture resource
- Used `icon.png` as texture for the Atlas property
- Set region to `0, 0, 64, 64`.
- Assigned this resource to a Sprite.
