### ISSUE TITLE
[Theming Enhancement] Improvements to StyleBox's

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#28219]
**Godot version:**
3.1

**OS/device including version:**
ANY

**Issue description:**
Currently users have to use an inconsistent way of setting/getting the stylebox property on a control node.  `add_stylebox("panel", StyleBoxFlat)` or `get_stylebox("panel", StyleBoxFlat) `. this makes properties on controls like Panels for example confusing since it breaks consistency the way properties are interacted with in 3.x and newer. Can support be brought inline to be consistent with the rest of the engine? Are there other nodes with similar limitations?

**Steps to reproduce:**
Users can't interact with these properties and leads to confusing.
![Screenshot (2)](https://user-images.githubusercontent.com/5633261/56449051-bcfa9c80-62c9-11e9-99c9-9e1b2a84aac2.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is how all theme properties work as far as I know (colors, constants, fonts, styleboxes). These are not member variables.

**Comment by KoBeWi** [comment]
This would involve binding fake properties for each theme item. It should be possible, but not sure if it's worth it. I didn't see anyone else complain that it's confusing.
(the problem might come from Panel having only theme properties unlike most other Control nodes)

**Comment by Calinou** [comment]
> This would involve binding fake properties for each theme item. It should be possible, but not sure if it's worth it.

Indeed, I don't think it's worth the trouble. All we can do is print a better error message if a theme item with the same name as the property exists when attempting to use it as a property.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
