### ISSUE TITLE
Add ability to autotile more finely based on bitmask grid

### ISSUE THREAD

**Issue by ishax-kos** [godotengine/godot#28251]
Currently, auto tiling is based entirely on what tile is adjacent to another. This is fine in some instances, but if for example, you want to create the top left image, it is impossible. It will instead look like the top right image. I believe a "bitmask autotiling mode" would fix this.
The first conception I came up with was to add a "bit layer" to tilemaps that you could draw on. 

Essentially you draw pattern the size of the bitmap editing grid for where you want a certain material to be, and the autotiler lays down the corresponding tiles.

I think my current conception of this solves the problem more elegantly, and without adding a new data layer. In this version in "bitmask autotiling mode", the place inside each tile you click determines what tile is placed. For instance, if you have grass selected, and you click and drag along the edge between two dirt tiles, it would place a transitional grass tile on either side of that edge. Clicking on a corner, you would see each become a corner transition etc.

The bottom two images illustrate where you would click in blue and where the actual tile grid is in red. The bottom right corresponds to a 3x3 bitmask. The bottom left image corresponds to an edge-based bitmask (2x2 turned 45 deg); which is the ideal sub grid the tiles used in the example. (this is the same as in issue #17063)
![tiling sample3](https://user-images.githubusercontent.com/25571687/56462350-f0dfcb80-6376-11e9-88d5-1fb7b9d924b7.png)
While this feature would go along nicely with adding ignored bitmask bits (#18134), I think it may take some brainstorming to make code that determines what you mean when drawing in these ignored spaces in the tilemap editor.

**Comment by Calinou** [comment]
Check the proposals [here](https://github.com/godotengine/godot-proposals/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+autotile) and try the new TileMap/TileSet editor in 4.0 nightly builds before opening a proposal.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
