### ISSUE TITLE
Prevent C# exceptions from terminating the game

### ISSUE THREAD

**Issue by mysticfall** [godotengine/godot#28259]
**Godot version:**
`master` / 7be49849

**OS/device including version:**
Manjaro Linux 18.0.4

**Issue description:** _(This issue is a feature request)_
When a non-fatal error occurs, like when invoking Godot API with a wrong argument, Godot usually logs the error to the console and continues. However, when an exception happens in C# code, it often crashes the entire game which is often an undesired behaviour.

It'd be better if Godot could catch all such unhandled exceptions and log them to the console and continues the execution, or let the user choose how to deal with such a case by setting a relevant project setting.

**Comment by neikeq** [comment]
I swear there was already an issue about this but I can't find it.
To make it a bit more clear, this issue asks for a behavior similar to that of Unity, where unhandled exceptions are logged in the editor without terminating the application. The plan is to make this configurable.

**Comment by aaronfranke** [comment]
Out of curiosity, would it be possible for the game to halt instead of terminating? This would allow viewing the game state in the remote inspector, and/or viewing the game's last frame in its window.

**Comment by neikeq** [comment]
This was implemented in 513cc78f85d8c45a9492ae25034cd2357714cfdf. You have a project setting to enable this and it's enabled by default in the editor as we should not be crashing due to mistakes in editor plugins (also it would make development of plugins too painful if we crashed the whole editor at every mistake).

Worth mentioning:

- It doesn't support different policies between editor player and exported games (e.g.: logging in editor player and terminating in exported games), so one would have to change the setting before exporting if that's desired. This could be implemented easily though.
- This is not supported for all exceptions, only those we can catch. Mono's unhandled exception hook are meant to never return, so we can only terminate the application if we get notified of an exception that way.

**Comment by akien-mga** [comment]
Closing as solved then. If changes to the new feature are needed, they could be tracked in new issues.

**Comment by c-schembri** [comment]
@neikeq was this feature removed from later Godot versions? I.e., is there no way to configure how Godot handles C# exceptions as of 4.1?

**Comment by MikeSchulze** [comment]
I actually run into the same problem, I strictly want to catch such exception by my own.
If there is an exception handler, I can register to be propagated engine caught exceptions?
