### ISSUE TITLE
Godot can not import files on exFAT drive

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#28268]
**Godot version:**
3.1 stable (tested on mono & classic)

**OS/device including version:**
Windows 10

**Issue description:**
Godot engine is portable, which is really an advantage. I use a fast external SSD (Samsung SSD 860 EVO 2.5" (1 To)), exFat formatted. The folder with Godot projects is marked as indexed in Windows indexation settings.

Problem is Godot do not refresh it's own file indexing when I try to import new files (no matter which, images, dae models, ogg sounds, scripts and so on). It sees them only when I restart the editor. It also does not matter if I started it from the file link, project link, or from ```godot -e```.
When I update files (for example, save a new image to an already imported one), godot updates it immediately.

The problem is both on mono and classic versions. If I create a project on a main drive (which is an NTFS Samsung 850 EVO 250 gb), there are no problems, it imports everything immediately.
Building and exporting work without problems on all drives.

**Steps to reproduce:**
Create a blank project on external SSD and try to import files.

**Comment by ismslv** [comment]
After a bit of experimentation found that it happens only with drives formatted to exFAT. NTFS and FAT32 work well. While I understand the difference with NTFS, I can not understand, how can FAT work better than exFAT?

**Comment by Ranoller** [comment]
It´s not problem of exFAT- NTFS - FAT32... is problem from not-indexed units. I has this problem in the past with a pendrive. In my main computer the problem was gone time ago... but i remember did a lot of shit to the system to try to idex the pendrive...so, i can´t help with that (and this kind of system tweerk is not godot philosophy). The reload of the entire editor finished to annoying me so much that i made a button in a plugin to "rescan":

`get_editor_interface().get_resource_filesystem().scan()`

**Comment by ismslv** [comment]
Hello Ranoller, thank you for your answer. I've read your issue before posting mine.

> It´s not problem of exFAT- NTFS - FAT32... is problem from not-indexed units.

But I have indexing turned on for this folder and "items indexed" number in control panel rise each time I add any file there.
