### ISSUE TITLE
Pixel Snap rounds position to pixel position from -0.29 to +0.69 

### ISSUE THREAD

**Issue by podpathos** [godotengine/godot#28278]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10, Intel i7-4770K, AMD Radeon R9 380, 

**Issue description:**
Pixel Snap rounds position to pixel position from -0.29 to +0.69 range. I'm making game with low resolution and it seems to me that it would be better if Pixel Snapin would just floor pixel position instead of this strange range. Not sure if it is a bug.

**Steps to reproduce:**
Move pixel inside a project with arrow keys.

![01](https://user-images.githubusercontent.com/34633102/56473437-b99f1680-646b-11e9-92f3-ab726fe98eec.png)

![02](https://user-images.githubusercontent.com/34633102/56473442-c885c900-646b-11e9-8dbb-6ba44a76f978.png)

![03](https://user-images.githubusercontent.com/34633102/56473443-cde31380-646b-11e9-8fe7-0bf4a0871cb5.png)

**Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/3101435/test.zip)

**Comment by clayjohn** [comment]
You are mixing up two different pixel snaps. One is in the global settings. It makes the pixels snap to screen pixels when being drawn to the screen (in order to maintain crisp pixel art in motion) (this one only affects drawing). The other is an editor feature that snaps pixels to the grid while placing them (this is the one you want). 

In the top bar above the viewport click the little icon that has a magnet and a few dots, this turns on pixel snapping. Beside it are three vertical dots. Click on those and select "use pixel snap".

**Comment by podpathos** [comment]
No I'am talking about Pixel Snap in Redner setings - drawing when resolution is streched. When I turn off Pixel Snap (not in editor) it draws pixels on screen on a mid point between two pixel as it should, but with Pixel Snap it places pixel that is greater than -0.29 and less than 0.69 in floats to -1 in pixel position, if floating point of sprite is greater or less or equal than 0.29 it would put pixel on -2 in pixel space. All I wonder is should it be simple floor funcition so that range should not be this strange. But it can also be product of screen resolution, dont know for sure. I have changed resolution but same things happened. Not sure is this wonded behavior but it doesn't look pretty for low resolution games - character would be inside obstacle even if collsion code runs as it should.

**Comment by clayjohn** [comment]
I understand what you're saying now. 

Pixel snap rounds up when the fractional part of the pixel is >0.5 and it rounds down when <0.5. This keeps pixels whole when you are working in pixel art and ensures smooth transitions while pixels are moving. 

You are seeing them snap at -0.29 and 0.69 because your camera is offset by by ``(0.196, 0.087)`` "Use Pixel Snap" snaps the pixel in screen space, not in global space. So when you camera is offset it creates a difference between when the pixels offset and the Sprite's position. If you set the transform of your "Player" Node2D to ``(0, 0)``, you will notice that the pixel now snaps correctly at 0.5.

**Comment by podpathos** [comment]
O, my bad. Did not see that, sorry. Thank you for fast answer and your time, much appreciated.

**Comment by clayjohn** [comment]
Your welcome! Good luck with your project.
