### ISSUE TITLE
C#: Allow project source files to be separated into a sub project folder.

### ISSUE THREAD

**Issue by exts** [godotengine/godot#28290]
**Godot version:**
3.2

**OS/device including version:**
All

**Issue description:**
Currently all C# projects are forced to be in the root project folder meaning the default namespace will always be that folder and most code is put into sub folders. When that happens your `src`, `code`, `project`, `scripts`, etc... subfolder where you store your scripts and other source code now is forced to be added into the namespace path eg.: `ProjectName.Scripts` which ideally despite scripts not needing namespaces, you would want your scripts on the root namespace which is just `ProjectName`.

I was messing around with jetbrains console project and realized there's a feature that allows you to set this in the `sln` file. For instance:

```
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "ConsoleApplication6", "ConsoleApplication6\ConsoleApplication6.csproj", "{D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}"
EndProject
Global
    GlobalSection(SolutionConfigurationPlatforms) = preSolution
        Debug|Any CPU = Debug|Any CPU
        Release|Any CPU = Release|Any CPU
    EndGlobalSection
    GlobalSection(ProjectConfigurationPlatforms) = postSolution
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Debug|Any CPU.Build.0 = Debug|Any CPU
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Release|Any CPU.ActiveCfg = Release|Any CPU
        {D7E527AF-F5E5-45A0-AAE6-B4C46ED0347D}.Release|Any CPU.Build.0 = Release|Any CPU
    EndGlobalSection
EndGlobal
```

Now you could try manually editing this to your project sln, but building in editor complains if you move the .mono, .csproj to the sub folder. 

**Suggestion:**
Allow c# projects to have a sub folder inside the project folder with the same name be the root of our project. This would make separating the c# much cleaner and organize the code base better.

Just a simple checkbox asking if the project source be in a subfolder `ProjectName\ProjectName` and when enabled the editor will look in that folder for the source as the root rather than the root project folder.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
