### ISSUE TITLE
Script attached to sub-scene is not attached to sub-scene's rood node

### ISSUE THREAD

**Issue by pgoral** [godotengine/godot#28301]
**Godot version:** 3.1.stable.official

**Issue description:**
If I have created a "scene from branch" (called B), and than added to it script while editing parent scene (A), then the root element of scene B doesn't contain this script (see attached gif)
![godotbugwithscript](https://user-images.githubusercontent.com/11059246/56502302-1f45de00-6512-11e9-8609-16a2244b149d.gif)

Additionally if that script is added manually to rood node of scene B and then removed from scene B while editing scene (A), the script no longer works
(see attached project)

**Minimal reproduction project:**
[godotBug.zip](https://github.com/godotengine/godot/files/3103465/godotBug.zip)

**Comment by TheDuriel** [comment]
This is entirely expected behavior. By adding the script to the instance. you are editing the instance of the scene, instead of the scene itself. So changes will not carry over to the scene file. And if you later add a script to the scene, the instance will not update because it has already been changed.

**Comment by pgoral** [comment]
Ahh, I understand now. Sorry, I may have been rushing things
