### ISSUE TITLE
Add multi-line text fields in Visual Script

### ISSUE THREAD

**Issue by TheRealCatherine** [godotengine/godot#28315]
**Godot version:**
3.1-stable-win64

**Issue description:**
Currently string inputs can only be single-line (AFAIK). Sometimes users, like myself, want to have a paragraph or more of text in a string field (such as for RPG dialog trees in my case). I think its personally think ok if it only shows as multi-line while editing and shows only the first line while not-editing (maybe with a little up/down arrow at the end to scroll through the lines or something)

Combined with issue #28314 having long string in Visual Script is made basically impossible without resorting to loading strings from some external resource.

![image](https://user-images.githubusercontent.com/31754592/56538695-570c5000-6529-11e9-96cb-44e8c1cceea9.png)

**Steps to reproduce:**
Create a visual script node with a string input. Paste or type a paragraph into that input.

**Comment by Jummit** [comment]
This is more of a GraphNode issue than a VisualScript one.

**Comment by DavidCambre** [comment]
I agree making String settings multiline and/or ignore escape characters should be easily accessible.
Also think we should move this to Proposals

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
