### ISSUE TITLE
Allow drag and drop bound child node properties

### ISSUE THREAD

**Issue by TheRealCatherine** [godotengine/godot#28320]
**Godot version:**
3.1-stable-win64

**Issue description:**
Feature request:
I would like to be able to drag a property from a child node to its parent node, and have the parent node automatically have a "bound" property that maps to the child's property. For eacmple:

https://gyazo.com/0d487caaa48eacb9cd70afc46b91471e

After clicking on NPC in the inspector I would like to see a Sprite secion with a Texture property, that is linked to the Texture property on the NPC/Sprite node (so changing one changes the other)

**Steps to reproduce:**
1) Create a Node
2) Create a Sprite as a child of the Node
3) drag the Texture property from the Inspector to Node in the Scene tree
4) click on Node in the scene tree
5) notice there is no bound property

**Minimal reproduction project:**
None.
If you really want to use the project in the animated .gif above here is the most recent commit as of this report: 
https://gitlab.com/youreperfectstudio/catherines-quest.git 
fc8ff3e4ea5111ae878d538cff89a7b2fb7a0318

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
