### ISSUE TITLE
Implement N-Dimensional OpenSimplexNoise

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#28382]
**Godot version:**
Any Version

**OS/device including version:**
Any OS

**Issue description:**
Currently the `OpenSimplexNoise` implementation supports rigid 2/3/4 dimensional noise.
Since `OpenSimplexNoise` supports N-Dimensional noise, this functionality should be implemented and exposed to users.

Since the current API takes advantage of `Vector2/3` for input, as well as specific function parameters for each dimension, this cannot be mirrored for N-Dimensional noise as there is no `VectorN` class that I am aware of.

I also do not believe that Godot supports arbitrary parameters (`*args, **kwargs` in Python) so unless I am mistaken that is also not an option.

Instead, I propose that the function signature looks like:
`OpenSimplexNoise.get_noise_nd(dimensions : int, position : list[float])`

Where:
`dimensions` is the number of dimensions you wish to get a value for
`position` is a list of floats that are position in each ordered dimension you want to get a value at

If the length of position does not match the specified dimensions, then it can throw an error, or ignore extra positions.

Alternatively, the signature can simply be:
`OpenSimplexNoise.get_noise_nd(position : list[float])`

And it will infer the desired dimension count based on the length of the list.

Is this possible? Are there severe limitations with regards to this in the engine?

Thanks,
-Devin

**Comment by fire** [comment]
Was involved with anl which uses Accidental Noise and implements 3d seamless noise.

Looking at opensimplex noise code, it doesn't work for 6 dimensions.

https://github.com/Xrayez/godot-anl

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
