### ISSUE TITLE
Implement get_image and get_seamless_image for N-dimensions

### ISSUE THREAD

**Issue by DevinPentecost** [godotengine/godot#28384]
Godot version:
Any Version

OS/device including version:
Any OS

Issue description:
Currently the `OpenSimplexNoise` implementation only supports getting a 'snapshot' of noise data in 2D via the `get_image` and `get_seamless_image` functions. Of course, images are inherently 2D, so the language would have to be different most likely.

I propose signatures that look like:
`OpenSimplexNoise.get_noise_data(size : list[float])
OpenSimplexNoise.get_seamless_noise_data(size : list[float])`

Where
`size` is a list of the sizes of the dimensions you wish to get the data for. The number of elements in the list dictates the number of dimensions.

Since an image cannot be used, instead could it return an n-dimensional list of data that is sized by each element in the 'size' parameter? Then the user could query the data frame, assuming they stay within the size boundaries, and do a direct lookup of the data in exchange for more memory usage.

I'm not an expert on OpenSimplexNoise and it's implementation in Godot, nor do I fully understand how to get a seamless noise pattern, so hopefully this isn't impossible to accomplish.

Thanks,
-Devin

**Comment by Xrayez** [comment]
Not necessarily related to `OpenSimplexNoise` but I've done something similar in my noise module (with similar/exact interface):

https://github.com/Xrayez/godot-anl/blob/master/noise.h#L266-L277

Instead, I've added additional methods just for 3D variants. I don't think fetching data bigger than 3D is all that useful for genera usel case.

`get_image_3d` would allow to return `TextureArray` or `Texture3D` which is currently supported by the engine to my knowledge.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
