### ISSUE TITLE
Stripping sensitive code from sources during export

### ISSUE THREAD

**Issue by and3rson** [godotengine/godot#28428]
**Godot version:**
v3.1-stable

**Issue description:**

There are cases when some code is intended only for server instance and clients should not even know about it. For example, requests to internal private API.

It would be great to have possibility of excluding parts of sensitive source code from the exported application based on export feature tags.

**Example usage:**

```gdscript
func _ready():
    set_network_master(1)

master func request_equip_item(slot, item):
    #if linux_server_feature
    send_http_request('http://api.company.vpc/update_inventory', {slot: item})
    #else 
    print('Not a chance.')
    #endif

func equip_clicked(slot, item):
    rpc('request_equip_item', slot, item)
```

This is similar to feature system, but it would remove parts of source code during export, not runtime.

**Comment by fire** [comment]
The tradition ways of securing is this:

* Via an environmental variable
* A secured file (so like in user://)

Why do we need this feature?

**Comment by Calinou** [comment]
> The tradition ways of securing is this:

    Via an environmental variable
    A secured file (so like in user://)

Indeed, that's usually the way modern Web apps do it (see [12-Factor guidelines on configuration](https://12factor.net/config)) :smiley:

**Comment by and3rson** [comment]
Right, but I'm speaking about some very sensitive logic that clients should never know about. Such as the fact that some external APIs are used. Disclosing sensitive code even without credentials is a potential security issue that can be exploited when someone decides to decompile the sources.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
