### ISSUE TITLE
Feature proposal: add collision shape RoundRectShape2D

### ISSUE THREAD

**Issue by Wiering** [godotengine/godot#28422]
When choosing a CollisionShape for objects in a 2D game, I sometimes find myself trying to decide between a Rectangle and a Capsule, and neither is really what I'm looking for. 

The shape I actually need is a rectangle with rounded corners, where you have a property that specifies the size (from 0 to 1/2 of the smallest width or height) that is rounded (probably best to have this as a float: 0.0 would be a Rectangle and 1.0 would make it a Capsule, so that the amount of rounding stays the same when the shape is scaled).

I think this is something that would be widely used, so it would make sense to have it as a standard CollisionShape2D.

**Comment by clayjohn** [comment]
Can you elaborate on the use case for this? A physics for a rounded rectangle are way more expensive to evaluate than either a capsule or a rectangle, so you would need a pretty good reason to justify adding/using it.

**Comment by kkeemmss** [comment]
I was also looking for a rectangle with round corners so i googled to this place. I cold use it for my main character in platformer.
basic enemys can be simple shapes, and 1 caracter wold not slow down game.

**Comment by kkeemmss** [comment]
Little update. So i made good enough aproximation using convex poligonal shape. And i find out that when both player and wall corners ar rounded, its har d to do precise jumping at last moment, becose move_and_slide dose not detect ground when your are sliding down the corner thus control feels broken.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
