### ISSUE TITLE
actions are buffered when window looses focus

### ISSUE THREAD

**Issue by pixelriot** [godotengine/godot#28440]
**Godot version:**
3.1 stable

**OS/device including version:**
tested on Win and Linux.

**Issue description:**
When an action is triggered and held within a _process function and the game window looses focus, the action is buffered and still active. 
Even after the window gains focus again, and no actual input occurs, the action is still "true".

**Steps to reproduce:**
1. open and run the sample project.
2. press and hold one of the arrow keys -> the label displays which butons are pressed and a counter increases.
3. click outside of the window so the window looses focus.
--> the counter still increases and the action is still active.

**Minimal reproduction project:**

[action_window_focus.zip](https://github.com/godotengine/godot/files/3120234/action_window_focus.zip)

**Comment by groud** [comment]
That might be expected behavior though.

**Comment by pixelriot** [comment]
It feels somehow wrong.

For example when I have a player character and hold the right arrow key to make him move right and for whatever reason, the window looses focus, then the player character will continue walking right and probably run into an enemy or fall into a pit.

Is there a way to clear the buffer? Or a workaround?
Let's say in "_notification(what)" I can check if the window is off focus and then clear all actions.

**Comment by Zylann** [comment]
This is a common byproduct of focus change, I have seen this behavior in some other games. However I agree that unless keyboard input is retrieved directly (i.e raw input without window manager events), keys should be considered as unpressed if the game looses focus. I can't see a reason why leaking key states  would be wanted.

**Comment by avencherus** [comment]
@pixelriot I haven't tried much with the direct API, because I process the input events and store results in my own controller class.  (Because I need to do some extra work to smooth things out.)

While having things stored there, I have been able to use the notifications from https://docs.godotengine.org/en/3.1/classes/class_mainloop.html

`NOTIFICATION_WM_FOCUS_IN`
`NOTIFICATION_WM_FOCUS_OUT`

I use these to clear my controls.  It so far is working fine, but off the top of my head I'm couldn't suggest how to tailor an approach using logic more directly stemming out of `_input()`.  

There has also been work recently with this pending pull request:  https://github.com/godotengine/godot/pull/28061

Haven't tested it yet myself, so I don't know exactly what it does.  But if you do your own builds you might want to cherry-pick it and see if it works for your situation.

**Comment by pixelriot** [comment]
Thanks @avencherus,

this worked for me (maybe it helps someone else):
```
 func _notification(what):
	if what == MainLoop.NOTIFICATION_WM_FOCUS_IN:
		for ac in ["ui_left", "ui_right", "ui_up", "ui_down"]:
			Input.action_release(ac) #clear input
	elif what == MainLoop.NOTIFICATION_WM_FOCUS_OUT:
		if !get_tree().is_paused(): #virtual press pause button
			var new_action = InputEventAction.new()
			new_action.pressed = true
			new_action.action = "ui_cancel"
			get_tree().input_event(new_action)
```

**Comment by Xrayez** [comment]
> That might be expected behavior though.

https://github.com/godotengine/godot/pull/30792#issuecomment-514587093

This indeed could be a problem but I haven't reached that point yet to verify that, so just referencing this here for now.
