### ISSUE TITLE
Support for One-shot play for AnimatedTexture

### ISSUE THREAD

**Issue by MuffinManKen** [godotengine/godot#28450]
I'm messing around with AnimatedTexture as a way to make UIs more interesting. For example, when you check a box, the arrow could draw rather just just appearing. A button that's enabled could flash once to signal to the player that it's available.

AnimatedTexture only cycles, rather than being a 1-shot animation but it was pretty easy to add a "one shot" flag to the C++ class.

The problem I'm having is that I don't see a way to make the animation start at the first frame when shown. So sometimes it starts in the middle and sometimes at the end.

Any ideas?

(I know I could fake this with something Sprite-based, but being able to do this via AnimatedTexture directly would be very handy for making better UIs)

**Comment by guilhermefelipecgs** [comment]
I guess you just need to call `set_frame(0)` when the one shot happens.

https://github.com/godotengine/godot/blob/260530f01caa8ea3e2fb7bfda04f4bd718ae14f5/scene/2d/animated_sprite.cpp#L497

**Comment by MuffinManKen** [comment]
AnimatedTexture , not AnimatedSprite.

I need a clean way for it to happen so that they can be used by Controls in a seamless manner.

**Comment by guilhermefelipecgs** [comment]
Yeah, I read it wrong. In that case I'm not sure what is the best way.

**Comment by guilhermefelipecgs** [comment]
I guess you already tried to set `current_frame` to `0`, right?

**Comment by MuffinManKen** [comment]
I see 2 options:
1) Have a virtual function on Texture that's a NOP for anything but AnimatedTexture
2) Have Controls know about AnimatedTexture and call that function when appropriate

#1 seems bad since it's not a core feature of a Texture (or even most of Texture's descendants) so all of those classes get a useless virtual method
#2 seems like a bit of a dirty hack, but it's at least more contained.

I'm not thrilled with either solution.

**Comment by guilhermefelipecgs** [comment]
Yes, I was thinking about the second option that you pointed out. Maybe not the best solution. If I find a better way, I'll let you know.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(btw, you can use AnimationPlayer for this specific case. Just keyframe `texture` property in your UI node)
