### ISSUE TITLE
Give AnimatedSprite a GetRect method that takes frame name & frame index values

### ISSUE THREAD

**Issue by exts** [godotengine/godot#28497]
**Godot version:**
3.1

**OS/device including version:**
Win10/64

**Issue description:**
Currently you have to manually get a animated sprite frame's texture for a specific index then create your own rect2. Why not simplify this so there's less steps for example:

C#

```cs
public Rect2 GetRect()
{
    var sprite = GetNode<AnimatedSprite>("Sprite");
    var texture = sprite.Frames.GetFrame("default", 0);
    return new Rect2(sprite.Position, texture.GetSize());
}
```

vs

```cs
GetNode<AnimatedSprite>("Sprite").GetRect("default", 0);
```

**Note**

`Sprite` has a GetRect() method, which is why I bring this up.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
