### ISSUE TITLE
Enable "allowBackup" in the AndroidManifest, so android app data gets backed up by default

### ISSUE THREAD

**Issue by wombatstampede** [godotengine/godot#28509]
**Godot version:**
Godot 3.1 (the AndroidManifest moved meanwhile to java in the master-branch)

**OS/device including version:**
Android (Backup is available starting from Android 6.0)

**Issue description:**
For unknown reason autp-backup is disabled in the Android Manifest:
https://github.com/godotengine/godot/blob/master/platform/android/java/AndroidManifest.xml

with the key/value: android:allowBackup = "false"

I see that this is already the case for a longer time:
https://godotengine.org/qa/8503/godot-games-do-not-show-up-on-android-system-backups

I see no reason why the data of godot apps shouldn't be backed up by default. Users normally expect their data to be backed up when they enable a backup and will be very, very dissapointed if the data is lost after a restore (i.e. when moving to another device).

My proposal: simply remove the key "android:allowBackup" from the Manifest or set it to true.

And yes, naturally, you can do your own android build. But I would consider this as expected default behaviour.

**Comment by volzhs** [comment]
with `android:allowBackup`, the backed up data will be restored even while developing & testing game.
this will cause some problems.
let's say the game data format is changed while developing.
then uninstall and reinstall on android device, old data is restored and game might be crashed.
need to find a way to ignore or remove old data at starting game.

**Comment by wombatstampede** [comment]
Thank you for telling me the reason! :-)

Ok, if it is a problem while developing & testing the game then it would be probably helpful to disable the backup only in the debug template.

Apart from that (regarding release versions) I'd think that android would check the game version and only restore (which I thought is only done when the user explicitly restores data) when the game version is same or newer.

**Comment by volzhs** [comment]
I couldn't find about the version related. but i think only restore with same version is useless.
it is more like not backing up.

**Comment by wombatstampede** [comment]
Yes, i just checked and also couldn't find anything about version checking on restore.

Restoring with the same (or newer) version would make sense. This is the case when you migrate to another device or when you uninstall and re-install an app.

My guess is that google at least assumes that the app will be same or newer version when you restore the data because the play store will normally (!) only offer the newest version for install. But this isn't always true. I.e. when you install a version from the beta channel, uninstall that and install the previous release version.

Ok, so enabling the autobackup "allowBackup" maybe isn't foolproof depending on how people implement their save data. Maybe it'll be easier to enable allowBackup with some plugin in the new 3.2 plugin system ("Custom build") if that allows not only adding lines to the manifest but also changing existing manifest content.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
