### ISSUE TITLE
Add Hierarchy visualization of the hierarchy of functions of a script.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#28521]
I think It would be very nice to be able to visualize a script in terms of some Tree Node structure similar to the Scene Node Tree.

Of course I'm not talking about a visual scripting tool, just a way to visualize how your script functions are layered and how they call each other.

Maybe looking like unreal blueprints where functions are just boxes and the input and output are just threads linking the function boxes, maybe they can be put in a sort of node hierarchy depending on who calls who functions, maybe looking like Blender node compositor.

Of course this would be just a visualizer of your code.

**Comment by Zylann** [comment]
If there was a way for a plugin to get the AST of the opened script, that would be a fun tool to make.

**Comment by bojidar-bg** [comment]
There was #23807.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
