### ISSUE TITLE
RigidBody2D Allow Gravity vector to be set for each RigidBody2D individually

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#28524]
**Godot version:**
3.1 stable

**OS/device including version:**
Win 7

**Issue description:**
Having downward gravity force is only useful for 2D games with "platformer" type of visual perspective and physics. There are endless other 2D game designs that could benefit from RigidBodies2Ds. However setting them up for other game mechanics is by far not as straight forward as it could be if Godot would allow to quickly and easily change the Gravity Vector of any RigidBody2D.
Currently it is only possible to either change and set the Gravity vector globally for all RigidBody2Ds in the project in the Project settings under Physics > 2D > Default Gravity Vector, or disable it completely with custom_integrator set to true and writing your own forces.

Ideally, I would like to have a setting in the Inspector that shows the current "Gravity Vector", but is greyed out. Above it, a toggle called "Use global Gravity Vector" with a checkbox.
If unchecked, the "current Gravity Vector" becomes colored and I can set it to either a "Vector2", "point position", "mouse position" or "Node position" - click to select node or drag and drop node.

Yes, I know you can do this with custom_integrator set to true and write some lines of code to make it work. Consider prototyping or beginners please. It took me 2hs alone to find out that I cannot directly or easily change the Gravity Vector per RigidBody2D. + adding time to write your own forces.
This would greatly improve the speed in which people could pic up and start experimenting with Godots RigidBodies doing other stuff than just platformer physics.

**Steps to reproduce:**
Add a RigidBody2D to your scene, add a Sprite2D with a planet texture, try to make it have gravity ... This one is kindergarten example, I think it should be kindergarten to implement as well.

**Comment by aaronfranke** [comment]
I don't think this is worth implementing. It would mean that every object would have to store more information about how it behaves gravity. Neither Unity nor Unreal have per-object gravity.

I don't see why you can't just implement it manually using `add_force()`.

**Comment by golddotasksquestions** [comment]
I spend a few hours trying to do just that and eventually gave up on using Rigid bodies for now.

**Comment by KoBeWi** [comment]
It is possible to use Area2Ds as gravity overrides. It's a bit hacky, but you can attach an Area2D to your RigidBody2D (i.e. as a child) and give it 1-pixel-big collider and some custom gravity vector. The body will behave like with different gravity.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
