### ISSUE TITLE
3.1.1 AudioServer is missing methods used in the bpm_sync demo

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#28553]
**Godot version:**
3.1.1

**OS/device including version:**
MXLinux 18

**Issue description:**
The changelog mentioned that the new audio features from 3.2 were backported but AudioServer is missing get_time_to_next_mix,get_output_latency and get_time_since_last_mix

**Comment by clayjohn** [comment]
These were added after 3.1.1, if they are being backported you should find them in 3.1.2.

**Comment by akien-mga** [comment]
I don't plan to backport those unless there's a really strong demand; IMO backporting the first batch of new audio features from 3.2 was a mistake, as such features typically take a few iterations to mature and that's why they're developed in the master branch.

If there's a lot of demand for having those in 3.1.x I can reconsider, but as 3.2 is just around the corner, I don't think spending time figuring out what to backport safely for these features is worth the effort.

**Comment by clemens-tolboom** [comment]
I was about to report this too. Found it through https://docs.godotengine.org/en/latest/tutorials/audio/sync_with_audio.html but I should have checked my version first :-/

Waiting for 3.2 :-) ... downloaded 3.2-beta4 from https://downloads.tuxfamily.org/godotengine/3.2/
