### ISSUE TITLE
Hide non-functional editor locales due to missing RTL/font shaping support

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#28577]
As explained in https://github.com/godotengine/godot/issues/982 and https://github.com/godotengine/godot/issues/9961, Godot currently doesn't support RTL and font shaping, which is required to display some languages correctly (such as Arabic).

I think it'd result in a better user experience if those languages were removed from the list of available editor languages until Godot supports the required features. The locale files would remain available in the repository, so that people can still contribute to translations on Weblate (and developers could test RTL/font shaping support using those locale files).

**Comment by akien-mga** [comment]
That's a good idea, since those locales would get automatically loaded otherwise when matching the system locale, but are not usable as is.

We'd need to list what locales exactly need to be disabled temporarily. I'll give it a try based on the locales for which we current have translation files.

Not supported:
- Arabic [ar]
- Persian [fa]
- Hebrew [he]
- Hindi [hi] (Devanagari)
- Urdu (Pakistan) [ur_PK]

Partial support:
- Thai [th], some fonts render OK, others don't, see #28371

Not sure:
- [Malay](https://en.wikipedia.org/wiki/Malay_language) [ms] (seems to support both Latin and Arabic scripts... the few strings we have translated so far seem in Latin script)

Not supported by current font, *might* also need font shaping. For those we should first check how they render when you have a font that supports them, and see if we should add such fallbacks fonts for the editor:
- [Bengali](https://en.wikipedia.org/wiki/Bengali_language) [bn]
- [Malayalam](https://en.wikipedia.org/wiki/Malayalam) [ml]
- [Sinhala](https://en.wikipedia.org/wiki/Sinhala_language) [si]
- [Tamil](https://en.wikipedia.org/wiki/Tamil_language) [ta]
- [Telugu](https://en.wikipedia.org/wiki/Telugu_language) [te]

**Comment by bruvzg** [comment]
AFAIK Bengali, Malayalam, Tamil, Telugu (and other Brahmic scripts) all use some composite glyphs and do require shaping on some level. I can't tell how broken rendering is, but it's definitely should have some problems at least to the same extent as Thai (misplaced and overlapping diacritics).

**Comment by bruvzg** [comment]
Here are rendering samples, top to bottom: **Godot + [gdtl module](https://github.com/bruvzg/godot_tl), [AAT](https://en.wikipedia.org/wiki/Apple_Advanced_Typography), Godot**:

* Bengali (broken)
![bn](https://user-images.githubusercontent.com/7645683/57074146-b4538e80-6ceb-11e9-832f-fe116e0239a0.png)

* Malayalam (broken)
![mn](https://user-images.githubusercontent.com/7645683/57074231-f7adfd00-6ceb-11e9-9291-1d075c4cdb44.png)

* Sinhala (broken)
![si](https://user-images.githubusercontent.com/7645683/57074280-19a77f80-6cec-11e9-97c7-c01805df22fe.png)

* Tamil (broken)
![ta](https://user-images.githubusercontent.com/7645683/57074312-30e66d00-6cec-11e9-8e2a-c05b3cd3479e.png)

* Telugu (broken)
![te](https://user-images.githubusercontent.com/7645683/57074371-4e1b3b80-6cec-11e9-9573-7766a29743da.png)

**Comment by akien-mga** [comment]
Thanks for the thorough test, I updated my comment to clarify that those 5 are also broken.
