### ISSUE TITLE
Add option to simulate network conditions like lag and packet loss

### ISSUE THREAD

**Issue by megalike** [godotengine/godot#28582]
Require some variable to simulate network condition for development and testing stable multiplayer algorithm and approach.

It's analog: net_packetextralag && net_packetlossrate from CryEngine, net_fakelag && net_fakeloss from Valve Source, PkgLag && PkgLoss from Unreal

**Comment by slapin** [comment]
@Calinou
This is not about variable, it is about packet loss patterns simulation. Only makes sense for UDP networks. Can be done using external tools though.
Please change topic, otherwise it is very confusing.

**Comment by megalike** [comment]
For reduce network latency in gamedev use only UDP (i mean real time game). External tool is not a handy way and besides that set different network condition for each client is a problem. What if i say about some like a random lag (i forgot add it to proposal) ? Do you think it's a simple to find a tool with multiplatform support and open source which is satisfy it ? How about easy to use ? How about add initial network condition for testing (imagine you have a team of 10+ QA and some branch with network depended feature like a server authoritative movement etc.) ? From my point of view exist only one best way and it's primary way in other engine and already proven by time. Thanks.

**Comment by slapin** [comment]
where I live many ISPs block UDP completely, but many MP games still work
so I guess TCP as also common option. But your request is not about variables,
but about network testing, please make topic clear about this. I work on Linix
and it have extensive network failure si,ulation tools to test apps.
I'm not against
adding some network error injector in Godot, but that will probably will be most
low priority ever. I think you better try to find some external tools
if you have
a problem at hand. Most Godot developers do not have experience in the area,
so I guess that will require outside contribution and you need to convince
developers to put such a feaure in the roadmap. Also I guess this could be
implemented as "gdnative" thing, but somethings tells me it is not possible
this way that easily. Another thing you will need to properly test is packet
reordering and traffic replayers. So I still bet more on external
tools if I were you.

**Comment by megalike** [comment]
Real time games (i mean AAA games) using UDP only.
No matter it's TCP or UDP at all, it's about network conditions.
I want to do this feature in the near future by myself, because it's absolutely require as i mention before. And it's not a problem if it's get a low priority. It's should only approve now in community to see it's value.

**Comment by megalike** [comment]
Yeah anyway, but maybe it can be useful for other. 
For me it mean to try do not make a fast but not a better solution if i trap. And i spend more time to find a better solution to solve some problem and stick to guideline.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
