### ISSUE TITLE
Script text editor shortcuts

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#28590]
**Godot version:**
3.1 stable

**Issue description:**
The default shortcuts used by script editor really bother me. Some of them are different than standard conventions.

Two most important proposals, based on pretty much any text editor:
Go to line - Ctrl+L -> Ctrl+G
Replace - Ctrl+R -> Ctrl+H

And some additional proposals based on Notepad++:
~~Duplicate line - Ctrl+B -> Ctrl+D~~
Remove line - Ctrl+Shift+K -> Ctrl+L
Toggle comment - Ctrl+K -> Ctrl+Q

I know I can just change them and that's what I did long ago, but I wanted to use Ctrl+B for thing I'm implementing and personally I think that Ctrl+D makes more sense for duplication.

Anyone agrees about these new shortcuts, or at least the first two? Maybe someone has other/more proposals?

EDIT:
Ctrl+B was ninja-remapped with a merge of #28218 (it's now used for bookmarks)

**Comment by Calinou** [comment]
> Toggle comment - Ctrl+K -> Ctrl+Q

<kbd>Ctrl + Q</kbd> is already used to quit the editor :wink:

**Comment by KoBeWi** [comment]
> Ctrl + Q is already used to quit the editor 😉

But still works perfectly in the code editor, although you lose ability to quit from there (if you for some reason don't use Alt+F4). I'd say that this one is the least important, as it makes the most sense.

**Comment by akien-mga** [comment]
> Two most important proposals, based on pretty much any text editor:

What "any text editor" do you refer to?

In the ones I use, I have:

- Replace: Ctrl+R (Kate), Ctrl+F for hybrid Find/Replace (QtCreator), Ctrl+\ or Ctrl+W + Ctrl+R (nano)
- Go to Line: Ctrl+G (Kate), Ctrl+L (QtCreator), Ctrl+_ (nano)
- Duplicate Line: Ctrl+Alt+Up/Down (Kate), no binding in QtCreator or nano. Ctrl+D is Delete in QtCreator and Comment in Kate
- Remove Line: Ctrl+K (Kate), Ctrl+D (QtCreator), Cut Line is Ctrl+K (nano)
- Toggle Comment: Ctrl+/ (Kate), Ctrl+/ (QtCreator)

I think this shows already that there is no "pretty much any text editor" standard. That's why we can rebind those to our liking.

**Comment by KoBeWi** [comment]
> Which "any text editor" do you refer to?

Windows Notepad, WordPad, Microsoft Word, Google Docs, Notepad++/Scintilla, Visual Studio (Code), CodeBlocks, JetBrains... Basically every popular code editor.

I was referring only to Replace/Go to line in that sentence, the other 3 shortcuts are more varied. HOWEVER, Ctrl+D is consistent with it's behavior in other parts of editor - duplicating stuff.

**Comment by Zylann** [comment]
I've never seen Ctrl+Q used to toggle comments (note, on Visual Studio it's Ctrl+K followed by either C or U)

**Comment by MaaaxiKing** [comment]
You shouldn't copy other programs' functions/shortcuts if they don't make sense. In my view, other programs should go for the shortcuts from Godot 😃

**Comment by KoBeWi** [comment]
I have so many shortcuts customized that it doesn't matter to me anymore.
