### ISSUE TITLE
Horizontal flip of tilemap cell is not working as expected

### ISSUE THREAD

**Issue by CngKO** [godotengine/godot#28610]
**Godot version:**
3.1.1 official

**OS/device including version:**
Windows 10.0.17134 Build 17134

**Issue description:**
Horizontally flipping tilemap cell changes the position of the tile by half of its width

**Steps to reproduce:**
In the project attached below, notice that the light-green tilemap cell is not placed where it should be.  Remove horizontal flip and notice that it fits into place.

**Minimal reproduction project:**
[hflip-tilemap.zip](https://github.com/godotengine/godot/files/3138406/hflip-tilemap.zip)

**Comment by groud** [comment]
Note: the bug happens only with isometric tiles.

**Comment by Ranoller** [comment]
Well, not only with isometric:
https://github.com/godotengine/godot/issues/22989
https://github.com/godotengine/godot/issues/28206
https://github.com/godotengine/godot/issues/15249

Problem is displacing textures with is not needed, a dessign problem, not easy fixable, i try and fail. This bug needs an expert programmer or directly reduz, because too many people touched in the past tile_map.cpp with different ideas about texture offset, origin point, etc... so... at the day, tilemap is a chaos and this kind of issue will be very recursive.

**Comment by CngKO** [comment]
@reduz, @Ranoller suggests that tile_map.cpp may need a rewrite.  What do you think?
