### ISSUE TITLE
Feature Request: Simplify the creation of multi-dimensional arrays

### ISSUE THREAD

**Issue by ChipChance** [godotengine/godot#28631]
Making arrays in GDScript is easy: var MyArray = []

But what if a variable needs to hold MULTIPLE bits of information (like X, Y, Z, Color, Packets, etc...) which would be much easier contained like this:

MyArray[X][Y][Z][Color][Pkt1]...

Currently, the process of doing this involves multiple lines of code:

for x in range(MAX_X): # This is the "X" dimension [width]
Map.append([])
Map[x]=[]
for y in range(MAX_Y): # This is the "Y" dimension [height]
Map[x].append([])
Map[x][y]=[]
#etc...

I'd MUCH rather like to see this defined as:

var Map = [][][][][]
or something to that effect.

Please consider.

Many thanks! (I LOVE the engine, by the way!!!)

    Mike

**Comment by avencherus** [comment]
If I understand your post correctly, this can already be done without append.

`var my_array = [[],[]]`

Would create two empty arrays in the first two elements of the initial array.

What might be nice to see in the future is a one line way of sizing and filling an array with given values.

**Comment by aaronfranke** [comment]
I do like the `[][][]` syntax proposal, but I should also mention the C# way of `[,,]`.

**Comment by akien-mga** [comment]
I don't understand how any of the proposed syntaxes actually define dimensions for the n-dimensional array. What would `[][][]` be? A 3x3x3 3D array? If so why should it be a square matrix? What would be the syntax for a non-square 3D array?

**Comment by Zylann** [comment]
Why not have `Grid2D` and `Grid3D` objects?

**Comment by TheDuriel** [comment]
The ability to use Vector and Array keys for dictionaries, and the fact that dictionaries actually outperform multi level arrays at depths above 2, makes me wonder if this is really necessary.

**Comment by Zylann** [comment]
@TheDuriel they outperform only in GDScript specifically though, precisely because in GDScript it's harder to make an optimal grid with only arrays (which is the most sensible choice for a fixed-size, contiguous data set). Although if you're fine in having to track the size of that grid separately and take care of floating-point mistakes, sure dictionaries are fine.

**Comment by aaronfranke** [comment]
@akien-mga `[][][]` would mean a 3D array with undefined dimensions, but `[5][6][7]` would be a 5x6x7 3D array. The way C# does it is `int[,,] myArr = new int[5, 6, 7];` so we could do something like `var myArr = int[5][6][7];`

**Comment by Zylann** [comment]
@aaronfranke `var myArr = int[5][6][7]` suggests a typed multi-dimensional array though. Godot only has `Array` [of variants] and `PoolTypeArrays`.

**Comment by aaronfranke** [comment]
Are `PoolTypeArray`s variants themselves? We could have `Array` of `Array` of `PoolTypeArray` if typing is desired, or just `Array` of `Array` of `Array`.

**Comment by Zylann** [comment]
@aaronfranke maybe... at this point I feel this is getting a bit complicated for just *one* of the ways to accomplish multidimensional arrays *without* support from an actual grid type (so you are still left with no straightforward access to its bounds and no guarantee to stay consistent past the declaration)

**Comment by bojidar-bg** [comment]
Note that `[3][2]` is currently valid syntax, which takes the 2-th (0-based) element from `[3]`.
Also `[3, 2]` is valid syntax for an array of two elements.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Xrayez** [comment]
For those stumbling upon the issue, some use cases can be solved by [`VariantMap`](https://goost.readthedocs.io/en/latest/classes/class_variantmap.html) class in [Goost](https://goostengine.github.io/). It's not quite the same as multi-dimensional array and only handles 2D, but works alright for most use cases I had to stumble upon. For 3D, I guess `VariantGrid` could be created in the future, but I haven't needed this personally.

The reason why I haven't named the class as `Grid2D` is because this could be falsely interpreted as a `Control` class. Also, `VariantMap` better reflects that it works similarly to classes such as `BitMap` (which is basically specialized class that handles booleans), or `Image` which is a specialized class that handles pixels. `VariantMap` suggests that it handles everything.

Unlike plain `Dictionary` with `Vector2/3` keys, a class allows to process the data in a much more convenient and robust way (for example, when you want to make sure that you don't go outside the dimensions). Later it makes sense to add other useful functions.
