### ISSUE TITLE
Implement new numeric-type distinction in API JSON in GDExtension

### ISSUE THREAD

**Issue by karroffel** [godotengine/godot#28645]
Pull request #28423 added metadata to numeric types, those could be used in the NativeScript API JSON file.

@neikeq anything else that needs to be considered? Do the ptrcalls have to be adapted and take all of those different types instead of the current up-casted types?

**Comment by neikeq** [comment]
> Do the ptrcalls have to be adapted and take all of those different types instead of the current up-casted types?

No, this didn't change. Let me put an example to make it clear. Let's consider the method `store_16` in `File`. The method declaration in the engine is the following:

``` C++
void store_16(uint16_t p_dest);
```

The current implementation in `godot-cpp` is this:

``` C++
void File::store_16(const int64_t value) {
	static godot_method_bind *mb = NULL;
	if (mb == NULL) {
		mb = godot::api->godot_method_bind_get_method("_File", "store_16");
	}
	___godot_icall_void_int(mb, (godot_object *) this, value);
}
```


As you can see, the method receives `int64_t` for the parameter instead of `uint16_t`. You could use this new metadata information to generate the method with `uint16_t` for the parameter. The variable that is passed to `ptrcall` still has to be of type `int64_t` as defined in [core/method_ptrcall.h](https://github.com/godotengine/godot/blob/master/core/method_ptrcall.h):


``` C++
void File::store_16(const uint16_t value) {
	static godot_method_bind *mb = NULL;
	if (mb == NULL) {
		mb = godot::api->godot_method_bind_get_method("_File", "store_16");
	}
        int64_t value_aux = value; // store it in a variable of the type ptrcall expects
	___godot_icall_void_int(mb, (godot_object *) this, value_aux);
}
```

As to why `ptrcall` requires `int64_t` for all integral types, this was introduced by @endragor in https://github.com/godotengine/godot/commit/30176b0bb1d6083ecf8ce9e6bfca0dce9240a634 (previously it was `int` for all). The commit message says the reason is because the specific int size information is not provided, so maybe this can be changed now that we do provide it?

**Comment by Calinou** [comment]
GDNative was removed in favor of GDExtension in 4.0, closing.

**Comment by Calinou** [comment]
> Does API json include the numeric type information in it? Otherwise this shouldn't be closed.

I don't think so, but a new issue should be opened for this since this is now about GDExtension.

**Comment by neikeq** [comment]
The switch to GDExtension has little to no impact on this. Just change GDNative to GDExtension in the title.

**Comment by reduz** [comment]
This has already been implemented in the extension API

**Comment by Calinou** [comment]
Closing per the above comment.
