### ISSUE TITLE
External PVRTC encoders don't work

### ISSUE THREAD

**Issue by DrMoriarty** [godotengine/godot#28669]
**Godot version:**

Godot 3.1.2-devel

**OS/device including version:**

MacOSX 10.13.6

**Issue description:**

I'm trying to use external pvrtc encoder. I set `filesystem/import/pvrtc_texture_tool = /usr/local/bin/TexturePacker`. When I try to reimport vram compressed texture it shows me:
```
TexturePacker:: error: Failed to load image: /Users/vasya/projects/match3/ga3/-i
TexturePacker:: error: Failed to load image: /Users/vasya/projects/match3/ga3/-o
TexturePacker:: error: File not found: /Users/vasya/Library/Caches/Godot/_tmp_dst_img.pvr
TexturePacker:: error: Failed to load image: /Users/vasya/projects/match3/ga3/-f
TexturePacker:: error: Failed to load image: /Users/vasya/projects/match3/ga3/PVRTC4
ERROR: _load: Failed loading resource: /Users/vasya/Library/Caches/Godot/_tmp_dst_img.pvr
   At: core/io/resource_loader.cpp:285.
ERROR: _compress_image: Can't load back converted image using PVRTC tool: /Users/vasya/Library/Caches/Godot/_tmp_dst_img.pvr
   At: editor/pvrtc_compress.cpp:103.
```

I change `filesystem/import/pvrtc_texture_tool = /Applications/Imagination/PowerVR_Graphics/PowerVR_Tools/PVRTexTool/CLI/OSX_x86/PVRTexToolCLI`. When I reimport vram compressed texture it shows:
```
Error: Invalid values chosen for Encode Format. Please see -help for valid parameters.
ERROR: _load: Failed loading resource: /Users/vasya/Library/Caches/Godot/_tmp_dst_img.pvr
   At: core/io/resource_loader.cpp:285.
ERROR: _compress_image: Can't load back converted image using PVRTC tool: /Users/vasya/Library/Caches/Godot/_tmp_dst_img.pvr
   At: editor/pvrtc_compress.cpp:103.
```

What specific external pvrtc encoder implied in this field? Maybe we should setup all necessary command line parameters somewhere near executable file?

**Steps to reproduce:**

Use any external pvrtc encoder except the implied by core developers (I don't know the right answer).

**Minimal reproduction project:**

**Comment by norton-corbett** [comment]
It looks like this is meant to work with PVRTexToolCLI because the arguments being supplied in [pvrtc_compress.cpp](https://github.com/godotengine/godot/blob/master/editor/pvrtc_compress.cpp) are almost correct, but wrong.

-f argument should be `PVRTC2_2 ` for 2bpp, `PVRTC2_4` for 4bpp. For ETC2 there is the option of `ETC2_RGB`, `ETC2_RGBA`, or `ETC2_RGB_A1`

In the case of `filesystem/import/pvrtc_fast_conversion`, the `-pvrtcfast` should instead be `-q pvrtcfast`

And the `-m` options expects a parameter for the number of mipmap levels.

The second problem is that [ResourceFormatPVR::load](https://github.com/godotengine/godot/blob/master/modules/pvr/texture_loader_pvr.cpp#L54) is not reading back the resulting *.pvr file properly so it fails when reading the header.

This format is specified here:
https://docs.imgtec.com/PVR_File_Format_Specification/topics/pvr_header_format.html

**Comment by Calinou** [comment]
The PVRTC option was probably used a long time ago by the original Godot developers (before it was open sourced). This is probably why the arguments are currently incorrect :slightly_smiling_face:

Is there still an use case in using PVRTC on iOS today? If not, support for it should be removed entirely.
