### ISSUE TITLE
Curve Texture Editor Iemprovments

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#28664]
I notice its not possible to increase the length of the handles in the curve editor. It would be nice if there was a key (ctrl or alt) that would allow the user to increase the length of the bezier handles.

Also there needs to be a way to increase the size of the editor, possibly even to open it where the 3D/Scripting main window is to allow for fine control. Currently we can make it wide, but cannot increase the height.

**Comment by Gibbz** [comment]
Also an option to preview the curve as a repeating loop to check the in's and out's of the curve :)

**Comment by Zylann** [comment]
Note that a curve cannot have overhangs, and allowing to make handles longer would no longuer guarantee that (it's the same in Unity3D).

**Comment by Gibbz** [comment]
It could be useful to have this open where the animation editor lives. As I know there are curves in there and that system works pretty well

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
