### ISSUE TITLE
Drawing sprites in grid introduces rendering artefacts

### ISSUE THREAD

**Issue by navaronbracke** [godotengine/godot#28674]
Godot 3.1 stable

System Specs
Windows 10 version 10.0.17134
CPU: i7-4790 
64 bit, x64 processor 
GPU: GTX 1070, Driver Version: 430.39

Description:
I Was getting started in a godot project. I needed a custom replacement for TileMap,
that holds more than just a texture/occluder. I wrote a Chunk class, to draw sprites in a grid instead. When trying to test out my new class I noticed that the sprites were being drawn BUT
it also had weird artefacts when more than 1 tile is drawn. I included a sample project to show the issue.

Reproduction Steps:
- open the sample project
- modify Start.gd(add/remove calls to set_tile)
- run Start.tscn to see what is drawn
[testProject.zip](https://github.com/godotengine/godot/files/3144281/testProject.zip)

**Comment by clayjohn** [comment]
You are drawing the sprite and you are drawing the sprites texture on top of the sprite. The way a sprite node works is you assign it a texture and that texture is drawn at the position you place the sprite. You were also using the custom drawing API to draw another texture on top of your sprite. The reason that you were getting two is because in your sprite node you used the variable ``texture`` to create and load your texture, however that is a property of the Sprite so it assigned that texture to the sprite itself. 

There are a couple solutions 1) make Tile a Node2D 2) remove the custom drawing code

**Comment by navaronbracke** [comment]
@clayjohn Fixed it, removed the custom _draw() and used set_offset to align the sprite.
