### ISSUE TITLE
Proposal: PathFollow2D unit_offset for individual path nodes

### ISSUE THREAD

**Issue by yesitsmattharris** [godotengine/godot#28673]
Exposing the path nodes when setting / getting the offset of a PathFollow2D's children could be very useful.

Currently, get_unit_offset() returns a value of 0 - 1 (first to last vertex). Although extremely useful, it could be good to have something such as:

`bool has_passed_vertex(int vertex_index):`
 ` if offset is >= path node argument supplied then return true`
`  else false`

or perhaps:

`int get_current_vertex():`
 ` find closest path node <= current offset and return the index`

As an example of where this can be used, say you want a character / item to move along a Path2D, then stop and do something else (or wait for player input), and then continue. This would save having to use magic numbers for individual scenarios, or multiple Path2Ds.

**Comment by golddotasksquestions** [comment]
This would also be a good foundation to eventually have branching paths.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
