### ISSUE TITLE
Hard to select objects in 3D when all gizmos(position, rotation, scale) are shown

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#28810]
**Godot version:**
3.1.1

**OS/device including version:**
Ubuntu 19.04

**Issue description:**
When I try to select multiple objects in 3D, then sometimes gizmos steal mouse clicks and hide some models behind.

I think that all gizmos from Q,  W, E, R shortcuts, should have option to disable(like grid and other gizmos)

Empty scene with only all gizmos(Q in keyboard) contains almost 6000 vertices!
![Zrzut ekranu z 2019-05-10 18-25-55](https://user-images.githubusercontent.com/41945903/57542165-3168ae80-7351-11e9-92bd-fdce3081bd06.png)

**Steps to reproduce:**
https://streamable.com/0wprg

**Comment by Calinou** [comment]
> Empty scene with only all gizmos(Q in keyboard) contains almost 6000 vertices!

Curved surfaces are always going to require a fair bit of surfaces to look smooth :wink:

Keep in the mind the reported number of vertices is *at least* doubled due to Godot's rendering pipeline.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
