### ISSUE TITLE
AudioStreamSample.data compatibility with AudioStreamGeneratorPlayback

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#28820]
**Godot version:**
3.1.1 stable

**Issue description:**
This is a feature request.  With the new `AudioStreamGenerator`, it is relatively straightforward to create simple waveform generators.  However, if one wishes to play sample data, it must first be converted to the format that the stream generator wants (An array of Vec2s containing the stereo frame data).  It would be helpful for users rather than having to read in AudioStreamSample.data() directly (and having to do some bit-shifting as well as a signed conversion for 16-bit samples) then manually caching that data, that `AudioStreamSample` had a convenience function which did this for you.  It might be even nicer if AudioStreamSample cached this behind the scenes so that repeated calls to the data would fetch fast unless the `data` has changed.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
