### ISSUE TITLE
Godot as Windows UI Control (Win10 WinUI) 

### ISSUE THREAD

**Issue by GeorgeS2019** [godotengine/godot#28830]
**Godot version:3.x 

**OS/device including version: Win10 WinUI

WinUI  (Windows UI Control for UWP) is key to future Microsoft cutting edge 3D user interface illustrated by Hololens 2/MMTK2

If it is possible to create Windows UI Control from Godot, this will address the gap or lack of open source 3D control for existing UWP 3D app development that is fundamental for Microsoft Hololens2/MMTK2

**Comment by aaronfranke** [comment]
To clarify, is this about creating UIs in AR? Please explain why Godot's existing tools aren't sufficient.

**Comment by GeorgeS2019** [comment]
The [feature](https://github.com/microsoft/microsoft-ui-xaml/issues/686#issuecomment-491991964) is now being evaluated by the Microsoft team

**Comment by GeorgeS2019** [comment]
@aaronfranke  The existing Godot UWP export provide a full windows 3D display. Windows UI Control allows developer to use part of the Windows to display Godot 3D display. Developer can use Windows UI controls e.g. button, slider etc to control the content of the Godot 3D display in Windows UI 3D Control.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
