### ISSUE TITLE
pck file missing 

### ISSUE THREAD

**Issue by Deliner** [godotengine/godot#28849]
After compilation on linux with params: platform=windows tools=no target=release bits=64
Exe file shows alert dialog -> Could not load game data at path ".". Is the .pck file missing?

**Comment by groud** [comment]
That's normal, with such parameters you are not compiling the editor in the executable. So the executable needs a game file (.pck next to it to run)

Use the project exporter to have the executable generated with the project file.

**Comment by ulissescad** [comment]
Hi, I have the same problem, how can I use these "project exporter"? Anyone can help me? Thanks

**Comment by groud** [comment]
How to export you project: [link](https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_projects.html)

If you still have problem about it, please ask on the other community channels. We use Github to submit bugs or ask for enhancements, not for support. :)

**Comment by ulissescad** [comment]
Thanks, I guess.

**Comment by RaTcHeT302** [comment]
hello future people from Google, i hope this helps you

i think for a true release you need to run this command in a bat file

find the godot folder

find the adress bar, and type cmd in it, push enter
https://i.imgur.com/4T6MoIy.png

type this whole monster
scons -j16 platform=windows tools=no target=release use_lto=yes

replace "16" with the number of threads your CPU has, you can find that information in the task manager (push ctrl + shift + esc to open it)
https://i.imgur.com/FHdr23e.png

push enter

if there's a way to simplify the process, i don't know how to do that yet, i'm just writing this here, for future people, so that they don't need to suffer like i did

**Comment by RaTcHeT302** [comment]
man i love how fast the engine builds, it's such a relief to not have to wait 45 minutes, or hell up to one hour with the unreal engine 4, but the whole thing feels really easy to break, i had to delete the whole project to recompile it with visual studio again

i also have no idea how to debug the engine, without rebuilding the whole thing every time

the debugger also detaches itself, and it just leaves me really confused
![](https://i.imgur.com/Kr1XayV.png)

if i figure this out (i kinda have to), i'll write some step by step instructions on my website (it's on gitlab, and it has my name in it)
