### ISSUE TITLE
GI Light Probes to get lighting information at given position

### ISSUE THREAD

**Issue by dam482** [godotengine/godot#28843]
We are currently limited to getting only the baked albedo and emissive lighting information from a GIProbe.

This request is to create a new "GI Light Probe" node type that can be placed inside a GIProbe, and query more lighting information at it's position.

This lighting information would be useful for sneak/thief games, where we need to know if the player is illuminated or hiding in a dark area.

**Comment by mhilbrunner** [comment]
You probably want to watch Godot 4.0 closely, as it seems like reduz is going to revamp GI/lighting with the Vulkan renderer - but if after that this still applies:

---

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
