### ISSUE TITLE
Add support for Themaister's compute shader FFT implementation

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#28854]
It would be really great to great to have access to [Themaister's fft implentation for glsl](https://github.com/Themaister/GLFFT) for implementing [Tessendorf's ocean wave vertex function](https://www.google.com/url?sa=t&source=web&rct=j&url=http://citeseerx.ist.psu.edu/viewdoc/download%3Fdoi%3D10.1.1.161.9102%26rep%3Drep1%26type%3Dpdf&ved=2ahUKEwiw2ajW2ZjiAhUE658KHctAAiIQFjAAegQIBBAB&usg=AOvVaw3sh9PdJSUYm1Q282fLmzSJ).

**Godot version:**

3.1.1

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
This implementation relies on GLES3.1 or OpenGL 4.3, neither of which are supported by Godot currently. 

Since it relies entirely on compute shaders, something similar could be added in theory after the vulkan port is finished. 

Also note, this isn't something you could add to a shader language. The fft is computed in entirely support GL calls in a compute shader. So it would have to be a separate resource entirely.

**Comment by creikey** [comment]
It would be really great to have this function in Godot 4 with Vulkan, Gernster Waves really don't cut it :smile: once vulkan is fully ported in the master branch I could take a crack at this.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
