### ISSUE TITLE
to_global is funky when moving parent node

### ISSUE THREAD

**Issue by grenzionky** [godotengine/godot#28888]
**Godot version:**

3.1

**OS/device including version:**

OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.0.9-2-MANJARO
DE: KDE 5.57.0 / Plasma 5.15.4
WM: KWin

**Issue description:**

when moving a parent node in a script, its children will appear to move correctly, but when using to_global to get its position, i dont get the correct position back.

**Minimal reproduction project:**

resize the window to see what i mean

https://mega.nz/#!nhxmBA5B!1cyVTtG4p3Zf9HWeuMdW1tbDMTeYPeqKGfMDeH9m_cY

**Comment by Chaosus** [comment]
> https://mega.nz/#!nhxmBA5B!1cyVTtG4p3Zf9HWeuMdW1tbDMTeYPeqKGfMDeH9m_cY

No need to use external file storages here - you can drag&drop zip archive to the post on Github directly

**Comment by fooff** [comment]
godot 3.2.1
i set my scene to have a camera node inside of a parent spatial node, camera movement works as intendend (i move the parent instead of moving the camera directly) but i cannot find a way to get the global coordinate of the camera anymore: both to_global(camera.translation) or to_global(get_viewport().get_camera().translation)gives gibberish results.

**Comment by Zylann** [comment]
I'm not really sure what the reproduction/expectation is supposed to be, but keep in mind you are exploiting two things here:
- You are using `get_viewport_rect()` to move the root node of the scene. This will have an effect on coordinates depending on screen size, which may not always fit calculations in world coordinates.
- One of your squares is below a `Node`. AFAIK, `Node` acts as a "root" in the transform hierarchy. Nodes below a `Node` will be in world space, no matter what the parent of that `Node` is. The opposite then also applies: if you use `to_global()` on a node, it will apply transforms of its parents, until it reaches a node which does not have a transform, *and will stop there*. In other words, if you move `board`, it will NOT affect the global transform of `square2`.

**Comment by mrjustaguy** [comment]
I've run into this in Godot Alpha 4.
I've been tossing a character off Vector3(0,3500,0) with velocity xyz all being non zero, and only x and z were updating correctly, y value was constantly at 3500, even when the actual global position.y was 0

**Comment by Calinou** [comment]
@mrjustaguy Your comment is about 3D and not 2D, so I'd recommend opening a separate issue. Feel free to create a MRP for 2D as well :slightly_smiling_face:

**Comment by Sauermann** [comment]
It believe that this works as expected and is based on a misunderstanding of coordinate systems.

Let's have a look at the following part of your MRP:
``` gdscript
func _draw() -> void:
	var square1 = $square1.to_global(Vector2(0,0))
	draw_circle(square1, 10, Color.red)
```

`$square1.to_global(Vector2(0,0))` converts `Vector2(0,0)` from the local coordinate system of `$square1` to the coordinate system of the canvas (global).

The `_draw` function belongs to the node `board`, and expects coordinates in its local coordinate system of `board`, but `var square1` is in the coordinate system of the canvas, so it draws the circle at the wrong location.

In order to make this work as expected, you would have to adjust it in the following way:
``` gdscript
var square1 = to_local($square1.to_global(Vector2(0,0)))
```

**Comment by Calinou** [comment]
Closing per @Sauermann's comment.

**Comment by Sslaxx** [comment]
Is there a way of getting a node's relative position in comparison to another node?

**Comment by Sauermann** [comment]
@Sslaxx

When you want to calculate, where `CanvasItem` A lies in the local coordinate system of `CanvasItem` B:

1) If A and B lie in the same Canvas: `B.get_global_transform().affine_inverse() * A.get_gobal_transform() * Vector2(0, 0)`

2) If A and B lie in the same Viewport: `B.get_global_transform_with_canvas().affine_inverse() * A.get_gobal_transform_with_canvas() * Vector2(0, 0)`

3) If A and B lie in different Viewports: there are cases, in which the question can not be answered.
