### ISSUE TITLE
Mono types checking in gdscript

### ISSUE THREAD

**Issue by ismslv** [godotengine/godot#28908]
**Godot version:**
3.1 Mono

**Issue description:**
It may sound strange, but gdscript does not know about c# types.    
Of course it does not, you would say. I can make a ```.call()```, which works quite nice.   

But, consider the following:   
I have some type created in c#, for example ```LevelData : Resource {}```   
Then, from my plugin, which uses gdscript, I get this object (e.x., in editor):   

```gdscript
extends EditorInspectorPlugin

func parse_begin(object):
   if (object is LevelData):
```   
And it will raise an error, because LevelData is of course unknown. But ```object.get_class()``` will return ```Resource```, so the only way for now is the following:   
```gdscript
if (object is Resource):
   if (object.get_script().get_path().get_file() == "LevelData.cs"):
```

Is there any workaround? If not, it should be in order for two languages to coexist.

**Comment by aaronfranke** [comment]
GDScript will likely never "really" know about C# classes, since they are completely different languages.

You're right that `get_class()` has limited usefulness as-is, however, improvements to this are already tracked by #21789 (specifically check out this comment https://github.com/godotengine/godot/issues/21789#issuecomment-618588900 with a very nice proposed solution).

So I'm closing this as half-duplicate and half-wontfix.
