### ISSUE TITLE
Add warnings when unused VisualScript nodes exist

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28911]
**Godot version:**
3.1.1

**Issue description:**
There is are useful errors for when code isn't reachable in GDscript, that should also exist for VisualScript.

**Comment by swarnimarun** [comment]
I am pretty sure this should be added to Visual Shader as well.

**Comment by Jummit** [comment]
I thought about that too, but the script based shader editor doesn't have that feature, so I think it would be an inconsistency to add it to the Visual Shader.

**Comment by swarnimarun** [comment]
Ok then let me find the shader editor code.
My guess we directly compile the shaders after transpiling them to glsl, but we should able to check for unused variables, in shaders it's kind of important too. The cost of extra fields in shaders is not so nominal, it gets put on the buffer and costs bandwidth, and cache.
And also pretty sure drivers or any other stage of processing can remove them.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
