### ISSUE TITLE
Culling does not respect vertex shaders

### ISSUE THREAD

**Issue by Brickcaster** [godotengine/godot#28933]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 7

**Issue description:**
Meshes made larger via vertex shaders are culled if the original object is outside of the field of view.  This applies to the editor preview, the camera preview, and when the project is tested.

![image](https://user-images.githubusercontent.com/13324089/57864893-a82aff00-77ca-11e9-9ed2-7583c4367cf6.png)

![image](https://user-images.githubusercontent.com/13324089/57864732-6c903500-77ca-11e9-80e9-7a8714931f29.png)

**Steps to reproduce:**
Create a mesh node.
Position the camera and mesh node such that the mesh node is outside of the camera's FOV
Apply a vertex shader to increase the size of the mesh node such that it should be in the camera's FoV.

**Minimal reproduction project:**
[Principles of Animation.zip](https://github.com/godotengine/godot/files/3187694/Principles.of.Animation.zip)

**Comment by CptPotato** [comment]
It's sadly impractical to calculate a bounding box at runtime when using vertex deformations. One possible fix would be allowing the user to customize the bounding box that's used for culling, though I'm not sure if something like this already exists.

**Comment by clayjohn** [comment]
This issue comes up periodically. It is not an issue with Godot, but a feature of how modern rendering APIs work (OpenGL, Metal, Vulkan, DirectX). Culling happens before the vertex shader is run. The AABB (used for culling) is calculated once and then used thereafter. It is impossible to recalculate it every frame because the results of the vertex shader are also not passed back to the CPU (they are calculated and remain in the GPU). Even if it were possible it would make all rendering operations incredibly slow. This is not something that Godot can "fix" or implement as it is rooted in the operation of all graphics API's.

In order to keep your object from being culled you have two options 1) adjust the "custom AABB" in your mesh to encapsulate the true size of your object (including vertex deformation) or 2) Provide an "extra cull margin" in your mesh instance as described in http://docs.godotengine.org/en/latest/tutorials/shading/advanced_postprocessing.html

**Comment by Brickcaster** [comment]
Yes, this appears to be more of a documentation/usability issue than an outright bug.  Thanks for the info!

**Comment by clayjohn** [comment]
Already documented here http://docs.godotengine.org/en/latest/tutorials/shading/your_first_shader/what_are_shaders.html and here http://docs.godotengine.org/en/latest/tutorials/shading/advanced_postprocessing.html

In my opinion even this is a little too far for Godot documentation. Because this isnt a feature of Godot its a feature of absolutely all 3D rendering.

**Comment by Brickcaster** [comment]
Closing this as bounding box scaling exists.
