### ISSUE TITLE
Integrate C++ editing in the script editor

### ISSUE THREAD

**Issue by cata0309** [godotengine/godot#28968]
Hello ! 
I read that it is possible to have some bindingds between C++ and Gdscript. I was wondering it is possible to edit the C++ files trought Script editor.
I would like to see much more integration of C++ language in Godot, C# has its own version of Godot.

**Comment by KoBeWi** [comment]
But C# isn't supported by built-in script editor either. It only has some basic syntax highlighting.

**Comment by Geequlim** [comment]
Make sure Godot is a game engine and this kind of features are not supposed to support.

**Comment by Xrayez** [comment]
The editor feature can be overkill, but the C++ compilation itself deserves attention: #11080
Also see #11068, #19079.

**Comment by blockspacer** [comment]
It may be good idea to use cling to solve that issue
see https://github.com/godotengine/godot/issues/31630

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(btw there's already a related proposal: https://github.com/godotengine/godot-proposals/issues/573)

**Comment by Croydon** [comment]
@KoBeWi If you are using this change in management to get rid of dusty issues nobody cares about anymore then okay... if this is a non-goal it would be nicer if you could move the issues to the new repository instead 😄

**Comment by KoBeWi** [comment]
It's more to get rid of dusty issues. There are (were) lots of them and many were abandoned and didn't receive much support. The new proposal repository is more strict, so we can't just move any issue there, because they don't meet the requirements in their original form. If the feature is still wanted, the author should create a proper proposal.
