### ISSUE TITLE
VisualScriptEmitSignal should be replaced by a VisualScriptFunctionCall

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#28982]
**Godot version:**
3.2

**Issue description:**
VisualScriptEmitSignal is useless because its functionality can be replaced by the more flexible VisualScriptFunctionCall.

**Steps to reproduce:**
Create a signal in a VisualScript and drag it into the graph. This creates a VisualScriptEmitSignal, but it could be a VisualScriptFunctionCall.

**Comment by Xrayez** [comment]
While it might not make sense when done purely via VisualScript, I imagine that other objects could be notified which could as well be extended via GDScript and other script languages where emitting and connecting to signals does make more sense.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
