### ISSUE TITLE
Path2D/PathFollow2D and YSort

### ISSUE THREAD

**Issue by e-e** [godotengine/godot#28990]
**Godot version:**

3.1.1

**OS/device including version:**

MacOS 10.14.3

**Issue description:**

It seems that it might be a common requirement for a `Path2D->PathFollow2D` node to be sorted as it might be expected along with the other sibling nodes in the `YSort`. Is there a way to do this currently? Or is it possible when sorting `YSort` children to add a check to see if the node is a `Path2D`, and if so, sort based on the child `PathFollow2D` node y-position instead?

**Steps to reproduce:**

**Minimal reproduction project:**

[path2d-ysort.zip](https://github.com/godotengine/godot/files/3194425/path2d-ysort.zip)

**Comment by e-e** [comment]
One solution I was thinking about would be to add a method to all `Node`s which is used to retrieve the y-position that is used to do the sorting. This way the method can be overridden, and return the y-position of a child node instead.

**Comment by eon-s** [comment]
You can simply detach the node you want to move from the path, put a RemoteTransform2D in it's place and link your Y-sorted node with the RemoteTransform2D.

![pathsorted](https://user-images.githubusercontent.com/10215987/58628206-7d9f7280-82af-11e9-9d74-d48b01b5177d.png)

**Comment by e-e** [comment]
@eon-s so then the `EntitySorted` would contain all of the actual entity nodes, such as the `Sprite2D`, etc?

**Comment by eon-s** [comment]
In this case it would be your path-moving object/s, the RemoteTransform nodes allow you to separate some "messy" structures (like paths or body joints) from other elements of the tree.

**Comment by avencherus** [comment]
What might be needed to solve such a problem is have YSorts offer some sort of tree depth option, so it could recursively go further, but this might have performance issues, and undesired side effects if some of the neighboring nodes are scenes of actors with lots of sprites aggregated together to be used as one entity.

**Comment by Calinou** [comment]
YSort was removed in 4.0 in favor of a Node2D YSort property – is this still relevant?

**Comment by eon-s** [comment]
@Calinou this looks more a request than a bug report, not fully fit for proposals either, and things changed a bit on 4 so there may be still usability issues but need some testing in projects to see the new workflows and problems.

**Comment by kleonc** [comment]
> The YSort node was removed in 4.0 in favor of a Node2D YSort property – is this still relevant?

It's not. Replacing `YSort` node with `Node2D.y_sort_enabled` property allowed use cases exactly like the one presented here (workaround with RemoteTransform2D like in https://github.com/godotengine/godot/issues/28990#issuecomment-497289667 is no longer needed).

Here's 4.x version of the MRP: [path2d-ysort.zip](https://github.com/godotengine/godot/files/14285367/path2d-ysort.zip)


|Setup|In action|
|--------|--------|
|![Godot_v4 2 1-stable_win64_732AUrHSPo](https://github.com/godotengine/godot/assets/9283098/ec86ebdb-56ff-4124-a697-595943731678)|![dMVkaZL39x](https://github.com/godotengine/godot/assets/9283098/278b03d3-9a35-49cf-8ed9-8766069f2d70)|



Hence closing this as resolved (since 4.0).
