### ISSUE TITLE
Add more texture alignment options

### ISSUE THREAD

**Issue by MegaMech** [godotengine/godot#29019]
**Godot version:**

3.1.1

**OS/device including version:**

W8.1
ATI 570 8GB

**Issue description:**

(Edited)
I don't trust the accuracy of texture placement (more so colour accuracy) in meshes from Blender to Godot.
It would be nice to have more options for aligning textures on meshes. Like rotation and projection<Flat, Cube, Sphere, etc.>. Scale and offset already exists. This would also make it so we have less work to do in Blender. Why export materials at all if we can just do all the work on in Godot? I could spend hours making a texture look exactly how I like in Blender and then be disappointing with the look in Godot because they're two different rendering engines; Godot would always require tweaking anyway.
Plus if I import an object and texture, and for some reason the texture is upside down I don't have to re-export it from Blender. I can just set the texture rotation to 180 within Godot

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
