### ISSUE TITLE
scene cannot be load after use export var(usability)

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#29061]
<godot 3.1>

If i use a export var to set the scene to be loaded like this:

```
export var scene_zoomed = "res://scenes/Drawing.tscn"

#----load the scene...
var new_scene = load(scene_zoomed).instance()
new_scene.init(_zoom_pos, _zoom_scale, _zoom_depth) 
scene_controller.add_child(new_scene)
```
The engine will throw a error null instance call instance on a null instance

Finally I find I add a "" on the export menu. So may be you can add a quotation marks on the export panel, so the users know that the engine add its already.

**Comment by KoBeWi** [comment]
Well, if you understand that `String` is whatever is inside the quotations, without the quotations, I don't think this is necessary.

**Comment by akien-mga** [comment]
I also don't think this should be changed, the widgets you get for each primitive type are specialized for each type.

For String, it's a LineEdit which lets you input the String, without having to care about whether it should be enclosed with single or double quotes, nor escape single or double quotes inside your String.

For Vector2, you get two float widgets for x and y, so you don't need to type `Vector2(10, 42)` manually.

For Curve, you get a handy curve edition widget instead of a list of point coordinates to set manually for the Bezier transform, and the list goes on for all Variant and Resource types that can be edited in the inspector.

For your use case, you should likely use `export (PackedScene) var scene_zoomed` which will let you load the scene directly from a File Manager, ensuring that you get the correct reference to call `instance()` on.
