### ISSUE TITLE
'cancel_action()' for UndoRedo

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot#29103]
When creating an action with `UndoRedo`, you may find yourself in this situation:
```
UndoRedo.create_action("action")
for i in stuff:
    if i.thing == true:
       # Do/Undo stuff here.

UndoRedo.commit_action()
```

Now, if `i.thing` is never `true` throughout the entire loop, the action is pointless, but to know that, you're forced into making it loop twice to know before hand, as there's no way to cancel it.

This is the point of this proposal, to add a way to cancel an action midway.

**Comment by akien-mga** [comment]
Wouldn't it be simpler to make `commit_action` discard the action if it has no undo/redo methods assigned?

**Comment by YeldhamDev** [comment]
@akien-mga Likely, yes.

**Comment by KoBeWi** [comment]
I think I once met a use case that made me want suggest this feature too, but forgot what it was. If it's not complicated, it wouldn't hurt to add it, probably.

**Comment by AlexHolly** [comment]
Maybe something like this?

https://github.com/godotengine/godot/blob/8f23f4b44e043c6a7f69e96369e6c26fe9fd205b/core/undo_redo.cpp#L250
```
	// cancel created action
	if(actions.write[current_action + 1].do_ops.size()==0 &&
	actions.write[current_action + 1].undo_ops.size()==0) {
		actions.remove(actions.size()-1);
		return;
	}
	if (action_level > 0) 
```

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
