### ISSUE TITLE
Cross param copying between CPUParticles2D and Particles2D

### ISSUE THREAD

**Issue by Dentrax** [godotengine/godot#29110]
**Godot version:**
`v3.1.1.stable.official`

**OS/device including version:**
`Windows 10 x64`

**Issue description:**
I am unable the copy the `CPUParticle2D` 's params to `Particle2D`. (I didn't mean to _convert_ it.)
I think we should be able to do this; if `Particle2D` have a _Particles Material_ under _Process Material_ tab when we click _Paste Params_ for _Particle2D_

**Simplified:** How can i copy my _CPUParticle2D_ params and paste them to `Particle2D` 's _Particles Material_, if have?

**Steps to reproduce:**
1. Create a `CPUParticle2D` and change the some params.
2. Create a `Particle2D`
3. Click _Copy Params_ on `CPUParticle2D` then select the `Particle2D` and _Paste Params_

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
