### ISSUE TITLE
Blackbody Light Colors?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#29122]
The idea is to use real-world color temperatures for lights in the scene.

This allows the artists to use measured real-world values in Kelvins to model different types of light sources.

Here's how that works in Blender:

![Screenshot_20190523_133149](https://user-images.githubusercontent.com/491704/58249423-22c1c480-7d5f-11e9-8e54-b6ec549049ff.png)

This is another step towards physically-based lighting - a.k.a. photorealism.
Maybe it'd be good to also have white balance controls in the camera?

Note: this above render uses Filmic Blender display transform with The Base Contrast look.
**Color Management is a huge deal in getting good looking CGI.**
Below is a "Default" Display transform instead. Look how burned out and distored the colors and light falloffs are, looking completely unnatural, yet familiar to anyone doing CG.

![Screenshot_20190523_133505](https://user-images.githubusercontent.com/491704/58249615-a4b1ed80-7d5f-11e9-87f2-14b87d1e8d12.png)

**Comment by unfa** [comment]
PS:

Here's how Filmic Blender looks with "Very High Contrast" Look:
![Screenshot_20190523_134027](https://user-images.githubusercontent.com/491704/58249910-6537d100-7d60-11e9-86c3-8403251692cc.png)

It's much closer to the "Default" Blender display transfrom, but it's free of the color distortion and clipping!

**Comment by r3fio** [comment]
It is relatively easy to approximiate with the help of a gradient or color ramp like this:

![Temperature_to_RGB_1000_to_40000](https://user-images.githubusercontent.com/10214363/58257785-d338c400-7d71-11e9-846b-39e51e0f3b02.png)

If you need more accuracy, then you can utilize a table like this:
http://www.vendian.org/mncharity/dir3/blackbody/UnstableURLs/bbr_color.html

Which results in the following plot:
![Raw_temperature_vs_RGB_chart](https://user-images.githubusercontent.com/10214363/58257580-7937fe80-7d71-11e9-8e1a-15d73d4a3bcd.png)

Unreal has a blackbody node too, which is similiar to the one in Blender:
https://docs.unrealengine.com/en-us/Resources/ContentExamples/EffectsGallery/2_C

Further, Unreal features physical lighting units, which are equally useful:
https://docs.unrealengine.com/en-us/Engine/Rendering/LightingAndShadows/PhysicalLightUnits

I suppose that something like that would be everything you might need to create a correct physically-based lighting setup in Godot.

Also, white balance controls might be better suited for the Environment resource?

**Comment by unfa** [comment]
That graph is clipped at 255!

Since we can have RGB values higher than 1.0 I guess we should be able to represent the blackbody curve without clipping.

I think it makes no sense to limit ourselves here to colors that can be expressed with a hex code - that notation only makes sense for display-reffered imager (like screenshots) - in scene reffered imagery (like 3D rendering) there's no "highest possible value" to anything.

I think going with the Unreal engine's way would be beneficial - physical lighting is awesome.
Maybe IES lights would also become an option at some point...

**Comment by tinmanjuggernaut** [comment]
Color aside, the blowout is because tonemapping doesn't work right. Instead of tonemapping it's clipping. #18181 has not been fixed. I just posted an updated example there.

**Comment by tinmanjuggernaut** [comment]
@CptPotato responded on that other thread. You can fix the blowout by changing the Environment/Tonemap mode to Filmic and increasing the White value.

**Comment by Calinou** [comment]
I think it'd make sense to have this, but then, we'd have *two* ways to set a light's color in the Inspector, which can be confusing. (For the record, we currently have a similar issue with RigidBody mass and weight properties.)

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
