### ISSUE TITLE
Mod/Editor support without shipping original assets

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#29121]
I'm running Godot 3.1.
Currently I can ship my demo build all packaged up as I don't support mods in the demo.
For the full version, I currently ship my game un-packaged as I want to support mods more easily.
I also ship an editor build of godot with my project.

Now, this means I am basically shipping my art assets twice, first I have the original assets, which are required to allow the editor to open.
Then I have everything in the .import directory.
Hence I've doubled the size of my game just to get mod support.

What I would like to see is the ability to open the editor without the original assets by either checking the import directory or checking any game packages (incase someone wants to mod a packaged game).

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
