### ISSUE TITLE
Ignoring a unused argument warning should add a lower case

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#29130]
**Godot version:**
3.1.1

**Issue description:**
`# warning-ignore:unused_argument` is redundant, as ignoring this issue can be solved by renaming the argument. I think the ignore button should put a lower case in front of the argument.

**Steps to reproduce:**
Create a function with unused arguments and ignore the warning.

**Comment by vnen** [comment]
This is tricky because the editor would also need to rename the references in the function block.

**Comment by Jummit** [comment]
> This is tricky because the editor would also need to rename the references in the function block.

True. Maybe both options could be available. Ignore and add underscore.

**Comment by Calinou** [comment]
@Jummit If we go through the pain of adding function block replacements, we might as well drop the old method of ignoring the warning :slightly_smiling_face:

**Comment by vnen** [comment]
Well, I guess we *could* just rename the argument, since most likely there's no reference in the function at all (since you're getting this warning).

It will break the code in cases like this though:

```gdscript
func foo(a):
    a = "bar"
```

Because you still get the warning, but renaming the parameter to `_a` will break the reference in the code block, which will trigger a parser error. But maybe it's not a big deal.

**Comment by Calinou** [comment]
Technically, the "unused argument" ignore annotation is different as it can ignore multiple unused arguments at once. By contrast, adding a `_` prefix only ignores a single argument at a time.

**Comment by Jummit** [comment]
That seems fair. I'll close this for now, if someone has ideas on where to mention this in the documentation, feel free to do so.
