### ISSUE TITLE
Running export with Godot or headless Godot along with opened editor deletes (corrupts) config file

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#29149]
**Godot version:** 3.1.1

**OS/device including version:** Linux 64

**Issue description:**

I had a project opened in editor. I tried to run export from terminal via godot and then headless godot. After it failing to export, I closed the editor, launched again and realized it deleted my whole config (project list, GUI settings of editor, everything). I was not amused. ☹️

**Steps to reproduce:**

* Open project in editor
* Try exporting via terminal
* Close editor
* Launch editor

**Comment by Zireael07** [comment]
Is it reproducible or a one-off thing? I am having very similar issues on Ubuntu 18.04 (64 bit), but unfortunately mine aren't reproducible.

**Comment by austinried** [comment]
This happens to me as well, and is one of the reasons I decided to switch to running headless in a docker container, but that shouldn't be requried.

Also, it doesn't seem like there is a way to specify an editor settings config file to headless, which is particularly annoying on Linux when you need to specify a path for wine and rcedit to export with Windows icons and there doesn't seem to be a way to do that since it destroys the existing system config file.

**Comment by akien-mga** [comment]
I think @bojidar-bg fixed this recently.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

**Comment by akien-mga** [comment]
No answer, so closing.
