### ISSUE TITLE
AnimatedSprite - SpriteFrame Editor: Being able to replace existing frames by double-click or/and button

### ISSUE THREAD

**Issue by IvanSoldano** [godotengine/godot#29158]
Currently to replace the texture from a frame in SpriteFrames Editor needs to Delete said frame, then add the desired texture (Load Resource), and finally Move the new frame to the original position of the replaced frame.
**Proposal**
Would be useful to replace the texture by double-clicking its frame or/and via a button.
**Use cases**
-correct mistakes.
-replace prototyping textures.
-create new character graphics using existing SpriteFrames as template

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
