### ISSUE TITLE
bool return value of Tween functions not documented

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#29171]
None of the functions here document the meaning of their return value:

https://docs.godotengine.org/en/3.1/classes/class_tween.html#class-tween-method-interpolate-property

**Comment by rcorre** [comment]
I was about to report this in the [godot-docs](https://github.com/godotengine/godot-docs/issues/) issue tracker, but after looking at the source, I think the issue is actually that the return value is used inconsistently and is not very useful.

Many `Tween` functions like `start` will _always_ return `true`. A few will return `false` in the case where there's "no valid delta", but there are [many other conditions](https://github.com/godotengine/godot/blob/master/scene/animation/tween.cpp#L1656) where it will fail with an assert instead. So it sounds like the answer for most is that they "return true if they succeed, and _maybe_ return false if they fail, but also might error out."

**Comment by Calinou** [comment]
I think it would make sense to make those Tween methods return `void` instead of a boolean value. We can still print errors if something wrong occurs.

**Comment by akien-mga** [comment]
This was fixed already by godotengine/godot#36844.
