### ISSUE TITLE
Shader not working on all custom draw modes

### ISSUE THREAD

**Issue by ZodmanPerth** [godotengine/godot#29181]
**Godot version:**
v3.1.stable.official

**OS/device including version:**
Windows 10 Pro, v1809, 64bit
Surface Pro 5, i5

**Issue description:**
Applying a shader to a `Node2D` with custom drawn content only works on some custom draw functions.  `draw_rect` works correctly, however `draw_circle` and `draw_polygon` do not.  Other custom draw functions have not been investigated and may not work correctly either.

**Steps to reproduce:**

Use the attached repro project.  It contains a `Sprite` with a texture (yellow) and a `Node2D` ("CustomDrawn") containing a script to draw some shapes (in white) on the screen, using 3 different `draw_` functions to create 3 shapes.

![image](https://user-images.githubusercontent.com/546368/58376335-89cbbd00-7f9b-11e9-8798-1ab42c53b690.png)

Both nodes use a unique custom shader to manipulate the alpha value by combining with a gradient mask, and only drawing if the mask UV is over a certain cutoff value.  This allows a transition type affect, which is demonstrated (on run) using an `AnimationPlayer` manipulating the cutoff value.

Notice that only the `draw_rect` data is working, the other `draw_` functions do not.  It is expected that all `draw_` functions should work using such a shader.

[Further discussion](https://godotforums.org/discussion/comment/27701) occurred in the Godot Forum

**Minimal reproduction project:**

[ShaderOnCustomDrawTest.zip](https://github.com/godotengine/godot/files/3219908/ShaderOnCustomDrawTest.zip)

**Comment by raphael10241024** [comment]
I think it's not a good idea to use shaders in custom draw, because a node2d has a size actually, so it  can't know how to mapping uv to a custom draw line or circle , etc. If you want to show part of graphics, trying to adjust  the _draw function and call update() each frame may be a good idea.
Maybe we should just ignore all the material when use custom draw mode in the game engine.

**Comment by mrcdk** [comment]
This isn't a bug. This is more a lack of understanding what a shader can do, how it works and what each shader parameter does.

For example, in the shader, the UVs are being used but they aren't passed when drawing the polygon so they'll be always (0, 0) and won't draw anything because that's what the shader does when the UV is (0, 0). You'll need to calculate them for it to work.

`draw_rect()` automatically creates the UVs for you because it's a basic shape and the command it generates is used for a lot of things (like drawing a sprite, is the same command but with a texture in it)

`draw_circle()` doesn't create UVs because they aren't needed internally. You'll need to generate a polygon with the correct UVs if you want a circle with UVs

Either way, that shader won't probably work as you expect with polygons depending on how you send the UVs and whatnot.

For example, In your example to fix the polygon:
```
	pt = Vector2(0,200)	
	var points = [ Vector2(), Vector2(0,80), Vector2(80,80), Vector2(120,40), Vector2(80,0) ]
	var pv2a = _makePoolVector2Array(points, pt)
	var pColour = PoolColorArray([Color.white])
	var uv = []
	for v in pv2a:
		uv.push_back(v / Vector2(120, 80))
	draw_polygon(pv2a, pColour, PoolVector2Array(uv))
```
![https://i.imgur.com/DJ0RPoj.gifv](https://i.imgur.com/DJ0RPoj.gif)

But if we `shuffle()` the UVs:
![https://i.imgur.com/1qebuFO.gifv](https://i.imgur.com/1qebuFO.gif)

**Comment by ZodmanPerth** [comment]
@raphael10241024 said:
> I think it's not a good idea to use shaders in custom draw, because a node2d has no size actually, so it can't know how to mapping uv to a custom draw line or circle , etc. If you want to show part of graphics, trying to adjust the _draw function and call update() each frame may be a good idea.

Obviously I've provided a simplified sample for replication.  The effect I'm actually trying to achieve isn't possible with using `_draw` functions.  A shader seems the best way to achieve what I'm actually after.

**Comment by ZodmanPerth** [comment]
@mrcdk  said:

> This isn't a bug. This is more a lack of understanding what a shader can do, how it works and what each shader parameter does.

That's no surprise to me; I've never used any game engines before and I'm trying to piece together knowledge from the documentation, videos, and articles on the web.  Unfortunately I haven't found any really well explained tutorials for this stuff, and most of them assume knowledge that isn't there for someone starting from scratch (like me).
 
> For example, in the shader, the UVs are being used but they aren't passed when drawing the polygon so they'll be always (0, 0) and won't draw anything because that's what the shader does when the UV is (0, 0). You'll need to calculate them for it to work.

Ah, that makes a lot of sense.  Between this and the code sample you provided, I think I understand; I need to provide the UV array in the `_draw` function in order for appropriate `uv` values to get to my shader.

There is no explanation of the `uvs` parameter (or any other parameter) on the `draw_polygon` function documentation, so I didn't understand what it was for.

![image](https://user-images.githubusercontent.com/546368/58540376-d5949580-822b-11e9-9fe9-9b8da46404a8.png)
_snapshot from the documentation_

>	for v in pv2a:
>		uv.push_back(v / Vector2(120, 80))

I'm assuming the divisor here (`Vector2(120,80)`) is to ensure the `uv` values are between 0 and 1 when they get to the shader.

If this is all correct then this is not a bug but a lack of understanding as you say.  Thanks!

**Comment by mrcdk** [comment]
> I'm assuming the divisor here (Vector2(120,80)) is to ensure the uv values are between 0 and 1 when they get to the shader.

Yes, UVs go from (0,0) to (1,1) (but not limited to those parameters) and are mapped to the texture size (0, 0) being the top left corner of the texture, (1, 0) being the top right, (0, 1) bottom left, (1, 1) bottom right. But, as I said, they are not limited by that, it depends on how the texture flags are set, if repeating or mirroring is enabled in the texture then the values will wrap around the texture so, for example, an UV value of (1.5, 0.5) will draw the center pixel of the texture if the repeat flag is enabled and if it's not enabled it will draw the middle right pixel of the texture.

Here's an image to show the result, the middle image are UV (0, 0) to (1, 1):
![https://open.gl/media/img/c3_clamping.png](https://open.gl/media/img/c3_clamping.png)
Godot supports the 3 first modes
