### ISSUE TITLE
Add Script#get_class_name() method

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#29229]
**Godot version:**
3.1.1.stable.official

**OS/device including version:**
MacOS HighSierra (latest)

**Issue description:**
I am missing programmatic access to information on the class name of an existing script.

While I am able to work around this, using a simple method by which I am able to determine the class name from either the Script's resource_path or assigned class_name, I would have to reimplement the same functionality in all of by base classes.

And with the GDScript module already knowing the class name, it should not be that hard for the Script resource to also provide that information to the user, or would it?

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
