### ISSUE TITLE
Closing Search bar will remove error message

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#29234]
**Godot version:**
3.1.1

**Issue description:**
When there's error in script editor and you close search bar, the message disappears and you no longer know what is wrong.

**Steps to reproduce:**
1. Write some bad code, so error appears
2. Open search bar
3. Close the search bar
4. Error message disappears and there's no way to bring it back
![image](https://user-images.githubusercontent.com/2223172/58434992-af051c00-80be-11e9-8b3c-3a068b290ec5.png)

**Comment by Anutrix** [comment]
Found the issue.
The culprit is https://github.com/godotengine/godot/blob/dfe228a865890931c6da7b98b53b6f0fe2555d15/editor/code_editor.cpp#L413

But the issue is in displaying search results though. It sets search results as errors using set_errors("Error/Search Result") function. So when search results are gone or displayed, the error message are gone or overwritten respectively.

Also, the Search Results overwrite the error message too. This issue could be renamed.
**Steps to reproduce**:
1. Write some bad code, so error appears
2. Open search bar
3. Type something in search bar and press Enter key/Search Button.
4. The result is printed and the error message is gone forever.
