### ISSUE TITLE
bug: converting sprite to mesh2dInstance

### ISSUE THREAD

**Issue by uuuuuup** [godotengine/godot#29267]
**Godot version:**

3.1

**OS/device including version:**

ubuntu18.04 and windows10
nvidia 1080ti

**Issue description:**

some kind of sprite cannot be generate correct mesh 2d.
for example, 
0000001
0000011
0000111
0001111
0011111
0111111

In this function,
Vector<Vector2> BitMap::_march_square(const Rect2i &rect, const Point2i &start) const
if I change from 
                        Rect2i fixed_rect = Rect2i(rect.position, rect.size - Size2i(2, 2));
to
                        Rect2i fixed_rect = Rect2i(rect.position, rect.size);
then, the bug is fixed.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Xrayez** [comment]
*Note*: the traced image has to be padded for march square algorithm to work here in all cases, this is why `Size2i(2, 2)` is there I think. Sprite's image most likely has to be padded by 1 pixel instead of limiting marching area by `fixed_rect`. so that all area can be traversed. Alternatively, necessary checks are needed to prevent march square algorithm from going outside of sprite's bounds.

**Comment by uuuuuup** [comment]
Do you mean sprite image size should have 1 pixel padding every line?
I thought usual sprite files do not have padding...

**Comment by Xrayez** [comment]
As a workaround, your image should be padded by a frame of 1 pixel indeed, but ideally you don't have to add 1 pixel padding to each sprite you import yourself, this should be done within engine, but it creates additional overhead since the engine would have to pad the image anyway, possibly by making an additional copy of it. Having bounds check on every march step would also work but that would be wasteful (don't need to check inner pixels).

**Comment by uuuuuup** [comment]
Actually I use the function via gdscript not godot engine tool.
I created sprite dynamically from gdscript and tried converting mesh2dInstance.
For 1 pixel padding case,  the problem is still exist.
For 2 pixel padding case, the bug is fixed.
