### ISSUE TITLE
GDScript: Check if signal connected to function

### ISSUE THREAD

**Issue by menip** [godotengine/godot#29300]
Say I have a parent `Node2D` with child `Button`. My parent has a script with function `_on_Button_pressed`. It would be convenient if editor would check whether the child's `pressed` signal is actually connected to `on_Button_pressed`. Note we do have the signal icon visible in node tree, but it can be easy to miss. 

Generating warnings for this would help in some cases, most obviously when one declares a function and forgets to attach signal. Others situation are edge cases: in my case I was messing around with scene root and switching where script was attached. Reattaching to different node breaks the signal connection as now paths are different.

This suggestion would only be applicable to signal callbacks that have standard names such as `_on_ChildName_SignalName`.

**Comment by KoBeWi** [comment]
Does anyone create these methods manually? From my experience, I always create `_on_ChildName_SignalName` from the connection dialog. If I connect to existing method, it has a custom name. That warning seems a bit arbitrary.

**Comment by Qws** [comment]
I use to check in code..

```
var list : Array = button.get_signal_connection_list("pressed")
if list.count() == 0:
  #no signal is found
```

If you found a signal, you can use the `is_connected()` function from the button, to see if the signal is connected or not.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
