### ISSUE TITLE
Saving/Loading actions with InputMap

### ISSUE THREAD

**Issue by menip** [godotengine/godot#29358]
It would be convenient to be able to easily save and load the input map.

Could add functions to InputMap to do this:
```
InputMap.save_input_map(path, include_defaults=false)
InputMap.load_input_map(path)
```
Where you can choose whether to save default actions `ui_*` or not.  It has been suggested to use `ConfigFile` for this purpose.

I'd be down to implement this, but not sure when will be able to, so putting this here as a reminder. Should be trivial to do if load is done destructively. Alternatively,  we could keep current actions/events and only add new ones from the save file. I'd like to hear whether that is what people want. Perhaps have both, with a `load_destructive=false` parameter that clears InputMap before loading actions from file.

**Comment by Calinou** [comment]
>  It has been suggested to use ConfigClass for this purpose.

It's [ConfigFile](https://docs.godotengine.org/en/latest/classes/class_configfile.html), actually :slightly_smiling_face:

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
@mhilbrunner A proposal already covers this: https://github.com/godotengine/godot-proposals/issues/423
