### ISSUE TITLE
Skeleton2D/Polygon2D combo bug

### ISSUE THREAD

**Issue by kozaluss** [godotengine/godot#29355]
Not sure if it is the same issue, as "fogine" has posted, but relates to similar problem.

**Godot version:**

Official 3.1 version (Godot_v3.1-stable_win64.exe).

**OS/device including version:**

Windows 10 64-bit
NVidia GeForce GTX 1070 Ti

**Issue description:**

In some special combination of scenes/polygons2d/skeletons2d they start to act oddly and the issue is more visible the more scenes with poly/skeleton are used. The skeleton itself behaves accurately, while polygon2d vertices seem to be influenced by improper skeleton movements.

**Steps to reproduce:**

Run the project's attached main scene. It will animate few subscenes with poly/skeletons. Some will animate properly, some will act oddly. There are godot icon sprites attached to bones so You can see where bone is at the moment in comparison to polygon.

![BUGpicture](https://user-images.githubusercontent.com/10975167/58729748-86489380-83ea-11e9-9f4e-9d5117f151e7.jpg)

**Minimal reproduction project:**

[KW_PolyBug.zip](https://github.com/godotengine/godot/files/3242635/KW_PolyBug.zip)

I hope the material provided will help to find and kill that bug soon.
Have a nice day.

**Comment by Qws** [comment]
I have also a similar problem. I have a scene containing multiple Skeleton2Ds and multiple Polygon2Ds... as I was working on it, suddenly another skeleton2D in the same scene stopped functioning. Bones are on the wrong place or are getting ignored it just gets really messy. And they animate fine in the Editor...

Currently, Skeleton2D + Polygon2D works on a simple Skeleton structure, like a single leaf, windy hair or a single tentacle. But if you're going to make a fully animated Octopus, each tentacle containing mini tentacles (for example) and each tentacle has its own Skeleton2D, it will definitely break.

Not sure if it's oke to have skeletons as sub children of another skeleton either... because I like to swap skeletons in-code too. But I think having too many Skeletons2D nodes around makes stuff unstable.

**Comment by kozaluss** [comment]
So I have looked a bit deeper into issues on git and found this one: #25911. And it seems it is the same issue, because when I've changed driver from GLES3 to GLES2, the problem seems to dissappear. Just wanted to add this as additional info - it seems like only GLES3 has the problem.

**Comment by fogine** [comment]
@kozaluss not really, it also happens with `GLES2` as I've previously reported in #29353

**Comment by andrewstrauch** [comment]
I can reproduce something similar in our project.

![flier_mesh_bug_g](https://user-images.githubusercontent.com/732367/66004288-70b9a800-e476-11e9-94b6-e85c30ca75fa.gif)

We also have multiple Skeleton2Ds and multiple Polygon2Ds

**Comment by KoBeWi** [comment]
Looks alright in 3.2.3
