### ISSUE TITLE
Array(text.split("",true)).empty() returns false

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#29366]
**Godot version:**

3.1.1.stable.official

**OS/device including version:**

Edition: Windows 10 Pro
Version: 1809
OS Build: 17763.503

**Issue description:**

Converted an empty PoolStringArray to Array and called empty() on the latter, expecting
it to return true, but it returned false instead. On an empty array. I expected it to return true,
as the source PoolStringArray was literally "".

**Steps to reproduce:**
var text = ""
var arr = Array(text.split("",true))
var b = arr.empty()
print(b)
print(arr)

**Minimal reproduction project:**

(https://github.com/godotengine/godot/files/3243499/Empty_PoolStringArray_to_Array_Error.zip)[Empty_PoolStringArray_to_Array_Error.zip]

**Comment by aspenforest** [comment]
So i was thinking about this... technically, isn't the array not empty when it contains an empty string?
So... this is expected behavior?

**Comment by akien-mga** [comment]
I didn't test, but this code reads like you would get `[[""]]`, i.e. an array containing an array containing an empty string. That's definitely not empty.

**Comment by akien-mga** [comment]
Actually I misinterpreted the code, just tested and the result is `[""]`, so one one Array with size 1 and that one element is an empty string. So it's still behaving as expected, the only issue is that the empty string is not visible when you `print()` the array, which is why it looks like an empty array (`[]`).

BTW, `var arr = Array(text.split("", false))` would give you what you expect, as the boolean parameter means that empty strings will not be returned.
