### ISSUE TITLE
Add Input.parse_action()

### ISSUE THREAD

**Issue by menip** [godotengine/godot#29363]
Input currently has [`parse_input_event()`](https://docs.godotengine.org/en/3.1/classes/class_input.html#class-input-method-parse-input-event). In order to simulate an action, you currently have to do something like: 
```
var action_event_list = InputMap.get_action_list("action")
var some_action_event = action_event_list[0]
Input.parse_input_event(some_action_event)
```

It would instead be convenient to be able to `Input.parse_action("action")`.

**Comment by KoBeWi** [comment]
You can also write the above code as a one-liner:
`Input.parse_input_event(InputMap.get_action_list("action")[0])`

**Comment by groud** [comment]
This feature is not needed to me. You can already create custom action events easily with InputEventAction.
Example:
```
var event = InputEventAction.new()
event.action = "ui_accept"
event.pressed = true
Input.parse_input_event(event)
```

**Comment by menip** [comment]
@KoBeWi I know, and that is how I have it in my game. I split it into multiple lines to be more readable.

**Comment by menip** [comment]
@groud I did not know this. That is indeed a much more fluid. 

I'll keep issue open for a week and see what other discussion we get.

**Comment by Xrayez** [comment]
Just to note, if you don't need to parse input events from actions alone, you can currently manipulate action states with:

```gdscript
Input.action_press(action)
Input.action_release(action)
```

They don't force to trigger `_input()` callbacks though, so this is only useful if you process your input with `Input.is_action_pressed` over `event.is_action_pressed` API and similar methods.

See also godotengine/godot-proposals#104 which could allow to have a complete control over the input (actions) state.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
