### ISSUE TITLE
Godot doesn't see changes in tool scripts until the editor is restarted when using an external editor

### ISSUE THREAD

**Issue by Jeremi360** [godotengine/godot#29379]
___

***Note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
3.1.1

**OS/device including version:**
LinuxMint 19.1 64bit

**Issue description:**
Godot 3.1.1 don't see changes in scripts that use keywords: `tool`, `export` until restart editor.
If I change anything in script that use keywords: `tool`, `export` it will still see the same errors as before and don't update inspector gui.

**Steps to reproduce:**
1. Crate new script in scene it can be any type
1. Add `tool` keyword on top
1. Add `export` var `test`
1. Check if inspector gui is changed
1. Try change something about `test`
1. Check if inspector gui is changed

**Comment by KoBeWi** [comment]
Are you sure it never updates, or until first reload? (btw, you can reload scene instead of restarting editor)

The only suspicious behavior I can confirm is that when changing export variable in tool script, it doesn't update the stored unchanged value.

**Comment by adrianperreault** [comment]
I've run into this same issue when editing tool scripts in an external editor (VS Code). 

For example, while editing a Curve node's "curve_changed()" signal handler, the updated functionality does not propagate until I switch to the Script tab in Godot, make a change (eg. put a blank space/anything), hit save, then switch back to the 3D view.

**Comment by jebedaia360** [comment]
@abhaskumarsinha O didn't thought about this that using external editor can causing that I use VSCode and Atom when I have this bug so maybe it is bug with external editor then.

PS.: VSCode godot-tool are dead :( , consider using atom with language-gdscript

**Comment by jebedaia360** [comment]
It is these same bug as this: #21956

**Comment by khoulihan** [comment]
This also seems to be happening for me in 3.2. I am using Atom as an external editor. I hadn't associated it with using those keywords, but all I have done since I switched to using the external editor has been work on tooling, and I keep having to restart Godot because it is not picking up my changes.

**Comment by KoBeWi** [comment]
Still valid in 3.2.4 beta4

Interestingly, you can use Soft Reload option in the script editor menu to reload the script properly.

**Comment by MikeSchulze** [comment]
I can confirm this bug is still valid in  v3.3.2.stable.officia.
I build an plugin update tool and override existing classes to update to new version but Godot still shows the old content.
It  happens for all script classes!

Forkflow
* run the update from a tool
* disable the plugin
* override existing plugin script classes by downloaded content form github
* force manually rescan
* enable the plugin

The plugin is broken because of invalid script classes (is sitll the old content)
Only restart Godot helps

I tryed to force update the filesystem manually by using the EditorFileSystem but it not helps.
````
func rescan(update_scripts :bool = false) -> void:
	yield(get_tree(), "idle_frame")
	var plugin := EditorPlugin.new()
	var fs := plugin.get_editor_interface().get_resource_filesystem()
	fs.scan_sources()
	while fs.is_scanning():
		yield(get_tree().create_timer(1), "timeout")
	if update_scripts:
		plugin.get_editor_interface().get_resource_filesystem().update_script_classes()
	plugin.free()
``` 

This is realy fustrating and blocks my to finish the update.

**Comment by benpm** [comment]
I'm experiencing this issue in 3.3.4.stable.official

**Comment by KoBeWi** [comment]
Can't reproduce in 4.4.
