### ISSUE TITLE
Godot should support import dependencies

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#29374]
When everything we need to support can be described in single file and goes auto - there is no problem. The problem arises when several objects are needed to be processed by import script - for example we build special texture out of a set of pngs. Alternatively - having large number of animations imported as several .escn files which are used to build single Godot scene's AnimationPlayer but are manageable only as separate files; Creating octree paging maps at import time so that all objects are loaded only when player visits certain world coordinates. All that stuff depends on running other importers first and then running second or third pass.

Current workaround is to tamper .import directory files when dependency change is detected by run of appropriate .import script, but this requires losing/gaining focus of Godot window several times (depending on dependency steps) which is ugly and hard to consider feasible solution.

I think better solution would be somehow to specify dependencies between import scripts, which would allow to re-import dependant assets when dependency changes.
Another alternative would be multi-import scripts which will handle dependencies inside. Any ideas?

**Comment by Calinou** [comment]
> Current workaround is to tamper .import directory files when dependency change is detected by run of appropriate .import script, but this requires losing/gaining focus of Godot window several times (depending on dependency steps) which is ugly and hard to consider feasible solution.

Maybe we could have an opt-in editor setting to reimport assets even if the window is not focused. This could also speed up the 3D workflow if you don't care much about CPU usage (e.g. on a desktop).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
