### ISSUE TITLE
Game crashes and scene becomes corrupted when you set "\" as node name

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#29401]
![Captura de pantalla de 2019-06-02 10-40-52](https://user-images.githubusercontent.com/19626687/58763646-0e31b900-8523-11e9-840d-3dfb8bac67e7.png)

I get the following error:
` drivers/unix/net_socket_posix.cpp:199 - Socket error: 104`

It basically makes my project to crash and makes my scene to be corrupted.

>Steps to Reproduce:
Basically I simply was making a calculator layout and in the last step when I inputed the = final button, I set my minimal size to 120 while it's parent was 60, then hit play and the game crashes.

>OS
Lubuntu last version.

>Minimal project
[Calculator.zip](https://github.com/godotengine/godot/files/3244955/Calculator.zip)

EDIT:
Can confirm the bug happens, and after testing It seems these steps cause it to happen.
- Add HSeparator as the first element in a VBoxContainer
- Set the VBoxContainer min size to 60x 60y
- Set the min size to 60x 60y
- Add buttons of also the same 60x 60y size after the HSeparator
- Hit play

Scene becomes corrupted.

**Comment by CowThing** [comment]
I don't think it has anything to do with the min size. I could not reproduce it at all no matter what I tried to do with min size, even following your steps exactly.

Looking at the TSCN file the error is happening because one of the nodes has the name "\" which I'm guessing is breaking the scene loader. If you open the TSCN file and manually change the name to "/" is works again and can be opened. However inside Godot you can't set the name of a node to "/" because / is an illegal character for node names. The character "\" should probably be an illegal too since it breaks the TSCN.

**Comment by ca3games** [comment]
> I don't think it has anything to do with the min size. I could not reproduce it at all no matter what I tried to do with min size, even following your steps exactly.
> 
> Looking at the TSCN file the error is happening because one of the nodes has the name "" which I'm guessing is breaking the scene loader. If you open the TSCN file and manually change the name to "/" is works again and can be opened. However inside Godot you can't set the name of a node to "/" because / is an illegal character for node names. The character "" should probably be an illegal too since it breaks the TSCN.

Oh, I remember setting up \ as the node name, in any case it seems \ is an allowed name and this could be the cause of the crash of the scene.
Maybe godot should warn about "\" as node name.

**Comment by bojidar-bg** [comment]
I guess the problem is because it treats `"\"` as a string starting with an escaped " character, while it should be `"\\"` for things to work properly.

Serialization:
https://github.com/godotengine/godot/blob/b9dc2e7e4dd38621ef0dd07d208ffc5468954adb/scene/resources/resource_format_text.cpp#L1715

Deserialization:
https://github.com/godotengine/godot/blob/b9dc2e7e4dd38621ef0dd07d208ffc5468954adb/scene/resources/resource_format_text.cpp#L206-L208
https://github.com/godotengine/godot/blob/b9dc2e7e4dd38621ef0dd07d208ffc5468954adb/scene/resources/resource_format_text.cpp#L274
https://github.com/godotengine/godot/blob/b9dc2e7e4dd38621ef0dd07d208ffc5468954adb/core/variant_parser.cpp#L1458-L1460
https://github.com/godotengine/godot/blob/b9dc2e7e4dd38621ef0dd07d208ffc5468954adb/core/variant_parser.cpp#L214

Seems like the deserialization code works fine, but the serialization code could use `String.c_escape`, like it does when saving groups a bit later. Note that the same probably applies to saving parent and owner.
