### ISSUE TITLE
Ability to use AnimationTreePlayer with AnimatedSprite instead of AnimationPlayer

### ISSUE THREAD

**Issue by fogine** [godotengine/godot#29403]
**Godot version:**

> v3.1.1

**OS/device including version:**

not related

**Issue description:**

It would be great if `AnimationTreePlayer`  could be used with `AnimatedSprite`.  
I have bunch of sprite animations of a character and need to dynamically combine them. `AnimationTreePlayer` requires you to use `AnimationPlayer` which is not really usable for sprite animations.

**Comment by golddotasksquestions** [comment]
Though I agree with you it would be nice to also have the AnimationTreePlayer work with AnimatedSprite node as well, I would definitely not want to have work with it **instead**. 
AnimationPlayer is actually a lot more powerful for sprite animation than the AnimatedSprite Node.
There are many ways you can set this up, but this one is the most straight forward and easiest, I found:
https://www.youtube.com/watch?v=M4wuhFgubWY 
(That's 3.0, but the Sprite+AnimationPlayer workflow is the same in 3.1)

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
