### ISSUE TITLE
Linux export under windows no longer possible

### ISSUE THREAD

**Issue by scottkunkel** [godotengine/godot#29416]
**Godot version:**

starting with commit
cd4449e7abe97b2bc883e2d182db2cc41eb35f8c

**OS/device including version:**

Win 10

**Issue description:**

Export to Linux when in windows results in
ERROR: FileAccessWindows::_set_unix_permissions: Windows does not support unix permissions
   At: drivers\windows\file_access_windows.cpp:348
ERROR: ProjectExportDialog::_export_project_to_path: Failed to export the project for platform 'Linux/X11'.
   At: editor\project_export.cpp:973

executable created, pck file not

**Steps to reproduce:**

**Minimal reproduction project:**

Recommendation:
Allow unix export and deal with required chmod by creating shell script that takes care of this.

**Comment by Calinou** [comment]
> Recommendation:
Allow unix export and deal with required chmod by creating shell script that takes care of this.

We don't have to do that; we can probably just disable the `chmod()` call on Windows using an `#ifdef`.

**Comment by bojidar-bg** [comment]
`DirAccess::copy` handles this properly:
https://github.com/godotengine/godot/blob/1abca6269780d08409c5907cb2b2ba54a674514d/core/os/dir_access.cpp#L333-L336

But, `FileAccessWindows::_set_unix_permissions` returns something unexpected (Should be `ERR_UNAVAILABLE` instead of `FAILED`):
https://github.com/godotengine/godot/blob/1abca6269780d08409c5907cb2b2ba54a674514d/drivers/windows/file_access_windows.cpp#L347-L350

The latter function comes from cd4449e7abe97b2bc883e2d182db2cc41eb35f8c, and indeed,  everything should have worked properly before that.

Note that there are some other functions which might get switched to `ERR_UNAVAILABLE`, in `FileAccessEncrypted`, `FileAccessNetwork`, `FileAccessPack`, `FileAccessZip`, `FileAccessAndroid`, `FileAccessJAndroid`. Not sure about `FileAccessCompressed`, though.
Tagging as junior job, as it should be easy to fix (and test!) the issue.

**Comment by scottkunkel** [comment]
Awesome, thanks.
It works now.
