### ISSUE TITLE
display modes for invisible objects 2d editor (boundbox)

### ISSUE THREAD

**Issue by danilojr** [godotengine/godot#2945]
This is a feature request! 

Can we have display modes in the 2d editor too?

So it would be easier to work on the levels, even when some objects are invisible.

Something like this:
![displaymode-boundbox-godot](https://cloud.githubusercontent.com/assets/13174433/11456461/7b72df06-9668-11e5-9454-8e4ea5388e38.jpeg)

(sorry my english)

**Comment by akien-mga** [comment]
CC @groud @poke1024 - is that something you would find useful for the 2D canvas editor? (asking since we're kind of going in the opposite direction right now :))

**Comment by groud** [comment]
I don't know. I don't get how making invisible nodes visible would help.
This feature proposal is a little bit unclear to me.

**Comment by poke1024** [comment]
Not sure either. Wouldn't be too hard to implement I guess, but I'm not sure there's a real use case. I could imagine something like this might be useful in some complex scenes with large objects, where you could turn on some kind of wireframe mode, so you can see objects behind the large ones in front - but that's a different use case the OP describes.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
