### ISSUE TITLE
Godot sometimes cut right side of editor, even after resizing

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29495]
**Godot version:**
3.2.dev.custom_build. 197b65f32

**OS/device including version:**
Ubuntu 19.04

**Steps to reproduce:(Open in new window)**
![file](https://user-images.githubusercontent.com/41945903/58933470-a7511180-8767-11e9-80c8-504b7c8bf2be.gif)

**Comment by LinuxUserGD** [comment]
Antergos (Arch Linux) with Godot master

I can reproduce that the content is too big when making the window smaller but for me it's resizing correctly when I move the window out of the edge.

**Comment by Houkime** [comment]
Reproducible with dwm (godot master on Arch Linux).
However I'm not realy sure how a correct behavior should be like in this scenario.
It is not like Godot ahave a mobile version of interface or sth.

**Comment by HugeGameArtGD** [comment]
@Houkime I'm using deepin window manager. Do you use gnome?

**Comment by LinuxUserGD** [comment]
@Houkime I'm using deepin window manager. Do you use gnome?

**Comment by LinuxUserGD** [comment]
Oh sry, dwm

**Comment by qarmin** [comment]
@groud @jbuck3 bisect shows that this is regression from https://github.com/godotengine/godot/pull/28952

**Comment by volzhs** [comment]
similar issue #29289

**Comment by groud** [comment]
@qarmin ah you are right. Though I think the fix is good.
The problem is likely from somewhere else I'd guess.

**Comment by jbuck3** [comment]
@groud I think it's directly related. The culprit seems to be the toolbar near the top of each workspace. It has different minimum sizes depending on which workspace the editor is using (3D<2D<Script<AssetLib). If you shrink the editor down and switch to a workspace with a bigger toolbar (in qarmin's gif, 2D->Script), the toolbar's right margin now gets "locked" where it previously didn't. (Notice that the right-hand content gets cut off by a constant amount when resizing.) I guess the solution would be, when the window gets resized, check if the toolbar is pushing stuff off-screen, and if so, try shrinking it. Though I'm not sure exactly where/how to do that. What do you think?

**Comment by tinmanjuggernaut** [comment]
This also affects windows and 3.1.1(though fixible without a restart, but annoying in distraction free mode). See #30787 for notes.

**Comment by sergey6661313** [comment]
why closed? This bug is still present on windows 10.

**Comment by tinmanjuggernaut** [comment]
> why closed? This bug is still present on windows 10.

Is what you are experiencing covered by this issue? 
https://github.com/godotengine/godot/issues/31133

**Comment by sergey6661313** [comment]
> > why closed? This bug is still present on windows 10.
> 
> Is what you are experiencing covered by this issue? #31133

yes it is.
