### ISSUE TITLE
I can't use animationtree node

### ISSUE THREAD

**Issue by gravit22** [godotengine/godot#29528]
**Godot version:**
3.1.1

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When I try to travel on Animationtree node I have an error in the inspector

**Steps to reproduce:**
Just run the scene I attached and check the errors that occurs.

**Minimal reproduction project:**
I attached
[Animation scene.zip](https://github.com/godotengine/godot/files/3260368/Animation.scene.zip)

**Comment by groud** [comment]
Can you copy paste the error here ?

**Comment by gravit22** [comment]
Thank you for interest. Sure. 
![image](https://user-images.githubusercontent.com/33228017/59017600-9a5a1e00-884c-11e9-9b0d-d6cd049d869d.png)

**Comment by pouleyKetchoupp** [comment]
Tested again on 3.2 beta 2. The error message is now displayed correctly:
![image](https://user-images.githubusercontent.com/1075032/69893965-ed52f080-1318-11ea-8c9d-5775d718ee17.png)

Which makes sense in this use case because the state machine has no start node and we're trying to travel with nowhere to start from.

But:
It does still show the same error message when there is a start node defined. That's because the state machine needs to be processed at least once to start playing the start node. So any call to `travel()` in `_ready()` would cause this error.
I think this case can be expected to be handled.

**Comment by akien-mga** [comment]
Closing as the issue was with the user project.

The "But" part in https://github.com/godotengine/godot/issues/29528#issuecomment-559902987 was fixed by #34011.
