### ISSUE TITLE
Allow split to use regex to split strings

### ISSUE THREAD

**Issue by davehayes** [godotengine/godot#29554]
**Godot version:**
 3.1

**OS/device including version:**
FreeBSD 11.2, but not really relevant

**Issue description:**
This is a lower priority feature request. Please allow a regular expression argument to ```split``` so splitting textual user input by whitespace (e.g. ```\s+```) is easier and less prone to coding errors. Thanks in advance!

**Comment by ibrahn** [comment]
This can probably be well served by the existing [RegEx](https://docs.godotengine.org/en/latest/classes/class_regex.html) class.
For example:
```gdscript
var r = RegEx.new()
r.compile("\\S+") # negated whitespace character class
for m in r.search_all("One  Two \n\tThree"):
	print('"', m.get_string(), '"')
```
```
"One"
"Two"
"Three"
```
Though if you want to detect empty leading/trailing matches when the input string begins/ends with whitespace, a more complex pattern is needed.

If a split-on-regex function is still required, it would probably be best to add it to the `RegEx` class rather than `String`. Regex is currently a separate module, so (theoretically at least) the engine can be built with it disabled.

**Comment by davehayes** [comment]
I had no idea the RegEx class had that method. That works just as well. Thank you!

In my view, the ```search_all``` function is effectively a more powerful ```split```. So it would seem to me it is actually not needed. However, perhaps your example should be referred to in the ```split``` documentation? (This is why I'm not closing this outright. :) )

**Comment by davehayes** [comment]
An addendum to this. Because `join` is a `PoolStringArray` method, is there any issue with making the return value of `search_all` a `PoolStringArray` rather than an `Array`?

**Comment by ibrahn** [comment]
RegEx::search_all returns an Array of RegExMatch, rather than Strings.
A RegExMatch is more complex than a single string as it can refer to multiple capture groups.

**Comment by mhilbrunner** [comment]
Moved to a docs issue: https://github.com/godotengine/godot-docs/issues/3607
