### ISSUE TITLE
Editor move camera with gizmo hotkey

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#29563]
**Godot version:**
3.1

**OS/device including version:**
linux

**Issue description:**
When moving objects around the scene in the editor, it would be useful to have a hotkey (shift) when using the move tool and this would 'lock' the camera to the selected gizmo while the key is pressed.

**Comment by Gibbz** [comment]
I can kind of emulate this by holding down the F key, however that is very laggy and janky.

**Comment by KoBeWi** [comment]
You mean something like moving a node together with the view?

**Comment by Gibbz** [comment]
Hey I checked that out. Space doesnt do anything when I am moving a node in the editor viewport.

Move a node around the viewport, and hold 'f' while doing it to get an idea of what I want :)

**Comment by KoBeWi** [comment]
> Space doesnt do anything when I am moving a node in the editor viewport.

Weird, it should. You can try middle mouse button too. (also, which version did you try? I mean the whole version string)

**Comment by Gibbz** [comment]
Editor version 3.2 abbbde87e

Ive done a little video of what id like to see. Obviously holding F is not designed for what im doing with it, and so is very janky.
https://youtu.be/T-gO6QGQW7E

**Comment by Calinou** [comment]
We already use <kbd>Shift</kbd> for precise snapping, so we could use <kbd>Alt</kbd> for this instead.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
