### ISSUE TITLE
AudioStreamPlayer3D option for distance fade only instead of always having directional audio / attenuation

### ISSUE THREAD

**Issue by ThunderFD** [godotengine/godot#29585]
As far as I can tell, there's no option on the node itself to disable the directional audio L / R attenuation.

It'd be nice if that could be turned off, so that just a distance fade/attenuation is left!

**Comment by NilsIrl** [comment]
@ThunderFD could you use an AudioStreamPlayer2D and manually change the sound levels based on distances?

**Comment by Calinou** [comment]
@NilsIrl AudioStreamPlayer2D is still positional, but AudioStreamPlayer isn't. You probably had AudioStreamPlayer in mind :smiley:

**Comment by NilsIrl** [comment]
> @NilsIrl AudioStreamPlayer2D is still positional, but AudioStreamPlayer isn't. You probably had AudioStreamPlayer in mind smiley

Sorry my bad, I really meant AudioStreamPlayer

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
