### ISSUE TITLE
Return the array key when appending a new item

### ISSUE THREAD

**Issue by cobreen** [godotengine/godot#29620]
Is it a good idea to return the array key when appending a new item to it?

Example: 
```
var arr=[]

var key = arr.append(123)#0

var key1 = arr.append(321)#1
```

**Comment by akien-mga** [comment]
What would be the use case? Does any language do this on their `append` or `push_back` methods?

I don't see much point in returning this value which would always be the size of the array minus 1, i.e the index of the last element. If you need it, you can just get `arr.size() - 1`.

To return this value, `append()` would actually need to call this too, this index information is not readily available to return. (See `Array::push_back()` in `core/array.cpp`). And the `Vector<T>::push_back()` it calls from `core/vector.h` already returns a boolean value to indicate failure or success, so it can't return the index.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
