### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by I7SOD** [godotengine/godot#29642]
**Godot version:**

**OS/device including version:**

Windows 8.1 Godot v.3.1 stable

**Issue description:**

The export does not export an application with the name given it. It shows the project name.Also the icon still remains as Godot icon even if it is changed 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by scottkunkel** [comment]
I am going on a limb here and assume that you are trying to export to it as a windows executable.
In order to change the icon, you have to create an ico file with multiple resolutions. 
This can do it for you: https://icoconvert.com/
 Also, point the editor to your rcedit file as specified in https://docs.godotengine.org/en/3.1/getting_started/workflow/export/changing_application_icon_for_windows.html
The name of the project is set in the Project editor. The executable name is set in the export settings, though.
Everything is laid out here:
https://docs.godotengine.org/en/3.1/getting_started/workflow/export/index.html

**Comment by StraToN** [comment]
@I7SOD Please provide more information on your problem regarding export.

Concerning the icon problem, it is already known #21347

**Comment by akien-mga** [comment]
It should work fine if you follow instructions on https://docs.godotengine.org/en/3.1/getting_started/workflow/export/changing_application_icon_for_windows.html
