### ISSUE TITLE
External editor isn't working without specifying exec flags

### ISSUE THREAD

**Issue by marcospb19** [godotengine/godot#29662]
**Godot version: 3.1 and 3.2.dev.custom.build...**

**OS: i3-Manjaro Linux**

**Issue description:**
> Using Sublime Text (or other editor) as an external text editor is not
> working, "Exec Path" isn't executing any command.

**Steps to reproduce**
1. Go to Editor -> Editor Settings -> Text Editor -> External.
2. Check the checkbox "Use External Editor".
3. Type "/usr/bin/subl" inside of "Exec Path".
4. Click on "close".
5. Attach a script to a new Node, and wait for it to opens or do any other action that opens the script on the text editor.
 
**Expected behavior:**
> Open sublime text editor

**Current behavior:**
> Do nothing

**Minimal reproduction project:**
> Any empty project with only one node

**Also:**
> I tried inserting any application command path to "Exec Path", but none
> applications opened, shouldn't the "Exec Path" just be run when I try to open
> a script?

> I also tried to debug this using --verbose argument, but as soon as I open a
> project, the application is disowned from the PPID ( -> 1) and I can't track
> the output anymore.

Reproduced in 3.1 stable and updated source code from 2 hours ago.

**Comment by akien-mga** [comment]
It works fine for me on Mageia 7 (tested with Kate) provided that Exec Flags are properly set according to the documentation: https://docs.godotengine.org/en/3.1/getting_started/editor/external_editor.html

The problem is that the external editor code does not pass the script path if you don't use the `{file}` placeholder in the flags:
https://github.com/godotengine/godot/blob/629bc10d80414570d18e0d918e59a116cb68dced/editor/plugins/script_editor_plugin.cpp#L1968-L2009

This fixes it as most external editors support `editor-name /path/to/file` as a way to open a given file, so I think the file path should always be passed if no custom Exec Flags are set:
```diff
diff --git a/editor/plugins/script_editor_plugin.cpp b/editor/plugins/script_editor_plugin.cpp
index 641c387c6..333eccfd1 100644
--- a/editor/plugins/script_editor_plugin.cpp
+++ b/editor/plugins/script_editor_plugin.cpp
@@ -1969,10 +1969,10 @@ bool ScriptEditor::edit(const RES &p_resource, int p_line, int p_col, bool p_gra
 		String flags = EditorSettings::get_singleton()->get("text_editor/external/exec_flags");
 
 		List<String> args;
+		String script_path = ProjectSettings::get_singleton()->globalize_path(p_resource->get_path());
 
 		if (flags.size()) {
 			String project_path = ProjectSettings::get_singleton()->get_resource_path();
-			String script_path = ProjectSettings::get_singleton()->globalize_path(p_resource->get_path());
 
 			flags = flags.replacen("{line}", itos(p_line > 0 ? p_line : 0));
 			flags = flags.replacen("{col}", itos(p_col));
@@ -2006,6 +2006,8 @@ bool ScriptEditor::edit(const RES &p_resource, int p_line, int p_col, bool p_gra
 					num_chars++;
 				}
 			}
+		} else {
+			args.push_back(script_path);
 		}
 
 		Error err = OS::get_singleton()->execute(path, args, false);
```

It could be further improved however, by adding a default `{file}` Exec Flags, and a placeholder text mentioning the various supported placeholders (I don't think we have tooltips/documentation for editor settings yet, but when we do the relevant info should go there).

Alternatively, there could be a drop down list with pre-configured Exec Flags for different editors (matching the documentation), with an option to set a custom one for advanced users.

**Comment by marcospb19** [comment]
Thanks for the commit, but this still isn't working for me, i'm trying to debug the problem and find out if it have something to do with linux symbolic links, i don't know exactly how to debug this. I will investigate this file.

`editor/plugins/script_editor_plugin.cpp`

**Comment by marcospb19** [comment]
I realized that the problem is only occurring when opening a built-in script, it just won't open inside of sublime, is this intended?

**Comment by marcospb19** [comment]
I will open another issue, because the problem i detected is different from what @akien-mga made this about.

New issue: _pending_
