### ISSUE TITLE
Normalize two vectors on a Vector3

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#29665]
I suggest to add the ability to normalize only two vectors on a Vector3 to be able to separate the gravity and jump of a KinematicBody from the direction.
The normalize would take three arguments all set to true by default.

To normalize the direction without the y gravity it would look like this:

```
if Input.is_action_pressed("ui_up"):
	velocity += -global_transform.basis.z * speed
if Input.is_action_pressed("ui_down"):
	velocity += global_transform.basis.z * speed
if Input.is_action_pressed("ui_left"):
	velocity += -global_transform.basis.x * speed
if Input.is_action_pressed("ui_right"):
	velocity += global_transform.basis.x * speed

velocity.y -= GRAVITY # Gravity
velocity = velocity.normalized(true, false, true)
```

**Comment by mrcdk** [comment]
I don't understand this issue. How do you normalize that way?  Normalizing a vector is basically keeping the direction but changing the magnitude to 1 (the length) You can't skip one coordinate because you need all of them to get the normalized vector. Sorry but what you are asking isn't a normalized vector and it makes little sense.

The example doesn't make any sense either. You are adding the speed but then you "normalize" it removing the speed multiplication? why? I really don't understand what you are trying to do.

**Comment by swarnimarun** [comment]
Would you mind doing it like, `Vector2(vel.x, vel.z).normalized()`

**Comment by akien-mga** [comment]
It doesn't make sense indeed, you can't "normalize" a vector with only two components. If what you want is a normalized vector to which the gravity is later added, you can do:
```
if Input.is_action_pressed("ui_up"):
	velocity += -global_transform.basis.z * speed
if Input.is_action_pressed("ui_down"):
	velocity += global_transform.basis.z * speed
if Input.is_action_pressed("ui_left"):
	velocity += -global_transform.basis.x * speed
if Input.is_action_pressed("ui_right"):
	velocity += global_transform.basis.x * speed

velocity = velocity.normalized()
velocity.y -= GRAVITY # Gravity
```

But BTW, normalizing the speed also doesn't really make sense. What you have to normalize is the directional vector, *to which* you would then apply a speed factor or gravity.

**Comment by lawnjelly** [comment]
> Would you mind doing it like, `Vector2(vel.x, vel.z).normalized()`

Agree with swarnimarun, can already be done longhand. The question is whether it would be something you would realistically do often enough to warrant a specific function?

On the other hand you could argue the same for all Vector2 functions on components of Vector3. A better solution for all this would be to have a way of accessing 2 components of a Vector3 as a Vector2, thus allowing all the Vector2 functions to be called.

You might be able to have it access components something like this:
`velocity.xz() = velocity.xz().normalized()`
for a more generalized method. I use something like this in my c++ vector templates.

**Comment by Linko-3D** [comment]
> If what you want is a normalized vector to which the gravity is later added

I have added the gravity after normalizing the Vector3 and the gravity gets normalized too I don't know why (falling slowly and linearly and slower when moving), this is why I have added this suggestion.

I have also made a vector 2 and copied his x setting to the Vector 3 and Y to the Vector 3 Z, then normalized and added the gravity and it doesn't work.

> velocity.xz() = velocity.xz().normalized()

Good idea but it would require a method for each combination possible.

**Comment by alexjamesritchie** [comment]
In that above example, you are definitely normalizing your gravity. Since this runs every physics tick the gravity you applied last tick is normalized along with your input. On top of which you then apply gravity. So your gravity over time wont actually be growing here.

The reason you fall a little faster when you're not moving is because your gravity is the only thing affecting the vector and so when it's normalized it becomes Vector3(0, -1, 0). And then you are removing 0.15 making your maximum total gravity -1.15 That is the largest it can ever be. Hopefully that makes sense, I'm pretty new to this

**Comment by aaronfranke** [comment]
You can just do this:

    var horizontal = Vector2(velocity.x, velocity.z)
    horizontal = horizontal.normalized()
    velocity.x = horizontal.x
    velocity.z = horizontal.y

Or just keep track of horizontal velocity separately (only determined by input and normalization) and then set velocity's horizontal components from scratch each time.

**Comment by Calinou** [comment]
Closing due to lack of support (see the above comments).
