### ISSUE TITLE
The maximum white value for tonemapping should be detected automatically.

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#29666]
I suggest that the maximum white value in the scene (including the HDRI panorama) gets detected automatically for tonemapping like other engines do.

**Comment by StraToN** [comment]
For what cases do you need this?
Godot already provides the ReinhardtAutoWhite tonemapper that adjusts the white value according to maximum luminance : https://docs.godotengine.org/en/3.1/tutorials/3d/high_dynamic_range.html?highlight=Reinhardt#tonemapper

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
