### ISSUE TITLE
Platform support suggestion

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#29672]
![platforms](https://user-images.githubusercontent.com/1850856/59259287-2f408b00-8c42-11e9-9ea0-5af5497e5132.png)
I think it could be useful adding platform support icons next to classes. In most cases the platforms a class supports isn't even documented and this could be a straight forward way to address this.

**Comment by Calinou** [comment]
Which classes can be considered *fully* OS-specific?

**Comment by zaksnet** [comment]
TCP_Server is only for desktops for example, while WebSockets is for HTML. They don't have to be fully OS-specific. You're right, the icons could either be visible only for the selected item or be visible only inside the documentation page.

**Comment by ArdaE** [comment]
Instead of displaying them just for the selected item or for all items, you could display them for **all classes that have a platform restriction** and not for those that don't. This way, classes that are generic would never display any icons, while the presence of one or more icons next to a class name would immediately indicate that the class is supported on a limited subset of platforms. It's like the icons list said "Only available on", without really spelling it out (which could be a hint when the mouse hovers over).

**Comment by zaksnet** [comment]
So many classes are not available for HTML by the way. I'm currently lost as to what breaks the HTML version of my app.

**Comment by zaksnet** [comment]
I'v found out how to add an icon at the documentation with:
`class_desc->add_image(get_icon("", ""));`
But i can't figure out how to add icons in the database so far :/. If someone can point me out to the right direction so i can possibly do some tests and see live results i'd be gratefull.
