### ISSUE TITLE
Button signals do not work after reparenting node at runtime

### ISSUE THREAD

**Issue by PonasKovas** [godotengine/godot#29682]
**Godot version:**
Godot 3.1.1

**OS/device including version:**
ArchLinux

**Issue description:**
When I try to reparent a button with

```gdscript
var AnotherParent = get_node("path/to/another/parent")
get_parent().remove_child(self)
AnotherParent.add_child(self)
```

my signals stop working.

For example, if I reparent the button when it is clicked (`button_down` signal), then I won't receive `button_up` signal after releasing the mouse. However I can click again, and receive `button_down` again.

**Steps to reproduce:**
1. Add a button to a scene
2. Attach a script to that button
3. Connect `button_down` and `button_up` signals to itself
4. When button_down signal is called, reparent the button.

**Minimal reproduction project:**
[signals_when_reparenting.zip](https://github.com/godotengine/godot/files/3276842/signals_when_reparenting.zip)

**Comment by sparkart** [comment]
The callbacks still exist if you reparent.

I'm not sure if this is a bug or intended. The signals are probably thrown away when you remove the object.
The problem is the button_up signal doesn't get a chance to execute the callback before the object is removed. Alternatively, you would remove the object after you receive the signal and perform the callbacks.

**Comment by PonasKovas** [comment]
Well I'm just gonna share a workaround that I used to solve this problem.

Instead of using the signal `button_up` I used the `_input()` method.

```gdscript
var clicked = false

func button_down():
	clicked = true
	# reparent stuff

func _input(event):
	if event is InputEventMouseButton:
		if clicked and not event.pressed:
			clicked = false
			# reparent stuff
```

**Comment by kawa-yoiko** [comment]
Currently all UI elements seem to treat removed and invisible controls as losing focus. Do you have use cases where controls are moved in the tree? If it's general enough this behaviour could be changed.

Details: signals have nothing to do with this. It's caused by the viewport resetting the currently focused element on child removal.

https://github.com/godotengine/godot/blob/2c6daf73f3a1077dfae0ca88117a3f4b583eb7e6/scene/main/viewport.cpp#L2477-L2482

The button resets its state as well.

https://github.com/godotengine/godot/blob/2c6daf73f3a1077dfae0ca88117a3f4b583eb7e6/scene/gui/base_button.cpp#L121-L129

**Comment by PonasKovas** [comment]
> Do you have use cases where controls are moved in the tree? If it's general enough this behaviour could be changed.

Yeah. I was making an inventory system, where all items are in a scroll container, but when you pick an item up, and drag it somewhere, the picked up items would disappear if you dragged them outside of the scrollContainer bounds. So then I decided to move all picked up items to another container, and when they're released somewhere, move them back to the scrollContainer.

**Comment by KoBeWi** [comment]
I tried the project and I don't actually see any bug. The button_down signal is received correctly. The button_up doesn't arrive, because _it's never emitted_. The button is unpressed, however no via input, but due to being removed from the tree, so it doesn't emit the signal. Case closed.

**Comment by PinkSerenity** [comment]
> I tried the project and I don't actually see any bug. The button_down signal is received correctly. The button_up doesn't arrive, because _it's never emitted_. The button is unpressed, however no via input, but due to being removed from the tree, so it doesn't emit the signal. Case closed.

The issue is that it isn't called `remove_and_add_copy_as_child_of()`. Even the docs say: "Changes the parent of this Node to the `new_parent`." Of course experienced programmers, especially Godot devs, know how hard it actually is to implement "the node magically appears at a new position in the tree and nothing else changes", but don't game engines exist so that people can make games without having to bother with or even know what happens behind the scenes and how object-orientated code actually works?

The OP saw `reparent()`, they read "[c]hanges the parent" and they expected "node gets moved". If the actual behavior doesn't match the behavior a user understands as being implied and intended, then in my opinion it is a bug that might be either fixed by changing the names and descriptions or actually implementing the behavior. So saying that it isn't a bug because you as a developer know how the code works and is actually intended to work feels like a user gap.

I acknowledge though that the use cases of this behavior is very small and that an easy alternative already exists, so I don't think it's actually necessary to change anything in the engine, but at least the docs should mention the actual behaviour of removing and adding a copy. Also, please don't think I'm attacking you here, I just think that saying "it's intended to work that way" doesn't solve the original issue of a user reasonably expecting a different behavior.

**Comment by KoBeWi** [comment]
But `reparent()` does what it says - it changes the parent. The node is not copied or anything. Also no idea where you got it from if `reparent()` was never mentioned here (and didn't even exist at the time of this issue). I already explained why the "bug" is happening.

**Comment by PinkSerenity** [comment]
I'm sorry. It was late yesterday, I was trying to figure out the bug for hours and when I found it I just got impulsive and emotional. The same behavior happens with `reparent()` as well, but that's a seperate issue. I totally agree with you here, and I'm sorry for disturbing you. Gonna keep looking and maybe make a new issue.
