### ISSUE TITLE
Peer-to-Peer across NAT

### ISSUE THREAD

**Issue by ibenx** [godotengine/godot#2970]
Good article:
http://www.brynosaurus.com/pub/net/p2pnat/

Thanks

**Comment by TierraDelFuego** [comment]
The title caught my eye, so I will give my 2 cents. Just pasting a link for a feature request seems to be not very helpful or inspiring. But more importantly how would hole punching NAT become a Godot feature? That is an architectural feature of the game and seems completely outside the scope of a game engine. But maybe I am wrong and let me know how if I am.

If you are serious about this feature request I would bet you might need to explain in detail what you would want to see from Godot. I am watching because I may learn something.

**Comment by vnen** [comment]
I believe (and I'm not the only one) that Godot does lack higher-level networking. For now, it'd be somewhat strange to smash in this feature, but IIRC there'll be a revamp in the network module to include higher-level stuff (which will likely include NAT hole punching).

It is a feature a game engine can provide. Construct 2, for example, does have [NAT traversal](https://www.scirra.com/manual/174/multiplayer).

Though don't expect this to be included soon in Godot.

**Comment by reduz** [comment]
we'll add better higher level networking eventually

**Comment by Elinvention** [comment]
I think UPnP protocol support should be added to Godot. With UPnP you can get external IP address and set port forwarding on most routers.

**Comment by mhilbrunner** [comment]
Reopening, as this  is about UPnP too.
