### ISSUE TITLE
Export right icon (ricon) from Button to GDScript

### ISSUE THREAD

**Issue by silkentrance** [godotengine/godot#29719]
The Button class features a right icon (ricon) that is used internally by the Godot editor plugin.

It would be nice for this to be a public feature so that we can implement similar functionality (collapsed/not collapsed) using GDScript as well without the need for us to reinvent the wheel here.

**Comment by volzhs** [comment]
would you share a screenshot to specify which one of editor plugin?

**Comment by silkentrance** [comment]
Well it is mostly in the Inspector

![image](https://user-images.githubusercontent.com/6068824/59375989-8da75f80-8d4f-11e9-994f-19691e075b5a.png)

**Comment by jitspoe** [comment]
Looking at the button source, I only see one icon being drawn.  Are you sure there's a right icon and not just another button/image placed there?

Related, though, I think it would be good to expose a left/right/center alignment option for the icons, like the text has: https://github.com/godotengine/godot/issues/11380

**Comment by silkentrance** [comment]
@jitspoe Yes, thanks for pointing this out. I mixed that up with the lineedit control. What I meant was the collapsible section stuff implemented into the editor and that we should have such a feature in the normal gui elements as well.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(on a side note, the collapse/expand icon are drawn on the button by the inspector. You can already replicate this behavior with scripts)

**Comment by jitspoe** [comment]
I have a pull request here for centered and right-aligned icons: https://github.com/godotengine/godot/pull/37181
