### ISSUE TITLE
feature need: connect with xcode obj-c

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29739]
It is hard to build the engin package for begginer. I cost a lot of time on compile with admob feature. But several hours it don't work after many tries. I think there has any easy way for it. The engine can supply a view controller templete for connect with godot function or signal. It is  the easy way for conrol like iap system. Instead of download admob old version and compile it and long waiting and crash and so on.

**Comment by StraToN** [comment]
Godot does not come with admob feature by default so I assume you are using https://github.com/kloder-games/godot-admob. Sorry, we do not provide support for third-party modules. You'll have to ask its author.

A feature request for supporting mobile adds already exists so I think this issue duplicates #25559.

**Comment by zszen** [comment]
> Godot does not come with admob feature by default so I assume you are using https://github.com/kloder-games/godot-admob. Sorry, we do not provide support for third-party modules. You'll have to ask its author.
> 
> A feature request for supporting mobile ads already exists so I think this issue duplicates #25559.

I don't only discuss the admob support. I hopy offical engine give a simple way for support conect/extension.

**Comment by StraToN** [comment]
Concerning extensions to the core engine, you can have a look at [GDNative on the official documentation](https://docs.godotengine.org/en/3.1/tutorials/plugins/gdnative/index.html). This is currently the alternative to modules (such as godot-admob) that require a complete engine recompilation, while GDNative extensions act basically as libraries for Godot.

Concerning [editor plugins](https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/index.html), they are already supported since a long time.

**Comment by zszen** [comment]
@StraToN Thank you, I'll take a look.
