### ISSUE TITLE
Provide a vertical option for the gradient texture

### ISSUE THREAD

**Issue by ZX-WT** [godotengine/godot#29748]
**Issue description:**

I am using the visual shader editor and I need a vertical gradient, I can rotate the UV to fit my need but it is not a intuitive approach. 
Now, I make the texture in gimp, if there is a flag to toggle the orientation of the texture, it would save some time.

**Comment by NoodleSushi** [comment]
I'd like this feature myself. Couldn't make the gradient fill vertical for a Polygon2D, so I had to rely on textures for this.

**Comment by puthre** [comment]
I was trying to use it for a window dialog background (I was looking to rotate it by 45 degrees) but I guess I'll just have to do it in gimp

**Comment by NoodleSushi** [comment]
> Is there still demand for this? #31655
> 
> We are looking for more people who want this.

that would be great especially for prototyping!

**Comment by jcnauta** [comment]
I would also like this. Ideally with the possiblility to completely specify the direction of the gradient.

**Comment by SleepProgger** [comment]
Just another +1
https://github.com/godotengine/godot/pull/31655 would be optimal, but at least an option to switch between vertical and horizontal would be nice.

**Comment by DrZanuff** [comment]
+1 Here. Many times i needed this feature.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
