### ISSUE TITLE
Implement subword navigation option in the script editor

### ISSUE THREAD

**Issue by Keelar** [godotengine/godot#29789]
**Issue description:**
Most editors and IDEs nowadays support subword navigation, which allows you to hold control(usually) and use the arrow keys to navigate a chunk of text without skipping the whole thing. So with identifiers like `my_variable_name`, if the caret starts at `my_variable_name|` and you hold control and hit the left arrow, the caret would go to `my_variable_|name` instead of going to the beginning of the identifier. In addition to navigating snake case, it should also support camel case. This would also work for right arrow, backspace and delete. It would make renaming certain parts of variables a lot less annoying than it currently is.

I would love to see the Godot script editor support this feature.

**Comment by Calinou** [comment]
It seems underscores are already considered not to be part of words, according to https://github.com/godotengine/godot/blob/e9999290241d81ac6f67686cf3704705a430262c/core/ustring.cpp#L65-L66. However, subword navigation doesn't work with underscores in the script editor.

**Comment by hsandt** [comment]
Hi, I checked linked issue #46721, but it is about Text Server, which seems to be a runtime feature.

Unless it's also used by the engine itself for the script editor, but in this case, where is the editor setting equivalent to the usage example using TextServerManager?

If this doesn't help the script editor side, then we still need to work on the script editor to support either: an editor setting (flag) to consider underscore `_` a word breaker, or better, brand new shortcuts to navigate per sub-word, separated by underscore or upper characters, we the user can quickly switch between full word and sub-word navigation.

This would be a feature request, not a bug though, so it would go to the Proposals repository.

I'd just like to ask if it is intended by design not to break at underscores in the script editor right now.

- if by design, then we should "re-close" this issue as rejected (but not completed, as it would give a false impression to users checking this), and open a suggestion in the Proposals repository for subword navigation
- if not by design, then we should reopen this issue since the behaviour is still the same. We can still open a suggestion in the Proposals repository for subword navigation on top of that, since users who also need to old full-word navigation will benefit from an option to switch between both navigation modes

**Comment by hsandt** [comment]
Well, as you can see just above, I ended making a proposal so we can get started.
