### ISSUE TITLE
support for automatic connection to positional devices

### ISSUE THREAD

**Issue by draconicfae** [godotengine/godot#29794]
With ar/vr support slowly ramping up, I think it would be useful to have the ability to automatically pull in positionally tracked device information.  I'm not sure how this would work for all platforms but for x11 in particular my idea is :

1) If the device also has buttons (eg a VR controller) then it would have a device node that's seen as a joypad.  This node will have a base name (for instance "daydream controller")

2) If the device has a gyroscope, accelerometer, magnetometer,  it would have a device node for each of those things it has.  Each device node will support EV_ABS (and in particular ABS_X, ABS_Y, and ABS_Z) but NOT EV_KEY.  This will prevent these nodes from being erroneously detected as joypads because the joypad detection filter requires both EV_ABS and EV_KEY.  The name for these nodes will be base name followed by comma followed by what type of tracking information it's providing (eg "daydream controller, gyroscope"), thus enabling all the data streams for the same device to be coupled together.

3) There's already a class called ARVRPositionalTracker which seems ideal to marshal this sort of information.  It would be extended with Vector3 set methods, mirroring what InputDefault already has (set_accelerometer(), set_gyroscope(), set_magnetometer()) and potentially also the corresponding get methods.  set_name() would be called to set it to match base name, so that 2 can discover that there is indeed an appropriate tracker to update, which it will do on an ongoing basis the same way the joypad code updates button state on an ongoing basis.  In terms of associating the tracker with the joypad from 1, that can probably be done manually in the GDScript associated with the tracker node rather than complicating the joypad code.

I can code this if it has approval from a design standpoint.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
