### ISSUE TITLE
textureLod() not working with DEPTH_TEXTURE

### ISSUE THREAD

**Issue by DiV4** [godotengine/godot#29820]
Using standard x64 Godot 3.1.1 build.

I have a fullscreen quad with a shader which uses depth texture. The problem is that this texture is always aliased. I tried textureLod() with power of two float values, but it doesn't affect the result at all. Though it works just fine with SCREEN_TEXTURE.

To reproduce, make a billboard fullscreen quad and apply a shader that outputs depth texture.

[issue.zip](https://github.com/godotengine/godot/files/3293864/issue.zip)

**Comment by BastiaanOlij** [comment]
To do texture LOD you need to mipmap the texture, which isn't being done with the depth texture, would just waste a lot of performance for a very questionable use case. It is possibly done for the screen texture because the blur post process uses it but you may be reading the previous frames mipmaps as a result.

At full resolution depth texture map lookups should be pixel perfect.

**Comment by DiV4** [comment]
> 
> 
> To do texture LOD you need to mipmap the texture, which isn't being done with the depth texture, would just waste a lot of performance for a very questionable use case. It is possibly done for the screen texture because the blur post process uses it but you may be reading the previous frames mipmaps as a result.
> 
> At full resolution depth texture map lookups should be pixel perfect.

I see now. Thank you very much for explaining!
