### ISSUE TITLE
`DynamicFont::get_char_size()` doesn't take hinting into account

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#29834]
**Godot version:** Git https://github.com/godotengine/godot/commit/9c7cce3c9b8062817e976676ff0f4772971895cb

**OS/device including version:** Fedora 30, Clang 8.0.0

**Issue description:** `DynamicFont::get_char_size()` will always return the same value for a given font and size, regardless of the font hinting used. (Fonts without hinting usually appear to be less wide than fonts with hinting.)

For instance, this causes the line length guideline to be placed incorrectly, as the line length guideline's position is set using `get_char_size()`:

https://github.com/godotengine/godot/blob/9c7cce3c9b8062817e976676ff0f4772971895cb/scene/gui/text_edit.cpp#L1353

With the line length guideline enabled at its default value (80) and the code font size set to 13, the line length guideline will be placed on the 80th column when using the **Normal** hinting mode. This is the correct placement:

![font_size_13_hinting_normal](https://user-images.githubusercontent.com/180032/59569787-aa64cf80-908e-11e9-8a8b-2eea7e01752a.png)

However, when using the **None** hinting mode, the line length guideline will appear around the 89th column instead:

![font_size_13_hinting_none](https://user-images.githubusercontent.com/180032/59569790-c23c5380-908e-11e9-8a1f-4f5815f44667.png)

This doesn't appear to be a caching issue; restarting the editor after changing the code font hinting setting doesn't solve the issue.

**Steps to reproduce:** Set the **Code Font Hinting** setting to **None** in the Editor Settings.

**Comment by kawa-yoiko** [comment]
I believe it is a rounding issue in the editor module rather than a bug in `DynamicFont`, since FreeType already takes hinting into account in the `advance` amount ([FT docs](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_glyphslotrec), [Godot calculating `advance` with FT](https://github.com/godotengine/godot/blob/68081b3f6e57d4bda7e93ce2dd319fb564d347b8/scene/resources/dynamic_font.cpp#L625)).

I have sent a PR #30483, see there for details ^ ^
