### ISSUE TITLE
CameraServer has strange enum values

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29857]
**Godot version:**
3.2 master
![Zrzut ekranu z 2019-06-17 22-41-26](https://user-images.githubusercontent.com/41945903/59635375-61298400-9151-11e9-92f0-29abd1efcdf4.png)

**Issue description:**
It is strange that 3 values are equal 0 in one enum

**Comment by KoBeWi** [comment]
This looks weird, but at the same time seems deliberate (the values are explicitly written in code).

@BastiaanOlij ?

**Comment by YeldhamDev** [comment]
Also, as they are `enum` elements, shouldn't they be fully upper cased?

**Comment by BastiaanOlij** [comment]
This is indeed on purpose. These enums are indices into an array and depending on what camera you have each slot in the array may have a different purpose.

So a camera (or the camera library more accurately) that provides RGB images will use a single texture that can be used as is. 
Most cameras however return Y Cb Cr images often in two separate textures (a single channel image with the Y values and a dual channel image containing the Cb and Cr images often at half resolution). But again some camera libraries will upscale the CbCr image and combine it into a single 3 channel texture.

It is important to know this distinction because you can't use the textures as you can only render RGB images. For the other two options you have to use a shader that converts the YCbCr texture(s). We're not handling that conversion on the CPU because at camera framerates that just wastes precious resources especially on mobile phones while a GPU does it in a blink of an eye.

Lastly I've kept the b and r lowercase to denote these are 3 channels, Y, Cb, and Cr and because this is the common way these are written. Nothing more or less then that :)

**Comment by BastiaanOlij** [comment]
Could use more info on the help page about this btw, might have lost some of that info in the two years I've worked on this :)

**Comment by YeldhamDev** [comment]
> Lastly I've kept the b and r lowercase to denote these are 3 channels, Y, Cb, and Cr and because this is the common way these are written.

That still doesn't sound right. All `enum` elements throughout the code base are completely upper cased (unless an exception got under my radar), and I don't think this is enough of a reason to get inconsistent with everything else.

**Comment by BastiaanOlij** [comment]
> That still doesn't sound right. All `enum` elements throughout the code base are completely upper cased (unless an exception got under my radar), and I don't think this is enough of a reason to get inconsistent with everything else.

I'm more then happy to change it :)

**Comment by BastiaanOlij** [comment]
#29901 :)
