### ISSUE TITLE
"Theme" > "Button" > "Styles" > "StyleBoxTexture" won't unfold edit pane

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#29873]
**Godot version:**
3.1 stable.official

**OS/device including version:**
Windows 10 Home 

**Issue description:**
I added a  Theme for a popup dialog in a game i was making which also included buttons. When trying to add Button Styles for the theme i choose to go for "StyleBoxTexture". I found out that this is bugged. When clicking on to edit the Texture the whole Theme tab folds.

**Steps to reproduce:**
Use a Node which can have a Theme (Popup in my case)
Theme > Button > Styles > choose one of the states below e.g. "Disabled" >
From the dropdown choose "New StyleBoxTexture"
Click on the "StyleBoxTexture" 

Expected: should open a dropdown like when clicking on "Theme" or "Font"

Actually behaviour: closes the whole "Theme" tab

**Comment by KoBeWi** [comment]
Doesn't happen with other StyleBox types and also doesn't happen with StyleBoxTexture in `custom_styles`.

**Comment by sparkart** [comment]
I can take a look.

**Comment by Feniks-Gaming** [comment]
There is a way around it for now. If You first select New StyleBox Empty and expand it and then change it to StyleBox Texture it will remain expanded as expected. 

Not sure how useful this information is to anyone who is going to fix the issue.

**Comment by Feniks-Gaming** [comment]
@codecustard any success on this?

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/0aea0d0b39cfa8959350a0c89fde72d50999fc5f.

**Comment by codecustard** [comment]
Sorry, I lost track of this bug.... go for it if you're trying to fix it.

**Comment by ondesic** [comment]
This bug is still here in 3.2.1.  Can't unfold StyleBoxTexture inside a Theme

**Comment by mariothedog** [comment]
On Godot v3.2.2.stable.official, the issue still occurs if you create a new StyleBoxTexture and click on it to edit it. However, if you use click the arrow dropdown and click "edit" instead, it works.

**Comment by Haledire** [comment]
In the time I've messed with this, the main thread that seems to be the issue is that `StyleboxTexture` and `Theme` seem to be vying for the `Bottom Dock` entry.

Creating a `StyleboxTexture` opens the `Texture region editor` in the bottom dock.  Creating any other `Stylebox` and switching to `StyleboxTexture` avoids this behavior (which is why this workaround works).

You can see this behavior again if you take any theme element that takes an image and attempt to put an `AtlasTexture` into it.  If you make a new `AtlasTexture` directly into the `Texture` slot, the `Theme editor` will be closed because the `Texture region editor` is trying to open.  If you create a `Texture` type that doesn't have a `Texture region editor`, and then switch to `AtlasTexture`, the same behavior is seen as with the `StyleboxTexture` and other styleboxes.

I'm not sure if it has to do with the bottom dock re-using the same entry for plugin editors as I've not made plugins before, much less a plugin that requires multiple editors open.
