### ISSUE TITLE
Export named flags property with GDScript

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#2988]
The Texture resource has a "Flags" property in which you can select multiple elements in a list. There's no current way to export such a property via GDScript.

![godot-named-flags](https://cloud.githubusercontent.com/assets/5599796/11593971/7caad412-9a8e-11e5-895c-2b0a5f52f92a.png)

I suggest to expand in the current flags property format:

```GDScript
# This is the current format for flags, like the CanvasItem's Light Mask property:
export(int, FLAGS) var current_flags

# Suggested format for named flags:
export(int, FLAGS, "Name 1", "Name 2", "And so on") var named_flags
```

It should be relatively easy to add this, just a careful change in the GDScript parser to accept `PROPERTY_HINT_FLAGS` near the [place where it parses the `PROPERTY_HINT_ALL_FLAGS`](https://github.com/godotengine/godot/blob/064fd762fae75371658e773a3acf39616e813b08/modules/gdscript/gd_parser.cpp#L2380-L2389).

**Comment by eska014** [comment]
> should be relatively easy to add this

:smiley:

> change in the GDScript parser 

:sob:

Can lend from `_ENUM` code to implement this, but before that:
Should any other currently unavailable hints be exposed to GDScript?

from source:

- ~~`PROPERTY_HINT_NONE, ///< no hint provided.`~~
- ~~`PROPERTY_HINT_RANGE, ///< hint_text = "min,max,step,slider; //slider is optional"`~~
- `PROPERTY_HINT_EXP_RANGE, ///< hint_text = "min,max,step", exponential edit`
- ~~`PROPERTY_HINT_ENUM, ///< hint_text= "val1,val2,val3,etc"`~~
- ~~`PROPERTY_HINT_EXP_EASING, /// exponential easing funciton (Math::ease)`~~
- `PROPERTY_HINT_LENGTH, ///< hint_text= "length" (as integer)`
- `PROPERTY_HINT_SPRITE_FRAME,`
- `PROPERTY_HINT_KEY_ACCEL, ///< hint_text= "length" (as integer)`
- **`PROPERTY_HINT_FLAGS, ///< hint_text= "flag1,flag2,etc" (as bit flags)`**
- ~~`PROPERTY_HINT_ALL_FLAGS,`~~
- ~~`PROPERTY_HINT_FILE, ///< a file path must be passed, hint_text (optionally) is a filter "*.png,*.wav,*.doc,"`~~
- ~~`PROPERTY_HINT_DIR, ///< a directort path must be passed`~~
- `PROPERTY_HINT_GLOBAL_FILE, ///< a file path must be passed, hint_text (optionally) is a filter "*.png,*.wav,*.doc,"`
- `PROPERTY_HINT_GLOBAL_DIR, ///< a directort path must be passed`
- ~~`PROPERTY_HINT_RESOURCE_TYPE, ///< a resource object type`~~
- ~~`PROPERTY_HINT_MULTILINE_TEXT, ///< used for string properties that can contain multiple lines`~~
- ~~`PROPERTY_HINT_COLOR_NO_ALPHA, ///< used for ignoring alpha component when editing a color`~~
- `PROPERTY_HINT_IMAGE_COMPRESS_LOSSY,`
- `PROPERTY_HINT_IMAGE_COMPRESS_LOSSLESS,`

###### My opinions

- I don't think there's any difference implemented between `PROPERTY_HINT_RANGE` and `PROPERTY_HINT_EXP_RANGE`.
- `PROPERTY_HINT_SPRITE_FRAME` is kinda specific (used for frame selection in Sprite type nodes), but it's basically a `_RANGE` that automatically increments the value when inserting it as a key in animation player. Might be useful...?
- No idea about `PROPERTY_HINT_LENGTH` & `PROPERTY_HINT_KEY_ACCEL`.
- Adding `PROPERTY_HINT_FLAGS` makes sense, although I'm kinda worried about people getting confused about bitwise operations. But we already added `_ALL_FLAGS` anyway.
- Don't think `PROPERTY_HINT_GLOBAL_FILE`/`_DIR` is a good idea. Beginners will see these and miss the fact that the files won't be available on other machines.
- Instead of `PROPERTY_HINT_IMAGE_COMPRESS_LOSSY` & `PROPERTY_HINT_IMAGE_COMPRESS_LOSSLESS`, users can just use `PROPERTY_HINT_FILE`. I don't think these are suited for anything other than Texture objects.

**Comment by vnen** [comment]
Well, most of it does not makes sense as property hints for GDScript.

* None of these seems to be implemented in the property editor: `PROPERTY_HINT_LENGTH`, `PROPERTY_HINT_KEY_ACCEL`, `PROPERTY_HINT_IMAGE_COMPRESS_LOSSY`, `PROPERTY_HINT_IMAGE_COMPRESS_LOSSLESS`. Also remember that you can use a resource type as hint (such as `Texture`).
* I can't find anything special about `PROPERTY_HINT_EXP_RANGE`.

Some of those might work:

* `PROPERTY_HINT_SPRITE_FRAME` may be useful in some cases (assuming it's possible to animate exported properties), but I'm not sure how this would work from GDScript. Maybe can be a special case for the `RANGE` hint.
* I also agree that `PROPERTY_HINT_GLOBAL_FILE/_DIR` may not be a good idea. It might be misleading and one should not blindly get a path that might not exist in the player's system. This could be useful in some cases (specially for plugins), but it must be treated very carefully, so I'm not really sure.

About `PROPERTY_HINT_FLAGS`, that's what my initial issue was about, so I think this is useful. It must be properly documented, so people can use it properly, but this should no be an issue.

Want to see input from other collaborators about this.

**Comment by eska014** [comment]
Second thoughts on this:
- Looked into `PROPERTY_HINT_EXP_RANGE`, it sets the range's `exp_unit_value` to true, which changes functionality in `Range::set_unit_value` and `Range::get_unit_value`. So I think it's rational to expose it as well.
- `PROPERTY_HINT_SPRITE_FRAME` sets the range to min=0 max=99999 step=1. Setting a different range configuration might require a little hack.
- For `PROPERTY_HINT_GLOBAL_FILE`/`_DIR`, maybe we can come up with some dangerous sounding export hint like `(DIR, UNSAFE)`. I guess unsafe is a bad pick though, makes it seem related to threading.

**Comment by eska014** [comment]
Adding discussed export hints, some insights:
- `PROPERTY_HINT_EXP_RANGE` does actually have an effect: To see it, click the Particles2D property `config/amount`, then press enter twice. A slider will popup, using an exponential scale.
However, trying to move it using the mouse will show an issue: There is an offset between slider and cursor. I'm fixing this as well.
- I'm implementing `PROPERTY_HINT_GLOBAL_FILE`/`_DIR` while restricting them to `tool` scripts. I don't think there's any use for these in any other situation (but feel free to suggest otherwise), so this seems like the cleanest solution to me.
- Will implement `PROPERTY_HINT_FLAGS` as suggested.
- For `PROPERTY_HINT_SPRITE_FRAME`, I don't think such a tiny difference is worth the effort. Maybe if someone specifically requests it...

**Comment by vnen** [comment]
@eska014 :+1: Thanks a lot!

**Comment by reduz** [comment]
yes, it makes sense to expose

**Comment by reduz** [comment]
awaiting a pr then?

**Comment by eska014** [comment]
Yes, already on my fork, will PR soon
