### ISSUE TITLE
Script and visibility icon doesn't highlight properly in scene tree

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#29919]
**Godot version:**
3.2.dev.custom_build. c6507933a

**Issue description:**
With clean Godot config, script highlight in scene tree are 1/2 pixels smaller than node name
![Zrzut ekranu z 2019-06-20 11-18-37](https://user-images.githubusercontent.com/41945903/59837686-f1341d00-934d-11e9-95bb-26ff4548e7f6.png)
 
When I set editor scale to 75%, and main font size to 23 then this looks worse
![Zrzut ekranu z 2019-06-20 11-17-23](https://user-images.githubusercontent.com/41945903/59837797-250f4280-934e-11e9-853d-c104b0d1c6c0.png)

**Comment by Anutrix** [comment]
It seems that highlighted rect uses exact same size as that of the icon.
So when scale of icon goes down, the highlighted rect also goes down.
You can test it by increasing both width and height to 18 in https://github.com/godotengine/godot/blob/10cf5ac0ff5d524c4ef8268f893485a5f53132ac/editor/icons/icon_script.svg#L1 
Then it fits perfectly with the clean Godot config.
Change it to higher value(I tried 32,32) and then it even fits when you set editor scale to 75%, and main font size to 23.
So the issue is probably in `TreeItem::Cell::Button` or `TreeItem::Cell` of tree.cpp. Not sure.

**Comment by Anutrix** [comment]
Found a way hacky way to do something.
https://github.com/godotengine/godot/blob/10cf5ac0ff5d524c4ef8268f893485a5f53132ac/scene/gui/tree.cpp#L972-L973 .
This never executes cause s.height=16(iconheight) and height=18(labelheight for font size 14).
Making it always execute by deleting line L972 kinda works.
