### ISSUE TITLE
Link Button Needs Align Text

### ISSUE THREAD

**Issue by pixelinkmedia** [godotengine/godot#29934]
**Godot version:**
3.1.1

**OS/device including version:**
Win7 Home

**Issue description:**
This more of a feature suggestion than a bug.
The linkButton doesn't have a way to center text both horz/vert just like the Label control does.

This is a problem, because when I try to center the text over my logo (see screenshot) the hotspot is mis-aligned.

If I had center text I could use the entire LinkButton as a Hotspot over images,

See the screenshot.
If I were to move the left control point to the edge of the logo, then "www.pixelink.media" would not be centered anymore. Thus, I have to do it like this to keep my text centered.

![linkbutton](https://user-images.githubusercontent.com/51757955/59865880-2d6c7b00-9358-11e9-861d-6c489968fc97.jpg)

**Steps to reproduce:**
Just add a linkButton to canvas, and look in the inspector... no way to align text

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
