### ISSUE TITLE
Image size for texture incorrect on Android

### ISSUE THREAD

**Issue by ratsdiov** [godotengine/godot#2997]
Tested under 2.0 20150930 alpha and 1.1 stable.  On windows 7 the attached program shows the texture image size correctly:

    texture info [ImageTexture:512] [Image] 4
    render size 64 64

Running under Android on a 2013 Moto-X shows the image as 0x0 in size even though the texture does display correctly.  

    texture type [ImageTexture:507] [Image] 0
    render size 0 0

It seems like get_data() on a texture on Android is returning an Image that does not have any actual data in it.  That attached android_image_test.png file is a zip with a project that replicates the problem.

![android_image_test](https://cloud.githubusercontent.com/assets/4614207/11610351/6488d754-9b6e-11e5-828b-e19b1175c4ef.png)

**Comment by reduz** [comment]
yes, Opengl ES will not give you back textures from video ram so you can't
retrieve back the image data.
If you want to load image data from disk use

var img = Image()
img.load(¨res://somefile.png")

**Comment by romulox-x** [comment]
If you just want the width and height, you can use the get_width() and get_height() calls of the Texture class, instead of trying to use the result of get_data().

Is it a lack of glGetTexImage in ES that creates this limitation?  If so, [this](http://stackoverflow.com/questions/11863416/read-texture-bytes-with-glreadpixels) suggests an FBO workaround that lets you use glReadPixels.  It might be worth implementing just so that we get consistent behavior on all platforms.

**Comment by reduz** [comment]
closing this, as it's a technical limitation of GLES2.
@romulox-x The file formats allowed for framebuffers are very limited, and some platforms have limits to the amount of them, this probably is too troublesome/hacky. GLES3 backend should allow to get back this data. Also, it's still possible to use the ImageLoader API
