### ISSUE TITLE
Provide obfuscar support for C#

### ISSUE THREAD

**Issue by Bleuzen** [godotengine/godot#29978]
Hi, I read a little through the issues here on GitHub and it seems a lot of people want to better protect their game resources / mainly code.

Here for example, some words about obfuscation were dropped: https://github.com/godotengine/godot/issues/24716

While obfuscation may be hard to implement for GDScript, it should be easier for now to do it at least for C#.
There is already a good open source C# obfuscator out there:
https://www.obfuscar.com/

So I'm opening this issue as a feature request for Godot Mono:
Add an option to apply Obfuscar on export.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by markhughes** [comment]
For those here in the Google land.. follow on here: 
https://github.com/godotengine/godot-proposals/issues/1407
