### ISSUE TITLE
Get type from number

### ISSUE THREAD

**Issue by Flairieve** [godotengine/godot#29972]
**Godot version:**

Godot v3.1

**OS/device including version:**

Windows 10

I couldn't find a way to get the types from the GlobalScope from using a number so I'm assuming  there isn't a way yet to do that.

Also I can't get any of the enums from the GDScript or Globalscope classes within GDScript?

**Comment by Flairieve** [comment]
Also I tried to get the classes that started with @ in front of them with ClassDB but they appear to not be exposed to GDScript so ClassDB can't get them at all?

**Comment by KoBeWi** [comment]
Enums are dictionaries, so there could be a hacky way to retrieve the name like
```
Types.keys()[types.values().find(17)]
```
However, I don't think there's a way to access the Type enum.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
