### ISSUE TITLE
Add a 2D DirectionalLight 

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#29994]
Sometimes I want a direct-light with light2d simulate. But when the lightoccluder2d mask the light. It also saw like a spot-light.

Here is my light texture:
![](https://user-images.githubusercontent.com/1890538/59967430-2f069080-955c-11e9-85eb-53dfaa6496c7.png)

and be block looks like:
![image](https://user-images.githubusercontent.com/1890538/59967492-1c408b80-955d-11e9-9f12-9ab55ac90b8f.png)

beginning on shader.

**Comment by clayjohn** [comment]
Are you suggesting a directional light node? Similar to the directional light in 3D?

**Comment by zszen** [comment]
@clayjohn you're right

**Comment by mintyleaf** [comment]
Any progress?
May assign milestone?

**Comment by Calinou** [comment]
@mintyleaf As 3.2 is in feature freeze, this will have to wait for 4.0 or later.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
