### ISSUE TITLE
ogg not linked properly in libdrivers2 when building with webp=no (due to max_src being too low)

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3001]
When building the current HEAD, I get:
```
g++ -o bin/godot.x11.opt.tools.64 platform/x11/godot_x11.x11.opt.tools.64.o platform/x11/context_gl_x11.x11.opt.tools.64.o platform/x11/os_x11.x11.opt.tools.64.o platform/x11/key_mapping_x11.x11.opt.tools.64.o -L/usr/lib64 main/libmain.x11.opt.tools.64.a modules/libmodules.x11.opt.tools.64.a bin/tests/libtests.x11.opt.tools.64.a drivers/libdrivers.x11.opt.tools.64.a drivers/libdrivers1.x11.opt.tools.64.a drivers/libdrivers2.x11.opt.tools.64.a drivers/libdrivers3.x11.opt.tools.64.a drivers/libdrivers4.x11.opt.tools.64.a tools/libtool.x11.opt.tools.64.a scene/libscene.x11.opt.tools.64.a servers/libservers.x11.opt.tools.64.a core/libcore.x11.opt.tools.64.a -lX11 -lXinerama -lXcursor -lssl -lcrypto -lfreetype -lpulse-simple -lpulse -lGL -lGLU -lpthread -lasound -lz
/usr/bin/ld: drivers/libdrivers2.x11.opt.tools.64.a(opusfile.x11.opt.tools.64.o): undefined reference to symbol 'ogg_sync_pageout'
/lib64/libogg.so.0: error adding symbols: DSO missing from command line
```

Note that I'm building with ```webp=no``` due to #2995.

Platform: Mageia 5 x86_64, gcc 4.9.2.

**Comment by akien-mga** [comment]
I wasn't having this a few days ago, but then I wasn't compiling with ```webp=no``` either.

**Comment by vnen** [comment]
I'm having this too in Arch Linux.

**Comment by vnen** [comment]
Tried to change the `max_src` value in `drivers\SCsub` from 64 to 128 and now it works. My guess is that this splitting of sources in different archives might be breaking the symbols. With `webp=yes` the splitting would occur at a different place, since WebP sources would come first.

Is this `max_src` really necessary?

**Comment by akien-mga** [comment]
Nice catch, I can confirm that it works fine with ```max_src=128```.

**Comment by akien-mga** [comment]
The whole splitting in several driversX libraries is a bit confusing IMO :-/

**Comment by reduz** [comment]
it's because of the command line length limit on windows. There was a patch to fix this at some point so it may not be needed anymore, but not sure how much it's working

**Comment by punto-** [comment]
The fixes for the command line problem had some issues, sometimes the don't
invoke the process correctly (for example on a certain version of clang for
a certain platform, I can't run "ar" using the replacement spawn, because I
get weird errors). Also sometimes it doesn't record the build progress
correctly when you press ctrl+c to interrupt the build, so when you build
again it starts all over again (it doesn't do the "writing .sconsign file").
I think the ideal fix would be to patch scons to write all the command line
to a file and then run using the gcc flag to use that, when it's on
windows.. That's probably what they do with the VS compiler already.

**Comment by vnen** [comment]
I set `max_src` to a very high number (so it generates a single `libdrivers`) and it stills build fine on Windows 10 with VS2015. I don't if this is still a problem with older versions of Windows or with other building tools.

**Comment by reduz** [comment]
yes i guess this option should be disabled for now
