### ISSUE TITLE
Adding a label to Position3D

### ISSUE THREAD

**Issue by BraindeadBZH** [godotengine/godot#30028]
Hi,

Just a quick though that came to my mind.
I have the feeling that if Position3D nodes, apply to Position2D too, were to display their node name as a label attach to them in the viewport it would make them more useful.

What are your though on that?

**Comment by Calinou** [comment]
This should likely be configurable on a per-node basis using an internal editor-only property, similar to https://github.com/godotengine/godot/pull/28390. Otherwise, it may get a little messy when you have lots of Position nodes on screen :slightly_smiling_face:

**Comment by BraindeadBZH** [comment]
> 
> 
> This should likely be configurable on a per-node basis using an internal editor-only property, similar to #28390. Otherwise, it may get a little messy when you have lots of Position nodes on screen 🙂

Agree

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
