### ISSUE TITLE
Create scene inheritance for existing scenes

### ISSUE THREAD

**Issue by uapaladin** [godotengine/godot#30024]
**Godot version:**

3.1.1

**OS/device including version:**

**Issue description:**

I have a suggestion for a feature concerning scene inheritance. Suppose I have the following scene structure and have been working on the code for some time:

SportsCarScene -> VehicleScene
PoliceCarScene -> VehicleScene

I now find that I need an intermediate scene, called CarScene, to achieve the following structure:

SportsCarScene -> CarScene -> VehicleScene
PoliceCarScene -> CarScene -> VehicleScene

I can construct the CarScene by using Create Inherited Scene from the Scene menu. However, there's no option for switching inheritance. There's an option for Clear Inheritance (right-clicking on the node), which could be used, but it seems not be possible to create an inheritance for an already existing scene. There's only the one for creating a new inherited scene.

_I would have liked to have an extra option, **Inherit From Scene**_ (on the right-click menu), for already existing scenes with no current inheritance. So, in the example above, when selecting the Clear Inheritance option, the inheritance chain will be cleared and a new option, Inherit From, would replace the Clear Inheritance option. After selecting this new option, I would have the possibility to select the new CarScene as the new inherited scene for my SportsCarScene and PoliceCarScene. And after that, with the new inherited scene as part of the node tree, I would need to delete the old inherited scene nodes (which are still there, but no longer inherited).

_It would also be great if there was an option, **Switch To Inherited Scene**_, which combines these two steps into one. Clearing and deleting the old nodes, and inheriting and adding the new nodes.

Currently, there's an option Merge From Scene which might be used. I can clear the inheritance, remove the old nodes, and then merge from the new CarScene. However, the new nodes show up not-grayed out, they are just merged, not inherited. I suppose there is a difference.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
"Merge" is basically copy-paste.

And a hearty +1 from me, I used merge for my cars because I kept reworking things and inheritance would have to be changed all the time. This feature would save me so much trouble ;)

**Comment by Nehluxhes** [comment]
+1 from me too, changing inheritance is a basic common feature.
Right now you have to manually edit the files like explained [here](https://godotengine.org/qa/10745/how-to-change-the-inheritence-of-an-existing-scene), which seems weird to me

**Comment by MrBSmith** [comment]
I want this hard.
Making scenes standalone, and then figure it would be a good thing to have a parent scene afterward is a pretty commun thing in my workflow...

**Comment by Calinou** [comment]
@MrBSmith Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
