### ISSUE TITLE
 import assets: multithread & command line

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#30055]
**Godot version:**
3.1

**OS/device including version:**
linux

**Issue description:**
It would be nice to have the asset importer multi-threaded, and also a command line version that doesn't need to have the editor open. This would help with speed and scripting/automating some processes.

**Comment by Calinou** [comment]
> and also a command line version that doesn't need to have the editor open.

If you have an headless editor binary, you should be able to run it with `--editor --quit` in the project directory. `--quit` will quit after one iteration, which means it will quit as soon as all assets have been imported.

**Comment by asheraryam** [comment]
The suggested workaround does not seem to work on the headless version (idk if it worked before).
I tested the headless version and it quits before the importing begins.

**Comment by Calinou** [comment]
@asheraryam I guess you could export the project for any platform from the command line and not care about the generated output in this case.

**Comment by asheraryam** [comment]
@Calinou thanks that's what I'm doing now, I wanted to use this for CI to better cache between platform builds, but I went ahead and put all the export commands in the same stage instead

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
