### ISSUE TITLE
Missing a mouse/cursor node

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#3006]
I don't now if this was suggested before but I'm missing a mouse/cursor node.

Idea behind:
- camera follow mouse
- change mouse cursor
- mouse can be animated with animationplayer
- hide and show mouse (in game movie)
- catch mouse (tutorial)
and more

I know you can do this with GDScript but I'm a visually programmer! :-)

**Comment by reduz** [comment]
well you can make a cursor follow the mouse pretty easily with a few lines of code, and make it work in any way you want so I would rather make a specific way as a node

**Comment by puppetmaster-** [comment]
I have done someting like that

```pyton
extends Sprite

export(int,"MOUSE_MODE_VISIBLE","MOUSE_MODE_HIDDEN","MOUSE_MODE_CAPTURED") var mouse_mode
export(bool) var invert_y
export(bool) var invert_x
export(float) var sensitive_y
export(float) var sensitive_x
export(Texture) var normal
export(Texture) var waiting

func _ready():
	self.set_pos(Vector2(get_viewport_rect().size.width/2,get_viewport_rect().size.height/2))
	set_mode(mouse_mode)
	set_texture(normal)
	set_process_input(true)

func _input(ev):
	if (ev.type==InputEvent.MOUSE_BUTTON and ev.button_index==BUTTON_LEFT and ev.pressed):
		set_scale(Vector2(0.8,0.8))
	elif (ev.type==InputEvent.MOUSE_BUTTON and ev.button_index==BUTTON_LEFT and !ev.pressed):
		set_scale(Vector2(1,1))
	elif (ev.type==InputEvent.MOUSE_MOTION):
		var fake_x = ev.pos.x * sensitive_x
		var fake_y = ev.pos.y * sensitive_y
		if(invert_y):
			fake_y = get_viewport_rect().size.height - ev.pos.y * sensitive_y
		if(invert_x):
			fake_x = get_viewport_rect().size.width - ev.pos.x * sensitive_x
		set_pos(Vector2(fake_x,fake_y))
	if (ev.is_action_released("ui_cancel")):
		set_mode(1)

func set_mode(in_mouse_mode):
	Input.set_mouse_mode(in_mouse_mode)

func set_waiting():
	set_texture(waiting)

func set_normal():
	set_texture(normal)
```

but I have problem with changing color of cursor depending what color is behind.
Perhaps I should start a forum post about that.

I've thought it would be more consistent if such a node would exist.

**Comment by vnen** [comment]
> but I have problem with changing color of cursor depending what color is behind.

Not sure why you would want to do that, because mouse cursors don't normally change colors based on the background. So, even if such node existed, you'd face the exact same problem.

You have the possibility of making a cursor node via C++ module though you likely can do the same behavior with just GDScript in a standard node.

I don't think there's any need for a cursor node and its utility is not very clear. An API to deal with the OS cursor is preferable (if doesn't currently exist) and in the platforms without mouse it wouldn't be needed anyway.

Let's talk about what's currently possible:

> * camera follow mouse
> * catch mouse (tutorial)
> * hide and show mouse

The Window Management demo is a good start to see how to do these.

> * change mouse cursor

You can do that via Project Settings with `display/custom_mouse_cursor` property, though it's not hardware accelerated AFAIK.

You can't use the Animation Player to make a cursor and that's a good request, but would a cursor node be needed for that? One possibility would be to use a custom scene as cursor (since node and scene are pretty much the same thing).

**Comment by puppetmaster-** [comment]
For our [LudumDare 34 game](http://ludumdare.com/compo/ludum-dare-34/?action=preview&uid=39425)  we have created a scene for the mouse and added it to the game gui scene (canvasLayer)
We can't go with the Project Settings "custom_mouse_cursor" because we have had the same [issue] (https://github.com/godotengine/godot/issues/3082) and don't get around it.

I closing this issues. Everything can easily be obtained inside the editor. Thanks!
