### ISSUE TITLE
Is impossible make render settings in the game

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#30087]
I want to make render settings in the game:

![01](https://user-images.githubusercontent.com/11189223/60183503-1da8d700-982f-11e9-960d-96bd949907c2.png)

It's very important! This allows the end user to adapt the performance of the game to their PC. I ran into problems. Gathering information, I realized - it is impossible.

I can change all these settings in "ProjectSettings". For example:

`ProjectSettings.set_setting("rendering/quality/shadow_atlas/size",1024)`

However, this does not always work. It does not always affect the render. I can get to some render settings in a different way. For example:

`get_viewport().shadow_atlas_size=1024`

However, not all render settings are available this way (It seems this is the only thing that may change).

It turns out it is impossible to change the settings "on hot".

I would like to be able to change the following settings in a running game:

![0000](https://user-images.githubusercontent.com/11189223/60184218-539a8b00-9830-11e9-9d09-4d0a9328e5e3.png)

P.S: https://github.com/godotengine/godot/issues/18621 - found a similar message, but it concerns one parameter.

**Comment by Calinou** [comment]
You can modify those parameters when the project starts by defining a path to a *project settings override* file in the **Project Settings. This file's path must point to an user-writable location such as `user://settings.ini`, and the file must follow the same format as `project.godot`. However, unlike `project.godot`, it should only contain the keys you want to override override. You can use the [ConfigFile](https://docs.godotengine.org/en/latest/classes/class_configfile.html) class to write such a file :slightly_smiling_face:

**Comment by DimitriyPS** [comment]
At least that's something... but it sounds like a manul for the production of a stone axe and how to make a fire in a cave.

Is there any way to apply the settings without rebooting? Do exist today to this what technical difficulties?

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
