### ISSUE TITLE
Color picker panel need add a reset button.

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30081]
mac 10.14.4 godot 3.1.1

![](https://user-images.githubusercontent.com/1890538/60161989-2c8d8a80-982b-11e9-895f-f31699eae9f1.png)

sometimes if I don't want change the color. I will want to change back. If is simple white or black it is easy. But it can't be changed back when some special color.~~

**Comment by girng** [comment]
close panel, and do ctrl+z

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
