### ISSUE TITLE
Improvements to the tilemap node

### ISSUE THREAD

**Issue by zszen** [godotengine/godot#30082]
mac 10.14.4 godot 3.1.1

1. tile texture can't be drag to  tilesets editor strightly. Click "+" then need go to deep folder to get the texture.
![Snip20190626_5](https://user-images.githubusercontent.com/1890538/60162225-a887d280-982b-11e9-958f-0bf422d78cfc.png)

2. tilemap node can't be move in ui design interface. It always do the draw operate. 
![](https://user-images.githubusercontent.com/1890538/60162291-d40abd00-982b-11e9-8c4e-4c1cff3c36ca.png)

3. tilemaps tilesets can't be batch delete. Wether in property panel or in tilesets editor.
![](https://user-images.githubusercontent.com/1890538/60162408-087e7900-982c-11e9-8242-9d534e11d734.png)

4. the tilesets editor should be scale with multi touch. (the shader script, ui editor, gd script all support scale)
![](https://user-images.githubusercontent.com/1890538/60162494-3bc10800-982c-11e9-984f-22143c93c1ae.png)

**Comment by Zylann** [comment]
About 4), it is similar to https://github.com/godotengine/godot/issues/17499 and https://github.com/godotengine/godot/issues/19860

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
