### ISSUE TITLE
Why the is_point_in_polygon is not bind to GDScript?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#30091]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

Since this method is called in the native source code, its implementation is efficient enough,  why it's not available in GDScript?

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Zireael07** [comment]
Good idea, I can immediately think of a couple uses in my own game (mostly when creating maps)

**Comment by Xrayez** [comment]
Perhaps because it might be buggy?

This:
https://github.com/godotengine/godot/blob/master/core/math/geometry.cpp#L39-L50

replaced by:
https://github.com/godotengine/godot/blob/master/core/math/geometry.h#L906-L934

Also Clipper's implementation could be quite fast and robust compared to what the engine provides:
https://github.com/godotengine/godot/blob/master/thirdparty/misc/clipper.cpp#L470-L513

It can also detect whether the point is outside, inside, or exactly on polygon boundary.
