### ISSUE TITLE
Switch back to 'Select mode' after the node is deselected

### ISSUE THREAD

**Issue by siradam7th** [godotengine/godot#30128]
**Godot version:**
3.1.1

**Issue description:**
Selecting a node then changing to 'Move mode', 'Rotate mode' or 'Scale mode' causes it to active that mode globally, so if you select another node, the same mode is active instead of the default 'Select mode'.

**Suggestion:**
Make it so when you deselect a node or select another one, it goes back to the default mode which is 'Select mode'.

**Reason:**
Keeping the same mode active even when you select another node or deselect it can cause you to accidentally do unwanted operations on another node.

**Steps to reproduce:**
- Create a node and select it.
- Change to 'move, rotate or scale mode' using the editor tab on the top or the shortcuts.
- Select another node in the 'Scene' window, and it's still in the same mode.

**Comment by siradam7th** [comment]
it would also be better if pressing the same shortcut for 'move, rotate or scale mode' causes it to go back to 'Select mode' instead of having to press yet another shortcut for select mode, currently pressing twice doesn't do anything.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
