### ISSUE TITLE
Applying shapekeys and generate meshintance. Feature request.

### ISSUE THREAD

**Issue by Lexpartizan** [godotengine/godot#30141]
I trying make in-game character generator for godot. Like Skyrim or Fallout 3-4.
https://github.com/Lexpartizan/Go_MakeHuman_dot/

I make blend-file with one model with 200+ shapekeys. Importing to Godot.
I need setup blendshapes value and customize the appearance of the character. 
I can this and on my github page have godot project with this example.

Then applying all shapes and generate MeshInstance without blend_shapes, because file with blendshapes for each character takes up a lot of memory space. 

Mesh after import to Godot with all shapekeys- 100 Mb.
But, you need make resource local for different characters. 
1 character on screen - 100 Mb video-memory.
10 character on screen - 1Gb video-memory. 
Without blendshapes - 1 character only 2,5 Mb. Zombie rush possible!

And i dont know how make that. I don't even know if this is possible. So, this feature request.
I can make this in blender, but for in-game character generator this must be maked via code.
I asked this question on forums, discord, Q&A, etc and did not get an answer.
Now I have the nerve to ask a question already on a github. Sorry for that. And sorry for my english. I hope you could understand the problems from this vague description.

**Comment by Lexpartizan** [comment]
Thats no import feature.
This about work with blendshapes via code in engine.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
