### ISSUE TITLE
Missing Joypad Button Index label.

### ISSUE THREAD

**Issue by joleeee** [godotengine/godot#30163]
**Godot version:** 3.1.1.stable.official

**OS/device including version:** Linux Mint 19.1 Cinnamon

**Issue description:**

When configuring input maps the buttons 10 and 11 are only named for Nintendo controllers, while DS4 controllers also use the same index's.
The SHARE(left) button is the equivalent of button_index 10
The OPTIONS(right) button is the equivalent of button_index 11

**Steps to reproduce:**
NA

**Minimal reproduction project:**
NA

![missing-10-11-ds4](https://user-images.githubusercontent.com/24441708/60358925-da3d9c80-99d7-11e9-8dd5-2c94c26c0341.png)

**Comment by daniel-luper** [comment]
There are several different names for the two central buttons on game controllers: "Share/Options" for the ps4, "View/Menu" for the Xbox One, and "Back/Start" for the Xbox 360, etc. Although it seems that the name "Select/Start" is generally understood since it dates way back (NES controller, maybe even before that). 
Now I think it would be nice if there were the specific names for each type of controller but I don't know which ones should be included... Just the Xbox One and PS4? Or also the PS3 and Xbox 360?

**Comment by joleeee** [comment]
There are already names for most of them so it feels like the start /
select are missing.

**Comment by daniel-luper** [comment]
![image](https://user-images.githubusercontent.com/50499124/60427341-69240200-9bee-11e9-9bc4-183441d449ca.png)

Start and select are already there

**Comment by joleeee** [comment]
Sorry. I mean it feels like Options / Share is missing.

**Comment by daniel-luper** [comment]
![share-options](https://user-images.githubusercontent.com/50499124/60450540-fd5b8c80-9c21-11e9-8dc8-646531f96fad.png)

OK how about this? Legit just two strings to modify xD

**Comment by joleeee** [comment]
Yes, something like that! Tried searching for them but couldn't find them.

man. 1. jul. 2019 kl. 18:04 skrev daniel-luper <notifications@github.com>:
