### ISSUE TITLE
Automatic columns in GridContainer

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#30173]
**Godot version:**
3.1.1

**Issue description:**
I once used GridContainer and wanted to support resizing the window. When the window would get resized, I wanted my container to fit the number of columns to the full size, since each column had the same width. Right now, it is only possible via script and cumbersome to do. It would be useful if GridContainers had an option to support this behavior automatically.

Happy 5000th simultaneously opened issue btw.

**Comment by Xrayez** [comment]
I highly support this, I needed to do the exact same thing for aligning a bunch of editor icon previews in my plugin, look [here for my ugly solution](https://github.com/Xrayez/godot-editor-icons-previewer/blob/v1.1/addons/editor_icon_previewer/editor_icon_window.gd#L115-L118).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by idbrii** [comment]
This was implemented in https://github.com/godotengine/godot/pull/56104 as the H and V [FlowContainers](https://docs.godotengine.org/en/stable/classes/class_flowcontainer.html)
