### ISSUE TITLE
Labelled Sliders

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#30172]
**Godot version:**
3.1.1

**Issue description:**
Right now Sliders don't support displaying their value and you need to implement it yourself (unless I'm missing something). Would be nice if they had an option to display a label with current value with some customization, namely whether it should be above or below and whether it should always show, only when dragging the slider or not at all.

A small mockup:
![image](https://user-images.githubusercontent.com/2223172/60375162-2ef90b80-9a08-11e9-89fc-5af481cd10ba.png)

**Comment by girng** [comment]
have a feeling this could be done with a label as a child, and its position gets updated based on the value of the slider. i don't know if it needs to be done in c++ (added to core, or could be done in gds)

**Comment by Zireael07** [comment]
It can be done with a label, but it's such an ubiquitous feature that it's kinda weird not to have it out of the box.

**Comment by Zylann** [comment]
Looking at your mockup, is that label to be shown only when sliding?

**Comment by volzhs** [comment]
it might need many properties if engine has this feature.
font, h/valign, offset, show all time or only when dragging, how many number shown after dot for floating number, how to show lager number like 100K, using comma for every 1000 or etc...

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
