### ISSUE TITLE
Several Instances With The Same Name, first instance is named correct, following will be renamed

### ISSUE THREAD

**Issue by Paradisebird** [godotengine/godot#3017]
I am creating several instances of the same scene with gdScript, so I will get several copies of one scene, all with the same name, scale etc.. 

But the name is changed. It looks like:

print(levelFragments)
[levelFrag1, @spatial1, @spatial3, @spatial4, ...]

How it should have looked:

print(levelFragments)
[levelFrag1, levelFrag2, levelFrag3, levelFrag4, ...]

When adding nodes to the scene tree, Godot automatically adds and increases a number  at the end. But when adding instances from script, they lose their name.

**Comment by reduz** [comment]
Yes, this behavior is intended. The reason is that going through all nodes
to see if the node exist for every possible number is extremely slow, so in
case the node exists, Godot simply assigns a unique name and adds it.

In the editor the behaviour is there for better usability in building the
scene, but in runtime this is too slow.

**Comment by ScyDev** [comment]
I can confirm this problem. It can be very confusing that a node.get_name() suddenly returns a completely different name than the one it was given.

How about just adding the object ID to the end of the nodes name, when instanced at runtime?
Instead or renaming it to Spatial?

**Comment by reduz** [comment]
This is not possible, the idea is to make sure at all costs that the
assigned ID is unique and as fast as possible, which is why the
@+type+objectid unique name is created.

However if performance is not your priority, maybe adding a new function or
option to add_child() so it behaves like in the editor may be desired?
something like

add_child(node,standard_naming=false)

or maybe a different add_child funciton or something that has a name tha
makes sense

**Comment by ScyDev** [comment]
Why is @+type+objectid faster than @+name+objectid?
And how is the first one more unique than the later?

And yes, as an alternative such an option to add_child() would also be nice.

**Comment by reduz** [comment]
ok, will change the function to:

void add_child(Node *p_child,bool p_legible_unique_name=false);

**Comment by akien-mga** [comment]
I'm curious about ScyDev's question though. It would be a simpler compromise than having an optional argument IMO:

> Why is @+type+objectid faster than @+name+objectid?
And how is the first one more unique than the later?

The only issue I can see with @+name+objectid would be if the name of one node corresponds to that of another "node+objectid" (e.g. you have nodes named *mynode* and *mynode2*, and then when instancing *mynode* you might get *@mynode23* if objectid is 23, while you might also get *@mynode23* when instancing *mynode2* if objectid is 3).

A way to prevent this issue would be to use specific symbols in the name and ensure they are not allowed when naming nodes manually, e.g. "@" and ":", so *mynode* might become *@mynode:23* while *mynode2* would be *@mynode2:3*.

**Comment by reduz** [comment]
It makes sense, I will change that right now. Can't use a ":" in a node
name because nodepaths use ":" to split between path and property, but can
use . instead I guess:

@MyNode.5

**Comment by ScyDev** [comment]
Nice! :)

**Comment by akien-mga** [comment]
> It makes sense, I will change that right now. Can't use a ":" in a node
name because nodepaths use ":" to split between path and property, but can
use . instead I guess

That should work, at least in the node renaming function the "." has recently been prohibited to avoid node names like ".." or "../whatever", so it should be free to use internally.

**Comment by akien-mga** [comment]
Right, you used @MyNode@5 in the end, which is just as fine I guess :)

**Comment by reduz** [comment]
yes i was in doubt about . so just went the easy way
