### ISSUE TITLE
Parameterized types / generics for GDScript

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#30180]
This seems like an obvious suggestion for static types but I couldn't find any related issues.

Parameterized types / generics (and many but not all uses of templates in C++) would be useful to have static-type-wise.

I think you could get most of the value by just parameterizing the built-in types where it makes sense:
* Element type for `Array` - maybe not as much value as the others since we do have some typed array types (`Pool*Array`), but would allow static typing when the contents are not built-in types
* Key and value types for `Dict`
* When method values are added, their static type could be parameterized with return and input types

And then methods on those classes would use the parameter in their types. For example `Array.append` would have an argument type matching the argument given as `Array`'s elment type. Built-in functions like `clamp` (#30142) could be parameterized on the numeric type given as input/output.

I can't come up with many current use-cases for user-defined generic classes or functions (implementing an object pool comes to mind), but maybe with increasing GDScript performance, people will want to write generic libraries like in other languages.

**Comment by hunterkjones** [comment]
I don't really see the appeal. GDScript's star property is simplicity, and those who want a little safer code can use type hints or another language.

This would also be hard to implement. The elements of many Godot collections aren't even typed at the C++ level, so there would have to be some ugly workarounds to accommodate.

**Comment by raymoo** [comment]
This would be part of the type hints, like in Python.

**Comment by hunterkjones** [comment]
Python's generics aren't part of its type hint system. In Python, a `List[int]` is the same as `List.__getitem__(int)`, which is really a constructor for a new type that wraps Python's built-in `list`. This is only possible because Python's types are first class - GDScript's aren't. To implement generics, GDScript would either need its own first-class type system that wraps the engine types, or type arguments would have to be supported directly by the relevant engine types. Neither option really seems worth it.

**Comment by raymoo** [comment]
I'm not sure what you mean when you say that they aren't part of its type hint system, since it looks like to me that primitive types and user-defined types can be used in the same way as type hints. I do see after your explanation though that it wouldn't be easy to add just because Python does it, since Python's type hints are already based on first-class types.

Since it was already some effort to implement the existing static type hinting in GDScript, I guess the question is why parameterizing the built-in types is significantly less valuable to the point that it's not worth implementing. As far as I can tell, this is a matter of how often the type checks would be invoked, since that affects how much additional type checking coverage you would get. I think the cases I listed in the OP would be the main ones: arrays of values of non-core types, dictionaries in general (since there's no specialized dictionaries like for arrays), and possibly connecting methods to signals, if signals are changed to accept first-class method values. There's also built-in mathematical functions like `clamp` whose output type depends on the input type.

It's possible that non-core arrays, dictionaries, and signal connections are used infrequently enough that parameterizing the built-in types won't give much of a benefit compared to the effort required. I haven't worked on the engine and my current project in Godot isn't even using GDScript (I am doing everything in C++ plugins), so I don't really have any authority to say whether it would be worth it.

Aside from built-in types, generics for user-defined classes/methods are needed for static typing in user-written libraries meant to be generic. My C++ plugin makes significant use of templates to write generic code (that I actually do end up using with multiple argument types). However, maybe it's intended that we switch our code from GDScript to a language with richer static types when our code becomes complex enough to benefit from static generic typing. If that's the case then I guess GDScript doesn't really have a need for user-defined generics either.

**Comment by hunterkjones** [comment]
> As far as I can tell, this is a matter of how often the type checks would be invoked, since that affects how much additional type checking coverage you would get.

GDScript's type hint checks are resolved statically. If you wanted to verify at all times that a `Dictionary<String, int>` only contained String-int pairs, there would be no way to do that because any code outside the script could change its contents without GDScript knowing. The only other way to accomplish this would be to add type parameters to collection classes across the engine, which would be a massive undertaking for very little ROI.

**Comment by raymoo** [comment]
I didn't realize that cost, but I also don't know why you quoted that line, since that line is describing the value and not the cost.

**Comment by hunterkjones** [comment]
Ah, sorry, I thought you were referencing when GDScript runs type checks.

**Comment by raymoo** [comment]
If this thread looks confusing to you, there was another user arguing against this feature and I guess they deleted all their posts.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by beyarkay** [comment]
For future travellers, it seems like [this](https://github.com/godotengine/godot-proposals/issues/1207) is the most relevant GIP for this issue. Although [searching for 'generics' in the GIP repo](https://github.com/godotengine/godot-proposals/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+generics) yields 12 open and 7 closed results, so there might be a few of them there.
