### ISSUE TITLE
NavMesh Generation - missing merging of simple geometry

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#30190]
Issue description:
I am looking for a way to make a NavMesh out of multiple Meshes (that are in multiple model files - dae) via Editor.
When i make the suffix "-navmesh" behind my model file, it is generating in Godot a NavigationMeshInstance out of it. Thats nice. It looks like it should (Geometry exactly like i created in Blender).

But how can i merge multiple Meshes. I know there is a bake function. But the bake functions are combining the meshes in a different way that i want. I want that the NavMesh looks like exactly the way i made it in Blender.

So how to merge multiple seperated model files (dae files for example) - that reperesenting the navMeshes - to a big NavigationMesh without a baking that transforms the result into something different?

I hope i explained it somehow. 

Another thing. But not so important right now. Why i cant group (Grouping is possible in the Editor) the NavMesh model Files in my scene, and than use the NavMesh Baking on it? So i dont have to put the NavMesh model file nodes under the NavigationMeshInstance directly. Would help when you arrange the buildings and you have not always to repositition the NavMesh Geometry all the time. I could add the NavMesh Geometry as child on the Building directly.

**Comment by TypeOverride** [comment]
Ive implemented both myself into in.

https://github.com/TypeOverride/godot/commit/ca7278f3f8ac99869c1d6593dcb63c798e20e1aa

if some dev wants to implemented it as well someday, he can look into my code if he want.

The second implementation (the grouping) -> thx to @dertom95

**Comment by Zireael07** [comment]
PR your changes?

**Comment by TypeOverride** [comment]
> PR your changes?

no sry. i won't. Its not much changed. And Clang is not given for sure.  sample_partition_typ i called Stationary.. not a good name and maybe not a good place where i placed the mode changing. Don't know. And i comment one thing out. Dont know what the try to do there. I needed global_transform instead local like they did.

The devs can make it better than me. For my needs its good right now.

**Comment by dertom95** [comment]
> The second implementation (the grouping) -> thx to @dertom95 (for the grouping thing look into his implementation maybe - i think he is further working on it)

@TypeOverride  I'm not working on the navmesh-code (and godot) anymore so feel free to promote your work with mine as one PR (if you are getting there someday ;) ). No need for any mentioning. Cheers, Tom

**Comment by asheraryam** [comment]
I'm interested in working on this, as I need merging nav meshes.

@dertom95 I can't find your PR anywhere, I want to try it merge it with with from @TypeOverride after I manage to rebase it on latest master.

**Comment by Zireael07** [comment]
@asheraryam: There were two "navmesh by group" PRs, one of them was merged, the other was closed. So just work on the code in latest master.

**Comment by asheraryam** [comment]
@Zireal07 Thank you. 

I also realised that this issue is different from what I'm facing, what I want is to fix the current usage of multiple **separate** navmeshes so they can be enabled/disabled at runtime independantly (e.g. closing off a room or a pathway).

Currently two navmeshes will be considered connected (at real-time) if they have overlapping vertices, which works in simple cases e.g. two squares of equal sizes side by side. This works as expected when enabling/disabling.

But that would not work in the case of pathways or rooms since they are usually small strips connected to much larger masses. e.g. A small rectangle attached to a bigger square.

The navmeshes need to considered connected if they share edges instead of just vertices.

Not sure if I should open a separate issue for this and see if the change would be welcome.

**Comment by Zireael07** [comment]
I recommend opening a separate issue for determining navmesh connection - possibly on https://github.com/godotengine/godot-proposals

**Comment by asheraryam** [comment]
@Zireael07 Thanks I did that, I hope I get some feedback about how it can be implemented.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by TypeOverride** [comment]
So i went back to my old project and try to make all with Godot 4 and i see, that there is not such an implementation in Godot 4.

So i cant back static meshes like before. Thats a big problem because i dont want always have generated nav meshes. I want maybe a navmesh i created fully in blender. And than use this one without any algorithm on it that changes the nav mesh.

My code made this. Furthermore it made that it combines static nav meshes. Game developers are using sometimes navmeshes they fully build in a 3D program. And they dont want a generated one.

**Comment by Zireael07** [comment]
@TypeOverride why do you need merging navmeshes? Navmesh links should prevent the biggest problem with multiple navmeshes that existed before, i.e. not being able to move from one to the other
