### ISSUE TITLE
Add ability to remove all assets except selected scenes with their dependencies 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#30210]
**Issue description:**
Now, when I found a bug in some scenes in big project, I must manually remove all other scenes and resources.

It would be good if would exists an option to leave only selected scene/scenes with their dependencies

**Comment by KoBeWi** [comment]
What if you select all and only deselect what you want to leave?

**Comment by akien-mga** [comment]
I think the proposal is to have a way to preserve only a given scene and its dependencies, without having to sort through those dependencies manually.

More interesting that a "remove all but scene" option, I think it would be useful to have the option to copy one or more scenes and their dependencies to a new project folder.

**Comment by fire** [comment]
Remember this doesn't solve if a resource is referenced in a gd script.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
