### ISSUE TITLE
CSGPolygon following a path throws errors if adding or removing points in path

### ISSUE THREAD

**Issue by Plopsiskopsis** [godotengine/godot#30229]
Godot 3.1 

If you make a CSGPolygon follow Path and add points to the path after _ready() function it keeps throwing the following errors. 
Signal 'tree_exited' is already connected to given method '_path_exited' in that object.
  <C Source>     core/object.cpp:1488 @ connect()
and
Signal 'curve_changed' is already connected to given method '_path_changed' in that object.
  <C Source>     core/object.cpp:1488 @ connect()

Is there any reason for the signal to reconnect on path update?

To reproduce you can create the following scene:
![image](https://user-images.githubusercontent.com/35765659/60460837-79b79500-9c4d-11e9-9780-a7a8576de052.png)

**Comment by tiax615** [comment]
I had the same problem.
No matter whether you use scripte or not. As long as you use follow path, those errors show.

**Comment by kb173** [comment]
Is there any possible workaround for this? Our logs are full of these errors.

It seems to me that `set_point_position()` causes this as well.

**Comment by ngreve** [comment]
Just want to push this issue a bit more.

I just encountered this bug, too. Right now, for me this is especially problematic, because I try to use `Path` with `CSGPolygon` to implement something similar to a rope, to connect two objects.

So, for developing reasons my `Path` is running in `tool` mode, and `curve.set_point_position(...)` is called in every physics frame.
Unfortunately the resulting amount of error message printing slows down Godot immensely.

**Comment by ngreve** [comment]
I still encounter this issue. Could it be that this fix only works for `add_point()` but not for `set_point_position()`?
