### ISSUE TITLE
Muscle Contraction and Expansion

### ISSUE THREAD

**Issue by arthur109** [godotengine/godot#30237]
**Godot version:**
3.1

**OS/device including version:**
Manjaro Gnome

**Feature Request description:**
I would like to simulate muscle contractions and expansions, as you can see in this video 
https://youtu.be/GOFws_hhZs8?t=43
I am using a groove joint, to separate the two "anchor" (circle things) and would like to be able to change their offset so simulate a contraction. I am unable to do this because the "initial_offset" can only be set at the start of the program and changing it while the program is running has no effect. This is what I have right now.
![Peek 2019-07-01 17-07](https://user-images.githubusercontent.com/8083567/60474135-1ade2580-9c25-11e9-9ec1-7b6de88e209b.gif)

**Minimal reproduction project:**
[Ai-1.zip](https://github.com/godotengine/godot/files/3347754/Ai-1.zip)

**Comment by raymoo** [comment]
Have you tried using the `length` property?

**Comment by raymoo** [comment]
Instead of using the offset to push / pull, you could allow for sliding then apply a contracting / dilating force.

**Comment by arthur109** [comment]
Yeah I thought about that, but then, if you pulled one node then the other would not get pulled with it because sliding is allowed

**Comment by raymoo** [comment]
The other node would get pulled by the contracting force after they get separated beyond the current target distance.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
