### ISSUE TITLE
HTTPClient/HTTPRequest Port

### ISSUE THREAD

**Issue by ventr1x** [godotengine/godot#30245]
Godot version: 3.1.1

As I haven't found any other issue on the matter:
I'm trying to get a very simple request with a custom port going. It is working on port 80 without any problems.
Trying to request anything other than 80 (for http) results in .. nothing. No error, no request being sent.

I for example am using a nodejs server which listens to port 8000. I am unable to request anything through this port (not even connect_to_host works; in fact it hangs to game completely).

Is that a known issue or limitation?
Is there any workaround besides reverse proxy a domain to every server I own just for godot?

**Comment by ventr1x** [comment]
That issue seems to be related to localhost, never had that issue before with any other http implementation though.

Works
> http.connect_to_host("http://127.0.0.1", 8000)
> http.connect_to_host("http://localserver.local", 8000)
> http.connect_to_host("http://domain.com", 8000)

Does not work:
> http.connect_to_host("http://localhost", 8000)

**Comment by Faless** [comment]
@ventrix1 what OS? Are you on windows?

Was Node.js was only listening to 127.0.0.1 (not any address, not an ipv6 address)?

`localhost` gets resolved to `::1` on some systems (windows but not only windows). So the client would try to connect to an IPv6 to which no-one was listening.

**Comment by ventr1x** [comment]
I'm resolving localhost to 127.0.0.1 on windows 10 ("::1 localhost" in hosts is removed).

What nodejs is listening to would be imho irrelevant, as irrelevant as it being even started or not. I'd expect at least an unresolved error, not the game hanging and letting me poll indefinitely.
But I tested it with localhost, 127.0.0.1, 0.0.0.0

Keep in mind that localhost:80 works without any problem, only different ports cause issues, and only on "localhost".

**Comment by Faless** [comment]
> What nodejs is listening to would be imho irrelevant, as irrelevant as it being even started or not. I'd expect at least an unresolved error

No, it's not irrelevant, unresolved error is if an address cannot be resolved, but if the address is resolved you will either get a connection refused, or if some firewall rule is active, it might even drop packets completely, without sending any port closed reply, and this letting the TCP connection hanging until it times out (that's a very common defence against scanning, syn/ack attacks, and so on).

That might not be your case, but it is a possibility.

That said, since you say that `::1` was removed from hosts file, can you provide a minimal reproduction project? With both the node.js and godot code?

Additionally, can you try resolving localhost with `print(IP.resolve_hostanme('localhost'))`?
What address does it resolves to?
Can you try connecting a TCP stream (StreamPeerTCP) to `localhost` and check that `get_status()` never reaches `STATUS_CONNECTED`? What status does it hang on?

Thanks.

**Comment by vicguedez** [comment]
@Faless This is still relevant. Windows 10, Godot 3.2-stable.

> print(IP.resolve_hostanme('localhost'))

Prints -> 0:0:0:0:0:0:0:1

Disabling IPv6 on the adapter does return 127.0.0.1 but it still wont connect. There is something wrong in `HTTPRequest` when it is trying to resolve domains like "localhost:8080", it fails to connec to them.

I'm using a restify (NodeJS) server

>server.listen(8080, function() {
  console.log('%s listening at %s', server.name, server.url);
});

And it won't connect. Firefox does open properly by using http://localhost:8080 or http://127.0.0.1:8080...

Also tried modifying my `hosts` file with no luck.

**Comment by vicguedez** [comment]
I give up, this is my host file:

>
127.0.0.1	localhost	server.local
::1		localhost	server.local

This is what restify returns:

>
restify listening at http://[::]:80
session: connected to Redis database

And I tried using this address:

>
http://localhost
http://server.local
http://127.0.0.1
http://my_public_ip

And I printed:

>
print(IP.resolve_hostname("localhost")) -> 0:0:0:0:0:0:0:1
print(IP.resolve_hostname("server.local")) -> fe80:0:0:0:d4df:2abc:408c:4cb
print(IP.resolve_hostname("127.0.0.1")) -> 127.0.0.1
print(IP.resolve_hostname(my_public_ip)) -> my_public_ip

And still, no error, no request.
