### ISSUE TITLE
Tilemap and Tileset - add a mirrored_offset property

### ISSUE THREAD

**Issue by Ranoller** [godotengine/godot#30262]
**Godot version:**

3.2 or after (feature proposal)

**OS/device including version:**

all

**Issue description:**

### Resume: 
Tilemap now mirror the offset by default. Would be great to specify which tiles should be mirrored in offset and which not.

### Explanation:
Currently tilemap mirror the tile offset when using flip_h, flip_v and transpose. The behavior is not incorrect but may prevent certain forms of design. It occurs to me, for example, that if you want to draw some "grass" or "plant" smaller than the tile and you want to place it on the bottom of the tile, you would like to flip the offseted texture without mirror... Currently there is a feature in merge process to add an option to center the textures (start the offsets in the middle of the tile), in which case you can put your drawing there, center, and offset Y **without gain "mirror" in flip_h**, but if you want to move the "grass" texture to a corner, or left or right, and you want to flip_h, you have the x mirror too ... so for manual offseting tiles and using flip and transpose both behaviors can be dessired, (both are correct, and one should not exclude the other because both have creative potential)

This property seems more suitable for tileset than tilemap, because you might want to have a tile that does not mirror the offset and another that does.

I think that this is a useful feature to adress.

### Objetive:
Make optional the current mirror behavior of tilemap making that dependent of a tileset property called "mirror_offset" or "mirrored_offset" and make it suitable per tile.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
