### ISSUE TITLE
Better handling of moving node hierarchies

### ISSUE THREAD

**Issue by epuscasu** [godotengine/godot#30271]
It would be nice if selecting multiple nodes in the Scene tab would keep the hierarchy when moving them around, specifically when making them children of other nodes.

Selecting and moving only a root note behaves as expected:
![image](https://user-images.githubusercontent.com/11788042/60542695-2f054e00-9d1d-11e9-9ca7-7a56fd7a47b8.png)

![image](https://user-images.githubusercontent.com/11788042/60542700-34fb2f00-9d1d-11e9-8a14-542675239e50.png)

Selecting and moving a whole hierarchy under a new parent flattens everything:

![image](https://user-images.githubusercontent.com/11788042/60542715-3af11000-9d1d-11e9-87a9-5ce77e6ded1d.png)

![image](https://user-images.githubusercontent.com/11788042/60542723-42181e00-9d1d-11e9-9075-4b37655482cc.png)

**Comment by sparkart** [comment]
Is there any reason you would want to select everything instead of selecting the parent, which essentially moves everything?

For me, it makes sense that it flattens the hierarchy because it's a selection of everything to move into the destination node.

If you wanted to move multiple nodes, like Wall12, and Wall13, which have similar hierarchy to Wall11 into Walls, selecting only the parents Wall12 and Wall13 should maintain their hierarchy.

**Comment by epuscasu** [comment]
The minimal example only has one parent, I encountered this inconvenience when having to move multiple Wall hierarchies. It would be nice to be able to shift-click a starting node, scroll 20 nodes down (expanded), shift-click an ending node and then drag them onto the new parent node, instead of either

1) Minimizing all 20 and shift-selecting them
2) Control-clicking 20 root nodes

and then dragging them onto the new node. 

If the flattening behavior is what makes sense to most people, then maybe add a way to minimize all selected hierarchies to their parent nodes, so it makes mass-moving easier?
