### ISSUE TITLE
GDScript doesn't issue an error when self-defining a local variable with the same name as a member

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#30284]
Godot 3.1.1

The following code fails as expected:

```gdscript
func _ready():
	var s = s
```

But this one succeeds and prints "null", but it should either issue an error too, or properly shadow `s` (with right-hand `s` being member, and left-hand `s` being local).

```gdscript
var s = 42

func _ready():
	var s = s
	print(s)
```

Seen on https://godotengine.org/qa/47663/instancing-same-scene-godot

**Comment by akien-mga** [comment]
Tested on Python 3, it throws an error there, we should likely do the same:
```
Python 3.7.3 (default, Apr  4 2019, 08:55:10) 
[GCC 8.3.1 20190329] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> s = 42
>>> def test():
...     s = s
...     print(s)
... 
>>> test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test
UnboundLocalError: local variable 's' referenced before assignment
>>> def test2():
...     s = 5
...     print(s)
... 
>>> print(s)
42
>>> test2()
5
>>> print(s)
42
```

**Comment by Scony** [comment]
@akien-mga your example from python is not necessarily relevant because in python you cannot have a global and local of the same name accessible at the same time (python 3.7.4):

```
s = 42

def foo():
    print(s)                    # reference global, 42
foo()

def bar():
    s = 3                       # local variable setting, global is not accessible anymore
    print(s)                    # refernce local, 3
bar()
print(s)                        # 42

def baz():
    global s
    s = 3                       # set global to 3
    print(s)                    # reference global, 3
baz()
print(s)                        # 3
```

so, python example doesn't help much.

let's take a look at JavaScript (1.8.5):
```
$ js
js> var s = 42
js> function foo() {
var s = s
print(s)
}
js> foo()
undefined
js>
```

looks like the problem is the same as in Godot.

So, let's take a look at TTCN-3 (using the proprietary compiler):
```
module main
{
    const integer s := 42;
    function foo() {
        var integer s := s;
        log(s);
    }
    control { foo(); }
}
```
Output of compiler:
```
main.ttcn3:5:21: error: #88 redeclaration of `s', already declared in line 3:19
    5 |         var integer s := 3;
      '                     ^
```

So, as far as GDScript is meant to be easy for everyone to understand, I propose to give up the shadowing and forbid a redeclaration of `s`.

**Comment by Scony** [comment]
@akien-mga your example from python is not necessarily relevant because the problem is about `member variable` not `global variable`. it's kind of similar, but different.

So, let's take a look at this example with `member variable`:
```
class C:
    def __init__(self):
        self.s = 42

    def foo(self):
        s = s                   # UnboundLocalError
        print(s)

    def bar(self):
        s = self.s
        print(s)                # 42
        s = 3
        print(s)                # 3
        print(self.s)           # 42

c = C()
# c.foo()
c.bar()
```

In python, one must use `self` prefix, so the situation is kind of different. So for GDScript, the two possibilities are on the table: shadowing and forbidding redeclaration (no shadowing). Since GDScript is meant to be simple and readable for anyone, I'd prefer not to introduce shadowing, as for newcomers it will be a source of very painful bugs.

P.S. JavaScript (1.8.5) seems to have similar problem (if we're talking about globals):
```
$ js
js> var s = 42
js> function foo() {
var s = s
print(s)
}
js> foo()
undefined
js>
```

**Comment by KoBeWi** [comment]
Still valid in 98ee852

**Comment by KoBeWi** [comment]
There is a shadowing warning now and you can turn it into an error, so this is resolved.
