### ISSUE TITLE
Enable "Convert Indent On Save" setting by default

### ISSUE THREAD

**Issue by regakakobigman** [godotengine/godot#30324]
**Godot version:**

3.1.1

**Issue description:**

This is an un-intrusive change that could complement #19285 in situations where the indentation style of a script doesn't match the editor settings. For example, the user may have their indent style set to spaces, but they open a project that uses tabs. When writing or copy/pasting code, it'll use spaces, which will conflict with the scripts already present in the project.

The editor already has a useful feature for this called "Convert Indent On Save", which will automatically fix the indentation whenever a script is saved. This usually means the user doesn't have to do anything, and the indentation will be fixed as soon as the script is saved or the project is run.

Because the setting already exists, doesn't have any significant side effects, and solves a common problem, I think it could be enabled by default.

<sup>(really, the main use of this is so I can just tell people to press Control-S to fix their indentation errors and appear like a wizard)</sup>

**Comment by RobKohr** [comment]
Yeah, I am going through the godot tutorial, and copy/pasting which makes indents spaces, and was super confused when I added new lines and they had errors due to them being tabbed in instead. It took me a bit to figure this out, and then I couldn't find a find and replace to fix this (which is an issue) but dug into the editor settings and found this option.

Personally, it would have saved me an hour if it was on by detail, though part of that hour was me just walking away annoyed to come back and see what the problem was.

**Comment by RobKohr** [comment]
Created a PR for this

**Comment by NikodemL** [comment]
I would just like to leave a note here that this change converted all our c# scripts from using spaces to using tabs, we don't like that, so we set the value to off in our fork of the engine.

**Comment by hilfazer** [comment]
> Because the setting already exists, doesn't have any significant side effects

I'm not sure about that. The setting can modify files that aren't following convention from current Editor Setting making scripts invalid when the project gets launched.
It can happen to files from addons which aren't supposed to be modified.
