### ISSUE TITLE
Depth maps are inverted

### ISSUE THREAD

**Issue by Linko-3D** [godotengine/godot#30344]
On a depth map the black should fakes depth and the white should be unchanged. In Godot this is the opposite the white fakes depth.

The right image is the correct result:

![depth map](https://user-images.githubusercontent.com/30020215/60739123-ff468800-9f60-11e9-931c-82b93cb4bf78.png)

**Comment by Zireael07** [comment]
Godot uses the a different channel for depth/normal maps, but I forgot the reasoning.

**Comment by Calinou** [comment]
To change this, you can select the depth map in the FileSystem dock, go to the **Import** tab, check **Invert** then click **Reimport**.

Changing the default depth would break compatibility, so it can't be done for 3.2. It could be done for 4.0 though.

**Comment by fracteed** [comment]
Yeah, I think this be changed for 4.0 so that we use height maps (the inverse of the current depth maps). It makes more sense and fits in with the terminology that other applications and engines use. Especially if we eventually get GPU tesselation/displacement it would save much confusion when using Substance and other material authoring software.

**Comment by KoBeWi** [comment]
Fixed in 4.0
