### ISSUE TITLE
Make new Inspector GUI Elements available as standard Control nodes

### ISSUE THREAD

**Issue by Mantissa-23** [godotengine/godot#30342]
The controls available in the new Inspector are perplexingly not available for plugin development, at least not outside of the Inspector itself.

Furthermore, many of the available control nodes (Resource Selectors, SpinBox, Slider are good examples) are inferior to the ones available in the Inspector, or there is just no equivalent. Considering the nature of the editor, is there any reason the new Inspector fields and elements couldn't be added as control nodes, while the current nodes could be made into legacy nodes?

**Comment by Zylann** [comment]
+1 for plugin development.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
