### ISSUE TITLE
GodotPaymentV3: querySkuDetails request more then 23 items, got: JNI ERROR (app bug)

### ISSUE THREAD

**Issue by etalot** [godotengine/godot#30386]
Android GodotPaymentV3: querySkuDetails request info for 28 items, got:

```
D/godot   (21920): response = {"skuDetailsToken":"AEuhp4JyKXx7bKWXFcyJ-0JsVmbHmCwHBoUpj2JYolSENwRcMfJBCFSUqDV"...
F/art     (21920): sart/runtime/indirect_reference_table.cc:98] JNI ERROR (app bug): local reference table overflow (max=512)
F/art     (21920): sart/runtime/indirect_reference_table.cc:98] local reference table dump:
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]   Last 10 entries (of 512):
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       511: 0x7215c160 java.lang.Class<java.lang.String>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       510: 0x7215bb70 java.lang.Class<java.lang.Class>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       509: 0x7215c160 java.lang.Class<java.lang.String>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       508: 0x72171598 java.lang.Class<java.lang.Number>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       507: 0x7215bb70 java.lang.Class<java.lang.Class>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       506: 0x721735e0 java.lang.Class<java.lang.Double>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       505: 0x7215bb70 java.lang.Class<java.lang.Class>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       504: 0x7215c160 java.lang.Class<java.lang.String>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       503: 0x7215bb70 java.lang.Class<java.lang.Class>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       502: 0x7215c160 java.lang.Class<java.lang.String>
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]   Summary:
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]         1 of java.lang.String
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]         1 of java.lang.Object[] (7 elements)
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]         1 of java.lang.Object[] (28 elements)
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]         2 of org.godotengine.godot.Dictionary (2 unique instances)
F/art     (21920): sart/runtime/indirect_reference_table.cc:98]       507 of java.lang.Class (7 unique instances)
F/art     (21920): sart/runtime/indirect_reference_table.cc:98] 
```

**3.1 branch 1-2 week fresh, custom android export build(use custom module) archv7**
minSdk 14
sdkCompile 28
ndk20

**Android 5.1.1 (Samsung Galaxy S6)**

if request 23 items no crush, 24 crush.

If try first call querySkuDetails for 14 items and with delay(5 sec) second part(14 items) same crush. Same for items 20/8, 22/6

I'm ready to test any suggestions

**Comment by Guaranapps** [comment]
Hello @etalot,
I had the same issue on Godot 2.1.6, I think this is due to **JNI memory leaks** in platform/android/java_glue.cpp because of missing many call to **env->DeleteLocalRef** / ReleaseStringUTFChars (I seems that this file is now named java_godot_lib_jni.cpp on Godot 3).

After adding some missing deleteLocalRef (mainly in **_jobject_to_variant** method) calls and backport correction of ReleaseStringUTFChars (https://github.com/godotengine/godot/pull/26328) on my custom build I can call querySkuDetails with 44 skus, but my game still crash with 45 or more sku, unfortunalty I need more than 45 skus :(

A workaround that works for me is splitting calls to querySkuDetails by waiting for result callback (sku_details_complete) to launch next call (@etalot mabye you can try this instead of using 5 sec delay to see if it's better in your case)

If it can help, I have attached my customized [java_glue.cpp](https://github.com/godotengine/godot/files/3464070/java_glue.cpp.zip) (now named java_godot_lib_jni.cpp) file, it contains missing calls to env->DeleteLocalRef. You can try to add them in method _jobject_to_variant of your java_godot_lib_jni.cpp file.

**Comment by etalot** [comment]
Hi @Guaranapps , thank you. But now I don't have time to play with this issue.
Godot's GodotPaymentV3 implementation have other issue, stability issue. 1 of 10 starts finish with crush.

I think I tried do second response with pause, but I'm not sure. And this didn't help.
I group items with same price and now I need only about 18 items for querySkuDetails =)

**Comment by SinaZK** [comment]
Any Updates on this issue?

**Comment by m4gr3d** [comment]
This issue should now be resolved and the payment module has been moved to its [own repo](https://github.com/godotengine/godot-google-play-billing).
