### ISSUE TITLE
Add swappable/customizable control schemes for InputMap

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#30395]
**Issue description:**

If one wanted a game that remaps a subset of controls to different inputs based on...

1. a game-specific state machine, such as different control schemes for different playable vehicles (can/can't turn, strafe, move vertically, etc.).
2. a user-preference, such as Super Smash Bros. Ultimate, FPS games, etc. (Default, Inverted, Southpaw, etc.)

...they would have to manually program a system to swap and customize multiple sets of input mappings and then merge them all together properly. That is a great idea for a plugin (sure?), but it's really something that sounds like it should be built into the engine by default as configuration / ProjectSettings data.

**Solution suggestion:**
Modify the existing InputMap editor so that one can create 1+ InputAction collections which are named (and hence referenceable from the scripting API), ordered (so that one collection will overwrite changes from another collection), and optional (so that some can be rendered inactive, to be later swapped in via scripts).

If we make the collections be the top level of the Tree node and have it start with at least one level, the current InputMap's use case would be preserved with everything just being moved out one level of depth in the Tree. If one then tries to add more complexity to the design of their input map, as described above, it would be a simple matter of specifying *another* InputMap for the differences in controls, marking which InputAction collections are active/inactive and re-ordering them as needed (some drag-and-drop functionality perhaps).

I would also advise, in this case, to allow users to add, delete, and duplicate individual InputAction collections.

WDYT?

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
