### ISSUE TITLE
hint_tooltip impossible to unset

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30448]
**Godot version:**

3.1

**Issue description:**

By default an unset hint_tooltip will not display a tooltip upon mouseover. However once set there is no way to restore this behavior, as setting "" will result in an empty tooltip to appear, instead of none at all.

Setting an empty string, or null, should clear the tooltip entirely and prevent it from showing.

**Comment by Meriipu** [comment]
or a method to clear it?

**Comment by TheDuriel** [comment]
That works. But it would need to be called when setting "" as well. Or you'd be forced to check if its "" yourself, then call the method.

**Comment by Meriipu** [comment]
I was just thinking incase somebody really wanted an empty tooltip (though I can not see much reason for it or that it could not be done by setting it to a space)

**Comment by sparkart** [comment]
The problem seems to be related to spaces in the hint. If you set the tooltip using the method `set_tooltip("")` the does not show.

If you erase the hint in the editor.... make sure you remove any spaces by pressing CTR + A and deleting or clicking the circle arrow button next to the "tooltip" caption in the hints property.

**Comment by TheDuriel** [comment]
Doing it through code, not the editor. Setting "" retains the hint. Please prove me wrong though. <3
