### ISSUE TITLE
SoftBody Troubles

### ISSUE THREAD

**Issue by OriginalAGP** [godotengine/godot#30472]
**Godot version:**
3.1.1 Mono Stable

**OS/device including version:**
Windows 10

**Issue description:**
I'm trying to do Batman's cape. I've suspended it by eight vertices on the shoulder. But two things happen: it's only help by one of the shoulders and the end of the cape appears stuck, as if nailed, to the floor. The following is a screenshot: https://www.dropbox.com/s/fvwqo2vur83ncbl/BatCapeProblem.png?dl=0

**Comment by Calinou** [comment]
@OriginalAGP Can you (or anyone else) still reproduce this bug in [Godot 3.2.2](https://godotengine.org/article/maintenance-release-godot-3-2-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
