### ISSUE TITLE
Disable/fix spinbox drag functionality

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#30479]
**Godot version:**

3.1

**Issue description:**

Spinbox is responsible for 

https://github.com/godotengine/godot/issues/30242

https://github.com/godotengine/godot/issues/11893

GraphEdits zoom spin box also has this problem.

To reiterate:

When moving drag data from get_drag_data over a spinbox node, the mouse cursor vanishes and locks. Sometimes it can be recovered though clicking, but that heavily depends on the circumstances.

**Comment by sparkart** [comment]
`get_drag_data()` returns an `Object` In the linked example: https://github.com/godotengine/godot/files/3348065/TreeMouse.zip you're returning a boolean. According to the documentation, you should return `null` if nothing should be passed.
Modifying the code so that it returns `null`, instead of 'false' seems to work.

**Comment by KoBeWi** [comment]
Another related issue: #42596

Last time I tried dragging it was quite buggy (at least in ColorPickers). You need to click in a specific spot to trigger it, otherwise you are selecting text or nothing happens.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/43608, which has more information about the issue at hand.
