### ISSUE TITLE
Add 2D vector drawing tools

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#30482]
I wish I could directly draw vectors into the editor and then animate them right there in the editor.  

This would speed up dev considerably, as one would not have to go back-and-forth between a third party vector drawing application and Godot to get the result that they need in their game. 

It would be like Adobe Flash was, where you could do exactly this.

**Comment by groud** [comment]
Related to #4826

**Comment by TheDuriel** [comment]
Basic SVG support exists. There also happens to be Polygon2D type which implements most basic vector features.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
