### ISSUE TITLE
Camera2D - More options if viewport is bigger than limits.

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#30530]
Currently camera behaviour is unpredictable if the viewport is bigger than the camera's limits.
Generally it puts everything in the top left of the screen which is kinda wonky.

The main use case of this is better support for multiple screen sizes for 2D games without resorting to the ol' scale up a single resolution guarenteed to work trick.
I think it would also help if these effects could be on a per-axis basis.

- Ignore limits if bigger.
- Centre the area inside the limit
- Zoom in until it fits (While somehow also leaving GUI intact...)

Obviously some of these options will be wierd for games that use limits to hide wonky stuff offscreen but the current version doesn't hide them anyway.

**Comment by KoBeWi** [comment]
Another option could be drawing a border outside the limits (with specified color).

**Comment by ElfEars** [comment]
Another thing I'd like to suggest (in reference to the above by @KoBeWi) would be a textured border

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
