### ISSUE TITLE
RigidBody in an Area node with gravity point increases it's speed continuously

### ISSUE THREAD

**Issue by udit** [godotengine/godot#30575]
**Godot version:** 3.1.1

**Issue description:**
Expected behaviour : A RigidBody inside an Area node with gravity and gravity_point enabled, when not influenced by any other force apart from gravity of the area should not gain momemtum/speed over time.

Current behaviour: RigidBody's speed keeps increasing over time.

**Steps to reproduce:**

1.  In Project Settings -> General -> Physics -> 3d, set 
Default Gravity = 0,
Default Gravity Vector = 0,0,0
Default Linear Damp = 0
Default Angular Damp = 0 

2. Add Spatial node and add Area node as a child, and set
Gravity Point = on
Gravity Vector = 0,0,0
Gravity = 100
Linear Damp = 0
Angular Damp = 0

3. Add CollisionShape as a child of Area
Set shape as New SphereShape and increase it's radius to a sufficient size like 100

4. Create a new scene and add RigidBody and add a CollisionShape and MeshInstance as childs
Move the body away from 0,0,0 so it starts orbiting the gravity point.

5. Add a camera to the scene

6. Optional - add script to RigidBody to print velocity to confirm.

**Minimal reproduction project:** [GravityBug.zip](https://github.com/godotengine/godot/files/3389490/GravityBug.zip)

**Preview** 
![GravityBug](https://user-images.githubusercontent.com/6249061/61179741-a80e7a80-a626-11e9-9bad-7b1de3fbc6b7.gif)

**Comment by Harvzor** [comment]
Reproduced with the supplied project on 3.2.1.

I'm also having issues with 2D gravity points and orbits not being symmetrical.

**Comment by udit** [comment]
@Harvzor Can you elaborate on orbits not being symmetrical (probably with a minimal reproduction project)? I was working on a 2D project and 2D gravity point physics worked as expected.

**Comment by Harvzor** [comment]
I'm still trying to figure this out.

The only think I've found is that setting  `gravity_distance_scale` to `0.001` causes causes my orbit to (very) slowly get smaller and smaller.

I still have another issue with orbits not being symmetrical. I stripped my project down until the bug was no longer present so I know there's an issue with how I set things up.

**Comment by JestemStefan** [comment]
I tested provided project and:
Test1:  with Area LinearDamp back to default value 0.1 there is no bug. (The rigidbody have stable orbit/amplitude over 15 minutes)

Test2: With any value below 0.1 the bug is present (Tested with 0.099)

Test3: With value over 0.1 (like 0.2, 0.3, 0.4) there is no bug again

**Comment by Geometror** [comment]
This bug is related to Bullet. Switchting to GodotPhysics fixes the problem,
the amplitude increases only very slightly over time (on the 6th decimal place) presumably due to floating point error.
As Bullet will be removed in Godot 4.0 I think this issue can be closed.

**Comment by Harvzor** [comment]
I've managed to recreate the issue with the orbit not being symmetrical: https://github.com/Harvzor/godot-gravity-test

There's also a video on the repo which shows the issue: https://raw.githubusercontent.com/Harvzor/godot-gravity-test/master/godot-gravitytest.webm

I've tried tweaking many random settings, including changing the physics engine to GodotPhysics rather than default (Bullet), but the settings don't seem to make a difference.

**Comment by bend-n** [comment]
> This bug is related to Bullet. Switchting to GodotPhysics fixes the problem, the amplitude increases only very slightly over time (on the 6th decimal place) presumably due to floating point error. As Bullet will be removed in Godot 4.0 I think this issue can be closed.

As Bullet is removed now, can this be closed?

**Comment by bend-n** [comment]
@harvzor Can you create a separate issue?

**Comment by harvzor** [comment]
My issue is more with unstable orbits rather than the speed of objects increasing, so I think it's fair to say it's a separate issue.

Created a new issue: https://github.com/godotengine/godot/issues/68348

Probably this issue can be closed, though I haven't checked myself that GodotPhysics solves it. At least in my projects, acceleration isn't much of a problem.

**Comment by udit** [comment]
Can confirm this issue does not happen in Godot 4. In Godot 3, it can be fixed by switching to GodotPhysics. Closing this.
