### ISSUE TITLE
var_name() / func_name() to get variable/function name as string

### ISSUE THREAD

**Issue by LotsaBugs** [godotengine/godot#30573]
__Feature Request (GDScript):__
Built-in function, __*var_name()*__, to get variable name as string.
Similarly, __*func_name()*__ would return the name of a function as a string.

__Example:__
```
const char_id := "Wizard"
const char_lvl := 100
const char_weapon := "Wand"

const char_array := [char_id, char_lvl, char_weapon]

func display_char_info():
	for _element in char_array:
		print( var_name(_element) + ": " + _element)

func _ready():
	call( func_name(display_char_info) )

```
__Desired output:__
```
char_id: Wizard
char_lvl: 100
char_weapon: Wand
```

**Comment by vnen** [comment]
If `var_name(_element)` were supposed to return `"_element"` that could make sense, since it can be resolved at compile time. Totally unfeasible (if not impossible) to get the variable that was added in the array.

For that particular case in the example I'd use a dictionary with string keys.

**Comment by LotsaBugs** [comment]
Thanks for your reply.
It can't be done on array elements? I see.

My use case would be mostly for using variable names as keys in dictionaries.
But I'd rather not have to make a const string key for each variable, since it doubles the number of variable declarations and leads to confusion.

I've been using "k_" as a prefix to show that a variable is a const string to be used as a key inside a dictionary, but it seems kind of hacky. I think a built-in var_name() function would make things more manageable.

__Example (confusing, doubled variable declarations at the top)__
```
var Name := "Wizard"
var Health := 100
var Offense := 20
var Defense := 5

const k_Name := "Name"
const k_Health := "Health"
const k_Offense := "Offense"
const k_Defense := "Defense"

const all_char_stat_keys := [k_Name, k_Health, k_Offense, k_Defense]
var all_char_stat_values := [Name, Health, Offense, Defense]

var test_character_1 := {}

func assign_char_dict(_char_dict : Dictionary):
	assert all_char_stat_keys.size() == all_char_stat_values.size()
	for _index in range(all_char_stat_values.size()):
		var _current_stat_key = all_char_stat_keys[_index]
		var _current_stat_val = all_char_stat_values[_index]
		_char_dict[_current_stat_key] = _current_stat_val


func print_char_dict_pretty(_char_dict : Dictionary):
	for _current_key in _char_dict:
		var _current_value = _char_dict[_current_key]
		print(_current_key + ": " + str(_current_value))


func _ready():
	assign_char_dict(test_character_1)
	print_char_dict_pretty(test_character_1)
```
__Prints:__
```
Name: Wizard
Health: 100
Offense: 20
Defense: 5
```

Also, I it would make doing something like this possible:
```
func set_otherscript_var(_var, _value):
	otherscript.set(var_name(_var), _value)
```

Here's what the the top section of the first example would look like with the var_name() function:
```
var Name := "Wizard"
var Health := 100
var Offense := 20
var Defense := 5

var all_char_stat_values := [Name, Health, Offense, Defense]

var test_character_1 := {}

func assign_char_dict(_char_dict : Dictionary):
	for _current_stat_val in all_char_stat_values:
		var _current_stat_key = var_name(_current_stat_val)
		_char_dict[_current_stat_key] = _current_stat_val
```

**Comment by CodeDarigan** [comment]
> My use case would be mostly for using variable names as keys in dictionaries.
But I'd rather not have to make a const string key for each variable, since it doubles the number of variable declarations and leads to confusion.

When using dictionaries, you can assign like {identifier = value} rather than {'identifier' = value} (it would be dict.identifier = value if you didn't assign it when you created the dictionary). These don't really act like consts in any meaningful way but I'm imagining you just want to avoid using too many raw strings?

**Comment by LotsaBugs** [comment]
> I'm imagining you just want to avoid using too many raw strings?
Yeah, I find it too easy to make a typo if I'm manually typing dictionary string keys.
Also, I don't get auto-completion for them later if I do that.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by vnen** [comment]
BTW, there's a similar proposal here: https://github.com/godotengine/godot-proposals/issues/837
