### ISSUE TITLE
X-ray view into intermediate GPU buffers contributing to a 3D rendering.

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#30638]
So, I was just watching a video on some custom tools that the Horizon: Zero Dawn folks used, and they had [this nifty thing](https://youtu.be/KRJkBxKv1VM?t=398) that allowed them to peer into the 3D world and see the exact intermediate buffers that are contributing to the final image (some GPU tools).

I know exceptionally little about internal GPU stuff and have no idea how this would exactly be useful, but it *sounds* like it would be an exceptionally powerful debugging tool when used for the right situation.

I am creating this issue simply because I felt that people may want to weigh in on how useful a tool like this might be / make a space for reminding us that it is desired (if it turns out to be).

**Comment by clayjohn** [comment]
This looks incredible!! 

That being said. Im not sure it adds anything of value over just using an existing tool like renderdoc.

**Comment by willnationsdev** [comment]
Perhaps we should open this up to asking whether there are any GPU profiling tools that people would like to have added to Godot natively?

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by clayjohn** [comment]
Also note, 4.0 is coming with a bunch more Viewport render modes to visualize intermediate buffers in the editor!
