### ISSUE TITLE
Confirm/Cancel buttons of FileDialog are swapped on Web Export

### ISSUE THREAD

**Issue by 2shady4u** [godotengine/godot#30653]
**Godot version:**
3.1 Official

**OS/device including version:**
Windows 10 vs. HTML5 Web Export

**Issue description:**
Confirm and Cancel buttons are swapped on the HTML5 web export for some reason.
(Confirm can be Save/Open/etc... depending on FileDialog.mode)

Windows exported build (debug):
![windows](https://user-images.githubusercontent.com/42484461/61396475-1b82e700-a8c8-11e9-9af6-6550a0b9efa4.PNG)
vs.
HTML5 vs. Web Export:
![web](https://user-images.githubusercontent.com/42484461/61396468-19b92380-a8c8-11e9-99ac-119c464c64b0.PNG)

**Steps to reproduce:**
Add a FileDialog to your Godot Project, make it popup and export for both Windows and HTML5. Compare the position of the buttons.

**Comment by Calinou** [comment]
This is because the [OK/cancel buttons are swapped by default on Windows](https://github.com/godotengine/godot/blob/d087a9e3283528792634de84b55a607d9b9b5137/platform/windows/os_windows.h#L347). However, the HTML5 platform doesn't try to check whether your host platform is Windows to swap the button order.

An alternative would be to drop the button swapping behavior altogether, which could benefit users using Godot on Windows and another platform.

**Comment by 2shady4u** [comment]
Well, this did confuse the ever-living hell out of me.
Would it make sense for the HTML5 build to check the OS during operation?
or is this something beyond a simple if-loop?

**Comment by akien-mga** [comment]
Why close it? I think @Calinou's suggestion to check the host platform to enable the OK/cancel button swap on Windows hosts makes sense.

**Comment by 2shady4u** [comment]
I'll reopen it.
Reason I closed this issue is because it wasn't really an error and I didn't really see the point in pursuing it beyond checking if it was "operating as intended".
