### ISSUE TITLE
Show instruction count of compiled shader in editor

### ISSUE THREAD

**Issue by loganjk** [godotengine/godot#30679]
**Godot version:**
3.1.1 win64 (Classical)

**OS/device including version:**
Windows 10 Pro, Intel i7-4790K, integrated GPU only (Intel HD Graphics 4600), driver igdkmd64.sys version 20.19.15.5058

**Issue description:**
It would be helpful to see a count of the number of instructions in a compiled shader while in the editor. If your shader is close to the maximum instruction count, or causes crashes because it exceeds the maximum, you might refactor to reduce the number of instructions, and being able to see the count would help determine the effectiveness of code changes.  I find myself in this situation now, having hit the maximum for a large fragment shader.

*Bugsquad edit:* Follow-up to #30666.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
