### ISSUE TITLE
Question about font scaling

### ISSUE THREAD

**Issue by Quest79** [godotengine/godot#30702]
@chris13524 on the text label's inspector you can go to rect and change the scale.

_Originally posted by @hasahmed in https://github.com/godotengine/godot/issues/1919#issuecomment-369464977_

Doing this messes up other things like layout. Try it in the latest version. Make a button name it START, scale it 2x then try and use the layout tool to center it. Internal code must be setting the initial fond sizing of "start" text, why cant we access that directly in the inspector?

**Comment by TheDuriel** [comment]
Digging up old comments with wrong information. So to set this clear:

Doing what is described in that comment does _not_ resize the font. It simply scales up the plane upon which the font texture is mapped. The result is blurry, or pixelated, at best, depending on if you have filtering on or off on the font.

Since fonts are pre rasterized, as part of the resource. There is currently no way to give each control node unique font settings. (Doing so would create pointless duplicates of the font resource for each node.) Not to mention that you should be using a theme anyways.

What is needed is for the engine to handle vector fonts properly. And for people to start using themes properly ;P

**Comment by clayjohn** [comment]
@Quest79 The issues section of Github is not a place for you to provide comments about previous comments on an issue that has been dead for years. If you want to ask the best way to dynamically size a font, use the discord or the forums. 

In response to that thread the DynamicFont was created. http://docs.godotengine.org/en/latest/classes/class_dynamicfont.html

Closing since TheDuriel has explained the misconception in the original comment. 

If you have a bug to report, please open another issue and use the template provided.
