### ISSUE TITLE
Should the Set methods be removed?

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#30744]
@neikeq So basically, this code fails with a compiler error:

    Transform.origin = Vector2.Zero; // Error CS1612 cannot modify return value.

I assumed that the Set method was a way to work around this problem:

    Transform.origin.Set(Vector2.Zero);

But after actually testing this... this code silently fails and does nothing at all! It seems that the `Set()` methods only work with variables that are otherwise settable with `=`:

    Vector2 a = Vector2.One;
    a.Set(Vector2.Zero); // Works.
    a = Vector2.Zero; // Or you can just do this...

Considering that they add nothing new and can silently fail, they should probably be removed.

If you run a blame on this file, you will see that Vector2's `Set` was added by... uh... me... but I was just trying to make Vectors consistent with Quat which [already had this](https://github.com/godotengine/godot/commit/ff97c97c930f80209480c630622b1b64372bd65a#diff-aff89657dda2c194037126619efa69b4L94). 

Quat also has `set()` [in core](https://github.com/godotengine/godot/blame/master/core/math/quat.h#L112), which is where it came from, so is / was there a purpose to Quat's `set()` method and what was it, and should it be removed too? It seems to have existed [before](https://github.com/godotengine/godot/blame/45438e9918d421b244bfd7776a30e67dc7f2d3e3/core/math/quat.h#L102) @akien-mga's very [musical commit](https://github.com/godotengine/godot/commit/5dbf1809c6e3e905b94b8764e99491e608122261#diff-46e3482d3d8d24cdcef5fb32c7380f82R97) (cc @reduz). I know that, for example, this works just fine in GDScript:

    transform.origin = Vector2.ZERO # Works

So, it's a good thing that @akien-mga rejected me adding this into core, as not only is it not a problem in GDScript, but also the "solution" doesn't work either...

Sorry for the long post, but I just wanted to post the whole story of `Set()` to my knowledge.

**Comment by neikeq** [comment]
Indeed, the compiler doesn't give an error `CS1612` for methods that mutate the struct. We should deprecate all such methods. Considering the severity of this, it may be better to forbid using them with `[Obsolete("...", error: true)]`.

Here is what I found from a quick look:

- `Vector2` -> `Set(Vector2)`, `Set(real_t, real_t)`
- `Vector3` -> `Set(Vector3)`, `Set(real_t, real_t, real_t)`
- `Quat` -> `Set(Quat)`, `Set(real_t, real_t, real_t, real_t)`, `SetAxisAngle(Vector3, real_t)`, `SetEuler(Vector3)`

None of these methods need an immutable replacement. For `q.SetAxisAngle(axis, angle);` that would be `q = new Quat(axis, angle);`. For `q.SetEuler(eulerYXZ);`, `q = new Quat(eulerYXZ);`. Although I find the latter would be better as `Quat.FromEuler(eulerYXZ)` instead of a constructor.
