### ISSUE TITLE
NON WORKING ANIMATED SPRIT

### ISSUE THREAD

**Issue by dijam8** [godotengine/godot#30784]
**Godot version:**

3.1

**OS/device including version:**

ubuntu 18.04.2 LTS , intel chip

**Issue description:**

my animated sprit does not working
when i press up the player jump and it play the first frame and ignore the rest
there is for frames but just the first who play
**Steps to reproduce:**
create animated sprit add frames to it and run the geme
[platformer 2.zip](https://github.com/godotengine/godot/files/3424148/platformer.2.zip)

 

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
Your problem lies here:
```
if not $Sprite.play("attack"):
    $Sprite.play("idle")
```
You are continuously playing "attack" and "idle" animations (btw, `play()` isn't for conditions, it just plays the animation) and they override your "jump".

That said, it's obviously not a bug in Godot. Next time if you are not sure about something, try asking on [other community channels](https://godotengine.org/community) first. GitHub is only for issues with the engine.

**Comment by Zylann** [comment]
The character doesn't jump because your code is trying to play `attack` and `idle` and `jump` all at once, every frame. It works if only `jump` is called, but because you call different animations before, it starts from the beginning, which is expected.

So you are basically not using `AnimatedSprite` correctly. To fix this, you should start only one animation at a time, or better, play it just once, at the frame where the jump starts, and it will animate until you tell it to play another animation (no need to call `play()` every frame).

Note: in your code you play `atack` and `attack`. But `attack` doesn't exist, only `atack` is defined.

**Comment by dijam8** [comment]
thanks
