### ISSUE TITLE
Atlas_tile tex_offset

### ISSUE THREAD

**Issue by Artifir** [godotengine/godot#30781]
Hi. Why each tile in Atlas_tile dont tex_offset? I will be very grateful if this property becomes an array.

**Comment by bojidar-bg** [comment]
Please add some more details to your issue, such as where is this Atlas_tile located (I shouldn't have to search to understand it is tilemap related) what usecase you have in mind, etc.

**Comment by Artifir** [comment]
Sure!
Me need do dinamic tex_offset. I dont make its in atlas_tile. I have 10+ tileset in one tilemap on 300 tiles (some 3000), and I can not use single tile for this.
![Безымянный](https://user-images.githubusercontent.com/53236247/61821083-13462100-ae5f-11e9-951d-a84000ab9b60.png)

**Comment by Artifir** [comment]
![Безымянный](https://user-images.githubusercontent.com/53236247/61821518-1beb2700-ae60-11e9-8390-3eb06d95e038.png)

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
