### ISSUE TITLE
Text editor view not updating when typing in last line

### ISSUE THREAD

**Issue by tsafs** [godotengine/godot#30793]
**Godot version:**
v3.3.1

**OS/device including version:**
Windows10

**Issue description:**
When typing at the end of a script (last line) the view is not updated properly / scrolled down such that I would see what I'm typing. In the image, see the red line at the bottom, which is where I was typing. I expect the view to display that line.

**Steps to reproduce:**
Try it out yourself :-)

![Capture](https://user-images.githubusercontent.com/6010491/61793249-f7bb2600-ae1e-11e9-89d4-a0ccef37b9c7.JPG)

**Comment by sparkart** [comment]
Using both version 3.1 and 3.2 latest branch, the script editor scrolls down to the last line when I type. Could you provide step by step instructions or maybe a project file?

I am also running on Windows 10.

**Comment by groud** [comment]
> v3.3.1

This version does not exist, could you you check again ?

**Comment by newold3** [comment]
when you use the control TextEdit and you write in last line, and max height of whole text written in it is bigger than textEdit height, the scroll is not update and you will be writing without being able to see what you have written until you scroll manually

**Comment by rkfg** [comment]
This is indeed an issue in the current master that I just compiled to confirm. It can be worked around by resizing the bottom area that contains Output, Debugger and other tabs so that the editor window has a (roughly) non-fractional number of visible lines.

When it's collapsed or has a "wrong" size:
![record-2019-11-09_13 20 46](https://user-images.githubusercontent.com/184066/68527342-d8c1a080-02f6-11ea-90ef-c87f06fbd101.gif)

When it's expanded and has a "right" size:
![record-2019-11-09_13 22 11](https://user-images.githubusercontent.com/184066/68527362-fe4eaa00-02f6-11ea-9132-ab7bb887f729.gif)

**Comment by rkfg** [comment]
I noticed that scrolling works as expected if the horizontal scroll bar is visible! As a workaround you can simply increase the right dock size to make that bar appear.

**Comment by KoBeWi** [comment]
Still valid in be14d9d

**Comment by KoBeWi** [comment]
Can't reproduce anymore in c13319d
