### ISSUE TITLE
Compile error: 'cl is not recognized' for Visual Studio 2019 dev tools

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#30797]
**Godot version:** adae2b073811d0f81afdfab277fdb27d2ba9f16a

**OS/device including version:** Windows 10, latest upgrade (Windows [Version 10.0.18362.239])

**Issue description:**

```
C:\Users\deno\Documents\Projects\Godot\GodotEngine\godot>scons platform=windows
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
 Found MSVC version 14.1, arch None, bits=32
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[  1%] run(["core\method_bind.gen.inc", "core\method_bind_ext.gen.inc", "core\method_bind_free_func.gen.inc"], ["core\make_binders.py"])
Executing builder function in subprocess: module_path='C:\\Users\\deno\\Documents\\Projects\\Godot\\GodotEngine\\godot\\core\\make_binders.py', parameter_file='C:\\Users\\deno\\AppData\\Local\\Temp\\1eeea726d1514410815ffc34587c2b61.json', parameter_file_size=16215, target=['C:\\Users\\deno\\Documents\\Projects\\Godot\\GodotEngine\\godot\\core\\method_bind.gen.inc', 'C:\\Users\\deno\\Documents\\Projects\\Godot\\GodotEngine\\godot\\core\\method_bind_ext.gen.inc', 'C:\\Users\\deno\\Documents\\Projects\\Godot\\GodotEngine\\godot\\core\\method_bind_free_func.gen.inc'], source=['C:\\Users\\deno\\Documents\\Projects\\Godot\\GodotEngine\\godot\\core\\make_binders.py']
[  1%] Compiling ==> platform\windows\godot_windows.cpp
'cl' is not recognized as an internal or external command,
operable program or batch file.
scons: *** [platform\windows\godot_windows.windows.tools.32.obj] Error 1
scons: building terminated because of errors.
```

I regularly compile Godot from source. It always worked fine when I still used Visual Studio 2017 with the 2017 developer command line tool.

After uninstalled VS2017 and installing Visual Studio 2019 and 2019 developer command line tool I'm unable to make Godot source compile with new Visual Studio developer tool 2019.

I reinstalled Developer command line tool 2017 in Visual Studio 2019, and it works fine again. 

Kinda strange error if you ask me ... why should 2017 work and not 2019?

**Steps to reproduce:** 

If you used Visual Studio 2017, uninstall it and install Visual Studio 2019.

You will see that Dev tool 2019 isn't able to compile Godot, you have to install Dev tool 2017.

**Comment by akien-mga** [comment]
What SCons version do you have?

Many users are using VS 2019 to build Godot so the problem must be in your environment. Either your SCons is too old, or you lack some of the VS 2019 components necessary to build C++.

**Comment by Qws** [comment]
@akien-mga 

If many people are compiling Godot with VS2019 without problems I guess the problem was indeed in my environment... I think I missed something important during the VS2019 installation because I wanted a minimal set-up.

I thought VS2019 developer command line tool is all I needed but then I installed "Desktop development C++ for Windows"-package too and now everything works fine.

I guess this issue was made by my error in the environment setup... so I think this can be closed 😅.

**Comment by kone9** [comment]
Godot Engine Gdnative Solution cl is not recognized as an internal or external command "
Godot Engine C ++ Solution  cl is not recognized as an internal or external command 

``` ruby
 "cl" is not recognized as an internal or external command ".
```


# It was because you had to put the path in the windows environment variables.

Sorry there are some things in Spanish,
but I leave the screenshots.

Edit the environment variables for this account.
![Screenshot_1](https://user-images.githubusercontent.com/12847027/131401788-0bff6b2d-d1b4-4dcb-9399-54ff5d519c6b.jpg)

go to path then edit
![Screenshot_2](https://user-images.githubusercontent.com/12847027/131401882-b39f0292-f246-4193-badc-d774d4222442.jpg)

add a new
![Screenshot_3](https://user-images.githubusercontent.com/12847027/131401939-95e7ee39-fb18-422a-95f9-e364eb9f9983.jpg)

look for it in the installation folder, in my case, it is in the default folder.
![Screenshot_4](https://user-images.githubusercontent.com/12847027/131402004-179b6165-3ff5-4c04-9037-206633d8e412.jpg)

So this would be the address of the default folder
``` ruby
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64
```
After doing all that, accept the options and restart the computer

As we can see, it now compiles correctly.
![Screenshot_6](https://user-images.githubusercontent.com/12847027/131402877-8436658d-a98a-4417-ae07-9a57c8d2adcd.jpg)

And so spin the cube using C ++ within Godot Engine.
[https://github.com/kone9/Godot_Engine_GDNative_CPP_Proyect_Config](url)

![Godot Engine GDnative](https://user-images.githubusercontent.com/12847027/131403646-8145c825-ff8f-4792-96d2-a1e3b8877eb7.gif)
