### ISSUE TITLE
App is using an old version of Google Play developer API.

### ISSUE THREAD

**Issue by enrikqose** [godotengine/godot#30809]
**Godot version:** 
2.1.6 stable

**OS/device including version:**
Windows 10 64bit

**Issue description:**
Google Play Console is showing me this message:
 "We’ve detected that your app is using an old version of the Google Play developer API. From 1 December 2019, versions 1 and 2 of this API will no longer be available. Update to version 3 before this date. [Learn more](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html)"

**Steps to reproduce:**
Export game for andorid that uses in-app purchases.
I also use admob module from [kloder-games](https://github.com/kloder-games/godot-admob)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I looked for any references to the "[androidpublisher](https://developers.google.com/api-client-library/java/apis/androidpublisher/v3)" API this refers to, but couldn't find any in either Godot or the AdMob module.

So I'm clueless about this warning. Maybe a thirdparty library downloaded by Gradle uses it?

CC @volzhs

**Comment by akien-mga** [comment]
Do you get the issue if you upload a game without the AdMob module?

**Comment by enrikqose** [comment]
I have another game exported with godot 2.1.6 that uses the same admob module, iap and google paly services from [this](https://github.com/FrogSquare/GodotGoogleService) module, and I dont get this message on that game. Also user "u/SHlNOBU" on [this](https://www.reddit.com/r/godot/comments/chkyx9/google_play_console_is_showing_me_this_message_on/) reddit post commented: "This also appeared on mine. I have no idea what it means tho. I only have admob and share module without iap"

**Comment by akien-mga** [comment]
> I have another game exported with godot 2.1.6 that uses the same admob module, iap and google paly services from this module, and I dont get this message on that game.

That's pretty weird then :/
Is there any way to get more details about what the Google Play Console "detected"?

**Comment by enrikqose** [comment]
Send me your email I will send you an invite to add you to my google play developer account with read only access.

**Comment by mbrlabs** [comment]
Related issue: #30323

**Comment by Shin-NiL** [comment]
Maybe something related with this file?
https://github.com/godotengine/godot/blob/2.1/platform/android/java/aidl/com/android/vending/billing/IInAppBillingService.aidl

**Comment by volzhs** [comment]
i have no clue either.

**Comment by ICatRegister** [comment]
Buil-in in-app purchases uses deprecated AIDL billing API in both 2.1 and 3.1

**Comment by allkhor** [comment]
Any idea about how to fix that? My game not used any in-app purchases, but google console show that warning. Godot 2.1.6 without any modules.

**Comment by xsellier** [comment]
I have an application published on the Google Play Store too, but I don't have any warning from google about it (maybe it will come later). I don't use any ad in my game (no admob, no ads at all).

About the deprecation, I think that the IAP implementation of Godot is completely fine because:
![image](https://user-images.githubusercontent.com/6616005/66784464-8b454580-eea8-11e9-8736-3b56fe582178.png)
(cf: https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html)

Im also using the Google Play Service API, but I've made my own module, so feel free to use it if needed:
https://github.com/binogure-studio/godotandroid

**Comment by timoschwarzer** [comment]
As of today, Google states that AIDL is deprecated and apps have to migrate to the Google Play Billing API (source: https://developer.android.com/google/play/billing/api)

**Comment by timoschwarzer** [comment]
I'm looking into working on a PR, but it will probably break the GodotPayment API. What do you think @akien-mga, should this still land in 3.2? I'd write an upgrade guide for users of the current payment module.

**Comment by akien-mga** [comment]
If this a changing requirement from Google, we have no option but to include the changes in 3.2 so that users can keep using it in production.

But if we can avoid breaking the API in 3.2, that would be better. We can break it in 4.0 to make the plugin better, but for 3.2 the priority should be that users can keep using their existing code.

Note however that 3.2.2 already breaks compat somehow by changing the plugin system, and renaming the singleton from `GodotPayments` to `GodotPayment`, so if we *have to* break compat further, we should probably do it in 3.2.2 and have a clear migration guide for GodotPayment users.

CC @m4gr3d

**Comment by timoschwarzer** [comment]
@akien-mga I worked on it yesterday and I came pretty far. I migrated away from using a callback object to using signals to handle callbacks (which is broken on current master and 3.2, but fixed with https://github.com/godotengine/godot/pull/39029). Should I open a draft PR to discuss issues?

**Comment by akien-mga** [comment]
Sounds good yeah :)

**Comment by timoschwarzer** [comment]
https://github.com/godotengine/godot/pull/39034

**Comment by akien-mga** [comment]
Fixed by #39034 and #39050.
