### ISSUE TITLE
C# _UnhandledInput(...) Memory Leak

### ISSUE THREAD

**Issue by WizzardMaker** [godotengine/godot#30821]
**Godot version:**
3.1.1 Mono

**OS/device including version:**
Windows 10

**Issue description:**
Having a `override public void _UnhandledInput(InputEvent e) { }` leaks objects, that don't get GC'd. Unreferencing the InputEvent object with `e.Unreference();` prevents a leak.

**Steps to reproduce:**
1. Create a new project.
2. Create a class with a `_UnhandledInput(...)` override.
3. Move the mouse inside the game window.
4. Observe the "Objects" counter in the debugger.

**Minimal reproduction project:**
```
using Godot;
using System;

public class MemoryLeakTest : Node2D {
	override public void _UnhandledInput(InputEvent e) {
		//e.Unreference(); Fix?
	}
}
```

**Comment by neikeq** [comment]
Are you sure they don't get garbage collected? What happens if you add the following to that method?:

``` C#
GC.Collect(GC.MaxGeneration);
GC.WaitForPendingFinalizers();
```

**Comment by WizzardMaker** [comment]
Well, it seems they are GC'd able. Forcing GC disposes the objects, but that shouldn't be necessary.

**Comment by neikeq** [comment]
It's not necessary. They will be collected in time, but there is no guarantee when that will happen. You can always dispose it manually.

**Comment by WizzardMaker** [comment]
In time isn't really happening, one pixel movement creates an object and they aren't collected frequently. Meaning that you just have to wiggle your mouse for 30 seconds and you "leaked" ~3 MB or ~4000 objects.
The event object should rather be recycled and used multiple times IMO

**Comment by neikeq** [comment]
We can't recycle it because we don't know if something else is referencing it. The user could have kept a reference to the InputEvent somewhere. I can't think of any reason to do that, but it may happen.
Perhaps we could document that no references should be kept, and then dispose the InputEvent after the call to `_Input`/`_UnhandledInput`. This way if someone keeps a reference and tries to access it later, `ObjectDisposedException` will be thrown. We cannot recycle it though as that could cause silent bugs if a reference was kept (this applies both to the managed instance and the native one).

**Comment by WizzardMaker** [comment]
True,
can't we use a struct for the event then? That would keep the footprint a bit smaller and every use outside of the function would copy the event struct. Though, I don't know how Godot handles classes and structs internally.

**Comment by neikeq** [comment]
Initially it was a struct, but it was changed later. The change made marshalling much simpler, but I would rather have it be a struct tbh.
