### ISSUE TITLE
Reset editor camera button should be in 'Perspective mode'

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#30845]
Using current Godot master I got lost in a view-port and realized no button exists which can reset camera back to its 'initial position from when the viewport is loaded or where a new view port would start from.

**Comment by Calinou** [comment]
You can select any 3D node and press <kbd>F</kbd> to move the camera to focus it.

**Comment by RevoluPowered** [comment]
Tried that but it didn't resolve my issue because it didn't reset to the grid center or move the camera to the center of the object even when the cursor for this was in the middle.

**Comment by Anutrix** [comment]
So you essentially want:
1. Viewport to reset to center of map.
2. Button to reset Camera position.

1 seems to be missing feature(not sure), while for 2, maybe you can try reseting the position of Camera.

**Comment by RevoluPowered** [comment]
For 2 The editor camera isn't available in the godot scene tree though is it?

**Comment by Anutrix** [comment]
Don't you use a Camera node for camera?

**Comment by RevoluPowered** [comment]
I'm literally just speaking about the invisible camera that the editor viewport uses. I cannot reset it to 0,0,0 it's not in the hierarchy.

When I use WASD in the godot engine viewport sometimes if a map is large enough and you are outside the culling range you cannot get back to the grid because its out of view and no other objects are there to orient your camera.

I'm literally just suggesting we make a reset button to reset the entire viewport in the editor only.

**Comment by clayjohn** [comment]
@RevoluPowered Im not understanding how your proposal is different from "Focus Origin" found in the perspective menu. It sounds like you want a button that will reset the editor camera to 0, 0, 0 which is exactly what "Focus Origin" does.

**Comment by RevoluPowered** [comment]
I'll make a video reproduction of this to show you as if that is the case then it may clarify it up as i totally understand that it should do that, but in my case it wasn't working and i could not explain why

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
@Gusher This sounds related to https://github.com/godotengine/godot/pull/39743 which was fixed in 3.3rc.

**Comment by Gusher** [comment]
..thanks for headsup..
