### ISSUE TITLE
Add InputEvent.action to InputEvents that has InputEvent.is_action_type() == true

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#30844]
**Godot version:** 3.1.1

**OS/device including version:** Solus Gnome 4.0

**Issue description:**

Currently I couldn't find any easy way to get access to the `action` an `InputEvent` represents, I thought even that making a check for `is InputEventAction` could do the trick, but seems like we never get them from `_*_input(event)` methods as mentioned in #19987, which is sad because they are the only `InputEvent` child class that has access to actions. Currently the only way I have to find these `actions` is to do the following:

```
func get_event_action(event):
	var action_name = ""
	var actions = InputMap.get_actions()
	for action in actions:
		if InputMap.action_has_event(action, event):
			action_name = action
	return action_name
```

Which is kinda strange, given that `InputEvent` has access to many `action` oriented methods, but none that returns the `action` it represents., e.g. `InputEvent.is_action_type()`, `InputEvent.is_action("action")`, `InputEvent.get_action_strength`...

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
