### ISSUE TITLE
Vector2 slide() returns zero-vector

### ISSUE THREAD

**Issue by TrickMe** [godotengine/godot#30878]
Godot v3.1.1.stable.official

Linux Mint 19.1

Vector2a.slide(Vector2b) always returns Vector2(0, 0)

Based on the documentation, I expected the same result as:
Vector2a.project(Vector2b.tangent())

If this is not a bug, just close the issue.

Just maybe this could also be the cause for open move_and_slide() related issues.

**Comment by lawnjelly** [comment]
```
// slide returns the component of the vector along the given plane, specified by its normal vector.
Vector2 Vector2::slide(const Vector2 &p_normal) const {
#ifdef MATH_CHECKS
	ERR_FAIL_COND_V(!p_normal.is_normalized(), Vector2());
#endif
	return *this - p_normal * this->dot(p_normal);
}
```
Is Vector2b normalized? It looks like this routine will return 0,0 if it detects the parameter as not unit length. Is it printing anything to the debug log?

**Comment by lawnjelly** [comment]
Yes I can confirm on my latest master is does print

`Condition ' !p_normal.is_normalized() ' is true. returned: Vector2()`

to the Debugger Error log.

There is an argument for emphasizing that it requires a unit length normal in the docs if this is indeed the problem (and it occurs often). The docs say

> Returns the component of the vector along a plane defined by the given normal.

There are probably a few different routines that require unit length input so maybe the docs could be consistent on this, and have a phrase like 'unit length normal', if it were decided that would be a useful change. Alternatively you could go with the assumption that normal in the docs would always assume unit length, and have this somewhere in the notes.

**Comment by TrickMe** [comment]
> Is Vector2b normalized? It looks like this routine will return 0,0 if it detects the parameter as not unit length.

Vector2b was not normalized.
It works fine with a normalized Vectoir2b, with the same output as:
Vector2a.project(Vector2b.tangent().normalized())

> maybe the docs could be consistent on this, and have a phrase like 'unit length normal'

That would definitely be useful.
But, for performance reasons, I would prefer any Vector2 to be accepted by the function.

Thanks for the tip.

I'm not sure if I should close this issue now, because in the move_and_slide() function there seems to be a similar issue and I think I should keep it open until this unit-normalvector problem is properly addressed and the function(s) accept Normalvectors of any length.

**Comment by TrickMe** [comment]
Besides normalizing the Normalvector, the is_normalized()-check within the function takes time and is, in my opinion, completely unnecessary.

I presume that in the Vector3's slide(), the KinematicBody2D's and the KinematicBody's move_and_slide() and move_and_slide_with_snap() functions, the Normalvector is handled similarly.

I just hope that, when calculating the lighting on normalmaps (with shaders?), no "is_normalized()-check" is done.
That would really cause some serious performance deficits.

**Comment by lawnjelly** [comment]
> But, for performance reasons, I would prefer any Vector2 to be accepted by the function.

It is usually the other way around. A lot of vector math routines need a normalized vector as input, but normalizing is a (relatively) expensive operation, and in many cases the input will already be normalized (for instance a face normal may have been precalculated) so this will be unnecessary. It also means the function will have to deal with the error condition of the vector input being too small to normalize. So versions that assume normalized input tend to be there for performance reasons.

If there are versions that do the normalization, they tend to be there for convenience and robustness rather than efficiency (or when it is known in advance that normalization will always be required). Of course in gdscript there are other considerations like the extra instructions for the VM etc may vastly outweigh the cost of a bit of extra math, but consider the same routines may be used from c++ in the engine and perhaps be more performance critical (slide is used repeatedly within move_and_slide, for example).

This particular situation is probably fairly easy to solve if you want to use unnormalized input, just use something like:

`Vector2a.slide(Vector2b.normalized())`

I had a quick look at move_and_slide (2d). Were you referring to the floor normal? This appears to either be expected as 0, 0 (in which case it is ignored), or else it is assumed to be normalized (there doesn't appear to be any check for this as it is just used in a dot product).

In at least these two cases it seems the docs are assuming normals to be unit normals. This should probably be emphasized either repeatedly or noted as a convention within the docs (as you are absolutely right you should not have to refer to the source code to find this out). There may also be an argument for an equivalent is_normalized() check in the move_and_slide routines to make it easier to identify similar bugs.

The checks for normalization are enclosed in #ifdef MATH_CHECKS so will have no runtime cost if this is not defined, which appears to be the case when DEBUG_ENABLED is not set (perhaps in release exports).

Anyway that's just my thoughts on it, maybe one of the old timer devs will want to chime in.

**Comment by KoBeWi** [comment]
The documentation now mentions that both vectors need to be normalized, so this is resolved.
