### ISSUE TITLE
Keyword replace for all of script in the project

### ISSUE THREAD

**Issue by fish2091852127** [godotengine/godot#30953]
new feature propose:
keyword replace for all of script in the project

**Comment by Anutrix** [comment]
You mean "Replace all instances in all opened scripts" and "Replace all instances in all scripts in project".
Same can be done for search too. Notepad++ has this in it's main Search/Replace dialog box itself but Godot doesn't have enough space on Search/Replace Bar. Maybe we can add an option in tools or somewhere on/near menu bar.

**Comment by KoBeWi** [comment]
Such option already exists in 3.2-dev, but doesn't support built-in scripts. Although there's also no option to search/replace in all _opened_ scripts. Not sure if that would be useful.

**Comment by aaronfranke** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
