### ISSUE TITLE
Feature requests for troubleshooting crashes in exported projects

### ISSUE THREAD

**Issue by nightblade9** [godotengine/godot#30960]
Preamble: I just shipped my first Godot game (nine months of work). I still consider myself a Godot noob. I learned a lot about the differences between running-from-source vs. exporting, which often result in opaque crash errors at runtime.

Based on my experience (still troubleshooting unresolved crashes), I would like to suggest two feature requests:

1) **Console logs.** The output of the Godot console (which appears only in debug exports) is extremely invaluable to finding/fixing issues. Without it, you just have a stack dump. Can you please add a way to get these from exports?

Perhaps exported games could automatically redirect the log to a temporary file on-disk, so at least if someone complains about  a crash, you have some data. Optionally, you can delete or keep the file between runs.

2) **One-click run-as-export.** Right now, I work alone (no QA team/process/etc.) so I don't ever export/run my app, because it takes long (set up the export profile, export, wait, launch game). Ideally, the editor could include a single push-button "export and run" option to make this frictionless.

This could be optimized - eg. always run the first configured export, or (like Visual Studio) show a list of available profiles, or always run an export that's fast and gives good error information (HTML5?)

For beginners, this would make it much easier to prevent crashes even before they're committed.

**Comment by YeldhamDev** [comment]
You can enable file logging by going in **Project Settings -> Logging -> File Logging** and enabling it.

**Comment by Calinou** [comment]
2. is similar (but not identical) to https://github.com/godotengine/godot/issues/5257.

**Comment by nightblade9** [comment]
> You can enable file logging by going in **Project Settings -> Logging -> File Logging** and enabling it.

Does this make logs when you export your game, too? If so, this is awesome.

I would then amend my request: this should be turned on by default. I would guess many of us don't know about this and would benefit from it being on by default.

**Comment by Calinou** [comment]
I'm not sure about enabling it by default. This could cause user data directories to become huge when error messages are spammed, which may happen during project development.

**Comment by nightblade9** [comment]
> This could cause user data directories to become huge when error messages are spammed, which may happen during project development.

This can be easily mitigated by truncating the log file when you launch your game.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
