### ISSUE TITLE
Ability to default saving scripts to a custom defined folder

### ISSUE THREAD

**Issue by elieobeid7** [godotengine/godot#30975]
Every time I try to save a file Godot wants me to save it in `/scenes`, users  on reddit say that's because according to the official best practices its best to save scripts to the scenes folder.

I didn't know that when I started and too late now for a change, plus you do stuff that you are comfortable doing, it would be nice if the editor don't force me into saving scripts in scenes folder.

**Comment by akien-mga** [comment]
Godot doesn't want to save your scripts in `/scenes` specifically, that's just a consequence of where you place your scenes. Scripts are saved by default next to their scene file, and the recommended outline is not everything in a `scenes/` folder but to use folders for semantic groups (e.g. `player`, `enemies`, `props`, etc.).

So what you're asking for is for a way to configure the project so that all scripts are saved in a specific folder by default instead of next to their corresponding scene.

Then the question is how far should it go? If we add such an option for scripts, there should likely be an option for scenes to also be saved by default in a custom-named folder. And likely also for non-resource resources... which sounds to me like a lot of options in favor of a file type-based repo structure. But why not, if there's more users interested in it.

**Comment by elieobeid7** [comment]
My request is very simple, no configuration nothing, just do what google chrome or any other program really but lets take the example of chrome:

You try to save a file in chrome, it asks you to download to the downloads folder, you tell chrome no, I want to place the file on Desktop

You try to download another file, it goes to the desktop not to the downloads folder.

I hope that makes my question clearer and easier to implement.

**Comment by KoBeWi** [comment]
Closing in favor of the proposal: https://github.com/godotengine/godot-proposals/issues/576
