### ISSUE TITLE
Parallax backgrounds are offset but not rotated when the Camera2D is rotated

### ISSUE THREAD

**Issue by m93a** [godotengine/godot#30988]
**Godot version:** 3.1.1 (and 3.2 ad @fossegutten)
**OS/device including version:** Ubuntu 19.04

**Issue description:**
Parallax background ignores the rotation of the camera. Instead all the layers should rotate with the rotation center being in the middle of the screen. (All layers with the same speed, disregarding the motion scaling.)

**Comment by fossegutten** [comment]
This seems to be a bug. The parallax backgrounds actually offset up and down, when camera2d is rotated. This is magnified the further away camera2d moves from zero position.
Gif and reproduction project is in my duplicate issue #35782

**Comment by juse4pro** [comment]
This is currently also blocking my camera shake task. Is there any idea to work-around this problem until it get's fixed?

**Comment by fossegutten** [comment]
@juse4pro code your own parallax script to attach to Node2D. offset it by camera position * 0.9 for example.
You can also use the follow_viewport on CanvasLayer nodes instead. Not exactly the same, but it works with rotations

**Comment by juse4pro** [comment]
@fossegutten Unfortunately then I would also have to re-implement the mirror feature because this is the reason why I am using a parallax layer. :)

**Comment by juse4pro** [comment]
@fossegutten Could you upload your already provided project + the video and reproduction steps here to this bug issue is going to be processed again and may get confirmed? 
Just asking because your issue has been archieved (what all duplicates even when I would create one) but this bug is very annoying. :D

**Comment by netAction** [comment]
This is still an issue in Godot 3.5.

**Comment by pinguinosod** [comment]
Still happening on 4.1.1

**Comment by AThousandShips** [comment]
And on 4.1.3? 4.1.1 is not supported

**Comment by hunterloftis** [comment]
This is still an issue in Godot v4.2.rc1.

**Comment by markdibarry** [comment]
Playing with the source code a bit, if you get the screen rotation from the transform in the `_camera_moved` method in `parallax_background.cpp`, you can pass in the screen rotation in `parallax_layer.cpp`'s `set_base_offset_and_scale` method, and it gets you most of the way there, with the layer rotating correctly with the camera. Here it is set at 90 degrees:

![image](https://github.com/godotengine/godot/assets/21325943/473250f4-2171-4988-b03c-cc6f1da8400d)
![image](https://github.com/godotengine/godot/assets/21325943/e56fa71b-cec0-4e2f-b0f9-c845aa91e6c5)

The issue is when you set the motion scale on the `ParallaxLayer` to anything else, it doesn't take rotation into consideration. For example, if you were to set the camera rotation to 90 degrees, and change the `ParallaxLayer`'s `x` motion scale, it'll offset the layer vertically in the viewport rather than horizontally.

![image](https://github.com/godotengine/godot/assets/21325943/10480767-5878-48cb-add8-0bfa9b33a6fc)

I may spend some more time on this, but I'm not sure if it's outside my abilities or it's an easy fix. If someone more familiar with the code base had any insight, I'd love to listen.

**Comment by markdibarry** [comment]
Some more info: Was down the wrong lane with the last fix. What we want is for not the `ParallaxLayer`s to adhere to the `Camera2D`'s rotation, but for the `ParallaxBackground` itself to do so. However, the rotation of the `Camera2D` is centered (most of the time), and `ParallaxBackground` is not. Somehow we'd need the `ParallaxBackground` to be offset to the `Camera2D`'s center, rotated, then offset back. The thing is I'm not sure if the renderer allows for that order.

This also just makes me question again why `ParallaxBackground` needs to be a `CanvasLayer` at all since we're working so hard to make it not behave like one.

**Comment by markdibarry** [comment]
I've thought it over a bit, and I think it's not worth fixing `ParallaxBackground` and `ParallaxLayer` when it's far easier to make a much better node in a few lines of code. I think even if it were fixed, `ParallaxBackground` is inherantly flawed by inheriting from `CanvasLayer`, requiring a second different workflow from the rest of your background, and a lot of workarounds just to make it work with everything else. It also requires a tight coupling and strict node hierarchy to work, making it difficult to adjust things together. `ParallaxBackground` might have just been made early on before we had better ways to do these things.

Anyway I whipped this up super quick and it works with zoom, rotation, etc, and doesn't require a hierarchy. You just add an image, set the scroll speed and you're done.

```cs
[Tool, GlobalClass]
public partial class ParallaxSprite2D : Sprite2D
{
    public ParallaxSprite2D()
    {
        TextureRepeat = TextureRepeatEnum.Enabled;
        RegionEnabled = true;
    }

    [Export]
    public Vector2 ScrollSpeed { get; set; }
    private Vector2 _textureSize;

    public override void _Ready()
    {
        TextureChanged += OnTextureChanged;
        _textureSize = Texture?.GetSize() ?? new();
    }

    public override void _PhysicsProcess(double delta)
    {
        FollowCamera();
    }

    private void FollowCamera()
    {
        if (Engine.IsEditorHint())
            return;

        Viewport viewport = GetViewport();
        Camera2D camera = viewport.GetCamera2D();
        Vector2 position = camera.GetScreenCenterPosition();

        if (camera.AnchorMode == Camera2D.AnchorModeEnum.DragCenter)
        {
            position -= viewport.GetVisibleRect().Size * 0.5f;
        }

        Offset = position / Scale;

        Vector2 scroll = (position * ScrollSpeed / Scale % _textureSize).Round();
        RegionRect = new(scroll, RegionRect.Size);
    }

    private void OnTextureChanged()
    {
        _textureSize = Texture.GetSize();
        RegionRect = new(RegionRect.Position, _textureSize);
    }
}
```


https://github.com/godotengine/godot/assets/21325943/cff1d924-5631-4e98-b4d7-8d8dfb89831a


https://github.com/godotengine/godot/assets/21325943/b817495c-0048-4cf1-8128-5dc6e96b2ae7

**Comment by tartley** [comment]
This sounds amazing but I'm just slightly out of my depth trying to make this work with drawn geometry instead of textures. If anyone has hints, I'd love to hear it.
