### ISSUE TITLE
Equivalent to OptionButton for checkboxes

### ISSUE THREAD

**Issue by NilsIrl** [godotengine/godot#31012]
**Godot version:**
Godot 3.2-dev master 2019-08-01 (3a6102a6f716904bb158819146e3fed7590b8106)

**Issue description:**

The OptionButton (a.k.a. drop down menu) uses radio buttons

It would be nice if we could have a class derived from OptionButton (or the other way round) that supports checkboxes.

This problem was encountered when improving the filter for the `GDNativeLibrary` dock #30923.

In this PR a MenuButton was used but isn't ideal as the operations had to be done manually.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
