### ISSUE TITLE
Make rand_from_seed and hash available in custom shaders

### ISSUE THREAD

**Issue by m93a** [godotengine/godot#31051]
**Godot version:** 3.1

**Issue description:**
When writing custom particle shaders, developers usually need some kind of random number generator. Because none is present in the Godot shader API, the easiest way is to look into [`particles_material.cpp`](https://github.com/godotengine/godot/blob/7d413f075c2e2747fa30a42de53ae7273c4bf594/scene/resources/particles_material.cpp#L247) and copy `rand_from_seed` from there (`hash` may be also useful for seed generation). Wouldn't it be much more comfortable to add these functions to the shader API and automatically include their declaration in the shader once they are used?

**Comment by clayjohn** [comment]
To get them, just create a new ParticlesMaterial. Then click the dropdown next to the material and select "Convert to ShaderMaterial". That will create a shader with all the functions from the default particles material.

**Comment by m93a** [comment]
While that's true, I don't need all the functions. I just need random numbers, which could easily be included in a "standard library".

**Comment by clayjohn** [comment]
The issue with a "standard library" approach is that it increases the compile time of all shaders. Since shaders are compiled at run time, it would increase the length of the already noticeable hiccups that occur when a new object enters into view. The current approach is to minimize the code that Godot adds behind the scenes in order to keep compile times down. 

That being said, maybe someone could create a standard library system similar to https://github.com/godotengine/godot/pull/31263 That way users could define functions they want in all shaders on a per-project basis and it would not add bloat to the engine.

**Comment by bojidar-bg** [comment]
Would it be possible to detect which "standard library" functions are used by a shader, and include only those functions?

**Comment by clayjohn** [comment]
Yea. That's entirely possible. IMO what your describing is the best approach. It's kind of done in GLES2 already in stdlib.glsl. But it would still add overhead to Godot's shader preprocessor step. 

However, if you limit it to functions defined in a shader library, then it may not add much overhead. There is also the recently implemented visual shader plugin. We could implement a similar shader plugin system.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
