### ISSUE TITLE
Warn when using / instead of res:// while loading stuff

### ISSUE THREAD

**Issue by CombustibleLemonade** [godotengine/godot#3106]
The above situation will lead to behavior that's different between the version launched by the editor and the version that is exported by the editor.

**Comment by kubecz3k** [comment]
I'm really unsure about adding a warning when using  "/" instead of "res://". 
Using "/"  is a normal thing when you want to refer to files with absolute paths on user hard drive. 
Don't see a reason why the warning should be displayed in this case... unless from what you write "/" is pointing to different folders depending on if the game is launched from editor or as standalone...  
Personally I didn't observed this, but if that is the case then it's a bug, and it should be fixed.  
Did I understand this issue correctly @CombustibleLemonade ?

**Comment by CombustibleLemonade** [comment]
I just created a small test-project to demonstrate said behaviour. When using 
- load("/script.gd")
it will load said script when run from the editor, and throw an error when not run from the editor.

Here's the test-project, if you want to mess around with it:
https://www.dropbox.com/s/g0obyypnb09phsh/test.zip?dl=0

I have run this on KXstudio, a variant of ubuntu. It seems to happen in the latest version of godot, though the test project was only tested on the november 3rd build on http://fixnum.org/godot/#latest_complete

**Comment by chanon** [comment]
Related, but not exactly the same thing, bug I found while figuring something out:
http://godotengine.org/qa/2913/how-can-i-get-the-script-type-of-a-node?show=2914#a2914

**Comment by akien-mga** [comment]
@Faless Fixed by #6702?

**Comment by Faless** [comment]
> @Faless Fixed by #6702?

@akien-mga  Yes, it actually throws an error instead of just a warning, so users don't get confused. You can close this and also close #4280
