### ISSUE TITLE
OmniLight contact shadows create weird artifacts

### ISSUE THREAD

**Issue by MartinHaeusler** [godotengine/godot#31084]
**Godot version:**
3.1.1.stable.mono.official

**OS/device including version:**
Windows 10, 64 bit, GLES3 on Nvidia GeForce 980ti

**Issue description:**
- I added a cube to my scene and gave it a spatial material.
- I added an omni-light close to the floor, not touching it though (light config see below).
- I set the "Contact" property to a value greater than zero.

This produces really weird triangular shadow artifacts around the light:

<img width="584" alt="omnilight" src="https://user-images.githubusercontent.com/16356998/62428027-596f7000-b6fc-11e9-8126-cee51a741666.PNG">

... and those lights also **move** when the camera moves:

![omniLight](https://user-images.githubusercontent.com/16356998/62428031-6ee49a00-b6fc-11e9-9e93-0cd25def7739.gif)

This looks really strange, and I think that this is a bug. In a static scene, shadows should look the same regardless of the viewer's angle. This is clearly not the case here. In fact, I'm even wondering where those triangular shadow artifacts come from in the first place.

**Minimal reproduction project:**
https://gofile.io/?c=sLdWKp

**Light setup**
<img width="177" alt="omniLightConfig" src="https://user-images.githubusercontent.com/16356998/62428203-3d210280-b6ff-11e9-86ca-34050a99400f.png">

**Comment by clayjohn** [comment]
I'm guessing it's because your ``bias`` value is larger than your ``contact`` value. Try fiddling with the two. Alternatively, it may be because your bias is larger than the distance between the light and the floor.

**Comment by MartinHaeusler** [comment]
@clayjohn I'm not even a 100% sure what the "bias" property really means. I'm coming from Unity, I can't recall a similar property there... Maybe I mis-interpreted the "contact" property too? I thought it means "enable contact shadows". I just had a look at the manual:

https://docs.godotengine.org/en/3.0/tutorials/3d/lights_and_shadows.html?highlight=bias

Apparently the two parameters don't do what I thought they did. I tried your advice and played around with the bias and contact values, but no matter how high or low I set the bias, I always get artifacts when contact is greater than zero. I'm still a bit puzzled by those parameters because to my knowledge no configuration like that is needed in Unity. I may be wrong about that though.

**Comment by Calinou** [comment]
Try setting **Contact** to 0; It usually looks too broken to be usable in my experience.

**Comment by clayjohn** [comment]
If you really need ``Contact`` you can also set your floor to not cast shadows. 

An explanation about ``bias`` and ``contact`` will probably clear things up. 

**Bias**
Bias is used to avoid a common shadow artifact where objects cast shadows onto themselves. It offsets the position the shadow uses to look up the depth texture in order to do so. However, this often results in a gap between where the object "contacts" the ground and where the shadow begins.

**Contact**
Contact tries to reduce that gap by performing a screen-space raycast (which is why the artifact in your example moved with the camera). The only purpose of Contact is to reduce the gap that appears, if you are not having trouble with a gap created from bias, then there is no point using Contact as it is very slow. 

In your scene, because the light is so close to the floor, Contact is eliminating the benefit of Bias and it is creating a self shadowing artifact. 

As Calinou pointed out above, you likely shouldn't be using Contact in this situation. There are better ways to solve the bias issue, like increasing the size of the shadow buffer, or disabling the cast_shadows property of the floor.

**Comment by MartinHaeusler** [comment]
Thanks for the explanations. I had the impression (from the name of the `Contact` property) that it has something to do with contact shadows i.e. ambient occlusion. So I cranked it up a little to see what it does, and much later on during scene creation I realized that the shadows were behaving in awkward ways. Took me a while to single out the cause.

So the way I understand it now is that `bias` and `contact` exist to fix scene-specific issues with shadow mappings, right? So the general way to use them is:

- if the shadows look good, don't touch neither `bias` nor `contact`
- if the shadows look off, try increasing the shadow map resolution first.
- if that doesn't help, play with `bias` and `contact`

Does that about sum it up?

**Comment by clayjohn** [comment]
@MartinHaeusler More or less. 

Specifically if you see self shadowing like this, increase bias
https://docs.godotengine.org/en/3.0/_images/shadow_bias.png

And if you get a gap, try increasing shadow map resolution, then try contact shadows
https://docs.godotengine.org/en/3.0/_images/shadow_bias.png

**Comment by MartinHaeusler** [comment]
Thanks, got it!

**Comment by Calinou** [comment]
I'll close this, as contact shadows are no longer available in the `master` branch (they were replaced by shadow pancaking, which does a similar job better).
