### ISSUE TITLE
Add a setting that makes polygon vertices snap to pixels by default

### ISSUE THREAD

**Issue by mitchcurtis** [godotengine/godot#31080]
I have to enable "Use Pixel Snap" each time I create a polygon (for e.g. a LightOccluder2D). It would be nice if there was a setting I could enable that made it default to true.

**Comment by Calinou** [comment]
We could query the project's **Rendering > Quality > 2d > Use Pixel Snap** setting and enable it automatically based on its value.

**Comment by TheDuriel** [comment]
To be honest. Absolutely _everything_ should snap to integers in the 2D editor, by default. You very rarely want to set sub pixel values.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
