### ISSUE TITLE
Using scrollwheel in HTML5 build causes error

### ISSUE THREAD

**Issue by ChronoDK** [godotengine/godot#31095]
**Godot version:**
3.1.1

**Issue description:**
When using the scrollwheel in an HTML5 build the console is spammed with this:

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
wheelHandlerFunc @ index.js:7
jsEventHandler @ index.js:7

**Comment by akien-mga** [comment]
What OS, browser and browser version?

**Comment by ChronoDK** [comment]
> What OS, browser and browser version?

Oh, sorry - I'm using Google Chrome 75 and Windows 10.

**Comment by Shilo** [comment]
Same issue here.

The errors show when scroll the mouse wheel:
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
wheelHandlerFunc @ index.js:7
jsEventHandler @ index.js:7`

Using latest Windows: Windows 10
Using latest Godot version: Godot Engine v3.1.2.stable.official
Using latest Google Chrome: Version 79.0.3945.88 (Official Build) (64-bit)
OpenGL ES 2.0 Renderer: GeForce RTX 2070/PCIe/SSE2

**Comment by Schroedi** [comment]
https://github.com/godotengine/godot/pull/37414 should fix this.
