### ISSUE TITLE
Asset download error: sha256 empty

### ISSUE THREAD

**Issue by nleehone** [godotengine/godot#31115]
**Godot version:**
Godot Engine v3.2.dev.custom_build.7126654ea
CORE API HASH: 2864405972004617357
EDITOR API HASH: -4062612966191217613

**OS/device including version:**
Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Issue description:**
When trying to download an asset from the AssetLib the download fails with the following error:
![Screenshot_2019-08-05_11-11-50](https://user-images.githubusercontent.com/12677513/62485566-e274be80-b771-11e9-845e-5989ed430506.png)

The "Got" sha256 string is empty.

**Steps to reproduce:**
- Create a new project
- Click AssetLib tab
- Select **any** asset and click download
- Fails with same error message each time, but different "Expected" hashes for different assets of course

**Comment by bojidar-bg** [comment]
The only way this can happen is when `FileAccess::get_sha256` returns `""`:
https://github.com/godotengine/godot/blob/52cfb5f5799af38e4aa543417a76999b732c3a54/editor/plugins/asset_library_editor_plugin.cpp#L368-L373

Inspecting that function, it seems that this happens only when `FileAccess::open` return `NULL`:
https://github.com/godotengine/godot/blob/52cfb5f5799af38e4aa543417a76999b732c3a54/core/os/file_access.cpp#L694-L696

Checking there, it seems that `FileAccess:_open` (per-OS function) has to return an error:
https://github.com/godotengine/godot/blob/e9d624d7ce1d56cf134599a62deea1f5a0848019/core/os/file_access.cpp#L113-L117

Finally, looking at the [unix version of `_open`](https://github.com/godotengine/godot/blob/e9d624d7ce1d56cf134599a62deea1f5a0848019/drivers/unix/file_access_unix.cpp#L67), one can see that there are a few cases in which this might happen:
* The file is nonexistent, or is a directory.
  * This might occur if the download link did not actually return a response body. Unlikely.
  * It could also occur that `HTTPRequest` returns `RESULT_DOWNLOAD_FILE_CANT_OPEN` instead of `RESULT_SUCCESS` due to not being able to open the file. Make sure that the editor cache directory is writeable.
* `fopen` fails, likely due to wrong permissions. Unlikely, since the file should have just been written by the `HTTPRequest`.

**Comment by nleehone** [comment]
> It could also occur that HTTPRequest returns RESULT_DOWNLOAD_FILE_CANT_OPEN instead of RESULT_SUCCESS due to not being able to open the file. Make sure that the editor cache directory is writeable.

This was indeed the source of the problem. For some reason the cache directory was owned by root instead of the user running godot.

Solution was to run

`sudo chown -R <username>:<username> ~/.cache/godot`

Is there any documentation regarding where the cache files and other important system files are on a Linux system? Only found the cache directory by digging around through another issue report: https://github.com/godotengine/godot/issues/13064

**Comment by Calinou** [comment]
> Is there any documentation regarding where the cache files and other important system files are on a Linux system?

On Linux, Godot follows the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). By default:

- user data (export templates, project-specific data, …) is in `$HOME/.local/share/godot/`,
- settings are in `$HOME/.config/godot/`,
- cache is in `$HOME/.cache/godot/`.

**Comment by nleehone** [comment]
That makes sense.

Is this something that should be added to the documentation?

I'd be happy to help out in this, but would need a bit of guidance as to how to go about submitting updates to the documentation.

**Comment by Calinou** [comment]
@nleehone I just opened https://github.com/godotengine/godot-docs/pull/2689 to this effect :smiley:

**Comment by bojidar-bg** [comment]
Note: Even if documented, please do not close this. `RESULT_DOWNLOAD_FILE_CANT_OPEN` has to show a different error message in the asset library.

**Comment by isral** [comment]
Hi, I get this error when downloading templates.
Windows 10.
Godot 3.1.2 and Godot 3.2.

**Comment by Calinou** [comment]
@isral Which template did you try to download?

**Comment by isral** [comment]
@Calinou 
Platformer 2D by CesarLeon

**Comment by bojidar-bg** [comment]
@Calinou we could do it in the new / Laravel backend, indeed.

**Comment by Calinou** [comment]
@bojidar-bg I already removed the hash support there, it's always sending empty hashes now.

**Comment by cptSwing** [comment]
I get this error when attempting to download the 3D Material Testers demo (Win10 as well, newest Godot)

**Comment by Rubakai** [comment]
Get this error when downloading all light demos

**Comment by Maujoe** [comment]
It's seems like many assets have this checksum problem. I couldn't download the half of the assets listed on the first page. For example

- Visual Shader Node Library
- Destruction
- JoystickControl
- Inkgd 
- Heightmap terrain
- ...

Just to name some of them..

**Comment by 2shady4u** [comment]
Same here 😢 
Almost none of the assets can be downloaded without getting a hash error

**Comment by Calinou** [comment]
@bojidar-bg Please remove the hash verification system already. It's clearly causing too much trouble at this point...

I can open a PR if you don't want to do it right now.

**Comment by bojidar-bg** [comment]
@Calinou Alright, let's remove hash checks from the asset library -- feel free to open a PR there, I suppose.
Removing checks from the editor is not necessary, I think, especially considering that when other asset libraries come around, they might want to use them.

**Comment by eduardonunesp** [comment]
Just downloaded with success the asses:

- Visual Shader Node Library
- Destruction
- Joystick Control
- Inkgd
- Heightmap terrain

Branch 3.2

**Comment by Calinou** [comment]
Hash checks were removed from the asset library with https://github.com/godotengine/godot-asset-library/pull/209, which solves this issue. Closing.

**Comment by bradzoob** [comment]
Can somebody please include that in the publicly readable docs and json references? 

I've walked three repos tonight to figure out why my sha256 won't work., after checking the cpp source i could see nothing too weird being done so it should match the other 3 methods if have for file hashing. But turns out that setting the hash in the json response from a web server just ensures it breaks lol.

https://github.com/godotengine/godot-asset-library/blob/master/API.md#get-assetid
