### ISSUE TITLE
Current camera 3D vs 2D

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#31153]
**Godot version:**
3.1.1

**Issue description:**
Sooo, both 2D and 3D camera have a `current` property that makes the viewport display them.
However, when you don't have a current camera in 3D, Godot will automatically select the first one in the SceneTree. In 2D this is not the case and you have to remember to enable the `current` property. Could 2D cameras work the same as in 3D?

**Comment by CowThing** [comment]
I think the reason for this is that a 3D scene requires a 3D camera to render it. But a 2D scene does not need a 2D camera to render it. You can make a 2D game with no camera, and have your own custom canvas manipulation. I think forcing a 2D camera to be active if one exists in the tree is not a good idea, because that wont always be desired for every game.

**Comment by KoBeWi** [comment]
From my experience, whenever I create a Camera2D, I always want it to be current. Dunno, could be an editor-only thing, like enabling the `current` property for first Camera2D created in the scene.

**Comment by sparkart** [comment]
I feel like forcing a 2D camera if one exists is better because a 2D camera is basically a high-level concept for canvas manipulation. If you want custom canvas manipulation you could just remove the camera. It should work the same way for consistency as custom canvas manipulation seems more like an outlier.

**Comment by KoBeWi** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3253
