### ISSUE TITLE
Lens flare post shader

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#31167]
**Godot version:**
3.1

**OS/device including version:**
linux 4.9

**Issue description:**
Ive tried adding a lens flare shader, but found a limit that I cannot upload a modified texture to the shader for use later in the shader. I was trying to implement the following:
https://john-chapman-graphics.blogspot.com/2013/02/pseudo-lens-flare.html

It would be nice to have something like this build in, and allow the users to specify their own textures. I remember using a similar built in effect in Unreal Engine and found it can add a lot to the game if done right.

This might be something that would be good for the 4.0 Vulkan release?
Also it would be nice to split the post effects from the world environment node and have that as its own node.

**Steps to reproduce:**
n/a

**Minimal reproduction project:**
n/a

**Comment by clayjohn** [comment]
> I cannot upload a modified texture to the shader for use later in the shader

What do you mean modified texture for the shader? It sounds like you might be using ``SCREEN_TEXTURE`` instead of using a Viewport. The effect described in the article should be fully doable in Godot currently.

**Comment by CptPotato** [comment]
> It sounds like you might be using `SCREEN_TEXTURE` instead of using a Viewport. The effect described in the article should be fully doable in Godot currently.

I agree. Although, to access the **unclipped** HDR data of the viewport there's still a fix required (#30574).

**Comment by Zylann** [comment]
I've used an asset already which does this: https://godotengine.org/asset-library/asset/198

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
