### ISSUE TITLE
No depth test on SpatialMaterial not working like before?

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#31164]
**Godot version:**
fa35a73f0

**OS/device including version:**
GNU/Linux x64

**Issue description:**
I had this setup to show an object behind walls in 3.1
![Screenshot](https://user-images.githubusercontent.com/18746022/62579943-1388e800-b873-11e9-8668-36dcdabc664c.png)

but now it looks like this
![Screenshot-1](https://user-images.githubusercontent.com/18746022/62580013-3ddaa580-b873-11e9-8b4c-0d5725dd51bd.png)

is this intentional?

MRP:
[ShowObjectBehindWalls.zip](https://github.com/godotengine/godot/files/3474389/ShowObjectBehindWalls.zip)

**Comment by clayjohn** [comment]
Can you upload an MRP?

**Comment by MightyPrinny** [comment]
@clayjohn MRP uploaded, though everything was in the first screenshot.

**Comment by clayjohn** [comment]
Thanks. MRPs are always helpful because users often don't realize that they have particular settings set that impact the bug. 

Technically this isn't a bug it is expected behaviour. Originally (and in 3.1.1) objects with "No Depth Test" would be drawn as part of the opaque pass. However, the sky is drawn after the opaque pass for performance reasons. So if any object with "No Depth Test" was drawn within nothing between it and the sky, it would disappear behind the sky ([this bug](https://github.com/godotengine/godot/issues/29108)). Further, you had to carefully tweak ``render_priority`` in order for it to appear in front of other stuff. 

Accordingly, "No Depth Test" objects need to be a part of the alpha pass so they could be properly sorted before being drawn. I implemented that behaviour in https://github.com/godotengine/godot/pull/29132. 

This way "No Depth Test" objects are always drawn appropriately. But the drawback is they are not mixed into the opaque pass, they are always drawn after opaque objects in the alpha pass. In order to fix this, you need to set your base object to be mixed into the transparent pass as will with the "Transparent" flag.

**Comment by MightyPrinny** [comment]
@clayjohn  Thank you very much for the detailed answer, turning on the transparent flag on both materials and changing the first one's depth draw mode to opaque prepass or always fixed my problem.
