### ISSUE TITLE
Can't generate Visual Studio project from SCons

### ISSUE THREAD

**Issue by ex** [godotengine/godot#3117]
I'm trying to generate the Visual Studio project with:
````
scons vsproj=yes platform=windows
````
using the VS command prompt as found here: http://stackoverflow.com/questions/21476588/where-is-developer-command-prompt-for-vs2013, but it fails with:
````
C:\godot>scons vsproj=yes platform=windows
scons: Reading SConscript files ...
internal error
Traceback (most recent call last):
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Script\Main.p
y", line 1372, in main
    _exec_main(parser, values)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Script\Main.p
y", line 1335, in _exec_main
    _main(parser)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Script\Main.p
y", line 1002, in _main
    SCons.Script._SConscript._SConscript(fs, script)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Script\SConsc
ript.py", line 260, in _SConscript
    exec _file_ in call_stack[-1].globals
  File "C:\godot\SConstruct", line 399, in <module>
    variant = variants)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Environment.p
y", line 260, in __call__
    return MethodWrapper.__call__(self, target, source, *args, **kw)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Environment.p
y", line 224, in __call__
    return self.method(*nargs, **kwargs)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Builder.py",
line 633, in __call__
    return self._execute(env, target, source, OverrideWarner(kw), ekw)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Builder.py",
line 554, in _execute
    tlist, slist = self._create_nodes(env, target, source)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Builder.py",
line 518, in _create_nodes
    target, source = self.emitter(target=tlist, source=slist, env=env)
  File "C:\Python27\Scripts\..\Lib\site-packages\scons-2.3.4\SCons\Tool\msvs.py"
, line 1642, in projectEmitter
    raise SCons.Errors.InternalError(s + " must be a string or a list of strings
")
InternalError: srcs must be a string or a list of strings
````
I can build fine.

**Comment by reduz** [comment]
I don't have the slightest clue, I haven't made msvc support, so I'm not going to fix it :P

**Comment by reduz** [comment]
Volunteers appreciated!

**Comment by RebelliousX** [comment]
![screenshot 2016-01-11 04 20 15](https://cloud.githubusercontent.com/assets/1888186/12231102/b1cbd7d2-b81a-11e5-820c-13377513741e.png)

Working here, just make sure you are running VS[~year~] x64 x86 Cross Tools command prompt when running:
`scons vsproj=yes platform=windows`

Win32 build fine, but x64 fails about a redefinition of:
```
#ifdef _WIN64
    typedef unsigned __int64 size_t;
    typedef __int64          ptrdiff_t;
    typedef __int64          intptr_t;
#else
```
Complaining about `ptrdiff_t` being redefined in `vcruntime.h`

**Comment by RebelliousX** [comment]
But one thing that bothers me is that header files of Godot are scattered everywhere, which means
VS can't find them but `Scons` will build fine. For example `main.cpp` is inside `Godot/main/`
Inside `main.cpp` where it tries to `#include "core/register_core_types.h"` for example, VS IDE fails
to detect the file if it exists with red squiggles underlines, causing debugging to go nuts. The reason
for this is that `core/register_core_types.h` is located one directory above of `main`. So the include
directive must have been `#include "../core/register_core_types.h"` instead.

My suggestion would be, to put all header files in their own directories, separated from source files.
Which will make it easier for VS IDE to find them all in one place or a set of directories at least.

I am not sure if I should open an issue for this or not, since it will require a lot of modifications to 
SConstruct I believe.

XCode doesn't have problems with searching directories recursively, and I think linux too but I am not
sure. It only affects VS. But Godot is not designed to be code-able in Windows platform. I don't think
the devs will change this, since they are adamant about SCons.

**Comment by akien-mga** [comment]
Well moving the headers would be a hacky workaround. Any buildsystem should be able to locate headers provided you pass it the good paths to the folders that contain those headers.

You probably just need to find a way to tell VS that "." is an include directory. With gcc it would be ```-I.```.

**Comment by reduz** [comment]
Indeed, just make sure you have the right include paths.

**Comment by RebelliousX** [comment]
@akien-mga No such option in VS I am aware of, I already tried to include the the obvious `$(ProjectDir)` in VS additional include directories, but VS needs all directories specified individually.

That is, VS is trying to look for header files locations **relative** to **current** location of the file being parsed by the prerprocessor, not the base directory every time.

So unfortunately, your suggestion didn't work for me.

**Comment by ex** [comment]
For the interested, I created manually a VS project is in the pull: https://github.com/godotengine/godot/pull/3247:

**Comment by RebelliousX** [comment]
Hey @ex since you already have VS project and a PR for that, you might want to close this issue.
For me to be honest, I just gave up on SCons, the incremental builds are ridiculous! GOD bless the devs for living with that. It is so slow, using SCons with IDE such as VS is no better than using notepad with command prompt to build.

Sorry for my rants.
