### ISSUE TITLE
Windows compile error (drivers/libdrivers)

### ISSUE THREAD

**Issue by Kermer** [godotengine/godot#3122]
(win7 x64, MinGW w64)
When trying to compile latest source I get errors like this:
```
drivers\libdrivers.windows.opt.tools.32.a(pem_lib.windows.opt.tools.32.o):pem_lib.c:(.text+0x18c7): undefined reference to `BUF_MEM_grow'
drivers\libdrivers.windows.opt.tools.32.a(bands.windows.opt.tools.32.o):bands.c:(.text+0x18f4): undefined reference to `renormalise_vector'
```
More errors: http://pastebin.com/t49bhY5s

I tried to find commit which makes this problem, so I started to compile different versions. So far:
Not working: [2478c](https://github.com/godotengine/godot/tree/534c8e74b9e4990ac1f63ef701330552cecfc28f)
Working: [2418c](https://github.com/godotengine/godot/tree/a028840ea5cfc6ac4e80d99c4850ae3f10eeb353)

So my guess is [this commit](https://github.com/godotengine/godot/commit/0f57bbb8e97b3eba84e5453a5d1948d699a67515), but can't verify this atm., maybe tomorrow

**Comment by Kermer** [comment]
Yup, that's the commit.
Using splitted libdrivers again (in `drivers/SCsub` changing `if (False)` to `if(True)`) fixes those errors and allows me to compile latest source.

**Comment by vnen** [comment]
The libdrivers split was made because long command lines don't work in some Windows prompts (the last arguments are ignored or something like that). Maybe Windows 10 has no such restriction or it's very long, but previous versions might still have this problem. More on the subject can be seen on #3001.

We need an elegant solution to this problem that does not rely on splitting libdrivers, as this might be a problem in some cases, specially if one cherry-pick the drivers to actually compile.

**Comment by vnen** [comment]
@punto- and @reduz might have some idea about this?

**Comment by reduz** [comment]
I am clueless, there is code in detect.py for windows that supposedly works around long commandlines, but it does not seem to be working?

**Comment by Kermer** [comment]
Didn't work on win7 x64, MinGW w64 at least.

**Comment by reduz** [comment]
this should be fixed now by latest commits
