### ISSUE TITLE
Pls add wizards to automate creation of common tasks.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#31236]
Hi, I think godot should have some kind of wizard tool to automate the creation of new scenes, like a wizard to automate a basic set up of an rpg, or a platformer or an FPS.
Basically a wizard that has parameters to configure a template if you want to make a generic game in a genre.

I think this will speed up the development for some users, since they wont have to remake every time the same scenes over and over again.

Maybe this way, there could be a list of presets, like JRPG 4 direction character or 8 direction characters, or FPS character, where the wizard has a basic configuration set up to generate a newer scene.

You could even make your own template wizards and share them with others, maybe use the asset store to download templates made by the comunity.

**Comment by mrcdk** [comment]
People can already upload templates to the asset library if they want. Godot is a generic game engine so a wizard to configure 3 or 4 genres makes little sense.

**Comment by ca3games** [comment]
> People can already upload templates to the asset library if they want. Godot is a generic game engine so a wizard to configure 3 or 4 genres makes little sense.

Yeah, but it becomes tiresome to remake over and over again in a newer project the same type of scenes I need, like an 8 directional character.
It would be nice to have a way to automate your own scene creation and make a custom node if you simply need to remake another JRPG character, where is just another scene.

Similar to how Substance designer has high level nodes that are made of lower level nodes.
It could speed up the repetition of scene creation.

**Comment by KoBeWi** [comment]
That totally sounds like a job for a plugin. Godot probably already supports these sorts of operations in plugins.

**Comment by ca3games** [comment]
> That totally sounds like a job for a plugin. Godot probably already supports these sorts of operations in plugins.

My idea is more like you can generate easily your own templates that create already the node hierarchy in a newer scene and they work like custom nodes with parameters that control the interiors.

Like I make a template to generate and reuse my own code to make a JRPG character on several of my projects and I don't need to remake over and over the creation of newer scenes but I can simply load this customized node which is just a scene made from a wizard of my own.

That's more like my idea, but I'm sure these nodes could be shared easily even on the asset store.
Hell, you could even automate several of them to generate easily a newer level made of such custom nodes.

Even be able to generate a basic template for a FPS or a JRPG which works like a hirarchy of said custom nodes/scenes.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
