### ISSUE TITLE
Int overflow in EditorResourcePreview::_preview_ready

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#31232]
**Godot version:**
3.2.dev.custom_build. 765839b2a

**Issue description:**
![Screenshot_20190809_103746](https://user-images.githubusercontent.com/41945903/62766086-e8301400-ba91-11e9-86ef-eedd87a3ef89.png)
**Steps to reproduce:**
Open Tilemap scene from minimal project

**Minimal reproduction project:**
[QQWR.zip](https://github.com/godotengine/godot/files/3485437/QQWR.zip)

**Comment by Anutrix** [comment]
No crash situations:
1. Opening Node2D.tscn first , then opening Tilemap scene somehow works even though p_str="ID:23022:2329490486" gives hash value that is greater than 2147483647(INT_MAX).
2. It doesn't even crash when you directly run it i.e, using F5(Play project).
3. It doesn't crash while opening or running the scene if run bin\godot.windows.tools.64.exe from external console(I used cmd.exe because I was using Windows).
I don't know the reasons for these yet. These situations feel really weird to be me.
Conclusions so far:
1. In all cases, running the given scene does crashes or make it unresponsive. While opening it does, sometimes(as mentioned above).
2. ..........
