### ISSUE TITLE
Moving .tscn files in the file dock creates pointless diffs

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31262]
**Godot version:**

3.1

**OS/device including version:**

Win 7

**Issue description:**

After moving sever .tscn files using the move command in the editors file dock, it created diffs in each and every file removing several newline characters.

It seems this might be caused by some additional/lacking check between when a tscn files is normally saved after being edited by the user, and when it is modified automatically. (Moving through the file dock will attempt to fix otherwise broken filepaths.)

**Comment by TheDuriel** [comment]
I _might_ also have been something else. Since i have a commit for _moving_ the files, which remapped the paths. And then _later_ these additional diffs appeared for seemingly no reason. (Note that i did _nothing to those files_ in the editor between those two diffs. I simply changed one unrelated script and saved it.)

**Comment by Anutrix** [comment]
It's due to difference in a line of rename_dependencies() and save() functions, isn't it?
https://github.com/godotengine/godot/blob/7bb2215ed0d7415179a8b59ad4766a3b573cf696/scene/resources/resource_format_text.cpp#L1586
https://github.com/godotengine/godot/blob/3418f76a9eab9f496e5b26310bd3bc1125b8119b/scene/resources/resource_format_text.cpp#L794

**Comment by TheDuriel** [comment]
No longer present.
