### ISSUE TITLE
Moving resource files creates pointless diffs

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31265]
**Godot version:**

3.1

**OS/device including version:**

Win7

**Issue description:**

Moving .tres and other resources files in the editor file dock, sometimes creates a new line character after the resource entry.

![image](https://user-images.githubusercontent.com/44248915/62821337-5dbfe100-bb73-11e9-853f-8921776beaaf.png)

**Comment by Anutrix** [comment]
It's due to difference in a line of rename_dependencies() and save() functions, isn't it?
https://github.com/godotengine/godot/blob/7bb2215ed0d7415179a8b59ad4766a3b573cf696/scene/resources/resource_format_text.cpp#L1586
https://github.com/godotengine/godot/blob/3418f76a9eab9f496e5b26310bd3bc1125b8119b/scene/resources/resource_format_text.cpp#L794

**Comment by bojidar-bg** [comment]
The two should be pretty equivalent though:
https://github.com/godotengine/godot/blob/3bd49dabfa909187d514e018ff7c60339e343c71/core/os/file_access.cpp#L561-L565

**Comment by KoBeWi** [comment]
I tried to reproduce it in 3.2 beta1, but doesn't seem to be happening. There were some changes to scene serialization, so maybe it is fixed?

@TheDuriel Did you have any reliable way to reproduce it and can test again?

**Comment by TheDuriel** [comment]
No, this can probably be closed. (And a new, reimporting assets creates diffs could be made... but that has to wait xD)
