### ISSUE TITLE
Add documentation to do homebrew ports.

### ISSUE THREAD

**Issue by ca3games** [godotengine/godot#31279]
Hi, I'm opening this issue to talk about the need for a documentation about porting your godot game as homebrew to consoles, maybe retro consoles.

I would love to port my game to retro consoles and emulators, but It seems godot can't easily add exporting templates to such consoles because of licencing issues, I was wondering how legal would be to easily let the users do the porting themselves and publish the binaries on the web for easy install on users.

Maybe the documentation should have a part about this topic.
I'm not talking about current generation consoles, but homebrew ports on the Wii or PS3 or DS.

**Comment by Anutrix** [comment]
Take a look at https://docs.godotengine.org/en/latest/tutorials/platform/consoles.html if you already haven't. As far as older generation consoles are concerned, AFAIK even they are licensed. And their SDK, as docs say, are secret or have limited access. Also, only limited people have knowledge on how these consoles work. Even if they do, some might be able to share it sometimes(legal issues). Even the porting knowledge could be unique for each console because it's proprietary. As you know proprietary software typically don't follow a standard.
If you can find and list out some of the consoles that are out of license(or don't cause any issues) and compatible with MIT license, maybe few from community might help.
I am _not against_ the idea, but it seems more hard than useful because of limited audience.
Let's see what others here think about it.

**Comment by ca3games** [comment]
> Take a look at https://docs.godotengine.org/en/latest/tutorials/platform/consoles.html if you already haven't. As far as older generation consoles are concerned, AFAIK even they are licensed. And their SDK, as docs say, are secret or have limited access. Also, only limited people have knowledge on how these consoles work. Even if they do, some might be able to share it sometimes(legal issues). Even the porting knowledge could be unique for each console because it's proprietary. As you know proprietary software typically don't follow a standard.
> If you can find and list out some of the consoles that are out of license(or don't cause any issues) and compatible with MIT license, maybe few from community might help.
> I am _not against_ the idea, but it seems more hard than useful because of limited audience.
> Let's see what others here think about it.

I think it falls under a fair use clause, reverse engineering is legal from my understanding and reverse engineering a piece of hardware to add some functionality or do software ports is legal, since is not piracy and falls under the fair use.
I think at least testing your game on emulators should be legal, since it would have the same legality of emulation (emulators are legal but not piracy of roms).

Also, from my understanding console companies lack any interest on such retro consoles, so they wont be interested in homebrew ports, they care more about piracy of their IPs than homebrews.
So, I don't see why at least testing your roms on an emulator should be illegal.

**Comment by ElfEars** [comment]
I think you'd need to do this on an older version. A REALLY old version.

Godot used to be able to run on tons of crazy platforms (even flash at one point IIRC.) but no longer supports any of those

Not exactly sure what strange stuff in the first open source release (pretty sure most of the really weird stuff was already depreciated) but with the 3.0 update tons of vestigial compatibility was wiped.

There's talks of releasing the entire history of Godot's code (sans proprietary SDKs) but you're gonna have to manually convert EVERYTHING. Formats have drastically changed even between the first open source release and now.

**Comment by Calinou** [comment]
Closing, as this will not be tackled officially (especially given the [new direction of the documentation](https://github.com/godotengine/godot-docs/issues/3390)). Nonetheless, nothing prevents third parties from writing homebrew ports and documentation for them :slightly_smiling_face:
