### ISSUE TITLE
Add ability to see list of all breakpoints

### ISSUE THREAD

**Issue by iwek7** [godotengine/godot#31285]
**Godot version:**
3.1

**OS/device including version:**
any

**Issue description:**
Currently management of breakpoints in godot is lacking. https://github.com/godotengine/godot/pull/30982 adds ability to disable/enable all breakpoints but it is not enough. **I want to be able to see the list of all existing breakpoints and be able to manage them from that list**, that means deleting them, moving to them in script and in future disabling single breakpoints or view attached conditions (currently last two features are not implemented). As far as I know right now there is no way to know where breakpoints are - you have to manually go through the files and remove them.

Most popular IDEs support this feature, examples:

**QTCreator**
![image](https://user-images.githubusercontent.com/9964886/62831683-93bc9e00-bc23-11e9-9bde-97938ab4c432.png)

**Intellij**
![image](https://user-images.githubusercontent.com/9964886/62831807-d92d9b00-bc24-11e9-8f81-9d5929e7d3ed.png)

I presonally would go with IntelliJ way of opening view in separate window (button to open it available near debugging options) as it does not clutter existing menu and allows to show richer set of options in future - especially showing code snippet around breakpoint is fancy :).

If issue gains some traction I can try to implement it. Looking for feedback.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
