### ISSUE TITLE
Scalable Realtime Global Illumination

### ISSUE THREAD

**Issue by DevMagicLord** [godotengine/godot#31289]
This could be a solution for lot of large 3D games when more people will use Godot for 3D.

Perhaps more capable and optimized than the current global illumination system. 

GDC presentation : 
https://www.gdcvault.com/play/1026469/Scalable-Real-Time-Global-Illumination

**Comment by mindinsomnia** [comment]
That is an amazing method, I love it!

**Comment by Calinou** [comment]
Note that the slideshow linked states that a deferred renderer is a requirement for this technique ("at least lighting and 'dynamic' layers"). Since Godot 4 will use a forward renderer, this may not be possible.

**Comment by Byzantian** [comment]
I really really hope Godot never fully ditches its forward renderer. Too many modern engines like Unreal 4 rely on deferred rendering, which severely limits the use of MSAA. People might argue that MSAA is outdated since modern AAA games have so many triangels that it starts to converge towards SSAA anyways, but since Godot is mainly used by indie developers, it seems fitting to keep the forward renderer arround for people like myself who prefer MSAA and baked lighting to real-time GI with ugly post process AA.

**Comment by mindinsomnia** [comment]
I think both forward and deferred have their pros and cons, deferred shading can be really beneficial for all the information it provides with a gbuffer and the separation between materials and lighting can be nice, it handles a large number of lights very well and reduces the amount of overdraw and shading of invisible surfaces. But a lot of those problems can also be solved with forward shading techniques. AA and transparency are definitely problematic for deferred shading, but there are some solutions for that too. I've always been a fan of the [SRAA technique](https://research.nvidia.com/sites/default/files/pubs/2011-02_Subpixel-Reconstruction-Antialiasing/I3D11.pdf) for AA in deferred shading, it seems very close to MSAA, but it does require rendering at least a supersampled depth and/or normal buffer.

One 'pro' for deferred shading I definitely like is the ease of implementing decals on surfaces. That's wonderful. But a strong disadvantage of deferred shading is the limitations it imposes on your material support, all the properties have to fit within the gbuffer, unless you're referring materials with IDs perhaps.

**Comment by Byzantian** [comment]
Not a fan of any kind of post-process AA in general. The thing I always loved about MSAA was that I was always be able to force it via the driver, even if the game didn't support it. With modern rendering pipelines people are at the mercy of the devs if they want good AA. But regardless, I hope that even if godot goes deferred one day that it will always still support plain old forward rendering. I think Unity does the same. Forward rendering for people who like their MSAA and deferred for people who can't live without realtime GI.

**Comment by Calinou** [comment]
@Byzantian Unreal Engine 4 also has a forward renderer, which is primarily targeted at VR usage (where post-process AA often looks bad, making MSAA a must have).

**Comment by blockspacer** [comment]
> [Quote] it's basically an optimized version of **SEGI, the latter being open source** https://forum.unity.com/threads/id-like-this-gi-solution-in-unity-thanks-a-lot.656899/

**Also supports only slowly changing lights (semi-static lights). Need to fake dynamic lights somehow.**

**Comment by Byzantian** [comment]
@Calinou Got any documentation on how to enable the forward pipeline for non VR purposes? I think post-process AA looks bad, period. (Sorry for the off-topic)

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
Open world GI is currently being implemented in the `master` branch (it's not committed yet).
