### ISSUE TITLE
Want to shrink the so size in mobile platform, can i disable 2D related code safely?

### ISSUE THREAD

**Issue by rssqian** [godotengine/godot#3132]
Hi,
    I want to shrink the so size, and as our main usage is in 3D, Could I disable 2D related code safely?
    Disable 2D related code in UI,Audio,Scene and so on....
    Will UI/Audio/Rendering system and so on ..., still works well with godot 3D Scene.

Many thanks,
Fengwei.

**Comment by bojidar-bg** [comment]
Pretty ping, it has been a long time without answer on this issue :smiley: 

Anyway, in my opinion that shouldn't be done, since there are few (if any) 3D games that don't use 2D Control nodes for HUD or menus, plus it should shrink code enough to be worth it. Anyway, for adventurous godot users, I guess even this should be possible (albeit complicated) :wink:

**Comment by akien-mga** [comment]
Last I tried disabling 3D hardly reduced the size of the template, so I don't think disabling 2D would be particularly useful either. And indeed Controls inherit CanvasItem which is the base class of the 2D stack, so it would likely be non-trivial to implement this for little gain.

As such, I'd propose to close this issue. :)

**Comment by KoBeWi** [comment]
We have this now: https://docs.godotengine.org/en/3.1/development/compiling/optimizing_for_size.html

Disabling 2D isn't mentioned there. Well, it doesn't make much sense, unless we are talking only about Node2Ds (since Controls are rather useful even for 3D...)

**Comment by akien-mga** [comment]
Thanks, closing then as the documentation needs are fulfilled indeed.
