### ISSUE TITLE
Add flip/mirror option to GridMap

### ISSUE THREAD

**Issue by Xenoamor** [godotengine/godot#31340]
**Godot version:**
3.1.1.stable.official

**Issue description:**
To save having to have identical but mirrored meshes in a GridMap I propose a flip/mirror option is added to GridMaps much like there is with TileMaps

Currently a GridMaps cell contents looks like this:
```
union Cell {
	struct {
		unsigned int item : 16;
		unsigned int rot : 5;
		unsigned int layer : 8;
	};
	uint32_t cell;

	Cell() {
		item = 0;
		rot = 0;
		layer = 0;
	}
};
```

I propose we change it to the following:
```
union Cell {
	struct {
		unsigned int item : 16;
		unsigned int rot : 5;
		unsigned int layer : 8;
		bool mirrored_x : 1;
		bool mirrored_y : 1;
		bool mirrored_z : 1;
	};
	uint32_t cell;

	Cell() {
		item = 0;
		rot = 0;
		layer = 0;
		mirrored_x = false;
		mirrored_y = false;
		mirrored_z = false;
	}
};
```

This however is worth some discussion as this will fill the `uint32_t` and remove any room for new features down the line. It would also need to be discussed if the mirroring would occur before _or_ after the rotation

**Comment by Varicus** [comment]
I would like to offer a different approach to mirror/flip in GridMap. Currently the orientation is saved as an integer ranging from 0 to 23. Every mirrored possibilty can be expressed by flipping only one of the axis, as flipping two axes is the same as a rotation of 180 degrees. It is therefore possible to express flipped bases either as a flip and a base rotation or by directly including flipped bases in the orientation integer. Either way, only **one** additional bit is needed.
Cells would therefore either look like this:
```
union Cell {
	struct {
		unsigned int item : 16;
		unsigned int rot : 5;
		unsigned int layer : 8;
		bool mirrored : 1;
	};
	uint32_t cell;

	Cell() {
		item = 0;
		rot = 0;
		layer = 0;
		mirrored = false;
	}
};
```
or like this:
```
union Cell {
	struct {
		unsigned int item : 16;
		unsigned int rot : 6;
		unsigned int layer : 8;
	};
	uint32_t cell;

	Cell() {
		item = 0;
		rot = 0;
		layer = 0;
	}
};
```
For the second option, the methods Basis::get_orthogonal_index() and Basis::set_orthogonal_index() have to be rewritten. I did that as a proof of concept over [here](https://github.com/Varicus/godot/commit/2fd5db94f5dbb2b792554c8329256f38d719cd52).
Those changes unfortunately break backwards compatibility, but it allows for the calculation of the orientation index from the basis instead of looking it up in an array.

**Comment by Xenoamor** [comment]
I definitely prefer this idea, good spot on the mirror optimisation to one bit.
I'm not sure if we want to break compatibility here but removing that ugly lookup table is definitely worth considering

How should we go about storing the flipped meshes? I guess we can either add all the meshes flipped when the Meshlibrary is mirrored or we could create them as needed with `MeshLibrary.create_item(id)`. We could also just create them on the stack

**Comment by Varicus** [comment]
Based on your pull request #31361, I took the liberty to implement the version with 6 bits for the item orientation in my branch over [here](https://github.com/Varicus/godot/tree/GridMapMirror). I kept the ugly lookup table for now to keep backwards compatibility, but the Basis methods could be exchanged for the ones I linked earlier.

Like your version also, this has a lighting issue when mirrored objects are placed in the GridMap. But since it does not change the method signature of GridMap::set_cell_item, the method binding does still work.

What do you mean by storing the flipped meshes? Since the information about mirrored cells is stored within the cell data, there should be no need to include more items in the MeshLibrary.

**Comment by Xenoamor** [comment]
Thanks @Varicus, this is great. I'll give it a try when I get back from the day job. This looks very clean though. Not sure if someone will object to having mirror information baked into the rotation parameter but as far as I'm aware those `Basis::` commands are only ever used by the `GridMap` anyway.

What I mean by flipped meshes is that the normals need to be inverted when the mesh is mirrored. There's a fairly similar example of this https://github.com/godotengine/godot/commit/9f2d54cd6827e39799b85bf306d0fc98ce5941bd. We could do this flipping in the `MeshLibrary` itself and adding it back into it or we could dynamically do it as required

We could do it when we construct the `GridMap` and potentially keep any on the stack in case they are reused in an octant. I imagine this will need to be done in `GridMap::_octant_update`

**Comment by DerKorb** [comment]
This would be interesting for me as well. The proposed solution here would be nice.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
