### ISSUE TITLE
RichTextLabel Theme-Responsive Tags/BBCodes

### ISSUE THREAD

**Issue by rxlecky** [godotengine/godot#31365]
Since RTL is usually a go-to solution for displaying formatted text, it would make sense for it to be theme-responsive. Currently all tags, i.e. font colors, underline, alignemnt, fonts, icons, etc, are static.

My suggestion is to add overloads to currently existing `push_*` functions that will insert "dynamic" tags that will get data from currently used theme. As an example,  `void push_color(const StringName &p_name, const StringName &p_type)` would be added and it would call `Control::get_color` to resolve its color. If too many `get_*` calls would turn out to be an issue, the results could be cached and refreshed when `NOTIFICATION_THEME_CHANGED` is received.

An example from the editor where this issue is evident.
![obrázok](https://user-images.githubusercontent.com/35656626/62983298-241afe80-be2f-11e9-9402-100150e9b4d8.png)

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
