### ISSUE TITLE
"Revert sub-resources to parent"

### ISSUE THREAD

**Issue by nobuyukinyuu** [godotengine/godot#31397]
**Godot version:**
3.1.1

**Issue description:**
This is a feature request.  I've found that when working with AnimationPlayers in inherited scenes, the consistency of "Local to Scene" resources is a bit spotty and Animations seem to prefer to stay local to scene once they've been overridden to do so.  Normally, to revert a property value to its parent defaults, most resources in the inspector have a revert button next to them in their parent context.  However, Animations are unique in that they can't be accessed directly from their parent but must instead be loaded into the inspector context from an option in the Animation tab.

One way to make it more obvious that overridden animations are reverted back to their parent resource's instance would be to add an option in the inspector menu next to "Make Sub-Resources Unique",  "Revert Sub-Resources to parent", if the subresource inherits from a parent one..

**Comment by robertarnborg** [comment]
Working with animationplayers in inherited scenes has been a nightmare for me. You dont feel safe that the changes you make will stick or that you override the parents animation player resources... the animationplayer is a real boon for godot but a bit spotty or finicky that you need to make subresources uniwque or just kill the inheritance.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
