### ISSUE TITLE
DDGI support (realtime global illumination without precompute)

### ISSUE THREAD

**Issue by blockspacer** [godotengine/godot#31405]
**Current GI state**: Godot uses voxel cone tracing (VCT) for global illumination (GI), see https://godotengine.org/article/godot-3-renderer-design-explained

According to https://www.ogre3d.org/2019/08/05/voxel-cone-tracing **Dynamic Diffuse Global Illumination (DDGI) can be built from _VCT_ or raytracing**

**Usefull links**:
http://www.cim.mcgill.ca/~derek/files/DDGI-highres.pdf
https://morgan3d.github.io/articles/2019-04-01-ddgi/
https://morgan3d.github.io/articles/2019-04-01-ddgi/intro-to-gi.html
https://morgan3d.github.io/articles/2019-04-01-ddgi/overview.html#citation-archard19
https://forum.unity.com/threads/enlighten-deprecation-and-replacement-solution.697778/page-2
https://www.cryengine.com/news/how-we-made-neon-noir-ray-traced-reflections-in-cryengine-and-more
https://github.com/armory3d/armory/issues/1268
https://news.developer.nvidia.com/an-engineers-guide-to-integrating-ddgi/
https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9900-irradiance-fields-rtx-diffuse-global-illumination-for-local-and-cloud-graphics.pdf

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
Note that the new GIProbe in the `master` branch supports real-time GI. Open world GI is also being worked on.
