### ISSUE TITLE
Unshaded shaders compile twice - first as shaded, then unshaded

### ISSUE THREAD

**Issue by endragor** [godotengine/godot#31406]
**Godot version:**
Commit b030834b6384d5f57e5fc63db21b643adc86b3da

**OS/device including version:**
Any

**Issue description:**
If you use `render_mode unshaded;`, then the shader gets compiled twice: first during scene load without `#define SHADELESS`, then during first frame rendering with `#define SHADELESS`. I've tested this on GLES2 (Godot compiled with `#define DEBUG_SHADER` in shader_gles2.cpp).

The issue is important as it induces 2x overhead for shader compilation time, which takes a significant chunk of scene loading, especially on mobile. The code should make sure the shader compiled during scene loading is the same one as will be used during rendering, or else simply delay binding the shader before it's actually necessary.

**Steps to reproduce:**
1. Compile Godot with `#define DEBUG_SHADER`, so that shader compilation and `#define` flags are logged.
2. Create a project with a simple unshaded shader that does nothing.
3. Observe the shader is compiled twice when running the project.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?
(although there's higher chance that something changed in 4.0-dev)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
