### ISSUE TITLE
save screenshot for Visual Shader

### ISSUE THREAD

**Issue by MadaraZ** [godotengine/godot#31429]
**Godot version:**
afecc0bc2283dfbfbce70ae95c28e0ed4ecd4160

keep high resolution screenshot users find it easier to watch the Discord and others useful, visual shader novice easier to learn fast for screenshot :)

![image](https://user-images.githubusercontent.com/17591539/63208780-2c9a6000-c0e1-11e9-991b-41dd9bfd288f.png)

screenshot save only format `.png` any directory

---------------------------------------------------------------------
for example, the first is not enough space channel longer visual shader will not be able to fully save screenshot
![image](https://user-images.githubusercontent.com/17591539/63209120-9caae500-c0e5-11e9-94ce-ff5a22756143.png)

for example, the second screenshot is hard to see zoom out save the screenshot there are problem
![image](https://user-images.githubusercontent.com/17591539/63209132-c19f5800-c0e5-11e9-8a44-5e76791632c4.png)

for example the third screenshot is not convenient through the GIMP save the screenshot is not very
![image](https://user-images.githubusercontent.com/17591539/63209138-d4199180-c0e5-11e9-99a5-c6e289eebcce.png)

**Comment by Jummit** [comment]
Maybe this could be put in GraphEdit, so it works for VisualScript as well?

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

(btw, in 3.2 you can take an editor screenshot, which partially addressees this issue)
