### ISSUE TITLE
Segfault crash when using set_cell 3.2-dev.

### ISSUE THREAD

**Issue by alexis-evelyn** [godotengine/godot#31477]

**Comment by alex-evelyn** [comment]
I just did some more testing and the timer has nothing to do with the crash. Also, the crash definitely only occurs when generating worlds. This means the server has to load the tiles into the tilemap and not just send them to the client. When loading, the server just pulls the tiles out of the tilemap (because the game has non-infinite worlds) and the sends them to the client as a dictionary in the form of chunks.

get_cell(...) doesn't seem to cause any issues, it is only set_cell(...) that causes issues. This crash occurs on the first instance of generating a chunk. Maybe, this has something to do with the fact that the chunk generation is done during _physics_process instead of _process (in the player's KinematicBody2D)?

**Comment by alex-evelyn** [comment]
Here's a [crash log](https://pastebin.com/iCzydXpy) from the crash reporter that I just got (they seem to be random if the window will pop up).

**Comment by alex-evelyn** [comment]
Copied From Reddit Comment: https://www.reddit.com/r/godot/comments/csbptd/help_tracking_down_cause_of_two_errors_which/exenekz/

I think the KinematicBody2D movement is a symptom of the problem. The reason I say this is because trying to set the chunks regardless if the player is moving (while inside _physics_process) ends up doing absolutely nothing. The generator code is still being run, it just doesn't do anything to the Tilemap (but at least the server is not crashing).

**Comment by alex-evelyn** [comment]
I suspect the crash has something to do with threading. The crash only occurs in the calling code in rpc and when I decided to try threading the server (so I can have a loading screen), the server crashed with [this log](https://pastebin.com/sQ8J75Ds).

**Comment by DanielKinsman** [comment]
I was having a similar problem with a kinematicbody2d on a tilemap will collision shapes, getting errors showing up such as your `!E Condition` prior to crashes. I tried for a good 2 hours to reproduce it in a smaller project with no luck.

I did find a solution in my main project though: changing the physics threading model back to the default (Single-Safe) from Multi-Threaded. I see that [your code is also using the Multi-Threaded model](https://github.com/alexis-evelyn/Sweet-Tea/blob/290c21c243ed4cf2fd5bd1ad9c95e1e59e58627a/project.godot#L147) so try that out @alexis-evelyn. Your problem may be different but it's worth a shot (if it is even relevant for you a year later).

**Comment by jonbonazza** [comment]
Why does this have the network label?

**Comment by Calinou** [comment]
> Why does this have the network label?

I don't see any reason for it either, so I removed the label.

**Comment by alexis-evelyn** [comment]
As I just started working on my game again a couple of days ago, I'll be able to test this within the next couple of days. I'm currently upgrading my game for the latest version of Godot.

**Comment by alexis-evelyn** [comment]
Yep, it still does occur. This time caused by the server player and both the client and server copies of the game crashing. Single threaded safe does not seem to help (it changes from outright crashing both the client and server immediately on multi-threaded to freezing the server instance (the copy of the game open to lan) while the client instance is unaffected. I'll be editing this with a Youtube video to demonstrate the issue and I'll see if I can figure out what the crash report means (I'm used to Java stacktraces, but don't really know how to read binary crash reports).

**Comment by alexis-evelyn** [comment]
So, as I switched to Debian from OSX due to constantly running out of disk space, I ended up setting up Godot on Debian. While I have two new bugs (unrelated to this report and potentially the engine in general; it's a bug with having to unfocus the window and refocus to gain control of my player and the physics stuttering once a second or so along with 3 fps frame dropping from 30 VSync that I never had before), but I did decide to test the Multi-Threaded Physics and have learned that the threading causing a segfault bug is Mac OSX specific. It's the same hardware, but the OS is different.

The game can generate chunks just fine in multiplayer on Debian with KDE.
