### ISSUE TITLE
Project manager window cursor offset

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3149]
I recently compiled from source (I think December 26) and I discovered the project Manager window (the  first window you see when Godot launches) has changed to a bigger size.

The problem: there seems to be some kind of offset between the real cursor and the "virtual" cursor. This is visible if you move the cursor over the buttons and see the hover effects.

It's not a big bug, but it's definitively a bug.
Request: The project manager window should also be opened maximized.

**Comment by neikeq** [comment]
I don't understand the issue, but I don't agree with the project manager starting maximized.

**Comment by reduz** [comment]
project manager for now will not get much changes, plan is to rewrite it for 2.1 once we have a better asset sharing system, so it can show a library of templates to download from the web instead

**Comment by reduz** [comment]
also I can't seem to reproduce this bug in any way, please try again to see if it's still there

**Comment by FEDE0D** [comment]
I compiled an hour ago and is still there.

**Comment by reduz** [comment]
I started godot with -mx to maximize it and it works fine

**Comment by FEDE0D** [comment]
I just found that my screen is too small (1366x768).
The window manager on Linux Mint has to scale the window down to fit on my screen.
If I move the window or maximize/restore the window it works fine.

I guess it's Caja's fault. You can close this issue now :)

**Comment by vnen** [comment]
I actually have this issue too with Gnome on Arch Linux. Might be the screen size problem, as it happens on my laptop with the same screen resolution (1366X768).

When I open the editor, the project manager shows some black section on the right:

![captura de tela de 2016-01-23 19-19-19](https://cloud.githubusercontent.com/assets/5599796/12532914/af2ec534-c206-11e5-9e01-cb61585f8ef8.png)

I have to click on the bottom half of the controls for it to work or bellow it. There is an offset between the visible cursor and the position where it's clicking (though I think that actually the window have the offset, not the cursor). The same happens to the editor, which is more visible:

![captura de tela de 2016-01-23 19-19-51](https://cloud.githubusercontent.com/assets/5599796/12532931/18b0a7fc-c207-11e5-8950-cf99ecec42ac.png)

I can fix it by restoring the window and maximizing it again (both with the project manager and the editor):

![captura de tela de 2016-01-23 19-20-10](https://cloud.githubusercontent.com/assets/5599796/12532936/538b9ed6-c207-11e5-9518-201e1de1eb83.png)

The problem also happens when I go back from the editor to the project manager.

**Comment by vnen** [comment]
Ok, definitely it is the screen size. It works fine when I plug the laptop on a big monitor:

![captura de tela de 2016-01-23 19-31-19](https://cloud.githubusercontent.com/assets/5599796/12532956/1223fe06-c208-11e5-8a60-90734e9e1874.png)

**Comment by reduz** [comment]
I really have no idea how to fix this, if fixable. Seems to work fine for me in Ubuntu

**Comment by vnen** [comment]
My wild guess is that the initial size of the windows are too big, so in small screens the window manager might be confused. May be the fault is on the window manager.

Is the window size set anywhere in the code?

**Comment by akien-mga** [comment]
If hardcoded anywhere, I think it's 1024x768.

**Comment by akien-mga** [comment]
> If hardcoded anywhere, I think it's 1024x768.

Hm, or actually 1280x720? https://github.com/godotengine/godot/blob/7e20c86ac71d27cc45e6a38feedc3037e8b0e8cd/core/os/os.h#L79
