### ISSUE TITLE
Suggestion: ARVR mode for editor

### ISSUE THREAD

**Issue by Scipi** [godotengine/godot#31510]
Unreal Engine has a in-editor VR mode that allows users to build content directly in VR using a headset like Occulus or Vive

https://docs.unrealengine.com/en-US/Engine/Editor/VR/index.html

Having a feature to create and edit scenes while in VR could be very useful for VR developers, as they wouldn't have to keep switching in and out of VR in order to test. And since Godot supports visual scripting, a majority of content in a scene could be created directly in the VR editor pretty intuitively (minus assets like textures and models)

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
