### ISSUE TITLE
Pressing Reload does not reload currently running scene, plays currently opened scene instead

### ISSUE THREAD

**Issue by PLyczkowski** [godotengine/godot#31515]
**Godot version:**
![image](https://user-images.githubusercontent.com/7307968/63382217-8c6f6000-c39a-11e9-8dae-5778887fba06.png)

**Issue description:**
The icon to re-play scene:
![image](https://user-images.githubusercontent.com/7307968/63382421-fbe54f80-c39a-11e9-9691-6c08cb4da11e.png)
suggests a Reload action. Instead it still behaves as Play Current Scene.

**Steps to reproduce:**
Have scene A and scene B. Currently active tab is scene A. Press Play Scene. The Play Scene button changes to a Reload button. While scene A is running, switch tab to scene B. Press Reload. Getting scene A played here would be convenient and more intuitive (the icon would suggest that). Scene B is played instead.

**Comment by Yoshiyuka** [comment]
I would expect the icon to indicate intention to "reload _currently running_ scene". It sounds like this is the current behavior. 
Am I understanding you correctly in that you wish for the updated behavior to be "close all running scenes and reload the first previously opened scene"?

**Comment by PLyczkowski** [comment]
@Yoshiyuka I would also expect the button to reload currently running scene, but it does not do that - it plays the scene that is open (which tab is currently active).

**Comment by KoBeWi** [comment]
Looks like the "_Reload_" button is now moved to Run instead. It has a correct tooltip, so IMO it's ok.

**Comment by akien-mga** [comment]
> Looks like the "Reload" button is now moved to Run instead. It has a correct tooltip, so IMO it's ok.

I thought so too for a bit but no, the "Reload" button is placed on top of the play button you used, i.e. either "Play", "Play Current Scene" or "Play Custom Scene".

And when using "Play Current Scene" and then changing the current scene in the editor, it will indeed act as "start currently edited scene" instead of "reload currently playing scene".

On the other hand the "Play Custom Scene" button's reload mode will properly reload the currently playing scene, so it shouldn't be too difficult to make the "Play Custom Scene" button do the same.

That being said, I can foresee users being equally confused if pressing the "Play Current Scene" button/hotkey would replay the currently playing scene instead of the one they chose to edit.
