### ISSUE TITLE
Improve scrollbar design?

### ISSUE THREAD

**Issue by SuperRobinHood** [godotengine/godot#31520]
Version: v3.2.dev.calinou.093798c97

The current scrollbars are small, have no arrows and are too similar in color to the rest of the interface. It's really hard to use them or even find them. How about a look like this: https://bipedu.files.wordpress.com/2013/01/xfce_samba10.png.

**Comment by VitaZheltyakov** [comment]
You can easily change the appearance of standard interface elements using themes.
I do not think that this problem requires consideration.

**Comment by Calinou** [comment]
Many applications have dropped the "up/down" arrows typically associated with scrollbars, since they are hardly ever used. Take Dolphin for example:

![image](https://user-images.githubusercontent.com/180032/63442481-795c9e80-c433-11e9-84e6-5bcca4189c04.png)

(The first scrollbar is hovered, the second one isn't.)

**Comment by MunWolf** [comment]
Pretty much the only thing here that is not just a reskin which is already possible is the arrows on the scrollbar, and I have to vote with @Calinou that I like it better when they are not there.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
