### ISSUE TITLE
Add ability to specify number of colums in an exported array per row in the GridContainer

### ISSUE THREAD

**Issue by creikey** [godotengine/godot#31542]
It would massively improve the usability of the gridcontainer, allowing each row to contain a flexible number of columns.

Differs from #30173 in that it allows the columns per row to be manually specified, as it is in QT.

**Comment by groud** [comment]
It's is likely not worth the complexity added to GridContainer. You can achieve the exact same behavior by staking HBoxContainers into a VBoxContainer.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
