### ISSUE TITLE
FLIF support

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#31568]
requesting this format to be supported

it achieves a 43% smaller file size than lossless png, 14% smaller than a lossless webp

https://flif.info/index.html

**Comment by DegradedMind** [comment]
Oh! I stumbled upon this format two months ago and also thought that it would be cool for Godot to add its support, but I didn't opened a request because i thought people would not be interested in that.

**Comment by anderlli0053** [comment]
@reduz  @akien-mga

**Comment by fire** [comment]
How does adding FLIF support help?

For example:

I assisted zylann with openexr export because it was necessary to have a format that can export 16bit or 32bit per component channels to an image.

Godot uses an internal packing for image formats called stex when exported, so the size saving doesn't help.

The use cases for FLIF sounds like png use cases, just use png?

**Comment by fire** [comment]
Thirdly FLIF is LGPL v3 and that is less compatible with Godot's MIT license.

I cannot find any other implementation.

https://www.reddit.com/r/programming/comments/3n7yvx/flif_free_lossless_image_format/cvlmnb3/ mentioned that it is slow, but I haven't tested those claims.

**Comment by Calinou** [comment]
Given FLIF's encoder license and the low activity of its [development repository](https://github.com/FLIF-hub/FLIF) (last commit on 2018-10-26 as of writing), I think we should close this.
