### ISSUE TITLE
get_stack() should translate to MainLoop.NOTIFICATION_CRASH and there should be an intentional way to crash the game for testing crash handler.

### ISSUE THREAD

**Issue by alexis-evelyn** [godotengine/godot#31610]
This is a feature request, not a bug.

**Godot version:**
3.2-dev

**OS/device including version:**
All Devices

**Issue description:**
When a MainLoop.NOTIFICATION_CRASH is called, the get_stack() from what caused the crash should be provided so the crash handler can print the stacktrace. I currently cannot get my game to crash while still calling the crash handler (because apparently my previously buggy code from an older commit of my game is deciding not to bug out right now). I did test the get_stack() using MainLoop.NOTIFICATION_WM_ABOUT on my mac and it currently starts the stack trace at the MainLoop handler in my game (which is where the crash handler is also located).

Also, there should be a way to intentionally crash the game (something like OS.crash()) so that developers can test to make sure their crash handler works. An example for me is I want to be able to log to a file while the game is running and put a stack trace in the log. Then, I would save a variable to the save file saying the game has crashed so when the game is loaded the next time, it can alert the player that a crash has occurred and that they should submit the log to me.

**Steps to reproduce:**
1. Crash Game (without causing segfault/freezing)
2. Check value of get_stack() that was printed to stderr or logged.

**Minimal reproduction project:**
Not a bug and I couldn't get my game to crash, so I don't have a working example anyway.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
