### ISSUE TITLE
Why the tiles transform set in one scene file will change that setting in other scenes?

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31629]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

For example, I have sceneA1 and sceneA2  inherited from SceneA, when I changed the  transform of tiles for the TileMap in sceneA1, the change will also set in the sceneA2 file.  My intention is the tiles filled in the sceneA1 flipped, but not the sceneA2, so when I edit the TileMap in SceneA2, I must clear the transform for the Tiles and change it again when back to sceneA1.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by KoBeWi** [comment]
What do you mean by "change transform"? If you are editing TileSet, it's because the resource is shared, not inherited. Only nodes inherit values.

**Comment by alexzheng** [comment]
<img width="380" alt="Screen Shot 2019-09-09 at 11 32 17 PM" src="https://user-images.githubusercontent.com/1130047/64544774-29019e00-d35a-11e9-8fa9-63b0eff0a83c.png">
I mean these settings.

**Comment by KoBeWi** [comment]
But this only affects tile placement. It's the same with e.g. multiple scenes and Move Tool. The TileMap itself is not modified.

**Comment by alexzheng** [comment]
Yes,but this is very inconvenient. If you flip the tile in one scene, in other scenes you will need to  change it back.

**Comment by KoBeWi** [comment]
In 3.2, there's a shortcut for that (similar to GridMap).

So this issue is basically about storing TileMap editor's state separately per-scene.

**Comment by alexzheng** [comment]
exactly.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
