### ISSUE TITLE
Using flow control keywords in ternary statements

### ISSUE THREAD

**Issue by aspenforest** [godotengine/godot#31677]
I'd like to be able to do:
`break if x == 0 else continue`
and:
`pass if x == 0 else break`
also:
`return myvar if x == 0 else pass`  

I could be writing so elegant code with this, but I can't, cause this capability is currently not available.

Instead, I must do this ugly-ass code:
```
if x == 0:
   ifthing
else:
   elsething
```

**Comment by Janders1800** [comment]
You can do this:
`if x == 0: ifthing; else: elsething`

**Comment by aspenforest** [comment]
god that's ugly :D

**Comment by Calinou** [comment]
I don't see what's wrong with the current approach. While it spends more lines, it's easy to read and much more common in most programming languages out there.

**Comment by aspenforest** [comment]
You're right, of course, but in addition of beautiful logic, I also strive
for visual code beauty, how the lines flow and form visual structures in
the code.
It prolongs development time, but what I produce is so beautiful... :)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
