### ISSUE TITLE
Mac OSX seems to report wrong language to Godot.

### ISSUE THREAD

**Issue by alex-evelyn** [godotengine/godot#31673]
**Godot version:**
3.2-dev

**OS/device including version:**
Darwin 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64 i386 (or Mojave 10.14.6)

**Issue description:**
Mac OSX seems to give the wrong locale version to Godot. When switching my mac's language to spanish the command `OS.get_locale()` returns en_US. The command `defaults read -g AppleLocale` also returns en_US.

Manually setting the language to es_ES (using the command `defaults write NSGlobalDomain AppleLocale -string es_ES`) results in Godot printing en_ES. I have yet to figure out how to change the `en` part of the language setting for Godot (using nothing but detecting the system language).

My mac itself properly changes languages for all other programs including Chrome. Godot's editor itself is in English, but I don't know if that is related to this issue.

**Steps to reproduce:**
Try setting the system language and see if Godot reports back the right language.

**Minimal reproduction project:**
Detect system language with `OS.get_locale()`.

**Comment by akien-mga** [comment]
CC @godotengine/macos

**Comment by bruvzg** [comment]
You are somehow changing only region (second part of `xx_XX` code, and Godot only care about first part) instead of primary language. Not sure what's wrong.

Changing language from the "System preferences" -> "Language & Region" works OK for me.

![Captura de pantalla 2019-08-26 a las 17 53 27](https://user-images.githubusercontent.com/7645683/63699961-84943d80-c82a-11e9-8e2f-00bfff0c77ae.png)
