### ISSUE TITLE
[C#/GDScript] Addition of _PreDelete() method in Node API for de-init code

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [godotengine/godot#31688]
I think it would be beneficial to add support into API for a function override where you would be able to put all the de-init code of the script/autoloaded script. The current implementation looks rather ugly: 
`public override void _Notification(int what) { if(what == NotificationPredelete) { ...de-init code... } }`
 and relies on notification usage that I never had to touch until this very moment.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
