### ISSUE TITLE
Ability to create language definitions during runtime

### ISSUE THREAD

**Issue by alexis-evelyn** [godotengine/godot#31690]
This is not a bug, this is a feature request.

**Godot version:**
3.2-dev

**OS/device including version:**
All

**Issue description:**
There should be a way to set a new language either in the project settings or gdscript. An example of the function could be something like TranslationServer.add_language("language_code", "Language Name"). The language importer can then just simply ignore if a language in the csv file is valid and just import it anyway.

I decided to add a joke language (I was toying around with in high school) by just simply specifying the name and code directly in Godot's source and it works just fine. Having a function that can do this during run time would be amazing.

This can be useful for languages that are not standardized and also for people who invent their own languages for their games (so people won't have to compile a custom version of Godot to do this).

**Steps to reproduce:**
Try setting a language not builtin to Godot.

**Minimal reproduction project:**
None Needed

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
