### ISSUE TITLE
In-game Editor Functionality

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#31693]
I recently managed to get the scene tree and inspector working in-game:
![ingame_editor](https://user-images.githubusercontent.com/11153232/63736450-477b8a00-c8c2-11e9-83b4-7719bfc921d8.jpg)

In theory this should work in a release build also (I have yet to test it). But I want to propose some changes be made to the editor code to make it possible for every one to use basically some of the editor features in game - even a release build.

to get this working I had to:
(1) make a copy of a bunch of editor files (see highlighted):
![editor_files](https://user-images.githubusercontent.com/11153232/63736626-ed2ef900-c8c2-11e9-8512-d4623e87ee39.jpg)
(2) modify the code to change the singleton usage or static method usage
(3) modify my plugin to include these files

To get this build something like this added to Godot I would suggest:
(1) modify the same files to accept some sort of EditorFactory to replace the singleton and static function usage
(2) Somehow allowing a subset of the editor to be compiled into a release build
(3) Some way for gdscript to be able to bring this up ingame

I am happy to attempt a PR to get this into Godot if such a change would be accepted.

**Comment by Zylann** [comment]
This is slightly related, but even within the editor I have difficulty using a proper inspector, and ended up making my own in GDScript. Pulling entire controls thought for the editor into a game sounds like a lot of trouble to get through in the long run, while having controls made for re-usability is more trusty.

**Comment by bojidar-bg** [comment]
Slightly related to #4725. implementing editor functionality using GDNative would allow using all those controls without bloating the engine for users who don't. (not saying it is a good idea though)

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by duchainer** [comment]
For the next people to come across this issue, Zylann's inspector is this one : https://github.com/Zylann/godot_hterrain_demo/blob/d3e2f78e9fe6b56973b8a92c7384e349a5670e49/addons/zylann.hterrain/tools/inspector/inspector.gd

Have a great day :D
