### ISSUE TITLE
Suggestion for folders

### ISSUE THREAD

**Issue by BigDC** [godotengine/godot#31786]
Hey may I make a suggestion...
I have noticed that while working on a project. the Scene Tree that holds all the nodes in a project gets pretty filled up and convoluted. Thus making it a little difficult to keep track of where you have put certain code and in which nodes you have put them. 

May I suggest a way to create folders in the scene tree to better organize which nodes are being used for what. Any nodes that would be put in these folders should not have to include the folders as part of any paths. The folders should only be for better organization for the developer and nothing more?

I think this would be very beneficial to everyone.!

Please?

**Comment by akien-mga** [comment]
The recommended approach is to use basic nodes as folders, e.g. `Node`, or `Node2D` or `Spatial` if you need to retain the parent node's transform.

Those do get added to the NodePath contrarily to the folders you suggest, but IMO if there were non-node folders implemented, I would likely want them to be part of the node path too for better organization of the code, so I think the existing Node-based approach works quite well.

**Comment by isaacremnant** [comment]
You might not be using scenes and instancing to their full potential if your scenes are too big. For example, levels should be instancing enemies and objects that are their own scenes, you shouldn't "see" more structure than what you need, especially not if the structure is reused elsewhere.

Here's an example, the level is quite complex but the tree organization has the folder structure you're looking for. I only ever expand the nodes I need to work with.
![SceneTree](https://user-images.githubusercontent.com/35355161/64039077-d0472f80-cb27-11e9-89e1-fef59b2da357.png)

**Comment by dalexeev** [comment]
This is probably difficult to implement, but it would be useful to be able to mark a node as intermediate. For example, it is often necessary to create large trees using `HBoxContainer`, `VBoxContainer`, `MarginContainer`. This creates paths like `MC/HBC/MC/VBC/Label`. It is especially inconvenient when you have to change the hierarchy of containers.

The only convenient solution that works now:

```gdscript
export(NodePath) var _label
onready var label = get_node(_label)
```

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
