### ISSUE TITLE
please allow resizing controls in containers

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#31813]
please allow resizing controls in container controls.
most of the time controls are not sized properly in containers.
allowing people to edit the size and position of containing items would make godot so much nicer.

Godot version: 3.1.1

**Comment by KoBeWi** [comment]
You can use `rect_min_size` to have a better control of the size. There are also `size_flags`. Containers are there to set the size automatically, so it makes no sense to get in their way.

**Comment by Shadowblitz16** [comment]
I don't want to have to mess with minsize I would like to be able to drag the edges to the desired rectangle or set the rectangle itself through the properties editor.

**Comment by akien-mga** [comment]
Use a Panel then I guess, if you don't want it to be a container?

**Comment by groud** [comment]
That's not how things work. Containers compute the size of their children, and this is not going to change, as this is what they are useful for. However, most containers use their children size flags and computed minimum size to compute this positioning.

If you need to resize a child of a container, you can set the rect_min_size property to eventually override this computed minimum size.

**Comment by groud** [comment]
> I don't want to have to mess with minsize I would like to be able to drag the edges to the desired rectangle or set the rectangle itself through the properties editor.

As this is not a common use case, providing a way to modify the rect_min_size on the editor will lead a lot of people to mess with their children of container's minimum size. This would cause more harm than good.

**Comment by KoBeWi** [comment]
Worth to mention that it was previously possible, but not intended and was bugged, because containers override the size anyways.

**Comment by Xrayez** [comment]
I use(d) `sort_children` signal for overriding (or rather adding upon) final properties of controls (including size), but this must be done via code.

> allowing people to edit the size and position of containing items would make godot so much nicer

I think what you're describing could be done by adjusting custom margin/separation properties.

**Comment by Shadowblitz16** [comment]
well at least let use drag the borders and treat them as min size.

**Comment by girng** [comment]
Might be using the wrong node, Shadow.   FWIW,  there is a `Creating custom Containers` section [here](https://docs.godotengine.org/en/3.1/tutorials/gui/gui_containers.html#doc-gui-containers) that might help

**Comment by groud** [comment]
> well at least let use drag the borders and treat them as min size.

As I said, this will what I want to avoid. Your use case is pretty rare, and allowing user to change the min size visually will create a lot of confusion.
So I don't think it is a good idea, modifying the min size in the inspector is sufficient for this use case.

**Comment by Shadowblitz16** [comment]
currently its a pain to figure out how to edit the size of controls in containers so I would disagree.
there needs to be some easier way to just drag them to where you need them.

**Comment by groud** [comment]
> currently its a pain to figure out how to edit the size of controls in containers so I would disagree.
there needs to be some easier way to just drag them to where you need them.

If you need to precisely position and resize control nodes, you should use the anchor and margins workflow, not the container one. Containers are meant to compute their children position and size, so if you want precise positioning you should not use them.

**Comment by Shadowblitz16** [comment]
I made this issue because my control were going out of the bounds of containers in the first place and I didn't have a way to resize them easily. 

I still think there needs to be a clearer way to resize controls in containers.
for example what if the control has a inherited min size that exceeds the bounds of the container?

it would just be easier to drag the controls to the desired position and size.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
