### ISSUE TITLE
allow process and other hooks to be yielded

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#31846]
please allow process and other hooks to be yielded.

basicly the idea behind this is that the process would either be yielded for x or a function in process would be yielded for x and process would continue running depending on where you yield.

this would make things like ai easier to make but overall **it would just be nice to not limit the user to certain events**.

for example I am trying to make a control flash on and off every x seconds when it is focused.

```
func _process(delta):
	flash(get_focus_owner(), 1);	
	
func flash(obj, spd):
	if (obj == null): return;
	yield(get_tree().create_timer(spd), "timeout");
	obj.modulate = Color(obj.modulate.r,obj.modulate.g,obj.modulate.b,0);
	yield(get_tree().create_timer(spd), "timeout");
	obj.modulate = Color(obj.modulate.r,obj.modulate.g,obj.modulate.b,1);
```

**Comment by girng** [comment]
```
extends Button

func _process(delta):
	flash(get_focus_owner(), 1)
	
func flash(obj, spd):
	if (obj == null):
		print(OS.get_ticks_msec())
		return
	
	print("creating yields%s" % OS.get_ticks_msec())
	yield(get_tree().create_timer(spd), "timeout")
	obj.modulate = Color(obj.modulate.r,obj.modulate.g,obj.modulate.b,0)
	yield(get_tree().create_timer(spd), "timeout")
	obj.modulate = Color(obj.modulate.r,obj.modulate.g,obj.modulate.b,1)
	print("e%s" % OS.get_ticks_msec())
```

this should help you with what your code is actually doing

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
