### ISSUE TITLE
Panel dock position is not saved or loaded

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#3186]
I changed panel(Scene, FileSystem, Inspector) position and close editor.
when open project again, all settings go default.

tested with 0ed864d876347841d60797773a37c0b2f235c85c on Unbuntu 14.04 and Windows 7

And Settings > Editor Layout > Save Layout > Save button doesn't work also.
I don't know what this for, I can see just save, delete & default. no load.

**Comment by neikeq** [comment]
#3187 fixes _"Settings > Editor Layout > Save Layout > Save button doesn't work also."_

The second issue seems to be an issue with ConfigFile. It's probably related to the new VariantParser.
ConfigFile is saved fine, but loading seems to be broken. The same happens when loading the saved layouts. You will probably only see the first one in the list, and with wrong values...

**Comment by volzhs** [comment]
I found something.
When tried to change layout, ``rename error`` is occured.
I saw ``editor_layout.cfg`` and ``editor_layout.cfg.tmp`` file.
``editor_layout.cfg.tmp`` has proper changed values.
So, I tried to delete ``editor_layout.cfg`` file manually with file explorer.
Then it says file is in use so can't be deleted.
I can't delete this file until quit editor.

**Comment by reduz** [comment]
can you try this again? i think it should be fixed

**Comment by neikeq** [comment]
Yes, it's fixed :)

**Comment by volzhs** [comment]
It's fixed now. :+1:
