### ISSUE TITLE
Feature: OS.get_version to get OS version string

### ISSUE THREAD

**Issue by fogine** [godotengine/godot#31895]
**Godot version:**

`3.1.1`

**Issue description:**

There should be a way to get platform specific `OS` version... 

Proposed API:
```
OS.get_version()
```

There seem to be no workaround for `iOS` devices (without creating a native module) as to my knowledge its only possible to access this information programmatically via `Swift`/`Objective C`..

**Comment by bojidar-bg** [comment]
What would `get_version()` return? The native version string such as `4.4` for android, or something containing the platform as well (such as `Android 4.4` or `iOS 3.4.2`)?

**Comment by fogine** [comment]
@bojidar-bg 
I think the good idea is for it to return full version string only without platform as there is already  [OS.get_name](https://docs.godotengine.org/en/3.1/classes/class_os.html#class-os-method-get-name) method.

**Comment by akien-mga** [comment]
>  I think the good idea is for it to return full version string only without platform as there is already OS.get_name method.

That's not really sufficient as `OS.get_name()` returns `Linux/X11` on linux distros, so you still need to know which distro that is, e.g.:
```
$ cat /etc/release 
Mageia release 7 (Official) for x86_64
```

**Comment by bojidar-bg** [comment]
On Linux, I would expect `get_version` to give me the kernel version; distribution should be listed as well though.

**Comment by fogine** [comment]
Some linux distros dont even have a version, like `Arch Linux` in that case I'd consider  `Arch Linux` (from `os_release`) as a linux version.. I think, given the diversity, `get_version` could return strictly formated composed string eg. `distro_name + version_if_any`...

`uname -a` gives me  
`Linux archlaptop 5.2.11-arch1-1-ARCH #1 SMP PREEMPT Thu Aug 29 08:09:36 UTC 2019 x86_64 GNU/Linux`

which is not really helpful to get from higher level API in gdscript..

**Comment by zaksnet** [comment]
On Windows, Mac, IOS and android it can just return the version number, for windows for example:

- Windows XP: "NT 5.1"
- Windows Vista: "NT 6.0"
- Windows 7: "NT 6.1"
- Windows 8: "NT 6.2"
- Windows 8.1: "NT 6.3"
- Windows 10: "NT 10.0"

Mac:

- El Capitan: 10.11.0

IOS:

- 4.3, 6.1 etc.

Android:

- Android Marshmallow: 6.0 to 6.0.1
- Android Nougat: 7.0 to 7.1
- Android Oreo: 8.0 to 8.1
- Android Pie: 9.0

The returned value should be the float value of the version so that you can easily compare it.

**Comment by bojidar-bg** [comment]
> The returned value should be the float value

Nope. It would be better to have it similar `Engine.get_version_info()`, containing major, minor, and patch versions as integers.

**Comment by zaksnet** [comment]
> > The returned value should be the float value
> 
> Nope. It would be better to have it similar `Engine.get_version_info()`, containing major, minor, and patch versions as integers.

But, what is the point of returns the full string of the version? What is the use case of it? If for example, you want to compare it and do some action depending on the version number, you'd have to remove the text and possible do more unnecessary actions. Maybe, return an array for all platforms with `os_name`, `os_version` etc..

**Comment by TimHu6001** [comment]
Hi,

Is there any update on this effort?

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
