### ISSUE TITLE
Image.load not work on Android

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#31918]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

I want to load an image and resize it, so I create the following function, but, image.load(image_file) return 19 on Android device. It's return 0 on Mac. 
func set_image_file(value):
	image_file = value
	var texture = ImageTexture.new()
	
	var image = Image.new()
	print(image.load(image_file))
	var size = $TextureRect.rect_size
	image.resize(size.x, size.y)
	
	texture.create_from_image(image)
	
	$TextureRect.texture = texture

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by puthre** [comment]
Make sure the image is not imported as texture.

**Comment by alexzheng** [comment]
What should be imported as?

**Comment by puthre** [comment]
> What should be imported as?

It should be imported as Image. I had this issue numerous times in the past. If you import it as texture it seems to work on desktop but it will not work on android.

**Comment by akien-mga** [comment]
Textures are imported as platform-specific compressed formats in `.import`. When you export the project, the original .png file is not exported as it's not necessary, given that the game will use the compressed format.

But if you want to load it manually, you should use `load()`/`ResourceLoader` and not `Image.load()` (the latter likely shows a warning BTW), so that it takes the remapping from `res://whatever.png` to its imported version in `res://.import/`).

So something like:
```gdscript
var tex : Texture = load("res://mytexture.png")
var img_data : Image = tex.get_data()
// do stuff to the img_data
var new_tex = Texture.new()
new_tex.create_from_data(img_data)
```

Or if you don't plan to use the PNG as a `Texture` but only as raw `Image` data, then yeah, import it as Image as advised by @puthre.

**Comment by akien-mga** [comment]
BTW it's not related to Android, but to exported projects. You should have the same behavior if you run the exported version on your host OS.

**Comment by alexzheng** [comment]
However, this way can not resize the texture to any size.

**Comment by akien-mga** [comment]
Why not? In my example, you can call `img_data.resize()` like in your original post.

**Comment by alexzheng** [comment]
My problem is the jpg file, my original code can also work with the png, but do not work with jpg image, your code has the same result.
