### ISSUE TITLE
Restructure AnimatedSprite editor icons

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#31963]
**Godot version:**

3.1

**Issue description:**

I keep clicking on delete animation, when it want to delete a frame instead.

Animation and  frame tools need to be cleanly seperated from one another.

Additionally frames should be drag and dropable, instead of requiring the move frame buttons on the right.

Rough example if what it could be
![image](https://user-images.githubusercontent.com/44248915/64272165-0b3dce80-cf3f-11e9-9663-f57a045107f4.png)

**Comment by tom-jk** [comment]
State of issue: both requests have since been fulfilled.

**Improved icon arrangement**
![Godot31963](https://user-images.githubusercontent.com/64640811/89297363-9ea1e700-d65b-11ea-942b-38183ede663f.png)
_3.1.1 vs 3.2.3.rc3_

**Drag and drop reordering**
Is implemented.

Further improvements may be possible but the issue as given is resolved.

**Comment by Calinou** [comment]
Closing as resolved per @tom-jk's comment. Please open a [proposal](https://github.com/godotengine/godot-proposals) if something else should still be added or changed.
