### ISSUE TITLE
C# Threading in Tool mode crashing the editor

### ISSUE THREAD

**Issue by websterek** [godotengine/godot#31968]
**Godot version:**
 Godot_v3.1.1-stable_mono

**OS/device including version:**
WIndows 10 x64

**Issue description:**
Threading function in C# (in both variants: system.threading and Godot threading), when used in Tool mode, crashes Editor.

Godot output after crash:
```
Unhandled Exception:
System.Threading.ThreadStateException: Thread has already been started.
  at (wrapper managed-to-native) System.Threading.Thread.Thread_internal(System.Threading.Thread,System.MulticastDelegate)
  at System.Threading.Thread.StartInternal (System.Security.Principal.IPrincipal principal, System.Threading.StackCrawlMark& stackMark) [0x0001a] in <52405d1838e24bc5b300f5ebeee9f7c4>:0
  at System.Threading.Thread.Start (System.Threading.StackCrawlMark& stackMark) [0x00028] in <52405d1838e24bc5b300f5ebeee9f7c4>:0
  at System.Threading.Thread.Start () [0x00002] in <52405d1838e24bc5b300f5ebeee9f7c4>:0
  at Node2D._Process (System.Single delta) [0x00001] in C:\Projects\Godot C#\Node2D.cs:13
```

**Steps to reproduce:**
Just try to Thread some function in Editor Tool mode

**Minimal reproduction project:**
[Godot C#.zip](https://github.com/godotengine/godot/files/3575797/Godot.C.zip)
Running Node2D.tscn crashes Editor immidietly. Node2D.cs has threading function using System.Threading

**Comment by Zylann** [comment]
```cs
    System.Threading.Thread thr = new System.Threading.Thread(new System.Threading.ThreadStart(test_func));

    public override void _Ready()
    {
    thr.Start();
```
I see two thread starts here. You are then getting `ThreadStateException: Thread has already been started.`, I think that makes sense.

**Comment by akien-mga** [comment]
I can't reproduce a crash on Linux with 3.2 RC 2, so this may have been fixed.

The Unhandled Exceptions are still triggered though.

> ```cs
>     System.Threading.Thread thr = new System.Threading.Thread(new System.Threading.ThreadStart(test_func));
> 
>     public override void _Ready()
>     {
>     thr.Start();
> ```
> 
> I see two thread starts here. You are then getting `ThreadStateException: Thread has already been started.`, I think that makes sense.

Is that really two threads? Looking at https://www.mono-project.com/archived/threadsbeginnersguide/#threads-in-action, it seems to be the way threads are constructed.

However moving the `thr` declaration in `_Ready()` fixes the issue:
```csharp
	public override void _Ready()
	{
		System.Threading.Thread thr = new System.Threading.Thread(new System.Threading.ThreadStart(test_func));
		thr.Start();
	}
```

**Comment by neikeq** [comment]
First a few clarifications:
1. There's only one thread instance being started in the reproduction project. `ThreadStart` is a delegate, so `new Thread(new ThreadStart(threadCallbackFunc))` is the same as `new Thread(threadCallbackFunc)`.
2. As of 8759c0e31a21d9f98ac24ac4c88fa86bd72ff68f, we `exit` instead of `abort`ing when there's an unhandled exception. That's why I'm removing the `crash` label.
3. As of 513cc78f85d8c45a9492ae25034cd2357714cfdf, the editor no longer terminates when there's an unhandled exception. It only logs the exception. That's why the "crash" is no longer reproducible, but the exception is still there.

Now about the reproduction project. It includes the prebuilt project assemblies in `.mono/temp/bin/Tools`. These prebuilt assemblies seem to be from an older version which was calling `thr.Start()` from `_Process` instead of `_Ready`. That's people were able to reproduce the exception with it, you were trying to start the same thread repeatedly every frame.
I rebuilt the project with the same sources included in the reproduction project (which start the thread in `_Ready`) and there were no more exceptions.
So I think OP @websterek may have forgot to rebuild the project after moving `thr.Start()` from `_Process` to `_Ready`.

**Comment by neikeq** [comment]
Just for completeness, running ikdasm on the prebuilt assembly in the reproduction project confirms what I said above:

```
.method public hidebysig virtual instance void 
          _Process(float32 delta) cil managed
  {
    // Code size       14 (0xe)
    .maxstack  8
    IL_0000:  nop
    IL_0001:  ldarg.0
    IL_0002:  ldfld      [mscorlib]System.Threading.Thread Node2D::thr
    IL_0007:  callvirt   instance void [mscorlib]System.Threading.Thread::Start()
    IL_000c:  nop
    IL_000d:  ret
  } // end of method Node2D::_Process
```

It's calling `thr.Start()` inside `_Process`.
