### ISSUE TITLE
Mouse grab error when modifying a slider/spinbox min/max values by dragging

### ISSUE THREAD

**Issue by hetdegon** [godotengine/godot#3196]
Since a few commits ago, and still existing in be1f2a0, trying to modify the value of certain editor spinboxes in the inspector by click-dragging mouse over the value, will do something weird with the mouse. Instead of modifying the value and releasing the mouse when the mouse button is released, it'll prematurely stop modifying the spinbox and the mouse will be released, but the cursor will remain hidden, and it will return to the position of the edited spinbox in regular intervals.

The only way to restore the mouse cursor in the editor is to close everything and reopen. This can be detrimental as undo buffers can be lost. Fortunately, the scene can still be saved and exited with the keyboard. Alt+tabbing out of the editor shows the mouse cursor again, but returning to the editor will hide it immediately.

I am not entirely sure, but seems it's more likely to happen when the spinbox has decimal values, with integer ones, at least the ones I use frequently, can be modified in this fashion with no issues.

System is Ubuntu 15.10 64b, KDE desktop (kwin 5). I haven't tried to reproduce in other OSs or windowing systems at the time, but if no one else can reproduce the issue it could be something to check.

**Comment by neikeq** [comment]
I can confirm this bug on df5fa62. It happens only with certain properties, like Spinbox's min/max range in this case.

I noticed this bug while working on #3019, which forced me to limit the PR a bit. But I thought it was a normal behaviour.

The problem seems to be with [this condition](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L1414) IIRC. The method will be recursively called once this condition is true, which mean it got to the row the mouse is hovering. The problem is that, for some reason, the condition is true before getting to this row. In the case of Spinbox, it returns true for the second _Range_ row in the image IIRC (or was it the first one? :confused:):

![captura de pantalla de 2016-01-02 13 34 27](https://cloud.githubusercontent.com/assets/7718100/12074460/94dd34b6-b155-11e5-84be-9c0b0b24b73d.png)

**Comment by neikeq** [comment]
Please, ignore the crossed part of my last comment. The bug has nothing to do with that.

The problem seems to be that for some reason [the TreeItem destructor](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L720-L747) is called, and sets `pressing_for_editor` to _false_. This shouldn't happen because, the next time the mouse is released, [this condition](https://github.com/godotengine/godot/blob/master/scene/gui/tree.cpp#L2163) will be false and the mouse won't be released.

**Comment by reduz** [comment]
yeah because some properties ask for redrawing the entire property list, so the whole thing is cleared. I wonder how we can workaround it? I was thinking of saving the path of the item and, if gone, search for it again..

**Comment by Zylann** [comment]
This just happened again for me in 3.0 beta 1, dragging SpatialMaterial/Rim/Tint.
