### ISSUE TITLE
Can't use type hints with _process_custom_fx

### ISSUE THREAD

**Issue by somnivore** [godotengine/godot#31973]
**Godot version:**
aadbb66dc23d547393bc220e1f36b56cf10f5cca

**OS/device including version:**
ArcoLinux

**Issue description:**
This function expects two things: `CustomFXChar`, a type which doesn't appear to exist (I believe it's meant to be `CharFXTransform`), and `int` return type, where, according to the PR, you're intended to return a bool.  So, the only way it works is if you leave type hints off.

`func _process_custom_fx(char_fx: CharFXTransform) -> int:`
![image](https://user-images.githubusercontent.com/28724859/64285824-f1da5980-cf21-11e9-9c00-4ab29d829718.png)

`func _process_custom_fx(char_fx: CustomFXChar) -> int:`
![image](https://user-images.githubusercontent.com/28724859/64285848-fb63c180-cf21-11e9-9615-79de4857ebaa.png)

**Comment by LinuxUserGD** [comment]
And it generates an error when compiling with mono on Linux or cross-compiling on Linux for Windows with mono:
```Swift
 ObjectType/RichTextEffect.cs(22,45): error CS0246: The type or namespace name 'CustomFXChar' could not be found (are you missing a using directive or an assembly reference?) [/run/media/user/user/git/godot/modules/mono/glue/Managed/Generated/GodotSharp/GodotSharp.csproj]
```

**Comment by RisaI** [comment]
Can confirm this breaks MSBuild, beacause it can't find the `CustomFXChar` class. I'm reverting to d2900347bf0586879df856e807858178d3bde5f4 for now.

**Comment by akien-mga** [comment]
CC @Eoin-ONeill-Yokai

**Comment by Eoin-ONeill-Yokai** [comment]
Alright I've taken a look at this and it was the result of a refactor gone awry. You should now be able to define a function that looks like the following:
```
tool extends RichTextEffect
class_name RichTextGhost

var bbcode = "ghost"

func _init():
	resource_name = "RichTextGhost"

func _process_custom_fx(char_fx: CharFXTransform) -> bool:
	
	var speed = char_fx.get_value_or("freq", 5.0)
	var span = char_fx.get_value_or("span", 10.0)
	
	var alpha = sin(char_fx.elapsed_time * speed + (char_fx.absolute_index / span)) * 0.5 + 0.5
	char_fx.color.a = alpha
	return true;
```

It should have always been CharFXTransform with a bool return, but I lost that at some point along the way due to a refactoring bug (It was using an old behavior where I allowed specific error codes, which is no longer necessary.) Thanks for taking the time to test out the new feature and hopefully it works better with this new patch. With regards to mono, if you still have the bug even after this patch, report again and I will investigate.
