### ISSUE TITLE
Script Editor opens class reference while still selecting text

### ISSUE THREAD

**Issue by deviousdaemon** [godotengine/godot#32070]
**Godot version:**
3.2.dev 00aabec8b

**OS/device including version:**
Windows 10 1809

**Issue description:**
In the Script Editor,  if I select text, hold control, and then release the mouse button while still holding control, the Class Reference will open to what ever text was being selected.

Example, you select the text "set_process", and, while pressing and holding CTRL, release the mouse button, the Node Class Reference will open.

This issue is not present in the current 3.1.1 stable version

**Steps to reproduce:**
Select text in the Script Editor that can be open in the Class Reference, and while holding down CTRL, release the mouse button.

**Minimal reproduction project:**
Any project I've created or edited shows this behavior.

PS. This is the first issue I've created, so please forgive any mistakes that may have been made.

**Comment by KoBeWi** [comment]
This is expected behavior. Ctrl + Click was changed to work on button release, to avoid accidental text selection when going to definition.

However I see another problem here. The reference opens for anything you release the button at, even if it's not what you originally clicked. That would be a bug.
