### ISSUE TITLE
Invalid Tile origin when set as Center

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#3209]
You can recreate this bug with the Kinematic Collision demo:
- Set the TileMap's _Cell_->_Tile Origin_ property to _Center_.
- Select the tile and compare its preview origin to the added tiles origin.

You should see something like this:
![vs4itdo](https://cloud.githubusercontent.com/assets/7718100/12076884/7926d25c-b1c0-11e5-88cb-e0a89bc3f29e.png)

The origin for the added tile is different than the preview's. I am not sure if the preview is the right one or if it should be like this:

![igg](https://cloud.githubusercontent.com/assets/7718100/12076920/42f957fc-b1c2-11e5-94c1-d46c74432624.png)

**Comment by neikeq** [comment]
Ok, I will assume the preview the the expected behaviour. I'll make a PR when I get some time.

**Comment by akien-mga** [comment]
I guess *Tile Origin->Center* means the tile should be centered on the origin, i.e. the top-left corner, no? So in such a case the preview would be wrong I guess?

There is a lot to clarify in all those tile origin/offset features for TileMap (and maybe GridMap). The previous fix we had before 2.0 broke many existing games with non-square flipped tiles (e.g. Jetpaca), and apparently also the hexamap demo (#4206).

There are still inconsistencies and non-working features IMO, so we need to establish clearly how it should behave, fix it, and make it clear in the release notes if it has the potential to break existing games (and if the breakage is too important, we might have to wait for 3.0 or even live with a flawed implementation).

**Comment by neikeq** [comment]
Also it would be good to use the same code for both actual drawing and preview drawing, or at least make both look implementations look the most similar possible.

**Comment by akien-mga** [comment]
Potentially related to #2513.

**Comment by neikeq** [comment]
@akien-mga This doesn't look critical for the 2.1 milestone. It is been like this for a while (if not since 1.0) and not many people cared.

**Comment by akien-mga** [comment]
What's the status on this in the current master branch? If there is still an inconsistency, it's now or never to fix it by breaking compatibility.

**Comment by hoelzl** [comment]
As far as I can tell from playing around with a simple tileset, in the master branch Tile Origin Center does essentially the same thing as Tile Origin Top Left. 

From looking at the implementation: The important internal data structure has type Quadrant.  This Quadrant is computed in a different way for the different values of Tile Origin. With Tile Origin Center the computation of the Quadrant takes into account the cell size, as well as the size of the tile's texture or region, depending on whether the region is a rectangle or not. Possibly also some other values that I've overlooked right now, because the code is rather convoluted. In addition, the treatment of mirroring is different between Tile Origin Center and Tile Origin Top Left.

Since I have no idea which part of the implementation provides useful behavior and which part is wrong I'm not sure how to fix the Tile Origin issue unless somebody can give more specific instructions what the intended behavior is. However, I think it would be possible to modify tile maps in a way that makes the behavior clearer and more general at the same time:

- Replace the Tile Origin as it is currently implemented with a Vector2 Tile Offset that allows positioning the tiles relative to the tile map. This would take care of positioning tile sets that have a different size in the map, e.g., isometric tile sets that place 256x159 tiles into a 256x512 grid (such as Kenney's Dungeon Pack). As such it would fulfill the role of Tile Origin Top Left or Bottom Left. It would also allow centering the tile set in either or both directions.

- Always perform tile rotation and mirroring around the center of the cell, after applying the Tile Offset. I think that this is what the current code does in many cases.

This solution seems to be similar to how editors such as Tiled handle tile sets. If it is really necessary to mirror or rotate tiles around a different point than the center of the cell, I'd propose adding another parameter, say Tile Pivot, that is responsible for shifting the center of rotation only. This would, e.g., allow rotating isometric tiles such as the ones mentioned above so that tiles rotated by 180 degrees fit next to unrotated ones. I find it difficult to justify the need for this, however, since in my experience isometric tiles look wrong when they are rotated, even if it is possible to align them.

Since I'm not a 2D game developer it's possible that I'm missing something that Tile Origin achieves that my proposed solution would not allow. But I hope that this proposal would cover most use cases (in particular since you can adjust offsets for individual tiles in a tile set), simplify the implementation, and be easier to explain in tutorials than the current solution.
