### ISSUE TITLE
Theme editor opens itself on scene save

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32107]
**Godot version:**
4ee8ecd

**Issue description:**
When a Control node has a Theme resource and the resource is unfolded in the inspector, the Theme Editor dock will open each time you save the scene. IMO it should only open when interacting with the theme. I had it open in the script editor until I realized I need to fold the Theme resource.

**Steps to reproduce:**
1. Create a Control node
2. Create some Theme resource for the node
3. Unfold the new resource
4. Close the "Theme" dock and go somewhere else (like Console, Script Editor etc.)
5. Save
6. Theme dock opens itself

**Comment by tom-jk** [comment]
Testing on linux mint 18.3.
Tried in several versions of Godot between 3.0 and 3.2.3.rc3, haven't been able to reproduce this.

There were some versions where the theme dock and the output dock would stack vertically (eg. 3.1.1), and since at least 3.1 the theme dock will open if you choose a different dock, switch to another scene, then switch back (though since 3.2 when you do the theme in the inspector will be rolled up, so if you repeat the switch the theme dock won't appear the second time).

But I can't get it to open on save. Maybe it requires some project/editor setting?

**Comment by KoBeWi** [comment]
I can't reproduce it anymore, so let's just close.
