### ISSUE TITLE
Version control window lists all global classes

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#32122]
**Godot version:**
3.2-alpha, 24e1039

**OS/device including version:**
Windows 10

**Issue description:**
When attempting to select a VCS, all global classes exposed via `class_name` are listed regardless:

![vsc_global_classes](https://user-images.githubusercontent.com/17108460/64863808-64dc8200-d63e-11e9-90d1-207104e0dea1.png)

**Steps to reproduce:**
1. Create global classes with `class_name`
2. Go to `Project` → `Version Control` → `Set Up Version Control`
3. See all classes listed in the project.

**Minimal reproduction project:**
[vcs-global-classes.zip](https://github.com/godotengine/godot/files/3610089/vcs-global-classes.zip)

**Comment by Calinou** [comment]
I can confirm this on commit https://github.com/godotengine/godot/commit/24e1039eb6fe32115e8d1a62a84965e9be19a2ed.

![image](https://user-images.githubusercontent.com/180032/64866085-0d88e280-d63b-11e9-8c6a-ea1fac9a31f4.png)

**Comment by Zylann** [comment]
I wonder what kind of VCS `Select an available VCS` is

**Comment by Xrayez** [comment]
Likely this [Git plugin](https://github.com/godotengine/godot-git-plugin), so CC @IronicallySerious I guess.

**Comment by IronicallySerious** [comment]
The "Select an available VCS" refers to a GDNative object placed in the project folder that extends [EditorVCSInterface](https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/editor/editor_vcs_interface.h#L38). @Zylann 	
To use the integration you will have to extract [this .zip file](https://github.com/godotengine/godot-git-plugin/releases/tag/v1.0-alpha) in your project folder.

Right now it lists all global scripts available because since the VCS integration is new, I kept things as simple as possible. I would expect the dialogue box to raise an error in the output if you selected a script that is not the Git plugin so the VCS functionality stays hidden.

I would probably fix in this line here: https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/editor/plugins/version_control_editor_plugin.cpp#L384

I can get this done after Monday because of my exams, but if someone is interested they can have a look. If we are able to detect what class a GDNative plugin extends then it is a simple if statement because all VCS plugins will extend [EditorVCSInterface](https://github.com/godotengine/godot/blob/24e1039eb6fe32115e8d1a62a84965e9be19a2ed/editor/editor_vcs_interface.h#L38)
