### ISSUE TITLE
Add bitcoin or ethereum payment

### ISSUE THREAD

**Issue by JosiasAurel** [godotengine/godot#32130]
Hi
I thought about if it was possible or a good idea to add a possibility or a function or node in the Godot engine to include cryptocurrency payment like bitcoin for in-app purchases in your game. Even do I'd think it could have been weird if it was done I will be happy else if it can't I will contempt myself with the existing options. Thanks.

**Comment by Chaosus** [comment]
You should create feature proposals in a specific repo - https://github.com/godotengine/godot-proposals/ (and make them correctly formed using this template https://github.com/godotengine/godot-proposals/blob/master/.github/ISSUE_TEMPLATE/feature---enhacement-proposal.md). Otherwise this is inappropriate of our quality barrier. Closed.

**Comment by JosiasAurel** [comment]
Thanks for informing

**Comment by martijnbolt** [comment]
I've created something along the lines of your request for the time being. Maybe you're interested: http://www.insert-coins.org

**Comment by JosiasAurel** [comment]
Oh thanks much I'll check it out.
