### ISSUE TITLE
Error GLES2 automatic.

### ISSUE THREAD

**Issue by marianokpo** [godotengine/godot#32141]
On some older equipment, it would be ideal if they do not have GLES3 automatically start with GLES2 and GLES3 cannot be selected in the project creation part.

for example:

If you give an exception when loading the controller with GLES3 automatically use the GLES2 and store in a variable that the engine started with GLES2 and when the user wants to create his project by default does not allow to create one with GLES3.

In this way we could avoid having to search the internet because the engine does not work on old machines and is easy for the user who is starting in godot.

this only happened to me on windows 7 with intel hd 4000 video card.

At the moment, I personally use the "Godot_v3.1.1-stable_win64.exe --video-driver GLES2" command to work on older computers.

From already thank you very much.

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
