### ISSUE TITLE
CSGPolygon following path can't be scaled

### ISSUE THREAD

**Issue by kb173** [godotengine/godot#32171]
**Godot version:**
3.1.1

**Issue description:**
I have a CSGPolygon with a PoolVector2Array polygon, which is extruded along a path. I would like to generically resize that polygon without having to know its exact points (different types of streets with different widths). I had expected to be able to do this by setting the 'Scale' parameter in its Transform.

However, the scale entered in the CSGPolygon's Transform is only visible until a different node is selected; then is resets (only visually - the different value is still in the Transform). For the short moment where the scale is visible, it doesn't actually scale the polygon, but the whole mesh extruded along the path. This is the result I would expect when scaling the path, not the polygon.

If this is intended, I think it should be communicated better (warning in the editor and note in the docs). I hope it isn't, though, since I can't find another way of rescaling the CSGPolygon without knowing its exact polygon.

**Comment by MathiasBaumgartinger** [comment]
I highly support this problem. It feels highly unintuitive in it's current state.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
