### ISSUE TITLE
Error spam after removing CollisionShape2D via undo

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#32208]
**Godot version:**
2add51d

**Issue description:**
When you remove CollisionShape2D (with Shape2D resource) using undo action, you will get spammed in the console when moving cursor inside viewport, until you select another node.
```
 scene/2d/canvas_item.cpp:478 - Condition ' !is_inside_tree() ' is true. returned: get_transform()
```

Somewhat similar to #15515

**Steps to reproduce:**
1. Create a 2D scene
2. Add a CollisionShape2D node
3. Attach any shape to it
4. Duplicate the node
5. Undo
6. RIP console [*]

**Comment by ThakeeNathees** [comment]
It's because when undoing the duplicate `CollisionShape2D` instance, it would be removed from the scene tree but the `CollisionShape2DEditor` have the reference to that instance ( the instance node is not NULL ) until selecting another `CollisionShape2D` instance. 

While the `CollisionShape2DEditor` has the reference to that instance and when the canvas received a mouse move event the `CollisionShape2DEditor` call `CanvasItem::get_global_transform()` to that instance which leads the error spam as long as moving the mouse.

**Comment by Janglee123** [comment]
Strange, but I can't reproduce this bug!!
