### ISSUE TITLE
Allow a way to block until a signal is emitted

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#3223]
I asked about this in the forums but I couldn't get an answer. I think maybe there is no way to do this currently in godot. I hope it's OK to make an issue about this.

In the [documentation](http://www.godotengine.org/projects/godot-engine/wiki/GDScript#Coroutines-38-Signals), it says:

> The real strength of using yield is when combined with signals. yield can accept two parameters, an object and a signal. When the signal is activated, execution will return.

But this works only if you call yield in a "top-level" function in the GDScript call stack. For example, if I use yield as follows, it doesn't block:

```
# script of the class

var m_param

# return a result from a signal
func get_result():
    # stuff...
    yield(node, "signal")
    # more stuff here...
    return m_param

func signal_callback(param):
    m_param = param
```

When I make an instance of this class and call get_result as follows:
```
# stuff
var result = obj.get_result()
```
it gives me a `GDFunctionState`, not `m_param`.

This is useful for getting input from the user via an input from a GUI control object for example.

I'm not sure if this is a bug in the implementation or the intended behavior but it's a bit confusing. Maybe the docs should be updated to clarify that yield doesn't actually block.

That being said, a blocking alternative to yield is sorely need for the use case I mentioned above.

**Comment by kubecz3k** [comment]
As far as I understand how yield works it's not a bug, but desired behaviour. 
The execution of the function is stopped and if you want to continue it from this point in the future you need to call resume() on GDFunctionState object. If you want to get value of m_param in this case then after  pausing function (read: yielding) just get the m_param itself.
 Still I probably don't understand something since I don't know how you are using resume() function and It's very possible I just don't understand your user-case since I never used anything similar to yield during  input processing,  if this is the case then I'm sorry.

**Comment by kubecz3k** [comment]
Ok, after refreshing myself how yield works I think it's not a bug, but desired behaviour.
The execution of the function is stopped and if you want to continue it from this point in the future you need to call resume() on GDFunctionState object and this resume() will return your m_param.
If you want to get value of m_param in this case then after pausing function (read: yielding) just get the m_param manually.
Still I probably don't understand something since I don't know how if you are using resume().

**Comment by kubecz3k** [comment]
Ok, after refreshing myself how yield works I think it's not a bug, but desired behaviour.
You are running function manually, it get stopped because of yield call. You get GDFunctionState object in return and you can continue execution at any time by calling resume() on your GDFunctionState object. And this resume() will return your m_param variable. Furthermore because of how you yielded your function it's execution additionally will be continued when connected "signal" will be emitted from the "node" object. 
I don't know your user-case and because of that I'm not sure what you want to do, probably there is other way to accomplish this. If I misunderstand something then sorry in advance.

**Comment by tagcup** [comment]
> You are running function manually, it get stopped because of yield call. You get GDFunctionState object in return and you can continue execution at any time by calling resume() on your GDFunctionState object. And this resume() will return your m_param variable. Furthermore because of how you yielded your function it's execution additionally will be continued when connected "signal" will be emitted from the "node" object. 

Yes, this is like the behavior of coroutines. Maybe it's just me but the documentation on the other hand suggests that yield blocks until the signal happens, and that is the use case:

> The real strength of using yield is when combined with signals. yield can accept two parameters, an object and a signal. When the signal is activated, execution will return.

As you described, the execution returns to the calling GDScript function right away, not after the signal is activated.

My use case is I want to implement something similar to yes/no modal window (but not just a yes/no dialogue, I will have more options). I'm simply trying to write a function that will present the modal window and return the user's choice.

Do you think such a thing is possible without a blocking alternative to yield?

**Comment by kubecz3k** [comment]
@tagcup I think you should just define a signal inside your window, something like  (writing from head):

```
signal on_user_choose(chooseID)

#this is a function connected to on_pressed signal of first button  
func on_button_1_pressed():
   self.hide() #or whatever you want to hide your window
   emit_signal(on_user_chose("Choose1");

#this is a function connected to on_pressed signal of second button  
func on_button_2_pressed():
   self.hide() #or whatever you want to hide your window
   emit_signal(on_user_chose("Chose2");

#this is a function connected to on_pressed signal of third button  
func on_button_3_pressed():
   self.hide() #or whatever you want to hide your window
   emit_signal(on_user_chose("Chose3");
```
You can connect this signal normally from the editor to any script that is interested in receiving this info. The connected function will receive a string prameter with one of the values: "Chose1"/"Chose2"/"Chose3"

**Comment by tagcup** [comment]
To be clear about "the execution returns to the calling GDScript function right away, not after the signal is activated":
Right after the yield is called, the program continues from the code which called get_result() in my original post. After the activation of signal, the execution continues inside get_result().

I did try wrapping the yield call as
```
func yield_wrap();
	yield(node, "signal")

func get_result():
	# stuff...
	y = yield_wrap()
	y.resume()
	# more stuff here...
	return m_param
```
but this doesn't block until the signal is activated.

**Comment by tagcup** [comment]
@kubecz3k
Thanks, but I do understand how signals work. Also, I think using `ButtonArray` is probably a better choice that doing it that way, which has the signal `button_selected`:
```
func _on_button_selected(selection):
    # ...
```

Anyway. As I mentioned in my first post, I'm trying to avoid a asynchronous code (which usually turns into a callback spaghetti, eventually). As I already said in my previous code, what I'm trying to write is an ordinary (rather than [future/promise](https://en.wikipedia.org/wiki/Futures_and_promises) and callbacks) function that will present the modal window and return the user's choice.

```
# returns the selected answer
func question_modal(question, answers):
    # function body
```

This allows a flat and simple code. However, I'm afraid this requires a blocking mechanism, which is not available in Godot at the moment.

**Comment by kubecz3k** [comment]
@tagcup Ok, now I understand the issue, it seems the solution you are looking for is not implemented currently... still I'm surprised that when executing. 
```
func ready():
   print("YIELD 1")
   var y = yield_wrap()
   print("YIELD 2")
func yield_wrap():
    yield(node, "signal");
```
both prints are printed on the screen. I'm unable to tell if this is a bug or intended behaviour. @reduz could you take a look at this?

**Comment by tagcup** [comment]
To elaborate on async vs sync: Godot has an extensive UI toolkit, which is clearly seen from the fact that Godot editor is made using it. From my experience with Qt, I understand that callbacks have to be the norm.

But many games have a very simple usage of UI elements. Since game logic is preferably synchronous, introducing asynchronous code just for the sake of adding simple question box can be demanding IMHO.

If Godot implements a blocking version of signal-yield, we won't have to mix asynchronous code with synchronous, and the resulting game logic code (GDScript code) will be simpler and more maintainable.

I'm not sure if wrapping yield like that is supposed to blocking until the signal is completely, of course.

**Comment by kubecz3k** [comment]
@tagcup what about:
```
(...)
1. dialogWindow.show();
2. yield(dialogWindow, "on_user_decision_is_made");
3. var decision = dialogWindow.get_user_decision()
(...)
```
As far as I know in this case third line should be executed only after dialogWindow emit signal "on_user_decision_is_made" .

**Comment by tagcup** [comment]
Right? This is also what I thought after reading the tutorial.
But I essentially have something similar, only it is inside the function:
```
func question_modal(question, answers):
	# stuff ...
	dialogWindow.show();
	yield(dialogWindow, "on_user_decision_is_made");
	var decision = dialogWindow.get_user_decision()
	# more stuff
	return decision
```
And unfortunately, yield() doesn't block here. Instead, it continues execution from the line right after the line question_modal() is called.

**Comment by tagcup** [comment]
In my case, the signal is "button_selected" of course, which is emitted when the user clicks.

**Comment by kubecz3k** [comment]
@tagcup Yeah sure, I'm just throwing around pseudocode since I don't have api in front of my head :)
If using this code outside the 'inner' function is working, then I still think this it's not a bug...  as a documentation said:  _Calling yield() will immediately return from the **current function**_ so it's a rather a lack of the functionality. 
I also think it would be really great to have this in Godot hovewer. I think you should open new feature request and close the current one (to hide this long and not really helpful conversation from the eyes of the core devs :). Sorry for initial misunderstanding, and have a good night. I'm out for today :)

**Comment by tagcup** [comment]
OK, I'll do that later today. Thanks so much for the helpful discussion and understanding!

I think I'll mention [CSP](https://en.wikipedia.org/wiki/Communicating_sequential_processes)-style concurrency, in which blocking channels allows synchronization between coroutines. A blocking yield will be equivalent to that. Of course with channels allow you pass a message along, with blocking yield, the message (in my case, that would be the # of button user clicked) should be passed in a non-atomic way, which is fine in my case.
