### ISSUE TITLE
Hotkey for disabling snapping

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3225]
Sometimes is desirable to disable pixel/grid snapping for a few seconds.
I think there should be a quick key to do that.

When moving the node: press ALT
When scaling the node: press CTRL
When rotating the node: press ALT

**Comment by hetdegon** [comment]
Blender does this and it's really convenient. +1

**Comment by reduz** [comment]
https://github.com/godotengine/godot/blob/master/tools/editor/plugins/canvas_item_editor_plugin.cpp#L3281

What keybinding might work for this? what is a common keybinding for toggling snap that does not conflict with something else we have?

Remember to always use KEY_MASK_CMD instead of KEY_MASK_CNTROL for control when doing keybindings, so this macro converts to meta instead of control when compiling for OSX

**Comment by hetdegon** [comment]
Well, the only example I know is Blender which uses Ctrl to reverse the current snap state (using it with snap on = no snap, using it with snap off = snap). Is that one available?

**Comment by nunodonato** [comment]
I just realized, while looking at the code, that this seems to be working already.
While moving/rotating/resizing, I can hold 'S' to turn snap on, After release it goes back to off.
perhaps just changing 'S' to 'Ctrl' would be better as it is more intuitive?

**Comment by crr0004** [comment]
Using S doesn't work in 2D.

In 3D pressing S will enable snap while moving an object, however pressing, or releasing it won't disable it again.

**Comment by reduz** [comment]
kicking to 3.1 unless anyone wants to do it

**Comment by akien-mga** [comment]
Actually that's the kind of issue which doesn't need a milestone - it's done when it's done :)

**Comment by Chaosus** [comment]
I think the hotkey for snapping is already been existed (for about a year) and it is CTRL. Closed.
