### ISSUE TITLE
Should TileMap.update_bitmask_region() use a Rect2 instead of start/end vectors?

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#32290]
**Godot version:**
3.2 alpha

**Issue description:**
update_bitmask_region uses two vectors, a start and an end. Could this be replaced with a Rect2 for more flexibility?

**Comment by CowThing** [comment]
I don't think it should be replaced, there can be times where you have the starting and ending vectors and in that case it's easier to just use those two instead of having to create a Rect2. Also it's easy to do this with a Rect2, `update_bitmask_region(rect.position, rect.end)`

Perhaps it would be better to add a function `update_bitmask_region_rect(Rect2)`. Similar to how there is `set_cell(x, y)` and `set_cell_v(Vector2)`

**Comment by Jummit** [comment]
Yeah, two vectors is what you're gonna use most of the time anyways. Closing.
