### ISSUE TITLE
[Mono] [Editor] -  Verbatim identifier character causes visual glitch

### ISSUE THREAD

**Issue by piratesephiroth** [godotengine/godot#32336]
**Godot version:**
v3.2 alpha0

**OS/device including version:**
Windows 10 x64

**Issue description:**
The verbatim identifier character glitches up the syntax highlighting, making the remaining of the file appear string-colored.
![image](https://user-images.githubusercontent.com/10672233/65593485-f0bbab80-df66-11e9-919b-5f653c5f72b2.png)

**Steps to reproduce:**
Open a C# script in the editor then write a string, adding an @ in front.

**Minimal reproduction project:**
\-

**Comment by akien-mga** [comment]
There's no support for C# syntax highlighting in the builtin editor that I know of, so that might be expected.

That being said, the same syntax in GDScript is highlighted properly (`@` a shorthand for `NodePath()`):
![Screenshot_20190925_125332](https://user-images.githubusercontent.com/4701338/65594669-8ec56b00-df93-11e9-9616-179dc519acd3.png)

**Comment by piratesephiroth** [comment]
It's funny that only the @ character causes the problem and only while editing C# code.

**Comment by neikeq** [comment]
The reason it only happens with C# is probably because it's configured as a delimiter for this language:

https://github.com/godotengine/godot/blob/edf9055b7f3fb16f9b927d09bc84be31c1076ce7/modules/mono/csharp_script.cpp#L294-L296

Is this just not supported or is it a bug? Maybe I should just remove it as it will work fine, only the `@` won't be highlighted.

**Comment by piratesephiroth** [comment]
It's definitely a bug. Maybe it's the double quotation marks at the end that are stopping it from closing properly?

**Comment by piratesephiroth** [comment]
I thought the error was caused by the string being matched twice so I moved the verbatim one up, to be matched first.
This fixed it but then it stopped the regular strings from being detected 😆.

I guess it can just be disabled then

**Comment by aaronfranke** [comment]
Just saying, you can use forward slashes instead and they work perfectly fine on Windows.

**Comment by piratesephiroth** [comment]
yeah but we use that character so we can write any character without escaping, not only backslashes

**Comment by Calinou** [comment]
I think we should just remove the dedicated highlighting for verbatim string literals until we figure out a way to fix it.

**Comment by piratesephiroth** [comment]
yep, at least it doesn't break the highlighting of everything
