### ISSUE TITLE
RichTextLabel's Item and Item* structs should not inherit Object, it's too expensive

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#32347]
**Godot version:**
3.2 master (e426169e4ce8cbb0a8c0fb04f75e60976058177e)

**OS/device including version:**
All

**Issue description:**
#23658 changed `RichTextLabel`'s `struct Item` to an `Object`-derived class (and thus all other `Item*` structs that derive from it, including `ItemFX` and its own inheriting structs).

Then #32202 changed the classes inheriting `Item` to also be `Object` and use `GDCLASS()` to fix casting issues.

@reduz says that it's a bad idea and will have a significant performance impact, as `Object` is quite expensive:
```
16:07 <Akien> Next: #32299
16:07 <IssueBot> #32299: fix area2d monitorable changes | https://git.io/JesFq
16:08 <Akien> reduz: We've had quite a few PRs like this lately where people need to `dynamic_cast` a non-Object class or a struct, and so far we've worked this around by making them Object to use Object::cast_to
16:09 <Akien> Is that the right approach? Another example (merged): #32202
16:09 <IssueBot> #32202: Fix crash on some platforms in RichTextLabel. | https://git.io/Je3Gq
16:10 <reduz> Akien: in those cases there is usually an enum where you can ask what it is
16:10 <reduz> Akien: if not, i suppose it could be added
16:11 <reduz> Akien: oh yeah that is a terrible idea, that will send the performance down the sewer
16:11 <reduz> Akien: ask people to use an enum and check the enum, dont ask them to use Object derived classes
16:11 <reduz> Akien: so yes, that PR will need to be reverted
16:12 <reduz> Object is way too expensive to use for simple things, it should never be used in these situations
16:18 <Akien> reduz: I guess this was also not a good idea then? https://github.com/godotengine/godot/pull/23658/files#diff-8333910cf7dd8405c864e7b46fb3b145R106
16:23 <reduz> yeah i guess not
16:24 <reduz> ItemCustomFX  should simply contain the reference to RichTextEffect
```

And https://github.com/godotengine/godot/pull/32202#issuecomment-535043254

> There is an enum so you can do static cast, so dont use Object, this is overkill as Object / GDCLASS is extremely expensive to be used in a case like this. This PR will have to be reverted.

In the end I decided not to revert the PR as it would reintroduce a bad crashing condition, but we need to refactor this to avoid the use of Object for `Item*`.

Comment by @Relintai: https://github.com/godotengine/godot/issues/32103#issuecomment-535114365

> #23658 will need to be heavily changed, because of the inheritance introduced. Namely `Item->ItemFX->(new classes)`, and the pr itself uses this fact quite a bit. This was also the cause why I changed my pr from using static_casts, to begin with.
> 
> I'll think about how to solve that inheritance issue properly. I don't just want to split up the type enum brainlessly. Even though that's probably what I'd do if I did this for myself :P
> 
> By the way please wait with reverting #32202, at least until there is a proper fix for this because when I was debugging this I was able to get RichTextLabels to crash, just by setting their text at runtime to a short text with a number and a newline in it. It was along the lines of "aaa0a\naa". (With BBCode disabled)
> 
> In fact that was the reason I got crashes in the first place, my game has spells, and I use RichTextLabels to show their description, which is just a few lines of text with a few numbers.

CC @Eoin-ONeill-Yokai @Relintai @reduz

**Comment by Eoin-ONeill-Yokai** [comment]
#32103 won't need to be heavily changed per-say, but the removal of dynamic cast as an option does make this more difficult. I only changed the subclass to the Object type simply for the ability to have dynamic casting again, as Godot chose not to support it due to android compatibility (which is the right choice) and that was the recommended procedure when I went to the IRC to inquire about the removal of dynamic_cast. 

Containing a reference to a RichTextEffect might work though, so I'll try that tonight and, if it works, send it upstream.

>In the end I decided not to revert the PR as it would reintroduce a bad crashing condition, but we need to refactor this to avoid the use of Object for Item*.

This is strange, it might have to do with my additional PRs to address C# compilation? Depending on whether I can come up with some decent solution tonight though, it might be worth exploring pulling back this PR until a proper solution is found.

**Comment by Relintai** [comment]
> This is strange, it might have to do with my additional PRs to address C# compilation? Depending on whether I can come up with some decent solution tonight though, it might be worth exploring pulling back this PR until a proper solution is found.

The reason for the crashing was that we had an inheritance tree (Item, and it's derived classes), and godot's internal RTTI thought they are the same classes (lack of GDCLASS macro), so it happily static cast every pointer, into every other pointer in that inheritance tree. On platforms that did not have built in c++ RTTI.

So for example the original code tried to collect every ItemFX, and it's derived classes into an fx_stack vector, but it actually collected every Item and derived classes, and also later it just static_cast everything into every type, and then member accesses caused crashes.

See my first comment in #32103. I kind of edited it a bunch of times, and now it looks a bit weird because of it, but it has more info about what caused the crashes.

Also please check my new pr, that references this issue, maybe you notice something I didn't.

**Comment by Eoin-ONeill-Yokai** [comment]
@Relintai Want to say thanks again for tackling this issue personally, I was about to start working on this right when your PR came in. 

Yeah your PR seems to be pretty good other than the one regression in ItemFade and some shake regressions. Other than that, it's already quite a bit cleaner.

**Comment by Relintai** [comment]
@Eoin-ONeill-Yokai No problem. I'll fix the fade. However I misunderstood you comment on the shake at the pr's code first, could you elaborate on that?

**Comment by Eoin-ONeill-Yokai** [comment]
The shake is actually working as intended. My original concern was that per-line shake orientation would all be the same due to a NULL assignment. However, having tested it more in my test project branch, it seems to work as intended.

**Comment by Relintai** [comment]
Okay, thanks for helping me out!

Also I pushed up the fix for fade.

**Comment by Eoin-ONeill-Yokai** [comment]
>Okay, thanks for helping me out!

No worries, you did all the hard work!
