### ISSUE TITLE
TextureRect size doesn't update when its texture changes size

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#32349]
Windows 10 64 bits
Godot 3.1.1

Similar to closed #20614 , if I change the size of a texture previously assigned to a `TextureRect`, the node does not update its size. 
This doesn't happen with sprites.

Project:
[TextureRectNotResizingIfTextureRecreated.zip](https://github.com/godotengine/godot/files/3649573/TextureRectNotResizingIfTextureRecreated.zip)

**Comment by girng** [comment]
Yeah, if using
```
	yield(VisualServer, "frame_post_draw")
	print(_texture_rect_with_forced_swap.rect_size)
```

the real `rect_size` will be displayed.

This issue is actually much deeper and isn't just isolated to `TextureRect`, it happens in a lot of nodes inherited from `Control`. From my experience with extreme UI development, my solutions over the years to obtain the correct  `rect_size`, is to   use a mixture of

 ```
modulate.a = 0
yield(get_tree(), "idle_frame") or yield(VisualServer, "frame_post_draw")
modulate.a = 1
```
Notice modulate.a instead of hide/show methods. 
I created a PR about this last year or so (might have been on my old deleted account, so can't find it).

**Comment by girng** [comment]
Basically, it's a good rule of thumb to always try yielding VisualServer's `frame_post_draw` signal if your `rect_sizes` are **not displaying what you think they should**. 95% of the time, yielding that signal   will fix any UI sizing issue you might run into (outside of `TextureRect`).

**Comment by Zylann** [comment]
Having to wait for the engine to draw can be very limiting though. See how much lengths one has to go just to workaround these kinds of limitations: https://godotengine.org/qa/51562/get_visible_line_count-returning-previous-change-labels

But in this situation it looks like it could still be fixed, because the engine knows the size of the texture right away, and it does update if I explicitely re-assign the `texture` property. There should not be a need to wait for a frame here.

**Comment by girng** [comment]
Lol, I can totally relate to that QA post. I swear, I could write a book about `rect_size` 😆
