### ISSUE TITLE
Add info about the node's virtuals in the code editor

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3237]
Forking this comment from @reduz in another issue: https://github.com/godotengine/godot/pull/1737#issuecomment-98901693

> I was thinking of adding to the code editor a tab that is "virtuals" or
> "overridable" and it shows a list of methods you can override and an
> optional link to the help

I think it's a cool idea, so it's worth having its own issue to discuss and maybe implement.

**Comment by StraToN** [comment]
This makes me think about the Eclipse way to do code completion.
If ctrl+space is toggled on an empty line, outside of any existing function of the source code, a little panel is displayed showing all overrideable methods (in a class inheriting an abstract class for example, or a class implementing an interface/pure virtual class).

One could imagine a similar panel displaying overrideable functions such as _process(), _draw(), and so one. Concerning help related to each of those, the panel could propose an help button attached to every overrideable function in this panel.

**Comment by bojidar-bg** [comment]
I guess we would need a way to mark functions as virtual from gdscript, like
````gdscript
virtual func serialize():
  return {}
virtual func deserialize(data)
# No need to pass, YAY
````

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
