### ISSUE TITLE
Resizing game window while breakpoint is active gives weird black edges

### ISSUE THREAD

**Issue by noname1477** [godotengine/godot#32418]
**Godot version:**
Custom build at a1fcac6

**OS/device including version:**
Windows 10 1903

**Issue description:**
If you try to resize a game window while a breakpoint is active, the part you resized turns black. It works again after pressing "Continue" in the breakpoint window.

![breakpoint_resize_test](https://user-images.githubusercontent.com/54987242/65818937-d60f5e00-e216-11e9-9073-7c32788cc999.gif)

**Steps to reproduce:**
1. Use any project you like.
2. Add a breakpoint somewhere (using F9).
3. When the breakpoint kicks in, resize the game window.
4. You should see black edges.

**Minimal reproduction project:**
https://github.com/noname1477/breakpoint-resize-bug-test

**Comment by Zylann** [comment]
This doesn't sound like a bug to me. You have a breakpoint active, that means the game loop is really suspended. That includes rendering, so that's why you get black edges, they are not getting updated because the code to do so cannot run. If it were running, it would mess up the breakpoint you used in the first place.

**Comment by clayjohn** [comment]
In light of Zylann's comment, I am closing this issue. 

He proposed an interesting new feature, but since the implementation will be extremely complex, I suggest if anyone wants it,  they make a proposal in the [proposals repo](https://github.com/godotengine/godot-proposals).
