### ISSUE TITLE
GDNative godot::String concatenation memory leak

### ISSUE THREAD

**Issue by rarsp** [godotengine/godot#32502]
**Godot version:** 3.1.1 stable

**OS/device including version:** Windows 8.1 64

**Issue description:** Using godot::String class is generating  memory leaks in static memory when concatenating Strings from the same scope 

**Steps to reproduce:** Create basic gdnative script with some Strings concatenation in _process method:

`// this isn't leaking memory
  String abc = "abc";
  for (int i = 0; i < 10000; ++i) {
    String abc_plus = abc + "plus";
  }

// this is leaking memory very fast
  for (int i = 0; i < 10000; ++i) {
    String abc = "abc";
    String abc_plus = abc + "plus";
  }
`

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
I think you need to free the memory yourself, see https://docs.godotengine.org/en/latest/tutorials/plugins/gdnative/gdnative-cpp-example.html#our-c-source

**Comment by sheepandshepherd** [comment]
That's true in C, but godot-cpp's String calls `godot_string_destroy` in its destructor to match the ref-counting behavior of the engine's String.

Looks like the problem is that [String::operator+](https://github.com/GodotNativeTools/godot-cpp/blob/master/src/core/String.cpp#L126) incorrectly adds to `abc`'s own ref-count. So the first example leaks one "abc" and the second leaks 10000 "abc"s.

I'll make a PR in a minute - if you want test the fix, it's just [these two lines](https://github.com/sheepandshepherd/godot-cpp/commit/9560cbff096caf1720d15ea6d8b77193c9cdda0a).
