### ISSUE TITLE
Linux can't build 32bit (cannot find -levdev).

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#3252]
Message is show:
```
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../libevdev.so when searching for -levdev
/usr/bin/ld: skipping incompatible /usr/lib/libevdev.so when searching for -levdev
/usr/bin/ld: cannot find -levdev
collect2: error: ld returned 1 exit status
```

I use Arch Linux, 64bit is build success.

**Comment by Hinsbart** [comment]
Arch doesn't provide a multilib package for libevdev. You could do one of the following:

- a) use a [chroot environment](https://wiki.archlinux.org/index.php/Install_bundled_32-bit_system_in_64-bit_system) for 32 bit builds
- b) [try](https://wiki.archlinux.org/index.php/Makepkg#Build_32-bit_packages_on_a_64-bit_system) to build your own lib32 version of libevdev

I recommend option a)

anyway, this is the distros problem rather than ours, so this can be closed.
But of course you can keep posting here if you need more help.

**Comment by akien-mga** [comment]
Shows again that a ```gamepad=no``` option could be useful, I'll have a look at it. In such cases for quick testing it's likely easier to disable a feature than create a 32-bit chroot (though arguably a distro that doesn't provide proper multilib packages is not really ripe for cross-compiling).

**Comment by Mavhod** [comment]
Old version of Godot is build success, it just build error in a last version.

**Comment by akien-mga** [comment]
If you backport this patch you should be able to build for 32-bit with "gamepad=no", but of course you'll have limited gamepad support: https://github.com/godotengine/godot/pull/3254

**Comment by akien-mga** [comment]
> Old version of Godot is build success, it just build error in a last version.

Yes the dependency on libevdev and libudev was added recently, together with improved gamepad support.

**Comment by vnen** [comment]
I didn't have success building 32-bit Godot in Arch Linux with multilib, even before libevdev. Chrooting, as @Hinsbart said, is the best way to cross-compile different architectures.
