### ISSUE TITLE
Attempt to call function get_cancel() from ConfirmationDialog 

### ISSUE THREAD

**Issue by SamToorchi** [godotengine/godot#32547]
**Godot version: 3.1.1**

**OS/device including version: Linux Opensuse**

**Issue description: by trying to call function `$ConfirmationDialog.get_cancel()` get following error: "Attempt to call function 'get_cancel' in base 'null instance' on a null instance" **

**Steps to reproduce:**
`extends ConfirmationDialog

func _ready():
	 $ConfirmationDialog.get_cancel()`

**Comment by akien-mga** [comment]
Sounds like a bug in your script, please use other community platforms to get support on such issues.

This issue tracker is for bugs in the engine itself.

Since we're here though, the issue is very likely that you don't have any node named `ConfirmationDialog` as a child of the `ConfirmationDialog` node on which you attached this script. What you want to do is probably just `get_cancel()` or `self.get_cancel()` -- you're *already* in the `ConfirmationDialog` node.

If you're confused about the `$` operator, check the GDScript docs: https://docs.godotengine.org/en/latest/getting_started/scripting/gdscript/gdscript_basics.html

**Comment by SamToorchi** [comment]
the Script for ConfirmationDialog must be the part of Node
