### ISSUE TITLE
InputEventMouseMotion speed is zero when capturing mouse

### ISSUE THREAD

**Issue by Juankz** [godotengine/godot#32578]
**Godot version:**
3.1.1.stable

**OS/device including version:**
Linux. Solus 4

**Issue description:**
When using `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)` mouse speed tends to zero. This worked as expected in Godot 3.0.6

**Steps to reproduce:**
1. Run minimal project and observe the console log.
2. Comment the line `Input.set_mouse_mode(Input.MOUSE_MODE_CAPTURED)`
3. Observe console log.

**Minimal reproduction project:**

[capture_mouse_speed.zip](https://github.com/godotengine/godot/files/3693871/capture_mouse_speed.zip)

**Comment by guilhermefelipecgs** [comment]
This isn't a bug, in captured mode the cursor must be locked at the center of the viewport (otherwise, other issues will happens), so it's not possible to calculate the speed because the speed is calculated based on last position. Use `event.relative` instead.

https://docs.godotengine.org/en/latest/tutorials/inputs/mouse_and_input_coordinates.html#hardware-display-coordinates

**Comment by Juankz** [comment]
Pardon the insistence, but why was this working on previous versions?

**Comment by guilhermefelipecgs** [comment]
Because the captured mode was broken for Linux. If you do the same test on Windows with the previous version, it probably won't work.

**Comment by guilhermefelipecgs** [comment]
see here: https://github.com/godotengine/godot/pull/21753

**Comment by Juankz** [comment]
Thanks for the clarification
