### ISSUE TITLE
Is the language option de_CH really needed?

### ISSUE THREAD

**Issue by NPScript** [godotengine/godot#32625]
Hi, I'm Nate.
I'm testing this Engine since two days and I pretty like it.
But I don't understand why there is the Swiss-German language option, because there is no grammar of Swiss-German that means in Switzerland we just write in German...
As result if you select *de_CH* as language you won't get some translations unlike German (*de*).

**Comment by QbieShay** [comment]
This is actually an interesting problem. It's be probably nice if de_CH could use de for all the missing translation! I wonder if there is a concept of "language variation". To my knowledge (I live in the north east Switzerland) some words differ between High German and Swiss German, perhaps the entire swiss translation should be emptied and only the different words should be filled in, and for the rest it should default to de.

Id appreciate thoughts on this !

**Comment by NPScript** [comment]
As far as I know, there are just differences between German and Swiss German words in the case of a *ß*, (for example : groß - gross).
In that case we could just replace the *ß* with *ss*
Is that right or are there more differences?

**Comment by akien-mga** [comment]
The option exists because one translator added it (see contact info in https://github.com/godotengine/godot/blob/master/editor/translations/de_CH.po).

Translations are at https://hosted.weblate.org/projects/godot-engine/godot/

IMO. it's always a bad idea to start a custom translation for a language variant on such a massive translation catalog. The focus should be on finishing the "standard" language translation, and then this translation can possibly be copied and edited for regional variants which may use different words.

Depending on the actual language and/or the translators though, some disagree with this and start a parallel translation. It's not always clear whether they know it because they have a deep understanding of the differences between language variants and think it's better to treat them as fully separate languages, or if it's because they just felt that their country/region needs representation.

We currently have `de_CH` which is indeed likely worth removing, as it's only 3% complete, and I don't think the differences with the 100% `de` warrant this situation.
We also have `pt_PT` which was started as a copy of `pt_BR` once both were ~20% complete or so. Now both are 100% complete, but IMO translators would gain time by focusing on a common `pt` translation before adapting it to their regional variants.
Same with `es_AR`, whose purpose is not very clear to me.

This is even worth on the massive godot-docs repo: https://hosted.weblate.org/projects/godot-engine/godot-docs/
`pt_PT` was forked from `pt_BR`, and did not advance much since. `es_MX` with 4% vs the 52% complete `es` seems like a very bad idea.

But for these things we have to defer to the actual speakers of the language to estimate whether branching off (or starting from scratch) is worth the effort. I would personally discourage any `fr` variant from starting translations.

---

> This is actually an interesting problem. It's be probably nice if de_CH could use de for all the missing translation!

That could likely be implemented, yes. We load all translations in the editor so it would be possible in theory for `de_CH` to fallback to `de` strings when there is no translation.

That would be nice to have, though I think in this very case the best solution is likely to remove the always empty `de_CH` translation, and let Swiss German translators help their German speak improve the quality of the common *Hochdeutsch* translation.

**Comment by akien-mga** [comment]
> That would be nice to have, though I think in this very case the best solution is likely to remove the always empty `de_CH` translation, and let Swiss German translators help their German speak improve the quality of the common _Hochdeutsch_ translation.
> Then if regional variants warrant branching off, it should likely be done by starting from the 100% complete `de` translation catalog.

@puppetmaster- If I'm not mistaken you're the one who added the `de_CH` translation. Do you agree with the above proposal?

**Comment by puppetmaster-** [comment]
@akien-mga No problem, I wanted to do this a long time ago myself, unfortunately it didn't work out because of problems with permission.

**Comment by Calinou** [comment]
Any progress on this? I can still see the `de_CH` translation here: https://hosted.weblate.org/projects/godot-engine/godot/de_CH/

**Comment by akien-mga** [comment]
I'll remove it next time I sync translations.

Here's the current version of `de_CH.po` as backup, if it can be used to retrieve some CH-specific translations to improve a new version forked from `de.po` (which is 100% complete) - again, after assessing if there's really a use case for a `de_CH` translation in the first case instead of the pangermanic `de`.

**Comment by puppetmaster-** [comment]
I would no longer offer a swiss translation. In the Vivaldi Browser it has one too but it reads badly and is very dialect dependent. Don't think that anyone uses it in an editor.
