### ISSUE TITLE
queue_free() is not releasing memory

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#32645]
**Godot version:**
current master: 98497ff71928daff6afb393b26e230e28bf18e3e release_debug build
as well as stable 3.1 

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
I discovered that Godot practically never releases memory. 
This can be observed even in editor, when closing scenes no memory is released and opening the same scenes again consumes additional amount of memory.
I created simple reproduction project in which couple of nodes are instanced 10000 times. When calling queue free we can see with Godot debug tools ('Monitor' tab) that memory is released, when in fact it's not (when checking with system tools). 
Furthermore, **calling queue_free() many times for the same node causes more leaks.**
I'm not sure if this is OS specific issue, would be good if someone could use reproduction project on Windows to check.

**Steps to reproduce:**
1. Create SimpleScene.tscn, add couple nodes inside.
2. Create Main.tscn together with Main.gd script.
3. Inside Main.gd script ready function instance SimpleScene.tscn couple thousands of time (so you can see difference in memory monitor in your OS) and add them as children of Main.tscn.
4. Add a 'ReleaseMemory' button to Main.tscn that will call `queue_free()` on each children of Main.tscn
5. Observe that after clicking the button there is no memory is released (use OS specific monitoring tool).
Additional steps:
6. Add a loop that will call queue_free many times for each of the children. Observe that memory consumption jumped significantly after pressing 'ReleaseMemory' button.

Sample script that can be used to recreate issue:
```
extends Node

const SomeScene = preload("res://path/to/some/scene.tscn")

func _ready() -> void:
	for i in range(10000):
		var scn = SomeScene.instance()
		add_child(scn)
		#CAUTION! uncommenting will leak a LOT more memory!
		#seems like calling queue_free many times causes a leak on its own
		#Godot debug tools (Monitor tab) will not represent that peak in any way
#		call_deferred("clear_all") 

func clear_all():
	for child in get_children():
		child.queue_free()

func _on_Button_pressed() -> void:
	call_deferred("clear_all")
```

**Minimal reproduction project:**
[MemoryLeakTest.zip](https://github.com/godotengine/godot/files/3702346/MemoryLeakTest.zip)

**Comment by Zylann** [comment]
Tried on Windows 10:

When I try to instance 10000 of your scenes Godot hangs. I tried waiting one minute but still nothing, and pausing the game did nothing as well so I don't know what it's doing. Had to stop. Even with 5000 instances the game hangs a lot so can't even test at this scale. Maybe nodes process too much.

I tried a slightly different repro:
I instance 1000 scenes on the click of a button instead of 10000. Then with another button, I clear them. I alternatively clicked the two buttons about 30 times, but did not see anything special in the task manager.

**Comment by kubecz3k** [comment]
@Zylann leave Godot open for couple of minutes I promise you it be responsible after instancing those nodes. Also don't know if you tried with my sample directly or if you used just my script, in second case increase Message Queue limit in Project Settings since it indeed will really take very long in such case to instance those scenes:
![image](https://user-images.githubusercontent.com/6129594/66398613-60f21480-e9de-11e9-83b4-3ff9f87f462a.png)

**Comment by kubecz3k** [comment]
Also, in given sample those 10 000 instances should consume consume around 350 megabytes of memory.

**Comment by akien-mga** [comment]
The reproduction project with 10000 instances seem to be an edge case, there are various things that could trigger leaks in *this specific configuration* and not in any generic `queue_free()` usage. For example the Message Queue might be forced to drop messages (and might do it in a dirty way) to be able to process such a request (I didn't check the code, it's just an hypothesis).

Do you get leaks in a less extreme scenario, with a single `queue_free()` or a handful of them?

**Comment by kubecz3k** [comment]
@akien-mga  yes I'm able to reproduce when for example doing a queue_free() on a level scene after coming back to main menu. I'm also able to reproduce with @Zylann  sample, I recorded small video that shows exactly how I'm testing this on Zylann's sample: https://youtu.be/0--YlTzbCcE

**Comment by Zylann** [comment]
@kubecz3k in your video, you are allocating many scenes, and then clearing the whole lot, and seeing that it doesn't reduce memory usage. This isn't complete though, because it could just as well be the OS keeping this memory allocated as a form of "capacity" (Windows does that too). To rule this out, did you try allocating again after the big clear? Did it make memory increase immediately again?

**Comment by kubecz3k** [comment]
I think you are right, when there is some amount of memory allocated already each click allocates additionally only a fragment of the base size. Not sure however if this memory is reserved by OS or somehow by Godot itself, since in in my case it's never released - even in the conditions of swap overfilling. 
It has some practical implications, in the project I'm working on, some temporary content is generated during the loading time, which doubles the memory consumption - since it's never released it's causing performance problems (related to swapping).

**Comment by kubecz3k** [comment]
That being said it's probably a topic for a different issue.

**Comment by RandomShaper** [comment]
I've been doing some research.

The first thing I noticed while running on Windows (compiled with MSVC) is that all the memory was given back to the OS after removing all the nodes.

Then, I checked the reason of the 6 GiB of used memory when uncommenting the `queue_free` line in the loop. That happens because the deletion queue ends up filled with a huge number of requests before it has a chance to honor them.

But on Ubuntu I was able to reproduce the issue that not all the memory was being effectively released. It was probably due to the allocator implementation in the standard C++ library. I found this in the docs about mt_allocator:

> Notes about deallocation. This allocator does not explicitly release memory back to the OS, but keeps its own freelists instead. Because of this, memory debugging programs like valgrind or purify may notice leaks: sorry about this inconvenience. Operating systems will reclaim allocated memory at program termination anyway. If sidestepping this kind of noise is desired, there are three options: use an allocator, like new_allocator that releases memory while debugging, use GLIBCXX_FORCE_NEW to bypass the allocator's internal pools, or use a custom pool datum that releases resources on destruction.

Not completely sure if that's the default allocator, but anyway I tried running the program with that flag, to no avail. The memory behavior kept being the same.

Finally, I decided to check with Valgrind's massif, to get a real view:
![image](https://user-images.githubusercontent.com/11797174/66470181-635d7880-ea89-11e9-9b92-e13e8b033485.png)

If I'm interpreting this correctly, it means that the heap was really getting shrinked as the nodes were being freed, but not down to its initial size. The reason why is maybe reservation or fragmentation, but in any case I agree that this is expected behavior and, if anything, Godot is taking responsibility of freeing the memory. If there's any issue it's in the allocator.
