### ISSUE TITLE
Cannot set_bone_global_pose at import time

### ISSUE THREAD

**Issue by fire** [godotengine/godot#32669]
**Godot version:**
bb41f0b0cbc8ceff55a77cec42664c2ee81bb2f2

**OS/device including version:**
Windows 10

**Issue description:**
Cannot set_bone_pose at import time. It lacks access to the scene tree.

https://github.com/godotengine/godot/blob/7ce5233d24ac30c937bbf06acb8d0be1d990ed37/editor/import/editor_scene_importer_gltf.cpp#L2138

Try skeleton->set_bone_global_pose_override(bone_index, node->xform, 1.0f, true);

**Comment by slapin** [comment]
If you see the code you'd know it needs global transforms to work, which is really weird but probably easier to do that way. Hope that will be fixed eventually. For my skeleton operations I have to just apply transforms from root (you can build list from current bone to root then reverse it). I have to do this anyway as I use custom pose and sometime want to use just bind pose to build my transforms, so that is unavoidable. For importer code a work with transform list should be fine. If you plan run time you will need to keep cached value on each level and check how dirty that is for speedup.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by fire** [comment]
Closing because I don't really use this feature. I expect bone global pose to be reset after import.
