### ISSUE TITLE
Folders with name that start with a dot (.) don't get included on export

### ISSUE THREAD

**Issue by sprite-1** [godotengine/godot#32826]
**Godot version:**
3.1.1

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
Folders that have a dot (.) at the start of their name don't seem to get included on export. Not even adding the folder to the filters section in the `Resources` tab of the export dialog.

**Steps to reproduce:**
1. Create a any folder with a dot at the beginning of their name
2. Export the project (can export as ZIP to easily inspect the result)
3. The folder is not included.

**Minimal reproduction project:**
[Font Test.zip](https://github.com/godotengine/godot/files/3724450/Font.Test.zip)

**Comment by Chaosus** [comment]
It may related to the fact that dot at the beginning used for hiding files on Linux systems..

**Comment by sprite-1** [comment]
@Chaosus I am aware, but I didn't think it would be an issue since it exports `.import` just fine

**Comment by KoBeWi** [comment]
So this happens because `editor_file_system.cpp` contains conditions like this
https://github.com/godotengine/godot/blob/64be558443c6ec684a9fffc4ee516a403c8d7e71/editor/editor_file_system.cpp#L651-L653
which filter out all files and directories starting with `.`. But if you remove this, the editor would be scanning e.g. `.git` directory, which would negatively impact filesystem performance a lot. The reason it exports `.import` just fine is that it's an exception, i.e. the exporter is hardcoded to include this directory.

That said, this should just be documented somewhere. It's not a bug.
