### ISSUE TITLE
Delete shortcut doesn't work on gridmap node

### ISSUE THREAD

**Issue by Nehluxhes** [godotengine/godot#32852]
**Godot version:**
3.2 since commit [https://github.com/godotengine/godot/pull/25406](https://github.com/godotengine/godot/pull/25406
)
**Issue description:**
The delete shortcut doesn't work anymore on gridmap nodes to delete them since it is now used to clear the cell selection. If there is no selection it should still work though.

I was trying to fix the problem myself since it seemed an easy enough task for a first pull-request but I am not too sure about what to do anymore...

Basically the problem is the InputEventKey never reach the _unhandled_key_input() method from scene_tree_dock.cpp since it is intercepted and consumed before in 

*menu_button.cpp*
```
void MenuButton::_unhandled_key_input(Ref<InputEvent> p_event) {
[...]
		if (popup->activate_item_by_event(p_event, global_only))
                        // Should NOT be called if there is no selection in the gridmap
			accept_event();
	}
}
```
And the PopupMenu just  uses the "id_pressed" signal to tell the gridmap to clear the selection by calling _menu_option() so there is no return value to be able to NOT call accept_event()

*grid_map_editor_plugin.cpp*
```
void GridMapEditor::_menu_option(int p_option) {
[...]
case MENU_OPTION_SELECTION_CLEAR: {
	    	    if (!selection.active)
                                // HERE we should ignore the input event so it reaches the scene tree dock
				break;
```

So I don't really know how to proceed without changing everything... any thoughts?

**Comment by codecustard** [comment]
If you disable the item `popup->activate_item_by_event(p_event, global_only)` should return false. So if there is no selection, you could do something like: `options->get_popup()->set_item_disabled(options->get_popup()->get_item_index(MENU_OPTION_SELECTION_CLEAR), true);` and it will disable that option. If you don't want to disable it, you could also disable the shortcut, which should also work because of this line: `if (is_item_disabled(i) || items[i].shortcut_is_disabled)` inside the `PopupMenu::activate_item_by_event()` method.

**Comment by Nehluxhes** [comment]
@codecustard Simply deactivating the item when there is no selection certainly did the trick and is a lot simpler than the other solutions that I had in mind. Don't know why I didn't think of that. Thanks! I will soon make a PR.
For homogeneity I will also deactivate the other selection actions (cut, fill, duplicate)
