### ISSUE TITLE
clear_colors in TextEdit does not work

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#32931]
**Godot version:**
3.2 Master

**OS/device including version:**
Ubuntu 18.04 bionic
x86_64 Linux 5.0.0-31-generic

**Issue description:**
TextEdit.clear_colors() should remove all syntax highlighting colors, although it does not

**Steps to reproduce:**

1. `clear_colors()`

**Minimal reproduction project:**
[GodotTestProject.zip](https://github.com/godotengine/godot/files/3747538/GodotTestProject.zip)

**Comment by pouleyKetchoupp** [comment]
Are you trying to disable all syntax highlighting? In this case you can simply use `syntax_highlighting = false` instead of `clear_colors()`.

It seems `clear_colors()` is not doing exactly what the documentation says, though. I'm going to propose a PR with two things:
- Clarification in `TextEdit` doc about `clear_color()`
- Fix its implementation, because it's not working in all cases at the moment

**Comment by nathanwfranke** [comment]
Thank you for the PR :)
Of course disabling syntax highlighting would work, I would plan to add my own custom options after the clear call

**Comment by pouleyKetchoupp** [comment]
After my change, `clear_colors()` is still going to only reset the custom options you've previously added using `add_keyword_color()` and `add_color_region()`.
 
If you need to disable all the default highlighting and replace it with your own, you can try to change the default colors in the Custom Colors section to make all the text white, and then add your own custom keywords by script like you intended to. Would that work for you?

**Comment by akien-mga** [comment]
So can this be considered solved by #32940?

**Comment by nathanwfranke** [comment]
Yes, thank you all!

**Comment by nathanwfranke** [comment]
Archive This?

**Comment by akien-mga** [comment]
Well no, why? It's a bug which has been fixed.
