### ISSUE TITLE
continue in match goes to wildcard case _ in for loop

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#32947]
**Godot version:**
3.2-alpha 48d3458f74

**OS/device including version:**
Linux Mint 19.1

**Issue description:**
`continue` in `match` goes to wildcard case `_` in `for` loop
but `break` ends `for` loop as expected.

**Steps to reproduce:**
```gdscript
func _ready():
	print("test continue")
	for i in 3:
		match i:
			0,1:
				if i == 1:
					continue # goes to wildcard "_"
				prints("a",i)
			_:
				prints("b",i)
	
	print("test break")
	for i in 3:
		match i:
			0,1:
				if i == 1:
					break # ends for loop
				prints("c",i)
			_:
				prints("d",i)
```

**Minimal reproduction project:**
[match test.zip](https://github.com/godotengine/godot/files/3748227/match.test.zip)

**Comment by volzhs** [comment]
I know this example code does not make sense.
but I had to make it like this for simplicity.

**Comment by volzhs** [comment]
I could not find about it on online doc.
by the way, using `continue` and `break` inside `match` in loop confuses me then.

**Comment by cur33** [comment]
The use of `continue` for fallthrough is mentioned in the [docs for the match keyword](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#match).
It is perhaps a little confusing to use `continue` for both loops and pattern matching, but the semantics are similar in both cases: "continue on to the next case." And at this point, it wouldn't make much sense to introduce a backwards-incompatible change by changing it to a different keyword for use in `match` blocks.

As the docs mention in the link above, `match` blocks in GDScript break by default instead of continuing to the next pattern—that's why they allow you to use the `continue` keyword if you want that behavior. So there is no need for a `break` keyword in `match` blocks. Thus, using a `break` inside of a `match` block will instead break the surrounding loop, and would likely cause an error if there is no surrounding loop.

If this answers your questions, it would be great if you could close this issue since it isn't a bug.

**Comment by volzhs** [comment]
i missed that you pointed in doc. thanks.
i need to keep in mind that and need to replace it with `if`s :smile:

**Comment by fsy98** [comment]
So is that mean you have question in using continue and break inside match in loop? It is similar with **switch**, **break**, **continue** in for loop. If you want to break the loop, use the **break**. if you want to make a jump of the left part and continue loop use **continue**. **Match** is similar to '=' means meet the condition.

**Comment by cur33** [comment]
No problem!
