### ISSUE TITLE
Tile set tile rotation doesn't affect LightOccluder2D

### ISSUE THREAD

**Issue by flakusha** [godotengine/godot#32993]
**Godot version:** 3.1.1

**OS/device including version:** Windows 10, Manjaro Linux 18

**Issue description:** Rotation of tiles in tileset has no effect on LightOccluder2D, resulting in incorrect shadowing of parented sprite in top-down environment.

**Steps to reproduce:**
1. Create the new scene
2. Add sprite and then add LightOccluder2D, StaticBody2D and CollisionShape2D (for StaticBody)
3. Set up occluder and collision shape. Occluder should have ClockWise or CounterClockWise Cull Mode, Closed set to On. You can try setting Closed to Off and issue still will be relevant, though you will also get a hole in occlusion or additional setup will be required
4. Convert scene to tileset
5. Create game level scene, add tiles to the scene, optionally add CanvasModulate to darken the scene
6. Add light source focused on assets
7. Place assets in different directions using tile rotate, only one will have correct shadowing.

**Screenshot:**
![2019-10-22 20_12_51-Godot Engine - Heist_Meisters - Test_Level tscn](https://user-images.githubusercontent.com/14177728/67312315-cc250600-f509-11e9-9b1f-e83f54345879.png)

**Comment by raphael10241024** [comment]
Can you provide a simple demo project for it ? So I can test it easily.

**Comment by flakusha** [comment]
> 
> 
> Can you provide a simple demo project for it ? So I can test it easily.

Hello!
Yes, please take a look at my development studying project!

`git clone https://gitlab.com/flakusha/heistmeisters-top-down.git`

**Comment by bojidar-bg** [comment]
I couldn't reproduce the bug on a project of mine, and checking the reproduction project linked above, I could "fix" the issue pretty fast:
![image](https://user-images.githubusercontent.com/5276727/70560553-7aa40980-1b91-11ea-996f-fe549e746e08.png)

All I had to do was.. rotate the upper tile twice (for 180°), instead of flipping it vertically. Or, alternatively, flipping it both horizontally and vertically (which leads to the same transform).

Not sure if light occluders should change their cull order when flipped using transforms, though. As currently implemented, it is "clockwise" or "counter-clockwise" in world space, not in local space, which could be confusing.

**Comment by flakusha** [comment]
@bojidar-bg well, your approach should be correct. I will try it out after I have spare time, thank you.
