### ISSUE TITLE
Integrate with travis-ci

### ISSUE THREAD

**Issue by gamedevsam** [godotengine/godot#33]
Travis provides continuous build support (including pull requests). This would let us know if a pull request would cause a compiler error.

https://travis-ci.org/

**Comment by bdero** [comment]
@reduz I was about to suggest the use of Travis for per-commit builds, but if you're using Jenkins, that's great, too.

An uprising practice is to run full build and test suite jobs against every commit on every pull request for automated integration into the code review process.

Notice how edX does it: https://github.com/edx/edx-platform/pull/6609
Next to each commit, there's an icon indicating the build status:
![Build status](http://i.imgur.com/xp14tsL.png)

Clicking it takes the user to the build report to pinpoint test/build failures:
![Build report](http://i.imgur.com/rx6pJi8.png)

Of course, building Godot for all platforms on every push might be intense on compute time. The bright side is that, since Godot has surprisingly few dependencies, build configuration is probably quite a bit simpler than it could be.

**Comment by erbridge** [comment]
Looks like Travis is already set up to do the Linux build. There's a `.travis.yml` file which looks like it's set up correctly to me. It only needs to be turned on.

**Comment by eska014** [comment]
The discussion about continuous integration is continued in #1553.
