### ISSUE TITLE
GDScript properties with the same setget methods overwrite the value from extended script over base one

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#33039]
**Godot version:**
3.2-alpha

**Issue description:**
Not sure if bug or by design. I stumbled upon this while testing #33015.

Consider two classes where B extends A:

```gdscript
# a.gd
var value_a setget setter, getter

func setter(val):
	value_a = val
	
func getter():
	return value_a
```
```gdscript
# b.gd
extends "a.gd"

var value_b setget setter, getter # notice same setget as in `a.gd`

func setter(val):
	value_b = val
	
func getter():
	return value_b
```
```gdscript
# main.gd
func _ready():
	var inst = preload("b.gd").new()
	inst.value_a = "a"
	inst.value_b = "b"
	
	assert(inst.value_a == "a") # FAIL: inst.value_a == "b"
	assert(inst.value_b == "b") # OK
```
This doesn't happen if setget method *names* differ in classes.

**Minimal reproduction project:**
[script-extended-getter-same.zip](https://github.com/godotengine/godot/files/3768667/script-extended-getter-same.zip)

**Comment by Xrayez** [comment]
Also see https://github.com/godotengine/godot/pull/33018#issuecomment-546017014 for context where I've found this.

**Comment by vnen** [comment]
Well, this makes sense to me. The child script is overriding the parent methods, so they'll be called instead of the parent. `inst.value_a = "a"` is the same as `inst.setter(a)` and, conversely, `print(inst.value_a)` is the same as `print(inst.getter())`. Since those were overridden to set and get `b` instead, that's what they're doing.

The possible solution to this would be doing something like Java and require some `@Override` attribute when you are intending to override, avoiding potential mistake.

**Comment by Xrayez** [comment]
I guess the explanation makes it clear, so considering this as a feature for now, just letting you know about the use cases when GDScript gets a major overhaul to possibly avoid this.
