### ISSUE TITLE
Importing TextureAtlas cuts out the sprites 

### ISSUE THREAD

**Issue by holzmb** [godotengine/godot#33106]
**Godot version:**
3.2 alpha3

**OS/device including version:**
Ubuntu 18.04.3 LTS

**Issue description:**
When importing the sprites as TextureAtlas it cuts out the sprites like in the picture.
Every sprite is affected, some more than others. Pic has extreme examples.
![Untitled](https://user-images.githubusercontent.com/49844382/67633932-81630f80-f8b6-11e9-970b-4bd5840b27de.png)

**Steps to reproduce:**
Import some sprites

**Comment by akien-mga** [comment]
See #33448 for reproduction project.

**Comment by nesja** [comment]
Something similar still exists in stable versions 3.2, 3.2.1 and 3.2.2 b3. In my case, the source sprites have an extra transparent space that should be cropped during import as TextureAtlas. The bug is reproduced only if the size of the sprites is larger than the final atlas (this is possible if the sprite has a transparent space around). In this case, the atlas is created with cropped sprites on it. 
Attached example project contains two atlases created from sprites of different sizes. "Atlas_big" has wrong cropped sprites [texture_atlas_bug.zip](https://github.com/godotengine/godot/files/4712763/texture_atlas_bug.zip)
