### ISSUE TITLE
Area2D's body_entered signal only fires if PhysicsBody2D has collision_mask's 0th bit set

### ISSUE THREAD

**Issue by arcticmatt** [godotengine/godot#33129]
**Godot version:**
Godot Engine v3.1.1.stable.mono.official

**OS/device including version:**
macOS Mojave Version 10.14

**Issue description:**
I'm trying to detect a collision between a RigidBody2D and a KinematicBody2D. To do this, I have an Area2D on my KinematicBody2D. I then connect the signal for "body_entered" and perform some logic in the connected function.

However, that function only gets called if the RigidBody2D has its 0th bit in collision_mask set to 1. For example:

RigidBody2D:
collision_layer = 001
collision_mask = 100

KinematicBody2D:
collision_layer = 01
collision_mask = 001

This works! The bodies collide, and "body_enter" fires.

RigidBody2D:
collision_layer = 001
collision_mask = 010

KinematicBody2D:
collision_layer = 010
collision_mask = 001

This does not work. The bodies still collide as expected, but "body_enter" does not fire. In order to get it to fire, I need to set the 0th bit of RigidBody2D's collision_mask to 1.

**Steps to reproduce:**
See above

**Minimal reproduction project:**
[godot-bug.zip](https://github.com/godotengine/godot/files/3777185/godot-bug.zip)

**Comment by avencherus** [comment]
This seems to be because your Area2D's masked to the first layer and not masked to any of the layers that the bodies are on.  If you change that, it should work fine.  I changed your Area2D to layer 3, the one given for the RigidBody2D, and the signal fires.  (Using 3.1 official)

![image](https://user-images.githubusercontent.com/13004169/67657662-1110c880-f960-11e9-8362-baeff2cdc2d3.png)

**Comment by arcticmatt** [comment]
Ah, didn't realize Area2Ds have masks of their own. I guess I was thinking that they inherit them from PhysicsBodies. Thanks @avencherus!
