### ISSUE TITLE
ERROR: _disconnect: Nonexistent signal: tree_exiting.

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33139]
**Godot version:**
3.2 alpha 3
**OS/device including version:**
Ubuntu 19.10
**Issue description:**

Project contains 3D Node which delete a little after delete Rigidbody, VehicleBody and VisibilityEnabler

After playing shows 2 errors:
```
ERROR: _disconnect: Nonexistent signal: tree_exiting.
   At: core/object.cpp:1518.
```
**Steps to reproduce:**
Run project 
**Minimal reproduction project:**
[AAA.zip](https://github.com/godotengine/godot/files/3778726/AAA.zip)

**Comment by Odyhayek** [comment]
can i work on this bug ??

**Comment by MCrafterzz** [comment]
> can i work on this bug ??

Yes, you can always work on it without asking. But it is a good idea to let people know when you tackle issues like this that are so new so multiple people don't work on the same thing.

**Comment by Odyhayek** [comment]
@MCrafterzz thanks for the reply , im new to the whole github/opensource thing ... how can i let people know that im handling this issue ?

**Comment by volzhs** [comment]
it would be enough just to say "I will work on this" :smiley:

**Comment by MCrafterzz** [comment]
Yeah I'm new as well (done 2 prs) but that's what I've heard as well. It's nice to see a bunch of people having to started contributing after the presentation at godotcon :D

**Comment by Odyhayek** [comment]
I need help with this bug, the following is some of my speculations, and please correct me if im wrong, i understand that the child node visibilityenabler enables the error when the other nodes are invisible. the issue is at object.cpp in line 1518.


`void Object::_disconnect(const StringName &p_signal, Object *p_to_object, const StringName &p_to_method, bool p_force) {

	ERR_FAIL_NULL(p_to_object);
	Signal *s = signal_map.getptr(p_signal);
	ERR_FAIL_COND_MSG(!s, "Nonexistent signal: " + p_signal + ". :: "+s+);`


and i think i need to know what is p_signal , and whats its output to understand where it went wrong .... but i have no idea how ERR_FAIL_COND_MSG() works nor enough understandment of the code to know what p_signal , s are , and what do they refer too.
any help ??

**Comment by jfreedman0212** [comment]
I added some print statements above the `ERR_FAIL_COND_MSG`, along with some analysis of the code itself, and I found the values of these variables:
- `p_signal` is "tree_exiting"
- `p_to_method` is "_node_removed"
- `p_to_object` is `VisibilityEnabler`
- `Signal *s` is `NULL`
`s` being `NULL` is what causes `ERR_FAIL_COND_MSG` to trigger the error being thrown. It's `NULL` because "tree_exiting" is not a key that exists in the HashMap `signal_map`. I'm not sure what all of that means in context because I'm not super familiar with the code base, but I hope this information helps!

**Comment by xenthe** [comment]
I will work on this

**Comment by gururise** [comment]
any updates on this bug? Anyone still working on it?

**Comment by xenthe** [comment]
I'm still working on this. I should have something to report by this weekend.

**Comment by xenthe** [comment]
Sorry, I was wrong. No luck on my end

**Comment by Rastrizh** [comment]
Hi, I was working on this bug and find the problem. It's in visibility_enabler and i can fix that. I'll make PR when I've done.

**Comment by Rastrizh** [comment]
#34352

**Comment by Rastrizh** [comment]
This fixes was already added in visibility_enabler2d #34352

**Comment by qarmin** [comment]
Now this shows this error (Godot 3.2 Beta 4)
```
ERROR: _disconnect: Attempt to disconnect signal 'tree_exiting' while in emission callback. Use CONNECT_DEFERRED (to be able to safely disconnect) or CONNECT_ONESHOT (for automatic disconnection) as connection flags.
   At: core/object.cpp:1522.

```
