### ISSUE TITLE
Editor remains less bright after window in foreground is closed

### ISSUE THREAD

**Issue by SmartySmart702** [godotengine/godot#33213]
**Godot version:**
Godot 3.2 Alpha 3

**OS/device including version:**
Win 10 x64 

**Issue description:**

If you use the one click deploy feature for android and you have "use custom build" checked in the export preset then the "Building Android Project (grandle)" window comes into the foreground and the editor gets less bright because it is now in the background. But after finishing, the editor is still less bright even if it is now in the foreground.
There are a few other situations when the editor remains less bright. Easiest to explain:

**Steps to reproduce:**

- Make sure that you can use one click deploy for android
- Create a new, blank GLES3 project
- Click on the android icon 
- Now Godot asks for a main scene, click on cancel or in the background 
- Now you should see that the editor is still less bright

**Comment by akien-mga** [comment]
CC @YeldhamDev

**Comment by YeldhamDev** [comment]
Can't really play with one-click deploy stuff here, so this complicates things. Could you tell the other situations where this happen?

**Comment by SmartySmart702** [comment]
> Can't really play with one-click deploy stuff here

What about the "one click preview in browser" feature? 

- Create a new, blank GLES3 project
- Add HTML5 as export preset
- Click on the HTML5 icon
- Now Godot asks for a main scene, click on cancel or in the background
- Now you should see that the editor is still less bright

**Comment by YeldhamDev** [comment]
Oh, that. That's because currently, `Dialog`s check for any open modal before making the editor bright again, but because `PopupMenu`s don't change brightness but are still modals, they end up leaving everything dark.

A quick fix would be to check if the top modal was indeed a dialog, and if not, make the editor bright again. But this would make so that if a dialog has a popup that opens another dialog, closing it would make it erase the dim while there's still another open actual dialog.

It would be better if `PopupMenu`s closed if a `Dialog` modal opened.

**Comment by Zylann** [comment]
Similar to https://github.com/godotengine/godot/issues/32690
