### ISSUE TITLE
Sprite3D displays a white quad instead of textures [regression]

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#33234]
**Godot version:**
3.2 master (a49c8d4a).
Bisected, regression from #33097.

**OS/device including version:**
Linux, Mesa 19.2.2 (both Intel and AMD GPUs).
Both GLES2 and GLES3.

**Issue description:**
All Sprite3D render a white quad instead of their assigned texture.
It's a regression from #33097, cc @clayjohn.

**Steps to reproduce:**
- Create new project
- Add Sprite3D, assign `icon.png`
- See white quad instead of texture

**Minimal reproduction project:**
Not necessary, see above.

**Comment by clayjohn** [comment]
Im assuming this only happens on GLES2?

**Comment by akien-mga** [comment]
Actually no, that was my initial expectation but it happens for both GLES2 and GLES3. So it should be related to changes in Material.

**Comment by clayjohn** [comment]
I looked into this quickly. It seems the issue is that I haven't called "queue_shader_update()" and "change_notify()" when textures are set. I'll fix this soonish or someone else can if they get to it first. 

It may be enough to call those functions within "set_texture()" in material.cpp

**Comment by CezaryKopias** [comment]
bumping
just try new 3.2.3 rc3 compared to steam 3.2.2 using GOAT framework
![sprite3d_material_bug](https://user-images.githubusercontent.com/3462746/89508289-024c2180-d7ce-11ea-884b-69ef51afd944.png)

ive desitalted the project to include just this issue for testing
[sprite3d_material_bug.zip](https://github.com/godotengine/godot/files/5033481/sprite3d_material_bug.zip)

**Comment by clayjohn** [comment]
In the MRP you linked you are overriding the albedo texture in the ``override_material``. Previously the Sprite3D texture overrode the albedo texture in ``override_material``, but this behaviour was undocumented and inconsistent with other Spatial objects. To be consistent the ``override_material`` should override the built-in material. Further, it is impossible to have the old behaviour now that Sprite3D uses a mesh internally instead of an ImmediateGeometry.

The docs should be updated to reflect this. I'll make a PR.

**Comment by akien-mga** [comment]
Fixed by #41088.
