### ISSUE TITLE
Add to ProjectSettings Logging a Max Log Size in addition to Max Log Files

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#33242]
**Godot version:**
Any version

**OS/device including version:**
Any

**Issue description:**
There does not seem to be a user or otherwise setting to limit log file sizes. This means a log file can grow and overflow the system.

A Max Log Files setting should be added to the ProjectSettings screen and logger should be changed to rotate files when they exceed Max Log Files.

![image](https://user-images.githubusercontent.com/930478/68036932-024a4e80-fc9d-11e9-832b-ae8532baa6c9.png)

**Comment by Calinou** [comment]
When you set up multiple log files, each log file will correspond to a game instance.

I don't see how log files can become huge if you only allow 5-10 of them to be created. For a long-running server, you should manage logs differently instead (look into solutions such as [Loki](https://github.com/grafana/loki)).

**Comment by wyattbiker** [comment]
With all due respect I am talking about a game running on a user device. Not servers even though same logic applies there.

Log file messages are generated by errors/warnings/etc but also print(). If I were debugging a long running game, I may want to keep logs enabled for a while printing thousands of messages.  And what is reasonable size anyway? 

In either case it is bad practice to allow logs to be generated unchecked. You can have a runaway app creating havoc. And then end users may have a problem system and cant even use their computer because of disk full.  And why would you want devs the extra headache to worry about system overflow adding extra code to check size. 

You already have the framework to add an extra property and check and rotate for that in logger.cpp.

**Comment by Calinou** [comment]
> And what is reasonable size anyway?

A few megabytes will most likely not cause an user's device to run out of space :slightly_smiling_face:

**Comment by Zireael07** [comment]
Games, especially ones still in development, can accrue log files up to 50-70 MB.

**Comment by Calinou** [comment]
@Zireael07 The current log rotation system should already take care of that, as the default is to keep 10 log files at most (one per project start).

**Comment by Zireael07** [comment]
I meant a single log file of 50 MB (the game in question was Tales of Maj'Eyal)

**Comment by wyattbiker** [comment]
> > And what is reasonable size anyway?
> 
> A few megabytes will most likely not cause an user's device to run out of space 🙂
> 

We don't know what we don't know. Making assumptions about the user's device is not something Godot can afford. It could be a mobile device short on space.

> > You already have the framework to add an extra property and check and rotate for that in logger.cpp.
> 
> If I'm reading correctly, we'd have to perform log rotation at run-time, which adds more complexity.

Yes, it would be at runtime and no it does not any special complexity. All the code is already in place for rotation and writing. It's a matter of checking whether the log has reached a limit and calling the rotation method in logger.

**Comment by Calinou** [comment]
> It could be a mobile device short on space.

In general, you don't want to log files on mobile for two reasons:

- Most users don't know how to access them, so storing them on the filesystem is of limited use. On iOS, it's impossible unless you jailbreak your device :slightly_smiling_face:
- Experienced users can use `adb logcat` to view the running project's output.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
