### ISSUE TITLE
ParticlesMaterial in 2D has revert arrows after creation

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33285]
**Godot version:**
3.2 alpha3

**Issue description:**
When you create a ParticlesMaterial for Particles2D node, some properties can be reverted right away, e.g. this
![image](https://user-images.githubusercontent.com/2223172/68087218-e046fc80-fe53-11e9-822a-981f0ee6f23f.png)

This is because they are set after creating the material, so not sure how fixable is that.

**Comment by akien-mga** [comment]
I don't think that can be fixed without creating `ParticlesMaterial2D` and `ParticlesMaterial3D`, but I don't think it's worth it.

The reverted state is the base material for 3D, and when added to a 2D not some settings like "Disable Z" are indeed enabled.

**Comment by fsy98** [comment]
I do the same reproduce, and I thought it can't be reproduce before create the node because the node flag appear after you have created the material
<img width="119" alt="Capture" src="https://user-images.githubusercontent.com/30133945/68088413-060cdb00-fe2d-11e9-873c-909b0fe4b2e7.PNG">

**Comment by KoBeWi** [comment]
> I don't think that can be fixed without creating ParticlesMaterial2D and ParticlesMaterial3D

We can also add a new functionality to the inspector, something like "Commit value", so the current value becomes the default one. In this case it would be called after assigning the new values to the material. (if it's not possible already, see scripts and inherited/instanced scenes)

I think I've seen other cases where this could be useful.

**Comment by KoBeWi** [comment]
Still valid in 94e5f66

**Comment by akien-mga** [comment]
I don't think this can be fixed without hacks. The revertability depends on the difference between what is serialized in the scene and what it set in the Node's constructor. Here the changes are applied after the constructor and the only way to internalize them would be to create node types which subclass `ParticlesMaterial`.

> We can also add a new functionality to the inspector, something like "Commit value", so the current value becomes the default one. In this case it would be called after assigning the new values to the material. 

That could be interesting but that would require a more detailed proposal, and I think that would be more useful as something users can choose to use and not something that the editor itself uses for edge cases like this one. Supporting this would imply saving the current non-default values as some metadata so that the revert algorithm can compare with this metadata instead of the base class.

I don't think it's worth the hassle just for ParticlesMaterial though.

**Comment by KoBeWi** [comment]
So let's just close it.
