### ISSUE TITLE
Animation of AnimationPlayers with length 0 can be dragged to 0.001

### ISSUE THREAD

**Issue by AtomaFajrovulpo** [godotengine/godot#33294]
**Godot version:**

_3.2 alpha 3_

**OS/device including version:**

All

**Issue description:**

If you set the legnth of an animation in a AnimationPlayer to 0, you can drag it right and it becomes 0.001.

**Steps to reproduce:**

Create an AnimationPlayer, create an animation, set legnth to 0, drag right in editor.

![dragged](https://user-images.githubusercontent.com/55881826/68089608-90236680-fe62-11e9-8b3e-7897d39f9bd3.PNG)

**Comment by rapperdinesh** [comment]
@AtomaFajrovulpo  I want to work on this issue. Can you please offer some help ?

**Comment by Frescote** [comment]
I was investigating this issue and noticed this might be intended behavior.

According to #19420 it should not be possible to set the animation length to 0, and it isn't. So, if you attempt to set it at 0, it is instead set to 0.001, which is why it is dragable between 0 and 0.001.

However the length UI field displays 0 instead of 0.001 because of rounding (you can mouseover the field to get the real value in the tooltip).

Therefore, I am unsure if there's anything to fix here. At most, not apply the rounding in this field?

**Comment by bojidar-bg** [comment]
> At most, not apply the rounding in this field?

Or round the other field as well, so the issue is no longer evident.

**Comment by rapperdinesh** [comment]
@bojidar-bg  Can you please help me in suggesting some 'junior job' or 'good first' issues which I can try to get started with contributing in Godot ?

**Comment by gururise** [comment]
Well, the problem is the min animation length is 0.001, while the step size for the EditSpinSlider is 0.01

I think the best fix is to set the stepsize of the EditSpinSlider that sets the Animation Length to match that of the min animation length of 0.001

The other option would be to set the minimum animation length to 0.01; however, there is some [code from reduz](https://github.com/godotengine/godot/blame/fa4f5252160f23b228b695b40fa49803eae6bdcc/editor/animation_track_editor.cpp#L1506) that seems to indicate that 0.001 should be the minimum.
