### ISSUE TITLE
Issues with a corresponding merged pull request should be closed.

### ISSUE THREAD

**Issue by justchen1369** [godotengine/godot#33346]

**Comment by akien-mga** [comment]
Why? Could you be more specific?

Issues are closed once they are fixed in the master branch. A proposed fix may not be merged, so we don't close issues before merging PRs.

**Comment by Calinou** [comment]
This is done automatically if the PR description or commit message contains "closes #xxxx" (or "fixes #xxxx", "resolves #xxxx") in the description. If not, it has to be done manually.

**Comment by Xrayez** [comment]
> If not, it must be done manually by the issue poster or someone with repository permissions.

I wonder how many opened issues are there which are already fixed but not closed that way, I think this is what this issue is about. @justchen1369 please provide a list of such issues that must be closed.

**Comment by Zireael07** [comment]
I assume quite a lot, since the auto-closing is a fairly new feature...

**Comment by KoBeWi** [comment]
About 6 months ago I did a full sweep over all existing issues and commented on anything that's already fixed. If some non-closed-fixed issues exists, they are probably recently fixed (some PR authors aren't aware that there's an issue that their PR closes) or I couldn't test them during my run (mostly platform-specific issues etc.).

Anyways, instead of making an issue about issues, if you find something that should be closed, just leave a comment and someone will close it. (if you do this enough times, you can get bugsquad pass :v)

**Comment by akien-mga** [comment]
> I assume quite a lot, since the auto-closing is a fairly new feature...

It's actually fairly old, at least I can't remember a time where the feature didn't exist (so it must have been around already when I started being active on GitHub projects maybe 7 years ago).

Usually we're on the lookout to make sure that PRs properly include auto-closing keywords if we're aware that they're actually fixing an issue.

In other cases as mentioned by @KoBeWi, we sometimes simply don't know/remember that an old issue exists for what the PR solves, so we usually find this later when we ask people to test old issues after a release to confirm if they're still relevant.

In any case, not sure what this issue is about, but any issue with only a title and no content is probably not worth spending too much time on. Suggestions on workflow improvements are welcome, but this is a bit too terse.
