### ISSUE TITLE
Rigidbody 2D platformer example is broken in v3.2.alpha

### ISSUE THREAD

**Issue by Gooberpatrol66** [godotengine/godot#33395]
**Godot version:**
 v3.2.alpha.custom_build.dc114fa2e

**OS/device including version:**
 AMD CAICOS (DRM 2.50.0 / 5.2.0-gentoo, LLVM 8.0.1)

**Issue description:**
Assets are offset up and to the right, causing player to float, enter walls, get stuck, and fall through the world.
https://imgur.com/a/LVLYG2Y

**Steps to reproduce:**
Make new project with Rigidbody 2D platformer template

**Minimal reproduction project:**

**Comment by pouleyKetchoupp** [comment]
This is caused by all the collision in the tilemap having their offset wrong when loading the old project, because `shape_offset` property in `TileSet` resources has lost retro-compatibility with this change:
#31050
CC @codecustard

`shape_offset` property is saved before the list of shapes in the old format:
```
0/shape_offset = Vector2( 32, 32 )
0/shapes = [ SubResource( 1 ) ]
```

Whereas in the new format, it's saved as `shape_transform` for each shape in `shapes`.

Previously, during loading the offset would be stored as a first entry in the shape list, and then used as a default value when loading the shapes:
```
else if (what == "shape_offset")
	tile_set_shape_offset(id, 0, p_value);
```

With the current code, the value is lost when loading the resource because the shape list is empty:
```
else if (what == "shape_offset")
	for (int i = 0; i < tile_get_shape_count(id); i++)
		tile_set_shape_offset(id, i, p_value);
```
