### ISSUE TITLE
Wheel Up and Wheel Down "buttons" apparently not working in InputMap

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3340]
After some debugging on IRC with @samuncle, it appears mouse wheel scroll events can't be used via the InputMap. It's possible to assign the "Wheel Up Button" and "Wheel Down Button" of a mouse to actions, but they don't seem to be triggered when scrolling the wheel.
On the other hand polling for mouse wheel events works just fine.

**This works:**
```
func _input(event):
	if event.type == InputEvent.MOUSE_BUTTON:
		if event.button_index == BUTTON_WHEEL_UP:
			print("wheel up (event)")
		if event.button_index == BUTTON_WHEEL_DOWN:
			print("wheel down (event)")

func _ready():
	set_process_input(true)
```

**This does not work:**

![script1](https://cloud.githubusercontent.com/assets/4701338/12302758/2b3337d8-ba27-11e5-871b-a1058bb548a3.png)
```
func _fixed_process(delta):
	if Input.is_action_pressed("wheel_up"):
		print("wheel up (action)")
	if Input.is_action_pressed("wheel_down"):
		print("wheel down (action)")

func _ready():
	set_fixed_process(true)
```

Do we misunderstand the meaning of the "Wheel Up" and "Wheel Down" mouse "buttons" in the InputMap, or are those non-working?

Tested on Linux 64-bit, current master branch.

**Comment by eska014** [comment]
Mouse wheel up/down "buttons" are never in a "pressed"-state other than during the events themselves (e.g. during the input event callbacks). Since you can't really keep the mouse wheel "pressed" up or down.

Before one can test with the `Input` singleton (outside event callbacks), the release event has already passed, right after the pressed event.

Workaround: Using the input event callbacks.

We could probably force the `Input` singleton to consider them in pressed state for a render frame. But `_fixed_process` might still not work, depending on the frame rates. Maybe not a good idea.
In general, the `Input` singleton can only be used to track current state, not what just passed (or echo, release, etc).

Maybe the best solution would be to rename `Input` singleton to `InputCurrentState` or something (hopefully shorter).

**Comment by akien-mga** [comment]
That makes sense, thanks. I guess the best solution is to drop those mouse wheel up/down "buttons" from the InputMap altogether?

**Comment by eska014** [comment]
Wheel up/down actions should work perfectly with `InputEvent.is_action`(`_pressed`/`_released`) or when using the `Input` singleton during the callbacks.

**Comment by RebelliousX** [comment]
For mouse wheel up and down a simple pressed state would be problematic too, since I believe
we should calculate the "delta" of the wheel how much it scrolled up (positive) or down (negative), idle (0). This would allow the event to be aggregated. Imagine an angry user trying as hard as he can to scroll down a webpage with a mouse wheel, and the webpage scrolls one line at a time. I hope you get my point.

**Comment by SuperUserNameMan** [comment]
I stumbled on this one while searching for something else, and this reminded me a previous attempt to make mouse wheel working with `InputEvent.is_action(whatever)`.

As there was some enlightening exchanges with Reduz and Punto, here are their references :

Related issue : #1636
Related PR : #1640

**Comment by eska014** [comment]
Closing as not an issue.
If anyone having issues with this finds their way here, check my comments above for explanation

**Comment by Raulvgz** [comment]
This is the way to capture wheel mouse in Godot from C#.

    public override void _UnhandledInput(InputEvent @event){
        if (@event is InputEventMouseButton){
            InputEventMouseButton emb = (InputEventMouseButton)@event;
            if (emb.IsPressed()){
                if (emb.ButtonIndex == (int)ButtonList.WheelUp){
                    GD.Print(emb.AsText());
                }
                if (emb.ButtonIndex == (int)ButtonList.WheelDown){
                    GD.Print(emb.AsText());
                }
            }
        }
    }

**Comment by Vasanthan-** [comment]
When using INPUT MAP:
Wheel up/down action works only with **InputEvent.is_action_just_released(action)**
