### ISSUE TITLE
Default values sometimes behave weirdly

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#33413]
**Godot version:**
3.2 beta1

**Issue description:**
This one is cryptic. I observed weird behavior with exported variables that have default value. The intended behavior is that anything with default value is not stored in tscn. Well, it sometimes happens that it's stored. I have a script with export variables like these
```
export var sprite: Texture
export var once := false
export var permanent := false
export var transparent := false

export var generate_shape := false
```
I have a scene with a node with this script attached and there's the sprite and transparent is set to true, everything is false. Today I opened this scene and noticed that other variables appeared in the tscn with false value. I didn't modify the scene, it just happened. I reverted the file, but it still appeared after saving. It stopped after I restarted the project.

Another case I had was slightly different. I had a variable like `var variable: float`. For whatever reason it was serialized as "null" until I explicitly declared it as `var variable := 0.0`. I can't reproduce it anymore.

So uh, I though I would report the issue, but I don't know how to reproduce it yet. It happened tho.

**Comment by KoBeWi** [comment]
I noticed that it (probably) happens only in tool scripts. Could be related to #33688 somehow (like, it's about tool and export...)

**Comment by KoBeWi** [comment]
Ok, so here's some repro
[ReproductionProject.zip](https://github.com/godotengine/godot/files/4242582/ReproductionProject.zip)

Notice how Node2D.tscn has `right = false` under Abyss, even though it's a default value. This will always appear, but it will stop appearing when you save the script to a file (it's built-in). The script I quoted in the OP wasn't built-in though (probably...), so not sure how much is this related.

**Comment by pouleyKetchoupp** [comment]
I was able to reproduce this issue with a minimal project:
[default-values.zip](https://github.com/godotengine/godot/files/4585708/default-values.zip)

Godot version: 3.2.1 stable
OS: Windows 10

It happens when a tool script is used in the scene, but not loaded in the script editor when you save.

Repro steps in the attached project:
- Open project
- Open node.tscn
- Save
- Check node.tscn in text editor: it contains `test_string = "default"` (this is wrong)
- edit the test.gd script in the scene
- Save again
- Check node.tscn in text editor: the line has disappeared (which is correct)

This has happened a lot to me on a medium size project, but it seemed random at first due to the fact it happens only when the script is not being edited.
