### ISSUE TITLE
set_surface_material not displaying in scene

### ISSUE THREAD

**Issue by UnmannedOcelot** [godotengine/godot#33467]
**Godot version:**
v3.1.1.stable.official

**OS/device including version:**
Windows 10 Pro 64bit

**Issue description:**
When using set_surface_material to change a mesh's color, the new material is not shown in the scene. It will return correctly if I use get_surface_material, however the change is not visible. 

If material_override is used instead, the new material will display in the scene. However, I am then unable to detect the material with get_surface_material. I am also unable to affect the material with interpolate_property.

![25fdb9b13617ca80fa6c60dc7f6f7dd8](https://user-images.githubusercontent.com/53127422/68520243-a747c700-025b-11ea-94bd-abde44f89843.png)

**Steps to reproduce:**
View attached project

**Minimal reproduction project:**
[RenderingIssue.zip](https://github.com/godotengine/godot/files/3826800/RenderingIssue.zip)

**Comment by clayjohn** [comment]
Material_override overrides the surface material. So if you set both, you will only see the material_override.

**Comment by UnmannedOcelot** [comment]
> Material_override overrides the surface material. So if you set both, you will only see the material_override.

Correct. However, even if I only use set_surface_material, it does not show on runtime.

**Comment by UnmannedOcelot** [comment]
Somehow on my main project set_surface_material is now working. I have no idea how. Although, I still can't affect it with interpolate_property.
I loaded up the sample project that I uploaded to check it and set_surface_material still isn't working there.

**Comment by KoBeWi** [comment]
Seems like the problem is no warning for invalid property, because the code is bad (although `set_surface_material` could be broken before 3.2).

Anyways, set the material with:
`mesh.set_surface_material(0, new_material)`

And then do either
`tween.interpolate_property(mesh, "material/0:albedo_color", GREEN, RED, 2, Tween.TRANS_LINEAR, Tween.EASE_OUT)` 
or
`tween.interpolate_property(new_material, "albedo_color", GREEN, RED, 2, Tween.TRANS_LINEAR, Tween.EASE_OUT)`
