### ISSUE TITLE
Camera "project_position" bug returns always (0,0,0) given no depth

### ISSUE THREAD

**Issue by XnetLoL** [godotengine/godot#33493]
**Godot version:**
Godot 3.2 beta 1

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
The function "project_position" now admits a depth parameter, but when you write 0 or no parameter at all (which is by default 0) the returned position is always (0, 0, 0).

**Steps to reproduce:**
Create new 3D scene, put a camera, and write "print(project_position(get_viewport().get_mouse_position()))" in the "process". You should get the mouse position in the 3D world. If you write no value or "0" value, the position will always be (0, 0, 0).
[https://i.gyazo.com/c37ee2be94da34b55955c794fea17744.png](url)

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Confirmed. It's a regression, 3.1.1 works fine.

Likely caused by #29248, CC @Cheeseness.

**Comment by hammeron-art** [comment]
I can't reproduce in v3.2.beta.custom_build.3aeb43f14. I've been using it for some time and it works as expected.

Where are you positioning the camera and what value do you want to get? Depth 0 will always return the camera position in global space no matter the screen_point since the 0 plane is the start of the projection and it has no area.

**Comment by XnetLoL** [comment]
I don't move the camera. I create a new 3D scene and add a camera. Then I attach a script using this function.
Here's an example:  https://drive.google.com/open?id=1U95PsifdKCcDNHhPjH-lEl8jzCAlP-G0
I downloaded this godot version from here: https://downloads.tuxfamily.org/godotengine/3.2/beta1/
(win64 version).

**Comment by hammeron-art** [comment]
I think you misunderstand how ray casting works. You need a distance from the camera (depth) to be able to find a position in 3D space with the mouse. The previous version as the same as `project_position(get_viewport().get_mouse_position(), near)`. It was hardcoded to use the near plane value as the depth which isn't useful.

You use `project_position` when you know what distance from the camera the point has to be. A more common approach is to use a collision object and the method described here:
https://docs.godotengine.org/en/3.1/tutorials/physics/ray-casting.html#d-ray-casting-from-screen

**Comment by XnetLoL** [comment]
I was thinking of that near value hardcoded you mentioned (but I edited my comment).
Then it's not a bug. Anyway, I think the default value should be 'near', instead of 0.

Closing this issue, thanks for replying.

**Comment by akien-mga** [comment]
It's still a compatibility-breaking change in how the method works between 3.1.x and 3.2, so it should be documented as such in the changelog (CC @Calinou).

About the default value, apparently @reduz advocated for using 0. I'm not sure why.  But I guess we can't really make it default to `z_near` as it's a property and not a static value.

Maybe instead of 0 there shouldn't be any default value, to force users to set something?

**Comment by Cheeseness** [comment]
I initially wrote #29248 without a default value because I don't believe that the function has any default/common use-case for a default value to address.

My initial feeling was that with no default, anybody who previously used the function would immediately discover that its nature had changed and look towards the documentation. Having a default value probably obscures that a little.

**Comment by akien-mga** [comment]
I PR'ed #33501 to remove the default value, I agree that it does more harm than good.

@Calinou Can you mention in the changelog that the API changed in a compat breaking way (now expects two arguments), and that to get back the 3.1 behavior one should use `near` as second argument?

**Comment by Calinou** [comment]
@akien-mga Done.
