### ISSUE TITLE
Total Crash: Screen Glitch

### ISSUE THREAD

**Issue by ThePublicHacker** [godotengine/godot#33605]
**Godot version:**
v3.2.beta.custom_build.14e52f7ae

**OS/device including version:**
Lenovo Ideapad 330 8GB RAM/AMD Ryzen 5 2500U/256GB M.2/AMD Radeon Vega 8 - W10 19.03 (Build 18362.418)

**Issue description:**
The screen turns into red, blue and yellow colours with small points randomly located. Ctrl+Alt+Supr doesn't work. The only way to turn off is ACPI Off

**Steps to reproduce:**
1. Start Godot Engine 3.2
2. Open a Godot Engine 3.1 3D Project
3. The bug appears at the moment

**Minimal reproduction project:**
[Pruebas-VR.zip](https://github.com/godotengine/godot/files/3843454/Pruebas-VR.zip)

**Comment by Calinou** [comment]
Does this occur in other 3D applications or games?

**Comment by lawnjelly** [comment]
I tracked it down to the images in res folder. I thought there was a problem with background.png, however the same file will load in another fresh project, so I now believe the problem is caused by there being 2 textures in res/ folder with the same name:

background.jpg and
background.png

This seems to be confirmed if I rename one of these to background2.png for example, the project will load.

**Comment by KoBeWi** [comment]
Can't reproduce in 0a96235b4

@ThePublicHacker Try removing your .import folder and testing again.

**Comment by ThePublicHacker** [comment]
@Calinou No, only in this version of Godot
@KoBeWi I'm gonna try and test it again

**Comment by lawnjelly** [comment]
Be sure to try renaming one of the background textures as I wrote in my post. I also got a crash in the graphics driver, so I'm assuming it was the same bug.

**Comment by ThePublicHacker** [comment]
I've got some troubles with my GitHub account, and I've tested it.
After deleting my .import folder it worked correctly.
