### ISSUE TITLE
ERR_COMPILATION_FAILED in the terminal when opening a project using singleton autoloads

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3361]
Though @reduz worked around the issues we were having with singleton autoloads (#3156), there is still a trace of it when you start a project in a terminal:

```
ERROR: GDScript::reload: Compile Error: Identifier not found: my_autoload
   At: res://new_scene.gd:5.
ERROR: reload: Method/Function Failed, returning: ERR_COMPILATION_FAILED
   At: modules/gdscript/gd_script.cpp:1889.
```

It stills works just fine, but this error hints that it's maybe still not 100% clear how such singleton autoloads are initialised.

See this minimal example that reproduces the issue: https://up1.ca/#bE6ZikY3SeEHUt03RM0rRw
Just start it with ```godot -e``` and you'll see the error in the terminal.

**Comment by reduz** [comment]
not sure why it throws this error (not sure why it's trying to compile the script either), but it should be harmless.. will check it later

**Comment by akien-mga** [comment]
Yes everything works fine otherwise, it's just some potentially annoying noise :)

**Comment by reduz** [comment]
The error is not wrong per se, because scripts need to be pre-parsed on load in case they are tool scripts, even if they are not and unused afterwards. Because of this it's expected to see these errors in the console.

However, to avoid unnecesary flooding stdout, I just added a small check to see if this is a tool script while it's being compiled and if not, then just simply avoid throwing any error.
