### ISSUE TITLE
Opening gdscript file from FileSystem and File menu created double instance in script tab

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#33654]
**Godot version:**
Godot 3.2 beta 1

**OS/device including version:**
Windows 10

**Issue description:**
if you open the script file from FileSystem and then you open the same script file from File > Open... (in script tab) notice that the script open as different instance.
![image](https://user-images.githubusercontent.com/8316851/68990723-22773180-0889-11ea-9114-b1d0ff8dd551.png)
And if the script have a class_name editor will show Unique global class error
![image](https://user-images.githubusercontent.com/8316851/68990730-476ba480-0889-11ea-8015-00ea6b089e73.png)

**Steps to reproduce:**
Make a new project
Create a new script (in FileSystem right click and pick New Script.. leave default and press Load)
Double click the new script in FileSystem so it open in script tab
In script tab select File > Open... , notice the script open as new instance

**Minimal reproduction project:**
Just do the reproduction step.

**Comment by Eoin-ONeill-Yokai** [comment]
Hey I've just tried this on master branch and I cannot reproduce the expected results. Could you perhaps give us more details on how your files are organized? 

Alternatively, if you have the Godot source code, could you also try this on master and see if you can reproduce the results?

**Comment by earlroxas13** [comment]
I use the same Project that I uploaded in my another bug report here #33667 
Im using Godot 3.2 beta 1 to test.
Try using it, if reproduced using beta 1 and unreproduced with master means that the issus already fixed.
Sorry I cant try the master. I dont have access to it (cant build)

**Comment by amisner2k** [comment]
Can confirm this is also happening to me. Opening a script from the File-> Open... menu in the Script Editor seems to treat the script as a unique resource than when opened via the File System dock.

1. Open a script from File System
2. Open that same script using File->Open... from Script Editor
You should see the script listed twice in the scripts list in the Script Editor.

If the script in question uses `class_name` then you should also get the "Parse Error: Unique global class 'name' already exists" error in the Output dock.

In my screenshot below, I get the parse error even if I haven't already opened the script using File System (it will happen solely from opening via File->Open...

The problem seems isolated to opening the script from File->Open...

![image](https://user-images.githubusercontent.com/55228705/69397592-b0915480-0c9b-11ea-864d-c6988d0a88dc.png)

**Comment by chrisphyffer** [comment]
I believe I found a solution. This may be related to the `.tscn` file storing a path that may have been _Uppercased_ or _lowercased_.

For example, I renamed a directory `characters` to `Characters` in windows. This directory housed character scripts. I then got the issue you are having now. I then did a search in my IDE for `res://**c**haracters/` in all `.tscn` files, then replaced all occurences with `res://**C**haracters/`, and the problem (for me anyways) was solved.
