### ISSUE TITLE
Mouse state does not change when trying to resize panels.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3366]
After tonight's pull of bit changes, when trying to change the panels width or hight be it in inspector, scene, filesystem or edited animation, the panels do resize, but my mouse cursor does not change any more into left-right arrow or up-down arrow, but remains normal/unchanged arrow. 
I don't know if it's related but I have noticed lots of errors in godot running console. Errors that look like:
At: core/object.cpp:1463.
ERROR: disconnect: Disconnecting nonexistent signal 'size_changed', slot: 2221:_size_changed

Every time the number after object.cpp:  was different.

My system is Xubuntu 14.04 LTS 64-bit.

**Comment by akien-mga** [comment]
I can confirm the issue in the current master branch.

**Comment by neikeq** [comment]
Same for the script editor. It displays normal cursor when hovering text, instead of the text cursor.

**Comment by reduz** [comment]
I just moved code around, so I'm unsure why this broke, relevant code is
here:

https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1797

which used to be here:

https://github.com/godotengine/godot/blob/0860f3c196e6228f65ca5fee4c077b4509d77175/scene/gui/control.cpp#L1226

Won't be able to check why this is broken until tomorrow night, so if
anyone wants to give it a try, feel more than welcome.

**Comment by neikeq** [comment]
After checking it, the cursor shape is being changed properly, but it instantly resets to the normal cursor (arrow) after that.
I am not sure, but I think the problem may be with the _[Viewport::_gui_find_control(const Point2& p_global)](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1427)_ method, because [this condition](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1750) is true when hovering the split separator or text in the script editor, and that's what resets the cursor.
