### ISSUE TITLE
 Error in class KinematicBody2D

### ISSUE THREAD

**Issue by IuryBorges1993** [godotengine/godot#33695]
tested ongodot 3.1 +

**Ubuntu 18.4:**

Error in class KinematicBody2D, I was trying to port a code to a module in c ++, when finalizing all right just this part of buga code ->velocity = KinematicBody2D::move_and_slide(velocity, Vector2(0, -1)); <-line 94 in player.cpp

When running the editor appears following errors:

1º:

E 0:00:00:0567   Condition ' !is_inside_tree() ' is true. returned: get_transform()
  <C Source>     scene/2d/canvas_item.cpp:478 @ get_global_transform()
  <Rastreamento de pilha>playerModule.gd:20 @ _physics_process()

2º
E 0:00:00:0590   Condition ' !body->get_space() ' is true. returned: false
  <C Source>     servers/physics_2d/physics_2d_server_sw.cpp:1052 @ body_test_motion()
  <Rastreamento de pilha>playerModule.gd:20 @ _physics_process()

I used in gdnativee works perfectly, can test:
https://github.com/IuryBorges1993/gdnativePlayerMoviment

here are project plus the module where the problem:
https://github.com/IuryBorges1993/playerModule

is, velocity = KinematicBody2D::move_and_slide(velocity, Vector2(0, -1)); <-line 94 in player.cpp

**Comment by akien-mga** [comment]
It's unclear what the issue is in this issue exactly. This issue tracker is for engine bugs but here it looks like there's an issue with your module and you're looking for help to debug it, but this is not the right place for that. I would suggest using one of the other [community platforms](https://godotengine.org/community/) (if this is still relevant after close to a year).

If an actual engine bug is found after debugging, then you're of course welcome to open a bug report with clear steps to reproduce it.
