### ISSUE TITLE
Drag & Drop node to scripts sometimes handles incorrectly

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#33704]
**Godot version:**
3.1.1 - 3.2beta1

**OS/device including version:**
Win10

**Issue description:**
Sometimes drag&drop behaves incorrectly - instead pushing string to the script it focus to the scene. This is very irritating and should be fixed ASAP.

**Steps to reproduce:**

![bug](https://user-images.githubusercontent.com/3036176/69053505-97c63c00-0a1a-11ea-8061-d6db1fbeb63f.gif)

**Minimal reproduction project:**
It's easy to reproduce in any simple project...

**Comment by KoBeWi** [comment]
You can press F3 while still dragging to open script editor again.

**Comment by name-here** [comment]
It's probably because of something set to show the thing in the scene when it is clicked on.  If this is intended behavior(it seems like it would do more harm than good, though), then it should only show it on mouseup if the mouse is still hovering over the item, rather than showing it on mousedown.
