### ISSUE TITLE
Enabling "Expand" size flag on UI elements doesn't change anything

### ISSUE THREAD

**Issue by Knuckl3head** [godotengine/godot#33717]
I don't know if this issue is caused by my idiocy or if it's actual bug. If it is my idiocy, please correct me, so that people with this issue in the future may be able to Google and find what they need.

**Godot version:**
v.3.1.1.stable.official, version provided by steam

**OS/device including version:**
Windows 10 Professional build 1903
Ryzen 5 1500X w/ 16gb RAM @ 2133 MHz
Radeon RX 570

**Issue description:**
Enabling the Expand size flag on both the Vertical and Horizontal options achieves nothing on PanelContainers, VBoxContainers, Labels, and LineEdits.

**Steps to reproduce:**
I couldn't figure a precise, step by step way to reproduce this issue. The best I could say is "Enable the Expand Vertical and Expand Horizontal size flags for an entire node tree of UI elements," so for more precision, I recorded a video demonstrating the bug and it's recreation.
[https://www.youtube.com/watch?v=7k7b999vVFw](
https://www.youtube.com/watch?v=7k7b999vVFw)

**Minimal reproduction project:**
This is the exact same project that I demonstrated in the video.
[SizeFlagExpandBug.zip](https://github.com/godotengine/godot/files/3860281/SizeFlagExpandBug.zip)

**Comment by groud** [comment]
The expand flag is only used for Controls within some Containers. For the video, you should resize the parent container, then you will see that the expanded controls will take the full available space instead of keeping their minsize. So all you see here is expected.

If you need more info, you can [read the documentation](https://docs.godotengine.org/en/3.1/tutorials/gui/gui_containers.html#size-flags) or ask advises on the [other community channels](https://godotengine.org/community) :)
