### ISSUE TITLE
Flickering of textures and part of models when imported 3D model is big

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#33727]
**Godot version:**
Godot 3.2 Beta 1
**OS/device including version:**
Ubuntu 19.10, both GLES 3 and GLES 2
**Issue description:**
When I imported to Godot model with default scale(in Godot model appears as sphere with radius +- 11000 units), then when I change camera position, model starts flickering
![jfile](https://user-images.githubusercontent.com/41945903/69128608-018f2600-0aad-11ea-81e5-8adb6932c73b.gif)

flickering only appears when camera is far away, when camera is close to objects, there flickering disappears

![jfile](https://user-images.githubusercontent.com/41945903/69128799-5fbc0900-0aad-11ea-86de-4f94b5ccbefa.gif)

but when I change scale to 0.01, then flickering gone
![jfile](https://user-images.githubusercontent.com/41945903/69128484-ae1cd800-0aac-11ea-9f62-232e33db12b7.gif)

I think that can be related to double precision floats, but I can be wrong.

**Minimal reproduction project:**
[tiki_treasure.zip](https://github.com/godotengine/godot/files/3862654/tiki_treasure.zip)

**Comment by Calinou** [comment]
If you're working at a large scale, you'll want to increase the camera's Near value (both in the camera node and the editor camera using the View menu).

**Comment by lawnjelly** [comment]
It looks like z buffer fighting. You need to tune the near and far values of cameras you are using (both the IDE viewport and the game cameras) according to size of the world you are using (or rather your desired view distance).

This isn't really a bug per se, it's just how z buffers work. With godot (and most standard setups) you have more z precision close the camera than further away, hence less z fighting closeup.

Instead of fixed near / far, you could have a viewport camera in the IDE (or in game for that matter) that dynamically adjusts near and far planes according to the camera position / world size, but that might cause issues itself.

**Comment by aaronfranke** [comment]
This is expected, but it might be solved in the future, see the discussion in https://github.com/godotengine/godot/pull/33207. What I would love to see is multiple cameras per viewport implemented, and used in the editor, so that we can have ultra-large and small scales at the same time without flickering.

**Comment by Calinou** [comment]
I think it's mostly a documentation issue right now. We should find a documentation page where we can mention caveats related to large-scale rendering.

**Comment by Calinou** [comment]
This caveat is now documented in [3D rendering limitations](https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html), closing.
