### ISSUE TITLE
The "Inspector" dock resizes itself when selecting a node with a long name

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#33741]
**Godot version:**
3.2 beta 1 mono

**OS/device including version:**
win10 64 home

**Issue description:**
Selecting some nodes causes the editor (the inspector doc) to resize windows called "docs" by itself.
I think that should not happen, simply if there is not enough space all the editors draw what fits in the space.

Size resizing occurs in the "Inspector" and "Node" right zone.

**Steps to reproduce:**
Simply select the "AnimationPlayer" node and then the "CollisionShape2D" node.

In the gif you can see that I allocated a lot of space and still, the editor is still resizing.
This cannot happen even if there is not enough space, the buttons and all panels must maintain their fixed position as long as the user does not change it.

![GIF](https://user-images.githubusercontent.com/19652075/69166213-2d34ff00-0af3-11ea-8198-844f8a1b2cc9.gif)

This cannot be a problem of space because there is enough room to draw everything.

![GIF](https://user-images.githubusercontent.com/19652075/69167116-b3057a00-0af4-11ea-9101-89f4abe33216.gif)

**Minimal reproduction project:**
[testEditor.zip](https://github.com/godotengine/godot/files/3864967/testEditor.zip)

**Comment by vitorbalbio** [comment]
I think this is based on name size. If the name is short it do not happen.

**Comment by Jiaming00** [comment]
After many attempts, I think the real problem is:
When adjusting the window size, if the scene window reaches the minimum width and affects the node window, then when you click on a node with a relatively short name (assuming there is a threshold here), the node window width will automatically adjust (the purpose is not clear, it may be Is it for the full display of node names? But there is a problem with the logic.) When you click on a node with a relatively long name, the node window width will not be adjusted automatically.
![](https://github.com/Jiaming00/lib0/raw/master/godot_editor_bug_02.gif)

**Comment by avencherus** [comment]
Seems to go back quite a bit, bisected it to f275de24eeebf954736f3a1278ed8875e7f861d6

@YeldhamDev Not sure though why, or if it runs deeper still.

**Comment by Torguen** [comment]
Hi, this is still happening in 3.2 stable.
I think it's the same problem or am I wrong?
![GIF](https://user-images.githubusercontent.com/19652075/73370268-3fca7200-42b4-11ea-890d-5dc18d38af72.gif)

**Comment by YeldhamDev** [comment]
@Torguen Does this only happens when clicking nodes in the remote tree? If so, it means that the warning needs to have it's text clipped as well.

**Comment by Torguen** [comment]
It seems so, it only happens in the case you mention.
