### ISSUE TITLE
Why there is a big difference between SpatialShader and VisualShader?

### ISSUE THREAD

**Issue by epth** [godotengine/godot#33753]
![图片](https://user-images.githubusercontent.com/25238420/69210813-fc0e0a80-0b96-11ea-9bb0-1d09401acba9.png)
SpatialShader is Left,VisualShader is right
I want to know how to set paramters to make VisualShader same as SpatialShader.

![图片](https://user-images.githubusercontent.com/25238420/69210963-7b9bd980-0b97-11ea-9393-6e13df03a7af.png)
![图片](https://user-images.githubusercontent.com/25238420/69210990-8ce4e600-0b97-11ea-9f1e-bad962f39295.png)
[gametest.zip](https://github.com/godotengine/godot/files/3867428/gametest.zip)

**Comment by clayjohn** [comment]
The difference is that proper sRGB conversion is not happening with your VisualShader. You are reading the pixel values from the image as raw data instead of as Color values. In order to fix this, you need to select underneath the image in your Texture node where it says "Data" and instead select "Color"

Also, in the future, please do not ask questions on here. it is for bug reports only.
