### ISSUE TITLE
move_and_slide weird behavior

### ISSUE THREAD

**Issue by git2013vb** [godotengine/godot#33849]
**Godot version:**
3.2.beta2

**OS/device including version:**
Wind 7 64/linux
**Issue description:**
Is difficult to explain: I use mouse to move a kinematicbody. If i let the mouse pointer at same place (screen position) the kinematicbody object move instantaneous  in mouse position. 
**Steps to reproduce:**
click in any position (better top or down in relation kinematicbody position) , keep mouse still click again and again.

**Minimal reproduction project:**
in attachment
[test_process.zip](https://github.com/godotengine/godot/files/3882948/test_process.zip)

**Comment by KoBeWi** [comment]
This is because of
```
if gap.abs() < Vector2(1,1):
```
It returns true if x is lower than 1. That's how vector comparison works (#9284 might be related here). You should rather use `if gap.length_squared() < 1` instead.

Also for the future, if you are not sure if something works as intended (this one clearly does), try [other community channels](https://godotengine.org/community) before submitting an issue.

**Comment by git2013vb** [comment]
Thank you,
I will be pleased to use alternative solution IF I have knowledge how they work ;)
"Returns the vector's length squared. Prefer this method over length() if you need to sort vectors or need the squared length for some formula." as description about lenght_squared , in my opinion, is not enough to describe me how this func have to be used. As developer myself I prefer to complete my "job" , especially when it involves other people, with a detailed example and uses case related what I did. write code without docs is 1/2 of what have to be done.  

Anyway thank you for your effort to explain me what other people didn't bother to do in first place. You are awesome. :))
