### ISSUE TITLE
RichTextLabel remove_line don't respects wrapping - new functions needed?

### ISSUE THREAD

**Issue by letsgamedev** [godotengine/godot#33912]
Hello,

In **3.2beta2** I try to make a textbox with a RichTextLabel.
The Label automatically adds line breaks.

**get_line_count** will always return 1 cause the base text is one long string.
**get_visible_line_count** returns the correct amount of visible lines.

**remove_line** removes the whole line, that is okay if there would be a function called **remove_visible_line** :)

So it would be intuitive to remove lines and go through the text.
Also, the **scroll_to_line** only takes the not wrapped text into account, so there should be a **scroll_to_visible_line** function so I can scroll the text the way it would make sense.

Tom

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
