### ISSUE TITLE
bug android report export iluminaciones 

### ISSUE THREAD

**Issue by matiashak** [godotengine/godot#33919]
![godot](https://user-images.githubusercontent.com/58227174/69657555-ba8bcc80-107a-11ea-92aa-fe42ac13680c.png)

**Godot version:** all version

**OS/device including version:** android apk 5.0

**Issue description:** lo que me e dado cuenta en varios proyectos para testeo que e realizado son que la iluminacion afetan alos modelos y hacen que desaparescan del escenario al exportar con ilumniacion ya sea del "Sky" o en nodo lo que he realizado fue activar el "Clear Color" estaria bueno que verifiquen ese bug ya que es muy importante para el desarrollo de juegos para sistemas moviles  
gracias por su comprension y sigan asi el engine sera uno de los mas grandes y podra competir contra los grandes engine 
**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Sorry for the late answer.

Bug reports should be written in English (it's ok to use a translation tool for that) so that all contributors can read them.

Moreover, we need detailed steps to reproduce and/or (ideally) a minimal reproduction project to be able to confirm the issue and possibly fix it. As this information is missing, there's nothing we can do for this issue so I'll close it.
