### ISSUE TITLE
请问godot在windows上运行会产生图像抖动的问题怎么解决

### ISSUE THREAD

**Issue by 2439905184** [godotengine/godot#34036]
我是一个godot的中国用户，在windows平台用godot做游戏时发现会产生图像抖动的问题，请问怎么解决。
我在官网看了相关解释，还是不知道该怎么解决。如果我想窗口运行游戏，而且图像不发生抖动怎么解决。unity3d引擎做的游戏在窗口下运行也一般不会产生这个问题,我也试过copper cube的引擎，也不会发生抖动，但是编写代码比godot更加困难，我喜欢godot的gds，还有godot的场景实例化的功能。
I hope godot will get better and better.
[netxt translated by bai du translate]
I'm a Chinese user of Godot. When I play games with Godot on Windows platform, I find that there will be image jitter. How can I solve this problem.
I read the relevant explanation on the official website, but I still don't know how to solve it. If I want the window to run the game, and the image does not shake how to solve. The game made by unity3d engine will not cause this problem when running under the window. I've tried the engine of copper cube, and won't shake. But it's more difficult to write code than Godot. I like the GDS of Godot and the scene instantiation function of Godot.
I hope godot will get better and better.

**Comment by Bucham** [comment]
Hi, I don't know if that's what you mean, but after researching and testing several things, the way that worked for me, was activating the borderless and fullscreen options, which are in project / project settings / display / window. With that, it works practically perfect, only very occasionally it gives some low of frames, but practically never. It's a bit annoying, because the screen will always occupy the entire monitor when you play, but it's worth it, I activate and deactivate those options, depending on whether I want to take a quick look or try the game for a while. As I understand it, it is a problem with the update of the monitors' hardware or something like that, and it cannot be solved until vulcan arrives in Godot 4.0. Or so I understand.

**Comment by fsy98** [comment]
告诉我你的具体问题至少按照他的要求给一个可执行的案例之类的， 还有你使用的版本

**Comment by Calinou** [comment]
Judging by the translated text, this should be solved by #33414 which is now merged (but disabled by default).

**Comment by Calinou** [comment]
Closing, as I'll consider this solved by #33414. We may enable that setting by default once it gets more testing.
