### ISSUE TITLE
Godot crashing

### ISSUE THREAD

**Issue by crab69** [godotengine/godot#34149]
**Godot version:**3.1.2

**OS/device including version:**

**Issue description:**When  i play my project Godot crashesh but when i play others people projects it doesnt(Im using GDScript)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Ace-Dragon** [comment]
This is a rather vague report with no file to look at, the devs. need more details on what could be causing the crash if it is to be fixed.

Go through your project and try to identify what your game logic, physics, ect... is doing at the time of the crash.

**Comment by akien-mga** [comment]
Indeed, you don't give us anything to work with. I'll close this, but feel free to open a new issue that properly follows the given template with clear steps to reproduce the issue, and ideally a project so that we can debug it. *Most likely*, if only your project crashes, that would suggest a mistake in your code.
