### ISSUE TITLE
It's impossible to force opening a scene automatically even if dependencies are missing

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#34156]
Godot 3.2 beta2

In an attempt to isolate a bug, I ended up cloning a big scene to open in another clean project, which means its dependencies were missing (textures, scene instances that I however don't care about etc). I was expecting to be able to open it, with all dependencies resolving to null or placeholder nodes. However Godot doesn't let me open it, at all.

I have two options:
- Create dummy scenes and resources, and go through the Dependencies dialog to manually fix them with placeholders
- Copy my entire project and attempt to delete things while the big scene is open.

Both are quite tedious... would it be possible to force open with placeholders/nulls?

**Comment by mhilbrunner** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
