### ISSUE TITLE
LineEdit changes confirmed by focus loss don't handle undoredo properly

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#3416]
Regression from the (otherwise super cool) #3407, so ping @TheHX :)

**Comment by TheHX** [comment]
This problem only occur when editing the Tree built-in LineEdit?

**Comment by akien-mga** [comment]
So far I noticed it when editing values in the inspector.

**Comment by TheHX** [comment]
Looks like this problem is not caused by #3407, for example: if i create a node2d and set position to Vector2(10, 10), and edit again, setting to Vector2(20, 20) the UndoRedo will merge both actions. When i undo one time the position of the node is set to Vector2(10, 10) instead of zero. And the next undo will remove the node.

I hope this is the problem or i just find another bug in the UndoRedo.

**Comment by akien-mga** [comment]
Actually after testing again, it's quite unreliable. It might not be related to #3407 indeed, as I can sometimes reproduce that UndoRedo does not work whether I valid the change with Return or a focus loss. And at other times it works properly :/

Actually if I press undo several times I don't see changes, but after many presses it will remove the Node2D I had added too... Definitely something fishy going on. I'll investigate more tomorrow.

**Comment by reduz** [comment]
I reverted #3407, does this change?

**Comment by reduz** [comment]
i fixed an issue with this, please check again

**Comment by akien-mga** [comment]
It's fixed, or at least not reproduceable anymore since LineEdit confirmation on focus loss was reverted :)
