### ISSUE TITLE
visual studio2015 build error

### ISSUE THREAD

**Issue by WRENCHLIN** [godotengine/godot#34171]
Godot version:
godot-3.1.2-stable
OS/device including version:
Windows7 visual studio2015
Issue description:
LINK : fatal error LNK1101: MSPDB140.DLL version not correct please re-check this product

updated MSPDB140.DLL but still the same error message

**Comment by akien-mga** [comment]
Please be more specific. How are you building Godot? What's the full build log?

**Comment by WRENCHLIN** [comment]
build Godot command:
scons p=windows vsproj=yes target=debug

use scons built Godot  was successful 

scons completed I open godot.sln in Visual Studio 2015 click Build button then get the error

**Comment by akien-mga** [comment]
That's a problem on your system, not related to Godot. Search "LINK : fatal error LNK1101: MSPDB140.DLL version not correct please re-check this product" in a search engine, you'll find lots of issues on other projects and forum posts with users having similar errors, caused by a problem on their system.

**Comment by WRENCHLIN** [comment]
Thanks help

reinstall Visual Studio 2015 problem solved
