### ISSUE TITLE
Select Tile activates permanently with Control

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34170]
**Godot version:**
3.2 beta3

**Steps to reproduce:**
1. Edit a Tilemap
2. Add some tiles
3. Undo the change
4. You have the "Select Tile" tool active, because you pressed Control

IIRC it didn't use to be like that.

**Comment by mathias17** [comment]
There's clearly a bug here concerning the Pick Tile tool - The Pick Tile tool gets selected quite often when I don't intend to pick it. And sometimes both the Paint Tile and Pick Tile tools' icons both indicate they're the currently active tool - [](https://i.imgur.com/1KE2EYI.png)

Big source of frustration for me right now.

I'm using Godot 3.2.stable.official.

**Comment by Calinou** [comment]
> **Suggested Solution:**1. Give Pick Tool a normal single key shortcut such as "i" (Photoshop's default color picker tool shortcut).

Does this mean the Pick Tool should stay enabled once you pick a tile using it? Or should pressing <kbd>I</kbd> just pick a tile immediately, without requiring a mouse click?

**Comment by mathias17** [comment]
Hello, Calinou!
> Does this mean the Pick tool should stay enabled once you pick a tile using it? Or should pressing I just pick a tile immediately, without requiring a mouse click?

Good questions.
I'm still new to Godot, but in my opinion the automatic tool switching with the absence of tool specific cursors is very confusing, until you memorize when Godot decides to switch tools.
(I'd hate to alter a behavior all the experienced users are already accustomed to.)
I think the important thing to do as soon as it's feasible is to stop using the control keys for the Pick Tool's shortcut key. It's causing a very unwanted quirk in the tilemap editor workflow.

👁‍🗨 If I created and submitted cursors (whatever format is needed) for each tilemap editor tool, would it be possible to add them to Godot so users could have a nice contextual cursor to make it clear which tilemap tool is selected at any given time? Especially given all the automatic tool switching going on. Contextual cursors in Godot are uncommon. Let's change that. 

Both the Select Tool and Pick Tool will switch to the Paint Tool after you click once in the viewport. Not sure why the current tool is auto-switched back to the Paint Tool from the Select Tool.
This auto-switching is arbitrary and not dependent on which tool you last had selected - in other words: if you switch from Bucket Fill to Pick Tool, click once to "pick" a tile, Godot automatically switches to the Paint Tool, instead of the Bucket Fill tool which was your previously selected tool (I would expect Godot to go back to the Bucket Fill if that was my previously selected tool).
For now, I don't think this auto-switching behavior should be changed until a more comprehensive change plan can be drafted up. I'd like to help do that, if possible.
Please give me a recommendation as to how I might submit my suggestions. Should I just submit additional issues to this github?

_Interesting idea to have a fast tile pick command that doesn't even change tools!_ I really like this idea and it could make a big difference immediately, without the danger of affecting existing tools/features negatively. Here's how - 
To implement this, rather than change the Pick Tool's behavior, I'd just add this new feature to the tilemap editor as an optional shortcut. Right now, pressing the left or right control key switches to the Pick Tool. I suggest a more logical shortcut key like "i" instead, which is nice and close to "p" already used for the Paint Tool. So, to make your immediate tile pick work, why not just assign the command to the "u" key (which is right there on the keyboard with "i" and "p") as long as the user is hovering their cursor in the tilemap editor viewport?
Call it "Quick Pick". You might add it to the tooltip when you hover the Pick Tool. Just like the Paint Tool's tooltip when you hover the icon in the top bar - it lists the alternate ways you can use the Paint Tool. If Quick Pick was implemented, it would be like an extension of the Pick Tool I suppose. The Pick Tool's tooltip could be updated to read:
`Pick Tile (I)`
`U: Quick Pick`
As for auto tool switching, for the sake of consistency, I think Quick Pick should invoke the same automatic tool switching that the Pick Tool uses, even though personally I'm not a fan of it.
Lastly, it would be very nice if when you used Quick Pick the user got some feedback - briefly change the color of the outline of the hovered tile. It's usually cyan, but turns orange when you hover a blank tile square. So maybe a quick blip of green when Quick Pick is used by pressing "u"?

(Please let me know if there's anything I can do to help with Tilemap Editor updates for Godot. I don't code but I work in interface and icon design. Maybe there's something I can do, instead of just complain haha.)

_yikes, sorry for the length_

**Comment by Calinou** [comment]
> :eye_speech_bubble: If I created and submitted cursors (whatever format is needed) for each tilemap editor tool, would it be possible to add them to Godot so users could have a nice contextual cursor to make it clear which tilemap tool is selected at any given time? Especially given all the automatic tool switching going on. Contextual cursors in Godot are uncommon. Let's change that.

We can consider using one of the built-in cursors provided by the OS, but I'd rather not provide custom cursor graphics if possible.

**Comment by mathias17** [comment]
Ok, makes sense! Thanks for the fast follow-up.

I looked at your pull request. Looks great. Please let me know if there's anything I can do to help.
