### ISSUE TITLE
[GDnative] ptrcall on OS.get_static_memory_usage cause segfault due to godot_int != uint64_t

### ISSUE THREAD

**Issue by touilleMan** [godotengine/godot#34254]
`OS.get_static_memory_usage`&friends are supposed to return `uint64_t`:
https://github.com/godotengine/godot/blob/435cced7d8fbc80e6842d7c171a87d4db1e64fe4/core/os/os.h#L398-L401

However they are defined with a `int` as return value in api.json:
```json
"name": "get_static_memory_usage",
"return_type": "int",
"is_editor": false,
"is_noscript": false,
"is_const": true,
"is_reverse": false,
"is_virtual": false,
"has_varargs": false,
"is_from_script": false,
"arguments": [
]
```

This is bad because the `int` type in api.json should correspond to `godot_int` type defined in godot native headers as `typedef int godot_int`.
This means we end up with memory corruption and segfault when using this function according to the `api.json` definition :'(

I guess the reason why this function is marked as `int` is because it represent the integer type of the Variant (which has uint64_t constructor and cast operator).

I see two solution to solve this:
- mark this function as ptrcall incompatible so use must use Variant call (typically by adding a new field `is_ptrcall_compatible` in the `api.json`). However I'm a bit worried what happened in case `OS.get_static_memory_usage` returns au value bigger than `sizeof(godot_int)`...
- introduce a uint64_t compatible type in api.json type field

It would be interesting to dig a big in the codebase to see how many functions have a similar issues (and if they are performance critical ones). Any idea how we could do that ?

**Comment by touilleMan** [comment]
It seems `Variant` already stores integer numbers on 64 bits:
https://github.com/godotengine/godot/blob/1361fa71c419a44c9a5849a599fa745efe9052cf/core/variant.h#L139

So I guess we could fix this by forcing those methods to return a Variant.

**Comment by neikeq** [comment]
The typedef for `godot_int` should be using `int64_t` instead of `int`.

For a long time, all integral primitives are passed and received from `ptrcall` as `int64_t`: https://github.com/godotengine/godot/blob/0f90ddbcf4489f46132ef48c1611d5c14ff2b776/core/method_ptrcall.h#L105-L112

The commit that introduced this was 30176b0bb1d6083ecf8ce9e6bfca0dce9240a634 and the reason it was done like this is because back in the day, the script system didn't provide information about the integer type size and whether it was signed or not.

However, as of 3380565e4be4e3decbd0981c3f6a2e54f982c2f2, the script system now includes this information, and it's being used when generating the C# bindings. This means if GDNative were to be updated to use this information to differentiate between integral types, then `ptrcall` could be updated to do so too.
But I don't know how much of a breaking change that would be for GDNative. 4.0 may be a good chance though...

**Comment by neikeq** [comment]
About my last comment, see #28645
