### ISSUE TITLE
Mono - Cannot build Android export templates, linker command failed with exit code 1

### ISSUE THREAD

**Issue by nathanwfranke** [godotengine/godot#34326]
**Godot version:**
Master

**OS/device including version:**
OS: Ubuntu 19.10 eoan
Kernel: x86_64 Linux 5.3.0-24-generic
Mono 6.4.0.198
Android SDK Build Tools 29.0.2 (Also reproducible in 27, 28)
Android NDK 17.2.4988734 (Also reproducible in 18, 19, 20)

**Issue description:**
Cannot build export templates for Android from a Linux host, I can build the editor fine
Error:
```
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [bin/libgodot.android.opt.debug.armv7.neon.so] Error 1
scons: building terminated because of errors.
```
Full Log: https://pastebin.com/FTcTbmnW

**Steps to reproduce:**
```
scons -j6 p=x11 tools=yes module_mono_enabled=yes mono_glue=no
bin/godot.x11.tools.64.mono --generate-mono-glue modules/mono/glue mono_prefix=/usr
scons -j6 p=android target=release_debug tools=no module_mono_enabled=yes mono_prefix=/usr
```

**Comment by neikeq** [comment]
You're building Godot for armv7 yet you're trying to link against x86_64 Mono. Even if you were building Godot for Android x86_64 you can't link the Linux Mono runtime as it's not the same for Android.
You need to build Mono for Android as described here: https://github.com/godotengine/godot-mono-builds#android. Then pass the result to SCons: `mono_prefix=$HOME/mono-installs/android-armeabi-v7a-release` (that's the default output path unless specified otherwise).
See: https://docs.godotengine.org/en/latest/development/compiling/compiling_with_mono.html#targeting-android
