### ISSUE TITLE
ColorRect is white in the shader

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#34368]
**Godot version:**
3.2 beta3

**Issue description:**
Fragment shader on ColorRect won't use its color.

**Steps to reproduce:**
1. Add a ColorRect
2. Change its color to e.g. red
3. Add a ShaderMaterial to it
4. Write some minimal shader like
```
shader_type canvas_item;

void fragment() {
	COLOR = texture(TEXTURE, UV);
}
```
5. The rectangle becomes white

**Comment by clayjohn** [comment]
Is this with TextureRect or ColorRect?

ColorRect doesn't have ``TEXTURE`` and TextureRect doesnt have a ``color`` property.

**Comment by KoBeWi** [comment]
ColorRect. Or it isn't supposed to be used this way? I mean, it doesn't have texture, but it has a color, so it can provide some pixel data, can't it?

**Comment by clayjohn** [comment]
There is no texture texture assigned so you are reading from the default ``TEXTURE`` value which is white. See the table of hints in the docs http://docs.godotengine.org/en/latest/tutorials/shading/shading_reference/shading_language.html#uniforms

**Comment by KoBeWi** [comment]
Ok, I went with a uniform. If it requires some hacks to have "texture" in ColorRect then it's probably not worth it.

**Comment by Arecher** [comment]
I ran into this limitation as well, and while I completely understand that `Control` nodes without a texture cannot be expected to return their color via `TEXTURE` in shaders, that leaves the question: **How are you meant to get the displayed color of a Control node?**

Since you are allowed to put Shaders on to Control nodes, which can be very useful, how are you meant to write a shader that can handle both textured Control nodes and untextured ones such as `PanelContainers` with a `StyleBoxFlat`. It's extremely confusing that there is no alternative way to get the color that is displayed.

Obviously it would be possible to use a `uniform` and pass the value, whether that's a single color (for extremely simple controls) or a Viewport capture image. But that seems extremely convoluted and feels like it shouldn't be necessary, since for any textured Control node a built-in function exist with `texture(TEXTURE, UV)`.

The only option I have found is to use:
```
float alphavalue = 0.5; // A hardcoded alpha value, or any calculation such as a lerp
COLOR.a = alphavalue;
```

This way the shader does not overwrite the `.rgb` values of the `COLOR` and the original color is preserved. But this clearly doesn't work for all shading cases. 

Either way this limitation makes shading Control nodes in Godot feel extremely inconsistent and cumbersome. I can write a proposal for the addition of a method to get the equivalent of `texture(TEXTURE, UV)`, but I thought I would ask around first, because there MUST be a way to get these color values that I've completely overlooked.
