### ISSUE TITLE
[Emscripten/Javascript] build compile error

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#3438]
Using Visual Studio's 2013 Developer Command Prompt, I was trying to compile a HTML5 platform build to experiment the new features of the web export, but not so much as getting this error when trying to complie:
___________
scons: *** Multiple ways to build the same target were specified for: main.javascript.opt.debug.bc  (from ['main.cpp'] and from ['input_default.javascript.opt.debug.bc', 'main.javascript.opt.debug.bc', 'performance.javascript.opt.debug.bc'])
___________

I was told on the Godot forums that it may be related to the Windows Case-Sensitivity, but what do I know. Hopefully this can get resolved so then I can try to export game projects to HTML5 format.

**Comment by reduz** [comment]
To be honest, never tried to build html5 backend on windows

**Comment by punto-** [comment]
what scons command are you running? and why is there no dots in the error?
how hard is it to get the emscripten sdk for windows?

**Comment by vnen** [comment]
@punto- about the dots, it's a GitHub bug that somehow omits the dots in every email from a just opened issue. In the page you can see the dots.

Also, Emscripten for Windows needs Visual Studio 2010 to build. Don't know what it needs when it have the toolchain ready. Also, I think it doesn't need a Developer Command Prompt, a regular prompt should do it. I'll try to test this tomorrow.

**Comment by Corruptinator** [comment]
Alright, so basically I was attempting to get the HTML5 compile to work on windows after managing to get the Developer Command Prompt for Visual Studio 2013 to work, what I did first was install the necessary downloads for Emscripten to work with Scons such as Node.js, Python, Java, and so forth. Next i was able to set the environment variable using the "setx" command used in Windows 7. (For Example: [setx EMSCRIPTEN_ROOT "Insert path to Emscripten SDK"]). Afterwards, I thought it could work but instead I got that error now.

Also the command I was using to try to compile HTML5 was: "scons -j 4 p=windows target=release tools=no bits=32", based on what this page told me:http://godotengine.org/projects/godot-engine/wiki/Batch_building_templates.

The Windows compile works, probably the same with WinRT as well, but javascript is where I am stuck on now...

**Comment by vnen** [comment]
There's a installer package for Emscripten to Windows, which makes it a little easier. The package install all dependencies, so no need to install them before.

It also installs a "Emscripten Command Prompt", which I guess is the best to compile Godot, but it might make not much difference from a regular prompt except from some small config in the environment. The "Developer Command Prompt" from Visual Studio **will not work**, and gives the error mentioned in the OP.

However, I get an error that the config file `~/.emscritpen` is not found, because this is not a standard path in Windows (should be `%USERPROFILE%\.emscripten`).

If I pass the `--em-config` flag to `emcc` in order to set the correct path to the config file, I get yet another error saying it can't detect the number of cores. This comes from a Python script inside Emscripten. It supposedly reads the value from the  `EMCC_CORES` environment or from `multiprocessing` Python lib, but none of those work, even if the environment variable is set.

As a workaround, I edited Emscripten Python files under the installed SDK folder:

* `tools/shared.py` to change the default `EM_CONFIG` to the correct path in my system. Otherwise the `--em-config` had to be passed to every command.
* `tools/system_libs.py` to hardcode a number of processor cores.

Then I bumped into the "command line too long" problem. Not sure how to work around this.

**Comment by Corruptinator** [comment]
Alright so I am getting closer to trying to get Javascript to work on windows, I added mingw to the PATH variable so then the windows command can use GCC to compile, emscripten almost works but now I have a new problem, I get this error:
_____________________________________
Traceback (most recent call last):
  File "C:[emscripten_path]\emcc", line 28, in <module>
    from tools import shared, jsrun, system_libs
  File "C:[emscripten_Path]\system_libs.py", line 17, in <module>
scons: *** [platform\javascript\javascript_main.javascript.opt.bc] Error 1
    CORES = int(os.environ.get('EMCC_CORES') or multiprocessing.cpu_count())
  File "C:\Python27\lib\multiprocessing\__init__.py", line 136, in cpu_count
    raise NotImplementedError('cannot determine number of cpus')
NotImplementedError: cannot determine number of cpus
scons: *** [platform\javascript\audio_server_javascript.javascript.opt.bc] Error 1
_____________________________________
You mentioned about the cpu core issue within python and that you ended up on the command line too long, this is the same on what I was going through. Sigh, I wish there was an another way to fix this...

**Comment by reduz** [comment]
just realized, don't use the visual studio command prompt for this

**Comment by reduz** [comment]
visual studio command prompt is for building with msvc, if you are building something else, use regular command prompt or mingw command prompt

**Comment by vnen** [comment]
@reduz I pointed this out in my previous comment, however it doesn't work even in a regular prompt or Mingw. I tried to enable the spawn fix for Javascript but then got a cryptic error (`%1 is not a valid Win32 application`) which I don't know how to fix.

**Comment by Corruptinator** [comment]
Well then, I guess I'll take your word for it. I'll see if the mingw command prompt works. Thanks for the feedback.

**Comment by beocat** [comment]
Have any of you had any progress on this? I can replicate the "command line too long", but don't quite understand how you handled that and ended up with the "%1 is not a valid Win32 application" error.

**Comment by vnen** [comment]
This is fixed, but I need to update the docs to add this info that you can't use the Developer Prompt.

**Comment by Corruptinator** [comment]
Sounds good to me.
