### ISSUE TITLE
The InputEventKey will stop after press another key.

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#34414]
**Godot version:3.1

**OS/device including version:**

**Issue description:**

**Steps to reproduce:**

**Minimal reproduction project:**

func _input(event: InputEvent) -> void:	
	if event is InputEventKey:
		if event.pressed:
			print("key pressed", event.scancode)

When press  key A and keep it down, it will  report continually, however, after pressed key B simultaneously and then release key B, the key event for Key A will not report any more.

**Comment by eon-s** [comment]
This could be a OS limitation on the key echo, if you press A on a text editor, then B, you see `AAAAAAABABABAB` or `AAAABBBBBB`?

In general, avoid the use of the key echo events and use press with echo control and release instead, because it will be more consistent across different OS configurations.
