### ISSUE TITLE
Increase number of concurrent touches for iOS above 8

### ISSUE THREAD

**Issue by marcosoldati** [godotengine/godot#34424]
**Godot version:** 
3.1

**OS/device including version:** 
MacOS 

**Issue description:** 
https://github.com/godotengine/godot/blob/master/platform/iphone/gl_view.mm line 207 limits the number of concurrent touches to 8. Looks like this dates from older iPhones. Latest iPads  support up to 18 concurrent touches. 
Raising the value to 18 should fix it for all iOS devices. 

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@bruvzg Do you have access to a device that supports more than 8 concurrent touches? This should be an easy change, it just needs someone to test it :slightly_smiling_face:

**Comment by bruvzg** [comment]
> Do you have access to a device that supports more than 8

No

**Comment by webair** [comment]
We are currently developing a game which need to recognize more than 8 touches on ios. If we test the app in the web export this restriction to 8 touches is not there when testing with our ipad. is this restriction nowday still relevant or could this restriction be removed because the ios platform will only allow its own max touches?

**Comment by akien-mga** [comment]
Seems like it has been `max_touches = 8` since Godot was open sourced.
```
static const int max_touches = 8;

@interface GodotView () {
	UITouch *godot_touches[max_touches];
}
```

There's no indication that it would be a technical limitation on iOS (though I haven't check the documentation to see if there are such restrictions), I think this was just added because the touches are stored in an array and thus it needs a size, and 8 might have seemed like a high enough max for the array.

It could likely be bumped to 16 or 32, or made a `LocalVector<UITouch *>`.

**Comment by akien-mga** [comment]
>  Latest iPads support up to 18 concurrent touches.
Raising the value to 18 should fix it for all iOS devices.

@marcosoldati Do you have a source for this value? It would be good to know where it's defined and for which versions of iOS. From a quick look through Apple docs I didn't find a mention of a max concurrency.

**Comment by webair** [comment]
I also tried to find something specific from apple. i only could find entries in forums where there is mentioned that for example the iPad Pro can support up to 18 touches.

**Comment by Krigu** [comment]
> @bruvzg Do you have access to a device that supports more than 8 concurrent touches? This should be an easy change, it just needs someone to test it slightly_smiling_face

I would be able to test it on an iPad (6th generation).

**Comment by bruvzg** [comment]
10th gen. iPad is registering at least 17 touches (I have changed `max_touches` to `32`, but it's hard to actually touch it in that many points at once).

**Comment by marcosoldati** [comment]
> @marcosoldati Do you have a source for this value? It would be good to know where it's defined and for which versions of iOS. From a quick look through Apple docs I didn't find a mention of a max concurrency.

I am afraid I do not have a source. If I remember well, I found the number by try and error on a 12.9-inch iPad. So it might not be correct.

**Comment by webair** [comment]
Would it make sense to change the implementation using an NSMutableArray instead of a pointer array, so the max size is not an issue anymore? Or was this already considered? i've got experience with ios development so i could give it a try
