### ISSUE TITLE
Navigation2D snaps path endpoints to outer borders when on triangulation seams

### ISSUE THREAD

**Issue by vpellen** [godotengine/godot#34449]
**Godot versions:**
3.1.1 stable, 3.2 beta 3 & 4, presumably others

**Issue description:**
This is probably going to be easier if I start by describing how the bug manifests.

When you use Navigation2D::get_simple_path, you specify two endpoints: a start and a goal. The first thing the function does is it tries to figure out which polygon to start in. It does this by going over every triangle in the associated navmesh and running Geometry::is_point_in_triangle for each of the two endpoints. It does this for every triangle until it finds which triangles the endpoints are contained within.

The issue is that Geometry::is_point_in_triangle returns false for points that are on the border of the triangle - That is, points that are coincident with the vertices or edges of the triangle. Consider the case of a triangulated square. Any point that lies on the diagonal seam between the two halves of the triangulated square will return false in tests with both triangles. And, indeed, this is what happens within the pathfinder - If one of the path's endpoints is, for example, directly in the middle of a triangulated square, the endpoint's triangle will never be found.

When this happens, the pathfinder assumes that the endpoint is outside the navmesh, and it goes over every edge on the navpoly, snapping the endpoint to the nearest one. This results in path endpoints snapping to external borders.

**Steps to reproduce:**
The easiest way to recreate this bug is to create a perfectly square NavigationPolygonInstance and try to get_simple_path to or from its exact center.

**Final thoughts:**
This bug can sometimes be worked around, but even in a best case scenario it's a performance degradation that you're likely to run into if you do pathfinding on any kind of real scale. This is actually a bug I may be able to fix myself, but my experience with github is extremely limited, and I'm not sure on the ideal way to proceed.

The simplest fix to this would likely be to rewrite Geometry::is_point_in_triangle to return true for points on the triangle's border, which may or may not be desirable. A less graceful but more contained method would be to use a custom triangle test within the pathfinder itself. Alternatively, a second triangle test function could be added, or the first could be modified with a boolean to test the borders.

Any advice would be appreciated.

**Comment by lawnjelly** [comment]
Just having a quick look, I'd question whether the is_point_in_triangle needs to do anything with orientation as you should be able to pre-orientate all your navmesh tris clockwise (or CCW).

You could also do an is point in triangle test by calculating the distance of the point in relation to each of the 3 edges. If it is behind all 3, it is within the triangle. If you use this you can also keep a running total of the best match, so that in the event of it not being 'inside' any particular triangle, you can choose the 'closest' without any further testing. Of course this is just approximate because you are getting the distance from the edges, which may be different to that from a corner.

You can also use barycentric coordinates as another alternative, but this might make it more difficult to have a world space 'best fit'.

Also such a routine should usually allow the caller to optionally specify the navmesh triangle to start from (and perhaps also optionally the navmesh tri to end on). A moving object can keep track of its current triangle and make these checks much cheaper. At least this is how I've done it with my own navmeshes, I have no experience with Godot navmeshes so these are just some ideas.

**Comment by KoBeWi** [comment]
Can anyone still reproduce this bug in Godot 3.2.3 or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by alexontheweb** [comment]
I can confirm the issue.

**Godot version:** Godot Engine v3.2.3.stable.official
**OS/device including version:** Windows 7 x64

**Steps to reproduce:**
1. Create Scene with the following structure:
-- Navigation2D
--- TileMap
2. Create a single square tile with square navigation region covering full tile
3. Place a few connected tiles inside the scene
4. Try to build a path with get_simple_path() between centers of tiles
5. As a result: start and end navpoints snap to edges of tiles instead of center.

![tilemap_bug](https://user-images.githubusercontent.com/6839374/101830713-9abc2f00-3b3d-11eb-8775-bf21941185e4.PNG)


**Minimal reproduction project:** [nav2d_issue.zip](https://github.com/godotengine/godot/files/5675621/nav2d_issue.zip)

**Comment by smix8** [comment]
This issue does no longer happen in Godot 3.5 and 4.0 as the old navigation logic was removed and 2D navigation now uses the same meshbased NavigationServer logic as 3D.

@KoBeWi 
Can be closed.
