### ISSUE TITLE
Strange OmniLight behaviour in GLES 3

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#34468]
**Godot version:**
3.2 beta 4
**OS/device including version:**
Ubuntu 19.10
**Issue description:**
When I change camera rotation, then light area are changing strange
This doesn't happens with GLES 2
![jfile](https://user-images.githubusercontent.com/41945903/71197357-b3c73280-2291-11ea-9db3-89c14e7a3f38.gif)

**Minimal reproduction project:**

[OmniLightIssue.zip](https://github.com/godotengine/godot/files/3984946/OmniLightIssue.zip)

**Comment by MadEqua** [comment]
This is a side effect of the contact shadow. It starts happening when the light goes out of screen, since it's a screen space technique.

It can be fixed by not marching the ray outside of the screen and return immediately as "no shadow". I think this is correct and it will not break other cases.

I will make a PR.
