### ISSUE TITLE
Graphical artifacts in Godot 3.2 beta 4

### ISSUE THREAD

**Issue by warriormaster12** [godotengine/godot#34483]
There seems to be a graphical issue in Godot 3.2 that isn't present in Godot 3.1.2. 
[Godot 3.2](https://drive.google.com/open?id=1tPJrudMnse-HQAWoOv6-QiimOyro7za9)
[Godot 3.1.2](https://drive.google.com/open?id=1SAYmH08TnDoaIAAwWGdYtKB2q-FLJnGJ)

Mesh: 
  -  Is imported using Collada format
  -  Two-sided so you can see it from any angle.
  -  custom collision included.

  [More images showing the issue](https://drive.google.com/file/d/13hkttV44rTIhOLBuwcjw9WtzqHOqJtY9/view?usp=sharing)
[Even more](https://drive.google.com/open?id=1pW997B5KtViLdXeNmW3KNFkKf1HjUdVA)

**Comment by volzhs** [comment]
you can attach images by just drag and drop in comment field.

**Comment by akien-mga** [comment]
Can you provide a test project that exhibits the issue, and details on your system?

**Comment by warriormaster12** [comment]
KDE Neon(Based on Ubuntu 18.04, kernel 5.3.18)
I5-4570 Cpu 
Gtx 1060 6gb gpu 
16 gb of ram 

Here's a test project that includes one of the assets shown in screenshots.
[Godot3.2_Test.zip](https://github.com/godotengine/godot/files/3988262/Godot3.2_Test.zip)

**Comment by lawnjelly** [comment]
![Screenshot_20191220_105932](https://user-images.githubusercontent.com/21999379/71264814-c8acd000-233c-11ea-9e47-1f4dc8e7dc2c.png)
![Screenshot from 2019-12-20 15-23-52](https://user-images.githubusercontent.com/21999379/71264828-d4989200-233c-11ea-98f5-2ea2277a4578.png)

For benefit of others I pasted one of your original images here. The second image is mine captured from blender. I loaded the DAE into blender, and there is z fighting because the object contains what seems to be a duplicate mesh underneath the first. I deleted a quad to show this, there is a white mesh underneath.

**Comment by warriormaster12** [comment]
The thing is that for personal reasons I would not like to share my project yet but it is odd that you don't experience it in 3.2 beta 4 and I do. 

In the project that I sent the issue persisted so I though that it should be enough for you to analyze, and at the time when I sent those screenshots above, my project consisted of only imported .dae assets and nothing else.

**Comment by Calinou** [comment]
@warriormaster12 Are you running the project on the Intel IGP or the dedicated NVIDIA graphics card?

Unlike AMD and NVIDIA, Intel graphics drivers default to 16-bit depth buffer unless the application explicitly requests a 24-bit depth buffer.

**Comment by clayjohn** [comment]
@Calinou on desktop we explicitly request 24/32 bit depth buffers. So when available, the driver should always supply the highest bit depth.

**Comment by warriormaster12** [comment]
@Calinou Nvidia graphics card. I want to repeat that in any project that I have imported assets to, issue persists. With 3.1.2 everything works as should.

**Comment by veryprofessionaldodo** [comment]
This really looks like Z fighting, or perhaps a problem with the normals... Have you tried uploading a normal cube exported from Blender?

**Comment by warriormaster12** [comment]
No not yet, I can try though.

**Comment by veryprofessionaldodo** [comment]
Please do, I think that's the source of the issue. Could be wrong tho

-------- Mensagem Original --------
Ligado 3/01/2020, 13:53, Alexander Streng escreveu:

**Comment by warriormaster12** [comment]
Nope, I still have the issue and it doesn't matter if I have collision or not.

![image](https://user-images.githubusercontent.com/33091666/71732865-f0c62400-2e50-11ea-9379-0453c6d373bb.png)
![image](https://user-images.githubusercontent.com/33091666/71732882-f9b6f580-2e50-11ea-80c3-cc6dca63a66a.png)

Godot 3.1.2
![image](https://user-images.githubusercontent.com/33091666/71732953-1b17e180-2e51-11ea-8738-bbe0845accee.png)

**Comment by Zireael07** [comment]
I fail to see the difference between 3.1.2 and 3.2 - the cubes look the same to me.

**Comment by warriormaster12** [comment]
3.1.2 doesn't have artifacts in the bottom face and it looks a bit darker.

**Comment by Zireael07** [comment]
Oh, zooming in I can see the artifacts now that you mentioned them.
Are the cubes two-sided? Does the issue occur if they are one-sided?

**Comment by warriormaster12** [comment]
It's the default blender cube so no it shouldn't be two-sided

**Comment by warriormaster12** [comment]
A little update. Tried default meshes in the meshinstance node aaaand... Basically same story.

**Comment by warriormaster12** [comment]
Tested with Godot 3.2 beta 5 and the issue is still there.

**Comment by Zireael07** [comment]
"Textured" in what sense? Do you import materials from Blender? Set up material in Godot?

**Comment by warriormaster12** [comment]
For custom assets I do import materials from Blender if their color is set to something other than default white. Once I have settled with how the object looks in the environment, I go back to Blender and texture it and then import updated object with textures back in to Godot and that seems to "fix" the artifacting issue.

Without textures 
![Screenshot_20200104_161825](https://user-images.githubusercontent.com/33091666/71766894-df8f1d00-2f0d-11ea-993c-f69081aab22f.png)

And with textures 
![Screenshot_20200104_161945](https://user-images.githubusercontent.com/33091666/71766913-08171700-2f0e-11ea-8bf0-25e897de7723.png)

**Comment by lawnjelly** [comment]
Unfortunately very difficult to pin down without the system it occurs on, I'm mostly stumped.

Some other possibilities aside from z buffer:
* the shader reading garbage somewhere, and maybe on most systems it just defaults to a zero or 1.
* it could be something precision sensitive in the maths for one of the shaders (e.g. divide by zero).

I would try converting both the spatial material that has the problem, and one that does not, to a shader, then try to manually bisect between the two, in order to figure out when the problem starts occurring. You could also try disabling the z prepass just to rule that out.

**Comment by warriormaster12** [comment]
I don't think that it's a material issue since choosing a default mesh from mesh instance has the same issue. How to disable z prepass and is there a way to debug Godot inside of terminal?

**Comment by Zireael07** [comment]
Exactly because default mesh and your mesh have the issue, it looks like a material issue.
Z prepass is somewhere in material's settings, btw.

**Comment by warriormaster12** [comment]
Oh okay, don't know all of the terms related to game engine development so thanks for correcting me 😁

**Comment by warriormaster12** [comment]
Are you going to leave this issue unsolved?

**Comment by clayjohn** [comment]
It needs to be reproduced in order to be solved. No one can reproduce therefore no one can solve it right now. 

I removed the 3.2 milestone as it is clear that this will not be solved in the coming weeks and I don't think this issue should block the 3.2 release as no one else is experiencing this issue.

**Comment by warriormaster12** [comment]
I understand.

**Comment by sunkper** [comment]
I've also encountered this issue. My GPU is GTX 1050Ti.

![ars](https://user-images.githubusercontent.com/4294611/72208908-ffb17400-34eb-11ea-88f9-15e81654c61b.png)

Some observations:
- It happens since 3.2 beta 2 build. It does not happen with beta 1.
- It only happens with GLES3.
- I thought it only happens to the face that is perpendicular (and almost perpendicular) to Y-axis. But looks like it's to do with shade. When I rotated the sky, it appears on the side, the new bottom.

![sky_rotated](https://user-images.githubusercontent.com/4294611/72208999-23c18500-34ed-11ea-8603-76dd1a13b708.png)

- It seems to disappear when:
-- Well, unshaded.
-- Enabled normal map, even without normal map texture.
-- Enabled metallic, proportional to the metallic value.
-- When the face was totally lit by other light sources.

I guess this is something to do with lighting and shadow but I'm clueless about graphics programming so...

**Comment by clayjohn** [comment]
@sunkper thanks for confirming. Based on your info it looks like this may be an issue with the irradiance map code that was added in beta 2 https://github.com/godotengine/godot/commit/cd40154890ba9791b219d66beaf187a7d8dcdba5

**Comment by clayjohn** [comment]
@warriormaster12 Thanks for your patience, I have submitted a PR to fix this issue. If you are comfortable building from master please do so and confirm that the PR fixes the issue for you. :)

**Comment by warriormaster12** [comment]
@clayjohn  will do 👌

**Comment by warriormaster12** [comment]
Cloned master branch, compiled it and yup, no artifacts anymore. Thanks a lot for fixing the issue. I hope only best for you and your project :D
