### ISSUE TITLE
Animation editor NodePath:Assign

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#3448]
invalid path
1 add call function track
2 pass 1 parameter (type:NodePath)
3 tie any node

the path is incorrect. first will be a lot Moussoro.

I would like to convey is not the way to the backing necessary and himself Offer.

**Comment by bojidar-bg** [comment]
@ret80 ~ Seems like automated translation didn't work for you. Can you add the source text (in your native language), so we can understand it more easily?

**Comment by ret80** [comment]
en:
1 Create an animation.
2 adds "add call function track"
3 Specify any Node and any func.
4 Set parameter 1 to the transfer. Parameter Type NodePath
5 Make Assign
When playing this animation in callBack comes to setting the path to the linked Node. So this way is not true.

ru:
1 Создаем анимацию.
2 Добавляем "add call function track"
3 Указываем любую Node и любую func.
4 Устанавливаем 1 параметр на передачу. Тип параметра NodePath
5 Делаем Assign
При проигрывании этой анимации в callBack приходит параметр с путем к привязанной Node. Так вот этот путь не верный.

**Comment by bojidar-bg** [comment]
Ok, I can confirm this. The problem is that the NodePath is assigned an editor-only path (`/root/EditorNode/@@7/@@11/@@13/@@17/@@21/@@22/@@23/@@39/@@40/@@42/@@47/@@8386/@@8297/@@8298/@@8299/@@8300/@@8301/TestCube/world/Area2D2/CollisionShape2D`), and not a path relative to the AnimationPlayer's root or function track's object.

**Comment by bojidar-bg** [comment]
Seems like the problem is at https://github.com/godotengine/godot/blob/master/tools/editor/animation_editor.cpp#L3641

**Comment by reduz** [comment]
My family comes from Ukraine (you probably guessed already by my last name)
, but unfortunately I don't understand russian :(

**Comment by akien-mga** [comment]
> but unfortunately I don't understand russian :(

That's why we'll let @bojidar-bg handle this one :D

**Comment by bojidar-bg** [comment]
@reduz ~ The problem is that the path assigned by AnimationEditor Function Track Argument Properties (NodePath argument) is editor-only, and not relative to Function Track's node. (so it is something of the sort `/root/EditorNode/@@7/@@11/@@13/@@17/@@21/@@22/@@23/@@39/@@40/@@42/@@47/@@8386/@@8297/@@8298/@@8299/@@8300/@@8301/world/Area2D/CollisionShape2D`)

To reproduce (my nomenclature might be wrong):
1. Create a new Function Track
2. Add a Function Call
3. Chose some random function (preferably one that prints its first argument)
4. Increase number of arguments to 1
5. Set argument type to `NodePath`
6. Assign any node from the scene
7. Play and see that some global, editor-related path is printed...

BTW, I know just a very little bit of Russan, but I know Bulgarian, and that's enough for me to understand it :wink:

P.S. I can provide a video of it :smile:

**Comment by reduz** [comment]
OK I think I understand the problem, this is indeed quite an obscure use case.. trying to fix it anyway

**Comment by ret80** [comment]
Теперь не работает: Сlear

**Comment by ret80** [comment]
Так как калбек срабатывает в скритпе который работает на анимационной ноде то путь должен быть построен от анимационной ноды а не от ее родителя.

**Comment by freemanfromgodotengine** [comment]
My Russian is soooo rusty and he makes typos  :( but I think he wants to say something like:

> Now it does not work: Clear
> As callback works in the script that works on an animation node, the same path should be created from an animation node and not from it's parent.

**Comment by ret80** [comment]
1 earned "assign" but stopped working "clean"
2 path must be "../n1/n2" instead of "/n1/n2"

**Comment by reduz** [comment]
the path will always be from the node the animation track refersto to, just
as if you were editing that node directly
fixing clean, give me a second
