### ISSUE TITLE
Physics2DDirectSpaceState.get_rest_info() returns incorrect collision results.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#34564]
**Godot version:**
569e9c1d5

**OS/device including version:**
Win10 64-bit

**Issue description:**

The normal and collision points returned by get_rest_info() physics query in 2D are often wrong.  Test motions show the correct results, the problem here is there is no work around for when you want to do these queries against Area2Ds.

![godot windows tools 64_2019-12-23_16-03-03](https://user-images.githubusercontent.com/13004169/71362284-4e7b8600-259e-11ea-94c5-ae8089f9e507.png)

The expected result is in green, the result given by get_rest_info() in red.

**Steps to reproduce:**

Query motions with Physics2DDirectSpaceState.get_rest_info().

**Minimal reproduction project:**
[Rest Query.zip](https://github.com/godotengine/godot/files/3995213/Rest.Query.zip)

**Comment by avencherus** [comment]
Not familiar with SAT algorithm, but traced through the circle collision test and it appears at least to be choosing the wrong best axis around this line:  https://github.com/godotengine/godot/blob/d711c57d767734887fbf0955a7b9902c54498a0d/servers/physics_2d/collision_solver_2d_sat.cpp#L296

Doubt this is the cause though, probably occurs between this point and what is passed into the collision solver: https://github.com/godotengine/godot/blob/d711c57d767734887fbf0955a7b9902c54498a0d/servers/physics_2d/space_2d_sw.cpp#L438

**Comment by avencherus** [comment]
@madmiraal Maybe you might be interested in this one.

**Comment by madmiraal** [comment]
The SAT algorithm simply checks whether or not there is a collision by checking whether or not there is a space between two objects. It does this efficiently by only checking along specific directions or "axes". In objects created from lines, the axes are the edges of the object. In the case of two circles it uses the perpendicular of the line between the centres.

To check whether a specific motion will cause a collision, it stretches the moving object in the direction of motion. In your example, of two circles, it will effectively convert the moving circle into a capsule stretching from the "current" to the "future" positions. It then checks two additional axes: in the direction of motion (will it collide?) and its perpendicular (will it reach?).

The SAT algorithm is not used to calculate the normal. Instead, if there is a collision i.e. no gaps, it simply uses the perpendicular of the axis which resulted in the minimum overlap.

You see two different normals, because the `move_and_collide()` function also determines the maximum distance it can move without colliding and the minimum distance it can move and still collide, by doing a binary search; calling the SAT algorithm each time. it uses the minimum distance it can move and still collide to just overlap the two objects, and the normal is calculated using the perpendicular to this tiny overlap.

The `get_rest_info()` function does not do the binary search. In your example, the "final" position does not result in a collision, so the normal is calculated from the minimum overlap of the stretched (capsule) object only, and the minimum overlap is in the direction perpendicular to the motion. Since the overlap at the top and bottom are equal, it just happens to use the bottom.

If you reduce the test motion to 120, the "final" position is a collision, and both normals will be the same.

**Comment by avencherus** [comment]
Many thanks for the detailed explanation.  I see now, I mixed this method up and also forgot it has this line in the docs the same as intersect_shape():  

> Note: This method does not take into account the motion property of the object. The returned object is a dictionary containing the following fields

Closing this, as it is working as described.  Been trying it as a work around since the PhysicsServer2D.body_test_motion() doesn't have an option to test against Area2Ds.
