### ISSUE TITLE
CPUParticles freeze when emitting is turned off

### ISSUE THREAD

**Issue by Alzy** [godotengine/godot#34577]
**Godot version:**
3.1.2 GLES3

**OS/device including version:**
Windows 10

**Issue description:**
I'm using CPUParticles in a 3D scene in my rhythm game. When a note is pressed I have the gdscript for the note set the CPUParticle's emitting property to true. On release, I set emitting to false. The expected behavior is that the particles still on the screen continue their movement until their lifespan runs out and they disappear. Instead, some particles simply freeze until the note is pressed again.

**Comment by rafaelgdp** [comment]
Have you unchecked the one-shot property? It is also worth noting that high explosiveness and number of particles may also play a role in existing blank periods between lifespans. Check other properties like velocity, acceleration etc. Maybe some misconfiguration? We need more info on these parameters to make sure it is really a bug in Godot or in your properties' values.

**Comment by Alzy** [comment]
@rafaelgdp I had explosiveness at 0.25. Lowering it to zero seemed to remove the problem so it seems to have to do with the way explosiveness is handled.

**Comment by rafaelgdp** [comment]
@Alzy , yes. Setting explosiveness to zero makes your particles to be emitted uniformly over the whole lifespan (with no perceptible gaps). The question is, has your problem been solved by tweaking the explosiveness? If the answer is yes, this issue should be closed. Otherwise, it would be nice for you to make a quick screen cast video or gif demonstration of the issue.
