### ISSUE TITLE
[Bullet] Jittering against two discrete, connected walls

### ISSUE THREAD

**Issue by DenisBelmondo** [godotengine/godot#34596]
**Godot version:**
3.2 dev

**OS/device including version:**
Windows 10 64-bit

**Issue description:**
In Godot 3.2, the physics seems to have changed in some way (at least for KinematicBody) that makes sliding along surfaces a lot more bumpy. This is similar to [#32182](https://github.com/godotengine/godot/issues/32182), but this time it's different between versions and it doesn't just occur in corners or exclusively against trimesh shapes (all of the walls are convex in this example).

Behavior in v3.1.2 (desired):

![312](https://user-images.githubusercontent.com/8296741/71427196-e21e8680-2672-11ea-8cab-440c07576768.gif)

Behavior in v3.2:

![32](https://user-images.githubusercontent.com/8296741/71427202-f2366600-2672-11ea-9f71-04245331e619.gif)

**Steps to reproduce:**

Open the minimal reproduction project and run it. You will find that you start the scene staring at the wall. Turn to the right, jump over the step and slide against the wall.

![image](https://user-images.githubusercontent.com/8296741/71427232-7b4d9d00-2673-11ea-93da-b7f8fc1a10bd.png)

**Minimal reproduction project:**

Note: apologies, but this reproduction project currently contains a prepackaged Qodot. This is because I don't believe I'll be able to set up this type of environment with hand-rolled geometry. I could position three skinny StaticBody's against one another but I don't think that would be a proper environment, I would rather have it tested in something more complex like this.

[movement.zip](https://github.com/godotengine/godot/files/3999267/movement.zip)

**Additional notes:**

I tried playing with the safe margins on both KinematicBody and its CollisionShape but it seemed to have little to no effect at all. Furthermore, the effects are much more exaggerated when using BoxShape instead of a cylinder or capsule. However, all of them seem to exhibit some kind of sudden "snapping" behavior from moving between adjacent _floors_, not walls. I assume this is related to this exact bug.

**Comment by DenisBelmondo** [comment]
Update:

I've created a minimal reproduction project that uses a GridMap. The walls and floors are all made of 1x1x1 cubes. As the entire world geometry is essentially made of discrete shapes, it is much more easy to demonstrate this bug here, as well as highlighting that it occurs on floors as well.

**Here is what it looks like using plain move_and_slide():**

![move_and_slide](https://user-images.githubusercontent.com/8296741/71633396-2fe64200-2bd1-11ea-8b47-0669c97122c5.gif)

The jittering is very extreme when standing on four tiles simultaneously, and less extreme when standing on two tiles.

**move_and_slide_with_snap():**

![move_and_slide_with_snap](https://user-images.githubusercontent.com/8296741/71633422-6a4fdf00-2bd1-11ea-876a-fec81e3c333e.gif)

It's hard to see in the gif, but while there is no extreme jittering while standing in place, the player seems to treat each "line" between tiles as a small crack in the making traversing along it very bumpy.

I've tried removing the floor check when applying downward velocity (gravity) and the bug still occurs.

**Download this reproduction project:**

[movement_gridmap.zip](https://github.com/godotengine/godot/files/4013437/movement_gridmap.zip)

**Comment by akien-mga** [comment]
CC @madmiraal

**Comment by madmiraal** [comment]
This problem occurs when a KinematicBody using `move_and_collide()` continuously collides against more than one surface. The continuous collisions are generated by a form of gravity or when the player is pushing against a wall.

This problem does not occur in 3.0.6.
This problem occurs in Godot Physics since 3.1-stable.
This problem occurs in both Godot Physics and Bullet Physics since 3.2 alpha 1.
This problem first started in Bullet Physics with 6dd65c0d6 a.ka. #27415, which fixed Bullet Physics to allow for multiple collisions.

My minimal projects:
v3.0:
[Multiple Collisions 3.0.zip](https://github.com/godotengine/godot/files/4076949/Multiple.Collisions.3.0.zip)
v3.1:
[Multiple Collisions 3.1.zip](https://github.com/godotengine/godot/files/4076950/Multiple.Collisions.3.1.zip)

This looks like a duplicate of #29392, #32182 and/or #34663. However, the problem is more general than described there.

Note: This problem also occurs with `move_and_slide()` and `move_and_slide_with_snap()` because they both call `move_and_collide()`.

**Comment by Calinou** [comment]
cc @aqnuep

**Comment by DenisBelmondo** [comment]
I should also note that after testing just now in the second reproduction project (red gridmap), it seems the bumpy floor collisions also happen when the player does not have any Y velocity. I tested this by commenting out the `	if !on_floor: if vel.y > -max_fall_acceleration: vel.y -= fall_acceleration` lines and placing the player node in the scene squarely on the floor. Bizarre.

**Comment by reduz** [comment]
I tested both samples using both Bullet and GodotPhysics. They work perfect with GodotPhysics.

**Comment by reduz** [comment]
There was a bug in GodotPhysics that made it break in some scenes which was introduced recently, should be fixed by 
#40377.

I suggest using the same logic in the Bullet physics server to ensure it works there too.

**Comment by aqnuep** [comment]
FWIW, I did not encounter such jittering with either convex shapes or trimeshes though I did not test such a scene entirely built from convex shapes.

The type of jittering does seem to be the result of one of the many margin values used throughout Godot and the individual physics servers. I recall making changes on that front too, but that was specific to ray shapes.

Please note though that the pre-3.2 Bullet kinematic body implementation was quite broken and it may just have worked by chance due to often doing literally 1000x more collision checks than necessary (dropping frame-rate to the single-digits) but, of course, it's possible that the fix for that did not address some margin related issues that exist there. In fact, IIRC there were quite some inconsistencies across the Bullet physics server code on how margins are set up for the various shapes, but didn't want to touch those any more than necessary, so the issue is probably around there.

**Comment by fire** [comment]
If Godot 4 has moved bullet externally, this issue should also be closed.

**Comment by Calinou** [comment]
> If Godot 4 has moved bullet externally, this issue should also be closed.

Someone's been working on re-adding Bullet to Godot 4.0, but I don't know if it'll be merged: https://github.com/godotengine/godot/pull/47508

**Comment by akien-mga** [comment]
Fixed by #56801.
