### ISSUE TITLE
"S" shortcut when in GridMap crashes Godot

### ISSUE THREAD

**Issue by zoiba** [godotengine/godot#3460]
when editing a GridMap and using the "S" shortcut for rotating a tile on Y axis will crash Godot. Rotating the tile on Y axis by using the menu just work fine. "A" and "D" shortcuts works fine too.

**Comment by bojidar-bg** [comment]
Can't confirm on 87517c564b83218871ac53afdad375a9501e6cb8

**Comment by akien-mga** [comment]
*Busquad tip:* When reporting issues again a specific version, please mention it in the issue description instead of the issue title. The bug may still be there in version 3.0 if it wasn't fixed quickly, and there the "2.0 Beta" mention in the title will not be so relevant anymore :)

Can't reproduce the issue either (on e4cb104, but I believe it would behave the same with the couple commits more of HEAD). Could you provide a project that reproduces the crash?

**Comment by zoiba** [comment]
thank you for the tips, I'll take in count for next issues. As for this specific issue, the bug is gone when I deleted the .godot folder inside my home folder, so, I'll close this ticket.
