### ISSUE TITLE
GDScript match binding reports a warning

### ISSUE THREAD

**Issue by ntsik** [godotengine/godot#34697]
**Godot version:** 3.1.2.stable.official

**Issue description:** `match`'s binding pattern produces this warning: `The variable 'new_var' was used but never assigned a value.`

**Steps to reproduce:** Use `match`'s binding pattern in a project as per the [documentation](https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#match) (search for `binding pattern`).

**Minimal reproduction project:**

```
match true:
	var new_var: # This line produces the warning
		print(new_var)
```

**Comment by FlashDaggerX** [comment]
Issue is confirmed to be present on **3.2.beta.custom_build.406dac191** (commit 406dac191)

**OS:** Arch Linux, kernel 5.4.6-arch3-1
**Graphics:** Intel Integrated Graphics UHD 620 (Whiskey Lake)

For those who don't understand the error, the binding pattern displayed above is like the `default` case in other languages, except it gives the default value a variable name. In the case above, it assigns the variable `new_var` the boolean value `true` since no other cases exist.

**Comment by Zoomulator** [comment]
This is also the case for the array patterns, not just the catch-all match case.
```GDScript
match [1,2]:
    [1, var x]: # Produces the same warning.
        print(x)
```
