### ISSUE TITLE
Unable to set scale in control child under scrollcontainer

### ISSUE THREAD

**Issue by joelmo** [godotengine/godot#34716]
**Godot version:**
v3.1.2.stable.official

**OS/device including version:**
win 10

**Issue description:**
No effect when scaling child under scrollcontainer. I want to use this to enable zooming in a GUI.

**Steps to reproduce:**
Change rect scale in VBoxContainer or other control under ScrollContainer.

**Minimal reproduction project:**
Yes, 
[scrollcontainerscalechild.zip](https://github.com/godotengine/godot/files/4012599/scrollcontainerscalechild.zip)

**Comment by groud** [comment]
As all containers, ScrollContainer override their children anchors and margins values, and consequently their size. 
This is an expected bahaviour, and you thus should add a intermediate normal control node in the hierarchy to solve the problem.

**Comment by joelmo** [comment]
I dont think this is expected since scrollbars and area should adjust to its first child. And scale change that area. But for now my solution will be to change the minimum area of child whenever i want to scale.

**Comment by groud** [comment]
> But for now my solution will be to change the minimum area of child whenever i want to scale.

Yes, the minimum size is considered by containers, so that's the correct way to do so if you want to override the default computation of minimum size. If you have a Control node which is not a container as a child, you can also implement the [_get_minimum_size()](https://docs.godotengine.org/en/3.1/classes/class_control.html#class-control-method-get-minimum-size) method, that allow you to compute and return the minimum size you want.
