### ISSUE TITLE
Kinematicbody fails to follow rotation

### ISSUE THREAD

**Issue by Janders1800** [godotengine/godot#34807]
**Godot version:**
3.2 beta 5

**OS/device including version:**
Zorin OS 15

**Issue description:**
I have a platform which is a kinematicbody and in 3.1 the character followed the rotation no problem, but in 3.2 beta 5 it fails to follow the rotation of the platform.

Behaviour in 3.1.2
![3 1](https://user-images.githubusercontent.com/27329423/71758548-5b9f4b80-2ea1-11ea-9475-083723c590db.gif)

Behaviour in 3.2 beta 5
![3 2](https://user-images.githubusercontent.com/27329423/71758551-6954d100-2ea1-11ea-9be7-fcc330e6c42b.gif)

**Minimal reproduction project:**
https://github.com/Janders1800/3D-Platformer

**Comment by akien-mga** [comment]
The regression seems to happen between 3.2 beta 2 and 3.2 beta 3.

Likely related to changes from #33864, cc @madmiraal.

**Comment by madmiraal** [comment]
Yes, it's definitely caused by #33864, which added:
https://github.com/godotengine/godot/blob/2299fb819808f5cab5140d31abe7e4dc0b0707df/scene/3d/physics_body.cpp#L1154-L1161

Updating the floor velocity with the current linear velocity of the platform discards the contribution provided by the rotation as calculated here in Godot physics:
https://github.com/godotengine/godot/blob/2299fb819808f5cab5140d31abe7e4dc0b0707df/servers/physics/space_sw.cpp#L975
and here in Bullet physics:
https://github.com/godotengine/godot/blob/2299fb819808f5cab5140d31abe7e4dc0b0707df/modules/bullet/space_bullet.cpp#L1024
Without the current collision point, we cannot calculate the current velocity due to rotation.

I'll submit a PR to fix it.
