### ISSUE TITLE
unable to preload packscene of the same type as self

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#34857]
**Godot version:**

3.1

**OS/device including version:**

Win 10

**Issue description:**

I have a breakout clone with a player `Paddle` being `kinnematicBody2D` with custom `class_name Paddle`
I have a inherited scene `PaddleLong` 

In original `Paddle`

I would like to preload `onready var PaddleLong = preload("res://Source/Paddle/PaddleLong.tscn") ` so I can create it later when my `Paddle` picks up a pill to expand. 

I am unable to do so because of the error on preloading object of the same class as self. 

**Steps to reproduce:**

Create a parent node, inherit from it. In parent node try to preload the node that inherits from it. 

**Minimal reproduction project:**
N/A

**Comment by Zylann** [comment]
It doesn't work with `preload` because in order to load `paddle_long.tscn`, Godot has to load `paddle.tscn`. To load `paddle.tscn`, it needs to load `paddle.gd`. In order to load `paddle.gd`, it needs to load... `paddle_long.tscn`. That's a reference cycle.

The solution is to write:
`var PaddleLong = load("res://paddle_long.tscn")`

**Comment by KoBeWi** [comment]
As per above comment, it doesn't look like engine problem.

Although might be a bit related to #25252
