### ISSUE TITLE
Editor tries and fails to import invalid resources every time it is opened or focused

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#34945]
**Godot version:** 28655e16d65ba8e5e281dd1be65d21b6630559c3 (current master)

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
If in your project there is an asset file which for some reason can't be imported, the editor will try to do it each time when engine window is regaining focus.
This behaviour can lead to some inexplicit consequences - for example EditorPlugin's "scene_changed" signal is called at the moment of such reimport.
I think it would be the best if there would be an error information for the user after starting the engine that there are some broken files in the project (and editor should not try to reimport them again in current session anymore).
For the reference, we had a similar issue in the past #9930

**Steps to reproduce:**
1. Download broken_asset_project.zip project, unpack it and open in Godot.
2. When starting the editor you will see it's importing assets.
3. Open any other aplication to lost window focus
4. Refocus the editor, observe '(Re) importing assets' dialog was visible for brief moment.

**Minimal reproduction project:**
[broken_asset_project.zip](https://github.com/godotengine/godot/files/4039647/broken_asset_project.zip)

**Comment by fire** [comment]
The ideal fix is this anti import loop should be for all resources.

Only when the developer restarts the editor is the check reset.

The anti-loop shouldn't be only for GLTF2.

**Comment by akien-mga** [comment]
Confirmed, and I agree that this shouldn't be handled specifically for glTF but for any kind of resources which fails importing repeatedly.

**Comment by fire** [comment]
I think this anti-loop feature should be written as a proposal.

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
