### ISSUE TITLE
Toggle select issue in multi-select mode Tree

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#34941]
**Godot version:** v3.2.beta.custom_build.e7b7dc57f

**OS/device including version:** macOS Catalina 10.15.2 / MacBook Pro (Retina, 13-inch, Early 2015)

**Issue description:**

In multi-select mode Tree, the "ui_select" action can be used to toggle the selection state of the current focused cell. But after toggling, the next Up/Down arrow key fails to move the cursor. (Left/Right arrow key works fine.)

I tested the official builds, this behavior exists in 3.2 alpha0, and does not happen in 3.1.2 stable.

Also, in the default Input Map, both "ui_select" and "ui_accept" contains the Space key. I have to remove the Space key from "ui_accept" to make the toggling work. (Otherwise, the Space key will do activation instead of toggling.)

FYI: 3.1.2 uses direct key handling instead of the action mechanism.

**Steps to reproduce:**
1. Prepare the project (or use the reproduction project below)
    1. Create a Tree, and set its "Select Mode" to "Multi"
    2. Delete "Space" from the "ui_accept" action in Input Map
    3. Add some items to the tree with the script
2. Run the project
3. Click on any cell to select it
4. Play with the Up/Down key freely, the cursor will move accordingly
5. Press Space, the selection state of current cell is toggled
6. Press Up/Down, the cursor won't move
7. Press Up/Down again, the cursor moves

**Minimal reproduction project:**
[Test3.1.2.zip](https://github.com/godotengine/godot/files/4038277/Test3.1.2.zip)

**Comment by follower** [comment]
I can confirm that these issue(s) exist--I haven't specifically run through your steps but it all looks very familiar. (In addition to the Space as `ui_accept` workaround the issue with cursor up/down is due to the space bar incorrectly triggering the incremental search functionality (with associated timeout). )

The move from direct key handling to the action system appears to have unintentionally broken a lot of the Tree functionality--especially around multi-select mode--because some of the subtleties of the previous implementation (and certain niche cases) weren't carried over into the new logic flow.

A combination of incorrect initial start state, the key input handling logic and some other factors causes around a half-dozen issues (particularly with multi-select) which I've run into over the past couple of days. I'm currently in the middle of creating some "minimal" reproduction projects & write-ups.

But just wanted to confirm that you're not the only person who has hit the issues. :)
