### ISSUE TITLE
is there a way for clipping planes?

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#3499]
I want to create simple water but I want to cut meshes , I konw that camera can do this but it will cut(clip) in the normal of camera , but I want to clip in in another rotation, is there any way to clip meshes , you can see water shader from [here](https://habibs.wordpress.com/lake/).
in this blog author using these code to clip

```
Vector3 planeNormalDirection = new Vector3(0, 0, 1);
planeNormalDirection.Normalize();
Vector4 planeCoefficients = new Vector4(planeNormalDirection, -waterHeight);
Matrix camMatrix = reflectionViewMatrix * projectionMatrix;
Matrix invCamMatrix = Matrix.Invert(camMatrix);
invCamMatrix = Matrix.Transpose(invCamMatrix);
planeCoefficients = Vector4.Transform(planeCoefficients, invCamMatrix);
Plane refractionClipPlane = new Plane(planeCoefficients);
device.ClipPlanes[0].Plane = refractionClipPlane;
```

**Comment by reduz** [comment]
no clipping planes in GLES2, and 3D engine will be rewritten this year, so not doing much more work for this

**Comment by reduz** [comment]
kicking to 3.1, where we might implement planar reflections

**Comment by akien-mga** [comment]
I guess it will have to wait again for the next milestone, as new rendering features are scheduled for when Vulkan support will be implemented.

**Comment by io12** [comment]
It turns out that clipping planes can be emulated (with probably worse performance) using the `discard` keyword.

```
shader_type spatial;

uniform vec4 plane = vec4(1.0, 0.5, 0.0, 0.0);

bool culls(vec3 vertex, mat4 cam) {
	vec3 pos = (cam * vec4(vertex, 1.0)).xyz;
	return plane.x * pos.x
		+ plane.y * pos.y
		+ plane.z * pos.z
		+ plane.w < 0.0;
}

void fragment() {
	if (culls(VERTEX, CAMERA_MATRIX)) {
		discard;
	}
	ALBEDO = vec3(1.0, 0.0, 0.0);
}
```

There's a video of this effect here: https://www.youtube.com/watch?v=9hiSy058-20

**Comment by SIsilicon** [comment]
That's great but, wouldn't that mean you'd have to apply that shader to _every_ geometry instance in the scene (or a selected few)?

**Comment by io12** [comment]
Yes, it's not a perfect solution

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
