### ISSUE TITLE
Some methods appear in xml files, but not in the editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#35090]
**Godot version:**
3.2 beta6

**Issue description:**
For example the `get_patch_margin()` in `NinePatchRect`. It has an entry in the xml file of the class, but you can't find it in the editor help. This probably applies to all getters/setters that use a default enum argument.

**Comment by akien-mga** [comment]
It does appear, as the getter of the four `patch_margin_*` properties.

But yes, composite setters with 2 arguments or getters with 1 argument are a bit unconventional and are not really documented in the best way - but they're also not really meant to be used, their implementation is a backend detail.

**Comment by KoBeWi** [comment]
> It does appear, as the getter of the four patch_margin_* properties.

But you can also write the description (unlike other setters/getters) and it's nowhere to be seen. That's the main problem.

**Comment by akien-mga** [comment]
Oh I see. That's a bug in the editor indeed.

We chose to expose those in the classref explicitly since their documentation is a bit more than just "sets <property>", as what property is set depends on an enum value. See #30125.

Seems like I did not check that they'd actually appear in the editor, there might be some code to filter them out.
