### ISSUE TITLE
animation_changed signal is broken

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3520]
in the AnimationPlayer class I tried to use the animation_changed signal but it didn't work.
the finished signal works fine though.

**Comment by eska014** [comment]
Works for me with `AnimationPlayer::queue()`, maybe it should fire from `play()`, `play_backwards()` and either `set_current_animation()` or `set_active()` as well

**Comment by reduz** [comment]
yes, it's ok. This is not a bug, the signal is only meant to be called when a queued animation starts.

**Comment by lordadamson** [comment]
could we possibly have one in the future that just works when any animation is changed? that would be great.

**Comment by reduz** [comment]
generally by design In godot, things that are changed by code (you directly
calling a function) do not emit signals. this makes things muuch easier. So
by that convention I don't think so.
If you are calling the code yourself you should be able to call whathever
it happens there. Also in the wosrst case, you can make the animaiton call
a function too
