### ISSUE TITLE
Timer Node: Autostart in Editor doesn't work

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#35289]
**Godot version:**
Godot 3.2 RC 1

**OS/device including version:**
Linux 5.4.12-arch1-1 

**Issue description:**
Checking the the Autostart Setting of a Timer in the Editor doesn't work.
`print($Timer.autostart)` always returns false.

`$Timer.autostart = true` instead works

**Steps to reproduce:**
1. Use a Timer Node 
2. Check the Autostart button in the Editor.

**Minimal reproduction project:**
Use a Script to check if the Autostart is enabled or not:
`print($Timer.autostart)`

**Comment by dankan1890** [comment]
Autostart via editor works as expected, by checking the remaining time in '_process' you can see that it has started.
The problem is that after being started it is set to false, before it even gets to the '_ready' function of the calling node.
Just do that check in the '_enter_tree' function of the parent node.
