### ISSUE TITLE
Game crashes when quitting while Area2D body_exited signal tries to change scene simultaneously

### ISSUE THREAD

**Issue by JupiterRider** [godotengine/godot#35323]
**Godot version:**
Godot_v3.2-rc1_mono_x11.64

**OS/device including version:**
Linux 5.4.12-arch1-1

**Issue description:**
Example:
You have a `on_Area2D_body_exited(Node body)` signal and when triggered the scene has to change with `GetTree().ChangeScene("res://anyScene.tscn")`.

But if you now quit the game with `GetTree().Quit()`, that signal will get triggered anyway and the Game crashes.

In the Editor you'll then find a mono_crash.*.json and on an exported game, you'll see this in the commandline:

Native Crash Reporting
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

**Steps to reproduce:**
1. Create a project 
2. Use an Area 
3. Add a signal:
`on_Area2D_body_exited(Node body)`
4. Put `GetTree().ChangeScene("res://anyScene.tscn")` into that signal function
5. Use a KinematicBody or whatever to trigger that signal
6. Start the Game and quit it by using `GetTree().Quit()`

**Minimal reproduction project:**
https://github.com/JupiterRider/AreaLeft
![Screenshot_20200119_193423](https://user-images.githubusercontent.com/60042618/72686234-c5029980-3af2-11ea-80b4-61832f2a8511.png)

**Comment by akien-mga** [comment]
Confirmed in the current master branch (90a224c6).

The Area2D's `body_exited` signal seems to be triggered while it shouldn't, since the crash happens even if you just run the scene, don't move and press escape.

I suspect that #33615 might be involved. Maybe quitting the scene involves having nodes exit the tree in an order which triggers the `body_exited` signal in Area2D.

**Comment by akien-mga** [comment]
> I suspect that #33615 might be involved. Maybe quitting the scene involves having nodes exit the tree in an order which triggers the `body_exited` signal in Area2D.

It's not due to #33615, but otherwise my guess was correct. The issue is reproducible in 3.1.2-stable too.

When quitting, if a PhysicsBody2D is enclosed in an Area2D, it will exit the tree, thus triggering Area2D's `body_exited` signal (unless the latter has exited the tree already, so it depends on their parent/child/sibling relationship). If the callback for that signal does anything fancy like trying to change the scene, it will indeed crash.

Here's a GDScript even more minimal example: [Area2D_quit.zip](https://github.com/godotengine/godot/files/4083537/Area2D_quit.zip)
Run the scene and press <kbd>Escape</kbd>.

Backtrace:
```
Thread 1 "godot-git" received signal SIGSEGV, Segmentation fault.
0x0000000002a8b698 in Node::add_child (this=0x0, p_child=0x5f9a1b0, p_legible_unique_name=false) at scene/main/node.cpp:1177
1177            ERR_FAIL_COND_MSG(data.blocked > 0, "Parent node is busy setting up children, add_node() failed. Consider using call_deferred(\"add_child\", child) instead.");
(gdb) bt
#0  0x0000000002a8b698 in Node::add_child (this=0x0, p_child=0x5f9a1b0, p_legible_unique_name=false) at scene/main/node.cpp:1177
#1  0x0000000002aba93a in SceneTree::_change_scene (this=0x6401e90, p_to=0x5f9a1b0) at scene/main/scene_tree.cpp:1290
#2  0x0000000001706b6d in MethodBind1<Node*>::call (this=0x63a49e0, p_object=0x6401e90, p_args=0x7fffffffce10, p_arg_count=1, r_error=...) at ./core/method_bind.gen.inc:775
#3  0x0000000003855869 in Object::call (this=0x6401e90, p_method=..., p_args=0x7fffffffce10, p_argcount=1, r_error=...) at core/object.cpp:921
#4  0x000000000384c4e5 in MessageQueue::_call_function (this=0x5508580, p_target=0x6401e90, p_func=..., p_args=0x7fffeb62a038, p_argcount=1, p_show_error=false) at core/message_queue.cpp:250
#5  0x000000000384c7a1 in MessageQueue::flush (this=0x5508580) at core/message_queue.cpp:297
#6  0x000000000147469f in Main::cleanup () at main/main.cpp:2150
#7  0x0000000001434331 in main (argc=1, argv=0x7fffffffd748) at platform/x11/godot_x11.cpp:57
```
