### ISSUE TITLE
Deal with "centrifugal forces" effect in KinematicBody move_and_slide on rotating platform 

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#35365]
referring to #16450

As no one reply me in the above issue and the issue is closed, I open a new issue.

In the above issue, @madmiraal  said it is normal for a KinematicBody get "centrifugal forces" effect on a rotating platform.
However, although it may be correct in physics simulation, if I am making a 3d platformer, I think I don't expect my character, who is standing on a rotating platform, eventually will be moved to fall off the platform. 

Is there any workaround to disable this "centrifugal forces" effect? 
Or I am implementing the rotating platform in a 3d platform in a wrong way?
Or is it really not a bug, but a expected behavior?

**Comment by tastesliketriangle** [comment]
A workaround could be to parent your character to the platform they are standing on. This *should* prevent them from sliding off.

Another thing to look into is increasing the friction of either the character or platform. This *could* reduce or eliminate sliding depending on the speed of the platform.

**Comment by madmiraal** [comment]
@nagasawamaki It is a limitation of using a computer to simulate physics using discrete time steps. 

Do @tastesliketriangle's suggestions work?

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
