### ISSUE TITLE
The "Signals" dock's size jumps when selecting nodes

### ISSUE THREAD

**Issue by katoneko** [godotengine/godot#35367]
**Godot version:**
3.2 RC2

**OS/device including version:**
Windows 10

**Issue description:**
When selecting and deselecting nodes in editor, the signals dock changes its horizontal size suddenly.

![f8DSWpNyiA](https://user-images.githubusercontent.com/48890128/72740240-1b410c80-3bc7-11ea-9949-442c30109946.gif)

The issue is present in 3.2 RC2, goes through to as far as 3.2.beta1 and is not present in 3.1.2.stable.

May be related to #33741 and #35324

**Steps to reproduce:**
Add a node, select it, see the signal dock change its size.

**Comment by avencherus** [comment]
My mistake, this ended up being unrelated to #33741 and #35324.

**Comment by YeldhamDev** [comment]
@avencherus Are you sure that didn't solve it? I'm trying to reproduce this now and the dock doesn't change size.

**Comment by avencherus** [comment]
@YeldhamDev Yeah it is, glad you asked about it, your suspicion was correct.  I didn't take into account the editor layout when testing.

To reproduce this one, have the signal dock in the left like he does, and the tree dock in the right.  Then click to select a node and deselect it by clicking on the canvas.

The resize is slight, and doesn't appear to be because of the text change.  If I had to  guess, maybe the signal list is in a container with some margins, and that's what is being hidden.

**Comment by ericrybick** [comment]
Yep this still happens if Inspector & NodeDock do not share the same side of the editor.

Steps to reproduce:
1. open editor
2. load default editor layout 
3. separate the NodeDock from the InspectorDoc (make sure they are not on the same side of the editor)
4. make sure that NodeDock is visible
5. select or deselect a Node in the SceneDock
