### ISSUE TITLE
Vector2.reflect not working consistently

### ISSUE THREAD

**Issue by Beechside** [godotengine/godot#35504]
Godot 3.2 RC2

Mac OS 10.14.6 Mojave

`Vector2.reflect(reflection_vector)` works for reflection_vector Vector2.UP and Vector2.RIGHT but not for Vector2(1, 1) or other specified reflection vectors.

There is a long standing issue from 2017 (#11678) which may be linked but was never marked as a bug.

```
var v = Vector2(2, 4)
print(v.reflect(Vector2(1, 1)))
```
prints (0, 0), which is incorrect

**Comment by HiddenSide** [comment]
In case it helps with something, using normalized () works as expected:
```
var v = Vector2(2, 4)
print(v.reflect(Vector2(1, 1).normalized()))
```
print (4, 2)

**Comment by groud** [comment]
Yes, I tested too, it works fine if the vector is normalized. 
I guess the reflect function could normalize the vector before using it, though it is typically expected to have a normalized vector as a parameter.

**Comment by akien-mga** [comment]
There is an error telling you that the normal vector has to be normalized, so it seems to behave as expected.

**Comment by akien-mga** [comment]
![Screenshot_20200124_131419](https://user-images.githubusercontent.com/4701338/73068409-7155ce80-3eab-11ea-8398-b5a926cd7907.png)

**Comment by groud** [comment]
Moving to discussion then.

**Comment by Sslaxx** [comment]
Could stand to have a more human-readable version of that.

**Comment by Xrayez** [comment]
See my [demo/learning project](https://github.com/Xrayez/godot-vector-bench) regarding `Vector2` operations, indeed some methods do require those to be normalized, which is done automatically in the demo regardless of vector length.

Note that `Vector2(1,1)` normalized is actually `Vector2(0.707107, 0.707107)` which has a length of `1`.

**Comment by Beechside** [comment]
Of course, UP and RIGHT etc are normalized by definition.  Two thoughts:

1. As a user, I don't expect to have to present a normalized vector.  I think only of my line of reflection.
2.Following the old adage "You can't document your way out of a usability issue", I would have thought it appropriate to normalize within the method code, since it doesn't affect the inputs and is not dangerous.

Probably the wrong place for this but thank you to the fantastic team who make Godot the go-to engine.  Very much appreciated...

**Comment by Calinou** [comment]
> As a user, I don't expect to have to present a normalized vector. I think only of my line of reflection.

Unfortunately, doing this has a performance cost (even if the vector is already normalized). This is why it's not done automatically.

**Comment by akien-mga** [comment]
> Following the old adage "You can't document your way out of a usability issue", I would have thought it appropriate to normalize within the method code, since it doesn't affect the inputs and is not dangerous (AFAIK).

That's a fair expectation, but this has a performance cost. Normalization involves some computation which is best avoid when we can, which is why currently the method will only check, **on debug builds**, if the vector is not normalized to warn the user. Then, in a release build, it will skip the check and use the vector as is, expecting it to be normalized, and thus being more efficient (but possibly wrong if you did not pay attention to debug errors).

https://github.com/godotengine/godot/blob/97cc2e53f6fbba7e85a2cbb79f38e077a6e511f7/core/math/vector2.cpp#L199-L204

That being said, it's debatable whether the performance cost outweighs the additional expectation from the user. For `Vector2.reflect`, maybe not, but the same logic is used for `Vector3`, `Quat` and others where the normalization is even most cost intensive.

**Comment by Beechside** [comment]
I appreciate the extra information.  Thank you.

1) I don't understand the additional performance cost, if the user has to call the normalize method in any case.  OK, an extra conditional test for V2, V3, Quat etc but not a significant amount of extra code executed (again AFAIK)

2) Returning (0, 0) when not normalised seems wrong.  There is a material difference between putting an error message (even with #35510, for which thank you) and outputting a wrong result.  Might execution stop to make the error more explicit?

**Comment by Xrayez** [comment]
> Returning (0, 0) when not normalised seems wrong

Yeah, I wonder whether these errors should actually be replaced with warnings. I've also noticed occasional false-positives even with `normalized` vectors being passed, likely because of floating point error.

**Comment by akien-mga** [comment]
> I don't understand the additional performance cost, if the user has to call the normalize method in any case. OK, an extra conditional test for V2, V3, Quat etc but not a significant amount of extra code executed (again AFAIK)

Normalizing a vector involved adding the square of its components, and then taking the square root of that. Multiplications and square root are not trivial operations, and while not prohibitively expensive, it can add up when used by the physics or rendering engines.

If the responsibility is on the user's end, you can handle your vectors in a way that won't force you to normalize all the time. Chances are that you may already be using a normalized vector, either because it's a unit vector like `Vector2.UP`, or because you saved it as a constant to reuse in each frame instead of renormalizing on each function call.

See e.g.:
```
const var NORM_TOPRIGHT = Vector2(1, -1).normalized()

var some_vec = Vector2()

func _physics_process():
    some_vec = ... # (any logic that sets its value)
    var reflection = some_vec.reflect(NORM_TOPRIGHT)
```
With the current code, normalization well happen only once, even if you call it for 100000 frames (half an hour).

While if the method always normalizes without you having control of it:
```
const var TOPRIGHT = Vector2(1, -1)

var some_vec = Vector2()

func _physics_process():
    some_vec = ... # (any logic that sets its value)
    var reflection = some_vec.reflect(TOPRIGHT)  # normalizes TOPRIGHT every single frame
```
So here in half an hour you'd be calculation `Vector2(1, -1) / sqrt(1 * 1 + (-1) * (-1))` 100000 times.

**Comment by Calinou** [comment]
Closing, as it seems we agreed upon not normalizing the vector automatically for performance reasons. The error message when using a non-normalized vector was improved in #35510.
