### ISSUE TITLE
get_nodes_in_group() returns null value

### ISSUE THREAD

**Issue by j5E01** [godotengine/godot#35503]
Godot version:
Godot_v3.1.2stable.official

OS/device including version:
Windows 10

Issue description:

I have followed the save/load tutorial shown [here](https://docs.godotengine.org/en/latest/tutorials/io/saving_games.html)
```
func _on_Button_pressed():
	var save_nodes = get_tree().get_nodes_in_group("Persist")
	for i in save_nodes:
		i.queue_free()
```
This code isn't working. I have many nodes in group " Persist " added via "NewNode.add_to_group("Persist")" code instantiated elsewhere -  and the debugger shows that save_nodes is [null]

**Comment by bojidar-bg** [comment]
Check for spelling mistakes, it is easy to slip and write "Presist" instead of "Persist".

I can't see a way for `get_nodes_in_group` to return `null`, an returning `[null]`, an array with a single null element, does not seem likely either.

At any rate, a minimal reproduction project would be great.
