### ISSUE TITLE
off by one error in string tests

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#3553]
https://github.com/godotengine/godot/blob/a77b786683483448d7a9d5d5a33b7ae19c9fa4d3/bin/tests/test_string.cpp#L907

```
> Godot_v2.0_beta_20160126_win32.exe -test string
...
Passed 28 of 27 tests
```

**Comment by akien-mga** [comment]
Thanks. It doesn't seem to be off by one but that the parameters are swapped, it should actually be "Passed 27 of 28 tests" I suppose (which means one test failed, does the rest of the output confirm that?).

Feel free to propose a PR that swaps the two parameters as you already did most of the job :) If not I can of course do it too, I just propose so that you can get attribution for looking into it :)

**Comment by techtonik** [comment]
> it should actually be "Passed 27 of 28 tests" I suppose (which means one test failed, does the rest of the output confirm that?).

Now I see, one test failed.
```
Test 26: RegEx
	match: true
	3 captures:
name:password
name
password
	FAILED
```

Submitted PR. Will create a new issue for that bug.

**Comment by techtonik** [comment]
Failed test is in issue #3556.
