### ISSUE TITLE
Bug in the order of 3D transparency

### ISSUE THREAD

**Issue by AlphinAlbukhari** [godotengine/godot#35573]
**Godot version:** 3.2 RC3

**OS/device including version:** Windows 10

**Issue description:** I do not know to explain it
If I enable "Transparent", sometimes the order is weird
![bug](https://user-images.githubusercontent.com/54466934/73131108-9c6d2900-4037-11ea-9cb1-066767ab7089.gif)

**Steps to reproduce:** Create 2 MeshInstance with different materials
Enable "Transparent" for each material
Change Alpha on Albedo

**Minimal reproduction project:** https://www.mediafire.com/file/nfj633s1vcdwxxh/tcrystal.tscn/file

**Comment by clayjohn** [comment]
Transparent objects can be very frustrating to work with. They are sorted based on depth in order for them to properly blend. However, sometimes that fails, as you see here. From certain angles, based on object position, the inner crystal gets sorted in front of the outer crystal. 

In order to avoid this problem you need to set the "render_priority" of the crystal material. Set the outer crystal to have a higher priority so that it always gets sorted to be in front of the inner crystal and you should be fine. :)
