### ISSUE TITLE
Wrong click behaviour (input event) on Android (Godot 3.2 RC 4)

### ISSUE THREAD

**Issue by mrcrb** [godotengine/godot#35655]
**Godot version:**
3.2 RC 4

**OS/device including version:**
Tested on Android 8.0.0 (Samsung S7 Edge [SM-G935F]) and Android 9 (Samsung S8 [SM-G950F])

**Issue description:**
(Description is related to sample project, see **Minimal reproduction project** for GitHub repository link)

With _Godot 3.2 Beta 2_ the click behaviour is as intented: clicking **quickly** on the buttons (from one to the next) turns them from green to blue (and back to green if clicked again). 

With _Godot 3.2 RC 4_ the click behaviour is buggy: clicking **quickly** on the buttons (from one to the next) almost every click turns the previously clicked button (which was blue) to green again.

**Steps to reproduce:**
- Start the app on an Android device
- you should see 5 green "buttons"
- click the first, then quickly click the second, the third, ...
- green color turns to blue (and blue color turns to green)

- With Godot 3.2 Beta 2 this works correct (no matter how quick the next buttons are clicked)
- With Godot 3.2 RC 4 this is buggy (previously selected button changes its color if next button is clicked quickly)

**Minimal reproduction project:**
https://github.com/mrcrb/Godot-3.2-Android-Click-Bug

**Comment by akien-mga** [comment]
I can confirm the regression on my Xiaomi Pocophone F1.

I tested intermediate versions between 3.2 beta 2 and RC 4:
- Beta 5 works fine.
- Beta 6 crashes (due to #35049).
- RC 1 has the issue.

This is likely a regression from #33630, CC @AlexHolly. It likely handles this rapid presses as double tap events, even though they're not pressing the same approximate location.
Can we configure the threshold for what should be a double tap? CC @m4gr3d
