### ISSUE TITLE
SpatialMaterial Flags: Unshaded and Use Shadow as Opacity updates incorectly

### ISSUE THREAD

**Issue by JohnMeadow1** [godotengine/godot#35665]
**Godot version:**
3.2.rc4
**OS/device including version:**
Win 10
**Issue description:**
It looks like changing SpatialMaterial Flags update update material incorrectly.
![flags-error](https://user-images.githubusercontent.com/23294139/73279723-d7b15880-41ed-11ea-8ceb-37f758618814.gif)
**Steps to reproduce:**
Scene3D:
 - Mesh instance -> Cube with Material Override ->Spatial, set Albedo alpha to 100
 - Omni Light

Material set flags:
- Transparent
- Shadow to Opacity
- Unshaded

Unset flags
- Transparent
- Shadow to Opacity

At this point the cube is not updated properly need to toggle Unshaded flag for an update.

**Minimal reproduction project:**
Just a cube in 3D

Might be related to: https://github.com/godotengine/godot/issues/35401

**Comment by clayjohn** [comment]
I think this is caused by the cache flag here
https://github.com/godotengine/godot/blob/1c3aff42dea3f9d9c49e6395dd4a9c848e65cbf6/scene/resources/material.h#L252

It only provides 18 bits but there are 19 flags

https://github.com/godotengine/godot/blob/1c3aff42dea3f9d9c49e6395dd4a9c848e65cbf6/scene/resources/material.h#L177-L198

Just switching 
https://github.com/godotengine/godot/blob/1c3aff42dea3f9d9c49e6395dd4a9c848e65cbf6/scene/resources/material.h#L252

to "19" should be enough.
