### ISSUE TITLE
Geometry.clip_polygons_2d() is bug

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#35676]
**Godot version:** 3.2rc4

**OS/device including version:** any

**Issue description:** instead of cutting a hole it produce stacked polygon if b completely inside a. the behaviour is right if b only clipped part of a.
![Peek 2020-01-29 07-10](https://user-images.githubusercontent.com/13792627/73309898-83968a80-4266-11ea-8a05-dc30d7acf79e.gif)

**Steps to reproduce:** -

**Minimal reproduction project:** 
[geometry.tar.gz](https://github.com/godotengine/godot/files/4124935/geometry.tar.gz)

**Comment by Calinou** [comment]
cc @Xrayez

**Comment by fian46** [comment]
@Calinou  done

**Comment by fian46** [comment]
enable visible navigation debug to see the result in debug menu

**Comment by Xrayez** [comment]
I wouldn't call this a bug, but this is certainly a limitation in such cases like this. It's expected that the `clip_polygons_2d` returns two separate polygons, one being the boundary and another one as a hole, because it's impossible to represent it geometrically otherwise, unless it's a [keyholed representation of a polygon](https://sourceforge.net/p/polyclipping/discussion/1148419/thread/2e8190c601/), which again is not supported by the Clipper library used currently for polygon boolean operation methods. For more details on this see https://github.com/godotengine/godot-proposals/issues/200#issuecomment-549300676. 

Having said that, the method can't be blamed for incorrect results for this use case, but further attempts to use such result with other *polygon decomposition* methods in Godot are limiting indeed:

1. Godot's `Geometry.triangulate_polygon` doesn't support holes either, and it only works for strictly simple polygons. Recall `Bad Polygon!` errors?

2. [Polypartition](https://github.com/ivanfratric/polypartition) used as [another thirdparty library in Godot](https://github.com/godotengine/godot/blob/6a5ffb8f6eb1ff36d3fa69659e48b7a6b77d1f2a/thirdparty/misc/triangulator.h
) does support holes to some extent. I've tried it myself in the past but it's quite slow for objects with lots of holes and it breaks on [degenerate polygons](https://cs.stackexchange.com/a/12547) easily. None of the methods are currently exposed to scripting from this library though. It's used for `NavigationPolygon` in Godot currently. What can be possibly done is exposing some of the library's methods to `Geometry` singleton to help this, namely `Geometry.decompose_polygon_in_convex`, with the ability to pass an array of both outer and inner (holes) polygons.

The new Clipper 10.0.0 alpha/beta does support polygon triangulation with holes but it can't be considered stable for production to be used in Godot yet, but it could solve many functional and performance limitations Godot currently has in this area. If you do want to experiment with this on the C++/GDScript level, you can take a look at my [godot-clipper](https://github.com/Xrayez/godot-clipper) module, but then again it doesn't provide this out-of-the-box yet as there's many ways to use the library, and I'm waiting for the library to become stable enough before continuing working in this direction to make this general-purpose perhaps.

**Comment by fian46** [comment]
After translating and reading the maintainer explanation i can understand this is just some limitations and not a bug. I am sorry for calling it a bug. We can close this issue.

**Comment by Xrayez** [comment]
@fian46 I solved your use case, what I've done instead is to call `make_polygons_from_outlines` because that's how those outer/inner polygons get sorted out internally. I haven't used navigation code yet to figure this out sooner. 😛

```gdscript
func cream():
	for i in $Navigation2D.get_children():
		i.queue_free()

	var target = $Polygon2D
	var moving = $Polygon2D2
	moving.position = get_local_mouse_position()

	var pa = extract_polygon(target)
	var pb = extract_polygon(moving)

	var clip = Geometry.clip_polygons_2d(pa, pb)

	var np = NavigationPolygon.new()
	for poly in clip:
		np.add_outline(poly)
	np.make_polygons_from_outlines()

	var npi = NavigationPolygonInstance.new()
	npi.navpoly = np
	$Navigation2D.add_child(npi)
```

![geom-nav-clip-hole](https://user-images.githubusercontent.com/17108460/73361109-f32f6880-42ac-11ea-8b05-db6f2eb7b1e8.png)

[geom-navpoly-clip-solved.zip](https://github.com/godotengine/godot/files/4128230/geom-navpoly-clip-solved.zip)

**Comment by fian46** [comment]
It wont work if you split the polygon with the cuter polygon. I try this method because it work on splitting the polygon. I think it some kind of limitations.

**Comment by Xrayez** [comment]
By splitting you mean something like this?

![geom-nav-clip-hole-split](https://user-images.githubusercontent.com/17108460/73363053-a3eb3700-42b0-11ea-8431-e7f21ea5b21b.png)

If yes, then it seems to works with the code I linked, no part is missing.

**Comment by fian46** [comment]
Let's close this and wait for 4.0 navigation server implementation. The PR looks good.

**Comment by fian46** [comment]
Wow you solve the missing puzzle. This is amazing, it do work. You are really cool. Now i can generate random level. Thanks man

**Comment by akien-mga** [comment]
Closing as discussed above.
