### ISSUE TITLE
Wrong offset on secret center-aligned content of LineEdit

### ISSUE THREAD

**Issue by Kenska** [godotengine/godot#35699]
**Godot version:** 
release 3.1.2

**OS/device including version:** 
Windows 10

**Issue description:** 
The offset on a secret center-aligned content of a LineEdit is off, I suppose because it is taking the clear text's length instead of the secret characters's length.

**Steps to reproduce:**
1. Create a project
2. Add two LineEdit controls to a UI
3. Set their Align property to Center and fill the same text in both
4. Check the second LineEdit Secret property

**Minimal reproduction project:**
[WrongOffsetExample.zip](https://github.com/godotengine/godot/files/4128746/WrongOffsetExample.zip)

![image](https://user-images.githubusercontent.com/9397887/73368791-e103f900-42b1-11ea-8bb3-0951f883753d.png)

**Comment by akien-mga** [comment]
Could you check if it's reproducible in the newly released Godot 3.2?

**Comment by Kenska** [comment]
Unfortunately, it still is!

**Comment by Kenska** [comment]
I post it here because I believe it is related to the same issue: the text selection is also off for all secret LineEdit, independently of any specifc text alignment.

**Comment by sumit0190** [comment]
This happens because the `cached_width` of the text isn't recalculated when a secret character (or the `is_secret` property) is changed.

I made that small modification to my `line_edit.cpp` and voila, it works. I'd be very happy to make a PR, although I doubt the way I've done it is correct in all cases.
![star](https://user-images.githubusercontent.com/8823156/73387506-af356700-429e-11ea-921d-44bcc7ee83eb.png)
Note that if the secret character is changed, my change would recalculate the width to preserve alignment, as shown in the following screenshot.
![f](https://user-images.githubusercontent.com/8823156/73387584-c411fa80-429e-11ea-9a93-42469be8fe83.png)

**Comment by Calinou** [comment]
@sumit0190 Thanks for tackling this issue! Feel free to open a pull request, we'll review it :slightly_smiling_face:
