### ISSUE TITLE
Inconsistent object name for generated collision

### ISSUE THREAD

**Issue by Shatur95** [godotengine/godot#35690]
**Godot version:**
68eae6b6e

**OS/device including version:** Arch Linux

**Issue description:** When generating collision using `-convcol` hint for glTF, `StaticBody` and `CollisionShape` objects are named in snake_case. But the editor uses CamelCase for objects on the scene by default.

**Steps to reproduce:**

1. Download model model with `-convcol` hints: [Strump.blend](https://github.com/Zoriya/asset-sources/blob/master/Objects/Vegetation/Trees/Strump.blend)
3. Open in Blender.
2. Export as glTF.
3. Import in Godot.
4. You will see `static_collision` name for `StaticBody` object and `shape<number>` for `CollisionShape` objects.

**Minimal reproduction project:**
[Inconsistent object name for generated collision.tar.gz](https://github.com/godotengine/godot/files/4127399/Inconsistent.object.name.for.generated.collision.tar.gz)

**Comment by Calinou** [comment]
Note to people interested in fixing this: the Project Settings have an option to c hoose the default node naming scheme. This setting should be honored when setting the name of the generated collision shapes.

**Comment by Anutrix** [comment]
set_name() calls _validate_child_name() which then calls _generate_serial_child_name() at https://github.com/godotengine/godot/blob/dcfe44f4479ddbf3518d3e753fbf242845402ae4/scene/main/node.cpp#L1097 which checks for `node/name_casing` setting.
Based on this, the Name Casing setting should be respected if we just change `static_collision` to `StaticBody` and similarly change `shape` to `CollisionShape`.

But, there seems to be multiple bugs here. Not tested any of them.
1. This setting is only checked if it's string name is `String()`(i.e, empty string) which can't be possible since we make sure it is !="" in first few lines of `set_name()`.
2. Since PascalCase is set, it just breaks out of the switch case. Thus, causing issues like moe.

**Comment by Shatur95** [comment]
> This setting is only checked if it's string name is String()(i.e, empty string) which can't be possible since we make sure it is !="" in first few lines of set_name().

Yes, I think that this is a typo, need to replace `name == StringName()` with `name != StringName()`.
