### ISSUE TITLE
updating ArrayMesh vertex array does transfer to GPU

### ISSUE THREAD

**Issue by albinaask** [godotengine/godot#35700]
**Godot version:**
3.2 stable
**OS/device including version:**
OS: win 10 64 bit
GPU: Nvidia gtx 750ti, 
**Issue description:**

writing to the vertex list after acquiring it from ArrayMesh.surface_get_arrays(idx) does not update it.
Acquiring it again shows that it ahsn't updated

**Steps to reproduce:**

run scene in project of your choice, note that all vertices are updated to have position (0,0,0) in the for-loop, but it does not retain that position as seen by the printout and the fact that the cube is visible when it should have no volume.

**Minimal reproduction project:**

[error scene.zip](https://github.com/godotengine/godot/files/4128832/error.scene.zip)

**Comment by clayjohn** [comment]
In order to update an ArrayMesh on the GPU you need to call ``add_surface_from_arrays()`` When you retrieve the arrays, you are simply getting an array of data, updating that array does not in turn update the array mesh. 

Please see the [ArrayMesh class reference](http://docs.godotengine.org/en/latest/classes/class_arraymesh.html) for an explanation of the features and a basic example. Also see the [ArrayMesh](http://docs.godotengine.org/en/latest/tutorials/content/procedural_geometry/arraymesh.html) tutorial in the docs for example usage and a more in depth explanation of how it works.
