### ISSUE TITLE
Rich text characters with visibility set to false still take up space within the label

### ISSUE THREAD

**Issue by BanchouBoo** [godotengine/godot#35729]
**Godot version:** 3.2 Stable

**OS/device including version:** Manjaro Linux

**Issue description:** Characters with their visibility set to false within a rich text tag will still take up space outside the tag but not within it.

The text that I'm using to test is: `Hi, my name is [hide char=*]Cal***eb[/hide]abc` which renders as:
![image](https://user-images.githubusercontent.com/32691832/73416365-afefec80-42e2-11ea-9a51-1b93781adab0.png)

```gdscript
tool
extends RichTextEffect
class_name HideCharTextEffect

var bbcode : = "hide"

func _process_custom_fx(char_fx : CharFXTransform):
	var hide_char : String = char_fx.env.get("char", "")

	if not hide_char or hide_char.length() > 1:
		return false

	if char_fx.character == ord(hide_char):
		char_fx.visible = false

	return true
```

**Minimal reproduction project:** [Rich Text Issue.zip](https://github.com/godotengine/godot/files/4131976/Rich.Text.Issue.zip)

**Comment by Calinou** [comment]
cc @Eoin-ONeill-Yokai

**Comment by Eoin-ONeill-Yokai** [comment]
I'll look into fixing this asap.

**Comment by Eoin-ONeill-Yokai** [comment]
@BanchouBoo @Calinou  I've gone ahead and submitted a PR. I've also added an example like yours into my [testing program repository](https://www.github.com/Eoin-ONeill-Yokai/Godot-Rich-Text-Effect-Test-Project) since it definitely seems like a nice and tricky one for catching bugs and regressions. 

I think more could be done here to adjust string length (for example, to replace whole words with other words) but for now a simple fix to this is more than sufficient. Give the patch a try to spot any oddities in the behavior if you can.
