### ISSUE TITLE
Godot 3.2 CPU Usage 100% sometimes

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#35737]
**Godot version:**
3.2
**OS/device including version:**
ubuntu 19.10
**Issue description:**
When i'm coding, every like 30-60 secs the CPU usage goes to 100% in one of threads, which causes 1-3 sec screen freeze

![Screenshot from 2020-01-30 08-18-44](https://user-images.githubusercontent.com/58845030/73445588-c5443580-4339-11ea-8e9d-858c31c693ff.png)

related to #35719 - cuz sometimes input lags occurs too

Computer specs:
SSD 120gb
![Screenshot from 2020-01-30 08-24-34](https://user-images.githubusercontent.com/58845030/73445710-105e4880-433a-11ea-9eed-c370dddd73bc.png)
![Screenshot from 2020-01-30 08-24-46](https://user-images.githubusercontent.com/58845030/73445711-105e4880-433a-11ea-825e-0ee30fe98ab9.png)
![Screenshot from 2020-01-30 08-24-54](https://user-images.githubusercontent.com/58845030/73445712-10f6df00-433a-11ea-89a6-d14c642351ec.png)
 

**Steps to reproduce:**

Code using using ubuntu 19.10

**Minimal reproduction project:**

**Comment by lawnjelly** [comment]
From the periodic nature it makes me wonder if it is another example of resources periodically trying to re-import (and failing each time)? Does it occur in a project with just scripts and no resources (images / model files / sounds etc)?

Other possible culprits might be parsing the scripts.

If you run godot from a console it is just possible it is providing some error / warning messages that can't be seen when you run normally. Worth a try anyway.

If you can figure out a minimum reproduction project that would help a lot because maybe we can replicate it on our machines.

If this doesn't work and it only occurs on your machine, as I wrote in the issue you quoted #35719, profiling can be a good way to pin down what is going on, if you feel confident enough to try.

If you do decide to try this grab a debug build from Calinou's webpage (see my post in that issue), and run a profiler such as valgrind / callgrind. Unfortunately I find callgrind is a bit less user friendly than some of the graphical profilers, so I will understand if this is too involved. I don't know if there are any simpler easier to use linux profilers.

Quick crash course:
```
valgrind --tool=callgrind GODOT_BINARY_PLUS_COMMAND_LINE_ARGS
```
I think from memory the command line args are `-e` to run the editor, and `--path BLAH` to specify which project to load.

This will save a file called `callgrind.out.*****` containing all the timings from your run of Godot. This file can be loaded in another program called KCachegrind to display a graph of the functions and tell you the percentage of time each is using, very useful for pinning down performance issues.

**Comment by nonunknown** [comment]
I'll take a look into this, btw I've created a new project and start working on a plugin and the same problem occurs!

**Comment by nonunknown** [comment]
i'm very newbie into this, but I runned valgrind and sent this command:
``` 
valgrind --tool=callgrind ~/Desktop/godot-3.2-debug-linux-gcc5.4/godot.x11.tools.64 -e --path ~/Desktop/Plugins

```
godot opens but doesn't advance from logo screen! although I've got this when opening my largest project:

[test.zip](https://github.com/godotengine/godot/files/4140898/test.zip)

**Comment by lawnjelly** [comment]
That's right you are doing the right thing, I can open that trace. You have to wait much longer, because when tracing it takes a lot longer to run than normal (maybe 10x as long). The trace shows most of the time spent in making the documentation:

EditorHelp::generate_doc()

**Comment by lawnjelly** [comment]
If you install KCachegrind you can view the trace logs yourself, it is quite enlightening, you can probably guess from the function names what they are doing:

![trace_docs](https://user-images.githubusercontent.com/21999379/73566920-0d0fad80-445d-11ea-8271-b69eed43e102.png)

**Comment by lawnjelly** [comment]
Also in this case, we ideally want to capture one of the freezes. There is also the ability in valgrind to turn it on and off as you run Godot, this might be helpful:

```
valgrind --tool=callgrind --instr-atstart=no ~/Desktop/godot-3.2-debug-linux-gcc5.4/godot.x11.tools.64 -e --path ~/Desktop/Plugins
```
In order to turn on and off the profiling at runtime, open up ANOTHER console window, and type:
```
callgrind_control -i on
OR
callgrind_control -i off
```
This should also allow you to startup much quicker.

**Comment by nonunknown** [comment]
niceee thanks, i'll do it

**Comment by nonunknown** [comment]
dude i'm sorry but godot stays unusable when running valgrind, I waited longer godot opened ok, but unusable! :(

**Comment by lawnjelly** [comment]
Hmm, well well done for trying.. :smile: When valgrind is running the editor will be too slow to use normally, but you can still sometimes capture some data and figure out why it is so slow. Maybe whatever it is is slowing down valgrind too.

Would you be able to make a minimum reproduction project? Maybe we can repeat it on development machines or figure out what is triggering it on your side. Does it occur with a blank project for example?

**Comment by nonunknown** [comment]
I used godot a lot these days and seems that this problem is not happening anymore!
