### ISSUE TITLE
The HDR environmental filter is broken (makes everything black)

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#3574]
My specs:: Windows 10 64 bit, 24 gigs RAM, third gen i7 CPU, and an ATI HD 7.xxx GPU using the Crimson drivers. The build used is a very recent one newer than the official beta.
# 

**The issue** - turning on the HDR in the environmental shading options causes the 3D viewport to become black. I know this is probably not a driver issue because basic HDR is fully functional if you go back to the alpha builds (though a few options are broken which has been the case since version 1).

---

Here's hoping that the developers are open to fixes in the area of 3D even though the renderer is going to be rewritten, it would be nice to have some of these things fixed in the meantime.

**Comment by AfterRebelion** [comment]
Testing on the stable release of Godot 2 (2.1.5), enabling HDR on the enviroment doesn't turn the viewport black, so this issue seems no longer valid.
I'm not sure where this was fixed, since a lot of rendering related changes where made at that time.
The only change directly referencing HDR on 2016 is 7b8fe97 , and that is about a crash, not black screen..

**Comment by akien-mga** [comment]
Yes, this seems to have long been fixed. Thanks for testing to confirm.
