### ISSUE TITLE
Godot Editor Very Slow to Close

### ISSUE THREAD

**Issue by Faustabov** [godotengine/godot#3579]
When I close the editor it takes an absurdly long time to shut itself down, the really annoying bit is that when this is going on you can't interact with the editor anymore meaning it's completely unresponsive while shutting down, which gives a very unsettling feeling to Godot's shutdown sequence as it makes me worry that Godot is about the crash or something similar.

**Comment by akien-mga** [comment]
Indeed, I think it has always been like that, but it would be nice to find a way to improve this with regard to user experience.

**Comment by neikeq** [comment]
I think the wait time is normal (not sure if it can be improved though). About being unresponsive, perhaps it could show a progress dialog or something similar, to make it clear that it's closing and you are not allowed to touch anything.

**Comment by Ace-Dragon** [comment]
I too think this has been the case for Godot since version 1. I will also note that it's not uncommon for applications to need a little time to close depending on which processes are being run.

However, I do think it is possible for the closing process to be optimized (Blender for instances closes in only a matter of seconds).

**Comment by reduz** [comment]
well, it's just deinitializing everything (the editor is huge) so it takes a while.  We will be doing lots of optimizations in 2.1 so this will help there

**Comment by djrm** [comment]
Improved by d61b91cbe0c05466182b15a6dd1899e92fcac749

**Comment by neikeq** [comment]
Yeah, this can probably be closed.
