### ISSUE TITLE
preload function is not highlighted in editor

### ISSUE THREAD

**Issue by trollworkout** [godotengine/godot#3581]
sorry guys. so many issues haha :)

preload works fine is just according to help/editor it is not supposed to exist. i tested it without the load and works. i put both in the same code to show you it is not recognized .

![screen shot 2016-02-04 at 3 38 42 am](https://cloud.githubusercontent.com/assets/6987027/12809962/f80c79e8-caf0-11e5-88f9-86dc18339ac8.png)

**Comment by akien-mga** [comment]
I did some looking around regarding the missing highlight and it's likely because `preload` is not listed as a reserved keyword in GDScript: https://github.com/godotengine/godot/blob/817fd1ab7186d00ec0cf113b4431bc6d31eb8272/modules/gdscript/gd_script.cpp#L2678

For the documentation part, it's likely more complex and could be extended to various other GDScript tokens like yield, assert, so I'll open a different issue for that.

**Comment by akien-mga** [comment]
Moved the second part of this bug report to #3583.

**Comment by trollworkout** [comment]
one day i'll try a junior job myself

**Comment by trollworkout** [comment]
@akien-mga  sorry to disappoint you but  preload still not showing up  :))) PI is , however. i just built a fresh one right now
![screen shot 2016-02-04 at 12 47 28 pm](https://cloud.githubusercontent.com/assets/6987027/12824098/7c607572-cb3d-11e5-9703-9cbb49d2f2ba.png)

**Comment by akien-mga** [comment]
Was a missing comma, it's fixed now :)
