### ISSUE TITLE
Can not add maven repositories for Android modules

### ISSUE THREAD

**Issue by deepmax** [godotengine/godot#35875]
**Godot version:**
3.2

**OS/device including version:**
Ubuntu

**Issue description:**
Migrating Android/Java modules from 3.1 to 3.2, there is no more `android_add_maven_repository` method. Error:

> AttributeError: 'SConsEnvironment' object has no attribute 'android_add_maven_repository':
>   File "/home/masoud/Projects/godot-3.2/SConstruct", line 431:
>     config.configure(env)
>   File "./modules/GodotFireBase/config.py", line 214:
>     env.android_add_maven_repository("url 'https://maven.fabric.io/public'")
> 

**Steps to reproduce:**

Add a new module with this `config.py`:

```
def can_build(env, plat):
        return plat=="android"

def configure(env):
    if (env['platform'] == 'android'):
        env.android_add_java_dir(".")
        env.android_add_maven_repository("url 'https://maven.fabric.io/public'")
        env.disable_module()

```

I've checked the 3.2's source code and there're many dropped methods.

**Comment by Shin-NiL** [comment]
Maybe the  ```[buildscript_repositories]``` and ```[allprojects_repositories]``` sections on the [gradle.conf](https://docs.godotengine.org/en/3.2/tutorials/plugins/android/android_plugin.html#gradle-conf) could help you.

**Comment by Jose-Moreno** [comment]
@deepmax Could it be because Maven along Fabric are being deprecated and rallied towards the Firebase ecosystem? It appears the service and dashboard will cease to functions in March 31st, 2020

https://docs.fabric.io/android/beta/maven.html (read the notice on the docs)
https://get.fabric.io/roadmap (the roadmap indicates Fabric is being deprecated and / or merged with Google Firebase)

Maybe someone else with Android deployment knowledge can confirm this is the reason for the missing methods or is something else amiss?

**Comment by volzhs** [comment]
because android plugin system is changed on 3.2
follow this guide.
https://docs.godotengine.org/en/3.2/tutorials/plugins/android/android_plugin.html
