### ISSUE TITLE
HTTPRequest silent error when invalid custom headers used

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#35956]
**Godot version:**
3.2-stable

**OS/device including version:**
Windows 10

**Issue description:**
HTTPRequest does not error out or sends the request when you pass malformed custom headers; e.g:

```
# Bad
var headers = ["Content-Type", "application/json"]

# Good
var headers = ["Content-Type: application/json"]
```

Spent almost a day thinking there was something wrong with my setup or Godot trying to reach my localhost/public ip.

PD: I commented on this #30245 thinking that was the problem.

**Comment by jonbonazza** [comment]
The only thing I can think to do here is to check wach string in the array for the existence of the ":" character, which is reuired for a valid header in the http spec. Maybe even the ": " (colon + space) string even since i think you need to space too according to the spec. This would be a good "junior" job as it's trivial to implement.

Beyond that, unless the http spec adds other constraints to headers, i'm not sure what else we can reasonably do here.
