### ISSUE TITLE
LineEdit max_length on Android doesn't work

### ISSUE THREAD

**Issue by tinxx** [godotengine/godot#35954]
**Godot version:**
3.2 stable + #35753 (cherry-picked)

**OS/device including version:**
Android 9

**Issue description:**
One cannot trigger signal `text_entered` when `max_length` is set and a string of the same length has been entered.

**Steps to reproduce:**
After applying said patch and building the Android export templates, editing was enabled on Android.
However, after I applied `max_length` I could enter the amount of characters, but the signal `text_entered` could only be triggered after removing 1 (one) character and hitting return again.

**Minimal reproduction project:**

**Comment by tinxx** [comment]
What's more, and I am not sure if it is a bug, when enabling `clear_button_enabled`, the button does not grow with the font size and is awful small on Android.

**Comment by akien-mga** [comment]
CC @MadEqua @pouleyKetchoupp

**Comment by MadEqua** [comment]
I don't have the time to tackle this right now, but took a look and this is the situation:

The text input is processed on [`onTextChanged()` from GodotTextInputWrapper.java](https://github.com/godotengine/godot/blob/0812f991f025ed5ca6e591206a8604acd82c0fa1/platform/android/java/lib/src/org/godotengine/godot/input/GodotTextInputWrapper.java#L102) when the text changes. From there, the new characters are passed to the C++ side, including the return key presses as '\n'.

With the addition of the `InputFilter` of #35438 this callback is not called any more when the limit is reached because text doesn't really change in that case. So the '\n' never get to the engine.

I'm guessing the solution is to use the method `onEditorAction()` to catch the return key presses instead of `onTextChanged()` (perhaps  [here](https://github.com/godotengine/godot/blob/0812f991f025ed5ca6e591206a8604acd82c0fa1/platform/android/java/lib/src/org/godotengine/godot/input/GodotTextInputWrapper.java#L137)). The method is already implemented on that class, but from a quick test I've not seen it being called, and that's probably also not correct.
