### ISSUE TITLE
Logging doesn't use Windows new line character

### ISSUE THREAD

**Issue by TheSecurityDev** [godotengine/godot#36027]
**Godot version:** 3.2.stable

**OS/device including version:** Windows 7

**Issue description:** When logging is enabled, if you look at the log files using notepad, everything is all one line. But if you use Notepad++, you can see the new lines. I'm assuming this is due to the fact that on Windows the new line character is \r\n instead of just \n.

**Steps to reproduce:** Enable logging, and put several errors or something that you can see in the log.

*Bugsquad edit (keywords for easier searching): CRLF, LF*

**Comment by Zylann** [comment]
This appears to be fixed in Windows 10. I tried dragging a script (which also use `\n` only) into Notepad.exe and it was displayed correctly.

**Comment by akien-mga** [comment]
Yes `notepad.exe` was fixed after three decades to finally support Unix-style files: https://blogs.msdn.microsoft.com/commandline/2018/05/08/extended-eol-in-notepad/

**Comment by Calinou** [comment]
PS: Supporting Windows 7-8.1's `notepad.exe` is probably very low-priority by now, since most people will be using Windows 10 or third-party text editors by the time Godot 4.0 is released.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
