### ISSUE TITLE
Tween _on_Tween_all_completed() stops being called after a tween is stopped and started

### ISSUE THREAD

**Issue by haplotypegames** [godotengine/godot#36056]
**Godot version:**
3.2 Master [d617df5](https://github.com/godotengine/godot/commit/d617df5f3460a2bb55ce41497fdc24a885bf746c)

**OS/device including version:**
Windows 10

**Issue description:**
Tween on_Tween_all_completed() stops being called if the tween is stopped and then started again.  on_tween_completed() still gets called, however.  Possibly related to: [#35441](https://github.com/godotengine/godot/issues/35441)

**Steps to reproduce:**

- call stop_all() or stop() on a running tween.  
- start the tween again. 
- on_Tween_all_completed() won't be called when the tween naturally stops

**Minimal reproduction project:**
https://github.com/haplotypegames/Godot_Tween_Testing

**Comment by leodimano** [comment]
Hello @haplotypegames I don't think this is an issue, I've suffered this too and after debugging the tween node, every time you call InterpolateProperty it will add new "track" to the tween so when you call Start() it will start all the tracks that hasn't been started, if at the middle of the track you call Stop() or StopAll() you're interrupting the track execution, so, you need to call Resume() or ResumeAll() to correctly wrap the track and the signal will be fired. 

For instance
a.
Call InterpolateProperty()
Call Start()
"The tween will do the interpolation and fire the event once the track if over"

b.
Call InterpolateProperty()
Call Start()
Call StopAll()
Call InterpolateProperty()
Call Start()
"The tween will stop the first interpolation but will not consider that the track is completed, then we add a new track to the tween and call Start() again, the second interpolation will finish and fire the signal 'tween_completed' but the signal 'tween_all_completed' won't be fired since the first interpolation is halted"

**Comment by haplotypegames** [comment]
Thanks for your response.  I suffered this in nodes where I was interpolating some oscillations.  It looks like incorrect implementation on my part.

**Comment by haplotypegames** [comment]
Incorrect implementation on my part.  Node is working correctly.
