### ISSUE TITLE
Mismatch between Distance Fade properties and their documentation

### ISSUE THREAD

**Issue by Matceporial** [godotengine/godot#36051]
In the documentation, it states:

    float distance_fade_max_distance

Distance at which the object fades fully and is no longer visible.

    float distance_fade_min_distance

Distance at which the object starts to fade. If the object is less than this distance away it will appear normal.

In reality, it's the other way around. The object is invisible at min and fully visible at max.

**Comment by Calinou** [comment]
> In reality, it's the other way around. The object is invisible at min and fully visible at max.

This is only the case if the min distance is greater than the max distance (or the other way around, I don't remember).

**Comment by clayjohn** [comment]
By default the object will dispensary when less than ``min_distance`` away and will be fully opaque when greater than ``max_distance`` away. You can indeed reverse the logic by making ``min_distance`` greater than ``max_distance``

**Comment by githubjsl118** [comment]
A potential fix would be to change on line 904 and line 933 of /scene/resources/material.cpp, reversing the min and max parameters on the function call to smoothstep

i.e 

smoothstep(distance_fade_min,distance_fade_max, ...) to smoothstep(distance_fade_max,distance_fade_min, ...)

Namely through blackbox testing have determined this will indeed make the program behave consistently with the code documentation.



HOWEVER, maybe we should just leave the code as is and just change the documentation that OP has shown us?  Because users may have already designed their games around the current behavior, furthermore:


On the docs for the user-side: 
https://docs.godotengine.org/en/latest/tutorials/3d/spatial_material.html

under the section "Proximity and distance fade", the description of the distance fade, ("Distance fade is useful for light shafts or indicators that are only present after a given distance"), along with the gif animation provided seems to suggest that the current behavior (object invisible at min distance away and fully visible at max distance away) is the expected behavior.

**Comment by clayjohn** [comment]
@githubjsl118 yes. This issue is tagged as "documentation" because the documentation needs to be updated to match the code.

**Comment by jabcross** [comment]
It's just a matter of describing the behavior if the values are reversed, right?

**Comment by clayjohn** [comment]
@jabcross and correcting the current descriptions.
