### ISSUE TITLE
(Godot 3.2 Windows) GPU Imploded after toggling settings

### ISSUE THREAD

**Issue by daimeng** [godotengine/godot#36129]
**Godot version:**
3.2 (not mono)
**OS/device including version:**
Windows 10, Nvidia GTX 760, GLES 3
**Issue description:**
GPU disabled error code 43
**Steps to reproduce:**
UPDATE: If you do not see a ball in the game, try to play with the invert color and hdr filters on the ball.png asset Import. I also played around with those before the crash.
Click around in display settings, toggling vsync off and back on, also flipped pixel perfect on and off. click the "restart to see changes".
**Minimal reproduction project:**
https://github.com/daimeng/pong-gd

Honestly not sure where to post about this.
I also posted here: https://godotengine.org/qa/61085/something-in-godot-settings-borked-my-gpu
The eventviewer logs are pasted there.

EDIT:
Come on guys, at least try to run the game and let me know what happens. Read the full thread carefully before dismissing as "not a godot problem".

**Comment by clayjohn** [comment]
Can you reproduce this reliably? If so, please provide clear instructions on how other users can reproduce the same issue. 

Also, please make sure your GPU driver is up to date.

**Comment by daimeng** [comment]
My GPU driver version is Jan 29 2020. I've tried other versions, completely uninstalling all nvidia, reinstalling, etc.

I can't exactly attempt to reproduce it because my GPU is not functioning anymore. But it definitely happened twice.

I updated post with the project.

**Comment by clayjohn** [comment]
> I can't exactly attempt to reproduce it because my GPU is not functioning anymore. But it definitely happened twice.

Ah. :/ that is a problem. I was going to say that, based on the two errors you linked, your GPU may be dying. The concerning fact is that you got different errors each time. That makes it look like the GPU is having random issues before dying. 

Please update if you can get your GPU up and running again and if you can reproduce the error. Otherwise RIP your GPU :(

**Comment by gamedevsam** [comment]
Don't think this has anything to do with godot...

**Comment by avril-gh** [comment]
@daimeng 

> (...) your GPU may be dying. The concerning fact is that you got different errors each time (...)

how about entirely removing graphic card from socket and inserting it back.
(could also exploit the chance and clean everything from dust)

> Don't think this has anything to do with godot...

either me

**Comment by daimeng** [comment]
Look, I know the instinct for everyone is to say this has nothing to do with Godot, because it sounds like a windows support ticket. And it might not be, it might be something OpenGL / Windows 10 related.

But the chances of it being my card "randomly dying" are not high either. I've had no graphical issues or artifacts prior.
The error clearly happened due to Godot attempting to reopen / open after the settings changes. I can see if I can fish out more crash logs.

At this point I realize fixing my GPU has nothing to do with godot (I'll be trying a bios flash and then maybe taking the card out, reinstalling windows etc).
But the trigger clearly was Godot (or something lower level used by it). Please test my game and let me know what happens! (if you are willing to, I don't expect it to be reproduceable, but on the 0.001% chance).

**Comment by elmartirta** [comment]
I tried to reproduce the issue, by downloading the project, disabling the `Use VSync` option in Project Settings, running the game, turning on VSync, and running the game again. Both times, the game loaded, and I was able to run around with a dinosaur and chase the little white guys on the screen. I did the same with the setting `Per Pixel Transparency: Allowed`, and `Per Pixel Transparency: Enabled`, and the game loaded just fine.

I'm pretty sure this issue is limited to your hardware and setup, and doesn't have anything to do with Godot. Try running it on your MacBook and see if you can find a specific setting to reproduce the issue. 

Otherwise, it's best to close this issue as one that's non-reproducible.

**OS/device including version:**
Using a Windows 10 computer, running a NVIDIA GeForce GT 730M, on Godot version 3,2,stable.official,

**Issues Reproduced**
No issues reproduced

**Reproduction Steps**
Disabled the setting `Use VSync` in the Display -> Window category of Project Settings.
Restarted Godot.
Ran game without any issue. Blocked little running dudes with my dinosaur in the game.
Enabled the setting `Use VSync` in the Display -> Window category of Project Settings
Restarted Godot.
Ran game without any issue. Blocked little running dudes with my dinosaur in the game.

Repeated steps with the `Per Pixel Transparency: Allowed` setting
Repeated steps with the `Per Pixel Transparency: Enabled` setting
Game ran without issues each time.

**Minimal reproduction project:**
https://github.com/daimeng/pong-gd

**Comment by daimeng** [comment]
Thanks for testing!
Wait, was there no ball in the scene? There should be a fireball thing bouncing around.
I remember another thing I was playing around with were the invert colors and HDR filters in the ball.png Asset Import tab.
If there is no ball rendering, this could confirm there is something funky going on, and perhaps your card just handled it better.

**Comment by Calinou** [comment]
I tested the reproduction project on Godot 3.2.1 and couldn't reproduce this issue either. I can see the red ball and no error messages appear in the console (even when tapping it by pressing <kbd>Space</kbd>). I'll close this issue as nobody else has been able to reproduce it. Sorry for your GPU loss anyway :slightly_frowning_face: 

![image](https://user-images.githubusercontent.com/180032/78510212-07538280-7794-11ea-8c16-622ab059f1b9.png)

> Note, I also have "Visible colliders" turned on while developing, not sure if that's saved as part of the project.

Settings from the Debug menu at the top of the editor aren't saved into `project.godot`. This means they're not stored in version control.
