### ISSUE TITLE
Vulkan: Broken splash screen display

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#36123]
**Godot version:**
Godot 4 hash 8c73e81

**OS/device including version:**
Win10 64 bit; Nvidia GTX 1060 with latest studio drivers; Ryzen 2700X CPU; 32 gigs RAM.

**Issue description:**
The splash screen displays as black with a large white rectangle in the center (not the Godot Engine logo or the custom splash image).

**Steps to reproduce:**
Open a project, any project, and take a look at should be the splash screen as the editor is opened.

**Minimal reproduction project:**
[Vulkan_Testing.zip](https://github.com/godotengine/godot/files/4189251/Vulkan_Testing.zip)

**Comment by KoBeWi** [comment]
Still valid in 2cbc0b6

**Comment by Anutrix** [comment]
I ran a debug build on master 0c23a2cfe3ad897e1e49008629c135764b2c155c and also in beta2. 
This can be considered partially fixed, since after few seconds on white screen, the splash screen was seen for few seconds.
So splash screen works now but it's just slow.

OS: Window 11 Pro 22H2 64 bit
CPU: AMD Ryzen 9 5900X
GPU: AMD RX 570(4GB version)
RAM: 32 GB

**Comment by KoBeWi** [comment]
Yep, the splash displays, but the white window looks rather bad. It shouldn't show window at all until it loads.

**Comment by clayjohn** [comment]
Fixed by https://github.com/godotengine/godot/pull/71289
