### ISSUE TITLE
Connections to method window doesn't expand to fit the text

### ISSUE THREAD

**Issue by Feniks-Gaming** [godotengine/godot#36245]
**Godot version:**

3.2

**OS/device including version:**

Win 10 

**Issue description:**

New 3.2 Connections to method button is great addition to the engine and I enjoy it a lot but it has one small limitation that it doesn't dynamically scale to a text inside the window reducing it usability.

**Steps to reproduce:**

Connect new signal to script and click on Connections to method button observe window being to small

**Minimal reproduction project:**

[Bug.zip](https://github.com/godotengine/godot/files/4208547/Bug.zip)

**Comment by KoBeWi** [comment]
Here's a screenshot for reference:
![image](https://user-images.githubusercontent.com/2223172/74590429-8cc97a80-500e-11ea-97cb-5a5b8cadd2a2.png)
Source and signal names are truncated, because the dialog is too small. Not sure if making it dynamically-sized is a simple task, but making it bigger could be enough too.
