### ISSUE TITLE
Typos in method/constant names

### ISSUE THREAD

**Issue by lordadamson** [godotengine/godot#3626]
![screenshot from 2016-02-07 20-09-32](https://cloud.githubusercontent.com/assets/6195060/12874671/bff472f2-cde0-11e5-8808-fe1608720e5c.png)
Here I suppose it means SUBTRACT instead?

![screenshot from 2016-02-07 21-08-42](https://cloud.githubusercontent.com/assets/6195060/12874673/d01a56ce-cde0-11e5-90cc-ae8c8df307f1.png)
get_video_texture* ?

I was fixing typos but feared that changing those is not a good idea so I made an issue instead.

**Comment by akien-mga** [comment]
Nice catch :) I was dead convinced that "substract" is correct, but actually it's the ancient form of "subtract" :D
``get_video_texutre`` should indeed be ``get_video_texture``.

You can't fix those directly in classes.xml, they need to be fixed in the source code, and then the doc file regenerated with ``-doctool``. It will break the API, but at least for ``get_video_texutre`` I think it's fine, if anyone had been using it, they would have reported the typo :p

**Comment by lordadamson** [comment]
I think I'll try to get into the code and try to fix it :D
as for the 'substract' are you saying that it should remain unchanged?

**Comment by akien-mga** [comment]
>  as for the 'substract' are you saying that it should remain unchanged?

I think it could be fixed too, unless @reduz objects to it as it would break compatibility for users that rely on ``KEY_KP_SUBSTRACT``. It's still quite easy for them to check the Global Scope and find the new name :)

**Comment by vnen** [comment]
At least `KEY_KB_SUBTRACT` can be added as an alias and the typo be marked as deprecated to be removed in the next version.
