### ISSUE TITLE
Dictionary has has has!

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3629]
I want to check that a json/dictionary has all keys I need so my funktion can work properly.

Right now I have to do this
```if (body_map.has("id") && body_map.has("url") && ...):```
Is there another way?

How about a second has function. hasn( args )
```if ( body_map.hasn("id", "url") ):```
Maybe it is too rare so godot doesn't have to provide it?

Another way would be to use try/catch.
I've seen that someone suggested try/catch to be implemented in GD but I don't like try/catch stuff.

I can write my own function in GD for now...
```
func has(map, args):
	for arg in args:
		if( !map.has(arg) ):
			return false
	return true
```

**Comment by bojidar-bg** [comment]
I would suggest `Dictionary::has_all(StringArray args)`

**Comment by akien-mga** [comment]
I'm not convinced that this would be a useful addition, as shown above it's pretty easy to write one's own function for that, and I would image that in such a use case most users might want to actually print debug info about the missing keys, instead of just plainly returning false if any key is missing.

If it were implemented, it could likely be `Dictionary::has(StringArray keys)` directly.

**Comment by bojidar-bg** [comment]
@AlexHolly BTW, as a workaround, you might make classes for most of those things:
````
class RequestData:
  var url = "localhost"
  #...
func make_request(data):
  if data extends RequestData:
    data.url....
````

**Comment by AlexHolly** [comment]
It is easy to implement in gd but I need it in a few projects. I have to add it in each project( a script with this method or copy and paste )
