### ISSUE TITLE
Godot application does not show up in taskbar on Linux Mint

### ISSUE THREAD

**Issue by oxben** [godotengine/godot#3631]
When running Godot on Linux Mint 17.3 (Cinnamon desktop), the application doesn't show up in the taskbar. No entry is added for Godot.
This means that if the window is minimized, it cannot be made visible again via the taskbar, which is a bit annoying.

- Bug seen with Godot 2.0-beta.

Maybe there are some hints missing when creating the X11 window, so Cinnamon's taskbar doesn't consider the window for showing it up there.

I cannot confirm if the bug also exists in other Linux distributions or with other desktop environments (gnome, unity, kde...)

**Comment by akien-mga** [comment]
This has been brought up on the Facebook group a couple times, but not yet on this repo apparently :) See:
- https://www.facebook.com/groups/godotengine/permalink/713127188823878/
- https://www.facebook.com/groups/godotengine/permalink/722886857847911/

To sum up and not force people to use an evil social network ;), the bug seems to be https://github.com/linuxmint/Cinnamon/issues/4986 and should hopefully be fixed next time your distro updates Cinnamon.

**Comment by akien-mga** [comment]
The actual fix is https://github.com/linuxmint/Cinnamon/pull/5022 if you want to backport it for yourself, or notify your distro and ask them for a bugfix update.

**Comment by oxben** [comment]
I indeed avoid "evil social networks" :-).
Thanks for pointing me to the fix.

**Comment by bojidar-bg** [comment]
BTW, I can confirm it works just fine on KDE plasma.
