### ISSUE TITLE
reset button next in Path2D "curve" property not working.

### ISSUE THREAD

**Issue by shafnaz** [godotengine/godot#36372]
**Godot version:**
3.2
**OS/device including version:**
Windows 10
**Issue description:**
The  reset button does not reset to an empty curve. (See .gif animation)
![godot path2D](https://user-images.githubusercontent.com/37254287/74875532-32e3f000-5341-11ea-9d96-f17bb2d95ddd.gif)

**Steps to reproduce:**
1. Create "Path2D" node.
2. Draw your curve.
3.  Now press the reset button. Curve disappears, but when you now draw a new curve, the reset button is also gone.
4. If you select "New Curve2D" from the dropdown, and then reset, it will default to the previous curve you had drawn.
**Minimal reproduction project:**
-

**Comment by simpuid** [comment]
Same kind of bug is present in spatial path.
It can be fixed by using an empty `Ref<Curve2D>` and `Ref<Curve3D>` for `curve` property of `Path2D` and `Path` respectively.

@shafnaz If the above fix is applied then you have to assign a new `Curve2D` to `Path2D` through drop down menu before editing it or after a revert.

@KoBeWi  If that sounds good to you then I will issue a PR (already tested).

**Comment by KoBeWi** [comment]
@simpuid If you have a PR ready, just open it and someone will review whether the fix is good or not.
