### ISSUE TITLE
Add thumbnails for non-binary scene types

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#3640]
There are no thumbnails in the filesystem dock for non-binary scene files. Quickly finding scenes is much easier in grid mode with previews.

**Comment by reduz** [comment]
yeah.. they can't be saved in-file like in scn, so i guess they should be
generated outside...

**Comment by Zylann** [comment]
Maybe they should be generated at the same place where `.gd` file thumbnails are stored?

**Comment by Calinou** [comment]
> Maybe they should be generated at the same place where .gd file thumbnails are stored?
If they aren't stored anywhere, it could be in local storage or under a special folder of the project?

On Linux, `$HOME/.cache/godot` should be used (the XDG cache directory) so that it doesn't go in `$HOME/.godot` (user doesn't need to back them up).

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone. (A fix for 2.1 would be great though :P)

**Comment by hal-314** [comment]
Hi
I'm new here and I would like to start trying to fix the this issue.  It seems a easy job. 

I like the idea to generate and store the thumbnails of .tscn files in the same way than .gd files. In case that loading an big scene takes a lot of time, the thumbnail could be also generated and cached when the scene is saved (the same behavior than binary scene). 

Finally, I think that thumbnail generation for binary scene should work like the other non binary scenes format in order to give some consistency.

**Comment by akien-mga** [comment]
I think some work was done for this in the master branch. What's the current status?

**Comment by hal-314** [comment]
I tried but failed. Sorry.

**Comment by djrm** [comment]
As far as i cant tell they already have a preview, hough its only generated when doing save and run scene, that is fixed by #12852
