### ISSUE TITLE
Autocompletion doesn't work for the class name (after the "extends" keyword)

### ISSUE THREAD

**Issue by Leleat** [godotengine/godot#36431]
**Godot version:**
3.2

**OS/device including version:**
Fedora 31

**Issue description:**
The auto-complete doesn't suggest classes after the "extends" keyword. It works fine in any other place (of the same file).

**Steps to reproduce:**
Just create a new script and try to change the class.

**Minimal reproduction project:**
-

**Comment by liuhantao9** [comment]
I would like to work on it, but I don't know which file or block of code is the starting point. Can you provide some more detail or some instructions on this issue.

**Comment by eliaperantoni** [comment]
Hello! It's my first time diving into Godot source code, please be patient with me :))
It seems like this function is a good starting point:

https://github.com/godotengine/godot/blob/620030b600b375545ecab5190615e08919e56da4/modules/gdscript/gdscript_editor.cpp#L2530

I think it is called every time auto completion options for GDScript are needed.

This line in particular:

https://github.com/godotengine/godot/blob/620030b600b375545ecab5190615e08919e56da4/modules/gdscript/gdscript_editor.cpp#L2552

switches among the various types of completion. When typing the name of the class to extend, the `GDScriptLanguage::complete_code` is called but `parser.get_completion_type()` returns `GDScriptParser::COMPLETION_NONE` so that's why nothing is suggested.

I'm not 100% where to go from here though

**Comment by eliaperantoni** [comment]
`GDScriptParser::COMPLETION_TYPE_HINT` seems to be the correct type but how should we check for it?

![Istantanea_2020-02-28_18-55-10](https://user-images.githubusercontent.com/6002855/75572912-feb4b180-5a5b-11ea-95e3-8a3f3669d8cc.png)

**Comment by liuhantao9** [comment]
@eliaperantoni How do you isolate this block of code exactly? Is there a way to see the call stack?

**Comment by eliaperantoni** [comment]
@liuhantao9 You can look a the call stack while debugging using gdb but I don't understand what you mean by "isolate this block of code".

I eventually figured out that solving this bug has to do with the tokenizer. There's a global variable `completion_type` that determines what the autocompletion will suggest, `GDScriptParser::COMPLETION_TYPE_HINT` would be the correct one in this case.

 There's a bunch of functions: `parse_expression`, `parse_type`, `parse_block`, ecc.. that get called somehow and overwrite the value of `completion_type`. The global state and the fact that it's not clear how and when these functions are called made me do little progress :/

**Comment by akien-mga** [comment]
Fixed by #40598 (`master`) and #41318 (`3.2`).
