### ISSUE TITLE
Scripts should be scene identifiable

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3644]
There should be a way to tell which script belongs to which scene.
By opening a lot of scripts, after a while it gets messy what is from where.
Maybe a note at the bottom of the script window, like from objName, SceneName, or whatnot.

**Comment by nunodonato** [comment]
you can use the same script for more than one scene/node. how would you do it in these cases?

**Comment by KioriSun** [comment]
maybe when you hover over the script a tooltip pops up that gives you a list of where its being used.
Something like that.

Alternatively if it is listed at the bottom of the window, when selected for instance.
Then you could have it like: "objName, SceneName; ObjName2, SceneName2; Obj..."
With the "..." added when the list gets too big.

Another idea i had was before the script starts at a non counting line( before line 001), there could be a list of it. Like: This script is being used by/at : name, name, name. etc.

These are just ideas.
While most ides don't really have this feature, most engines are not multi scene engines.
So being able to easily keep track of you scripts, "where did i put this again?", might be useful for godot.

**Comment by reduz** [comment]
just put the same name to the script and the scene. The new script dialog
does this..

**Comment by akien-mga** [comment]
I do think that this could be a useful feature, if it's able to tell you all scenes/nodes that use this script. But I'm not sure this is technically doable; maybe using a logic similar to that of the orphan manager?

**Comment by Anutrix** [comment]
This would nice especially when you wanna delete a whole script. Finding scenes that depend would be helpful feature. Tooltips on Script Names in ScriptEditor already show their location. Something like "Dependents: SceneA, SceneB,..." along with it would be nice.

**Comment by mrcdk** [comment]
You can already see the owners and dependencies of any `Resource` (anything that shows in the FileSystem dock) by right clicking over it and selecting `Edit Dependencies...` or `View Owners...`

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
