### ISSUE TITLE
create_shape_owner API ignores the Object parameter

### ISSUE THREAD

**Issue by udit** [godotengine/godot#36528]
**Godot version:** 3.2

**OS/device including version:** Windows 10

**Issue description:** As per [`create_shape_owner(Object)` API](https://docs.godotengine.org/en/3.2/classes/class_collisionobject2d.html#class-collisionobject2d-method-create-shape-owner), it creates an owner for the provided object parameter, but it is creating an owner for the Object/node that is calling this API, completely ignoring the `Object` parameter.

**Steps to reproduce:** Write the following script in a **'Parent'** `RigidBody2D` to create shape owner for a **'Child'** `RigidBody2D`

    var own0 = create_shape_owner($Child)
	
    var shape0 = CircleShape2D.new()
    shape0.radius = 100
    $Child.shape_owner_add_shape(own0, shape0)

This will create a shape owner for `$Parent`, the node that was calling the shape owner API, instead of creating it for `$Child` that was passed as a parameter.

Code when changed to `var own0 = $Child.create_shape_owner($ANY_OBJECT_HERE)` creates shape owner for `$Child`

**Minimal reproduction project:**
[ShapeOwnerAPI.zip](https://github.com/godotengine/godot/files/4249390/ShapeOwnerAPI.zip)

**Comment by madmiraal** [comment]
Closing, because the current behaviour is correct.

`owner` is actually either a `CollisionShape` or a `CollisionPolygon` that is a child of the `CollisionObject` giving it its shape. It is simply a container (the "owner") for one or more shapes. It does not refer to the `CollisionObject` that are defined by the shapes. The `owner_id` returned is the index of the "container" (the `CollisionShape` or `CollisionPolygon`) in the sub-list of children of the `CollisionObject` that give it its shape. It is local to the `CollisionObject`.

All the `shape_owner_*` functions apply to the `CollisionObject` from which they are called. Therefore, the new `owner_id` returned by `create_shape_owner()` will always be associated with the `CollisionObject` from which it was called. Similarly, `$Child.create_shape_owner()` will always create a container for the `$Child`. The object passed to the `create_shape_owner()` function, should be a pre-existing `CollisionShape` or `CollisionPolygon`. It is only ever used when calling `shape_owner_get_owner()` to retrieve the `CollisionShape` or `CollisionPolygon` that contains the `Shape`s associated with it.
