### ISSUE TITLE
Navigation leaks when closing editor

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#36537]
**Godot version:**
Master (dace1ec)

**OS/device including version:**
Any

**Issue description:**
When closing the editor, those errors are reported (among others):
```
ERROR: 4 RID allocations of type 'P8RvoAgent' were leaked at exit.
ERROR: 2 RID allocations of type 'P9NavRegion' were leaked at exit.
ERROR: 2 RID allocations of type 'P6NavMap' were leaked at exit.
```

CC @AndreaCatania 

**Steps to reproduce:**
- Open and close editor, check console

**Comment by dreamsComeTrue** [comment]
The problem is in gd_navigation_server.cpp and its 'command' pattern.
'free' method is also being considered as a command, so it's not executed directly, but - within 'step' method.
Unfortunatelly, NavigationServer is NOT enabled by default in Editor, thus why that 'step' method is omitted and 'free' never gets called.

```c++
void GdNavigationServer::step(real_t p_delta_time) {
	if (!active) {
		return;
	}
.....
	for (size_t i(0); i < commands.size(); i++) {
		commands[i]->exec(this);
		memdelete(commands[i]);
......
}
```
When I simply switched NavigationServer as enabled by default (in EditorNode constructor):

```c++
NavigationServer::get_singleton()->set_active(TRUE_SET_HERE); // no nav by default if editor
```

then everything works fine, and there are no memory leaks.

So there are two solutions:
- this server is enabled by default
- 'free' method must be taken from that Command pattern, and allowed to be called directly, no deferred...

**Comment by dreamsComeTrue** [comment]
One additional out-of-the-curiousity question: apart of 'thirdparty' libraries, modules\gdnavigation is the only one part in whole engine which uses:

```c++
#include <vector>
and
#include <algorithm>
```
instead of relying on Godot's data-structures. Is there any particular rationale for that choice? :)

**Comment by AndreaCatania** [comment]
@dreamsComeTrue Thanks for have looking at this!

Regarding the std vector, it's used there because there I don't need all the functionalities that the godot `Vector` has (like COW) or doesn't have like smart internal allocation.

For this specific use case, the `std::vector` is a better choice.

**Comment by dreamsComeTrue** [comment]
Ok, thanks, I wasn't sure if using STL is even allowed in godot's codebase, that's why I asked :)

**Comment by AndreaCatania** [comment]
It's not, but the servers have some exception.
