### ISSUE TITLE
Adding rectangular holes to NavigationPolygonInstance trough code does not work

### ISSUE THREAD

**Issue by lszl84** [godotengine/godot#36555]
**Godot version:** 3.2 stable

**OS/device including version:** macOS 10.15.2

**Issue description:** Trying to setup rectangular navigation polygon with smaller rectangular hole inside. If I comment out adding either inner or outer outline, the code works, but with two outlines it produces empty polygon list in the navpoly (see code).

**Steps to reproduce:** See code

**Minimal reproduction project:**

Node2D.tscn:
```
[gd_scene load_steps=3 format=2]

[ext_resource path="res://Node2D.gd" type="Script" id=1]

[sub_resource type="NavigationPolygon" id=1]

[node name="Node2D" type="Node2D"]
script = ExtResource( 1 )

[node name="Navigation2D" type="Navigation2D" parent="."]

[node name="NavigationPolygonInstance" type="NavigationPolygonInstance" parent="Navigation2D"]
navpoly = SubResource( 1 )
```

Node2D.gd:
```
extends Node2D

func polygon_from_box(rect):
	return PoolVector2Array([Vector2(rect.position.x, rect.position.y), Vector2(rect.end.x, rect.position.y), Vector2(rect.end.x, rect.end.y), Vector2(rect.position.x, rect.end.y), Vector2(rect.position.x, rect.position.y)])

	
func generate_navpoly():

	var inner = Rect2(Vector2(0,0), Vector2(300, 300))
	var outer = inner.grow(200)
	
	var polygon = NavigationPolygon.new()

	polygon.add_outline(polygon_from_box(outer))
	polygon.add_outline(polygon_from_box(inner))

	polygon.make_polygons_from_outlines()
	$Navigation2D/NavigationPolygonInstance.navpoly = polygon
	
	
func _ready():
	
	generate_navpoly()
	print($Navigation2D/NavigationPolygonInstance.navpoly.get_polygon_count()) 
```

**Comment by Xrayez** [comment]
@lszl84 I managed to fix the issue in your example (btw, you can simply drag-n-drop projects here for easier reproduction)

```gdscript
extends Node2D

func polygon_from_box(rect):
	return PoolVector2Array([
		Vector2(rect.position.x, rect.position.y), Vector2(rect.end.x, rect.position.y), 
		Vector2(rect.end.x, rect.end.y), Vector2(rect.position.x, rect.end.y)])

	
func generate_navpoly():
	var inner = Rect2(Vector2(0,0), Vector2(100, 100))
	var outer = inner.grow(100)
	
	var polygon = NavigationPolygon.new()
	
	var rect_outer = polygon_from_box(outer)
	
	var rect_inner = polygon_from_box(inner)
	var ofs = Transform2D(0.0, Vector2(50, 50))
	rect_inner = ofs.xform(rect_inner)

	polygon.add_outline(rect_outer)
	polygon.add_outline(rect_inner)

	polygon.make_polygons_from_outlines()
	$Navigation2D/NavigationPolygonInstance.navpoly = polygon
	
	
func _ready():
	generate_navpoly()
	print($Navigation2D/NavigationPolygonInstance.navpoly.get_polygon_count()) 
```

[nav-poly-rect-holes.zip](https://github.com/godotengine/godot/files/4255708/nav-poly-rect-holes.zip)

`polygon_from_box` returned 5 points with duplicate starting and ending vertex (no need to finish up the rect, only 4 points is required)

Some other unrelated errors popped up, had to clear initial `NavigationPolygon` from the scene.

Godot 4.0 will have a complete overhaul for navigation code so likely this is going to be outdated. But I'd like to chime in and link my PR regarding adding holes support on geometry level since the navigation code used for cutting out holes might not be there anymore in 4.0: #35706.

**Comment by lszl84** [comment]
Thank you, this fixes the problem 👍
