### ISSUE TITLE
Unable to run environment shaders in child viewport

### ISSUE THREAD

**Issue by Jimmio92** [godotengine/godot#36615]
**Godot version:**
Godot 3.2 release
**OS/device including version:**
AMD Ryzen 7 3800X 8c/16t CPU @ 3.90GHz, 32GB DDR4 @ 3200MHz on X570 chipset
Windows 10 Pro 1903 (build 18362.657)
**Issue description:**
I have a world set up where I'm drawing the backdrop, then drawing two viewport textures on top using TextureRect: one displaying the game world, and one displaying always-above things, like the player's gun in a first person shooter.

I am unable to get the "game world" viewport to use the environment it is provided, aside from Ambient, Sky, and Fog. The others do not respond; as if disabled.
**Minimal reproduction project:**
Attached is a minimal reproduction project. There's an insanely overbright environment (Glow shader) set in the interior viewport, and it's not at all displayed.
[NestedWorldBug.zip](https://github.com/godotengine/godot/files/4264058/NestedWorldBug.zip)

This is currently a blocking issue in my project, and if anybody could help me workaround this for the time being, I'd greatly appreciate it.

Thanks.

**Comment by clayjohn** [comment]
I have opened your provided example but I am unclear what you are trying to do. 

Right off the bat, you seem to misunderstand what a World environment does. In two cases you are using a WorldEnvironment as the root for spatial objects (including the root of your scene). But also in your viewport you have it set to use a custom world (which is empty) and you also have a world assigned through a WorldEnvironment node. 

The World you have assigned directly to the viewport is overriding the one you have in the scene tree which is why you aren't seeing the effects you want. Further, certain effects are disabled when ``Transparent Bg`` is turned on.

In order to get your post-processing effects to apply, you need to remove the world you have set in your Viewports ``World`` property. And potentially turn off ``Transparent Bg``.

In the future, please ask these types of question on the [community channels](http://docs.godotengine.org/en/latest/community/channels.html) before filing a bug report. Going through reports is very time consuming for devs and it takes time away from working on the engine itself.

**Comment by Jimmio92** [comment]
I've switched every possible option I could find and have been unable to get it to work, including setting a world, setting that world's environment, adding WorldEnvironment, moving it around, parenting, etc. Hours of research what others did.. just trying to get it to display.

I also did ask about it in the community Discord, but I guess no one was knowledgeable in this stuff when I asked so I went as far as to post a bug report which I will refrain from doing in the future. I'm sorry for the trouble.

You did however fix my problem by disabling Transparent Bg. The tooltip says it's whether the background is transparent. I incorrectly assumed this meant I wanted the background of the viewport's render image to be transparent... so I could overlay it. I guess that's for some other feature that just so happens to have the same name... So still sort of a bug report, but for documentation. Maybe that's a feature for root viewports, so the window border can be alpha scissored or what have you and I just misused it.

Anyway, thanks.
