### ISSUE TITLE
Shape key dont work on GLES2

### ISSUE THREAD

**Issue by bosman697** [godotengine/godot#36612]
**Godot version:*Godot_v3.2-rc2_win64*

**OS/device including version:*windows 8*

Shape keys don't work on GLES2 , they work  in GLES3.

**Comment by clayjohn** [comment]
Looks like they aren't supported in GLES https://github.com/godotengine/godot/issues/25697#issuecomment-468774787

Are you getting an error when you try to use them?

Also please include more information in your bug report, please see the [contributing guidelines](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md)

**Comment by bosman697** [comment]
Are you getting an error when you try to use them?
only in console
![obraz](https://user-images.githubusercontent.com/43348149/75478569-7d4b1980-599e-11ea-8693-b12e663e6e35.png)

**Comment by clayjohn** [comment]
That message is letting you know that belnd shapes are not supported when using the GLES2 backend. In order to use them, you must use GLES3. As far as I know, adding blend shapes to GLES2 is not planned. It may even be impossible. 

Also, please see the document "Differences between GLES2 and GLES3" particularly the [section on blend shapes](https://docs.godotengine.org/en/latest/tutorials/misc/gles2_gles3_differences.html#blend-shapes)
