### ISSUE TITLE
Exporting Template not showing up

### ISSUE THREAD

**Issue by Quique1222** [godotengine/godot#36735]
**Godot version:**
3.2
**OS/device including version:**
Windows 10
**Issue description:**
I have imported the export template from the Godot website and the templates/export options arent appearing in the export tab.[ Images](https://imgur.com/a/1rDgan2)

![Fysrhfn](https://user-images.githubusercontent.com/8281454/75710598-321b6880-5d08-11ea-8602-9f370671cf3b.png)
![le9WRJc](https://user-images.githubusercontent.com/8281454/75710603-347dc280-5d08-11ea-9af0-b5e85804a92b.png)

**Steps to reproduce:**
1. Import Godot_v3.2-stable_export_templates.tpz
2. Go to Export tab.
**Minimal reproduction project:**
[Its a new created project with a scene, cant export.](https://www.mediafire.com/file/tke7zupun4a4b7x/Test.rar/file)

**Comment by volzhs** [comment]
did you click "Add..." button?

**Comment by Quique1222** [comment]
> did you click "Add..." button?

I tryed to export yesterday and when you import a export template isnt necesary to click "add" button because you dont need to create a new one, its a template with already created ones.

**Comment by Calinou** [comment]
@Quique1222 The Export dialog displays the export *presets* you've created, not the export templates you've installed. You need to click the **Add…** button to be able to export a project.

**Comment by volzhs** [comment]
![export](https://user-images.githubusercontent.com/8281454/75714643-72321980-5d0f-11ea-87c5-568773ba61f3.gif)

**Comment by Xrayez** [comment]
Should it have default presets populated for each platform on installing templates from within editor? I recall going through similar thinking process when preset-based workflow was first introduced in 3.0 or so, but eventually I managed to figure this out, because I had to compile my own export templates due to having C++ modules.

**Comment by Quique1222** [comment]
@volzhs Well, i think that with Add... button you are CREATING a new exporting config, but i downloaded a template that should add a pre configurated export options.

**Comment by akien-mga** [comment]
It's a confusion due to the name "Export Templates", but those are not configuration files, they're binaries of the Godot engine for each target platform.

It's independent and separate from "Export Presets", which are the configuration that you do for each project and the platforms you want to export to. Presets differ by projects as the configuration often differs too. You can also have several presets for a given platform in a given project (e.g. Android armv7 and Android arm64v8, or Windows Demo and Windows Premium).
