### ISSUE TITLE
GLES2 WebGL depth texture not draw

### ISSUE THREAD

**Issue by danilw** [godotengine/godot#36786]
**Godot version:**
3.2 stable

**OS/device including version:**
Chrome 78 /Firefox 70, Linux and Windows

**Issue description:**
GLES2 Depth texture not work when it supported by device/hardware(webbrowser)

Docs https://docs.godotengine.org/en/3.2/tutorials/misc/gles2_gles3_differences.html :
>>While GLES2 supports DEPTH_TEXTURE in shaders, it may not work on some old hardware (especially mobile).

it means Godot do check if device support Depth, and use it when supported.
I have support depth texture in GLES2 in webbrowser, Godot do not use it.
**Webgl does Depth support** https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_depth_texture

**Steps to reproduce:**
1. open this [link example](https://danilw.github.io/godot-utils-and-other/bug_depth/gles2_depth.html) project in browser, depth not draw
2. open webbrowser console write 
```
var canvas = document.createElement('canvas');var gl = canvas.getContext("webgl");console.log(gl.getSupportedExtensions());
```
WEBGL_depth_texture listed

![1](https://user-images.githubusercontent.com/24825887/75874412-ae09d380-5e22-11ea-85c4-da438a928a6a.png)

**Minimal reproduction project:**
source zip [link](https://danilw.github.io/godot-utils-and-other/bug_depth/gles2_depth.zip)

**Comment by akien-mga** [comment]
>  Web

Please provide details about the OS and browser(s).

**Comment by danilw** [comment]
> > Web
> 
> Please provide details about the OS and browser(s).

Chrome 78 /Firefox 70, only Linux

**Comment by Calinou** [comment]
@danilw Which graphics card and driver are you using?

**Comment by danilw** [comment]
look my screenshot please

**Comment by clayjohn** [comment]
This is expected behaviour. Take a look at the error you get when running the scene you provided:
```
GL ERROR :GL_INVALID_OPERATION : glDrawElements: Source and destination textures of the draw are the same.
```
Certain hardware (and platforms, including webgl) do not support reading from a bound depth texture. The ``WEBGL_depth_texture`` extension means your hardware supports _using_ the depth texture. It says nothing about reading and writing at the same time. 

That note in the docs is particularly pointing to this situation. Godot allows you to read from the depth_texture, however, your hardware (in this case platform) just doesn't support it. The only way to "fix" this would be to go back to the previous hardware and not allow anyone to use the depth_texture in shaders because it cannot be supported on all hardware and platforms.

**Comment by danilw** [comment]
okey I see, thanks for clarification
can be closed I think
