### ISSUE TITLE
Custom editor shortcuts get corrupted

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#36839]
**Godot version:**
da05ca6

**Issue description:**
When you open the editor, the shortcuts you have assigned stop working. They appear as empty strings in the settings panel and upon inspecting the `editor_settings-4.tres` you can see that the shortcuts exist, but are empty (scancodes are removed; but interestingly the modifiers remain).
![image](https://user-images.githubusercontent.com/2223172/76031675-78570e80-5f38-11ea-99bf-fd93205d5499.png)

**Comment by Calinou** [comment]
I can reproduce this on commit https://github.com/godotengine/godot/commit/0c53f1f7db70d398e5d1127d35a7f0308ef92bb9 (specifically after rebinding the freelook keys to be AZERTY-friendly).

**Comment by akien-mga** [comment]
Possibly related to #18020, CC @bruvzg.

**Comment by bruvzg** [comment]
I can't reproduce it with current master, at least with newly assigned shortcuts. But shortcuts assigned before #18020 was merged will be invalid since `scancode` was renamed to `keycode`.

**Comment by KoBeWi** [comment]
Uh, I'm constantly switching between pre-Vulkan and master, so this is a problem for me .-.

**Comment by akien-mga** [comment]
Pre-Vulkan master branch is almost the same as the 3.2 branch, so I'd advise using that instead if you need a usable version. I don't think it makes much sense to add some compatibility glue for bindings made with `4.0.dev` before #18020, as these older revisions will quickly be obsolete.

There's no (direct) concern in the 3.x to 4.0 migration since they use different editor settings files.

**Comment by KoBeWi** [comment]
So this can be closed I guess.
I'm using pre-Vulkan mostly for #35704.
