### ISSUE TITLE
some GDScript keywords are not reserved

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#36878]
**Godot version:** 3.2

**OS/device including version:** Any

**Issue description:**
I can use `signal` `static` `tool`  `onready` ... (keywords) as identifier for variable assignment but for `extends` `preload` `PI` ... it's an error according to `GDScriptTokenizer::is_token_literal()`. I think we need to make these keywords reserved (unlike Fortrain). Also using built in function as variable name is an error `min`, `sin`, ... (not sure if that was intended)

when I try to `print(static)` without `var static = 3` the error message was 
`the identifier "static" isn't declared in the current scope`

![var-identifier-bug](https://user-images.githubusercontent.com/41085900/76140295-e0b00800-607e-11ea-9675-a15caf655e40.JPG)

**Steps to reproduce:**
N/A
**Minimal reproduction project:**
N/A

**Comment by BigRed-118** [comment]
The TK_BUILT_IN_FUNC could be changed to always be a literal, which would allow you to use min, etc, as variable names. I'm not certain what confusion or problematic ripple effects this would cause though. Whichever of the keywords or built in functions are allowed should have their color in the script changed from red to white though, so it's clear they're variables and not keywords. Also the autocomplete would have to changed to pick up the built in function name as a local variable instead of a function.

**Comment by ThakeeNathees** [comment]
Closing: Fixed in GDScript 2.0
