### ISSUE TITLE
key scancodes returning unknown on android

### ISSUE THREAD

**Issue by hk-32** [godotengine/godot#36991]
**Godot version:**
3.2.1 though its the same with 3.2

**OS/device including version:**
Android 9 Galaxy S8

**Issue description:**
I found the LineEdit very limited so I went ahead and tried to create my own by just doing OS.show_virtual_keyboard and then listening for _input(ev) in which I check if its a KEY event and then get its scancode which I then convert by OS.get_scancode_string(ev.scancode) which returns UNKNOWN + the only keys that actually returns something are BACKSPACE and ENTER

**Steps to reproduce:**
OS.show_virtual_keyboard(text) from somewhere.

and then:
func _input(ev):
	if ev is InputEventKey: 
		text += OS.get_scancode_string(ev.scancode)

**Comment by Calinou** [comment]
> I found the LineEdit very limited

Out of curiosity, what kind of limitations did you find in LineEdit?

**Comment by hk-32** [comment]
@Calinou just general things like not being informed if its selected. And I wanted control over the text being typed. Either way that's not the issue. The issue is that there is a bug that needs to be assessed.

**Comment by pouleyKetchoupp** [comment]
On Android, you can still use `ev.unicode` to get the text characters, so you can do something like that:

```
func _input(ev):
    if ev is InputEventKey:
        match ev.scancode:
            KEY_ENTER:
                # handle ENTER key
                pass
            KEY_BACKSPACE:
                # handle BACKSPACE key
                pass
            _:
                if ev.unicode:
                    # handle characters
                    text += char(ev.unicode)
```
Does that work for you @hk-32?

**Comment by hk-32** [comment]
@pouleyKetchoupp that does seem to work but the scancode method is still a bug that needs to be fixed I guess.

**Comment by madmiraal** [comment]
Even in Android this is not doable.

Only hardware keyboards send scan codes. For [security reasons](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#security), software keyboards are discouraged from sending [`onKey`](https://developer.android.com/reference/android/view/View.OnKeyListener) events. In fact, although they look like a keyboard, there is no need for them to even be key based; Consider swipe typing on your virtual keyboard: It's a line that doesn't even need to hit the virtual keys, only resemble the shape of the most likely word you wanted to type.

What Godot does is create a [`TextWatcher`](https://developer.android.com/reference/android/text/TextWatcher) and attaches it to an [EditText](https://developer.android.com/reference/android/widget/EditText). These are then wrapped around the Godot text editor controls like [`LineEdit`](https://docs.godotengine.org/en/stable/classes/class_lineedit.html). This gives us access to post processed software and hardware text entry. We can tell what characters were changed, hence we can simulate a [`InputEventKey`](https://docs.godotengine.org/en/stable/classes/class_inputeventkey.html) with the character's Unicode defined, but there aren't ever actually any keys being pressed, hence no scan codes. In fact, we generally send multiple [`InputEventKey`](https://docs.godotengine.org/en/stable/classes/class_inputeventkey.html)s for every new character added (see #50125), because Android generally replaces the entire line each time when using the virtual keyboard.

**Comment by hk-32** [comment]
Perfect then. It says this issue will automatically close when the PR is merged so I guess I don't need to do anything. Thanks.
