### ISSUE TITLE
Zip packing/unpacking with GDScript

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#3701]
I'm looking for a way to zip files/folders and unzip .zip files in GDScript.

**Comment by punto-** [comment]
There's no way to do this specifically from gdscript, but if you want to
access the files you can do
Globals.load_resource_pack("res://path/to/file.zip"), then open the files
in the zip as if they were part of the filesystem with load() or File, etc.
You can't unload it tho, and you can't get a list of what files were in the
zip.

**Comment by AlexHolly** [comment]
Is it not possible because it's not implementent yet or is there no way to support this for cross-platform?
Godot has some Project files from Minizip,  Minizip supports unzip...
http://www.winimage.com/zLibDll/minizip.html

**Comment by punto-** [comment]
Probably because it's not implemented as a "public" api, to be used from
gdscript. We already use it for a number of things (including loading them
as resource packs), and they're all cross platform if they use the
FileAccess class to open files.

**Comment by AlexHolly** [comment]
I also found this maybe it will help to implement a public api.https://github.com/sebastiandev/zipper

**Comment by reduz** [comment]
We have minizip already within Godot, could add a wrapper API so GDScript
can access it.

**Comment by blurymind** [comment]
I also need this feature for my app - to save a collection of resources and data to a custom file type and load it

**Comment by marcelofg55** [comment]
Just as an idea, maybe it would be cool to include libarchive (https://github.com/libarchive/libarchive) in the thirdparty dir and expose its api to GDScript? This would include support for many formats, and also fix the issue we have with setting permissions on a zip (minizip is bugged with permissions and libarchive is not).

**Comment by HeartoLazor** [comment]
¿What is the status on this?

**Comment by avencherus** [comment]
Could be handy now and again.

**Comment by HeartoLazor** [comment]
Well at least with Godot 3.0.6 I found a way to compress text and could be extrapolated to a file.
```
#Receive a text and compress it, then encode to base 64
func compress(text):
	var byte_text = text.to_ascii()
	var compressed = byte_text.compress(COMPRESSION_MODE)
	var base_64_text = Marshalls.raw_to_base64(compressed)
	return base_64_text
	
#Receive a base 64 compessed text, decode base 64 then uncompress data
func uncompress(text):
	var compressed = Marshalls.base64_to_raw(text)
	var uncompressed = compressed.decompress(UNCOMPRESSION_BUFFER_SIZE, COMPRESSION_MODE)
	return uncompressed.get_string_from_ascii()
```

I think now we need a more clear way to do this.

**Comment by avencherus** [comment]
Thanks for sharing that Hearto.   I was wondering about something similar, but considering zipping binary files.  In the end though I felt it was going to take a certain amount of tinkering and investigation that it would be considerably more time effective for me to use OS.execute() using a portable ZIP app, or running a python script.

**Comment by akien-mga** [comment]
See also #22440 for Zlib compression, which could likely be handled together with Zip archiving.

**Comment by jellehermsen** [comment]
I have created a zip file browser / decompressor in pure GDScript. It works fine if your needs are modest: [gdunzip](https://github.com/jellehermsen/gdunzip)

**Comment by sprite-1** [comment]
I would still very much like a proper open API to do this

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by anderlli0053** [comment]
So, anyone care to tell me what is the status of this? Was this accepted then?? Is it doable somehow? TO compress and uncompress ZIPs using Godot 3.4.4, using only GDScript?? Will this be as addon or part of executable??
