### ISSUE TITLE
libudev packaging problems

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#3702]
While reading through the irc backlogs I noticed this discussion (ping @punto- ):

```
<punto> can we statically link libudev.so? that one seems to not be as standard as the others
<punto> (for example it's not on the steam runtime, at least not the version that we use to build on the build server)
<Akien> punto: I have it in the steam runtime: /home/akien/.steam/steam/ubuntu12_32/steam-runtime/i386/lib/i386-linux-gnu/libudev.so.0
<Akien> punto: Don't you mean libevdev?
<Akien> punto: libevdev was dropped so shouldn't be an issue
<punto> yeah but the build server links with libudev.so.1
<punto> and package libudev0 doesn't exist anymore
<punto> could we do the same with udev? replace it with normal code?
<Akien> No idea
```

The following options came into my mind:
 - Figure out a way to add statically linked libraries to the build system. Might come in handy in the future.
 -  Add a code-path (enabled when libudev hasn't been found) that manually checks for joystick devices changes every (few) frame/s like the old code has. (`poll_joysticks()`, if you remember it ^^ )
 - Try to load the symbols at runtime (like with xinput on windows)

**Comment by punto-** [comment]
If the only thing that udev provides is notifications when devices are
connected, I like option 2. With that in place we can eventually implement
option 1 if necessary, and it's not a big deal if the engine takes a second
to realize a joystick has been plugged in.. We would have to compile
without udev by default, since the original problem was that our build
machine is linking with version 1 and steam only has version 0.. We don't
want it to fail at static linking time..
