### ISSUE TITLE
Middle click on scene tab when editor is unfocused creates new scene

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37055]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Steps to reproduce:**
1. Open a scene
2. Unfocus editor (click on task bar etc.)
3. Middle click on the scene tab
4. Instead of closing the scene, new scene gets created

**Comment by volzhs** [comment]
can't reproduce it with 3.2.1 on Linux mint 19.3

**Comment by dreamsComeTrue** [comment]
Can't reproduce either on Fedora and Ubuntu :/

**Comment by KoBeWi** [comment]
Here's a GIF
![bBYv2W8yYj](https://user-images.githubusercontent.com/2223172/76701675-8852b900-66c3-11ea-8497-cf171dfd83c2.gif)
Unfocused editor treats scene tab like empty space. Maybe it's system specific for some reason 🤔

**Comment by denormative** [comment]
Can replicate it with 3.2.1 from steam on windows 10 as well. Un-focus the window and middle click on the tab it creates a new [empty] tab. Un-focus click on the tab again; another [empty] tab. Oddly though if I am focused and middle click on the [empty] tab, it closes it; that might actually be a feature though that I've never used before. :)

I can also replicate it on OSX Catalina with 3.2.1 stable installed via brew. Had to connect my logitech mouse to it via bluetooth though. The behaviour is a little different though.

For windows if I click on any of the [empty] tabs with the window unfocused, it spawns a new tab.

On the mac, if I click on an [empty] tab, then click on the newly focused [empty] tab it closes it, then clicking on the single remaining [empty] tab it opens it again, and it continues to work while I keep clicking on the [empty] tag.

If I click on the [empty] tab, then click on the unfocused [empty] tab, it removes the [empty] tab, but if I click again it doesn't create a new one until I forcibly focus on the godot window, then unfocus.

So... yeah, bit random and weird.

**Comment by gamepad-coder** [comment]
Using Windows 10.
Godot 3.2.3

Normally, when the main Godot window is active:
middle clicking on an empty area of the projects tab bar will spawn an empty project tab. 

However, when the Godot's window is unfocused, 
this same behavior is happening no matter where you click on the projects tab bar.

Same with context menus. When Godot's window is unfocused, right clicking anywhere on the scene tabs (whether on a tab itself or on an empty area of the tab control) results in the same behavior as when a control is not found hovered under the mouse.

The bug seems to exhibit this behavior because of the code in 
`Godot_Source/editor/editor_node.cpp::EditorNode::_scene_tab_input()`.

```
void EditorNode::_scene_tab_input(const Ref<InputEvent> &p_input) {
	Ref<InputEventMouseButton> mb = p_input;

	if (mb.is_valid()) {
		if (scene_tabs->get_hovered_tab() >= 0) {
			if (mb->get_button_index() == BUTTON_MIDDLE && mb->is_pressed()) {
				_scene_tab_closed(scene_tabs->get_hovered_tab());
			}
		} else {
			if ((mb->get_button_index() == BUTTON_LEFT && mb->is_doubleclick()) || (mb->get_button_index() == BUTTON_MIDDLE && mb->is_pressed())) {
				_menu_option_confirm(FILE_NEW_SCENE, true);
			}
		}
  ...
```
When Godot's window is unfocused, then the code in `_scene_tab_input()` here is trying to get the hovered control through a pointer to a Tabs object called `scene_tabs`. It seems like the call `scene_tabs->get_hovered_tab()` is probably getting a negative value. 

Conclusion : Godot engine is probably not correctly calculating the variable `scene_tabs->hover` when the Window is inactive.

Haven't found the rest of the aspects of this bug yet. 
Just what I've found so far.

Going to read up on the process of compiling Godot + submitting pull requests sometime this month. 

Until then, if anyone else wants to go ahead and patch this, please do.
