### ISSUE TITLE
Texture button has no built-in texture resize option

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3707]
The texture button rect resizes but there is no option to auto-stretch it.
Currently I'm using this code on func _ready():
set_texture_scale(Vector2(get_rect().size.x/get_minimum_size().x, get_rect().size.y/get_minimum_size().y))

It works flawlessly as far as i've tested, but for newcomers it would be good to have this as a toggle somewhere.
Like 'stretch with rect'.
There actually is a 'stretch ratio' property, but i've no idea what its supposed to do since changing it doesnt seem to do anything...

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by alkhimey** [comment]
I have this problem in 3.0.6.

![peek 2018-12-15 20-41](https://user-images.githubusercontent.com/652603/50046282-fd42d780-00a9-11e9-9d63-10f0fdfcdd1f.gif)

Also found this question: 
https://godotengine.org/qa/9625/button-scaling

**Comment by alkhimey** [comment]
I also tried playing with Size Flags, Size and Min Size as suggested [here](https://godotengine.org/qa/13237/setting-the-size-of-a-texture-button-doesnt-work) and [here](https://www.reddit.com/r/godot/comments/8fwpl3/change_size_of_buttons_in_a_vboxcontainer/).

Nothing could change the size of the texture.

**Comment by neosin** [comment]
> I also tried playing with Size Flags, Size and Min Size as suggested [here](https://godotengine.org/qa/13237/setting-the-size-of-a-texture-button-doesnt-work) and [here](https://www.reddit.com/r/godot/comments/8fwpl3/change_size_of_buttons_in_a_vboxcontainer/).
> 
> Nothing could change the size of the texture.

Hello alkimey
I do not know if this is still an issue for you but I found a solution that works for scaling the texture within a texturebutton

make sure you have the following settings in your texturebutton
Expand: On
Stretch Mode: Scale
Size Flags
Horizontal: Fill + Expand
Vertical: Fill + Expand

This will stretch the image to fill the container of your texturebutton

**Comment by alkhimey** [comment]
@neosin Thank you fro the suggestion I did not touch Godot for some time, but I am sure others could use your solution.

**Comment by KoBeWi** [comment]
Is this stil valid? TextureButton has an `expand` option with multiple stretch modes, which will resize the texture in different ways with the `rect_size`.

@KioriSun

**Comment by LordSyd** [comment]
Seems to work ok, but for newbies it might be important to note that the anchors have to be set right, otherwise the texture won't scale automatically if you resize it's parent. Other than that, this does not seem to be an issue any more - but this topic helped me find the error with anchors beeing set wrong.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
