### ISSUE TITLE
Copy, Cut, Paste scene nodes

### ISSUE THREAD

**Issue by kirilledelman** [godotengine/godot#3720]
Copy / Cut, Paste nodes would be a tremendous time saver.

Right now I have to add my components ( sub-scenes ) and re-enter script variables in Property Editor over and over. If I could copy / paste selected node trees between scenes, I would be very happy.

I'm sure many other users miss this ability.

**Comment by nunodonato** [comment]
can't you do that with "copy params" and "set params" in the inspector? (gear icon)

**Comment by kirilledelman** [comment]
Yeah, you can, one node at a time, very painful.

**Comment by rgrams** [comment]
Can't you just put the stuff in a scene and add an instance of that instead of copy-pasting? Isn't that the point of scenes? Not that I'm disagreeing with you, copy-paste is always good.

**Comment by kubecz3k** [comment]
Basically there is already option to copy node from other scene into current one. Just "import->Node from scene". It will copy the node together with all children.

**Comment by reduz** [comment]
You know you can Ctrl+D to duplicate right? no need to add things and edit
them over and over..

**Comment by kirilledelman** [comment]
I didn't know about *Import->Node from scene*. I will certainly start using it from now on.

I thank everyone for offering workarounds. Yes, it could be done. Copy / paste params one at a time, or import a node from another scene, one at a time, then reparent, one at a time. It would, however be so much easier with simply Ctrl+C and Ctrl+V. 

Maybe there could be an "offscreen" scene loaded in memory, where selected nodes are copied? Then pasting copies them back to current scene / under selected node or root if nothing is selected?

**Comment by nanodeath** [comment]
There doesn't appear to be an `Import -> Node from scene` option anymore (v2.1.3). Is there another workaround available?

**Comment by kubecz3k** [comment]
I think this issue is obsolete now. We have 'merge from scene' option under right click as Nonodeath noted. Closing.

**Comment by nanodeath** [comment]
I'd personally still like to see an actual copy/paste function, and I'd be willing to bet that 90%+ of new users won't intuitively know what `Merge from scene` does without actually trying it, but...now that *I* now what the process is, I'm not going to press the issue.

**Comment by voithos** [comment]
+1 to copy/pasting. `Merge from scene` works, but I too had absolutely no idea what it did until reading this issue. Copy/paste is extremely intuitive, and I think it'd be great to have it - it'd certainly make Godot easier to use, and a better tool.

Can we reopen this?

**Comment by akien-mga** [comment]
Let's reopen as it's partly implemented by #13309 already, and the copy function does sound like it could be useful (cut, less so, but for consistency why not have it too).

**Comment by akien-mga** [comment]
When this gets implemented, "Merge from scene" could maybe be removed as it's quite non-intuitive and would be less convenient in the end than just opening the scene and copying its contents to paste them in another scene.

**Comment by davidawad** [comment]
I would very much like cut and paste features. The only thing I could come up with, (as a user that hasn't read the manual and am figuring it out on my own), was to copy the files in the project folder from the command line and edit the copies as independent scenes

**Comment by gerchicov-bp** [comment]
2.5years passed but still nothing works. The versions should be 0.3.x instead of 3.x if even copy-paste actions don't work

**Comment by nikolatesla20** [comment]
> 
> 
> 2.5years passed but still nothing works. The versions should be 0.3.x instead of 3.x if even copy-paste actions don't work

IMO 3.0 is "junk" too much stuff just doesn't work 

For now I stick with 2.1.4 until 3.1 is out long enough to try

**Comment by Reneator** [comment]
Sorry if these points were already said, just wanted to list my personal reasons:

If being able to copy and paste with either right-click->copy or standard hotkeys (ctrl +c etc.) would make the workflow more intuitive (instead of duplicating). The functionality could be similar to duplicating, but with hotkeys, so less dragging.

Now: right-click -> Duplicate ->drag node to the node it should be child of
new: click -> ctrl + c -> left-click on node you want it to be a child of -> ctrl + v


This could help me to refactor my projects, where i may have to move some nodes into a new scene. Right now i could copy the entire scene and then delete which i dont want to move.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by akien-mga** [comment]
For the reference, this was implemented by #34892 as of 3.3.
