### ISSUE TITLE
Enhancement wish for "Create New Node" Window

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#3734]
**Old:**
![image](https://cloud.githubusercontent.com/assets/10463138/13088386/4f58f69a-d4ec-11e5-9e64-d2b6850e7c93.png)
**New:**
![node_filter](https://cloud.githubusercontent.com/assets/10463138/13089554/87e848bc-d4f1-11e5-8a73-1daf7a08b030.png)
![control_filter](https://cloud.githubusercontent.com/assets/10463138/13089564/907924f6-d4f1-11e5-8597-46b51cd3b6c1.png)

**Filter** is type of node.
- Node = everything
- CanvasItem = all Control node + all Node2D node
- Control = all Control node

and so on..

**Favorites** and **Recent** is like "Open a Resource/File" Window.

**Comment by nunodonato** [comment]
I like the filters, somehow categorizing nodes by their type is a good way to speed up finding them and show only what makes sense. If i'm editing a 3d scene, it could default to 3d nodes, for example. if i'm in 2d, it could default to 2d.

Regarding favorites and recent... its nice, but I dont know if its useful and/or makes sense. I dont add nodes because I *like* them, but because I need them :)

**Comment by vnen** [comment]
This is an interesting idea. I like the concept of "favorites", even though @nunodonato is right about you don't have preferred nodes, it's certain that you may add many more nodes of one type and just a couple of another type. So it makes sense to have a list of nodes you're more likely to add.

**Comment by lewislepton** [comment]
oh this would be some awesome.
+1

**Comment by Sslaxx** [comment]
+1 for this one seeing as it also is a lot more space-efficient than the current (as of 2.1) design. Any opinions @reduz?

**Comment by Sslaxx** [comment]
https://twitter.com/reduzio/status/768269377347080192

**Comment by akien-mga** [comment]
Related to #5897.

**Comment by akien-mga** [comment]
Fixed by 043a7a1 \o/
