### ISSUE TITLE
Compiling for server fails

### ISSUE THREAD

**Issue by LinuxUserGD** [godotengine/godot#37342]
**Godot version:**
vulkan master (https://github.com/godotengine/godot/commit/5f1107aa30295e686be6f41cb6d17fc2cff1e036)
**OS/device including version:**
Arch Linux
**Issue description:**
compiling for server fails
**Steps to reproduce:**
```Swift
[user@archlinux ~]$ cd /run/media/user/user/git/godot
[user@archlinux godot]$ scons p=server
scons: Reading SConscript files ...
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) yes
scons: done reading SConscript files.
scons: Building targets ...
[Initial build] Compiling ==> platform/server/godot_server.cpp
In file included from platform/server/godot_server.cpp:32:
platform/server/os_server.h:41:10: fatal error: platform/x11/crash_handler_linuxbsd.h: No such file or directory
   41 | #include "platform/x11/crash_handler_linuxbsd.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [platform/server/godot_server.linuxbsd.tools.64.o] Error 1
scons: building terminated because of errors.
[user@archlinux godot]$ 
```

**Comment by akien-mga** [comment]
The server platform is obsolete and will be dropped. Now that the OS/DisplayServer split is done, we should be able to add a `--headless` switch to all platforms.

**Comment by Calinou** [comment]
@akien-mga Shouldn't we still have a build-time option for smaller libraries? Also, would a `--headless` command line argument work on server Linux where OpenGL/Vulkan libraries aren't installed and no X server is running?

**Comment by akien-mga** [comment]
@Calinou Server builds aren't significantly smaller, so it's not necessary to keep a dedicated binary. See https://downloads.tuxfamily.org/godotengine/3.2.1/ (Linux 64 28.2 MB, Headless 64 26.7 MB).

> Also, would a --headless command line option work on server Linux where OpenGL/Vulkan libraries aren't installed and no X server is running?

If OpenGL/Vulkan libraries are not installed, the rendering drivers will not be registered, so the only option would be `--rendering-driver None`.

Most likely, there'd also be a `--display-driver None` so that you can run it without X11/Wayland installed.

`--headless`, if we add it, could be sugar for `--display-driver None` (which implies `--rendering-driver None`).

**Comment by LinuxUserGD** [comment]
`--display-driver headless` and `--headless` is implemented now in the master branch (https://github.com/godotengine/godot/pull/51216)
