### ISSUE TITLE
Adding Nav pol to a tile closes godot editor

### ISSUE THREAD

**Issue by Emaleth-BSE** [godotengine/godot#37388]
Godot version: 3.1.2-stable

OS/device including version: Solus linux (latest)

Issue description: When addind navigation polygon to a tile with property navigation set to new navigation polygon editor force closes

Steps to reproduce:
1). Create tileset with at least one tile (this tile should not have navigation polygon).
2). Set "Navigation" property of that tile to new navigation polygon.
3). Add navigation polygon to that tile in tileset editor. 

Minimal reproduction project:
[GoBuTe.zip](https://github.com/godotengine/godot/files/4397840/GoBuTe.zip) < just try to add nav polygon to a tile

**Comment by Razoric480** [comment]
The editor crashes with the following errors:
```
ERROR: get_polygon: Index p_idx = 0 is out of bounds (polygons.size() = 0).
   At: scene/2d/navigation_polygon.cpp:150
ERROR: canvas_item_add_polygon: Condition "pointcount < 3" is true.
   At: servers/visual/visual_server_canvas.cpp:762
ERROR: get: FATAL: Index p_index = 0 is out of bounds (size() = 0).
   At: ./core/cowdata.h:152
```

**Comment by ThakeeNathees** [comment]
I can't reproduce it.
is it possible to set NEW navigation polygon from the Inspector?
@Emaleth-BSE  @Calinou

**Comment by Emaleth-BSE** [comment]
If you downloaded minimal project - idk. If you made one, you can access that property if you create a tilemap, add tileset to it and then click on it to change parameters.

**Comment by ThakeeNathees** [comment]
@Emaleth-BSE  sorry didn't get that.

Adding a new navigaion polygon seems to be imposible, the only way is to draw on the tile set editor, because before drawing one the inspector tab not showing any, even thought after drawing one the inspector showing the navigation property, it can't be changed.

and I found that in your minimal project/new_tileset.tres the navigaion polygon doesn't have any coordinate points, which could be happen if you add a new polygon with zero coordinates. drawing a polygon adds coordinates(with minimum of 3).

so your .tres file maybe damaged ( the coordinates weren't written ) when writing  or the new navigation polygon property in the inspector tab worked for you (which shouldn't)

![1](https://user-images.githubusercontent.com/41085900/77857333-6d7f5900-721a-11ea-8e27-eaeb61309931.JPG)

![2](https://user-images.githubusercontent.com/41085900/77857355-8425b000-721a-11ea-8dd8-8780aa55c534.JPG)

![3](https://user-images.githubusercontent.com/41085900/77857365-8c7deb00-721a-11ea-9bc7-01d99c05da90.png)

![4](https://user-images.githubusercontent.com/41085900/77857376-969fe980-721a-11ea-83c0-b79aca53b229.JPG)

**Comment by Emaleth-BSE** [comment]
Sorry about that, I'm trying to remove somehow this issue from my list...
