### ISSUE TITLE
Project/Editor settings shows empty search results

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#37424]
**Godot version:**
3.2.1

**Issue description:**
![bug](https://user-images.githubusercontent.com/3036176/77899767-b4eeff00-7285-11ea-991c-fdf21fa6969a.gif)

**Comment by bojidar-bg** [comment]
This probably occurs due to a mismatch between these two pieces of code:

https://github.com/godotengine/godot/blob/0168709978154a89f137b44f33647e5d28a46250/editor/editor_sectioned_inspector.cpp#L245-L246
https://github.com/godotengine/godot/blob/0168709978154a89f137b44f33647e5d28a46250/editor/editor_inspector.cpp#L1620-L1621

The example in the OP, "cursor", gets matched as "appli**c**ation/r**u**n/low_p**r**oce**s**s**or**_mode" by the first piece of code, but the second piece of code looks only at the last part, "low_pro**c**essor_mode" ("ursor" unmatched), and fails to match.

**Comment by Schmowser** [comment]
Hey, everyone! First contributor here :smile: I can confirm that @bojidar-bg found the correct pieces of code. There is even more to it. In OP's example, there are no results shown because:
1. "application/run/..." gets matched in edition_section_inspector but it has no settings that match.
2. "display/mouse_cursor" gets matched and there would be settings that match but it is not the selected category.

A fix should ensure these things:
- If editor_inspector matches any settings, then the category should be included in the list on the left.
- If editor_sectioned_inspector matches any category, its settings should show on the right.

Maybe, the category matcher should only focus on the first two parts of the path? I.e. For "application/run/low_processor_mode" trying to match in "application/run" only.

If no one is working on this, I could spend some time working on this as this was tagged as a junior job :)

**Comment by bojidar-bg** [comment]
I would suggest changing `editor_inspector` to match using prefixes as well.
Rationale: currently, searching for "application/run" shows all settings in the "application/run" category, as it should. But, searching for "application/run/l" suddenly shows no results, though "application/run/low_processor_mode" should match.
