### ISSUE TITLE
3D Grid Color Picker missing Alpha / Opacity setting

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#37561]
4.0 
![Anteckning 2020-04-03 225503](https://user-images.githubusercontent.com/13393087/78404233-3cc66780-75fe-11ea-9b56-db26e8c1f3d2.png)

EDIT: The same for 3.2 stable

WIndows 10

The 3D grid color picker does not have the Alpha to select, only the colors
the 2D grid has the alpha setting in its color picker

![Anteckning 2020-04-03 225253](https://user-images.githubusercontent.com/13393087/78404112-05f05180-75fe-11ea-986c-67ab9d709dc1.png)
![Anteckning 2020-04-03 225305](https://user-images.githubusercontent.com/13393087/78404121-07ba1500-75fe-11ea-8c56-dee3c8638e3a.png)

**Comment by Calinou** [comment]
This is because of a limitation that prevents drawing a transparent 3D grid. Otherwise, I'd have exposed the color's alpha component :slightly_smiling_face: 

#28289 will solve this.

**Comment by Norrox** [comment]
Cool, thank you :)

**Comment by aaronfranke** [comment]
Good idea! Yes, the grid now supports transparency with #28289 since the grid fades when zooming, so I've went ahead and removed the no-alpha property hint. It works as you would expect, feel free to [compile it](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html) and give it a try.
