### ISSUE TITLE
add_child and call_deferred("add_child", node) dont add node.

### ISSUE THREAD

**Issue by dexterslaboratory** [godotengine/godot#37594]
**Godot version:**
3.2.1
**OS/device including version:**
Mac OS 10.13.6
**Issue description:**
Can't add node.
**Steps to reproduce:**
```
extends Control
var richTextLabel = RichTextLabel.new()
var rtl = RichTextLabel.new()
func _ready():
	richTextLabel.set_name("rich")
	richTextLabel.set_use_bbcode(true) 
	richTextLabel.set_bbcode("BBCode [color=blue]blue[/color]")
	richTextLabel.set_position(Vector2(0,0))
	richTextLabel.set_visible_characters(-1)

	rtl.add_text("Hello")
	rtl.set_visible_characters(-1)
	addNodes(rtl, richTextLabel)
	
func addNodes(rtl: RichTextLabel, richTextLabel: RichTextLabel):
	self.add_child(rtl)
	self.call_deferred("add_child", richTextLabel)
```

**Comment by TheFlamyy** [comment]
I can't reproduce the issue.

I've copied the code but the nodes are clearly added as children: 
![image](https://user-images.githubusercontent.com/8056898/78469226-8a86c100-771f-11ea-921b-2ce278e4f5cb.png)

I think the problem is, that they aren't visible. That's probably because the size is (0, 0). I've manually edited the `rect_size`: 
![image](https://user-images.githubusercontent.com/8056898/78469249-b3a75180-771f-11ea-9dd4-c64b729e4ea3.png)  ![image](https://user-images.githubusercontent.com/8056898/78469264-ce79c600-771f-11ea-8ab6-a276ae99cc6a.png)

**Comment by dexterslaboratory** [comment]
Since, visible characters is set to -1 shouldn't the contents be displayed. Is there a way to set the rect_size by code in gdscript?

**Comment by Ev1lbl0w** [comment]
> Since, visible characters is set to -1 shouldn't the contents be displayed. Is there a way to set the rect_size by code in gdscript?

[Sure is](https://docs.godotengine.org/en/3.2/classes/class_control.html#class-control-property-rect-size):

```gdscript
rtl.rect_size = Vector2(100, 200)
```

**Comment by dexterslaboratory** [comment]
@Ev1lbl0w  Thanks a lot. That worked.
