### ISSUE TITLE
Using a custom RichTextEffect named "fade_in", but the built-in fade RichTextEffect is used instead.

### ISSUE THREAD

**Issue by Darenn** [godotengine/godot#37603]
**Godot version:**
Godot Engine v3.2.1.stable.official

**OS/device including version:**
Microsoft Windows 10 Pro
Version	10.0.18363 Build 18363

**Issue description:**
I wanted to create a fade_in RichTextEffect that fade-in the letters at a given speed.
@Eoin-ONeill-Yokai maybe you can help? (thanks for the classes btw!)

```
tool
extends RichTextEffect
class_name FadeInRichTextEffect

# Syntax: [fade_in speed=5][/fade_in]
# The speed argument is the number of characters fade in per second

var bbcode := "fade_in"

func _process_custom_fx(char_fx : CharFXTransform):
	var speed: int = char_fx.env.get("speed", 10)
	var character_count_to_fade_in := (speed * char_fx.elapsed_time) as float
	if char_fx.absolute_index < character_count_to_fade_in:
		char_fx.color.a = \
				clamp(character_count_to_fade_in - char_fx.absolute_index, 0, 1)
	else:
		char_fx.color.a = 0
	return true
```

I remarked that when using my effect with that line :` [fade_in]This is a test[/fade_in]`, it instead uses the built-in "fade" RichTextEffect. 
Maybe there is a problem while parsing the bbcode? Looks like it use the "fade" effect because its bbcode is contained the "fade_in" bbcode.
The problem does not occur if I create two custom RichTextEffects that have have a bbcode starting in the same way.

**Steps to reproduce:**

1. Create a RichTextEffect that has a bbcode starting with fade. 
2. Try to use it in a RichLabelText, it should use the built-in fade effect instead.

Or

Launch the minimal project below.

**Minimal Project Example:**
[FPE.zip](https://github.com/godotengine/godot/files/4433196/FPE.zip)

**Comment by akien-mga** [comment]
The relevant code probably checks something like `tag.startswith("fade")` and should be changed to include a trailing space, to ensure that the tag name is a 1:1 match and not a substring.

Note that if it's possibly be to declare custom effects with the same name as built-in ones, then they should be made to take precedence over the built-in.

**Comment by Darenn** [comment]
I've search in **rich_text_label.cpp** and find exactly what you mentioned, at line 2327.
```
else if (tag.begins_with("fade")) {
			Vector<String> tags = tag.split(" ", false);
			int startIndex = 0;
			int length = 10;
```

**Comment by Eoin-ONeill-Yokai** [comment]
Ah yeah that's an oversight. I'll address that tomorrow.

**Comment by Darenn** [comment]
I will try to fix it as my first contribution ;) 
I'm currently reading tutorials about contribution. I'll let you know if I need any help!

**Comment by Darenn** [comment]
Hey!

I'm about to do this : `else if (tag.split(" ")[0] == "fade")`.
Does not look very pretty, do you have any idea if I can do better ? (I'm a beginner)

**Comment by Eoin-ONeill-Yokai** [comment]
I would split the tag for spaces and do a direct equality check.

Begins with is great in conditions where you want some leniency but in this case we want to make sure the first "word" of the bbtag is fade exactly to prevent the overlapping issues.

When I'm at my pc, I can provide a more clear code example.

**Comment by Darenn** [comment]
Hi!
Thanks for your help. Do you mean it would be better to split the tag string before all the if else comparison?
I have thought of that first, but I was afraid to break something in the code.
I can try that tomorrow!

**Comment by Eoin-ONeill-Yokai** [comment]
Sure thing, here's my thought process.

The issue currently is that BBCode identifiers can now have overlap. For example, if someone makes a custom effect `rainbow_capitalized`, that identification can accidentally pass the if check on `line 2418` because `tag.begins_with("rainbow")` is true. This is a carry-over from the original implementation that didn't have user extendable effects.

The short of it is that, to fix this, I would actually try to be more explicit regarding identifiers. The bulk of this work will be in `RichTextLabel::append_bbcode` as you've noted. However, to fix this will involve a few changes.

- [ ] After `String tag = p_bbcode.substr(brk_pos + 1, brk_end - brk_pos - 1);` on line 2094, You should split the tag up by spaces and grab the first element of the split. pseudocode `String bbIdentifier = tag.split(' ', false)[0];` This will give you the first "term" of the identifier in isolation.
- [ ] Next comes the giant if / else statement (sorry, not entirely my fault, this is partially legacy) where you will need to carefully assess whether these will need to be updated. **For a shorthand, the following are probably ok to remain as-is:**
    - `if (tag == 'sometag') { .... }` This is already checking for an **exact** match.
    - `if (tag.begins_with('/')) { ... }` This is simply checking for an "end" statement. Shouldn't need to be touched.
    - `if(tag.begins_with('sometag='){ .. .}` The equality on the end is already helping with matching exact phrases. This restricts someone from using an equals sign as their tag identifier, but that's a perfectly reasonable limitation imo.

-  However, you will have to **change lines that look like**:
    - `if(tag.begins_with('sometag')) { ... }` should now become `if( bbIdentifier == 'sometag' ) { ... }`

Hopefully that's helpful. This is kind of pseudo code but should help you get to where you need to be.

**Comment by Darenn** [comment]
Ok I understand!
So instead of splitting to get the bbcode at each if, I should just get it once at start, store it, and compare it when needed. I will get it done today, thanks.

**Comment by Darenn** [comment]
Ok I just did it in #37608.
Tell me if it's not what you expected!
