### ISSUE TITLE
Cannot build in Visual Studio after NULL to nullptr changes (32-bit)

### ISSUE THREAD

**Issue by CNate** [godotengine/godot#37620]
**Godot version:**
3.2.1-stable.official
**OS/device including version:**
Windows 10
Visual Studio 16.4.5 & 16.5.2
scons v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691
**Issue description:**
Getting an error when building SCons generated VS solution
**Steps to reproduce:**
Generate godot solution for Visual Studio with SCons and attempt to build the solution through Visual Studio.

I looked at the similar issues but it seems that they claim is has been resolved. A recent commit changed NULLs to nullptrs for these lines reporting the errors. https://github.com/godotengine/godot/commit/95a1400a2ac9de1a29fa305f45b928ce8e3044bd

![Capture](https://user-images.githubusercontent.com/13683291/78514434-57741a00-777f-11ea-8d25-34aacf017c40.PNG)

**Comment by ThakeeNathees** [comment]
relative to: #36113

**Comment by akien-mga** [comment]
> **Godot version:**
> 3.2.1-stable.official

That does not make sense, the Vulkan port is in the `master` branch, not in 3.2.1-stable.

Which commit from the `master` branch are you building?

**Comment by akien-mga** [comment]
I assume you're building for 32-bit Windows?

The problem is likely due to the fact that those typedefs are different on 64-bit and 32-bit Windows as per:
https://github.com/KhronosGroup/Vulkan-Headers/blob/0e78ffd1dcfc3e9f14a966b9660dbc59bd967c5c/include/vulkan/vulkan_core.h#L59-L65

On 32-bit Windows they're `uint64_t` and `nullptr` can't be converted to an integer by design.

**Comment by akien-mga** [comment]
Confirmed with a 32-bit Linux build with GCC, working on a fix.

**Comment by CNate** [comment]
@akien-mga Thanks for that. You were absolutely correct on all cases.
