### ISSUE TITLE
FIleSystem won't show external files in res://

### ISSUE THREAD

**Issue by markidak** [godotengine/godot#37671]
![image](https://user-images.githubusercontent.com/33268307/78704037-88815580-790b-11ea-97ab-4ac718e3cea9.png)
I am still novice and following step by step tutorials. This bug has rendered me unable to even start a tutorial to be honest. Whatever I import into the file I can't see in Godot unless that file is made inside Godot. No external resources show up.

**Comment by Anutrix** [comment]
Please follow the issue template.
Give Godot version, OS and any other details.

**Comment by Xrayez** [comment]
Currently this is a feature. A file which is not recognized by the engine is ignored. Those files cannot be used by the engine directly and have to be imported in some way. A lot of files are also imported like `.png` so they mostly represent named resources which happen to live inside the *virtual* `res://` filesystem used by Godot to map resources in some way.

Do you suggest that there should be an option/switch to show *all* files? 

> This bug has rendered me unable to even start a tutorial to be honest.

What part of the tutorial makes it impossible/difficult to follow? You can request to clarify tutorials at [godot-docs](https://github.com/godotengine/godot-docs) specifically.

> Whatever I import into the file I can't see in Godot unless that file is made inside Godot. No external resources show up.

There's currently a usability issue of having to refocus the Godot editor in order to force the rescan of externally modified files in order for them to be reimported again, just as a hint.

It's also possible to create an arbitrary *text* file with the script editor. Saving such a file won't show it up in the FileSystem dock either unfortunately.

See also [Import plugins](https://docs.godotengine.org/en/3.2/tutorials/plugins/editor/import_plugins.html).

**Comment by winston-yallow** [comment]
It was just discussed on discord. The problem was that the `start` and `end` folders where godot projects itself, containing a `project.godot` file. Therefore they are not shown in the FileSystem dock.

I reproduced this in godot 3.2.1

**Comment by markidak** [comment]
I'd like to see the option to have an unfiltered view of all files in my res:// directory. I'll close the issue now as it was my mistake, not a bug, but a feature.

**Comment by Xrayez** [comment]
> It was just discussed on discord. The problem was that the `start` and `end` folders where godot projects itself, containing a `project.godot` file. Therefore they are not shown in the FileSystem dock.

Actually I've heard rumors about having nested project support, namely when it comes to plugin development as they are usually created as Godot projects at first, so we'll see how it goes.
