### ISSUE TITLE
Bug: rotating Light2D affects LIGHT_VEC

### ISSUE THREAD

**Issue by vetoed** [godotengine/godot#3772]
Windows 10 64bit.
Normal mapping works fine when all lights are omni. It's not that easy when trying to achieve spotlights.

![Figure 1](https://cloud.githubusercontent.com/assets/17331426/13169461/fb0a0718-d6e5-11e5-9d9c-f75affee65e0.gif)
As the light rotates, the bricks begin to be lit from the wrong side.

The LIGHT_VEC constant in light shader gets altered on light rotation. If my understanding is correct, it should remain the same.

[example_scene.zip](https://github.com/godotengine/godot/files/137664/example_scene.zip)

**Comment by lekoder** [comment]
This issue also affects 3.0a2, with built-in normal mapping.

It seems that `LIGHT_VEC` rotates with the light, and it really should not. In following example, a light is a child of object on center:

https://www.youtube.com/watch?v=qYCd0fl5zWg

**Comment by mhilbrunner** [comment]
Still rotating in Godot 3.0 beta 2.

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by lekoder** [comment]
@akien-mga My current project is frozen because this issue - I don't want to commit to idea of pre-rendered normal-mapped assets if I'm not sure that they will actually work in the project and they will look good enough in game - hiring artists takes too much of my current miniscule budget to waste their time on such experiments.

I am aware that 2d is not a focus for 3.0 release, however good support for 2d graphics/physics/rendering is actually the very reason I choose Godot for my project in the first place. Releasing 3.0 is a monumental task and I will certainly understand if you choose to push this down to 3.1, but I won't resume development until this one is fixed.

**Comment by vetoed** [comment]
@lekoder Workaround is scripting lights to keep no rotation at all times, works for omnis. For spotlights you have to render rotated texture into new texture and use that as a light texture. It's probably expensive to run but will give an idea how it looks.

**Comment by lekoder** [comment]
@vetoed I seen this workaround and this is not practical. I have a couple of spaceships (RigidBody2d) flying around asteroids, each with few of spotlights working as both general illuminations and radar beams.

Yeah it looks good on screenshot/mockup, but I'm not sure if there will be no weird artifacts and edge cases.

I actually had similar case with 2.5d (top-down locked 3d): It looked good on mockup, but even in first gameplay tests I found that player had real problem with seeing what will cause actual collision (due to z-movement not apparent in projection). I don't want to get to similar dead end with 2d/normals.

Then again, I recognize that 2d is not a focus for 3.0 release, and it's not like I'll go bankrupt over this. I can and will wait for this is issue to be fixed in 3.1 if necessary. I could probably commit to start porting to 3.0 (currently developing in 2.1.4) if it's stable enough and some assurance that this issue won't be pushed down the backlog to 3.2 or later :)

**Comment by thorlucas** [comment]
This is still broken for me.
