### ISSUE TITLE
RichTextLabel append text problem

### ISSUE THREAD

**Issue by ShrewdSpirit** [godotengine/godot#3773]
Arch Linux x64

When I try to append text in any possible way to a rich text label, the first line will be a duplicate of all contents with no escape characters and other lines will be the new content.
To reproduce, try to append text to a rich text label!

I'm using [this commit](https://github.com/godotengine/godot/commit/f88d7a0df7d28ff5572173ba3e496907de79bb04)
![Screenshot](http://up.vbiran.ir/uploads/35432145587238927735_DeepinScreenshot20160219121213.png)

**Comment by salalex** [comment]
I had the same problem (Godot 2.0.2 official) and, based on some tests I made, it seems to happen only when the first character appended after a call to .clear() is a newline "\n", though it does not happen if instead of appending "\n" you use the .newline() method.

Try changing from `append_bbcode('\n'+msg) ` to  `append_bbcode('msg+'\n') `  and see if it works.

**Comment by ShrewdSpirit** [comment]
@salalex Yeah I use the newline method and it works.

**Comment by salalex** [comment]
I created a minimal project that demonstrates the issue: http://olomatrix.org/godot/RichTextLabelBug.zip
Simply run the project and follow the on-screen directions.
