### ISSUE TITLE
using setget on a dictionary doesn't work properly if I modify the dictionary by index

### ISSUE THREAD

**Issue by Megaguy32** [godotengine/godot#37737]
**Godot version:**
3.2.1

**OS/device including version:**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.68.0
Qt Version: 5.14.2
Kernel Version: 5.4.30-1-MANJARO
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7700K CPU @ 4.20GHz
Memory: 15,6 GiB of RAM

**Issue description:**
using setget on a dictionary doesn't work properly if I modify the dictionary by index

**Steps to reproduce:**
the code explains

**Minimal reproduction project:**
```
extends Node

var dict = {0: false} setget set_dict

func set_dict(value):
	print("triggered")

func _ready():
	self.dict[0] = true
	print(dict)

# then dict[0] is true anyway even though the setter should discard / ignore the value.
# for reference, docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html#setters-getters
```

**Comment by nisovin** [comment]
A setter is only triggered when setting the variable itself, not when modifying the object the variable contains. So `self.dict = {}` will trigger the setter. This applies to any dictionaries as well as arrays and anything that extends Object.

**Comment by aaronfranke** [comment]
Exactly what @nisovin said. This is the same behavior as other languages, and is not a bug.

**Comment by bojidar-bg** [comment]
(Well, the issue is closed now. Anyway, I wrote this wall of text before that, so and I'm still going to posted, as I do not want to scrap it)

Dictionaries, Arrays (but not PooledXArrays before 4.x), and Objects are passed by reference. This means that a variable containing a dictionary actually contains only a reference, a pointer, to that dictionary.

Therefore, when you do `self.dict[0] = true` you get the dictionary, then modify it before the setter is even called.

"But why does the setter get triggered then?"
Consider the following case:
```gdscript
var vec = Vector2(0, 0) setget set_vec

func set_vec(value):
	print("triggered")

func _ready():
	self.vec.x = 1
	print(vec) ## Prints (0, 0)
```
Since Vector2-s are passed by value, `self.vec.x` first gets "vec" from `self`, then changes the "x" property of the returned value.. and then assigns the new value to `self.vec`.
In psuedocode:
```gdscript
self.vec.x = 1
# -->
var _vec = self.vec # Copies the value
_vec.x = 1 # Changes the value
self.vec = _vec # Without this step, self.vec would remain the same
```

The same happens when dictionaries/arrays/objects are modified by index, but this is something which would probably be fixed in future (https://github.com/godotengine/godot/issues/17310#issuecomment-371397418 / #28720).

In order to make your example work, you should duplicate the dictionary returned by self.dict, so that people outside the class cannot modify the dictionary by reference:
```gdscript
var dict = {0: false} setget set_dict, get_dict

func set_dict(value):
	print("triggered")
func get_dict():
	return dict.duplicate()
```

**Comment by Megaguy32** [comment]
Thanks for the clearing up especially bohidar-bg for the good explanation.
For clarity about nisovin's claim, the setter *is*  triggered when modifying the object the variable contains and yet the contents value is changed. which confused me.

But I suppose I understand now that changing the contents of a container variable that is passed by reference (as opposed to variables passed by value) is changed before getters and setters are able to handle the operation.

respectfully imho, I would disagree on that not being a bug, because getters and setters are supposed to manage the modification and access of a variable, which I'd expect include arrays and dictionaries.

**Comment by bojidar-bg** [comment]
@Megaguy32 even if it is a bug, it is already handed in the two issues I linked above.
