### ISSUE TITLE
Error C2220 during project assembly

### ISSUE THREAD

**Issue by Mintormo** [godotengine/godot#37750]
**Godot version:**
4.0dev
commit 9ab08f06c89cb4ace09aaad1e3f33588835cf631

**OS/device including version:**
Windows 7 x64, Visual Studio 2017, MSVC 14.1

**Issue description:**
It's impossible to assemble a project from a master branch. Build is interrupted with error C2220.
File: godot\thirdparty\misc\cubemap_coeffs.h(24)
![bug](https://user-images.githubusercontent.com/2286710/78983366-c14c4500-7b2c-11ea-83e0-0b370f7e9857.png)

**Steps to reproduce:**
1. Run the project assembly from the command line: 
`scons -j 3`

**Minimal reproduction project:**

**Comment by akien-mga** [comment]
>  4.0dev

What commit?

**Comment by akien-mga** [comment]
According to https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2220?view=vs-2019 error `C2220` just means that there were warnings and since we treat them as errors, the build aborts.

So the real issue is about the warnings C4838: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4389?view=vs-2019

**Comment by Mintormo** [comment]
> What commit?
 9ab08f06c89cb4ace09aaad1e3f33588835cf631
Added

**Comment by akien-mga** [comment]
@Mintormo Could you translate what the message about warning C4838 says?

> So the real issue is about the warnings C4838: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4389?view=vs-2019

Google failed me, that's actually C4389.
C4388 does not have a specific documentation page on MSDN, but https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4200-through-c4399?view=vs-2017 says it's `'expression': signed/unsigned mismatch`.

@clayjohn The message looks to me like it's unhappy about `const float` (source format) to `double` conversion, but I can't find where it would be converted to double. It's passed in a storage buffer and used in the shader as `vec4[..]` which should be single float precision IINM.

**Comment by Mintormo** [comment]
> 
> 
> @Mintormo Could you translate what the message about warning C4838 says?
> 
> > So the real issue is about the warnings C4838: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4389?view=vs-2019
> 
> Google failed me, that's actually C4389.
> C4388 does not have a specific documentation page on MSDN, but https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-c4200-through-c4399?view=vs-2017 says it's `'expression': signed/unsigned mismatch`.
> 
> @clayjohn The message looks to me like it's unhappy about `const float` (source format) to `double` conversion, but I can't find where it would be converted to double. It's passed in a storage buffer and used in the shader as `vec4[..]` which should be single float precision IINM.

I tried translating with deepl.com/translator.

warning C4838: the conversion from "double" to "const float" requires a narrowing conversion

**Comment by akien-mga** [comment]
Thanks for the translation, and thanks for the link, I misread the warning number indeed.

**Comment by akien-mga** [comment]
I guess this might be due to VS 2017 treating floating point numbers as double by default unless post-fixed with `f`, so it treats this as doubles that end up converted to `const float`: https://github.com/godotengine/godot/blob/master/thirdparty/misc/cubemap_coeffs.h

I wonder if there's a convenient way to make it understand that those are floats without having to postfix `f` to every single of those numbers.

**Comment by clayjohn** [comment]
Oof, it shouldn't actually be too hard to just add "f"s just a find and replace all commas with "f,".
