### ISSUE TITLE
Particles menu is awkward

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#37784]
**Godot version:**
3.2.1

**Issue description:**
![image](https://user-images.githubusercontent.com/2223172/79029051-f68b7e00-7b92-11ea-8e0a-eb824fe34222.png)
Why there's a separator between each option .-.

**Comment by dreamsComeTrue** [comment]
I would say - to chop off different, unrelated functionality-domains; but that may be one cheesy answer :)

**Comment by Calinou** [comment]
I agree, separators could be removed here. Also, shouldn't **Restart** be the first option as it's probably the one people will use the most often? It's also mostly harmless as it won't change any data in the current scene.

**Comment by Xrayez** [comment]
> Also, shouldn't **Restart** be the first option as it's probably the one people will use the most often?

Playing the devil's advocate here, but might be related to [Serial-position effect](https://en.wikipedia.org/wiki/Serial-position_effect), namely it doesn't matter much whether an element is at the start or the end of the list. But it takes additional mouse movement in order to hit that **Restart** option indeed.

**Comment by clayjohn** [comment]
When I added the "Restart" button, I put it on the bottom because it was the newest button. I didn't consider strategic positioning at all. Similarly, I added a line break because all the other buttons had line breaks. 

It should be fine to reorder them and remove the line breaks if it looks bad.
