### ISSUE TITLE
Is there anyway to check if one script is set as autoload(singleton) script ?

### ISSUE THREAD

**Issue by davied9** [godotengine/godot#37849]
I'm trying to add a checker in my script

e.g.
 
SceneManager.gd
```
# This script manage scenes, need to run as @@ Singleton script @@
func _ready():
       if not is_autoloaded():
             print("[error] this scripts should run as autoload script !!!")
```

Is there a function to check if current script is autoloaded ?

**Comment by aaronfranke** [comment]
Not directly, but this can be accomplished with a script like this (autoloaded as "Autoloaded"):

```gdscript
extends Node

var loaded = false

func _ready():
	if Autoloaded.loaded:
		printerr("[error] this scripts should run as autoload script !!!")
	else:
		Autoloaded.loaded = true
```

This code:

* Will fail if the script is not autoloaded (since it accesses its autoloaded instance).

* Will print an error if there is more than one instance (allowing only the autoloaded one).

By the way, GitHub isn't a support forum, typically it would be better to ask these questions elsewhere. However, I'll leave this open in case we wanted to add something like `is_autoloaded`.

**Comment by Zireael07** [comment]
That is epically hard to know, it needs to be added to docs and a is_autoloaded function would be VERY welcome (*hint hint* )

**Comment by davied9** [comment]
@aaronfranke Thanks

**Comment by CaptainProton42** [comment]
I've been thinking about how one could implement this. The problem is that Singleton Nodes are just normal Nodes at runtime.

One way to do it would be to just add a property `is_autoloaded` to the `Node` class that is set to `true` after an autoloaded Node is instantiated. This, of course, has the downside that it would be easy to manipulate that value from the outside.

`SceneTree` could also create and hold a list of autoloaded Nodes.

Reading and comparing Autoloads from `ProjectSettings` at runtime will only work if the name of the autoloaded Nodes is never changed.

One could also try to check `ScriptServer` for matching globals but then this would only work with Autoloads that have "Singleton" enabled, and depends on the registered script languages. I also couldn't find an easy way of retrieving globals directly from `ScriptServer`.

Any thoughts on this?

**Comment by mrcdk** [comment]
This should work:

```gdscript
func _ready():
	# Autoloads are always children of the SceneTree's root node and not the SceneTree's current_scene
	if get_parent() == get_tree().root and self != get_tree().current_scene:
		print("This is an autoload %s" % name)
	else:
		print("This is NOT an autoload %s" % name)
```

**Comment by davied9** [comment]
@mrcdk Thanks, this helps me out

**Comment by davcri** [comment]
I saw that some years ago @vnen added `has_autoload` to ProjectSettings.cpp

https://github.com/godotengine/godot/pull/40162/files#diff-d06617966387fb7135d4af8cf52217b94e7a4c658c6ed9f259bbf8cd801e31d5R967-R989

However this was never exposed to GDScript/C# (EG: via [EditorPlugin](https://docs.godotengine.org/en/4.1/classes/class_editorplugin.html)): is it a design decision?

**Comment by vnen** [comment]
> However this was never exposed to GDScript/C# (EG: via [EditorPlugin](https://docs.godotengine.org/en/4.1/classes/class_editorplugin.html)): is it a design decision?

I didn't feel the need to expose it. But I believe you can already get a list of autoloads from ProjectSettings, since they are a setting like any other under the hood (maybe it's not properly documented).

Still, this issue is 3 years old, so it probably should be closed and if this is needed it should be opened as a proposal instead.

**Comment by davcri** [comment]
Thanks very much for the reply @vnen . 

Yes you're right, this code from GDScript works:
```gd
if ProjectSettings.has_setting("autoload/Game"):
   var game = ProjectSettings.get_setting("autoload/Game")
   print(game) # *res://addons/game-template/game.gd
```

Issue can be closed on my side!
