### ISSUE TITLE
Custom StyleBox not showing in Tabs' panel

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#37875]
**Godot version:**
3.2.1 mono
**OS/device including version:**
Windows 10
**Issue description:**
When I create a Tabs node and add a custom style to the panel (or anything), the style will not show.  Even if I take the Tabs node out of the container, it still will not show the custom style.
**Steps to reproduce:**
Create empty project
Add Node2d
Add a TabContainer to Node2d
Add a Tabs node to the TabContainer

Create a Custom Style and select StyleBoxTexture
Place the godot icon.png to the texture field.
The panel remains blank.

**Minimal reproduction project:**

**Comment by aaronfranke** [comment]
A minimal reproduction project would be appreciated.

**Comment by ondesic** [comment]
Should I just zip up the project folder and post it, or is there a better way?

**Comment by ondesic** [comment]
The structure is:
Node2d
----TabContainer
---------Tabs
Even with the Node2d as the root, if I apply the same StyleBox to the TabContainer, everything displays correctly.  It is only the Tabs node that is not displaying and StyleBox

**Comment by git2013vb** [comment]
Hi, I have same problem 
Also:
- signal issue: they not work
- Layout setting different between tabs (tried Full Rect)
[TestTabs.zip](https://github.com/godotengine/godot/files/4593616/TestTabs.zip)

**Comment by akien-mga** [comment]
Thanks for the details @git2013vb and the test project. I can confirm that it works as intended, @ondesic was misunderstanding how to use `Tabs`, which is not meant to use in `TabContainer` (those two nodes have similar features but are otherwise unrelated, see https://github.com/godotengine/godot-proposals/issues/2129).

>  I checked and the only Custom StyleBox that I don't know where is is "Panel" If someone can give me an hint about it - I can't see it nowhere :)

That's correct, the "panel" stylebox doesn't seem used in `Tabs`, I'll remove it.
