### ISSUE TITLE
VisualShader precision inconsistant?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#37884]
**Godot version:**

3.2.1

**OS/device including version:**

Ubuntu 20.04

**Issue description:**

precision of floats in VisualShader is inconsistant?
sometimes allows 4 decimals (scalar or vector op) and sometimes only allow 3 decimals (uniform or constant)

**Steps to reproduce:**

0.0345
input this value into a shader as a constant or uniform and it gets trimmed to 0.034
input this value into a shader as a part of an scalar or vector add or multiply and it does not get trimmed

![Sprite-0002](https://user-images.githubusercontent.com/962340/79260003-9844f080-7e5b-11ea-9bd8-3ae52d18b4c6.png)

close editor and edit the text file to pass in the right shader param and it works so that means it just a ui problem?

why trim to 3? i need 4! and float can handle 4!

or maybe there is an editor setting somewhere that i missed? i could not find it

please & thanks

**Minimal reproduction project:**

**Comment by clayjohn** [comment]
The display of floats in the editor is found in the editor settings under "Interface > Inspector > Default Float Step" reduce that number to 0.0001 and your number will display fine in the shader editor. 

In the future, please consider asking your question on one of the [community channels](http://docs.godotengine.org/en/latest/community/channels.html) (e.g. Q&A, discord, reddit) before opening a bug report. Reviewing and answering bug reports takes away time that could have otherwise been used to work on the engine, improve documentation, and respond to bug reports.

**Comment by rakkarage** [comment]
the (issue) inconsistency is not affected by the setting tho? if it is set to 3 it should show 3 in both those places? would make it seem less like a bug if was consistent? but maybe not maybe constant and uniform are meant to use and respect that setting while scalar and vector ops are supposed to ignore the setting idk!?
