### ISSUE TITLE
(possible) _draw() function behaving weirdly when maximising and minimising window

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#37897]
**Godot version:**
3.2.1

**OS/device including version:**
macOS Catalin 10.15.4 / MacBookPro11,1

**Issue description:**
I have a Godot project with standard configuration. Nothing has been changed.
I wrote a simple line of code in func _draw():
draw_circle(Vector2(rand_range(0, 600), rand_range(0, 600)), rand_range(100, 300), Color(0.39, 0.58, 0.93, 1))
The (possible) problem: When I run the project, then maximise and minimise the window, the circle gets rearranged on the screen.

Also, check this screen recording:
[Godot_Draw_Anomaly.mov.zip](https://github.com/godotengine/godot/files/4480177/Godot_Draw_Anomaly.mov.zip)

**Steps to reproduce:**
Use the attached Godot project.

**Minimal reproduction project:**
[Apocalypse Now.zip](https://github.com/godotengine/godot/files/4480168/Apocalypse.Now.zip)

**Comment by Calinou** [comment]
This is probably because the circle is drawn every frame while the transition occurs. Since you've called `randomize()` in `_ready()` and are using `rand_range` to define the circle's coordinates, it will move every frame.

If you want the random number to be deterministic, generate random values in `_ready()`, store them into member variables and use them in `_draw()`.

Closing, as this isn't a bug with the engine.

**Comment by drmar** [comment]
@Calinou

> This is probably because the circle is drawn every frame while the transition occurs. Since you've called randomize() in _ready() and are using rand_range to define the circle's coordinates, it will move every frame.

I made a version without randomize() and it behave identically.
The problem is still there.
