### ISSUE TITLE
Godot 3.2.1 bakedlightmap issue

### ISSUE THREAD

**Issue by josedgm** [godotengine/godot#37909]
Godot version: 3.2.1 stable win64
OS/device including version: Windows 10 PRO

When I use a small "cell size" value for the bakedlightmap, the size of the scene file grows extremely big.(more than 700MB). This makes every save or runs process takes quite long, and of course the app becomes very big. (even though the generated PNG files are less than 10MB). 

If I use a bigger "cell size" value, the he scene file becomes smaller but the "lightmap" becomes a bunch of big clear and dark rectangles.

 Is this behavior normal? is there a work arround for such big scene files?

Thanks

**Comment by Calinou** [comment]
There are known issues with BakedLightmap in 3.2, see #30929. The lightmapper will be rewritten for Godot 4.0.

As for the scene file size issue, try saving the scene as `.scn` instead of `.tscn` (which is a text-based format). You may be able to save only the baked lightmap data to a `.res` file to avoid having to convert the entire scene to a binary format.
