### ISSUE TITLE
Code editor block indent

### ISSUE THREAD

**Issue by flurick** [godotengine/godot#3803]
Indenting lines is picky with the first and last selected lines. The **first** lines tab is inserted  where the selection begins. The **last** lines tab is inserted at the beginning, but only if the selection goes past the first character.
I expected the tab characters to be inserted at the beginning of each line touched by the selection.

**Comment by adolson** [comment]
Holding Alt and pressing the left/right arrows seems to work fine for me.

**Comment by bojidar-bg** [comment]
@akien-mga / @kubecz3k ~ Please retag this as a bug, since it is clearly not the expected behaviour.

Initial selection:
![image](https://cloud.githubusercontent.com/assets/5276727/13349594/9b0efabe-dc83-11e5-8032-d5b533011a03.png)
After pressing <kbd>Tab</kbd>:
![image](https://cloud.githubusercontent.com/assets/5276727/13349607/b2a4e42c-dc83-11e5-9d78-bf22e1ee54f0.png)
After pressing <kbd>Alt</kbd>+<kbd>Right</kbd>
![image](https://cloud.githubusercontent.com/assets/5276727/13349699/32bbfa9c-dc84-11e5-9917-b3fc50f6ee86.png)
After pressing <kbd>Tab</kbd>, when the selection doesn't include characters from the last line (but the cursor is clearly on it):
![image](https://cloud.githubusercontent.com/assets/5276727/13349644/e346e59e-dc83-11e5-8f66-00f07efd9c87.png)
After pressing <kbd>Alt</kbd>+<kbd>Right</kbd>, when the selection doesn't include characters from the last line (but the cursor is clearly on it):
![image](https://cloud.githubusercontent.com/assets/5276727/13349819/def1e3a8-dc84-11e5-9ac8-2ee23b565d5a.png)

Overall, the behaviour between <kbd>Tab</kbd> and <kbd>Alt</kbd>+<kbd>Right</kbd> is inconsistent. Also,  <kbd>Alt</kbd>+<kbd>Right</kbd> isn't perfect either - it generates an awful undo-redo history, removing and readding the lines one by one, while <kbd>Tab</kbd> can be easily undone with <kbd>Ctrl</kbd>+<kbd>Z</kbd>.

(Sorry for the varying screenshot region...)
