### ISSUE TITLE
AnimatedSprite not working as expected

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#38052]
Godot Version : 3.2.1

OS : Ubuntu 18.04

Issue description : 
I created an Animation Sprite, with 2 animations : idle (1 frame) and attack (3 frames)
Attack happens on action_just pressed_input
Then I listen to animation_finished of the attack animation, and switch to idle.
Expected : go back to idle
Actual : the animation get stuck on "attack" and the game freezes

This happens randomly, so if at first you can't reproduce, you can stop and start again the game.
Use space bar to test.

**Steps to reproduce:**

**Minimal reproduction project:**
[minimal_bug.zip](https://github.com/godotengine/godot/files/4505277/minimal_bug.zip)

**Comment by guilhermefelipecgs** [comment]
I think the way you created your code generates an infinite loop. Chainging this 
`$AnimatedSprite.play("idle")` to this `$AnimatedSprite.call_deferred("play", "idle")` solves your problem.

**Comment by guilhermefelipecgs** [comment]
Even better, add some fps to your idle animation like this:
![Screenshot from 2020-04-20 16-09-46](https://user-images.githubusercontent.com/1387165/79789986-6f23d480-8321-11ea-9eab-953a9d8249d5.png)

**Comment by guilhermefelipecgs** [comment]
Although I think this freeze should be investigated.

**Comment by hakro** [comment]
Hi Guilherme,
Thank you for your reply.
Adding an FPS of at least 1 seems to be solving the problem indeed.
My initial thought was: since idle is not really an animation, but a single frame, maybe there is no need to add some FPS.
And that caused the freeze, so maybe there should be some kind of notification or warning when the FPS value is 0, so it won't cause a confusion? Or it shouldn't be possible to set it to 0 in the first place.
What do you think?

**Comment by guilhermefelipecgs** [comment]
Setting FPS to 0 should be possible IMO. I think this issue must be investigated a little more deeply, because freezing the game is not a desired behavior.

**Comment by avencherus** [comment]
@guilhermefelipecgs I believe you're correct.

I took a quick look, but I'm out of time.  What I could see is it is being trapped in a while loop during processing.

It seems like some kind of threading or async callback issue, because during the while loop `set_animation("idle")` is called, and then the timeout value will become 0.0 during the loop, when it shouldn't be.  So the timers at the end are doing -= 0.0 and never advance, creating an infinite loop.

The logic before the loop appears to guard against 0.0 time, but the animation name is updated during mid loop, which is what it uses to get the timeout value.  So it get's an invalid time during an iteration.  (Possibly the last iteration of "attack")

https://github.com/godotengine/godot/blob/f989a43135ce42a43c35193b8eecefb055aec84c/scene/2d/animated_sprite_2d.cpp#L385-L387

https://github.com/godotengine/godot/blob/f989a43135ce42a43c35193b8eecefb055aec84c/scene/2d/animated_sprite_2d.cpp#L395

https://github.com/godotengine/godot/blob/f989a43135ce42a43c35193b8eecefb055aec84c/scene/2d/animated_sprite_2d.cpp#L634-L636





The problem area.

https://github.com/godotengine/godot/blob/f989a43135ce42a43c35193b8eecefb055aec84c/scene/2d/animated_sprite_2d.cpp#L376-L431


If you need this working, a hack could be written to check the next timeout value during the loop:

```
			while (remaining) {

				if (timeout <= 0) {

					timeout = _get_frame_duration();

					if (timeout <= 0.0) {
						break;
					}
```

The proper way would be to figure out the timing issue and rewrite the logic based on that.  The stack is looking like:

```
 	godot.windows.tools.64.exe!AnimatedSprite::play(const StringName & p_animation, const bool p_backwards) Line 616	C++
 	godot.windows.tools.64.exe!MethodBind2<AnimatedSprite,StringName const &,bool>::call(Object * p_object, const Variant * * p_args, int p_arg_count, Variant::CallError & r_error) Line 1619	C++
 	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 921	C++
 	godot.windows.tools.64.exe!Variant::call_ptr(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant * r_ret, Variant::CallError & r_error) Line 1112	C++
 	godot.windows.tools.64.exe!GDScriptFunction::call(GDScriptInstance * p_instance, const Variant * * p_args, int p_argcount, Variant::CallError & r_err, GDScriptFunction::CallState * p_state) Line 1091	C++
 	godot.windows.tools.64.exe!GDScriptInstance::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 1202	C++
>	godot.windows.tools.64.exe!Object::call(const StringName & p_method, const Variant * * p_args, int p_argcount, Variant::CallError & r_error) Line 900	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant * * p_args, int p_argcount) Line 1217	C++
 	godot.windows.tools.64.exe!Object::emit_signal(const StringName & p_name, const Variant & p_arg1, const Variant & p_arg2, const Variant & p_arg3, const Variant & p_arg4, const Variant & p_arg5) Line 1275	C++
 	godot.windows.tools.64.exe!AnimatedSprite::_notification(int p_what) Line 415	C++
 	godot.windows.tools.64.exe!AnimatedSprite::_notificationv(int p_notification, bool p_reversed) Line 127	C++
 	godot.windows.tools.64.exe!Object::notification(int p_notification, bool p_reversed) Line 933	C++
 	godot.windows.tools.64.exe!SceneTree::_notify_group_pause(const StringName & p_group, int p_notification) Line 987	C++
 	godot.windows.tools.64.exe!SceneTree::idle(float p_time) Line 524	C++
 	godot.windows.tools.64.exe!Main::iteration() Line 2036	C++
 	godot.windows.tools.64.exe!OS_Windows::run() Line 3159	C++
 	godot.windows.tools.64.exe!widechar_main(int argc, wchar_t * * argv) Line 162	C++
 	godot.windows.tools.64.exe!_main() Line 184	C++
 	godot.windows.tools.64.exe!main(int _argc, char * * _argv) Line 196	C++
```

**Comment by avencherus** [comment]
Ah, actually missed that the project had a signal connected via tscn.  Nothing asynchronous actually.

1. It calls the finished signal.
2. The finished signal in the project calls play("idle")
3. This sets the new animation.
4. Loop iterates again, because it still has time remaining.
5. References the new animation name.

It's a timing issue with the signal and just has to be rewritten so it emits the finish signal outside the loop.
