### ISSUE TITLE
My lighting and texture are gone went I lunch the game on android

### ISSUE THREAD

**Issue by Inlinkcraft** [godotengine/godot#38087]
**Godot version:** 3.1.2.stable

**OS/device including version:** Windows 10 Home

**Issue description:** when i lunch my app on my pc everything is fine but went i lunch on my android phone everything is gone and my lighthing is funcky and laggy

PC 
![image](https://user-images.githubusercontent.com/47537121/79893624-558e9580-83d2-11ea-9cca-48b01cb82947.png)

Phone
![94229368_277118523681860_8745903121013669888_n](https://user-images.githubusercontent.com/47537121/79893865-a1d9d580-83d2-11ea-8345-4ba3c27c4e22.jpg)

I tried Manualy putting the texture in the Material tab
I also tried going in Project Setting>Vram Compression and activation Import Etc like some people said

I can't send my godot file because it too big .. sorry

**Comment by Calinou** [comment]
Which renderer are you using in the project (GLES3 or GLES2)? Make sure to use GLES2 when exporting to mobile platforms.

**Comment by Inlinkcraft** [comment]
I updated to Godot : 3.2.1.Stable
and my renderer is GLES3
but it stills doesn't work

**Comment by lawnjelly** [comment]
You'll need to tune quite a few things moving between GLES2 and GLES3 because they are quite different, see:
https://docs.godotengine.org/uk/latest/tutorials/misc/gles2_gles3_differences.html
especially the color space, lack of HDR and tonemapping.

Also note that there are some project settings regarding rendering that default to different values on desktop and mobile (e.g. force vertex shading) and you might want to try some of the mobile settings on desktop to get some kind of preview.

**Comment by Calinou** [comment]
As @lawnjelly said, try disabling **Rendering > Quality > Shading > Force Vertex Shading.mobile** in the Project Settings then export the project to Android again.

**Comment by Inlinkcraft** [comment]
It worked !!
I desactivated:
- Force Vertex Shading (mobile)
- Force Lambert (mobile)
- Force Blinn Over Ggx (mobile)
Thanks alot for your help

**Comment by lawnjelly** [comment]
Note that while it is possible to deactivate vertex shading on mobile, this may cause lower performance on some devices, so if at all possible, and you can get it looking good, I would recommend trying to do it the other way around, i.e. force vertex shading on desktop, and then retune the lighting etc until you can get it looking good.

In your screenshot for GLES2, it looks like the table particularly is 'overexposed', there is too much light hitting it. Due to the lack of tonemapping etc, GLES2 can be more expensive to overbright areas. You might be able to turn some of your lights down for GLES2.

There have been some issues with overbright lighting with vertex shading (#34257) I don't know if these have been fixed since.
