### ISSUE TITLE
Feedbacks about a first time experience

### ISSUE THREAD

**Issue by Nutriz** [godotengine/godot#38139]
I will try to fill in the template but this issue is a bit special, in sense of I'm reporting a guy (not me) who complains about his first experience in Godot. I was happy to see this [nice project](https://ldjam.com/events/ludum-dare/46/otherworldlyflavors) was made with Godot, I had a very fun and productive moment to use Godot for this last ludum dare, so my curiosity ask him how was his first time with Godot, and...and...

> "I did not have a good time with Godot. There were so many gotchas and random hiccups with bad google/documentation resolutions"

:sob: :sob: :sob: 

This sentence was followed by a list of points (see below). I don't have really proposal for there points but I think is interesting to have first time experience feedbacks.

**Describe the project you are working on:**
LD46, 2D card game

**Describe the problem or limitation you are having in your project:**
* I spent 30 minutes trying to figure out how to center text in a rich text label.
* I spent an hour trying to get the icon for the exe changed and still couldn’t do it.
* The engine text editor was a complete pain to work with. It didn’t open new files automatically when created. The tabs on the top and panel to the left for scripts vs scene was frustrating as scenes and scripts often had similar names.
* F2 to change to 3d view instead of renaming an object drove me mad.
* Changing a nodes placement in the tree breaks all your scripts and there is no tool that automatically looks in all scripts for if that object has been accessed and tries to auto fix the path for it.
* Sure it(Godot) is a tiny download, but that’s because they don’t download the packaging templates with the base engine. So when you actually want to export then you get another half gig of data. It just didn’t feel ready for prime time still.

**Comment by MWFIAE** [comment]
As I'm fairly new as well I will just explain my view on things :)

1. I spent 30 minutes trying to figure out how to center text in a rich text label.

Using bbcodes to solve this feels natural since one would generally only use a RichTextLabel if planning to use bbcode anyways. 
One could argue that such an option should exist if bbcode is disabled. 
 

2. I spent an hour trying to get the icon for the exe changed and still couldn’t do it.

Documentation is there and can be easily found. Would be nice to have an additional tooltext in the export window though. Right now it just seems like it doesn't work. 


3. The engine text editor was a complete pain to work with. It didn’t open new files automatically when created. The tabs on the top and panel to the left for scripts vs scene was frustrating as scenes and scripts often had similar names.

New scripts do open automatically if attaching to a node. Scripts won't be opened if creating them via the FileSystem dock. That's a bit inconsistent. However I always directly attach, therefore this wasn't much notable for me.


4. F2 to change to 3d view instead of renaming an object drove me mad.

Yeah this default is strange and also made it more difficult to onboard the others. Maybe we can change that to something more common for new users?
But as mentioned can be changed manually, so it's not that big of a deal for experienced godot developers.

5. Changing a nodes placement in the tree breaks all your scripts and there is no tool that automatically looks in all scripts for if that object has been accessed and tries to auto fix the path for it.

I would call that a bad coding habit in godot. 

6. Sure it(Godot) is a tiny download, but that’s because they don’t download the packaging templates with the base engine. So when you actually want to export then you get another half gig of data. It just didn’t feel ready for prime time still.

Maybe include a popup on first launch to ask which export templates should be downloaded? 
Not a big deal for me though :)

---

On a sidenote, we also participated in the [ludum dare](https://ldjam.com/events/ludum-dare/46/medic), quite enjoyable to make games with godot :)
Also it was fairly easy to onboard the others. I think with any other new engine we wouldn't have gotten that far in that short amount of time :)

**Comment by Calinou** [comment]
> Yeah this default is strange and also made it more difficult to onboard the others. Maybe we can change that to something more common for new users?

<kbd>F5</kbd> is already used to run the project, so we can't move the <kbd>F2-F4</kbd> keys one column towards the right, unfortunately.

**Comment by MWFIAE** [comment]
> F5 is already used to run the project (and F6 for the current scene), so we can't move the F1-F4 keys two columns towards the right, unfortunately.

How about the normal `1` `2` `3` keys? Or just with a key combination like Ctrl+F1 etc.
Also I'm not sure how it's implemented right now, but does adding new MainScreen-EditorPlugins also add F Keybindings? I guess not because of the conflict with `F5`. 


> I'm not sure about this. I think it's better to just let people download individual export templates to make the download faster instead: [godotengine/godot-proposals#647](https://github.com/godotengine/godot-proposals/issues/647)

Oh didn't know that this isn't possible right now. Would explain why I should download so much even though I only tried to export to windows^^
I cancelled it because of my bad connection and just let the other guys build instead 😅 
So yeah, that would be a huge plus for me too :)

**Comment by Calinou** [comment]
> How about the normal 1 2 3 keys?

I can see two downsides with this:

- This makes it no longer possible to switch tabs while in the script editor (or any text field in general).
- On some keyboard layouts like AZERTY, you need to press two keys to type 1/2/3 (nonwithstanding the numpad, which many laptops don't have).

**Comment by MWFIAE** [comment]
![image](https://user-images.githubusercontent.com/6072971/80280008-7cfe9e80-8701-11ea-9d98-bb4b1db244b9.png)

This is the only one currently in use. 
Ironically it's a rename function :D
But I think we can just reassign that to Shift+F2 (not used) instead.

**Comment by Calinou** [comment]
Closing, as the main actionable issues described here have been addressed. Please open new feature proposals
 if needed.
