### ISSUE TITLE
Steam thinks Godot is still running after I quit

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#3813]
**Operating system or device:**

Linux 64-bit, Steam version

**Issue description** (what happened, and what was expected):

Steam thinks I am still running Godot after I quit. I tracked it down to this process which remains running in the background: adb -P 5037 fork-server server

If I kill adb, Steam resumes normally.

**Steps to reproduce:**

Launch Godot, do some stuff, quit. Sometimes it's fine. Sometimes it isn't.

**Link to minimal example project** (optional but very welcome):

**Comment by est31** [comment]
Its most probably caused by the `adb` daemon for android, which gets started by godot and then runs for as long as the phone is connected. Don't really know why adb has been designed this way, most probably to offer some state over the command line.

Godot should simply kill that process on exit: http://developer.android.com/tools/help/adb.html#stopping

The issue then of course is that it might cause problems with people who want to use adb separately from godot.

**Comment by est31** [comment]
Correction: its not the adb daemon (that runs on the phone), but the adb server (that runs on the computer).

**Comment by kubecz3k** [comment]
Archiving because there is fresh discussion on this issue here: https://github.com/godotengine/godot/issues/4073#issuecomment-198667838
