### ISSUE TITLE
Godot names nodes in reverse order when duplicating more then 1

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#38162]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10 Pro Education 64 bit

**Issue description:**
when duplicating nodes the editor seems to name them in reverse order.
![image](https://user-images.githubusercontent.com/2453707/80160343-40f0ff80-8582-11ea-85d3-d42873bc3713.png)

**Steps to reproduce:**
- create two nodes 1 named Block0 and another named Block1
- duplicate them
- see that Block0 and Block3 are in the same position but Block 3 should be named Block2 and Block2 should be named Block3

**Minimal reproduction project:**
Not needed

**Comment by aaronfranke** [comment]
I took a look at the code and couldn't figure it out. https://github.com/godotengine/godot/blob/master/editor/scene_tree_dock.cpp#L556 

If I change the loop to `.front()` and `->next()` instead of `.back()` and `->prev()`, the behavior is the same somehow and has the same bug.

If I change `selection_tail` to move to the parent's next child each iteration, the result is that the duplicated nodes are placed after nodes after the selection (and the editor crashes if there are no more nodes to skip over).

If I change `selection_tail` to point to the previous duplicated node, then future duplicated nodes aren't added to the scene, and performing more operations with the same selection gives "Can't operate on nodes from a foreign scene!"

How do we place duplicated nodes after other duplicated nodes?

**Comment by TheDuriel** [comment]
Might be because renaming is automatically done, and propagates up the tree, not down.

So you'd duplicate the nodes, wait for them to rename, then sort. Or rename them _before_ adding the copy to the scene tree.

**Comment by sumit0190** [comment]
@aaronfranke That's strange - I ran into this issue today and made the same change as you did to see if it fixes it (change `back` to `front` and `prev` to `next`) - and it worked. Now `Block2` corresponds to `Block0` and `Block3` to `Block1`, but they are still added into the hierarchy incorrectly (i.e., `Block3` comes before `Block2`).
