### ISSUE TITLE
Can't pass script reference to function or inner classes

### ISSUE THREAD

**Issue by asluizh** [godotengine/godot#38266]
**Godot version:**
3.2

**OS/device including version:**
Linux/X11 

**Issue description:**
As a workaround for #4472, I tried passing a script variable to an inner class. The function that receives it as an argument only sees null.

**Steps to reproduce:**
Make a new script containing:
```
var s = preload("res://printHelloWorld.gd").new()

class Ref:
	var s : Script
	func _init(script:Script):
		self.s = script
		print(script)
		print(typeof(script))

func ps(script:Script):
	print(script)
	print(typeof(script))

func _ready():
	print(s)
	print(typeof(s))
	var a = Ref.new(s)
	ps(s)
```
Will print: 
```
[Node:1187]
17
Null
0
Null
0
```
**Minimal reproduction project:**
[tests.zip](https://github.com/godotengine/godot/files/4541670/tests.zip)

**Comment by ThakeeNathees** [comment]
`preload("res://printHelloWorld.gd").new()`  here s is not a Script, its a ScriptInstance
`preload("res://printHelloWorld.gd")` is a script resource

`func _init(script:Script):` you're providing ScriptInstance instead of Script which throws a runtime error on current master, but not in 3.2 (this could be backported to the 3.2 branch).
 
and the `typeof(...)` returns different values on 3.2 and current master which leads inconsistency in gdscript if anyone using `if typeof(s) == 17` will fail on master

**Comment by asluizh** [comment]
I see. So the issue is then that the editor does not throw an error when we pass a ScriptInstance to a variable that expects a Script. 

It is confusing as well because at least in the 3.2 version, I thought that that was the expected behavior, since `typeof(s) == typeof(Script)` is true, and thus I chose the type of Script for the function argument.

This issue disappears if the argument of the function is of the type Node instead. Should I close this?

**Comment by akien-mga** [comment]
> It is confusing as well because at least in the 3.2 version, I thought that that was the expected behavior, since `typeof(s) == typeof(Script)` is true, and thus I chose the type of Script for the function argument.

That's because `typeof()` only returns which `Variant` type the variable contains, which is `Object` in this case for both `Script` and `ScriptInstance`.

As it seems to be reporting errors properly in the `master` branch, I think we can close this.
