### ISSUE TITLE
Android 1 click deploy / ADB not working 3.2.2.beta1

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#38278]
**Godot version:**
3.2.2.beta1
**OS/device including version:**
Windows10
**Issue description:**
Android 1 click deploy doesn't launch project.  Same project works / one click deploys on 3.2 stable.
0 param: --remote-fs
1 param: localhost:6010
2 param: --remote-debug
3 param: localhost:6007
4 param: --xr_mode_regular
5 param: --use_depth_32
6 param: --use_immersive
Uninstalling previous version: Samsung SM-N960U1
Installing to device (please wait...): Samsung SM-N960U1
--- Device API >= 21; debugging over USB ---
--- DEVICE API >= 21; DEBUGGING OVER USB ---
Reverse result: 0
Reverse result2: 0
--- Debugging process started ---
--- Debugging process stopped ---
 platform/windows/os_windows.cpp:2772 - Condition "!process_map->has(p_pid)" is true. Returned: FAILED
**Steps to reproduce:**
Try one click deploy.
**Minimal reproduction project:**

**Comment by akien-mga** [comment]
Does the issue happen in 3.2.1-stable?

**Comment by HEAVYPOLY** [comment]
Checked today, it works fine on 3.2.1-stable

**Comment by avril-gh** [comment]
@akien-mga 
i can confirm that on most recent `v3.2.2.beta.custom_build.deb082e85`
(and on previous build's, because im using it all the time)
on windows 10 x64, **one click android deploy works without problems**.

@HEAVYPOLY 
Try to enter your workstation REAL IP not 'localhost' or '127.0.0.1' ,
and if you must use 'small deploy over network' then enable WIFI / Network on device.
Because even with USB, it will do most of things over USB, but will still try to use network for file system. ... _and localhost from device point of view meant it connects to self not the workstation_.

(but for pleasant work i would rather suggest to drop away USB cables and use [Wifi ADB](https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb&hl=en)
and if you use TotalCommander then [Android ADB 8.7](https://totalcmd.net/plugring/android_adb.html) for even more pleasant work. )

**Comment by HEAVYPOLY** [comment]
@avril-gh are you able to get the minimal reproduction project to one click deploy on 3.2.2 with your system?

**Comment by avril-gh** [comment]
> are you able to get the minimal reproduction project to one click deploy on 3.2.2 with your system?

@HEAVYPOLY 

of course, here it is. Tested with
Godot Engine v3.2.2.beta.custom_build.45bbcedd9
Windows 10 x64 1909 18363.778 (2020.04.28)

[one-click-android-deploy-minimal-project.zip](https://github.com/godotengine/godot/files/4555679/one-click-android-deploy-minimal-project.zip)

here is also ADB i use
[adb.zip](https://github.com/godotengine/godot/files/4555681/adb.zip)
you must have it set in your EDITOR CONFIG - `export/android/adb`

also make sure that in EDITOR CONFIG - `network/debug/remote_host`
is set to IP of your workstation where EDITOR is running,
(**it must be workstation IP like x.x.x.x** and must be reachable from debugged device,
"localhost" does not work here because from device point of view, localhost is not workstation)

here is my EDITOR SETTINGS so you can browse other settings as well,
[editor_settings-3.zip](https://github.com/godotengine/godot/files/4555699/editor_settings-3.zip)

If you use USB, and device is not in the same network with workstation
then you should uncheck menu `debug` -> `small deploy with network FS`

If you use USB, and device is in the same network with workstation
then you can use menu `debug` -> `small deploy with network FS`

When using USB - editor should start ADB and find device connected by itself. 

When using [WiFi ADB - Debug Over Air](https://play.google.com/store/apps/details?id=com.ttxapps.wifiadb&hl=en_US) (_which i would recommend, because no USB cables required_)
Editor might sometime not see this device (eg. _when its been closed and reopened_), in this case you must manually connect to it by cmd `adb connect 1.2.3.4:5555`, then quick deploy button will be back.

(But instead of playing with command line on Windows i would recommend to use Total Commander with plugin [Android ADB 8.7](https://totalcmd.net/plugring/android_adb.html) which lets not only connect to device over Wifi ADB, but do with it everything else, with easy like it could be yet another local folder on PC. copy files, get logs, make screenshots, reboot, and everything else that ADB can do. Not mention it does not require any USB cables)

![totalcommander](https://user-images.githubusercontent.com/3224132/80665190-0fec5f80-8a99-11ea-8aa6-7773a3520709.jpg)


**about bug, if there is one**
first, i see here misconfiguration
```
0 param: --remote-fs
1 param: localhost:6010
2 param: --remote-debug
3 param: localhost:6007
```
because obviously `localhost` from device point of view is not editor's workstation

then second,
if menu `debug` -> `small deploy over network FS` is supposed to emulate file system over ADB, then **no - it still trying to use network to do it**, (in my case over wifi) and when wifi is turned off,
 (or misconfigured) then this option does not work.
Still, the debugging over USB - like **debug** -> **deploy with remote debug** do works over USB

**Comment by HEAVYPOLY** [comment]
On second thought, I think this might not be an ADB problem since it seems to connect to my phone find and tries to install.  The phone screen flashes black for a moment before closing the app.  So maybe it's a problem with my project + 3.2.2 beta 2

**Comment by HEAVYPOLY** [comment]
I found the problem:  
![image](https://user-images.githubusercontent.com/24432677/81458783-222d6400-9151-11ea-9dde-06ddb4115434.png)
After removing this module, the project works.  But now I can't use payment :/
