### ISSUE TITLE
Favourites are project-specific

### ISSUE THREAD

**Issue by junkdeck** [godotengine/godot#3828]
Favourites set in the file manager doesn't carry over from project to project. Very annoying as I have to add the same directories in every new project I start.

**Comment by kubecz3k** [comment]
I'm not sure.. you are adding to favourites folders that are outside the project you are working on?

**Comment by Mooseloser** [comment]
Yeah, for instance if I add my Desktop folder as a favourite in Project1, it doesn't show up in Project2. 
It's a pretty minor thing, but still, clicking a global bookmark is much easier than navigating to C:\Users\User\Desktop every time.

Maybe I'm just misunderstanding the use of favourites though?

**Comment by kubecz3k** [comment]
Well favourites were created mostly to improve navigation within the project (it helps a lot in bigger ones), that's why it makes a lot of sense for them to be project specific. Not sure why you are using so much external folders during development.. Generally project folder should contain all your code and all your assets. Additionally all the things that you want to import to given project should be exactly one folder above your project (Generally this is the folder that should be included in version control)... here please  take a look at this piece of documentation: http://docs.godotengine.org/en/latest/tutorials/engine/project_organization.html#importing-game-folder

**Comment by Mooseloser** [comment]
I find it a lot easier to just export assets to Desktop, and import them from there. Otherwise I might as well just use Explorer to drag things into my project folder.
But yeah, I guess I just misunderstood the purpose.

**Comment by Calinou** [comment]
I can confirm this is still the case as of https://github.com/godotengine/godot/commit/584ca0f156cec64c259382895e105cf27566a987. However, as @kubecz3k, this may be desired.

**Comment by akien-mga** [comment]
This is done on purpose indeed, favorites are meant for project-specific locations.

If there's a strong demand for editor-wide favorites, it could likely be added too, but so far it doesn't seem to be a very requested feature.
