### ISSUE TITLE
GridMap editor: pick up tile from map

### ISSUE THREAD

**Issue by Wiering** [godotengine/godot#3829]
If you have a large tileset, it can sometimes be hard to find the exact tile you are looking for in the list at the left. Sometimes it would be much easier if you could select a tile you already used somewhere else in the map and start using it.

This could be done with Shift+Clicking or some other key while hovering above the tile you want to use.

**Comment by Hinsbart** [comment]
I don't know about GridMaps, but for TileMaps this is already possible. 
Use `Ctrl + Click` to select a Tile from the map, there's even `ctrl + b` to pickup a selection of tiles (whole rooms, platforms, whatever) :)

**Comment by neikeq** [comment]
Renamed the issue since TileMap already has this feature as mentioned above. The TileMap editor was also improved recently, so this feature is more visible. Moving to the 3.0 milestone where the renderer will be improved and most likely the 3D tools too (I am not sure if GridMap already has this feature though).

**Comment by djrm** [comment]
This is already possible, but you need to pick a tile in the current floor level, so this might be closed or renamed to Pick a tile from an arbitrary cell

**Comment by akien-mga** [comment]
Closing as fixed as mentioned above. If usability still needs improvement once 3.0 is released, it might be worth opening another issue specific to what needs to be done.
