### ISSUE TITLE
Make networking extendable from GDScript (NetworkedMultiplayerPeer)

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#38294]
`NetworkedMultiplayerPeer` is currently `virtual` and thus it's impossible to add new implementations or extension via GDScript.

This was brought to our attention [in this issue](https://github.com/godotengine/godot-docs/issues/3460), there's some discussion over there.

After a brief talk with Faless, while GDScript may not be the *best* tool for such extensions, but easy and fast for the user.

We should investigate the complexity of making `NetworkedMultiplayerPeer` extendable from GDScript :)

**Comment by Calinou** [comment]
This issue is probably a better fit for the Godot proposals repository.

**Comment by mrimvo** [comment]
I think we should generalize the focus of this ticket a bit more, because not only _virtual_ classes like `NetworkedMultiplayerPeer` [can't be extended](https://github.com/godotengine/godot-docs/issues/3460) in GDScript, but also ordinary classes like `WebSocketClient`. Minimalistic example for this:

```
extends Node

class MyPeer extends WebSocketClient:
	func get_available_packet_count() -> int:
		return 0

var peer = MyPeer.new()

func _ready():
	peer.connect_to_url("ws://localhost:8080")
	get_tree().set_network_peer(peer)
```

The console pushes this error about every 20ms:

```
E 0:00:01.320   get_available_packet_count: Please use get_peer(ID).get_available_packet_count to get available packet count from peers when not using the MultiplayerAPI.
  <C++ Error>   Condition "!_is_multiplayer" is true. Returned: 0
  <C++ Source>  modules/websocket/websocket_multiplayer_peer.cpp:101 @ get_available_packet_count()
```

This means, the overriden method is _not_ called but the hard coded one. So extending this class is impossible too. This might affect not only these two network classes I tried to extend, but this might be _a general problem with all engine-classes_ exposed to GDScript.

I suppose extending engine classes is something most people expect to be working. Maybe we should consider this being a bug to be fixed.

If extending engine classes is not intended to be working, maybe should give at least a warning/error in the editor if the user is trying to do so.

Thank you guys for your courage and support, I appreciate :)

**Comment by mrimvo** [comment]
While this ticket is more about _extending virtual engine classes_, I added [another ticket](https://github.com/godotengine/godot/issues/38342) primarily addressing overriding engine classes' functions.

**Comment by mrimvo** [comment]
@mhilbrunner would you mind to rename this issue to "Make virtual classes extendable from GDScript"? Because this is a general problem with all virtual classes exposed to GDScript.

**Comment by Faless** [comment]
This is fixed in `3.x` via https://github.com/godotengine/godot/pull/63163 and `master` via https://github.com/godotengine/godot/pull/63262 ,
