### ISSUE TITLE
Increasing editor window size shows incorrect graphics

### ISSUE THREAD

**Issue by verdog** [godotengine/godot#38311]
**Godot version:** 4.0 (commit abf5132a3)
**OS/device including version:** Manjaro Linux/RTX 2060
**Issue description:**
Increasing the window size of the editor does not immediately re-draw the contents. Instead, it takes ~5 seconds for the window to be redrawn.
**Steps to reproduce:**
![resize](https://user-images.githubusercontent.com/25630273/80532273-dec14180-8969-11ea-88eb-aba5059c7f7d.gif)

**Comment by Calinou** [comment]
I'm fairly sure this one has been reported already, but I'm not sure where exactly.

**Comment by verdog** [comment]
Noticed this:
![window](https://user-images.githubusercontent.com/25630273/80655735-69c73800-8a4d-11ea-9272-78b0af0a119b.gif)

Looks like the delay might be caused by a huge amount of window_changed events taking a while to be processed?

**Comment by reduz** [comment]
On Ubuntu 20.04 can't reproduce, can anyone else still reproduce it?

**Comment by opl-** [comment]
Can still reproduce it on Debian bullseye with Nvidia proprietary 440.100 driver and KDE 5.17. The issue appears to be caused by the `fpGetPhysicalDeviceSurfaceCapabilitiesKHR` and `fpCreateSwapchainKHR` calls in in [`VulkanContext::_update_swap_chain`](https://github.com/godotengine/godot/blob/4dda62f5911eefe4c0476d1e148256545e3c931e/drivers/vulkan/vulkan_context.cpp#L788) which is getting called for every `window_changed` event, as @verdog suggested. According to my timings, the `fpGetPhysicalDeviceSurfaceCapabilitiesKHR` calls take ~210ms, and the `fpCreateSwapchainKHR` take ~390ms.

I did a quick test in a [test branch](https://github.com/opl-/godot/tree/test/slow-vulkan-resizes) and discovered that while queuing up `VulkanContext::_update_swap_chain` calls does improve performance by not wasting time reallocating swapchains that will never be used, it doesn't make the windows render nicely either. It seems that by the time `VulkanContext::swap_buffers` is called Vulkan is already returning `VK_ERROR_OUT_OF_DATE_KHR`, which makes the entire frame go to waste. Still, might be worth implementing that fix?

**Comment by KoBeWi** [comment]
Can anyone still reproduce this in 4.0 alpha7?
