### ISSUE TITLE
ConfigFile should handle errors in such a way that we can continue loading when they occurs

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#3832]
**Issue description** (what happened, and what was expected):
Referring to this question: http://godotengine.org/qa/331/how-would-i-handle-errors-when-loading-using-configfile

Calinou mentioned I could post it as an issue. I hope we can implement something that allows us to "continue" looking for keys and values even after an error has occurred to prevent complete shutdown when looking for keys and values underneath a bad line. :)

Since they are posted on separate lines; perhaps it will be possible to add exception handling for each line, but allow it to continue search for key&value even when an error has occurred.

**Comment by Calinou** [comment]
Is this feature still desired? Strict error validation is usually considered to be a good thing nowadays, as long as clear error messages are displayed to the user.

We should probably look at improving ConfigFile's error messages instead (if needed).

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
