### ISSUE TITLE
Inconsistent RayCast2D collision results for different shapes

### ISSUE THREAD

**Issue by nathaniellam** [godotengine/godot#38343]
**Godot version:** 
v3.2

**OS/device including version:**
Windows 10

**Issue description:**

When testing what `RayCast2D.is_colliding()` returns true for, I found that certain shapes reported true for different situations that are inconsistent with each other.

Here is an example of the inconsistencies:
* The line segments in red represent RayCast2D nodes that report `true` for `is_colliding()`
* The line segments in green represent RayCast2D nodes that report `false` for `is_colliding()`

![raycast_inconsistencies](https://user-images.githubusercontent.com/7120015/80662923-90db3500-8a60-11ea-93a9-e5f16cc6ed8c.png)

This is a table that documents the observed behavior where:
* Entering is a raycast from outside the shape into the shape.
* Exiting is a raycast from inside the shape out of the shape.
* Internal is a raycast entirely contained in the shape.

Shape | Entering | Exiting | Internal
-|-|-|-
Rectangle | x | x | x
Circle | x |  | 
Convex Polygon | x | x | 
Concave Polygon | x | x | 
Capsule | x* | x* | x*

The big inconsistencies are:
* Rectangle collides with a ray cast that is completely inside the shape.
* Circle does not collide with exiting ray casts.
* Capsule shares both rectangle and circle inconsistencies in the parts of the shape that behavior like a rectangle or a circle.
  * See the green line at the bottom of the capsule for an example of it not colliding with exiting ray casts.
  * See the red line in the middle of the capsule for an example of it colliding with a completely internal ray cast.

**Steps to reproduce:**

**Minimal reproduction project:**

[circle_line_test.zip](https://github.com/godotengine/godot/files/4555678/circle_line_test.zip)

**Comment by avencherus** [comment]
Have had similar experiences with rays cast from inside another shape.

https://github.com/godotengine/godot/issues/35845

Have to be very careful about where they are cast from.  It would be desirable if it could resolve itself backwards or at least return a zero normal or have a method for checking if it's origin is intersecting.  It's nice to know when it's failing for this reason.

Otherwise doing a point collision test first is needed, or firing the ray from inside a collider it ignores, and won't intersect the geometry it will query.
