### ISSUE TITLE
VisualShader use only two colors of Gradient

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#38354]
**Godot version:** 3.2.2.beta1

**OS/device including version:** Linux 5.6.7-1-MANJARO

**Issue description:** The visual shader only considers the first and last colors of the gradient input. I expected all gradient colors to be used.

**Steps to reproduce:**
1. Add `ColorRect`;
2. Add `ShaderMaterial` for `ColorRect`;
3. Select `VisualShader` for `CanvasItem`;
4. Make a shader:
![изображение](https://user-images.githubusercontent.com/5412322/80697951-2d4e1780-8af3-11ea-876c-dd275310621d.png)
or just this:
![изображение](https://user-images.githubusercontent.com/5412322/80698393-dac12b00-8af3-11ea-8a0a-88062941fd4b.png)
5. Use more then 2 colors in Gradient Texture;
**Minimal reproduction project:** [debug.zip](https://github.com/godotengine/godot/files/4557597/debug.zip), see `Main.tscn`.

**Comment by Calinou** [comment]
Could you upload a ZIP archive with the minimal reproduction project?

**Comment by toby3d** [comment]
> Could you upload a ZIP archive that contains the minimal reproduction project?

[debug.zip](https://github.com/godotengine/godot/files/4557597/debug.zip)

**Comment by AlexSabourinDev** [comment]
It seems to be because you're outputting the colors as vertex colors instead of fragment colors.

![VertexInterpolation](https://user-images.githubusercontent.com/27436276/90322291-a5b0db00-df20-11ea-8694-c261b92ac42d.PNG)

This causes the colors of your gradient to only be assigned at the vertices and interpolated by the rasterizer.

If you want colors in between your vertices, you need to assign your gradient in the fragment portion of the shader.

![Fragment](https://user-images.githubusercontent.com/27436276/90322345-1f48c900-df21-11ea-9c8b-109ecbbabd44.PNG)

Which should now look correct.

![CorrectGradient](https://user-images.githubusercontent.com/27436276/90322348-2a9bf480-df21-11ea-9a42-20e7f00bd9d0.PNG)

**Comment by toby3d** [comment]
@AlexSabourinDev Oh, I saw it. Really my mistake, I'm sorry about that. I'm closing this issue.
