### ISSUE TITLE
Native crash on opening a project

### ISSUE THREAD

**Issue by Pilvinen** [godotengine/godot#38368]
**Godot version:**
Godot_v3.2.1-stable_mono_x11_64

**OS/device including version:**
Ubuntu Linux 18.04

**Issue description:**
I'm getting a native crash on opening a project. Not on running it, mind you, but simply on opening it. It happens every time. And it happens only on Linux version of Godot. On Windows version it works fine.

Console output:
https://pastebin.com/n1ZQTKPi

Mono logs:
https://pastebin.com/Vu1P14gp

I have tried deleting all import files, I have tried deleting .mono folder, and anything extra, but I haven't found a workaround.

I tested this on the older Godot 3.1.x stable branch and it worked fine there.

It would seem that `System.Memory` library might be causing the crash in Godot 3.2.x

**Steps to reproduce:**
1) Clone the project from Git:

`git clone git@github.com:starandserpent/Voxel-demo.git --recursive`

`cd Voxel-demo`

`nuget restore`

2) Start Godot.
3) Import project and open it.
4) Crash.

**Minimal reproduction project:**
https://github.com/starandserpent/Voxel-demo

**Comment by Pawlost** [comment]
I found cause of crash. It is if you include following in project.godot file:
`[mono]

profiler/enabled=true
export/include_scripts_content=true`
This doesnt affect Windows system, only Linux systems and it has nothing to do with the library.

**Comment by Pawlost** [comment]
We are moving forward with the project so I will post here the commit where the crash occured so we can merge dev to master. https://github.com/starandserpent/Voxel-demo/commit/ae8ddf0ba77cf7f21cfa180e5ae0d474ff5a7d2b

**Comment by Tobi-Mob** [comment]
Godot 3.3.3 on Linux (Ubuntu/Mint) I can open the project.

I took the master branch of your project and added the offending lines you found:
![grafik](https://user-images.githubusercontent.com/69400800/132952269-0d9251df-d753-47fe-a721-fc5db7d59f04.png)

The projekt still opens fine for me:
![grafik](https://user-images.githubusercontent.com/69400800/132952306-905863d3-199d-49f4-91e7-1a949a678690.png)

So, this may be fixed in current mono/Godot versions?

**Comment by Calinou** [comment]
Closing as resolved per @Tobi-Mob's comment.
