### ISSUE TITLE
Assign a static function result to a constant not works

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#38429]
**Godot version:**
Godot Engine v3.2.1.stable.official - https://godotengine.org
OpenGL ES 2.0 Renderer: GeForce GTX 980/PCIe/SSE2

**OS/device including version:**
Windows 10 (64x)
**Issue description:**
I try to create a constant value on my class by assignment a value created by a static function.
I guess it should work because a const variable is like a final static variable.
The Godot documentation says:

> cConstant names if they contain a script resource (MyScript if you declared const MyScript = preload("res://my_script.gd")).

So I would expect it should work with static functions to

**Steps to reproduce:**
* create a new GsScript and put this lines into
```
static func encodeModuleId(id:int, orientation:int) -> int:
	return orientation<<16|id

const DEFAULT_ID = encodeModuleId(-1, 0)
```

>  res://assets/wfc/sampler/constVar.gd:7 - Parse Error: Expected a constant expression.
>  modules/gdscript/gdscript.cpp:576 - Method failed. Returning: ERR_PARSE_ERROR

**Minimal reproduction project:**

**Comment by ThakeeNathees** [comment]
gdscript const are compile time constants, and thats why `preload()` works but not `load()` since load and every other functions (including static) are called at run time. Also not every static functions could be const folded, they may return different values at different states, consider a static function returns the current time.

**Comment by MikeSchulze** [comment]
got it, you can close it
