### ISSUE TITLE
OptionButton.grab_focus() does grab_click_focus(), grab_click_focus() does nothing

### ISSUE THREAD

**Issue by mnkylord** [godotengine/godot#38436]
**Godot version:**
Godot 3.2.1
**OS/device including version:**
Windows 10
**Issue description:**
It appears that OptionButton.grab_focus() does what grab_click_focus() is supposed to do. But grab_click_focus() does not appear to do anything. I believe that grab_focus() should grab focus without opening option menu and grab_click_focus() should grab focus and open the options menu.
**Steps to reproduce:**
Create an OptionButton, add some items.
in _ready(), add $MyOptionButton.grab_focus()
**Minimal reproduction project:**

**Comment by EricEzaM** [comment]
Can't reproduce 100%, since grab_focus() does not do what grab_click_focus() is supposed to do, but I do see a bug...

grab_focus() works as intended.
grab_click_focus() does nothing.

Note that grab_*() functionality is located in the Control class, so all controls will have this bug (theoretically), not just OptionButton.

Tested with OptionButton, CheckButton.

**Comment by mnkylord** [comment]
I thought grab_focus() will highlight the control, but not open a control like OptionButton. But in my case, OptionButton menu opens with grab_focus(). To me, it seems like grab_click_focus() should open the menu of OptionButton, grab_focus() should set the OptionButton highlighted.

**Comment by EricEzaM** [comment]
You are correct, I am just saying I can't reproduce the behaviour when I try to (but I can see that grab click focus does nothing) . Could you post a zip file with the minimum set up to reproduce the bug?

**Comment by EricEzaM** [comment]
Ok so I think I figure it out at least partially. The behaviour is quite strange, but I have stepped through the C++ to see what was happening.

As per the docs, it says
```gdscript
func _process(delta):
    grab_click_focus() #when clicking another Control node, this node will be clicked instead
```

So I added this to one of the OptionButtons... I just made it poll every frame and call this. As per the docs... what is expected happens. It redirects all clicks on the control to that option button. Click anywhere, and that option button shows it's popup. Now essentially what happens is that the viewport says 'hey, I got a click... and also a control I have registered said that it grabs clicks, so I'm going to redirect that click'. That's why it works with polling. For it to work on _ready(), you would need to click on the exact frame that it is called grab_click_focus() (not really possible, of course).

You can see this in action when you add a normal Button and hook up "pressed" to call OptionButton2.grab_click_focus(). You still need the other OptionButton1 polling each frame for this to work. When you click the Button, this is what happens:

1. The viewport detects the user's click and goes, "hey, I should redirect this to OptionButton1".
2. The viewport then detects _that_ 'generated' click, and redirects that to OptionButton2!
3. Both option buttons are clicked in the same frame, opening both.

Here is where that check happens of where it should redirect to.
https://github.com/godotengine/godot/blob/2435d4bdb93c65465cfddd027bfaa02b9ca60c8d/scene/main/viewport.cpp#L2635-L2646

If the functionality it wanted (could be useful), I think it is possible add an else statement onto the end of this if, and handle the case where we just want to do a click via code... without redirecting an existing user click.

**Comment by mnkylord** [comment]
Thank you so much for looking into this and explaining what grab_click_focus() was intended to do. I will find some work around in my project.
