### ISSUE TITLE
Sometimes exported script variables are not present in inspector

### ISSUE THREAD

**Issue by p10tr3k** [godotengine/godot#38469]
**Godot version:**
v3.2.2.rc.custom_build.36a30f681

**OS/device including version:**
Windows 10

**Issue description:**
Sometimes exported script variables are not displayed in inspector for root scene node. I cannot reproduce it. It just happens sometimes.
It may be related with having class_name in script, because when it happens I have to remove class_name, then save file and add again class_name, to make the variables visible again.

**Steps to reproduce:**
It can be related to class_name in root scene node script.

**Comment by Calinou** [comment]
@p10tr3k Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
