### ISSUE TITLE
Tween returns null for non-existing properties

### ISSUE THREAD

**Issue by mnn** [godotengine/godot#38473]
**Godot version:** 3.1.1

**OS/device including version:** Manjaro (Linux 64b)

**Issue description:**

Tween node returns `null` for all non-existing properties/fields. Same issue is with `in` operator (got bitten by this just an hour ago). I don't see this behaviour mentioned in docs.

**Steps to reproduce:**

```gdscript
	print("alshdlckvjhxlkdjsfg" in $Tween) # True
	print($Tween.alshdlckvjhxlkdjsfg) # Null

	print("alshdlckvjhxlkdjsfg" in $Sprite) # False
	print($Sprite.alshdlckvjhxlkdjsfg) # crashes with "Invalid get index"
```

**Minimal reproduction project:**
Add a tween and a sprite to a new project and code above to `_ready`.

**Comment by bojidar-bg** [comment]
The issue seems to lie in those lines (in `Tween::_set` and `Tween::_get`):

https://github.com/godotengine/godot/blob/1c23a0cc7f879774f56404378db1bf86979e42d1/scene/animation/tween.cpp#L136
https://github.com/godotengine/godot/blob/1c23a0cc7f879774f56404378db1bf86979e42d1/scene/animation/tween.cpp#L152

There should either be an `else { return false; }` clause added, or the `return true;`-s should be moved within the `if`/`else if`-s above.
