### ISSUE TITLE
Export resources without dependencies

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#3851]
I was thinking the option of exporting without dependencies should be implemented.
I wanted to have to .pcks one with hd res and another with sd res. Now let's say the game is put together with an hd res. if i try to export a pck with only the sd stuff(and the appropriate script to load the right texture given the context), the pck export actually has both the hd -and sd versions defeating the purpose of such, because the hd versions are considered a dependency.

Generally having full control over your project is beneficial, so i don't see why not.
Along with the option of selecting folders and not only files on export(which i already mentioned on another feature request), i think this one would further optimize the exporting system.
In fact my suggestion is that "include dependencies" should be a checkbox in the "export selected resources" tab.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
