### ISSUE TITLE
Missing functions in undo_redo class

### ISSUE THREAD

**Issue by TypeOverride** [godotengine/godot#38518]
There are no 

- get_action_count() or get_actions_count() 
- get_current_action()

methods in the UndoRedo class.

But they are needed if you want to use the class in your own project. I know its more for editor stuff made (internally). But when you want to use the class, this methods are missing, so you can visualize undo redo buttons with the count of actions and on which action index he is already.

```
int UndoRedo::get_action_count() const {
	return actions.size();
}

int UndoRedo::get_current_action() const {
	return current_action;
}
```

**Comment by MightyPrinny** [comment]
If you want to use in a game first make sure it works when you export the game, editor classes are only available in the editor.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
