### ISSUE TITLE
Join method for PackedStringArray is not exists

### ISSUE THREAD

**Issue by toby3d** [godotengine/godot#38526]
**Godot version:** 112884de
**OS/device including version:** Linux 5.6.7-1-MANJARO
**Issue description:** After renaming class `PoolStringArray` (Godot 3.0+) to `PackedStringArray` (Godot 4.0+), the `join` method was lost.
**Minimal reproduction project:**

```gdscript
const uppercase: String = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
const lowercase: String = "abcdefghijklmnopqrstuvwxyz"
const alphabetic: String = uppercase + lowercase
const numeric: String = "0123456789"
const alphanumeric: String = alphabetic + numeric

# Generate fixed-sized string with charset symbols
func string(length: int, charset: String = alphanumeric) -> String:
	randomize()

	var output: PackedStringArray

	while output.size() < length:
		output.append(charset[randi() % charset.length()])

	return output.join("") # The method "join" isn't declared on base "PackedStringArray"
```

**Comment by kuruk-mm** [comment]
As you said, this issue is from the rename of PoolStringArray to PacketStringArray, when reduz changed PoolVector to Vector on #36311

I read #36311 and see the changed syntax on the Engine for the joins on the code is:
 `String(delimiter).join(parts)`

e.g in your case: `String("").join(output)`

So in a few minutes I'll make a PR with this change to give the ability to join a PacketStringArray to String
