### ISSUE TITLE
get_peer_address/port does not work

### ISSUE THREAD

**Issue by NuxaHD** [godotengine/godot#38537]
**Godot version:**
3.2.1
**OS/device including version:**
Windows 10
**Issue description:**
I use NetworkedMultiplayerENet for Multiplayer

An error occurs when two clients are running on the same device

![Unbenannt](https://user-images.githubusercontent.com/64705411/81299248-3a7c8080-9076-11ea-9761-981f4a9928f2.PNG)

am I doing something wrong? or is this function only for the serverside?

**Steps to reproduce:**
use the NetworkedMultiplayerENet 

(network_peer_connected and network_peer_disconnected)
> func _player_disconnected(id):
	print("The player "+ str(players[id].name) + " ("  +str(get_tree().get_network_peer().get_peer_address(id))+ ":" +str(get_tree().get_network_peer().get_peer_port(id))+") left the server")

**Comment by Faless** [comment]
As the error mention, only the server can get the address and port of other clients. This is due to the client/server architecture of the ENet implementation in Godot which is not P2P, and does not, by default, send those information to the clients (you can do that manually if you so desire, by sending an RPC from server to other clients with those information).
