### ISSUE TITLE
Godot Mono C# Warning says you can't export to iOS yet

### ISSUE THREAD

**Issue by Davoleo** [godotengine/godot#38627]
**Godot version:**
Mono 3.2.1

**OS/device including version:**
Windows 10 1909

**Issue description:**
The warning message says you can't export to iOS while as #36979 says, iOS support was added on the 3.2 update
![image](https://user-images.githubusercontent.com/24458276/81500545-1e294f80-92d3-11ea-9d69-78e4abbc0fb8.png)

**Steps to reproduce:**
Open Godot Mono 3.2.1
and then open any kind of project to make the C# warning appear

**Comment by LinuxUserGD** [comment]
Actually the PR was merged against the `3.2` branch which could also mean that it would be only available on next 3.2.2 release.

**Comment by Davoleo** [comment]
oh, didn't know that, I thought 3.2 meant it was going to be released on 3.2.0, sorry for the trouble
feel free to close this issue if it's not released yet

**Comment by neikeq** [comment]
iOS support is available starting with version 3.2.2. But apparently we didn't remove iOS and HTML5 from the exceptions yet so this issue is still valid: https://github.com/godotengine/godot/blob/6ab92464bc6356f3342c3efd1fc1bb1a5e4467d5/modules/mono/editor/GodotTools/GodotTools/GodotSharpEditor.cs#L424
