### ISSUE TITLE
Godot Engine Crashes when creating OpenGL ES 3.0 project

### ISSUE THREAD

**Issue by GDJason12** [godotengine/godot#38652]
**Godot version:**
Latest *stable version* as of May 2020

**OS/device including version:**
Linux Kernel v4.4 | Ubuntu 16.04.3 Unity 7.4.5 | Acer Chromebook 11 using crouton

**Issue description:**
When i open the Godot project manager, and i create a project in GLES 3.0 it gives up. 
Checked GL drivers:

 ```glxinfo | grep "OpenGL"```

"Suspected Driver":

```OpenGL ES GLSL ES 3.00```

**Steps to reproduce:**
1. Open Godot
2. Create a GLES 3.0 project
3. Edit
4. Expect a Crash

```Note: i suspect that this occurs to other chromebook/linux users```

**Minimal reproduction project:**

**Comment by lawnjelly** [comment]
By latest do you mean latest master? If so that is 4.x branch and only vulkan is implemented so far.

**Comment by Ev1lbl0w** [comment]
Can you also provide a stacktrace, if there's one?

**Comment by GDJason12** [comment]
> Can you also provide a stacktrace, if there's one?

Sure, right here 
![scrot](https://user-images.githubusercontent.com/44308126/82185349-ee171900-989d-11ea-8d88-538cc2db6f1c.png)

**Comment by GDJason12** [comment]
I'm using 3.2.1 and i mean by latest i mean by the *stable* versions

**Comment by Ev1lbl0w** [comment]
Huum, that looks like an issue with the driver itself. I'd say try these:

- Get a debug build of Godot from [here](https://github.com/Calinou/godot-debug-builds/releases), and use this version for all the instructions below.

- Try launching the project directly like this (it might give more info where it is exactly crashing):

`godot -e --path /path/to/project/`

- If it still doesn't work, try forcing Godot to use GLES2:

`godot --video-driver GLES2 -e --path /path/to/project/>`

If it works, great; GLES3 will be deprecated when 4.0 rolls out anyways.

If it still crashes, but this time shows a complete stacktrace, please post it here. Otherwise, it might be best to report this bug to the [driver upstream](https://gitlab.freedesktop.org/mesa/mesa) instead.

**Comment by akien-mga** [comment]
That's a driver bug indeed. Ubuntu 16.04 is fairly old and its Mesa version outdated too. I would suggest upgrading to a newer Ubuntu version to get the latest Mesa that they provide.

**Comment by akien-mga** [comment]
Intel Bay Trail should only have support for up to OpenGL 3.0 on older Mesa version: https://feedback.wildfiregames.com/report/opengl/device/Intel(R)%20Bay%20Trail

But I think it might be among those that were eventually downgraded to OpenGL 2.1 only in later Mesa versions, as their GL 3.0 support was too broken.

Godot should normally be able to abort gracefully if you try to open an OpenGL 3.3 (GLES3) project on a driver that doesn't support it, but I guess the older Mesa driver for this older low-end chipset is too broken and it crashes.

I think there's nothing we can do to prevent it sadly. Try an upgrade to a newer Mesa, but most likely you should stick to OpenGL 2.1 (GLES2) on this hardware.
