### ISSUE TITLE
Text editor extensions for the plugins API

### ISSUE THREAD

**Issue by ZippoLag** [godotengine/godot#3869]
It'd be nice to be able to add behaviour that we've grown to love from other editors in plugins, such as "zen coding", highlighting of all occurences of the currently selected word, etc.

I'm not entirely sure what the best approach for coding such features would be (perhaps it'd be worth it to take a look at how Brackets.io plugins are coded), but I'm guessing we'd need all kinds of access to the text editor window..

Apoligies for being too vague (and/or if such access is already available).

**Comment by kubecz3k** [comment]
+1 Would love to try to write some parts of vim style movement

**Comment by kubecz3k** [comment]
+1 Would love to try to write some parts of vim style movement

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
