### ISSUE TITLE
HDR ViewportTexture requires at least USAGE_3D_NO_EFFECTS

### ISSUE THREAD

**Issue by The5-1** [godotengine/godot#38702]
**Godot version:**
3.2.2 beta2 win64

**OS/device including version:**
Windows 10 1903

**Issue description:**
In order for a ViewportTexture to be sampled as HDR I must not only have `HDR = true` in the viewport but also have at least `usage = USAGE_3D_NO_EFFECTS`. Sampling the ViewportTexture in another shader with 2D usage results in [0.0,1.0] ranges.
The `disable 3d` flag has no influence (though its intent is not clear to me anyway).

**Steps to reproduce:**
Create a Viewport with a shader outputting a HDR value. 
Use the resulting ViewportTexture in another shader and sample the value.
Change the producing viewports modes.

**Minimal reproduction project:**
Try switching the `Viewport` Node in the project between 2D and 3D usage modes.
[HDR_Viewport_Bug.zip](https://github.com/godotengine/godot/files/4618167/HDR_Viewport_Bug.zip)

![Godot_HDR_Bug](https://user-images.githubusercontent.com/22944373/81740304-0c93a380-949d-11ea-904b-cc99160adcc0.JPG)

**Comment by hana-lys** [comment]
I don't understand your problem,
Did it the range of the Sampling of the ViewportTexture in  another shader or
need to check hdr = true and usage = 3D ?

**Comment by mrushyendra** [comment]
The issue seems to be in the following [code:](https://github.com/godotengine/godot/blob/7ccb146a55edc41a9dd14c10efb8dc8f4b87f14e/drivers/gles3/rasterizer_storage_gles3.cpp#L7115-L7139)

`

    bool hdr = rt->flags[RENDER_TARGET_HDR] && config.framebuffer_half_float_supported;
	//hdr = false;
	if (!hdr || rt->flags[RENDER_TARGET_NO_3D]) {

		if (rt->flags[RENDER_TARGET_NO_3D_EFFECTS] && !rt->flags[RENDER_TARGET_TRANSPARENT]) {
			//if this is not used, linear colorspace looks pretty bad
			//this is the default mode used for mobile
			color_internal_format = GL_RGB10_A2;
			color_format = GL_RGBA;
			color_type = GL_UNSIGNED_INT_2_10_10_10_REV;
			image_format = Image::FORMAT_RGBA8;
		} else {

			color_internal_format = GL_RGBA8;
			color_format = GL_RGBA;
			color_type = GL_UNSIGNED_BYTE;
			image_format = Image::FORMAT_RGBA8;
		}
	} else {
		color_internal_format = GL_RGBA16F;
		color_format = GL_RGBA;
		color_type = GL_HALF_FLOAT;
		image_format = Image::FORMAT_RGBAH;
	}
`

In particular, in this [line](https://github.com/godotengine/godot/blob/7ccb146a55edc41a9dd14c10efb8dc8f4b87f14e/drivers/gles3/rasterizer_storage_gles3.cpp#L7118), the '||' needs to be changed to '&&' , since we want to use 16 bits if HDR is enabled, regardless of the Usage value.

If that seems fine, I can make the PR soon.

**Comment by akien-mga** [comment]
Fixed by #39032.
