### ISSUE TITLE
Proposal for looping and audio sample default behavior.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#3872]
Right now to loop the sample two steps need to be taken now:
1. setting the loop at import sound setting
2. setting Loop Format, Loop Begin and Loop End at SampleLibrary sample edit properties Indicator panel.

It is not intuitive at all. Most new users probably expect that after the first step (setting the loop during sample import), the sample will be already looped and will play from the very start to the very end and again. After all they set it to be looped, right?
It would be better if, after checking the loop option in sample import settings, the sample by default be set to Loop Format = Forward, Loop Begin = 0, Loop End = 1000000000. It's what is expected most of the times as a sound loop.
Of course other settings and their editing should still be available in Inspector after pressing the pencil icon in SampleLibrary, if someone wants to change anything.

**Comment by Zylann** [comment]
I'm having issues with this too so I'll add my feedback:

Before I discover this, I expected to be able to loop a sample just setting the loop format in the SampleLibrary. Actually this has to be done at import time too... why? 
I am currently confused going back and forth import dialogs and sample libraries just to make sounds loop properly, because I make mistakes when importing the sound too (normalization, mono/stereo, Godot having to be restarted for changes to take effect, maybe bugs?).

Also, looping doesn't affects the samples, it should be a play setting, so the behaviour can be configured at one single place and work with fewer steps.

**Comment by akien-mga** [comment]
The audio server will be reworked for 2.2.

**Comment by akien-mga** [comment]
As the audio server was fully reworked for 3.0, and the import workflow too, I suppose that this issue doesn't apply as is anymore.

You might still have suggestions regarding how to improve the workflow in 3.0+ though, but I'd suggest to open a new issue for this if relevant, for better visibility.
