### ISSUE TITLE
StaticBody2D Constant Linear Velocity not affect the static KinematicBody 2D

### ISSUE THREAD

**Issue by firecloud888** [godotengine/godot#38721]
**Godot version:**
3.2

**OS/device including version:**
window 10

**Issue description:**
Put a KinematicBody2D as player on a StaticBody2D as a conveyor which has non-zero constant linear velocity, it affect the player when it moves, but if the player not move at start, it just stay there. If you give a jitter speed to player, the player start moving but that will cause player slide on a slope

**Steps to reproduce:**
http://kidscancode.org/godot_recipes/physics/conveyor_belt/
Just change the rigid body to kinematic body 2d

**Comment by madmiraal** [comment]
This is the expected behaviour. `KinematicBodies` are meant to be user-controlled. The `move_and_slide()` and `move_slide_with_snap()` functions are utility functions that automatically update the `KinematicBody`'s velocity depending on the angle of the surface and the velocity of the body that the `KinematicBody` collides with. If you're not using one of these functions in the `_physics_process()` loop, your `KinematicBody` won't and shouldn't move.
