### ISSUE TITLE
Building release export template with MSVC 2019 fails in GDNative module.

### ISSUE THREAD

**Issue by bruvzg** [godotengine/godot#38748]
**Godot version:**
master, 00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8

**OS/device including version:**
Windows 10, MSVC 2019 (19.25.28614) x86-64.

**Issue description:**
Release build with MSVC fails, with the following warnings in all GDNative module `godot_variant_as_packed_XXX_array` functions (on the `*dest = *self;` line):

```
warning C4789: buffer 'raw_dest' of size 8 bytes will be overrun; 8 bytes will be written starting at offset 8
```

Relevant code (same for all Packed*Arrays):
https://github.com/godotengine/godot/blob/00949f0c5fcc6a4f8382a4a97d5591fd9ec380f8/modules/gdnative/gdnative/variant.cpp#L393-L400

Used build command: `scons p=windows target=release tools=no optimize=speed use_lto=yes debug_symbols=no -j20 extra_suffix=msvc`.

Adding cast (e.g. `*dest = (PackedByteArray)*self;`) to these lines seems to remove this warning, but I'm not sure this assignment is necessary at all. Same code for the other types, like `Dictionary` and `Array` do not have it. Shouldn't it be handled by `self->operator PackedByteArray()` on the previous line?

3.2 branch have the same code (but for the old PoolVectors), and do not give these warnings.

**Comment by pouleyKetchoupp** [comment]
It seems the problem here is that `godot_packed_byte_array` type is not large enough to handle `PackedByteArray`, which is the size of a `Vector`.

GDNative assumes packed arrays are the size of a pointer:
https://github.com/godotengine/godot/blob/d999071edf137fa8b125c9aa057e3936fe54aed0/modules/gdnative/include/gdnative/pool_arrays.h#L42-L49

But `Vector` is a little bit more due to the write proxy:
https://github.com/godotengine/godot/blob/d999071edf137fa8b125c9aa057e3936fe54aed0/core/vector.h#L56-L64

So it might be fine to remove the `*dest = *self;` line (it does seem like a leftover from old code), but the issue this warning is pointing out is real. `godot_packed_byte_array` should be updated to reflect the correct size, same with other packed array types.

**Comment by bruvzg** [comment]
Yep, looks like size was not updated when vector was changed from `PoolVector` (which was a single pointer internally) to the `Vector<T>`. https://github.com/godotengine/godot/blob/f5a3d34593cbcd428fcc2f93d3d0de1b66906fcd/core/pool_vector.h#L83

Might be worth adding size checking `static_assert`s for the GDNative type.
