### ISSUE TITLE
Occasionally Unresponsive Export Variables in Editor [godot 3.2.1 mono]

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#38761]
**Godot version:** Godot 3.2.1 [Mono}

**OS/device including version:** Windows 10 1909

**Issue description:** Whenever I create an export variable (especially fields like, int, float) in C#, the variable field in the editor occasionally becomes unresponsive. I don't know whether this bug or issue is only present in the Mono build or not, but I have been using the Mono variant and noticed it once in a while. Whenever the bug or issue appears, I can no longer select the field to type in new value or drag to change the value.

**Steps to reproduce:** Create a node, attach a C# script, create an export variable of types like int or float (I have noticed this bug for this datatypes especially) and then try to modify the value of the variable from the editor. I am not sure how frequently this bug will appear (or whether the bug will appear at all) on your pc. I am not sure whether this bug will affects other datatypes or not, I have not checked them out.

**Minimal reproduction project:** This may appear on any projects, but I have been doing small tutorial type projects.

**Comment by Chaosus** [comment]
Corrupted and broken export variables in Mono is known problem which has been reported several times in different issues. (see https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+export+variables+label%3Atopic%3Amono+). I've closed this issue since the 3.2 version of Godot is old and 
no longer supported + the author is deleted from Github and cannot answer anyway.
