### ISSUE TITLE
Automatically duplicate a dictionary

### ISSUE THREAD

**Issue by rdmtt** [godotengine/godot#38792]
**Godot version:**
3.2.1

**Issue description:**
You need to use the _.duplicate(true)_ function in order to copy the dictionary instead of referencing to it.
With every other value type, it is done automatically (it copies the value instead of referencing the variable itself).

Now, if I want to copy part of the dictionary and make changes to it, the BOTH dictionaries are changed. This has caused me a lot of confusion because I keep forgetting that this one type of value for some reason behaves differently then all the others.

**Steps to reproduce:**
Create two dictionaries --> assign one to the other --> change one of them --> see the other one change as well.
If you repeat those steps with any other type of value (string, integers, etc.) you won't see this behavior.

**Minimal reproduction project:**
[dict.zip](https://github.com/godotengine/godot/files/4639167/dict.zip)

I know this behavior might be intended but it's not clearly stated anywhere that there is a variable exception such as this. The first time it happened, I discovered this behavior by accident after many, many hours of confusion.

**Comment by Calinou** [comment]
This is not a bug, but a design decision (this helps decrease memory usage). The same also applies to Arrays. As far as I know, there are no plans to change this for Godot 4.0.

Note that PoolArrays are passed by value (instead of reference), though. (They were renamed to PackedArrays in the `masteer` branch).

> I know this behavior might be intended but it's not clearly stated anywhere that there is a variable exception such as this. 

This is already mentioned in the [Array](https://docs.godotengine.org/en/latest/classes/class_array.html) class description, but not yet in the Dictionary class description. I'll add it ASAP.

**Comment by pycbouh** [comment]
> This is already mentioned in the Array class description, but not yet in the Dictionary class description.

To be fair, it is explicitly stated in the [GDScript basics doc](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html).

![image](https://user-images.githubusercontent.com/11782833/82141480-b0cf6e80-983e-11ea-98fa-da6a31a25477.png)
