### ISSUE TITLE
Can't set FileDialog window title

### ISSUE THREAD

**Issue by Barugon** [godotengine/godot#38896]
**Godot version:**
3.2.1 stable

**OS/device including version:**
Fedora 32 (64 bit)

**Issue description:**
I set Window Title for FileDialog to "Select Log Folder" but it always comes up "Open a Directory" and my change ultimately gets reverted to "Open a Directory".

**Steps to reproduce:**
Create a FileDialog, change the window title and then show the dialog.

**Comment by Barugon** [comment]
If I set the title programatically, that works.

**Comment by dominiks** [comment]
If you want to give the FileDialog a custom title you have to disable the property ``Mode overrides Title``. Using the ``window_title`` property in code after the FileDialog has been created works since it has already received its automatic title and won't overwrite your change again.

I don't think this is a bug but maybe a documentation issue. The FileDialog could also detect that the ``window_title`` has been set by the user and automatically refrain from overriding it with the current mode.

**Comment by Calinou** [comment]
Related to #39258?

**Comment by dominiks** [comment]
I don't think so. #39258 looks like an issue with the editor itself and its handling of translations.

**Comment by Barugon** [comment]
> If you want to give the FileDialog a custom title from the editor you have to disable the property `Mode overrides Title`. Using the `window_title` property in code after the FileDialog has been created works since it has already received its automatic title and won't overwrite your change again.
> 
> I don't think this is a bug but maybe a documentation issue. The FileDialog could also detect that the `window_title` has been set by the user and automatically refrain from overriding it with the current mode.

Thanks. I should've seen this. Closing the issue.

**Comment by Calinou** [comment]
We should still add the missing documentation, so reopening it as a reminder.

**Comment by akien-mga** [comment]
Fixed by #39322.

**Comment by follower** [comment]
While the documentation is a good addition, the behaviour does seem "unintuitive" at best and doesn't really seem to serve any purpose--so I'd still consider this a bug.
