### ISSUE TITLE
Can't get direct space state while game is paused in Godot Physics

### ISSUE THREAD

**Issue by MightyPrinny** [godotengine/godot#38909]
**Godot version:**
3.2.2 beta 2 mono

**OS/device including version:**
MXLinux 19 64bits

**Issue description:**
When Godot Physics are used and the game is paused the direct space cannot be obtained using get_world().direct_space_state, this works in bullet (it doesn't update but you can still access it).

**Steps to reproduce:**
pause game and try to get the direct space state.

**Comment by madmiraal** [comment]
I think the problem lies with Bullet physics not Godot physics. When the game is paused, physics should be paused too.

The problem is Bullet physics does not control access to the space state, which Godot physics does. This can be seen by the fact that Bullet physic's space state is also available from outside the _physics_process() loop, which it shouldn't be.

The documented behaviour is that direct_space_state should return `null` when it's not available, which is what you're seeing.

**Comment by MightyPrinny** [comment]
it would be nice if both had the same behavior, I can still store the result of the last call to get_direct_space_state() that didn''t return null so I can still use it in godot physics while the game is paused if I want to .
