### ISSUE TITLE
Add support for Android scoped storage requirements

### ISSUE THREAD

**Issue by HEAVYPOLY** [godotengine/godot#38913]
**Godot version:**
3.2.2 Beta 2
**OS/device including version:**
Android
**Issue description:**
Try to save image, get error "No permission grants found for com.google.android.apps.photos"

Read/Write external storage permssions are enabled in Android Export options.  The same code worked in 3.2.1 stable.
**Steps to reproduce:**

**Minimal reproduction project:**
Logcat:
05-20 21:35:58.903 29344 29554 I godot   : Loaded Strokes Drawn
05-20 21:35:57.777  1423  4285 W UriGrantsManagerService: No permission grants found for com.google.android.apps.photos
05-20 21:35:59.052  1423  4285 D ConnectivityService: filterNetworkStateForUid() uid: 10209, pid: 18529
05-20 21:35:59.052  1423  4285 D ConnectivityService: filterNetworkStateForUid() uid: 10209, pid: 18529, networkInfo: [type: WIFI[], state: DISCONNECTED/BLOCKED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
05-20 21:35:59.052  1423  4285 D ConnectivityService: filterNetworkStateForUid() uid: 10209, pid: 18529
05-20 21:35:59.053  1423  4285 D ConnectivityService: filterNetworkStateForUid() uid: 10209, pid: 18529, networkInfo: [type: WIFI[], state: DISCONNECTED/BLOCKED, reason: (unspecified), extra: (none), failover: false, available: true, roaming: false]
05-20 21:35:59.137  1423  4285 W UriGrantsManagerService: No permission grants found for com.google.android.apps.photos
05-20 21:35:59.137  1423  4937 W UriGrantsManagerService: No permission grants found for com.google.android.apps.photos
05-20 21:35:59.195 29344 29554 E godot   : **ERROR**: Can't save PNG at path: '/storage/emulated/0/Pictures/HEAVYPAINT_EXPORT/asd.png'.
05-20 21:35:59.195 29344 29554 E godot   :    At: drivers/png/resource_saver_png.cpp:58:save_image() - Condition "err" is true. Returned: err

**Comment by HEAVYPOLY** [comment]
Did some digging around, could it have something to do with this?  
[https://developer.android.com/training/data-storage/compatibility]
![image](https://user-images.githubusercontent.com/24432677/82526185-30cc3180-9ae8-11ea-97f4-c062aae1ce5a.png)

**Comment by m4gr3d** [comment]
@HEAVYPOLY you're most likely running into [scoped storage](https://developer.android.com/training/data-storage#scoped-storage) issues. 

The reason you're seeing that is because `3.2.2` has [`targetSdk` set to `29`](https://github.com/godotengine/godot/blob/9aeb9ea826cb7ae939fe25366368e42fc85b52fa/platform/android/java/app/config.gradle#L5), while `3.2.1` has [`targetSdk` set to `28`](https://github.com/godotengine/godot/blob/b0eca5828ccd3a5c07b77e82e567c45937de9056/platform/android/java/app/config.gradle#L5) and the new `scoped storage` restriction starts at API level `29`.

As mentioned in the [scoped storage](https://developer.android.com/preview/privacy/storage#maintain-compatibility-android-10), you can temporarily restore the previous behavior by using the `requestLegacyExternalStorage` attribute, but in the long term, you should probably start migrating to the new way of using storage.

**Comment by HEAVYPOLY** [comment]
Thanks for the info.  I'm searching for requestLegacyExternalStorage in Android export options but don't see it, where can I find this setting?  

Also, what is the proper way to save/load files for the future?

![image](https://user-images.githubusercontent.com/24432677/83066566-16c7ad00-a01a-11ea-9122-8196324cdcb1.png)

**Comment by m4gr3d** [comment]
@HEAVYPOLY I didn't realize you were using an internal Godot method to save the file.

@akien-mga Now that I have a fuller understanding of the issue, it's quite tricky as we possibly have a wide surface area to investigate/fix (pretty much any logic that write to file) and we only have until [August 3, 2020](https://support.google.com/googleplay/android-developer/answer/113469#targetsdk) since API level `29` will be required starting then.

A first approach would be to include the `requestLegacyExternalStorage` attribute by default to keep the current behavior. This will give us about a year to update the internal file logic before we have to switch to API level `30`.

**Comment by HEAVYPOLY** [comment]
Sounds good, thank you.  Is there a better way I should be handling all this?  Is there a way to access native android share popup?

**Comment by m4gr3d** [comment]
@HEAVYPOLY It's hard to say given I'm not familiar with the logic from your app.

Using `scoped storage` properly would require some familiarity with Android and its filesystem. If you have that experience, then you could write your own plugin that stores files properly, and use it from gdscript instead of using the Godot provided APIs.

Otherwise, the alternative is to wait until we clean those APIs.

**Comment by HEAVYPOLY** [comment]
Ok, I will wait for the legacy external storage fix.  Thank you!

**Comment by akien-mga** [comment]
> A first approach would be to include the `requestLegacyExternalStorage` attribute by default to keep the current behavior. This will give us about a year to update the internal file logic before we have to switch to API level `30`.

I think we should do this for now, especially as it will be needed for older stable branches like `2.1` which also needs a 2.1.7 update targeting API level 29 (#41300).

We should still work to implement the new scoped storage access ASAP, but this should be a good stopgap measure for 3.2.3 and 2.1.7 (and 3.1.3 if I make one).

**Comment by m4gr3d** [comment]
> > A first approach would be to include the `requestLegacyExternalStorage` attribute by default to keep the current behavior. This will give us about a year to update the internal file logic before we have to switch to API level `30`.
> 
> I think we should do this for now, especially as it will be needed for older stable branches like `2.1` which also needs a 2.1.7 update targeting API level 29 (#41300).
> 
> We should still work to implement the new scoped storage access ASAP, but this should be a good stopgap measure for 3.2.3 and 2.1.7 (and 3.1.3 if I make one).

@akien-mga this has already been done by #39103.

The issue remains open to track the full implementation for scoped storage.

**Comment by akien-mga** [comment]
Thanks, I cherry-picked the change for 2.1.7: 11fba315ec.

**Comment by m4gr3d** [comment]
@HEAVYPOLY What's the api you were using to save the images and how are you generating the path where they are being saved?
In addition, do the images your app generates need to remain on the device even if your app is uninstalled?

**Comment by HEAVYPOLY** [comment]
here is my save script, it uses standard save_png()
I get the user pictures path with OS.get_system_dir().
The images do need to stay on device after uninstall, and using this method they do (since they are in pictures directory).

On iOS though I don't have access to pictures directory so everything is saved to user folder unfortunately

```gdscript
func save_layer_png(layer, path, merge = false):
    var ld = GB.get_layer_data_by_name(layer.name)
    if merge == false:
        if GB.get_layer_data_by_name(layer.name).visible == false:
            print("SKIPPING SAVE LAYER PNG, INVISIBLE")
            yield(get_tree(),"idle_frame")
            return
    layer.Export.rect_size = SM.canvas.size
    layer.V.size = SM.canvas.size

    layer.Export.modulate = layer.modulate
    layer.Export.material = layer.material


    layer.V.render_target_update_mode = Viewport.UPDATE_ONCE
    yield(get_tree(),"idle_frame")
    yield(get_tree(),"idle_frame")
    var img:Image = layer.V.get_texture().get_data()
    GB.Status.text = str("RENDERING LAYER ", layer.name.to_upper())
#    print("APPENDING ", img)
#    layerpngs.append(img)
    if SM.user_prefs.batch_export_layers:
        var img_path = path + "/" + str(SM.canvas.layers.find(ld)+1) + " " + ld.name + ".png"
        img.save_png(img_path)
        print("SAVING PNG BATCH ", img_path)
#        img.save_png(path + "/" + str(layer.get_position_in_parent()+1) + " " + layer.name + ".png")
    layer.V.render_target_update_mode = Viewport.UPDATE_DISABLED
```
