### ISSUE TITLE
Ability to create plugin that is based on a scene

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#3895]
Currently if I want to create new node with plugin api I need to use `add_custom_type()` function to provide script that will be the base for a node-plugin. What I would consider the most convenient way to create some types of node-plugins would be the ability to point to a whole scene instead. 
Please note that I haven't used plugin system a lot yet and it might be possible that what I need is already there (in this case please show me the way :))

**Comment by Hodes** [comment]
Well @kubecz3k, as far as i'm using Plugin System, I would do something like: 
- Place the scene together with the plugin files. Preferred with new text based format .tscn or .xscn
- Create a node script for the custom type. That should extends at least Node or deeper in the hierarchy
- Declare the variable (the_scene) that will hold the wanted scene to be "custom_type", then preload("the/scene.tscn")
- In the _enter_tree(): do something like this 
```gd 
func _enter_tree():
    the_scene.instance()
    add_child(the_scene)
```

And then you should have your custom node to have an entire tree of the 'scene.tscn'.

As far as I know, the plugin custom type will always be linked to a script, then you will not have a clear custom node with script slot free.

Well, I hope I have helped with something, or someone can correct me if I'm wrong. Thanks !

**Comment by kubecz3k** [comment]
@reduz according to our irc conversation, this issue is about new function inside `EditorPlugin` that's similar to  `add_custom_type(Name, ParentType, Script,  icon)` but take `instanced scene` as a third argument instead of `Script.`

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
