### ISSUE TITLE
3.2.2beta3 Cannot find dotnet CLI executable. Fallback to MSBuild from Mono

### ISSUE THREAD

**Issue by van800** [godotengine/godot#38985]
3.2.2beta3
MACOSX

**Issue description:**
Create a new empty project, add one C# script.
Set Build tool dotnet CLI in Godot settings. Try to build. Get 
`modules/mono/glue/gd_glue.cpp:250 Cannot find dotnet CLI executable. Fallback to MSBuild from Mono`

In terminal:
```
dotnet --version
3.1.102
```

**Comment by van800** [comment]
From what I see, likely `UnixFileHasExecutableAccess` doesn't work on Mac.

**Comment by raineszm** [comment]
I think I'm having this issue with `3.2.4rc1` on Big Sur. On my system it looks like the problem is that `dotnet` is not in `$PATH` when running Godot from the finder, which believe defaults to `/usr/bin:/bin:/usr/sbin:/sbin` or some permutation of that on MacOS.

However if I run Godot from the command line as `/Applications/Godot_mono.app/Contents/MacOS/Godot -p` everything works fine.

For now I've set up a trampoline with Platypus to set path and then run Godot
```sh
#!/bin/sh
export PATH="/usr/local/bin:$PATH"
/Applications/Godot_mono.app/Contents/MacOS/Godot -p
```
 but it seems like this can be fixed in Godot itself, either by adding `/usr/local/bin` to PATH in the Plist file, expanding on the code that searches for the dotnet cli, or just letting the user manually specify the path to the dotnet cli.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by Noah-Huppert** [comment]
fyi for others looking for a solution my problem was similar, but ended up being because on linux my `Godot.desktop` file I made didn't include the custom `PATH` modification that was in my shell profile. So I had to modify the `.desktop` file's `Exec` property to setup the `PATH` env var so `dotnet` was accessible.
