### ISSUE TITLE
Cant open project, project unnamed

### ISSUE THREAD

**Issue by martinpelli** [godotengine/godot#39073]
Hi , first of all I want to say that I am very noob and I am desesperated. I was going to launch my game on play store, but before I wanted to reduce the apk size, so I learn that I have to downlod godot Source from github And disable some modules. So I do it. I open my project in the compiling godot for windows that I download thanks to the godot docs. When opening my project all resoruces failes to load. So I say dosen’t matter the size I am going to launch the apk how is it. So I go and open the normal godot mono version and when opening an error of my project apear and the project is unnamed. So I start to search why, and I realized that I download the newest version of godot source. And I read that you can’t open a project in an older version if you open in a newer version. I changed the config file from 4 to 3 but still failing . So is there any solution or I have to kill me?

**Comment by KoBeWi** [comment]
This is not a place to ask such questions. It's an issue tracker, place to report bugs.

What you describe is a result of opening your project on master branch, which has changed lots of things. The "unnamed project" issue (which is not a bug) is caused by recent StringName changes. Some of the strings in project.godot are changed to StringNames when opening in newest version, you can revert this by removing `@` from them. Although if you opened your project, most likely all opened scenes were affected too. This is reversible, but it would be easier to restore a backup if you had one.

Also next time, unless you want to upgrade your project, compile Godot from 3.2 branch.
