### ISSUE TITLE
make_input_local function has an offset of +1 for negative positions

### ISSUE THREAD

**Issue by UltyX** [godotengine/godot#3909]
http://i.imgur.com/0kZEWhT.png
Using the "make_input_local" function returns an offset of +1 for positions which are negative.
In this example I created 4 rectangles at 10,10   -10,10  10,-10 and  -10,-10  and moused over the top right edge and got   10,10  -9,10  10,-9 and  -9,-9   as resulting position.

gd scrip  and test project attached below.

```
# testcase for make input local
extends Node2D

func _ready():
    set_pos(Vector2(50,50))
    get_node("Camera2D").set_zoom(Vector2(0.08,0.08))
    update()
    set_process_input(true)

func _input(event):
    if event.type == InputEvent.MOUSE_MOTION:
        var local_event = (make_input_local(event))
        get_node("label").set_text( str(local_event.pos.x) + "  " + str(local_event.pos.y) )
        get_node("label").set_pos( local_event.pos )

func _draw():
    var lower_rect = Rect2(Vector2(10,10),Vector2(10,10))
    var lower_rect2 = Rect2(Vector2(-10,10),Vector2(10,10))
    var higher_rect = Rect2(Vector2(10,-10),Vector2(10,10))
    var higher_rect2 = Rect2(Vector2(-10,-10),Vector2(10,10))

    draw_rect( lower_rect, Color(0,0,0))
    draw_rect( lower_rect2, Color(0,0,0))
    draw_rect( higher_rect, Color(0,0,0))
    draw_rect( higher_rect2, Color(0,0,0))
```

**Link to minimal example project** (optional but very welcome):
[testttttt.zip](https://github.com/godotengine/godot/files/156722/testttttt.zip)

**Comment by akien-mga** [comment]
That's harder to fix than I thought initially. The fact is that the local positions are computed as floats, and then cast to an int due to the definition of ``InputEvent``.

So around the ``x = 0`` and ``y = 0`` lines, you get things like:
``
int(-1.5) --> -1
int(-0.5) --> 0
int(0.5) --> 0
int(1.5) --> 1
```
Hence this offset.

I guess this could be solved by using ``floor`` instead of just assigning the floats to ints:
```
floor(-1.5) --> -2
floor(-0.5) --> -1
floor(0.5) --> 0
floor(1.5) --> 1
```

But would that break stuff to change that in [CanvasItem](https://github.com/godotengine/godot/blob/master/scene/2d/canvas_item.cpp#L962) and [Viewport](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1253)? :)

**Comment by akien-mga** [comment]
The current system, casting floats to integers, produce these coordinates:
![spectacle lh5955](https://cloud.githubusercontent.com/assets/4701338/14944061/50b60464-0fe9-11e6-988a-0b25b74dba55.png)

If we switch to using ``floor()`` (i.e. round to the nearest lower integer), we'd get:
![spectacle bz5955](https://cloud.githubusercontent.com/assets/4701338/14944067/7e918af2-0fe9-11e6-8008-ed563716c000.png)

Another alternative would be to change ``InputEvent`` to use floats instead of integers, but that would be quite a big change.

@reduz @punto- WDYT?
Also, if we do change the current behaviour, should it wait for 3.0 to warrant breaking compatibility?

**Comment by reduz** [comment]
we got rid of casting floats to integers so this should no longer apply, closing
