### ISSUE TITLE
MultiMesh does not work in C#

### ISSUE THREAD

**Issue by zerc** [godotengine/godot#39224]
**Godot version:**
v3.2.2.beta.mono.official
v3.2.1.stable.mono.official

**OS/device including version:**
MacOS 10.13.6

**Issue description:**
For some reason, I can't render meshes using `MultiMesh` when using C#. Pretty much the same code works as expected in GDScript. I've tried to setup `MultiMesh` using the editor's interface and from the script as in the [example](https://docs.godotengine.org/en/latest/tutorials/optimization/using_multimesh.html#multimesh-example) - same result.

**Steps to reproduce:**

1. Create a simple scene - `Spatial -> MultiMeshInstance`, configure the multi mesh
2. Write logic to populate the multimesh via `SetInstanceTransform` method in C# - does not display anything.
3. Write the same logic in GDScript - works like a charm.

**Minimal reproduction project:**

[multimesh-test.zip](https://github.com/godotengine/godot/files/4711989/multimesh-test.zip)

----

Hope that makes sense, thank you

**Comment by neikeq** [comment]
The Basis default constructor initializes all fields to 0f, which is different to GDScript. Use `Basis.Identity` to get the same value.
This is due to a limitation with struct default constructors in C#. The same applies for a few other types, see: https://docs.godotengine.org/en/stable/getting_started/scripting/c_sharp/c_sharp_differences.html?#basis

I haven't tested the uploaded project so there may be other issues.

**Comment by zerc** [comment]
Hi @neikeq 

Thank you for your reply, indeed `Basis.Identity` was the key and it works now, didn't notice this difference (although I've read the document your linked🤦 )

I've created a small PR to update the example: https://github.com/godotengine/godot-docs/pull/3624

Closing this one, as there is no issue, thank you again.
