### ISSUE TITLE
Rotation on 3D transform animation track in inspector with Quaternion is hard to use

### ISSUE THREAD

**Issue by lukostello** [godotengine/godot#39229]
**Godot version:**

3.2.1 stable official

**OS/device including version:**

Geforce 750 TI, GLES3

**Issue description:**

when using a 3d transform track adding rotation information to keys is simply ignored
(P.S. why does the editors axis lines intersect at (0.5, 0, 0) ?)
**Steps to reproduce:**
add a 3d transform track to an object, change the rotation information, observe no change. 

**Minimal reproduction project:**

[no rotation.zip](https://github.com/godotengine/godot/files/4713785/no.rotation.zip)

**Comment by Ev1lbl0w** [comment]
It's not working because the rotation is a quaternion, and not the regular rotation degrees.

To work on transforms, it's best to edit the object in the editor, and not in the inspector:

![godotGif](https://user-images.githubusercontent.com/6501975/83631982-56e8db80-a596-11ea-881e-1010ef2c99ad.gif)

> (P.S. why does the editors axis lines intersect at (0.5, 0, 0) ?)

I don't see it, the axis are aligned at (0, 0, 0). Maybe the confusion is coming from your object, which is slight to the left of the origin?

**Comment by lukostello** [comment]
hmm I see. Why then does not use the translation track when I use insert key from the inspector of the fine object? It instead asks if I'd like to make a bezier curve. I understand why it needs to be quaternion in the animation but perhaps we could use the insert key button in the objects' inspector as a way of converting Euler to Quaternion. My solution for preventing this communication error is to not allow values above 1 to be entered since thats as high as Quaternary would go. If that happened to me I'd have been like "ah quaternions... right"

P.S. yea I found that displacement later I didn't look at the scene root for it.
