### ISSUE TITLE
NoiseTexture image data and used OpenSimplexNoise don't resolve to the same values

### ISSUE THREAD

**Issue by razcore-art** [godotengine/godot#39239]
**Godot version:** v3.2.stable.official

**OS/device including version:**
```
 $ uname -a
Linux alienware 5.4.0-31-generic #35-Ubuntu SMP Thu May 7 20:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Issue description:**
I expect that
```
int(clamp((noisetexture.noise.get_noise_2d(x, y) * 0.5 + 0.5) * 255, 0, 255)) / 255.0
```
and
```
noisetexture.get_data().get_pixel(x, y).r
```
to resolve to the same values, but they don't. They start to deviate as the `(x, y)` position increases.

Texture flags don't seem to change anything.

**Steps to reproduce:** See the attached project.

**Minimal reproduction project:** [dbg.zip](https://github.com/godotengine/godot/files/4716620/dbg.zip)

**Comment by mrushyendra** [comment]
This is actually the same issue as #30356. The reason you are seeing deviations is not because `(x,y)` increases, but because you are setting `x = 220` and `y = 232` differently.

For example, flipping x and y before calling get_pixelv yields `true` every single time.
```
extends TextureRect

func _ready() -> void:
	yield(texture, "changed")
	
	for v in [Vector2.ZERO, 100 * Vector2.ONE, Vector2(150, 190), Vector2(200, 190), Vector2(220, 232)]:
		var noise: float = texture.noise.get_noise_2dv(v) * 0.5 + 0.5
		noise = int(clamp(noise * 255, 0, 255)) / 255.0
		
		var image := texture.get_data()
		image.lock()
		var image_r := image.get_pixelv(Vector2(v[1],v[0])).r
		image.unlock()
		
		print("noise: ", v, " ", noise)
		print("image: ", v, " ", image_r)
		print("is_equal_approx(noise, image_r): ", is_equal_approx(noise, image_r), "\n")
```

The existing PR for that issue would break compatibility, which is why I guess they are hesitant about approving it. Perhaps updating the documentation in the meantime would be useful.

**Comment by razcore-art** [comment]
Thanks, I searched for an issue related to this, but I guess I wasn't searching the proper terms cause I didn't see that issue.

Closing this in favor of that issue.
