### ISSUE TITLE
Flatpack Package does not recognize all binaries (Linux)

### ISSUE THREAD

**Issue by csteiiin** [godotengine/godot#39267]
> Operating System: Arch Linux

> Kernel:` Linux 5.6.14-arch1-1

Setting External editor to "emacsclient" or "emacs" is not possible.
Godot seems to not be able to find the binary ,although the can be used by any other programm/terminal (even with "Show hidden files")
ls -alh seems to show all permissions and groups correctly
`-rwxr-xr-x 1 root root  39K Mar  6 14:01  echo`
`-rwxr-xr-x 1 root root   28 Jan  3 13:24  egrep`
`-rwxr-xr-x 1 root root  14K May 19 09:51  einfo`
`-rwxr-xr-x 1 root root  78K May 20 21:27  eject`
`-rwxr-xr-x 1 root root  39K May 21 20:38  elfedit`
`lrwxrwxrwx 1 root root   10 May 19 10:00  emacs -> emacs-26.3`
`-rwxr-xr-x 1 root root  39M May 19 10:00  emacs-26.3`
`-rwxr-xr-x 1 root root  31K May 19 10:00  emacsclient`
`-rwxr-xr-x 1 root root  14K May  8 03:54  encodedv`
`-rwxr-xr-x 1 root root  47K Mar  6 14:01  env`
`-rwxr-xr-x 1 root root  38K Apr 15 08:43  envsubst`
`-rwxr-xr-x 1 root root 197K Dec 23 13:21  eqn`

Next i tried to remove the package via flatpak uninstall and downloaded the web binary. Emacs and emacsclient can now be used as an external editor without any problem.

**Comment by Calinou** [comment]
This is expected when using the Flatpak, due to sandboxing limitations. It's not a bug within Godot. Maybe we could patch the Flatpak version to use `flatpak-spawn` to start external editors, but this comes with security implications.

Feel free to open an issue on https://github.com/flathub/org.godotengine.Godot which is a better place to track this kind of issues and limitations.
