### ISSUE TITLE
Multiple Meshes is not allowed on NavigationRegion3D bake_navigation_mesh()

### ISSUE THREAD

**Issue by nightrobin** [godotengine/godot#39318]
**Godot version:**
4.0.dev
Commit: f05b4fea33e84ea3322702d774d69926a41ba913 [f05b4fe]

**OS/device including version:**
Windows 10 x64 Bit

**Issue description:**
Thru GDScript:
Multiple Meshes is not allowed on NavigationRegion3D bake_navigation_mesh() because NavigationMesh.create_from_mesh() only allows one mesh.

**Steps to reproduce:**
Thru GDScript:
1. Create a scene with the following nodes:
- Navigation3D
- NavigationMesh
- NavigationRegion3D
- 3 MeshInstance with CubeMesh (1 floor, 2 boxes)

2. Position the 3 MeshInstance with the floor on the bottom and the 2 boxes on top of the floor.
3. Use NavigationMesh.create_from_mesh(MeshInstance) - The floor MeshInstance.
4. How about the 2 boxes. It does not affect the baked navmesh

**Minimal reproduction project:**
N/A

**Comment by Calinou** [comment]
cc @AndreaCatania

**Comment by smix8** [comment]
A node setup like described does not / nolonger exist in Godot 4.0.

NavigationRegion3D with a NavigationMesh resource bakes multiple floor / box meshinstance children perfectly fine if the NavigationMesh has an `agent_height` and `agent_radius` that fits the geometry. Without a MRP I can only assume that the issue was the default NavigationMesh agent height of 2 which is a very high value and maybe should be lowered together with agent_radius to fit a human sized character better.

@akien-mga
@Calinou 
Since this is no bug for current Godot 4.0 this can be closed.

**Comment by Calinou** [comment]
Closing per smix8's comment.
