### ISSUE TITLE
Built In button in dialog cannot change translation

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#39320]
**Godot version:**
Godot 3.2.1.stable.official

**OS/device including version:**
Win7

**Issue description:**
Built In button in dialog cannot change translation. (eg. OK and Cancel in ConfirmationDialog).

**Steps to reproduce:**
Add ConfirmationDialog
Add translation file
call TranslationServer.set_locale() in ready

**Minimal reproduction project:**
[Dialog Translation.zip](https://github.com/godotengine/godot/files/4736160/Dialog.Translation.zip)

**Comment by akien-mga** [comment]
Yeah that's because the title and button texts for dialogs are defined in the constructor, so they are called when the Node is instantiated.

In your example, since you call `TranslationServer.set_locale("es")` from the script after the node has been created, it already has the English texts by default.

It works for Label as it intercepts `NOTIFICATION_TRANSLATION_CHANGED` to reset the text to match new translations.

The various `Dialog`'s should also be made to intercept `NOTIFICATION_TRANSLATION_CHANGED` and reset the various text fields that they use.

**Comment by akien-mga** [comment]
Note that if you set the locale before starting the game (e.g. with the `locale/test` project setting, or by actually running the game on a system with Spanish locale), it will work fine.

Similarly, if you create the dialogs from script after having changed the locale, it should work fine.
