### ISSUE TITLE
Cannot set input vector for an AnimationTree

### ISSUE THREAD

**Issue by NebulousWeb** [godotengine/godot#39339]
**Godot version:**

Godot 3.2.1

**OS/device including version:**

Windows 64 bit and Linux 64 bit; GLES3

**Issue description:**

Created an animationtree in the ActionRPG project for which see this youtube tutorial: https://www.youtube.com/watch?v=Z9aR9IiiHT8&list=PL9FzW-m48fn2SlrW0KoLT4n5egNdX-W9a&index=6

Despite the code working in the tutorial, the exact same code only had the character idling left and running left no matter the direction. 

**Steps to reproduce:**
The code that didnt work is in the player GDScript:

animationTree.set("parameters.Idle.blend_position", input_vector)
animationTree.set("parameters.Run.blend_position", input_vector)

However if it is replaced by the following code, it works perfectly:

$AnimationTree["parameters/Idle/blend_position"] = input_vector
$AnimationTree["parameters/Run/blend_position"] = input_vector

Attaching a project which has both lines of code, uncomment appropriately to test both cases.

**Minimal reproduction project:**

[Action RPG.zip](https://github.com/godotengine/godot/files/4740588/Action.RPG.zip)

**Comment by clayjohn** [comment]
That appears to be a typo in the tutorial code you followed. Take a look at the tutorial for [Animation Tree](https://docs.godotengine.org/en/latest/tutorials/animation/animation_tree.html#controlling-from-code) in the official docs. It says you can set properties from code like so:

```
anim_tree.set("parameters/eye_blend/blend_amount", 1.0)
# Simpler alternative form:
anim_tree["parameters/eye_blend/blend_amount"] = 1.0
```
Note that the string in both cases is the same (i.e. using "/" instead of ".".

You may want to follow up with the tutorial maker yourself if you think they made an error so that they can correct it.
