### ISSUE TITLE
the engine keeps crashing every time i try to open on of my project or create a new one

### ISSUE THREAD

**Issue by Didine-SG** [godotengine/godot#39384]
i haven't had this problem before using godot 3.2.1, I am able to open the project manager just fine but as soon as I open a project or create a new one the engine crashes and I get a warning from my AMD driver saying : "the display driver stopped responding and has recovered" 
I'm using an AMD radeon hd 5450

**Comment by akien-mga** [comment]
The issue template asked you for the Godot version you use and your OS, why remove it instead of providing the information we ask for?

This statement is ambiguous:

> i haven't had this problem before using godot 3.2.1

Are you having the issue in Godot 3.2.1, or were you not having the issue in 3.2.1 and you're now using a more recent version (3.2.2-beta4, or a build from the `master` branch)? If the former, what versions used to work and do they still work?

**Comment by Didine-SG** [comment]
sorry i'm new to github, i have this problem only when using godot 3.2.1 and older versions work just fine and the OS i'm using is windows 7

**Comment by akien-mga** [comment]
Again, what are the older versions which run fine?

**Comment by Didine-SG** [comment]
3.1.1 and 3.1.2

**Comment by clayjohn** [comment]
Sounds like a GPU timeout error like in #35366. T

his happens on lower end GPUs. You can try running the engine using GLES2 which would be more appropriate for such an old computer (HD 5450 is from 2010). The GLES3 backend is made for more modern computers, we created the GLES2 backend so that we could support low-end computers like this.
