### ISSUE TITLE
Automatic paths resolver.

### ISSUE THREAD

**Issue by DriNeo** [godotengine/godot#3950]
I wonder what you think about a kind of paths database system to allow folder reorganization without 
breaking dependencies.

The editor already displays the folder tree into the "Filesystem"dock maybe it is possible to save these informations into some location or a text file at the project's root.

This database file will be updated at every scene saving or scene running. Or simply when the Filesystem dock is updated.

To use this, a function, exposed to GDScript, must be designed to pull paths strings from the database.
This function takes the file name key as argument, and tries to returns the string who is necessary in various places where a file path is needed.

`var myScene = preload(get_file_path("my_scene.scn"))`

`extends get_file_path("base_class.gd")`

Maybe it's uglier to read, but such a function allows you to rearrange the folders, 
move the files when you want without worriying about broken dependancies. It prevents you to type
long paths in your scripts if your file system becomes huge.

If a kind C++ programmer found this useful for his needs, and if it's possible to implement with not much sweat, I guess he could helps a lot of other developers.

If an easy workaround is already  avalaible I apologize for this useless proposal.

**Comment by mohaalak** [comment]
what if there is two my_scene.scn??
but I think if we can drag and drop the files from filesystem two code then the path is copied there it will so good

**Comment by reduz** [comment]
if you do file operations in the filesystem dock, Godot fixes dependencies. Is there any missing operation?

**Comment by DriNeo** [comment]
@reduz Thanks for the tip ! I will try that.
My little project has all scenes folders at root. Some weeks later I wanted to create a single "Scene" folder and drop all the scenes folders inside. So a bunch of scripts needs to updated.

Anyway the mohaalak post is very interesting. Sometimes we can have two identical names. So his idea is probably better than mine.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
