### ISSUE TITLE
Rotation with snap sets values to NaN

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#39507]
**Godot version:**

3.2.1.stable.custom_build.f0a489cf4

That's 3.2.1 with two patches:

- https://github.com/godotengine/godot/pull/37228
- https://github.com/godotengine/godot/pull/35864

**OS/device including version:**

GNU/Linux 5.6.15-arch1-1
GTX 970
GLES3

**Issue description:**

When I rotate an object with snapping (either by pressing `y` or holding `ctrl` while dragging the gizmo),
Godot sets all the rotations to `NaN`. If I save the scene after doing this, Godot will refuse to load the scene
again, saying it encountered an error while parsing.

Rotation without snap works normally.

**Steps to reproduce:**

Unfortunately this isn't happening in a new project, I'm unsure what I did to get my current project into this state.

**Minimal reproduction project:**

https://gitlab.com/rcorre/quest

**Comment by nobuyukinyuu** [comment]
big guess here but the rotational value of a node an old project might've had a number in it that evaluated out to something that maybe resulted in a 0/0 operation -- applying rotation has always done some funky things with snap and maybe a change in how it's processed between editor versions let the door open for a NaN to sneak in when mixing old and new data values.

If there's a specific node in your project that this occurs on, you might be able to replicate it in a new project by manually assigning the same rotational value to the node from a text editor (not godot itself).  This would require a rotational value that isn't NaN, since once a NaN sneaks in it will spread to other values.  If you keep your code in a repo you may have a specific commit to track down where when adjusting the rotation from the editor the NaN first sneaks in.

**Comment by rcorre** [comment]
Good idea, but unfortunately there's no NaN in any scene files, and it happens on any object.

**Comment by rcorre** [comment]
In the logs I see

```
 servers/visual/visual_server_scene.cpp:601 - Condition "Math::is_nan(v.x)" is true.
```

**Comment by rcorre** [comment]
It happens even if I create a new scene. I'll try to build debug bits and dig in tonight.

**Comment by rcorre** [comment]
Debugging that line was no help, as it is just noticing the NaN, not creating it. @nobuyukinyuu might be on to something with a bad config though. I just removed the entry for this project from `~/.config/godot/projects/` and the issue disappeared.

**Comment by rcorre** [comment]
[cfg.zip](https://github.com/godotengine/godot/files/4789855/cfg.zip)

Here's the offending config. I can't find anything suspicous.

**Comment by rcorre** [comment]
There's a fair chance I accidentally opened this project with a `master` build and screwed up my config this way. It probably isn't worth pursuing unless you're really curious.

**Comment by rcorre** [comment]
Just happened to me again. I'm reasonably sure I didn't open this particular project with a `master` build. I noticed that in the `configure snap` menu my snap values are set to

- Translate: 0
- Rotate: 0
- Scale: 0.000002%
