### ISSUE TITLE
Can't use custom light shader if vertex shading is enabled

### ISSUE THREAD

**Issue by mbrlabs** [godotengine/godot#39513]
**Godot version:**
3.2.2rc1, GLES2 and GLES3

**OS/device including version:**
Windows 10

**Issue description:**
If you enable `Force vertex shading` in the editor, the `light()` function in custom shaders has no effect. I think this is because `light()` is called in the fragment shader for each light source and if you disable per pixel lighting this won't work of course.

Since it's nowhere mentioned that custom shading only works if per pixel shading is active this is either a bug or a documentation issue. I hope it's a bug tough and not by design 😄.

**Steps to reproduce:**
1) Enable `Force vertex shading` in the editor
2) Make a material with a custom shader and do e.g. `DIFFUSE_LIGHT = vec3(1.0, 0.0, 0.0);` in the `light()` function
2) Make a simple scene with a mesh and assign the material
3) Lighting did not change

**Minimal reproduction project:**
[PerVertexShadingBug.zip](https://github.com/godotengine/godot/files/4775011/PerVertexShadingBug.zip)

**Comment by Calinou** [comment]
I think this feature needs to be implemented from scratch.

**Comment by tetrapod00** [comment]
This was documented a long time ago by https://github.com/godotengine/godot-docs/pull/3685. 

Since then, vertex shading was removed in 4.0 and readded in 4.4. The warning is [still present](https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/spatial_shader.html#light-built-ins) in the spatial shaders page, so this does not need to be re-documented.
