### ISSUE TITLE
Editor performance stutters a lot in 2D scenes with several dozen Sprites.

### ISSUE THREAD

**Issue by avencherus** [godotengine/godot#39574]
**Godot version:**

3.2 fac9f8f82de50cec926fcc35f81b1cd3722e2f9b

**OS/device including version:**

Win10 64-bit GLES2
NVIDIA GeForce GTX 1660 SUPER

**Issue description:**

Been noticing in some of our large scenes, even on a good GPU there is a fair bit of lag and stuttering.  Some profiling shows these two pain points.  Our scenes usually contain one or sometimes two semi-large PNG atlas that provides the textures for 99% of the stage's sprites.

Lots of spiking.
![image](https://user-images.githubusercontent.com/13004169/84694521-ff614d00-af51-11ea-9bdd-57434f31a824.png)

Visual Studio gives these as its two pain points.

![devenv_3D0Ujq3kSm](https://user-images.githubusercontent.com/13004169/84694383-cb862780-af51-11ea-962c-71c3d5363ac1.png)
![devenv_jagmetBHKY](https://user-images.githubusercontent.com/13004169/84694386-ccb75480-af51-11ea-9b90-26b8a3817dc9.png)

**Steps to reproduce:**
Use a large 2D scene, and pan around.

**Minimal reproduction project:**
[Stuttering.zip](https://github.com/godotengine/godot/files/4784741/Stuttering.zip)

**Comment by Calinou** [comment]
Could you upload a minimal reproduction project, please?

**Comment by avencherus** [comment]
Sure, the attached project is far more than what we're using, so as to magnify the problem.  The stuttering is in the editor only.

**Comment by lawnjelly** [comment]
Did you forget to attach the project?

Maybe this editor resource preview is getting stuck, or getting called repeatedly and loading the png multiple times.

**Comment by avencherus** [comment]
@lawnjelly Ah yes.  😄  I must of been looking at the preview still when I tested downloading it, and closed it when I returned.  It was late.  Should be attached to the first post now.

**Comment by lawnjelly** [comment]
I'm not getting this stuttering:
Linux Mint 18.3
Intel HD Graphics 630

It's a little slow for me (due to fill rate probably with the large sprites) but nothing too bad. I've put a breakpoint on the png image loader and it's not getting hit for me. There's a lot of differences which could be causing it on your system and not mine : editor settings as well as platform / hardware.

If you are able to compile from source and debug it, you could place a breakpoint on ResourceLoader::load and try and find out where it's getting called from (during the stuttering, rather than during startup). Or else it will need a dev that can reproduce the problem to investigate.

**Comment by avencherus** [comment]
Thanks, that pinpointed it, and helped a lot.

It's a false alarm.  The timing of this was coincidental with an upstream pull and rebuild that I did.  Though it isn't the issue.  I had very minor validation line added in an attempt at fixing this:  https://github.com/godotengine/godot/issues/36241

When it does creep back in, it has this side effect.  I doesn't look like it can successfully create the thumbnail data, and the problem goes deeper.
