### ISSUE TITLE
Custom drawing ignores color argument when sampling with a shader

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#39601]
**Godot version:**
3.2.2 rc1

**OS/device including version:**
Gles3 Win10 64

**Issue description:**
If you use _draw() with any draw functions (draw_circle, draw_colored_polygon, etc) combined with any shader that tries to sample the texture, all custom drawing will be white regardless of what color you pass as an argument. 

![image](https://user-images.githubusercontent.com/526829/84803778-d2a44880-afd8-11ea-877e-36f3dda4d4f5.png)
Sampling the texture:
![image](https://user-images.githubusercontent.com/526829/84803677-b0aac600-afd8-11ea-9297-a58f1b404722.png)
Without sampling the texture:
![image](https://user-images.githubusercontent.com/526829/84803744-c5875980-afd8-11ea-9d18-4a2414c57996.png)

**Steps to reproduce:**
- open attached project
- playtest the project. It shows the godot icon with a white circle on top
- check the script for the sprite and notice draw_circle is using red rather than white
- go to the shader for the sprite and comment the following lines:
```
	vec4 color = texture(TEXTURE,UV);
	COLOR = color;
```
- see how the circle is now colored properly 

**Minimal reproduction project:**

[CustomDrawingwithShader.zip](https://github.com/godotengine/godot/files/4787987/CustomDrawingwithShader.zip)

**Comment by clayjohn** [comment]
Thanks for the well-written bug report. Unfortunately, this is not a bug.

The color you pass in from custom drawing functions is passed to the shader through the vertex shader which passes it to the fragment shader as ``COLOR`` (note ``COLOR`` is an ``inout`` variable in the [docs](https://docs.godotengine.org/en/stable/tutorials/shading/shading_reference/canvas_item_shader.html#canvasitem-shaders)).

So at the beginning of your fragment function ``COLOR`` is red, but you are overriding it by setting it to ``color`` and you are losing the red color. 

I suggest, instead of setting ``COLOR`` to ``color``, you instead multiply the values.

```
COLOR *= color;
```

**Comment by noidexe** [comment]
Thanks a lot for the detailed explanation!
