### ISSUE TITLE
AnimationTreePlayer blending 2d animations incorrectly

### ISSUE THREAD

**Issue by FEDE0D** [godotengine/godot#3962]
**What happens:**
When blending two animations, the scale of one of them is assumed to be 0 (zero) even when no information about the scale is present in the animation tracks.

**What should happen:**
When blending an animation tracks with no information about scale:
        \* The scale is the same as the scale present on the other animation.
        \* Or the scale should be assumed to be (1, 1).
        \* Or no blending should be performed on the scale property. This is preferable, as the scale set on the editor by the user is preserved.

This bug may be related to #3711 

**Operating system or device:**
Linux Mint 17
Custom build commit 218bb112e59b20fd881e799754d7cc634f4a8bca

**Link to minimal example project** (optional but very welcome):

https://dl.dropboxusercontent.com/u/274954519/godot-issues/AnimationTreeBug.zip

**How to test:**
        \* The AnimationPlayer has two animations: horizontal and vertical, each one moves the IK chain in diferent directions to test the blending.
        \* The AnimationTreePlayer has a simple Blend2 node to blend the animations.
        \* Test by changing the amount slider on the Blend2 node.

**Notes:**
    \* The blending worked fine until a timeScale node was introduced in the AnimationTree. After that the scale (0, 0) was present for all nodes in all animations where no scale was set.
    \* After deleting the timeScale node the error persist, even after restarting the editor.
    \* Also note that I had to add the scale (1, 1) in the vertical animation in order to make it easier to see what is happening, otherwise the scale of every node is (0, 0) making it imposible to see what's going on

**Comment by rgrams** [comment]
Hmm, it seems like you're talking about two things here. Can you clarify when you're talking about animating the scale of a node (Node2D, Sprite, etc.), and when you're talking about the timeScale node in the AnimationTree? 

I'm aware of the issue with scale tracks (or any vector2 track actually, try pos) blending to (0, 0) if there's no track in the other animation. I'm not sure where the timeScale node comes in though, I couldn't find any issues with that in your example project. 

If the AnimationTree is behaving weird after you modify the animations (in the AnimationPlayer), try deleting and re-adding their Animation nodes in the Tree, there seems to a bug there, though I haven't tested it properly yet.

**Comment by JoshuaGrams** [comment]
Yeah, I've been worried about this for a couple weeks but I'm not sure how to fix it.  The existing code was written so that it the blending doesn't know whether other tracks are present. It just grabs all tracks used anywhere in the Animation Tree, sets them all to zero, and then the blend nodes just pass a blend fraction to each of their inputs. So each track only knows that it should update its time in a certain way and then add a certain fraction of its current value to the property it controls.

That's the way the code was. It previously had the multiply-add code for Transforms, all I added was the multiply-add code for Variants.

This is a deeper problem and I'll have to see whether I understand the code well enough to be confident modifying it that much. The problems I see are:

* The scale should be the same as the one present on the other animation: It doesn't *know* anything about the other animation, so we would need a mechanism for that.
* The scale should be assumed to be (1, 1): The scale is just a vector, so how can we identify it for sure. By name? But we might have to check the node type and the property value in case a user adds a different type of "scale" value to an object?
* The scale should preserve the value set in the editor and no blending should be performed: all we have is the value from the previous frame, so (except when the Animation Tree Player is first loaded) we don't have any idea what the value in the editor was. So we'd need a place to save those other values while the game is running. And...if you're playing an Animation or Animation Tree, the editor saves the values where you stopped the animation rather than resetting it to a base pose, so they may be arbitrary values anyway.

So...I'll see what I can come up with.

**Comment by FEDE0D** [comment]
Yes you're right.
This is quite a complicated bug to fix. Keep in mind that other properties have to also be considered like modulate colors.
I've just tested this and animations with modulate color tracks default to (0, 0, 0, 1) color.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
