### ISSUE TITLE
Add an editor keyboard shortcut to the C# "Build solution" button

### ISSUE THREAD

**Issue by JimArtificer** [godotengine/godot#39633]
**Godot version:** 3.2.1
**OS/device including version:** Windows 10
**Issue description:** `Editor > Editor Settings > Shortcuts`  does not have a binding for the `Build solution` button.

This is a workflow concern when editing C# code.

**Comment by Calinou** [comment]
What should the default shortcut be?

**Comment by Flavelius** [comment]
Rider uses ctrl-shift-b which sounds reasonable.

**Comment by akien-mga** [comment]
Something with <kbd>B</kbd> indeed sounds good, but it will likely conflict with existing bookmark/breakpoint shortcuts in the script text editor.

**Comment by JimArtificer** [comment]
I will remap it to F6, which is what I use in Visual Studio due to muscle memory. Any default is probably fine.

**Comment by JimArtificer** [comment]
Even if this shipped without a default it would address the workflow issue. I intend to remap it to `F6` anyway (Visual Studio muscle memory).

**Comment by codecat** [comment]
Was this issue addressed in 3.4 or 4.0 yet? If not I wouldn't mind doing a pull request for this.

**Comment by Calinou** [comment]
It wasn't added yet - feel free to open a pull request for this 🙂

**Comment by codecat** [comment]
I underestimated the build requirements for the Mono build of Godot, so I'm gonna have to retract my statement of doing a pull request, sorry. Open for anyone to do this!

**Comment by lewiji** [comment]
Hi, I was linked to this issue after asking about the same thing.

I've implemented an editor keyboard shortcut for the "Build" button by exposing the `ED_GET_SHORTCUT` function from `editor_internal_calls.cpp`  via `GDMonoUtils::add_internal_call`. Result:

![image](https://user-images.githubusercontent.com/233380/132982441-25c0895e-7e73-4ffb-9b2a-2ed1e5077d0c.png)

However, since I'm working on 3.x, I made this change on a 3.x branch. When I tried to rebase on master, first I got an error because `ShortCut` from 3.x is now `Shortcut` in 4 I guess, but now I'm getting further errors unrelated to my changes in `code_completion.cpp` (unchanged)

![image](https://user-images.githubusercontent.com/233380/132982484-06ce87c6-f4ae-4359-bb53-38ef114ee757.png)

Is there an accepted way to submit a PR for 3.x, or do they need to be based on `master` to be accepted?

**Comment by raulsntos** [comment]
C# doesn't compile in master right now due to #52268

**Comment by lewiji** [comment]
> C# doesn't compile in master right now due to #52268, if you've already made the changes for `master` I think you should submit that PR too.

Thanks for the info, I will keep an eye on that. I think I have the changes applied and modified for `master`, however I've not tested them due to the compiler issue. I can revert to before the mentioned issue and test against that.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/3197, as feature proposals are now tracked on the Godot proposals repository.
