### ISSUE TITLE
More demos for tool mode needed

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#3964]
Hi!
I don't know carefully about tool mode abilities, but can forecast some game objects' behaviours in editor:
[Level Design (video)](http://www.aparat.com/v/YkvsB)
[Level Design2](http://www.aparat.com/v/tmioD)

**Comment by bojidar-bg** [comment]
I don't get this issue, exactly what is lacking currently?

**Comment by neikeq** [comment]
Is this a feature request or a question? Looks the same [as this](http://godotengine.org/qa/954/tool-mode-potential).

**Comment by bojidar-bg** [comment]
@neikeq ~ Quite similar, yeah. Maybe if we change it to "More demos for tool mode needed"?

BTW, currently nothing is lacking from tool mode AFAIK, since it can use all APIs as in the real game. If there is a bug, it wouldn't be proper to insert it in this issue, so, I guess we should close it as invalid, or change it to a docs/demos request.

**Comment by djrm** [comment]
Movable to demos repo

**Comment by akien-mga** [comment]
Moved to https://github.com/godotengine/godot-demo-projects/issues/3
