### ISSUE TITLE
Node not found C# Mono 3.2.2 RC1

### ISSUE THREAD

**Issue by ksvslk** [godotengine/godot#39660]
**Godot version: 3.2.2 RC1 Mono**

**OS/device including version:**
macOS Catalina 10.15.3

**Issue description:**

`GetNode` methods in `_Ready()` will not set values to variables - values are still `null` for `progress` and `background` after `_Ready()`.
```
public class Preloader : Control
{
    private Thread thread;
    private ProgressBar progress;
    private Sprite background;

    public override void _Ready()
    {
        thread = null;
        progress = GetNode<ProgressBar>("Progress");
        background = GetNode<Sprite>("Background");
    }
```

**Steps to reproduce:**
1. Define a `Node`
2. Use `GetNode` in `_Ready` to initialize the `Node`
3. Get error `...Node not found`

**Minimal reproduction project:**
https://ufile.io/bayhwyw7

**Comment by rafaelgdp** [comment]
@ksvslk The problem is not with Godot, it's with your project. I just downloaded it and inspected what you were doing. See, you defined the Preloader.cs as an autoload script. Notice, however, that the class itself has no knowledge of the nodes in the Preloader.tscn scene. If you want the autoload to know about the nodes in this scene, you have to add the Preloader.tscn SCENE as an autoload. It ran just fine when I deleted the Preload.cs as an autoload and replaced it with Preload.tscn. I think this issue should be closed.

**Comment by ksvslk** [comment]
> @ksvslk The problem is not with Godot, it's with your project. I just downloaded it and inspected what you were doing. See, you defined the Preloader.cs as an autoload script. Notice, however, that the class itself has no knowledge of the nodes in the Preloader.tscn scene. If you want the autoload to know about the nodes in this scene, you have to add the Preloader.tscn SCENE as an autoload. It ran just fine when I deleted the Preload.cs as an autoload and replaced it with Preload.tscn. I think this issue should be closed.

Yes! Thank you - I was hoping that it was my mistake. Closed.
