### ISSUE TITLE
BoneAttachment Lag

### ISSUE THREAD

**Issue by cart** [godotengine/godot#3966]
**Operating system or device:**
OS: Arch Linux 
Device: Macbook Pro late 2013

**Issue description** (what happened, and what was expected):
A node attached to a BoneAttachment lags behind the bone it is attached to when the bone is animating.  This is not desirable.

Example illustrating why this is an issue: a sword attached to an animated hand's BoneAttachment could appear outside of the hand

**Steps to reproduce:**
1. Import an animated bone structure
2. Add a bone attachment
3. Attach a node to the bone attachment
4. Play the animation in game

**Link to minimal example project** (optional but very welcome):
[BoneAttachmentBug.zip](https://github.com/godotengine/godot/files/160627/BoneAttachmentBug.zip)

**Comment by slapin** [comment]
Yeah, it was always lagging, see old Godot 3D videos on youtube...

**Comment by reduz** [comment]
this will be redone in 3.0

**Comment by mcanders** [comment]
Great!  The lag distance is relatively constant, so I've been getting around this by scaling everything up to the point where the lag is hard to notice :)

**Comment by OGMP-Gyrth** [comment]
![peek 2017-06-05 18-54](https://cloud.githubusercontent.com/assets/14081613/26794131/ce7f9b0e-4a20-11e7-81a4-bd7f642f42a7.gif)
![peek 2017-06-05 18-55](https://cloud.githubusercontent.com/assets/14081613/26794132/ce9df6a8-4a20-11e7-8c78-c4577aabeb2f.gif)
![image](https://cloud.githubusercontent.com/assets/14081613/26794251/3d6cce88-4a21-11e7-8598-137f11c9c322.png)

I also experience this issue. The first animation is while looping/playing the animation. You see the gun dragging behind a bit. The second animation is when manually sliding the animation progress. I hope this can be fixed in Godot 2 or a workaround is found.

System info:
Arch Linux
Godot 2.1.3-1

**Comment by punto-** [comment]
Does it change if you make the animation process on fixed instead of idle?

**Comment by punto-** [comment]
also try if you change the order of the nodes (animation player before or
after the bones/attachment in the tree)

**Comment by OGMP-Gyrth** [comment]
Yes! Thanks punto.
Workaround: put the Process Mode to Fixed in the AnimationPlayer.

**Comment by mcanders** [comment]
Yup thats definitely a fix!  We could close this now, but I think saying "you just need to know that you have to change the process mode to fixed whenever you use a bone attachment" isn't user friendly enough.  It should either be enforced automatically or warned about.  Maybe we could make use of the warning system (the one used to warn about Collider misconfiguration) to say something like "This AnimationPlayer references a node with a bone attachment, but it's mode isn't set to fixed.  This could result in unexpected behavior."
