### ISSUE TITLE
External Editor: Can't access parent class variables in child class but can access them after restarting Godot

### ISSUE THREAD

**Issue by Arun-N** [godotengine/godot#39713]
**Godot version:**
3.2.1

**OS/device including version:**
Windows 10

**Issue description:**
I'm using VSCode as an external editor and any time I declare a new variable in a parent class, I can't access that variable in a child class (error: not declared in current scope) unless I restart Godot entirely. Not sure if it's related, but it also shows "possible cyclic resource inclusion" message along with the reference error in Godot's output tab. This doesn't seem to be happening with the in-built editor.

As a side note, I followed [the steps show in the docs](https://docs.godotengine.org/en/stable/getting_started/editor/external_editor.html) to set up VSCode for use with Godot

**Steps to reproduce:**
1. Set up an external editor.
2. Open parent and child class scripts in the external editor by double-clicking the respective gdscript files.
3. Create variable in parent class
4. Try to use this variable in child class - It shows the "not declared in scope" error
5. Exit Godot entirely
6. Open the scripts again. Now that variable can be called inside the child class without any error popping up

**Minimal reproduction project:**
I don't think it's project dependent but here's the one I was facing this issue in.
[Godot Platformer.zip](https://github.com/godotengine/godot/files/4808274/Godot.Platformer.zip)

**Comment by KoBeWi** [comment]
Isn't this issue with VS Code plugin?

**Comment by Arun-N** [comment]
> Isn't this issue with VS Code plugin?

Thought about that but then reloading vscode doesn't solve it. I have to restart Godot for it to go away. Not sure if the issue is on the plugin side or Godot side

**Comment by linkpy** [comment]
After looking at the messages exchanged between the LSP server and the VSCode extension, it seems like the autocomplete suggestions in that case is all of the available identifiers (classes, GDScript functions, class functions, ...) and there is so much of it that vscode debugger isn't able to show it.

For me the issue is on the LSP server, not on the extension. The extension doesn't handle that kind of logic, neither the VSCode language adaptator interface, that kind of operations are done on the LSP server.

**Comment by hdorer** [comment]
This is still happening to me in Godot 4.2.2
