### ISSUE TITLE
Color.black is false

### ISSUE THREAD

**Issue by API-Beast** [godotengine/godot#39731]
**Godot version:**
3.2

**OS/device including version:**
Windows

**Issue description:**
In GDScript a black color evaluates to false in a if statement. It is unlikely that this is what the user expects and can result in nasty bugs.

**Steps to reproduce:**
```swift
var color = null
color = Color.black

if color:
  print("color is true")
else:
  print("color is false")
```

**Comment by API-Beast** [comment]
![grafik](https://user-images.githubusercontent.com/1295635/85226918-3c0dc800-b3da-11ea-8fc9-5c6f365e3120.png)

**Comment by pycbouh** [comment]
Red aspect doesn't have anything to do with it:

```gdscript
	print("true" if Color() else "false")           # false
	print("true" if Color(0, 0, 0) else "false")    # false
	print("true" if Color(0, 0, 0, 1) else "false") # false
	print("true" if Color(0, 0, 0, 0) else "false") # true
	print("true" if Color(0, 1, 1) else "false")    # true
	print("true" if Color(0, 1, 1, 1) else "false") # true
	print("true" if Color(0, 1, 1, 0) else "false") # true
```

I remember some discussion about it, but I can't find a link. The `black` color is falsy, because it's the default value of `Color`, as I recall.

**Comment by akien-mga** [comment]
That's by design, all `Variant` types evaluate to `false` when their value is their default initialization. It's debatable whether this is a good design, but it's not a bug, and changing it would mean changing a lot of the engine's code and base assumptions, so it should be debated in https://github.com/godotengine/godot-proposals.

See:
https://github.com/godotengine/godot/blob/9ecb85644bba4207efcfe5e595ccb872efe7533a/core/variant_op.cpp#L162-L170

and:
https://github.com/godotengine/godot/blob/9ecb85644bba4207efcfe5e595ccb872efe7533a/core/variant.cpp#L817-L965

`Color.black` is `Color(0, 0, 0, 1)` (opaque black), which happens to be `Color`'s default value, thus its "zero" value.

#39733 made this clear in the documentation, so I think this can be closed. But if anyone feels strongly about challenging this `booleanize()` assumption, that should be done via a proposal as mentioned above.
