### ISSUE TITLE
Again, Touchscreen button doesn't obey control positioning 

### ISSUE THREAD

**Issue by yuyoDev** [godotengine/godot#39740]
Version:
Godot 3.2.2rc2

Os:
Archlinux amd64

This error has already been reported and fixed, but right now it doesn't work.
[https://github.com/godotengine/godot/issues/171](url)

Steps to reproduce the error:
Add VboxContainer and inside this add two touchscreenbuttons with textures inside normal.

**Comment by MightyPrinny** [comment]
It's not an error, it's more of an inconvenient design, it doesn't work because it's not a Control node, it's a Node2D, you can add it as a child of a Control node and write some code to make it update the parent rect's min rect size and make it resize properly so it fits in the parent Control rect. Alternatively you could use a TextureButton or a Button node if you don't need multi touch.

**Comment by Calinou** [comment]
Closing per @MightyPrinny's comment. This is why the TouchScreenButton icon is blue, not green :slightly_smiling_face:

Maybe you could open a [proposal](https://github.com/godotengine/godot-proposals) about making TouchScreenButton inherit from Control, but it will break compatibility with existing projects.
