### ISSUE TITLE
body_shape_entered yields extraneous shape indices on rigidbodies with only one shape (RigidBody with Bullet)

### ISSUE THREAD

**Issue by crodnu** [godotengine/godot#39767]
**Godot version:**
v3.2.1 mono 64 bits

**OS/device including version:**
Windows 10, also happens in linux machines

**Issue description:**
When a rigidbody with only one shape in it (either added by a collision shape or one added programatically with the shape_owner syntax) the body_shape_entered signal yields extraneous shape indices (this can happen both on the body_shape and the local_shape parameters). The signal seems to work correctly more than one shape are present. This error is present both in GDScript and in c# (examples for the latter not included).

**Steps to reproduce:**
1) Add 2 rigidbody nodes with one shape in them.
2) Connect the signal to a function that prints the parameters body_shape and local_shape.
3) Collide.

**Minimal reproduction project:**
[Tests](https://github.com/godotengine/godot/files/4816395/godot.collision.test.zip)
All the tests print the body_shape and local_shape of the signal in question, catched by the upper sphere.
Test 1 and 4 showcase the error in question (1 adds the shapes programatically while 4 uses CollisionShapes from the editor).
Test 2 shows the signal working correctly by adding one more shape to the same shape owner.
Test 3 shows the signal working by adding a different shape owner with a different shape to the rigidbody.

**Comment by akien-mga** [comment]
Confirmed in 3.2.2 RC 3.

This seems to happen with Bullet but not GodotPhysics, so I guess Bullet is using some uninitialized memory.

**Comment by pouleyKetchoupp** [comment]
Here's what I found about this issue.

The members `mIndex0` & `mIndex1` in Bullet manifolds that we use for getting shape indices are not initialized by default (unless `DEBUG_PART_INDEX` was defined which is not the case by default):
https://github.com/godotengine/godot/blob/b92477d77e9a6f46e4276a20a451dfac9d485f47/thirdparty/bullet/BulletCollision/CollisionDispatch/btManifoldResult.h#L60-L71

In bullet, this is only set when `btManifoldResult::setShapeIdentifiersA` and `btManifoldResult::setShapeIdentifiersB` methods are called.

These indices are set to **child shape indices** for compound shapes (which is what we want):
https://github.com/godotengine/godot/blob/b92477d77e9a6f46e4276a20a451dfac9d485f47/thirdparty/bullet/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp#L198-L199

And they are also set to **triangle indices** for concave shapes (which is not what we want):
https://github.com/godotengine/godot/blob/b92477d77e9a6f46e4276a20a451dfac9d485f47/thirdparty/bullet/BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp#L122-L133

That means a static body with multiple concave shapes also reports wrong values if what we expect is the shape index, as it would be the triangle index instead (tested on 4.0 branch, that's what happens with Bullet, while GodotPhysics reports the shape index as expected).

So there's an easy quick fix we can do on Godot side to solve the current issue in simple cases, by making sure the shape index is set to 0 in case of single shapes in `SpaceBullet::check_body_collision`:
https://github.com/godotengine/godot/blob/b92477d77e9a6f46e4276a20a451dfac9d485f47/modules/bullet/space_bullet.cpp#L835-L846

By using something like that:
```
int shapeA = (bodyA->get_shape_count() > 1) ? pt.m_index0 : 0;
int shapeB = (bodyB->get_shape_count() > 1) ? pt.m_index1 : 0;
```

But that wouldn't solve the case with a body with multiple concave shapes, as this would still report triangle indices instead of shape indices. The information about shape indices is currently lost in this case AFAIK.

@AndreaCatania: Do you know of any way to work around this issue with concave shape manifolds reporting triangle indices instead of shape indices? Or do you think it's something that would require a fix in Bullet?

**Comment by Shfty** [comment]
I'm seeing what looks like the same issue using `PhysicsDirectSpaceState::intersect_ray` under Bullet. Tracing a single ray down onto a `StaticBody` with a single `CollisionShape` comprised of a cube `ConcavePolygonShape` causes `9` to come back as the shape index, whereas GodotPhysics returns the expected `0`.

This is a significant blocker for 3D physics work - I'm currently trying to implement a custom `intersect_ray`-based movement system due to various issues with `move_and_slide`, and `ConcavePolygonShape` seems to be the only way to get consistent intersection results from the Bullet backend. Unfortunately, the returned normals for `ConcavePolygonShape` don't account for `CollisionShape` scale and need to be manually fixed up in script, but that can't happen without being able to look up the hit shape and query its transform.

As an aside, i's interesting that the incorrect values are being driven by triangle index for `ConcavePolygonShape` intersections - that would be useful data to have as its own key in the result dictionary alongside correct shape indices.

**Comment by madmiraal** [comment]
> So there's an easy quick fix we can do on Godot side to solve the current issue in simple cases, by making sure the shape index is set to 0 in case of single shapes in SpaceBullet::check_body_collision
> ...
> But that wouldn't solve the case with a body with multiple concave shapes, as this would still report triangle indices instead of shape indices. The information about shape indices is currently lost in this case AFAIK.

I think the "easy, quick fix" makes sense. We could also set it to zero if the `partId` is not -1 i.e. there is a `ConcavePolygonShape`. The scenario where there are multiple shapes and one or more is a `ConcavePolygonShape` is an unlikely one. We can document the failure to detect the shape id if a `ConcavePolygonShape` is used.

> Do you know of any way to work around this issue with concave shape manifolds reporting triangle indices instead of shape indices? Or do you think it's something that would require a fix in Bullet?

It looks like the problem is the other way around. The index should be the triangle index, but compound shapes have hijacked it to report the child index. The change to support the triangle index was done [here](https://github.com/bulletphysics/bullet3/commit/fe4e81ebff6936497758b3cc5395876a04350c80), and later the change to use it to store the child index was done [here](https://github.com/bulletphysics/bullet3/commit/d67aa861f2456e2c40980c11a02b41b026969cf6). So there's no easy fix.
