### ISSUE TITLE
Collisions do not recalculate when updating collision_layer

### ISSUE THREAD

**Issue by stevearc** [godotengine/godot#39768]
**Godot version:**
3.2.2-rc3

**OS/device including version:**
Windows 10 x64

**Issue description:**
I have an Area2D with a large collision shape. I instantiate a KinematicBody2D with `collision_layer = 0` and place it within the Area2D's collision radius. Inside of the `_ready()` function for the body, it sets `collision_layer = 1`. Previously this would cause the `body_entered` signal to be emitted on the Area2D, but now the signal is *not* emitted. Note that if you move the body out of collision radius with the Area2D and then back into the radius, the signal will be emitted as expected.

**Steps to reproduce:**
Simply run the attached project. In 3.2.1 you will see
```
Body detected: Body
Body detected: @Body@2
Body detected: @Body@3
Body detected: @Body@4
```
There is no output in 3.2.2-rc3

Under the hood this is simply instantiating bodies with the parameters mentioned above on a 1 second timer and printing in the `body_entered` signal handler.

**Minimal reproduction project:**
[BugDemo.zip](https://github.com/godotengine/godot/files/4816469/BugDemo.zip)

**Comment by madmiraal** [comment]
I suppose it's debatable whether this is a bug or a fix. Consider the scenario where the `CollisionObjects` are both `PhysicsBodies` changing the collision/mask layer when they're overlapping so they now interact would create a sudden, huge, unrealistc separation impulse. Others have this problem when changing the `position` of a `KinematicBody` directly so that it overlaps with a `RigidBody`. It's also why it's so important to place `Bodies` away from other `Bodies` when creating them.

Finally, it's worth noting that this only happens when changing the collision/mask layer combination. In the example project, if the Bodies being added already have the required collision layer, the signal does get triggered.

**Comment by stevearc** [comment]
I agree that this is not obviously wrong behavior at first glance, however I do think it violates the principle of least surprise. If I put two physics bodies overlapping, I expect them to be repulsed. If I put a physics body inside of an Area2D, I expect it to be detected. If I change the collision layer/mask of a body, I would expect one of two things to happen:

1) The simulation is updated to account for the new layer/mask and the next frame will have the appropriate enter/leave signals
2) Godot throws an exception saying that you cannot change the layer/mask

What I *don't* expect is that the overlapping bodies completely fail to detect each other unless they move out of each others' radius and then back in. If changing the collision layer/mask is not supported anymore, that's fine. I can find a way to hack around it. But if it *is* still supported, it probably shouldn't work like this.

**Comment by madmiraal** [comment]
Interestingly, even in v3.2.1, if changing the collision layer is delayed it doesn't work either. I changed the `Body.gd` to this:
```
extends KinematicBody2D

var pressed = false

func _input(event):
	if !pressed and event.is_action_pressed("ui_accept"):
		collision_layer = 1
		print("Changed " + name + "'s collision layer!")
```
Which produces the following output when a `ui_accept` key is pressed:
```
Changed @Body@4's collision layer!
Changed @Body@3's collision layer!
Changed @Body@2's collision layer!
Changed Body's collision layer!
```
No signals are triggered either.

So this problem is bigger than it just not working when changing it in `_ready()` in v3.2.2.rc3.
