### ISSUE TITLE
Changing the radius of a CircleShape2D, will have an effect on all instances of a scene

### ISSUE THREAD

**Issue by YugoCode** [godotengine/godot#3983]
I have a scene, which includes an Area2D and a CollisionShape2D(CircleShape2D). If I make a couple of instances of this scene and change one specific radius with `Area4.get_child(0).get_shape().set_radius(newRadius)` it will change the radius of all instances.

It's the second time in my only two games that I have such confusing problems with CollisionShape2D ( https://github.com/godotengine/godot/issues/2804 ). 

Could you please fix these both for 2.1?

And what is the workaround for this case?

**Comment by bojidar-bg** [comment]
@YugoCode The thing is that shapes are resources, so you will have to either duplicate them before changing the radius, or play with `shape_transform`. So, to me it is a feature (as it allows for faster loading and running of scenes), and not a bug.

BTW, you might create a new collision shape the first time you want to change radius, and then you will have no such problems.

**Comment by kubecz3k** [comment]
It's intended behaviour, not sure what you are doing exactly since you haven’t add any sample code or 'reproduction steps' but resources are shared generally. You can duplicate shapes inside _ready of your area with something like this one:
```
var uniqueShape = get_shape(0).duplicate();
clear_shapes();
add_shape(uniqueShape)
```
Then your code should work as you expect for it to work. This is working like this for performance reasons (believe me you want for resources to be shared generally). There are many other ways of achieving what you need but the best would be to ask a question on Q&A so other users could benefit from it in future as well.
