### ISSUE TITLE
[FBX] Unable to correctly import fox

### ISSUE THREAD

**Issue by fire** [godotengine/godot#39853]
**Issue description:**
List of bugs that break FBX on https://github.com/godotengine/godot/pull/39418

**Steps to reproduce:**
Load. 

For each use case please post a broken model screenshot and the FBX. Post the git hash.

**Comment by fire** [comment]
I'll post the fox fbx that breaks this.

[f993eb95eda14be3949d23309ff13d76.zip](https://github.com/godotengine/godot/files/4838503/f993eb95eda14be3949d23309ff13d76.zip)


https://sketchfab.com/3d-models/low-poly-fox-by-pixelmannen-animated-371dea88d7e04a76af5763f2a36866bc

![image](https://user-images.githubusercontent.com/32321/85886349-c53a4b80-b79a-11ea-9586-f04a9eae1b77.png)

**Comment by fire** [comment]
Can reproduce in 4d667dadb90bb87245dba877970ff913beafa388

**Comment by RevoluPowered** [comment]
OK so the problem with loading a random model from sketchfab is that I really need to know a lot of info about how the rig was made, what specific parts break.

Otherwise it will take many more hours to debug each model which is reported.

Please post the verbose log output run the editor with -v and open project with command line, when you re-import the file on the ticket and I can look into it further with the log which is required. Importer often reports errors in the verbose log output and it's more useful.

**Comment by fire** [comment]
Can still reproduce in c4c211c.

**Comment by fire** [comment]
I'm not able to find the editor data and answer revolu's questions.
