### ISSUE TITLE
Sign official Godot releases with GPG

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#3989]
In last month there were two situations in which Open Source Software website got hacked and filled with trojan horses/ransomware ( [Linux Mint](http://www.pcworld.com/article/3035682/security/hackers-planted-a-backdoor-inside-a-compromised-version-of-linux-mint.html), [Transmission](http://arstechnica.com/security/2016/03/first-mac-targeting-ransomware-hits-transmission-users-researchers-say/) ). I remember, that Godot website was also often target of crackers ( mostly when it was hosted on Wordpress )...

So, I think that all files put on website should be signed with GPG keys ( and it would be goog if those keys got signed by some other people that you met in person in real life ), so we will be sure it's not a malware.

@reduz @punto- @akien-mga

**Comment by akien-mga** [comment]
I have no clue how to do it, but yeah it would be a good idea :)

**Comment by Marqin** [comment]
In most ideal case we should also sign all commits ( like [here](https://mikegerwitz.com/papers/git-horror-story) ).

Debian have some nice [docs](https://wiki.debian.org/Keysigning) about signing, and there is this [list of good practices](https://help.riseup.net/en/security/message-security/openpgp/best-practices).

**Comment by est31** [comment]
One problem with signing commits is that bzr-git doesn't work with it: https://bugs.launchpad.net/ubuntu/+source/bzr-git/+bug/1084403

But there already is one commit in godot that's signed, so we can forget compat with bzr-git.

Signing binaries / release tags? Very nice!

**Comment by est31** [comment]
For the context: bzr-git is the classical way to do nightly build PPAs.

**Comment by Marqin** [comment]
Launchpad supports GIT from some time. It's still not possible to push to
PPAs with it?

2016-03-10 23:56 GMT+01:00 est31 <notifications@github.com>:

**Comment by Marqin** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

>But there already is one commit in godot that's signed, so we can forget compat with bzr-git.

All my commits in Godot are signed with my key.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCgAGBQJW4gBvAAoJEDB4s+IRDWlHBmoP/0y5gFh1+j3DZjQP/+JvEExB
d9TJiKKAWP4oBO0ozUl2nn78F937DPvurIFQuqFpoWybTZbUD1B7zwH/ftS8+KaJ
89VladNDCQmoKxCxnxJ9Eg2vUpJcVFQbLJ6Djk80aBIT6gTqf5+QZfUkDsvqQhjJ
04sZ5vS+liRd0+FjTWvd8zlAW+hNt9aRNQCWLnKUWQXf39u2y3nh8b9/yxYWj/60
U/HCjPTNtBTcaXlcpHgEwA4GPKdPyByW9cXOxsgyRP7ckcmvxyGb+PBH/6K3LcPZ
37rjVfER700108uCW+bTcS4Ug4GPRMJHIDrUTrDiTAitXifjqJQoTeqGAuUpiP1l
2CZSgt+ZHJ2OpEhj+FKckCEwSnS+pnqZUtfrJmkshLTN6AXIsW//2fwtvdgdPUoi
qDJcc1wWTaZXHbtj+MMK3F3t266BSXX+AXKyYeFfxxDk3mnFJfX6cp1YbuMVyrGP
Gy/B6bhvsWu3IkObRQexf9qDi9Nxa8PtGwYZ+754U9yA0zbkFr+wNxGHMr1efSUJ
KdwUpn03h//1AHx9IYG0p9PTa+NsbF9381oYZnxJoMaFV4L9npwCND9EyiJyhgHI
IN0HeNF29uA2YX+qi9NHt/TCI6dvH5eXbAnvf8yNfIimNMTZ816X8B44JKiSg/Qi
0u5xx42Qc8p6JueCkf0w
=juZQ
-----END PGP SIGNATURE-----

**Comment by aaronfranke** [comment]
By the way, when it comes to signing commits, the Git client I use, [GitKraken](https://www.gitkraken.com), now has [automated signing](https://support.gitkraken.com/git-workflows-and-extensions/commit-signing-with-gpg/). I can simply give GitKraken my GPG key information and it automatically signs my commits. You can expect all future commits from me to be GPG signed (shows up as "Verified" on GitHub).

**Comment by Calinou** [comment]
Do we still plan on doing this? GPG verification for "end-user" software seems to be on the way out, unless required by the package manager (apt, DNF, ...).

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
