### ISSUE TITLE
Animation Tree is not using latest animations from Animation Player

### ISSUE THREAD

**Issue by RobTheFiveNine** [godotengine/godot#39926]
**Godot version:**
v3.2.1.stable

**OS/device including version:**
Ubuntu 18.04

**Issue description:**
When playing an animation in an `AnimationTree`, it is not using the animation that is saved in the corresponding `AnimationPlayer` - it seems to be using some kind of cached version.

**Steps to reproduce:**
- Clone this repository: https://github.com/RobTheFiveNine/godot-animation-tree-bug
- Open the Test scene
- Check the `Test` animation in `MovementPlayer` and see that neither tracks are enabled, and that if the `Hip` track was enabled, it would rotate the `Hip` bone
- Enable the `AnimationTree` node, and then play the `Test` animation, which should play the previously checked `Test` animation of `MovementPlayer`
- See that it rotates the `Hip` bone, even though the track is disabled

I have recorded a video to demonstrate this, as it's a bit easier to show it. You can find the demonstration video here: https://imgur.com/a/eJOMxxT

**Minimal reproduction project:**
https://github.com/RobTheFiveNine/godot-animation-tree-bug

**Comment by RobTheFiveNine** [comment]
An additional point that seems noteworthy - even though the Animation Tree doesn't pickup the changes to the track, if you edit the length of the animation in the Animation Player, that will be applied, but it will still play the old animation (i.e. in the case of the example, the hip rotating).

**Comment by RonanZe** [comment]
I also have some problems of sync between the AnimationTree and AnimationPlayer (and what seems to be the cache system of the AnimationTree?)
Here is the error message I got after $Level.queue_free() the Level node and reloading it with add_node(level_instance):

`E 0:00:27.960   get_node: Node not found: /root/Level/Dynamics/NpcSysB/CharacterDirection/CSkin.
  <C++ Error>   Condition "!node" is true. Returned: __null
  <C++ Source>  scene/main/node.cpp:1381 @ get_node()`
`E 0:00:27.971   _update_caches: AnimationTree: 'run-fast-loop', couldn't resolve track:  '/root/Level/Dynamics/NpcSysB/CharacterDirection/CSkin'
  <C++ Source>  scene/animation/animation_tree.cpp:581 @ _update_caches()
`

Not sure if it come from the same issue. Maybe it's best to open a new bug report?

Overall, I find the current design with cached AnimationPlayer a bit troublesome.
It lacks functions to collect datas from the AnimationTree and force you to use "method tracks" that are then cached in the AnimationTree (?) and lead you to all kind of bugs because it use it's own system and not the Godot's Tree system.
