### ISSUE TITLE
Particles bouncing off of collision objects?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#3994]
I'd like to be able to make particle systems react to physical world around it.
Like sparks bouncing off the floor etc.

**Comment by puppetmaster-** [comment]
I've ask some time ago https://github.com/godotengine/godot/issues/2334 It would be cool if we can have a scene emitter. Scene particles could then react as normal with the physical world.

**Comment by bojidar-bg** [comment]
That might be quite laggy, but depends on how fast raycasts would be... :smile:

**Comment by akien-mga** [comment]
If it's implemented, it should probably be done within a new node to avoid having to make the Particle node overly complicated (and more performance-intensive). Something like a RigidParticle that would inherit from Particle maybe.

**Comment by unfa** [comment]
I think that emitting scenes could be a great way to handle this and many other things aswell!

**Comment by Calinou** [comment]
It eventually could happen in Godot 3.0, especially since one is able to process the particles on the GPU nowadays (using something like compute shaders, which are found in OpenGL ES 3.1).

**Comment by unfa** [comment]
I saw physics-enabled particles in Unreal Tournament 2004 - the game didn't use normalmaps yet, but had nice particle effects with physics, so for sure they were computed on the CPU. It wasn't however an engine that'd run on Mobile Devices though...

**Comment by kubecz3k** [comment]
This thing is on the 3.0 wish-list so for sure it will be considered when we will have new renderer :)

**Comment by reduz** [comment]
planned for 3.1

**Comment by aaronfranke** [comment]
Is it still planned for 3.1?

**Comment by KoBeWi** [comment]
Looks like some people already did it themselves, e.g. https://www.youtube.com/watch?v=8Q77OlffvfQ

**Comment by asheraryam** [comment]
This plugin has been in the works for a while and not only does particle collision but many other things as well.

https://gitlab.com/polymorphcool/futari-addon

The videos are usually not hosted on youtube so you'll have to search for the vimeo and peertube links.

**Comment by alpinus4** [comment]
Will it be added in 3.2?

**Comment by Calinou** [comment]
@alpinus4 This will likely be added in 4.0 with the Vulkan renderer.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
For the record, this was implemented in `master` by https://github.com/godotengine/godot/pull/42628.
