### ISSUE TITLE
Editor crashes when selecting more than 5 lines and duplicating keyframes in the animation editor

### ISSUE THREAD

**Issue by zkukulj** [godotengine/godot#39940]
3.2.2 stable 

Windows 10 64bit, Nvidia 1070

Selecting multiple lines in animation player in order to duplicate keyframes crashed Godot .. however selecting only up to 5 lines with keyframes and then duplicating worked fine.

Images attached describing selection which produced crash, and another one with success on copying when less then 5 lines duplicated at the time.
![2020-06-29_11-50-09](https://user-images.githubusercontent.com/3915548/85995965-98d43880-ba01-11ea-884a-12c13932ee8f.jpg)
![2020-06-29_11-34-58](https://user-images.githubusercontent.com/3915548/85995973-996ccf00-ba01-11ea-8706-b6d1ec5506c7.jpg)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@zkukulj If you can still reproduce this on Godot 3.4.3 or later, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
