### ISSUE TITLE
Blender-style object manipulation with keyboard?

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#3995]
It'd be a great feature to have to be able to use Bldender-style node manipulation keyboard control like:

g - grab (move, translate)
r - rotate
s - scale
m - mirror

after these are initiated the user can press x, y or z to select an axis to manipulate
also using Alt modifier selects two other axis.

**Examples:**

The user presses (in order) and actions occur:
- M, X, Enter - the node is mirrored (scaled -100%) in X axis;
- G, X, 5, Enter - the noded selected is translated in axis X by 5 units;
- R, Y, -90, Enter - the node is rotated along Y axis 90 degress counterclockwise;
- S, Alt+Z, 2, Enter - the node is scale5 by 200% in axis X and Y (all but Z).

Also an action
x - delete, just like pressing "Delete" key (not htat this is using X as an action, not axis modifier!)

**Comment by bojidar-bg** [comment]
:+1: for axis selection, though I like T more than G

**Comment by Masterblop** [comment]
I'd like it to be also introduced the function "zoom on cursor"! :)

**Comment by unfa** [comment]
@Masterblop I'm not sure what you mean - isn't that a completely unrelated issue?

**Comment by bojidar-bg** [comment]
@Masterblop ~ This is already existing (I think it was bound to F), and it is another issue.

To everybody ~ Please, don't bloat conversations on issues by mentioning "just another feature that would be nice"... :smile:

**Comment by nunodonato** [comment]
this one is easy to do, just a matter of having The Powers That Be approving it :)

**Comment by karroffel** [comment]
Switching from Blender to Godot always feels weird, the quick scaling, rotating, moving shortcuts are really awesome and I miss them a lot, would be awesome to have them.

**Comment by reduz** [comment]
The way Godot works is sort of in the middle, so it's not too different to
other 3D apps, and you can configure it to work like Maya too.
I have no idea which amount of users come from Blender, but I prefer Godot
stays rather neutral on this.
Maybe this could somehow be added via addon?

**Comment by karroffel** [comment]
Godot already has a Blender/Maya navigation scheme for rotating/panning the camera, couldn't we extend those or create a separate setting for object manipulation?

Would be interesting to have those implemented as addons, but I'm not sure how complex that would be to make.

**Comment by hubbyist** [comment]
adding "shortcut profiles" support may be a good solution. User can choose between "Godot", "Maya", "Blender", "Custom" etc. shortcut schemes and customize if it feels something is missing.

**Comment by JayFontenot** [comment]
So I got started on this. No typing in values yet, but otherwise I feel like I've got the major functionality in now ^^ https://github.com/JayFontenot/godot/tree/Blender-like-spatial-manipulation

**Comment by cschar** [comment]
@ComradeJay is it able to be installed via some 'plugin' mechanism?
https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/index.html

I'd be cool if it was plug'n'play like in blender where you can 'toggle' addons.

**Comment by ComradeJay** [comment]
> @ComradeJay is it able to be installed via some 'plugin' mechanism?
> https://docs.godotengine.org/en/3.1/tutorials/plugins/editor/index.html
> 
> I'd be cool if it was plug'n'play like in blender where you can 'toggle' addons.

I edited spatial_editor_plugin.cpp directly in order to implement the functionality, so you'd have to replace that file somehow in order to implement it as I've coded. You could probably make a plugin that does it, but idk how. I could try and compile binaries for you if you're having trouble with that.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
Note that there's already an open proposal about this: https://github.com/godotengine/godot-proposals/issues/1215
