### ISSUE TITLE
TextFiles resources are uneditable after closing the editor

### ISSUE THREAD

**Issue by NekiCoule** [godotengine/godot#39964]
**Godot version:**
3.2.2.stable

**OS/device including version: **
Windows 10

**Issue description:**
TextFile .tres ressources with data in them gets uneditable inside Godot Editor after closure.

**Steps to reproduce:**

1. Create a TextFile .tres ressource file
2. Write some text in it
3. Save the file
4. Close Godot
5. Open Godot
6. The TextFile ressource is now a common Ressource file and can't be opened anymore.

**Comment by Calinou** [comment]
You shouldn't save TextFiles with a `.tres` extension, as that's the text-based resource extension. Use another extension like `.txt` instead.

The save dialog should prevent you from doing so.

**Comment by NekiCoule** [comment]
But I can't see .txt files in my Godot file system. I thought you needed to go through a .tres, the only thing I saw to create a file with only string in it.

**Comment by Calinou** [comment]
@NekiCoule That's because `.txt` files aren't considered resources by Godot. You can still open them using the **Open** action in the script editor then changing the filter to show all files (https://github.com/godotengine/godot/issues/24187).

**Comment by Kylogias** [comment]
I just tested, and it looks like that when you save the file, it overwrites the resource data as well, making the file a non-functional resource.

**Comment by jasonwinterpixel** [comment]
From my testing, TextFile's dont work.

When you create a TextFile the file creation menu forces the .tres extension. If you open the text_file.tres in the script editor and save it, it breaks the .tres formatting.

If you remove the .txt extension, it dissapears from the project menu.

If you put a plain .txt file into a export(TextFile) variable, the game crashes when trying to load it.

Seems like TextFiles do not work.

**Comment by SpaceAceMonkey** [comment]
This is still an issue. I don't understand how this workflow is supposed to go. Here is what currently happens:
- 1: Create a new resource in the Godot UI.
  - You are _forced_ to save the file with a .tres or .res extension. If you modify the extension to, say, .txt, Godot will give an error when you try to save, and no file will be created.
- 2: Open the file in any other text editor, and you will see Godot metadata. If you open it in the Godot editor, you will be presented with a blank document.
- 3: Edit the file as needed in the Godot editor, save.
- 4: Close and re-open the editor. You will now receive parsing errors for the resource you just created, because the parser is looking for the `[metadata]` stuff.

Is the TextFile resource type even intended for use by the end-user? If not, why are we allowed to select it when creating a resource? As far as I can tell, this resource type is completely broken and unusable.

**Comment by Calinou** [comment]
> Is the TextFile resource type even intended for use by the end-user? If not, why are we allowed to select it when creating a resource? As far as I can tell, this resource type is completely broken and unusable.

TextFile was only added to make it possible to edit non-script files (such as READMEs) using the Godot script editor: https://github.com/godotengine/godot/issues/24187
