### ISSUE TITLE
Export HTML5 demos on releasing

### ISSUE THREAD

**Issue by techtonik** [godotengine/godot#4000]
http://www.godotengine.org/download (and other pages) doesn't showcase Godot capabilities in HTML5 export, which is essential for many game jams to share your creations.

I'd expect to just find links to all exported demos so that I click through them for each release to estimate maturity, track progress and add more (problematic) demos.

**Comment by akien-mga** [comment]
But maturity is not good, so that would be counter-productive.

**Comment by techtonik** [comment]
I am not sure how it relates to productivity. Is the reason is that users should not know that web export support is poor? But isn't it a worse user experience if users download and try it only to find it is broken?

IMO an explanation and a link to tracker issues related to web export will do more good than bad.

**Comment by akien-mga** [comment]
It would be counter-productive as Godot is not an HTML5 engine. It's an engine that produces performat code for desktop and mobile devices, and it does happen to have an HTML5 template using a technology (asm.js) that *can't* deliver good performance (it could probably be better than it is currently, but probably never as good as native code for desktop and mobile).

So showing half-broken HTML5 demos would just have the consequence that newcomers who not even try Godot at all, because they would assume that the native code performance is as bad as the HTML5 one. By not providing HTML5 demos, we allow users to get intrigued by our cool looking screenshots and descriptions, then download a very lightweight editor with demos and run them natively on their desktop machine, thus seeing that Godot *is* pretty good.

Seems like basic communication to me to not start approaching people by showing them your flaws. It doesn't mean that we're hiding our flaws, just that we don't put them forward.
