### ISSUE TITLE
Revised: Export misses .ogg files.

### ISSUE THREAD

**Issue by JonathanGrant92** [godotengine/godot#40079]
The zipped archive requires the .ogg files in the soundtrack folder, not just the .ogg.import files. If i were to export the project, MusicPlayer.gd will not have any .ogg files to load to the scene's AudioStreamPlayer node, hence no music for exported copies. Otherwise, the music player scene works as intended from within the Godot editor and the executable even works properly from within the project folder

Adding *.ogg to the export filter doesn't add the corresponding resources to the exported project, which is required for the music player to work. I can think of two work-around solutions. Loading the music files from an external directory, but ../soundtrack/ as resource path works inside the godot editor and not in the executable with soundtrack folder in the same directory.  The most obvious option is to create an AudioStreamPlayer for every single audio file and use a script on the parent node to play each child as needed. I'm not especially keen on doing this, but I will consider experimenting with it tomorrow.

I know that scene nodes have immediate access to the resources internally. Is there a visible path to access those resources in script?

Suggested feature: 'export everything' export mode please? Evidently, 'export all resources in the project' is not sufficient for some users' needs. 😄 

Missing .ogg files, obviously.
~~[MusicPlayerDemo.zip](https://github.com/godotengine/godot/files/4867784/MusicPlayerDemo.zip)~~
Edit: I am posting a repository link to the source project without the entire fonts package and with some of the .ogg music. Thank you for your patience.

[source project repo](https://github.com/JonathanGrant92/MusicPlayerDemo/tree/master/MusicPlayerDemo)

**Comment by JonathanGrant92** [comment]
The creative commons music is at https://dos88.itch.io/dos-88-music-library. I don't feel justified directly uploading the ogg files of DOS88's work.

**Comment by Calinou** [comment]
Ogg Vorbis *is* treated as an imported resource by Godot, so you shouldn't need to add it to your non-resource export filter. Double-check the casing of your file names, as the virtual filesystem is case-sensitive even on Windows.

**Comment by JonathanGrant92** [comment]
Ah, that issue template is much easier for me to read, thank you.

name | about | title | labels | assignees
-- | -- | -- | -- | --
Bug report | Report a bug in Godot |   |   |  


Godot version: 3.2.1

OS/device including version: Windows 10 Home 10.0.18363

Issue description: Export does not include .ogg files, only their .ogg.import files, regardless of whether the export is .zip or .exe w/ .pck, etc.

Steps to reproduce: Test run the project in Godot. It should work. Then, try exporting the file as an executable to a location outside the project and run it. The music player will play no music and the command shell will report a 0 indexing error as I haven't coded any exception handling in the script. Now try exporting the project as .zip and you can observe that the cause of the error are missing .ogg files.

Minimal reproduction project: I am sharing the source project via repo because of the 10MB limit applied after the initial post. It will include some of the .ogg files for testing purposes.
[source project repo](https://github.com/JonathanGrant92/MusicPlayerDemo/tree/master/MusicPlayerDemo)

More details: I tried removing the dash and capitalization from the name of an audio, imported it through the editor ui for good measure, and exported the project as zip. The .ogg file is still missing.

**Comment by pfertyk** [comment]
Today I tried exporting the .zip with Godot 4.4 on Ubuntu 22.04 and encountered the same issue. It also didn't work when I changed the files to .wav and .mp3. The workaround in my case was to copy the files manually into the .zip file after the export was done.

**Comment by Calinou** [comment]
> Godot 4.4

There is no Godot 4.4. Are you referring to Godot 3.4 or 4.0.alpha4?

**Comment by pfertyk** [comment]
Right, sorry, I meant 3.4.4 :) I've also checked 3.4.5 and 3.5 since yesterday, same issue :(

**Comment by DeeJayLSP** [comment]
I have experienced a similar problem a few weeks ago and I realized it wasn't actually a problem, but part of how Godot is designed to work with imported resources.

In my project, I made a "music" folder containing multiple music files. Then, I made a script to generate a Dictionary that would scan the folder for .ogg files, then use their basename as key, and its path as value, so I could play a music by simply pointing to its name.

However, since .ogg files are imported, then remapped with their .import files and deleted, the function is unable to find any .ogg files.

In order to solve this, I looked at the .import files. Even if the .ogg doesn't exist, but its .import exists, it can be loaded by specifying the original file's path.

I solved the dictionary generation function simply by telling it to look for .ogg.import instead, then stripping the .import from the path string so it would attempt to load the original file instead, which works due to remap.

I don't know if this is the problem that's happening since the issue author deleted the source, but for the case I explained, this is how it's supposed to be done. 

It's Godot's design, not a bug. Probably just undocumented.

**Comment by pfertyk** [comment]
I'll give it a try, but I think last time I've checked this the exported .zip file simply didn't contain any music files, same for .csv translation files. In your case, were you still able to import the original music file using the .ogg.import one?

**Comment by DeeJayLSP** [comment]
Do .import files for both music and translation exist in your export? If it does, then nothing wrong is happening.

When you place a music or image file in your project, Godot does a thing called Importing. It will take the data it needs from that file and place it on a folder called .import, at the root of the project. It will also generate a .import **file** at the side of that resource, which works as a remap to the data file at the .import **folder**.

If you have a file such as `res://music/lol.ogg` it won't be present on the exported project, but  trying to load it with ResourceLoader **will** work, because the imported data is present in the export.

**Comment by pfertyk** [comment]
OK, I've checked my code and it seems that GOAT (the project I'm using) was looking for .import files, but only in case of a debug build:

```
	assert (goat.GAME_RESOURCES_DIRECTORY)
	var voice_directory = goat.GAME_RESOURCES_DIRECTORY + "/voice/"
	var files = goat_utils.list_directory(voice_directory)
	for file in files:
		if file.ends_with(".import"):
			# Godot export workaround
			if not OS.is_debug_build():
				var actual_file = file.replace(".import", "")
				var basename = actual_file.get_basename()
				_register(actual_file, basename)
			else:
				continue
		var basename = file.get_basename()
		if file.ends_with(".txt"):
			var content = goat_utils.load_text_file(voice_directory + file)
			var seconds = float(content.strip_edges())
			_register(basename, basename, seconds)
		else:
			_register(file, basename)
```

It seems I also have to enable this if I want to import a game using a .zip file ;) Thanks a lot for the hint! :+1: 

However, this only worked with sounds. I'm afraid it still doesn't work with .csv, as they don't end up in the .import directory. I do end up with a .csv.import file and with .translation files. Do you know if there's a way to load .translation files dynamically? Without this option, I have to manually update the .zip file with the original .csv file, and later process it on my own (read each line and add translations).

**Comment by akien-mga** [comment]
This is not a bug and indeed working as intended. OGG files are imported, so the actual data that Godot uses is in the `.import` (`.godot/imported` in 4.0) folder, and the `filename.ogg.import` file points to that data.

When you do `load("filename.ogg")`, Godot will automatically use the `filename.ogg.import` file to remap to the actual imported file and it works out of the box.

On the other hand, if you walk through the directory manually using a low level API, `File.file_exists()` doesn't do those remaps. You can use `ResourceLoader.exists()` instead which takes remapping into account, as mentioned in the documentation: https://docs.godotengine.org/en/stable/classes/class_file.html#class-file-method-file-exists

**Comment by pfertyk** [comment]
Thanks for the explanation! Since my last comment I also figured out that importing .csv files is not required, I can work directly with .translation files (which was much better for my goal). So, I also consider this issue resolved ;)
