### ISSUE TITLE
Fullscreen toggle on and off tears screen/produces additional menu

### ISSUE THREAD

**Issue by LionArt** [godotengine/godot#40095]
**Godot version:**
Godot v3.2.2 stable (from Steam)

**OS/device including version:**

Windows 10 64 bit, Intel HD Graphics 520, DirectX  12, model WDDM 2.1

**Issue description:**
Visual bug with creating fake menu bar
![image](https://user-images.githubusercontent.com/37901946/86480810-09a38980-bd4f-11ea-9d0f-1f2d4c36b9e5.png)

**Steps to reproduce:**
Maximalize the window, toggle Fullscreen on, toggle Fullscreen off

**Minimal reproduction project:**
Doesn't apply

**Comment by pouleyKetchoupp** [comment]
I'm not able to reproduce with a new project on 3.2.2 stable:
Windows 10, Nvidia GeForce 940M

**Comment by LionArt** [comment]
If there is any more info I could provide to help with fixing this issue, I will be happy to do so.

**Comment by pouleyKetchoupp** [comment]
Thanks! At the moment I have no idea what could be the cause, but there are a few things that might help someone reproduce the issue:
- Check if you can reproduce it on the non-steam version: https://godotengine.org/download/windows
- Share the log from the system console window when the bug appears (`Editor>Toggle System Console` if the separate console window is not visible)
- Share your editor settings: `C:\Users\[user]\AppData\Roaming\Godot\editor_settings-3.tres`
(open it with a text editor first to check that it doesn't contain personal information you don't want to share)
- Share a minimum project you can reproduce it with (even empty, just to make sure it's not related to some project settings)
- Let us know if you can think of anything that is not standard about your setup (running on a tablet rather than desktop, custom Windows settings that might affect application windows, etc.)

**Comment by LionArt** [comment]
1. Can reproduce on non steam version (64 bit):
![image](https://user-images.githubusercontent.com/37901946/86539819-f97edc00-beff-11ea-8525-cfef027a9695.png)

2.
![image](https://user-images.githubusercontent.com/37901946/86539733-47471480-beff-11ea-853e-e2144851b805.png)

3.
[editor_settings-3.zip](https://github.com/godotengine/godot/files/4875385/editor_settings-3.zip)

4.
[Godot Project.zip](https://github.com/godotengine/godot/files/4875388/Godot.Project.zip)

5. Nothing unusual about my setup. 

BR,
Artur

**Comment by pouleyKetchoupp** [comment]
Thanks for the extra info! I'm still not able to reproduce it, but we'll see if someone else is able to or has a clue what to look for.

**Comment by Calinou** [comment]
@LionArt Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.
