### ISSUE TITLE
Array resizing to original size unexpectedly

### ISSUE THREAD

**Issue by Kylogias** [godotengine/godot#40178]
**Godot version:**

I originally encountered this bug in Godot 3.2.1, but I've been able to successfully reproduce it in 3.2.2

**OS/device including version:**

Windows 10 Version 10,0.18362 Build 18362

**Issue description:**

When I was testing a puzzle game I'm making, it consistently crashed on the second level when I got rid of some pieces (or whatever you call them) outside the size of the previous level. The weird thing is, I don't even resize the array where I'm keeping the pieces outside of changing the level, but it resizes back to the size of the first level unexpectedly right before where the game crashes. This even occurs when I change the size of the first level (with a similar error message) via the levels.json included in the assets.

**Steps to reproduce:**

--Run the attached game
--complete the first level (if necessary, I haven't fixed the part where the pieces that are necessary disappear before the game starts) (you can move a row/column by moving the piece in the direction you want it to go)
--just make puzzle pieces outside of the top-left 5x5 (size of the first level) disappear

**Minimal reproduction project:**

I'm a bit confused on how the bug actually works, so I'll just submit the most current version of the game where I encountered the issue

[Puzzle Game.zip](https://github.com/godotengine/godot/files/4882028/Puzzle.Game.zip)

**Comment by tom-jk** [comment]
This is a bug in your game logic and not Godot.

I added some prints to the check_adjacent function and the change_level function, here's an example of what it looks like when it errors out:

```
...
sze: 8, idx: (6, 7)
sze: 8, idx: (7, 7)
CHANGING LEVEL [1->2]
current_level: [[0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0]]
size: 5
5
sze: 5, idx: (0, 0)
sze: 5, idx: (1, 7)
(error is here)
```

When the player beats level 2, the game advances to the next level. It would error out because there is no level 3, except in change_level:

```gdscript
	level_number += 1
	level_number = level_number % levels.size()
```

you wrap level_number back to 1, so it loads level 1 again, and the piece_refs arrays are set back to size 5.

The real problem is that piece instances from the previous level hang about for a time, and in that time are processed and check adjacency with their position, which for some will be out of bounds. It looks like you've tried to guard against that with level_initialized, but for whatever reason it doesn't work (finicky timing stuff).

The solution is to add a check in pieces.gd _process for whether the instance is_queued_for_deletion(), like so:

```gdscript
func _process(delta):
	initialized = main.level_initialized
	if initialized and not is_queued_for_deletion():
		...
```

and then you probably don't need to check level_initialized anymore. There could be a better fix but this stops your game from crashing, so I believe **this bug can be closed**.

**Comment by Kylogias** [comment]
Wow, I didn't know that is_queued_for_deletion() existed, thanks! and also, the report is closed
