### ISSUE TITLE
Additional Exporting Mode for Optimized Binary Size and Game Performance

### ISSUE THREAD

**Issue by KelinciFX** [godotengine/godot#4020]
**A.] As we know, Godot has One mode for exporting a godot project.**

We just need to make sure that Export Template for desired platform there, and then hit Export Button. But with C++, we need to re-compile our game on every changes we made, and also need to compile export template before hit Export button. By using GDScript, we'll most likely get fast made Game with "acceptable" performance. Instead, we'll wait some minutes even hours to compile and re-compile for a higher performance game.

Still, both have the same downside, non-optimized binary size. A simple "HelloWord" game will have similar size as a simple "Jumper" game.

**B.] Compiling for Release Mode with AutoConverted GDScript to CPP**

As usual, coding the game using GDScript, fast prototyping as we have every changes done in second. And, whenever we think our game ready to be released, we are provided Two ways of Exporting.

1) Just like what Godot have now. There is export template. Hit Export button and the engine Start exporting. A short description could be added though, for example: "Fast Exporting. No need to spend some minutes or hours."

2) Compiling for Release. A Short description: "Slow Exporting. Could take some minutes or hours. Be warned". In this mode, the engine automatically convert all GDScript files into CPP and gather all resources first and then start Compiling (when it comes to Android, the engine calling Android NDK Toolchain).

This way, we could have 3 advantages:
- Make games faster (thanks to GDScript)
- Optimized binary size
- Having C++ performance (thanks to something like gdscript_to_cpp conveter and "compiling for release" mode).

**C.] Where the idea comes from?**
- Cocos Studio. It has Two modes for exporting project:
  1) Using pre-made libraries. The libraries are static. No need to compile on every changes. Take a few minutes. Bigger binary size and less performance if we use JavaScript as Scripting Language.
  2) Compiling the whole project for release. Takes minutes or hours (depend on machine rig), but well optimized binary size and performance.
- GameMaker Studio. It also has Two modes for exporting project:
  1) Export using Non-YYC (default mode). This way, GML (GameMaker Scripting Language) packed together with other resources and interpreted at runtime. Fast Export, but less performance.
  2) Export using YYC (YoYo Compiler). This way, GML and other related resources is converted into CPP by YoYoCompiler and then compiling to .so file done by Android NDK Toolchain (of course if we target Android Apk). Once the game compiled, there is .ini file that said something like, LLVM. Probably it's kind of modified LLVM Compiler. Long Export, but the performance much better.
- Unity3D. Two modes for exporting project provided:
  1) Using C# (Mono C# Compiler)
  2) Using IL2CPP (Intermediate Language To CPP. Convert Mono C# Compiler to C++ Compiler). More Info: http://blogs.unity3d.com/2015/05/06/an-introduction-to-ilcpp-internals/

http://blogs.unity3d.com/wp-content/uploads/2015/04/il2cpp-toolchain-smaller.png

Or, other methods which supposed to give better optimization on binary size and performance is most welcomed.

Edit 1: Added IL2CPP which used by Unity3D

**Comment by Sposito** [comment]
There was ever any side development on this?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
