### ISSUE TITLE
WindowDialog theme does not allow to define title background color/texture

### ISSUE THREAD

**Issue by cgeadas** [godotengine/godot#40267]
**Godot version:**
3.2.1.stable

**OS/device including version:**
Macos 10.15.5 (GLES2)

**Issue description:**
When setting a custom theme for a Dialog, the title background gets transparent and there is no option to set it's Color/Texture and/or Opacity.

![ImgTurzzleToolDialog](https://user-images.githubusercontent.com/61761248/87182621-67e6e400-c2dc-11ea-95e9-84561a850275.png)

This happens when changing the windows panel.

**Comment by Calinou** [comment]
This is because the window panel itself is used to draw the title bar background. You can do so by modifying its StyleBox, increasing the top Expand Margin to 20 pixels or so, and setting the top border width to 20 pixels if you'd like it to use a different background color.

**Comment by cgeadas** [comment]
Thank you for your explanation, it worked great. Let's hope this gets reflect on the documentation soon. (Or an explicit property in the theme class would also make sense).

**Comment by Calinou** [comment]
I'll reopen this as someone needs to document it still :slightly_smiling_face:

**Comment by cgeadas** [comment]
OK. Thank you :-)

**Comment by akien-mga** [comment]
Closing as per https://github.com/godotengine/godot/pull/43198#issuecomment-786050544, this is not something that can be documented in FileDialog, it's a problem with users not being fully aware of the object-oriented nature of Nodes in Godot and the impact it has on how they should use the class reference.
That issue is tracked in https://github.com/godotengine/godot-docs/issues/4425.
