### ISSUE TITLE
The container's margin values can't be set even after the scene is saved.

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#40273]
**Godot version:**

3.2.2.stable.official 64-bit

**OS/device including version:**

OS: Windows 10 64-bit version 2004 build 19041.329.
GPU: Intel UHD Graphics 620, driver version 27.20.100.8336, backend GLES3.

**Issue description:**

I'm following the UI tutorial in Godot Docs but the container's margin values can't be set (the value in the box has no effect at all). When I saved the scene and hit play, there's no margin (the margins change show in the editor both in the main window and the output window). And when I quited Godot and opened the project again, all the margins that I had set previously were reset to 0, as shown in this video [here](https://photos.app.goo.gl/vUCMR37uBzjGX6Kh7). 

I expect the editor to save the container's margin values when set.

**Steps to reproduce:**
1. Open the project.
2. Set HBoxContainer's margin.
3. Save the scene and hit play.
4. Quit Godot and open the project again. 

**Minimal reproduction project:**

[start.zip](https://github.com/godotengine/godot/files/4906157/start.zip)

**Comment by CoderEx24** [comment]
**Confirmed**
happens also on linux (5.5.0-kali1-amd64 #1 SMP Debian 5.5.13-2kali1 (2020-04-03) x86_64 GNU/Linux)

**Comment by groud** [comment]
This is an expected behavior. Children of containers get their anchors/margin values overridden by their parent.
It's even stated in the tutorial : "Parent containers control the size, the scale, the margins, and the anchors of their direct children. "
Editing those properties when you have a child of a Container will be disabled later on, to avoid confusion.

For the MarginContainer you have to modify the margins in the "Custom contants" section in the inspector.
