### ISSUE TITLE
Can not override setters / getters

### ISSUE THREAD

**Issue by mrimvo** [godotengine/godot#40288]
**Godot version:**
3.2.2 stable

**OS/device including version:**
Linux

**Issue description:**
I tried to override Label's `set_text(value)` to add custom logic.

Expected: method to be called when trying to set the text.
Observed: method is not called.

**Steps to reproduce:**

Run a scene with this Script attached to a Label:
```
extends Label

func _ready():
	text = "abc"
	
# This setter method is never called
func set_text(value):
	.set_text(value)
```

**Comment by Calinou** [comment]
You need to define a `_set()` method for this:

```gdscript
func _set(name, value):
    match name:
        "text":
            print("Text is being set to ", value)
            text = value
```

**Comment by mrimvo** [comment]
This works very well, thank you.

**Comment by NathanLovato** [comment]
This is already in the docs it seems

**Comment by NathanLovato** [comment]
This is already in the docs it seems

**Comment by xsellier** [comment]
> This is already in the docs it seems

MAy you please quote the documentation please?

**Comment by zimonitrome** [comment]
@NathanLovato Not sure if this is a duplicate but I would suggest re-opening this issue as per @vibrunazo's comment.

In general it would be nice to be able to override variable getters and setters, but I guess then we would need to be able to override class variables (attributes) too (which I wouldn't mind).

**Comment by NathanLovato** [comment]
I don't work at Godot or maintain these issues so I won't be able to help here. I just maintained the official documentation a couple years back.

There's likely a good reason why this is not possible anymore but you'll have to see this with someone who knows about the history of this feature.

**Comment by dalexeev** [comment]
@zimonitrome

* Native non-virtual methods cannot be overridden, see the warning at the end of the [section](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#inheritance). This is not a bug, but a limitation.
  * Specifically for setters/getters of built-in properties, you can _partially_ work around this by "overriding" these properties in `_set()` and `_get()`. This will work in the Inspector, when calling `set()` and `get()`, when serializing the object, but will not work if the engine modifies the property value on an internal event.
* Setters/getters of custom properties can be overridden, but this is only allowed for separated setters/getters.

**Comment by zimonitrome** [comment]
@dalexeev Thanks for the info. I'm aware this isn't a bug and I assume that's why this issue has the "enhancement" tag. I understand now that this issue regarded setters/getters of built-in properties, which is not my specific concern.

For custom properties, having separate setters and getters (as stand alone methods) makes sense to me, even if a tad clunky. Thanks for the suggestion.

In a more macro sense, why aren't properties virtual in the first place? Would this lead to some unforeseen consequences?

**Edit:**
Here is an issue regarding overriding variables: https://github.com/godotengine/godot-proposals/issues/338
Related draft PR: https://github.com/godotengine/godot/pull/93787
Issue for overriding custom setters/getters: https://github.com/godotengine/godot-proposals/issues/8045

**Comment by Alcalientre** [comment]
I am dealing with this right now and the way it works should definitely be improved. There appears to be no way to add behavior to the setting of a built in function without overriding the _set function, and if you do that, it seems you have to code yourself how the function handles the setting of every property, rather than being able to fall back on a default in any way.

I understand that I can just make my own variable that I set and which sets the native variable I want when it is set, but this just seems clunky and unnecessary. Why isn't there some way to just add some behavior to the _set function for some given property.

Now I have to go through like thousands of lines of code to change everywhere I was setting transparency on my main character mesh to instead set my custom variable, just because I realized I want it to adjust the transparency of child nodes whenever transparency is adjusted. And I guess I can look forward to having to do the same thing again whenever I might want to make a similar change.

Feels like a huge waste of time that shouldn't be necessary, and is a big discouragement to using the engine. I don't want to have to be 100% sure of how I'm going to structure all of my code before I start working, it's ridiculous.
