### ISSUE TITLE
"Edit sample" displays a broken panel

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4030]
**Issue description** (what happened, and what was expected):
In Godot 2.0.1 and master branch, when clicking "Edit sample" in the sample library, it loads the characteristics of the sample in the inspector (which is expected), but also displays a broken panel at the bottom:
![spectacle b30671](https://cloud.githubusercontent.com/assets/4701338/13728454/ab5e8e64-e919-11e5-9cef-9b8fdc73b9bb.png)

In 1.1-stable it used to display this:
![spectacle b31685](https://cloud.githubusercontent.com/assets/4701338/13728479/b4ed971c-e91a-11e5-8b76-2807cd901b6b.png)

**Steps to reproduce:**
Load a project that has a sample library, edit the sample library and click the "Edit sample" button of any sample.

**Comment by akien-mga** [comment]
BTW the panel when just selecting a SamplePlayer in the scene tree looks buggy too:
![spectacle t11342](https://cloud.githubusercontent.com/assets/4701338/13729144/8f742488-e92e-11e5-8852-c1e3c683ee51.png)

**Comment by TheHX** [comment]
I think the Sample editor should be moved to the bottom dock.

I've found another three occurences of the same problem, in the StreemPlayer, TileSet and GridMap editors. The problem with this editors, and with SamplePlayer editor is they edit some nodes without categories(2D/3D) and they aren't children of the toolbar, and because of this they show buggy.

Related to #3056.

**Comment by reduz** [comment]
sample editor is fixed already
