### ISSUE TITLE
C# Signals with custom parameter type do not appear in inspector 

### ISSUE THREAD

**Issue by trommlbomml** [godotengine/godot#40318]
**Godot version:**
3.2.2 Stable

**OS/device including version:**
- Ubuntu 20.20
- AMD Ryzen 5 3600
- Radeon RX550
- GLES3

**Issue description:**
When I create a signal in C# where the passed parameter in the delegate has a type of a custom class I have created in the project, then the signal does not appear in the inspector after recompile. 

If I change the parameter type to a custom enum type or a build-in class type from godot then the signal appears properly in the inspector.

**Steps to reproduce:**
1. Create C# project
2. Add a class to the project:
`public class Test
{
  public int Value { get; set; }
}`
3. Create a spatial node and attach a c# script
4. Add the following signal to the script:
`[Signal]
public delegate void MyCustomEvent(Test test);`
5. Hit compile
6. Check Inspector -> signal not present.
7. Change delegate Parameter type in script to e.g. Node:
`[Signal]
public delegate void MyCustomEvent(Node test);`
8. Compile.
9. Check inspector -> signal is there.

**Minimal reproduction project:**
EDIT: As someone from discord asked for a test project, here is a small project for 3.2.2 with a single scene: one node has a script with working signal and the other is not, see script implementations: [signal_test.zip](https://github.com/godotengine/godot/files/4909328/signal_test.zip)

**Comment by neikeq** [comment]
I think there's another issue about this but can't search it as I'm on my phone for a few days.
Right now, only `Godot.Object` derived types can interact with the engine (being exported, used in signals, etc).

**Comment by trommlbomml** [comment]
Only found #19868 which seems at least related to the topic. Furthermore primitive Types and enums are already an exception - they do not derive from Godot.Object either.

**Comment by raulsntos** [comment]
The MRP declares a signal with a parameter of type `Test`, the `Test` type is defined as a class that inherits from `System.Object` which is not valid, Godot only supports marshable types to be used with the engine (this means any of the types compatible with [`Variant`](https://docs.godotengine.org/en/stable/classes/class_variant.html)).

> Furthermore primitive Types and enums are already an exception - they do not derive from Godot.Object either and work in signals properly.

Only the types supported by the `Variant` class are supported. To know which types are supported you can take a look at the [`Variant.Type`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#enum-globalscope-variant-type) enum.

If the `Test` type is modified to inherit from `Godot.Object` instead (which makes it compatible with `Variant`), the signal shows up in the editor when I tested this in Godot 3.5.1.

Since this sounds more like a proposal than a bug I'll close it in favor of https://github.com/godotengine/godot-proposals/issues/997. To avoid splitting the conversation throughout multiple issues.
