### ISSUE TITLE
PacketPeerUDP.wait() infinite loop

### ISSUE THREAD

**Issue by peeet95** [godotengine/godot#4037]
**Operating system or device:**
Linux (posix)

**Issue description**:
PacketPeerUDP.wait() never wakes up. It should when receiving a package.

**Steps to reproduce:**

``` python
var udp = PacketPeerUDP.new()
udp.listen(12345)
udp.wait()
#never reaching here
```

**Mistake** (optional but very welcome):
In /drivers/unix/packet_peer_udp_posix.cpp In line 124 the while loop never finishes because p_wait equals true.
In the winsock implementation, p_wait isn't used at all.
I would expect the thread to block, so use p_wait, without the while loop. waisting cpu with polling
doesn't make sense in a wait-method

**Comment by reduz** [comment]
This is not really a bug, this is UDP. I'm not really sure why there is a wait() function, maybe @punto-  remembers why, but the whole concept of waiting for a packet on UDP is strange.

I think this method should be removed, what does everyone else think?

**Comment by punto-** [comment]
wait() is probably there to use the api in blocking mode, which works if
you're running a thread that listens from the network, the code is simpler
because you don't have to make a state machine that works over multiple
frames, it's just a loop that listens and processes the packet (on the
other hand, you have to make it thread safe). If it's correctly
implemented, it's not actually an infinite loop, it's sleeping, either on a
select(), poll(), or a blocking call to read() on the socket. Doesn't it
stop waiting when a packet arrives on the network?

**Comment by bojidar-bg** [comment]
Bump, can someone test it and reply to punto? ( @peeet95 )

**Comment by Faless** [comment]
> Doesn't it stop waiting when a packet arrives on the network?

@punto- I've tested it, it does not return after the first packet is received as it should be expected.

The reason is that the `_poll` function uses a while loop to fetch all the packets available on the buffer. This is okay in non blocking mode (i.e. when you call `get_available_packets_count()`) since it will stop after the first `WOULD_BLOCK`) but actively locks it forever in blocking mode (i.e. when calling `wait()`).

This should be an easy fix, I'm working on a PR to simply fetch the first packet when polling for a wait.
