### ISSUE TITLE
Add methods to get convex polygons

### ISSUE THREAD

**Issue by pfanne** [godotengine/godot#4041]
It would be nice if there was a binding for "TriangulatorPartition::ConvexPartition_HM".
Right now I am writing some buoyancy physics and it would be nice to have convex polygons instead of only being able to triangulate a polygon.
If this is a needed/wanted feature I could do a pull request myself.

**Comment by akien-mga** [comment]
Just had a quick look at this, `TriangulatorPartition` is a thirdparty library and not meant to be exposed as is. If we want to expose some of this functionality to scripting languages, it should be done via a Godot class (which could use the `triangulator.cpp` stuff). What would be the API like and its use cases?

**Comment by pfanne** [comment]
It's been a while, but I think I needed it to be able to intersect 2 arbitrary polygons to use the resulting polygon to calculate the area and centroid of the submerged part of the polygon to calculate the force of the displaced water. Most algorithms working on polygons are much simpler if you can work with convex polygons.

As for the API:
Unless you want to add TriangulatorPoly Class to gdscript it would probably best to keep the API simple and just export Triangulate_EC, Triangulate_OPT, Triangulate_MONO, ConvexPartition_HM, ConvexPartition_OPT and work with PoolVector2Arrays.
It should probably look somethling like this:

```C++
class Triangulator {
	public:
	PoolVector<PoolVector<Vector2> > Triangulate_EC(const PoolVector<Vector2> &polygon) const;
	PoolVector<PoolVector<Vector2> > Triangulate_OPT(const PoolVector<Vector2> &polygon) const;
	PoolVector<PoolVector<Vector2> > ConvexPartition_HM(const PoolVector<Vector2> &polygon) const;
	PoolVector<PoolVector<Vector2> > ConvexPartition_OPT(const PoolVector<Vector2> &polygon) const;
}
```

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
