### ISSUE TITLE
Container magically shrinks to minimal size on scene reload

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#40454]
**Godot version:**

3.2.2

**Issue description:**

![LIf9NwHBri](https://user-images.githubusercontent.com/2223172/87721654-14323a00-c7b7-11ea-9d44-348d00cdaec1.gif)

**Steps to reproduce:**
1. Create a scene with a container (PanelContainer is the easiest to observe)
2. Add a label (probably works with TextureRect etc. too)
3. Add some lines to the label, so the container expands
4. Undo your text (container should still be big)
5. **Save**
6. Reload scene
7. The container is magically back to small size, even though it was big when saving
(shrink also happens without reloading when you *touch* either handle of the container)

The container should shrink immediately to the small size.

This is similar to #21803 and #19252

**Comment by Leleat** [comment]
I think this is part of Control's intended behaviour and a feature. 

Usually the children's size and position will depend on the parent. But if the (combined) size of children Controls exceeds the parent node's size, the parent will dynamically expand to fit all children. But after you removed the text (so the child node shrinks), the parent can scale down to its own (min) size again. A use case for this feature: A table, which dynamically scales based on the amount of columns it has.

PS.
You also don't need to reload the scene. Just toggling the visiblity of the Control will update the size as well. 
The fact that Control nodes don't always automatically update their sizes seems to be a bug. And I remember reading about it somewhere here (this is how I got to know about the visibility-toggle workaround). Although I can't find an issue related to it now.

**Comment by KoBeWi** [comment]
> The fact that Control nodes don't always automatically update their sizes seems to be a bug.

That's what I said

> The container should shrink immediately to the small size.

**Comment by Leleat** [comment]
> That's what I said

Whoops, my bad. I missed that sentence and thought you meant that it shouldn't.

**Comment by me2beats** [comment]
Setting a Control `rect_min_size` `x` or `y` to value less than the current one resets rect position when reopening/reloading the scene.

**Steps to reproduce:**
1. Create a new empty scene
2. Add a Control as a root
As you can see, its `rect_size_x` is `0`
3. In `Inspector`, set its `rect_min_size_x` to `100` (for example).
As you can see, the control `rect_size` changed in the Inspector and  the control became bigger.
4. Now set it to any value smaller than the current one (say to `20`).
As you can see the control is not updated/redrawn.
Well this makes sense, because the `rect_size` has not changed (`rect_size_x` is still `100`)
5. Now `Add a new scene` and then go back to the main one (or Save and reload it with `Scene` - `Reload saved scene`).
As you can see, `rect_size_x` has changed and equals to `0`.

**Comment by me2beats** [comment]
I think the following is related:
1. repeat as above
2. repeat as above
3. repeat as above
4. press `Ctrl+Z` (to undo)
As you can see, `min_size_x` is changed to 0 in `Inspector` (it's ok), but the control is not redrawn in editor (it's not ok).
This is because `rect_size_x` is not changed (the bug is here).
5. reload/reopen the scene (repeat as above).
now the control is redrawn
