### ISSUE TITLE
SkeletonIk Scaling issue

### ISSUE THREAD

**Issue by barbaros83** [godotengine/godot#40466]
**Godot version:**

godot 3.2.3 beta1

**OS/device including version:**

OS: Solus Linux GPU: RX480 Backend: GLES3

**Issue description:**

SkeletonIk in godot 3.2.3 beta1 still doesnt work correctly when any node in the scene has a scaling other then 1.0

**Steps to reproduce:**
- i downloaded a model from mixamo, a collada, and weapon.
- then i added the scene containing the weapon to the scene of the character model, under the bone attachment node for the right hand.
- then under the weapon model i added a position3D.
- to the skeleton node i added a SkeletonIk( sometimes it crashes when adding the SkeletonIK node)
- then i selected the root and tip bone as left shoulder and left hand
- as the target node i selected the position3D
- it works fine when there is no scaling in the scene

**Minimal reproduction project:**

as soon as there is any scaling in the scene on any node,  the model behaves really weird, sometimes it makes the root and tip bone smaller or larger and never goes to the point specified

**Comment by barbaros83** [comment]
without scaling
![Screenshot from 2020-07-17 17-23-16](https://user-images.githubusercontent.com/59711483/87804595-637a7800-c854-11ea-8e0a-cece2ee7f8ea.png)

**Comment by barbaros83** [comment]
with scaling
![Screenshot from 2020-07-17 17-23-44](https://user-images.githubusercontent.com/59711483/87804635-6f663a00-c854-11ea-8aaa-60941407fee7.png)

**Comment by TwistedTwigleg** [comment]
It looks like the issue is that the SkeletonIK is not correctly getting the target position, which could be related to scale, but it could also be related to something else entirely. I might rename the issue to something like "SkeletonIK - Wrong target position used when scaling" or something similar, since the issue seems to be the target position being offset when there is scaling in the scene.
Regardless, this issue is definitely different than #25544, as that issue was the tip bone itself was being scaled incorrectly when using the `Override Basis` property. Here, the hand appears to be the correct scale, but the target position is not being handled correctly.

If possible, can you provide a download to a minimum project that shows the issue? A project already setup and showing the issue would be very helpful for debugging the issue and checking potential solutions.

One thing to try, and I have no idea if this will help or not, is moving the SkeletonIK node further up in the scene tree, so its code gets execute before the BoneAttachment. It is possible that the BoneAttachement being before the SkeletonIK is messing up how the SkeletonIK node gets the position, leading it to being offset.

Also, when you say it works fine with no scaling in the scene, which node do you mean? Is the `ranger` node being scaled or the Skeleton?

**Comment by barbaros83** [comment]
moving it up didnt work
![Screenshot from 2020-07-17 18-28-01](https://user-images.githubusercontent.com/59711483/87809217-52813500-c85b-11ea-89bc-ac39b6ee548f.png)

**Comment by barbaros83** [comment]
github doesnt allow me to upload the project, because its size is larger then 10mb, where do you prefer i should upload the project ?

**Comment by TwistedTwigleg** [comment]
Something like Google drive or Dropbox is fine.

**Comment by barbaros83** [comment]
by scaling i mean a parent node, something that eventualy touches the skeletonIk, if the scaling of the node doesnt touch skeletonIK, then its fine, maybe some other node in the same branch, or something on a diffrent node entirely

**Comment by TwistedTwigleg** [comment]
Hmm, interesting. I wonder if the BoneAttachement is causing the issue, the Skeleton, or the SkeletonIK node, since they'd all be affected. Does scaling the SkeletonIK node itself do anything?

**Comment by barbaros83** [comment]
https://drive.google.com/file/d/13GRKDzTWDXc7BPsHMvlgV4LMfyhdf5xQ/view?usp=sharing

**Comment by barbaros83** [comment]
the skeletonIk node does not inherit from spatial, how would i scale it ?

**Comment by TwistedTwigleg** [comment]
Ah, right, I forgot, its just a normal Node, so it doesn't have a scale.
I'll mess around with the test project and see if I can figure out what is going on.

**Comment by barbaros83** [comment]
is it an easy fix ?

**Comment by TwistedTwigleg** [comment]
> is it an easy fix ?

I don't know, to be honest. I haven't poked around in the SkeletonIK code and tried to fix it, and with many things, "easy" is relative. I do not expect it to be too difficult, since it seems to just be a position issue, but without having tried to fix the issue, I don't know.
I'll take a look at the source code and see if I can find a solution next week.

**Comment by vini-guerrero** [comment]
Having the same issue on MacOS - 3.2.3 Stable
Been trying to find a workaround for this to use for now, but still no luck...

![image](https://user-images.githubusercontent.com/18181786/102109866-4ce04900-3e13-11eb-9c74-55fcbf191190.png)

![image](https://user-images.githubusercontent.com/18181786/102110002-6d100800-3e13-11eb-9ed4-9fbfee85e404.png)
