### ISSUE TITLE
The "Add Child Node" button remains pressed after adding a node via shortcut

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#40464]
**Godot versions:**
4.0.dev 9e34ba48556b71f1f672b5be47d12b0e3f679b86
3.2.3.beta
3.2.2.stable
*Cannot* reproduce in 3.1.1.stable, regression?

**OS/device including version:**
Windows 10, GLES3

**Issue description:**
The "Add Child Node" button remains visually pressed after adding a node with <kbd>Ctrl</kbd> + <kbd>A</kbd>.

![Annotation 2020-07-17 130200](https://user-images.githubusercontent.com/17108460/87774980-01a71780-c82e-11ea-80ea-9d1edfd8310f.png)

Using a [custom theme](https://github.com/Xrayez/godot-editor-settings), but I think that shouldn't affect the behavior. If it does, that's still a bug which might happen under some theme conditions.

Stumbled upon this one while testing workarounds suggested in godotengine/godot-proposals#1206.

**Steps to reproduce:**
1. Create empty scene.
2. <kbd>Ctrl</kbd> + <kbd>A</kbd>, might need to do this several times.

**Comment by Calinou** [comment]
I can reproduce this on 3.2.2, as long as I'm not on the 2D tab when I press <kbd>Ctrl + A</kbd>.

**Comment by Xrayez** [comment]
Regression from 1e6fa5d1a553fdf76840762024420fba3a720e70, #25573, @pouleyKetchoupp what do you think could cause this? Note that before your change, the button doesn't get highlighted at all under any circumstance (if using shortcut).

**Comment by pouleyKetchoupp** [comment]
@Xrayez Maybe the release event doesn't go through when there's a popup on top? That would be my first guess given the logic in `BaseButton::_unhandled_input`, but only debugging could tell.

Also it looks like it doesn't work the same way on 3.2 and master.

3.2 version:
https://github.com/godotengine/godot/blob/89f57ae12244f3269c9e3fe4684e16ec1fd2c989/scene/gui/base_button.cpp#L356-L365

Master version:
https://github.com/godotengine/godot/blob/9e34ba48556b71f1f672b5be47d12b0e3f679b86/scene/gui/base_button.cpp#L338-L342

**Comment by Xrayez** [comment]
Yeah that's where I've found this at least... It's not high priority though.

**Comment by EricEzaM** [comment]
I found this as well when working on #42109. I can only get it to replicate in one scenario - but in this scenario the window does not popup at all, and the button stays pressed.

Sequence of events:
1. User Holds CTRL + A.
2. Button receives press event for this action, and `status.press_attempt` is now true. By default, BaseButton is action mode ACTION_MODE_BUTTON_RELEASE so the `pressed()` method has not been called yet.
3. User releases CTRL but A is still pressed.
4. This no longer matches the action, so the button is forever in the `press_attempt` state since the button does not think it has been released.
