### ISSUE TITLE
Import window doesn't appear at all

### ISSUE THREAD

**Issue by kremetis** [godotengine/godot#40471]
![20200717_142739](https://user-images.githubusercontent.com/68440503/87815358-d62b2980-c83b-11ea-9498-90ec228f2f43.jpg)
I've downloaded godot for the first time and I can't upload my textures properly without the import window. Any way to fix this? I've already tried redownloading and using older versions. Please help!

**Comment by Calinou** [comment]
Since Godot 3.0, assets no longer need to be explicitly imported before they can be used. Just place them in your project folder and you'll be able to use them immediately.

PS: Please don't ask support questions here. Use one of the other [community channels](https://godotengine.org/community) instead.

**Comment by kremetis** [comment]
Oh okay sorry, thank you very much!
