### ISSUE TITLE
Cursor locked by keyboard input

### ISSUE THREAD

**Issue by protito** [godotengine/godot#40530]
**Godot version:**

3.2.2.stable.official

**OS/device including version:**

OS: Pop-os! 20.04 (ubuntu)
Device: Lemur pro 2020

**Issue description:**

Cursor movement is locked if any key is pressed.
I'm using the trackpad, will test with a wired mouse.

**Steps to reproduce:**
Create new project
run
hit "a"  key and hold,  try to move cursor using trackpad, it wont move

**Minimal reproduction project:**

[test.zip](https://github.com/godotengine/godot/files/4945970/test.zip)

**Comment by Calinou** [comment]
I think many trackpad drivers will block trackpad input after pressing a key for a short amount of time to implement palm rejection. You may be able to [disable it](https://askubuntu.com/questions/931761/how-to-fix-palm-rejection-on-ubuntu-16-04-lts), which is recommended when using 3D applications with a trackpad.

**Comment by redoxCode** [comment]
As Calinou mentioned, this might be an issue with your OS settings. I have the same thing going on with Arch linux and fluxbox wm. However an external mouse is not affected as well as the arrowkeys (they don't lock the track pad).
You can easy test if it's a godot issue by observing if the same thing happens when you use other software than godot.
Not sure if it has to be in the documentation, but it won't hurt either I guess..

**Comment by protito** [comment]
Hi, thanks for the answer. Yes, this is an OS thing I wasn't aware of.
