### ISSUE TITLE
Cubic interpolation of rotations in 3d transform animation track is unpredictable.

### ISSUE THREAD

**Issue by mohrcore** [godotengine/godot#40592]
**Godot version:**
v.3.2.2.stable.official, v.3.2.3.beta.custom_build.bdd1e7486 (bdd1e74869cab44c062994cb8a5b3068fa7164d2)

**OS/device including version:**
Gentoo/Linux x86_64

**Issue description:**
Cubic interpolation of 3d rotations seems to produce unpredictable splines.

I tried to create a 3D animation using 3D transform track in AnimationPlayer node. I made 3 keyframes in total.
In the first two keyframes, the rotation of the node is unchanged, in the third, the object is rotated. Interpolating the animation with nearest and linear options seems to work fine. However if I switch the track interpolation to cubic, the node rotates towards the angle specified in the third keyframe and the back to the original angle within the period between first two keyframes. Then, after the second keyframe it bounces off and rotates again towards the angle specified in the third keyframe as it should.

Expected result: the node's rotation should stay unchanged during the period between first two keyframes (wrapping is set to clamp), then after the second frame it should smoothly rotate towards the angle specified by the third keyframe.

**Steps to reproduce:**

The simplest scenario has been already described above, however other animations of rotation of 3d transform also result unexpected interpolations. Some of these interpolations seem to be not even continuous (eg.: the rotation "bouncing" off the angle defined by keyframe instead of going through it smoothly).

The simplest steps for reproduction would be:
1. Create a 3D scene.
2. Place a node (MeshInstance for example)
3. Place AnimationPlayer as it's child
4. Create a simple animation in AnimationPlayer with 3D transform track for it's parent.
5. Place some keyframes, some of which should change node's rotation, others should keep the rotation from their forerunners.

**Minimal reproduction project:**
[godot_animation_bug.zip](https://github.com/godotengine/godot/files/4959593/godot_animation_bug.zip)

**Comment by fire** [comment]
I've been using https://github.com/KhronosGroup/glTF-Sample-Models/tree/5bbe0b378d703a506ce8ae12c7dc829e42546d3b/2.0/InterpolationTest to test too, but it's also different.

**Comment by mohrcore** [comment]
Ok, I checked the source code and the code for cubic slerps for quats looks really sketchy to me:

```C++
Quat Quat::cubic_slerp(const Quat &q, const Quat &prep, const Quat &postq, const real_t &t) const {
#ifdef MATH_CHECKS
	ERR_FAIL_COND_V_MSG(!is_normalized(), Quat(), "The start quaternion must be normalized.");
	ERR_FAIL_COND_V_MSG(!q.is_normalized(), Quat(), "The end quaternion must be normalized.");
#endif
	//the only way to do slerp :|
	real_t t2 = (1.0 - t) * t * 2;
	Quat sp = this->slerp(q, t);
	Quat sq = prep.slerpni(postq, t);
	return sp.slerpni(sq, t2);
}
```

If I get it right (`prep` is a quat before `*this` and `postq` is a quat after `q`), there's no way it would work in the scenario I've described. The third keyframe would have the `postq` quat, so when interpolating between `*this` and `q` which are the same, the result would gravitate towards postq just to go back to the same quat and the worst part is that the derivative would end up having a wrong sign. Maybe there's something I've overlooked in the implementation, but for now the presented interpolation method seems to me, to be fundamentally wrong.

**Comment by mohrcore** [comment]
@fire I'm not familiar with the whole glTF stuff, but it seems weird to me that with cubic interpolation the cube on gif stops overy 90 degrees.

**Comment by GNSS-Stylist** [comment]
This may be related to the wobbly/"wrong way around" interpolation of Quat when using cubic_slerp I stumbled upon as seen in this video:
https://youtu.be/6T5wmcpTBtk
The "triangle" and the camera as childs of the same spatial-node are using slerp. The car, using the same source values,  is first using cubic_slerp and later slerp_ni (which also seems to sometimes interpolate "wrong way around", although this might be a feature(?)).

Code for this test can be found from:
https://github.com/GNSS-Stylist/LOSolverDemo_Godot/tree/godot_quat_interpolation_issue
Interpolation is implemented in file LOScriptReplayer.gd. When using cubic_slerp, this is used:
quat = quat_a.cubic_slerp(quat_b, quat_pre_a, quat_post_b, fraction)
where quat_b, quat_pre_a, quat_post_b, fraction are the ones seen as text on the video and the result (quat) is labeled "interp" there.

What I expected was cubic_slerp to smoothen out those slight discontinuities in direction seen in slowed-down camera movement when piecewise (slerp) linear interpolation switches between "pieces", something like the SQUAD here:
https://www.gamasutra.com/blogs/VegardMyklebust/20150911/253461/Spherical_Spline_Quaternions_For_Dummies.php

"Disclaimer": I'm not very familiar with quaternions (just used them first time here, because I needed some kind of interpolation of orientations), so there might be false assumptions etc. in the text above.

Godot version: 3.2.2.stable
OS: Windows 10

**Comment by fire** [comment]
I submitted a pull request. https://github.com/godotengine/godot/pull/41626

**Comment by GNSS-Stylist** [comment]
Tried the fix with my "flying car demo": https://youtu.be/ZhJpJgQBAsU
"Wrong way around"-turns seem to be less frequent/severe in this (than in https://youtu.be/6T5wmcpTBtk ), but they still happen now and then. Wobbliness is gone, but this seems to follow slerp (see "diff (selected-slerp)") when not "glitching", instead of SQUAD/cubic-slerp(?).

**Comment by fire** [comment]
Can you make a flying demo for me to test with? Not sure if it's open source.

**Comment by GNSS-Stylist** [comment]
It can be found here: https://github.com/GNSS-Stylist/LOSolverDemo_Godot/tree/godot_quat_interpolation_issue
License for the code is MIT, 3D-models are CC-BY (not mine, I just used them).

**Comment by fire** [comment]
I don't see a test case that uses cubic_slerp?

**Comment by GNSS-Stylist** [comment]
You can change interpolation method of the car by changing "LOSolver_TimeShift"'s "Quat Interpolation Method". Quats used in the interpolation are printed in lower left corner. See my post above for some more info.

**Comment by fire** [comment]
Added a clamp function, and testing the change on cubic_slerp.

**Comment by GNSS-Stylist** [comment]
There seem to be discontinuities when using the latest commit ( https://github.com/godotengine/godot/commit/5c6e45ee9006633b7cdf8ccb237e5229c1908b92 ) in some cases, see https://youtu.be/61QawNpJeOA
Made some modifications to my demo (see previous messages) to better see these issues.

Some instructions can be found from readme.md, few most relevant in this context /changed (changed also some namings (hopefully better) and other stuff from the previous version):
- You can change interpolation method using "LOSolver_Interpolated->Quat interpolation method" and replay speed with "Main->Replay speed" (as shown in Godot's editor).
- F3-key changes camera to one looking at the X-axis basis vector, F4 to one more zoomed-in.
- Using "camera rig camera" (=F2) doesn't make sense here, since origins for both the object and camera are the same.
- Committed version skips 3/4 of the lines (="keyframes") of the source files to make interpolation issues more visible. You can change this using "readLineSkip" in LOScriptReplayer.gd.
- Press R to get rid of the traces (and restart).
- Location/orientation scripts (*.LOScript-files) consist of "keyframes" with a steady 125 ms interval, but since in the committed version 3/4 of these are skipped, they are effectively 0.5 s apart.
- Do not change "timeshift" nor activate "Visibility script". These don't make sense with this.

Sorry for this late reply, I didn't have time/energy to build anything usable before.

**Comment by fire** [comment]
If you're interested there's a survey of orientation interpolation methods at http://www.adrian-haarbach.de/interpolation-methods. The most interesting is are listed below:

>  RQBez:  The curve looks very similarto SQUAD, but is actually a uniform cu-bic B ́ezier curve of the quaternion coeffi-cients∈R4 with subsequent renormaliza-tion. The segments are joined withC2con-tinuity requirements, thus we have global control.

> CuBsp:  ThisC2curve is the uniformcumulative  cubic  B-spline  onSU(2),  in-troduced  by  [21]  and  used  in  [22,  27].The angular velocity graph shows that thiscurve minimizes angular accelerations.  Ithas local control, but the inner keyframesare only approximated.

They also have an executable demo with runtime costs.

**Comment by fire** [comment]
[godot_animation_bug.zip](https://github.com/godotengine/godot/files/7326457/godot_animation_bug.zip)

Update bug project for latest master.

**Comment by GNSS-Stylist** [comment]
Investigated this further (in godot 4) as I'm planning to use this for camera track with sparsely placed keys. Have to admit that I'm still "super confused" (as someone else in the stackexchange-link above)... But after days of mostly trials and errors managed to get somewhat smooth-looking movements out.
Video taken from the godot editor:

https://user-images.githubusercontent.com/50438441/150857377-b417fbbd-2d45-4f13-9c2a-ed20b41950b5.mp4

Red cube and axes show slerped rotations for comparison, blue cube shows the next key, green cube cubic_slerped rotations.

There are 4 identical keys between 20...26 s. Cubic_slerped object actually first rotates a bit over the "rest-position" there before settling and takes identical "step back" before going on. Not sure if this is how squad should work(?) However calculation of those helper quaternions uses quaternion log-function that has a division with the length of the vector part of the quaternion (that becomes zero when some of the subsequent source quaternions are identical) so I wrote some code to handle these cases. Anyone know how helper "tangent" quaternions are supposed to be calculated when some rotations are identical?

Here's another video from a running project:

https://user-images.githubusercontent.com/50438441/150860692-0d2e0dc6-79bd-44fc-98e3-39f71efcdfb3.mp4

Bottom part has the same objects as the previous video, on top there's objects following the same rotations as my previous videos/godot projects (red = slerped, green = cubic_slerped, yellow lines connecting the points used for interpolation).

Godot project (Godot 4):
[Quat_cubic_slerp_issue_single.zip](https://github.com/godotengine/godot/files/7928806/Quat_cubic_slerp_issue_single.zip)
You can fly around by first pressing CTRL and WASD-QE-keys/mouse wheel. Switch to 6DOF-mode (roll = R/F-keys) with TAB. "Playback speed" can be changed using number keys (7 = normal speed, 6 = half, 5 = quarter, 8 = double etc), for rewind keep SHIFT-pressed. Backspace resets playback.

Quaternion.c&h (Godot 4) sources:
[quaternion_modified_src.zip](https://github.com/godotengine/godot/files/7928880/quaternion_modified_src.zip)
I also tried code from the mentioned PR #53692, but there was some problem with it (which, still being super confused I don't remember any more). Wrote some functions as statics to keep my confusion at more tolerable level (it was easier to clone/compare some calculations from the source documents when using static functions).

Not sure if this is the way this is supposed to work. There are also some limits and such in the source files that are just thrown there and "seemed to work" so this is definitely not "release ready" code. But feel free to utilize these if you find them helpful.

**Comment by fire** [comment]
I'll investigate your notes over this week and the next.

**Comment by fire** [comment]
Discussed with @TokageItLab .

We discussed modified akima may be able to solve this. Tokage posted some plots of modified akima. The main part is the graphs and not the text.

![](https://jp.mathworks.com/help/matlab/ref/datainterpolationcomparisonexample_01_ja_JP.png)
![](https://jp.mathworks.com/help/matlab/ref/datainterpolationcomparisonexample_02_ja_JP.png)

**Comment by TokageItLab** [comment]
Quote from:
- https://slpr.sakura.ne.jp/qp/wp-content/uploads/2020/11/Akima_eye_c-1038x519.jpg
-https://jp.mathworks.com/help/matlab/ref/datainterpolationcomparisonexample_01_ja_JP.png
- https://jp.mathworks.com/help/matlab/ref/datainterpolationcomparisonexample_02_ja_JP.png

**Comment by TokageItLab** [comment]
The implementation that directly interpolate each element and does the normalization is probably wrong. I guess we need to adopt the difference and norm of the two quaternions into the modified akima formula.

**Comment by GNSS-Stylist** [comment]
While twiddling with this I decided to test also component-wise interpolation with standard cubic-interpolation. Here's the result:

https://user-images.githubusercontent.com/50438441/151156668-aa478b9b-2341-46a3-b892-259c5e5a1cad.mp4

To the eye looks to be quite close to squad, but sometimes goes wrong-way around.

Code (not pretty, just a quick hack to test this): 

```
static real_t cubic_interpolate_real(const real_t p_pre_a, const real_t p_a, const real_t p_b, const real_t p_post_b, real_t p_c) {
	// This is cloned straight from animation.cpp

	real_t p0 = p_pre_a;
	real_t p1 = p_a;
	real_t p2 = p_b;
	real_t p3 = p_post_b;

	real_t t = p_c;
	real_t t2 = t * t;
	real_t t3 = t2 * t;

	return 0.5f *
		((p1 * 2.0f) +
			(-p0 + p2) * t +
			(2.0f * p0 - 5.0f * p1 + 4 * p2 - p3) * t2 +
			(-p0 + 3.0f * p1 - 3.0f * p2 + p3) * t3);
}

Quaternion Quaternion::static_cubic_slerp(const Quaternion& p_q0, const Quaternion& p_q1, const Quaternion& p_q2, const Quaternion& p_q3, const real_t& p_t) {
	if (true) {
		return Quaternion(
			cubic_interpolate_real(p_q0.x, p_q1.x, p_q2.x, p_q3.x, p_t),
			cubic_interpolate_real(p_q0.y, p_q1.y, p_q2.y, p_q3.y, p_t),
			cubic_interpolate_real(p_q0.z, p_q1.z, p_q2.z, p_q3.z, p_t),
			cubic_interpolate_real(p_q0.w, p_q1.w, p_q2.w, p_q3.w, p_t)
		);
	}

	if (false) {
		// Test code to compare slerp and lerp
		// (just return lerp)
		// (This was active on the previous example)

		return static_lerp(p_q1, p_q2, p_t);
	}
```
Personally I will probably stick to squad for now (as it is good enough for my use case) but will still keep my eyes open for other methods.

**Comment by fire** [comment]
Headsup, I moved your project into a github git repo, I want to try the modified akima interpolation.

I added labels.

![image](https://user-images.githubusercontent.com/32321/153332596-6f4dd51b-99e4-47c8-b68c-b45b69ba2eed.png)


## Reference

https://github.com/fire/godot-40592

**Comment by fire** [comment]
@GNSS-Stylist I wish to use this an a benchmark for Godot Engine for 1) testing slerping vs cubic slerping 2) cubic slerping 1000 transforms for networking replication.

What are your thoughts? I wanted to have a license compatible or exactly the same as the Godot Engine MIT license.

**Comment by TokageItLab** [comment]
In my opinion, this issue seems to be confusing two issues.

1. cubic_slerp() may take a rotation path that is not the shortest
2. cubic_slerp() and cubic_interportion() cause overshoot

I'm not sure about issue 1, as I haven't tested it properly, but if it's correct about issue 1, I think we should close this issue and repost the these issues.

**Comment by GNSS-Stylist** [comment]
Made a pull request with added LICENSE-file (MIT) for @fire 's repo: https://github.com/fire/godot-40592/pull/1. Added Jon Ring and Roujel Williams to the "copyright-list" also, since the first person controller was created and modified by them. Personally I don't really care much about the copyright here, but can't decide on behalf of others.

Have to agree with @TokageItLab that this issue got somewhat bloated over time.

**Comment by SIsilicon** [comment]
Why am I here?

**Comment by SIsilicon** [comment]
The first person controller isn't mine actually. If you look in the [credits](https://github.com/SIsilicon/Godot-Ocean-Demo#credits) section of my project you'll see I got it from a tutorial by Jeremy Bullock.

**Comment by TokageItLab** [comment]
Superseded by #57951 and #57952.

**Comment by fire** [comment]
Reopened because we posted a new attempt at fixing this.

https://github.com/godotengine/godot/pull/63380
