### ISSUE TITLE
GDScript desync between editor and file

### ISSUE THREAD

**Issue by batmanasb** [godotengine/godot#4069]
**Operating system or device:**
Linux Mint 17.3

**Issue description** (what happened, and what was expected):
Editor doesn't recognize that the code has changed when you undo after a cut. If you cut a line of code and run it, stop, then undo, then run again the editor should recognize the change and update code in the file when pressing run, but instead it doesn't until you make another change.

**Steps to reproduce:**
1. Write a line of code ex: `print("hello)`
2. Run game ("hello" is have printed)
3. Cut that line of code
4. Run game ("hello" is not have printed)
5. Press Undo to restore that line of code
6. Run game ("hello" should have been printed but wasn't)
7. Add a new line
8. Run game ("hello" is printed)

**Note**
Title of this issue should be changed to something along the lines of "Editor doesn't recognize that the code has changed when you undo after a cut."

**Comment by Krzycho666** [comment]
It seems to be very similar to some[ other bug](https://github.com/godotengine/godot/issues/4068) that I've found. Making some change in code ( removing / redo / undo ) wont make effect after you compile it. But after putting at least one empty sign the changes are being noticed by Godot somehow and it works then as it should.

How to reproduce:
1. Write some code.
2. Compile it - check if it works.
3. Cut some code - check if it works again.
4. Make undo and compile - there won't be any change in behaviour since last check.
5. Make new line in code and compile - changes will be applied.

Is that the problem of yours?

**Comment by batmanasb** [comment]
Yes! That's the issue! Cutting, then RUN, then Undo, then RUN.

**Comment by demolitions** [comment]
I don't have that issue, running under Arch Linux, Godot compiled from GIT

**Comment by batmanasb** [comment]
Then maybe it's already fixed! But it's definitely still in the 2.0.1 binary

**Comment by reduz** [comment]
Sorry, can't reproduce in any way, i will guess this is fixed
