### ISSUE TITLE
intersect_point ignores collision_layer argument

### ISSUE THREAD

**Issue by IvanSoldano** [godotengine/godot#40705]
**Godot version:**

3.2.3 RC 1 win64

**OS/device including version**
Windows 10

**Issue description:**

Physics2DDirectSpaceState.intersect_point ignores the collision_layer argument and returns any intersecting area or body regardless of the layer it is on. Works fine in version 3.2.2 Stable win64

**Steps to reproduce:**
Use the reproduction project to check for collisions with the mouse pointer, notice how intersect_ray works correctly compared to intersect_point

**Minimal reproduction project:**

[IntersectPointCollisionLayerIgnored.zip](https://github.com/godotengine/godot/files/4976271/IntersectPointCollisionLayerIgnored.zip)

**Comment by madmiraal** [comment]
#40193 deliberately removed the collision layer checking, because it was thought that:
> `_intersect_point_impl()` isn't used for anything else than mouse picking, so making it ignore layers is safe.

Of course `_intersect_point_impl()` is also used by `PhysicsDirectSpaceState's` `intersect_point()` function, hence this issue.

My suggestion is to revert #40193 and its 3.2 counterpart #40280 and find an alternative solution for #11159.
