### ISSUE TITLE
Removing a CollisionShape or CollisionPolygon from a sleeping RigidBody at runtime breaks gravity in Bullet physics

### ISSUE THREAD

**Issue by hoontee** [godotengine/godot#40739]
**Godot version:**
3.2.3.rc1

**OS/device including version:**
Windows 10 2004

**Issue description:**
When removing a `CollisionShape` or `CollisionPolygon` from a sleeping `RigidBody` at runtime with the Bullet physics engine, its gravity stops working.
Does not occur with GodotPhysics.

**Steps to reproduce:**
Create a `RigidBody` with a `CollisionShape`, set `sleeping` to `true`, then attach the following script:
```GDScript
extends RigidBody

func _ready():
	var collision_shape = $CollisionShape
	add_child(collision_shape.duplicate())
	collision_shape.queue_free()
```
In this case, `queue_free` frees the old `CollisionShape` after Bullet initializes the physics body. It can be mitigated by calling `free` instead of `queue_free`.

**Minimal reproduction project:**
[Physics.zip](https://github.com/godotengine/godot/files/4979611/Physics.zip)

**Comment by hoontee** [comment]
Not reproducible in 3.2.3.rc3.

**Comment by madmiraal** [comment]
Reopening, because I can reproduce this issue in both `master` (bc813fd061) and 3.2.3.rc3 by delaying the replacement of the `CollisionShape` by one physics frame.

MRP 4.0: [40739-4.0.zip](https://github.com/godotengine/godot/files/5015481/40739-4.0.zip)
MRP 3.2: [40739-3.2.zip](https://github.com/godotengine/godot/files/5015482/40739-3.2.zip)
