### ISSUE TITLE
Cannot use functions from Singletons

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#40741]
**Godot version:**
4.0.dev.custom_build. 6de86946e

**Issue description:**
Using functions from Singletons, shows errors like:
```
Parser Error: Cannot find property "qq" on base "null"
```

**Minimal reproduction project:**
[RRRRRRRRRR.zip](https://github.com/godotengine/godot/files/4980584/RRRRRRRRRR.zip)

**Comment by creikey** [comment]
I think this has something to do with the scripts attached to the nodes also loaded as singletons , as in another test project where I have a separate `TestSingleton.gd` script called from a `Main.gd` script attached to a `Node2D` everything works out fine

**Comment by creikey** [comment]
After some poking around what I previously mentioned had nothing to do with the issue, the issue is inside of the gdscript analyzer, where it is making a reference to a singleton that has not been analyzed yet ( they are cyclically referenced ). However, even after removing the cyclic reference on one of the Node's ready functions, it still thought it was null, so it turns out that this has to do with the order singletons are analyzed I believe.

In the autoload tab, when the singletons are placed like this:

1. N3
2. N2

Now N2 can call `N3.qq()` in its ready function, and the inverse is true if you switch their order

**Comment by fracteed** [comment]
Can confirm that I also have this problem on master. Trying to access variables from an autoload singleton and getting the error 

Cannot get member "my_var" from "Node: xxxxx"

The last time I tried this project on master about a month ago, it worked, so I guess this is related to all the gdscript changes?
