### ISSUE TITLE
get_global_mouse_pos() doesn't respects stretch_aspect

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4075]
Windows 7 64 bits, Godot 2.0.1

I tried to add simple look at to my game, but I noticed a strange return value of the get_global_mouse_pos function(), leading to a wrong behaviour.

Test project: http://zylannprods.fr/dl/godot/LookAt.zip
Start the scene, look at seems fine. But resize the window horizontally or vertically so black bands appear. Notice the sprite doesn't looks at the mouse correctly.

It seems the virtual center stays nearby the origin of the window and doesn't "follows" the viewport:
![Screenshots](http://zylannprods.fr/images/screen/godot/LookAt_screens.png)

QA thread: http://godotengine.org/qa/1515/how-to-make-a-moving-character-look-at-the-mouse

**Comment by DenisComtesse** [comment]
I can confirm this behaviour. The easiest way to test it is to use a sprite and set its position with get_global_mouse_pos(). When there are no borders, the sprite is positioned correctly. but when you resize the window so that there are borders at the left and right or at the top and bottom, the sprite is displaced, because the engine seems to take the upper left corner of the window as the origin, without taking the borders into account.
