### ISSUE TITLE
GDScript: auto completion bugs

### ISSUE THREAD

**Issue by ThakeeNathees** [godotengine/godot#40933]
**Godot version:** v4.0.dev.custom_build 35ff38b3d

**OS/device including version:** windows 10

**Issue description:**
- no builtin types in type name (including "Variant") completion
in both variable type completion and function return type completion there is no builtin type
![Capture](https://user-images.githubusercontent.com/41085900/89092879-2f19c680-d3d3-11ea-9788-9a6dce2f648e.JPG)

- function argument suggestions are wrong (use with indexing)
![Capture](https://user-images.githubusercontent.com/41085900/89093345-380c9700-d3d7-11ea-8cc1-cd47ceb9ef99.JPG)

- no argument hint immediately after open a bracket
![Untitled-1](https://user-images.githubusercontent.com/41085900/89093451-1f50b100-d3d8-11ea-9d50-65500711d4a3.jpg)

- autocompletion of subclass suggest other subclasses too
![Capture](https://user-images.githubusercontent.com/41085900/89093113-190d0580-d3d5-11ea-8838-7e0c85038ef0.JPG)

```[tasklist]
### Resolved issues
- [ ] no builtin types in type name (including "Variant") completion in both variable type completion and function return type completion there is no builtin type
- [ ] function argument suggestions are wrong (use with indexing)
- [x] no argument hint immediately after open a bracket
- [ ] autocompletion of subclass suggest other subclasses too
```

**Comment by gvekan** [comment]
When working on https://github.com/godotengine/godot/issues/42382, I found that the example in that issue does not get any autocompletion options in `master`.

I found that `entries` was empty which stops the creation of the completion suggestions, but I have not researched why there are no entries..
https://github.com/godotengine/godot/blob/3c441baf6c11de564ee723fa8731ce40a0052fd9/editor/code_editor.cpp#L835-L837

Hope it is okay that I comment this here, because it seems similar to the issues listed.

**Comment by HolonProduction** [comment]
Just tested in v4.1.stable.official [970459615].
- Problem 1 is fixed (no builtin types in type name (including "Variant") completion)

Problems 2 and 4 still apply.

**Comment by HolonProduction** [comment]
Can't reproduce the 4th problem on v4.2.dev.custom_build [ef155c1ae]
