### ISSUE TITLE
CSG Editor perfomance

### ISSUE THREAD

**Issue by SuperDIMMaX** [godotengine/godot#40934]
**Godot version:**
Any?

**OS/device including version:**
Any?

**Issue description:**
Example if exist 500 CSG nodes and if i start move 100 CSG of this, then editor recalc every frame and this impact of perfomance,(Very impact), but if i unparent CSG nodes and move 100 CSG(not parented of CSG_Combiner) - not affected perfomance.
Can you change code - if transform(move,rotate, ...) - then not recalc, if only stop transform - recalc. ?

**Comment by madmiraal** [comment]
This is by design. The `CSGShape` needs to be reconstructed if one of its children or peers changes.

If you are interested in proposing an improvement, please open a new proposal in [Godot Improvement Proposals (GIP)](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already).

**Comment by SuperDIMMaX** [comment]
@madmiraal i mean - min changes - recalc only stop move, rot, etc.. just on mouse button released. i not see any break cap and limitations. 
i open https://github.com/godotengine/godot-proposals/issues/1289 - this is realy necessary?
