### ISSUE TITLE
get_node() with typed variables give Parse Error in neo-GDScript

### ISSUE THREAD

**Issue by Anutrix** [godotengine/godot#40985]
**Godot version:**

Godot 4.0 master https://github.com/godotengine/godot/commit/ec9302ceccb75f44038db3695d2f9e7c82cfe951

**OS/device including version:**

Windows 10 1809

**Issue description:**

When using `get_node()` or its `$` syntax with typed variables we get ` Parse Error: Value of type "Node" cannot be assigned to variable of type "<any-type-name>"`.

**Steps to reproduce:**
1. Under a root node, add an `ItemList` node.
2. Then use this line in the script for the root node:
```
var item_list : ItemList = $ItemList
```
3. Observe:
```
res://Node2D.gd:90 - Parse Error: Value of type "Node" cannot be assigned to variable of type "ItemList".
modules\gdscript\gdscript.cpp:620 - Method/function failed. Returning: ERR_PARSE_ERROR
```

**Comment by dsnopek** [comment]
I went and checked out this code in godot_analyzer.cpp because I was in there earlier today, and I suspect that this is the expected new behavior of GDScript.

The `get_node()` function returns a Node but the variable is typed as an ItemList, and I think now you're expect to explicitly cast from a child class to a parent class:

```
var item_list : ItemList = $ItemList as ItemList
```

In fact, this aligns with the behavior of most programming languages, where you can automatically assign an child class to a variable typed as a parent class (ie. `var node : Node = item_list`), but to do the reverse, an explicit cast is required.

@vnen would have to say for sure if that's true, though.

**Comment by vnen** [comment]
It should work but mark the line as unsafe, I might have forgotten to add it on this particular case and just used the more eager check.
