### ISSUE TITLE
GDScript 2.0: @export_range doesn't allow negative values for the start of a range.

### ISSUE THREAD

**Issue by DarkKilauea** [godotengine/godot#41183]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
Godot Engine v4.0.dev.custom_build.a32b427f9

**OS/device including version:**
Windows 10 (64-bit)

**Issue description:**
@export_range does not allow the starting value to be negative.

``` gdscript
extends Node

# Does not allow negative values for start of range.
@export_range(-1, 1, 0.05) var exported_variable: float;

# Zero is allowed.
@export_range(0, 1, 0.05) var working_exported_variable: float;

# Positive is allowed.
@export_range(1, 50, 0.05) var another_working_exported_variable: float;

func _ready():
	pass 
```

Error encountered:
`error(4,28): Expected float as argument 1 of annotation "@export_range").`

**Steps to reproduce:**
Add example script in the issue description to project.

**Minimal reproduction project:**
[TestGDScript2_export_range.zip](https://github.com/godotengine/godot/files/5054826/TestGDScript2_export_range.zip)

**Comment by neqs20** [comment]
This also applies to `@export_exp_range()`. Both annotations don't accept negetive values in their parameters.

**Comment by Blackiris** [comment]
There are 2 issues happening behind this:

**1. The validation when parsing**
In `GDScriptParser::validate_annotation_arguments`, the code is expecting @export_range arguments to be of Node::LITERAL type.
However, -1 is an UNARY_OPERATOR, with a LITERAL inside, but not a LITERAL.

A solution is then to treat UNARY_OPERATOR to check its child operand instead:
Before:
```
if (argument->type != Node::LITERAL) {
	push_error(vformat(R"(Expected %s as argument %d of annotation "%s").)", Variant::get_type_name(parameter.type), i + 1, p_annotation->name));
	return false;
}
```
After
```
ExpressionNode *argument_to_check = argument;
if (argument->type == Node::UNARY_OPERATOR) {
	argument_to_check = static_cast<UnaryOpNode *>(argument)->operand;
}

if (argument_to_check->type != Node::LITERAL) {
	push_error(vformat(R"(Expected %s as argument %d of annotation "%s").)", Variant::get_type_name(parameter.type), i + 1, p_annotation->name));
	return false;
}
```




**2. The generation of the export hint_string**
The hint_string is normally generated with the following code, in the **parser**:
```
String hint_string;
for (int i = 0; i < p_annotation->resolved_arguments.size(); i++) {
	if (i > 0) {
		hint_string += ",";
	}
	hint_string += String(p_annotation->resolved_arguments[i]);
}

variable->export_info.hint_string = hint_string;
```

But there are many issues:

- resolved_arguments is calculated by the **parser**, and not the analyzer, so it cannot treat "-1". Only gdscript_analyzer.cpp can read it using reduce_expression, and then read the variant result.
- AnnotationNode is a struct with 2 fields: `Vector<ExpressionNode *> arguments;` and `Vector<Variant> resolved_arguments;`. This is redundant info and resolved_arguments is, I think, used as a result cache, but ExpressionNode already has a cache with its `reduced_value` member.

My proposal is then to move the hint_string to gdscript_analyser.cpp instead, and completely remove all usage of `resolved_arguments`.
Not sure it will be approved but I hope my upcoming PR could help to better fix the issue.

I have complete the test project with the @icon, since my PR have certainly an impact on it.
[TestGDScript2ExportRange.zip](https://github.com/godotengine/godot/files/6290715/TestGDScript2ExportRange.zip)

**Comment by duchainer** [comment]
Quick workaround for those stumbling on this issue:
If your total range is less then the max Int range, you can have an offset-ed exported variable instead:
```
#TODO: Negative Range 
# Intended declaration:
#    @export_range(-3.1416, 3.1416) var cursor_deg := 0.4 : set = set_cursor_deg
@export_range(0, 6.2832) var cursor_offset_deg := 0.4 + 3.1416
var cursor_deg := cursor_offset_deg - 3.1416: set = set_cursor_deg
```

**Comment by bowling-allie** [comment]
I'm also wondering why I cant use simple binary operators too, or maybe even a 'const',
Because aren't `const`s known at compile-time?
Allowing annotations to accept const values sounds like a solution to me.
But maybe that's a feature request.

**Comment by MeshVoid** [comment]
Dealing with the same problem here. Hopefully will get resolved soon.

**Comment by sebastianrueckerai** [comment]
Still happening. A fix would be awesome!

**Comment by iamjoeysox** [comment]
Any updates on this yet?

**Comment by Calinou** [comment]
> Any updates on this yet?

https://github.com/godotengine/godot/pull/63929 is not ready to be merged yet, according to https://github.com/godotengine/godot/pull/63929#issuecomment-1288381206.

**Comment by Nekuromu** [comment]
![image](https://user-images.githubusercontent.com/30809120/212571110-b3f23195-e7ce-4f11-9730-c2668217494a.png)
![image](https://user-images.githubusercontent.com/30809120/212571117-78c5ebe1-5ac7-48c4-91e4-851024a7a7d3.png)

Still happens in Godot 4 Beta 11

**Comment by dalexeev** [comment]
Negative numbers are a particular case. Annotations do not support expressions (even constants), only literals. The following examples also result in the same error:

```gdscript
@export_range(+1, 10) var a := 0
@export_range(1 + 1, 10) var b := 0
```

A negative number for the parser is not a literal (it's a `UnaryOpNode`).
