### ISSUE TITLE
Unable to see certain tilemap collision shapes

### ISSUE THREAD

**Issue by Rubonnek** [godotengine/godot#41267]
**Godot version:**
3.2 branch commit f732cea0ff8311301d49fe7760f8339df6a6d4ea

**OS/device including version:**

Arch Linux

**Issue description:**

Most of the tilemap collision shapes are visible when enabling `Debug`->`Visible Collision Shapes`, but some shapes are not visible even though they have working collision shapes.

All these collision shapes are defined in a `TileSet` resource.

**Steps to reproduce:**
1. Download attached project.
2. Make sure `Debug`->`Visible Collision Shapes` is enabled.
3. Press F6
4. The following places on screen have collision shapes defined:
![NonVisibleCollisionBoxes](https://user-images.githubusercontent.com/8337880/90287750-79c12700-de46-11ea-885f-f0b6ea6de8f2.png)

5. Press WASD to move and attempt to collide with the non-visible shapes -- the collision shapes function, but are not visible on screen.

**Minimal reproduction project:**
[CollisionVisibilityBug.zip](https://github.com/godotengine/godot/files/5076906/CollisionVisibilityBug.zip)

**Comment by lawnjelly** [comment]
Just checked it out and it's a batching bug, doesn't occur with batching off. I'll look into it. :+1:

**Comment by lawnjelly** [comment]
I've tracked this down to the debug_collisions sometimes having a stream of useless extra matrix transform commands before the collision poly. This is something I should have been taking care of, but it is so rare I'd not seen it before.

I have a possible fix now, but want to double check all the concerned code rigorously because I remember this part being very error prone.

**Comment by akien-mga** [comment]
Fixed by #41346.
