### ISSUE TITLE
Overflowing MaxLength on LineEdit via Code manipulation leaves you with an empty Text variable for the rest of the code loop.

### ISSUE THREAD

**Issue by LynnCelest** [godotengine/godot#41278]
**Godot version:** 3.2.2

**OS/device including version:** Windows 10

**Issue description:** If you want to manipulate LineEdit.Text and right after count the words in Text in a given virtual func loop of your program you may have consistent results until you turn max length on. Once you turn max length on and your code makes the Line become overflown then Text will become empty for the rest of the virtual loop. So if you have following code that counts information in text and then does something like Text.Split()[WordIndex] your game will crash since Text is empty. (Or you just in general won't be able to gather information from the text from the rest of the loop)

I feel like some people would be pretty confused about this bug but I luckily figured it out after some experimenting. If this is intended behavior the user wasn't warned about it, That's why I feel it's a bug. It makes manipulating and gathering information from LineEdit.Text via in the same code loop inaccessible.

Disclaimer: I haven't checked if Text is reset in the next loop so I'm just assuming that's how it was coded. I was using _Input specifically when this happened. I replicate it in my game by pressing up on the keyboard (which makes my game go through a word selection wheel and then regathering information from Text for exact selection.)

**Minimal reproduction project:** 1. First turn Max Length on to 15 or so.
2. Write this code (possibly in _Input):
```cs
Text = Text + "L ";
occurenceOfK = 0;
for(var i = 0; i < Text.Length; i++){
    if(Text[i] == 'k') {//It should crash here since there is no Text.
        occurenceOfK = i;
        break;
    }
}
```
3. Start the game.

**Comment by Tony-Goat** [comment]
Whenever `set_max_length()` is called it also calls `set_text()` again to force a refresh. `set_text()` further called append_at_cursor() (Which is at 0 after `clear_internal()`).

`append_at_cursor()` would check the text length against the max length, and if it's too long, `would emit text_change_rejected`. So the text would get cleared out by `set_text()`, but because the text longer than max_length from `set_max_length()` was preserved in the call stack, it would never set the new text in and instead sent the signal.

Since one wouldn't expect `text_change_rejected` from `set_max_length()`, I could see why this is never caught. The behavior most people would expect would be to chop off the end of the text instead of making it empty.

**Comment by KoBeWi** [comment]
#33321 might be related.

**Comment by Tony-Goat** [comment]
It looks like these two issues most likely stem from the same bug. Would it be better to move the trimming code to set_text rather than set_max_length()?

**Comment by KoBeWi** [comment]
> Would it be better to move the trimming code to set_text rather than set_max_length()?

If it works and fixes both issues then probably yes.

**Comment by akien-mga** [comment]
Reopening as #41520 was reverted.
