### ISSUE TITLE
AnimationTreePlayer.  Unable to get the position of animation.

### ISSUE THREAD

**Issue by DimaKiva** [godotengine/godot#4131]
The AnimationTreePlayer node is missing tool receiving position animation.

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
