### ISSUE TITLE
Navigation2D on TileMap passes over non-navigation area

### ISSUE THREAD

**Issue by ElliotBak3r** [godotengine/godot#41349]
**Godot version:**
3.2.2 Stable

**OS/device including version:**
macOS

**Issue description:**
If you have a turn in the navigation area in a tile, the Navigation2D ignores it and tries to move straight through it instead of going around the turn.

**Steps to reproduce:**
Have a turn in the navigation area in a tile, run get_simple_path() on the Navigation2D and you will get a straight line instead of a turn.

**Minimal reproduction project:**
[Bug Showcase.zip](https://github.com/godotengine/godot/files/5089464/Bug.Showcase.zip)
This projects has a Line2D draw the path of Navigation2D from get_simple_path(). Notice that the navigation area in the tile has a bend.

**Comment by erictuvesson** [comment]
Issue is related to the polygon creation.

![image](https://user-images.githubusercontent.com/1263211/97416482-caed9c80-1906-11eb-8532-1548ada4ab76.png)

![image](https://user-images.githubusercontent.com/1263211/97416770-2881e900-1907-11eb-8b23-07c09cc72615.png)

**Comment by smix8** [comment]
Not very familiar with the TileSet Editor internals but the created TileData resource has the wrong polygon values / order stored for a NavigationPolygon resource.

If you create the exact same Polygon in the exact same steps with other tools that use NavigationPolygon resources it works perfectly fine but if you copy the TileSet polys to a NavigationPolygonInstance you get the same bug result.

**Comment by smix8** [comment]
Getting closer ...

TileSet creates and stores NavigationPolyons vertices in a format that looks good with CanvasItem.draw_polygon() which fools everyone that things should work correct while in the Editor.

NavigationPolygons and the NavigationServer2D require a format that you get when you set these vertices  as outline points and call NavigationPolygon.make_polygons_from_outlines().

![tilsetpolygon](https://user-images.githubusercontent.com/52464204/169658475-169c362c-0054-4608-8045-a4dc04504d88.png)


As soon as you convert the TileSet verticies to an outline and call that function you have a working NavigationPolygon again that only looks wrong in the Editor because CanvasItem.draw_polygon() can't work with it.
