### ISSUE TITLE
not support DDS

### ISSUE THREAD

**Issue by cjmxp** [godotengine/godot#4135]
not support DDS

error  ERR_FAIL_COND_V( size!=pitch, RES() );

**Comment by bojidar-bg** [comment]
@sanikoyes ~ Is this related to/fixed by your recent PRs? :smile:

**Comment by akien-mga** [comment]
@cjmxp I know English is not your native language, but you really provide too little information. We have an issue template, try to follow it. It's okay to use an automatic translator like Google Translate, just make sure that you write perfect sentences in your native language so that the translator can parse them efficiently.

**Comment by cjmxp** [comment]
You can try to add a TextureFrame in the editor and load the DDS texture to cause an exception.

**Comment by cjmxp** [comment]
@akien-mga Thank you for the next time I will try to provide details of the information

**Comment by bojidar-bg** [comment]
@cjmxp Which version of godot do you run?

**Comment by cjmxp** [comment]
@bojidar-bg v2.1 alpha

**Comment by reduz** [comment]
if you have a dds file that fails, feel free to submit it here
