### ISSUE TITLE
The android's virtual keyboard & the navigation bar height isn't calculated correctly.

### ISSUE THREAD

**Issue by capnm** [godotengine/godot#41388]
___

***Bugsquad edit:** This bug has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**

3.2 branch tip 9bf5a0b791faf8e960bdb07009b5fe8003206e4f

**Issue description:**

The height of the virtual keyboard `OS.get_virtual_keyboard_height()` 
isn't calculated correctly if it is above the Android navigation bar.

This happens in the smartphone in portrait format, on the tablet in portrait and landscape format.

Fortunately it is possible to craft some workaround for the issue. You get the negative
height of the **navigation bar** when you close the keyboard (see the first screenshot).

There have been attempts by @pouleyKetchoupp to fix this. The related PR was reverted due
to bad side effects. https://github.com/godotengine/godot/pull/40672

**Steps to reproduce:**

<details><summary>Screenshots</summary><p>

![vkb_height_test](https://user-images.githubusercontent.com/4047289/89119660-60b48f80-d4b0-11ea-9b61-517e569668c8.png)

![grafik](https://user-images.githubusercontent.com/4047289/90710538-eb620080-e29e-11ea-9e9d-6740f3c29791.png)

</p></details>

**Minimal reproduction project:**

[vkb_height_test.zip](https://github.com/godotengine/godot/files/5100303/vkb_height_test.zip)
[apk-app.zip](https://github.com/godotengine/godot/files/5100304/app.zip)

**Comment by pouleyKetchoupp** [comment]
It might be possible to re-use a part of #40944 to help with this issue.

In order to take the virtual navigation bar in portrait mode into account, using `getRealSize` instead of `getSize` in `onGlobalLayout` works:

```
// Adjust final height from real size to take other decorations into account
// like the navigation bar in portrait mode.
if (godotActivity.isImmersiveUsed()) {
	Point realScreenSize = new Point();
	godotActivity.getWindowManager().getDefaultDisplay().getRealSize(realScreenSize);
	keyboardHeight = realScreenSize.y - gameSize.bottom;
}
```

But only when immersive mode is on, otherwise the navigation bar being always on I was getting wrong results (might be different when not using a separate popup window for the text edit though).

Also, this was still not working on tablet when the virtual navigation bar shows in landscape mode for some reason.

**Comment by m4gr3d** [comment]
@capnm you seem to have good luck as the Android developer blog recently published a post about how to handle keyboard visibility and height: https://medium.com/androiddevelopers/animating-your-keyboard-fb776a8fb66d

I'll experiment with it and push a fix once I get it working.

**Comment by wilmer-daza** [comment]
Hi! @m4gr3d do you have any idea of when a fix will be provided for this issue? I'm having the same exact problem that #45768 (in portrait mode on Android)

The virtual keyboard hides all the lines edits; I was trying to get the 'height' so that at least I can manually move my controls but the "OS.get_virtual_keyboard_height()" method always return 0

Do you have any idea of at least a workaround? Thank you!

**Comment by tpaulino7** [comment]
Hi. Having this exact same problem, if anyone has a workaround or fix would be great! Thanks

**Comment by marick-py** [comment]
@capnm @tpaulino7 @wilmer-daza
ive fixed it with this code...
im doing a chat system and my goal was to move all the `self.rect_position` node (chat + input)

	#ive tryed my app in 2 differents devices and in the old one i have a -offset in the regular keyboard position 
	#(when the keboard is not selected the pos is like -86 for no reason and this will fix it)
	var error_offset = 0
	
	func _process(_delta):
		# get the virtual keyboard height
		var offset = OS.get_virtual_keyboard_height()

		# check the irregular offset and set the var 'error_offset' = -offset error
		if offset < 0: 
			error_offset = offset
			offset = 0
		elif offset > 0:
			# take the difference between the 'game' screen size and the actual 'screen size' (/2 cuz half is in the top and half in the bottom) + the error_offset value (in my case -86)
			offset -= (OS.get_screen_size().y - ProjectSettings.get_setting("display/window/size/height"))/2 + error_offset

		#set the offset position for the self.rect_position (chat + input)
		rect_position.y = -offset

I hope this may be useful to you and sorry for my English   T___T
