### ISSUE TITLE
Support localization of scancode strings

### ISSUE THREAD

**Issue by EIREXE** [godotengine/godot#4140]
Currently there's no way to get a localized version of OS.get_scancode_string, it would be great if this was possible.

**Comment by Calinou** [comment]
I wonder how this could be handled. We could pass the scancode string directly to `tr()`, which means the user would have to translate it themselves. We could run into issues due to varying contexts though (e.g. "Shift" may be used both as a key name and as an in-game action).

**Comment by EIREXE** [comment]
I have realised, do we even need this? Because Escape is a pretty universal term for the ESC key, and I'm pretty sure it's used this way even in languages other than english/spanish.

**Comment by akien-mga** [comment]
> I have realised, do we even need this? Because Escape is a pretty universal term for the ESC key, and I'm pretty sure it's used this way even in languages other than english/spanish.

In French the key is labelled "Échap" (can also be "Esc" on some devices though). Return/Enter are "Entrée", Backspace is "Retour Arr." IIRC, "Delete" is "Suppr", etc. So yes, for many keys localization could be useful.

**Comment by Dragoncraft89** [comment]
I think this is very much needed for games that do localization and feature remappable controls.

So let me comment on @Calinou's ideas:
1. Passing the string to `tr()`: This is not useful. The game's developers still need to create the translations. This is not feasible for smaller teams. Also it doesn't improve the situation at all, because it is equivalent to `tr(OS.get_scancode_string(key))`, which doesn't cause confusion with unintended translations.
2. Builtin translations: IMO this is the better idea. As for the size I estimate it'd be about (assuming gettext format): 98 (number of KEY_* constants with SPKEY bit set + KEY_SPACE) * 64 (number of languages currently registered in Hosted Weblate) * 58 bytes (len('msgid ""\nmsgstr ""\n') == 18 + 20 chars (my estimate) for `id` and `translation` each) is about 355KiB. (Doesn't account for file headers/comments though)
    For comparison: export template for 3.2.1 linux amd64 is 38MiB. So this would probably increase it to about 39MiB.
   I see two possibilities for this:
    - Include those strings in the binary: Might need extra work to parse a gettext file from a string (I'm not sure about the engine internals here). Also this might be considered bloat when not needed.
    - Include those strings in the exported pck: Add the files in the exported pck to a path like "res://.godot_engine_translations" and load translations from that path automatically on startup. Possibility to let the users choose if they want this. Possible, but unlikely clashes with the project's file system though.

As @Calinou mentioned, these translations might clash with user defined translations. So it may be necessary to either use the name of the constant (e.g. "KEY_SHIFT"), or prepend that name to something like "__GODOT_KEY_SHIFT" to avoid name clashes.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

-----

Specific to this feature, relevant strings that should be translated are in `core/os/keyboard.cpp`, and they could be exposed using `RTR()` a priori.

Note that in the `master` branch the function was renamed to `OS.get_keycode_string()`. A boolean parameter should likely be added to define whether the English or localized string is wanted.
