### ISSUE TITLE
Resources not exported/broken on export. No error

### ISSUE THREAD

**Issue by TheDuriel** [godotengine/godot#41489]
**Godot version:**

3.2 official

**OS/device including version:**

windows 10

**Issue description:**

In my current client project, (a 3D VR game) I'm encountering a scenario in which a number of texture resources are seemingly not exported and included in the pck. (other .png files import and export correctly) The files are initially in .png imported using the 3d preset, and function correctly in the editor and when running the game from the editor.

However, once the project is exported the log is filled with generic "could not load resource" errors. These errors do _not_ name the files in question, and the project continues to run, replacing the "missing" textures with grey rectangles.

My workaround for now is to manually place the .import _directory_ next to the binary. But unless your go through it 1 by 1 that will cause massive bloat through duplicate files and is only a stopgap measure.

**Steps to reproduce:**
Dunno.

**Minimal reproduction project:**

Client project, please message me directly for a copy of the repository.

**Comment by Calinou** [comment]
> 3.2 official

Is this 3.2 or 3.2.2?

**Comment by TheDuriel** [comment]
3.2

This is what I get on 3.2.3rc3, which is quite a bit more verbose:

https://gist.github.com/TheDuriel/8d5d11bd03403cda455bd5145098df09

Ignore line 72 and onwards, thats due to my headset not being plugged in.

On 3.2official the only errors that show are line 14 through 52.

**Comment by Calinou** [comment]
@Theduriel Can you (or anyone else) still reproduce this bug in [Godot 3.5.1](https://godotengine.org/article/maintenance-release-godot-3-5-1) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by TheDuriel** [comment]
Project is under NDA, only the project specific files seem to have been affected at the time. Closing this for now.

**Comment by jammin-ben** [comment]
Just a heads up, I encountered a related problem where some sprites / objects weren't loading properly in the exported version. It turned out the cause was that the filenames had different capitalization. It seems that in-engine, loading files is not case sensitive, but exported versions _are_ case sensitive. Definitely double check those textures that aren't loading and make sure the strings match exactly.

For what it's worth, this bug came up for me after checking out my git repo to an early version, just to check things out, then checking master back out. Somewhere along the way, I (intentionally) changed my capitalization convention. When checking out the early version, the file names changed case, but for some reason they didn't change going the other way. Godot version 3.4. I don't know if this is a git bug or a Godot bug.

**Comment by TheDuriel** [comment]
Godot will inform you of case miss matches with a warning in the editor.

https://docs.godotengine.org/en/3.2/getting_started/workflow/project_setup/project_organization.html?#case-sensitivity More info here.
