### ISSUE TITLE
3D scene Import problems

### ISSUE THREAD

**Issue by karolgotowala** [godotengine/godot#4153]
Windows 8.1 Godot v2.0.1.stable.official

So this is my problem with godot importer.
It fails to:
1. Remember the last cips of animation.
2. Overwrite the scene when it's opened in editor.
3. When reimporting it shows some other clips from past.

[The video tells more than any words](https://www.youtube.com/watch?v=sLgN5FRVjpM&feature=youtu.be)

**Comment by bojidar-bg** [comment]
I think this was fixed by the new importer's addition on master, can someone confirm?

**Comment by KoBeWi** [comment]
Hard to tell what the issue was about, as the video is dead. Second problem was reported again in #14338. As for the other too, if someone had this issue, there's probably some less vague report out there (if not already closed). Closing this one, because it's from even before 2.1, so there's no reason to keep it in the current state :I
