### ISSUE TITLE
Add "step" button next to "play"

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#4165]
Feature proposal:
It would be nice to have a "step-by-step" button next to "play", to see the game execute frame by frame. It is useful when something happens too quickly, so we would be able to see it more precisely.

**Comment by bojidar-bg** [comment]
:+1: ~ But, wouldn't it be better if the step button is binded to an in-game key. (I bet that's doable with pause)

**Comment by Zylann** [comment]
That's the workaround I would use at the moment, but requires a bit of code on game-side.

**Comment by Ace-Dragon** [comment]
I could see this being useful for diagnosing any animation bugs that might pop up (which in turn would help determine if it would need reporting to the issue tracker as a Godot bug).

Thumbs up from me.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
