### ISSUE TITLE
An advanced profiler

### ISSUE THREAD

**Issue by alabd14313** [godotengine/godot#4167]
Do you have any idea about better profiler, like:
![profiler](https://cloud.githubusercontent.com/assets/14325605/14100141/68c25c5a-f5a0-11e5-91ba-be4107c0b13c.gif)

**Comment by Ace-Dragon** [comment]
Isn't this example a little over-engineered, some of these profiles (such as the L2 data access) sound like it would require a degree in computer science to even understand (nonetheless figuring out what in Godot would cause such to go up and down)?

By extension, the vast majority of developers would really not have a use for some of those fields since they would not understand them.

**Comment by HeartoLazor** [comment]
Hey,
This feature request is for an ADVANCED profiler, there is a basic profiler somewhere?
After looking a bit on the debugger options, I could only find 
![Image](http://i.imgur.com/9il1zb4.png)
The "basic profiler" could be the performance and videomem tab?
Also for me the info tab Clicked control/Clicked Control Type/Live Edit Root doesn't make sense, what is the purpose of those three textbox?
What I'm looking for is a way to profile methods, to find bottlenecks on code

**Comment by vinod8990** [comment]
How about adding something simple like frame debugger in Unity. It does steps through the rendering and we could know how the engine renders and identify problems like overdraw etc.
Ref(if needed): http://blogs.unity3d.com/2014/07/29/frame-debugger-in-unity-5-0/

**Comment by reduz** [comment]
this is done now :)

for frame debugger you generally need hardware support, this is quite complex as far as I understand, but you can use external tools for this, there are plenty of opengl debuggers.
