### ISSUE TITLE
Collision Polygon Delete Bug

### ISSUE THREAD

**Issue by pcvonz** [godotengine/godot#4168]
**Operating system or device:**
Linux 4.2.0-34-generic 64 bit

**Issue description** (what happened, and what was expected):
When a collision polygon was deleted, the collision still occurred in game (even when reloading). 

**Steps to reproduce:**
Create a collision polygon, delete. 

**Link to minimal example project** (optional but very welcome):

[test.zip](https://github.com/godotengine/godot/files/194079/test.zip)

**Comment by RebelliousX** [comment]
I confirm this happened to me too. It drove me nuts for awhile. Windows 10 here.

**Comment by reduz** [comment]
this is kind of a design bug that we can't fix without breaking compatibility. Next version (3.0) we'll redo how these nodes work to make sure it doesn't happen.

**Comment by gigabison** [comment]
I had this issue and I found that if I manually delete all the points in the collision polygon before I delete the node, it deletes correctly. That may seem obvious, but it saved me from smashing my computer screen because of some invisible walls.

 I don't know if it would be a good idea but instead of rewriting the nodes completely, a quick fix could just be to loop through the points in the polygon and delete them, then delete the whole node.

**Comment by Giacom** [comment]
Had this bug recently. One workaround is to manually edit the .tscn.

**Comment by reduz** [comment]
must be the 11th time now i close this bug today :D
