### ISSUE TITLE
(Mono) Editor crashes when opening project.

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#41735]
**Godot version:**

Godot_v3.2.2-stable_mono_win64

**OS/device including version:**

Windows 10

**Issue description:**

Worked on tilemap editor toolmode, when you can change tilemap texture with drag and drop texture from filesystem. I suspect that it was from code below.

```csharp
	[Export] private Texture _texture
	{
		get {return _texture;}
		set {_texture = value;
		TileSet.TileSetTexture(0, _texture);
		}
	}
```
**Steps to reproduce:**
1. Unpack the archive
2. Open the project.

**Minimal reproduction project:**
[CVania.zip](https://github.com/godotengine/godot/files/5168813/CVania.zip)

**Comment by DmitriySalnikov** [comment]
You get StackOverflowException because you are using properties incorrectly.
In your code 'set' function calling recursively.
Correct code:
```c#
private Texture _local_texture_variable;
[Export] public Texture _texture
	{
		get {return _local_texture_variable;}
		set {_local_texture_variable = value;
		TileSet.TileSetTexture(0, _local_texture_variable);
		}
	}
```
![kj9mPLDiVa](https://user-images.githubusercontent.com/7782218/92128431-1144e480-ee0b-11ea-8672-a87d936feee3.gif)

[Properties (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/properties)

**Comment by boruok** [comment]
Cleared .mono/temp folder, changed script to new, it works now! @DmitriySalnikov  Thanks!

**Comment by DmitriySalnikov** [comment]
I do not know if this is an error, but the logs do not show the place where the exception occurs
These are all logs with verbose flag
```
Unhandled Exception:
StackOverflowException
ERROR: GDMonoUtils::debug_send_unhandled_exception_error: System.StackOverflowException: The requested operation caused a stack overflow.
   At: modules\mono\mono_gd\gd_mono_utils.cpp:371
```
