### ISSUE TITLE
GLES2 batching issue

### ISSUE THREAD

**Issue by qdwang** [godotengine/godot#41757]
**Godot version:**

3.2.3 rc5 mono

**OS/device including version:**

windows 10 GLES2 
nvidia 1660super

**Issue description:**

One node with two sprites will disable the batching rendering.

The pic below is the correct situation with batching rendering, each node contains one sprite.
<img width="484" alt="gles2hasbatching" src="https://user-images.githubusercontent.com/403616/92209774-2891d980-eec0-11ea-896a-3b865d6261e7.png">
**batch working**⬆️

The pic below is the incorrect situation without batching rendering, each node contains two sprite.
<img width="455" alt="gles2nobatching" src="https://user-images.githubusercontent.com/403616/92209798-32b3d800-eec0-11ea-9b54-de7ab7de7598.png">
**batch not working**⬆️

**Minimal reproduction project:**

[GodotIssueTest.zip](https://github.com/godotengine/godot/files/5173223/GodotIssueTest.zip)

**Comment by lawnjelly** [comment]
I tried the min production project - this isn't actually a bug. There are some situations that cannot be batched, this is one of them. This is not due to a problem in the batching, it is dictated by how GPUs render the scene.

Naively, a change in texture breaks batching, so you have a sequence of blue green blue green etc textures.

However, there is an optimization whereby the batching can reorder sprites to batch more together, but it can only happen providing an overlap test passes (i.e. the rects are not overlapping). In your test project they are all overlapping so no reordering can happen.

If instead you change your `Node1` scene to have the 2 sprites not overlapping, then you should see a reduction in drawcalls.

The other alternative is to use a texture atlas (instead of separate textures) in which case they should be batched better.

This is probably better explained in the docs here:
https://docs.godotengine.org/en/stable/tutorials/optimization/batching.html
