### ISSUE TITLE
Documentation version

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#4185]
Two additional files could be useful in doc/base :  
* A file with just the documentation's version (or engine major version + minor version/build) for avoid to load and parse the entire file.
* A second file with the conventions and structure used (recently the codeblock tag has been added)

**Comment by akien-mga** [comment]
> A file with just the documentation's version (or engine major version + minor version/build) for avoid to load and parse the entire file.

For that you can use ``version.h``. The documentation version is the same as the engine version.

**Comment by BBric** [comment]
I have just found a version.py file. But the minor version isn't incremented for each small change in the file (between 2.x and 2.x + 1 classes.xml can be modified more than 1 time), that is not exactly what i search.

**Comment by akien-mga** [comment]
Well we won't start having a static versioning of the documentation for each new commit made on it, it would be unmanageable. You can parse the git commit hash or the git log to infer how many times it changed since the last time you checked, or something like that.

**Comment by BBric** [comment]
I don't know how do that, it seems complicated for so little. This version number would be just indicative, it has not need to be strictly incremented at each modification, only for the significants changes.

**Comment by akien-mga** [comment]
It's a bit unclear what you're asking for. The documentation is kept in sync with the source code. When the source code changes, we try to update the documentation accordingly. We also try to document existing features that are not documented yet. What would be the criterion to decide that the documentation version should be bumped? "Significant" is quite subjective.

You don't state it, so it's left to us to do the guesswork, but I guess you want this to decide when you should update your standalone documentation reader. Just make it check if there was a new commit since the last time and download the file if there was. There is no reason *not to* use the latest version of the documentation, for a given branch (2.0 or master).

**Comment by BBric** [comment]
Ideally it should be incremented when the API has been modified, or when a description has been improved. But for spelling mistakes or minor cosmetics changes it could be forgotten.
I don't know how to communicate with GitHub without git. I have tried another method with the last modification date of the file but it doesn't work.

**Comment by akien-mga** [comment]
Well that won't happen, it would be unmaintainable to have to force documenters to bump an arbitrary version number in a file each time they touch the class reference.

You can get e.g. the last modification date with:
```
git log -1 --format="%ad" -- doc/base/classes.xml
```
And infer a version number from it (e.g. master_20160411).

**Comment by akien-mga** [comment]
> A second file with the conventions and structure used (recently the codeblock tag has been added)

I moved this part to https://github.com/godotengine/godot-docs/issues/122

For the first part, closing as wontfix as per the above discussion.
