### ISSUE TITLE
Yield is still recognized by the editor

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#41865]
**Godot version:**

5c879e6

**Issue description:**

The `yield` keyword was removed, but is still recognized by the editor. The keyword is highlighted and using `yield`, instead of typical "identifier not declared" error, gives "expected statement found yield" error. Either this should be not recognized at all or properly deprecated and point to `await` in the error message.

**Comment by dalexeev** [comment]
As I understand it, this is a reserved keyword for iterators/generators. In `modules/gdscript/gdscript_tokenizer.cpp`, in addition to `yield`, other tokens are defined that are also not yet implemented (`namespace`,` trait`).

**Comment by vnen** [comment]
I did reserve a few keywords that we might use in the future to make sure we can add features without breaking compatibility. In case we decide not to use those we can remove them later.

`yield` is still a keyword both because we can add an special error message if someone tries to use (like when migrating code) and also in the case that we add generators later on (which while unlikely for now it's interesting to consider).

So this isn't really a "bug".

**Comment by dalexeev** [comment]
@vnen Did we forget that `yield` is used for generators/iterators besides waiting for signals? `await` is a replacement for only the second function, and the first one is removed in 4.0. Very sad. Although this is rarely used, it is sometimes very useful.

**Comment by vnen** [comment]
@dalexeev `yield` doesn't work like that in GDScript, it is kind of backwards of what you expect from other languages. It works more like a first-class continuation which is something not common in modern programming languages.

If you think something is missing feel free to open a proposal for this. As I said, generators is still under consideration (but no proposal for that yet AFAIK).
