### ISSUE TITLE
Twitch API integration?

### ISSUE THREAD

**Issue by tanjunior** [godotengine/godot#41915]
**Godot version:** 3.2.2

**Issue description:** twitch integration. Specifically getting Auth code [https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-authorization-code-flow](url) using HTTPRequest as the code will be contained in the URI after a redirect
![redirect](https://user-images.githubusercontent.com/11617693/92612168-31cddc80-f2ec-11ea-9ea1-1d9c0167411f.jpg)

The only way I could think of to make this work is using `OS.shell_open` to bring up the redirect page, copy the code to a LineEdit node for input

**Minimal reproduction project:**

[twitch.zip](https://github.com/godotengine/godot/files/5195985/twitch.zip)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by tanjunior** [comment]
noted @Calinou  thanks for the info
