### ISSUE TITLE
Collision RectangularShape and RayShape don't work as expected

### ISSUE THREAD

**Issue by Dr4kzor** [godotengine/godot#42021]
**Godot version:**
3.2

**OS/device including version:**
Windows 10, GLES3 

**Issue description:**
If a Rayshape inside a KinematicBody is rotated even if by 1 degree it speeds up the KinematicBody for no reason
A Rectangular Collision Shape inside KinematicBody will not work properly with slide on slope, in this case this was tested colliding with a treadmill (staticbody with constant_linear_velocity set)
A Rectangular Collision Shape inside KinematicBody will not move with constant_linear_velocity set if we set stop on slope to true...

I have supplied a sample project with some combinations of raycast and rectangular shape interacting with a treadmill, both at 0 degree and at an angle, note that what I was hopping to achieve was a working collision using a rectangular shape

Any insight on how to workaround this issue?

**Minimal reproduction project:**
[TestProject.zip](https://github.com/godotengine/godot/files/5213567/TestProject.zip)

**Comment by madmiraal** [comment]
@Dr4kzor Please report one problem per issue. That been said, as far as I can see, everything is working as designed.

> If a Rayshape inside a KinematicBody is rotated even if by 1 degree it speeds up the KinematicBody for no reason

`RayShapes` are designed to provide a collision normal in the opposite direction to the `RayShape`; instead of the normal of the surface it's colliding with. When you tilt the `RayShape` you create the same effect as a slope. You're `KinematicBody` is accelerating down this "slope".

> A Rectangular Collision Shape inside KinematicBody will not work properly with slide on slope, in this case this was tested colliding with a treadmill (staticbody with constant_linear_velocity set)

When the `KinematicBody` collides with the tilted "Treadmill" it slides up. However, you're adding a large downward velocity on each step; so on the next iteration it will slide down, collide with the horizontal "Treadmill" and then slide along it. Note: The velocity of the "Treadmill" is subtracted from the velocity of the `KinematicBody`, but since it is less than the velocity of the "KinematicBody" it continues to move along it in the opposite direction, just slower.

> A Rectangular Collision Shape inside KinematicBody will not move with constant_linear_velocity set if we set stop on slope to true...

You're specifically telling it not to slide on the "Treadmill"; so it doesn't. Note: `stop_on_slope` has no effect on `RayShapes`.

The only real issue is that `stop_on_slope` is not intuitive, but that is not a new issue.

> Any insight on how to workaround this issue?

Please ask this question on one of the [community channels](https://godotengine.org/community).
