### ISSUE TITLE
Crash in AudioStreamPlayer3D::_notification with PhysicsDirectSpaceState NULL (Godot Physics)

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#42108]
**Godot version:**

3.2.3 RC (somewhere around Sept 10th 2020, I'll try and pin this down)

**OS/device including version:**

Linux Mint 18.3

**Issue description:**

While pausing my test game, I got a (somewhat random) crash in the sound, it seems to occur more in release build than debug.

I caught it in the debugger and it goes down here (audio_stream_player_3d.cpp, line 394):
```
	if (p_what == NOTIFICATION_INTERNAL_PHYSICS_PROCESS) {

		//update anything related to position first, if possible of course

		if (!output_ready) {

			Vector3 linear_velocity;

			//compute linear velocity for doppler
			if (doppler_tracking != DOPPLER_TRACKING_DISABLED) {
				linear_velocity = velocity_tracker->get_tracked_linear_velocity();
			}

			Ref<World> world = get_world();
			ERR_FAIL_COND(world.is_null());

			int new_output_count = 0;

			Vector3 global_pos = get_global_transform().origin;

			int bus_index = AudioServer::get_singleton()->thread_find_bus_index(bus);

			//check if any area is diverting sound into a bus

			PhysicsDirectSpaceState *space_state = PhysicsServer::get_singleton()->space_get_direct_state(world->get_space());

			PhysicsDirectSpaceState::ShapeResult sr[MAX_INTERSECT_AREAS];

// CRASHES ON THIS LINE
			int areas = space_state->intersect_point(global_pos, sr, MAX_INTERSECT_AREAS, Set<RID>(), area_mask, false, true);
```
It looks like we are assuming that space_state will be valid but it is NULL in this case causing the crash. Should we be checking for NULL here or is this something that should never happen?

**Steps to reproduce:**
Not sure yet, will try and make a min reproduction project and fill in more info here as I get it. It seems to be repeatably when I'm playing a sound effect then hit pause (which is pausing the scene tree).

I am creating a lot of self destructing AudioPlayer3Ds if I remember correctly using a script I got from Calinou. So maybe that could be causing a dangling reference or something.

They are being played with this snippet, attached to a node (e.g. a player). Note the PAUSE_MODE_PROCESS, maybe this has something to do with it, not expecting the AudioPlayer to be processed while paused?
```
	var player : AudioStreamPlayer3D = m_Node_Sound.instance()

	node.add_child(player)
		
	player.bus = info.m_Bus
	player.stream = info.m_Stream
	player.pitch_scale = 1.0 - info.m_PitchVariation + (randf() * info.m_PitchVariation * 2)
	player.set_max_db(_DBFromVolume(volume))
	player.connect("finished", player, "queue_free")
	player.play()
	
	player.pause_mode = PAUSE_MODE_PROCESS
```

**Minimal reproduction project:**

**Comment by lawnjelly** [comment]
Well it appears to be fixed simply by wrapping the call to space_state with a check for NULL:

```
int areas = 0;
if (space_state) {
    areas = space_state->intersect_point(global_pos, sr, MAX_INTERSECT_AREAS, Set<RID>(), area_mask, false, true);
}
```

I'll wait and see if there is any input for any audio / physics guys, but could make a PR with that if it is all that is needed. It could be that it is just an oversight and the space_state should be NULL when paused. But it might be a symptom of something else that shouldn't be happening.

**Comment by madmiraal** [comment]
Unless you're using Godot physics, in which case it's related to #38909, within `INTERNAL_PHYSICS_PROCESS`, `space_get_direct_state(RID p_space)` should only return `null` if the `p_space` doesn't exist. However, in this case it's the default world `space` so it should always exist; so something else is going wrong.

Regarding the proposed solution, the obvious problem with simply not checking for the `Area`s that a `AudioStreamPlayer3D` is in, is the `Audio Bus` and `Reverb Bus` overrides of the `Area`s its in will be ignored. Still, having a `AudioStreamPlayer3D` ignore the `Area` audio overrides when the `tree` is paused is better than it crashing; so probably a good short-term solution while a proper fix is found.

Also, when not crashing, `space_get_direct_state()` should spam the console with error messages before returning `null`.

Assuming the problem is that the project is running Godot physics, I've created an MRP. Click the "Pause" button, to trigger the crash. I've included an `Area` that muffles the alarm, to show the undesired effect the above proposed solution will have i.e. unmuffle the alarm. :-)
[AudioStreamPlayer3DCrash.zip](https://github.com/godotengine/godot/files/5233985/AudioStreamPlayer3DCrash.zip)

**Comment by lawnjelly** [comment]
Just trying it now.

My project was actually using bullet, and testing your min reproduction project it seems to crash when I change the physics engine to bullet (as well as with godot physics) on mine.

**Comment by madmiraal** [comment]
Odd. For me, it works fine with Bullet on 3.2.2-stable and 3.2.3-rc6. Can you provide a stack trace when it crashes using Bullet?

**Comment by lawnjelly** [comment]
Ah my mistake, I had set it to DEFAULT (assuming that would be bullet), however in my custom.py I have module_bullet_enabled set to "no" so bullet is compiled out, and so in both cases this could be caused by Godot physics, which you correctly identified as being related to #38909.

I'll try compiling in bullet just to confirm it is Godot physics only.
