### ISSUE TITLE
Shader only works in editor, not in build or play mode

### ISSUE THREAD

**Issue by cenullum** [godotengine/godot#42140]
**Godot version:** 3.2.2 stable

**OS/device including version:** windows 10

**Issue description:**  I  have written a shader for changing colors of texture but it doesn't work on colors which have decimal numbers only works on pure colors that have 1 or 0 such as vec4(1,1,0,1), vec4(0,0,1,1).  It seems the shader works on editor but in playmode or build it doesn't work.

```
shader_type canvas_item;

uniform vec4 color1 : hint_color;
uniform vec4 changed_color1 : hint_color;

uniform vec4 color2 : hint_color;
uniform vec4 changed_color2 : hint_color;

uniform vec4 color3 : hint_color;
uniform vec4 changed_color3 : hint_color;

void fragment() {
    vec4 curr_color = texture(TEXTURE,UV); 
	
	if (curr_color ==color1){
		COLOR = changed_color1;
	}else{
		if (curr_color ==color2){
			COLOR = changed_color2;
			}
		else{
			if (curr_color ==color3){
				COLOR = changed_color3;
			}
			else{
				COLOR = curr_color;
			}
		}
	}
}
```

**Steps to reproduce:**  
[paints.zip](https://github.com/godotengine/godot/files/5241004/paints.zip)

1- attach the shader to paints that one of them is pure other isn't.
2- choose colors as shader parametre to decide which color is going to be changed
3- choose colors as shader parametre to decide what color you want to convert.

shader will work perfect in editor but not in playmode

**Minimal reproduction project:** 
[Shader Bug Godot.zip](https://github.com/godotengine/godot/files/5240973/Shader.Bug.Godot.zip)

**playmode**
![in playmode](https://user-images.githubusercontent.com/57962685/93508935-b55c7e80-f927-11ea-9661-0bb034982ac3.png)
**editor**
![in editor](https://user-images.githubusercontent.com/57962685/93508940-b68dab80-f927-11ea-99ab-f6ce1838eb41.png)

**Comment by lawnjelly** [comment]
_For future reference for graphics issues issues it is best to include information such as the backend (GLES2, GLES2 batching, GLES3, vulkan etc) and your GPU model (and possibly drivers). I got the backend from the example project but it is nice to see at a glance without downloading. :+1:_

When I try it both the editor and playmode look the same as your playmode, in 3.2.2 and 3.2.3.

However in this case I suspect the problem is that you are trying to use an equals operator in the shader with floating point data. Equals usually won't work with float data, because of precision issues, and especially so in shaders because precision may vary on different hardware. Instead if you want to match a color you usually have to use an epsilon.

see e.g.
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
https://floating-point-gui.de/errors/comparison/

I suspect there may also be a better way of doing palette swaps than this (I've not really done it myself perhaps one of the 2d guys will have ideas).

**Comment by clayjohn** [comment]
As lawnjelly pointed out above, this is a result of trying to compare floating point numbers with ``==``. 

Instead of:
```
curr_color ==color
```
Use:
```
!(abs(curr_color - color) > 0)
```

**Comment by cenullum** [comment]
I had to use this if (lessThan(vec4(0.001),abs(curr_color - color1))==bvec4(false))
0.001 is similarity factor , it can't be 0
I can't compare two vec4 so I had to use lessthan func and this return bvec so that why I check bvec4(false) at the end
