### ISSUE TITLE
feature TabContainer option: tab position top/bottom

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#4214]
**Issue description** (what happened, and what was expected):
I cont create a tab container where the tabs are listed at the bottom so I have to programm one by myself. (HBottonarray and a script...)

**missing feature**
there should be an option in the tabContainer Node that lets me choose if I want to have the tab at the bottom or at the top. (Like the option tab align: left/right/center or: tab visible true/false)

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
