### ISSUE TITLE
export var can have different name instead of variable name

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4222]
when we use `export var var_name`, editor shows it's variable name `Var Name` at `Script Variables` section.
but it would be better if we can have alternative name for variable name.

if so, without changing all variable names,
script variables can show more detail message for it,
or can show non-Latin character also.

usually, developer uses Latin character for developing games.
but level designer feels more comfortable if `script variables` can show alternative string for export variables.

**Comment by neikeq** [comment]
I think it's just how inspector works. It converts underscores to spaces and capitalizes each word. Same goes for the other properties, `one_way_collision/max_depth` passes to be _One Way Collision -> Max Depth_.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
