### ISSUE TITLE
VehicleBody not react to collision layers

### ISSUE THREAD

**Issue by SinaZK** [godotengine/godot#42253]
**Godot version:**
3.2.3.stable

**OS/device including version:**
MacOS GLES2

**Issue description:**
I create 2 collision layers one for ground (bit 1) and one for car (bit 2) and set ground mask to collide with car and car collide with ground and everything is working fine. But when i want to car not colliding with ground and set the both bodies (ground and car) collision mask to 0 (both in editor and script via set_collision_mask) but car collide with ground! no matter which collision layer  set for ground, car always collide with it. But when i set the ground collision layer to zero they don't collide anymore! I tested with a RigidBody box and it works fine. I think maybe There is an issue for VehicleBody Wheel raycasts?

**Comment by pouleyKetchoupp** [comment]
Please provide a minimal project to help with investigating.

**Comment by Zoomulator** [comment]
I've encountered the same problem.
Here's a reproduction:
[GodotWheelCollisionMask.zip](https://github.com/godotengine/godot/files/5987817/GodotWheelCollisionMask.zip)

It seems the wheel ray cast doesn't pass the collision mask at all:
https://github.com/godotengine/godot/blob/cea42faa77d72cdbea8ab7c38936e7c8722900d0/scene/3d/vehicle_body_3d.cpp#L410

I assume it defaults the mask to `0xFFFFFFFF`, which would make it check against all the layers.

I'd guess the ray should have the same mask as the vehicle, or even have its own defined per VehicleWheel.

**Comment by angad-k** [comment]
Sending a PR for this

**Comment by mojoyup** [comment]
Would this be the same as what I mention here? I want to make sure I dont create a new issue if not needed. [https://github.com/godotengine/godot-proposals/issues/3341](url)

**Comment by mojoyup** [comment]
This is my zip project I made to replicate my collision issues with it. Hope this is helpful! My apologies if I do anything wrong or post wrong at all. [ZIP FILE](https://www.dropbox.com/s/0ajolqbhyn22cex/collision_issue_godot_project.zip?dl=0)

**Comment by pouleyKetchoupp** [comment]
@mojoyup Yes, it is the same issue. What version are you using? It should be fixed starting on Godot 3.3 (current stable is 3.3.3).

**Comment by mojoyup** [comment]
@pouleyKetchoupp Oh thats good to hear that its the same. Thank you. I am using this: Godot Engine v3.2.3.stable.custom_build - https://godotengine.org
So, that would make sense then :) I build Godot from code, but I can always grab the latest version. Updates quick :P Would you like me to verify it is fixed in the newest version? Hope all is well!

**Comment by pouleyKetchoupp** [comment]
@mojoyup That makes sense! I've tested your project with the offical 3.3.3 build so I can already confirm it's fixed, but let me know if you have any problem.
And just make sure to update you custom version from the `3.x` branch and not `master`, otherwise you'll have compatibility issues with your existing projects.

**Comment by mojoyup** [comment]
@pouleyKetchoupp Thank you very much :) I just became a patreon also :) Worth it!
