### ISSUE TITLE
Support editor theming

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#4228]
This is a follow-up on #2207.

Over the last few years, we had various interesting contributions to make the editor interface cooler looking, and every Godot release incorporated such contributions little by little. We now have two contributors (@toger5 and @UgisBrekis) working on two new themes for the editor. Hopefully we can integrate one of their themes or a merge of the two in the main branch for Godot 2.1, but more important, we need to think about supporting user-made themes for the editor without having to change the whole source code.

Ideally they could be defined with a similar API as the Theme class, maybe with extended capabilities in an EditorTheme class. Being able to download themes on the addon sharing platform and switch to them in one click would be awesome.

**Comment by toger5** [comment]
This would be a great feature. 
the API could support acces to some functions of the editor_node.cpp file too. That would be handy.
But i think for basic themes it is almost enough if the editor would read .thm files on the fly. thy can be created inside Godot relatively easy so that would be a good approach i think.
The editor is based on the engine itself. why is it not possible already to use a .thm file for the editor (when you can use .thm files for games created with the editor.)
I would be interested looking into that (if its not to advanced for me.)

**Comment by djrm** [comment]
How much flexibility do the themeing should have, i am thinking in something like, two types of theming, colors themes and layout themes. The editor could have a base theme, and override its values with the user specified ones, when the custom themes does not have certain element specified the editor could fallback to defaults.

**Comment by MarianoGnu** [comment]
I'll try to make a mockup of how this might work...

**Comment by reduz** [comment]
this is done, editor supports themeing so closing
