### ISSUE TITLE
No method for clearing an area of a canvas made with VisualServer (only one for clearing the whole canvas)

### ISSUE THREAD

**Issue by RichardEllicott** [godotengine/godot#42316]
when creating a canvas using the visual server, it starts off transparent with nothing drawn on it.

when you run the function vs_clear_canvas on it, this clears it back to a transparent state.

If you draw something on it, for example a rectangle or texture, it uses transparency but it overdraws... so the only way to clear one part of the canvas is to draw an opaque rectangle over the top of it

surely there must be a way of setting one rectangle on the canvas to transparent? (this is important to be able to draw a UI without having to redraw the entire canvas, you can normally do this in low level frameworks)

I've tried asking my question in multiple places, no-one seems to have any idea about how to use the VisualServer so I'm posting here. Has something been overlooked in the design of the VisualServer?

Maybe I'm doing something wrong?

**Godot version:**
3.2.3

**OS/device including version:**
Mac, seems unrelated to version

**Comment by RichardEllicott** [comment]
okay i done an extra test, i exported from blender, and then back into blender, and the lights where lost... i can see even if Godot supports these lights Blender won't export them.

any support advice/comments would still be appreciate though, what should i do? I have a lot of lights in my scenes, it seems very important for a reasonable workflow building 3D games

**Comment by clayjohn** [comment]
Your comment seems unrelated to your issue. Did you mean to post that to another issue?

Regarding your original post, have you tried using a white opaque rectangle with a blend mode set to subtract?

**Comment by RichardEllicott** [comment]
> Your comment seems unrelated to your issue. Did you mean to post that to another issue?

sorry i deleted that it was from the wrong thread, creating confusion


> Regarding your original post, have you tried using a white opaque rectangle with a blend mode set to subtract?

i can't find where you se the "blend mode" for the visual server, there's no mention of it except with the lights

https://docs.godotengine.org/en/stable/classes/class_canvasitem.html#class-canvasitem

so the issue still seems to be here :( this is a shame as i'm trying to do a custom UI again, i wanted to make this vector drawing tool, it's very expensive trying to use Line2D's everywhere

**Comment by Zamir7** [comment]
I fully support the author, and I insist on the expediency of the proposed feature, drawing in VisualServer itself gives an incredible performance advantage due to batching and semi-manual control of the process, but the whole impression is spoiled by the absence of a zone cleaning mode, since the layer has an alpha channel, and so many advantages in optimization, it gives an endless flight of imagination, which unfortunately gets smashed to smithereens by the lack of elementary cleaning. Thank you for your attention, I hope for your help on this topic.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
