### ISSUE TITLE
TabContainers foreground tabs are not drawn in front of background tabs

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#42345]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 ltsc 64 bit

**Issue description:**
On styling the tab container to match win95 theme I realized foreground tabs are not drawn in front of background tabs on tab container.
![image](https://user-images.githubusercontent.com/2453707/94310155-08d55a80-ff2e-11ea-9c4b-83ea91ee08a2.png)

**Steps to reproduce:**
- Download and Open project in godot
- Run Debug.tscn
- Click on the tabs and see they are only drawn left to right.

**Minimal reproduction project:**
[FocusBug.zip](https://github.com/godotengine/godot/files/5285041/FocusBug.zip)

**Comment by lmsonic** [comment]
Wasn't able to replicate this after porting the MRP to Godot 4.1.1. I messed a lil bit with the theme because it wasn't ported correctly automatically, and I expanded the tab theme margins to show more clearly if the drawing occurred in tree order or not.
![image](https://github.com/godotengine/godot/assets/25965198/0837795e-90da-4967-9a2b-4c1331099259)
![image](https://github.com/godotengine/godot/assets/25965198/1ea12abd-dabc-4da9-88e9-1be76633516d)

[42345.zip](https://github.com/godotengine/godot/files/12124853/42345.zip)

**Comment by lawnjelly** [comment]
If the OP meant the 2 pixels to the right of "TabA", this seems to have been fixed since 3.2.4.

Otherwise I'm unsure of the bug that is referred to, can reopen if OP can clarify that there is another bug.
