### ISSUE TITLE
Mono: Error message about getter/setter flipped

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#42355]
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Windows 10 x64

**Issue description:**

When exporting a get-only property, the error message that gets printed mentions this wrongly:
"modules/mono/csharp_script.cpp:2618 - Write-only property (without getter) cannot be exported[..]"

**Comment by theoway** [comment]
On it.

**Comment by eduardohmrodrigues** [comment]
With get-only did you mean "Read-only"?

**Comment by Flavelius** [comment]
yes, meaning a property with only a getter.

**Comment by eduardohmrodrigues** [comment]
I was looking through the code and noticed the following:

```cpp
if (!property->has_getter()) {
    #ifdef TOOLS_ENABLED
    if (exported) {
        ERR_PRINT("Read-only property cannot be exported: '" + MEMBER_FULL_QUALIFIED_NAME(p_member) + "'.");
    }
    #endif
    return false;
}
if (!property->has_setter()) {
    #ifdef TOOLS_ENABLED
    if (exported) {
        ERR_PRINT("Write-only property (without getter) cannot be exported: '" + MEMBER_FULL_QUALIFIED_NAME(p_member) + "'.");
    }
    #endif
    return false;
}
```

So, apparently the code logic says you can't export a variable that do not have a setter (a get-only property), probably because you wouldn't be able to import it back.

The only thing that caught my attention in the code snippet was that the text `without a getter` probably should be a `without a setter`, right?

**Comment by eduardohmrodrigues** [comment]
I'd opened a PR with the respective fix: https://github.com/godotengine/godot/pull/42414
