### ISSUE TITLE
Godot crashes when importing 1x1 pixel JPEG image using YCbCr and 2x2 sampling factor

### ISSUE THREAD

**Issue by Edwin-Pratt** [godotengine/godot#42363]
**Godot version:**
Godot 3.2.3

**OS/device including version:**
- Device: *Acer Aspire A315-33*
- OS: *Windows 10 64-bit*
- CPU: *Intel(R) Celeron(R) N3060 @ 1.60 GHz*
- GPU: *Intel HD Graphics 400*
- RAM: *4GB*

**Issue description:**
I was following an answer on the [Godot forum about making a coloured rectangle](https://godotengine.org/qa/59423/best-way-to-make-a-colored-squares-for-in-game-use), and using Microsoft Paint, I made a white 1x1 pixel JPEG image and placed it in my project's `.\Images\` directory. When I opened Godot to rescan for assets, Godot crashed as it was importing `.\Images\Background.jpg`.

**Steps to reproduce:**
1. Create an empty Godot project.
2. In the small File Explorer view on the bottom left, right-click on `res://` and create a folder called `Scenes`.
3. Open MS Paint.
4. Go to `File -> Preferences` .
5. Change both width and height to 1 pixel.
6. Tap on the white colour in the colour palette.
7. Tap on the single pixel (may need to zoom in).
8. Go to `File -> Save As... -> JPEG image`.
9. Go to the project's directory and make a new folder called `Images`.
10. Save the JPEG image as `Background.jpeg` or `Background.jpg`.
11. Open Godot and let Godot scan the project's assets.
12. The crash occurs when scanning `Background.jpeg`.

**Minimal reproduction project:**
I've added the original project.

[ForEx Simulator.zip](https://github.com/godotengine/godot/files/5288023/ForEx.Simulator.zip)

**Comment by Calinou** [comment]
I can't reproduce this on Godot 3.2.3 with JPEGs generated by ImageMagick (`convert -size 1x1 xc:"#fff" 1x1.jpg`).

**Comment by timothyqiu** [comment]
I can reproduce this with JPEGs generated by ImageMagick if I set the colorspace to YCbCr and use a sampling factor of 2x2:

```
convert -size 1x1 xc:"#fff" -sampling-factor 2x2 -colorspace ycbcr 1x1.jpg
```

This produces the same backtrace as the MRP.

**Comment by alketii** [comment]
This is happening to me also, while trying to import a .dae file with a 1x2 texture.

**Comment by pWNn1sher** [comment]
hello,
I want To work on this i understood the problem but i really don't known where to start . 
I imported the [MRP](https://github.com/godotengine/godot/files/5288023/ForEx.Simulator.zip) saw that it got froze at Importing assets dialog and Crashed, so I think i should start by checking code for importing project and importing assets functions but, it's hard to find. 

Any help regarding this Is Appreciated.

**Comment by akien-mga** [comment]
If you can reproduce the crash, use a debugger to get a stacktrace, which will show you which files are involved.

There's a hint in https://github.com/godotengine/godot/issues/42363#issuecomment-699630340:
```
godot.x11.tools.64.llvm: thirdparty/jpeg-compressor/jpgd.h:278: int jpgd::jpeg_decoder::check_sample_buf_ofs(int) const: Assertion `ofs >= 0' failed.
```

You can then search which files include this file:
```
$ rg "jpgd.h"
thirdparty/jpeg-compressor/jpgd.cpp
29:#include "jpgd.h"

thirdparty/jpeg-compressor/jpgd.h
1:// jpgd.h - C++ class for JPEG decompression.

modules/jpg/image_loader_jpegd.cpp
36:#include <jpgd.h>
```

(But again a stacktrace would show you that the crash in `thirdparty/jpeg-compressor/jpgd.h` originates in `modules/jpg/image_loader_jpegd.cpp`, and would additionally give you the relevant line and further call stack for what triggers that image loader call in the editor import code.)

**Comment by pWNn1sher** [comment]
So, I checked the code `int b = (c_x1 >> 3) * BLOCKS_PER_MCU * 64 + (c_x1 & 7);` which is in file [thirdparty/jpeg-compressor/jpgd.cpp on Line 2061](https://github.com/godotengine/godot/blob/dfed88b11ff1a3315f1f276ff30cbaaf05e6d7b7/thirdparty/jpeg-compressor/jpgd.cpp#L2061)

above value `b` becoming negative which eventually on the next line :
`int cb10_sample = p_C0Samples[check_sample_buf_ofs(b + y0_base)];`
is used to call `check_sample_buf_ofs()` which checks whether passed argument is positive or not 
([check `check_sample_buf_ofs()` defination ](https://github.com/godotengine/godot/blob/dfed88b11ff1a3315f1f276ff30cbaaf05e6d7b7/thirdparty/jpeg-compressor/jpgd.h#L278)) and closes the program when it's negative -> CAUSE OF ERROR

Then, I tried to read the function in which this whole thing is implemented and found out that it is [`uint32_t jpeg_decoder::H2V2ConvertFiltered()`](https://github.com/godotengine/godot/blob/dfed88b11ff1a3315f1f276ff30cbaaf05e6d7b7/thirdparty/jpeg-compressor/jpgd.cpp#L1888) Fuction.

now i am really stuck on what to do next because i don't see anything wrong in the implementation.

If i am missing something. I'm Happy to learn it.
