### ISSUE TITLE
When saving branch as a scene, data from editable children is lost

### ISSUE THREAD

**Issue by lekoder** [godotengine/godot#42611]
**Godot version:**
3.2.3-stable-official

**Issue description:**
When a node branch has children instances with editable children enabled and you save that brach as a separate scene, the changes made to children is lost.

**Steps to reproduce:**

* Create scene with instanced, editable children:
```
Scene
 `- NodeBranch
   `- Editable Child
     `- [changes]
```
* Save the NodeBranch as separate scene.
* Changes in children are silently lost.

**Expected behaviour:**
New scene saved has children with `editable children` and changes persisting.

**Use case:**
Re-factoring scenes that already have instances with changed children in their branches.

**Comment by lekoder** [comment]
MRP: https://github.com/lekoder/children-lost
Just open `Scene.tscn` and try to save `NodeBranch` as a scene, then examine the file.

Details:
- children injected directly on Editable Child will be kept, children deeper in editable tree will be lost
- `Editable Children` flag is lost
- values changed in children nodes are lost.

**Comment by KoBeWi** [comment]
Confirmed in e93af13

**Comment by pigigi** [comment]
For what it's worth it's the same in 3.2.1 stable.

**Comment by chucklepie** [comment]
I've noticed there's quite a few related bugs raised for this. I think I even raised one. I think this bug needs some kind of priority because it is corrupting games and in many cases it isn't noticed until too late.

A few weeks ago I restructured my project and moved nodes around. My game is quite large with a few hundred, many of which are editable children.

I've just spotted that every change made such as moving and sizing collision 2d shapes has been wiped too, corrupting most of my map. Because of the way scene files are saved, and the time frame, it isn't exactly simple to just go back, I have to open an old project and go back and fix every single node, one at a time.
