### ISSUE TITLE
Set TreeItem.set_icon_max_width results in render selection glitch

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#42701]
**Godot version:**
Godot Engine v3.2.3.stable.mono.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 980/PCIe/SSE2

**OS/device including version:**
Windows 10 x64

**Issue description:**
I want to use svg icons on a TreeItem where has a bigger size (e.g. 32x32px).
The TreeItem provides a func 'set_icon_max_width' to align the icon size.
When use 'set_icon_max_width' to smaller size e.g. 16px the selected item is not correct rendered.
![image](https://user-images.githubusercontent.com/347037/95663595-d1c39380-0b40-11eb-9cd1-4f54635488c4.png)

**Steps to reproduce:**
* create a tree 
* add an TreeItem with an icon (32x32)
* set 'set_icon_max_width(0, 16)' 
* select the item

**Minimal reproduction project:**
[TreItemIconScaleIssue.zip](https://github.com/godotengine/godot/files/5359850/TreItemIconScaleIssue.zip)

**Comment by Fran6nd** [comment]
Hello everyone,
For me the issue is still open when I edit a TreeItem with an icon and used `set_icon_max_width` and then `set_editable`.
I am using the latest godot4.

Here is a picture as a proof:
<img width="474" alt="Screenshot 2022-09-16 at 15 51 03" src="https://user-images.githubusercontent.com/14808487/190654891-2c79e52f-79c4-403f-a273-f48f1632e430.png">

So I believe there is still something unfixed.
