### ISSUE TITLE
Vector3 FORWARD and basis.z , both point in opposite directions to each other?

### ISSUE THREAD

**Issue by Skyvastern** [godotengine/godot#42739]
**Godot version:**
3.2.2 - 3.2.3

**OS/device including version:**
Windows 10 Professional 64-bit

**Issue description:**
The Vector3 class constant FORWARD, is assigned to Vector3(0, 0, -1). Which I guess is due to the way OpenGL conventions work. But on the other hand, if we look at the transform matrix of a node, then it's basis.z is by default equal to Vector3(0, 0, 1).

**Steps to reproduce:**
Create a new scene with spatial as the root
Add a script
Add the following lines in the _ready() function
```
print("Vector3.FORWARD = " + str(Vector3.FORWARD))
print("basis.z = " + str(global_transform.basis.z)) # Considering the node's transform is not changed
```

Also looking in the editor, the blue z-axis arrow, when moved in the direction it is pointing, always increases the z-value. So I guess wouldn't it be a little bit more consistent to change the value of Vector3.FORWARD constant -

_**from Vector3(0, 0, -1) to Vector3(0, 0, 1) ?**_

**Comment by Calinou** [comment]
The value of `Vector3.FORWARD` was set for gameplay purposes, and seems to be doing its job fine for that. Also, changing its value would break backwards compatibility, so I'd be careful about it.

**Comment by Skyvastern** [comment]
> The value of `Vector3.FORWARD` was set for gameplay purposes, and seems to be doing its job fine for that. Also, changing its value would break backwards compatibility, so I'd be careful about it.

Ahh I guess you mean when working with camera, as they point in opposite z direction. I guess that kinda makes sense, but then there are times when we have to use forward for other things where camera is not the priority. So in those situations using Vector3.FORWARD kinda becomes useless. For example, doing cross product for some specific scenarios or just using it as a shorthand for (0, 0, 1).

But then at the same time, ofcourse I must be underestimating it's usage. I guess you are right. I didn't consider the backward compatibility stuff. It's just that I sometimes find it rather annoying, but then also I haven't done many tasks involving negative directions other than camera.

**Comment by aaronfranke** [comment]
The Z vector on the transform/basis points back (aka south), not forward (aka north). This is intentional and can't easily be changed, and is not something that will be changed, the behavior is already ideal. This is just something that developers have to learn about when jumping into Godot. If you have a suggestion on a documentation improvement, that would be welcome.

* If you want a shorthand for `Vector3(0, 0, 1)` you can use `Vector3.BACK`.

* The purpose of `Vector3.FORWARD` is such that moving by this vector will move a character forward. For games where the camera angle does not change you always want `Vector3(0, 0, 1)` as the forward vector. For first person games, you need this in local space, so it's better to use `-transform.basis.z`, but you can also use `basis.xform(Vector3.FORWARD)`.

* These names correspond with other values like `Vector3.RIGHT` and `Vector3.UP`. If you have a character facing forward towards `Vector3.FORWARD`, and they are upright, their right hand will be in the direction of `Vector3.RIGHT`.

**Comment by Skyvastern** [comment]
Hmm I see, so there is a well thought reason for using forward as (0, 0, -1). Though, the way basis.z is (0, 0, 1) kinda make things a bit confusing to me. Though still I don't fully understand the reasoning of using (0, 0, -1). But then, I don't really have much knowledge about conventions used in computer graphics and in general different areas of mathematics and engineering.

So I am closing this issue. Thank you both for providing me the information! :)

**Comment by akien-mga** [comment]
There's simply no coupling between `basis.z` (which is `(0, 0, 1`) in a identity matrix, as expected), and a constant that indicates what direction is pointing forward.

X+ is right, Y+ is up, so since the coordinate system is right-handed, Z+ is pointing "away" from the screen. In a 3D view, usually going forward is understood as going "away" from the player, i.e. along Z- `(0, 0, -1)`.
