### ISSUE TITLE
regression in 3.2 branch: nondeterministic Blend shape rendering glitch

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#42767]
**Godot version:**
0a2a93b165fa714e23e93e6d5c95ca37937c8f12

**OS/device including version:**
Windows 10 [10.0.18362.1082]
NVIDIA GeForce RTX 2080 Ti

**Issue description:**
Blendshapes seems to randomly glitch out. On a particular test model, they work about 30% of the time.

We do not see this problem in 3.2.3 stable. We suspect it is caused by the new software skinning change from #40313 that landed last week. (At first I thought it happens less, but actually it still seems to happen in some cases if Software Skinning is disabled in Project Settings.)

Note that it happens both with and without the recent commit 0a2a93b.

See video: https://www.youtube.com/watch?v=ZHO8LyQDmps

**Steps to reproduce:**
1. Open attached project.
2. Open the glb file in the testmodel folder
3. Open a new blank scene tab.
4. switch back and forth between tabs repeatedly.
(the issue also shows in the inspector if you expand mesh data, sometimes randomly.)
5. disable Software Skinning in Project Settings and verify that the issue no longer happens.

**Minimal reproduction project:**
[GLTFBug.zip](https://github.com/godotengine/godot/files/5371719/GLTFBug.zip)

**Comment by Calinou** [comment]
cc @lawnjelly

**Comment by smix8** [comment]
I noticed it appeared more within the more recent Godot version but after watching your video I think the underlying problem is older and not just a 3.2.3 addition. I reported an issue that is more or less the same problem with exploding blendshape glitches with Godot 3.2.0. https://github.com/godotengine/godot/issues/37854


The only workaround I found is reseting all blendshape values to zero after loading/changing a mesh resource as it prevents the glitch form appearing completely.

**Comment by lyuma** [comment]
Very nice insight @smix8 !!

Yes, when it shows the corruption, manually going through every blendshape slider and dragging it slightly up and back to 0 corrects the bad blendshapes. Most blendshapes are OK, but like one time it was 26 and 29 causing all the trouble. Another time it was 4, 30 and two others together. another time it was like 10 blendshapes adding on top of each other.

So I'd guess that the *underlying* issue in the engine is possibly the same between this and #37854.

The difference is the scenario to reproduce the issue. In the older case, it required a complicated series of steps involving replacing meshes at runtime. However, in this bug, merely opening a .glb scene and/or switching scene tabs within the godot editor is now sufficient to reproduce the problem.

I am completely unable to replicate *this series of reproduction steps* on 3.2.3.stable or 3.2.2 (don't have a copy of 3.2.0 on me atm)... so somehow the regression is that this bug became easier to reproduce.

Though now that I know that resetting all blendshapes to 0 "fixes" it temporarily until I switch tabs again, I might write a simple tool script to reset all blendshapes as a stopgap workaround until we can figure out a full fix.

**Comment by smix8** [comment]
The mesh preview screenshots that the editor automatically creates also capture the exploded blendshape meshes at random from time to time. So this bug is something that happens by default in Godot when meshes are loaded in a scene (the empty "screenshot maker" scene in this case) independent of a specific scene or mesh resource. It just seems to happen more often when the system is under load or the mesh resource is more taxing on the engine.

**Comment by akien-mga** [comment]
Regression fixed by #42846. (#37854 is still valid.)
