### ISSUE TITLE
Suggestions for the Plugin API

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#4276]
Important plugins, `SpatialEditorPlugin`, `CanvasItemPlugin`, `TileMapEditorPlugin`, or simply every C++ editors, should have it’s own API for extension. Based on #4174, various plugins can work together like one, but a big problem with this now is the plugins don’t know exactly what the others are doing.
For example creating a addon for filtering(Random tiles or auto-mapping, #843) tiles in a `TileMap` node is not possible, or not practical, you can handle the input but you don't know what tool the editor is using.

---

I created a small example for the `TileMapEditorPlugin`:  
- TileMapEditorPlugin
  - RandomTileAddon
  - PolygonDrawAddon
  - MinimapAddon

In this case we have three different plugins with different functionalities. They need differents API functions, and different levels of access.

| Name | Description | Required API |
| :-: | --- | --- |
| RandomTileAddon | Simple addon to draw random tiles automatically | The `TileMap` editor have the `_set_cell` function used by all tools of the editor, for this addon it is interesting to override the function when the user press a key or toggle a button |
| PolygonDrawAddon | Addon for drawing a "polygon" of tiles | This addon will use two existing features line drawing and bucket fill. If the user "activate" the addon all the viewport input will be handled by this addon, and the addon will release the "focus" when the polygon is finished. A virtual function for drawing on the editor viewport, for example `viewport_draw`, can be useful for this addon |
| MinimapEditorAddon | Simple addon to display a minimap of the `TileMap`, for faster navigation | This is a especial type of addon it don't need override any function, handle any viewport input or draw anything on the viewport. It will only need access to the viewport(#3992) to add a custom widget, which will handle all the input and drawing |

---

Other ideas:
- A addon for a editing a custom type can have a "special access", it can override some functions of the C++ plugin, or simply "override" the entire plugin.
- A similar API of the `SpatialEditorGizmo` for 2D can make addons for this type of node faster and simpler.
- Every plugin should have a simple API for extending it's toolbar menu, panels or docks.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by akien-mga** [comment]
CC @kubecz3k @vnen

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
