### ISSUE TITLE
Undo/Redo doesn't work for reset buttons

### ISSUE THREAD

**Issue by CitrusWire** [godotengine/godot#42797]
**Godot version:**
3.2.3

**Issue description:**
If I press one of those little reset buttons (the anti-clockwise three-quarter arrow) in the editor next to a inspector property that has changed, there's no way to undo that click. Or at least Ctrl-Z does nothing.

**Comment by Calinou** [comment]
Which property are you modifying? Undo/Redo definitely *does* work for reset buttons usually, but it might not work in pathological cases.

A minimal reproduction project would be helpful here.

**Comment by erictuvesson** [comment]
@CitrusWire Do you mean that you want to call these buttons using <kbd>Ctrl-Z</kbd> ? I don't think there are any keyboard shortcuts for calling the buttons there.

They are not added to the undo/redo queue, which could be discussed. 

![image](https://user-images.githubusercontent.com/1263211/97438943-d3090480-1925-11eb-8862-c4f9200fea37.png)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
