### ISSUE TITLE
ConcavePolygonShape2D not intersected by direct_space_state.intersect_point()

### ISSUE THREAD

**Issue by bfishman** [godotengine/godot#42807]
**OS:** Windows 10

**Godot Version:** 3.2.2 official

**Steps to Reproduce:**   Attempt to use `direct_space_state` to `intersect_point()` against a `ConcavePolygonShape2D`.  

**Reproducible example:** [ConcavePolyShape2DBugDemo.zip](https://github.com/godotengine/godot/files/5382607/ConcavePolyShape2DBugDemo.zip)

Note that point intersection works against `ConvexPolygonShape2D`, but fails against `ConcavePolygonShape2D`.  See gif:

![ConcavePolyShape2DBug](https://user-images.githubusercontent.com/3529531/96079575-16259b00-0e83-11eb-95e1-5a51aa396c8e.gif)

**Comment by madmiraal** [comment]
This is by design. A `ConcavePolygonShape2D` has no body, it only has a border of segments. This allows for the efficient calculation of collisions against complex concave collision shapes. If you want to determine whether a point is inside a concave collision body, you need to use a `ConllisionPolygon2D` in `Solids` build mode.

Note: A `CollisionPolygon2D` in `Segments` build mode will create a `ConcavePolygonShape2D` with the same outcome.

**Comment by akien-mga** [comment]
Should this be clarified in the documentation for `ConcavePolygonShape2D`? Or is it already clear enough?

**Comment by madmiraal** [comment]
Yes, it should be clarified in the documentation. The documentation for [`Physics2DDirectSpaceState.intersect_point()`](https://docs.godotengine.org/en/stable/classes/class_physics2ddirectspacestate.html#class-physics2ddirectspacestate-method-intersect-point) states:
> Checks whether a point is inside any shape.
