### ISSUE TITLE
Can not change to Blend of OneShot node in AnimationTreePlayer editor

### ISSUE THREAD

**Issue by volzhs** [godotengine/godot#4281]
**Operating system or device:**
Any OS.

**Issue description** (what happened, and what was expected):
Can not change to **Blend** of `OneShot` node in AnimationTreePlayer editor.
**Auto Restart** grabs mouse input.
Tested with 7d1b4567b07ac4d88bca58f70b773dd996d0cae6 commit.

**Steps to reproduce:**
![animationtreeplayer](https://cloud.githubusercontent.com/assets/8281454/14431035/cd50ef76-003e-11e6-8023-2a92f62d0411.gif)

**Link to minimal example project** (optional but very welcome):

Edit : change OS to any.

**Comment by slapin** [comment]
Yeah, seen this, it is before recent changes, probably added long ago.
Seems to be focus issue. @JoshuaGrams can you look into this while your memory is still fresh?

**Comment by slapin** [comment]
Forgot to mention - it is on Linux too, so set OS to any.

**Comment by JoshuaGrams** [comment]
I don't think it has anything to do with the AnimationTreePlayer: it's an editor/UI thing. The mouse selects the thing that's underneath rather than the menu. I believe it happens most places that you have a dropdown menu with other things below it in the dialog box...?

You can work around it by selecting the item you want with the keyboard and hitting Enter.

Anyway...the editor code seems pretty scary and I have been avoiding digging into it...so if there's someone else who's familiar with it... :)

**Comment by bojidar-bg** [comment]
Bump, is this still valid nowadays?

**Comment by thankjura** [comment]
Same problem

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
