### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by nachitoes** [godotengine/godot#42828]
I don't really have a bug but I don't know how to put a suggestion.

I have read many people say that the visual programming is very bad and others including doradoro say that the doc is poorly organized, I don't have to complain but they could read: https://www.doradoro.com/hasta-luego-godot/

Another thing I do not understand why people prefer Unity is closed source and very expensive capable that some mechanics not capable could read a little unity and implement and improve them for godot because I can not think of anything.

**Comment by Calinou** [comment]
This repository is now intended to be used for bug reports only.

If you have a *specific* feature proposal to make, open an issue in [godot-proposals](https://github.com/godotengine/godot-proposals/) **after** searching for possible duplicates. Otherwise, use one of the other [community channels](https://godotengine.org/community) to discuss ideas.
