### ISSUE TITLE
GLES2-GLES3

### ISSUE THREAD

**Issue by KJFM2021** [godotengine/godot#42833]
now i dont know if this is an issue or bug but when i go and open up godot it says gles2 and i go to switch to gles3 it just restarts and goes back to gles2 please help.

**Comment by Calinou** [comment]
This is likely because your graphics adapter doesn't support GLES3.

If you're certain it *does* support GLES3, then try to open the Project Settings and change **Rendering > Quality > Driver > Driver Name** instead of using the dropdown in the top-right corner. The dropdown is known not to persist its changes reliably on Windows due to file locking limitations.
