### ISSUE TITLE
Storing two Physics2DDirectBodyState as var from Physics2DServer.body_get_direct_state in GDScript overwrites the first var

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#42877]
Sorry for the long title, didn't know how to make it shorter.

**Godot version:**

3.2.3.stable

**OS/device including version:**

N/A

**Issue description:**

When storing the output of `Physics2DServer.body_get_direct_state` to a var in GDScript, it gets overwritten when you call this function again with another input.

**Steps to reproduce:**
```gdscript
# there exist vars nodeA and nodeB of type RigidBody2D
func _physics_process(delta):
	var stateA = Physics2DServer.body_get_direct_state(nodeA.get_rid())
	print("A before: ", stateA.transform.origin)
	var stateB = Physics2DServer.body_get_direct_state(nodeB.get_rid())
	print("A after: ", stateA.transform.origin)
	print("B: ", stateB.transform.origin)
```
This prints:
```
A before: <some value A>
A after: <some different value B>
B: <value B again>
```

**Minimal reproduction project:**

**Comment by mateosss** [comment]
Reading through I see that `Physics2DDirectBodyStateSW` is a singleton, so everytime you call `body_get_direct_state()` it just returns the same object, with an updated `body` property though. So that's what you are seeing.
Can anyone shed some light into the need for a singleton here? I couldn't find any comments or commits that talked about it.
