### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by jeffietheturtle** [godotengine/godot#42883]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10

**Issue description:**
I downloaded Godot, then I started using a tutorial but then the code did not work, so then I copied the entire thing, and that did not work at it had a error
E 0:00:12.325   instance_create: Script inherits from native type 'KinematicBody2D', so it can't be instanced in object of type 'Node2D'.
  <C++ Error>   Method failed. Returning: __null
  <C++ Source>  modules/gdscript/gdscript.cpp:325 @ instance_create()

than I followed a tutorial on a offical website of godot, copied it, did not work as it always said the error  above, than I downloaded a project saw it worked copied a project files, did not work, Please help me

**Comment by Ev1lbl0w** [comment]
You need to provide a reproduction project so the developers are able to tell if it's a problem with the engine or not.

If it turns out not to be a problem with the engine, then GitHub issues it not the place you're looking for; there are plenty of [ways of getting help](https://godotengine.org/community) on how to use Godot. :slightly_smiling_face:

**Comment by Xrayez** [comment]
> I downloaded Godot, then I started using a tutorial

Which tutorial? Consider opening an issue at https://github.com/godotengine/godot-docs.

**Comment by akien-mga** [comment]
You're assigning a script with `extends KinematicBody2D` to a node of type `Node2D`. That's not allowed, hence the error.

Either the tutorial is wrong (in which case see previous comments) or you made a mistake.

**Comment by jeffietheturtle** [comment]
how do you make the node kinematicbody2d
