### ISSUE TITLE
Driver not supported

### ISSUE THREAD

**Issue by Unieo** [godotengine/godot#42893]
**Godot version:** 3.2.3

**OS/device including version:** Microsoft Windows 10 Pro/10.0.19041 Build 19041 (It is graphics-related.)

**Issue description:** [In Godot] Well, when I hit the play button in the project it said my driver was not supported. [In Unity] But when I play a scene in Unity it works, I am very unhappy with this, please help. [I have an attachment if you need more info.]

**Steps to reproduce:** Well my driver version is "Intel(R) HD Graphics 3000"

**Minimal reproduction project:** None

**Additional File(s):** [Godot Driver Proof.docx](https://github.com/godotengine/godot/files/5398955/Godot.Driver.Proof.docx)

**Comment by qarmin** [comment]
You need to change in project settings(Project Settings -> Rendering -> Quality -> Driver Name) GLES 3 to GLES 2, because in Windows Intel HD 3000 doesn't support OpenGL ES 3.0.
I remember than on laptop I had i3-2330m with same video card, and on Linux after change from Windows I got 2x speedup(bunnymark score) and support for GLES 3.

**Comment by Unieo** [comment]
Thanks! I actually forgot to test it in GLES2, Sorry.
