### ISSUE TITLE
Simple mesh editing tools

### ISSUE THREAD

**Issue by unfa** [godotengine/godot#4304]
I miss some simple mesh editing capability in Godot.

By "simple"  mean a way to move a bunch of verticies around to do a quick fix of a without the need to reimport.

**Comment by nunodonato** [comment]
it's a game engine, not a 3d editor. even in tools like Unity or UE4 I think you can't do that without using third-party plugins

**Comment by Ace-Dragon** [comment]
I think it would be useful to at least have vertex painting in Godot (because you could then combine that with the visual shader nodes to create a sort of splatting system for terrains).

I don't see why that at least would be an issue since Unity and Unreal both have terrain painting (except in Godot you can use it with _any_ geometry)..

**Comment by slapin** [comment]
you can use export vars to edit your Vertex3Array, then in script use SurfaceTool
to generate vertices from set.
Also you can generate your mesh from spatial nodes, too.

**Comment by TongTungGiang** [comment]
Well actually it's not so necessary, since it's not a feature of a game engine

**Comment by DriNeo** [comment]
Ok it's not so necessary and not the first priority, but a basic modeling module (or plugin) limited to the video games needs,  could increase productivity a lot by avoiding import issues. 
Personnally I don't care about Unity or Unreal features areas, let's talk about what could be make developpement easier and the feasibility of the requested features.

**Comment by Zylann** [comment]
Terrains are a great example of geometry that must be modified, because 3D modeling software outputs a bigass mesh, which is not suitable as is for open-worlds. In case of heightmap It also lacks info such as heightfield for physics (mesh colliders are known to be slow).

Another example is procedural geometry such as generative trees or plants.

There is also CSG, which is present in Unreal, and Unity has a package for it (SabreCSG)

Also 2D would benefit from that, for example smart terrains (We already have Polygon2D btw but it's too basic)

All this isn't really 3D modeling, that's something you can expect to find in a game engine and it involves mesh generation/modification.

**Comment by tagcup** [comment]
This feature may be useful in different ways though.
For example, it would allow us to create something similar to Unity's [Cloth](https://docs.unity3d.com/Manual/class-Cloth.html) component in Godot, as an editor plugin.

**Comment by drequivalent** [comment]
+1 for porting SabreCSG over to Godot.

**Comment by Calinou** [comment]
@drequivalent Please do not bump issues without meaningful new information. (Moreover, I would question the feasability of porting an Unity add-on to Godot, as these engines work very differently, even though both support C# now.)

**Comment by akien-mga** [comment]
Closing as superseded by the more detailed #17411.

**Comment by shayneoneill** [comment]
While its not editing, there are still things that are suoer inconvenient to do in Godot, particularly working with nav and collision meshes. An aditor with just the ability to drag points, subdivide and extrude cubic faces would remove so much drag out of the workflow
