### ISSUE TITLE
Editor crashes if you try to export with `*` as exclude filter.

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot#43145]
**Godot version:**
3.2.3

**OS/device including version:**
```
$ uname -a
Linux pc 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
```

**Issue description:**
The editor crashes if you set "Filters to exclude files/folders from project" to `*` while also having a resource selected.

**Steps to reproduce:**
![crash](https://user-images.githubusercontent.com/17316999/97354519-c9d05700-1895-11eb-8f7c-4c192959b341.png)

**Minimal reproduction project:**
[export_crash.zip](https://github.com/godotengine/godot/files/5447785/export_crash.zip)

**Comment by mujpao** [comment]
I was working on this. The crash happens due to dividing by zero in `EditorExportPlatform::_save_pack_file()` and `EditorExportPlatform::_save_zip_file()` in `editor/editor_export.cpp`, which occurs if you try to export zero files from a project.

Also, should `EditorExportPlatform::export_project_files()`, which can call these functions, be changed so that it propagates the error values returned by these functions? Since right now it is not doing anything with the return values.
