### ISSUE TITLE
set text in Label by code is automatically translated 

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#43151]
**Godot version:**
3.2.3

**OS/device including version:**

ANY

**Issue description:**

var label = Label.new()
label.text = "WORD"

if the WORD is a key in translations used somewhere else, the label will display a translated text.
This is not intented. If the translated text required, we can use tr("WORD").
However, if the "WORD" is input from the user, it's weird to displayed a translated text.

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Ev1lbl0w** [comment]
This behavior is intended (https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html#converting-keys-to-text), because if the developer decides later to localize the game, there won't be any need to change code everywhere to enable that.

However, there is no way to disable this behavior, and as you pointed out, there are good cases where this needs to be disabled.
