### ISSUE TITLE
Make the code that colors functions and member variables smarter

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4323]
As the title says.
## The issue right now

The code for coloring the text for functions and member variables is fairly simplistic at the moment, the function coloring colors every piece of text before a pair of parenthesis and the member variable coloring colors every piece of text after a period.
## What can be done about it?

How about making the system smarter by using information gleaned from parsing the code in the editor.
- Only color member variables that are known to exist. Otherwise leave the text white.
- Only color functions that are known to exist (and only if the inheritance is correct). Otherwise leave the text white.
- For both, you could even have the editor throw an error if it's a safe bet that said white text would stop the game (I know we may not be able to catch everything, that's why I said a 'safe' bet).

---

In a sense, use the color feature to help developers write working code more of the time so there's less time quashing errors.

Comments?

**Comment by kubecz3k** [comment]
Sounds like a good idea, hovewer it will never work well because of weak typing (how you will color functions and members of nodes for which you have only references, what if in some regions of your code you are operating mostly on that kind of environment?) I know there are plans to add high performance static version of Gdscript to Godot <- with this version of language such things would be a breeze.

**Comment by bojidar-bg** [comment]
The thing is no matter how we do it, a slightly more complicated script will easily throw the system off. Consider for example the following tree and code:

- Node2D: SceneRoot (with script)
  - Button: Button [`pressed` connected to `button_pressed`]
  - Button2: Button2 (hidden, with another script, omitted for brevity) [`pressed` connected to `button2_pressed`]
  - Node2D: SomeNode

````gdscript
extends Node2D

func do_stuff():
  get_node("SomeNode").set_margin(MARGIN_LEFT, 5)

func button_pressed():
  get_node("SomeNode").replace_by(Control.new(), true)
  get_node("Button2").show()

func button2_pressed():
  do_stuff()
````

At this point, should `set_margin` be shown in white or red text? Or maybe in pink?
We might say, red, because it is "impossible" to click the button when clicked. But.. what if another script shows the button, or even calls `do_stuff` directly?
Ok, then it must be white, since it is a bug... but we still don't know if it is for sure.
So, pink then? Or maybe white, since we couldn't track it down that far?

Also, what about scripts that are shared between incompatible scenes? In some of them there might be a `"XX"` node, but in others it might be missing.

**Comment by akien-mga** [comment]
@Paulb23 started some work to better abstract the code highlighter in #17923. I'm not sure what's the current state of the algorithm used to highlight functions and member variables, but I guess some more improvements could be done based on the new architecture.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
