### ISSUE TITLE
GLES3.0 batching is turning anti-aliasing off

### ISSUE THREAD

**Issue by TimCoraxAudio** [godotengine/godot#43319]
**Godot version:**
3.2.4 beta 1 official

**OS/device including version:**
Ubuntu 18.04 LTS, GLES3.0, Nvidia GTX 1650

**Issue description:**
Batching on GLES3.0 is turning 2D anti-aliasing off

**Steps to reproduce:**
Create a scene with Line2D's, turn off HDR, turn on anti-aliasing on the node. Switch between batching and non-batching and you will see the issue quite clearly

**Minimal reproduction project:**
[Reproduction.zip](https://github.com/godotengine/godot/files/5491020/Reproduction.zip). This already has everything set up, all you need to do is to turn batching off and on

**Comment by lawnjelly** [comment]
Ah yes, this isn't too surprising, that anti-aliased batch types aren't well tested. I'll see if I can work out what is going on, it's probably just creating the wrong type, or I haven't implemented it yet(!). :grin:

**Comment by lawnjelly** [comment]
I've made a fix, it turns out I probably didn't implement it because anti-aliasing wouldn't be straight forward to batch for polys, as it requires a second pass to draw smoothed lines around the polys. So the PR just reverts to the legacy method if you use anti-aliasing.

Note this will be a lot slower. Also note it is switched off in mobile - anti aliased polys was never available in mobile, so this may affect if you are relying on this feature for a game.

**Comment by akien-mga** [comment]
Fixed by #43332.

> Note this will be a lot slower. Also note it is switched off in mobile - anti aliased polys was never available in mobile, so this may affect if you are relying on this feature for a game.

I guess this might be good to mention in the batching docs, so users are aware of the tradeoff?
