### ISSUE TITLE
C# MultiMesh Doesnt Work

### ISSUE THREAD

**Issue by NHodgesVFX** [godotengine/godot#43344]
**Godot version:**
3.2.3, 3.2.4 Beta1 Mono

**OS/device including version:**
Windows 10 64 Bit, RTX2080, GLES3

**Issue description:**
I wanted to use a multimesh but it doesn't seem to work, perhaps I'm doing somthing wrong in the C# but it seems correct. The C# doesn't work but the same code, roughly, in GDScript works fine.

C#

```C#
public override void _Ready()
    {
     MultiMeshInstance MMI = new MultiMeshInstance();
     MultiMesh MM = new MultiMesh();
     SphereMesh M = new SphereMesh();

     MM.TransformFormat = MultiMesh.TransformFormatEnum.Transform3d;
     MM.Mesh = M;
     MM.InstanceCount = 1;
     
     Transform t = new Transform();
     t.origin = new Vector3(5, 1, 0);
     MM.SetInstanceTransform(0, t);

     MMI.Multimesh = MM;
     AddChild(MMI);
    }
```
GDScript
```GDScript
func _ready():
	var MM = MultiMesh.new()
	var MMI = MultiMeshInstance.new()
	var M = SphereMesh.new()
	
	MM.transform_format = MultiMesh.TRANSFORM_3D
	MM.mesh = M
	MM.instance_count = 1
	
	var t = Transform()
	t.origin = Vector3(5, 1, 0)
	MM.set_instance_transform(0, t)
	
	MMI.multimesh = MM
	add_child(MMI)
```

**Steps to reproduce:**
Create a 3d scene, attach the above code as a script. add a camera.

**Minimal reproduction project:**

[MultiMeshIssue.zip](https://github.com/godotengine/godot/files/5498262/MultiMeshIssue.zip)

**Comment by kleonc** [comment]
It happens because `new Transform()` creates a transform with all values set to zero (so its basis has a zero scale and thus you can't see anything). It's implemented like this and can't be changed because [C#'s struct is not permitted to declare a parameterless instance constructor](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/language-specification/structs#default-values).
This is documented in the description of `Transform.Identity`:

https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/modules/mono/glue/GodotSharp/GodotSharp/Core/Transform.cs#L288-L294


Changing `Transform t = new Transform();` to `Transform t = Transform.Identity;` in your code fixes the issue.

You'd encounter similar problem for `Basis` or `Quat` because they also have non-zero default value in GDScript.

**Comment by NHodgesVFX** [comment]
> It happens because `new Transform()` creates a transform with all values set to zero (so its basis has a zero scale and thus you can't see anything). It's implemented like this and can't be changed because [C#'s struct is not permitted to declare a parameterless instance constructor](https://docs.microsoft.com/en-gb/dotnet/csharp/language-reference/language-specification/structs#default-values).
> This is documented in the description of `Transform.Identity`:
> 
> https://github.com/godotengine/godot/blob/30b6db99a99a94c64d906c1b828ff44f79a1bc75/modules/mono/glue/GodotSharp/GodotSharp/Core/Transform.cs#L288-L294
> 
> Changing `Transform t = new Transform();` to `Transform t = Transform.Identity;` in your code fixes the issue.
> 
> You'd encounter similar problem for `Basis` or `Quat` because they also have non-zero default value in GDScript.

Thank you for the help this fixes the issue. :)
