### ISSUE TITLE
Internationalizing function is not working

### ISSUE THREAD

**Issue by banti101** [godotengine/godot#43379]
**Godot version:**
3.2.3 official stable version

**OS/device including version:**
Ubuntu 20.04
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2)

**Issue description:**
Internationalizing function is not working

**Steps to reproduce:**
I have made .csv as it ment to be.
Then i add those translation to the localization.
Then 
func _ready():
	TranslationServer.set_locale("bn") ("bn" is for bengali)
and add my key to the lable , but its blank.
how ever if i use "en", its working... only for english.
I followed this tutorial... 
################
https://www.youtube.com/watch?v=GjMHoxsl5f8
################

**Minimal reproduction project:**
file was not uploading, so i made this drop box link...
https://www.dropbox.com/s/7l200mmp9aa564w/Internationalizing%20function.zip?dl=0

**Comment by Calinou** [comment]
You need to use a font that supports the character set used by Bengali. This is why nothing appears with the default project font, because BitmapFonts won't display any fallback character if the character can't be found in the font.

If you use [this DynamicFont](https://github.com/godotengine/godot/blob/master/thirdparty/fonts/NotoSansUI_Regular.ttf), you'll get this instead:

![image](https://user-images.githubusercontent.com/180032/98443021-f5aad280-2108-11eb-9d26-7316f9b80c45.png)

Keep in mind Godot doesn't support RTL and font shaping yet, so support for some languages may be limited or nonexistent.

**Comment by banti101** [comment]
still is does not working... i have used every type of font...
![Uploading Screenshot from 2020-11-25 14-27-12.png…]()

**Comment by banti101** [comment]
please report this issue... there is a huge Bengali user... we need Bengali support. i have used Japanese, Spanish... those are working, not Bengali. please plase plase.....

**Comment by akien-mga** [comment]
As @Calinou explained, two things are required for Bengali font rendering:

- A font that supports Bengali symbols. If you use Noto Sans Bengali, it works:
![Screenshot_20201125_100804](https://user-images.githubusercontent.com/4701338/100206035-20b56480-2f06-11eb-9a1f-7cf881c99c76.png)

- As you can see in the above screenshot, the actual rendered text is wrong even though the font has the correct glyphs, because Godot 3.2 doesn't support the advanced form of font shaping and diacritics that Bengali glyphs need to be properly rendered. This is what is being worked on by @bruvzg for Godot 4.0, and is already tracked in relevant feature proposals, so this bug doesn't need to be reopened. See https://godotengine.org/article/complex-text-layouts-progress-report-1 and https://godotengine.org/article/complex-text-layouts-progress-report-2

Here's how your project looks like in Godot 4.0 with PR #41100 and Noto Sans Bengali Regular:
![Screenshot_20201125_102633](https://user-images.githubusercontent.com/4701338/100208154-b3570300-2f08-11eb-8784-564e6af50793.png)

This seems better though it doesn't seem to match what system tools or Firefox renders (`আমি খেলছি ।`), I'll let @bruvzg comment on that.

**Comment by volzhs** [comment]
> still is does not working... i have used every type of font...
> Uploading Screenshot from 2020-11-25 14-27-12.png…

@banti101 you pressed "comment" button before completing upload.

**Comment by bruvzg** [comment]
> better though it doesn't seem to match what system tools or Firefox renders (আমি খেলছি ।), I'll let @bruvzg comment on that.

Seems to match what's displayed by LibreOffice, macOS FontBook tool, Firefox and Github app on my Android phone.
<img width="603" alt="Screenshot 2020-11-25 at 11 33 10" src="https://user-images.githubusercontent.com/7645683/100209036-0e412800-2f12-11eb-92b2-b213b831a5d3.png">

**Comment by akien-mga** [comment]
Hm maybe it's just a matter of font, or my system has a problem with Bengali shaping. I can't say if both versions are "correct".

Google Translate looks like Godot (minus the final।but that might be a different in the base string used):
![Screenshot_20201125_110108](https://user-images.githubusercontent.com/4701338/100212431-9cff7600-2f0d-11eb-8926-17dc73c9156e.png)

But Libreoffice, Kate or GitHub looks like it for me:
![Screenshot_20201125_110259](https://user-images.githubusercontent.com/4701338/100212570-cae4ba80-2f0d-11eb-8af5-1dd1cfff85dc.png)
(with that same string from Google Translate)

**Comment by bruvzg** [comment]
> But Libreoffice, Kate or GitHub looks like it for me:

I have checked multiple fonts and all are similar, except `Unifont` which have some missing and overlapping glyphs (first on the screenshot).

<img width="274" alt="Screenshot 2020-11-25 at 12 08 03" src="https://user-images.githubusercontent.com/7645683/100213210-06d04d80-2f17-11eb-9479-05fcfee041a9.png">

> Edit: Here's what happens when I paste the text in the Google Translate form:

Firefox is not doing anything like this for me, neither on macOS, nor on Linux.

**Comment by banti101** [comment]
Can you send me a demo project... It would be pretty helpful... I quite
don't understand, what I a missing...🙏☮️ Thanks in advance...

**Comment by akien-mga** [comment]
It's not possible to render Bengali correct in Godot 3.2, you have to wait for Godot 4.0.

You can also try this module via the GDNative builds: https://github.com/bruvzg/godot_tl
But it requires some technical knowledge to set things up.

**Comment by bruvzg** [comment]
> You can also try this module via the GDNative builds: https://github.com/bruvzg/godot_tl

A quick guide to use `godot_tl` for the similar demo project:

1. Download the module archiver from https://github.com/bruvzg/godot_tl/releases
2. Create "addons" folder in your project, and extract "libgdtl" from the download to the "addons"
![Screenshot 2020-11-26 at 11 27 28](https://user-images.githubusercontent.com/7645683/100333048-ccc87f80-2fda-11eb-850c-62269281af71.png)
3. Enable it in the "Project Settings"
![Screenshot 2020-11-26 at 11 17 36](https://user-images.githubusercontent.com/7645683/100333178-f1bcf280-2fda-11eb-9a71-4424f35272dc.png)
4. Add `TLLabel` control (do not use it as root node, or you will not be able to attach any scripts).
*Note:* module supports only three controls `TLLabel`, `TLLineEdit` and `TLRichTextEdit`, other controls won't work.
5. Add font files to the project folder
6. Create new font: in the `TLLabel` properties "base font" select "New TLFontFamily"
7. Create new font style, in the font properties enter "Regular" to the "Style name" and press "Add style" button
8. Add font file to the font family, in font properties "Regular" style section, select "New TLDynamicFontFace" in "0"
9. Set filename in the TLDynamicFontFace properties
10.  Do the same two steps for "1" and second font file
<img width="483" alt="Screenshot 2020-11-26 at 11 41 25" src="https://user-images.githubusercontent.com/7645683/100334367-5b89cc00-2fdc-11eb-9a30-1fa75673117e.png">

Here's modified project (without steps 1 and 2 done, the module is too large to upload it to the GitHub comments):
[Internationalizing function.zip](https://github.com/godotengine/godot/files/5601940/Internationalizing.function.zip)

<img width="312" alt="Screenshot 2020-11-26 at 11 48 59" src="https://user-images.githubusercontent.com/7645683/100335245-6f81fd80-2fdd-11eb-9602-c3f4be3bd3e1.png">

**Comment by Al-Shahrior** [comment]
@banti101 If you want to render bangla text in Godot 3.x you can use a [Bangla ANSI font](https://www.omicronlab.com/bangla-fonts.html). To use Bangla ANSI font you have to convert Bangla Unicode to ANSI. Hare is a screenshot.
![image](https://user-images.githubusercontent.com/31450209/104282697-a5ba0480-54d9-11eb-8cf7-add268fe3274.png)

I'm trying to write a script for godot 3.x that will convert Bangla unicode to Bangla ANSI. As everyone mentioned earlier comment Godot 4.0 gonna support RTL and font shaping. Screenshot ?
![image](https://user-images.githubusercontent.com/31450209/104283334-96878680-54da-11eb-9645-aea3e7bd20dd.png)
The text is a bit blurry.

**Comment by akien-mga** [comment]
>  The text is a bit blurry.

That's because you're zoomed in (118.9%). The other screenshot has zoom 100%, so it's not blurry.
