### ISSUE TITLE
Extend the dock system

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#4344]
**A feature request that docks can be placed at the bottom part of the editor too:**

The bottom part of the editor is treated like "three docks" (kind of..) It would be great if this space could be used for other docks too. Like the file browser to have access to some assets in the whole bottom part of the editor.
So it would be cool if the animation, Output and the Debug tab could be treated like any other dock.
(placed wherever the user wants them to be placed)
Since you often don't need these windows and I really like the concept of godot that only the things that are needed will be displayed, there possibly could be a button that lets the bottom area open and close. Or clicking the curent tab could minimized the bottom area. (and of course the bottom area should be opened automatically when an animationPlayer node is selected or the game is started...)

It also would be really useful to be able to place two docks at the bottom area. So you can have two docks at the same time. For example the debugger and the output window.

**Comment by Zylann** [comment]
As @vnen suggested I'll put my idea here:

**The ability to pin/toggle docks:**
I find the ability to toggle docks individually is handy when you don't need them to take lateral space all the time. Visual Studio (and other IDEs) do that, but Godot only has it on the bottom dock. Then they open again depending on the context. For example if you hide the inspector, you can code without it. But if you select a node in the scene tree or a resource, it would open again. Same for the Output console: if you debug your game, it opens to show you the prints(). To me, the Distraction-Free mode looks like a hardcoded layout to solve the most common use case. It's a matter of context, you don't need to see the same things depending on what you do.

**Comment by reduz** [comment]
I really want to avoid that we go into a more flexible Unity/Blender like
dock approach, I think the current approach of having editors appear on
demand on a relevant place flows lot better. I understand that the theory
is attractive, but without actual examples of why we should go this route
would have to make sense.

**Comment by reduz** [comment]
@Zylann  I think someone implemented a distraction-free mode at some point, not sure what happened with it.

**Comment by reduz** [comment]
@toger5 I think having so much flexiblity sucks. I have used Unity and Blender and it always gets difficult to find ways where you want to see all the information that is not cumbersome or confusing. 

The approach used in Godot is limited on purpose, so we can optimize our space much better instead of going the "yeah we can add a dock and the user can throw it anywhere, not our problem" route.

**Comment by Zylann** [comment]
@reduz I originaly had this idea because when I code in Godot, the inspector takes space on the right while I don't need it at all. I wouldn't say it becomes "claustrophobic", but compared to Sublime or VS and small screens / vertical screens, there is wasted horizontal space. Distraction Free partially solves the issue but it also hides the scene tree and file explorer.

Unity and Blender are bad examples IMHO because their dock system is too different, too "free-to-mess-everything". In Godot, VS or QtCreator there is a concept of "central widget", with docking areas on left, right and bottom that you can toggle, which is better.

**Comment by toger5** [comment]
@reduz I see your point and it is very convincing. One thing that still would be awesome is when you at lest would be able to hide the right, left dock space. Like Zylann proposed.

**Comment by toger5** [comment]
I will close this one.
If there should be drag and drop support or any other additions to the layout we will use another issue. this one is too ambiguous.
