### ISSUE TITLE
The type of namespace name 'Godot' could not be found

### ISSUE THREAD

**Issue by niceloaf** [godotengine/godot#43469]
**Godot version:**
Using Godot 3.2.3-stable

**OS/device including version:**
Solus 4.1

**Issue description:**
Whenever I edit a .cs file in neovim, it says that 'The type of namespace name 'Godot' could not be found (are you missing a using directive or assembly?)'

There is also these build warnings from msbuild
```
/home/USER/.nuget/packages/godot.net.sdk/3.2.3/Sdk/Sdk.props(31,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. hostfxr assembly:<unknown assembly> type:<unknown type> member:(null)
/usr/lib64/mono/msbuild/Current/bin/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(14,3): warning MSB4242: The SDK resolver "Microsoft.DotNet.MSBuildSdkResolver" failed to run. hostfxr assembly:<unknown assembly> type:<unknown type> member:(null)
```

**Steps to reproduce:**
1. Create a project
2. BUild the project
3. Create a new .cs file
4. Edit the .cs file
5. Wait for the omnisharp server to load
6. Error

**Comment by aaronfranke** [comment]
Please post a minimal reproduction project.

Do you have Mono installed?

**Comment by niceloaf** [comment]
Yes I have installed mono and this happens on every new project I create

**Comment by aaronfranke** [comment]
@niceloaf The problem is that it doesn't happen on my system, so I don't know if there's a problem with:

a) the projects you are creating

b) your system running any project

It would also be helpful to try running some of the [official demo projects](https://github.com/godotengine/godot-demo-projects/). These can also be downloaded individually by using the "Templates" tab in the Godot project manager.
