### ISSUE TITLE
Particles don't adjust curves to fit a randomized lifetime

### ISSUE THREAD

**Issue by eevee** [godotengine/godot#43485]
**Godot version:** 3.2.2
**OS/device including version:** Arch Linux x64, GTX 1660, GLEX3

The documentation [says](https://docs.godotengine.org/en/stable/classes/class_particlesmaterial.html) that properties "can have a CurveTexture applied to vary values over the lifetime of the particle."  But they appear to vary values over the _base_ lifetime, not the individual particle's _actual_ lifetime.  Consider this particle system, with a linear scale curve from 1 to 0, a lifetime of 2, and a lifetime randomness of 1:

![Peek 2020-11-12 14-37](https://user-images.githubusercontent.com/94112/98999420-01293f80-24f5-11eb-94c2-af14ee97eae1.gif)

I'd expect the particles to always shrink to nothing, but they clearly shrink at the same rate regardless of their individual lifetimes.

Same behavior occurs with other properties (at least color and tangential acceleration), and with both GPU and CPU particles.  I'm not sure if it's intentional, but it makes "fade out" or "shrink away" effects infeasible to combine with randomized lifetimes.

**Comment by akien-mga** [comment]
I agree that taking into account the randomness of the lifetime would likely be the most expected behavior here, though there might be use cases for the current one (not for fade out effects like this but possibly other effects which are intended to vary with a constant speed, e.g. looping over rainbow colors).

So this might need to be made optional? Opinions welcome, maybe there aren't many valid use cases for the current behavior and always taking the randomness into account would be better.

**Comment by RPicster** [comment]
I want to join in this discussion as I was about to open a duplicate.
This is a behaviour that actually makes the "Random Lifetime" property useless for most cases.
I work with other Engines and I, to be honest, cannot imagine a use case where this behaviour is desired.

The fix is very easy to implement and if we can agree that the behaviour below is the behaviour that a developer would look for, I would happily commit a fix.

Random Lifetime is one of the most important things to have in a Particle System, but if it messes with all the other "over-lifetime" parameters it's not usable.

At the moment I convert my Particle Materials to shaders to fix it with a very small addition to the shaders code e.g. for a gradient ramp color it would be:
`
COLOR = hue_rot_mat * textureLod(color_ramp, vec2(CUSTOM.y/CUSTOM.w, 0.0), 0.0);
`
instead of
`
COLOR = hue_rot_mat * textureLod(color_ramp, vec2(CUSTOM.y, 0.0), 0.0);
`

![GODOT-particles-random-lifetime](https://user-images.githubusercontent.com/9423774/101634228-b41f8700-3a28-11eb-9ac2-38c8c13218a2.gif)

[3.2.3_particle_rnd_lifetime_gradient.zip](https://github.com/godotengine/godot/files/5666071/3.2.3_particle_rnd_lifetime_gradient.zip)

**Comment by Calinou** [comment]
@RPicster or @eevee Feel free to open a pull request for this :slightly_smiling_face: 

I think this is worth fixing in the `3.2` branch, so we'll need a pull request for the `3.2` branch and one for `master`.

**Comment by lentsius-bark** [comment]
@RPicster that's the behaviour of be expecting as well! I've been avoiding the random lifetime because of this issue till now.
The trick you've showed will be useful, also hoping the fix makes into the core engine.
