### ISSUE TITLE
AStar throws error for ids greater than 2^31 - 1

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#43494]
**Godot version:**
3.2.3.stable

**Issue description:**
Max integer size in Godot is `2^63 - 1`, as stated [here](https://docs.godotengine.org/en/stable/classes/class_int.html). However, if you provide an id to AStar that is greater than `2^31 - 1`, it will throw an error.

I took a peek in AStar source code:
```cpp
void AStar::add_point(int p_id, const Vector3 &p_pos, real_t p_weight_scale) {
    ERR_FAIL_COND(p_id < 0);
    // ...
```

I believe the issue is that Godot's `int` is "Signed 64-bit integer type" while `p_id` argument that's of type `int` is something lower, probably signed 32-bit.

I discovered the issue when generating random ids for a waypoint system, where upper limit is Godot's int max. For now i'll just reduce the upper limit to be `2^31 - 1`.

**Steps to reproduce:**
Add points to AStar with ids greater than `2^31 - 1`.

**Comment by pWNn1sher** [comment]
Interesting ,
but In Cpp int takes value from `-2 ^ 31` to `(2^31)-1`. so anything greater than `((2^31) - 1) + x` will be handled as `(-(2^31) + x)` which causes error in the next line. **i bet u known this Stuff but ** Is it really necessary to make the whole implementation in `long long int` To support it the GDScript Standard. ?

**Comment by Calinou** [comment]
Shoudln't replacing `int` with `int64_t` do the trick?

**Comment by pWNn1sher** [comment]
Yep.

**Comment by Zylann** [comment]
FYI, I think there are a number of places (basically everywhere) in which `int` is used anyways, so I wouldnt be surprised if an issue like this happens elsewhere. The question would then be if we really want to support 64-bit integers in all these classes.

**Comment by slapin** [comment]
Can't consider this a bug, maybe a documentation issue. You can always have multiple AStar nodes as for this large number of nodes AStar will take seconds or even minutes to complete. No much point for 64-bit ids.

**Comment by akien-mga** [comment]
This needs design discussion beyond this specific AStar case, as we indeed use `int` throughout the codebase and many methods have similar restrictions. If this is by design / for performance, we need a way to make this appear clearly in the documentation, and the simplified `Variant::INT` and `Variant::FLOAT` doesn't really allow it for now.

**Comment by OlexiyKravchuk** [comment]
Is it acceptable to allow negative identifiers to be used as well? It seems to me that this would not break compatibility, and would solve a lot of problems at the same time.

**Comment by tavurth** [comment]
I would prefer that we could just support string identifiers instead of `int` but I guess that would lead to performance issues.

In any case, having negative ID support or at least a higher cap would help with the logistics of building on AStar. At the moment I feel a little handicapped in the way I can build ID calculations, and have reverted to just treating AStar as a simple array, so the ID system is useless.

**Comment by xylr117z4** [comment]
I believe if the int variant in godot is supposed to be a 64bit int as mentioned in the documentation.  https://docs.godotengine.org/en/stable/classes/class_int.html#class-int

Then all classes which can take an int in GD script should support 64bit. 
It's a matter of consistency and compatibility.

However if the int variant is changed to a 32bit int, then this would no longer be an issue. 
But I'd also want to see int_64 in GDscript.

I ran into this issue recently when working with procedural generation and creating paths for my world using AStar.
There isn't a good way for me to get IDs for my procedural points but I need repeatable results.
So I'm using hash(str(x)+str(y)) to encode the coordinates as their own ID.
The issue is that Hash returns a 64bit int, which breaks with Astar. 

These sorts of things are why we need either everything to be 64bit or 32bit. 
Or the more complex option, the option to set whether you're using 64bit or 32 bit.

**Comment by Calinou** [comment]
> I ran into this issue recently when working with procedural generation and creating paths for my world using AStar.
There isn't a good way for me to get IDs for my procedural points but I need repeatable results.
So I'm using hash(str(x)+str(y)) to encode the coordinates as their own ID.
The issue is that Hash returns a 64bit int, which breaks with Astar.

Can you keep the first (or last) 32 bits of the generated number instead? The risk of collisions should remain pretty low.

**Comment by xylr117z4** [comment]
> Can you keep the first (or last) 32 bits of the generated number instead, or modulo the number with `2^32 - 1`? The risk of collisions should remain pretty low this way. I haven't checked which method best preserves the random distribution though.

That's exactly what I ended up doing, just dropping the digits which are greater than 2^32-1.   I was just giving my opinion on the 64/32 issue.  Of course I realize that this is sort of a niche error in terms of general game design.
```static func get_id(point):
	var id = hash(str(point.x)+str(point.y))
	if(id > MAX_INT_32):
		var s_id = str(id)
		var len_diff = abs(str(MAX_INT_32).length()-s_id.length())+1
		s_id = s_id.right(len_diff)
		id = int(s_id)
	return id
```
(though I could probably just do s_id.left(10) now that I re-read that.)

**Comment by Zireael07** [comment]
Running into this (or what looks like this) in 3.5.

I wanted to decouple AStar points from input file order, so I tried to use hashes as identifiers, then 1d indices from 3d array... and both approaches fail with the complaint that the number is negative.

**Comment by Zireael07** [comment]
@akien-mga @Calinou I see 3.5.1 is on the horizon, can I hope for a fix?
