### ISSUE TITLE
Suggestion: Let the computer guess basic collision and occlusion polygons based off a sprite.

### ISSUE THREAD

**Issue by ChildishGiant** [godotengine/godot#4350]

**Comment by vnen** [comment]
Care to explain exactly what you want? I understand what you want, but you should elaborate a little about how you want it to work.

**Comment by SolarPolarMan** [comment]
So you could make the computer guess the outline of a polygon based off the parent (if it's a sprite) and have an input for how many verts you want the polygon to have.

**Comment by pwab** [comment]
If I understand this right this is for generating collision shapes just as [convex decomposition](https://godotengine.org/article/godot-3-2-adds-support-convex-decomposition) is doing this in 3D space. There are [external tools for this](https://www.codeandweb.com/physicseditor) but I would also like to see this implemented in Godot itself because this would be a very handy tool.

Depending on the parent it could:

- Polygon2D: Take the vertices of the parnet and copy them for its own polygon data
- Sprite: Trace the outline with specific image analysis algorithms (edge or feature detection?) and then calculating a hull based on input of the user (eg. for precision)

I'm not sure but aren't the algorithms already implemented for calculating the ArrayMesh of a MeshInstance2D from a Sprite ("Convert to 2D Mesh")?

**Comment by Calinou** [comment]
@pwab Has this been implemented by https://github.com/godotengine/godot/pull/27553?

**Comment by pwab** [comment]
Thank you @Calinou I haven't noticed that 😲! This looks super awesome and seems to be exactly what I was talking about. I have to get an alpha build as fast as possible to test this in the field. (So thank you again for your unofficial builds page 😄)

**Comment by Calinou** [comment]
I'll close this issue then. Thanks @ShyRed for implementing this feature :smiley:
