### ISSUE TITLE
Bug with Clip Content property of a Container when turning a set to current Camera2D node

### ISSUE THREAD

**Issue by progyan** [godotengine/godot#43543]
__Godot version:__ 3.2

__Issue description:__ I have created a `Container` node and put some `Sprite` nodes in it. Then I've set the `Clip Content` property to true and created a `current` `Camera2D` node. The program worked and there was no errors. When I've set the `Camera2D`'s `Rotating` property to true and turned the camera by 10 degrees (and zoomed it to 0.6). When I run the program, the `Container`'s clip content rectangle is slightly (approximately by 30% of its height) moved down and is rotating with the camera, like the camera wasn't rotated. What's the problem with it?

**Comment by Calinou** [comment]
@progyan Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by insomniacUNDERSCORElemon** [comment]
The only thing you need is a clipping control node that's rotated and visible content that is clipped (no camera needed). 

It keeps the maximum bounding box of the _corners_ of the control node, so it seems like maybe it's clipping after rotation rather than before? Or maybe non-rotated boxes were the only thing in mind with the original structure.

MRP: 

[rotated_clip_content_mrp.zip](https://github.com/godotengine/godot/files/6680285/rotated_clip_content_mrp.zip)

Screenshot of MRP:

![ArcoLinux_2021-06-19_04-26-43](https://user-images.githubusercontent.com/4397725/122636337-c56fdd00-d0b6-11eb-8625-032f6b86c7ec.png)

**Comment by KoBeWi** [comment]
Closing in favor of #87902, which is more precise.
