### ISSUE TITLE
Unused variable in gpu_particles_3d_editor_plugin.cpp

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#43643]
**Godot version:**
4.0.dev.custom_build. dd5485142

**Issue description:**
`image2` is assigned but never used anywhere
also `point_img2` is unused, because result is used only in `image2` 
https://github.com/godotengine/godot/blob/6497a3fb50802d2a56f5d6a586a66da0f887dc04/editor/plugins/gpu_particles_3d_editor_plugin.cpp#L387-L393

also `image` variable is not used
https://github.com/godotengine/godot/blob/6497a3fb50802d2a56f5d6a586a66da0f887dc04/editor/plugins/gpu_particles_3d_editor_plugin.cpp#L359-L364

**Comment by 2002Bishwajeet** [comment]
I am newbie here. I want to contribute here . can I work on this??

**Comment by qarmin** [comment]
I'm not sure if `junior job` tag is proper.
Basing on logic, this images should be used(code have 4 years, so author probably doesn't remember what exactly should this look like).
Probably code should looks that
```
tex.instance();
tex.create_from_image(image);
```
and a little lower
```
tex2.instance();
tex2.create_from_image(image2);
```
You can open PR with this fixes

**Comment by namedtoaster** [comment]
@qarmin shouldn't it be

```
tex->create_from_image(image);
```

and

```
tex2->create_from_image(image2);
```
?

I'm just starting contributing here, so I'm curious what this accomplishes? If that's all that needs to be done, I can submit a PR

**Comment by qarmin** [comment]
I don't even know when to use . or -> because QtCreator itself inserts the correct character (in this case indeed ->).

I don't know this code very well, but it seems to calculate and set the texture of the emission.

The problem is that there is an unused variable, the removal of which would create another unused variable and would make it necessary to remove most of the code from the function.

Since this function seems to make sense, the only solution will be to link the data inside through the `create_from_image` function.

This should be enough, so PR can be created with this changes(someone more familiar with the code should check PR soon).

**Comment by akien-mga** [comment]
To clarify, the current code does nothing due to the lack of calls to `tex->create_from_image(image);`. Well not nothing, but it assigns empty textures instead of the images created before.

So to fix this, there's two options:
- Add the calls to `tex->create_from_image(image);` to actually fill the textures. But then you need to actually see where this code is used in the editor and see if those textures are actually meant to be used, or if this bug which has never worked is meant for the trash can.
- Remove all the unused code as the current editor seems to work without it, so this might have been WIP that was discarded.

To decide, the best is to do the first option, use the GPUParticles3D editor plugin, see what changed and if that's good or bad.

The code was written by @reduz, but @JFonS may be able to tell if it's needed or not.

**Comment by namedtoaster** [comment]
Got it. Well I can wait for @JFonS or @reduz reply. Until then I’ll continue investigating

**Comment by JFonS** [comment]
I would say it's just missing the `create_from_image` calls. But tomorrow I will double-check the rest of the code does what it's meant to do.

**Comment by JFonS** [comment]
The `create_from_image` calls are present in 3.2, and it looks like @reduz removed them in 3f335ce3. We should investigate whether we can just add them back or there is an alternative way to achieve the same result.

**Comment by gxhamster** [comment]
I dont think that @reduz removed that.
I saw calls to create_from_image in his PR

**Comment by JFonS** [comment]
@gxhamster If you check the commit I mentioned (3f335ce), in the `editor/plugins/particles_editor_plugin.cpp` file, the `create_from_image()` calls were removed. 

It's probably just a mistake in the repetitive task of updating all `create_from_image()` calls, but someone needs to test if adding them back breaks anything.

**Comment by Calinou** [comment]
Closing per @and-rad's comment.
