### ISSUE TITLE
Strange error after running Godot-Ocean-Demo

### ISSUE THREAD

**Issue by silocoder** [godotengine/godot#43666]
Mac OS X, Mojave
Godot Engine v3.2.3.stable.official - https://godotengine.org
Using GLES3 video driver
OpenGL debugging not supported!
OpenGL ES 3.0 Renderer: NVIDIA GeForce GT 650M OpenGL Engine
CoreAudio: detected 2 channels
CoreAudio: audio buffer frames: 512 calculated latency: 11ms

Using this ocean creation app, https://github.com/SIsilicon/Godot-Ocean-Demo, displays the error message below in Output, repeatedly, when you click `Play the project` even though the `update_cube_map'` exists

`res://Projected-grid.gd:62 - Invalid call. Nonexistent function 'update_cube_map' in base 'Nil'.`

If you stop the project, the error keeps repeating ad infinitum even if you clear the Output.

**Comment by smix8** [comment]
The error happens due to saving the open scene with a running tool script that has the `cube_cam` variable empty by default. The saving updates the open editor scene, sets the script variable back to null and the running process function keeps spaming the error msg.

It is a project for a 3 year old version of Godot and prints a warning about this at project start. The project runs fine with Godot v3.2.4 but it was made with old function behaviour in mind. The `_ready()` function that adds the `cube_cam_inst` is only called ones in modern Godot in the editor so reseting the tool script with a scene save breaks this old project.

As a quick fix add safety checks for the tool script `_process()` function that reassigns the variable if it is empty and add the scene child again if it is missing at codeline 60 in `Projected-grid.gc` to prevent the error spam when you save the running scene.
```
if cube_cam_inst == null:
    if has_node("CubeCamera"):
        cube_cam_inst = get_node("CubeCamera")
    else:
        cube_cam_inst = cube_cam.instance()
```

**Comment by akien-mga** [comment]
Closing as it's not a Godot issue.

Please report such project specific issues to the project authors.
