### ISSUE TITLE
Zeros can be negative in vectors

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#43669]
**Godot version:**
3.2.3 stable and 3.2.4 beta 2

**OS/device including version:**
Windows 10

**Issue description:**
Zeros can be negative in vectors.

(This is probably a non-issue, so feel free to close this if it has no affect on anything)
(However, see #43407 where it apparently did cause a problem)

**Steps to reproduce:**
```gdscript
	print("0 * -1:", "\n", 0 * -1, "\n")
	print("Vector2.ZERO * -1:", "\n", Vector2.ZERO * -1, "\n")
	print("Vector3.ZERO * -1:", "\n", Vector3.ZERO * -1, "\n")
```

prints:
```gdscript
0 * -1:
0

Vector2.ZERO * -1:
(-0, -0)

Vector3.ZERO * -1:
(-0, -0, -0)
```

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
Negative zeros are normal and part of the IEE 754 standard for floating point representation: https://en.wikipedia.org/wiki/Signed_zero

The difference you see between printing a scalar and a vector is only because your scalar test using integers (in which `0 * -1 == 0`, there's no signed zero representation there. Vectors are floating-point, hence the difference.

Try this code:
```
var zero = 0.0 * -1
print(zero)  # -0
print(1 / zero)  # -inf
```
