### ISSUE TITLE
GridMap reports errors to the Physic server on removing cells

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#43712]
**Godot version:**
3.2.3 - 3.2.4

**OS/device including version:**
Win10/GTX1060

**Issue description:**
Removing the cell by calling `set_cell_item(x, y, z, -1)` will cause errors in the PhysicServer even if there is no physic body attached to cells.

**Steps to reproduce:**
Run attached project.
The following code will spam errors to the Output:

![image](https://user-images.githubusercontent.com/3036176/99772313-96db5500-2b1b-11eb-8a04-aa9d2b785f89.png)

```
ERROR: get: Condition "!id_map.has(p_rid.get_data())" is true. Returned: __null
   At: ./core/rid.h:150
ERROR: body_set_state: Condition "!body" is true.
   At: modules/bullet/bullet_physics_server.cpp:675
ERROR: Invalid ID.
   At: modules/bullet/bullet_physics_server.cpp:1551
```

**Minimal reproduction project:**
[GridMapBug.zip](https://github.com/godotengine/godot/files/5571950/GridMapBug.zip)

**Comment by XLIVE99** [comment]
I encountered this error too. But mine is on gridmap paint and it prints on "Output", so I analyzed this bug.
First, these are descriptions of the terms I'm going to use:
-Paint: Gridmap paint
-Action area: Smallest box that contains a paint (Here's some image for better explanation):
![Action_area](https://user-images.githubusercontent.com/30470295/111991851-d182e780-8b25-11eb-8007-cf9169857b05.png)

The bug only occurs if action happened in a frame which action area bigger than octant size. So in order to reproduce the bug, you need to:
-Undo + Paint
-Undo + Redo + Erase (Mouse right click)
-Clear selection + Paint
-Cut selection + Paint
If these actions is not bigger than octant size then the bug wont appear. However the bug can still appear while the action area is smaller than or equal to octant size in some special conditions:

**Gridmap octant size setted to 2 for easier visualization.**
**All action areas which contains both green and red tile will cause the bug.**

![Bugmap_octant2](https://user-images.githubusercontent.com/30470295/111999719-4b1ed380-8b2e-11eb-8843-e0762f1e1833.png)

If octant size setted to 3 then all areas as shown above will increase 1 cell, like this:
![resim_2021-03-22_165305](https://user-images.githubusercontent.com/30470295/112000460-12332e80-8b2f-11eb-854a-d08c6ea457aa.png)

Sometimes the bug will appear as infinite loop (only output if input happens such as mouse motion), and sometimes it happens once or third. It depends on where you click first. If infinite loop happens then in order to get rid of the bug, you need to paint and erase the corresponding tile.

Undo + Redo + Erase doesn't produce bug always, as mentioned above only erasing tiles which cause infinite loop will give error once.

Hope this helps to solve the bug.
