### ISSUE TITLE
WebM with alpha showing black background instead of transparent.

### ISSUE THREAD

**Issue by Reyjakai** [godotengine/godot#43736]
**Godot version:**
v3.2.3.stable.official

**OS/device including version:**
GLES3

**Issue description:**
Playing a .webm file that was encoded with an alpha channel has a black background in godot. This is how I'm planning on doing all attack and battle animations, and it's much cheaper on memory than using a .png spritesheet. 

**Steps to reproduce:**
1. Create a VideoPlayer node.
2. Add a .webm file to the VideoPlayer node.

**Minimal reproduction project:**
[WebM Alpha.zip](https://github.com/godotengine/godot/files/5576829/WebM.Alpha.zip)

**Comment by Calinou** [comment]
I don't think support for transparent WebM was ever implemented. Not that our current WebM playback is too reliable anyway: https://github.com/godotengine/godot/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+webm+label%3Abug

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/1070, as feature proposals are now tracked in the Godot proposals repository.

**Comment by Railwanderer** [comment]
Hey is it possible for this to get solved in the next two months? I need this feature for a recent project.
I was able to load webm files and play them - only if they were converted to webm v.8 first - but the alpha channel turns out black, no transparent. I need those transparent videos to animate materials. A mask would also be fine though.

Another good work around would be to use animated textures, splitting the video into separate png first using ffmpeg, but assigning all those hundreds of textures frame by frame is not really a serious option. Is it possible to load like 30 png files as frames for an animated texture?

**Comment by Calinou** [comment]
> Hey is it possible for this to get solved in the next two months? I need this feature for a recent project.

Nobody really knows how to implement this, unfortunately.

**Comment by Railwanderer** [comment]
hehe okay, I wish I knew how to work on the source code of the engine at all, but I am still quite new to Godot, although it helped me complete one project already! For the next project I ll try to use c# instead of gdscript, since I am actually more experienced in java then dynamic languages. maybe some time after that I ll make it to help at little tasks :)

I wonder where to begin though, since the video gets played on a sphere meshs material already, I can even flip to the inside. Just the transparency is not there.

Any hint for my second approach, using the animated textures?

**Comment by Railwanderer** [comment]
> If you only need materials with additive blending, you can already have a transparent video displaying this way (since that's how additive blending works). Black will appear to be fully transprent.
> 

Unfortunately I need several layers of videos to animate a scene made of a sphere.

> Alternatively, you can use a chroma keying shader on a CanvasItemMaterial or SpatialMaterial.
this sounds good, I have the video edited so that the transparent parts could be green for example. Can I somehow mask the green and replace it with transparent pixels? or use a mask to play only a part of the video?

**Comment by Railwanderer** [comment]
> > Hey is it possible for this to get solved in the next two months? I need this feature for a recent project.
> 
> Nobody really knows how to implement this, unfortunately.
> 
> If you only need materials with additive blending, you can already have a transparent video displaying this way (since that's how additive blending works). Black will appear to be fully transprent.
> 
> Alternatively, you can use a chroma keying shader on a CanvasItemMaterial or SpatialMaterial.

Yes, thanks a lot for the hint to use a shader. That worked fine. Now I just need a better video editing software to create masks and cut out greenscren stuff. :)

**Comment by Calinou** [comment]
> Now I just need a better video editing software to create masks and cut out greenscreen stuff. :)

I think [Olive](https://olivevideoeditor.org/) has chroma keying features, even in its current stable (0.1) version.

**Comment by Railwanderer** [comment]
> > Now I just need a better video editing software to create masks and cut out greenscreen stuff. :)
> 
> I think [Olive](https://olivevideoeditor.org/) has chroma keying features, even in its current stable version (0.1, not the 0.2 rewrite).

Hey thanks for the hint, I checked it out already.
Unfortunately the problem seems to be the video encoding process itself. My source video is mov and I can t convert it to webm without losses, so I always get borders around my mask. these are pixels that used to be transparent and most players can t handle it, including Godot and most video players.
I don t know why Godot has to use such a video format and doesn't leave other options. It is really a pain and I am trying to find a workaround for days now... I wish I could just write my own input stream and buffer the video from any format I want like in most frameworks.

**Comment by Calinou** [comment]
> I don t know why Godot has to use such a video format and doesn't leave other options. 

Most other video codecs like H.264 are patent-encumbered.

**Comment by Railwanderer** [comment]
Okay things broke again. This is really a pain if not unsusable, to play a video on the inside of a sphere and have it transparent, I created a viewport added the videoplayer, spent days to figure out how to get it with a mask pixelperfect to webm format. Then used this viewport as a stream texture in a spartial shader material, keyed out the chroma value and had a video on one part of the sphere with transparent background around it only to then figure out that all other transparent static spatial materials behind it broke... nice one -.-

Chroma keying works for one video but breaks several

**Comment by Railwanderer** [comment]
> > I don t know why Godot has to use such a video format and doesn't leave other options.
> 
> Most other video codecs like H.264 are patent-encumbered. Supporting them in an open source engine is risky in countries where software patents are followed, such as the United States.
> 
> That said, there are plans to remove built-in video playback functionality in profit of an official [GDNative add-on based on FFmpeg](https://github.com/KidRigger/godot-videodecoder). FFmpeg is larger, but is much more compatible and has the potential to be less buggy.

That was quite a good hint. I finally managed it, preprocessing the video in several video editors such as adobe after effects > shortcut > then used ffmpeg to convert lossless and i had a video with my pixelperfect magenta mask applied and was able to key it out using a shader :) now I have a transparent video playing inside a sphere mesh displaying serveral layer in front and beyond it 🤠
