### ISSUE TITLE
Vulkan: Triplanar mapping not working in world space

### ISSUE THREAD

**Issue by fracteed** [godotengine/godot#43741]
**Godot version:**
current 4.0 master

**OS/device including version:**
Win10 960m

**Issue description:**
When switching between local and world space using the checkbox in the spatial material settings, there is no change. It stays in local space. As can be seen in this image, local on left and world on the right. They are identical. 

To my knowledge, this has never worked in 4.0. When converting to a shadermaterial, you can see that there is no mention of it in the render_mode line of the shader. 

![triplanar](https://user-images.githubusercontent.com/7741669/99870226-9d55f380-2c25-11eb-9fa4-1f2647c9a106.jpg)

**Minimal reproduction project:**
[triplanar_bug.zip](https://github.com/godotengine/godot/files/5577179/triplanar_bug.zip)

**Comment by CaptainProton42** [comment]
I think I figured out what's going on: On 3.2.x, there is only a single `FLAG_TRIPLANAR_USE_WORLD` for the material which adds `world_vertex_coords` to `render_mode`. However, in 4.x this changes to two seperate flags `FLAG_UV1_USE_WORLD_TRIPLANAR` and `FLAG_UV2_USE_WORLD_TRIPLANAR` which means that just setting the render mode won't work anymore since it would affect both UVs.

The best solution I could come up with is to use `WORLD_MATRIX` to transform `NORMAL` and `VERTEX` if the respective flags are enabled (in `scene\resources\material.cpp`):

```
if (flags[FLAG_UV1_USE_TRIPLANAR]) {
	if (flags[FLAG_UV1_USE_WORLD_TRIPLANAR]) {
		code += "\tuv1_power_normal=pow(abs(mat3(WORLD_MATRIX) * NORMAL),vec3(uv1_blend_sharpness));\n";
		code += "\tuv1_triplanar_pos = (WORLD_MATRIX * vec4(VERTEX, 1.0f)).xyz * uv1_scale + uv1_offset;\n";
	} else {
		code += "\tuv1_power_normal=pow(abs(NORMAL),vec3(uv1_blend_sharpness));\n";
		code += "\tuv1_triplanar_pos = VERTEX * uv1_scale + uv1_offset;\n";
	}
	code += "\tuv1_power_normal/=dot(uv1_power_normal,vec3(1.0));\n";
	code += "\tuv1_triplanar_pos *= vec3(1.0,-1.0, 1.0);\n";
}
```

I'm still pretty new to contributing but I feel comfortable creating a PR with this unless someone comes up with a better solution :)

**Comment by fracteed** [comment]
Thanks @CaptainProton42 for fixing this!
