### ISSUE TITLE
Engine singletons which inherit from `Reference` print an error on editor startup (C++)

### ISSUE THREAD

**Issue by Xrayez** [godotengine/godot#43783]
**Godot version:**
3.2.4 beta b900ec03f
Related to change in #43682 (CC @RandomShaper)

**OS/device including version:**
Windows 10.

**Issue description:**
![image](https://user-images.githubusercontent.com/17108460/99918635-066e6180-2d21-11eb-91ee-0750abbbd452.png)

I don't quite see a substantial reason for this, why? I have a number of singletons already registered like that and they work perfectly fine for a long time now. One of the main use cases why I'd like to use `Reference` is because certain classes can act both like a singleton *and* be instantiated as local instances:

- [`Random`](https://github.com/goostengine/goost/blob/gd3/core/math/random.h) singletons:
    - These classes can be accessed from anywhere and the seed is randomized automatically for those. But local instances can also be instantiated if you do need to control the seed etc.
- [`PolyBoolean2D`](https://github.com/goostengine/goost/blob/gd3/core/math/2d/geometry/poly/boolean/poly_boolean.h) etc.
    - As a singleton, you're not allowed to setup parameters, but local instances can.

Before forcing such intrusive messages, it's required that:
- static methods support is implemented
- namespace issues resolved
- properly support `Reference`-based singletons (documentation etc).

That said, #43682 only attempts to prevent programming errors by hiding the underlying problem. The message should be part of documentation (just like the changes made to `Variant` in `3.2-stable`), not part of run-time behavior. Unfortunately, none of these changes are documented currently.

So far, I haven't experienced any errors with such approach, both in debug and release builds, so the error is not legitimate and should be reverted.

The situation is pretty much the same as with #42653, namely that I don't like when the engine decides for me what I can and cannot do, especially if the error does *not* handle *all* use cases, else the engine should just crash if that's really a problem. 😛

I mean, it's not that critical to warrant printing an error message, currently this just pollutes the debugger with messages and hides more important errors to be noticed. If you suggest that I need to make all those classes inherit `Object`, then sorry it's not really possible by design, else it would be too easy to introduce leaks into the project, that's just shooting yourself in the foot with another foot.

**Steps to reproduce:**
1. Compile https://github.com/goostengine/goost
2. Run editor.

**Minimal reproduction project:**
N/A

**Comment by Rprabudeva** [comment]
I would like to contribute

**Comment by RandomShaper** [comment]
The aim of the message is to prevent the surprising behavior that arises from a not well supported feature.

In the past, `Variant` would not realize an `Object *` is a `Reference` so it wouldn't deal with its reference count. One consequence of that is that you could register a singleton, regardless `Reference` or not, and just manage its lifecycle yourself. Now that's not the situation anymore. Because of that, one of the typical patterns for registering a singleton leads to a double free bug:

```
SomeClassExtendingReference *instance;

void register_some_module_types() {
    ClassDB::register_class<SomeClassExtendingReference>();
    Engine::get_singleton()->add_singleton(Engine::Singleton("SomeSingleton", instance));
}

void unregister_some_module_types() {
    memdelete(Engine::get_singleton()->get_singleton_object("SomeSingleton")); // It was already freed when GDScriptLanguage was destroyed
}
```

There's indeed a way to have a `Reference`-derived singleton without running into that situation, as it's done in Goost: you keep yourself a `Ref<>` to the singleton object and don't `memdelete()` it directly, bur rather `unref()` it.

I'm submitting a PR that constraints the warning to really fit the unsupported case. After that, you should no longer get errors about it, but cases where it's still not being done the right way will.
