### ISSUE TITLE
Custom Resources don't automatically free themselves when no longer used

### ISSUE THREAD

**Issue by pikol93** [godotengine/godot#43791]
**Godot version:**
3.2.3.stable.mono

**OS/device including version:**
Windows 10

**Issue description:**
Note: I'm not certain that this issue is reproducible only by using C#. I have not tested GDScript yet.

Classes inheriting from Resource don't get freed the same way built-in Resources do. Normally when freeing a built-in Node, all the resources it own will befreed as well if no other node uses them. This is not the case with custom Resources as you have to call `Dispose()` on them explicitly for them to be freed.

I've included a graph displaying the amount of cached Resources still in game after changing the scenes multiple times. The same effect can be achieved by downloading the minimal reproduction project.
![resourceGraph](https://user-images.githubusercontent.com/40030490/99960309-d0ff5d80-2d8c-11eb-84be-b499f338059b.png)
Notice how initially the project only contains 3 Resources, but after changing the scene to the one containing custom Resources and back the Resources don't get cleared and still remain in memory (their count doesn't go below 10).

If this in fact is not a bug, I'd push for updating the documentation as it currently states that Resources are managed automatically and will get freed after no Node use them anymore.

**Steps to reproduce:**
1. Create a class that inherits from Resource
2. Create new Resource in editor and attach the script to it
3. Use the Resource in a scene
4. Free the node that uses said Resource

**Minimal reproduction project:**
[ResourceIssue.zip](https://github.com/godotengine/godot/files/5582773/ResourceIssue.zip)

**Comment by Calinou** [comment]
See also #42954, #41543, #36649 and #35450.

**Comment by Tobi-Mob** [comment]
I took your example and added a forced GC/Finalize call to EmptyScene.cs

``` 
        //EmptyScene.cs
        public override void _Process(float delta)
        {
            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();
        }
```

This causes the Resource count to revert back to 3 after switching back to the EmptyScene

![grafik](https://user-images.githubusercontent.com/69400800/133052920-dad28793-e3ab-4986-89c5-838106c8ace6.png)

Looks to me like this is working rather fine. The finalizer Thread is just taking his time, because there is no pressure.
Since this behaviour is now mentioned in the documentation (https://github.com/godotengine/godot/pull/43793), could this issue be closed?

**Comment by Calinou** [comment]
Closing per @Tobi-Mob's comment.
