### ISSUE TITLE
[FBX] Meshes attached to a Skeleton should be parented to that Skeleton.

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#43823]
**Godot version:**
3.2.4 beta2

**OS/device including version:**
Windows 10.0.19041.630
NVidia GeForce RTX 2080 Ti 452.06

**Issue description:**
With the new FBX importer, meshes are not inside of their Skeleton. While this may literally match what is inside the .fbx file, it is a Godot convention that meshes with a skeleton be placed inside of the Skeleton they are attached to.

Because Godot moves a skinned mesh relative to its own position rather than that of the skeleton, having the mesh inside the skeleton matches more closely the behavior of other engines.
(For example, moving or rotating the Skeleton *should* move the meshes attached to that skeleton, and did so with the old importer, as well as with glTF importer. But with beta2, moving the Skeleton does not move the attached meshes)

Changing the scene hierarchy in this way may be compatibility breaking with existing animations designed to target a mesh.
![image](https://user-images.githubusercontent.com/39946030/100115104-fb055e00-2e26-11eb-8154-17b3cbf568af.png)

**Steps to reproduce:**
1. Open the attached project.
2. Click Bunny_Farmer.fbx and click Reimport in the import panel.
3. Open the imported scene.
4. Ignore all the unused Spatial nodes to make this more obvious.
5. Notice that the parent of Rabbit is not the Rabbit_Skeleton. The other indicator of this issue is that the Skeleton shows a "revert symbol" next to it. Godot recognizes that a mesh should be parented to its skeleton, so the new behavior is unusual.

**Minimal reproduction project:**
[fbx_issues.zip](https://github.com/godotengine/godot/files/5590831/fbx_issues.zip)

**Comment by RevoluPowered** [comment]
Sorry I don't think this is worth implementing since it would most likely cause breakage. Moving these nodes breaks the strong linking the FBX Document provides from the FBX ID.

**Comment by BastiaanOlij** [comment]
@lyuma We already discussed this all today on the chat server but just sharing for everyone looking at this and wondering.

Having a look at your FBX file, the problem wouldn't actually be solved by re-parenting. The problem looks to be exactly the same issue I am running against. You can see it in your screenshots as well but from my own import:
![image](https://user-images.githubusercontent.com/1945449/109950367-8a78b200-7d30-11eb-806a-d9bb796f8379.png)

That is the transform on the bunny mesh that will rotate the bunny mesh 90 degrees and scale it up 100x. After this transform is applied the bunny matches up with the rest pose of the armature.

But Godot applies the deformations first and then applies the Model-View-Projection matrix. That means that the deformations are completely wrong because they happen on the wrong orientation and scale.

The previous FBX importer would apply this transform to the mesh data resulting in a mesh that matched the armature. That solves the problem but would create new problems if the mesh is used on multiple nodes or if this node is keyframed with the rotation and scale encoded in the keyframe. As we discussed in chat both are incredibly unlikely scenarios due to the flow on effects of doing so but without having enough sample files to confirm no 3d modeling software is crazy enough to do this.... The format seems to support it. 

The solution @RevoluPowered is currently working on adds an option to apply the transform before deformation but at the cost of extra instructions in the shader. This would be a solution that would work even in those unlikely scenarios.

In the end note that both skeleton and rabbit mesh are childed to a "RootNode" so movement wise we always move skeleton and mesh in unison. If this makes it more close to the FBX internal structure and we see merit in keeping that in tact, its really same old same old.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
