### ISSUE TITLE
Make tooltip cause error, when error show, the PanelContainer rect_size is wrong.

### ISSUE THREAD

**Issue by wijat** [godotengine/godot#43847]
**Godot version:**

Godot Engine v3.2.3.stable.official

**OS/device including version:**

GLES3 on Win10 PC

**Issue description:**

Make tooltip cause error, when error show, the **PanelContainer** rect_size is wrong.

**Steps to reproduce:**
Use the code to show.
![screenshot_2020_11_25](https://user-images.githubusercontent.com/8220843/100201144-a3581700-2f3a-11eb-8201-daf4e1a846a4.png)
![screenshot_2020_11_251](https://user-images.githubusercontent.com/8220843/100201147-a521da80-2f3a-11eb-9efd-6b2f8f915c4e.png)
![screenshot_2020_11_252](https://user-images.githubusercontent.com/8220843/100201149-a5ba7100-2f3a-11eb-87c4-9eda37b286e0.png)
![screenshot_2020_11_253](https://user-images.githubusercontent.com/8220843/100201151-a6530780-2f3a-11eb-9aef-c34f7703b2b7.png)

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@wijat Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
