### ISSUE TITLE
Normal maps don't affect ReflectionProbes in GLES2

### ISSUE THREAD

**Issue by Firepal** [godotengine/godot#43873]
**Godot version:**
3.2.3

**OS/device including version:**
Windows 10 RTX2060

**Issue description:**
Using a SpatialMaterial with a normal map doesn't perturb a ReflectionProbe reflection,
but it does perturb a WorldEnvironment background reflection.
(The quad on the left is reflecting a checkerboard quad out of view)
![image](https://user-images.githubusercontent.com/29317321/100292845-f30e0100-2f81-11eb-9842-9b4ba3b41a7d.png)

AFAIK this behavior is undocumented, so I assume it's not a shader optimization?

**Steps to reproduce:**
1. Create any mesh with a SpatialMaterial and give it a normal map
2. Place a ReflectionProbe into the scene
3. Move that mesh into the ReflectionProbe

The mesh will use the mesh's unperturbed normals for sampling the ReflectionProbe.

**Minimal reproduction project:**
[normalMapReflection.zip](https://github.com/godotengine/godot/files/5599729/normalMapReflection.zip)

**Comment by clayjohn** [comment]
My guess is that this will be fixed by changing this line (and the equivalent for reflection probes 2) to "normal" instead of "normal_interp" 
https://github.com/godotengine/godot/blob/17eb869231b044ac0a744ea49b43e045a6312c35/drivers/gles2/shaders/scene.glsl#L1603

Normal is the normal with normalmaps applied. While normal_interp comes straight from the vertex function.

**Comment by Firepal** [comment]
@clayjohn What a very educated guess! :)

**Comment by akien-mga** [comment]
Fixed by #43885.
