### ISSUE TITLE
sliders of Color Picker behave wrong in RAW mode

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4396]
there is a button named `raw mode` in color picker,
when turned on, rgb become from 0 to 1 but not from 0 to 255.
bug1: the slider still has the range of 0~255. it should be 0~1 then
bug2: alpha is not affected, at least in preview, e.g. 128 is still half opaque

**Comment by MarianoGnu** [comment]
This is not a bug, RAW mode allows to multiply the value for over 1, increasing the gamma of the sprite in the given colors, try putting the value in 2,2,2 to know what i mean

**Comment by buckle2000** [comment]
@MarianoGnu I was talking about the UI element

**Comment by MarianoGnu** [comment]
0 to 255 is the value of Color8(), 0 to 1 is used in the Color() constructor, and colors avobe 1 are used for HDR.
if i set both default values form 0 to 255 it will be confusing, because it's using two coloration scales according to the mode...

**Comment by buckle2000** [comment]
@MarianoGnu I was talking about the sliders, not `Color8` or something.
The **slider** controlling alpha in Color Picker has range of 0~255 whether RAW mode is turned on.

**Comment by MarianoGnu** [comment]
Ah, right, that's not correct.

**Comment by djrm** [comment]
This is actually strange, the code seems to be very explicit that it has to happen to alpha 

https://github.com/godotengine/godot/blob/master/scene/gui/color_picker.cpp#L143
https://github.com/godotengine/godot/blob/master/scene/gui/color_picker.cpp#L174

**Comment by vnen** [comment]
@djrm [right above, outside the condition](https://github.com/godotengine/godot/blob/master/scene/gui/color_picker.cpp#L172), it set max to 255, I believe this is what this issue is about. The slider goes to 255 even in raw mode.

**Comment by djrm** [comment]
what i was trying to say, is that maybe is there for a reason (i dont know). Also i noted that the color picker is very broken, but im fixing it.

**Comment by djrm** [comment]
so theres is no bug here the sliders goes from 0 to 255 even though the internal values are from 0 to 1, the thing with Raw mode is that you should be able to increase the R,G,B components past the 1 value, even if that means that they are really 255, so in this case the get_color function will return a color that looks like a Color8, even though its not a Color8, alpha slider max value cant be set to 1 because that would be an inconsistent behavior (because as explained before value in non raw mode are from 0 - 255 even though the internal representation is from 0 to 1)

**Comment by akien-mga** [comment]
What's the status on this one guys, is #5511 good to merge, and if not, what should be changed?
