### ISSUE TITLE
PackedArray's allocating twice at the same memory at some conditions

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#43983]
**Godot version:**
b9a2787bd164602e866ecac1527020e0e1c34da8

**OS/device including version:**
Win10

**Issue description:**
It's a very strange bug I discovered recently - in `_draw` method PackedArray seems allocates memory twice at the same location

![image](https://user-images.githubusercontent.com/3036176/100597740-da4d7480-330e-11eb-8c31-daa40fa9ece7.png) 

the correct result should be 

![image](https://user-images.githubusercontent.com/3036176/100598016-3912ee00-330f-11eb-8069-7901d6ea1702.png) if you push array initialization away from _draw the result will be correct.

**Minimal reproduction project:**
[ArrayMemoryBug.zip](https://github.com/godotengine/godot/files/5615348/ArrayMemoryBug.zip)

**Comment by vnen** [comment]
Looks the same as #36892. Probably a regression from the changes in variant call.

**Comment by bruvzg** [comment]
Seems like all `var x = PackedXArray()` calls return the same instance of array, instead of creating a new one:

```
	var a = PackedInt32Array()
	var b = PackedInt32Array()
	a.push_back(222)
	var c = PackedInt32Array()
	b.push_back(333)
	var d = PackedInt64Array()

	print(a)
	print(b)
	print(c)
	print(d)
```

Prints:
```
[222, 333]
[222, 333]
[222, 333]
[]
```

**Comment by vnen** [comment]
Ah, I think I know why this happens. GDScript optimizes it by constructing on compile time. If packed arrays equality is based on value instead of reference, then this will reuse the same reference. It's the same with regular arrays, but those have a special path to fix this issue (which essentially removes the optimization and make it construct at runtime).
