### ISSUE TITLE
The "on_top" parameter of EditorSpatialGizmoPlugin.create_material has no effect

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#44077]
Godot 3.2.3
Windows 10 64 bits
OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

I'm making a plugin where I show a custom wireframe gizmo with `EditorSpatialGizmoPlugin`. I need it to be shown on top, so I set the `on_top` parameter to `true` in `create_material`. However it does not have any effect.

![image](https://user-images.githubusercontent.com/1311555/101091467-1bb07f00-35b0-11eb-9fe3-494e5b2dd401.png)

With wireframe mode turned on, you can see where the gizmo is supposed to be:
![image](https://user-images.githubusercontent.com/1311555/101091557-384cb700-35b0-11eb-82ea-4fe7aecce6ba.png)

MRP:
[GizmoOnTop.zip](https://github.com/godotengine/godot/files/5639077/GizmoOnTop.zip)
Check the plugin is enabled in ProjectSettings, open `main.tscn`, select the `MeshInstance`.

**Comment by stevenjt** [comment]
I hit this same bug when working on a custom gizmo and I've linked a PR with a fix that worked for me.

Since the MRP was for Godot 3.x I updated it to 4.3: 
[GizmoOnTop_4_3.zip](https://github.com/godotengine/godot/files/14857829/GizmoOnTop_4_3.zip)

With the linked PR the circle renders over the geometry when the gizmo is being used as expected:

![GizmoOnTop](https://github.com/godotengine/godot/assets/629887/9f4b2141-a727-4c28-8325-3d64b06406aa)
