### ISSUE TITLE
HTTP.Request Error when exporting from Windows to Android

### ISSUE THREAD

**Issue by cshiffl** [godotengine/godot#44097]
**Godot version:**

Godot Engine v3.2.3.stable.offical

**OS/device including version:**

GLES3
export template  3.2.3.stable

**Issue description:**

HTTP.request works on windows; however, it fails when I export the application to Android. No matter what url I try to request I get the following error - 

**ERROR**: getaddrinfo failed! Cannot resolve hostname.
At: drivers/unix/ip_unix.cpp:112:_resolve_hostname() - getaddrinfo failed! Cannot resolve hostname.

http.request("http://www.google.com", [], false, HTTPClient.METHOD_GET)   is the GDscript that I used successfully in Windows but failed on android export

**Steps to reproduce:**
1. Have http.request in your application on windows, i.e. http.request("http://www.google.com", [], false, HTTPClient.METHOD_GET)

2. Export application to android with debug

3. Debug will show getaddrinfo error

**Minimal reproduction project:**

[HTTPRequestError.zip](https://github.com/godotengine/godot/files/5645705/HTTPRequestError.zip)

**Comment by Calinou** [comment]
You forgot to enable the **Internet** permission in the Android export preset. You need to enable it so that the exported project can make HTTP requests.

**Comment by Calinou** [comment]
@m4gr3d I wonder if we could display an user-visible notification of some kind when attempting to make an HTTP request on Android without the Internet permission. (This would only be enabled in debug builds, of course.)

**Comment by m4gr3d** [comment]
@Calinou That would be difficult to get right and would introduce additional overhead since a trip to the Android/java layer would be needed to check on the internet permission every time a request is made.

Just at the usability level though, I can think of two options that may help:
- We could add an explicit `Use internet/network` in the Android `export` window. If this is checked then the `INTERNET` permission would be added during the export process.
- We should update the [HttpRequest tutorial](https://docs.godotengine.org/en/stable/tutorials/networking/http_request_class.html) and related documentation to note that on Android the `INTERNET` permission is required as well.

**Comment by sengkean** [comment]
> You forgot to enable the **Internet** permission in the Android export preset. You need to enable it so that the exported project can make HTTP requests.

I take almost one week to figure it out. Thank you! You saved my day bro!
