### ISSUE TITLE
NavigationRegion does not take into account collision shapes

### ISSUE THREAD

**Issue by IndieQuest** [godotengine/godot#44144]
**Godot version:**
v4.0.dev.custom_build.93b107ac9

**OS/device including version:**

Windows 10, Nvidia 1070

**Issue description:**
When baking navigation mesh in the editor only MeshInstances are treated as obstacles.
This is a problem when the user would want to separate the visualization of an object from the object collision, for example in order to prevent clipping with a tree, the user might want to set the collision of a tree to extend beyond the tree mesh so that the paths will always stay far from the tree(The agent radius does not solve this because this behavior might be desired only in some obstacles and not all of them).

Generally speaking, I don't think that the navigation region should use the *MeshInstance* itself for building the navigation mesh.
It would be better in my opinion to work with *StaticBody3D* and *Area3D* and I'll explain why.
Imagine the workflow of a level designer using the navigation mesh, he creates game objects and adds them as a child of the navigation region. If the part of the object that determines which part of the region is blocked there would be no separation between visualization and collision and there would be disambiguity when a single object is made from multiple meshes. 

**Steps to reproduce:**
Add the following objects as children of *NavigationRegion*:

1. MeshInstance
2. StaticBody3D with only a CollisionShape
3. Area3D with only a CollisionShape

Click the bake button and observe the navigation mesh.

**Minimal reproduction project:**
[Active.zip](https://github.com/godotengine/godot/files/5649115/Active.zip)

**Comment by Calinou** [comment]
cc @AndreaCatania

**Comment by smix8** [comment]
There are (filter) settings for both geometry type, children or groupnames but the inspector settings are part of the NavigationMesh Resource inside the NavigationRegion3D Node.

The default geometry parse filter for baking navmesh is set to Mesh Instances.

Geometry -> Parsed Geometry Type -> Mesh Instances / Static Colliders / Both
Geometry -> Source Geometry Mode -> Navmesh Children / Group with Children / Group Explicit (with String Name)

I think it would be more userfriendly if the settings would show up on the NavigationRegion3D node instead of the Navmesh Resource.

**Comment by IndieQuest** [comment]
Closing this, the Gemoetry selection is great.
