### ISSUE TITLE
'Lock Selection' only locks parent nodes

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#44157]
**Godot version:**

3.2.3.stable.mono.official

**OS/device including version:**

Win10

**Issue description:**

When selecting nodes & their children explicitly and clicking the Lock Selection button, only the top level nodes get actually locked; selected children are ignored:

![grafik](https://user-images.githubusercontent.com/8841352/101325289-cdc79f80-386b-11eb-8c9a-df76eb91f2b6.png)

**Steps to reproduce:**
Create a hierarchy of nodes, select every node, click the lock button and notice only the toplevel node getting locked

**Comment by akien-mga** [comment]
That's expected. You might want to lock e.g. "GameplayButtons" as the main container, but still move its children around.
If you want the lock to be applied to children (thus not being able to select them), use the Group button for that:
![Screenshot_20201207_095350](https://user-images.githubusercontent.com/4701338/101329793-2306af80-3872-11eb-8600-611468d02d6f.png)

**Comment by Flavelius** [comment]
Expected is the wrong word here. It's how it works currently. If i explicitly select all nodes and the button says 'Lock the selected object [...]', i expect it to lock the selected object and not require me to do an unmentioned additional step to achieve something only close to my intention.
Technically it's not even the same. Unselectable objects are still movable;
Although the linked usecase seems to not be functioning correctly too (or against intuition atleast), moving unlocked parents with locked children - still moves the children.

**Comment by akien-mga** [comment]
Locked doesn't mean locked in global position, but in local position (position in its parent's space). If you lock children, you can still move the parent and they will move together with the parent - that's the main use case for the lock feature: make sure that children won't move with regard to their parent. Think e.g. a "hat" sprite that has to always follow its parent "head" sprite.

**Comment by Flavelius** [comment]
That's a lot of implied functionality, but apart from that i'm not sure i can follow this, if the hat is nested inside the head it will implicitly follow the head, no need to lock it; in which case the lock doesn't provide any additional functionality.
But as editor tool, to move the parent to adjust it as implicit pivot while maintaining the child global positions, or to globally lock nodes, it would be a real helper.
If the lock button is this constraint in its actual effect and use, it is in my option a good candidate for improvement in either description or functionality.

**Comment by akien-mga** [comment]
> That's a lot of implied functionality, but apart from that i'm not sure i can follow this, if the hat is nested inside the head it will implicitly follow the head, no need to lock it; in which case the lock doesn't provide any additional functionality.

The lock is for the editor only, not used in game. In game the hat will definitely follow the head, but in the editor you can still move both independently, unless you lock them in place. Settings that affect game behavior are properties of the Node (in the Inspector), while the tools in the editor's main screen plugins (CanvasIten and Spatial) are providing editor-specific functionality.

The lock is a way to prevent you from changing the position of a Node by mistake (which can happen frequently when using the CanvasItem editor plugin or Spatial editor plugin otherwise, since Nodes can be dragged and dropped). It doesn't prevent you from changing the position from script or even from the Inspector - it's only for the editor plugin itself.

The description is "Lock the selected object in place (can't be moved)."
That seems fairly accurate to me, but I'm open to suggestions to make it clearer.

If you'd like different functionality added in the editor, this should be discussed in a Godot proposal: https://github.com/godotengine/godot-proposals

**Comment by Flavelius** [comment]
As you said preventing the accidental change of child positions is already possible by toggling the prevent-child-selection/group toggle (and the only case the lock actually prevents _too_)
I formulated a proposal:
https://github.com/godotengine/godot-proposals/issues/1949
