### ISSUE TITLE
Dictionary element are not available by index

### ISSUE THREAD

**Issue by TotCac** [godotengine/godot#44241]
**Godot version:**
custom d0f1c03b4

**OS/device including version:**
Windows 10

**Issue description:**
Cannot find existing key in Dictionary

**Steps to reproduce:**
Empty project
Create node
Add script 
`func _ready():
	var dict: Dictionary = {
		"elem1": 1,
		"elem2": 2,
	}
	print(dict)
	print(dict["elem1"])`

Output:
{elem1:1, elem2:2}

Debug:
Invalid get index 'elem1' (on base: 'Dictionary').

**Minimal reproduction project:**
[bugreport.zip](https://github.com/godotengine/godot/files/5668913/bugreport.zip)

**Comment by pouleyKetchoupp** [comment]
I can confirm `dict["elem1"]` or `dict.elem1` don't work in current master. It seems to be related to failed comparison between `String` and `StringName` types.

For info, as a workaround you can use the syntax `dict.get("elem1")` which still works.

**Comment by AndreaCatania** [comment]
I can confirm it too.

**Comment by lyuma** [comment]
hit this when looking up bone names in a dictionary. since I already made it, here is a reproduction project: run dictnames.tscn
[gdscriptbugs.zip](https://github.com/godotengine/godot/files/5754700/gdscriptbugs.zip)

had some trouble with .get() ... I mean, it avoids a crash yes but produces the wrong result. I just worked around by iterating through all keys and checking equality.

**Comment by pouleyKetchoupp** [comment]
@lyuma I've checked your project and dictionary accesses with `get()` seem to work ok.

The only clunky thing I had to do is to use `nodes.get(&"Camera3D")` because node names are `StringName` type, so `nodes.get("Camera3D")` would return null (that needs to be fixed too).

I'm not sure what the expected result from the scene is though. What wrong result did you get?

**Comment by lahouaridc** [comment]
so I have this example related to this issue (in GDScript):
```
	var space_state = get_world_3d().get_direct_space_state()
	
	if space_state != null:
		target_result = space_state.intersect_ray(from, to)
		var target_position = target_result.get("position")
		if target_position is Vector3:
			target_position = target_result[String("position")]
			target_position = target_result["position"] #<-- ERROR 
```
I am not certain why is string literal converted to StringName in here instead of String

**Comment by nemerle** [comment]
The problem is likely related to `Variant::hash_compare` that is used internally to compare keys in Dictionary class.
Currently, it's possible to do:
```cpp
Dictionary oh_lawd;
oh_lawd[StringName("chunky")] = "cat";
oh_lawd["chunky"] = "dog";
```
and end up with Dictionary of `size()==2` 

Current `Variant::hash_compare` assumes that `Variant::STRING` and `Variant::STRING_NAME` are not hash-comparable:
```cpp
bool Variant::hash_compare(const Variant &p_variant) const {
	if (type != p_variant.type) {
		return false;
	}
```
and it bails in the first conditional check.

**Comment by vonflyhighace2** [comment]
looks as if this bug has hit a brick wall. Dictionary's might need an overhaul similar to what vnen is doing with Arrays.

**Comment by paulhocker** [comment]
does anyone know if this is going to be fixed/addressed? I have to think that there are many people that are expecting Dictionaries to work as they did before.

**Comment by Calinou** [comment]
> does anyone know if this is going to be fixed/addressed? I have to think that there are many people that are expecting Dictionaries to work as they did before.

The `master` branch isn't meant to be used for production, so it may take a while for this to be fixed.
