### ISSUE TITLE
GDScript 2.0: Editor hangs forever while validating script

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44281]
**Godot version:**
Master 44a88244dee7e8996824aa29507e917b22ffccca

**OS/device including version:**
Windows 10

**Issue description:**
I don't have a very accurate repro, but sometimes the editor completely hangs while I'm in the script editor in a specific project, either when I save or when a script is validated while modifying it.

The debugger points to an infinite loop here:
https://github.com/godotengine/godot/blob/32c06dfc8dbf4c3e29232b7dbccc6a34ba257027/modules/gdscript/gdscript_editor.cpp#L1753-L1773

The first case in this switch does seem dangerous, because when the condition fails, it just breaks from the switch and checks the same type again.

In my case, `base_type` was `Node2D`, but the kind was `CLASS` rather than `NATIVE`, which might by the underlying issue.

**Steps to reproduce:**
- Open the MRP
- Edit script `tests/performance/test_perf_contacts.gd`
(it might have happened in another script as well, but I'm only sure about this one)
- Observe editor hang in some cases

**Minimal reproduction project:**
[physics_tests-4.0.zip](https://github.com/godotengine/godot/files/5676641/physics_tests-4.0.zip)

**Comment by Blackiris** [comment]
I have also encounter the bug in a more recent Godot 4.0 version, at commit a864a703ee27065795c6297aaeb72ed753d0f279.

Moving base_type = base_type.class_type->base_type; out of the "if"fixes the issue, but understanding the underlying issue to find the root cause if first necessary.

**Comment by Blackiris** [comment]
I have just made a very simple project that can reproduce this same bug.
[EditorInfiniteLoop.zip](https://github.com/godotengine/godot/files/6258508/EditorInfiniteLoop.zip)


Please have a look at the following files:

**parent.gd** (yes, only 1 line)
```
class_name ParentClass
```

**child.gd**
```
class_name ChildClass
extends ParentClass

func doReady(childNode):
	#Here, just write "childNode." to make the editor hangs in the infinite loop
	pass
```


When I type `childNode.` in the doReady method, an infinite loop happens in **_guess_identifier_type** method that is trying to guess the **childNode** type.

Let's look at the code again:
https://github.com/godotengine/godot/blob/32c06dfc8dbf4c3e29232b7dbccc6a34ba257027/modules/gdscript/gdscript_editor.cpp#L1750-L1773

To guess this childNode type, it will first gets its parent type (which is the ParentClass class)
`GDScriptParser::DataType base_type = p_context.current_class->base_type;` (l. 1752)
then it will check if the parent type has the same method doReady in order to guess childNode from it
`if (base_type.class_type->has_function(p_context.current_function->identifier->name)) {` (l. 1752)

Of course, its parent class ParentClass has no such method, so it should check its parent's parent instead.
It should be able to but the line `base_type = base_type.class_type->base_type;` (l. 1771) is inside the `if` that is never true .

**Solution to confirm**
If parent type does not have a similar method, it should check parent's parent type, so `base_type = base_type.class_type->base_type;`  should be outside the if.
