### ISSUE TITLE
Custom Company/GameName folder for OS.get_data_dir() instead of just "Godot" on Desktop?

### ISSUE THREAD

**Issue by alexandervrs** [godotengine/godot#4431]
Currently Godot is using a "Godot" master path in Appdata directory for user data.

However it'd be better if we could change the path so it would be either something like,

```
%appdata%/<CompanyName>/<GameName> or 
%appdata%/<GameName>
```

So instead of:
`C:/Users/Alex/AppData/Roaming/Godot/app_userdata/TestGame`

on Windows, it would be,

`C:/Users/Alex/AppData/Roaming/My Company/My Game/`

So you could organize your games' data under a Company or a custom branded directory etc.

I propose a field in the Project Settings that would allow for a path like `[ My Company/My Game  ]` that'd be always parented to the %appdata% directory.

Tested on Windows. Mac & Linux possibly have this issue as well. Especially Linux since I know files are most likely stored under`~/.config/`, and it probably needs to be `~/.config/<CompanyName>/<GameName>`. On Mac it should be in the Library/Application Support folder like `~/Library/Application Support/<CompanyName>/<GameName>`

_Using Godot 2.0.2_

**Comment by akien-mga** [comment]
By reading the code, this feature is already partly implemented:
- Unix: https://github.com/godotengine/godot/blob/1ea4b8e2dc61b39e78fb1691f738a03091ee2138/drivers/unix/os_unix.cpp#L465
- Windows: https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/platform/windows/os_windows.cpp#L2112

There should be `application/use_shared_user_dir` in the project settings that you can toggle off so that it uses:
- On Unix: ``$(HOME)/.<GameName>``
- On Windows: ``%appdata%/<GameName>``

**Comment by akien-mga** [comment]
If someone wants to make a PR to allow defining a custom path instead of ``<GameName>``, it should be relatively easy to do. It's also partly related to #3513, but the latter won't be fixed before 3.0 as it breaks compatibility for existing games.

**Comment by alexandervrs** [comment]
Adding that on Mac it should be under the Application Support folder:
`~/Library/Application Support/<GameName>`

**Comment by akien-mga** [comment]
Using `SYSTEM_DATA_PATH/Game Name` was already supported for a while, and I've added proper support for XDG paths in #12988, so this is fixed.

I'll open another issue for the only point that could still be addressed, i.e. allow to use something like `SYSTEM_DATA_PATH/Company Name/Game Name` instead of just `SYSTEM_DATA_PATH/Game Name`.
