### ISSUE TITLE
AnimationTreePlayer woes again :)

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4434]
Well, we have a funny documentation about AnimationTreePlayer function types.

Like track_get_key_value() which returns Variant and labelled
as void in the class docs. You can't really work with A-T-P until you read C++ code.
That is really a bad thing. Also animation filter handling is not documented while it is
very simple and useful concept. Also filter editor is a piece of crap.

Saying that, I had really good time digging all that. Thank you guys!

**Comment by akien-mga** [comment]
Well feel free to enhance the documentation, as you're one of the happy few who *can* read the C++ code. About the wrong return type for ``track_get_key_value()``, it's because the doctool can't extract this information itself from the function declaration, so you need to append ``:Variant`` in the ``bind_method`` call, e.g. in https://github.com/godotengine/godot/blob/a895e2e372c9df2a9972f38134ae0ea9c8bf45a8/scene/resources/animation.cpp#L1669:

```
ObjectTypeDB::bind_method(_MD("track_get_key_value:Variant","idx","key_idx"),&Animation::track_get_key_value);
```
Same thing for other custom classes like ``Resource`` or ``Shape2D`` for example.

**Comment by akien-mga** [comment]
And please try to make issues that focus on one thing and have a meaningful title. How are we supposed to fix "AnimationTreePlayer woes again :)"?
```
git rm -r godot/scene/animation/animation_tree_player.*
```
? :)

**Comment by slapin** [comment]
As a variant. Well, consider vague-named topic as discussion topics. I
can't think after a few sleepless nights,
and really you can't force me.

Also I really have no idea.

And. sleepless nights are not about Godot, they are about $$$ work :(

Also I think magic tags like animation-tree-player, discussion, wtf should
do the trick.

And I'm happy to hear from you today! Really!

**Comment by akien-mga** [comment]
Yeah, it's just that with almost 1000 open issues, I'm trying to keep things under control so that we can actually fix what needs to be. But a discussion issue here and there don't hurt much either, if we remember to fork them to proper issues once the discussed bits have been well defined. :)

**Comment by akien-mga** [comment]
Note to self: the bit about ``:Variant`` should go in the documentation page about writing documentation :D

**Comment by slapin** [comment]
So please clarify in a few lines what should I do for proper code lines to
appear in docs? I could not find
any guides (not that I'm much successful with anything today)

**Comment by akien-mga** [comment]
So basically for the erroneous return type (``void`` instead of ``Variant``), you should do what I mentioned above, i.e. modify the relevant ``bind_method`` calls to append ``:Variant`` to the method stringname. It's the same for arguments btw, if an argument has to be ``Variant`` or ``Animation``, you can specify it the same way (e.g. ``ObjectTypeDB::bind_method(_MD("track_foo_bar:Variant","anim:Animation"),&Animation::track_foo_bar);``

Once you've fixed the .cpp, you can build Godot and regenerate the documentation XML with:
``bin/godot.<your arch, platform and stuff> -doctool doc/base/classes.xml``
``git diff`` should show that the return type is now correct (together with some other changes if the documentation template was out of sync with the code base).

Then to fill the method descriptions, you have to edit ``doc/base/classes.xml`` and fill in the blanks. Once this is done and PR'ed, the online docs can be updated in the godot-docs repo (using ``doc/tools/makerst.py`` for the conversion from XML to reST).

**Comment by akien-mga** [comment]
See also http://docs.godotengine.org/en/latest/contributing/updating_the_class_reference.html for more details. It's the page I'll have to enhance to add the bits about ``:Variant`` and similar things.

**Comment by neikeq** [comment]
<details> 
  <summary>Who needs correct types any way :man_shrugging:</summary>
   Just kidding, it's fixed.
</details>

**Comment by akien-mga** [comment]
(translation: type inference for the docs is now functional, no need for hints)
