### ISSUE TITLE
Calling property_list_changed_notify() while dragging slider stops drag action

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#44354]
**Godot version:**
3.2.3 stable

**OS/device including version:**
Macbook Pro 
macOS Mojave

**Issue description:**
I have a tool script where exported variable B sometimes needs to also be set when exported variable A is set. Now if I change B in the setter for A, it does change B but B will not update in the inspector. So I tried calling property_list_changed_notify() in the setter, but this doesn't work out because now when I try to drag the slider for A, the action ends abruptly. 

**Steps to reproduce:**
Add the following script to a Node2D:

```
extends Node2D
tool


export (float, 0, 1) var variable = 0 setget _on_variable_set
export (float, 0, 1) var constrained_variable = 0


func _on_variable_set(value):
	variable = value
	constrained_variable = value
	property_list_changed_notify()
```
And try dragging the slider for "variable".

**Minimal reproduction project:**
[SliderUpdatePropertyList.zip](https://github.com/godotengine/godot/files/5685692/SliderUpdatePropertyList.zip)

**Comment by HaSa1002** [comment]
I did some debugging and got some results which are not encouraging.
Good thing is, you won't have this issue in 4.0.

`property_list_change_notify` leads to a complete rebuild of the inspector by calling `update_tree` in `editor_inspector.cpp` indirectly. `_clear` frees then all the plugins. Later all plugins are reinstantiated and the previously selected plugin is reselected. Because of the `EditorSpinSlider`s logic to drag values there is no easy way to reenable it.
We can fix one issue there to reset the mouse position correctly (I will make a PR once I tested some other stuff). Another idea I just got while writing, is to try a different update approach. Rubber duck programming at its best :)

In the meantime you can use this ugly work-around:
```swift
tool
extends Node2D


export (float, 0, 1) var variable = 0 setget _on_variable_set
export (float, 0, 1) var constrained_variable = 0

var _editor_run = 0

func _on_variable_set(value):
	variable = value
	constrained_variable = value
	_editor_changed()


func _editor_changed():
	_editor_run += 1
	var _run = _editor_run
	yield(get_tree().create_timer(0.25), "timeout")
	if _run == _editor_run:
		property_list_changed_notify()
		_editor_run = 0
```
Instead of directly calling `property_list_changed_notify` we defer the call 0.25 seconds and only call `property_list_changed_notify` if the last 0.25 seconds no other edit was made. That is not excatly nice, but it works better.

I suppose that this issue is not specific to `EditorSpinSlider`, but to every dragging control.

**Comment by sairam4123** [comment]
I can confirm this in 3.3.1

**Comment by HaSa1002** [comment]
> I can confirm this in 3.3.1

yes... and in 3.x

**Comment by Jonathan-Jay** [comment]
This issue seems to have reintroduced itself in 4.2 or something, because calling `notify_property_list_changed()` in a setter on a export_range() variable stops the drag action once again.

**Comment by BoopEnthusiast** [comment]
I'm experiencing this in 4.4.1 still with an `@export` on a `Vector3`'s values.

**Comment by BaconEggsRL** [comment]
Same issue in 4.6.stable

**Comment by dcarlile42** [comment]
I'm experiencing the same issue in 4.7. Create a script with these contents, attach it to a _.tres_ file, and the slider doesn't function unless you comment out the _notify_property_list_ call.

    @tool

    @export_range(0, 10) var test : float:
      get:
        return test

      set(value):
        test = value
        notify_property_list_changed()
