### ISSUE TITLE
'Corrupted header in binary project.binary (not ECFG)' with exported PCK over 2.1 GB (32-bit signed int) 

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot#44363]
**Godot version:**
3.2.3

**OS/device including version:**
Windows

**Issue description:**
When a PCK file is over 2.1gb godot will not run and throws this error:
```
ERROR: Corrupted header in binary project.binary (not ECFG).
   At: core/project_settings.cpp:522
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).
```

This was raised back in the 3.1 days as https://github.com/godotengine/godot/issues/27168 and a PR was created. 

Due to the large number of changes the PR was moved to 4.x as part of https://github.com/godotengine/godot/pull/27247 (proposal https://github.com/godotengine/godot-proposals/issues/400) and the original 3.1 issue closed. However, due to age of the PR it was never merged into 4.0 as far as I can tell.

I think this means the problem is not fixed and also does not have an issue associated with it. The exported game runs on Linux but not Windows.

Now I have a PCK over 2.1gb and am searching for a solution or a workaround. Is it possible to merge that PR, even if it's for 4.0? Or is there some way to break the export up into multiple PCK files? Thanks

**Steps to reproduce:**
Create PCK file over 2.1gb

**Comment by Calinou** [comment]
> Or is there some way to break the export up into multiple PCK files? Thanks

Yes, see [this page](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_pcks.html) in the documentation.

**Comment by Patashu** [comment]
Adding a comment to this because this is the top google search result for this error message and there is a totally unrelated reason why it can happen!

How it happened: Apparently if you upload HTML5 builds to itch.io in multiple succession, and some people played on the intermediate build, their browser will cache some but not all of the HTML5 files, allowing them to attempt to play the game in an inconsistent state.

The solution: tell them to Ctrl+F5 lmao. No idea if there's an automateable solution besides 'don't do that'
