### ISSUE TITLE
Transpose argument of draw_texture_rect or draw_texture_rect_region does not work anymore

### ISSUE THREAD

**Issue by groud** [godotengine/godot#44365]
**Godot version:**
Master branch

**OS/device including version:** 
Linux, vulkan

**Issue description:** 
Setting transpose to true as an argument of draw_texture_rect_region does not work, the texture is not rendered as transposed (the texture should be rendered as mirrored by its diagonal axis).

It is needed to render rotated textures (and thus, tiles). Related issue: https://github.com/godotengine/godot/issues/31149

**Steps to reproduce:**
Simply try to draw a texture with draw_texture_rect or draw_texture_rect_region.

**Minimal reproduction project:**
Ask if needed. :)

**Comment by halgriffiths** [comment]
It looks to me like the issue is here:
https://github.com/godotengine/godot/blob/e44a2f16805b09a9a858ba5e8ebec7e598feb4d8/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L530-L532

While flipping the destination rect might have worked on GLES3, it doesn't seem to do anything at all for Vulkan. I have tried flipping the dest rect in all possible combinations and could see precisely zero difference to the on-screen output.

I am well out of my depth dealing with APIs this low-level though, so I don't know what the "correct" way to transpose the render for Vulkan is.

**Comment by halgriffiths** [comment]
OK, think I have it figured it out, will put up a PR on my lunch break.
