### ISSUE TITLE
[3.2.4 beta 4] Zooming in/out in the 3D Editor has limits that don't exist for previous versions

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#44488]
Godot version:
3.2.4 beta 4

OS/device including version:
Windows 10 Pro 2004

Issue description:
Cannot zoom in below 0.2 u and zoom out above 125 u in the 3D Editor.

Steps to reproduce:
Create a Spatial node, then try to zoom in below 0.2 u and zoom out above 125 u.

Minimal reproduction project:
Any project will do.

**Comment by akien-mga** [comment]
That was done on purpose: #39743. CC @aaronfranke @Calinou 

Do you have a valid use case for going beyond 0.2 and 125?

**Comment by floppyhammer** [comment]
I suppose it is pretty normal to go beyond these limits when developing games with big spatial scale variation. For example, space games.

**Comment by aaronfranke** [comment]
This is intentional. If you want to zoom further, you should change the camera's clipping planes:

![Screenshot from 2020-12-18 03-47-26](https://user-images.githubusercontent.com/1646875/102594192-dc238000-40e3-11eb-8171-87cba1afd831.png)

There's not much use of zooming to a level in which the thing you're looking at is invisible.

**Comment by floppyhammer** [comment]
Now I feel this change kind of makes sense for maintaining some consistency between zoom limits and the actual visible range.

**Comment by akien-mga** [comment]
Great, closing then.
