### ISSUE TITLE
`Texture2D.get_data()` does not always return the correct `Image`

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#44529]
**Godot version:**
3.2, 4.0-dev

**OS/device including version:**
All

**Issue description:**
Not all classes inherited from `Texture2D` return the correct `Image`, which violates OOP. For example `AtlasTexture.get_data()` always returns `null`. 

**Steps to reproduce:**
—

**Minimal reproduction project:**
I created a test project in 3.2 because 4.0 works very poorly on my hardware.

[texture-types.zip](https://github.com/godotengine/godot/files/5720003/texture-types.zip)

(The method works correctly only for the `StreamTexture`, `ImageTexture`, and `AnimatedTexture` classes.)

![](https://user-images.githubusercontent.com/47700418/102697142-87e3e180-4244-11eb-8e9d-31eabec7527e.png)

**Comment by UltraWelfare** [comment]
I've tried experimenting with it (on 3.2) and I found out that the `Texture`'s `get_data()` function isn't implemented so that's why you get a null.
I don't have experience with the code architecture and how things work but as far as I understand the bug, I'll try to give an example for `AtlasTexture`.

Because `AtlasTexture` doesn't implement the get_data function you are getting routed to the base texture function located here. 
https://github.com/godotengine/godot/blob/a4d25a115ed65b05bb6e2b575c0d9ddef8a7a123/scene/resources/texture.h#L82

Looking at the implementation of this function it seems like it returns a Ref which might somehow turns to 'null' once it reaches the script. 
Anyways, I've tried adding the `get_data` function to the `AtlasTexture` class and then using this line of code:
```c++
return VisualServer::get_singleton()->texture_get_data(get_rid());
```
to obtain the `Ref<Image>`, which I took 'inspiration' from `ImageTexture::get_data()`
https://github.com/godotengine/godot/blob/a4d25a115ed65b05bb6e2b575c0d9ddef8a7a123/scene/resources/texture.cpp#L267-L274

And this is result.
![image](https://user-images.githubusercontent.com/6756759/102699703-879d1380-424f-11eb-982b-6aa8f4fc3648.png)
I'm not sure if this is a correct behaviour.
It displays exactly the 'data' which is the .png texture and not the Atlas'ed texture which seems correct to me but I'm not entirely sure.

I suppose all the other classes suffer from the same issue of an undefined `get_data()` function.

**Comment by dalexeev** [comment]
> I'm not sure if this is correct behavior though.

@UltraWelfare Yes, the correct behavior would be something like:

```cpp
return atlas->get_data()->get_rect(region);
```

> I suppose all the other classes suffer from the same issue of an undefined `get_data()` function.

Exactly.

**Comment by UltraWelfare** [comment]
> > I'm not sure if this is correct behavior though.
> 
> @UltraWelfare Yes, the correct behavior would be something like:
> 
> ```c++
> return atlas->get_data()->get_rect(region);
> ```
> 
> > I suppose all the other classes suffer from the same issue of an undefined `get_data()` function.
> 
> Exactly.

My particular question is about the wording of the function.
Since it is called `get_data()` isn't it correct that it returns the png image (Which is indeed the data of the texture)?

**Comment by dalexeev** [comment]
> My particular question is about the wording of the function.
> Since it is called `get_data()` isn't it correct that it returns the png image (Which is indeed the data of the texture)?

Docs:
```
Image get_data() const

Returns an Image that is a copy of data from this Texture. Images can be accessed and manipulated directly.
```

Nothing really can be said from this description.

However, it seems to me that we need to return a part of the texture, and not the entire atlas. To get the whole atlas there is another property (`AtlasTexture.atlas`).

**Comment by UltraWelfare** [comment]
Yeah because of that `atlas` property, I think it makes sense to return only the part of the texture that is relevant.

**Comment by UltraWelfare** [comment]
I also assume that you've already started working on this, so let me know if you need any help!

**Comment by dalexeev** [comment]
> I also assume that you've already started working on this, so let me know if you need any help!

I dug around in the source code a bit but haven't started working yet. I saw that this was affecting several classes, so I decided to take my time. If anyone else has a desire to fix this, I will only be glad.

**Comment by UltraWelfare** [comment]
I tried fixing `NoiseTexture` but there are strange things happening.
The function is implemented but it is not quite correct.
https://github.com/godotengine/godot/blob/e9d12f9e4ea30a6c3f2cf179f104a153d668c2a3/modules/opensimplex/noise_texture.cpp#L271-L273

The `data` that it is referring to seems to be empty (references to 0x0). I also found that there is an `RID texture` so I quickly tried using the visual server to get the texture data from it but this texture was also empty...

My next speculation was the `Ref<OpenSimplexNoise> noise` property.
So I quickly threw this inside `get_data()`
```c++
if (seamless) {
    return this->noise->get_image(size.x, size.y);
} else {
    return this->noise->get_seamless_image(size.x);
}
```
and it seems to work.. I'm just not quite sure what are the purposes of the properties
- `RID texture`
- `Ref<Image> data`
and if we need to give them any attention on `get_data()`. Are they always empty? Can they be different from the image that the `noise` property returns?
