### ISSUE TITLE
Support multi uv channels in gltf2.

### ISSUE THREAD

**Issue by fire** [godotengine/godot#44552]
**Godot version:**
c2e0c6cc2282669017707596c810cde996414131 fork. should test on master.

**OS/device including version:**
win10. Nvidia. Vulkan

**Issue description:**
Fails on multi uv test case.

https://github.com/godotengine/godot/pull/44319 supports four custom uv channels.

See https://github.com/godotengine/godot-proposals/issues/2192

**Steps to reproduce:**
Load MultiUVTest

**Minimal reproduction project:**

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MultiUVTest

![Multiuvs](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/MultiUVTest/screenshot/screenshot.jpg)

![image](https://user-images.githubusercontent.com/32321/102720283-484ee100-42a8-11eb-9064-b5d5f382eedd.png)

**Comment by Zylann** [comment]
> #44319 supports four custom uv channels.

I've been searching quickly for the place it does that, but so far haven't found it. This PR reworked SurfaceTool, yet I've seen `add_triangle_fan` still only expects 2 sets of UVs.

**Comment by fire** [comment]
We need to modify surface tool to use the custom slots.

**Comment by fire** [comment]
My plan is to look at https://github.com/godotengine/godot/pull/49932 to implement https://github.com/godotengine/godot-proposals/issues/2266

**Comment by Lexpartizan** [comment]
I understand that using many UV channels can lead to big changes in the code. And in the logic of working with the lightmapper. But it is better to do such things that break backward compatibility now, before the release of 4.0. Because then it will be much more difficult to accept such changes. Nevertheless, these changes are necessary at least in order to use the texture array, which will significantly increase performance and reduce the required number of textures. In addition, I would also like to see several Vertex_Color channels, which would allow us to use blending materials without overhead and add decals for splitting tiles, which are very noticeable in the texture array.
