### ISSUE TITLE
How can I split animation in imported FBX file into several clips? "Clip amount" setting doesn't seem to do anything.

### ISSUE THREAD

**Issue by lumenwrites** [godotengine/godot#44561]
Hi! How can I split the imported animation into several clips?

I'm trying to import an animated character (FBX file). It has several animations (walk, attack, etc) in it's timeline, one after another. I need to split these animations into separate animation clips so that I could use them in my game.

Import tab has the "Clip Amount" and Start/End frames options, which seem like they're meant to do exactly what I need. I create several clips, give them names, set the frame ranges, click reimport, but the animation player in the scene still only has the "Main" animation, not split up into clips.

Can you help me out? What am I doing wrong?

Here's the [FBX file](https://www.dropbox.com/s/5zklnkgtg582foa/zombie-animated.fbx?dl=0) I'm using.

Import settings I'm trying to use:
<img width="268" alt="import-settings" src="https://user-images.githubusercontent.com/4761235/102738444-0f634a80-4342-11eb-9fcd-524825fd95b4.png">

**Comment by lumenwrites** [comment]
Tried converting FBX to DAE using [this converter](https://anyconv.com/fbx-to-dae-converter/), now the clips appear in the timeline, but the animation is completely broken (so are materials).

Tried converting FBX to DAE using [this converter](https://3d-convert.com/en/convert/fbx-to-dae.html), now animation works, but clips are back to not working.

(so it's not FBX-specific issue).

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
