### ISSUE TITLE
File order in FileSystem is not the same as file order in Directory

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#44602]
**Godot version:**

3.2.3

**OS/device including version:**

Windows 10

**Issue description:**

I was naming a bunch of files "0_file_name", "1_file_name"... and so on. In the FileSystem window, 10 comes after 9. Then I created a Directory to go through all of the files in a directory. When the directory is going through files, 10 comes after 0.

(In the meantime, how should I name files to ensure that the directory goes through them in the correct order?)

**Steps to reproduce:**
_

**Minimal reproduction project:**

_

**Comment by akien-mga** [comment]
Pad the numbers with zeros to have the same columns: 01, 02, 10.

While it might be surprising, the behavior here is correct IMO. OSes do letter-by-letter sorting and not natural comparison, so that's what you should get in low level APIs like Dictionary.
The Filesystem dock uses natural sorting as it's more user-friendly to humans.

**Comment by ShatReal** [comment]
Ok, thanks! :)
