### ISSUE TITLE
Creating a new mesh resource inside a `MeshInstance` wipes out materials slots

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#44714]
**Godot version:**
Godot 3.2.4 dev 279f4fbb5f83c2df6e8499799a2aa0c14f85aa2d

**OS/device including version:**
Windows 10 64 bits

**Issue description:**
I created a new mesh resource in a MeshInstance that already had a material slot setup, and the material was removed. I expected the material to stay. I have to re-setup the material again, which is annoying.

The way I understand those slots, they are per-MeshInstance, not directly inside the mesh? (since they appear on the node, and it wont show up if I edit the mesh resource) Either way, in the case cited above, I would not expect them to be wiped.

**Steps to reproduce:**
1) Create a MeshInstance
2) Assign a new CubeMesh
3) In this material slot, create a new material
![image](https://user-images.githubusercontent.com/1311555/103161308-a8c5ad00-47d7-11eb-90ac-3158721d4be2.png)
4) Assign a new SphereMesh in place of the previous mesh
5) Observe the material previously setup is gone

**Minimal reproduction project:**
None

**Comment by mrjustaguy** [comment]
I can Confirm, went all the way back to 3.1.1 stable (didn't check further down the line)

Seems like it happens because the Material is a Property of the Mesh or Just takes the Mesh Surface count (which could mean that it is for like a moment 0 surfaces instead of 1 thus clearing the 0th surface material before creating a new one), as can be clearly observed when there is no mesh as there is no Material option available in that case...

That Material Option (which overrides the material set by the mesh itself) should be Considered a property of the MeshInstance that by Default has the 0th surface available (which it doesn't by default as empty mesh doesn't show it), and the option to add more of those surfaces to override (which would override the corresponding surfaces if the mesh has said surfaces)
