### ISSUE TITLE
A nested class cannot access function outside its scope

### ISSUE THREAD

**Issue by buckle2000** [godotengine/godot#4472]
...With or without `static` keyword.
well I think it should.

**Comment by buckle2000** [comment]
```
extends Object

func calc_offset(dt, target):
	var dx = 0.0
	var dy = 0.0
	if true: # use keyboard
		if Input.is_key_pressed(KEY_LEFT):
			dx-=1
		if Input.is_key_pressed(KEY_RIGHT):
			dx+=1
		if Input.is_key_pressed(KEY_UP):
			dy-=1
		if Input.is_key_pressed(KEY_DOWN):
			dy+=1
	return Vector2(dx, dy)

class FourWayCtrl:
	func update(dt, target):
		var offset = calc_offset(dt, target)
		target.apply_impulse(Vector2(0,0), Vector2(offset.x*target.max_acc,offset.y*target.max_acc))
```

**Comment by buckle2000** [comment]
Also, the completion shows `calc_offset` inside `FourWayCtrl`. It is another question if I am not supposed to do that.

**Comment by slapin** [comment]
This is normal, as Godot do not implement closures.
You will need to provide appropriate references.

**Comment by slapin** [comment]
If you want closures to be added, just add proper request. And send PR fixing it.

**Comment by vnen** [comment]
Inner class is not a subclass, so it's expected that it doesn't have access to the outer class' methods. I would propose to add a way to reference the outer class, so you can explicitly make use of inheritance and access static methods.

**Comment by akien-mga** [comment]
I confirm that it's a bug, actually the inner class has access to its outer class' functions if it's place *at the end* of the file. If place at the beginning, it can only see the outer constants, but all the rest will be seen as undefined.

**Comment by akien-mga** [comment]
Nevermind, looks like I misinterpreted the situation in my script, even when placed at the end of the file the inner class does not have access to its outer class' functions and member variables, only constants.
I do believe this would be an interesting feature though, as various languages do support it (e.g. Java). As @vnen mentions, it could be something explicit and not implicit like in Java.

**Comment by bojidar-bg** [comment]
In any case, static functions should be accessible by all inner classes, since it is currently impossible to do it without a recursive load or preload...

**Comment by reduz** [comment]
@bojidar-bg you can give it a try if you want, meanwhile I will kick to 3.1

**Comment by amirea** [comment]
I suspect this is related with a few other problematic cases:
1. Class inter-relation (depends on order)
```
class A1:
    func B1():
        return A2.new()

class A2:
    func B2():
        return A1.new()
```
2. Recursive components
```
class A:
    var a = A.new()
```

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by FrederickDesimpel** [comment]
Will this work in Godot 4 trough use of the new callable type ?

**Comment by vnen** [comment]
Callable doesn't help with this. As I mention, we either need some way to reference the outer class or automatically resolve the static method in the compiler (like it does with constants).

But yes, I intend to work on this for 4.0.

**Comment by paulmiller** [comment]
As a work-around, you can call an outer function `foo()` by `get_script().foo()`.

**Comment by vnen** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
