### ISSUE TITLE
An option to batch-delete all references to various asset files if needed.

### ISSUE THREAD

**Issue by Ace-Dragon** [godotengine/godot#4474]
The reason for this request is that sometimes when exporting, you may end up seeing new .tex files created everywhere. The result of this is a much higher file size for the full project and a lot of duplication. I know for some cases, you may want to just have the material created with the surface itself, but considering that I always use the override material, the surface material just gets in the way and works to clutter my project file system.

The solution for that (and any other case where you want to do a complete deletion of an asset quickly and without breaking everything), would be an option to auto-delete all references to the asset in question when you get the warning prompt that comes with the _delete_ option.

For instance, in deleting an excess .tex file for instance, it would delete the references to it within all materials that use it while not deleting the materials themselves (so a diffuse texture slot for example would be reset to _null_). The project will still work when playing it and opening scene files, but the extra textures and any other old cruft can then just be cleaned out quickly and easily (with no visible impact in this case at least since said materials were overridden anyway and those materials use .tex files in a folder specifically created for them).

Comments?

**Comment by bojidar-bg** [comment]
Master (and 2.1 I think) now allow you to get a list of all files referencing a given file (though it doesn't count in GDScripts :smile: ). Thus, it is possible to do it manually to some extent...

**Comment by Anutrix** [comment]
Any updates?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
