### ISSUE TITLE
AnimationTreePlayer: oneshot node doesn't work correctly after blend2 node

### ISSUE THREAD

**Issue by slapin** [godotengine/godot#4478]
**Issue description** (what happened, and what was expected):
For skeletal animation (transform track).
If we set oneshot node directly into animations, it works as intended, i.e blending one animation into
the other depending on filters. If we set oneshot node main pin into blend2 node,
it never use that animation as basis, it uses default bone pose instead, which looks like zeero channel,
so animation is basically lost for time of oneshot run.

**Steps to reproduce:**
Just setup AnimationTreePlayer, you will bump into this fast enough.
Do transition-blend2-onshot chain, this one was properly tested and always reproduce the bug.
Use transform tracks, or, better, skeletal animation to see the result. I don't care about value tracks
and 2D stuff for this one.

@JoshuaGrams looks like this one is for you :)

**Comment by JoshuaGrams** [comment]
As I said, I'm cutting back on Godot development. The core developers consider it [a waste of their time to document](http://godotengine.org/article/fill-blank-class-reference) and fix the existing broken core features rather than working on shiny new broken features. I'm reluctant to support a project whose developers have their priorities so totally backwards, because it means that it's always going to be a poor-quality project unless they somehow get enough contributors to keep up with fixing their broken mess. And it's difficult to attract good-quality contributors when they know that you're just going to keep creating more broken mess and don't care about the quality of your code base.

So...if you want to make a sample project, I'll take a look at it and see if it's a quick fix. But if it's not worth enough for you to spend a little bit of time demonstrating the problem, it's definitely not worth my time to fix it.

Also, are filters involved? If you have more than one oneshot or blend2 in line with each other then the one closest to the leaf nodes (Animation node) just replaces all the others. And that is broken enough that I'm not going to fix it.

**Comment by akien-mga** [comment]
> As I said, I'm cutting back on Godot development. The core developers consider it a waste of their time to document and fix the existing broken core features rather than working on shiny new broken features.

Wow wow, take it easy. I was the one writing this article, and I said that to enhance the fact that writing the class reference is something that does not require a deep knowledge of the engine. It's just a matter of opening the XML file, find where ``<description>`` is empty, if need be open the C++ file and check what the method does.

I never said that the core developers consider it a "waste of their time to [...] FIX the existing BROKEN core features". The article you quoted is SOLELY about the class reference, which is not about broken core features and bugs reports but about the existing API and what it's supposed to do (and yeah, sometimes this API has bugs, which are then reported on GitHub and hopefully fixed - but this has nothing to do with the documentation job this article is about).

So if you don't like the way this project is run, that's your call, but don't quote my article about enhancing the documentation as a justification.

**Comment by akien-mga** [comment]
Please keep in mind that Godot is an open source project 100% developed by people on their free time. And the code base is HUGE. Yeah, parts of it are buggy and others are rusty. Which is why it is *mandatory* to grow the community of developers so that we can all maintain it together. You can't just expect @reduz and @punto- alone to do all the maintenance work, there's just too much to do. But again, in my wannabe inspirational blog article about the documentation, I never mentioned anything about bug fixing, that's pure interpretation on your side.

**Comment by reduz** [comment]
@slapin @JoshuaGrams No further work is done in the 3D Area of Godot because it will be completely rewritten after 2.1 is out in July. This also includes AnimationTreePlayer, which will be modernized to be more root motion friendly (the technique modern engines use). Godot 3D side is really old (almost 10 years) and was written using the common techniques of the time. Most of these changed and a rewrite is due.

As no intent on preserving perfect backwards or forward compatibility in that area will be made, simply because we don't have the resources to maintain parallel implementations, we keep discouraging it's use or maintenance for the time being.

The reason this was not done before is because the main source of complaint and problems for users when Godot came out were usability related and missing features of the 2D engine (which is what most users work with at the time), so these were all fixed the past year. Now the main problematic areas for most users are shifting to be the 3D side of things and script performance. We will be shifting focus that as soon as possible.

Regarding @slapin I told you this probably a dozen times already, but no more work will be done on this stuff, so all these issues being reported, while helpful in case someone wants to fix them, will go away when 3.0 is out.

**Comment by slapin** [comment]
Alas I understand @JoshuaGrams <https://github.com/JoshuaGrams> position
quite well, as experience shows, the rewrite is usually not a good option
for any project.
- The best way to do changes is to do them step by step from A to B, with
every step an evolution, having rewrite done at point B.
- The absence of plan of changes looks like the rewrite is not being
planned so it will either be postponed again or failed.
- The probability for @reduz alone to do this rewrite properly is about 0,
but to do it collegually the step by step plan
should be published and discussed and this is not being done.
- The setting of any particular date or "after xxx release" looks just as a
way to postpone the development because of lack of resources,
but not having a passion to share the responsibility.
All of the above makes me very pessimistic.
I seen how things are done, and they never done this way. So I will say
again, that 3.0 is a lie.
Of course I will be really happy if proven wrong.

**Comment by reduz** [comment]
kicking to 3.1, will do serious rewrite to AnimationTreePlayer

**Comment by reduz** [comment]
> kicking to 3.1, will do serious rewrite to AnimationTreePlayer

And almost exactly one year later, this is done.. so closing it.

**Comment by slapin** [comment]
Yes, thanks! New AnimationTree is fascinating!
