### ISSUE TITLE
GDScript: indexing PackedFloat32Array fails

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#44812]
**Godot version:**
4.0 edccc0b

**OS/device including version:**
Microsoft Windows [Version 10.0.19041.685]

**Issue description:**
I created a packed array with multiple elements. indexing any value such as 0 causes a gdscript exception:
```
Invalid get index '0' (on base: 'PackedFloat32Array').
```
**Steps to reproduce:**
1. open attached project.
2. open packedarraytest.tscn
3. play scene (2nd button from the right on top bar)
4. it will get an error

workaround: use for loop and break after index iterations.
**Minimal reproduction project:**
[gdscriptbugs.zip](https://github.com/godotengine/godot/files/5754700/gdscriptbugs.zip)

**Comment by supagu** [comment]
I am even getting an error just doing this in gdscript:

> var p: PackedFloat32Array = PackedFloat32Array.new();

With error: "Builtin type cannot be used as a name on its own."

**Comment by Calinou** [comment]
The correct syntax is:

```gdscript
var p: PackedFloat32Array = PackedFloat32Array.new();
```

Using `new()` on built-in types isn't supported.

**Comment by Blackiris** [comment]
It looks like it is because `REGISTER_INDEXED_MEMBER(PackedFloat32Array);` is missing in the following code:

https://github.com/godotengine/godot/blob/7d70cdc6ccbea0cca2619a8790e097724e8e5f18/core/variant/variant_setget.cpp#L1034-L1056


There is one for PackedInt32Array but not PackedFloat32Array.
Adding it fix the issue for me.
