### ISSUE TITLE
Controls layout is reset when opening a previous project in 4.0

### ISSUE THREAD

**Issue by pouleyKetchoupp** [godotengine/godot#44820]
**Godot version:**
Master f62f64193a5ba54a5e0e74547d0cb0fb54b11258

**OS/device including version:**
Windows 10

**Issue description:**
Following #44605, any scene with `Control` nodes made with a previous version will see all the control positions set to the default anchor position due to the `margin_` properties renamed to `offset_`.

This issue probably needs to be addressed before 4.0 alpha comes out. It will happen with no warning, so it's difficult to spot and fix, except by preemptively search all the scene files to replace all `margin_` properties with `offset_`.

It requires support for properties backward compatibility, either with a generic system, or by adding specific cases to `_set` method in `Control`.

**Steps to reproduce:**
- Open a 3.2 project that contains controls with margins set
- Observe all controls moved to their default anchor position

**Minimal reproduction project:**
[control-margins.zip](https://github.com/godotengine/godot/files/5755266/control-margins.zip)
| 3.2 | 4.0 |
| --- | --- |
| <img src=https://user-images.githubusercontent.com/1075032/103373457-40562480-4a92-11eb-9f5b-3109bfb50496.png width=400/> | <img src=https://user-images.githubusercontent.com/1075032/103373520-6ed3ff80-4a92-11eb-9af8-5751402a9e47.png width=400/> |

**Comment by KoBeWi** [comment]
I think it's better to rely on auto-converters than add a boilerplate code that we'll need to remove.

**Comment by duchainer** [comment]
Happened when working on porting https://github.com/tavurth/godot-radial-menu to Godot4

**Comment by akien-mga** [comment]
> I think it's better to rely on auto-converters than add a boilerplate code that we'll need to remove.

I think the scope of changes that have to be made is big enough that adding the relevant checks in `_set` / `_get` would be worth it. Conversion tools will help for big projects but likely won't be used for every single scene you may find in a plugin on the asset library. And the checks we'd need to add are fairly simple (`rect_position` -> `position`, etc.).

**Comment by KoBeWi** [comment]
IMO we either do it for all properties or none. When you open a random GUI scene, Label autowrap and alignment, all theme overrides, TextureButtons, all fonts, will all break. Even if you keep the layout, you lose lots of information. Some of it needs to be converted manually, e.g. fonts that now don't have size, so you need to keep track of what font is used where and add proper font sizes to your theme. Adding some built-in conversions helps migrating scenes, but also gives a fake feeling of "safety".

That said, we have some conversions already, like for node and resource types. They are indeed helpful, but you wouldn't be even able to open the scenes otherwise, so this is justified.

> won't be used for every single scene you may find in a plugin on the asset library

None of the editor plugins currently in the asset library will work in 4.0, for the simple fact that `tool` was changed to `@tool` (and that's the most basic script incompatibility).

> rect_position -> position

This is actually only relevant to scripts, as these properties don't exist in scene.

**Comment by KoBeWi** [comment]
Opened a proposal that would cover this in a better way:
https://github.com/godotengine/godot-proposals/issues/4801

**Comment by akien-mga** [comment]
Agreed, after seeing the extent of changes needed I also agree that adding some compatibility code in Control would be quite difficult. Let's go the converter way, so closing as superseded by https://github.com/godotengine/godot-proposals/issues/4801.
