### ISSUE TITLE
EventPlayer - shows wrong values for get_loop_count() and get_length()

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#4493]
print(get_lenght()) prints 1. 
print(get_loop_count) grows each second ( 1689 and so on).

The song that is played has not looped that many times.
It's lenght in seconds or miliseconds (or whatever that is) is not 1.

It is showing wrong values on both accounts.

Load this IT file in eventPlayer node and see for yourself:
[impulseTrackerFile.zip](https://github.com/godotengine/godot/files/243541/impulseTrackerFile.zip)

**Comment by akien-mga** [comment]
I can confirm the bug using the above file.

**Comment by akien-mga** [comment]
Hm, it seems to be a known limitation. ``EventSteam`` currently supports only one driver, which is ``EventStreamChibi``: http://docs.godotengine.org/en/latest/classes/class_eventstreamchibi.html

According to the description, the latter is quite limited and cannot return the song length (and thus likely can't return the loop count, as counting loops probably related to the known length). It can return the playback position with ``get_pos()`` though.

**Comment by akien-mga** [comment]
So basically the conclusion is that EventStream is a work-in-progress API, it was designed so that various drivers could be written, but so far there's only a very limited one. So best keep this issue open has a reminder to improve it all.

**Comment by blurymind** [comment]
Any idea of a workaround to figure out when a track has finished playing?

**Comment by blurymind** [comment]
@akien-mga why are the methods there in the first place if they don't work? :) It's a shame. These track files save a lot of space and can get some really nice sound.

**Comment by akien-mga** [comment]
> why are the methods there in the first place if they don't work? :) It's a shame.

It's because those are virtual methods of ``EventPlayer`` that are supposed to get implemented in each driver. The only current driver does not implement all of them properly (I guess because it can't, though it could also be that it just wasn't finished, I don't know), but theoretically there could be other drivers in the future like ``EventSteamMIDI`` that would be able to implement those features properly. So the methods are there because they're what an EventPlayer should support, but the only backend behind EventPlayer does not support them. But I agree with you that it's quite confusing; I know @reduz plans to rework on the sound system in the near future, so we'll make sure that this EventPlayer is looked at.

**Comment by blurymind** [comment]
It would be super useful if there was a method to get the time of the next note.
like get_channel_last_note_time(), it could be called get_channel_next_note_time

**Comment by blurymind** [comment]
I found another problem with the current implementation!
@reduz @akien-mga 
get_pos() starts returning the wrong value after the song loops one time. It just continues to grow instead of returning back to 0.

So in essence there is absolutely no way of knowing when the song has looped.

**Comment by blurymind** [comment]
seemingly one could do it via get_lenght(), but that always returns 1. get_loop_count - but that returns a wrong value. And finally even get_pos() starts returning a wrong value after the first playthrough.

**Comment by blurymind** [comment]
a workaround to get the right get_pos() value after a loop is to disable loop on the node and add this manual loop method :
	if not is_playing():
		play()
It however creates a delay between the loops
