### ISSUE TITLE
Support for sending desktop notifications

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#4503]
There should be a way to send native notifications for desktop operating systems from Godot. By native notifications, I mean something like this:

![Notification](http://i.imgur.com/UBvoMj9.png)

Those notifications could be sent from the OS singleton, for example. There should probably also be the project icon next to the notification.

`OS.alert()` already exists, but it doesn't send notifications like this, it just makes a blocking pop-up system window.

The main use case of this would be for multiplayer games (be alerted when a new round starts or new chat messages while the window is minimized, for example).

**Comment by volzhs** [comment]
It would be better if this feature can handle Local Notification for android and iOS too.

**Comment by Calinou** [comment]
This issue is still relevant as of https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

**Comment by Calinou** [comment]
I have a proof of concept for this feature here: https://github.com/Calinou/godot/tree/add-os-notifications

It's currently implemented on Linux and Windows. It works perfectly on Linux, but on Windows, the notification will only appear the first time you request it. When you show a notification, a blank tray icon shows up and doesn't remove itself until you exit the application and hover it with the mouse. Any pointers?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/godot-proposals/issues/1338.
