### ISSUE TITLE
Can't save scene created from Filesystem Dock

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45031]
**Godot version:**

3.2.4 beta5

**Steps to reproduce:**
1. Right-click in Filesystem Dock
2. Select New scene and enter some name
3. Add some root
4. Save
5. SUDDENLY! A wild save dialog appears
6. When you try to save under the defined name, it says that you can't overwrite the scene already opened

Previously the dialog didn't appear and the scene just got saved.

**Comment by arrowinaknee** [comment]
I've looked it up and the issue seems to be brought by cherrypicking #42779
[Here](https://github.com/godotengine/godot/blob/029d2568c364b9755b333c59fae8c04d955055be/editor/editor_node.cpp#L2286) is a check for file existence that shows the save dialog because the scene is yet to be saved for the first time. 

I assume in case of saving a freshly created scene it should be saved without a dialog. Also i guess this check exists for the cases when the scene file is deleted for the user to be able to pick a new location to save the scene, but I don't think this behavior is logical too (and in this case the scene will also fail to save to it's old location).

So can the file existence check be simply deleted or the file dialog should still pop up in the case of deleted file?

**Comment by KoBeWi** [comment]
I think it's fine to delete it.
