### ISSUE TITLE
Horizontal lines appear across tilemap with pixel snap on

### ISSUE THREAD

**Issue by Supernova507** [godotengine/godot#45047]
**Godot version:**
3.2.3 stable official

**OS/device including version:**
Windows 10, 
NVIDIA Geforce GTX 1060, 
461.09 Gamer Ready Drivers
GLES2 and GLES3 

**Issue description:**
Horizontal lines appear across tilemap with pixel snap turned on, while using tile textures taller than cell size, this issue only happens at certain resolution ranges, and while zooming in/out inside the editor
![obraz](https://user-images.githubusercontent.com/77207819/104106486-8db66b00-52b6-11eb-9c3b-405f7495d261.png)

**Steps to reproduce:**
Create a tilemap with a tileset, where the subtile size is taller than the cell size, and where tile textures are the size of a cell with unused space being transparent, then zoom in or out in the editor or resize the window while the project is running

Project stretch settings:
Mode: 2D
Aspect: Keep

**Minimal reproduction project:**
[TilemapTextureBleeding.zip](https://github.com/godotengine/godot/files/5791633/TilemapTextureBleeding.zip)

**Comment by lawnjelly** [comment]
Looks like it is occurring because you have zero alpha at the edges of the green tile, which is getting read in by the filtering, so you are seeing the background showing through.

This can be reduced by using power of 2 textures, or better still by adding padding around each tile.

You can alternatively use 3.2.4 with batching and select the 'uv_contract' project setting (rendering->batching). You may need to increase the uv_contract amount in this case from the default.

**Comment by Zylann** [comment]
> which is getting read in by the filtering

Shouldnt it not be a problem if the texture does not use a filter in the first place? I remember having this issue for ages in my game while all my textures are powers of two and have filtering off.

**Comment by lawnjelly** [comment]
Yup, sorry this is misleading on my part, in godot parlance filtering is on or off, but in API speak there is always a filter active, one of which is nearest neighbour.

Mapping of texels to pixels on screen is a bit of a minefield, here's some info:
http://hacksoflife.blogspot.com/2009/12/texture-coordinate-system-for-opengl.html

The long version as I understand it is that, particularly when not using 1:1 mapping (scaling etc), due to precision errors in floats there is a reasonable chance that the texture reading (filtering bit) will read in a texel just over the boundary you specify. In fact, if you think about it, if the edge is at U 0.5 for a 64 width texture, the edge texel is undefined - it could either read from 31 or 32. This edge texel is in theory very unlikely to be read, but the math is fuzzy.

The problem tends to exhibit in a regular aliasing type fashion. A similar problem is much more pronounced when you use e.g. linear filtering, but it occurs with nearest too.

With a full sized texture this is not a problem - you can either use texture wrapping (where 0.0 wraps around to 1.0 on the other side), or clamping (where the edge texels are 'repeated' on a read), or mirror. But for an atlas you are out of luck, there is no hardware method to deal with this problem.

Some ways to try and deal with it:
* Texture arrays (not available in GLES2)
* Contract the UVs a little (this is what uv contract does, at the cost of a slight squashing of the drawn area)
* Apply wrapping manually in the fragment shader - I've not done this, and I've not heard of anyone using this - it could be very expensive to do on mobile as it breaks the texture read ahead etc. It would probably require independently having the area bound available in the fragment shader, either as a uniform (which would prevent batching) or through expensive extra varyings and larger vertex format.
* Use POT textures and regular grid atlas (e.g. 2x2 8x8). I believe this works by the math less likely to make errors.
* Edge padding - this is the most common solution, and can (almost) perfectly solve the problem.

Out of these edge padding is probably the best solution, although it can introduce problems of its own because a 16x16 area now becomes e.g. 18x18, you are off power of 2 boundaries etc.

Edge padding can be done manually but it would be nice to have an automatic solution. We did briefly bring this up with @groud as this would probably be his area.

It can in theory be done automatically and transparently to the user, but it requires an intermediate between what the user sees and edits, and the actual texture / UVs that are used for rendering. You need to take the original texture atlas, add the special padding, then also adjust the UV coords which are sent to the renderer. This has to be done client side, rather than in the godot renderer, because the renderer has no knowledge of UVs and the atlas etc, it is just a 'dumb' system.

Some structures in an atlas are potentially problematic. Edge padding is easy if e.g. everything in the atlas is 32x32 (which could e.g. pad to 34x34). But when you use a block that is 2x height, you either have to draw it as two independent blocks, or the padding would have to create a block that is 66x34 (i.e. off the boundary), and the UVs become more complex.

Note that edge padding is already the goto solution for a similar situation - skinned meshes. Here parts of the model are textured as UV islands with padding around each island to prevent this type of problem. With irregular UV islands, using wrapping type approaches is not really an option.

This whole area becomes even more complex when filtering and mipmapping is used, as the padding needs to be increased.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/39720, as this is due to the same cause.
