### ISSUE TITLE
Android Debug button doesn't show in editor 3.2.4 beta5

### ISSUE THREAD

**Issue by bluebarnacles** [godotengine/godot#45095]
**Godot version:**
3.2.4 beta5

**OS/device including version:**
Editor running on Windows 10 x64.

**Issue description:**
I plugged in my Android phone. I expected the Android Debug button to appear on the toolbar. It didn't appear.

**Steps to reproduce:**
* Open Godot 3.2.4 beta5 on Windows 10 x64
* Plug in an Android phone in with developer mode enabled and USB debugging on, that worked with Godot 3.2.4 beta4

**Minimal reproduction project:**
N/A

**Comment by akien-mga** [comment]
The Godot Android setup has changed from 3.2.4 beta 5 onwards, and requires you to specify the path to the Android SDK, see the updated documentation at https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_android.html#setting-it-up-in-godot

This is because we now need to use `apksigner` which is part of the Android SDK, instead of `jarsigner` from the JDK. What defines the availability of the Debug button is `adb`, for which there is no longer a setting to specify its path manually as it's also part of the SDK (so its location is inferred from the Android Sdk Path setting).

I could have made this clearer in the blog post, but this will be properly called out in the 3.2.4 stable release post.

**Comment by bluebarnacles** [comment]
Thanks, I see now that it wasn't a bug.
