### ISSUE TITLE
No escape character for % in ItemList

### ISSUE THREAD

**Issue by roberttodor** [godotengine/godot#45106]
I am trying to Create a item in a ItemList  with name "Acierto % " but is no way to make the perecentage (%) character appear. 
I used the documentation example:
        var health = 56
	print("Remaining health: %d%%" % health)
        $ItemList.add_item("Remaining health: %d%%" % health)

Output for print is ok : Remaining health: 56%
But the output for the item is : Remaining health: 56

I don´t know what else to do to make the % character visible.

**Comment by Calinou** [comment]
@roberttodor Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot. Also, please fill in the [issue template](https://github.com/godotengine/godot/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) instead of replacing it when reporting issues. We need to know your Godot version :slightly_smiling_face: 

In your GUI, are you using a font which includes a `%` character? The default project font includes this character

**Comment by Calinou** [comment]
I can't reproduce this on 3.6.beta 2b1544b4f (Linux). Make sure your ItemList is wide enough to display all characters from the item's text.

![image](https://user-images.githubusercontent.com/180032/200090573-5d9f2853-7b72-45bd-8655-edd53ecdb645.png)
