### ISSUE TITLE
tiling doesn't work in editor

### ISSUE THREAD

**Issue by vitw** [godotengine/godot#45124]
**Godot version:**
3.2.3 stable

**OS**
I am using Ubuntu with GNOME 3.36.8

Window tiling works in project manager, but not in editor.

https://user-images.githubusercontent.com/41671014/104308470-8bd8eb80-54f2-11eb-87b7-10c9a82aa96e.mp4

**Comment by groud** [comment]
I have a similar issue with awesome wm (on master). The window is popped up with a flags which make it not tiling (while the project manager spaws in tiling mode). But awesome allow me to change it with.

Apparently this is because the window pops in maximized mode. Maybe your windows manager does not handle things properly there.

I any case I find it quite annoying that it always spawns maximized, I hope this could be saved somewhere to keep the same status as the last run.

**Comment by Calinou** [comment]
> I any case I find it quite annoying that it always spawns maximized, I hope this could be saved somewhere to keep the same status as the last run.

See https://github.com/godotengine/godot/pull/32056.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/36373.
