### ISSUE TITLE
Editor window gets blurry when moving to the second monitor with lower DPI

### ISSUE THREAD

**Issue by MrZak-dev** [godotengine/godot#45203]
**Godot version:**
3.2

**Issue description:**
Editor Window Gets blurry when moving to the second monitor
### Main Monitor
![image](https://user-images.githubusercontent.com/27586088/104695463-de4a2000-571d-11eb-929c-56041d1c14e9.png)
![image](https://user-images.githubusercontent.com/27586088/104695756-46006b00-571e-11eb-95be-0fd5c2513f52.png)

![image](https://user-images.githubusercontent.com/27586088/104695719-384ae580-571e-11eb-9dde-1183954cfab8.png)

### Second Monitor
![image](https://user-images.githubusercontent.com/27586088/104695486-e5712e00-571d-11eb-8778-6b0e36913020.png)
![image](https://user-images.githubusercontent.com/27586088/104695817-5ca6c200-571e-11eb-9991-f16a00dcfd00.png)

![image](https://user-images.githubusercontent.com/27586088/104695698-32550480-571e-11eb-901b-a5e1e2ec747e.png)

You can see the difference in text , it get blurry and all the other parts of the editor

**Steps to reproduce:**
open any project move it from main monitor to a secondary one .

**NOTE**
This happens for me only on windows i couldn't reproduce the issue on Linux

**Comment by Calinou** [comment]
This is because Godot doesn't support seamless window scaling on Windows. For this to work, editor scale changes would have to be applied while the editor is running. This is a lot of work to do properly.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/56341, which has more information about the issue at hand.

**Comment by jaonewguy** [comment]
Hi, I know this issue is closed, but since this is the top Google result -- for those who don't want to read through the other issue, if you are on Windows just refer to this comment: https://github.com/godotengine/godot/issues/56341#issuecomment-1004584442

In short, just override the High DPI scaling override to "Application" so that at least it isn't "blurry" and that will give you more flexibility to adjust the editor.
