### ISSUE TITLE
Vulkan: Glow shape is square and offset from center when high-quality glow is enabled

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#45210]
**Godot version:**
497653ab53beff19b0420f4dbf1cf42babe544e0

**OS/device including version:**
Windows 10, 1080 ti

**Issue description:**
The glow shape is square and the glow is being offset when hq is turned on?

**Steps to reproduce:**
Check image

**Minimal reproduction project:**

[miniproj.zip](https://github.com/godotengine/godot/files/5820928/miniproj.zip)

on this picture you can se how offset they become when the hq option is turned on, and the further you zoom out the more square the glow becomes.
![Skärmbild 2021-01-15 133254XXXXXXXX](https://user-images.githubusercontent.com/13393087/104736394-27609b00-5743-11eb-9db8-87cfab0e7852.png)

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
Confirmed in part. I can reproduce both issues, but I am unsure which parts are bugs. 

Regarding the offset, I am not certain that high-quality is offset, I think it may be the regular glow that is offset. This is because the regular setting only captures every second pixel in a checkerboard patter. It would make sense if that naturally offset the glow pattern. So we need to investigate more. 

Regarding the square pattern when zooming out. This is a combination of using really intense glow settings and using low frequency glow. The low frequency glow (higher "levels") use smaller mip levels of the glow texture. So when the glow is predominantly low frequency you naturally see the boundaries of the texture's pixels. High quality mode makes the edges significantly softer and rounder, but does not eliminate this artifact altogether. I dont think this is something that can be addressed without rewriting the glow effect and making it orders of magnitude slower.

**Comment by Norrox** [comment]
i just wanted to write a little update, i see the glow has mostly been fixed? but when i look at it from this direction in the picture and from the opposite direction the offset is a little to the right now, if i look at it from the other sides its looks fine :)

(A little offset)
![Skärmbild 2021-06-08 113503](https://user-images.githubusercontent.com/13393087/121162163-fac23280-c84d-11eb-83cb-635f3edf7d45.png)

(Looks fine)
![Skärmbild 2021-06-08 113245](https://user-images.githubusercontent.com/13393087/121162708-71f7c680-c84e-11eb-968d-9e9b98c126d1.png)

**Comment by Calinou** [comment]
@Norrox On the first screenshot, this is expected because one of the cube's faces is brighter than the others.

**Comment by Norrox** [comment]
> @Norrox On the first screenshot, this is expected because one of the cube's faces is brighter than the others.

Yeah you are right, i feel kinda stupid because when i turn off the glow i can see that.
i spent ages trying to figure out why there was light comming from that direction.
i guess it's some defaut setting? ( can i change it anywhere??? )
i had to override it by placing a directional light and disable it  (hide it)
![Skärmbild 2021-07-09 205032](https://user-images.githubusercontent.com/13393087/125123900-98cc4580-e0f7-11eb-9498-8e1cbf39441b.png)
