### ISSUE TITLE
HTTPClient requests don't return any response until the body is fully transfered by the browser

### ISSUE THREAD

**Issue by rvenson** [godotengine/godot#45236]
**Godot version:**
3.2.3 / 3.2.4.beta5.official

**OS/device including version:**
GNU/Linux

**Issue description:**
When we execute an HTTPClient request on web builds, the request remains in the `STATUS_REQUESTING` until the body is fully transferred by the browser (and any response data can't be accessed). Only after the response body is fully received by the browser, the HTTPClient start to read the buffer. This issue is very perceptible with big files and remote servers because we have to wait a long time without know the actual progress of the body transfer.

On PC builds, the status changes to `STATUS_BODY` and the response data is accessible even if the body wasn't ready yet

**Steps to reproduce:**
1. Setup a minimal web server (preferably remote or throttled)
2. Make a request for a big file on the server
3. Try to access any response data while the body is being transferred by the browser

**Minimal reproduction project:**
[HTTPClientRequestBug.zip](https://github.com/godotengine/godot/files/5824834/HTTPClientRequestBug.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by Faless** [comment]
This can't be done in HTML5 platform, because `XMLHttpRequest` do not allow it.
It is also documented here: https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_web.html#class-httpclient-and-class-httprequest .
We could re-implement the HTTP classes using the new `fetch` API, but compatibility should be taken into account.
`CanIUse` suggest `fetch` support is good, but last time I checked (2/3 months ago), most of the implementations seemed more like stubs, where the base `fetch(URL)` works, but anything more than that was an undefined mess.

**Comment by Faless** [comment]
The `fetch` API was implemented in `master` and is also available in `3.3`. Closing as fixed via #46728
