### ISSUE TITLE
Issue with func named get

### ISSUE THREAD

**Issue by dt192** [godotengine/godot#45287]
**Godot version:**
3.2.3

**OS/device including version:**
PC / W10

**Issue description:**
If using a function named 'get' in script extending Reference, the parser throws an error unless an arg exists.

error(4,1) Parser Error: Function signature doesn't match the parent. Parent signature is: "Variant get(String)".

**Steps to reproduce:**
using `test.get("nothing")` with `func get(nothing):` works fine, but using `test.get()` with `func get():` throws an error.
 
**Minimal reproduction project:**
[get_bug_maybe.zip](https://github.com/godotengine/godot/files/5831296/get_bug_maybe.zip)

**Comment by pycbouh** [comment]
That's because `get` is a name of a built-in function of `Object`, which each class extends. And it expects a single argument of the type `String`.
https://docs.godotengine.org/en/stable/classes/class_object.html#id1

**Comment by Calinou** [comment]
Closing per @pycbouh's comment.

**Comment by dt192** [comment]
> 
> 
> That's because `get` is a name of a built-in function of `Object`, which each class extends. And it expects a single argument of the type `String`.
> https://docs.godotengine.org/en/stable/classes/class_object.html#id1
> 
> When reimplementing built-in functions you must use the same signature.

According to the docs only _get() can be overridden, so surely the fact it's letting me override get() as long as I pass a variable is a bug. The editor should throw an error and stop me.

**Comment by pycbouh** [comment]
@dt192 Every method can be *overridden*. `_get()` is a virtual method and can be *implemented*, which is not the same. You can override `get()`, but you need to give it the same signature as the original method. You can then call the original method from within your reimplementation by using the parent class accessor `.`: 

```gdscript
func get(property_name : String):
  return .get(property_name)
```

This can be used to preserve the default functionality while extending it, instead of replacing it. Virtual methods, on the other hand, are used to implement specific functionality within each individual class with no relation to the parent. Usually, the engine itself calls them in a very specific way.
