### ISSUE TITLE
Incorrect albedo colours when importing GLTF models

### ISSUE THREAD

**Issue by vybr** [godotengine/godot#45300]
**Godot version:**

3.2.4 Beta 6

**OS/device including version:**

Windows 10, GLES3, GTX 1050

**Issue description:**

I was using Kenney's assets to test environment settings when I noticed the colours were very washed out and wasn't sure what the problem was, I realised that Godot was lightening albedo colours in materials (gamma correction?) when I imported a GLTF/GLB model. 
I compared with a dae version and the hex values are actually not identical, so it's nothing to do with metallic/roughness values. 
To make sure there was nothing wrong with the models themselves, I verified in blender and the materials are all the same colour-wise.
As far as I can see there's nothing to rectify this in import settings. 

Left is the .**gltf**, right is .**dae**
![image](https://user-images.githubusercontent.com/10262137/104976066-3ae65d00-59f4-11eb-90c7-09bbf8722769.png)

**Minimal reproduction project:**

[Albedo Bug.zip](https://github.com/godotengine/godot/files/5833156/Albedo.Bug.zip)

**Comment by akien-mga** [comment]
There seems to be differences in how the materials are imported with glTF and DAE in `3.2` indeed (e09e5ab25) (also tested `3.2.3-stable`, same result).

Here's the `yellow` material generated by each importer:

- DAE:
```
[gd_resource type="SpatialMaterial" format=2]

[resource]
resource_name = "yellow"
params_cull_mode = 2
albedo_color = Color( 0.960784, 0.72549, 0.258824, 1 )
metallic = 0.5
roughness = 0.0960784
```

- glTF:
```
[gd_resource type="SpatialMaterial" format=2]

[resource]
resource_name = "yellow"
vertex_color_use_as_albedo = true
albedo_color = Color( 0.98256, 0.867959, 0.545718, 1 )
metallic = 1.0
```

Does Kenney provide the original Blender files too? It would be useful to compare how each has been exported to DAE / glTF to see if it's an export or an import issue.

**Comment by akien-mga** [comment]
I'm not sure it's a Godot bug here, I imported the DAE and glTF in Blender and they also look different there (with Eevee):
![Screenshot_20210119_103042](https://user-images.githubusercontent.com/4701338/105015019-63e10f00-5a41-11eb-9f00-c511f12131b8.png)
(glTF left side, DAE right side)

They do have different materials (glTF left, DAE right):
![Screenshot_20210119_103141](https://user-images.githubusercontent.com/4701338/105015150-88d58200-5a41-11eb-9fcd-4e1563edcaba.png) ![Screenshot_20210119_103117](https://user-images.githubusercontent.com/4701338/105015100-778c7580-5a41-11eb-877c-4296205ba514.png)

The albedo color is the same though in Blender, so there's still something weird here in Godot as the value changes, possibly due to `vertex_color_use_as_albedo = true`.

**Comment by akien-mga** [comment]
The issue seems to be that Godot's glTF importer (at least in `3.2`) applies a linear to SRGB conversion to the color:
https://github.com/godotengine/godot/blob/544f0bfff11634474ad645952a7f70214d6bb76d/editor/import/editor_scene_importer_gltf.cpp#L1466-L1475

It's also done in that file to `emissiveFactor` and lights `color`.

CC @godotengine/import

**Comment by fire** [comment]
If Blender has a difference without going into details, it would make sense Godot would have the same match.

Details
* I believe that Godot is following the gltf2 spec on gamma settings for the various maps.

**Comment by fire** [comment]
We match Blender's interpretation. Please comment if this is still a problem. Thanks!
