### ISSUE TITLE
Theme property "colors/font_color_selected" has no effect for TextEdit

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#45301]
Godot version:
3.2.3 stable

OS/device including version:
Windows 10

Issue description:
Theme property "colors/font_color_selected" has no effect for TextEdit, while it works fine for LineEdit.
Theme property setting
![image](https://user-images.githubusercontent.com/28705694/104977628-eca87c80-5a3a-11eb-9e2f-804fdbd20260.png)
When not selected
![image](https://user-images.githubusercontent.com/28705694/104977497-a3f0c380-5a3a-11eb-8da0-4cf5df393bcc.png)
When selected
![image](https://user-images.githubusercontent.com/28705694/104977547-c256bf00-5a3a-11eb-807c-34a97e984a0d.png)

Steps to reproduce:
Create an empty theme template, change "colors/font_color_selected" property for TextEdit, check the result in Theme Preview.

Minimal reproduction project:
[Test.zip](https://github.com/godotengine/godot/files/5833134/Test.zip)

**Comment by EricEzaM** [comment]
This is caused by `override_selected_font_color` is false by default, so the check below fails.

https://github.com/godotengine/godot/blob/8a6d4dd5ed770f4dc464bbc6af912b96c63bbc2c/scene/gui/text_edit.cpp#L1261-L1263

@Paulb23 @bruvzg Not sure if you guys are the right ones to CC, but should this even be an option? If the user wants a custom selected font color, why do they need to set a color AND set this option to true for every TextEdit?

**Comment by Paulb23** [comment]
Yeah this is intended, though an additional bug is the feature not being ported to `LineEdit`.

We could potentially get rid of the property for 4.0 as it's compatibility breaking by checking if `font_color_selected == Color(0, 0, 0, 0)` instead. This would however prevent reuse of that theme where the font colour should not be overridden. In addition `Color(0, 0, 0, 0)` would no longer be a valid value.
