### ISSUE TITLE
Generic6DOFJoint precision value is not correctly applied

### ISSUE THREAD

**Issue by Demindiro** [godotengine/godot#45378]
**Godot version:**
3.2.3.stable.custom_build.31d0f8ad8

**OS/device including version:**
Linux pc1 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Issue description:**
The precision value of Generic6DOFJoint in the inspector (_before_ running the project) is not correctly shown, nor is it correctly applied. It shows as 1 when the actual default is 10 (according to [this post][1] I found and some experimentation by myself.). When setting the value to 2 in the _remote_ inspector (while the project is running) the joint becomes extremely saggy. When setting it to 10 it behaves as previously and setting it to 100 removes the saggyness as expected.

https://user-images.githubusercontent.com/17316999/105564173-510c5a00-5d21-11eb-89ce-39b9534289cf.mp4

**Steps to reproduce:**
1. Create two RigidBodies with some distance between them. Lock the axises of the first and increase the mass of the second one to 100.
2. Create a Generic6DOFJoint and set the nodepaths to each of the bodies.
3. When running the project, the second body should be saggy.
4. Nothing changes if you set the precision to any other value _before_ running the project
5. When setting the precision in the _remote_ inspector you will see the body become less saggy with values above 10 and more saggy with values below 10.

**Minimal reproduction project:**
[6dof-joint.zip](https://github.com/godotengine/godot/files/5859356/6dof-joint.zip)

[1]: https://pybullet.org/Bullet/phpBB3/viewtopic.php?p=41050#p41050

**Comment by Demindiro** [comment]
Also, on a related note: there is nothing about the precision property in the [documentation][1]. This should also be fixed.

[1]: https://docs.godotengine.org/en/stable/classes/class_generic6dofjoint.html

**Comment by madmiraal** [comment]
The `Generic6DOFJoint` `precision` property has been removed in #44391 and backported to 3.2 (#44392) which will be included in 3.2.4.

**Comment by pouleyKetchoupp** [comment]
@Demindiro:
From https://github.com/godotengine/godot/pull/44392#issuecomment-767409570
> I actually do have a usecase for this. The default precision of 10 is too low and results in sag, which I only managed to fix by setting it to 75 or higher.

The problems you encounter with this setup are due to the attached rigid body to have a mass of 100, while the parent rigid body has a mass of 1 and is forced to be static using locked axes.

It's generally not a good idea to have this kind of setup, as unbalanced masses make solving constraints really hard for the physics simulation. The precision value you were using before was a hack that allows forcing the joint to be solved many times, but it's not the proper way to fix this problem as it can make things very slow if you have multiple rigid bodies like this one and it might cause unwanted side effects when collisions occur.

In your test project, it works perfectly well if you either:
-Set the parent rigid body mode to static.
-Set both rigid bodies with the same mass.

**Comment by Demindiro** [comment]
@pouleyKetchoupp 

> In your test project, it works perfectly well if you either:
> -Set the parent rigid body mode to static.
> -Set both rigid bodies with the same mass.

In the project I'm working on I can't use either of these solutions as the player is able to create objects of arbitrary size (with a potentially large difference between them) and the mass roughly depends on this size. So far, the only solution I've found is setting the precision property higher for the cases where a small object is connected with a large object.

**Comment by pouleyKetchoupp** [comment]
I'd like to understand why setting the locked rigid body to static doesn't work in your use case.
 
In the example from your MRP, the lighter object is locked, while the heavy object is attached to it. Would you be able to set the object to static mode instead of locking when this is needed, and then switch back to rigid when it needs to move?

If that doesn't work for you, can you share a bit more about your use case so I understand the problem better? Another MRP would be best. So far I understand that you have multiple objects of different masses linked with joints, but I would expect that to be fine as long as the lighter ones can move.

**Comment by Demindiro** [comment]
I think these videos from my project demonstrate the issue well:

This is what happens with the default settings (precision 10):


https://user-images.githubusercontent.com/17316999/105877417-4216f780-6000-11eb-8230-86d6568e541c.mp4

This is what happens with precision set to 100:


https://user-images.githubusercontent.com/17316999/105877462-51964080-6000-11eb-8e87-97f93fae9b1f.mp4

I don't know how I'm supposed to fix this in a clean way without increasing the precision.

**Comment by pouleyKetchoupp** [comment]
In this video, it looks like the turret parts could all use the same mass for the joints to be more stable. The only case where they would need an accurate mass depending on their shape is if they could be detached and would be simulated as separate rigid bodies. If that was needed, you could set a proper mass only when it happens.

**Comment by pouleyKetchoupp** [comment]
Also, I'm wondering if joints are the best way to do what you're trying to achieve here, since it doesn't seem you need to give them free movements at all. Have you tried using RigidBody in Kinematic mode instead for the turret parts? This way they could be just set as child of the node they need to be attached to, and the rotations could be done by script (just changing their transform).
