### ISSUE TITLE
PhysicsDirectBodyState3D.transform is exposed as Transform2D

### ISSUE THREAD

**Issue by winston-yallow** [godotengine/godot#45502]
**Godot version:**
4.0 build at 549ffb9be9

**OS/device including version:**
Linux

**Issue description:**
When trying to access a property like `basis` of the states `transform` you will get this error:
```
Cannot find property "basis" on "Transform2D"
```
 It seems like it is incorrectly exposed to gdscript in `./servers/physics_server_3d.cpp` for the property only. The getter `get_transform()` works as expected.

**Steps to reproduce:**
Attach this script to a rigid body 3D:
```gdscript
func _integrate_forces(state: PhysicsDirectBodyState3D) -> void:
    var b := state.transform.basis
```

**PS:**
This is a simple fix, a merge request will follow in a second. Is it better practice to have this issue to explain the merge request, or to just make the merge request without an issue first (but obviously with a small description within the request)? Would appreciate guidance for the future.

**Comment by akien-mga** [comment]
>  This is a simple fix, a merge request will follow in a second. Is it better practice to have this issue to explain the merge request, or to just make the merge request without an issue first (but obviously with a small description within the request)? Would appreciate guidance for the future.

In this case making the PR directly with explanations on what the bug is in the PR would likely be fine. I'd say a separate issue is good if you don't plan to make a PR right away, or if the PR might not necessarily be the absolute best fix for the issue (or the issue may not be considered one). I.e. if you're very confident like here, direct PR is good :+1:
