### ISSUE TITLE
Objects are translucent in WebXR immersive-AR mode

### ISSUE THREAD

**Issue by michaelvogt** [godotengine/godot#45505]
**Godot version:**
Godot_v3.2.4-beta6_win64, HTML5 export, custom exporter provided by dsnopek

OS/device including version:
Windows 10, Pixel 4, Android 11, Chrome 89 Beta

**Issue description:**
Meshes added to an web AR project, like this
![simplescene](https://user-images.githubusercontent.com/231274/106004204-43edc300-60b3-11eb-953a-175dd03000f2.JPG)

are displayed translucent when running the app
![Screenshot_20210127-151347](https://user-images.githubusercontent.com/231274/106003765-cfb31f80-60b2-11eb-85b0-bb547fed3d3b.jpg)

No transparency was set for the meshes by me.

**Steps to reproduce:**
Setup a minimal WebXR app with immersive-ar mode (like [here](https://www.snopekgames.com/blog/2020/how-make-vr-game-webxr-godot), setting immersive-ar in place of immersive-vr) and start it in an AR capable browser.

After successful localisation, the objects are displayed, semitransparent as shown in the screenshot above.

**Minimal reproduction project:**

**Comment by dsnopek** [comment]
Thanks for the report!

I'm able to reproduce this, and I've spent a little bit of time trying to figure out where the transparency is coming from, but no good leads yet.

**Comment by Calinou** [comment]
Judging by the screenshot, it looks like the object is rendered with the Add blend mode instead of Mix.

**Comment by dsnopek** [comment]
@michaelvogt The clue you found about `CanvasLayer` on Discord seems to be the key here!

In my demo project, if I remove the `CanvasLayer` after entering AR, then the geometry is no longer translucent. I have no idea why having that `CanvasLayer` is causing a problem (it shouldn't), but it isn't even strictly necessary in order to add the UI.

Here's a new version of my demo project that uses a `Control` node to hold the UI, and hides it after entering AR:

http://bit.ly/godot-webxr-06

I think this might end up being a documentation fix, where we just give a different example/recommendation for how to add the UI to the scene.

**Comment by michaelvogt** [comment]
Yes, works for me. Thanks for looking into this so quickly.

**Comment by dsnopek** [comment]
The `CanvasLayer` is recommended much more strongly in [the tutorial on my website](https://www.snopekgames.com/blog/2020/how-make-vr-game-webxr-godot), which I've already updated, but there is also a reference to it in the WebXR example code in the Godot core docs, so I've made PR #45548 to remove that, to try and avoid others running into this problem.
