### ISSUE TITLE
Newly created AnimationTree appears with previously deleted content

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#45528]
**Godot version:**

3.2.4.beta6.mono.official

**OS/device including version:**

Win10

**Issue description:**

See the following gif; an AnimationTree is deleted and a new one created afterwards. The newly created one contains the content of the previously deleted one:
![6YtyAXf8se](https://user-images.githubusercontent.com/8841352/106148506-677b4100-6179-11eb-8179-925ece3da8fe.gif)

**Steps to reproduce:**
Just follow the displayed steps in the gif, create an AnimationTree, configure something inside it, delete the node, create a new AnimationTree. See it having the old content.

**Comment by theraot** [comment]
I confirm this still happens in master at the time of writing.

**Comment by duianto** [comment]
This might be the same or a similar issue that also will be solved by the pending PR:
Update all AnimationTree's editors when editing #45764

But here are some additional information.

A new `AnimationTree` shows the nodes from the last viewed `AnimationTree`.
Instead of showing an empty `AnimationTree` dock.

### Observed in:
v3.5.beta1.official [b9b23d222]
v3.4.3.rc1.official [894b6d504]
v3.4.2.stable.official [45eaa2daf]

Windows 10 21H2

### Reproduction steps

- Open the attached project: [issue, new animationtree shows last viewed animationtree.zip](https://github.com/godotengine/godot/files/8055167/issue.new.animationtree.shows.last.viewed.animationtree.zip)
- From the `FileSystem` dock, open the scene: `a.tscn`
- In the `Scene` dock, add a child node: `AnimationTree`
- Observe that the `AnimationTree` dock is empty.
- From the `FileSystem` dock, open the scene: `b.tscn`
- In the `Scene` dock, select the `AnimationTree` node
- Observe that the `AnimationTree` dock has one node: `Output`
- Above the viewport, click on the scene tab: `a(*)`
- Observe that the `AnimationTree` dock that used to be empty,
now shows the same `Output` node as in scene: `b.tscn`
- From the `FileSystem` dock, open the scene: `c.tscn`
- Select the `AnimationTree` node
- Observe that the `AnimationTree` dock has two nodes: `Animation` and `Output`
- Above the viewport, click on the scene tab: `a(*)`
- Observe that the `AnimationTree` dock now shows,
the same two nodes as in scene: `c.tscn`


### Expected

A new `AnimationTree` should show an empty `AnimationTree` dock.

### Minimal project

[issue, new animationtree shows last viewed animationtree.zip](https://github.com/godotengine/godot/files/8055167/issue.new.animationtree.shows.last.viewed.animationtree.zip)
