### ISSUE TITLE
3D gizmos are rendered behind the grid

### ISSUE THREAD

**Issue by Flavelius** [godotengine/godot#45520]
**Godot version:**

3.2.4.beta6.mono.official

**OS/device including version:**

win10, nvidia gtx1060

**Issue description:**

Editor scene gizmos are rendered behind the world grid:

![grafik](https://user-images.githubusercontent.com/8841352/106107883-c58f3080-6147-11eb-9d8b-a57e0bc5e548.png)

**Comment by akien-mga** [comment]
To be clear, you're talking about the directional light gizmo specifically here?
The other two gizmos (transform and cube) don't seem to be behind the grid.

**Comment by Flavelius** [comment]
all of the 'gizmos' are behind the grid, the transform handle is not.

**Comment by aaronfranke** [comment]
I tested some old Godot versions. This bug occurs on all 3.x releases (I tested down to 3.0.6) but does not occur on 2.1.6.

**Comment by JFonS** [comment]
This happens because of the transparent object sorting, there's no easy way to split the grid so that sorting doesn't cause issues AFAIK. 

After #28289 (or #43206 for 3.2) the issue has become more apparent due to the grid being denser, especially at very steep viewing angles like in OP's image.

I have a WIP branch adding a shader to the grid, so it fades nicely at steep angles. I will try to clean it up and open a PR soon.

**Comment by Flavelius** [comment]
Can't the grid then just be rendered as solid lines; does it need transparency?

**Comment by Calinou** [comment]
> Can't the grid then just be rendered as solid lines; does it need transparency?

Yes, the grid needs transparency to look more subtle. Otherwise, it easily gets too obnoxious.

**Comment by nathanfranke** [comment]
See https://docs.godotengine.org/en/stable/tutorials/3d/3d_rendering_limitations.html#transparency-sorting and https://github.com/godotengine/godot/issues/23694

**Comment by JFonS** [comment]
I opened #45594, which should mitigate this issue.

**Comment by Flavelius** [comment]
With the new fading-out grid, this is less noticeable
