### ISSUE TITLE
viewport.warp_mouse lingers on mouse motion event speed for many frames

### ISSUE THREAD

**Issue by ceLoFaN** [godotengine/godot#45592]
Or maybe `Mouse speed is not changing fast enough` would be a better title?

**Godot version:**
3.2.3

**OS/device including version:**
`Manjaro Linux`, `KDE 5.20.5`, `Xorg 1.20.10`, `libinput 1.16.4` if it helps

**Issue description:**
First of all, my use-case is to process mouse motion events to precisely move an object.

When I use `MOUSE_MODE_VISIBLE` I get fine values for mouse speed (e.g. `(-0.364325, 0.731412)`), but I kinda need the behavior of `MOUSE_MODE_CAPTURED`, as I want the cursor to be hidden and not be restricted by the window borders.

Unfortunately `event.speed` is 0 when using the captured mode, and using `event.relative` is really choppy for small mouse movements since it is rasterized (e.g `(-0, 1)`). So I went back to `MOUSE_MODE_VISIBLE`.

To work around it, I tried using `viewport.warp_mouse(viewport_center)` whenever I got too far off from the screen center. That, understandably, triggers a mouse motion event. The problem is the motion speed is being affected by the mouse warping for many following motion input events (slowly decreasing). So subtracting the warp vector to compensate during the next event won't work.

I also tried `set_process_input(false)` before warping and then turning it back on, but to no avail, sometimes even 100 frames are not enough for the speed to be unaffected. From what I read, that is not expected to work anyway, as it only stops processing the input event on the node, not globally. It would kinda suck as a workaround though.

Here's a visual recording:

https://user-images.githubusercontent.com/9743949/149625198-085fdb9e-6e72-44f0-9002-4424dc8452ee.mp4

**Steps to reproduce:**
See attached project, it's fairly simple. But to give a summary:
```gdscript
func _input(event):
	if event is InputEventMouseMotion:
		speed = event.speed
		
		if (viewport.get_mouse_position() - viewport_center).length() > 300:
			set_process_input(false)
			viewport.warp_mouse(viewport_center)

func _physics_process(delta: float):
	# wait some ticks...
	set_process_input(true)
```

**Minimal reproduction project:**
[TestMouseWarp.zip](https://github.com/godotengine/godot/files/5898483/TestMouseWarp.zip)

**Comment by Calinou** [comment]
> Unfortunately event.speed is 0 when using the captured mode, and using event.relative is really choppy for small mouse movements since it is rasterized (e.g (-0, 1)). So I went back to MOUSE_MODE_VISIBLE.

Actually, floating-point mouse inputs should be reported correctly when using captured mouse mode since raw input is now used since Godot 3.1.

**Comment by ceLoFaN** [comment]
> Can you (or anyone else) try to reproduce this on Windows if you have access to a Windows machine?

Yes, I had a W8.1 laptop sitting around and the behavior is pretty much the same as the one described above. The reported mouse speed is in line with the one on Linux. 

> Floating-point mouse inputs should be reported correctly when using captured mouse mode since raw input is now used since Godot 3.1. However, this is impossible to do in other mouse modes since we want to preserve the OS' mouse acceleration in other modes.

Maybe I'm missing something, but I think there's no way of getting those floating-point inputs using the captured mouse mode, because the `event.speed` is always 0, and the `event.relative` values, although they probably are floats, are rounded to integers to match the cursor position I suppose.

But the speed is indeed being correctly reported for all the other mouse modes, except for the captured one, if that's what you meant?

-----------------------------------------------------------------------

I do have a workaround in mind, maybe it will help others:
- Use `event.speed` all the time, except when it's time to warp the mouse to the viewport's center.
- For the next ~120 ticks after warping, use `event.relative` instead, since the values there are pretty much instantaneous, but make sure to ignore the event caused by warping.
  The lack of accuracy can be partially solved by considering past X values of `event.relative` to get a more stable vector, at the cost of added latency.

It might be good enough for my use-case, but for shooters and the likes, probably not.

**Comment by TempestStorm** [comment]
I have huge issues with warp_mouse() I'm running pop_os! 20.04 Xfce, haven't yet tested it on anything else. Take this extremely simple example:

extends Control

func _process(delta):
	var mousePos:= get_global_mouse_position()
	warp_mouse(mousePos)

It jitters around and quite often I can see 2 cursors on screen at once.
I only just discovered it today however so I'm yet to come up with a work around, on my main project I'm trying to bind the mouse to a rectangle in the middle of the screen and use warp_mouse if it leaves the rect. 

I think the issue might be that Godot is faking a mouse motion rather than setting the mouse cursor to that position. The documentation doesn't really explain why its using the term "warp" instead of "set"

**Comment by Calinou** [comment]
> It jitters around and quite often I can see 2 cursors on screen at once.

This is likely to be due to monitor ghosting. Your display can't refresh fast enough to completely remove the cursor that appeared in the previous frame, which lets you see more than one cursor at once.

(Most operating systems don't support multiple mouse cursors at once, not out of the box at least.)

**Comment by TempestStorm** [comment]
Oh I'm sure that is the issue and if it only happened when the mouse was moving then I would completely understand it, however you can manipulate them by moving the mouse and if you stop moving the mouse when its showing 2 then it will keep flickering between them. Also if you move the mouse slowly you can widen the gap between them. I took a video:

https://user-images.githubusercontent.com/66976859/108542796-18d64800-72dc-11eb-904a-10036f30fc6b.mp4

**Comment by TempestStorm** [comment]
I thought that first too and I'd be happy to put that to bed if it wasn't for the fact that the mouse still flickers between the 2 when it isn't in motion. I took a video, hopefully that explains it better:


https://user-images.githubusercontent.com/66976859/108543493-0f011480-72dd-11eb-90ff-25733e58b05c.mp4

**Comment by Calinou** [comment]
Which stretch mode are you using in this project? If you're using the `2d` or `viewport` stretch mode, your "viewport" mouse coordinates will most likely not match the ones used on the screen.

**Comment by TempestStorm** [comment]
I made this project to test it and didn't change any stretch mode, are you referring to this page?
![image](https://user-images.githubusercontent.com/66976859/108543888-99e20f00-72dd-11eb-9434-d7e536a14ab1.png)

**Comment by Calinou** [comment]
> I made this project to test it and didn't change any stretch mode, are you referring to this page?

Yes :slightly_smiling_face:

**Comment by TempestStorm** [comment]
Yeah so it defaults to disabled, I tried it on the other 2 (2d and viewport) and although I am aware that those 2 might need some conversion all 3 of them have the same flickering effect.

**Comment by TempestStorm** [comment]
We have just passed the project to our artist as she has windows 10 and we can confirm that it runs far better under windows 10 then it does on any of the Linux machines. We have tried both the main project and the 2 line example program. 

On windows it can still leave the binding Rect or window and interact with objects outside of that Rect if you "slingshot" by moving the mouse very quickly, but we can't get the flickering double cursor glitch. 
I have even tried borrowing her monitor to see if it was a monitor issue (I didn't think it was due to it coming up on the recording but might as well check). 

We think it really is faking a mouse motion rather than setting the position because you can kinda see it moving back when you "slingshot" rather than snapping back.

**Comment by Calinou** [comment]
> We think it really is faking a mouse motion rather than setting the position because you can kinda see it moving back when you "slingshot" rather than snapping back.

Don't speculate, test :slightly_smiling_face: 

To confirm this, try printing text using the following:

```gdscript
func _input(event):
    if event is InputEventMouseMotion:
        print(event.relative)
```

Then check the text being printed when `warp_mouse()` is called.
