### ISSUE TITLE
Empty `canvas_item` shader with thousands of nodes = high (100%) CPU core usage

### ISSUE THREAD

**Issue by AlexTheRegent** [godotengine/godot#45595]
**Godot version:**

3.2.3 stable, 3.2.4 beta 6

**OS/device including version:**

Windows 10, GLES2 and GLES3, GeForce 1070Ti (last version of drivers).

**Issue description:**

When attaching empty shader script (only `shader_type canvas_item;`) to scene that is instanced thousands times CPU core usage raises to 100%. In my project I made simple shadow shader for grass (fragment shader to make sprite black+transparent and vertex shader to rotate and skew the result). Benchmark results:  

No shader, about 3000 grass sprites: 8% CPU core usage.
Shader and around 3000 grass sprites: 100% CPU core usage.  

Benchmark results for minimal reproduction project:  

No shader, 8000 sprites: 6% CPU core usage.
Empty shader, 8000 sprites: 100% CPU core usage.  

I also noticed that turning on shader increases `2d/draw calls` by 4 * nodes count. CPU usage is also affected by node's visibility (if none of the nodes are visible, CPU usage is low).

**Steps to reproduce:**
1. Make scene with sprite and sprite for shader.
2. Add ShaderMaterial to sprite and create empty shader (`shader_type canvas_item;`).
3. Instance scene thousands times.

**Minimal reproduction project:**

[empty_shader_with_thousands_of_nodes.zip](https://github.com/godotengine/godot/files/5898912/empty_shader_with_thousands_of_nodes.zip)

*Bugsquad edit (keywords for easier searching): 2D*

**Comment by Calinou** [comment]
You probably want to use MultiMeshInstance2D when you have thousands of instances like this. I don't think you can benefit from batching with custom shaders, or can you?

**Comment by lawnjelly** [comment]
Yes Calinou is right. If you tick `project_settings->rendering->batching->debug->diagnose_frame` you can see the difference. Your null shader is not batching.

Before batching, all projects took this much CPU. These days a lot of custom shaders will batch, but just not this one (have not investigated why, but given it is unlikely in practice, it doesn't seem a big problem).

**Comment by lawnjelly** [comment]
Ah looking closer your `sprite.tscn` contains 2 sprite objects. A sprite, and a sprite with a shader as a child. They are thus one rendering 1 - 2 - 1 -2 etc. It can't batch them because they use separate shaders, and they also overlap so can't be reordered.

If you instead make the shader the root of sprite.tscn, and hide the other node, the shader will batch (because there are no material changes).

See:
https://docs.godotengine.org/en/stable/tutorials/optimization/batching.html

For a full description of how it works. As such, it is working great, so closing this issue.
