### ISSUE TITLE
[3.2.4-rc1] - tscn files created from FBX files have absurdly large sizes

### ISSUE THREAD

**Issue by indie-dude** [godotengine/godot#45625]
Godot version:
3.2.4-rc1

OS/device including version:
OS-independent

Issue description:
Saving an imported FBX as .tscn results in a huge .tscn file.

As an example, I imported a rigged and textured humanoid in an animated T-Pose as an FBX file.
The size of the FBX itself is 7,282KB, and the imported material file (including textures) is 9,248KB.
Opening the FBX in the editor and saving it as .tscn results in a 196,726KB file.

I repeated the process going the GLTF way using the exact same sources (model, textures and animation), and I ended up with a 10,075KB tscn file. The difference in file sizes is absurd.

Steps to reproduce:
Create a humanoid 3D model in your program of choice, rig, texture and animate.
Export as FBX.
Import FBX into Godot.
Use the "Open anyway" option in Godot (as opposed to "New Inherited") to open the FBX.
Apply materials, check animation(s)
Save it as a scene (.tscn)
Check file size of the .tscn. In my case it's ~190MB

GLTF workflow:
Identical except save as GLTF using the "GLTF Separate" option, in order to end up with a GLTF file and a .bin file. Bring these files into Godot and open the GLTF as above, apply materials then save as .tscn. Filesize in my case ~10MB.

**Comment by akien-mga** [comment]
That's not really a bug, you're saving a binary FBX file as a text-format, and serialization all this binary content (vertices, textures, etc.) in text takes (a lot) more space than if packed as binary.

The correct workflow would be to open the FBX as inherited scene, and save the inherited scene. Not edit and save the FBX file itself as a new copy.

**Comment by indie-dude** [comment]
@akien-mga :
I've tried it the way you suggested. The tscn file created this way is 1KB, so the issue goes away.
However... that means you can't delete the FBX file from your project, and any changes you make to the scene can only be activated through code at runtime, since the assets from the FBX are not editable. Unless I'm missing something obvious to everyone else.

**Comment by akien-mga** [comment]
Yes the recommended workflow is that you do keep the FBX file - that's your source asset, which gets imported in `.import/`. If you need to modify the model, you'd do it in your 3D modelling application and overwrite the previous FBX file, which will automatically get updated in the inherited scene.

In an inherited scene, the you can edit the nodes and properties imported from the FBX - the inherited scene will only save the diff to the original.

Alternatively, if you really want to convert the FBX to a native Godot scene and delete the source (losing the possibility to update it with changes), you should save it to `.scn` (binary format) instead of `.tscn` (text format).
