### ISSUE TITLE
3.2.3 stable.mono: crash Editor

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#45636]
**Godot version:**
3.2.3 stable.mono

**OS/device including version:**
GLES2, GLES3,
MacOs 10.15.7
Mono

**Issue description:**
Crash of the editor when starting from Visual Studio for Mac 8.8.6 (b15)
. The fall does not always occur, usually the first few times everything is tested normally. I fix the dumps.
[mono_crash.zip](https://github.com/godotengine/godot/files/5905324/mono_crash.zip)

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by Calinou** [comment]
@ret80 Can you (or anyone else) still reproduce this bug in [Godot 3.3.2](https://godotengine.org/article/maintenance-release-godot-3-3-2) or any later release?

If yes, please ensure that an up-to-date Minimal Reproduction Project (MRP) is included in this report (a MRP is a zipped Godot project with the minimal elements necessary to reliably trigger the bug). You can upload ZIP files in an issue comment with a drag and drop.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
