### ISSUE TITLE
AR development workflow limitations

### ISSUE THREAD

**Issue by michaelvogt** [godotengine/godot#45689]
**Godot version:**
Godot_v3.2.4-beta6_win64

**OS/device including version:**
Windows 10, Chrome 88

**Issue description:**
Previewing a Godot app that uses AR is impossible with the internal HTML5 preview
- The preview is only served over localhost. AR features need to be run on an AR capable device. Accessing the preview over the network is essential
- The preview is served over http. Modern web apis require https to be used

Of course it is possible to serve the content of the export folder using an external server (external to Godot). But this requires manual export every time I want to preview a change. That gets boring quickly. I was told about the possibility to do the export with an external python script, but I think this feature should be provided by Godot directly.

**Steps to reproduce:**
Press the HTML5 preview button with any project. The preview starts with the default browser. Trying to access the URL with https or over the network fails.

**Minimal reproduction project:**
Any project can be used to reproduce this (I believe)

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
In the meantime, you can expose the local web server using [ngrok](https://ngrok.com/) which exposes HTTP and HTTPS tunnels accessible over the Internet.
