### ISSUE TITLE
[GDScript] String's erase() function does not work for strings inside arrays/dictionaries

### ISSUE THREAD

**Issue by Xascoria** [godotengine/godot#45688]
**Godot version:**
Godot v3.2.3 Stable Mono win64

**OS/device including version:**
Windows 10, device n/a

**Issue description:**

GDScript's String's `erase ( int position, int chars )` only works if the string is reference from a variable, if it's passed via inside an array/dictionary, no errors/warnings are given but no changes will be done to the original string.

Credit to Smudge#4848 on discord for finding this.

**Steps to reproduce:**
```
var test1 = "testing"
test1.erase(4,3)
print(test1)  #"test"

var test2 = ["testing"]
test2[0].erase(4,3)
print(test2[0])  #"testing"
	
var test3 = {0:"testing"}
test3[0].erase(4,3)
print(test3[0])  #"testing"
```

**Minimal reproduction project:**

n/a

**Comment by pycbouh** [comment]
Why would there be an error or a warning, though? Strings are passed by value. When you access an array index or a dictionary key, you get the same value, but not a reference to the original entry.

The value you get is properly edited by your function call. You can see it if you use an intermediate variable. But since it's not a reference, you need to write it back to the array or the dictionary.

There is no bug.

**Comment by pycbouh** [comment]
Yes, the function edits in place, but you can store the value you get from the collection by index or by key in an intermediate variable, call the function on that and then write it back.
