### ISSUE TITLE
Wrong popups/tooltips offset in the editor (DisplayServer regression)

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45740]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

**Godot version:**
![image](https://user-images.githubusercontent.com/58845030/107088966-9712f480-67dc-11eb-82a6-0b5f753bdef9.png)

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**
When you click any tab (Project,Scene,Debug) or even right click to add node the popup appears far away form mouse:
![image](https://user-images.githubusercontent.com/58845030/107089056-bd389480-67dc-11eb-86cb-ca82cce6c0e2.png)

**Steps to reproduce:**
Just interact with engine itself

**Workaround**
minimize window and maximize again!

**Comment by awalone995** [comment]
happens only with custom zoom ftw

**Comment by KoBeWi** [comment]
Related to #45200
This issue goes away when you resize the window.

**Comment by sunkper** [comment]
I experienced this issue with the default setting. (Windows 10, RX 570). Also can confirm that it goes away when I resize the window.

I found that this only happens when the editor loses focus while it is opening a project (i.e. I alt+tab to other windows while waiting). If the Godot is still focused while loading a project this does not happen.

**Comment by mhilbrunner** [comment]
I also experience this with default settings on Windows 10 with current master (b1eee24e2673b4a980a6f661511ff0f18c2fff8a).

I can reproduce this every time like in previous comments: open Godot, while a project loads switch focus to another window, wait, voilá, offsets are all weird. :)

**Comment by foxydevloper** [comment]
I noticed that it's offset by the same offset that the project manager opens up offset by. Dragging the project manager around before opening a project doesn't affect this offset though.

### 1440p monitor
| Popup Offset | Project Manager Offset |
| - | - |
| ![image](https://user-images.githubusercontent.com/12120644/127074000-2d736650-2fb1-4804-94dd-dac4db944410.png) | ![image](https://user-images.githubusercontent.com/12120644/127074607-f25baf43-daed-49fd-a82a-7bc44ead31ed.png) |

### 1080p monitor
| Popup Offset | Project Manager Offset |
| - | - |
| ![image](https://user-images.githubusercontent.com/12120644/127074364-5b50d009-5ff3-49c1-9506-ff999aae63c7.png) | ![image](https://user-images.githubusercontent.com/12120644/127074526-19849cd1-504e-4d3a-b65e-6bb197c6b728.png) |

The 20 px difference is probably due to the Windows Title bar being 20px high

**Comment by MatteoPiovanelli-Laser** [comment]
Windows 10.  d6f972fad45d28222b1437a047241dd74f0d5b90
I'm trying to figure this out.
After a few steps I got to (and similar lines if I'm trying to click on the FileSystem dock):
https://github.com/godotengine/godot/blob/d6f972fad45d28222b1437a047241dd74f0d5b90/editor/filesystem_dock.cpp#L2512
The call to `tree->get_screen_position()` there is returning the odd values.
Following deeper
https://github.com/godotengine/godot/blob/d6f972fad45d28222b1437a047241dd74f0d5b90/scene/gui/control.cpp#L1717
`w->get_position()` seems to be the call that leads to the bad offset values.

When the editor window is resized, everything starts going to the right positions. My guess would be that https://github.com/godotengine/godot/blob/d6f972fad45d28222b1437a047241dd74f0d5b90/scene/main/window.cpp#L284 gets called and finally sets the right position for the window.

Could it be that a call to that is being "skipped" with the repro steps described in the comments above?

**Comment by nathanfranke** [comment]
Still reproducible somewhat on v4.0.alpha.custom_build [afdae67cc], only in single window mode

On my left monitor (1080p):

![image](https://user-images.githubusercontent.com/14253836/176794710-ee5b67eb-f04b-4248-94b6-b0089c14b225.png)
![image](https://user-images.githubusercontent.com/14253836/176794714-ecce3f03-1f3b-4f27-9123-387dd57f8ab1.png)

On my middle monitor (1440p):

![image](https://user-images.githubusercontent.com/14253836/176794734-84ec90e4-2de9-445c-915c-476d86d35ace.png)
![image](https://user-images.githubusercontent.com/14253836/176794740-8ec8fee3-7615-4d9e-b1c0-c20b229cb0fd.png)

Menus are always displayed correctly for me though:
![image](https://user-images.githubusercontent.com/14253836/176794881-3c5efa6e-4b5b-4dae-a0b6-eda44a32f7c3.png)

---

Project manager is also offset, but not by the same offset as any of the tooltips

![image](https://user-images.githubusercontent.com/14253836/176794931-c6da1256-84e2-4187-956f-58fbd967cca5.png)
