### ISSUE TITLE
[Godot 4] Character skin is broken

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#45760]
**Godot version:**
Godot Engine v4.0.dev.calinou.779dc7613

**OS/device including version:**
Windows 10 x64
Using Vulkan Device #0: AMD - AMD Radeon R7 200 Series

**Issue description:**
Importing fbx doesnt show any error message, but the model is messy.

This is the result of importing fbx:
![image](https://user-images.githubusercontent.com/58845030/107116957-ab470800-6855-11eb-9c96-abe255ebdc38.png)

Compared to GLB format:
![image](https://user-images.githubusercontent.com/58845030/107116949-979ba180-6855-11eb-8165-2b86f16fc71f.png)

**Steps to reproduce:**
* Import Fbx file

**Minimal reproduction project:**
[Project.zip](https://github.com/godotengine/godot/files/5936734/Project.zip)

**Comment by RevoluPowered** [comment]
Can you please let me know what the model was created in?

**Comment by nonunknown** [comment]
the original file is a .mesh file (XNA lara) https://www.deviantart.com/sticklove/art/Mileena-Dangerous-Allure-866594649

**Comment by RevoluPowered** [comment]
OK then the original FBX itself which is concerned in this ticket is related to blender's fbx exporter #44402

This is on the radar to be fixed, but we need to actually fix upstream blender exporter too.

**Comment by RevoluPowered** [comment]
#46525 
<img width="395" alt="Screenshot 2021-02-28 at 21 17 48" src="https://user-images.githubusercontent.com/748770/109433919-a7e50d80-7a0a-11eb-84b8-a448dd0c9721.png">

requires some more work to fix the keyframes but on the right track 🍰

**Comment by nonunknown** [comment]
Awesome, keep it up dude!!!

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
