### ISSUE TITLE
Is it possible to connect to a Websocket server?

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4577]
I have a gameserver (websocket, written in nodejs) that is around.. 20k lines of code :(. I was curious if Godot supports connecting to an HTTP server to make the Websocket handshake?  

I found [this](https://github.com/godotengine/godot/issues/4208), but not sure.

**Comment by bojidar-bg** [comment]
@Dillybob92 ~ BTW, it might be better to ask such questions on our [QA site](http://godotengine.org/qa/).

But still, since you asked, Godot supports connecting to HTTP servers via the HTTPClient and HTTPRequest classes. Also, if in any way they don't support websocket technology, you might open an issue for it, or just switch to a plain old TCP stream connection, which is supported as well :smile: .

**Comment by Dillybob92** [comment]
@bojidar-bg Awww, thanks. Good idea. I'll check out the classes and docs.

**Comment by jahd2602** [comment]
In case anyone is interested, I found this library:
https://github.com/marcosbitetti/Godot-Websocket
And the tutorial: https://www.youtube.com/watch?v=rMnUVm-4fEw
I didn't make it but plan to give it try these days.
