### ISSUE TITLE
Let there be a signal manager, please

### ISSUE THREAD

**Issue by azurvii** [godotengine/godot#4578]
**Operating system or device - Godot version:**
Mac OS X 10.11.3, Godot 2.0.2.stable.official

**Issue description** (what happened, and what was expected):
FR, not a bug.
I'd like to propose a feature which can manage all editor-managed signals in one place.

**Steps to reproduce:**
It looks like currently the only way to check connections I set up in the editor (not in script) is to go through each node and click the "edit connections" button. This is a nightmare if I have lots of connections made with editor from/to lots of nodes, and I'd like to edit/check on them.

**Link to minimal example project** (optional but very welcome):
N/A

**Comment by akien-mga** [comment]
I agree that something needs to be done to improve the usability of signals when bound via the GUI. At @KOBUGE-Games we're actually starting to bind all signals by script, so that they do throw an error when a function goes missing, what the GUI-bound signals won't do (they'll just throw a warning in the terminal). Changing the type of a node also makes it lose its signals (that would be #1461).

Having an overview of all signals (both GUI-bound and script-bound if possible) for the current scene would be a very nice feature indeed.

**Comment by StraToN** [comment]
Signal connections are both related to Nodes and script attached to Nodes.

Therefore, I think that the Signals panel should be moved from its current location to be displayed next to the script editor, so that all 3 information are displayed side-to-side:
- Scene tree (nodes)
- Script editor
- List of signals and connections

This panel would display the list of signals available and/or connected (*both* by script or by editor) to the node which the currently opened GDScript is attached to. And clicking any of them would focus the editor on the according function that manages this signal.

**Comment by neikeq** [comment]
Is this issue still relevant after 3ae61f2?

**Comment by StraToN** [comment]
@neikeq I think it can be closed.
