### ISSUE TITLE
Possible glitch? debugger warnings about animation player

### ISSUE THREAD

**Issue by RebelliousX** [godotengine/godot#4580]
**Operating system or device - Godot version:**
W10, Latest nightly as of writing this. Both x64.

**Issue description** (what happened, and what was expected):
Everything works as intended when I run the project, except for the incomprehensible debugger
warnings. All animations work fine.
![warnings](https://cloud.githubusercontent.com/assets/1888186/15096531/981994f0-14c2-11e6-964a-e84e134f0c46.png)

I don't know if I am not supposed to "key" visibility for Sprites that are or are not visible! But I need to do that for the animation sequence to happen correctly. But warnings are for visible and non-visible sprites are there. Should I just ignore this?

Why is the path backwards in the tooltip? It is the reverse of what is in Scene viewer.

Please feel free to close this issue if it is not a bug. But an explanation about this would be appreciated.

Note: If I press WinKey (Super) + Home, myriads of warnings and errors gets logged within seconds. And I don't think they are related to anything I did. (exceptions in CPP code and their line numbers).

**Comment by bojidar-bg** [comment]
Maybe yet another `tscn`-related bug?

**Comment by volzhs** [comment]
@bojidar-bg possibly
@RebelliousX Any other issue when close scene and reopen it?

**Comment by neikeq** [comment]
Seems to be a `tscn` bug indeed.

**Comment by neikeq** [comment]
The issue seems to be the same as #4579

**Comment by reduz** [comment]
I checked this and #4579 and i honestly can't understand what's going on. The mentioned error happens when you place a node from the current scene as a child of a node of an inherited or instanced scene... then the place (parent) of that node where it was instanced is removed.

Maybe in such case, this is what happens and what is leading to the warning? If so, then there is nothing much to do about this, just re-save the scene and the error will be gone..
