### ISSUE TITLE
Colliding Rigidbody2Ds cause FPS drop even if their masks/layers don't match

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45824]
**Godot version:**

3.2.4 rc1

**Minimal reproduction project:**

[rigidbody_mask_bug.zip](https://github.com/godotengine/godot/files/5943816/rigidbody_mask_bug.zip)
Compare Slow.tscn and NotSlow.tscn. In both the collision layers/masks are set to 0, but if the bodies are colliding, there is an extreme FPS drop.

**Comment by HenryWConklin** [comment]
From some quick profiling, looks like the culprit is `BroadPhase2DHashGrid::_check_motion`
```
  14.91%  godot.linuxbsd.  godot.linuxbsd.tools.64             [.] BroadPhase2DHashGrid::_check_motion
  10.23%  godot.linuxbsd.  godot.linuxbsd.tools.64             [.] Rect2::intersects
   8.04%  godot.linuxbsd.  godot.linuxbsd.tools.64             [.] CollisionObject2DSW::test_collision_mask
```
Looks like it's not short-circuiting on the collision masks, so it's always checking the AABB collisions:
https://github.com/godotengine/godot/blob/2abe996414b8b551e69e29461de3ff1bcaf5a28f/servers/physics_2d/broad_phase_2d_hash_grid.cpp#L72-L92
