### ISSUE TITLE
ColorPicker with Hsv Mode enabled in the inspector displays RGB labels but still acts as HSV

### ISSUE THREAD

**Issue by ShatReal** [godotengine/godot#45832]
**Godot version:**

3.2.4.rc1.official

**OS/device including version:**

Windows 10

**Issue description:**

A ColorPicker with HSV mode on displays the text labels "R" "G" "B" when running the scene (in editor it displays HSV). Toggling HSV mode on and off in the scene resets the text.

**Steps to reproduce:**
1. Make ColorPicker
2. Click on for hsv mode
3. Run scene
4. Observe

**Minimal reproduction project:**

**Comment by Calinou** [comment]
I can reproduce this on 3.2.3. Note that this only happens if you check **Hsv Mode** in the ColorPicker node properties, not if you enable HSV mode in the running project.

**Minimal reproduction project:** [test_color_picker.zip](https://github.com/godotengine/godot/files/5945706/test_color_picker.zip)
