### ISSUE TITLE
Ability to extend base scene script easily for inherited scenes

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#4585]
**Issue description** (what happened, and what was expected):
When we are creating new inherited scene, it would be cool if we could have an option to automatically create script that's extending base scene script. I think this extended script could be saved in the same location where inherited scene is saved, under the same name but with gd extension.
Simple switch, something like "create extended script: on/off" inside this dialog window in which we are pointing base scene, would be enough. 

**related issue:** https://github.com/godotengine/godot/issues/4584

**Comment by MarianoGnu** [comment]
I belive an option on contextual menu is enought for this
If no script:
-create script
If has script
-edit script
-extend script

**Comment by kubecz3k** [comment]
@MarianoGnu yeah https://github.com/godotengine/godot/issues/4584 is about this.

**Comment by kubecz3k** [comment]
If anyone is interested in this, I made a plugin that adds 'inherit node' button. It's called 'Smart scene extender' and is available via asset store.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
