### ISSUE TITLE
Cannot type dead keys (accented characters) or use Input Method Editor on a LineEdit exported to HTML

### ISSUE THREAD

**Issue by ofrias** [godotengine/godot#45904]
**Godot version:**
 Godot v3.2.3

**OS/device including version:**
MacOS exporting to HTML

**Issue description:**
Cannot type dead keys (needed to enter accented characters) inside a LineEdit which has been exported to HTML.

**Steps to reproduce:**
1) Open this project:
https://origamer.itch.io/ortografiator
2) Try to enter any accented character in the input field (a LineEdit).  When you press the dead key (for example ^ or ' or ` or ") nothing will happen, and when you press the vowel key it will appear as a standard vowel, without the accent.

**Minimal reproduction project:**
Any project with a LineEdit.

**Comment by Calinou** [comment]
cc @Faless

**Comment by ofrias** [comment]
@Calinou Spanish layout.

I have been testing accessing the HTML page on different computers and these are the results:
- Mac:  affected
- Linux:  affected
- Windows:  NOT affected
- iPad with a external keyboard:  NOT affected  (the virtual keyboard does not work, but this is another issue...)

This seems to be OS related and independent of the browser, because all tested browsers fail in the affected systems, and none of the browsers tested on the non-affected systems fail.

**Comment by Faless** [comment]
This is due to limitation in web standards.
We would need to focus an hidden `input` element (IME-like) to make it work (but that could cause focus issues when navigating the canvas).
In `3.3` enabling `Experimental Virtual Keyboard Support` should allow you to input dead keys in TextEdit(s)/LineEdit(s)

**Comment by ofrias** [comment]
Thanks for your reply but I don't understand how this is related to web standards.  Other keys work OK, and on Windows even dead keys work...

**Comment by Faless** [comment]
> Thanks for your reply but I don't understand how this is related to web standards. Other keys work OK, and on Windows even dead keys work...

Because different OSes uses different methods for handling dead keys, and because composition events are not fired on canvas. https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent

**Comment by Faless** [comment]
> Because different OSes uses different methods for handling dead keys, and because composition events are not fired on canvas.

To expand a bit on this...
When I spent few days on this topic last month, I found out the following inconsistencies:

- Different browsers reported different values of [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) when the event was fired from a `canvas` instead of an `input`/`textarea`.
- The preferred method for handling [IME](https://en.wikipedia.org/wiki/Input_method) (which in most OSes includes dead keys) is using the CompositionEvent(s) mentioned above, [according to the spec](https://w3c.github.io/uievents/#events-compositionevents).
- CompositionEvent(s) do not fire on `canvas` element at all, and I found no way to tell the browser to fire them on the canvas.
- As you might have noticed from the "Editor's Draft" status of the spec, the whole standard is not finalized yet (like for most web standards), and the implementation status varies across browsers and OSes.

That said, if anyone finds a reliable way to detect special keys inserted via dead keys from a `canvas`, in a way that does not interfere with regular input handling in a game (i.e. allows detecting `keydown`/`keyup` correctly), I'll gladly help integrating it in Godot, and it would be certainly a great contribution.

**Comment by ofrias** [comment]
Maybe you could use KeyboardEvent.code instead of KeyboardEvent.key ?

This is the output when typing `Rosalía` on Firefox on Ubuntu with a Spanish keyboard layout on [this canvas](https://jsfiddle.net/ucofbrpk/):

```
Shift, ShiftLeft
R, KeyR + shiftKey
o, KeyO
s, KeyS
a, KeyA
l, KeyL
Dead, Quote
i, KeyI
a, KeyA
```

While on Chrome on Windows I get this:

```
Shift, ShiftLeft + shiftKey
R, KeyR + shiftKey
o, KeyO
s, KeyS
a, KeyA
l, KeyL
Dead, Quote
í, KeyI
a, KeyA
```

This is why the issue does not affect Windows, because in this case KeyboardEvent.key contains the composed output (í instead of i)

Do you have a way to combine several keys (KeyboardEvent.code) into the corresponding output taking into account the user keyboard layout?  (note that the KeyboardEvent.code returns the physical key pressed, independently of the keyboard layout).

**Comment by Faless** [comment]
> note that the KeyboardEvent.code returns the physical key pressed, independently of the keyboard layout

Exactly, that's why we can't use `code` for getting the actual UTF8, we need to use KeyboardEvent.key, but that doesn't seem to report the right value across different browsers/OSs when the target is a canvas.

**Comment by Calinou** [comment]
Physical scancodes were added to 4.0 by https://github.com/godotengine/godot/pull/18020.

**Comment by Eranot** [comment]
Looks like this is still happenning on Godot 4.0 and 4.0.1

**Comment by Eranot** [comment]
So, I've being studying this problem for some days. Like @Faless said, I don't think there is a way to make canvas use CompositionEvents. I've tried a lot of ways, but none of them worked.

That being said, looks like the option we have is to use a hidden input, as commented by Fabio. I made a little proof of concept here to test this out, and it looks like it works fine, just has to be polished (the code right now is absolutely awful). 

The gif below shows how it is working right now.

![Peek 2023-03-23 21-25](https://user-images.githubusercontent.com/13923596/227392962-b1a3ee63-5cef-4a9e-a4bb-66bb10f8eba1.gif)

That being said, does it look like this is a viable option?

**Comment by timothyparez** [comment]
Not sure whether or not this is related but when I export a project to HTML5  
I can no longer input Chinese characters.  

- Godot 3.5
- Ubuntu 
- Firefox/Edge

**Comment by LaneSun** [comment]
Maybe we can make a web only function like `OS.request_web_ime` to manully trigger a hidden text input to handle this?

From my point, it's important to make web export able to use IME, but with the current web standard it's not possible to achieve it with any other approach.

**Comment by Faless** [comment]
There is a pending PR (linked above) implementing this using a hidden element: https://github.com/godotengine/godot/pull/79362 .
It needs a rebase, and some more testing.
