### ISSUE TITLE
Godot 3.2 branch crashes when using VR plugins (regression)

### ISSUE THREAD

**Issue by BastiaanOlij** [godotengine/godot#45952]
**Godot version:**
Godot 3.2.4 83e4e4dc52f37ea6a093ba72b2790aecdae502a5

**OS/device including version:**
Any

**Issue description:**
Due to #44617 Godot now crashes when using VR plugins as these implement functionality that is not solely using NativeScript. 
I think this code needs to listen to the `reloadable=false` setting for the library which was added to prevent the reloading the editor did for exactly this same crashing issue.

**Steps to reproduce:**
Run any VR project that uses the OpenVR or OpenXR plugins. The others may be effected but not 100% sure.

**Comment by BastiaanOlij** [comment]
@geekrelief feedback would be welcomed here :)

**Comment by geekrelief** [comment]
I'm not familiar with godot and VR.  I can't really offer useful suggestions without understanding what you're trying to do or the nature of the crash. Do you have a sample project or a stacktrace of the error?

So forgive me if you're already familiar with this stuff, but I'm just going over my understanding of godot. But the first thing that comes to mind is how/why are calls being made to a GDNative library when there should be no script references to it if the library was terminated?  Do you have some changes on the engine side? My change to free the gdnative library was to  bring it in line with how other subclasses of `Reference` are freed when nothing references it. 

Before my patch, when all references in my app were removed the GDNative library was still in memory.  So while having the library cached might be useful, we can never free it. For hot reloading, the dll is locked on Windows preventing us from overwriting it.  My change should only affect the app at runtime since the editor always holds references to scripts as far as I've seen.

I tried your suggestion of checking for the `reloadable` like this:
```cpp
			Map<String, Ref<GDNative> >::Element *G = library_gdnatives.find(script->lib_path);
			if (G && G->get()->get_library()->is_reloadable()) {
				G->get()->terminate();
				library_gdnatives.erase(G);
			}

```
And `default_reloadable` is set to true in gdnative.ccp .  So it wouldn't make a difference in my use case. Does checking `reloadable` still makes sense for you?

**Comment by BastiaanOlij** [comment]
@geekrelief Indeed that is the solution I already made a PR for. The reloadable flag was actually introduced for that purpose. I think that is the right solution so people can chose either behavior in a meaningful way.

For your understanding, VR uses more closely integrated calls into the plugin from the render engine that do not involved GDnative script classes. While we do use those in some of the plugins for additional features, the core solution does not. 
Instead the plugin populates this struct with callbacks:
https://github.com/godotengine/godot/blob/master/modules/gdnative/include/xr/godot_xr.h#L47
These functions are called directly from `ARVRInterfaceGDNative` (the interface being what is used directly by the render engine).

So in this case the ARVRInterface instance was still kicking around, was still being called and still making calls into the plugin, while the plugin was unloaded.

I think the video encoder API and plugin script API use similar approaches as well and may also not behave nicely if the library is unloaded just because there are no more script class instances. The GDNative script classes are a part of what GDNative can do.
