### ISSUE TITLE
Collision detection unreliable with KinematicBody2D inside CollisionPolygon2D

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#45971]
**Godot version:**

3.2.4 rc2

**Issue description:**

So I discovered that collision with polygons broke somewhere between beta5 and beta6.

Test code:
```
func _physics_process(delta: float) -> void:
	$KinematicBody2D.global_position = get_global_mouse_position()
	if $KinematicBody2D.test_move($KinematicBody2D.get_global_transform(), Vector2.DOWN):
		$KinematicBody2D.modulate = Color.red
	else:
		$KinematicBody2D.modulate = Color.white
```
3.2.4 beta5
![qFmKJfTxLT](https://user-images.githubusercontent.com/2223172/107859225-492f6980-6e38-11eb-8c01-2c71ce8d41bf.gif)
3.2.4 beta6 and newer
![e16dBiPznp](https://user-images.githubusercontent.com/2223172/107859235-53516800-6e38-11eb-8fed-ee510c719044.gif)

**Minimal reproduction project:**

[ReproductionProject.zip](https://github.com/godotengine/godot/files/5976294/ReproductionProject.zip)

**Comment by akien-mga** [comment]
CC @godotengine/physics

**Comment by akien-mga** [comment]
This seems to be caused/exposed by #42575 (tested a local revert to confirm).

**Comment by KoBeWi** [comment]
I just discovered another broken case with CollisionShape2Ds not polygons. I assume the cause is the same though.

**Comment by pouleyKetchoupp** [comment]
@KoBeWi Thanks for catching these regressions! If it's easy enough, I'm interested in a MRP for your other case to help with testing when we have a fix.

**Comment by KoBeWi** [comment]
Here's repro for the CollisionShape2D issue:
[ReproductionProject.zip](https://github.com/godotengine/godot/files/5992511/ReproductionProject.zip)
Use left/right to move "player". The drops will pass through you when you approach them from side, while previously it would properly detect collision.
![3A6yfvsNgo](https://user-images.githubusercontent.com/2223172/108140947-15b43f80-70c3-11eb-814b-348f2e190abd.gif)

**Comment by madmiraal** [comment]
This is not a regression, rather #42575 has fixed a bug in `move_and_collide()` that is used by `test_move()`, which was being abused in the MRPs: `test_move()` is being used to test for a collision but `move_and_collide()` is not being used to move the bodies.

What is happening is `move_and_collide()` (and `test_move()`) first moves the body to a safe location, and then attempts the move. The bug that #42575 fixed was that the body was not first being successfully moved to a safe location; so all moves would result in a collision (see #34242). In the MRPs, in 3.2.3, the bodies are not being successfully moved to a safe location; so any move results in a collision. When `move_and_collide()` is not used to subsequently move the body, this initial move to a safe location is not seen.

With #42575, the bodies are now first being successfully moved to a safe location. In the original MRP, when the safe location is, to the bottom or right-hand edges of the `Polygon2D`, a downward move is possible without a collision. So
```$KinematicBody2D.test_move($KinematicBody2D.get_global_transform(), Vector2.DOWN)``` returns false.
However, since `move_and_collide()` is not used to move the body (the position of the mouse is used to move the body) this move to a safe location outside the `Polygon2D` is not seen.

Likewise, with the drops MRP. When the safe location is to the left or right edge of the player, the drop can move down without a collision, so `test_collision()` returns `false` and the drop is not destroyed:
```
if test_move(global_transform, Vector2.DOWN * fall * delta):
    queue_free()
```
Again, this displacement is not seen, because `move_and_collide()` is not used to move the body, rather the position is updated directly:
```position.y += fall * delta```

In the scenarios presented in the MRPs, instead of using `test_move()`, `Physics2DDirectSpaceState`'s [`cast_motion()`](https://docs.godotengine.org/en/stable/classes/class_physics2ddirectspacestate.html#class-physics2ddirectspacestate-method-cast-motion) should be used.

**Comment by KoBeWi** [comment]
Well, then it's compatibility breakage. Also I looked at `cast_motion()` and it looks like I'm supposed to set all the parameters myself, which is much less convenient than `test_move()`.

Maybe `move_and_collide()` should internally use a different version of `test_move()` (e.g. `test_move_safe()`) and `test_move()` could be reverted to the old behavior?
