### ISSUE TITLE
Mutex does not lock

### ISSUE THREAD

**Issue by jcribeirooo** [godotengine/godot#46084]
I have a Singleton Node script.
In the initialization script I try to do the following:

```
func _init():
    print("point a")
    var mutex = Mutex.new()
    mutex.lock()
    mutex.lock()
    print("point b")
```

The code above should never reach to point b, but it just ignores the Mutex.

**Comment by mbrlabs** [comment]
You should fill out the issue template since Mutexes are implemented differently on each platform and Godot version. 

If you are on Windows for example Godot uses [WaitForSingleObject](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject) to acquire a mutex. According to the [docs ](https://docs.microsoft.com/de-de/windows/win32/sync/mutex-objects) the wait-funtions can be called on the same thread multiple times without blocking if it already has ownership of the mutex. 
I don't know how this behaves on other platforms though. That said i think i recently saw @RandomShaper implement threads and mutexes using the C++11 standart lib (for 3.2 and master)

**Comment by RandomShaper** [comment]
@mbrlabs is right. Mutexes in Godot are expected to be recursive, so a single thread can lock multiple times without unlocking.

I'd close this as no bug and only reopen in case something can be added that actually means there's a bug.

**Comment by akien-mga** [comment]
Is it properly documented in the Mutex class reference? If so this can indeed be closed.

**Comment by RandomShaper** [comment]
It isn't, neither in 3.2 nor _latest_.
