### ISSUE TITLE
Executing `OS.open_midi_inputs()`  crashes Godot

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#46183]
**Godot version:**
Godot 3.2.4 rc 2

**OS**
Ubuntu 20.04 - Ubuntu 3.36 X11

**Issue description:**
Executing
```
func _process(_delta : float) -> void:
	if randi() % 2 == 0:
		print("Executing OS::open_midi_inputs")

		OS.open_midi_inputs()
```

crashes with backtrace(address sanitizer doesn't show anything)
```
Executing OS::open_midi_inputs
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x172e07a] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fc3f2fdd210] (??:0)
-- END OF BACKTRACE --
Aborted (core dumped)
```

**Comment by Ovnuniarchos** [comment]
Confirmed on commit 94a0fc47f.
System: Debian SID

**Comment by waimus** [comment]
I also experienced crash simply by running `OS.open_midi_inputs()` with log:
```
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] /lib/x86_64-linux-gnu/libc.so.6(+0x41950) [0x7fe672508950] (??:0)
-- END OF BACKTRACE --
```

The last change of AlsaMIDI driver [(/drivers/alsamidi/midi_driver_alsamidi.cpp)](https://github.com/godotengine/godot/blob/master/drivers/alsamidi/midi_driver_alsamidi.cpp) was on commit 99fe462/[direct link to file difference](https://github.com/godotengine/godot/commit/99fe462452be44efa618e83ad9bbecd722ae6ecd#diff-a4930f40d02bab378257ddbdf5f17caa2f73187702649eb9f2b80bae6b2fbaa9). So I tested one commit before 99fe462 that happened in the same day, which was commit c4a2fe9 and the `OS.open_midi_input()` is working fine.

Since commit 99fe462 is only modified the Alsa MIDI driver, the rest of CoreMIDI and WinMIDI driver does not affected. But I haven't got any confirmation or able to test if OS.open_midi_inputs() crashes on Mac and Windows.

Other than this report I am unable to figure out what other files that may be related to `OS.open_midi_inputs()`.

**Comment by 20kdc** [comment]
Issue still present in Godot 3.3.2.stable Linux 64-bit as gotten from itch.io

**Comment by aki-cat** [comment]
@akien-mga hey, I'm having this issue and just saw you merged a fix for 3.4
is there a current workaround for this on 3.3.2?

**Comment by qarmin** [comment]
No, you need to wait for `3.3.3` or compile it by yourself

**Comment by abhinav3967** [comment]
[MIDIBUG.zip](https://github.com/godotengine/godot/files/6986092/MIDIBUG.zip)
