### ISSUE TITLE
Master mono binary crash on macOS

### ISSUE THREAD

**Issue by gitcatrat** [godotengine/godot#46238]
**Godot version:** master ([last commit](https://github.com/godotengine/godot/commit/dc1ae065578baee102d461353c757ebf2cc5cf8c))

**OS/device including version:** macOS Catalina 10.15.6

**Issue description:**

Running complied glue executable crashes with the followinng error:
```
Generating VisualScriptEditor.cs...
The Godot API sources were successfully generated
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: recursive_mutex lock failed: Invalid argument
```

**Steps to reproduce:**
* `git clone`
* `cd godot`
* `scons p=osx tools=yes module_mono_enabled=yes mono_glue=no`
* `./bin/godot.osx.tools.64.mono --generate-mono-glue modules/mono/glue`

**Comment by akien-mga** [comment]
Possibly related to Mutex changes? @RandomShaper @hpvb

**Comment by RandomShaper** [comment]
Could we get a stack trace?

**Comment by gitcatrat** [comment]
@RandomShaper Feel free to ask more info if required. https://pastebin.com/tY01BDjy

**Comment by RandomShaper** [comment]
My hypothesis is that it's due to the destruction order of some globals/statics.

Specifically, `StringName::mutex` and `ClassDB::default_values`.

@gitcatrat, could you please try the following to help me confirm?:

Add this before the last `::exit(0);` in the `modules\mono\editor\bindings_generator.cpp`:
`ClassDB::cleanup_defaults();`

If this is true, we'd know that the way the engine is being shutdown is too aggressive. Before the MT rewrite, the static mutex in `StringName` would just be leaked, but not it's no longer a pointer, we can no longer do things that way (maybe just a patch similar to the suggested change would be enough).

**Comment by gitcatrat** [comment]
@RandomShaper I'll try it at once but I have to do a restart. This is necessary after every described Godot crash, Mac terminal gets stuck at login phase and Activity Monitor never recovers from unresponsive so I can't force close any login/terminal related tasks. Not sure if Mac has any other means to fix this state but I've found restart to be the only way.

**Comment by gitcatrat** [comment]
1. Modified `bindings_generator.cpp`:
```cpp
// Exit once done
ClassDB::cleanup_defaults();
::exit(0);
```
2. `scons p=osx tools=yes module_mono_enabled=yes mono_glue=no`
3. `./bin/godot.osx.tools.64.mono --generate-mono-glue modules/mono/glue`

Same error unfortunately. 

Second step was 100x faster but I don't know anything about C++, probably only recompiles changed/dependency files?

**Comment by RandomShaper** [comment]
Thank you for testing. It was worthy to give it a try, but I'll have to look deeply into it myself.

I don't know what to say about the unrecoverable state you get after the crash. Sounds quite weird.

Regarding the build process, your assumptions were right: calling scons again was needed, and it's much faster because the build system only recompiles what has changed (and, in their case, files that are indirectly affected by the changes).
