### ISSUE TITLE
Mesh Data Tool Functions broken

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#46294]
Related to: https://github.com/godotengine/godot/issues/27508

**Godot version:**

3.2.3 stable, 3.2.4 RC2

**OS/device including version:**

W10 64-bit

**Issue description:**

Example (in MRP): A vertex that has 5 edges and 5 faces connected to it outputs only 2 edges and 1 face with get_vertex_edges() and get_vertex_faces()

**Steps to reproduce:**
Create a Cube in Blender and import it in Godot
Create MeshDataTool and create surface from the mesh
Get any Vertex Edges or Faces, or get any edge Faces, or get any face edges and the output is wrong (incomplete data)

**Minimal reproduction project:**

[MDT.zip](https://github.com/godotengine/godot/files/6018220/MDT.zip)

**Comment by kleonc** [comment]
I don't see a bug here. Seems like there's a misconception of what a vertex is.  Vertex is not just a position, it's a set of properties (a vertex data, position is only one its components). This cube has 24 different vertices, not 8 (because for each corner there are 3 different vertices, each with the same position but with the different normal).


<details>
<summary>Example debug output from your MRP showing everything is fine (click to expand).</summary>

This:
```
extends MeshInstance

var MDT = MeshDataTool.new()

func _ready():
	MDT.create_from_surface(mesh, 0)

	for i in range(MDT.get_vertex_count()):
		print("v%-2d: p%-15s n%-15s f:%-15s e:%-15s" % [ i, MDT.get_vertex(i), MDT.get_vertex_normal(i), MDT.get_vertex_faces(i), MDT.get_vertex_edges(i) ])

	print()	
	for i in range(MDT.get_edge_count()):
		print("e%-2d: v%-2s v%-2s" % [ i, MDT.get_edge_vertex(i, 0), MDT.get_edge_vertex(i, 1) ])

	print()
	for i in range(MDT.get_face_count()):
		print("f%-2d: v%-2s v%-2s v%-2s  n%-15s" % [ i, MDT.get_face_vertex(i, 0), MDT.get_face_vertex(i, 1), MDT.get_face_vertex(i, 2), MDT.get_face_normal(i) ])
```
Prints:
```
v0 : p(-1, 1, 1)      n(-1, 0, 0)      f:[0]             e:[0, 2]         
v1 : p(-1, -1, 1)     n(-1, 0, 0)      f:[0, 1]          e:[0, 1, 3]      
v2 : p(-1, 1, -1)     n(-1, 0, 0)      f:[0, 1]          e:[1, 2, 4]      
v3 : p(-1, -1, -1)    n(-1, 0, 0)      f:[1]             e:[3, 4]         
v4 : p(-1, 1, -1)     n(0, 0, -1)      f:[2]             e:[5, 7]         
v5 : p(-1, -1, -1)    n(0, 0, -1)      f:[2, 3]          e:[5, 6, 8]      
v6 : p(1, 1, -1)      n(0, 0, -1)      f:[2, 3]          e:[6, 7, 9]      
v7 : p(1, -1, -1)     n(0, 0, -1)      f:[3]             e:[8, 9]         
v8 : p(1, 1, -1)      n(1, 0, 0)       f:[4]             e:[10, 12]       
v9 : p(1, -1, -1)     n(1, 0, 0)       f:[4, 5]          e:[10, 11, 13]   
v10: p(1, 1, 1)       n(1, 0, 0)       f:[4, 5]          e:[11, 12, 14]   
v11: p(1, -1, 1)      n(1, 0, 0)       f:[5]             e:[13, 14]       
v12: p(1, 1, 1)       n(0, 0, 1)       f:[6]             e:[15, 17]       
v13: p(1, -1, 1)      n(0, 0, 1)       f:[6, 7]          e:[15, 16, 18]   
v14: p(-1, 1, 1)      n(0, 0, 1)       f:[6, 7]          e:[16, 17, 19]   
v15: p(-1, -1, 1)     n(0, 0, 1)       f:[7]             e:[18, 19]       
v16: p(1, -1, -1)     n(0, -1, 0)      f:[8]             e:[20, 22]       
v17: p(-1, -1, -1)    n(0, -1, 0)      f:[8, 9]          e:[20, 21, 23]   
v18: p(1, -1, 1)      n(0, -1, 0)      f:[8, 9]          e:[21, 22, 24]   
v19: p(-1, -1, 1)     n(0, -1, 0)      f:[9]             e:[23, 24]       
v20: p(-1, 1, -1)     n(0, 1, 0)       f:[10]            e:[25, 27]       
v21: p(1, 1, -1)      n(0, 1, 0)       f:[10, 11]        e:[25, 26, 28]   
v22: p(-1, 1, 1)      n(0, 1, 0)       f:[10, 11]        e:[26, 27, 29]   
v23: p(1, 1, 1)       n(0, 1, 0)       f:[11]            e:[28, 29]  

e0 : v0  v1 
e1 : v1  v2 
e2 : v0  v2 
e3 : v1  v3 
e4 : v2  v3 
e5 : v4  v5 
e6 : v5  v6 
e7 : v4  v6 
e8 : v5  v7 
e9 : v6  v7 
e10: v8  v9 
e11: v9  v10
e12: v8  v10
e13: v9  v11
e14: v10 v11
e15: v12 v13
e16: v13 v14
e17: v12 v14
e18: v13 v15
e19: v14 v15
e20: v16 v17
e21: v17 v18
e22: v16 v18
e23: v17 v19
e24: v18 v19
e25: v20 v21
e26: v21 v22
e27: v20 v22
e28: v21 v23
e29: v22 v23

f0 : v0  v1  v2   n(-1, 0, 0)     
f1 : v2  v1  v3   n(-1, 0, 0)     
f2 : v4  v5  v6   n(0, 0, -1)     
f3 : v6  v5  v7   n(0, 0, -1)     
f4 : v8  v9  v10  n(1, -0, 0)     
f5 : v10 v9  v11  n(1, 0, 0)      
f6 : v12 v13 v14  n(0, 0, 1)      
f7 : v14 v13 v15  n(0, -0, 1)     
f8 : v16 v17 v18  n(0, -1, 0)     
f9 : v18 v17 v19  n(0, -1, 0)     
f10: v20 v21 v22  n(0, 1, 0)      
f11: v22 v21 v23  n(0, 1, 0)    
```
</details>

The cause of such misconception is probably the fact that "vertex" is often used with the meaning "vertex position" (for example in `MeshDataTool` there are `get_vertex`, `set_vertex` which should rather be called `get_vertex_position`, `set_vertex_position` to be explicit).

**Comment by clayjohn** [comment]
I think what OP is looking for is a function to "weld" vertices together that share vertex positions.

**Comment by mrjustaguy** [comment]
Please read https://github.com/godotengine/godot/issues/27508#issuecomment-524511970
It clearly states the correct behavior should be getting all the edges of a given vertex, that aren't just of one of the triangles it belongs to, but of others too. When I saw that I opened this and closed the proposal that would "weld" the vertices as the expected behavior seems to be what it'd be with a "weld" option available.

**Comment by kleonc** [comment]
> Please read https://github.com/godotengine/godot/issues/27508#issuecomment-524511970
It clearly states the correct behavior should be getting all the edges _**of a given vertex**_, that aren't just of one of the triangles it belongs to, but of others too.

And that's what the current behaviour is. Again: you're expecting different vertices with the same position to be treated like they're the same, single vertex (which is not the case). Also note that the comment you've linked is written by the person who fixed that linked issue (problem mentioned there is already properly solved).

Although the current behaviour is technically correct, I see what you're after and it does make sense to define edges by their endpoints (vertex positions) instead of by the actual vertices. Such change would make mentioned cube have 18 instead of 30 edges (edges connecting cube sides wouldn't be doubled). The problem is that such change would require changes in the `MeshDataTool` API which would break compatibility and thus it can't be done for the 3.2 branch. For example `MeshDataTool::get_edge_vertex` returning an index of an actual vertex would no longer make sense since edge would be defined by the vertex positions and each of these vertex positions could be associated with many actual vertices.

A different approach could be preserving current behaviour of all `MeshDataTool` methods and extending its API by adding a bunch of new methods for welded vertices and welded edges (not sure if welding faces makes sense). This way, based on your needs, you could deal either with the edges defined by the actual vertices (currently exposed methods) or with the edges defined by the vertex positions (potential new methods). Such enhancement could be added for 3.2 branch.

Anyway, these are just my thoughts. There are many different approaches of dealing with the welded/merged vertices and it should probably be discussed how (and if) it could be introduced into `MeshDataTool`.

**Comment by Zireael07** [comment]
Welding could be implemented without breaking compat just by having an optional weld bool parameter that defaults to false.

Incidentally I would expect the same behavior as @mrjustaguy (i.e. welded)

**Comment by mrjustaguy** [comment]
Ok yea I see how I misunderstood the comment I linked that gave me the basis to think of this as not intended behavior.. At first I Opened a Proposal with the idea of generating a welded set, but when I stumbled upon that comment it looked like a bug that someone attempted to fix and not expected behavior in any way.. 😆 

Closing as this is after all intended behavior, and reopening https://github.com/godotengine/godot-proposals/issues/2272 for creating the option to have a welded data set available
