### ISSUE TITLE
Cannot to reset or delete shortcut in Editor Settings

### ISSUE THREAD

**Issue by dalexeev** [godotengine/godot#46298]
**Godot version:**
4.0-dev

**OS/device including version:**
Kubuntu 20.10

**Issue description:**
After #44181, it became impossible to reset or delete shortcut in the Editor Settings, because when you click on these icons, the Event Configuration window appears. 

**Steps to reproduce:**
![](https://user-images.githubusercontent.com/47700418/108637693-b7a9a280-749c-11eb-95a8-f63a31b6dfb9.gif)

**Minimal reproduction project:**
—

**Comment by Calinou** [comment]
cc @EricEzaM

**Comment by EricEzaM** [comment]
Hello, I would be careful about saying "all platforms" if you cannot test that - looks like you are on Linux.

Working fine on Windows, although it is a bit laggy. I will have to look at the performance and see if it is just because it's in debug or if there is something slowing it down in the logic.

![D4xQ0yQteW](https://user-images.githubusercontent.com/41730826/108639368-ee54dc80-74df-11eb-800d-b44bbaac832c.gif)

**Comment by EricEzaM** [comment]
@dalexeev I don't have a way of testing Linux at the moment. If you have the time and interest, perhaps you could try?

Here is the callback method for a tree button being pressed. The index of the button determines which option to execute in the switch statement. Since it is always defaulting to editing the event, there could be soemthing going wrong in this section of code. 

https://github.com/godotengine/godot/blob/54a1b0a2a4d7fbe6385b8ee1e0587da3b1f6115d/editor/action_map_editor.cpp#L784

**Comment by KoBeWi** [comment]
Fixed by #47596
