### ISSUE TITLE
Real-time lights on lightmapped surfaces with bake mode "All" are only disabled in GLES2, not GLES3

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#46332]
*Continued from https://github.com/godotengine/godot/pull/41629.*

**Godot version:** `3.2` Git 4f891b706

**OS/device including version:** Fedora 33, GeForce GTX 1080 (NVIDIA 460.39)

**Issue description:**

Real-time lights on lightmapped surfaces with bake mode "All" are only disabled in GLES2, not GLES3. This happens regardless of which renderer was used at the time of lightmap baking. Texture atlases are only used when baking in GLES3, but this bug is also visible when using lightmaps baked without texture arrays in GLES3.

We should fix this so that the behavior in GLES3 is identical to GLES2.

**Steps to reproduce:**

Edit the minimal reproduction project and switch it to GLES3 using the dropdown in the top-right corner.

### DirectionalLight visible

![image](https://user-images.githubusercontent.com/180032/108773696-0881cf80-755f-11eb-871e-176f831122be.png)

### DirectionalLight hidden

![image](https://user-images.githubusercontent.com/180032/108776641-f30ea480-7562-11eb-94f2-95953ba84ca7.png)

### DirectionalLight visible

![image](https://user-images.githubusercontent.com/180032/108773492-b8a30880-755e-11eb-8d57-48c6724ca0b6.png)

### DirectionalLight hidden

![image](https://user-images.githubusercontent.com/180032/108773511-c0fb4380-755e-11eb-9560-46a63f5b1a9f.png)

**Minimal reproduction project:** [test_lightmap_shadow.zip](https://github.com/godotengine/godot/files/6025308/test_lightmap_shadow.zip)

**Comment by Janders1800** [comment]
I don't know if this goes out of the reach of this report but I've found out a couple more problems.
- Dynamic cannot cast shadows onto baked (GLES2 and GLES3)
- BakedLight cells doesn't store environment lighting (Notice dynamic objects aren't affected by sky light)

GLES2:
![Screenshot from 2021-02-24 02-55-48](https://user-images.githubusercontent.com/27329423/108937752-22024480-764f-11eb-9f28-b7ebe47a7c64.png)
GLES3:
![Screenshot from 2021-02-24 03-00-51](https://user-images.githubusercontent.com/27329423/108937769-29295280-764f-11eb-885e-52d51ba4b2bf.png)


Array textures seems to work fine for me, since if I bake on GLES3 I get this error if I switch to GLES2.
![Screenshot from 2021-02-24 03-02-11](https://user-images.githubusercontent.com/27329423/108937835-4e1dc580-764f-11eb-9f9a-d3dd3f738898.png)

Here is a modified test project reflecting this problems.
[test_lightmap_shadow.zip](https://github.com/godotengine/godot/files/6032899/test_lightmap_shadow.zip)

**Comment by Calinou** [comment]
> Dynamic cannot cast shadows onto baked (Notice the sphere shadow gets cut off wen casting onto baked floor, this happens on GLES2, on GLES3 can't be tested due to original bug report)

By definition, this is impossible to do. We'd need to implement a subtractive shadowmapping option for DirectionalLight (no light is emitted, only a shadow is cast).

**Comment by Janders1800** [comment]
> We'd need to implement a subtractive shadowmapping option for DirectionalLight 

Why only for DirectionalLight?

**Comment by Calinou** [comment]
> Why only for DirectionalLight?

It can be implemented for other light types too, but shadows will look bad if they cross with each-other. You should generally use subtractive shadowmapping with a single light.

**Comment by akien-mga** [comment]
Fixed by #46694.
