### ISSUE TITLE
Improve drag-and-drop reliability at the bottom of the Scene tree dock

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#46339]
**Godot version:**

3.2.4 rc2 mono

**OS/device including version:**

win10 64

**Issue description:**

A kinematic node cannot be positioned below a sprite, however the opposite can happen.

![GIF](https://user-images.githubusercontent.com/19652075/108835258-87165580-75cf-11eb-9a19-2d96254d1232.gif)

**Steps to reproduce:**
Create a scene
Add a kinematic node and a sprite being children of another node.
Try positioning one below the other and vice versa.

**Minimal reproduction project:**

**Comment by Calinou** [comment]
This is not an issue with the node types in themselves, it's just that drag-and-drop at the bottom of the scene tree is finnicky.

**Comment by Torguen** [comment]
and why is it so easy with the sprite node?

**Comment by Calinou** [comment]
> and why is it so easy with the sprite node?

Maybe because it has contains child nodes?

**Comment by Torguen** [comment]
Well I have no idea, I don't know why that would matter (the fact that it has child nodes).

This is not possible either.
![gif gif](https://user-images.githubusercontent.com/19652075/109063928-0c8e2880-76ea-11eb-9799-490f8612dba2.gif)

**Comment by nmrkr** [comment]
This appears to be a visual problem, not a functional one. The drop indicator line appears above the item instead of below, but the drop still works as expected. Seems to happen only happen on nodes with children and only on the upper half of the drop zone. This makes it very noticeable on the last node because there is now lower half. If you watch closely, you can see the drop indicator appear above the last item in @Torguen's GIF, but for clarity I recorded an extended version.

![node-reorder](https://user-images.githubusercontent.com/68759527/109075425-621e0180-76f9-11eb-841a-794dfc93a1d7.gif)

**Comment by kleonc** [comment]
Fixed by #52095/#52096.

**Comment by Calinou** [comment]
Closing per @kleonc's comment.
