### ISSUE TITLE
add some visual effects to where undo/redo occurs (feature request)

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#4634]
**Operating system or device - Godot version:**
Official 2.0.2_stable win64

**Issue description** (what happened, and what was expected):

When I work on several scenes at the same time, the undo/redo stack apply to all the scenes.
Having one undo/redo stack per scene would be less confusing, but as @reduz  stated into #3511, it is not possible to change this behavior.

So, to make it less confusing, what about adding some visual effects to where a undo/redo is applied ?

For instance, when a property or a node is undone/redone, something like a red or yellow circle could brievely appear over the concerned item to attract eyes.

I think it would make easier to follow the undo/redo flow.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by raould** [comment]
I whole-heartedly agree, I find undo and redo to currently be only dangerous things that do mostly invisible confusing changes to my stuff, breaking things, and leaving me lost. :-(

**Comment by bojidar-bg** [comment]
Sounds good, though the UndoRedo class would be painfully changed if we need to accommodate for this..

**Comment by Calinou** [comment]
**Bugsquad note:** This feature is still not implemented as of commit https://github.com/godotengine/godot/commit/4d787869e189b670d609f33c308991741592e40a.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
