### ISSUE TITLE
3.2.4 rc3 --version option generates warning

### ISSUE THREAD

**Issue by bitwes** [godotengine/godot#46391]
**Godot version:**

3.2.4 rc3

**OS/device including version:**

OSX

**Issue description:**

Running Godot with `--version` option generates  the warning `Property not found: application/run/flush_stdout_on_print`

Occurs in project and non-project directories
```
[/]$  /Applications/Godot_3.2.4_rc3.app/Contents/MacOS/Godot --version
arguments
0: /Applications/Godot_3.2.4_rc3.app/Contents/MacOS/Godot
1: --version
Current path: /
3.2.4.rc3.official
WARNING: _get: Property not found: application/run/flush_stdout_on_print
   At: core/project_settings.cpp:209.
[/]$  
```

**Steps to reproduce:**
see issue description

**Minimal reproduction project:**

see issue description

**Comment by Calinou** [comment]
This is happening because Godot thinks the ProjectSettings singleton is initialized.

I tried to replace the call to `GLOBAL_GET()` (which expands to `ProjectSettings::get_singleton()->get()` with `ProjectSettings::get_singleton()->get_setting()`, but that didn't solve the error message.

I see two ways to fix this:

- Revert this change for `3.2`. I really wouldn't like this because it makes the server build almost unusable in a production environment, unless you always use `printerr()` instead of `print()` in your scripts.
- Always flush stdout when printing in release builds. This would likely be a good move for 4.0, but it will require educating people about not spamming `print()`s in their exported projects or risk performance issues.

**Comment by kuruk-mm** [comment]
> [This is happening because Godot thinks the ProjectSettings singleton is initialized when it's not.](https://github.com/godotengine/godot/blob/4cdd22212a9b1acbb62f0c82160f80c8aed2191e/core/io/logger.cpp#L210-L214) I tried to replace the call to `GLOBAL_GET()` (which expands to `ProjectSettings::get_singleton()->get()` with `ProjectSettings::get_singleton()->get_setting()`, but that didn't solve the error message.
> 
> Unless we find a way to properly check whether the ProjectSettings singleton is ready to be queried for settings using `get_setting()`, I only see two ways to fix this:
> 
> * Revert the `flush_stdout_on_print` change for `3.2`. I really wouldn't like this because [it makes the server build almost unusable in a production environment](https://github.com/godotengine/godot-proposals/issues/1912), unless you always use `printerr()` instead of `print()` in your scripts.
> * Always flush stdout when printing in release builds and remove the setting. This would likely be a good move for 4.0, but it will require educating people about not spamming `print()`s in their exported projects or risk performance issues. (It's fine to spam prints in debug builds since performance isn't so important there.)

What do you think about caching the variable like this: https://github.com/kuruk-mm/godot/commit/6810049b8e480588c3af39e2e2c51c0140308830 ?

Can improve the performance too, because is not searching the value in each print at the cost of one string comparison in the set of the ProjectSettings.

If you think is a good idea I will PR it.

**Comment by Calinou** [comment]
> What do you think about caching the variable like this: kuruk-mm@6810049 ?

While this fixes the issue, this means it can no longer be changed at run-time (changes will be silently ignored).

**Comment by kuruk-mm** [comment]
> > What do you think about caching the variable like this: [kuruk-mm/godot@6810049](https://github.com/kuruk-mm/godot/commit/6810049) ?
> 
> While this fixes the issue, this means it can no longer be changed at run-time (changes to the setting will be silently ignored). This should at least be documented.

Why? I'm changing the value of the variable when you set the ProjectSetting variable. I tested and I can change it from the Editor option and see the difference. I'm missing something?

**Comment by akien-mga** [comment]
[Solutions must be local](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local). Caching might be a good idea but it should be done in `logger.cpp`, not in `project_settings.cpp`.

**Comment by kuruk-mm** [comment]
> [Solutions must be local](https://docs.godotengine.org/en/latest/community/contributing/best_practices_for_engine_contributors.html#solutions-must-be-local). Caching might be a good idea but it should be done in `logger.cpp`, not in `project_settings.cpp`.
> 
> It should just be set in the constructor once and for all (and then yes documented as such, a restart is needed to change its value).

Ok, sounds great, to access `Logger` objects I need to get it from `OS` singleton.
Or I can just set it as a static variable in Logger. What do you think is the best solution?

**Comment by akien-mga** [comment]
I meant this should just be a private variable initialized in the `Logger` constructor.
