### ISSUE TITLE
Original array is affected when changed in function

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#4640]
**Operating system or device - Godot version:**
Windows 10 Pro - Godot 2.0.2

**Issue description** (what happened, and what was expected):
When an array is set into a function, it also affects the original one. This doesn't occur to variables, so I'm supposing it's not intended.

**Steps to reproduce:**
Use this code into your project:
```
var a = 0
var b = [0]

func _ready():
	varr(a)
	arr(b)
	print(a)
	print(b)
	
func arr(p):
	p[0] = 5

func varr(k):
	k = 5
```
Will print:
0
5

**Comment by Zylann** [comment]
This is an intented behaviour.

Arrays are objects, so like in C#, Java or Python they are treated as references. If you pass that reference to a function that modifies it, you get the array modified.

On the other hand, numbers are values, they are passed by copy. So in varr you are modifying a local copy.

**Comment by volzhs** [comment]
as @Zylann said, it's intended.
if you want to have a copy of array in function, you can do like this.

```gdscript
func arr(p):
    var copy = [] + p
    copy[0] = 5
```

**Comment by eska014** [comment]
As Zylann explained, arrays created with this syntax `[0, 2, 4]` are created in shared mode ("as references").

If you create an array with `Array.new()`, the array will be in COW-mode (copy-on-write), which will copy the array when it's modified, so that the original array is not changed. 

This is undocumented though, @reduz please clarify if this is intended

**Comment by eska014** [comment]
I meant `Array()` rather than `Array.new()`, since Array is a built-in type
