### ISSUE TITLE
Set rotation functions

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#4643]
There are too many namings for the same function, set_rot, set_rotation, set_rotation_deg, set_rotationd, set_rotd, also there are thing like set_param functions that takes an angle, should we add things like PARAM_ANGLE_DEG, i think is too much bloat, there shoul be only one rotation type function either in degrees or radians and use deg2rad or rad2deg, also it is confusing that angles in the editor are expressed in degrees whereas angles in scripts are expresed in radians, probabily theres a good reason for that, but for beginners i dont think that is friendly.

**Comment by vnen** [comment]
> it is confusing that angles in the editor are expressed in degrees whereas angles in scripts are expresed in radians, probabily theres a good reason for that, but for beginners i dont think that is friendly.

It is friendly for any one that knows math IMO. I expect radians in code because it's easier to do math with. But in the editor I don't want to type the value of  `PI/2` to get 90º, it's much simpler to type "90". Conversion functions also add another layer of complexity and more CPU usage.

I do agree on the inconsistent names. The API should really have a consistent naming convention. And IMO the next API breakage in 3.0 could get a complete review to ensure this consistency.

**Comment by bojidar-bg** [comment]
Wasn't this somewhat done by @akien-mga in 4eab767a6fbc746f6a13e976b4e34d566e7cc4cd?
