### ISSUE TITLE
EditorPlugins won't let you write "%BASE%"

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#46436]
**Godot version:** 3.2.4.rc2
**OS/device including version:** Windows 8.1
**Issue description:**
In my EditorPlugin I wrote the line ``file.replace("%BASE%",sceneRootNode.get_class())`` and whenever I restarted Godot I received the error ``Unable to load addon script from path: 'res://addons/plugin/plugin.gd' There seems to be an error in the code, please check the syntax.``
Attempting to re-enable the addon caused the same error. So I commented out the line but the error persisted.

**Steps to reproduce:**
Create a new plugin with the following lines and then restart Godot:
```
tool
extends EditorPlugin
# %BASE%
```

**Minimal reproduction project:**
[script_templates bug.zip](https://github.com/godotengine/godot/files/6047115/script_templates.bug.zip)

This bug isn't surprising to see (because of how script_templates work). I'm sure this one's a low priority issue, there are very easy workarounds such as writing "%"+"BASE"+"%". It doesn't seem to affect normal scripts but I haven't checked thoroughly.

**Comment by Calinou** [comment]
cc @Xrayez as they worked on script templates in the past.

**Comment by Xrayez** [comment]
Since the script is not parsed, no base type is assigned.

https://github.com/godotengine/godot/blob/7bb0d39da4333032d9bb9205ed8d2158692035eb/modules/gdscript/gdscript.cpp#L789-L792

Which leads to this:

https://github.com/godotengine/godot/blob/7bb0d39da4333032d9bb9205ed8d2158692035eb/editor/editor_node.cpp#L3153-L3157

> cc @Xrayez as they worked on script templates in the past.

Yes, apparently @27thLiz is the one who worked on this based on the git history, so at least need some feedback on how to solve this in the best way possible without introducing hacks.

It may be safe to remove the check and let the script to be parsed, because script templates can be ignored by creating `.gdignore` file if those scripts reside within a project (referring to #31111 which happens to reveal existing bug).

Could also be possibly solved with annotations in GDScript 2.0 to denote that those script templates are actually templates, and not actual scripts...
