### ISSUE TITLE
Multiple folder delete through editor filesystem dock crashes editor

### ISSUE THREAD

**Issue by smix8** [godotengine/godot#46469]
**Godot version:**
v3.2.4-rc3

**OS/device including version:**
Win 10 64x

**Issue description:**
Deleting multiple project folders one by one (not at the same time) through editor filesystem dock gets editor stuck in an infinite loop with console spam.

First folder delete  through the editor filesystem dock works flawless.
Second folder delete (doesn't matter if already empty or folder is full of files) the editor seems to be stuck in an infinite loop.
After a few seconds editor prints a generic file access error to the console.
After another few seconds editor prints another generic file access error to the console.
After some time editor gives up and spams the console endless with "Cannot open file from path 'XYZ'" At: editor/editor_file_system.cpp:1801
The XYZ filepaths that get spamed are previous deleted filepaths and sometimes completely unrelated filepaths in the project.
The editor is unresponsive and requires a hardreset.

The Godot editor runs with with admin and full fileaccess rights so that shouldn't be the issue. Maybe this is a Windows only issue, I can't test on Linux.

**Steps to reproduce:**
Delete one project subfolder through the editor filesystem dock, now delete another.

**Minimal reproduction project:**
see steps

**Comment by kuruk-mm** [comment]
Confirmed on Linux Mint 18.04, here a video:

https://user-images.githubusercontent.com/12563266/109394144-3de24080-7904-11eb-9a2e-e3e7ce3ff1ba.mp4

It seems that happens when you delete two folders fast, it doesn't happens when you delete those slow.

And it started to search the resources inside the folders recursive

```
ERROR: _reimport_file: Error importing 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (8th copy)/icon.png'.
   At: editor/editor_file_system.cpp:1791.
ERROR: _reimport_file: Cannot open file from path 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (8th copy)/icon.png.import'.
   At: editor/editor_file_system.cpp:1797.
ERROR: load_image: Error opening file 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (7th copy)/icon.png'.
   At: core/io/image_loader.cpp:56.
ERROR: _reimport_file: Error importing 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (7th copy)/icon.png'.
   At: editor/editor_file_system.cpp:1791.
ERROR: _reimport_file: Cannot open file from path 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (7th copy)/icon.png.import'.
   At: editor/editor_file_system.cpp:1797.
ERROR: load_image: Error opening file 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (6th copy)/icon.png'.
   At: core/io/image_loader.cpp:56.
ERROR: _reimport_file: Error importing 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (6th copy)/icon.png'.
   At: editor/editor_file_system.cpp:1791.
ERROR: _reimport_file: Cannot open file from path 'res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (6th copy)/icon.png.import'.
   At: editor/editor_file_system.cpp:1797.
```

And those paths doesn't exists

(tree of my godot project)
```
├── default_env.tres
├── folder1 (3rd copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (4th copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (5th copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (6th copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (7th copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (8th copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (9th copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (another copy)
│   ├── icon.png
│   └── icon.png.import
├── folder1 (copy)
│   ├── icon.png
│   └── icon.png.import
├── icon.png
├── icon.png.import
├── Main.tscn
└── project.godot
```

**Comment by kuruk-mm** [comment]
So, we went deep with @YeldhamDev and we found that this bugs happens on 3.2.2-stable 3.2.3-stable, 3.2.4 (before the PR this commit e6b3579e56226947c01884c3cdaec4217686d0de) and on the master branch too!

It seems that it's a problem on '_scan_fs_changes' function.

When a changes happens on the filesystem, Godot gets a trigger and a '_scan_fs_changes' is called from the root path (alias 'res://'), and it starts a recursive search searching modifications.

Godot saves the modification time of each folder (even the root folder). And when a change is triggered, it would compared if something has a different modification time.

```
void EditorFileSystem::_scan_fs_changes(EditorFileSystemDirectory *p_dir, const ScanProgress &p_progress) {
	uint64_t current_mtime = FileAccess::get_modified_time(p_dir->get_path());

	bool updated_dir = false;
	String cd = p_dir->get_path();

	if (current_mtime != p_dir->modified_time || using_fat32_or_exfat) { // <-- check if the current path changed
```

Look this log, and see the **** where the problem happens.
```
[BEGIN] _scan_fs_changes triggered
[SYSTEM] _scan_fs_changes [dir="res://"] [current_mtime=1614456940] [p_dir->modified_time=1614456940]
[END] _scan_fs_changes triggered
[GUI] Folder removed: res://folder (26th copy)/
[BEGIN] _scan_fs_changes triggered
[SYSTEM] _scan_fs_changes [dir="res://"] [current_mtime=1614456943] [p_dir->modified_time=1614456940]
[SYSTEM] Remove directory: res://folder (26th copy)/
[END] _scan_fs_changes triggered
[BEGIN] _scan_fs_changes triggered
[SYSTEM] _scan_fs_changes [dir="res://"] [current_mtime=1614456943] [p_dir->modified_time=1614456943]
[END] _scan_fs_changes triggered
[GUI] Folder_removed res://folder (27th copy)/
[BEGIN] _scan_fs_changes triggered
[SYSTEM] _scan_fs_changes [dir="res://"] [current_mtime=1614456943] [p_dir->modified_time=1614456943] ****
ERROR: Failed to get modified time for: res://folder (27th copy)/.
   at: _get_modified_time (drivers/unix/file_access_unix.cpp:308)
ERROR: Failed to get modified time for: res://folder (27th copy)/default_env.tres.
   at: _get_modified_time (drivers/unix/file_access_unix.cpp:308)
```

So looking this log, I deleted two folders very fast. And triggered 3 times the "_scan_fs_changes", the first one was ok, the second one too, but the third one (where you see ****) doesn't, the `current_mtime` and `p_dir->modified_time` are equal. But a folder was removed! So it's not detecting the change.

So there the problems begins.
In the same function, below that you have this function:
```
		da->change_dir(cd);
		da->list_dir_begin();
```

And because the folder wasn't updated, it would try to search inside it modifications. But that `da->change_dir(cd)` would fail (returning an error) but because there is not a error handling, the `da->list_dir_begin()` would list the files from the previous folder but thinking we are in the deleted folder, searching in it recursively.

So that is the reason that starts in a infinite loop searching paths inside the deleted folder like:
`res://folder1 (31st copy)/folder1 (8th copy)/folder1 (9th copy)/folder1 (3rd copy)/folder1 (8th copy)/icon.png`

This only happens with folders. So I had some ideas. One idea is when we delete a folder from the Editor, it will reset the modified time from the parent folder. So I'm opening a PR with that change.

**Comment by KoBeWi** [comment]
> And because the folder wasn't updated, it would try to search inside it for modifications. But that da->change_dir(cd) would fail (returning an error) but because there's no error handling, the da->list_dir_begin() would list the files from the previous folder but thinking we are in the deleted folder, searching in it recursively.

Wouldn't it be better to add error handling in that method? I mean, do `da->change_dir()` and list dir only if there is no error.

**Comment by kuruk-mm** [comment]
> > And because the folder wasn't updated, it would try to search inside it for modifications. But that da->change_dir(cd) would fail (returning an error) but because there's no error handling, the da->list_dir_begin() would list the files from the previous folder but thinking we are in the deleted folder, searching in it recursively.
> 
> Wouldn't it be better to add error handling in that method? I mean, do `da->change_dir()` and list dir only if there is no error.

I did it in the PR, but it brings a new bug. The folder in the GUI will be displayed even if deleted. So it would not update the GUI.

That error is just the consequence.
