### ISSUE TITLE
The FileSystem dock doesn't open files or folders

### ISSUE THREAD

**Issue by Wickersun** [godotengine/godot#4663]
**Godot engine**: v.2.0.3 (official stable)
**OS**: Windows 7 x64 

When you're in the root folder (res://) at the FileSystem dock, double mouse click on any file or folder doesn't work (pressing "Enter" key works properly).

**Comment by neikeq** [comment]
Looks like a duplicate of #4607 which was recently fixed. Ping @akien-mga

**Comment by Wickersun** [comment]
You're right! I missed that issue. It's my fault, sorry! Now all works fine.

**Comment by akien-mga** [comment]
The bug should not be there in 2.0.3, I reverted the problematic commit.

**Comment by akien-mga** [comment]
So I'm a bit confused about you having the bug in the first place in 2.0.3. You later state that now all works fine, what changed since your initial report?

There was a ~12 h window where a build of 2.0.3 with this bug was on the mirrors (but not announced officially yet), and it was then replaced by the build that got linked on the download page / announced on the blog. Did you download it at this time?

**Comment by Wickersun** [comment]
Yes, Remi, the issue was opened by me when I caught the bug version of Godot from the mirror.
Later I downloaded the corrected version from the blog and closed the issue.

In the next time I'll be more carefull when I describe the problem and give the version of program.

That was my first bug report, so don't scold me ;-)

**Comment by akien-mga** [comment]
Thanks for the clarification, all is good then :) You were fast to grab it from the mirrors before it had been announced officially ;)

**Comment by Wickersun** [comment]
Yeah, I'm r-r-r-eally fast! :) I try not to miss any fresh version of Godot - the best gamedev software!
