### ISSUE TITLE
Artifacts when using shader with sprite that has enabled mipmaps

### ISSUE THREAD

**Issue by ofiala-a51** [godotengine/godot#46630]
**Godot version:** 3.2.3

**OS/device including version:** Linux Mint 20.1, IGPU (Mesa DRI Intel HD Graphics 3000), GLES3

**Issue description:** There are visual artifacts when shader is applied on sprite with mipmaps. The placement of artifacts and their size changes with zoom. See [video](https://gitlab.com/ofiala/godot-repro2/-/raw/master/out.ogv).

**Steps to reproduce:** Enable mipmaps on an image, place it as a sprite, apply some primitive shader. Also see reproduction project.

**Minimal reproduction project:** GitHub's file upload doesn't work in my browser, so I uploaded it [here](https://gitlab.com/ofiala/godot-repro2). Blame GitHub.

**Comment by lawnjelly** [comment]
From a quick look your shader looks suspect. Anything doing a comparison like this:
```
	if (tex_clr == vec4(0.0, 0.0, 0.0, 0.0)) {
```
is likely to be a bad idea.

**Comment by ofiala-a51** [comment]
That's kinda irrelevant though, such artifacts should not happen. It's hard to even understand how shaders work when it's outputing junk like that.

**Comment by lawnjelly** [comment]
I suspect these are not a Godot problem, I think they are just a consequence of how GPUs work, they will occur on shadertoy etc. Godot just simply translates your shader into GLSL, the rest is done by the GPU.

What I'm guessing is happening is that the UV you are using is a very high number and reading from a lower mipmap and giving aliasing. But there's also likely to be aliasing due to the float equal comparisons.

Shaders and precision are hard to understand and debug, and this is 10x worse when you need them to run on mobile. Even experts have lots of trouble with them (I'm far from an  expert myself). I believe that the Godot discord has an active shaders section (if you look in the community channels on the Godot website), that would be good for getting help if you are starting with shaders. I expect at this stage it is hard for you to know what is a problem with your shader and what might be an issue with Godot.

Also the shadertoy website is probably great for learning about precision and do's and don't of float comparisons etc.

**Comment by ofiala-a51** [comment]
Thanks for the reply @lawnjelly, you are right. I spent some more time experimenting with shaders and too high UV value is the source of those artifacts.
