### ISSUE TITLE
PhysicsServer error with rigid BodySetSpace() GodotPhysics

### ISSUE THREAD

**Issue by nikitavondel** [godotengine/godot#46738]
**Godot version:**

3.2.3 mono official stable.

**OS/device including version:**

Windows 10 64 bit 

**Issue description:**

When setting the space of a rigid body from a PhysicsServer a stream of a repetitive error occurs with GodotPhysics enabled:
`ERROR: The axis Vector3 must be normalized.
   At: core/math/basis.cpp:980`

**Steps to reproduce in:**
1. Create a space
2. Set space to active
3. Create a body
4. Set body space to space we created earlier.
5. Enable GodotPhysics
6. Watch "The axis Vector3 must be normalized" spam.

**Minimal reproduction project:**

[godotBug.zip](https://github.com/godotengine/godot/files/6096110/godotBug.zip)

**Comment by nikitavondel** [comment]
This also happens with GDScript
```extends Spatial



var defaultSpaceState : RID

func _ready():
	
	defaultSpaceState = PhysicsServer.space_create()
	PhysicsServer.space_set_active(defaultSpaceState, true)
	
	var bodyRID : RID = PhysicsServer.body_create(PhysicsServer.BODY_MODE_RIGID,false)
	
	PhysicsServer.body_set_space(bodyRID, defaultSpaceState)
	
```

**Comment by pouleyKetchoupp** [comment]
This also occurs with any `Rigidbody` node with all `CollisionShape` nodes disabled, or no `CollisionShape` at all.
It's not a common use case (the body doesn't collide with anything and just falls), but it can be supported by the physics simulation and can be useful for special cases (particles with advanced physics or joint attachments).

Note for junior job:
This is due to how inertia is calculated for a body with no valid shape in `Body3DSW::update_inertias()`:
https://github.com/godotengine/godot/blob/9b853d7a7b12f11e98e8c12b2e4ba96f4111add8/servers/physics_3d/body_3d_sw.cpp#L79-L103
`inertia_tensor` is initialized to zero and inertias are added from valid shapes (this is correct), but in case there's no valid shape at all it should be set to a valid default inertia with `inertia_tensor.set_diagonal(Vector3(1.0, 1.0, 1.0));` to avoid divisions by zero during the simulation.

**Comment by Bhu1-V** [comment]
hlo Current master branch has some changes in the `PhysicsServer` so the above code need some changes to run

```
var defaultSpaceState : RID

func _ready():
	
	defaultSpaceState = PhysicsServer3D.space_create()
	PhysicsServer3D.space_set_active(defaultSpaceState, true)
	
	var bodyRID : RID = PhysicsServer3D.body_create()
	
	PhysicsServer3D.body_set_space(bodyRID, defaultSpaceState)
```

as u can see `body_create()` got different syntax and also this code is no longer going to `update_inertia()`. atleast thats what I'm thinking . and I really don't known what went wrong.

**Comment by pouleyKetchoupp** [comment]
@Bhu1-V Your sample code works for me on master, I'm able to reproduce the issue. It calls `update_inertias()` on the next physics step with this callstack:
```
 	godot.windows.tools.64.exe!Body3DSW::update_inertias() Line 107	C++
 	godot.windows.tools.64.exe!Space3DSW::setup() Line 1165	C++
 	godot.windows.tools.64.exe!Step3DSW::step(Space3DSW * p_space, float p_delta, int p_iterations) Line 147	C++
 	godot.windows.tools.64.exe!PhysicsServer3DSW::step(float p_step) Line 1354	C++
 	godot.windows.tools.64.exe!PhysicsServer3DWrapMT::step(float p_step) Line 76	C++
 	godot.windows.tools.64.exe!Main::iteration() Line 2472	C++
 	godot.windows.tools.64.exe!OS_Windows::run() Line 622	C++

```

The only difference is `body_create` creates a body with `BODY_MODE_RIGID` by default, and `body_set_mode` needs to be called separately for making it static or kinematic.
