### ISSUE TITLE
AnimationPlayer changes its frame milliseconds before looping

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4681]
This is on Godot_v2.0.3_stable_win64.exe

- Add a Normal Node Sprite
- Set the texture to your spritesheet
- Set the vFrames and hFrames respectively
- Keyframe an animation using the AnimationPlayer with `steps` set to `0`, and then set it to `continuous`.
- Set the len(s) to: 0.8
- Now on the first keyframe, set the  `Frame` 0.
- Now on the last animation keyframe set the `Frame` to 19 (or your total amount of frames -1)

Now here is where the bug is:

Look at where the timeline is at, it's **barely** at the end, and it's showing the `Frame` 19. Which is correct: **(This is the last frame it should be on before looping)**
![image](https://cloud.githubusercontent.com/assets/10387670/15309133/d6d3951a-1b98-11e6-81c2-3f138e88758c.png)

Now, move the timeline cursor over just a bit (you might need to click on the image to zoom in) and look what happens:

![image](https://cloud.githubusercontent.com/assets/10387670/15309150/024ff418-1b99-11e6-9f02-dbb8b5226b34.png)

It goes to the last frame right at the last millisecond before looping. Which causing distortion (barely noticeable) when animating. You can change the steps value to 0.0001 to fix this, but the distortion still happens.

**Comment by adolson** [comment]
Dupe of #959... Nice to see someone else thinking it's screwy, though... Hope it gets fixed some day, if it hasn't been already.

**Comment by Dillybob92** [comment]
Ha, well if this doesn't get fixed I'm kind of stumped at continuing to use the engine :P I'm porting my game over from HTML 5 and we have hundreds of sprite sheets like this, the distortion is barely noticeable but it's there :(. I think I isolated the problem more though, it's basically right before the last frame (as you stated, on continuous mode) it sets it to frame 0 when it shouldn't. [The last couple milliseconds] -- I don't know C++ at all, but I think if someone is well versed it will be no problem.

Do you know if this happens on the linux builds though? For example, #4667 doesn't seem to happen on linux builds, but sporadically out of no where on windows.. Might be the same for this :palm_tree:

**Comment by adolson** [comment]
I only run Linux, so yes.

It's not only a problem with the last frame. It's because of how the engine is behaving as a whole. It is blending from end to beginning when you enable looping, and it's NOT right. I don't care what anyone else says. There needs to be a way to turn that off. I had fixed it completely and submitted a pull request, but closed it out because the current behavior is, for some reason, actually intended and desired behavior. It is outside of my skillset to implement a proper fix that retains the current, unexpected, and broken behavior while giving us the option to play animations how they should be played.

And yeah, as you allude, it is definitely discouraging and has at least contributed partly to why I am not as active here as I once was.

**Comment by Dillybob92** [comment]
duplicate https://github.com/godotengine/godot/issues/959

I guess, thanks @adolson up to the bosses now. See my post there, I tried, we'll wait and see :)

**Comment by reduz** [comment]
there is a problem with the interpolation which @punto- found. It needs to be corrected and leads to this kind of mistakes... question is if any project would break as a result

**Comment by Dillybob92** [comment]
> question is if any project would break as a result

Thanks for your response! Maybe an option to disable this so current projects are not affected? 

It could be added as a checkbox to the `Track Tools` button:
![image](https://cloud.githubusercontent.com/assets/10387670/15339180/0ad7e466-1c38-11e6-81f6-4990a95832a5.png)
