### ISSUE TITLE
Camera2D does not stay centered when resizing the window and smoothing is false.

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#46826]
**Godot version:**
Godot 3.2.4 RC4

**OS/device including version:**
Win10

**Issue description:**
When a Camera2D is not set to smoothing and the window is resized the Camera2D does not stay centered. In RC3 and before the camera stayed centered, and while smoothing is enabled the camera stays centered.

**Steps to reproduce:**
Have a Camera2D in the scene, see minimal project.

**Minimal reproduction project:**
Run the game and resize the window, the Godot logo should stay in the center, but it does not. If you enable smoothing the logo will stay centered as intended.
[camera_bug_test.zip](https://github.com/godotengine/godot/files/6109324/camera_bug_test.zip)

**Comment by akien-mga** [comment]
We likely need to call `_update_scroll()` when the window is resized, but there doesn't seem to be a notification for it.

The fact that it worked fine before RC 4 was actually due to a bug which made `Camera2D` update on every frame even when not using smoothing, which is wasteful and can cause delays or jitter. But now we need to make sure we do update discretely whenever relevant.

**Comment by akien-mga** [comment]
Fixed by #46829.
