### ISSUE TITLE
Grouping nodes in Editor

### ISSUE THREAD

**Issue by eXponenta** [godotengine/godot#4682]
How group node in Editor without scripting?
This is possible?

**Comment by akien-mga** [comment]
Could you be more specific on what you mean by "grouping"?

Do you mean make all nodes grouped together so that you can move them all at once in the viewport? For that the best solution is to make all those nodes children/grandchildren of a common node, and you would move this node around.

If you mean how to make a specific node part of a "group", as in ``add_to_group``, see http://docs.godotengine.org/en/latest/tutorials/step_by_step/scripting_continued.html#groups

**Comment by eXponenta** [comment]
Yes, I mean how to make a specific node part of a "group" WITHOUT scripting.
I searched "Group" property for Node in inspector, but didn't find it.
The existence of this property would be very useful . Currently i can't understand how determine the type of body that has collided with current node when there are types of 'Coins','Mobs' and other.

**Comment by akien-mga** [comment]
Well check the link I just gave, there's a button for it in the scene tree. (If you're using the latest master branch, it was replaced by a contextual menu with right mouse click).

**Comment by eXponenta** [comment]
Oh. Thanks. I used prebuild version 2.0.3. 
I will update it soon.
