### ISSUE TITLE
Range Nodes Min Values can be higher than Max Values

### ISSUE THREAD

**Issue by dragifon** [godotengine/godot#46863]
**Godot version:**

v3.2.3.stable.flathub

**OS/device including version:**

Linux Mint 20.1 x86_64

**Issue description:**

Range Nodes have Min Value and Max Value properties. Changing Min Value to be higher than Max Value is allowed. The inverse (changing Max Value to be less than Min Value) is also allowed. 

The expectation was changing Min Value to be higher than Max Value would automatically set Min Value to be 1 less than Max Value. Likewise, changing Max Value to be higher than Min Value was expected to automatically correct Max Value to be 1 more than Min Value

**Steps to reproduce:**
1. Create a Range Node (Scrollbars, Sliders, Progressbars, or Spinbox)
2. In the Inspector for the Range Node, set Min Value to be more than Max Value OR set Max Value to be less than Min Value
3. Notice Value automatically adjusts to equal Min Value, but Min Value and Max Value do not automatically adjust.

**Minimal reproduction project:**

[Range Node Bug.zip](https://github.com/godotengine/godot/files/6115286/Range.Node.Bug.zip)

**Comment by Zylann** [comment]
As I explained earlier in RocketChat this is a bit more complicated to implement than it sounds, due to how Godot serializes properties. This applies to all situations where we have interdependent properties such as `min` and `max`, not just `Range`:

Godot serializes `min` and `max` as two separate properties, and there is no guarantee about the order in which they will be set when the scene is loaded. There is also no guarantee that they will be set at all.

Because of this, if we do this in the setter:

```cpp
void Range::set_min_value(float p_min_value) {
	min_value = MIN(p_min_value, max_value);
}
```

If `max` is set after `min` and `p_min` is greater than max's default value, it will end up with the wrong value. The setter cannot know if it is used in the context of loading the scene or being modified by the inspector or a script.

One way to fix this is to keep that code, but instead change properties bindings such that they only have the `EDITOR` hint, without `STORAGE`. Then, `min` and `max` can be saved and loaded a one pair by registering an internal `_range` property of type `Array` that only has the `STORAGE` hint (no need to have an extra field in the class, this is only done with `_get`/`_set`/`_get_property_list`). The setter of that property will then be able to check validity with both values.

**Comment by KoBeWi** [comment]
Maybe when setting `min`/`max`/`page` we could make a deferred call to e.g. `validate_min_max`, which would make sure that these values are all correct?

**Comment by Bhu1-V** [comment]
Yep saw how it's effecting.
> Maybe when setting `min`/`max`/`page` we could make a deferred call to e.g. `validate_min_max`, which would make sure that these values are all correct?

well how to make a deferred call ?

**Comment by Calinou** [comment]
> well how to make a deferred call ?

```gdscript
call_deferred("method_name")

set_deferred("property_name", value)
```

**Comment by Zylann** [comment]
Will this work properly if the node is instanced from a thread? (not added to tree, just instanced, which should be supported). I think deferred calls are invoked from the main thread.

**Comment by dragifon** [comment]
How well would something along the lines of 
```cpp
void Range::set_min_value(float p_min_value) {
        float p_max_value = get_max_value();
        if (p_min_value >= p_max_value) {
                min_value = p_max_value - step;
        }
        else{
                min_value = p_min_value;
        }
}
``` work?

What's a deferred call?

**Comment by Calinou** [comment]
> What's a deferred call?

A deferred call is a call that occurs with a delay of one frame (and won't block the rest of the code execution).

**Comment by KoBeWi** [comment]
In codebase base I sometimes see `MessageQueue::get_singleton()->push_call()` for deferred calls.

**Comment by Bhu1-V** [comment]
>[Maybe when setting `min`/`max`/`page` we could make a deferred call to e.g. `validate_min_max`, which would make sure that these values are all correct?](https://github.com/godotengine/godot/issues/46863#issuecomment-795798206)

but what does `validate_min_max` would do? true values are stored in **save file**[.tres], should I check with those values or something else..?

**Comment by KoBeWi** [comment]
Yes.
