### ISSUE TITLE
3.2.4 Noise Texture doesn't generate

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#46907]
**Godot version:**

3.2.4 RC3,RC4, RC2 was fine

**OS/device including version:**

Nvidia Quadro K2000, 452.06, GLES3

**Issue description:**

Noise Textures don't generate.

**Steps to reproduce:**
Create Mesh, Add Material, Set Albedo (or any other texture) to Noise Texture, Add opensimplexnoise to the noise texture

**Minimal reproduction project:**

[Noise.zip](https://github.com/godotengine/godot/files/6125784/Noise.zip)

Edit: The MRP will be useless, it Generates Noise when one loads the project.

**Comment by Calinou** [comment]
This is possibly a regression from https://github.com/godotengine/godot/pull/45618.

**Comment by mrjustaguy** [comment]
Negative, that PR is Jan 31st, I've managed to Find the issue on master branch PR 45326 (oldest master that I have, so could be before that) from Jan 25th

**Comment by akien-mga** [comment]
@mrjustaguy The 3.2.4 release is built from the `3.2` branch, which is fully separate from `master`. So merge time for PRs in the `3.2` branch and `master` don't necessarily match (and thread modernization work happened in `master` first).

I reproduced the bug in a build from #45618, and not in its parent commit, so it's confirmed as a regression from #45618. Noise generation happens in a thread so that's probably why.

**Comment by akien-mga** [comment]
I spotted the bug in the diff, fix incoming.

**Comment by akien-mga** [comment]
Fixed by #46909.
