### ISSUE TITLE
Windows Only - Background Throttling on Dragged Window

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4695]
https://www.reddit.com/r/godot/comments/4jpjdh/question_disable_game_throttling_on_window_drag/

When dragging the window, the game freezes (locks thread) before letting go.  Doesn't happen on Linux though (see video in thread).

Looks like this is only happening on **Windows** builds

Not sure if this is reported, I have searched github so my apologizes if it's already reported. 

:+1:

**Comment by vnen** [comment]
I can confirm this in Windows 10. BGM keeps playing and it seems to keep running but does not update the render until you stop dragging the wnidow.

Also, if you keep a key pressed, start dragging the window, release the key and then release the window, it'll keep that key as pressed. So input events also freezes when dragging.

**Comment by Dillybob92** [comment]
Just curious, @akien-mga or any others, do you think this will be fixed in 2.1? Don't mean to be intrusive, but it's a big issue for multiplayer games I think

**Comment by akien-mga** [comment]
Well ideally all bugs should be fixed as soon as possible, but it's not always doable :) As this issue happens only on window drag, and it's an action that should not be needed in most games, I don't consider it very harmful (compared to other bugs that might affect all games, etc.).

But let's assign to 2.1 for now so that it gets visibility, hopefully a Windows dev can have a look. It probably won't be a blocker for the 2.1 release if not fixed before that though.

**Comment by Hinsbart** [comment]
It seems like a known windows issue. I guess the solution would be to do all of the window handling in a seperate thread.
That will likely involve a bit of re-structuring of os_windows.cpp, but in the end shouldn't be too hard.
I wanted to move the joystick code to a thread anyways (so no events might get lost), so I'll have a look at this too when I'm free the next days/weeks.

**Comment by florton** [comment]
This appears to still be happening, namely its an issue because timers keep running but everything else stops, causing potential exploits.
