### ISSUE TITLE
Invalid type in function 'rpc' (...) Cannot convert argument 1 from String to String.

### ISSUE THREAD

**Issue by Nanox19435** [godotengine/godot#47018]
**Godot version:**

I'm using a custom build. The hash is: a4fd6d374c6a58247ba3d13855e8348fc0c76f3b.

**OS/device including version:**
I have confirmed that this bug occurs both in windows and Linux

**Issue description:**

When attempting to use the rpc() function, the program crashes, sending the error Invalid type in function 'rpc' (...) Cannot convert argument 1 from String to String. I have confirmed that this is present in all the functions on the rpc family, that is rpc_id(), rpc_unreliable, etc.

**Steps to reproduce:**
add the line rpc("string") to a script. When running the project, reaching that line will cause a crash.

**Minimal reproduction project:**

[Example_1.zip](https://github.com/godotengine/godot/files/6139329/Example_1.zip)

**Comment by W4RH4WK** [comment]
Probably 4c528e76e7886613ac99ade66b325ede072ee691.

**Comment by akien-mga** [comment]
> Probably [4c528e7](https://github.com/godotengine/godot/commit/4c528e76e7886613ac99ade66b325ede072ee691).

PR for reference: #45570.
CC @MarvinFF @Faless

**Comment by Killfrra** [comment]
For those who, like me, stumbled upon this issue in search of a solution, as a workaround, you can replace all occurrences of rpc("method_name") with rpc(StringName("method_name")). This is because internally these functions now use StringName instead of String, but the error message was not changed accordingly
