### ISSUE TITLE
[Godot Physics] PhysicsServer reports angular velocity with the wrong sign

### ISSUE THREAD

**Issue by e344fde6bf** [godotengine/godot#47029]
**Godot version:**
3.2.3.stable

**OS/device including version:**
N/A

**Issue description:**

If you request the angular velocity estimate of a kinematic body from the physics server with
```
PhysicsServer.body_get_direct_state(self.get_rid()).angular_velocity
```
the Godot physics value has the incorrect sign.  If you rotate with an angular velocity of `(0, 1, 0)`, then the angular velocity estimate is reported as `(0, -1, 0)`.

**Steps to reproduce:**

* Rotate a kinematic body with a fixed angular velocity: `self.rotate(Vector3(0, 1, 0), 1 * delta)`
* See that the reported `angular_velocity` value has the wrong sign: `(0, -1, 0)`

**Minimal reproduction project:**
[angular-velocity-bug.zip](https://github.com/godotengine/godot/files/6142095/angular-velocity-bug.zip)

**Comment by pouleyKetchoupp** [comment]
I can confirm the angular velocity seems wrong in Godot Physics and it's ok with Bullet Physics.

Here's the code in Godot Physics that calculates the angular velocity for kinematic bodies:
https://github.com/godotengine/godot/blob/6eef187a81cbdd3cd314776de372e753f79f9831/servers/physics_3d/body_3d_sw.cpp#L502-L518
I'm not sure what's wrong exactly, but the math needs to be checked. The issue is probably on this line:
`Basis rot = new_transform.basis.orthonormalized().transposed() * get_transform().basis.orthonormalized();`

**Comment by e344fde6bf** [comment]
Using 

```cpp
    Basis rot = new_transform.basis.orthonormalized() * get_transform().basis.orthonormalized().transposed();
```

gives the correct angular velocity.

However, it seems lots of the code is expecting "reversed" angular velocities.  For example, using `move_and_slide()` on a rotating platform:

https://user-images.githubusercontent.com/79001820/111310850-4202b200-86a9-11eb-9b57-e45967ebde4b.mp4

[angular_velocity_bug2.zip](https://github.com/godotengine/godot/files/6149013/angular_velocity_bug2.zip)
