### ISSUE TITLE
Code editor auto complete feature must use scene hierarchy info to prevent cliping paths too early

### ISSUE THREAD

**Issue by hubbyist** [godotengine/godot#4704]
**Operating system or device - Godot version:**
Using : Godot_v2.0.2_stable_x11.64 on linuxmint 17.2

auto complete list in code editor is cliping node paths depenging on the last letter written as illustrated below.

```
get_node("CenterContainer/VBoxContainer/Panel/Button$
         |CenterContainer/VBoxContainer/Panel/Button|
         |CenterContainer/VBoxContainer/Panel/Button|
         |CenterContainer/VBoxContainer/Panel/Button|
         |CenterContainer/VBoxContainer/Panel/Button|
         |CenterContainer/VBoxContainer/Panel/Button|
         |CenterContainer/VBoxContainer/Panel/Button|
```

It would be better to use biggest next word while listing nodes as below.

```
get_node("CenterContainer/VBoxContainer/Panel/Button$
         |CenterContainer/VBoxContainer/Panel/Button_Up   |
         |CenterContainer/VBoxContainer/Panel/Button_Down |
         |CenterContainer/VBoxContainer/Panel/Button_Aim  |
         |CenterContainer/VBoxContainer/Panel/ButtonGroup/|
         |CenterContainer/VBoxContainer/Panel/ButtonGroup/|
         |CenterContainer/VBoxContainer/Panel/ButtonL/Zone|
```

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by hubbyist** [comment]
Still happening in 2.1.3

![godot_path_clipping](https://cloud.githubusercontent.com/assets/5895328/25474133/b4c9a2a4-2b3a-11e7-9c7f-5282cc97bb56.png)

Some sort of path shortening may help as well I think.

```
get_node("CenterContainer/VBox...iner/Panel/Button$
         |CenterContainer/VBox...iner/Panel/Button_Up   |
         |CenterContainer/VBox...iner/Panel/Button_Down |
         |CenterContainer/VBox...iner/Panel/Button_Aim  |
         |CenterContainer/VBox...iner/Panel/ButtonGroup/|
         |CenterContainer/VBox...iner/Panel/ButtonGroup/|
         |CenterContainer/VBox...iner/Panel/ButtonL/Zone|
```

May also need a milestone update.

**Comment by AlexHolly** [comment]
I am not sure if this aproach helps much
![image](https://user-images.githubusercontent.com/4741886/37123289-ec997b2a-2263-11e8-9427-bb2621ed8790.png)

Is there a reason to use canvasitem and not some Node with horizontal scroll?

**Comment by silverkorn** [comment]
Make it configurable?
Both ways seems good and useful but the expertise of the user might be the breaking point to get more on a path than another.

@AlexHolly, do you know if the dots could be on a different color/shading? This could avoid potential confusion.

**Comment by AlexHolly** [comment]
@silverkorn I looked into the color thing I don't see an easy way for it.
I could probably make the whole line a different color if folding was applied.

> Make it configurable?

You mean disable folding? I don't see any benefit.
The folding should only happen when really needed and only as far as needed to fit.

To me this looks like a temporary solution anyway. To solve this issue some horizontal scroll is needed.

**Comment by silverkorn** [comment]
@AlexHolly, sorry, I meant the different ways to see the auto-completion list.
But otherwise, indeed, an horizontal scrollbar would be needed. I wasn't aware that all those suggestions were for a workarounds.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
