### ISSUE TITLE
Scripts improvement. Discussion

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#4709]
Furious that the script file is a class. On the one hand it is convenient in terms of resources. Always clear what script to load. But on the other hand it is very inconvenient in terms of development. Often what is needed auxiliary functions or objects you want to access from many places. And to use such objects in the current approach is very inconvenient. Of course one might say that there are cars loaded scripts. You can use them. But they are made as a node. And get them out of difficult subclasses. It is necessary to transmit the node. Either create a helper class instance. There's a lot that can be said. But what do you think about the fact that to do in Unity, hang on the node class rather than the entire file?
PS. Offline for some strange reason I can not create threads. Writes are not correct insert verification letters :(

**Comment by reduz** [comment]
I can't really say I understand much, but you can use the singleton objects
as global, or use any class with static functions for helpers..

**Comment by ret80** [comment]
A possible small code examples.

**Comment by ret80** [comment]
Here is a simple example. I have a gun. And there enumerator type of weapon. Instead enumerator natural constants. And I need access to these constants somewhere in a class that does not apply to weapons. And if I do not have an instance of this class in a class of weapons that I have problems.


file: weapon.gd
```
const T_BLASTER = 0
const T_MASHINGUN = 1
...
```

file: weapon_helper.gd
```
func create_weapon_by_type(weapon_type):
        if weapon_type == T_BLASTER :
              return load("res://..../weapon_blaster.gd").new()
....
```

**Comment by reduz** [comment]
can you not do something like

in weapon_helper

const Weapon = preload("res://weapon.gd")

then just use

Weapon.T_BLASTER ?

It should also autocomplete it fine

**Comment by reduz** [comment]
I thought for a while about having an option to add classes to the global
scope, similar to how you do autoloads. This way you can use "Weapon" for
everywhere

**Comment by ret80** [comment]
and with functions so a ride?

file: weapon.gd
```
static func sum(a, b):
    return a + b
```
file weapon_helper.gd
```
const Weapon = preload("res://weapon.gd")

func calc():
    return Weapon.sum(1, 5)
```

**Comment by ret80** [comment]
besides, I have a script for example Fail 7-10 subscripts. and some use subscripts util function. I need to get in each create subscript a constant?

file:util.gd
```
static fun add(a, b):
```
file brain.gd
```
class brain_left:
   const util = rpeload("util.gd")

class brain_right:
   const util = rpeload("util.gd")
```

**Comment by reduz** [comment]
I think if you place:

const util = preload() on the top of the script it should work

that said, I think it makes sense to set classes as Global, do you think
that would make some things simpler?

**Comment by ret80** [comment]
what do you mean by a global set?

I'll try to do as you suggested and see what happens.

**Comment by Zylann** [comment]
The way GDScript work at the moment feels like Java, in the way that each file is necessarily a class named whatever_class.gd. It's also inspired on Python so each file is like a "module" you have to import in every other file that needs it, by the mean of 'load' or 'preload'.

Then when you use it somewhere else, instead of writing:
```
WhateverClass.foo()
```
You do this instead:
```
preload("whatever_class.gd").foo() # This one needs a fix
```
But as I said in another issue, it doesn't works well for some reason, so you write this:
```
const WhateverClass = preload("whatever_class.gd")
...
WhateverClass.foo()
```
In the end, that's the same steps as C++'s `#include "whatever_class.h"`, not a big deal. But on a scripting perspective it looks weird. Things should just work, at least like C# or Java works (you don't need "imports" in these languages, and GDScript has no namespaces so... classes should be global).
From a Python perspective, GDScript doesn't looks so bad, but I wonder if it's possible to put inner classes on Nodes instead of whole files?
I'm curious about how global classes could work. I come from C++/C# language family so it makes sense to me, but it would differ from Python. 

Classes in C++ however get their global scope, and that's definitely something you cannot do in GDScript. The problem is, if you make a library, that someday you port to a C++ module, you'll have to update your code just because usage of C++ classes is different (they aren't in a "file"). It goes the same for global functions, although I'm not sure if they all come from the engine's bindings or the language itself.

Singletons:
Those inheriting Node must be nodes, so it makes sense that they get their place on top of the tree. However, when you need a singleton that is not a node... how would you do? Because you cannot create static variables, only constants and static functions. The reason for this is thread friendlyness as said in the doc: http://docs.godotengine.org/en/latest/reference/gdscript.html?highlight=gdscript#classes
So... I don't know :)

**Comment by ret80** [comment]
Actually I learned better documentation. I conducted an experiment. All in all, it goes. I close the topic. Thanks to all.
