### ISSUE TITLE
AudioEffectCapture buffer length cannot be changed

### ISSUE THREAD

**Issue by sketchyfun** [godotengine/godot#47107]
**Godot version:**
3.2.4

**OS/device including version:**
Ubuntu/Windows 10

**Issue description:**
When experimenting with adding an AudioEffectCapture effect to an audio bus, I noticed I was unable to change the buffer length property from it's default value of 0.1

I was also not able to change it via code using set_buffer_length()

The following error is printed each time an attempt is made:

E 0:00:00.392   set_buffer_length: Condition "buffer_initialized" is true.
  <C++ Source>  servers/audio/effects/audio_effect_capture.cpp:98 @ set_buffer_length()
  <Stack Trace> Main.gd:42 @ _ready()

**Steps to reproduce:**
Add an AudioEffectCapture effect to any audio bus and then try to change it's buffer length property

**Comment by jmb462** [comment]
Confirmed with master branch e57f6e2cca90d4c9e956fe1a7ddb3ca086521b42

**Comment by sketchyfun** [comment]
> > Godot version:
> > 3.2.4
> 
> Please be more specific. 3.2.4 is not released yet (and won't be as it's being renamed to 3.3). Things move fast in Godot development so bug reports need an exact version.

Sorry, I forgot I was using a custom build based on the latest 3.2 release. It's present in 3.2 stable as well.

**Comment by lyuma** [comment]
I'm the author of the feature in question. I designed this feature to be created in code, so I did not test the case that you add the effect to the bus by hand. It was designed to have the buffer length set in the resource or assigned before the effect is instanced.

However, it seems that Godot calls instance() instantly when it is added in the editor. This wasn't something I planned for, so I can see how it fails when editing it in the Audio editor panel.

The proposed fix should solve your use case, but instead of negating the check (which will break the other half the use cases), the ERR_FAIL_COND_V should be simply removed. I'll go make a comment over there.

The design assumes that the buffer length is not changed once the audio effect has started, so note that it will not update the internal buffer, but it will allow you to change the resource property in the editor, and it won't cause any crashes. It might be good to add a message to the documentation that set_buffer_length will have no effect if changed after the effect is initialized.

**Comment by sketchyfun** [comment]
Couldn't the effect re-initialise if the buffer length is changed? or is that not possible?

**Comment by lyuma** [comment]
It might be possible by wrapping some buffer reallocation in 
```
AudioDriver::get_singleton()->lock();
...
AudioDriver::get_singleton()->unlock();
```
Is runtime reallocation something that people would find useful? It would also require copying the data from the existing buffer into the new one if you want to minimize the change of popping. I'm not really interested right now in writing the code to do this, but I would accept a PR if someone wants to make this work.

**Comment by sketchyfun** [comment]
Ah, I can see how it would be more hassle for runtime changes, I was mainly asking for when the value is edited in the editor, really. It wasn't clear that the effect is supposed to be created at runtime and adjusted before initialising as I'm used to adding the effects via the editor normally.
