### ISSUE TITLE
C# Export: System.IO.FileNotFoundException; Missing `System.Drawing`

### ISSUE THREAD

**Issue by JapanYoshi** [godotengine/godot#47164]
**Godot version:**
3.2.3.stable.mono.official

**OS/device including version:**
Windows 10

**Issue description:**
I'm trying to export a game that contains QR code scanning and generation capabilities using a C# library called ZXing.Net. However, when I try to load or save a QR code on the HTML export, the game hangs with this error in the console:

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

**Steps to reproduce:**
1. Create a Godot project, which contains a C# script that uses `System.Drawing`.
1. Export the project to HTML, and attempt to use that script.

**Minimal reproduction project:**
[Test_Project.zip](https://github.com/godotengine/godot/files/6171082/Test_Project.zip)
[Test_HTML5.zip](https://github.com/godotengine/godot/files/6171084/Test_HTML5.zip)

**Comment by JupiterRider** [comment]
Hey,

System.Drawing is not compatible with Web assembly:
[](https://www.reddit.com/r/dotnet/comments/jzxzse/blazor_wasm_cannot_use_bitmap_or/)

That's not an issue with Godot.

**Comment by JapanYoshi** [comment]
Oh, great. How can I deal with QR codes?

**Comment by Calinou** [comment]
@neikeq Any idea where we should document this limitation?

**Comment by neikeq** [comment]
These limitations seem to be described in the `System.Drawing` documentation: https://docs.microsoft.com/en-us/dotnet/api/system.drawing#remarks (and I hope this is turned into a compiler warning with .NET 6: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416).

I'm closing this since it's not a Godot issue.

> How can I deal with QR codes?

I can't help much with that. I did a quick search where the last comment seems to have managed to make it work with ImageSharp: https://github.com/micjahn/ZXing.Net/issues/273#issuecomment-830017377
The relevant parts I found in his project were the package references to ImageSharp and ZXing.Net's ImageSharp bindings, and the image loading and QR decoding code:
- https://github.com/sabitertan/BlazorWasmBarcodeScanZxingNet/blob/d8fce2f4bf60e6069229fa7a81ee6d4e1b2bdcc2/BlazorWasmBarcodeScanZxingNet/Client/BlazorWasmBarcodeScanZxingNet.Client.csproj#L10-L12
- https://github.com/sabitertan/BlazorWasmBarcodeScanZxingNet/blob/d8fce2f4bf60e6069229fa7a81ee6d4e1b2bdcc2/BlazorWasmBarcodeScanZxingNet/Client/Pages/Index.razor#L125-L130
