### ISSUE TITLE
Yield - unexpected behavior

### ISSUE THREAD

**Issue by MadDogMayCry0** [godotengine/godot#47239]
Godot any version!

Yield requires an object to work. A situation causing a logical collision is described below.
Expected behavior is broken! It is required to revise the basic logic of Yield's work.

```gdscript
class Class:
    extends Node
    signal _ready
    
    func do()->Object:
        emit_signal("_ready")
        return self

var bla = Class.new()
add_child(bla)
yield(bla.do(),"_ready")
#will never print bla
print("bla")
```

**Comment by pycbouh** [comment]
Please, follow the issue template provided when creating an issue. You also should provide a reproduction project so that your report can be tested. The code you supplied is not valid GDScript code, so it's impossible to tell where the issue lies.

On the superficial level it looks like you don't fully understand how signals works. We don't provide support on GitHub though, so you should ask around our [community platforms](https://godotengine.org/community/user-groups) for help.

If you fill the template and provide a reproduction project, the issue will be reopened.

**Comment by KoBeWi** [comment]
btw yield is removed in 4.0, so this is no longer relevant anyways.
