### ISSUE TITLE
`EditorInspectorPlugin` children go out of bounds when using `Control.set_anchors_and_margins_preset`

### ISSUE THREAD

**Issue by LightningAA** [godotengine/godot#47274]
**Godot version:**

3.2.3 stable

**OS/device including version:**

Windows 10, GLES2

**Issue description:**

Tried adding a label to a texture rect and set the label's anchors and margins to the bottom right preset, it caused the label to go off the screen.

Here's a screenshot from the minimal reproduction project showing a green panel added as a custom inspector control, and the green panel has a smaller red panel as a child of it and it's had it's anchors and margins set to the bottom left preset. You can't see the red panel as it's off the screen, but I'm using https://github.com/Zylann/godot_editor_debugger_plugin to highlight the red panel so you can see where it is.

![image](https://user-images.githubusercontent.com/50304111/112062839-1b6bcd80-8b26-11eb-9e22-d845aa371a39.png)

**Steps to reproduce:**
Create a control node. Add another control node as a child. Try and position the child node. Add the base control node as a custom editor control.

**Minimal reproduction project:**

[MinimumReproProject.zip](https://github.com/godotengine/godot/files/6185469/MinimumReproProject.zip)

**Comment by pycbouh** [comment]
You are not using containers. The second panel is bound to the left bottom corner of the first panel and then proceeds to grow in its natural direction: down and to the right.

If you want to overlay them, you need to use a container like `MarginContainer` and instead of anchors use size flags with appropriate values. (Namely, no horizontal flags and shrink end for vertical if you want to add the control to the bottol left).
