### ISSUE TITLE
Add a true, professional way, to unit test inside Visual Studio

### ISSUE THREAD

**Issue by evan-boissonnot** [godotengine/godot#47289]
I know there is an other issue about it, but it's really the same 
(

**Godot version:**

**OS/device including version:**
Windows

**Issue description:**
I'm developping our game use Visual Studio 2019, and godot mono 3.2.3.
In all my projects, there are Unit Tests.

I want to be able to run them with Visual Studio 2019, as ... normal Unit tests with my IDE.

It's impossible for now ...

I do not want to use WAT plugin (that is not running for C# or other tricks like https://github.com/NathanWarden/godot-test-tools), I just want normal and professionnal Unit tests, like normal Unit Tests in Visual Studio.

I want to create my unit tests to check :
- player moving, 
- animations starting and stopping, 
- displaying one scne or not, 
- etc ....

**Steps to reproduce:**
I try 3 ways :
- first, create mstest project for 4.7 framework, I got this error : https://github.com/godotengine/godot/issues/38775 (and it's not truue : it's a bug not a missing documentation, please).
- other way : I have created a xunit tests with .net core ... but our game project is in C# mono, so not okay
- other way : I have created a class library in 4.7 framework, I have a class and I use the nuget package Nunit.framework => Visual studio can see there is a unit test, I got the same error "OneTimeSetUp: System.Security.SecurityException: ECall methods must be packaged in a system module."

So please, tell me when we wil able to get true professionnal unit tests integration in vs 2019 for godot mono.

**Comment by pycbouh** [comment]
This repository is for bug reports only. If you want to make a feature proposal, you need to create it in the [https://github.com/godotengine/godot-proposals](Godot Proposals) repository, following the template there. That said, since you mentioned another issue existing, and I guess it's https://github.com/godotengine/godot-proposals/issues/432, you really shouldn't open a new one.

 You can show your support by putting a thumbs up reaction to the proposal issue. You can add more information to the proposal via comments.

**Comment by evan-boissonnot** [comment]
Wow, for now, it's a bug ... not a proposal .. because I get bug when I use it ......
strange reaction, isn't it ?
