### ISSUE TITLE
RichTextLabel loses its (simple) text after scene reopen in editor in Godot 4.0

### ISSUE THREAD

**Issue by felrugo** [godotengine/godot#47471]
Godot version:
4.0 commit: 02471ba44d4b00af51af7bb3061437c6001d2c88

OS/device including version:
Windows 10 1909

Issue description:
After reopening a Scene its RechTextLabel nodes lost their texts. The text fields were empty.
A small debug session showed that the attribute was saved in the .tscn file and in the load stage the set_text function of
RichTextLabel was called. Therefore the bug probably is in the implementation of the RichTextLabel and not in the ResourceLoader. 

Steps to reproduce:

1. Create a Scene with a Control root node and a RichTextLabel node as its child.
2. Set the text of the RichTextLabel and save the scene
3. Close the scene and reopen it
4. After the reopen the text field of the RichTextLabel is empty

**Comment by Calinou** [comment]
@felrugo Can you reproduce this on 3.2.3 or 3.3rc6?

**Comment by felrugo** [comment]
@Calinou No, it doesn't appear in the 3.2.3 and 3.3rc6 version, only in 4.0.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
It's overwritten by bbcode (even when bbcode value is not saved in the resource), `set_bbcode` and `set_text` code is the same as in 3.x, something has been changed in the resource loading process (maybe it's loading default values for the missing properties instead of skipping them).

The best solution probably is removing duplicate text/bbcode properties - #39148.
