### ISSUE TITLE
error decode variant condition "len <4 " | error executing exported project

### ISSUE THREAD

**Issue by jugador0** [godotengine/godot#47479]
Godot version:
3.2.3

Issue description:

Hi everyone, I'm really very new to github, I don't even know where to start, luckily I discovered the section for writing errors:

I have been trying for a long time to solve an error that only occurs when the game exe is running, I don't know why, since I am relatively new to programming, thank you very much in advance.

project:

[proyecto.zip](https://github.com/godotengine/godot/files/6225347/proyecto.zip)

**Comment by akien-mga** [comment]
Hi, this issue tracker is for engine bug reports, not user support. Your report has too little information to be able to identify an engine bug, most likely it's an issue with your project itself. Please use other community platforms to discuss it with other users and find what the problem is: https://godotengine.org/community

If it turns out to be an engine bug, then you can open an issue with clear steps to reproduce and a reproduction project (not your full game).
