### ISSUE TITLE
Using Division inside the float or decimal functions return unexpected results 

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#4753]
```
	print(float(0.25)) # This works fine, returns 0.25
	print(float( 25 / 100)) # Should be 0.25, returns 0
```

This bug **only happens when doing division**, float does work correctly **without division**

[Decimals ](http://docs.godotengine.org/en/latest/classes/class_@gdscript.html?highlight=decimals#class-gdscript-decimals) is a bit odd, too:

```
	print(decimals(0.25)) # Should be 0.25, returns 2
	print(decimals( 25 / 100)) # Should be 0.25, returns 0
```

**Comment by akien-mga** [comment]
That's not a bug, that's how most languages work. ``25 / 100`` is an ``int / int`` operation, so it must return an int, so it returns the integer part of 0.25, i.e. 0. The enclosing ``float()`` only returns the float version of 0, i.e. still 0. What you want is ``float(25)/100`` or ``25.0/100`` or ``25/100.0`` or ``25/float(100)``.

As for decimals, did you read the documentation you linked? :)

> Return the amount of decimals in the floating point value.

i.e. it returns 2 for 0.25 because they're are two decimals (two digits). It returns 0 for ``25 / 100`` since, as mentioned above, the result of this statement is 0.

**Comment by akien-mga** [comment]
Note that ``decimals`` is a bit buggy though, it suffers from float precision issues.

**Comment by Dillybob92** [comment]
Lol oh oops. Sorry about that. I would of never known. I am so used   to JavaScript I guess and was just doing math in the console to double check. Guess this is when I depart away from that language once and for all.
