### ISSUE TITLE
Selecting node with rectangle selection doesn't show it in the inspector

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#47555]
**Godot version:**

3.3 rc7

**Issue description:**

When you select a node with rectangle selection
![FvxmJd2Jyi](https://user-images.githubusercontent.com/2223172/113360847-e132d500-934a-11eb-897b-02fac30ff2c0.gif)
it doesn't show up in the inspector. It shows up only if you click it or select multiple nodes.

**Comment by lhalf** [comment]
Hi, I'd like to contribute and it's my first time contributing. Do you have any other information you could give about this issue please? Thanks!

**Comment by Calinou** [comment]
@lhalf The 2D editor code (including the rectangle selection) is here: https://github.com/godotengine/godot/blob/master/editor/plugins/canvas_item_editor_plugin.cpp

Compiling instructions can be found here: https://docs.godotengine.org/en/latest/development/compiling/index.html

Note that the `master` branch requires a GPU that supports Vulkan. If your GPU doesn't support Vulkan, use the `3.x` branch to test your changes, then port over your changes to the `master` branch so that you can open a pull request from the `master` branch.
