### ISSUE TITLE
LineEdit ctrl+backspace and ctrl+delete not working correctly

### ISSUE THREAD

**Issue by mujpao** [godotengine/godot#47557]
**Godot version:**
4b6e9f315739c4400e3c2d27cd72028779bce1e5

**OS/device including version:**
Ubuntu 20.04.2 LTS

**Issue description:**

Both ctrl+backspace and ctrl+delete are not working correctly on the LineEdit node.

Using ctrl+backspace deletes everything to the left of the cursor, instead of just the last word.
![lineedit_ctrl_backspace](https://user-images.githubusercontent.com/13281891/113361945-09e2ac80-9302-11eb-92da-fb31d34a7a62.gif)

Using ctrl+delete seems to be working correctly, except that it doesn't take effect immediately. The next word only gets deleted after you click on the LineEdit or press a key.
![lineedit_ctrl_delete](https://user-images.githubusercontent.com/13281891/113362064-55955600-9302-11eb-8138-8d6ac39e77a3.gif)

**Steps to reproduce:**
Create a LineEdit node. Run the scene. Add some text, and then try pressing ctrl+backspace and ctrl+delete.

**Minimal reproduction project:**

**Comment by EricEzaM** [comment]
I can reproduce both issues on Windows 10.

For the first one, looks like I just missed a `break` call when finding where to delete the text. Most likely a rebasing error, whoops! PR attached.

No idea at the moment for the second issue. Ctrl Delete works fine in the editor, it seems like the issue only exists in the project.

**Comment by EricEzaM** [comment]
Never mind, I found the second issue. After deleting (Ctrl Delete), the LineEdit was never updated. Other actions had `set_cursor_position()` called, which would in turn call `update()`, so they were visually updated properly. Adding a call to `set_cursor_position()` fixed the issue.

I think this was not happening in the editor because it has the setting to constantly update.
