### ISSUE TITLE
`@GlobalScope` and `@GDScript` function highlight is not consistent - could maybe use a dedicated color

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#47644]
**Details:**
![image](https://user-images.githubusercontent.com/58845030/113574705-05184400-95f3-11eb-8fdf-864ce5b53c2a.png)

**Issue description:**
the `@GlobalScope` functions doesnt highlight in the editor, altought they work:
![image](https://user-images.githubusercontent.com/58845030/113574643-e44fee80-95f2-11eb-88b4-446e3f0ec1ac.png)

**Steps to reproduce:**
* attach a script
* type some GlobalScope function: `randi() - randf_range()`

**Minimal reproduction project:**
N/A

**Comment by KoBeWi** [comment]
This might be intended actually.
CC @Paulb23

**Comment by akien-mga** [comment]
I'm not sure I understand the issue, what does "doesn't highlight" mean here? What's the different between the highlighting of `print`, `randi`, and `draw_line` in that screenshot?

**Comment by dalexeev** [comment]
![](https://user-images.githubusercontent.com/47700418/167082909-eb671648-18ea-430a-9dac-a77f99921d30.png)

**Comment by akien-mga** [comment]
So the bug is that `@GDScript` functions wrongly use the Keyword Color property instead of the Function Color one.

**Comment by dalexeev** [comment]
1. This is the same as in 3.x.
2. It makes sense to highlight global functions (`@GlobalScope` and `@GDScript`) in a different color, because they take precedence over methods ([`load` and `self.load`](https://github.com/godotengine/godot/pull/54949)). And besides, global functions are not first class functions (you can't pass `min` as a parameter to another function).

Perhaps the color of global functions should be different from the color of keywords. But it can also differ slightly from user-defined functions, for example:

![](https://user-images.githubusercontent.com/47700418/167087092-5b041476-5bcd-4514-9f82-715bce417501.png)

How it works for types:

![](https://user-images.githubusercontent.com/47700418/167087609-e9b1bde1-76a5-4c50-b204-0ce375c7a3bb.png)

**Comment by Calinou** [comment]
I'm not sure about introducing yet another color for global scope functions. Visual Studio Code doesn't seem to do this in its popular language highlighters such as C++, JavaScript or Python.

**Comment by MewPurPur** [comment]
I'd be down to work on this.
