### ISSUE TITLE
2D Soft Shadows

### ISSUE THREAD

**Issue by kenoph** [godotengine/godot#4785]
It would be nice to have 2d soft shadows in Godot.

![hard_shadow](https://cloud.githubusercontent.com/assets/1985669/15478160/0681fc36-2119-11e6-8fb4-c60d7e11f6c8.png)

As you can see, this doesn't look ok. I used CanvasModulate with a black color to remove the "global" light.

Something like the following would be way better:

![soft_shadow](http://kortham.net/temp/upshot_NJAvp9K4.png)

Actually, the option to put the light above/under a Sprite would also be useful (as seen here: [http://godotengine.org/qa/1588/how-to-disable-self-shadowing-in-2d?show=1789#c1789](http://godotengine.org/qa/1588/how-to-disable-self-shadowing-in-2d?show=1789#c1789))

**Comment by reduz** [comment]
This is too difficult to do with the GLES2 renderer, but with the new renderer for 3.0 it should be much easier.

**Comment by Asmageddon** [comment]
@reduz I have not tried implementing it myself, but I have seen algorithms that accomplish this by using triangles textured with a gradient, without any shaders or otherwise separate drawcalls being involved. 

![](http://archive.gamedev.net/images.gamedev.net/features/programming/2dsoftshadow/01Overview.gif)

Image source: https://www.gamedev.net/articles/programming/graphics/dynamic-2d-soft-shadows-r3065

**Comment by reduz** [comment]
This is already implememted in 3.0

**Comment by Asmageddon** [comment]
Oh! In that case, consider me as reminding that the issue can be closed :P

**Comment by Sungray** [comment]
How about the ability to put the shadow below a parent sprite ? A sprite with child LightOcclusion2D gets affected by the shadow. Is there any way around this ?
https://godotengine.org/qa/1588/how-to-disable-self-shadowing-in-2d?show=1789#c1789
