### ISSUE TITLE
3.3 - Skeleton IK - Starting then stopping breaks root bone positions while playing animations

### ISSUE THREAD

**Issue by yanorax** [godotengine/godot#47850]
**Godot version:**

3.2.3, 3.2.4RC4, 3.2.4RC8, 9c33f091cdede2fb805a624287c17738736135d4

**OS/device including version:**

Windows 10 64bit

**Issue description:**

I recently converted my main project from Godot 3.1.1 to 3.2.4RC4 and I have been using the new 3.3 release candidates as they have been coming out.

I use an AnimationTree state machine to drive my 3D characters and I start and stop the Skeleton IK node depending on which animation needs it or not.

In Godot 3.1.1 I was able to stop Skeleton IK and the currently playing animation would reassert its bone positions and continue on playing:

![IK_3 1](https://user-images.githubusercontent.com/25857669/114486197-ba30a900-9c50-11eb-98f0-276571ae9c5d.gif)

I encountered the root bone problem with RC6 https://github.com/godotengine/godot/issues/47381 so I went back to using RC4. I created a sample project for testing the following pull request - https://github.com/godotengine/godot/pull/47441 and I was able to switch between release candidates without seeing any problems in my main project.

Behaviour from RC6, root bone position is broken when Skeleton IK is enabled:

![IK_RC6](https://user-images.githubusercontent.com/25857669/114489717-f36c1780-9c56-11eb-9a2b-646701834b29.gif)

I tried RC8 yesterday and now my main project is not working properly - I am getting the root bone position problem whenever Skeleton IK is started then stopped. I tried going back to 3.2.4RC4 that used to work but now it's producing the wrong result as well. I tried the Windows 64bit build in https://github.com/godotengine/godot/pull/47738 but that did not help.

Behaviour from build 9c33f091cdede2fb805a624287c17738736135d4, stopping Skeleton IK does not allow bones to be moved by the animation player:

![IK_3 3](https://user-images.githubusercontent.com/25857669/114486306-fa902700-9c50-11eb-9f59-473cbf97ecc3.gif)

I tried my new sample project on another Windows machine that has never run Godot 3.2.3+, converted the 3.1.1 project and the new 3.3 version broke straight away. I can't explain the delay in seeing the wrong result on my main machine.

**Steps to reproduce:**

I have created a v3.1.1 sample project and the same project opened in 9c33f091cdede2fb805a624287c17738736135d4. 
Mouse click anywhere to toggle Skeleton IK on and off.

**Minimal reproduction project:**

[SkeletonIKTest_3.1.1.zip](https://github.com/godotengine/godot/files/6301034/SkeletonIKTest_3.1.1.zip)

[SkeletonIKTest_3.3.zip](https://github.com/godotengine/godot/files/6301035/SkeletonIKTest_3.3.zip)

**Comment by akien-mga** [comment]
CC @AndreaCatania @TwistedTwigleg

**Comment by TwistedTwigleg** [comment]
Strange, it looks like the bone's are not reset correctly. Probably what is happening is the global bone pose override strength is not being reset to `0`.

If IK is being started and stopped using the `start` and `stop` functions respectively, it could be the issue is that the `stop` function doesn't reset the global bone pose overrides. If IK is being started and stopped by setting the interpolation to `0`, then its probably something in the condition that checks if the interpolation strength is `0` that is not working.

**Comment by smix8** [comment]
I think the issue is that the SkeletonIK node if stopped is only calling the `clear_bones_global_pose_override()` on the parent Skeleton node.

This function only clears the global_pose_override interpolation value to zero but not the persistent flag so everything stays frozen.

```
skeleton.cpp::383

void Skeleton::clear_bones_global_pose_override() {
	for (int i = 0; i < bones.size(); i += 1) {
		bones.write[i].global_pose_override_amount = 0;		
		bones.write[i].global_pose_override_reset = true;
	}
	_make_dirty();
}
```
... adding the `bones.write[i].global_pose_override_reset = true;` fixes it but I don't know if this has any sideeffects to other skeleton features that rely on current `clear_bones_global_pose_override()` behavior.

**Comment by TwistedTwigleg** [comment]
I will try to look into this once I have a chance. A fix like @smix8 mentioned is probably the best solution, at least short term. It may also be potentially be possible to use the global pose override without setting it to be persistent in the SkeletonIK node, though this may cause regressions and/or unintended side effects.
