### ISSUE TITLE
EditorScript: run shortcut (Ctrl+Shift+X) triggers cut shortcut (Control+X) if text is selected

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#47873]
**Godot version:**
3.2.3.stable

**OS/device including version:**
Windows 7

**Issue description:** 
EditorScript: run shortcut (Ctrl+Shift+X) triggers cut shortcut (Control+X) if text is selected.

**Steps to reproduce:**

1. Add an EditorScript:

```
tool
extends EditorScript

func _run() -> void:
	pass
```
2. Select some text.
![tGZ3nIEdgy](https://user-images.githubusercontent.com/9283098/114633231-75dcf180-9cc0-11eb-8e64-78eea5fa48db.png)

3. Control+Shift+X to run.
![Godot_v3 2 3-stable_win64_AYdI0i5vAJ](https://user-images.githubusercontent.com/9283098/114633205-68276c00-9cc0-11eb-81fd-587f18859bb5.png)

**Minimal reproduction project:**
[EditorScriptRunShortcutBug.zip](https://github.com/godotengine/godot/files/6307216/EditorScriptRunShortcutBug.zip)

**Comment by EricEzaM** [comment]
I have tested this issue and can confirm it is *not* apparent in the master branch.

I think this is a combination of 2 existing issues which are both fixed in master, but unlikely to get a backport to 3.X.
First relevant one, shortcut contexts: #42109
Second relevant one, checking shortcuts "exactly" to avoid overlap like this.

**Comment by kleonc** [comment]
Closing per @EricEzaM comment (and seeing similar issues are closed with `4.0` milestone and without a separate fix for `3.x`).
