### ISSUE TITLE
GDScript is buggy when it comes to onready accessor properties

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#47904]
**Godot version:**
3.2.3 
requires mono to test

**OS/device including version:**

Kubuntu 20.10

**Issue description:**
sometimes onready nodepaths do not exist when using them in properties

**Steps to reproduce:**
- Download project
- Run it through its startup scene (Control.tcsn)
- See that cs script works but gd script doesn't even though the code is the same

Note that its tends to happen with nested scenes and multi script variable accessors 

**Minimal reproduction project:**
[Accesser Property Bug.zip](https://github.com/godotengine/godot/files/6314943/Accesser.Property.Bug.zip)

**Comment by Shadowblitz16** [comment]
@Duroxxigar please look at the example before downvoting

**Comment by Shadowblitz16** [comment]
Looks like cs is having errors too. 
I didn't see it due to the program not crashing like it did with gdscript.

I will do more testing, but for now I'm closing this

**Comment by Duroxxigar** [comment]
I downvoted because we spent an hour in chat explaining to you why things are behaving the way they were, even explained that the same thing would happen in C#. This isn't a "buggy" thing. This is you not understanding the creation process.

> sometimes onready nodepaths do not exist when using them in properties

Yes, as explained in chat, you cannot access other nodes before _ready. You are trying to access it during initialization. You cannot do this.

**Comment by Shadowblitz16** [comment]
@Duroxxigar The problem comes from that fact scripts are initialized before the node is ready.
removing enter_tree, _exiting_tree and _exited_tree in favor of _ready, _destroyed, and _destroying would fix this issue.
then we wouldn't even need onready variables to begin with

**Comment by Duroxxigar** [comment]
There isn't an issue. You do not understand the framework. I do not understand why you are so reluctant to learn it.

The script is an extension of the node. Of course they get initialized when they get created. As has been explained to you many times now, you are creating an object in memory when creating the node. It gets initialized at this point. That doesn't mean it can try to walk the scene tree. At this point in time, the node has no understanding of the scene tree. It simply means an object was created in memory.

_ready is when the node entered the scene tree and all of its children are ready as well, IE - their _ready notification have ran.

If you want to change this - open a proposal, because Godot is functioning as expected in this situation.

**Comment by Shadowblitz16** [comment]
@Duroxxigar I understand how it works.
however the script does not need to be initialized until the node is ready.
it could be delayed.

I have explained this to you guys many times but you don't seem to get it.

I have actually talked about this on the C# discord with professional C# devs and they say it is possible but again the api would have to take this in account which it doesn't 

so either its api issue or a gdscript one

**Comment by Duroxxigar** [comment]
I do not care who you spoke to. You can speak to John Carmack for all I care.

You clearly do not understand what is going on. The script is an extension of the node. It is an unnamed class. You are creating it in memory. You can interact with it and configure things and do whatever you want, other than scene tree operations - such as trying to get a reference to another node that you are getting by walking the scene tree.

Again - the C# equivalent would be to create a class, that has something like `public Person Driver`, so it expects to have a reference to something of type "Person". In the constructor, you do not initialize it. Then, you try to access it before having an object of Person to even reference. If you do this, you will get a Null Reference Exception. This is the equivalent of what you are trying to do in GDScript.

This will fail in literally any language out there. Because the thing you are trying to access simply does not exist to the knowledge of the class. The core problem is that you are relying on a scene tree operation - prior to even being in the scene tree. The scene tree is something that can be completely avoided if so desired.
