### ISSUE TITLE
Vulkan: Black screen and errors in the console when shaders are compiled on macOS

### ISSUE THREAD

**Issue by HonestHacker** [godotengine/godot#47909]
___

***Bugsquad edit:** This bug has been confirmed several times already. No need to confirm it further.*

___

**Godot version:** v4.0.dev.calinou.a86e7c3bb

**OS/device including version:** macOS 11.0 Big Sur

**Issue description:** Errors of shaders at Backtrace and black window with "Please confirm..."
![Снимок экрана 2021-04-15 в 10 20 35](https://user-images.githubusercontent.com/66554952/114830267-b9c11b00-9dd4-11eb-8992-15b9ddc5d58a.png)

**Comment by akien-mga** [comment]
> Godot version: 4

Please be more specific, this number covers more than a year of development.

**Comment by akien-mga** [comment]
Additionally, try to update your MoltenVK version, and paste the full output from the terminal, not a screenshot. We can't do much with just the tail of the error log.

**Comment by HonestHacker** [comment]
@akien-mga It's so horrible! Там слишком много ошибок!

**Comment by HonestHacker** [comment]
I update MoltenVK, but Godot don't want work.

**Comment by lucicam** [comment]
Since the original poster did not provide more info about his error, I will, because it's been bothering me also that I can't run 4.0 and as such I can't properly contribute to it. 
In my case, I'm running macOS Mojave 10.14.6, and I have MoltenVK installed. 
The engine I'm running to test is compiled from latest master branch as of today. The result is a LOT of errors and a black screen:
![image](https://user-images.githubusercontent.com/23422632/115440319-49712a00-a218-11eb-8305-4a0a6579f78a.png)

Log is as follows (I put only a part of it here because it goes like this forever):

%> ./godot.osx.tools.64
arguments
0: ./godot.osx.tools.64
Current path: /Users/lucicam/Workspace/Test Workspace/godot-code-my-fork/bin
Godot Engine v4.0.dev.custom_build.c36807994 - https://godotengine.org
Vulkan API 1.2.162
Using Vulkan Device #0: INTEL - Intel(R) Iris(TM) Graphics 6100
- Vulkan subgroup size 1
- Vulkan subgroup stages STAGE_TESSELLATION_CONTROL, STAGE_COMPUTE
- Vulkan subgroup supported ops FEATURE_BASIC
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:92:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:92:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 140475637637264
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140475637672480
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: compute_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:5770)
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:92:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:92:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 140475635624224
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140475635671264
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: compute_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:5770)
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:94:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:94:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 140475636458176
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140475637186208
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: compute_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:5770)
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:94:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
program_source:95:47: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_auto_exposureSwzl = spvSwizzleConstants[1];
                                              ^
.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:94:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
program_source:95:47: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_auto_exposureSwzl = spvSwizzleConstants[1];
                                              ^
.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_SHADER_MODULE, Handle 140475634633424
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
	Objects - 1
		Object[0] - VK_OBJECT_TYPE_PIPELINE, Handle 140475637186208
   at: _debug_messenger_callback (drivers/vulkan/vulkan_context.cpp:156)
ERROR: vkCreateComputePipelines failed with error -1000012000.
   at: compute_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:5770)
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:92:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
.
ERROR:  - Message Id Number: 0 | Message Id Name:
	VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
Compilation failed:

program_source:92:39: error: use of undeclared identifier 'spvSwizzleConstants'
    constant uint& source_colorSwzl = spvSwizzleConstants[0];
                                      ^
..........
To infinity and beyond...

**Comment by lucicam** [comment]
Let me know if I can provide more details regarding this problem in helping solving it

**Comment by HonestHacker** [comment]
@lucicam I have the same thing

**Comment by HonestHacker** [comment]
OK, I'm working for detect and correction for this error.

**Comment by molevision** [comment]
I have the same issue, on Mojave 10.14.6 with the AMD Radeon M9 370X. Will be happy to provide any help with testing.

<img width="1016" alt="Screen Shot 2021-06-18 at 23 15 25" src="https://user-images.githubusercontent.com/9658355/122602171-00aae580-d090-11eb-8540-47d45205d02b.png">

**Comment by HonestHacker** [comment]
I'm closed this problem, because i download from [https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210727/](https://downloads.tuxfamily.org/godotengine/testing/4.0/4.0-dev.20210727/) and it's working. RECOMENDED

**Comment by lucicam** [comment]
How does this fix the issue? I upgraded to latest version of Big Sur 11.6, and I still can't compile and run it because of the same error. If you can't compile and run it, then you can't debug it and contribute... And it seems like I'm no the only one having issues with this.

The latest documentation says:
> If you are building the master branch, you also need to include support for the MoltenVK Vulkan portability library. You can do so either by building it statically with use_static_mvk=yes, or by including the dynamic library in your .app bundle:

But I have tried using use_static_mkv and also adding the MoltenVK library in the .app bundle and I just couldn't get it to work even as of today...

**Comment by akien-mga** [comment]
@lucicam Yours is a different issue, you seem to have issue with compiling from source, while @HonestHacker had issues running official binaries.

Do official binaries work for you?

> If you are building the master branch, you also need to include support for the MoltenVK Vulkan portability library. You can do so either by building it statically with use_static_mvk=yes, or by including the dynamic library in your .app bundle:

That's slightly outdated and needs to be updated, please open an issue on the docs repo.

**Comment by lucicam** [comment]
It seems like running one of the binaries from the same link that the author posted here does indeed work. So then am I doing some thing wrong while compiling it? What should I do different when compiling it?
