### ISSUE TITLE
Use of All files access (MANAGE_EXTERNAL_STORAGE) permission

### ISSUE THREAD

**Issue by SkanerSoft** [godotengine/godot#47910]
**Godot version:**
3.3 RC 9

**OS/device including version:**
Android

**Issue description:**
I can't argue that this is a bug, but I got an unpleasant feeling from the message I received on Google Play.
Google says it will remove my games that use file access, and I'm not sure if I know what to do about it.

More details are written here: https://support.google.com/googleplay/android-developer/answer/10467955

Also, I did not find the necessary settings when exporting, perhaps some explanation is required on working with flags or the manifest directly.

**Comment by akien-mga** [comment]
Related to #39414 and #38913.

@m4gr3d I suggest we make the flag in #39103 configurable (and *opt-in*) for 3.3 so that only users who actually need access to external storage will get this warning, and will have to justify their use after May 5.

And then we really need to fix #38913 for 3.3.1 before May 5.

**Comment by akien-mga** [comment]
Fixed by #47954. (For users who don't use external storage.)
