### ISSUE TITLE
3.3 bone names in gltf are no longer modified affecting BoneAttachment and AnimationTree

### ISSUE THREAD

**Issue by ereyre** [godotengine/godot#47977]
**Godot version:**
3.3.rc9

**OS/device including version:**
Windows GLES3

**Issue description:**
Regression
when importing (when project dl from git) / or reimporing a Gltf file (if the file was already in the .import subdire before upgrading) ,  in 3.2.3 , the importer change bones names  (ie : LowerLid.L -> lover_lid_l) 
In 3.3.rc9 that not the case.
majors isue with : 
  * bone attachement point : it roll back to root bone (Bone Name)
  * in Animation Tree : when using a filter in a blend node, all seting are lost

**Steps to reproduce:**

just import a Gltf file with a rig, where bones are named like "UpperLeg.L" 
in 3.2.3, add an attachement point linked to this bone
upgrade the project to 3.3rc9
select the gltf file
reimport it
the attachement point should default to a bone that dont exist / default to root  of the rig
The attached bone dont follow the rig

**Minimal reproduction project:**
in bledner the bone is named Hip.L

In 3.2.3, we set a bone attachement to the bone named hip.l
![BoneAttachement 3 3](https://user-images.githubusercontent.com/5115601/115115971-84b0f600-9f97-11eb-96a6-e718403592fd.png)
after reimporting the mesh in 3.3, the bonne change name to Hip.L (which is correct), but the bone attachement point is no longer functional
![Bonne attachement V3 2 3](https://user-images.githubusercontent.com/5115601/115115972-85498c80-9f97-11eb-8473-5c1d1e6ece7a.png)

Bone name after reimporting in 3.3
![Bone name after import](https://user-images.githubusercontent.com/5115601/115115970-84185f80-9f97-11eb-917d-60e36b5a2676.png)

[MinimalRigProject.zip](https://github.com/godotengine/godot/files/6329381/MinimalRigProject.zip)

**Comment by fire** [comment]
Investigating:

1. Bone Attachment broken
2. Animation Tree: When using a filter in a blend node, all setting are lost

**Comment by lyuma** [comment]
@ereyre Nice observation!
> if the file was already in the .import subdire before upgrading

I think this leads to an obvious and simple way to address this compatibility breakage:

My opinion is to add a compatibility flag to `XXXX.gltf.import` like:
```
use_legacy_compatible_bone_names = 1
```
and it can default to **1 if not present in the .import** file, but **write 0 when importing a new file** if the .import is not yet present. That way, newly imported files get to take advantage of the internationalized bone names, but existing projects will not be corrupted!

I think the new import setting would be a simple and effective fix for the **cause** of the issue, without needing to address *migration* of existing content or *flimsiness* of bone attachment when the underlying bones change name (which would otherwise be a hard problem to solve especially at an *rc9* stage)

**Comment by ereyre** [comment]
@lyuma  such solution would be perfect.

**Comment by akien-mga** [comment]
Fixed by #48058.
