### ISSUE TITLE
get_var ( ) returns null when opening files

### ISSUE THREAD

**Issue by holzmb** [godotengine/godot#47971]
**Godot version:**
3.3rc9

**OS/device including version:**
linux

**Issue description:**
I'm opening savegame files with get_var() but it return null instead of whatever it was saved.

prints out this error msg
ERROR: get_var: Condition "(uint32_t)buff.size() != len" is true. Returned: Variant()
   At: core/bind/core_bind.cpp:2307.

**Steps to reproduce:**
Needs to be some recent thing cause rc8 works fine.

**Comment by KoBeWi** [comment]
Any minimal project or sample code?

**Comment by holzmb** [comment]
@KoBeWi 
[get_var_test.zip](https://github.com/godotengine/godot/files/6329080/get_var_test.zip)

click save game, it will write some dictionary to the file, then load it and it will print the dict in the label.
it works with all rc versions but rc9 which returns null

**Comment by holzmb** [comment]
after looking around it's probably this
https://github.com/godotengine/godot/commit/9a7e537aac0fd251cc500d39e41224c7bf2fdf48

**Comment by akien-mga** [comment]
> after looking around it's probably this
> [9a7e537](https://github.com/godotengine/godot/commit/9a7e537aac0fd251cc500d39e41224c7bf2fdf48)

Indeed, confirmed that it's a regression from this cherry-pick / PR #47811. CC @HaSa1002.

**Comment by akien-mga** [comment]
I pushed 701fa8a779 to revert the change in `3.x` and fix this issue.

I haven't reverted it in `master` yet though as we should investigate whether the change was wrong, or whether more changes are needed to accommodate for it.

**Comment by HaSa1002** [comment]
Ok. I take a look at it.

**Comment by HaSa1002** [comment]
So issue is, `buff.size()` is `len -1`. I will check why this is the case

**Comment by HaSa1002** [comment]
So it looks like, this is a wrong fail condition resulting from the old behaviour. I changed it to check for len - 1  and the parsing just works fine... But, I don't trust my judgement, because this regression happend in the first place, so let me check where else `get_buffer()` is used and if there are fail checks like this.

**Comment by HaSa1002** [comment]
So indeed the issue is that the size of the the buffer is stored and fread returns the number of read elements. That is why `buff.size() == len -1`. Fixing the error_fail_cond should be enough.

**Comment by theraot** [comment]
Listen, https://github.com/godotengine/godot/pull/47811 is correct. It fixes https://github.com/godotengine/godot/issues/51959.

The present issue does not happen when using `open` instead of `open_compressed`. Thus, I believe the investigation to find a solution should should begin at `open_compressed` (I'm and clueless about how that works, so I don't think I can provide a solution).
