### ISSUE TITLE
VisibilityNotifier2D doesn't notifies as soon as it's out of viewport

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4803]
**Godot version:** Built from master

VisibilityNotifier2D doesn't notifies as soon as it's out of viewport, there seem to be son kind of internal offset. It's the same for "exit_viewport" and "exit_screen" signal.

EDIT:

Here is a demo: 
[QuickTest.zip](https://github.com/godotengine/godot/files/287543/QuickTest.zip) (Arrow keys to move the sprite/visibilitynotifier out the view)

**Comment by neikeq** [comment]
I don't understand the issue correctly. Could you specify a bit more? It would be also helpful to provide an example project, if possible.

**Comment by EdwardAngeles** [comment]
Sorry for the delay, I uploaded a demo. :)

**Comment by neikeq** [comment]
I could reproduce it with the example project. It's weird because I had a similar demo I did around a month ago and there was no such issue. It may be a recent regression.

**Comment by Razzlegames** [comment]
I've confirmed this behavior.  Oddly enough, if you are in windowed mode and resize the screen using your mouse, I am able to see correct behavior on some window dimensions.

**Comment by reduz** [comment]
This is intended behavior, VisibilityNotifier uses a hashed grid to quickly determine when something is near the screen, so it's really really fast even if you have thousands of objects moving. The downside is that it's approximate but not exact. 

It is warranted that the notifier will always be visible when on the screen though. Maybe this should be documented..

**Comment by razvanc-r** [comment]
Well, I wanted to remove bullets using this node, but I ran in the same problem. I wouldn't have an issue with the `VisibilityNotifier2D` being triggered AFTER it leaves the screen/viewport, but `exit_screen`, `exit_viewport` signals are emitted BEFORE leaving the screen/viewport in some cases.

I have a 1920x1080 px resolution project with `stretch_mode` set to `2d` in the Project Settings. The bullets have `VisibilityNotifier2D` set to `queue_free` when signals are emitted. See the result in the attached gif.
![2016-12-01 17-57-bd02-visibilitynotifier](https://cloud.githubusercontent.com/assets/1177508/20804222/5a6943f2-b7f2-11e6-8ea7-20a7c77b5b45.gif)

**Comment by RandomShaper** [comment]
I've hit the same issue when I've set my stretch mode to 2d with keep aspect: the `VisibilityNotifier2D` seemed to be offset as much as the viewport in relation to the window.

I've tried a quick fix (https://github.com/RandomShaper/godot/commit/13451dabf69cc94e19198168e0c586a698208a73). What this does is passing the viewport rect to the `VisibilityNotifier2D` positioned at (0, 0) before applying the transform.

Please test. I'm not sending a PR unless we are sure this works for every stretch mode and keep aspect setting. I'm pretty tired right now and I'm not very confident about this.

**Comment by eon-s** [comment]
@RandomShaper I've tried your fix for 2.1 but it is not making any difference.

I don't think is an offset because it affects all sides on my tests (like if the notifier area is 3x bigger than it should).

**Comment by RandomShaper** [comment]
In this topic there are two issues:

  * The notifiers being considered visible although they are not
    actually inside the viewport, just when they get close.
    This one is expected behaviour and can't be fixed. The engine only
    guarantees the notifier is out-of-view when it's notified as being
    so, but for the case of becoming visible it can notify before the
    viewport is actually entered because of the optimizations used by
    the implementation.
  * The other one is nodes being notified as no-longer-visible before
    they actually leave the viewport, but this one only happens on one
    edge because of the offset.
    If you were able to see it, at the opposite edge they would need to
    be even further than usual to be notified as no-longer-visible.
    This is the one I'm trying to fix.

Which one are you talking about?

What we aim to fix here is not the size

**Comment by eon-s** [comment]
@RandomShaper ah, ok, I think that only got the first but for both, visible and not visible, on 2.1.2 and the fixed version.

Is weird because in one project I have noticed the offset and got almost perfect edge notifications but on another got the on/off screen notifications far from the edges (outside of the screen), no offset.

I will continue trying to see if I can trigger the offset and test the fix properly.

**Comment by Razzlegames** [comment]
If you do this, you should probably create a more exact notifier class (or
a parameter to enable), with this change, and leave the old one alone.  The
less granular checks are proposed to be faster given large amounts of
objects (see above) at the expense of accuracy.

Perfect notifications probably fit a narrow use case and should be treated
as such.

**Comment by vortexofdoom** [comment]
I was going to open my own issue, but it fits very well with the discussion here.

From a design standpoint, it seems like VisibilityEnabler2D should be very well suited for keeping track of a countably limited number of nodes that you want to keep in the hierarchy but not have running.

However, when I tried to implement it in a project (making enemies deactivate when off screen, I'm finding that they often can walk out of the scene without disabling, and that I sometimes have to not be one but two screens over (with a jumping camera that works in cells) before they deactivate. In short, it doesn't work as predicted out of the box, and I don't know that mine really qualifies as an "edge" case for the node.

The current workaround involves adding an Area2D to the camera and using that to manually disable the various properties, but it strikes me as hacky, and not ideal when there's a core class designed for that exact purpose

After investigating, it seems that it's possible that this is due to the above comment by @reduz about how VisibilityNotifier works, which is definitely a reasonable implementation for less countable use cases (like destroying offscreen projectiles in a bullet hell for instance).

I think a parameter for adding more precision is something that VisibilityNotifier2D needs. That kind of precision is not going to be needed with the kind of scalability that the current implementation offers, so I don't think a trade-off in that department is prohibitive.

Thoughts?

**Comment by eon-s** [comment]
Configurable precision would be nice, but that may need to be applied project wide on VisualServer settings, depending on how this is working.

**Comment by vortexofdoom** [comment]
In that case, I'd think the grid hash for everything would have to either be less/more granular or replaced with a different less performant method? That definitely seems like a potentially big effect for this.

**Comment by nezvers** [comment]
2x screens or more away is not how Visibility Notification should work!
I'm on 3.2 and I'm forced to do some hacky calculation that is not even near as performant. 
If I do checks against camera positions, that is not always the correct way to tell a drawn rect position.
If I do against a player, then it's a hustle to make it null instance safe.

**Comment by Razzlegames** [comment]
@nezvers It's OK for most use cases, is the thought, since it's performant (more of a heuristic).  

>If you do this, you should probably create a more exact notifier class (or
a parameter to enable)

>  think a parameter for adding more precision is something that VisibilityNotifier2D needs

**Comment by RandomShaper** [comment]
> 2x screens or more away is not how Visibility Notification should work!

The cell size (i,e., the granularity of the detection) is 100 pixels. If you could provide a minimal reproduction project that does it as close as possible to your actual project, that'd help.

**Comment by nezvers** [comment]
Ok, here it is. My game is 160x90 resolution and this imprecision is really problematic.
[VisualNotificationBug.zip](https://github.com/godotengine/godot/files/4350091/VisualNotificationBug.zip)
