### ISSUE TITLE
NodePath::get_parent has no function definition

### ISSUE THREAD

**Issue by briansemrau** [godotengine/godot#48100]
**Godot version:**

All versions.
(3.3, master c7b97f0)

**OS/device including version:**

N/A

**Issue description:**

In `node_path.h`, there is an unimplemented function:
```cpp
NodePath get_parent() const;
```

I expect this function to return the nodepath one node above (`Some/Node/Path` → `Some/Node`), but this is not implemented. It should either be implemented or removed.

I believe this is the code to achieve this behavior:
```cpp
Vector<StringName> names = nodepath.get_names();
names.resize(names.size() - 1);
NodePath parent_path = NodePath(names, nodepath.is_absolute());
```

**Comment by kleonc** [comment]
And it's like this since [forever](https://github.com/godotengine/godot/tree/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac):
- [path_db.h](https://github.com/godotengine/godot/blob/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/core/path_db.h#L77),
- [path_db.cpp](https://github.com/godotengine/godot/blob/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/core/path_db.cpp).
