### ISSUE TITLE
Cannot compare `null` with e.g. `int`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#48150]
**Godot version:**
4.0.dev.custom_build. 759b876b8

**Issue description:**
This code runs fine in Godot 3.2
```gdscript
func _ready():	
	var i : int = 0
	if i != null:
		pass
```

shows errors
```
SCRIPT ERROR: Parse Error: Invalid operands "int" and "null" for "!=" operator.
          at: GDScript::reload (res://main.gd:6)
ERROR: Method/function failed. Returning: ERR_PARSE_ERROR
   at: reload (modules/gdscript/gdscript.cpp:836)
```

**Comment by akien-mga** [comment]
I don't see why this would be a bug? The bug seems to be that this works in Godot 3.2.

**Comment by qarmin** [comment]
This is only simple example, but I used this in similar way to
```
func _ready() -> void:
	var box : BoxShape = null
	var box2 : BoxShape = BoxShape.new()
	var i : int = 2
	
	printer(box)
	printer(box2)
	printer(i)
	
func printer(variable) -> void:
	if variable == null:
		return
	
	print(variable)
```
I can change `variable == null` to `typeof(variable) == TYPE_NIL` which will do exactly same, but I assumed that since it worked before, then it is regression.

**Comment by megalobyte** [comment]
I also ran into this problem when trying to compare a `float` with `null` using a custom build (`v3.4.beta.mono.custom_build.1f0e57021`). I'm pretty sure all `Variant` types can't be compared to `null`. If this is deemed an issue, I think it was introduced by #43323

**Comment by t3nk3y** [comment]
Throwing a "me too" along with another example.  In my case, I am using a function that expects a variant type.  And it is supposed to be checking to see the variable is null(or otherwise empty).  The function is supposed to not know the type, I'm actually intending to use this as a weakly typed function, and not explicitly defining any types.

```GDScript
@extends Node
#remove the @ to test in 3.x

export var this_is_a_string = ""
export var this_is_an_int = 0

func func_with_variant(the_var):
	return the_var == null

func _ready():
	func_with_variant(this_is_a_string)
```

Is this stronger typing intended?  If so, there isn't a great way to generically check for null/Nil

If the plan is to do away with `== null` then can we get `is Nil` instead of having to use `typeof(val) == TYPE_NIL`?  It seems that `is` works with every other type, except Nil, which is just triggering me when my code blocks are getting these mixed styles.
