### ISSUE TITLE
Geometry not visible on imported FBX files, both 3.3 and 4.0

### ISSUE THREAD

**Issue by rogerdv** [godotengine/godot#48155]
**Godot version:**
3.3 and 4.0 (updated from a week ago)

**OS/device including version:**
Linux Mint, RX 5500 XT with open source drivers. 

**Issue description:**
If I export a model from Blender (tried both 2.82 and 2.90) only the armature is visible, the geometry is there (a meshInstance) but it is not visible.

**Steps to reproduce:**
[geometrybug.zip](https://github.com/godotengine/godot/files/6369637/geometrybug.zip)

**Minimal reproduction project:**
Any project will do, just export the attached blend file.

**Comment by Calinou** [comment]
cc @RevoluPowered

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
