### ISSUE TITLE
Animated FBX model that worked fine in v3.2.3 is broken in v3.3

### ISSUE THREAD

**Issue by lumenwrites** [godotengine/godot#48191]
**Godot version:** 3.3

**OS/device including version:** macOS Catalina

**Issue description:**

I'm trying to import an animated fbx model. The FBX file contains a simple rigged and animated character model with a walk cycle. The animation works fine in godot 3.2.3, but it is broken in 3.3 - the character's legs are imported incorrectly, with upper leg part missing, and lower legs and feet animated incorrectly.

**Steps to reproduce:**

- Download the [FBX File](https://www.dropbox.com/s/xxxywyzrl446hl3/charlie.fbx?dl=0).
- Import it to godot (set the Root Scale to 100 to fix the scaling issue).
- Click on the AnimationPlayer node, playback the animation, look at the character's legs. It will work fine in Godot 3.2.3, but will be broken in Godot 3.3.

Can you guys help me out? How can I fix the issue? Is there any workaround to this?

Maybe there's some issue with the IK on the rig? I don't know, just a guess.

Edit:

Oh, and another problem - it looks like in 3.3, every node has a keyframe on it every frame. And in 3.2.3, the keyframes exist only on animated nodes (the way it should be).

Edit2:

The difference seems to be that some of the nodes in 3.3 (specifically `left_upper_leg` and `right_upper_leg`) are imported as "Skeleton" type nodes. In 3.2.3 these nodes are imported as "Spatial" nodes, that's why it works correctly.

Strangely enough, there are all kinds of bones in the character, but only the upper leg ones are imported as "Skeleton". I don't know what the difference is.

Is there any way that I can make godot import everything as "Spatial", maybe with an import script of some kind?

Edit 3:

Right clicking on the Skeleton nodes and doing Change Type > Spatial makes the character's upper legs reappear, but the animation is totally broken.

**Comment by Ehobits** [comment]
I think we ran into the same problem

Model animation is incorrect

Godot version:
This problem exists in both v3.3 and v4.0bate

operating system:
windows

Problem Description:
When playing FBX animation, all sides of the model are confused, which causes the animation to not play normally and the model displays abnormally.

Steps to reproduce:
Import FBX files with bones and animations;
Double-click spatial to view the content;
Try to click the AnimationPlayer node to play the animation;
---The model is displayed abnormally.

ps:
When importing FBX without bones and animation, everything is normal;
The problem seems to only appear when there are animations or poses that need to be presented;
So the problem probably lies in the process of how the bones of the model determine the changes in the model surface.
[test.zip](https://github.com/godotengine/godot/files/6418684/test.zip)

**Comment by Calinou** [comment]
> Happens to me too. Model with animations that worked great in 3.x is scattered around in 4.x when no animation is playing. When I select one of the animations, it somewhat resembles the animation, but the end bones are messed up (in wrong positions)

If the model looks good in 3.3/3.4 and bad in `master`, it's an entirely different issue. Please open a separate issue for this.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
