### ISSUE TITLE
Editor no longer supports Mac OS X 10.11

### ISSUE THREAD

**Issue by Avantir-Chaosfire** [godotengine/godot#48222]
**Godot version:**
3.3, I think. It's the latest Steam version as of April 26th, 2021. I don't know how to check the version as I can't open the app.

**OS/device including version:**
Mac OS X 10.11.6

**Issue description:**
The app crashes instantly on startup when launched from Steam. I launched the app from Terminal and got this:
```
<Computer Name>:Godot Engine <User Name>$ ./Godot.app/Contents/MacOS/Godot 
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: /Users/<User Name>/Library/Application Support/Steam/SteamApps/common/Godot Engine/./Godot.app/Contents/MacOS/Godot (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: /Users/<User Name>/Library/Application Support/Steam/SteamApps/common/Godot Engine/./Godot.app/Contents/MacOS/Godot (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libc++.1.dylib

Trace/BPT trap: 5
```

It's worth noting that the Steam page lists the minimum requirements as OpenGL 2.1. OS version is not specified.

**Comment by akien-mga** [comment]
Thanks for the report, I've fixed the Steam page to specify that it requires macOS 10.12.

The requirement change is expected, it's a consequence of using C++14 standard library in #45618.

Could you check if manually changing the `10.9` versions to `10.12` in `/Users/<User Name>/Library/Application Support/Steam/SteamApps/common/Godot Engine/./Godot.app/Contents/Info.plist` changes the behavior? E.g. whether it would make macOS give you a friendly error dialog that this version doesn't support your OS, instead of crashing.

**Comment by Avantir-Chaosfire** [comment]
I did this:
![Min Version](https://user-images.githubusercontent.com/11003232/116633177-af8f3880-a90d-11eb-80f5-05dd203f3c7a.png)
Which didn't seem to have any effect, when launched via Steam or via Terminal.

**Comment by jasonliu--** [comment]
Greetings, I am the creator and maintainer of the Godot package for the [MacPorts package management system](https://www.macports.org/).

I realize that this issue is being reported for Godot Engine on Steam, but I'd just like to point out that on MacPorts, I've been able to get Godot 3.3+ working on old versions of macOS, all the way back to 10.8 (Mountain Lion):

https://ports.macports.org/port/godot/details/

The publicly available package is a couple of patch versions behind, but I already have a MacPorts package prepared for Godot 3.4 that is running, without issues, locally on my macOS 10.11 laptop.

If you _really_ want to run the latest Godot on an old version of macOS, might I suggest giving MacPorts a try?

(CC @akien-mga)

**Comment by Calinou** [comment]
@Avantir-Chaosfire If you still have access to macOS 10.11, do you get a user-friendly error message when trying to run 3.5.2?

**Comment by Calinou** [comment]
Closing due to lack of response.
