### ISSUE TITLE
Godot's import of gltf misname skeleton's bones

### ISSUE THREAD

**Issue by aakord** [godotengine/godot#48247]
**Godot version:**
Godot 3.3 stable

**OS/device including version:**
Linux (Ubuntu Gorilla)

**Issue description:**
Godot 3.3-rc9 correctly import bone name from GLTF exported by blender.
ie: _Bone.001_ in blender is named _Bone.001_
However, when Godot 3.3-stable is used to import, the same bone is named _bone_1_ 

**Steps to reproduce and Minimal reproduction project:**
[test.zip](https://github.com/godotengine/godot/files/6386503/test.zip)
- Open project in Godot 3.3-rc9 (but also previous rc) and let Godot import **model.gltf** file
- Run the project to print all bone's names. It should print:
```
Bone
Bone.001
Bone.002
Bone.003
Bone.004
Bone.005
Bone.006
Bone.007
Bone.008
Bone.009
Bone.010
Bone.011

```

- Close Godot 3.3-rc9 and open (or open a new copy of the same minimal project) Godot 3.3-stable
- Load the project and re-import  **model.gltf** (or better, delete .import folder for automatic reimport)
- - Run the project to print all bone's names. It should print:
```
bone
bone_1
bone_2
bone_3
bone_4
bone_5
bone_6
bone_7
bone_8
bone_9
bone_10
bone_11

```

**Comment by Calinou** [comment]
cc @fire

**Comment by fire** [comment]
See https://github.com/godotengine/godot/pull/48058

**Comment by fire** [comment]
`use_legacy_names` keeps old 3.2 names.

**Comment by lyuma** [comment]
To expand a bit on @fire 's comment, the specific issue in your case is caused because you imported the mesh on a beta or release candidate build.

Unfortunately, there was no easy way to detect that the user was not previously on a stable build, so we have to guess if you want the old naming or the new naming. Out of caution of breaking 3.2.3-stable projects, if you are upgrading from a -beta or -rc build, we assume that you prefer the old bone names.

It is still possible to get the new naming, Open your project on the latest 3.3-stable build, and then either go to the importer panel and *uncheck* "Use Legacy Names" (You can also get this by importing the gltf files from scratch, for example deleting the .import files).

If you have BoneAttachments or other in-scene references, it is good to discard changes and close and reopen any scene files once you have reimported without Use Legacy Names.

**Comment by aakord** [comment]
Got it: unset the _Use Legacy Names_ solved it. Thanks everyone.

**Comment by Flavelius** [comment]
It's unfortunate that these are the small, things that can suddenly break whole projects like in my case. Only finding the right github issues then reveals why.
There should be a field in the project file that specifies which editor version the project was last opened in. This could give breaking-commit authors the chance to handle their changes better and create other opportunities too.

**Comment by Calinou** [comment]
> There should be a field in the project file that specifies which editor version the project was last opened in. This could give breaking-commit authors the chance to handle their changes better and create other opportunities too.

See https://github.com/godotengine/godot-proposals/issues/237.
