### ISSUE TITLE
Any Popup Dialog Window Giving An Error When Using Popup()

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#4838]
**Operating system or device - Godot version:**
Linux, Godot 2.0.3

**Issue description** (what happened, and what was expected):
Using popup() on a script added to a dialog window to show it causes an error in the debugger.
C Error: Condition 'data.block>0' is true
C Source: scene/main/node.cpp:289
C Function: move_child

**Steps to reproduce:**
Call popup() in a script attached to any window dialog

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
this is not a bug, it happens only in the very specific situation when you are: 
1) calling popup() from the popup itself
2) calling it in _ready()

this will fail to raise the popup, because the parent is busy setting up children nodes. This will make it work: 

`call_deferred("popup")`

In any case, will push a change that explains better what is going on in the error.
