### ISSUE TITLE
Vulkan: Some objects don't appear on Android when using the mobile renderer

### ISSUE THREAD

**Issue by szymonm-google** [godotengine/godot#48424]
**Godot version:**
4.0.dev

**OS/device including version:**
Device: Pixel 4a
GPU: Adreno 618
Renderer: Vulkan

**Issue description:**
The reference scene contains three spheres, but only one sphere is visible on the Android build. The PR that introduced the issue is #47059 (Create mobile renderer).

Expected result:
![good](https://user-images.githubusercontent.com/80777504/116921968-91755100-ac09-11eb-87d9-b66e46c8b60c.png)

Actual result:
![bad](https://user-images.githubusercontent.com/80777504/116921990-976b3200-ac09-11eb-8393-aa31f794e046.png)

**Steps to reproduce:**
Run the project on Android.

**Minimal reproduction project:**
[assets.zip](https://github.com/godotengine/godot/files/6417100/assets.zip)

**Comment by BastiaanOlij** [comment]
Super weird... this is reproducible on desktop by switching to the mobile renderer even in the editor:
![image](https://user-images.githubusercontent.com/1945449/116949169-cd212100-acc4-11eb-9119-6ba818802572.png)

I'm guessing its getting confused because they are three meshinstances sharing the same mesh object. I'll investigate

**Comment by BastiaanOlij** [comment]
Because the original clustered renderer loads all instance data in a big instance data list that is pushed into an uniform buffer the code tries to be smart and process all instances in a single draw call. 

With the mobile renderer this only works when a multimesh or particle trail is used as we use a buffer with transform but for normal mesh instances each instance is drawn with a draw call with the transform stored in the push constant. Hence only the first is drawn (and drawn 3 times in the same spot) while the other two are ignored.

Need to remove that bit of logic
