### ISSUE TITLE
Odd Scene Pane Slowdown With Module

### ISSUE THREAD

**Issue by Gramps** [godotengine/godot#48459]
**Godot version:**
Godot 3.3

**OS/device including version:**
Only tested on Windows 10 so far.

**Issue description:**
There is a noticeable lag when duplicating (CTRL+D) or clicking through nodes in the Scene pane of the editor when using a custom module that does not exist with Godot 3.2.3.  However, this lag does not exist in other panes of the editor like FileSystem or Inspector.  I also tested the module with Godot 3.2.3 to be sure and the lag does not exist.

**Steps to reproduce:**
[You can get a copy of the pre-compiled version of the module with Godot 3.3 here](https://github.com/Gramps/GodotSteam/releases/tag/g33-s151-gs39) and test it against the official release of Godot 3.3.  Duplicating just a simple label node multiple times inside the Scene pane will cause a lag.  I duplicated it 20 times in a row to test.  Then clicking through those 20 nodes randomly also has a lag between the click and it switching to the node you clicked.

**Minimal reproduction project:**
A fresh scene with only one label node in it will do the trick.  Then quickly hitting CTRL+D to duplicate it 20 times.

**Comment by Xrayez** [comment]
Does the custom build requires Steam SDK installed?

![image](https://user-images.githubusercontent.com/17108460/117040728-d9cc6600-ad12-11eb-92a7-9cc38bc52c7e.png)

But without actually testing this, when comparing official builds and your builds, they significantly differ in size:

![image](https://user-images.githubusercontent.com/17108460/117041027-2fa10e00-ad13-11eb-8511-14b00a281327.png)

This is either because of Steam, or because the binaries are not optimized just like in official builds. Official builds currently use `use_lto=yes` which also reduces the binary size and optimizes performance.

I also [distribute custom Godot builds](https://github.com/goostengine/goost/releases/tag/1.0-beta-gd3) and they seem to be mostly identical to official ones. You can try building your custom module with [Godot's build scripts](https://github.com/godotengine/godot-build-scripts) if you also want to achieve this, and that could likely resolve the performance issue.

That said, what `scons` commands do you use to compile the engine with your module?

**Comment by Gramps** [comment]
The custom build only requires the DLL; which we can't distribute unless with a game.

You use `use_lto=yes` on editor compiling?  I assumed it was only used for templates.

I will definitely check out the build scripts you linked.  Though the reason I brought the issue up is because it only seems to exist in Godot 3.3 even if I compile the editor the exact same way with the exact same module code compared to Godot 3.2.3; which led me to assume the issues had more to do with 3.3 itself.

For compiling the editor, I just use `scons platform=windows -j8`.  I use the `use_lto=yes` for templates.

Yeah, MinGW does not work with Steamworks due to various internal bits.  Valve would have to re-write parts of the API; we tried patching them out which only caused more problems.  I mostly use Native Tool Prompt for Visual Studio to compile on Windows.  On Linux I use terminal and GCC.

**Comment by Xrayez** [comment]
> You use `use_lto=yes` on editor compiling? I assumed it was only used for templates.

If you look at godotengine/godot-build-scripts#22, this uses a new `production=yes` option, and this applies to both editor and export templates now, so you'd also likely want to use this option for your own builds.

**Comment by Gramps** [comment]
Yeah, I started digging through the script and noticed the `production=yes` which shows it as using LTO once it starts to compile.   Currently compiling a test build using this setup and going to see what it does.

**Comment by Gramps** [comment]
Well, using that SCONS line seems to have cleared up the lag and reduced the editor size.  Still rather odd it didn't have lag with Godot 3.2.3 but I guess that doesn't matter much now.  Thanks for the information!
