### ISSUE TITLE
Find in Files trimming input text

### ISSUE THREAD

**Issue by chucklepie** [godotengine/godot#48464]
**Godot version:**
3.3 stable

**OS/device including version:**
linux

**Issue description:**
Find in files does not honour white space at start or end, causing invalid results, which in many instances results in hundreds of erroneous results making searching impossible, even when 'whole words' is used (hoping it might honour whitespace). As screenshot only words with a space at start and end was required, but the input is trimmed causing all these results...

![image](https://user-images.githubusercontent.com/12863685/117077005-45bcc780-ad2f-11eb-8b6c-de58629502ba.png)

**Steps to reproduce:**
1. search for something with a space
2. the search trims the input

**Comment by Calinou** [comment]
This is due to various `.strip_edges()` calls in [`editor/find_in_files.cpp`](https://github.com/godotengine/godot/blob/master/editor/find_in_files.cpp). Most of those should be removed.

**Comment by chucklepie** [comment]
Thanks, that sounds embarrassingly like something I could have searched for in github web code view (not having the code downloaded)...

I did search the proposals to see if anyone had put in a suggestion to incorporate regex searches as that would be just lovely :)

**Comment by Zylann** [comment]
These were intended to avoid typos though.

**Comment by chucklepie** [comment]
Ok, but surely a search facility shouldn't be trying to presume what you
wanted to find...

**Comment by brennengreen** [comment]
@Calinou Any specific convention I should use to decide which calls to leave in code and which to remove?

**Comment by Calinou** [comment]
> @Calinou Any specific convention I should use to decide which calls to leave in code and which to remove?

I haven't taken a look thoroughly, but make sure to tweak and test the behavior for *both* Find in Files and Replace in Files actions.

**Comment by brennengreen** [comment]
Looks like the call in `FindInFilesDialog::get_folder` should be kept since I cannot think of a scenario where a folder name should or even could have a leading/trailing whitespace.

I'd assume the call in `get_search_text` is what is causing this issue specifically. Also to me it seems like we should remove the call `_on_result_found()` as that would lead to technically inaccurate results? If the user searches ` hello ` then the result should include ` hello ` not `hello` as thats not entirely accurate.

I'll check out replace in files as well and of course run some tests.. That just leaves the question brought up by @Zylann, is removing these what we want to do or would that inhibit other search functionality like whole words from performing its job?

**Comment by Calinou** [comment]
> I'll check out replace in files as well and of course run some tests.. That just leaves the question brought up by @Zylann, is removing these what we want to do or would that inhibit other search functionality like whole words from performing its job?

Maybe we should strip edges *only* when not performing a whole-word search.

**Comment by brennengreen** [comment]
> Maybe we should strip edges _only_ when not performing a whole-word search.

Would it be appropriate to do this via `FindInFiles::is_whole_words()` in `FindInFilesPanel::start_search()` or would you go about it a more appropriate way?

**Comment by Calinou** [comment]
> Would it be appropriate to do this via `FindInFiles::is_whole_words()` in `FindInFilesPanel::start_search()` or would you go about it a more appropriate way?

I don't really have an opinion on it – pick what works :slightly_smiling_face:
