### ISSUE TITLE
Proposal for the 3D viewport tools

### ISSUE THREAD

**Issue by guzzard** [godotengine/godot#4850]
I would like to propose to make the viewport tools more accessible, similar to UE4.
![deepinscreenshot20160528010806](https://cloud.githubusercontent.com/assets/9007314/15623163/3e7fc2e8-2471-11e6-8616-67d8298c619e.png)

Is this or something similar already in the development plans? If not, then I could try to implement in it the c++ code myself and do a pull request. My first thought was to create a EditorPlugin script, but I was not able to find any way of modifying the snap settings in the editor that way. Is it possible to access somehow from script, or is c++ the only way?

**Comment by guzzard** [comment]
I was thinking something something like this. In the top right corner of the viewport.
![2016-05-29_10-03-06](https://cloud.githubusercontent.com/assets/9007314/15632018/e85e60c6-2584-11e6-8861-29bf3bf91d2f.gif)

I have started to implement visual parts (menus, icons) into **spatial_editor_plugin.h/cpp**, however I will start over and see if it's possible to implement it for both 2D and 3D viewports in an easy way. Help, tips, suggestions are welcome!

**Comment by guzzard** [comment]
Small update..
![2016-05-30_13-14-57](https://cloud.githubusercontent.com/assets/9007314/15648131/ca6957b2-2668-11e6-8212-fe56fe9c93b5.gif)

I'm having issues using the degree character in code. No matter what method I use to add the character, it's missing when the engine launches. Anyone know how to use special characters?

**Comment by bojidar-bg** [comment]
@guzzard It is probably since the font doesn't have it... I think we changed the font recently in master, maybe you can recheck?

**Comment by jjay** [comment]
Wow! Pretty nice! I want it already.

Hotkeys for toggling that states are also useful btw (especially without modifiers ctrl, alt, etc.). And 2D viewport misses that functionality as well =)

**Comment by guzzard** [comment]
@bojidar-bg I needed to parse the string using the String.parse_utf8(String str) function. Juan (reduz) gave some quick support by email :-)

**Comment by guzzard** [comment]
@jjay Thanks! Yes, hotkeys would be nice.. will check if I can add it. Right now I will only focus on the 3D-viewport.

**Comment by reduz** [comment]
This is fine but just put it in the top toolbar using regular controls.., i
think there is no benefit of it being over the screen or is it? If you use
regular controls it will work with hidpi

**Comment by guzzard** [comment]
@reduz the reason I put it in the viewport was because some nodes have custom controls that are added to the toolbar when you select the nodes. Adding the viewport controls will add around 200-300px width to the menu, so those controls which are added by other nodes will be much further to the right than usual. It might also be an issue on a small screen (but I don't think people use Godot on 800x600..). What do you think?

Meanwile, I will look have a look and see if I can add it to the toolbar instead in some nice way.. will need to make some changes to the design to make it more suitable for the toolbar i think.

**Comment by reduz** [comment]
Oh I think the nodes that appear on the right margin are gone, moved their
stuff to the property editor or just removed it all together.

All that remains is nodes that might add a menu or two to the left, but the
right space should be unused. Alternatively, you could put the controls to
the right of the mode buttons (select/move/etc)

**Comment by guzzard** [comment]
Closed the pull request.. screwed up using GitKraken.. will open a new pull request after I have done the changes discussed.

@reduz, question regarding moving the controls. Would this be an acceptable solution? So that the user can choose which side the controls are shown in the toolbar?
![deepinscreenshot20160601133021](https://cloud.githubusercontent.com/assets/9007314/15708120/0674cfb2-27fd-11e6-87d9-198f85fbfbaa.png)

**Comment by trollworkout** [comment]
wow this is great! I don't mind it being on the toolbar or on the window. On the window looks more slee tbh.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
