### ISSUE TITLE
Cant override enum from extended class

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#48522]
**Godot version:**

3.3

**OS/device including version:**

windows 10 x64

**Issue description:**

You cant override existing enum from parent class

e.g
```gdscript
extends Node2D
class_name Character

enum STATES {idle,move}
```

```gdscript
extends Character
class_name NPC

enum STATES {idle,move,attack}
```

**Steps to reproduce:**
* Create two classes
* parent has a enum
* extends from one of classes
* try to override enum

**Minimal reproduction project:**

N/A

**Comment by Calinou** [comment]
Out of curiosity, does something like that work in other programming languages? If so, which ones?

**Comment by nonunknown** [comment]
C#... I think

since in godot a enum, is like a dictionary, at least append more (which is currently possible) but then you cant use enumname.newkey

**Comment by EricEzaM** [comment]
I dont think this is possible in C#, at least no easily and intuitively.

**Comment by FeatherAntennae** [comment]
Enums can't really work like this for multiple reasons. They aren't the right tool for this use case. Sadly, this is a situation that requires rethinking the code rather than the language.

Allowing to override enums would opens the door to a lot of problems; some pretty hard to debug. It would go against what most people working with enums expect and take for granted, which increase the risk of introducing errors too.

The biggest problem imo is that it would break polymorphism when a parent class is used to refer to a child class, like in a switch case, as children classes could remove, rename, reorder or change the values of elements from the enum used in the parent class.

There are plenty of ways to approach this without enums depending on what you use them for.

Without more context, in C#, to have similar possibilities as to what enums offer, I would make a "State" struct with a name and a value properties without public setter. Then you can have a private collection of "State" with some default values in a parent class, a public getter returning a list of them, and a protected method to add new states into the collection from a child class.

As for GDScript, it really depends what you want to do with the enum.

Feel free to poke for help on the official Godot Discord if you want, I'm sure we can find a cleaner solution.

**Comment by EricEzaM** [comment]
I mean technically the internal code of Godot already does this:
https://github.com/godotengine/godot/blob/0ec809462e1c0b008d4a617552acd1b56f6c0f6c/scene/main/node.h#L215-L222
https://github.com/godotengine/godot/blob/0ec809462e1c0b008d4a617552acd1b56f6c0f6c/scene/gui/control.h#L298-L304

The numbering is just manually controlled to ensure no overlaps. Nothing stopping you from doing this in GDScript I suppose - you would just need to control it yourself.

**Comment by willnationsdev** [comment]
I *thought* (need to confirm) C# does support the example that @nonunknown provided though. It isn't an "override" though. The enums that are declared are type declarations that are specific to the class in which they are defined. So when you re-define a same-named enum in a derived class, subsequent references to that typename are referring to the current class scope definition of that name. To then access the base class's enum, you would directly refer to it with something like `Character.STATES`.

C++ doesn't really do that since the enums are global more or less (although, I think scoping was added for `enum class` data types in C++11? I'd have to check - either way, Godot C++ source code doesn't use those).

Sounds to me like it's at least worth considering the usability it would grant users to allow them to have enum declarations exist within the same lookup table, from a user perspective, as the inner class declarations. While they are technically just a Dictionary, we could masquerade them otherwise and allow users to redefine those symbols.

**Comment by vnen** [comment]
This is intended. Enums are the same as constants, and constants cannot be overridden. If you need this you should open a proposal to explain the use cases.
