### ISSUE TITLE
AnimationTree does not apply Call Method Track for a method in an AudioStreamPlayer script.

### ISSUE THREAD

**Issue by apples** [godotengine/godot#48526]
**Godot version:**
3.3

**OS/device including version:**
Windows 10 Home, version 20H2, build 19042.928, HP Pavilion Gaming Laptop 16-a0xxx.
nVidia GeForce GTX 1660 Ti Max-Q, driver version 457.63, any backend.

**Issue description:**
Apologies, this is a weird one.

What happens: AnimationTree state machine does not apply method calls to an AudioStreamPlayer script in a Call Method Track in an Animation when another Animation exists on the same AnimationPlayer and which is alphabetically after the current animation and has an Audio Playback Track.

(yes, all of those details are important, see steps to reproduce below)

What I expected: The Call Method Track should get called regardless of other animations' Audio Playback Tracks and alphabetical status.

**Steps to reproduce:**
Gosh, where to begin...

Setup:
1. Create a new Node2D scene with a child Sprite node to animate (optional but useful for debugging).
2. Add AudioStreamPlayer node to the scene with some audio stream imported.
3. Attach a script to the AudioStreamPlayer with a simple method that prints a debug message or something.
    ```gdscript
    extends AudioStreamPlayer
    
    func play_bloop():
	    print("hi")
	    play()
    ```
4. Add an AnimationPlayer node to the scene.
5. Create a simple animation named `default` which translates the Sprite (optional) and which has a Call Method track pointing to the AudioStreamPlayer. Optionally, make this looping.
6. Add a keyframe to the Call Method track which calls the AudioStreamPlayer's method which was added in step 3.
    ![image](https://user-images.githubusercontent.com/2352020/117427720-f1f6dd80-aeea-11eb-988a-4e6569c89a3f.png)
7. Create a second animation named `zzz` which has an Audio Playback track with a keyframe that plays a stream to the AudioStreamPlayer (edit: actually, the keyframe is optional, only the track itself needs to exist).
    ![image](https://user-images.githubusercontent.com/2352020/117427921-27033000-aeeb-11eb-8d8a-5e8649430555.png)
8. Add an AnimationTree node to the scene.
9. Point the AnimationTree to the AnimationPlayer, mark it as Active, and create a new state machine tree root.
10. In the tree root, add a single node to play the `default` animation.
11. Attach a script to the scene root node which starts the AnimationTree's state machine at the `default` node on ready:
    ```gdscript
    extends Node2D
    
    func _ready():
	    #$AnimationPlayer.play("default")
	    $AnimationTree["parameters/playback"].start("default")
    ```

Actual bug reproduction:
1. Play the scene. Observe that the `default` animation is playing, but the method in the Call Method track is not being called.
2. Do any one of the following:
    - Change the root node script to play the animation via the AnimationPlayer directly, without using the AnimationTree.
    - Remove the Audio Playback track from the `zzz` animation.
    - Rename the `zzz` animation to `aaa`.
3. Play the scene. Observe that the method is now being called as expected.

Additional notes:
- If there are multiple other animations which are similar to `zzz`, they must all be "fixed" in order to get the method calls to function.
- This does not affect a Call Method track which targets a node other than the AudioStreamPlayer.
- *[screaming]*

**Minimal reproduction project:**
[AudioAnimationTreeTest.zip](https://github.com/godotengine/godot/files/6440509/AudioAnimationTreeTest.zip)

**Comment by TokageItLab** [comment]
Here is suggestion for `AnimationTree` improvement.

First of all, there are two solutions to the problem of duplicate paths being removed.

- Generate a `TrackCache` for each animation
- Append the `TrackType` to the path

The first one is not good from a performance point of view, because it expands the number of elements. So we should pick the latter.

Next, consider the original reason for being: to remove duplicate paths. Perhaps we want to prevent cases like the one in the image below.

![スクリーンショット 2021-05-13 4 32 11](https://user-images.githubusercontent.com/61938263/118036816-0255ff00-b3a8-11eb-96dd-914d2ea3be4f.png)

In this case, it is not possible to determine which track should be preferred, so we need to validate. However, this should not be an implicit validation, but rather a UI warning when a track is added.

The most important thing to keep in mind is that we don't know if blending between things with different `TrackType`s will work. A blend between a `BezierTrack` and a `ValueTrack` may work fine with some fixes, but there is no way to ensure that a blend between a `ValueTrack` and a `MethodTrack` will work.

As far as `AudioTracks` are concerned, forcing the blend to override the `AudioStream`'s volume is also problematic - it may be useful for crossfading background music, but it's inconvenient when playing sound effects in `OneShot`. We think it should be selectable.

With all this in mind, I suggest that the blending issue should be resolved.
