### ISSUE TITLE
Label or OptionButton display text when translate not expected

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#48662]
**Godot version:** 3.3; 4.0

**OS/device including version:** Windows10 64Bit

**Issue description:**

If translate "Baby" to "宝贝"，
Label.text = "Baby" will display to "宝贝"
Expected:
Label.text = "Baby" # display Baby
Label.text = tr("Baby") #display 宝贝
For example: I save my player name in ConfigFile, load it and display with label, now i can't set my player name to "Baby", Because it always display to "宝贝“

**Steps to reproduce:**

**Minimal reproduction project:**

**Comment by dalexeev** [comment]
This is expected behavior. You can use identifiers:

MSG_ID|en|zh
-|-|-
$BABY|Baby|宝贝

```gdscript
label.text = "Baby"  # Will display "Baby".
label.text = "$BABY" # Will display "Baby" or "宝贝" (depending on locale).
```

**Comment by CsloudX** [comment]
> This is expected behavior. You can use identifiers:
> 
> MSG_ID	en	zh
> $BABY	Baby	宝贝
> ```gdscript
> label.text = "Baby"  # Will display "Baby".
> label.text = "$BABY" # Will display "Baby" or "宝贝" (depending on locale).
> ```
> 
> (As far as I remember, there was a suggestion to duplicate properties like this (`text` and `tr_text`), but I couldn't find it.)

Dear, Now I can't set my player's name to "$BABY".
In my cast, I want set player's name to any string, why limit?
var player_name = load_name_from_configfile()
$Label.text = player_name #player_name maybe "$BABY"

**Comment by CsloudX** [comment]
I think it should decide by myself.
var player_name = load_name_from_file()
$Label.text = tr(player_name) # I want translate
$Label.text = player_name # don't translate

**Comment by dalexeev** [comment]
It's assumed that you choose IDs that you do not want to display as is. If you want to display arbitrary text (which can match IDs), you can:

1\. Use an invisible character (any other than U+0000, because this is a line terminator).
```gdscript
label.text = "Baby"    # Will display "Baby".
label.text = "$BABY"   # Will display "Baby" or "宝贝" (depending on locale).
label.text = "$BABY\a" # Will display "$BABY"
```

In your case:

```gdscript
var player_name = load_name_from_file()
$Label.text = player_name + "\a"
```

(This will always work as there is no point in using invisible characters in IDs.)

2\. Don't use `Label` for such cases, but use `RichTextLabel`, which works as you expect (because it doesn't use auto-translation).
```gdscript
rtl.text = "Baby"      # Will display "Baby".
rtl.text = "$BABY"     # Will display "$BABY".
rtl.text = tr("$BABY") # Will display "Baby" or "宝贝" (depending on locale).
```

Even if we decide to change this behavior, it will not happen until 4.0, because it affects backward compatibility.

**Comment by CsloudX** [comment]
In my case, I used the OptionButton, I can choose one to deal something, add the '\a' cause code so ugly and
```
label.text = "Baby"
lable.text = tr("Baby")
```
always translate so confused to me, right?
why I can't decide is translate?
whatever, so thanks?

**Comment by dalexeev** [comment]
> why I can't decide is translate?

Because this feature is used for auto-translation (translation without a code). You just specify the ID (in the properties of the controls that support it), and Godot itself replaces it with the translation of the current locale. When changing the locale, the controls automatically update the displayed text. At the same time, the property itself does not change all this time. This is quite convenient, although it sometimes creates such collisions.

I remembered one feature. You can turn off `tr()` for some object. For example, you can attach a script to the `Label` and add the following function to it: 

```gdscript
func _init():
    set_message_translation(false)
```

In `_ready`, it is additionally required to send `NOTIFICATION_TRANSLATION_CHANGED`.  For `OptionButton`, you can do this: 

```gdscript
func _ready():
    $OptionButton.set_message_translation(false)
    $OptionButton.notification(NOTIFICATION_TRANSLATION_CHANGED)
    $OptionButton.get_popup().set_message_translation(false)
    $OptionButton.get_popup().notification(NOTIFICATION_TRANSLATION_CHANGED)
```



> add the '\a' cause code so ugly

This is called perfectionism. If something works and does not create problems, then this is a good solution. Best the enemy of the good. Though perhaps this is actually better:

> (As far as I remember, there was a suggestion to duplicate properties like this (`text` and `tr_text`), but I couldn't find it.)

**Comment by CsloudX** [comment]
> > why I can't decide is translate?
> 
> Because this feature is used for auto-translation (translation without a code). You just specify the ID (in the properties of the controls that support it), and Godot itself replaces it with the translation of the current locale. When changing the locale, the controls automatically update the displayed text. At the same time, the property itself does not change all this time. This is quite convenient, although it sometimes creates such collisions.
> 
> I remembered one feature. You can turn off `tr` for some object (and the engine code of this object will also not be able to automatically translate messages). For example, you can attach a script to the `Label` and add the following function to it:
> 
> ```gdscript
> func _init():
>     set_message_translation(false)
> ```
> 
> If you want to do it in `_ready`, it is additionally required to send `NOTIFICATION_TRANSLATION_CHANGED`.
> 
> For `OptionButton`, you can do this:
> 
> ```gdscript
> func _ready():
>     $OptionButton.set_message_translation(false)
>     $OptionButton.notification(NOTIFICATION_TRANSLATION_CHANGED)
>     $OptionButton.get_popup().set_message_translation(false)
>     $OptionButton.get_popup().notification(NOTIFICATION_TRANSLATION_CHANGED)
> ```
> 
> > add the '\a' cause code so ugly
> 
> This is called perfectionism. If something works and does not create problems, then this is a good solution. Best the enemy of the good. Though perhaps this is actually better:
> 
> > (As far as I remember, there was a suggestion to duplicate properties like this (`text` and `tr_text`), but I couldn't find it.)

Thanks, set_message_translation() completely meet my needs.
My fault, not see set_message_translation()
Thanks very much!
