### ISSUE TITLE
HTML5: npot repeated texture nearest-neighbour interpolation is off

### ISSUE THREAD

**Issue by snoopdouglas** [godotengine/godot#48807]
**Godot version:**
3.3.1-rc2, though also observed in 3.3

**OS/device including version:**
Ubuntu Linux 20.04, HTML5, checked in Chromium 90.0.4430.93, Firefox 88.0.1
GTX 1660 super
GLES 2

**Issue description:**
Specific to HTML5. This doesn't happen in desktop/mobile builds. Possibly related to https://github.com/godotengine/godot/issues/44379 

Top texture has repetition enabled, bottom doesn't. They're both the same size (320x56):

![2021-05-18T10:43:11+01:00](https://user-images.githubusercontent.com/4892574/118630086-1f366c00-b7c6-11eb-8d59-5dfd9dd30d64.png)

**Steps to reproduce:**
Seems as simple as importing a repeating npot texture and exporting to HTML5.

**Minimal reproduction project:**
[bug.zip](https://github.com/godotengine/godot/files/6500243/bug.zip)

**Comment by snoopdouglas** [comment]
I've confirmed that this doesn't happen with GLES 3.

**Comment by lawnjelly** [comment]
This is expected behaviour, although it may not be expected by users (we should probably have a warning to this effect). For hardware that doesn't support non-POT tiling on GLES2 (which includes HTML5, I think we always assume npot tiling not supported), if the texture is imported as repeat it gets resized to POT, as discussed in #44379.

With no filtering, that results in ugly aliasing / sampling error. If you turn filtering on at import you get a smoother result. If you reimport with wrapping off, you see it looks fine as no resize has taken place.

There is also a shader that will attempt to wrapping in the fragment shader as last ditch if the texture has been imported as non-wrapping, but a wrap flag is used at runtime. But this may have bad effects on some hardware (slowness, artifacts).

So really the general advice is, don't use npot textures for tiling on GLES2 or HTML5.

**Comment by snoopdouglas** [comment]
Good to know. I generally don't build for HTML5, but was trying it out and noticed this artifacting, so thought it'd be worth reporting.

> If you turn filtering on at import you get a smoother result.

I'm sure, though can be problematic for pixel art :p

> So really the general advice is, don't use npot textures for tiling on GLES2 or HTML5.

FWIW the game I'm working on runs GLES2 on desktop and mobile, and doesn't have these problems - though maybe I just happen to have not tested on any problematic hardware yet.

**Comment by lawnjelly** [comment]
> FWIW the game I'm working on runs GLES2 on desktop and mobile, and doesn't have these problems - though maybe I just happen to have not tested on any problematic hardware yet.

Yes, it will potentially have problems if you run on hardware which doesn't support npot tiling, it checks for this capability at startup.

**Comment by snoopdouglas** [comment]
Do you reckon it's worth adding a gotcha to [this page in the docs](https://github.com/godotengine/godot-docs/blob/3.3/getting_started/workflow/export/exporting_for_web.rst), or should this just be closed?

**Comment by lawnjelly** [comment]
Yes certainly there should be something in the docs about it, and probably a warning too at runtime imo.

**Comment by Calinou** [comment]
> So really the general advice is, don't use npot textures for tiling on GLES2 or HTML5.

Can we print a warning every time such a texture is used?

**Comment by akien-mga** [comment]
Fixed by #48817.
