### ISSUE TITLE
F5 shortcut gets eaten when numeral fields are selected in the inspector

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#48825]
**Godot version:**
3.3.1.stable

**OS/device including version:**
Windows 10 Pro Version 20H2 (OS Build 19042.985)

**Issue description:**
I wanted to test my game after making some changes in the inspector. I pressed F5 and nothing happened. I expected F5 to launch the game.

After some experimentation I found this bug occurs only when I have a numeral field selected in the inspector.

**Steps to reproduce:**
Place a Node2D (for example) in the scene. Click on the Transform Position.x field in the inspector and type in a value. DO NOT PRESS ENTER OR CLICK AWAY. Either leave the field selected or press tab to select the next field (Position.y). Press F5. Nothing will happen.

Click out of the field or press Enter to deselect it and press F5. The game will launch.

This only seems to happen when editing numeric fields. F5 functions as expected when selecting checkboxes or editing text/string fields.

**Minimal reproduction project:**
[BugReport.zip](https://github.com/godotengine/godot/files/6506129/BugReport.zip)

**Comment by samsaga2** [comment]
I have done some tests. It is a Windows only bug. The play button (the button that have the key shortcut) has a windows_id 0 (the main window). The F5 key event, when the focus is on the line_edit control, is sent to a different window_id (a hidden popup maybe?).

It is also happening in the master branch, not only in Godot 3.

**Comment by akien-mga** [comment]
It's reproducible on Linux in `3.x`, `EditorSpinSlider` takes focus and most likely the editor doesn't receive the F5 event. The same happens when a dialog is opened (e.g. signal connection dialog) or an OptionButton popup.

That doesn't strike me as a really problematic issue though, all those actions are actions which take focus, and focus impacts which shortcuts are available.

**Comment by Deozaan** [comment]
> That doesn't strike me as a really problematic issue though, all those actions are actions which take focus, and focus impacts which shortcuts are available.

Are you saying that editing any numeric field (some of which are highlighted with rectangles in the image below) should be taking the focus?

![Godot Numeric Shortcut Eater](https://user-images.githubusercontent.com/227734/119203412-37212080-ba50-11eb-8ccb-b63ef6d245e6.png)

Sure, maybe using the slider or the spinner (annotated with arrows) should steal focus. But I don't think just typing in a number in the box should be stealing focus and breaking shortcuts. Otherwise, why doesn't editing a string such as in a label also steal focus and break the shortcut?

**Comment by EricEzaM** [comment]
> Otherwise, why doesn't editing a string such as in a label also steal focus and break the shortcut?

Because the numeric field editors on SpinSliders and such are Popups. They are Popups (Windows) which contain a LineEdit and are perfectly sized and aligned such that it looks like they are part of the inspector. However, they are just borderless "embedded"-like windows, so they are the window into which all inputs are sent.

We could potentially add some functionality which allows viewports to pass their unhandled input to their parent viewports, however that may be adding complexity for very niche situations.

**Comment by Deozaan** [comment]
#67397 appears to be only for master branch. That means this issue still exists in 3.x, right?

**Comment by Calinou** [comment]
https://github.com/godotengine/godot/pull/67397 may be redoable for `3.x`, but it causes several regressions which means it shouldn't be done until those regressions are fixed in `master`.
