### ISSUE TITLE
Show colors in script editor - pigments

### ISSUE THREAD

**Issue by GlaDOSik** [godotengine/godot#4882]
Atom editor has a neat plugin called [pigments](https://github.com/abe33/atom-pigments). It highlights the color declaration with the declared color. This is especially usefull in web development so I'm not sure, how usefull this feature would be for game developers. Thus further discussion is welcome.

This is a separate issue from the big list #2982

![pigments](https://cloud.githubusercontent.com/assets/3484686/15635045/57e8cc48-25d4-11e6-9faf-10453d29933d.jpg)

**Comment by vnen** [comment]
I believe it's possible to use the editor with a color picker for this currently, with `export var`.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
