### ISSUE TITLE
Crash when removing a CollisionObject node in `_ready()` with debug collision shapes enabled

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#48866]
**Godot version:**
Godot_v3.3.1-stable_win64

**OS/device including version:**
Win7 x64

**Issue description:**
I migrated my current project from stable 3.3 to stable 3.3.1, after trying to run I got a critical error (ERROR: get_world: Condition "! Is_inside_world ()" is true. Returned: Ref <World> ()
   At: scene / 3d / spatial.cpp: 509) in the console and the project crashes.
If I turn off rendering of debug collision fonts. crashes stop happening, but crashes also stop if I change some configurations of the scene by removing some collision shapes before starting the project, but at the same time if I remove some node from the scene tree in the script, the crash will also occur, I have been trying to balance the test scene for the second day in order to determine in which specific place the failure occurs, but judging by all accounts this is due precisely to the combination of several collision objects in one scene, and their subsequent change in the script, so the minimal project turned out to be rather complicated.

**Steps to reproduce:**
Run the example project with debug shapes enabled.

**Minimal reproduction project:**
[strange_complex_regression_BUG.zip](https://github.com/godotengine/godot/files/6511823/strange_complex_regression_BUG.zip)

**Comment by OlexiyKravchuk** [comment]
https://github.com/godotengine/godot/pull/48175

**Comment by OlexiyKravchuk** [comment]
https://github.com/godotengine/godot/issues/48281

**Comment by OlexiyKravchuk** [comment]
https://github.com/godotengine/godot/issues/48085

**Comment by akien-mga** [comment]
CC @trollodel @pouleyKetchoupp

**Comment by trollodel** [comment]
@OlexiyKravchuk I tested the MRP and I can reproduce the issue. It is caused (indirectly) by this line: `i.get_parent().remove_child(i)`.
I already did a fix, so I'll submit a PR soon. Meanwhile, you can workaround the bug by deferring the remove_child like this: `i.get_parent().call_deferred("remove_child", i)`.

**Comment by OlexiyKravchuk** [comment]
@trollodel 

>Meanwhile, you can workaround the bug by deferring the remove_child call like this: i.get_parent().call_deferred("remove_child", i).

If you look closely, you will find that the construction using i.get_parent (). Call_deferred ("remove_child", i) will be meaningless because when i.queue_free () finishes its work, it will remove the node from the tree without prompting.
But the problem is complicated by some behind-the-scenes not very obvious circumstances, they are that in my project the node had to be cleaned immediately and immediately after the cleaning there was another operation for which this preparation was needed.
By the way, call_deferred () looks like a much more terrible hack for me than even go_to (), so I use it in the most hopeless case, trying to avoid this to the last possible.

**Comment by trollodel** [comment]
> If you look closely, you will find that the construction using i.get_parent (). Call_deferred ("remove_child", i) will be meaningless because when i.queue_free () finishes its work, it will remove the node from the tree without prompting.
But the problem is complicated by some behind-the-scenes not very obvious circumstances, they are that in my project the node had to be cleaned immediately and immediately after the cleaning there was another operation for which this preparation was needed.

Yes, it's not just a problem in `_ready`, I suggest that title because your MRP has it, and it's one of the possible way to trigger the bug. The bug in the MRP (and probably in other parts of your project) happens when you remove the node after at least one shape was just added to the CollisionObject. CollisionShapes do that in them `_ready` for example. 

When you (or a CollisionShape) add a new shape to a CollisionObject and "Debug Collision shapes" is enabled, it stores the shape (to be specific, the shape owner) and it schedules a debug shapes update through `call_deferred`. Before that `call_deferred` there are some checks, including an `is_inside_tree()`. When updating the debug shapes, it needs to be inside the scene tree.
But, if CollisionObject scheduled a debug shapes update, and you remove it from the node *right after*, when it's time to update, it tries to get the context information from the tree (`get_world()`), it fails, and it crashes.
The fix for it is to check if `is_inside_tree()` is true when updating and the issue goes away.

> By the way, call_deferred () looks like a much more terrible hack for me than even go_to (), so I use it in the most hopeless case, trying to avoid this to the last possible.

I know, I just want to suggest a workaround until 3.3.2 will be out and hopefully this and other bugs will be fixes.

**Comment by OlexiyKravchuk** [comment]
> The fix for it is to properly check is_inside_tree() when updating and the issue goes away.

That is, it will be notified by a signal that the node has left the scene tree? (For reference, I'm not at all sure whether the option to use signals in the C ++ code is available, with a back end, it's just interesting to the point that it hangs the load and reliability)
I hang this to understand if I could use a similar trick in the future to manipulate the visual part directly through the render server, bypassing the use of the node system to reduce costs for highly loaded scenes, but at the same time without disrupting the workflow in general, so that there are no conflicts and failures with memory leaks ...

**Comment by trollodel** [comment]
> That is, it will be notified by a signal that the node has left the scene tree? (For reference, I'm not at all sure whether the option to use signals in the C ++ code is available, with a back end, it's just interesting to the point that it hangs the load and reliability)

Everything you can do in GDScript you can do inside the engine code too, (with probably yield as the only exception). For this specific case, I already use the `NOTIFICATION_EXIT_TREE` notification (in GDScript there is `_exit_tree` as helper) to handle the case when the node exits. 
So, if you remove the node, `NOTIFICATION_EXIT_TREE` will be propagated and handled correctly, but if a debug shapes update is scheduled, there is no trivial way to stop it, then I need to handle that case.

> I hang this to understand if I could use a similar trick in the future to manipulate the visual part directly through the render server, bypassing the use of the node system to reduce costs for highly loaded scenes, but at the same time without disrupting the workflow in general, so that there are no conflicts and failures with memory leaks ...

This is a bit off-topic here (it's still the issue tracker). Anyway, my suggestion for this is to not use servers during development and use them in the end to save a bit of memory, especially for static objects.
