### ISSUE TITLE
Error while using varyings in Godot 3.4 beta

### ISSUE THREAD

**Issue by josefkaragoli** [godotengine/godot#48949]
**Godot version:**

v3.4.beta.custom_build.c311b4c03

**OS/device including version:**

Windows 10 GTX 1060 I7-6700k

**Issue description:**

A shader that worked before 3.4 beta (3.3, 3.2.3) that uses varyings displays error " Varying must be assigned before using! "
This issue persists even after assigning a value to the varying.
Shader:

```
shader_type spatial;

varying vec2 uv;
//varying vec2 uv = vec2(1.0, 1.0); // Doesnt work either

void function() {
	1.0 * uv;
}
```

**Steps to reproduce:**

Create a mesh with a shader material, and use a varying within the shader

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/48840.

**Comment by Chaosus** [comment]
@josefkaragoli You cannot assign value to varying inside its declaration or custom function. By default, you should do it only in the vertex function.

**Comment by josefkaragoli** [comment]
So I cant use varyings in a custom function anymore? This worked in prior versions

**Comment by Chaosus** [comment]
I guess this code should work:

```
shader_type spatial;

varying vec3 v;

void test() {
	vec3 t = v;
}

void vertex() {
	v = vec3(0, 1, 0);
}

void fragment() {
	
}
```

but after check its still write a "Varying must be assigned before using". I need to figure out the problem and fix it then..

**Comment by josefkaragoli** [comment]
Thanks, I wasnt aware that these changes were made to varyings in shaders.

**Comment by m4nu3lf** [comment]
I'm still seeing this issue despite #48961, am I the only one?

**Comment by akien-mga** [comment]
> I'm still seeing this issue despite #48961, am I the only one?

That PR was not merged ("Closed") and  this issue is still open :)

**Comment by Chaosus** [comment]
I began thinking @lyuma made a mistake to port this feature to 3.4. That's minor but compatibility breakage. If anyone has this problem - all you have to do is follow the instructions and assign varying inside `vertex` or `fragment` functions. If you assign it in `vertex` you can later use it in `fragment` or `light` functions, or if in a `fragment` - `light`. 

<i>Note for myself: This should be properly documented on Godot Docs.</i>

**Comment by m4nu3lf** [comment]
@akien-mga Sorry for the confusion, now it makes sense.
@Chaosus It seems to me all variables are assigned where I get the error 
here https://github.com/Master-J/DecalCo/blob/bd4381d5e171795b003e79c27526c15fdff1af43/decalco/src/Decal.shader#L64

**Comment by lyuma** [comment]
@Chaosus I have concerns too. I strongly objected to the original design because it overloaded an existing syntax (`varying`) for a different purpose, adding substantial complexity because the parser can't know which type of varying it is... but that's water over the dam now that it's implemented...
I think these usability concerns will also pop up in master, and we should take this opportunity to fix it and improve compatibility at the same time... Reverting this feature from 3.x would be a mistake because it means we are making diverging decisions in master branch for no good reason.

**New issues introduced by varying**
The cases ought to be reduced to two valid cases:
1. VERTEX: The varying is assigned in `vertex` but not `fragment` or `light`. This is the old usage of `varying`. If this happens, the varying must not be modified anywhere outside the `vertex` function. This is the only case where compatibility breakage can happen. It should be safe to permit referencing this variable in any function, because it is guaranteed to be in scope.

2. FRAGMENT: The varying is assigned in `fragment` but not assigned or referenced in `vertex`. This is the new usage of `varying`. Because Godot doesn't know if a given function is called by the vertex stage or fragment stage, it shouldn't allow any function other than `fragment` or `light` to reference it.

And a few other cases exist which now will cause compiler errors, but perhaps worked before:
3. Varying is assigned in `vertex` but never used. This should be allowed and acts as VERTEX. Bonus: optimize it away.
4. Varying is assigned in `fragment` but never used. This should be allowed and acts as FRAGMENT.
5. (as in the OP) Varying is used but never assigned. Treat this as the VERTEX case or treat this as a constant with default value.
6. Varying is declared but never assigned and never used. Treat this as the VERTEX case, or ignore the varying. This should be allowed.

**Proposals**
I'd propose three changes to the current behavior that should be safe:
First, If the varying is a VERTEX type, permit it to be referenced (but not assigned) from any function. This should fix the shader example from https://github.com/godotengine/godot/issues/48949#issuecomment-846389495

Second, if the varying is VERTEX, permit it to be used from `light` as well, because it is equally valid.

Third, permit these "use without assign" or "assign without use" cases.

Finally, currently, a varying shall never be assigned from a function other than `vertex` or `fragment`. I propose that FRAGMENT style varyings should be permitted to be assigned from `light` as well, because that is guaranteed to occur during the fragment stage and therefore safe.

**Comment by Chaosus** [comment]
@lyuma Can you re-check your concerns again? Which point is obsolete and what still needs to be fixed, (my mind is currently busy with other problems, sorry). Maybe all is fixed by the recent fixes to varyings and this issue should be closed.

**Comment by lyuma** [comment]
As noted in rocketchat, your PR solved most of the issues. However I discovered the following shader (based on the OP) still does not work:
```glsl
shader_type spatial;

varying vec2 uv;

void vertex() {
	uv = vec2(1.0,3.0);
}

vec2 function() {
	return 1.0 * uv;
}

void fragment() {
	ALBEDO = vec3(function(), 0.0);
}
```
producing the error, "Varying must only be used in two differnt stages, which can be 'vertex' 'fragment' and 'light'"

Adding a simple `uv;` to the fragment() function works around the error, so my guess is we should extend the rule of 'if a varying is assigned in the vertex function, it can be used anywhere' to include that it is not necessary to use it in fragment or light.


As for the OP's original shader, producing errors is correct: It is meaningless to use a varying without first assigning it... and the commented out line would produce a syntax error, since you cannot assign a varying variable in its own declaration.

**Comment by Chaosus** [comment]
Strange, it seems to work for me: ![image](https://user-images.githubusercontent.com/3036176/129316753-a9a57f3b-2bba-4b24-a15a-47efea8e4280.png) which version of Godot do you use?

**Comment by Chaosus** [comment]
I think this topic is no longer actual. If there are any problems with the varying system - please, open a new issue.
