### ISSUE TITLE
AStar  get_available_point_id () initially returns 1 instead of 0

### ISSUE THREAD

**Issue by OlexiyKravchuk** [godotengine/godot#48950]
**Godot version:**
Godot_v3.3.1-stable_win64

**OS/device including version:**
Win7 x64

**Issue description:**
AStar. get_available_point_id () initially returns 1 instead of 0.
Also, in some cases, for unknown reasons, it returns 1 twice in a row.

The first mistake in this line ...
https://github.com/godotengine/godot/blob/8f7f5846397297fff6e8a08f89bc60ce658699cc/core/math/a_star.cpp#L39

Someone correct this one figure, it has been waiting for more than a year.

**Comment by OlexiyKravchuk** [comment]
https://github.com/godotengine/godot/issues/38263

**Comment by deveshXm** [comment]
I'd like to work on this.

**Comment by akien-mga** [comment]
@deveshXm There's a fix already, see the PR linked above your comment.

**Comment by deveshXm** [comment]
> @deveshXm There's a fix already, see the PR linked above your comment.

I am beginner. So can i make a pull request on this or has this been already merged and closed because it shows me open.

**Comment by akien-mga** [comment]
See this:
![Screenshot_20210522_165823](https://user-images.githubusercontent.com/4701338/119230984-edebd200-bb1e-11eb-8a22-7d83fe019717.png)

If you click the link, you'll see a Pull Request which aims at fixing this issue. It is still Open, so it hasn't been merged yet. But unless there are reasons to think that it wouldn't be merged (e.g. if the fix is wrong), then there's no reason for you to make another PR fixing the issue. We only need one fix (and the best one :)).

You can help by reviewing that PR and confirming that it's how you would have fixed the issue too.

**Comment by deveshXm** [comment]
> See this:
> ![Screenshot_20210522_165823](https://user-images.githubusercontent.com/4701338/119230984-edebd200-bb1e-11eb-8a22-7d83fe019717.png)
> 
> If you click the link, you'll see a Pull Request which aims at fixing this issue. It is still Open, so it hasn't been merged yet. But unless there are reasons to think that it wouldn't be merged (e.g. if the fix is wrong), then there's no reason for you to make another PR fixing the issue. We only need one fix (and the best one :)).
> 
> You can help by reviewing that PR and confirming that it's how you would have fixed the issue too.
> 
> This issue will be closed as fixed once the PR is reviewed and merged.

okay. Thank you for the help.

**Comment by OlexiyKravchuk** [comment]
if this is a ready-made fix why was it not included in version 3.4?

**Comment by Calinou** [comment]
> if this is a ready-made fix why was it not included in version 3.4?

See the description of https://github.com/godotengine/godot/pull/48958:

> Technically it breaks compat so not sure if it should be cherry-picked.
