### ISSUE TITLE
Connected methods to signal don't get called in correct order.

### ISSUE THREAD

**Issue by EdwardAngeles** [godotengine/godot#4898]
**Operating system - Godot version:**
Ubuntu / Linux - Godot v2.1.alpha.custom_build (built from source) [Last commit (7913e79)](https://github.com/godotengine/godot/commit/7913e792acd656469b29fb90be1dbb7c06a855ba)

**Issue description**:
So what happens is I am connecting two methods to a signal (exit_tree) but this methods don't get called in the order they should be called. **Keep on mind that I am connecting them within a function that gets called by a signal**. On the other hand if I wrap those two methods in one single function, it works as expected. So the problem is connecting those methods individually. 

**Steps to reproduce:**
Video showing the issue in a demo: [QuickDemo-Video.zip](https://github.com/godotengine/godot/files/288761/QuickDemo-Video.zip)

**Link to minimal example project**:
Here is a demo: [QuickDemo.zip](https://github.com/godotengine/godot/files/288764/QuickDemo.zip)

**Comment by razvanc-r** [comment]
I'm having a different, but similar problem. I have a custom signal and I want multiple functions in different places (nodes) to be triggered by it. After I connect them to the signal only the first one gets executed. Only tried programatically creating the signals and connections, the set-up I have doesn't allow for manual connection through the GUI.

**Comment by reduz** [comment]
order in which objects are called is not warranted, enforcing an order
would decrease performance in connecting and disconnecting considerably.

**Comment by Geequlim** [comment]
Got similar problem with this.

**Comment by Geequlim** [comment]
@endragor  Is it possiable to solve the problem with the new `OrderedHashMap`

**Comment by reduz** [comment]
Yeah, many places should move to it

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
