### ISSUE TITLE
Tooltips don't appear for PopupMenus

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#49077]
**Godot version:**
v4.0.dev.custom_build.b6f381475

**OS/device including version:**
Windows 10

**Issue description:**
Tooltips don't appear for PopupMenus, but they appear for other node types. This happens inside of the editor and in projects. This happens with single window mode on or off

**Steps to reproduce:**
Hover over any of the items in a PopupMenu that are meant to have a tooltip (like the gizmos), and the tooltip won't pop up. This also happens for PopupMenus placed inside of projects, not just in the editor, so creating a PopupMenu and setting tooltip for it's items won't show the tooltip (like in the minimal reproduction project)

![image](https://user-images.githubusercontent.com/12120644/119554165-5c70a000-bd6a-11eb-8655-98f826527155.png)

**Minimal reproduction project:**
[PopupMenuTooltipTest.zip](https://github.com/godotengine/godot/files/6541862/PopupMenuTooltipTest.zip)

**Comment by Calinou** [comment]
This is a regression from DisplayServer.

**Comment by requizm** [comment]
This error happens because `PopupMenu` is not a `Control`
4.0 master https://github.com/godotengine/godot/commit/441f1a5fe9a3bf0e4e5dab578f793500b1ff6e3d PopupMenu -> Popup -> Window -> Viewport -> Node 
3.3 PopupMenu -> Popup -> Control -> CanvasItem -> Node


More detailed exp:
When we try to show tooltip, this function works:
```
void Viewport::_gui_show_tooltip() {
	if (!gui.tooltip_control) {
		return;
	}

	// Get the Control under cursor and the relevant tooltip text, if any.
	Control *tooltip_owner = nullptr;
	String tooltip_text = _gui_get_tooltip(
			gui.tooltip_control,
			gui.tooltip_control->get_global_transform().xform_inv(gui.last_mouse_pos),
			&tooltip_owner);
       //render stuff
}
```

```
String Viewport::_gui_get_tooltip(Control *p_control, const Vector2 &p_pos, Control **r_tooltip_owner) {
	Vector2 pos = p_pos;
	String tooltip;

	while (p_control) {
		tooltip = p_control->get_tooltip(pos);
        //stuff
       }
}
```


What we click or hover over becomes `gui.tooltip_control` or `p_control`



If we open `PopupMenu`, this functions works first
```
void PopupMenu::take_mouse_focus() {
	ERR_FAIL_COND(!is_inside_tree());

	if (get_parent()) {
		get_parent()->get_viewport()->pass_mouse_focus_to(this, control);
	}
}
```

```
void Viewport::pass_mouse_focus_to(Viewport *p_viewport, Control *p_control) {
	ERR_FAIL_NULL(p_viewport);
	ERR_FAIL_NULL(p_control);

	if (gui.mouse_focus) {
		p_viewport->gui.mouse_focus = p_control;
		p_viewport->gui.mouse_focus_mask = gui.mouse_focus_mask;
		p_viewport->gui.key_focus = p_control;
		p_viewport->gui.forced_mouse_focus = true;

		gui.mouse_focus = nullptr;
		gui.forced_mouse_focus = false;
		gui.mouse_focus_mask = 0;
	}
}
```

From the moment the `PopupMenu` opens, the `PopupMenu::Popup::Window::Viewport::gui.mouse_focus` variable becomes the `control` variable in the `PopupMenu` class. 

In this case, if the tooltip tries to open, the `get_tooltip` function of the `control` variable in the `PopupMenu` returns null because it cannot run the `get_tooltip` function in the `PopupMenu`.
