### ISSUE TITLE
Focus capturing by Popups is not documented

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#49116]
**Godot version:**
3.3.2 - 64 bit

**OS/device including version:**
Windows 10

**Issue description:**
When a popup is open, it completely seems to ignore control layers that are in front of it, even through Canvas Layers and through control nodes that have mouse mode set to "stop" - Even tough the control nodes in the front are clearly rendered in the front.

It seems like it ignores anything that Nodes usually do - even the pause mode is ignored.

https://user-images.githubusercontent.com/9423774/119722777-f91b6680-be6c-11eb-99ea-698795c6f33f.mp4

**Steps to reproduce:**
- Open a popup
- Open something in front of it that should normally stop mouse input.
- Try to click the front layer, clicks go through

**Minimal reproduction project:**
[Popup-Order-Bug.zip](https://github.com/godotengine/godot/files/6549336/Popup-Order-Bug.zip)

**Comment by amoriqbal** [comment]
@RPicster I think this is the intended behaviour of the UI and not a bug. An open `Popup` will retain the focus, even if a new `CanvasItem` is made visible.  There are two ways to achieve your desired behaviour here:
Soln A : Explicitly transfer focus from the `Popup` to the desired `Control`. (Forcefully solves the prob)
Soln B : Open a new `Popup` for getting your focus to a new `CanvasItem` i.e. enclose the contents of the new `CanvasItem` inside a `Popup`. This is possibly the best and the most intuitive. 

![gd ui fx](https://user-images.githubusercontent.com/43443370/119765286-a1164b80-bed0-11eb-9017-16b3e8bd9af3.png)
Here is your minimal reproduction project with the changes of Soln B incorporated.
[Popup fixed.zip](https://github.com/godotengine/godot/files/6551061/Popup.fixed.zip)

Please take a look and revert back.

**Comment by RPicster** [comment]
@amoriqbal thanks for your feedback.

I tried Solution A and it does not work.
.force_focus() is focusing the button, but any interaction loses focus against the popup and it's not possible to get the focus back.

Solution B is ... more a hack than a solution in my opinion. Using a popup to fight a popup does not feel right.

Overall I don't think the behaviour is:

- Beneficial for the user (it would be great to know in what situation the popup "stealing" input from a control layer in front is beneficial)
- Predicted by the user
- Documented in any way I found.

**Comment by amoriqbal** [comment]
You are right @RPicster the behaviour is not documented. In my opinion, the docs need to add a note.

After reading your reply, I understand that you want to control the focus hierarchy with the ordering of `CanvasLayers`. In that case, we use a `Panel` instead of a `Popup`. Here is your minimal reproduction project with the `Popup` changed to a `Panel`. Please take a look and tell me if this is the behaviour you wanted.
[popup_panel.zip](https://github.com/godotengine/godot/files/6553464/popup_panel.zip)

PS: Soln B is the easy way to achieve the focus hierarchy i.e. with popups. We usually don't create `CanvasLayers` to do it. This behaviour (the capturing of focus by a pop-up) is not specific to Godot.

**Comment by RPicster** [comment]
Thanks for the feedback!
As long as it is well documented, I guess it is at least understandable what is happening.

I'm still not sure if the absolutely focus "vacuum" of a `Popup` makes sense, but then, probably I just used it in the wrong way eventually.

Thanks for the feedback.
