### ISSUE TITLE
`TextureRegion` view not updating when the resource changes

### ISSUE THREAD

**Issue by edassis** [godotengine/godot#49233]
**Godot version:**
Godot Engine v3.3.2.stable.official
OpenGL ES 3.0 Renderer: Radeon (TM) RX 480 Graphics
OpenGL ES Batching: ON

**OS/device including version:**
Windows 10 x64 19043

**Issue description:**
The `TextureRegion`'s selector doesn't update when I change the scenes. He stays pointing to the region that I selected previously in the another scene.

**Steps to reproduce:**
1. Create a `Node2D` scene (SceneA);
2. Add a Sprite as child and assign it with the  `tilesets.svg` resource;
3. Enable `Auto Slice` and define a region to the Sprite.
4. Create another `Node2D` scene (SceneB);
5. Add a Sprite node as child and assign it with the  `blueprints.svg` resource;
6. Enable `Auto Slice` and define a region to the Sprite.
7. Change between scenes and look at the `TextureRegion`'s view.

***Demo:***
![TextureRegionIssue](https://user-images.githubusercontent.com/31329807/120250531-ddd99e00-c254-11eb-8946-cbe04db7ebcc.gif)

**Minimal reproduction project:**
[TextureRegionIssue.zip](https://github.com/godotengine/godot/files/6572583/TextureRegionIssue.zip)

**Comment by KoBeWi** [comment]
Might be same issue as #26814

**Comment by kleonc** [comment]
> Might be same issue as #26814

No, these issues are different. Here referenced texture is correct but region's rect isn't updated (and redrawing isn't trigerred) in a specific case. In #26814 (as you mentioned [here](https://github.com/godotengine/godot/issues/26814#issuecomment-703250430)) the problem is the texture reference not being updated properly after new texture is created with "Make Unique".
