### ISSUE TITLE
Out of memory crash on LightmapDenoiser step - BakedLightmap

### ISSUE THREAD

**Issue by Albertolopezs** [godotengine/godot#49311]
**Godot version:**
3.3.2

**OS/device including version:**
Windows 10

Specs:
Ryzen 5 3600
24 GB Ram
RX 590 8 GB

**Issue description:**
When baking lightmaps in large scenarios the memory collapses in the denoiser step. When a smaller region is selected or objects are discarded, the memory is enough.
```
LightmapDenoiser: out of memory  
LightmapDenoiser: out of memory  
ERROR: alloc_static: Condition "!mem" is true. Returned: __null  
   At: core/os/memory.cpp:84  
ERROR: Out of memory  
   At: ./core/local_vector.h:148
```

**Steps to reproduce:**

Create an scenario with a large quantity of vertices and try to bake map

**Comment by Calinou** [comment]
@Albertolopezs Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
