### ISSUE TITLE
`is_on_floor` triggers even if the side or top of a character body is touching something while `is_on_ceiling` and `is_on_wall` don't work when `floor_max_angle` is above 4

### ISSUE THREAD

**Issue by TuxTheAstronaut** [godotengine/godot#49353]
**Godot version:**
v4.0.dev.custom_build.7085c0d80

**OS/device including version:**
Ubuntu 20.04

**Issue description:**
when ever a character body is touching a surface it will say its on the floor even if its on a wall or touching the ceiling. this will only happen if `floor_max_angle` value is above 4 if its below 4 then this bug docent happen

**Steps to reproduce:**
make a `CharacterBody3D` with a collision shape and have set `floor_max_angle` to 4 then move the character body into a wall and ceiling and have it print if its on the floor or not  

Example project
[CharaterBody3D.zip](https://github.com/godotengine/godot/files/6605885/CharaterBody3D.zip)

**Comment by Chaosus** [comment]
Please provide a test project otherwise the devs may be stuck in helping you.

**Comment by TuxTheAstronaut** [comment]
ok i figured out that this only happens when `floor_max_angle` has a value of 4 or above and i provided an example project to show how it works

**Comment by pouleyKetchoupp** [comment]
It looks like the expected behavior. `floor_max_angle` is currently the maximum floor angle in radians.
A value of `3` is `171.887 degrees` so the walls are considered floor.
A value of `4` is `229.183 degrees` so the walls and ceilings are considered floor.

I'm going to change it to work with degrees to make things clearer though, it doesn't make a lot of sense to set an angle in radians in the editor.
