### ISSUE TITLE
Visual Script - Godot 4 - Logic Operators Mislabeled

### ISSUE THREAD

**Issue by Anaxan** [godotengine/godot#49412]
**Godot version:**

v4.0.dev.calinou.cb8244273

**OS/device including version:**

Ubuntu 20.10/Atermiter dual Xeon motherboard, gtx 970 nvidia package 460

**Issue description:**

Pulled in a logic operator and it did not match selection. See attached GIF. 

**Steps to reproduce:**
Pull in logic operators and, or, not,  etc and notice the wrong operator gets dragged in.

**Minimal reproduction project:**

Will create if needed.
![logic_operators_bug](https://user-images.githubusercontent.com/81984273/121111560-180ae880-c7dd-11eb-9b7b-b3aead8bfffd.gif)

**Comment by MisoMosiSpy** [comment]
I did some study on this and I believe it is because of incomplete implementation of  OP_STRING_CONCAT which make the data-structures inconsistent. 

I would like to work on this however, need direction to decide whether we want fix it by implementing OP_STRING_CONCAT or removing it (this I have tried and it works).

Thanks.

**Comment by Chaosus** [comment]
@MisoMosiSpy In such cases you can create multiple PR for each version, and devs choose to merge anyone.

**Comment by MisoMosiSpy** [comment]
> @MisoMosiSpy In such cases you can create multiple PR for each version, and devs choose to merge any.

Thanks for the suggestion, I will put my fixes in PRs.
