### ISSUE TITLE
store_var()/get_var() doesn't preserve object state

### ISSUE THREAD

**Issue by levilindsey** [godotengine/godot#49430]
### Godot version

3.3.2.stable.official

### System information

Windows 10

### Issue description

I am trying to use `File.store_var()` and `File.get_var()` to save and load an object. However, I am not seeing any of my object's state preserved after loading it.

This seems pretty basic, and I don't see any other relevant open issues, so I assume I must be doing something wrong? But I can't imagine what.

### Steps to reproduce

I've inlined the interesting bits from my repro project here:

```GDScript
const PATH := "user://foo.save"

var foo_saved := Foo.new()
var foo_loaded


func _ready() -> void:
    foo_saved.text = "foo"
    
    store_var()
    get_var()


func store_var() -> void:
    var file := File.new()
    var status := file.open(PATH, File.WRITE)
    if status != OK:
        push_error("Unable to open file: " + PATH)
        return
    file.store_var(foo_saved, true)
    file.close()


func get_var() -> void:
    var file := File.new()
    var status := file.open(PATH, File.READ)
    if status != OK:
        push_error("Unable to open file: " + PATH)
        return
    foo_loaded = file.get_var(true)
    file.close()
    
    # Prints "Expected: foo; Actual: "
    print("Expected: %s; Actual: %s" % [foo_saved.text, foo_loaded.text])
    # Prints "Expected: Hey; Actual: Hey"
    print("Expected: %s; Actual: %s" %
            [foo_saved.predefined_text, foo_loaded.predefined_text])
```

### Minimal reproduction project

https://github.com/levilindsey/godot_bug_get_var

**Comment by Calinou** [comment]
I don't think Object binary serialization is supported in the first place.

**Comment by levilindsey** [comment]
Ah, thanks for that info!

If this is working as expected, then it seems like some documentation should be updated.

For example, the docs for `store_var` say "Stores any Variant value in the file". Maybe this should instead say something like "Stores any non-Object value."

Also, it would probably be a lot less confusing for folks if `store_var` could report an error when you provide an Object value.

**Comment by kleonc** [comment]
`File.store_var()` uses internally `encode_variant()` method, [here's the source code for `3.3.2` for the part handling serializing `Object`](https://github.com/godotengine/godot/blob/7610409b8a14b8499763efa76578795c755a846d/core/io/marshalls.cpp#L1079-L1141). As you can see in there, if `p_full_objects` flag is `true` then it doesn't do anything with the properties which doesn't have `PROPERTY_USAGE_STORAGE` flag set in their respective `PropertyInfo.usage`. Which would mean that `text` property in your example doesn't have that flag set. Indeed if you'd add this to your example:
```
func _ready() -> void:
	foo_saved.text = "foo"

	for p in foo_saved.get_property_list():
		prints(p.name, p.usage)
```
it will output:
```
script 7
Script Variables 256
predefined_text 8192
text 8192
```
so both `predefined_text` and `text` have usage flags set to [`PROPERTY_USAGE_SCRIPT_VARIABLE`](https://docs.godotengine.org/en/3.3/classes/class_%40globalscope.html#enum-globalscope-propertyusageflags) and that's why they're ignored by `encode_variant()` (and thus by `store_var()`).
Changing your `foo.gd` script to:
```
class_name Foo
extends Object

var predefined_text := "Hey"
var text: String

func _get_property_list() -> Array:
	return [
		{
			name = "predefined_text",
			type = TYPE_STRING,
			usage = PROPERTY_USAGE_STORAGE,
		},
		{
			name = "text",
			type = TYPE_STRING,
			usage = PROPERTY_USAGE_STORAGE,
		},
	]
```
changes previous output to:
```
script 7
Script Variables 256
predefined_text 8192
text 8192
predefined_text 1
text 1
```
so these properties are now listed twice and now you're getting your expected output:
```
Expected: foo; Actual: foo
Expected: Hey; Actual: Hey
```
Not sure if these properties being listed twice is expected nor if the custom property definitions are interpreted as overrides or something like that; didn't check none of that.

For sure this needs to be clarified in the docs.

**Comment by levilindsey** [comment]
Oh, that's very interesting. That's the first I've heard of PropertyUsageFlags. Thanks for the info!

I assume PropertyUsageFlags have thus far been mostly limited to internal use, since there isn't much documentation for them, and it doesn't seem like there is a very ergonomic way to configure them (this seems like the kind of use-case that decorators from other languages would be ideal for).

It would definitely be nice to have some more documentation describing why PropertyUsageFlags are important and when you should use them, and also some docs describing overriding _get_property_list() as the intended pattern for configuring PropertyUsageFlags.

**Comment by levilindsey** [comment]
I've taken a stab at updating the docs in a couple places.
