### ISSUE TITLE
OUYA gamepad joystick movement/tilting causes game to crash on OUYA.

### ISSUE THREAD

**Issue by Corruptinator** [godotengine/godot#4944]
Windows 10, 64 bit; Godot Engine 2.0.3 (STABLE RELEASE)

What happened is that after finding out that there has been improvements and updates to export any games from godot to the OUYA, I've decided to give it a test run to see how it goes, so far it starts up nicely and the framerate doesn't seem to stutter or fail. I've pressed the O,U,Y,A buttons and the D-pad and those work very well, but however the problem is that the instant I've started to tilt the gamepad joystick, the game instantaneously crashes

I've tried separate empty projects to see if there were any instances of causing the same issue without using gdscript or any other method, but alas they all failed and crashed.

So it does export, but then later crashes after tilting the joystick on the OUYA gamepad. Could the X,Y,Z, controller axis be somehow affected by the OUYA's android OS?

**Steps to reproduce:**
1. Run ADB.exe
2. Create any empty project and export it to any android or OUYA devices.
3. Test all the buttons on the OUYA gamepad controller.
4. After it crashes by tilting the OUYA gamepad joystick, run this command on ADB:
   " adb bugreport > bugreport.txt" (Should be located in the [USERNAME] folder) and see if there is
   any error related to the joystick crash.

P.S. If anybody likes to request my bug report for this issue, please let me know so then I can post and share my results.

**Comment by Hinsbart** [comment]
mhh, I don't have an OUYA controller.
So, a crashlog / backtrace would be nice :)

**Comment by Corruptinator** [comment]
Just a moment, I'll upload a bug report shortly.

**Comment by Corruptinator** [comment]
[OUYA_REPORT.txt](https://github.com/godotengine/godot/files/292064/OUYA_REPORT.txt)

**Comment by Corruptinator** [comment]
Hopefully someone will find out what went wrong with the joystick tilt error crash.

Also this is my first time I've uploaded a crash report, and I've made sure there are no passwords or Internet Ids there aren't supposed to be in there for security reasons, however if there are please let me know so I can take it down and replace it with another crash report.

**Comment by bojidar-bg** [comment]
To note, the godot logcat output starts at `05-31 19:54:11.784`, or line `13323`

**Comment by Corruptinator** [comment]
Hello! thanks for informing me where the logcat output starts, and I did see the backtrace output where I assume this is what the error tells me (as bojidar-bg explained earlier):

`05-31 19:54:17.404   108   108 I DEBUG   : backtrace:

05-31 19:54:17.404   108   108 I DEBUG   :     #00  pc 00078398  /data/data/org.godotengine.ouyatest/lib/libgodot_android.so (InputDefault::joy_axis(unsigned int, int, int, InputDefault::JoyAxis const&)+428)

05-31 19:54:17.404   108   108 I DEBUG   :     #01  pc 00a43ff8  /data/data/org.godotengine.ouyatest/lib/libgodot_android.so (_err_print_error(char const*, char const*, int, char const*, ErrorHandlerType)+252)

05-31 19:54:17.404   108   108 I DEBUG   : 
`

So is this a bug that needs to be fixed or is there an alternative, because I was looking forward to experiment with the OUYA console, not just for making games but to get a hands on experience for making a game for a home console as a hobby.

**Comment by Corruptinator** [comment]
Sorry to interrupt but has there been any updates on this issue so far?

**Comment by bojidar-bg** [comment]
@Corruptinator I think no, since I haven't heard of it on IRC... Would be nice if someone checks that `InputDefault::joy_axis` makes no assumptions about pointers.

**Comment by Corruptinator** [comment]
Well I guess that this could take a while for this bug to get fixed, nothing more I can do on my end.

**Comment by fgoo** [comment]
Same crash on Pong 2D game on NVIDIA Shield TV using its Controller.

**Comment by Corruptinator** [comment]
That doesn't sound good. : (

**Comment by LaPieza** [comment]
I made some testing on this, tried on the Ouya with the Ouya controller and the DS3 (PS3 Dual Shock 3), and it crashes not only with the joysticks but also with the joysticks buttons, some of the shoulders and start and select (DS3), the Dpad is not recognized by the Joystick demo and doesn't move the character on the 3d platformer demo, also tried a keyboard and it didn't move the platformer character, tried a mouse and I moved it using the arrows that appear on screeen.

From the mouse and keyboard I noticed something else, when you plug or unplug them from the USB port the game also chrashes.

Then I tested the same demos on an JXD S5800 (an android gaming phone with built in game pad) and the demos worked perfect, the gamepad didn't move the character but it was recognized by the joystick demo except for L2 and R2 and the dpad, face bottons where on sligntly diferent order but worked ok, also paired an Ouya controller on bluetooth and it didn't crashed the demos, the buttos and axis were all messed up but thats because of the JXD configuration for that controller the is shown as HID, finaly tried the DS3 on with an USB OTG cable and it made the demos crash the same as in the Ouya, conecting and disconecting devices doesn't crash the demos.

As a final notes the shaders on the platfomer demo look perfect on the JXD S5800 and on the Ouya they look bad, and on the JXD I notice the crash of the demo send the application to the background and restart it but doesn't fully close it.

**Comment by fgoo** [comment]
@Corruptinator I found a solution, use Unity 3D, it's free now. Export to Android TV with no issues, easy to use.

**Comment by bojidar-bg** [comment]
@Hinsbart Would you have time to give this a more substantial check? :smile:

**Comment by Hinsbart** [comment]
I'm looking into this atm :)
However there seem to be issues with android template compilation.. see https://github.com/godotengine/godot/pull/5077#issuecomment-232062888 :/

**Comment by Corruptinator** [comment]
I guess the Android Template still has a few or more bugs to crush completely, and hopefully there is still room for improvement.

**Comment by fluffrabbit** [comment]
I too have experienced crashes. Every time you wiggle the joystick on a gamepad called the Mocute the Godot game dies. Just thought I'd throw that out there even though this issue is 2 months old.

**Comment by marcelofg55** [comment]
@Corruptinator Hi, I don't have an OUYA controller but I found that joy_axis is missing a check that might be related to this crash, could you test the attached patch? Thanks!
[joy_axis.patch.zip](https://github.com/godotengine/godot/files/1073130/joy_axis.patch.zip)

**Comment by fluffrabbit** [comment]
I tried to compile but shit went wrong and I'm too out of practice. But just so you know, your patch, if it works, could open up a whole world of possibilities for VR, so good job.

**Comment by Hinsbart** [comment]
It'll "work" but doesn't fix the underlying problem. Somehow the os sends us event that are out of range... need to check why this happens or else we might be missing events.

**Comment by marcelofg55** [comment]
@fluffrabbit I can give you a hand for the compiling if you want.

**Comment by fluffrabbit** [comment]
@marcelofg55 I live in a giant perpetual motion machine that always keeps me at arm's length from the fuzzy wuzzies. As a result, I don't have the luxury of doing online builds with Gradle, which is why building the Android export templates is such a pain in the ass. Apparently Godot now requires a version of Gradle which I have not pre-downloaded, or I am reading the error messages wrong. I should be able to compile it myself if it's allegedly "easy" to compile, but the last time I made progress on the engine side of Godot I was operating at 110% and didn't have IRL deadlines distracting me.

**Comment by fluffrabbit** [comment]
@marcelofg55 It turns out Godot updated the Gradle and Android build tools requirements without telling anyone. Changing a couple values in build.gradle to match what I had let me build, but only if the values are changed between running scons and gradlew (scons overwrites build.gradle), so backing up the Gradle-related files is a must. And here I thought the Godot 2 branch wouldn't change much. Guess Godot 3 is still a while coming.

Now, as for the patch itself, it does suppress crashing upon joystick movement. But the actual joystick signals are not recognized, just like the guy said. So I can't actually use the thumbstick to control anything, it's just dead.
