### ISSUE TITLE
Backspace doesn't work while Shift key is pressed, in the script editor

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#49517]
### Godot version

fbb5a541ef30f41bb7814687e9cd9f11e991faa7

### System information

Windows 10

### Issue description

Pressing the backspace key to remove the previous symbol in the script editor does not work if the shift is pressed. This is regression not presented in 3.3.

### Steps to reproduce

Create a script and try.

### Minimal reproduction project

Too easy to reproduce.

**Comment by Calinou** [comment]
I can confirm this and was pretty sure I reported it at some point, but I can't find an issue about it right now.

**Comment by EricEzaM** [comment]
A regression from #43663 because the shortcuts use "exact match" for their checking. This is because we have things like Ctrl+Backspace, etc which perform different actions, and we do not want overlap of those.

The safe option here I suppose is to just add Shift+Backspace to the list of commands, as done in the PR linked above.
