### ISSUE TITLE
Vulkan: "Display unshaded" option still shows camera effects such depth of field

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#49696]
### Godot version

v4.0.dev.custom_build [085e1d3c0]

### System information

manjaro linux Gnome

### Issue description

When User whants to display unshaded its explicit that he doesnt want camera effects also:

![image](https://user-images.githubusercontent.com/58845030/122480167-b6980600-cfa2-11eb-92c5-a0b787edecfa.png)

but they still are shown, when enabled.

Solutions:

* Solving this stated issue

and/or Adding a option in the `Camera3D` or in `WorldEnvironment` an option do enable/disable camera effects without needing to remove them (this will be more practice)

### Steps to reproduce

* Click on perspective
* Then select "Display Unshaded"

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is technically correct, but it makes sense to disable camera effects whenever any debug draw mode is used.

**Comment by lander-vr** [comment]
I'm also stumbling upon this issue, particularly with autoexposure (not sure if that warrants a new issue if it may be related to this) being applied in the unshaded viewmode using physical light units:
It starts off at a reasonable exposure
![image](https://github.com/godotengine/godot/assets/31851431/f9353195-1049-4567-9bf6-3c2867d9eda4)

and then continues brightening to an entirely unusable result
![image](https://github.com/godotengine/godot/assets/31851431/38c8c21e-07d5-46f2-a126-13fb7cf21ab6)

I just made a proposal for in-editor exposure locking that may or may not be useful or relevant to this. [#9532](https://github.com/godotengine/godot-proposals/issues/9532)

**Comment by ChristopheClaustre** [comment]
Hi, looking for a good first issue since I haven't contributed for a year at least.
If I understand well, the goal is to hide the "Camera Attributes" (outlined in yellow) attribute on "WorldEnvironment" when the user is debugging rendering ? With unshaded or other debug rendering mode ?

![image](https://github.com/godotengine/godot/assets/11921745/2d363ad7-1b8e-4844-8085-abca8bd40fde)

Well I think I could do it but it feels weird.
Hiding an irrelevant attribute when a behaviour is disabled on a node like "dof_blur_far_enabled" that hide other dof_blur_far's attributes (outlined in yellow) I understand, but hiding an attribute when the editor is in a specific transient state it lost me.
Do we have another case of this behaviour ? Do we really want it ?

If yes I will try to do it.

**Comment by Calinou** [comment]
> If I understand well, the goal is to hide the "Camera Attributes" (outlined in yellow) attribute on "WorldEnvironment" when the user is debugging rendering ? With unshaded or other debug rendering mode ?

The inspector entry shouldn't be hidden, but depth of field should be made ineffective when the user is currently using the Unshaded debug draw mode in one of the 3D viewports.

Remember that multiple viewports can be displayed at once in the 3D editor, and they may be using different draw modes each.

**Comment by ChristopheClaustre** [comment]
Oh my bad I misunderstood this line on first message :

> but they still are **shown**, when enabled.

Okay so we want to disable the DOF for example when user activate one of the debug draw mode.

> Remember that multiple viewports can be displayed at once in the 3D editor, and they may be using different draw modes each.

Good point, I guess in this case we want to disable camera effects only for the viewports in debug draw mode but not for the others ?

**Comment by Calinou** [comment]
> Good point, I guess in this case we want to disable camera effects only for the viewports in debug draw mode but not for the others ?

Yes, we should aim to do that if possible.

**Comment by ChristopheClaustre** [comment]
Okay, I will look at it soon.
