### ISSUE TITLE
`Geometry.is_polygon_clockwise` seems to return the opposite of expected results

### ISSUE THREAD

**Issue by davidscholberg** [godotengine/godot#49716]
### Godot version

v3.3.2.stable.official

### System information

Windows 10, GLES3,  GeForce GTX 1070/PCIe/SSE2

### Issue description

The results of `Geometry.is_polygon_clockwise` seem consistent with a cartesian coordinate system where the Y axis grows upwards. However, I was under the impression that 2D graphics in Godot used a coordinate system where the Y axis grows downward, and since `Geometry.is_polygon_clockwise` is an inherently 2D function, the results given seem to be the opposite of what I would have expected.

### Steps to reproduce

1. Add the following line to any node script and observe that the output is `True`, which is not consistent with the 2D coordinate system that Godot uses with the Y axis growing downward.

```gdscript
print(str(Geometry.is_polygon_clockwise(PoolVector2Array([Vector2(-1, -1), Vector2(-1, 1), Vector2(1, 1), Vector2(1, -1)]))))
```

**Comment by Calinou** [comment]
cc @Xrayez

**Comment by Xrayez** [comment]
It looks like a bug to me. I have previously exposed this method to scripting in #28987, but I never really paid attention to result because nowadays I'm calculating polygon's signed area to determine the orientation in my code.

See also #30251 which can be added as an alternative to `is_polygon_clockwise()`, because orientation could be computed via area alone, and computing area will be more useful for other stuff, so we could remove `is_polygon_clockwise()` in Godot 4.0:

```gdscript
var clockwise = Geometry.polygon_area(polygon) < 0           # aka Hole
var counter_clockwise = Geometry.polygon_area(polygon) > 0   # aka Boundary
```

**Comment by markopolojorgensen** [comment]
Just ran into this issue using godot 4.0.1. If `is_polygon_clockwise` is going to remain accessible via script, would it be better to change what it's returning or update documentation to let users know? I understand if it's low priority, seems like it's only affected three or four people in ~2 years.
