### ISSUE TITLE
GDScript with "$." crashes the editor

### ISSUE THREAD

**Issue by addixff** [godotengine/godot#49764]
### Godot version

v4.0.dev.custom_build.7aebb8f81

### System information

Windows 10

### Issue description

When you start typing `$.` in the script editor, it throws unhandled exception:
`read access violation. p_subscript->base was nullptr.` in `modules\gdscript\gdscript_analyzer.cpp` line 2731

### Steps to reproduce

Start the script editor, define any function and try to type `$.` in function body.

**Comment by Blackiris** [comment]
When writing `$.` , the GDScript analyzer expects to have an expression like `object.attribute` because of the dot (Token::PERIOD)
But in this case, the **base** is $ and it is parsed as a get_node expression on nothing, which means **null**.

Then later when Godot wants to get the **base** type, it crashes at gdscript_analyzer line 2731:
`if (p_subscript->base->type == GDScriptParser::Node::IDENTIFIER) {`

**Comment by addixff** [comment]
The issue is rather more deeper. The parser should not recognize `$.` as subscript.

**Comment by Blackiris** [comment]
Because of the dot, the parser will go to GDScriptParser::parse_attribute and create a subscript whose base is nullptr:
https://github.com/godotengine/godot/blob/fdccc0b2195813d7874a7d9b97fff46081772e1e/modules/gdscript/gdscript_parser.cpp#L2543-L2570

Here p_previous_operand is indeed null.

Don't know if a subscript is sometimes allowed to have a null base, but if not, another solution would be to stop it here and generate an error.

**Comment by addixff** [comment]
The parser should generates "illegal node name" error or similar. Fix this on the analyser level is a mistake IMHO.

**Comment by Blackiris** [comment]
Indeed, it already does it in parse_get_node:
https://github.com/godotengine/godot/blob/fdccc0b2195813d7874a7d9b97fff46081772e1e/modules/gdscript/gdscript_parser.cpp#L2706-L2707

(the return nullptr will go to p_previous_operand in parse_attribute just after)

But it will still continue to the analyzer layer nonetheless.

Making the fix in GDScriptAnalyzer::reduce_subscript is not wrong too I think.
This method really needs p_subscript->base to be non-null to do its job, then if the base is null, there is nothing to reduce and the method should stop directly. It will make at least this method more robust.

**Comment by addixff** [comment]
You are a little right, but fix this in the analyser only masks the real problem in the parser. I have no time to analyse the whole parser code, but at firce glance, it requires some parser code refactoring.

**Comment by Blackiris** [comment]
I understand the idea, if the error is catched in the first layers, the better it will be.
That's why in parse_attribute, I am wondering if we could return nothing is the base (p_previous_operand) is null. It's just I don't know if a null base could be valid or not...

**Comment by MisoMosiSpy** [comment]
#50259 , has same issue. Also it has no operator involved just adding a quotation mark makes it crash. I believe that parser shouldn't consider this as an operator so that analyzer need not have to deal with it. 

I am going through parser code to understand this better, however, if someone feels that I am totally off track feel free to correct :)

**Comment by Blackiris** [comment]
Indeed, they are linked, same reason => the subscript base in null.
Adding a quotation mark ends the string, which make the following text executed as code.

PR #49897 does fix the case describe in https://github.com/godotengine/godot/issues/50259#issue-939117789
