### ISSUE TITLE
RichTextLabel.push functions do not push BBCode tags onto the tag stack

### ISSUE THREAD

**Issue by Nosrick** [godotengine/godot#49855]
### Godot version

3.3.2.stable.mono.official

### System information

Windows 10

### Issue description

When using the `RichTextLabel.push_x()` functions, they don't seem to modify the BBCode at all. Calling them does nothing.

### Steps to reproduce

1. Create a RichTextLabel
2. Create a script (tested GDScript and C#)
3. Make the script call one of the `push_x()` functions
     1. I can't get any of them to work, maybe that's just me.
4. Observe as the BBCode is not modified, and no changes are made to the text

### Minimal reproduction project

[RichTextLabel Problem.zip](https://github.com/godotengine/godot/files/6701696/RichTextLabel.Problem.zip)

**Comment by Calinou** [comment]
This is intended. You should use one method to append rich text or the other, not both. The `push_x()` functions do *not* use BBCode to improve performance and avoid security issues with players entering arbitrary BBCode into chat and having it parsed as such.

**Comment by Nosrick** [comment]
Ah, I see, thank you.
Documentation wasn't particularly clear about this, so the documentation tag is very welcome.
Thank you!

**Comment by Nosrick** [comment]
Sorry, didn't mean to close that!

**Comment by timothyqiu** [comment]
I once came across an issue that maybe caused by this.

Updating the bold font after `push_bold` won't affect existing content. This is becasue `push_bold` creates a frame using the current bold font. When the theme changes, `RichTextLabel` updates itself by reloading the BBCode. But since there is no BBCode generated for `push_bold`, it won't be able to update.
