### ISSUE TITLE
Corruption on VRAM-compressed texture mipmaps (S3TC compression)

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#49981]
### Godot version

eb318d3e04ac6d3bb01b0f2a8311d06ba55c3a2b

### System information

Windows 10, Vulkan, Nvidia GTX 1080 (471.11)

### Issue description

It appears that the mipmaps of textures imported as VRAM Compressed can appear with odd skewing distortion.

![editor_screenshot_2021-06-29T050000](https://user-images.githubusercontent.com/12756047/123735281-dc70b500-d896-11eb-8c9c-564f3d6dd6a8.png)

The cube in the centre is using a texture with VRAM compression, while the other cubes are using the other four options. This issue does not appear to affect all textures, but it seems consistently broken on the example texture provided.

### Steps to reproduce

Simply open the example project and observe the middle cube with VRAM Compressed version of the texture at an appropriate distance to see the mipmaps.

### Minimal reproduction project

[mipmaps.zip](https://github.com/godotengine/godot/files/6730593/mipmaps.zip)

**Comment by SaracenOne** [comment]
I don't know exactly how long this has been an issue, but it seems to have been around for a while at least.

**Comment by SaracenOne** [comment]
A bit more follow-up info, the main reason this particular texture seems to fail is due to it being non-power-of-two. I've also been informed that this particular issue is likely specific to S3TC compression.

**Comment by lawnjelly** [comment]
It is probably just that the texture compression works in blocks (e.g. 4x4), so you will often get compression artifacts across these borders in the base level or mipmaps. As you say, using a power of 2 texture size makes them less likely.

**Comment by lyuma** [comment]
[The khronos OpenGL wiki](https://www.khronos.org/opengl/wiki/S3_Texture_Compression) claims the following:
> S3TC is a block-based format. The image is broken up into 4x4 blocks. For non-power-of-two images that aren't a multiple of 4 in size, the other colors of the 4x4 block are taken to be black. Each 4x4 block is independent of any other, so it can be decompressed independently.

From what I can tell, on OpenGL, there seems to be no hard requirement about dimensions of S3TC compressed textures being powers of two or multiples of four... However, apparently DX11 and WebGL impose some limitations to prevent it [except for 2x2 and 1x1 mipmaps since those are special]. I can't find any info on Vulkan, however.

The problem Godot has is it also allows mipmaps for non-power of two textures... which means, even if LOD 0 is a multiple of 4, some of the lower resolution LODs might be odd dimensions. I don't know if there is a good way around this contradiction, other than either ignore the DX11 requirement, or block VRAM Compression for any non-power of two texture with mipmaps enabled?

Just to see what other engines do in these cases, interestingly, Unity completely doesn't allow mipmaps for non-power of two textures (it defaults to resizing to nearest power-of-two when mipmaps are enabled), and it also does not allow compression for non-multiple-of-4... so they went the easy route of just not allowing this case.
![image](https://user-images.githubusercontent.com/39946030/123779437-06ba7680-d887-11eb-955c-092995ab1ae7.png)

Regardless of what is compatible with ANGLE and DX11, it seems fair to me that Godot shouldn't produce incorrect results or crash on non-multiple-of-4 S3TC compression. So while Godot might want to consider applying stricter rules, there's still a bug here that should be fixable, I would think. See also: #48509

**Comment by GerbilSoft** [comment]
I tested importing a 958x552 image in both Godot 3 and 4 to compare the results.
Source image: https://tcrf.net/images/f/fc/SCU-TEST_RR_areaMap-bg.png

Godot 3: Creates a DXT1 format texture, looks correct.
Godot 4: Creates a DXT5 format texture, has skewed output and broken colors.

It seems Godot 4's DXTn encoder isn't padding the last tiles. (958 should be padded out to 960)

================================

Godot 3.3 has DXTn compression in module_compress_squish.cpp:
https://github.com/godotengine/godot/blob/9d0e0fe783f05b7ea504f0d233afc7441a74c535/modules/squish/image_compress_squish.cpp#L187

which calls out to the third-party squish module for the actual compression:
https://github.com/godotengine/godot/blob/3.3/thirdparty/squish/squish.cpp#L181

Squish is given the *original* unaligned width/height, not a padded width/height, and it pads the last 4x4 tile correctly.

================================

Godot 4 has DXTn compression in image_compress_etcpak.cpp:
https://github.com/godotengine/godot/blob/e5c6c773e99e3f9aae4ac8a804f392416c871285/modules/etcpak/image_compress_etcpak.cpp#L148

_compress_etcpak() ends up calling either CompressDxt1Dither() or CompressDxt5() with a mipmap size value that's been aligned to 4 pixels. However, this is telling the compression function that the original image is (in this case) 960 pixels, but it's actually 958 pixels. This is why the image ends up broken.

**Comment by Zylann** [comment]
I also noticed transparent textures with VRAM compression completely fail to render mipmaps, when it worked in Godot 3:
![image](https://user-images.githubusercontent.com/1311555/147715576-af2e0f6c-d48c-407d-a56c-5bb40f85fabc.png)

Is this the same issue or should it be a different one?

**Comment by clayjohn** [comment]
> Just to see what other engines do in these cases, interestingly, Unity completely doesn't allow mipmaps for non-power of two textures (it defaults to resizing to nearest power-of-two when mipmaps are enabled), and it also does not allow compression for non-multiple-of-4... so they went the easy route of just not allowing this case. ![image](https://user-images.githubusercontent.com/39946030/123779437-06ba7680-d887-11eb-955c-092995ab1ae7.png)
> 
> Regardless of what is compatible with ANGLE and DX11, it seems fair to me that Godot shouldn't produce incorrect results or crash on non-multiple-of-4 S3TC compression. So while Godot might want to consider applying stricter rules, there's still a bug here that should be fixable, I would think. See also: #48509

It looks like Unreal doesn't even let you use mipmaps if your texture is non power of two https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/Textures/Importing/ (also tested using the texture from OP)

From the Unity docs: https://docs.unity3d.com/560/Documentation/Manual/ImportingTextures.html

> It is possible to use NPOT (non-power of two) Texture sizes with Unity; however, NPOT Texture sizes generally take slightly more memory and might be slower for the GPU to sample, so it’s better for performance to use power of two sizes whenever you can. If the platform or GPU does not support NPOT Texture sizes, Unity scales and pads the Texture up to the next power of two size. This process uses more memory and makes loading slower (especially on older mobile devices). In general, you should only use NPOT sizes for GUI purposes.

So I agree, we porbably need to be stricter about texture dimensions as well. In the short term, we should give the user an appropriate error and disable mipmaps. In the medium run, we should have a nicer UX that allows users to automatically pad nonpot textures

**Comment by lyuma** [comment]
Regarding being strict, I agree that it's better to fail the import tell the user to fix their art so they aren't surprised when it's blurry (due to scaling by a few pixels. I like that Unity lets you choose how to deal with power-of-two. Currently, in Godot, you can use the "Max Size" setting but that resizes in both dimensions, and it applies a separate resize from the power-of-two one, effectively causing two resizes, so it might not be optimal (since both width and height might need to be resized differently).

About your comment, two things to note:
- Before etcpak was merged, Godot actually enforced the same rules as Unity. However, it did it by automatically scaling up to the nearest power-of-two if mipmaps enabled, and scaling to the nearest multiple-of-four if not (which probably causes aliasing)

My draft PR at #46931 only tries to restore this old behavior.

- Even if you are strict about dimensions, there will still be mipmap levels for 2x2 and 1x1 (or Nx1 if not square). These are allowed out of necessity, but because they still use integer blocks, it expects to compress a 4x4 block, which means that we need to pass a padded buffer.

The old "modules/etc" library took in width&height in pixels, so I think it somehow handled this case, while "etcpak" is more strict. Once I add the code to scale Nx2 and Nx1 buffers to multiple of 4, I'll submit that PR.
