### ISSUE TITLE
Tab with edit (not save) script not show modification icon (*)

### ISSUE THREAD

**Issue by mefihl** [godotengine/godot#4998]
**Operating system or device - Godot version:**
Windows 10, 2.1 alpha with 182ee80

**Issue description** (what happened, and what was expected):
When change script (not save), tab with this script not show modification icon (*). See screenshot: [http://postimg.org/image/8cojic3zf/](http://postimg.org/image/8cojic3zf/)

**Steps to reproduce:**
1. Open script.
2. Change code.
3. Look to open script list and open tab.

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Well that's not a bug IMO, the script is independent from the scene. By editing the script, you haven't changed the scene itself, so you don't need to same it. What you changed was the _behaviour_ of the scene, since it uses the script internally, but it would be the same with instanced scenes: if you change the source of the instanced scene, it won't mark scenes that instance it as changed.

**Comment by mefihl** [comment]
Ok my mistake. Close
