### ISSUE TITLE
PinJoint2D connections are unstable on RigidBody2Ds chained together

### ISSUE THREAD

**Issue by CardboardCarl** [godotengine/godot#50002]
### Godot version

3.2.3-stable

### System information

Windows 10, GLES3

### Issue description

PinJoint2Ds, even when parent collisions are disabled, softness is set to 0, and bias is set to 0.9, will stretch its two joined bodies apart and behave erratically when the joint is under any sort of stress. This allows larger colliding bodies to stretch the joint apart and pass through it when they should not. 

The example given in my reproduction project is a chain of RigidBody2Ds linked together with PinJoint2Ds. It seems the weight of lower links in the chain will stretch the upper links, which allows the two bodies on either side of the chain to sometimes pass through to the other side.

![image](https://user-images.githubusercontent.com/31835840/123811540-55850200-d8c1-11eb-9ca7-3e20d9989d32.png)

The effect seems to be amplified on smaller bodies, which is to be expected with Godot's physics integration method.

### Steps to reproduce

- ***Open `PinJoint2D bug.zip`***
- ***Import the project.godot or open Scene.tscn***
- ***Run the project***

**You can also edit the PinJoint2D properties in `cordSegment.tscn` if so desired**

*Alternatively, you can create a RigidBody chain using another method. It will likely produce the same result.*

### Minimal reproduction project

[PinJoint2D bug.zip](https://github.com/godotengine/godot/files/6733976/PinJoint2D.bug.zip)

**Comment by Calinou** [comment]
See also https://github.com/godotengine/godot/issues/6323.

**Comment by CardboardCarl** [comment]
Just to be clear, #6323 has a different scope than this issue, and the example given there ended up being the result of a completely different problem.

**Comment by pouleyKetchoupp** [comment]
Chain of bodies using physics joints are very sensitive to mass differences. You won't be able to stabilize it properly with a rigid body at the end with a larger mass than your chain pieces.

My suggestions would be:
-Make sure the last piece in the chain has a mass of 0.1 like the other ones, it fixes the issue. You can also test with slightly larger masses to adjust the behavior you want, but the larger it is compared to 0.1 the more difficult it's going to be to stabilize the chain.
-You can also set higher linear and angular damping on all the chain pieces, that generally helps a lot with joint stabilization.
-In case you do need the end piece to have a much larger mass because of interactions with other bodies, you can possibly set its mode to Kinematic, set its layer not collide with the chain and set its transform to match the last piece of the chain each frame by script. This way it will create a similar effect without affecting the chain's physics directly.

I'm closing this issue since it won't be fixed in the engine, but don't hesitate to ask if you need more help.
