### ISSUE TITLE
`find_next_valid_focus()` causes the game to hang

### ISSUE THREAD

**Issue by LoneDespair** [godotengine/godot#50127]
### Godot version

3.3.2.stable

### System information

Windows 10

### Issue description

Calling find_next_valid_focus() while parent nodes are hidden, causes the game to hang indefinitely

### Steps to reproduce

already written on issue description

### Minimal reproduction project

[find_next_valid_focus bug.zip](https://github.com/godotengine/godot/files/6758531/find_next_valid_focus.bug.zip)

**Comment by VedatGunel** [comment]
Duplicate of #49975.

**Comment by Energyxxer** [comment]
This is still occurring in Godot 4.4.

I had to modify the original MRP a little bit to reproduce it (moving control nodes around the tree), but it's still very much consistent.
[find_next_valid_focus bug 4.4.zip](https://github.com/user-attachments/files/19968397/find_next_valid_focus.bug.4.4.zip)

Please let me know whether it's possible to reopen the issue, or if I have to make a new one.

**Comment by precup** [comment]
@Energyxxer Since the MRP needed to be changed, I think opening a new issue would make sense, if you wouldn't mind.

I also just ran into this in the wild on a released, production game. If we need to pare that down to an MRP as well, we can, but it looks like the one provided is the same underlying issue despite being in `find_prev_valid_focus` instead.
