### ISSUE TITLE
"Create Debug Tangents" action on MeshInstance3D is missing undo/redo

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#50158]
### Godot version

4.0.dev (52e3f986a)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 465.31)

### Issue description

The Create Debug Tangents action on MeshInstance3D is missing undo/redo functionality.

### Steps to reproduce

- Create a MeshInstance3D node then add any primitive mesh resource to it.
- Select the MeshInstance3D node, go to the Inspector, click the "toolbox" button then choose **Create Debug Tangents**:

![image](https://user-images.githubusercontent.com/180032/124390399-b78f9e00-dceb-11eb-8599-ff38ad032629.png)

- Try to undo the action using <kbd>Ctrl + Z</kbd>.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
"good first issue" was a mistake. I assumed this is some editor action, but turns out this method is using a special flag that exposes it to the editor. It's called from the editor, but the logic is fully inside the node, so adding UndoRedo logic is tricky (without adding editor dependencies to the node).
