### ISSUE TITLE
Buttons not re-centering after deleting Custom buttons in popup Dialog.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#50192]
### Godot version

3.3.2 official

### System information

Windows 10

### Issue description

If you add custom buttons to any popup Dialogs, upon deleting them, the remaining buttons do not recenter.

### Steps to reproduce

Create a project with a button and any Dialog node that you can use "add_button()" on.
In the button put code that opens the dialog and adds a custom button through "add_button()".
Next close the Dialog node and make the second time the DIalog opens delete the custom button.
The resulting Dialog will have all remaining buttons off-centered. 

### Minimal reproduction project

In this reproduction project press the button once and you get this:
![Untitled-1](https://user-images.githubusercontent.com/26915986/124526873-33a7e580-ddc1-11eb-95aa-c6d11b3c7421.png)
Close the Dialog and press the button again.  This time it will add a new button.  All is well:
![Untitled-2](https://user-images.githubusercontent.com/26915986/124526888-428e9800-ddc1-11eb-8d19-7d3d3281442c.png)
close the dialog and push the Button again.  This time it will delete the custom button.  Notice how even though the custom button is gone, things are off-centered:
![Untitled-3](https://user-images.githubusercontent.com/26915986/124526900-4e7a5a00-ddc1-11eb-91cf-acd4dc37f3aa.png)
Close dialog and press the button again.  Now the code adds a custom button back.  Again, everything is off centered:
![Untitled-4](https://user-images.githubusercontent.com/26915986/124526929-66ea7480-ddc1-11eb-961a-52ebe6c6d49d.png)

Here is the project (code is in C#):
[Dialog.zip](https://github.com/godotengine/godot/files/6766606/Dialog.zip)

**Comment by kleonc** [comment]
Happens because `AcceptDialog::add_button` adds spacers (here `Control`s extending horizontally) around buttons so the layout in `HBoxContainer` with the buttons is like: `spacer-button-...-(spacer-button)-...-spacer`. Removing a button makes spacers adjacent, hence the issue.
![firefox_gJxOndLWZR](https://user-images.githubusercontent.com/9283098/124610767-10d50a00-de71-11eb-9337-bac4f23d5a8c.png)

Adding `AcceptDialog::remove_button` which would handle removing spacers accordingly should solve this issue. I'll open a PR.

---

@ondesic As a workaround for now you'd need to remove them manually. For example adding such extension method should do the thing (C#):
```
public static class AcceptDialogExtensions
{
    public static void RemoveButton(this AcceptDialog acceptDialog, Button button)
    {
        if (button == null)
        {
            return;
        }

        HBoxContainer hbc = acceptDialog.GetOk().GetParent<HBoxContainer>();
        if (button.GetParent() != hbc)
        {
            return;
        }

        Node rightSpacer = hbc.GetChild(button.GetIndex() + 1);
        if (rightSpacer != null)
        {
            hbc.RemoveChild(rightSpacer);
            rightSpacer.QueueFree();
        }
        hbc.RemoveChild(button);

        if (button.IsConnected("pressed", acceptDialog, "_custom_action"))
        {
            button.Disconnect("pressed", acceptDialog, "_custom_action");
        }
    }
}
```
and here's your button pressed handler modified to use it:
```
public void _btnPressed()
{
    if (clickCount == 2)
    {
        cd.RemoveButton(btnCustom);
        btnCustom.QueueFree();
    }
    else if (clickCount == 1 || clickCount == 3)
    {
        btnCustom = cd.AddButton("Extra", false, "custom");
    }

    cd.PopupCentered();
    clickCount++;
}
```
