### ISSUE TITLE
[Text Editor] Shift+Tab shortcut only works when multiple lines are selected

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#50279]
### Godot version

v4.0.dev.custom_build [cb4e42155]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

When you select multiple lines and press `SHIFT+TAB` the tab goes back one step which is ok:
before:
![image](https://user-images.githubusercontent.com/58845030/124931449-9a531c00-dfd8-11eb-98f5-ab7ab47b2ec1.png)
after:
![image](https://user-images.githubusercontent.com/58845030/124931519-ac34bf00-dfd8-11eb-8687-61baa366d408.png)

 But if the cursor is over one line only (without selecting) `SHIFT+TAB` doesnt work:
before:
![image](https://user-images.githubusercontent.com/58845030/124931620-c9698d80-dfd8-11eb-95d9-71c9e0c5d84d.png)

after:
![image](https://user-images.githubusercontent.com/58845030/124931640-ccfd1480-dfd8-11eb-87ac-8321e70d5641.png)

PS: it only works if the single line is selected, but without any selection it doesnt work!

### Steps to reproduce

* Select Multiple lines
* press the shortcut
* put the cursor at a single line without selection
* press the shortcut

### Minimal reproduction project

N/a

**Comment by Calinou** [comment]
cc @Paulb23

**Comment by Calinou** [comment]
> What is the desired behavior? It seems like Godot 3 always unindents the line the cursor was on, but Godot 4 appears to have changed it to only remove tabs and spaces the cursor is touching.

The 3.x behavior definitely feels more natural to me.

**Comment by MewPurPur** [comment]
This has been around since alpha 1, probably longer. I can't quite understand how the indent/unindent logic is supposed to be, so I won't touch it, but here's the correct one in 3.x

https://github.com/godotengine/godot/blob/3.x/scene/gui/text_edit.cpp#L3225

and incorrect one in 4.beta

https://github.com/godotengine/godot/blob/master/scene/gui/code_edit.cpp#L898

To me it looks like unindent is always supposed to call unindent_lines(), not only when something is selected or you're at the beginning of a line. But maybe there are exceptions or something?
