### ISSUE TITLE
Godot y position problem

### ISSUE THREAD

**Issue by Nep-Toodles** [godotengine/godot#50303]
### Godot version

3.3 stable

### System information

Windows 10

### Issue description

if we look at graph then
![image](https://user-images.githubusercontent.com/59413955/125029687-c4c0da00-e0a9-11eb-807d-c3406ade9b35.png)
when we add x it will go right
when we subtract x it will go left
when we add y it should go up but it goes down in godot
when we subtract y it goes down but goes up instead in godot

is it some kind of bug cause while doing graph projects i get confused a lot or is it just like that and cant be fixed??.

### Steps to reproduce

i dont know the steps for this to fix

**Comment by SirQuartz** [comment]
What you've described here is not a glitch in Godot, this is simply how computers measure the X and Y coordinates in screen space. Going down increases the Y value on a display, and going up decreases the Y value. This because the origin of a display is in the upper left corner of the display. 

This is not a glitch, it's intended behavior, and you'll find this to be true in any game engine or program that deals with displays.
