### ISSUE TITLE
Vulkan: Projector textures on SpotLight3D and OmniLight3D needs adjustment to scaling

### ISSUE THREAD

**Issue by pracedru** [godotengine/godot#50445]
### Godot version

4.0.dev

### System information

PopOS, Vulkan, Nvidia GTX 1060 

### Issue description

The current build of Godot only show a small section of the center of the texture on spotlight.
Maybe a texture scale feature could be added to the light projector texture.

### Steps to reproduce

Make 3D scene.
Add Spotlight.
enable shadows.
Add texture to Projector.
Place a surface on which the light can be seen.
![image](https://user-images.githubusercontent.com/15041324/125590576-c7b6e612-4083-4021-85af-a4839b7c2d2b.png)
Here a 11x11 tiled texture is added to the projector and only 4-5 partial segments of the texture is shown in the light.

**Comment by jcostello** [comment]
Can you show what happens if you move the light away to almost hit the mesh with the edge of the cone? Also can you set up the default attenuation?

**Comment by pracedru** [comment]
Attenuation, Angle, Angle Atenuation and the position of the light has no impact on the scaling of the texture. The same small subsection is always projected.

**Comment by dusakus** [comment]
So I hit that problem recently, which prompted me to look into the engine to check how the projector calculates the texture UV, and I found this:

`vec2 proj_uv = normal_to_panorama(splane.xyz) * spot_lights.data[idx].projector_rect.zw;` 
[link to this exact line in scene_forward_lights_inc.glsl](https://github.com/godotengine/godot/blob/897afb69a7f1130894d4e76857fb52ff5bd37544/servers/rendering/renderer_rd/shaders/scene_forward_lights_inc.glsl#L880)

Since we are talking about SpotLights, I tried removing the "normal_to_panorama()" part, as I'm pretty sure SpotLights are not supposed to use panoramic textures.
The resulting line is

`vec2 proj_uv = splane.xy * spot_lights.data[idx].projector_rect.zw;`

And the result?
![image](https://user-images.githubusercontent.com/3822753/148541062-2de2f90f-6511-478d-b683-9d8b9f3cfba7.png)

While I'm sure this isn't a proper fix, it might at least point someone much more knowledgeable to possibly implement one.

**Comment by akien-mga** [comment]
Fixed by #57888.
