### ISSUE TITLE
Blinn specular is too intense

### ISSUE THREAD

**Issue by Kobrar** [godotengine/godot#50455]
### Godot version

3.3.2

### System information

gles3, ubuntu, intel i5 8350u

### Issue description

Blinn
![obraz](https://user-images.githubusercontent.com/5860567/125643098-f64ee5e3-93a6-42dc-9850-5ed27f3f4fd3.png)
Phong
![obraz](https://user-images.githubusercontent.com/5860567/125643181-20687d71-46ec-48eb-90ce-2917250a6b6e.png)
Schlick ggx
![obraz](https://user-images.githubusercontent.com/5860567/125643265-7f7b053b-3fec-456c-ac0d-a8e261b0b7e6.png)
Lambert diffuse, Specular 0.5, Metallic 0.0, Roughness 1.0
Tonemap filmic, exposure 1.0, white point 16.0
Needless to say, this result is unusable. It looks like the Blinn and Phong are not normalized at all, and the Blinn is boosted some too.

### Steps to reproduce

1. Create a meshinstance and a directionallight
2. give the meshinstance a sphere and a spatialmaterial
3. set the albedo to something low, like 64,64,64
4. alternate between specular shading modes to see significant differences between algorithms

**Comment by clayjohn** [comment]
Just testing with a PlaneMesh you can see that both the Blinn and Phong settings are very bright when using a rough material. In both cases they indeed look like they are not being normalized at all.

**Comment by clayjohn** [comment]
This turned out to be more complex than I thought (but also should have been more obvious). Physically Based specular Materials are typically the product of 3 functions:
1. a normal density function
2. a geometric function (masking function)
3. a Fresnel function

Right now we use all three in the GGX shading mode, but for Blinn and Phong we just use the NDF. The surface albedo of a material is only references in the Fresnel function. This means that neither Blinn nor Phong take the surface albedo into account. This is closer to the behaviour of blinn and phong in non-PBR materials. But it does result in very bright highlights on dark materials. Essentially, the Blinn and Phong models are non-PBR, but they are energy conserving. They are much cheaper than the GGX model but they do not look very similar.

**Comment by akien-mga** [comment]
Fixed by #51410.
