### ISSUE TITLE
New Theme Editor - Control Picker broken, Horizontal Min Size is too large, Cannot remove item types (?), No UndoRedo support (Proposal?)

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#50460]
CC @pycbouh
Related to https://github.com/godotengine/godot/pull/49388

### Godot version

3.4.beta1

### System information

Linux

### Issue description

- [ ] 1) Control picker tries to select one giant "Panel" instead of individual elements. Scrolling also shows an issue with clipping content.
![image](https://user-images.githubusercontent.com/14253836/125658686-1ae9c831-da96-4c2d-8164-a2f682c3c3b5.png)
* Click the control picker button.
* Click on any UI element in the preview.

- [ ] 2) Decreasing the window width while the theme is open causes a horizontal overflow issue.
https://user-images.githubusercontent.com/14253836/125661079-66bdcce9-4e35-48b5-945e-9ab66c24eca2.mp4
* Decrease the window width to the minimum. The inspector is now partially or completely invisible.

- [ ] 3) There seems to be no option to remove an item type (could be a wontfix, not sure).
![image](https://user-images.githubusercontent.com/14253836/125660044-c061417c-a97f-47d9-91bd-e4f1b0704776.png)
* Add an item that you do not want anymore.
* Try to remove it.

- [ ] 4) None of the functions (Variable modification, add/remove item types, etc.) seem to support `UndoRedo`.
https://user-images.githubusercontent.com/14253836/125661422-709fae4e-7f81-4d18-82b2-0f0965e7a3e2.mp4
* Make any sort of modification to the theme.
* Try to undo your change.

### Steps to reproduce

See Above

### Minimal reproduction project

Very basic testing project with a theme and a label.
[Test.zip](https://github.com/godotengine/godot/files/6817723/Test.zip)

**Comment by pycbouh** [comment]
> Decreasing the window width while the theme is open causes a horizontal overflow issue.

It's a pretty big editor, not sure how much distance we can extract from it while keeping it usable.

> There seems to be no option to remove an item type (could be a wontfix, not sure)

Types don't exist in a way that would allow to remove them and yet have a nice flow to add them before adding items. Empty types aren't saved with the resource itself, so it doesn't matter other than some occasional clutter if you decide to remove a type.

> None of the functions (Variable modification, add/remove item types, etc.) seem to support `UndoRedo`.

Indeed, it was never integrated with editor's UndoRedo. Functions that existed before the overhaul never supported it either, likely because they can take some time to complete. But I guess it can be implemented for some of the new ones.

**Comment by akien-mga** [comment]
Fixed by #50519.
