### ISSUE TITLE
Godot becomes unresponsive after Creating Theme From Current Editor Theme

### ISSUE THREAD

**Issue by Roopaish** [godotengine/godot#50514]
### Godot version

3.3.stable

### System information

Windows 10, GLES3

### Issue description

Godot becomes unresponsive after Creating Theme From Current Editor Theme

### Steps to reproduce

- Select a node (I used control node)
- Select Theme in Inspector
- Click empty > New Theme
- In Theme Preview panel click Edit Theme
- Click Create From Current Editor Theme

**Comment by pycbouh** [comment]
This is because the editor theme is huge and it takes some time to copy it and display it in the Inspector dock. You probably don't want to do this for your game anyway, and should create a theme from an empty template instead.

Either way, with https://github.com/godotengine/godot/pull/49774 this is resolved in `3.x` and you will not have this problem in 3.4, so closing.
