### ISSUE TITLE
FBX models are imported with wrong offset

### ISSUE THREAD

**Issue by AndreaCatania** [godotengine/godot#50633]
### Godot version

Master: a09088ac8fb4cb50e2269d4769e4eedf2731df49

### System information

Fedora, GTX 970

### Issue description

The FBX models are imported with a wrong offset, so the mesh looks wrong. This is likely a regression, since if we try to re-import the models by removing the `.godot` directory the map, where those FBX models are used, have incorrect offset.

Since before this issue wasn't there, this is likely to be a regression.

### Steps to reproduce

Here I've the FBX and the GLTF for the same model, that can be used as sample to debug the issue. (The gltf is correctly imported).

- Download the file.
- Import the two versions of the same file.
- Verify if the offset of both meshes are the same. 

[Models.zip](https://github.com/godotengine/godot/files/6846101/Models.zip)

**Comment by Calinou** [comment]
> Since before this issue wasn't there, this is likely to be a regression.

Do you know the date on which the last correct import was made? Knowing this would greatly speed up bisecting the regression.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
