### ISSUE TITLE
Inherited Scene  does not recognize that it's parent has a script

### ISSUE THREAD

**Issue by apaza610** [godotengine/godot#50759]
### Godot version

3.3.stable

### System information

Windows 10, Nvidia GTX970

### Issue description

I'm creating a piano game, therefore I thought about creating 1 base scene for 1 piano "Key"(parent) and 2 children keys "KeyWhite" & "KeyBlack" (as inherited scenes), I also BUILD THE LEVEL Map (piano with 24 keys), ONLY AFTER THAT I created a script for the "Key"(parent) but I noticed 2 situations in the instanciated child keys:
1) They DO NOT recognize that the parent has a script !!!
2) but creating new Instanciations, they DO recognize the parent's script (no problem at all).

Since I can't find a way to Force Refresh the OLD instances in the Level, I ended up REBUILDing THE ENTIRE LEVEL ....
**otherwise I would need to write the scripts BEFORE the creation of the Level**

### Steps to reproduce

1- create scene "Map1"
2- create scene "Key" (parent scene)
3- create inherited scene "KeyWhite"
4- create inherited scene "KeyBlack"
5- create instance of "KeyWhite" inside "Map1"
6- create a SCRIPT attached to "Key" (parent)
7- create instance of "KeyBlack" inside "Map1"
8- here is the problem: "KeyWhite" does NOT have the script attached, conversely "KeyBlack" HAS it, a way to force update is needed here
![TheProblem](https://user-images.githubusercontent.com/10149862/126729495-3925830c-b6aa-4825-86ee-5ce5aea9ee7f.png)

### Minimal reproduction project

[Piano03.zip](https://github.com/godotengine/godot/files/6866230/Piano03.zip)

**Comment by foxydevloper** [comment]
The problem seems to be that property changes don't propagate through more than 1 level of inheritance.
If you have: `Node C inherits from Node B inherits from Node A`, changing  a property inside of `Node A` will only update the new property for `Node B`, not for `Node C`

https://user-images.githubusercontent.com/12120644/126730657-dcde2752-4a19-4d59-a113-c84542b422f0.mp4

When you changed Key's script, it only updated the new script for KeyBlack and KeyWhite's scenes, it didn't update for the instances of KeyBlack and KeyWhite.

You can fix this manually by reverting the `script` property for the instances of KeyBlack and KeyWhite:
![2021-07-22_22-31-04](https://user-images.githubusercontent.com/12120644/126731150-a37d5f66-3618-4816-aa83-acc4bc4d1ea1.png)

This issue occurs in v4.0.dev.custom_build [515670351] as well.

**Comment by foxydevloper** [comment]
Related to: https://github.com/godotengine/godot/issues/7984

**Comment by apaza610** [comment]
Thanks @foxydevloper, that indeed solves the problem...
