### ISSUE TITLE
Top Level property of Node3D is broken

### ISSUE THREAD

**Issue by foxydevloper** [godotengine/godot#50813]
### Godot version

v4.0.dev.custom_build [2b1e6e3]

### System information

Windows 10

### Issue description

`top_level` property for Node3D doesn't work properly. It's supposed to make the transforms for the node in global space, however it doesn't. Node3Ds with `top_level` enabled still inherit transformations from their parent.

https://user-images.githubusercontent.com/12120644/126876960-0d3d61b6-0526-4a49-a872-56f830fb1cf8.mp4

The property work fine for CanvasItem.

https://user-images.githubusercontent.com/12120644/126876952-c8c089fd-c217-48bc-8932-597d69b33d38.mp4

This property is new in 4.0, added in https://github.com/godotengine/godot/pull/42448

### Steps to reproduce

- Enable Top Level on a 3D node
- Move it's parent node
- It will move as well, which shouldn't happen.

### Minimal reproduction project

[testing_top_level.zip](https://github.com/godotengine/godot/files/6872848/testing_top_level.zip)

**Comment by foxydevloper** [comment]
Can confirm this bug still occurs as of v4.0.alpha.calinou [c80540f9a]
It's also a bit odd the `top_level` property appears under "Visibility" for CanvasItem, even though CanvasItem doesn't have a transform. Meanwhile, `top_level` is under "Transform" for Node3D.

**Comment by Flavelius** [comment]
This is still an issue in 4.0.beta17

**Comment by kkhhaann** [comment]
Still an issue in 4.0.1, but it is editor-only.

**Comment by SlothDevLlama** [comment]
I'm not an expert in this repository since I've been contributing far less than I probably want in the future. But I've looked into the code and it seems, the set_as_top_level might be broken here:

https://github.com/SlothDevLlama/godot/blob/72f7131be1be81e3b8c3d45732d55e5765b95dde/scene/3d/node_3d.cpp#LL734C12-L734C12

the main issue I guess could be, that once the editor_hint is active, it will not set top_level_active accordingly.
Even when processing notifications it will check for editor_hint and hence won't set top_level_acitve to true:
https://github.com/SlothDevLlama/godot/blob/72f7131be1be81e3b8c3d45732d55e5765b95dde/scene/3d/node_3d.cpp#L156

but later when checking for transform propagation, it will only check against top_level_active, but not top_level:
https://github.com/SlothDevLlama/godot/blob/72f7131be1be81e3b8c3d45732d55e5765b95dde/scene/3d/node_3d.cpp#LL113C18-L113C18

Maybe @Calinou can confirm my wild guess?

**Comment by Calinou** [comment]
I can confirm this on 4.1.dev 33957aee6 (Linux).
