### ISSUE TITLE
Can't undo TileMap bucket tool

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#50871]
### Godot version

8932b55

### System information

W10

### Issue description

This is probably known issue, but the new tile editor doesn't support undo for bucket tool. I looked into it and it's not like it's unimplemented. It's just bugged. You can undo bucket erase and bucket replace. But if you fill empty area with tiles, then you can't undo. I looked into the code and noticed these lines:
https://github.com/godotengine/godot/blob/8932b55011126b06315ed544a0bc1f715ec37dd8/editor/plugins/tiles/tile_map_editor.cpp#L1216-L1219
When you compare them with the lines above:
https://github.com/godotengine/godot/blob/8932b55011126b06315ed544a0bc1f715ec37dd8/editor/plugins/tiles/tile_map_editor.cpp#L1205-L1206
The undo and redo seem to be swapped, but they do work correctly. Also there's this `commit_action(false)` that basically means the fill isn't executed here. I know where the changes are done, but I have no idea what is wrong and why would it break only in case of filling empty space ;_;

This bug is rather frustrating, so it would be nice to have it addressed soon >_>

### Steps to reproduce

1. Add TileMap
2. Fill some empty area
3. Try undo :(

**Comment by groud** [comment]
These two lines should be removed for the bucket tool:
```
if (!erase_button->is_pressed() && E->get().source_id == TileSet::INVALID_SOURCE) {
   continue;
}
```
Depending on whether the release executes the action or not, the drag_modified map contains either the previous or the new cells. In the bucket case, it contains the previous cells, while for the rect tool, it contains the new cell. This explains the difference between the two.

If you want it quick, feel free to open a PR for the fix. Otherwise I'll include it in my next PR to implement TileMap layers.
