### ISSUE TITLE
Worklet.deprecated, WebBrowser no Sound.-

### ISSUE THREAD

**Issue by esbvaGames** [godotengine/godot#50944]
### Godot version

3.3.2 and 3.4-beta2

### System information

Windows 10, OpenGL es 3.0, Graphics 620 intel

### Issue description

Web Browser No Sound.-
![Godot_Woklet-Deprecated](https://user-images.githubusercontent.com/5530499/127185666-50d1ec72-5c8e-487b-b72c-dfacc760007d.png)

### Steps to reproduce

extends Control

var stream = null
var volumen = 1.0
var fileName = 'res://TecnoGuitar.ogg'

func _ready():
	set_process(false)

	stream = load(fileName)

	$AudioStreamPlayer.set_stream(stream)
	$AudioStreamPlayer.seek(0.0)
	$AudioStreamPlayer.volume_db   = volumen
	$AudioStreamPlayer.pitch_scale = 1
	$AudioStreamPlayer.play()

### Minimal reproduction project

[WebMusic.zip](https://github.com/godotengine/godot/files/6886917/WebMusic.zip)

**Comment by foxydevloper** [comment]
Tested on 3.4-beta2, this warning about deprecation shows up in the console, but the audio still plays for me once I click inside of the page. On the latest version of Chrome (92.0.4515.107)

![chrome_2021-07-27_14-02-27](https://user-images.githubusercontent.com/12120644/127204934-b0eccb97-7f43-4cc9-99e8-7faf2554b1b6.png)

**Comment by Faless** [comment]
We now also support `AudioWorkletNode` for non-thread builds but we still prefer `ScriptProcessorNode` because it actually works better in non-threaded environments so you will keep seeing the deprecation notice, but it will (should) fallback automatically to `AudioWorkletNode` whenever they drop support for `ScriptProcessorNode`.

As mentioned in the warning the user must interact with the page before the audio can start, because we can't have good things on the web without people trying to abuse them.

**Comment by esbvaGames** [comment]
My Game es here, i migrante versión 3.4.x,. Audio y fixed into pck, but Big size.....
https://gamejolt.com/games/SpaceBattle/326130
