### ISSUE TITLE
For Controls, using accept_event() in _input(event) breaks _gui_input(event)

### ISSUE THREAD

**Issue by PatrickCaughey** [godotengine/godot#51032]
### Godot version

3.3.1.stable.official

### System information

Windows 10, Intel i5, NVIDIA Geforce GTX

### Issue description

When using `accept_event()` or `get_tree().set_event_as_handled()` from inside `_input(event)`, `_gui_input(event)` will either "Lock on" or "Lock off" and will either trigger for every input event, even when the mouse is not over the Control, or not trigger for any events, even when it should. 

`has_focus()` returns false and release_focus() doesn't fix it.

It strangely might only happen if `accept_event()` is on click release, not on click pressed.

Also strangely, it "Locks on" or "Locks off" depending on if the click started inside the Control, not where it ended, which is when `accept_event()` is called

### Steps to reproduce

Give a Panel a script. 
Give it a `_gui_input(event)` that prints when clicked.
Give it a `_input(event)` that prints when mouse is released.
Test it and see it works as expected.
Set the  `_input(event)` to call `accept_event()` when it detects a mouse release.
Test it and see that if you click once on the panel it will always take mouse input, but if you restart and click first away from the panel, then the panel will never detect input events.

### Minimal reproduction project

[GodotBug.zip](https://github.com/godotengine/godot/files/6903252/GodotBug.zip)

**Comment by RandomShaper** [comment]
I'd say this is in part expected behavior.

`accept_event()` is documented to stop propagation of the event.

Also, the docs say that `_gui_input()` goes after `_input()`:
![image](https://user-images.githubusercontent.com/11797174/158059314-cc59695d-d66b-44a7-8e40-f2a628a65713.png)

Therefore, an `accept_event()` on `_input()` is expected to prevent the event from reaching `_gui_input()`. But that should only be for scripts. Engine's internal state should be able to recover from that.

Potential ways to address this:
a) Let the engine's `_gui_input_event()` run in an input accepted mode, which will make it only do what is needed to keep the state tidy. In the case of a mouse release event that would be releasing drag, clearing focus button mask, etc., but not run any side effect, including propagating the mouse release into scripts.
b) Don't allow `accept_event()` at `_input()`. Not cool, I guess.
b) Make `accept_event()` not avoid propagating the event into `_gui_input()`. Not very cool, either.

**Comment by Sauermann** [comment]
@RandomShaper
Regarding your potential solutions:
a) I played around with a possible implementation:
``` C++
diff --git a/scene/main/viewport.cpp b/scene/main/viewport.cpp
index e580e64db6..51cfe9be31 100644
--- a/scene/main/viewport.cpp
+++ b/scene/main/viewport.cpp
@@ -2033,6 +2033,17 @@ void Viewport::_gui_input_event(Ref<InputEvent> p_event) {
        }
 }
 
+void Viewport::_gui_accepted_input_event(Ref<InputEvent> p_event) {
+       ERR_FAIL_COND(p_event.is_null());
+
+       Ref<InputEventMouseButton> mb = p_event;
+       if (mb.is_valid()) {
+               if (!mb->is_pressed()) {
+                       gui.mouse_focus_mask &= ~mouse_button_to_mask(mb->get_button_index()); // Remove from mask.
+               }
+       }
+}
+
 List<Control *>::Element *Viewport::_gui_add_root_control(Control *p_control) {
        gui.roots_order_dirty = true;
        return gui.roots.push_back(p_control);
@@ -2695,6 +2706,8 @@ void Viewport::push_input(const Ref<InputEvent> &p_event, bool p_local_coords) {
 
        if (!is_input_handled()) {
                _gui_input_event(ev);
+       } else {
+               _gui_accepted_input_event(ev);
        }
 
        event_count++;
diff --git a/scene/main/viewport.h b/scene/main/viewport.h
index 1976b20502..2ab15af821 100644
--- a/scene/main/viewport.h
+++ b/scene/main/viewport.h
@@ -388,6 +388,7 @@ private:
        Control *_gui_find_control_at_pos(CanvasItem *p_node, const Point2 &p_global, const Transform2D &p_xform, Transform2D &r_inv_xform);
 
        void _gui_input_event(Ref<InputEvent> p_event);
+       void _gui_accepted_input_event(Ref<InputEvent> p_event);
 
        _FORCE_INLINE_ Transform2D _get_input_pre_xform() const;
 

```
d) verify if #58944 has other unintended consequences

**Comment by RandomShaper** [comment]
That code looks totally good to me. A PR with it is probably the best option now, maybe with a comment about the goal of the alternative code path.
