### ISSUE TITLE
The Script property appears doubled in the Remote inspector

### ISSUE THREAD

**Issue by tulipan-it** [godotengine/godot#51077]
### Godot version

v3.4.beta2.official

### System information

Windows 10

### Issue description

The script property doubles in the inspector when running the app and selecting 'remote'. Is present on all nodes, in every project, in a new project, after clearing the cache at User/AppData/Roaming/Godot/Projects.

![script_doubling_3_4_LI](https://user-images.githubusercontent.com/52129590/127689701-e232d00e-47e6-4436-8b89-a9673be2e3d6.jpg)

### Steps to reproduce

Create a new, simple, runnable project. Run it and go to the 'Remote tab'. Select any node. In the inspector, the 'script' property is doubled. Occurs both in 3.3.2 and 3.4.beta2.official.

### Minimal reproduction project

[Test_3_4.zip](https://github.com/godotengine/godot/files/6909171/Test_3_4.zip)

**Comment by uapaladin** [comment]
Sorry. By clearing the cache, I meant removing the project file at this location:
C:\Users\ulfij\AppData\Roaming\Godot\projects

And to clarify, I also meant that this didn't help. Not that it was a necessary step to reproduce the issue.

**Comment by Calinou** [comment]
I can confirm this on v3.4.beta.custom_build [d22f487df].

![image](https://user-images.githubusercontent.com/180032/127697442-3e1bd863-3424-4568-acb3-153630ccda6a.png)

**Comment by belzecue** [comment]
I just noticed this bug in 3.4-stable, Standard version (Linux).

I did some manual bisecting of releases and can tell you this regression was introduced in 3.2.4.beta2.  I'm embarrased I didn't notice this much earlier.

Here's a screenshot of 3.2.4.beta1 and 3.2.4.beta2.  Looks like in beta2 somebody removed the "Script" header, and now the duplicated "Script" properties for a node display together.  I'm not sure why a node has (had!) a separate "Script" section when it already had a script property within its Node section.  Maybe the person who made the change was trying to resolve that duplication.

In any case, from 3.2.4.beta2 forward we now have those duplicate script properties over/under each other, confusingly.

![3 2 4 beta1 good](https://user-images.githubusercontent.com/1931303/141654594-f75242cc-9d36-4049-864f-952a86582467.png)

![3 2 4 beta2 bad](https://user-images.githubusercontent.com/1931303/141654598-3994091f-a129-44d5-99e5-0d5fee509b36.png)

**Comment by Calinou** [comment]
> Here's a screenshot of 3.2.4.beta1 and 3.2.4.beta2. Looks like in beta2 somebody removed the "Script" header, and now the duplicated "Script" properties for a node display together. I'm not sure why a node has (had!) a separate "Script" section when it already had a script property within its Node section. Maybe the person who made the change was trying to resolve that duplication.

Indeed, the Script group was removed in https://github.com/godotengine/godot/pull/43566.

**Comment by raulsntos** [comment]
I have tested and can confirm this issue is present at least since **3.0**.

---

The inspector gets the properties from an object using the `Object::get_property_list` method which calls the virtual implementation and then adds some properties (like the `script` property). For the remote inspector, the object is an instance of `ScriptEditorDebuggerInspectedObject` which implements the virtual `_get_property_list` method by returning all of the object's properties (including `script`) so it gets added twice.

The properties retrieved from the `_get_property_list` virtual method (the remote properties) are added without a category and the `script` property that is added by `Object::get_property_list` at the end is added within the `Script` category (until #43566 which removes the category), but the `script` property has always been duplicated.

I can see a two ways to fix this:

1. Since we know `Object::get_property_list` will add the `script` property, the implementation of `ScriptEditorDebuggerInspectedObject::_get_property_list` can skip the `script` property and not push it.
2. The implementation of `Object::get_property_list` can check if the `script` property was added by the virtual method and not push it in this case.

I'm not sure which option is preferred.

_Note: `ScriptEditorDebuggerInspectedObject` was renamed to `EditorDebuggerRemoteObject` in 4.0 but the issue still applies._
