### ISSUE TITLE
Ability to perform live editing from a PC to another PC

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5108]
It would be very welcome to have support for live editing (and one-click deploy, remote filesystem, …) when two PCs are on the same Ethernet or Wi-Fi network. This way, you could develop the game on one PC, and test it on another PC.

**Comment by reduz** [comment]
Just run godot with -rdebug <ip>

**Comment by vnen** [comment]
While running Godot with `-rdebug ip:port` option does work, currently there's no way to make the editor listen for debug connections. So I propose to add a button to make the editor debugger start listening to a connection, otherwise it's impossible to use this feature.

**Comment by Calinou** [comment]
**Update:** This issue is still relevant as of https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

**Comment by Anutrix** [comment]
Junior job pending since atleast more than year. Anyone interested?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
This is now implemented by https://github.com/godotengine/godot/pull/52226 in 4.0alpha and https://github.com/godotengine/godot/pull/60819 in 3.5 and later.
