### ISSUE TITLE
GLTF export invalid in 3.4 beta 2

### ISSUE THREAD

**Issue by MrJoshBowman** [godotengine/godot#51132]
### Godot version

3.4 Beta 2 Official

### System information

Macbook Pro 2019 16", AMD Radeon Pro 5500M

### Issue description

Exporting a GLTF/GLB file in 3.4 Beta 2 causes errors in PowerPoint and Windows 3D Viewer.

I tested the same exact code in GDv4.0 and it exports just fine from GD4.0

### Steps to reproduce

Open the minimal reproduction.
Run it.
Let it export the GLB file.
Try importing the file into PowerPoint or Windows 3D Viewer

### Minimal reproduction project

[20_GLTF_Export_GD3.4Beta2.zip](https://github.com/godotengine/godot/files/6912154/20_GLTF_Export_GD3.4Beta2.zip)

**Comment by lyuma** [comment]
Progress update.
I'm looking through the validation errors:

GLB_CHUNK_LENGTH_UNALIGNED | Length of 0x004e4942 chunk is not aligned to 4-byte boundaries. | --
-- | -- | --

<- should be an easy fix.

EMPTY_ENTITY | Entity cannot be empty. | /accessors/0/min
-- | -- | --

<- the line to assign `accessor->min = min` was missing, should be fixable

MESH_PRIMITIVE_POSITION_ACCESSOR_WITHOUT_BOUNDS | accessor.min and accessor.max must be defined for POSITION attribute accessor. | /meshes/0/primitives/0/attributes/POSITION
-- | -- | --

<- Same error as above caused by empty `"min":[]` field.

Now this is where things start getting strange:

ACCESSOR_VECTOR3_NON_UNIT | Vector3 at accessor indices 0..2 is not of unit length: 0.9921572334828104. | /meshes/0/primitives/0/attributes/TANGENT
-- | -- | --
ACCESSOR_INVALID_SIGN | Vector3 with sign at accessor indices 0..3 has invalid w component: 0.9921259880065918. Must be 1.0 or -1.0. | /meshes/0/primitives/0/attributes/TANGENT

<- The `array[Mesh::ARRAY_TANGENT]` seems to be vector3 and missing the w component, despite the length being a multiple of 4 (e.g. it's an array of size 16, and the first 12 values are correct)
```
TANGENT: [0.99213, 0.00000, -0.00787, 0.99213]
TANGENT: [0.00000, -0.00787, 0.99213, 0.00000]
TANGENT: [-0.00787, 0.99213, 0.00000, -0.00787]
TANGENT: [0.00000, 88.00000, 88.00000, 0.00000]
```
Digging into `VisualServer::_get_array_from_surface` I see the attached project is hitting the `ARRAY_FLAG_USE_OCTAHEDRAL_COMPRESSION` case.
This looks to be a regression introduced by PR #46800 (d274284) in that when compression is in use, querying ARRAY_TANGENT seems to only return three components per tangent and neglects the w component:

https://github.com/godotengine/godot/pull/46800/files#diff-833822f7ca153a64d1cd65f155a808a571f5c2b6149f5bcecd8be66c56d3ce63R1492-R1515

That data is then passed to the export, which attempts to export these corrupt tangents. I'm going to go ping @The-O-King to see if they have ideas how to reconstruct the w components in VisualServer when ARRAY_TANGENT is requested.

I haven't yet learned which (if any) of these are making the resulting glTF files unreadable in windows 3D Viewer, but fixing these is a good first step.

**Comment by The-O-King** [comment]
@lyuma you are right there was a bug in the implementation that you pointed out where I should be multiplying j by 4 rather than 3 in order to decode the tangent vector, and the sign of the tangent vector should already by taken into account, I just wasn't writing into the vector properly! I'm working on a PR for that right now

**Comment by MrJoshBowman** [comment]
thanks @The-O-King, I've just downloaded and built the latest 3.x branch and still finding that the export bug is still occurring, hopefully your fix has made this another step closer to finding a fix :)

**Comment by lyuma** [comment]
Yeah awesome to see the fix to the octahedral compression in. that should cut down drastically on the validation errors.

I'll be looking into this issue with fire next week along with issue 51292 and other 3.4 gltf bugs.

**Comment by MrJoshBowman** [comment]
I completely understand there are many competing priorities across the different aspects of Godot development currently underway. I've reached a point in my own development however where I really need to ability to export GLTF files out to be able to continue on. I wish I understood the C backend to be able to help out but my coding knowledge is limited to GDScript.

If anyone is able to put aside some time to see where this bug is at and potentially figure out a fixed I'd be so grateful.

**Comment by lyuma** [comment]
@MrJoshBowman
The fix should be committed. When Godot 3.4 rc3 is out, please check your projects and see if addresses all your issues.

If you run into any more issues with GLTF export, please open a new issue, with a reproduction project showing the problem.
Thanks for your reports!

**Comment by MrJoshBowman** [comment]
Brilliant! Thanks so much @lyuma 👍🏻👍🏻

**Comment by MrJoshBowman** [comment]
![Untitled](https://user-images.githubusercontent.com/27105009/140048289-8c5dc428-1fed-4f1b-bd74-5c8677b7ac32.jpg)

@lyuma @fire 

So I've tested the GLTF output with a standard material with some different flags on material and texture and these are the results. Taking the exported model into Blender, removing the Godot inserted material and simply re-applying a Principled BSDF with transparency and the same texture works. So there's something still a bit screwy with how Godot is applying materials to exported models out of Godot.
- Transparency is all messed up
- Turning 'Filter' off on the texture doesn't appear to have any sharpening effect on the outputted model even though it sharpens in Godot itself. 
- Blender's 'Clostest' option for texture display does what I would expect turning off 'Filter' to do on the Godot exported material

**Comment by fire** [comment]
Godot does not handle filter modes correctly at all in import or export. Theres a bug for it. The other issues is gltf only has opaque, alpha scissors and blend. Theres a bug in transparency maybe.

**Comment by Calinou** [comment]
See https://github.com/godotengine/godot/issues/45206.

**Comment by MrJoshBowman** [comment]
hmmm well it's really great that Lyuma was able to fix the GLTF export not being corrupted so that's definitely a great step forward, but the inability to set non-filtered textures still visually breaks GLTF exported models when transparencies are involved, but I can see how that is a separate issue to this so ✅✅ for being able to get the GLTF exporting models again, and onto hoping filters and alphas are able to be fixed soon!

**Comment by MrJoshBowman** [comment]
Also testing out the .gltf export and finding that the separated texture and mesh files aren't able to be imported. Many other applications create the .gltf file with embedded textures and meshes so that they're more compatible with a wider array of standard apps like PowerPoint.

**Comment by fire** [comment]
There are three modes gltf files can be:

1. gltf + bin + texture files
2. gltf and with the bin and texture files expanded into a text encoding and then saved as json
3. glb which is the same as 2 but with the bin and texture files as binary without encoding into base64.
