### ISSUE TITLE
CanvasGroup breaks with any material applied

### ISSUE THREAD

**Issue by Haydoggo** [godotengine/godot#51204]
### Godot version

v4.0.dev.calinou [c17a54165]

### System information

Windows 10, Vulkan Clustered, GTX 1060 6GB (471.41)

### Issue description

Applying a CanvasItemMaterial or ShaderMaterial to a CanvasGroup node cause it to render as a white rectangle

![image](https://user-images.githubusercontent.com/14885846/127961397-3198800e-b0f2-4c4b-b58d-96d7b709d39f.png)

### Steps to reproduce

1. Create CanvasGroup node
2. Add Sprite as a child
3. Apply material to CanvasGroup node

### Minimal reproduction project

[CanvasGroupBug.zip](https://github.com/godotengine/godot/files/6921200/CanvasGroupBug.zip)

**Comment by thomaskole** [comment]
Can confirm this on Linux too.
Having access to the CanvasGroup material and manipulating it (blurring, dropshadow, etc) would be a killer feature.

**Comment by DragonAxe** [comment]
When creating a shader for CanvasGroups, I have to use
`COLOR = texture(SCREEN_TEXTURE, SCREEN_UV);`
instead of
`COLOR = texture(TEXTURE, UV);`.

I think this is because it uses a back buffer to render sub-nodes to. My guess is that material shaders use TEXTURE/UV and not SCREEN_TEXTURE/SCREEN_UV which means materials don't work, but custom shaders will.

Can CanvasGroups be re-coded to use TEXTURE/UV? That would seem to make more sense in terms of usability.

**Comment by golddotasksquestions** [comment]
Thanks to @DragonAxe I realized today CanvasItem shaders have been working with CanvasGroups all this time, only `texture(TEXTURE, UV)` did not work in a CanvasItem shader on a CanvasGroup material.

The solution is like DragonAxe states above to use texture(SCREEN_TEXTURE, SCREEN_UV) instead of texture(TEXTURE, UV), but this seems incredibly confusing! Especially so because when used on a CanvasGroup, texture(SCREEN_TEXTURE,UV) does not behave like it would take SCREEN_TEXTURE or SCREEN_UVs at all.

Is there any possibility to make this make more sense? If changing this to make texture(TEXTURE, UV) is not possible, can we maybe at least introduce a new texture and uv constants for the CanvasGroup, rather than using SCREEN_TEXTURE and SCREEN_UV?

**Comment by Zireael07** [comment]
Looks like something needs documented, if I'm reading the somewhat rambling comment by @golddotasksquestions right?

**Comment by arkology** [comment]
@Zireael07 not sure that it's documentation issue. As examples, CanvasItemMaterial uses TEXTURE, so it breaks CanvasGroup. And if SCREEN_TEXTURE behaves like TEXURE, we don't have actual SCREEN_TEXTURE (For CanvasGroup TEXTURE should clear backbuffer, SCREEN_TEXTURE should not). So it's definitely the bug. Only if @reduz  doesn't say it's a feature.

**Comment by golddotasksquestions** [comment]
@Zireael07 
Documentation is never a good solution to fix a completely confusing and counter intuitive workflow. A better solution is to improve the workflow so it becomes less confusing and more intuitive. As a byproduct you then also need less overall documentation.

**Comment by clayjohn** [comment]
I agree, using ``TEXTURE`` and ``UV`` would be way more intuitive than using ``SCREEN_TEXTURE`` and ``SCREEN_UV``. As it is implemented I understand  the technical reasons why it was originally implemented using ``SCREEN_TEXTURE``, but I will take a deeper look and see if there is a way to make this better.

**Comment by thomaskole** [comment]
Super happy to see this working, now you can do cool things like this drop-shadow effect. 🎉 

![tmp](https://user-images.githubusercontent.com/29757178/208686854-72d4684d-7df6-4e35-bf54-28912dfb47f2.gif)

It would be even better if Canvas Group could be made compatible with `canvas_item` shaders.
Right now, the `TEXTURE, UV` vs. `SCREEN_TEXTURE, SCREEN_UV` breaks this compatibility.

Effects such as this [Squish](https://godotshaders.com/shader/squish-sprite/) or this [Perspective](https://godotshaders.com/shader/2d-perspective/) don't work as a result, and would require a separate sprite / canvas group version.

**Comment by Prototypist1** [comment]
I'd like to make a CanvasGroup with blend mode add. Is there any way to do that?

**Comment by Haydoggo** [comment]
> I'd like to make a CanvasGroup with blend mode add. Is there any way to do that?

You can, but for the reasons discussed above, you'd currently have to use a `ShaderMaterial` to do so. Here's a minimal add blend mode shader for Beta 17:

```HLSL
shader_type canvas_item;
render_mode blend_add;

uniform sampler2D screen_tex : hint_screen_texture;

void fragment() {
	COLOR = texture(screen_tex, SCREEN_UV);
}
```

**Comment by Prototypist1** [comment]
Awesome! Thank you so much!

**Comment by peter-rocchio** [comment]
> Super happy to see this working, now you can do cool things like this drop-shadow effect. 🎉
> 
> ![tmp](https://user-images.githubusercontent.com/29757178/208686854-72d4684d-7df6-4e35-bf54-28912dfb47f2.gif) [ ![tmp](https://user-images.githubusercontent.com/29757178/208686854-72d4684d-7df6-4e35-bf54-28912dfb47f2.gif) ](https://user-images.githubusercontent.com/29757178/208686854-72d4684d-7df6-4e35-bf54-28912dfb47f2.gif) [ ](https://user-images.githubusercontent.com/29757178/208686854-72d4684d-7df6-4e35-bf54-28912dfb47f2.gif)
> 
> It would be even better if Canvas Group could be made compatible with `canvas_item` shaders. Right now, the `TEXTURE, UV` vs. `SCREEN_TEXTURE, SCREEN_UV` breaks this compatibility.
> 
> Effects such as this [Squish](https://godotshaders.com/shader/squish-sprite/) or this [Perspective](https://godotshaders.com/shader/2d-perspective/) don't work as a result, and would require a separate sprite / canvas group version.

This is something I've been trying to do for a while now!  Do you mind sharing the shader?
