### ISSUE TITLE
Regression when loading a custom resource file into exported variable

### ISSUE THREAD

**Issue by StraToN** [godotengine/godot#51219]
### Godot version

3.4 beta 2

### System information

GNU/Linux Ubuntu 21.04

### Issue description

Having a script defining an exported variable to hold a custom resource this way:

```
tool
extends Node2D

var animations: ESCAnimationResource


func _get_property_list():
	var properties = []
	properties.append({
		"name": "animations",
		"type": TYPE_OBJECT,
		"hint": PROPERTY_HINT_RESOURCE_TYPE,
		"hint_string": "ESCAnimationResource"
	})
	return properties
```

The ESCAnimationResource resource is a nested resource using 2 custom subresources.

Issue:
In the Inspector, when I click on "Load" and select a TRES resource file, I get an error popup "The selected resource (Resource) does not match any type expected for this property (ESCAnimationResource)." and the variable doesn't keep the content of the file.

![image](https://user-images.githubusercontent.com/1289207/128051151-fd4d2c62-d4eb-4335-a3fd-0bb1f08f2e0e.png)

When doing the same using last stable Godot Engine v3.2, I still get the error popup, but the variable contains the expected value.

![image](https://user-images.githubusercontent.com/1289207/128051233-c03f6e58-81ff-41f2-a1cd-4da47520e759.png)

Can be linked to #45015

### Steps to reproduce

Load the attached project.
Open the Node2D scene
Select the root node
In the inspector, click "Load"
Select the file "mark_animations.tres" and click Open button

### Minimal reproduction project

[bug_load_nested_resource.zip](https://github.com/godotengine/godot/files/6925656/bug_load_nested_resource.zip)

**Comment by pycbouh** [comment]
> When doing the same using last stable Godot Engine v3.2, I still get the error popup, but the variable contains the expected value.

That's because this is not a regression, but a validity check doing its job.

**Comment by StraToN** [comment]
> That's because this is not a regression, but a validity check doing its job. Custom resource exports aren't supported out of the box and tricks are not a guaranteed way to achieve this.

I totally agree on this. I am just surprised of this difference between the 2 versions. Does this mean this was a bug in validity check in stable 3.2 that was fixed in 3.4 beta 2? If nothing was done on this purpose, this could be a side effect of something else. Just asking, I didn't follow the whole changelog tbh. If that is a bugfix in beta, ok to close as not a bug.

**Comment by pycbouh** [comment]
> Does this mean this was a bug in validity check in stable 3.2 that was fixed in 3.4 beta 2?

Yes, the control that is used in the Inspector for resource picking was refactored and exposed to the scripting API (so that plugin developers could use it), and in the process its logic was tightened (well, hopefully 🙃 ). As such it's supposed to actually validate types properly to be useful. As an unfortunate side-effect of this your workaround doesn't work anymore.

https://docs.godotengine.org/en/3.4/classes/class_editorresourcepicker.html
https://docs.godotengine.org/en/3.4/classes/class_editorscriptpicker.html

**Comment by lyuma** [comment]
Forgive me if I misunderstood your issue report, @StraToN but the fix is just to declare the variable as
```gd
var animations: Resource
```
instead of 
```gd
var animations: ESCAnimationResource
```

The reason for this is quite simple: script-made types with class_name are still just scripts attached to the type you extends... So in your case, you declare the class as
```gd
tool
extends Resource
class_name ESCAnimationResource
```
Because it's a GDScript which extends `Resource`, the correct way to reference that type is `Resource`, *not* by declaring the type as `ESCAnimationResource`.
The reason Godot 3.x accepted the latter at runtime (for non-exported data) is because it doesn't have type validation so it didn't tell you it was wrong... but the type of the variable is really Resource.

Making that one change to Node3D.gd seems to fix the test project for me:
![image](https://user-images.githubusercontent.com/39946030/128098189-7ad45656-1a73-44c9-a0f9-04255b376fcb.png)

And, because you implemented the "hint_string" in _get_property_list, the type validation still shows up in the inspector, so it seems like a simple fix to me.

Now, I know you're probably thinking right now that you want proper class extensions, but we simply don't have those yet: `class_name` is but a facade around attaching scripts to base Resource types. Though, one thing to look forward in Godot 4.x is the concept of GDExtension, which will be able to provide first-class types written in C++, should you really need that... but you don't.

**Comment by lyuma** [comment]
Ugh, I'm sorry I ran an old build by mistake. It really did break in the latest beta. :'-( selecting "Load" doesn't work any more.
