### ISSUE TITLE
Split Stream option in renderer broken

### ISSUE THREAD

**Issue by RevoluPowered** [godotengine/godot#51257]
### Godot version

3.x (63047093c9728974a7890f31096a36ced58ea60e)

### System information

MacOS Big Sur 11.4 (AMD Radeon Pro 5500M 4GB)

### Issue description

Enabling Editor Option -> Mesh Storage -> Split Stream causes mesh to distort and not render correctly

<img width="886" alt="Screenshot 2021-08-04 at 23 21 47" src="https://user-images.githubusercontent.com/748770/128262944-02efd467-0054-4465-a8c1-c0082ea7b020.png">

### Steps to reproduce

1. Open Ferris Wheel Mesh in Godot on Mac with the option enabled in the settings.
2. Distorted mesh should be all over viewport

Result
<img width="1231" alt="Screenshot 2021-08-04 at 23 22 31" src="https://user-images.githubusercontent.com/748770/128263201-13618b07-0b22-4849-8426-bbaa4be4b0ad.png">

### Minimal reproduction project

[FerrisWheel.zip](https://github.com/godotengine/godot/files/6934715/FerrisWheel.zip)

**Comment by The-O-King** [comment]
So I think this might be some confusion about how to use the Split Stream toggle

When the mesh is initially imported, it will be using whatever setting Godot was currently on for the import, but if you toggle the mesh import setting right after import and then try to open the mesh, it will not work because the mesh is still using the old split stream setting, it needs to be reimported and then the scene closed and opened again for the change to take effect

The option is also a global option, so when it's toggled one needs to reimport all meshes and reopen all scenes to have the change properly take place

This could imply that there needs to be more explanation in the tool tip to explain what happens/what needs to be done when the setting is toggled (or perhaps figuring out how to automate the reimports and restart as talked about previously in the original PR)

Could try doing a reimport of the mesh after toggling the split stream setting and then reopening the scene and see if that fixes things?

**Comment by RevoluPowered** [comment]
I am pretty sure this is fixed already by @The-O-King
