### ISSUE TITLE
Visible Collision Shapes debug in HTML5

### ISSUE THREAD

**Issue by leotada** [godotengine/godot#5130]
[Proposal] Visible Collision Shapes debug in HTML5.
I needed to see collision shapes in my game after export (not working) but don't have this feature.

**Comment by akien-mga** [comment]
What would be the added value of debugging this after export instead of doing it directly in the editor? If in this specific case the issue is that collisions behave weirdly in HTML5, it's a platform bug that needs to be fixed, and though making the collision shapes visible might help show visually that something is broken, it won't solve the bug.

**Comment by leotada** [comment]
The collision shape (Area2D with collisionShape) follow the mouse position on _fixed_process() and check collisions on mouse click, and works in the editor, but in HTML5 export don't, and is difficult to say where is the bug. But probably is in the exporter. Any hint?

**Comment by bojidar-bg** [comment]
You might use [`get_tree().set_debug_collisions_hint(true)`](http://docs.godotengine.org/en/latest/classes/class_scenetree.html#class-scenetree-set-debug-collisions-hint), no?

**Comment by Calinou** [comment]
Is displaying collision shapes in exported projects supported on platforms other than HTML5? If not, this issue should be closed.

**Comment by Calinou** [comment]
Closing due to lack of response.
