### ISSUE TITLE
Auto linked portal prefer external room

### ISSUE THREAD

**Issue by timothyqiu** [godotengine/godot#51389]
### Godot version

3.4.beta3

### System information

macOS 11.5.1

### Issue description

Auto link works fine if not inside an internal room.

When I put an unlinked portal in an internal room, it seems always prefer the external room.

### Steps to reproduce

Run the MRP, you'll see an empty hole in the wall that leads to the outside. But it's supposed to lead to another room.

The portal is named `AutolinkPortal` if you want to search for it in the Scene dock. (RoomList > Building > EntranceHall > AutolinkPortal)

### Minimal reproduction project

[Autolink.zip](https://github.com/godotengine/godot/files/6950736/Autolink.zip)

**Comment by lawnjelly** [comment]
Ah I didn't twig that this was with an internal room. This looks like I wrote the autolinking before internal rooms were added to the system, and it needs to account for the internal rooms, and preferentially choose the highest priority room instead of the first one it finds. :+1: Should be no problem. :grin:

**Comment by lawnjelly** [comment]
Fixed in 23 mins, you can't complain! :grin:

**Comment by akien-mga** [comment]
Fixed by #51392.
