### ISSUE TITLE
GDScript: get_properties_list() returns unexpected results

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5146]
At some point in my game, I need to iterate the members of a class in order to serialize it (althought other purposes exist), but I didn't found any way to do it, but to use dictionnaries instead.

There is a `get_method_list()` function, which return alls methods, fine. But there is also a `get_property_list()` function, which returns unexpected results that have nothing to do with actual members (see this QA thread: http://www.godotengine.org/qa/5097/how-to-iterate-the-members-of-a-class).

Can we have support for members iteration in GDScript?

Note: there is an open issue about reflection (#4372), but the discussion was off-topic so I wasn't sure about posting in it.

**Comment by vnen** [comment]
I'm not sure what's the intended purpose of `get_property_list()`. Currently, you can add a virtual function `_get_property_list()` to the script and return an array of properties, though it seems this is *added* to the property list, so it *doesn't override* it.

This is a kind of reflection, though not so harmful and slow (I think) as general reflection. Since `get_method_list()` exists and works, then `get_property_list()` should work too.

Note that there's `inst2dict()` and `dict2inst()` functions to deal specifically with serialization.

**Comment by Zylann** [comment]
For me, I don't get what `get_property_list()` is returning. It expected the fields in my class.
I wouldn't override _get_property_list() because it makes me rewrite them all, I don't want that (I try to be as DRY as possible).

At the moment I do this:
```gdscript
class LevelAchievements:
	var best_time = -1.0
	var collected_orbs = 0
	var death_count = -1
	var completed_count = 0
	
	func is_valid():
		return completed_count > 0
	
	func to_dict():
		return {
			"best_time": best_time,
			"collected_orbs": collected_orbs,
			"death_count": death_count,
			"completed_count": completed_count
		}
		
	func from_dict(d):
		best_time = d["best_time"]
		collected_orbs = d["collected_orbs"]
		death_count = d["death_count"]
		completed_count = d["completed_count"]
```
Then I convert the dict to whatever format I want for saving. inst2dict could do the trick nicely indeed. But it returns data I don't want:
```
[best_time]: -1
[collected_orbs]: 0
[completed_count]: 0
[@path]: res://scripts/player.gd
[death_count]: -1
[@subpath]: LevelAchievements
```

**Comment by reduz** [comment]
okay, this makes sense. will change get_property_list so it also shows script variables. you will be able to identify an item variable by doing

if (pinfo.usage&PROPERTY_USAGE_SCRIPT_VARIABLE)
