### ISSUE TITLE
Can't instantiate custom class in builtin script (Invalid call. Nonexistent function 'new' in base 'GDScript')

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#51538]
### Godot version

4.0dev.calinou.18bd0fee5

### System information

Window 10

### Issue description

Can't new custom class after @onready

*Bugsquad edit:* Tested as a regression, bad in 18bd0fee5 and good in 2df1765fc.

### Steps to reproduce

1. Create a GDScript "Test.gd" and write code like this:
```
class_name Test

func _init():
	prints("Test")

```
2. Create a scene and attack code like this:
```
extends Control

@onready var a = Test.new()

```
3. Run the scene and will report error: Invalid call. Noneexistent function 'new' in base 'GDScript'
![test](https://user-images.githubusercontent.com/35988767/129130366-e7ffc3ba-61f4-4d1e-82dd-efd8bd2b8600.PNG)

### Minimal reproduction project

[OnreadyNewTest.zip](https://github.com/godotengine/godot/files/6972465/OnreadyNewTest.zip)

Note: 4.0dev.calinou.2df1765fc and before version hasn't this issue

**Comment by akien-mga** [comment]
Bisected, it seems to be caused by #51453, CC @Blackiris.

It's related to using a builtin script instead of a dedicated script file, which throws this error (in any version, both before and after the regression):
```
ERROR: Condition "err" is true. Returning: err
   at: load_source_code (modules/gdscript/gdscript.cpp:990)
```

Since the merge of the DAP, it also throws:
```
ERROR: Condition "path.is_empty()" is true.
   at: compute_checksums (editor/debugger/debug_adapter/debug_adapter_types.h:66)
```
(Unrelated to this bug, but another problem with builtin scripts.)

And finally this is the error which seems related to the GDScript error:
```
ERROR: Resource file not found: res://.
   at: _load (core/io/resource_loader.cpp:214)
```

**Comment by Blackiris** [comment]
Strange, because of my change, the code will read the `else` block:
```
} else {
	result.kind = GDScriptDataType::GDSCRIPT;
	result.script_type_ref = GDScriptCache::get_shallow_script(p_datatype.script_path, main_script->path);
	result.script_type = result.script_type_ref.ptr();
	result.native_type = p_datatype.native_type;
}
```
This is normal because the other block indicates that Test is a local class of the current script (which it isn't).
But because of `get_shallow_script`, the script is not compiled (thus, valid = false, and `new` method failed).

Loading the script should be done in ResourceLoader::load. When I revert my "fix", the following `if` never get true, and the script compilation happens just after the block:

https://github.com/godotengine/godot/blob/56ac302dc4bbb887c45157b3e377313378e376c1/core/io/resource_loader.cpp#L539-L555
Still trying to understand the code...

**Comment by Blackiris** [comment]
In my previous post, as a test, if I replaced `if (res.is_valid())` to `if (false)`, the compilation get triggered, and the bug disappears.

No chance for me, here, res.is_valid() = true, because it is a reference to a invalid GDScript (but non null):
https://github.com/godotengine/godot/blob/56ac302dc4bbb887c45157b3e377313378e376c1/core/object/ref_counted.h#L212
Indeed, the referenced GDScript has `valid=false`.

**Comment by Blackiris** [comment]
Well, replacing `GDScriptCache::get_shallow_script` to `GDScriptCache::get_full_script` does fix the bug, as `get_full_script` also reload the script.
I am afraid I don't have the level to understand the logic behind it... get_shallow_script allows to compile the script later on, but I don't have any idea when the 'later' on is appropriate.
**Maybe it is better to just revert my commit for the moment?**

---

Btw, maybe a code smell here, `get_full_script` calls `get_shallow_script`. and it looks like `load_source_code` is called twice:

Inside get_shallow_script:
https://github.com/godotengine/godot/blob/a98589a4497bdff15c66a98b6d07241addddae2c/modules/gdscript/gdscript_cache.cpp#L186

Inside get_full_script:
https://github.com/godotengine/godot/blob/a98589a4497bdff15c66a98b6d07241addddae2c/modules/gdscript/gdscript_cache.cpp#L203-L205

**Comment by Blackiris** [comment]
The more I think about it, the more I don't think it's a good idea to revert the commit. The commit fixed a bug that was hiding a second bug (this one).

To sum up, here what's happening:

1. `get_shallow_script` is called instead, which load the test.gd script WITHOUT compiling it. This uncompiled resource is also stored in the ResourceCache by this method.
2. When the compiler wants to check if `new` exists, it loads from the ResourceCache the previous the uncompiled script. (if the uncompiled one weren't found in the cache, it would have instead compiled it completely, and the bug won't happen)
3. Because the script is uncompiled, the compiler said `new` is not a supported method.

Here are some solutions ideas:

1. Use `get_full_script` instead of `get_shallow_script` ==> Easiest solution but I am afraid it could have some performance impact. There should be a reason why `get_shallow_script` was preferred.
2. Change the resource loader validity checks: do not only check if the reference to the resource is valid, but also check that the contained GDScript resource (which is a subtype of Resource) is also valid ==> hard because GDScript's parent type, Resource, does not have a `is_valid` method, even if GDScript has. And Resource loader only deals with Resource class....
3.  After resource loader sends the uncompiled script to the GDScript compiler, maybe we could check if it is valid and if not, force recompile it ==> Also difficult because resource loader sends back a Ref<Resource> (=RES), not sure it could be casted to a GDScript or not...

Except the first solution which gets the job done, I am stuck...

**Comment by CsloudX** [comment]
^V^, I found a way bypass the issue:
1. Create a AutoLoad script, and use custom class in the AutoLoad script
2. Then I can instanciate custom class in builtin script any time.

**Comment by h0lley** [comment]
Mentioning `Invalid call. Nonexistent function 'new' in base 'GDScript'.` error message to prevent further duplicate reports.

for people looking for a workaround: you can still use `load` or `preload` to instantiate the class, e.g. `preload("res://myclass.gd").new()`

**Comment by KoBeWi** [comment]
Found an easier workaround (that might also help fixing the issue):
```GDScript
MyClass
MyClass.new()
```
You need to "use" the class before instantiating it.

**Comment by Jimmio92** [comment]
@Blackiris 
> 1. Use `get_full_script` instead of `get_shallow_script` ==> Easiest solution but I am afraid it could have some performance impact. There should be a reason why `get_shallow_script` was preferred.

I think this is necessary for it to be type-and-number-of-arguments-correct. I don't see how it could be much of a slowdown when it literally has to have knowledge about the other script's `_init` to be fully aware.

Either way, this bug has been around for almost a year and needs solved; your change making it into alpha12 would be lovely assuming nothing else breaks as a result. We're still in alpha here, so speed can come later, imo.

@KoBeWi
The way you suggested to "use the script" before calling new isn't possible due to GDScript's parser complaining about "Unexpected "Identifier" in class body." This may have changed since you posted the comment, so I just wanted to mention it in case anyone else is having troubles.

For now the only way that seems to work is to preload the script and call new on it `preload("res://the_script.gd").new()` or make an autoload that creates the script for you in a static function as autoloads don't seem to have this issue.

**Comment by KoBeWi** [comment]
My workaround still works but a bit differently. You need to "use" your class in _ready().

**Comment by pineapplemachine** [comment]
I have encountered this same problem in `v4.3.stable.mono.official [77dcf97d8]`. Since this was closed as completed, presumably it was fixed at some point and has since regressed?

I was at least able to work around the issue using a static function that calls `new` within the class itself. (Thank you @KoBeWi https://github.com/godotengine/godot/issues/51538#issuecomment-1140529421)

**Comment by KoBeWi** [comment]
Do you have some minimal reproduction project? I have not encountered this issue anymore after the fix, so it might have different cause. Also check if it's fixed in 4.4 snapshot.

**Comment by hakuhan** [comment]
Hi! @KoBeWi I got this issue in 4.3. And I also use “forward declaration” way to fix this issue!
I created few **EditorProperty** in editor and use "tool" mode in these scripts:
![图片](https://github.com/user-attachments/assets/23ee469f-6f0f-4481-bd83-5ab6e03b8c3f)
![图片](https://github.com/user-attachments/assets/94d995ce-e1fc-4a56-85b9-d47f09d3ef19)
![图片](https://github.com/user-attachments/assets/7feed9a5-224a-4779-91d6-965377d9ac27)
![图片](https://github.com/user-attachments/assets/72d3845e-19da-4a36-9b6d-1300489ba4b2)
I checked all scripts in this inspector plugin. All of these scripts have "@tool" on the top.

This is a fixed verion of plugin zip on my project (If you want to test it. Please remove class_name of button and try with folloing image)
[generic_inspector.zip](https://github.com/user-attachments/files/17410068/generic_inspector.zip)
![图片](https://github.com/user-attachments/assets/fc0156af-6782-4290-a903-80d0d3742315)

**Comment by KoBeWi** [comment]
Can you send a complete project? A non-fixed one? When is the error supposed to appear?

**Comment by hakuhan** [comment]
> Can you send a complete project? A non-fixed one? When is the error supposed to appear?

Hi!  @KoBeWi  Sorry for late reply! I was a little busy at last few days.

When I create a new project with this addon. This error disappears in new project. I'm tring to reproduce it. If I get it. I will upload new project.

**Comment by solodeveloping** [comment]
I've encountered the issue as a "non-bug"

You'll see the error if you have an error in the class_name script.

You won't see any errors in the script instantiating the class_name, which might be an issue.

You don't see any error if you do it using Node3D.new(), node.set_script(MyClassName) either.

There is not even a warning, maybe because it was correct at some point 🤷‍♂️
