### ISSUE TITLE
Keystore problem

### ISSUE THREAD

**Issue by AbdulkarimAhmad** [godotengine/godot#51552]
### Godot version

3.3.2

### System information

Windows 10 

### Issue description

Hi there 
i was work on win 10 and make a game and i export it to android with a key and i saved all the data in a text . 
now i copy the project to mac os so i export to android from it 
i copy the key and every thing as its from windows 
and it keep that the password and the keystore password not the same 

### Steps to reproduce

 i have the project on win 10 and i export it and its work fine the key and the pass work fine 
but on mac i get error " password and the keystore password not the same "

**Comment by madmiraal** [comment]
You need to make the store password and the key password the same.

This is not a Godot specific issue. It affects all Android Studio projects since version 4.2 too: https://developer.android.com/studio/releases#4.2-known-issues
To enable compatibility with various browsers, it is a by design issue with the Java JDK11 keytool for PKCS12 key stores that will not be fixed: https://bugs.openjdk.java.net/browse/JDK-8008292
