### ISSUE TITLE
Freezing and black screen when start godot inside my project root dir

### ISSUE THREAD

**Issue by sprhawk** [godotengine/godot#51633]
### Godot version

4.0dev (e5411a815c, d8a8d32f2ef617944c)

### System information

Debian 11 Linux, Vulkan, nVidia 3060 Laptop

### Issue description

start inside project root without specified project file, it shows black screen, no project manager nor current project
```
godot.linuxbsd.tools.64
```
If I passed project.godot, The UI will show up
```
godot.linuxbsd.tools.64 project.godot
```

### Steps to reproduce

Inside My Demo Project, execute
```
godot.linuxbsd.tools.64
```

### Minimal reproduction project

https://github.com/sprhawk/godot_crash_demo

**Comment by Calinou** [comment]
This is likely due to this incomplete line: https://github.com/sprhawk/godot_crash_demo/blob/master/Children/Player.gd#L24

I've seen reports about crashes and freezes in this situation.

**Comment by sprhawk** [comment]
> This is likely due to this incomplete line: https://github.com/sprhawk/godot_crash_demo/blob/master/Children/Player.gd#L24
> Fix it using an external script editor, and it should work again.
> 
> I've seen reports about crashes and freezes with the new GDScript rewrite in this situation.
> 
> Duplicate of #51620 (same cause).

No, I had already fixed it the error line then tested it and then report. and in my issue description, I said if I start with `godot.linuxbsd.tools.x64 project.godot`, it will show up the project scene.

**Comment by akien-mga** [comment]
This seems to be a misunderstanding.

Running the Godot binary in a project folder without arguments will *run* the project itself. So since this project has an invalid script, it fails loading the main scene.

Running with the `--editor`/`-e` argument, or a path to `project.godot`, will *edit* the project in the editor. The project isn't corrupted so it can be edited fine, but running it from the editor will also lead to the game stopping execution due to the error in the script (but since there's a debugger attach, it lets you actually debug it).

So it's behaving as intended.
