### ISSUE TITLE
Clicking "Online Docs" freezes the editor

### ISSUE THREAD

**Issue by Sosasees** [godotengine/godot#51691]
### Godot version

3.3.2.stable.official

### System information

Debian 10.10.0, amd64, Openbox Window Manager

### Issue description

When I click the "Online Docs" button,
the online documentation Does open in my default web browser,
but before that happens, the Godot Editor freezes so that I have to kill the process
and then Restart the editor to continue working.

The expected behavior was that the online documentation opened
Without the Godot Editor freezing.

### Steps to reproduce

1. Open a script in the internal script editor
2. Look on the toolbar above the script
3. Press the "Online Docs" button in the toolbar.
![online-docs-button](https://user-images.githubusercontent.com/66305550/129475190-d0dc158f-74d2-4467-9bcd-1a06c56cfa54.png)
4. Reproduced: The Editor freezes before the webpage opens

### Minimal reproduction project

The most minimal reproduction project is any Empty Godot Project.
This issue can be reproduced in Any Godot Project.

**Comment by anderlli0053** [comment]
It too occurs on Linux Mint 20.2 Cinnamon, kernel version 5.4.0-81-generic, CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx × 4, and those 2 GPUs:

NVIDIA Corporation GP107M [GeForce GTX 1050 3 GB Max-Q] / Advanced Micro Devices, Inc. [AMD/ATI] Picasso

**Comment by Calinou** [comment]
I can't reproduce this on Fedora 34 KDE. I get this warning message in the terminal when clicking the button, but the URL opens normally in the default browser:

```
kf.coreaddons: Trying to attach UI delegate: KIO::JobUiDelegate(0x55add646c6b0) to job KJob(0x55add647a5f0) but this delegate is already attached to a different job KIO::OpenUrlJob(0x55add64628e0)
```

**Comment by Ev1lbl0w** [comment]
Godot hangs because with https://github.com/godotengine/godot/pull/43053 it now blocks until the command has finished running.

With https://github.com/godotengine/godot/pull/44514, this can be reverted to the old behavior without the zombie process issue, thanks to this:
https://github.com/godotengine/godot/blob/61d681cfb9a89f5c32a6c85e8f1cf53360c6eddb/drivers/unix/os_unix.cpp#L331-L334

But with `create_process`, it can no longer check for the error code, which was introduced to prevent trying all other options when the requested file doesn't even exist:

https://github.com/godotengine/godot/blob/61d681cfb9a89f5c32a6c85e8f1cf53360c6eddb/platform/linuxbsd/os_linuxbsd.cpp#L196-L202

So, what would be the best way to solve this? Have two `shell_open`'s, one blocking and one async? Or maybe have `shell_open` detect the URL prefix, and work async when dealing with web links (`http://`), and blocking when dealing with local files (`file://`)?

**Comment by akien-mga** [comment]
CC @Faless

**Comment by akien-mga** [comment]
Is this no longer valid/reproducible?
