### ISSUE TITLE
Calling inner classes with reference

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#5171]
You can call methods when doing `get_node("*").do_something()` but trying `get_node("*").Class.new()` doesn't work. Ability to reference a class this way would be a pretty cool addition to the language, plus it fits in perfectly and you don't have to write extra methods for just getting them out of the script.

**Comment by neikeq** [comment]
I like the idea. I don't think this type of "reflection" would affect performance since that's kind of the way GDScript works already.

**Comment by eska014** [comment]
This works for me, do you have an example where this fails?

**Comment by Zylann** [comment]
Theoretically, you could do this instdead:
`preload("the/script.gd").Class.new()`
It makes sense to me that Class is not available from an instance because it's not a member of it.

**Comment by ArcFutahito** [comment]
@eska014 I've asked the question on QA http://godotengine.org/qa/5152/cant-call-inner-class-from-singleton
@Zylann Well, the thing is, I already have a script with inner class, so loading it twice is just not right.

**Comment by Zylann** [comment]
preload() won't load it twice, it's a compile-time feature that will just replace the call by the class (as for any resource). And if your singleton is not used for anything else, you could even remove it.

**Comment by ArcFutahito** [comment]
@Zylann Nifty. 
Still, I think it would be an improvement to get a class without this kerfuffle, especially because you can get methods this way already.

**Comment by eska014** [comment]
Made a demo project, is this not what you want?
[autoload_subclass.zip](https://github.com/godotengine/godot/files/310772/autoload_subclass.zip)

By the way. instead of `preload`, you can just call `get_script()` on the node to retrieve the class object. But as the demo shows, it shouldn't be necessary for what you're trying to do.

**Comment by Zylann** [comment]
You can get methods from the node because they work on instances.

On the other hand, static methods, consts and classes don't need an instance to be called. That's why we primarily use preload() directly rather than having a node.

After testing, it's true that you can get constants and call static methods from an instance. So yeah, it would be consistent to be able to access inner classes :)

**Comment by ArcFutahito** [comment]
Strange. This exact same thing didn't work in my project. What the hell.
I will close the issue now, sorry.
