### ISSUE TITLE
BakedLightmap atlas size not respected

### ISSUE THREAD

**Issue by grevius5** [godotengine/godot#51741]
### Godot version

3.4.beta.3 mono

### System information

Windows 10

### Issue description

BakedLightmap node is not respecting the atlas size as you can see: 
![BakedLightmapErrorDimensions](https://user-images.githubusercontent.com/16955149/129592879-8c859797-9025-417b-a7da-ac5232296a48.PNG)
Also i remenber in the older version there was an error message that tells you that the size of the uv's were too big, in thet version i haven't see that error anymore.

### Steps to reproduce

Bake a scene with 3d models imported with low lightmap texel size (for example 0.01) and light baking as "Gen Lightmaps". Then bake

**Comment by Calinou** [comment]
The Atlas Max Size likely defines the smaller dimension only. Alternatively, it means that individual *layers* are being clamped in size, not all layers as a whole.

**Comment by JFonS** [comment]
Yes, `Atlas Max Size` refers to the individual layers, which are then stacked on top of each other to create a single image.

Right now there isn't any way to limit the total height of the atlas, so if you want to keep images below 2048 in both dimensions you will need to disable atlassing.

We could implement multi-image atlases, so instead of a single image for all layers, multiple images are used, but I don't really have the time right now. If anyone is interested, I'll be happy to give guidance on what needs to be changed.

**Comment by Calinou** [comment]
> We could implement multi-image atlases, so instead of a single image for all layers, multiple images are used, but I don't really have the time right now. If anyone is interested, I'll be happy to give guidance on what needs to be changed.

For reference, support for multiple atlas in BakedLightmap is being tracked in https://github.com/godotengine/godot-proposals/issues/2147.

**Comment by KoxaKoxama** [comment]
> Yes, `Atlas Max Size` refers to the individual layers, which are then stacked on top of each other to create a single image.
> 
> Right now there isn't any way to limit the total height of the atlas, so if you want to keep images below 2048 in both dimensions you will need to disable atlassing.
> 
> We could implement multi-image atlases, so instead of a single image for all layers, multiple images are used, but I don't really have the time right now. If anyone is interested, I'll be happy to give guidance on what needs to be changed.

I don't understand why multi-image atlases is left behind in a backlog, this is so critically important  for proper lightmapping setup with performance in mind.
Any relatively large interior static scene will greatly benefit from baked lightmaps that nicely packed in pow2 textures with fixed size, not in one huge atlas and not in thousands small textures, this is just ridiculous.
And no GIProbe is not an option for interior scenes with small details due to the poor quality, noticeable light leakage and unnecessary performance impact.

What should be done to implement multi-image atlases? Instead of stacking on top of each other to create a single atlas we need to constrain each atlas to fixed width and height, and constantly check whether we fill one out completly? This just screams for an efficient UV packing algorithm...

**Comment by JFonS** [comment]
@KoxaKoxama There are many things that need our attention and we have to set priorities one way or another, we can't please everyone. Whether you think this is ridiculous or not doesn't really matter, so you can skip that part in future posts on Godot's issue tracker.

That said, I did look into this issue a while back, and I made some progress. The only thing preventing larger lightmaps is the fact that the `Image` resource has a maximum size. 

As a quick fix I tried saving a `TextureArray` resource directly, but it appears that the saving code for this resource type was never implemented, only the loader was. Implementing this saver would take quite some time and testing, and the solution would not be ideal anyway, so I left it there.

There are two options moving forward:
* Implement the saver for `TextureArray`. 
  This is my work-in-progress changes: [diff.txt](https://github.com/godotengine/godot/files/8004617/big_lm.txt) in case someone wants to continue working on it. But as I said, the solution is not ideal since images won't be compressed.

* Instead of saving a single image or a single texture array, add support for saving multiple images. 
  Since the CPU lightmapper already generates a list of images, saving them separately should be easy, but this needs some changes in `LightmapperCPU` in order to keep track of which meshes ended un in which image. It's not a complicated process, but it takes some time and some careful testing to make sure everything keeps working as expected. I can provide more specific details if anyone is interested.

**Comment by KoxaKoxama** [comment]
@JFonS  There is no need for an implementation of TextureArray saver. 
Support for saving multiple images/atlases from lightmapper is exactly what I was wondering about, currently there is two extreme options how baked lightmaps are stored, it's either thousands of small textures or one unreasonably huge texture, both of which is harmful for performance, especially a very big non power of two atlas. 

When texture atlas size is specified, lightmapper needs to keep texture size as pow2 and try to fill it with as much UV's as it can, and then create another texture and fill it with rest, repeat untill all mesh is done. A perfect middle ground.

**Comment by JFonS** [comment]
As I mentioned, the `TextrueArray` approach was an attempt to get a quick fix. As I also mentioned, saving multiple images is possible, but requires a bit more work. After taking another look, I see the lightmapper already keeps track of the correspondence between meshes and images, so it's just a matter of correctly saving and loading the images. I will give it a go one of these days, when I have some spare time.

Note: the master branch has an image size limit of `2^24` (16.7M) instead of `2^14` (16.3k), so for 4.0 this is much less relevant.

**Comment by akien-mga** [comment]
Fixed by #58102.

**Comment by gdlq** [comment]
> Fixed by #58102.

Not fixed at all. Same error as before **Failed determining lightmap size. Maximum lightmap size too small?**
