### ISSUE TITLE
When the text editor has focus, it doesn't trigger certain shortcuts correctly

### ISSUE THREAD

**Issue by mbasaglia** [godotengine/godot#51948]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Operating System: Kubuntu 21.04 
KDE Plasma Version: 5.21.4 
KDE Frameworks Version: 5.80.0 
Qt Version: 5.15.2 
Kernel Version: 5.11.0-31-generic 
OS Type: 64-bit 
Graphics Platform: X11 
Processors: 8 × AMD FX(tm)-8320 Eight-Core Processor 
Memory: 31.4 GiB of RAM 
Graphics Processor: AMD Radeon ™ RX 470 Graphics

### Issue description

I changed the shortcut for "Play" to "Meta+R".
It works fine but if the text editor is focused it enters the letter "r" and doesn't trigger the "Play".
Same happens if I use "Alt+R". If I keep the editor open but click on something else (eg: Filter scripts), the keyboard shortcut works fine.

### Steps to reproduce

* Open an project and edit a script
* Change the "Editor > Play" shortcut to "Meta+R"
* With the text editor focused, trigger "Meta+R"

Instead of running the project, it adds "r" to the text.

**Comment by EricEzaM** [comment]
Not reproducible in 4.0 (tested 89417ba).

This is an issue that was fixed in 4.0 but currently I don't think there are plans to backport to 3.X. https://github.com/godotengine/godot/pull/42109

See also: https://github.com/godotengine/godot/issues/50271 and https://github.com/godotengine/godot/issues/47873

**Comment by EricEzaM** [comment]
Please direct further discussion to #52861
