### ISSUE TITLE
Tree drag&drop line does not render correctly if an item has children

### ISSUE THREAD

**Issue by Beider** [godotengine/godot#52053]
### Godot version

3.3.2 stable mono win64

### System information

Windows 10

### Issue description

If you have a tree with items that have children and enable drag & drop with mode (DROP_MODE_INBETWEEN) then the drop hint line does not render correctly (see screenshot).

![dragdroptree](https://user-images.githubusercontent.com/35214615/130587413-a29214e4-9636-4d6b-bafc-62b0ab857a58.png)

As you can see the line renders correctly below the item that has no children (left side), however for the item with children it never renders below the item (right side).

That being said the position you get from "get_drop_section_at_position(position)" is correct and tells you that the item was dropped below the item even though the line is not rendered as such.

### Steps to reproduce

Enable drag & drop in a tree that has items with children and try to drag something below an item with a child. I included a simple project that shows the issue.

### Minimal reproduction project

[Dragndroptree.zip](https://github.com/godotengine/godot/files/7037854/Dragndroptree.zip)

**Comment by kleonc** [comment]
So I fixed the drawing ([commit on my fork](https://github.com/kleonc/godot/commit/2fb13ce812f5818bed513855ebc60dc410e1efde)) but it doesn't solve the real issue about the current `Tree`'s API:
|version|the look|get_item_at_position(mouse_pos)|get_drop_section_at_position(mouse_pos)|
|-|-|-|-|
|3.3.3.stable|![Godot_v3 3 3-stable_win64_2TdxmcUdNd](https://user-images.githubusercontent.com/9283098/130661399-1ecd6005-549f-4afc-9286-0e673f55a7fa.png)|TopLevel3|1 (Below)|
|[3.x with fix](https://github.com/kleonc/godot/tree/2fb13ce812f5818bed513855ebc60dc410e1efde)|![uZGenkD4vy](https://user-images.githubusercontent.com/9283098/130661425-9a67a693-6c7c-4f20-aea1-45d5f666a8be.png)|TopLevel3|1 (Below)|

As you can see the problem which remains before/after the fix is that the user can't obtain the drop destination according to what's being drawn as a drop destination. So currently the user would need to duplicate the same logic in his drag-drop code to match what's being highlighted by the `Tree`.

A possible solution might be adding a method like `get_drop_destination_for_position(position)` which would return a `Dictionary` with `item` and `section` keys which would work like this:
|version|the look|get_drop_destination_for_position(mouse_pos)|
|-|-|-|
|[3.x with fix](https://github.com/kleonc/godot/tree/2fb13ce812f5818bed513855ebc60dc410e1efde)|![uZGenkD4vy](https://user-images.githubusercontent.com/9283098/130661425-9a67a693-6c7c-4f20-aea1-45d5f666a8be.png)|{<br>"item": SeconLevel1,<br>"section": -1 (Above)<br>}|

**Comment by Beider** [comment]
While this is very much an improvement I still think there are additional things to consider here. If you look at the screenshots you made the line when you hoover "TopLevel3" which has children stops at the indentation of the children, while for "TopLevel2" with no children it goes all the way to the left.

So the question is where would the item end up when you drop over something with children? In my case I re-order items on the same level of the tree. As such perhaps the line when you drop on an item with children should actually be drawn below all the children and above the next item of the same level. That way if you want to drop it on that level of the tree it would indicate accurately where it would end up, however if you want to drop it as a child you would have to hoover the first child item.

So using your same drop location perhaps the line should be here instead,
![dragdroptree2](https://user-images.githubusercontent.com/35214615/130669967-3234ad68-c9e9-4815-a2a9-8d9ef2dad0b6.png)

With the solution provided above if we assume this is something like godot node tree, if the last item in the tree (item A) has children there is no way to indicate that you want to drop something on the same level as that item (item A) but after it. Since once you go past the last child (of item A) the line does not indicate that you are dropping on the parent level again.

I hope this made sense, I just think the only way to make sure any drop location works is to have it drop before/after the item on the same level of the tree (ignoring children).

**Comment by kleonc** [comment]
Yes, what you're saying makes sense, I get your point.

However, just checked how `Tree` currently behaves in the Scene dock in the editor and... it behaves exactly according to what's being drawn with my fix. When dragging at "below" section of an item with children:
![Godot_v3 3 3-stable_win64_xgYHve6lO2](https://user-images.githubusercontent.com/9283098/130695133-5fc44c20-f4ca-4840-be2f-d327f6b126e0.png)
although the line is being drawn above the hovered item, actual drop happens above the first child of the hovered item:
![gmh2Q88vs3](https://user-images.githubusercontent.com/9283098/130694942-dcc10221-8886-4b76-86ff-12dfed07e0a2.png)
In fact it's kinda reported in #46339, as clarified in [this comment](https://github.com/godotengine/godot/issues/46339#issuecomment-785431588). So maybe I'll just make a PR with my fix just as a quick-fix for the current state of the editor's Scene dock. :thinking: 

This will of course not solve the issue I've mentioned in my previous comment: in drag-drop code user needs to perform the same logic which is applied when drawing to make things match. This needs to be somehow solved, I'd say this needs a separate [proposal](https://github.com/godotengine/godot-proposals)/discussion for finding a good solution.

About your point: when I was writing a fix linked above, I didn't even think about doing it like you're suggesting, the way it behaves currenly in the editor's Scene dock / the way it's drawn in my fix seemed obvious. So my doubt about your suggestion is: will it be intuitive? On the other hand if the indicators will be drawn correctly then the feedback for the user should make it obvious how things work. Not sure about it.
And currently in the editor's Scene dock to add drop a Node at the end of some tree-level you can just drag Node at the parent of that level (hope it makes sense), for example:
|dropping|dropped|
|-|-|
|![Godot_v3 3 3-stable_win64_16u21EHs1g](https://user-images.githubusercontent.com/9283098/130698481-7d36d00c-55b8-4c22-984c-d3b4f0c7f3c2.png) | ![GdWlRHXFrR](https://user-images.githubusercontent.com/9283098/130698484-dc556202-534a-4aa7-9aeb-6d9287469612.png)|
|![Cc6czQZZnj](https://user-images.githubusercontent.com/9283098/130698486-ca95ba35-4b77-4def-9667-a56d9a016011.png) | ![2YCRF9PY3N](https://user-images.githubusercontent.com/9283098/130698487-54a64e90-ea10-4751-90eb-64c0d321dd45.png)|

**Comment by Beider** [comment]
Thank you for the suggestion about the proposal, I filed one with my thoughts on how this should work. Hopefully this will at least start some sort of discussion for this so a solution can be found (even if it is not the one I suggested).

https://github.com/godotengine/godot-proposals/issues/3201

**Comment by kleonc** [comment]
Fixed by #52095/#52096.
