### ISSUE TITLE
[3.x] Batch rename window size not updating correctly

### ISSUE THREAD

**Issue by LoipesMas** [godotengine/godot#52074]
### Godot version

3.4 5ce734c073

### System information

Linux

### Issue description

When in batch rename window preview text doesn't fit in the window, the window background doesn't scale properly. 
Moving the window updates it.

Same thing on 3.3.3, but on master it's fine (because it's a separate window there?).

![image](https://user-images.githubusercontent.com/46327403/130659419-b72a9b99-7313-47f3-ad2f-c652defe458d.png)

### Steps to reproduce

Open batch rename window.
Make so the preview text is so long that it doesn't fit.

**Comment by nsrCodes** [comment]
I was trying to fix this by making changes in `editor/rename_dialog.cpp`
But just turning on autowrap on the preview label was not enough as we also have to increase the height of the `VBoxContainer`, else, instead of overflowing from the right, it overflows from below. 
![Screenshot from 2021-09-14 22-39-34](https://user-images.githubusercontent.com/57226514/133303091-b799c990-874f-4b17-adaa-83dd1bc704fa.png)

Is there a way to do so? I was expecting to find some sort of update function to call inside the `_update_preview` function, but so far no luck.

> the height is adjusted when the advanced options are toggled, but that too gives weird results.

**Comment by nsrCodes** [comment]
We could also just clip off the overflow, but that would not show the complete preview to the user (*which I guess is not ideal?*)
![Screenshot from 2021-09-14 22-49-10](https://user-images.githubusercontent.com/57226514/133304145-a67c68bd-36a8-47b7-bc8f-cdd4d2c94971.png)

**Comment by Calinou** [comment]
> We could also just clip off the overflow, but that would not show the complete preview to the user (_which I guess is not ideal?_)
> ![Screenshot from 2021-09-14 22-49-10](https://user-images.githubusercontent.com/57226514/133304145-a67c68bd-36a8-47b7-bc8f-cdd4d2c94971.png)

In the `master` branch, there are various ellipsis overflow modes available in Label.
