### ISSUE TITLE
Bug with viewing ShortCut with InputEventAction

### ISSUE THREAD

**Issue by boruok** [godotengine/godot#52117]
### Godot version

v3.3.3.stable.official [b973f997f]

### System information

Windows 10, GTS450

### Issue description

Tried to add items to popup with following script.
```gdscript
extends PopupMenu


var table := {
	"add"    : {"key": "a", "tooltip": "add thing"},
	"delete" : {"key": "d", "tooltip": "delete thing"},
	"select" : {"key": "s", "tooltip": "select thing"},
}


func _ready():
	var id := 0
	for key in table:
		var i := InputEventAction.new()
		var s := ShortCut.new()
		i.action = key
		s.shortcut = i
		add_shortcut(s, id)
		set_item_text(id, key)
		set_item_tooltip(id, table[key].tooltip)
		id += 1

	visible = true
```
result is this, i believe this is string representation of event. Expected to see event action name, like:
- add a
- delete d
- select s

![Безымянный](https://user-images.githubusercontent.com/36783322/130908174-b7cebfb1-4a9e-41a1-85ca-a4b261c81c62.png)

### Steps to reproduce

1. attach script above to popupmenu
2. run scene

**Comment by LunaticInAHat** [comment]
This looks like the same issue as #28914. Unfortunately, although that issue was initially reported against 3.1, it got closed with a resolution in `master`, that doesn't appear to have been backported to 3.x.

**Comment by LunaticInAHat** [comment]
Also, after looking more closely at what the resolution of #28914 actually achieved, it does not seem to have reached the expected behavior that you are looking for (and which I agree would be a sensible thing to do for tooltips) -- it would instead create a string such as `(Input Action add was pressed)`, which is an improvement, but still not ideal for showing to players/end-users.
