### ISSUE TITLE
Tilemap can't be selected as node_a for GrooveJoint2D

### ISSUE THREAD

**Issue by mrkdji** [godotengine/godot#52158]
### Godot version

3.3.3.stable

### System information

Windows 10

### Issue description

Tilemaps are not available for selection when assigning GrooveJoint2D's node_a

### Steps to reproduce

Add a Tilemap and a GrooveJoint2D in a scene and click on the Node A property of the GrooveJoint2D

**Comment by KoBeWi** [comment]
Why would you need GrooveJoint2D for doors though? Unless you need physics, sliding can be done with AnimationPlayer or just via script.

**Comment by mrkdji** [comment]
@KoBeWi those "sliding doors" can also be used to fling boxes or other game objects, that's why I opted for RigidBody2D + GrooveJoint2D. 
Anyway I found a workaround, which on hindsight was pretty straightforward, by setting both the tilemap and the sliding door's mask to 0 and by attaching a dummy static body to each GrooveJoint2D.

**Comment by pouleyKetchoupp** [comment]
I'm closing this issue since there's a simple workaround.

For info:
I'm planning to make a change for Joint2D in 4.0 for empty node_a to be handled like a fixed point in space (not attached to a particular body) as it's already the case in 3D.
That will allow cases like this one to work without the need for a dummy static body, but it can't be easily backported to 3.x because it can break compatibility in some cases (currently the joint becomes inactive when node_a is empty).
