### ISSUE TITLE
[GDScript 2.0] inconsistent `type casting` expression handling

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#52224]
### Godot version

v4.0.dev.calinou [4d08a737f]

### System information

Windows 10

### Issue description

When it comes to `subscription` (`x[index]`) and `attribute reference` (`x.attribute`) expressions the `type casting` (`as`) should either always be allowed in place of `x` or always be disallowed.

In practice, however, the situation goes like this (`Main.tscn`):
```
extends Node3D

func foo():
	print(self as Node . name) # Main:[Node3D:29309797536]
	#print(self as Node . name . size()) # Cannot call on an expression. Use ".call" if it's a Callable.
	print((self as Node).name) # Main
	#print([1,2,3] as Array [0]) # Expected type for collection after "["
	print(([1,2,3] as Array)[0]) # 1
```

In case of `self as Node . name` the expression is parsed, but the outcome is as if it was `self as Node`.
When it comes to `[1,2,3] as Array [0]`, the expression raises parse error.

To me, it should be decided if type casting is allowed in such circumstances and:

- if yes, the parser should be fixed
- in not, the `self as Node . name` expression should raise parse error as well.

### Steps to reproduce

compile / run

**Comment by williamd67** [comment]
I think this is not related to the fact that `as` is allowed but about the priority of operators in this case `.`, `as`, and `[]`. Reading your examples I expect that `.` and `[]` has higher priority as `as` which means that your examples will be interpreted as:
* (self as (Node.name)) where Node.name resolves into String, which means it results in (self as String) what is also the result
* (self as (Node.name.size()) which results in an error as size cannot be called (name is not instantiated in this case) which is also the result
* ((self as Node).name) the priority is forced by the brackets and the statement resolves normally
* ([1, 2, 3] as (Array [0]) where Array [0] cannot be resolved resulting in an error
* (([1, 2, 3] as Array)[0]) the priority is forced by the brackets and the statement resolves normally

So far it seems proper behavior, I do not know if this priority of the operators is documented, if not that could be an improvement.

**Comment by Scony** [comment]
I don't think your reasoning right.

To me, the `as` operator has `TYPE` terminal as a right operand and thus in corner case situations like:
```
self as Node . name
```
`as` operator has higher priority then e.g. `.`.

For example `false as bool or true` results in `true` which means it's executed as `(false as bool) or true` - not as `false as (bool or true)` as you'd suggest.

**Comment by williamd67** [comment]
Interesting as according this [page (GDScript basics)](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html) `as` has almost the lowest priority. So I expect another rule kicks in, that correctly determines order by `false as bool or true` while this rule does not resolve `self as Node . name`. We need to determine the reasoning behind that. Still as the operator priority is well defined I think the code `self as Node . name` is at least ambiguous.

**Comment by Scony** [comment]
As I said, to me the `as` operator has `TYPE` terminal as a right operand and hence it cannot have any complex expression on the right - if it does, then (assuming grammar allows that [it does]) it's being parsed with higher priority thus allowing constructs like `false as bool or true`, `1 as int + 1`, `1 as int * 1` etc. - that's the rule that kicks in.
The only question that remains is, should subscription and attribute reference behave just like other operators above. Or should it not allow toplevel `as` as the left operand.

**Comment by vnen** [comment]
So, `self as Node . name` will be interpreted as `self as (Node . name)` and that is correct, because this pattern can be a type in some cases. Consider this code: 

```gdscript
class_name MyClass

class MyInnerClass:
    func foo():
        pass
```

In this situation, `MyClass.MyInnerClass` (from another script) is a valid type, thus `expr as MyClass.MyInnerClass` should be interpreted as `expr as (MyClass.MyInnerClass)` by default.

Right now it does allow arbitrary expressions to tackle this case, mostly for convenience of parsing code. We could consider parsing it specifically as a type, which would consume an arbitrary chain of `IDENTIFIER (DOT IDENTIFIER)*` but that would still entail self as Node . name` to be parsed as `self as (Node . name)`, but allow some other cases.

The thing is that given the fluidity of types in GDScript, class types are pretty much first class objects, so some not obvious constructs could technically be valid, like this:

```gdscript
class_name MyClass

var VarType = Node

func foo(arg):
    print((arg as VarType).name)
```

If we want this be a valid usage, then allowing arbitrary expressions to be types is needed, and the precedence of `as` is in a sensible spot IMO.

On another note, I would argue that `[1,2,3] as Array [0]` is not the most readable construct and requiring parenthesis for this case (and some other cases too) isn't really bad.

The only bug I see is `self as Node . name` actually doing something while it should fail since `Node.name` isn't a valid type.

**Comment by Scony** [comment]
Ok, if we reason about the type in terms of `IDENTIFIER (DOT IDENTIFIER)*` then it all makes sense. Then the attribute reference cannot have `as` expression as the left operand as it would be ambiguous.
Also, I agree that `[]` and even `()` should (for the sake of simplicity) not allow `as` expression as left operand as well (to force parenthesis).

So I conclude the only bug here is `self as Node . name` just like @vnen  mentioned.

**Comment by williamd67** [comment]
Clear, I was on the wrong path. Thanks for the explanation.

**Comment by vnen** [comment]
This has already been solved.
