### ISSUE TITLE
Godot doesn't read FBX exported from Blender correctly

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#52396]
### Godot version

3.3.stable

### System information

Linux, GLES3

### Issue description

Godot has some problems with FBX files.

### Steps to reproduce

Please have a look at the Quad Bike model (https://www.dropbox.com/s/63ismbltoa496aq/PolygonQuadBike.zip?dl=1) from here: https://syntystore.com/pages/free-assets
Importing into Godot works good, but when you import it into Blender and then export it again as FBX, the Quad Bike payloads are not correctly transformed.

### Minimal reproduction project

See above.

**Comment by 2439905184** [comment]
Because autodesk's fbx is not open source and free.So godot as a open source software can't use it's sdk.
Engine developers use Reverse engineering technology to Implement the import FBX function ，so the function may not be perfect.
Just like linux use  Reverse engineering technolog to Implement the import NVIDIA driver function。so it may not be perfect and have some problems and bugs

**Comment by AgentSmith0** [comment]
I know that, but other open source projects are also able to import FBX files correctly. Beside that, Blender is open source and it's FBX exporter too, so it should be possible to fix this problem somehow.

**Comment by akien-mga** [comment]
That's expected currently, see #44402.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
