### ISSUE TITLE
Default editor layout

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5242]
The current default layout in 2.1-dev is:
![spectacle p15397](https://cloud.githubusercontent.com/assets/4701338/16107604/a6a14154-339d-11e6-88e6-2189101d26d1.png)

It has the advantage of exhibiting the cool new feature of the Filesystem dock, but at the same time I'm not sure it's the most meaningful when starting a project. I preferred to have the Scene dock on the top left, as it's the most important one, and to have the inspector on the right.

My own simple layout is:
![spectacle z15397](https://cloud.githubusercontent.com/assets/4701338/16107540/58618940-339d-11e6-96d6-a46a03343d3d.png)
I think it would make a better default (it's quite similar to 2.0).

As an alternative, I'd propose also this one, with all docks directly visible, thus making sure new users don't miss the new Node dock:
![spectacle r15397](https://cloud.githubusercontent.com/assets/4701338/16107576/7a17da30-339d-11e6-8920-c35d680eb0cd.png)

**Comment by bojidar-bg** [comment]
I like the first one, but I also disagree about the Node tab, since it is not used as often as the others (unless you really want to do it, in which case you would move it around).

**Comment by neikeq** [comment]
I am using the first one. I prefer the Inspector to have good vertical space.

**Comment by akien-mga** [comment]
I guess you both meant "the first one" I proposed, and not the first screenshot (current default one)?

**Comment by neikeq** [comment]
The first one you proposed.

**Comment by nunodonato** [comment]
I also prefer the scene tree on the top left (maybe just habit?)
I dont use the node dock so much so I reduce the size so that the inspector is taller.
![layout](https://cloud.githubusercontent.com/assets/1642015/16110407/7eba4336-33a5-11e6-9152-f7d83a4daca1.png)

**Comment by SuperUserNameMan** [comment]
As 2.0 user who never tried to compile current head, all these new layout make me feel lost.
What is this new "Node" tab ? 
Where are gone all the Scene tab buttons ? 
![scene_tab_ui](https://cloud.githubusercontent.com/assets/9801802/16114587/4ce6d302-33c2-11e6-9c8c-aac3616b4b24.png)

**Comment by akien-mga** [comment]
> What is this new "Node" tab ? 

As a 2.0 user, I think it's relatively easy to understand by looking at the screenshot. It lets you manage signals (first tab, highlighted) and groups for the selected node. It was previously done via popup windows.

> Where are gone all the Scene tab buttons ?

Contextual menus and drag and drop.

**Comment by SuperUserNameMan** [comment]
Hmm, okay. So the content of the "Node" tab changes each time we select a node into the Scene tab, like the Inspector does.

On small screens (laptop 1366x768 for instance), I think it is better to have a large Inspector tab which reduce the needs for scrolling.
Seeing the content of "Node" tab all the time is less important. So having it hidden behind the Inspector is okay for me.

Therefore, for small screens, the second layout you posted (your own simple layout version) looks more adapted.

**Comment by SuperUserNameMan** [comment]
also, maybe, instead of calling this new tab "Node", maybe it could be called "Signals".
I think it would have more sense.

As for the "Group" button into the current "node tab" (never used groups so far so i don't really know how it work and what they are useful for), maybe it could become a tab of its own.

**Comment by SuperUserNameMan** [comment]
On a 1366x768, it would gives sometinh like this :

![layou_proposal_2 1](https://cloud.githubusercontent.com/assets/9801802/16115573/2ab5afaa-33c8-11e6-9b25-2852070f81bf.png)

**Comment by djrm** [comment]
I guess that moving the scene dock is kinda bad idea, when i first noticed the change i felt lost, and i found myself trying to do node operations in the filesystem dock, now i think im used to both layouts, but maybe other users will feel lost at first.

**Comment by reduz** [comment]
The new default layout was changed because it's just more friendly to new
users, it has the following advantages:

1) It puts more emphasis in the FS dock, and how resources can be managed
from it
2) It groups property editor and scene tree together, on the same side
which makes it more obvious that they are connected
3) The Node dock is hidden but you can see a tab all the time, to make it
clear that it exists. Current options in the dropdown were not commonly
accessed

Of course, once you get used to it, it's just much easier to shrink the FS
dock and move the scene tree to the left, but I think it's better to have a
default that is more welcoming instead of one that makes you more
productive.

**Comment by djrm** [comment]
I agree, and i actually prefer the new layout, have to move the mouse less when doing node operations (like selecting node and modifying its properties)

**Comment by TheoXD** [comment]
Probably a better idea to keep scene tree on the left side next to inspector, since most useful UI elements are clustered on the left side. I barely use FileSystem, just keeping signals tab open but minimized to it's minimum, while the left panel is slightly larger.

**Comment by akien-mga** [comment]
I'm not sure having the Filesystem dock on the left in full height is more user-friendly. It would be nice to have feedback from new users.

When I started learning how to use Godot, I cared mostly about the Scene dock, because I opened demos and wanted to see how they are done. I never touched the Filesystem at that time because I did not have to add anything to the scene tree, only to understand how the various scenes are setup.

Now that I know Godot, I still almost never use the Filesystem dock. I do everything with quick open scene/script, it's quite rare that I need to drag and drop stuff in the viewport or scene tree, even though I acknowledge that those are nice features.

**Comment by djrm** [comment]
Please consider this for the poll, this could make things easier for new users that expect a D&D workflow

![screenshot from 2016-06-16 12-48-52](https://cloud.githubusercontent.com/assets/1103897/16127575/ade592c4-33c2-11e6-8922-7881867fe9ee.png)

**Comment by freemanfromgodotengine** [comment]
@Akien to say the truth, it's not that big of a difference, but I like better "My own simple layout" because I prefer to see as much inspector as possible most of the time. 

In the subject  of layout I just think, that the most important is to have a layout settings and possibility to create our own default layout for Godot so we can use whatever wee need.

**Comment by vnen** [comment]
@freemanfromgodotengine you can save different layouts already in the settings menu.

**Comment by paper-pauper** [comment]
I personally agree with @djrm. Default layouts are mostly for new users (since everybody else can already change them), and since this layout minimizes mouse movements and divides attention between two (and not three) areas of interest, it makes the most sense from a presentation point of view, IMHO.

**Comment by bojidar-bg** [comment]
@drjm I would rather prefer if the filesystem tab is half-column not full-column though

**Comment by djrm** [comment]
@bojidar-bg maybe swapping Filesystem for Inspector + Node, but then the new FS capabilities are hidden from new users

**Comment by akien-mga** [comment]
BTW, the current hardcoded layout is not the same as the one you get when loading "Default layout", so this needs fixed too :)

**Comment by djrm** [comment]
is the default editor layout going to be changed for 2.1?

**Comment by DenisComtesse** [comment]
> BTW, the current hardcoded layout is not the same as the one you get when loading "Default layout", so this needs fixed too :)

This is still the case in 2.1 stable.

**Comment by eon-s** [comment]
I was about to open an issue about this...

I've noticed that the filesystem tab confuses new users, they see the big important tab and small scene and cluttered tiny inspector (the buttons to move tabs are not easy to guess).

I'm for this style to give a good place for new users to test the most important things of Godot, scenes and nodes:

![godot-gui-overlay2-scaled](https://cloud.githubusercontent.com/assets/10215987/19701672/c7932520-9ad2-11e6-8ea3-308e3697a363.png)

Another good option is present all the 4 tabs in each corner so the new users don't miss stuff like signals and groups on the first look, but not one single tab more important than the other (especially one not that important as filesystem).

**Comment by vnen** [comment]
I agree that featuring the FileSystem tab is not really the best idea, since the Scene is more important. But it must be shown in the default layout, preferably next to the Inspector or the Scene dock. You can drag & drop files from the dock to fill properties in the Inspector (like the texture of a sprite) and also instance a scene by dropping in the Scene tree. Because of all that it needs to be shown by default.

**Comment by eon-s** [comment]
@vnen right, the thing is what new users try is to drag something to what is next to it, the Godot icon to the editor to get a sprite instanced xD. And drag and drop scenes is an advanced scenario for a very specific workflow, not for a "first look".

Once users learn the basics they rearrange everything but for first impresion and use, mmm...

**Comment by reduz** [comment]
I will close this, with folding on by default it makes less sense to make the property editor bigger. Also think the default layout has proven to work pretty well, with little difficulty for users to change it

**Comment by akien-mga** [comment]
Still not happy with the default layout, but I rest my case :P
Eventually I might implement some alternative default layouts using the current layout templates, and add an editor settings to pick the default one for new projects. That should satisfy all use cases.
