### ISSUE TITLE
Vulkan: Environment `background_mode` set to Canvas causes 2D viewport, tooltips, context menus, and popups to be blank (DisplayServer regression)

### ISSUE THREAD

**Issue by axblount** [godotengine/godot#52467]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.0.dev.calinou (29bdd000f)

### System information

Windows 10, Vulkan, RX 580 (Driver Version 20.45.35.03-210217a-364232E-RadeonSoftwareAdrenalin2020)

### Issue description

When the WorldEnvironment's background_type is set to canvas (BG_CANVAS) all tooltips, context menus, and pop up windows appear as blank grey squares. They still work if you know where to click.

I'm using the latest build from https://hugo.pro/projects/godot-builds/

![image](https://user-images.githubusercontent.com/2730141/132380038-f1a571e3-e705-47da-8de0-4b59709b4049.png)

### Steps to reproduce

1. Create a 3D scene.
2. Add a WorldEnvironment child.
3. Add a new Environment.
4. Change the environment's background type to "Canvas"

Now hover over exported properties, right click nodes, open anything on the menu bar.

### Minimal reproduction project

[GodotTest.zip](https://github.com/godotengine/godot/files/7123034/GodotTest.zip)

*Bugsquad edit (keywords for easier searching): background mode, background type, bg, canvas, dropdown*

**Comment by nonunknown** [comment]
I can confirm this issue! in 2D its even worse, because everything disappear in the scene:

![canvas](https://user-images.githubusercontent.com/58845030/134002499-cf223717-d84e-47b6-9b35-8e0d351c80fc.gif)

**Comment by jsmnbom** [comment]
Note that setting the Canvas Max Layer to a negative value makes everything show up again, but none of the environement properties seem to actually apply in that case.

This effectively means it's impossible to use the wordenvironment (and therefore glow and such) with 2D in current master as far as I can tell?

**Comment by jsmnbom** [comment]
Okay so I (a complete C++ novice) spent some time trying to debug this today, and I think I've found part of the cause. (note that i might also be completely wrong so take this with a grain of salt).

When WorldEnvironment's background_type is set to canvas (BG_CANVAS) then the method [render_empty_scene](https://github.com/godotengine/godot/blob/48ed0400bc2313b9652d7f6cfd6119d784adc956/servers/rendering/renderer_scene_cull.cpp#L3256) gets called to (as far as i can tell) render a transparent 3d scene on top of the canvas. This method seems to be broken though, since it does not pass the environment that it finds on to scene_render->render_scene.
Proposed fix:
```diff
- scene_render->render_scene(p_render_buffers, &camera_data, PagedArray<RendererSceneRender::GeometryInstance *>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), RID(), RID(), p_shadow_atlas, RID(), scenario->reflection_atlas, RID(), 0, 0, nullptr, 0, nullptr, 0, nullptr);
+ scene_render->render_scene(p_render_buffers, &camera_data, PagedArray<RendererSceneRender::GeometryInstance *>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), PagedArray<RID>(), environment, RID(), p_shadow_atlas, RID(), scenario->reflection_atlas, RID(), 0, 0, nullptr, 0, nullptr, 0, nullptr);
```

This turns out to not be enough to fix the issue completely, unfortunately. It seems that the tonemapper effect (desponsible for glow, tonemapping etc.) makes the entire viewport black (NOT the clear color, but completely black). I've spent a ton of time (compilation takes around 5min on my potato machine) and other than narrowing it down to the tonemapper, I cannot figure out what's going wrong :(

Probably useless but screenshot after the "fix":
![image](https://user-images.githubusercontent.com/3002987/153776412-5312d500-dc77-415a-8e88-e855e9224b5d.png)

**Comment by jsmnbom** [comment]
Okay so forgot what i said about it being the tonemapper. I think the problem just shows there because of what texture the tonemapper gets passed. Unfortunatly, I have no idea how to debug what texture gets passed to a shader (espcially since it's just an RID, and i have no idea how to use those properly), so I am once again stuck.

My guess (100% a guess, I am too noob to actually figure out how this works), is that the internal texture in p_viewport->render_buffers, somehow does not contain the previously drawn 2d canvas content from RSG::canvas->render_canvas(p_viewport->render_target, ...) calls. Again weather that's how it actually works I have no idea.

Might try again when I have more time, but I think this issue might run deeper than I am able to fix. (sorry for the spam on this issue, do say if these updates are not allowed, i just thought they might help someone in the future.)

**Comment by h0lley** [comment]
I've had a look at it as well and pretty much came to the same conclusion as @jsmnbom.

a couple of things to note:

I am almost certain that @jsmnbom is correct that this call needs to get `environment` passed:
https://github.com/godotengine/godot/blob/9c746b32131d79d85fe05a09db7d8f2f229c3362/servers/rendering/renderer_scene_cull.cpp#L3271

In addition, it should probably get passed `scenario->camera_effects` (which now holds the settings for the DOF effect) as well (it's the two empty RIDs right before `p_shadow_atlas`). Only by passing those arguments will the tonemapper code for the various effects be invoked.

then, I've confirmed that the current state is pretty much how it's always been since the initial Vulkan implementation. so unfortunately it's hard to compare it with the state when it was last working.

next, I've toyed around with [RenderDoc](https://renderdoc.org) to attempt confirm @jsmnbom's suspicion that the issue is not down due to a bug in the tonemapper but rather that it gets passed a black texture. If I interpret it correctly, this really seems to be the case. So it would be interesting to inspect the render buffers - however, I too have no clue how to debug RIDs. It doesn't seem to be documented anywhere.

**Comment by julhe** [comment]
I did some deeper diging and the issues seems to be not only the enviroment not beeing passed, but also the canvas rendering to a completly different texture: ``p_viewport->render_buffers->render_target``. The 3D and post-processing pipeline however uses ``render_buffers->internal_texture`` and only copies in the very last moment into ``render_target`` .

The simple solution would be to copy the contents of ``render_target`` into ``internal_texture``. That seems to be the easiet arround here:
https://github.com/godotengine/godot/blob/8d15814e6a211646a04478978224fd1af41a75cc/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L1559-L1561

I've tried things like ``copy_effects->copy_to_fb_rect()`` but that doesn't work for "Vulkan reasons"🙃, need to do more digging there.

**Comment by h0lley** [comment]
anyone considering addressing this be also aware of this related proposal https://github.com/godotengine/godot-proposals/issues/4564
if 2D and 3D post processing is to be separated, then the solution this issue might look different.

**Comment by sketchyfun** [comment]
This is still an issue in Godot 4.0 Beta 1

All my backgrounds use this method to draw 2D skies behind the 3D world, so it currently breaks the entire view in-game

**Comment by Notatea** [comment]
This issue makes any kind of WorldEnvironment post-processing impossible to use in 2D projects.
Present both on Windows 11 (R5 2600, RX580 4G) and Linux (i5 8265U, intel UHD620) - tried on latest Ubuntu and Fedora releases.

I've looked into it, and I also think that the issue has something to do with canvas rendering texture target. But sadly, my knowledge isn't sufficient to fix this :(

I do agree with @h0lley that 2D and 3D post-processing separation should be considered, though.

**Comment by INdIEDeV016** [comment]
Still an issue in Beta 2...
<img width="282" alt="image" src="https://user-images.githubusercontent.com/80198819/193195427-f459d1eb-2234-4ece-91de-6145b6ed54e9.png">

**Comment by Novark** [comment]
Issue persists in Beta 3 [v4.0.beta3.official (Windows 10 x64)]

**Comment by SewerynKaminski** [comment]
Issue persists in Beta 3 [v4.0.beta3.official (Linux Ubuntu 22.04)]

**Comment by MaybeAnonymous** [comment]
Issue persists in Beta 4 v4.0.beta4.official [e6751549c] (Artix Linux)

**Comment by Calinou** [comment]
As noted in OP, please stop posting further confirmation comments. It will not help the issue be resolved faster. Future comments not bringing significant new information will be removed.
