### ISSUE TITLE
Ability to play the project using an optimized binary from the editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#5257]
If an user has installed export templates, it should be possible to play the project on a PC using the optimized binary (release mode), for improved performance while keeping fast iteration in development (since the button and keyboard shortcut would be integrated into the editor), at the cost of debugging features.

This would be helpful to test the "real" performance of a game without needing to export.

**Comment by Calinou** [comment]
**Update:** This issue is still relevant as of https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

This can be worked around manually (by starting the export template binary and specifying the project path in the command line) but would be still nice to see as a built-in option.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

----

For the reference, I think it's a good idea and it should be easy to implement.

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-proposals#1072.
