### ISSUE TITLE
Missing error message when importing FBX file with missing albedo texture in material

### ISSUE THREAD

**Issue by AgentSmith0** [godotengine/godot#52576]
### Godot version

3.3.3

### System information

Linux, GLES3

### Issue description

Albedo texture missing of FBX files, that already contain materials.

### Steps to reproduce

I attached a file, you can import the FBX in Blender, then turn on Viewport Shading and you will see the materials. But in Godot the materials are not correctly imported. The albedo texture is missing.

### Minimal reproduction project

[Demo.fbx.zip](https://github.com/godotengine/godot/files/7148063/Demo.fbx.zip)

**Comment by Calinou** [comment]
> 3.3.stable

Please test this on 3.3.3 just in case, as [old patch releases aren't supported anymore](https://docs.godotengine.org/en/stable/about/release_policy.html#release-support-timeline).

**Comment by AgentSmith0** [comment]
Oh, yes, I meant 3.3.3. But I found out that the problem was that Godot just couldn't find the path of the albedo textures. When I have the textures in the same directory as the FBX file, it works. Maybe an error message could be added there (or the fix dependencies dialog)?

**Comment by AgentSmith0** [comment]
Should I close this issue and open a new issue or proposal?

**Comment by Calinou** [comment]
Is the FBX file configured to have absolute or relative paths? I don't have the tools required to check.

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
