### ISSUE TITLE
Cannot set constant to an API constant

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5264]
Godot 2.0.3, Windows 10, 64 bits

```gdscript
const HOTKEY_TOGGLE = KEY_F3
```
Produces an error, both in code editor and playing the game:
`Parser Error: Expected constant expression`

I expected it to work because KEY_F3 and the like are constants.

Similar to the PI constant, a while ago https://github.com/godotengine/godot/issues/2134: the fix was to move PI inside the language. In this case you cannot do that for every constant in the engine, so it would be a better fix to make engine constants work the same as user-defined ones.

**Comment by Warlaan** [comment]
I agree that these values should behave like constants, I just think that the example above is not a very good one since there is a built-in mechanism for abstracting keys into actions (Project Settings -> Input Map).

Are there other built-in constants like that? It doesn't affect whether they should be constants or not, but it changes how important this issue is compared to others.

**Comment by akien-mga** [comment]
> Are there other built-in constants like that? It doesn't affect whether they should be constants or not, but it changes how important this issue is compared to others.

There are mainly constants in [@Global Scope](http://docs.godotengine.org/en/latest/classes/class_@global%20scope.html#numeric-constants), PhysicsServer or VisualServer.
Check the [classref status](https://etherpad.net/p/godot-classref-status) for a detailed overview.

**Comment by Zylann** [comment]
@Warlaan I agree the example is not the most widespread use of constants. That's because at time of writing, I was coding a configuration-free debug script in which I put hotkeys on top as consts. 

There are lots of global constants, but also class constants, for example `InputEvent.MOUSE_MOTION`.

**Comment by RandomShaper** [comment]
I'm working on this.

I've thought of different ways of achieving this. I'd like some advice from the original devs, so I welcome @reduz to this discussion.

Options:

1. At the compiler: provided the syntax of the constant initializer expression is good, let the compiler reduce it.
**Pros:**
- More academically correct.
**Cons:**
- Code for expression reduction should be refactored from the parser into some common component.
- Checks for const at edit time would be lost.

2. A variant of the first: still at the compiler but instead of it having to reduce the expression, let it generate the code for evaluating it and use it at runtime to give a value to the constant.
**Pros:**
- Still keeps the parser from dealing with the API.
- No need to refactor the reducer; just apply some constraints to expression evaluation.
**Cons:**
- Checks for const at edit time would be lost.
- Reduction/evaluation should be achieved at runtime so there is a potential for performance lost (negigible?).

3. At the parser: let it access to the API globals and classes to it can use them for reducing the expression and giving a value to the constant.
**Pros:**
- Full checks at edit time.
**Cons:**
- Probably not a good design.

**Comment by RandomShaper** [comment]
I was preparing something more ambitious, more general. For instance, to be able to do `const GOOD_KEYS = [ KEY_A, KEY_B, KEY_C ]` and all kinds of computations and mixing of API globals and class constants.

Any thought about the options I gave?

**Comment by reduz** [comment]
I think constant expression reduction already works the way you mention, as
well as the example you mentioned.
I don't want to touch gdscript code that much, as I was thinking of ways to
implement optional static typing though

**Comment by RandomShaper** [comment]
OK!

Furthermore, probably I was overcomplicating things.
