### ISSUE TITLE
Vector2 movement issues

### ISSUE THREAD

**Issue by GittyGrubHub85** [godotengine/godot#52748]
### Godot version

3.2.3

### System information

Windows 10, GLES2, GE Force 730, i3 processor

### Issue description

I'm trying to make the player climb a ladder. I use Area2D and added a script in there as a way to detect its collision in order for the player to climb when its colliding an Area2D ladder. My other node for player is simply just a Node in my second script, I set its gravity to false to avoid it from falling to the ground. Somehow, I can't climb the ladder even I set its gravity to false already. My jump does work at first which means I can climb the ladder if I press the space bar at that time. As I kept running multiple times, my jumping method doesn't work anymore same as I press "W" button to climb upwards. Is this just me or is there something going on with GDScript?

### Steps to reproduce

Code for climbing input -> https://i.imgur.com/WKw7PAE.png -> https://pastebin.com/raw/vRvndYdq

Code of gravity and its boolean variable -> https://i.imgur.com/nHlFko9.png ->https://pastebin.com/raw/QUYYaStN

Code of Area2D to detect Ladder's Area2D from Player's Area2D -> https://i.imgur.com/VnmQ8vo.png -> https://pastebin.com/raw/41EGPXSr

**Comment by pycbouh** [comment]
This is not a support forum, this is a bug tracker. If you experience issues with your code, please use one of our community platforms to ask for help: https://godotengine.org/community.

If you conclude that there is an issue in Godot, please file a concrete report about what the issue is and provide a minimal reproduction project for contributors to test out and confirm your findings.
