### ISSUE TITLE
GDScript 2.0: Function callhint popup doesn't update after entering a comma

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#52820]
### Godot version

v4.0.dev.20210916.official [104a6191f]

### System information

manjaro Gnome 21, AMD R7 200 series, Intel i3 3.0 GHZ,8GB RAM

### Issue description

https://user-images.githubusercontent.com/58845030/133889746-226cbddf-35e4-46ea-9554-50a29831191c.mp4

### Steps to reproduce

* Create a custom class
* create a function
* try to fill the function in antoher script

### Minimal reproduction project

N/a

**Comment by EricEzaM** [comment]
Right here:
https://github.com/godotengine/godot/blob/8138280d20f8b3974f0f268d4d65035aca30bebc/editor/code_editor.cpp#L844-L847

`text_editor->is_insert_text_operation()` always returns false because `current_op.type` is always `None`. The signal is being called after the current_op has been cleared in `_push_current_op()`. This is also the cause of another issue which says that auto-complete does not trigger just by typing - you need to press ctrl+space. I cannot find this issue right now, but pressing ctrl+space also updates the hint in this issue.

Not sure on the fix, cc @Paulb23
