### ISSUE TITLE
[MultiMesh] `Populate Surface` Spawns Meshes Only Onto Vertices

### ISSUE THREAD

**Issue by ngreve** [godotengine/godot#52845]
### Godot version

v4.0.dev.custom_build [0e5b0c025]

### System information

Linux

### Issue description

When using the the `Populate Surface` feature of a `MultiMeshInstance` the selected source mesh does not get distributed evenly across the target surface. It seems to accumulate the source mesh at the vertices of the target mesh.
The only expection to the issues occurs when using a capsule mesh as the target mesh; with the capsule as the target mesh, the source mesh gets distributed evenly.

### Steps to reproduce

https://user-images.githubusercontent.com/18660100/133925259-35d26910-132d-43d6-a942-b00c53ce0611.mp4

### Minimal reproduction project

[multimesh_bug.zip](https://github.com/godotengine/godot/files/7191966/multimesh_bug.zip)

**Comment by Zylann** [comment]
> with the capsule as the target mesh, the source mesh gets distributed evenly.

Isn't it because capsules actually have much more geometry than other shapes? https://github.com/godotengine/godot/issues/20030
Does your issue also happen with spheres?

If someone wants to improve this to emit instances on faces, I did some work on this with my runtime instancer: https://github.com/Zylann/godot_voxel/blob/6a6682dfd5e9e8cf34c2af8acb2b56811a8f0872/terrain/instancing/voxel_instance_generator.cpp#L164

**Comment by ngreve** [comment]
![image](https://user-images.githubusercontent.com/18660100/133935690-a7d093d0-bcaf-4b60-a01a-6a66b2275b8e.png)

Sphere looks good, too. So your assumption about the more complex geometry would be a good fit here.


>  to emit instances on faces regardless of triangle density

I am not an engine developer myself, but concept wise this seems like a more elegant and scalable approach.

**Comment by CaptainProton42** [comment]
This was a simple fix since the implementation was actually working, `Face3::get_random_point_inside` just made a call to the integer version of `Math::random` thus not actually returning a point inside the face.

Generally, is there demand for generally improving this a bit (e.g. something like Poisson disk sampling to get a more uniform distribution)? Is this something that could just be submitted as a PR or should this be made into a feature request first?

**Comment by Calinou** [comment]
> Generally, is there demand for generally improving this a bit (e.g. something like Poisson disk sampling to get a more uniform distribution)? Is this something that could just be submitted as a PR or should this be made into a feature request first?

I'd just fix what's available for now, then open a proposal at the same time (or later) about improving the otoling.
