### ISSUE TITLE
Some QOL improvements for Asset Library interface

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5284]
The Asset Library is not very polished yet, so I wanted to make some pointers about the interface and open the discussion.

![asset-lib-qol](https://cloud.githubusercontent.com/assets/5599796/16174340/d5c4aab4-3593-11e6-8d60-0d04cd67e6d0.png)

The interface is a bit cryptic and it's hard to tell what some buttons and links do.
- The "Support.." come from Blender's "Supported", but the interface there is different (it actually shows the list, not only when you click). So I proposing this to something like "Channels" (which reminds me of  apt) or "Stability" (which is not quite what it means, but because of the "Testing" that seems to apply).
- The double-arrow button after Sorting has no tooltip. I suppose it means "Ascending/Descending", but the icon doesn't help. Is pressed ascending or descending? Some standard "AZ" icon would be better.
- The pagination numbers are bizarre. What do they mean? What is "0-0/1"? Also, they occupy way to much space. Since there's only one item, I'm not sure how the navigation will work.
- The category in the item is a link. If this link will make the Library go that category, then that'll be okay, but what happens now is that the category changes when you click on the asset.
- The "test-hash" below the category I suppose it's the asset version (though in the asset page it shows an actual version number, so why the hash shows here?). It is also a link. Where will it point to?

**Comment by djrm** [comment]
support -> Channel.
Site -> Host | Origin
let me know if you need a custom sort icon

**Comment by ArcFutahito** [comment]
After our little talk with vnen, I decided to make a little mockup of AssetLib window that would reduce the amount of clicks needed for stuff to actually happen. If user wants to apply filters to search, right now he needs to: 
1. Click on first filter
2. Select filter
3. Click on category filter
4. Select filter
5. Optionally click on "Support" filter. 
6. Select filter
This can be reduced by combining all menus in one group. For example
![mockup1](https://cloud.githubusercontent.com/assets/10696955/16444934/2d4dde2e-3de9-11e6-888f-b12c6e623014.png)
Here user can click on "Filters" button and enter one filter menu, where he can select all toggles. It's not really necessary but it would be nice if, depending on "descending/ascending" option labels would change names (like "Most popular/Least popular", "Most expensive/Cheapest". 
"Sort by name" option name is a bit icky but that's not particularly a problem. 
Since users don't change repositories often, repository selection is in the "Settings" dropdown. From there user can also import assets from the disc and open plugin settings. 
![mockup2](https://cloud.githubusercontent.com/assets/10696955/16445700/94b2e3ea-3dec-11e6-9549-3326213ce3eb.png)
Here is an example of "main" view. On top one of the featured assets is displayed with short description. It's followed by icon grid of newest assets. On the bottom of the icon category and rating of the asset is displayed. Background is darkened for better readability.
That's my take on AssetLib. Less clicks and more content on the main view.

**Comment by akien-mga** [comment]
One year later (!) this hasn't seen much work, and 3.0 is around the corner. Assigning to the 3.1 milestone, as I think we might get new ideas and motivation to improve the assetlib as new 3.0 content starts being added to it.

**Comment by Calinou** [comment]
**Bugsquad note:** This issue is still relevant as of commit https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

For the record, this is how the Asset Library interface looks like in the editor as of 2018-04-04:

![assetlib_20180405](https://user-images.githubusercontent.com/180032/38358513-b6a219a0-38c5-11e8-8bff-3d1144cc5ad1.png)

**Comment by vichug** [comment]
Hello, there are some usability mysteries about the asset library :
when one downloads an example demo using the built-in asset downloader, first it downloads the thing ; then you have to clic "install" to install it. That's two buttons where one could have been enough (if prompted about the location at the start of the download process), but i guess that's fine.
While it is downloading,you have the option to continue browsing the asset lib and begin the downloads of other demos/assets so you can download in parallel several assets without problem, which is cool, but...
when you clic "install" for a specific asset that has finished downloading, you are prompted for a location in which to install, and then you have a choice between just 2 options :
either "cancel" or "install and launch".
If you "install and launch" the asset will install and godot editor launches, _and all the other downloads will go to the void_. You can not batch install them, which is strange considering you can batch download them.

**Comment by flurick** [comment]
The only thing left to do is deciding what to call the "support" button

**Comment by Calinou** [comment]
@flurick Do we have any more suitable name? We could rename it to "Support Level" (it seems we have enough space to do it), but I'm not sure what else we could do.

**Comment by Anutrix** [comment]
Isn't calling it Channel fine?

**Comment by socket220** [comment]
It seems to me "Server" suits pretty well.

**Comment by Calinou** [comment]
> It seems to me "Server" suits pretty well.

All support levels come from the same server (that is, `godotengine.org/asset-library/`).

**Comment by socket220** [comment]
> 
> 
> > It seems to me "Server" suits pretty well.
> 
> All support levels come from the same server (that is, `godotengine.org/asset-library/`).

Ok, so how about "Channel" as mentioned @Anutrix ? Or "Support channel" -- something like that?

**Comment by Calinou** [comment]
@socket220 I tried changing it to Support Level but this makes the bar overflow at the narrowest project manager window width when the **Least Recently Updated** sorting mode is selected:

![image](https://user-images.githubusercontent.com/180032/110251257-07e63180-7f80-11eb-93be-078e36e077c9.png)

**Comment by ator-dev** [comment]
Personally I'd prefer fewer dropdowns and more asset details (like the update time) shown in the window, which the current interface doesn't allow for. I've edited together a quick draft of what a new interface could look like that would show clearer information and never causes overflow (which happens in both the current Godot 3 and 4 asset libraries):

![image](https://user-images.githubusercontent.com/66553618/139603123-af351944-93cc-42a4-95a1-68cd647c0244.png)

Do any of these changes seem like an improvement? Obviously these are just initial thoughts on how they could look, and some of them could be added while others left out. I'm planning on programming the implementation if this looks alright to anyone else  (;

**Comment by Calinou** [comment]
> Do any of these changes seem like an improvement?

I'm not sure. it feels like this proposed design makes less efficient use of horizontal space (especially on wider displays), since the two columns on the right are displaying relatively little information compared to the main column on the left.

**Comment by ator-dev** [comment]
@Calinou Thanks, that's a good point. Do you think it would be alright to display smaller asset icons in the list, so that more of them can be displayed? I like this format because it adds flexibility to the design; we can easily add more information at a glance if needed, for example if star ratings are added to the library.
Here's a new draft that reflects this better:
![image](https://user-images.githubusercontent.com/66553618/139649956-da50a38a-6d63-451d-b5b1-ac873de57db6.png)

Alternatively, the icons could be larger at the expensive of slightly fewer items on screen but still a lot more information.

**Comment by Calinou** [comment]
> Do you think it would be alright to display smaller asset icons in the list, so that more of them can be displayed?

The icons are designed to be displayed at a size of 64×64, so I'd prefer to keep them at their current size. Non-power-of-two scaling may look blurry, so I'd rather avoid it.

Also, we currently don't have a "short description"/blurb field that we could display on the right or below each asset title. Most descriptions are too long to be featured below the asset title in the list of assets.

**Comment by ator-dev** [comment]
> > Do you think it would be alright to display smaller asset icons in the list, so that more of them can be displayed?
> 
> The icons are designed to be displayed at a size of 64×64, so I'd prefer to keep them at their current size. Non-power-of-two scaling may look blurry, so I'd rather avoid it.
> 
> Also, we currently don't have a "short description"/blurb field that we could display on the right or below each asset title. Most descriptions are too long to be featured below the asset title in the list of assets. This is something the [new asset library](https://github.com/Calinou/godot-asset-library-laravel) features, but we have no ETA for deploying it currently. (Also, existing assets won't have blurbs automatically added to them, as the field is optional.)

Ok, that makes sense. Still, with putting some of the information in columns, there's no empty space (other than padding) needed below the icons which means you can fit quite a few assets on the screen anyway.
The new asset library looks interesting - it is a bit of a downside to the current version that there isn't a summary field. However, I've found that many of the assets currently have 1 or 2 line descriptions, while the first line of the longer descriptions usually summarises the purpose anyway; if we keep the icons at the 64×64 size, there are three (short) lines per asset available for the 'Description' column. I'm thinking of just displaying the first part of the descriptions here since in many cases this would summarise an asset's purpose quite well.
Additionally, I could hide the description column in a small window, then add it once it's expanded, making it easier to compare assets without having to click on them separately.

Given these changes, would you be happy for me to have a go at programming a draft version of the asset library, or would you prefer for only some or none of the changes to be implemented? I understand if you think it's better left as it is of course (:

**Comment by ator-dev** [comment]
Here's a quick example using descriptions randomly picked from the Godot 3 asset library:
![image](https://user-images.githubusercontent.com/66553618/139678301-0a81b547-ca28-4c92-a469-b02532adcced.png)

**Comment by MHAQpps1** [comment]
Hey, we've noticed that this issue has existed for about 6 years. We've noticed some changes that have already been made, but the main one about the "Support" button has not been fully touched yet. We are thinking working on it ourselves. Is that okay? Also, this is one of our first time doing this, can you give us some tips on how to do it?

**Comment by coppolaemilio** [comment]
I think this issue should be closed or moved to https://github.com/godotengine/godot-proposals
It is a bit too broad and improvements will be made for the new asset lib.
