### ISSUE TITLE
`apply_velocity_on_leave` in `CharacterBody3D` is may not working correctly

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#52957]
### Godot version

4.0.dev

### System information

MacOS 11.4

### Issue description

`apply_velocity_on_leave` in `CharacterBody3D` is may not working. Or possibly the calculation of `get_floor_velocity()` is wrong or jumping method in GDScript is wrong... So, there is a gap when jumping on a moving platform.

### Steps to reproduce

https://user-images.githubusercontent.com/61938263/134446182-1892b32f-0b53-4a5b-84ae-4db9f9c4a6b6.mov

### Minimal reproduction project

#50732

**Comment by pouleyKetchoupp** [comment]
From what I see in your script you apply the platform velocity yourself here:
https://github.com/TokageItLab/3d-platform-test-for-godot4/blob/d9176bc0e88c8c03e8bfb1cab428a32241fbb786/Player/Player.gd#L274-L275

So even if you `apply_velocity_on_leave` is set to `Never`, the platform velocity is used.

On the other hand, if you set it to `Always`, the `linear_velocity` set by `move_and_slide()` just when you leave the platform is set to the platform velocity, so in this case you need to make sure not to reset it to 0 during your jump.

Let me know if that helps.

You can also have a look to the simpler script @fabriceci made based on your project as an example:
https://github.com/fabriceci/3d-platform-test-for-godot4/blob/main/Player/Player.gd

**Comment by TokageItLab** [comment]
@pouleyKetchoupp @fabriceci

Does this mean that `motion_velocity` should not be touched while jumping? I think that would block the player's control during the jump.

Probably, I think the general way of coding controllers is to assign player input to `motion_velocity` as it is in GDScript, so it may not be good way for `motion_velocity` to be changed implicitly.

Also, in addition to `UpwardOnly`, I think it would be better to implement `ExceptUpward`. This is a matter of illusions and feeling, but on a platform that is moving up and down, it may be more comfortable to have a lower jump height on a platform that is moving up, and a higher jump height on a platform that is moving down.

**Comment by fabriceci** [comment]
I didn't look at your code, but on the simplify project that @pouleyKetchoupp linked, if you remove the friction in the air and jump, the player stays on the platform, which seems to indicate that `apply_velocity_on_leave` works correctly.

![air friction](https://user-images.githubusercontent.com/6397893/135878384-fcb9a87f-7516-42f7-9575-4784113e37aa.gif)

**Comment by TokageItLab** [comment]
@fabriceci It's not a problem of air friction. At least in my latest project, `Always` works like `UpwardOnly`, and `Never` causes a gap.
https://github.com/TokageItLab/3d-platform-test-for-godot4

**Comment by pouleyKetchoupp** [comment]
@TokageItLab Let's see if we can clarify a few points to help you get the desired behavior, and adjust character options if needed.

> Does this mean that `motion_velocity` should not be touched while jumping? I think that would block the player's control during the jump.

You can still make adjustments to x and z for air control by interpolating between the current values and the player inputs, but you can't just replace the velocity, otherwise you lose the velocity from the platform you just left from.
Could you try this way to see if it works for you? I think that's what @fabriceci did in his test project.

> Probably, I think the general way of coding controllers is to assign player input to `motion_velocity` as it is in GDScript, so it may not be good way for `motion_velocity` to be changed implicitly.

Yeah, I know it would be ideal, but it would be difficult to design a flexible system this way. At the moment, the idea is for things like jump and platform velocity, `motion_velocity` is modified when changes happen so the script can take it into account and combine it with player controls in the desired way.

On the other hand, you can still decide to set the platform behavior on leave to `Never` and handle changes in velocity directly in gdscript.

> Also, in addition to `UpwardOnly`, I think it would be better to implement `ExceptUpward`. This is a matter of illusions and feeling, but on a platform that is moving up and down, it may be more comfortable to have a lower jump height on a platform that is moving up, and a higher jump height on a platform that is moving down.

I'm not sure `ExceptUpward` would do what you expect. It would mean that it applies the platform's velocity when you leave in the downward direction only, which means your character won't jump as high if you jump while it's going down.

In order to achieve what you describe, you might actually need an option to do side velocities only. Please test jumping with `Never` on a platform that moves up and down to check if it's correct, and if it's the case we can add another option.

> After I try some test, I could not get the desired behavior.

Could you please try and describe precisely what is the desired behavior for your case? I share @fabriceci's feeling that it's mostly a script issue, but there are certain things I don't understand clearly:
-Do you need the player to stick to the same point on the platform when you jump?
-How much air control do you need?
Right now, it seems like these two functionalities might be conflicting, because air control is causing x/z velocity to be changed, which makes the character not always stick to the platform (that requires keeping the leaving platform velocity x/z intact while jumping).

**Comment by TokageItLab** [comment]
@pouleyKetchoupp @fabriceci Oh, I noticed that something might be wrong, is the @fabriceci 's project up to date? The Player does not apply the inertia of the moving platform in my environment (MacOS 11.5.2 MacBook Pro 2019), even though it is `Always` mode.

**Comment by pouleyKetchoupp** [comment]
> These do not conflict. If I want to move the character while jumping, I can simply add the speed obtained from the platform using the `Never` option as you say in GDScript, but the problem is that when `Never`, the landing point will be slip on the moving platform, even though no input in the xz direction when jumping.

In any case, in order to get the correct behavior you'll have to modify a bit the logic around jumping in your script.

If you set the mode to `Never`, you need to apply the platform velocity yourself, not just when you are on the platform, but also on the first frame after leaving it.

On the other hand, `Always` does that for you but you need to make sure you apply x/z velocity changes only when you actually have inputs from the player.
I was able to make this case to work in your project by:
- Commenting this line to stop applying platform velocity manually:
https://github.com/TokageItLab/3d-platform-test-for-godot4/blob/ca967371fcfdf80b003b642e7f1fc90f0006afb4/Player/Player.gd#L270
- Adding a condition `if self.is_on_floor() || h_velocity != Vector3():` on setting the velocity here so it's not reset to 0 when leaving the platform:
https://github.com/TokageItLab/3d-platform-test-for-godot4/blob/ca967371fcfdf80b003b642e7f1fc90f0006afb4/Player/Player.gd#L146-L148
- Changing the condition to `if !self.is_on_floor() && _state_jump_velocity != Vector3():` here so the jump velocity doesn't keep being accumulated:
https://github.com/TokageItLab/3d-platform-test-for-godot4/blob/ca967371fcfdf80b003b642e7f1fc90f0006afb4/Player/Player.gd#L161-L163
- Changing this line to `_state_jump_velocity = Vector3()` here for the same reason:
https://github.com/TokageItLab/3d-platform-test-for-godot4/blob/ca967371fcfdf80b003b642e7f1fc90f0006afb4/Player/Player.gd#L175

With these changes, the velocity is properly applied when leaving the platform and you don't get the gap.

The only remaining problem you need to fix is that when you're against a step and you jump, the x/z velocity is canceled and you end up not jumping forward.
For that you would have to make sure inputs are still being applied while jumping, but I'm not familiar enough with your code to make this change easily.

> As for `ExceptUpward`, I consider the effect of reaction in physics. For example, if you are in an airplane, the sensation of your body being pressed against the chair during takeoff and the sensation of your body floating during landing are applicable. So.. rather than saying `ExceptUpward`, it might be better to say `InvertUpward`.

In the case you describe, isn't the effect due to the frame of reference being the plane itself (i.e the moving platform)?
I'm not sure it would look correct to apply this effect in world space, but I wonder if you could play with the camera (sticking to the platform in some cases) to get a similar feeling.

> Oh, I noticed that something might be wrong, is the @fabriceci 's project up to date? The Player does not apply the inertia of the moving platform in my environment (MacOS 11.5.2 MacBook Pro 2019), even though it is Always mode.

You're right, it looks like the repo is not up to date with the latest API, so maybe that's the problem. Let's see if we can update it soon so you can use it as an example.

**Comment by TokageItLab** [comment]
@pouleyKetchoupp Thank you for explaining.

> You're right, it looks like the repo is not up to date with the latest API, so maybe that's the problem. Let's see if we can update it soon so you can use it as an example.

Does that mean that the current godot/master API has not been updated yet? Maybe there is nothing wrong depending on the behavior of the latest API, I will wait for that.

**Comment by pouleyKetchoupp** [comment]
@TokageItLab The godot/master API is all up to date, I was just referring to @fabriceci's test project for 3D platforms. It's all updated now, and falling back on the same spot in the moving platform should work as long as you disable "Air friction" in the options (press escape to toggle the mouse so you can click the GUI).

**Comment by TokageItLab** [comment]
@pouleyKetchoupp @fabriceci Okay, I mostly understand now.

The bug in `Always` is caused by my code overriding `motion_velocity` in the air on GDScript. This is my bad.

So the only problem is that in `Never`, when I want to apply the velocity of the moving platform by myself with GDScript, in one frame just after the jump, the "calculation to follow the moving platform in the physics server" and the "jump velocity calculated from the velocity of the moving platform in GDScript" are applying the movement doubly.

**Comment by TokageItLab** [comment]
The reason for causing the shift with `Never` was that the `platform_velocity` was included in the initial velocity of the jump. (It's the velocity used to move the player from ground to air, so it adds up on the ground as well.

So, I finally made the following fixes.

https://github.com/TokageItLab/3d-platform-test-for-godot4/commit/d655bd6b5cc1ad4b9363a0021abe1e1aead6abee

Considering the changes since 3.x, the system has become quite complex. However, if you understand everything, it is a great physics system that does not break the bank. It may be difficult to write documentation about it, but I will try my best to help explain it to users by creating tutorials and add-ons.

There are still some issues to be resolved, such as the priority order of collider resolution, but I believe we have perfected the basic physics calculations in `CharacterBody`. Thanks a lot @pouleyKetchoupp and @fabriceci !

**Comment by TokageItLab** [comment]
Sorry I found another issue #53435. The behavior is similar but probably a different problem.

**Comment by pouleyKetchoupp** [comment]
Thanks for spending so much time testing and reporting issues @TokageItLab! It helps a lot. We'll have a look into the new issue.

Concerning this case:

> So the only problem is that in `Never`, when I want to apply the velocity of the moving platform by myself with GDScript, in one frame just after the jump, the "calculation to follow the moving platform in the physics server" and the "jump velocity calculated from the velocity of the moving platform in GDScript" are applying the movement doubly.
>
> This means, for example, that if you jump at the 5th frame on a platform that moves in the x-direction at `1 m/frame` with `apply_velocity_on_leave` being `Never`, the question is whether the x-coordinate is `4` or `5` or `6`.

The frame when you're starting to jump, platform velocity is applied within the physics server, but it shouldn't be the case the one after.

Your script can go this way:
```
[physics process frame 1]
-Character standing on the platform
-move and slide -> applies moving platform
-is_on_floor = true
[physics process frame 2]
-Character starts to jump
-move and slide -> applies moving platform
-is_on_floor = false
[physics process frame 3]
-This is where you can apply the last platform velocity yourself (or at the end of frame 2)
-Character jumping
-move and slide -> doesn't apply moving platform
-is_on_floor = false
```
