### ISSUE TITLE
Switch Editor Language needs project restart

### ISSUE THREAD

**Issue by AlexHolly** [godotengine/godot#5296]
Ubuntu 14.04
64-bit

After an "Editor Language change" I need to restart the project to get the new Editor Language.

**Comment by Zylann** [comment]
Does it also means changing game language requires game restart?

**Comment by volzhs** [comment]
@Zylann https://github.com/godotengine/godot-demo-projects/tree/master/gui/translation
this shows how to change language in game without restart.

**Comment by reduz** [comment]
this will not be fixed, but will leave it open as a reminder that we must show some sort of warning for properties that they were changed and a restart must happen.
I added an usage flag for this, but it' s not being used to show a warning yet

**Comment by AlexHolly** [comment]
Maybe popup a window on switch that is asking for an "restart project now"?

**Comment by punto-** [comment]
The more general issue is that Label and the other controls don't remember
their "original" string, only the translated one.

**Comment by reduz** [comment]
@punto- that is true for the running game and only for a few specific controls (button and label), and has to be fixed eventually (probably keeping key and text).,

For the editor, though, there is just no chance to do it. Text is used in many many other places and controls or custom controls. It needs to restart and this can' t be fixed. Adding a lot of code because changing language of the fly looks cool does not make it worth it, because we' ll have to then hunt for bugs related to text not changing when language is changed.

What needs to be fixed is handling editor restart in this case.

**Comment by akien-mga** [comment]
The warning @reduz mentions + the possibility to set the language from the project manager (#4901) would go well together IMO.

**Comment by AlexHolly** [comment]
Is it possible to add some kind of "Restart Godot now to apply changes?" screen that will kill the current process and reopens godot with current Project?

**Comment by AlexHolly** [comment]
A "Save&Restart" Button appears at the Bottom after making a language change.
