### ISSUE TITLE
Editor lags when selecting color for StyleBox

### ISSUE THREAD

**Issue by floppyhammer** [godotengine/godot#53087]
### Godot version

v3.4.beta5.official [dd0ee4872]

### System information

Windows 11, GLES3

### Issue description

Editor lags when selecting color for StyleBox.

![color_picker](https://user-images.githubusercontent.com/28705694/134807067-1fdb21db-05a3-442d-be78-d71e3f7038f1.gif)

### Steps to reproduce

Open the reproduction project, click `theme.tres` in the FileSystem tab, change `bg_color` of a StyleBoxFlat.

### Minimal reproduction project

[StyleBoxColorTest.zip](https://github.com/godotengine/godot/files/7231356/StyleBoxColorTest.zip)

**Comment by pycbouh** [comment]
Note that this doesn't happen in the latest `3.x` version anymore because the StyleBox resource will now open in a new inspector instead of showing in a sub-inspector. This is ultimately a performance problem of the inspector with huge objects, which is made bigger by the fact that we have a theme editor now that also syncs up with the resource.

This is still a problem in `master` though.

**Comment by floppyhammer** [comment]
No such an issue in 3.3. And it's not only lagging but also mouse input interruption which effectively makes the color selection process uncontrollable.

**Comment by pycbouh** [comment]
Yes, this is not so obvious in 3.3 and prior because basically nothing happens in the old theme editor. But the chokepoint is in the inspector nonetheless. You also don't see this in 3.4 with smaller theme resources.
