### ISSUE TITLE
Split script editor

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5315]
It would be neat to split the code editor in two (at least) horizontally and/or vertically. Sometimes I need to edit more than one script at a time and this would make it easier.

Don't seem so hard to do, but it can wait and be done after 2.1.

(I'm impressed that no one asked this before, or my GH-issue-search-fu failed on me.)

**Comment by bojidar-bg** [comment]
Would be cool if we can also split between script editor and 2D/3D view (or even one 2D and one 3D..), WDYT?

**Comment by hubbyist** [comment]
These issue may end up Godot editor having splitable, mergeable and modifiable viewports which can be any panel as in Blender. And may lead to significant changes in GUI I think. It has a feeling of "Big Red Button". :smile: But any way It will be cool. :)

**Comment by bojidar-bg** [comment]
Well, we actually don't need to support more than 2-3 splits, since it becomes uselessly granular at some point. But being able to edit script and 2D/3D is really helpful for tool script prototyping.

**Comment by reduz** [comment]
Let's wait for 3.1 for this, way too many things already for 3.0

**Comment by justinluk** [comment]
Bump.

Is this going to be added into 3.1?

**Comment by vnen** [comment]
Well, this is not priority. I'm not sure if I'll have the time to look into it for 3.1. If someone wants to step up and do it, be my guest.

**Comment by coppolaemilio** [comment]
I would love to have this feature implemented, specially when doing the Distraction Free Mode, half of my screen is empty 😢

**Comment by burstina** [comment]
Horizontal split is a must have, nonetheless many text editors have this feature.
When code in a signle script is big, there is a big need to look at the top to browse variables.
Editor itself is a nice one, but moving always up and down is frustrating.

**Comment by Megalomaniak** [comment]
Hopefully something for 4.0 then if not 3.2?

**Comment by jahd2602** [comment]
3.1-stable still doesn't have this.

There are a couple of reasons that make me open VSCode when editing GDScript, and this is one of them.

Coding something while looking at another file/another line of the same file is very common, and scrolling/alt-lefting all the time makes it very hard.

**Comment by magpie514** [comment]
I'd like to have this as well, it's pretty much the only reason I'm using an external editor.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
