### ISSUE TITLE
Raster occlusion incorrectly culls objects through gaps

### ISSUE THREAD

**Issue by lawnjelly** [godotengine/godot#53288]
### Godot version

4.0 dev df57aa670

### System information

Linux Mint 20, Intel HD graphics 630

### Issue description

Objects are being culled when they should be visible, in cases where there are small gaps between occluders.

Setup:
![Screenshot from 2021-10-01 08-45-37](https://user-images.githubusercontent.com/21999379/135585233-039786eb-37f8-4f7a-8a8d-46dd109947f8.png)
What should be seen:
![Screenshot from 2021-10-01 08-45-23](https://user-images.githubusercontent.com/21999379/135585250-5e2be9ae-8c9e-4e34-8489-42ccdbbd1690.png)
What is seen:
![Screenshot from 2021-10-01 08-45-09](https://user-images.githubusercontent.com/21999379/135585255-760fc5fa-c407-4634-bb2f-a0a2181b5a13.png)
Occlusion buffer:
![Screenshot from 2021-10-01 08-46-23](https://user-images.githubusercontent.com/21999379/135585455-97febc76-f351-4a0f-8863-a83a06d1a449.png)

### Steps to reproduce

Create a couple of boxes as occluders and place them with a small gap, then attempt to view a 3rd object through the gap. Vary the viewing angle / distance.

### Minimal reproduction project

[TestOcclusion.zip](https://github.com/godotengine/godot/files/7265271/TestOcclusion.zip)

### Discussion

I'm just having a look at some situations likely to trip up the raster occlusion, especially edges / joins between objects. I'm guessing this is caused by the rendering of the occlusion buffer not being conservative (or rather the opposite of conservative rasterization :smile: ), i.e. gaps between objects are being joined. This makes occlusion more effective, but produces visual artifacts.

This one can be quite disturbing as objects flicker in and out of view according to the viewing angle, and whether or not a gap is rendered in the occlusion buffer.

**Comment by tinmanjuggernaut** [comment]
On Alpha13 if the gap is wide enough it works fine.

https://user-images.githubusercontent.com/632766/182120007-b8321dd2-6f48-4851-bb69-9249adb6a7e9.mp4

To trigger it requires two objects occluding something, it doesn't work with one. And the effective gap between them has to be narrow. Here the objects have a wide gap, but because of the angle, the effective gap has made the red object disappear. The difference between left and right is just camera angle, as the red box is flickering when I move the camera. Interesting how different the occlusion mask is.

![image](https://user-images.githubusercontent.com/632766/182123238-fc218944-41e9-4c91-8d8f-d6e99b396240.png)

**Comment by Calinou** [comment]
Does anyone have pointers to performing conservative rendering with Embree? GPU support isn't a  problem here as raster occlusion all happens on the CPU.

**Comment by lawnjelly** [comment]
> Does anyone have pointers to performing conservative rendering with Embree? GPU support isn't a problem here as raster occlusion all happens on the CPU.

Even with non-conservative rasterization (don't know what the word for this is, but only fill if an entire pixel is within poly) you would get gaps between polys _within_ a mesh. So it wouldn't really be a solution, just a part explanation of the problem.

With ray tracing, I guess the aim would be to find if any ray can pass between the two objects, which could be quite tricky. But you could have a stab. If you recorded e.g. the triangle ID hit per pixel, you could calculate a point between two adjacent triangle IDs to trace a ray to. But this might be expensive, and wouldn't work in all cases. I don't know, perhaps there is some literature on dealing with this problem. Maybe you could use the silhouette edges somehow. :man_shrugging:

**Comment by tinmanjuggernaut** [comment]
Can this be added to the gd4 roadmap?

**Comment by timshannon** [comment]
Maybe add a margin value when generating the culling geometry?  Scale the occluder down a bit to account for the gap in the rasterization?  It'd be better for it to occlude too little than too much and have obvious pop-in like this right?  With a user set margin value, it could be tweaked on a per scene basis.

**Comment by lawnjelly** [comment]
> Maybe add a margin value when generating the culling geometry? Scale the occluder down a bit to account for the gap in the rasterization? It'd be better for it to occlude too little than too much and have obvious pop-in like this right? With a user set margin value, it could be tweaked on a per scene basis.

This is a good idea as anything using pre-processing would be great, but two potential snags:
* The best margin to shrink the meshes may be dependent on view distance / angle (a small margin would work up close, but a larger margin would be needed for distance, to ensure that pixel gap)
* Consider if users build a continuous wall out of two objects that abut, this could introduce a gap between the two, through which the AABBs of occluded objects may then be seen, reducing a lot of the occlusion. That is unless you could detect such cases, which might not be trivial .. perhaps by voxellizing the scene or something like that.

**Comment by thoced** [comment]
Hello,
Using the occluderInstance3d, I found that this problem still existed. I wanted to post an issue but I realize that the problem was already present in 2021. Has a solution been found?

**Comment by Calinou** [comment]
> Has a solution been found?

No, other than tweaking the meshes you use for occlusion manually.

**Comment by Calinou** [comment]
@gongpha made a custom occlusion culling baker with shrinking along normals: https://github.com/gongpha/gdQmapbsp/commit/9d031ad17984cf87d210a5b15b3c5a223d6df00d

**Comment by myaaaaaaaaa** [comment]
An alternative solution would be to add an option for occlusion "soft-culling", where instead of skipping rendering of occluded objects entirely, the LOD can be lowered instead, which should result in less distracting artifacts.

Essentially, this would rely on GPU depth testing to prevent overdraw ([Hierarchical Z](https://fgiesen.wordpress.com/2011/07/08/a-trip-through-the-graphics-pipeline-2011-part-7/#:~:text=Hierarchical%20Z/Stencil) makes this very fast for low polycounts), and HLOD to reduce draw calls.

**Comment by myaaaaaaaaa** [comment]
See a proof-of-concept below that sets LOD bias to 0.1 when occluded.

https://user-images.githubusercontent.com/103326468/222288895-b603ff26-bd0f-4633-b1e2-79b27603b05e.mp4

One other benefit of this approach is that it allows for more aggressive occluder meshes, such as using a quad for a chain link fence.

**Comment by myaaaaaaaaa** [comment]
> One other benefit of this approach is that it allows for more aggressive occluder meshes, since small gaps no longer need to be preserved.

It also allows for more aggressive bounding boxes for occludee meshes. See below for a proof-of-concept "bounds scale" knob that shrinks AABBs before doing occlusion testing, which is much more feasible now thanks to soft culling.

https://user-images.githubusercontent.com/103326468/222990232-75927466-cf33-4300-af11-8d510591bee8.mp4

Left: Bounds scale = 0.1x (an extreme value for easier demonstration)
Right: Bounds scale = 0.5x (a more typical usage)

**Comment by Enhex** [comment]
> > Does anyone have pointers to performing conservative rendering with Embree? GPU support isn't a problem here as raster occlusion all happens on the CPU.
> 
> Even with non-conservative rasterization (don't know what the word for this is, but only fill if an entire pixel is within poly) you would get gaps between polys _within_ a mesh. So it wouldn't really be a solution, just a part explanation of the problem.

it's possible to make it work by only allowing "pixel overflow" for internal edges.
internal edges can be defined as edges that overlap and can be computed ahead of time during baking.

also it's better to have these gaps and render a correct image slower than render a very wrong image faster (at which point you disable the occlusion culling, defeating the purpose).
you can optimize for this approach by using occluders with big triangles/polygons.
this is what Urho3D did AFAIK and it worked fine.

**Comment by Enhex** [comment]
if i understood correctly Godot's occlusion culling uses raycasts to create the depth buffer, which is a wrong solution.
if the depth buffer's pixels are larger then the viewports pixels they can hide things which should be visible.
if they're smaller (unlikely) they can not hide things which should be hidden.
it's only correct if the occluder buffer and viewport buffer have exactly matching pixels. (not practical)

instead of raycasting against occluders, rasterize the occluders' triangles.
this approach worked for Urho3D. introduction can be found [here](https://urho3d.io/documentation/HEAD/_rendering.html) in the "Optimizations" section.

**Comment by bedardjo** [comment]
Hi, this issue has come up in a project I have been working on and I'd like to share some findings.

Firstly, here's a [minimum repro project](https://drive.google.com/file/d/1ldPm_Wfh2h2aCFj2pMLmfgeAukB5p_0m/view?usp=drive_link). This is on Godot 4.2.1.

Also, I took some notes when I was reading through the code trying to understand the issue. Sharing them in case they come in handy: [notes](https://docs.google.com/document/d/1x7-F5IkPyNY19F9Dg3CFnz5o89isgIsvb6-yZ9bfpQA/edit).

[This section](https://docs.google.com/document/d/1x7-F5IkPyNY19F9Dg3CFnz5o89isgIsvb6-yZ9bfpQA/edit#heading=h.otwf64m6f06k) may be of particular interest, as it mentions a few variables I was able to tweak to make the issue go away. This info might be useful to somebody with a better understanding of the code.

Cheers!

**Comment by unfa** [comment]
> Godot's occlusion culling uses raycasts to create the depth buffer, which is a wrong solution.

Oh. So the engine does a raycast for every pixel in the occlusion buffer?
Wouldn't raycasting at a lower res inherently miss everything that is between the rays? 
Raycasting will always miss "everything between" the rays, unless we do it at full res, will it not?

And there's an option to instead just rasterize the triangles??

Why isn't that used? Wouldn't it give the same result only much faster and with less errors due to rays being sparse?

**Comment by yosoyfreeman** [comment]
Yes, the RayCasting solution is problematic for this use case.  Not only because you loose information between the rays, but because this gaps can result in zones being occluded that should not.  In general lines, one wants to be conservative with the culling, which means that rending more than needed is always preferable to rendering less than needed (rendering exactly what is needed is an unrealistic expectation). This can be achieved in multiple ways, but a common approach is to render a depth texture to a lower resolution using the CPU, and then downscaling it multiple times keeping always the brighter/farther value.  This results in a much smaller texture in which the "available space" was prioritized, which makes sure (Intentionally) to show a little more than what is actually needed.  You also have a really small texture to perform checks against using the screen space position of the occluders.  This technique was used in KillZone 3, for example, and seems very similar to what Urho3D does to.

**Comment by unfa** [comment]
I suppose many other games use the same idea or something based on it.

To me it looks like we're trying to hammer nails using a cucumber.

Maybe instead of covering the cucumber in chainmail, we can use a hammer instead? :D
