### ISSUE TITLE
HTTPS requests fail on macOS with TLS handshake error: -9984 when built with Clang 12 with -O2 or higher

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#53297]
### Godot version

3.4.Beta5

### System information

MacBook Pro (13-inch, 2019) 2.4 GHz Quad-Core Intel Core i5

### Issue description

Production exports no longer seem to connect properly to HTTPS domains.

```
ERROR: TLS handshake error: -9984
   at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:87)
mbedtls error: returned -0x2700

ERROR: [Network Error]: when waiting for request completion
   at: call (modules/gdscript/gdscript_functions.cpp:774)
ERROR: Condition "!node" is true. Returned: nullptr
   at: get_node (scene/main/node.cpp:1326)
   ```

Debug exports and editor builds still seem to function normally.

### Steps to reproduce

1. Clone https://github.com/tavurth/godot-internet-bug
2. Export to production
3. Run project from terminal

### Minimal reproduction project

https://github.com/tavurth/godot-internet-bug

**Comment by akien-mga** [comment]
Does it work properly in previous versions (3.3.3-stable or intermediate 3.4 betas)?

**Comment by tavurth** [comment]
It was working intermittently for me in 3.4.Beta3, it was working fine in 3.3.x.

Could this be something to do with my back-port of the HTTPS gzip system? https://github.com/godotengine/godot/pull/48651

**Comment by dsnopek** [comment]
I'm also seeing this problem with 3.4.0-beta6, but only on MacOS. Running the same game on Windows or Linux doesn't get this issue. So far it hasn't been intermittent, all HTTPS requests failing with this error message.

**Comment by dsnopek** [comment]
I tested 3.4-beta1, and it fails even there! Were there any alpha's or earlier official builds?

FYI, I started using the test project from @tavurth because it's easier to build than my project, and it fails/succeeds in the same way as mine.

Also, just to re-iterate something from the original description so it doesn't get lost: this problem only happens on release exports! When run in the editor, or with debug exports, the issue doesn't happen. So, it seems that something necessary is turned off in the release build?
