### ISSUE TITLE
One line of code generates hundreds of errors

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#53345]
### Godot version

d97f223

### System information

W10

### Issue description

While converting a project I came across this code:
```GDScript
func load_path(path: String):
	for entry in data:
		for property in mandatory_properties:
			assert(property in entry, str("Missing mandatory property '", property, "' in entry '", entry.name, "'"))
		
		if not valid_properties.empty():
			for property in entry:
				assert(property == entry_name or property == id_name or property in mandatory_properties or property in valid_properties,
						str("Invalid property '", property, "' in entry '", entry.name, "'"))
```
Which produces this:
![image](https://user-images.githubusercontent.com/2223172/135735357-da33c83f-4409-4415-a5c6-2ec3f25c9470.png)

### Steps to reproduce

Put above snippet in script editor.

**Comment by miv391** [comment]
Shorter example which causes 208 errors in `v4.0.alpha11.official [afdae67cc]`

```gdscript
extends Node2D

func _ready():
	[1]
	.sort()
```

![kuva](https://user-images.githubusercontent.com/49998025/176991993-8220e811-0f47-4121-a8a8-c9a541270998.png)

Marking line 3 as erroneus with red color is also very annoying. In similar cases I have more than once tried to find what's wrong with the function definition line. I have tried to find if I have copypasted some invisivble control characters or maybe there already is a function with the same name. Then the error turns to be a false positive.

**Comment by Spartan322** [comment]
For:
```gdscript
extends Node2D

func _ready():
	[1]
	.sort()
```
I haven't checked what is causing the basis of the spam, but, and I checked this does apply to the original issue too, it seems that whatever spam is generated is duplicated because of
https://github.com/godotengine/godot/blob/344b42703bab951dbc8c0e7763740ac6b3dfad79/editor/plugins/script_text_editor.cpp#L445
and
https://github.com/godotengine/godot/blob/344b42703bab951dbc8c0e7763740ac6b3dfad79/editor/plugins/script_text_editor.cpp#L469
which will eventually make calls to
https://github.com/godotengine/godot/blob/344b42703bab951dbc8c0e7763740ac6b3dfad79/modules/gdscript/gdscript_editor.cpp#L113
with the same values. 

So the signal `"name_changed"` being connected  to `ScriptEditor::_update_script_names` means it'll call `ScriptEditor::_update_members_overview` which calls `ScriptTextEditor::get_functions()` which calls `GDScriptLanguage::validate` which starts the parser and is where the error is reported again.
