### ISSUE TITLE
id_pressed signal returns index if id takes more than 2 bytes

### ISSUE THREAD

**Issue by PoliPyc** [godotengine/godot#53423]
### Godot version

3.3.3 stable

### System information

Host: manjaro-desktop Kernel: 5.4.148-1-MANJARO x86_64 model: Intel Core i3-6100 bits: 64
Device-1: Intel HD Graphics 530 driver: i915 v: kernel 
Device-2: NVIDIA GM206 [GeForce GTX 960] driver: nvidia v: 470.63.01

### Issue description

`id_pressed` signal returns index value if `menu item` of `PopupMenu` node has custom id greater than `2147483647`

### Steps to reproduce

1. Create PopupMenu node
2. Create script file and add item with id higher than `2,147,483,647` for example:
```
func _ready():
  add_item('test', 3147483647)
  ```
3. Connect signal `id_pressed` and read passed value. For example:
```
func _on_BoxMenu_id_pressed(id):
  print(id)
  ```

**Comment by Ev1lbl0w** [comment]
That's just an issue with overflow, and this line prevents it from causing issues by changing the ID in that situation:

https://github.com/godotengine/godot/blob/198b49d8b589e88a5ae61fc8418ebf8890d2d1f7/scene/gui/popup_menu.cpp#L1338

Maybe there should be a warning for when overflow is happening, but other than that it doesn't look like a bug to me.

**Comment by PoliPyc** [comment]
I think that this should be mentioned in the documentation at least.

**Comment by zenasican** [comment]
Is it possible that this also applies to Godot 4 Beta 2? The id arg is int, so I expected the limit to be 9223372036854775807, per the int documentation.
I tried adding 870173055144603648, 866438331150536704 and 788420508952702976 but the ids are 0, 1409454080 and 2. If this is the expected behavior, I think it should definitely be added to the documentation.

Also.. total beginner, so I apologize for everything.

**Comment by Ev1lbl0w** [comment]
Not sure if `int` was changed in Godot 4 to be 64-bits, but from your experiments it looks like it's still 32-bits. (`866438331150536704 % 4294967296 = 1409454080`)

**Comment by zenasican** [comment]
In my case a workaround isn't too difficult. In any case, amending the doc and / or warning about it happening is something I would second. I'm not sure how to go about promoting such a change though. Thanks for the quick reply and the explanation.

**Comment by Ev1lbl0w** [comment]
I don't know if this situation is happening regularly in your projects, but if it is, adding a warning would spam the output constantly with it. 

If this scenario happens frequently, can you explain that scenario better, please?

Either way, it's a good idea to add this to the documentation, so I'll make a PR for that shortly.

**Comment by zenasican** [comment]
So I've been using Godot daily for about two years. The beta obviously just since it came out. And this never came up before. I don't know if it's possible to add a #warning-ignore because it's not something that the parser can pick up beforehand, I think.

The reason it is happening in this case is that I wanted to use an existing id from another database (namely.. nerd alert.. fantasy football league ids) in PopupMenu.add_item(). Since I know how the function defaults work, I try to setup the ids in that way (0,1,2,..), but here I can't change the existing ids. I've had some cases where the ids would go up to something like 10,092, but it's still well within the 32-bit limit.

I haven't tested it, but I assume it's the same for all add_item() funcs, i.e. ItemList and MenuButton.

My suggestion for the docs:

Note: The provided id mustn't exceed (insert limit here). 

To clarify further, one could add something like: This doesn't apply to "pure" ints. (There is probably a better word here than pure)
