### ISSUE TITLE
Animations of FBX models are imported incorrectly in Godot 3.3 and later

### ISSUE THREAD

**Issue by vetro21** [godotengine/godot#53544]
### Godot version

3.3.4 stable

### System information

Kde neon 5.22 user edition - Linux 5.11.0-34-generic

### Issue description

The animations in the AnimationPlayer are totally broken, and the only way to make them work is to import them with godot3.2.3 and then copy them into a godot3.3.4 project.
maybe it is better to create another report (tell me if I have to do it), but I want to add that I have noticed that in godot 3.3.4 the "Fps" parameter in the import tab has no effect on the number of key frames.

### Steps to reproduce

1) Download this: https://kaylousberg.itch.io/kaykit-animations
2) Import KayKit Animated Character_v1.1.fbx into a new godot 3.3.4 project (or any version higher than 3.2.3) 
3) Try to play some animation

For the workaround:
1) Download this: https://kaylousberg.itch.io/kaykit-animations
2) import KayKit Animated Character_v1.1.fbx into a new godot 3.2.3 project with the "import with separate animations" preset
3) Move the animations (file.anim) into a godot 3.3.4 project and add them to the AnimationPlayer
4) Play the imported animations

edit: I changed the link to the correct one to download the 3d model

### Minimal reproduction project

This is a godot 3.3.4 project and contains the model with the animations of godot 3.2.3 and godot 3.3.4: [AnimationBug.zip](https://github.com/godotengine/godot/files/7305778/AnimationBug.zip)
video:
[video_anim.zip](https://github.com/godotengine/godot/files/7306241/video_anim.zip)

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.
