### ISSUE TITLE
Why Not Gitter?

### ISSUE THREAD

**Issue by mohaalak** [godotengine/godot#5378]
in Gitter we can chat about issues , commits, and it all will be saved and can be retrieved easily , IRC is good but Gitter is great. :smiley:

**Comment by vnen** [comment]
It's always a problem to depend on proprietary solutions.

**Comment by punto-** [comment]
Why not Zoidberg?

**Comment by est31** [comment]
There is [mattermost](http://www.mattermost.org/). See also [why they made mattermost](http://www.mattermost.org/why-we-made-mattermost-an-open-source-slack-alternative/).

**Comment by mohaalak** [comment]
@djrm: it is a chat room based on godot we can add room for godot developers and also we can add rooms for guys that wants to ask question about godot .
@vnen : trello , github this sites has also proprietary functions.

**Comment by akien-mga** [comment]
This has been brought up several times already, personally I don't see anything positing in trying to split the community further. Most devs will stay on IRC because we're a bunch of nerds and like this outdated platform, so that would be yet another proprietary platform where we'd be supposed to hang out, give support, discuss stuff, etc. No thanks.

**Comment by mohaalak** [comment]
it was just an idea , let's use IRC like some nerds 😄
