### ISSUE TITLE
Path/PathFollow (+Z) wrong orientation

### ISSUE THREAD

**Issue by razcore-rad** [godotengine/godot#53837]
### Godot version

v3.3.4.stable.official [faf3f883d]

### System information

Ubuntu 21.04

### Issue description

The

```
Path
  - PathFollow
```

Setup orients on `+Z`, inverse from the convention. E.g. `Vector3.FORWARD` is `Vector3(0, 0, -1)` and `look_at()` orients on `-Z`, but `Path/PathFollow` orients on `+Z`.

See: 
- https://github.com/godotengine/godot/blob/5bc0e4081bbfa077567e1d94b760f81c63eb3392/scene/3d/path_3d.cpp#L120
- https://github.com/godotengine/godot/blob/5bc0e4081bbfa077567e1d94b760f81c63eb3392/scene/3d/path_3d.cpp#L128

### Steps to reproduce

1. Create the following tree:

```
Path
  - PathFollow
```

2. Set `PathFollow -> Rotation Mode` to `Oriented`.

---

Notice that `+Z` points forward on the curve. It should be `-Z`.

![Screenshot from 2021-10-15 15-53-18](https://user-images.githubusercontent.com/1177508/137489932-96759b8a-bf4a-40d0-8643-2fe042384f65.png)

**Comment by kubecz3k** [comment]
@Calinou since it's breaking compatibility maybe we should set milestone of this issue to 4.0?

**Comment by lukostello** [comment]
was just about to post this. I also find it odd that look_at Forward don't have a angle of 0 when using angle_to(). Makes me think what is currently RIGHT should be forward or angle 0 should be at the top. Probably wont happen because ages of convention. But if it were up to me I'd align those somehow.
