### ISSUE TITLE
Sometimes GraphEdit minimap doesn't show using minimap_enabled

### ISSUE THREAD

**Issue by a-v-o-dev** [godotengine/godot#53831]
### Godot version

3.3.4.stable

### System information

Ubuntu 16.04

### Issue description

There's a problem with showing the minimap after hiding it in special combination of using the built in `minimap_button` and setting `minimap_enabled` in code.

1. 

### Steps to reproduce

Test case:
Create a new project with a `Panel`, a `GraphEdit` and a `Button`.
Connect the `Button` pressed signal to a simple toggle script:

```
extends GraphEdit

func _on_Button_pressed () -> void:
	minimap_enabled = not minimap_enabled
```

Run the scene.
The minimap is visible and you can switch it on or off with the created `Button` (via script).
When the minimap is visible and you click onto the toolbutton `minimap_button` of the `GraphEdit`, the minimap isn't visible.
Clicking on the created `Button` (to enable the minimap via script) doesn't show the minimap, though the toolbutton `minimap_button` changes its color (depending on the theme).
With the correct combinations of clicks onto the 2 buttons the original state can be reached again.

### Minimal reproduction project

[Minimap.zip](https://github.com/godotengine/godot/files/7352468/Minimap.zip)

**Comment by akien-mga** [comment]
I can reproduce the issue, it should be fairly easy to fix for a new contributor. See `scene/gui/graph_edit.cpp` and how the `minimap_enabled` property and the `minimap_button` toggle are using slightly different methods, which can lead to this inconsistency.

**Comment by kleonc** [comment]
I'd say the real root cause here is that calling `BaseButton::set_pressed()` on a toggleable button results in not emitting its `pressed` signal (and emitting its `toggled` signal). For me that's counterintuitive and not consitent.

That's why changing `minimap_enabled`:
https://github.com/godotengine/godot/blob/3ca80031995c8f4d312fcb4c955b83163d30b656/scene/gui/graph_edit.cpp#L1632-L1635
never triggers calling `_minimap_toggled`:
https://github.com/godotengine/godot/blob/3ca80031995c8f4d312fcb4c955b83163d30b656/scene/gui/graph_edit.cpp#L1641-L1648
which is connected to `minimap_button`'s `pressed` signal:
https://github.com/godotengine/godot/blob/3ca80031995c8f4d312fcb4c955b83163d30b656/scene/gui/graph_edit.cpp#L1856
What triggers `_minimap_toggled` are only "real clicks" on the `minimap_button`.
So if `minimap` was hidden by clicking `minimap_button` then its `visible` property is set to `false` until `minimap_button` is clicked again. Clicking user's button with callback:
```
func _on_Button_pressed () -> void:
	minimap_enabled = not minimap_enabled
```
never changes `minimap.visible` property. It can toggle minimap drawing when `minimap.visible` is `true` just because of this check:
https://github.com/godotengine/godot/blob/3ca80031995c8f4d312fcb4c955b83163d30b656/scene/gui/graph_edit.cpp#L964-L967


Changing the code by connecting to `toggled` instead of `pressed`:
```
 void GraphEdit::_minimap_toggled(bool p_pressed) {
 	if (is_minimap_enabled()) { 
 		minimap->set_visible(true); 
 		minimap->update(); 
 	} else { 
 		minimap->set_visible(false); 
 	} 
 } 
```
```
minimap_button->connect("toggled", this, "_minimap_toggled"); 
```
should make it work (didn't actually test it). However, as I've already mentioned I don't think that would solve the real inconsistency/problem here. I do think `pressed` should be emitted when calling `BaseButton::set_pressed()` in the first place.

**Comment by pycbouh** [comment]
> That's why changing `minimap_enabled` never triggers calling `_minimap_toggled`

That's an oversight on my part, because I just took the same approach that was already used for enabling snap. Problem is that snap only calls `update()`, which we call either way, and minimap is more involved. We just need a call to `_minimap_toggled()` in between the two lines of `set_minimap_enabled`, that's it.

> I do think `pressed` should be emitted when calling `BaseButton::set_pressed()` in the first place.

That may not be a good idea, depending on what you want to achieve. You can always emit the signal on behalf of the button to work around the current behavior, but you would not be able to prevent the signal emission if you needed, if the behavior was to always emit on set. So at the moment, developers have less automation, but more control. Which is, IMO, desirable.

**Comment by kleonc** [comment]
> That may not be a good idea, depending on what you want to achieve. You can always emit the signal on behalf of the button to work around the current behavior, but you would not be able to prevent the signal emission if you needed, if the behavior was to always emit on set. So at the moment, developers have less automation, but more control. Which is, IMO, desirable.

If auto-emitting signals is indeed not desired then it's still not consistent since calling `BaseButton::set_pressed()` can trigger emitting `toggled` signal (if the button is toggleable) but it will never trigger emitting `pressed` signal. I think that calling `BaseButton::set_pressed()` should trigger either both `pressed` and `toggled` or neither of them. In the latter case I'd be fine with no auto-emitting.

However, it seems in #48502 `BaseButton::set_pressed_no_signal()` was added (exactly for the use case you're talking about?:thinking:). So with such method in place I'd say it makes even more sense to make `BaseButton::set_pressed()` trigger emitting `pressed`.

Currently it's like this:
|| `BaseButton::set_pressed()`| `BaseButton::set_pressed_no_signal()`|
|-|:---:|:---:|
|can emit `BaseButton::pressed`|✖|✖|
|can emit `BaseButton::toggled`|✔|✖|
|can emit `ButtonGroup::pressed`|✔|✖|

and I'm saying it should be like this:

|| `BaseButton::set_pressed()`| `BaseButton::set_pressed_no_signal()`|
|-|:---:|:---:|
|can emit `BaseButton::pressed`|✔|✖|
|can emit `BaseButton::toggled`|✔|✖|
|can emit `ButtonGroup::pressed`|✔|✖|

**Comment by emcguirk** [comment]
Has anyone done any work on this issue? If not, I would be happy to take a crack at it.

**Comment by pycbouh** [comment]
> Has anyone done any work on this issue? If not, I would be happy to take a crack at it.

Feel free, I think I mention a solution somewhere up there.
