### ISSUE TITLE
Change comment color in GDScript editor for additional readability

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5393]
The current comment color has poor contrast, and as a result isn't very readable (or pretty, IMHO).

Of course, everybody is going to have their own preferences here, but I think something like this is already more readable:

![Tango dark](https://pawelbx.github.io/emacs-theme-gallery/screenshots/dark/tango-dark/el.png)

In Godot's case, this color is too similar to the color for keywords, but something like this:

![Badger](https://pawelbx.github.io/emacs-theme-gallery/screenshots/dark/badger/el.png)

or a light shade of grey like this:

![Bubbleberry](https://pawelbx.github.io/emacs-theme-gallery/screenshots/dark/bubbleberry/el.png)

would also be more readable.

What do you think about it?

**Comment by vnen** [comment]
I agree, the default comment color is not distinctive enough, it looks like normal code.

**Comment by neikeq** [comment]
I like the default color :( Well, I don't really care since I can change it :P

**Comment by paper-pauper** [comment]
@neikeq Sure, but the ideal is to offer defaults that appeal to the lowest common denominator. 

Godot looks really good, fortunately, but the few changes that can be made here and there to make it look even better and improve usability (which improves user satisfaction overall) are totally worth it.

Comments need to be understated and need to stick out at the same time. This balance is very hard to reach with dull colors (as is the case right now) or bright colors. The last theme I posted IMHO nailed it, because you don't get the impression that comments are unimportant, but it's also very clear that they aren't code.

I am too compromising about it - if I had to say what I really think, I would say that Godot should adopt a less quirky color scheme by default, but I think the current theme doesn't look too bad as long as usability is kept in check.

**Comment by bojidar-bg** [comment]
@Calinou Maybe you would like to present us a whole new and better color theme? ^^

**Comment by nunodonato** [comment]
is this still relevant?

(current status in v3, looks good to me):
![screenshot from 2017-06-02 16-08-23](https://cloud.githubusercontent.com/assets/1642015/26731968/c77d0b5e-47ad-11e7-8f99-13c03c8ff911.png)

**Comment by Calinou** [comment]
Comments could be made a tad brighter (like, 3-5 shades brighter out of 255), but they're fine to me right now (on most displays).
