### ISSUE TITLE
Rust as a scripting language

### ISSUE THREAD

**Issue by sunnystormy** [godotengine/godot#5394]
I saw that there's a ticket open for C# (*gag*), and wanted to know if there was any interest in utilizing Rust as a scripting language?

I know Mozilla just gave the Godot Engine team money for a WebGL2 port, and given that they're already updating their render engine to use Rust, perhaps we should get on the same bandwagon?

I saw that the "newcomer" argument was also made in the C#-related thread. Since Rust is a more modern language that embraces multiple programming paradigms, wouldn't this be more accommodating to adopt?

**Comment by reduz** [comment]
you can make a module for this, it shouldn't be that hard

**Comment by sunnystormy** [comment]
I can? Where do I start?

**Comment by reduz** [comment]
you should try to join #godotengine-devel and hang around there

**Comment by sunnystormy** [comment]
How do I join that?

**Comment by J08nY** [comment]
We have an irc channel #godotengine-devel on irc.freenode.net

**Comment by sunnystormy** [comment]
Cool! I'll go check it out.

**Comment by dagit** [comment]
I see this is closed now, but was any progress made on creating a module to use Rust?

**Comment by kubecz3k** [comment]
@dagit I believe there is no one interested to the point to actually start working on Rust language support.

**Comment by sunnystormy** [comment]
@kubecz3k Not true. I still believe this is a valid language to support, but received very little feedback when asking about how to accomplish this. I think, given the proper information and resources, we can get this done. I don't think supporting vendor-based languages like C# is the right way forward. It's just a superficial attempt to woo Unity developers. Why not innovate instead of emulate?

**Comment by neikeq** [comment]
@sunnystormy This should be possible with the C API when it's ready. Basically, you want to compile your rust code as a shared library and use it from Godot. You could use `extern "C"` with every method you want to expose or you could create an API similar to `ObjectTypeDB` and just use `extern "C"` with a few of its methods, like `call_method(instance, name, args)`.

The problem is that calling `bind_method` or `register_type` on the rust side would be annoying (it would be similar to how Object derived types are written in C++). In the D Language I would just add an attribute to the methods I want to bind (e.g: `@ScriptMethod void doSomething() {}`) and then use a mixin to automatically generate the binding code at compile time. Does Rust have something similar?

**Comment by sunnystormy** [comment]
@neikeq Good to know. To the best of my knowledge, Rust's FFI would be the only way to create the kind of communication that you're talking about. I'm aware of some of the benefits of DLang, but I believe it's designed to work differently than Rust under the hood. As a result, there may be some language/library deficiencies between the two. Please keep this ticket updated as the C API progresses. Thank you. :)

**Comment by neikeq** [comment]
I found this: https://doc.rust-lang.org/book/compiler-plugins.html
I am not sure if it supports code generation.

**Comment by sunnystormy** [comment]
Hmm... very interesting! :)

I'll take a look at this in the meantime to see if it will work.

**Comment by jpernst** [comment]
Coincidentally, I also briefly attempted this, albeit months ago before the commitment to other language support was published. I eventually let it drop since I felt I was working against the ethos of the engine by trying to add another language into it, and binding C++ is always high-friction from any langauge. If there is in fact a C api planned, that will make things immensely easier for sure.

@sunnystormy Keep in mind that the rust plugin interface is unstable and will probably remain so for a long time, so any user would have to use rust-nightly, and the interface will break frequently (see serde for how often that happens, in my experience it was every couple weeks or so). Another alternative is to use a cargo build script that performs the binding generation. That has the downside of complicating the build slightly, but will work on stable.

Another thing I was attempting to do was hook rust into godot's internal allocator to help reduce heap fragmentation from competing allocators, thankfully rust makes doing this quite easy and I managed to get it all linking (not thoroughly tested though, and there were still unresolved questions about allocation alignment). However, godot also provides the `DynamicPool` allocator IIRC, and I never could quite discern it's exact purpose or what to do about it.

Now that my two largest concerns for rust bindings (engine direction and C api) are addressed, I might be interested in contributing to this again. Let me know if you're looking to collaborate.

**Comment by sunnystormy** [comment]
@jpernst I'm all for collaboration! And I agree with your sentiment about using Rust Nightly. I don't think we want to make the process of incorporating (or using the language) painful if it can be avoided. Once this C API is finished, let's get together and figure this out. :)

**Comment by jpernst** [comment]
@sunnystormy Sounds good; for now I'll start poking around in the code to see what's what.

**Comment by d9n** [comment]
Hey, it looks like there is a [C API for Godot scripting now](https://godotengine.org/article/dlscript-here). Do you know if there is any current work on writing Rust bindings for Godot at this time?

**Comment by dagit** [comment]
This appears to be the repo with the C headers: https://github.com/GodotNativeTools/godot_headers

I glanced at it. I don't see anything crazy or complicated in the parts I looked at. I would guess that it should be straight forward, but there is a fair bit in there so it's more than an afternoon's work too.

**Comment by karroffel** [comment]
You guys missed [the Rust bindings.](https://github.com/GodotNativeTools/rust_bindings)

**Comment by swarnimarun** [comment]
Are there any updates on the rust scenario??

**Comment by karroffel** [comment]
@mateusfccp there are open issues on the Rust bindings repo, new people wanting to help out are always welcomed! (there's also #godotengine-gdnative on freenode)
