### ISSUE TITLE
AnimationPlayer + AnimatedSprite: Keyframing a frame no longer increments the frame count for the next step

### ISSUE THREAD

**Issue by ranmaru90** [godotengine/godot#5422]
**Operating system or device - Godot version:**
Windows 10 Pro. Latest compile from GitHub repo.

**Issue description** (what happened, and what was expected):
When keying a frame on an AnimatedSprite into a timeline in an AnimationPlayer, the key button beside "Frame" has lost the ability to increment the frame by 1 and move on to the next step in the timeline after a click, automatically.

**Steps to reproduce:**
1. Make a scene and add an AnimatedSprite node.
2. Edit "Frames" on the AnimatedSprite node and add SpriteFrames.
3. Add some sprites into the SpriteFrames, maybe 3 - 5 or more.
4. In the same scene, add an AnimationPlayer node, click on it and create a new animation to start keying into the timeline.
5. Now key the "Frames" on the AnimatedSprite node into the timeline.
6. Notice that whenever you click on the key button beside "Frame", it doesn't get incremented by 1 and move to the next step in the timeline automatically anymore. 

This button used to have this ability, so even if we have hundreds of frames, we can just mash click this key button beside "Frame" and all the frames on the AnimatedSprite node get keyed into the timeline really fast.

**Comment by akien-mga** [comment]
In 2.0.3 the feature used to work for both Sprite and AnimatedSprite: ![spectacle c31591](https://cloud.githubusercontent.com/assets/4701338/16361413/98857072-3b90-11e6-8323-101fb8f5f4b7.png) ![spectacle b31591](https://cloud.githubusercontent.com/assets/4701338/16361415/a8bc9b00-3b90-11e6-9100-86e8cc9e27ad.png)

In the current master branch, it only works for Sprite:
![spectacle jd3201](https://cloud.githubusercontent.com/assets/4701338/16361514/39cda86c-3b93-11e6-986f-85c8ab214b36.png) ![spectacle cs3201](https://cloud.githubusercontent.com/assets/4701338/16361516/49fec158-3b93-11e6-9a87-259d991b18ce.png)

I guess it might be due to the recent AnimatedSprite rewrite. @reduz Is that intended, or a regression?
