### ISSUE TITLE
High CPU usage in Project Manager

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#54291]
### Godot version

8c162f4

### System information

W10

### Issue description

When I open Godot, its CPU usage is between 10-15% while inside Project Manager. It falls to 0 when I open a project.

### Steps to reproduce

1. Run Godot
2. See your CPU being melted for no reason

**Comment by ibrahn** [comment]
Testing on my machine, most of this seemed to be down to the 2D physics server.

The short version is we can deactivate this server and a couple of others, as we do in the editor here:
https://github.com/godotengine/godot/blob/6b0b1a4c042175190381737e3000027ef912e6cb/editor/editor_node.cpp#L5783-L5786

PR for that #54422 if you want to give it a test.

The longer version:
[Popups](https://docs.godotengine.org/en/latest/classes/class_popup.html#class-popup) are [Viewports](https://docs.godotengine.org/en/latest/classes/class_viewport.html#class-viewport) and Viewports have their own [World2D](https://docs.godotengine.org/en/latest/classes/class_world2d.html#class-world2d).
Each World2D adds an iteration here:
https://github.com/godotengine/godot/blob/6b0b1a4c042175190381737e3000027ef912e6cb/servers/physics_2d/godot_physics_server_2d.cpp#L1250-L1255
and `GodotStep2D::step` is not a cheap function, even on an empty world.
https://github.com/godotengine/godot/blob/6b0b1a4c042175190381737e3000027ef912e6cb/servers/physics_2d/godot_step_2d.cpp#L127

This all becomes an issue with something like the Project Manager because there are several PopupMenus.
We can fix it here by turning off the physics server in the Project Manager, but it's probably worth looking into further as PopupMenus being expensive to have lying around in a game is not ideal.

**Comment by KoBeWi** [comment]
Seems fixed.
