### ISSUE TITLE
FileSystemDock incorrectly sorts underscore

### ISSUE THREAD

**Issue by jmoon1506** [godotengine/godot#54341]
### Godot version

4.0 dev (157cba393)

### System information

macOS 12.0.1

### Issue description

Files and folders beginning with underscore are incorrectly sorted alphabetically in FileSystemDock.

Note: GDscript string arrays are still sorted correctly, so it's probably not an issue with `NaturalNoCaseComparator `.

### Steps to reproduce

File starting with underscore is at bottom, while all other symbols at top.

![Screen Shot 2021-10-28 at 12 31 21 AM](https://user-images.githubusercontent.com/21185262/139209244-a715797e-5a32-4a81-a6ab-491ede5e3977.png)

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7432135/test.zip)

**Comment by zedutch** [comment]
@akien-mga FileInfo already uses the NaturalNoCaseComparator by default though so explicitly sorting with that comparator doesn't fix this.  
I think this has to do with the fact that `_` has a higher ASCII number than alphanumerical characters while other symbols (like `!`, `+`, `-`) have a lower ASCII number. The same thing e.g. also happens if the filename starts with `^`, `[`, `]`, or `/` which are also all symbols that come after the alphanumerical symbols in the ASCII table. So we'd need to explicitly specify an ordering for symbols <> alphanumerical characters in NaturalNoCaseComparator to fix this I think. If this is actually something that needs fixing, I guess that depends on what you consider the "right" order for symbols like this.

**Comment by akien-mga** [comment]
I don't have a strong opinion on what the order should be, it's bound to be arbitrary one way or another.

Here's what happens in KDE's Dolphin file manager for example:
![Screenshot_20211104_115208](https://user-images.githubusercontent.com/4701338/140301615-ecd1c016-ee34-4475-9541-781744447903.png)

I'm fine keeping things as is if the current arbitrary order is not better or worse than a possible alternative. I just wonder about this:

> Note: GDscript string arrays are still sorted correctly, so it's probably not an issue with NaturalNoCaseComparator .

Might need checking where this difference comes from.

**Comment by zedutch** [comment]
> >Note: GDscript string arrays are still sorted correctly, so it's probably not an issue with NaturalNoCaseComparator .
>
> Might need checking where this difference comes from.

Strings don't seem to use NaturalNoCaseComparator, they use a custom 'is_str_less' function which just compares the char's directly: [https://github.com/godotengine/godot/blob/master/core/string/ustring.h#L492](https://github.com/godotengine/godot/blob/master/core/string/ustring.h#L492).  
They don't have the case-insensitiveness or the exceptions for `.` and digits that NaturalNoCaseComparator has but other than that they are sorted the exact same: `["abc", "Aba", "+abc", "_abc", "-abc", "[aba"].sort()` leads to: `+abc, -abc, Aba, [aba, _abc, abc`, since it's sorting them by their ASCII values.

**Comment by akien-mga** [comment]
Thanks for checking! Seems to me that there's no bug to fix then, the current behavior makes sense.
