### ISSUE TITLE
Inspector does not display properties without category 

### ISSUE THREAD

**Issue by 4d49** [godotengine/godot#54410]
### Godot version

v4.0.dev.custom_build [61786f803]

### System information

Windows 10

### Issue description

If script usages `_get_property_list()` method Inspector does not display properties without custom Category.

### Steps to reproduce

Create a script with a `_get_property_list()` method without a category. 

### Minimal reproduction project

[demo-project.zip](https://github.com/godotengine/godot/files/7445846/demo-project.zip)

**Comment by Calinou** [comment]
@4d49 Does this occur in 3.3.4 or 3.4rc?

**Comment by 4d49** [comment]
> 
> 
> @4d49 Does this occur in 3.3.4 or 3.4rc?

No, 3.4 parse properties like Script Variable.

![изображение](https://user-images.githubusercontent.com/8208165/139535356-25e85f19-8ca1-4845-99e4-f76781bff629.png)

**Comment by object71** [comment]
Seems like a few months ago someone added a change so that the "Scripted Variables" values in the inspector are moved to a category with the name of the script (for example instead of "Scripted Variables" you will get "test.gd"). You can notice that regular exported variables are shown under another category.

Problem that I noticed in the code is (```EditorInspector::_update_script_class_properties()```)

1. That it gets as an argument the script variables exported + custom from the override method ```_get_property_list```
2. Locates the "Script Variables" category
3. Checks from which script they come and adds them under a category with the script name <<<--- here it checks against only the exported variables
4. Clears all variables under the "Script Variables" category 

@Calinou Here my question is - do we want them categorized as the exported variables under a category with the script name or should we just limit what gets deleted under "Script Variables" in the last step?

**Comment by object71** [comment]
@4d49 You can try with my pull request. I made it work correctly for GDScript and also extended scripts too.

**Comment by rosshadden** [comment]
I just ran into this as well. @object71 it seems you have closed your PR. Is there something that superseeds it?
