### ISSUE TITLE
"Save all Scenes" gives unclear prompt for [unsaved](*)

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [godotengine/godot#54425]
### Godot version

6b0b1a4c042175190381737e3000027ef912e6cb

### System information

Windows 10

### Issue description

![image](https://user-images.githubusercontent.com/19283945/139539783-5ac09d87-6081-4ebe-89f1-69a0f3f2dd37.png)
I would guess this has to do with #53705.
Outstanding changes to scenes that had been saved earlier are saved correctly.

This is different form Godot 3.3, where in the same conditions the prompt from the screenshot isn't shown, and the Editor, as far as I can tell, silently does nothing with "[unsaved](*)" scenes.

### Steps to reproduce

Create a new project or open an existing one.
Create a new Scene.
Try to use the "Save all Scenes" functionality.
![image](https://user-images.githubusercontent.com/19283945/139539862-2e9e78c1-9c57-4cdb-ba21-f7d0e937f89d.png)

Outstanding changes to scenes that had been saved earlier are saved correctly.

### Minimal reproduction project

Any project.

**Comment by MatteoPiovanelli-Laser** [comment]
Possibly, the message in the popup should tell that the scenes need to first be saved by themselves. If I understand the code from the PR I linked, the only condition that would cause that warning to show is that there are one or more unsaved(*) scenes: were that the case, changing that text would probably make everything clear? Am I missing something

I would wish to see, for each "[unsaved](*)" scene, a "Save Scene As..." prompt.
![image](https://user-images.githubusercontent.com/19283945/139540193-3c95eb03-a228-4702-9991-7f8138388133.png)
I don't know how hard that would be.

**Comment by e8newallm** [comment]
The original reason for these changes was for issue #52078 where renaming a directory (Both in the editor and outside) that you've already saved a scene into will also cause saving to fail. For this issue at least, it's very important that the user is informed so they don't save and close and not have their scene saved properly. 

It could potentially be fixed by simply skipping scenes that don't have a path already defined, however it could come across as inconsistent for some inability to save is skipped while others show an error (Granted the issue that triggered all this is an edge case that probably won't happen often). I don't think the proposed idea of popping up a "save as" box for each unsaved scene would work, as if you have multiple unsaved scenes it wouldn't be possible to indicate which scene is being saved when.

**Comment by MatteoPiovanelli-Laser** [comment]
I guess a more verbose popup explaining that there wasn't really an error would be helpful already.

**Comment by golddotasksquestions** [comment]
I get this same popup since 3.4. and it's incredibly annoying.

I often create new scenes to try stuff, scenes I usually don't want to save. But when I then run any other of my open saved scenes I have to click away this pop up every time. It's super annoying. 

Can we please have this revert to the behavior of 3.3.4?
