### ISSUE TITLE
3D editor freelook only recognizes the first key assigned to a shortcut

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#54469]
### Godot version

4.0.dev (1aef3a42b)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 470.74)

### Issue description

Related to https://github.com/godotengine/godot/issues/54460.

Following the merge of https://github.com/godotengine/godot/pull/51273, the editor only recognizes the first key assigned to a shortcut for freelook shortcuts (even if none of the keys are marked as physical).

Here, only <kbd>W</kbd> will be used to move forward while freelook is active:

![image](https://user-images.githubusercontent.com/180032/139602568-ea447cc8-3c94-4a94-9f30-c9e46f050898.png)

Here, only <kbd>Up</kbd> will be used to move forward while freelook is active:

![image](https://user-images.githubusercontent.com/180032/139602585-b8c7ad79-6853-440b-a534-80d9ab3c8a05.png)

This does **not** occur with other shortcuts, such as the 2D editor's **Always Show Grid** shortcut:

![image](https://user-images.githubusercontent.com/180032/139602644-831d0860-5451-4d82-a123-3582a97a3d82.png)

Here, both <kbd>#</kbd> and <kbd>L</kbd> work as expected.

This is the part of the code that handles 3D editor freelook shortcuts: https://github.com/godotengine/godot/blob/1aef3a42b234b86c5db21d5a64509453e6bf145c/editor/plugins/node_3d_editor_plugin.cpp#L2606-L2623

### Steps to reproduce

Open the **Editor Settings**, go to the **Shortcuts** tab and add a second shortcut for one of the freelook movement keys.

### Minimal reproduction project

N/A

**Comment by EricEzaM** [comment]
The `is_shortcut_pressed` method is defined specifically for the 3D editor. See the method below, this is what would need to be changed.

https://github.com/godotengine/godot/blob/1aef3a42b234b86c5db21d5a64509453e6bf145c/editor/plugins/node_3d_editor_plugin.cpp#L2557-L2575

**Comment by akien-mga** [comment]
Soudns like this `is_shortcut_pressed` method might not be needed at all? It might predate better shortcut handling and now it's counter productive.

**Comment by EricEzaM** [comment]
@akien-mga From memory I believe this is because it is checking the shortcut event(s) _without_ having an event available from `_input(Ref<InputEvent>)`, etc, so it needs to check it "manually" using the `Input` singleton.

I think you are on the right track though - this could potentially be solved by putting this checking logic into the `unhandled_key_input()` method, and updating an instance variable called `Vector3 freelook_velocity`, then in the `update_freelook` method, just use this vector instead of the `direction` vector which is created locally.

This would work in my head and I've explained the logic a bit here, so I will mark this as a good beginner issue and see if anyone gets to it before I do 😄

**Comment by EricEzaM** [comment]
Hmm ok, this is slightly more complex than I first though.

`_input` methods are no good because they include keypress echoing, So there is a short delay between when you first press a key, and the next event if you hold it down (the echo).

What is needed is kind of like putting `Input.is_action_pressed()` inside `_process()` in a Godot game. This is basically what is done now, but there is no shortcut equivalent of `is_action_pressed()`. There is no method in general inside `Input` to check if a certain `InputEvent` is currently pressed - there is only `is_key_pressed()`.  (**Side note:** The input singleton only keeps a record of keys pressed by using `event->get_keycode()`, won't this also screw up if a physical keycode is used? Not sure what the interaction with physical keycodes is here. Related to #54460)

Another pitfall of the current implementation is that if you set the freelook shortcuts to include a modifier, they also won't work since it only checks if the keycode is pressed. 

Maybe some method in the `Input` singleton needs to be added to check if a particular event is currently pressed? This would require storing every event that comes through though, and removing it from storage when it is released. Doesn't sound good.

Overall I'm not sure what to do with this - seems tricky. Could we somehow leverage the Input Actions system, since that has pressed-checking already implemented? Like, convert those shortcuts to internal, editor-only hidden actions? Not sure how that would work but I might look into it.
