### ISSUE TITLE
Ability to fix dependencies instead of showing a warning.

### ISSUE THREAD

**Issue by TheoXD** [godotengine/godot#545]
After copying a scene from one place to another you get tons of "Resource Not Found" in a textedit box. It would be useful to have them as a list with ability to replace them. After replacement, mark green if resource extension matches, yellow if unsure (.res, xml) and red if the types do not match.

**Comment by AlexHolly** [comment]
So i think it is now implemented but still buggy? I saved all my .scn as .xscn and had problems with opening the main.scn because it is using the renamed .scn files. Fixing a dependency worked only on one scene. Maybe it broke after i renamed two scenes at once? So when i choose the new .xscn it still shows the .scn as red marked and nothing changes... no error messages

**Comment by akien-mga** [comment]
Closing as fixed, it has been implemented for 1.1 or 2.0. It's not necessarily perfect yet, but then new issues should be open against it that describe the behaviour in the current master branch.
