### ISSUE TITLE
Crash on launch in windows 10: regression from Windows high contrast themes support

### ISSUE THREAD

**Issue by Alex-doc** [godotengine/godot#5452]
**Operating system or device - Godot version:**
OS: Windows 10 32 bits
CPU: Intel Core i3-2350M
Graphics: Intel HD 3000 

Godot Version: since [85a5290](https://github.com/godotengine/godot/commit/85a5290ee8a4c95be19f086181379330baf0deed)

**Issue description** (what happened, and what was expected):
Crash on launch.

**Steps to reproduce:**
- Just launching the application.

Callstack: http://imgur.com/wy0egqm

**Additional notes**
- Not sure why, but reverting the commit makes it work again.

- Doesn't happen on my other machine (Win10 64 bits i7 GTX760)

**Comment by akien-mga** [comment]
Ping @RandomShaper as it's a regression from 85a5290e.

**Comment by RandomShaper** [comment]
I'm researching…

**Comment by RandomShaper** [comment]
It seems like Intel HD 3000 (and other models) have compatibility issues with Windows 10.

First of all, make sure you have the latest version of your graphics card drivers.

In one forum an user suggests to try the workaround in [this video](https://www.youtube.com/watch?v=t9xnmBIM-fg).

Another good try would be, since the manifest is telling Windows that Godot supports Windows 10 and that causes the issue, run in in a compability mode for Windows Vista or 7 at most.

Please tell us the outcome.

**Comment by RandomShaper** [comment]
Hmm… Intel [seems to be supporting only 64-bit Windows 10](https://downloadcenter.intel.com/search?keyword=hd+graphics+3000) for that card.

Maybe the manufacturer of your computer provides additional drivers, but my guess is your computer (like mine) is from several years ago (Vista/7 era) and you'll be lucky if everything works under Windows 10 since there will not be updated vendor-provided drivers.

**Comment by akien-mga** [comment]
If that's the case it kind of sucks for us, as MS is forcing its Windows 10 upgrade on all users without even asking their opinion, so most people with older laptops on Vista/7 are now on Windows 10 or will soon be, unless they're really clever and manage to avoid MS's incessant nudges and disguised upgrade attempts.

**Comment by Alex-doc** [comment]
The videocard settings doesn't seems to have the option shown in the video.
Compatibility mode doesn't seems to fix, the only way so far is by recompiling without the commit.

I think we should find a way(no idea how) to define how much the problem could be diffused(hopefully is just happening to me)

**Comment by RandomShaper** [comment]
Alex, maybe you know I suggested the same manifest thing to the Blender team because it also didn't work under a high contrast theme.

Could you do another test?

It'd be to download Blender and follow what I explained in [a post on their bug tracker](https://developer.blender.org/T42545#379112). It's to check whether Blender starts up in your machine with the modified manifest.

**Comment by RandomShaper** [comment]
Well, GDevelop already bundled it in [their last release](https://github.com/4ian/GD/releases/tag/4.0.92) so you could just download it and check if it works for you…

Thanks in advance!

**Comment by RandomShaper** [comment]
@Alex-doc, another thing you could try is installing the driver provided for Intel for Windows 8 by running the installer in compatibility mode. This has helped some users of different products.

**Comment by Alex-doc** [comment]
GDevelop seems to work.
Blender doesn't work, it thinks there is no hardware 3D acceleration and no OpenGL 2.1

**Comment by RandomShaper** [comment]
Alex, thanks for testing!

At this point we could extract a conclusion: it's a driver issue. Then, the question: should Godot keep going forward so it can be fully compatible with high contrast themes or should it keep supporting legacy graphics cards at the expense of new desired, features?

Well, that looks a bit biased, but is not intentional.

**Comment by Hinsbart** [comment]
Mhh, IMO the hd3000 generation of GPUs aren't old enough to not support them anymore.
I think a _lot_ of users are running this kind of hardware so it's not exactly "legacy".

That said, if there are only recent drivers for 64bit windows versions and it is in fact a driver issue, then I'm all for keeping the high contrast support.

**Comment by akien-mga** [comment]
> IMO Godot should not be limited by Intel not providing updated drivers, I'm for keeping the high contrast support too.

I'd say it's Microsoft's fault for proposing (or forcing, depending on the situation) users to move to a much newer OS version without checking with its partners if they will be able to provide proper drivers. :)

**Comment by akien-mga** [comment]
Another user with Intel HD 3000 having issues on Windows 10 since "July", that does sound like this bug: https://godotengine.org/qa/5933/godot-2-1-alpha-stoped-working-in-july

It would be nice to have someone from Intel have a look at this directly :)

**Comment by akien-mga** [comment]
Another user on Facebook with Intel HD 3000 for whom 2.1-beta crashes on start: https://www.facebook.com/groups/godotengine/permalink/804118753058054/?comment_id=804169426386320

I'm starting to fear we'll have to revert the patch temporarily until MS/Intel fix their crappy drivers for Windows 10.

**Comment by akien-mga** [comment]
Another one: https://www.facebook.com/groups/godotengine/permalink/804568179679778/

As I feared, there are apparently way more users on Windows 10 32-bit with Intel HD 3000 as we would like, since MS forced its upgrade on low-end hardware. So I think it's not worth having this patch for now if it means that Godot is broken for a non-negligible part of our user base.

Unless there are strong objections I'll revert the patch before the next official beta snapshot.

**Comment by akien-mga** [comment]
Sorry, given the number of affected users (among those testing the beta, which are just a small subset of our user base), I don't think we can ship 2.1 with this patch, the feature is interesting but not worth breaking the engine for many users with GL 2.1+ compatible hardware.

Hopefully MS/Intel will fix their buggy drivers and we can reintroduce the patch for 2.2.

**Comment by RandomShaper** [comment]
No offense!

It's a pity but sometime we will be able to reintroduce it.
