### ISSUE TITLE
Painting TileMap with terrain with unset peering bits does not work as expected.

### ISSUE THREAD

**Issue by xorborg** [godotengine/godot#54587]
### Godot version

v4.0.dev.custom_build[78931aa04]

### System information

Linux

### Issue description

I have setup a terrain set with a single terrain like this:
![tileset_setup](https://user-images.githubusercontent.com/33593060/140285833-8c4246b7-bb49-4f76-813b-c6d7b53d6d43.png)

The set peering bits are red. If I try to paint this terrain in [78931aa04] it does this:

![new_tilemap_edit](https://user-images.githubusercontent.com/33593060/140286036-8987fdcf-25d8-4959-92ed-2881b0ad0c59.gif)

While back in [d9d529636] it looked like this:

![old_tilemap_edit](https://user-images.githubusercontent.com/33593060/140286897-16668596-9745-493c-9fc1-13750e3e12d7.gif)

Using a terrain set with multiple terrains where all peering bits are set to a terrain seems to working fine though.

### Steps to reproduce

Open the attached minimal project and paint the terrain.

### Minimal reproduction project

[terrain_test.zip](https://github.com/godotengine/godot/files/7473631/terrain_test.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by himaghnam** [comment]
got the similar issue, single tile does not work like autotile, i was trying to have the platformer tileset

**Comment by himaghnam** [comment]
need selected tile rotation too - Rotating a tile before painting

**Comment by AttackButton** [comment]
Got this in the new alpha 1. 

> need selected tile rotation too - Rotating a tile before painting
Is this a workaround?

**Comment by nhjansen** [comment]
The issue is that the 'paint' part for the terrain peering isn't supposed to match the actual area of land, it's just a visual indicator of which direction it's going to check for another tile. So your upper left tile should want to see terrain to the bottom, bottom right, and right. So you would need three red squares active so that it requires terrain on those three sides. As of now, the upper left tile will be applied when you ONLY have another tile painted to the bottom right of it. Make sense?
