### ISSUE TITLE
Vulkan: Material colors appear washed out

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#54628]
### Godot version

4.0.dev eeec0f40457a985092055dbcd463e51aa95e3b41
Still here in ce634e03d5bbfe7f92b6285a79e8c0ce29649642

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description

When importing a GLB file into Godot, colors are off, they look faded.

This is an image rendered inside Blender:
![image](https://user-images.githubusercontent.com/6616005/140516150-f6edcb18-7b2e-4498-bb40-f7a2e168cfbc.png)

This is the default material color from inkscape:
![image](https://user-images.githubusercontent.com/6616005/140516191-09196719-df8d-4604-8920-6467bc86f6bd.png)

This is the result on godot after import (sky is only white)
![image](https://user-images.githubusercontent.com/6616005/140518299-9c7f1fad-3e91-4358-ab57-80338ba4e062.png)

Note, this is a regression, I imported the very same Mesh on Godot 3.1, using a simple white color and the colors were great.

### Steps to reproduce

1. Open Blender, create a cube with a red Material
2. Export it as a GLB file
3. Open Godot, create a new project
4. Import the GLB file, the Red color is now Orange.

### Minimal reproduction project

Create a new project, then import this 3 Mesh.
[plateau.glb.zip](https://github.com/godotengine/godot/files/7486321/plateau.glb.zip)

Or you can fork this repository, since the game I'm working on is supposed to be a FOSS game:
https://github.com/binogure-studio/real-estate-online

**Comment by fire** [comment]
I am not sure which of these things it is yet:

1. Albedo vertex colors in srgb are incorrect in gltf import
2. Preview world environment is not kept in game (expected)
3. Other errors in gltf import

**Comment by xsellier** [comment]
1. Albedo looks ok in Godot (right color)
2. Doesn't render well in the editor, in preview mod, or even exported.
3. No idea

**Comment by fire** [comment]
![glb-colors-wrong-unshaded](https://user-images.githubusercontent.com/32321/140540939-4cdcc485-dc70-4e5d-ab5b-dd4388c5d9ed.png)

I can recreate the error.

**Comment by Calinou** [comment]
Possibly related to https://github.com/godotengine/godot/issues/48573. Double-check the tonemap settings configured in the Environment.

**Comment by xsellier** [comment]
Colors seems ok with this commit: 9444a3f01d3a8c4f49ddf24e3acc65b399ee0609

**Comment by akien-mga** [comment]
This is still reproducible and was introduced in #54307.

@groud debugged it yesterday, it's due to:
```
drivers/gles3/scene.glsl
#define SHADER_IS_SRGB true //TODO remove
```
and related logic. No idea why it impacts Vulkan though.

**Comment by clayjohn** [comment]
@akien-mga that define doesnt impact rendering when using the Vulkan renderer. Currently the code is never actually compiled or run.

**Comment by groud** [comment]
@clayjohn what worked around the bug was mainly to remove the test for `OUTPUT_IS_SRGB`, added in generated the shader in material.cpp:
```
	if (flags[FLAG_SRGB_VERTEX_COLOR]) {
		code += "	if (!OUTPUT_IS_SRGB) {\n";
		code += "		COLOR.rgb = mix(pow((COLOR.rgb + vec3(0.055)) * (1.0 / (1.0 + 0.055)), vec3(2.4)), COLOR.rgb * (1.0 / 12.92), lessThan(COLOR.rgb, vec3(0.04045)));\n";
		code += "	}\n";
	}
```
So definitely `OUTPUT_IS_SRGB` is causing issues there. It seems that it is not correctly set, as this constant is `true` even when using Vulkan (which should be linear if I am not mistaking).

I don't know if `SHADER_IS_SRGB` is causing some issues or not, I had found out it was in the list of renames for `shader_compiler_rd.cpp` and `shader_compiler_gles3.cpp` though:
```
actions[RS::SHADER_SPATIAL].renames["OUTPUT_IS_SRGB"] = "SHADER_IS_SRGB";
```

**Comment by clayjohn** [comment]
It sounds like we need to add the ``SHADER_IS_SRGB``  define to the Vulkan renderer and set it to false.

**Comment by clayjohn** [comment]
#55029 partially fixes this issue as it corrects the behaviour of the SRGB to linear conversion for vertex albedos. However, as the MRP shows, there is also an issue with colors defined in shaders with ``hint_color`` they aren't being converted to linear. 

The offending line is:
https://github.com/godotengine/godot/blob/0cdd18de7849de6e5c47158c672a4a5cfb4f6ea9/servers/rendering/renderer_rd/renderer_storage_rd.cpp#L2871

The last argument is ``p_use_linear_color`` which needs to be true otherwise all colors are forced to remain in the same color space they are specified in (which means they remain in SRGB space, even when ``hint_color`` is used).

**Comment by lyuma** [comment]
I was originally really happy to find that Godot 4 removed the automatic and unconditional sRGB color conversion. I've been hit by that a few times in Godot 3.x, and the workaround of changing all linear colors to use `Plane` was an ugly hack.

The way I see it, some materials will want to use HDR colors. If this happens, automatic sRGB color conversion in renderer_storage_rd (raising colors outside the range of 0..1 to some power) can lead to drastically incorrect results (intensity 4 -> 22)

This leads me to have two issues with your proposal, @clayjohn 

First, in terms of the UI, If this feature is added, I would need a way to have a color picker while turning off the automatic color picker (in other words, set the uniform color slot to linear)

For example, in unity, an ordinary `Color` property uses sRGB and disallows HDR by default. However, marking the color as `[HDR]` will switch it to linear and use an HDR color picker.

Second, I do not think color conversion should happen in the rendering server. If it is done here, it leads to a future-proofing problem where color uniforms may break when a color slot is changed to support HDR.

Doing it in the inspector / UI seems much safer. It also allows for paradigms like having a sRGB color + energy multiplier without forcing that logic to move into the shader.

**Comment by lyuma** [comment]
Alright, after chatting a bit and doing more research, I think I understand what @clayjohn is going to fix. I'll take back my previous comment. There is still a usecase for HDR color pickers, but that should be moved into its own proposal.

Basically, if I understand, the reason it is done in the rendering server is that way the project can be switched to gamma space / GLES3 and all materials will still look the same
if the conversion were done in the inspector, the materials will have converted colors and they will now look too dark when you switch to GLES3

the issue here is we can't look at the shader hints because this is too deep.. and furthermore we may be setting a global uniform which doesn't know which shader it will be used for.

So.... looking at the code around renderer_storage_rd.cpp:2134, it looks roughly the same as I remember from Godot 3.x...
```cpp
                               if (value.get_type() == Variant::COLOR) {
                                        Color v = value;
                                        if (p_linear_color) {
                                                v = v.to_linear();
                                        }
                                        gui[0] = v.r;
                                        gui[1] = v.g;
                                        gui[2] = v.b;
                                        gui[3] = v.a;
                                } else if (value.get_type() == Variant::RECT2) {
...
                                } else {
                                        Plane v = value;
                                        gui[0] = v.normal.x;
                                        gui[1] = v.normal.y;
                                        gui[2] = v.normal.z;
                                        gui[3] = v.d;
```
Note here how `Color` unconditionally does sRGB->Linear conversion, while `Plane` is always raw.

if this is the case.... `Plane` would still do what I want, that is to say, keeping raw color values with no linear conversion. One option would be to make it an official "feature".
That is to say, my proposal would go something like make a new hint such as:
```
uniform vec4 hdr_emission : hint_color_hdr;
```

and if the inspector sees a `hint_color_hdr`, it will use a `Plane` datatype instead of a `Color` datatype, but still show a color picker. Some logic might be needed to convert a "RAW" (`Plane`) color to a "converted" (`Color`) color and tell the user if a given value is mismatched for the type declared in the hint.

I will try and convert this all to a formal proposal once I've thought it over and chatted with people who have experienced similar issues in other engines.

**Comment by clayjohn** [comment]
Further to @lyuma's comments the logic for selecting between and Plane internally is here:
https://github.com/godotengine/godot/blob/7d1b454b679a0a10a38dc4dee150bb433ff4979d/servers/rendering/shader_language.cpp#L3504-L3531

Should be simple to extend this to detect a different hint too.

**Comment by xsellier** [comment]
thank you, works great!

**Comment by xsellier** [comment]
We better re-open this issue since it's happening again in eeec0f40457a985092055dbcd463e51aa95e3b41

Linux binogure 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64 GNU/Linux

**Comment by fire** [comment]
Can you post a link to the commit?

**Comment by xsellier** [comment]
Note it might be an import issue:
This is how it looks like inside Blender:
![image](https://user-images.githubusercontent.com/6616005/144822936-fe603047-aa76-41eb-8e78-4510a99c95d5.png)

This is how it looks inside Godot:
![image](https://user-images.githubusercontent.com/6616005/144823001-692ef714-9445-415a-b4fa-31988b6ac56d.png)

**Comment by xsellier** [comment]
I'm sorry, I checkout the wrong commit. Instead of going through the master branch, I was on another branch (which was not up-to-date).

My bad, sorry for the extra work, I'm closing this issue since it's been fixed already.
