### ISSUE TITLE
Strange problems with Uniform Arrays

### ISSUE THREAD

**Issue by anunknowperson** [godotengine/godot#54657]
### Godot version

4.0.dev (d04681753)

### System information

Windows 10, Vulkan Clustered, INTEL R CPU 0000 / RTX 3060 Ti

### Issue description

In some cases, depending on the location of the uniform declaration, arrays may stop returning values.

For example:

```glsl
uniform int texture_count = 1;

uniform sampler2D diffuse[1];
uniform sampler2D roughness[1];

uniform sampler2D weights[1];

uniform sampler2D heightmap;
uniform sampler2D colormap;

uniform vec2 uv_scale[1];
uniform vec2 uv_offset[1];
uniform bool depth_blending[1];
uniform bool triplanar[1];
uniform bool tile_reduction[1];
```

In this case, regardless of what is in uv_scale, uv_scale[0] will always return vec2(0, 0). However, all sampler2D arrays work fine.

However, in this case, when the variables are arranged in a different order, everything works well:

```glsl
uniform vec2 uv_scale[1];
uniform vec2 uv_offset[1];
uniform bool depth_blending[1];
uniform bool triplanar[1];
uniform bool tile_reduction[1];

uniform int texture_count = 1;

uniform sampler2D diffuse[1];
uniform sampler2D roughness[1];

uniform sampler2D weights[1];

uniform sampler2D heightmap;
uniform sampler2D colormap;
```

### Steps to reproduce

I discovered this by accident while working on the Terrain system for Godot 4, so other than a test project, I do not know how to recreate it. With that, it took me sooo much time to figure out where the problem is at all.

In the test project there is a scene with two Planes, each with a material with different shaders specified above. Uniforms has the same values set from the editor, but in one case it does not affect Plane in any way, and in the other it does.

### Minimal reproduction project

[unform_array_bug_test.zip](https://github.com/godotengine/godot/files/7490210/unform_array_bug_test.zip)

**Comment by InfuriatedBrute** [comment]
On a sidenote, what do you mean "will always return vec2(0, 0)"? You can't simply print values in shader code, so how are you debugging them? My current method is basically 20 Questions using the discard keyword.

**Comment by anunknowperson** [comment]
> On a sidenote, what do you mean "will always return vec2(0, 0)"? You can't simply print values in shader code, so how are you debugging them? My current method is basically 20 Questions using the discard keyword.

I add the return value to the Y coordinates of the mesh vertices and observe if its position has changed. You can see it in the test project.

**Comment by akien-mga** [comment]
Reopening as #54736 was reverted in #55308.

**Comment by GNSS-Stylist** [comment]
Not sure if this this is related (or a common limitation (configurable?) or a feature instead of a bug), but:

I tried to use big (around 500 000 items) uniform arrays but they didn't seem to work. After narrowing down the problem it started to look like the total number of uniform items (including the items inside arrays) was limited to 4096. In addition to this, bigger types like mat4 seem to consume the available space quicker so that 1024 items already use all of it. This happens in both the editor and the running (ran from the editor) project.

Changing the sizes or contents of the arrays through "Shader Param" doesn't seem to affect anything

Tried to change setting "Rendering->Limits->Global Shader Variables->Buffer size" to see if it fixes the issue. Didn't help. Is there some other place to look for limits for these?

See attached video and sample project for more info.

If this is a (new) bug I can make an issue out of this(?)

System: Windows 10, RTX-2060(mobile), Godot v4.0.dev.custom_build [5f9e2fccc], Vulkan renderer
(btw: After changing to opengl3-renderer godot stopped showing menus, the "3d-area" was grey, menus disappeared and after selecting a node it crashed so couldn't test the opengl-renderer).

https://user-images.githubusercontent.com/50438441/144888228-691b9a84-ce1a-412c-b54b-572e0900d26e.mp4

[UniformArrayTest.zip](https://github.com/godotengine/godot/files/7662257/UniformArrayTest.zip)

**Comment by clayjohn** [comment]
@GNSS-Stylist Most discrete GPUs have a maximum uniform buffer size of 65536 bytes (including yours) Which translates to 4096 vec4s or 1024 Mat4s (which are essentially 4 vec4s). Your GPU driver will pad most data types to vec4 when used in an array (some GPUs don't add padding, but many do).

There are two things we need to do in response:
1. Add a warning if a user tries to add more uniforms than can fit in 65536 bytes (long term we could automatically split the uniforms up into multiple UBOs internally, or use a SSBO internally)
2. add documentation about data padding and size limits to the documentation page.

Ultimately, these are all unrelated to this issues. I have opened #55674 to track
