### ISSUE TITLE
Console no longer showing in windows builds

### ISSUE THREAD

**Issue by clayjohn** [godotengine/godot#54684]
### Godot version

master bd31af37b465f9d4730c18f6985645aa1b773396

### System information

Windows 10

### Issue description

When building the engine in debug with the ``windows_subsystem=console`` build flag, the console no longer appears. This issue was introduced in the last week or two. 

For clarity ``interface/editor/hide_console_window`` is ``false``. 

The console still appears in the project manager, but disappears when a project is opened.

### Steps to reproduce

Build Godot using ``windows_subsystem=console`` and open a project in the engine.

**Comment by ShlomiRex** [comment]
After investigating, it appears the build option is no longer exists in 3.4.
After digging, reading this:
https://github.com/godotengine/godot/pull/41332
It appears this feature was reverted and no longer exists.

**Comment by clayjohn** [comment]
#41332 added the ``windows_subsystem=console`` build command and reverted #41164 it did not remove the ``windows_subsystem=console`` command.

**Comment by akien-mga** [comment]
Probably caused by #54591, CC @WoLfulus @mhilbrunner.

**Comment by mhilbrunner** [comment]
I can confirm this was caused by https://github.com/godotengine/godot/pull/54591. Building the commit immediately before it (https://github.com/godotengine/godot/commit/fa033e11b7484c8b3a1b1aad7d38b15c4ac35483) works as expected, whereas with it, the console closes as soon as the project manager exits to start the editor.

Starting the project manager from the terminal also doesn't work as a workaround, it still loses the streams once the manager exits and starts the editor.

Starting the editor directly (`--editor`) with the project, circumventing the project manager, does work as a workaround.

**Comment by ShlomiRex** [comment]
May I ask what was the purpose of this command and why was it revoked?

**Comment by Chaosus** [comment]
Indeed, it's was caused by #54591 The correct action to fix it (I think) is somehow handling the content of its calling (probably through command-line arguments or global singletons) and don't attach the CREATE_NO_WINDOW flag if it's the editor or project manager.

**Comment by clayjohn** [comment]
@Chaosus That makes sense. In my local branch I have just removed ``CREATE_NO_WINDOW`` entirely.
