### ISSUE TITLE
Option to have a bigger text editor area

### ISSUE THREAD

**Issue by mateusak** [godotengine/godot#5473]
The current text editor feels small, uncomfortable and even claustrophobic. I'm used to the Visual Studio area, which is basically the entire screen.

**Comment by djrm** [comment]
use SHIFT + F11

**Comment by vnen** [comment]
Depends on the screen size, since horizontal space is usually enough. Visual Studio also have side docks, so it's not so different. And as said <kbd>Shift</kbd>+<kbd>F11</kbd> (if you're using the development version) hides the docks. Also, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F11</kbd> toggles "Distraction-free mode".

**Comment by mateusak** [comment]
Didn't knew that, and it's great. But I mean an "automatic" version of that, which just applies to the text editor. In the Visual Studio I'd hide the tabs, to have a clean vision of the script.

**Comment by vnen** [comment]
Well, I wouldn't it to be automatic (maybe an opt-in setting could do). For the script list, I prefer the Visual Studio Code way (as I said [in another comment](https://github.com/godotengine/godot/issues/4775#issuecomment-221676036)), since tabs are already showing scenes and switching scenes also switch scripts.

And to illustrate, this is Fullscreen mode (<kbd>Shift</kbd>+<kbd>F11</kbd>):

![godot windows opt tools 64_2016-06-28_21-15-18](https://cloud.githubusercontent.com/assets/5599796/16436621/b144d580-3d75-11e6-8cb4-c0af97c2c755.png)

This is Distraction-free mode (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>F11</kbd>):

![godot windows opt tools 64_2016-06-28_21-15-50](https://cloud.githubusercontent.com/assets/5599796/16436629/c62210ee-3d75-11e6-9b46-97226f8410c6.png)

**Comment by vnen** [comment]
BTW I usually open scripts from the Scene Tree and FileSystem docks, so hiding them would make it worse for me. Quick Open Script is cool, but not always I know the name of the script.

**Comment by Zylann** [comment]
I find the ability to toggle docks individually is handy when you don't need them to take lateral space all the time. Visual Studio (and other IDEs) do that, but Godot only has it on the bottom dock. Then they open again depending on the context. For example if you hide the inspector, you can code without it. But if you select a node in the scene tree or a resource, it would open again. Same for the Output console: if you debug your game, it opens to show you the prints(). To me, Distraction-Free mode looks like a hardcoded layout to solve the most common use case. It's a matter of context, you don't need to see the same things depending on what you do.

**Comment by akien-mga** [comment]
If a wider script editor means writing longer code lines (more than 80 chars), then it's encouraging bad practice and would be a misfeature ;)

**Comment by Zylann** [comment]
@akien-mga true, if you are lazy at formatting code :p (btw my suggestion is not only about the script editor, but the dock system)

**Comment by vnen** [comment]
Yeah, unless you use a vertical monitor, I don't know how useful this is. I shrunk the window to take screenshots and still there's plenty of room for coding.

So my suggestion remains: an opt-in setting to make Fullscreen mode default in script editor.

----

@Zylann I like your suggestion, but it'll likely be forgotten in here. It's better if you bump an old related request (like #4344) or open another issue if you think it's not the same.

**Comment by mateusak** [comment]
Not really about writing longer code lines, just more space. I don't know what it is, but I can't think with little space.

**Comment by akien-mga** [comment]
> So my suggestion remains: an opt-in setting to make Fullscreen mode default in script editor.

Seems fine to me and should be easy enough to implement, provided this feature is still wanted. Personally I'm fine with the size of the script editor:
![screenshot_20181123_161706](https://user-images.githubusercontent.com/4701338/48950376-38cf0380-ef3b-11e8-93bd-c31a807c3e30.png)

**Comment by Calinou** [comment]
Enabling the fullscreen mode when you toggle the script editor could be strange, as the editor window would switch from being maximized to fullscreen all the time.

Instead, we could add an option to make the script editor look as if it was in fullscreen mode, but the window would remain in whatever state it is.

**Comment by Anutrix** [comment]
Assuming it's feasible, we can maybe slightly decrease font size and editor scale in distraction-free mode.

Also, side by side multiple script-editor area optional feature might use up space efficiently but that's a separate issue or GIP.

**Comment by Calinou** [comment]
@Anutrix The editor scale can't be changed at run-time. Also, I'm not sure if changing the font size is a good idea as people may have trouble reading the smaller font after entering distraction-free mode.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
