### ISSUE TITLE
How change omniligths energy programmatically

### ISSUE THREAD

**Issue by gerardogc2378** [godotengine/godot#5476]
Hi, my question are two, is posible change energy ligth in 3d worlds? if possible, how change omniligths energy programmatically using gdscript?

**Comment by djrm** [comment]
The issue tracker is used to report bugs or make suggestions for the engine.
Please use this webpage to ask questions http://www.godotengine.org/qa/

**Comment by vnen** [comment]
Please ask question at https://godotengine.org/qa (or some other [community channel](http://www.godotengine.org/community)). GitHub is for bugs and feature requests only.

If it's not possible to do what you want or if it's not working as it should, then you can propose the feature or point out the bug here.

**Comment by gerardogc2378** [comment]
Ok, thanks.
