### ISSUE TITLE
GDScript built-in wrapi() does not start wrapping with minimal value

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#54775]
### Godot version

3.4 stable

### System information

Win 64

### Issue description

If the input value starts with 0 and is continuously increased, then warped and printed, I would expect the printout to start with the minimum value:

```
var input = 0
var wrap_min = 50
var wrap_max = 150

func _process(delta):
	if Input.is_action_pressed("ui_accept"):
		input += 1
		input = wrapi(input, wrap_min, wrap_max)
		print(input)
```

but instead this will print:

```
101
102
103
...
149
150
50
51
...
```

What I would expect is this:

```
51
52
53
...
149
150
50
51
...
```

The same is the case if you don't asign the wrapped input value btw:

```
var input = 0
var wrap_min = 50
var wrap_max = 150

func _process(delta):
	if Input.is_action_pressed("ui_accept"):
		input += 1
		print(input)
		print(wrapi(input, wrap_min, wrap_max))
```

### Steps to reproduce

See above

### Minimal reproduction project

Just copy/paste the code example provided into any project.

**Comment by spindlebink** [comment]
Forgive me if I'm misunderstanding the issue, but isn't this working as expected? `wrapi` wraps bi-directionally, so numbers below the minimum will loop back around from the top--in this case, since the minimum is 50, 1 is 49 less than that, which makes it loop backwards from 150 -> 101.

**Comment by Chaosus** [comment]
The idea behind this function is to wrap value between min and max regardless of value itself. Accept it as an extended modulo function that supports negative numbers and setup of minimum value. If it's 0 and min/max is 50/150 then it should wrap to the negative side and the result becomes 100. Plus a lot of users already used that function since it was implemented(by me) without a problem and changing it would break their scripts.

**Comment by Chaosus** [comment]
The further discussion is pointless - this function does what is expected and would not be changed.
