### ISSUE TITLE
Checking Own World option in Viewport crashes editor

### ISSUE THREAD

**Issue by pkowal1982** [godotengine/godot#5482]
[godot_test.zip](https://github.com/godotengine/godot/files/338795/godot_test.zip)

**Operating system or device - Godot version:**
Win7 64 - v2.0.3.stable.official

**Issue description** (what happened, and what was expected):
Checking Own World option in Viewport crashes editor

**Steps to reproduce:**
Add Viewport as root node, add WorldEnvironment as its child.
In the Inspector window add new Environment.
Select Viewport node and try to check Own World option.

**Link to minimal example project** (optional but very welcome):
Test project can be found in the attached file.
Just try to click the option...

**Comment by TheHX** [comment]
Using GDB, i've found the crash occurs while calling the [```Viewport::_propagate_exit_world```](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1112), precisely in this [line](https://github.com/godotengine/godot/blob/master/scene/main/viewport.cpp#L1086). As the notification is called in reverse order, the correct statement would not be?
```GDScript
                s->notification(Spatial::NOTIFICATION_EXIT_WORLD, true);
```

Using the current statement causes a segfault in the ```WorldEnviroment``` node, during the notification(NOTIFICATION_EXIT_WORLD), because the notification is called first in parent class(```Spatial```), when the ```WorldEnviroment::_notification``` is called, the node is not in tree anymore, which causes the the segmentation fault in the [line](https://github.com/godotengine/godot/blob/master/scene/3d/scenario_fx.cpp#L49)(in the expression ```get_world()->get_environment()==environment```, because the the first function returns a invalid reference), showing this error in the terminal:
```
ERROR: get_world: Condition ' !is_inside_world() ' is true. returned: Ref<World>()
```
