### ISSUE TITLE
[3.4] Camera2D doesn't snap into the limits when limit smoothing is enabled

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#54856]
### Godot version

3.4.stable

### System information

Ubuntu 20.04.3 LTS

### Issue description

When Camera2D has limit smoothing enabled and isn't inside the limits, it behaves weirdly. If smoothing is enabled, it will slowly slide into the limits, and if smoothing is disabled, it will stay outside.
This did not occur in 3.3.4, where Camera2D always immediately snaps into the limits.

The video below shows the behavior in 3.4
https://user-images.githubusercontent.com/85438892/141212294-0eb786d5-d501-442b-b0fd-298e9b41ba8b.mp4

### Steps to reproduce

1. Create Camera2D and set its limits to small numbers
2. Enable limit smoothing
3. Move the Camera2D outside of the limits
4. Run the project

### Minimal reproduction project

[Camera test.zip](https://github.com/godotengine/godot/files/7516701/Camera.test.zip)

**Comment by timothyqiu** [comment]
Possibly related to: #49409

This can be used as a workaround:

```gdscript
camera.force_update_scroll()
camera.reset_smoothing()
```

**Comment by ekumlin** [comment]
Yeah, the fix I made is new in 3.4. This sounds related.

This part sounds like desired behavior:

> If smoothing is enabled, it will slowly slide into the limits

The logic being that if you use smoothing and set new bounds, it's natural to expect smoothing to apply as the bounds are adjusted.

However this sounds like a bug:

> and if smoothing is disabled, it will stay outside.

I'm pretty sure I tested this case so it seems a little odd that this would happen. If you use the workaround described above (even just the second line should be sufficient), does it properly snap to the new bounds?

**Comment by timothyqiu** [comment]
| `smoothing_enabled` | `limit_smoothed` | start the scene with 3.4 | start the scene with 3.3.4 |
|--|--|--|--|
| :no_entry:  | :no_entry:  | directly inside the bounds | directly inside the bounds |
| :no_entry: | :heavy_check_mark: | stuck outside the bounds | directly inside the bounds |
| :heavy_check_mark: | :no_entry: | directly inside the bounds | directly inside the bounds |
| :heavy_check_mark: | :heavy_check_mark: | smooth into the bounds | directly inside the bounds |

With the workaround, the camera behaves the same as 3.3.4.

> The logic being that if you use smoothing and set new bounds, it's natural to expect smoothing to apply as the bounds are adjusted.

Maybe this is a corner case, but the issue here (as shown in the MRP) applies to the initial state of a scene. I think not smoothing makes more sense here, because with "Draw Screen" on, the magenta screen rect shown in the editor is directly inside the limit bounds.

**Comment by MewPurPur** [comment]
Limits are mostly used for rooms and probably a lot of people:
* never want the camera to leave the rooms
* want the camera to not make a sharp stop when you approach the edge of a room.

Getting into proposals zone here, but perhaps it would be best to separate limit smoothing into two: Inside for handling limit smoothing when the camera is inside the limits (i.e. smooth into the edges of a room) and outside for handling it when it's outside the limits (i.e. smooth into a new room).

**Comment by ekumlin** [comment]
> Maybe this is a corner case, but the issue here (as shown in the MRP) applies to the initial state of a scene. I think not smoothing makes more sense here, because with "Draw Screen" on, the magenta screen rect shown in the editor is directly inside the limit bounds.

Yes, what you say here makes sense, but it's also the easiest time to call `reset_smoothing()`. The reason I made this fix is that from a game dev's code, it is harder &mdash; perhaps to the point of even have to write your own camera movement &mdash; to make the camera properly smooth to the limits. However, adding a call to `reset_smoothing()` on a `_ready()` in a scene is trivial.

---

> Getting into proposals zone here, but perhaps it would be best to separate limit smoothing into two: Inside for handling limit smoothing when the camera is inside the limits (i.e. smooth into the edges of a room) and outside for handling it when it's outside the limits (i.e. smooth into a new room). Or a "Never leave limits" setting, or something of that sort.

I think this isn't a bad idea, but definitely a proposal or at least a significant change. For now, given what I said above, I think it makes more sense for Godot to handle smoothing into the limits and let the game dev forcibly bypass it, instead of jumping to the limits and forcing game devs to write their own camera smoothing code.

---

In terms of this case, though:

![image](https://user-images.githubusercontent.com/1350074/142344135-1d9f673f-6336-489a-b8c3-6cf70d6202ca.png)

The fact that the camera stays outside the bounds with `limit_smoothing` disabled seems like a bug &mdash; I just don't know what the cause is. As mentioned, this was the change made (hiding whitespace changes):

![image](https://user-images.githubusercontent.com/1350074/142343691-1d8e34a3-1108-4fbb-94a0-ea190bc915ee.png)

So, if `limit_smoothing` is disabled, that code should still execute, same as it did in 3.3.X. (Far as I can tell, [the code](https://github.com/godotengine/godot/blob/b99792b5d9e85169b82127efe2ade563cc363b27/scene/2d/camera_2d.cpp#L179) hasn't changed since, either.) Open to ideas why it might not be; I may take a look at this if I get the chance.

---

With all that said: I'm open to suggestions from the room, but since there is a very easy workaround in the 3.4 state but not one in the 3.3.X state, I think we should stick with the general 3.4 behavior, and give a try to fixing the behavior for when `limit_smoothing` is disabled.

**Comment by ekumlin** [comment]
I did a bit of digging and think I understand now &mdash; this was my mistake. When working in the code, I misinterpreted this factor of `limit_smoothed`:

> This has no effect if smoothing is disabled.

I had taken it to mean that `!smoothing_enabled` would enforce `!limit_smoothing_enabled` in the C++ code, but that is not the case.

So, correct me if I'm wrong, but I believe that means that the condition should not be `(!limit_smoothing_enabled)`, but rather `(!smoothing_enabled || !limit_smoothing_enabled)`.

When testing locally, I confirmed that this would result in the following truth table instead:

| `smoothing_enabled` | `limit_smoothed` | start the scene with 3.4
| --- | --- | ---
| ⛔ | ⛔ | directly inside the bounds
| ⛔ | ✔️ | directly inside the bounds
| ✔️ | ⛔ | directly inside the bounds
| ✔️ | ✔️ | smooth into the bounds

In no case did it stay stuck outside the bounds. Does that look right?

**Comment by MewPurPur** [comment]
The behavior in the gif LGTM.

**Comment by ekumlin** [comment]
I've created the above pull request to address the issue. It's only one commit but please let me know if a rebase is required.
