### ISSUE TITLE
Wrong scaling steam godot on osx with retina display

### ISSUE THREAD

**Issue by xklakoux** [godotengine/godot#5485]
**Operating system or device - Godot version:**
godot 32-bit stable 2.0.3 steam buildID:1126922 on osx 10.11.5
i'm working with 2 fullhd external monitors and retina display

**Issue description** (what happened, and what was expected):
when project is run content is not scaled properly
after resizing the window it updates and works ok from then 

you can observe it when launching godot (or any sample)
![when launched](https://cloud.githubusercontent.com/assets/1180857/16450153/cbf9abae-3dfb-11e6-9b06-5b571c78aac2.png)

after any window resize it works good
![after any window resize](https://cloud.githubusercontent.com/assets/1180857/16450156/cfb2a6e2-3dfb-11e6-8477-49e8d4977ec8.png)

this issue doesn't occur on the same non-stream 64-bit version of godot

**Comment by akien-mga** [comment]
I have no clue why this would happen only in the steam version, it's normally the same as the non-Steam one (though maybe the OSX binary on Steam is only 32-bit, but it shouldn't make much difference).

Retina support was added in the current development branch for 2.1 though, so this should get fixed automatically when we release it. In the mean time, if someone has an idea on how to debug this steam issue for 2.0.x...

**Comment by timoschwarzer** [comment]
@xklakoux Did you open a project before and close it afterwards?
Because the Project Manager changes its 2D Viewport Properties with opening your project.
E.g. if you open a project with 2D viewport scaling and aspect ratio set to keep, and close to the Project Manager, it has 2D viewport scaling and keep aspect ratio, too.

**Comment by xklakoux** [comment]
that's the first thing i see when I launch the steam app. It also happens everytime for every project I run from the project manager or editor. If I choose to launch project fullscreen then there's no problem.

**Comment by akien-mga** [comment]
Ah @timoschwarzer has a good lead. Do you have maybe an `engine.cfg` file in your home directory that the project manager might be using to setup its dimensions?

**Comment by xklakoux** [comment]
no file like that

**Comment by reduz** [comment]
did you try Master? we have proper retina support there

**Comment by jackmakesthings** [comment]
I'm seeing something similar on the latest from the master branch; I'm on a 13" MBP plugged into an external display. When I open the project manager and then try to open a project, the layout of the editor ends up wrong:
- on the laptop screen, the whole editor is visible but all the text and UI are tiny (half what they should be, probably)

![godot-on-laptop](https://cloud.githubusercontent.com/assets/3606708/16747253/3ebe531c-478c-11e6-92e7-747c45532226.jpg)

- on the attached external monitor, the text and UI are the right size, but the editor window won't show all of its contents, no matter how large or small I make it. The top and right edges are always cut off, regardless of dragging the window edges.

![godot-on-mac-display](https://cloud.githubusercontent.com/assets/3606708/16747285/5cc53038-478c-11e6-837d-89ca4d070cb6.jpg)

Like I said, this is happening on a version I just built from master. I can't find any stray engine.cfgs or settings that seem like they could be responsible. I do remember seeing this issue once before and it had something to do with running the bare compiled godot executable rather than putting it into the provided .app template, but that's not the case this time around; in these screenshots, I was running the app, with the freshly-built executable copied into place inside it.

**Comment by paryl** [comment]
I'm having the same issue as jackmakesthings on my MacbookPro... the window renders ok on the laptop screen (albeit with tiny text), but not on secondary monitors. 

http://i.imgur.com/OR6lULN.jpg

**Comment by akien-mga** [comment]
There were many fixes to hidpi support on macOS in the master branch, so I assume this might be fixed (at least part of the issues mentioned here, especially regarding external monitors).

**Comment by ZingBlue** [comment]
I still am having problems with this. 3.1

**Comment by code0wl** [comment]
Hi guys, great work with the engine. I just adopted it. 
I am Afraid to confirm that @ZingBlue is correct, this is still an issue. 

I invite you to place @paryl's answer as a Q&A for Mac adopters somewhere on the readme.
