### ISSUE TITLE
CollisionShape not getting detected by RayCast

### ISSUE THREAD

**Issue by MilkAndBanana01** [godotengine/godot#54887]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 10, GLES3, Intel Core i3 7100

### Issue description

This might just be a freak incident, but I want to make sure that this is reported just in case this is an actual bug.
There is an FPS controller and 2 RigidBodies in there that are supposed to interact with the player. It seems that WeaponA is not getting collided by the raycast at all but WeaponB is.
A helper and I even tried to see what was happening and ended up without any solutions.
I have provided a google link for the project entirely, apologies since it will print out per frame due to the checks we did to see the issue.
This is my first issue ever sent so there was probably a lot of protocol that I just broke, but I want to make sure to get this to the devs in case this is an actual bug that needs to be fixed.

Thank you for everything and this amazing engine that you brought to us, and I can't wait for the next update :)

### Steps to reproduce

1. I finished the RigidBody scene (WeaponB)
2. I duplicated to create WeaponA and make the material unique to give a different albedo
3. I set up the code the same way

### Minimal reproduction project

https://drive.google.com/drive/folders/1cRCcQFpGmGYh3W6D6JEGfIzlK5DWBzPU?usp=sharing

**Comment by kleonc** [comment]
@Calinou Tested, it's user error. I don't see any in-engine bug in here.

@MilkAndBanana01 Detection works fine, it's something with your logic. I removed your `print` and added one like this:
```
func _physics_process(delta):
	print(reach.get_collider().name if reach.is_colliding() else "---")
	...
```
Result:

![I190nhA0dL](https://user-images.githubusercontent.com/9283098/141337733-06e43510-dcce-436a-bff3-d3dd7255fa27.gif)

And indeed your logic is the issue:
```
func detectEquip():
	if reach.is_colliding():
		if reach.get_collider().get_name() == "WeaponA":
			weaponToSpawn = weaponAHR.instance()
		if reach.get_collider().get_name() == "WeaponB":
			weaponToSpawn = weaponBHR.instance()
		else:
			weaponToSpawn = null
	else:
		weaponToSpawn = null
```
You wrote `if...if...else` but you're expecting it to work like `if...elif...else`.

If you're not sure whether you're facing an in-engine bug you can ask for help in other [Community channels](https://godotengine.org/community) (like Q&A/Discord/Reddit) in the first place. This is a bugtracker, it's not a place for "help me with my code" stuff. :wink:

Also please don't ignore the errors in the console/debugger. Specifically in your case instead of:
```
if node.get_child(0) != null:
	var first_child = node.get_child(0)
	...
```
you can write:
```
if node.get_child_count() > 0:
	var first_child = node.get_child(0)	
	...
```
to not produce an error.

**Comment by Calinou** [comment]
Closing per @kleonc's comment.
