### ISSUE TITLE
"Quick Open" window is ignoring file extensions

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#5488]
**Operating system or device - Godot version:**
Ubuntu 16.04,  119cd5d3ff9fbbafc59db7481c0eee29f43c0c64 commit

**Issue description** (what happened, and what was expected):
It's a regression from 2.0
In Godot 2.1 windows "Quick open scene" and "Quick open script" are ignoring dots (or file extensions). It will be the best to ilustrate this with screenshot:
![quickopenregression](https://cloud.githubusercontent.com/assets/6129594/16455967/7ac1849e-3e16-11e6-9ab2-478c11edb8c8.png)
In Godot 2.0 for this phrase I would have only one outcome.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Well, it's not ignoring. It is performing subsequence search and since all files have `.t` it shows all files. So there's a few solutions to this:

1. Make the search smarter and change from subsequence to regular match if the search term has a dot.
2. Make it only search for file name, not the whole path.
3. Make the subsequence search opt-out with an editor setting (then it should consider if this is global or there's an option for each search field).

**Comment by akien-mga** [comment]
Doesn't the search algorithm consider a full match like "mainmenu.t" as a best match? If so it should then show `UI/MainMenu/MainMenu.tscn` on the top of the list as the best match no?

**Comment by akien-mga** [comment]
I think (2) is not a good solution, as quite often you type a folder name to get all files of this folder and pick the one you want (e.g. `levels`).

(1) might be a good compromise. Another solution could be to always start with a regular match, and only make the subsequence search afterwards, thus always listing regular matches first. But that might have a performance impact.

**Comment by kubecz3k** [comment]
I also think option (2) is not the best one for the reasons raised by Akien. It's quite comfortable to write name of the folder with levels to see all the levels for example.

**Comment by vnen** [comment]
I'll tackle this. I'll make it so it uses regular match first then.

**Comment by vnen** [comment]
Heh, there's no easy way to do this :disappointed:. The list is a Tree, which seems to have no way to add items in a particular position and since the function is recursive per directory, I can't prioritize generally (unless I change the root function to perform two searches).

A clean way around this would be to add two root items, one with the regular matches and other with subsequences.

**Comment by kubecz3k** [comment]
Hmm changing root function to perform two searches sounds like a good solution for me, but I have fast ssd disk, is it possible for those searches to be to slow?
