### ISSUE TITLE
`stepify()` and format strings round `5` down

### ISSUE THREAD

**Issue by Error7Studios** [godotengine/godot#54896]
### Godot version

3.4.stable

### System information

Windows 10

### Issue description

`stepify()` and format strings round `5` down instead of up.

```
	print(stepify(0.150, 0.1))
	print("%.1f" % 0.150)

	print("---")

	print(stepify(0.151, 0.1))
	print("%.1f" % 0.151)

	breakpoint
```

Prints:
```
0.1
0.1
---
0.2
0.2
```

Expected:
```
0.2
0.2
---
0.2
0.2
```

### Steps to reproduce

Run code above

### Minimal reproduction project

N/A

**Comment by justchen1369** [comment]
core/math/math_funcs.cpp:116
```c
double Math::snapped(double p_value, double p_step) {
	if (p_step != 0) {
		p_value = Math::floor(p_value / p_step + 0.5) * p_step;
	}
	return p_value;
}```

I believe the implementation is correct because based on the documentation, the correct behavior is to "snap" to the nearest multiple of p_step.

**Comment by Error7Studios** [comment]
Interestingly, with larger numbers, it rounds correctly.

```
	print(stepify(0.150, 0.1))
	print("%.1f" % 0.150)

	print("---")

	print(stepify(3.150, 0.1))
	print("%.1f" % 3.150)

	print("---")

	print(stepify(9.150, 0.1))
	print("%.1f" % 9.150)

	breakpoint
```

Prints:

```
0.1
0.1
---
3.1
3.1
---
9.2
9.2
```

Notice that the rounding of `3.150` is also incorrect.
So I guess it's a float rounding error.

**Comment by justchen1369** [comment]
I guess this leads to the question of what the correct rounding algorithm is- typically it'd be to round halves up.

**Comment by justchen1369** [comment]
maybe something like this? 

```cpp
    double snapped(double p_value, double p_step) {
        float inverse = 1.0 / p_step;
        if (p_step != 0) {
            p_value = Math::round(p_value * inverse) / inverse;
        }
        return p_value;
    }```

**Comment by nathanfranke** [comment]
See https://github.com/godotengine/godot/pull/56050#issuecomment-999161311 on why this is expected behavior.

**Comment by aaronfranke** [comment]
The values you are working with are not exact floats, so the math isn't working as you expect.

When you write `stepify(0.150, 0.1)`, those values get converted to the nearest float values to those values. For 32-bit floats it would be `stepify(0.1500000059604644775390625, 0.100000001490116119384765625)` (same thing with 64-bit, but with more `0`s before the unreliable digits).

This fix isn't correct (casting to float will work in some cases but break others), but there is no way to fix this function for those values because the numbers you're passing in are not what you expect, so it the math error happens before we even get to the code of the function.

The best suggestion I can offer you is to use an epsilon value, so instead of `snapped(value, step)`,
do `var epsilon = 0.000001` and `snapped(value + epsilon, step)`.

**Comment by Error7Studios** [comment]
> There is no way to fix this function...
The best suggestion I can offer you is to use an epsilon value, so instead of snapped(value, step),
do var epsilon = 0.000001 and snapped(value + epsilon, step).

Thanks for the explanation and suggestion. I'll close this since it's not a bug.
