### ISSUE TITLE
HSlider value_changed signal now emitted multiple times per frame when moving slider. (changed 3.3-3.4)

### ISSUE THREAD

**Issue by Jattmackson** [godotengine/godot#54909]
### Godot version

3.4.stable (64)

### System information

Window10 (64) Nvidia 1060 6gb GLES3

### Issue description

HSlider value_changed signal can now be emitted multiple times per frame when moving slider. (changed 3.3-3.4)

This causes compatibility issues in my project as this signal calls computationally expensive methods multiple times a frame causing massive lag-spikes when moving a slider.

### Steps to reproduce

Connect the "value_changed" signal from a HSlider (likely an issue on other sliders/signals too?)

In 3.3 this signal would only be emitted once per frame when moving the slider
In 3.4 this signal can be emitted multiple times per frame

### Minimal reproduction project

[sliderbug.zip](https://github.com/godotengine/godot/files/7527201/sliderbug.zip)

**Comment by Calinou** [comment]
@Jattmackson  Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?

As a workaround, use a Timer node to prevent expensive functions from running too often, either via throttling (only emit a custom signal once every N milliseconds) or debouncing (wait until emitting a custom signal).

**Comment by Jattmackson** [comment]
> @Jattmackson Can you reproduce this in any of the [3.4 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.4/) to determine when the regression started?
> 
> As a workaround, use a Timer node to prevent expensive functions from running too often, either via throttling (only emit a custom signal once every N milliseconds) or debouncing (wait N milliseconds until no changes happen, then emit a custom signal).

Thanks for your quick reply
Beta 3 - calls slider value_changed at most once per frame
Beta 4 - appears to be where change appears. Value changed called many times per frame.

And thanks for workaround suggestion. For now I've collected the signals in a dictionary overwriting changes when the slider emits signals lots of times and just call my function at end of frame.

**Comment by akien-mga** [comment]
> Beta 3 - calls slider value_changed at most once per frame
Beta 4 - appears to be where change appears. Value changed called many times per frame.

Thanks for testing. From a look at the [changeset](https://github.com/godotengine/godot/compare/8db0bd44249e9cac56cf24c7c192bc782c118638...6a058cbf3984131f94c8680970f3c184ddecc801), it sounds likely that this was a regression from #42220.

As found in #55037, this PR mistakenly turned input accumulation off by default.

I confirm that calling `Input.set_use_accumulated_input(true)` in `_ready` solves the issue here and restores the 3.3 behavior. So technically it's the same bug as #55037, I'll close it to consolidate there.
