### ISSUE TITLE
Editing complex TileMap results in significant editor freeze

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#54961]
### Godot version

ed300d7

### System information

W10

### Issue description

I have a complex TileSet with over 20 atlas sources and scenes with hundreds of tiles. Whenever I click TileMap to edit it, the editor will freeze for a couple of seconds (5 in release_debug build) before the Tile editor will open.
![opSlLYOyfB](https://user-images.githubusercontent.com/2223172/141663612-b054801f-efbd-4a95-831f-c47f2fab91da.gif)

Opening or switching to scenes that contain TileMap also results in a freeze.

### Steps to reproduce

1. Open the attached project
2. Open LagExample scene
3. Click TileMap

### Minimal reproduction project

[TileMapLag.zip](https://github.com/godotengine/godot/files/7532993/TileMapLag.zip)

**Comment by Calinou** [comment]
cc @groud

**Comment by briansemrau** [comment]
I suspect this could be caused by the TileMapEditor queuing lots of preview rendering at once here:
https://github.com/godotengine/godot/blob/5aae92f069b47c040d93e5edba2aad5b104fd1a5/editor/plugins/tiles/tile_map_editor.cpp#L302-L308

This could cause a _lot_ of viewports to be rendered to in a single frame.

**Comment by KoBeWi** [comment]
Still valid in 1f690f1

**Comment by KoBeWi** [comment]
Likely related to the recent HashMap changes, but the freeze went down from 5s to 2s, which is more acceptable. Optimizing it more would be nice, but the issue is less important probably.
