### ISSUE TITLE
GDScript cannot override Godot's native functions

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#55024]
### Godot version

4.0.dev 7791599d5bcfdbae0d2a96e5fc13d9021ec820be

### System information

Linux binogure 5.14.0-2-amd64 #1 SMP Debian 5.14.9-2 (2021-10-03) x86_64 GNU/Linux

### Issue description
I don't know if it is normal, but I cannot override any godot's native functions using GDScript.
It never calls the gdscript function but the godot's core function instead.

### Steps to reproduce

- Create a new project
- Attach this script to the main node:
```gdscript
extends Node

var __data = {}

func _ready():
    set('random_key', 'random value')

func set(key, value):
    print('Setting a new value')
    __data[key] = value
```

The `set` function is never called, and there is no warning/error in godot explaining that is prohibited.

**Comment by xsellier** [comment]
Seems to be related to: https://github.com/godotengine/godot/issues/40288

**Comment by Zylann** [comment]
Shouldn't it be `_set`? I don't recall the engine expecting `set` to be overridable

**Comment by xsellier** [comment]
I expect to override any engine's function if I want to do it.

**Comment by Zylann** [comment]
I'm afraid that's not how things work, as it has probably been said in other issues, to achieve that the engine would have to use slow `call` on *absolutely every function that ever faces the script API*, which likely won't happen as it's too much work and downsides to it (unless maybe the engine was in Java?)

I remember that in Godot 3 so far, if you write a function with the same name as an existing function, Godot lets you "shadow" it, although it is not true overriding. For example if you write "get_position" in `Node2D`, GDScript might behave as if you overrode the function (because GDScript uses `call` everywhere), but the *engine* will not use your function when getting the position of the node.

So there should be a decision wether or not Godot should consider it an error. I personally think it should, but like many edge cases like this one, other people might have decided to exploit it and want it to remain maybe 🤷

**Comment by xsellier** [comment]
It would be great to have an empty class, that you can use as a singleton so you can have any functions you want. That's the bare minimum to me.

**Comment by Zylann** [comment]
> It would be great to have an empty class, that you can use as a singleton so you can have any functions you want.

I still don't understand the relation with overriding functions, but you basically describe an utility class with static functions:

`util.gd`
```gdscript
class_name Util
static func foo(a, b) -> int:
    return a + b
```
`bar.gd`
```gdscript
func _ready():
    print(Util.foo(3, 4)
```

And I dont understand the example you give with it... the example sounds like just a dictionary.

**Comment by Zylann** [comment]
And that example code doesn't work? It's basically still a fancy dictionary. You can put that in an autoload and it should work.

**Comment by xsellier** [comment]
It doesn't because of the `set` `get` functions that belongs to the `Object` class.

**Comment by Zylann** [comment]
If you use `_set` and `_get` for Godot it means adding extra code to `get` and `set`, this is one way you can achieve what you want to do here. You can write all the code you wanted in `_get` and `_set`, and Godot will still allow you to call `get` and `set` AND take the `_get` and `_set` into account.

**Comment by xsellier** [comment]
Still doesn't solve my naming issue.

**Comment by akien-mga** [comment]
This was changed in #54676. It's being reconsidered / further discussed in #54949.

**Comment by StraToN** [comment]
@akien-mga #54949 seems to concern member variables only, not functions, which are the problematic point here.

**Comment by KoBeWi** [comment]
You are supposed to override only virtual functions and they are all prefixed with `_` (e.g. `_ready()`, `_get_drag_data()` etc.). We should give a clear error when trying to shadow a built-in function, but non-virtual overriding likely won't happen.

**Comment by xsellier** [comment]
> You are supposed to override only virtual functions and they are all prefixed with `_` (e.g. `_ready()`, `_get_drag_data()` etc.). We should give a clear error when trying to shadow a built-in function, but non-virtual overriding likely won't happen.

Thank you for those explanations. However it would be better that behavior is describe somewhere (since it didn't behave that way in Godot 2), and also Godot itself should raise an error to warn the user. Actually, this is **not** user friendly.

**Comment by CsloudX** [comment]
I code like this:
```
class Test
    enum Type{Input,Output}
```
It will report error: `Enum member Input has the same name as a global class`
I think this was valid code, because I can use it like this: `Test.Type.Input`

**Comment by xsellier** [comment]
Another use case:
`set_owner` and `get_owner`, those functions are defined by godot so not usable in GDScript.
Wasted time because of that.

**Comment by akien-mga** [comment]
To repeat what @Zylann was explaining, not all functions in Godot can be overridden. That's the same in any language, some functions are virtual, others are not. In Godot's scripting API there's another level of indirection as some functions might be virtual in C++ but that doesn't transfer to the scripting API. "Virtual" methods are implemented by calling methods via StringName, which is much less efficient than what a C++ compiler can do for you with the virtual function table.

So there's no intention to support overriding *any* method such as `Object.set` or `Node.set_owner`. These methods are used by the engine API internally and making them overridable would lead to terrible performance, and a very simple footgun for users to break the API by changing the way things are expected to behave internally (i.e. if you were to replace `set_owner` and expect it to be called internally, you'd have to make sure that you reimplement exactly what the C++ method does - which might not even be possible).

Now, we should indeed add explicit warnings whenever you shadow such a method unknowingly, as the way it behaves is not intuitive at all (and can still lead to bugs for internal engine calls using `call` or `call_deferred`):

```gdscript
var test = 0

func set(property, value):
	print("Setting '%s' to '%s'." % [property, str(value)])
	set(property, value)

func _ready():
	test = 1
	set("test", 2)
	self.set("test", 3)
	$".".set("test", 4)
	call("set", "test", 5)
	$".".call("set", "test", 6)
	call_deferred("set", "test", 7)
	$".".call_deferred("set", "test", 8)
	get_script().set("test", 9)
```

This prints:
```
Setting 'test' to '3'.
Setting 'test' to '5'.
Setting 'test' to '6'.
Setting 'test' to '7'.
Setting 'test' to '8'.
```

IMO it's far from obvious, and not something we should aim to support.

So I would ensure that shadowing an internal function raises a warning, as done in #54949 for variables.
IMO this could even be an error, but given the reactions to #54676, I guess we can start with a warning and let people who still want to play with fire mark the warning as ignored and accept they're using an unsupported feature.

**Comment by Mickeon** [comment]
I know it is outstandingly difficult to reimplement, but it is worth reconsidering this stance, at least by adding way more overridable methods, since these "issues" are being reported by the userbase fairly frequently, as it often is limiting, compared to 3.x.

**Comment by MikeSchulze** [comment]
I need too to overwrite **all** functions to buld a spy to verify function interactions.
This was still possible on Godot3 if this will be not allowed anymore than please give me a way to check if a function called or not.
If this still possible than please tell me how to spy a function call without overwriting a function.

I need it! My plugin GdUnit3 provides spy and mock to verify interactions on a instance.

**Comment by MikeSchulze** [comment]
Hello I don't understand why you want to restrict developers so much, there is no real reason for that.
Whether shadowing or override this is blurring in my eyes. 

Overriding methods/functions is still a valid option in many languages, and was possible in Godot 3.x.
Instead of responding to the users, it is worsened, I would like to refer only to the sorry topic private/protected/public accessors there is stubbornly blocked.
What speaks against it?
It is only important that if you overwrite a function a warning, error (configurable) gets as feedback in the editor to avoid accidental overwrites.

So please don't bring in such regressions! 
This makes me frustrating.

Here is my suggestion
a) allow function overrides
b) show a warning for overwritten functions
c) introduce an annotation `@override` to mark as allowed override and disables the warning
d) an editor setting to configure accidental overrides as a warning or error
e) finally respond to the users and introduce the long requested private/protected accessors
   @private, @protected
   This would also help to disallow overwrites if explicitly requested by the dev

**Comment by Zylann** [comment]
I feel `@override` would not be the right name for this though, the problem is to allow *shadowing core class methods*. `@override` would make it look like it makes it work like a virtual function override, when it doesn't, and has limitations. Maybe something like `@overwrite` or `@shadow` or `@scriptonlyoverride`, or whatever retains the fact it's not a typical override like every other language.

**Comment by MikeSchulze** [comment]
Again my question, why is it forbidden to override core class functions?
I want to explicitly overwrite it and not shadow it!

I have written a unit test plugin 'GdUnit3', which provides mock and spy functionality and I'm explicitly instructed to be able to overwrite core functions to carry if and how often they were called.

And again this is a strong limitation compared to Godot3

**Comment by FeralBytes** [comment]
Can the speed up really be justified to remove what was existing functionality in 3.0, if so I am curious as to just how much, I am not demanding numbers just curious if any one has numbers.

Would it be possible to allow the over-ride of core function calls at least for debug builds but release builds could still retain the speed to allow the testing in debug builds?

In order to work around this new feature, developers will need to write additional functions to make the call to a core class in order to successfully Spy on what functions were called. This is a waste of developer time by writing additional lines of code, if it could be avoided I would prefer such a solution.

**Comment by Calinou** [comment]
> Can the speed up really be justified to remove what was existing functionality in 3.0, if so I am curious as to just how much, I am not demanding numbers just curious if any one has numbers.

The GDScript implementations are entirely different between 3.x and 4.0, so it's not possible to compare performance with this change alone.

**Comment by KoBeWi** [comment]
Here are some numbers.

Script 1 (overwrites a function)
```GDScript
extends RandomNumberGenerator

func randi_range(a, b):
	pass
```

Script 2 (calls script 1)
```GDScript
extends EditorScript
@tool

func _run() -> void:
	var rng: RandomNumberGenerator = preload("res://FakeRNG.gd").new()
	
	var time = Time.get_ticks_usec()
	for i in 1000000:
		var test = rng.randi_range(0, 100)
	print(Time.get_ticks_usec() - time)
```

Execution time in 3.x `release_debug` build:
**210ms**

Execution time in 4.0 `debug` build:
**140ms**

In 4.0 this executes 50% faster, *despite I used a debug build which comes with severe speed handicap*. If we compared official builds, the difference would be even greater. This kind of optimization would be impossible if functions were overwritable.

**Comment by MikeSchulze** [comment]
`This kind of optimization would be impossible if functions were overwritable.`
As far i understand Godot4 used function ptr to jump to the right method.
Why should this be a problem for overriding?
Its just an another ptr to the overriden method or not?

**Comment by KoBeWi** [comment]
Overriding *could* be used if ptr calls can't be determined (that is, calling a method on untyped object), but then you'd get inconsistent behavior. It would be confusing.

**Comment by Mickeon** [comment]
Worth keeping an eventual solution in the back of the head. `super()` on virtual calls (`_process`, `_ready`...) became mandatory in Godot 4.0 instead of implicit, because it was unexpected behavior to a lot of users (even if it was intentional and documented). One _could argue_ that the same could be said for being able to override built-in functions **_to an extent_**. It is no longer "allowed", and it was not really accounted for, yet some users believe this to be the expected behavior.

**Comment by MikeSchulze** [comment]
Sorry, but any good programming language allows us to override methods to extend existing functionallities.
Now all of a sudden not allowing it anymore will push many devs over the head.
The argumentation to write an equivalent function with underscore that calls the core function is total nonsense.
This just creates useless code noise and forces us to define pseudo names for existing core functions.
A simple example, you want to log if a child node was added.

Godot 3:
```gdscript
func add_child(node: Node, force_readable_name: bool = false) -> void:
	LOG.debug("node added %s" % [node])
	.add_child(node, force_readable_name)
```

for Godot4 it would look like this
```gdscript
func _add_child(node: Node, force_readable_name: bool = false, internal := INTERNAL_MODE_DISABLED) -> void:
	LOG.debug("node added %s" % [node])
	super.add_child(node, force_readable_name, internal)
```
now we have two functions with almost the same name `_add_child` and `add_child`.
Furthermore it leads to confusion when providing such an API, should i call `_add_child` or `add_child`.

**Comment by KoBeWi** [comment]
> Sorry, but any good programming language allows us to override methods to extend existing functionallities.

No they don't. Unless you say that C++, C#, Rust or any compiled language are not good. They require you to explicitly mark overrideable functions as virutal and most of their functions aren't virtual.

**Comment by MikeSchulze** [comment]
ok `good programming language` was probably said a little too harshly ;) 

to get ahead here and solve my own problem.
How can I determine if and how often and with which arguments a function was called without overwriting it?

Due to the new limitation I can not realize a spy or mock on core classes anymore

Best regards

**Comment by firebelley** [comment]
Just chiming in to say in my issue #69765 overriding would be really nice for plugin development. I wanted to have a `RandomTimer` class ([see here for Godot 3 implementation](https://github.com/firebelley/godot-addons/blob/master/node_library/scripts/random_timer.gd)) with the same methods as the build in `Timer` so that it can be used in the same way. I don't really want to tell users "This is a timer, but make sure to call start_random instead of start, otherwise it won't work as expected". Lots of room for error there.

**Comment by dalexeev** [comment]
3.x:

![](https://user-images.githubusercontent.com/47700418/209368611-1861e422-c4e1-4a4e-ae22-b1e57b5ba4c6.png)

4.0-dev:

![](https://user-images.githubusercontent.com/47700418/209369109-b11ce7e0-9f47-4986-a641-c8384a3407ee.png)

In both 3.x and 4.0-dev you can't really override non-virtual methods (to have C++ call them), this only works for GDScript.

I'm not sure if the behavior in 4.0 should be the same as in 3.x, or if we should completely disallow overriding non-virtual native functions. But if we choose the first option, then we should add a warning and/or make another indicator (blue arrow).

**Comment by tx350z** [comment]
I'm a bit confused by this debate. There seems to be many comments about to how difficult it is to allow overriding (or shadowing) methods of built-in classes. Since this was a capability in 3.5.1 it suggests it's difficult only because of engine changes made for "GDScript 2.0". That fact alone means it's a regression. Call it a bug or a feature, but it's a regression.

So here are a few serious questions.
1. If method overriding/shadowing is allowed for custom methods in custom classes, why not built-in classes? What's so special about built-in classes?
2. If built-in classes are so special why not make them all FINAL so they can't be extended?
3. Is this just a case of "trying to protect the programmer"? If so, from what?
4. Is GDScript intended to be an object-oriented-like language? Method overrides are a core feature of OOP languages.

We are talking about a language feature that previously existed, is expected to exist, and was widely used.  If it is truly difficult to support method override/shadowing in 4.0, maybe the solution needs to be completely revisited?

In the old days issues like this were referred to as "trying to fix the solution rather than solving the problem".

**Comment by YuriSizov** [comment]
@tx350z It didn't exist in 3.x. Unless the method is registered in a way that allows extending it with scripting, which few are, the engine cannot call into it, it has no idea that you've overridden the method. What might have worked is scripts calling methods of other scripts directly. But it wasn't really overriding the method, it was indeed just shadowing it for the scripting side of things, while the engine was not aware that you might've overridden it.

So it was a bad idea to do it, even if it could be perceived as working in some practical scenarios.

**Comment by KoBeWi** [comment]
> If method overriding/shadowing is allowed for custom methods in custom classes, why not built-in classes? What's so special about built-in classes?

All methods in custom classes are *virtual* by default.

> If built-in classes are so special why not make them all FINAL so they can't be extended?

They are not special. You can extend them and override their *virtual* methods. Every single script extends some class, so making them non-extendable would make the engine literally unusable.

> Is this just a case of "trying to protect the programmer"? If so, from what?

No, it was done for performance. Calling methods in GDScript 2.0 is **much** faster thanks to that.

> Is GDScript intended to be an object-oriented-like language? Method overrides are a core feature of OOP languages.

And GDScript does support overriding *virtual* methods like every OOP language. The behavior in 3.x was a convenient bug that went against the OOP, because it allowed shadowing methods that aren't *virtual*.
The methods that you can override are marked as such in the documentation:
![image](https://user-images.githubusercontent.com/2223172/210354110-9544c1dd-0ed3-47a6-8001-cae264ba69e1.png)

> If this was an intentional change why is it implemented as a silent failure?

Because it's bugged. It's the only reason why this issue is still open.

**Comment by tx350z** [comment]
So the ability to shadow built-in class methods in 3.x was a bug that is now fixed in 4.0?
If my vote counts, I'd like the bug back please.

**Comment by YuriSizov** [comment]
@tx350z It didn't actually work in 3.x. Bringing it back, if it even was sensible, would only create an illusion that you can override built-in methods when in fact you cannot.

**Comment by MikeSchulze** [comment]
> @tx350z It didn't actually work in 3.x. Bringing it back, if it even was sensible, would only create an illusion that you can override built-in methods when in fact you cannot. And shadowing is not a feature of any language, it's a bug or a code smell at the very least.

Thats not true!
I still using override built-in methods on Godot 3.5.1 as build a mock/spy  by fuction doubling and calling than the original implementation.

**Comment by dalexeev** [comment]
In 3.x you can "override" non-virtual methods, but only for GDScript, not C++. That is, if some method is called directly, the C++ original will be called, not your GDScript override (this does not apply to calling via `Object.call`). This is especially noticeable when trying to override a property setter or getter.

**Comment by YuriSizov** [comment]
@tx350z Yes, this will work for scripting, but it won't work if the engine needs to call the same method that you are trying to override. That's why we make a distinction between overriding and shadowing. Shadowing is a potential bug and code smell, we don't recommend getting into this situation, so there is little reason to support it. And apparently, avoiding it improves the execution speed. Overriding is not available at all.

**Comment by dalexeev** [comment]
I think we have two options:

1. Prohibit "overriding" non-virtual methods (this should produce an error).
2. Allow non-virtual methods to be "overridden" (as in 3.x), but generate a warning about it. And also we can change the method override indicator (blue arrow) for this case.

**Comment by YuriSizov** [comment]
> I can't think of a single use case where I want the engine to call my custom functionality.

Whether you generally want to or not, if it was true overriding then the expectation from a programmer would be that the engine would call the override and not the original. Of course, not every public/exposed method is called by the engine, but some do, and consistency is expected. Allowing just shadowing wouldn't be very OOP of us, would it?

And overrides in general _are_ allowed, but we have strict rules that the method should be declared as virtual. It's just not all built-in methods are, for one reason or another (already explained in the discussion above). This is all completely within the OOP principles.

**Comment by tx350z** [comment]
> Whether you generally want to or not, if it was true overriding then the expectation from a programmer would be that the engine would call the override and not the original. Of course, not every public/exposed method is called by the engine, but some do, and consistency is expected. Allowing just shadowing wouldn't be very OOP of us, would it?
> 
> And overrides in general _are_ allowed, but we have strict rules that the method should be declared as virtual. It's just not all built-in methods are, for one reason or another (already explained in the discussion above). This is all completely within the OOP principles.

Four Pillars of OOP:
1 Inheritance: child classes inherit data and behaviors from the parent class **with the ability to extend or replace parent behaviors**
2 Encapsulation: containing information in an object, **exposing only selected information**
3 **Abstraction: only exposing high-level public methods for accessing an object**
4 **Polymorphism: functions bearing the same name, but each may have different behaviors**

**Comment by akien-mga** [comment]
Reopening for now as #72487 was reverted.

**Comment by tx350z** [comment]
Consequences:

```
● String get_class() const

Returns the object's built-in class name, as a String. See also is_class().

Note: This method ignores class_name declarations. If this object's script has defined a class_name, the base, built-in class name is returned instead.

```

`SCRIPT ERROR: Parse Error: The method "get_class" overrides a method from native class "Object". This won't be called b)`

**Comment by YuriSizov** [comment]
Yes, and this was never going to work correctly.

**Comment by tx350z** [comment]
Even though it did work as needed in 3.x. At this point it appears none of my 3.x apps, libraries, and tools are upgradable to 4.x.

**Comment by Zireael07** [comment]
@tx350z It was a bug/inconsistency that you exploited

**Comment by dalexeev** [comment]
> Even though it did work as needed in 3.x.

In 3.x, this is also not overriding, but shadowing. You're just creating another method with the same name, which is definitely confusing. In 4.0, an additional problem is that even GDScript can't always distinguish between these methods. We could fix this, but it would hurt performance for no good reason, since the behavior in 3.x is still not correct and expected by users ("I've overridden `queue_free()`, why isn't it called?").

<details>
<summary>Discussion in Rocket Chat</summary>

![](https://user-images.githubusercontent.com/47700418/219399685-e66785af-d0e8-484d-a614-590dde1bce12.png)
![](https://user-images.githubusercontent.com/47700418/219400190-fddbe5f6-22b9-45bf-8abb-5ed3f14d5ec9.png)

</details>

Duplicate another my comment:

---

Why it's done:

* The engine doesn't call your "overrides" in most cases (unless it calls them via `call()`). This behavior is also present in 3.x, it's not a bug, it can't be fixed without a huge performance hit, it would introduce a lot of new bugs due to the violation of the engine's expectations when the user overrides the method incorrectly.
* Unlike 3.x, the "override" call may not happen even in GDScript, due to type collisions (in some cases, GDScript calls a native method for optimization, unless you work around it with a cast or `call()`). For this reason, non-virtual native methods should never be "overridden", even if you know about the previous point and don't worry about it.

A few tips:

1. You can disable or ignore this warning, but correct behavior is not guaranteed.
2. This warning does not apply to native **virtual** methods and any custom methods. You can override them.
3. If you need to customize some engine method, you should create a wrapper with a different name, not "override" it.

**Comment by tx350z** [comment]
I think I found a solution for my needs in HxGodot. As much as I've come to love coding GDScript, the 4.0 update has too many new barriers to overcome.

**Comment by MikeSchulze** [comment]
@GodotDevs it an always upcomming topic and you can see the useres want to have the possibility to override a core function.

From technical perspective so far i anderstand, the core change in GdScript 2,0 is instead of calling functions by name you call it via function pointer.

Why you not provide a `@override` annotation and check when a class is loading to use a function table instead of function pointer to achive it?

**Comment by YuriSizov** [comment]
@MikeSchulze Again, this didn't work in Godot 3.x either. It is not related to GDScript, it's just how Godot is, and always was. If a method is not made to be overridable, you *can't* override it, neither from scripting, nor from extensions. The only change in GDScript that is relevant here is that we now _tell the user_ that what they are trying to do is wrong and is not going to work.

There are no plans to allow overriding any core function, because it's impractical from the performance perspective. And once again, this is not a decision of the GDScript team, it's a core decision.

**Comment by KoBeWi** [comment]
Virtual methods all start with underscore (`_`) and are also labelled as virtual in the documentation.
