### ISSUE TITLE
"Stack Frames" now always empty

### ISSUE THREAD

**Issue by Keyaku** [godotengine/godot#5510]
**Operating system or device - Godot version:**
Mac OS X 10.11.5 - Godot 2.1- f6725f9
Built with flags `scons platform=osx theora=yes`

**Issue description** (what happened, and what was expected):
Suddenly — doesn't even matter if I go a few days back in commit history — I have the "Stack Frames" tab always empty.

Essentially, if I put in a breakpoint, the line is not highlighted and clicking "Step Over" isn't following the script.

**Steps to reproduce:**
1. Create a breakpoint
2. Test scene
3. Play the edited scene (F6)
4. Wait for breakpoint

**Link to minimal example project** (optional but very welcome):
It's with one specific project that I'd like not to share. New projects seem to work fine; in fact, after testing with a new project, I reopen this one, it works at the *very first* breakpoint, but then I click on "Step Over" and the "Stack Frames" window empties itself again. Remains empty in subsequent tests.

I honestly don't know whether to consider this a bug or just something I screwed up in the settings.

**Comment by vnen** [comment]
Are you using threads or inner classes? Breakpoints don't work on threads and might still be buggy with inner classes even after the recent fixes.

If you think it might be the settings, try to move your settings file elsewhere so Godot generates a new one, then see if it's working or not.

This might also be related to the Debug Host setting (in Network category), especially if you use a VM which creates custom network interfaces.

**Comment by Keyaku** [comment]
> Are you using threads or inner classes? Breakpoints don't work on threads and might still be buggy with inner classes even after the recent fixes.

I'm using no threads (although I have thread_model=Multi-Threaded turned on, switching it back to Single Safe didn't seem to make a difference)

> If you think it might be the settings, try to move your settings file elsewhere so Godot generates a new one, then see if it's working or not.

Apparently, it's something in the engine.cfg file. I just swapped to a fresh one and it works fine. I'll be putting the the cfg file back together until I stumble upon the cause of the problem.

Thanks for the help!

**Comment by Keyaku** [comment]
> Are you using threads or inner classes? Breakpoints don't work on threads and might still be buggy with inner classes even after the recent fixes.

I got it: It has to do with Autoloading a certain script I wrote that can load scenes in a thread. This seems to be the root of my problems, but I still find it odd since I'm not even using the node, yet removing from autoload fixes my problem.

I'll have to carefully debug this one and see why this is happening.

**Comment by pink-ink** [comment]
I had the same problem like Keyaku, but a different root cause.
In the project.godot file below [Network] there was this line:
limits/packet_peer_stream/max_buffer_po2=64

I stopped Godot, removed this line and restart Godot again. Then the degugger was working properly.

The malfunction looks like that:
![Bildschirmfoto 2022-11-04 um 02 54 28](https://user-images.githubusercontent.com/12589334/199878306-41b2926f-cdf8-4551-96a8-f0aa6d9bda61.png)

After deleting the line it looks like that and I can see a line number again, where the error occured:
![Bildschirmfoto 2022-11-04 um 02 56 09](https://user-images.githubusercontent.com/12589334/199878393-209d4167-28ec-4fcd-971c-9c6b3e0e2747.png)

This line was the culprit in my case:
![Bildschirmfoto 2022-11-04 um 02 58 54](https://user-images.githubusercontent.com/12589334/199878578-3632e94f-7f57-4354-b72b-9dc0dc7eed83.png)

I hope it helps somebody with the same problem.
