### ISSUE TITLE
Classref: Enum constants are no longer sorted by value

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5512]
**Operating system or device - Godot version:**
Any system, current master branch.

**Issue description** (what happened, and what was expected):
Most likely since #5350, all elements are sorted alphabeticallyl in the classref. This is however not what we want for enum constants, which should stay sorted by value, as it's a lot more meaningful.

See e.g. http://docs.godotengine.org/en/latest/classes/class_inputevent.html or (a lot more problematic, as different enums get mixed together) http://docs.godotengine.org/en/latest/classes/class_@global%20scope.html

CC @vnen and @bojidar-bg.

**Comment by vnen** [comment]
Well, it depends. Not sure if you understand the way they're sorted. Citing my PR:

> Constants are sorted by value if they have the same `PREFIX_` otherwise alphabetically.

And Global Scope (which has [tons of constants](http://docs.godotengine.org/en/latest/classes/class_@global%20scope.html#numeric-constants)) seems much better organized in the current way (though even sor by value is arguable if you look at `JOY_` constants, where there are lots with the same value). There are smaller examples too like [Animation](http://docs.godotengine.org/en/latest/classes/class_animation.html#numeric-constants). At least for me it makes more sense to organize that, since you can find for type first and for value within the type.

For Input it is a problem because constants don't share a `PREFIX_`. So either hard code a way or another for some cases or pick a favorite.

**Comment by akien-mga** [comment]
Check the ERR_ in Global Scope, they're clearly not sorted by value. See also how the BUTTON_ and BUTTON_MASK_ get mixed. IMO the previous natural sorting was much more meaningful for constants.

**Comment by vnen** [comment]
I don't know that happened to `ERR_` (another paranormal activity). For `BUTTON_` it's more obvious since they share the prefix.

Natural sort may be better (the way they show in editor help) but the XML merge seems broken since it was randomly reordering the constants (#5337).

**Comment by reduz** [comment]
constants should be left in the same order that they came from

**Comment by reduz** [comment]
they are already organized manually when registered, so no sorting should happen

**Comment by vnen** [comment]
Then the XML merging must be fixed. I'll try to take a look soon.
