### ISSUE TITLE
Crash when printing array that contains itself

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55256]
### Godot version

3.4 / 4.0

### System information

W10

### Issue description

When you do do
```GDScript
var a = []
a.append(a)
print(a)
```
Godot will crash.

I checked how Python handles it and it prints `[[...]]`.

### Steps to reproduce

See above.

**Comment by Ev1lbl0w** [comment]
Regression from #35816. I've tested on `3.4` and it works fine since it doesn't have these changes yet.

I have incremented the `recursion_count` which fixes the issue, but the output has changed to:
`[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[...]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]`
*(aka 100 recursions before the trigger is called, returning `[...]`)*

@touilleMan I see that the PR was to change the `==/!=` behavior specifically. Do you think, for the `stringify` method, the old stack behavior can be reverted, or is there a reason for it's changes too? I've been trying some ideas on how to fix this but I haven't found a clean way to do it, and I think it's gonna be hard to fix this properly under these new changes.
