### ISSUE TITLE
ConvexPolygonShape2D.Points returns empty array from Mono C# script

### ISSUE THREAD

**Issue by jamiebuckley** [godotengine/godot#55283]
### Godot version

3.4 stable

### System information

Windows 10 and MacOS

### Issue description

Accessing the points array of a ConvexPolygonShape2D returns an empty list when accessed from a Mono C# script, but works fine in GDScript.  In Mono, calling the Points accessor returned by ConvexPolygonShape2D returns an empty array.  In GDScript, this returns a correctly populated array of Vector2s.

### Steps to reproduce

Attach following to an Area2D with a polygon shape added in the editor
**Non-working CS example**
```
    public override void _Ready()
    {
        var shapeOwners = GetShapeOwners();
        
        var shape = (ConvexPolygonShape2D)ShapeOwnerGetShape((uint) (int)shapeOwners[0], 0);
        GD.Print(shape.Points);
    }

// Prints "Godot.Vector2[]"
```

**Working GDScript Example**
```
extends Area2D


func _ready():
	var shapeOwners = get_shape_owners();
	var shape = shape_owner_get_shape(shapeOwners[0], 0);
	print(shape.points);

// Prints "[(-1, -1), (3, -1), (3, 2), (-2, 3)]"
```

The original use case that surfaced this was when trying to get the collision polygons of a tile from a tileset, but it seems to happen anywhere with a Shape2D and a polygon.
 

Reproduceable example attached - there are two Area2Ds each with a ConvexPolygon2D on them, both with scripts accessing the points and printing to the console on ready.

Run the project and you should see:

Godot.Vector2[]
[(-1, -1), (3, -1), (3, 2), (-2, 3)]

### Minimal reproduction project

[godot-mono-shape2d-issue-main.zip](https://github.com/godotengine/godot/files/7594395/godot-mono-shape2d-issue-main.zip)

**Comment by kleonc** [comment]
>In Mono, calling the Points accessor returned by ConvexPolygonShape2D returns an empty array.

It's not returning an empty array, it's just `GD.Print()` printing out the type instead of the contents of the array. You can easily print the points one by one in a loop.

The problem is that `GD.Print(arg)` passes in the result of `arg.ToString()`:

https://github.com/godotengine/godot/blob/00342b7d36f09c22e32bd75ce459e1fa983113dc/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs#L279-L282

https://github.com/godotengine/godot/blob/00342b7d36f09c22e32bd75ce459e1fa983113dc/modules/mono/glue/GodotSharp/GodotSharp/Core/GD.cs#L108-L116

and `Vector2[].ToString()` seems to be returning its type as a string.

Probably either `Vector2[].ToString()` would need to be overridden properly, or maybe in case of arrays `ToString()` shouldn't be called on them in the first place and passing just the array itself would fix the issue? :thinking: Not sure what's the correct way to solve it.

**Comment by raulsntos** [comment]
I think printing the type is expected in C#, that's how every type works in C# if you don't override `ToString`. And it behaves just like `Console.WriteLine`.

Since an array is the `System.Array` type provided by C#, we can't override `ToString` but you can easily print its contents with the `string.Join` method:

```csharp
GD.Print(string.Join(", ", shape.Points));
```

**Comment by jamiebuckley** [comment]
Thanks, yep - that's an issue in the example I've uploaded there - the original issue was that the array was empty in the mono example, as opposed to a problem with ToString specifically, I'll upload a fixed example in a bit.

**Comment by jamiebuckley** [comment]
Closing this, while trying to create the example realized this was a bug in my code not Godot (new Transform2D() vs Transform2D.Identity), my bad.

Thanks for looking into it @raulsntos and @kleonc, it was that ToString mistake that was leading me down an incorrect debugging rabbithole.
