### ISSUE TITLE
.resume() -ing a function causes it to be called again

### ISSUE THREAD

**Issue by spookdogg** [godotengine/godot#5529]
**Operating system or device - Godot version:**
Windows 7 - 2.0.3

**Issue description** (what happened, and what was expected):
When .resume() -ing a .yield() -ed function, that function is resumed but it is also called again

This means that if you attempt to .yield() and then .resume() _ready(), the game crashes (due to the fact that the game crashes when _ready() is called in scripting after it's initial calling once the script is loaded, which I assume is intentional)

**Steps to reproduce:**
1. Create scene with single node with attached script
2. .yield() and then .resume() _ready
3. Observe crashing of game

**Link to minimal example project** (optional but very welcome):
[Yield Test.zip](https://github.com/godotengine/godot/files/345040/Yield.Test.zip)

**Comment by bojidar-bg** [comment]
Either I can't confirm, or I can't understand the issue.
I get a GDScript stack overflow here from the recursion in `_ready` and `func1`.
Here is the script which was given by the OP (with some additional formatting):

```gdscript
func _ready():
	print("1")       #A
	func1()          #B
	yield()          #C
	func1().resume() #D

func func1():
	print("2")        #E
	_ready().resume() #F
	yield()           #G
	print("3")        #H
```
Let's see what happens when it runs:
* `_ready()` is called
  * it prints `"1"` (A)
  * **it then calls `func1()` (B)**
    * then, `"2"` is printed. (E)
    * **then, `_ready()` is called (F), and it's result would be `.resume()`-ed**
      * it prints `"1"` (A)
      * **it then calls `func1()` (B)**
        * then, `_ready` and `func1` get into mutual recursion, and overflow the stack no matter its size.
    * if something magical happens, and it gets out of the recursion, `_ready()` gets finally resumed (C)
      * then, `func1()` is called (F), and it's result would be `.resume()`-ed
        * this causes additional recursion, as it would call `_ready` again.
      * if something magical happens, and it gets out of the recursion, `func1()` gets finally resumed (G)
        * then, `"3"` is printed. (H) (but this doesn't stop the recursion, unless your magic continues to modify the memory in strange ways. Good luck with that.)

I guess @spookdogg didn't notice that he isn't resuming the *already-running* instance of `_ready()` or `func1()`, but instead, calling a **new** "instance" of those functions, and resuming it in turn.

**Comment by vnen** [comment]
This has been stalled for a long time and it seems like a misunderstanding from the OP, no really a bug. I don't see a reason to keep this open.
