### ISSUE TITLE
TextureButton needs an extra texture field for when both pressed and focused

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#55400]
### Godot version

3.4 stable

### System information

Windows 10

### Issue description

At the moment, TextureButton has fields for setting a texture for a pressed state and a focused state, but has no field for when the control is both pressed and focused.  This is needed for when it is being used as a toggle button and can be displayed in both states for long periods of time.

### Steps to reproduce

Create a new TextureButton.  Take a look at the fields available under the Texture submenu.

### Minimal reproduction project

Create an instance of a texture control.  Try to find a field for a state coresponding to both pressed and focused.

**Comment by Calinou** [comment]
The focused state is displayed as an *overlay* of the current texture. If you give the focus texture a transparent background and design it as an outline, it will be displayed when the button is pressed.

**Comment by abaum27** [comment]
Is there a solution for texture buttons that shift position when pressed? Since the focus is displayed as an overlay, it's unable to move with the text of more "dynamic" UIs. In my example, the 1 player button has the focus texture overlay, but when I press enter, it's unable to move with the pressed texture. I'm able to accomplish this going from hover texture to pressed texture though.
![TextureButton](https://user-images.githubusercontent.com/18707023/195522518-97d9cc37-6c25-413f-9f33-c32353f2dbed.gif)
