### ISSUE TITLE
RichTextLabel Incorrect justified alignment

### ISSUE THREAD

**Issue by DimitriyPS** [godotengine/godot#5543]
Godot 2.0.3

When text justified alignment is ([fill]), the last line of the paragraph is not correct. Especially if RichTextLabel occupies almost the entire width of the screen and the last row consists of 2-3 words, it looks very ugly.

![8239753](https://cloud.githubusercontent.com/assets/11189223/18159339/cfe94ac8-7030-11e6-91e0-61679fb66420.png)

**Comment by Calinou** [comment]
I presume text filling is forced even if the line contains only a few words. The last line alignment should be configurable (left, center, right, fill), probably.

**Comment by bojidar-bg** [comment]
@Calinou Most text editor would assume left-alignment for the last line, but it makes sense to be configurable indeed.

**Comment by DimitriyPS** [comment]
> Я не читал весь разговор, но это дубликат # 4591 ? (Edit: или # 4159 )

I can't be absolutely sure, but my problem is similar to: # 4591

**Comment by DimitriyPS** [comment]
I can't specify conditions for the repetition, but I found that when the width alignment periodically disappears the last word in the last line.

In General had to abandon the alignment in width .

**Comment by Calinou** [comment]
**Bugsquad edit:** This issue is still relevant as of commit https://github.com/godotengine/godot/commit/d87307d850186d27d2c27c5916ec8c4744c14979.

![RichTextLabel fill issue](https://user-images.githubusercontent.com/180032/38608180-ef569a0a-3d7a-11e8-84bd-73a7d899aa26.png)

**Comment by DimitriyPS** [comment]
Please add this to the milestone Godot3.1.

**Comment by DimitriyPS** [comment]
> I presume text filling is forced even if the line contains only a few words. The last line alignment should be configurable (left, center, right, fill), probably.
> 
> Maybe use something like [fill=left], [fill=center], [fill=right] and [fill=fill]?


It's unnecessary. Even in the typography is not often in demand. All you need from Rich Text Label is to display the information in the correct form.
Please fix the left alignment of the last line.
Please include this in release year from 3.1, 2 years already waiting.

**Comment by scmccarthy** [comment]
I believe the main issue here is that the fill justification is being applied to all lines, not only "full" lines that end due to word wrap. My proposed fix is to take note when we wrap lines and only apply the fill justification in those cases. In other cases (line ends with a newline, or it's the final line in the text), we should simply perform left alignment.

I have a fix ready and will make a pull request if this sounds good. (As a new contributor, I don't want to jump the gun!) Below is some test text before and after applying my fix.

![godot broken fill](https://user-images.githubusercontent.com/4999445/47535986-c6530100-d872-11e8-9362-5f017a473bf1.PNG) ![godot fixed fill](https://user-images.githubusercontent.com/4999445/47535989-c94df180-d872-11e8-8d26-926898d7bdac.PNG)

One may argue that not everyone wants left alignment as the default for non-filling lines, and that's fair. However, I am confident that no one wants the current buggy behavior, and left justification is likely to be by far the most common use case as DimitriyPS says. Given the general roughness of the bbcode features I think this minimal fix is the correct one for now.

**Comment by scmccarthy** [comment]
Additional support for this fix: it mirrors the behavior of Label.

**Comment by bojidar-bg** [comment]
> I have a fix ready and will make a pull request if this sounds good. (As a new contributor, I don't want to jump the gun!)

OFC, make a PR. There is no way we can accept your fix if you don't send it to us :wink:
