### ISSUE TITLE
When iterating over `enum` goes to infinite loop

### ISSUE THREAD

**Issue by Amatrelan** [godotengine/godot#55491]
### Godot version

v4.0.dev.custom_build [125c5eabc]

### System information

Linux, x11, nvidia

### Issue description

```gdscript
extends Node2D

enum Enum {
  ONE,
  TWO
}

func _ready():
  for each in Enum:
    print(each)
```

```txt
--- Debugging process started ---
Godot Engine v4.0.dev.custom_build.125c5eabc - https://godotengine.org
Vulkan API 1.2.200 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2070 SUPER
 
0
1
2
3
4
5
6
7
8
...
257357
257358
257359
257360
257361
257362
257363
25[...]
  [output overflow, print less text!]
--- Debugging process stopped ---
```
Causes infinite loop and iterates over integers (previously printed `KEY` and not `VALUE`, I prefer this but there should be way to say what is iterated over `ENUM.keys()` and `ENUM.values()`)

On Godot 3.4 same script would print out:
```txt
ONE
TWO
```

### Steps to reproduce

- Create any scene
- Put script to root
- Copy example script to *.gd
- Run 

### Minimal reproduction project

[EnumLoopInfinity.zip](https://github.com/godotengine/godot/files/7628164/EnumLoopInfinity.zip)

**Comment by cdemirer** [comment]
I believe this is not an infinite loop, but a loop of `value of ptr to underlying DictionaryPrivate` iterations.

Using `--test gdscript-compiler`:
```
Disassembling _ready()
 0: line 9:   for each in Enum:
 2: assign stack(5) = const({ONE:0, TWO:1})
 5: for-init (typed INT) stack(3) in stack(5) counter stack(4) end 26
 10: jump 17
 12: for-loop (typed INT) stack(3) in stack(5) counter stack(4) end 26
 17: line 10:     print(each)
 19: call-utility stack(6) = <unknown function>(stack(3))
 24: jump 12
 26: == END ==
```

`Enum`'s type is considered to be `int` here, due to:
https://github.com/godotengine/godot/blob/a074ceefcd74d903579c7b256a07e7e531141b07/modules/gdscript/gdscript_compiler.cpp#L143-L148

which results in bytecode that assumes int as the container type (e.g. as in `for i in 10`).
