### ISSUE TITLE
[4.0] double clicking on a word is broken

### ISSUE THREAD

**Issue by CrezyDud** [godotengine/godot#55588]
### Godot version

v4.0.dev.custom_build [bbff64eee]

### System information

Linux, Vulkan

### Issue description

this happened recently probably related to: https://github.com/godotengine/godot/pull/55294
because my mouse is very sensitive to small movements it probably moves my cursor a little when double-clicking, making godot want to perform a drag-and-drop for the word

(the word does get marked for shot (until i release the click))

### Steps to reproduce

double click on word lol

**Comment by Calinou** [comment]
cc @ConteZero

**Comment by ConteZero** [comment]
I use Linux but have never seen it happen, @CrezyDud you have a HiDPI screeen? What's you current DPI setting?

The code in /scene/main/viewport.cpp has an hardcoded value of 10 pixels to detect the start of drag operation:

```
		// Drag & drop.
		if (!gui.drag_attempted && gui.mouse_focus && (mm->get_button_mask() & MouseButton::MASK_LEFT) != MouseButton::NONE) {
			gui.drag_accum += mm->get_relative();
			float len = gui.drag_accum.length();
			if (len > 10) {
				{ // Attempt grab, try parent controls too.
```

**Comment by CrezyDud** [comment]
> I use Linux but have never seen it happen, @CrezyDud you have a HiDPI screeen? What's you current DPI setting?
> 
> The code in /scene/main/viewport.cpp has an hardcoded value of 10 pixels to detect the start of drag operation:
> 
> ```
> 		// Drag & drop.
> 		if (!gui.drag_attempted && gui.mouse_focus && (mm->get_button_mask() & MouseButton::MASK_LEFT) != MouseButton::NONE) {
> 			gui.drag_accum += mm->get_relative();
> 			float len = gui.drag_accum.length();
> 			if (len > 10) {
> 				{ // Attempt grab, try parent controls too.
> ```

no i don't have hidpi

and the bug doesn't occur if i marked the whole line before doing it

**Comment by ConteZero** [comment]
It happens only in TextEdit or also in LineEdit?
It happens when you do a double click within the editor or when you run a project?
It happens always, only if you do a "fast" double click or only if you do a "slow" double click?
It happens only if you keep the left mouse button pressed at the end of double click?
Also if you could make a short video/gif showing the problem this could be useful to understand more.

**Comment by CrezyDud** [comment]
https://user-images.githubusercontent.com/84625713/144702231-d455610c-1676-463b-873f-63c2b0d36f75.mp4

sometimes it works sometimes not, when I'm coding it mostly doesn't

**Comment by CrezyDud** [comment]
`It happens only if you keep the left mouse button pressed at the end of double click?`

it doesn't delsect as long as i hold down lmouse

**Comment by ConteZero** [comment]
The problem with double click selection happens also in LineEdit?
You can try with the input filed "Filter nodes" on the editor Scene tab or with the input filed "Filter properties" on the editor Inspector tab.

**Comment by ConteZero** [comment]
@CrezyDud can you try https://github.com/godotengine/godot/pull/55637 to see if it solves the problem?

**Comment by CrezyDud** [comment]
worked!

![image](https://user-images.githubusercontent.com/84625713/145057630-3e76e3d3-40a2-4e6d-a835-09d04e105ab3.png)
so sometimes, (maybe very small mouse movements)
it focuses more than it should

**Comment by akien-mga** [comment]
Is this still reproducible in 4.0 RC 1 or later?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

**Comment by wyattbiker** [comment]
I had same issues with v4.3.dev5.official [c9c17d6ca], Operating System: Kubuntu 23.10, KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0

I think it's more of a Linux issue since it was happening in other apps, I fixed it changing the Repeat Interval to 100 on the Accessibility mouse settings. Seems to be holding up but time will tell.

![image](https://github.com/godotengine/godot/assets/930478/1450ec2a-e1f1-445a-bb42-67087d9c7baf)
