### ISSUE TITLE
[FBX] Mesh is imported with incorrect skinning

### ISSUE THREAD

**Issue by djmaesen** [godotengine/godot#55592]
### Godot version

3.4 stable

### System information

windows 10

### Issue description

fbx import screws up skinning of mesh.
also godot creates seperate animation layers for non "bone" animated objects, wich isnt ideal. shouldnt it just create a "main" animation layer?

### Steps to reproduce

simply try importing the (attached zip)fbx into godot. skinning is messed up.
works fine and tested in unity and sketchfab

### Minimal reproduction project

[animatedsmg.zip](https://github.com/godotengine/godot/files/7650823/animatedsmg.zip)

**Comment by djmaesen** [comment]
split animation clips on import doesnt work

**Comment by akien-mga** [comment]
This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases).
You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6
This new importer might also be backported for the `3.x` branch eventually.

If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

**Comment by djmaesen** [comment]
> This is probably fixed with the new FBX importer using [FBX2glTF](https://github.com/V-Sekai/FBX2glTF/releases). You can test it in Godot 4.0 alpha 6: https://godotengine.org/article/dev-snapshot-godot-4-0-alpha-6 This new importer might also be backported for the `3.x` branch eventually.
> 
> If you still find issues with these models using the new importer, we suggest opening a new issue with details about the problems in Godot 4.0 alpha 6 or later.

tnx for the effort
it was the c4d exporters that were causing the problems. 
doesnt matter now as i switched to blender as main 3d app. 
the .glt exporter works fine in blender > to godot
