### ISSUE TITLE
Cannot find binary for 'MSBuild (Mono)'; Fedora 34; Both dotnet and mono-complete are installed

### ISSUE THREAD

**Issue by quentincaffeino** [godotengine/godot#55610]
### Godot version

v3.4.stable.mono.official.206ba70f4

### System information

fedora 5.15.5-100.fc34.x86_64

### Issue description

Trying to run mono project and getting a no msbuild executable found. Searching `dnf search msbuild` returned nothing. Searching 'fedora install msbuild' on the internet returned that it is available with `dotnet build` which I have. Both are in PATH.

```sh
$ which mono
/usr/bin/mono

$ which dotnet
~/.dotnet/dotnet
```

### Steps to reproduce

-

**Comment by raulsntos** [comment]
I'm pretty sure `mono-complete` should include the `msbuild` command so this might be an issue with fedora's package, but you might not need it if you use **dotnet CLI** instead of **MSBuild (Mono)** (the setting is in `Editor Settings > Mono > Builds > Build Tool` and **dotnet CLI** should be the default).

Can you try executing the following commands?

- `msbuild --version`
- `dotnet msbuild --version`

**Comment by akien-mga** [comment]
I think `msbuild` is a separate package on their Fedora repos, you need to install it.

**Comment by quentincaffeino** [comment]
```sh
$ msbuild --version
bash: msbuild: command not found...

$ dotnet msbuild --version
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
```

Switching Build Tool to dotnet worked.

Seems that it is not packaged for fedora for some reason. https://github.com/mono/linux-packaging-msbuild/issues/18

Thanks for help
