### ISSUE TITLE
error: package android.os does not exist > Godot export android no gradle linux 32bits .aab

### ISSUE THREAD

**Issue by MiqueiasDevGames** [godotengine/godot#55738]
### Godot version

3.3 STABLE

### System information

LINUX

### Issue description

I'm trying to generate an aab on a 32bits linux without gradle, I managed, but I stop at:

javac -d build -cp ../android-sdk/platforms/android-30/android.jar -cp ../platform-godot/classes.jar gen/com/godot/game/*.java ../ProjetoGodot/android/build/src/com/godot/game/*.java

platform-godot is unzip godot-lib.release.aar ai uses classes.jar

gives the error:
error: package android.os does not exist

I wanted to know how godot exports to android apk without customize template that works and generates apk, could you tell me which javac command godot uses because it doesn't seem to use gradle and it works, so I can generate aab on my 32bits linux using aapt2 32 bits debian testing that I installed, I just need to generate the classes.dex that goes through this process that gives this error.

Tell me what command javac godot uses to generate apk classes.dex when exported without customize template

### Steps to reproduce

javac -d build -cp ../android-sdk/platforms/android-30/android.jar -cp ../platform-godot/classes.jar gen/com/godot/game/*.java ../ProjetoGodot/android/build/src/com/godot/game/*.java

platform-godot is unzip godot-lib.release.aar ai uses classes.jar

gives the error:
error: package android.os does not exist

### Minimal reproduction project

Tell me what command javac godot uses to generate apk classes.dex when exported without customize template?

**Comment by Calinou** [comment]
If your hardware doesn't support running 64-bit Linux, renting a VPS for one month will let you export for Android there (all x86 VPSes are 64-bit now).

**Comment by miqueias9889** [comment]
build .aab

mkdir compiled_resources
mkdir gen

aapt2 compile ProjetoGodot/android/build/res/**/* -o compiled_resources

aapt2 link --proto-format -o temporary.apk -I ../android-sdk/platforms/android-30/android.jar --manifest ProjetoGodot/android/build/AndroidManifest.xml -R compiled_resources/*.flat --auto-add-overlay --java gen

mkdir platform-godot
unzip ProjetoGodot/android/build/libs/release/godot-lib.release.aar -d platform-godot

>>>>until here ok

javac -d build -cp ../android-sdk/platforms/android-30/android.jar -cp platform-godot/classes.jar gen/com/godot/game/*.java ProjetoGodot/android/build/src/com/godot/game/*.java 

>Error: package android.os does not exist


>>>Then I could generate aab without gradle on 32bit linux since gradle says aapt2 doesn't support 32bit


mkdir staging
unzip temporary.apk -d staging
cd staging

mkdir dex
mkdir manifest


dx --dex --output=staging/dex/classes.dex build/

mv AndroidManifest.xml manifest


>>>Assets and kotlin and lib folder taken from unzip apk generated by godot

mkdir root

mv -rf ../kotlin root
mv -rf ../assets staging
mv -rf ../lib staging

zip -r ../base.zip *
cd ..

java -jar ../bundle-all-1.8.2.jar build-bundle --modules=base.zip --output=bundle.aab 

jarsigner -keystore nome.keystore bundle.aab alias

exit


See, that's why I wanted to know how godot generates the apk without cutomize android template and without gradle, it probably goes through javac to generate the classes.dex, could you tell me how?

**Comment by miqueias9889** [comment]
So the focus is here, help me

javac -d build -cp ../android-sdk/platforms/android-30/android.jar -cp platform-godot/classes.jar gen/com/godot/game/.java ProjetoGodot/android/build/src/com/godot/game/.java

How godot generates classes.dex without custom android template without giving this error?
>>>Error: package android.os does not exist

**Comment by Calinou** [comment]
> How godot generates classes.dex without custom android template without giving this error?

I don't know; I don't see any reference to `classes.dex` (or even `.dex`) within the Godot codebase.

Note that Godot's old approach to exporting APKs (without custom builds) required reverse engineering of the format, but this old approach is no longer recommended.

**Comment by miqueias9889** [comment]
So I managed to generate the aab using the method above, if I can resolve this error from package android.os does not exist
ready, I can now generate aab even on 32 bit linux

**Comment by miqueias9889** [comment]
The problem is no longer to generate aab in 32bits linux, but to compile the java file from ProjetoGodot/android/build/src/com/godot/game/*.java

**Comment by miqueias9889** [comment]
Without setting customize template in godot i generate apk by godot, so i thought i was doing something wrong in javac command

**Comment by miqueias9889** [comment]
I put this name Generating Android AAB on a 32-bit operating system to see if in the future or in the present someone shed light on this issue, I'll keep trying

**Comment by miqueias9889** [comment]
Got it, yeah, Got it, now I can develop my game and launch it for android using Godot Engine, Thank you Godot for working on 32bits systems.

**Comment by akien-mga** [comment]
Could you document how you did it? While we likely won't be able to support exporting to Android from 32-bit Godot anymore, if there's a way to do it manually, it would be great if we can document it.

**Comment by miqueias9889** [comment]
OK!!
I was even thinking about doing a project on Github about how to do this, I'll document it and even try to simplify it.

So when I'm done, I'll post it here.

**Comment by miqueias9889** [comment]
Hello again!

I'm building a bash to generate aab from godot projects so far so good, but before getting the resources from a godot generated apk to build my aab, now I wanted to do this without needing to unzip the godot generated apk, but i found two problems because godot generates an apk with assets which contains 2 files project.binary and _cl_ how do i generate it manually?

**Comment by miqueias9889** [comment]
Here it is, if you want to generate an aab for your godot project use https://github.com/miqueias9889/android-generate-aab-manually-linux-i386-and-x86_64/blob/main/README.md

**Comment by miqueias9889** [comment]
@akien-mga 

To generate my aab I use the apk generated by godot with plugins unchecked, to be able to generate without gradle, then I unzip this apk to get the assets folder with the godots assets compiled, this will prevent the plugin from working, for example the plugin Admob, then I add all the dependencies manually and also the lib aar of the plugin, I pass everything to d8, but the plugin is not working.

I would like to know if activating the plugin when exporting changes more than telling gradle to compile the aar plugin lib and download the dependency, what changes in godot for it to make the plugin work?

**Comment by miqueias9889** [comment]
@Calinou 

What does Godot do when compiling so that the plugin is found and activated?


Change Androidmanifest.xml?
or what ?

**Comment by miqueias9889** [comment]
I got it, it was the AndroidManifest that was missing
