### ISSUE TITLE
Clicking to the left of a dropdown checkbox will check the checkbox

### ISSUE THREAD

**Issue by jitspoe** [godotengine/godot#55774]
### Godot version

3.4

### System information

Windows 10

### Issue description

Clicking to the left of a checkbox to drop down (ex: selecting resources to export) can check the checkbox.  This was particularly frustrating in my case, because I had a large list of levels I wanted to export and just needed to add one, but I clicked well to the left of the checkbox to avoid accidentally checking it, and ended up checking it anyway, meaning I had to completely redo my list of levels to export.

### Steps to reproduce

In a project that has subdirectories, Project -> Export, under the resources tab, select "Export selected resources".  Click to the left of the dropdown arrow:
![image](https://user-images.githubusercontent.com/7751182/145507893-5764900e-f0a2-4524-a56b-dc0b3f80fc0e.png)
Note that, instead of opening/closing the dropdown, the checkbox will check.

**Comment by timothyqiu** [comment]
Did you mean clicking "left of the dropdown arrow" instead of "left of the checkbox"? Clicking _on_ the dropdown arrow expands/collapses the tree for me.

Clicking on the tree item itself toggles the check. And left of the dropdown arrow is designed to be treated like the item itself I think. But yeah, I think it would be better to only toggle the checkbox when itself is clicked on.

**Comment by jitspoe** [comment]
Yeah, I said "Click to the left of the dropdown arrow".  In the title I mean that clicking anywhere to the left of the checkbox should NOT check the checkbox.  What makes this especially frustrating is the export menu has everything expanded by default, so when you go to collapse a bunch of directories, it's VERY easy to miss the dropdown arrow and check everything.  Wasn't really sure if this should have been a suggestion or bug report, but it feels like a user experience bug.

**Comment by kleonc** [comment]
It was done like that in #6553 (see their reasoning in there).

Note that currently `Tree` has `force_edit_checkbox_only_on_checkbox` flag which is not exposed to scripting:
https://github.com/godotengine/godot/blob/85380c52073d679c088d61fc663ec62cbd85b453/scene/gui/tree.cpp#L4730-L4736
However, it doesn't really make what its name says as `force_edit_checkbox_only_on_checkbox == true` only disallows toggling the checkbox by clicking to the right from it (you can still toggle by clicking to the left/above/below):
https://github.com/godotengine/godot/blob/85380c52073d679c088d61fc663ec62cbd85b453/scene/gui/tree.cpp#L2507-L2518

It's used for example by `EditorFeatureProfileManager`:
https://github.com/godotengine/godot/blob/bdf8340e5993ec3f86e4bf1d5ede48df7d023a12/editor/editor_feature_profile.cpp#L922

So in there you can't toggle checkbox by clicking to the right of the checkbox but you can still toggle it by clicking to the left (however currently an invisible collapse/folding arrow can consume mouse event, this should be fixed by #55791):
![E9kH1Tq9WE](https://user-images.githubusercontent.com/9283098/145611165-b91ed3f7-8820-4cf0-9268-f086f378293c.gif)

So some things to discuss/consider:
- Should the behavior for in tree checkboxes be customizable?
- If so, how should it be customizable?
- Should it be exposed to scripting?
- What should be the dafault behavior?
- What should be the behavior for some in editor trees (like the ones in _Export_ or _Manage Editor Features_ dialogs)?

**Comment by jitspoe** [comment]
Don't know that it needs to be customizable, but I feel like having the current behavior where something visibly to the right of the dropdown can be triggered by clicking to the left of the dropdown feels broken.

Bad:
[check][dropdown][check]

OK:
[nothing][dropdown][check]
[dropdown][dropdown][check]

So if either the dropdown consumes the click of everything to the left of the checkbox OR the checkbox click area only includes the checkbox and the area to the right of it when in a tree, I feel that would adequately solve this issue.

If anybody is wondering, this was my frustrated reaction when it happened: https://clips.twitch.tv/AnimatedEndearingCarrotShadyLulu-JjxECm96YRNYVZOw 😅
I just needed to add 1 level.
