### ISSUE TITLE
Directory list_dir file order is alphabetical on Windows but something else in Mac OS

### ISSUE THREAD

**Issue by Razoric480** [godotengine/godot#55776]
### Godot version

3.4.stable

### System information

Windows 11, Mac OS

### Issue description

I'd written a plugin that created an animation based on a list of files in a directory. On Windows it worked fine, but on Mac it was janky with the frames out of order.

It's fixable by putting the files in an array and sorting before using them, but this behavior - that order may not be maintained depending on platform - is not documented anywhere.

The expectation is that listing a directory's files would match the way it's laid out in the godot filesystem, not however Finder feels like it.

### Steps to reproduce

Have a directory with some amount of files where the order should be obvious, I.E. 0001.png, 0002.png, 0003.png, etc.

```gdscript
func _ready() -> void:
	var directory := Directory.new()
	directory.open(the_path_to_textures)
	directory.list_dir_begin(true)
	var next := dir.get_next()
	while not next.empty():
		if not dir.current_is_dir():
			print(next)
        	next = dir.get_next()
```

On windows, it should be in alphabetical order. On Mac, it may be date modified? Or some other.

**Comment by SommerEngineering** [comment]
It is quite common that the order of such results is not defined. For example, in .NET Microsoft notes that the order is not guaranteed (see https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo.getfiles?view=net-6.0). The fact that the result is undefined in this way should of course be written in the manual 🙂 

Another example is the Go language. There an order is guaranteed for the function fs.WalkDir (see https://pkg.go.dev/io/fs#WalkDir) and at the same time the disadvantages are pointed out: a directory must always be completely loaded into memory beforehand. This is obvious, because the result can only be sorted in this way.

In my opinion, the current behavior of Godot is ideal. It should just be documented. Who needs a certain order, should sort the result himself. So the solution is universally applicable. Because not all users need the automatic sorting and these users would be punished then with a worse performance (in case of very large directories).

**Comment by Razoric480** [comment]
Yeah, documenting it is fine.

**Comment by akien-mga** [comment]
Note that the new methods added in https://github.com/godotengine/godot/pull/40547 might provide sorted listings, I didn't check (of they don't, they should be fixed to sort).
