### ISSUE TITLE
Vulkan: When combining blend shapes into a larger positive combined value, shading issues occur (blend shape normalization / normals issue?)

### ISSUE THREAD

**Issue by ModularNucleus** [godotengine/godot#55812]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10, Nvidia GTX1060 6GB, Studio driver 472.47, Vulkan clustered

### Issue description

I tried to do a search, but couldn't come up with any issues that seemed to describe the exact same phenomenon. Perhaps it is related to what is described in lyuma's comment here: [https://github.com/godotengine/godot/issues/49249#issuecomment-853330681](url)? But I am not knowledgeable enough to understand / determine that.

In Godot 4.0 pre-alpha:
- When only one blend shape is set to positive 1 at a time, the mesh renders normally.
- When multiple blend shapes are set to 1 simultaneously, shading issues occur.
- The shading issues seem to gradually appear, as the combined values of the active shape keys increase.
- The effect seems to be counteracted by setting some of the shape keys to negative values ("subtracting from the combined value")

Setting all the blend shapes to negative values instead does not seem to result in shading errors.

In Godot 3.4 this does not happen.

Godot 4.0: only one blend shape at positive 1:
![Blendshapes and normals in Godot 4 - 1 blendshape](https://user-images.githubusercontent.com/91982860/145672169-df1fd15a-b988-439b-96e0-01ff438cead6.png)

Godot 4.0: two blend shapes at positive 1:
![Blendshapes and normals in Godot 4 - 2 blendshapes](https://user-images.githubusercontent.com/91982860/145672180-8f8cfbcd-fec8-4553-b993-0e3821e91075.png)

Godot 4.0: three blend shapes at positive 1:
![Blendshapes and normals in Godot 4 - 3 blendshapes](https://user-images.githubusercontent.com/91982860/145672188-7224f4aa-6ad3-4b66-ab64-9ee0d0f120bb.png)

Godot 4.0: two blend shapes at positive 1, one blend shape at negative 1:
![Blendshapes and normals in Godot 4 - 2 blend shapes positive - 1 blend shape negative](https://user-images.githubusercontent.com/91982860/145673051-b4aea713-0437-4428-acc0-0442eaf6ddf3.png)

Godot 3.4: three blend shapes at positive 1:
![Blendshapes and normals in Godot 3 - 3 blendshapes](https://user-images.githubusercontent.com/91982860/145672313-a9a63e43-3758-45b2-acd9-eb082c07bf29.png)

### Steps to reproduce

- Open the included MRP.
- Select the Cube MeshInstance.
- Set only one blend shape to positive 1: observe that the cube is rendered normally.
- Set two, then three, blend shapes to positive 1: observe that the shading changes each time, resulting in a mesh that looks like it has normals errors.
- Set one of the blend shapes to negative 1: observe that the shading returns to normal.

### Minimal reproduction project

[Pre-alpha 4 - multiple blend shapes shading issue.zip](https://github.com/godotengine/godot/files/7696795/Pre-alpha.4.-.multiple.blend.shapes.shading.issue.zip)

**Comment by raiseledwards810** [comment]
I can confirm this, I'm using the nightly builds and the same kind of artifacts appear when 2 blend shapes are used at the same time. Here you can see my example:

![Untitled](https://user-images.githubusercontent.com/42452866/145689651-9a55c01b-3e50-4a94-a186-b85c69cc675d.png)
![Untitled2](https://user-images.githubusercontent.com/42452866/145689655-61eafe9e-a03a-45a3-aa64-38581102906b.png)
![Untitled3](https://user-images.githubusercontent.com/42452866/145689658-99b3cb43-764d-4b9b-b2f5-43ac6a500e4b.png)

**Comment by fire** [comment]
@lyuma didn't you use a 0.9999 blend value workaround?

**Comment by raptorEE** [comment]
It's a major issue since it literally makes blendshapes unusable. It still is a problem in the latest alpha however it changed a bit. Now the artifacts appear when the total value is 2. Sadly, from the looks of it this issue is untapped and not in anyone's radar.

**Comment by lyuma** [comment]
I agree. It's currently broken. glTF imports currently in "Normalized" blend shape mode, which I assume means it stores full vertex positions for each shape, rather than offsets. I don't understand how "Normalized" blend shapes are supposed to work, since they require canceling out the original value.

With "Relative", it should be possible to adjust the normal by the delta in the blend shape, which is generally a very small number. It seems to me that relative would also compress better.

Blend shapes were originally changed from Relative to Normalized mode in this PR by @WindyDarian : https://github.com/godotengine/godot/pull/24647
The reason given was that bone weights were being doubled. However, this is no longer a problem because vertex buffers were split, and blend shapes should now only operate on Vertex, Normal and Tangent. I think the original reason for this change is no longer relevant.

Anyone else know why Normalized form is desirable?

![picture showing bad normals.](https://user-images.githubusercontent.com/39946030/166867401-89c47c70-3afd-4cb8-a6d5-94e34bb61bd1.png)
At sum of blend shapes == 2.0, it seems to flip normals (causing artifacts), and above 2.0, normals are inverted.

**Comment by WindyDarian** [comment]
Trying to remember this. Right, changing from relative mode to normalized mode will change behavior when there are multiple blend shapes.

According to [skeleton.glsl](https://github.com/godotengine/godot/blob/master/servers/rendering/renderer_rd/shaders/skeleton.glsl). Normalized mode tries to get weighted average, however, it assumes the weight is normalized in the shader.
```
		if (params.normalized_blend_shapes) {
			vertex = (1.0 - blend_total) * vertex;
			normal = (1.0 - blend_total) * normal;
			tangent.rgb = (1.0 - blend_total) * tangent.rgb;
		}

```

But the weights need to be normalizes somewhere so the sum is 1, so this is probably why it looks broken instead of "average" like expected for normalized mode. I am guessing there may be missing a normalization before uploading to renderer buffer (probably wants to be before uploading to renderer buffer in `MeshStorage::update_mesh_instances()`), and that would result in total weights exceed 1.0 and cause issue.

So probably want to either figure out if it is the case that is breaking normalized blend and fix it, or change back into relative mode. (or better, make it an import option? still need to fix normalized mode though.) I don't think there were other reasons besides working around https://github.com/godotengine/godot/issues/20377 for using normalized mode, unless there are some other things now depend on its behavior.

**Comment by WindyDarian** [comment]
Oops sorry for the commit spam above. Got a pull request here that changes it back to `BLEND_SHAPE_MODE_RELATIVE`, and the test case here is fixed for me locally. https://github.com/godotengine/godot/pull/60814

**Comment by WindyDarian** [comment]
#61217 is actually the fix now that i understand the math for real...

So BLEND_SHAPE_MODE_NORMALIZED and BLEND_SHAPE_MODE_RELATIVE actually do the same thing when math is fixed, just differ in how blend shape is stored is different
