### ISSUE TITLE
Adapt mouse pad navigation for Mac OSX

### ISSUE THREAD

**Issue by OrenjiAkira** [godotengine/godot#5585]
Mac OSX El Capitán
Godot v2.0.3.stable.oficial

Mouse pad navigation in mac osx works with pinch for zooming in or out, and double finger for panning/scrolling. However, Godot does not use this convention, instead using double finger for zooming. That makes the zoom very sensitive, and quite clunkier to use when compared to other systems. This also means that panning doesn't work using just the pad, and you have to use spacebar+click to pan, which is harder. It would be nice if the convention was used, for the sake of user-friendliness.

**Comment by Keyaku** [comment]
I too am looking forward to this, but since Mac OS X seems to be in the minority, we'll have to implement this ourselves.

I could dedicate a few days to re-read Apple Documents on their Touchpad gestures, but I'm too busy with my own Godot project that it might be a while before I can tackle it (either that, or a lot of accumulated frustration for the lack of gestures :P)

**Comment by toger5** [comment]
This is a general problem with the pan gesture on any notebook that supports multi touch gestures (like two finger pan).
It would be extremely helpful cool if someone can look into that.

**Comment by qubodup** [comment]
Wanted to use Godot on a MacBook at a game jam today and realized that it seems to be impossible to rotate the view without a mouse. Video demo comparing the behavior to Blender: https://youtu.be/9hMMR-Uszko

**Comment by akien-mga** [comment]
It's possible if you toggle `3d_editor/emulate_3_button_mouse` or something like that.

**Comment by Keyaku** [comment]
I think Godot 3.0 addressed these issues. This could be closed as far as I'm concerned.
