### ISSUE TITLE
Skew CanvasGroup causes rendering issues

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#55853]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Win 64, dedicated Nvidea 765M

### Issue description

Adjusting the new skew property on a CanvasGroup results in Clipping and Masks breaking as well as other rendering issues:

https://user-images.githubusercontent.com/47016402/145706835-4842fa3d-e96b-409d-a01f-796a591d7626.mp4

This video also shows how a Masked Sprite is revealed this way, but rendering issues will also appear without any Sprites that have the "Clip Children" property enabled.

Possibly related to
https://github.com/godotengine/godot/issues/54211
https://github.com/godotengine/godot/issues/54213
https://github.com/godotengine/godot/issues/49198 

### Steps to reproduce

1. Add CanvasGroup Node
2. Add a few Sprites as children to the CanvasGroup
3. Skew the CanvasGroup until rendering issues appear

### Minimal reproduction project

[Clipping_Masking_Skew_test.zip](https://github.com/godotengine/godot/files/7698424/Clipping_Masking_Skew_test.zip)

**Comment by insomniacUNDERSCORElemon** [comment]
Note this effect happens with rotation as well, it's caused by https://github.com/godotengine/godot/issues/43543 (note my comment, and that the issue should be re-named). It also still happens with my 1-line improper fix (the one mentioned in the comments of 49198).

An additional oddity, unsure if still present (I'm testing with an older build): if the canvasgroup is partially transparent, a screen-based FXAA shader will remove the problem framebuffer ghosting that occurs in the area caused by 43543.

**Comment by golddotasksquestions** [comment]
Still present in alpha 1, 2, 3:
https://user-images.githubusercontent.com/47016402/155633024-64b84f34-8be0-4d6f-866f-9afdc57b1572.mp4

**Comment by golddotasksquestions** [comment]
I can't replicate this issue anymore in Alpha7, seems to be fixed. Quite possibly by https://github.com/godotengine/godot/pull/59989

Thanks @NNesh
