### ISSUE TITLE
When RayCast2D placed next to a Body(StaticBody2D) it activates.

### ISSUE THREAD

**Issue by NerChick** [godotengine/godot#55873]
### Godot version

3.3 stable

### System information

Windows 10, GLES3

### Issue description

Using Grid Snapping with RayCast2D and placed next to a Body(StaticBody2D) it activates. It shouldnt happen as raycast is not placed in the collisionShape2D.

### Steps to reproduce

Create a StaticBody2D and place RayCast2D next to it using Grid Snap. Then if placed directly in the StaticBody2D node disable exclude parent. Then write a script that displays a message when RayCast is colliding.

### Minimal reproduction project

[Raycast2D_bug.zip](https://github.com/godotengine/godot/files/7699588/Raycast2D_bug.zip)

**Comment by Calinou** [comment]
> 3.3 stable

Can you reproduce this on 3.4? 3.3 is no longer supported (except for security fixes).

**Comment by NerChick** [comment]
oh, i wrote the wrong version. Yes, it works in the latest version

**Comment by NerChick** [comment]
very annoying tho , you have to disable grid snap and pixel snap and move it a little bit to fix it.

**Comment by Calinou** [comment]
> oh, i wrote the wrong version. Yes, it works in the latest version

Closing as resolved then.

> very annoying tho, you have to disable grid snap and pixel snap and move it a little bit to fix it.

This is expected, as the RayCast must be located fully outside the StaticBody2D to avoid a collision. If you do not wish this to happen, configure the StaticBody2D's collision layers then configure the Raycast2D's cull mask accordingly, or add a collision exception to prevent the StaticBody2D from being registered as a collider for the RayCast2D.

PS: Please use the **Edit** button (hidden behind the **…** icon in the top-right corner of your comments) instead of multi-posting.
