### ISSUE TITLE
GDScript 2.0: const does not handle typing in the same way that var does for Array[...]

### ISSUE THREAD

**Issue by gustavi** [godotengine/godot#55916]
### Godot version

v4.0.dev.20211210.official [21b81998b]

### System information

Windows 10 64bit - Vulkan API 1.2.141 - GeForce GTX 1660 SUPER

### Issue description

Godot does not handle typing for `var` and `const` in the same way. Specially when you try to type a `const` with Array[<something>]` it looks not really typed with this type.

Tested with Godot 4 only.

*It may be duplicated since there is a lot of bugs related to GDScript 2.0 and typing (I did not find this one).*

### Steps to reproduce

Following code can reproduce:

```gdscript
extends Control


var foo: Array[Vector2i] = []
const FOO: Array[Vector2i] = []


func f(a: Array[Vector2i]) -> void:
    pass


func _ready():
    f(foo)
    f(FOO)  # <- bug here

```

![image](https://user-images.githubusercontent.com/2736557/145887505-4b9c8806-a442-423b-a976-661453dd4dfd.png)

### Minimal reproduction project

[bug-const-array-vector2i.zip](https://github.com/godotengine/godot/files/7706959/bug-const-array-vector2i.zip)

**Comment by gustavi** [comment]
Note: the error message "Cannot convert argument N from Array to Array" should be improved to include Array inner type. I did not find related issue, should I open one?

**Comment by Calinou** [comment]
> Note: the error message "Cannot convert argument N from Array to Array" should be improved to include Array inner type. I did not find related issue, should I open one?

Yes, please open a separate issue for this :slightly_smiling_face:

**Comment by cdemirer** [comment]
Note that this behavior is not only for `Array`s:

```gd
const x: int = 3.14 # This will compile fine, and it will be a float
```

**Comment by cdemirer** [comment]
Currently the type of a const is solely defined by the inferred type of the initializer expression. So `const FOO: Array[Vector2i] = []` should be a parser error according to current implementation. The reason it doesn't error is probably because of a missing a check regarding constant member declarations (you can try the same line inside a function body to see the error).

The actual type of the const value here is the inferred type of `[]`, which is plain `Array`, leading to the error in the original comment. Whether there should be type conversion during const initialization (and to allow declarations like this) is probably something to discuss. In my opinion, it would be nice to have initializer expression values converted to the explicitly annotated type (if there is one), so that it would be similar to how `var` works. But apparently that is not the current design.
