### ISSUE TITLE
Control nodes need multi-touch support

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#55934]
### Godot version

965a527

### System information

W10

### Issue description

Recently it was discussed that Control nodes need to get proper multitouch support and the TouchScreenButton could then be removed (#https://github.com/godotengine/godot/pull/54430#issuecomment-987901083). Just opening an issue so that it's not forgotten.

### Steps to reproduce

1. Add TouchScreenButton
2. Try to replace it with a Button
3. It's just not the same

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated **[Godot Improvement Proposals (GIP)](https://github.com/godotengine/godot-proposals)** ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please **[open a new proposal on the GIP tracker](https://github.com/godotengine/godot-proposals/issues/new/choose)** following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by KoBeWi** [comment]
The issue was just a reminder of what we decided. I don't have any specific details to open a proposal. But whatever xd

**Comment by Calinou** [comment]
I opened a proposal for this: https://github.com/godotengine/godot-proposals/issues/3976
