### ISSUE TITLE
ViewportContainer Not Resizing Viewport

### ISSUE THREAD

**Issue by Jonyleo** [godotengine/godot#55955]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Ubuntu 20.04, GLES3

### Issue description

ViewportContainer doesn't behave like it is stated in the [documentation](https://docs.godotengine.org/en/stable/classes/class_viewportcontainer.html#class-viewportcontainer)

"A Container node that holds a Viewport, automatically setting its size."

Also for [Viewport](https://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport)

"If a viewport is a child of a ViewportContainer, it will automatically take up its size, otherwise it must be set manually."

This causes this official [tutorial](https://docs.godotengine.org/en/stable/tutorials/viewports/custom_postprocessing.html) to not work as expected

I would like to preemptively respond in case someone says this issue is a duplicate of #19252, in my case, the Viewport isn't being resized at all, unlike that issue where it's not resizing to a smaller size than the initial

### Steps to reproduce

Just open and run the scene, would expect to see a cube face, see nothing (grey background) instead

If I manually resize the Viewport, for example (100,100), I can see, but it never gets resized to the ViewportContainer's size like the documentation says

### Minimal reproduction project

Here is a sample project - [test.zip](https://github.com/godotengine/godot/files/7719784/test.zip)

**Comment by Jonyleo** [comment]
So, apparently, you have to set the stretch flag to true, I feel dumb, either way I feel like the sentences I highlighted in the docs and the tutorial could use a change to reflect this flag.

Should I make a suggestion or can this issue be converted to a suggestion in any way?

**Comment by Roucou** [comment]
This confused me as well. Based on reading the documentation, one would assume that the Viewport, when added as a child of a ViewportContainer, would automatically match the size of the ViewportContainer. This is also stated here:

[https://docs.godotengine.org/en/stable/tutorials/viewports/viewports.html](https://docs.godotengine.org/en/stable/tutorials/viewports/viewports.html)

> Viewports have a "size" property, which represents the size of the Viewport in pixels. **For Viewports which are children of ViewportContainers, these values are overridden**, but for all others, this sets their resolution.

Jonyleo mentions the `stretch` flag, but settings this to `true` caused a heap of side effects for me (for example, CollisionObjects signals are no longer triggered due to, I guess, weird mouse position scaling voodoo).

Instead of using the `stretch` flag, I made the `Viewport` behave as per the documentation. Add a script to the `Viewport`, and connect it up with the `resized` signal from the `ViewportContainer`. Here's my code:

```
extends Viewport

func _ready():
	resize_to_parent()

func _on_parent_resized():
	resize_to_parent()

func resize_to_parent():
	var p = self.get_parent()
	self.size = p.get_size()
```

**Comment by Calinou** [comment]
> Jonyleo mentions the stretch flag, but settings this to true caused a heap of side effects for me (for example, CollisionObjects signals are no longer triggered due to, I guess, weird mouse position scaling voodoo).

See https://github.com/godotengine/godot/issues/34805.

**Comment by Roucou** [comment]
> See #34805.

Thanks, Calinou! I did see [#34805](https://github.com/godotengine/godot/issues/34805). But not sure what I'm supposed to find there? Is it just to confirm this is a known issue? Or to point me to a potential workaround? In case of the latter, note that I do not directly interact with the mouse position myself. Instead, I use a `CollisionObject` (an `Area` actually) to detect if a 3D object is clicked, i.e. I catch the `input_event` signal thrown by the `CollisionObject`. Which doesn't get thrown if the `stretch` property is set to `true`, due to the mouse position being messed up (I guess).

**Comment by Calinou** [comment]
> Is it just to confirm this is a known issue?

Yes, it's a known issue.
