### ISSUE TITLE
Game Output/Log goes to new terminal window on start and closes on game end

### ISSUE THREAD

**Issue by eazrael** [godotengine/godot#55971]
### Godot version

3.4.1-rc3 Windows Mono 

### System information

Win10 64bit, Radeon Vega 64, GLES3

### Issue description

Just upgraded from 3.4.1-rc2 to 3.4.1-rc3. Now each time the developed application  is started a new terminal window is open, output from the application  goes there and when the application  is closed the new terminal window gets closed immediately taking any output with it.
This is reproducible with the Control Gallery demo app and switching back to 3.4.1-rc2 restores the old behaviour of having the Godot log terminal also showing the application output. 

Not sure if that is the intended behaviour or a new regression, but the new log unfortunately takes the any final crash exception stack output with it, in case of crashes, which are not mirrored in the editors internal log window. 

### Steps to reproduce

Start Godor 3.4.1-rc3 with Control Gallery App. Start App and close it. Retry with 3.4.1-rc2. 

### Minimal reproduction project

Control Gallery

**Comment by eazrael** [comment]
Probably caused by PR #55925

**Comment by Calinou** [comment]
This may be fixed by https://github.com/godotengine/godot/pull/55967.

**Comment by akien-mga** [comment]
This will be expected behavior for users of Windows 11 using the new Windows Terminal, at least until Windows Terminal developers reconsider this design choice.

For Windows 10 users, or users who manually configure things to use the old Windows Console Host or other third-party terminals, #55967 will restore the original behavior of Godot before 3.4.1 RC 3.
