### ISSUE TITLE
After compiling with float=64, vector3 still cannot use double type parameters

### ISSUE THREAD

**Issue by Alunwalker** [godotengine/godot#55972]
### Godot version

4.0 mono

### System information

windows10, Vulkan

### Issue description
I need to use double-precision vector3 in c#, but when I compile with float=64, this still doesn’t work. Is there a problem with my compiling command or is it not currently supported?
![image](https://user-images.githubusercontent.com/57265274/146292124-a2cfbd9e-7a7c-4f97-a275-0544517b8838.png)

### Steps to reproduce
scons p=windows tools=yes module_mono_enabled=yes mono_glue=no float=64
bin\godot.windows.double.tools.64.mono --generate-mono-glue modules/mono/glue
scons p=windows target=release_debug tools=yes module_mono_enabled=yes float=64

**Comment by Zylann** [comment]
It's really strange because the errors shown on your screenshot don't appear to be related to double vs floats at all. I checked `Vector3.cs` and it uses `real_t`, which is itself defined with this on top of every `.cs` math file:
```cs
#if REAL_T_IS_DOUBLE
using real_t = System.Double;
#else
using real_t = System.Single;
#endif
```
Mono is still work in progress at the moment so may need to be re-checked later.

**Comment by aaronfranke** [comment]
This doesn't seem related to using doubles in Vector3 specifically, it looks like something is causing the Mono build to fail. Considering that C# support is not currently expected to work in master even with `float=32`, I don't think that this is an issue we can solve in the near future.

**Comment by raulsntos** [comment]
As explained by the previous comments, this doesn't look like an issue with using doubles in Vector3.

If you (or anyone else) is still reproduce this issue, please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, since pre-built binaries with double support are not officially distributed, you must be using a custom build. Please indicate the commit hash.

**Comment by akien-mga** [comment]
It's a pretty old issue so I think we can close it for now. If it's still reproducible, it should likely be reopened with clearer information on what is being tested on which Godot version exactly.
