### ISSUE TITLE
TextureAtlas fail - Error: Image height must be greater than 0.

### ISSUE THREAD

**Issue by SuzukaDev** [godotengine/godot#55998]
### Godot version

v3.4.stable.official [206ba70f4]

### System information

Windows 7 64bits GLES3

### Issue description

When importing some textures as TextureAtlas, it fails.
Gives all those errors in console (since the Image height one is the first, I thought it was appropiate to put it in the issue's title) :

```
ERROR: Image height must be greater than 0.
at: (core/image.cpp:1743)

ERROR: Condition "data.size() == 0" is true.
at: (core/image.cpp:2543)

WARNING: png_image_write_to_memory: invalid argument
at: check_error (drivers/png/png_driver_common.cpp:56)

ERROR: Condition "compressed_size <= png_size_estimate" is true. Returned: FAILED
at: image_to_png (drivers/png/png_driver_common.cpp:186)

ERROR: Can't convert image to PNG.
at: (drivers/png/resource_saver_png.cpp:54)

ERROR: Invalid image.
at: (scene/resources/texture.cpp:190)

ERROR: Can't find file 'res://atlas/atlasFAIL.png'.
at: (editor/editor_file_system.cpp:1668)
```

Minimal reproduction project included.

**Note:** I already thought at first that it could be something that went wrong when saving those images, but I already tried to export them in different softwares (aseprite, krita, photoshop) to be sure, in case there was any hidden problem in the file or something. But even with those exported files from different programs, I get the exactly same result. The image seems to be perfect. 
In fact, I was able to replicate it by making more images that have the same sizes (both for the image size, and the inner rect (that contains just the alpha of the image).

After the confirmation on reddit by some users, I thought that it was worthy to open an issue.

Here is a guideline for recreating more images that fails:
![isykWVh](https://user-images.githubusercontent.com/52723367/146423153-4c0399bc-42a2-41ad-bd33-179631c6687e.png)

Extending the inner box just one pixel (image at the bottom), makes it work properly. But the top image fails.

### Steps to reproduce

1. Open the project
2. Open the folder "`images_fail`" or "`images_stack`"
3. Re-import all the images of any of those folders as a `TextureAtlas`
4. See how it fails*

*NOTE:
"`images_fail`" folder contains only just the images with the specific dimensions that seems to be causing the problem.
"`images_stack`" generates an AtlasTexture, but isn't working properly (images are stacked). Image:

![Image](https://preview.redd.it/q0tl4xmhbw581.png?width=64&format=png&auto=webp&s=c337780a25f8629ecbf09ef7767cbd1d2da14ab7)

### Minimal reproduction project

[AtlasIssue.zip](https://github.com/godotengine/godot/files/7729394/AtlasIssue.zip)

**Comment by SuzukaDev** [comment]
I've been testing with different sizes that also fails (cropping the image, changing the inner rect of the sprite, etc).
So, in case it helps to identify the bug or to test it, I upload it here:
[doomed_cursed_slide_image_of_the_demon.zip](https://github.com/godotengine/godot/files/7737160/doomed_cursed_slide_image_of_the_demon.zip)

Its separated in 2 main folders, one containing a set that works, and the other has some different sets with diferent sizes that triggers the bug.

**Comment by kleonc** [comment]
The issue is in [this method](https://github.com/godotengine/godot/blob/b0e93711b36bae3d2bb3a7e9a4a88faf055499fb/editor/editor_atlas_packer.cpp#L84-L287):
https://github.com/godotengine/godot/blob/b0e93711b36bae3d2bb3a7e9a4a88faf055499fb/editor/editor_atlas_packer.h#L72
It's being called [in here](https://github.com/godotengine/godot/blob/b0e93711b36bae3d2bb3a7e9a4a88faf055499fb/editor/import/resource_importer_texture_atlas.cpp#L273). It seems it's not always working properly for`p_cell_resolution > 1`.  For `p_cell_resolution = 1` all test cases above seems to work fine. The `p_cell_resolution` parameter is used to perform packing on a `p_cell_resolution` times smaller bitmaps (making the whole packing process quicker). But it seems like some logic is incorrect for some cases when dealing with shrinked bitmaps (`p_cell_resolution > 1`). Haven't pinpoint the exact issue(s) with the current logic yet.
