### ISSUE TITLE
Imported fonts blurry and cut off

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#56019]
### Godot version

4.0.dev (58712e9)

### System information

Windows 10, Vulkan

### Issue description

Fonts added show correctly in the Font Data preview tab, and when running the project, but are rendered incorrectly in the editor.
Anti-aliasing is off.

![image](https://user-images.githubusercontent.com/21325943/146555760-fd466beb-23b9-406d-b49c-a25ba1facde6.png)

### Steps to reproduce

1. Create a new project.
2. Create a new Label node.
3. Create a new Font Resource in the Theme Overrides tab.
4. Add a font to the Font Data tab.
5. Make sure it's imported with anti-aliasing off.
6. Type some letters.

**Comment by Calinou** [comment]
This is likely a duplicate of https://github.com/godotengine/godot/issues/33968. If you use the `canvas_items` or `viewport` stretch mode, the issue will go away in the running project. However, this can't be fixed in the editor as fonts can't be re-rasterized every time you zoom in and out (it would be too slow).

PS: Disabling anti-aliasing will *not* disable filtering when rendering the font (it's an entirely separate thing). To fix this issue in the editor, the font should be rendered with filtering disabled, but I'm not sure if there is a way to do this in `master`.

**Comment by markdibarry** [comment]
I've reloaded the current project twice. Once with "Snap 2d Transforms To Pixel" selected, and once with "Snap 2d Vertices To Pixel". Both times with stretch mode viewport, and keep aspect.
Note that (unlike the linked issues) while the edges of the characters have hard cutoffs, the insides of each character isn't constrained to a pixel block, but rather blurs between them.
![image](https://user-images.githubusercontent.com/21325943/146585785-7d830dca-0f74-419c-a53a-6ab0af423b6d.png)

**Comment by KoBeWi** [comment]
Is this still valid in newest master/alpha 6? If yes, provide an example font with this problem.

**Comment by markdibarry** [comment]
Old issue. I haven't had this issue in awhile, so closing.
