### ISSUE TITLE
Running a static code analyser on Godot's codebase

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#5604]
Have any of you tried to run a static code analyser on Godot's codebase? GCC offers extra analysis via the `-Wextra` and `-Weffc++` flags, Clang comes with its own static analyzer `clang-check` and there are a few standalone programs that perform static analysis (like `cppcheck`).

I tried to use `clang-check` but it requires a compilation database, which can be generated automatically from CMake but not from scons.

It should be a good way to find memory leaks and poor loops automatically, if anything.

**Comment by akien-mga** [comment]
@tomreyn set up Coverity scans for Godot at some time: https://scan.coverity.com/projects/godot-engine
It has some interesting results, but sadly they're not public, and the handful of devs with access to it don't necessarily have the time/motivation to go through.

If those results could be made public, it would be nice. Godot is not mission critical software so I don't see any issue with having defects exposed to the public, if that can help getting them fixed.

**Comment by tomreyn** [comment]
https://scan.coverity.com/policy lists some restrictions which may rule out publishing the results (e.g. "You will not publish any findings regarding or resulting from use of the Service or the Software"). Setting up a shared user account may or may not be an option, IANAL. I suggest to talk to them (send mail to: scan _hyphon_ admin _at_ coverity _dot_ com) and find a solution which both you and they will be happy with. This is usually much more useful than trying to parse legalese. 

See also https://scan.coverity.com/faq#who-can-have-access on their perspective on how the results should be handled and why.

**Comment by Marqin** [comment]
Current state. This ignores `/drivers` directory (apart from gles2 driver).

![zrzut ekranu 2016-09-03 o 17 58 45](https://cloud.githubusercontent.com/assets/959429/18225964/49be435a-7200-11e6-9e5a-791b48bb89e5.png)

**Comment by paper-pauper** [comment]
Although your kindness is appreciated, you should delete the image, since it seems like sharing the results is against their ToS.

**Comment by Marqin** [comment]
No. It's not `findings` but screen of public data (that you can see [here](https://scan.coverity.com/projects/marqin-godot)).

> You will not publish any findings regarding or resulting from use of the Service or the Software

It says `findings`.

**Comment by Marqin** [comment]
> Clang comes with its own static analyzer clang-check

@paper-pauper I think you meant [`scan-build`](http://clang-analyzer.llvm.org/) called ClangAnalyzer command. It doesn't need any DB and I'd ran it few times against Godot, but it hasn't found much critical bugs (btw. Godot compile logs are flooded with warnings so it's hard to find those interesting onces).

**Comment by paper-pauper** [comment]
@Marqin Whoops, sorry! I just get over-cautious when I see ToSs, that's why I prefer free software.

Well, I suppose that since you have access to it, only you could potentially fix those "defects", which Coverity doesn't want the rest of us to know about. I hope they aren't serious, but I guess some of them could be discovered via Valgrind.

**Comment by Marqin** [comment]
> you have access to it

@bojidar-bg also has access to my fork results, and @reduz or @punto- have access to @tomreyn's

> I hope they aren't serious

As I said, I'm not proficent with Godot internals so I cannot say which of it's problems with `Reference` is false-positive and which is real problem.

**Comment by tomreyn** [comment]
@Marqin Just FYI, here's the components which I think reduz (?) configured on 'my' project:

Component name | Pattern | Ignore in analysis
-------------- | ------- | ------------------
Core | `/(core\|main)/.*` | No
Platform specific code | `/platform/.*` | No
Scene code | `/scene/.*` | No
Servers | `/servers/.*` | No
Third party drivers | `/drivers/(?!gles2)(.*)` | Yes
GLES driver | `/drivers/gles2/.*` | No
Modules - GDScript | `/modules/gdscript/.*` | No
Modules - GridMap | `/modules/gridmap/.*` | No
Modules - other | `/modules/(?!gridmap\|gdscript)(.*)` | No
Unit tests | `/bin/tests/.*` | No
Tools - Collada | `/tools/collada/.*` | No
Tools - Editor | `/tools/editor/.*` | No
Tools - other | `/tools/(?!collada\|editor)(.*)` | No

**Comment by hubbyist** [comment]
As all "Ignore in analysis" checks are "No", Nothing is "Ignored in analysis" as it seems. In combination with defect density of 0.09 this seems a good result to me.

**Comment by vnen** [comment]
Actually, the "Third party drivers" component is ignored. It is also ignoring some of Godot code though, since some files there contain engine code (at least `alsa`, `pulseaudio`, `unix` and `windows` folders have only Godot code, and many of the others have a bit of engine code too).

**Comment by tomreyn** [comment]
If you ignore the "Third party drivers" component you end up with a defect density of 0.62 (at least that's how it was when the latest check was run with these settings in April):
https://scan.coverity.com/projects/godot-engine

Categorization of code into components serves three purposes: 
- ignore parts of the code (such as third party code)
- allow for filtering on the 'defect browser'
- gain a better understanding of the more problematic parts of the code

**Comment by Calinou** [comment]
Is there any progress on this issue lately? If there are no developers interested in fixing some of the issues found by a Coverity scan, this issue should be closed for now.

**Comment by akien-mga** [comment]
I'm interested in having Coverity scans and having contributors work on fix issues, but the current setup we have is based on @tomreyn's fork (and uses outdated patterns). I'm also unhappy with Coverity's "private by default" system, so only approved contributors can access the stats (so basically noone, and thus nothing gets fixed).

I'm now looking into setting up Coverity scans for godotengine/godot, and if possible public for everyone (if not, I'll add all GitHub org members and then some so that they have access).

I'll open new issues to keep track of build results and work done to address them though, so closing this one.

**Comment by tomreyn** [comment]
While this doesn't make results universally available, it can ensure you always have current results:
https://scan.coverity.com/travis_ci
https://docs.travis-ci.com/user/coverity-scan/
https://blogs.s-osg.org/using-travis-ci-submit-coverity-scan-service/
https://github.com/bjorn/tiled/commit/c0fac49b6f9e96716a5554cb7d9a990bddbe7c29

Making results publicly available should prove difficult. I tried to download a full result set but it's not easy since it's just different sets of (not well defined) JSON data wrapped around a somewhat convoluted web UI.

**Comment by akien-mga** [comment]
Thanks for the input - I've also used your components as a reference to set the new ones, so thanks for that (thinking back I could maybe have just tweaked the `tomreyn/godot` project to make it more "official" instead of creating a new one, but well.. it's done).

Here's the new "official" Coverity Scan: https://scan.coverity.com/projects/godotengine-godot/

I plan to add Travis integration indeed, it's more convenient than uploading local builds (especially when they're still 250 MB xz-compressed).

I set the "Project summary and defects are viewable in read-only mode by all users" option, but it still doesn't seem to allow viewing defects without being invited first (at least in private mode/not logged in, I can't access defects). I guess I'll just invite all core contributors.

**Comment by tomreyn** [comment]
Indeed the [build submission frequency limits](https://scan.coverity.com/faq#frequency) will often collide with an automated build (and submission) mechanism - I have no (fully automated) solution for this either. I guess a cron job triggering a (not otherwise modified) fork to be synced with its upstream, committing and pushing this stage (just into the fork) then triggering a build via Travis-CI and that triggering a submission to Coverity / Synopsis Scan could do. Quite a bit of overhead, I guess, but it should work since you can decide on the build / submission frequency this way, remaining below the limits.

**Comment by tomreyn** [comment]
Revisiting the topic on how to extract analysis results, I stumbled upon
https://stackoverflow.com/questions/44119285/does-coverity-have-rest-api

I did not succeed in using HTTP basic authentication to authenticate against one of the report servers using a URL like this:
`
curl --verbose --user 'tomreyn%40megaglest.org:MYPASSWORD 'https://scan7.coverity.com/api/viewContents/issues/v1/All%20Newly%20Detected?projectId=MegaGlest&rowCount=-1'
`

I was, however, able to access this URL directly from my web browser just fine, and got a somewhat usable JSON output. Apparently the "REST API" allowing this type of scripted access is a newer feature. Chances are that the Coverity Scan (for OSS scans) platform is just not updated to the latest Coverity Analysis platform, yet. 

I also learned that there actually *is* an export feature on the web UI:

![covscan_export](https://user-images.githubusercontent.com/1328851/38733244-70a40e42-3f21-11e8-8c4e-06e01cd37c95.png)
