### ISSUE TITLE
CPU and GPU usage slowly increase even though the application does not more than it did at the start.

### ISSUE THREAD

**Issue by Lauriichan** [godotengine/godot#56040]
### Godot version

3.4.stable

### System information

Windows 10, GLES2, NVidia GeFore GTX 1050 Ti, Driver version 487.09

### Issue description

I was creating a small Audio Visualizer for personal use in videos / streams and noticed that even though the application was running just fine all the time the cpu and gpu usage was always increasing. It increased up to 40% CPU / 40% GPU usage.
What was even more surprising was that when I opened the custom context menu I made and closed it again that the CPU and GPU usage reset to 3-4% almost instantly without having the application have a lag or something, it just worked fine all the way through but yeah.
What I expected was that it stays on the same CPU and GPU usage all the time as what the application does didn't change over time.

Something which was even more surprising was when I tried to create the minimal reproduction project is that when I just created a empty Control node with nothing at all and started it then the CPU usage just instantly reached 38% and the GPU usage even up to 55% which makes no sense to me.
The only thing which the engine should render and do right now is clear the world all the time as there is nothing in there.

### Steps to reproduce

Using "ReproductionUsage" project:
1. Import the project
2. Either start the Control Scene from your Godot editor or export it
3. Open for example Task Manager and look at your CPU and GPU usage

Using the "Audio Visualizer" project (not minimal I think):
1. Clone my git repository ([Click here](https://github.com/Lauriichan/Audio-Visualizer))
2. Import it in godot
3. Start the project
4. Open something to monitor your CPU and GPU usage
5. After it has gone up by some rightlick on the Audio Visualizer to open the Context Menu
6. Then close the Context Menu again by rightclicking
7. You can repeat that as long as you want it will always decrease the CPU and GPU usage

### Minimal reproduction project

[ReproductionUsage.zip](https://github.com/godotengine/godot/files/7738614/ReproductionUsage.zip)

**Comment by lawnjelly** [comment]
You probably want to turn on `vsync`.

Without vsync, an app or game will run unconstrained, and will use up as much CPU and GPU as it can.

**Comment by Lauriichan** [comment]
So I actually had vsync on at the beginning and I disabled it because I thought that might help with this issue.
It doesn't matter if I have vsync on or off.
Also the Audio Visualizer Project does set the target FPS and UPS of the engine.
The FPS to 45 and the UPS to 45.
I actually played around with those settings and if I go to about 10 FPS / UPS the CPU and GPU usage seems to stay at the same level. But if you go higher the CPU and GPU usage rises slowly which again makes no sense to me. If it uses 3-4% and does not more than before then why is the CPU and GPU usage rising up to 40% after about 20 seconds or something.

**Comment by Lauriichan** [comment]
Okay after some testing later I discovered that if I use my AudioSpectrum script in a blank project everything works out well.
And that script is the only heavy script in the whole project everything else is either plain default or does nothing
So it seems like some of the node types I'm using are constantly doing something which I'm unaware of

**Comment by Lauriichan** [comment]
Okay I seem to have found the problem.
![image](https://user-images.githubusercontent.com/41839265/146640174-f3533690-8a99-4a67-b13d-9c099cd2e473.png)
I was drawing the Styleboxes down here and moving it to _draw seems to have fixed it.
Why is there such a huge difference between _process and _draw?

**Comment by Calinou** [comment]
Calling `update()` in `_process()` will force continuous redrawing, whereas doing so in `_draw()` will not. If you want to benefit from low-processor mode (which you should always enable for non-game applications on desktop platforms), you need to make sure that redrawing only happens when it is actually needed.

**Comment by Lauriichan** [comment]
Thanks for the answer but that's not exactly what I meant.
Calling `update()` in `_process()` when using `_draw()` to draw the style boxes uses less!! CPU and GPU usage than drawing the style boxes in `_process()` directly. Which is why I was wandering what the difference is

**Comment by Calinou** [comment]
> Thanks for the answer but that's not exactly what I meant.
Calling `update()` in `_process()` when using `_draw()` to draw the style boxes uses less!! CPU and GPU usage than drawing the style boxes in `_process()` directly. Which is why I was wandering what the difference is

If you call drawing functions in `_process`, they will be performed every frame, regardless of whether there was an actual change in the CanvasItem's appearance. If you call drawing functions in `_draw`, they will only be drawn when needed.

> Something which was even more surprising was when I tried to create the minimal reproduction project is that when I just created a empty Control node with nothing at all and started it then the CPU usage just instantly reached 38% and the GPU usage even up to 55% which makes no sense to me.
The only thing which the engine should render and do right now is clear the world all the time as there is nothing in there.

In the minimal reproduction project, this occurs because low-processor mode isn't enabled in the Project Settings. It is not enabled by default because it can impact responsiveness negatively in games where everything on screen will change every frame (most of the time).
