### ISSUE TITLE
GradientEdit uses wrong ColorPicker

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#56081]
### Godot version

8485d0c

### System information

W10

### Issue description

![nsevsaYAU7](https://user-images.githubusercontent.com/2223172/146696210-8ea301d8-1f9c-44e6-b7e8-3651ed671aec.gif)
It's different from the editor's default.

### Steps to reproduce

1. Add anything that uses Gradient resource (e.g. ParticlesMaterial with color ramp)
2. Edit the color in gradient
3. Notice the old ColorPicker

**Comment by jmb462** [comment]
The new default ColorPicker Shape is "VHS Circle".

PropertyEditor get the default shape via EDITOR_GET("interface/inspector/default_color_picker_shape");
(That's why Modulate button pops the new ColorPicker shape)

GradientEdit belongs to /scene (not /editor) so EDITOR_GET is not possible. It uses the old shape by default.

Should we force VHS Circle shape in GradientEdit or what could be the proper way to get the editor setting from here ?
