### ISSUE TITLE
Godot Mono: InvalidProjectFileException on folder rename.

### ISSUE THREAD

**Issue by tx350z** [godotengine/godot#56095]
### Godot version

v3.4.stable.mono.official [206ba70f4]

### System information

Windows 8.1

### Issue description

Renaming a project folder generates the following exception.

ERROR: Microsoft.Build.Exceptions.InvalidProjectFileException: The project file could not be loaded. Could not find file "C:\dev2\gd_monolab\gd_monolab.csproj" C:\dev2\gd_monolab\gd_monolab.csproj at: debug_send_unhandled_exception_error (modules/mono/mono_gd/gd_mono_utils.cpp:369)

The .csproj file is not created until a .cs script is created and opened for editing.

### Steps to reproduce

Launch Godot Mono
Create a new project.
Add a folder to the project.
Rename the folder.

**Comment by raulsntos** [comment]
Just to confirm, this issue is about renaming a folder from the FileSystem dock before a .csproj is generated, right?

- Does renaming the folder from the Windows Explorer cause any issues?
- If you manually create the solution (`Project > Tools > Mono > Create C# solution`), does renaming a folder after that work?

Since renaming is basically the same as moving, I expect the same issue to happen when moving folders. Also, removing folders probably causes the same issue. Can you confirm?

**Comment by akien-mga** [comment]
Fixed by #56101.

**Comment by tx350z** [comment]
Many thanks for the quick work! You folks are under appreciated.
