### ISSUE TITLE
Vulkan: VoxelGI Artifacts from casting emissive light

### ISSUE THREAD

**Issue by Norrox** [godotengine/godot#56149]
### Godot version

830b54a03b480f29e60b4ebc813c1e24ac140a70

### System information

Windows 10, GTX 1080 Ti, Vulkan

### Issue description

I can for the love of god not get rid of the square artifacts from the light cast from the emissive light. the omni light is able to cast a smooth light on the surface. i want to belive that i tried every setting possible to change this.
is this a bug?
![Skärmbild 2021-12-22 024343](https://user-images.githubusercontent.com/13393087/147021295-63337cd2-cfc8-4829-9c8b-afd80fc7b72d.png)
![Skärmbild 2021-12-22 025417](https://user-images.githubusercontent.com/13393087/147021787-06bd13ca-25be-4fb1-a27e-141715fdf83a.png)

### Steps to reproduce

Add emissive light, add something to cast on, add VoxelGI

### Minimal reproduction project

[EmissiveGI.zip](https://github.com/godotengine/godot/files/7759379/EmissiveGI.zip)

**Comment by clayjohn** [comment]
It doesn't look like a bug. Remember, that VoxelGI uses voxels to store lighting information, so the underlying data gets limited by a voxel grid. To reduce the visual artifacts you can:
1. decrease the emissive strength of the material (All real time GI solutions struggle with small sources of bright light, VoxelGI is no exception);
2. decrease the area that the VoxelGI covers or increase the resolution (this will make the square artifacts smaller and less noticeable, but will not remove them); or
3. fake GI instead of relying on VoxelGI completely (for a sphere light source, it is a much better option to use an omnilight with a size set to match the size of the sphere)

I hope that we can improve the visual artifacts to make them less noticeable. Especially in your second screenshot there appears to be some bilinear filtering artifacts, so perhaps applying a smoother filter will improve the look of the GI. But it is unlikely that you can totally eliminate the issue because of the Voxel nature of VoxelGI.

**Comment by Norrox** [comment]
Yeah adding a omni light to the emissive object seems to be the better option.
What is the reason emissive object don't cast light like omni lights?

**Comment by Calinou** [comment]
Remember that bilinear filtering artifacts become less noticeable as you add high-frequency detail to the scene (textures, more geometric detail, etc).

**Comment by Norrox** [comment]
LightmapGI is it the same as 3.x GIProbe?

**Comment by clayjohn** [comment]
> What is the reason emissive object don't cast light like omni lights?

They are totally different techniques. In order to render things efficiently we have to create simple representations of objects. Lights are defined by a few parameters and they have a special place in the rendering pipeline while meshes are represented as a bunch of triangles and they have their own place in the rendering pipeline. 

Lights use mathematical simplifications to compute how they effect nearby objects. That same math doesn't work with emissive meshes because emissive meshes don't have a mathematically defined shape. 

In order to render things in real time, meshes generally receive a list of lights that effect them, but rendering one mesh doesn't rely on other meshes. We use GI solutions to calculate how much light one mesh casts on to another, but Realtime GI solutions are approximations at best.

> LightmapGI is it the same as 3.x GIProbe?

No. VoxelGI is equivalent to GIProbe. LightmapGI is equivalent to BakedLightmap

**Comment by Norrox** [comment]
Thanks for the information :)
Guys, is this a bug? do i need to make a new issue for this?
![glowbug](https://user-images.githubusercontent.com/13393087/147090260-3f562b9e-adf2-48e4-a840-bf4c26d0d91a.gif)

**Comment by Norrox** [comment]
Im closing this since it's not really an issure, more of an improvment for the future maybe? :)
