### ISSUE TITLE
Why does the input function not have is_action_just_pressed

### ISSUE THREAD

**Issue by JDMDK** [godotengine/godot#56143]
### Godot version

3.3

### System information

Windows 10

### Issue description

it is missing and it works perfectly fine if you do it manually

### Steps to reproduce

```
func _input(event):

	if event.is_action_just_pressed("ui_up"):
		print("hi")
```

**Comment by Calinou** [comment]
There is `Input.is_action_just_pressed()`, but not `InputEvent.is_action_just_pressed` (`event` being an instance of InputEvent).

Most of the time, you do not need an `InputEvent.is_action_just_pressed()` function because `InputEvent.is_action_pressed()` already takes care of rejecting echo (key repeat) events.

**Comment by JDMDK** [comment]
then mine is broken, if I use InputEvent.is_action_pressed() it just constantly triggers repeatedly, I only wanted to trigger once

**Comment by Calinou** [comment]
> then mine is broken, if I use InputEvent.is_action_pressed() it just constantly triggers repeatedly, I only wanted to trigger once

Are you using it with keyboard or gamepad input? If it's gamepad input, see https://github.com/godotengine/godot/issues/54959.

**Comment by JDMDK** [comment]
no I just thought I already tested it, but it turned out I used Input.is_action_pressed("ui_up"): and just assumed.
InputEvent.is_action_pressed() doesn't repeat but Input does 😅
