### ISSUE TITLE
Dragging model into 3D scene fails with "Couldn't load resource (no cache)"

### ISSUE THREAD

**Issue by andyp123** [godotengine/godot#56216]
[axes.zip](https://github.com/godotengine/godot/files/7773785/axes.zip)
### Godot version

v4.0.dev.calinou [71616630e] (also Godot_v4.0-dev.20211210_win64)

### System information

Windows 10, Ryzen 3700x, 32GB, 3060Ti, Vulkan

### Issue description

I've recorded a video of the issue from creating a new project to showing the bug occuring. The steps are mentioned in the video comments. Please let me know if there is an offical way to share videos of bugs, and I will reupload elsewhere if this Youtube hosted unlisted video is a problem. Here's the link: https://youtu.be/Xn-hqL6xnUA

I often get two resources after dragging a gltf file into the file tree. I don't know if there is any other way to import models, but I've always used this way with Godot 3.4, and it works fine. 

Importing GLTF models (.glb) does not generate any other assets (scenes, meshes, materials) as it does with Godot 3.4, although I can inspect the objects in the file just fine if I double click on it in the file tree or open it in the advanced import options. The engine also doesn't ask me if I would like to create a new inherited scene any more, although if I understand correctly, it's because the model importer has been reworked for Godot 4.0.

If I try to drag the glb file into an open scene, the model is displayed until I release the mouse button, but then it vanishes, leaving an empty node, and the warning `core/io/resource_format_binary.cpp:326 - Couldn't load resource (no cache): res://axes.glb::ArrayMesh_fwvu0`. I tried saving and reloading the scene, but it did not help. However, when the play button is pressed, the model is there. If I delete the .godot folder and reimport the entire project, the model will be visible in the editor, but if I drag another into the scene, the same problem occurs.

This happens with any mesh I've tried exporting with default settings from Blender 3.0 or 3.1 alpha, and I have not experienced problems on Godot 3.4, only 4.0.

### Steps to reproduce

1. Create a new empty project
2. Drag a glb file into the file tree panel to import it (I've attached the model I used to this bug report)
  At this point, you may notice you get two resources with the same name in the file tree. If you try to delete one, Godot will 
  probably crash. Viewing one by double clicking should open the advanced asset importer, but note that both resources will be 
  selected in the file tree when you double click on either one of them. This is the first strange part of this issue.
3. Try dragging one of the .glb resources into the scene
  In my case, the model displays in the scene until I release the mouse button to place it, but then it vanished, leaving a warning in 
the console `core/io/resource_format_binary.cpp:326 - Couldn't load resource (no cache): res://axes.glb::ArrayMesh_fwvu0`. An empty node will be left in the scene.
4. Save and reload the scene. The model should now be visible.
5. _Alternatively_, place a camera in the scene and run the project. The model should be displayed correctly in game, even if it is not shown in the editor window.

**Comment by Calinou** [comment]
I've found that if you reference a single imported glTF scene in two different open scenes in the editor, the mesh will stop displaying in at least one of the open scenes. Closing one of the open scenes and reloading the other scene usually resolves this issue.

**Comment by NNesh** [comment]
This causes due to updating a cache index for the _main_ internal resource only.
https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/core/io/resource_format_binary.cpp#L736-L738

But this executes for the all internal resources after the above code https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/core/io/resource_format_binary.cpp#L754

Should we leave this condition?
https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/core/io/resource_format_binary.cpp#L736

**Comment by fire** [comment]
Is there a pr for `updating a cache index for the internal resources including main resource.` so we can test?

**Comment by NNesh** [comment]
@fire I've made some test and it's not due to a main resource. It's due to _ResourceCache_:
https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/core/io/resource_format_binary.cpp#L681-L688
But here we always create _ResourceLoaderBinary_, which has an internal index cache:
https://github.com/godotengine/godot/blob/91b97dac03996c4b8791633ea6fa8fdc47852cb6/core/io/resource_format_binary.cpp#L1025-L1035
Other words, internal_index_cache is empty, but a path of the resource is in the ResourceCache. The first creating of a node in a scene is successfull. But after...
