### ISSUE TITLE
about  my last Issue -Invalid set index 'value' (on base: 'Nil') with value of type 'int'

### ISSUE THREAD

**Issue by setwind** [godotengine/godot#56271]
### Godot version

3.4.2

### System information

windows7 32bit

### Issue description

onready var hbar= $MarginContainer/HBoxContainer/TextureProgress.value  <- this  is my typing error  or copy error

onready var hbar= $MarginContainer/HBoxContainer/TextureProgress  -> IS  MY ORGINALl  CODE

it's real bug ,NOT  seeking for help

### Steps to reproduce

extends CanvasLayer

var barRed=preload('res://imgs/redBar.png')
var barGreen=preload('res://imgs/blueBar.png')
var barYellow=preload('res://imgs/yellowBar.png')
var bar_texture
onready var hbar= $MarginContainer/HBoxContainer/TextureProgress
func update_healthbar(_value):                          <-HERE I already emit a signal to call it . it's correct

bar_texture=barGreen
if value<60:
	bar_texture=barYellow
	pass
if value<25:
	bar_texture=barRed
	pass
hbar.texture_progress=bar_texture
hbar.value=_value

**Comment by setwind** [comment]
I test it  many times .

**Comment by KoBeWi** [comment]
At least provide a minimal reproduction project.
Also you could've commented in the previous issue. Closed doesn't mean you can't comment.

**Comment by setwind** [comment]
[http://www.hsjb.cn/tmp/aGame9.rar](url)

I can't use github app,this is the link url

**Comment by KoBeWi** [comment]
The problem here is execution order of things in the scene. Here's what happens:
1. myPlane enters tree
2. bloodUI enters tree. The signal `health_changed` is connected
3. myPlane receives READY notification, it emits the signal
4. bloodUI receives the signal -> here's your "bug"
5. bloodUI receives READY notification; initializes the `onready` variable and prints "ffff" (you can continue execution after error to reach this code)

tbh I'm a bit surprised myself that first all child nodes get `_enter_tree()` and after that they all get `_ready()` (instead of being mixed), but this is a correct and documented behavior, even if a bit unexpected. Not sure if we can improve something on our side.

**Comment by setwind** [comment]
thank you . let me think it over

**Comment by setwind** [comment]
adjusting the bloodUI to above can solve the problem according to your analysis in main game scene

**Comment by setwind** [comment]
may be it's  difficult for ordinary people to notice the problem of scene sorting

**Comment by setwind** [comment]
any way thank you  for helping  me  learn GODOT deeply

**Comment by akien-mga** [comment]
> tbh I'm a bit surprised myself that first all child nodes get `_enter_tree()` and after that they all get `_ready()` (instead of being mixed), but this is a correct and documented behavior, even if a bit unexpected. Not sure if we can improve something on our side.

That's intended behavior, and it's indeed well documented in the `Node` docs, so I think this can be closed.
