### ISSUE TITLE
Network authority not set with replicator spawner

### ISSUE THREAD

**Issue by Duroxxigar** [godotengine/godot#56282]
### Godot version

4.0 dev [#28174d531b](https://github.com/godotengine/godot/commit/28174d531b7128f0281fc2b88da2f4962fd3513e)

### System information

Windows 10

### Issue description

When using the replicator, and setting it up to handle the spawning of scenes, the network authority is not set to the clients. Followed https://godotengine.org/article/multiplayer-changes-godot-4-0-report-4 example.

### Steps to reproduce

Create a basic setup with `replicator.spawn_config`. Then put movement behind an `is_network_authority()` check. You can only move if you're the server, even though it is a client that is being spawned in. If you set the network authority to be the client prior to spawning on the server, no one can move the client that is behind the auth check.

One other thing that I noticed, that wasn't immediately obvious, was handling the server spawning a character for itself and replicating that to any client that connects later.

### Minimal reproduction project

[network.zip](https://github.com/godotengine/godot/files/7781056/network.zip)

Main scene is `Lobby.tscn`. You can just run that, it'll run as `Client`. Then you can press "Q" to spawn a new instance as server.

**Comment by Faless** [comment]
Thanks, this is currently expected (i.e. only spawn from server to client is supported) but will be fixed with the new [MultiplayerSpanwer node](https://github.com/godotengine/godot-proposals/issues/3459).

**Comment by Faless** [comment]
The new proposal is implemented via #55950 .
The authority is still not automatically set but you can do it using custom spawn functions.
Spawning from client to server is also now supported (when spawners are properly configured).

**Comment by MitchReidNZ** [comment]
@Faless is there upcoming work to have authority automatically set during spawn?

**Comment by Faless** [comment]
Not right now, I'm not convinced assigning the authority of the spawned entity by default is the right choice.

**Comment by Faless** [comment]
Note that I'm not against it, I'm just not convinced it's common case, but I might be wrong, we can totally add it as an option, it should be quite easy.

**Comment by MitchReidNZ** [comment]
Yeah, I had a bit of a look at how the spawner works and it seems like implementation should be simple.

I was caught out because I created a node on the server, assigned the multiplayer authority, then added it to the scene tree so the spawner would replicate it to clients (and auto-spawn) - I had assumed network authority would be implicitly synced, like a nodes name.
I feel like the current authority should be the only one to change a nodes authority, rather than having each client responsible for figuring it out.

Perhaps I'm misinterpreting network authority though. I'm assuming that each player in a game would be the network authority for their own character node, thus allowing them to call RPCs on the server. Is that a bad starting point?

What would be your recommendation? A custom spawn function? Is multiplayer_authority something that can be exposed to MultiplayerSynchronizer?
Or is the best idea to name network-spawned nodes after the peerID, and use that to determine who should be network authority? I think I saw that in the bomberman example on your PR.

**Comment by MitchReidNZ** [comment]
Is there an @rpc(server) / @rpc(authority) type of annotation? Something to allow an RPC to be called on the server/authority by any client.
I initially used the any_peer like with the first demo. I wasn't sure if I was doing the right thing though, since it required the boilerplate to validate get_remote_sender_id matches the node name. Which felt like I was just rolling my own version of multiplayer authority. I've flip-flopped in the other direction now, and just made the player the network authority (https://github.com/MitchReidNZ/Godot-Things/commit/6729ef429161cf9bdfc0b190b294559ea0663c73)

I'll need to play around with that second demo a bit. I like the idea of letting the NetworkSynchronizer handle everything!
Though I suspect there will still be times when I want to call an RPC against the server. @rpc(any_peer) + validating remote sender ID isn't really a problem, but it does seem a bit boiler-platey for what I assume is a very common use case.

Sounds like I'm just trying to take the lazy way out by setting the authority to the player, when I should really go back to using the node name to define a 'local' authority for players. A little bit of extra boilerplate isn't the end of the world!

**Comment by Faless** [comment]
> `@rpc(any_peer)` + validating remote sender ID isn't really a problem, but it does seem a bit boiler-platey for what I assume is a very common use case.

In real life scenarios, almost every time you receive a call from a client you will want to know/use the remote sender ID.
