### ISSUE TITLE
Check in ConvexPolygonShape2D if convex hull points are used when setting points property

### ISSUE THREAD

**Issue by mhilbrunner** [godotengine/godot#56382]
> We could detect in debug builds if a concave shape is assigned to a convex collider and print a warning every time the shape is changed to a concave shape. This check is likely expensive, so it should be disabled in release builds.

See https://github.com/godotengine/godot-docs/issues/5313

**Comment by NirobNabil** [comment]
Hello @Calinou
Is this issue solved yet? Otherwise I'd like to work on it. Can you assign this issue to me?

**Comment by Zireael07** [comment]
@NirobNabil This is a PR that fixes an issue, not an issue report, so there is nothing to assign

Also Godot engine does not practice assigning issues

**Comment by NirobNabil** [comment]
Sorry i didnt notice the referenced PR before. I guess this issue has already been worked on right? In that case i wont work on this further.

Also are you sure this is not an issue? Did you mean that this is not a reported issue but just a placeholder issue created for a PR rgtemze worked on?

**Comment by Zireael07** [comment]
Ops, you're right that we're in an issue. Since there is a PR linked then yes, it's already been worked on

**Comment by purviporwal0** [comment]
Could you please assign me this issue so I can work on it?

**Comment by YuriSizov** [comment]
A bit late, but to not discourage a future reader: We do not assign issues to non-maintainers, you can just leave a comment (or not) and work on a PR. Assigning non-maintainers is risky because they can disappear without a warning, but the issue would appear to be taken. So just work on issues you find interesting, and that don't have PRs open already, and submit your work :)
