### ISSUE TITLE
Enable OS-specific shell hints

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5653]
While Godot is intended to be multi-platform, some OS-specific stuff is nice to have both for the editor and exposed for the games.

One example is  #3292, which can be enabled on Windows and Mac (and maybe on Linux too, at least for some DEs). On #5560 there's also a request for progress hint on the taskbar, which is on the same situation of the proposal for request attention.

There's also some stuff that is very specific to a single OS. On Windows you can extend the task bar context menu with recent files and custom tasks.

![explorer_2016-07-11_17-02-12](https://cloud.githubusercontent.com/assets/5599796/16744833/46bc0ee0-4789-11e6-89dd-66b8f862754e.png)  ![2016-07-11_17-00-54](https://cloud.githubusercontent.com/assets/5599796/16744805/26c15410-4789-11e6-96c7-8683654b1a80.png)

**Comment by hubbyist** [comment]
I wish OS specific features to be added with care so that godot does not seem to be favoring one OS over another just for the OS goodies. But trivial functions like progress bar and blink on event, etc are exception to this concern.

**Comment by punto-** [comment]
We already favor some OSs more than others, there's nothing wrong with
that, if we had resources we'd support all of them, but we can't..

**Comment by Calinou** [comment]
**Bugsquad note:** This issue is still relevant as of commit https://github.com/godotengine/godot/commit/ec110076caca7a75ffb4795c32362bc52151dbcc. Some of the shell hints mentioned by @vnen have already been implemented, but the "Recent files" feature on Windows remains to be supported in Godot.

**Comment by aaronfranke** [comment]
Notifications is a feature that I'd like to see implemented that needs to be given a separate implementation on each OS. For example, `notify-send` on Linux.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
