### ISSUE TITLE
Blue screen when editing a sky from environment resource

### ISSUE THREAD

**Issue by GianptDev** [godotengine/godot#56547]
### Godot version

3.4

### System information

Windows 10, gls3, amd, 4gb ram

### Issue description

so, i was editing the `def_env.tres`, specifically i was changing the properties of procedural sky, then godot freezed, my computer frezzed (can't move the mouse or do anything) and after like 5 seconds the screen became black and the blue screen showed up on my screen.

I don't have any photo of it because i didn't thinked about doing one, it was 23 pm.

I tried to reproduce the steps but godot just crashed whitout any blue screen.
There was no extra program open in the background.

After this mess when i reopened the project i found `def_env.tres` totally cleared out ( i opened whit a hex editor and it was full of `00`).

### Steps to reproduce

open the `def_env.tres` and edit the resolution to 256 and then to 2048, godot should freeze;

- If godot closes no blue screen happen and everything is normal;
- If godot don't close and the mouse don't work, then a blue screen should happen;

I got this problem twince and i'm not sure if i'm forgetting a step.

### Minimal reproduction project

This happened from a big project, but you just need `def_env.tres` i guess....

**Comment by pycbouh** [comment]
For future reference the blue screen has useful information about what exactly crashed in your system. Without it this can be anyone’s guess. It can be a GPU driver or a memory issue.

In any case, the steps that you describe shouldn’t crash Godot, let alone the host OS.

As for the file being replaced by zeros, yeah, that happens on a hard crash like that.

**Comment by akien-mga** [comment]
What happens is typically that the settings you wrote requested something that your GPU cannot handle, but also isn't capable of straight out rejecting. So Godot asks for something via OpenGL, the GPU drivers pick it up, try it, explode, and Windows crashes in turn because it couldn't recover from a GPU drivers failure at that time.

That's difficult to fix on the Godot side as each hardware/drivers setup has different capabilities, so one setting that you change which was too much for your GPU may be totally fine on a higher end one. And OpenGL doesn't provide any good capabilities to query this ahead of time to enforce some sane maximum.

Vulkan gives some more tools for this so hopefully this can be handled better in Godot 4.x, but for 3.x this can't be solved.
Note that some of those settings do have minimum and maximum values enforced via the GUI, but if you edit the `default_env.tres` manually you're taking additional risks.
