### ISSUE TITLE
Clicking on bell button does nothing

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#56550]
### Godot version

b2382183635acb4117d6b88eaffa8fd841052f10

### System information

Windows 10

### Issue description

Clicking on 
![image](https://user-images.githubusercontent.com/3036176/148364017-15956614-d858-4843-bf5b-70107eb1fc38.png)
 does nothing. I think if there is no effect that button should be either disabled or hidden. Plus it does not have a tooltip.

### Steps to reproduce

^^

**Comment by KoBeWi** [comment]
It toggles the toaster notifications.
![8ngR0Dx9bb](https://user-images.githubusercontent.com/2223172/148378828-5082a70a-8e88-4b88-87ca-8412ee667397.gif)

**Comment by Chaosus** [comment]
Ah, yeah, I have a "show internal errors in toast notification" in the disabled(auto) state (which is on by default), so pressing it does not have any effect almost always.

**Comment by gerhean** [comment]
Another thing I noticed when pressing this bell button is that it still displays errors which has already been resolved. This can also be confusing.

Demo:
![image](https://user-images.githubusercontent.com/16630400/148647334-512a3264-5539-4291-84c0-7acd533a4fbd.png)

After resolving the error, the error message is still there:
![image](https://user-images.githubusercontent.com/16630400/148647355-602e82e9-815c-4d37-ac15-e24ffc96f6ea.png)

**Comment by akien-mga** [comment]
The "show internal errors in toast notification" setting is enabled on `target=debug` builds, and disabled on `target=release_debug` (so e.g. official 4.0 alpha 1 builds have this disabled as they use `target=release_debug`).

That's intentional, as we're not convinced that those internal errors are actually useful to show in the toaster. However, some errors which might be relevant to show seem to be wrongly internal-only, and they should be changed. There might also be a double reporting of errors (e.g. the Parse Errors in the above screenshot are likely already reported somewhere else in the script editor, and having them again in the toaster is not useful).
