### ISSUE TITLE
InputEventMouseMotion.Relative gives incorrect values if MouseMode is set to Captured.

### ISSUE THREAD

**Issue by Charybdizs** [godotengine/godot#56669]
### Godot version

Godot_v3.4.2-stable_mono_win64

### System information

Windows 10

### Issue description

For some reason, when the MouseMode is set to Captured, getting the mouse's relative position returns an abnormally low value at all times. Anywhere from 10 to 100x lower than it ought to be.

### Steps to reproduce

I've provided a sample project along with this bug. Move your mouse and watch the Mouse Delta value change. Hitting Space will change the mouse mode from Captured to Visible and back again. Observe the difference in values depending on the mode.

### Minimal reproduction project

[MouseDeltaTest.zip](https://github.com/godotengine/godot/files/7840266/MouseDeltaTest.zip)

**Comment by kleonc** [comment]
You seem to incorrectly assume there can be only one `InputEventMouseMotion` during a single frame. What you're showing is `Relative` mouse movement of just the last such event occured during the given frame. Instead of overriding your `MouseDelta` (in the minimal reproduction project) you can accumulate the result for the current frame instead (since you're already zeroing it out at the end of `_Process`):
```
    public override void _Input(InputEvent @event)
    {
        if (@event is InputEventMouseMotion inputEvent)
        {
            // this:
            MouseDelta += inputEvent.Relative;

            // instead of:
            //MouseDelta = inputEvent.Relative;


            ...
```
And it should "fix the issue".

Not sure why mouse motion events occur more often (and thus with smaller values) in `MouseMode.Captured` than in `MouseMode.Visible` though.

**Comment by Calinou** [comment]
> Not sure why mouse motion events occur more often (and thus with smaller values) in MouseMode.Captured than in MouseMode.Visible though.

Raw input is used when the mouse mode is set to `Input.MOUSE_MODE_CAPTURED`.
