### ISSUE TITLE
Boolean uniform instances does not assigned properly

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#56726]
### Godot version

b2ae6f838ac04cce8358434901f59c2b7198184a

### System information

Windows 10, GTX 1060

### Issue description

Currently, all boolean types (`bool`, `bvec2`, `bvec3`, `bvec4`) in form of `instance uniform` seems doesn't assigned before passed  to the shader:

![boolean_instance_bug](https://user-images.githubusercontent.com/3036176/149157293-88d2b656-8711-4e30-83c3-109e711619ef.gif)

### Steps to reproduce

Create a shader like that, assign it to shader material & mesh, and try to change it through inspector or via code:

```
shader_type spatial;

instance uniform bool test;

void fragment() {
	ALBEDO = vec3(1, 0, 0);
	if(test) {
		ALBEDO = vec3(0, 1, 0);
	}
}
```

All other types should work fine - so changing it to the `int` type would work. I have no idea why this happening - it assigns values to the uniform buffer correctly at least at the `_fill_std140_variant_ubo_value` function.

### Minimal reproduction project

[InstanceBooleanBug.zip](https://github.com/godotengine/godot/files/7855164/InstanceBooleanBug.zip)

**Comment by nevarek** [comment]
[This line](https://github.com/godotengine/godot/blob/master/editor/editor_inspector.cpp#L3207) returns false, and indicates the ClassDB doesn't contain the property. This is causing the bug, because the editor has no idea what property to update in memory. It tries to search for `shader_params/test` and doesn't find it in the property map.

Is this kind of lookup the intended behavior or is this just a new edge case? Are unique classes added to ClassDB for dynamic properties like this?
