### ISSUE TITLE
GDScript: Rect2.has_no_area() returns true if size is negative

### ISSUE THREAD

**Issue by just-like-that** [godotengine/godot#56736]
### Godot version

3.4.2

### System information

Windows 10

### Issue description

I'm calling has_no_area() on a Rect2 which end is smaller than its position hence it's not absolute.
I'm receiving false although rect has an area if I make this rect absolute.
Is this by design or regarded as bug?
I'm expecting has_no_area() to always return the same result wether I call abs() first or not.

### Steps to reproduce

```
var rect := Rect2(10, 10, -100, -100)
print(rect.has_no_area())
print(rect.abs().has_no_area())
```
I expect same result (false) for both calls as it's still the same rect.

**Comment by clayjohn** [comment]
In your example ``rect`` is the same as ``Rect2(10, 10, -100, -100)`` while ``rect.abs()`` returns a different rect that is the same as ``Rect2(-90, -90, 100, 100)``. 

Notice how the new rect has a positive size. Mathematically speaking an area of less than zero is no area at all. However, in the context of video games it can be useful to allow negative sizes. 

The difficulty we have (and the reason this is marked as "discussion") is that there is no clear consensus on whether a negative area is or is not "some area". In a certain sense we like to think that ``rect`` and ``rect.abs()`` occupy the same area, but in another sense ``rect.abs()`` has some area while ``rect`` does not. 

A further complication is that negative sizes have very real implications for a game engine. For example, a sprite with a negative size flips in the axis that is negative. This is a very handy result for us graphics-focused developers, however, it is a total nightmare for our friends who work on physics code (how much force does an object with a size less than 0 impart?). 

Ultimately we need to agree on a convention and then make sure that the engine is internally consistent (e.g. we could agree that negative sizes dont exist and that a negative sign in front of a size value just denotes that something will be backwards, or alternatively, we could agree that a negative size represents the mathematical concept, so be careful when you use it).

**Comment by just-like-that** [comment]
That's fine with me. I came across this because I drew rects by hand with the mouse.
There are lots of approaches for me to solve this.

**It'd be valuable if the method description has a little more detail on this.
Something like: Caution: If  called on rects with negative size function always returns true.**

Even more so as method get_area() returns the same result in both cases
```
	var rect := Rect2(10, 10, -100, -100)
	print(rect.get_area())
	print(rect.abs().get_area())
```
which outputs 10000.

Because of the similarity in name I thought it's just an engine method for retrieving the area and determining if it differs from zero.

**Comment by clayjohn** [comment]
> Even more so as method get_area() returns the same result in both cases

Ah, yeah, that is definitely inconsistent between the two functions. 

Here are our definitions:
https://github.com/godotengine/godot/blob/e00a6d2b71a2b4dddc11f8baff942f241ca8d37a/core/math/rect2.h#L47

https://github.com/godotengine/godot/blob/e00a6d2b71a2b4dddc11f8baff942f241ca8d37a/core/math/rect2.h#L125-L127

It looks like we definitely need to revisit these functions. For 3.x, we need to update the documents (changing behaviour will be too much of a breaking change). For 4.0, we may be able to break compatibility to make the functions more consistent, but it may not be worthwhile, that will have to be discuss. 

cc @lawnjelly, @aaronfranke, @groud (who were active in the rocketchat discussing Rect2 yesterday)

**Comment by lawnjelly** [comment]
This seems as good a place as any to get some ramblings down. I've personally only ever seen the min / max definition used in practice - so would welcome input from anyone who has extensively used another definition, and other opinions, I know some others are more fans of treating negative areas as positive. There's obviously a fair amount of unashamed bias from yours truly for something I've used extensively, but I'm willing to be converted. :grin: 

### Introduction
There seems to be historical evidence in the Godot source code of contributors using both definitions of an AABB / Rect, or at least a confusion between the two. This may be partly why we have anomalies like `get_area()` returning a positive value for a bound that returns `has_no_area()` as true (or perhaps undocumented the former just assumes a positive area). This is something we should probably try and standardize a bit better.

Currently the polarity of `get_area()` would seem unreliable except in the case of positive areas (especially when you consider that in a width * height calculation, if both are negative it returns a positive area), and `has_no_area()` is misleading, when what it returns is `has_no_positive_area()`.

It may be easier to think about the difference on a single dimension, such as the x axis, as Rects and AABBs are just 2D and 3D versions of this.

### Min / Max (with area polarity)
The most common case I've personally seen in engines / libraries is the bound defined by min and max coordinates on polar axes, and having a negative area (uncollidable) when any of the axes maximums are less than the minimum. Note that any axis is really arbitrary in polarity (we might e.g. choose y as up, or y as down) but we measure a zone on this axis in terms of the minimum and maximum according to this coordinate system. The area / size is thus a _polar_ quantity, it has magnitude _and_ polarity, defined in relation to the minimum (which would be the position in Godot bound speak).

This should not be strange - polar areas are widely used in geometry, for instance finding which side a of a 2d line a point is on etc.

_Note that although this may be the working definition, there is no reason why you can't use alternate forms internally via encapsulation, so the definition is determined by the member function implementations rather than the data that is stored. (min max is more efficient for some collision operations, min + size can be more efficient for e.g. moving). You can also store for instance the half extents which can speed up some operations. Another variant is storing negative max or negative min, to make better use of SIMD._

The classic point in bound, and bound intersection and merging work well with this natively:
e.g.
```
bool contains_point(x) const
{
return (x >= min) && (x <= max);
}

bool intersects(const Bound &o) const
{
return !((max < o.min) || (min > o.max));
}
```

Min/Max has a number of properties which make it really handy:
* You can shrink a maximum till it is lower than the minimum to give a negative size, then grow, scale, and apply any number of operations, and the end value will be correct.
* If you overly shrink a bound below zero, there will be no collisions. If you had a bunch of object ranging from 0-10 metre size, and you shrank them by 10 metres, you might be surprised if negative area objects started detecting collisions.
* Tolerant of floating point error. Nothing special happens if you accidentally cross the 0 size boundary.
* Allows filling a blank bound by setting mins and maxs to opposite maximum extents, then adding all points using the same code. This removes the need to treat the first addition as a special case.

In addition if there is a situation where you need to use a negative area bound as a "positive bound", there is the option to call the `abs()` function which does this conversion for you. e.g. `myrect.abs().has_point(blah)`.
This flips the min and max of any axes where the max is smaller than the min.

### Allow Flipped definition (treat a negative area as a positive area in terms of collision etc)
_(Caveat, I've never seen this used in practice, so there's a certain amount of guesswork here.)_
If you instead choose to treat negative area (flipped) bounds as valid, (which Godot does in specific cases in the canvas renderer but afaik for reasons of data compression in the vertex format) there seem to be a number of potential pitfalls, here are some of the top of my head:
* If you shrink a positive bound, and it can change polarity, the code would have to clamp to zero in order to prevent unwanted collisions (assuming this is done automatically by the shrink). This would mean calculations that can potentially cross zero are no longer reliable:

For instance consider box that is 1 metres, shrinking by 2 metres then grow by 2 metres.

When clamping:
`1 metre - 2 = 0 (clamped) + 2 = 2` (does not sound right for a general operation?)
When using polar area definition:
`1 metre - 2 = -1 + 2 = 1` (sounds as expected)

* If instead you shrink but don't clamp to zero and accept a negative size as having positive area, you have a problem. For instance how do you grow a flipped bound? Will it become bigger in area or smaller? If you increase the maximum, it may become smaller!

You either end up with "shrink" function growing a flipped bound, or you end up with a stochastic effect of shrink and grow depending which side of 0 size you happen to fall on. Neither sounds ideal. And consider this is _per axis_.

* You can end up with anomalies and undefined behaviour. For instance if you merge a flipped bound to itself, what should be the polarity of the result?
* You also may end up having to call `abs()` on any arguments prior to use, or end up write a lot of functionality twice to deal with the various permutations of flipped and non-flipped function arguments.

### What do others use

Unreal
https://docs.unrealengine.com/4.27/en-US/API/Runtime/Core/Math/FIntRect/
https://docs.unrealengine.com/4.27/en-US/API/Runtime/Core/Math/FBox/
Seems to follow the min / max convention.

Unity
https://docs.unity3d.com/ScriptReference/Rect.html
They seem to allow either using min max, or allowing flipped bounds using allowInverse.

GeometricTools
https://www.geometrictools.com/Documentation/AABBForTransformedAABB.pdf
Looks like min/max

PyGame
Uses position / size, but appears to use min/max internally:
https://github.com/pygame/pygame/blob/main/src_c/rect.c

**Comment by just-like-that** [comment]
@clayjohn @lawnjelly 

What's the initial intention resp UC of method has_no_area()?

Would it be enough to just compare if size differs zero?

Like so
```
_FORCE_INLINE_ bool has_no_area() const { 
 	return (size.x != 0 && size.y != 0);
 } 
```

**Comment by lawnjelly** [comment]
> intention resp UC

You would have to ask the original author.

> Would it be enough to just compare if size differs zero?
 Like so
_FORCE_INLINE_ bool has_no_area() const { 
 	return (size.x != 0 && size.y != 0);
 } 

Unlikely no.
