### ISSUE TITLE
physical bone transform not right

### ISSUE THREAD

**Issue by ywaby** [godotengine/godot#56745]
### Godot version

master

### System information

linux,gtx1050ti,vulkan

### Issue description

physical bone tansform not right, when AnimationTree is child of AnimationPlayer. 
![Screenshot_2022-01-13_16-14-43](https://user-images.githubusercontent.com/12198203/149291575-7edbaaf9-f56d-4b18-a8b3-c7b0d9fd2cd4.png)

### Steps to reproduce

1. active animation tree
2. play walk
3. select animation player 

### Minimal reproduction project

[godot_physicalbone.zip](https://github.com/godotengine/godot/files/7919909/godot_physicalbone.zip)

**Comment by TokageItLab** [comment]
It looks like the initial pose when generating the physical bone is wrong. Also, if you want to animate physical bones, you should set the process mode to `Physics` instead of `Idle`.

**Comment by ywaby** [comment]
[godot_physicalbone.zip](https://github.com/godotengine/godot/files/7919909/godot_physicalbone.zip)

@TokageItLab 
> It looks like the initial pose when generating the physical bone is wrong.

I don't know what you mean.

it work fine when AnimationTree is up AnimationPlay

https://user-images.githubusercontent.com/12198203/150667217-ed356c32-c62d-4770-800f-bf4c7d9d967a.mp4

It cause the problem when  AnimationTree is blow AnimationPlay  

https://user-images.githubusercontent.com/12198203/150667219-64f45314-6fce-4004-befc-50e83b2ffca1.mp4



>  if you want to animate physical bones, you should set the process mode to Physics instead of Idle in AnimationPlayer and AnimationTree.

Physcial bone will not animate if set AnimationPlayer/AnimationTree process mode to  physics, 

here is Physics mode  

https://user-images.githubusercontent.com/12198203/150666996-c80ecbfd-81d7-4e79-a678-26e622e042dc.mp4

here is idle mode  

https://user-images.githubusercontent.com/12198203/150667001-784c91a1-a984-4b26-9959-7d236da58cd1.mp4

**Comment by TokageItLab** [comment]
@ywaby It certainly doesn't seem to be a problem only when creating PysicalBones, sorry my fault. The problem does not occur in animations where the BoneRest is always equal to the BoneRest. Perhaps the problem is that the PysicalBone is somehow being moved when the AnimationPlayer is sought, and we should look into the seeking process of the AnimationPlayer.

https://user-images.githubusercontent.com/61938263/150668719-76211344-f148-4902-a0bb-4317aa4258fe.mov

---

> Physcial bone will not animate if set AnimationPlayer/AnimationTree process mode to physics,

It's not directly related to this bug, but you should use physical mode for objects involving physics. Your project was playing the PysicalBone animation out of sync in my environment.

https://user-images.githubusercontent.com/61938263/150668726-b0c1283f-193f-4d4a-9df6-84beddd155b7.mov

**Comment by akien-mga** [comment]
Was this closed because it's fixed, or because it's no longer relevant to you?

**Comment by ywaby** [comment]
> Was this closed because it's fixed, or because it's no longer relevant to you?

I cant recurrence problem in Latest build.  it maybe fixed.
