### ISSUE TITLE
GDScript 2.0: Lambda capturing issues with default parameter values

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot#56751]
### Godot version

4.0.dev (99b46a261)

### System information

5.15.12-1-MANJARO

### Issue description

Lambdas seem to fail capturing locals that are used in parameter defaults:

```gdscript
func _ready():
	var x = "local"
	var lambda = func(param=x): print(param)
	lambda.call()
```
```
Parse Error: Identifier "x" not declared in the current scope.
```

But magically, if we simply add a member with the same identifier, it works (and correctly uses the local):

```gdscript
var x = "member" # having this lets it compile
func _ready():
	var x = "local" # this is the one that gets used (as expected)
	var lambda = func(param=x): print(param)
	lambda.call()
```
```
local
```

Very messed up case:

```gdscript
var x = "member" # this is still required
func _ready():
	#var x = "local" # does not affect anything
	var lambda = func(x=x): print(x)
	lambda.call()
```
```
null
```

### Steps to reproduce

Reproducible code in the description above.

**Comment by vnen** [comment]
> Very messed up case:
> 
> ```gdscript
> var x = "member" # this is still required
> func _ready():
> 	#var x = "local" # does not affect anything
> 	var lambda = func(x=x): print(x)
> 	lambda.call()
> ```
> 
> ```
> null
> ```

This is actually a general issue with default parameters, not only with lambdas. The problem is that the default value is gathered later so it uses the local value instead (which is empty), since it's in a closer scope. If you try to do `func any(x=x)` you'll get a parser error if `x` isn't previously declared (note that `func any(a, b=a)` is valid and works as intended).

For the first issue I'm about to post a fix.
