### ISSUE TITLE
Profiler: usability ideas

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5682]
After testing a bit the profiler, I have a few ideas to improve its usability:
- Ability to focus spikes more easily. Half of performance bottlenecks can be seen as spikes, and focusing them in the profiler is currently a bit tedious since you have to be pixel-perfect when clicking on the graph.
  Could we have zoom or something allowing easy precision?
- Functions taking most time should be ordered first instead of last, because they are the point of profiling. I see I can click on the headers but it does nothing particular.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by Zireael07** [comment]
Being able to order the functions by time spent would massively improve the usability of the profiler. (As simple as making the click on the header sort decreasing/increasing)

**Comment by Zireael07** [comment]
Bump. Zooming in and ordering are needed.

Also in the monitors tab, what is the range of values for fps? It's weirdly difficult to see the difference between 15 and 30 FPS.

P.S. Where should I look if I want to improve those things?

**Comment by Calinou** [comment]
**Note:** Ordering functions from most to least expensive has already been implemented in 3.1 and later by https://github.com/godotengine/godot/pull/25354.

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/god
otengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
