### ISSUE TITLE
NavigationAgent makes zigzag movements when moving to a point near the NavigationObstacle

### ISSUE THREAD

**Issue by Killfrra** [godotengine/godot#56854]
### Godot version

3.5 beta 1

### System information

Ubuntu 20.04

### Issue description

This becomes most noticeable when working with large radiuses. Sometimes this behavior is also observed when moving to a point behind an obstacle, but it is difficult to reproduce.

https://user-images.githubusercontent.com/15277964/149683977-6f281756-8561-48ca-8ee7-a409e85720cf.mp4

### Steps to reproduce

See _Map_RVO.tscn_

### Minimal reproduction project

[MOBA_3.5_v4.zip](https://github.com/godotengine/godot/files/7878256/MOBA_3.5_v4.zip)

**Comment by Scony** [comment]
I think it may have something to do with the underlying navmesh geometry which looks like this:

![2022-01-18-225448_4480x1440_scrot](https://user-images.githubusercontent.com/1207385/150027214-d0c338c7-16a7-4910-9941-63ac32a029cd.png)

**Comment by Killfrra** [comment]
I'm pretty sure the avoidance algorithm is the problem, because zigzag behavior doesn't show up when it's disabled. I assume that the algorithm works like this: it starts to bypass the obstacle, the trajectory changes, the desired speed towards the target changes and when the desired motion vector becomes perpendicular to the obstacle, it stops interfering.

I managed to fix the movement by changing the time horizon depending on the distance to the target. The idea was this: I only care about those collisions that can occur before I reach the goal. But I don't know how it will work with many agents, not sure if it's good. I like that the avoidance is completely independent of the pathfinding, maybe this issue can be regarded as not a bug at all, but just a feature that is worth mentioning in the tutorial. But, again, changing the horizon feels like a hack and will probably lead to other oddities.

In the video: no RVO, RVO, RVO + hack.

https://user-images.githubusercontent.com/15277964/150090545-2fb2fc62-96f1-44c5-9b99-6b885664a804.mp4

In the _Map_RVO_ scene (with a perfect navmesh this time) on the _RigidBody_ object, you can turn on/off the avoidance and the horizon hack.

[MOBA_3.5_v5.zip](https://github.com/godotengine/godot/files/7895237/MOBA_3.5_v5.zip)

**Comment by smix8** [comment]
@Killfrra 

The set avoidance radius with 3.6 on the `NavigationAgent.radius` is very high for the visual mesh with just 1.0 radius.

What happens is that the agent already at a far distance receives constant pushback by the avoidance.
Since the target position is inside the avoidance area the agent has no other option than to push against the avoidance vector.
At close distance to the target the agent wins over the other agent pushback so it can zig back in.

Static obstacles should not use NavigationAgents or NavigationObstacles. Those are intended for constantly moving objects like CharacterBody3D. Static objects should be (re)baked to navmesh so agents can avoid them and their outline with better detail as the RVO avoidance only has a radius value and does not follow the real geometry.

So technically this is not a bug but documentation / expectation issue.
