### ISSUE TITLE
Editor help has degraded performance when resizing (RichTextLabel regression?)

### ISSUE THREAD

**Issue by pycbouh** [godotengine/godot#56900]
### Godot version

4.0 (#366d393)

### System information

Windows 10, Ryzen 5900 X, Radeon 5700 XT

### Issue description

There seems to be some performance degradation when trying to resize a built-in doc page. It seems to perform worse the more content there is. Compare below how it performs for `Button` and for `ProjectSettings`.

https://user-images.githubusercontent.com/11782833/149934755-b233d435-66b7-4b7e-b9c0-92ebbd3ef89f.mp4

Scrolling seems to work fine, but opening the doc and resizing the panel causes a lot of lag. This is either something I've introduced in some of the more recent doc-related PRs, or it's a regression from some text rendering changes (cc @bruvzg @Paulb23 ?)

### Steps to reproduce

Just open the built-in docs and try to resize the panel. Should work with a project of any size, I believe, as smaller class references perform noticeably better (but still choppy). I've also tried in a completely new and empty project.

### Minimal reproduction project

N/a

**Comment by pycbouh** [comment]
Akien confirmed bad performance:
> Yeah I can confirm that resizing is slow. Also slow in 9b3535a33 (Jan 14).

**Comment by bruvzg** [comment]
Seems like for some reason, editor help RTL is receiving `NOTIFICATION_THEME_CHANGED` on each resize, which causing full reshaping of the text instead of resizing it (resizing is 3-5 times faster than reshaping).

**Comment by bruvzg** [comment]
The source of theme change is `add_theme_style_override` call here: https://github.com/godotengine/godot/blob/f8b8d0d4b82a5eb6ea3829398fd5076f1c49c148/editor/editor_help.cpp#L166-L178

**Comment by bruvzg** [comment]
It's necessary to reshape only if font is changed, adding extra type of notifications for the font change and font size change (can be optimized to rescale shaped text, instead of reshaping) instead of `NOTIFICATION_THEME_CHANGED` might be worth.

In any case, I'll add functions to set font and language without resetting the text to the `TextServer`, this allows to skip some steps (~10% of processing), and functions to rescale text on font size change.
