### ISSUE TITLE
Refactoring: Code files to rename or split

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5691]
This is a brainstorming issue so that we can see what we'd like to rename/split when we start working on 3.0 (and thus will be allowed to break compatibility).
## Files to rename
- `core/path_db:*` -> `core/node_path.*`, to match their actual class
## Files to split
- `core/math_2d.*` -> `core/vector_2d.*`, + more as needed
- `tools/editor/editor_node.*` -> TODO, list potential split classes

**Comment by bojidar-bg** [comment]
Maybe, `core/math_2d.*` -> `core/vector_2d.*`, + more as needed
That would be nice for easier finding of the right file, either using the GitHub file finder (<kbd>T</kbd>) or Atom's file finder (<kbd>Ctrl</kbd> + <kbd>T</kbd>) and others

**Comment by reduz** [comment]
I fixed a ton of these files the past month, from scene_main_loop.h -> scene_tree.h to many many more.
Guess I forgot about path_db.h, will fix it.

For math 2D i think it's kind of ok as is, as they are not very large classes

**Comment by tagcup** [comment]
matrix3 (in matrix3.cpp) has been renamed to basis, and AABB was renamed to rect3, right?

**Comment by aaronfranke** [comment]
I've created a version of `math_2d` with `vector2` split up into its own files. Excluding the 30-line comment at the top, `vector2.cpp` is about 150 lines and `vector2.h` is about 210 lines.

@reduz We do have smaller standalone files, `math_defs.h` is under 40 lines of useful code. I definitely think it's worth splitting `vector2` into its own files, it improves readability of both `vector2` and the rest of `math_2d` due to being smaller files.

I'll create a PR sometime soon.
