### ISSUE TITLE
Label with text overrun behaviour ellipsis inside HBox gets trimmed completely

### ISSUE THREAD

**Issue by stijn-h** [godotengine/godot#56915]
### Godot version

8958e1b35297baa8ef4f9e03bb4ad105500e3a0c

### System information

W10

### Issue description

Consider two labels inside an HBoxContainer, both with ellipsis. With just a horizontal size flag of FILL, they are both completely invisible:

![fill](https://user-images.githubusercontent.com/25907608/152680051-846587b4-0288-4aab-bdcd-15c7bc2ec4d9.png)

. Adding the EXPAND flag does make them show up:

![fill_expand](https://user-images.githubusercontent.com/25907608/152680063-f8010de2-33f2-410b-8794-312f047e7036.png)

but it always forces both labels to take the same amount of space. This can be a problem when one of the labels is shorter than the other:

![fill_expand2](https://user-images.githubusercontent.com/25907608/152680066-4ddc1cbf-5412-4bb2-a87e-62e03bba5fad.png)

So I can't use EXPAND for my use case. I would like to see FILL work this way:

![fill2](https://user-images.githubusercontent.com/25907608/152680253-a7d60e98-170e-4905-a756-9c86c12a8668.png)

### Steps to reproduce

Make a scene like this:

```
HBoxContainer
   Label1
   Label2
```

Configure both Labels with some text, horizontal size flag FILL, overrun behaviour -> trim_ellipsis

Both labels should now be invisible (see file below).

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/7891437/test.zip)

**Comment by fire540** [comment]
Does using Fill and Expand not work for what you're trying to do?

**Comment by hinlopen** [comment]
No, using Expand results in the image above. It cuts off the labels before it, and pushes away labels after it.

**Comment by Calinou** [comment]
@stijn-h Can you still reproduce this on 4.2.2 or later, or is the issue resolved?

**Comment by stijn-h** [comment]
@Calinou It doesn't seem like a bug, but more like a 'potentially missing feature' to me. I closed it since I personally no longer need this anymore, and it doesn't seem like anybody else does, either.

**Comment by a-johnston** [comment]
(Coincidentally ran into this issue a few days after looking at the relevant code, just dumping some info)

The root cause is that there is no way for the label to set/advertise a preferred size to the parent container, only a minimum size, when being laid out by the parent. Since text overrun handling means that there is no technical minimum size, as it can be handled by ellipsis etc, it doesn't bother to compute that and ends up with a minimum width of 1px. Even if the parent container has enough size, it'll still use that 1px minimum size when expand isn't set. Ideally IMO the label would always compute a target size and the parent container would then size it between that and the minimum size (or greater if expand is set) but afaik this is a design limitation with the current UI stuff.
