### ISSUE TITLE
Plugins don't show up in Editor settings

### ISSUE THREAD

**Issue by hanst99** [godotengine/godot#5694]
**Windows - 2.0.4.1.stable.official (Steam version):**

Plugins don't show up as available in the editor settings. According to the docs and information I read elsewhere, they should show up if there's a plugin.cfg in either `res://addons/<plugin name>/` or (on windows) `$env:APPDATA/godot/plugins/<plugin name>/ `. I have tried both with self made plugins following the plugin tutorial in the docs, as well as plugins I grabbed from github, and neither seemed to work even after refreshing the plugin list.

**Attempt to install any plugin**

**Link to minimal example project https://github.com/hanst99/godot_bug_demonstration**

I'm naturally not sure if this is a genuine bug or a documentation bug or if my assumptions about how this works are just wrong.

**Comment by akien-mga** [comment]
That's not a bug but a lack of clarity on the documentation; the page about making plugins is actually specific to the upcoming 2.1 version where the plugin API was completely reworked. Having plugins `res://addons/` is also something that is arriving in 2.1 (you can test the freshly released 2.1-beta if you want).

For 2.0, there was no official documentation about making plugins, but they had to be placed in `%APPDATA$/godot/plugins/` as you mentioned yes. Since the API changed a lot, those plugins are no longer compatible with Godot 2.1; I'd advise you to go directly with the beta while learning how to make plugins, since the days of 2.0 are counted :)

**Comment by hanst99** [comment]
Cool. I'd personally mark this as a documentation bug though; Documentation should make it clear if something only applies to specific versions of the engine, especially if the feature isn't 'released' yet.
