### ISSUE TITLE
Broken StreamTexture3D s3tc VRAM compression after #56931

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#57092]
### Godot version

4.0.dev (dda6d2674)

### System information

Linux, Mageia 9 x86_64

### Issue description

Since #56931, images imported as StreamTexture3D and S3TC VRAM compression seem to be broken. There are no errors during import, but attempting to use them spams the output with these errors:

```
ERROR: Image size mismatch
   at: texture_3d_initialize (servers/rendering/renderer_rd/renderer_storage_rd.cpp:663)
ERROR: Attempting to use an uninitialized RID
   at: get_or_null (./core/templates/rid_owner.h:199)
ERROR: Condition "!tex" is true.
   at: texture_set_path (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1083)
ERROR: Attempting to use an uninitialized RID
   at: get_or_null (./core/templates/rid_owner.h:199)
ERROR: Condition "!tex" is true.
   at: texture_set_path (servers/rendering/renderer_rd/renderer_storage_rd.cpp:1083)
ERROR: Attempting to use an uninitialized RID
   at: get_or_null (./core/templates/rid_owner.h:199)
ERROR: Condition "!t" is true. Returning: false
   at: free (servers/rendering/renderer_rd/renderer_storage_rd.cpp:9217)
```

This was seen first in https://github.com/clayjohn/godot-volumetric-cloud-demo where `perlworlnoise.tga` and `worlnoise.bmp` trigger the issue, and the demo is broken.
This is however not specific to TGA or BMP, the same happens when converting `perlworlnoise.tga` to PNG and importing it with the same import settings.

I confirm with a local revert that the bug was introduced by #56931 (clearing `.godot/` is needed when changing builds as the bug happens during import).

CC @godotengine/import @godotengine/rendering

### Steps to reproduce

- Open the MRP
- Try to use `worlnoise.bmp` which is imported as StreamTexture3D (e.g. by drag and dropping from filesystem to the canvas item editor - this isn't supported for StreamTexture3D but it will still trigger an error that wouldn't happen before that PR)
- Alternatively, open https://github.com/clayjohn/godot-volumetric-cloud-demo

### Minimal reproduction project

[regression-StreamTexture3D-import.zip](https://github.com/godotengine/godot/files/7921015/regression-StreamTexture3D-import.zip)

**Comment by fire** [comment]
The mipmap generating code is in ResourceImporterLayeredTexture::_save_tex https://github.com/godotengine/godot/blob/a27b85378ba75bacd9730e609f6068a5fd73484e/editor/import/resource_importer_layered_texture.cpp#L158

**Comment by lyuma** [comment]
ok, so the issue is that 3d textures create separate Image objects for each mipmap level, then compresses them independently, which is technically not correct because individual mipmap levels are not subject to the multiple of 4 requirement, but now it resizes the individual mipmaps to a multiple of 4x4.

Indeed, I can confirm that this resizing-to-4 is interfering with godot's validation code to check a 3D texture for incorrect mipmap or layer sizes:
![illustration_of_3dtex_bug](https://user-images.githubusercontent.com/39946030/150695015-890b8266-e51a-45dc-9134-becca6c8fb7b.png)
In the screenshot, the last 4 layers should have been 4x4, 2x2, 2x2 and 1x1, but they are instead all 4x4

I'll submit a workaround to disable resizing to Nx4 for 2x2 and 1x1 Image's
