### ISSUE TITLE
iOS export failing when entering provisioning profile and codesign identity

### ISSUE THREAD

**Issue by ehmprah** [godotengine/godot#57195]
### Godot version

3.4.stable

### System information

MacOS 12.1

### Issue description

When exporting my project for iOS, I entered all necessary codesigning data like team ID, codesign identity and provisioning profile UUID. Exporting fails with the following error:

error: PROJECT has conflicting provisioning settings. PROJECT is automatically signed, but provisioning profile PROVISIONING_PROFILE has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the Signing & Capabilities editor. (in target 'PROJECT' from project 'PROJECT')
** ARCHIVE FAILED **

I would expect the automatic signing to be turned off once I supply all these details? Or am I somehow not understanding the error message?

### Steps to reproduce

See above. The only way the export works for me is to leave the provisioning profile UUID empty and by entering "iPhone Developer" / "iPhone Distribution" in the codesign identity fields.

**Comment by nathanfranke** [comment]
This should be re-opened, as someone [on Reddit](https://www.reddit.com/r/godot/comments/w9fwpe/issue_with_building_for_release_on_ios_signing/) and I can reproduce it in Godot 3.5.

Luckily, I think I found a workaround for App Store Connect (Test Flight + App Store):
1) Before continuing, do yourself a favor and make sure you have a **JPG** selected for Icons→"App Store 1024 X 1024", otherwise XCode will complain about a transparent image. This should be improved in Godot too.
2) Keep "Code Sign Identity Debug" and "Code Sign Identity Release" blank in Godot export
3) Export
4) Open XCode, click the root item to open the main settings area, switch to the Build Settings tab and scroll all the way down to Signing
5) Change **all 4** "Code Signing Identity" values to "Apple Development". This is silly but from all my testing it was the only way to trick it into working.
6) Go to the "Signing & Capabilities" tab and uncheck/recheck "Automatically manage signing" a couple times, kinda like whack a mole, until 7)
7) Eventually there should be a single signing area, with "Automatically manage signing" **checked**. Now select your Team.
8) I did Product→Archive for my own workflow, and it seems to work. Make sure App Store Connect is selected, and later on it will tell you it is resigning everything

**Comment by Overvault-64** [comment]
I'm getting this same issue when exporting to iOS with Godot 4.1.1. I've set nothing in the export settings other than team ID and package name.

**Comment by scripturial** [comment]
I am encountering the same problem 4.1.3

/Users/myapp/iOS/MyApp.xcodeproj: error: "MyApp" requires a
provisioning profile. Select a provisioning profile in the Signing & 
Capabilities editor. (in target 'MyApp' from project 'MyApp')
** ARCHIVE FAILED **

https://www.reddit.com/r/godot/comments/17vgbub/export_fails_for_ios_in_413_but_half_works/?

It appears to interrupt the build process because my SQLite library dependencies appear to not get dumped out into the Xcode project. (I think that is why anyway, I am not sure)
