### ISSUE TITLE
(4.0) Game freezes if you free() Tween target object when Tween is still running

### ISSUE THREAD

**Issue by seppoday** [godotengine/godot#57339]
### Godot version

4.0 alpha 1

### System information

Doesn't matter (Windows 10)

### Issue description

(Sorry for bad english, also new Tweening system is just fcking amazing overall, so simple to use - love it)

There is a small bug. I've created Tween in tree get_tree().create_tween() and set it on loop. When I tried to queue_free() node that was object target under that Tween game just stopped responding. @KoBeWi said that it should auto-kill itself when the target object is queue_free(). That's why I am creating this issue.

Here is gif:
![Godot_v4 0-alpha1_win64_iXj9cgbzcr](https://user-images.githubusercontent.com/62170071/151512615-6606c5fe-980a-4981-a6c1-3bbaa26902fb.gif)

There are 2 solutions, for now, to prevent the game from crashing (28.01.2022).

1. Kill tween before queue_free() it's target node.
2. Create tween under the node that you are going to queue_free(). That way it will be killed with it.

### Steps to reproduce

Try this code with this tree. Connecting signal via editor gives the same result.

Node2D (here is script)
-> Button
-> Sprite2D

```
extends Node2D

func _ready():
	var tween = get_tree().create_tween().set_loops()
	tween.tween_property($Sprite2D, "scale", Vector2(1.25, 1.25), .25).set_ease(Tween.EASE_OUT_IN).set_trans(Tween.TRANS_SINE)
	tween.tween_property($Sprite2D, "position", Vector2(100, 0), .1).as_relative()
	tween.tween_property($Sprite2D, "scale", Vector2(1.5, 1), .1).set_ease(Tween.EASE_OUT_IN).set_trans(Tween.TRANS_LINEAR)
	tween.tween_property($Sprite2D, "position", Vector2(-100, 0), .1).as_relative()
	tween.tween_property($Sprite2D, "scale", Vector2(1, 1), .1).set_ease(Tween.EASE_OUT_IN).set_trans(Tween.TRANS_LINEAR)
	$Button.pressed.connect(tween_test)
	
func tween_test():
	$Sprite2D.queue_free()
```

### Minimal reproduction project

[test23.zip](https://github.com/godotengine/godot/files/7956907/test23.zip)

**Comment by KoBeWi** [comment]
This is not a crash, but a freeze. I was partially wrong in my comment, deleting object doesn't kill the Tween, but makes it end animation on that object. So e.g. if you have an animation sequence of 10 steps and your object is deleted on step 4, the animation is interrupted and all subsequent steps are skipped, because there is no object to animate.

The problem is in case of looping animation. If the object is invalid, the Tween will just repeat the steps infinitely. This is more or less expected, this is the reason why node binding exists and why `create_tween()` instead of `get_tree().create_tween()` works in this case.

Similar issue exists when you have infinite looping tween with only a callback. Since callback has no duration, the Tween cycle will never finish and freeze. I wonder if this can be detected somehow.

**Comment by seppoday** [comment]
In my opinion this is not a problem that should be fixed. Because as I showed it is really easy to fix it. 

Maybe good "solution" would be to just add some warning/error message to debugger so people would know why game freeze, because it is kinda not clear what is going on. Game just freeze. It took me a while to find that problem.

**Comment by akien-mga** [comment]
> This is not a crash, but a freeze. 

A freeze typically ends with a crash once the instance runs out of memory :P

**Comment by seppoday** [comment]
Thanks @KoBeWi!
