### ISSUE TITLE
get_as_text() works fine in editor but fails when exporting game

### ISSUE THREAD

**Issue by Qudware** [godotengine/godot#5748]
On Windows 10, Godot 2.1 beta:
Somewhere in my game code I have this line:

    my_game_settings.parse_json(file.get_as_text())
where the file has the path 'res://settings.cfg'. I am choosing not to save to user:// since this isn't a game save but something only internal.

**In the editor when playing the scene, it works just fine & loads the file with no errors.
However, when I build an .exe I get the error:**

    ERROR: _File::get_as_text: Condition ' !f ' is true. returned: String()
    At: core\bind\core_bind.cpp:1582
I superstitiously tried changing everything! It won't budge! Same error & I don't understand C++ to know why.

**Comment by vnen** [comment]
When you export, `res://` is now inside the `.exe` (or `.pck` if exported as such). Thus you can't write there. I'm talking this because you said "save".

But since you're trying to *read*, it should be available if you exported the file. The engine by default only exports used resources, and since `settings.cfg` is not a resource name, it's ignored. So you need to explicitly add that file/extension in the export settings.

**Comment by neikeq** [comment]
`settings.cfg` is exported as `settings.cfb` which is a binary format.

**Comment by neikeq** [comment]
BTW, you can use `Globals.get_property_list()`. It mixes the settings with other properties, but if you know what you are looking for, then it's fine.

**Comment by Qudware** [comment]
Yup, I wasn't exporting .cfg files.  Sorry about the ignorance!
