### ISSUE TITLE
Embedded Windows on Windows 10/11 Don't Have an Icon

### ISSUE THREAD

**Issue by forecaster-cyber** [godotengine/godot#57484]
### Godot version

v4.0.alpha1.official [31a7ddbf8]

### System information

Windows 11

### Issue description

![Screenshot 2022-01-31 165615](https://user-images.githubusercontent.com/75746148/151816463-6ff75cc8-ecaf-4892-8936-16c1e451a709.png)

### Steps to reproduce

Open any other window (other than the main editor window)

**Comment by TechnicalSoup** [comment]
I notice that in the 3.x releases these windows are borderless, and don't have any of the native OS icons or buttons. I'm not sure if the 4.x releases will follow the same styling, but if so then the issue is probably that the windows are being opened with a border showing, and are missing the custom close icon/button.

**Comment by Calinou** [comment]
> I notice that in the 3.x releases these windows are borderless, and don't have any of the native OS icons or buttons. I'm not sure if the 4.x releases will follow the same styling, but if so then the issue is probably that the windows are being opened with a border showing, and are missing the custom close icon/button.

3.x does not have multi-window support, while Godot 4.0 does thanks to the [DisplayServer refactoring](https://godotengine.org/article/core-refactoring-progress-report-2). You can force the same styling as 3.x by enabling **Single Window Mode** in the Editor Settings.

**Comment by TechnicalSoup** [comment]
I've taken a look at the DisplayServer code, focusing on Windows as that's the platform I'm on, and I can see that the icons get set for the Main window from the Main.cpp code, but an icon is never set for the sub windows.
I'm happy to work on a fix, and at first glance I'm probably leaning towards a change in the existing set_icon code to take a window_id parameter as well as the icon.
So basically change the set_icon methods in the DisplayServer and DisplayServer<platform> classes to take an additional window_id parameter (at present it is hard coded to be the Main window).
Add in a call to the set_icon method from the Window class so that whenever a subwindow gets created an icon is set. A little care will be needed to grab the default Godot icon for the editor, and the user configured icon when running a game.

I'm happy to hear from maintainers on an alternate way of fixing this one if they have a preference. What I'm a little concerned about it my ability to change/test the equivalent code for the other platforms.

**Comment by forecaster-cyber** [comment]
> I've taken a look at the DisplayServer code, focusing on Windows as that's the platform I'm on, and I can see that the icons get set for the Main window from the Main.cpp code, but an icon is never set for the sub windows. I'm happy to work on a fix, and at first glance I'm probably leaning towards a change in the existing set_icon code to take a window_id parameter as well as the icon.
> 
> So basically...
> 
> * change the set_icon methods in the DisplayServer and DisplayServer-platform classes to take an additional window_id parameter (at present it is hard coded to be the Main window).
> * Add in a call to the set_icon method from the Window class so that whenever a subwindow gets created an icon is set. A little care will be needed to grab the default Godot icon for the editor, and the user configured icon when running a game.
> 
> I'm happy to hear from maintainers on an alternate way of fixing this one if they have a preference. What I'm a little concerned about it my ability to change/test the equivalent code for the other platforms.

I think this is a great idea!
To my knowledge, other platforms don't need it (Linux, MacOS)

**Comment by forecaster-cyber** [comment]
> I've taken a look at the DisplayServer code, focusing on Windows as that's the platform I'm on, and I can see that the icons get set for the Main window from the Main.cpp code, but an icon is never set for the sub windows. I'm happy to work on a fix, and at first glance I'm probably leaning towards a change in the existing set_icon code to take a window_id parameter as well as the icon.
> 
> So basically...
> 
> * change the set_icon methods in the DisplayServer and DisplayServer-platform classes to take an additional window_id parameter (at present it is hard coded to be the Main window).
> * Add in a call to the set_icon method from the Window class so that whenever a subwindow gets created an icon is set. A little care will be needed to grab the default Godot icon for the editor, and the user configured icon when running a game.
> 
> I'm happy to hear from maintainers on an alternate way of fixing this one if they have a preference. What I'm a little concerned about it my ability to change/test the equivalent code for the other platforms.

I think this is a great idea!

**Comment by Calinou** [comment]
@forecaster-cyber 
Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.
