### ISSUE TITLE
Feedback on new flat editor icons

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5749]
Opening this issue to collect feedback and todos for @djrm regarding the (awesome!) new flat icon set have for 2.1.
- The resource icon should still be remade: 
  ![spectacle zb4463](https://cloud.githubusercontent.com/assets/4701338/16900268/5bbb3960-4c20-11e6-803e-b0d201afcc71.png)
  Right now it even looks like Unity3D's logo, so changing that would be nice :)
- Grouping icons: They are fine already, but I'm not 100% convinced, it took me some time to understand that those were grouping icons (especially when seeing them in the SceneTree). I don't really have suggestions to improve it though, just thought I'd mention my opinion here.
  ![spectacle pe4517](https://cloud.githubusercontent.com/assets/4701338/16900281/8d5de3c8-4c20-11e6-8d30-de2350b68a3d.png)
- Node groups icon: Same feeling, but again I'm not sure how best to convey the grouping notion. It's not bad as is, but if people have suggestions for improvements, go ahead :)
  ![spectacle cj4572](https://cloud.githubusercontent.com/assets/4701338/16900285/ceda1cfe-4c20-11e6-982b-f03392121e5d.png)

Awesome work generally speaking though, Godot 2.1 looks so rad :D

**Comment by TheoXD** [comment]
am I the only one who thinks the "Object" icon reminds of Unity logo? xD

**Comment by TheoXD** [comment]
+1 to get rid of anything that reminds of Unity

**Comment by neikeq** [comment]
The Sprite icon is too scary:
![:S](https://github.com/godotengine/godot/raw/master/tools/editor/icons/2x/icon_sprite.png)

**Comment by djrm** [comment]
I agree with changing the unity logo, but i would leave it as a box (cube, since the box is already used for resource preloader)

![object](https://cloud.githubusercontent.com/assets/1103897/16901590/c55a8f78-4c0d-11e6-925a-dfb73ddc0339.png)
because it is the object icon, not the resource icon, and we can use objects to box things

about the group icons, im also not convinced by them at all, my reference was this icon:
https://design.google.com/icons/#ic_group_work  (well, basically a rip off)
but yeah given the reduced amount of space it is hard to come up with something better.

And the groups, well, it is kinda good, i mean not the best representation of a group but it is consistent with the rest of the group icons.

**Comment by TheoXD** [comment]
Grouping icons should be somewhat consistent, when I first saw the round icon I thought it was an old projector tape, next to the icon on the right it looks like "inverse selection". Gladly I knew the old buttons and recognized them by their location, to me it's like they've always been there, can barely remember how old icons looked like.

**Comment by bojidar-bg** [comment]
@djrm Well, what about getting the good ol' sphere for objects?

**Comment by djrm** [comment]
group and ungroup (with fat version)
![rect4471](https://cloud.githubusercontent.com/assets/1103897/16928091/777dc74a-4cf6-11e6-8d3d-fe11a1a641ea.png)

object
![object](https://cloud.githubusercontent.com/assets/1103897/16928093/7d17c9bc-4cf6-11e6-8e44-5bc9e508ef85.png)

let me know what you think

**Comment by akien-mga** [comment]
Where is the fat version meant to be used? I like a lot the non-fat version for group and ungroup, but the fat one is not so readable (especially the group one).

The object icon looks fine IMO.

**Comment by TheoXD** [comment]
Rather than making it look like a window on top of another window, can you try make two circles that are tangled? Should be easy to understand that it means some sort of "linking".

**Comment by akien-mga** [comment]
> Rather than making it look like a window on top of another window, can you try make two circles that are tangled? Should be easy to understand that it means some sort of "linking".

That would be intuitive yes, but the problem is that it might kind of conflict with the "Instance a scene" icon:
![spectacle ra4574](https://cloud.githubusercontent.com/assets/4701338/16929439/193420a2-4d38-11e6-9268-36d250b6b418.png)

**Comment by TheoXD** [comment]
@akien-mga, I meant something like this https://cdn4.iconfinder.com/data/icons/religion-6/53/two-circles-mark-religion-belief-256.png

**Comment by djrm** [comment]
its either the fat or not fat (not both), i agree i like the thin version better, but it wont look so good in editor as the fat version, since the base line size is 2px, it will also look kinda different to rest of the icons in the same toolbar

for instance:
![screenshot from 2016-07-18 15-16-30](https://cloud.githubusercontent.com/assets/1103897/16928914/d5bfcdfe-4cfa-11e6-989d-258f7a92f387.png)
(look worse in the actual editor)

i also did this one
![screenshot from 2016-07-18 15-40-49](https://cloud.githubusercontent.com/assets/1103897/16929583/0cd14842-4cfe-11e6-911d-d389fe3c1e35.png)

**Comment by TheoXD** [comment]
First one looks like "maximize" on windows, the one with circles looks definitely like "scene instance". Even the current one is less confusing compared to these.

**Comment by djrm** [comment]
this one is more related to the selection context, and it seems that is more widely used
![screenshot from 2016-07-18 16-16-12](https://cloud.githubusercontent.com/assets/1103897/16930701/0112e7fe-4d03-11e6-8663-556c9f8cc441.png)

also i dont think that the two tangled circles are a good option since i cant tell just by looking at the icon what it is suppose to do, is it the group action or the ungroup action (one of the two options needs a different icon)

**Comment by akien-mga** [comment]
The 2.0 icons used a nice trick to make it clear which one is the ungroup icon: it's crossed :)
![spectacle jd6672](https://cloud.githubusercontent.com/assets/4701338/16931157/ce7507ae-4d3f-11e6-95da-602bfc65ecaf.png)

**Comment by djrm** [comment]
I think the last one is the most intuitive, the function may not be grouping but its more related to selection (select the parent and its children as a whole), also it seems to be widely used
https://www.paintcodeapp.com/content/documentation/c_drawing/d_groups/groupungroup.png
http://4.bp.blogspot.com/-cOzu3g1n2SA/VGTQBNwI8PI/AAAAAAAABBA/9L-hiTnk7Bg/s1600/Selection_008.png
http://www.webcodeapp.com/images/groupungroup.png
https://support.content.office.net/en-us/media/924b7dfe-d59f-4922-b5d8-e995b240e4ac.png

**Comment by TheoXD** [comment]
@djrm , idea was that you can't move one without the other, but anyhow I like the most recent one too, plus it's widely used which makes it more recognizable.

**Comment by Zylann** [comment]
The new visibility icon looks more like a target than an eye now:
In 2.0: ![visibility_icon_2_0](https://cloud.githubusercontent.com/assets/1311555/16935601/1395affc-4d61-11e6-8105-c377bb046aa6.png), in 2.1: ![visibility_icon_2_1](https://cloud.githubusercontent.com/assets/1311555/16935612/2616c454-4d61-11e6-8600-7bebfd5036eb.png)

**Comment by hubbyist** [comment]
![](https://cloud.githubusercontent.com/assets/1103897/16930701/0112e7fe-4d03-11e6-8663-556c9f8cc441.png)

Using circles instead of squares for objects may make these more apparent.

**Comment by Zylann** [comment]
I don't understand this icon as well :s

**Comment by akien-mga** [comment]
Overall I think we're quite happy with the icon set, so closing.
