### ISSUE TITLE
Godot delay on scene launch

### ISSUE THREAD

**Issue by jcov28** [godotengine/godot#57560]
### Godot version

3.4.2

### System information

MacOS Big Sur, GLES3, INTL(R) HD Graphics 6000

### Issue description

There is a 3 second delay on all of my scenes when they are started before any of the operations I have programmed begin.

### Steps to reproduce

None

**Comment by Calinou** [comment]
@jcov28 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

Also, if you have a large project with complex autoloads, it's expected that the engine takes 3 seconds or more to start.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
