### ISSUE TITLE
Deep Copy / Duplicate for non-Nodes

### ISSUE THREAD

**Issue by supaiku0** [godotengine/godot#5770]
I asked the question here: https://godotengine.org/qa/6193/deep-copy-any-object
But there doesn't seem to be a straightforward way to create a [deep copy](https://en.wikipedia.org/wiki/Object_copying#Deep_copy) of any object.

It should be possible to create a copy of any object, by either providing a method like duplicate() or by having access to the constructor of a class through type information.

**Comment by Xrayez** [comment]
Me and @Calinou are still curious about this (recent question from #godotengine-devel):
```
<Calinou> can I clone an object in GDScript to return a new instance of the object? (a copy)
<Calinou> or do I need to make my class constructor accept the object to copy it?
```
I think this can be implemented using similarly to node duplication, but it would not touch: 
* DUPLICATE_GROUPS
* DUPLICATE_USE_INSTANCING

As it's only relevant for node duplication. So only properties, signals and scripts need to be cloned for an object.

**Comment by paulmiller** [comment]
related: https://github.com/godotengine/godot/issues/37162 - dictionary `duplicate(deep=true)` shallow-copies Objects

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
