### ISSUE TITLE
MeshInstance3D don't use the skeleton pose to calculate the AABB

### ISSUE THREAD

**Issue by fire** [godotengine/godot#57740]
### Godot version

4.0.dev (df1724470d1cff4f67aeb4c0d039114373aeb001)

### System information

popos 21.04 Linux, Vulkan, NVIDIA 3000 series

### Issue description

Selecting the AABB of the node of the skeleton, doesn't show the AABB of the pose of the skeleton.

The incorrect AABB of the skeleton and its meshes causes the whole mesh to disappear.
![editor_screenshot_2022-02-06T204938](https://user-images.githubusercontent.com/32321/152726908-0a5174be-4f3f-4418-b284-c351707cca70.png)

@lawnjelly was last in this area.

### Clue

Clicking on the skeleton pose editor arrow shows the correct AABB.

![image](https://user-images.githubusercontent.com/32321/152728496-a4a2db82-17ea-4627-a0a1-37f9a4d79c35.png)

### Steps to reproduce

1. Import this character
2. Set the hip bone to be posed vector3(10, 10, 10)
3. Click on the skeleton
4. Notice the ABBB does not include the posed vertices of the skeleton

### Minimal reproduction project
[AABB Game Project.zip](https://github.com/godotengine/godot/files/8012476/AABB.Game.Project.zip)

**Comment by fire** [comment]
When in the Skeleton3D pose editing mode looking away from the origin cases the mesh to disappear while clearly in the AABB volume.

![image](https://user-images.githubusercontent.com/32321/152728890-909b2eb3-85af-46a0-b8bb-64d824360a6c.png)

**Comment by lawnjelly** [comment]
Sorry I haven't done any work on skeleton AABBs or culling in 4.0.

**Comment by KoBeWi** [comment]
Is this still reproducible in alpha 9?
Not sure how to test this.

**Comment by fire** [comment]
It's a blocker for our project, I'll rename the title and add more reference information.

**Comment by raiseledwards810** [comment]
I can confirm this, it's a blocker for my project too, when the camera and the mesh are far from the origin only the meshes that are deformed by the skeleton seem to disappear.

**Comment by raiseledwards810** [comment]
I can confirm this, it's a blocker for my project too.

When the camera and the mesh are far from the origin (as far as I can tell) only the meshes that are deformed by the skeleton seem to disappear.

![image](https://user-images.githubusercontent.com/42452866/175616536-df6046ce-d010-4b23-bbe2-8a54e2992d64.png)

However the meshes that are only attached to bones but are not influenced remain visible.
Doesn't matter if the mesh has a material assigned or not.

Made a minimal reproduction project with the same results. The Orange Cheeto affected by the skeleton disappears when it is far from the origin.

![image](https://user-images.githubusercontent.com/42452866/175617295-4a35d66c-0199-435f-b4de-b19debcf7cdc.png)

![image](https://user-images.githubusercontent.com/42452866/175617232-c69814a3-d686-4b7f-afa8-11d61034192e.png)

I'm using **alpha 10**.

[Dummy Project.zip](https://github.com/godotengine/godot/files/8978969/Dummy.Project.zip)

**Comment by Calinou** [comment]
You can work this around by increasing **Extra Cull Margin** in the GeometryInstance3D section of the MeshInstance3D node.

**Comment by mhilbrunner** [comment]
Animation team wants to know if @clayjohn has an idea about the best way to solve it, as the obvious approach of just adding all bones seems hacky.

**Comment by clayjohn** [comment]
I think there is just an issue with the Node grabbing the appropriate AABB, the calculation is already done in the RenderingServer: https://github.com/godotengine/godot/blob/ba4bd7f00971a94c20d90e7d2c665d5eb0ae1b90/servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp#L616-L720

We loop through all the bone AABBs and create a larger AABB out of all of them. This should be enough to produce the AABB that fire gets when clicking on the skeleton bone editor. 

To me it seems the real issue is the node is using a different AABB for some reason. Perhaps it is using the mesh's AABB instead of the one with the.

Maybe this line here has something to do with it, the mesh's AABB is returned if the Skeleton hasn't changed since the last time this was calculated. Instead it should be caching and returning the calculated skeleton AABB https://github.com/godotengine/godot/blob/ba4bd7f00971a94c20d90e7d2c665d5eb0ae1b90/servers/rendering/renderer_rd/storage_rd/mesh_storage.cpp#L626-L628

**Comment by lawnjelly** [comment]
I know this is done differently in master than 3.x so I've been mostly staying out.. but a summary of the usual problems as I understand them:

The classic problem is a chicken egg problem, you want to calculate the animation / bones in order to calculate the AABB, in order to cull and decide whether to save processor and not calculate the animation / bones (+ render).

This is why in a lot of situations people just use an oversized AABB to try and cover the zone the character will move to and be done with it. Perhaps that in combination with some root motion to cover gross movements.

The other problem is if the calculation is done for the AABB in the rendering server and it is out of sync with the scene tree code, and either causes a stall or has a delay between updating the AABB scene side.

**Comment by clayjohn** [comment]
> Do you simply need to store `mesh->aabb` after calculating it at the bottom of that function? Or else store a specific "skeleton_aabb" and use that whenever the skeleton is valid.

I think so. It looks like mesh->aabb starts as the AABB of the first surface, then it is expanded by the next surface's AABB and bones. The end result I guess would be an AABB that cover's the t-pose of the character. Accordingly, it makes sense with the current approach to store mesh->aabb after calculating it. If the skeleton is invalid it never runs and the original mesh->aabb is always returned. 

> > edit2: Hmmm even if we get this working properly we will end up recomputing the AABB every time the skeleton is updated. I guess we need to precompute a larger AABB somehow
> 
> Maybe having both modes as options might be good (either recalculate AABB each frame, or use gross AABB). Recalculating the AABB each frame might not be that bad .. but the bigger expense might be recalculating the animation unnecessarily.

Yes, I think that would be ideal. I guess all we need to create some sort of editor tool to create a decent custom AABB as that gets used if it is non-zero.
