### ISSUE TITLE
Vulkan: GPU performance regression in `master` when using ProceduralSkyMaterial or PhysicalSkyMaterial

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#57928]
### Godot version

4.0.alpha (38c851a3f)

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 495.46)

### Issue description

Framerate is much lower since 5 days ago, having went from 1,700 FPS in an empty 3D scene to 170 FPS on my system. This affects both the Vulkan Clustered and Mobile backends.

I bisected this performance regression to 430d5d64aa33804668bb8414547103c563d59e49. cc @clayjohn 

This performance regression does not occur (noticeably) when using PanoramaSkyMaterial. It only happens when using ProceduralSkyMaterial or PhysicalSkyMaterial.

Most of the time is spent on the GPU:

![image](https://user-images.githubusercontent.com/180032/153471321-a0f741ac-08db-4b4b-ae5c-ef0a7429e222.png)

This does not occur in 9d1626b4d:

![image](https://user-images.githubusercontent.com/180032/153471384-bbb4e306-7041-40df-9851-3f0a579e987d.png)

### Steps to reproduce

- Create a new project and switch to the 3D editor.
- Enable **Perspective > View Frame Time** in the top-left corner of the 3D viewport.

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
It looks like I erroneously flipped the dirty flag to always be true while testing and never flipped it back
https://github.com/godotengine/godot/blob/38c851a3fa14983e60f74703fea2178d52358b92/servers/rendering/renderer_rd/renderer_scene_sky_rd.cpp#L1174-L1176

The fix is to change this to ``false``. It is very odd that I didn't notice the performance difference while testing!
