### ISSUE TITLE
`cubic_slerp()` may take a rotation path that is not the shortest

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#57951]
### Godot version

4.0.dev, 3.4

### System information

Any

### Issue description

#40592 split and resend. There is a problem with the implementation of `cubic_slerp()`, it may mix non-shortest paths in the calculation.

### Steps to reproduce

https://user-images.githubusercontent.com/61938263/180647818-b7c9550f-462b-430a-8966-96ccde165ea6.mp4

### Minimal reproduction project

[cubic_slerp_test.zip](https://github.com/godotengine/godot/files/9175808/cubic_slerp_test.zip)

**Comment by owstetra** [comment]
lerp causes this too

**Comment by TokageItLab** [comment]
@GNSS-Stylist https://github.com/TokageItLab/godot/commit/5cd3792e9a6a6820343112a5d04c8500d5516ac7

There is a problem that the way to interpolate each element of the quaternion directly is spherical-intererpotion, not spherical-linear-intererpotion. So I tried to adapt it to exponential map, which is probably the most common solution. Can you test it?

I think it does make the behavior more consistent. However, cubic-slerp flips the current quaternion when picking the shortest path and it does not match the pre and post sign, which causes strange kickbacks sometimes. I am trying to seek a way to improve it.

**Comment by TokageItLab** [comment]
Probably, flips will be done correctly by the literature referenced by @fire. See #58043.

**Comment by TokageItLab** [comment]
Repost from #58043:

For example, if we have [*a*, *b*, *-c*, *d*, *-e*], and the first interpolationA is [*a*, *-b*, *-c*, *d*], and the next interpolationB is [*b*, *c*, *d*, *-e*], then, the sign of the pre value of  interpolationB will change (because there is *b* in interpolationB, but it was *-b* in interpolationA), and the interpolation-curve will be broken. 

So, even if we use exp map, cubic_slerp() requires one of the following two things for sign consistency between pre and post.

- Determine and store the sign of all keys at the start of the animation
- We need to implement the values before_to = next_pre and before_post = next_to using a special case in the track cache to pass to the next section pre and post

Linear interpolation in Basis elements has major problems, and linear interpolation in Quaternion elements still has flip problems, so implementation in the track cache may be inevitable.

**Comment by fire** [comment]
@GNSS-Stylist 

We were able to get https://github.com/godotengine/godot/compare/master...V-Sekai:fix-cubic_slerp to work. There's still some acceleration problems though.

https://user-images.githubusercontent.com/32321/153880735-d33d9171-6535-4a42-906d-e1f5169fbe18.mov

https://user-images.githubusercontent.com/32321/153880743-a8167eff-d650-4ac3-8fd4-1411074627e3.mp4

**Comment by fire** [comment]
I think the reason is we're ignoring the term in the exp map paper.

![image](https://user-images.githubusercontent.com/32321/153881922-75ca917c-1904-4a00-b2b0-cdb6466f1cda.png)

http://number-none.com/product/Understanding%20Slerp,%20Then%20Not%20Using%20It/

https://www.cs.cmu.edu/~spiff/moedit99/expmap.pdf

**Comment by fire** [comment]
Update https://github.com/godotengine/godot/compare/master...V-Sekai:fix-cubic_slerp if @GNSS-Stylist wants to test.


https://user-images.githubusercontent.com/32321/154830947-d9ce3b81-5e9d-417c-bf13-670ee3fe90ca.mp4

**Comment by GNSS-Stylist** [comment]
Sorry for the late response, I was away from my keyboard for a week.

Made a comparison video between the code from @fire 's link (on the left) and my previous component-wise interpolation (on the right, code from https://github.com/godotengine/godot/issues/40592#issuecomment-1022127219 and previous comments there):

https://user-images.githubusercontent.com/50438441/154846802-ad8ba382-2feb-464e-9225-b45f5d68f19d.mp4

Paths seem to differ somewhat. The same flipping as seen on fire's video can be seen 00:25 onward. There are several glitches when the Z-axis (blue) of the the right-side thingy is close to the world's X-axis, about 1 min onward.

> Repost from #58043:
> 
> For example, if we have [_a_, _-b_, _c_, _-d_, _-e_], and the first interpolationA is [_a_, _Q_, _-b_, _c_], and the next interpolationB is [_b_, _Q_, _c_, _-d_], then, the sign of the pre value of interpolationB will change (because there is _b_ in interpolationB, but it was _-b_ in interpolationA), and the interpolation-curve will be broken.
> 
> So, even if we use exp map, cubic_slerp() requires one of the following two things for sign consistency between pre and post.
> 
>     * Determine and store the sign of all keys at the start of the animation
> 
>     * We need to implement the values before_to = next_pre and before_post = next_to using a special case in the track cache to pass to the next section pre and post
> 
> 
> Linear interpolation in Basis elements has major problems, and linear interpolation in Quaternion elements still has flip problems, so implementation in the track cache may be inevitable.

Pondered this for a while... As flipped quaternion represents the same orientation with the non-flipped one, shouldn't this work in any case without a cache or such? I mean does it actually matter which quaternions are flipped as long as they are adjusted to give the shortest path between subsequent ones? My brain refuses to understand the exp map right now, though (if the issue is related to it?).

Did some quick tests by flipping (negating all components) of a some quaternions in animation and this didn't change anything, apart from some minor rounding errors causing the center box to turn green/red instead of solid green by changing z-order just enough.

**Comment by TokageItLab** [comment]
Quaternions that are flipped in sign show the same orientation, but interpolation changes the values of those quaternions.
For example, the following two interpolations with weight 0.5 should be different.
```
Quaternion(2, 1, 4, 3).blend(Quaternion(1, -2, 3, -5)) = Quaternion(1.5, -0.5, 3.5, -1);
Quaternion(2, 1, 4, 3).blend(Quaternion(-1, 2, -3, 5)) = Quaternion(0.5, 1.5, 0.5, 4);
```

**Comment by fire** [comment]
@TokageItLab I noticed your animation scene has something wrong.

When I duplicated the track and set the path to be `gizmo2` I had different results.

[cubic_slerp_test_duplicate_track.zip](https://github.com/godotengine/godot/files/8383420/cubic_slerp_test_duplicate_track.zip)

**Comment by fire** [comment]
https://github.com/V-Sekai/godot/tree/fix-cubic-slerp

![image](https://user-images.githubusercontent.com/32321/160925596-a693c5b6-8080-462a-a8cd-7aa793b163c4.png)

![image](https://user-images.githubusercontent.com/32321/160925614-06bc2e5a-985f-49b5-a4b7-2c03296e307d.png)

**Before**

1. ret
2. ret - pre_a 
3. ret - p_b (error)
4. p_b - p_post_b (error) 


**After**

1. ret
2. ret - pre_a
3. p_b - ret
4. p_post_b - p_b

**Comment by TokageItLab** [comment]
Before:

https://user-images.githubusercontent.com/61938263/180647862-24e1afef-fa8e-4e84-b55d-ea93befd2f22.mp4

After #63380:

https://user-images.githubusercontent.com/61938263/180647865-6c55383b-5225-4e43-a697-0664a2dac065.mp4
