### ISSUE TITLE
Vulkan: Normal map mipmaps suffer from artifacts when VRAM compression is used

### ISSUE THREAD

**Issue by abaky** [godotengine/godot#57981]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

Material seems to very quickly and aggressively switch to lover res version of roughness texture, as a result you get pixelate roughness   

https://user-images.githubusercontent.com/9384421/153638408-afc4a1f0-4545-4283-ba84-2f5438458de2.mp4

In the video, I move the camera from super close up to 30 to 50 meters away from mesh plane.

### Steps to reproduce

Create ORMMaterail3D or StandardMaterial3D and put texture with packed AO, roughness and metalness in appropriate slots. Assign that material to mesh instance and up close it looks ok, but as soon as you move slightly away from mesh instance, the lover res version kicks in and pixelated effect starts to appear.

**Comment by abaky** [comment]
@Calinou changing compression on ORM texture to Lossless or/and disabling Screen Space Roughness Limiter does not seem to make a difference.

**Comment by abaky** [comment]
**[Minimal reproduction project](https://drive.google.com/file/d/1ffXJF2e26IJ-RXTr1WVdoCcVfw2LH9d2/view?usp=sharing)**

**Comment by Calinou** [comment]
This is actually linked to the **normal map**'s compression mode, not the ORM map's:

### Normal map set to VRAM Compressed

![2022-02-12_02 31 48](https://user-images.githubusercontent.com/180032/153691010-8bf7944c-27a3-4bf5-ae75-32cfa773e14c.png)

### Normal map set to Lossless

![2022-02-12_02 31 55](https://user-images.githubusercontent.com/180032/153691013-006479b2-68eb-418e-92f6-6a5d4799b58c.png)

**Comment by abaky** [comment]
Only changing compression from VRAM Compressed to VRAM Uncompressed already fixes the visual for me, I don't have to disable mipmaps.

**Comment by fire** [comment]
I'm at my computer now.

Try BPTC VRM compression. (BC7 compression).

**Comment by abaky** [comment]
In the project settings I enabled Bptc and disabled S3Tc, reimported normal map using VRAM Compressed and the artifacts are gone. If I leave S3Tc on then it still looks pixelated. When first enabling Bptc I got this error if that means enaything 

![snip](https://user-images.githubusercontent.com/9384421/153706627-7c5bcf8d-d456-47ca-b64f-8d65d3ba20eb.png)

**Comment by fire** [comment]
Here are some screenshots of my results.

![image](https://user-images.githubusercontent.com/32321/153709664-50df2b23-f0ad-4a8f-a774-11b83f8bd48b.png)


![image](https://user-images.githubusercontent.com/32321/153709628-a7160736-4c4a-49a5-9817-0f5784ab25e0.png)

![image](https://user-images.githubusercontent.com/32321/153709654-7313177b-5183-4d9f-bc78-308e7ae35d5a.png)

**Comment by abaky** [comment]
@fire  Ok, enabling Bptc in settings and enabling Bptc Ldr on imported normal texture and reimporting that texture, have fixed the visual pixilation for me.

**Comment by fire** [comment]
Are you still affected by this issue?

**Comment by abaky** [comment]
Sorry for late replay

Yes, in v4.0.alpha4.official [f47097973] I made a fresh project and the normal map still produces artifacts.

![editor_screenshot_2022-03-20T131738](https://user-images.githubusercontent.com/9384421/159161738-f35f6463-6810-4ee2-9496-545e2315c82d.png)

This is all set to default import vise. 

After I  enable BptcLdr and reimport textures the problems is gone. 

![editor_screenshot_2022-03-20T132337](https://user-images.githubusercontent.com/9384421/159161975-0046e776-8498-445b-9e42-865d3177ebb8.png)

**Comment by ModularNucleus** [comment]
I believe the issue I have is the same as this issue (or at least related).

The issue is visible banding ("stairstepping") in normal maps when imported with S3TC/RGTC (DXT5/BC5?) compression. Artifacts that to my albeit limited knowledge should be avoidable (see below). As I understand it, banding is a common issue with normal maps exported to 8-bit per channel images such as 8-bit PNGs. As Godot does not support 16-bit PNGs, a workaround is exporting to e.g. 16/32-bit OpenEXR and then dithering down to 8-bit PNGs. The dithering noise masks the banding. When importing to Godot this should then allow slighty noisy, but almost banding-free normal maps.
See e.g.: [https://polycount.com/discussion/148303/of-bit-depths-banding-and-normal-maps](https://polycount.com/discussion/148303/of-bit-depths-banding-and-normal-maps)

However, in my experiments I have been unable to achieve this when using S3TC compression. For reference, my authoring process is as follows:
- Blender: 1) Create bake image as 32bit float OpenEXR. 2) Bake normal map (from Multires) to image. 3) Change image "Color Space" to sRGB. 4) Export image as 32bit float, sRGB OpenEXR.
- GIMP: 1) Open image. 2) Reduce image precision to 8-bit and dither - e.g. with Floyd-Steinberg. 3) Export image as 8-bit PNG
- Godot: Import PNG with S3TC VRAM compression -> visible banding when using the normal map in StandardMaterial3D

As discussed, enabling BPTC compression and importing with BPTC Ldr enabled (BC7 compression) fixes the banding issue:

S3TC/RGTC (DXT5/BC5) - I assume this corresponds to Godot's image class' format Enum "FORMAT_RGTC_RG = 21"?
![S3TC - RGTC (DXT5 - BC5) compressed normal map](https://user-images.githubusercontent.com/91982860/178719828-160ef426-7664-4078-9c5a-da407999cf42.png)

BPTC (BC7) - I assume this corresponds to Godot's image class' format Enum "FORMAT_BPTC_RGBA = 22"?
![BPTC (BC7) compressed normal map](https://user-images.githubusercontent.com/91982860/178720194-d962e455-2c8c-459c-8726-e6876f76c06a.png)

Using BPTC / BC7 for importing normal maps is a viable solution, then. However, I still have a few caveats:
- Compression time is increased with BC7
- As I read it, according to e.g. Sebastian Aaltonen, BC5 should be able to compete in quality with BC7 for normal maps in most cases: [https://twitter.com/SebAaltonen/status/978736887627223040](https://twitter.com/SebAaltonen/status/978736887627223040)

My knowledge of normal maps and texture compression is very limited, but the question is whether Godot's RGTC / DXT5 compression is working as it should when compressing normal maps? I have included a simple MRP where the normal map has been imported with both S3TC and BPTC (Ldr enabled):
[Normal map compression.zip](https://github.com/godotengine/godot/files/9101812/Normal.map.compression.zip)

**Comment by Calinou** [comment]
I can still reproduce this with [this MRP](https://github.com/godotengine/godot/issues/57981#issuecomment-1036908070) on 4.1.dev 9b9bb418c after removing the `.godot/` folder and reimporting all resources:

![image](https://user-images.githubusercontent.com/180032/224577318-2dc51f56-f1ba-4115-b180-3264d7bc420b.png)

**Comment by AlexHCC** [comment]
I get the same visual artifact regardless of texture compression or mipmaps, and I haven't found a way to fix it.

![image](https://github.com/godotengine/godot/assets/28542484/dde66d34-bb9d-4602-9e5c-af7aa193cc5e)

[Here](https://www.reddit.com/r/godot/comments/14fwfzd/how_do_i_increase_the_resolution_of_the_lighting/) is a forum post I've found online that describes the same issue.

I think this is a major issue since it breaks all normal maps, and the only way to fix it is to remove them.
The bug persists in 4.1 betas.

**Comment by fire** [comment]
Are we using sufficiently high quality vram compression for normal maps? Like BPTC or ASTC?

**Comment by clayjohn** [comment]
Current best workaround is to change compression to Basis Universal instead of VRAM compressed. Both options ultimately use the same compression format (DXT5_RA_AS_RG), but using Basis Universal outputs correct results.

**Comment by Saul2022** [comment]
> Current best workaround is to change compression to Basis Universal instead of VRAM compressed. I can confirm that in 4.1 rc2, BasisU gives better results than vram compression deleting most white artifacts when you are far but worse than lossy.
![editor_screenshot_2023-07-04T104632](https://github.com/godotengine/godot/assets/97898580/ac31e87b-1464-41bc-85cb-7f91bbb18cb4)
![editor_screenshot_2023-07-04T104736](https://github.com/godotengine/godot/assets/97898580/f61360f4-6f48-4028-ad35-fdcf7367ace0)
![editor_screenshot_2023-07-04T104814](https://github.com/godotengine/godot/assets/97898580/ec50a78c-aa2c-4725-bddd-697aac9903ae)

**Comment by npip99** [comment]
I'd like to add here that this doesn't appear to be specific to Normal map mipmaps. This pixelation issue occurs on every Sampler2D.

![image](https://github.com/godotengine/godot/assets/8939474/1376d2cf-0381-4fae-83ac-3f6885158282)

Currently, heightmaps usage in procedural geometry vertex shaders are completely broken when using compressed VRAM, it destroys the procedural geometry with the artifacts as vertices alternate between up / down / up / down / up due to the dithering pattern, rather than staying smooth. Heightmaps PNGs are often huge and smooth, and should lend themselves to compression very well.

**Comment by Calinou** [comment]
This is expected with VRAM compression, which can't render smooth gradients by design (it works with 4×4 macroblocks). Use lossless compression when you need smooth heightmaps instead.

**Comment by npip99** [comment]
> Use lossless compression when you need smooth heightmaps instead, or for pixel art textures in general.

I'll note for anyone else that might be on this thread (In response to lossless compression):

VRAM Compression with "High Quality" (BPTC) looks virtually identical to the original image (Lossless), and uses 33.3% of the VRAM. Checking with the color picker, the RGBs appear unmanipulated.

When "normal map" is set to "enable", both low quality (DXT5_RG_AS_RA) and "High Quality" (BPTC) use 33.33% of the VRAM of a lossless image, so "High Quality" appears to come at no cost.

**Comment by npip99** [comment]
I believe this issue specifically has to do with the RA_AS_RG transformation, involving mipmap generation.

![image](https://github.com/godotengine/godot/assets/8939474/27226b85-aa51-459d-909f-9b7a1216bb67)

A huge percentage of the mipmap becomes set to "1.0", for no clear reason (I'll call this 1.0 area the "glitched" area). The glitches happen in a pixelated format, but the pixels are much larger than the underlying resolution (You can see the higher resolution by the tiny pixels in the un-glitched regions). In specific, it's observed that the glitched pixels are 4x4 "true" pixels.

Another property is that _only_ the "x" coordinate of the normalmap is glitched. The "y" coordinate is unaffected and generates correctly.

![image](https://github.com/godotengine/godot/assets/8939474/71b1612f-1269-492b-a1b0-1d075bdd895e)

The shader code to generate the two images is here:

```// NOTE: Shader automatically converted from Godot Engine 4.1.3.stable's ORMMaterial3D.

shader_type spatial;
render_mode blend_mix,depth_draw_opaque,cull_back,diffuse_burley,specular_schlick_ggx;

uniform sampler2D texture_normal : filter_nearest_mipmap,repeat_enable;

void fragment() {
	vec2 base_uv = UV;
	ROUGHNESS = 1.0;
	METALLIC = 0.0;
	vec3 normal_map = textureLod(texture_normal,base_uv,3.0).rgb;
	normal_map = 2.0*normal_map-1.0;
	normal_map.z = sqrt(max(0.0, 1.0 - dot(normal_map.xy, normal_map.xy)));
	
	bool SHOW_GLITCH = true;
	if (SHOW_GLITCH) {
		ALBEDO = vec3(clamp((20.0*normal_map.x+1.0)/2.0, 0, 1), 0, 0);
	} else {
		ALBEDO = vec3(clamp((20.0*normal_map.y+1.0)/2.0, 0, 1), 0, 0);
	}
}
```

**Comment by fire** [comment]
Now that astc and bptc are in, we could default to "high quality" for normal maps since there is significant loss in the current dxt and etc2 usages.

**Comment by BlueCube3310** [comment]
I may be wrong about this, but <a href=https://www.khronos.org/opengl/wiki/Red_Green_Texture_Compression>DXT5 compression differs from RGTC_RG</a> as with the latter the red and green channels are interpreted as DXT5's alpha channel, which results in significantly higher quality at the cost of data size, while DXT5 compresses the RGB channels in a similar way to DXT1, so the quality is generally lower. 

After analyzing the texture compression code, it seems that Godot converts the RG normal map into an RGBA texture <a href=https://github.com/godotengine/godot/blob/7233bc6736e6a9e12758a52402660f9a3a892a78/core/io/image.cpp#L3877>(with the B and A channels set to 0)</a>, and <a href=https://github.com/godotengine/godot/blob/7233bc6736e6a9e12758a52402660f9a3a892a78/modules/etcpak/image_compress_etcpak.cpp#L231C4-L231C4>compresses it to the DXT5 format</a>, which results in visible artifacts due to the algorithm's lack of precision.

**Comment by npip99** [comment]
Just current status on this issue as a result of the most recent PR (Woot! Checked it out and it fixes it nicely):

I'm not sure if that PR should close this issue, because FORMAT_DXT5_RA_AS_RG is still in the codebase and has broken mipmaps. Unless the plan is to remove FORMAT_DXT5_RA_AS_RG (Perhaps we still keep this issue open until that's done?).

I don't believe this issue is because of quantization artifacts, I think somewhere the implementation of FORMAT_DXT5_RA_AS_RG has a bug (Gave some LOC regions that might be where it is?).

Reasoning:
- In the example I showed above a very high percentage of the image just becomes set to "1.0"; it's not merely low quality, but completely incorrect, over half the image gets set to exactly "1.0" even if the original image is dark / close to "0.0". Additionally, it only happens at mipmap levels, so it's not an issue of RA_AS_RG's ability to hold the data itself, but rather specifically an issue related to generating mipmaps. It's exactly the 4x4 sections that are set to "1.0" that come out as the ugly pixelations in the wood example, the other 4x4 sections are fine.

----

Maybe we rename this issue to "FORMAT_DXT5_RA_AS_RG garbles R-channel in mipmaps", since the issue is no longer Normal Map's default mipmap setting.

Currently https://docs.godotengine.org/en/stable/classes/class_image.html#enum-image-format has no info on RA_AS_RG, would be clean to mention "R channel is garbled" / "Deprecated" / or what the plan is etc.

**Comment by BlueCube3310** [comment]
> Additionally, it only happens at mipmap levels, so it's not an issue of RA_AS_RG's ability to hold the data itself

It still happens to images without mipmaps, just less noticeably:
| VRAM Compressed | Basis Universal |
|---------------------|-----------------|
|<img width="785" alt="raasrg" src="https://github.com/godotengine/godot/assets/53150244/30c74996-637a-46a0-86a6-36947ab434b0">|<img width="526" alt="basisu" src="https://github.com/godotengine/godot/assets/53150244/38c01efa-317a-447e-aff5-bda33e9cbb2a"> |

> FORMAT_DXT5_RA_AS_RG is still in the codebase and has broken mipmaps. Unless the plan is to remove FORMAT_DXT5_RA_AS_RG

BasisUniversal still uses the same format (`DXT5_RA-As-RG`), yet it doesn't exhibit the artifacts. The conversion from RG to RA is handled the same way there as it is with `etcpak`. 
The artifacting also happens with VRAM Compressed `ETC2_RA_As_RG`, so the issue is likely due to `etcpak` lacking accuracy in favor of fast compression speed.
