### ISSUE TITLE
Godot 4: adding Visual Script's Call node will crash the engine

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58036]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

Adding Visual Script's Call node will crash the engine, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/153732059-4c170be4-3c72-49e5-93f7-fc52e38d4a73.mp4

I expect to get the node and the engine doesn't crash.

### Steps to reproduce

1. Adding Visual Script's Call node.
2. The engine will crash.

**Comment by fire-forge** [comment]
I can't be sure, but this might happen because there's no EditorProperty class for Callable. Selecting Callable in the array and dictionary editors in the inspector crashes it as well which I why I think that.

The next PR I'm going to make is adding EditorProperties for Callable and Signal, so I'll check if this is fixed after doing that.
