### ISSUE TITLE
NavigationMesh is not being generated at all for HTML5 games

### ISSUE THREAD

**Issue by SlothDevLlama** [godotengine/godot#58098]
### Godot version

3.5.beta1.mono

### System information

Windows 10, GLES2

### Issue description

When generating a NavigationMesh by using the `bake_navigation_mesh` function at runtime, the navigation mesh won't be generated at all for HTML5 games. Desktop works fine tho.

When running the minimal project as desktop application it immediately prints "baking done" and you can see the navmesh when debug navigation is toggled. In browser it will never print "baking done".
Prebaked navigation meshes are visible as intended.

### Steps to reproduce

Just run the minimal reproduction project, it should show the issue clearly

### Minimal reproduction project

[MinimalProjectHTML5Navigation.zip](https://github.com/godotengine/godot/files/8061861/MinimalProjectHTML5Navigation.zip)

**Comment by Scony** [comment]
@Spowmtom this issue is for `3.x`.
@SlothDevLlama currently runtime baking happens on a separate thread so you need to export your HTML5 project with threading support: https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads

Btw. @SlothDevLlama please don't close this issue - we either need to document baking better or introduce some runtime switch taking threading support into account

**Comment by SlothDevLlama** [comment]
@Scony is there for the version I'm using (3.5.beta1.mono) an issue when installing the export template? Since it seems to not beiung able to install the template :-/
