### ISSUE TITLE
Have Capsule Collider Vertical By Default

### ISSUE THREAD

**Issue by toliaferrode** [godotengine/godot#5813]
**Operating system or device - Godot version:**
Any OS, any Godot version

**Issue description** (what happened, and what was expected):
As it is now when testing I have to rotate the capsule collider 90 degrees on the X axis before I can use it. At first I thought it was just weird and I was using it wrong (keeping it horizontal), but that makes collisions act strangely. The capsule collider icon in the inspector shows an upright, vertical capsule so it's confusing.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Are there more use cases for it being vertical than horizontal? The icon is just an icon, representing a capsule shape, it does not mean that the resulting object will have the exact same orientation as the icon used to represent it :D

**Comment by toliaferrode** [comment]
It was so confusing for me that it took me awhile to learn how to use it.

Being able to get right into prototyping a character controller without having to rotate your collider is a big workflow improvement. Also I feel like the orientation should be representative of the icon, too, because it shows you what you're going to get ideally. 

I'm not going to say Godot should because Unity does, but I think it makes a lot of sense because people will be using it for their character controllers. If I had trouble with it, I think more people will too.

**Comment by vnen** [comment]
:+1: A vertical capsule sounds more sensible to me. I'm worried that this might break compatibility though.

**Comment by toliaferrode** [comment]
Maybe we could have it for 3.x?

**Comment by aaronfranke** [comment]
This is also a problem for Capsule Meshes. They are lopsided by default, aligning along the Z axis.

![capsule](https://user-images.githubusercontent.com/1646875/35017974-0ca3d8a8-fae5-11e7-9fdc-244bacf81093.png)

Worth mentioning also that Cylinders are unaffected. They are correctly oriented at 0,0,0 rotation.

**Comment by AndreaCatania** [comment]
Hmm the main problem of changing it is that all the current existing project became wrong... I can imagine a lot of people that open issue about capsule shape that behave corrupted... I don't think that we need to change it because I see no real improvement. But if it makes understanding simple for most part of community I'm fine to change it... Also should be changed the orientation of capsule mesh

**Comment by aaronfranke** [comment]
The most common use case for capsules is vertical, for most projects the fix is as simple as changing the rotation to (0,0,0). We should fix capsules now, for the benefit of future projects.

**Comment by Calinou** [comment]
Such compatibility breakage is likely acceptable in minor release (such as 3.1), but probably not in a patch release (such as 3.0.3).

**Comment by leiget** [comment]
It would be a minor compatibility breakage for something that is most likely always used vertically (for characters).

**Comment by TheYokai** [comment]
I'm not sure if there's a perfect way to get around compatibility, but I agree that vertical seems like the most logical starting orientation.

**Comment by aaronfranke** [comment]
@TheYokai I'd prefer incompatibility to hacky or bad solutions.

**Comment by TheYokai** [comment]
@aaronfranke same, especially since incompatibility can easily be resolved on the user end (when upgrading between engine versions, some minor changes like this are to be expected.)

**Comment by kenneth-leblanc** [comment]
My personal thoughts on compatibility are to break it so long as two conditions are met:
1. The change is correcting a bug. I consider changes that align the engine with what would be the most common use case a bug.
2. The fix after the compatibility is broken is straightforward. 

If it matches those two criteria, I always support breaking compatibility. I will admit, maybe it should wait for a major subversion change. 3.1 for instance rather than break a ton of minor things between 3.0.2 and 3.0.3. I created an issue that has a similar sort of effect. #18250 I hope it gets changed rather than pushed off because it breaks compatibility.

**Comment by AndreaCatania** [comment]
I want to point out that this is not a bug

**Comment by BastiaanOlij** [comment]
The thing to keep in mind here is that there are legions of people out there who have got existing games that have already rotated the capsule the way they want it. 
When I added the capsule mesh this discussion also flared up with the same concerns raised and we decided to align the capsule mesh with the capsule collision shape.

For you it is a simple 90 degree rotation of the capsule which you do in 1 second.

For everyone else with existing projects its breaking their game in unexpected ways, finding this out when their players start complaining because they weren't aware the default orientation has changed, and then spending the next couple of hours finding every place where they use a capsule, where they may have code that does something with that capsule, etc. to work around the fact that the orientation has changed, not to mention having to put code in to switch the orientation if they are currently releasing their game on 3.0 but plan to switch development to 3.1 in the near future.

**Comment by JarLowrey** [comment]
Can we get a 4.0 milestone assigned on this so it's not forgotten again - a minor break in compatibility during a major semver update?

**Comment by Megalomaniak** [comment]
> I want to point out that this is not a bug

this is 100% a _design bug_. The bug is in flawed UX design. But since it is compatibility breaking it was 100% the right choice to wait for 3.1. This **should** be fixed for 3.1 however.

**Comment by aaronfranke** [comment]
https://github.com/godotengine/godot/issues?q=milestone%3A4.0

**Comment by KoBeWi** [comment]
> For everyone else with existing projects its breaking their game in unexpected ways, finding this out when their players start complaining because they weren't aware the default orientation has changed

Compatibility breakages are always listed in release notes, so it's up to developer to read it. Players are unaffected as long as they play a build of the game, not the source.
