### ISSUE TITLE
Godot 4: transform node (3D) is missing from the Visual Script's property selector

### ISSUE THREAD

**Issue by kreaninw** [godotengine/godot#58228]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 11, Vulkan Clustered, Intel UHD Graphics 620 v30.0.101.1340

### Issue description

The transform node (3D) is missing from the Visual Script's property selector. The users have to search this node from the add node window. This issue is shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/154407223-885caa31-fd1e-4973-beeb-25072fadee59.mp4

This issue is a regression from Godot 3.4. In Godot 3.4, the transform node (3D) is presented in the Visual Script's property selector, as shown in the screen recording below:

https://user-images.githubusercontent.com/1403194/154407433-f480741b-876a-46e6-a724-b84d4b6d6c96.mp4

I expect the transform node (3D) to be presented in the Visual Script's property selector. 

Note: It seems this issue is not fixed by [merged PR #56252](https://github.com/godotengine/godot/pull/56252).

### Steps to reproduce

1. Attach Visual Script to Node3D.
2. Add a **get** node in Visual Script.
3. At the property selector in the inspector tab, search for the **transform** node. You won't find the transform node.

**Comment by megalobyte** [comment]
I was able to trace the issue to d03b7fbe090dca1f9ea4190116ac0efbee37e929. 

I think there are two possible fixes, but I don't know which is the right approach: 
1. I think `PROPERTY_USAGE_NO_EDITOR` should be added to the  property selector, but it seems weird that `PROPERTY_USAGE_NO_EDITOR` and `PROPERTY_USAGE_EDITOR` would both be valid cases 
https://github.com/godotengine/godot/blob/3a008fc1a2fcd02ddd7c47a2d3535f54ceebd435/editor/property_selector.cpp#L180-L182
2. Or update the property flag in node_3d.cpp from `PROPERTY_USAGE_NO_EDITOR` to ...something else 
https://github.com/godotengine/godot/blob/3a008fc1a2fcd02ddd7c47a2d3535f54ceebd435/scene/3d/node_3d.cpp#L990 
 
Completely removing the flag is not an option, because then the transform will appear in the editor inspector.

**Comment by KoBeWi** [comment]
VisualScript was removed in Godot 4.0, so closing.
