### ISSUE TITLE
It is not possible to add inherited scenes into Godot 4 TileSet Scene Collection

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#58349]
### Godot version

v4.0.alpha2.official [79077e6c1]

### System information

Windows 10

### Issue description

When using node inheritance, and attempting to add an inherited scene to TileSet's Scene Collection, an error is raised :

`Invalid PackedScene for TileSetScenesCollectionSource: res://child.tscn. Root node should extend Control or Node2D.`

Even if the root scene is Node2D in the base scene.

Are inherited scenes unsupported, or is this a bug?

### Steps to reproduce

1. Create a scene with Node2D as root.
2. Create another scene, that inherits from the first scene.
3. Drag the second scene into a TileSet's Scene Collection
4. An error is printed into the output, and the TileSet now contains an invalid entry: "Tile with Invalid Scene"

**Comment by Cowa** [comment]
I encountered the same bug.
I found the origin while exploring the code but I have no idea how to solve it.

From `set_scene_tile_scene` the call to `get_node_type(0)` returns an empty string:

https://github.com/godotengine/godot/blob/master/scene/resources/tile_set.cpp#L4551

Because `SceneState::get_node_type` returns an empty string when it's an instanced type:

https://github.com/godotengine/godot/blob/master/scene/resources/packed_scene.cpp#L1302-L1304

So `ClassDB::is_parent_class(type, "Control") || ClassDB::is_parent_class(type, "Node2D")` will always be false

**Comment by B-l-u-e-f-i-r-e** [comment]
Any Updates?

**Comment by GibionMillak** [comment]
Godot 4.14 is still like this...

**Comment by Calinou** [comment]
cc @groud

**Comment by lumpiasallad** [comment]
Explanation:

    TileSetScenesCollectionSource is used to add scenes as tiles (like buildings, props, etc.) in a TileMap.

    These scenes must be visual, so their root node needs to be a type that extends CanvasItem (like Node2D, Sprite2D, AnimatedSprite2D, etc.).

    Node is just a generic, non-visual node, so it doesn't work for this purpose.

Solution

    Open res://child.tscn in the Godot editor.

    Select the root node.

    Change its type to something that extends CanvasItem, typically:

        Node2D (if it’s a regular 2D scene),

        or Sprite2D / StaticBody2D / etc., depending on what you’re using.

    You can right-click the root node → Change Type → choose Node2D.
