### ISSUE TITLE
Internal Script Error! - opcode #31 instancing a subclass from a preloaded script

### ISSUE THREAD

**Issue by supaiku0** [godotengine/godot#5843]
**Operating system or device - Godot version:**
Arch Linux - b623acb718c50b86219027e0f6f7bebd11d96909

**Steps to reproduce:**
I created a sample project which triggers the error. The classes are intended to not make any sense.

**Link to minimal example project**

[opcode13.tar.gz](https://github.com/godotengine/godot/files/376702/opcode13.tar.gz)

**Note**
I _think_ this may be related to https://github.com/godotengine/godot/issues/5726

**Comment by bojidar-bg** [comment]
Note that moving the `const Cow = preload("Cow.gd")` into the subclass makes it work:
````gdscript
# Moved below
#const Cow = preload("Cow.gd")
class Class1:
	func _init():
		pass

class Class2 extends Class1:
	const Cow = preload("Cow.gd") # Here
	func getMoo():
		return Cow.new()
````

**Comment by bojidar-bg** [comment]
I think I found the core of the issue:
* The GDScript compiler returns a reference to a super class's constant at [gd_compiler.cpp:199](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_compiler.cpp#L199) (through [:230](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_compiler.cpp#L230) and the while loop)
* The super GDScript gets unreferenced (since it was referenced through `const Class2 = preload("A.gd").Class2`, and A.gd is useless from now on)
* It clears the `_owner` pointer in subclasses at [gd_script.cpp:966](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_script.cpp#L966)
* Finally, GDFunction fails to find the said constant at [gd_function:50](https://github.com/godotengine/godot/blob/master/modules/gdscript/gd_function.cpp#L50)
* ...And proceeds to blame the compiler :smile: 

@reduz I guess `_owner` should be make into a `Ref<>` or something of that sort?

**Comment by bojidar-bg** [comment]
Ok, seems like the only plausible version of what I want to do would be if I duplicate the constants among subclasses, since if I add a Ref to the owner, it becomes a cyclical reference (since it is also referred to by the constants of the owner script).

So, I guess that's out of my reach...

**Comment by akien-mga** [comment]
Is this still valid in the current master branch?

**Comment by bojidar-bg** [comment]
Yes, still valid under similar conditions. Reported "Invalid opcode `#31`" here, though.

**Comment by akien-mga** [comment]
Updated title for new opcode number and some more details on the actual symptom. See duplicate #21591 for a recent reproducer.

**Comment by dennmat** [comment]
Ah, not sure how I missed this... Sorry for the duplicate.

Still fairly new to GDScript and Godot but I'll throw in this in case it is useful:
`var B = load('...').B` results in the same error. (From the example in ticket #21591)

**Comment by vnen** [comment]
I forgot about @bojidar-bg's comment explaining the cause, and proceeded to reach the same conclusion xD

I don't really know how to solve it without creating a reference cycle. We'll need a help from @reduz to solve this.

**Comment by adabru** [comment]
Hi, got the same error with Godot 3.0.6-1. I think it would help if the error message in the editor could be more specific.

For the googling folks:

```
Internal Script Error! - opcode #31 (report please).
Internal Script Error! - opcode #18 (report please).

0:00:00:0251 - GDScriptCompiler bug...
----------
Type:Error
Description: GDScriptCompiler bug...
Time: 0:00:00:0251
C Error: Method/Function Failed, returning: __null
C Source: modules/gdscript/gdscript_function.cpp:90
C Function: _get_variant
```

**Comment by nathanfranke** [comment]
Still reproducible in GDScript 2.0 (6f4384f20) with extremely specific circumstances...

<details>

<summary>Reproduction Description</summary>
<p>

`World.tscn` - Empty Scene
`TestWorld.tscn` - Inherits `World.tscn`, attached `TestWorld.gd`

`TestWorld.gd`:  
```py
extends Node

func _ready():
	Player.new().init_resources()

```

`Player.gd`:  
```py
class_name Player

var resources := []
func init_resources(a := 0.0, b := 0.0) -> void:
	resources.append(Metal.new(b))

```

`GameResource.gd`:  
```py
extends Node
class_name GameResource

func _init(amount := 0.0):
	pass

```

`Metal.gd`:  
```py
extends GameResource
class_name Metal
```
</p>
</details>

[wtf.zip](https://github.com/godotengine/godot/files/5231087/wtf.zip)

To demonstrate the almost absurd sensitivity of this bug, try removing the `a` parameter from `init_resources`. Even though it is never referenced, redefined, or used in any way, it causes the bug to no longer occur.
