### ISSUE TITLE
Show progress hint in the task bar

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#5844]
As stated in https://github.com/godotengine/godot/pull/5560#issuecomment-231595959

![output](https://cloud.githubusercontent.com/assets/5599796/17034435/11257848-4f59-11e6-9fd7-9ea40a682628.gif)

I was able to make this work on Windows. For OSX there's [NSProgressIndicator](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSProgressIndicator_Class).

What I'm not sure is what should be the API for this though. I want to be able to set a `ProgressBar` or `TextureProgress` as "default" and make that show in the hint. Still, there's a need to enable/disable the hint at some point, as the OS API doesn't handle that automatically.

For Windows there's also error and pause states, I'm not sure if other OSes can handle that.

**Comment by Calinou** [comment]
**Bugsquad note:** This issue is still relevant as of https://github.com/godotengine/godot/commit/a1f835df771464e9db6909fd104751ccbbc1b91a.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
