### ISSUE TITLE
Godot 4: Need to press "Directory Up" button twice in path with slash at the end

### ISSUE THREAD

**Issue by Akylzhan** [godotengine/godot#58504]
### Godot version

4.0 dev

### System information

pop-os 5.15.15, Vulkan

### Issue description

As the title says, if you go to any favorite folder in EditorFileDialog and press Directory Up button it does nothing, but removes `/` in path. Same happens if you copy and paste the path with `/` at the end. Would be nice if there was no need to press button twice

### Steps to reproduce

.

**Comment by Akylzhan** [comment]
If it's OK, I can work on this.

**Comment by Calinou** [comment]
> If it's OK, I can work on this.

Sure, feel free to open a pull request for this :slightly_smiling_face:

**Comment by Alex2782** [comment]
@akien-mga 
This problem is probably already fixed. https://github.com/godotengine/godot/pull/80821

At first I also wanted to adjust the function `String::get_base_dir()` as in this PR: https://github.com/godotengine/godot/pull/58508 (Label `needs work`)
But the effects on other functions were not clear to me.

**Comment by akien-mga** [comment]
Fixed by #80821.
