### ISSUE TITLE
PitchShift audio bus effect cannot be dynamically changed

### ISSUE THREAD

**Issue by DavidJVitale** [godotengine/godot#58647]
### Godot version

3.4.3 stable

### System information

Ubuntu 20.04.3 LTS

### Issue description

When the `PitchShift` effect is added to any audio bus, it works well ONLY if the `pitch_scale` value does not change. If I change the value every frame dynamically, the audio will NOT play during the frames that the value has changed. See example project.

I believe this bug was not present in earlier versions of Godot -- I have been working on a project through many versions, and haven't touched my audio code in many months. It used to slide through the various pitches. Now it cuts out. I have noticed it on my linux PC, as well as on an exported Android phone.

### Steps to reproduce

See example project. The audio plays fine while the `pitch_scale` is an unchanging `1`

If some code increment the `pitch_scale` each frame, the audio stops playing for all frames that the pitch scale is changed

When it reaches `1.5` and stays there, the audio continues to play at the new pitch.

### Minimal reproduction project

[AudioPitchBug.zip](https://github.com/godotengine/godot/files/8158614/AudioPitchBug.zip)

**Comment by Calinou** [comment]
@Listwon is working on fixing this, see https://github.com/godotengine/godot/pull/57985.

**Comment by ellenhp** [comment]
Akien's usually good about cherry-picking stuff like this into 3.x. :) I think this bug made it into 3.4.3 but iirc 3.5 hasn't been released yet so #58668 will almost certainly be picked into that. My guess is it'll be fixed in the next 4.0 alpha, next patch release of 3.4.x series and 3.5 when that comes out.

@akien-mga Considering this was an enhancement it might have made sense to not pick it into 3.4 and instead wait until 3.5? I remember there was some backlash about the ill-fated 3.2.4 release about exactly this kind of thing. Really the regression is on me though because I remember checking my email and telling myself "I should go object to those changes" without even looking at the details of the PR but I got overwhelmed with work like I always do so it slipped through.

**Comment by akien-mga** [comment]
@ellenhp Well it was described as fixing something that users have repeatedly reported as a bug over the years. But yeah the line between bugfixnsnd enhancement can be thin and subjective.

**Comment by DavidJVitale** [comment]
Thank you all for the quick turnaround on this. Just wanted to add that `3.4.4` fixed this issue for me!
