### ISSUE TITLE
Camera3D looks backwards

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#5865]
I noticed the Camera3D node actually looks towards -Z, which is backwards. Is there a reason for it or is it a bug?

**Comment by reduz** [comment]
OpenGL convention

**Comment by Zylann** [comment]
Yeah actually I see all 3D nodes use a coordinate system where Z is backwards (so if you look towards +Z, the X axis goes left instead of right). I was used to Z-forward X-right coordinate systems until now, so I got a bit confused :p

**Comment by akien-mga** [comment]
Would be nice to get this mentioned in the documentation, as well as the reason for having the Y axis pointing downwards in 2D. It's a question that comes around quite often from power mathematicians who get frustrated that the system of their high school years is upside down :p

**Comment by Zylann** [comment]
In 2D it kinda makes sense because it mimics the screen's coordinate system and way of writing text, but in 3D that's the first time I see this system deeply used. Even on my early OpenGL programming days I wanted to have Z forward and X on the right just because it was easier to wrap my head around it, and it didn't needed to negate `basis.z` as an exception to get the forward vector.

**Comment by reduz** [comment]
Z-Forward and X on the right is the DirectX convention, most engines come
from there.
Godot was created in OpenGL, so it uses the OpenGL convention

**Comment by CowThing** [comment]
I am still not clear what "forward" is meant to be in 3D in Godot. The camera faces negative Z, and using `look_at()` will rotate the node to look at the target with negative Z, so from this it seems negative Z is meant to be forward. But when importing a model it will face towards positive Z, and pressing numpad 1 in the editor to enter "front" view will correctly face the front of those imported models, so from this it seems positive Z is meant to be forward.

**Comment by reduz** [comment]
Yes, it's the OpenGL convention. We didn't invent anything new.

On Feb 4, 2018 03:09, "CowThing" <notifications@github.com> wrote:

I am still not clear what "forward" is meant to be in 3D in Godot. The
camera faces negative Z, and using look_at() will rotate the node to look
at the target with negative Z, so from this it seems negative Z is meant to
be forward. But when importing a model it will face towards positive Z, and
pressing numpad 1 in the editor to enter "front" view will correctly face
the front of those imported models, so from this it seems positive Z is
meant to be forward.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/5865#issuecomment-362874085>,
or mute the thread

**Comment by akien-mga** [comment]
> I am still not clear what "forward" is meant to be in 3D in Godot. The camera faces negative Z, and using look_at() will rotate the node to look at the target with negative Z, so from this it seems negative Z is meant to be forward. But when importing a model it will face towards positive Z, and pressing numpad 1 in the editor to enter "front" view will correctly face the front of those imported models, so from this it seems positive Z is meant to be forward.

Typically in a 3D game "forward" and "front" are opposed directions. "Forward" means that when you press the button to go forward, the character will move "away" from the screen/player (so in Godot on Z- as per OpenGL convention). In a third person game you would typically then see the back of your character. "Front" means that the character is facing the player/screen, and thus looking at Z+ in Godot.

Seems consistent to me.

**Comment by Chaosus** [comment]
I think this misunderstanding is fixed by http://docs.godotengine.org/en/latest/tutorials/3d/using_transforms.html
_Closed by bugsquad._
