### ISSUE TITLE
Issues with Physics and Y-Sorting at large coordinates / node positions

### ISSUE THREAD

**Issue by Matti1903** [godotengine/godot#58664]
### Godot version

3.4.3

### System information

Windows 11

### Issue description

Currently I'm working on an openworld game, where due to the large game world, it can happen that the position of the player becomes very high. I noticed that there are problems with the physics and the Y-sorting at such large positions.

If the position of the a Node gets too high, the node gets stuck at collisionshapes and the Y-Sort seems not to work anymore (nodes that should be behind others, appears on top of others in a flickering pattern)

Low position:

https://user-images.githubusercontent.com/82829772/156253741-990ab4a0-78bf-4474-832a-142d7d327548.mp4

High position (x=2783488 and y=2783488):

https://user-images.githubusercontent.com/82829772/156254488-26620358-9606-4b0e-a0d5-8d9e4ce6dc75.mp4

### Steps to reproduce

I attached an minimal project where you can see the Issue.

In my example there is a KinematicBody2D that is moving towards a StaticBody2D. As expected, the KinematicBody moves along the StaticBody2D. But if the two nodes are now at a high position (in my example x=2783488 and y=2783488), the KinematicBody gets stuck at the StaticBody2D.

### Minimal reproduction project

[PhysicsTest.zip](https://github.com/godotengine/godot/files/8164899/PhysicsTest.zip)

**Comment by Calinou** [comment]
With Godot using 32-bit coordinates for everything, I'm not sure if this can be fixed. It may be possible to improve precision by ensuring computations do not cascade into losing precision, but it may not suffice in this scenario.

cc @aaronfranke

**Comment by aaronfranke** [comment]
At the positions you gave (±2783488 pixels), the float precision is only 0.25 pixels. Many calculations in a row can cause errors to compound / cascade, so it's not surprising that you are experiencing issues at this distance.

It's possible that there are bugs that we can fix that would allow you to go a few times farther, since 0.25 might be enough precision for this case, but really the only proper fix is to increase the amount of floating point precision.

Have you tried using the `float=64` compile option in the master branch (what will become Godot 4.0)? Using double-precision 64-bit floats will theoretically allow you to travel quadrillions of pixels away from the origin.

**Comment by Matti1903** [comment]
I tried to build it with the `float=64` argument, but that didn't help.

**Comment by Matti1903** [comment]
I tried compiling Godot 3.4.3 with the `float=64` argument, but that did not solve the issue for me.

**Comment by aaronfranke** [comment]
@Matti1903 The `float=64` argument only works in Godot 4.0 and later.

**Comment by Matti1903** [comment]
I tried the demo project I attached with the Godot 4.0 alpha, the problem still exists there.
Is the alpha built without the `float=64` option?

**Comment by aaronfranke** [comment]
All official releases use `float=32` (or rather, they don't specify `float=` so it defaults to `32`). You have to either build it yourself, or Linux users can grab the "Linux Builds / Editor with doubles and sanitizers" build from CI.

**Comment by Matti1903** [comment]
Ok thank you for the information. Then I guess I will have to wait for godot 4.0 to be finished.
