### ISSUE TITLE
Translation project name is not working for iOS export

### ISSUE THREAD

**Issue by wangdong20** [godotengine/godot#58709]
### Godot version

3.3.2 stable

### System information

macOS 12.1, Mac Pro

### Issue description

I just followed the docs to add Application/config/name_zh with project name in translation, then export it to iOS project. Then I try to run it on iPhone, the translation didn't show up even I already changed the language setting on my iPhone. I have no idea what is wrong by my operation. I haven't try it on Android yet.

### Steps to reproduce

Add Application/config/name_zh with project name in translation, then export it to iOS project. 
Export it as iOS project, then build in Xcode and run it on iPhone, the translation of project name was not show up on the device.

**Comment by timothyqiu** [comment]
This is currently only implemented on Android if I remember correctly.

**Comment by wangdong20** [comment]
> This is currently only implemented on Android if I remember correctly.

How do I implement iOS export project app name translation in Xcode if Godot can't do it.

**Comment by timothyqiu** [comment]
I don't have a mac now. But if you have access to the Xcode project, I think you can localize it like a regular iOS project via `InfoPlist.strings`.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by bruvzg** [comment]
> But if you have access to the Xcode project, I think you can localize it like a regular iOS project via InfoPlist.strings.

This should be the case for all "system" texts, like an app name or permission request messages, for both iOS and macOS. Godot translations are used only by the engine itself.

**Comment by timothyqiu** [comment]
Since the [documentation](https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html#translating-the-project-name) suggests to use `application/config/name_{locale}` for localizing the project name, I think we should either make it clear that this approach is Android-only, or try implementing it for iOS.

According to the _Localizing Property List Values_ section of [this documentation](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/AboutInformationPropertyListFiles.html). It seems that creating a plain text `Contents/Resources/{locale}.lproj/InfoPlist.strings` with `CFBundleDisplayName = "{localized name}";` in it is all that have to be done.

I don't have a mac so I'm unable to test it.

**Comment by bruvzg** [comment]
Recently, I have added empty translation `.plist` generation to the macOS exports. I guess the same should be done for iOS (we can also write `application/config/name_{locale}` value to the file automatically).
