### ISSUE TITLE
Searching some words results in empty Editor Settings sections

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#58815]
### Godot version

ff65d33

### System information

W10

### Issue description

![godot windows tools 64_B7kAAT1CtT](https://user-images.githubusercontent.com/2223172/156903908-f6f1e776-47e5-47f8-ba6d-91b558ea00c2.gif)

### Steps to reproduce

1. Open Editor Settings
2. Search `type_`

**Comment by Calinou** [comment]
I can confirm this on `master` and `3.x` cf970aab2.

## `master`

![image](https://user-images.githubusercontent.com/180032/156904006-066e62d0-9892-4e26-8e7f-bff4fdeaa09f.png)

## `3.x`

![image](https://user-images.githubusercontent.com/180032/156904013-5838e95c-bef4-4aa6-86e2-d131dab20e6f.png)

**Comment by EricEzaM** [comment]
The settings that trigger these sections to show:
```
interface/editor/code_font_custom_opentype_features
text_editor/theme/highlighting/base_type_color
text_editor/theme/highlighting/engine_type_color
text_editor/theme/highlighting/user_type_color
text_editor/appearance/gutters/highlight_type_safe_lines
text_editor/completion/add_type_hints
```

The culprit seems to be these lines:
https://github.com/godotengine/godot/blob/b70a83a2b9be57467cc1572ba6f5d45e4c09d661/editor/editor_inspector.cpp#L2690-L2696

In a sectioned editor inspector, the paths already have all "/" stripped from them, so when it gets to this code they are all converted to an empty string. Note that the reason this happens only on underscores is because only the paths contain underscores. Look at the lines after the code above:

https://github.com/godotengine/godot/blob/b70a83a2b9be57467cc1572ba6f5d45e4c09d661/editor/editor_inspector.cpp#L2698-L2703

`filter.is_subsequence_ofn(path)` will always fail because path is always empty in a sectioned editor inspector, and 'path' is the only one of those that can contain underscores. I have no idea why the code from lines 2690-2696 exists.

So essentially it comes down to the fact the filtering is done twice: once to filter the sections on the left, and again to filter the properties displayed themselves, and these two filtering implementations appear to be different.

**Comment by EricEzaM** [comment]
This came from 4bd7700e cc @groud
