### ISSUE TITLE
device limit exceeded for uniform buffer

### ISSUE THREAD

**Issue by Dolichomps** [godotengine/godot#58840]
### Godot version

4.0 alpha 3

### System information

Windows 11, AMD RX 6700XT, Vulkan, Driver Version 22.2.3

### Issue description

When writing a custom spatial shader if I add any uniforms I get this warning. The shader still works fine in both the editor and the game. I haven't touched any limits in the project settings. It seems like it is not properly determining my device limits? I am assuming because of the -1.

`Line 2 (DEVICE_LIMIT_EXCEEDED):The total size of the uniform buffer for this shader on this device has been exceeded (4/-1). The shader may not work correctly.`

### Steps to reproduce

add any uniform to a shader

``` glsl
shader_type spatial;

uniform float test = 0.0f;

void fragment() {
	// Place fragment code here.
}

**Comment by Calinou** [comment]
Do you have any global or per-instance uniforms defined in the project?

**Comment by Dolichomps** [comment]
No I have none.

**Comment by clayjohn** [comment]
Looks like the ``maxUniformBufferRange`` is returning -1. 
https://github.com/godotengine/godot/blob/ffd64505c51cb9734ad68f52277c807a9b759338/drivers/vulkan/rendering_device_vulkan.cpp#L9343
the ``maxUniformBufferRange`` is set here:
https://github.com/godotengine/godot/blob/1f3916e0b6afc84872f7354432ca8606d764fc22/drivers/vulkan/vulkan_context.cpp#L958
The ``maxUniformBufferRange`` for a 6700xt [as reported on GPUInfo.org](https://vulkan.gpuinfo.org/displayreport.php?id=14253#properties) is ``4,294,967,295`` which is the largest value an unsigned 32 bit integer can represent (conveniently ``vkGetPhysicalDeviceProperties`` returns ``maxUniformBufferRange`` as a [uint32_t](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceLimits.html)). Converted to a signed 32 bit integer it is ``-1``

So the core of the problem is that ``limit_get`` returns an ``int`` even though many of the values it returns should be uints and require the full range of uint 
https://github.com/godotengine/godot/blob/ffd64505c51cb9734ad68f52277c807a9b759338/drivers/vulkan/rendering_device_vulkan.cpp#L9298

``limit_get`` should be changed to return a uint64_t (or a uint32_t if ``LIMIT_MIN_UNIFORM_BUFFER_OFFSET_ALIGNMENT`` is removed as it requires a uint64_t)

**Comment by notSanil** [comment]
Hi, I'm new and I'd like to work on this. If this is to do the proposed changes, then can I do this?

**Comment by Calinou** [comment]
> Hi, I'm new and I'd like to work on this. If this is to do the proposed changes, then can I do this?

Sure, go ahead :slightly_smiling_face:
