### ISSUE TITLE
Inspector's dropdown parses the strings of @export_enum("A, B", "C") incorrectly

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [godotengine/godot#58846]
### Godot version

4.0.alpha3

### System information

Linux

### Issue description

Inspector's dropdown parses the strings of @export_enum("A, B", "C") incorrectly
![script export enum parsing error](https://user-images.githubusercontent.com/3934352/156939342-de9c8cf9-8337-4136-9b0d-daa4f57e372b.png)

### Steps to reproduce

Add `@export_enum("A, B", "C") var pick: int` to a node's script.
In the editor's scene tree, select the node.
In the Inspector open the dropdown for "pick".
Note that it should have 2 items ("A, B" and "C") not 3 items ("A", " B", "C").

**Comment by timothyqiu** [comment]
This also happens on `3.x`, and also affects bit flags (`PROPERTY_HINT_FLAGS`).

```gdscript
export(int, FLAGS, "A,B", "C") var foo
export(int, "A,B", "C") var bar
```

![ksnip_20220318-005144](https://user-images.githubusercontent.com/372476/158852542-08620ede-c766-41f5-bfd5-79b5d685a13c.png)

C# supports specifying hint & hint string directly, so I think it's also affected (not tested):

```csharp
[Export(PropertyHint.Flags, "Fire,Water,Earth,Wind")]
private int SpellElements = 0;
```

The root cause is we don't support escapes in these hint strings. I think we can error out for GDScript code:

```gdscript
export_enum("A, B", "C") var pick: int  # comma is not allowed in enumerator
```
