### ISSUE TITLE
ColorRect does not have color_changed signal

### ISSUE THREAD

**Issue by dragifon** [godotengine/godot#58884]
### Godot version

Godot Engine v3.4.3.stable.flathub.242c05d12

### System information

OS: Manjaro Linux x86_64    Kernel: 5.16.11-2-MANJARO 

### Issue description

The ColorRect node doesn't have a color_changed(color: Color) signal. I needed this to tell another node when the ColorRect's color had been changed in the editor. I tried making my own signal in a script attached to the ColorRect, but couldn't figure out where to emit the signal nor how to detect the color changing from a previous frame. I guess this might be possible by attaching a tool script and comparing the ColorRect's color property in the _process() function, but that seems far more difficult than simply having a color_changed(color: Color) signal built into the ColorRect node like the ColorPicker node.

### Steps to reproduce

1. Add ColorRect node to a scene
2. Look through Signals on the Node dock for "color_changed(color: Color)"

**Comment by KoBeWi** [comment]
This should go to [proposals](https://github.com/godotengine/godot-proposals). But it won't be added, because ColorRect's `color` can only be changed from editor/code and if you do that, additional notification is redundant. It's like requesting `text_changed` to Label.

You could use a setter or a Tween for this case.

**Comment by timothyqiu** [comment]
I think you can override `_set` to inspect any property changes. Just return `false` for everything to keep the original behavior.
