### ISSUE TITLE
Implement automatic OpenGL fallback for GPUs not supporting Vulkan

### ISSUE THREAD

**Issue by Leedoriden** [godotengine/godot#58927]
### Godot version

alpha 4

### System information

win 10

### Issue description

when i open Godot alpha 4 exe i've this error messag
![Ga4_crash](https://user-images.githubusercontent.com/73864215/157448670-6abe3f63-67a9-4684-b883-03ddb92c05d9.jpg)
e

### Steps to reproduce

double clic exe

**Comment by akien-mga** [comment]
Please provide more information on your system (CPU, GPU at least).

**Comment by Leedoriden** [comment]
CPU i7 2630Q% 2 GHz
GPU NVidia GeForce540M 2Go

**Comment by akien-mga** [comment]
I think Nvidia doesn't provide Vulkan drivers for the 540M series: https://www.nvidia.com/en-us/geforce/forums/discover/231677/vulkan-support-for-geforce-540m-gt-notebook-/

So you're out of luck to run Godot 4 for now until we have completed the OpenGL 3.3 renderer (it's currently work in progress, you can test it with `--rendering-driver opengl3` but it's very limited - only 2D, and lots of things unimplemented still).

Still, it should normally tell you that your GPU doesn't support Vulkan instead of crashing, so we should look into this.

**Comment by Leedoriden** [comment]
same issue with --rendering-driver opengl3
Probably my GPU notebook is too old to run the latest Godot's version

**Comment by akien-mga** [comment]
> same issue with --rendering-driver opengl3

That's weird because the error is related to Vulkan. Are you running it from the console or from a shortcut with `Godot_4.0-alpha4_win64.exe --rendering-driver opengl3`? It should at least let you open the project manager then (and to open projects you'd have to make sure to select the OpenGL renderer in the New Project creation dialog).

---

@RandomShaper The line it's crashing on is:
```
    VMA_ASSERT(pCreateInfo->physicalDevice && pCreateInfo->device && pCreateInfo->instance);
```

I think we should make sure that the `VmaAllocatorCreateInfo` we pass to VMA is valid on the Godot side, so we can do proper error handling instead of hitting its assert.

We should likely also set `NDEBUG` on `release` and `release_debug` builds as several thirdparty dependencies rely on it to disable debug stuff, including here `VMA_ASSERT`.

**Comment by Leedoriden** [comment]
I run Godot a4 via shortcut with --rendering-driver opengl3
I also setup Exe in NVidia Card ( see pics )

![g4_nvidia_setup](https://user-images.githubusercontent.com/73864215/157460885-604e5ce6-d6ae-43f0-b1de-871a1b9f199a.jpg)

Godot runs but some GUI are no visible
Here, i press ENTER to confirm

![g4_start](https://user-images.githubusercontent.com/73864215/157460927-1c425195-137a-4ded-a5b8-241007798dd7.jpg)

and the result is 

![g4_start2](https://user-images.githubusercontent.com/73864215/157461007-89291418-3df2-4096-b397-b1788a311738.jpg)

**Comment by akien-mga** [comment]
@Leedoriden Ah thanks, so it's "working", there's just another bug with multiple window support in the OpenGL renderer on Windows. It's still very early progress so it's not unexpected.

You might be able to work things around with some command line magic if you want to test the editor with OpenGL:
- Create a new folder for a project
- Create a text file in that folder named `project.godot` with these contents:
```ini
[rendering]

driver/driver_name="opengl3"
```
- Put the Godot .exe in the project folder
- Make a shortcut in that folder to run the Godot .exe with the `-e` option (`--editor`)

**Comment by Calinou** [comment]
`--rendering-driver opengl3` should currently **always** be used with `--single-window`, as multi-window support is not implemented yet in the OpenGL renderer. This should fix editor and project manager display.

**Comment by Leedoriden** [comment]
i  followed instructions and this is the result

no 2D & 3D windows ( black GUI )
menus are not clickable / visible, same for the rest of GUI

![g4_start3](https://user-images.githubusercontent.com/73864215/157464860-2b6934d7-9d81-4da9-9f53-9caa10e17a2f.jpg)

**Comment by Leedoriden** [comment]
with --rendering-driver opengl3 --single-window

menus are visibles & clickables now

2D & 3D are still black GUI

**Comment by RandomShaper** [comment]
When I try to simulate a lack of Vulkan drivers on latest _master_ (by running Windows in fail safe mode), I get the following dialog:
**
![image](https://user-images.githubusercontent.com/11797174/158030287-30db9435-3c8e-4e5f-9d20-ac4bb0c01ccc.png)
**

I'm curious about which flow of failed setup can lead to the message not being shown.

Aside, it's worth mentioning that Godot will end up falling back to the dummy display server and therefore keep running without any window created and nothing shown. I've submitted a PR to avoid that, to be more user friendly: #59074

**Comment by sugarsthenewwhite** [comment]
> I think Nvidia doesn't provide Vulkan drivers for the 540M series: https://www.nvidia.com/en-us/geforce/forums/discover/231677/vulkan-support-for-geforce-540m-gt-notebook-/
> 
> So you're out of luck to run Godot 4 for now until we have completed the OpenGL 3.3 renderer (it's currently work in progress, you can test it with `--rendering-driver opengl3` but it's very limited - only 2D, and lots of things unimplemented still).
> 
> Still, it should normally tell you that your GPU doesn't support Vulkan instead of crashing, so we should look into this.

I'm not sure if thats entirely true? i have a gt 520 and i ran this test https://github.com/skeeto/vulkan-test  which says i can run vulkan but when it comes to godot 4 alpha 12 i get this exact error as the op ;
![image](https://user-images.githubusercontent.com/53354625/180626749-01a4a00b-087f-4a75-aca5-e5489c6b91eb.png)

does that test mean anything or??

**Comment by Calinou** [comment]
> i have a gt 520 and i ran this test [skeeto/vulkan-test](https://github.com/skeeto/vulkan-test) which says i can run vulkan

No, Fermi GPUs have never supported Vulkan, no matter the operating system used.

**Comment by joemicmc** [comment]
I can reproduce the c++ error if useful. My laptop GPU is GeForce GT 710M and doesn't look like it's supported (downloaded Vulkan SDK and tried to run demo scene). The OpenGL rendering worked better than expected though!

**Comment by Calinou** [comment]
> I can reproduce the c++ error if useful. My laptop GPU is GeForce GT 710M and doesn't look like it's supported (downloaded Vulkan SDK and tried to run demo scene). The OpenGL rendering worked better than expected though!

Mobile Kepler GPUs don't support Vulkan either – only desktop GPUs do.

**Comment by joemicmc** [comment]
> Mobile Kepler GPUs don't support Vulkan either (at least on Windows) – only desktop Kepler GPUs do.

Yep I understand my laptop GPU is not supported, just pointing out I can reproduce the unhandled error so can retest when there's a fix.

**Comment by Vivalzar** [comment]
Since it will be a long time before OpenGL will be available in Godot 4, would it be possible in the meantime to have a friendly error message displayed?

Right now with the beta, Godot silently freezes on launch when Vulkan is not supported.

**Comment by Calinou** [comment]
> Since it will be a long time before OpenGL will be available in Godot 4, would it be possible in the meantime to have a friendly error message displayed?

Implementing this message takes the same amount of effort as implementing an automatic fallback, so we might as well implement the fallback directly.

**Comment by Vivalzar** [comment]
> Implementing this message takes the same amount of effort as implementing an automatic fallback, so we might as well implement the fallback directly.

Ok, thank you for the information. I thought that the fallback was harder to implement because I was under the impression that OpenGL was not ready for Godot 4 yet.

**Comment by lostminds** [comment]
If this automatic fallback to the Compatibility OpenGL renderer is implemented, it would be good if there was some way of detecting this in GDScript so that projects can adapt if necessary to the different renderers. 
Currently all I've found is the [OS.RenderingDriver](https://docs.godotengine.org/en/latest/classes/class_os.html#enum-os-renderingdriver) enum definition, but no way to access the current value. The `OS.get_current_rendering_method()` [mentioned previously regarding renderer features](https://github.com/godotengine/godot-proposals/issues/6207#issuecomment-1409742857) doesn't seem to be exposed in GDScript in Godot 4?

Or maybe the intention is to make the OpenGL Compatiblity renderer support all the same features eventually (or at least fail gracefully if unsupported features are used), so that the game doesn't need to know what renderer it is using?

**Comment by Calinou** [comment]
> The OS.get_current_rendering_method() https://github.com/godotengine/godot-proposals/issues/6207#issuecomment-1409742857 doesn't seem to be exposed in GDScript in Godot 4?

It should be trivial to expose by adding the required code to `core_bind.cpp`/`os.cpp`.

**Comment by PauloVBettio** [comment]
This was the biggest struggle some testers had when I shared my game. Many of them couldn't start the game because they didn't know what CMD is and had little to no knowledge about how arguments work. They only knew that double-clicking the game opens it. As a result, I had to provide a .bat file that contains the necessary command for them to run the game without having to open the command prompt and do it themselves.

I've also noticed that this error is frequently discussed in all the Godot communities I'm a part of, including Facebook, Reddit, and Discord.

Addressing this issue should be a priority. Maybe by adding a button to "Run in Compatibility Mode" if making automatic is complicated to do now.

**Comment by akien-mga** [comment]
This started as a bug report about a crash, but I think that part was solved.

This issue was then repurposed in a way that's more suitable for a formal proposal, so I'll open one to supersede this issue.

**Comment by akien-mga** [comment]
Here we go: https://github.com/godotengine/godot-proposals/issues/8006

Let's keep the discussion on OpenGL fallback in the proposal.

**Comment by RpxdYTX** [comment]
Is this fallback only for the editor? Because it'd be awesome if games could also use this as long as no vulkan specific graphical functions are used
