### ISSUE TITLE
Port platform-specific GDNative code to support GDExtension

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#58935]
### Godot version

4.0.dev (922348f4c00e694961a7c9717abdcd0310c11973)

### System information

Any

### Issue description

GDNative is being replaced by GDExtension in 4.0, and we need to make sure that all relevant engine code is ported.

In particular, platform-specific export code has some code to handle bundling GDNative libraries in the export, and this needs to be adapted and tested to handle GDExtension libraries properly.

TODO: Port export code and test exporting a project with a GDExtension library for:

- [ ] Android
- [ ] HTML5 (that's likely going to be tricky, requires both threads + dlopen support which was not possible until now - can be moved to a dedicated issue if everything else gets fixed and this one is stuck waiting for Emscripten changes)
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Windows

**Comment by akien-mga** [comment]
CC @godotengine/_platforms for the respective platform porting and testing. (Some might already be ported, I didn't test any.)

This can likely be tested with the godot-cpp demo initially: https://github.com/godotengine/godot-cpp/tree/master/test/demo

**Comment by bruvzg** [comment]
> In particular, platform-specific export code has some code to handle bundling GDNative libraries in the export, and this needs to be adapted and tested to handle GDExtension libraries properly.

We probably should add a few improvements to the way GDNative used to export libs:
- Add an option to specify folders as dependency (for including JRE for example), right no there's no way to set dependencies at all, GDNative had only single file dependencies.
- Instead of exporting all libs into executable folder, add an option to set library / dependency target location (this is also relevant for stuff like JRE, with both libraries and non-executable files, which should be placed in the `Frameworks` and `Resources` on macOS. Or can be used to avoid clutter by placing all libraries into the `libs` subfolder).
