### ISSUE TITLE
Godot Engine - Project Manager 4.0.alpha4 - can't resolve https://godotengine.org/asset-library/api/

### ISSUE THREAD

**Issue by mo-moxi-gd** [godotengine/godot#59037]
### Godot version

v4.0.alpha4.official(f47097973)

### System information

Debian 11 (Bulleye)

### Issue description

Project manager can't resolve https://godotengine.org/asset-library/api/

### Steps to reproduce

Load Godot alpha 4, then select asset library projects

**Comment by Sauermann** [comment]
I am unable to reproduce this issue on Debian 11 with v4.0.alpha4.official [f47097973].
It works for me.

**Comment by Calinou** [comment]
@mo-moxi-gd Are you behind an HTTP proxy or a [dual-stack IPv4/IPv6 connection](https://github.com/godotengine/godot/issues/36418)?

**Comment by Sniperchang** [comment]
I have this issue. According to the [conversation in this issue](https://github.com/godotengine/godot/issues/36418), I seem to have a broken dual-stack, where I can ping godotengine.org via IPv4 but not IPv6. But I don't have this issue with V3.4.3

**Comment by RibalGZ** [comment]
> I have this issue. According to the [conversation in this issue](https://github.com/godotengine/godot/issues/36418), I seem to have a broken dual-stack, where I can ping godotengine.org via IPv4 but not IPv6. But I don't have this issue with V3.4.3

Same problem here using the master branch.

**Comment by taisph** [comment]
Godot outputs the message below to the console:
```
ERROR: getaddrinfo failed! Cannot resolve hostname.
   at: _resolve_hostname (drivers/unix/ip_unix.cpp:98)
```

https://github.com/godotengine/godot/blob/f470979732513436124c01a465b22f948637b5fa/drivers/unix/ip_unix.cpp#L96-L100

It seems to be caused by the proxy handling code. It expects the proxy host to be empty or the port to be -1, but when it gets the proxy config from the editor settings, if they are not set, proxy host is U"null" (`.is_empty()` is then false) and port is 0, which makes godot try and fail to resolve the proxy host.

https://github.com/godotengine/godot/blob/f470979732513436124c01a465b22f948637b5fa/core/io/http_client_tcp.cpp#L761-L779

Adding `network/http_proxy/port = -1` to the "~/.config/godot/editor_settings-4.tres" file is enough to make Godot ignore the proxy and the asset library no longer fails to lookup the host. Maybe setting the editor defaults is a good approach.
