### ISSUE TITLE
Physics interpolation (3D): Issue when setting the position of a Rigidbody or Kinematicbody

### ISSUE THREAD

**Issue by FilipLundby** [godotengine/godot#59173]
### Godot version

Godot 3.5 beta 2

### System information

Ubuntu 21.10, GLES3

### Issue description

When I instance a Rigidbody or Kinematicbody and immediately set the position right after, the object blinks for at least 1 frame before moving to the desired position. 

This is not an issue when Physics Interpolation is disabled (Project Settings -> Physics -> Common).

### Steps to reproduce

1. Instance a Rigidbody or Kinematicbody and add it as a child node. Either `call_deferred("add_child", body)` or `add_child(body)` - doesn't matter.
2. Set the position using `body.global_transform.origin = Vector3(5, 0, 0)`

### Minimal reproduction project

Run the game and left-click your mouse. 

[Godot-3.5.beta2.PhyInt.zip](https://github.com/godotengine/godot/files/8256341/Godot-3.5.beta2.PhyInt.zip)

**Comment by lawnjelly** [comment]
See the in progress docs:
https://github.com/lawnjelly/Misc/blob/master/FTIDocs/FTI.md

Specifically this section:
https://github.com/lawnjelly/Misc/blob/master/FTIDocs/FTI.md#call-reset_physics_interpolation-when-teleporting-objects-large-distances

This is expected :+1: , this is one of the gotchas of using interpolation, you need to call `reset_physics_interpolation()` after moving to a new location (teleport) rather than regular movement, in order to prevent this "streaking".

**Comment by rburing** [comment]
By the way, you can avoid the deferring and the yielding by setting the correct position from the start, like this:

```
func _input(event: InputEvent) -> void:
    if event is InputEventMouseButton:
        if event.button_index == BUTTON_LEFT and event.pressed:
            var sphere = _sphere.instance()
            sphere.translation = to_local(Vector3(5, 0, 0))
            add_child(sphere)
            sphere.reset_physics_interpolation()
```

The "difficult" part of this alternative is using local coordinates instead of global coordinates. In my opinion it's conceptually easier than deferring and yielding. Moreover, it ensures that the object in the physics server is created with the correct values on the first frame. @lawnjelly Why is the reset needed in this case as well (in 3.5 beta 2)?

**Comment by lawnjelly** [comment]
> @lawnjelly Why is the reset needed in this case as well (in 3.5 beta 2)?

It could either be some transform being set at the origin in the client code, or even just the previous transform in the physics interpolation code is unset on the first tick. So calling the `reset_physics_interpolation()` is always best practice I think.

**Comment by RPicster** [comment]
Hm, I'm not sure if this is the right issue to append my problem to, but from my initial search it seems like it.

I am unsure if it is a problem from my side but it seems that adding nodes to the tree in general seems to interpolate from their "original" translation.

So:
```
var new_thing = Thing.instance()
new_thing.translation = Vector3(300,0,0)
add_child(new_thing)
```
would interpolate from Vector3.ZERO.
To have the behaviour that I guess most users would expect, I need to do:
```
var new_thing = Thing.instance()
new_thing.translation = Vector3(300,0,0)
add_child(new_thing)
new_thing.reset_physics_interpolation()
```

Is that correct?

**Comment by lawnjelly** [comment]
> To have the behaviour that I guess most users would expect, I need to do:
> Is that correct?

Yes, this is correct, adding a new object to the scene (in a location other than the origin) is one of the cases where a `reset_physics_interpolation()` is needed.

I think at some point I did consider automatically doing a `reset_physics_interpolation()` when adding to the scene tree, but there are so many cases where this would break down, it might be more confusing than helpful.

In short any time you are instantaneously moving to a new location (teleport, often referred to), including adding to the scene tree you should call `reset_physics_interpolation()` to prevent "streaking".

**Comment by FeralBytes** [comment]
@lawnjelly there is no equivalent that I see for Godot 4.0 that is for calling `reset_physics_interpolation()`, how would I do this in 4.0?

**Comment by Calinou** [comment]
> @lawnjelly there is no equivalent that I see for Godot 4.0 that is for calling `reset_physics_interpolation()`, how would I do this in 4.0?

Physics interpolation isn't implemented yet in 4.x.

**Comment by FilipLundby** [comment]
Closing, cause lawnjelly answered https://github.com/godotengine/godot/issues/59173#issuecomment-1068391400

For 4.x see https://github.com/godotengine/godot/pull/92391
