### ISSUE TITLE
OptionButton `expand_icon` breaks the layout

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#59202]
### Godot version

4.0 9d732aa / 3.x

### System information

Windows 10 x64

### Issue description

![image](https://user-images.githubusercontent.com/2223172/158632327-5acfe61d-9672-41ff-8056-1738ef645c8b.png)
Text overlaps arrow

### Steps to reproduce

1. Add OptionButton
2. Add some icon and text
3. Enable `expand_icon` property
4. Shrink the button to minimal size

**Comment by nickhachmer** [comment]
Hey! If possible I'd like to try and tackle this bug. This will be my first time trying to contribute to an open source, so I'm, excited to try it out.

**Comment by Calinou** [comment]
> Hey! If possible I'd like to try and tackle this bug. This will be my first time trying to contribute to an open source, so I'm, excited to try it out.

Sure, go ahead :slightly_smiling_face:

**Comment by rtarun9** [comment]
Hey! I have faced same bug earlier however the solution might be a bit tricky since the actual size of the OptionButton remains the same whether the ExpandIcon option is selected or not. What would be a good solution to this bug ? The options I can think of are both un optimal -> Limiting size of icon (or) changing size of OptionButton when the ExpandIcon option is selected.

**Comment by KoBeWi** [comment]
> changing size of OptionButton when the ExpandIcon option is selected.

This. Minimum size should properly use the final icon size. Right now it's probably ignored, like with most `expand` properties.

**Comment by AtlaStar** [comment]
> This. Minimum size should properly use the final icon size. Right now it's probably ignored, like with most `expand` properties. The icon's width seems to depend on the height, so it should be possible to calculate it.

The oddity here is that the code is functionally identical between the master and 3.x branch outside of some function renames or refactors for the `get_minimum_size()` methods in both `OptionButton` and `Button`, yet the master branch has no issues. It suggests a possibly deeper issue, but I am not yet familiar enough with the internals to even know quite where to look.

My trail currently has ended at trying to look at how the margins themselves get set, and looking into the diff of `texture_region_editor_plugin.cpp` across branches, which appear to be functionally the same outside of some updated semantics in for loops and usage of `SNAME`. Everything in `OptionButton` is identical in how it updates margins outside of the master branch having some localization stuff for right to left layouts, and everything appears to be logically identical in `Button` as well other than master using a more verbose means of getting the font dimensions for the minimum size.

So I believe that any submission that only changes the way the minimum size is calculated is marked with a big TODO or FIXME because it is probable that such a fix may  just mask a deeper bug that could pop up later down the development process.

**Comment by KoBeWi** [comment]
> yet the master branch has no issues.

The issue does exist in master. As I said in my previous comment, the problematic part is this code:
https://github.com/godotengine/godot/blob/35eec4de40ed25eeb4423fcd6ae65936db9961ec/scene/gui/button.cpp#L42-L62
If `expand_icon` is true, this whole block is ignored, which is incorrect.

**Comment by AtlaStar** [comment]
> > yet the master branch has no issues.
> 
> The issue does exist in master. As I said in my previous comment, the problematic part is this code:

Hmm, I must be mistaken in my memory then, because I was sure that I tested a build of both master and 3.x and only saw the behavior on the 3.x branch. Not just that but neither 3.4 or 3.3 branches do an explicit calculation of the icon size when `expand_icon` is true either. I haven't tested whether the issue exists in those branches or not, but if it doesn't that would be odd no?

That is mostly why I believe that there is something deeper going on and made the comments that I did, as if it works as expected on those other branches but not 3.x or master, then something else has to be going on suggesting a deeper issue.

**Comment by Rindbee** [comment]
Hello everyone, I think it may be caused by the following three reasons：
1. In the function `Button::get_minimum_size`, the minimum size is calculated without actually considering the `icon` size, as the `icon`  in Button can be hidden when the button size is smallest;
2. The size of the `icon` (not the `icon_arrow`) to draw that seems to be computed in the function `Button::_notification`. And It does consider the new properties in `OptionButton`;
3. In the function `OptionButton::get_minimum_size`, it takes the `arrow_icon` into the minimum size computing (`theme_override_constants/arrow_margin` should also be considered). It will make the width of the minimum size be larger.

So, when enable the property `expand_icon` in `OptionButton`, the `icon` will expand. The drawing actual width becomes wider.
