### ISSUE TITLE
[Vector3][Math] It is aboat Vector3.sign() function. When a component is zero, it returns positive one. That is weird！

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#59377]
### Godot version

3.3.4.stable

### System information

Window 10

### Issue description

[Vector3](https://docs.godotengine.org/en/stable/classes/class_vector3.html#class-vector3) sign ( )

Returns a vector with each component set to one or negative one, depending on the signs of this vector's components. If a component is zero,###  **_it returns positive one._**

But It should be return 0!? I don't know why it designs to return -1?

### Steps to reproduce

#

### Minimal reproduction project

#

**Comment by Calinou** [comment]
This also occurs with Vector2 (tested on Godot 3.4.3):

```gdscript
extends Node

func _ready():
	print(Vector3(0.2, 0, 0.2).sign())
	print(Vector3(-0.2, 0, -0.2).sign())
	print(Vector3(0, 0, 0).sign())
	print()
	print(Vector2(0.2, 0).sign())
	print(Vector2(-0.2, 0).sign())
	print(Vector2(0, 0).sign())
```

**Comment by akien-mga** [comment]
Is that a bug? `sign` is just a utility function and what it should do with 0 (which can be both positive or negative) is a matter of convention. Since the convention is clearly documented that 0 is treated as a positive integer, it seems fine to me?

I'm not sure why the convention changed in 4.0 though.
