### ISSUE TITLE
`cut` command (`ctrl+x`) deletes whole line even if nothing selected

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#59441]
### Godot version

v3.5.beta2.official [7a4f9dfb1]

### System information

Mac OSX (Intel 2019)

### Issue description

When in the script editor, press `Ctrl+x` (`Cmd+x` on mac).

The whole current line will be deleted. This often leads to annoyances if you are working in `Emacs` as `Ctrl+x` is such a common keybinding. 

I often find myself accidentally deleting one line and then trying to run the game.

### Steps to reproduce

When in the script editor, press `Ctrl+x` (`Cmd+x` on mac).

**Comment by timothyqiu** [comment]
Many editors have behaviors like this, i.e. copy/cut the whole line when nothing is selected. e.g. VSCode and JetBrains IDEs.

**Comment by tavurth** [comment]
Perhaps then a way to disable this behaviour? 

For me I rarely type anything in the script editor (rather using it as a separate screen), so this just causes an annoyance.

**Comment by tavurth** [comment]
Cut can be useful, so the answer to cripple the script editor in some way (by moving the default cut key) doesn't sound great to me.

**Comment by tavurth** [comment]
I think there is also an important difference in godot from most editors. 

Since in godot you spend 90% of your time in other UI, whereas in VSCode you spent 90% of the time in the editor.

**Comment by tavurth** [comment]
Another problem here is that when I accidentally cut something, I can press `Ctrl + z` to undo, but the lines are then selected. This causes other development flow issues.

For me these are not huge issues but something I see every day at least a few times and breaks my immersion as I struggle to get Godot to do what I feel it should be doing.

**Comment by BeayemX** [comment]
Sure, the following explanations are just my opinion, no offense meant.

> The whole current line will be deleted. This often leads to annoyances if you are working in Emacs as Ctrl+x is such a common keybinding

This is only true for people who are used to Emacs. For people who use VSCode or similar software, they would expect the behavior how it is currently implemented.
I am guessing here, but I think there are more users that are used to VSCode or similar as compared to Emacs.

> I often find myself accidentally deleting one line and then trying to run the game.

This feels more like a user error and while changing it may be beneficial to you, it certainly would cripple the experience for others.

> perhaps adding a second shortcut for cut line (defaulting to ctr+x) when nothing is selected would fix this issue.

I don't think adding a second keybinding for `cut` is a good way. 

> In godot you spend 90% of your time in other UI (inspector) whereas in VSCode you spent 90% of the time in the text editor.

This is just not true and heavily depends on the user. For me I would say that the percentages could be switched because I spend most of my time in Godot writing code.

> Another problem here is that when I accidentally cut something, I can press Ctrl + z to undo, but the lines are then selected. This causes other development flow issues.

I agree with this, but I don't think this has anything to do with the original issue and it should probably be made an issue of its own.

**Conclusion**
I certainly would be glad if Godot would work for everyone and the problem could be solved for you, but I think the current implementation is superior to your suggestion for the majority of the users.

**Comment by tavurth** [comment]
> I think the current implementation is superior to your suggestion for the majority of the users.

Thanks for the in depth reply. OK it makes sense that a lot of people want to keep their flow as similar to VSCode as possible.

What about adding a single toggle somewhere in the editor settings which enabled or disabled this feature?

**Comment by TheSofox** [comment]
I have made a pull request that solves this by adding a Project Settings checkbox that can disable this behaviour (it's on by default so no changes for most people).

> Another problem here is that when I accidentally cut something, I can press `Ctrl + z` to undo, but the lines are then selected

If this is still an issue, make a separate bug report. You may tag me when doing so.

**Comment by KoBeWi** [comment]
Resolved by #90743
