### ISSUE TITLE
warp_mouse_position doesnt work on project settings/window/move - 2d or viewPort

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#59461]
### Godot version

v3.4.3

### System information

windows 10, GLS3

### Issue description

dificulty in setting the mouse position.
If the project settings are set to mode 2D or mode viewport
warp_mouse_position only works when mode is disable

		if ( Input.is_action_just_pressed('mouse_button') ):
			Input.warp_mouse_position( btn_name.get_global_transform_with_canvas().get_origin() );
			
		elif ( Input.is_action_pressed('mouse_button') ):
			btn_name.rect_global_position = get_global_mouse_position();
			skel_name.global_position =  btn_name.rect_global_position;

### Steps to reproduce

project settings window/set mode to 2d or mode viewPort
forum: https://godotforums.org/discussion/comment/65129#Comment_65129

func _physics_process(_delta: float) -> void:
Input.warp_mouse_position( vector2(50, 50) );

#--the cursor goes off screen in full or window mode
![mouse](https://user-images.githubusercontent.com/77213594/159879297-5f10111f-a58a-46f1-9a4b-36056a8bee46.png)

**Comment by Sauermann** [comment]
In your reproduction project you use
``` gdscript
func _input(event):
	if event is InputEventMouseMotion:
		mouse_pos = event.position
```
`event.position` is in the coordinate system of the viewport.

``` gdscript
Input.warp_mouse_position(mouse_pos + mouse_rel)
```
`Input.warp_mouse_position` expects its input in the coordinate system of the Screen, but your parameters are in the coordinate system of the viewport. So you are mixing different coordinate systems.

Please try using `get_viewport().warp_mouse(mouse_pos + mouse_rel)` instead of `Input.warp_mouse_position`. This takes care of converting viewport coordinates to screen coordinates (at least in this simple case without nested viewports #59308).

**Comment by jonSP12** [comment]
thanks, 
but can you tell me were the var mouse_rel is being created

**Comment by jonSP12** [comment]
ok, lol
thanks
