### ISSUE TITLE
(Auto-)update of assets

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#5947]
As mentioned in the (RIP) #4279 :
It would be nice to have a way to update assets that were installed from the asset library. That would require storing asset information (as an url probably), and maybe a list of selected folders from the asset. Then, when a button is clicked, or some time after the editor is started, we can check for updates to the said assets (by comparing the version id properties), and notify the user if it is so.

WDYT?

**Comment by caryoscelus** [comment]
:+1: 

For me, there is virtually no use in asset library without update and restore (loading specific version of asset stored in config when it's not found - it would allow to keep repository free of external deps) features. Would be great if it's implemented.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
