### ISSUE TITLE
Vulkan: SpotLight3D's Projector doesn't work (regression from 4.0.alpha5 and later)

### ISSUE THREAD

**Issue by macryc** [godotengine/godot#59488]
### Godot version

4.0 alpha 5

### System information

Win10, GLES3, RTX 2070 mobile

### Issue description

SpotLight3D's Projector doesn't work. Worked fine in alpha 4, stopped in alpha 5.

### Steps to reproduce

Create a 3d scene
add spotlight3d
add texture2d to projector slot
enable shadows on spotlight
put in a 3d mesh to cast spotlight on

**Comment by Calinou** [comment]
@macryc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by macryc** [comment]
[spotlight3d.zip](https://github.com/godotengine/godot/files/8345783/spotlight3d.zip)

**Comment by Calinou** [comment]
I can confirm this on 992317957 (Linux, NVIDIA 510.68.02). OmniLight3D projectors also don't work.

**Comment by Calinou** [comment]
I bisected the regression to 57e5a33623130ead5aeb5369c7a40410a1afc79b. cc @BastiaanOlij

**Comment by BastiaanOlij** [comment]
Hmm, I must have messed something up when moving all the code related to this into the new TextureStorage class. I'll have a closer look as soon as I've finished with the GI changes.

**Comment by kidinashell** [comment]
Currently still no change (in 4.0 beta1) when using projector textures (plain lighting as per default) @BastiaanOlij Would this be something you could want some help with? I've never contributed to the project myself so I would have to look into the structure of things and regulations but I would like to fix this if possible.

**Comment by fire** [comment]
@clayjohn May be able to assist @kidinashell

**Comment by clayjohn** [comment]
> Currently still no change (in 4.0 beta1) when using projector textures (plain lighting as per default) @BastiaanOlij Would this be something you could want some help with? I've never contributed to the project myself so I would have to look into the structure of things and regulations but I would like to fix this if possible.

@kidinashell Feel free to work on this, Bastiaan is quite busy with some other work right now. 

To help you get started, projector textures were added in https://github.com/godotengine/godot/pull/37887. This should give you an idea about how they should work.

Calinou bisected the regression to https://github.com/godotengine/godot/commit/57e5a33623130ead5aeb5369c7a40410a1afc79b so the bug was introduced by something that Bastiaan changed in https://github.com/godotengine/godot/commit/57e5a33623130ead5aeb5369c7a40410a1afc79b. Looking between Juan's PR and Bastiaan's commit you should be able to find out what went wrong. 

As for contributing, we have a whole [section of the docs](https://docs.godotengine.org/en/latest/community/contributing/index.html) dedicated to documenting helpful things to know as you get started contributing. 

Also feel free to ask questions. You can reach both Bastiaan and I quite easily on the rendering channel on Godot's [contributor chat](chat.godotengine.org).

**Comment by BastiaanOlij** [comment]
Sorry guys, totally lost track of this one. Yeah I'm heads down bum up in further reorg stuff so I could definitely use an extra set of eyes on this one. As the commit that seems to have broken this mostly moves stuff into new classes it's likely a simple issue with a RID getting mixed up or a setting getting reversed.

**Comment by kidinashell** [comment]
@BastiaanOlij Did a PR #66065 for this after looking around the renderer section and it's ready for review. Hope it helps.
