### ISSUE TITLE
Vulkan: SSR breaks with transparent materials

### ISSUE THREAD

**Issue by PZerua** [godotengine/godot#59512]
### Godot version

v4.0.alpha.custom_build [3990152f6]

### System information

Windows 10, Nvidia GTX 970 (471.11), Vulkan

### Issue description

When enabling SSR in a scene with transparent materials the render is completely broken:
![ssr break](https://user-images.githubusercontent.com/8772233/160095038-e1b366b7-1894-4009-a1da-1b4022c0c08d.png)

Taking a closer look, seems that it is related to how depth is managed when SSR is enabled in the merge_specular function here:
https://github.com/godotengine/godot/blob/3990152f6b7fcbac39ed68f0cc0fd36131bc9e2f/servers/rendering/renderer_rd/effects_rd.cpp#L766
The final depth action is set to **FINAL_ACTION_DISCARD**, which at the end sets the flag VK_ATTACHMENT_STORE_OP_DONT_CARE in the attachment description. From the [vulkan docs](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkAttachmentStoreOp.html):

> VK_ATTACHMENT_STORE_OP_DONT_CARE specifies the contents within the render area are not needed after rendering, and **may** be discarded.

Looking in renderdoc, the transparencies get rendered just after the effects, and the depth buffer seems to be reaching the "Render 3D Transparent Pass" in an undefined state.

Changing the final depth action to **FINAL_ACTION_READ** seems to fix the issue, but I'm not completely sure this is the proper solution and intended behavior.

### Steps to reproduce

1 - Add a mesh and apply a material that has transparencies.
2 - Enable SSR in environment node.

### Minimal reproduction project

[Test SSR.zip](https://github.com/godotengine/godot/files/8778498/Test.SSR.zip)

**Comment by ComputehGuy** [comment]
I downloaded Test_SSR.zip and imported it with godot v4.0 alpha. It says the Main.tscn is corrupted and cannot be opened. I did download a straight-up binary from the mirror and everything seems to be very buggy and everything is clipping and stuff, maybe it will work if i compile it from source? I don't know, did you compile from source, or did you download just the executable like me?
![Corrupted Main-Tscn](https://user-images.githubusercontent.com/85007222/160138677-cbb2277e-2997-4dd1-b828-941bff1accf9.png)

**Comment by PZerua** [comment]
You are opening the project with Alpha 1 and some things changed since then. Try again with the latest Alpha 5. If that doesn't work either try deleting the .godot folder.

**Comment by ComputehGuy** [comment]
After opening it with godot 4.0 alpha 5 it does give me a warning before opening the scene that the scene has invalid/corrupt entities in it, but it opens anyways for some reason. Here after hitting F5 and previewing the scene the floor box seems to be glitching a lot with black lines. It seems to have to do with the resizing of my window because even if I don't move in the
Test SSR(DEBUG) the black lines change with the size of my window.
Window at full size:-
![The scene is glitched](https://user-images.githubusercontent.com/85007222/160225271-fdfdd8cb-9489-42c5-9618-6cf7191630dc.png)

Window has been resized:-
![Black lines have changed](https://user-images.githubusercontent.com/85007222/160225280-84671f45-b43c-49ca-bee1-d773b1975916.png)

Also, I don't seem to get any of those black speckles you got. Any idea why?

gpu : Intel Iris Plus Graphics 655
Supported vulkan extensions (which is probably unnecessary) :
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6

**Comment by lewiji** [comment]
Possibly related: #59015 

I included some videos there of a few different StandardMaterial3D settings that didn't really work with SSR/SDFGI, and one that does with a shader that manually discards alpha (but never sets the `ALPHA` built-in). That was for alpha backgrounds on textures, but not necessarily actual transparency/translucency in materials.

**Comment by PZerua** [comment]
@ComputehGuy I'm not getting this invalid/corrupt warning, that's weird. Also for some reason in your image I can see the material doesn't have transparencies enabled, try setting transparency in the "Succulent" material to Depth-Pre Pass.

**Comment by PZerua** [comment]
I have updated the minimal reproduction project link to Alpha 8 and I can confirm it's still happening. Looking at the code changes of the "Initial TAA implementation" (#61319), it seems like JFonS is changing the FINAL_ACTION_DISCARD to a FINAL_ACTION_READ [here ](https://github.com/godotengine/godot/pull/61319/files#diff-cff00d5ca58d233af4e4590bfa182d3f6a10b10e9f9aaecbd6e8907efc259fbaR445) as I described in the issue, so problably it will be fixed after merging.

**Comment by PZerua** [comment]
I can confirm it is fixed with https://github.com/godotengine/godot/pull/61319.

**Comment by clayjohn** [comment]
Closed by: #61319
