### ISSUE TITLE
Set_owner duplicates instance children in the editor (tool script)

### ISSUE THREAD

**Issue by atngames** [godotengine/godot#59625]
### Godot version

3.5 beta1

### System information

linux

### Issue description

If I set the owner of a child in a PackedScene, this child will duplicate in my instance each time it is called

![screenshot](https://user-images.githubusercontent.com/56628137/160368331-0fc4a062-bded-4ed9-9df1-83256d22834e.png)

(See? Two nodes with the same name !!!)

### Steps to reproduce

Create a new Node
Add a child Node
Save this child as a Scene
Attach to the packedScene the script containing:

```
tool
extends Node


func _ready():
    for c in get_children():
        c.set_owner(get_tree().get_edited_scene_root())
```

Add a child to this PackedScene

Reload the project a few times

### Minimal reproduction project
[test_owner_bug.zip](https://github.com/godotengine/godot/files/8361537/test_owner_bug.zip)

**Comment by atngames** [comment]
Woops sorry, two very similar names.
I did edit the issue, thanks for noticing

**Comment by KoBeWi** [comment]
Thanks. This is not a bug. When you have instanced scene, its child nodes' `owner` point to the root of the instance. If you change it to the root of the main scene (the one where the instance was placed), the nodes will now change ownership from the instance to the main scene. But instance still has these nodes, because you didn't edit the original scene, so they reappear after reload.

The only bug is being able to have 2 nodes with the same name, but this is covered by #26390

**Comment by atngames** [comment]
Ok thank you for the explanation
