### ISSUE TITLE
Backport fix for Tween final values

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#59649]
### Godot version

3.x 11d40d7

### System information

Windows 10 x64

### Issue description

This PR can be backported to 3.x: #59571
It couldn't be cherry-picked, because Tween code changed almost completely. This particular part is mostly unchanged though and still relevant for Godot 3.

### Steps to reproduce

See this issue #33813

**Comment by KoBeWi** [comment]
When the Tween is finished, just assign the `data.final_val` value. This is how 4.0 Tweens do it.

**Comment by esensar** [comment]
Issue with that approach for 3.x version is that final val is converted to float (and it is integer intially) and in that process it loses the original value. I don't think I saw such conversion in 4.x, but then again, I am not sure if removing it here would break some current code.

Just assigning `final_val` would work for some cases I guess, but not for the one provided in the original issue (since in that case, wrong value is generated right away, since float can't store 999999999 and as noted in the original issue, it works if using double as float).

**Comment by KoBeWi** [comment]
Ah, I don't know if final value type is important. Maybe we could just store the original one too, so there is `data.final_val` and `data.final_val_original`.

**Comment by esensar** [comment]
Yeah, I thought about it too, but figured it may be weird receiving notifications of different types (especially if static typing is used in GDScript), because all notifications would be integers, except for last one which would be float.

**Comment by KoBeWi** [comment]
Not sure what you mean by notifications. If a float value is provided for some callback, but the argument type is int, it will just be implicitly converted (to the value the user expects). Same thing would happen if you e.g. animated `frame` property of sprite.

Not sure why the conversion is done in the first place tbh, the old Tween system wasn't very good and had some stuff that doesn't make sense.

**Comment by esensar** [comment]
Sorry, this is my first attempted contribution and I am not very familiar with the specifics. If these different types are fine, then yeah, I agree that storing original final value would be the best, since it would have the least impact on other cases.

If that is fine then I can proceed with that approach to fixing this.

**Comment by KoBeWi** [comment]
Seems like this wasn't as simple as expected (I think?). The new Tweens were backported and they don't have this problem, so closing.
