### ISSUE TITLE
Android editor crashes on saving a scene

### ISSUE THREAD

**Issue by foureyedredheadedstepchild** [godotengine/godot#59719]
### Godot version

3.5 beta 3

### System information

Android 11, Samsung A32 5G

### Issue description

When saving a scene the editor crashes. 

### Steps to reproduce

Created a new project. 
Set it to be a 3d scene.
Changed the name of the Spatial node.
Saved the scene.  (Tried with and without adding a script)

**Comment by NumbuhFour** [comment]
I also frequently hit this crash on my Samsung Note10+. Android 12
Godot Version: v3.5.beta3.official [3c0d32562] (apk downloaded from blog post)

[godot_androidcrash.log](https://github.com/godotengine/godot/files/8421602/godot_androidcrash.log)
Here's a log in case it helps. What I did during this capture was as follows:
- Open the editor
- Select my project in the project manager
- Click Edit
- Click Scene > Save 
- Click Scene > Save (it didn't crash the first time, but did the second)

**Comment by Henner25** [comment]
For me, the editor crashes every single time a scene is saved. Interestingly, the scene is still written to the disk because when I reopen the editor, it loads correctly.

I'm running /e/-os on a Fairphone 4 (build number "e_FP4-userdebug 11 RQ3A.211001.001 eng.root.20220726.061619 dev-keys")

Regarding Godot, I have tested the latest stable 3.5 release, the latest 4.0 alpha release (15) as well as the latest 3.5.1 RC: v3.5.1.rc1.official [293c3844b].

I'd really like to help with the bug. Unfortunately I don't even know where to get the Godot error log that @NumbuhFour included. My phone is not rooted so I cannot access `/data/` (I expect the log to be there?).
I _did_ get a "tombstone" (core dump?) of the crash using `adb bugreport`. Is that useful to anyone? Does it contain sensitive data?

**Comment by Culain** [comment]
This is still an issue on Android 12 (4.14.186-gb658b7746380)
with Godot Editor 3.5.1 stable.

**Comment by m4gr3d** [comment]
Issue is no longer reproducible in the latest 3.6.x version of the Godot Android Editor.
