### ISSUE TITLE
2D viewport is not fully cleaned up when closing scenes

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5977]
**Operating system or device - Godot version:**
Mageia 6 x64, Godot 2.1 RC1.

**Issue description** (what happened, and what was expected):
When closing a 2D scene in the editor, some visual elements like the lock icons stay visible. Compare these two screenshots (before / after):
![spectacle fw7886](https://cloud.githubusercontent.com/assets/4701338/17272723/5fd01c7c-569e-11e6-81cf-907e157bdadd.png)
![spectacle nt7886](https://cloud.githubusercontent.com/assets/4701338/17272726/68b1309c-569e-11e6-8269-925fa2fae6cd.png)

**Comment by Zylann** [comment]
That's because the `lock_list` is refreshed only when scrollbars are updated in `_update_scrollbars()`. When the scene closes, scrollbars don't need to be updated, but then locks aren't refreshed.

**Comment by Zylann** [comment]
I found _update_scrollbars() is also called in set_state(), if the state contains "ofs"... no idea what this is. But this happens very rarely, I wonder if it can actually be removed because it seems to happen as a duplicate.

![set_state_update_scrollbars](https://cloud.githubusercontent.com/assets/1311555/17874679/8bdf20b0-68cd-11e6-846d-37c519d52cd9.png)

The other case where _update_scrollbars is called looks correct when more than one scene is open:

![update_scrollbars](https://cloud.githubusercontent.com/assets/1311555/17874716/c6a1039e-68cd-11e6-9924-202ebb85868d.png)

But when I close the last scene it isn't called at all.
Day 2, still no clue why :D

**Comment by rivten** [comment]
So I tried to lead an investigation today. It indeed boils down to "no `CanvasItemEditor::_viewport_draw` call is made after the last tab is closed" in the `CanvasItemEditor`.

It seems to me that we should update the `CanvasItemEditor` from `EditorNode::_remove_edited_scene` call which is called from `EditorNode::_scene_tab_closed` after the close button is clicked. Indeed, the `_remove_edited_scene` call ends with the following

`_update_title();
_update_scene_tabs()`

Maybe we could also add a `_update_viewport` call or something in this case (the case where we close the last tab) to force the scrollbar and therefore the locks to update.

But I don't know much about the flow of all this, maybe there is a more elegant solution. To me, it already seems pretty weird that the locks are updated only when we update the scrollbars.

**Comment by Zylann** [comment]
Technically, the locks are actually updated when the viewport is updated, which also happens when you add or remove them. But for some reason it has been put inside _update_scrollbars(). The function is either badly named or should not include this.

We can force the update from _remove_edited_scene() of course, but I wonder if it should actually happen automatically on a lower level, or if it's really something specific to call. Because to me, the viewport is indeed updated, otherwise we would still see remnants of the previous scene. But the editor just doesn't gets the event in this case. Why should we explicitely call editor update then? Maybe it's currently connected to the wrong object?

**Comment by akien-mga** [comment]
Can someone check if this issue is still valid in the current master branch?

**Comment by Zylann** [comment]
I saw it happen in 3D too, althought it could be a separate issue

**Comment by Zylann** [comment]
Otherwise it seems to be fixed in 2D
