### ISSUE TITLE
Font / Inspector

### ISSUE THREAD

**Issue by tolgaprg** [godotengine/godot#59790]
### Godot version

v4.0.alpha5.official [d7d528c15]

### System information

Linux Mint 64-bit NVidia GeForce GT650M

### Issue description

Font > Inspector not shown correctly

### Steps to reproduce

new project
create label
inspector -> Theme Overrides -> Fonts => "New Font"
Data => "New FontData"
shows name/value underscores

### Minimal reproduction project

![scrshot](https://user-images.githubusercontent.com/56676411/161278653-46628e3f-0912-47c8-ba42-039d59224923.png)

**Comment by bruvzg** [comment]
> shows name/value underscores

It's not name/value, but font preview, "underscores" is font baseline, and with empty `FontData` it's not showing any chars, since there's none to show.

<img width="414" alt="Screenshot 2022-04-01 at 17 04 06" src="https://user-images.githubusercontent.com/7645683/161279658-c3bee532-1a15-42c4-8f37-1a38fc8828f8.png">

**Comment by tolgaprg** [comment]
sorry for your time, thank you.
