### ISSUE TITLE
'get_global_transform: Condition "!is_inside_tree()" is true. Returned: get_transform()' when a scene has NavigationObstacle2D

### ISSUE THREAD

**Issue by hilfazer** [godotengine/godot#59833]
### Godot version

3.5 beta 3

### System information

Windows 7 SP1

### Issue description

I'm getting 'get_global_transform: Condition "!is_inside_tree()" is true. Returned: get_transform()' errors when a scene i run has NavigationObstacle2D. I didn't see those errors in 3D version.

The number of those errors depends on number of sibling CollisionShape2D nodes in as well as on node order.

### Steps to reproduce

Run the MRP.

### Minimal reproduction project

https://downgit.github.io/#/home?url=https://github.com/hilfazer/Projects/tree/EngineIssues/Godot/EngineIssues/Obstacle2DIsInsideTreeErrors_godot35

**Comment by rburing** [comment]
After https://github.com/godotengine/godot/pull/59848, a workaround is to place the `NavigationObstacle2D` node *below* all of its `CollisionShape2D` siblings.

Still, a better fix is needed.

**Comment by smix8** [comment]
When `estimate_radius` is enabled on the NavigationObstacle2D/3D node as soon as the node joins the SceneTree and finds a valid parent node it will attempt to collect all parent childnodes that are CollisionShape2D/3D to calculate the radius value.

When the the NavigationObstacle2D/3D node is higher in the SceneTree order than the CollisionShape2D/3D those nodes are not loaded inside the SceneTree so the global_transform() function fails.

Instead of a generic red error message should ignore those nodes if they are not in the SceneTree and print a configuration warning.

Solution is to disable `estimate_radius` and set a manual radius so no nodes are collected or to move the NavigationObstacle2D/3D in the correct position which is below all the collisionshapes in the SceneTree order.
