### ISSUE TITLE
FileDialog directory selection is misleading

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#5989]
**Operating system or device - Godot version:**
Mageia 6 x64, Godot 2.1 RC1

**Issue description** (what happened, and what was expected):
The way FileDialog wants users to select folders is relatively misleading. A good example is the FileDialog used when clicking on "Scan" in the project manager.

- First situation: Folder selected, but current folder is its parent
![spectacle lh1262](https://cloud.githubusercontent.com/assets/4701338/17278505/23ebdcd4-575f-11e6-8c59-f69c44c2bc37.png)
If I click "Open", the contents of the `kobuge` folder will be scanned, and not that of the `juck` folder, even though one could expect that when clicking "Open" after having selected the target folder.

- Second situation: What the FileDialog expects is that the user opens the folder first in the FileDialog, before clicking "Open". This leads to this situation:
![spectacle tq1262](https://cloud.githubusercontent.com/assets/4701338/17278512/55dffcac-575f-11e6-8af0-e1edb72b6a38.png)
Here clicking "Open" will properly scan the contents of the `juck` folder, even though the selected entry is `..`, i.e. its parent folder.

It would make more sense IMO that clicking "Open" opens the selected folder instead of the currently browsed one; if no folder is selected (e.g. if it's a file that is selected when a folder is expected, or maybe (to be discussed) if the `..` entry is selected), the current behaviour (opening the cwd) could be used.

**Comment by vnen** [comment]
Also, the "File" field should be filled with the current selection (and maybe renamed to "Folder").

**Comment by TheKK** [comment]
Hi, I'm interesting in contributing to Godot. May I take this one as my first one?

**Comment by akien-mga** [comment]
@TheKK Sure! You'll want to have a look at `scene/gui/file_dialog.cpp` and likely `tools/editor/editor_file_dialog.cpp`.

**Comment by TheKK** [comment]
I've browsed `scene/gui/file_dialog.cpp` a while and have some rough thought. Here's what we have in `FileDialog`, currently:

- `Path` LineEdit, path which would be synced with tree below
- `Directories & Files` Tree, where we get path string from while pushing `Open` button
- an event from `FileDialog::tree`, `cell_selected`, which tells us which item is selected

And here's my candidate solutions:

- concatenate `FileDialog::dir_access->get_current_dir()` with selected item in tree, then pass it as result of FileDialog when FileDialog is in MODE_OPEN_DIR

To make this happen, we need to add `.(current directory)` into tree so that we can select it.

What's your opinion on this solution?

**Comment by TheKK** [comment]
So I made a [change] to let `file_dialog` append selected directory name under "MODE_OPEN_ANY" and "MODE_OPEN_DIR". And show `.` in the tree list so that we can still select current working directory.

What do you think about this solution, @akien-mga 

[change]: https://github.com/TheKK/godot/compare/77cb836fc4110a19bdba1d74928a6343fbca7f05...TheKK:issue5989
