### ISSUE TITLE
C# SetDragForward

### ISSUE THREAD

**Issue by LadyDefile** [godotengine/godot#59899]
### Godot version

v3.4.3.stable.mono.official [242c05d12]

### System information

Windows 10, C# 10, Ryzen 5, 3060 ti

### Issue description

There is an issue with Control.SetDragForward(), specifically in how it handles the forwarding. You have to snake_case your C# methods to use drag forwarding so you end up with three functions cased differently than the rest of your entire file.

`Control.SetDragForward()`
requires `private object get_drag_data_fw( Vector2 vector, Control control )`
instead of `private object GetDragData_FW( Vector2 vector, Control control )`.

### Steps to reproduce

Use Control.SetDragForward() in C#.

**Comment by LadyDefile** [comment]
Well, you can probably do what I ended up doing. I created a wrapper method My code looks something like this
```cs
private object get_drag_data_fw( Vector2 vector, Control control ) => this.GetDragDataForward( vector, control);
protected virtual object GetDragDataForward( Vector2 vector, Control control ) { return null; }
private void drop_data_fw( Vector2 position, object data, Control control ) => DropDataForward(position, data, control);
protected virtual void DropDataForward( Vector2 position, object data, Control control ) { }
private bool can_drop_data_fw( Vector2 position, object data, Control control ) => CanDropDataForward( position, data, control );
protected virtual bool CanDropDataForward( Vector2 position, object data, Control control ) => false;
```

Of course, in the Godot base code you may want *both* to be protected virtual methods.

**Comment by LadyDefile** [comment]
I have this in a base class of my own creation then any classes that inherit from this can call SetDragForwarding and it calls the method in the base class which calls the pascal-cased method in child classes.

**Comment by neikeq** [comment]
Although, this affects C# and other language bindings, this issue cannot be fixed by those bindings.

`can_drop_data_fw`, `drop_data_fw`, and `get_drag_data_fw` are not registered as virtual methods, and they're not called the way normal virtual methods are called for scripts.

The expected implementation should be the same as `can_drop_data`, `drop_data`, and `get_drag_data`.

--------

`get_drag_data` is registered as a virtual method in its declaring class:

https://github.com/godotengine/godot/blob/6d9cbcb05faabd03d0eb95dad39503cb2d5a9938/scene/gui/control.cpp#L2776-L2778

`get_drag_data_fw` is registered as a normal non-virtual method (cannot be overridden). Furthermore, it's not implemented in the declaring class, but rather in multiple subclasses like this one that want to override the method, like this one:

https://github.com/godotengine/godot/blob/6d9cbcb05faabd03d0eb95dad39503cb2d5a9938/editor/create_dialog.cpp#L746

--------

Notice the difference in which the two methods are called:

https://github.com/godotengine/godot/blob/6d9cbcb05faabd03d0eb95dad39503cb2d5a9938/scene/gui/control.cpp#L694-L711

Perhaps it's easier to understand with the 4.x version:

https://github.com/godotengine/godot/blob/9d3c8f04d4927bc464197a50fab3aca5a8355d98/scene/gui/control.cpp#L872-L883

--------

Fixing this won't be as simple as registering the methods as virtual and changing the way they're called. As seen with the `CreateDialog` example, many C++ classes seem to "override" this method in an unconventional way. The way that work will need to be changed as well.

**Comment by neikeq** [comment]
BTW, I think fixing this in 3.x is possible without breaking compatibility. The names `can_drop_data_fw`, `drop_data_fw`, and `get_drag_data_fw` don't need to be changed. When it comes to the scripting API, the method would simply be registered as virtual, which would in fact enhance the documentation as it would appear in the `Control`'s method list. All the other changes would be internal.

**Comment by reduz** [comment]
To be honest, this API should be changed to just use Callables in Godot 4 so we can avoid the problem altogether, but somebody would need to step up and do this work.
