### ISSUE TITLE
Resources from addons folder are not being properly imported to WebXR

### ISSUE THREAD

**Issue by mgrigajtis** [godotengine/godot#59949]
### Godot version

3.4.4

### System information

Windows 11

### Issue description

When creating a WebXR game, adding child instance scenes such as hand models and function like movement, teleport, and pickup do not function at all.  Hand models will not be visible and functions do not fire.

### Steps to reproduce

Create a new project and add hand and function child scenes from Open XR tools.  Export as a HTML app and run in browser.

### Minimal reproduction project

[XRTools_WebXR_Test.zip](https://github.com/godotengine/godot/files/8429124/XRTools_WebXR_Test.zip)

**Comment by Calinou** [comment]
cc @dsnopek

**Comment by dsnopek** [comment]
The models not importing thing is very strange! I'll look into this as soon as I can.

> function like movement, teleport, and pickup do not function at all

The functions not working, however, isn't that unexpected. The button ids are all different between OpenXR and WebXR, and so I wouldn't be surprised if some changes were necessary to XR Tools to make it fully compatible with WebXR.

**Comment by Calinou** [comment]
cc @the-o-king

**Comment by dsnopek** [comment]
The import settings on those model in XR Tools were fixed in https://github.com/GodotVR/godot-xr-tools/pull/118 (disabling vertex compression), and the axis/button ids can be converted using the feature added in #59994 which was just merged.

So, I don't think there's anything left to do here! I'm going to close this for now, but we can re-open if anyone thinks there's more work that should be done. Thanks, Everyone! :-)
