### ISSUE TITLE
`Input.MOUSE_MODE_CAPTURED` does not hide the mouse cursor and center it every frame on Android/iOS

### ISSUE THREAD

**Issue by gramfy** [godotengine/godot#60031]
### Godot version

3.5 beta 3 android editor

### System information

Android 11, GLES3, Mali-G57

### Issue description

I tried an fps game template project coz why not. I played it but when i play it, it doesnt hide my mouse cursor (using external mouse and also keyboard).

https://user-images.githubusercontent.com/79078329/162473562-aeb5dbda-84a0-4bda-9af5-e1f340d2eaa3.mp4

### Steps to reproduce

Run the android editor port and try to play fps example with external mouse

### Minimal reproduction project

[example project.zip](https://github.com/godotengine/godot/files/8456626/example.project.zip)

**Comment by Calinou** [comment]
I don't think `MOUSE_MODE_CAPTURED` was ever implemented on Android/iOS.

**Comment by Rkzy1** [comment]
Hi, sorry late 10h

> Guessing from the project, I don't think Input.MOUSE_MODE_CAPTURED was ever implemented on Android/iOS. It would be nice to support
Idk but look
https://developer.android.com/training/gestures/movement#pointer-capture

> Are there any Android/iOS games out there with full mouse and keyboard support (without involving touch emulation)?
Yes, Minecraft PE for example. They added full mouse and keyboard support (if i remember correctly android 8 below right click button will act as a back button instead of the actual right click function.)

> Please upload a minimal reproduction project to make this easier to troubleshoot.
I have school gotta send it later

**Comment by m4gr3d** [comment]
This issue has been resolved in the upcoming 3.6 beta build.


https://user-images.githubusercontent.com/914968/210089834-0bd0a8a7-85ea-4794-b606-3136f98a7f5d.mp4

**Comment by rpahut** [comment]
@AThousandShips Is this not an indication, right [there](https://github.com/godotengine/godot/issues/60031#issuecomment-3958881263). You meant to say I didn't jump the right hoops, that I did not.

So go ahead and ignore what I say if you will, but what is the actual evidence it works? Tests maybe? What I see hands on is it doesn't with the MRP provided with this report, nor with godot-demo-projects 3.5 . If it did in beta, that certainly didn't translate into the release.

See you have and always had all the pieces to deal with this bug. **You have it filed for you since 2022, MRP and all, and what.** Is not the reports what's lacking, but the **incentive and procedures to make good use of them**. Yes I do blame the "way you handle things". The way it somehow now my _job_ to come and prove there is an issue needing looking into, and my fault if I didn't, when in a sane world you'd work and organize things to never let the bug hapen in the first place. I don't know how else to say, this is crazy backward stuff. The worst I could do is show my approval.

**Comment by rpahut** [comment]
@m4gr3d I do not know about the bug enough to blame it on you personally, but the way this whole situation was and is being handled is undeniably ugly and I don't care what your code of conduct says. A piece of feedback - throw it into trash along with my person and my time wasted on it if that is what it takes for you to feel comfortable and accepted.
