### ISSUE TITLE
Progress Bar reverts to default minimial size when exporting

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6004]
**Operating system or device - Godot version:**
Godot_v2.0.4.1_stable_win64

**Steps to reproduce:**
Create a progress bar, uncheck the percent visible setting. Change the height of it to 8 (can only go lower than 13 when it's unchecked)

Preview the scene and you can see it's 8 pixels high. 
But, when you export your game, the progress bar resets back to a 13px height

This happens on Godot_v2.1_rc1_win64 as well

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
