### ISSUE TITLE
`cubic_interpolate()` does not consider the distance between keyframes

### ISSUE THREAD

**Issue by TokageItLab** [godotengine/godot#60154]
### Godot version

4.0.dev, 3.5

### System information

Any

### Issue description

`cubic_interpolate()` should adjust its speed according to the distance between keyframes, the current algorithm determines keyframes as if they were at constant intervals, resulting in slightly skewed transitions when keyframes with small distances are interspersed.

```cpp
static _ALWAYS_INLINE_ double cubic_interpolate(double p_from, double p_to, double p_pre, double p_post, double p_weight) {
	return 0.5 *
			((p_from * 2.0) +
					(-p_pre + p_to) * p_weight +
					(2.0 * p_pre - 5.0 * p_from + 4.0 * p_to - p_post) * (p_weight * p_weight) +
					(-p_pre + 3.0 * p_from - 3.0 * p_to + p_post) * (p_weight * p_weight * p_weight));
}
```

The above formula probably treats the `p_pre, p_from, p_to, p_post` times as `-1.0, 0.0, 1.0, 2.0`. It would be more correct to consider the time that the keyframes have actually. So `cubic_interpolate()` needs to receive times as an argument paired with values.

CC @fire 

### Steps to reproduce

Use cubic interpolation in Animation.

**Comment by fire** [comment]
https://github.com/godotengine/godot/pull/59707#issuecomment-1084145374 describes a way to interpolate between uneven key frames.

**Comment by GNSS-Stylist** [comment]
I have been using some kind of arbitrary interval cubic interpolation, based on this wikipedia article: https://en.wikipedia.org/wiki/Cubic_Hermite_spline . You can see this (not cleaned up) implementation here: https://github.com/GNSS-Stylist/godot/commit/659bfbc0e4e4ed473629441891b5f0f21b777c62
The actual interpolation code (for reals) is this:

[code]static real_t hermite_interpolate_real(const real_t y0, const real_t y1, const real_t y2, const real_t y3,
	const real_t x0, const real_t x1, const real_t x2, const real_t x3,
	real_t t) {

	// Everything here is based on this wikipedia article:
	// https://en.wikipedia.org/wiki/Cubic_Hermite_spline

	real_t h00 = 2.0 * pow(t, 3) - 3.0 * pow(t, 2.0) + 1.0;
	real_t h10 = pow(t, 3.0) - 2.0 * pow(t, 2.0) + t;
	real_t h01 = -2.0 * pow(t, 3.0) + 3.0 * pow(t, 2.0);
	real_t h11 = pow(t, 3) - pow(t, 2.0);

	real_t m0;
	real_t m1;

	m0 = 0.5 * (y2 - y0);
	m1 = 0.5 * (y3 - y1);

	// "Finite difference":
	if (((x2 - x1) == 0.0) || ((x1 - x0) == 0.0)) {
		m0 = 0.0;
	}
	else {
		m0 = 0.5 * ((y2 - y1) / (x2 - x1) + (y1 - y0) / (x1 - x0)) * (x2 - x1);
	}

	if (((x3 - x2) == 0.0) || ((x2 - x1) == 0.0)) {
		m1 = 0.0;
	}
	else {
		m1 = 0.5 * ((y3 - y2) / (x3 - x2) + (y2 - y1) / (x2 - x1)) * (x2 - x1);
	}

	return h00 * y1 +
		h10 * m0 +
		h01 * y2 +
		h11 * m1;
}[/code]

Quaternion uses this as component-wise interpolator. Otherwise quaternion code in this commit is horrible mess as it isn't cleaned up as in https://github.com/godotengine/godot/pull/63287

This commit also adds a new interpolation method into animation. Icon for it is just re-colored cubic interpolation icon because I had no idea how to differentiate between those and have no artistic skills either. How do you see this arbitrary interval version, should it be a new choice or just replace the old one? For backward compatibility perhaps?

I can make a some kind of demo and maybe clean up the code if you see this as a plausible way to go on with this(?)

Can the quaternion exp-map interpolation method ( https://github.com/godotengine/godot/pull/63380 ) modified to support arbitrary interval interpolation?

**Comment by fire** [comment]
I would replace because it takes major eefort to test variations of this code. The code should support equal spacing too.
