### ISSUE TITLE
Texture preview in the editor always uses filtering, even for very low-resolution textures

### ISSUE THREAD

**Issue by h0lley** [godotengine/godot#60150]
### Godot version

v4.0.alpha6.official [e4f0fc50f]

### System information

Ubuntu, Windows

### Issue description

For projects that use mainly pixel art assets, all previews are displayed blurry now.

Godot 3.5 to the left, and 4 alpha to the right.

![shrroms](https://user-images.githubusercontent.com/23386940/162809699-09c8dd9f-2da4-4c35-877b-363ebb918daa.png)

Since the filter setting is now no longer stored with the imported resource, perhaps it could be solved via an editor setting.
Alternatively, perhaps it could use different filters based on texture resolution.

### Steps to reproduce

1. In the FileSystem panel, double-click any low res pixel art sprite to preview it the inspecor
2. Notice it being blurry

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/57550 and https://github.com/godotengine/godot/issues/52332.

**Comment by riazey** [comment]
A few extra areas to tack on so it doesn't get missed in testing juuuust in case!

The blurriness affects shaders that are pulling color from a sampler2D which is small in size, like say a pixel color palette in a color replacement shader because it pulls the color from the blurred image~  (Including global shader params)

Using edit region on pixel art is a bit of a "guess which pixel is the edge" game~ xD
