### ISSUE TITLE
Label disappears in gles2 from gles3

### ISSUE THREAD

**Issue by Kakcalu13** [godotengine/godot#60179]
### Godot version

3.4

### System information

20.04, Mac os (M1 and intel) 

### Issue description

Label disappears in gles2. See here example in zip

I thought it was my setting, but then I learned that it was not supposed to be that way.

This issue is similar to https://github.com/godotengine/godot/issues/35755#issuecomment-1096790231

The difference is that my label disappears while that issue doesn't disappear.

### Steps to reproduce

1) Play the scene
2) See label exists in GLES3
3) Change the setting to GLES2
4) Play the scene
5) See it disappears.

### Minimal reproduction project

[delete_this.zip](https://github.com/godotengine/godot/files/8474255/delete_this.zip)

**Comment by Calinou** [comment]
The issue is that you enabled **Render Direct To Screen** on the Viewport node. This property only has an effect on GLES2, and it should _not_ be used for subviewports when you want the main viewport to be visible.

### GLES3

![image](https://user-images.githubusercontent.com/180032/163003719-3c3ca945-8bec-4f5f-b611-55c0791235fe.png)

### GLES2

![image](https://user-images.githubusercontent.com/180032/163003774-46c64956-891e-4d49-8baa-71b07d58319c.png)

### GLES2 with **Render Direct To Screen** disabled on the Viewport node

![image](https://user-images.githubusercontent.com/180032/163003976-110e058e-c707-4934-b35e-6813acb507c3.png)
