### ISSUE TITLE
Skeleton IK 3D Interpolation

### ISSUE THREAD

**Issue by Taiseibutsu** [godotengine/godot#60180]
### Godot version

4.0.alpha6.official [e4f0fc50f]

### System information

Arch Linux, Nvidia Geforce 1080Ti

### Issue description

Skeleton Ik 3D Interpolation does not assign the interpolation of the IK chain.
It assign it to 1 and only controls the override tip rotation.

https://user-images.githubusercontent.com/84092569/163007567-32a3a9c6-696b-4754-8dbf-402b9a77b478.mp4

<details>
  <summary>Rotation also seemed identical as override tip magnet solution</summary>
  
https://user-images.githubusercontent.com/84092569/162998518-d19a5d98-9109-4783-ab66-c0f220b506f9.mp4
</details>

### Steps to reproduce

Normal use of 
```Skeleton3D.interpolation``` or ```Skeleton3D.set_interpolation()```

### Minimal reproduction project

[skeleton3D_interpolation.zip](https://github.com/godotengine/godot/files/8474573/skeleton3D_interpolation.zip)

**Comment by Calinou** [comment]
Is the behavior in Godot 3.4.4 considered correct here?

**Comment by fire** [comment]
There is two systems for IK in godot engine.

The SkeletonIK3D is the older system. The newer system is pending modifications due to review by @lyuma  and @TokageItLab.

**Comment by TokageItLab** [comment]
@fire There is similar issue in #59554. CC @TwistedTwigleg

**Comment by lyuma** [comment]
I'll try and take a look at this, since I intend to keep SkeletonIK3D for 4.0 and it should be able to work the same as 3.5

My guess is these issues are casued by the change to make bone_pose include the bone_rest, while they were separate in 3.x

**Comment by lyuma** [comment]
Did a little experiment to port SkeletonIK3D to GDScript where the same bug can be replicated. It took only an hour or so.
[skeletonik3dimpl.gd](https://github.com/godotengine/godot/files/11503277/skeletonik3dimpl.gd.txt)

I know it doesn't solve this bug, but if I'm really stuck, my plan is to do the same to the 3.x implementation. it may be easier to replicate the same behavior or debug if I have both implementations side-by-side.

People weren't particularly fond of SkeletonIK3D in 3.x either, but it might be a starting point.

**Comment by lyuma** [comment]
I found the bug.

I'm attaching a zip with the test 4.1 project with SkeletonIK3D node, GDScript port of 4.0 skeleton_ik_3d and GDScript port of 3.x skeleton_ik_3d (the only difference is how the rest pose forward direction is calculated)
[skeleton3D_interpolation.zip](https://github.com/godotengine/godot/files/11506696/skeleton3D_interpolation.zip)

I already applied the bugfix to the gd files in the attached projects. Search for `if true:` and bring back the original condition or make it `if false` to reproduce the bug.

And finally, I performed a backport by hand of the tscn to 3.x so we can run it on the classic engine and confirm behavior is the same, which is now is.
[skeleton_interpolation_3.x.zip](https://github.com/godotengine/godot/files/11506700/skeleton_interpolation_3.x.zip)

The cause of the bug is `get_bone_pose_global_no_override` was inadvertently broken in 2021 due to a typo in the forward port of 3.x #48251 to master #48166 , and then the typo was concealed later in #51368 due to removing what then appeared to be duplicate code.

See the bug here in skeleton_3d.cpp
3.x:
```cpp
	if (b.parent >= 0) {
		b.pose_global = bonesptr[b.parent].pose_global * pose;
		b.pose_global_no_override = bonesptr[b.parent].pose_global_no_override * pose;
```
master:
```cpp
	if (b.parent >= 0) {
		b.pose_global = bonesptr[b.parent].pose_global * pose;
		b.pose_global_no_override = bonesptr[b.parent].pose_global * pose;
```
