### ISSUE TITLE
New project dialog that remembers your last folder 

### ISSUE THREAD

**Issue by therealrobster** [godotengine/godot#6020]
**Operating system or device - Godot version:**
I'm using OS X, but I suspect all would appreciate this

**Issue description** (what happened, and what was expected):
Every time I start a new project I have to head back to // then traverse through my folders to where I keep my GoDot projects. 

In my case it's: /Users/username/Documents/Development/Game Dev/GoDot/

That's a total of 6 double clicks every time.  It would be nice if it remembered the last location or even better, perhaps a favourite list of folder?  Recently used folders even?  Something to make it a little quicker.  

I hope the feedback is welcome.  Great work on GoDot, am very grateful for it and thank you all.

**Comment by vnen** [comment]
Note that there's an editor setting for a default project path.

**Comment by therealrobster** [comment]
Thank you!  I am still learning GoDot.  Perhaps I should learn some more before adding feature requests.  That's going to save a lot of time (the default project path).

**Comment by turtletooth** [comment]
Thank you @vnen  - that was a big help.  I was in the same boat.

**Comment by Skaruts** [comment]
Might it be worth considering adding a button to _Set Current Folder As Default_, to the new project's Browse window? I suppose that might be somewhat advantageous, namely because it's not obvious that this setting exists (I thought it was a bug, because I expected Godot3 to automatically remember it), but also because it might be kind of handy, considering there's no way to access the editor settings prior to opening a project.

**Comment by djrm** [comment]
a checkbox used for that purpose was there in previous implementations, but the behavior was confusing, since you usually choose the actual folder project and not its parent folder, so in order to select the correct default folder you have to open the file dialog twice, and it is quite easy to get this wrong.

**Comment by Skaruts** [comment]
I  see. I think I fell into that mistake myself, actually. Well, if you allow me another suggestion, what if the _New Project_ dialog had things separated, maybe along the lines of:
___
**Project name:**
[MyGame]
**Project Folder**
[C:\some\path\Godot\MyGame\]

**Default Projects path**
[C:\some\path\Godot\]
___
(I'm thinking the Project Folder might be editable, or simply reflect the Project Name)
Do you think that button could then exist without much confusion? (maybe even in this dialog, right next to the Browse button)

**Comment by rokit** [comment]
> Note that there's an editor setting for a default project path.

Editor > Editor Settings > Filesystem > Directories

**Comment by Anutrix** [comment]
But what if we want it to use last project location instead of a fixed default. Also, if rejected, is there a reason why this issue is still open? Or are we waiting for someone to PR with this feature?

**Comment by Calinou** [comment]
Closing, as the default project path can already be changed in the Editor Settings (in addition to the Autoscan Project Path).

If you can come up with a mockup to add a "set folder as default" button to the project creation dialog, you can open a proposal on the [Godot proposals](https://github.com/godotengine/godot-proposals) repository.
