### ISSUE TITLE
build ios in enabled bitcode build (improvement)

### ISSUE THREAD

**Issue by ret80** [godotengine/godot#6034]
**Operating system or device - Godot version:**
godot 2.x.x ios

**Issue description** (what happened, and what was expected):
Now Apple has added the ability to assemble projects included "bitcode". This allows you to not build the project under 2 different architectures and in the future to forget about the different architectures. Most of the advertising libraries already support this function. it would be great if Godot also had the opportunity.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by punto-** [comment]
what is this exactly? like pnacl?

**Comment by ret80** [comment]
http://lowlevelbits.org/bitcode-demystified/
https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

**Comment by samgreen** [comment]
I believe this is possible, but would require distributing the bitcode of the export templates with each release.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
