### ISSUE TITLE
Changing .import file externally doesn't trigger asset reimport

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#60730]
### Godot version

3.5 beta7 / 4.0

### System information

Windows 10 x64

### Issue description

When you change `.import` file externally, Godot won't detect this change. What's worse, you are left with the old imported file in your .import folder. This is not really a problem normally, but in team projects the .import file can be changed by git. This can cause bugs in exported project, like music not looping, because someone enabled loop and someone else made a build.

To fix this, you need to either manually reimport the file or delete the asset(s) from .import directory.

### Steps to reproduce

1. Open icon.png.import
2. Change e.g. repeat to true
3. Switch to editor
4. No reimport
5. Your texture doesn't repeat
6. Your texture doesn't repeat in exported project

**Comment by tbillington** [comment]
We've also seen this multiple times.

In our case I'd added a lightmapGI and changed the import settings on the environment models to `Static Lightmaps` and pushed the changes. When my team mate pulled he got the updated `.import` files, but his scene looked totally different because it was still using the generated file in `.godot/imported` from the previous settings. We had to nuke `.godot/imported` and reimport everything on the next launch to get back to the correct visuals.

**Comment by AsrielDewitt** [comment]
Holy shoot, this has been a problem since May last year, how come this hasn't been solved yet? because this issue would affect team project.

**Comment by AThousandShips** [comment]
Because no one has identified the cause of this or worked on it, you're welcome to look into it if you are interested 🙂

**Comment by KoBeWi** [comment]
> this has been a problem since May last year

This has been a problem since Godot 3.0 (so 5 years) and only wasn't reported until last year.
