### ISSUE TITLE
Ability to resize VS nodes 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6074]
**Operating system or device - Godot version:**
72748d1363d090f33d5ca6b9c00142b5e8f7d78f

**Issue description** (what happened, and what was expected):
Currently usually VS nodes takes a lot of space horizontally, while not so much vertically. 
![topdown1](https://cloud.githubusercontent.com/assets/6129594/17481558/19546f64-5d7e-11e6-9a39-a5f4aca940f8.png)

I think we could use this space better if we could resize VS nodes to have non standard sizes. In this scenario content of the VS node could be broken into multiple lines dynamically. 

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
in b276d92c8a63887df011032bc95d98bbb9c51c70 still valid

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
