### ISSUE TITLE
Warning: Your clang-format binary is the wrong version (14.0.0, expected between 12 and 13).

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#60778]
### Godot version

master (30f3c4255e506c25e3273906c01127f8614540bc)

### System information

Ubuntu 22.04

### Issue description

Similar to #49380, but I'm now getting the same message on Ubuntu 22.04, which includes clang-format 14.0.0:
```
Warning: Your clang-format binary is the wrong version (14.0.0, expected between 12 and 13).
         Consider upgrading or downgrading clang-format as formatting may not be applied correctly.
Files in this commit comply with the clang-format rules.
```

Clang-format 14.0.0 doesn't seem to break anything, so we can probably increase the maximum version number again.

### Steps to reproduce

On Ubuntu 22.04 copy the misc/hooks folder into your .git/hooks folder. Make a change, try to commit the change.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
There's a regression in clang-format 14.0.0 which actually breaks formatting on some files (notably core headers): https://github.com/llvm/llvm-project/issues/54901

It's fixed in 14.0.2, but so far most distros haven't picked up the patch releases for 14.0.x.

It's still usable despite the bug as long as you're not modifying a header that uses macros, so we can likely relax the warning (but CI should still use clang-format 13 until 14.0.2+ is available in the repos).
