### ISSUE TITLE
【Web3.0 is developing rapidly. Html5 doesn't work in IOS browser】

### ISSUE THREAD

**Issue by Atem1995** [godotengine/godot#60815]
### Godot version

3.x and 3.4.

### System information

window10, html5

### Issue description

Web3.0 is developing rapidly. Does Godot not optimize in the direction of web? At present, the Android support performance is general, and the IOS basically cannot run. Godot is an amazing game engine, but unfortunately it is not commercially available in HTML games.

### Steps to reproduce

#

**Comment by clayjohn** [comment]
Hi, this space is reserved for reporting bugs with the engine. If you have specific issue to report please do so either by opening a new issue or editing this one.

If you browse closed issues and pull requests you will see that a great deal of effort goes towards improving support for the web. But in order to fix issues, we have to know what they are.
