### ISSUE TITLE
Vulkan: BaseMaterial3D Proximity Fade exhibits a visible line regardless of distance if opaque surfaces are in front

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#60860]
### Godot version

4.0.alpha7

### System information

Fedora 34, GeForce GTX 1080 (NVIDIA 510.60.02)

### Issue description

BaseMaterial3D Proximity Fade exhibits a visible line regardless of distance if opaque surfaces are in front.

This looks similar to https://github.com/godotengine/godot/issues/54978, but happens even if neither VoxelGI nor SDFGI are enabled.

### Proximity Fade disabled

![2022-05-07_18 15 26](https://user-images.githubusercontent.com/180032/167263013-13c778c6-434f-48f0-8851-0acc647712d0.png)

### Proximity Fade enabled

![2022-05-07_18 15 31](https://user-images.githubusercontent.com/180032/167263016-05a67d20-6f83-40b8-b20e-e06d897aa5e2.png)

This also occurs without any lights or environment (although the difference is more subtle). You can notice it by <kbd>Ctrl + Tab</kbd>bing between those images opened in new tabs:

### Proximity Fade disabled

![2022-05-07_18 14 42](https://user-images.githubusercontent.com/180032/167263011-36b8e78c-082b-4fe2-b621-bcf3fd34f884.png)

### Proximity Fade enabled

![2022-05-07_18 15 01](https://user-images.githubusercontent.com/180032/167263012-6511ecbd-a094-4fbc-810e-640bdafd6ef9.png)

In comparison, there is no such visible line in 3.5.beta4's GLES3 renderer:

![2022-05-07_18 18 51](https://user-images.githubusercontent.com/180032/167263018-b20b2218-583a-4a52-a184-d8c5a9505275.png)

### Steps to reproduce

- Add a small mesh without any material override.
- Add a large mesh with a material that has Proximity Fade enabled (any distance will do).
- Place the large mesh behind the small mesh (relative to the camera).

### Minimal reproduction project

- `master`: [test_proximity_fade_line_master.zip](https://github.com/godotengine/godot/files/8645559/test_proximity_fade_line_master.zip)
- `3.x`: [test_proximity_fade_line_3.x.zip](https://github.com/godotengine/godot/files/8645558/test_proximity_fade_line_3.x.zip)

**Comment by somnathsarkar** [comment]
I took a look at the project in a frame debugger, and it seems like the issue lies in the computation of screen_uv.

Godot 3.x:
`vec2 screen_uv = gl_FragCoord.xy * screen_pixel_size;`

Godot 4.0:
`vec2 screen_uv = (gl_FragCoord.xy * scene_data.screen_pixel_size) + (scene_data.screen_pixel_size * 0.5);`

I don't believe we need to manually correct for the center of the pixel since gl_FragCoord returns the center by default anyway: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/gl_FragCoord.xhtml

Using an incorrect value of screen_uv causes the wrong texel of the depth buffer to be sampled, which is most noticeable at the boundary of another object. When I change this computation of screen_uv back to the Godot 3.x version, the black border disappears: 
![godot_proximity_fade](https://user-images.githubusercontent.com/22252865/168443747-00128c57-36ea-4747-9a38-cc4d5da0fd7b.PNG)


This also appears to fix the related issue: #54978

![image](https://user-images.githubusercontent.com/22252865/168443847-d7633704-d5d4-480f-96dd-ceeb6e6f2fa4.png)

**Comment by Calinou** [comment]
@somnathsarkar Nice catch :slightly_smiling_face: 

I wonder if this also resolves https://github.com/godotengine/godot/issues/56792.

**Comment by somnathsarkar** [comment]
The blur in #56792 is eliminated after applying the fix

Old screen_uv:
![godot_sdfgi_blurred_1](https://user-images.githubusercontent.com/22252865/168445994-e853f323-c071-47f7-88de-27f37cec6e61.PNG)

New screen_uv:
![godot_sdfgi_blurred_2](https://user-images.githubusercontent.com/22252865/168446000-29850f22-46b4-4754-b4a7-86b97edc27f5.PNG)

**Comment by Calinou** [comment]
cc @clayjohn
