### ISSUE TITLE
Project/Tools/C# shows no options

### ISSUE THREAD

**Issue by AntonioNoack** [godotengine/godot#60940]
### Godot version

v3.4.4.stable.mono.official [419e713a2]

### System information

Windows 10, GLES3

### Issue description

I followed the tutorial https://gist.github.com/paulloz/30ae499c1fc580a2f3ab9ecebe80d9ba to get code completion for VSCode, and got stuck in step 3.

When I click on "Project", and hover over "Tools", then "C#", no options are showing up. Obviously there shouldn't be an empty menu slot, even if maybe there no longer are these options. Or maybe they still exist, but are not showing up for me.

![image](https://user-images.githubusercontent.com/20659579/167791092-2de409ac-ea78-4902-9103-a390dd49dd8d.png)

I was able to reproduce it with a minimal setup, but got a slightly different appearance:
![image](https://user-images.githubusercontent.com/20659579/167792578-8fe2f60e-3b0e-4147-9d0a-56d4c96796fd.png)

This bug occurs on my desktop PC with Ryzen 5 2600, RTX 3070 and my laptop with Ryzen 7 4700U, integrated GPU; both are running Windows 10.

### Steps to reproduce

- create a new project
- create a new script via the built-in file explorer
  - use C# as type
- click on the menus, and go to Tools/C#
- the box is now empty

### Minimal reproduction project

This is one of the project, where the issue occurs for me:
[TestProject2.zip](https://github.com/godotengine/godot/files/8667641/TestProject2.zip)

**Comment by AntonioNoack** [comment]
Before adding any C# scripts to the test project, the box works fine (or it shows up; didn't test whether it actually works).

**Comment by kleonc** [comment]
1. Create new project.
2. ![gewq9bwK4V](https://user-images.githubusercontent.com/9283098/167829654-9a2d4866-8d07-44d9-b24d-f66dfcf91bde.png)
3. Click "Create C# solution".
4. ![Godot_v3 4 4-stable_mono_win64_NNAtVOBPdf](https://user-images.githubusercontent.com/9283098/167829831-f8172462-9f98-4ebc-9f62-8b7a4b7098e3.png)
5. Close and open project.
6. ![Godot_v3 4 4-stable_mono_win64_HDfd0Dea7s](https://user-images.githubusercontent.com/9283098/167830118-e4e72ef9-e2c4-4e7d-b56a-8f0e618f95f0.png)


Different look of empty lists is probably caused by PopupMenu not updating/recalculating its size after the item is removed. So that's one issue.

Besides that maybe "Create C# solution" should always be listed in there so the list won't ever be empty? It could be disabled in case solution is already created and text could be changed to something like "Create C# solution (already created)" so the user will know why it's disabled.

---

> I followed the tutorial https://gist.github.com/paulloz/30ae499c1fc580a2f3ab9ecebe80d9ba to get code completion for VSCode, and got stuck in step 3.

@AntonioNoack  To make things clear: in that version after adding C# script the C# solution is automatically generated (that's why this option evaporates from the menu). Meaning you're not stuck in step 3 of that tutorial, you're already past step 3.

**Comment by AntonioNoack** [comment]
"To make things clear: in that version after adding C# script the C# solution is automatically generated (that's why this option evaporates from the menu). Meaning you're not stuck in step 3 of that tutorial, you're already past step 3." Oh, thank you :).

**Comment by kreivi** [comment]
Having empty menu is very confusing for the user though. Would it make sense to have it grayed out or have "Refresh C# solution" or something like that instead when you already have the solution? Empty menu looks like it's bugged out.
