### ISSUE TITLE
AnimationNodeStateMachine can't add animation loaded from animation library due to "/" in initial node name.

### ISSUE THREAD

**Issue by tdaven** [godotengine/godot#60959]
### Godot version

Godot Engine v4.0.alpha8.official.cc3ed63af

### System information

Linux, 64-bit, Fedora 36, AMD RX 590, Vulkan

### Issue description

Trying to add an animation that has been save previous into an animation library fails to add the new animation node to a state machine.  The animations play fine on the AnimationPlayer or from a blend tree.

The following error is printed when trying to add an animation node:
     scene/animation/animation_node_state_machine.cpp:646 - Condition "String(p_name).contains("/")" is true.

The issue appears to be due to how the initial node name is chosen.  Since the animation name is built to be library_name/animation_name but the "/" is used internally by the state machine, it is not a valid character to include in the name.  

One possible solution is to sanitize the names and replace any invalid characters like "/" with something else.

### Steps to reproduce

1. Create 3D Scene
2. Add animation player
3. Add animation tree
4. Link player to tree
5. Load animation library (if not already present once can be saved)
6. Verify animation names are of the pattern library_name/animation_name
7. Add a state machine to the animation tree.
8. Try to add an animation to state machine by selecting an animation that matches the above pattern.

**Comment by permelin** [comment]
The animation tree is 100% broken in 4.0 at the moment but there is a **very** easy fix.

The issue is this line from when @reduz implemented animation libraries. It adds a slash to all animation names, which in turn breaks the animation tree which doesn't allow that.
https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L1200

If I change `/` to `|` there it fixes the problem. (There are a few more functions in this file that also adds the slash that need to be fixed.)

This bug is duplicated in #61640 and there are also PRs #62350 and #60960 that want to fix this by sanitizing the name inside the tree. But it must be better to simply not give all animations illegal names to begin with?

**Comment by permelin** [comment]
It's possible that changing the automatic animation naming is not the correct fix. Maybe Juan's intention is for these names to also work like paths. But then the animation tree state machine must be changed to accept those names.
