### ISSUE TITLE
Normal map is incorrectly compressed when using Basis Universal compression mode

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#61039]
### Godot version

4.0.alpha (992317957)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

Normal map is incorrectly compressed when using Basis Universal compression mode:

![image](https://user-images.githubusercontent.com/180032/168449293-d9736d25-c4c9-41cf-a9a4-52a31fdf4a7d.png)

This does not occur when using VRAM compression (which is S3TC on desktop platforms).

### Steps to reproduce

- Add a normal map to a material.
- Change its compression mode to **Basis Universal** in the Import dock, then click **Reimport**.
- Notice how the 3D rendering looks all wrong, and the normal map in the inspector preview is too green (the thumbnail may be outdated).

### Minimal reproduction project

https://github.com/Calinou/godot-test-basis-universal
(`.godot/` is included to avoid crashes due to Basis Universal importing)

The texture included in the MRP is https://polyhaven.com/a/mud_cracked_dry_03.

**Comment by lyuma** [comment]
Changing this code works around the problem:
modules/basis_universal/register_types.cpp
```
                        case Image::USED_CHANNELS_RG: {
 #ifdef USE_RG_AS_RGBA
-                               image->convert_rg_to_ra_rgba8();
-                               decompress_format = BASIS_DECOMPRESS_RG_AS_RA;
+                               //image->convert_rg_to_ra_rgba8();
+                               //decompress_format = BASIS_DECOMPRESS_RG_AS_RA;
+                               decompress_format = BASIS_DECOMPRESS_RGB;
```
It's disabling a major optimization to how normal maps are compressed, so I don't think this is a good fix, but it confirms that the issue is caused by the RG_AS_RA case.

I don't know quite enough about what's going on here to suggest a good fix yet, but we could apply the above to disable the RG_AS_RA workaround for 4.1 or 4.0.x until we learn more.
