### ISSUE TITLE
Logical folders in Project List

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6105]
Hello guys,
in a past weeks I collected a lot of demos and example projects for Godot and I have them all loaded to Project List. But having 50+ projects in the list became confusing and harder to browse (even though ability to favourite is useful). So I ask if it is possible to add logical folders to Project List so me and some other hoarders could better organize their projects.

**Comment by reduz** [comment]
Good question, I was thinking of maybe having categories or tags, or having
a project come with a default category but then allowing you to change the
tag to something you like?, I'm not sure.

**Comment by MrMaidx** [comment]
Custom tags could be nice aswell. :)
This arrangement of tags is what came to my mind right now so they could be used for searching in Templates library:
- primary: 3D, 2D, 2D&3D, ...
- secondary: demo, example, project, ...
- third level (user editable tags): platformer, RPG, controls, FPS, ... 
First two levels of tags might be selectable from predefined list of tags and the third could just have suggestions (maybe from tags already used in project uploaded to Templates).

**Comment by bojidar-bg** [comment]
Pretty bump, any updates here? (tagging as pr-welcome for all free contributors :wink: )

**Comment by nunodonato** [comment]
just to leave my (irrelevant) 2cents here:

for me this is totally a non-issue, I never felt the need to organize a projects list. Because you usually work in one (or very few) projects at a time. Its not like a photo album. I even remove projects which I consider finished, if I need them later I'll import again, but its so rare. I prefer a clean and usable projects list than a complex one full of hierarchies.

there's also a searchbox, which will probably filter faster what you need than (de)selecting categories or folders

**Comment by DriNeo** [comment]
Do you think that bundling all official examples projects into one, or a few projects, could be relevant ?

**Comment by nunodonato** [comment]
@DriNeo as far as I know, the official demos will be moved to the asset lib and users can download them on-demand

**Comment by eon-s** [comment]
I'm facing this problem, my solution is a different self contained Godot for different purposes, I can't test issues, do experiments and other things and work on my _serious_ projects on the same place, is a mess.

Also without project descriptions you are limited to search by project name and there is a point everything turns into trial and error :sweat_smile:

**Comment by nunodonato** [comment]
@eon-s I have 1 or 2 junk projects where I just go to test stuff out, there's no need to create yet another project just for testing something. That's why we have scenes which can run independently :)

Just spend 5seconds writing a good project name and it works wonderfully :)

**Comment by eon-s** [comment]
@nunodonato yes, I do that too but I can't do it for everything (because settings and other specific mess I do xD ).

I have mentioned description and project "tags" on another issue, that could help on the organization.

**Comment by Zireael07** [comment]
My projects are named "xxx xxx xxx prototype" and then after I create copies of it for whatever reason, I end up with several project with the same name (as far as the project list is concerned) but in different folders.

**Comment by vnen** [comment]
Of course, different people have different workflows. It just needs to be non-obstructive for the people who won't use it.

**Comment by Zireael07** [comment]
Folders/tags/renaming, either of the three would help massively.

**Comment by nunodonato** [comment]
@Zireael07 you can rename a project in its own project settings

**Comment by eon-s** [comment]
Imagine using Godot for a course, having class material and student projects = hellish project manager

**Comment by nunodonato** [comment]
create a "students" folder, then filter by path ;)

**Comment by eon-s** [comment]
@nunodonato path filtering is useless if does not accept multiple words, there is where tags are stronger.

**Comment by DriNeo** [comment]
I didn't find a way to clear the project list. If it is possible easily this could help to keep a clean project manager.

**Comment by Anutrix** [comment]
Just wanted to mention this. Sometimes the list of projects randomly gets reordered for me. Don't know why.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
