### ISSUE TITLE
Font outline is seen through the actual character

### ISSUE THREAD

**Issue by miv391** [godotengine/godot#61055]
### Godot version

v3.4.4.stable.official [419e713a2]

### System information

Windows 10, OpenGL ES 3.0 Renderer: GeForce GTX 1060 6GB/PCIe/SSE2

### Issue description

My goal is to fade out Label using AnimationPlayer. Animation is changing Label's Modulation to fully transparent. However, it seems that outline is seen through the actual character. This looks pretty ugly. Is this a bug or is this working as expected? Are there any other ways to fade out the label?

- First Labe's Modulation is `#ffffff`
- Second Label's Modulation is `#6cffffff`

![kuva](https://user-images.githubusercontent.com/49998025/168483721-9cdcb2d1-e0e4-4e9b-b348-1294d04f72b3.png)

### Steps to reproduce

- Add Label 
- Add custom font to Label
- Set Label's Modulation to partially transparent

### Minimal reproduction project

The example project doesn't contain AnimationPlayer, as animation is not needed to replicate this.

[font_outline.zip](https://github.com/godotengine/godot/files/8695412/font_outline.zip)

**Comment by Calinou** [comment]
This is expected, as the font outline does not actually contain the "background" of the character itself.

In Godot 4.0, you'll be able to use a CanvasGroup node to modify the opacity of the whole final rendering, rather than the individual font glyphs and its outline.

That said, it might be possible to fix this without CanvasGroup by combining the main font with the outline (using the outline font as the main font color) in the outline rendering. cc @bruvzg

**Comment by miv391** [comment]
As Calinou said, the desired effect can be achieved by putting the `Label` inside a `CanvasGroup` (tested with `v4.4.dev6.mono.official [1f47e4c4e]`) and changing its `self_modulate` instead of the `Label`'s `modulate` or `self_modulate` directly.

![Image](https://github.com/user-attachments/assets/dc529996-382e-471a-94f6-4c27afe2d0fe)
