### ISSUE TITLE
CharacterBody3D surface snapping does not detect WorldBoundaryShape3D

### ISSUE THREAD

**Issue by ShroudedMuridian** [godotengine/godot#61080]
### Godot version

4.0.alpha8

### System information

Windows 10

### Issue description

When a `CharacterBody3D` moves downward on a sloped plane created by an angled WorldBoundaryShape3D collision shape, the surface snapping function provided by the `floor_snap_length` variable does not function, causing the CharacterBody3D to "bounce" along the slope.

### Steps to reproduce

-In an empty project, create a StaticBody3D.
-Add a WorldBoundaryShape3D collision shape to it.
-Rotate the StaticBody3D 20 degrees to create an angled slope.
-Add a CharacterBody3D with the default template movement code and any type of CollisionShape.
-Start the project and use the arrow keys to move the CharacterBody3D down the slope,
-Observe the "bouncing" motion as the CharacterBody3D repeatedly breaks contact with the slope.

**Comment by rburing** [comment]
Here is a minimal reproduction project as described in the steps to reproduce:

- [BouncyWorldBoundary.zip](https://github.com/godotengine/godot/files/9419026/BouncyWorldBoundary.zip)

The flow of the Godot physics code is that `GodotSpace3D::test_body_motion` in its second phase (kinematic solving) calls `GodotCollisionSolver3D::solve_distance` with a `GodotWorldBoundaryShape3D` and a `GodotMotionShape3D`, which in turn calls `GodotCollisionSolver3D::solve_distance_world_boundary`. The problem is that this last method does not handle motion shapes at all (it calls `get_supports()` on the shape, which results in zero points for a motion shape).

It should be relatively easy to handle motion shapes in there, using the `get_support()` method instead of `get_supports()`. Detecting the motion shape in the first place seems to require `dynamic_cast` however (for the first time in the physics code?), as `GodotMotionShape3D::get_type()` returns `SHAPE_CONVEX_POLYGON` for some reason.

**Comment by Corruptinator** [comment]
Interesting...

**Comment by rburing** [comment]
Please confirm if my PR https://github.com/godotengine/godot/pull/64936 fixes the issue.

(See https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html for PR testing instructions.)
