### ISSUE TITLE
Moving node from other node's script results in crash without message

### ISSUE THREAD

**Issue by BelowAverageFish** [godotengine/godot#61081]
### Godot version

3.4.4.stable.mono

### System information

MAC OS, Macbook Pro

### Issue description

When attempting to apply a pushforce to my player's body from the script attached to the player's gun(a child of the body), I found that the game crashed immediately upon pressing down on the left mouse button. No error message, just a note saying "--- Debugging Process Ended ---". I tried a variety of functions and used both Position and GlobalPosition to no avail. It also occurred when attempting to modify the rotation of another node. I understand that I might not be going about this the right way, it would be nice if an error message was given on startup to illuminate how to fix this problem.

### Steps to reproduce

I've included the simplest project which has the bug below, the only lines of code are declaring a variable a node and attempting to change that node. Simply press play and it will instantly close, saying Godot closed unexpectedly on mac.

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/8699967/New.Game.Project.zip)

**Comment by kleonc** [comment]
>No error message, just a note saying "--- Debugging Process Ended ---".

You most likely have the error in the Debugger tab of the editor, check it out. In case of the provided minimal reproduction project (MRP) the error clearly states what's the issue:

```
E 0:00:02.713   void Node2D._Ready(): System.NullReferenceException: Object reference not set to an instance of an object.
  <C++ Error>   Unhandled exception
  <C++ Source>  path\to\project\Node2D.cs:9 @ void Node2D._Ready()()
  <Stack Trace> Node2D.cs:9 @ void Node2D._Ready()()
```

Why you're getting `NullReferenceException`? Because you've named your class `Node2D` and thus in this context `Node2D` refers to your custom class, not the the Godot's built-in class. And your child node `A` isn't your custom `Node2D` (it doesn't have such script attached to it) so the cast `as Node2D` returns `null` hence the exception on to next line. If you'd change:
```
public class Node2D : Godot.Node2D
{
    public override void _Ready()
    {
        Node2D a = GetNode("A") as Node2D;
        a.Rotation = 100f;
    }
}
```
to:

```
public class Node2D : Godot.Node2D
{
    public override void _Ready()
    {
        Godot.Node2D a = GetNode("A") as Godot.Node2D;
        a.Rotation = 100f;
    }
}
```
there will be no exception as such cast won't fail. So there's nothing wrong in the provided MRP (besides naming a custom class the same as some built-in class, it should be avoided).

I have no idea what's the issue with your original project. Maybe it's the same problem as in MRP, maybe some other user error, maybe an actual bug. Can't tell unless you'll provide a way to verify it.

Also you're using mono version so please provide that info next time (I've already edited the version in your comment).

**Comment by BelowAverageFish** [comment]
Thank you for the quick response. After changing it to use Godot.Node2D and reinstalling the godot, the problem was resolved. And the error message also worked after I re-downloaded it. Sorry for making my terrible computer your problem. Have a great day!
