### ISSUE TITLE
Auto scroll Input Map when adding new actions

### ISSUE THREAD

**Issue by saltares** [godotengine/godot#6121]
**Operating system or device - Godot version:**
Windows 10 Godot 2.1 Stable

**Issue description** (what happened, and what was expected):
I would like the Input Map screen to auto scroll to the bottom whenever a new action is added. It would make the workflow more efficient.

**Steps to reproduce:**

1. Open Scene -> Project Settings
2. Select Input Map
3. Add a new action
4. Scroll to the bottom and click + on the action to map it to a key/button etc

I guess this would be low priority but it would be nice.

**Comment by neikeq** [comment]
`Tree::ensure_cursor_is_visible()` is already being called after adding new actions. That should ensure the new action is completely visible. However, only half of the action is visible (vertically). This should probably be considered a bug rather than an enhancement.

On the other hand, a simpler solution (ignoring that possible bug) is to just set the vertical scroll to the bottom (`Tree` exposes `get_scroll` but not `set_scroll` though).

**Comment by ScotFlux** [comment]
Agreed. This would give a nicer workflow. 👍

**Comment by bojidar-bg** [comment]
@akien-mga So, it's both a bug and an enchancement? :laughing:

**Comment by neikeq** [comment]
@bojidar-bg We must enhance bugs! :laughing:

**Comment by akien-mga** [comment]
@bojidar-bg Well the issue @neikeq described is a bug, and the usability enhancement @saltares asked for is an enhanced, so I found fitting to keep both tags :)

**Comment by saltares** [comment]
Thanks a lot @volzhs!
