### ISSUE TITLE
Const arrays and dictionaries are static variables in diguise

### ISSUE THREAD

**Issue by Trioct** [godotengine/godot#61274]
### Godot version

4.0.dev (4173a4735eb1690132d30430f88fb7d2681c5727)

### System information

5.17.5-gentoo (Linux)

### Issue description

Any array or dictionary like `const x := [3,2,1]` acts like a static variable. If edited anywhere from any scope, function, or instance, `x` is permanently changed across every other use of it. This is because the compiler wants to substitute in constants for its identifier in code, where the constant is actually an address to a constants vector.

### Steps to reproduce

Example 1:
```gdscript
for i in range(4):
    const x := []
    x.append(i)
    print(x)
```
Expected: `[0] [1] [2] [3]`
Actual: `[0] [0, 1] [0, 1, 2] [0, 1, 2, 3]`

Example 2:
```gdscript
func test():
    const x := []
    x.append(1)
    print(x)

func _ready():
    test()
    test()
```
Expected: `[1] [1]`
Actual: `[1] [1, 1]`

Example 3:
```gdscript
class Test extends Object:
    const x := []
    # var x := [] also works here

func _ready():
    var test1 := Test.new()
    var test2 := Test.new()
    test1.x.append(1)
    print(test2.x)
    test1.free()
    test2.free()

    var test3 := Test.new()
    print(test3.x)
    test3.free()
```
Expected: `[] []`
Actual: `[1] [1]`

**Comment by ExplodingImplosion** [comment]
ngl this is something i been dealing wit for multiple months and just thought this was intentional LMFAO

**Comment by and3rson** [comment]
I found it very convenient to use `const` dictionaries to share data between instances of the script, like a node-bound global variable.

I really hope this is intended and won't change in the near future since:
- It eliminates the need of having some sort of `Global` singleton.
- It nicely encapsulates node-specific "global" variables without polluting the actual global scope.

**Comment by gokiburikin** [comment]
I just happened upon this behaviour and find it useful. Since it's marked as a bug, if I exploit this should I expect to have to rewrite whatever systems use it since afaik there is no static member variable implementation to replace it?

Similar to the above, I'm being a menace and using a const array to keep track of all instances of a custom class and a static function to be able to access the array from the outside (since accessing `LineTrailer._line_trailers` returns an empty array, furthering the case that this is indeed a bug):

```gdscript
class_name LineTrailer extends Object

const _line_trailers:Array[LineTrailer] = []

func _init():
	_line_trailers.append(self)

static func all():
	return _line_trailers
```

I'm likely breaking a bunch of conventions but it sure is convenient.
