### ISSUE TITLE
Ability for plugins to add entry under right mouse click context menu

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6128]
**Operating system or device - Godot version:**

**Issue description** (what happened, and what was expected):
Yesterday I wrote a plugin which potentially solves https://github.com/godotengine/godot/issues/4584 https://github.com/godotengine/godot/issues/4584 (it allows you to extend scenes easily). 
The problem is there is no way to add an entry to right click mouse button context menu, so I needed to put new button near the editor 'settings' button, which is not elegant and take space all the time. Besides I can imagine there will be more plugins which allows to perform operations on nodes selected in scene tree tab... 

In context menu I think there should be  subcategory for each plugin which would automatically unfold when mouse cursor is near:
![subcategory](https://cloud.githubusercontent.com/assets/6129594/17616491/5950fb60-6075-11e6-8b68-e5c049d9a1cf.gif)

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by TheHX** [comment]
I was thinking on something like this(I proposed it on #4276, for menu buttons) which is like i implemented on #6065, but with a new class.
I don't like the idea of creating a submenu for each plugin, it's strange have a submenu for a plugin that only needs one item. For this i prefer to manually add the items to the menu(The developer can choose to add a single item or a submenu) using exposed functions in the `EditorPlugin`:
```cpp
enum ContextMenu {
    CONTEXT_MENU_SCENE_DOCK,
    CONTEXT_MENU_FILESYSTEM_DOCK
    // And possibly others
};

void add_item_to_context_menu(ContextMenu menu, String name, Object *handler, String callback, Variant ud);
// And possibly other functions to add a item with a icon or shortcut.
void add_submenu_to_context_menu(ContextMenu menu, String name, PopupMenu submenu);
void remove_item_from_context_menu(ContextMenu menu, String name);
```
The way of where the menu will display the plugin item can be:
  1. The items are always added to the bottom of menu.
  2. Every item needs to have a category, every group of items between separators is a category, the developer will pass the items category with `category/My Item Text` or an additional parameter to in the function. New categories are added to the bottom of menu. This can be quite problematic to implement because the contextual menu of scene and filesystem docks are recreated before it's displayed, and all possible position needs to be documented, but this will create intuitive and elegant entries.
  3. Every contextual menu will have a submenu for plugins items, and it'll work the same way of the "Tools" menu API(#6065), this will prevent the contextual menus from getting too crowded.

**Comment by Hinsbart** [comment]
I suggest to also add an optional callback that allows for overriding whether or not the item should be instanced when recreating the context menu.
So the above example would change to:
```cpp
void add_item_to_context_menu(ContextMenu menu, String name, Object *handler, String callback, Variant ud, String can_instance_callback="");
```
This is useful for context-sensitive context menus (wow, what a sentence :p).
Say you have an EditorPlugin that operates on `TileMap` nodes, you wouldn't want the menu item to appear when right clicking on another node type.

**Comment by reduz** [comment]
kicking to 3.1

**Comment by bfloch** [comment]
I could use this for #15928 - A way to add a custom tools to scene_tree_dock context menu.

As is, the proposal seems to miss the ability to assign shortcuts. Any thoughts on this?

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
