### ISSUE TITLE
_integrate_forces not called when used Custom Integrator and set Mode to Rigid 

### ISSUE THREAD

**Issue by Mavhod** [godotengine/godot#614]
actually It called a few count in Rigid mode
In Kinematic mode is called one time only
in Character mode is called normal

**Comment by akien-mga** [comment]
If the issue is still valid, could you provided a test scene that reproduces the problem?

**Comment by touilleMan** [comment]
This bug is still present (I'm using a custom build of version cb39db0b02c2d69994e2cd523844a2a9d3087d85)

Enclosed is a small project showing the bug:
 - Pressing keyup should make the bird shit
 - If bird's RigidBody2D is set to "Static", pressing `keyup` now does nothing and bird.gd's `_integrate_forces` is not called anymore
 - If bird's RigidBody2D is set to "Character" (default setting) the behavior works as expected

[issue-614-showcase.zip](https://github.com/godotengine/godot/files/87655/issue-614-showcase.zip)

**Comment by reduz** [comment]
Yeah, this is expected. No force integration happens on static mode

**Comment by touilleMan** [comment]
Oups sorry, I've messed up with my explanations !

Forget my previous post and let start again:

In my example (I've updated it) there is a bird dropping guano each time you pressed `keyup`:
 - If `RigidBody2D` is set to `Character`, function `_integrate_forces` is called
 - If `RigidBody2D` is set to `Rigid`, `_integrate_forces` is no longer called
 - if I add `s.set_linear_velocity(lv)` at the end of `_integrate_forces`, then this function is called when the body is `Rigid` !

[issue-614-showcase-v2.zip](https://github.com/godotengine/godot/files/87681/issue-614-showcase-v2.zip)

**Comment by akien-mga** [comment]
@touilleMan I checked your detailed example, thanks for that.

The issue is that `can_sleep` is toggled on, so after a few frames with no action, the body in `Rigid` mode is put to sleep. If you press <kbd>Up</kbd> from the start, it should work as you expect it to, but it will stop working as soon as you make a little pause and let the body go to sleep. Setting `s.set_linear_velocity(lv)` forces the body to move, and thus prevents it from sleeping. So you should disable `can_sleep` if you don't want this behaviour.

As such, not sure if there's something to fix here or not :)

**Comment by akien-mga** [comment]
Maybe the documentation can be improved.

**Comment by akien-mga** [comment]
Junior documentation job.

**Comment by rminderhoud** [comment]
@akien-mga I've added a note to the documentation to point out this pitfall.
