### ISSUE TITLE
Make menu items in center alignment

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6141]
**Operating system or device - Godot version:**
Any OS - 2.1-stable

**Issue description** (what happened, and what was expected):
![capture](https://cloud.githubusercontent.com/assets/20664041/17642604/e21be524-6154-11e6-98ca-cf831d3ee464.png)

First time posting on GitHub and i don't know if i'm doing it right. I want to make the menu items in center alignment but i didn't find it. Is it possible from GDScript or is a future of low priority

**Comment by reduz** [comment]
No.. it's more like you are the first person to ever ask for this :P

Are there any common uses for this feature? Otherwise you could probably
put toolbuttons with click on press option in a vbox inside a popup to
achieve something similar

On Aug 13, 2016 6:57 AM, "Chrisanthos" <notifications@github.com> wrote:

*Operating system or device - Godot version:*
Any OS - 2.1-stable

*Issue description* (what happened, and what was expected):
[image: capture]
<https://cloud.githubusercontent.com/assets/20664041/17642604/e21be524-6154-11e6-98ca-cf831d3ee464.png>

First time posting on GitHub and i don't know if i'm doing it right. I want
to make the menu items in center alignment but i didn't find it. Is it
possible from GDScript or is a future of low priority

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/6141>, or mute the thread

**Comment by Chrisanthos** [comment]
Okk i 'll try other way but it will be nice :)

**Comment by volzhs** [comment]
`MenuButton` is used for menu and it shows `PopupMenu` when clicked.
So, this actually requests align mode with `PopupMenu`.
But `PopupMenu` has various feature.
![image](https://cloud.githubusercontent.com/assets/8281454/24909787/5961d4e0-1f00-11e7-8a86-c6e8572e275b.png)
Each item of `PopupMenu` can have icon, label and shortcut.
It could be mess if `PopupMenu` had align mode for label.

This issue can be easily done in various way.
I doubt if it's good to add align mode in `PopupMenu`

**Comment by nunodonato** [comment]
it would totally mess up the alignment of icons and shortcut hints.
Seems to also be a very specific use case, perhaps something to do manually when needed instead.

**Comment by aaronfranke** [comment]
Can you provide any examples of menu items being centered horizontally? Every program that I can think of has text elements aligned left (except for Arabic text which is aligned right).

I don't think this would be a desired change for most people. I suggest closing.

**Comment by Rriik** [comment]
I can give you an example: when your goal *isn't* making a conventional dropdown menu like you see in toolbars or whatnot. For instance I would like to have this list centered 
![image](https://user-images.githubusercontent.com/40471819/55641186-f6b1aa80-57d5-11e9-90d2-d2494ee8a0f1.png)
And it annoys me that I can't do that, especially since the popup menu was otherwise perfect for my use case and spared me of having to manually set up a whole control node tree just to get a menu to pup up when I press a button. Curiously though, I found out that (using the font and font size I set up in the theme of the MenuButton) I could actually get them to center by ticking the separator box on each item's properties.
![image](https://user-images.githubusercontent.com/40471819/55641372-78a1d380-57d6-11e9-98c5-843b0ef91791.png)
However, for some reason doing that both bugs the separator and disables the button so I can't actually use this hack for my purpose (I tried setting the separator style to an empty stylebox but the result is the same).

But yes, I would really prefer there to be an option to be able to set the position of the text of an item. There is no reason why it should be so complicated to setup since the node is *right there*. It's the opposite of intuitive. If the sole purpose of MenuButtons is displaying toolbars then at least rename the node to ToolbarButton, menu is a much broader word.

**Comment by Anutrix** [comment]
Is this really a junior job? We can remove that tag I think.

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
