### ISSUE TITLE
[3.5.rc2] iOS crash at startup

### ISSUE THREAD

**Issue by oeleo1** [godotengine/godot#61413]
### Godot version

3.5.rc2

### System information

iOS, iPhone

### Issue description

Crash at startup on the target. Same project runs well on previous versions. Suspect a Godot build problem.
![iOS_target_crash_3 5](https://user-images.githubusercontent.com/40200623/170281307-9719645b-5fa0-4d21-8e36-1cb8c403c99e.png)

### Steps to reproduce

Run an existing project on iOS

**Comment by akien-mga** [comment]
I suspect that I've been using Clang 14 from Fedora 36 by mistake against instead of a self-compiled Clang 13.0.1. This was causing issues for macOS so we solved it, but the iOS build container then still re-installed clang from Fedora 36.

I might have solved this after 3.5 RC 2 in https://github.com/godotengine/build-containers/commit/469fc4515c2281368b6738d1d56c6585734ea275 while doing what I thought was just a cleanup, but it's actually a critical bugfix.

I made a test build yesterday using this updated container, could you check if it works? It's a Mono build but it should work OK also with a GDScript project.

- macOS editor: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.5-rc2_mono_osx.universal.zip
- Templates: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.5-rc2_mono_export_templates.tpz (still uploading, might be ready in ~10 min)

**Comment by oeleo1** [comment]
I tried it but the exported project doesn't build in XCode - mono unresolved symbols. Not sure what to do with that...
![mono_unresolved](https://user-images.githubusercontent.com/40200623/170305699-47fe3e0e-b7f5-4b0b-b601-d416753b618f.png)

**Comment by oeleo1** [comment]
Putting up a C# extension would be too much for me at this point. I'll check the non-mono though when ready.

**Comment by akien-mga** [comment]
Here's a standard / non-Mono build:

- macOS editor: https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.5-rc2_osx.universal.zip
- Templates (macOS and iOS only): https://downloads.tuxfamily.org/godotengine/testing/Godot_v3.5-rc2_export_templates.tpz

It's still the same commit as 3.5-rc2 so the templates you already installed need to be uninstalled/overwritten. Since there's not all platforms in the .tpz I'm not 100% sure how it works but I think "Install From File" in the editor should still work to overwrite the existing templates. I would double check then that `~/Library/Application Support/Godot/templates/3.5.rc2/` does have files with timestamps that confirm that they are new. (You can also unzip the .tpz and place the files in that folder manually.)

**Comment by oeleo1** [comment]
This build works fine.

**Comment by akien-mga** [comment]
Awesome, thanks! I'll use the same container from now on so it should be fine in 3.5 RC 3.

I'll keep this issue open and pinned for the time being so that it's clear for others that 3.5 RC 2 is broken for iOS.

**Comment by akien-mga** [comment]
This should be fixed in 3.5 RC 3.

**Comment by oeleo1** [comment]
Yes, it is.

**Comment by Zireael07** [comment]
@silver978 can you open a new issue and attach the project in question?

**Comment by silver978** [comment]
> @silver978 can you open a new issue and attach the project in question?

I wanted to, but this project is a commercial product I made.
I am more than open to share any logs that can help btw.
