### ISSUE TITLE
Pausing causes various errors with `Area2D`s

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#61420]
### Godot version

4.0.dev (a534346)

### System information

Windows 10

### Issue description

If a body is within an `Area2D`'s `CollisionShape2D` when the scene is paused and resumed two things happen:
If the body is higher in hierarchy (behind the `Area2D`), all signals are disconnected from the `Area2D`.

https://user-images.githubusercontent.com/21325943/170354862-e9274c51-848d-47a2-9b4c-9cc1f4e47b36.mp4

If the body is lower in the hierarchy (in front of the `Area2D`), errors are written to the console.

https://user-images.githubusercontent.com/21325943/170354890-7fd076fc-691e-4fa2-a2ea-7f3badfa97f0.mp4

### Steps to reproduce

1. Create `CharacterBody2D` with collision.
2. Create `Area2D` with collision.
3. Connect `BodyEntered` signal for `Area2D`.
4. Pause and Resume game while body is inside `Area2D`.

### Minimal reproduction project

[CollisionBugGD.zip](https://github.com/godotengine/godot/files/8774446/CollisionBugGD.zip)
(converted to GDScript project)

**Comment by markdibarry** [comment]
Still present in f38ea254f3

**Comment by markdibarry** [comment]
More oddities found with the new pause system while testing:
Currently, some nodes/controls (ex: `Button`) will connect and fire signals (ex: `on_mouse_entered`) whether the scene tree is paused or node is set to `PROCESS_MODE_DISABLED`.
Other nodes, will not connect signals if the scene tree is paused in the same cycle, even if paused after the connection happens.
This can be unexpected and possibly impossible to work around, especially in common scenarios like menu stacks where only the highest menu should have processing/signals enabled.
These may be unrelated and worth separate tickets, but I'm unfamiliar with the internals, so I can't say one way or another.

**Comment by markdibarry** [comment]
Still present in 8a98110e
Updated MRP:
[PauseBug.zip](https://github.com/godotengine/godot/files/10366488/PauseBug.zip)

**Comment by hcoura** [comment]
I spent a while looking into this one, posting my findings here cause I am not sure what to do to fix:

### 1. Discrepancy in behaviour depending on who is on top 

Whoever is on top of the tree is the one "monitoring" for the other, then, when enabling/disabling the process mode code will follow different paths on [`_apply_disabled()`](https://github.com/godotengine/godot/blob/master/scene/2d/collision_object_2d.cpp#L228) and [`_apply_enabled()` ](https://github.com/godotengine/godot/blob/master/scene/2d/collision_object_2d.cpp#L256) resulting in different behaviours.


### 2. Signal's disconnection

There isn't in fact a signal disconnection, but by the way the area2d function monitoring bodies coming in and out, when that is on top of the hierarchy (thus monitoring) and you set `PROCESS_MODE_DISABLED` it doesn't get a callback saying the object is out. This makes it so this [counter](https://github.com/godotengine/godot/blob/master/scene/2d/area_2d.cpp#L185) doesn't get decremented, and when the object actually leaves the area [this](https://github.com/godotengine/godot/blob/master/scene/2d/area_2d.cpp#L213) is never called.


### 3. Why is the callback not called when Area2D is the one monitoring but not when it's `CharacterBody2D`

Back to 1., when `_apply_disabled()` goes the area route, this [function](https://github.com/godotengine/godot/blob/master/servers/physics_2d/godot_area_2d.cpp#L64) is called, particularly it calls for `get_space()->area_remove_from_monitor_query_list(&monitor_query_list);` in essence removing itself from the monitor_query_list and making it so the callback set for the leaving of the object to not be called on `call_queries()`.


### 4. Error log when `CharacterBody2D` is on top

I haven't really looked much to it, but this function has some comments on the counter that feels weird to me. https://github.com/godotengine/godot/blob/master/scene/2d/physics_body_2d.cpp#L366


---------
## Possible fix

On theory this would handle the worst reported issue, making sure all callbacks are handled before `set_space` does it's thing.

```c++
void GodotArea2D::set_space(GodotSpace2D *p_space) {
	call_queries();  // make sure to handle any callbacks before clearing the space
	if (get_space()) {
		if (monitor_query_list.in_list()) {
			get_space()->area_remove_from_monitor_query_list(&monitor_query_list);
		}
		if (moved_list.in_list()) {
			get_space()->area_remove_from_moved_list(&moved_list);
		}
	}

	monitored_bodies.clear();
	monitored_areas.clear();

	_set_space(p_space);
}
```

I am not opening a PR because this looks completely wrong, imo the way the process enable/disable is currently done is quite error prone and invites these quirks for specific cases.

**Comment by MetalChair** [comment]
The problem is that the Area2D is getting a new _body_inout event on unpause if the object is still in the Area2D. Because the body_map on the Area2D already has that object in it, it iterates the rc element. The iteration is done in line 195:
https://github.com/godotengine/godot/blob/c151d3231f8e5d207f64055c60c70967dd5351b5/scene/2d/area_2d.cpp#L195

What I'm confused about now is what situation would require us to count the same body multiple times on the same Area2D. A quick-and-dirty solution is to just check if the body is already in the body_map, but that completely eliminates the use of the rc iteration. I made this change locally and tested it and it resolves the issue. We could also just explicitly set the rc to 1 one on line 185 and eliminate line 195:
https://github.com/godotengine/godot/blob/c151d3231f8e5d207f64055c60c70967dd5351b5/scene/2d/area_2d.cpp#L185

I think there's two areas to further investigate:

1. Why does unpausing send a new inout event?
2. Is the rc element of BodyState used for reference counting? If that's the case, then in what instance would rc need to be anything other than a boolean?

**Comment by MetalChair** [comment]
It _looks_ like this system is supposed to implement reference counting for a scenario where multiple object are referencing the same body_map object, but the implementation of Area2D as it currently exists creates a body_map for each instance of Area2D.

I would need information from someone more knowledgeable about the physics engine as a whole, but it appears the only references to value.rc are within this specific function call.

This is also an issue in Area3D

**Comment by hsandt** [comment]
Same error as in https://github.com/godotengine/godot/issues/70848

However, trigger conditions slightly differed. I the bug above, I could only trigger in timeout callback (re-enabling at any time), or during process/physics process by re-enable node immediately in same frame as disabling.

It seems than manual toggle also triggers the bug in this demo, but I'm not sure of the exact conditions.

**Comment by hsandt** [comment]
@hcoura Thanks, I see now that your point "2. Signal's disconnection" may be the cause of https://github.com/godotengine/godot/issues/76219

**Comment by golfinq** [comment]
I think I found what causes the bug, it comes from `monitor_query_list` in `GodotSpace2D` being added to after an unpause which will erroneously trigger a call to  `Area2D::_body_inout` when  `GodotPhysicsServer2D::flush_queries` is called leading to `GodotArea2D::call_queries` which leads to `Area2D::_body_inout` finally leading to the reference count getting incremented incorrectly.

I'll try to copy the call stack which causes it:
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/main/main.cpp#L3488-L3490
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_server_2d_wrap_mt.cpp#L73-L75
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_physics_server_2d.cpp#L1282-L1284
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_step_2d.cpp#L255-L257
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_step_2d.cpp#L84-L86
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_area_pair_2d.cpp#L72-L74
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_area_2d.h#L162-L164
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_area_2d.cpp#L199-L201
->
https://github.com/godotengine/godot/blob/787259441abb7aa92a382ccf48591a70136f25f0/servers/physics_2d/godot_space_2d.cpp#L1099-L1101

I am not sure what the solution would be, so I am not opening a PR yet

**Comment by golfinq** [comment]
It happens when disabled because the monitor_query_list is emptied of the area when both paused and disabled (There is a call to `area_add_to_monitor_query_list` followed by a call to `area_remove_from_monitor_query_list`). I am still not sure how it all functions...

**Comment by Rindbee** [comment]
It takes two to make a collision. If either is disabled, collision will no longer exist. It should be noted that **unpair** will cause the area to eventually be added to `monitor_query_list`, although it may have previously tried to remove from `monitor_query_list`.

https://github.com/godotengine/godot/blob/ba54c34551d1bda5139515d74e7d614ccbc43cea/servers/physics_2d/godot_area_2d.cpp#L66-L68

If it is disabled in the order of A-B (Area-Body), the area will eventually be added to the `monitor_query_list`; if it is disabled in the order of B-A (Body-Area), the area will not be added to the `monitor_query_list` in the end.

https://github.com/godotengine/godot/blob/ba54c34551d1bda5139515d74e7d614ccbc43cea/servers/physics_2d/godot_space_2d.cpp#L1126-L1130

That is, in the above code, `monitor_query_list.first()` is different in the two cases. `Area2D::_body_inout()` will be called when A-B, but will not be called when B-A.

```
ERROR: Condition "p_elem->_root" is true.
   at: add (./core/templates/self_list.h:46)
```
For the error message during resumed. The body is **paired** with the area in place and becomes **active**. This causes the same body to be added to the `active_list` twice.

https://github.com/godotengine/godot/blob/4df80b0e629e25653a706f6721c13a1f9d1da368/servers/physics_2d/godot_area_pair_2d.cpp#L99-L101
https://github.com/godotengine/godot/blob/4df80b0e629e25653a706f6721c13a1f9d1da368/servers/physics_2d/godot_body_2d.cpp#L410-L412

**Comment by aniezurawski** [comment]
> Tested the new PR. While it doesn't fix the problem enough to close out this ticket, it's still a big step forward. However, I am curious if it is intentional that pausing/unpausing a scene causes enter/exit signals to retrigger in Area*D's. That is the current behavior, so unrelated to the referenced PR, but it's definitely problematic. My wonder is if it's more or less problematic if it does than if it doesn't.

I would expect signals to not be retriggered after unpausing. I'm imagine pausing as some kind of hole in Node's lifetime. It should not affect its behaviour. After unpausing it should stay at the exact same state it was when it was paused.

**Comment by MrWolfyer** [comment]
Hey, is there any workaround for this issue right now?

**Comment by llopis** [comment]
I have the same problem (body entered signal re-triggered after unpausing). That's a game-breaker bug for me, so I also hope for a fix soon. 
I tried hacking around it by sending my own signal before/after pausing and unhooking the Area2D signals, but it doesn't matter. As soon as I reconnect the Area2D signals after the processing is resumed, they still re-trigger.
Edit: I just realized this issue is closed! Is that a mistake, or is there another issue that more closely matches this problem?
