### ISSUE TITLE
Vulkan: Error spam when using Particles Billboard mode on a BaseMaterial3D in GPUParticles3D

### ISSUE THREAD

**Issue by DillonSteyl** [godotengine/godot#61516]
### Godot version

4.0alpha8

### System information

Windows 10, Vulkan, RTX 3060 Laptop GPU

### Issue description

When creating a GPU Particles system with a standard process material and setting the material to "particle billboard", the following error is spammed to log:
"Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline"
The particle rendering then seems to bug out (the material becomes black and the billboarding does not work at all).

Interestingly, this seems to be dependent on the _order_ in which things are done (see the Steps to Reproduce). Adding a new process material *after* the billboard mode is set up seems to fix the issue?

### Steps to reproduce

- Create a GPUParticles3D node.
- Add a Quadmesh to "Draw Passes - Pass 1".
- Change the Quadmesh material to a "New StandardMaterial3D"
- In the "billboard" section of this new material, change "mode" to "Particle Billboard"
- Godot will either crash or spam out the error "Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline"
- If I add a process material now, the issue resolves itself. However note that adding a process material **before** adding the billboard material will still result in the above error.

**Comment by akien-mga** [comment]
I can reproduce the issue on Linux with AMD GPU (Mesa RADV drivers) in 4.0 alpha 11.

**Comment by wacyym** [comment]
Yes, Material3D in GPUparticles is completly broken - this bug is reproducing while almost any parameter is changed in:
-transparency tab
-shading tab
-vertex color
-emission
-normal map
- etc...

Tested on Godot_v4.0-alpha14_win64, Vulkan Clustered, AMD Ryzen 5300U.
ERROR: Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline
   at: (drivers/vulkan/rendering_device_vulkan.cpp:7784)
ERROR: Condition "!shader" is true. Returning: RID()
   at: render_pipeline_create (drivers/vulkan/rendering_device_vulkan.cpp:6434)
ERROR: Condition "pipeline.is_null()" is true. Returning: RID()
   at: _generate_version (servers/rendering/renderer_rd/pipeline_cache_rd.cpp:60)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
   at: (drivers/vulkan/rendering_device_vulkan.cpp:7736)
ERROR: No render pipeline was set before attempting to draw.
   at: (drivers/vulkan/rendering_device_vulkan.cpp:7753)

**Comment by wacyym** [comment]
Seems its some sort of GUI bug? Because i found a workaround: create mesh and add material to it, separately in filesystem, then dragndrop this mesh into draw pass property and it works.

**Comment by warriormaster12** [comment]
This still seems to be an issue with 4 beta 13. Updating material while particlematerial is active still causes these errors and after that a crash.
