### ISSUE TITLE
[3.x] Support for saving multiple Images in BakedLightmap is not implemented properly.

### ISSUE THREAD

**Issue by gdlq** [godotengine/godot#61547]
### Godot version

3.5RC2

### System information

Windows 10, GLES3

### Issue description

Issue #58102 seems to be implemented incorrectly and doesn't create multiple baked .exr lightmap textures.
Currently still generates a single atlas at 2048x4096 but there should be two 2048x2048 textures.

This is how baked .exr atlas looks like:
![test](https://user-images.githubusercontent.com/96324738/171047854-54d308ce-1807-4530-99fb-996fefe9aea9.jpg)

### Steps to reproduce

Reproduction project contains baked lightmap in \bake\test.exr

### Minimal reproduction project

https://github.com/gdlq/test_lightmap_large_3.x/releases/download/3.5RC2/test_lightmap_large_3.5rc2.zip

**Comment by gdlq** [comment]
If you change lightmap scale for reflection.obj to 4x it woun't bake at all, producing same old **Failed determining lightmap size. Maximum lightmap size too small?**
[test_lightmap_large_3.x.zip](https://github.com/godotengine/godot/files/8800318/test_lightmap_large_3.x.zip)

**Comment by JFonS** [comment]
The multi-image implementation is working as expected. In your MRP project there is a very large mesh with a default lightmap size of 1094x1090. If you chose the 4x lightmap scaling option, the lighmap for that mesh becomes 4376x4360, so it breaks the 4096 limit. 

The multi-image atlases can only split different meshes into separate images, but it cannot split a single large mesh into smaller atlases. This could be implemented in the future, but it's not supported currently. For now, you will have to split your large mesh into smaller ones (which is also recommended for culling purposes).

**Comment by Calinou** [comment]
@godotengine/bugsquad I have to remind you that we have a [Code of Conduct](https://godotengine.org/code-of-conduct). Please stay constructive.

**Comment by JFonS** [comment]
@gdlq Yes, I tried baking atlases with multiple images, and it works exactly as intended. You just think multi-image atlases do something different from what they were designed to do.

I can see where the misunderstanding comes from, the `atlas_max_size` property name is not entirely clear, but before opening multiple issues and pointing fingers, you should try and see why things work the way they do.

The current implementation tries to fit as many meshes as possible in a single `TextureLayered` (limited by `atlas_max_size`) but this texture is then saved by stacking the various layers into a single image. That means `atlas_max_size` limits the size of the individual layers, but the height of the image file is only limited by the 16k pixel limit in `Image`. That is done to reduce file clutter in the project, since it really makes no difference to the renderer how the texture slices are saved.

If you have a need or a valid use-case for limiting the size of the actual images instead of the texture slices, you can open a proposal over at https://github.com/godotengine/godot-proposals, but your attitude here is starting to get out of line.

**Comment by gdlq** [comment]
I honestly think that the max height should not be set to 16k by default, this just defies the whole point of atlas creation.
@JFonS You’ve done an amazing job fixing 16k limit in lightmapper, but if we opt for atlas bake we should respect width and height set by the user.
I’m really looking forward to hear some arguments why this is done this way and why height is fixed to 16k, I feel like I’m missing something here and I’d love to know more.
Thanks.

**Comment by Zireael07** [comment]
@gdlq; Some video cards just won't work with an image bigger than 16k

**Comment by JFonS** [comment]
@gdlq As I mentioned in my last message, the 16k limit comes from the `Image` class, because it stores data in a `Vector` and it has limited size. The lightmapper stores as many atlas slices as possible into this limited space before creating a new image. This is done in order to keep the number of files low. This is just a choice on how the data is stored into files, we could just as well split the data into smaller images, but I still don´t know why you want to do that.

Lightmaps are just a chunk of data that you typically don´t edit or interact with, so I don't see what are the benefits of splitting the atlas into smaller files. Do you have a specific reason for wanting that?

**Comment by fire** [comment]
@lyuma Do we have any scenes lying around that exceeds 16kx16k texels or the lower limit on mobile?
