### ISSUE TITLE
Changing scene tab while in Script editor switches to 2D/3D tab

### ISSUE THREAD

**Issue by Yagich** [godotengine/godot#61704]
### Godot version

3.5rc3

### System information

Linux/Ubuntu 21.10

### Issue description

Previously, when the Script editor tab was active and you switch the scene tab, it would open that scene's script, if present. Now when doing that, the view changes to 2D/3D instead. Not sure if this is intentional, but it breaks the workflow I was quite used to.

### Steps to reproduce

1. Open two scenes
2. Switch to Script editor
3. Switch from one scene tab to the other

**Comment by akien-mga** [comment]
Most likely caused by #61162. The behavior change is reproducible in both `3.x` and `master`.

This behavior of opening the script of the scene's root node is controlled by this editor setting (enabled by default):
![image](https://user-images.githubusercontent.com/4701338/173046755-97ca3651-7b91-4d9d-bb53-e054791153a7.png)

It still works (the script gets opened), but it doesn't get focus.
