### ISSUE TITLE
Decouple server classes from Main and MainLoop classes

### ISSUE THREAD

**Issue by wkubiak** [godotengine/godot#6171]
**Operating system or device - Godot version:**
Windows 10 x64 - Godot 2.1 stable

**Issue description** (what happened, and what was expected):
We discussed this today on #godotengine-devel with @bojidar-bg in regards to the possibility of introducing custom server implementations via the custom module mechanism.

It would be good to decouple existing server classes (e.g. Physics) from the Main classes and in the process enable developers to register their own servers via custom modules.

**Steps to reproduce:**
Check the source code.

https://github.com/godotengine/godot/blob/9397458cc0a37f4899a0dba5352a6e045ed123d8/main/main.cpp#L1580
https://github.com/godotengine/godot/blob/master/scene/main/scene_main_loop.cpp#L857

**Comment by kubecz3k** [comment]
It's worth to mention that this need appeared because there is no straightforward way to update your 'server' code in each game tick.

**Comment by reduz** [comment]
I'm sorry, I don't understand the problem at all

**Comment by kubecz3k** [comment]
@reduz today on irc you partly solved the problem, what this issue was about was ` OS::get_singleton()->get_main_loop()->connect("idle_frame",this,"mystep")`
The thing that left is how to initialize custom c++ module to beeing able to actually connect to main loop singleton. I believe @wkubiak will open an issue about this soon.
Meanwhile I think I can close this one, am I right @wkubiak ?

**Comment by wkubiak** [comment]
@kubecz3k
Yep, we can close this, as @reduz said that we probably won't benefit from redesigning Godot in such a way that servers would be decoupled and that users shouldn't be encouraged to add their own servers, although one could substitute an existing server with his/her own implementation.

New issue is here: https://github.com/godotengine/godot/issues/6193
