### ISSUE TITLE
Add Threads for VS (Fork, Join and Mutex/Semaphore vs nodes)

### ISSUE THREAD

**Issue by Marqin** [godotengine/godot#6177]
add Fork and Join nodes to visual script
- Fork - divides execution into multiple parallel threads (so **not sequence**)
- Join - joins threads (like posix pthread_join) - waits for all to complete
- Mutex/Semaphore - like thread mutex/semaphore

example:
![example_fork_join](https://cloud.githubusercontent.com/assets/959429/17727878/619b98f8-645c-11e6-8329-69528e79412c.png)

@reduz

**Comment by Marqin** [comment]
(edited issue - added mutex/semaphore - edit may not appear in Mail notice)

If you don't want to implement Semaphore node it could at first work by bloking in VS-VM access to the same stuff in different threads during by compilation error.

**Comment by reduz** [comment]
This probably could be done due to how VS works, but I can't imagine it
being useful in any way

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
