### ISSUE TITLE
Usability improvement in adding/setting groups

### ISSUE THREAD

**Issue by vinod8990** [godotengine/godot#6181]
If we have several nodes in the hierarchy, let's say 15 of them and we need to add them to a group, we need to type the group name 15 times and add them as one by one.

How about showing all groups in the project in the groups section as a checklist. This will not only make it adding faster but also make us know what groups are there project wide.

(I know that adding the root node to a group in a packedscene does the job, but I want the packedscene in different groups on different levels)

**Comment by Calinou** [comment]
The group editor partially addresses this since 3.1:

![image](https://user-images.githubusercontent.com/180032/63087936-a8ff3880-bf53-11e9-8fa0-06a300ca9c1b.png)

It can be accessed by selecting a node, going to the Node dock and in the Groups subdock, then clicking **Manage Groups**. The list of groups displayed only contains groups present in the currently edited scene.

However, groups still cannot be added to a project-wide list. This is being tracked in #5744, so I'll close this issue in favor of #5744 :slightly_smiling_face:
