### ISSUE TITLE
Suggestion : Curve2D.get_normal()

### ISSUE THREAD

**Issue by thomasbaijot** [godotengine/godot#6192]
**Operating system or device - Godot version:**
2.1 stable official

**Issue description** (what happened, and what was expected):
I had to find the normal of a point on a Curve2D but there is no built-in function to do so.
Then i suggest to implement this function in the next release.
This would be very useful for low-math-level-users like me :)
Thanks a lot.

**Link to minimal example project** (optional but very welcome):
Here is the function i made for this task :
http://pastebin.com/RQ2vZU2q

```
func get_normal(idx, fraction, precision):
    var previous_point = mycurve.interpolate(idx, fraction - precision)
    var next_point = mycurve.interpolate(idx, fraction + precision)
    var normal = (next_point - previous_point).normalized().rotated(PI/2)
    return normal.angle()
```

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
