### ISSUE TITLE
LineEdit Caret internal blinker timer fails to be added

### ISSUE THREAD

**Issue by TheDragonkeeper** [godotengine/godot#61984]
### Godot version

4.0 alpha 9

### System information

Windows 10

### Issue description

Trying to change scene using  change_scene() whilst having a LineEdit node present within the scene being loaded and having a forced displayed caret causes an error:

Timer was not added to the SceneTree. Either add it or set autostart to true.

### Steps to reproduce

Create a scene
add a LineEdit node
set LineEdit property "caret_force_displayed" to true

change_scene("to_new_scene")

**Comment by KoBeWi** [comment]
The problem is this function:
https://github.com/godotengine/godot/blob/136f84fc3549fa22b700d80f86216c484174ffb6/scene/gui/line_edit.cpp#L1341-L1345
It's called before the node is added to tree. Then the Timer is force-started here:
https://github.com/godotengine/godot/blob/136f84fc3549fa22b700d80f86216c484174ffb6/scene/gui/line_edit.cpp#L1322

This should be delayed until the node is inside tree.

**Comment by neilnvaidya** [comment]
Unable to reproduce on Linux

I have two scenes saves in project

scene_1(default scene) is  Node2D with script and no children
    func _ready():get_tree().change_scene("res://scene_2.tscn")

scene_2 is Node2D with LineEdit child that has "Force Display" enabled

Has this been fixed or am I missing something?

**Comment by TheDragonkeeper** [comment]
> Unable to reproduce on Linux

> Has this been fixed or am I missing something?

I tried to reproduce with a new project.
Problem still exists on alpha 10 Windows 10 (64).

However i did discover that not only is "caret_force_displayed" needed to be true but also "caret_blink" needs to be true.

"caret_blink" blink works on its own, when you click into the box to edit  but the combination of both throws the error

**Comment by TheDragonkeeper** [comment]
[GODOTTESTS.zip](https://github.com/godotengine/godot/files/8924803/GODOTTESTS.zip)
