### ISSUE TITLE
Automatic keys mode for Animation Player

### ISSUE THREAD

**Issue by Rinocrosser** [godotengine/godot#6201]
**Operating system or device - Godot version:**
Any device and Version

**Issue description** (what happened, and what was expected):
Now we have to press key icon each time we animate something. If you forget to do it, engine clear the value and replace it with the previous. In simple game it cause 100s of extra actions. In more complex games it is 1000s of pointless extra clicks (more than 3000 in my case). Godot animation player need auto key mode, when you change any value and it set a key automatically and rewrite it, when value changed again.

It will be faster and easier, like in any other engine.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
Question, 2D games have this thing on top where you can add keys by
pressing k , and you can choose if you want keys for
position/rotation/scale.
Would it be OK if autokeying is only for this? (loc/rot/scale), for
everything else you still would have to edit the value in the inspector as
always.

**Comment by Dillybob92** [comment]
Wait, isn't this what continuation mode is for? It interpolates through all the frame from x to x

**Comment by Rinocrosser** [comment]
@reduz Guess we need to vote. How about Facebook group post from you with same question?

**Comment by reduz** [comment]
no vote, just be honest and tell me if what I'm proposing is good enough
for you :P

**Comment by Rinocrosser** [comment]
@reduz For me will be great if any value could be setted with auto keys. Not just three of them.

**Comment by asheraryam** [comment]
Wondering if auto-keyframing is still wanted and if so how would you like it to be implemented?

A "record" mode where all changes are recorded?

**Comment by asheraryam** [comment]
>Would it be OK if autokeying is only for this? (loc/rot/scale), for
everything else you still would have to edit the value in the inspector as
always.

@reduz I'm interested in implementing this since even this limited autokeying would speed up our animator's work by magnitudes. Any specific notes about how it should be done?

**Comment by Calinou** [comment]
@asheraryam It seems autokeying was added in 296c74072 (shortly after the 3.1 release).

**Comment by asheraryam** [comment]
@Calinou Thanks! I'd like to enable it for the 3D editor, so will have to see if it has to be implemented or I just need to expose a button.

**Comment by asheraryam** [comment]
This is being discussed in https://github.com/godotengine/godot/pull/37195 if you'd like to test the binary attached there.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
