### ISSUE TITLE
NavigationAgent2D stops working after being placed into new map

### ISSUE THREAD

**Issue by Asgatoril** [godotengine/godot#62040]
### Godot version

v4.0.alpha9.official [fc18891db]

### System information

Manjaro 21.2.6

### Issue description

If a NavigationAgent2D is placed into a new map with NavigationServer2D.agent_set_map() the agent isn't able to find a path anymore.

When setting a new Target with set_target_location(), the function is_target_reachable() will always report false and get_nav_path() will always return an empty array.

Meanwhile NavigationServer2D.map_get_path(), with the agents map, position and target as parameters, will find a path.

### Steps to reproduce

Create a NavigationAgent2D and a NavigationRegion2D with a valid NavigationPolygon in the Editor.
Then create a new map with the NavigationServer2D and copy all parameters from the old one into it.
Then put the NavigationAgent2D and the NavigationRegion2D into it.
Wait until after the next physics tick and then try to navigate with the NavigationAgent2D.
Example:
```
	var agentRID = $NavigationAgent2D.get_rid()
	var navRegionRID = $NavigationRegion2D.get_region_rid()
	var oldMapRID = NavigationServer2D.agent_get_map(agentRID)
	var newMapRID = NavigationServer2D.map_create()

	#Copy all Options from the old Map
	NavigationServer2D.map_set_cell_size(newMapRID, NavigationServer2D.map_get_cell_size(oldMapRID))
	NavigationServer2D.map_set_edge_connection_margin(newMapRID, NavigationServer2D.map_get_edge_connection_margin(oldMapRID))
	NavigationServer2D.map_set_active(newMapRID, NavigationServer2D.map_is_active(oldMapRID))
	NavigationServer2D.region_set_map(navRegionRID, newMapRID)
	NavigationServer2D.agent_set_map(agentRID, newMapRID)
```
Afterwards set a new target for the Agent with NavigationAgent2D.set_target_location() and check the output of NavigationAgent2D.is_target_reachable().

Alternatively use the provided reproduction project:
You can move with a right click in the white area.
A click on the big button will reproduce the bug.
Afterwards you can't move anymore.

You will also find annotated logs in the console.

### Minimal reproduction project

[nav_test.zip](https://github.com/godotengine/godot/files/8901854/nav_test.zip)

**Comment by akien-mga** [comment]
NavigationAgent was changed so that avoidance is not enabled by default, for performance reasons. You can enable it with the `avoidance_enabled` property on relevant agents: https://github.com/godotengine/godot/pull/61235

**Comment by Asgatoril** [comment]
I don't think that that has anything to do with this.
`avoidance_enabled` is set to true and stays that way even after the agent gets set to a new map.
Also the agent would still create a path and return true on `is_target_reachable()`, even if `avoidance_enabled` was set to false. It would just not call the `velocity_computed() `callback.

**Comment by akien-mga** [comment]
CC @smix8

**Comment by smix8** [comment]
The `NavigationAgent2D/3D` Node and the `agent` RID on the NavigationServer are two totally different entities.

The NavigationAgent by design is a helper node for the parent Node2D/Node3D so everything is tied to the map of the parent which is the default navigation map from `get_world2d()` if a Node2D or `get_world3d()` if a Node3D.

While the NavigationAgent needs to create an agent as proxy to query paths on the NavigationServer it is not aware if this agent gets changed directly with the NavigationServer API.

I guess a function could be added to NavigationAgents to overwrite the default map.

**Comment by Asgatoril** [comment]
Ah, ok. I didn't knew that.
Since the NavigationAgents RID is mapped to the maps RID in the NavigationServer,  I expected the NavigationAgent to also use this information to determine its map.

If thats not the case, it seems to work as intended. I just tried to move just the NavigationAgent to a new map and the navigation still works on the original map.

Would i be possible to add this behaviour to the documentation?

**Comment by smix8** [comment]
The server `agent` is only used in avoidance and has nothing to do with pathfinding. Changing the agent map would not change the returned path but only the avoidance. The `NavigationAgent` internally uses NavigationServer `map_get_path()` with the assigned map. It is bad luck that both have agent in their name which often leads to confusion.

**Comment by Zireael07** [comment]
Can one of the agent thingies get renamed then? I'd assumed they're related at the very least...

**Comment by smix8** [comment]
It is `NavigationAgent` and `RVOAgent` which I think is distinct enough.

The problem is that RVOAgent is NavigationServer internal and GDScript only shows a generic RID and that the parameters for the NavigationServer API functions are all abbreviated to `agent` does not help. Maybe they should be renamed to `rvo_agent` so ppl know what kind of agent is expected as RVO is documented as the avoidance.
