### ISSUE TITLE
AnimationPlayer external broken animation resource causes the scene to crash on open

### ISSUE THREAD

**Issue by quantumcode-martin** [godotengine/godot#62102]
### Godot version

4.0.alpha10

### System information

Windows 10

### Issue description

When a scene has an `AnimationPlayer` node and this animation player has an external animation (`anim.tres`) and you delete this `anim.tres` the scene crashes (if opened in the editor, I think the entire editor crashes and closes).

Then if you try to open the scene, you'll get an error like so 
![image](https://user-images.githubusercontent.com/31007551/174043171-0e5fd6bd-d532-4096-843d-0fe77e489a93.png)

When you should just have the missing dependencies window.

So it looks like the animation player does something too early, before the missing dependencies can report and fix it.

Workaround:
Open you scene file and delete the line corresponding to the concerned animation it the `AnimationLibrary`:
![image](https://user-images.githubusercontent.com/31007551/174043782-7f876842-4487-46f7-947b-4ca79c1d35c5.png)

 

### Steps to reproduce

Create a scene, add an `AnimationPlayer` node.
Create an animation, and save it as `anim.tres` in the project files.

Now delete the `anim.tres` file and try to reopen the scene.

**Comment by LnxPaw** [comment]
I have not been able to reproduce a crash.

Unfortunately, I couldn't figure out how to fix the other issue (the _Alert_ window appearing instead of the _missing dependecies_ window), but I did some digging and found where the error occurs, so here it is.

The error happens when loading the AnimationLibrary sub-resource for the AnimationPlayer (more specifically the __data_ field) in `ResourceLoaderText::load()` and is caused by the `VariantParser::parse_tag_assign_eof` function call returning `ERR_FILE_MISSING_DEPENDENCIES`:
https://github.com/godotengine/godot/blob/17ca5b913c0a1fdad120a0451bd8183a2c6927ef/scene/resources/resource_format_text.cpp#L603-L613  

Returning from the function with an error here will result in the `ResourceLoader::load` finishing with an error which causes the whole Scene to be invalid and thus displaying the error:
https://github.com/godotengine/godot/blob/480586899a9a4226b2e6799893ef8c424080ef2d/editor/editor_node.cpp#L3717-L3720

Just "skipping" the error and continuing the executon in `ResourceLoaderText::load()` instead of returning will cause the correct missing dependecies window to appear in the editor, however actually fixing the dependency is not possible and the scene will still remain in an invalid state.

**Comment by Nandax00** [comment]
Could not reproduce the crash nor the "Alert" window on Linux.

The expected behavior is seen in this environment:
- "Missing Dependencies" window pops up
- "Open Anyway" opens the project
- AnimationPlayer is not present in the node tree anymore.

Logs for comparison, maybe it helps somewhat:
```bash
WARNING: FBX file import is enabled, but no FBX2glTF path is configured. FBX files will not be imported.
     at: _editor_init (modules/gltf/register_types.cpp:92)
WARNING: res://node_2d.tscn:3 - ext_resource, invalid UUID: uid://dadoat0bybi6h - using text path instead: res://anim.res
     at: load (scene/resources/resource_format_text.cpp:448)
ERROR: Cannot open file 'res://anim.res'.
   at: load (core/io/resource_format_binary.cpp:1123)
ERROR: Failed loading resource: res://anim.res. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:221)
ERROR: res://node_2d.tscn:7 - Parse Error: [ext_resource] referenced non-loaded resource at: res://anim.res
   at: _parse_ext_resource (scene/resources/resource_format_text.cpp:177)
ERROR: Index p_idx = 1 is out of bounds (edited_scene.size() = 1).
   at: remove_scene (editor/editor_data.cpp:530)
```

**Comment by KoBeWi** [comment]
I can't reproduce the bug at all. Saving animation to a file doesn't make it an external dependency.
Also the issue might be related to #54603
