### ISSUE TITLE
Orthogonal camera bottom border crossing visual issue

### ISSUE THREAD

**Issue by abderman** [godotengine/godot#62137]
### Godot version

3.4.4.stable.official.419e713a2

### System information

Windows 11 Home 22H2

### Issue description

In Orthogonal camera when KinematicBody is close to bottom border strange visual effec

https://user-images.githubusercontent.com/5955262/174262155-749597fb-0677-4381-883b-93793ff24235.mp4

t

### Steps to reproduce

run wih F5
using arrows move Hedge to bottom of screen

### Minimal reproduction project

[hedge.zip](https://github.com/godotengine/godot/files/8926043/hedge.zip)

**Comment by Chaosus** [comment]
Its because your camera clipping plane intersects with geometry, which makes parts of it disappear (even orthogonal camera's is affected by this). The solution is moving a camera away from the surface like this:

![solution](https://user-images.githubusercontent.com/3036176/174268950-e5c16368-78e9-4978-a343-dc023a17510d.gif)

I guess this is not a bug and should be closed.
