### ISSUE TITLE
Multiplayer spawner doesn't seem to work

### ISSUE THREAD

**Issue by Shadowblitz16** [godotengine/godot#62239]
### Godot version

4.0 build 10

### System information

KDE neon 5.24

### Issue description

I can't get multiplayer spawner to work at, it might be related to having the multiplayer synchronizer as a direct child of my player scene.

### Steps to reproduce

- download project
- run two instance
- on one click host
- on the other click join
- see that the server node with name 1 doesn't spawn on the client

### Minimal reproduction project

[AstroWars.zip](https://github.com/godotengine/godot/files/8937262/AstroWars.zip)

**Comment by Faless** [comment]
In `network.gd` you call:
```
_on_server_connect()
multiplayer.set_multiplayer_peer(_peer)
```

Which emits `server_connected` and calls the spawn before setting the multiplayer peer (i.e. before becoming a server).
The spawner then ignores the `add_child` because it is not the authority (see #22892).
Using the direct `_spawn` function would have reported an error, but when auto-spawning this cannot be detected.

Simply swap the 2 lines, and it will work:
```
multiplayer.set_multiplayer_peer(_peer)
_on_server_connect()
```
