### ISSUE TITLE
Position coordinates of mouse in scene shown in status bar.

### ISSUE THREAD

**Issue by iammangod96** [godotengine/godot#6224]
**Operating system or device - Godot version:**
Windows 8.1
Godot v.2.1.stable
**Issue description** (what happened, and what was expected):
Whenever I want to place an instance in a scene, right now I have to do that approximately as I can't say which is the center and everything. So it would be better to show the mouse coordinates in some type of status bar or on bottom right of scene.

And also one more thing that can be done is when resizing an instance and the size shown somewhere in realtime of resizing.

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by manokara** [comment]
I implemented something like this in my local build some time ago, it shows mouse coordinates in grid units and the tile under the mouse. It may need some polishing I think, but it works ^^ I'll make a PR.

**Comment by spookdogg** [comment]
YES, have wanted this for so long!
+1 is not enough!
(I hope it won't be just for tilemap... having to place Position2Ds to judge position is very clunky)

**Comment by pallavnawani** [comment]
Another Vote for this feature. Is especially useful in developing hidden object & adventure games.

**Comment by MarianoGnu** [comment]
isn't this solved with the 2D Editor Rulers?

**Comment by dreamsComeTrue** [comment]
Maybe instead of putting it on bottom of the editor, do it more contextually - like - display X,Y near the cursor as some kind of transparent hint. Same for resizing - then you could focus solely on your action, and no switching your sight back and forth.

**Comment by Calinou** [comment]
@dreamsComeTrue I think it makes sense to display the selected node's coordinates while moving or resizing something, as it already causes the editor to redraw continuously.

However, we can't *always* display the mouse cursor coordinates as this would cause unnecessary redrawing, which is problematic for Godot users on laptops.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
