### ISSUE TITLE
[Suggestion / Maybe Bug?] Option for RichTextLabel to inhert Label's auto resizing feature

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6230]
**Operating system or device - Godot version:** 2.1

**Issue description** (what happened, and what was expected):
So, if you add a `Label` node and add randomized text it will auto resize to fit. 

If you do the same for  a `RichTextLabel` node, it doesn't auto resize and you must give it a custom minimum size. Is this intended? If not, could it be possible for RichTextLabel to inherit this "auto resizing" feature that the `Label` node already does? 

For text that is.. as auto resizing pixel perfect based on custom fonts and images is not really possible.  But colorized text is basically the same length and size.. so the auto resizing should atleast be used for that :P

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
