### ISSUE TITLE
File recovery on crash

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#6231]
Godot shouldn't crash, but we all know that it does sometimes. It would be very nice that a data recovery function existed so not much of work is lost.

I believe an autosave to a temp path from time to time seems enough, along with a popup showing what can be recovered when opening a project that crashed.

**Comment by burstina** [comment]
I'm full up for this feature.
Losts are not editor-only: PC crashes, electricity fault, dangerous girlfriends shutting down PC...

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
