### ISSUE TITLE
not all arguments converted during string formatting

### ISSUE THREAD

**Issue by oddman621** [godotengine/godot#62313]
### Godot version

3.4.4 stable

### System information

Windows 10, GLES3, x86_64, Radeon RX 5700 XT

### Issue description

![aaa](https://user-images.githubusercontent.com/15917089/175059033-543e9cd9-915d-49a3-9bae-84866d45db7e.png)

This occurs when I add a new group to the node.

It seems no problem to test and release the game with that, still annoying every time saving a project.

Not using group is the only workaround fixing I found.

※Edit: I run Godot on CJK environment, maybe this is the cause?

### Steps to reproduce

1. Create any node.
2. Go to Node Tab→Group.
3. Add any group you want.
4. Add a new node from the node.
5. You will see several "not all arguments converted during string formatting" in output.

This also happens when you add a new script(with adding groups, of course). Everytime you modify and save scripts, the error appears.

### Minimal reproduction project

[group_error_reproduce.zip](https://github.com/godotengine/godot/files/8958607/group_error_reproduce.zip)

Load and unload Spatial.tscn file and you can see the error.

Adding new nodes or scripts in Spatial.tscn also causes the error.

**Comment by timothyqiu** [comment]
> Node is in %s group(s).
> Click to show groups dock.

is currently translated to

> 노드가 그룹 안에 있습니다.
> 클릭하면 그룹 독을 보여줘요.

The translation string of this is missing a `%s`. It's a placeholder for the number of groups that node is in.

@oddman621 If you're interested, you can fix the translation at <https://hosted.weblate.org/translate/godot-engine/godot/ko/?checksum=655e3abfa1c16bc2>

Sorry I missed the Korean translation yesterday. Languages are listed as codes in the editor settings. I thought the language code for Korean is `kr` and didn't find it in the options, so I assumed it wasn't included in the editor because its completion is below some threshold :(

**Comment by oddman621** [comment]
> @oddman621 If you're interested, you can fix the translation at https://hosted.weblate.org/translate/godot-engine/godot/ko/?checksum=655e3abfa1c16bc2

![fixtrans](https://user-images.githubusercontent.com/15917089/175227035-88ed3373-d279-411d-9af2-da4c4ff55c14.png)

Done.

**Comment by timothyqiu** [comment]
Checked in 3.5.1, this is fixed.
