### ISSUE TITLE
Autosaving scene or scripts

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6236]
An auto-saving feature every 5-min let's say to save the project  maybe?

**Comment by bojidar-bg** [comment]
:+1: only if it is configurable and defaults to off :wink:

**Comment by ivanskodje** [comment]
If we could optimize the auto-saving to save on the current scene/script every 5-10 seconds (or when switching scenes), we could possibly save a lot of time on saving. Sometimes saving takes far too long (1-2 seconds), which makes me wonder if it saves everything everywhere. Hmm..

**Comment by akien-mga** [comment]
If saving takes 1-2 seconds, I don't see how triggering it every 5-10 seconds would be an improvement.

**Comment by Calinou** [comment]
Optional automatic saving when the window is unfocused or idle could be added, similar to JetBrains IDE or Visual Studio Code with the autosave option enabled.

**Comment by burstina** [comment]
I am actually up for autosave feature, 
I just lost 300 lines of code for PC crash...

**Comment by SandbergSan** [comment]
I just installed godot since it looked interesting. One of the first thing i check in any new program is if there is an autosave and i'm a bit concerned that this proposal is almost 3 years old without any signs of it being implemented. Hope it will soon so i can choose this engine for any future project, it is too risky without any autosave/backup system.

**Comment by Calinou** [comment]
@SandbergSan I think it should be relatively easy to add a "save on focus loss" option by listening to `NOTIFICATION_WM_FOCUS_OUT` in the scene/script editor's `_notification()` method (in the engine source, that is).

**Comment by SandbergSan** [comment]
The autosave on the script is just what i was hoping to find. I didn't find it myself because i used the Search function in the Editor Settings and it didnt search all categories, only the currently selected one, so i went out and googled it and found this thread, so i assumed it wasnt there.

That the scene doesnt autosave is more understandable, and afaik many other programs have problems with this too so i dont expect that to work as easily. For example in unreal engine i always have had issues with trying to restore an autosaved/autobackup scene.

Still, if this program actually got scene-autosave/autobackup to work, without any downsides that the people above are describing and that it was default turned off, it wouldn't be bad for anyone,  xP

**Comment by KoBeWi** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
