### ISSUE TITLE
Node3D::set_position is broken

### ISSUE THREAD

**Issue by and-rad** [godotengine/godot#62386]
### Godot version

v4.0.alpha.custom_build [307dfa9fe]

### System information

Windows 10, Vulkan Clustered, nVidia RTX 2060 (512.15)

### Issue description

Calling `set_position` on a node that inherits from `Node3D` has no effect. This manifests at runtime when called from GDScript and also in the editor: Trying to change a node's translation via the Inspector does not work, the node doesn't move and the translation's value field is not updated.

Bisection suggests that the problem was introduced with #62227.

### Steps to reproduce

1. Open the attached project and try to set the cube's position via the inspector. Notice how it doesn't change.
2. Play the map via F6 and notice how the cube doesn't move either. It's supposed to move a little bit every frame.

### Minimal reproduction project

[set_position.zip](https://github.com/godotengine/godot/files/8980402/set_position.zip)

**Comment by Bromeon** [comment]
Thanks for finding and fixing this so quickly! Can confirm that 51c884f7acd276e86bb43a6f5856c3401c02adfe broke the `Node3D::set/get_position()`. It's pure chance that this even had an effect on me, since it's [pretty much the only Node APIs I use](https://github.com/Bromeon/gdext-rust/blob/feature/objects/itest/rust/src/object_test.rs#L109-L119) in integration tests 😉
