### ISSUE TITLE
"Changing the "Target SDK" is not valid" error even though I never tried to

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#62465]
### Godot version

3.5. RC5

### System information

Win, Nvidea 765M

### Issue description

I'm testing the latest Godot 3.5.RC build, trying the one click deploy but can't export and get this error:

![image](https://user-images.githubusercontent.com/47016402/176008116-a69a4705-c641-41dc-bcff-cacf87bd6c66.png)

I have not touched the "Target SDK":

![image](https://user-images.githubusercontent.com/47016402/176008333-04d244e7-1195-4679-a811-93ec8fefd2c2.png)

If I enable "Use Custom Build" like the error message seems to want me to, I get another error which also makes no sense to me (I have the 3.5.RC5 templates installed, even restarted Godot 3.5RC5 after just to make sure):

![image](https://user-images.githubusercontent.com/47016402/176008965-64084211-44a7-48dd-8af1-adfada52fd55.png)

Not sure if this is related to https://github.com/godotengine/godot/pull/61691 or https://github.com/godotengine/godot/pull/51815 since the times I have tested Godot 3.5 so far, I never tried to export.

### Steps to reproduce

Trying to export working 3.4.4 project to Android.

**Comment by akien-mga** [comment]
CC @m4gr3d 

The "Target SDK" option likely needs to default to 32 instead of 30. But I didn't get this error myself when doing a local test of the `3.x` branch with a custom built debug template, needs investigation.

**Comment by golddotasksquestions** [comment]
@akien-mga 

> The "Target SDK" option likely needs to default to 32 instead of 30.

This worked! I set "Target SDK" to 32 and unchecked "Use Custom Build" and errors are gone, one-click deploy is working.
I can also report after a guick test accessing external storage so far is also working like with 3.4.4

**Comment by m4gr3d** [comment]
I think the issue occurred because the previous value of `30` was saved as part of the project settings, and with the new value, the logic thought the user intentionally changed from the default. 

Couple of options:
- We can keep the error and change the default to an invalid value like `-1`. Seeing this value tells the logic it should always use the default sdk.
- Or change the error to a notice to inform users that want to use the target sdk that custom built must be enabled, without blocking users that don't want to use it. And provide another warning when custom build is enabled but the target sdk is not the default.

Thoughts?

**Comment by akien-mga** [comment]
> We can keep the error and change the default to an invalid value like -1. Seeing this value tells the logic it should always use the default sdk.

That would work indeed, but that's not very explicit to the user what a version of `-1` means. That also conflicts with the current hint range that goes from `min_sdk` to (default) `target_sdk`.

> Or change the error to a notice to inform users that want to use the target sdk that custom built must be enabled, without blocking users that don't want to use it.

That could work. The situation could also be improved by changing the message to actually mention what is the default target SDK, so users can understand by themselves that if they have 30 but the warning mentions 32 being the default, it might be a leftover from previous config (if they didn't choose this value themselves).

> And provide another warning when custom build is enabled but the target sdk is not the default.

Wouldn't that be the expected use of target SDK? If it warns when non default it means the only way not to get a warning is to not use it at all, in which case it's not clear what's needed for.

---

BTW, this looks like the range is designed so that one can't use a newer target SDK than the one we hardcoded as default. Is that intended? I would imagine the main use case for this setting is actually to be able to upgrade the target SDK to e.g. 31 now in 3.4.4-stable (which targets 30 by default) so one can fulfill Google Play requirements.

```
static const int DEFAULT_MIN_SDK_VERSION = 19; // Should match the value in 'platform/android/java/app/config.gradle#minSdk'
static const int DEFAULT_TARGET_SDK_VERSION = 32; // Should match the value in 'platform/android/java/app/config.gradle#targetSdk'
const String SDK_VERSION_RANGE = vformat("%s,%s,1", DEFAULT_MIN_SDK_VERSION, DEFAULT_TARGET_SDK_VERSION);
```

---

Another option could be to change the fields for `version/min_sdk` and `version/target_sdk` from int to strings, and keep them empty by default, with a placeholder string that shows the default value (e.g. "32 (default)"). So what's saved in the `export_presets.cfg` is `"'` and there's no problem on upgrade.

The downside is that you lose the SpinBox and the input validation for a valid integer - so it will require adding some manual checks that the string is a valid integer, and a new error message when that's not the case. But that might be the most flexible way to provide a "default unless overridden" behavior.

**Comment by oeleo1** [comment]
Same problem here with rc5, while with rc4 worked OK. Can't export -- Android is dead now :-)

**Comment by akien-mga** [comment]
> Same problem here with rc5, while with rc4 worked OK. Can't export -- Android is dead now :-)

Just change the Target SDK to 32 as described above.

**Comment by oeleo1** [comment]
PS: Ahaa - if I change the Target SDK setting from 30 to 32 - the error disappears and we can export indeed. Thanks!

**Comment by HEAVYPOLY** [comment]
Sorry to resurrect, is there a way to manually update target sdk from 30 to 32 if spinbox maxes at 30 in editor and without needing to rebuild export templates?  (using custom build of godot so want to avoid compiling if possible)

**Comment by m4gr3d** [comment]
> Sorry to resurrect, is there a way to manually update target sdk from 30 to 32 if spinbox maxes at 30 in editor and without needing to rebuild export templates? (using custom build of godot so want to avoid compiling if possible)

@HEAVYPOLY The target sdk in the editor was updated to an input field, so you can enter whichever values you'd like. If you're still seeing a spinbox, you may be on an older build.

**Comment by akien-mga** [comment]
You could try to set the value in `export_presets.cfg` manually, but it might still get overridden when you open the export dialog, not sure.

I assume your custom build is 3.4.x prior to 3.4.5? I'm not sure it can compile for API 32 at all, you should likely look into upgrade to 3.4.5 (which defaults to API 31, might work with 32) or 3.5.x.

**Comment by HEAVYPOLY** [comment]
Ok, I will try upgrading, my build was based on 3.x but pretty old i think right when 3.5 started.  Is 3.x branch newer than 3.5?  Also do either of these support android scoped storage?

**Comment by m4gr3d** [comment]
> Ok, I will try upgrading, my build was based on 3.x but pretty old i think right when 3.5 started. Is 3.x branch newer than 3.5? Also do either of these support android scoped storage?

Yes to both :)

Current code in `3.x` is for the upcoming 3.6 release, and scoped storage support has been fully integrated in 3.5.

**Comment by HEAVYPOLY** [comment]
Awesome, thank you!
