### ISSUE TITLE
A scene name can be empty (`.tscn`), leading to confusion in the list of open scenes and sometimes disappearing from the FileSystem dock

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#62497]
### Godot version

4.0.alpha10 (likely applies to 3.x too)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

Godot editor allows you to save a file with no name but an extension, such as `.tscn` or `.scn`. The result is that the scene will appear to have no name in the list of open scenes, which can look confusing. On top of that, the scene file will sometimes disappear and reappear in the FileSystem dock.

![image](https://user-images.githubusercontent.com/180032/176291193-ead7fc1a-0cc7-4e72-b0d1-d9ef78ceaeab.png)

I suggest not allowing empty names for saved scenes in the editor – the lefthand side (without the extension) should be at least 1 character long.

### Steps to reproduce

- Create a new scene and add any node.
- Press <kbd>Ctrl + S</kbd> to save the scene, and change its name to `.tscn` or `.scn`.
- Notice how the scene will not have any name (as the file extension is trimmed), and it will intermittently disappear from the FileSystem dock.

### Minimal reproduction project

N/A

**Comment by gotnospirit** [comment]
While doing some tests with my 3.x version, I noticed that we can also create a scene with ".tscn.scn", resulting in a basename ".tscn" and an extension of "scn". Is this should also be prevented?

**Comment by Calinou** [comment]
> While doing some tests with my 3.x version, I noticed that we can also create a scene with ".tscn.scn", resulting in a basename ".tscn" and an extension of "scn". Is this should also be prevented?

I think this particular case should be prevented if possible, but we shouldn't prevent users from creating scenes/resources whose name starts with `.`.

We should however print a warning when a scene or resource is saved with a name that starts with a `.`, as it'll be hidden in file managers on macOS and Linux.

**Comment by gotnospirit** [comment]
After few other tests, I think the warning for "leading period" will lead to too many warnings, because scene/resource saving appear many times (quitting editor, running game, save file) and if in case of a desired name, I think it become an UX problem.
Other way would be to start "tracking" if the warning was already done for each scene/resource, but it seems a bit too much.

That being said, I will be able to provide a PR for the 3.x branch (after few cleanups).
Unfortunately, for v4 I can't help, because it crashes on startup with my old GTX 850M.

**Comment by akien-mga** [comment]
I don't think creating files with a leading dot is a desired use case, those files will be ignored by Godot (and by Linux, possibly macOS) so I'm not sure what's the point of creating them in Godot in the first place. So I would just prevent doing this.

Then if someone comes with a valid use case we can add an editor setting that allows it, but I wouldn't bother doing it now.

Finally, the main UX issue we have to solve here aside from preventing saving with a leading dot is that there are various places where Godot will not propose a valid name in the first place. If you then save with an empty name, Godot will just append the extension and be happy with it - it should not allow saving without defining a base name.

**Comment by gotnospirit** [comment]
On the 3.x branch, the FileSystemDock does actually show files with leading dot (ie: ".tscn.scn"), while hiding folders with this same name (a bit strange, since I was allowed to create such folder from FileSystemDock).

Also, if I create a folder and then a create scene (from res://) with the name "myfolder/a.tscn", when I save the scene, the file will be located in "myfolder" (which is ok) but the implementation of String::get_basename() will return "myfolder/a".

So, in order to avoid side-effects and prevent leading dot when creating/saving/duplicate/rename scene or resource, I can either add a boolean parameter (default=false) to change the current get_basename method (allowing me to switch to new implementation) or introduce a new method.
What would be better?

While I'm here, should I also introduce a new TTR explaining leading dots are prohibited, or using "No name provided." would be ok?

**Comment by gotnospirit** [comment]
My PR is for the 3.x branch (https://github.com/gotnospirit/godot/commit/4dfd1c4735fc6d547bd1d4f3f2171acaa7a46259,)
I let @SekoiaTree do the job for the master :)
