### ISSUE TITLE
A way to know in-editor if sub-resources are unique or not

### ISSUE THREAD

**Issue by marcelofg55** [godotengine/godot#6258]
Hi, if you duplicate for example an AnimationPlayer its sub-resources remain linked and on the editor there is no way to determine if the sub-resources are unique or not. The only way now is to check the .tscn file.
So I was thinking that perhaps a good solution for this would be to show the list of sub-resources ids used by the node on the Inspector, I could try to implement this as well but I would like to know first if you agree with this or not :)

**Comment by reduz** [comment]
There is no need, sub-resources are never unique, always shared.


On Tue, Aug 23, 2016 at 1:06 PM, Marcelo Fernandez <notifications@github.com

**Comment by marcelofg55** [comment]
I see, the "Make Sub-Resources Unique" button is a bit confusing then. Could a unique flag be implemented for sub-resources?

**Comment by reduz** [comment]
Make sub-resources unique just makes a copy, they are never unique

On Wed, Aug 24, 2016 at 8:49 AM, Marcelo Fernandez <notifications@github.com

**Comment by reduz** [comment]
Maybe the text could be better, I'm not exactly sure what it could say.
I was considering adding a flag to make resources unique for the scene, but
that would still not solve your problem I guess.

**Comment by marcelofg55** [comment]
It would be nice to have that flag implemented, and then the flag is shown on the gui and issue solved :)

**Comment by reduz** [comment]
It would be relatively easy to do, but It would only work for resources
that are directly placed on a node..

On Wed, Aug 24, 2016 at 9:11 AM, Marcelo Fernandez <notifications@github.com

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
