### ISSUE TITLE
`get_node_or_null` returns `[Object:null]` instead of `null`, which breaks when calling a `Node` setter

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#62658]
### Godot version

v4.0.alpha.custom_build [602b27c07]

### System information

Arch on 5.18.7-arch1-1

### Issue description

I don't see what the difference is between these values. Therefore, not sure if this is a bug with `get_node_or_null` or `@node_setter`.

```gdscript
func _ready() -> void:
	print(null) # null
	print(get_node_or_null("doesnotexist")) # [Object:null]
```

```gdscript
var node: Node:
	set(value):
		node = value

func _ready() -> void:
	# Invalid type in function '@node_setter' in base 'Node ()'. The Object-derived class of argument 1 (null instance) is not a subclass of the expected argument class.
	node = get_node_or_null("doesnotexist")
```

### Steps to reproduce

1) Run the MRP

### Minimal reproduction project

[test3.zip](https://github.com/godotengine/godot/files/9034332/test3.zip)

**Comment by linkpy** [comment]
After investigation, the argument passed to the setter is indeed of type `Variant::OBJECT` with a null pointer. 
I guess the issue is that since the pointer is null, casting it to the requested type (here `Node`) fails.

The issue boils down to `GDScriptDataType::is_type`. In this particular case, this function tries to retreive the object corresponding to the null object through the `ObjectDB` but since it's null a null pointer is returned, which makes `is_type` returns falls : 
```cpp
// gdscript_function.h:108
				Object *obj = p_variant.get_validated_object();
				if (!obj) {
					return false;
				}
```

In my opinion, in this case `is_type` should return true since all `Object`-derived classes can be null.
