### ISSUE TITLE
Godot Engine Editor has stopped working

### ISSUE THREAD

**Issue by rogerdg** [godotengine/godot#6272]
**Operating system or device - Godot version:**
 Windows 7 Home Premium 64 bit with Service Pack 1
3.0GB RAM
AMD Athalon DualCore processor 5400B 2.80Ghz
Godot version: Godot_v2.1-stable_win64
AND                 Godot_v2.1-stable_win32

**Issue description** (what happened, and what was expected):
After download and extract of Godot on my computer, double clicking on the executable 
A window opens with the following:

  EXEC PATHP??: C:\Users\Roger\godot\2.1 Install\Godot_v2.1-stable_win64.exe
  EXEC PATHP??: C:\Users\Roger\godot\2.1 Install\Godot_v2.1-stable_win64.exe
  EXEC PATHP??: C:\Users\Roger\godot\2.1 Install\Godot_v2.1-stable_win64.exe
  DETECTED MONITORS: 1

A blank window with a white background opens partially covering the first window

A smaller window opens in the middle of the white window with the following text:
  Godot engine editor has stopped working
  A problem caused the program to stop working correctly.
  Windows will close the program and notify you if a solution is available.

A button [Close program] is displayed on the window.  Clicking the Close program button closes all 3 windows.  

Changing Windows compatibility choices or downloading and running the 32 bit version also present the same error.
 
**Steps to reproduce:**
As noted above  

**Link to minimal example project** (optional but very welcome):
Not applicable.

**Comment by manokara** [comment]
You have on-board graphics, right? Godot needs at least support for OpenGL 2.1 from your GPU. Usually Godot crashing at startup means your GPU is not supported :/

**Comment by akien-mga** [comment]
Most likely your GPU drivers don't fully support OpenGL 2.1. You could try updating your drivers, and if it doesn't work, try to use Linux which typically has better OpenGL drivers especially for old hardware.

Note that there is some ongoing work to better catch such issues and display a helpful error message instead of crashing, it should be better in upcoming releases.

Closing as it's a well-known issue on old hardware, and we can't really do much about it apart from telling you to upgrade drivers or hardware :)
