### ISSUE TITLE
Error in browser "_as_voices[$0] is undefined"

### ISSUE THREAD

**Issue by DaddySmash** [godotengine/godot#6274]
**Operating system or device - Godot version:**
OpenSuse Leap 42.1 64 bit
Godot 2.1

**Issue description** (what happened, and what was expected):

The repo for the game is https://gitlab.com/zombiesgo/zombiesgo.gitlab.io.  I the middle of playing it, I get a popup saying, "Exception thrown, see JavaScript console".  The console shows:

TypeError: _as_voices[$0] is null
ASM_CONSTS</_as_voices[$0].onended()

[post-exception status] Exception thrown, see JavaScript consolezombiesgo.gitlab.io:331:7
printErr()zombiesgo.gitlab.io:331
window.onerror/Module.setStatus()zombiesgo.gitlab.io:350
window.onerror()zombiesgo.gitlab.io:348

TypeError: _as_voices[$0] is undefined
ASM_CONSTS</_as_voices[$0].onended()

**Steps to reproduce:**
Start playing the game at any level of difficulty, and the error should show within a minute of gameplay.  It seems to be related to a mouseclick. The link to the game is https://zombiesgo.gitlab.io/.

**Link to minimal example project** (optional but very welcome):

**Comment by MilanVasko** [comment]
The same thing (among other stuff, apparently) is happening in our game - http://fryhet.com/ludum36

After a few blocks are thrown, the exact same thing happens - I don't think it's related to a mouseclick, it seems to me that it's somehow related to sounds being played (maybe repeatedly?). In your game, you also play a sound when you smack a zombie, so that would make sense.

Also, I don't know about you, but it only happened to me using Firefox (48.0.2) on Windows 10 64-bit (not sure if that's relevant), Google Chrome and Opera seem to work fine.

**Comment by Yogoda** [comment]
I have the same issue, it happens when playing a sound over itself (polyphony). To solve the issue, I gave each entity its own SamplePlayer.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.
