### ISSUE TITLE
Vulkan: SDFGI is still drawn when the unshaded debug draw mode is enabled

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#62758]
### Godot version

4.0.alpha11

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

SDFGI is still drawn when the unshaded debug draw mode is enabled. Unshaded *materials* are not affected by this issue; only the unshaded debug draw mode is.

### Normal draw mode

*An unshaded white sphere is present in the scene.*

![2022-07-06_02 04 33](https://user-images.githubusercontent.com/180032/177439105-fe360ed5-bb72-4401-94a9-e4c65aa66cd7.png)

### Unshaded draw mode

![2022-07-06_02 04 24](https://user-images.githubusercontent.com/180032/177439104-b941a85f-da91-4190-9572-bda149405f39.png)

### Steps to reproduce

- Enable SDFGI in the Environment resource.
- In the **Perspective** menu in the top-left corner of the 3D viewport, set the debug draw mode to **Unshaded**.

### Minimal reproduction project

**Testing project:** [test_fallback_material.zip](https://github.com/godotengine/godot/files/9050331/test_fallback_material.zip)

**Comment by Calinou** [comment]
I can still reproduce this as of 4.3.dev 8f0c20ee8.

Updated MRP: [test_debug_draw_modes.zip](https://github.com/godotengine/godot/files/14393989/test_debug_draw_modes.zip)

**Comment by atirut-w** [comment]
Is this also related to LightmapGI also being drawn in unshaded mode?

**Comment by Calinou** [comment]
> Is this also related to LightmapGI also being drawn in unshaded mode?

Yes, although the fix is slightly different.

**Comment by lander-vr** [comment]
This is a pretty bothering issue for artists. Normally in my environment workflow I religiously check base colors in my scene with unshaded viewmodes because setting up accurate and cohesive base colors are crucial in building solid PBR environments.

Inaccurate base colors (i.e. too bright, too dark, too saturated, not neutral) can cascade down to a heap of problems for artists when aiming for high fidelity graphics, particularly when it comes to lighting: struggling with getting accurate lighting results, not getting the bounce-light or general light behavior that might be expected, difficulties in color balance and post processing, overall the scene will not feel grounded.

Besides lighting concerns, this viewmode also allows for much easier fine-tuning of base colors. An example case could be matching base colors on materials using different textures.
