### ISSUE TITLE
Can't directly modify points of Line2D

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#62857]
### Godot version

d26442e

### System information

Windows 10 x64

### Issue description

Broken:
```GDScript
extends Line2D
func _process(delta: float) -> void:
	points[0].y += 10 * delta
```
Also broken:
```GDScript
extends Line2D
func _process(delta: float) -> void:
	points[0] += Vector2.DOWN * 10 * delta
```
Workaround:
```GDScript
extends Line2D
func _process(delta: float) -> void:
	var p = Array(points)
	p[0].y += 10 * delta
	points = PackedVector2Array(p)
```
I remember it was fine a month ago or so.

Probably not related to Line2D, but this where I noticed this first.

### Steps to reproduce

1. Add Line2D
2. Add some script
3. Try to change points of Line2D

**Comment by Chaosus** [comment]
Why simply not use `set_point_position(0, Vector2(get_point_position(0).x * 10 * delta, get_point_position(0).y))`?

**Comment by KoBeWi** [comment]
Oh I didn't see these methods 🤔
Still, it was working before, so it's a regression (it broke my code).

**Comment by cdemirer** [comment]
This probably happens due to the weirdness of Packed Array passing behavior.

Since #62462, The VM doesn't unnecessarily set values back to parent when something was modified in-place (shared stuff like Array, Dictionary, etc.).

However, Packed Arrays are edge cases. They are currently shared types within the boundaries of GDScript (they are assigned to vars by reference, and they pass to GDScript functions just like Arrays do), but they are copied when passing between GDScript and the C++ API. See https://github.com/godotengine/godot/pull/36492#issue-569558185.

The optimization in #62462 regards Packed Arrays as shared types, however `Line2D`'s `points` is not exactly shared, despite being accessed as a Packed Array.

**Comment by Maran23** [comment]
This is also _partly_ broken for 3.x already:
This does not work:
```
for point in line_x.points:
    point.y = position.y
```
This however works at least:
```
line_x.points[0].y = position.y
line_x.points[1].y = position.y
```
So there is probably more.

**Comment by Lippanon** [comment]
Still present in v4.0.beta.custom_build [91713ced8]. Can't edit a CSGPolygon3D's polygon directly (PackedVector2Array):
```GDScript
csgpolygon3d_ref.polygon.set(1, Vector2(1.0, 1.0)) # Doesn't change the value
print(csgpolygon3d_ref.polygon[1])
csgpolygon3d_ref.polygon[1] = Vector2(1.0, 1.0) # Doesn't change the value
print(csgpolygon3d_ref.polygon[1])
```
The same workaround of setting a new PackedVector2Array works.
