### ISSUE TITLE
Vulkan: Negative scale doesn't flip geometry normals, resulting in inverted appearance

### ISSUE THREAD

**Issue by abgenullt** [godotengine/godot#62879]
### Godot version

4.0 alpha 11

### System information

Windows 10,  RX 560

### Issue description

Hi,

if you set a negative scale on a Node3D that includes a mesh instance, it inverts the whole geometry.
![Screenshot](https://user-images.githubusercontent.com/34768615/178141378-d19fa885-46e2-479c-8b02-28badf4e4c3f.PNG)

Regards,

abgenullt

### Steps to reproduce

Create any MeshInstance3D as a child of a Node3D. Set the scale to a negative value.

### Minimal reproduction project

[scale_test.zip](https://github.com/godotengine/godot/files/9078885/scale_test.zip)

**Comment by Calinou** [comment]
This is being tracked in https://github.com/godotengine/godot/issues/29317 for 3.x, but I guess it makes sense to have a separate issue for 4.0.

**Comment by mrjustaguy** [comment]
This seems like Expected Behavior to me.

The MeshInstance Nodes are being scaled as children of the Node3D
MeshInstance Scaling affects the resulting Mesh
Mesh Scaled by Vector3(-1,-1,-1) will result in an exact opposite mesh to the input one.

Try Playing around with Blender Scaling, with backface culling enabled for instance.. same thing will happen, as it's the nature of vector math taking place.

What is weird is that I cannot reproduce this in the Vulkan Mobile Renderer on G4 A11 on my 1050ti

**Comment by abgenullt** [comment]
I've tested this in blender and unity. Both mirror the meshes without flipping the normals.
![Blender](https://user-images.githubusercontent.com/34768615/178157122-9735de6b-f39c-418d-bb49-01482aedbf72.PNG)

As far as I know, this is a common way to mirror meshes in certain situations, like in 2D. So, you don't need to create multiple variations of the same model.

Correct me, if I'm wrong..

**Comment by jtnicholl** [comment]
Is this different from #58546?

**Comment by krebszattila** [comment]
> Is this different from #58546?

The two issues must be related, because if I hide the node with correct normals in the scale_test project, the remaining nodes with flipped normals became correct. If I set the hidden node visible again then it will be the flipped one.

This issue only occours when multiple visible nodes use the same mesh with different scale (positive and negative). If I set negative scale for all three nodes they will be all correct. If I use different mesh resources for all nodes they will be all correct even with negative scale.

I can only reproduce this bug using Vulkan Clustered renderer.

**Comment by Dazdingon** [comment]
It's not fixed yet

**Comment by Dazdingon** [comment]
Model's normals flip for non-StandardMaterial3D (like those created by blender) when mirrored in Godot
...and physics behave weirdly
![Example](https://github.com/godotengine/godot/assets/8311871/62ba7bef-8c80-415f-86dd-ecb280b14017)
This is what happens if a model is scaled negatively, on an uneven number of axis ( negative on the x axis, in this case )
If a CharacterBody3D stands on the mirrored object, it gets stuck ( setting velocity doesn't make it move, when stuck )

If you use a StandardMaterial3D then the visual glitch goes away but it still breaks the physics
(Imagine having to deal with this headache without the visual indication)

And here's the reason mirrored objects are needed:
![image](https://github.com/godotengine/godot/assets/8311871/5a45fb85-760f-4633-bf5f-2443532d93e9)
Pre-built **segments for procedural generation**

**Comment by Calinou** [comment]
>  If a CharacterBody3D stands on the mirrored object, it gets stuck ( setting velocity doesn't make it move, when stuck )

Scaling collision shapes non-uniformly will never be supported, so you'll need to duplicate collision data either way.
