### ISSUE TITLE
Button shortcut not triggered from gamepad

### ISSUE THREAD

**Issue by SpyrexDE** [godotengine/godot#62899]
### Godot version

4.0.alpha.custom_build [6198bd5b8]

### System information

Windows 10

### Issue description

Same as issue #25741
HUD Button Shortcut does not trigger InputEventAction when the input source is a gamepad.

### Steps to reproduce

- Download and run minimal reproduction project
- Press escape or the joypad button with the index 0

Further explanation:
- The counter button's shortcut is bound to an action called "add_to_counter"
- To this action, two inputs have been added: `escape-key` the `joypad button` with the index 0
- Both should work to increase the counter, however only pressing escape is working

### Minimal reproduction project

[GamepadBug.zip](https://github.com/godotengine/godot/files/9079920/GamepadBug.zip)

**Comment by EricEzaM** [comment]
Thanks for the report. Your minimum project is way too complex tbh. All you need is a button with the shortcut set, and the counter. 1 scene, 1 script. It also did not work for me when I opened it - the nodes A,B.X,Y were missing, but they were referenced in the main script. Anyway, I was able to reproduce it after deleting some of those references.

@bruvzg 
This is happening because the button shortcut handling is happening in `shortcut_input` but only InputEventKey is allowed:
https://github.com/godotengine/godot/blob/f74491fdee9bc2d68668137fbacd8f3a7e7e8df7/scene/main/viewport.cpp#L2801-L2804

Just adding InputEventJoypadButton here is the easy fix. Thoughts?

**Comment by SpyrexDE** [comment]
@EricEzaM Thanks for fixing the issue! To be honest I didn't make the example project by my self. I just ported the example project from the Godot 3 version of this issue (https://github.com/godotengine/godot/issues/25741) to Godot 4.

**Comment by EricEzaM** [comment]
Ah no worries 🙂 thanks for reporting the issue!
