### ISSUE TITLE
Image filtering bug

### ISSUE THREAD

**Issue by Knand1861** [godotengine/godot#62956]
### Godot version

4.11 alpha

### System information

Windows 11

### Issue description

set to nearest and no repeat. These artifacts are not from the file itself
![изображение](https://user-images.githubusercontent.com/53999633/178547693-4856af3b-39e4-4800-ab50-e922b3fb2eb0.png)

### Steps to reproduce

set to nearest and no repeat.

**Comment by Calinou** [comment]
@Knand1861 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
