### ISSUE TITLE
Gradient Cubic interpolation looks like Constant interpolation for the last point in the gradient

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#63000]
*Related to https://github.com/godotengine/godot/issues/62999.*

### Godot version

4.0.alpha (5fec0d232)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 510.68.02)

### Issue description

Gradient Cubic interpolation looks like Constant interpolation for the last point in the gradient:

### 2 points

Constant | Linear | Cubic
-|-|-
![2022-07-14_16 59 46](https://user-images.githubusercontent.com/180032/179013867-99ffdb84-932f-40bf-8e5b-7ffec346785a.png) | ![2022-07-14_16 59 52](https://user-images.githubusercontent.com/180032/179013873-781c4bb0-8cb5-462f-ac20-abbfbf1ee194.png) | ![2022-07-14_16 59 58](https://user-images.githubusercontent.com/180032/179013875-aa9d4102-d68c-4ca7-a18a-74ad41ff05bd.png)

### 3 points

Constant | Linear | Cubic
-|-|-
![2022-07-14_17 00 11](https://user-images.githubusercontent.com/180032/179013877-f783543b-4282-446e-9bdb-497e36487265.png) | ![2022-07-14_17 00 17](https://user-images.githubusercontent.com/180032/179013880-101ea2ad-15d4-4719-90da-8a15f3878119.png) | ![2022-07-14_17 00 23](https://user-images.githubusercontent.com/180032/179013884-d07bc25f-f09f-4b76-bf97-38c2aaa2f3f5.png)

cc @Geometror 

### Steps to reproduce

Create a Gradient resource in the editor. This can be done as a standalone resource, but you can also create a GradientTexture1D or GradientTexture2D resource for use in a Sprite2D node to test this.

### Minimal reproduction project

N/A

**Comment by fire-forge** [comment]
It doesn't seem to always just be the last point. Here I have 4 points and both the first and last points are behaving strangely.

![image](https://user-images.githubusercontent.com/67974470/179372293-81218b37-7639-496a-a6ed-c9e706d053ef.png)

This bug was caused by https://github.com/godotengine/godot/pull/62458. If it helps, I took the `cubic_interpolate()` method in `Gradient.h` that was removed in that commit and compared it to `Math::cubic_interpolate()` to pinpoint the difference. Since the arguments have different names in both functions, I replaced the first 4 arguments with `A` `B` `C` and `D` and the fifth with `weight`. Comparing them this way might help whoever fixes this see the difference between the functions.

```cpp
Math::cubic_interpolate()
0.5 * ((A * 2.0) + (-C + B) * weight + (2.0 * C - 5.0 * A + 4.0 * B - D) * (weight * weight) + (-C + 3.0 * A - 3.0 * B + D) * (weight * weight * weight));

Gradient.h cubic_interpolate()
B + 0.5 * weight * (C - A + weight * (2.0 * A - 5.0 * B + 4.0 * C - D + weight * (3.0 * (B - C) + D - A)));
```
