### ISSUE TITLE
Function argument's default value not display in tooltips/documents when it's Array/Dictionary

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#63018]
### Godot version

4.0.alpha12

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

In the current version, if the default value of a GDScript function arguments is set to an array or dictionary, it will be null in tooltips and documentation. 

### Steps to reproduce

Just look at the script document and the tooltip when calling the fn function, the default value won't show/is null:

```GDScript
func fn(x = [], y = {}):
	return
```

### Minimal reproduction project

```GDScript
func fn(x = [], y = {}):
	return
```

**Comment by akien-mga** [comment]
Still reproducible in 4.0 RC 2.

**Comment by adamscott** [comment]
Post-poned to 4.2, see my [comment](https://github.com/godotengine/godot/pull/62994#issuecomment-1595195036) for details.

**Comment by dalexeev** [comment]
> In the current version, if the default value of a GDScript function arguments is set to an array or dictionary, it will be null in tooltips and documentation.

This is mostly fixed by the following PRs:

* #88211
* #89738

![](https://github.com/godotengine/godot/assets/47700418/a3ab0f5a-5255-4022-975e-91c3c41f33f0)
![](https://github.com/godotengine/godot/assets/47700418/7e295b72-d015-4fc6-a3ab-1502ead13d3f)

For complex expressions, an ellipsis is displayed, but we can increase the maximum recursion level if necessary:
![](https://github.com/godotengine/godot/assets/47700418/53f10344-340a-49da-b9e6-8e2afaae2662)

* In the future we may think about refactoring expression reduction (see #66218), but for now I think this issue can be considered resolved.
