### ISSUE TITLE
GDScript 2.0: Passing AutoLoad to function with typed parameter error "argument 1 should be Node but is ."

### ISSUE THREAD

**Issue by nathanfranke** [godotengine/godot#63045]
### Godot version

v4.0.alpha.custom_build [5fec0d232]

### System information

Arch on 5.18.10-arch1-1

### Issue description

```
Parser Error: Invalid argument for "test()" function: argument 1 should be Node but is .
```

### Steps to reproduce

scene.gd:

```gdscript
extends Node

func test(node: Node) -> void:
	print(node)

func _ready() -> void:
	test(Global)

```

### Minimal reproduction project

[test13.zip](https://github.com/godotengine/godot/files/9123446/test13.zip)

**Comment by git2013vb** [comment]
Similar error in v4.0.beta8.official [45cac42c0]
Debian 11

![DeepinScreenshot_select-area_20221220063302](https://user-images.githubusercontent.com/13235119/208599407-675940bb-6e39-4f4b-95eb-61afdfaed4a3.png)

![DeepinScreenshot_select-area_20221220062454](https://user-images.githubusercontent.com/13235119/208598421-b5e1d1d9-b9d8-4537-a51b-c78bb6e0aff2.png)

I cannot give a MVP/code because is difficult to replicate. 

If I change position to the first parameter the editor do not show the error but I will have the error at runtime
If I keep as is in pics the editor show the error but the code compile and run.

Thanks

**Comment by anvilfolk** [comment]
So I just checked and #70331 fixes this issue. One big detail about this issue is that at least on current `master` the error is not present in-editor but is still present at runtime. That's what the linked PR fixes :)

**Comment by anvilfolk** [comment]
> Similar error in v4.0.beta8.official [[45cac42](https://github.com/godotengine/godot/commit/45cac42c0b511672240c1fcccecfd3cc0580edcb)] Debian 11

That feels like a different issue to me. This one here only happens at runtime and it was about not finding the autoload. Yours appears more related to an issue with the type of the function that it *did* find in the autoload.

Out of curiosity, do you have any other function with the same name? Or are you using binds anywhere?

**Comment by git2013vb** [comment]
@anvilfolk 
Nope I do not have other functions in the same project with the same name.
Never used bind so far :)

**Comment by anvilfolk** [comment]
@git2013vb would you be able to open an issue for that if you haven't already? :) Would love to see that fixed :)

**Comment by git2013vb** [comment]
> @git2013vb would you be able to open an issue for that if you haven't already? :) Would love to see that fixed :)

I cannot. It was a on time error. If it will happen again Ill do it. I would love too see the others my bugs  fixed ;)

Thanks

**Comment by anvilfolk** [comment]
Hahahah! But if people don't know what bugs there are, they don't know what to fix! We all want to make godot as stable as possible! :) And everyone has different skills in different parts of the codebase, so it's not like everyone is looking at 7k issues, haha :D
