### ISSUE TITLE
Visual Script Minimap

### ISSUE THREAD

**Issue by djrm** [godotengine/godot#6316]
Since visual scripts tend to grow very fast, a minimap  could be useful to easily navigate the script

**Comment by Calinou** [comment]
**Bugsquad note:** This feature is still not implemented as of commit https://github.com/godotengine/godot/commit/4d787869e189b670d609f33c308991741592e40a.

**Comment by aspenforest** [comment]
I also need a minimap. Upvote for visibility.

**Comment by fire** [comment]
I think it is better that we implement whole graph rescaling. https://github.com/godotengine/godot/pull/29091 Thoughts?

**Comment by Calinou** [comment]
@fire A minimap is often a simplified version of the full thing it's representing. Here, it could just be a bunch of boxes and lines, which would be much faster to render compared to a second full-blown graph.

**Comment by dreamsComeTrue** [comment]
I would say - it could be extended - and used also in regular script editor (such as Sublime Text's code minimap)..

**Comment by Zireael07** [comment]
Regular script editor got a minimap recently.

**Comment by dreamsComeTrue** [comment]
> Regular script editor got a minimap recently.

Sure it is :) Sorry for mistype.

**Comment by Calinou** [comment]
For the record, the script editor minimap was added in #31302. We still don't have a visual script minimap yet though.

**Comment by dreamsComeTrue** [comment]
I was wondering - how should that kind of minimap look like for visual script? Similar to one in script editor (with lines and blocks mimicking actual nodes) put on one side of the canvas ? Or, because
visual scripts can go either horizontally or vertically, have a lot of empty spaces between nodes, etc.. - it should be real minimap, like the one from aseprite or Tiled editor..
And even if so - should it be still represented with simple primitives (rects/lines) or just like a scaled-down texture taken off from script canvas..

**Comment by Calinou** [comment]
> should it be still represented with simple primitives (rects/lines) or just like a scaled-down texture taken off from script canvas..

A simplified representation is likely the way to go, as it'll perform better.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
