### ISSUE TITLE
OS.has_touchscreen_ui_hint() works differently on pc and web

### ISSUE THREAD

**Issue by lesleyrs** [godotengine/godot#63181]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

On my laptop this returns true (no touch screen just touchpad) yet on web this returns false.

If this can't be used for detecting touch screens on html5 builds, then how do you deal with that? get_model_name() also does not work as expected and returns GenericDevice on most phones presumably.

### Steps to reproduce

Try it in editor and web build for different results

**Comment by return2monki** [comment]
My current solution is: check for touchscreen AND html in order to turn on mobile specific stuff.

I still don't know why touchscreen hint returns true on my laptop without touchscreen, and idk how it works on actual windows laptops with a touchscreen, but this seems to work for detecting phones on web.

**Comment by Zireael07** [comment]
Why close? I understand the issue still exists?

**Comment by lesleyrs** [comment]
I haven't tested this in a long time and I think the issue has more to do with a dependency that's being used for input rather than Godot directly so I'll leave it for some1 else to track.
