### ISSUE TITLE
Triplanar viewport texture weirdness 

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#63226]
### Godot version

3.4.4

### System information

Windows 10

### Issue description

![ve](https://user-images.githubusercontent.com/79376841/179925553-6d7569cb-9954-48b2-ac88-f9d45de28a8a.png)

### Steps to reproduce

Simple cube mesh instance with a viewport albedo texture and UV1 triplanar (to be mapped on all faces) - while in engine display looks alright, when rendering it gives those lines
Is it normal?

### Minimal reproduction project

I'd upload the project but is a VR project.

**Comment by sanyi12** [comment]
the viewport node also has a label node that allows it to display scale rotation etc.

**Comment by Calinou** [comment]
> I'd upload the project but is a VR project.

You can still upload the project if it's a VR project :slightly_smiling_face:

**Comment by sanyi12** [comment]
workaround - I just increased the margin of the label
however, I made a test project
[g.zip](https://github.com/godotengine/godot/files/9173805/g.zip)

**Comment by Calinou** [comment]
I'm fairly sure what is happening is that your label is touching the viewport's edges, and since the texture is non-repeating, it will infinitely expand. This is expected behavior, and nothing we can do anything about.

When rendering 2D elements on a viewport, make sure there's always at least 1 pixel of empty space between the viewport's edges and actual content (unless you intend it to be seamless when Repeat is enabled).
