### ISSUE TITLE
It's impossible to rearrange functions in Visualscript

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6347]
**Issue description** (what happened, and what was expected):
It would be great if we could rearrange functions in Visual Script. Currently they are ordered alphabetically but I personally think we should be able to rearrange them. Imagine if you would be forced to put your functions alphabetically in regular text script. It's just not practical since quite often order of functions express some kind of hierarchy (one function use another one, some meant to be public other are helpers etc).

**Comment by pwab** [comment]
It's still valid for Godot 3.2+ but this should be moved to the [godot-proposals repository](https://github.com/godotengine/godot-proposals)

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
