### ISSUE TITLE
Ability to define custom conditional function in VS

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6350]
**Issue description** (what happened, and what was expected):
This would be mostly a 'Syntax Sugar' in VS world, but it would further improve VS readability :)
Like we have currently `Condition` block it would be awesome if we could declare boolean getter functions which works just like current condition block, take a look at picture: 
![sugarconditional3](https://cloud.githubusercontent.com/assets/6129594/18134119/8d093530-6f9d-11e6-928f-f1ba44840a2b.png)

**Comment by hubbyist** [comment]
There must be a way to show origin of the decision function (canseeHero() from where?) to make it readable by other developers in bigger projects IMO.

**Comment by fire** [comment]
This should be part of generic visual script function node rather than a special case.

I don't know if functions should support multiple returns but it could be possible.

**Comment by fire** [comment]
![godot windows tools_2018-10-11_17-01-56](https://user-images.githubusercontent.com/32321/46840342-60954e00-cd77-11e8-8793-7e9f3e35f2fb.png)

You can use the switch node on an string. 

The int defines a enumeration. Such as: CHASE = 0, PATROL = 1

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
