### ISSUE TITLE
Vector4i and Projection are missing icons

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#63516]
### Godot version

v4.0.alpha.custom_build [5b6135291]

### System information

Windows 10

### Issue description

The new Vector4i and Projection types are missing editor icons.

![image](https://user-images.githubusercontent.com/67974470/181127863-5446f74b-6d19-4713-8b7c-c227d7f324e2.png)
![image](https://user-images.githubusercontent.com/67974470/181127918-cf7ff61d-75f6-486b-b004-3f0345d6f82e.png)

### Steps to reproduce

* Press F1
* Search for Vector4i and Projection

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/46056.

**Comment by snw-0** [comment]
Here's some possibilities.  I redid the '4' in Vector4.svg, since it wasn't pixel-aligned, and made them a slightly different color from Vector3 (in the same way Vector3 is a different color from Vector2).

![Projection](https://user-images.githubusercontent.com/2808851/181381409-36a8482d-43aa-4cec-a13c-af6f2c32974a.png) ![Vector4](https://user-images.githubusercontent.com/2808851/181381412-859afe3a-b718-48e6-ba1a-444344d5aa85.png) ![Vector4i](https://user-images.githubusercontent.com/2808851/181381419-d49f645a-e20a-4936-b6b3-e736f0afda3a.png)

SVGs: [godoticons.zip](https://github.com/godotengine/godot/files/9203936/godoticons.zip)

**Comment by RedMser** [comment]
#70639 also introduced a `uint` type which is missing an icon (shows up in the "Add Node" dialog for visual shaders).

**Comment by snw-0** [comment]
Something like this?
![uint](https://user-images.githubusercontent.com/2808851/211893336-47208f32-16d5-445c-aa95-45a1e91e3d15.png)
SVG: ![uint](https://user-images.githubusercontent.com/2808851/211893379-05818d02-8ab3-43bb-abe3-7fe929e474a5.svg)
