### ISSUE TITLE
AnimatedSprite3D margin calculation seems slighlty off by a couple of pixels, compared to AnimatedSprite2D

### ISSUE THREAD

**Issue by edwood-grant** [godotengine/godot#63520]
### Godot version

4.0-alpha12 (2c11e6d9efc42370a8d7537eaff8b1ea78a283e5)

### System information

x86_64 Windows 11, Vulkan backend (AMD Radeon RX 5700)

### Issue description

It seems that AnimatedSprite3D has a slight off calculation in the margins when rendering in the 3D world.

This causes some misalignment on sprites when animated and use margins, wchihi may prove difficult to deal if you want sprites to remain in the same pivot pint when exporting them as texture atlases created outside of Godot.

This behaviour does NOT occur in 2D mode with an AnimatedSprite2D. The margins are respected and sprite are centered correctly. You can fix this in 3D mode by moving a couple of pixels in the margins manually. But it will always misalign the 2d AnimatedSprite.

I assume that this is either a bug in Animatedsprite3D, or there is something that I'm not aware of on 3D when trying to align sprites correctly with tres resources.

### Steps to reproduce

- Open the attached project.
- Open and compare 2d_test.tscn and 3d_test.tscn Animated Sprite nodes. Both use the same frames resource and the same tres resources for animation.
- Observe that the Animatedsprite3D has a slight offset in the vertical 

### Expected results
Animated Sprites in Both 2D and 3D world are aligned correctly and the "pivot" does not move.

### Actual results
AnimatedSprite3D seem slightly off, by around 2 pixels position in margin height (notice the feet moving slighlty).

![Godot_v4 0-alpha12_win64_tMYwPK7zCq](https://user-images.githubusercontent.com/44873757/181163286-189ace5d-d96c-47e5-9f9b-0d731884963e.gif) ![Godot_v4 0-alpha12_win64_5dxcbzTugI](https://user-images.githubusercontent.com/44873757/181163480-5e0920ab-28ad-47e3-b50c-2a8641258a6b.gif)

AnimatedSprite2D, in contrast, looks Ok in comparison and no mislaignment is present.

![Godot_v4 0-alpha12_win64_bwBV8OBGdJ](https://user-images.githubusercontent.com/44873757/181163360-bf473d72-cb62-4fa6-a7a1-b079ce50a891.gif)

### Aditional notes
You can fix the sprite bop in the AnimatedSprite 3d if you open the **CopetonIdle0001.tres** resource and change its margin h value from **803** to **805** (Two pixel difference).  Unfortunately this will misalign the AnimatedSprite2D position and have a similar "bop" that the Animatedsprite3D had.

![ezgif-3-fd2bf060a1](https://user-images.githubusercontent.com/44873757/181165111-7542bd7d-c0e4-4a8f-a167-566afe5ebe2e.gif)

### Minimal reproduction project

Here is a minimal reproducton project that exhibits this behaviour.
- Unzip and import in Godot. 
- Open 2d_test.tscn and 3d_test.tscn to compare

[RepairBird_bug.zip](https://github.com/godotengine/godot/files/9195096/RepairBird_bug.zip)

**Comment by Chaosus** [comment]
Can this be reproduced it in 3.5?

**Comment by edwood-grant** [comment]
Hello @Chaosus,

Yes, I can confirm this exact behaviour in **Godot_v3.5-rc7_win64.exe.zip**. Commit [38b95cc2f](https://github.com/godotengine/godot/commit/38b95cc2fd7f898ead8c7be2732a6817eed1fba0).

In this version since is slightly different (due to the importer margin changes in trying to fix this problem) is changing **CopetonIdle0001.tres** height value from 801 to 803. But the offset is always the exact same, which is 2 pixels. Making the change fixes one scene, one but breaks the other. 

I've attached a similar project for **Godot_v3.5-rc7_win64.exe.zip** to confirm and test.
[RepairBird_bug_3.3_rc7.zip](https://github.com/godotengine/godot/files/9199408/RepairBird_bug_3.3_rc7.zip)

**Comment by kleonc** [comment]
The issue is how inverting Y axis is currently handled when converting a 2D rect into 3D. Simple example:
![Godot_v3 5-rc7_win64_2sZLggOOIz](https://user-images.githubusercontent.com/9283098/181277811-f0d4889c-93fe-4e41-b98f-890040724369.png)

- 2D (`AnimatedSprite`):
![Godot_v3 5-rc7_win64_QAdXz9y2eD](https://user-images.githubusercontent.com/9283098/181277816-ff897056-b69d-4746-b74d-b28e4ee46d38.png)

- 3D (`AnimatedSprite3D`):
![Godot_v3 5-rc7_win64_QlKwrZs5ga](https://user-images.githubusercontent.com/9283098/181277818-a25d2dd7-c60c-44fa-85f1-34b9aae80dad.png)

I think it should be changed from:
![Godot_v3 5-rc7_win64_QlKwrZs5ga](https://user-images.githubusercontent.com/9283098/181279493-7aec1551-d8e2-4fc0-b9a9-d0ede388ed1f.png)
to:
![FHm6ZJ35nG](https://user-images.githubusercontent.com/9283098/181279494-26ca9efe-8491-49dc-ba4a-8caf7fca9594.png)

Fixing it this way shouldn't break users' existing projects too much as it changes only non-zero vertical `AtlasTexture`'s margin cases. Without margins frames would still go into positive X/Y axes by default etc.
And it would of course fix this issue, meaning it would result in 2D/3D being rendered the same when centered.

Alternative would be making it go into negative Y by default, like:
![VKB4NW5H2u](https://user-images.githubusercontent.com/9283098/181286869-4bd54488-d8ba-4d93-b33f-0bd844ecc787.png)
But it would be a more breaking change as it would change literally every use case (so this is a no-no for `3.x`).


I'll open a PR with the proposed fix later.
