### ISSUE TITLE
Nested function for VS (ability to group nodes) 

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6353]
**Issue description** (what happened, and what was expected):
I was thinking about this issue for long time. In general we can group VS nodes by creating new functions, but **I think it's not always practical to create artificial functions that have no other purpose than to 'group nodes' for some other parent function** (and bloat function list view with many helpers function this way).  This is why I would like to propose 'Nested Functions' for VS. What I'm proposing is ability to group nodes by creating nested functions. I will try to explain how I imagine this feature with gif:
![nestedvsfunc](https://cloud.githubusercontent.com/assets/6129594/18139315/31dcde14-6fb1-11e6-8919-274a64b007de.gif)

I think this would allow us to have very readable VS scripts, and use them also in 'creating algorithm phase' where you could add couple empty blocks with nice names and implement them later when your 'high level logic' is on the place.

**Comment by volzhs** [comment]
How can add more node if all others faded in black when edit inner function?
And there should be "Ungroup" also, regrouping is needed in some case.

**Comment by kubecz3k** [comment]
@volzhs I have limited gif creations super powers :) By 'everything is faded' I meant that main function vs sheet is faded. It's an idea proposal, not exact way how I would like to see it when introduced :)
Also dont think ungroup/regroup is needed in first implementation, you can simply copy/cut nodes (it works already) to use them in different group or in parent function.

**Comment by reduz** [comment]
maybe, i'm still not sure how useful is this, give you can create as many
functions as you want and copy/paste the nodes there.

**Comment by djrm** [comment]
@reduz so there is no performance hit for creating multiple functions v.s. explicitly placing the nodes in VS

**Comment by Ace-Dragon** [comment]
With Godot seeing more use of node-based systems in general, wouldn't it be better to have generic node groups with custom inputs and outputs like in Blender?

If anyone is not sure what the usefulness would be, consider that...
 - Node Groups could be selected from a list and be reused anywhere in a tree or in multiple trees (so long as the node-tree type is the same)
 - It allows for clean organization (no having to have hundreds of nodes visible at once in a very complex situation)
 - It allows for mass-scale changes with just a few tweaks (what would be changed in a node group for shaders would change every shader using it for example)
 - It allows the user to break down a complex setup into a set of easy-to-use, intuitive controls (no having to hunt down the right values to changes, especially since input values can be shared with many nodes).

------------------------------------
In general, it's become a rule of thumb that a good quality node editor has something to group or organize nodes with, otherwise it can become very hard to work with.

**Comment by reduz** [comment]
I understand you guys are used to node groups from other systems, but as
far a now I am unconviced about the need for them, so they won't be
implemented anytime soon.

You can create functions and sub-call nodes, which should clearly cover the
same use cases.

**Comment by procedural** [comment]
@reduz to move some nodes into a new function you have to copy the nodes, create a function, paste them in, create input and output ports, connect the wires... vs. one click solution proposed in this issue

**Comment by reduz** [comment]
That's another issue, how about one-click create function? :)

**Comment by procedural** [comment]
@reduz sounds good :)

**Comment by kubecz3k** [comment]
GamesFromScratch was recording first VS introduction yesterday, and one of his first comments was that it's not yet possible to do what I requested in the first post :P It's in this video, basically exactly at 13 minute:
https://youtu.be/dSUMCUsOeyU?t=13m1s

**Comment by fire** [comment]
I agree with reduz there should be a one click create function and expand function into nodes.

**Comment by fire** [comment]
> I think the best way for organization would be a 'code collapse box' that could be used in different ways:

https://github.com/godotengine/godot/issues/18267#issuecomment-382490921

This can be expanded for the one unified graph enhancement @reduz mentioned in planning.

The approach is to have one graph. Use the existing custom node functionality but have the graph function collapse its nodes and be able to be callable. We can store the nodes inside of the custom node and expose it as a global library for sharing. The nodes can be collapsed and expanded at any point.

**Comment by fire** [comment]
This was discussed in Google Summer of Code 2019, but the schedule was moved back. @swarnimarun Do you want to post your proposal for feedback?

**Comment by swarnimarun** [comment]
Yep I am planning to finalize a proposal ASAP.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
