### ISSUE TITLE
GDScript 2.0: Incorrect null check when resizing typed array in setters

### ISSUE THREAD

**Issue by Trung0246** [godotengine/godot#63570]
### Godot version

4.0 alpha12

### System information

Windows 11

### Issue description

Apparently the null check failed when array is initially empty and resizing it along with looping will not pass the check.

Expected result: print `true` 8 times
Actual result: print `false` 8 times

The weird thing is that if I replace `print(data == null)` with `print(data)` then it will print `null` 8 times
And the line `print(bbb.arr[0] == null)` will also print `true`

However removing type information `Array[Array]` should be the temporary fix.

### Steps to reproduce

```gdscript
class BuggyArray:

    var arr: Array[Array] = []

    var m_size: int:
        get:
            return arr.size()
        set(p):
            arr.resize(p)

            for data in arr:
                print(data == null)
                print("---")
```
```gdscript
# Some random _ready
func _ready():
    var bbb = BuggyArray.new()
    bbb.m_size = 8
    print(bbb.arr[0] == null)
```

**Comment by h0lley** [comment]
I would expect
```
var arr: Array[Array]
arr.resize(3)
```
to result in
```
[[], [], []]
```

**Comment by Trung0246** [comment]
Hm after checking for similar issues this maybe relevant?
https://github.com/godotengine/godot/issues/58285

**Comment by ajreckof** [comment]
The problem is with initialisation an `Array[Array]` should never have `null` elements as `null` is not an `Array`. Based on that your behaviour seems coherent sometimes it thinks it is an array as it is in an `Array[Array]` and some times he forgets it.When it thinks it is an `Array` it then can't be null. The bug is not on that but as said by hOlley that the array should be populated with empty arrays and not null objects

**Comment by vonagam** [comment]
Yes, what @hOlley said is correct, Array is a non-nullable type. And proper initialization will be done when PR is merged.
