### ISSUE TITLE
Singletons are not loaded when running script from command line

### ISSUE THREAD

**Issue by caryoscelus** [godotengine/godot#6360]
**Operating system or device - Godot version:**
2.1 & git

**Issue description** (what happened, and what was expected):
When script is launched using `-s` command line options, it cannot access singletons (they are not loaded). Perhaps, sometimes this is desired behavior, but sometimes scripts do require globals, so it should be at least optional.

**Steps to reproduce:**
Launch script containing global singleton references from command line.

**Comment by vnen** [comment]
Singletons are part of a *project*. When you run a script with `-s` you're not running the project, only the script itself. Such script must inherit from `MainLoop` and by so the engine does not run the usual initialization (since it's not loading the project).

You need to load the singletons manually in the script.

**Comment by Sslaxx** [comment]
This doesn't sound like a bug, but it might be classifiable as a documentation issue? http://docs.godotengine.org/en/latest/reference/command_line_tutorial.html does not mention any issues with singletons, for one.

**Comment by caryoscelus** [comment]
That might be so (even though it does load engine.cfg if it's present), but what prevents from it from changing?

As a matter of fact, i've just implemented it by changing couple of lines in main.cpp. It could be made optional, as well.

**Comment by caryoscelus** [comment]
So, can anybody answer this? Would you accept pull request with a fix?
