### ISSUE TITLE
mouse_enter signal doesn't fire if lmb is held down

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6362]
**Operating system or device - Godot version:** 21

**Issue description** (what happened, and what was expected):
I have two very expensive custom draw **control** nodes (inventory/stash) and while dragging (LMB is held down)  `mouse_enter` doesn't get fired.

Not sure if this is intended, but if it is, is there a way we can simulate the release of LMB internally?  If not, I guess my argument would be `mouse_enter` should fire even if the lmb is held down because well, technically, it's _over_ and _entering_ the area.. :)

**Comment by Zylann** [comment]
I suspect it's due to mouse capturing, which is a common behaviour in GUIs:
When any control/widget is clicked and mouse is held down, no other widget will get events except the widget. This is mostly useful for dragging operations.
Try this on your desktop with other applications, you will find out hover effects don't always play if you drag something like a scrollbar, but also buttons or even a panel's background. It depend on the type of widget and application.

**Comment by Dillybob92** [comment]
@Zylann Yeah, now that I think of it this would allow for better UX too. Since we can detect drag, and set a var to true, and if that node has a `mouse_enter` on it, (this is all ofcourse using nodes and not custom _draw overlaps) we can then fire a `ondraghover` type of event to ease the eyes. For example, while dragging, and if `mouse_enter`, show a red dotted border or whatever.

**Comment by reduz** [comment]
I suggest you check the drag and drop demo (it's in the godot demo package)
to see how to drag stuff from one control to another

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
