### ISSUE TITLE
Animation Retargeting Scale is .01 and corrupts the visuals

### ISSUE THREAD

**Issue by finepointcgi** [godotengine/godot#63641]
### Godot version

4.0 Alpha 13

### System information

Windows 11

### Issue description

During testing I noticed my rig after retargeting the scaling went to .001
![image](https://user-images.githubusercontent.com/12012300/181825730-6b8a41a3-2e09-48c9-9c2a-992f424ad43d.png)

![image](https://user-images.githubusercontent.com/12012300/181826344-4e047c61-2026-40f8-b9f5-e9ad0fd485a4.png)

I have attached my file and discussed it with @fire and it seems to be a bug.

I have found a workaround with using Fbx2GLTF importer

### Steps to reproduce

* I imported a mixamo rig into blender and moved the blend file into Godot.
* Retarged the rig 
* Opened the scene
* Scaling was broken

### Minimal reproduction project

[AnimationTest.zip](https://github.com/godotengine/godot/files/9222618/AnimationTest.zip)

**Comment by TokageItLab** [comment]
@finepointcgi Let me get the issue straight.

Is the Retarget system you are referring to the Blender one? Or are you using Godot's Retarget system?

If the problem is caused by Godot's Retarget system, then you need a sample project that contains the glTF file that caused the problem.

If it is not a problem with Godot's Retarget system, I think the problem is with `.blend` importer. At least Godot's Retarget system does not change the scale of imported files.

**Comment by finepointcgi** [comment]
It is with the Godot retargeting system. I imported using the blend
importer. I can check try using gltf export and see if it works.

**Comment by TokageItLab** [comment]
@finepointcgi I can't open the blend file in that project in the importer, so I don't know what is wrong with it.

**Comment by finepointcgi** [comment]
I have also exported it out with glb and also have this issue.
[AnimaitonTest.zip](https://github.com/godotengine/godot/files/9222864/AnimaitonTest.zip)

**Comment by TokageItLab** [comment]
@finepointcgi Thank you! the problem is very simple and relies on the scale and orientation of the parent of the model being imported being broken.

The solution is clear, just include the global transform of the Skeleton "Node" in the retarget calculation, but the Node in the current Post Import Scene does not have transform 3D.

So, in my opinion, it is necessary to "apply" those transforms before the Post Import Process. Otherwise, we need to set up the transform 3D correctly in the Post Import Scene.

CC @fire

**Comment by TokageItLab** [comment]
I have successfully retrieved the global transform.

But the problem is that if the parent node has transforms, retargeting is meaningless.

For example, there is a model A and a model B.

If they have a front forward animation, but their parent Nodes have different rotations, they will not be able to share, since the current retargeting system only aligns the skeleton's bone orientation.

Also, if the parent Node is transformed by the retargeting system, it may affect other objects besides the Skeleton.

Therefore, we need to apply rotation and scale before PostImportScene, as in approach #60115, or import only the Skeleton, as in AnimationLibrary.

@reduz Any thoughts on this? So far, I think this can be a documentation issue.

**Comment by TokageItLab** [comment]
In the meantime, I implemented an option #63662 to apply those transforms to the Skeleton. I don't think this will be a problem for general use cases, but it could cause problems with non-rigged accessories, etc.

**Comment by Szotyi2501** [comment]
I had very similar issue with simply importing the mixamo model with Blender 3.2.
Even after fixing the scale, the mesh wasn't following the animation of the skeleton:
![image](https://user-images.githubusercontent.com/14240206/182252601-b8f31da9-e029-47b9-b0c6-37202b3bd060.png)

Importing it with Blender 3.1 instead of 3.2 fixed the issue though.
