### ISSUE TITLE
Audio WAV samples can't be previewed anymore

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#63683]
### Godot version

4.0alpha13

### System information

linux

### Issue description

| alpha 12                                                                                                        | alpha 13                                                                                                        |
|-----------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/71937306/181933458-8984e14c-0c53-4236-9951-258a172df098.png) | ![image](https://user-images.githubusercontent.com/71937306/181933478-442b5883-dc71-411d-ad97-e1a29a22a653.png) |

A new dedicated window for mp3 and ogg files import setup was added in alpha 13, maybe that's the reason.

### Steps to reproduce

Select a wav file in the FileSystem dock.

**Comment by KoBeWi** [comment]
This is a regression from #63265
A fix is already planned.

**Comment by tangentstorm** [comment]
I believe this has worsened considerably. In 4.0 betas 9 and 10, attempting to preview the waveform with the inspector visible causes an "illegal instruction" error, at least on my windows 64 machine:

```
$ ~/Downloads/Godot_v4.0-beta10_win64.exe/Godot_v4.0-beta10_win64 --editor
Godot Engine v4.0.beta10.official.d0398f62f - https://godotengine.org
Vulkan API 1.3.224 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080 Ti

...  # line below happens when clicking a *.wav file:

ERROR: Index p_index = 3 is out of bounds (((Vector<T> *)(this))->_cowdata.size() = 3).                                                                                                                              at: operator[] (./core/templates/vector.h:52)                                                                                                                                                                  Illegal instruction                                                                                                                                                                                                                       
```

If the inspector tab is not showing, then the problem does not happen, but if you click the inspector without first selecting another resource, it again crashes... So it's very likely the resource editor.

For what it's worth, I discovered this while working on a godot plugin that not only shows a waveform and allows playing it, but lets you edit and record... Perhaps someone else might find this useful as a workaround until the bug is fixed:

https://github.com/tangentstorm/godot-waveform

(Just don't have the inspector visible!) :)

**Comment by akien-mga** [comment]
Please open a new bug report with a reproduction project.
