### ISSUE TITLE
GDScript 2.0: When accessing const, enum, inner classes from preloaded scripts, their type in constant expressions is Variant

### ISSUE THREAD

**Issue by stylemistake** [godotengine/godot#63715]
### Godot version

4.0.dev (66d1bb84c3)

### System information

Arch Linux, Vulkan, RX 550

### Issue description

This worked before on 3.5

So basically, I commonly put various constants and types for convenience into a single file and then register it as a global (via class_name) so that I could access them from anywhere, and because all constants are in a single file, I avoid unnecessary circular dependencies.

This still works in 4.0, but GDScript can no longer infer the type in constant expressions. This broke type inference in a lot of my scripts because all expressions were reducing to `Variant`.

Export of enums is also broken if referencing the type from another script. (I mitigate by manually specifying an `int` type)

https://user-images.githubusercontent.com/1516236/182022105-9a836e83-d095-406d-987e-dd47f7e3810b.mp4

### Steps to reproduce

```gd
## Constants.gd
const MACH_TO_SI = 343.0

enum WeaponFireType {
  NONE = 0,
  SEMI_AUTO,
  FULL_AUTO,
}

## If registered as global via class_name
const MACH_TO_SI = Constants.MACH_TO_SI # -> Variant
const WeaponFireType = Constants.WeaponFireType # -> Variant

## If using preload
const MACH_TO_SI = preload('res://Constants.gd').MACH_TO_SI # -> Variant
const WeaponFireType = preload('res://Constants.gd').WeaponFireType # -> Variant
```

**Comment by AntonioDell** [comment]
This is connected to #63535. Because Enums declared in autolaods are being parsed as Variants, the `resolve_match_branch` in `gdscript_analyzer.cpp` throws the error "Expression in match pattern must be a constant.".

**Comment by AntonioDell** [comment]
To reproduce this in gdscript editor instead of VSCode like it was done in OP you have to adjust the code slightly and will get an error message, which is related to the issue:

```
# Constants.gd
extends Node

const SOME_CONST = 42
```
```
# Test.gd

const Constants = preload("res://Constants.gd")

func cannot_be_inferred():
  return Constants.SOME_CONST

func _ready():
  const a := cannot_be_inferred() # Throws error 
```
Error: `Parse Error: Could not infer the type of the variable "a" because the initial value is a variant. Use explicit "Variant" type if this is intended.`

**Comment by AntonioDell** [comment]
I created a PR to correctly infer types from preloaded const, but sadly I could not reproduce the video in OP, because the VSCode plugin godot-tools does not support godot 4.0 and so the inferred types were all over the place. In the godot editor the types are inferred correctly with the PR.
@stylemistake can you tell me, which vscode extension and which godot engine version you are using for type inference in the video? I would like to recreate this to see, if the PR really solves the issue mentioned here.
If you like, you could also try recreating the video with the build in my PR and give feedback.
Any help is much appreciated :)

**Comment by stylemistake** [comment]
@AntonioDell I can confirm your PR fixes the issue, including the types that are reported in VSCode plugin.

I'm using `godot-tools`, and despite lack of official support, it does work, albeit with some broken functionality, but type information that it reports so far has been accurate.

It does require a change in settings because language server now runs on a different port:

```js
"godot_tools.gdscript_lsp_server_port": 6005
```

https://user-images.githubusercontent.com/1516236/183296765-a4f27bf6-d3c4-4c75-8b9e-a140e150a9dd.mp4

**Comment by AntonioDell** [comment]
Very nice, thank you for the extensive tests :D
The only thing I am wondering is the type inference for preloaded enums. They are inferred as dictionaries, but I think fixing this could be a separate enhancement issue.

**Comment by stylemistake** [comment]
Yes, it unrelated.
