### ISSUE TITLE
Highlight "TODO" and "FIXME" in GDScript comments

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6371]
**Operating system or device - Godot version:**
2.x

**Issue description** (what happened, and what was expected):

It could be very handy ...

.... if the editor made possible to do global search for keywords or keychains into every scripts (including shader scripts), 

or

... if the editor kept a list of all scripts and lines where the words *WORKAROUND", "TODO", "FIXME", "WARNING" appear into comments or as new official keywords (that would be ignored like the `pass` kw )

**Steps to reproduce:**

Make a complicated project that contains many scripts with lots of workarounds, fixme and todo, and try to keep your code up to date with the fixes included into each new official stable godot release.

**Link to minimal example project** (optional but very welcome):

**Comment by vnen** [comment]
Global search for comments: okay. Official keywords: please don't.

**Comment by SuperUserNameMan** [comment]
Adding them as official keywords, OR **only enlightening them in a special color** even when written into a comment, would allow to avoid misspelling them so we are sure to retrieve them with global search.

**Comment by Ace-Dragon** [comment]
The problem with adding stuff like these as keywords is the fact that they are subjective and user opinion on what to add as keys can vary.

Perhaps instead of hardcoding them, the user can define a custom keyword list in the project settings (so as to avoid long-winded debates as to what the official comment keywords should be).

**Comment by ArcFutahito** [comment]
Why these should be reserved keywords? I just spam ## FIXFIXFIXFIXFIXFIXFIXFIX before the block I need to work on and that's enough for me. It's comments, you can still make them stand out by using lots of characters or some other formatting.

**Comment by Calinou** [comment]
> OR at least enlightening them in a special color even when written into a comment, would allow to avoid misspelling them so we are sure to retrieve them with global search.

That sounds much more reasonable, but then it should be changeable by users. Note that I don't see a lot of "WORKAROUND"s out there, but "TODO", "FIXME" and possibly "CHANGED" are very common in programming.

**Comment by SuperUserNameMan** [comment]
@ArcFutahito : as reserved keywords or just enlightened in a different colors when written into a comment, to be honest I don't care.
I just would like that the editor give me easy and quick access to ALL the lines of codes from ALL gdscript and shader scripts where one of these keywords appears, so that I don't have to manually open and search each and every scripts of my project.

And enlightening this keywords in a different color would reduce the risk of misspelling them.

I wish i could have kept my project simple enough to not need some extra help from the editor, but has has reached a point where it's starting to be a PITA.


( Though, as a workaround, maybe i could just scan all my files with a windows version of Grep ..... ? .... hmmmm think i gonna do that )

**Comment by ArcFutahito** [comment]
@SuperUserNameMan reserved keywords have a little bit more going on then just different color :D But having some sort of tagging system would be interesting, so let's, maybe, just think about it in more general way? For example, highlighting blocks of code with different background color or whatnot. That would stand out more than a keyword.

![screenshot at 2016-09-04 14 33 47](https://cloud.githubusercontent.com/assets/10696955/18230706/04d2f72e-72ad-11e6-8254-d55334b54006.png)

**Comment by SuperUserNameMan** [comment]
@ArcFutahito : if you set the background color using the right-click menu, and if a user defined tag-name is associated to each color, and if the editor gives me access to a list of all scripts where one of these colors-tag-name is used, I'm ok with your idea.

**Comment by ArcFutahito** [comment]
@SuperUserNameMan Well, yeah, that's what I was thinking. Let's say you have predefined "tags" like [Incomplete], [Workaround], [Needs refactoring] and whatever, as well as the ability to create your own tags and edit tags that are already defined. 
You highlight lines of code, select "Apply Tag" and lines of code get highlighted with a color, set in your tag. 
Since you'll need to get and store tagged lines of code (I guess that would be engine.cfg), you can also have all sorts of metrics, like pie charts with amount of code under different tags shown and list files that have code under a certain tag (let's say that code editor panel will have [Metrics] button for that). 

The only question right now is whether or not this idea will get picked up.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : such keywords aren't yet globally searchable.

**Comment by neikeq** [comment]
Why not do it the IntelliJ IDEA way? It highlights comments with a certain pattern. It provides TODO and FIXME patterns by default, but you can add your own. There is also a bottom panel which lists all the results, like an automatic global search.

**Comment by akien-mga** [comment]
Note that there's a plugin for that on the Asset Library: https://godotengine.org/asset-library/asset/53

**Comment by jahd2602** [comment]
@akien-mga The plugin is not working in v3. Also, probably it won't highlight the keywords in the code.

**Comment by Zireael07** [comment]
They don't need to be keywords, but special highlighting pretty please!

**Comment by akien-mga** [comment]
I agree about adding highlighting for "TODO" and "FIXME" in comments in the GDScript text editor (cc @Paulb23). It should be relatively straightforward.

Global search is already implemented (Find in Files) so likely not needed specifically for those terms. (For a TODO-specific listing, https://godotengine.org/asset-library/asset/53 can easily be ported to Godot 3.x.)

I'm not sure if the list of such special highlighted terms should be made configurable, but it probably doesn't hurt to make it an option (as a comma separated list of strings).

**Comment by alex9099** [comment]
Any update on this? it is not high priority, but would be nice to see implemented (highlighting keyworks like FIXME, TODO, etc in comments)

**Comment by Calinou** [comment]
@alex9099 As far as I know, nobody has worked on this so far. It's likely not too difficult, but remember that `TODO` and `FIXME` should be highlighted only in comments, not in strings or identifiers.

Also, many editors highlight the whole `TODO`/`FIXME` line rather than just the keyboard. This is more difficult to implement.

**Comment by akien-mga** [comment]
Superseded by godotengine/godot-proposals#602.
