### ISSUE TITLE
Signal cannot be connected to the custom function using the connection dialog

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#63710]
### Godot version

66d1bb84c380910a50e3176124da5c8821e93097

### System information

Windows 11

### Issue description

Instead of establish connection to the custom existed function, the editor emits error - `editor\connections_dialog.cpp:550 - Condition "!it" is true.`

### Steps to reproduce

![signal_connection_bug](https://user-images.githubusercontent.com/3036176/182012587-86cc19aa-0e6c-4a03-844c-c57f42707492.gif)

### Minimal reproduction project

[TestSignals.zip](https://github.com/godotengine/godot/files/9228155/TestSignals.zip)

**Comment by MinusKube** [comment]
I think this should be kept open, this has only been partially solved by my PR.

The signal gets deselected every time the script is validated (thus causing the error), but my PR only fixes the bug which was causing the script to be validated every second endlessly. But there are still other ways to validate the script.

For example, if you open a script then quickly open the connection dialog, the signal will still get deselected, because a script gets validated about one second after it's opened.

**Comment by KoBeWi** [comment]
Seems fixed.

**Comment by reduz** [comment]
:partying_face:

**Comment by MinusKube** [comment]
Not fully fixed, see my latest comment, and here's a example to reproduce:
![Switch file reproduction video](https://user-images.githubusercontent.com/13206601/213928612-3dfee196-a049-4f2f-ba9b-7c255469ecfe.gif)

Can also be reproduced by editing the code then quickly opening the connect popup, for example:
![Edit code reproduction video](https://user-images.githubusercontent.com/13206601/213929180-042e3578-ac5b-4b91-aa29-857184e825db.gif)
