### ISSUE TITLE
`find_children` returns `[]` if match string is given

### ISSUE THREAD

**Issue by sairam4123** [godotengine/godot#63757]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Windows 11, Nvidia GeForce GTX 1050, 27.21.14.5771

### Issue description

`find_children` method of `Node` returns empty list even if it is looking for a node with a name is present in the tree! 
It finds the node if the `match_string` is `"*"`.

### Steps to reproduce
```
find_children("*name*", "", true, true)  # returns []
find_children("*") # returns [nodes! whoohoo!]
```

### Minimal reproduction project
[MRP.zip](https://github.com/godotengine/godot/files/9231350/MRP.zip)

**Comment by heppocogne** [comment]
This might be because `find_children` only searches for the children nodes whose names match the `match_string`.

![image](https://user-images.githubusercontent.com/83043568/182160007-7a729e0d-59d5-4d84-a0ae-fe3125d46637.png)

In this case, `find_children("A*","",true,true)` would finds "A" and "A/Alpha" but not "B/Alpha".
