### ISSUE TITLE
ParticlesMaterial turbulence properties are missing default values

### ISSUE THREAD

**Issue by fire-forge** [godotengine/godot#63798]
### Godot version

v4.0.alpha.custom_build [98c1fb396]

### System information

Windows 10

### Issue description

The ParticlesMaterial turbulence properties are missing default values (except for `turbulence_active`). This means the revert button doesn't appear after changing the value in the inspector.

![image](https://user-images.githubusercontent.com/67974470/182261410-7d28c3f5-b5ef-4c35-971b-b07a6f39e424.png)

![image](https://user-images.githubusercontent.com/67974470/182261385-c2053eb8-f3f1-4e01-80ce-92698d14af81.png)

### Steps to reproduce

**Note:** This must be done in a build from any commit after 9137ba79269cd957753fce8d783ffb01c8ac60fa (https://github.com/godotengine/godot/pull/55387).

* Create a ParticlesMaterial
* Open the "Turbulence" section
* Change some properties
* The revert button does not appear
...
* Open the ParticlesMaterial documentation page
* Navigate to the `turbulence_*` properties
* See that there are no default values listed, except for `turbulence_active`

**Comment by Calinou** [comment]
cc @RPicster

**Comment by RPicster** [comment]
I looked into it and the problem is that the properties are hidden when the turbulence is not active.
You can observe the same behaviour in the emission shape properties (changing the emission shape to e.g. sphere).

It seems that default values will only be picked up for properties that are not set to `PROPERTY_USAGE_NONE` at time of compilation. Eventually it would make sense to change this problem at the root? I would like to hear what the more experienced contributors think about this.
