### ISSUE TITLE
Properties in the inspector lacking tooltips.

### ISSUE THREAD

**Issue by Sslaxx** [godotengine/godot#6382]
I suspect this should have "Documentation" and "Discussion" tags at least.

A lot of properties for default nodes are lacking descriptive tooltips. For example, the "Under" and "Over" properties of TextureProgress display "property: texture/under", without any description of what the property actually does. Whereas the "Pos" property on the same node does (which appears to come from Rect, in the same way "Pos"'s tooltip on a Sprite comes from Node2D?).

What is the (best) way of adding these?

**Comment by vnen** [comment]
AFAIK the tooltips come from the documentation of the setter method (for that property) and it's defined manually which method to get the doc from. Since TextureProgress has no documentation for the methods, that's why it's missing. They also inherit the tooltips along with the properties, as you noticed: Sprite position is the same `transform/pos` from Node2D and TextureProgress inherit `rect/pos` from Control.

However, not every property shown in the inspector has a setter method, so the current approach is a bit lazy, leaving quite a few properties without any tooltip. Also, some setter methods are documented as *methods* so they're phrasing is weird when showing as a tooltip.

**Comment by Kaukamieli** [comment]
Yes, tooltips come from the setter method. Which becomes a problem in 3, as the separate setters and getters disappears for member variables, which have their own things. The tooltip has to be set to have the member text instead, because the tooltips in the editor are important.

**Comment by akien-mga** [comment]
Should be easy to change in https://github.com/godotengine/godot/blob/02c7566/editor/property_editor.cpp#L2915-L2948

**Comment by carlosfvieira** [comment]
Guess that the major issue here is the lacking of tooltips from the members of the parent classes... for example... by selecting a Node2D node, the Node2D properties has tooltips - Ok. But the properties from the class which Node2D inherits from (CanvasItem) don't have tooltips...

A fix for this is to traverse class docs using the inherits property of ClassDoc... do you agree or i'm missing something?
