### ISSUE TITLE
Scene Naming should be Auto by default

### ISSUE THREAD

**Issue by xix-xeaon** [godotengine/godot#63866]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Linux

### Issue description

The project setting Scene Naming (editor/scene/scene_naming) should be Auto by default because then the (suggested) name of the scene will be exactly the same as the name of the root node. It the user wants them to differ then it should be a manual choice. There is already a setting for default naming nodes with other standards (editor/node_naming/name_casing).

### Steps to reproduce

Create a new scene. The node is named with *PascalCase*. Save the scene: Suggested name is *snake_case.tscn*.

**Comment by Calinou** [comment]
The [Godot project style guide](https://docs.godotengine.org/en/latest/tutorials/best_practices/project_organization.html#style-guide) recommends using snake_case for file names whenever possible (with the exception of C# scripts).

We've had people regularly opening issues for years because the suggested scene naming didn't match this recommendation. I don't think going back to the previous behavior is what we should do here :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing in favor of other issues such as https://github.com/godotengine/godot/issues/39441 per the above comment.
