### ISSUE TITLE
Animation(s) Imported Despite Import Settings Unchecked

### ISSUE THREAD

**Issue by michael-nischt** [godotengine/godot#63954]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Ubuntu 22.04, NVIDIA GeForce GTX 765M 

### Issue description

GLTF animations get imported despite setting unchecked:

![import_no-anim](https://user-images.githubusercontent.com/500820/183058605-ce5af44a-9162-4ec0-bc33-9db615dc9cc2.png)

The created scene contains an `AnimationPlayer` node:

![scene_anim-player](https://user-images.githubusercontent.com/500820/183058613-44e120cb-9114-4e7e-af77-497f757b1380.png)

Which contains the animation resource:

![anim_clip-res](https://user-images.githubusercontent.com/500820/183058616-02bb2eaf-5e4f-49e8-bff6-16f7bb6a266b.png)

I would expect neither the animation player node to be present nor the animation data to be generated.

### Steps to reproduce

1. Disable the animation import settings check-box for an GLTF file which contains at least one animation
2. Open the imported scene and observe an `AnimationPlayer` node present with the imported animation data (both unexpected)

For your convenience I added a sample project with a simple rotating cube gltf (`cube_rot.glb`). The import settings have animation unchecked but it is ignored.

### Minimal reproduction project

[import-no-anim-bug.zip](https://github.com/godotengine/godot/files/9267838/import-no-anim-bug.zip)

**Comment by Calinou** [comment]
Can you reproduce this in 3.4.x?

**Comment by michael-nischt** [comment]
yes, same in `v3.4.5.stable.official [f9ac000d5]`

Sorry, didn't realize the version on itch.io got updated today to 3.5 (possible a mistake?)

**Comment by Calinou** [comment]
> Sorry, didn't realize the version on itch.io got updated today to 3.5 (possibly a mistake?)

3.5 is being prepared for release as we speak :slightly_smiling_face:

**Comment by hakro** [comment]
This issue is also visible on Godot 4 Alpha 13.

Collada works as expected : no AnimationPlayer is added to the scene when animation is unchecked in the import window.

But Gltf does not work as expected : an AnimationPlayer is created regardless of whether animation is checked or not in the import window : 

**Collada (dae) :** 

![2022-08-08_14-43](https://user-images.githubusercontent.com/3624853/183421892-903c03c2-8c9a-4a6b-8c49-8174f1383f31.png)

**Gltf :** 
![2022-08-08_14-45](https://user-images.githubusercontent.com/3624853/183421977-1fc4afe8-aa96-444f-b434-b0f1d4e0b6f4.png)

In both cases, it's the same scene exported from Blender, one using collada, one using Gltf
