### ISSUE TITLE
Uniform arrays of `mat4` type are set incorrectly when an Array of Transform3D is supplied

### ISSUE THREAD

**Issue by cdemirer** [godotengine/godot#64051]
### Godot version

3b39f00761145

### System information

Linux

### Issue description

While you can set a `uniform mat4 x;` using a `Transform3D`, you can't set a `uniform mat4 x[N];` using an Array of `Transform3D`s (the values visible to the shader will be corrupted / incorrect). Instead, currently you have to convert the Array of `Transform3D`s to a flattened `PackedFloat32Array` and use that as the parameter of `set_shader_param`.

I think the reason might be that the conversion in this line doesn't work as expected:
https://github.com/godotengine/godot/blob/25915cdd0e8e2baffc4d52692a1c54ad182e2aea/servers/rendering/renderer_rd/storage_rd/material_storage.cpp#L652

Somewhat related: #63064

### Steps to reproduce

Given this uniform:
```gdshader
uniform mat4 x[1];
```
This doesn't work (results in bad values in shader):
```gdscript
my_shader_material.set_shader_param("x", [global_transform])
```
This works:
```gdscript
my_shader_material.set_shader_param("x", global_transform_as_16_floats_in_packed_array)
```

**Comment by Calinou** [comment]
cc @Chaosus

**Comment by clayjohn** [comment]
Implementation here:
https://github.com/godotengine/godot/blob/40b9c246b65010768bd3c87dd6162e07dabd6898/servers/rendering/renderer_rd/storage_rd/material_storage.cpp#L651-L655

the conditional checks whether an array is passed, if so, it reads the data like an array of floats, otherwise, if the variant is a transform, it will read the transform directly. I guess we need another conditional within the array branch to see if the array contains Transform3Ds, or we need to at least to error in the case that an array other than a PackedFloat32Array is used

**Comment by faylite** [comment]
I've encountered the same issue with arrays of `mat3` and `Basis`. But I see @bitsawer is already ahead of the curve here 🥇
