### ISSUE TITLE
Found a bug relating to GIprobes and reflections

### ISSUE THREAD

**Issue by leobaker202** [godotengine/godot#64115]
### Godot version

3.4 and 3.5

### System information

Windows 10, GTX 1650, GLES3

### Issue description

Default PBR shader renders correctly with GIprobe reflections but Custom shaders render as if it has no material on it in Reflections and shows up as white, tested with both visual shaders and written shaders

Also am unsure if this bug is in 4.0 as i've not tested, but since i've just found it, theres a good chance its there too since its in 3.4 and 3.5

Also, now something unrelated to GIprobes but, Screenspace reflections from the world enviorment are also broken too, as they are very Glitchy i notice, and stretch alot, i figure'd i'd add this in here, since its a bit of an annoying bug too

### Steps to reproduce

Mainly just use a random custom written shader, or make a custom LIGHT shader in visual shaders, Also make sure you are using a GIprobe in the scene with the reflections from the GIprobe specificly, not the ones from the Reflectionprobe but the GIprobe

**Comment by clayjohn** [comment]
I have marked this as a bug for now, but I have a feeling this is actually a design limitation of the GIProbe. If I recall correctly, when rendering the GIProbe it checks to see if a SpatialMaterial is used, if so it can read color from that. If a ShaderMaterial is used, then it defaults to white (because the GIProbe is mostly calculated on the CPU)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/34281. I'll keep this issue open as it pertains to 4.0.

**Comment by leobaker202** [comment]
> Duplicate of #34281.

34281 is a completely different bug
