### ISSUE TITLE
Particle node rotation changes are ignored while the node is moving

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#64133]
### Godot version

7355dfb

### System information

Windows 10 x64

### Issue description

![](https://chat.godotengine.org/file-upload/ymejCTaJhdgBiyqPT/godot.windows.tools.64_dClcnzP7CN.gif)

### Steps to reproduce

1. Add GPUParticles2D node
2. Make it rotate
3. Move it

### Minimal reproduction project

[GPUParticles2D.tscn.txt](https://github.com/godotengine/godot/files/9285914/GPUParticles2D.tscn.txt)
Move the node around, like in the GIF.

**Comment by luketrenaman** [comment]
Built version mentioned above and was able to reproduce on Ubuntu Desktop 22.04.1 LTS. Processor is i7-1260p on Iris Xe Integrated graphics.
![bug](https://user-images.githubusercontent.com/46632227/183556333-450cc03b-0b4e-45ac-a83e-60efac8f2fa5.gif)

**Comment by Calinou** [comment]
Does this occur with CPUParticles2D as well?

**Comment by luketrenaman** [comment]
I don't think this issue is specific to particle generator nodes.

When dragging the CPUParticles2D node under any conditions it will stop spinning.

When running a slightly modified script that follows the reproduction steps (rotating and moving an emitting GPUParticles2D node), you find that rotation changes are not ignored:

![https://user-images.githubusercontent.com/46632227/183657230-5615f427-5500-4506-b69e-ef76193bbbfc.png](https://user-images.githubusercontent.com/46632227/183657230-5615f427-5500-4506-b69e-ef76193bbbfc.png)

The issue seems to be that the `rotate` method doesn't fire when an element is actively being dragged within the editor. It can be reproduced with a Sprite2D:
![sprite2](https://user-images.githubusercontent.com/46632227/183664989-1a1bd74a-8c21-4dc4-b953-90feece34fbf.gif)

[MovingSprite.tscn.txt](https://github.com/godotengine/godot/files/9291278/MovingSprite.tscn.txt)

**Comment by KoBeWi** [comment]
> When running a slightly modified script that follows the reproduction steps (rotating and moving an emitting GPUParticles2D node), you find that rotation changes are not ignored:

Weird, because I originally noticed this issue at runtime. I recreated it in the editor just for easier testing.

I'll retest in my project.

**Comment by KoBeWi** [comment]
🤦‍♂️
So, my particles didn't rotate, because, guess what, I wasn't actually rotating the node. My scene had a sprite and particles with the same texture, I was only rotating sprite and wrongly assumed something is wrong with the particles.

The editor behavior isn't really a bug. The node keeps whole transform while dragging, so it discards any rotation changes. It just accidentally aligned with the broken in-game behavior caused by my mistake xd

Closing; forget this issue existed.
