### ISSUE TITLE
AnimationPlayer: Collapse key tracks into single track

### ISSUE THREAD

**Issue by 1000h** [godotengine/godot#6422]
My suggestion is to implement a button which would collapse the view of all the tracks into a single track.  The purpose of this is for cutting up a strip of animation which contains multiple 'actions' e.g. a strip which has the walk cycle, attack cycle, jump cycle all in the same strip.

When cutting up a strip now, if there are more tracks than fit within the track window, even if extended, you have to scroll down mid selection to get the tracks that weren't visible.  If the tracks could be collapsed into a single track, you would be able to select all tracks at once.

Look at blender's action/ dope sheet frame tracks.  The top row collapses all of the tracks.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9ad1800 : it's not implemented yet

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
