### ISSUE TITLE
Godot 3.5 break C# API `GetMeta`  Method not found

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#64286]
### Godot version

v3.5.stable.mono.official.991bb6ac7

### System information

unix, windows

### Issue description

I use the SetMeta/GetMeta methods to transport missing ResourcePath parameters and access them by 
`var resourcePath = node.GetMeta("ResourcePath") as string;`

With Godot 3.5 mono it fails now by
```
ERROR: 'System.MissingMethodException: Method not found: object Godot.Object.GetMeta(string)'
```
It worked with all previous versions

### Steps to reproduce

```
var node = new Godot.Node();
node.SetMeta("ResourcePath", "foo");
var resourcePath = node.GetMeta("ResourcePath") as string;
```

**Comment by raulsntos** [comment]
I can't reproduce this issue it works fine for me in v3.5.stable.mono.official [991bb6ac7], can you provide a minimal reproduction project? Also, is it only `GetMeta` or are other methods in the `GodotSharp` assembly missing?

My guess is the project is using the wrong DLL so I'm specially interested in the `.csproj`, it should look something like this:

```csproj
<Project Sdk="Godot.NET.Sdk/3.3.0">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by MikeSchulze** [comment]
Here the example Project, it works with Godot v3.4.5.stable.mono.official.f9ac000d5
But fails on 3.5
[getMeta.zip](https://github.com/godotengine/godot/files/9325172/getMeta.zip)

**Comment by raulsntos** [comment]
The cause seems to be the `GodotSharp` package reference in your `.csproj`. The `Godot.NET.Sdk/3.3.0` already references the `GodotSharp` assembly but it's likely a different version in 3.5 so they conflict, you have to always reference the same version (or a compatible version).

**Comment by MikeSchulze** [comment]
This is only a example i have an extra mono project bundled as nuget package
This project needs the GodotSharp package.

Can you tell me the version Godot v3.5 is using?

**Comment by raulsntos** [comment]
Each Godot version is bundled with its own GodotSharp DLL built from source, the DLL is copied by the Godot editor to the game project. If you have a project that uses `Microsoft.NET.Sdk` instead of `Godot.NET.Sdk` you'd have to reference the DLL manually, like this:

```csproj
<Reference Include="GodotSharp">
    <HintPath>$(GodotProjectDir)/.mono/assemblies/$(Configuration)/GodotSharp.dll</HintPath>
</Reference>
```

This is how the `Godot.NET.Sdk` references the GodotSharp assembly:

https://github.com/godotengine/godot/blob/1806e414b81a960be12eaa4774f3ecaabcd414ad/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.props#L101-L108

**Comment by MikeSchulze** [comment]
Thanks for the answer, I will have to try it out

**Comment by MikeSchulze** [comment]
If is ok to upload the GodotSharp v3.5 to nuget to can reference in my project?

**Comment by raulsntos** [comment]
There are no plans to distribute NuGet packages of the Godot assemblies for the 3.x branch that I'm aware of, but we plan to publish NuGet packages for 4.0.

Any NuGet package that you find right now is not official so we can't guarantee it will work properly, I did experiment with it in the past around the 3.2 release but I deprecated it and don't recommend using it as it won't work on projects exported with the Release configuration.

**Comment by MikeSchulze** [comment]
Thank you very much for your time.

As far as I understand, I now have to configure my project without GodotSharp package reference. But I need to manually install the correct version of GodotSharp to compile it.

But I don't want to have extra project.godot in the module just to install the right version of GodotSharp. This would mean a manual step via `godot -rebuild-solutions` every time I check it out fresh from the repository.
A simple `dotnet restore` + `dotnet build` is not currently possible, or am I missing something?


You can close as clarified.

**Comment by raulsntos** [comment]
If you have the Godot editor available, you could manually copy the DLLs from the `GodotSharp/Api` directory next to the Godot editor binary and then you can `dotnet build`. The important part is to make sure that the DLL you use doesn't break [binary compatibility](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/breaking-changes#binary-breaking-change) with the DLL used by the consumer.

By the way, the PR that broke binary compatibility in this case was https://github.com/godotengine/godot/pull/58608 because it changes the `GetMeta` method to add an extra parameter. Even though the added parameter is optional, since the method signature has changed they are technically different methods so that's why it throws a `MissingMethodException`, usually you can avoid this by adding a method overload instead of modifying the method but since the C# API is generated from ClassDB we don't have much control over it.

**Comment by MikeSchulze** [comment]
Short update i have removed the usage of GetMeta/SetMeta and use instead a dedicated Node class with explicit Get/Set methods and it works.
