### ISSUE TITLE
Can not edit projects in Godot 3.5

### ISSUE THREAD

**Issue by TheDjgamerProductions** [godotengine/godot#64322]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10 (Version 21H2 Build 19044.1889), CPU: Intel I7-9700k x64, GPU: MSI GeForce GTX 1660 Driver Version 31.0.15.1694 

### Issue description

I am able to run projects from the launcher but not edit them.
When trying to edit a project in Godot, the Godot splash screens shows up, then crashes after a second.
This is what the log shows after the crash
```
ERROR: Condition "res != ((HRESULT)0x00000000)" is true. Returned: String()
   at: get_system_dir (platform/windows/os_windows.cpp:3677)
ERROR: Condition "res != ((HRESULT)0x00000000)" is true. Returned: String()
   at: get_system_dir (platform/windows/os_windows.cpp:3677)
```

While on Godot 3.4 I did not face this issue

### Steps to reproduce

1. Open a project

**Comment by Calinou** [comment]
@TheDjgamerProductions  Can you reproduce this in any of the [3.5 betas and RCs](https://downloads.tuxfamily.org/godotengine/3.5/) to determine when the regression started?

**Comment by TheDjgamerProductions** [comment]
I can not edit a project on any of the betas or RCs

**Comment by tinmanjuggernaut** [comment]
Can you create and edit a new project from 3.5?

The code and line specified is here in the get_system_dir function:
https://github.com/godotengine/godot/blob/991bb6ac74ac8c09d7683041b50a8ced3a2defb1/platform/windows/os_windows.cpp#L3677

Here is the gdscript version and documentation page:
https://docs.godotengine.org/en/stable/classes/class_os.html#class-os-method-get-system-dir

Looks like it can't access one or more of your system directories. https://docs.godotengine.org/en/stable/classes/class_os.html#enum-os-systemdir

Go through all of them and ensure that the user running Godot has read and write access to all of those named folders. Also make sure of your godot projects directory, and your %appdata%\godot folders. You may need to take ownership and reset permissions. Also run a file system check before changing permissions.

FOLDERID_Desktop, FOLDERID_Downloads, etc shown in the C++ code are defined by the windows API 
If you search for them here, you'll find default paths, eg FOLDERID_Ringtones = `%LOCALAPPDATA%\Microsoft\Windows\Ringtones`
https://docs.microsoft.com/en-us/windows/win32/shell/knownfolderid

If there's still trouble after these, please attach your full log found in %appdata%\godot. And your if you are accessing the project folder on a local drive and what file system.

**Comment by TheDjgamerProductions** [comment]
I can create new projects in 3.5 but can not edit them.
Taking the new project made in 3.5 and importing it into 3.4 I can edit it.

I have full permissions on all of the systemdir listed.
Even after resetting perms, I still can not edit a project.

I can not find any log inside of %appdata%\godot.
![image](https://user-images.githubusercontent.com/40590952/184464468-50a574d3-c36d-4479-b52e-241dba7d7866.png)

I am using an SSD with an NTFS and Ext4 partition

**Comment by tinmanjuggernaut** [comment]
It's likely a problem with windows or any custom set up you've done.  The problem is that Godot is calling this function:
`SHGetKnownFolderPath(id, 0, NULL, &szPath);` and getting a not-ok error back. Unfortunately Godot doesn't print out the error code. That is an oversight on the developer's part. Anyway, that function is a windows function, not Godot code. It's failing because windows doesn't like the parameters given. You can google SHGetKnownFolderPath and look at general troubleshooting articles on why it is failing. Some might be code issues, but others will be about OS issues.

Such as, did you change your document, downloads or other profile directories to alternate locations? Try resetting them to defaults.

Try moving godot and the project files onto your ntfs partition and remove ext4 out of the equation.

The log is just what is printed to the console, where you got the original error message. Please post the whole thing. In a text file or zipped if it's large.

Another thing you can use is procmon and trace all file accesses around the time you get the error messages, especially the ones it displays as failures. Then figure out what's wrong with those files or directories. 
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

If what you know about your custom configuration, or procmon doesn't reveal the fundamental problem, the best way to identify the cause would be for you to build Godot 3.5 branch from source (https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html), then set a break point on the code I identified, and trace execution of loading a project until it prints out the error message. Then you can find out the contents of the variables and the exact file it's attempting to access and the error message.

**Comment by TheDjgamerProductions** [comment]
I think this may be an issue with my current installation of windows, as it does not want to reset my pictures folder, even if I change its key in regedit.

I will try to reset/reinstall my windows when I next get the opportunity to do so.

Thanks so much for helping out!

**Comment by siddharth-narayan** [comment]
I am having this same problem. I can link a procmon log but I don't have a way of fixing it right now.

**Comment by tinmanjuggernaut** [comment]
> I am having this same problem. I can link a procmon log but I don't have a way of fixing it right now.

@siddharth-narayan The same questions and troubleshooting steps from the beginning apply to you. It's likely a windows problem based on your custom configuration of Windows. The procmon log is for you to identify what configuration you've done so you can try resetting it back to defaults at least for testing.

I don't know why Godot cares about these folders, but this section of code has been unchanged for 3 years. Perhaps code that calls this section has changed more recently. However, at least hundreds of people if not thousands have been using Godot 3.5, even before 3.4 was released, and so far it's limited to the two of you. Some code might be able to be changed to account for your particular situations, but only if you can identify the cause on your system and it is apparent that it should be addressed in Godot rather than on your individual system. Since it's not reproducible by any dev yet, you're the only ones who can troubleshoot.

@TheDjgamerProductions Did you remember to run regedit as administrator? It annoyingly won't ask you automatically.

**Comment by TheDjgamerProductions** [comment]
> @TheDjgamerProductions Did you remember to run regedit as administrator? It annoyingly won't ask you automatically.

I do remember a UAC prompt popped up when I ran regedit,

**Comment by siddharth-narayan** [comment]
I'm running Windows 11 Home with very basic programs and games installed, and haven't really touched anything serious on my system, so I don't know what I could have done. I'm still very new to Github's versioning system, and I don't really know C++, but I'm sure I can give some more debug information or find out what the problem is. Give me some time to compile different versions and I will get back on what the problem might be

**Comment by tinmanjuggernaut** [comment]
@siddharth-narayan before getting into debugging the engine, start with producing the Godot log, and then use procmon to look for what file access errors there are when the Godot error happens. We still have not received any full Godot log or procmon errors. We don't need the full procmon log, you filter it and include only the immediately timed, relevant part.

**Comment by siddharth-narayan** [comment]
I compiled a couple different versions. Godot 4.0-alpha 4dbb63c ran absolutely fine, and managed to open my (completely empty) project after a prompt to upgrade from the old format. 3.5.1.rc failed to open a completely empty project, along with 3,5 stable.

Here is the output from 3.5 stable running with --verbose:
https://pastebin.com/7JsFDPDi

Here is the procmon log. What I did for this is capture only file events from Godot. I waited until the project selection had come up before capturing any events, to not clutter up the log even more. If you want everything from the beginning of starting Godot I can provide that too:

[Logfile.PML.txt](https://github.com/godotengine/godot/files/9351357/Logfile.PML.txt)

**Comment by tinmanjuggernaut** [comment]
Thanks for the logs. I don't see any accesses of the windows profile directories. Try renaming `C:/Users/siddh/AppData/Roaming/Godot/editor_settings-3.tres`, and see if that helps. If not please attach it.

The next step is for you to do what I said here:
>  set a break point on the code I identified, and trace execution of loading a project until it prints out the error message. Then you can find out the contents of the variables and the exact file it's attempting to access and the error message.

You can do this on the project manager, and don't have to load the full game since you get the error in both places.  I would start the breakpoint at the beginning of the function and step through the execution. It may get through a few times without error since there are multiple calls.

**Comment by siddharth-narayan** [comment]
Looking through the code, I have a general idea of what is going on. I the problem is Windows trying to sync with Onedrive. I disabled Onedrive functionality, but this effectively breaks the documents and pictures folder, as well as others. because their paths are supposed to be C:\user\Onedrive\documents or something like that. I tested it by assigning a new String strid, and then assigning it appropriately inside the case switch. I also changed

ERR_FAIL_COND_V(res != S_OK, String()); 

to

ERR_FAIL_COND_V(res != S_OK, String(), String(), String(p_dir));

In this case it seems that SHGetKnownFolderPath would set res equal to E_FAIL given that the folder we want does not exist.
And sure enough, running the program after compiling with these changes shows that the folder that Godot wants access to is SYSTEM_DIR_DOCUMENTS.

I remember getting back the normal documents folder on a previous Windows installation by deleting the old Onedrive synced folder, and putting a new documents folder in the user folder, but this unfortunately did not work for me, but as soon as the documents folder issues are fixed, this problem should be solved.

**Comment by tinmanjuggernaut** [comment]
Good job troubleshooting.

The Godot enum `SYSTEM_DIR_DOCUMENTS` means the windows enum `FOLDERID_Documents` which defaults to `%USERPROFILE%\Documents`.

I use OneDrive on win10 and 11 and have had no issues with the 3.5 branch. 

My current system directories stored in my registry are as follows. Rebooting may be necessary after editing these.
`Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders`

![image](https://user-images.githubusercontent.com/632766/184930179-b6086392-5ae5-434e-81be-f3786ebb2bf0.png)
Reference: https://answers.microsoft.com/en-us/windows/forum/all/move-documents-folder-from-onedrive-to-local/c01276d7-c246-4f2a-9e61-d35a63dc6e93


I have a local documents and a onedrive documents folder.

![image](https://user-images.githubusercontent.com/632766/184930885-21bc7805-848b-4c77-a6ab-4797cb5fb187.png)


This is the reset button mentioned on the properties of the Documents folder, which just edits the registry as above.

![image](https://user-images.githubusercontent.com/632766/184931787-cee30b84-141b-4135-a5da-3e348a2475fe.png)


@TheDjgamerProductions Since @siddharth-narayan fixed his problem, let us know if you've fixed yours. You can close this ticket when resolved.

**Comment by siddharth-narayan** [comment]
I wonder if there is anything that can be done on Godot's side. Ultimately this is an issue with Windows not doing a great job with Onedrive synchronization, but it is a bad user experience to download Godot, create a project and instantly crash without any way of knowing what just happened.

**Comment by tinmanjuggernaut** [comment]
It's 3+ year old code that only the two of you have had issues with so far. I have onedrive and windows with no issue. Perhaps @akien-mga or @Calinou can decide if they want to classify it as bug, or perhaps they want to expand error messages at the least to provide more information about what its failing on and why.

**Comment by siddharth-narayan** [comment]
The best thing to do would probably be to just give a better error message if so few people have had problems with it. It also seems to be limited to just 3.5 so it should be fine for people to just come look at this thread if they have this problem.

**Comment by TheDjgamerProductions** [comment]
>@TheDjgamerProductions Since @siddharth-narayan fixed his problem, let us know if you've fixed yours. You can close this ticket when resolved.

This might have to be a thing I have to take to the Microsoft Support Forums due to the fact that when I try resetting my pictures folder it gives me an error.

I currently do not have access to my pc so I can not currently give details about the error.

**Comment by siddharth-narayan** [comment]
The error happened for me too, after I clicked through it it seemed as though it ended up working anyway. you might want to additionally delete any existing replica folders before you try to reset, at which point the reset button will prompt you to create the folder. It then gave me an "access is denied" error, which is what I clicked through. Mess around with it and see if you can get it to work. Hope you get it!

**Comment by Zireael07** [comment]
WHY does Godot want Documents, etc. anyway? That's a code smell and likely to be a problem on school/corporate settings/network too.

**Comment by TheDjgamerProductions** [comment]
> The error happened for me too, after I clicked through it seemed as though it ended up working anyway. you might want to additionally delete any existing replica folders before you try to reset

Sadly it did not work even if I clicked through the error, or deleted replica folders.
I have now made a post on the Microsoft Support Forum and I am hoping for the best. If the worst comes to be I can just reinstall windows!

Not closing the ticket RN just in case a reinstall does not work.

**Comment by TheDjgamerProductions** [comment]
Someone over at the Microsoft help forums has helped me in resetting my pictures folder but this has sadly not fixed my godot issue.

Sorry for taking so long to get the procmon log to you (I am a bit dumb and did not know how to filter it properly) but here it is [Logfile.zip](https://github.com/godotengine/godot/files/9358685/Logfile.zip).

**Comment by siddharth-narayan** [comment]
It should be the documents folder that you are resetting. If that still doesn't work and if you know how to compile the source you can follow the modifications I made to the 3.5 stable os_windows.cpp or you can compile the 4.0 where the problem seems to be gone. If even that doesn't work you can get someone else to compile for you, or I would be happy to send you my version with the modification for the better error.

**Comment by TheDjgamerProductions** [comment]
> It should be the documents folder that you are resetting. 

My documents folder has been reset a while ago, it was my pictures folder that got caught in the shuffle when I uninstalled onedrive
![image](https://user-images.githubusercontent.com/40590952/185117597-12188eaf-b9d2-45ca-af10-d90bd6dc0c21.png)

I can try compiling by myself following the instructions but sadly I do not know any c++ (I am a python programmer)
If you want you could send over your custom compiled version and I will see if it works!

**Comment by siddharth-narayan** [comment]
https://drive.google.com/file/d/1NHsGHefzh_y56DU0bjSwwcb1fONEumk0/view?usp=sharing

**Comment by TheDjgamerProductions** [comment]
@siddharth-narayan Thanks for sending your custom build but it sadly still crashes, it's currently late rn where I live so I do not feel like trying to modify it and compiling it myself right now. I will try doing this tomorrow.

Sadly this looks like its going to end in me re-installing windows or just using Godot only on my linux partition

**Comment by siddharth-narayan** [comment]
It should crash, it is a simple modification, where if you run from commandline it outputs which folder it is trying to access. That's the only reason I was able to do it with my close to zero knowledge of c++

**Comment by TheDjgamerProductions** [comment]
> It should crash, it is a simple modification, where if you run from commandline it outputs which folder it is trying to access. That's the only reason I was able to do it with my close to zero knowledge of c++

Sorry my bad, I will run and see the output

**Comment by TheDjgamerProductions** [comment]
Ok so interesting thing, even tho my documents folder says it is in the default location 
![image](https://user-images.githubusercontent.com/40590952/185139519-4f488c3a-0d7b-4099-aaaf-037d123697d4.png)
The console still outputs it fails trying to get my documents folder

```
ERROR: SYSTEM_DIR_DOCUMENTS
   at: (platform\windows\os_windows.cpp:3685)
ERROR: SYSTEM_DIR_DOCUMENTS
   at: (platform\windows\os_windows.cpp:3685)
Editing project: C:/Users/dylan/Documents/Development/5. Apps/Godot/Battle Engine Test (C:::Users::dylan::Documents::Development::5. Apps::Godot::Battle Engine Test)

Godot Engine v3.5.stable.custom_build.991bb6ac7 - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
Async. shader compilation: OFF

ERROR: SYSTEM_DIR_DOCUMENTS
   at: (platform\windows\os_windows.cpp:3685)
ERROR: SYSTEM_DIR_DOCUMENTS
   at: (platform\windows\os_windows.cpp:3685)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v3.5.stable.custom_build (991bb6ac74ac8c09d7683041b50a8ced3a2defb1)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] embree::TaskScheduler::instance
[1] embree::TaskScheduler::instance
[2] embree::TaskScheduler::instance
[3] embree::TaskScheduler::instance
[4] embree::TaskScheduler::instance
[5] embree::TaskScheduler::instance
[6] embree::TaskScheduler::instance
[7] embree::TaskScheduler::instance
[8] BaseThreadInitThunk
-- END OF BACKTRACE --
================================================================
```

**Comment by siddharth-narayan** [comment]
So Windows does some weird stuff with onedrive. Instead of syncing things in C:\user\documents to a onedrive folder, it syncs everything in C:\user\onedrive check and see if you still have the onedrive folder in your user folder, if yes, delete it and then try to reset again. Create a new documents folder in your user folder and tell windows to reset it again. If windows complains that it already exists, delete it and try resetting it then.

**Comment by tinmanjuggernaut** [comment]
Does your registry look like mine, posted above? 
https://github.com/godotengine/godot/issues/64322#issuecomment-1216878417

Have you taken ownership and reset file permissions on your documents folder?

**Comment by TheDjgamerProductions** [comment]
> Does your registry look like mine, posted above?

Yes, my registry looks like yours (except for the part where my pictures folder is on a separate drive)
![image](https://user-images.githubusercontent.com/40590952/185144907-c99c0e47-036b-45db-afe1-7ff9f4d59e51.png)

I have taken ownership and reseted permission on the folder before, but I might try again soon.

**Comment by siddharth-narayan** [comment]
I'm including the 4.0 alpha build, hopefully it works for you

https://drive.google.com/file/d/1PSFBU6zn4pqqF7AwpUKoYc_6jKf2i06O/view?usp=sharing

**Comment by TheDjgamerProductions** [comment]
I have taken ownership of the folder and reset permissions yet this has still not fixed the problem
![image](https://user-images.githubusercontent.com/40590952/185149640-c9320e84-f71d-4494-be94-3ee67606a017.png)

Running the 4.0 build @siddharth-narayan gave me allowed me to actually open and edit a project but still gave me the error as a notification
![image](https://user-images.githubusercontent.com/40590952/185150835-336de13c-1dd3-4f1a-93c7-e79b51cf9e3a.png)

While I can just use 4.0 I much rather use a stable build plus my school is using stable as well

**Comment by siddharth-narayan** [comment]
Using linux is definitely a good option, if you need to use windows, see if the documents folder under This PC in file explorer is clickable. If it does not give an error message, then this might actually be a bug with godot.

![image](https://user-images.githubusercontent.com/26383051/185152724-6918dfab-b117-4b4e-be03-49dfdcb811ea.png)

**Comment by TheDjgamerProductions** [comment]
My documents folder is clickable

**Comment by siddharth-narayan** [comment]
@tinmanjuggernaut I don't know where to go from here. Can we get some insight as to why Godot even wants access to the documents folder? It doesn't seem to want to place any files there anyway.

**Comment by tinmanjuggernaut** [comment]
> Yes, my registry looks like yours (except for the part where my pictures folder is on a separate drive) 

It does not look like mine! Godot is reporting it can't access your documents folder. You do not have a documents folder listed. It is not Personal. It is `{F42EE....` as I mentioned. Look again at mine. https://github.com/godotengine/godot/issues/64322#issuecomment-1216878417

It is discussed in the reference I sent. You can get the full string here, read about it, and recreate it manually.
https://answers.microsoft.com/en-us/windows/forum/all/move-documents-folder-from-onedrive-to-local/c01276d7-c246-4f2a-9e61-d35a63dc6e93

> Can we get some insight as to why

Why? I don't know. I'm not an engine developer. You can go to the code I mentioned, get the `git blame` from the buttons on the left and see who wrote it if you want to ask them.

**Comment by TheDjgamerProductions** [comment]
> It does not look like mine!
I am sooooo sorry for missing that and wasting your guys time, this has now fixed it and I am going to close the ticket.

Once again so sorry for missing that, but I guess that is what happens when you debug when you are sleep deprived

**Comment by tinmanjuggernaut** [comment]
Glad to hear it was fixed for both of you. Thanks for your help @siddharth-narayan .
