### ISSUE TITLE
 [3.5] C# EditorInspectorPlugin.CanHandle(Godot.Object) was not called properly

### ISSUE THREAD

**Issue by xuaii** [godotengine/godot#64381]
### Godot version

3.5.stable

### System information

Windows 11

### Issue description

When I followed the [inspector plugin tutorial](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html?highlight=inspector), I found that after **changing** the edited property name and **rebuilding**, `EditorPlugin.Handles` will be called normally and `EditInspectorPlugin.CanHandle` will no longer be called. In gdscript they will all be called normally.

### Steps to reproduce

1. [inspector plugin tutorial](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/inspector_plugins.html?highlight=inspector)
2. Create a Node2D node named main
3. Attach main.cs to node main
```c#
public class main : Node2D
{
    [Export] public int a = 0;
}
```
4. Inspector is displayed normally
5. Change the property name(a -> b) and build
```c#
public class main : Node2D
{
    [Export] public int b = 0;
}
```
6. The Inspector panel will not appear with a random number button

**Comment by raulsntos** [comment]
The project assembly is also loaded by the editor in order to execute Tool classes (such as a custom `EditorInspectorPlugin`) so when the project is re-built the editor needs to reload the assembly.

After the assembly is reloaded, C# forces a refresh of the inspector so the properties and signals are updated, this should trigger the inspector calling `CanHandle` again (and it does) but your script is no longer a `CSharpInstance`, instead it's a `PlaceHolderScriptInstance`.

When a script can't be instantiated by the editor we use a placeholder instead, the main reason why a script can't be instantiated in the editor is that the class is not a Tool. Like I said at the beginning, for a class to be executed in the editor it needs to be a Tool class. In C# this means the class needs to have the `[Tool]` attribute. Can you confirm that adding the attribute to the `EditorInspectorPlugin` and `RandomIntEditor` classes fixes the issue? In that case this is a documentation issue.

**Comment by xuaii** [comment]
> 项目程序集也由编辑器加载以执行 Tool 类（如自定义类），因此当重新生成项目时，编辑器需要重新加载程序集。`EditorInspectorPlugin`
> 
> 重新加载程序集后，C# 强制刷新检查器，以便更新属性和信号，这应该会再次触发检查器调用（确实如此），但您的脚本不再是 ，而是 .`CanHandle``CSharpInstance``PlaceHolderScriptInstance`
> 
> 当脚本无法由编辑器实例化时，我们使用占位符，脚本无法在编辑器中实例化的主要原因是该类不是工具。就像我在开始时说的，要在编辑器中执行一个类，它需要是一个工具类。在 C# 中，这意味着类需要具有该特性。您能否确认将属性添加到 和 类可以解决问题？在这种情况下，这是一个文档问题。`[Tool]``EditorInspectorPlugin``RandomIntEditor`

Thank you very much for your answer, adding the `[Tool]` attribute to `EditorInspectorPlugin` and `RandomIntEditor` did solve this problem, as you said it was a documentation problem, thank you very much.

**Comment by xuaii** [comment]
> The project assembly is also loaded by the editor in order to execute Tool classes (such as a custom `EditorInspectorPlugin`) so when the project is re-built the editor needs to reload the assembly.
> 
> After the assembly is reloaded, C# forces a refresh of the inspector so the properties and signals are updated, this should trigger the inspector calling `CanHandle` again (and it does) but your script is no longer a `CSharpInstance`, instead it's a `PlaceHolderScriptInstance`.
> 
> When a script can't be instantiated by the editor we use a placeholder instead, the main reason why a script can't be instantiated in the editor is that the class is not a Tool. Like I said at the beginning, for a class to be executed in the editor it needs to be a Tool class. In C# this means the class needs to have the `[Tool]` attribute. Can you confirm that adding the attribute to the `EditorInspectorPlugin` and `RandomIntEditor` classes fixes the issue? In that case this is a documentation issue.

Thank you very much for your answer, adding the `[Tool]` attribute to `EditorInspectorPlugin`  and  `RandomIntEditor` did solve this problem, as you said it was a documentation problem, thank you very much.
