### ISSUE TITLE
NavigationRegion3D - Referencing runtime generated navmesh property returns editor generated navmesh property

### ISSUE THREAD

**Issue by Vododovoodvod** [godotengine/godot#64437]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Kubuntu 22.04, kernel: 5.15.0-46-generic (64-bit), Vulkan, NVIDIA GeForce RTX 3050/PCIe/SSE2, AMD Ryzen 7 3700X 8-Core

### Issue description

Referencing navmesh property of NavigationRegion3D does not return newest state. It will return navmesh generated in editor, not new navmesh generated in code. 

Output from attached godot project:
Navmesh vertices from editor: 
(-0.5, 1.5, -0.5)
(-0.5, 1.5, 0.5)
(0.5, 1.5, 0.5)
(0.5, 1.5, -0.5)
Navmesh vertices from realtime baking (edited gridmap): 
(-0.5, 1.5, -0.5)
(-0.5, 1.5, 0.5)
(0.5, 1.5, 0.5)
(0.5, 1.5, -0.5)

### Steps to reproduce

1. Use GridMap to create simple grid
2. Set GridMap as child of NavigationRegion3D
3. Bake NavMesh in editor
4. Add script that will a) add extra tiles to GridMap b) bake_navigation_mesh
5. for v in self.navmesh.get_vertices():
		print(v)
6. Values do not match new state with extra tiles

### Minimal reproduction project

[Uploading NavigationRegion3D_bug_report.zip…]()

Uploading MRP went wrong so I [uploaded it again to Google drive](https://drive.google.com/file/d/1KXsf8kSscpvpUqLpppV8uPvtsnxto2SD/view?usp=sharing)

**Comment by smix8** [comment]
Your MRP link does not work.

The NavigationRegion3D navmesh on top of your GridMap is not the same as the cell navmesh baked inside your GridMap cells.

**Comment by Vododovoodvod** [comment]
**Uploading MRP went wrong** so I [uploaded it again to Google drive](https://drive.google.com/file/d/1KXsf8kSscpvpUqLpppV8uPvtsnxto2SD/view?usp=sharing)

**Comment by smix8** [comment]
The issue is that you are calling everything in the `_ready()` function, at that time most nodes and resources are not fully setup.

NavigationMesh baking happens threaded / deferred in the background, the navmesh is not replaced instantly.
Because navmesh baking parses the entire geometry depending on NavigationMesh properties it needs to wait until all SceneTree nodes are done so a `_ready()` call in a (sub)node is the wrong time to change and bake something procedural. If you disable the threaded baking with `bake_navigation_mesh(false)` and use a deferred function call in your `_ready()` it reports the updated vertices.

```gdscript
func _ready():
    place_cells()
    bake_navigation_mesh(false)
    call_deferred("deferred")

func deferred():
    print(navmesh.get_vertices())
```

If below ~10 mb please upload always directly to github, external links are not reliable in the long run.
[NavigationRegion3D_bug_report.zip](https://github.com/godotengine/godot/files/9337865/NavigationRegion3D_bug_report.zip)

**Comment by Vododovoodvod** [comment]
Your solution works, thanks for helping out.

So no bug after all, I will close the issue.
