### ISSUE TITLE
Printing an array of strings with a `?` character will escape that character as `\?`

### ISSUE THREAD

**Issue by Capital-EX** [godotengine/godot#64520]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Manjaro 21.3.6 Ruah on Linux 5.10

### Issue description

When using `JSON::parse` in Godot 4.0 alpha 14. It appears that issues #3334 has been re-introduced.

Expected result from Godot:
![image](https://user-images.githubusercontent.com/13488718/185028605-1e759946-808e-43ad-89a1-d6d67b1a84d2.png)

Actual result from Godot:
![image](https://user-images.githubusercontent.com/13488718/185027905-0a38135c-9b2f-40a1-b1b5-64adedf7e394.png)

### Steps to reproduce

1. Use JSON::parse on any string containing `?`
2. Result will be produced as `\?` instead of just `?`

### Minimal reproduction project

[question-mark-bug.zip](https://github.com/godotengine/godot/files/9356101/question-mark-bug.zip)

**Comment by Capital-EX** [comment]
Actually, turns out this has nothing to do with JSON.parse. It appears how Godot converts `?` into `\?` when turning an array into a string. Is this intended behavior?

**Comment by Calinou** [comment]
> It appears how Godot converts ? into \? when turning an array into a string. Is this intended behavior?

Probably not – I don't see why this escape would be needed.

**Comment by Capital-EX** [comment]
Where is Array printing handled? I've been looking around the code to see if I could find the issue because the fix feels small.

**Comment by kleonc** [comment]
> Where is Array printing handled?

https://github.com/godotengine/godot/blob/dbd15243621ec595742b18abc4c26f3cb2e00f3d/core/variant/variant.cpp#L1787

Specifically the cause of this issue is `c_escape()` in here:
https://github.com/godotengine/godot/blob/dbd15243621ec595742b18abc4c26f3cb2e00f3d/core/variant/variant.cpp#L1755-L1768

It was made like this in #60609.

**Comment by Capital-EX** [comment]
Doing some digging around it appears that [`\?`](https://github.com/godotengine/godot/blob/de53e91b856aba0e0ac100707376c8de9f50b4d1/core/string/ustring.cpp#L3887) exist do to [trigraphs](https://en.wikipedia.org/wiki/Digraphs_and_trigraphs#C) in C and C++.

**Comment by Mickeon** [comment]
Looking at the c_escape() function:

https://github.com/godotengine/godot/blob/dbd15243621ec595742b18abc4c26f3cb2e00f3d/core/string/ustring.cpp#L3876-L3891

`escaped = escaped.replace("\?", "\\?");` looks to be written appropriately, but then I look at the debugger and...
![image](https://user-images.githubusercontent.com/66727710/185248303-7d8bbc78-be6e-4aec-bc49-418e925779a3.png)

"`\\?`" is then visualised as "`\?`" because... you may know how double slashes work.

**Comment by Mickeon** [comment]
I don't know how to address this other than straight-up removing the "?" character, or making the logic for detecting trigraphs make a bit more sense. The compiler really seems to translate the standalone "\?" to "?". That is the issue, it seems.

**Comment by Mikerhinos** [comment]
I read a distant JSON file that returns an ASCII list, that I then transform in a string with result.get_string_from_ascii() and parse it back to JSON, it's working on Godot 3.5 but not with 4.0, possibily because of 4.0 converting that seems to have changed a lot of code.

Output extract example in 3.5 : 
{MOVIE:[{"title": "movie title", etc.

Output of what 4.0 get : 
{"MOVIE": "[{\"title\": \"movie title\", etc.

Not sure if related but it adds a lot of " so it has to escape some, tried to do some replace('\\"', "'") with a few variations like "\\\"" etc. but it's not replacing anything, or it gets it back because when I print it there's still the " and \" not in original JSON so I can't access values.
