### ISSUE TITLE
GDScript 2.0: ``class_name`` apparently doesn't do anything

### ISSUE THREAD

**Issue by julhe** [godotengine/godot#64543]
### Godot version

v4.0.alpha.custom_build [deb3f8eb3]

### System information

Windows 10

### Issue description

When trying to reference a class from another file, Godot will show an error: Indentifier "Bar" was not found in the current scope, even though that other class is doing ``class_name Bar``. (I'm not very familiar with Godot 4, but this looks like a bug.) 
___
Hope thats helpfull:

Uppon debugging, I found that in ``gdscript_analyzser.cpp:3049``, ``class_exists(name)`` will return false for my class name. I also found that ``_add_class2()`` in ``class_db.h`` is apparently never called somewhere. Note that I can declare a class name twice (see ``Bar2.gd``), so I think that ``_add_class2()`` isn't called is an oversight?

### Steps to reproduce

See the script Foo.gd in the example project.

### Minimal reproduction project

[Godot4_Class_Name_Issue.zip](https://github.com/godotengine/godot/files/9365033/Godot4_Class_Name_Issue.zip)

**Comment by 01010100010100100100100101000111** [comment]
It looks like you have class_name Bar defined in both Bar2.gd and Bar.gd, if you comment out everything in Bar2.gd, you will then get an error against SaySomething() because you have no instance of the class, you could change SaySomething to static func SaySomething() so you don't need the instance.

If you want a non static func, you would need to create an instance in Foo.gd _ready like;

	var x = Bar.new()
	x.SaySomething()

Hope that helps

**Comment by julhe** [comment]
The issue seems to be related to my custom build.
