### ISSUE TITLE
Project refuses to start when using openxr in linux

### ISSUE THREAD

**Issue by croxis** [godotengine/godot#64584]
### Godot version

4.0.alpha14

### System information

Arch linux, AMD 5700xt, swaywm/wayland

### Issue description

I enabled xr support per the current latest documentation: https://docs.godotengine.org/en/latest/tutorials/xr/setting_up_xr.html

A pop up window  says 
```
"Your video card driver does not support any of the supported Vulkan or OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU, upgrade it.
If you have updated your graphics drivers recently, try rebooting." 
```
I have rebooted since my last update.

The output in terminal says:
```
 ~/src/ITF  on main ⇡1 !5  godot4                                                                  255 ↵  took 9s
VR Server (v1659988962)

Using breakpad crash handler
Setting breakpad minidump AppID = 250820
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
OpenXR: Running on OpenXR runtime:  SteamVR/OpenXR   0.1.0
Godot Engine v4.0.alpha14.official.106b68050 - https://godotengine.org
OpenXR: XrGraphicsRequirementsVulkan2KHR:
 - minApiVersionSupported:  1.0.0
 - maxApiVersionSupported:  1.2.0
OpenXR: Failed to obtain vulkan physical device [ XR_ERROR_RUNTIME_FAILURE ]
ERROR: Condition "err != OK" is true. Returning: ERR_CANT_CREATE
   at: _window_create (drivers/vulkan/vulkan_context.cpp:1444)
ERROR: Can't create a Vulkan window
   at: _create_window (platform/linuxbsd/display_server_x11.cpp:4554)
```

This does not happen if XR-->Shaders is enabled but XR->OpenXR is still disabled

### Steps to reproduce

Written above

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/59505 (possible duplicate)? However, nobody reported the issue on Linux yet.

**Comment by Cyberrebell** [comment]
I did some tests:
Arch Linux, RX 6600, Valve Index, SteamVR "beta" branch (1.24.1)
I did test using the default GPU driver (RADV) and for me both worked X11 and wayland. My app did start and render. (ignoring the fact that SteamVR on Linux is a big mess at the moment...)

@croxis are you using RADV or AMDVLK?

**Comment by BastiaanOlij** [comment]
@croxis happened to have run into this as well just now, if you're problem is the same as mine we need to improve the error message (or exit earlier on).

With OpenXR on Vulkan, OpenXR takes over the creation of the OpenXR context. The problem is that SteamVR will exit if you don't have your headset plugged in, as a result OpenXR will not fully initialise, as a result Vulkan will not initialise, and as a result Godot reports that you're hardware doesn't support Vulkan.

In reality it's that OpenXR failed to start.

At least that is what I ran into, it is still possible there is more going on if OpenXR does properly start but for some reason breaks Vulkan...
