### ISSUE TITLE
Channging authority of MultiplayerSynchronizers that control spawned nodes does not work.

### ISSUE THREAD

**Issue by TheGodojo** [godotengine/godot#64599]
### Godot version

v4.0.alpha14.official [106b68050]

### System information

Windows 10, Vulkan

### Issue description

The character controlled on the server syncs to the clients just fine, but synchronizers with multiplayer_authority properties set to anything other than 1 seem to stop working.

### Steps to reproduce

multiplayer_peer.peer_connected.connect(
		func(id):
			await get_tree().create_timer(2).timeout
			add_player_character(id)
	)

func add_player_character(id=1):
	var character = preload("res://player_character/player_character.tscn").instantiate()
	character.name = str(id)
	add_child(character)

##In player character script:

@onready var multiplayer_synchronizer = $MultiplayerSynchronizer
func _ready():
	multiplayer_synchronizer.set_multiplayer_authority(str(name).to_int())

![image](https://user-images.githubusercontent.com/104181056/185531168-af064164-9101-42cd-816a-5cf61257def9.png)

![image](https://user-images.githubusercontent.com/104181056/185531204-6152bf67-4074-4823-a1ac-a3395cf630b5.png)

### Minimal reproduction project

[Mulitplayer Nodes.zip](https://github.com/godotengine/godot/files/9378818/Mulitplayer.Nodes.zip)

**Comment by GuilhermeGSousa** [comment]
Seem to be having the same issue, the variables aren't synced if `set_multiplayer_authority` is set on `_ready`

**Comment by JotaFaD** [comment]
Also happening on alpha 15.

**Comment by GuilhermeGSousa** [comment]
Could I take a stab at solving this one?

**Comment by Calinou** [comment]
> Could I take a stab at solving this one?

Sure, go ahead :slightly_smiling_face:

**Comment by Faless** [comment]
@GuilhermeGSousa some notes on the issue after I spent some time debugging it.

The problem lies in the internals of the replication system.
Currently, each node can have one spawner (which spawned it) and one synchronizer.
In cases where the authority of the two mismatch, the system fails to sync (due to how network IDs are assigned).
On the other hand changing the authority of a synchronizer which does not control the root node of the spawned scene, will work as expected, e.g.:

```
- Player
  - ServerSynchronizer (auth=1)
  - ClientController
    - ClientSynchronizer (auth=client)
```
![working_mixed_sync](https://user-images.githubusercontent.com/1687918/190600121-e5e4f8ca-246a-4035-ba03-2c9553b585e1.png)

works as it should. Interestingly, the `ClientSynchronizer` can correctly set properties of `Player` too, when assigning `..:property` as property (or by just drag and dropping it from the inspector):

![synchronizer_stroked](https://user-images.githubusercontent.com/1687918/190602227-8990c95a-1817-4fd4-85d7-e23ddd0eca40.png)

I think we should start by adding a warning when we detect the authority mismatch, possibly suggesting the above setup to the developer.

Then see if we can change the internals to support this use case (which likely requires splitting the spawner NetID and synchronizer NetID).

**Comment by GuilhermeGSousa** [comment]
Just tried out your solution on the project @TheGodojo attached to the issue, works perfectly well although I agree it is not exactly intuitive. I'll open a PR to add a warning in case of auth id mismatch.

There is a point to be made that having client-side authority is a common use case: helps reduce input lag and for some games giving the authority to a client is an acceptable risk. In those use-cases it could be nice to make `MultiplayerSynchronizer` more user friendly.

**Comment by Faless** [comment]
This issue will be fixed by https://github.com/godotengine/godot/pull/66794 , but requires a small change to the user code which will also be reported by that PR with an explanation.
The change in question is setting the multiplayer authority during the `_enter_tree` callback instead of the `_ready` callback, i.e., in `player_character.gd`:

```gdscript
# player_character.gd
func _enter_tree():
	$MultiplayerSynchronizer.set_multiplayer_authority(str(name).to_int())
```
