### ISSUE TITLE
Volumetric Fog goes dark on the edges when a Fog shader is used

### ISSUE THREAD

**Issue by Hannyson** [godotengine/godot#64634]
### Godot version

4.0.alpha12

### System information

Archlinux

### Issue description

I use a FogVolume type World, to decrease the fog density with the altitude. When it goes near 0.0, the color switches to a much darker color on the last appearing line.

### Steps to reproduce

Create a FogVolume type World, with a new ShaderMaterial and a fog shader :

```glsl
shader_type fog;

void fog() {
	ALBEDO = vec3(1.0);
	DENSITY = mix(0.005, 0.0, WORLD_POSITION.y * 0.01);
}
```

### Minimal reproduction project

[TestVolumetricFogBug.zip](https://github.com/godotengine/godot/files/9384381/TestVolumetricFogBug.zip)

**Comment by Calinou** [comment]
PS: Code blocks should use triple backticks like this (with an optional language name for syntax highlighting):

\`\`\`glsl
code here
\`\`\`

I edited your post accordingly, but remember to do this in the future :slightly_smiling_face:

**Comment by clayjohn** [comment]
This isn't a bug, what you are seeing is the end of the Volumetric Fog. In the MRP it extends to 1024 metres because the Volumetric Fog length is 1024 metres. If you use a smaller value it won't extend as far. Volumetric Fog cannot extend forever so it needs to be mixed with fixed fog if you want to keep fog in the far distance consistent
