### ISSUE TITLE
Referencing Child Node in Parent fails when called from other Child Node

### ISSUE THREAD

**Issue by protodrew** [godotengine/godot#64755]
### Godot version

3.5

### System information

Pop!_OS 22.04

### Issue description

When you call a function from a child node that invokes a var that represents a different child node, the var throw an error that says it is nil

### Steps to reproduce

Make a Scene with 2 child nodes, I tested this with an Audiostreamplayer, as it was when I encountered the bug, and the other 2 were both Node2D

have the other child node call a parent function that references the other child node as an onready var

try again but use the reference directly, (I.E using $AudioStreamPlayer instead of a variable that represents it)

you will see the first one fails but the second does not.

### Minimal reproduction project

[Scene_Reference_Bug_Project.zip](https://github.com/godotengine/godot/files/9398201/Scene_Reference_Bug_Project.zip)

**Comment by protodrew** [comment]
Should specify this error didnt exist in 3.3 afaik

**Comment by akien-mga** [comment]
This doesn't work in 3.3 nor in 3.5 and that's expected, as it's not a bug.

See the [Node](https://docs.godotengine.org/en/stable/classes/class_node.html) class description for details on how parent-child relationships work and the order of calling for `_ready`.

`_ready` is called first on child nodes (while the parent is _not_ ready) and then on the parent once all children are ready. So your code fails because the child node's `_ready()` tries to access a variable that's only initialized once the parent is ready itself.
