### ISSUE TITLE
Area enter shape signal, weird parameters

### ISSUE THREAD

**Issue by germanandino** [godotengine/godot#6480]
**Operating system or device - Godot version:**

Windows 10 - Godot Version 2.1 stable

**Issue description** (what happened, and what was expected):

When connecting Area2D signal, "area enter shape", it generates this line of code

func _on_Area2D_area_enter_shape( area_id, area, area_shape, area_shape ):

Notice the last two parameters, they have identical name. Plus, the code works... duplicated parameter's name should throw an syntax error message IMO

**Steps to reproduce:**

Create a Node2D with a script attached. Put Inside an Area2D. Connect signal, area_enter_shape to Node2D script. Look the generated code.

**Link to minimal example project** (optional but very welcome):
![ccc](https://cloud.githubusercontent.com/assets/15801379/18498205/2564bd14-7a0b-11e6-865d-c0ccbf175955.png)

**Comment by akien-mga** [comment]
The bug is at:
- https://github.com/godotengine/godot/blob/98e73429afccaba88bf0220352ecdc38da1aeca6/scene/2d/area_2d.cpp#L653-L654
- https://github.com/godotengine/godot/blob/91c85ff1f5e83fd7e360ad07abad98684acf6ecf/scene/3d/area.cpp#L643-L643

The actual signal calls in the source are of the form `emit_signal(SceneStringNames::get_singleton()->area_enter_shape,p_id,node,E->get().shapes[i].area_shape,E->get().shapes[i].self_shape);`, so it looks like the arguments should be something like `area_id, area_node, area_shape, self_shape`, whatever that means :D
