### ISSUE TITLE
Right-click on property elements of an array does not pop the property menu in the inspector.

### ISSUE THREAD

**Issue by groud** [godotengine/godot#64916]
### Godot version

v4.0.alpha13.official [59dcddc45]

### System information

Archlinux

### Issue description

Right-clicking on a property that is part of an array element does not pop the property menu:

https://user-images.githubusercontent.com/6093119/186867977-a34ad64e-7d58-4d2c-85ff-5b6e234612da.mp4

(I am right-clicking on each property but nothing pops up, aside from the "array element" menu when i sometimes click between the properties)

### Steps to reproduce

- Create a scene
- Add a TileMap node
- Go in the Layers array
- Right-click on a property name (like Enabled or Modulate)
- Nothing happen
- Press F to pay respects to the popup

### Minimal reproduction project

Any new project would fit the reproduction steps.

**Comment by TamerSoup625** [comment]
I also got this bug and found out some useful info about it:

- This bug also happens when right-clicking on a resource's property.
![main tscn - Stealth bc I couldn't find a project to do - Godot Engine 22_10_2022 19_11_12](https://user-images.githubusercontent.com/107559799/197353542-2d35a1b1-f2f5-4fef-b71c-c6e359914531.png)
- The bug no longer occurs if using single-window mode.
https://user-images.githubusercontent.com/107559799/197353720-86990dc0-1108-49e7-9914-1522a0231d9e.mp4
- The popup for the tilemap layers appears as well in single-window mode, but there's still the double popup from #55401
https://user-images.githubusercontent.com/107559799/197353804-75f93a38-c2fb-48f7-b430-4ef7ad33771a.mp4
