### ISSUE TITLE
EditorPlugin ability to determine/change current editor state

### ISSUE THREAD

**Issue by kubecz3k** [godotengine/godot#6497]
**Issue description** (what happened, and what was expected):
It would be nice if from editor plugin there would be ability to determine various information about editor state. Some of the properties that come to my mind:
- [x] Currently active scene
- [x] Currently active script
- [x] List with all opened scripts
- [x] List with all opened scenes
- [x] Currently active tab [2D|3D|Script|Other]
- [x] Current script content
- [ ] List with plugins that are enabled
- [ ] Current cursor position in script
- [ ] Current word under the cursor in script

I also think there should be a way to change at least some of those properties, so:
- [x] Ability to open script (as far as I know already possible with inspect object api)
- [x] Ability to open scene https://github.com/godotengine/godot/issues/6495
- [ ] Ability to close script (remove from opened scripts list)
- [ ] Ability to close scene
- [ ] Ability to set cursor position in active script

**Comment by MolbOrg** [comment]
> Ability to close scene
anyone?
opening works, closing would be nice

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
