### ISSUE TITLE
Opening any doc display it with incorrect theming

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#64997]
### Godot version

006915b4824a91c0e0fc95ac6aa2f70908a0a027

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/3036176/187087876-ab2c8f66-a261-49b0-bbe2-9a33421f6668.png)

### Steps to reproduce

Open any doc item in the editor help

**Comment by akien-mga** [comment]
CC @AaronRecord

**Comment by AaronRecord** [comment]
Good catch, I'll try and look into tomorrow

**Comment by faisal-alam09** [comment]
Works fine on Ubuntu 22.04 LTS
![Screenshot from 2022-08-29 00-48-57](https://user-images.githubusercontent.com/94897163/187091029-a2864743-133a-407d-a00b-139f53ca2506.png)

**Comment by AaronRecord** [comment]
I can reproduce the problem on my computer (also Win 11, although I'm guessing that's unrelated?)

**Comment by AaronRecord** [comment]
Okay so this is weird, I can't reproduce with a debug build compiled with msvc, but I can reproduce with the release builds from the CI checks (both on commit cb62d3193)

**Comment by Xwdit** [comment]
If I switch themes in the editor settings, everything goes back to normal, I think it's a regression related to themes or related notifications. It may be regression introduced by https://github.com/godotengine/godot/pull/62846 ?

**Comment by AaronRecord** [comment]
> If I switch themes in the editor settings, everything goes back to normal, I think it's a regression related to themes or related notifications. It may be regression introduced by #62846 ?

It is a regression from #62846

**Comment by JohanAR** [comment]
> > If I switch themes in the editor settings, everything goes back to normal, I think it's a regression related to themes or related notifications. It may be regression introduced by #62846 ?
> 
> It is a regression from #62846

Don't know if you want a new issue for it, but #62846 causes an infinite loop segfault when I try to open one of my current projects. I haven't been able to pin down exactly what's causing it, but EditorLog is asked to log an error, add_image fails due to the theme_cache not being properly initialised, which leads to a new error log, and so on. I added a couple of `if (icon != nullptr)` in around add_image EditorLog to avoid the loop, but instead it got stuck in some other loop instead..
