### ISSUE TITLE
Errors when inheriting scene with animation

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#64990]
### Godot version

4.0.dev (f38ea254f3)

### System information

Windows 10

### Issue description

If a scene has an animation and an inherited scene attempts to override that with different animations (or none) the following errors are shown:
![image](https://user-images.githubusercontent.com/21325943/187077195-ca87e76f-bbcb-41e3-9dac-bf4a7b5fe2ef.png)

### Steps to reproduce

Inherit a scene with an animation.
Override that animation or remove it.

### Minimal reproduction project

[InheritIssue.zip](https://github.com/godotengine/godot/files/9439785/InheritIssue.zip)

**Comment by garychia** [comment]
I'm not familiar with the animation player but the problem seems to disappear after adding the following code, which connects the animation player to "tracks_changed" signals when adding an animation library:
https://github.com/garychia/godot/blob/567bae4ab45fddc6c15206e2afb3839756695ee7/scene/animation/animation_player.cpp#L1381-L1383
