### ISSUE TITLE
Impossible to retrieve physics layer on which a collision occurred

### ISSUE THREAD

**Issue by quantumcode-martin** [godotengine/godot#65009]
### Godot version

4.0.alpha14

### System information

Windows 10

### Issue description

When accessing a collision from `move_and_slide` or  using `get_slide_collision` we get a `KinematicCollision2D`.
I think this type is lacking a `collision_layers` specifying on which layer(s) the collision occurred.

Because otherwise, if the collider is a `TileMap` for example, it is pretty much impossible to retrieve on which layer the collision occurred, and so, with.

I suppose there is a test on layers to detect if there is a collision, if so it would be a good idea to pass the resulting layer(s) to the `KinematicCollision2D`.

Other problem is that it seems pretty much impossible to access any `TileData` from a `TileMap`, it seems like a regression to me as we were able to call `get_cellv` on 3.x (I can open another issue for this problem if needed).

### Steps to reproduce

Create a KinematicBody2D, use move_and_slide and detect collisions with `get_slide_collision`.
Then create a `TileMap` and add a `TileSet` with some collisions on some tiles, use different physics layers.

Now try to retrieve from detected collision, which layer it occurred on.

**Comment by rburing** [comment]
If a collision between bodies occurs, it means that their layers/masks were such that it was allowed to occur, because some bitwise `&` (AND) operation resulted in a nonzero number (so some bits matched). That's all. You can do such a calculation yourself when you know which bodies collided. Note also Unity, Unreal, and Box2D don't report extra information about layers upon collisions (because most people don't need it, and those who do can calculate it after the fact).

Please report the `TileData` issue separately, if it still exists.
