### ISSUE TITLE
Console error when AnimationPlayer get_animation() returns null

### ISSUE THREAD

**Issue by Pennycook** [godotengine/godot#65005]
### Godot version

3.5.stable

### System information

Ubuntu 20.04

### Issue description

Calling `get_animation()` with a string that does not correspond to an animation causes a console error:

![image](https://user-images.githubusercontent.com/857660/187094257-c8675ad8-3e8a-4696-905a-c00a78ac7fa2.png)

This is surprising because the documentation says that `get_animation()` "Returns the `Animation` with key `name` or `null` if not found.", which suggests it is safe to supply any name.

The runtime behavior of the function is correct (it returns `null`), but I don't think this line should throw an error: https://github.com/godotengine/godot/blob/991bb6ac74ac8c09d7683041b50a8ced3a2defb1/scene/animation/animation_player.cpp#L1056

### Steps to reproduce

To reproduce:

1. Create an `AnimationPlayer` with no animations in it
2. Call `get_animation()` with any string
3. Run the project

I've attached a minimal reproduction project created from these steps, which shows the error when run.

### Minimal reproduction project

[get-animation-null.zip](https://github.com/godotengine/godot/files/9440462/get-animation-null.zip)

**Comment by timothyqiu** [comment]
Should this be a documentation error? That behavior is since the beginning of Godot and the description about `null` is added later.

There's indeed exceptions on whether `get_xxx()` errors when there's a corresponding `has_xxx()`. But most of these methods print an error, e.g. `AnimationLibary.get_animation()` / `Node.get_node()` / `LineEdit.get_selection*()` / `TileMapPattern.get_cell*()`.

**Comment by akien-mga** [comment]
Yes the documentation is wrong, the error is intended here. It could be given a proper message to mention what animation name was requested though.
