### ISSUE TITLE
Crash on C# exception while reloading assemblies

### ISSUE THREAD

**Issue by codecat** [godotengine/godot#65032]
### Godot version

v4.0.alpha.mono.custom_build [0b8a63e47]

### System information

Windows 11, Vulkan, 3080

### Issue description

When I build a C# project that generates an exception in the editor, it crashes the editor inside of `godotsharp_internal_script_debugger_send_error` because `EngineDebugger::get_script_debugger()` returns null, and this is not checked.

![image](https://user-images.githubusercontent.com/136534/187188087-1da3cf93-1d51-4be9-bf0b-e602996abd1f.png)

### Steps to reproduce

1. Open the reproduction project
2. Make sure the "crash_test" addon is enabled
3. You should see a gizmo drawing a line in the 3D view
4. In `addons/crash_test/CrashGizmoPlugin.cs`, change `if (true) {` to `if (false) {`
5. Click "Build" in Godot

### Minimal reproduction project

[CrashTest20220829.zip](https://github.com/godotengine/godot/files/9443995/CrashTest20220829.zip)

**Comment by raulsntos** [comment]
> `EngineDebugger::get_script_debugger()` returns null, and this is not checked.

You are not entirely correct about this, it's true that this method can return null but we do guard calls to this method with a call to `EngineDebugger::is_active()` which would return false if the debugger is null so it would never call that method:

https://github.com/godotengine/godot/blob/8c7be63588bf3e4ef4b780ff57936c68db5939c7/modules/mono/glue/GodotSharp/GodotSharp/Core/NativeInterop/ExceptionUtils.cs#L106-L109

The `NativeFuncs.godotsharp_internal_script_debugger_is_active` method calls `EngineDebugger::is_active()` to check that the script debugger is not null, then we call the `SendToScriptDebugger` method which ends up calling `EngineDebugger::get_script_debugger()` but this only happens if the previous check passed.

---

I have been unable to reproduce the crash (with Godot built from commit 3cf16c959) but I do get an error in the console with the C# exception:

```
modules/mono/glue/runtime_interop.cpp:1241 - System.InvalidCastException: Unable to cast object of type 'Godot.EditorNode3DGizmoPlugin' to type 'CrashGizmoPlugin'.
     at crash_test.RestoreGodotObjectData(GodotSerializationInfo info) in /media/raulsntos/Data/GodotProjects/TESTS/CrashGizmo/Godot.SourceGenerators/Godot.SourceGenerators.ScriptSerializationGenerator/crash_test_ScriptSerialization_Generated.cs:line 15
     at Godot.Bridge.CSharpInstanceBridge.DeserializeState(IntPtr godotObjectGCHandle, godot_dictionary* propertiesState, godot_dictionary* signalEventsState) in /media/raulsntos/Data/Godot/src/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 239
```

This is caused by the generated code that handles the restoring of a class when reloading assemblies. This may be expected since the class being reloaded has been modified but I'm not sure.

**Comment by raulsntos** [comment]
@codecat Are you still able to reproduce this issue in the latest release (RC2)?

**Comment by codecat** [comment]
I am not working on the particular project that I was anymore, but I just tested the reproduction project on RC2 and it doesn't seem to crash anymore for me. 👍
