### ISSUE TITLE
Listener2D

### ISSUE THREAD

**Issue by robertdhernandez** [godotengine/godot#6517]
There's a Listener for Spatial but there's no Listener2D for 2D positional audio, which is tied to the viewport position.

**Comment by vnen** [comment]
This would be nice to have for 3.0, which is supposed to have positional audio.

**Comment by reduz** [comment]
was not done, kicking to 3.1

**Comment by Banduck** [comment]
3.1 now, and there is still no 2D Listener :(
Will it be added in 3.1 or do we have to wait for 3.2?

**Comment by akien-mga** [comment]
Probably not for 3.1 at this stage sadly, there are enough features already to finish polishing and bug fixes for the stable release.

**Comment by robertarnborg** [comment]
This would be super great for my horror 2D audio game I am working on.  :(((

**Comment by Calinou** [comment]
@robertarnborg Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by robertarnborg** [comment]
Sorry :(

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by Calinou** [comment]
This issue was superseded by https://github.com/godotengine/godot-proposals/issues/49.
