### ISSUE TITLE
Godot profiler cant start

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot#65209]
### Godot version

v4.0.alpha15.official

### System information

Windows10,Vulkan

### Issue description

I can't start Godot profiler

### Steps to reproduce

I started the Godot profiler before I started the game, but after I started the game, the Godot profiler didn't output any results. I had to turn it off and then turn it on to output
![image](https://user-images.githubusercontent.com/33598732/187968573-648f5f7c-94d3-494f-931d-e87bd4376059.png)
Then, when the game is running, I pause the scene first, and then stop the scene. At this time, I can't start the Godot profiler again
![image](https://user-images.githubusercontent.com/33598732/187969141-6a72c6d6-ea2c-4f19-a2ac-238d4ecfd3ec.png)
![image](https://user-images.githubusercontent.com/33598732/187969362-d530e0d7-9f9e-47b5-ace4-2479b770b9ed.png)

**Comment by BrandonCline** [comment]
[min_repro.zip](https://github.com/godotengine/godot/files/9485546/min_repro.zip)

Three issues here with the profiler, have confirmed reproducible with the attached project Godot version:v4.0.alpha15.official
Windows10,Vulkan.

Issue description.

1. If profiler is started first, and then project is run, the profiler does not connect as expected (compared to 3.5)
    - Stopping and starting the profiler again while the project is running connects to the debug process as expected.
3. While profiler is running, **_if the project has a script on node other than root node_**, pausing the project, or clicking the frame graph output (which pauses the project), causes the **stop button** of the profiler to be grayed out. 
    - Unpausing the project re-enables the **stop button** as expected.
    - Stopping the project leaves the **stop button** in grayed out state. (Unlike 3.5 behavior which re-enables it)
    - Running project while **stop button** is greyed out does not re-enable it. 
    - While project is running, pausing/unpausing will re-enable **stop button**.
    - If the script on the child node is detached while **stop button** is greyed out, pausing/unpausing the project will not re-enable the **stop button**.
 4. While profiler is running, if the project window is given focus the profiler's frame graph update rate is significantly lowered (unlike 3.5).

_* Unsure if the greying out the stop button while the project is paused is intended functionality (as in 3.5), or was removed, but still happens when a script is attached to a child node, perhaps unintentionally? *_
