### ISSUE TITLE
Expose EditorNode to plugins

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#6520]
The core editor plugins have major advantage over GDScript plugins: the access to the `EditorNode` singleton. Many of the `EditorPlugin` functions are just wrappers to `EditorNode` methods.

The core C++ plugins are quite good examples on how to extend the editor but they require unavailable API. For instance, the Theme editor is quite good for being context sensitive. You can't do that in a custom plugin since it's impossible to show and hide the bottom panel without access to `EditorNode`.

Is there a reason why `EditorNode` is not fully exposed?

The alternative, of course, is making more `EditorNode` wrappers inside `EditorPlugin` like I did in #6516.

**Comment by reduz** [comment]
EditorNode changes a lot and the overall interfaces are pretty dirty. The interfaces are abstracted in EditorPlugin just to avoid the mess of EditorNode and provide an API that will be unlikely to change

**Comment by vnen** [comment]
@reduz looking at it now I can understand, but WDYT of my last phrase:
> The alternative, of course, is making more EditorNode wrappers inside EditorPlugin.

There are some useful things to use like `reload_scene()` for importers.

**Comment by kubecz3k** [comment]
I added 3.1 label since I remember reduz was talking about EditorNode refactoring in 3.1. So I guess we will consider then what to do with this issue.

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
