### ISSUE TITLE
`Navigation2D::get_simple_path` Doesn't Return Exact Destination if Reachable 

### ISSUE THREAD

**Issue by BHSDuncan** [godotengine/godot#65257]
### Godot version

3.5.stable

### System information

Windows 10

### Issue description

Prior to Godot 3.5, for a reachable position, `Navigation2d::get_simple_path()` would return as its final element the exact location of the specified destination, i.e. precisely the same.

With Godot 3.5 (which looks like `get_simple_path` now hands off to the new `NavigationServer`), the final element--while very close--is now off by +/- 0.001 (give or take), which, for the values checked, `is_equal_approx` still fails.

E.g. With a start of `(97, 412)` and destination of `(37.452099, 392.045013)` with no obstacles in between, I get the following walk paths:

Godot 3.5: (96.999329, 411.999847) -> (37.451111, 392.044891)

Godot 3.4.4: (97, 412) -> (37.452099, 392.045013)

And doing an `is_equal_approx` between the last element of each path returns `false`, owing to what I guess is the epsilon being used isn't at the appropriate scale.

Perhaps this is a result of the shape of the nav polygon and possibly its placement, as a plain square for a nav poly seems to work all right.

### Steps to reproduce

Run the attached reproduction project and note the values printed to the output window: The first line is the starting point; the second line is the destination point; and the third line is the path resulting from calling `get_simple_path`.

Do this in both 3.4.4 and 3.5, and you'll see the difference and get the values mentioned in this ticket.

(Interesting side note: if that `yield` statement in the main scene's `_ready` is removed, the code still works in 3.4.4, but not 3.5...)

### Minimal reproduction project

[nav2d-issue.zip](https://github.com/godotengine/godot/files/9479746/nav2d-issue.zip)

**Comment by Calinou** [comment]
This may be a configuration error. I recommend looking through `get_simple_path` issues (both open and closed): https://github.com/godotengine/godot/issues?q=is%3Aissue+sort%3Aupdated-desc+get_simple_path

**Comment by BHSDuncan** [comment]
Thanks for the quick response!

I just went through all the issues in the link you provided. I can't seem to find anything similar, and a lot of them seem to deal with using TileMaps which my example doesn't. I'll keep going through them, though, to see if I missed anything.

Is there a specific configuration issue you're thinking about that I should take a look at? I don't see anything in the logs, and the only "error" I'm seeing is the deprecation warning for `get_simple_path`.

**Comment by kleonc** [comment]
> E.g. With a start of `(97, 412)` and destination of `(37.452099, 392.045013)` with no obstacles in between, I get the following walk paths:
> 
> Godot 3.5: (96.999329, 411.999847) -> (35.451111, 392.044891)
> 
> Godot 3.4.4: (97, 412) -> (37.452099, 392.045013)

Seems you have a typo there (should be 37.451111 instead of 3**5**.451111).

![Godot_v3 4 5-stable_win64_T3LZa8Lj0a](https://user-images.githubusercontent.com/9283098/188202506-53d14300-7f84-4575-be0e-8138bd7ace91.png)
![UufsROtRFa](https://user-images.githubusercontent.com/9283098/188202508-4b0c66d0-c300-4fbb-a5fe-398f6c5f68cb.png)


The cause is that `get_simple_path`:
- in `3.4.5` have a dedicated code for 2D and it uses `Geometry::is_point_in_triangle` for checking whether the start/end points are in the navigation polygon triangles (if they are it sets the path start/end to such exact points):
https://github.com/godotengine/godot/blob/f9ac000d5dc0d1014fa347fb2f23069b294d511a/scene/2d/navigation_2d.cpp#L247-L267
- in `3.5.stable` (and `master`) there's no dedicated 2D code, `NavigationServer2D` is just a wrapper around the `NavigationServer3D` (it just treats `Vector2(x, y)` as `Vector3(x, y, 0)` etc.). And in 3D case points are not checked whether they belong to the triangle because in general they're not guaranteed to be on the same plane as the triangle/face. So instead for the given point (start/end) the closest point on each triangle/face is being calculated and used as potential start/end of the path. And these calculations (`Face3::get_closest_point_to`) seem to result in the observed inaccuracy:
https://github.com/godotengine/godot/blob/b38ac3f09fb5386ba8236db2b3efcf654a9e27d8/modules/navigation/nav_map.cpp#L91-L110
https://github.com/godotengine/godot/blob/b38ac3f09fb5386ba8236db2b3efcf654a9e27d8/core/math/face3.cpp#L322


Potential solutions:
- Make `Face3::get_closest_point_to` give more accurate results (not sure if / how much feasible).
- Snap the result of `Face3::get_closest_point_to` to start/end position if it's close enough. Note that (as @BHSDuncan pointed out) currently `actual_start_point.is_equal_approx(returned_path_start)` may return `false`, meaning the epsilon/threshold for _"close enough"_ would need to be bigger than the one used in `is_equal_approx` (otherwise this issue would still be present).
- Make the `NavigationServer2D` be not a wrapper around the `NavigationServer3D`. A dedicated code would allow to simplify some calculations etc. and should make things more precise and performant. Of course the cost would be some code duplication, which would be harder to maintain.

**Comment by BHSDuncan** [comment]
Thank you for pointing out the typo--you're absolutely right, it was.

And thank you for confirming this. For the project I'm working on, we may just do our own "custom" version of `is_equal_approx` for now.

**Comment by smix8** [comment]
Should take the lazy option and just set the end position to the destination position when both are very close to each other. In general I wouldn't expect equal positions with any navmesh path at all but I am also not a 2D user. 

Not sure the `Face3::get_closest_point_to` should be touched as it is a core math function properly used somewhere else. The 2D navigation is upscaling everything a lot e.g. a 3D world units that is real world meter is only a tiny 2D pixel. This adds room for more precision problems and errors and makes function like is_equal_approx() fail a lot compared to 3D.

If the past years of Godot 2D navigation maintenance and development is anything to go by splitting 2D off from 3D (again) would be a death-sentence for 2D navigation.

**Comment by smix8** [comment]
This issue can be closed.

As discussed among navigation devs and with OP in the linked thread there are no plans to bring back the old "snapping" behavior.

There are a multitude of smaller reasons why but the major one is properly the already brought up example with e.g. is_equal issues that are common place. What can be considered "equal enough" for a position snapping is entirely project specific.
