### ISSUE TITLE
Compression functions (zlib/gzip/deflate) in GDScript

### ISSUE THREAD

**Issue by vnen** [godotengine/godot#6536]
I'm missing ways to compress/decompress data in GDScript. I believe this would be quite useful to compress data to send over network or compressed assets/saves to be used by the game.

Since Godot already bundles zlib, this would not be hard to do for zlib/gzip wrapper formats and pure deflate compression.

**Comment by mattiascibien** [comment]
@vnen seems interesting, if I can find some time (very busy at work) I can look into it. Any ideas on the names and signatures of the methods?

**Comment by vnen** [comment]
I was thinking about a new class actually. So you can choose options (compression level, strategy), add data in chunks and get the result as a `RawArray`.

Adding a ZipFile class would be interesting too, though that goes a little beyond since it has directory structure.

**Comment by romeojulietthotel** [comment]
Since you're example was to put data out over the network it would be good and useful to compress then encrypt the data (in that order).  This will fit in nicely with peer-to-peer and client/server networking. Argon2 is a new encryption scheme that just won the password-hashing contest so maybe that would make a suitable choice. I hear bcrypt is good also. As for compression what does upx use?

**Comment by vnen** [comment]
I don't intend to add any extra dependency to Godot. Any particular need for specific libraries can be provided as custom modules.

Argon2 and bcrypt are both *hashing* functions and tailored for *password* hashing (so they're slow). I see no common use case for password hashing in a game engine. For actual encryption, I believe OpenSSL provides AES functionality but that's a topic for another issue.

It seems UPX uses UCL, LZMA and zlib for compression. Though I don't see the need for multiple compression libraries. There are already zlib and FastLZ libraries bundled in Godot and I believe those are enough.

**Comment by romeojulietthotel** [comment]
This request had caught my eye because I am looking at compression and encryption in my game. Compression is not complicated but I don't know much about encryption (or hashing) until recently. And you're right hashing would not make sense because it's a one-way function. You can't get the original content from something that's been hashed. But with encryption you do get the original of course. I am looking forward to what we do for compression and for encryption I will have to figure that out. I agree about not adding dependencies.

**Comment by vnen** [comment]
@romeojulietthotel for encryption there's issue #1969 (and a proposed solution in #5868). I do want to have a take in this compression, but not sure if I'll have time to make it before 2,2 is out. If you're in a hurry, it shouldn't be hard to create a custom module to expose compression functionality.

**Comment by nicholatian** [comment]
Would very much like to see this implemented in Godot 2.x, at some point. Compression isn’t exactly something you can implement efficiently in a script itself, so it’s probably best to create a wrapper for the C++ code that handles it better. I’m surprised Godot doesn’t have support for general-purpose compression in some form already!

**Comment by Catprog** [comment]
@vnen 
The only case I can see for password hasing is for in game 'passwords'. I.e  If you have a safe puzzle then you hash the answer and it cannot be found by decompiling the code.
