### ISSUE TITLE
controls only accepts integer values ​​for set_pos 

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#6540]
Godot version: v.2.2.alpha.custom_build on linux

Issue description:
controls only accepts integer values ​​for set_pos.
No decimal values accepted.

Steps to reproduce:
create new scene with a TetureFrame control

set_pos(Vector2(1.5,1.5))
print(get_pos()) #print (1, 1) in output

**Comment by Hinsbart** [comment]
This happens because calling `set_pos()` on a control just re-calculates and sets the margins internally.
So the problem here is that the margins are integer values.
However I don't know if changing this will break compatibility or even makes sense.
So, might be a candidate for #6523

**Comment by VictorSeven** [comment]
This bug happens to me also in Godot 2.1.stable.official, in Windows 7 x64. In my case I am using a generic `Control` node, so it does not affect the TextureFrame only, but probably all controls.

I comment it in order to call your attention about this one, which is a very annoying bug in a very basic function xD

Hope it gets fixed soon!

**Comment by bojidar-bg** [comment]
"bug in a very basic function" -- Don't know... if you want to use floating-point positions, you can use Node2D nodes. For Control nodes it makes less sense since texts can easily get blurred if you leave it in half-pixel position.

So, I'm with @Hinsbart on that -- I don't know if it makes sense to have, even if won't break compatibility.

Maybe it makes sense for Animating the values...

**Comment by volzhs** [comment]
I think it would be better if it's float.
I had a little issue with it.
when animating this `Control`'s size, inner `Control` looks a little bit jumpy.

**Comment by bojidar-bg** [comment]
Ok, given new evidence from #9464, I guess it makes sense after all... 👍

**Comment by AlexHolly** [comment]
I am not sure if this is exactly the same issue(#9464), when I use set_position everything works like expected at least the use cases I tried...

**Comment by AlexHolly** [comment]
Looks like my issue was solved how about this one?

**Comment by bojidar-bg** [comment]
This is not closed yet, that PR just fixed some of the symptoms. We still have to discuss if controls should have integer or floating-point positions.

**Comment by reduz** [comment]
I don't know what's going on anymore here, what is missing?

**Comment by bojidar-bg** [comment]
Well, nothing is missing, this issue is just a discussion about whether Control nodes should have floating-point positions and anchors, or integer. It is potentially related to #9889.

**Comment by groud** [comment]
I would say that with floating anchors implemented in #9889, this issue can be closed.

**Comment by reduz** [comment]
Controls are now floating point. To avoid issues (fonts looking like ass)  I added the option to snap controls to pixels (which is on by default)). Closing this.
