### ISSUE TITLE
Ctrl+Backspace is too hungry

### ISSUE THREAD

**Issue by TX256** [godotengine/godot#6546]
When one erases "empty" text (i.e. tabs) with Ctrl+Backspace, also code is deleted.

An example, let's say I have redundant tabs at the end of a method:

`|` == caret position
`T` == tab

```
func _on_ok_pressed():
    save_settings()
    Game.show_title()
        T
        T
        T  T  T  |
```

Pressing CTRL+Backspace just once erases not only the tabs, but also the `show_title()`

 I find this quite awkward - and I think it'd be better to either:
1. Erase one full row of tabs
2. Just erase all the tabs

**Operating system or device - Godot version:**
Windows 10, Godot 2.2. Alpha custom build

**Issue description** (what happened, and what was expected):
See above.

**Steps to reproduce:**
See above.

**Link to minimal example project** (optional but very welcome):
N/A

**Comment by flurick** [comment]
I have been poking around at this, turns out there are a lot of detail. I have it removing white-spaces, symbols or text characters until some other type is found. There are some weird stuff going on with quotes mostly because of color coding, you probably expect everything in the same color to be removed, might be nice to use that code for removing data chucks instead of randomly by character types if possible.

**Comment by nbcks** [comment]
I'm getting the same issue(?), I think option 2. would be very nice.
