### ISSUE TITLE
Vulkan: Transparent window not working

### ISSUE THREAD

**Issue by Xwdit** [godotengine/godot#65487]
### Godot version

4.0.alpha16

### System information

Windows11, Nvidia RTX 2060, Vulkan

### Issue description

![image](https://user-images.githubusercontent.com/44023235/188925445-7eff4728-5bae-4e14-9577-ec5ce45cf014.png)
I followed what was described in PR https://github.com/godotengine/godot/pull/65283 , But only got the same black background as before. But if I switch to Gles3 renderer everything works fine.

### Steps to reproduce

- Enable `display/window/per_pixel_transparency/allowed` in the project settings.
- Disable viewport background with `get_viewport().transparent_bg = true`.
- Set transparent flag for a window with `DisplayServer.window_set_flag(DisplayServer.WINDOW_FLAG_TRANSPARENT, true, window_id)`

**Comment by Calinou** [comment]
@Xwdit Can you try this on the latest `master` branch (now that https://github.com/godotengine/godot/pull/67104 is merge)d?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by ChildLearningClub** [comment]
Hi @Calinou, This does still appear to be an issue. I'm using 4.4 dev 5 on Forward + it is a black background. Switching to Compatibility works.
