### ISSUE TITLE
Godot 4: Switching to GLES3 - Windows/Popups Blank

### ISSUE THREAD

**Issue by eumario** [godotengine/godot#65510]
### Godot version

4.0 alpha 16

### System information

Windows 11 - GLES3

### Issue description

When switching a project from Vulkan Driver, to GLES3, and restarting the Editor, the Editor will open up, but any popup created, will be the standard Grey interface, that will not display any contents, be it project settings, or Menus.  Attempting to change Editor Settings to use Single Window Mode, does not change the error.

### Steps to reproduce

Create any project, with Default Vulkan renderer, switch to GLES3, and save and restart.  Only way to switch back, is to go to project.godot, and change driver from gles3, to vulkan to get interface back for poups (Window Dialogs / Menus)

**Comment by akien-mga** [comment]
Multiple window support doesn't work with OpenGL3 currently indeed, that's a known issue.

In the meantime, we should likely force single-window mode (embedded popups) when using OpenGL3 @clayjohn.

**Comment by eumario** [comment]
Mind you, I have tried to use Single Window Mode in the Editor Settings, and it doesn't work, so it would need to be forced, and removed as an option in Editor Settings, if GLES3 is detected.  Just wanted to make sure that was clear that it isn't fixed just by selecting the option.

**Comment by clayjohn** [comment]
This issue is a regression from https://github.com/godotengine/godot/pull/63091, prior to that multiwindow appeared to work. That being said, last week I spent some time investigating this issue and once I "fixed" it I noticed that multiwindow merely appeared to work, it updated the new window correctly, but whenever a new window was opened, the previous window(s) would freeze as all updates from all windows would get applied to the newest window opened. 

I have a WIP branch to fix this for x11 and should be able to fix Windows shortly after. I don't know if if it is working on MacOS or not.

We could force enable single-window mode in the meantime.
