### ISSUE TITLE
Export to Web fails from Windows (file in use and can't be overwritten)

### ISSUE THREAD

**Issue by Nuku** [godotengine/godot#65660]
### Godot version

4.0 alpha 16

### System information

Windows 11

### Issue description

![image](https://user-images.githubusercontent.com/886729/189538395-85240878-cfca-4a77-8b70-cbfe4feebbaf.png)
All other exports work fine, but web produces this error each time. I've tried changing what directory it saves to, no difference.

### Steps to reproduce

Export, add, Web, export project.

**Comment by Nuku** [comment]
![image](https://user-images.githubusercontent.com/886729/189544907-aaa71c40-fd05-431b-8973-562ce8b5a167.png)
Re-naming the tmp file it creates allows it to be uploaded, but then this error is visible in the console of the resulting page.

**Comment by GithubPrankster** [comment]
I also have this same issue and can attest to @Nuku's fix working. Their following error is due to the environment not having SharedArrayBuffer defined which is required now for 4.0.

**Comment by Calinou** [comment]
> Re-naming the tmp file it creates allows it to be uploaded, but then this error is visible in the console of the resulting page.

You need to use a web server that sends the correct headers, as threads are now required.

**Comment by Thisisntmatt** [comment]
I experienced this and setting a custom html shell in the export settings will allow it to export.
![image](https://user-images.githubusercontent.com/87195335/190276557-38d47412-8cf7-42e8-89f9-664a8864cfbb.png)

**Comment by alfredbaudisch** [comment]
- Can confirm that on alpha17 export to web generates the same `lacking permissions` error from OP
- Using "Custom HTML Shell" with https://github.com/godotengine/godot/blob/master/misc/dist/html/full-size.html then the export works

**Comment by akien-mga** [comment]
> But then with the Custom HTML Shell the application does not run:

That's not a bug, see https://github.com/godotengine/godot/issues/65660#issuecomment-1243088017

**Comment by alfredbaudisch** [comment]
> > But then with the Custom HTML Shell the application does not run:
> 
> That's not a bug, see [#65660 (comment)](https://github.com/godotengine/godot/issues/65660#issuecomment-1243088017)

> You need to use a web server that sends the correct headers

I'm using a web server.

**Comment by akien-mga** [comment]
You need to use a web server *that sends the correct headers*: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy#certain_features_depend_on_cross-origin_isolation

And on a secure context.

**Comment by alfredbaudisch** [comment]
Yes, I have everything setup accordingly already (the correct headers, SSL, etc). I'll try to test on Itch to see how it reacts.

**Comment by alfredbaudisch** [comment]
@akien-mga on Itch.io, with both `SharedArrayBuffer` support on or off, I got the error:

![image](https://user-images.githubusercontent.com/248383/190452393-f2325f11-658a-4d7a-898f-fe8f68307bfd.png)

**Comment by Thisisntmatt** [comment]
@alfredbaudisch I got it to work on my webserver by setting the correct cors headers(I used Node.js):
`return res.sendFile(path.join(__dirname + '/public' + '/Web8' + req.url)), res.setHeader("Cross-Origin-Opener-Policy", "same-origin"), res.setHeader("Cross-Origin-Embedder-Policy", "require-corp") ;`
I guess mostly work, animated textures all come out pink, but that's a different issue for a different thread

**Comment by nisovin** [comment]
> @akien-mga on Itch.io, with both `SharedArrayBuffer` support on or off, I got the error:
> 

Itch.io's support for this feature currently only works in Chrome, and I think that looks like Firefox.

**Comment by Nuku** [comment]
Using chrome, but not on Itch.io
https://flexiblesurvival.com/resources/FI/play.html

**Comment by alfredbaudisch** [comment]
@nisovin @Thisisntmatt @Nuku I confirm that on Chrome it works both in my local server and Itch.

**Comment by vkbsb** [comment]
Created PR https://github.com/godotengine/godot/pull/65881
for fixing the locked file issue. The output file was opened for read and then for write. The instance opened for write is closed before the one opened for read. This causes the _close() on the instance opened for write to fail.

**Comment by Deins** [comment]
Got it working for myself, but bumped into few issues on the way. 
Here are my tips for those who want to run it with current alpha:
1. set custom http export shell line like mentioned above (to workaround the file locking issue). If the build errors the `.tmp` or other files won't work.
2. use webserver and set correct headers like people said. I used nginx I set mine:
```
            add_header Cross-Origin-Opener-Policy same-origin;
            add_header Cross-Origin-Embedder-Policy require-corp; 
```
3. Also your webserver has to serve the files as **https**. Might depend on browser, not  sure, but it seemed that with plain http  I got the same `SharedArray` error .
3. first experiment from scratch with empty project. Otherwise you might get errors until you figure out what feature breaks it. For me I had enabled in project settings 'multithreaded renderer' which didn't work. And sky shader with clouds also didn't run.

here is sample, so you can test your browsers: https://www.deins.lv/godot_test/

**Comment by Nuku** [comment]
![image](https://user-images.githubusercontent.com/886729/190803773-197a0053-fcbe-49cd-aa05-11039f9e40fa.png)
Did that, new fancy error.

**Comment by nisovin** [comment]
@Nuku That's the original posted error, caused by the failed rename.

**Comment by Deins** [comment]
I got that error only when trying to use `.tmp` http shell. Did you do:

> I experienced this and setting a custom html shell in the export settings will allow it to export. ![image](https://user-images.githubusercontent.com/87195335/190276557-38d47412-8cf7-42e8-89f9-664a8864cfbb.png)

**Comment by Nuku** [comment]
What do you set the custom shell to?

**Comment by Deins** [comment]
> * Can confirm that on alpha17 export to web generates the same `lacking permissions` error from OP (no need for reproducible project, try any HTML export)
> 
>     * Using "Custom HTML Shell" with https://github.com/godotengine/godot/blob/master/misc/dist/html/full-size.html then the export works
>       But then with the Custom HTML Shell the application does not run:
> 
> 
> ![image](https://user-images.githubusercontent.com/248383/190371787-7fa585f6-1e86-4313-a31e-1347d92c6f70.png)

**Comment by Zireael07** [comment]
I see things need to be documented better...

**Comment by tripodsan** [comment]
> here is sample, so you can test your browsers: https://www.deins.lv/godot_test/

on macos, running in chrome (Version 105.0.5195.125 (Official Build) (x86_64))  just hangs the browser and I need to force-quit it. in safari it works for me.

**Comment by Spycemyster** [comment]
Might be related to this issue, but this is from a web export for a web game I'm developing (using Google Firebase as a backend)
![image](https://user-images.githubusercontent.com/6189001/193945471-b1834aaf-8b49-41f4-8e37-c5b67e9e1414.png)

I've used the custom shell described above and I'm on Godot 4 beta 2.

**Comment by Calinou** [comment]
> Might be related to this issue, but this is from a web export for a web game I'm developing (using Google Firebase as a backend) ![image](https://user-images.githubusercontent.com/6189001/193945471-b1834aaf-8b49-41f4-8e37-c5b67e9e1414.png)
> 
> I've used the custom shell described above and I'm on Godot 4 beta 2.

This is not a bug. You need to host the project files on a web host that sends the correct headers as described in the [Exporting for the Web](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads) documentation.

**Comment by Spycemyster** [comment]
> > Might be related to this issue, but this is from a web export for a web game I'm developing (using Google Firebase as a backend) ![image](https://user-images.githubusercontent.com/6189001/193945471-b1834aaf-8b49-41f4-8e37-c5b67e9e1414.png)
> > I've used the custom shell described above and I'm on Godot 4 beta 2.
> 
> This is not a bug. You need to host the project files on a web host that sends the correct headers as described in the [Exporting for the Web](https://docs.godotengine.org/en/latest/tutorials/export/exporting_for_web.html#threads) documentation.

Ah I see, my mistake! I forgot to add the headers to my firebase.json file. I'll post what I have for posterity's sake in case anyone has the same problem as I did:
```
  "hosting": {
    "public": "public",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "headers": [ {
        "source" : "**",
        "headers" : [
            {
            "key" : "Access-Control-Allow-Origin",
            "value" : "*"
            },
            {
                "key" : "Cross-Origin-Opener-Policy",
                "value" : "same-origin"
            },
            {
                "key" : "Cross-Origin-Embedder-Policy",
                "value" : "require-corp"
            }
        ]
    }],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  },
```
Deploying to Firebase hosting using that as my firebase.json file fixed it.

**Comment by Nuku** [comment]
What should you put in the custom section?

**Comment by sanchitgulati** [comment]
If anyone is wondering how to do this on apache24 server.

- Uncomment  the line that says `LoadModule headers_module modules/mod_headers.so` in your httpd.conf file
- Add the following lines at the end of the httpd.conf file  

```
<IfModule mod_headers.c>
  <Directory />
    Header always set Cross-Origin-Opener-Policy "same-origin"  
    Header always set Cross-Origin-Embedder-Policy "require-corp"  
  </Directory>  
</IfModule>  
```

**Comment by netAction** [comment]
For .htaccess, you can use this:

<IfModule mod_headers.c>
  Header always set Cross-Origin-Opener-Policy "same-origin"  
  Header always set Cross-Origin-Embedder-Policy "require-corp"  
</IfModule>

**Comment by AwokeKnowing** [comment]
As a long-time developer I think this path of Godot 4 for the web is problemmatic. I realize it's the browsers coming up with all these security policies but projects generally can be set up to run with no webserver modification provided that all the content is self-contained.

It seems Godot will end up having to create a docker container and be deployed basically with integrated webserver.
In other words, I think rather than trying to convince people to add headers to webservers, people expecting an index.html file to 'just work' probably want:
1. a bash script to make it work in web locally or on server
2. a docker container that runs locally and can be just put on server/aws
3. powershell script same as the bash script but for windows.
4. the interface of godot should do this for you initially.

Now, once they have it running, they may investigate and find oh, i can do this myself with just a couple headers.  But the problem is that when you're working in godot and just click export to web, you expect it to basically just work since it's for web and you have a browser.

At least, this message is not nearly as helpful as those familiar with the problem imagine:
Error
The following features required to run Godot projects on the Web are missing:
Cross Origin Isolation - Check web server configuration (send correct headers)
SharedArrayBuffer - Check web server configuration (send correct headers)

most people who know some web development don't really know about shared array buffers and obscure Spectre mitigation headers.

So you would at least have to give a user friendly message saying like:
```
Godot 4 uses advanced browser features which are only available if your server sends the following headers on the response for the HTML file:
Cross-Origin-Opener-Policy "same-origin"
Cross-Origin-Embedder-Policy "require-corp"

To set up a preconfigured webserver to run godot 4 projects in the browser, click here.  For deployment to a webserver however, you will need to make sure the two headers are sent back when this html file is requested.
```

I can' guarantee you that 99% of people exporting to web, even literal game developers would not just know what to do from the current message.  They would end up frustrated and digging through docs and forums, when they expected it to just run in the browser, like a normal self-contained html5 app.

Having godot 4 apps showing up all over the web is going to be huge. so I seems worthy of streamlining.

**Comment by Calinou** [comment]
> As a long-time developer I think this path of Godot 4 for the web is problemmatic. I realize it's the browsers coming up with all these security policies but projects generally can be set up to run with no webserver modification provided that all the content is self-contained.

This can be worked around without any specific web server configuration. See https://github.com/godotengine/godot-proposals/issues/6616.

**Comment by AwokeKnowing** [comment]
Thanks. I added it here because here was where I found the 'solution' so i wasn't aware of anywhere else it was being worked on. at time i didn't realize it was closed, so i was just about to delete it and post as separate issue.

In any case, I'm glad you responded with the link to the correct place to discuss since I have a feeling some people will pass through this way until the workaround becomes automatic.
