### ISSUE TITLE
GDScript 2.0: Casting to Zero when using property

### ISSUE THREAD

**Issue by Ajrarn777** [godotengine/godot#65675]
### Godot version

4.0.16

### System information

Windows 10

### Issue description

When using a property and casting the value from an INT to a FLOAT, produces very strange result.

See to step to replicate.

It seems when we assign a property to a float, the internal variable type is corrupted.

### Steps to reproduce

```gdscript
#===============================================================================
var Value:int = 0 :
	get:
		return Value
	set(v):
		Value = v
		
#===============================================================================
func Test():
	var f:float 
	var n:int 
	
	Value = 7
	f = Value
	n = int( f )   # Here : f = 7, and n = 0 ??? <<<<<<<<<<<<<<<<<<<<<<<< BAD !!!

	f = 4
	n = int( f )   # Here : f = 4, and n = 4 GOOD
```

**Comment by KoBeWi** [comment]
`prints(f, int(f))` prints `7 0` 🤔
The bug only occurs if you use a getter.

**Comment by anvilfolk** [comment]
Digging a little into this one :)

It appears that there is no conversion happening between the int from the getter and the float `f`.

```GDScript
	f = Value
	print(typeof(f) == TYPE_INT)
```

This will print `true`, which it shouldn't, because `f` is supposed to be a `float`.

Furthermore, in those conditions it appears that the constructor for the variant of type int might actually skip a few steps and forget to assign the value? I'm digging in a little more.

**Comment by anvilfolk** [comment]
Ok, so I got a fix in, but I'm not convinced it's completely thorough.

Essentially getters were not their return address types in the compiler, meaning that the compiler wouldn't know to create an `OPCODE_ASSIGN_TYPED_BUILTIN` instead of an `OPCODE_ASSIGN`.

Somehow I still believe that it's possible to fool the compiler into creating an `OPCODE_ASSIGN` rather then the typed variant, which will result in the same issue: the `float` variant containing an `int`.

Which also doesn't solve problem number 2, which is that calling `int()` on something strange like a float variable with an int inside results in a zero.
