### ISSUE TITLE
Feature: Promotable Properties 

### ISSUE THREAD

**Issue by jeremyjh** [godotengine/godot#6571]
**Operating system or device - Godot version:**
Any platform, Godot 2.1

**Issue description** (what happened, and what was expected):

I may be approaching my node hierarchy design incorrectly in which case feedback is welcome, but I think there may be an interesting feature possibility based on the little bit of experience that I have.

I think it would be interesting if there was a way for a parent node to promote specific properties of its children, so that when the parent is instanced into a scene that those child properties could be set directly for that instance, rather than replicated from parent to children by script. 

An example...

I've created a Player scene hierarchy that I instantiate into my scene for each game player. Right now my player scene looks like

```
 player (RigidBody2D)
  - Sprite
  - CollisionPolygon2D
  - control_move(Node)
```

`control_move` is just a node with a script attached that implements simple controls, it exposes a variable `player_speed`,`player_number`. Its `player_number` is used to build an Input name unique to that player's controls. I may move this in to a plugin later.

Right now my player parent node *also* has to expose `player_number`, and it has to pass this along at initialization to its child. Player parent also exposes an `extern (Texture) texture` which it passes along to the Sprite child:

```godot
func _ready():
	get_node("Sprite").set_texture(texture)
	control.player_number = player_number
```

In a perfect world, `player` could simply promote the texture of `Sprite` and `player_number` from those child nodes, so that when instanced I could set those properties on player and then I wouldn't need any script at all in player - the engine would transparently reference the actual property for me. 

As for implementation - well that I am not qualified to say but perhaps a dynamic script object would have to be created for the parent class, and any user defined script would have to subclass that. Probably not nearly as simple as the idea is - but any alternative ideas are welcome.

**Comment by razvanc-r** [comment]
If I understand you correctly you want to change some properties of this `player` node from the inspector, but are not able to do it because it's a property of a child that you want to really change. I don't see this useful, you can already change those properties in the inspector, it's just not on the `player` node, but on the child node. I think your proposal would lead to confusion. Unless I'm not understanding correctly.

**Comment by reduz** [comment]
You can edit and set properties of child nodea for that specifix instance,
just make it editable

**Comment by bojidar-bg** [comment]
@reduz The problem with this approach is that it looks ugly in most cases, plus it is easy to forget about having made modifications to it.

Maybe something like a checkbox or similar that would show certain child node properties on the root of its scene?

**Comment by jeremyjh** [comment]
@reduz Thanks, I hadn't realized this was an option. 

@bojidar-bg Yes showing certain child properties on the root of the scene is exactly what I'm asking for, sorry if that wasn't clear. I'm not sure if its really that big of a benefit though if there is already a way to at least edit those properties at the instance level, which is what I thought was missing.

**Comment by Zylann** [comment]
I feel like whenever you expect a behaviour that is beyond the current Inspector, what you need to do is to write an editor plugin that creates a brand new edition panel.

But because it looks too much work for simple features (categories, property promotion), we prefer having a simple way with a keyword, or a special feature in GDScript.
But simple features are piling up.

I am somehow against these types of language features because it would start to clutter GDScript more and more, mixing user interface (editor) and script logic to a point it becomes a mess.
Having the representation of the inspector separate from the script itself seems tedious, but IMO in a longer term it is better to cleanly separate logic and editor UI (MVC, anyone?).

In your case, having a top-level property forwarding to the child looks fine to me, and it's clearer to understand when reading the code.
The one downside I see however, is that the value could end up being saved in two places instead of one, which could be an issue.

**Comment by jeremyjh** [comment]
I'm going to close this; I tried out the editable children option and it does what I need, thanks!

**Comment by reduz** [comment]
@bojidar-bg It's not ugly, it shows nodes only if they are editable and you can see which properties where modified. Maybe we could also show which nodes were changed.
