### ISSUE TITLE
Updating shader samler2d results in pink texture (alpha 16)

### ISSUE THREAD

**Issue by CoreTaxxe** [godotengine/godot#65719]
### Godot version

4.0-alpha16

### System information

Windows 11, Vulkan, RTX 3070 V. 516.94

### Issue description

Setting shader sampler2D texture with non static texture loader causes texture to be loaded pink.
Using the static loader works perfectly fine.
Looks like regression to #63442

![image](https://user-images.githubusercontent.com/47256718/189753860-cd0eda15-c692-41d4-afe7-b293be45d5c7.png)
nonstatic

### Steps to reproduce

1. Create shader with Sampler2D uniform.
2. Use **non**-static Texture constructor.
3. Set shader param.

### Minimal reproduction project

[Uploading sampler2d.zip…]()

**Comment by clayjohn** [comment]
The issue here is the ImageTexture you create is lost because it is not assigned to anything. 

In earlier alpha builds the API for ImageTexture was changed so that ``create_from_image()`` became a static function which returns the created ImageTexture (see [docs here](https://docs.godotengine.org/en/latest/classes/class_imagetexture.html#class-imagetexture-method-create-from-image))

So the proper code is
```
txt = ImageTexture.create_from_image(image);
```
