### ISSUE TITLE
Suggestion: non-blocking breakpoints

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#6576]
I realize very few people know this exists, but it's very useful in realtime and GUI development.

**Situation:**
Breakpoints are useful, but because they suspend the game, you can only stare at a fixed point in time while leaving your game unresponsive.
If you want to see how frequently some code is called, in what order, or how a value changes over time, you have to modify your code and print stuff. The problem with that solution is that you loose a lot of time doing it if your game runs on a device, or if you have to run a long series of actions in the game before reaching the point where the bug is (not to mention asynchronous or time-dependent tasks where breaking would prevent an action from being repro-ed correctly). Also, script hot-reloading is not always an option because it could be risky, and it doesn't even works well on my own game.

**The idea**
The idea is that a breakpoint could also, instead of breaking, print a message, retrieve the stack, or display the value of available variables. Or eventually break if a condition is fullfilled. This alternative doesn't requires code modifications and would be very fast to setup.

Now I don't necessarily need it currently, but maybe others could be interested by the idea. I use a similar feature in Visual Studio on a daily basis due to the complexity of the project, and it saves a significant amount of time.

**Comment by vnen** [comment]
👍 to conditional breakpoints.

Some addition to the Remote Inspector would be interesting. Like a way to put and update your variables there.

**Comment by Noshyaar** [comment]
I think this is partially fixed by `breakpoint` keyword and the new debugger?

**Comment by Zylann** [comment]
How would a keyword help setting up non-breaking breakpoints at runtime? (reminding that non-breaking breakpoints are essentially a way to add prints to a running game without having to re-run the whole game)

**Comment by Noshyaar** [comment]
I misunderstood then. The way I think involves modifying the script.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
