### ISSUE TITLE
NavigationMeshInstance baking Static Colliders includes disabled colliders

### ISSUE THREAD

**Issue by dweremeichik** [godotengine/godot#65765]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Debian 11 (bullseye), OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2) Async. shader compilation: OFF

### Issue description

In testing for #65764 I discovered that disabled colliders are not ignored when baking a NavigationMeshInstance with Parsed Geometry set to Static Colliders (PARSED_GEOMETRY_STATIC_COLLIDERS).

I would expect that disabled shapes would not be parsed - they are likely disabled for testing purposes and when disabled do not accept collisions from other bodies.

### Steps to reproduce

1. Create a 3D project
2. Create a NavigationMeshInstance
3. Create a NavMesh
4. Set the NavMesh Geometry -> Parsed Geometry to Static Colliders
5. Create a Static Body and a Collision Shape with a Box Shape; extents 20, 1, 20
6. Create a Static Body and a Collision Shape with a Box Shape; check disabled
7. Bake the NavigationMeshInsance

You should then see that the second collision shape is cut out of the first.

### Minimal reproduction project

[nav_bake_disabled_collisionshape_mrp.zip](https://github.com/godotengine/godot/files/9561670/nav_bake_disabled_collisionshape_mrp.zip)

**Comment by smix8** [comment]
I guess this was just an oversight.

I did not add GridMap Colliders in the fix pr on purpose because users that use static colliders in grid cells usually don't intend to disable them like this manually and GridMap does not store this info on the object because it calls the PhysicsServer directly which has no getter for this to not stall the server.
