### ISSUE TITLE
[Mono] Godot 4 Alpha 17 error when running build_assemblies.py

### ISSUE THREAD

**Issue by zaksnet** [godotengine/godot#65782]
### Godot version

v4.0.alpha.mono.custom_build [3d08678e1]

### System information

Windows 11

### Issue description

I get the following errors when trying to run build_assemblies.py:
```
error CS0592: Attribute 'Signal' is not valid on this declaration type. It is only valid on 'delegate' de
clarations.
```
After examining the generated files it seems that `[Signal]` Attribute has been applied to the `event` and not to the `delegates`. Here is an example for `Generated/GodotObjects/MainLoop.cs` (line 168-179):
```CSharp
public delegate void OnRequestPermissionsResultHandler(string permission, bool granted);

// ReSharper disable once InconsistentNaming
[DebuggerBrowsable(DebuggerBrowsableState.Never)]
private static readonly StringName SignalName_on_request_permissions_result = "on_request_permissions_result";

[Signal]
public event OnRequestPermissionsResultHandler OnRequestPermissionsResult
{
    add => Connect(SignalName_on_request_permissions_result, new Callable(value));
    remove => Disconnect(SignalName_on_request_permissions_result, new Callable(value));
}
```

When i move the `[Signal]` Attribute to the delegate there are no errors:
```CSharp
[Signal]
public delegate void OnRequestPermissionsResultHandler(string permission, bool granted);

// ReSharper disable once InconsistentNaming
[DebuggerBrowsable(DebuggerBrowsableState.Never)]
private static readonly StringName SignalName_on_request_permissions_result = "on_request_permissions_result";


public event OnRequestPermissionsResultHandler OnRequestPermissionsResult
{
    add => Connect(SignalName_on_request_permissions_result, new Callable(value));
    remove => Disconnect(SignalName_on_request_permissions_result, new Callable(value));
}
```

EDIT: Interestingly the `[Signal]` Attribute is applied to `delegates` and not `events` in `GodotTools.csproj`. It is only `GodotSharp.csproj` that has the issue. I tried changing the signature of `Attributes` from `[AttributeUsage(AttributeTargets.Delegate)]` to `[AttributeUsage(AttributeTargets.Event)]` but then `GodotTools.csproj` gave me the errors so i'm not entirely sure what is the purpose is here.

**Comment by raulsntos** [comment]
The syntax to declare a signal in a custom C# Node is:

```csharp
[Signal]
public delegate void MySignalEventHandler(int parameterA, int parameterB);
```

Which generates an event using source generators like this:

```csharp
public event MySignalEventHandler MySignal;
```

So the `[Signal]` attribute is only used in the delegate and only serves as a way to let the source generator know to generate the event (as well as registering the signal in Godot).

For the built-in classes bindings generated with the bindings generator they don't need the `[Signal]` attribute since they don't use source generators (everything they need is already generated by the bindings generator implemented in C++). It's true that events used to have the attribute at one point and at one point we planed to allow this way of declaring signals but it didn't pan out so it was removed in https://github.com/godotengine/godot/pull/64911.

It's likely that the generated C# needs to be re-generated if some generated code still uses the `[Signal]` attribute, AFAIK the bindings generator should not be adding the attribute anywhere anymore. Try doing a clean build and remember that due to recent changes the name of the Godot binary has changed a bit (`64` -> `x86_64`) so if you are using an old script make sure to update it.
