### ISSUE TITLE
Importer keeps -loop and -cycle suffixes in animation names but removes suffixes in nodes

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#6582]
**Operating system or device - Godot version:**
Debian GNU/Linux

**Issue description** (what happened, and what was expected):
When importing animations from collada files, importer removes the suffixes such as -col, -colony from nodes. However, the behavior is different with animations: suffixes such as -cycle and -loop are kept in the animation names.

I expected that the behavior would be uniform/consistent.

**Steps to reproduce:**
Import a .dae file as a scene with animations.

**Link to minimal example project** (optional but very welcome):

**Comment by legione** [comment]
The same issue happens also for gltf2 files. The suffixes are removed from the nodes but not from the animations, requiring manual renaming.

**Comment by Calinou** [comment]
Can anyone still reproduce this bug in Godot 3.2.1 or [3.2.2beta4](https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-4)?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
