### ISSUE TITLE
Godot 4.0 Beta 1 Annotations 

### ISSUE THREAD

**Issue by Berkru** [godotengine/godot#65850]
### Godot version

4.0Beta1 [20d667284]

### System information

Ryzen 3600, Ubuntu 22.04.1 LTS, Radeon Rx 550, Vulkan

### Issue description

1. Random Crashes, mostly when changing settings ( and once when editing a material);
2. Text Editor gets a red-ish background if using any theme, other than the default theme;
3. Vsync doesn't afect the editor frame rate.
4. Changing the Low Procesor Mode Sleep in the Editor Settings seems not to affect the editor frame rate.

### Steps to reproduce

N/A

**Comment by Calinou** [comment]
These issues are either already reported, or are not bugs.

> 1. Random Crashes, mostly when changing settings ( and once when editing a material);

This is already being tracked in https://github.com/godotengine/godot/issues/59798.

> 2. Text Editor gets a red-ish background if using any theme, other than the default theme;

Custom themes need to be updated to use the `#rrggbbaa` color syntax instead of `#aarrggbb`. This is a breaking change between 3.x and 4.0.

> 3. Vsync doesn't afect the editor frame rate.

**View Frame Time** does not report the actual rendered framerate; it performs an estimation using CPU and GPU timings, so it can report values above the monitor refresh rate. This is done by design so you don't have to disable V-Sync or uncap the framerate to accurately preview performance :slightly_smiling_face: 

> 4. Changing the Low Procesor Mode Sleep in the Editor Settings seems not to affect the editor frame rate.

See above.

PS: In the future, please open one issue per reported problem.
