### ISSUE TITLE
LSP server does not starting in 4.0 beta 1

### ISSUE THREAD

**Issue by Ghashy** [godotengine/godot#65886]
### Godot version

4.0 beta1

### System information

MacBook Pro m1, Big sur 11.4

### Issue description

When I try to open a script file in vim, coc.nvim tries to connect to lsp Godot server. At that moment Godot crashes and vim prints the error, I have attached the screenshot.
<img width="1440" alt="Screenshot 2022-09-16 at 12 57 30" src="https://user-images.githubusercontent.com/109857267/190614125-d91a3b66-001b-441b-b178-bb30407a196d.png">

### Steps to reproduce

Start any project and try to connect to lsp from vim.

**Comment by FlySlime** [comment]
Also having this issue, bump.

**Comment by FlySlime** [comment]
Found the problem. It seems that LSP on my code editor is listening for port ``6008``, however on commit de7873c2d87c3ee8af8c27e35f49767fcc384e75 they changed it to port ``6005``. 

So in my case, since I'm using Emacs, I would have to change my code editor to listen for a GDScript port as such:

```elisp
(setq lsp-gdscript-port "6005")
```

It's not a bug from Godot's side, rather that the LSP for our text editors haven't been updated for the new port.

Hope this helps!

**Comment by Ghashy** [comment]
Hello! thanks for the answer) I tried with both ports 6008 and 6005, it always fails. In the screenshot below, red lines: 127.0.0.1:6005

**Comment by FlySlime** [comment]
> Hello! thanks for the answer) I tried with both ports 6008 and 6005, it always fails. In the screenshot below, red lines: 127.0.0.1:6005

Aha sorry, didn't see. Maybe it's an issue with neovim then? Lsp seems to work fine on Emacs.

Hope you get it solved!

**Comment by Ghashy** [comment]
Right before the crash, Godot prints this message in the terminal, right at the moment when I try to open the script in vim
<img width="923" alt="Screenshot 2022-09-30 at 13 09 59" src="https://user-images.githubusercontent.com/109857267/193248162-855bbfbd-84ef-4ed0-9fc6-f9c5ff9ec9db.png">

**Comment by Ghashy** [comment]
It works in 4.0 beta 2!
