### ISSUE TITLE
Godot 4.0 Beta 1 - Minimal project works in local preview but not on Web preview or Itch

### ISSUE THREAD

**Issue by QushyQushy** [godotengine/godot#65882]
### Godot version

4.0 Beta 1

### System information

Garuda Linux, 5900HX, 6800M

### Issue description

The game works in preview mode in the Editor but as soon as I try Web Preview or upload it to itch I get the following errors (same in both):

![2022-09-16T11:51:50,465995516+03:00](https://user-images.githubusercontent.com/85321958/190598759-9d990d75-90a7-4f8c-8088-5037701ed565.png)

### Steps to reproduce

Open the project and try Web Preview.

### Minimal reproduction project

[PuzzleCalculation_G4.zip](https://github.com/godotengine/godot/files/9582425/PuzzleCalculation_G4.zip)

Also you can test it on Itch [here](https://cosmichappiness.itch.io/puzzle-calculation).

**Comment by alfredbaudisch** [comment]
Depending on the scene it works, but then Skeletal Meshes and most Materials are all gone:

![image](https://user-images.githubusercontent.com/248383/190604005-6d02d283-4fe2-4c7e-9e10-abd17d31158b.png)

**Comment by clayjohn** [comment]
The web export has been significantly overhauled since this issue was made and now supports most features that were missing (including skeletons etc.). 

The only error from the OP that seems to be still active already has a dedicated issue (https://github.com/godotengine/godot/issues/68180) So I will close this in favour of https://github.com/godotengine/godot/issues/68180
