### ISSUE TITLE
missing texture when importing with blender importer

### ISSUE THREAD

**Issue by Nikuto13** [godotengine/godot#65913]
### Godot version

4.0 beta

### System information

Windows 10

### Issue description

if I have a texture assigned to mesh in blender 3.1 and I use Godot's blender importer the texture disappears. The information about roughness, glossiness ... of texture remains but image texture is gone.   

### Steps to reproduce

In blender assign texture to a mesh. Ui unwrap the mesh by using u then click reset.  assign the image texture. go to Godot 4 new project, set the blender importer folder. then drag the blend file in to the editor. the image texture is missing.

### Minimal reproduction project

https://drive.google.com/file/d/1kqZnvaXdAIdPnD66zBS-1_RQt8p-uodw/view?usp=sharing

**Comment by Calinou** [comment]
@Nikuto13 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by aaronfranke** [comment]
Not a Godot bug, it's a bad file. The reason the texture is missing is because the Blend file does not include the texture. The Blend file did store a preview for it, so I can still see it in the inspector, but the complete texture is missing.

<img width="1400" alt="Screenshot 2024-09-09 at 8 33 13 PM" src="https://github.com/user-attachments/assets/2d2c57cd-38d6-4154-8537-48b060869f8d">

You need to click "Pack Resources" in Blender to ensure the texture is stored inside the Blend file:

<img width="580" alt="Screenshot 2024-09-09 at 8 34 36 PM" src="https://github.com/user-attachments/assets/295ab82a-454e-4cee-b20f-7a209c4c8a45">

If you are still having issues, you need to attach a new minimal reproduction project that displays correctly in Blender.
