### ISSUE TITLE
Create Root Node buttons overlap their container border

### ISSUE THREAD

**Issue by okla** [godotengine/godot#65928]
### Godot version

4.0 beta 1

### System information

MacOS Monterey 12.5.1 (21G83)

### Issue description

When left editor panel is at its minimum size, Create Root Node buttons do not fit in it. Look at the buttons right side on the screenshot

<img width="183" alt="Screen Shot 2022-09-16 at 22 02 47" src="https://user-images.githubusercontent.com/8558017/190714169-65b2f676-54a2-4b8a-b7a3-90d238f7a5bb.png">

### Steps to reproduce

Resize left editor panel to its minimum size

**Comment by coppolaemilio** [comment]
I saw this one on my Mac as well, but is it also happening in other operative systems? Can anyone test it out?

**Comment by akien-mga** [comment]
Yeah I saw it on Linux too. I think it's a fairly recent regression (max 2 weeks?).

**Comment by gotnospirit** [comment]
Windows 10 also #65853

**Comment by YuriSizov** [comment]
I've seen overflowing like that for quite some time, and it doesn't happen just in the empty Scene dock, but other docks and panels as well. Though I attributed it to the 200% scale I was using at the time. Seems it can happen at any scale? Or maybe only non-default?

**Comment by akien-mga** [comment]
I'm using 100% scale with 1920x1080 resolution on Linux.

Here's an empty scene in an empty project in 4.0 beta 1:

![image](https://user-images.githubusercontent.com/4701338/190854264-696421ff-7ed1-4a40-b872-de0b20f5d9fa.png)

Same test in 4.0 alpha 15:

![image](https://user-images.githubusercontent.com/4701338/190854362-70520053-1ab2-4012-a306-5bc0a3792559.png)

The regression started in 4.0 alpha 16:

![image](https://user-images.githubusercontent.com/4701338/190854371-79f8d975-dff1-4593-a6f8-4efac8634fb7.png)

There are two bugs visibly:
- The side docks shrunk below their configured default size
- The scene dock doesn't properly enforce its min size for the Create Root Node buttons

The second one might be a pre-existing issue, the first one is likely caused by #65028 (@groud).

**Comment by groud** [comment]
Hmm, I might have messed up some minsize computation. I'll have a look.

**Comment by Rindbee** [comment]
It seems that the calculation of the minimum size of the `ScrollContainer` is wrong.
