### ISSUE TITLE
TileMap 4 : Unable to select or add a tile if zoom < 100%

### ISSUE THREAD

**Issue by Aegel5** [godotengine/godot#65941]
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Windows 11, Vulkan

### Issue description

Creating a tilemap (isometric), creating a tileset, creating an atlas, choosing to automatically create tiles

After that, you can select tiles only in the upper left corner, the rest of the tiles cannot be selected.

It is also not possible to place tiles on the map (it is possible place only several tiles from the upper-left corner of the tile map)

### Steps to reproduce

- Open mini proj
- Select a tilemap
- Try to place a tile on the scene - you can only place 6 (from the upper left corner) of the 18 tiles.

### Minimal reproduction project

[test_proj.zip](https://github.com/godotengine/godot/files/9587286/test_proj.zip)

UPD: after several experiments, I found that the ability to select a tile appears if you zoom a tile map tab more than 100%.
But if the zoom is less than 50%, you cannot select or add tile.

**Comment by KoBeWi** [comment]
I can confirm something is wrong with selecting tiles (square in my case). I didn't investigate it much though.

**Comment by afestini** [comment]
Probably not much help (I figured I'd just "quickly" find where the zoom isn't taken into account and fix it), but in this scenario "TileMapEditorTilesPlugin::_tile_atlas_control_gui_input" isn't called. Unfortunately this call seems to come from the Control base class (or rather, it doesn't). Since 50% zoom means you can select exactly the top left half, I suspect zooming changes some attribute in Control that results in the mouse being considered "outside".

I'll keep debugging either way, since this has been driving me crazy for a while now and makes working with large tilesets a real pain.

**Comment by groud** [comment]
I think the bug might have been caused by https://github.com/godotengine/godot/pull/64597. CC @MinusKube .

**Comment by afestini** [comment]
I noticed the tiles had stopped randomly disappearing at certain zooms. Now I'm trying to remember if that happened on top of not being able to select some tiles.

Two things I notice:
-"_base_tiles_root_control_gui_input" in TileAtlasView is triggering fine (tooltips are correctly showing)
-the viewport of tile_atlas_control doesn't seem to scale with the zoom (mouse_exit triggers when you move out of the last working tile)

**Comment by MinusKube** [comment]
I see, there's a problem with the zoom being applied twice for the `base_tiles_drawing_root` and `alternative_tiles_drawing_root`. I found a solution, I'll make a PR soon.
