### ISSUE TITLE
Possible Godot 4.0 Curve3D get_follow_offset() Regression

### ISSUE THREAD

**Issue by Kuma-Boo** [godotengine/godot#66067]
### Godot version

v4.0.beta1.mono.official [4ba934bf3]

### System information

Windows 10

### Issue description

I recently moved to Godot 4.0 and noticed using curve.get_follow_offset() is causing jittering compared to the previous version I was using (v3.5.1.rc1.mono.official [293c3844b]).

It's my first time opening an issue on Github, so please go easy on me! ^^

### Steps to reproduce

I've attached a zip file that contains identical minimal reproduction projects for both 4.0 and 3.5.1.

- Import the project into the editor
- Open "PathFollowTest.tcsn"
- Run the scene

Two objects will scroll across the screen. The sphere is a child of a PathFollower, whose parent is a Path node that has a Curve which goes in a straight line to the right.
The cube has a script that runs every frame and moves the cube to the right, then sets the PathFollower's offset to be the closest offset to cube.

When running the scene, the sphere follows the cube smoothly in 3.5.1, while in 4.0 there's constant jittering.

### Minimal reproduction project

[Minimal Reproduction Projects.zip](https://github.com/godotengine/godot/files/9595114/Minimal.Reproduction.Projects.zip)

**Comment by kidinashell** [comment]
@Kuma-Boo 

In Godot 4 when you increase the bake interval of the Curve3D itself, you can see, that you jittery motions get smaller and smaller until they ALMOST disappear.

The one in 3.5 is also ALMOST gone, but not really. If you look closely enough, there's also jittering going on. It's just less noticable because of the difference in distance of the camera or size of the objects.

Doc entry of `get_closest_offset(to_point: Vector3)`: `Returns the closest offset to to_point. This offset is meant to be used in sample_baked() or sample_baked_up_vector().`

So maybe this method shouldn't even be used this way.

**Comment by Kuma-Boo** [comment]
Even when I zoom the camera way in on the 3.5 demo, it still tracks almost perfectly. I think the "jittering" you mention may be caused from a lack of antialiasing.

While increasing the bake interval minimizes the issue for linear A -> B segments, it's somewhat impractical for me since I need to be able to use more complex curves in my project.

I also tried setting the position directly by sampling the curve using `sphere.global_position = 
path.curve.sample_baked(path.curve.get_closest_offset(global_position));` based on your suggestion, but the results seem identical to modifying `pathfollower.progress`.

Thanks for the suggestions though!

**Comment by Kuma-Boo** [comment]
I don't really know what was changed in the Engine's source code, but it seems to be fixed as of version v4.0.beta8.mono.official [45cac42c0], so I'll be marking this as closed for now.

Thanks to any contributors who may have fixed this issue!
