### ISSUE TITLE
Callable.get_object() returns null after passing it as a parameter to another method

### ISSUE THREAD

**Issue by fkeyzuwu** [godotengine/godot#66139]
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

When using a callable in the same scope, Callable.get_object() returns the object as intended.
However, when you pass it as a parameter to a different method, the value of Callable.get_object() becomes null.
When trying to print it, it says "Freed Object", even though the object is still in the hierarchy, and still has functionality running.
This happens for every way that a Callable can be created (afaik).

I know there was a bug report regarding something similar already, however I think it has been passively fixed somehow and this one seems like a different bug.

### Steps to reproduce

Pass in a Callable as a parameter to another method, call get_object() on that Callable parameter.

### Minimal reproduction project

[Callable As Parameter.zip](https://github.com/godotengine/godot/files/9603150/Callable.As.Parameter.zip)

**Comment by kleonc** [comment]
Seems like it's caused by static typing (tested in v4.0.beta1.official [20d667284]):
```gdscript
extends Node2D

func _ready():
	pass_callable_untyped(test_method)
	pass_callable_typed(test_method)

func pass_callable_untyped(callable):
	prints("%-25s %-25s %-15s %-25s" % [
		"pass_callable_untyped()",
		callable.get_object(),
		callable.get_object_id(),
		instance_from_id(callable.get_object_id())
	])
	
func pass_callable_typed(callable: Callable):
	prints("%-25s %-25s %-15s %-25s" % [
		"pass_callable_typed()",
		callable.get_object(),
		callable.get_object_id(),
		instance_from_id(callable.get_object_id())
	])

func test_method():
	pass
```
Outputs:
```
pass_callable_untyped()   Test:<Node2D#21239955837> 21239955837     Test:<Node2D#21239955837>
pass_callable_typed()     <Freed Object>            21239955837     Test:<Node2D#21239955837>
```
In both cases `callable` can be called just fine, the problem seems to be only with `get_object()`.

Now here's interesting example:
```gdscript
extends Node2D

func _ready():	
	var callable_untyped = test_method
	var callable_typed: Callable = test_method
	var callable_typed_inferred := test_method
	
	var callable_as_callable_untyped = test_method as Callable
	var callable_as_callable_typed: Callable = test_method as Callable
	var callable_as_callable_typed_inferred := test_method as Callable
	
	prints(1, callable_untyped.get_object())
	prints(2, callable_typed.get_object())
	prints(3, callable_typed_inferred.get_object())
	
	prints(4, callable_as_callable_untyped.get_object())
	prints(5, callable_as_callable_typed.get_object())
	prints(6, callable_as_callable_typed_inferred.get_object())

func test_method():
	pass
```
Outputs:
```
1 Test:<Node2D#21239955837>
2 Test:<Node2D#21239955837>
3 Test:<Node2D#21239955837>
4 Test:<Node2D#21239955837>
5 Test:<Node2D#21239955837>
6 Test:<Node2D#21239955837>
```
But depending on which printing lines are commented out (and thus some `get_object` calls are removed) the output will differ. Example outputs (lines with the numbers not listed in the output were commented out):
```
2 <Freed Object>
3 <Freed Object>
4 Test:<Node2D#21239955837>
5 Test:<Node2D#21239955837>
6 Test:<Node2D#21239955837>
```
```
2 <Freed Object>
3 <Freed Object>
5 <Freed Object>
6 <Freed Object>
```
```
1 Test:<Node2D#21239955837>
2 Test:<Node2D#21239955837>
3 Test:<Node2D#21239955837>
5 Test:<Node2D#21239955837>
6 Test:<Node2D#21239955837>
```
So seems like calling `get_object` on untyped `Callable` makes the subsequent `get_object` calls on typed `Callable`s return the proper object (instead of freed object).

**Comment by rune-scape** [comment]
I just ran into this issue and I think its the difference between `vc_method_call()` vs `vc_validated_call()`
The `ObjectID` in the variant isn't being updated in `VariantInternalAccessor<Object *>::set` in `variant_internal.h`.
I'm not familiar with this code, but I'm making a pull request because of how simple it seems.
And it fixes all the code here.
