### ISSUE TITLE
GDScript 2.0: Statically typed variables can have different types assigned to them

### ISSUE THREAD

**Issue by L4Vo5** [godotengine/godot#66141]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10

### Issue description

Statically typed GDScript variables sometimes don't work statically as promised, even when debugging the game from the editor.

### Steps to reproduce

Normally, attempting to assign a float to an int variable in GDScript will result in an automatic conversion:
```gdscript
var a: int = 1.5
print(a) # 1
```
However, if the float comes from a non-statically typed variable, there's no conversion:
```gdscript
var b = 1.5
var a: int = b
print(a) # 1.5
assert(a is int) # Runtime error
assert(a is float) # (Editor error, even though a is a float at this point, but this is the expected behaviour)
```

A similar thing happens with incompatible types where you'd expect an error instead. It works fine without variables:
```gdscript
var a: int = "" # Editor error
var c: int = 0
c = "" # Editor error
```
Then with variables, (at least in the case of strings, the error sometimes will trigger on variable declaration, but it can still slip by later):
```gdscript
var b = ":("
var a: int = b # Editor error
var c: int = 0
c = b # No error
print(c) # ":("
assert(c is int) # Runtime error
```

**Comment by MladoniSzabi** [comment]
When assigning a constant value to a variable (`var a: int = 1.5`) the GDScript VM uses the `OPCODE_ASSIGN_TYPED_BUILTIN` opcode which checks the type of the variant and casts the constant to that type.
[https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_vm.cpp#L1145](url)

However when a variable is assigned to another variable (`var a: int = b`) the GDScript VM uses the `OPCODE_ASSIGN` opcode which assigns a variant to another variant without doing any checks on the types. 
[https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_vm.cpp#L1119](url)

I didn't find any method or attribute on the Variant to check if its type shouldn't change to indicate that it is a statically typed variable so im not sure what the fix would be, since checking against `Variant::get_type()` sounds like a bad idea as it would break code like `var b = 1.5`

I noticed however that the VM gets the type of the variable from `_code_ptr` so maybe there is some other information about the variable there that could be useful?
[https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_vm.cpp#L1150](url)
