### ISSUE TITLE
Saving movie using meta_data doesn't work.

### ISSUE THREAD

**Issue by SilencedPerson** [godotengine/godot#66148]
### Godot version

Godot 4.0 beta 1

### System information

Windows 10

### Issue description

The metadata movie_path doesn't work.
![image](https://user-images.githubusercontent.com/82024211/191206988-7af1bf74-3a11-4029-a340-751a52d8c626.png)

### Steps to reproduce

1) make a new scene
2) give it metadata of movie_path
3) enable movie_writer mode
4) run the scene

**Comment by timothyqiu** [comment]
Currently checking for `movie_file` metadata instead of `movie_path`.

https://github.com/godotengine/godot/blob/aa553f403099a31520ab0c75a43f352642170d5f/editor/editor_node.cpp#L2446-L2455

**Comment by Calinou** [comment]
PS: The output path must be a file name, not a folder name.

**Comment by eliacanavera1111** [comment]
Hi, the movie_file metadata *must* be set on the root node of a scene, or it can be also on another node like a subviewport or subviewportcontainer? This would be to record only the subviewport (with its contained nodes), instead of the whole scene, without having to split my scene into more scenes, or to set visible properties to false to everything else (btw not a problem).
