### ISSUE TITLE
[Godot4] shader's sample2D color not correct sometimes

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#66157]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows 10, 64bit

### Issue description

I create a meshintance and set shader material:
![image](https://user-images.githubusercontent.com/35988767/191260558-ca04280a-1d31-421f-b060-65d40ac9079a.png)

I was set the `color` to a `GradientTextrue2D` and which color was from RED to BLUE, when I set the `t` to 0.0, I think it should be RED, but it not, look above image.

A video I test below:

### Steps to reproduce

/

### Minimal reproduction project

[ShaderTest.zip](https://github.com/godotengine/godot/files/9607693/ShaderTest.zip)

**Comment by Calinou** [comment]
This is not a bug. You need to add the `repeat_disable` hint to your gradient's sampler2D in the shader code:

```glsl
uniform sampler2D color : repeat_disable;
```

Textures are repeating by default, and you're seeing the transition between the red at the beginning of the gradient and the blue at the end of the gradient otherwise (with linear filtering, which is also the default).

**Comment by Zireael07** [comment]
@Calinou Can this disabling be done automatically for gradients?

**Comment by CsloudX** [comment]
> 

Oh, Thanks.

**Comment by Calinou** [comment]
> @Calinou Can this disabling be done automatically for gradients?

No, as repeat is decided on the sampler instead of the texture in 4.0.
