### ISSUE TITLE
Scene instance properties aren't properly set in exported project if their values equal the property default.

### ISSUE THREAD

**Issue by pLawitzki** [godotengine/godot#66154]
### Godot version

4.0.beta1

### System information

Windows 10, Vulcan

### Issue description

If you create a scene with properties altered in the root node (e.g. a Sprite node with its modulate value set to Color.RED in the inspector), create an instance of that scene, and set the instance's altered property to its default value (e.g. Color.WHITE on the modulate property), that property is set correctly when starting the project through the editor but not when starting the exported executable.

This was only tested on a Windows 10 project export.

### Steps to reproduce

1. Create a new project (or alternatively download the minimal repro project below and skip to 6.)
2. Create a Node2D main scene and a Sprite2D child scene
3. In the child scene pick the icon.svg as texture and set the modulate property to some other value than Color.WHITE
4. Instantiate the Sprite2D child scene in the main scene
5. On the instance of the child scene set the modulate property to Color.WHITE
6. Export the project
7. Start the executable and observe that the modulate property of the instance is not Color.WHITE

### Minimal reproduction project

[PropertyTest.zip](https://github.com/godotengine/godot/files/9606497/PropertyTest.zip)

**Comment by PucklaMotzer09** [comment]
I opened the minimal project and in the editor the Sprite is purple and its modulate value is set to purple (R:1, G:0, B:1, A:1). But when I run the project the Sprite is normal as if the modulate value would be white. I noticed that the self_modulate value impacts the Sprite, but the modulate value does not. The self_modulate value works as intended, but the modulate value has no impact at all.

**Comment by pLawitzki** [comment]
> I opened the minimal project and in the editor the Sprite is purple and its modulate value is set to purple (R:1, G:0, B:1, A:1). But when I run the project the Sprite is normal as if the modulate value would be white. I noticed that the self_modulate value impacts the Sprite, but the modulate value does not. The self_modulate value works as intended, but the modulate value has no impact at all.

Yes, the modulate value of the sprite in the child scene (icon_scene.tscn) is set to purple. On the instance of icon_scene.tscn in the main scene the modulate value is set back to white. If you run the project in the editor the Sprite is white as it should be. If you export the project and run the exported executable, the sprite is purple which is inconsistent with the behaviour observed in the editor.

**Comment by PucklaMotzer09** [comment]
Okay. I didn't see that there was a MainScene. Then I am seeing the same thing as you are. I will test if the same thing occurs on a Linux epxport.

**Comment by PucklaMotzer09** [comment]
I can now confirm that this issue does also occur on a Linux export.

**Comment by PucklaMotzer09** [comment]
I did some research and found out that the issue does not occur when switching `editor/export/convert_text_resources_to_binary` off which is on by default. You can do that by switching on the advanced settings in the project settings.
Godot converts the .tscn files to binary .scn files when exporting the project and somewhere during this conversion the modulate property gets ignored because it has the default value.
I could track down the bug to somewhere here https://github.com/godotengine/godot/blob/658bfb0395fa356f67745de0620628167671d5c6/editor/export/editor_export_platform.cpp#L730-L741

The bug probably occurs in `s->pack(node)` or `ResourceSaver::save`

**Comment by PucklaMotzer09** [comment]
I continued my research and found the following code snippet:

https://github.com/godotengine/godot/blob/53d2a9acddf4df5ba7819c154a8a52dc58ddcd1d/scene/resources/packed_scene.cpp#L605-L611

This is some code that is called inside `s->pack(node)`. Here properties which do not have a value different to the default value get ignored and not packed into the scene which ultimatly results into them not being inside the .pck file. The `PropertyUtils::get_property_default_value` method here wrongly determines the default value of instanced scenes and takes it from the default values of the class (which in case of a color is white).
This stems from the `states_stack` being empty eventhough there should be the scene from which the node is being instanced from (I think).

So I think this issue can be solved by doing one of the following things:
1. Make sure that the scene state of the node is correctly set. So that the `states_stack` can be filled as intended. This can be done by either calling `set_scene_inherited_state` or `set_scene_instance_state` (I am not really sure which of them. I tried to set them on multiple occasions but couldn't get anywhere).
2. Update `PropertyUtils::get_node_states_stack` to add the correct scene states to the stack.
3. Update `PropertyUtils::get_property_default_value` to determine the correct default value without the `states_stack`.

I am now stuck and can't get any further. Maybe someone else who has more knowledge about this part of the engine can fix this issue. Anyway I hope I helped out.

**Comment by Rindbee** [comment]
The flag used when packing is `GEN_EDIT_STATE_DISABLED`. 

https://github.com/godotengine/godot/blob/8e14f9ba21725a9445f3979742f2fc87c8a7b463/scene/resources/packed_scene.h#L233

This caused the sub-scene root node to not call `set_scene_instance_state` and `set_scene_inherited_state`.

https://github.com/godotengine/godot/blob/8e14f9ba21725a9445f3979742f2fc87c8a7b463/scene/resources/packed_scene.cpp#L146-L148

https://github.com/godotengine/godot/blob/8e14f9ba21725a9445f3979742f2fc87c8a7b463/scene/resources/packed_scene.cpp#L1750-L1752

Further, because the scene root node does not set the scene state, the correct inheritance chain cannot be obtained.

https://github.com/godotengine/godot/blob/8e14f9ba21725a9445f3979742f2fc87c8a7b463/scene/property_utils.cpp#L162-L170

Therefore, the default values obtained when packaging and editing are different, resulting in the result of running the exported project not as expected.

Not sure what the reason is, the inherited scene root doesn't seem to be affected (still works as expected).

**Comment by jonpikum** [comment]
It's quite possible I'm doing something wrong, but there might still be an issue here.
When running an exported build, I still see a purple icon when `editor/export/convert_text_resources_to_binary` is on, and the normal white logo if the setting is set to off.
Tested this on both:
- v4.0.4.rc.custom_build [75e5bf789]
- v4.1.beta.custom_build [c211c22ab]

This was the closest related issue I could find that described an inconsistency I am experiencing with the `editor/export/convert_text_resources_to_binary` setting so I decided to try confirming its validity using the provided minimal reproduction project and still saw the inconsistent behavior.

**Comment by Rindbee** [comment]
> It's quite possible I'm doing something wrong, but there might still be an issue here.

@jonpikum  Have you exported your project before? If yes, please delete `.godot/exported` directory.

**Comment by jonpikum** [comment]
Ah, that did it. After some testing I can confirm that deleting `.godot/exported` removed the inconsistency I was seeing both in the provided minimal reproduction project and my own project.

As a (seemingly now obvious) note for anyone coming here after me, `PropertyTest.zip` does indeed contain files within `.godot/exported`.

Thanks!
