### ISSUE TITLE
There is an option in 3.0 that is missing in 4.0

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#66203]
000000000000000000

**Comment by lawnjelly** [comment]
This will be down to @clayjohn and 4.x rendering contributors to decide on.

For some background, the reason for this option was that there was a PR that changed the behaviour of the ninepatch significantly (#32170 ), and some users weren't happy with this change. We therefore offered the option for both behaviours, but as a global option to maintain backward compatibility.

For 4.x, it could even be selectable _per ninepatch_, rather than globally, as there is no longer the requirement for backward compatibility. But is totally up to the 4.x guys. They may equally decide to only offer one mode.

See here for full discussion:
https://github.com/godotengine/godot-proposals/issues/1618

**Comment by clayjohn** [comment]
@xiaoliang6669 It would be helpful to know what behaviour you expect from ninepatch and what behaviour you get in 4.0 and whether there is a way to work around this.
