### ISSUE TITLE
not implementing one of the functions when using selfget should throw an error

### ISSUE THREAD

**Issue by razvanc-r** [godotengine/godot#6622]
**Operating system or device - Godot version:**
v2.1.stable.official

When using `setget` but not implementing one of the two functions:

``` python
var a setget ,get_a
# or
var a setget set_a
```

and accessing the unimplemented part Godot should throw an error, for example in the first case doing `self.a = 'something'`, the same for the second: `print(self.a)` should throw an error. At the moment, in the first case nothing happens and in the second case `self.a` returns `null`. I can't remember how Python behaves when using the `@property` decorator but I think it throws an error when used improperly.

**Comment by akien-mga** [comment]
AFAIK this is not a bug, but a feature: http://docs.godotengine.org/en/latest/reference/gdscript.html#setters-getters

**Comment by razvanc-r** [comment]
@akien-mga, I don't see where it says this is a feature. It only says that *local access* does not trigger setter/getter, it doesn't say that nothing should happen if you try to access the non-implemented part (eg. `self.a = 'something'` when there's no defined setter).

I think that for the non-implemented part it either should throw an error or do the default action, in case of setters, just set the value (which doesn't happen if there's no setter and using `self.`) and in case of the getter just return the value (which doesn't happen, it returns null when no getter and using `self.`)

**Comment by akien-mga** [comment]
> Either of the setter or getter functions can be omitted:
>
> ````
# Only a setter
var myvar = 5 setget myvar_set
# Only a getter (note the comma)
var myvar = 5 setget ,myvar_get
```

**Comment by razvanc-r** [comment]
Yes, that's my point

**Comment by eska014** [comment]
If one of setter/getter is not defined, the default is used (naive assignment/retrieval)

```
func set_a( val ):
    # [setter logic here]
    a = val

var a = 3 setget set_a

func _init():
    print( a )
    # => 3
```

If that's unclear, it's a documentation issue

**Comment by razvanc-r** [comment]
@eska014, try that with defined getter only and with `self.a` instead of `a` and see what's the default behavior you get when setting :)

**Comment by eska014** [comment]
Can't produce an issue like that either
```
var a = 3 setget ,get_a

func get_a():
    return a

func _init():
	prints( self.a, a )
	# => 3 3

	a = 4
	prints( self.a, a )
	# => 4 4

	self.a = 5
	prints( self.a, a )
	# => 5 5
```

**Comment by razvanc-r** [comment]
I'm using it this way:

```python
extends Node

var __a = 3
var a setget ,get_a


func get_a():
	return self.__a

func _ready():
	self.a = 5
	print(self.a, ' ', a)
	# => 3 5
```

I find it very strange to use the same name `a` inside the set/get functions. Look at Python for what I'm talking about. You can't have `@property` on say variable `a` in Python and also get or set `a` within the setter/getters.

**Comment by vnen** [comment]
I misunderstood this issue at first, this is not a bug.

You have to consider that all members are public in GDScript. There's no reason to add an extra `__a` member to make it hidden since external scripts can get and set `__a` at will with direct access. The `setget` mechanic can allow you to properly hide the member if you want, just by making a getter which returns `null`.

You may find strange, to use `a` inside `set_a()` but that's how GDScript is, you're just expecting something else.

**Comment by razvanc-r** [comment]
But that would mean that for every variable you want to have "private" you'll have to create one of those functions, that's a lot of work just for making variables "private". I prefer the more conventional style. But in this example I'm not trying to make it private or anything, I was just using `__a` because why not? I could have as easily use `b`. So then in setter/getter in GDScript **you are meant to use the same variable for which you specify `setget`**, i.e. `var a = setget set_a, get_a` in `set_a` & `get_a` you **have to use** `a`. For someone that comes from Python I don't think this is clear enough. :).

After I confirm this I'll close the issue, thanks.

**Comment by vnen** [comment]
Why not? Because GDScript is not Python. I know it can be confusing for someone with a Python background, but it's mostly a matter of learning it once (the same way you learn to use `func` instead of `def`).  So the issue here is just the missing clarification in the docs.

In `set_a()` you have to set `a`, yes. In fact I prefer this way, less names to keep track and no need to come up with a name convention (like the `__` prefix). If there were private members, then this could make sense.

If you're willing to use `__a`, don't define `setget` and just create getter/setter functions. Since you're not willing to make it private anyway.

**Comment by razvanc-r** [comment]
Thanks for the clarification. So is it possible to move this issue then to the other repository? Should I close or leave it?

**Comment by bojidar-bg** [comment]
Yeah, makes sense to move to -docs.
https://github.com/godotengine/godot-docs/issues/340
