### ISSUE TITLE
Embedded window doesn't emit mouse_exited / mouse_entered.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#66293]
### Godot version

4.0.beta1

### System information

Windows 10

### Issue description

Embedded window doesn't emit `Window.mouse_exited` or `Window.mouse_entered` when the player move the mouse into or out of the window's area. (Embedded window meaning its parent viewport has `gui_embed_subwindows` = false.) 

Non-embedded windows will correctly emit both signals.

Also, both the embedded window and its parent will emit `Window.window_input(event)`, as if they're a same window - which is technically right on the OS level. So it might not be a bug.

If it's not a bug, how do we check if the mouse exited an embedded window?

### Steps to reproduce

See reproduction project.

### Minimal reproduction project

[mouse_exited.zip](https://github.com/godotengine/godot/files/9632710/mouse_exited.zip)

**Comment by Sauermann** [comment]
From what I can tell, this is a missing feature. Currently embedding Viewports do not keep track, over which embedded Window the mouse is. Adjustments would need to be made to `Viewport::_sub_windows_forward_input` in order to implement this.

You could try in your MRP as a workaround something like this in the meantime (warning: contains inaccuracies, not for production):
```GDScript
var overW2 = false
func _on_window_window_input(event: InputEvent) -> void:
	if name == "Window2" and event is InputEventMouse:
		var r = Rect2i(Vector2i(0,0), size)
		var pos = event.position
		var inside = r.has_point(pos)
		if overW2 and (not inside):
			overW2 = false
			print("now outside W2")
		elif (not overW2) and inside:
			overW2 = true
			print("now inside W2")
```

> Also, both the embedded window and its parent will emit `Window.window_input(event)`, as if they're a same window - which is technically right on the OS level. So it might not be a bug.

If you look closely, you will see that for a single Mouse event, that output shows different coordinates for the embedding window and the embedded window.
