### ISSUE TITLE
yield's idle_frame may confuse new people

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6638]
**Operating system or device - Godot version:**
2.1 latest
- Create a new scene
- Add a RichTextLabel with a lot of text (so it shows the scrollbar)
- Attach a script to it, use the code below

```
extends RichTextLabel
func _ready():
    print(get_v_scroll().is_visible())
```

It will show **false**. You might be wondering, why in the world?

Well, the reason is somehow you need to have a random `yield(get_tree(), "idle_frame")` right before printing.  Like so:

```
extends RichTextLabel
func _ready():
    yield(get_tree(), "idle_frame")
    print(get_v_scroll().is_visible())
```

My suggestion is.. can't this `yield(get_tree(), "idle_frame")` be done behind the scenes for us? And can also give us the option to use it when we need? I know it advances towards the next frame and yields for it: http://docs.godotengine.org/en/latest/reference/gdscript.html#coroutines-signals

But for newer people, and I can contest to this.. I was stuck developing a user interface for my fairly large game now for hours trying to figure out why some ui elements weren't working. And then I suddenly added  the `idle_frame` yield at the top of whatever code and it worked miraculously.

There was also another instance earlier where I was tweening a RichTextLabel and it had a weird blink for the first 0.5ms of the transition then any other new tweens / messages were fine. I spent almost an hour looking at what it could be. It turned out I just needed a `idle_frame` yield right before it.  

Yeah, I understand the need for it and I like it. But I feel like if we could somehow get it to work behind the scenes for most basic stuff (like my example code above), newer people won't have problems with it.  Especially when developing rich user interfaces. Maybe we should add somewhere in the docs that `idle_frame` is your best friend? :)  Especially when working with UI elements.

Edit: The point I am getting at is really about the example code above. If I were brand new, I would have absolutely no idea that I would need a `idle_frame` yield there. I just don't want other new people to share this fate. I would have most likely made a bug issue about it, and waste the time of other developers.

**Comment by akien-mga** [comment]
Well I'm not sure why you think that the example code you gave is the "right way" to do this, and that therefore `yield(get_tree(), "idle_frame")` would be a mandatory but undocumented instruction.

From what I can see, the issue seems more to be that RichTextLabel does not set the proper value for the visibility of its scrollbar when instanced with a lot of text. One should not have to wait one frame to get this information.

**Comment by Dillybob92** [comment]
@akien-mga Well, that's kind of what I was hinting at I think. It doesn't feel "right" using the yield there, we shouldn't have to be using the `idle_frame` signal all over. UI updates should happen flawlessly behind the scenes already, and if we need to do rich UI with the `idle_frame` signal we can. Kind of like what we are doing now I guess?

 I'm thinking this might be a reason why Godot isn't as used as much for extensive UI applications outside of gaming. Maybe some developers get stuck and are like "wtf why isn't this ui element working" when they all just forgot to put that `idle_frame` signal above the code. They would have never thought about that though. I'm not saying Godot is not used outside of games, it is infact, and I've seen some awesome programs. But I do believe the `idle_frame` can be a hindrance.

  But maybe this is just how godot is designed from the ground up and we must deal with it. I am just kind of worried that newer people might run into some stupid problem like I did trying to find the `get_max()` value of a `VScrollBar` and wondering why it's not returning the max value.. (or in this case, `is_visible()` -- all because they forgot to add a `idle_frame` signal.  It happens not only to RTL, but basically any UI element that gets changed.  

Or.. maybe I'm over thinking this entire thing and it's a RTL bug? Although, as I said it happens to mostly every UI element I've done extensive UI development with :P 

With all that said, I'm in favor of some type of new/edited documentation explaining that `idle_frame` is essential for rich UI creation. Doc's currently say it's needed to resume execution of the next frame, but as my example code above shows.. Not a lot of people would really know, hey, we need to add a `idle_frame` signal there to get the value of a scrollbar! :palm_tree:

**Comment by bojidar-bg** [comment]
I think it should not be required in any way, and that it isn't essential either, because:
1. it's really ugly in code
2. it's more-or-less better to just use call_deferred, like all real GUI code does in the background. (it would set a `dirty=true` flag, and then call_deferred the update function)
3. The best option would be to just fix that in those GUI components that are affected than to use a workaround
  * E.g. by making them call their update function on first ready/enter_tree received, rather than queueing it.
4. Even if 3 doesn't really happen, then just adding another callback/signal/thing would be way better..

**Comment by reduz** [comment]
Getting values out of the UI right after you instance it is in general a
bad idea. Most UI systems of this kind (using containers or anchors)
generally defer resizing elements until everything is in place and stops
moving.. then does everything in one go.

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
