### ISSUE TITLE
More obvious way to rotate GridMap tiles

### ISSUE THREAD

**Issue by Zebcash** [godotengine/godot#6639]
Ubuntu Studio Godot 2.1

I work with 3D procedural world, and actually, for a wall for exemple I must had 4 Tiles (North, East, West, South) Oriented tiles for make Library mesh. after that I can put on gridmap my tiles with set_cell_item(x,y,z,0), but when done, It's not possible to change Y axis of my tiles by code. I think, and I'm not alone, set_cell_item_rotation(x,y,z) function has very welcome for do that, simply for have only one tile for wall not four !
Thank you for had this: 3D projects really need rotating(x,y,z) tiles in gridmap. 

You can find my project here : https://www.facebook.com/groups/168800120225984

**Comment by Zylann** [comment]
Are you requesting something similar to 90 degrees rotation or flip/mirror like TileMap?

**Comment by Zebcash** [comment]
Yes, something like set_cell_item_rotation(x,y,z) for manipulate Tiles 3D
in gridmap, why ?

**Comment by Zylann** [comment]
Just wanted to clarify, because on this kind of grid you could flip and rotate 90 degrees because it's very cheap to store the information (only a few bits per block), but arbitrary rotations, scales and positions are usually not supported (mostly for optimization).

**Comment by bojidar-bg** [comment]
@Zebcash `set_cell_item` already has an optional "orientation" param.. so workaround is too easy. (just you have to make some tests on what different values do, but, yeah)

**Comment by Zebcash** [comment]
Yes Bojidar-bg, I know, but try this option for rotate your tile on the same time on the x y and z axis... good luck ;-), believe me, I have not posted here, if I could overcome my problem with the current set_cell_item

**Comment by Zylann** [comment]
I think the orientation parameter is not an angle here, but an index to a 3D base between 0 and 24, 0 being the identity base (X+, Y+, Z+).
This is for sure a terribly un-obvious API ;D https://github.com/godotengine/godot/blob/master/core/math/matrix3.cpp#L290

**Comment by Zebcash** [comment]
Waouh ! Sure ! Terribly un-obvious ! But thanks for this explain, and for finding this link. I stay on my first Idea. Godot need a more intuitive command for rotate item.

**Comment by akien-mga** [comment]
@tagcup Did you handle this by chance in your math changes?

**Comment by Zebcash** [comment]
Hello,
I have a little difficulty to link your question to its context.
I have been obliged during the last three months to put my project on a
break for professional reasons, and I disconnected a bit from godot, (I
wait for the 3.0 to get over it as my project is in 3D)
But I will be happy to answer it if I can, if you help me understand it
better.

2017-01-13 19:07 GMT+01:00 Rémi Verschelde <notifications@github.com>:

**Comment by tagcup** [comment]
@akien-mga Nope, this is rather a UI issue.

So how about changing the UI such that you select a rotation axis (X, Y or Z) and angle (90 or 180), and possible flips for each axes? Constructing the transformation from this information is straightforward, and we can get rid of _ortho_bases completely.

**Comment by akien-mga** [comment]
@Zebcash I was asking @tagcup specifically as @Zylann above had reference the Matrix3 API, which was recently changed a bit.

> So how about changing the UI such that you select a rotation axis (X, Y or Z) and angle (-90, 0, 90, 180), and possible flips for each axes? Constructing the transformation from this information is straightforward, and we can get rid of _ortho_bases completely.

Sounds good to me :)

**Comment by Zebcash** [comment]
For UI, I don't know,
I had only one problem of rotation with the 3D Tiles in the gridmap, but I
solved that by tatoning based on:
https://github.com/godotengine/godot/blob/master/core/math/matrix3.cpp#L290
That said I learned the code alone and I still have a lot of progress to
make in this area. The Gdscript is a very easy tool to understand for
someone who uses the code occasionally, hence my choice on godot, my
reflection on this subject and just that the matrix3 system is a bit
twisted, and that to find a solution more Intuitive (I'm a 3D graphics
designer) might be useful for non-codeware users. I suspect that priority
should not be my problem of locating in a 3D space via the code! ;-)
waiting for 3.0 for testing !!!

2017-01-13 19:49 GMT+01:00 Ferenc Arn <notifications@github.com>:

**Comment by Zebcash** [comment]
Ok... :-D Ah ! ah! ah!

2017-01-13 19:58 GMT+01:00 Rémi Verschelde <notifications@github.com>:

**Comment by tagcup** [comment]
OK, so I checked what exactly these orthogonal indices are. There are just all possible [cube rotations](http://www.euclideanspace.com/maths/discrete/groups/categorise/finite/cube/), with no reflections.
It seems they form a "nice" sequence (except for the last 4) if we assume that they're rotation matrices written in ZYX-convention Euler angles (which is different from Godot's overall XYZ convention!).

First, let me define a simple notation, in which trio of ZYX Euler angles are written as a vector in units of π/2. For example, a rotation of R_z(π/2).R_y(2π/2).R_x(3π/2) is written as (1,2,3). To further simplify the notation, I'll just write `1 2 3`

Then the 24 orthogonal matrices correspond to Euler rotations given as
```
0 0 0
1 0 0
2 0 0
3 0 0

0 0 1
1 0 1
2 0 1
3 0 1

0 0 2
1 0 2
2 0 2
3 0 2

0 0 3
1 0 3
2 0 3
3 0 3

0 1 0
1 1 0
2 1 0
3 1 0

2 3 0
3 3 0
0 3 0
1 3 0
```

There are many other alternatives for basis of course. We need to choose a basis such that

1. It uses XYZ convention
2. There is a simple correspondence between Euler angles and the index to this matrix list, such that we can have a nice UI.

After thinking about this a little, I'm planning to submit a PR to implement this soon (sans the actual UI implementation). The UI, which can come in a later PR, can look like this:

Z-rotation (first rotation): (integer)
Y-rotation (second rotation): (integer)
X-rotation (third rotation): (integer)

Integers will be mod 4, of course. And there will be 64 combinations, of which 40 of them are redundant. This degeneracy needs to be lifted manually only in `set_orthogonal_index` though, `get_orthogonal_index` is fine since it will map one of the 24 matrices to an index.

**Comment by reduz** [comment]
as nothing was done on this, will kick to 3.1 
keep in mind that whatever you add, it will still need to be compatible with old saved scenes

**Comment by tagcup** [comment]
Yeah, I've been a bit busy these days. Sure, sounds good. It's just a usability issue anyway

**Comment by Wiadomy** [comment]
Hey, flipping feature could be useful to introduce move variations in tiles.

`for a wall for exemple I must had 4 Tiles (North, East, West, South)`
I'm not sure if rotating was implemented back then, but if yes - it is possible to do such thing with only one tile, at least for me. The origin just needs to be set right.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by aschuhardt** [comment]
For anyone else who winds up here from a search engine, here is a helpful chart I found:
![BblmzVh](https://user-images.githubusercontent.com/13511943/147859229-bf4259a5-ad11-4dab-b8d6-359e5c32bbaa.png)

Source: https://old.reddit.com/r/godot/comments/6y5gwa/gridmap_rotations_chart/
