### ISSUE TITLE
Shortcuts to open PopupMenu of MenuButton do not work

### ISSUE THREAD

**Issue by bfedie518** [godotengine/godot#66403]
### Godot version

4.0 beta 1

### System information

Windows 10

### Issue description

`Shortcuts` on `MenuButtons` don't work in the 4.0 beta.  They work in 3.5.

### Steps to reproduce

1. Create a `MenuButton`
2. Add a `Shortcut` to the `MenuButton` under its `BaseButton` properties
3. Run project and watch it not work

In the minimal reproduction project, there are four buttons.  
1. A menu button with F1 set as a shortcut through the editor
2. A menu button with F2 set as a shortcut through a script
3. A regular button with F3 set as a shortcut through the editor
4. A regular button with F4 set as a shortcut through a script

The regular button shortcuts work.  The menu button shortcuts don't.  This example uses `InputEventKey`s, but behavior is the same for other `InputEvent` types.

### Minimal reproduction project

[menu_button_shortcut_bug.zip](https://github.com/godotengine/godot/files/9640898/menu_button_shortcut_bug.zip)

**Comment by EricEzaM** [comment]
To clarify: the shortcuts within the popup menu of the MenuButton work, what doesnt work is making the PopupMenu pop up when the shortcut for the MenuButton is activated.

**Comment by bfedie518** [comment]
A temporary workaround is to open the popup manually using an `InputEvent` in `_input()`.  Although this runs into #66308, which has its own [workaround](https://github.com/godotengine/godot/issues/66308#issuecomment-1257326868).

**Comment by andrewruales** [comment]
How can I get started on this issue as a first time contributor?

**Comment by bfedie518** [comment]
@andrewruales Read the [Contributing](https://docs.godotengine.org/en/latest/community/contributing/index.html#) section of the docs, then:
1. Fork Godot
2. Make a new branch
3. Find and fix the bug (presumably it's somewhere in `Shortcut`, `Basebutton`, or `MenuButton`)
4. Open a pull request

**Comment by EricEzaM** [comment]
Take a look at the shortcut_input method on Menu Button. Some code needs to be added here to trigger/press the button when the shortcut is activated.

Look at the logic in the base button, and how it activates the button when a shortcut is pressed:
https://github.com/godotengine/godot/blob/84f2c68c84bde10026454292578e5fdcc9ab69a3/scene/gui/base_button.cpp#L352

It will be very similar to that base button logic. I would probably make it so that checking the shortcuts for popup items is done before checking the shortcut for the button, as activating some action is more important that opening the popup for the menu button (if there is a shortcut clash)

**Comment by andrewruales** [comment]
Can you assign this issue to me? working on it now

**Comment by andrewruales** [comment]
Can you assign this issue to me? I am working on it now.

**Comment by Calinou** [comment]
> Can you assign this issue to me? I am working on it now.

For future reference, we only use the assignees feature for core contributors (and we don't always use it in the first place). Since contributors can leave at any time for any reason, we'd rather avoid a situation where nobody is working on an issue because it's assigned to someone who is no longer active.
