### ISSUE TITLE
Improvements on the High-Level Multiplayer API

### ISSUE THREAD

**Issue by Faless** [godotengine/godot#6642]
# Motivation

The current multiplayer API is very promising, and easy to use. There are though, in my opinion, 2 limitations:
- It does not allow to optimize the network usage by not exposing multiple **ENet channels** (see http://enet.bespin.org/Features.html#Channels )
- It does not allow to test both client and server in the same instance.

I'm opening this issue since I'd like some **feedback** from the community and the developers regarding the new features and the design.
# Proposal

My proposal is composed by two parts:
## Expose channels

Reserve the 2 channels already in use by Godot and allow to specify the number of custom channels to be used in `create_server` and `create_client` (minimum 1)
- All calls to `put_packet(packet,len)` will send the packet to the first custom channel
- SceneTree will call `put_packet(packet,len,CHANNEL)` (where CHANNEL is currently 0 and is reserved)
- From GDScript `put_packet_channel(packet,channel)` will be available in order to send the packet on `channel + first_custom_channel`
- SceneTree will emit `network_peer_packet(sender:int,channel:int,packet:RAW_ARRAY)` when receiving a packet on a custom channel. In this case `channel` will be `actual_channel - first_custom_channel`

(I have this partially implemented already in a private repo, I'm still cleaning up the code. See note 1 for a more detailed description)

This will keep the compatiblity with the current system, it will still not allow to test multiple clients on the same scene, but will enable the user to have multiple channels available for any custom data he'd like to send.

This brings us to the second proposal.
## Expose Poll and create NetworkedMultiplayerNode
- Shuoldn't we expose the `poll()` method of `NetworkedMultiplayerENet` to GDScript?
- Create a `NetworkedMultiplayerNode` that mimics the current behaviour of `SceneTree` concerning polling and handling network signals (including the new `network_peer_packet`)
- Possibly expand the node behaviour also to mimic the scene synchronizations with relative node paths (probably a long shot).

---
# Notes
## Note 1 - Details of phase one
- Add `RESERVED_CHANNELS` pre-compiler define to `NetworkedMultiplayerPeer` (the first reserved channel, that is also the number of reserved channels)
- Add function `put_packet(packet,len,channel)` to `NetworkedMultiplayerPeer`
- Override `put_packet(packet,len)` with a call to `put_packet(packet,len,RESERVED_CHANNELS)` in `NetworkedMultiplayerENet` (so default GDScript binding will send the packet on the first custom channel)
- Add function `get_packet_channel()` to `NetworkedMultiplayerPeer` (it works, like `get_sender`, on the next incoming packet)
- Update `SceneTree` to use `put_packet(packet,len,0)` (0 is the channelID already in use)
- Update `SceneTree` to emit signal `network_peer_packet(sender:int,channel:int,packet:RAW_ARRAY)` packets on `channel >= RESERVED_CHANNELS`
- Add function `put_packet_channel(packet, channel)` to `NetworkedMultiplayerENet` GDScript binding (the default `put_packet(packet)` will send the packet on the first not reserved channel) \
  Note: All GDScript references to `channel` will be considered as `channel + RESERVED_CHANNELS`
## Note 2

Example to test udp network code stability locally with iptables (20% packet loss simulated).

```
iptables -A INPUT -p udp --sport SERVER_PORT -m statistic --mode random --probability 0.2 -j DROP
iptables -A INPUT -p udp --dport SERVER_PORT -m statistic --mode random --probability 0.2 -j DROP
```

**Comment by WalasPrime** [comment]
I haven't stumbled upon the need to use multiple channels yet, but the problem with testing clients and servers pretty much occured right away. I've worked this around by copying the godot's executable into the project's directory. Not the best way to do that really...

Ideally there should be an optional project setting (eg. "client-server testing mode") that would change the play button to a "run client and server" button, where two instances of the project would be started (debugging and profiling-wise only one instance would be taken care of, for the sake of simplicity).

**Comment by NathanielLLally** [comment]
My dilemma with the current 2.1+ networking is the inability to have a server and client in the same scene tree.  I have a server/client multiplayer game which I coded to have each as a standalone as well as individual AI players as standalone clients.  The issue arises when an android user without a connection wishes to play versus the AI.  There is no platform=server & platform=android compilation (yet) so I must instantiate the server and AI's within a single tree in the gui application- which is fine, except for the whole one scene tree per either client or server.  This has forced me to conditionally not execute any rpc call- which is quite cumbersome and entirely unnecessary (this is the purpose of a loopback) I was thinking about forking godot and having enet belong to a node rather than being contained by scene tree this way I could kludge all 3 in one process by addressing each as targetNode.rpc_id etc... however, I was uncertain as to the current direction devs are going with it...

As far as the channels are concerned, I could use them in this same project for different QoS bands..  One channel for the large chatty datasets and another for "interactive" type bands akin to a linux router setup with ssh and torrent on different bands.  Currently I am forced to use yield / timer at known choke points to ensure that latency doesn't interfere with the order of operations in terms of synchronization.

**Comment by bojidar-bg** [comment]
@NathanielLLally Note that you can make ... (drumroll) ... another SceneTree! For example, I've done something similar here: https://github.com/KOBUGE-Incubator/multiball/tree/615e0f07c6f30ab7e1d337b512dac1c6761957de/game/menu

**Comment by NathanielLLally** [comment]
mind blown ;p thanks for the ex.

**Comment by raymoo** [comment]
#16733
