### ISSUE TITLE
Changing the Play shortcut gets overwritten every restart

### ISSUE THREAD

**Issue by keyle** [godotengine/godot#66428]
### Godot version

4.0 beta 1

### System information

macOS Monterey (12.6) on Intel with AMD Radeon RX 6600 XT

### Issue description

Minor bug, changing the Play shortcut gets overwritten every restart.

this does not occur if you add a secondary shortcut (command+B and F5), only if you replace.

### Steps to reproduce

- load settings
- change shortcut for Play (e.g. F5)
- F5 does work
- restart Godot 4
- F5 shortcut has been removed

### Minimal reproduction project

Any base project, I tested with Vulkan mobile profile.

**Comment by EricEzaM** [comment]
Cannot reproduce on Windows 10 using f74491fd

Can you maybe record a video of it? It is a bit confusing because F5 is the default for 'Play' so when you say change shortcut to F5 I'm not sure what you are doing exactly.

You could also open your `editor_settings.tres` file in VS Code for example, and see if/how it changes as you restart the editor. The customised shortcuts are listed at the bottom.

**Comment by keyle** [comment]
Thanks, I tried.

Is there a crash log location on macOS for Godot4? I couldn't reproduce it today however it crashed while changing shortcut... I'd like to at least produce the log for that.

**Comment by DATADEER** [comment]
@EricEzaM I've replicated the Behaviour in v4.0.beta10.official [d0398f62f] as mentioned in https://github.com/godotengine/godot/issues/70682

I've documented the changes on the`editor_settings-4.tres` (found in `/Users/YOUR_USERNAME/Library/Application` on macOS) Support/Godot) in a Gist.

https://gist.github.com/DATADEER/6c8dad6f3f6f28bd5d5379bb9b7d9d39/revisions

1. In the first revision the `Run Project` command was already set to <kbd>F10</kbd> 
2. In the second revision i've changed `Run Project` command to <kbd>F5</kbd>
3. In the third revision i've restarted Godot and checked the "Editor Settings" -> Shortcuts and saw that `Run Project`  has been changed back to <kbd>cmd</kbd> + <kbd>b</kbd>

**Comment by EricEzaM** [comment]
Thanks @DATADEER. I can't test Mac at the moment so if you could, I would appreciate your help. Could you see if the same issue happens when changing `filesystem_dock/rename`? Default on Windows is F2, on Mac it's Enter.

**Comment by EricEzaM** [comment]
I can reproduce on windows if I add something like `ED_SHORTCUT_OVERRIDE("editor/run_project", "windows", Key::F10);` to editor node, just below where the other shortcuts are set.

Basically this only happens if you are on a platform which overrides a shortcut and you change the shortcut to be the same as the non-overriden shortcut. So in this case, changing the shortcut to `F5`. What happens is that when running the `_OVERRIDE` code, it checks to see if the events array of the 'original' is the same as current. If this is true, it is assumed the user has not customised the shortcut. However this bug proves that is a bad assumption, as the user may have customised the events to be the same as the non-overridden value.

Reading back that explanation I'm not sure if it is very clear. But I think it is an easy fix.
