### ISSUE TITLE
iOS memory leak on touch input

### ISSUE THREAD

**Issue by djrain** [godotengine/godot#66422]
### Godot version

3.5 stable, 3.5.1 RC2

### System information

macOS, iOS

### Issue description

On iOS, touch input causes memory to leak, even in an empty scene with just a Node2D root (tested on iPhone 6s and 2020 iPhone SE). The leak seems to occur specifically on touch begin (not hold/release), and repeated multitouch tapping will increase the memory use by several MB within a few minutes. This also seems to degrade the FPS more and more as tapping continues.

Seems the leak was introduced back in 3.2.3 (it's not present in 3.2.2) - perhaps by #40723 somehow?

### Steps to reproduce

Open a fresh project with an empty test scene, export and run on iOS from Xcode. Repeatedly tap the screen (quite a lot), and Xcode should show the app's memory usage increasing permanently.

### Minimal reproduction project

any project should do

**Comment by akien-mga** [comment]
CC @godotengine/ios

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/32139.

**Comment by djrain** [comment]
Tried running Instruments leak tool for the empty scene - I'm tapping throughout this video and we can see memory increase, but no leaks are detected.
(this is Godot 3.5)

https://user-images.githubusercontent.com/33777501/193625959-1994e023-31a1-4d1f-ad13-861307be2c6f.mov

**Comment by tbveralrud** [comment]
The leak occurs in the gesture recognizer due to an incomplete implementation. Per [the docs](https://developer.apple.com/documentation/uikit/uigesturerecognizer?language=objc), part of their requirement is:
> Subclasses must set the `state` property to the appropriate value when they transition between states.

and

> Subclasses must also periodically reset the `state` property

It appears that recognizers need an "end" state in order to purge accumulated touch events.

I experimented by replacing this gesture recognizer with a vanilla `UIGestureRecognizer`, which _doesn't_ adhere to the above, and it reproduces the memory leak.

Furthermore, I placed a `state = UIGestureRecognizerStateEnded` at a seemingly logical spot in the current implementation and while it resolved the leak it caused runtime assertions in `GodotView`. The existing logic in the view requires side effects of this unending gesture recognizer state.

This said: I believe using a gesture for ALL touch input is inappropriate. Sending the raw touch events from the view to Godot suffices and is a simpler implementation. This also removes the need for the special cased delay that exists for the iOS platform.

I have a branches for [3.x](https://github.com/godotengine/godot/pull/69200) and [master](https://github.com/godotengine/godot/pull/69201) available for review.
