### ISSUE TITLE
OpenGL: Environment fog does not affect sky rendering

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#66456]
### Godot version

4.0.beta (53d2a9acd)

### System information

Fedora 36, GeForce GTX 1080 (NVIDIA 515.65.01)

### Issue description

Unlike in Vulkan, environment fog does not affect sky rendering when using the OpenGL renderer. Fog Sky Affect's value is ignored.

### Fog disabled

![2022-09-26_20 01 30](https://user-images.githubusercontent.com/180032/192348038-0daa9f4f-022d-41f0-aaff-6aff320504d8.png)

### Fog enabled

![2022-09-26_20 01 26](https://user-images.githubusercontent.com/180032/192348033-d9b03f11-cbbd-4c42-aef3-062716253106.png)

### Steps to reproduce

- Switch to the OpenGL driver in the Project Settings.
  - Make sure to start the editor with single-window mode enabled afterwards. This can be done by enabling **Single Window Mode** in the Editor Settings before changing the driver, or by opening the project in the editor directly with the `--single-window` [command line argument](https://docs.godotengine.org/en/latest/tutorials/editor/command_line_tutorial.html).
- Add a WorldEnvironment node, a Camera3D node and a MeshInstance3D in front of the camera.
- Enable fog. Increase density to 0.05 or more to make a visible difference in the scene.

### Minimal reproduction project

[test_opengl_fog_sky_affect.zip](https://github.com/godotengine/godot/files/9648583/test_opengl_fog_sky_affect.zip)

**Comment by ParsleighScumble** [comment]
I've been looking into fixing up some of the GLES fog issues because of the fog_sky_affect issue. There are some uniforms in the sky shader but they ain't exactly hooked up to the rendering backend properly. I wanted to pick your brain @Calinou and @clayjohn about what approach the Godot team would like here. Should we pack those guys in a UBO SkySceneData (name in shader) with a struct SkySceneState (mirrored storage on host) to make it more like the Vulkan renderer? Then we would update values in the UBO from RendererEnvironmentStorage in void RasterizerSceneGLES3::_setup_sky. Or should we stick to setting individual uniforms and avoid making a new UBO?

**Comment by clayjohn** [comment]
@ParsleighScumble Either approach is fine. Initially I went with the individual uniforms for small things that change frequently, but once you have more than one or two uniforms, it becomes just as fast to pack everything into a UBO that you update every frame.

**Comment by ParsleighScumble** [comment]
Let's go with a UBO, then. I should have fog sky affect working in GLES pretty soon.

**Comment by Calinou** [comment]
I can still reproduce this on 4.3.dev 13a0d6e9b.

**Comment by ParsleighScumble** [comment]
I did get it working but it's a bit of a mess and I didn't get tonemapping working for all background modes. I can post what I have though.

**Comment by Calinou** [comment]
> I can post what I have though.

Please do :slightly_smiling_face:

**Comment by prabhask5** [comment]
Hi! I'm new to contributing, can I work on this issue? It looks like it's been a while since its been worked on.

I am a bit confused on what the end goal for this bug fix is from the pictures above. I see in https://github.com/godotengine/godot/issues/92019 that fog stops sky affects to be changed, is this the main issue here?

**Comment by Calinou** [comment]
> I see in https://github.com/godotengine/godot/issues/92019 that fog stops sky affects to be changed, is this the main issue here?

Yes, fog should affect sky rendering to the extent set by the Environment **Fog Sky Affect** property. That property defaults to 1.0, which means the sky color should match the fog color according to the Camera3D's Z far property (the sky is assumed to be at the same depth as Z far).
