### ISSUE TITLE
Long loading of custom theme in Godot 4.0 beta 1

### ISSUE THREAD

**Issue by Ghashy** [godotengine/godot#66469]
### Godot version

4.0 beta 1

### System information

MacBook Pro m1, Big sur 11.7, gles3

### Issue description

When I create a custom theme and apply it to any element (panel, tooltip, font, etc) the opening of this element increases loading time for approximately 4 seconds than without this theme

### Steps to reproduce

Create a panel element

Create a theme for it

Try to load with and without it

**Comment by Calinou** [comment]
@Ghashy Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

> Try to load with and without it

What are you referring to "loading"? Are you referring to running the project from the editor? The editor/project is currently slow to start compared to 3.x, especially on macOS due to MoltenVK limitations.

**Comment by Ghashy** [comment]
Just tried to reproduce this in beta 2, and issue has gone.
