### ISSUE TITLE
default grow direction

### ISSUE THREAD

**Issue by 36k-wild-monkey** [godotengine/godot#66470]
### Godot version

v4.0.beta1.official [20d667284]

### System information

Windows10

### Issue description

Please set "Horizontal" to "Right" by default and "Vertical" to "Bottom" by default

I am used to using html layout, but when I use godot anchor points, almost every anchor point needs to change the growth direction. I think the default setting is unreasonable. When the window is zoomed, the component moves to the left all the time. Normally, it should remain unchanged. If this cannot be modified, it may be good to add a global default property setting page

### Steps to reproduce

none

**Comment by clayjohn** [comment]
The issue tracker on the main Godot repository is for tracking bugs only. It sounds like you have an idea how some behaviour could change in Godot that would be more intuitive. Accordingly, I suggest that you open a discussion in the [godot-proposals](https://github.com/godotengine/godot-proposals) repository so that this can be discussed with other users.
