### ISSUE TITLE
No response when resizing the panel

### ISSUE THREAD

**Issue by ProgrammerMao** [godotengine/godot#66498]
### Godot version

4.0 beta1

### System information

Win11 22H2, Intel UHD Graphics 730, 31.0.101.3413

### Issue description

After entering any item
If you resize the panel, it will not respond
However, it is no problem to adjust the panel separated into windows
This problem also appears in the alpha 10 version
I haven't tried any earlier version
(From Baidu Translation)

进入任意项目后
调整面板大小就会未响应
不过调整被分离成窗口的面板是没问题的
这个问题在alpha10的版本也出现了
再早的版本我没试过

### Steps to reproduce

After entering any item
If you resize the panel, it will not respond
(From Baidu Translation)

进入任意项目后
调整面板大小就会未响应

### Minimal reproduction project

beta1 和 alpha10
beta1 and alpha10

https://user-images.githubusercontent.com/72609054/192550648-2126775c-a34c-44ca-957d-fe67c8be2a8f.mp4

**Comment by ProgrammerMao** [comment]
似乎只有调整大块的面板才会未响应

It seems that only the large panel will not respond

**Comment by ProgrammerMao** [comment]
![屏幕截图 2022-10-01 094618](https://user-images.githubusercontent.com/72609054/193378456-1fbce832-b2ba-4f3a-83fd-e52cc01e1368.png)

在未响应的时候会3个报错
Three errors will be reported when there is no response

**Comment by YuriSizov** [comment]
There don't seem to be any other reports of this kind, and this was reported during late alphas/early betas. Steps described are not enough to reproduce the problem with the latest version of Godot 4, and the errors demonstrated on a screenshot are not related to it.

So I'm going to assume this was some temporary issue that has since been resolved. Please let me know if you can still reproduce it with 4.0 stable.
