### ISSUE TITLE
Leaving dock area in ranges in inspector releases mouse

### ISSUE THREAD

**Issue by GuilhermeGSousa** [godotengine/godot#66555]
### Godot version

14e1f36e614686f3fea0c74fac3624d1027dd5cc

### System information

Windows 10

### Issue description

When dragging a slider in the inspector, the mouse is released if it falls outside of its dock area:

![slider_bug](https://user-images.githubusercontent.com/13313321/192846006-0505ccc7-4783-4a38-9b24-c93a5a2d1140.gif)

From what I could test it seems to affect all uses of `EditorSpinSlider`. 

### Steps to reproduce

- Add this script to a node:
```gdscript
extends Node

@export_range(0, 1) var x : float
```

- Drag the mouse outside of the dock area without releasing the mouse

### Minimal reproduction project

Should be easy enough to reproduce without one, I can however provide one if needed

**Comment by Zireael07** [comment]
dupe of #64695?

**Comment by GuilhermeGSousa** [comment]
@Zireael07 Similar but I dont think so, that one was very specific to the TileMap editor, this one seems to affect everything that uses a range on the inspector.

**Comment by lmurray** [comment]
Dragging the slider has a different behavior than dragging in the text box above the slider which uses mouse capture to permit infinite dragging in either direction. For usability purposes I think they should both have the same behavior as it took me a while to figure out why sometimes I can drag the value outside of the sliders range while other times being constrained by it (by accidentally clicking on the slider instead of the text box).

**Comment by tinmanjuggernaut** [comment]
Duplicate of #63544, allegedly fixed in #63598.

**Comment by GuilhermeGSousa** [comment]
Closing as duplicate of https://github.com/godotengine/godot/issues/63544
