### ISSUE TITLE
No way to get a tile's name in GDscript

### ISSUE THREAD

**Issue by willhansen** [godotengine/godot#66642]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Ubuntu 22.04.1 LTS

### Issue description

I can't seem to find any way to get a tile's name from GDscript in V4.  In V3.5, I would have used `TileSet::tile_get_name`, but it looks like that was removed in [this commit last May](https://github.com/godotengine/godot/commit/a3dda2df85bf3e3ef82dbe1c2377640b9f3fd9c0)

### Steps to reproduce

https://docs.godotengine.org/en/latest/classes/class_tileset.html#methods

**Comment by groud** [comment]
Tile have no names anymore in 4.0

**Comment by groud** [comment]
Closing per the above comment, since this is expected.

I don't think we should bring back the possibility to name tiles, as I am not sure it was really useful. But if you feel like named tiles is an important feature to have, please [open a proposal](https://github.com/godotengine/godot-proposals/issues) instead.
