### ISSUE TITLE
Physical Bone Joints broken

### ISSUE THREAD

**Issue by danemadsen** [godotengine/godot#66645]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

Windows 11 and Manjaro Linux

### Issue description

Joints for physical bones are broken in Godot 4. When a scene containing a physical bone with a joint is run in Godot 4 an error is thrown stating "E 0:00:01:0190   pin_joint_set_param: Condition "joint->get_type() != JOINT_TYPE_PIN" is true.
  <C++ Source>   servers/physics_3d/godot_physics_server_3d.cpp:1249 @ pin_joint_set_param()" 

![Screenshot 2022-09-30 043406](https://user-images.githubusercontent.com/11537699/193190992-ba4f79c0-d299-4f3c-b1bc-4fea02bddfd5.png)

This issue effects all joint types and throws similar errors if cone, hinge, slider or 6DOF joints are used.

### Steps to reproduce

1. Create a simple skeleton3D with at least 2 bones
2. Create a physical skeleton from the skeleton3D
3. Ensure all bones except the root bone have a joint applied
4. Run the scene

### Minimal reproduction project

[PhysicalBoneJointIssueReport.zip](https://github.com/godotengine/godot/files/9680778/PhysicalBoneJointIssueReport.zip)

**Comment by danemadsen** [comment]
Any ideas where to start with this issue? I would like to try and fix it myself if I can but IDK where to start. 

I tried to comment out ERR_FAIL_COND(joint->get_type() != JOINT_TYPE_PIN); in pin_joint_set_param to see what would happen but I got the same error.

**Comment by danemadsen** [comment]
Ok so i was wrong. Commenting out ERR_FAIL_COND(joint->get_type() != JOINT_TYPE_PIN); does fix the issue but as this is an error throw condition i would imagine this isnt going to be an acceptable fix.

**Comment by danemadsen** [comment]
For some reason when godot starts the provided project pin_joint_set_param is called 6 times. The first 3 times joint and pin_joint have the JointType JOINT_TYPE_MAX despite being declared as JOINT_TYPE_PIN and then for the preceding 3 times they have the correct type.
![Screenshot from 2022-10-14 14-38-10](https://user-images.githubusercontent.com/11537699/195764000-d5c3e11f-86c3-4307-9c76-a65756a139f2.png)

**Comment by danemadsen** [comment]
The issue is coming fom PinJointData::_set in physics_body3d.cpp

for some reason J here has the default value of JOINT_TYPE_MAX

![Screenshot from 2022-10-16 19-47-31](https://user-images.githubusercontent.com/11537699/196029021-45bc35e3-42fd-4b9a-a15c-d268b534403d.png)

**Comment by danemadsen** [comment]
It appears that _reload_joint is failing inside set_joint_type because parent_skeleton is NULL.
![Screenshot from 2022-10-16 21-05-00](https://user-images.githubusercontent.com/11537699/196035796-a58e94f6-cf03-4ff0-a421-d8ff5bf18d0e.png)

**Comment by TheContainer** [comment]
Im getting the same error, is it fixable somehow?

**Comment by danemadsen** [comment]
> Im getting the same error, is it fixable somehow?

Not currently. You can disable the error like I did in the pull request I've now closed but that will just cause a memory leak.

It seems to be caused by _reload_joints failing to get the skeleton3D parent. 

I'm currently trying to fix it but I'm very new to working on a big project like this.

**Comment by Bauxitedev** [comment]
I can confirm this bug on Godot 4 beta 10. Ragdolls are *completely* broken.

https://user-images.githubusercontent.com/31383123/209440915-08bcff06-a065-4d82-a23e-dade0466658a.mp4

The spazzing seems to be caused by self-collisions between adjacent parts of the ragdoll. If I disable self-collisions (by changing the collision layer/masks), the spazzing goes away:


https://user-images.githubusercontent.com/31383123/209441022-25dbc0bc-4675-45f8-b736-ea693bc4db4d.mp4

However, this is not a satisfactory solution either, because you do want some degree of self-collision. For example, arms should be able to collide with the torso. Not to mention this doesn't fix parts of the ragdoll seemingly disconnecting from each other, as seen in the first video.

**Comment by danemadsen** [comment]
@Bauxitedev I believe your issue is separate to this issue, as this issue is related to 3D joints and your issue seems to be related to collisions. 

I recommend opening up a new issue

Nevertheless thanks for your input.

**Comment by Bauxitedev** [comment]
@danemadsen I don't think this is a separate issue, because of two reasons.

1. I'm getting the exact same error spam as see in the OP:
```
E 0:00:03:0356   pin_joint_set_param: Condition "joint->get_type() != JOINT_TYPE_PIN" is true.
  <C++ Source>   servers/physics_3d/godot_physics_server_3d.cpp:1250 @ pin_joint_set_param()
```

2. Joints and collisions are closely related. In Godot's physics engine, creating a joint between two rigid bodies A and B usually disables the collision between them. This is needed for stability purposes, because A and B's colliders may intersect each other at the moment of the joint's creation, as is the case with ragdolls. However, due to the aforementioned error spam, we can deduce that the joints aren't being created properly, which probably also means the collision between the bodies isn't being disabled properly.

**Comment by lyuma** [comment]
I cannot reproduce this on 4.0 rc6
Maybe I'm not following the steps for "Ensure all bones except the root bone have a joint applied" exactly right. I tried opening the attached .tscn but it also produces no error messages.

**Comment by danemadsen** [comment]
> I cannot reproduce this on 4.0 rc6 Maybe I'm not following the steps for "Ensure all bones except the root bone have a joint applied" exactly right. I tried opening the attached .tscn but it also produces no error messages.
> 
> I also haven't managed to get the physical bones to move at all in the test scenes, so maybe that's what is meant by "Broken". I just want to make sure I understand the bug correctly.
> 
> here's a .tscn I tried to make: [joint_test.tscn.txt](https://github.com/godotengine/godot/files/10839083/joint_test.tscn.txt) but nothing seems to happen with or without joints. I would have expected gravity, or some movement upon impact.

Can confirm this error is no longer present. Would love to know which PR fixed this issue but cant seem to find one.
