### ISSUE TITLE
2.2-alpha android export apk excludes armeabi native platform in favor of armeabi-v7a

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#6666]
**Operating system or device - Godot version:**
Xubuntu 14.04 64-bit, Godot 2.2-alpha vs Godot 2.1-stable

**Issue description** (what happened, and what was expected):
It looks like native platform for apk exported from 2.2-alpha is set to armeabi-v7 and armeabi platform is ignored, resulting in excluding some of the android devices from supported list in Google Dev Console.
 
As much as adding 64-bit platform is a very good move, letting the older platforms still be available by default (if possible), or via menu settings in 'Android Export' would be a better option imho.
Let the user decide if he wants armeabi-v7 or armeabi.

**Comment by RandomShaper** [comment]
You can build the export templates with support for both architectures.

Anyway, pre-ARMv7 devices with FPU are pretty rare.

**Comment by freemanfromgodotengine** [comment]
Thx @RandomShaper, I should have expected that, after all it's Godot and all can be set if one knows how ;)
I just could not find any information. 
How do I do that, if it's not a secret?

**Comment by RandomShaper** [comment]
I'm not sure you're aware of [the compiling instructions for Android](http://docs.godotengine.org/en/latest/reference/compiling_for_android.html).

In order to build for ARMv6, invoke SCons accordingly: `scons platform=android target=release android_arch=armv6` and/or `scons platform=android target=debug android_arch=armv6`.

That will add the ARMv6 libraries to `platform/android/java/libs/<target>` so the next invocation of Gradle will put them inside the APKs.

In fact you don't even need to build the ARMv7 variants at all and if you don't need them, you can remove the `armeabi-v7a` directories and invoke Gradle again so your APKs get smaller.

**Comment by RandomShaper** [comment]
Actually, it was a secret, but now it's been revealed!

**Comment by freemanfromgodotengine** [comment]
I use compiling instructions all the time & my compilation is full of different settings to scrap the engine of things I don't need, but could not find any android specific tags for some reason (android related blindness?).
I think I will open Q&A with this one, and put that answer. More people might want to know about our secret that is not so secret now ;)

**Comment by freemanfromgodotengine** [comment]
ok, its there https://godotengine.org/qa/8612/compile-android-different-architectures-working-armv6-armv7?show=8613#a8613, so I close the 'issue' 
Thx again @RandomShaper

**Comment by RandomShaper** [comment]
You're welcome!
