### ISSUE TITLE
Rendering issues with GLTF models

### ISSUE THREAD

**Issue by cbscribe** [godotengine/godot#66775]
### Godot version

4.0 beta2

### System information

MacOS 12.5

### Issue description

Imported GLTF models are rendering incorrectly or displaying artifacts. These same models render correctly in 3.x. 

* Shadowed faces displaying line artifacts
3.x: 
![Screen Shot 2022-10-02 at 10 06 51](https://user-images.githubusercontent.com/3812514/193467123-38a2ac96-2005-473d-a53d-411a1d51326f.png)
4.0:
![Screen Shot 2022-10-02 at 10 04 46](https://user-images.githubusercontent.com/3812514/193467137-1fc5717d-c78f-4336-84c3-db62a150edc0.png)

* Some meshes not rendering correctly
3.x:
![Screen Shot 2022-10-02 at 10 09 19](https://user-images.githubusercontent.com/3812514/193467188-dfee2408-fa5f-4044-995c-a45bb12e9969.png)
4.0:
![Screen Shot 2022-10-02 at 10 09 25](https://user-images.githubusercontent.com/3812514/193467203-08fb6fc7-83d4-4204-9f70-d84d7956807e.png)

Even stranger, in the latter model, which contains separate meshes for the body and the 5 wheels, toggling visibility on different meshes affects the rendering of others, sometimes in irreversible ways.

I've attached the model file here as well.
[suv.glb.zip](https://github.com/godotengine/godot/files/9693082/suv.glb.zip)
[cartoon_plane.glb.zip](https://github.com/godotengine/godot/files/9693088/cartoon_plane.glb.zip)

### Steps to reproduce

Import .glb file and create an instanced scene.

**Comment by fire** [comment]
@clayjohn on the [suv.glb](https://github.com/godotengine/godot/files/9693082/suv.glb.zip), if i duplicate the second material on the missing wheel the material appears again. Any ideas?

**Comment by clayjohn** [comment]
> Shadowed faces displaying line artifacts

This is shadow acne from the default DirectionalLight3D. The issue is already tracked in https://github.com/godotengine/godot/issues/54523 and a draft PR has already been made https://github.com/godotengine/godot/pull/55757

> Some meshes not rendering correctly

I've run into this issue with imported GLTF files as well. But like Fire mentions it goes away when you make the material unique. It also is not reproducible using non-imported materials. My guess is it is an issue with the GLTF material importer but I am not familiar with that code.

**Comment by lyuma** [comment]
![image](https://github.com/godotengine/godot/assets/39946030/09b3603c-9750-49db-bd3e-918f8272fb7f)
The artifacts have been solved since the release of Godot 4.0.

Thanks for the report.
