### ISSUE TITLE
[Suggestion] - Option to choose entire folder and subdirectory for export

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#6679]
![1234](https://cloud.githubusercontent.com/assets/10387670/19019491/e785fd5e-883e-11e6-87a9-672bf148d809.png)

I have hundreds of gd scripts and other files that need to have their own .pck file (for patching later, etc) -- We cannot hold down shift + select multiple files either.  I am suggesting an option to select an entire folder and all its children and sub-directories to be exported! Would be a great quality of life feature!

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
