### ISSUE TITLE
Editor dock rendering is broken

### ISSUE THREAD

**Issue by Lawyno** [godotengine/godot#66834]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

5.19.7-1-MANJARO with Plasma 5.25.5

### Issue description

![Peek 2022-10-02 15-44](https://user-images.githubusercontent.com/2905247/193636560-ed3e898d-9131-48f6-ac66-d4cb0980aabe.gif)
When I open a project, most of the editor's `docks` are not visible at first. They reveal only when I play around with the `Dock Positions`. Only then, their tab becomes visible (and I finally able to work with them).

And I am not sure if that's the same issue, but as you can see in the image, the (3-dot) handles for the `Dock Positions` are also sometimes in a "messy" spot (see the file dock on the lower left for example).

I didn't experience this issue with 3.x versions, but with every 4.0 version I've tried so far (alpha15, alpha16, beta1, beta2 (all from [https://downloads.tuxfamily.org/godotengine/4.0/](https://downloads.tuxfamily.org/godotengine/4.0/))

### Steps to reproduce

Start Godot 4.0 and open an existing or new project.

**Comment by akien-mga** [comment]
Can you copy `~/.config/godot/editor_layouts.cfg` somewhere, delete the original, and see if that fixes the issue?

If it does, please attach the copied `editor_layouts.cfg` so we can check why it breaks things.

**Comment by Lawyno** [comment]
Well, I didn't find a file called `editor_layouts.cfg`. Instead I've found one called `editor_settings-4.tres`. Moving it out of that folder indeed ~~fixed~~ the issue.

After that, I found out that the issue was caused by my custom Editor Feature Profile, having `Node Dock`and `FileSystem Dock` deactivated for some weird reason I can't remember.
![Screenshot_20221014_220525](https://user-images.githubusercontent.com/2905247/195933003-2f81a22b-fead-4da0-b54c-d2edee26d85d.png)

Knowing that, I figured out that if you do that on v3.5 it's also an issue there.

**Comment by kitbdev** [comment]
Here are some reproduction steps for various issues with `EditorFeatures` docks
Start with all `EditorFeatures` enabled in the default layout

### Changing dock tabs shows docks that have only 1 hidden tab.
Reproduction steps:
1. Disable `FileSystem` dock in `EditorFeatures`
2. Change tabs in another dock - switch to the `Node` dock
3. `FileSystem` dock appears without a tab bar
![image](https://github.com/godotengine/godot/assets/10054226/64547cee-f029-410e-86d0-84a87cf0a8e5)


### Disabling the first dock of a dockslot with multiple docks
Reproduction steps:
1. Move `Node` tab after `FileSystem` dock
2. Disable `FileSystem` dock in `EditorFeatures`
3. The `FileSystem` dock is shown, but its tab is not there to be selected
![image](https://github.com/godotengine/godot/assets/10054226/371a70e2-d50f-46d3-99b8-3d8fda984515)


### Loading a layout with a disabled dock in a different slot unhides it
Reproduction steps:
1. Move `FileSystem` dock to a different dock slot
2. Disable `FileSystem` dock in `EditorFeatures`
3. Load default layout
4. The `FileSystem` dock is not hidden at all even though it should be disabled


There are other ways to reproduce the issues, but these were the simplest I could find and it should cover all of them.

These are caused by various implementations of `_update_dock_slots_visibility` and the layout loading not properly handling hidden tabs that `EditorFeatures` uses.
