### ISSUE TITLE
Mend fix visibility filtering options for .blend imports

### ISSUE THREAD

**Issue by fire** [godotengine/godot#66836]
### Godot version

1371a97acfb9263aaca7fa8642e95ba68534fa19

### System information

Windows 11, Nvidia 3000

### Issue description

\<Akien> I'm not sure this fix is complete, the logic that parses the option seems bogus as it treats the integer as a boolean. It will now "work" because All is 0 and so it will use the else branch which does the same as All, but that code is broken.

@jtnicholl

https://github.com/godotengine/godot/issues/66753

### Steps to reproduce

Need to recreate the sample.

### Minimal reproduction project

None

**Comment by jtnicholl** [comment]
I didn't notice that when writing the PR.
It _does_ work correctly, there's just some redundant checks and as a result, some code paths that can't be reached. Looking further, the same issue is there for the skinning and materials checks too. The skins one is especially bad since the second check that's never true sets the wrong arguments.
I can make another PR real quick to clean this up.
