### ISSUE TITLE
Typed arrays can't be used as type in checks using `is` keyword

### ISSUE THREAD

**Issue by kleonc** [godotengine/godot#66840]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

N/A

### Issue description

Typed array is not recognized as a valid type when used in check using the `is` keyword like `variable is Array[type]`.

### Steps to reproduce

E.g.:
```gdscript
@tool
extends EditorScript

func _run():
	var a: Array[int] = [1, 2, 3]
	print(a is Array[int])
```
![JF6slUKzqC](https://user-images.githubusercontent.com/9283098/193653348-bf0cac80-ddea-4027-bade-73fdebf33b4b.png)

**Comment by manueldun** [comment]
I am trying to fix this issue, I think the parser should treat the right operand of the "is" operator as an IdentifierNode or a TypeNode but it treats it as a subscript, I see that when the TypeNode is an int it treats it as a IdentifierNode, the problem is that is difficult to to know which method should I modify. the parse_precedence() method correctly treats Array as identifier (like with int) but then creates the SubscriptNode like I mentioned.

**Comment by Scony** [comment]
Duplicate of #54312

**Comment by kleonc** [comment]
@manueldun I'm not very familiar with the new GDScript code but I'd try to look how it's made to work properly in other places like: when declaring variable's type, or when declaring function argument's type.

@Scony Strange I haven't found that, I've looked over "typed array" related issues before creating this one. :astonished:

**Comment by kleonc** [comment]
> Duplicate of #54312
