### ISSUE TITLE
export android

### ISSUE THREAD

**Issue by ElGatton** [godotengine/godot#66892]
### Godot version

3.5.1

### System information

windows 11

### Issue description

normally in previous version of godot i can export my project in aab without any problem. In these version ... (i have latest gradle, sdk with all components 33 api) I
![Screenshot (36)](https://user-images.githubusercontent.com/106838359/193877417-1275271b-3b17-46a4-8a72-724f1c2f7bf2.png)
 cannot export my project in aab.

it returns error. I have finished my idea to fix this.
![Screenshot (36)](https://user-images.githubusercontent.com/106838359/193877470-495d3ce0-bc45-4959-8aa9-98687705d489.png)

### Steps to reproduce

i normally set the configuration that perfectly work in 3.44 but i received the same error. 

I tried to reinstall sdk  , android studio, update my java, work with jdk 8, work with jdk 11, work with jdk 12. NOTHING

**Comment by Calinou** [comment]
The issue is likely here:

https://github.com/godotengine/godot/blob/master/platform/android/java/app/gradle.properties#L12-L14

https://github.com/godotengine/godot/blob/master/platform/android/java/gradle.properties#L15-L17

I assume your machine only has 4 GB of RAM, and using a higher amount in `-Xmx` than the total system RAM won't work.

**Comment by ElGatton** [comment]
yes, that was the mistake. I have already solved. Thanks Ignacio. It's really nice to see someone responding to you in such a short time :) thank you
