### ISSUE TITLE
GDScript 2.0: `match` does not allow variable patterns anymore

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#66999]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

all

### Issue description

I want to migrate my plugin and had a parser implemented where is using tokens.
A token is just a object with some meta data, but is uniqe

```
var token_x := Token.new("x")
var token_y := Token.new("y")
...


match token:
    token_x: 
             .. make something
    token_y: 
             .. make something
```

This is the `Variable pattern and works fine in Godot3 but ends up with an compile error in Godot4

Zeile 14:Expression in match pattern must be a constant.
Zeile 16:Expression in match pattern must be a constant.

It blocks me to migrate my plugin, please take a look.

Thanks

### Steps to reproduce

here a simple example to reproduce
```
var TOKEN_A := Node.new()
var TOKEN_B := Node.new()

func _ready():
	var token := TOKEN_B
	
	match token:
		TOKEN_A: 
			prints("match a")
		TOKEN_B: 
			prints("match b")
```

**Comment by adamscott** [comment]
I confirm this issue on master (fcba87e).

### Minimal reproduction project
[66999.zip](https://github.com/godotengine/godot/files/10369088/66999.zip)

**Comment by adamscott** [comment]
@vnen Is there a reason behind the fact that `match` only now accepts constant values as entry?

**Comment by ShugarSkull** [comment]
I'm also curious about this, I've tried to search a little about it but could not find very much

**Comment by vnen** [comment]
> @vnen Is there a reason behind the fact that `match` only now accepts constant values as entry?

It was always supposed to only allow constants, but it also allowed identifiers since those could be constant as well. The only difference in Godot 4.0 is that it actually checks if it's a constant, so it fixes an oversight. This is not really a bug.

The reason for this initially was probably about how it works in other languages. Pattern matching is usually optimized by the compiler and it requires constant values for this. GDScript doesn't do any optimization of this sort (at least not yet) so it's debatable whether variable values should be accepted (and any arbitrary expression as well). 

As a partial solution we could now allow any identifier and attribute access (e.g. `x.y`) to restore behavior available in 3.x and consider the other cases later.

**Comment by MikeSchulze** [comment]
I understand that a match can only be made on const values.
Unfortunately I can't define an object as const which would make it much easier for me.

so for example
`const XXX := Token.new("XXX")`
Then I could use match again in my parser instead of a messy string of if/else
