### ISSUE TITLE
Exporting resource whose _init takes a parameter results in resource being null in scene startup

### ISSUE THREAD

**Issue by mavsm** [godotengine/godot#67059]
### Godot version

v4.0.beta2.official [f8745f2f7]

### System information

windows 10 

### Issue description

When attempting to export a resource whose _init function takes a parameter, that resource will be null when running the scene.
An error is also thrown when running the scene; _create_instance: Error constructing a GDScriptInstance.

Im not sure what the expected behaviour should be, but at least the error thrown in this case should be more descriptive, as currently it doesn't even point to a given resource being the issue, its stack trace leading to gdscript.cpp:183. 

### Steps to reproduce

1. Open the reproduction project
2. In the only node in the scene, see that its Res resource is exported and set.
3. Run the scene with F6, check the resource again in Remote.
4. See the error reported by the debugger as soon as the scene began.

### Minimal reproduction project

[ResourceExportTest.zip](https://github.com/godotengine/godot/files/9738023/ResourceExportTest.zip)

**Comment by Regnaris** [comment]
Can confirm similar problem for 3.5.1 stable. In my case I was using custom resources in tool script and after reloading editor every resource becomes null for tool scripts.

Seems related to #38222 and somewhat related to #37907

Maybe we need some warning about using _init with arguments, because it can lead to unexpected behavior.

**Comment by lemilonkh** [comment]
Just encountered this in 4.0 stable. Was really confusing to debug, as the error message in the debugger is just `_create_instance: Error constructing a GDScriptInstance`. Only figured it out by reading the C++ source and realising that it might be related to my custom `_init` function that was taking parameters. Would be good to print a more descriptive error message here, since the behavior of having resources that seem valid in the editor suddenly being suddenly null when you run the project is very confusing (I just thought I had hit a bug with Godot 4's custom resource typed array exports initially until trying more types of exports).

**Comment by AThousandShips** [comment]
The class is instantiated in the scene loader, so the function would need default values to work correctly if the `_init` function should indeed be used.

**Comment by qsrenniks** [comment]
It would be best to at least warn the user that a resource requires a default constructor.

**Comment by AThousandShips** [comment]
Yes, as the related proposal godotengine/godot-proposals#5899 does

**Comment by Calinou** [comment]
Consolidating with https://github.com/godotengine/godot-proposals/issues/5899.
