### ISSUE TITLE
Label render issue

### ISSUE THREAD

**Issue by drmar** [godotengine/godot#67114]
### Godot version

3.5.1.stable

### System information

M1 MacBook Pro, macOS 12.6

### Issue description

I'm updating a Label's text from _physics_process().
When the text stops updating, the text is sometimes kind of between states.
Even weirder, when I take a screenshot, the issue doesn't show up.

### Steps to reproduce

Open the attached project, move the Godot icon around with the arrow keys and pay attention to the "cone rotation deg".

### Minimal reproduction project

[angles.zip](https://github.com/godotengine/godot/files/9740914/angles.zip)

**Comment by TheDuriel** [comment]
Your code is continuously over and undershooting its target value of 360. Because you are relying on naive float comparisons. Casting to int doesn't solve this because you're just flooring the value.

I really am not sure what you're trying to accomplish here. But there is absolutely no engine bug present. You wrote it to do this.

**Comment by drmar** [comment]
Thanks, @TheDuriel! You comment helped me understand what the problem with my code was.
Sorry about the bug false alarm!
