### ISSUE TITLE
On-demand shader compilation causes hiccups

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6713]
(Not using the template as this is a very general issue.)

By design, Godot's rasterizer setups shaders for both 2D and 3D elements as they are needed during render. It creates different versions of each shader for any context it's used on, with different set of defines for every case.

This is sensible as long as it would be a waste of time and memory to precompile every shader for every use case. For instance, if a material in 3D is never used in the alpha pass, that variant won't ever get compiled. There are a number of combinations for both 2D and 3D materials.

The downside is that **the first frame of a scene just loaded with several different materials/shaders takes much more time because of the compilation of shaders, causing a noticebale hiccup**. And, as long as I can guess, as soon as any mesh or sprite with a not-yet-compiled shader enters the viewport it will happen again.

In my game I'm calling `VisualServer.draw()` on the main scene's `_ready()` to force compilation of at least the shaders needed for the first screen without affecting the timing, thus avoiding the hiccup.

Is there any reasonable implementation that could avoid that yet being more reliable?

I'm willing to implement it. I even started adding a method, `VisualServer.prepare_all_materials()`, but precompiling every combination is cumbersome and wasteful so I need a better approach.

Does anybody know how is this handled in other engines?

**Comment by reduz** [comment]
There is not much way around this in OpenGL, since you can't precompile the
shaders. Shader compilation will likely be more efficient in 3.0, but not a
lot can be done.

A solution can be to, in platforms that support it, extract the shader
binaries used, compress them and cache them in the user:// filesystem, as
long as the ARB_get_program_binary extension is present. Basically, we can
MD5 the shader text before compiling it, and do the lookup.

In a future, with stuff like Vulkan, this will be easier because we will be
able to cache the generated binaries on PC, then upload them to mobile.



On Tue, Oct 4, 2016 at 7:48 PM, Pedro J. Estébanez <notifications@github.com

**Comment by punto-** [comment]
On old mobile games we used to put all the 3D objects behind the loading
screen, or the instructions screen, etc, to force the compilation in the
first frame, then move everything away or move the camera to the actual
start of the level, etc.

**Comment by Sslaxx** [comment]
@punto- I'd do that sans loading screen because, well, I liked the way old arcade machines booted up.

**Comment by RandomShaper** [comment]
I guess those are sensible approaches. Closing issue.
