### ISSUE TITLE
"Advanced import settings" window lags and CPU usage spikes when generating physics for objects

### ISSUE THREAD

**Issue by JulianHeuser** [godotengine/godot#67149]
**Your Godot version:**
v4.0.beta2.official [f8745f2f7]

**System**
Linux Mint 21
CPU: Ryzen 3 2200G
GPU: RX 570

**Issue description:**
When importing a model, if you generate physics for objects, the interface quickly begins to stutter and CPU usage goes up. This happens every time you open the import dialogue for the model, until restarting godot.

On restart, it behaves normally, until modifying a physics property (toggling "generate physics," or changing the shape type). This makes me pretty sure this isn't just a performance issue - something is going wrong.

(In the below video there's no recording lag - all the lag/stutter is what I saw)

https://user-images.githubusercontent.com/25406449/194772621-59639e62-0f89-47b3-9177-8eb55c228458.mp4

Tested with .blend and.glb. It doesn't matter if I click  "close" or "reimport" to exit the window - the result is the same.

**Comment by ArshPanesar** [comment]
The lag/stutter issue seems to originate from `void SceneImportSettings::_update_view_gizmos()` in at line 418 in `scene_import_settings.cpp` file. The function repeatedly builds a `collider_view` for the mesh even if one already exists:
`if (generate_collider)`

The stutter goes away by adding a simple check - if `collider_view` already exists for the mesh, don't rebuild it:
`if (generate_collider && collider_view->get_mesh().is_null())`
However, the performance drop when generating physics initially for a mesh still exists so I'm not sure if this completely fixes the issue. I'll still make a PR so that the stutter after generating physics is fixed.

**Comment by lyuma** [comment]
As noted in https://github.com/godotengine/godot/pull/67269#issuecomment-1433608013 we believe the issue was already fixed by PR #71691 (part of 4.0 RC2)

If you still encounter lag in the advanced import menu, by all means reopen this issue with precise reproduction steps so we can investigate.
