### ISSUE TITLE
Vector3.BACK should be rename

### ISSUE THREAD

**Issue by MeBadDev** [godotengine/godot#67229]
### Godot version

v3.5.stable.official [991bb6ac7]

### System information

Windows 10

### Issue description

`Vector3.BACK` should be rename to `Vector3.BACKWARD`

### Steps to reproduce

1. Go to [this link](https://docs.godotengine.org/en/stable/classes/class_vector3.html#:~:text=BACK%20%3D%20Vector3(%200%2C%200%2C%201%20)%20%2D%2D%2D%20Back%20unit%20vector.%20Represents%20the%20local%20direction%20of%20back%2C%20and%20the%20global%20direction%20of%20south.)
2. You can see constant of front is Vector3.FORWARD, but constant of back is Vector3.BACK, which is confusing

**Comment by YuriSizov** [comment]
Renames are enhancements, and not bugs, so you need to open a formal proposal instead of a bug report. Please note the submission rules https://github.com/godotengine/godot-proposals

That said, we are no longer accepting renames, at least new ones. Godot 4 development is in the beta stage and this is a breaking change. You can still open a proposal, but it is unlikely to be implemented before the next major version, even if it is accepted.

I'm also pretty sure this has been discussed before, and wasn't accepted. See https://github.com/godotengine/godot/pull/50047, https://github.com/godotengine/godot/pull/52334, and the discussions they link.
