### ISSUE TITLE
Gradient sliders bug out when changing colors

### ISSUE THREAD

**Issue by mrjustaguy** [godotengine/godot#67235]
### Godot version

4.0 Beta 2

### System information

Windows 11

### Issue description

When trying to change color of gradients, the slider often keeps moving with the mouse even when the color picker is active, and keep moving even when mouse isn't held after the color picker has been closed.

### Steps to reproduce

Make a Gradient, try to pick colors, move mouse over the slider while the color picker is active, or after you've closed it, notice the bar is following the mouse, but you aren't holding the mouse button.

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
Seem to happen only when opening the color picker by double clicking. Does not happen in a single window mode (editor setting `interface/editor/single_window_mode = true`).

In action (only double clicked to open the color picker and then pressed <kbd>Esc</kbd> to close it, no more presses involved):
![gAuXORFRWj](https://user-images.githubusercontent.com/9283098/195072539-02e2a0e0-a991-4537-8369-276dc6762967.gif)

**Comment by AleCamara** [comment]
I can see the issue. Is the expected behaviour here to 1) create a gradient key on the position that was double-clicked, 2) open the colour picker, and 3) never allow the gradient key position to move on this process? If so I have a fix for this :)

Here's the potentially fixed behaviour in action:
![67235-PotentiallyFixedBehaviour](https://user-images.githubusercontent.com/1842070/201493865-64387f93-d689-4a6e-879e-066a735c0041.gif)

**Comment by kleonc** [comment]
> Is the expected behaviour here to 1) create a gradient key on the position that was double-clicked, 2) open the colour picker, and 3) never allow the gradient key position to move on this process?

Yes, yes, yes.

>If so I have a fix for this :)

Feel free to open a PR (no need to ask for permission). :slightly_smiling_face:
