### ISSUE TITLE
Custom shader uniform bool somehow has three states - Linux only

### ISSUE THREAD

**Issue by belzecue** [godotengine/godot#67240]
### Godot version

3.5.1.stable

### System information

Linux, Ubuntu 20.04, Intel graphics, NUC7PY

### Issue description

I am seeing worryingly different behavior of a simple custom shader between Linux and Windows.

NOTE: I tested this issue with Godot 3.5.1.stable on two different low-end Linux devices (Intel Compute Stick running MXLinux; Intel NUC 7PY running Ubuntu 20.04.5) and one high-end Windows10 gaming laptop with RTX3060.  The issue exhibited the same on BOTH the Linux devices, but the Windows10 laptop was unaffected and behaved as expected.

In the following video, the value of uniform bool TINT_ON is FALSE, and therefore I should be able to remove that bit of code without it affecting the shader.  I am simply removing what should be an inactive piece of code.

However, you will see that when I remove (comment out) the code, the texture colors change.

In my testing on Windows 10, the behavior is as expected: commenting out the code makes no difference because the code is inactive due to TINT_ON being FALSE.

Explaining the video...

- A 2D project with a quad and custom shader.
- The custom shader does two things controlled by two uniform bools: a tint function and a mask function, both of which alter the pixel color.
- In the default state, TINT is OFF and MASK is ON, so the texture colors are only affected by the mask function.
- I demonstrate the two toggles and their effect on the texture.  I then leave TINT OFF and MASK ON (i.e. the default state).
- I then COMMENT out the shader IF statement related to TINT, which currently has a value of false and therefore the statement is inactive, so removing it from the shader should have NO effect.
- Uh oh, commenting/removing it DID have an effect!  WTH?  The texture is now sort of pixelated.
- Next I reinstate the IF statement and replace the TINT uniform bool with true/false, which should be the same two (and only two) values the TINT uniform can hold.  When TRUE, it correctly shows the pinkish tinting.  When FALSE, it behaves the same as when I comment out the IF statement.  Both of these are expected outcomes.  AND YET THERE IS A THIRD STATE, the one we began with before altering anything, where MASK ON / TINT OFF gives a different texture color than MASK ON / TINT-replaced-with-FALSE.

I deleted my Godot editor_data/cache folder just to be sure this was not some local caching issue, but that made no difference, and in any case I reproduced this behavior on another Linux box that I use rarely and had not yet housed this code.  Again: this does not happen on my Windows 10 laptop.  There, commenting out the code does nothing; the texture colors do not change.

https://user-images.githubusercontent.com/1931303/195021365-cc509188-a396-41ae-8ba3-f94f77b2a7e6.mp4

### Steps to reproduce

Load up the repro project ON A LINUX DEVICE, follow along with the demo video, comment out the code, and see if removing the what-should-be-inactive statement has an effect on the texture colors.

> 	//if (tint_on) {
> 	//	COLOR.rgb = mix(COLOR.rgb, color_tint.rgb, color_tint.a);
> 	//}

### Minimal reproduction project

[repro.zip](https://github.com/godotengine/godot/files/9752088/repro.zip)

**Comment by clayjohn** [comment]
I took a look at your MRP and identified the root cause. You are relying on undefined behaviour in the ``mask_on`` branch. You create three variables: ``result_r``, ``result_g``, and ``result_b`` but you do not initialize them to any value, so they contain garbage data that can be anything. OpenGL implementations are allowed to do whatever they want in this case (they can default all floats to 0.0 if they want, or NaN, or to garbage data). In your case, running on the intel device, you are getting garbage data which differs depending on code generated by your GPU driver's GLSL compiler. The code works as expected if you change ``float result_r, result_g, result_b;`` to ``float result_r = 0.0, result_g = 0.0, result_b = 0.0;``

In general you will find that Intel devices enforce the OpenGL and GLSL specifications to the letter while Nvidia is a lot more relaxed about the specification and will deviate from the specification to make sure things appear to "just work" on NVidia devices (even if the code is not valid GLSL code). As a developer it is important for you to ensure that you don't rely on any undefined behaviour. Just because it works on your device doesn't mean it will work on all devices. Testing on both intel and Nvidia devices is a very good practice to identify such issues.

**Comment by belzecue** [comment]
Thank you so much, clayjohn! That makes perfect sense and works as expected now.

Today's lesson for me, which goes straight into my Godot notebook in bold letters is:

**ALWAYS INITIALIZE SHADER VARIABLES.**

And a secondary lesson: Always test on Intel, AMD, and NVidia devices.
