### ISSUE TITLE
an option to interrupt gdscript and open debugger when C++ error occurs ?

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#6735]
**Operating system or device - Godot version:**
2.x, 3.x

**Issue description** (what happened, and what was expected):

Maybe it could be handy if, when a C++ error is displayed into the console and into the debugger, the script was interrupted. (like if it was a breakpoint or a gdscript error).

For instance, when this kind of error happen many time into a loop :

```
ERROR: Image::get_pixel: Index p_x out of size (w).
   At: core\image.cpp:352
```

**Steps to reproduce:**

**Link to minimal example project** (optional but very welcome):

**Comment by kubecz3k** [comment]
It could be helpful to deal with those problem when they actually pops out, and not couple months later... :) But this should be definitely optional.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by kubecz3k** [comment]
I think the issue still makes sense.

**Comment by akien-mga** [comment]
See also #23865.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
