### ISSUE TITLE
LIGHT direction in light shaders isn't correct

### ISSUE THREAD

**Issue by rumbogs** [godotengine/godot#67356]
### Godot version

v4.0.beta.custom_build.56563ef09

### System information

MacOS, Vulkan API 1.1.211 - Using Vulkan Device #0: AMD - AMD Radeon Pro 560X

### Issue description

The light position doesn't seem to be calculated properly in world space.

Please see here:

https://user-images.githubusercontent.com/9051832/195652205-b12143b0-6237-4c63-816f-d07aa131b199.mp4

In the recording, the mesh has a shader material that simply displays the light position in world space as a DIFFUSE_LIGHT value. In my understanding, this should be the same color regardless of the camera position, since the LIGHT direction doesn't change. 

### Steps to reproduce

Attach a shader material to a mesh with the following:
```
shader_type spatial;

varying mat4 inv_matrix;

void vertex() {
        // Saved this in a varying to avoid another bug
	inv_matrix = INV_VIEW_MATRIX;
}

void light() {
	DIFFUSE_LIGHT = (inv_matrix * vec4(LIGHT, 1.0)).rgb;
}
```

Make sure there's a DirectionalLight3D node in the scene.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/9778676/test.zip)

**Comment by clayjohn** [comment]
This isn't a bug, ``LIGHT`` represents the view space _direction_ of the light not its view space position. To transform a normalized direction from view space to world space you should use ``(INV_VIEW_MATRIX * vec4(LIGHT, 0.0)).rgb`` (or better yet: ``mat3(inv_matrix) * LIGHT``). Note that the 4th component of the vector is a ``0`` and not a ``1``. The ``0`` is used because in a matrix multiplication the fourth channel is multiplied by the transform's origin representing a translation. In effect, the code you have written rotates the light's direction into world space and then it translates the vector by the ``INV_VIEW_MATRIX``'s origin which results in an incorrect vector.

**Comment by rumbogs** [comment]
Oh, my bad, thanks for the explanation!
