### ISSUE TITLE
GdScript 2.0: Using infer typed for typed Array is not working or supported

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67436]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I love the new typed Array 👍 

I'm current migrating my Plugin and improve the code by using the new features.

Typical i use  infer typed code style to define and assign values.
```
# a infer typed value a as int
var a := 1
# a infer typed value a as String
var b := "foo"
# a infer typed value a as Array with out inner type
var c := Arrary()
```

Now i want to use typed Arrays also as  infer typed to be consistent code style.

```
# replace
var c := Arrary()
# this is not working
var c := Arrary[int]()
```
This ends up in a compile error `Cannot call on an expression. Use ".call()" if it's a Callable.`
I tryed different syntax but it ends always in an error
```
var c := Arrary()[int]
var c := Arrary[int]
var c := [int]
```

I have to workaround by, but this looks like a different code style to initalize variables
```
# a infer typed value a as int
var a := 1
# a infer typed value a as String
var b := "foo"
# a typed value a as typed Array
var c :Arrary[int] = []
```

### Steps to reproduce

setup a new script and put into

```
func foo():
	var c := Arrary[int]()
```

**Comment by Cykyrios** [comment]
`Array()` is a function used to construct an empty array, you cannot specify the type here. If you want to have an `Array[int]`, you have to either provide initial values (`var a := [0, 1]` and such), or specify the type as you wrote: `var a: Array[int] = []` or `var a: Array[int] = Array()`. `var a := []` always infers the type as `Array` (untyped).

In the 3 lines with `var c`, the code tries to a) get the value at index `int` from the empty array returned by `Array()`, b) same but from array `Array` which is not valid, and c) declare an array that contains `int` as its first and only element. In all 3 cases, `int` is a reserved keyword and therefore invalid syntax.

**Comment by MikeSchulze** [comment]
@Cykyrios using `var a := [0, 1]`  will not help i want to have an inital empty typed array in infer typed notation
`var a := <typed array syntax>`

**Comment by Cykyrios** [comment]
As far as I know, this is not currently possible, as arrays can only infer the type of their elements if at least one element can be inferred. Alternatively, you would need to clear the array after having it inferred, which is bad practice. There may be a proposal for this already, or you can make one in the [Godot Proposals repository](https://github.com/godotengine/godot-proposals).

I personally believe things are fine the way they are, since inferring requires initializing the variable, and in this particular case, you choose not to (or at least, the contents of the array cannot be inferred). There are some other situations where explicitly specifying the type can be useful, for instance when getting a node of a given class, but declaring the variable with a parent class as its type.
Also, as far as code style consistence is concerned, is having `Array[int]` inferred from an empty array really useful, when you would need to explicitly write `int` anyway, be it before or after `=`?

**Comment by MikeSchulze** [comment]
ok i can live with this solution, not happy but ok

**Comment by Calinou** [comment]
Closing per @Cykyrios' comment.
