### ISSUE TITLE
Should I put the MIT license in my game created with godot?

### ISSUE THREAD

**Issue by hormoz1** [godotengine/godot#6745]
Hello.

I am not exactly sure if this is the right place to ask this question but let's ask:

Someone on this topic:
https://github.com/godotengine/godot/issues/1635
Said this:

"I'm not a lawyer either but here's the thing.. MIT license states "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software." and because there is no definition of "software" it can be misinterpreted. Software can be defined as a set of machine instructions (which is binary file) meaning you're legally obligated to put a MIT copyright somewhere in the executable file. So mentioning of godot is not required, but copyright notice must be included somehow (not necessarily has to be rendered to the screen). But to play it safe - just include it in the credits and be done with it."

Is this true if it isn't true why isn't it true can you explain about it?

And also in Godotengine.org it says:
"Godot is completely free and open source under the very permissive MIT license. No strings attached, no royalties, nothing. Your game is yours, down to the last line of engine code."

I think if that thing is true this thing in Godotengine.org isn't true because I think that thing in Godotengine.org also means you are not forced to put anything in/with your game but if that thing is true I think it means you are forced to put something in/with your game.

I also asked this question in the Q/A of godotengine.org too.

Thank you.

**Comment by Sslaxx** [comment]
https://www.tawesoft.co.uk/kb/article/mit-license-faq appears to be a reasonable summation of the MIT and what it means for you in terms of what you can do with it and what you have to do (with the obvious caveat that I am not a lawyer).

**Comment by OniLink** [comment]
Disclaimer: I am not a Laywer

In laws regarding software, I believe a game made with Godot would be considered a "derived work", and thus does not require the same license as Godot UNLESS Godot's license required something of "derived works". As the MIT license does not refer to "derived work", the MIT license is not forced upon your own game.

If not for the distinction between software and derived work, it could be possible to use that as a loophole to, say, force all software made on a computer using Microsoft Windows to use the Windows ToS, or on a computer using Linux to use GPL3, which would be completely insane.

**Comment by hormoz1** [comment]
Thank you for answering.
Oh I don't think godot forces your game to use the same license what I meant in the question was:
whether you are forced to put the license file in/with your game or not.(i think putting doesn't mean your game is licensed under that license)

**Comment by OniLink** [comment]
Disclaimer: I am not a Lawyer

My bad, I misread. The MIT license does not require that you credit the Godot authors in any way, and since you aren't distributing Godot itself, but rather something made with Godot, you don't need to include the licensing information for Godot. It is, however, generally good practice and considered polite to say something like "Made with Godot" in your games credits or in a splash screen as the game starts.

**Comment by hormoz1** [comment]
Thank you for answering.
But what about this:
Software can be defined as a set of machine instructions (which is binary file) meaning you're legally obligated to put a MIT copyright somewhere in the executable file.

**Comment by OniLink** [comment]
Disclaimer: I am not a Lawyer

The Godot Engine is a tool for making software. The software you create with Godot is NOT Godot itself, and so is not under Godot's license. When you distribute your software created with Godot, you are not distributing the Godot, merely software that was created with Godot. The MIT License only requires you include the MIT License if you distribute Godot itself. The MIT License does NOT require you include the MIT License if you are not distributing Godot itself.

**Comment by hormoz1** [comment]
But when you make a software with Godot I think you actually use some part of it when you export it.
(Some part of it is with your game I think)

**Comment by akien-mga** [comment]
> The Godot Engine is a tool for making software. The software you create with Godot is NOT Godot itself, and so is not under Godot's license. When you distribute your software created with Godot, you are not distributing Godot, merely software that was created with Godot

Actually you are effectively distributing Godot itself when you distribute a game. The game binary is the Godot runtime, so basically all of good but the editor tools. You obtain it by compiling the MIT licensed Godot code with the `tools=no` argument.

**Comment by quantum-entangler** [comment]
Yes, include a copy of the license with your game in say for an example a sub-folder named licenses if you wish(also a good place to include a copy of your own games eula), it's wording should make it clear to anyone reading it that it applies to something named godot and it will include the names of the primary contributors to godot, pretty simple.

**Comment by ScotFlux** [comment]
Well... Let's go official 👍 

![related to mit license - prestidigitator and godotengine](https://cloud.githubusercontent.com/assets/10663548/19218580/eef00a0a-8e27-11e6-8e07-4e41c628abcd.png)

MIT License is very cool, @hormoz1

**Comment by punto-** [comment]
I was talking about the logo etc in that case, but yeah you have to include
that license text somewhere, usually in your documentation or with your
other licences that nobody reads :p

**Comment by fluffrabbit** [comment]
This bugs me to no end, because copyright law is rather strict and I have always interpreted the MIT license as being less permissive than zlib. I have been researching this stuff for almost 9 years, ever since a Google Code project of mine was locked by an admin and I was lectured about open source software.

>Actually you are effectively distributing Godot itself when you distribute a game. The game binary is the Godot runtime, so basically all of good but the editor tools.

We have a winner. Every game has Godot's code in it.

>I was talking about the logo etc in that case, but yeah you have to include
that license text somewhere, usually in your documentation or with your
other licences that nobody reads :p

What about the [Apache-licensed code](https://github.com/godotengine/godot/blob/c05ff0577fd9cc39a6968e65743f7d7da711bfe2/platform/android/java/src/com/google/android/vending/expansion/downloader/impl/AndroidHttpClient.java) in Godot's source tree?

**Comment by quantum-entangler** [comment]
if you are publishing on android then perhaps yes, although how that is usually handled on android(where to put it?) I do not know.

**Comment by hormoz1** [comment]
So I think if this is true, "No strings attached, no royalties, nothing. Your game is yours, down to the last line of engine code." is wrong.

**Comment by hubbyist** [comment]
MIT Licence means that "You have a copy of the software that you can use and distribute as you like. Only restriction is that you can't remove the original copyright and license".

So you have to keep the license some where in your project to show the original authors of the software that you used or modified. But after that your copy is yours (your copy of engine code, etc) and every thing you made with it (your game, app, etc) as well.

Only cost is you must keep the original license in your project and make it easy to find, thus showing you are not the original author. You can remove every thing else if you want al long as you keep license in an easy to find place in code (in licenses folder ) or product (in credits like "powered by GodotEngine : Copyright (c) 2007-2016 Juan Linietsky, Ariel Manzur.").

Disclaimer : I am not a lawyer. :)

**Comment by punto-** [comment]
You don't have to make it easy to find, that sort of thing is usually
hidden somewhere in the documentation or similar, that's fine

**Comment by hubbyist** [comment]
I think in binary form if you are not distributing source code you have to put it in an easy to find place. But as the disclaimer says : I am not a lawyer. :)

**Comment by hubbyist** [comment]
A good summary on subject : https://www.quora.com/Whats-the-different-between-Apache-v2-0-and-MIT-license

**Comment by quantum-entangler** [comment]
There's also a site called tldrlegal with nice summaries of licenses: https://tldrlegal.com/license/mit-license

**Comment by SuperUserNameMan** [comment]
all these licenses are boring and confusing.
I think there should be an official FAQ or guide into the official Godot doc about when/where/how we are supposed to cite Godot license and copyright.

**Comment by fluffrabbit** [comment]
Such a document could potentially conflict with the letter of the legalese, so it could only serve as a guide lest it be interpreted as additional conditions added to the legalese. In many cases software is distributed as "beerware" wherein less-than-formal usage guidelines are given rather than a license. With Godot, this is not the case. It has the MIT license and the Android builds also have the Apache 2 license. Best not to give people contradictory legal information, which is easy to do.

But I would agree that some kind of document serving as a licensing guide would be helpful. Maybe it could include rough suggestions as to how to include the license text.

From what I can tell, a mention in the credits is not necessary, but the full text of the Godot license must be accessible if the player wants to see what licenses apply to the software. I believe iPods have a "legal" screen in one of the about menus that lists all kinds of software licenses. Something like that would be a good model, but of course it is not necessary if the license is shipped as a text document alongside the executable in a zip folder where people can see it. The situation changes in the case of APKs and certain app stores where the player would have to dig pretty deep to get at the license text since it would essentially be a hidden source file.

**Comment by punto-** [comment]
We should have a file somewhere with whatever text is required, from our
license and potentially the licenses of the 3rd party libraries we include,
and just tell people to put it somewhere in whatever they distribute, it
doesn't have to be obvious, it can be hidden somewhere in the installation
or documentation, etc. Maybe even embed it in the binary, that counts too.

**Comment by akien-mga** [comment]
@punto- That's the plan, but it takes time to put it up. The big refactoring I did to move most thirdparty code to a separate folder was partly motivated by the fact that we currently don't honor the licenses of some of the libraries we're using (we should mention in the editor itself that it uses FreeType, etc.). And what applies to the editor also applies to games (apart from the modules that are not enabled on templates, like squish).

I plan to work on this, but it takes time, and it was more pressing for me to work on actually moving the code so that it's easier to track down what are the licenses of thirdparty contents (and also to readd erroneously stripped LICENSE or COPYING files next to the thirdparty files we're distributing - some being mandatory (like the FTL license file), others being just there for clarity).

Once I'm done with this work, we could do two or three things:
- Bundle the licensing details in the binary (both editor and templates), so that `godot --license`` would output it when run in a terminal (not sufficient for embedded devices, so sadly it does not cover everything the users would have to care about when distributing their games - but on desktop it's a start).
- Have the exporter optionally (opt-out) export a `LICENSE.Godot.txt` file with the same details next to your binary and data.pck, so that it's ready to distribute for those who want to use this form.
- Alternatively or complementary to the above, we could have (as discussed already with @reduz) a new tab in the Export dialog that gives you all the licensing details: what text is mandatory to include (the very minimal, i.e. tuned down to the licenses that explicitly require it), what text is a nice-to-include (same as mandatory one + non-"mandatory" copyright and licenses, for those who care or want to be 100% they're doing things right), and suggestions about where to include such text.

**Comment by akien-mga** [comment]
Also, to anyone ready to blow the whistle about Godot not honoring the licenses of the thirdparty libraries it uses, be mindful that it's pretty common, even - yelp - in commercial engines. Last I checked Unity3D uses FreeType but does not honor the terms of its license.

So basically right now we're doing "good", as we use very permissive libraries and we don't try to usurp their authorship, even though we don't give attribution as well as we should. The next step would be to give the proper attribution and mention the relevant license snippets, so that we go from "good" to "excellent" licensing wise.

**Comment by clayjohn** [comment]
There is now an entire tutorial on this in the docs :)

http://docs.godotengine.org/en/latest/tutorials/legal/complying_with_licenses.html#requirements

**Comment by fluffrabbit** [comment]
IMHO this should have been the first feature in Godot 1.0.
