### ISSUE TITLE
Grid Map Hotkeys for "changing floors" in editor no longer work

### ISSUE THREAD

**Issue by Stealcase** [godotengine/godot#67497]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0 Beta 3

### System information

Windows 10

### Issue description

# Expected Behaviour
When editing a Grid Map, the E and Q keys are used to change the "floor" that the user is currently working on. (Marked in green in the image below)

## Actual behaviour
E and Q changes the transform mode of the 3D Editor. I believe it changes from Rotation, translation or scale. (marked in Red in the image below)

![image](https://user-images.githubusercontent.com/38126357/196045347-80a5fece-af96-4b59-80a0-84a18d54ab2e.png)

### Steps to reproduce

1. Create a scene, add a 3D mesh to the scene.
2. Save the scene as a Mesh Library through File>Export>MeshLibrary somewhere in your project.
3. Create a new Scene, add a GridMap Node.
4. Drag and drop the MeshLibrary from step 2 into the "MeshLibrary" slot in the GridMap inspector. 
5. Select the GridMap in the Scene Hierarchy. A Window should appear showing all the meshes in the MeshLibrary.
6. Select the mesh and start drawing the mesh in the scene. 
7. Try to Change the floor you are drawing on with Q and E. Instead of changing floors, it will switch between Transform/Rotation/Scale

### Minimal reproduction project
[GridMap Project_v2.zip](https://github.com/godotengine/godot/files/9841145/GridMap.Project_v2.zip)

**Comment by Stealcase** [comment]
@Anutrix 
Thanks for the heads-up.
I forgot to delete the shader cache so it was needlessly bloated.

**Comment by hoodlumj3** [comment]
Feedback: 
Can confirm this still happens in :-
Godot_v4.0-beta15_mono_win64
Godot_v4.0-beta15_mono_win64_console
Same steps as @Stealcase posted above to replicate issue.

**Comment by tristanpemble** [comment]
`W` will not clear cursor rotation either, and instead switches transform mode to move mode (Godot 4.1)

**Comment by rainerdeyke** [comment]
This is a serious bug because it makes it impractical to make 3D selections in the GridMap editor.  (It's kind of possible with the zxc keys, but inconvenient and unreliable.)  I suspect that it is caused by another UI element snatching up the input events before the GridMap editor gets it.  A workaround would be to change the key assignments to avoid the conflict; a proper fix would be to change the UI input handling order such that the GridMap editor has top priority.

**Comment by intervolver** [comment]
this is happening as described in version 4.1.1 as well

**Comment by elvisish** [comment]
Why is this closed? W key doesn't work in 4.1.1?

**Comment by krytoou** [comment]
still not working in Godot 4.1.3...

**Comment by akien-mga** [comment]
@krytoou As the milestone says, this was fixed in 4.2. So it's expected that it doesn't work in 4.1.3.

Please keep ironical rants out of your GitHub comments, as per our [Code of Conduct](https://godotengine.org/code-of-conduct/). This is not the place to voice frustrations at people who provide you an engine for free.

**Comment by krytoou** [comment]
> this was fixed in 4.2.

that's just an shortcuts, lol! why it is not fixed in all the versions?

**Comment by akien-mga** [comment]
> why it is not fixed in all the versions?

Because the fix was relatively complex (and introduced two bugs, which had to be fixed later on), and was therefore not deemed safe enough to backport to the stable branch at the time. We're carefully around backporting changes which could introduce new bugs in released versions, and with a 4/5-month release cycle between minor releases, it's better to keep any risky change for the next milestone.

4.2 is released, you can use it. If you can't use it due to new bugs, this is a demonstration of what I just described. Bug fixes can be risky and introduce regressions.
