### ISSUE TITLE
GDScript 2.0: `get_method_list()` and `class_get_method_list()` return an incorrect function description

### ISSUE THREAD

**Issue by MikeSchulze** [godotengine/godot#67544]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

I use `get_method_list` and `class_get_method_list` to create a function descriptor to create a spy or mock for a class and I strictly rely on the information provided being correct and complete.

I run into this issue when migrating my plugin GdUnit3 to Godot4 and my spy tests failing by creating invalid functions.
For example the function description `get_script` is broken in Godot4, the return type is TYPE_NIL but should be `Variant` 

There is no TYPE definiton for `Variant` sounds like TYPE_VARIANT is missing.

```
{
   "name":"get_script",
   "args":[
      
   ],
   "default_args":[
      
   ],
   "flags":5,
   "id":12,
   "return":{
      "name":"",
      "class_name":"&""",
      "type":0,
      "hint":0,
      "hint_string":"",
      "usage":262150
   }
}
```

### Steps to reproduce

- put the code in your script `testScene.gd` and execute

```
class_name TestScene
extends Node

func _ready():
	test_extract_functions()

func test_extract_functions() -> void:
	var script :GDScript = load("res://testScene.gd")
	var script_functions :Array = script.get_method_list()
	for function in script_functions:
		if function["name"] == "get_script":
			prints(script.resource_path.get_file(), function)
	var base_clazz :String = script.get_instance_base_type()
	if ClassDB.class_get_method_list(base_clazz):
		var clazz_functions := ClassDB.class_get_method_list(base_clazz)
		for function in clazz_functions:
			if function["name"] == "get_script":
				prints(base_clazz, function)
```
Output:
Godot 4 (return type is 0)
```
testScene.gd { "name": "get_script", "args": [], "default_args": [], "flags": 5, "id": 12, "return": { "name": "", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 262150 } }
Node { "name": "get_script", "args": [], "default_args": [], "flags": 5, "id": 12, "return": { "name": "", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 262150 } }
```
Godot 3 (return type is 17)
```
testScene.gd {args:[], default_args:[], flags:9, id:12, name:get_script, return:{class_name:Reference, hint:19, hint_string:Reference, name:, type:17, usage:7}}
Control {args:[], default_args:[], flags:9, id:12, name:get_script, return:{class_name:Reference, hint:19, hint_string:Reference, name:, type:17, usage:7}}

```

**Comment by Lewin225** [comment]
Godot version(s)
v4.0.beta1.official.20d667284
v4.0.beta6.official.7f8ecffa5

System information
Windows 10 LTSC / SteamOS 3 (deck)


Just ran into this bug and it's causing me some pain, I found another interesting quirk with this where it does sometimes return the correct signature for the function, but also returns a duplicate entry with the above issue. I can't work out what causes it to return the correct result

Example - Define two functions and call `get_method_list` on them

```
extends Label

# List of functions to inspect with get_method_list()
var methods_to_inspect = ["set_text", "set_aim"]

func set_aim(new_aim:Vector3=Vector3(0,0,0)):
	text = str(new_aim)

func set_text(new_text:String):
	text = new_text


func _ready():
	var i:int = 0
	for method in self.get_method_list():
		if method.name in methods_to_inspect:
			i+=1
			print()
			print("(",str(i),")", " Function introspection for function ", method.name)
			print("===================")
			for x in method:
				print(x," -> ", method[x])
```

Outputs this to the console, The first entry is correct, note both the entries with the issue have `id=0`

```
(1) Function introspection for function set_text
===================
name -> set_text
args -> [{"name":"text", "class_name":&"", "type":4, "hint":0, "hint_string":"", "usage":6}]
default_args -> []
flags -> 1
id -> 3742
return -> {"name":"", "class_name":&"", "type":0, "hint":0, "hint_string":"", "usage":6}

(2) Function introspection for function set_aim
===================
name -> set_aim
args -> [{"name":"arg0", "class_name":&"", "type":0, "hint":0, "hint_string":"", "usage":6}]
default_args -> []
flags -> 1
id -> 0
return -> {"name":"", "class_name":&"", "type":0, "hint":0, "hint_string":"", "usage":6}

(3) Function introspection for function set_text
===================
name -> set_text
args -> [{"name":"arg0", "class_name":&"", "type":0, "hint":0, "hint_string":"", "usage":6}]
default_args -> []
flags -> 1
id -> 0
return -> {"name":"", "class_name":&"", "type":0, "hint":0, "hint_string":"", "usage":6}
```

**Comment by YuriSizov** [comment]
Is this still reproduceable with the latest beta?

**Comment by Lewin225** [comment]
Just tested this on v4.0.beta12.official.3c9bf4bc2 (Web Editor), Still seems to have this issue

```gdscript
# Test method for get_method_list with a range of parameter types

#                   Array of custom type,     Custom Type,    typed int,       typed bool with default,       typed string with default,           untyped default, 
func can_xyz_summon(materials:Array[Monster], target:Monster, playerphase:int, allow_xyz_summon:bool = false, successmsg:String = "Xyz summoned!", failmsg=" Summon failed! :( ") -> bool:
	# Function logic
	return true


for method in get_method_list():
		if method.name == "can_xyz_summon":
			print(method)
 ```

```gdscript
{
"name": "can_xyz_summon", 
"args": [
{ "name": "arg0", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }, 
{ "name": "arg1", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }, 
{ "name": "arg2", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }, 
{ "name": "arg3", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }, 
{ "name": "arg4", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }, 
{ "name": "arg5", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 }
], 

"default_args": [], 
"flags": 1, 
"id": 0, 

"return": { "name": "", "class_name": &"", "type": 0, "hint": 0, "hint_string": "", "usage": 6 } }
 ```

**Comment by YuriSizov** [comment]
cc @anvilfolk @adamscott @vnen @vonagam

**Comment by vnen** [comment]
It's as @vonagam says, you need check the usage flag. What changed between 3.x and 4.0 is the return type of `get_script` (before it was `Reference`, now it's `Variant`).

The bug here is that the type information seems not to be set for script methods. For what I tested this is also a problem in 3.x so it isn't a regression.

**Comment by MikeSchulze** [comment]
instead of an additional flag we should have an equivalent type
`TYPE_VARIANT`

**Comment by vnen** [comment]
`TYPE_VARIANT` wouldn't be a valid Variant type though, so we can't really add to the enum. We could potentially hijack `TYPE_MAX` to be the "Variant" type, though it might be awkward in some cases (even if we rename it, I bet people would try to use `typeof(x) == TYPE_VARIANT` and wonder why it doesn't work).

But this is proposal material, since it requires changing a system that has been in place since forever. My point here is that there's no regression.

**Comment by MikeSchulze** [comment]
For me it is a regression. Variant type was not used in v3,x as return type and is now general used.
Godot 3.x `Reference get_script() const`
Godot 4.x `Variant get_script() const`




> `TYPE_VARIANT` wouldn't be a valid Variant type though, so we can't really add to the enum.

Sorry no.
The descriptor says type == 0  (TYPE_NIL) from the documentation  `Variable ist null.`
If you take it exactly TYPE_NIL is not a valid type either.

TYPE_VARIANT is a valid typ
![image](https://user-images.githubusercontent.com/347037/213123348-b7ba905c-585f-4414-b66f-4edc188f0861.png)

The same problem applies to the void type, there is no corresponding enum here either.

So please add the missing enums
`TYPE_VARIANT`
`TYPE_VOID`

**Comment by vnen** [comment]
> For me it is a regression. Variant type was not used in v3,x as return type and is now used.
> Godot 3.x `Reference get_script() const`
> Godot 4.x `Variant get_script() const`

It's not a regression since it's not something that used to work and now does not. It works the same as before. This is simply a change in the API: `get_script()` used to return `Reference` now it returns `Variant`. There are many other cases where the return value of a function changed between 3.x and 4.0 since there has been a lot of API changes.

This in particular is like this for a technicality: it should be `Script` but since `Script` inherits `Object` it cannot be used in `Object` itself. It could be `Reference` before (which is more specific) only because of how the internals worked, but that have changed in 4.0.

> Variant type was not used in v3,x as return type and is now used.

That is true only for script methods. Engine methods already had Variant return types (e.g. `bytes2var()`). Those also used `TYPE_NIL` with `PROPERTY_USAGE_NIL_IS_VARIANT` set. The problem is that `PROPERTY_USAGE_NIL_IS_VARIANT` constant isn't exposed to scripting in 3.x (not sure why) and that's probably why this detail was missed.

> The descriptor says type == 0 (TYPE_NIL) from the documentation `Variable ist null.`
> If you take it exactly TYPE_NIL is not a valid type either.

Yes, it is. `print(typeof(null) == TYPE_NIL)` prints `true`. It's a unit type (there's only one valid value for the type) but it's still a valid type.

OTOH `TYPE_VOID` is not a valid type because `void` means "nothing" so there is no valid value of this type (in practice the function returns `null` which is of `TYPE_NIL` so it's correct as it is now).

A variable (or function return) is only "Variant" in the sense that they can be of any type and also change types at runtime. It's a compile-time detail. The actual value stored in the variable (or returned by the function) **must** have a specific type from the enum). Those `TYPE_*` values are used in the documentation and reflection for convenience, but they are actually meant to reflect the runtime type of values, so `TYPE_VARIANT` does not make sense since it will never happen.

----

Again, this is how the system works and how it always worked. If want this to change, you need to submit [a proposal](https://github.com/godotengine/godot-proposals).

**Comment by MikeSchulze** [comment]
Thanks for the detailed explanation, yes, that makes sense.
So i have to check in addition the flag is set to PROPERTY_USAGE_NIL_IS_VARIANT 
Thanks

**Comment by MikeSchulze** [comment]
I use now the flag `PROPERTY_USAGE_NIL_IS_VARIANT` to detect the return value us an `Variant` and fixes my issue.
@vnen This ticket can be closed, if you want

**Comment by Lewin225** [comment]
Can we please keep this open since `get_method_list()` still doesn't return the correct function description on script methods. 

I'm trying to provide a Timeline for calling functions but these are user created and loaded as from pck at runtime

**Comment by anvilfolk** [comment]
Is this needed for relase, debug or editor builds?

From a very quick look at the relevant code, it seems like the information is obtained from `GDScriptInstance::get_method_list()`, which contains reference to `GDScriptFunction`, and at least some of the info seems locked behind debug or editor flags, e.g.
```#ifdef TOOLS_ENABLED
	Vector<StringName> arg_names;
	Vector<Variant> default_arg_values;
#endif
```

**Comment by Lewin225** [comment]
I'm not sure to be honest, I'm loading pck files generated by users as third party plugins (Think VST's in an audio editor), once loaded users can animate the properties of the plugin using a custom timeline (Using `get_property_list` to provide a list of things to add to the timeline ). 

I was hoping to allow function calls to be animated in the same way but that's when I discovered `get_method_list` doesn't return anything. So I can't prompt to user for what they'd like to animate, nor find the default values for the function.

I would suggest having `get_method_list` work in any build `get_property_list` does, since they have the same purpose

@anvilfolk Currently `get_method_list` doesn't work in editor builds either, so I'm not sure what's causing the empty response

**Comment by anvilfolk** [comment]
Right, there's two problems right now!

1. The information that is available in editor builds isn't used to populate `get_method_list()`
2. The information isn't available outside of editor builds

The general worry about adding things to release builds is memory usage. If we implement this for release builds, then every method ever declared would start storing its argument names in memory, which might be mildly significant for larger codebases :/

I do find your argument that `get_method_list()` serves the same function as `get_property_list()` (which works) pretty compelling though. I wonder whether this should go straight to implementation or whether it's worth opening a proposal to start a discussion about it?

**Comment by dalexeev** [comment]
See:

* #33624
* #50425
