### ISSUE TITLE
Godot 4, C#: Missing Vector3 copy constructor

### ISSUE THREAD

**Issue by wp2000x** [godotengine/godot#67573]
### Godot version

4.0.beta3.mono

### System information

Windows 10

### Issue description

Godot 4.0 is missing a Vector3 constructor, that was there in previous versions like 3.5.

### Steps to reproduce

![const](https://user-images.githubusercontent.com/70962730/196430667-8f027e8b-c360-49b5-ad8e-10a01fc1ea19.PNG)

Example usage
`Vector3 playerOrigin = new Vector3(_objectNode.GlobalTransform.origin);`

**Comment by wp2000x** [comment]
@Chaosus I just noticed i had such a "copy constructor" usage a few times in my project, and the project upgrader didn't changed it.

**Comment by AndreSacilotto** [comment]
They were removed, not only from vector3, but from all vectors.  And it is a good thing. Why?
```csharp
vec2 a;
vec2 b = a;
b.x = 2;
```
The result is a={0, 0} and b={2, 0}, structs are value types so any assigment operations do with them creates a copy, so having a construtor that makes a copy is only usefull in very rare cases. So it was generating more harm than good.

But there is a easy workround simply use a extension method:
```csharp
public static Vector2 Copy(this Vector2 vec) => new(vec.x, vec.y);
public static Vector3 Copy(this Vector3 vec) => new(vec.x, vec.y, vec.z);
```

**Comment by raulsntos** [comment]
As explained in https://github.com/godotengine/godot/issues/67573#issuecomment-1283100729, copy constructors were removed intentionally in https://github.com/godotengine/godot/pull/64727 because they are not necessary since structs are already passed by copy so you can just assign them to another variable and they'll be copied, no need for a extension method either.

```csharp
Vector3 playerOrigin = _objectNode.GlobalTransform.Origin; // This already copies the Origin vector
```

With C# 10 the [`with` expression](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/with-expression) also allows you to create a copy but modifying the value of some members:

```csharp
Vector3 myVector = _objectNode.GlobalTransform.Origin with { X = 42 }; // Copies Y and Z; X is set to 42
```

---

About the project upgrader, keep in mind it is quite limited because AFAIK it can only use RegEx and not everything can be upgraded since there's a risk it will change things it shouldn't when there's ambiguity so right now there's a lot of cases where the project upgrader won't help and you're expected to fix the project manually afterwards.
