### ISSUE TITLE
JSON can not be loaded with ResourceLoader::load but the file can be correctly parsed

### ISSUE THREAD

**Issue by PucklaJ** [godotengine/godot#67630]
### Godot version

4.0 beta3

### System information

Garuda Linux

### Issue description

There is a dedicated `ResourceFormatLoader` for JSON, but this loader can not load JSON files because the JSON class is not a `Resource`:
https://github.com/godotengine/godot/blob/61051a44ccacbe447f14538b5bb4b68a62fc896f/core/io/json.cpp#L582-L609

This method can correctly load and parse a json file, but when it gets returned, the `Ref<Resource>` becomes null, because it can not be converted into a `Resource`. This is because of this:
https://github.com/godotengine/godot/blob/61051a44ccacbe447f14538b5bb4b68a62fc896f/core/io/json.h#L39-L40

`JSON` is derived from `RefCounted`, but not from `Resource`. This seems to be somewhat indentional, but why is there a specific `ResourceFormatLoader` if it will never be able to load it?

I tried to change the base class of `JSON` to `Resource` and the `ResourceFormatLoader` can load it, but just changing the base class will probably not be enough and lead to other bugs. I just wanted to open this issue to point out that something needs to be done to fix this.

Related: #66820

### Steps to reproduce

1. Create a new project
2. Create a JSON file
3. There will probably already be a lot of errors, because the editor tries to load the file.
4. Load it with `ResourceLoader.load`.
5. See that the returned `Resource` is null, but the error is `OK`.

**Comment by pfertyk** [comment]
The problem (as noticed by @PucklaMotzer09 ) is that currently the inheritance tree looks like this:

```
Object
└── RefCounted
    ├── Resource
    └── JSON
```

This means that `JSON` cannot be loaded using `ResourceLoader`, because it's not actually a `Resource`.

One solution would be to make `JSON` a `Resource`, as initially suggested by @PucklaMotzer09 . Possibly we would have to move several types around, like `FileAccess`, which seems to be similar (also a file, but without a specific format).

Another solution is to make the `ResourceLoader.load` method return `Ref<RefCounted>`, which also seems like a huge change. Probably `ResourceLoader` would have to be renamed to `RefCountedLoader` :) 

For now I'd like to submit a PR that makes `JSON` a `Resource`, and if we choose a different direction, please let me know and I'll amend it ;)

**Comment by akien-mga** [comment]
Fixed by #71390.
