### ISSUE TITLE
Adding a "end" keyword at the end of func / loop/ if

### ISSUE THREAD

**Issue by niokasgami** [godotengine/godot#6770]
Hi I'm Nio Kasgami,

I have to say I'm happy on how you guys made a such nice OOP languages for the engine 
Easy to grasp the concept, yet powerful for doing what I want.

Although, this would be maybe just a taste but when I do if or function I'm used to having a closure symbol for show that my method or condition stop here. (example "{}" from standart C like languages or "end" from ruby/ lua).

This not like super problematic but I'm used to see them and find them more clean.

Could it be possible to add the **optional** possibility to add a end keyword to func block and condition, loop? 

thanks for your further answer!

**Comment by akien-mga** [comment]
That would be very non-idiomatic, you don't have such end statements in Python either. In GDScript, code blocks are defined by their indentation. A change in indentation means either the start of a new code block, or the end of the previous one.

**Comment by vnen** [comment]
You can end all your blocks with `pass` if you want.

**Comment by niokasgami** [comment]
@akien-mga as I said in begin I was just confused I'm used to language who define the end of their block with a specific keyword Or obviously a bracket
as I said this not make the language bad I'm just the type to tend to make mistakes  from lacks of concentration lol.

@vnen oh I didn't know thanks!

**Comment by bojidar-bg** [comment]
@niokasgami BTW, some people use `#{` and `#}` (both comments) to delimit code. E.g.:
```gd
if something == true: #{
    do(stuff)
    stuff_done += 1
    for i in range(stuff_done): #{
        toggle_light_switch(i)
    #}
#}
```

**Comment by SuperUserNameMan** [comment]
I'm among the people who use ``#{`` and ``#}``, but for more clarity it can be handy to use ``#endif```, ``#wend``, ``#next``, ``#endfunc`` etc ....

**Comment by akien-mga** [comment]
Honestly, it's mostly a matter of getting used to it. Use GDScript without guards for two weeks and you'll no longer be bothered by the lack of guards.

**Comment by niokasgami** [comment]
haha I see t hanks yes your advise was helpful! 

I'm happy to find a language who was easy to use and yet dynamic.

**Comment by cyb3rkun** [comment]
Hay, 

I I'd like to advocate for adding an end keyword as well.

conceptually it would function the same as pass. the reason I don't like to use pass is because it's confusing.

the reason I'd like an end keyword is for auto-indentation.

I use neovim for writing my gdscript and pretty much everything else.

however the lack of a closing "token" makes it hard for autoindentation to work properly.

when I want to move outside an if_statement then neovim auto-indents the new line to the same as the content of the if statement.

and if there's nested if statements (an issue I rarely have, but still happens from time to time.

it will autoindent the next line to the same as the deepest if statement since there's no closing "token" it assumes you're still working inside the if statement.

using pass can fix this, and using the above reccomended 
`#{ 
#}`
would fix this issue but it's not ideal and looks messy.

I imagine that 'end' could just be an "alias" for pass.

It'd literally just be for better auto-indenting.

is there any way this could be added to gdscript?

**Comment by cyb3rkun** [comment]
one more thing I'd like to add that would make the end keyword different from the pass

pass is used like this:

```gdscript

func foo(x: int) -> void:
	if x < 5:
		print("x < 5")
		pass
	else:
		print("x > 5")
		pass
	pass

```

I imagine end would work more like in lua:
```gdscript

func foo(x: int) -> void:
	if x < 5:
		print("x < 5")
	end
	else:
		print("x > 5")
	end
end

```


where the indentation of end matches the previous block and it's not "inside" of the function or if statement.

but this would still be just syntactic sugar, and optional.

I don't think it should be an enforcable rule in the language just an optional feature to use for those who like it.

this could potentially improve auto-indenting in a lot of cases where it's currently a bother

**Comment by niokasgami** [comment]
Ruby also has an concept of end for delimiting  a function or method.

it make it more clearer syntax wise. I do understand it can be more to type however. Although by spirit an gdscript function / syntax is fairly similar to ruby in spirit.

an example of ruby : 
```ruby
def hello_world
  puts "Hello, World!"
end
```

**Comment by bojidar-bg** [comment]
It's cool to see discussion on this issue! However, these days, feature requests like it would be best handled over at the https://github.com/godotengine/godot-proposals repository — I can't find a matching issue there, but feel free to search as well, and open a new one for this proposal there (:

**Comment by cyb3rkun** [comment]
> Ruby also has an concept of end for delimiting a function or method.
> 
> it make it more clearer syntax wise. I do understand it can be more to type however. Although by spirit an gdscript function / syntax is fairly similar to ruby in spirit.
> 
> an example of ruby :
> 
> def hello_world
>   puts "Hello, World!"
> end

to me personally it's not strictly about readibility or clear syntax but more about making auto indentation better, Especially in external editors (neovim btw)

at the same time I recognize that it's not a feature everyone would want. and some might even be completely apposed to the idea (although I don't know why that would be)

but that's why I recommend making it an optional syntactic sugar. 
a feature that's there for those who would like it but not enforced so those who don't like aren't forced to use it.
same as the pass keyword, it's placement would just differ, 
instead of being inside a function block (or if statement) or any other indented block it would denote the end and therefore be at the same level of indentation as the first line of that block.

as I described in my previous post.

**Comment by cyb3rkun** [comment]
@bojidar-bg 
> It's cool to see discussion on this issue! However, these days, feature requests like it would be best handled over at the https://github.com/godotengine/godot-proposals repository — I can't find a matching issue there, but feel free to search as well, and open a new one for this proposal there (:

I've done as you have suggested:
https://github.com/godotengine/godot-proposals/issues/12494

please feel free to advocate and voice your support for the issue above if you so wish
