### ISSUE TITLE
GPUParticles3D's View Depth draw order breaks when particle Amount is beyond certain threshold

### ISSUE THREAD

**Issue by PZerua** [godotengine/godot#67717]
### Godot version

Godot 4 Beta 3

### System information

Windows 11, GTX 970

### Issue description

When sorting the particles in View Depth order, I realised that particle rendering breaks when the amount is bigger than 7327. I can only see one particle with slightly distorted vertices. Performance is the same or worst, so probably all the particles are in the same location.

### Steps to reproduce

Create GPUParticles3D node, attach a CubeMesh for instance.
Set a ParticleProcessMaterial and a Sphere emission shape with radius 10, so the problem is easier to spot.
Set the amount to 7327.
Increase amount to 7328 and see how it breaks.

### Minimal reproduction project

[particles_bug.zip](https://github.com/godotengine/godot/files/9840068/particles_bug.zip)

Run the project and do left click to increase one particle (and break it), right click to decrease one particle.

**Comment by and-rad** [comment]
Not exactly duplicate, but definitely related to #55511

**Comment by clayjohn** [comment]
Debugging further, the issue comes from this dispatch in ``particles_set_view_axis()``:
https://github.com/godotengine/godot/blob/2b505b74b9b0a7005586ecaa9aa1236e86b18437/servers/rendering/renderer_rd/storage_rd/particles_storage.cpp#L1223-L1238

So this and https://github.com/godotengine/godot/issues/55511 are indeed the same bug
