### ISSUE TITLE
ScriptEditor shortcuts only work when focused on code editor

### ISSUE THREAD

**Issue by ClarkThyLord** [godotengine/godot#67743]
### Godot version

Godot 4.0 beta 3

### System information

Windows 10

### Issue description

In Godot 4 beta 3 it's become impossible to use ScriptEditor shortcuts without having to focus on the code editor first.

In Godot 3 we're able to use the `find` shortcut while focused on the code editor, and even when focused on the `find` input we're still able to use the `find and replace` shortcut; as well as when focused on the filter methods input we're able to use ScriptEditor shortcuts, as seen below:
https://user-images.githubusercontent.com/17155529/197325485-0fc23954-a10d-46b2-b7fb-b9424fe6381b.mp4

However, now in Godot 4 beta 3, we can still use the `find` shortcut while focused on the code editor, however once focused on the find input I'm not able to use anymore ScriptEditor shortcuts, nor when focused on any other thing other than the code editor. This means if I want to switch between `find` and `find and replace` with shortcuts I'd have to focus on the code editor again to be able to use them, as seen below:
https://user-images.githubusercontent.com/17155529/197325476-cb8b4034-0221-4aa2-b318-c10d6183a4c6.mp4

### Steps to reproduce

- Open Godot Engine
- Open any editable file with the ScriptEditor
- Focus on text editor
- Use any ScriptEditor shortcut
- Shortcut works
- Focus on anything else than the text editor
- Use any ScriptEditor shortcut
- Shortcut won't work

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
That's because many shortcuts are context sensitive and the previous behavior made some of them conflict and some were outright unusable or caused bugs.

**Comment by ClarkThyLord** [comment]
I see, so the shortcuts were redesigned with this in mind?

If so, I do feel like this has reduced the productivity and work flow somewhat as I have to constantly be focusing on the code editor to use shortcuts, as opposed to before; but that's just my 2 cents.

**Comment by KoBeWi** [comment]
Find and replace bar is part of the script editor, so script editor shortcuts should be available when it's focused.

**Comment by EricEzaM** [comment]
The structure of the UI here is kind of weird. The `FindReplaceBar` is owned by `SciptEditor`, and is injected into each `ScriptEditorBase` for usage. However, the `ScriptEditorBase` owns it's own `Edit` menu, and when each `ScriptEditorBase` is activated, the `ScriptEditor` get's it's edit menu and adds it to the main menu toolbar hbox container. What this means is that the `FindReplaceBar` is never actually a child of the node which own the `Edit` menu, the `SciptEditorBase`. 

So when you set the shortcut context of the edit menu to `this` when it is created (in the ScriptTextEditor`), it will never have menu items triggered when `FindReplaceBar` is focused because `FindReplaceBar` is never a child of the `ScriptTextEditor`.
