### ISSUE TITLE
SDFGI does not updateSoftbody shadow when softbody moves

### ISSUE THREAD

**Issue by Mikeysax** [godotengine/godot#67816]
### Godot version

4.0beta3

### System information

PopOS 22.04, 5.19.0-76051900-generic kernel, Ryzen 6800h, Radeon 6700m, amdgpu, Vulkan

### Issue description

In the screenshot, you can see the shadow is still in the original location when the scene started, on the water:

![image](https://user-images.githubusercontent.com/15805689/197407105-c49c9519-3042-4e42-aeff-3722de7895b3.png)

versus what it looks like when the character is not moved:

![image](https://user-images.githubusercontent.com/15805689/197407245-32397b6e-f101-4e50-a314-8d565bbb79e5.png)

This only happens with the softbody in the scene, which leaves a dark spot.

It's also not updating in the editor:

![image](https://user-images.githubusercontent.com/15805689/197407545-34b3f637-f37f-4ff1-9c70-ca59f99877f2.png)

### Steps to reproduce

Enable sdfgi with softbody in the scene. It does not update it's shadow when moved.

**Comment by clayjohn** [comment]
Only static geometry contributes to SDFGI. Which is why you have to set the GI mode to "Static" in order for the geometry to contribute to SDFGI. 

This is explained in the [``GIMode``](https://docs.godotengine.org/en/latest/classes/class_geometryinstance3d.html#enum-geometryinstance3d-gimode) documentation and a longer tutorial on SDFGI is coming soon in https://github.com/godotengine/godot-docs/pull/6216
