### ISSUE TITLE
Shader Memory leak

### ISSUE THREAD

**Issue by alazifk** [godotengine/godot#67885]
### Godot version

4.0 Beta3

### System information

Windows 10, Vulkan mobile

### Issue description

When using a shader with `render_mode wireframe;` memory is leaked. Other render modes seem fine.

### Steps to reproduce

Create a camera and a mesh instance.
Apply the following shader to the mesh.
```
shader_type spatial;
render_mode wireframe;
```
Now memory usage should increase about 1 MB every few seconds when running the scene.

**Comment by bitsawer** [comment]
Thanks for the report! This should have been fixed by https://github.com/godotengine/godot/pull/78200 in Godot 4.1, so closing this as completed. Looks like we did close the duplicate issue https://github.com/godotengine/godot/issues/76237 but missed this one. Feel free to comment here or re-open the issue if the problem still exists.
