### ISSUE TITLE
Visible LOD artifacts in Basketball

### ISSUE THREAD

**Issue by lyuma** [godotengine/godot#67891]
### Godot version

4.0beta3 (also exists on 4.0alpha17, so not a new issue)

### System information

Windows 10, Nvidia

### Issue description

LODs on this basketball causes visible artifacts such as the black line disappearing.

View showing no artifacts when zoomed in:
![close-up of basketball](https://user-images.githubusercontent.com/39946030/197932072-0a76efd5-c1d7-42e1-8284-29b4531eee1a.png)

View showing LOD artifacts when zoomed out:
![Display Normal, basketball with artifacts](https://user-images.githubusercontent.com/39946030/197932129-332b5e37-df1b-4c83-87fe-7802ebda2b0c.png)

View showing artifacts are gone when LODs are disabled.
![Display Disable Mesh LOD, distant basketball with no artifacts](https://user-images.githubusercontent.com/39946030/197932160-f401f2da-8e32-4954-9ddc-51b95753039d.png)

Closeup view of the artifacts, made by @fire :
![Closeup of LOD artifacts](https://cdn.discordapp.com/attachments/471742248468480011/1034681967079342100/editor_screenshot_2022-10-25T211619.png)

(unrelated to this issue, but this model's texture also has visible aliasing artifacts due to .glb, but that's a different bug. These texture artifacts do not happen if converted to .gltf + .jpg. please ignore texture artifacts for the purpose of this issue)

### Steps to reproduce

1. Import the zipped .glb below into a project.
2. Right click the .glb and choose New Inherited Scene
3. Leave the editor in the default orientation and zoom out.
4. You should see some black lines flicker or disappear

### Minimal reproduction project

[basketball.zip](https://github.com/godotengine/godot/files/9865899/basketball.zip)

**Comment by fire** [comment]
Changing the lod bias to be 3 seems to make the distance when the lod level triggers to be unoticable. 
![Uploading Screenshot 2022-10-25 211747.png…]()

**Comment by lyuma** [comment]
Is that a change that can be applied engine-wide? Is this fix of multiplying LOD bias by 3 correct?

**Comment by fire** [comment]
The constant is tuned here https://github.com/godotengine/godot/blob/58ca3031419cacb35c530cebe68e87a4c27dde06/scene/resources/importer_mesh.cpp#L455-L458

**Comment by JFonS** [comment]
I took a look at the issue, and #68006 is definitely not correct. The sorting is needed for two reasons:
* We generate the LOD meshes in the reverse order that we want them to be in the LOD array.
* MeshOptimizer can give lower or higher error thresholds than the ones we request, so there's no guarantee that after running the generation the LODs will be sorted, in which case we would just need to reverse the array.

I did check the MRP in this issue, and the way we currently do LOD generation and selection is working fine. The problem with this particular model comes from the fact that the decimation process doesn't take into account texture coordinates. 
Merging two vertices that lay in different sides of the basketball black lines results in a small error in terms of overall mesh shape (the only metric we account for now), but the break in the texture continuity makes a much bigger difference in the final renderer mesh. 

Here you can see the break being produced by the texture coordinates, rather than an oversimplified mesh geometry.
![Screenshot_20221029_184741](https://user-images.githubusercontent.com/4402304/198844345-5e2a2a23-a60c-4e02-b0d2-a1a470a0c09f.png)

I'm not sure that there is an easy solution for this issue other than checking if we can let MeshOptimizer know about texture coordinates for the mesh. But even then, a tiny change in texture coordinates can potentially have a huge impact in the final rendered mesh, so it's not a silver bullet.

**Comment by fire** [comment]
So there's two bugs.

1. is that the UVs are mirrored which is a change of sign rather than a discontinuity. It probably needs a recalculation of the uvs. Too difficult.
2. The lod levels decimate too soon.

**Comment by fire** [comment]
Here's another test lod failure case.

Tested with Godot 4 beta 3.

![image](https://user-images.githubusercontent.com/32321/198850906-62a39c01-fb53-429a-804e-5751954580af.png)
[New Game Project 2.zip](https://github.com/godotengine/godot/files/9894532/New.Game.Project.2.zip)


https://sketchfab.com/3d-models/sf-girl-a219070284e64ddd8a51f69c207cc81b
