### ISSUE TITLE
Unable to select a value in Editor in exported variable after "Clear" has been used

### ISSUE THREAD

**Issue by 2fd5** [godotengine/godot#67938]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

macOS 12.6 (21G115)

### Issue description

Unable to select a value in exported variable after "Clear" has been used
Variable is defined as follows `@export var script_name : Script`

Note that using circle arrow to reset the value works.
See gif
![Oct-27-2022 14-03-37](https://user-images.githubusercontent.com/64538990/198279516-0e2285d3-9055-4a3a-a7fb-299a11497b2f.gif)

Maybe related to https://github.com/godotengine/godot/issues/65916

### Steps to reproduce

1. Open reproduction project
2. Open node.tscn
3. Select Node
4. In Inspector -> Script Name -> from menu next to <empty> select "Load"
5. Select a "new_script.gd" file
6. From the same drop down select "Clear"
7. Again try In Inspector -> Script Name -> from menu next to <empty> select "Load"
8. Select a "new_script.gd" file
9. Now field "Script Name" is not updating

### Minimal reproduction project

[export_script_ui_1.zip](https://github.com/godotengine/godot/files/9879206/export_script_ui_1.zip)

**Comment by anvilfolk** [comment]
I've been slowly investigating this one. I'll keep this comment as a notepad for my findings as I keep digging. Here's what I know so far.

### General findings

This behavior:
- is still present on `master`, but not on `3.x`
- occurs even for `@export`ed `Resource` typed variables, when you try to assign a script to it.
- does not occur with other resources I have tried

### Specific findings

`EditorPropertyResource::update_property()` gets called twice. First when `EditorPropertyResource::_resource_changed()` gets called from a signal emitted by the resource picker, and a second time from `EditorInspector::_notification()` with a `NOTIFICATION_PROCESS`.

When called from because of `NOTIFICATION_PROCESS`, the resource from `Ref<Resource> res = get_edited_object()->get(get_edited_property());` is `NULL`. This is because the edited object is the underlying `Node2D` (in my case), but the edited property is `@export my_inner_var : Script`, which belongs to the script, not the Node2D object itself.

When called from `EditorPropertyResource::_resource_changed()`, the property is correctly identified.

Therefore, the issue appears to be that the edited property gets overridden by `NULL` in the `update_property()` call originating from `EditorInspector`'s `NOTIFICATION_PROCESS` notification.


### Open questions

- Why does the assignment work the first time it is attempted? What's different on the second time?
- Would it make sense for `Object::get()` to search its attached script for properties?
- Instead, would it make sense for void `EditorPropertyResource::update_property()` to check the object's script for the property if checking for the property on the object itself fails?
- `EditorPropertyResource::_resource_changed()` runs `s->call("set_instance_base_type", get_edited_object()->get_class());` on the script. Might this be the culprit for why it works once, then stops working?

**Comment by anvilfolk** [comment]
I believe I have the issue identified (see The Error section in my notes above), but I don't know exactly how to make the comparison work. I'd love some input!
