### ISSUE TITLE
c# class Image function not match gdscript

### ISSUE THREAD

**Issue by crasy1** [godotengine/godot#67937]
### Godot version

4.0 custom_build (03e5de37ae3228de26e7b83888c542a9f400b5d9)

### System information

macos

### Issue description

gdscript Image class functions create ,create_from_data are static function,but not in c# .
so call those function in c# will freezing.
by the way,how can i put byte[] in c# function Call(),Callv() etc

### Steps to reproduce

run this code in node
```
public override void _Ready()
    {
var image = new Image();
GD.Print("create start");
  image.Create(100,100,true,Image.Format.Rgba8);
GD.Print("create end");
  image.Fill(Colors.Black);
}
```
```
//this is not allowed
node.Call("set_bytes",new byte[]);
```

**Comment by raulsntos** [comment]
Since you are using a custom build, it's likely that you forgot to remove the previously generated packages. Try removing the contents of the `GodotNuGetFallbackFolder` and rebuild your game project. These packages are copied by the Godot editor but only if the same version doesn't already exist, since every custom build uses the same version it won't copy them again unless you explicitly remove them so make sure you cleanup that directory after you rebuild the assemblies to make sure the latest version of the packages is used.

About the second question, the `Call` methods, like most Godot methods, take Variant parameters and we currently don't have an implicit conversion between byte arrays and Variant, we have an implicit conversion between byte **spans** and Variant so you should be able to do something like this:

```csharp
var bytes = new byte[];
node.Call("set_bytes", bytes.AsSpan()); 
```

**Comment by crasy1** [comment]
get it!thanks
