### ISSUE TITLE
'New Project' browse window should have "Recent" and "favorites".

### ISSUE THREAD

**Issue by KioriSun** [godotengine/godot#6799]
**Operating system or device - Godot version:**
Any, Godot 2.1.Stable.Official

**Feature Request**
If this hasn't been added in the latest branch, the idea is to have the recent and favorites sub-window, just like when you open a scene up
![godot windows opt tools 32_2016-10-11_19-16-20](https://cloud.githubusercontent.com/assets/10463922/19292015/55637696-8fef-11e6-8f9a-3a0a895d9f23.png)

That should make creating new projects in same, non engine root, location easier.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 3ad9e47 : the project manager uses different node for opening folder so it doesn't have those.

**Comment by dreamsComeTrue** [comment]
I would also love to see some kinda 'Favourites' panel for directory selectors..

**Comment by Calinou** [comment]
I'm not sure how feasible this is, as you can't just replace references to `FileDialog` with `EditorFileDialog` in `project_manager.cpp` (or you'll get a segmentation fault when any of the file dialogs appear).

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
