### ISSUE TITLE
Vertex colors are not imported correctly from DAE files

### ISSUE THREAD

**Issue by muppetzero** [godotengine/godot#68]
When importing a collada file with vertex colors, the colors are not displayed either when using a fixed material with 'Use Color Array' checked, or when using a fragment shader as follows: DIFFUSE = COLOR.rgb;

The file that was used can be found here: https://dl.dropboxusercontent.com/u/69139577/tree.DAE

**Comment by akien-mga** [comment]
Can someone confirm this bug in the current master branch?
And was your collada file exported with Godot's "Better Collada Exporter"?

**Comment by kubecz3k** [comment]
Checked on fresh model exported from blender, it works for me. Not sure but it looks like the problem was with the model or exporter since DAE from the first post don't even have any material (or it's just   exported with so old better collada plugin that it's impossible to load this to current version of Godot).  
Anyway I'm closing this one, if the problem still exist on fresh export for you @muppetzero then open new issue.
