### ISSUE TITLE
Drag and drop picture editor can't recognize JPG in uppercase

### ISSUE THREAD

**Issue by xiaoliang6669** [godotengine/godot#68104]
### Godot version

4.0-beta3

### System information

win10

### Issue description

Drag and drop picture editor can't recognize JPG in uppercase

### Steps to reproduce

![6666](https://user-images.githubusercontent.com/112788136/199155520-0beb18f7-8057-4ba6-b4e2-77c1a8918aa0.png)

**Comment by alfredbaudisch** [comment]
I can't reproduce. Check whether the underlying image is really a JPG or if it just has the extension. 

Quickest way to check it I can recommend is to drag it here: https://www.metadata2go.com/

It should be an `image/jpeg` or `image/jpg`:

![image](https://user-images.githubusercontent.com/248383/199175553-c1421c80-4846-419d-84ab-09a43113d23b.png)

**Comment by xiaoliang6669** [comment]
![222](https://user-images.githubusercontent.com/112788136/199177098-9e3129d2-34de-4ca8-8d6c-79c7a47f41ba.png)

**Comment by akien-mga** [comment]
Can you attach that file in this issue (e.g. in a zip to ensure the metadata isn't changed by GitHub)?

**Comment by xiaoliang6669** [comment]
[1.zip](https://github.com/godotengine/godot/files/9907743/1.zip)

**Comment by akien-mga** [comment]
I can confirm the issue. The file is properly imported and gets a thumbnail, but drag and drop to the CanvasItem editor doesn't work. Drag and drop in a texture slot works fine. Changing the extension to `.jpg` does fix it.

**Comment by xiaoliang6669** [comment]
I know it can be solved by changing it to lower case. I hope it can be compatible with upper case

**Comment by alfredbaudisch** [comment]
@akien-mga `ResourceLoader::get_recognized_extensions_for_type` deals only with lowercase extensions across the board, it's not only a problem for dragging and dropping.

I could fix it in two ways:
1. Either cast the file name extension being dragged to lowercase (but only when making the extension check, the name will be preserved afterward)
2. Or duplicate extensions when calling `get_recognized_extensions_for_type`, adding both lowercase and uppercase extensions to the list, here: https://github.com/godotengine/godot/blob/master/core/core_bind.cpp#L76

(1) is easy and I could do right away, but (2) affects the core - so since this would be a big change, how are these things decided?

**Comment by akien-mga** [comment]
(2) is not a good option because you would also need to support `Jpg`, `JpG`, etc.

Extension tests should always be done with lowercased filenames, seems like this is just missing here for the drag and drop code.

**Comment by alfredbaudisch** [comment]
> (2) is not a good option because you would also need to support `Jpg`, `JpG`, etc.

Oh definitely! 💯 

> 
> Extension tests should always be done with lowercased filenames, seems like this is just missing here for the drag and drop code.

Done then https://github.com/godotengine/godot/pull/68107
