### ISSUE TITLE
find_node() for instanced nodes is counterintuitive

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#6811]
Current signature is `Node find_node( String mask, bool recursive=true, bool owned=true )`.

In my scripts when I have to find a node whose path can change a lot during development and has a unique name, I try to find it with `get_tree().get_root().find_node("node_name")`.

A lot of times that doesn't work because the target node is instanced (not owned) and the default value of `owned` if **true**. What's the rationale behind that? Wouldn't a more universal solution be to default it to **false**?

It often takes me some minutes to figure out what's happening. What's more, if a node which is formerly there as itself is later saved as its own scene and instanced, it suddenly becomes non-findable without editing the code.

Doesn't Godot 3.0 constitute a good chance to change that default value?

**Comment by bojidar-bg** [comment]
I think you don't want it to search deep in instanced scenes, since that would make everything a lot slower (like, 3x slower)

**Comment by Zylann** [comment]
I would not try to find a node that is moved/instanced/destroyed a lot in the hierarchy, I would prefer make it register in the scene root script, or in a singleton. It's way faster and simpler than assuming the node name will be unique or even be found.
(we could consider this as the same thing as using FindObjectsOfType in Unity, which is similarly a last-resort issue due to its slowness)

**Comment by RandomShaper** [comment]
Your ideas appeal to me so I'll adapt my node searching strategies to them.

In this respect it seems I was working against the tool.

Closing issue then.
