### ISSUE TITLE
8 UVS broke during gltf import

### ISSUE THREAD

**Issue by fire** [godotengine/godot#68150]
### Godot version

c29fe310f1b782cbf588ccf7040cf1606eba6769

### System information

Windows 11, Nvidia 3000

### Issue description

User tests in discord found that 8 uvs broke at some point.

### Steps to reproduce

1. Launch demo.
2. Launch tscn
3. See that the tscn only shows color on one left band the uv1, and uv2 and missing uv3, uv4, uv5, uv6, uv7, uv8

## Broke

Black should be coloured.

![image](https://user-images.githubusercontent.com/32321/199409082-e2d2d799-1926-4fc3-b655-1dcba8ed2614.png)

## Example test case

https://user-images.githubusercontent.com/32321/132632190-366120f9-04ab-49f5-9e54-835e53747ed0.mp4

https://github.com/godotengine/godot/pull/52504

### Minimal reproduction project

[multi_uv_set_test.zip](https://github.com/godotengine/godot/files/9916689/multi_uv_set_test.zip)

**Comment by lyuma** [comment]
The problem is caused by the Static Lightmaps import option.
Suzanne_GLTF2_Multi_UV_Sets.gltf as defined in the MRP (Static Lightmaps):
![mostly black except the left quarter showing UV1/2](https://user-images.githubusercontent.com/39946030/215663978-d2483806-ba06-4e50-af06-22e72c77ba1a.png)

And now the same mesh with any other option:
![every quarter of the screen shows UV data](https://user-images.githubusercontent.com/39946030/215664074-89742af6-f248-4be6-93b0-92661c555c9d.png)
