### ISSUE TITLE
Editor tooltips stay on game screen when launching maximized/large game window (DisplayServer regression)

### ISSUE THREAD

**Issue by rainlizard** [godotengine/godot#68197]
### Godot version

v4.0.beta4.official [e6751549c]

### System information

Windows 10, 970 GTX

### Issue description

It's not the end of the world but it is very annoying. I like to be maximized when testing but now I have to be conscious of where the mouse pointer is whenever I press F5.

![Untitled](https://user-images.githubusercontent.com/15337628/199633673-35746040-ba54-4f5d-bd45-85bfe97bd68a.png)

When this happens, the window needs to be switched or closed in order to clear it.

It seems if you press F5 when the tooltip is already showing, then it is cleared properly. But if you press F5 right before the tooltip shows, then it stays on screen.

### Steps to reproduce

1. Set `Project Settings -> Display -> Window -> Mode -> Maximized`, or Viewport Width/Height to cover most of the screen
2. Move mouse over something in the inspector that will display an editor tooltip
3. Before the tooltip appears, press F5
4. Tooltip now stays on game screen permanently until you change windows or close it

**Comment by Calinou** [comment]
As a workaround, enable the **Single Window Mode** editor setting then restart the editor.

**Comment by Grimmr** [comment]
This issue seems to have been introduced on linux in ac1e7e10.

flipping the `focused` member of `WindowData` to false in "platform/linuxbsd/x11/display_server_x11.h:158" fixes the issue and is basically a reversion of ac1e7e10. I also can't see any other changes in behaviour caused by this the newly created window(s) are still getting focus (eg: OS hotkeys to move them about automatically apply to the newest window)

I've applied a fix and opened a PR but as this is my first contribution to this codebase there is a non-zero chance I've missed something.

I'm not sure about how the same is happening on windows though as I don't have access to a windows machine

**Comment by Sauermann** [comment]
I can confirm this problem on Linux X11 Xfce.

**Comment by Grimmr** [comment]
My above solution has consequences as it reverts the sole commit of the fix for #53894 which causes it to regress. I'm going to do some more looking into the tooltips themselves and how they get the signal to go away

**Comment by Grimmr** [comment]
So I've done a bit of investigation and I have a possible solution. The tool tips hang around whenever focus is lost not just when running the game (eg: alt-tab), we don't clean up tooltips when the window focus is lost (we only do it based on input events like mouse movement). it seems that when we lose focus we also stop getting input events so the tooltip just hangs there. 

My fix is to cancel all tooltips when window focus is lost. This effects all viewports  and so I'm not 100% on knock on effects this may have. However it seems reasonable to clean them when focus is lost assuming all tooltips are meant to behave like the one in the original issue here.

This does work but it doesn't explain why the bug free version (I've been using the commit just before ac1e7e1) doesn't exhibit this behaviour on alt-tab while ac1e7e1 does. There's also some other weirdness in the bug free version, like when tooltips are cleaned due to a new window being created it's not done via "_gui_tooltip_cancel()" and they don't get nulled, they just vanish and the call to "_gui_tooltip_cancel()" and the nulling happens when the main window re-gains focus.

I'm going to rebase my solution and make a draft PR now so it's visible
