### ISSUE TITLE
[GodotPhysics] Raycasts don't reliably collide with HeightMapShape3D

### ISSUE THREAD

**Issue by celeste-sinead** [godotengine/godot#68238]
### Godot version

v4.0.beta.custom_build.01ae26d31

### System information

Pop!_OS 22.04, 5.19.0-76051900-generic, Intel(R) UHD Graphics (CML GT2)

### Issue description

When casting rays from the camera in the direction of the mouse position, I found that in some camera positions and orientations, the result of the result of PhysicsDirectSpaceState3D.intersect_ray is empty where it ought to have found a collision. 

When this occurs, there is generally a contiguous region of the heightmap through which rays cast from a given camera position won't produce a result. Different camera transforms produce different non-colliding regions (and some camera transforms result in no such regions). When I originally encountered this issue with non-flat heightmaps, I found non-colliding regions could occur anywhere in the heightmap, not necessarily touching edges, in non-rectangular shapes, and often multiple such regions would exist.

In the simplified reproduction project I've only observed rectangular non-colliding regions, usually at the +X edge but sometimes at +Z.

### Steps to reproduce

I haven't isolated exact conditions for when this occurs. I've observed it to be sensitive to the following:

- heightmap size: I've only been able to reproduce this with heightmaps of 20x20 and larger
- raycast length: I've only been able to reproduce this with rays >20 length
- camera transform (ray origin / direction): changes which regions of the heightmap don't collide, and in some cases prevent the issue. Directions closer to -Y seem much less likely to reproduce the issue.
- heightmap shape: the flat heightmap in the repro project only seems to produce rectangular non-colliding regions at the edge of the heightmap, but for non-flat (specifically, simplex noise) maps I've seen multiple not-necessarily rectangular regions not necessarily touching edges.

The reproduction project sets a camera transform where the issue is apparent (and will cast rays to mouse position and position a sphere at the intersect location when detected). It also includes a script that casts an example ray that ought to collide but doesn't, and also draws a line corresponding to that ray to demonstrate visually that it ought to have collided.

### Minimal reproduction project

[heightmap_raycast_repro.zip](https://github.com/godotengine/godot/files/9933778/heightmap_raycast_repro.zip)

**Comment by Calinou** [comment]
Can you reproduce this on 3.5.1 (with both Bullet and GodotPhysics)?

**Comment by ipeet** [comment]
This reproduces on 3.5.1 with GodotPhysics but not with Bullet.

**Comment by ciqven** [comment]
I can confirm this is still occurring on *Godot 4.0 beta 16*, with a flat (`map_data` nothing but zeroes) `HeightMapShape3D` of size 64x64.

* What works *
- Using a `BoxShape3D` works.
- Using `create_trimesh_collision()` on the `MeshInstance3D` representing the terrain works.
- Enabling *Debug -> Visible Collision Shapes* shows a correct looking wireframe for `HeightMapShape3D`.

* What doesn't*
- When using a `HeightMapShape3D`, manual raycasting with `PhysicsDirectSpaceState3D.intersect_ray()` returns an empty `Dictionary` for some regions of the shape.
- When using a `HeightMapShape3D`, `CollisionObject3D.input_event()` does not receive any `InputEvent`s for the same regions as previous point.

**Comment by dkaste** [comment]
I can also reproduce this (v4.1.dev.custom_build [5860b02b6])

I have a hunch that this may happen at the borders between the collision shape triangles as seen with Visible Collision Shapes enabled.

**Comment by kevinkuo52** [comment]
using 
[heightmap_raycast_repro.zip](https://github.com/godotengine/godot/files/9933778/heightmap_raycast_repro.zip)
Raycast with issue seems to fall under this case here ray is long so it does query on higher level grid first
https://github.com/godotengine/godot/blob/f7c567e2f56d6e63f4749387a67e5ea4903c4696/modules/godot_physics_3d/godot_shape_3d.cpp#L1998
Stepping thru code, it looks like the loop here exit before it got to the chunk where the ray actually intersect
https://github.com/godotengine/godot/blob/f7c567e2f56d6e63f4749387a67e5ea4903c4696/modules/godot_physics_3d/godot_shape_3d.cpp#L1940
p_width and p_depth is the grid's width and depth (ceil(21/16) = 2 in the case of [heightmap_raycast_repro.zip](https://github.com/godotengine/godot/files/9933778/heightmap_raycast_repro.zip))

Think the fix is to change the logic to be `if ((x < 0) || (z < 0) || (x >= p_width) || (z >= p_depth))`
because x = 1 or z = 1 should still be valid chunk, but it will exit here.

tested this fix on this MVP and it seems to work [heightmap_raycast_repro.zip](https://github.com/godotengine/godot/files/9933778/heightmap_raycast_repro.zip)

There's parts I still don't quite understand in this code, so looking more before I raise the PR to make sure it's the correct fix.
And also test fix on this MVP when i have time:
[raycastHeightmapBug.zip](https://github.com/godotengine/godot/files/12774149/raycastHeightmapBug.zip)
