### ISSUE TITLE
TileMap: Updating texture_offset in _tile_data_runtime_update() has no effect

### ISSUE THREAD

**Issue by DekuJuice** [godotengine/godot#68277]
### Godot version

v4.0.beta3.official [01ae26d31]

### System information

Windows 10

### Issue description

Changing the texture offset in the runtime TileData in _tile_data_runtime_update() does nothing, since in draw_tile() the texture_offset from the runtime TileData is ignored:

https://github.com/godotengine/godot/blob/ec521a405a89a1b80a9989c09dcc2f2e7763ddcf/scene/2d/tile_map.cpp#L1369-L1375

### Steps to reproduce

Create a TileMap
Update a cell's TileData texture_offset in _tile_data_runtime_update(). The tile's position will not change.

### Minimal reproduction project

[RuntimeTileData.zip](https://github.com/godotengine/godot/files/9942845/RuntimeTileData.zip)

**Comment by groud** [comment]
You example project clearly shows a mistake, assuming that `_tile_data_runtime_update` is ran every frame. 
This method is in fact only called when you set/update a tile, otherwise it would cause huge performance issues.

This method can be useful, but it should definitely be not used to animate tiles in a complex way (like, more complex than what the built-in tileset animation system provides). Instead, you should use a TileSetSceneCollectionSource, and paint scenes on your tilemap.

**Comment by DekuJuice** [comment]
The example project calls force_update() in _process(), you can add a line to change the modulate and you can see it will change while the offset does not.
I agree TileSetSceneCollectionSource is probably a better solution for animating tile movement, but I still think it should be possible to alter offsets per tile, one example (non animation related) use case being to slightly offset tiles for visual effect:
![image](https://user-images.githubusercontent.com/10264470/200434071-ff121090-3a3e-496a-ac96-f7d0962ae016.png)

**Comment by manekinekodesu** [comment]
I used "tile_tex_offset" in godot v3.5 to create a tile bouncing effect when the player hits it from below like in a Mario game. But I ran into this problem when migrating my project to v4. I believe that this restriction should be lifted.

**Comment by FluffyJay1** [comment]
AFAIK this is the only mechanism we have (barring TileSetScenesCollectionSource) to dynamically position a tile separately from the collision shapes defined in its physics layers. Please correct me if I'm wrong (I'd really like to do this another way for my use case).

I'm making a top-down 2D game with a pseudo height dimension. "Height" is implemented as rendering the sprite at a Y offset. I want to implement physics so all collision shapes are placed at "sea level", but the corresponding sprites can be rendered at any "height". This simplifies collision logic between objects at different heights, e.g. when stairs are involved. But I also want to use tilemaps at different heights. For this to work I need some way to e.g. render a tilemap at a certain height but send the collision shapes to "sea level". In Godot 3 I used `TileSet.tile_set_texture_offset(...)` to achieve this, and that's the maximum amount of hacking around I'm willing to do. If there really is no other way in Godot 4, I'd like this restriction lifted.

**Comment by kleonc** [comment]
@groud BTW I think the name of the property and the behavior are reversed. For positive `texture_offset` I'd expect the tile to be visually shifted right/down (also that's how it works in 3.x). Currently it would be shifted left/up instead because as mentioned it's the offset of the texture origin, hence the visible texture offset is the opposite. So I suggest either renaming this property or reversing its behavior.

>In the end I think that maybe the restriction could be lifted, at the price of maybe a confusing UI when you have weird origins sets (the origins might overlap in the property painting panel. But I guess we could find a workaround.

Even without a workaround I'd say a confusing UI is better than lack of the feature many users require / rely on. UI can always be improved later (e.g. based on the feedback of some angry users :smile:).

**Comment by groud** [comment]
> @groud BTW I think the name of the property and the behavior are reversed. For positive texture_offset I'd expect the tile to be visually shifted right/down (also that's how it works in 3.x). Currently it would be shifted left/up instead because as mentioned it's the offset of the texture origin, hence the visible texture offset is the opposite. So I suggest either renaming this property or reversing its behavior.

Yeah, I guess it could be renamed "texture_origin" I guess. But I feel it's a bit late now.

> Even without a workaround I'd say a confusing UI is better than lack of the feature many users require / rely on. UI can always be improved later (e.g. based on the feedback of some angry users smile).

Users should not rely on that though. Animating such a value is super inefficient and should be done with a scene instead. I am not strictly against it but it is not of very high priority TBH.
