### ISSUE TITLE
Using ray casting to select faces

### ISSUE THREAD

**Issue by LeonardMeagher2** [godotengine/godot#684]
http://www.moczys.com/webGL/Experiment_02_V05.html

Being able to select a face from a mesh, or collision shape could be a useful feature in godot, in this example they change face color, but I could imagine using the face to get uv information which can turn to pixel information, and having the ability to move an image around in a 2d scene.

**Comment by bojidar-bg** [comment]
Shouldn't this be considered for 3.0?

**Comment by akien-mga** [comment]
What's the status on this for the upcoming 3.0 release?

**Comment by reduz** [comment]
There is TriangleMesh now, but it does not keep UV information. It's also mostly used for editing.
Kicking for 3.1

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by LeonardMeagher2** [comment]
I don't think this a necessary feature anymore, it's easily solved many other ways.
Might open another issue or PR for exposing TriangleMesh functions to GDScript, but that's about it.

**Comment by idchlife** [comment]
So basically as of 2021 there is no built-in way as in Unity (RayCastHit.textureCoord) to get coordinate of texture to work with it etc?

I mean there are workarounds like shaders or manually iterating through every vertice but no easy way?

Asking because I came from Unity at some point and was utilizing .textureCoord heavily there. It seems Godot simply does not have such feature without modifying engine with some cpp plugins etc?

**Comment by leiget** [comment]
@idchlife
Yes it seems so, unfortunately. But Considering the 4.0 render API refactor, I imagine it'll eventually be on the list. Let's see if there is a issue/request for it in the tracker, and if not, then maybe we should make one.

**Comment by Calinou** [comment]
For the record, @leiget opened a proposal: https://github.com/godotengine/godot-proposals/issues/2863
