### ISSUE TITLE
Beta releases missing git tags

### ISSUE THREAD

**Issue by gerrywastaken** [godotengine/godot#68563]
### Godot version

4.0 beta 4

### System information

Linux

### Issue description

Please tag beta releases. This way people who feel inclined can both try the beta and easily contribute fixes.

Currently, if you want to build the beta from the source you have to track down the commit ID. After some searching, I guessed correctly and found it in the readme here: https://downloads.tuxfamily.org/godotengine/4.0/beta4/README.txt, but I was surprised it wasn't just a git tag.

Does tagging these releases cause problems?

### Steps to reproduce

> git clone git@github.com:godotengine/godot.git
> git checkout 4.0-beta-4

error: pathspec '4.0-beta-4' did not match any file(s) known to git

**Comment by Zireael07** [comment]
Commit id (hash) is shown in the project manager when opening it and can even be clicked to copy to your clipboard

**Comment by gerrywastaken** [comment]
@Zireael07 Are you suggesting somebody first download the binary version, in order to find out the commit ID, so they can build the actual version they wanted?

**Comment by adamscott** [comment]
@akien-mga Build/git related issue

**Comment by KoBeWi** [comment]
AFAIK we don't tag betas to avoid having too many tags.

**Comment by Sauermann** [comment]
You can also look in the release announcements (e.g. https://godotengine.org/article/dev-snapshot-godot-4-0-beta-4) and look for the line containing "__This release is built from commit__". The commit id is mentioned there.

**Comment by akien-mga** [comment]
Not tagging alpha/beta snapshots is intentional:
- I like tags to reflect actual stable releases, and not multiply their number by 30 to include all pre-release snapshots.
- Dev snapshots are just snapshots from the master branch. If you want to work on fixing issues, the best is always to build the latest master branch. Knowing the commit of a given beta is only useful to bisect regressions, and for custom builds that need to be compatible with a given snapshot for some reason (e.g. custom Android template to use with the official build of the editor, or using godot-cpp with GDExtension header and JSON synced with a given snapshot). In both cases this info can be easily found in the README when needed.
- As they're snapshots from the master branch, it can happen more often than not that a given platform doesn't build properly and I then do a fixup on the buildsystem which may be out of sync with the upstream branch (if new PRs were merged after the dev snapshot started building, or if the hotfix is still pending review/merge). Some snapshots had custom PRs merged locally before they are merged in master to fix issues preventing making a release. Obviously this doesn't happen for tagged stable releases, which are guaranteed to be built from the exact same code as found under their tag, but for alpha/beta snapshots with biweekly release schedule and 4-5 hour long builds, I'm more flexible.

Overall it's mostly a matter of personal taste, and I agree that it's arbitrary, but as release manager I prefer not to tag unstable snapshots.

**Comment by gerrywastaken** [comment]
@akien-mga 

I think there was some confusion about why I was asking for this and who I was asking for. Creating and responding to this ticket has already taken more time for me than I will probably ever save. I was asking for others who likely don't wish to be sitting on the latest HEAD commit but who might compile the latest beta and then end up one-day submitting PRs. I was hoping to lower the barrier to entry for future possible Godot devs and remove some reasons they might be turned away:

![compile-godot](https://user-images.githubusercontent.com/71481/201494385-531f27d4-e8ec-4bc9-8d3a-d060259a79b8.png)
https://www.youtube.com/watch?v=ebriLXCVfx8&lc=Ugxo9Jf-oo6NWyRYoAN4AaABAg

> and not multiply their number by 30

Good point. One tag for the latest would achieve most of the benefits. e.g. `latest-dev-release`

> And deleting tags in Git requires a force push

Maybe you are thinking of overwriting a tag?
`git push --delete origin tagname`

But even overwrite is only a force push of a tag that would be pointing to a specific commit on the master branch, so the traditional issues of force pushing shared branches with rewritten commits isn't applicable.

> and doesn't propagate to local clones, which then keep outdated local tags and may push them again.

True. They would have to specifically push all tags (bad practice) or that specific tag. This same argument could be applied to any local tags they set up/modified themselves. 

I would expect only the release manager or other admins are pushing tags:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules

Anyway, now that I've clarified what I was intending. I'll leave it at this.

**Comment by KoBeWi** [comment]
> I was asking for others who likely don't wish to be sitting on the latest HEAD commit but who might compile the latest beta and then end up one-day submitting PRs. I was hoping to lower the barrier to entry for future possible Godot devs and remove some reasons they might be turned away:

I use latest HEAD builds often and situations where the build is completely broken are super rare. Also master usually has more fixes than regressions compared to betas. Also also, this mostly matters when you are actually working on something (and I think people would rather use official releases). For contributing it's not really a concern.
