### ISSUE TITLE
Event Configuration listening to gamepad axis generates long string not fitting for search filter

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#68617]
### Godot version

v4.0.beta.custom_build [767f8fb48]

### System information

Linux Ubuntu 20.04 with Unity desktop

### Issue description

Possible regression of https://github.com/godotengine/godot/pull/43660

When configuring input mapping in Project Settings > Input Map > Event Configuration, and pressing a gamepad axis to auto-fill the Listening for input... field, a long readable string is printed, but not the one needed to add an input mapping.

For instance, when moving the left stick to the left, I get:
> Joypad Motion on Axis 0, (Left Stick X-Axis, Joystick 0 X-Axis) with Value -0.59

which doesn't auto-select the corresponding directed axis, whose official name is "Joypad Axis 0 - (Left Stick Left, Joystick 0 Left)"

![image](https://user-images.githubusercontent.com/1067772/201531740-1c8ad0b5-c1b9-45c1-a8b8-ee49e03cf199.png)

I'm looking at the code in editor/input_event_configuration_dialog.cpp and can clearly see the quickfix in InputEventConfigurationDialog::get_event_text under

> // Joypad motion events will display slightly differently than what the event->as_text() provides. See https://github.com/godotengine/godot/pull/43660.

which should use the official name, but it doesn't seem to be applied.

I couldn't make debugging work in my VS Code so I don't know why the quickfix doesn't work exactly, but I suggest developers tackling this issue to start by debugging get_event_text.

### Steps to reproduce

1. Open Project Settings > Input Map > add a new input mapping (+ button)
2. In the Event Configuration popup, focus the Listening field and press your gamepad left stick or any axis in some direction
Expected: short name formatted like "Joypad Axis 0 - (Left Stick Left, Joystick 0 Left)" is displayed
Actual: the long name is displayed with value, formatted like "Joypad Motion on Axis 0, (Left Stick X-Axis, Joystick 0 X-Axis) with Value -0.59"

### Minimal reproduction project

Any project will do.

**Comment by clayjohn** [comment]
CC @EricEzaM

**Comment by EricEzaM** [comment]
Good catch, thanks. I forgot that joypad events are displayed differently in the input event dialog. I recently refactored the way inputs are listened to into `event_listener_line_edit.cpp`, which does not use the `_joy_axis_descriptions` array you found in the `input_event_configuration_dialog.cpp` file - but it probably should.

I also noticed that although you have made input with an axis, the top label has not updated (which is the event actually selected). This is because joypad motion for input event configuration purposes has a cutoff of 0.9. This causes trouble as sometimes the input is not above 0.9. Removing this limit does not cause issues so I will do that too.
