### ISSUE TITLE
Crushed after export while trying to get a static json file

### ISSUE THREAD

**Issue by Kaoruha** [godotengine/godot#68635]
### Godot version

Godot Engine v3.5.1.stable.mono.official.6fed1ffa3 - https://godotengine.org

### System information

Linux kali 5.19.0-kali2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1kali2 (2022-10-10) x86_64 GNU/Linux

### Issue description

I have a json file.
Project structrue like this.
src
├── config
│   └── config.json

I read the file via
```
var data_file = new File();                                                                                                                                                                  
  1         try
  2         {
  3             data_file.Open("res://config/config.json", File.ModeFlags.Read);
  4         }
  5         catch (System.Exception error)
  6         {
  7             GD.Print(error);
  8             throw;
  9         }
```

It works well in play scene.But when i export the project. It will crush.
It works fine if i delete the code reading json file.

### Steps to reproduce

1. Add a static json file.
2. Read file with "res://"
3. Export.
4. Run.

**Comment by yedpodtrzitko** [comment]
This is expected behaviour in 3.x, `.json` files are not considered resources by default. You have to add them explicitly in the Export dialog window.

This is changed in 4.x, see https://github.com/godotengine/godot-proposals/issues/3608, but I dont think this will be changed in 3.x as it would be a breaking change in the current behaviour.

**Comment by Kaoruha** [comment]
Thanks, problem solved.
