### ISSUE TITLE
Code signing Mac exports from Windows doesn't work 

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#68744]
### Godot version

3.5.1

### System information

Windows 10

### Issue description

If I export my game on Windows 10 for mac, then try to run it on a macbook it will immediately crash and give an error report with: EXC_CRASH (SIGKILL (Code Signature Invalid))

### Steps to reproduce

Make a game, export for Mac from a Windows PC
Run the game on an up-to-date macbook

**Comment by bruvzg** [comment]
> If I export my game on Windows 10 for mac

Using ad-hoc signature or a real one with `rcodesign`?

**Comment by Miziziziz** [comment]
> > If I export my game on Windows 10 for mac
> 
> Using ad-hoc signature or a real one with `rcodesign`?

ad-hoc

**Comment by bruvzg** [comment]
Ad-hoc signature seems to be working correctly. To check signature, you can use `codesign -vvvv ./your_app.app` command.

Please note that due to the nature of ad-hoc signing, it won't run until you have allowed it to run:
- Gatekeeper should be set to allow third-party apps.
- You should remove quarantine flag by right-clicking app in the Finder and selecting `Open` in the menu, in the `System Setting` or by using `xattr` command - see https://docs.godotengine.org/en/latest/tutorials/export/running_on_macos.html#app-is-signed-including-ad-hoc-signatures-but-not-notarized for details (distribution platforms like Steam usually do it for you).

The only reason ad-hoc exist, M1/M2 macs require executables to be signed to run, but it's not a substitute for the real signature/notarization.

When you are exporting and running on the same mac, the quarantine flag is not set, so it will run (but will have the same issues if it's moved to another mac).

If you want to it to run without any issues on any mac you have to use real signature and notarize it, there are no other options.

**Comment by Miziziziz** [comment]
Hey just checked, and fixing the run path on steam to point at the bundle instead of the executable as you mentioned in #68745 seems to fix it.
