### ISSUE TITLE
Mac exports on steam require double click to use left mouse button

### ISSUE THREAD

**Issue by Miziziziz** [godotengine/godot#68745]
### Godot version

3.5.1

### System information

macOS 13.0 Ventura

### Issue description

Not sure if this is a steam issue or a godot issue, but it happens on two of my games on steam that I've tested. Can provide copies to testers if they need.

Basically if you open the game left click is unresponsive unless you click twice. The fix is to not move the mouse at all until the game menu fully loads. Notably the same bug is found in CSGO here: https://steamcommunity.com/discussions/forum/2/1752358461539279191/

### Steps to reproduce

Open a godot-made game in steam from a macbook. 
I can provide a key for one if needed

**Comment by bruvzg** [comment]
Is it an issue if you run the `.app` bundle directly from Finder instead of running it from Steam? It's possible that macOS Ventura broke the window activation hack again (and if Steam is running executable directly, instead of a bundle).

**Comment by bruvzg** [comment]
Also, are "semaphore" buttons in the window title bar grayed out when it's happening?

**Comment by Miziziziz** [comment]
> Is it an issue if you run the `.app` bundle directly from Finder instead of running it from Steam? It's possible that macOS Ventura broke the window activation hack again (and if Steam is running executable directly, instead of a bundle).
Yeah it works fine running it from the finder

> Also, are "semaphore" buttons in the window title bar grayed out when it's happening?
Sorry what do you mean by semaphore buttons?

**Comment by bruvzg** [comment]
<img width="89" alt="Screenshot 2022-11-16 at 22 03 12" src="https://user-images.githubusercontent.com/7645683/202282671-ca6b81b7-3d33-4d1b-b7b1-ce9ae413c2ab.png">

**Comment by Miziziziz** [comment]
yes they are grayed out, and if I move the cursor outside and click the bar it fixes the problem

**Comment by bruvzg** [comment]
OK, it seems to be the same issue, but now it's manifesting when you run the executable directly even if it's bundled (on previous OS versions it was doing in only for unbundled apps and when running from terminal).

Firstly, Steam config for the game should specify the path to the bundle instead of the executable, e.g., `Game.app` not `Game.app/Contents/MacOS/Game`. This should fix the issue.
- Bad config - https://steamdb.info/app/404790/config/ (yep, Godot itself is affected).
- And this one seems to be good - https://steamdb.info/app/1712390/config/ (Godot game, seems to work fine).

This is working with non-Steam shortcuts added to Steam.

Also, try the following patch (I have briefly tested it, and it seems to work, but I do not what API Steam is using, so it might need more testing).
```diff
diff --git a/platform/osx/os_osx.mm b/platform/osx/os_osx.mm
index cc9b9287ed..61b6a73bec 100644
--- a/platform/osx/os_osx.mm
+++ b/platform/osx/os_osx.mm
@@ -195,7 +195,9 @@ static NSCursor *cursorFromSelector(SEL selector, SEL fallback = nil) {
 
 - (void)applicationDidFinishLaunching:(NSNotification *)notice {
 	NSString *nsappname = [[[NSBundle mainBundle] infoDictionary] objectForKey:@"CFBundleName"];
-	if (nsappname == nil || isatty(STDOUT_FILENO) || isatty(STDIN_FILENO) || isatty(STDERR_FILENO)) {
+	NSString *nsbundleid_env = [NSString stringWithUTF8String:getenv("__CFBundleIdentifier")]; 
+	NSString *nsbundleid = [[NSBundle mainBundle]bundleIdentifier];
+	if (nsappname == nil || isatty(STDOUT_FILENO) || isatty(STDIN_FILENO) || isatty(STDERR_FILENO) || ![nsbundleid isEqualToString:nsbundleid_env]) {
 		// If the executable is started from terminal or is not bundled, macOS WindowServer won't register and activate app window correctly (menu and title bar are grayed out and input ignored).
 		[self performSelector:@selector(forceUnbundledWindowActivationHackStep1) withObject:nil afterDelay:0.02];
 	}
```

**Comment by akien-mga** [comment]
> Bad config - [steamdb.info/app/404790/config](https://steamdb.info/app/404790/config/) (yep, Godot itself is affected).

Thanks, I just edited it to point to `Godot.app` directly. It still passes `--path $PATH -p` as arguments, will that work?

**Comment by bruvzg** [comment]
> It still passes --path $PATH -p as arguments, will that work?

It should work, at least with non-Steam bundle arguments are passed correctly.

**Comment by bruvzg** [comment]
> I just edited it to point to Godot.app directly.

Steam version activation issue seems to be fixed. Arguments are passed, but I'm not sure what it supposed to do.

**Comment by akien-mga** [comment]
> Steam version activation issue seems to be fixed. Arguments are passed, but I'm not sure what it supposed to do.

The `--path $HOME` (previous `$PATH` mention was a typo) I think is to set the working path to `$HOME`, so that when you create a new project it shows you your home and not the Steam installation folder.

And `-p` is to force running the project manager in case you put a `project.godot` file in your `$HOME` by mistake.

**Comment by Miziziziz** [comment]
> Firstly, Steam config for the game should specify the path to the bundle instead of the executable, e.g., `Game.app` not `Game.app/Contents/MacOS/Game`. This should fix the issue.

Oh yeah this fixed it, thanks!
