### ISSUE TITLE
Time_left not working

### ISSUE THREAD

**Issue by AmilcarGodot** [godotengine/godot#68761]
### Godot version

4.0 beta 5

### System information

Windows 10

### Issue description

Hey people
I'm working on a rifle code adding a timer (autostart and One shot checked, time set at 0.1)
time_left seems not working at all
Thanks
			
### Steps to reproduce
```
if Input.is_action_just_pressed("Shoot") and Rifleshoot.time_left == 0.1:
	print("Time Left is buggy")
	var shoot_origin2 = shoot_from2.global_transform.origin
	var b6 = bullet06.instantiate()
	var Shoottarget = grapplecast.get_collision_point()
	muzzle2.add_child(b6)
	b6.look_at(Shoottarget)
	b6.global_transform.origin = shoot_origin2
	var shoot_dir1 = (Shoottarget - shoot_origin2).normalized()
	b6.direction = shoot_dir1
	b6.add_collision_exception_with(self)
	Rifleshoot.start()
```
### Minimal reproduction project
```
if Input.is_action_just_pressed("Shoot") and Rifleshoot.time_left == 0.1:
	print("Time Left is buggy")
	var shoot_origin2 = shoot_from2.global_transform.origin
	var b6 = bullet06.instantiate()
	var Shoottarget = grapplecast.get_collision_point()
	muzzle2.add_child(b6)
	b6.look_at(Shoottarget)
	b6.global_transform.origin = shoot_origin2
	var shoot_dir1 = (Shoottarget - shoot_origin2).normalized()
	b6.direction = shoot_dir1
	b6.add_collision_exception_with(self)
	Rifleshoot.start()
```

**Comment by mrcdk** [comment]
You shouldn't compare float values with `==` as they [aren't precise enough](https://docs.godotengine.org/en/latest/classes/class_float.html). Use [`is_equal_approx()`](https://docs.godotengine.org/en/latest/classes/class_@globalscope.html#class-globalscope-method-is-equal-approx) or [`is_zero_approx()`](https://docs.godotengine.org/en/latest/classes/class_@globalscope.html#class-globalscope-method-is-zero-approx) for that.

**Comment by clayjohn** [comment]
Yes, as mrcdk points out, this isn't a bug, the chanced of ``time_left`` being exactly 0.1 are extraordinarily low. As an example, imagine what would happen if ``time_left`` was ``0.101`` one frame and then ``0.99`` the next. Your condition would never trigger. You need to use a broader range (like using ``is_equal_approx``) or better yet do something like ``if time_left < 0.1`` so that any value under ``0.1`` will trigger the branch. 

In the future, please do not open a bug report for obtaining help with your code. Please ask for help in one of the various [community channels](https://docs.godotengine.org/en/latest/community/channels.html).
