### ISSUE TITLE
BackBufferCopy does not allow you to use anchor + margins properly

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#6880]
**Operating system or device - Godot version:**
x11 64bit, v2.2.alpha.custom

**Issue description** (what happened, and what was expected):
When you place an "BackBufferCopy" node in your scene, regardless of your parent anchor and sizes, it wont allow you to set size to match parent sizes.
Currently, you have to manually change the size of the children as anchor+margins are useless.

**Steps to reproduce:**
![image](https://cloud.githubusercontent.com/assets/6776092/19567649/d25f11cc-96ee-11e6-8f38-836d795ec5f3.png)

Does not use parent sizes.

**Comment by bojidar-bg** [comment]
I'm not sure you have to add children to the BackBufferCopy...
Also, this is not a bug, its a feature, that's how all Node2D>Control scenarios work.

**Comment by Tybobobo** [comment]
One feature I could do without, and always could have. Same with Node2D; although I can just use Control instead. Unfortunately, I have no option but to use BackBufferCopy in order to run multiple shaders on top of eachother.

How would you suggest I attach a shader that covers the entire screen without having to manually set the sizes to fit screen?

**Comment by bojidar-bg** [comment]
BTW, to anyone who stumbles upon this, you can just put the BackBufferCopy as a sibling to the other nodes.

E.g., do this:
* Control
  * Shader A
  * BackBufferCopy
  * Shader B // All is good

Instead of:
* Control
  * Shader A
  * BackBufferCopy
    * Shader B // Can't resize automatically
