### ISSUE TITLE
When the number of PointLight2D nodes is up to 16, all 2D lights are not visible

### ISSUE THREAD

**Issue by Fantety** [godotengine/godot#68812]
### Godot version

4.0 beta 5

### System information

Windows 10, Vulkan, AMD Radeon(TM) Graphics

### Issue description

Add the PointLight2D node in the 2D scenario. Add a texture to the node, copying the PointLight2D node. When the number of nodes in the stack reaches 16, all lights are invisible.

https://user-images.githubusercontent.com/62731498/202603403-1ca791b0-2a5a-4724-8d69-b3d338341fa1.mp4

### Steps to reproduce

1. Create a 2D scene
2. Add background texture to the scene
3. Add the CanvasModulate node
4. Add the PointLight2D node and texture it
5. Ctrl+D replicates the PointLight2D node until the number of nodes reaches 16

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
I can reproduce this on both the OpenGL renderer and the Vulkan renderer, so any fix will have to be done for both.

**Comment by firebelley** [comment]
This issue is negatively affecting my bullet-hell game. Each bullet (red dots) have lights as children. When I have enemies do burst shots, it appears to disable lighting only within a specific rectangular area:

![vlcsnap-2023-01-19-17h41m16s985](https://user-images.githubusercontent.com/4622925/213578401-03730d81-82e9-42b3-9fcd-3726354ca329.png)

Not sure if this added info helps at all, but I did some testing and did confirm that this light limit is what's causing it.

**Comment by Calinou** [comment]
> Each bullet (red dots) have lights as children. When I have enemies do burst shots, it appears to disable lighting only within a specific rectangular area:

Consider using sprites with additive blending instead, as light rendering is much slower.

**Comment by firebelley** [comment]
@Calinou Ah thanks for the pointer! I was unaware I could do that. This is functionally the same and is a great workaround for this issue 👍
