### ISSUE TITLE
VariantParser: Encoding issue for Unicode chars when loading/streaming

### ISSUE THREAD

**Issue by BBric** [godotengine/godot#6888]
In my project path i have a directory called 'Développement', the first time i launch a project the terminal display a normal output:

```
OPENING:.../Développement/...::Développement::...
```

But the second time it display:

```
OPENING:.../Développement/...::DÃÂ©veloppement::...
```

Then:

```
OPENING:.../Développement/...::DÃÂÃÂÃÂÃÂ©veloppement::...
```

And rapidly it can take one minute for display dozens of lines just for the path.
Ubuntu 14.04.

Edit:
workaround: restore editor_settings.tres each time before to launch Godot

**Comment by akien-mga** [comment]
Confirmed reproducible on Linux with Godot 3.0, working on it.

**Comment by akien-mga** [comment]
Simple test that reproduces the issue with `ConfigFile`:
```
	var accented = "/path/to/héllo"
	
	var cfg = ConfigFile.new()
	cfg.set_value("test", "projects/" + accented.replace("/", "::"), 42)
	cfg.save("res://test.cfg")
	
	# Load from scratch
	cfg = ConfigFile.new()
	cfg.load("res://test.cfg")
	print(cfg.get_section_keys("test"))
	print(cfg.get_value("test", "projects/" + accented.replace("/", "::")))
```
prints:
```
[projects/::path::to::hÃ©llo]
ERROR: get_value: Couldn't find the given section/key and no default was given
   At: core/io/config_file.cpp:90.
Null
```

**Comment by akien-mga** [comment]
Here's a basic project that reproduces the bug in `ConfigFile` as shown above: [bug_6888_unicode.zip](https://github.com/godotengine/godot/files/1753911/bug_6888_unicode.zip)

I've traced the issue back so far to:
- Here `assign` will already be `Ã` instead of `é`:
https://github.com/godotengine/godot/blob/e4213e66b2dd8f5a87d8cf5015ac83ba3143279d/core/io/config_file.cpp#L184
- Same here:
https://github.com/godotengine/godot/blob/ac2a9bb26718f5e5a699eb24ca0868ede55e7f0d/core/variant_parser.cpp#L1501
- Need to go further up in `CharType` and `FileAccess` stuff and there I'm totally clueless...

CC @hpvb to the rescue :P

**Comment by akien-mga** [comment]
As seen in #16850, this seems to be mitigated if the strings read by VariantParser are quoted - so maybe we just need to ensure that strings which non-ascii characters are always quoted when written to a text file.

**Comment by akien-mga** [comment]
This diff makes my above reproducer work fine:
```diff
diff --git a/Node2D.gd b/Node2D.gd
index 73e6bbc..6a9dc45 100644
--- a/Node2D.gd
+++ b/Node2D.gd
@@ -4,7 +4,7 @@ func _ready():
        var accented = "héllo"
        
        var cfg = ConfigFile.new()
-       cfg.set_value("test", accented, 42)
+       cfg.set_value("test", '"' + accented + '"', 42)
        cfg.save("res://test.cfg")
        
        # Load from scratch
diff --git a/test.cfg b/test.cfg
index 326d10b..cc911bc 100644
--- a/test.cfg
+++ b/test.cfg
@@ -1,3 +1,3 @@
 [test]
 
-héllo=42
+"héllo"=42
```
