### ISSUE TITLE
Ability to visually parent Controls to a 3D node

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#6893]
The ability to visually parent Controls to a 3D (Spatial) node, that is, moving a Control automatically to "follow" a 3D node would be very useful. It surely can be done by code currently, but having it in core would make it easier (and likely faster when there's lots of Controls to move).

This would be useful for player name tags or other kinds of visual information that are "attached" to an object in a 3D world, without requiring a depth-scaled rendered viewport containing the Control.

**Comment by eon-s** [comment]
Something that works like Sprite3D but for controls

**Comment by Calinou** [comment]
This is still relevant as of https://github.com/godotengine/godot/commit/3ad9e4740c35ec20fdd6942f13047ebd53ea203e, but it's possible to manually implement this by using `Camera.unproject_position(Vector3 world_point)`. Should this be closed then?

**Comment by eon-s** [comment]
I would like a Panel3D that simplifies the setup of 3D UI.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
