### ISSUE TITLE
Color picking not working on Windows

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#68979]
### Godot version

4.0 11e1c83

### System information

Windows 10 x64

### Issue description

![](https://user-images.githubusercontent.com/2223172/202451788-ac56bfcc-8049-4bf6-83fd-79854004c12d.gif)
The color never changes. Not for the property, nor for the button. According to the discussion in #63886, this is a Windows-specific issue.

### Steps to reproduce

1. Be on Windows
2. Open ColorPicker
3. Click the eyedrop button
4. Try to pick some color

### Minimal reproduction project

N/A

**Comment by duianto** [comment]
v4.0.beta5.official [89a33d28f], Win 10 22H2

It does work if the Color popup is closed with `esc` after clicking on the eye dropper icon:
- click on the color property in the inspector to open the color popup
- click on the eye dropper icon
- press `esc` to close the color popup
- click on a new color

**Comment by Sauermann** [comment]
While investigating this issue I tracked it to this:
https://github.com/godotengine/godot/blob/6318320c04f348eee1df7a5dae3bad540ef1fdcc/scene/gui/color_picker.cpp#L1408-L1429
Is it possible, that this is related to the Control->Window conversion?

I verified, that this problem also exists in v4.0.alpha1.official [31a7ddbf8] on Linux X11:
- I can't pick colors
- The color under the mouse cursor is not used

In v4.0.beta.custom_build [6318320c0] on Linux X11:
- I can't pick colors
- The color under the mouse cursor is used for previewing it in the color-picker (so at least some kind of progress has happened since v4.alpha1).

**Comment by stmSi** [comment]
I saw weird things happening while debugging `ColorPicker::_screen_input`. The first Mouse Click Event doesn't not enter yet... after u click again.... two clicks events enter continuously.

1. First comment out this so that u can capture screen click events as long as u want. (in `_notification`)

![image](https://user-images.githubusercontent.com/32661049/209582017-6ba3f85c-ab0d-4d01-aa83-bd9e3e829491.png)


-------------------------------------------------------
2. insert these lines (in `_screen_input`)

![image](https://user-images.githubusercontent.com/32661049/209582150-b315f94e-1304-4549-b11b-1e348134f3ed.png)


-------------------------------------------------------
3. select color picker and click it. nothings happens. click again... "LEFT" will print 2 TIMES
 
![image](https://user-images.githubusercontent.com/32661049/209582391-fa7dc496-2171-4715-95b8-84a77627130e.png)

-------------------------------------------------------
4. Color will set successfully.

**Comment by nezvers** [comment]
Godot 4 Beta 15 on Windows eyedrop does not pick a color.

**Comment by Sauermann** [comment]
The relevant code section has this comment:
`// TODO: show modal no longer works, needs to be converted to a popup.`

So I did some experiment with popups. Current status is that I ran into the problem that Popups can not be made transparent reliably (previously the Control `screen` simply was transparent). So I believe, that it is currently not possible to solve this by a simple replacement Control->Window.

**Comment by JohanAR** [comment]
I've considered a couple of alternative ideas, that may or may not work in reality..

1) Use some OS-specific code for eye dropping a colour instead of trying to implement it using Godot objects.
2) Hide the ColorPicker popup while using the eyedropper, and open it again after the user has clicked the main window. Possibly with some kind of decoration, like a thick frame around the window, or a small notification e.g. "click to pick a colour, or Esc to cancel", to give some kind of indication that the popup didn't just disappear.
3) Remove eye dropper. Maybe people aren't using it anyway?
