### ISSUE TITLE
GDScript 2.0: lambda function does not change captured variable after function exists.

### ISSUE THREAD

**Issue by muchitto** [godotengine/godot#69014]
### Godot version

4.0 beta 5

### System information

MacOS 13.0.1

### Issue description

When trying to use a lambda function, it seems it does not change an outer variable after the function has ended. I don't know if this is by design, but it seems kinda weird.

### Steps to reproduce

This occurs in this small snippet:

```gdscript
func _ready():
	var test_var := "first"
	var fn := func():
		test_var = "second"
		print(test_var)
	
	print(test_var)
	fn.call()
	print(test_var)
```

prints out:

```
first
second
first
```

So it changes the variable until the function exits.

### Minimal reproduction project

Just run the above.

**Comment by Mickeon** [comment]
This is by design. It's going to be probably documented down the line (as it should be) in Callables' documentation, like it has been noted in [GDScript's Basics](https://github.com/godotengine/godot-docs/blob/master/tutorials/scripting/gdscript/gdscript_basics.rst):
> Lambda functions capture the local environment. Local variables are passed by value, so they won't be updated in the lambda if changed in the local function:
```GDScript
var x = 42
var my_lambda = func(): print(x)
my_lambda.call() # Prints "42"
x = "Hello"
my_lambda.call() # Prints "42"
```

**Comment by muchitto** [comment]
Ok, peculiar.

**Comment by Mickeon** [comment]
Do note that Variants passed by reference (Objects, Dictionaries and Arrays) are also passed by reference in the lambda if that is what you needed this for.

**Comment by muchitto** [comment]
Ok, right. So this is a possible workaround:

```
func _ready():
	var test_var := { "thing": "first" }
	var fn := func():
		test_var.thing = "second"
		print(test_var.thing)
	
	print(test_var.thing)
	fn.call()
	print(test_var.thing)
```

Seems just a little bit peculiar and "footgunish" as it works differently in majority of languages and when I modify the variable inside the lambda, it modifies it inside the function so I did not gather until later that it does not modify the actual variable outside, but I guess this is just another one of those things you have to keep in mind.

**Comment by KoBeWi** [comment]
What's the point of lambdas modifying local variables, other than *maybe* locally reusable code?

**Comment by YuriSizov** [comment]
> What's the point of lambdas modifying local variables, other than _maybe_ locally reusable code?

Here's a very specific case. Consider this undo redo system where you want to know some id generated by do to use in undo:

```gdscript

var variation_value := -1

state.add_do_action(func() -> void:
	variation_value = Controller.clone_pattern_nocheck(pattern_idx)
)

state.add_undo_action(func() -> void:
	Controller.delete_pattern(variation_value)
)
```

To echo the above comment, it's not something that you cannot work around, but it's a very natural thing to expect to work. This limitation is only true for value types anyway. Reference types, being reference types, work as you'd expect it. So changing `variation_value` here to something like this fixes the problem:

```gdscript

var variation_value := { "id": -1 }
````

But again, it's unintuitive from looking at the original code that the captured local variable in two lambdas is actually two new, unrelated variables.

**Comment by The3DWizard** [comment]
For me the problem is that there are no inner functions in GDScript, so I use lambda functions for inner functions. And when using those lambda functions I would like to access outer variables, which this design decision makes very cumbersome. So I would definitely vote for lambda functions modifying the actual outer value types. Using a lambda function referencing an outer variable in a different context should raise an error. For me that would be the more logical way to implement this.

**Comment by solodeveloping** [comment]
Most languages use lambda with out of scope capturing.

I would say that 95% of people using lambdas do this with this intention in mind.

I do not quite understand why this is "intended" and "not planned".

"Local variables are passed by value" => this is so counter intuitive, everything is passed by reference except for this? Is it even a thing, "by value" in Gdscript? (by that, I mean: is it serialized/deserialized? With it's own caveats)

It feels like "passing by value" is the worst possible choice between not allowing it, passing by reference and passing by value (idk).

Edit: in the end, I'm using an inner class, it makes the declaration maybe cleaner, I don't think you would want to create an inner class every time you want to use a lambda though, especially since there are no local inner classes, and it defeats the purpose 🤷‍♂️

Edit 2: it's so unclear, I have an array, I do a pop_back, and it's really unclear whether or not it's popped or not, there are no warnings, no errors, unlike for the variables

**Comment by solodeveloping** [comment]
Actually, if it's using duplicate internally, you expose yourself to every issues involving duplicate() (@export, _init etc)

**Comment by KoBeWi** [comment]
It doesn't duplicate anything. Value types (int, Vector2, Color) are captured by value, reference types (Array, Object) are captured by _copy_ of reference (I think), which still points to the same object. Not sure about PackedArrays, they are value types, but GDScript handles them differently.

**Comment by solodeveloping** [comment]
> captured by copy of reference

For me, it sounds like "passed by reference"; I'm not sure I understand

So, I did a few tests:

Define an object, initialize it outside, modify it inside the lambda => ✅ it will be modified outside of the lamba, does not need to be a parameter, a value properties (String) also works

Define an object, initialize it inside the lambda => ❌ will not be initialized outside of the lambda (and there is a warning)

Value types (String etc) => ❌ will not be modified outside of the lambda (there is a warning)

**Comment by solodeveloping** [comment]
And it does not "duplicate" anything, everything was fine on this end.

**Comment by KoBeWi** [comment]
> For me, it sounds like "passed by reference"; I'm not sure I understand

Well, your examples illustrate that.

```GDScript
var variable = something

var lambda = func():
	var captured = variable
	captured.some_call()
```
In this simple example `variable` is a variable with some value, `captured` is a variable with copy of that value.

If you assign an object to the `variable`, its value will be a pointer to object (on C++ level, GDScript doesn't have pointers).
Then `captured` will be a copy of that value, so a copy of the pointer, but still pointing to the same object.

If you assign a different object to `captured`, the original `variable` will not be modified, because `captured` is a different variable.
