### ISSUE TITLE
tree control ensure_cursor_is_visible issue

### ISSUE THREAD

**Issue by alex44444444** [godotengine/godot#691]
when tree.set_column_titles_visible(true), selection hides under column title after
ensure_cursor_is_visible(), when scrolls to top

**Comment by akien-mga** [comment]
Since this was reported already a year ago and there is relatively little information on what the bug is (a screenshot and example scene could have been useful), archive it for now. Feel free to reopen an issue with more details if you still experience this problem in current Godot 2.0 alpha nightly builds.
