### ISSUE TITLE
Vulkan: LightmapGI with Environment Mode set to a value other than Disabled exhibits light leaking through one-sided surfaces

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#69126]
*Related to https://github.com/godotengine/godot/issues/63437 (but not the same, as that issue is about general light leaking).*

### Godot version

4.0.beta6

### System information

Fedora 36, Vulkan Forward Plus, AMD Radeon RX 6900 XT

### Issue description

LightmapGI with Environment Mode set to a value other than Disabled exhibits light leaking, especially through one-sided surfaces. This light leaking is caused by environment lighting, which spreads incorrectly through corners.

While this can be worked around to an extent by ensuring all surfaces are two-sided (manifold), one-sided surfaces are fairly common in level design for optimization reasons.

Other things I've tried to no avail:

- Increasing/decreasing Bias on LightmapGI
- Disabling **Use Denoiser**
- Enabling **Interior**
- Increasing bake quality to **Ultra**

Environment Mode: Disabled | Environment Mode: Scene
-|-
![2022-11-24_18 13 37](https://user-images.githubusercontent.com/180032/203838323-9d30cd14-189a-4d75-b959-ec6726f89777.png) | ![2022-11-24_17 58 22](https://user-images.githubusercontent.com/180032/203837659-7f76d745-d2d0-4f14-a56c-2d0836da2d14.png)
![2022-11-24_18 13 44](https://user-images.githubusercontent.com/180032/203838325-cec5d68a-a9f5-4480-bafa-bc1d4c7bf911.png) | ![2022-11-24_17 58 41](https://user-images.githubusercontent.com/180032/203837663-52bf143c-c521-471c-9848-95a83a009f76.png)
![2022-11-24_18 13 50](https://user-images.githubusercontent.com/180032/203838328-dd6e3ce1-6a9e-4dc0-86db-7bb3b6442ddb.png) | ![2022-11-24_17 58 57](https://user-images.githubusercontent.com/180032/203837665-cd46fbff-6c0d-43c4-a5de-7b6a64253cc5.png)
![2022-11-24_18 13 56](https://user-images.githubusercontent.com/180032/203838332-ec382a1b-e071-4b28-ba51-06d231e1a51f.png) | ![2022-11-24_18 06 15](https://user-images.githubusercontent.com/180032/203837667-2a4b07e7-631b-4dbe-9f77-9f3f8b0ea8d2.png)

(The little bit of light leaking that remains on the 3rd screenshot is from the shadow map, not the lightmap.)

### Steps to reproduce

- Import a 3D scene with its **Light Baking** property set to **Static Lightmaps**.
- Add a DirectionalLight3D node and WorldEnvironment.
- Add a LightmapGI node.
- Bake lightmaps.

### Minimal reproduction project

[test_lightmapgi_leak.zip](https://github.com/godotengine/godot/files/10086490/test_lightmapgi_leak.zip)

**Comment by WickedInsignia** [comment]
This seems to be happening with direct light GI too. Here's a manifold structure with thick walls and environment set to "disabled" in the bake. The directional light is set to dynamic, so this is the GI leaking.
![LightmapLightLeak_Godot4](https://user-images.githubusercontent.com/70243134/226510574-c568a1e4-aecf-4edf-8f04-ed467c7f0e74.jpg)

[LightmapLeaking.zip](https://github.com/godotengine/godot/files/11024770/LightmapLeaking.zip)

**Comment by DarioSamo** [comment]
My theory was right, this is a fairly simple fix.

A half pixel offset needs to be added to gl_Position in the rasterization step.
```glsl
vec2 half_pixel_offset = vec2(-1.0f, -1.0f) / vec2(params.atlas_size.xy);
```

Before
![image](https://github.com/godotengine/godot/assets/538504/9d884417-2fc9-4389-bf2f-cd250e4c0414)

After
![image](https://github.com/godotengine/godot/assets/538504/96c80adf-a348-4f42-9ca3-09849a7caf2f)

After of the scene above.
![image](https://github.com/godotengine/godot/assets/538504/a8424de8-9152-4a5d-b335-d9472e89b0a8)

There's some leaking on the last one but to be honest I don't trust the denoiser (OIDN) is doing a good job there, as it exhibits no leaking when the denoiser is off (which wasn't the case before).

![image](https://github.com/godotengine/godot/assets/538504/5a66f159-e16a-48bc-a1b9-3cb2a20e694c)

I'll open a PR with this change.

**Comment by jeffhube** [comment]
I am seeing significantly more leaking with this change. Should I open a new issue? Example project is attached.

I have also confirmed this behavior when cherry-picking this change onto 4.2-dev5.

![image](https://github.com/godotengine/godot/assets/1283264/5f6b0f8d-26b1-4c38-814f-be999505ecf9)
![image](https://github.com/godotengine/godot/assets/1283264/2234e676-fd9a-45e1-91b3-0ce61d601be0)

[LightmapTest.zip](https://github.com/godotengine/godot/files/12704942/LightmapTest.zip)

**Comment by Calinou** [comment]
The scene in the MRP doesn't load. Don't remove the `.Lmbake` and `.exr` files without clearing the LightmapGIData from the LightmapGI node first.

**Comment by DarioSamo** [comment]
You sure it's not just because this thing is built out of several planes with slight protrusions towards the corners that can get light?

![image](https://github.com/godotengine/godot/assets/538504/70ca4135-5241-4bfe-a20e-156d1a51b036)

The texel resolution is also so low to the point it makes this even worse. If you increase the lightmap resolution you can see the issue pretty clearly fix itself.

![image](https://github.com/godotengine/godot/assets/538504/74a75c31-50d0-48ff-93cc-0b8facb8cf81)

You should model a proper inside out cube if you don't want leaks like that.

**Comment by WickedInsignia** [comment]
You'll want to be careful that you have enough texel density in these tests that the leak isn't occurring due to overlap in the lightmap image itself. That won't happen with a huge amount of padding between UV islands and a high texel density.
Intersecting planes pose an issue because if the edge of the planes are catching any light from outside, the low resolution of the lightmap will cause the light to bleed to the inside a lot more than it actually should physically.

This test would be better done with a cube with inverted normals, or a room with one wall removed and some thickness on the remaining walls.

**Comment by DarioSamo** [comment]
I'm definitely a bit puzzled as to how it's even generating positions at the very edge of the planes at least at such low resolution, the half pixel offset is exactly meant to prevent that. I get the feeling there's some other mechanism at play on this scene.

At least all of these planes are just using a pretty plain independent UV2. I'll take a look at how the position texture is being generated next week.

**Comment by jeffhube** [comment]
Here is a version with an inverted cube. [LightmapTestCube.zip](https://github.com/godotengine/godot/files/12705472/LightmapTestCube.zip) I'm getting pretty similar results.

|4.2-dev5 / before change / 0.2 texel size|4.1.2-rc1 / after change / 0.2 texel size|
|-|-|
|![image](https://github.com/godotengine/godot/assets/1283264/867d1f3f-3e78-4202-837d-25266c013b7d)|![image](https://github.com/godotengine/godot/assets/1283264/37da1dd1-a65a-4bcb-b2b3-5be3ffff87f8)|

|4.2-dev5 / before change / 0.05 texel size|4.1.2-rc1 / after change / 0.05 texel size|
|-|-|
|![image](https://github.com/godotengine/godot/assets/1283264/a70fbcb1-d45b-4e78-966c-5e0af3e78037)|![image](https://github.com/godotengine/godot/assets/1283264/ef4336fd-ef8a-495f-b0bb-fedc63ad551c)|

Increasing the texel density does help, though even with an increased texel density there is less leaking before this change.

I thought it was interesting how when you look at the lightmap textures for 4.2-dev5 (included in each screenshot above), it is only the top left edges that leak. The same is true for the plane version as well, where every face is on its own slice. On 4.1.2-rc1 with this change, there is uneven leaking on all 4 edges. Each face of the cube (or each plane) has two adjacent edges that leak worse than the other two.

**Comment by DarioSamo** [comment]
Thanks for testing with the cube, that makes it easier to rule out the other possibilities.

> I thought it was interesting how when you look at the lightmap textures for 4.2-dev5 (included in each screenshot above), it is only the top left edges that leak. The same is true for the plane version as well, where every face is on its own slice. On 4.1.2-rc1 with this change, there is uneven leaking on all 4 edges. Each face of the cube (or each plane) has two adjacent edges that leak worse than the other two.

Yes, this is why I'm inclined to believe this is not exactly a regression but uncovering some other bug where the other edge can somehow retrieve the position of the edge of the polygon, especially because one of the original test scenarios was very similar to this. In theory with the half-pixel offset, the rasterizer should never be writing coordinates that perfectly align like that when it's used... but something seems to be failing here.

I'll take a look at it on Monday by debugging the output position texture in the rasterization step.

**Comment by DarioSamo** [comment]
I've been giving this a look and I'm unable to determine so far what's the reason behind the error. The half pixel offset is clearly doing the behavior I want it to do in proper meshes, but this mesh in particular seems to have something in its generation of the UV2 that makes the rasterization never generate the coordinate from the center as it should. Whenever I look at the position texture that it outputs, the values are pretty much at the very edge of the cube.

The size in the atlas itself is very weird and uneven. I noticed this was generated via ArrayMesh. Can we reproduce this behavior with something like a regular box instead? I'm just not sure where the difference lies yet that causes this behavior compared to regular scenarios.

**Comment by jeffhube** [comment]
Ah, it seems that an obj import works fine. [LightmapTestObj.zip](https://github.com/godotengine/godot/files/12719916/LightmapTestObj.zip)

|4.2-dev5 / before change / 0.2 texel size|4.1.2-rc1 / after change / 0.2 texel size|
|-|-|
|![image](https://github.com/godotengine/godot/assets/1283264/25639928-88d6-4962-bf86-0be72f6c33fe)|![image](https://github.com/godotengine/godot/assets/1283264/7e34b7ea-f427-43a0-ab19-7c39e82cec07)|

Before I was using PlaneMesh and BoxMesh, so maybe there is something funny going on there with the uv2 generation.

**Comment by Calinou** [comment]
cc @BastiaanOlij, as he implemented UV2 generation in primitive meshes.

The default padding is defined to 2 pixels, but maybe it's too high/low? You can configure it in the PrimitiveMesh resource inspector.

**Comment by DarioSamo** [comment]
> Ah, it seems that an obj import works fine. [LightmapTestObj.zip](https://github.com/godotengine/godot/files/12719916/LightmapTestObj.zip)
> 4.2-dev5 / before change / 0.2 texel size 	4.1.2-rc1 / after change / 0.2 texel size
> ![image](https://user-images.githubusercontent.com/1283264/270490030-25639928-88d6-4962-bf86-0be72f6c33fe.png) 	![image](https://user-images.githubusercontent.com/1283264/270490051-7e34b7ea-f427-43a0-ab19-7c39e82cec07.png)
> 
> Before I was using PlaneMesh and BoxMesh, so maybe there is something funny going on there with the uv2 generation.

Very interesting indeed. Sounds like this might warrant a close inspection of what UV2 values the primitive mesh ended up with.

**Comment by jeffhube** [comment]
I took a quick look at what is being passed to LightmapperRD::add_mesh() when lightmapping an obj plane and when lightmapping a PlaneMesh. The lightmapper generated size 16x16 slices for each plane. In summary, there's a half pixel offset difference between the two (not caused by this change).

For an obj plane, the image size was 14x14 and the uvs go from `[0.035714, 0.035714]` to `0.964286, 0.964286`.
![image](https://github.com/godotengine/godot/assets/1283264/b3332e96-9ef9-4fc4-91dd-8742098577c7)

For a PlaneMesh, the image size was 12x12 and the uvs go from `[0, 0]` to `[0.833333, 0.833333]`. The UV2 Padding was 2 so that explains the unused pixels on the bottom and right.
![image](https://github.com/godotengine/godot/assets/1283264/c52f188b-88c8-4e6a-94c4-5fc73c3540c1)

**Comment by DarioSamo** [comment]
@jeffhube Thanks for the investigation.

I think what you've shown so far might explain why I've seen primitive meshes sometimes linearly interpolate the light-map on one edge of a shape and wrap around to the other side when rendering.

We might need more eyes from this on from more experienced parties as now I'm not entirely sure if it's the model importer the one that is wrong or the primitive generation depending on what else the engine expects. However, I'm inclined to say the OBJ is correct, as it matches the behavior of what I've seen happen in other engines and the half pixel offset is required when dealing with linear interpolation.

**Comment by BastiaanOlij** [comment]
It's been a long time since I last looked into this but the primitive meshes take a fairly straight forward approach. It calculates the size of the image required based on the dimensions of the primitive shape, taking the texelsize into account. Then adds the required margins to this. 

The margins are indeed added just to the right and bottom edge, so that bottom image for the plane is indeed correct. 

For a box it will lay out a grid of 2 x 3 faces adding the margins again at the right and bottom edges to space them out.

You can see the UV unwrap with the mesh instance selected, pressing the Mesh button and then selecting View UV2:

![image](https://github.com/godotengine/godot/assets/1945449/c0121d72-e2a7-4f20-b493-49a6e63f4654)

We really should add a grid view to this :)

If we want a border on the left and top, we could change the logic fairly easily by just adding a single texel to all UV coords.
