### ISSUE TITLE
WorldEnvironment makes adjustments to editor dropdowns and dialogs if background mode is set to Canvas

### ISSUE THREAD

**Issue by ItsDaBenji** [godotengine/godot#69122]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

4.0-beta6

### System information

Windows 10, mobile renderer

### Issue description

When messing with the world environment node in 2D, I was adding some bloom effect to my game, and the editor itself now has bloom
![image](https://user-images.githubusercontent.com/71361474/203828525-13f462d1-8214-40eb-abae-e97714576e93.png)
![image](https://user-images.githubusercontent.com/71361474/203828607-52fb5dfe-b6f3-4889-b2f6-8a3c3ece2d68.png)
![image](https://user-images.githubusercontent.com/71361474/203828652-e95b2fad-b076-4cf5-ac59-d2a85213596a.png)

### Steps to reproduce

Create a 2D scene
Add a world environment node
Set the Background mode to "Canvas"
Enable "Glow"
Increase both the "Strength" and "Blend" values
For best results, set "Blend mode" to "Replace"
Open up any sub menu (I discovered this by clicking to change the Blend Mode again, but the project settings is also effected by the post processing)

### Minimal reproduction project

[2DPostProcessingErrorProject.zip](https://github.com/godotengine/godot/files/10086139/2DPostProcessingErrorProject.zip)

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/52467.

**Comment by snougo** [comment]
I can reproduce issue in Godot4 beta6 on Mac

**Comment by clayjohn** [comment]
This issue is deceptively tricky and may require quite a bit of work to fix. 

Primarily it comes from how we handle editor drawing. 
1. The environment from the user's scene is also applied to the root Viewport (i.e. the editor itself)
2. We instruct the root Viewport to ignore the environment by setting the ``disable_environment`` flag
3. In Godot 4.x, we have popup Windows which are independent from the root (or at least, have their own Viewport)

Unfortunately, the ``disable_environment`` flag does not carry over to child Viewports so the popup windows use the environment even though they shouldn't. 

I'm not sure what an ideal fix would look like. On the one hand, we can probably make child Viewports inherit the ``disable_environment`` flag from their parents, but that may not be useful and may cause its own problems.

**Comment by therealcreativesam** [comment]
Had same issue, came to see if it was already reported, guess this answers my question. :)

**Comment by 2fd5** [comment]
Still can reproduce with Godot 4.0.beta14 on Macbook Air M1
