### ISSUE TITLE
Character3D capsule collisionShape3D getting stuck in trimesh heightmap planes

### ISSUE THREAD

**Issue by StoreBoughtRocketGames** [godotengine/godot#69131]
### Godot version

4.0 dev Beta 6

### System information

Windows 10, Vulkin

### Issue description

My Character3D player is getting stuck on trimesh collision surfaces, basically anything that isn't a flat trimesh plane. I tried to make a heightmap in Blender, and trimesh the surface to use as a landscape, and found it was basically unusable.

It happens with capsule shapes, and (I believe, but need to confirm) also happens with cylinder shape collisions, but seems to be not happening at all for boxShape collisions. I almost can't move at all when I use a capsule collision shape. There may be some relation to issue #46712, but this seemed different enough to warrant a new bug report. I searched for this issue, and couldn't find anything, so hopefully I'm not duplicating a known issue.

### Steps to reproduce

 Run around terrain (ASDW), and you should get stuck almost right away. To get unstuck, you can push spacebar to jump, which you can use to move around the level. Change to a boxShape, and the issue goes away. I think the issue is also present to some extent with the cylinder collision shape, but it happens less frequently.

### Minimal reproduction project

[TestProject.zip](https://github.com/godotengine/godot/files/10086914/TestProject.zip)

**Comment by StoreBoughtRocketGames** [comment]
This doesn't occur in Godot 3.5.1.  I'm able to run around in the same scene just fine. Although, I get the capsule collision clipping through the terrain, it doesn't get stuck. So there is some weirdness with the capsule collision in 3.5.1.
Minimal reproduction project
[TestProject_3_5.zip](https://github.com/godotengine/godot/files/10087989/TestProject_3_5.zip)

**Comment by snougo** [comment]
I got same issue and it caused by ConcavePolygonShape3D, when I used ConvexPolygonShape3D, there is not such problem at all.




https://user-images.githubusercontent.com/64188282/203952212-6094e05a-75ff-4125-a30a-d3824b251bf3.mov




https://user-images.githubusercontent.com/64188282/203952316-1f97f02c-14a6-4a02-bda7-fe10fe29d420.mov

**Comment by Gamepro5** [comment]
This seems to be due to the same underlying issue as https://github.com/godotengine/godot/issues/69137

It seems to be a tracked issue, but hasn't been fixed yet despite it's severity. I suspect that the the issue of trimesh edges causing incorrect collision normals causes

https://github.com/godotengine/godot/issues/46712
https://github.com/godotengine/godot/issues/69131
https://github.com/godotengine/godot/issues/69137

There are probably more I'm missing.

**Comment by StoreBoughtRocketGames** [comment]
Any idea why the behavior is different from 3.5.1 to 4.0? I haven't looked through engine code myself as I'm not familiar. I'm fairly certain I could figure out how to fix it if I compared the code from 3.5.1 to this one. But, probably not a good use of my time since I've never contributed, nor compiled the engine.

**Comment by josheb** [comment]
I'm seeing this sometimes with a capsule shape.  The FPS template in the repository is my starting point.
[godot_physics_1.webm](https://user-images.githubusercontent.com/3301884/205451970-d56fde28-5c15-452c-a218-92984ab9fed3.webm)
Axis alignment seems to be a factor.  If I run straight at it it will stick much of the time, but if I rotate a little it slides past.

**Comment by rburing** [comment]
Related to (or maybe even the same as) https://github.com/godotengine/godot/issues/69683.

**Comment by rburing** [comment]
The main problem in the minimal reproduction project is the non-uniformly scaled capsule collision shape on the character. Since 4.0 beta 15 the editor (and the class reference) warns against using non-uniform scaling for 3D physics objects (see https://github.com/godotengine/godot/pull/67847), since such transformations can't be supported properly by the physics engine.

Using a capsule collision shape with uniform `(1, 1, 1)` scale (and the radius and height updated to approximately match the previous transformed shape) fixes the issue: [TestProject-uniformscale.zip](https://github.com/godotengine/godot/files/10498656/TestProject-uniformscale.zip).
