### ISSUE TITLE
CanvasItem with clip_children in any enabled mode draws black if all children are invisible

### ISSUE THREAD

**Issue by Giometric** [godotengine/godot#69179]
### Godot version

v4.0.beta6.official [7f8ecffa5]

### System information

macOS Ventura 13.0.1, Radeon Pro 560X (MacBook Pro 15" 2018)

### Issue description

If a CanvasItem-inheriting object (Sprite2D, Polygon2D, etc) has `clip_children` set to "Clip Only" or "Clip + Draw", the entire object will render opaque black if either it has no children at all, or if all its children have `visible` set to `false`. Setting the alpha of the `modulate` color of the children is the same as setting `visible == false`, however setting `self_modulate` does not produce this effect, and thus can be used as a workaround.

### Steps to reproduce

- In a new or existing scene, create a CanvasItem-inheriting object, such as a Sprite2D / Polygon2D.
- Assign a texture / otherwise ensure it has some clippable area to draw.
- Create a child on this object that is also a CanvasItem-inheriting object, such as a Sprite2D / Polygon2D.
- Set `clip_children` on the parent object to "Clip Only" or to "Clip + Draw".
- Toggle visibility of the child object and observe the result.

https://user-images.githubusercontent.com/4956530/204049323-9af1e633-23a2-4e1a-a0bd-3a6209926deb.mov

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
It seems that this issue also occurs when the child node is not in the view.

https://user-images.githubusercontent.com/30386067/204079025-cb5e5d11-78b7-46f6-96d3-75e63a7d553e.mp4

**Comment by Rindbee** [comment]
I looked into this issue and the presumable cause is that the group owner has not set `group_owner` when there are no visible child nodes.


https://github.com/godotengine/godot/blob/690199b7dddd784b435e6ce71365256b29285fe8/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L1435
Adding the following code to the location above seemed to resolve it.
```cpp
// The group owner has not set group_owner.
if (ci->canvas_group_owner == nullptr && ci->canvas_group) {
	ci->canvas_group_owner = ci;
}
```

**Comment by felbecker** [comment]
Run into this in 4.0 RC 1.

It's problematic in situations where the number of clipped children is dynamic and can reach zero. It does not help to set the clip mode to CLIP_CHILDREN_DISABLED in that case, because apparently there is a slight and (to me) counter-intuitive difference in shading compared to CLIP_CHILDREN_AND_DRAW which will cause a noticeable flickering. 

The only workaround I can think of for now is to add a visible canvas item (like a single pixel) as a child and always keep it in the viewport. This is however not really practical of course.
