### ISSUE TITLE
clip children's parent-child behavior inverts when inside a canvas group

### ISSUE THREAD

**Issue by Gnumaru** [godotengine/godot#69307]
### Godot version

4.0.beta6

### System information

windows 10 x64, nvidia graphics

### Issue description

Usually, a parent with clip_children clips the children, preventing the rendering of anything outside the parent renderable area.
But, when the parent/child pair is put inside a canvas group, the relationship gets reversed: everything inside the parent is not rendered, only what's outside get's rendered.

https://user-images.githubusercontent.com/5783414/204355476-c173ce61-8b47-4c4f-a3d3-1af2ed8e5fc3.mp4

### Steps to reproduce

Open attached project. Open main.tscn. Try draggin the parent sprite outside of the canvas group, and then inside again.

### Minimal reproduction project

[CanvasGroupInvertsClippingBehaviorBetweenParentAndChild.zip](https://github.com/godotengine/godot/files/10106538/CanvasGroupInvertsClippingBehaviorBetweenParentAndChild.zip)

**Comment by clayjohn** [comment]
What's happening here stems from a limitation with CanvasGroup/clip_children. They both rely on using the backbuffer. Since there is only one backbuffer, you can't nest multiple CanvasGroups, nor can you nest multiple nodes with clip_children enabled. For the same reason, you also can't next CanvasGroups with nodes with clip_children enabled.

**Comment by KoBeWi** [comment]
[This was recently documented.](https://github.com/godotengine/godot/pull/68948)
