### ISSUE TITLE
Add an inverse to `object_set_instance`

### ISSUE THREAD

**Issue by antonWetzel** [godotengine/godot#69378]
### Godot version

4.0.dev (7f8ecff) (Beta 6)

### System information

Windows 11

### Issue description

Own C# Bindings for GDExtension

If I construct a C#-Object `<<ClassName>>` which extends a Godot-Object I use `object_set_instance` to combine both. I return the Godot-Object back to the Engine so everything works.

```csharp
static unsafe IntPtr CreateObject(IntPtr userdata) {
	var instance = new <<ClassName>>();
	return instance._internal_pointer; //pointer to a godot-object
}
```
If I get a `<<ClassName>>` from the Engine (assign it in the Editor, ...), I get the pointer to the Godot-Object, but I need the C#-Object.

I see no obvious way to do that. Currently I use pointer arithmetic, which is dependent on the internal implementation of Object

```csharp
public static <<ClassName>> Construct(IntPtr ptr) {
	ptr = *(IntPtr*)(void*)(ptr + 16); //change from godot-object-pointer to c#-object-pointer
	return (<<ClassName>>)ptr;
}
```

Did I miss something or would it be possibly to expose a `object_get_instance` to the GDExtension interface?

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
I think you want to use `object_set_instance_binding` and `object_get_instance_binding` for this (rather than `object_set_instance`).

All extension objects that are bound to Godot objects should use `object_set_instance_binding` (even ones that aren't custom classes from your extension), and `object_set_instance` should _additionally_ only be used on custom classes from your extension.

Given that this issue is rather old, I'm going to close it, but if there are any additional questions we can re-open it.
