### ISSUE TITLE
TileMaps, Sprites YSorting is not working properly

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot#69385]
### Godot version

4.0 beta 6

### System information

manjaro linux

### Issue description

I'm making a isometric 2D game, and even with YSort enabled the ysorting doesnt work!

cc @groud 

### Steps to reproduce

![image](https://user-images.githubusercontent.com/58845030/204780172-84e1ee83-1ae1-4a4b-bd6d-cac167ab34ba.png)
AnimatedSprite2D -> Tileset

![image](https://user-images.githubusercontent.com/58845030/204780186-1a16e333-ce2a-4d76-84d7-5af14cb096d4.png)
AnimatedSprite2D -> AnimatedSprite2D

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/10122397/MRP.zip)

**Comment by groud** [comment]
You need to enable Y-sort on the top node. Y-sort only works for common nodes in a hierarchy if they share a root node with Y-sort enabled. Also, you have to set the texture_offset (and Y-sort origin if you need to) on tiles.

https://user-images.githubusercontent.com/6093119/204788724-7f78e7c8-5610-4dfa-81a3-22c1d3dc6203.mp4

The only thing that seems is not working is setting the origin on animated tiles, while it works on normal sprites. But that's another bug which need its own report.

Closing as this is an expected behavior.
