### ISSUE TITLE
Enabling the new physical light unit in project settings will make spotlight not working

### ISSUE THREAD

**Issue by Intervel** [godotengine/godot#69436]
### Godot version

4.0 beta 6

### System information

Windows 11,  Rtx 3090

### Issue description

by enabling the new physical unit in project settings will make spotlight not working.

https://streamable.com/pmycmr

- i cranked the energy all the way to 16
- i maxed out the lumens.

when i hit play, spotlight not working

### Steps to reproduce

just download the files

### Minimal reproduction project

https://www.dropbox.com/scl/fo/4i2vmoywoqas264z2pn27/h?dl=0&rlkey=itabgvtkti5v5oc0s5gihqyd1

**Comment by clayjohn** [comment]
What are your exposure settings like?

Keep in mind the default environment is set to be exposed properly for an outdoor scene with a clear sky and a sun, so in order to make a spotlight visible you have to turn it's brightness up to a similar level to the sun or turn your exposure down to be consistent with your target brightness for the light.

**Comment by Intervel** [comment]
![1](https://user-images.githubusercontent.com/86478025/204982299-de81b2d6-de9f-4da0-8421-11db5df726d0.png)

@clayjohn 
you mean this?

**Comment by Intervel** [comment]
![Uploading 2.png…]()

**Comment by clayjohn** [comment]
Yes. Those are indeed set to properly expose a sun and clear sky. 

For reference an indoor scene would have an aperture of around 2-4. The docs have this information as well https://docs.godotengine.org/en/latest/classes/class_cameraattributesphysical.html#class-cameraattributesphysical-property-exposure-aperture

**Comment by Intervel** [comment]
@clayjohn 

its working now! 

sorry for bothering
