### ISSUE TITLE
IPV6 TYPE_ANY unused and unimplemented

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#6951]
**Operating system or device - Godot version:**
`master` branch

**Issue description** (what happened, and what was expected):
Currently, `IP_Address::TYPE_ANY` is unimplemented, as evidenced by experimentation (with both TCP and UDP servers) and some IRC logs:

```
[15:18:17] <fales> punto, akien, regarding ipv6 there are still a couple of things to be noted. I think: 1 - IP_TYPE_ANY does not work (tested with udp_packet_peer) 2 - IP_TYPE_ANY should be the default value for "listen".
[15:18:59] <fales> "p_address_type != IP_Address::TYPE_IPV4 && p_address_type != IP_Address::TYPE_IPV6" drivers/unix/packet_peer_udp_posix.cpp:124
```

Opening this since I lost an hour or so on #6933 without having this in mind... :laughing: 

Pinging @Faless and @punto- just in case.

**Comment by punto-** [comment]
IP_ANY was originall put there for the resolver, to say you don't care
about the type of address you want for the hostname. If it can be used on
other APIs then we can implement it, but otherwise it's just an invalid
parameter..

**Comment by bojidar-bg** [comment]
@punto- Well, the problem is that the editor currently listens on IPV4, while the debugger connects on _ANY, which gets picked up to be IPV6... and it can't connect at all afterwards.

**Comment by reduz** [comment]
Is it even possible to listen in both ipv6 and ipv4?

**Comment by bojidar-bg** [comment]
Well, apache seems to be able to do it, so... Maybe we would internally do two listens, but expose them as only one.

**Comment by punto-** [comment]
Are we sure that's the problem? I set it to listen by default on ipv6 on
windows, assuming the client was connecting via ipv6 because "localhost"
resolves to an ipv6 if available, and it still didn't connect. At least we
should make sure listening and connecting on ipv4 works correctly, so the
debugger works again, just force the connections to ipv4.. We can listen on
both if we open 2 servers, but it wasn't clear if it was possible to accept
both types of connection with the same socket, @faless was looking into that

**Comment by Faless** [comment]
> Is it even possible to listen in both ipv6 and ipv4?

Yes, it is possible, on any new system that I know off.
There is a socket option `ipv6_v6only` that defines that behavior (http://man7.org/linux/man-pages/man7/ipv6.7.html).
IPv6 sockets that support IPv4 mapped addresses (dual-stack socket) is allowed on modern linux kernels (2.4.21+/2.6+), windows (Vista and newer) and Mac (since OSX I think).
I read some FreeBSD kernels does not allow it, but I don't think it's a problem (again, it works on Mac).
See here for a brief intoduciton: https://en.wikipedia.org/wiki/IPv6#Dual_IP_stack_implementation 

Also, my patch is almost done, I'll PR it later tonight or tomorrow in the morning if everything keeps going as expected.
It will address both the debugger issue and the TYPE_ANY flag not not working.
I'm also trying to have TYPE_IPV6 to only accept IPv6 connections (which is not the default on most systems).

**Comment by bojidar-bg** [comment]
Yay, time to revert my local patches to godot :smiley:
