### ISSUE TITLE
Add a Polygon2D equivalent in 3D

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#6967]
**Operating system or device - Godot version:**
Linux, current master branch

**Issue description** (what happened, and what was expected):
As far as I know, there is no option to simply "mask" a Sprite3D like in 2D with a Polygon2D to prevent alpha overdraw (Does this even exist in 3D? [I've no idea of 3D :-)]).
I think the only option right now is to import a polygon mesh and add a texture to it. But this is not very convenient if you have to add 100+ Sprites.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 3ad9e47 : I don't think it's implemented yet.

**Comment by timoschwarzer** [comment]
Yes, 2D meshes in 3D are not available yet.

**Comment by Noshyaar** [comment]
CollisionPolygon (3D) can be edited directly in the viewport. We might be able to reuse this code to create 2D Polygons in 3D.

**Comment by Calinou** [comment]
CSGPolygon2D can now be used for this, but this is probably less efficient compared to having a dedicated Mesh type for use in MeshInstance.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
