### ISSUE TITLE
[C#] Bit field enums lack `[Flags]` attribute and thus they are stored/passed as `int` instead of enum

### ISSUE THREAD

**Issue by eumario** [godotengine/godot#69701]
### Godot version

4.0.beta.7

### System information

Any

### Issue description

A part of the Dotnet 6 re-write, has been to ensure that all Enumerations properties are properly using Enums, instead of int values.  However, found that SizeFlagsHorizontal and SizeFlagsVertical are not following the Enumeration usage for SizeFlags.  I have to cast the SizeFlag enum to an integer, in order to assign to SizeFlagsHorizontal, and SizeFlags.Vertical.

### Steps to reproduce

Write code to create a Control, and Attempt to Assign a SizeFlag enumeration to SizeFlagsVertical, or SizeFlagsHorizontal.

### Minimal reproduction project

See Notes above

**Comment by kleonc** [comment]
```csharp
Control c = new Control();

// (1) Doesn't work.
c.SizeFlagsHorizontal = Control.SizeFlags.Expand | Control.SizeFlags.ShrinkEnd;

// (2) Works.
c.SizeFlagsHorizontal = (int)Control.SizeFlags.Expand | (int)Control.SizeFlags.ShrinkEnd;
```

(1) would work if `Control.SizeFlags` enum would have `[Flags]` attribute and `Control.SizeFlagsHorizontal` property would be of type `Control.SizeFlags` instead of `int`.

I assume it's general problem with bit field / flag enums.

cc @neikeq @raulsntos Not sure whether it's intentionally made like that because of some limitation or whether it should be treated as a bug.

**Comment by raulsntos** [comment]
Most of the C# API is generated from ClassDB. We generate flag enums when the Core enum is registered with `BIND_BITFIELD_FLAG`, we have no way of knowing otherwise if the enum is meant to be used as a bitfield flag.

If `Control.SizeFlags` is meant to be a flag enum it should be fixed in Core, that would also fix it in the generated C# bindings.

It's unlikely to be fixed in 3.x since `BIND_BITFIELD_FLAG` wasn't backported so we have no way of getting this information.

**Comment by eumario** [comment]
I understand that raul, I was not suggesting for 3.x, but instead ensuring we are keeping 4.0 consistent.

**Comment by neikeq** [comment]
The change is easy to apply if you consider an enum should be marked as flags. Find the enum in the C++ code and replace the `BIND_ENUM_CONSTANT` statements of its elements with `BIND_BITFIELD_FLAG`.
This may have ramifications on other parts of the engine in addition to C#, though. I don't know if any of it could be considered problematic.

Sadly, we're in beta already. If it was only a C# change, we can make an exception. But this is unlikely to be accepted as it affects the entire engine.
We could still hard-code a list of flags enums in the C# bindings generator, though.

**Comment by raulsntos** [comment]
Fixed by https://github.com/godotengine/godot/pull/71037
