### ISSUE TITLE
Set the zoom of camera2d will cause the text in the label to be blurred

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#69711]
### Godot version

v4.0.beta7.mono.official.0bb1e89fb

### System information

Windows11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Hi, My game asset is design for 640x480, But I don't want set viewport to 640x480. I want use 1920x1080 as viewport size and use camera2d zoom to fit

This is my project setting:
![屏幕截图 2022-12-07 172923](https://user-images.githubusercontent.com/14236891/206141210-fcacb32a-49b6-41d1-805d-a1e37d346779.png)

**Camera2d is child node of player node, and set camera2d zoom to 3**
the text in richtextlabel in player will look like:
![屏幕截图 2022-12-07 173153](https://user-images.githubusercontent.com/14236891/206142424-1c0ad172-ffeb-49a4-8978-f4147e557e1e.png)

**But if set ProjectSetting Display/Window/Stretch/Scale to 3, and set camera2d zoom to 1:**
![屏幕截图 2022-12-07 173843](https://user-images.githubusercontent.com/14236891/206143304-8edb74f2-eda4-4731-b58d-6e97a4d9392a.png)
It seems normal

### Steps to reproduce

Pls look uploaded project

### Minimal reproduction project

[TestCamera2d.zip](https://github.com/godotengine/godot/files/10174577/TestCamera2d.zip)

**Comment by Calinou** [comment]
This is expected, as font oversampling does not take camera zoom into account by design. (It would be too slow otherwise.)

To have a font that renders crisply at any resolution without requiring oversampling, use a MSDF font. If *not* using a custom font, this can be done by enabling **Default Font Multichannel Signed Distance Field** in the advanced Project Settings. If using a custom font, this can be done by checking the **Multichannel Signed Distance Field** property in the Import dock after selecting a font file in the FileSystem dock, then clickin **Reimport**.
