### ISSUE TITLE
[3.x] ERROR: Can't resize PoolVector if locked.

### ISSUE THREAD

**Issue by madmiraal** [godotengine/godot#69727]
### Godot version

3.x

### System information

Ubuntu 22.10

### Issue description

Sometimes, when opening a project, I get:
```
ERROR: Can't resize PoolVector if locked.
   at: resize (./core/pool_vector.h:528)
ERROR: Can't resize PoolVector if locked.
   at: resize (./core/pool_vector.h:528)
```

This only affects the 3.x branch, because `PoolVector` has been removed from master.

### Steps to reproduce

I've only got this to happen when building with `use_asan=yes, use_ubsan=yes`.

### Minimal reproduction project

Any project, but I was using https://github.com/godotengine/regression-test-project.

**Comment by lawnjelly** [comment]
What version of 3.x / commit hash are you using here? I only ask because line 528 is not the resize operator.

There are a number of problems with `PoolVector` and race conditions if I remember right, I had a go with a replacement in #59444 but never got it finished.

**Comment by madmiraal** [comment]
> What version of 3.x / commit hash are you using here? I only ask because line 528 is not the resize operator.

Sorry, that error message is from my own custom branch, which is based on 3.4.5. The line that generates the error is:
https://github.com/godotengine/godot/blob/9983df9210b2ba4e9161c9fc52eefef9d1d3c07b/core/pool_vector.h#L590

**Comment by madmiraal** [comment]
> Could you get this to reproduce with a debug build or does it occur for you only on release?

Actually, I don't seem to be able to reproduce it on the 3.x branch either. So, this may be a bug on my custom branch only (although I've not made any changes to 'PoolVector'?). I'll close this issue for now. I'll reopen it if I find it a way to reliably reproduce it on 3.x too.

**Comment by lawnjelly** [comment]
My best guess is that the problem was caused by a dangling `Access`, and I will see if it is possible to reproduce with an MRP. I don't *think* it is possible from gdscript (as `Access` cannot afaik be made directly) but can from c++.

If the `Access` still has a lock when the `Alloc` is freed, then it may attempt to decrement (or worse read / write) from the `Alloc` after freeing, and perhaps after assigning to a new `PoolVector`.

But as I say there are likely many such vulnerabilities in the current `PoolVector`, so it would be nice to replace at some point.
