### ISSUE TITLE
The problem about tilemap navigation

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#69743]
### Godot version

v4.0.beta7.mono.official.0bb1e89fb

### System information

Windows11 Vulkan API 1.2.0 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

Hi. My tilemap has two layer:
1. Layer 1 (Low)
2.  Layer 2 (High)

In Layer 1 I place a grassland tile at (0,0), it is navigable. In Layer 2 I place a wall tile at (0,0), it un support navigation.
So, in fact (0,0) in tilemap should be non navigable, but it is still navigable.

I solved this problem by add a Nav Layer (more high) and place transparent navigable tile on where navigation needs to be supported

Is there a better solution?

### Steps to reproduce

N/A

### Minimal reproduction project

[Godot4Tilemap.zip](https://github.com/godotengine/godot/files/10183583/Godot4Tilemap.zip)

**Comment by mrbaggins** [comment]
Navigation as in Navigation Server? Just make sure to tick the navigation layers you want in the TileSet inspector, and then paint the navigation properties in the the same. See blue areas in attached image.

![image](https://user-images.githubusercontent.com/1549457/206360706-5465f0ac-ea47-4c2b-ae5c-6ba6f50ff1d1.png)

**Comment by gnenux** [comment]
> Navigation as in Navigation Server? Just make sure to tick the navigation layers you want in the TileSet inspector, and then paint the navigation properties in the the same. See blue areas in attached image.
> 
> ![image](https://user-images.githubusercontent.com/1549457/206360706-5465f0ac-ea47-4c2b-ae5c-6ba6f50ff1d1.png)

Hi. I know this. Look this image:
![屏幕截图 2022-12-08 164109](https://user-images.githubusercontent.com/14236891/206399510-5eb18b04-f7b6-4366-9e96-34c529940b4f.png)

1: is road tile in "ground" layer, support navigation and has paint the navigation properties.
2: is wall tile in "above ground" layer, not support navigation and not paint the navigation properties.

So, in tilemap, "4" should not in Navigation Server

**Comment by gnenux** [comment]
Can we add a bool variable called cut or erase in navigation layer's paint properties. If check it, then painting on the cell will erase NavigationPolygons on low layer (Tilemap Layer) cell. It is a convenient feature.

**Comment by MikeBaldwin21** [comment]
Is it frowned upon to add additional details to an issue that's not mine or should I just make a new one? I guess delete this comment if it's useless to the discussion...

---

I agree with @gnenux, an 'erase' or 'delete' navigation tile paint could potentially fix this. To me this seems to be a tilemap navigationpolygon generation issue, not a navigationserver/navigationlayer/navigation-agent issue.

I'm on v4.0beta10.mono
I have a single tilemap that contains two tilemap layers (floor and wall layers) and a single navigation layer
![image](https://user-images.githubusercontent.com/5078843/210111006-d40c6fbc-f856-41de-a4af-e6734f70aa10.png)

I've painted the tile that makes up my 'floor' layer with the navigation layer paint
![image](https://user-images.githubusercontent.com/5078843/210111071-f9c3b483-6ad5-48fa-ab8c-98f71cae92b8.png)

No navigation paint on the tiles that I use for my 'wall' layer
![image](https://user-images.githubusercontent.com/5078843/210110969-8b741e23-f15b-4152-bd79-9da46e3700d9.png)

For the tilemap I first laid down a 16x16 grid of 'floor' tiles on the tilemap floor layer. Then added wall tiles to the tilemap wall layer. The issue is that the navigation polygon generation doesn't seem to take into account the non-navigable 'wall layer tiles' and instead just treats the entire floor as navigable (is that a word?). I can easily fix this by removing the floor tiles from the floor layer where they are under the walls, but that seems to defeat the purpose of having layered tiles (unless I'm grossly misunderstanding what the new tilemap layers are to be used for).

With NavigationVisibilityMode set to default to show what the map looks like:
![image](https://user-images.githubusercontent.com/5078843/210111569-e8f28875-1c02-4480-ab15-56363d6524e3.png)


NavigationVisibilityMode set to Force Show:
![image](https://user-images.githubusercontent.com/5078843/210111610-33e9381d-7dd0-465f-a7f8-9066fc8d589b.png)


and here's the test project:
[NavigationTest.zip](https://github.com/godotengine/godot/files/10326305/NavigationTest.zip)

**Comment by smix8** [comment]
I don't see how this can ever work in 2D with TileMap. The TileMap tries to create some pseudo 2D "verticality" with the Layers. Something that would only work when each Layer would be placed on its own navigation map or on a different y-axis and it would require to mark the connecting edges inside the TileMap Layers, else agents would never find coherent paths on and between the Layers. Not only does the TileMap not do this but it would also impossible to query navigation paths for 2D this way as NavigationAgents are not aware of all this TileMap shenanigans to be able to query paths on the correct layers. The Layers are basically a doomed TileMap feature for anything that is not visuals.

**Comment by animentork** [comment]
Even though tiles on the tile map layers get their initial navigation polygon from the tile set, you can change it at any time for each individual tile cell. So you can loop over your ground layer cells, check if there is a non-traversable tile at the same position on your wall layer and, if so, remove the navigation polygon from the ground layer cell – without removing the navigation polygon on all the other ground tiles:

Something like this, I haven't tested it:

```
for cell in get_used_cells(0):
    if get_cell_tile_data(1, cell).get_custom_data("is_wall") == true:
        var nav_poly_res = NavigationPolygon.new()
        get_cell_tile_data(0, cell).set_navigation_polygon(0, nav_poly_res)
```

**Comment by gnenux** [comment]
> Even though tiles on the tile map layers get their initial navigation polygon from the tile set, you can change it at any time for each individual tile cell. So you can loop over your ground layer cells, check if there is a non-traversable tile at the same position on your wall layer and, if so, remove the navigation polygon from the ground layer cell – without removing the navigation polygon on all the other ground tiles:
> 
> Something like this, I haven't tested it:
> 
> ```
> for cell in get_used_cells(0):
>     if get_cell_tile_data(1, cell).get_custom_data("is_wall") == true:
>         var nav_poly_res = NavigationPolygon.new()
>         get_cell_tile_data(0, cell).set_navigation_polygon(0, nav_poly_res)
> ```

Hi, sorry for my English. I test this method. This method will remove all navigation polygon in tilemap, my code like this:
```c#
            var layersCount = GetLayersCount();
            for (int i = layersCount - 1; i >= 0; i--)
            {
                var usedCells = GetUsedCells(i);
                foreach (var usedCell in usedCells)
                {
                    var tileData = GetCellTileData(i, usedCell);
                    if (tileData != null && tileData.GetCustomData("clear_nav").AsBool() == true)
                    {
                        for (int j = i - 1; j >= 0; j--)
                        {
                            var _tileData = GetCellTileData(j, usedCell);
                            if (_tileData != null)
                            {
                                var _navigationPolygon = _tileData.GetNavigationPolygon(0);
                                if (_navigationPolygon != null)
                                {
                                    _navigationPolygon.ClearOutlines();
                                    _navigationPolygon.ClearPolygons();
                                    _tileData.SetNavigationPolygon(0, _navigationPolygon);
                                }
                                _tileData.SetCustomData("clear_nav", false);
                            }
                        }
                    }
                }
            }
```
I guess it seems that the navigation polygon data configured in the tileset is removed, rather than a single tile after instantiated.
So if "_tileData" is the "TileData" of "grass" tile, the navigation polygon data of all grass tiles in tilemap will be removed.

**Comment by gnenux** [comment]
> You're right, I didn't know that. But you can change the tile data at runtime according to the documentation:
> 
> > TileData object represents a single tile in a [TileSet](https://docs.godotengine.org/en/latest/classes/class_tileset.html#class-tileset). It is usually edited using the tileset editor, but it can be modified at runtime using [TileMap._tile_data_runtime_update](https://docs.godotengine.org/en/latest/classes/class_tilemap.html#class-tilemap-method-tile-data-runtime-update).
> 
> I've changed the code:
> 
> ```
> # Check if there is a non-traversable cell on any other layer than the provided cell_layer:
> func is_cell_traversable(cell_layer, cell):
> 	var is_traversable = true
> 	for layer in range(get_layers_count()):
> 		if cell_layer == layer:
> 			break
> 		if get_cell_tile_data(layer, cell).get_custom_data("traversable") == false:
> 			is_traversable = false
> 			break
> 	return is_traversable
> 
> # Call the above function to check if a cell's tile_data needs to be updated:
> func _use_tile_data_runtime_update(layer, coords):
> 	if not is_cell_traversable(layer, coords):
> 		return true
> 	else:
> 		return false
> 
> # Remove a cell's navigation polygon if the above function returns true:
> func _tile_data_runtime_update(layer, coords, tile_data):
> 	tile_data.set_navigation_polygon(0, NavigationPolygon.new())
> 	return true
> ```
> 
> Here is a slightly modified version for testing purposes, which removes the navigation polygon on every second column:
> 
> ```
> func is_cell_traversable(cell_layer, cell):
> 	var is_traversable = true
> 	for layer in range(get_layers_count()):
> 		if cell_layer == layer:
> 			pass
> 		if cell.x % 2 == 0:
> 			is_traversable = false
> 			break
> 	return is_traversable
> 
> func _use_tile_data_runtime_update(layer, coords):
> 	if not is_cell_traversable(layer, coords):
> 		return true
> 	else:
> 		return false
> 
> func _tile_data_runtime_update(layer, coords, tile_data):
> 	tile_data.set_navigation_polygon(0, NavigationPolygon.new())
> 	return true
> ```
> 
> I admit that it's not the most elegant solution, but it seems to work, and as long as you only use it sparingly (for example, once for the whole tile map during initialization), I find its decrease in performance tolerable.

Thank you very much! It helped me. 
It should be noted that, the tile_data.set_navigation_polygon() should pass “NavigationPolygon.new()” or “null” in func _tile_data_runtime_update. Not use origin navigation polygon and clear polygons, it will impact whole tileset.

**Comment by smix8** [comment]
One potential solution to the TileMap Layer navigation layer "verticality" problem would be that the TileMap, instead of throwing everything on the same default navigation map, creates a dedicated navigation map for every navigation layer above the first layer. Than add convenvience functions to receive these maps to the TileMap so they can be used with set_navigation_map() functions on other navigation objects whenever they do their "logical" TileMap layer switch.

This would then allow users to still use the NavigationAgent2D nodes. They only need to set the agent to a different navigation map  for this TileMap layer in scripting whenever they do this logical TileMap layer switch, e.g. move up a stair or jump down somewhere.

Not only would this split between maps solve the apparent problem with overlapping navigation polygons but it would also immediately solve or mitigate other related issues like with avoidance or NavigationServer map sync cost on very large maps.

Agents on different maps would not need to avoid / process each other. So an agent on a logical "upper" TileMap layer would not avoid and agent on a "lower" TileMap layer even when their avoidance radius overlap.

Since the NavigationServer syncs by map and only when the map has received changes it would also help with runtime updates on large TileMaps as each TileMap layer that has not received changes would have no need to be processed automatically.

**Comment by kozak-codes** [comment]
The above PR doesn't actually solve the problem that this issue outlines. Thanks for the example code @gnenux and @animentork - I've modified it somewhat so it doesn't require custom data:


Place the above code in TileMap.gd - basically the way this works is each layer will inherit the navigation polygon from the layer above, if it doesn't have one then it will be considered non-navigable. This means that only the navigation layer from the top-most level will be used. In my case, the terrain is on layer 1 and the rocks are on layer 2. The rocks on layer 2 have some transparent backgrounds.

```godot
# Call the above function to check if a cell's tile_data needs to be updated:
func _use_tile_data_runtime_update(layer, cell):
	var nextLayer = layer + 1
	if nextLayer >= get_layers_count():
		return false
	
	var currentPolygon = get_cell_tile_data(layer, cell).get_navigation_polygon(0)
	if !currentPolygon:
		return false

	var nextTile =  get_cell_tile_data(nextLayer, cell)
	if !nextTile:
		return false
	
	var nextPolygon = nextTile.get_navigation_polygon(0)
	if nextPolygon:
		return currentPolygon != nextPolygon
	
	return true

# Inherit the tile data polygon from the parent layer
func _tile_data_runtime_update(layer, cell, tile_data):
	var nextLayer = layer + 1
	if nextLayer >= get_layers_count():
		return false

	var currentPolygon = tile_data.get_navigation_polygon(0)
	if !currentPolygon:
		return false

	var nextTile =  get_cell_tile_data(nextLayer, cell)
	if !nextTile:
		return false
	
	var nextPolygon = nextTile.get_navigation_polygon(0)
	if nextPolygon:
		tile_data.set_navigation_polygon(0, nextPolygon)
		return true

	tile_data.set_navigation_polygon(0, NavigationPolygon.new())
	return true
```

Result:
![image](https://github.com/godotengine/godot/assets/1368558/c74d03e3-6bc5-47ee-9118-0f14fa795d1d)

I'm pretty new to godot so I have no idea if this will be performant or not but it serves my needs

**Comment by animentork** [comment]
I agree that the PR doesn't solve the issue or at least it isn't clear to me how it solves it. Which isn't to say, it wouldn't be a welcome addition, of course.

With the PR it's possible to have multiple navigation maps for one TileMap, and that's very cool and offers new possibilities. The question here is, however, how to prevent navigation on otherwise navigable cells when there are non-navigable cells on upper levels – like a rock or a wall on grass terrain.

In an ideal world, collision polygons could be subtracted from navigation polygons. The above code examples try to work around that by exchanging the navigation polygons on the "terrain level", either by setting a blank, empty navigation polygon and blocking the cell altogether or by setting the polygon of the cell on the upmost layer. Thank you, @kozak-codes, for another variant, I'm sure it will be useful.

**Comment by stwupton** [comment]
This PR is not a solution for me. In my case I have grass tiles with navigation polygons on Layer 1. Trees, walls etc. with collisions on Layer 2. 

How am I supposed to alter the navigation mesh in such a way that makes the pathfinding avoid the collision shapes on Layer 2?

![image](https://github.com/godotengine/godot/assets/7224013/9c081186-4a88-4248-82f5-d0698cd7b23f)

**Comment by smix8** [comment]
The pr fixed that different TileMap layers that are actually used as different pseudo 2D vertical layers could not be used as such, because the TileMap did throw all TileMap layers on the same navigation map causing conflict and navigation map errors.

The remaining issue that users mention here is not what the pr tried to solve. A part of it is asking for boolean ops done by the TileMap, the other part is the TileMap providing a TileMap layers feature that is only workable for visuals but simple does not work with the underlying physics and navigation system.
