### ISSUE TITLE
`_draw()` function called twice on start for TileMap node

### ISSUE THREAD

**Issue by enemy141** [godotengine/godot#69754]
### Godot version

4.0 beta 7

### System information

Windows 10

### Issue description

_draw() Function in TileMap node loops 2 time after applied the TileSet 

### Steps to reproduce

apply TileSet in TileMap node  then create a script in TileMap and write _draw() with loop for example
func _draw():
	for i in 10:
		print(i)

result[
0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
5
6
7
8
9]

### Minimal reproduction project

[DrawReport.zip](https://github.com/godotengine/godot/files/10183774/DrawReport.zip)

**Comment by groud** [comment]
Hmm, there's no reason this function would be called twice, we don't even call `queue_redraw` on a TileMap since it uses internal child canvas items to render things (with direct calls to the RenderingServer API). Even if it's not a big issue I guess, this should not happen.

**Comment by enemy141** [comment]
thank you for replying This is probably my first report in 4.0 I just found the bug during the testing connection between Astar points also thank you for correcting the tile sentence that is very embarrassing.

**Comment by iamtoaster** [comment]
I did a little debugging on this issue. So it seems that the double draw call is caused by the `TileMap` recreating its internals upon entering the tree:

https://github.com/godotengine/godot/blob/829d49b0110edc7bf283c7cca30cddb967bccb70/scene/2d/tile_map.cpp#L494-L497

 As a part of that process it also queues an update to dirty quadrants, which then tries to recompute the rect cache. The rect cache recomputation is an operation that can potentially alter the boundaries of our `TileMap`, and thus it calls the `item_rect_changed()` function:
https://github.com/godotengine/godot/blob/829d49b0110edc7bf283c7cca30cddb967bccb70/scene/2d/tile_map.cpp#L998-L1002

That function then queues a redraw by default:
https://github.com/godotengine/godot/blob/829d49b0110edc7bf283c7cca30cddb967bccb70/scene/main/canvas_item.cpp#L446-L451

The problem is, because the dirty quadrant update call is deferred, it only occurs after the first draw call that is a part of entering scene tree is done. Because of that, a new redraw gets queued.

A solution I thought of is to check if the rect actually changed and pass that to the `item_rect_changed()`  function, so that it does not queue a redraw. I will make a pull request with that solution soon.
