### ISSUE TITLE
Globals.localize_path fails to localize an absolute path

### ISSUE THREAD

**Issue by neikeq** [godotengine/godot#6979]
**Issue description** (what happened, and what was expected):
Regression from #6813

`Globals.localize_path(String path)` is returning the same absolute path that was passed to it, instead of the localized path.

**Steps to reproduce:**

Example with the Platformer 2D demo:

``` GDScript
func reproduce_the_bug_plz():
    var local_path = "res://player.gd"
    var global_path = Globals.globalize_path(local_path)
    assert(local_path == Globals.localize_path(global_path))
    #assert(global_path != Globals.localize_path(global_path))
```

**Comment by akien-mga** [comment]
CC @Faless

**Comment by Faless** [comment]
Yeah, I really messed up this path thing :-1:  .
Anyway, can someone check if the small patch referencing this issue is ok? It is in my mind, but I'm not completely sure about the behavior of localize_path.
This way if the path is absolute will be localized if a subfolder of the resource folder, it will be left absolute otherwise.

**Comment by neikeq** [comment]
@Faless I tested your patch with _"res://player.gd"_ and _"res://folder/test.gd"_ globalized and both succeeded at localizing the path.

However, wouldn't the following be better?:

``` C++
	if (p_path.is_abs_path() && !p_path.begins_with(resource_path)) {
		return p_path;
	}
	// Otherwise continue with the function, which localizes the path
	// It seems to do more than just calling replace
```
