### ISSUE TITLE
Assigning array of different type can overwrite original array reference

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#69839]
### Godot version

4.0 ae86d90

### System information

Windows 10 x64

### Issue description

This is a bit convoluted, but it boils down to this:
```GDScript
var base_array: Array[int]
var array: Array[int]
array = base_array
array.append(1)
print(base_array) # prints [1]
var new_array := []
array = new_array
print(base_array) # prints []. base_array is gone??
```
`array` variable was holding `base_array`. We then assign a different array to `array` (it's important that it's a new variable). Assigning to `array` overwrites `base_array`.

Does not happen if `base_array` is not typed.
Does not happen if `new_array` is `Array[int]`

### Steps to reproduce

Run the code above.

### Minimal reproduction project

N/A

**Comment by vonagam** [comment]
#69248 fixes it.

I don't know if you have rights to do reviews/approvals in GDScript/Core section. 
But if you do - I would appreciate a look at the PR.
It started simple but then grew because there were so many issues with typed arrays.
I can try to separate and remove things out of it if it helps.
Have no problem squashing - just kept it as separate commits for now because it became too much for one.
If it matters - I am on rocket chat thing so can respond there too.
