### ISSUE TITLE
Skeleton3D - "Create Physical Skeleton" fails with error mesh_storage.h:686 - Condition "skeleton->size == 0" is true. Returning: RID()

### ISSUE THREAD

**Issue by samuelfine** [godotengine/godot#69887]
### Godot version

4.0.beta7

### System information

macOS 13.0, 2020 Mac Mini M1

### Issue description

Adding a `Skeleton3D` node to a new project fails silently, alongside Output errors:

`./servers/rendering/renderer_rd/storage_rd/mesh_storage.h:686 - Condition "skeleton->size == 0" is true. Returning: RID()`

![image](https://user-images.githubusercontent.com/695568/206881866-b5681b1c-51f6-42fe-97f7-95994afd57b3.png)

### Steps to reproduce

- Create a new Scene with a `Node3D` root
- Add a `Skeleton3D` node as a child
- Observe error message in the Output panel
- Under the Skeleton3D sub-menu, click "Create Physical Skeleton"
- Nothing happens, no bones are created

### Minimal reproduction project

[Skeleton3D_bug.zip](https://github.com/godotengine/godot/files/10201292/Skeleton3D_bug.zip)

**Comment by Calinou** [comment]
Is it supposed to be possible to create a physical skeleton with no bones? If not, an error dialog should appear.

**Comment by samuelfine** [comment]
I should also note that I was following the tutorial here:

https://docs.godotengine.org/en/latest/tutorials/physics/ragdoll_system.html

**Comment by SaracenOne** [comment]
I think the issue at hand here is more likely the documation is unclear on the workflow for physical bones. The appropriate way to handle it is to bring in your own model as something like GLTF file with its own skeleton, and then use the Create Physical Skeleton button to give it ragdoll properties. Regardless, I've done a PR now which should add an explicit warning as well as silencing the unhelpful errors which were actually caused by the relevant gizmos not being able to handle the fact that the skeleton has no bones.

https://github.com/godotengine/godot/pull/71956
