### ISSUE TITLE
Normal maps in 3D space don't work on Android

### ISSUE THREAD

**Issue by timoschwarzer** [godotengine/godot#6990]
**Operating system or device - Godot version:**
Android 7.1, latest master branch

**Issue description** (what happened, and what was expected):
Normal maps in 3D space don't work on Android. It just renders the diffuse texture.
If this is intended behavior, it should be documented somewhere. (I could't find anything)

**Steps to reproduce:**
Add a Sprite3D with a FixedMaterial which uses a normal map. Add a light to the scene to test it.

**Comment by RandomShaper** [comment]
Have you enabled fragment lighting in *Scene -> Project Settings -> Rasterizer.Android*?

**Comment by timoschwarzer** [comment]
Yes.

**Comment by timoschwarzer** [comment]
So, there seem to be differences between devices.

Android 7.1, OnePlus 2:
![img_20161031_083710]

Android 7.0.1, Samsung Galaxy Tab S2:
![screenshot_20161031-083227]

PC, Linux, GTX 970, proprietary drivers, this is the correct one:
![screenshot_20161031-083656]

(https://cloud.githubusercontent.com/assets/8849554/19847237/bf79b22e-9f45-11e6-8508-698a66f00c07.png)


(https://cloud.githubusercontent.com/assets/8849554/19847211/8e65ba34-9f45-11e6-8777-cbac7b360cfc.png)


(https://cloud.githubusercontent.com/assets/8849554/19847184/58efea50-9f45-11e6-9bb6-bf7dd2ecde98.jpg)

**Comment by RandomShaper** [comment]
Maybe a precision issue.

Sometimes I get different results between PC and Android and I need to add
some hacks for mobile.

Are you using normalize()? Any chance of having a look at your shader's
code?

**Comment by timoschwarzer** [comment]
This is my shader code:
```
uniform color fmp_specular;
uniform texture fmp_normal_tex1;
uniform texture fmp_normal_tex2;

float speed = 0.02;

color specular=fmp_specular;
SPECULAR=specular.rgb;
SPEC_EXP=48;

vec2 uv1 = UV;
vec2 uv2 = UV;
vec3 normal_tex = vec3(0);
float time_rem = mod(TIME, speed * 3);

uv1 += TIME * speed;
uv2 -= TIME * speed;

normal_tex = mix(tex(fmp_normal_tex1, uv1), tex(fmp_normal_tex2, uv2), 0.5).xyz;

NORMALMAP = normal_tex * vec3(2.0, 2, 0.3) - vec3(1,1,0);
NORMALMAP_DEPTH = 1;

DIFFUSE=vec3(0);
```

The texture uniforms are both a water normal map.
As I'm new to shaders, could you explain the normalize() function to me, please?

**Comment by RandomShaper** [comment]
normalize() takes a vector and makes it one unit long while keeping its
direction. It's like dividing every component by the length of the vector.

But I've found sometimes on mobile the vector ends up measuring less than
1.0 and I have needed to put down normalize() and do it by multiplying by 1
/ length(vector) to get accurate results (you know, multiplying by the
inverse of a number is an optimization used when you have to divide several
times by the same number as division is much slower than multiplication).

With TIME you have to be careful because as time goes by it can grow as
much as to cause numeric range issues. That's why using fract(), mod(),
etc. on it is advisable depending on what you need to achieve or what
computations it will be involved in.

All that said, I have not yet seen anything that can cause precision issues
in your shader during the first minutes of execution.

The only thing that I find wrong is that if you are translating from normal
map color to the actual normal by yourself, you must assign the result
directly to NORMAL (by using NORMALMAP Godot will do the conversion one
more time).

Furthermore because of that 0.3 for Z, you are not getting a unit normal
vector. It might be what you want, but if not, you have to normalize() the
resulting vector.

Check these things and tell your results so we can further investigate
whether you have hit a bug.

**Comment by timoschwarzer** [comment]
Thank you! By normalizing, it works on Android.

**Comment by RandomShaper** [comment]
I'm glad I've helped you. Good luck with your project!

**Comment by AugustusCollins** [comment]
Thanks, normalizing the vectors in my shader worked and it gave me a much more cooler effect.
You have no idea how happy you just made me, Thank You!!
