### ISSUE TITLE
const arrays cannot be declared if the array contains different type of variables

### ISSUE THREAD

**Issue by zetim** [godotengine/godot#70021]
### Godot version

4.0 beta8

### System information

Windows 10 64bit

### Issue description

When writing a const that contains an array, the system will not allow the user to create a const if the array contains variables of different types. const arrays that contain the same type are allowed by the compiler. It only spits an error and stops the user if the array has different types. The error it gives is "Variant array is not compatible with an array of type "unresolved type"."

![image](https://user-images.githubusercontent.com/22281231/207397716-5c40d298-a8d9-4ddd-a0e9-b55bdd06d774.png)

### Steps to reproduce

Try to declare a const array with multiple types. Any arrangement of types gives the error, except keeping them all an identical type.

### Minimal reproduction project

N/A

**Comment by jquinl** [comment]
Seems like the issue happens because the analyzer tries to infer datatypes for any const Array with more than 0 elements, even if it has no type specifier. I have created a pull request that solves this.

**Comment by vonagam** [comment]
Fixed in #69248 (with many other problems of typed arrays).

The last linked PR is wrong way to do it. You want to type an array literal in two cases: a) you want to infer type and there are some items to do so, b) you have an explicitly typed array with an element type. By replacing `OR` with `AND` you for example block setting an element type from an explicit declaration on an empty array.
