### ISSUE TITLE
Godot 4beta 'Open a Directory' dialog layout bug

### ISSUE THREAD

**Issue by epchain** [godotengine/godot#70060]
### Godot version

v4.0.beta8.official [45cac42c0]

### System information

Windows 10 x86_64

### Issue description

When using 'Advanced Import Settings' dialog on a .glb asset and any of its 'Actions' there comes 'Open a Directory' dialog with broken layout of controls.

Screenshot:
![open-dir-layout-bug](https://user-images.githubusercontent.com/25767621/207628338-b820084b-ce10-486b-8ea2-69d9de038160.png)

### Steps to reproduce

1. Create new Godot project
2. Export any .glb resource for Godot project
3. In Editor, select that resource -> open Import tab -> hit Advanced
4. Open Actions menu and choose any of 'Extract Materials', 'Set Animation Save Paths' or  'Set Mesh Save Paths'
5. An 'Open a Directory' dialog appears with messed buttons and labels layout at top left corner.

### Minimal reproduction project

[godot-import-open-dir-layout-bug.zip](https://github.com/godotengine/godot/files/10228890/godot-import-open-dir-layout-bug.zip)

**Comment by akien-mga** [comment]
I've also seen something similar in another dialog recently, but I can't remember which one.

**Comment by dustinsth** [comment]
When an "Actions..." menu option is selected, the function `_menu_callback` in `scene_import_settings.ccp` is called.

https://github.com/godotengine/godot/blob/2e657e51f8818401f0a54a0df3d3e74446044b93/editor/import/scene_import_settings.cpp#L960-L970

In the above code `save_path` is referring to the `editor_file_dialog` that is opened to allow the user to select a folder in which the selected "Action..." option will be performed.
`editor_file_dialog`'s inherited `AcceptDialog::set_text` function is called; this function would normally set the message text found on a plain `AcceptDialog` or `ConfirmationDialog`.

Should an `editor_file_dialog` have any message text at all? Perhaps the code should call `set_title()` instead so that the desired message is shown in the dialog window's title.

I'm still looking into why the `message_label` text is overlapped by the `editor_file_dialog` control elements.
