### ISSUE TITLE
Signals not properly disconnecting on object freed

### ISSUE THREAD

**Issue by Mario55770** [godotengine/godot#70067]
### Godot version

4.0 beta 8.mono

### System information

Windows 10

### Issue description

Signals are not correctly disconnected on freeing objects. This causes an error on next emittion of that signal.

### Steps to reproduce

Create a project, connect an object with signals.(I used c# in testing, unconfirmed in GDScript)

Than free that object and create a new one. I recreated the same object when I found this issue. Than connect as normal to that new object. Emit the signal. 

An error should show up to the effect that it is trying to signal an object that was already freed.

### Minimal reproduction project

N/A

**Comment by stmSi** [comment]
`Than free that object and create a new one. I recreated the same object when I found this issue. Than connect as normal to that new object. Emit the signal.`

I don't understand these steps... can you give me minimal repoducable project?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
