### ISSUE TITLE
Using Alpha in Visual Shader removes SSAO, SSS and breaks Refraction.

### ISSUE THREAD

**Issue by SirManfred** [godotengine/godot#70109]
### Godot version

v4.0.beta.custom_build [df61f3475]

### System information

Windows 10, RTX 3060

### Issue description

When plugging something (anything, really) into the Alpha slot in the Visual Shader editor, everything that uses that material loses SSAO, SSS and shows up as solid black objects in transparent glass like shaders.

### Steps to reproduce

Make a shader using the visual shader editor.
Make a custom material that uses said shader.
Make a glass material, either using the visual shader editor or using the default StandardShader.

Place an object using the glass material in front of an object using the custom material.

When you then plug something into the alpha output of the custom shader in the visual shader editor, everything that uses the custom material shows up as solid black objects when seen through the glass material.

Additionally, if the custom material uses SSS and if SSAO is active in the environment, those effects disappear whenever something is plugged into the alpha output.

### Minimal reproduction project

Reproduction steps are trivial.

**Comment by clayjohn** [comment]
Could you please upload an MRP to make this easier for contributors to troubleshoot?

An MRP is a project that is as small as can be while still reproducing the bug you are reporting. We include the MRP in the bug reporting template as including one greatly increases the chance that a contributor will be able to reproduce the bug you reported and be able to fix it.

**Comment by Calinou** [comment]
This is expected, as transparent materials don't make use of SSAO and SSR. Refraction however should keep working (in fact, it forces the material to be transparent).

**Comment by BastiaanOlij** [comment]
The same applies to the glass effect.

I've created this basic scene:
![image](https://user-images.githubusercontent.com/1945449/220884638-c84e04d5-afa9-4471-9596-aaa416d29696.png)
In this first screenshot the blue box has a visual shader without an alpha (it's actually irrelevant if this is a visual shader or normal shader, what is important is that it is not transparent).
The flattened sphere has a normal material with alpha set to something low like 0.2 but **no refraction**. Also roughness is set to 0.24.

If we turn refraction on we can see the expected result:
![image](https://user-images.githubusercontent.com/1945449/220885054-5c1b5145-aae1-4bbe-a5d9-5dfd186b6f6c.png)
Our sphere and ground plane are shown with spherical distortion through the sphere.

Now without refraction but with the alpha assigned on our blue box, looks ok:
![image](https://user-images.githubusercontent.com/1945449/220885364-26cfdbb3-205c-4597-ac15-7d5f2d697db6.png)

Finally with refraction and alpha assigned on our blue box:
![image](https://user-images.githubusercontent.com/1945449/220885624-affad653-0a15-4b33-bf3f-de7b7f90b0ce.png)

The box magically disappears! I'm assuming this is what the OP was referring to.

Alas, just like with SSAO and SSR this is expected behavior. In order to do reflection we need to make a copy of what is rendered, so we can read from this copy to show the refracted result. This copy is made after opaque materials and the background are rendered, but right before we render our transparent materials as these consume our screen texture (which is the copy we were talking about).

Hence transparent materials can not be seen refracted through other transparent materials.

The only way to solve this would be to make a fresh copy of the render result before each transparent material that requires a read from screen texture, which would seriously impact performance.

**Comment by Zireael07** [comment]
> Hence transparent materials can not be seen refracted through other transparent materials.

Probably worth calling out in docs and not fixing given you said it would impact perf negatively
