### ISSUE TITLE
RigidBody2D.inertia is hidden when auto-computed

### ISSUE THREAD

**Issue by Lemonymous** [godotengine/godot#70149]
### Godot version

4.0.dev (30800d20f452015c054dc7d1d7cfd38362fe28ff)

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1050 Ti (31.0.15.1694)

### Issue description

RigidBody2D's property `inertia` says in the tooltip, that if set to 0, inertia is automatically computed. This works fine.

However, checking what the object's inertia is at run-time isn't always readily available, as the property `inertia` remains 0, even after it has been computed.
The only way I've found to check the object's auto-computed inertia is via `PhysicsDirectBodyState2D.inverse_inertia`, which is only available in the `_integrate_forces` method.

### Steps to reproduce

- Create a `RigidBody2D`
- Leave `inertia` at 0
- Add a `CollisionShape2D` with any `CollisionShape2D`
- Observe that `inertia` remains set to 0 at run-time
- Also observe that `1/state.inverse_inertia` returns the object's auto-computed inertia in `_integrate_forces(state)`

### Minimal reproduction project

[Hidden Inertia.zip](https://github.com/godotengine/godot/files/10246733/Hidden.Inertia.zip)

This project has two `RigidBody2D` objects.
One with an auto-computed inertia, and one with a fixed inertia.
When the project is run, each rigid body will in their `_integrate_forces(state)` method, print the following properties:
- `inertia`
- `state.inverse_inertia`
- `1/state.inverse_inertia`

**Comment by rburing** [comment]
This is kind of by necessity in the present design. Since the value `0` means inertia is automatically computed, setting it away from this value would mean it won't be automatically computed again when the collision shapes change. Besides, internally there's not really a natural moment to be sure one is "done" adding collision shapes. This quirk should be documented, with reference to a method to obtain the automatically computed inertia. One could also make a [proposal](https://github.com/godotengine/godot-proposals/) to replace the magic value `0` by a separate boolean toggle.

**Comment by Lemonymous** [comment]
Since adding this issue, I've also learned that it is possible to fetch the automatically computed inertia via `PhysicsServer2D.body_get_direct_state(body).inverse_inertia`, so it can actually be found in any function after all.

I agree that it would be good if it was documented under `RigidBody.inertia` how to find the auto-computed inertia.
A separate boolean toggle could also work. However, wouldn't that potentially break old projects?

**Comment by nehemiah-negussie** [comment]
Hi, I would like to take on this issue :)

**Comment by SekoiaTree** [comment]
Alternatively, how about a `_inertia` or `_internal_inertia` value? Backwards-compatible, seems easy enough.
