### ISSUE TITLE
Godot 4.0 (beta 8) bleeds shader texture

### ISSUE THREAD

**Issue by henriquelalves** [godotengine/godot#70165]
### Godot version

4.0 (beta 8)

### System information

Pop_OS

### Issue description

The same shader shows different meshes in Godot 4 beta 4 and beta 8 (in the following images, respectively):

![image1](https://user-images.githubusercontent.com/7095429/208176127-8d8b400c-ab30-497f-b134-fe30cde082e1.png)
![image2](https://user-images.githubusercontent.com/7095429/208176130-85fccc3b-f0ad-4c90-bc61-f33c042477fe.png)

The correct rendering would be the first screenshot (without the grass bleeding on the side). I'm just not sure if there was a regression in the render, or if Godot beta 8 actually is the correct behavior.

### Steps to reproduce

Just open the project on Godot beta 4 and beta 8.

### Minimal reproduction project

Example project: 
[ProjectExample.zip](https://github.com/godotengine/godot/files/10248558/ProjectExample.zip)

**Comment by clayjohn** [comment]
This is pretty interesting it seems that the normals are getting messed up somehow during the main rendering pass. However, if you look at the normals from the depth pass they look totally fine. Will need to investigate a little bit

**Comment by henriquelalves** [comment]
Yup! Those screenshots are from the project example, I'm just running the first screenshot on Beta 4, and the later on Beta 8

**Comment by clayjohn** [comment]
I think I misunderstood your first post. There indeed was a change in normals because we had a bug where the normals were being sent to the shader without being normalized. So users were getting some pretty wonky results. 

In this case the beta8 normals are more correct. 

I confused myself here by thinking you were comparing 3.5 to beta8. I even loaded the terrain model in Godot 3.5 to verify that the normals were the same in both versions lol. 

So I'm going to go ahead and close this because, although there was a change in behaviour, the previous behaviour was a bug and caused a bunch of other problems. Thank you for reporting this anyway!
