### ISSUE TITLE
Cannot compile Godot without x server - `scons x11=no`

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot#70199]
### Godot version

Godot beta 8

### System information

Ubuntu 22.10 - AMD RX 470, Gnome shell 43 X11

### Issue description

```
scons x11=no
```
show this error
```
platform/linuxbsd/os_linuxbsd.cpp: In member function 'virtual Vector<String> OS_LinuxBSD::get_video_adapter_driver_info() const':
platform/linuxbsd/os_linuxbsd.cpp:247:13: error: 'RenderingServer' has not been declared
  247 |         if (RenderingServer::get_singleton()->get_rendering_device() == nullptr) {
      |             ^~~~~~~~~~~~~~~
platform/linuxbsd/os_linuxbsd.cpp:251:46: error: 'RenderingServer' has not been declared
  251 |         const String rendering_device_name = RenderingServer::get_singleton()->get_rendering_device()->get_device_name(); // e.g. `NVIDIA GeForce GTX 970`
      |                                              ^~~~~~~~~~~~~~~
platform/linuxbsd/os_linuxbsd.cpp:252:48: error: 'RenderingServer' has not been declared
  252 |         const String rendering_device_vendor = RenderingServer::get_singleton()->get_rendering_device()->get_device_vendor_name(); // e.g. `NVIDIA`
      |                                                ^~~~~~~~~~~~~~~

```

### Steps to reproduce

Above

### Minimal reproduction project

N/A

**Comment by pfertyk** [comment]
I'd like to submit a fix. I'm not sure what should `OS_LinuxBSD::get_video_adapter_driver_info()` return when X11 is disabled, so I've set it to an empty Vector. If it should be a specific value, please let me know, I'll update the code.

I think that if X11 is disabled, GLES3 should also be disabled automatically. I'll check if it's possible to set it, since it would simplify my PR and would probably be the proper way of handling this situation (instead of adding double ifs everywhere). What do you think?
