### ISSUE TITLE
[GodotPhysics] Extremely odd Rigid capsule with Static cylinder collision

### ISSUE THREAD

**Issue by TheJazMaster** [godotengine/godot#70405]
### Godot version

4.0 beta 9

### System information

Manjaro 6.0.14

### Issue description

(3D) Rigid bodies with capsule shapes seem to have completely broken collision with static bodies with cylinder shapes, as they collide as if they were a cylinder of the same total height, and on top of that they don't topple at all when their centre of mass is over an edge.
![image](https://user-images.githubusercontent.com/47794482/208954595-ceb74474-8c05-425b-a2fa-a7c39b90e453.png)

### Steps to reproduce

Start a new project. In the 3D scene add a StaticBody3D with a cylinder collision shape and a RigidBody3D with a capsule collision shape. (Add a camera and meshes to see what's going on.) Move the RigidBody3D above the StaticBody3D so its centre of mass' downward projection doesn't hit the cylinder. Play the scene

For the minimal reproduction project: Play the scene

### Minimal reproduction project

[bug display.zip](https://github.com/godotengine/godot/files/10279550/bug.display.zip)

**Comment by Calinou** [comment]
This is likely fixed by https://github.com/godotengine/godot/pull/68958. Please [test that pull request](https://docs.godotengine.org/en/latest/community/contributing/testing_pull_requests.html) :slightly_smiling_face:

**Comment by TheJazMaster** [comment]
I'd test it, but there is no artifacts for the Linux build as far as I can tell, and the rest are expired.

**Comment by rburing** [comment]
This is probably due to the following code:

https://github.com/godotengine/godot/blob/b04bc494439193255c85ed9753d28aa92b5adcfa/servers/physics_3d/godot_collision_solver_3d_sat.cpp#L1721-L1727

My work-in-progress branch (slightly ahead of the linked PR) behaves as follows:

https://user-images.githubusercontent.com/229837/209014108-cf623114-3007-4a20-a54a-b93f6d8c223e.mp4

I will be continuing work on this (getting the PR out of draft status) soon.
