### ISSUE TITLE
TreeItem EraseButton does not work reliably

### ISSUE THREAD

**Issue by Dunkhan** [godotengine/godot#70423]
### Godot version

v4.0.beta9.mono.official [e780dc332]

### System information

Linux Mint 20.3 Cinnamon, NVIDIA Corporation TU106 [GeForce RTX 2070]

### Issue description

When calling EraseButton on a TreeItem with exactly one button, the following error occurs:

`ERROR: Index p_idx = 2 is out of bounds (cells[p_column].buttons.size() = 1).`

After investigating the cause is clear, the Erase function is taking the button id and passing it to the button array as an index. So if the first button you add has the id 0, and the second 1, and so on, the function actually works fine. Conversely if I set the button id to 99 the error says .

`ERROR: Index p_idx = 99 is out of bounds (cells[p_column].buttons.size() = 1).`

I have to assume that expecting the user to track the order that the buttons are stored in the internal array is not intentional. Should be simple enough to fix.

### Steps to reproduce

Just create a Tree with a TreeItem and then add a button to it with an id that is != 0
Then try to remove that button.

### Minimal reproduction project

c# (sorry I don't really do GDScript)

var Tree = new Tree();
var root = Tree.CreateItem();
var item = Tree.CreateItem(root);
item.AddButton(0, someRandomTexture2D, 99);
item.EraseButton(0, 99);

**Comment by Dunkhan** [comment]
For anyone experiencing this the workaround is to make sure your button id is always the same as the order it was added to the TreeItem, starting with 0. For more complex setups this could be difficult.

**Comment by DissonantVoid** [comment]
![b](https://user-images.githubusercontent.com/69814029/209018576-1ea7a44c-2fcc-48ec-8aa5-d6a34d651efe.PNG)
check the last line..
basically you're adding a child with an index of say 10, the child is added to the tree at position 10 but the problem is that the tree doesn't have 10 or more children so it puts the child at the next highest index, and since the tree has no children that highest index is 0, this is why trying to erase higher than 0 returns an error.

it is honestly your fault for not reading the docs, (or not understanding) but I think that Tree.CreateItem should return the new index where the item was inserted so we can avoid these issues

**Comment by Dunkhan** [comment]
That is the wrong section of the docs. The function in question is [TreeItem.AddButton](https://docs.godotengine.org/en/latest/classes/class_treeitem.html#class-treeitem-method-add-button):

***
void add_button ( [int](https://docs.godotengine.org/en/latest/classes/class_int.html#class-int) column, [Texture2D](https://docs.godotengine.org/en/latest/classes/class_texture2d.html#class-texture2d) button, [int](https://docs.godotengine.org/en/latest/classes/class_int.html#class-int) id=-1, [bool](https://docs.godotengine.org/en/latest/classes/class_bool.html#class-bool) disabled=false, [String](https://docs.godotengine.org/en/latest/classes/class_string.html#class-string) tooltip_text="" )

Adds a button with [Texture2D](https://docs.godotengine.org/en/latest/classes/class_texture2d.html#class-texture2d) button at column column. The id is used to identify the button. If not specified, the next available index is used, which may be retrieved by calling [get_button_count](https://docs.godotengine.org/en/latest/classes/class_treeitem.html#class-treeitem-method-get-button-count) immediately before this method. Optionally, the button can be disabled and have a tooltip_text.
***

It is honestly your fault for not reading the bug report, (or not understanding).
Note that to avoid this problem in the future, there is no reason to assign blame in a bug report. If I write a mistaken report (which happens often enough) I will be embarrassed enough without such comments.

On another note, the AddButton tooltip_text doesn't work. This probably requires another report though.

**Comment by Sauermann** [comment]
If you know, that `id != index`, as a workaround you could use `TreeItem.get_button_by_id`:
https://docs.godotengine.org/en/latest/classes/class_treeitem.html#class-treeitem-method-get-button-by-id

**Comment by DissonantVoid** [comment]
@Dunkhan apologies if I come off as rude, it wasn't my intention I'm just trying to lend a hand here. besides I don't see why one should be embarrassed for making such mistakes it happens all the time.
so I've done some digging in the source code of Godot and this is the problematic part:
![t](https://user-images.githubusercontent.com/69814029/209116230-f0cf5910-0ee1-4b2a-a7f4-dda00936c23b.PNG)
as you can see in the second line it checks if the index is valid by checking if it's smaller than 0 (ok makes sense) and bigger than the buttons size (what the??), so the same things I talked about with `Tree.create_item()` above is happening here, which shouldn't be the case according to the docs.
so we should either document this, just like it's documented in `Tree.create_item()` or change its behavior so that it loops all buttons in that column and finds the one with the erase id, as for the tooltip I think you should open a second issue for that.

**Comment by Dunkhan** [comment]
@DissonantVoid You are right it is the same thing, and to be fair, if I had read the entire documentation page for both Tree and TreeItem I would most likely have realised what was happening. I find it a little strange that an internal implementation detail like what order the buttons are stored in an internal array is the main way for users of the class to reference the buttons. Having said that this appears to be the standard way to do things across the entire UI library. Coming from other UI frameworks it can be especially problematic. Although it can be confusing and occasionally cause difficulties, to change that system in one place and not everywhere else would cause confusion for all the people that are used to the Godot way of doing things. Therefore I think the solution suggested by Sauermann is probably the best we can do.
