### ISSUE TITLE
Shader: can't use varyings as read-only parameters in custom functions

### ISSUE THREAD

**Issue by zhehangd** [godotengine/godot#70434]
### Godot version

4.0 Beta9

### System information

-

### Issue description

See this example:
```glsl
shader_type spatial;

varying float foo;

void function2(in float f) {
}

void function1() {
  // This is ok
  float bar = foo;
  function2(bar);
  // This is not ok (bug)
  // error: Varying 'foo' must be assigned in the vertex or fragment function first.
  function2(foo);
}

void vertex()
{
  foo = 1.0;
}

void fragment()
{
  function1();
  // This is ok
  function2(foo);
}
```

`foo` is a varying and is assigned in the `vertex` function.
In `fragment`, calling `function2(foo);` is ok as expected.
However, in `function1` calling `function2(foo);` is mistakenly marked as an error.
Instead, assigning `foo` to `bar` first then giving `bar` as the parameter is ok.

![Screenshot_20221221_235020](https://user-images.githubusercontent.com/9572364/209084406-6dadef24-51ba-4f8e-9b6a-c9ebd172e411.jpg)

### Steps to reproduce

-

### Minimal reproduction project

[varying_error.zip](https://github.com/godotengine/godot/files/10284816/varying_error.zip)

**Comment by Chaosus** [comment]
As a fix, you can place vertex() function above the function1, and it will work. I'm not sure whether it is a bug or just misunderstanding.

**Comment by Chaosus** [comment]
cc @clayjohn

**Comment by hmans** [comment]
This doesn't seem to be specifically related to varyings, but any global variable name. Functions are apparently not allowed to have parameters or local variables that shadow existing globals:

![image](https://user-images.githubusercontent.com/1061/224546508-0bab31b3-b13c-43ef-be4b-21b1fd2e24d8.png)
![image](https://user-images.githubusercontent.com/1061/224546542-34ff545d-a42d-4146-b118-d69f3900463c.png)

(The same for varyings and uniforms.)

This has the added repercussion of making the distribution (or general reuse) of _shader includes_ difficult (because now it's on the includes to never use a local variable that conflicts with any global scope variable in the shaders that include them.)
