### ISSUE TITLE
4.x project converter tool messes up super class constructor calls

### ISSUE THREAD

**Issue by Dante3085** [godotengine/godot#70542]
### Godot version

v4.0.beta10.official [d0398f62f]

### System information

Windows 11

### Issue description

If the following passes an argument to the constructor of the super class in past GDScript versions ([Docs](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html)):

```
func _init().("some_string_value", 34):
   pass
```

then the project converter tool consistently messes it up by just pulling the super constructor arguments into the self constructor, which results mostly in invalid code:
```
func _init("some_string_value", 34):
   pass
```

Something like this sould be correct I think:
```
func _init():
   super("some_string_value", 34)
```

### Steps to reproduce

1. Create a 3.5.1 project where the old super constructor call feature is used.
2. Use the project converter tool with 4.0.beta10.official and look at the resulting code.

### Minimal reproduction project

[super_constructor_project_converter_bug.zip](https://github.com/godotengine/godot/files/10299286/super_constructor_project_converter_bug.zip)

**Comment by stmSi** [comment]
`_init()` is not supposed to take any arguments/params.. no?

**Comment by Dante3085** [comment]
> `_init()` is not supposed to take any arguments/params.. no?

Search for **Class constructor** in these [docs](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html). That is where the following is from:
![image](https://user-images.githubusercontent.com/26558776/209482648-e7fe7bd7-1480-4c0a-a70a-e9e31fc7a33b.png)

As I understand it, this is how you create constructors for user defined types.

**Comment by Calinou** [comment]
cc @qarmin @feralbytes

**Comment by vnen** [comment]
I'm not familiar with the project converter but I took a peek for this to see if it was easy to fix. I found out that the `_init` function is transformed to remove the `-> void` if present:
https://github.com/godotengine/godot/blob/e0de3573f3fc86062763152f5a1ac62f5a986da3/editor/project_converter_3_to_4.cpp#L1928-L1938

However, the mentioned issue is fixed, current master does allow `void` as return type for the constructor. This was solved after the converter was made but before it was merged so it slipped through.

The low hanging fruit is to just remove this rule, since it's likely what's causing this issue. I would still be invalid syntax but at least wouldn't be a wrong conversion, just a missing one.

I don't know how easy it would be to convert this to the `super()` syntax, as I'm not sure how the converter handles multiple lines in the output.

**Comment by rcorre** [comment]
I'm taking a look at this now. It does seem like it's possible to have the converter replace one line with multiple lines:

```diff
@@ -129,9 +132,10 @@ class Text:
 class Boolean:
        extends Setting
 
-       var value: bool setget set_value, get_value
+       var value: bool : get = get_value, set = set_value
 
-       func _init(section: String, key: String, default: bool).(section, key, default) -> void:
+       func _init(section: String, key: String, default: bool):
+               super(section, key, default)
                pass
 
        func normalize(val):
```
