### ISSUE TITLE
Expression evaluater for debugging gdscript

### ISSUE THREAD

**Issue by CombustibleLemonade** [godotengine/godot#7057]
I would like to propose adding an expression evaluator to the gdscript debugger. This would be a text field where the user could enter a gdscript expression, and that expression would be evaluated in a certain context (perhaps the current debugging context, perhaps the context of the selected node in the live scene tree). The result of that evaluation would be shown to the user.

A text field and label for this could be added somewhere in the debugger->debugger tab, and/or the debugger->remote inspector tab, and the expression would be evaluated for that context.

**Comment by akien-mga** [comment]
We dicussed this on IRC #godotengine-devel a couple weeks ago or so, if someone wants to grep the logs to link them here :)

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9e7cee2 : not implemented yet. This would be very useful to have.

**Comment by nonbeing** [comment]
This feature would be really helpful - it would obviate the multitude of print statements that are currently needed for debugging.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
