### ISSUE TITLE
TileSet does not keep friction property after conversion

### ISSUE THREAD

**Issue by ivanskodje** [godotengine/godot#7059]
**Operating system or device - Godot version:**
2.2

**Issue description** (what happened, and what was expected):
The TileSet does not keep friction property after conversion. 
Using a StaticBody2D and setting the friction to 0 does not work properly. 
It acts as if it had friction with a value of 1 when you place it with the TileMap node.
This causes other RigidBody2D's to stop, even when it is supposed to slide, regardless of the friction value of the body itself.

**Steps to reproduce:**
1. Create tileset with a staticbody2d tile and a collision box. 
2. Set friction to 0 on the tile
3. Convert to a tileset
4. Create a player or another rigidbody2d and make it move on top of the tile - it stops

**Comment by bojidar-bg** [comment]
There is a friction property on the TileMap itself.

**Comment by eon-s** [comment]
The thing is that the tileset does not store any information about characteristics of the staticbody and I don't know if will be good to add more data to a tile when you can make multiple tilemaps with different static features.

**Comment by Tybobobo** [comment]
As an user; I would rather have the engine do a little extra work storing extra data from each tile, in order to get a clean and user-friendly TileMap in the scene tree - not having to micromanage each TileMap for unique tiles. I hope we get this "suggested feature" in the future. Would make it overall more user-friendly and more intuitive for existing and new users of Godot to keep tile properties on tilesets. :)

**Comment by eon-s** [comment]
@Tybobobo you mean something like this? #3089

**Comment by Tybobobo** [comment]
Exactly! :)

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by mayuso** [comment]
I can confirm this issue still exists in 3.0.3.

I have 2 different scenes that contain 2 different types of blocks, each with different properties (including friction). When I export all of them to the tileset each ones friction is completely ignored and the tilemap uses its own ("global") friction value for every tile in it.

Right now I don't know how to set friction individually for each type of tile.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
