### ISSUE TITLE
Better tools for check method parameters

### ISSUE THREAD

**Issue by HeartoLazor** [godotengine/godot#7072]
**Operating system or device - Godot version:**
Windows 10
Build compiled from this commit https://github.com/godotengine/godot/commit/611a94e3a673a61b51746366366c698c66ef0195
because in 2.1 stable get_method_list crash

**Issue description** (what happened, and what was expected):
1. I need to check how many parameters are needed to call a method, taking in account the optional ones. has_method only check if the method exist, and with get_method_list I couldn't find a way for check if a parameter is optional. 
2. get_method_list is **SLOW** for check if a method exist with n parameters, maybe create a variation of has_method which seems faster, like has_method(method_name, parameter_number = -1) for example and return true if the method could be called with that parameter number?, Of course taking in account optional parameters and parameter_number = -1 is the same behavior as current version.

**Steps to reproduce:**
Create a node with a method using optional parameters
example: func hello(param_a, param_b, param_c = 1, param_d = 2)
try to find a way to check if you could call the method with a number of parameters, for example:
func check_method_with_parameters(method_name,parameter_number)
that method should return true with the variations:
check_method_with_parameters("hello",2)
check_method_with_parameters("hello",3)
check_method_with_parameters("hello",4)

**Comment by bojidar-bg** [comment]
I think this is closed in 3.0/master with the new ClassDB?

**Comment by HeartoLazor** [comment]
@bojidar-bg Playing with ClassDB directly doesn't seems to solve this problem.
Looking at the documentation:
http://docs.godotengine.org/en/latest/classes/class_classdb.html
Almost all methods required a ClassName, where the class name is seems to be one of the base classes from godot, listed in next image:
https://i.imgur.com/VaHzvBc.png
![alt text](https://i.imgur.com/VaHzvBc.png "Image")
I'm trying to poll gdscripts, as my example:
![alt text](https://i.imgur.com/iPYOUfn.png "Image")
So, I didn't find anything new to resolve this issue in 3.0.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by HeartoLazor** [comment]
At least 3.0.2 doesn't seem to have a fastest way to check the number of parameters.
So this issue is still open.

**Comment by akien-mga** [comment]
I can confirm that ClassDB only seems to let you inspect the base classes of the engine, and not user-defined ones yet.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
