### ISSUE TITLE
rename Tween's stop() and stop_all() methods to pause() and pause_all()

### ISSUE THREAD

**Issue by wingedadventurer** [godotengine/godot#70747]
### Godot version

3.5.1.stable

### System information

N/A

### Issue description

there's some slight inconsistency with naming some methods.

Tween:
start() - starts interpolating
stop(...) - stops an active interpolation
continue(...) - continues a stopped interpolation

Timer:
start() - starts ticking
stop() - stops an active timer and resets its time_left to 0.
paused = true - pauses an active timer
paused = false - continues an active timer

Tween.stop(...) is actually pausing the interpolation, without resetting its value. i think it would be more appropriate to call it Tween.pause(...) instead.

this only applies to Godot 3. in Godot 4 the way the tweens work has changed and it includes pause() method.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
We can't rename Godot 3 methods, because it breaks compatibility. `pause()` could be an alias, but it would be confusing.

**Comment by YuriSizov** [comment]
Indeed, we cannot make breaking changes in Godot 3, and we typically don't rely on aliases so all users can rely on a single way to achieve the desired result. In either case, a feature enhancement should go to the proposals repository.

https://github.com/godotengine/godot-proposals

Please be mindful of the submission form and rules. If in doubt, start a discussion instead of opening an issue.
