### ISSUE TITLE
KinematicBody (with RayShape) sinking through floor

### ISSUE THREAD

**Issue by ReturnMinusOne** [godotengine/godot#70757]
### Godot version

v3.5.1.stable.arch_linux

### System information

Manjaro Linux (kernel 6.1.1-1)

### Issue description

CollisionShapes inside KinematicBody objects don't appear to function properly when they use a RayShape.

The KinematicBody will sink through the floor (rather slowly), and fall through unless it has another CollisionShape child.

### Steps to reproduce

1. Create a KinematicBody.
2. Give it a CollisionShape as a child.
3. Give the CollisionShape a RayShape.
4. Place the KinematicBody over a simple CSGMesh floor or a StaticBody with a BoxShape CollisionShape.
5. Attach a script to the KinematicBody wherein the move_and_slide() function is called with gravity.

### Minimal reproduction project

[Example.zip](https://github.com/godotengine/godot/files/10326706/Example.zip)

In this example project, the camera can be moved with the mouse and the KinematicBody can jump with the space bar.

Notice how the RigidBody stays on top of the surface, but the KinematicBody sinks.

**Comment by Calinou** [comment]
Can you reproduce this after switching the 3D physics engine to **GodotPhysics** in the Project Settings?

**Comment by Hiiamwilliam** [comment]
The code makes vertical velocity increase at every `_physics_process` step. Eventually, the velocity will try to travel a length greater than what the `RayShape` can separate, thus you sink into ground.

However, Bullet and GodotPhysics have different behaviours:
- Bullet: sinks into ground a little bit every physics tick. Maybe the `RayShape` separation is done with a delay. Eventually, will tunnel through the ground.
- GodotPhysics: stays separated correctly, until, from what I understand, the attempted travel distance is larger than `RayShape`'s length. In that moment, the entire `RayShape` tunnels through the ground.

The Capsule collision shape doesn't seem to tunnel/sink in this example.

You can prevent this by setting the vertical velocity (mVerticalMove in your code) to zero if `is_on_floor` is true.

**Comment by ReturnMinusOne** [comment]
Thank you both. The behaviour did indeed change according to the physics engine used, with Godot Physics keeping the object in place for a moment, until the Ray collision abruptly stops working.

The example I provided was a heavily simplified version of the movement system I used in a much more complicated project, which, upon closer inspection, still handles gravity in a very simplistic and incorrect way.

I had the impression that the ground collision worked correctly in Windows, but not in Manjaro; this may have been my mistake, though older builds haven't given me consistent results so I'm not sure. In any case, the new code appears to work properly with both physics engines, and across operating systems.

I now check if the character is on the floor, in which case the downward pressure is reset to `gravity * delta`. I also check the jump afterwards, instead of beforehand:

```
	if ( !is_on_floor() ):
		mVerticalMove += gravity * delta;
	else:
		mVerticalMove = gravity * delta;
		
	if ( Input.is_action_just_pressed( "JUMP" ) && is_on_floor() ):
		mVerticalMove = 5;
		
	velocity.y = mVerticalMove;
```

If I may ask, however... It seems that the gravity needs to be multiplied by `delta` (as seen in the code above). Why is this? According to the docs, `move_and_slide()` "uses the physics step's delta value automatically in calculations".

**Comment by Hiiamwilliam** [comment]
The docs state that because there is another method, `move_and_collide`, which does not automatically use delta. This means you need to do e.g. `move_and_collide(velocity * delta)`.

Basically, delta represents the time between calls to the physics engine (physics step). By default, physics calls try to happen 60 times per second, so delta ~= 1/60 seconds.
In your code, mVerticalMove is added 9.8 every physics step. In 1 second (60 steps), you'll have traveled 9.8 * 60 = 588 meters.
When you multiply by delta, you get more normal results. In 1 second, you'll have traveled 9.8 * 60 * (1/60) = 9.8 meters.

So that's why multiplying by delta is necessary: to adjust the value, not because `move_and_slide` cannot work without it. In fact, if you don't multiply by delta, both `move_and_xxx` will work - but their result will be likely be unexpected in terms of values.

**Comment by ReturnMinusOne** [comment]
I understand multiplying the motion by the frame time, but if `move_and_slide()` does it automatically, why does the gravity need to be multiplied by delta while the horizontal motion does not?

The character's horizontal movement speed (`moveSpeed`) is 6 units; but it moves 6 units per second, not per frame.

**Comment by Hiiamwilliam** [comment]
> but it moves 6 units per second, not per frame.

That's what the doc refers to when it states that `move_and_slide` uses the physics step automatically.

Now, about why would you need to multiply gravity, but not horizontal motion? Good question, I don't know.
I'd imagine it's due to things like jumping, where you need to set a vertical value in a single frame. If vertical velocity was automatically multiplied by delta, jumping would need to be divided by delta, and that's weird. But all in all I'm not sure, never thought about this...

**Comment by ReturnMinusOne** [comment]
`move_and_slide()` is a puzzling function in Godot, especially since the similar `move_and_collide()` method doesn't use `delta`...

I'm curious to see if the physics processing evolves in this regard, though right now, the "latest" documentation suggests it won't change in 4.0, with [PhysicsBody3D.move_and_collide()](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html#class-physicsbody3d-method-move-and-collide) expressly advising multiplication by `delta`, and [CharacterBody3D.move_and_slide()](https://docs.godotengine.org/en/latest/classes/class_characterbody3d.html#class-characterbody3d-method-move-and-slide) not even mentioning it.

But for now, I at least know that multiplying _vertical_ velocity does require `delta`. At any rate, the immediate problem was simply due to the excessive downward force applied to the character each frame. That problem being solved, I'm okay with closing this issue. Thank you again.
