### ISSUE TITLE
Overlapping transparent shader materials cancel out in GD 4 beta 10 but not 9

### ISSUE THREAD

**Issue by timshannon** [godotengine/godot#70753]
### Godot version

v4.0.beta10.mono.official [d0398f62f]

### System information

Ubuntu 22.04

### Issue description

This may not be an issue, as I'm very new to shaders, but I had noticed that the behavior in two of my shaders has changed between betas 9 and 10.

I have a water shader, then a separate shader applied to a plane in front of the camera to add a water effect when the players camera goes underwater.

In beta 9, everything works as expected.  You can see the warping effect of the screen overlay as well as back, non-culled face of the water surface.  In beta 10, you can only see the screen overlay, and the water surface completely disappears.

Once again, this may be due to an issue in my shaders, so keep that in mind.  Also it's important to note that this behavior only applies to the back face of water mesh.  The behavior is the same (not blending the effects) for the front face in both betas.

Beta 9:
![image](https://user-images.githubusercontent.com/1330485/210113464-97880f27-e772-40f7-8f85-abc1b52a8d60.png)

Beta 10:
![image](https://user-images.githubusercontent.com/1330485/210113418-02e63b63-bdf3-4fba-a392-786b53ec2281.png)

### Steps to reproduce

Simply open up the attached project and view the main.tscn scene from the camera.  Half the camera is covered with the screen overlay, and half isn't.  In beta 9, you can see both effects, in beta 10, you can only see one.

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/10326345/bug.zip)

**Comment by clayjohn** [comment]
I'm not sure if this is a bug. I think this is a change in behaviour introduced by https://github.com/godotengine/godot/pull/69998, but I am fairly certain the behaviour in beta 9 was a bug. If you take a look at the scene in beta 9 you will see that the overlay you have added only effects the portion of the screen not covered by the "water" block. 

So in Beta 9 what is happening is the overlay is drawn first, then the water is drawn second which draws over the overlay (i.e. the overlay does not affect the water block). Although from some angles the water is properly drawn first which causes the overlay to flicker in and out.

_Beta 9_
![Screenshot from 2023-01-10 11-56-35](https://user-images.githubusercontent.com/16521339/211649648-26e638b0-5d3f-4f00-9274-4a216cab8536.png)

In Beta 10 and above, the overlay appears to be properly sorted so that it always draws after the "water" block. This causes it not to display the water as its entire color comes from the SCREEN_TEXTURE which only captures opaque objects. 

To illustrate what is going on I modified the shader code for the overlay to tint it yellow. Here is how it looks in Beta 9:

![Screenshot from 2023-01-10 12-01-24](https://user-images.githubusercontent.com/16521339/211650671-8a02962e-dd59-46ed-b42b-eda55ce87982.png)

And in Beta 10/11:

![Screenshot from 2023-01-10 12-02-03](https://user-images.githubusercontent.com/16521339/211650682-32481991-98fe-4d1b-aa31-7d523adc4560.png)

Note how in Beta 9 the water is drawn overtop of the overlay and in Beta 10/11 the overlay is properly drawn on top

**Comment by timshannon** [comment]
I was suspecting something along those lines.  Thanks for looking into it.
