### ISSUE TITLE
Core Api Hash Mismatch Error Test

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#70829]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

See "Steps to reproduce" for details
In fact, In fact, I found an issue with the same situation(https://github.com/godotengine/godot/issues/35290) ,but it had been closed

### Steps to reproduce

Create an empty project
Exported it in debug mode
Run it in CMD
See error message " Mono: Core API hash mismatch. ".This doesn't affect the game, but I think it's a bug that needs to be fixed

### Minimal reproduction project

An empty project

**Comment by AThousandShips** [comment]
If you read the [comments](https://github.com/godotengine/godot/issues/35290#issuecomment-575981861) in the other issue you will see that this is not an error that causes any problems, please don't open new issues when there is another issue.

**Comment by YuriSizov** [comment]
Well, the other issue was closed because it was supposed to be fixed in 3.2. And this report is for 3.5, so I think it's fair to open a new issue (though we could of course also reopen the old one if it was brought up there, but it doesn't matter at this point).

**Comment by AThousandShips** [comment]
Thank you, I'm sorry I had missed that it got resolved and thought it was just a false positive

**Comment by XenonSheng** [comment]
May I know this issue is going to solve or how to solve it temporarily from my side? I'm currently using the Godot LTS v3.5.2 mono and also downloaded the official templates from editor. Currently, still have this error in console logs for HTML5 web platform.

From last reply in #74658 , if template executable has a different version than the editor, how to update the template executable version for web? Thanks a lot if someone can help XD
