### ISSUE TITLE
Quaternion.GetEuler() and Quaternion(Vector3 eulerYXZ) not found in Godot 4.0.beta10.mono

### ISSUE THREAD

**Issue by maximiliancsuk** [godotengine/godot#70822]
### Godot version

4.0.beta10.mono

### System information

Windows 11

### Issue description

When trying using the method `Quaternion.GetEuler()` or the constructor `Quaternion(Vector3 eulerYXZ)`, I'm getting MissingMethodExceptions in the current Godot 4.0.beta.10.mono.
```
E 0:00:02:0034   Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* ): System.MissingMethodException: Method not found: 'Godot.Vector3 Godot.Quaternion.GetEuler()'.
  <C++ Error>    Exception
  <C++ Source>   :0 @ void root._Process(Double )()
  <Stack Trace>  :0 @ void root._Process(Double )()
                 Node.cs:1809 @ Boolean Godot.Node.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )()
                 CanvasItem.cs:1443 @ Boolean Godot.CanvasItem.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )()
                 Control.cs:3155 @ Boolean Godot.Control.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )()
                 root_ScriptMethods.generated.cs:38 @ Boolean root.InvokeGodotClassMethod(Godot.NativeInterop.godot_string_name& , Godot.NativeInterop.NativeVariantPtrArgs , Godot.NativeInterop.godot_variant& )()
                 CSharpInstanceBridge.cs:24 @ Godot.NativeInterop.godot_bool Godot.Bridge.CSharpInstanceBridge.Call(IntPtr , Godot.NativeInterop.godot_string_name* , Godot.NativeInterop.godot_variant** , Int32 , Godot.NativeInterop.godot_variant_call_error* , Godot.NativeInterop.godot_variant* )()
```

### Steps to reproduce

A simple C# script should be enough to reproduce the error:
```
public partial class root : Control
{
  public override void _Process(double delta)
  {
    var q = Quaternion.Identity;
    var eu = q.GetEuler(); // <- throws C++ exception
  }
}
```

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
> the constructor `Quaternion(Vector3 eulerYXZ)`

There's no such constructor, there's `Quaternion.FromEuler(Vector3 eulerYXZ)` static method instead:
https://github.com/godotengine/godot/blob/57267709e665f1683e79bd5d3432be2be5db6c1d/modules/mono/glue/GodotSharp/GodotSharp/Core/Quaternion.cs#L570-L576

---

> A simple C# script should be enough to reproduce the error:
> 
> ```
> public partial class root : Control
> {
>   public override void _Process(double delta)
>   {
>     var q = Quaternion.Identity;
>     var eu = q.GetEuler(); // <- throws C++ exception
>   }
> }
> ```

Can't reproduce, works just fine for me (v4.0.beta10.mono.official [d0398f62f]).

**Comment by raulsntos** [comment]
The `MissingMethodException` means that the method you are using could not be found, this is because the GodotSharp assembly referenced by the Game assembly and the one used on runtime are different.

One of the reasons why we ask for a minimal reproduction project is to check the `.csproj` file and other things that could be causing the issue. In this case, I would make sure the Project Sdk is the right version (should be `Godot.NET.Sdk/4.0.0-beta.10`).

Are you referencing other C# projects? Make sure they also reference the same version of the GodotSharp assembly; otherwise, the may be using methods that no longer exist.

In your case, the `Quaternion.GetEuler()` method does not exist, it was replaced with `Quaternion.GetEuler(EulerOrder order = EulerOrder.Yxz)`, since the parameter is optional you may think it's the same method but the method signature is different which means this breaks binary compatibility so an older version of the GodotSharp assembly would reference a different method, causing the `MissingMethodException`.

**Comment by maximiliancsuk** [comment]
> Are you referencing other C# projects? Make sure they also reference the same version of the GodotSharp assembly; otherwise, the may be using methods that no longer exist.

That was exactly it! I have a multi-project setup and forgot to update the reference in one of the projects... silly me! Sorry for the false alarm, teaches me that I should always test in a minimal sample project first before opening an issue.
