### ISSUE TITLE
Billboard Material not working in Double Precision Build

### ISSUE THREAD

**Issue by scuzzar** [godotengine/godot#70845]
### Godot version

Godot 4.0 [57267709...] + precision=double

### System information

Windows 11

### Issue description

If i open the attatched project in my custom build using precision=double, the billboard of the particles is seaming not to work, basicaly ignoring the billboard setting all togeter.

I am using a QuadMesh as particle Mesh.

![grafik](https://user-images.githubusercontent.com/33227147/210270466-7a577d17-9374-4aed-b15c-fe7ad4e692d2.png)

Opening the same Project in without the precision=double setting, and it is working.

![grafik](https://user-images.githubusercontent.com/33227147/210270695-31a24536-bef3-4823-8243-d31af2ff9db1.png)

### Steps to reproduce

build using precision=double (i tryed several commits, all the same)

create CPUParticles3D

Add a Quad Mesh

Add a Material to the Mesh

Set Billboard to On

### Minimal reproduction project

[Billboard_Bug.zip](https://github.com/godotengine/godot/files/10333196/Billboard_Bug.zip)

**Comment by jwatsn** [comment]
Not sure if this will help, but I've noticed this bug is caused due to not being able to modify MODELVIEW_MATRIX in the shader vertex function when in double precision build. I found a work around:

VERTEX *=  mat3(MODEL_MATRIX * mat4(VIEW_MATRIX[0], VIEW_MATRIX[1], VIEW_MATRIX[2], VIEW_MATRIX[3]));

But this wont work in things like Label3D or Sprite3D since you can't edit its shader

**Comment by cridenour** [comment]
This will be fixed by #75462.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot/issues/75433, which has more information about the issue at hand.
