### ISSUE TITLE
CharacterBody3D process_mode reenabled while colliding Area3D leads to Error "p_elem->root is true"

### ISSUE THREAD

**Issue by BenjaminSchulte** [godotengine/godot#70848]
### Godot version

v4.0.beta.custom_build.b29bb11a4

### System information

Ubuntu 20.04.3 LTS, Vulkan, TU116 [GeForce GTX 1660 Ti], nvidia 470.161.03

### Issue description

If you reactivate a disabled CharacterBody3D (process_mode = DISABLED) with process_mode = INHERIT **while** the body is inside an area the following error appears:

```
ERROR: Condition "p_elem->_root" is true.
   at: add (./core/templates/self_list.h:46)
```

I did some (unfinished) debugging and figured out some kind of backtrace:
- GodotBody3D::set_space()
- GodotCollisionObject3D::_set_space()
- GodotCollisionObject3D::_update_shapes()
- GodotBroadPhase3DBVH::create()
- BVH_Manager::create()
- BVH_Manager::_check_for_collisions()
- BVH_Manager::_collide()
- GodotSpace3D::_broadphase_pair()
- GodotAreaPair3D::GodotAreaPair3D()
- p_body->set_active(true); **First time adding the item to the list**
- GodotBody3D::set_space() **Second time adding the item to the list**

### Steps to reproduce

- Create a new project
- Add a CharacterBody3D with a collision shape
- Add an Area3D with a collision shape
- Ensure that both objects collide
- Use anything to set the CharacterBody.process_mode = Node.PROCESS_MODE_DISABLED
- Use anything to set the CharacterBody.process_mode = Node.PROCESS_MODE_INHERIT

### Minimal reproduction project

[SelfListBugCharacterBody3D.zip](https://github.com/godotengine/godot/files/10333220/SelfListBugCharacterBody3D.zip)

**Comment by hsandt** [comment]
Same issue in 2D. I tried to create a minimal repro by killing some character (= make it invisible and set process mode to disable) via a hitbox and resurrecting it (= make it visible and set process mode to enabled), but the error didn't reappear. Only my full game with a melee attack animation containing an event callback triggering the hit actually enables the error.

I'll try to find the middle ground for a minimal repro that doesn't need the full animation stuff, but I'm not sure what I really need. Hopefully the 3D example will help you find how to fix it in 2D.

(alternatively, I can also provide the full project if needed, after I swap sprites for non-licensed ones)

**Comment by hsandt** [comment]
OK, I managed to extend your bug to 2D, and also tested the case of physics process where the conditions to trigger the issues are different, and where it's easy to fix the error in one line.

I could not manage to reproduce the duplicate physics body in the MWE, only in my actual game, and even fixing the "p_elem->root is true" error doesn't avoid duplication anyway, so both seem unrelated. Therefore I'll open a new issue for the duplication.

I will rewrite repro steps for the new project I created from yours, which combines 2D and 3D scenes and scripts:

After disabling a CharacterBody2D/3D inside an Area2D/3D with a proper collision shape, if you reenable ityou may get the error "Condition "p_elem->_root" is true."

- if this happens on a timeout signal, error occurs anyway
- if this happens during a process/physics process, error can be avoided with `await get_tree().physics_frame`, `await get_tree().process_frame`, `await get_tree().create_timer(0.1).timeout` before re-enabling, or moving the node at any time in that frame

Other types of PhysicsBody2D/3D nodes don't seem to trigger the error.

Simple callstacks:

2D
> E 0:00:01:0934   BaseCharacter.gd:161 @ restart(): Condition "p_elem->_root" is true.
  <C++ Source>   ./core/templates/self_list.h:46 @ add()
  <Stack Trace>  BaseCharacter.gd:161 @ restart()
                 Level.gd:7 @ _unhandled_input()

3D
> E 0:00:00:0587   Test3D.gd:17 @ _on_timer_timeout(): Condition "p_elem->_root" is true.
  <C++ Source>   ./core/templates/self_list.h:46 @ add()
  <Stack Trace>  Test3D.gd:17 @ _on_timer_timeout()

Repro steps:

1. Open Test2D/3D.tscn. Make sure that Test2D/3D root node > Test With Physics Process is unchecked so it works on timer
2. Play the scene
3. Observe error in Output after 0.1s
4. Stop game, and this time, check Test2D/3D root node > Test With Physics Process is unchecked so it works on process
5. Play the scene
6. Observe error spam in Output
7. Repeat steps after uncommenting some of the lines in Test2D/3D.gd. Note how _on_timer_timeout always causes an error, while _physics_process can be fixed with any line. 

2D/3D hybrid project:

[Issue 70848 - SelfListBugCharacterBody3D-2D hybrid.zip](https://github.com/godotengine/godot/files/11264261/Issue.70848.-.SelfListBugCharacterBody3D-2D.hybrid.zip)
