### ISSUE TITLE
NavigationServer3D not automatically registering NavigationRegion3D

### ISSUE THREAD

**Issue by mandomal** [godotengine/godot#70855]
### Godot version

master 4.0 beta 10

### System information

Windows 10

### Issue description

A stated in the [documentation](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationregions.html) for the new framework in which navigation is managed, navigation mesh regions should be added to the navigation server automatically.

This allows the developer to call functions from the region such as `get_path()`, in the same way you would using the Navigation node from Godot 3.X.

When checking the NavigationServer3D for map ids, it returns only the default 3D and 2D maps it creates. We should expect 3 ids when checking.

### Steps to reproduce

Run the project provided below. The editor output will demonstrate that the navigation map's RID is not in the list of the ones in the NavigationServer3D.

### Minimal reproduction project

[NavigationServerExample.zip](https://github.com/godotengine/godot/files/10333905/NavigationServerExample.zip)

**Comment by smix8** [comment]
You are missing the documentation part about NavigationServer synchronisation [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationservers.html#waiting-for-synchronisation).

When you query the server in a _ready() function at game start you are querying against empty navigation maps cause the nodes from the SceneTree had no time to sync with the server.

**Comment by mandomal** [comment]
I guess there's a big disconnect for me with using this new paradigm versus the old one with asking for a path from the Navigation server. I'm attaching an update to the project below to demonstrate my typical point of entry to working with the NavigationServer.

[NavigationServerExample_WithClick.zip](https://github.com/godotengine/godot/files/10334132/NavigationServerExample_WithClick.zip)

If you click on the screen on the black circles. You should get a path that goes from the origin, to the closest point to the intersection of a camera's ray based on your click. If you click outside the circle I imagine it would just grab the point closest to the edge.

This adaptation was take from the way that [this project](https://godotengine.org/asset-library/asset/124) lets you navigate. I have a modified example of the same example below where I've replaced the code's navigation code to use the Navigation
Server and it seems to work exactly the same as the original project.

[3d_navmesh_modified.zip](https://github.com/godotengine/godot/files/10334128/3d_navmesh_modified.zip)

**Comment by smix8** [comment]
If you replace in your new example the `"self.get_region_rid()"` code parts with `"get_world_3d().navigation_map"` your example works and returns a path.

I think you are confused about `map` and `region` because in the newer test project you tried to use the region RID returned from `get_region_rid()` in the `map_get_closest_point_segment()` function that requires a `map` as the first parameter, not a `region`.

The "NavigationRegion3D" node is basically the same as the old Godot <=3.5 "NavigationMeshInstance" node, just renamed.

The "Navigation" node of old does no longer exist, the replacement for this navigation "world" is the abstract navigation `map` on the NavigationServer. This map is automatically created when Godot creates the 3D viewport world. All navigation related 3D nodes like NavigationRegion3D / NavigationAgent3D and NavigationObstacle3D join this map automatically so normally you dont have to bother with it. If you need this map to use NavigationServer functions you can use the mentioned get_world_3d().navigation_map on any Node3D inheriting node to receive the required map RID.

**Comment by mandomal** [comment]
Thanks for your help I will close this. Is there a reason why we have to specify which world we're using here? I understand there are a lot of situations where this new framework is easier and more flexible to use. But here it seems like a step was taken backwards in terms of workflow from Godot 3.X.

**Comment by smix8** [comment]
When you use the NavigationServer API directly the function and server can not know what map you want to query. In the old Godot <=3.5 the "Navigation" node was a self-contained (but also very limited) "map" that required that NavigationMeshInstance nodes are placed as child nodes. It did not need a parameter for the map in the function cause it was the map, everything was stored on the limited node and not on a server. It also did not need to know which regions are registered on its server map cause the regions where plain child nodes to collect. The child node placement restriction alone created immense node placement problems on more complex projects hence why this requirement was removed and in the new navigation the NavigationRegion3D can be placed anywhere. The problem is that you can never just assume that all regions will use the default map or the map from the Navigation node as in the new navigation you can change the map of any navigation object at any time.
