### ISSUE TITLE
get_current_navigation_path bug

### ISSUE THREAD

**Issue by cora-schallock** [godotengine/godot#70905]
### Godot version

4.0.beta10

### System information

Windows 10

### Issue description

The output of ` $NavigationAgent2D.get_current_navigation_path()` changes depending on if `$NavigationAgent2D.is_target_reachable() `  is called or not.

### Steps to reproduce

The minimal reproduction project below contains a tile map with two tiles, where the blue tiles have a navigation layer shape and the green tiles do not. 

To reproduce the bug follow the steps below:
1) Open the project and run the test scene
2) Left Click on a blue tile in the tile map and move your cursors, note nothing happens.
![commented_out](https://user-images.githubusercontent.com/89163951/210493592-5a20a48a-b7d8-4bbc-a7c5-d566d4702908.png)
3) Go into the the `Navigator.gd` file and uncomment out line 19 (the line with `is_target_reachable()`)
4) Rerun the test scene
5) Left click on a blue tile in the tile map and move your cursor. Now a white line should appear previewing the current navigation path.
![uncommented](https://user-images.githubusercontent.com/89163951/210493590-55dc4d08-b835-4c7e-a26d-e51a9eb7e37e.png)

### Minimal reproduction project

[navigator_agent_bug.zip](https://github.com/godotengine/godot/files/10341728/navigator_agent_bug.zip)

**Comment by cora-schallock** [comment]
I wanted to add that I saw the note in the documentation for the `get_current_navigation_path()` function that says `Use the intended get_next_location() once every physics frame to receive the next path point for the agents movement as this function also updates the internal path logic.`.

The reason I'm using `get_current_navigation_path()` is I'm trying to debug the navigation layer and check that I setup the tile map correctly, so since I'm not actually moving anything (just trying to visualize the path) I tried using this function as opposed to `get_next_location()`.

**Comment by smix8** [comment]
You already mentioned the important part. Not all the available functions do update the NavigationAgent internal path.

Specifically it only updates once each physics_frame and only when get_next_location() or is_navigation_finished() or get_final_location() is used.

I wouldn't say this issue is a plain bug, more an limitation of the current NavigationAgent design that was intentionally limited to a single update each physics_frame. If all the utility functions would trigger the update the important path movement updates wouldn't go through reliably.

For pure debug paths I suggest it would be better to use the NavigationServer.map_get_path() directly instead of using a "dummy" NavigationAgent.

**Comment by smix8** [comment]
This can be closed. It is as mentioned documented behavior and the NavigationServer.map_get_path() should be prefered to get pure path arrays. We also added NavigationAgent path debug visuals in recent beta so there is now a build-in feature for debug path visuals.

**Comment by Calinou** [comment]
Closing per @smix8's comment.

**Comment by Muhammad-Fiqri** [comment]
> This can be closed. It is as mentioned documented behavior and the NavigationServer.map_get_path() should be prefered to get pure path arrays. We also added NavigationAgent path debug visuals in recent beta so there is now a build-in feature for debug path visuals.

but it still a bug none the less, you guys need to fix this if yall didn't want redot to take over
