### ISSUE TITLE
Input event triggering is unstable

### ISSUE THREAD

**Issue by L2750558108** [godotengine/godot#71155]
### Godot version

3.5.1mono

### System information

windows10

### Issue description

My sample project outputs a time every frame and the state of this input event every time A is pressed or released. If you just press A, you will get the "JustPress" output; If you hold down the A key, you will get the output of "Hold"; If you just release the A key, you will get the output of "JustRelease".

Run my sample project, then press the A key, release after 5 seconds. Close the program, analyze the output, and you can see that there is a lot of frames between the "JustPress" and "Hold" outputs, and there are two or three frames between each "Hold" output. These are unstable, especially when you need to work _Input functions and _Process functions together to process input, which can cause serious problems.

### Steps to reproduce

See "Issue description"

### Minimal reproduction project

[InputEvent Test.zip](https://github.com/godotengine/godot/files/10381561/InputEvent.Test.zip)

**Comment by henriquelalves** [comment]
I don't think this is an issue, it's just how the "input" function and "echo" input events works.

The "input" function doesn't run every frame; it only runs when there is an InputEvent to be handled by the class. So the frames your function runs depends on the user OS. The "echo" boolean is just a way for you to know there wasn't a "release" event for that key before the last "press" event, so the user is still pressing the same key, and didn't "just" pressed it.

If you want to know in each frame whether the user is currently pressing a key or not, you might want to use `Input.is_key_pressed()` in your `_process` function.

**Comment by akien-mga** [comment]
Indeed, if you need synchronicity between pressed keys and the `_process` function, you should do it as Henrique advises.

**Comment by L2750558108** [comment]
> If you want to know in each frame whether the user is currently pressing a key or not, you might want to use in your function.`Input.is_key_pressed()``_process`

But then I won't be able to use echo to achieve something like Input.IsKeyJustPressed. Although there is a solution to record the echo yourself, this method is flawed, and if the key has been pressed before the first frame of recording, it will be considered that the key was just pressed in the first frame. I think it's really necessary to add more complete input functions such as Input.IsKeyJustPressed. Most other major game engines (such as Cocos, Unity, Unreal, Gamemaker) have these input functions, which is enough to justify the need for these functions to be used frequently. In fact, I suggested the same in a previous discussion, but I was told that this feature is rarely used and that I should use an echo of the input event instead.

**Comment by AThousandShips** [comment]
How is adding that functionality going to fix the issue? The input system doesn't get updated until the OS sends the event, so nothing will be different?

It being present in other engines isn't an indication of it being needed, can you show that there is a large need for this? Give us examples of use cases for it that developers have, because as I and others have pointed out adding this functionality doesn't come for free, and you need to justify adding that cost to *everyone*, by showing that many people do need this functionality.

Given the relatively low popularity of the proposal it doesn't seem like may people are wanting or needing this.

**Comment by Zireael07** [comment]
> . If this is implemented using is_action_just_pressed, then the player will not be able to customize the pause button by changing the GlobalSetting.pauseKey.

Why can't you just use the action system? It allows changing the keys...

**Comment by L2750558108** [comment]
I think the action system is clunky and cumbersome, and when I want to detect the input of each key across the keyboard, I have to define a mapping for each key. There can be a simpler and more reasonable solution...

**Comment by L2750558108** [comment]
To add, functions such as isKeyJusyPressed/Released correspond to isActionJustPressed/Released, without which the API would feel incomplete

**Comment by AThousandShips** [comment]
I'm talking about the original proposal that has gotten barely any attention in over a year

Can you show and prove that a large part of the users of Godot need this functionality? Because if you can't this isn't a "more reasonable" solution. You constantly ignore that this isn't a feature that's just easy to add and that doesn't come with a cost, and you aren't giving any good arguments why everyone else would need this functionality, just that *you* would find it more convenient.

For your example, what is the reason this code has to be in _Process? And you seem to miss that Action can absolutely be modified and have the key changed, that is part of what makes *that* the best way to go.
