### ISSUE TITLE
Right click on an element of the interface does not work as expected (DisplayServer regression)

### ISSUE THREAD

**Issue by TheRealSlander** [godotengine/godot#71242]
### Godot version

4 beta 11

### System information

Linux 64 bits (Manjaro)

### Issue description

When right clicking on a node in the Scene Tree (or any other part or the interface with right click abilities) to perform an action from the popup menu, if the menu appears under the cursor, the menu entry below the cursor is "clicked" in the same event instead of reacting to a left click later.

This does not happen every times and depends highly on the position of the cursor in the popup menu but as I have my Scene Tree on the right side of the interface, the popup menu often appears under the mouse cursor. It's very annoying as it can select the "cut" command for example and I have to do Ctrl + Z to restore the deleted node and do the right click again. Sometimes it takes me 3 or 4 attempts to achieve what I was looking for!

When the popup menu is not under the cursor, it behaves like normal. I suspect the problem to be reproductible on any part of the interface (I spoted it in the Inspector as well), but there is some little chances to have the popup under the mouse cursor for the other parts of the interface (unless if we mess with it).

I saw this "bug" in the beta 10 as well, but as there is a lot of bugs reported already I though someone else would have spoted it and fixed it already.

If this is a double of another reported bug, I'm really sorry, I tried to find it in the reported issues, but there is really a lot of issues with the keywords "right click", "mouse buton" or other combinations.

### Steps to reproduce

1°) Ensure the Scene Tree is on the right side of the interface (or the Inspector, but there is less chances to make it appear).
2°) Add an instance of a node not a standard node (as there is more entries in the popup menu this way).
3°) Make the scene tree width small to allow the popup menu to pop under the mouse cursor when right clicking a node.
4°) Right click a node (sometimes it does not "select" a menu entry as the mouse cursor could be over a separator).

I can provide a video if required.

### Minimal reproduction project

None

**Comment by EricEzaM** [comment]
It appears you may have encountered a feature of PopupMenu that allows you to select an item with the release of the mouse button, when the press of that event caused the popup to open. 

This allows you to open a popup menu, slide your mouse while pressed to the item you want to select, and then release to select it. If you release faster than 150ms since the 'button down' event, this behaviour is skipped. 

I'm not sure how common this functionality is in other applications - I certainly don't use it. And I wonder if it causes confusion more than it is helpful, as it is not well documented (as far as I know), and is kind of hard to document in a good place. 
 https://github.com/godotengine/godot/blob/master/scene/gui/popup_menu.cpp#L395-L397

**Comment by TheRealSlander** [comment]
Wow! After more than 25 years in the computer industry, I never saw that! O.o
Is there a way to deactivate this unintutive behavior? I didn't find anything in the settings...

**Comment by Calinou** [comment]
> Wow! After more than 25 years in the computer industry, I never saw that! O.o Is there a way to deactivate this unintuitive behavior? I didn't find anything in the settings...

This feature is present on macOS and most Linux desktop environments. Windows has never followed suit though.

**Comment by TheRealSlander** [comment]
I'm not using Windows and I never have seen this "feature" under Linux either (27 years under Linux).

> we should refrain from adding a setting for everything

Surely allowing to disable this particular thing would be a must have for everyone not using this as it is counter intuitive.
This is really annoying when you are not familiar with.

**Comment by Calinou** [comment]
Can you reproduce this in 3.5.1?

**Comment by TheRealSlander** [comment]
> Can you reproduce this in 3.5.1? This may determine where it's actually a bug.
It does not act weirdly in Godot 3.5.1 (I wasn't able to reproduce).

> also try enabling Single Window Mode in the Editor Settings in 4.0.beta.
Once I checked the Single Window Mode in Godot 4.0 beta, I was unable to get the "bug" anymore...

**Comment by TheRealSlander** [comment]
Here is a video showing the difference between the 2 modes:

https://user-images.githubusercontent.com/102065761/212202388-a98910ce-24b2-4e6e-8258-78c92d9151f8.mp4

When I right click on the nodes in my Scene Tree, I never click on the left button, all I do is normally right clicking on the node, expecting the popup menu to show up, as it does when the Single Window Mode is set. Then I press Escape to close the popup menu when it is not already closed by an auto-select-weird-feature :D

**Comment by EricEzaM** [comment]
In your video, when the popup menu does not close instantly, but instead lingers for a bit, is that you holding down the right mouse button?

**Comment by TheRealSlander** [comment]
Nope, it is mostly because the mouse pointer is not over a clickable item (separation or between 2 buttons for example). Sometimes the popup menu is displayed outside of the mouse pointer too, so it does not "click" an item neither.

As I said, all I do in this video is making a simple right click without maintaining the mouse button. I try to make the popup menu to act normally (as you can see it working when the Single Window Mode is activated).

**Comment by TheRealSlander** [comment]
After more investigations, I'm able to state this fact (when I deactivate the Single Window Mode):
- The auto-click behaviour only happens when I'm using more than 1 monitor (if I set my config to only use 1 monitor or to use multiple ones in mirror mode, the problem disapears, but if I'm using 2 or more monitors, the problem arises).

I also tested it with an USB mouse and the pad of my laptop and both devices trigger the auto-click when conditions are met.

My system is an Asus ROG Strix (laptop) plugged to another monitor and external keyboard / mouse.
My OS is Manjaro Linux 64 bits and I use XFCE desktop with a compositing manager on top of it (Compiz Fusion). I didn't noticed this behaviour on another application / software I use, only in Godot 4.0 betas and in particular conditions (I only noticed this since beta 10, never encountered it in previous betas, but maybe the conditions where not met, like my Scene Tree was maybe smaller and the popup menu always appeared below the mouse pointer, I don't know).
Working on battery or plugged in the wall is the same thing

I'll test it without the compositing manager when I can and report back the result as well.

I hope this helps to understand what is happening.

**Comment by EricEzaM** [comment]
OK, sounds like it is not the popup menu feature that causes the issue then? Thanks for your detailed info.

**Comment by TheRealSlander** [comment]
I don't think so as when I use the Single Window Mode, all is fine...

**Comment by TheRealSlander** [comment]
Well, after more investigations and tests, **I managed to make it happen totally outside of Godot** (Godot wasn't even started)!

So we can close this "bug" as it is not related to Godot but more likely to my system. I'm really sorry for the false alarm here. I will simply keep the Single Window Mode active for now.

And as EricEzaM mentioned, it is indeed related to the right-click-popup feature as when I maintain the right mouse button pressed it never occurs... I discovered this feature on my system as well, thanks Calinou to have pointed it out for the Linux OS, I wasn't aware of this :D.

Again sorry to have wasted your time guys.

**Comment by EricEzaM** [comment]
No worries! Glad you figured it out

**Comment by tom-jk** [comment]
Though this issue was closed, I was coming to report the same thing so I hope you won't mind if I do it here :)

Linux Mint 20 Cinnamon (4.6.7), Godot 4.2 beta 1

[rightclickmenu71242.webm](https://github.com/godotengine/godot/assets/64640811/ba2ffc63-194e-42ef-b4f8-3b5cc6c68a15)


There is a small delay before the menu actually appears and becomes interactive, which eats up the 150ms grace period (mentioned above https://github.com/godotengine/godot/issues/71242#issuecomment-1379517804). In the video you can see how the menu drop shadow appears first, then the menu itself. I inserted a print into a custom build to show the delay time (diff) each click, and in a small test where I clicked then release the mouse as fast as I could, I measure diff to average about 200ms.

Solution suggestions (in order of decreasing favourability):
 - only start counting time from when the menu actually appears (ie. when it can start accepting input); or
 - ensure the menu pops up slightly away from the mouse so no item is immediately under it; or
 - increase the threshold time to something like 250ms to compensate.

Note: I also find this doesn't happen in single-window mode, probably(?) because it can show the menu and start processing input without delay.

**Comment by AThousandShips** [comment]
Did you follow the conversation and the resolution? If this is the same issue it isn't a Godot issue but a platform issue

**Comment by TheRealSlander** [comment]
@tom-jk Do you have an nVidia card and do you use multiple monitors by hasard?

It exists a bug in the nVidia drivers when using multiple monitors on Linux. They are working on it, but I think the issue you have (and I still have as well) is related to that. The delays you mention are caused by the Graphic Card struggling when heavy load is put on the GPU. This is why the problem only (mostly) occurs to me when using Godot, as it is heavier than my other apps on the GPU.

If you don't have an nVidia card, then I don't know what can be the cause.

The solution I found that is working for me is to use the "Single Window Mode" for Godot for now.

Hope this helps.

**Comment by tom-jk** [comment]
A menu item accidentally being selected immediately: I did get this to happen in other apps, such as the file explorer.
The menu appearing after a delay: of the apps I looked at, I only saw this in Godot.[^1]

The 150ms no-click period was added in #42173, and the pull description indicates this was in part to mitigate a linux/x11 issue. The duration was originally 100ms, but was later increased to 150ms in #55766. This replaced an earlier guard against accidental clicks (#17809 with a mouse-movement threshold).

All that's to say, is that it's sort-of a platform issue, but there's precedent for mitigations inside Godot.

TheRealSlander: I've got an nvidia rtx 2060 super, and only one monitor, at 1440x900. In terms of gpu workload, if I watch nvidia-smi's output in a terminal while bringing up the context menu in Godot, I see only a very small load on each click.

[^1]: I guess the delay before appearing is because the menu is itself a Godot window rather than a system menu, and it takes time to initialise Godot rendering stuff for a new window? (I also considered the delay might be for a menu popup animation so I turned off system animation effects to check, but no change.)
