### ISSUE TITLE
Project Manager - features proposal

### ISSUE THREAD

**Issue by fpv999** [godotengine/godot#7128]
**Operating system or device - Godot version:**
GODOT 2.1

**Issue description** (what happened, and what was expected):
Project Manager - Project List.
1) The list of projects is not sorted at all, it's hard to find projects there. What about adding sort by: NAME, DATE OF CREATION, DATE OF LAST LAUNCH?

2) Would be cool if project could be organizes into 2-level group hierarchy with custom group names. So user could create groups like:  "demo projects", "my current", "my old", "3rd party games"

3) Import button - would be cool to have a checkbox [X] scan subdirectories, so I could
   add all demo projects with single directory selection

**Comment by vnen** [comment]
> Import button - would be cool to have a checkbox [X] scan subdirectories, so I could
add all demo projects with single directory selection

There's a <kbd>Scan</kbd> button which does that.

**Comment by fpv999** [comment]
ok, true. I just found something other,
when I press SCAN and paste directory name like this:
d:\DevGodot\Godot-Demos-2.1-20160729 
then it starts to scan whole D:\ drive, because it expects path in this format:
d:/DevGodot\Godot-Demos-2.1-20160729 

Maybe for Windows version this could work with both / and \ ?

**Comment by vnen** [comment]
It *should* work with `\`, if it's not then you found a bug.

**Comment by fpv999** [comment]
It does not work with '\'.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9e7cee2 : some functionality are not implemented yet

**Comment by ArdaE** [comment]
I came in to create a feature request for project groups, did my search, and found it's been already requested here... So, I'm all thumbs up for request 2 above!

The way it is currently, everything is at the same level in one big pile in the Project Manager (my main projects, official demos, various experiments, projects shared by other developers, projects created to report bugs,...). It's quite a mess. I'm sure many must be dealing with the same mess. The ability to create custom groups within "Project Manager" would solve this issue nicely.

**Comment by ScepticDope** [comment]
Might this be a candidate one for the 3.2 milestone?

**Comment by KoBeWi** [comment]
Would #8167 solve this? With sorting/filtering by tag.

**Comment by aaronfranke** [comment]
1 is solved, you can now sort by name, path, or modified. See also: https://github.com/godotengine/godot/issues/29841

3 would be very nice, +1 from me.

**Comment by ArdaE** [comment]
@aaronfranke, I thought 3 was also done. Are you looking for something other than what the "Scan" button on the right does?

2 is the only remaining open issue here.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
