### ISSUE TITLE
GDScript 2.0: Autocompletion to fetch non-direct children doesn't work when using $NodePath literal

### ISSUE THREAD

**Issue by Lippanon** [godotengine/godot#71298]
### Godot version

v4.0.beta.custom_build [0abd60b95]

### System information

Windows 10, Vulkan

### Issue description

Autocomplete doesn't work when trying to access a scene node that isn't a direct child of the scene root script, using $NodePath (Shorthand for get_node("NodePath") as per docs).

Example:
![image](https://user-images.githubusercontent.com/115422160/212197922-10e73c9f-de10-475e-ac6e-4163fc5b8013.png)

It worked in Godot 3.5:
![3.5](https://user-images.githubusercontent.com/115422160/212197992-61b67a42-86c6-4650-bab4-c7dfa5a67975.PNG)

I should mention that it works if you start by typing the name of a direct child:
![image](https://user-images.githubusercontent.com/115422160/212198641-6d8e6fca-a2d2-47a7-b627-2df95268daf5.png)

But when you have many nodes in the scene and longer names it's a pain to access the last children like that.

### Steps to reproduce

See above or MRP.

### Minimal reproduction project

[autocomplete bug.zip](https://github.com/godotengine/godot/files/10406695/autocomplete.bug.zip)

**Comment by Chaosus** [comment]
Yeah, I did notice of it when made https://github.com/godotengine/godot/pull/65712.

**Comment by poohcom1** [comment]
I think this is due to the bug in the filtering logic for all auto-completion: 

https://github.com/godotengine/godot/blob/56fdef281ecc40e8ce10d4e17aa1357b150aca18/scene/gui/code_edit.cpp#L2963-L3087

Based on the comment explaining the code, the the filtering *should* include options where the user string is a substring of the suggestion, so `cha` should suggest `house/kitchen/chair`. But there is probably a bug in the logic of the optimized version.
