### ISSUE TITLE
Make better use of right side Inspector empty space / allow resizing values column

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#7133]
This is a UI/Usability improvement request.

Right now the Inspector on the right side of the screen which is used to edit scene properties, is making wasteful use of the space available.

For example see this:
![ex1](https://cloud.githubusercontent.com/assets/357737/20377165/c2c1d740-acbf-11e6-96e2-0ba6912c5a84.png)
There is a lot of space wasted between the word Path and the beginning of the actual path value and there is no way to resize the value column (that I know of). This is a big issue for values that are not numbers (ex. strings, enum style options)

The only way to increase the width of the value column is to increase the width of the whole Inspector which results in this:
![ex2](https://cloud.githubusercontent.com/assets/357737/20377211/20fb4990-acc0-11e6-95cf-29369794fe9b.png)
Here even though the width has been increased by a lot, the value column is still not wide enough to show the complete Path value. Instead of the value column being given priority / more space, the property names column have been given more, resulting in lots of wasted space.

In order to see the whole value the Inspector needs to be expanded even more:
![ex3](https://cloud.githubusercontent.com/assets/357737/20377255/7dd2a7ee-acc0-11e6-9847-26f3a571fda7.png)

In the first two images above, it is possible to view the full value by hovering the mouse over it, however it doesn't help when editing the value.

Suggestion is to either:
1. Allow resizing of value column
or
2. Limit width of property names column to the width of the longest property name
and/or
3. Change priority so that more space is given to value column

At least combination of 2 and 3 would go a long way and it would not require implementing additional UI.

**Comment by volzhs** [comment]
for now, the easiest solution is making property name with fixed width.

**Comment by RayKoopa** [comment]
I also suggested to make columns resizable. https://github.com/godotengine/godot/issues/6437
Maybe I have a look into implementing this. Column headers were visible in 1.x Godot already (though probably nonresizable, never used 1.x), but they magically disappeared.

**Comment by volzhs** [comment]
I agreed with re-sizable column.

**Comment by chanon** [comment]
I think this issue needs to be fixed soon. 

Especially now that the debugger can also show detailed object property names/values, the usability issue due to the space wasting is diminishing the usefulness of it.

**Comment by chanon** [comment]
Example of applying the above fix:

Before:
![image](https://user-images.githubusercontent.com/357737/30511060-4096a8d8-9afb-11e7-9efb-1e83fe5cedde.png)

After:
![image](https://user-images.githubusercontent.com/357737/30511052-22bf4e64-9afb-11e7-95b6-214f85a1c156.png)

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9e7cee2 : 
![image](https://user-images.githubusercontent.com/26753932/38462663-19bc417c-3b15-11e8-9db4-a0cab5e25484.png)

**Comment by akien-mga** [comment]
As others mentioned, two things should be implemented IMO (potentially in different PRs, as one is more important and simpler than the other):
- 1. Automatic calculation of split ratio based on the inspector width ratio (current width / min width). It can start at 0.5 like it is now, and then be reduced proportionally to the width ratio.
- 2. Allow dragging this separation to set an arbitrary base ratio (which can then still be subject to the scaling in (1)).

For (1), here are some pointers:
- `split_ratio` is set in the constructor to 0.5: https://github.com/godotengine/godot/blob/08bde5b2dea65ef3f80af5de4f4caf0e76982b64/editor/editor_inspector.cpp#L798
- It is then used here: https://github.com/godotengine/godot/blob/08bde5b2dea65ef3f80af5de4f4caf0e76982b64/editor/editor_inspector.cpp#L98
That's likely where automatic lerping of the ratio should be done, but I couldn't find out how to access the current dock size and it's minimum size
- `split_ratio` is also (ab)used in https://github.com/godotengine/godot/blob/c8f761ae2d71ffb70c4ee59fd0f951440804f055/editor/plugins/animation_blend_tree_editor_plugin.cpp and https://github.com/godotengine/godot/blob/c8f761ae2d71ffb70c4ee59fd0f951440804f055/editor/plugins/visual_shader_editor_plugin.cpp to hide the property name - I would suggest to make it a `set_hide_name(bool p_hide)` method instead

**Comment by MelvinWM** [comment]
As per Godot 3.1, there is a new inspector: https://godotengine.org/article/godot-3-1-released#inspector . It seems incredibly nice, many thanks to those who worked on it! I believe it solves some of the issues reg. this issue, and I believe that it may show an alternative solution, at least for resource paths and script paths.

Examples from the new inspector where increasing the width of the inspector is not necessary: 
![godot_inspector_2019-03-14_example1](https://user-images.githubusercontent.com/26661991/54412068-ae7cfc00-46f1-11e9-961f-92cc2d5cda95.png)
![godot_inspector_2019-03-14_example2](https://user-images.githubusercontent.com/26661991/54412070-af159280-46f1-11e9-99a8-399de7a0631c.png)
![godot_inspector_2019-03-14_example3](https://user-images.githubusercontent.com/26661991/54412071-af159280-46f1-11e9-83c4-a34396cc4acb.png)

Example of a resource path where this issue is still relevant:
![godot_inspector_2019-03-14_example4](https://user-images.githubusercontent.com/26661991/54412072-af159280-46f1-11e9-96d4-cc4391e75677.png)

Comparing the new features of the inspector with how resource and script paths are currently handled, might it make sense to use a similar solution for resources and script paths, with putting the path value field below the path property name instead of to the right of it? For instance:

![godot_inspector_2019-03-14_proposal1](https://user-images.githubusercontent.com/26661991/54413330-927b5980-46f5-11e9-85ef-d4b84248dfd4.png)

**Comment by toger5** [comment]
I think the best solution would be to just give the left size a maximum width based on the longest prop/ name.

**Comment by MelvinWM** [comment]
@toger5 then the left size might change in size when folding or unfolding a sub-resource, right?

**Comment by toger5** [comment]
@MelvinWM oh damn. Good point.
I still Don't like using two lines for one property. I think it's confusing, when a new line does not start a new property?

**Comment by MelvinWM** [comment]
@toger5 You have a good point, for a single-line value part, it is not nice to use 2 lines. It is also typically wasteful of space.

I wonder, might it make sense for resource and script paths to have the vertical bar removed, such that there is more horizontal space for the value part? For instance:

![godot_inspector_2019-03-17_proposal2](https://user-images.githubusercontent.com/26661991/54483318-5e1cb000-4851-11e9-9db3-18c5b9cda197.png)

**Comment by Calinou** [comment]
You can enable **Interface → Inspector → Horizontal Vector 2 Editing** in the Editor Settings to make Vector2 properties fit on one line (this is enabled for Vector3 by default).

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/2497, as feature proposals are now tracked on the Godot proposals repository.
