### ISSUE TITLE
NavigationAgent3D can only use the first NavigationLink3D it finds, ignores the others

### ISSUE THREAD

**Issue by venilark** [godotengine/godot#71438]
### Godot version

4.0 beta 12

### System information

Windows 10

### Issue description

I created a test NavigationAgent3D that reaches a NavigationLink3D and then it jumps towards the other end, it works and after that it heads to the next navlink but the signal is never emitted.
If you place the agent on the first platform then that link works, but not the next one.

### Steps to reproduce

.

### Minimal reproduction project

[navlinks_jump_test.zip](https://github.com/godotengine/godot/files/10418996/navlinks_jump_test.zip)

**Comment by fire** [comment]
@smix8 's work probably improves on this

**Comment by venilark** [comment]
> @smix8 's work probably improves on this

You mean his navlink project or a new PR?

**Comment by smix8** [comment]
This is primarily an issue with you NavigationAgent pathfinding properties not suited for the movement you are trying to make.

The `path_desired_distance` and `target_desired_distance` and `path_max_distance`  are at their default world units (1/1/3).

If you increase those defaults your agent jumps successfully like a bunny on all platforms.

So what basically happens here is that the agent either does not have a chance to get close enough to the current path index to advance the path or that the path is reset due to being outside the max distance to the current path point.

**Comment by venilark** [comment]
> This is primarily an issue with you NavigationAgent pathfinding properties not suited for the movement you are trying to make.
> 
> The `path_desired_distance` and `target_desired_distance` and `path_max_distance` are at their default world units (1/1/3).
> 
> If you increase those defaults your agent jumps successfully like a bunny on all platforms.
> 
> So what basically happens here is that the agent either does not have a chance to get close enough to the current path index to advance the path or that the path is reset due to being outside the max distance to the current path point.

I understood the problem. I forgot to set velocity.x and z to 0 once it hits the ground :disappointed:
No need to change the default values.

**Comment by YuriSizov** [comment]
Resolved then?
