### ISSUE TITLE
Asset Library should be able to filter plugins by compatibility with engine version 

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#7147]
**Operating system or device - Godot version:**
Godot 2.1.1-Stable

**Issue description** 
It is possible to download templates/demos/plugins that won't work for your Godot version, there are no warning or filters that hide non compatible projects. 

**Steps to reproduce:**
 - Download and install Cute 3D Multiplayer Third Person Shooter from the Project Manager's template tab.
 - You won't get any warning saying that it does not works on your Godot version.
 - Try to edit and run the project.

ps: I don't like the idea of compulsive version filter but at least a warning should be there.

**Comment by vnen** [comment]
> [...] compulsive version filter

I think you meant "compulsory". But yeah, it should let you install even in incompatible version.

**Comment by eon-s** [comment]
@vnen yes, compulsory, picked a word from the wrong dictionary in my poor brain :sweat_smile:

**Comment by vnen** [comment]
Repeating my comment here for visibility:

> It would be great if it were possible to upload different versions of the plugin for different versions of Godot.

**Comment by kubecz3k** [comment]
also @neikeq comment from #96880:
> Maybe related. Now that we also have more scripting languages, it would be great to also filter plugins automatically by available languages.

**Comment by kubecz3k** [comment]
I think in `plugin.cfg` we should have obligatory value like `min_engine_version=2.1.1` and **optional** value like `max_engine_version=2.1.x` I think ability to declare 'atomic' versions is necessary since while api will not be broken inside main version (2.x) it still is possible that some features will be added as a part of minor update (2.1.2).
Also @neikeq noted that we should have ability to declare what languages are needed in order for plugin to work. Not sure, but maybe we should go even further so we could declare in general 'what components are needed in order for this plugin to work'. What I mean is for example some custom module (like I believe there is some VR module in the works for example).

**Comment by eon-s** [comment]
Languages may apply only for C# version of Godot, since native can be shipped in binary form, right?

Some GDNative plugins may be restricted by platform too.

**Comment by reduz** [comment]
we also talked about allowing plugins to be anywhere, not just in addons/
right?

**Comment by kubecz3k** [comment]
@reduz actually I don't think that's very good idea. I think there would be many plugins that are not respecting addons folder, however maybe there is some user-case that I didn't think of, for which there is more sense to have plugin outside of addons?

**Comment by kubecz3k** [comment]
Unless you want to allow game developer to decide where addons should be, for me that would be actually quite cool

**Comment by eon-s** [comment]
Plugins outside "addons" sounds messy and I don't see the benefit, more if you want many versions of the same addon for _reasons_

**Comment by reduz** [comment]
ok, alright, let's not do it then

**Comment by eon-s** [comment]
This is already working on the web site, just need Godot 2.1 and 3.0 editor support.

**Comment by bojidar-bg** [comment]
Actually, Godot 2.1 is supporting it already, just Godot 3.0 should send the version number when requesting assets.

**Comment by Chaosus** [comment]
@bojidar-bg is this solved for now ?

**Comment by akien-mga** [comment]
Yep, fixed by #12778.
