### ISSUE TITLE
Setting DEPTH_TEXTURE to ALPHA glitches depth

### ISSUE THREAD

**Issue by yahi752952** [godotengine/godot#71487]
### Godot version

4.0-beta12

### System information

Windows 11, Vulkan, RX570 (31.0.12029.10015)

### Issue description

Been trying to blend objects with terrain,
 for example in xb2:
![Screenshot 2023-01-16 004954](https://user-images.githubusercontent.com/84506353/212572507-5a77090f-423f-4613-9d3a-9faa233c4ba3.jpg)
I think theyre using what unreal calls depthfade:
https://stackoverflow.com/questions/43902715/how-to-create-depth-fade-effect-in-opengl
Here's what ive got thus far:
![Screenshot 2023-01-16 004954](https://user-images.githubusercontent.com/84506353/212573801-c44c4435-c7c8-4c71-8011-375740bf89f4.jpg)
but depth is glitchy:
 

https://user-images.githubusercontent.com/84506353/212573863-5f606d0a-9529-46d6-8824-bf2221e72f44.mp4

shader:
```
shader_type spatial;
render_mode depth_prepass_alpha;

varying vec3 VertexNormalWS;
varying vec3 AbsoluteWorldPosition;

uniform sampler2D Albedo;
uniform float depthFadeDiv;
void vertex()
{
	
	VertexNormalWS = normalize(MODEL_MATRIX * vec4(NORMAL, 0.0)).xyz;
	AbsoluteWorldPosition = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
}
void fragment() 
{
	vec3 CameraPosition = INV_VIEW_MATRIX[3].xyz;
	vec3 CameraDirection = normalize( INV_VIEW_MATRIX[2].xyz*-1.0);
	//Scene Depth
	float depth1 = texture(DEPTH_TEXTURE, SCREEN_UV).x;
	vec3 ndc = vec3(SCREEN_UV, depth1) * 2.0 - 1.0;
	vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
	view.xyz /= view.w;
	float linear_depth = -view.z;
	linear_depth *= 1.99;
	//Depth Fade
	float PixelDepth = dot(CameraDirection,(AbsoluteWorldPosition - CameraPosition));
	float depthFade = (linear_depth-PixelDepth)/depthFadeDiv;
	depthFade = clamp(depthFade/depthFadeDiv,1.0,0.0);
	
	

	ALBEDO = texture(Albedo,UV).xyz;
	ALPHA = depthFade;
}
```

### Steps to reproduce

Set DEPTH_TEXTURE to ALPHA

### Minimal reproduction project

[Depthfade.zip](https://github.com/godotengine/godot/files/10421626/Depthfade.zip)

**Comment by clayjohn** [comment]
You aren't calculating depth correctly. Take a looks at the advanced post processing docs which has sample code that should help you https://docs.godotengine.org/en/latest/tutorials/shaders/advanced_postprocessing.html#depth-texture

Also take a look at how proximity fade is implemented in the StandardMaterial3D. 	https://github.com/godotengine/godot/blob/91fedb60de6011434938499a9d4a7d4fd1cd4f06/scene/resources/material.cpp#L1248-L1253 
(Alternatively you can enable it in a material and then select (convert to Shader material))

**Comment by yahi752952** [comment]
i just updated my shader according to doc , but depth sorting is still glitched out :(

![update](https://user-images.githubusercontent.com/84506353/212584484-7148509e-ab03-4894-90c5-d4cb8d1a8c8e.jpg)

**Comment by yahi752952** [comment]
Found a work around:

![update2](https://user-images.githubusercontent.com/84506353/212973586-df1b6406-a2a0-4c4b-bd96-83b00ef7acab.jpg)


dont use ALPHA, instead use depthfade as MASK to linear interpolate SCREEN_TEXTURE.

Final Shader:
```
shader_type spatial;
render_mode depth_prepass_alpha;

varying vec3 VertexNormalWS;
varying vec3 AbsoluteWorldPosition;

uniform sampler2D Albedo;
uniform float depthFadeDiv;
void vertex()
{
	AbsoluteWorldPosition = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
}
void fragment() 
{
	vec3 CameraPosition = INV_VIEW_MATRIX[3].xyz;
	vec3 CameraDirection = normalize( INV_VIEW_MATRIX[2].xyz*-1.0);
	//Scene Depth
	float depth = texture(DEPTH_TEXTURE, SCREEN_UV).x;
	vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth);
	vec4 view = INV_PROJECTION_MATRIX * vec4(ndc, 1.0);
	view.xyz /= view.w;
	float linear_depth = -view.z;
	//Depth Fade
	float PixelDepth = dot(CameraDirection,(AbsoluteWorldPosition - CameraPosition));
	float depthFade = linear_depth-PixelDepth;
	depthFade = clamp(depthFade/depthFadeDiv,0.0,1.0);
	
	vec3 ScreenTex = texture(SCREEN_TEXTURE,SCREEN_UV).xyz*1.0; 
	ALBEDO = mix(vec3(0.0,0.0,0.0),texture(Albedo,UV).xyz,depthFade);
	EMISSION = mix(ScreenTex,vec3(0.0,0.0,0.0),depthFade);
}
```

**Comment by yahi752952** [comment]
@clayjohn im pretty sure this is a BUG, as in 3.5.1 sorting glitches by just accessing depth_texture and not even using it,
so the workaround doesnt work.

**Comment by clayjohn** [comment]
Sorry, my previous answer was only a partial answer and I didn't realize you were using the mobile renderer. I will provide more detail here. But to be clear, this space is reserved for bug reports only. You should be asking for help with this on one of the [community channels](https://docs.godotengine.org/en/latest/community/channels.html)

Godot forward plus renderer renders the scene in 3 passes: the depth pass, the opaque pass, and the alpha pass. Objects that write to ALPHA or read from a screen texture are rendered in the alpha pass, other objects are rendered in the depth pass and the opaque pass. 

The mobile renderer (what you are using in your MRP) only has the opaque pass and the alpha pass. The depth texture is created during the opaque pass, but it can be written to in the alpha pass as well (with the ``depth_draw_always`` render mode)

Objects in the opaque pass are ordered in such a way to minimize state transitions between objects (i.e. grouped by shader etc.). Objects in the alpha pass are ordered from furthest from the camera to nearest to the camera so that they are rendered back to front. The opaque pass doesn't need to manually rely on the order of objects as it uses the depth written to the depth texture to cull pixels that are not visible. When you have large objects that overlap in multiple places it is impossible to sort the objects perfectly. However, if the object in the transparent pass is mostly opaque anyway, you can write to the depth texture to take advantage of depth texture based culling. 

For most shaders this is as simple as adding ``depth_prepass_alpha`` to the shader so that the opaque parts of the transparent object are written to the depth texture. However, there are two issues with your shader:
1. You are using the mobile renderer which doesn't have a prepass and
2. the transparency of your object is modified by the depth_texture (since there is no depth texture in the depth prepass the shader can't run in the depth prepass).

Accordingly, your shader falls back on regular transparent sorting. To fix this, you can force it to write to depth in the transparent pass by adding ``render_mode depth_draw_always``
