### ISSUE TITLE
Node added right after adding another node has wrong parent

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#71481]
### Godot version

4.0 91fedb6

### System information

Windows 10 x64

### Issue description

Add Child Node adds node as a child of currently selected node. However if you add 2 nodes in a row, the second node will ignore selected node and get added as its sibling:

![godot_nueDdjsOup](https://user-images.githubusercontent.com/2223172/212568178-ab6e5812-aa66-4a63-9278-2c931fd84f74.gif)

### Steps to reproduce

1. Add Node
2. Add Node

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
There's two options for what should be the expected behavior:
1. Don't select the added child node, and keep the behavior of adding new nodes as children of the node the user last selected
2. Fix the behavior so it does add the next child to the newly added and selected child.

IMO 1. matches the way I create scenes more closely (adding multiple siblings under a selected node), but auto selecting the added node to edit it in the inspector (thus 2.) may also be preferred.

**Comment by KoBeWi** [comment]
Yeah I used it a lot for containers and it made me open this issue.
I think adding multiple siblings in a row is not a common action. Normally you add 1 node and duplicate it if anything.

**Comment by KoBeWi** [comment]
No longer happens in beta 16.
