### ISSUE TITLE
regression: running godot -e path_to_scene fails to open the scene

### ISSUE THREAD

**Issue by punto-** [godotengine/godot#7161]
**Operating system or device - Godot version:**
linux, master

**Issue description** (what happened, and what was expected):
I think caused by #6813. The path in the parameter is made absolute in main.cpp (around line 1326), the editor later calls Globals::localize_path, which fails to localize the path. I don't know what bug that fixes, but localize path should make the path local to the resource path

**Steps to reproduce:**
run
godot -e scene.scn
from the root of a project

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
CC @Faless.

**Comment by punto-** [comment]
So in looking at the issues that this fixed, those weren't issues :) You're
not supposed to use load("/script.gd") and expect it to load from your
resource path, that's an absolute path in the filesystem. Use res://, or
just "script.gd", that should be portable. I don't know if there's a way to
detect this, since scripts need to open absolute paths to do things like
batch processing of resources, but localize_path should work correctly.

**Comment by Faless** [comment]
> So in looking at the issues that this fixed, those weren't issues :)

Yes, it all started with a misunderstanding, because `load("/file.gd")` was behaving like `load("res://file.gd")` while `load("/dir/file.gd")` was properly loading from the file system (on supported platforms of course).

That PR reverts a previous modification I did that completely disabled using absolute paths, and fixed the misbehavior for `load("/file.res")` trying to load from resource.
This is related to #6979 .
