### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by rogerwes** [godotengine/godot#71777]
Probably not the correct place to open this discussion, but I've noticed in the snapshot articles for Godot 4 the articles talk about potentially supporting .NET 7. While keeping up with the latest is a good idea, I wonder if it would make more sense to focus on the LTS releases of .NET, and with .NET 8 coming out as a LTS release this year, it might make sense to skip 7 and go from 6 to 8 later this year.

Microsoft's release schedule / support policy: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

Happy to discuss more on this, thanks!

**Comment by Zireael07** [comment]
A PR was opened a couple days ago: https://github.com/godotengine/godot/pull/71241

**Comment by raulsntos** [comment]
While there's a difference in the amount of time an LTS release is officially supported compared to a non-LTS release, other than that all .NET releases have the same level of support and there's no particular change in development that makes an LTS release "safer" or more "stable" than a non-LTS one.

The reason why we may want to update Godot to .NET 7 is to take advantage of some of the new features that would allow us to improve the GodotSharp implementation.

However, we also have to keep in mind that if the GodotSharp library targets .NET 7, that also means that users' projects need to target .NET 7, that's probably fine for most but some users may be reluctant to update to a non-LTS release (maybe due to company policy) and this would make things difficult for them.

There are probably a few ways in which this could be solved, such as multi-targeting, but first we'd have to decide whether we want to update to .NET 7 or stay in .NET 6, it seems .NET 7 also includes some breaking changes that may complicate the update so it may be safer to stay in .NET 6 considering how close we are to the 4.0 release.

**Comment by rogerwes** [comment]
Great discussions and thanks for the PR link, somehow missed my search queries.
