### ISSUE TITLE
Reparenting `SoftBody3D` crashes Godot if the `SoftBody3D` has pinned points

### ISSUE THREAD

**Issue by James103** [godotengine/godot#71785]
### Godot version

Since before v4.0.alpha1.official 31a7ddbf8 (first encountered in 4.0.beta14.official 28a24639c)

### System information

Windows 10, Forward+, NVIDIA GeForce GTX 1660/PCIe/SSE2

### Issue description

Reparenting a `SoftBody3D` node may crash the editor, especially if the `SoftBody3D` has at least one pinned point attached to a `Node3D` higher up in the tree.

### Steps to reproduce

1. Unzip, import, and edit the attached project.
2. Open `main.tscn` for editing.
3. Reparent the `SoftBody3D` from the `Node3D` named "main" to the `Node3D` named "body_parent".
4. The editor crashes whilst reparenting.

### Minimal reproduction project

[Crash reparenting SoftBody3D.zip](https://github.com/godotengine/godot/files/10471423/Crash.reparenting.SoftBody3D.zip)

**Comment by rburing** [comment]
The problem seems to be that reparenting the `SoftBody3D` node first updates all the node paths to what they should be after the reparenting, which in this case replaces the attachment path `..` by `../..`, but the property setter

https://github.com/godotengine/godot/blob/2ec0da1a75a066fe88986fc6ceda22fbabf7eedd/scene/3d/soft_body_3d.cpp#L127

tries to do an *immediate* update:

https://github.com/godotengine/godot/blob/2ec0da1a75a066fe88986fc6ceda22fbabf7eedd/scene/3d/soft_body_3d.cpp#L134-L139

which eventually fails here:

https://github.com/godotengine/godot/blob/2ec0da1a75a066fe88986fc6ceda22fbabf7eedd/scene/3d/soft_body_3d.cpp#L756-L759

because while `has_node(p_spatial_attachment_path)` is `true` and `get_node(p_spatial_attachment_path)` is not `null`, `Object::cast_to<Node3D>(get_node(p_spatial_attachment_path))` is in fact `null` because `../..` does not refer to a `Node3D` (before the reparenting is done).

We can add the extra `null` check there, but with that alone the update would just fail, so probably `SoftBody3D::_set` should do a *deferred* call to `_set_property_pinned_points_attachment` (or something like that) to fix this issue.
