### ISSUE TITLE
Vulkan: Fog volume illumination changes with movement direction of light

### ISSUE THREAD

**Issue by andyprice** [godotengine/godot#71820]
### Godot version

v4.0.beta.custom_build [2ec0da1a7]

### System information

Linux, Iris Xe Graphics, Forward+

### Issue description

With a light moving as a child of the camera, moving through a fog volume gives inconsistent lighting results depending on the direction of movement: while moving forward, the brightness of the fog decreases and while moving backwards it increases. My expectation is for movement direction to not have any effect at all on fog illumination.

### Steps to reproduce

Add an OmniLight to the scene as a child of the camera and move it back and forth through the fog volume.

### Minimal reproduction project

[fogtest.zip](https://github.com/godotengine/godot/files/10472628/fogtest.zip)

An animation is included in the project to move the camera back and forth but it also can be demonstrated in-editor if you move the camera manually while viewing the camera preview.

**Comment by Calinou** [comment]
I can confirm this with the MRP on 4.0.beta 621e32971 (Linux, GeForce RTX 4090 with NVIDIA 525.60.11).

However, this is not a bug, but an artifact of temporal reprojection (which is done to improve quality). If you disable volumetric fog temporal reprojection in the Environment properties, the issue goes away (at the cost of lower volumetric fog rendering quality).

**Comment by clayjohn** [comment]
> However, this is not a bug, but an artifact of temporal reprojection (which is done to improve quality). If you disable volumetric fog temporal reprojection in the Environment properties, the issue goes away (at the cost of lower volumetric fog rendering quality).

Its actually even simpler than that, the camera goes from one end of a fog volume to the other. When at one end, the total depth of the fog is about 4 metres, at the other end it is only a few centimeters of fog. Fog scatters light backward, so when there is more fog, there is more light reaching the camera. If you change the MRP from using a local FogVolume to using global fog, the effect disappears even with temporal accumulation on. 

There is no bug here, as you approach the end of a fog volume, there will be less fog accumulating and since the background is black, the image will get darker overall. If you want the brightness of the light to stay the same, then the amount of fog in front of the camera needs to stay the same.
