### ISSUE TITLE
4.0 B14 - InputMap.action_add_event overwrites any existing events rather than adding them.

### ISSUE THREAD

**Issue by Bargeral** [godotengine/godot#71888]
### Godot version

v4.0.beta14.official [28a24639c]

### System information

Windows 10

### Issue description

**InputMap.action_add_event** overwrites any existing Event rather than adding events. I expect this script would add a second InputEventKey to the action, but instead it overwrites the first one.  Adding multiple events manually to the action via settings seems to work fine. 

Example output from the attached script.

```

`--- Debugging process started ---
Godot Engine v4.0.beta14.official.28a24639c - https://godotengine.org
OpenGL Renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
 
First run
Action_from_Settings has events: [InputEventKey: keycode=73 (I), mods=none, physical=true, pressed=false, echo=false, InputEventKey: keycode=67 (C), mods=none, physical=true, pressed=false, echo=false, InputEventKey: keycode=85 (U), mods=none, physical=true, pressed=false, echo=false]
Action_From_Script has events: [InputEventKey: keycode=88 (X), mods=none, physical=false, pressed=false, echo=false]

Second run
Action_from_Settings has events: [InputEventKey: keycode=73 (I), mods=none, physical=true, pressed=false, echo=false, InputEventKey: keycode=67 (C), mods=none, physical=true, pressed=false, echo=false, InputEventKey: keycode=85 (U), mods=none, physical=true, pressed=false, echo=false]
Action_From_Script has events: [InputEventKey: keycode=89 (Y), mods=none, physical=false, pressed=false, echo=false]
--- Debugging process stopped ---
`
```

### Steps to reproduce

```
extends Node2D

# Called when the node enters the scene tree for the first time.
func _ready():
	_simple_test()
	pass # Replace with function body.

func _simple_test():
	var _temp_key = InputEventKey.new()
	InputMap.add_action("Action_From_Script")

	_temp_key.set_keycode(KEY_X)
	InputMap.action_add_event("Action_From_Script", _temp_key)
	print("First run")
	_print()

	_temp_key.set_keycode(KEY_Y)
	InputMap.action_add_event("Action_From_Script", _temp_key)
	print("\nSecond run")
	_print()

func _print():
	var current_map = InputMap.get_actions()
	for i in current_map:
		if ! "ui_" in i:
			print(i, " has events: ", InputMap.action_get_events(i))
```

### Minimal reproduction project

[bugtest.zip](https://github.com/godotengine/godot/files/10475780/bugtest.zip)

**Comment by EricEzaM** [comment]
Not a bug.

Add `_temp_key = _temp_key.duplicate()` or `_temp_key = InputEventKey.new()` before `_temp_key.set_keycode(KEY_Y)`

`Action_From_Script has events: [InputEventKey: keycode=88 (X), mods=none, physical=false, pressed=false, echo=false, InputEventKey: keycode=89 (Y), mods=none, physical=false, pressed=false, echo=false]`

The issue is that adding the action to the list just adds a reference to `_temp_key`, essentially. `_temp_key` and the value of (psuedocode)`InputMap.actions["Action_From_Script"][0]` point to the same bit of memory. So changing temp key also changes that stored value.

To fix this, you just need whatever you pass into `action_add_event` to _not_ be the same object. So, duplicate it, or instantiate a new `InputEvent`.

If this answer resolves this problem, could you please close the issue.

**Comment by Bargeral** [comment]
Yes that worked fine. Thank you.
