### ISSUE TITLE
`StyleBoxTexture` be always expanded to a texture size

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#71913]
### Godot version

9937915ad77059b63582ffd4e324afb26f467b76

### System information

Windows 11

### Issue description

Even if I decrease a `Sub-region` property to 0, 0 it is expanded to a full size at runtime:

![image](https://user-images.githubusercontent.com/3036176/214050016-0069af9c-3d64-429d-aea4-119e3633a6e3.png)

It should take the parent container size into account, but instead it expanded independently, which broke the UI used that style box.
It's broken after https://github.com/godotengine/godot/pull/71686 cc @YuriSizov 

### Steps to reproduce

Try to use StyleBoxTexture

### Minimal reproduction project

[TestSBTexture.zip](https://github.com/godotengine/godot/files/10480088/TestSBTexture.zip)

**Comment by eviltrout** [comment]
Thanks for reproducing this. My UI is quite broken in Beta 14/15 and this seems to be the cause.

**Comment by YuriSizov** [comment]
> Thanks for reproducing this. My UI is quite broken in Beta 14/15 and this seems to be the cause.

The cause for this is not in Beta 14, only Beta 15 has the relevant changes.

**Comment by lostminds** [comment]
I've encountered an issue in beta 15 with ProgressBar controls using StyleBoxTexture for the bar fill that no longer size the bar correctly for low values but become correct as the bar is close to full. I'm guessing this bug is the cause, preventing the bars from being scaled smaller than the original texture size for the stylebox texture?

**Comment by KoBeWi** [comment]
The PR wrongly assumed that `get_center_size()` had anything to do with stylebox's minimum size and the changes forced it as minimum size everywhere (including Controls that never cared about texture's size, like Button or PanelContainer, which explains all issues...).

**Comment by YuriSizov** [comment]
I mean, the behavior should be consistent, and it wasn't. Why shouldn't all controls respect the region of the texture, if that's how the stylebox was set up? The problem was that controls that tried to respect the center bit ended up ignoring the min size. So it wasn't working correctly for them, not really.

**Comment by KoBeWi** [comment]
We could add `ignore_texture_size` property to StyleBoxTexture, to allow shrinking past the texture's size.

**Comment by YuriSizov** [comment]
Honestly, I can't find the reason for the existing logic. It tracks back to the pre-open-source days, and might be just a mistake or a carry-over from some old Juan's system. I think your initial hunch to remove the logic was correct, @Chaosus. Let me see if this breaks anything, and I'll make a PR that completely removes the override. If some stylebox doesn't look correctly after that change, it simply needs to adjust its margins to the expected value.

What could make sense to account for in the min size, is borders of the 9-patch mode. But that would be a completely new behavior, unrelated to any previously established or current logic.

**Comment by YuriSizov** [comment]
Removing the min size override logic fixes your issue though.

**Comment by Chaosus** [comment]
My custom_min_size of all controls setted to zero or what you mean?

**Comment by Chaosus** [comment]
@YuriSizov So I've setted the sub-region property to zero in the inspector, and after the editor restarted - it's reverted to texture size - do you think it's OK?

**Comment by YuriSizov** [comment]
The region is used to define which part of the texture to use, same thing as using an AtlasTexture. If you set it to zero then it doesn't make any sense, because that means you don't want any part of the texture to appear on the screen. That's what KoBeWi wanted to make implicitly okay with his PR. Either way, that's unrelated to the issue here. I've made my PR now.
