### ISSUE TITLE
Grandchild class of RefCounted is mistaken for Resource's child class.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#71994]
### Godot version

4.0.beta14

### System information

Windows 10, Forward+

### Issue description

I simplified the situation in the title. 
Specifically, in any class which is sub-sub-class of RefCounted, when you try to define a function which exists in Resource, parser will throw this error: The function signature doesn't match the parent. Parent signature is "duplicate(bool = default) -> Resource".

### Steps to reproduce

```
class A:
	extends RefCounted

class B:
	extends A

	static func duplicate():
		pass

```

* res://addons/new_script.gd:5 - Parse Error: The function signature doesn't match the parent. Parent signature is "duplicate(bool = default) -> Resource".

### Minimal reproduction project

N/A

**Comment by adamscott** [comment]
Please join a MRP when there's scripts involved. Even if it seems simple, it simplifies greatly the developer's work.

**Comment by adamscott** [comment]
I confirm this issue. Got it on master (e93266b).

### Minimal reproduction project
[71994.zip](https://github.com/godotengine/godot/files/10501469/71994.zip)

**Comment by vnen** [comment]
To clarify, even though an argument can be made that this is correct behavior (static methods are accessible with the class alone and since a class is also a GDScript object, you can also access methods defined in GDScript and its super classes, so makes sense to check signature), the error shown here itself is not consistent.

This does not give an error:
```gdscript
class A:
	extends RefCounted
	static func duplicate():
		pass
```

This gives an error even without `static`:
```gdscript
class A:
	extends RefCounted
class B:
	extends A
	func duplicate():
		pass
```

So there's definitely something odd with the super class check.

**Comment by akien-mga** [comment]
Reopening as #72144 was reverted.
