### ISSUE TITLE
AssetLib recognise already installed

### ISSUE THREAD

**Issue by testman42** [godotengine/godot#7202]
**Operating system or device - Godot version:**
Fedora 25 x86_64 - Godot Engine v2.1.1.stable.official

**Issue description** (what happened, and what was expected):
In AssetLib tab, there is no indication of any kind that an entry is already installed.
You can still download it (again), and only when trying to install it, you see that all filenames in proposed installation are red, implying already existing files.

I think that there should be an indication that either:
- latest version of addon is already installed or
- addon is installed but there is newer version avaliable

If user already has latest version of addon, do still allow him to re-download the latest version again, but in that case change the button text from "Install" to "Reinstall"

**Comment by vnen** [comment]
I believe this could be (partially) solved if Godot stored an "asset database" file with the project.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 9e7cee2

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
