### ISSUE TITLE
In the _ready() function of the parent node, calling the location information of the child node under the ui container gets the wrong result

### ISSUE THREAD

**Issue by chamer-vati** [godotengine/godot#72024]
### Godot version

4.0Beta14

### System information

Windows10，Vulkan

### Issue description

In the _ready() function of the parent node, calling the location of the sub node in the ui container gets an error result. For example, child nodes (such as labels) after Custom Constans is set in MarginContainer. In this case, getting the global_position of the Label in their parent _ready() function only gives the Global Position of the MarginContainer

### Steps to reproduce

Enter the Test project file and run it directly.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/10498269/Test.zip)

**Comment by Zireael07** [comment]
Some functions do not work in _ready, need to be used after a frame (yield)

**Comment by aXu-AP** [comment]
Since `_ready()` is called from bottom up (children first) usually you can rely on children being ready. However, since ui needs the whole thing to be ready since parents affect childrens' positioning, you need to wait until next frame, as Zireael noted. At least that's what I think is happening.

**Comment by chamer-vati** [comment]
> 由于是自下而上（孩子优先）调用的，通常您可以依靠孩子做好准备。但是，由于 ui 需要准备好整个事情，因为父母会影响孩子的定位，因此您需要等到下一帧，正如 Zireael 指出的那样。至少我认为这是正在发生的事情。`_ready()`

Thanks, since this issue did not occur in the _Godot3.5.1stable_ and _early Beta versions_,  this confused me a bit.

**Comment by YuriSizov** [comment]
It seems to me that we are missing a signal or a notification for when the sorting of children is done. So there is no obvious hook to reliably track when container updates child positions. I guess you could use child's own `item_rect_changed` signal.

**Comment by Reneator** [comment]
I encountered this one as well, and for my UI heavy game this is not just QoL but that requires a workaround compared to the 3.X logic, of having the correct global_position etc. available on ready.

I have built the logic in the scripts with the assumption/knowledge that onready the positions in the UI were already the predefined ones.

Here a reproduction project:

[ready position testing.zip](https://github.com/godotengine/godot/files/13772863/ready.position.testing.zip)


The Label is put at the bottom of the screen by the VboxContainer with Alignment "End".
In the editor it shows the correct position of the Label, on _ready it prints an incorrect one (in this case (0,0)) and on _process it has the correct position.

**Comment by Reneator** [comment]
I would like to advocate for this to be changed from an enhancement to a bug, as this is breaking a lot of code in my project and this behaviour in godot 4 is not intuitive imo.

**Comment by markdibarry** [comment]
@YuriSizov I don't believe there is a hook/signal/notification that would be able to accommodate this, but feel free to correct me. I imagine this is highly desired for most users for the common use case of not wanting to show the UI until everything is in its right place, same as you wouldn't want the curtain to come up on a theater cast as they're putting their costumes on and running across the stage. Unfortunately, though, I'm not sure there can be a built in signal or notification that could know when a container's children are done sorting, since it can be triggered to resort multiple times based on not only their children but their parents and siblings. I think maybe if anything it would be helpful to push for documentation to say for scripting your outermost container, wait a frame and have it pass down that it's safe to calculate or show stuff, but again, if they're gonna use those calculations to adjust the child even more, it'd cause another resort, meaning you'd need to wait another frame, etc. It's just kinda hard to have a notification based on what the user considers "done".

**Comment by tokengamedev** [comment]
This is not a limitation or designed feature in Godot. It is a serious bug, which was not reproducible in 3.x. Even if you want to document as a limitation, you cannot, as you do not know when it produces correct result and when not.

It is safe to assume that the core functionality of Godot is broken. This bug redefines the usability of _ready() function

**Comment by AThousandShips** [comment]
What's your suggestion for "solving" this? It's a limitation, not a bug, it's simply not possible to know this when `_ready` as other nodes are not ready, and might update some of their sizing on `_ready`, the solution is instead to provide some update point

Relying on `_ready` itself doesn't seem good to me to begin with, it's not guaranteed to be useable anyway because of other factors IMO, the shaping is done deferred for various reasons, including performance, but also because `_ready` just means *this* node is ready, not its later siblings, or it's parent, or siblings of its parent, etc.

**Comment by tokengamedev** [comment]
> It's a limitation, not a bug, it's simply not possible to know this when _ready as other nodes are not ready, and might update some of their sizing on _ready

This bug is not related to resizing done inside the _ready code. It is a different problem altogether. It is just loading the scene from the scene file. If resizing done inside the _ready or anywhere else, it is users' problem and not engine's.

> Relying on _ready itself doesn't seem good to me to begin with, it's not guaranteed to be useable anyway because of other factors IMO, the shaping is done deferred for various reasons, including performance, but also because _ready just means this node is ready, not its later siblings, or it's parent, or siblings of its parent, etc.
The data in _ready isn't guaranteed to be valid and can change later, so the best approach is to not rely on it but listen to changes as suggested here

so how and where do we know the size and position of child controls at the time of launch of the scene.

> But I'm also unsure why you need this information? Containers are intended to handle sizing and knowing sizes isn't necessarily something usually needed, so this feels like an unusual problem

You are right, containers should handle the sizing, no body argues that. It is not an unusual problem. 
It is for animations, and the most important of them all why we need is `pivot_offset` It does not take from 0- 1, rather takes the local position inside the control

Moreover, thanks to you I got the workaround to the problem i.e., use objects inside `Control` for animation rather than objects inside containers. It will add one more layer, but hope it works. In 3.x it was a big mess

**Comment by AThousandShips** [comment]
This limitation is due to how the sorting is deferred, but it *is* related to sizing changes and avoiding spurious resorting when updating things, but in the end the node isn't ready until the full tree is and it'd be pointless to sort the nodes constantly

> so how and where do we know the size and position of child controls at the time of launch of the scene.

You don't, it'd be unreliable information at best anyway

The solution here is to have a signal and respond to it

`_ready` doesn't mean everything is ready, there's plenty of things that won't be available until the next frame or the next physics frame due to registering and updating

**Comment by PiewieP** [comment]
I ran into this limitation with the following use case:
Building a menu which allows users to customize the layout of the user interface by dragging the corners of the displayed dummy containers. Clicking the 'apply changes' button writes the layout (i.e. sizes and position of said containers) away to a config file.
Clicking the 'undo changes' button resets the layout to the starting layout which is cached in `_ready()`, but that is precisely the place I'm unable to cache them.

It feels unnatural to have to await get_tree().process_frame() before being able to reliably cache the containers' size and position.
Just thinking out loud here, would it be an option to get a signal like `children_finished_drawing()` or something?

Also, I had a hard time finding this in the documentation, to be fair, I haven't found it at all. I've looked in `Control`, `CanvasItem `and `PanelContainer`. I checked [this page](https://docs.godotengine.org/en/stable/tutorials/ui/gui_containers.html#using-containers) for good measure and unless I glanced over it, the behaviour is not documented.

**Comment by markdibarry** [comment]
It was mentioned before, but what would this `children_finished_drawing` signal look like? How would it work?

When you instantiate a scene, a node's `_ready()` isn't hit until all of its children are ready, and they're not ready until their children are ready, and so on. This propagates up.

What about size and position? This can propagate up *and* down depending on tons of factors. How big is a `Control` when its `_ready()` is called? That depends on how it's set up. In some cases it depends on the size of its parent and sometimes on the size of its children. When you ask how big the parent is in the child's `_ready()` method, you're asking how big the parent is before it's ready and before *its* parent is ready. To determine how big each child is and its position, it may need resized and resorted dozens of times with every ancestor that becomes ready. So, the question is "how do we know that this is the last time this `Control` will be resized or moved?" and depending on your setup it may be "never" because it'll keep resizing as things change.

There are two ways to really handle this *consistently*:
- If you need to make sure things are in place *any time* it moves or is resized, you can hook into some stuff like resorting, or the `resized` or `item_rect_changed` signals. This way you can be guaranteed it's in the right place at all times no matter what happens.
- If you just want to know when the sorting is finished *initially* and you *know that it won't move further* you can just `await get_tree().process_frame()` or `call_deferred()` (both work a little differently though).

Again, the amount of re-sorting will depend on your layout and how many time it's necessary to propagate up and down until it's settled, but you can see the order of most things with some debug statements:

<img width="663" height="777" alt="Image" src="https://github.com/user-attachments/assets/482fd542-aefe-40f3-aae6-dee661eab02e" />
