### ISSUE TITLE
godot 4 beta 14/15 graphical issues

### ISSUE THREAD

**Issue by Gloxide** [godotengine/godot#72097]
### Godot version

4.0.14

### System information

windows 10, Vulkan, Nvidia GeForce GTX 1050 ti,  game ready driver 526.98

### Issue description

it started when i would try to load my project with my background, then i removed it witch fixed it, then my games logo started to do it, so i tried to changed it into a sprite didn't help so i imported it as an image and when it reloaded the editor the Godot window is full of garbage.

just incase i did use paint.net to make the images.
godot beta 14:
![image](https://user-images.githubusercontent.com/76183058/214756721-e8cba597-445d-4646-8aa8-df599ac125cc.png)
godot beta 15:
![image](https://user-images.githubusercontent.com/76183058/214759742-293bd8be-8a91-4c77-9a61-163e25a3433d.png)

godot beta 14 shows the garbage,
godot beta 15 shows garbage but less or it
### Steps to reproduce

I open the project and if i doesnt put garbage on the whole screen i add the images as a sprite or image rec and run

the background and logo in my project tend to do it no matter what, and ive had it get worse almost every time i open godot, in beta 14 or 15

### Minimal reproduction project

[source.zip](https://github.com/godotengine/godot/files/10506260/source.zip)

**Comment by clayjohn** [comment]
Unfortunately this looks like artifacts caused by your GPU. Typically you see things like this with older GPUs that are approaching the end of their life. However sometimes it can happen from other issues like if your GPU isn't plugged in all the way or if the drivers are out of date. 

I would first update your drivers to the latest ones (it looks like some were released for your GPU yesterday https://www.nvidia.com/en-us/geforce/drivers/), then take the GPU and put it back in. 

To rule out this being a vulkan issue you should test the engine using the compatibility renderer which uses OpenGL instead of Vulkan. 

Its also a good idea to test a few other Vulkan based apps/games to see if you get similar artifacts when utilizing your GPU

**Comment by Gloxide** [comment]
thank you, i totally forgot to update my driver that's all it was
