### ISSUE TITLE
Export as dedicated server - Selecting folder does not propagate to children

### ISSUE THREAD

**Issue by AlmightyLaxz** [godotengine/godot#72156]
### Godot version

v4.0.beta.mono.custom_build [d1e5903c6]

### System information

Arch Linux, Vulkan

### Issue description

While using the new "Export as dedicated server" Export Mode introduced in #70377, ticking a folder does not tick all children like the other modes.

When a project has hundreds or thousands of resources it would be tedious to have to click them all individually.

Below looks to be the cause, it looks to be handled differently as the file mode (e.g Strip Visuals) would need to be setup for each of the children as well.

https://github.com/godotengine/godot/blob/d1e5903c67956707948b1de370b807e3aad395b7/editor/export/project_export.cpp#L842-L854

Ideally, if a folder's file mode is changed then that would propagate to any ticked children as well.

### Steps to reproduce

1. Open Project>Export
2. Add or click on an existing preset
3. In the Resources tab select "Export as dedicated server" as the Export Mode
4. Tick a folder, observe no children are affected.
5. Try the other selective export modes, ticking folders also ticks all child files & folders

### Minimal reproduction project

N/A

**Comment by dsnopek** [comment]
When you tick a parent and select "Strip visuals" (for example) that _will_ automatically propagate to all children!

However, the checkboxes by the children are NOT meant to automatically get ticked like the other export modes. The way it works is that the parent's mode propagates until it hits an child item that is also ticked and has a different mode selected.

So, in this screenshot:

![Selection_486](https://user-images.githubusercontent.com/191561/214120684-06174333-4df6-46a5-a673-19d3d9de004d.png)

The top-level ("/") is set to "Strip visuals", so that becomes the default for all children (and grandchildren and so on). But the "some_scenes/" folder is also checked and set to "Remove" - this means that the default for all its children becomes "Remove" which will affect the "test_embedded_resources.gd", but the other two children have their own settings overriding that default.

I hope that makes sense?

I guess the summary is that this mode works differently than the other modes. We should probably add something to the UI to signal that somehow?

**Comment by dsnopek** [comment]
I had thought about how to indicate what is happening in the UI: what if checking the parent and setting, say, "Strip visuals" would put "Strip visuals" (read only, and grey out to indicate that it's read only) by all the affected children, and then you'd need to tick the checkbox by a child to make the mode read-write allowing you to change it from "Strip Visuals" to something else?

**Comment by dsnopek** [comment]
I just made PR #72412 implementing my idea in the previous comment.

It looks like this:

![Selection_005](https://user-images.githubusercontent.com/191561/215589784-34ef533f-0a8b-48b5-b2c2-7a797d110f4d.png)

**Comment by AlmightyLaxz** [comment]
Thanks for that change, I think the greyed out modes make it a lot clearer.
From my understanding now, a tick indicates a kind of override from the parent's 'export mode' on the side?
If so, I think part of my confusion came from the names of the modes - Keep & Remove.

I think it'd be more clear language wise to rename Keep as "Export With Visuals" and Remove as "Do not export".
Coming straight from the export mode "Export selected resources" it seems odd to me that something needs to be 'kept' or 'removed' rather than it just be in the exported project or not.
Might be just me though?

Thanks for your work on the dedicated server export!

**Comment by dsnopek** [comment]
> From my understanding now, a tick indicates a kind of override from the parent's 'export mode' on the side?

Yep!

> I think it'd be more clear language-wise to rename Keep as "Export With Visuals" (or even Keep Visuals) and Remove as "Do not export".

Hm, yeah, that makes a lot of sense. This probably needs more discussion with more folks, though. Can you open a new issue about this?

> Coming straight from the export mode "Export selected resources" it seems odd to me that something needs to be 'kept' or 'removed' rather than it just be in the exported project or not.

It's tricky. The other modes have essentially binary selection (it's in or it's not) but here its ternary, or actually, "quadrinary?" (since it's "no override", "strip", "keep" or "remove"), and Juan's original proposal actually called for two more modes (although, I'm not sure if/when those would get added).

**Comment by Festerdam** [comment]
I think even with https://github.com/godotengine/godot/pull/72412, it should be clearer. How about a text like the one that explains what "strip visuals" means, but explaining that the selecting/deselecting defines whether the export mode for that particular resource are inherited or overridden. I think it's especially important, because I don't think graying out "strip visuals", "remove", "keep" clearly conveys inheritance (at least that's not how I initially interpreted it, I interpreted it as it not being included in the export), and because this export menu's selection behaviour behaves very diferently from the other export menus.

**Comment by Calinou** [comment]
> I think even with #72412, it should be clearer. How about a text like the one that explains what "strip visuals" means, but instead explicitly states that the selecting/deselecting defines whether the export mode for that particular resource is inherited or overridden. I think it's especially important, because I don't think graying out "strip visuals", "remove", "keep" clearly conveys inheritance (at least that's not how I initially interpreted it, I interpreted it as it not being included in the export), and because this export menu's selection behaviour behaves very differently from the other export menus.

I think we could replace grayed out texts to add an "Inherit:" prefix.

**Comment by dsnopek** [comment]
> I think we could replace grayed out texts to add an "Inherit:" prefix. I'm not sure if this is easily done given the way the dialog is set up though.

Hm. Or, maybe an "(Inherited)" suffix? So, it could still be greyed out, but if it's inherited the text would be like "Strip Visuals (Inherited)"

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/76700 which adds this:

![Selection_032](https://user-images.githubusercontent.com/191561/235953190-350dd7cc-8136-47d5-9a0f-7fd08bab7565.png)

What do you think?
