### ISSUE TITLE
Godot 4 Mouse get locked after clicking an editable field in the editor

### ISSUE THREAD

**Issue by Reports1874** [godotengine/godot#72187]
### Godot version

4.0.beta16

### System information

Debian GNU/Linux 11 (bullseye) x86_64

### Issue description

The issue seems a bit random sometimes, but I have found that whenever I try to edit a field in the editor (position, scale, etc) after editing another one, the mouse get locked and I can't do anything until I press ESC or I click again.

Currently using beta16, but noticed it on earlier betas as well.

### Steps to reproduce

The easiest way to reproduce the issue, but not the only one:
Edit one field, press ESC and click another field.

Short video demostration (24s):
https://youtu.be/6iNe30KnLhQ

### Minimal reproduction project

N/A

**Comment by Sauermann** [comment]
Unable to replicate this on Windows.

The edited `EditorSpinSlider` doesn't receive the Left-MouseButton-Up event and so it assumes that mouse movements are meant to start dragging, so that `MOUSE_MODE_CAPTURED` is activated in `EditorSpinSlider::gui_input`.
Bisecting shows that this got introduced in #70052.

**Comment by Juuliuus** [comment]
Hi, I can confirm this. I'm using Beta 16 on kubuntu 22.04.

In my case I had opened a PBR material. Had just changed the albedo and went to expand the emission section. Instead of expanding the emission it expanded Anisotropy. From then on all left clicks, even on the main menu items, kept flipping Anisotropy section. I got left click control back when I did a Projects save all with ctrl shift s.

**Comment by Calinou** [comment]
Related to https://github.com/godotengine/godot/issues/72012.

**Comment by Juuliuus** [comment]
@Reports1874  I am also on 17 now, I reproduced my steps as best I could from my description. I also tried a variety of other things and I can not make it happen again.

**Comment by YuriSizov** [comment]
> Bisecting shows that this got introduced in #70052.

fyi @bruvzg

**Comment by bruvzg** [comment]
This should be already fixed.
