### ISSUE TITLE
[Godot 4 beta 14] `TextEdit.set_text("")` emits `_on_line_edited_from()` twice when it shouldn't emit it at all, bug

### ISSUE THREAD

**Issue by TheWarmWaffle** [godotengine/godot#72241]
### Godot version

4.0 beta 14

### System information

windows 10

### Issue description

only when you execute `TextEdit.set_text("new_text")` the signal `_on_line_edited_from()` gets emitted twice, and by my understanding it shouldn't emit at all because the signal `text_set()` can be connected for users that want it, and it doesn't get called for `text_changed()` either

### Steps to reproduce

Open and run TestControl.tscn, when you press the set text button, notice boolvar prints twice, first with boolvar set to false, then set to true, because at the end of the signal boolvar is set to true

### Minimal reproduction project

[TextEditTest.zip](https://github.com/godotengine/godot/files/10527045/TextEditTest.zip)

**Comment by Paulb23** [comment]
This is the expected behaviour. `text_changed` emits once for all changes apart from set/clear which are covered by `text_set`. `lines_edited_from` will emit no matter what, and as soon as the text is changed. So in a complex edit such as `set_text` where it first clears the old text (1st edit) then sets the new text (2nd edit), it will be emitted twice.
