### ISSUE TITLE
[Build System] compling with MSVC (14.3) is verbose

### ISSUE THREAD

**Issue by kuhnchris** [godotengine/godot#72246]
### Godot version

master

### System information

Win 11

### Issue description

Debug output, incase it's specific to a certain MSVC version:
```
c:\Dev\godot>scons separate_debug_symbols=true debug_symbols=true
scons: Reading SConscript files ...
Automatically detected platform: windows
Auto-detected 12 CPU cores available for build parallelism. Using 11 cores by default. You can override it with the -j argument.
Found MSVC version 14.3, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
Checking for C header file mntent.h... no
scons: done reading SConscript files.
scons: Building targets ...
[  0%] Compiling platform\windows\console_wrapper_windows.cpp ...
[  0%] console_wrapper_windows.cpp
[  3%] Compiling main\main.cpp ...
[  3%] Compiling main\main_timer_sync.cpp ...
[  3%] Compiling main\performance.cpp ...
[  3%] main.cpp
main_timer_sync.cpp
performance.cpp
```
(weirdly the logs shows it in order, the real output looks like this:
![image](https://user-images.githubusercontent.com/761911/215266047-fb06f36f-2556-4323-a478-65640948cc8d.png)

)

the lines without the `[ x% ]` are the output of MSVC, apparently.
Doesn't happen when using MinGW/gcc/linux.
Using "debug_symbols=true" or "separate_debug_symbols=true" is irrelevant, it happens even without them.
Low priority as it's just a "optics" thing (and possibly increasing build log size)

### Steps to reproduce

* Have MSVC
* Compile godot (master) from source.

### Minimal reproduction project

N/A

**Comment by Kabiirk** [comment]
Hi,

I'm still going through the Godot source code, as per my understanding, In the ```SConstruct``` file, the below code is executed :
https://github.com/godotengine/godot/blob/218bef90af2091afde3b1be816c87286c194a2a8/SConstruct#L955-L960 

which calls the below code
https://github.com/godotengine/godot/blob/218bef90af2091afde3b1be816c87286c194a2a8/methods.py#L1034-L1047

and somewhere, these variables are being called as well
https://github.com/godotengine/godot/blob/218bef90af2091afde3b1be816c87286c194a2a8/methods.py#L533-L556

After going through the file, could it have something to do with the ```flush()``` in ```methods.py``` ?

As per my understanding ( ref. [Link 1](https://www.geeksforgeeks.org/python-sys-stdout-flush/) & [Link 2](https://stackoverflow.com/questions/10019456/usage-of-sys-stdout-flush-method) )
> ```sys.stdout.flush()``` forces it to “flush” the buffer, meaning that it will write everything in the buffer to the terminal, even if normally it would wait before doing so.

Since screen in ```sys.stdout```, maybe when the ```screen.flush()``` is called in ```method.py```, it is outputting what's in the buffer (```$SOURCE```) at the time ```flush()``` method is called ?

**Comment by kuhnchris** [comment]
I rather think that this is due to the compiler (the MSVC one) doing that by default - i.e. if you compile a file by hand it also shows the filename as an output.
I actually found a thread on the thread on the Dev Community by @aaronfranke (https://developercommunity.visualstudio.com/t/allow-having-clexe-not-print-the-compiled-source-f/717761) from 2019 - seems like this is a known issue right now, not much we can do. People suggested prehaps redirect stdout (>NIL), but I fear it may also affect warnings (or errors)...

**Comment by aaronfranke** [comment]
Yup, this is not a Godot bug, this is a bug with MSVC. Please share that link and get your friends to upvote it :)
