### ISSUE TITLE
Bone Attachments children get eliminated after reimporting the .glb file.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#72264]
### Godot version

4.0 beta 16

### System information

Ubuntu 22.04

### Issue description

When reimporting a .glb model, all the children of bone attachments disappear even if the model does not change structure names like bones and meshes. This means we need to re make the work every time the model gets updated. It did not happen in beta 15.  Previously, even if the model changed heavily, bone attachments and their children got backed up with @ @ names. 

### Steps to reproduce

Import a .glb 3d model. Make it children of a scene and mark it as "editable children". Then attack some Bone Attachments and add some children to them. Save the work. Then reimport the model with some minor updates like modified animations. It turns out that the attachments children are gone in the scene hierachy view. They are visible in the 3d viewport but they are gone.

### Minimal reproduction project

N/A.

**Comment by lyuma** [comment]
I've been noticing something unusual about node owneship related to BoneAttachment3D:
Every time I switch tabs and switch back, my bone attachments turn black.
![showing some bone attachment and skeleton nodes black](https://user-images.githubusercontent.com/39946030/215654055-3c8538c3-4059-457b-bac1-04a1b466ee8a.png)
I have to select the skeleton3D node to fix it, but they seem to act strange if I switch tabs again.
![now all nodes are yellow](https://user-images.githubusercontent.com/39946030/215654065-083502fa-e4f9-4cf5-b55f-ea884a35a9e9.png)

`Node.owner` is what determines which nodes show up as part of the inherited scene or not (black), and it also sounds a bit like the culprit here.

I don't really understand yet if this is the issue, so I'll have to keep looking into it. Just something I noticed which seemed unusual.

**Comment by lyuma** [comment]
I suspect this was actually caused by #57606 - reloading reimported scenes
cc @SaracenOne

**Comment by SaracenOne** [comment]
Yeah, I was afraid of regressions it could introduce. I shall try to investigate it as soon as possible.
