### ISSUE TITLE
Control._has_point(position) description is outdated

### ISSUE THREAD

**Issue by Lielay9** [godotengine/godot#72283]
### Godot version

v4.0.beta16.official [518b9e580]

### System information

-

### Issue description

The description of `Control._has_point(position)`-virtual function is outdated likely due to #66688. 

> Note: If you want to check if a point is inside the control, you can use `get_rect().has_point(point)`.

After #66688, get_rect() returns the Controls rect relative to its parent, while the point is relative to the Control.

Also, the note refers to `point` while it likely should refer to the parameter `position`. That said, in this case, I think the incorrect name is better and the parameter of the function should be changed to`point` to avoid shadowing `Control.position`.

Suggested fixes:
1. Change the note to match the new behavior (`Rect2(Vector2.ZERO, size).has_point(point)` should work; verify) OR introduce `get_local_rect()` that matches the old behavior and recommend using it instead.
2. Change the name of the `position` parameter to `point` in `Control._has_point(position)`

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by Kabiirk** [comment]
Hi,
I can work on this in some time.

Will message again if I have any queries.

**Comment by Sauermann** [comment]
I missed this detail in #66688.
@Kabiirk please let me know, if you want me to fix this instead. I just want to avoid that we both do the same work.

**Comment by Kabiirk** [comment]
I'll have a crack at it.

Since I am still finding my way around Godot's codebase, this seems like a good opportunity to learn about docs and contribute.

**Comment by Kabiirk** [comment]
Hi,

I am facing a slight challenge while testing the changes in ```doc```/```classes```/```Control.xml``` in the Godot editor.

### **Solution being implemented:**
Based on the explanation above I decided to ```change the name of the position parameter to point in Control._has_point(position)``` & made the following changes in ```Control.xml``` :
![image](https://user-images.githubusercontent.com/16386226/216788065-6691181a-8584-469f-8ca8-ad5bdec311ae.png)

-----

### **Current challenge:**
Apart from the text body, there are no other changes being reflected in the Editor docs for ```Controls``` (i.e. the **Search Help (F11)** option) which was intended behavior, their current look is as follows :
1. In the **Method Descriptions** Section, while the definition of the function changed. But the bullet ```bool _has_point(position: Vector2) virtual const``` still looks like it did before I made the change 
![image](https://user-images.githubusercontent.com/16386226/216788104-e1fa4a23-01c4-4080-83c5-f2b2a2edf802.png)
2. The **Methods** section still looks like this
![image](https://user-images.githubusercontent.com/16386226/216787954-c27ebc4c-564b-4a44-a3bd-d786a96570e9.png)

-----

### **Steps followed :**
I referred the below links as mentioned in the Contribution Guidelines: 
1. [Contributing to the class reference](https://docs.godotengine.org/en/latest/contributing/documentation/updating_the_class_reference.html#doc-updating-the-class-reference)
2. [Compiling for windows](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html)

After making changes to ```Control.xml```, I compiled Godot from source using ```scons platform=windows``` and then executed the compiled Godot binary from the Godot root directory with the `--doctool` flag. I am using PowerShell, so the command used I used was
```
C:/path_to_godot_root_directory/godot> .\bin\godot.windows.editor.x86_32 --doctools
```

While I know what the change should look like (`position` should be replaced with `point` wherever necessary for ```_has_point()```). Please let me know if I am missing something (maybe an extra step while compiling ?), because of which, these changes aren't being updated in the Editor view ?

Thanks in advance !

**Comment by Sauermann** [comment]
@Kabiirk
This part of the xml-documentation is autogenerated with the command `--doctools`

It is defined by the content of `Control::_bind_methods()`

You should have a look at
https://github.com/godotengine/godot/blob/00302860541e9cccc59abd93b930af2a6e6ec360/scene/gui/control.cpp#L3393

**Comment by Kabiirk** [comment]
Ah, I see, 
Thanks for pointing me in the right direction.

This also explains how those sections were not in the ```Control.xml``` but still visible in the docs.
