### ISSUE TITLE
TileMap Y-Sort sorts by X position too much for large tiles

### ISSUE THREAD

**Issue by Anixias** [godotengine/godot#72322]
### Godot version

v4.0.beta16.mono.official [518b9e580]

### System information

Windows 10

### Issue description

Using Y-Sort in a TileMap does not behave as expected when using large tiles:

![image](https://user-images.githubusercontent.com/22286697/215344922-58bc1ff7-870d-4b5c-914b-02f6d94626f4.png)

The large trees should both obscure the small tree, but notice that that tree on the right is drawn behind the small tree. This is not apparent until the large tree is 2 or more tiles to the right of the small tree:

![image](https://user-images.githubusercontent.com/22286697/215344971-15275514-e63c-4c97-8c98-62fb748a3d12.png)
![image](https://user-images.githubusercontent.com/22286697/215344976-6715d876-76b2-4fd6-aa67-fd543c45f2f7.png)

### Steps to reproduce

1. Create a large tile that is more than 3 tiles wide
2. Place it 2 or more tiles to the right (and 1 tile or more below) a smaller tile (3x3 in my case for the small tree)
3. Observe the incorrect sorting
4. Repeat but place the larger tile anywhere left of 2 tiles to the right of the small tile
5. Observe the correct sorting

### Minimal reproduction project

[YSortIssueMRP.zip](https://github.com/godotengine/godot/files/10530763/YSortIssueMRP.zip)

**Comment by kleonc** [comment]
> ### Steps to reproduce
> 
>     1. Create a large tile that is more than 3 tiles wide
> 
>     2. Place it 2 or more tiles to the right (and 1 tile or more below) a smaller tile (3x3 in my case for the small tree)
> 
>     3. Observe the incorrect sorting
> 
>     4. Repeat but place the larger tile anywhere left of 2 tiles to the right of the small tile
> 
>     5. Observe the correct sorting

Can't reproduce. Please upload minimal reproduction project.

Without MRP I'd guess it's a matter of incorrect setup of the tiles. E.g. for a tree tile make sure that `y_sort_origin` is located at the base of the trunk (seems like its relative to `texture_offset` so take it in mind).

**Comment by Anixias** [comment]
![image](https://user-images.githubusercontent.com/22286697/215348839-2470b115-f6ed-4386-ad37-dcb25940edb4.png)
Y Sort Origin is set up correctly. I will see if I can make a minimal reproduction project.

**Comment by Anixias** [comment]
![image](https://user-images.githubusercontent.com/22286697/215353915-7149fe04-1e8d-4c3a-b91d-decd5656ce74.png)
This bug is inconsistent, and seems to depend on the actual tile coordinates (look at the top-middle, note the red is over the green). Uploading MRP to original comment.

**Comment by kleonc** [comment]
So the issue happens when the tiles are within different quadrants:
![Godot_v4 0-beta16_win64_4PrDDyzmI3](https://user-images.githubusercontent.com/9283098/215356881-eee9ce8b-36ba-495b-bd2f-fb75057f8928.png)
![zxT7NOa8Bj](https://user-images.githubusercontent.com/9283098/215356883-14cb2b6e-2c88-46db-a930-cc364e017763.png)
![YCIeHy343s](https://user-images.githubusercontent.com/9283098/215356884-2c44129e-d551-44fd-9510-fe46ab96e004.png)



cc @groud

**Comment by groud** [comment]
You need to enable Y-sort on the TileMap node itself.

https://user-images.githubusercontent.com/6093119/215433662-06974fd3-d093-4aa3-a0be-f42e2840da17.mp4

**Comment by kleonc** [comment]
@groud But shouldn't the layers be y-sortable on their own?:thinking: AFAIU TileMap for each of its layers creates a separate child canvas item within the RenderingServer. If that's the case then sorting tiles within a single layer is a matter of marking the given layer's canvas item as y-sorted within the RenderingServer (and effectively drawing each tile separately). Enabling y-sort for the TileMap itself should be needed only when the tiles from different layers should be y-sorted together, instead of separately for each layer with enabled y-sort.

At least that's how I'd think it works. But I might be missing something in here.

**Comment by groud** [comment]
> @groud But shouldn't the layers be y-sortable on their own?

Technically, it should be possible to do so. I can modify it to make it work, but it might be a source of confusion anyway, 
there's not way to have two Y-sorted layers work well together if you don't set the TileMap node as Y-sorted too.

Also, if you need to mix Y-sorted and not Y-sorted layers, you need to set their Z-index to different values anyway, as having the TileMap node set as Y-sorted will lead to the not Y-sorted layer to be weirdly inserted between the Y-sorted ones.

All of this to say that there are not really a lot of use cases where you would set a layer as Y-sorted, but not set the whole TileMap itself as Y-sorted.

Maybe I could do the following:
- Fix per-layer Y-sorting, so that you can mark a layer as Y-sorted individually.
- Change the warning to pop only if more than one lay is Y-sorted.

I am not sure it's a super useful improvement, as, like, there's not really a situation where you would Y-sort a layer without Y-sorting the TileMap. But if that can help reduce some confusion, I guess that could help, idk.
