### ISSUE TITLE
Array cannot be Un-Typed, or Array.is_typed() is broken.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#72347]
### Godot version

4.0.beta.16

### System information

N/A

### Issue description

```gdscript
var typed_array: Array[Node] = []
var array : Array = typed_array
print(array.is_typed())
print((typed_array as Array).is_typed())
var array2 : Array[Variant] = typed_array
print(array2.is_typed())
print((typed_array as Array[Variant]).is_typed())
```
All prints `true`

### Steps to reproduce

N/A

### Minimal reproduction project

[godot.4.0.beta15.bugs.0.zip](https://github.com/godotengine/godot/files/10531948/godot.4.0.beta15.bugs.0.zip)

**Comment by anvilfolk** [comment]
This may have changed with the big #69248 PR of @vonagam's. Would you be able to check in Beta 17?

**Comment by vonagam** [comment]
Well, the code that shown would not change. But there is a way to make array untyped now:
```gdscript
var array: Array = []
array.assign(typed_array)
```

**Comment by dalexeev** [comment]
I checked the description and MRP (please don't combine many issues in one MRP) and I don't think there are any bugs/issues that are currently unresolved or not tracked in other threads.

Since arrays are passed by reference, it makes no sense to make an already existing array untyped, which would break the following code:

```gdscript
var a: Array[int] = []
var b = a
b.set_untyped()
b.append("string") # Now `a` contains string?!
```

Instead, you should create a new array. Note that `var array : Array = typed_array` does **not** create a new array. But you can use the `assign()` method, which assigns (copies) the contents rather than a reference.

See also:

* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
* #80586
* godotengine/godot-proposals#7364
* #71336

Note that there are bugs that may cause this to work incorrectly in some cases:

* https://github.com/godotengine/godot/pull/72514#issuecomment-1628893636
* #81332

If you still have any issues with typed arrays, please post here, in the appropriate thread from the list above, or open a new issue.

Thanks for the contribution nonetheless!
