### ISSUE TITLE
Typed array constructor cumbersomeness.

### ISSUE THREAD

**Issue by rambda** [godotengine/godot#72355]
### Godot version

4.0.beta.16

### System information

N/A

### Issue description

```gdscript
# Array(base: Array, type: int, class_name: StringName, script: Variant)
Array([0], TYPE_INT, &"", null)  # Works
Array([0], TYPE_INT)             # Error
Array([0], TYPE_INT, null, null) # Error
```
I think we could add more constructors.

### Steps to reproduce

N/A

### Minimal reproduction project

[godot.4.0.beta15.bugs.0.zip](https://github.com/godotengine/godot/files/10532081/godot.4.0.beta15.bugs.0.zip)

**Comment by dalexeev** [comment]
> ```gdscript
> Array([0], TYPE_INT)             # Error
> ```

Invalid number of arguments.

> ```gdscript
> Array([0], TYPE_INT, null, null) # Error
> ```

All `Variant` types except `Object` are not nullable. That is, `null` is an invalid value for an argument of type `StringName`.

> I think we could add more constructors.

See:

* #71336
* godotengine/godot-proposals#7364
* #79066
* #79075

The `Array(Array, int, StringName, Variant)` constructor is for creating typed arrays dynamically when you don't know the type beforehand. This is rarely needed, I don't think we need more _dynamic_ typed array constructors.

If you know the type of the typed array in advance, now you can use a temporary variable with the specified static type:

```gdscript
var a: Array[int] = [1, 2, 3]
my_func(a)
```

In the future, we'll add a handy typed array constructor so you can create typed arrays on the fly, without the need for temporary variables:

```gdscript
my_func(Array[int]([1, 2, 3]))
```

Note that you can now use untyped literals, and they will automatically be cast to the required type if it is known from the context:

```gdscript
my_func([1, 2, 3])
```

This behavior is convenient but can be confusing because it doesn't work if the function's type is unknown at compile time or the user doesn't fully understand in which contexts it works and which it doesn't.

I believe there is no bug here. This inconvenience is known and is being tracked in other issues. Thanks for the contribution nonetheless!
