### ISSUE TITLE
`randfn` can extremely rarely return nan in some cases

### ISSUE THREAD

**Issue by FeldrinH** [godotengine/godot#72394]
### Godot version

3.5, 4.0 beta and probably most other versions that have `randfn`

### System information

N/A

### Issue description

I believe there is a possibility that `randfn` (implemented in https://github.com/godotengine/godot/blob/master/core/math/random_pcg.h), can extremely rarely produce nan when `deviation` is 0 or in even rarer cases with any `deviation` value.

This is because the value is computed as `p_mean + p_deviation * (cos(Math_TAU * randd()) * sqrt(-2.0 * log(randd())))`.  
When `randd()` returns 0 then `log(randd())` would be -infinity and by extension `sqrt(-2.0 * log(randd())))` would be infinity. If `p_deviation` or `(cos(Math_TAU * randd())` is 0 then this would lead to a value of 0 * infinity which under IEEE floating point standard is nan.

While this is an extremely rare occurrance (in fact I have yet to successfully produce it in godot), it would be nice if this was fixed or documented, so that if someone does happen to come across it they will at least know what happened.

### Steps to reproduce

In theory it should be reproducible by running `randfn` calls with a `deviation` value of 0 for a long time and checking for nan, but this is rare enough that it would probably take more than several days of continuous running to observe a single occurrance.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can we return `0.0` after checking whether the output is `nan` (using `unlikely()` optimization hint)?

**Comment by vpellen** [comment]
```GDScript
extends Node

func _ready():
	seed(3965468160)
	for i in range(100000):
		if is_nan(randfn(1, 0)):
			print(i)
```
This reproduces the error on my machine, not sure if the RNG is platform-dependent (4.0 rc2, win64 standard build)
I will not attempt to reproduce it on a `randfn` call with a non-zero SD, though I may later test if two consecutive identical randf calls is even possible (I don't know the underlying behavior of the RNG, but I have a sneaking suspicion that producing 0 twice in a row may actually not be possible, though I lack the mathematical rigor to even begin to prove such)

**Comment by vpellen** [comment]
On further inspection, I've realized that nan isn't the only degenerate case. Even if the `cos` factor is non-zero, the `log(0)` still ends up propagating the infinity through to the output, and while I'm sure some eager mathematician would be happy to argue that, technically speaking, a bell curve has no bounds, I suspect most users would expect `randfn` to output a finite value, and little would be gained by violating that assumption.

To that end, rather than attempting to verify the integrity of the output, perhaps a preferable solution would be to ensure that the value passed to `log` is non-zero. I propose caching an initial `randf` call and returning `p_mean` in the (optimized for unlikely) event that the cached value is 0. That way, we would eliminate all problematic cases.

An alternative would be to replace `log(randf())` with `log(randf_range(EPSILON, 1))`, although I forget if `EPSILON` is an actual constant within the code, and I wouldn't be surprised if the scaling of `randf_range` ended up incurring a greater performance hit than the branching.
