### ISSUE TITLE
Dock icons become blurry when launched

### ISSUE THREAD

**Issue by igorskuhar** [godotengine/godot#7258]
**Operating system or device - Godot version:**
Mac OS X 10.11.4 (MBP 2015 Retina) - Godot v2.1.1.stable

**Issue description** (what happened, and what was expected):

Dock icons for both Project Manager and Editor become blurry when their are launched.
They become sharp again after closing apps. 
It happens on both HiDPI and LoDPI displays. 

<img width="201" alt="blurry_dock_icon" src="https://cloud.githubusercontent.com/assets/5592468/20948297/bce39260-bc13-11e6-8d8f-278dab361073.png">

**Steps to reproduce:**
1. Click Godot Project Manager icon in the dock.
2. Icon will become blurry.
3. Close the Godot Project Manager.
4. Icon will become sharp again.

The same steps work for Godot Editor dock icon.

**Comment by Noshyaar** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Calinou** [comment]
This issue seems resolved as of Godot 3.0 (tested on macOS 10.13 High Sierra with a self-compiled Godot from commit https://github.com/godotengine/godot/commit/2f4f8de459f8b45a3a80018753f0fa24dc138809):

**Unopened Dock icon:**

![godot_macos_unopened](https://user-images.githubusercontent.com/180032/38469518-5921f186-3b56-11e8-9565-48b0c94ec575.png)


**Project manager Dock icon:**

![godot_macos_project_manager](https://user-images.githubusercontent.com/180032/38469516-577b93fa-3b56-11e8-975c-0721e22c3f70.png)

**Unopened and editor Dock icons (from left to right):**

![godot_macos_unopened_and_editor](https://user-images.githubusercontent.com/180032/38469519-5b4184d6-3b56-11e8-8481-e68790a2d9d7.png)

I'm closing this issue, feel free to comment if you can still reproduce this on the `master` branch.
