### ISSUE TITLE
Shaders not rendering property on Android with Samsung SM-A037W

### ISSUE THREAD

**Issue by blackears** [godotengine/godot#72642]
### Godot version

v3.5.2.rc2.official [1a2bf3eb4]

### System information

Windows 10 GLES2

### Issue description

I'm having trouble with shaders rendering incorrectly when I export to Android.  In the attached project is a simple scene with a visual shader on a mesh exported from Blender.  While the mesh with the default shader is rendering fine on my Samsung Galaxy phone, the one with the visual shader is incorrect.  I was having this trouble initially on Godot 3.5 where the custom shader was simply solid red, but am running into a somewhat different display problem with Godot 3.5.2 rc2 as well.

I have tried a variety of project settings, such as enabling `rendering/gles2/compatibility/enable_high_float.Android`, `rendering/gles2/compatibility/disable_half_float`,  and setting `rendering/quality/intended_usage/framebuffer_allocation.mobile` to 3D.

This happens with regular hand coded shaders too.  I just can't seem to get any shaders to work on Android.

This is what I'm seeing on my phone

![image](https://user-images.githubusercontent.com/6724608/216482632-7b42112d-f072-4f5b-a738-8e712608c256.png)

This is what is displayed on desktop:

![image](https://user-images.githubusercontent.com/6724608/216482904-4d98b3c0-2eb9-4742-93e0-4c432e794f03.png)

### Steps to reproduce

Run the project and export to a Samsung SM-A037W.  The mesh with the visual shader on it will not render correctly.

### Minimal reproduction project

[SamsungShaderIssue.zip](https://github.com/godotengine/godot/files/10574522/SamsungShaderIssue.zip)

**Comment by clayjohn** [comment]
The issue here isn't with shaders; it is with ETC texture compression. ETC1 does not support compressing images with alpha channels in them. 

In your MRP the issue appears to be that the mipmaps of the texture are getting all messed up. This could be a problem with Godot's ETC importer, or it could be an inherent limitation of ETC1.

You have two choices, both of which fix the problems in your MRP:
1. Re-import your texture with VRAM compression turned off. or
2. Re-import your texture with mipmaps turned off. 

My guess is the first option is the better option. 

Looking at your shader, you ignore the alpha channel entirely. So a third potential option is to export the texture again with only RGB channels. It should work better with ETC1 after that as well.

**Comment by blackears** [comment]
Sorry.  I had meant to hook the texture's alpha channel up to the weight.  Either way, I was getting the error.

Setting the texture compression to something other than VRAM did fix the problem.  Lossy works for my purposes.
