### ISSUE TITLE
Documentation about compiling for Android for 2.1.1-stable needs 2 additions.

### ISSUE THREAD

**Issue by freemanfromgodotengine** [godotengine/godot#7266]
**Operating system or device - Godot version:**
Xubuntu 16.04 64-bit , Godot 2.1.1-stable but probably also 2.1-stable

**Problem 1**

**Issue description** (what happened, and what was expected):
After doing all steps from documentation 
http://docs.godotengine.org/en/stable/reference/compiling_for_x11.html#distro-specific-oneliners 
and taking care of all needed requirements from 
http://docs.godotengine.org/en/stable/reference/compiling_for_android.html
Compilation stops at error:

```
Incremental java compilation is an incubating feature.
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:preReleaseBuild UP-TO-DATE
:prepareComAndroidSupportSupportV42340Library UP-TO-DATE
:prepareDebugDependencies
:compileDebugAidl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugAidl'.
> java.lang.RuntimeException: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/home/user1/Android/android-sdk-linux/build-tools/23.0.3/aidl''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Only after installing additional and not mentioned in the documentation 32-bit libraries it's possible to build Android templates.

Please add `lib32z1 lib32ncurses5 lib32stdc++6` to the required one liner on Ubuntu.
For Fedora it probably should be `zlib.i686 ncurses-libs.i686 bzip2-libs.i686`
in the documentation at http://docs.godotengine.org/en/stable/reference/compiling_for_x11.html#distro-specific-oneliners
or maybe at the http://docs.godotengine.org/en/stable/reference/compiling_for_android.html .

**Problem 2**

**Issue description** (what happened, and what was expected):
In the r10e version of Android NDK, in the /toolchains/ folder there is no /llvm/ subfolder that Scons is looking for, so Scons fails to compile for Android.
There are only llvm-3.5 and llvm-3.6 folders, so simple solution is to create a llvm symlink to llvm-3.6 or change Scons to search in more places for llvm* folder.

**Comment by chanon** [comment]
I've just run into Problem 2. Can confirm.

**Comment by freemanfromgodotengine** [comment]
I can confirm that NDK r14beta2 I used lately does not have llvm folder problem anymore. Still, at least in ubuntu 16.04 with Godot 2.1.2 the lack of libraries I mentioned is still present - testeg again on freshly installed system.

**Comment by akien-mga** [comment]
The instructions have been updated to require the r13* NDK already, so that part should be fine.

As for the missing libs, that's weird. Compiling for Android should not be using shared libraries from your distro (otherwise it wouldn't be possible to compile for Android while on Windows), especially not runtime ones like you mentioned (`lib32z1 lib32ncurses5 lib32stdc++6` which are not development libraries, i.e. no headers and .so). All development libraries should be taken directly from the SDK and NDK to cross-compile to the right platform.

So I can only guess that those libraries are dependencies of the SDK - why the Android SDK would need 32-bit libraries on a 64-bit system, I don't know, but that seems to be a SDK issue and not Godot's.

**Comment by freemanfromgodotengine** [comment]
@akien-mga In case somone runs into this, I created Q&A https://godotengine.org/qa/12652/problem-compiling-godot-2-1-for-android-on-ubuntu-16-04-64-bit.

**Comment by Noshyaar** [comment]
Is this still an issue? If it is, please report to https://github.com/godotengine/godot-docs repository
