### ISSUE TITLE
animated sprite "playing"

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#72683]
### Godot version

4.0 beta 17

### System information

windows 10 vulkan

### Issue description

the "playing" option true or false, has been removed from "animated sprite", and cant be accessed from script.

### Steps to reproduce

create animated sprite node

### Minimal reproduction project

create animated sprite node

**Comment by raulsntos** [comment]
I think what you are looking for is the `is_playing` method.

https://github.com/godotengine/godot/blob/604493eb6ee3def65aca089c1d4bc71ea03ca19a/doc/classes/AnimatedSprite2D.xml#L21-L25

**Comment by jonSP12** [comment]
õk, if you say so
![aa](https://user-images.githubusercontent.com/77213594/216692889-f06ec1d2-c1cb-48f1-b4c8-6d2d3b2c8bfa.png)

**Comment by raulsntos** [comment]
Oh, if you want to set it, then I guess you are looking for the `play` method.

https://github.com/godotengine/godot/blob/604493eb6ee3def65aca089c1d4bc71ea03ca19a/doc/classes/AnimatedSprite2D.xml#L34-L43

**Comment by dalexeev** [comment]
You can start playback via `play()` in `_ready` OR choose an animation to autoplay via ![](https://user-images.githubusercontent.com/47700418/216693832-297df994-9e92-43f3-b0b8-d874a1804508.png) (but not both).

**Comment by jonSP12** [comment]
thanks, play() is working...
I was hesitant in trying it, has in the manual says it takes a string for the animation name. ( I guess its only optional )

![aa](https://user-images.githubusercontent.com/77213594/216704058-18f9e7c3-c368-415b-bab7-5504459ef7e0.png)

**Comment by Calinou** [comment]
The `=` in the method signature denotes an optional parameter.

This is not a bug but an intentional change, which should be clarified on https://docs.godotengine.org/en/latest/tutorials/migrating/upgrading_to_godot_4.html if the project converter doesn't handle it automatically.

**Comment by TokageItLab** [comment]
In the meantime, the class reference has already been updated, so I believe this can be closed.

**Comment by hsandt** [comment]
Neither https://docs.godotengine.org/en/latest/classes/class_animatedsprite2d.html#class-animatedsprite2d nor https://docs.godotengine.org/en/stable/tutorials/2d/2d_sprite_animation.html#summary mention the new autoplay button to set autoplay directly on SpriteFrames.

The API also still indicates an autoplay property, which I suppose is used internally when setting the Autoplay animation via the GUI, and still provided to the user if they want to set it dynamically by code.

Both pages should mention the button and how it relates to the autoplay property. And the fact that, since autoplay is a property of AnimatedSprite2D, and not SpriteFrames, it is decided by the AnimatedSprite2D instance and therefore not shared with other AnimatedSprite2D using the same SpriteFrames, contrary to what the UI could suggest (i.e. a button on the SpriteFrames panel would usually modify SpriteFrames data, but not in this case). This allows us to have different sprites autoplaying different animations.

I think I'll open an issue on godot-docs.

**Comment by jeancallisti** [comment]
Bonus question : neither "play" nor "is_playing" are standard properties, and therefore cannot be **"keyed"** in an AnimationPlayer. How do you start and stop playing an AnimatedSprite2D in the AnimationPlayer?
