### ISSUE TITLE
animated sprite2D stops playing on clamp frame

### ISSUE THREAD

**Issue by jonSP12** [godotengine/godot#72756]
### Godot version

4.0 beta 17

### System information

windows 10 vulkan

### Issue description

Node ( AnimatedSprite2D ) stops playing animation when clamp is used ( works on beta 15 )
ex: 
$AnimatedSprite2D.frame = clamp($AnimatedSprite2D.frame, 7, 13); 

### Steps to reproduce

AnimatedSprite2D
add script

if ( bltEnd == false ):
  if (  frame > 4 ):
	  frame = 0;

elif ( bltEnd == true ):
 frame = clamp( frame, 7, 13 );
    if (  frame > 11 ):
    queue_free();
![bullet](https://user-images.githubusercontent.com/77213594/216818249-a3b420c3-9a33-46f1-b509-df7564e2ce07.png)

### Minimal reproduction project

beta 17 ( if opened in beta15 the animation sprites disapear )
[bullet_animation.zip](https://github.com/godotengine/godot/files/10610974/bullet_animation.zip)

beta 15
[bullet_animation_Beta15.zip](https://github.com/godotengine/godot/files/10610975/bullet_animation_Beta15.zip)

**Comment by kleonc** [comment]
The new behavior is caused by the changes in #71907. It's working as intended. The docs are updated accordingly so I don't see any issue in here (good news is before 4.0.stable there should be no more compatibility breaking changes like this one (unless they'd be really necessary)).

Specifically, `AnimatedSprite2D.frame`'s docs state:
> The displayed animation frame's index. **Setting this property also resets [member frame_progress]**. If this is not desired, use [method set_frame_and_progress]. 

https://github.com/godotengine/godot/blob/5964e4c202980f5530bc62d448962c6e71f4dcb5/doc/classes/AnimatedSprite2D.xml#L94-L96


So e.g. changing your:
```gdscript
$AnimatedSprite2D.frame = clamp($AnimatedSprite2D.frame, 7, 13);
```
to:
```gdscript
$AnimatedSprite2D.set_frame_and_progress(clamp($AnimatedSprite2D.frame, 7, 13), $AnimatedSprite2D.frame_progress)
```
would make it work like you're expecting it to (BTW there's no reason to not cache that `$AnimatedSprite2D` node :wink:).
