### ISSUE TITLE
[v4.0beta17] .blend files fail to import due to RPC connection

### ISSUE THREAD

**Issue by whattheheckman** [godotengine/godot#72767]
### Godot version

Godot Engine v4.0.beta17.official.c40020513

### System information

Windows 10

### Issue description

When using Godot Beta 17, trying to import .blend files cause Godot to become unresponsive (editor is not rendered and only importer UI is visible, see figure below) for upwards of 30 seconds per file. Every .blend file fails to import throwing a error in the console.

_Figure: Godot unresponsive while trying to import a single .blend file_

![image](https://user-images.githubusercontent.com/40683851/216836047-933fc6d5-52d2-4393-a892-e5382d904bee.png)

_Console output:_ 
```
ERROR: Unexpected status during RPC connection: 4
   at: (modules/gltf/editor/editor_import_blend_runner.cpp:225)
ERROR: Error importing 'res://default_cube.blend'.
   at: _reimport_file (editor/editor_file_system.cpp:2009)
ERROR: Condition "!importer.is_valid()" is true. Continuing.
   at: reimport_files (editor/editor_file_system.cpp:2233)
```

Based on the console output, this bug seems to be related to PR #69319 . This error also **does not** happen on Godot 4 Beta 16.

This error happens with .blend files of various complexity, ranging from nothing but the default cube to meshes with baked images.

This error happens with various RPC ports and RPC server uptime settings as well.

This error also occurs with Blender installs in various locations and versions. I tried Blender 3.4.1 from Steam, Blender 3.4.1 Portable and Blender 3.3.3 LTS Portable.

Expected behavior is for .blend files to import and be able to be used in a scene.

This bug is severely work flow disturbing as Godot tries to reimport .blend files every time the editor is refocused after Alt-Tabbing away, but the bug causes Godot to become unresponsive for ~30+ seconds per file, which quickly adds up if the project contains any number of  .blend files.

### Steps to reproduce

1. Create a empty Godot project in Godot 4 Beta 17.
2. Add a .blend file to the project folder
3. .blend file fails to import after Godot is unresponsive for  30+ seconds.

### Minimal reproduction project

[blender_import_test.zip](https://github.com/godotengine/godot/files/10611728/blender_import_test.zip)

**Comment by akien-mga** [comment]
CC @RedMser @fire @lyuma 

I wonder if it's a matter of users not having yet given Godot the permission to use the LAN. Usually the prompt comes up once when running a new Godot version when playing the game, as the debugger needs it. But here it's the first thing that happens when you open the editor while .blend files are included, so I would assume (didn't test, I'm on Linux) that it shows a permission request in the background but users don't see it and Godot is frozen.

That's just a wild hunch, maybe it's not related. But if that's a potential failure scenario, we should probably fall back to another import method.

Either way, we really need to fix the import system so that when a fail fails importing, it shouldn't be re-attempted every single time you focus the editor. It should be added to an exceptions list until the user attempts to reimport manually.

**Comment by RedMser** [comment]
@whattheheckman As a workaround, you should be able to set the RPC port editor setting to 0, then restart the editor. It should then work as in previous betas.

> I wonder if it's a matter of users not having yet given Godot the permission to use the LAN.

It can also be due to Blender, which creates the RPC server. Since it's run as a command line application, I don't know if a permissions prompt like this would even show up. I will mess with network and firewall settings to see if I can reproduce.

> ERROR: Unexpected status during RPC connection: 4

This is `STATUS_CANT_CONNECT`, which is set in many different places in the HTTPClient implementation, so it's hard to find out which step fails. But the 30 seconds timeout sounds a lot like default connection timeout, and the server is not up. Since it's localhost, this timeout should be greatly reduced.

**Comment by whattheheckman** [comment]
I think we might be on to something with the firewall/proxy settings. The enterprise network I'm on might be setting some weird defaults, and the error has only been happening on my laptop for some reason, my desktop that's plugged into the LAN seems to import fine.


I'll also try setting the RPC port to 0 to see if the old method works fine.

**Comment by Calinou** [comment]
> It can also be due to Blender, which creates the RPC server. Since it's run as a command line application, I don't know if a permissions prompt like this would even show up. I will mess with network and firewall settings to see if I can reproduce.

Windows Firewall should never ask for permission if an app listens on `127.0.0.1` (localhost only), but it will ask for permission if an app listens on `0.0.0.0` (whole Internet, port forwarding nonwithstanding).

It's strange that Blender's RPC server would listen on anything else than `127.0.0.1` by default – this seems like a security risk to me.

**Comment by RedMser** [comment]
@Calinou It is [listening on localhost only](https://github.com/godotengine/godot/blob/ba388d09b4e52fc6254e2bdde67a8bb3ad023d46/modules/gltf/editor/editor_import_blend_runner.cpp#L47), but I'm not really sure what else could cause a local network connection to fail (since changing the port did not seem to fix the issue either). Anti-virus software perhaps?

**Comment by whattheheckman** [comment]
I downloaded the build from PR #72802 and it did fail much quicker instead of taking 30+ seconds to fail. 

Letting both Godot and Blender through Windows Firewall didn't change anything, it still fails to import.

**Comment by Flavelius** [comment]
Same for me on Kubuntu 22.10, godot 4.0.rc2.mono, blender 3.2.2

**Comment by RedMser** [comment]
Once there's better stdin support in Godot, I'll try to switch the code to that. Should be same performance benefit, but less brittle technology stack. Not sure how a localhost connection and server can fail, unless the port is already in use...
