### ISSUE TITLE
Collision avoidance bursts impact agents being far away

### ISSUE THREAD

**Issue by Scony** [godotengine/godot#72772]
### Godot version

4.0 beta (master @ 03.02.2023)

### System information

Linux Manjaro

### Issue description

When adding new navigation agents which collide immediately with existing agents we can observe immediate bursts of RVO2 velocity affecting even the agents being very far from the burst origin:

https://user-images.githubusercontent.com/1207385/216842584-fa1ebf90-989d-42f0-80b7-b07c20928867.mp4

My guess is that for a short while (few frames at most) RVO2 velocities are very large thus impacting further agents.

### Steps to reproduce

Follow the steps presented in the video above.

### Minimal reproduction project

[godot-open-rts-navi-error-v2.zip](https://github.com/godotengine/godot/files/10612057/godot-open-rts-navi-error-v2.zip)

**Comment by smix8** [comment]
Can't say for certain but that agents within distance shuffle a little when one spawns or moves is "normal" because the agents predict velocities for their squared `radius` / `neighbor distance` for the entire `time horizon` period in seconds. They do not know that Godot changes this immediately on the next frame.

Basically what happens is that the agents "predict" a situation in 1 second (cause that is what the default time horizon is) when every agents keeps the current velocity. They all move to positions that will still be valid after 1 second. If not possible to "move aside" they will reduce their own velocity considerably and slow down.

By lowering the time horizon the shuffling goes more or less away and only affects very close agents.

I can also barely reproduce this issue with https://github.com/godotengine/godot/pull/69988.

**Comment by Scony** [comment]
@Chaosus it should be `topic:navigation`

**Comment by smix8** [comment]
Can not reproduce in Godot 4.1 dev3.
@Scony If you are around can you try to reproduce now that the avoidance rework was merged in Godot 4.1 dev3?

**Comment by Scony** [comment]
Still reproducible using `v4.1.dev.custom_build [28cca66d2]`

**Comment by Scony** [comment]
Lowering `time_horizon` fixes the issue. If that would not be possible, then new agents should be added to the scene in a way so that they don't collide from the very beginning.
