### ISSUE TITLE
TextEdit caret line selection raises: Index p_column = N is out of bounds

### ISSUE THREAD

**Issue by andreymal** [godotengine/godot#72797]
### Godot version

4.0.beta17

### System information

Linux

### Issue description

This issue is very similar to #69011 and #69055 but I ran into this error in latest beta.

    scene/gui/text_edit.cpp:4943 - Index p_column = 6 is out of bounds (text[carets[p_caret].selection.selecting_line].length() + 1 = 6).

### Steps to reproduce

1. Open the script editor
2. Select any line
3. Press Tab to indent this line
4. Remove selection
5. Select the line again
6. Press Shift+Tab to unindent
7. Click after the end of the line
8. The error happens

![godot-out-of-bounds](https://user-images.githubusercontent.com/3236464/217017846-90f3a14d-5303-4716-8c6b-8a8482af3b52.gif)

### Minimal reproduction project

not needed

**Comment by andreymal** [comment]
The same error happens when using "Convert Indent to Tabs" instead of indent/unindent (but I'm too lazy to make another gif). I think it always happens when the selected line gets shorter

**Comment by akien-mga** [comment]
CC @Paulb23 @KoBeWi

**Comment by MewPurPur** [comment]
Working on it. There's more to this bug than meets the eye, though I'm not going to open separate bug reports. If someone else wants to work on it, please poke me, I'll keep trying to solve it myself for now

**Comment by MewPurPur** [comment]
I explained what causes the bug and a possible easy patch in the PR above. Though right now, I'm trying to rework the TextEdit selection system.

**Comment by andreymal** [comment]
@akien-mga yes

![Screenshot_20230623_191843](https://github.com/godotengine/godot/assets/3236464/2bc67632-527d-4b75-a31a-8705a561efe6)

**Comment by MewPurPur** [comment]
Yeah, nothing about the underlying problems was solved. Text selection still needs an overhaul and to consistently be updated when text with selections is moved.

**Comment by theraot** [comment]
I found another way this happens:

1. Select text
2. Toggle Comment
3. Deselect
4. Select again
5. Toggle Comment
6. Click at the end

I'm running v4.1.rc1.official [1f9e540f1]

![error](https://github.com/godotengine/godot/assets/1212509/a979c917-a57d-4627-9208-ac6c6efc031f)

**NOTE**: Even though I'm demonstrating at the end of the script, the same happens if I do it anywhere in the middle of the script.

Also, I believe https://github.com/godotengine/godot/issues/74400 is the same issue.

See also: https://github.com/godotengine/godot/issues/69011 and https://github.com/godotengine/godot/issues/67828

**Comment by MewPurPur** [comment]
Yeah, everything that can remove characters to a line while its end is selected would have this issue. Again, the PR above explains it, it's just hard to solve. Me and Paulb seem to have settled down on needing to rework the whole text selection system of TextEdit to rely on less information and to update said information more consistently, since the problem is that when a line is updated, we don't update the "pivot" of the selection. Ideally, the pivot should be a bool saying if it's the beginning or the end of the selection, which would make it impossible that it goes to an invalid position.
