### ISSUE TITLE
Hot-reloading of scripts ("Synchronize Script Changes") doesn't work when using external editor (VSCode)

### ISSUE THREAD

**Issue by retro-git** [godotengine/godot#72825]
### Godot version

4.0.beta17

### System information

MacOS

### Issue description

When the "Synchronize Script Changes" option is selected, scripts should hot-reload when changes are saved. However, this does not work when using Godot 4 with an external editor (only tested on VSCode). It does work when using the in-built text editor, or when using Godot 3.

### Steps to reproduce

1. Configure Godot to use VSCode as an external editor.
2. Enable Synchronize Script Changes.
3. Edit a script file within VSCode while the game is running.

### Minimal reproduction project

N/A

**Comment by rosshadden** [comment]
I don't want to turn this into a "me too!" comment stream, but I will say it's not just VS Code. I have this problem with Neovim as well, so it is very likely simply Godot isn't monitoring for inotify events or whatever equivalents on non-Unix systems.

I'm guessing the integrated editor runs some code on save that initiates the reloading, which would certainly be more efficient than monitoring the filesystem when applicable so it is very understandable. But it would be great if it _did_ monitor the filesystem when users work with external editors.

**Comment by PathogenDavid** [comment]
I did some digging into this and I believe I've found the underlying cause as well as a potential fix.

This code in `ScriptEditor::_update_modified_scripts_for_external_editor` is what's typically responsible for telling the running game that it needs to reload scripts via `_trigger_live_script_reload`:

https://github.com/godotengine/godot/blob/013a45706897af989703b944c7cd5f4f58a6c060/editor/plugins/script_text_editor.cpp#L728-L739

Separately: When an external editor is connected to the language server, it sends a `didSave` event when you save a file, which in turn calls `GDScriptTextDocument::didSave`, which reloads the script using `GDScript::load_source_code`:

https://github.com/godotengine/godot/blob/550a7798510810d238b733a54f69da71b2a2d152/modules/gdscript/language_server/gdscript_text_document.cpp#L104

This in turn causes the script's `last_modified_time` to be updated.

Since the `didSave` callback happens well before `_update_modified_scripts_for_external_editor`, the date check in `ScriptEditor::_update_modified_scripts_for_external_editor` will never succeed as the timestamps will always be the same.

------------

I did not have time to investigate fully, but I suspect this issue was introduced by https://github.com/godotengine/godot/pull/66867 as it introduced reloading the script within `didSave`.

-------------

I found that I can fix the issue by calling `ScriptEditor::_trigger_live_script_reload` from `GDScriptTextDocument::didSave`. See here: https://github.com/PathogenDavid/godot/commit/210edab910a226a1e8a6a9f1cd391a3ee966b76f

(As an added bonus this also fixes https://github.com/godotengine/godot/issues/73808, but only if you're connected to the language server)

However today is the first time I've ever really used Godot, so it's not immediately clear to me whether this is the most appropriate fix. (If it is, would be more than happy to clean things up and make a PR!)

**Comment by OmarShehata** [comment]
Thank you so much for the code snippet here @PathogenDavid . I've been using a custom build of Godot 4 with your patch and it has significantly improved my workflow. It would be great to have a PR for this. Maybe this could even only run if `Use an external editor` is on? If there's any concern on this triggering more than is needed for users who aren't using an external editor?

**Comment by clemens-tolboom** [comment]
> <C++ Source>   modules/gdscript/gdscript_vm.cpp:697 @ call()

In https://github.com/godotengine/godot/issues/75550 we use the build-in GDScript editor which @dakennedyd thinks relates to this issue. Does it?

**Comment by Dexterminator** [comment]
Is there any reason for not making the fix @PathogenDavid made into a PR? https://github.com/PathogenDavid/godot/commit/210edab910a226a1e8a6a9f1cd391a3ee966b76f

**Comment by PathogenDavid** [comment]
@Dexterminator I mainly left my comment to share my findings for someone who wishes to investigate this further and to share my quick and dirty fix (and perhaps learn if someone more involved with Godot's development thought it was good enough as-is.)

Based on the quirk @OmarShehata ran into, I suspect the real fix will need to be more complicated.

A lot has changed for me in the past 6 months and I'm no longer using Godot, so I most likely won't be the one to investigate further.

**Comment by geowarin** [comment]
@PathogenDavid Can you make a PR with the change?
That way people can test it easily and maintainers can discuss the implementation.

**Comment by geowarin** [comment]
@PathogenDavid I think it's a good change.
From what I understand, the LanguageServerProtocol will trigger a didSave request, which will be forwarded to the gdscript_text_document, which will trigger a reload.

You should open a PR so that people may test the change easily and maintainers can get a chance to review the change.

**Comment by PathogenDavid** [comment]
From the Godot contribution guidelines:

> [...] when contributing bug fixes - it's always best to discuss the implementation in the bug report first if you are not 100% about what would be the best fix.

My understanding is this is the appropriate and preferred place to discuss the change. I don't think my fix will be the whole fix--at the very least the issue Omar ran into needs to be addressed.

Additionally, I don't see how making a PR would make it any easier for people to test the change.

**Comment by geowarin** [comment]
A PR is the best way to discuss a code change in the engine.
Many PRs have limitations that can be discussed with the maintainers.

It is the normal review process to checkout a PR and test a change locally. Checking out a commit that is out of tree is more involved.

The issue of the editor requesting focus after a script error is, IMHO a minor inconvenience VS having not reload.

Anyway, if you want to discuss this change with somebody that knows the in and outs of the engine, you have a better chance with a PR than waiting for one of those people to stumble into a code change mentioned in an issue.

**Comment by OmarShehata** [comment]
Just to share my 2 cents here: I think it's clear David is no longer able to commit time/resources to this. His snippet posted above is super valuable for anyone wanting to pick this up, and anyone is free to do and open a PR. It makes that whoever opens a PR will likely also be the one to collect feedback from engine maintainer/test it/update it etc. 

Anyway, since I do have an interest in seeing this fixed, and have been testing it locally with a patched version of the engine, I'd be happy to open a PR sometime next week if no one gets to it before then.

**Comment by eterlan** [comment]
> Just to share my 2 cents here: I think it's clear David is no longer able to commit time/resources to this. His snippet posted above is super valuable for anyone wanting to pick this up, and anyone is free to do so and open a PR. It makes sense that whoever opens a PR will likely also be the one to collect feedback from engine maintainer/test it/update it etc.
> 
> Anyway, since I do have an interest in seeing this fixed, and have been testing it locally with a patched version of the engine, I'd be happy to open a PR sometime next week if no one gets to it before then.

Seems like there is already an pr about this？https://github.com/godotengine/godot/pull/82113#issuecomment-1734326593

**Comment by OmarShehata** [comment]
@eterlan I think that is maybe fixing a slightly different situation? 

I just started re-testing this with the latest version of Godot. Had some trouble initially but turns out it was just the language server not properly connecting. 

The fix described in the patch above still works. The obvious thing needed before merging would be figuring out a proper way to force reload the script (currently the patch just makes a private function public). 

I'm still familiarizing myself with these files, one thing I wanted to try is whether we just need to flip this boolean in the case where an external editor is being used:

```
ScriptEditor::get_singleton()->reload_scripts(true);
``` 

I also wanted to double check what the flow is for updating when you save inside the Godot editor, and if it makes sense to match that when saving with an external editor.

If I can't make progress I'll just open the PR and ask in the engine devs chat for further guidance
