### ISSUE TITLE
Models with skeleton bone maps and parent rotations are not imported correctly

### ISSUE THREAD

**Issue by aaronfranke** [godotengine/godot#72820]
### Godot version

Latest master, 4.0.dev.cd0f1e9b102fe899d37921c1155df08966549363

### System information

macOS 13.1

### Issue description

Models with skeleton bone maps and parent rotations are not imported correctly. I thought this had something to do with the [Apply Node Transforms](https://github.com/godotengine/godot/pull/63662) option, but it's broken even without that enabled.

In the below screenshot, the middle one is the expected behavior (unrotated in model, then I rotated it in the scene), and the other two are nearly the same GLTF file but I added a Quaternion rotation of `[0, 1, 0, 0]` (180 deg around Y) to the root node (named "Armature_deform"). The one on the left side of the image has Apply Node Transforms enabled, and the one on the right side of the image has it disabled. Both have broken shoulders, arms, and feet.

<img width="841" alt="Screenshot 2023-02-06 at 8 55 38 PM" src="https://user-images.githubusercontent.com/1646875/217136931-f96b750e-53d3-449f-990f-8dd41c5ccae8.png">

### Steps to reproduce

1. Download and open the reproduction project.
2. Open `test_model_rot.tscn`.
3. Observe the behavior in the above image.

### Minimal reproduction project

[b_chan.zip](https://github.com/godotengine/godot/files/10671193/b_chan.zip)

**Comment by TokageItLab** [comment]
This is not a bug. If you apply the T-poser [Fix Silhouet](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/retargeting_3d_skeletons.html#fix-silhouette), the asset must be oriented +Z to match the [SkeletonProfile](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/retargeting_3d_skeletons.html#rest-fixer).

**Comment by aaronfranke** [comment]
If the T-poser is not able to handle rotated transforms, then why doesn't it show an error message when it encounters rotation? There is absolutely an actionable improvement that can be made here.

**Comment by TokageItLab** [comment]
It is because in glTF, the specification defines that the model is +Z forward facing.

You can ignore the specification, but it is your fault that it is undetectable. That is really indistinguishable from the case where there is a character with its face behind it.

**Comment by reduz** [comment]
@aaronfranke The import process is correct and the remapper assumes that the model is front facing because this is how artists work in the DCC in the vast majority of cases (This is not really related to glTF, that is just the convention there, but even for other formats Godot just converts the coordinate system so it matches the DCC). To properly handle models looking in other orientations, an option will have to added at some point, but this is beyond the scope of 4.0 at this point and we can discuss it later.

I would also refrain from doing further pull requests and opening issues on this topic. If in doubt, feel free to discuss this topic with me on the chat instead.
