### ISSUE TITLE
Godot 4: Editor freezes when trying to import image assets

### ISSUE THREAD

**Issue by vinrato** [godotengine/godot#72839]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Windows 11, Vulkan, RTX 2060 (31.0.15.2824)

### Issue description

Issue seems to be only occurred when trying to import image files (tested: png, jpg) but not other files (tested: glb, mp3, dae).

When dragging an image assets from the file manager onto godot, a blank window would appear (which looks like it supposed to be the progress bar when importing) and then it freezes while throwing an error:
```
ERROR: Task 'reimport' already exists.
   at: (editor/progress_dialog.cpp:177)
```

![Screenshot (3)](https://user-images.githubusercontent.com/72286622/217278657-bf289ae0-00ae-491b-853f-9861a5065e68.png)

### Steps to reproduce

Just try to import any image into any project.

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
Possible duiplicate of https://github.com/godotengine/godot/issues/72819.

**Comment by saierXP** [comment]
Duplicate of #72632,Single window mode can solve this issue temporarily.

**Comment by hmturnbull** [comment]
I've been having the same problem, and I can confirm that it also happens with .svg files.

![Godot import freeze](https://user-images.githubusercontent.com/52052397/217416432-a8a5fe08-8e84-4857-8bb5-6898118f3346.png)

Additionally, it only happens when dragging the file into Godot's **FileSystem** dialogue.  When I open the directory in Windows Explorer and drag the file there, Godot then imports it as normal.

**Comment by YuriSizov** [comment]
Duplicate of https://github.com/godotengine/godot/issues/53871.
