### ISSUE TITLE
[4.0 beta]  boxCollision tunneling through the hills despite continuous_CD

### ISSUE THREAD

**Issue by dr3muchiy** [godotengine/godot#72889]
### Godot version
tested on 4.0 beta 17

### System information
Windows 10, Nvidia GeForce GTX 1060 (528.02) / Vulkan
linux mint Nvidia GeForce GTX 1060 / Vulkan

### Issue description
Red and blue RigidBody3D raised above the hilly surface by approximately 6 meters
Red RigidBody has a box-shaped collision. 
Blue RigidBody has a spherical collision.
On both RigidBody continuous_cd (continuous collision detection ) turn on.
Hills ground surface has a collision generated by "create trimesh static body" on Mesh Instance.

After launch: 
red RigidBody  tunneling through ground
blue RigidBody remains on the surface after impact with the ground.

if you replace a hilly ground surface with a flat one, both bodies will remain on the surface after falling.

Minimal reproduction project have prefab of a flat_surface for quick replacement of hilly_surface

### Steps to reproduce
run minimal reproduction project

wasd
esc - turn off/on mouse control

### Minimal reproduction project
[boxCollisionTunneling.zip](https://github.com/godotengine/godot/files/10686107/boxCollisionTunneling.zip)

**Comment by rburing** [comment]
I confirm the issue. The problem is that the CCD algorithm does one raycast from a single support point in the motion direction:

https://github.com/godotengine/godot/blob/c4fb119f03477ad9a494ba6cdad211b35a8efcce/servers/physics_3d/godot_body_pair_3d.cpp#L195

This is not enough e.g. in the case where an axis-aligned box under influence of gravity (hence with 4 support points in the motion direction) hits a triangle which is not flat.

Moreover the CCD algorithm tries to make the fast body arrive "just within" the other body:

https://github.com/godotengine/godot/blob/c4fb119f03477ad9a494ba6cdad211b35a8efcce/servers/physics_3d/godot_body_pair_3d.cpp#L216

The problem with this is that trimesh (`ConcavePolygonShape3D`) shapes have no inside, so this offset causes tunneling.

I'll make a PR fixing both of these (at least in the case of this minimal reproduction project).
