### ISSUE TITLE
Project Manager dialogs are wrongly sized based on their dynamically wrapped contents

### ISSUE THREAD

**Issue by fishclaws** [godotengine/godot#72950]
### Godot version

4.0rc1

### System information

Mac Intel

### Issue description

<img width="626" alt="Screen Shot 2023-02-09 at 12 42 55 AM" src="https://user-images.githubusercontent.com/17450241/217761358-968a6308-2ffc-437e-aa5d-a6f0dcf67741.png">

### Steps to reproduce

Try converting a 3.0 -> 4.0 project

### Minimal reproduction project

N/A

**Comment by ievr** [comment]
Also happens on Windows 4.0-RC1
![image](https://user-images.githubusercontent.com/94887743/217826987-d7097619-8139-4757-8a2e-a904c44e2846.png)

**Comment by RandomShaper** [comment]
Is this still reproducible on RC 2? It'd also be interesting to check it on current _master_.

**Comment by akien-mga** [comment]
Testing on Linux with a 1920x1080 monitor and 100% DPI scale:

RC 1:
![image](https://user-images.githubusercontent.com/4701338/220100147-60377895-9ee1-4e54-aee8-e2ce2762d77d.png)

RC 2:
![image](https://user-images.githubusercontent.com/4701338/220100284-de3d433b-fcfc-48b3-878f-35b586e7e8b1.png)

Latest `master` (6f64349bfe42b795a6c50e9c2093d38e7a992e7a):
Same as RC 2.

Not sure why it pops up so tall, the code is:
```cpp
ask_full_convert_dialog->popup_centered(Size2i(600.0 * EDSCALE, 0));
```

But at least the issue of cropped content is likely to be fixed in RC 2. I assume the two reporters here have DPI scaling above 100% (4K Retina, etc.).

**Comment by ievr** [comment]
Windows 10, 4k resolutino, DPI scaling at 200%:
![image](https://user-images.githubusercontent.com/94887743/220104805-52442ac3-2375-4564-b7a1-52fb754e2e8e.png)

If I click and pull on the lower edge of the dialog (note that this persists, if I cancel and retry without quitting the program):
![image](https://user-images.githubusercontent.com/94887743/220104971-a2c29be4-4d88-4599-b5e9-01a38f2f2791.png)

**Comment by akien-mga** [comment]
Last time I worked on this dialog I noticed some issues with centering the first time it's shown: #65806
I don't reproduce it now but it might have had a similar cause as what's causing the sizing mismatch on HiDPI.
