### ISSUE TITLE
`get_tree().pause = true` also pauses RigidBody (2D) physics even with `process_mode = AWAYS` and `disable_mode = KEEP_ACTIVE`

### ISSUE THREAD

**Issue by Misignu** [godotengine/godot#72974]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

EndeavourOS Linux x86_64, Forward+, Intel i5-5200U

### Issue description

The expected result is that the node physics will keep running while the game is paused, but it won't.
![example](https://user-images.githubusercontent.com/28039158/217838061-f33d2fe5-def3-4e30-bebf-081b68faa5a7.gif)

### Steps to reproduce

1. Create a scene with a `RigidBody2D` Node setup
2. Set the properties `Node.process_mode = Node.PROCESS_MODE_ALWAYS` and `CollisionObject2D.disable_mode = CollisionObject2D.DISABLE_MODE_KEEP_ACTIVE`
3. Create a script to pause the game (using `get_tree().pause = true`).

### Minimal reproduction project

[minimal_project.zip](https://github.com/godotengine/godot/files/10697919/test.zip)

**Comment by dalexeev** [comment]
This is intentional. See https://github.com/godotengine/godot-proposals/issues/1835#issuecomment-727204854.

**Comment by EmilyV99** [comment]
...why the fuck would this be intentional? I just spent several hours tearing my hair out trying to debug something, only to find out it's because the engine is working in a completely unintuitive and unexpected way.... only to then search for the problem and find that it's _**INTENTIONAL**_. WTF?

If I pause something, I want that thing to be paused. If I specifically do not pause something, I do not want that to be paused. I see absolutely no sane reason why a non-paused physics object... would be paused?

As it stands, I now am seeing that I either need to completely write my own entire pause code from scratch, or my own entire physics code from scratch, as these systems just blatantly conflict with each other. Why???

I want to run physics for one section of nodes, as part of custom loading code, to make sure things have "settled" before showing a scene to the player. In this situation, I want everything BUT this one scene to be paused- the clearly correct way to do this would be to pause everything, but set this scene to PROCESS_ALWAYS... except that just outright does not work, instead requiring that I not pause everything, but instead, pause, like, everything separately and individually. Why the fuck does pausing work this way?

**Comment by akien-mga** [comment]
@EmilyV99 I understand the frustration that this doesn't work the way you would like it to do, but please stay constructive and follow our [Code of Conduct](https://godotengine.org/code-of-conduct/). Ranting on a 2 years old issue is not constructive.

Now regarding this issue, I haven't re-read all the discussions from 2020 and 2021 around this, but it sounds to me like #49834 was implementing a way to decouple the physics simulation from the Node pause behavior. If it doesn't work, this might be a bug, or might require better documentation.

**Comment by EmilyV99** [comment]
> [@EmilyV99](https://github.com/EmilyV99) I understand the frustration that this doesn't work the way you would like it to do, but please stay constructive and follow our [Code of Conduct](https://godotengine.org/code-of-conduct/). Ranting on a 2 years old issue is not constructive.
> 
> Now regarding this issue, I haven't re-read all the discussions from 2020 and 2021 around this, but it sounds to me like [#49834](https://github.com/godotengine/godot/pull/49834) was implementing a way to decouple the physics simulation from the Node pause behavior. If it doesn't work, this might be a bug, or might require better documentation.

Setting a node to stop processing definitely stops correctly, but, `SceneTree.paused` disables the ENTIRE physics simulation, even for nodes that are `PROCESS_MODE_ALWAYS`, regardless of the setting for `disable_mode`.

Also, that decoupling was older than this issue- and is even mentioned in this issue's title (`disable_mode = KEEP_ACTIVE`) as not helping. From what I see, `SceneTree.paused = true` entirely stops the physics server, meaning NO node whatsoever can ever run separately from that, as the entire physics server is stopped- at least, that's what I'm gathering from trying to read the linked posts, and from replies I've gotten on reddit.

My apologies if the correct thing to do would have been to create a new issue that's an exact duplicate of this one, instead of just commenting on this one, but in my experience generally duplication is best avoided, so I figured simply expressing my opinion here was best. My apologies for the frustrations, just... seeing that something causing so much trouble is supposedly ***intentional*** feels like a huge slap in the face.
