### ISSUE TITLE
Visible notifier3D problem Godot 4 RC

### ISSUE THREAD

**Issue by Captainkittyca2** [godotengine/godot#72981]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 10, Forward+, Intel Iris Xe Graphics

### Issue description

I used 2 signals, one for when entering screen, it makes the node visible, other for exiting screen, it makes the node invisible, both technically work, but when a node becomes invisible after exiting screen, it doesn't become visible when entering screen. i can still interact wih it, it just doesn't become visible.
This doesn't happen in godot 3.4.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/68467449/217887616-9f348594-1e87-476f-a857-fcf5d95bdb03.png)

### Minimal reproduction project

N/A

**Comment by Captainkittyca2** [comment]
actually we talked about it in reddit https://www.reddit.com/r/godot/comments/10xnd62/visible_notifier3d_problem_godot_4_rc/

**Comment by Captainkittyca2** [comment]
here is the sceen with the visiblenotifier btw same hierarchy as how it was in godot 3.4 before i ported it
![image](https://user-images.githubusercontent.com/68467449/217891638-d3aba820-cfdd-4ce3-a2ae-9954663aff0d.png)

**Comment by AThousandShips** [comment]
It isn't a bug, it's a consequence of how the implementation works, why should the notification of *visible* be fired if the node isn't actually *visible*

**Comment by Captainkittyca2** [comment]
> It isn't a bug, it's a consequence of how the implementation works, why should the notification of _visible_ be fired if the node isn't actually _visible_

Are you talking about the if statement? it happens even without the if statements.

**Comment by AThousandShips** [comment]
No I'm talking about the if statement, are you not making the notifier hierarchy not visible, if it isn't visible on screen it isn't *visible*

**Comment by Captainkittyca2** [comment]
> No I'm not talking about the if statement, are you not making the notifier hierarchy not visible, it isn't visible on screen if it isn't _visible_

ah ok, i wasn't sure that's how it worked in godot 4. Thanks!
In godot  3.4, you don't have to worry about that

**Comment by AThousandShips** [comment]
That's what I gathered from the original bug referenced above and in the Reddit thread

**Comment by AThousandShips** [comment]
Also if you consider this to not be a good functionality I'd suggest opening a discussion in [proposals](https://github.com/godotengine/godot-proposals/discussions) as bug reports aren't for making statements, that's what it sounded like given the comment on the Reddit thread

> If you (or anyone else) are not happy with this new behavior please submit a bug report

**Comment by KoBeWi** [comment]
To clarify what is happening, every Node3D/CanvasItem has logic like this:
- is node visible? (`visible` is true, and in case of CanvasItems, `modulate.a` > 0)
- is rect/aabb on screen?
If yes, draw. If not, don't draw.

This code is run for every CanvasItem/Node3D node to cull items that don't need drawing and is very performant. VisibilityNotifier used to run some specific logic, but now it hooks into the drawing code, which makes it more accurate and performant.

**Comment by Captainkittyca2** [comment]
> To clarify what is happening, every Node3D/CanvasItem has logic like this:
> 
> * is node visible? (`visible` is true, and in case of CanvasItems, `modulate.a` > 0)
> * is rect/aabb on screen?
>   If yes, draw. If not, don't draw.
> 
> This code is run for every CanvasItem/Node3D node to cull items that don't need drawing and is very performant. VisibilityNotifier used to run some specific logic, but now it hooks into the drawing code, which makes it more accurate and performant.

every node3d has logic like that without even using visibility notifier node, right?

**Comment by KoBeWi** [comment]
Yes.

**Comment by Captainkittyca2** [comment]
ok thanks

**Comment by HybridEidolon** [comment]
Since this came up on reddit, if you need the ability to turn off the visibility (and thus the culling pass for a canvas item) based on whether it would be visible in the camera or not,

- having VisibilityNotifier perform the same culling checks even when visible=false would mean doubling up culling work in all cases where that node is used. This would clearly be a deficiency in the engine. The new behavior is both consistent and better performing than previous uses of the node.
- trust that 2D culling is doing the job you were previously trying to accomplish (it probably is)
- _If 2d culling is the actual root of your performance issue_ (profile before premature optimization!), and you are not using multiple viewports, you can solve most of the problem by just checking the CanvasItem's distance-squared from the main camera node and switching visible based on that. This will introduce a new design constraint for you: any individual CanvasItem affected by this must not be so large as to have its center point exceed the distance between the visible-boundary and the actual viewport bounds.
- If you have a need for multiple viewports with different cameras, you must rely on culling instead, as you cannot mutate a node between viewport renders.

**Comment by KoBeWi** [comment]
Note that VisibilityNotifier takes arbitrary NodePath to a node, so you can put it anywhere in your tree.
