### ISSUE TITLE
About animationplayer node

### ISSUE THREAD

**Issue by wzc-creat** [godotengine/godot#73017]
### Godot version

3.4.3

### System information

windows10

### Issue description

I have encountered a strange problem many times. When I use the animationplayer node to scale the image, it is like the following.
![image](https://user-images.githubusercontent.com/73389627/217987551-6988289d-ccab-46b7-8610-0f680a22ba15.png)
![image](https://user-images.githubusercontent.com/73389627/217987607-bdda838d-a26b-4177-b51b-37aaa7af4f56.png)
At first, everything is normal, but sometimes, without knowing what it is, the picture suddenly becomes very large, as if it has been magnified more than ten times. Like the following.
![image](https://user-images.githubusercontent.com/73389627/217987873-1e95e01b-f1ef-4c40-8f6e-130896df9d03.png)
This problem is often encountered, but because I don't have a ready-made project file, I can only try to ask if anyone else has the same problem

### Steps to reproduce

none

### Minimal reproduction project

none

**Comment by Zireael07** [comment]
Without a minimal project, there's nothing the team can do.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
