### ISSUE TITLE
Parse error when exporting named enums from scene singletons

### ISSUE THREAD

**Issue by SnowyStoat** [godotengine/godot#73109]
### Godot version

v4.0.rc1.official [8843d9a]

### System information

Windows 10, AMD Ryzen 7

### Issue description

Say, we have an enum in an autoload file called Global:
```
enum TestEnum {
	SOMETHING,
	SOMETHING_ELSE,
	SOME_THIRD_THING,
}
```

In 3.x, you could define an export var in a different file that would use the enum's constants:
`export (Global.TestEnum) var test`

The appropriate syntax in 4.0 would look like this:
`@export var test: Global.TestEnum`

However, when I write it this way, I get an error message:
`Parse Error: Could not parse singleton "Global" from "res://global.tscn".`

At the same time, Godot clearly has no problem parsing this same singleton to simply assign values from TestEnum to other vars: `@export var test2 := Global.TestEnum.SOMETHING` works just fine and doesn't throw an error.

### Steps to reproduce

1. Create a new autoload scene called `Global`, attach a script and paste the TestEnum block
2. Create another scene, add a script, and paste `@export var test: Global.TestEnum`

### Minimal reproduction project

N/A

**Comment by Vennnot** [comment]
Happening in my project as well. 4.0.2 stable

**Comment by PolyBytes** [comment]
Can confirm this is happening in my project v4.0.2.stable.official [7a0977ce2]. It was functioning fine last night but upon booting the editor up today the issue is happening. I made no changes to my code or the editor during this time. The project was left alone until I opened it today and found the error.

**Comment by jitspoe** [comment]
I was able to use enum types from singletons until I changed my singleton from just a .gd file to a whole scene.  Once it was a scene, I started getting this error.

Changing `@export var impact_sound_type : SoundSystem.ImpactSoundType` to `@export var impact_sound_type := SoundSystem.ImpactSoundType.generic` worked around it.

**Comment by dannyking** [comment]
I am having this problem too with a singleton scene (Could not parse singleton)

**Comment by dannyking** [comment]
Until this is fixed, a hack to get around this is that you can make a copy of the enum from the autoloaded class and use that locally to define the type i.e. instead of: 

`@export var test: Global.TestEnum`

You can do:

`var TestEnum = test: Global.TestEnum
@export var test: TestEnum'

This is fragile, but seems like a better tradeoff to me than falling back to an untyped variable depending on your use case.

And then when this issue is fixed you can switch back to `@export var test: Global.TestEnum` easily.
