### ISSUE TITLE
is_move_and_slide_on_wall() and is_move_and_slide_on_ceiling()  Issue

### ISSUE THREAD

**Issue by 0nepixel** [godotengine/godot#7313]
Windows 7- Godot 2.2 alpha 

is_move_and_slide_on_wall() doesn't work at all, always returns false, and is_move_and_slide_on_ceiling() works like if you were using "is_move_and_slide_on_wall()", if you collide with a wall returns true. 

![image](https://cloud.githubusercontent.com/assets/22958303/21270585/07040382-c396-11e6-9988-44169dc39cac.png)

**Comment by bojidar-bg** [comment]
Here is the code that checks the move_and_slide normal:
[`scene/2d/physics_body_2d.cpp:1192-1205`](https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/scene/2d/physics_body_2d.cpp#L1192-L1205)
```cpp
if (get_collision_normal().dot(p_floor_direction) > Math::cos(Math::deg2rad((float)45))) { //floor

	move_and_slide_on_floor = true;
	move_and_slide_floor_velocity = get_collider_velocity();

	if (get_travel().length() < 1 && ABS((lv.x - move_and_slide_floor_velocity.x)) < p_slope_stop_min_velocity) {
		revert_motion();
		return Vector2();
	}
} else if (get_collision_normal().dot(p_floor_direction) < Math::cos(Math::deg2rad((float)45))) { //ceiling
	move_and_slide_on_ceiling = true;
} else {
	move_and_slide_on_wall = true;
}
```

Thus, `move_and_slide_on_wall` would be `true` only if the dot product of the collision normal and the floor direction is exactly equal to `cos(45⁰)`. Obviously something fishy here.

@reduz Since you introduced this code in fc70824f7c6ab1944d54194f54b816e55671e177, can you elaborate on this issue? :smiley:

**Comment by nunodonato** [comment]
@0nepixel can you share that scene?

**Comment by bojidar-bg** [comment]
@nunodonato Here it goes: [7313-is-on-celling-false.zip](https://github.com/godotengine/godot/files/893021/7313-is-on-celling-false.zip) (yea, I know I'm not called 0nepixel...)
