### ISSUE TITLE
'Create Version Control Metadata' Dialog doesn't use editor theme

### ISSUE THREAD

**Issue by devlein** [godotengine/godot#73154]
### Godot version

v4.0.rc1.official [8843d9ad3]

### System information

Windows 11

### Issue description

The 'Create Version Control Metadata' Dialog doesn't use the editor theme:

![grafik](https://user-images.githubusercontent.com/104411913/218311985-9d3830da-0394-4f53-a2d6-9f15bcffdced.png)

Even worse, if a default project theme is set, it is used:

![grafik](https://user-images.githubusercontent.com/104411913/218312022-dc7ee6d1-4e68-4cb0-9926-88c5efc7ba2f.png)

### Steps to reproduce

Open:
Project > Version control > Create Version Control Metadata

### Minimal reproduction project

Not needed

**Comment by YuriSizov** [comment]
It's probably added to the root of the editor tree, instead of the root of the editor GUI.

**Comment by BigZaphod** [comment]
I just ran into this by accident, too. Was going to file a bug, but saw this and figured it's probably the same issue?

Not only does the theme feel wrong, the window itself was super tiny on my mac (maybe due to the retina display?) - it's like a dialog box for ants!

<img width="2078" alt="Screenshot 2023-03-12 at 11 24 33 AM" src="https://user-images.githubusercontent.com/453721/224558107-b33af1d4-c32d-4f59-881c-20a28aed9aac.png">

Version: v4.0.stable.official [92bee43ad]

**Comment by KoBeWi** [comment]
This is fixed in 4.2 (the dialog is added to correct parent).
