### ISSUE TITLE
A boot splash in JPG format doesn't work anymore.

### ISSUE THREAD

**Issue by Rocket-Buddha** [godotengine/godot#7327]
**Operating system or device - Godot version:**

- Fedora: Fedora release 25 (Twenty Five)
- Kernel: Linux localhost.localdomain 4.8.13-300.fc25.x86_64 #1 SMP Fri Dec 9 14:52:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Gogot: v2.1.1.stable.official

**Issue description** (what happened, and what was expected):

- What happened: A boot splash in JPG format doesn't work anymore.
- What was expected: A boot splash in JPG format should work.

**Steps to reproduce:**

   1. Set up a JPG boot splash.
   2. Play the project.

**Comment by RebelliousX** [comment]
Does it work in PNG/BMP format or is specific to JPG?

**Comment by Rocket-Buddha** [comment]
It works in PNG, I didn't try in BMP.

**Comment by insomniacUNDERSCORElemon** [comment]
Why would you be using JPG in any other circumstance than:

1. You WANT grain/color noise (like for horror/dystopian games)
2. Your image contains many colors that would bloat a PNG (like a rendering or photograph of a complex scene)

If you want a simple splash menu (like with a game/company logo, text etc.) JPG is going to have visible artifacts on it especially if it isn't a super high resolution. JPGs don't do large flat areas of color, crisp edges, or gradients very well.

PNG images can also be further losslessly compressed than your image editor probably exports, for instance I use a program called Trimage (uses optipng, pngcrush, and advpng as well as removes EXIF data). You can also further reduce size if you reduce the amount of colors beforehand, for instance finding colors that are nearly the same and combining them (especially if they aren't touching each other) and/or reducing the resolution of the image.

Unfortunately there aren't great ways to reduce colors in PNGs aside from directly indexing to 256 colors or using thresholds+layer blend modes+selections in order to manually reduce values/colors without sacrificing detail. You might be able to use a GIMP plugin called cartoonizer but it it really depends on how cluttered/non-crisp your photo is and how much color you need for the end result.

SVG might fix it when it comes to issues with gradients (convert your PNG into an SVG... assuming ), and that's added to milestone 3.0 (issue #4826).

**Comment by RebelliousX** [comment]
@insomniacUNDERSCORElemon true, but if this issue is true, nonetheless it must be fixed, because it is a bug.

**Comment by Rocket-Buddha** [comment]
Thanks for the theory but I'm not judging the advantages of one format over another. The FACT is that the editor let me select a JPG image like a splash screen. If the JPG format is not allowed for splash screen this is a bug and must be fixed, equally if it is allowed and doesn't work.

**Comment by akien-mga** [comment]
> A boot splash in JPG format doesn't work anymore.

Could you explicit the "anymore" part? Did it use to work, and if so in what version?

**Comment by Rocket-Buddha** [comment]
It worked on Gogot: v2.1.stable.official

**Comment by volzhs** [comment]
I downloaded and tested official Godot 1.1 / 2.0 / 2.1 / 2.1.1 / 2.1.2.
and 2.1.3 / 3.0 alpha custom build.

File filter for boot splash screen have only `*.png` and `*.*`
JPG file can be selected with `*.*` filter.
but I think JPG have not been officially supported for boot splash, even if it worked or not.

**Comment by mhilbrunner** [comment]
This can be closed.

**Comment by akien-mga** [comment]
> This can be closed.

Can you explain why? :)

**Comment by mhilbrunner** [comment]
From the issue description:
> What happened: A boot splash in JPG format doesn't work anymore.
> What was expected: A boot splash in JPG format should work.

The first is false, it never worked, reading volzhs above.
The second is probably also false, since there is no particular reason JPG support should be added for boot splashes. PNG is fine. I mean, the engine only supports PNG everywhere?

So I think this can be closed? The issue could be summarized as "the engine allows you to use any file as boot splash with *.* filter, even JPG files (or .exes, I guess), which don't work as PNG". Thats.. true, but not an issue.

**Comment by akien-mga** [comment]
Thanks :)

**Comment by Rocket-Buddha** [comment]
I used to use a JPG format in one of my projects. Why should I use a heavier format for a splash screen? I can't test it right now but I will...

**Comment by Calinou** [comment]
> Why should I use a heavier format for a splash screen?

JPEGs are not renowned for their compression quality, it's a much better idea to use a PNG instead. You can optimize PNG images using [oxipng](https://github.com/shssoichiro/oxipng).

**Comment by akien-mga** [comment]
Well if it works, I don't see any reason to prohibit it. Users can pick what works for them in all awareness. If their splash screen looks bad, it's not the engine's business :)

**Comment by mhilbrunner** [comment]
Yeah, but the point was that it *doesn't* work, in which case.. well, just use a PNG? There is no reason to support JPG for textures.

**Comment by Calinou** [comment]
> There is no reason to support JPG for textures.

JPEGs works for textures in Godot games, but not as a splash screen.

**Comment by akien-mga** [comment]
Indeed:
![spectacle lh2511](https://user-images.githubusercontent.com/4701338/33839353-45850de6-de92-11e7-8a3a-b00c2207f14f.png)

The reason why it's not supported is that the splash code comes from the initial initialization of the engine, where JPG support (`modules/jpg`) is not registered yet in the engine. While PNG support is a core component a.k.a. "driver" (`drivers/png`).

And yes, incidentally, using JPG as a splash screen is not a good idea as it's lossy -- unless you want to use a photo as splash screen, in which case it's debatable.

**Comment by Rocket-Buddha** [comment]
Only for records, 2.1 allowed me to use jpeg and it works, al least in the editor. But it doesn't care, the issue was originated by an artist that used to sent me many files in jpeg, "to save space".

[testPNG.zip](https://github.com/godotengine/godot/files/1550150/testPNG.zip)

**Comment by unfa** [comment]
I think I have the same issue but with Webp in Godot 4.1.1:

![image](https://github.com/godotengine/godot/assets/491704/53afa8ed-d616-459c-a416-809bdcc92293)

```
E 0:00:00:0222   setup2: Non-existing or invalid boot splash at 'res://icon.webp'. Loading default splash.
  <C++ Source>   main/main.cpp:2356 @ setup2()
```

**Comment by YuriSizov** [comment]
@unfa It's the same reason too. WebP is a module and is only initialized after the boot splash is checked. The setting is actually hinted with `"*.png"`, so no other type is suggested as supported.

**Comment by unfa** [comment]
But the file dialog in Project settings accepts all three formats! If WebP won't work, that's fine, but the file dialog suggests to me that it's expected to work :)

**Comment by KoBeWi** [comment]
Where does it accept WebP?
![image](https://github.com/godotengine/godot/assets/2223172/46ff8c1d-3b93-4704-99c5-2ef45d10ec18)
You need to select All Files, which allow you to select literally anything, so it's irrelevant.

**Comment by unfa** [comment]
Oh! You are right - it doesn't! I must've blindly copied the path from project icon and thought I saw the file dialog for the Splashscreen, but that was for the icon!


Sorry - my bad.
