### ISSUE TITLE
LightmapGI: Lightmap static lights are still counted in real-time light calculations

### ISSUE THREAD

**Issue by jcostello** [godotengine/godot#73289]
### Godot version

v4.0.beta17.official [c40020513]

### System information

Ubuntu with Nvidia 2060

### Issue description

Lights statically baked are still count into light calculation. Shouldn't be disabled by default? Dinamic or not baked objects should be lighted by lightmaps probes (not working yet)

static light enabled
![image](https://user-images.githubusercontent.com/1168582/218774353-c1064b46-459e-4b3b-9095-1391d864e3d4.png)

static light disabled (Notice the FPS increase when disable it)
![image](https://user-images.githubusercontent.com/1168582/218774527-958af1ac-d192-4484-8907-13b1171b6365.png)

### Steps to reproduce

Bake a scene with static light enabled
Disabled light
See diference in FPS

### Minimal reproduction project

No needed

**Comment by Calinou** [comment]
Dynamic objects are still lit, so a performance impact is expected for static lights.

**Comment by Calinou** [comment]
I have a proof of concept: https://github.com/Calinou/godot/tree/light3d-add-static-baked-mode

**Testing project:** [test_light3d_baked_static_mode.zip](https://github.com/godotengine/godot/files/12744731/test_light3d_baked_static_mode.zip)

It has some issues:

- It crashes when you use **Scene > Reload Saved Scene** due to the culling code having some "uneven" cases with lights sometimes being paired, sometimes not.
- Lightmap probes don't take direct light into account for these Static Baked lights yet.

However, I was able to get a successful bake with lightmaps having the Static Baked lights present, yet dynamic objects not being lit by these lights at all.

Light3D bake modes from left to right: Disabled, Static, Dynamic, Static Baked. The white box is a static (baked) object, while the cyan torus is a dynamic object.

![image](https://github.com/godotengine/godot/assets/180032/04650a11-73aa-42ae-9e70-cc79184a66b8)

**Comment by jcostello** [comment]
In the future we have to come with a better name like: Dynamic, Mix / Movable (old static), Static

**Comment by jcostello** [comment]
> I'd appreciate help on this area as I'm not sure how to modify the lightmap probe baking code to get it to bake direct light for lights that use the Static Baked bake mode (and only those lights).

It will be better to wait for https://github.com/godotengine/godot/pull/82068 to be merged first. Then maybe @DarioSamo can help you

**Comment by Calinou** [comment]
> In the future we have to come with a better name like: Dynamic, Mix / Movable (old static), Static

Lights with Static bake mode that are moved or have their color/energy changed will not affect baked surfaces, so I think that bake mode should remain Static in the UI. I would only add a distinction when it comes to lighting of dynamic objects by the static light.
