### ISSUE TITLE
Implement alternate camera projection(s)

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godotengine/godot#7340]
Panini projection will not only offer lower distortion than rectilinear projection, but also allow for a much higher usable FoV (that has more gradual distortion) as seen in comparisons:

![rectilinear vs panini projection](https://raw.githubusercontent.com/shaunlebron/blinky/master/readme-img/old-and-new.jpg)
https://youtu.be/jQOJ3yCK8pI?t=24s

It will eliminate distortion at the edges of the screen and should have no distortion at 90 FoV.

Code with MIT license: https://github.com/shaunlebron/blinky

I think the lowest possible distortion (maybe differing per FoV) should be the default projection type. Rectilinear should likely only be used at an extremely low FoV (eg 60). Although everyone has different preferences (for instance I don't want edge distortion OR queasiness, although I just want something near 90 FoV) so this is obviously something that users (of games) should be able to configure when they set the FoV itself in the options screen.

I'm not sure of the best projection setup, considering there are many different options+optimizations and I can't personally test them myself at this time. Although I have played games where edge distortion doesn't seem to be an issue, one is Sauerbraten 2 where I know they're not using Rectilinear at least.

**Comment by insomniacUNDERSCORElemon** [comment]
Can this get the 'junior job' label added? Should be normal cameras stitched into one camera, so not nothing 'internal' rendering wise.

**Comment by reduz** [comment]
Is this not a post process (distortion) at the very end of the line?
in any case, kicking to 3.1

**Comment by insomniacUNDERSCORElemon** [comment]
Yeah, it _is_ a post process. See my edit above. Basically it takes the typical rectilinear view and distorts it.

This could likely be done by a user easily in 2.X, though there are fuzzy parts:

- the quality of the sphere (making sure it's high-res enough where the edges don't cause a jarring transition)
- the FoV... for proper optimization, the game world camera and projection-seeing camera would need a linked FoV
- to support a smaller FoV from the game world camera, the projection on the sphere would need to be at size (as in a smaller projection should be projected smaller rather than stretched) **OR** maybe I'm wrong on that and it'd need to be the same projection size on the sphere with the projection-seeing-camera staying at a fixed FoV (**or** smaller FoV but further away from the inside of the sphere to result in the same coverage but different view angle... but I doubt this one)
- doing this dynamically... doing it now would require manually setting up a rig each time (or maybe hooking it up from an instanced scene).

I don't know anything about GDscript (AFAICT the only way to do a camera projection, and IIRC the docs didn't help much) to know if these issues are easily solvable, but I assume that doing the projection internally will yield cleaner results.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1 : not implemented yet

**Comment by insomniacUNDERSCORElemon** [comment]
@Noshyaar, not sure if you're interested or just doing book-keeping... but as I've said above a prototype for this should be quite easy to do for anyone who knows how to do camera projections.

A prototype might not be enough for a pull-request (though it might be usable in games for those who manually add it), but as I've said before some other person might be able to internalize it. Plus it'd be good so users can compare distortion and how it 'feels'.

It also might take some tinkering to get the most accurate/distortion-free projection(s). Or just to find the right setup. However I'm sure someone could implement multiple projection types user-side and it'd be minimal work implementing them internally in one go. Stitching multiple cameras together for less distortion _is_ a thing though, so that'd be the more complex thing (and an area devs might not be enthused about because of increased rendering load).

Also correction from my previous comment: a panini projection (if I understand it correctly) would be a cylinder rather than a half-sphere as I described (I'm not sure if that is a thing or even what the distortion would look like particularly at ~90 FoV... maybe fish-eye, but I think that'd only apply at 180+ FoV).

**Comment by eiszfuchs** [comment]
[I have been working on an equirectangular projection shader](https://imgur.com/a/Fd6rV3s) yesterday. Since Godot now properly passes ViewportTextures to Shaders, and once you have a cubemap from viewports to work with, this is fairly easy to implement (and basically works as a foundation for [every other projection](https://en.wikipedia.org/wiki/List_of_map_projections), I guess).

However, it creates some visual artefacts when using bloom and, well, shadows.

![vlcsnap-2020-01-12-11h09m40s294](https://user-images.githubusercontent.com/240167/72217368-0e6c4b00-352d-11ea-9651-5eacc8015f2a.png)

This is to be expected, since that's how these "effects" work.

![vlcsnap-2020-01-12-11h09m31s086](https://user-images.githubusercontent.com/240167/72217373-0f9d7800-352d-11ea-9480-9dab00fb1a3c.png)

As a proof of concept, this kind of works, and with a few hacky workarounds, I can use this scene as a drop-in replacement for every other camera I've been using in my game (once I've fixed all the bugs with it). It doesn't slow down the game too much, however, the artefacts are something I'd want to fix as well, before I would even consider using that technique to achieve nice fisheye effects.

Now, this was implemented using shaders and viewports, since I don't know where to start implementing that in the actual game engine, but it suppose the same artefacts would occur when trying to get this projection to work with "built-in" engine code.

**Comment by Cykyrios** [comment]
I've given this a try as well as I was needing a fisheye camera for my game. After I got the fisheye working, I decided to add some more projections as well, you can find the repo [here](https://github.com/Cykyrios/Godot360). For reference, here is the Sponza demo in fisheye view: ![](https://raw.githubusercontent.com/Cykyrios/Godot360/master/Images/Fisheye.png)

Now, as pointed out by @eiszfuchs, there are artefacts when screen space effects are close to the edges between two cameras, and image quality goes down in heavily distorted regions. I haven't tried that, but maybe it would be possible to render more per camera, say 100°, and only work with the "useful" 90° to compensate. I suppose the resolution of each individual camera could be adjusted depending on the FoV and the projection used to limit the additional rendering cost.

For reasonable fields of view that stay below 180°, it is worth pointing out that 3 cameras are enough if you look at the corner between the 3 cameras, although that means you're looking right at a region of the screen where artefacts are likely to appear. If anything can be done to make those artefacts less visible, I would be interested to know about it.

Also worth noting is that on a 16:9 screen, you could technically render a 150° FoV panini projection using only 3 cameras instead of 5, as the top and bottom ones are not visible.

**Comment by insomniacUNDERSCORElemon** [comment]
Thank you @Cykyrios that's interesting. Although testing could be better (like having objects at different ranges, vertical camera rotation/player movement, maybe some basic textures or rotating objects, changing projection methods/toggling grid in-game etc). Some things seem off (like a 360 view gives black rectangles on the sides and seems to have a blind spot and thus not fully 360), although I'm not sure on everything (like some of the projections seem to have set distortion and just scroll the image).

Also for around 150 FoV and under it seems like you could save pixels by going with tall aspect side cameras (matching the height of the middle one) and having the width only go out as far as needed (at least as math permits, but you could at least try just half of what you use now in some cases). I could also see the lacking top/bottom portion useful in any sort of game where that could be obscured with a GUI or extra mesh (via a viewport below, or above if it has a transparent background), particularly games with mechs/planes/spaceships (the blank section skinned as controls or other internal part of the vehicle).

The 3-camera setting on projections seems like it's too similar for each projection (like I wouldn't expect 3 warped areas for a cylinder projection), but then again I don't know enough about projections to be certain.

--------------------

Not sure if you've tried actual projection or not (like Blinky where you have a camera viewing the projection), but it might allow for higher quality (if you make the 1st cameras higher res and the viewer camera native) with screen-space shaders applied to the native camera.

**Comment by Cykyrios** [comment]
I must admit that I didn't iron out any obvious issues such as the black parts (or entire screen going black at 360° FoV) and just wanted the proof of concept out. I do agree there's a blind spot at the back, I suspect this is due to the automatic scaling/zoom to prevent seeing "outside" the projection, but is maybe too conservative. In this regard, I am not convinced the displayed FoV is the requested one either - 180° looks more like 160-170 if you look at the grid lines (one line every 10° plus the center lines).

Cylindrical, Equirectangular and Mercator look pretty similar, and the panning/scrolling effect is actually just an interesting side effect of these projections.
Also, setting the number of cameras lower than 5 is not properly implemented at this time.

I think that based on what I managed to do here, it would be interesting to see what would be required to do in order to make non-standard projections work with minimal impact on rendering time and visual quality, and whether some of those improvements are possible on the user's side or require changes on the engine side.

**Comment by insomniacUNDERSCORElemon** [comment]
@Cykyrios I've just dropped your camera into a first-person test project that someone made and it seems currently the best setting is 3-camera rectilinear at 120 FoV, which seems like it could be a sane default (there is still stretching at the left/right edges of the screen, but overall not too bad and allows for wider FoV). 

Others feel too much like a funhouse mirror, but panini at 150 FoV should work for any game that doesn't allow up/down camera rotation (1st-person dungeon crawlers with grid-based motion as a prime example, like Legend of Grimrock).

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
