### ISSUE TITLE
Custom .svg icons blurry in some places inside the editor

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#73491]
### Godot version

4.0-rc2

### System information

Windows 10, 4K monitor

### Issue description

Custom .svg icons occur blurry in certain parts of the editor on higher resolution monitors (e.g. 4K) and 200% editor scaling and **Scale With Editor Scale** turned on. Note, that this only affects custom icons and native editor icons seem to be fine in the MRP.

Given a node defines something like this:
```
@icon("tree.svg")
class_name CustomNode extends Node2D

@export var node:Node2D
```
it will occur like this in the editor:

![219475155-758bafde-ad52-4821-8d83-0ac910c0b680](https://user-images.githubusercontent.com/822035/219610336-23f69474-d921-4efd-a39c-1e2f54aa7fdf.PNG)

All the red circles are places where the icon seems to be blurry and does not scale correctly with the editor. Only the green circle shows the correct version of the icon.

### Steps to reproduce

1. open MRP on a 4K monitor
2. set editor scaling to 200%

### Minimal reproduction project

[blurry-icons.zip](https://github.com/godotengine/godot/files/10765347/blurry-icons.zip)

**Comment by bitbrain** [comment]
I cannot help but also find that the blurred versions look a bit... squashed?

Blurry version:
![1](https://user-images.githubusercontent.com/822035/219615190-1f0f5bf3-d9db-4f50-beb1-67ab592191ac.PNG)
Sharp version:
![2](https://user-images.githubusercontent.com/822035/219615194-5b93877d-096d-4092-ae77-fbe610001c84.PNG)

**Comment by coppolaemilio** [comment]
I think there are a couple factors making it blurry. The source svg according to figma is: 16.88 x 15.06. Making a "frame" with it being 16 x 16 might result in less blurriness because it doesn't have to make those decimal calculations when rasterizing. 
There's also the size of the source image. I usually get better results (might be psychological, haven't compared) when I make a bigger image, so instead of going for a 16x16 I try to use 32x32 or 64x64 on the svg file.
I tried making your icon on a 32x32 frame
![image](https://user-images.githubusercontent.com/2206700/219649830-414e521b-0606-4942-946d-5721a3e766ed.png)

And got better results in editor:

![image](https://user-images.githubusercontent.com/2206700/219649602-4878794b-d643-4af0-ba17-1f716d6ab41e.png)

Hope that helps!

**Comment by DricomDragon** [comment]
Icon displayed on the left of "BehaveTree" seems to be a bit oversized. May be related to https://github.com/godotengine/godot/issues/75845 ?

**Comment by coppolaemilio** [comment]
This was fixed recently with: https://github.com/godotengine/godot/pull/75472

**Comment by Zylann** [comment]
I found it's not just custom icons
![image](https://github.com/godotengine/godot/assets/1311555/5c63aae5-bca3-41fc-b448-d2252bb558e9)
