### ISSUE TITLE
Vulkan: Steam Overlay not rendered

### ISSUE THREAD

**Issue by Defaultsound** [godotengine/godot#73532]
### Godot version

Godot_v4.0-rc2

### System information

Vulkan 

### Issue description

The Steam Overlay does not show (Shift + Tab) in Godot 4 when Forward+ renderer is enabled. It does work when the compatability renderer is used, hence this is an issue with the Vulkan renderer. 

This issue was brought up in the GodotSteam issues [#305](https://github.com/Gramps/GodotSteam/issues/305) and [#237](https://github.com/Gramps/GodotSteam/issues/237) However this is not the fault of GodotSteam, and suggests that it is an issue with Godot 4's Vulkan renderer. 

It seems something is overriding the overlay from being rendered. It seems there was an issue with Vulkan and Steam back in 2018 [145](https://github.com/flathub/com.valvesoftware.Steam/issues/145) but this has since been fixed according to that issue.

My concern with this issue being unresolved before Godot 4's release will mean any games released on Steam in Godot 4 using the forward renderer will not fully work with Steam. Personally, I would like to use the forward renderer in the current game I am working on. The goal is to launch on Steam and have Steam work with the game.

### Steps to reproduce

Run reproduction project:

Example code:

```
extends Node3D

func _ready():
	var steam = Steam.new()
	var INIT = steam.steamInit(true)
	steam.restartAppIfNecessary(480)
	if steam.isSteamRunning():
		print(steam)
		print(INIT)
		steam.activateGameOverlay("Friends")
		print(steam.isOverlayEnabled())
	pass
```

Press Shift + Tab

Overlay doesn't show

Change rendering mode to Compatability.

Restart and test and overlay will show. Hence it does work with OpenGL. (But not a workaround for me personally as I would like to use new rendering features from Forward+)

### Minimal reproduction project

The reproduction project contains the latest GodotSteam GDExtension binaries compiled for Godot_v4.0-rc2.

Make sure Steam is installed and running.

In the project hit run and press Shift + Tab. No Overlay will show.

[GodotSteamOverlayBug.zip](https://github.com/godotengine/godot/files/10772321/GodotSteamOverlayBug.zip)

**Comment by Calinou** [comment]
Which operating system are you using?

**Comment by Defaultsound** [comment]
Windows 10, Nvidia RTX 3080.

Well the overlay does indeed work when running the project in editor. I did test and export the project as well but same result, no overlay.

**Comment by clayjohn** [comment]
This is not a Godot issue. Both issues you linked were closed without any investigation, instead the maintainer shrugged and said "it's Godot's problem"

Looking at the [Steamworks documentation ](https://partner.steamgames.com/doc/features/overlay)they say:

> Your game does not need to do anything special for the overlay to work, it automatically hooks into any game launched from Steam! While in development and running your game in a debugger, the overlay is loaded when you call [SteamAPI_Init](https://partner.steamgames.com/doc/api/steam_api#SteamAPI_Init). As such you'll need to make sure to call [SteamAPI_Init](https://partner.steamgames.com/doc/api/steam_api#SteamAPI_Init) prior to initializing the OpenGL/D3D device, otherwise it won't be able to hook the device creation.

Taking a quick look at the module its clear they don't register the module prior to initializing the OpenGL/Vulkan device. They need to follow the [example in the docs](https://docs.godotengine.org/en/latest/contributing/development/core_and_modules/custom_modules_in_cpp.html) and ensure that they initialize the module in ``MODULE_INITIALIZATION_LEVEL_SERVERS`` or earlier.

To be clear, we are not responsible for 3rd party modules. You use them at your own risk. Please do not come here for support for code written and maintained by others.

**Comment by Defaultsound** [comment]
Understood. I was at the whim of not knowing where to go for support on this issue as you can tell it's not easy to know where to begin. I will raise it back there.

**Comment by Gramps** [comment]
Hey @clayjohn, I do maintain the GodotSteam project.  The overlay will work, albeit sluggishly, on with Compatibility but not Forward+.  It works perfectly fine as is on Godot 3.x which is using OpenGL.  So, odd man out, it doesn't seem to work with Godot's Vulkan implementation.  I have looked at the example in Godot's documentation when porting the project from 3.x to 4.x so unless I'm missing something major, I'm not sure what would really need changed.  Especially if it does, as mentioned earlier, work with Compatibility but not Forward+.

**Comment by clayjohn** [comment]
@Gramps You register your module during the ``MODULE_INITIALIZATION_LEVEL_SCENE`` step in engine initialization. The docs explain how to initialize the module earlier. In your case you likely need to initialize the module during the ``MODULE_INITIALIZATION_LEVEL_SERVERS`` so that it is initialized before the Vulkan device is initialized. Currently you are initializing _after_ the Vulkan device is initialized. The Steamworks docs say you need to initialize the module _before_ the Vulkan device is initialized otherwise it won't work. So you need to move the initialization to be before the Vulkan device is initialized (i.e. ``MODULE_INITIALIZATION_LEVEL_SERVERS`` should work). Its the same initialization level for both modules and GDExtensions, so both will have to be updated if you are using both.

**Comment by Gramps** [comment]
Hey @clayjohn!  Thanks for clarifying this as the documentation is a little confusing and seems to use some 3.x text.  Digging into the actual module types, I found these other module initialization levels but the documentation seems to go in a totally different direction that doesn't work at all.

I tried with both MODULE_INITIALIZATION_LEVEL_SERVERS and MODULE_INITIALIZATION_LEVEL_CORE but it will not render overlay with Forward+.  It does however still work with Compatibility and with RC 2, the overlay is finally smooth as butter.

**Comment by Gramps** [comment]
@Calinou You are correct.  Overlay never triggers in the editor or project manager as it won't be available until Steam is initialized by calling SteamAPI_init, or in our case steamInit().

Also for clarification, I'm on Windows 11 and using a 3070.

**Comment by Gramps** [comment]
@clayjohn One more update, I created a blank Godot 4 project with Forward+ as the renderer and just a text label.  I then exported it, added it to Steam as a non-Steam game, and overlay functioned no problem.  I swapped it with my game to run as a Steam application and it also worked with overlay.  I created a similarly blank project in Godot 3.x with GodotSteam but did not call the Steam initialization function; added it to Steam in both ways and overlay still came on.  So calling the Steam API initialization doesn't actually seem to matter at all.

On the plus side, this at least confirms to me that Forward+ is fine with overlay.  On the flip side, considering moving the module higher in the initialization process doesn't work... I'm at a loss to get it working with Forward+.  Again, it works as expected with Compatibility so I'm not sure where to go from here.

Any additional advice or feedback would be helpful!

**Comment by Defaultsound** [comment]
To rule out GodotSteam I tried a C# Library Steam implementation in Godot Mono and the same issue occurs, does not work in Forward+ but does in Compatability. So I don't believe it is the implementation of Steam. Something isn't hooking to the process. Again I can't say what exactly.

**Comment by Gramps** [comment]
Is it possible that it can't attach/inject overlay into Godot's Forward+ for some reason when run outside the Steam client?  Since when run from the Steam client, it can attach/inject overlay games and apps not even using Steamworks.

**Comment by Gramps** [comment]
Attempting rolling back drivers to the version the one user had didn't seem to make any difference.

**Comment by follower** [comment]
Drive by comment (based on my brief research indicating that the Steam overlay is implemented via Vulkan layer) in case it's helpful:

 * Are you aware of these "recent" Vulkan layer-related changes/issues:
    *  "Force disable Vulkan overlays in the editor and project manager": https://github.com/godotengine/godot/commit/12817543a9e55b132da252a55f08ab11f9a02724
    *  Related issue: https://github.com/godotengine/godot/issues/57403
    * " Vulkan: Initialize VK_EXT_debug_utils only for dev build or verbose mode ": https://github.com/godotengine/godot/commit/8a47cdc93363865cb7da5dad34f328a3fc948489
 * Have you tried using any of the Vulkan SDK layer-related debugging tools (via [sdk](https://vulkan.lunarg.com/sdk/home) & [docs](https://vulkan.lunarg.com/doc/sdk/1.3.239.0/windows/getting_started.html)) and/or something like Renderdoc to get more insight into what's happening in the success/failure cases?
 * Are there differences between the environment variable configurations in success/failure cases?

**Comment by Gramps** [comment]
Hey @follower!  If this comment is for me, then my answer to number 1 is no, I don't follow Godot's development due to time constraints.  I generally only work with the stable builds but we started making 4.x versions due to community request and overlay has never been a problem before.  The overly definitely shouldn't work in the editor itself until the project is run and then only in that run project.  I will look at these links more closely this weekend after my deadline passes.

I've not used any of the debugging tools you mentioned; it has been discussed in our community but, again, I won't have more time until this coming weekend.

I don't think there are any environment variable configuration differences between success and failure cases but there have been no successes unless the game is run from the Steam client itself.  The one person who had success running from editor was just using our Godot 4 alpha 11 pre-compiled version; though I'm just basing this off their word it worked with no hard evidence.

Thanks for the information though, I plan on digging further into it this weekend once my project is finished.

**Comment by Defaultsound** [comment]
@follower Thanks for this information. Is there a way to parse these args into the process run by the editor?
```
OS.unset_environment("DISABLE_VKBASALT")
OS.unset_environment("DISABLE_RTSS_LAYER")
OS.unset_environment("DISABLE_MANGOHUD")
```

I tried this, but didn't work on start. 

Can ```editor/run/main_run_args``` be used to unset these variables to test this?

**Comment by akien-mga** [comment]
There's no reason these variables would impact the Steam overlay, it's unrelated to VkBasalt, RTSS and MangoHud, which are all thirdparty overlays. And they're only disabled in the editor.

**Comment by Gramps** [comment]
I will remove those from my research, thanks!

**Comment by miketgv** [comment]
Hello,
I have a custom build with mono for Godot 4.0 stable + GodotSteam 4.2 and same behavior can be seen on my side(steam overlay not starting).
But if you minimize the debug window and maximize it again, the overlay starts to work as expected,...
I can see the same behavior using Facepunch.Steamworks.
I use an AMD Ryzen 9 5900HX laptop with AMD Radeon 6800M GPU (Advantage edition) on Windows 10, you can see the behavior in the video bellow.
https://www.youtube.com/watch?v=En5_vgJB9PM

The issue is persistent in the official version of godot with Facepunch.Steamworks...

Palying more with the Facepunch.Steamworks I've got this error after a minimize->maximize :
E 0:00:11:0077 _update_swap_chain: Condition "err" is true. Returning: ERR_CANT_CREATE
<C++ Source> drivers/vulkan/vulkan_context.cpp:1970 @ _update_swap_chain()
immediately after
![image](https://user-images.githubusercontent.com/7500437/225046880-0ababb31-0e57-4997-8827-c4a74214c6f1.png)
pops up, and after the error the whole game is frozen, or at least the input..

So I've debugged the engine and for some reason the VK_ERROR_UNKNOWN = -13 is returned as a result on vulkan_context.cpp:1970 line when the function vkCreateSwapchainKHR(fpCreateSwapchainKHR inside the engine) is run after the game is maximized... 

Both Facepunch and GodotSteam throws the error above if you minimize and maximize the game window several times. Also after this error happens the game view is frozen(no interaction can be done on UI)

This is what is sent to fpCreateSwapchainKHR before the error
![image](https://user-images.githubusercontent.com/7500437/225047203-c07bd83d-0c9e-49e5-9508-57b42c3173f6.png)
![image](https://user-images.githubusercontent.com/7500437/225047262-a263790e-8a23-4ad2-9d0c-5127ebbece6a.png)

Steps to reproduce:
In my case after first minimize -> maximize i have to wait 2-3 seconds to see the steam popup, after that if I minimize->maximize again the error occurs, it's a strange behavior but I can replicate it each time and on both Facepunch.Steamworks and GodotSteam. After first occurrence of the error each minimize->maximize throws the same error

I guess something is missing from Vulkan implementation, unfortunately I do not have experience with graphics APIs so not sure how to interpret what I see... 

Sorry for the long post and hope this helps.

Thanks,
Mihai C.

**Comment by clayjohn** [comment]
@miketgv Thats a very interesting issue. My understanding is that VK_ERROR_UNKNOWN is not a valid result for any function. Therefore it is used in situations of undefined behaviour. Instead of handling the edge case in a vender-specific way, vendors are free to return VK_ERROR_UNKOWN. This can happen if we provide invalid input that the implementation can't handle, or if there is an internal bug in the implementation. The specification recommends running the application with validation layers enabled to see if you can get more information about exactly what has gone wrong. In godot you do that by running the application from the command line with the ``--gpu-validation`` command line argument.

**Comment by miketgv** [comment]
> @miketgv Thats a very interesting issue. My understanding is that VK_ERROR_UNKNOWN is not a valid result for any function. Therefore it is used in situations of undefined behaviour. Instead of handling the edge case in a vender-specific way, vendors are free to return VK_ERROR_UNKOWN. This can happen if we provide invalid input that the implementation can't handle, or if there is an internal bug in the implementation. The specification recommends running the application with validation layers enabled to see if you can get more information about exactly what has gone wrong. In godot you do that by running the application from the command line with the `--gpu-validation` command line argument.

 Thanks for your reply,

after running with --gpu-validation I get this:
![image](https://user-images.githubusercontent.com/7500437/225139166-a66f1830-f409-4b51-bb4d-ac322281f20c.png)
I hope I did it right but I do not see any new info, is there a log file I should look into?

**Comment by clayjohn** [comment]
Thanks for trying. It looks like you need to download the [Vulkan validation layers](https://vulkan.lunarg.com/sdk/home) from khronos to get any helpful information

**Comment by miketgv** [comment]
> Thanks for trying. It looks like you need to download the [Vulkan validation layers](https://vulkan.lunarg.com/sdk/home) from khronos to get any helpful information

Well this is new info:
![image](https://user-images.githubusercontent.com/7500437/225144894-7ca863e7-f804-481b-8a8f-c2508d4f115c.png)

**Comment by Gramps** [comment]
Still works fine when running from Steam client after exporting with the GodotSteam template.  I tried exporting and running from Steam client with console to see what it would output but I'm 100% I'm doing something wrong.  I made a post on the Khronos forums to see if I could get someone to weigh in on this.

**Comment by Gramps** [comment]
OK, I installed the Vulkan SDK and have been playing with the Configurator.  Due to my lack of knowledge with this stuff I'm not 100% sure I'm looking for or what tests to run.  I do get some weird validation errors when running a test project with `--gpu-validation` but not sure what I'm looking for.  If it even helps, I see this:
````
ERROR: Vulkan Debug Report: object - 2759994775760
Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00291 ] Object 0: handle = 0x2829c8218d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x9a6c2841 | vkCreatePipelineLayout(): max per-stage storage image bindings count (9) exceeds device maxPerStageDescriptorStorageImages limit (8). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, and VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER accessible to any shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceLimits::maxPerStageDescriptorStorageImages (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00291)
   at: VulkanContext::_debug_report_callback (drivers\vulkan\vulkan_context.cpp:300)

VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00291(ERROR / SPEC): msgNum: -1704187839 - Validation Error: [ VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00291 ] Object 0: handle = 0x2829c8218d0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x9a6c2841 | vkCreatePipelineLayout(): max per-stage storage image bindings count (15) exceeds device maxPerStageDescriptorStorageImages limit (8). The Vulkan spec states: The total number of descriptors of the type VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, and VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER accessible to any shader stage across all elements of pSetLayouts must be less than or equal to VkPhysicalDeviceLimits::maxPerStageDescriptorStorageImages (https://vulkan.lunarg.com/doc/view/1.3.239.0/windows/1.3-extensions/vkspec.html#VUID-VkPipelineLayoutCreateInfo-pSetLayouts-00291)
    Objects: 1
        [0] 0x2829c8218d0, type: 3, name: NULL
````
Running the test project from Steam with console doesn't show anything; however, when I run the test from Vulkan's Configurator, the Steam console does change, though mostly updating me on game processes being added or removed solely.

I do notice that in my case it only loads the these layers, though I don't know Steam should be listed in here:
- VK_LAYER_NV_optimus
- VK_LAYER_OBS_HOOK
- VK_LAYER_KHRONOS_validation

It does seem to find the Steam manifest when it boots:
````
Located json file "D:\Steam\SteamOverlayVulkanLayer64.json" from registry "HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\Vulkan\ImplicitLayers"
````

The only response I got from posting this issue with @miketgv's image was: "Creation of the Vulkan Swapchain failed in Godot with error code that is obscured by Godot."  So I'm not sure what to do with that information.

**Comment by Gramps** [comment]
@miketgv How do you get that output?  Mine looks very different with no red errors.

**Comment by sakrel** [comment]
@Gramps where are you initializing steam? I could only find this method that calls `SteamAPI_Init`:
https://github.com/Gramps/GodotSteam/blob/gdextension/godotsteam/godotsteam.cpp#L353-L357
But I couldn't find any calls to `Steam::steamInit` in the extension source code

**Comment by Gramps** [comment]
Yeah, the user manually calls this since they can choose whether or not to have it fetch the user's data (statistics, achievements, etc.) during the start process.  Also in case they decide to make a build that ignores Steam's API so they can have one project that exports to difference platforms.

**Comment by sakrel** [comment]
Well, then that's the problem. Just like clayjohn said, `SteamAPI_Init` needs to be called during module initialization (`MODULE_INITIALIZATION_LEVEL_SERVERS`).

**Comment by Gramps** [comment]
If that is what he meant, it was not specifically clear as he just mentioned "module initialization".  Semantics, what can ya do.  That being said, that's how pretty much every implementation of Steamworks seems to function from what I've seen.  If this is actually the case then it will never work with Forward+.  Though it does make me wonder how a user reported it working for them in beta 15.

Though thank for finally giving me some clear direction on what is going on!  I will build a version that just calls the Steam API immediately to see if that clears it up.  If so, then we'll just inform users that overlay will not work in the editor with Forward+.

**Comment by Gramps** [comment]
OK, so moving SteamAPI_Init to trigger automatically will indeed allow overlay to function with Forward+ in the editor.  However, this makes overlay actually work **in** the editor, which is not ideal behavior.

At least we can finally put this to bed and make the necessary notes!  Thank you much, @sakrel!

**Comment by etha7** [comment]
Does anyone in this thread e.g. @Gramps, know if there's anything we can do within our project code to fix this? Is there somewhere we can call SteamClient.init (and I assume SteamAPI_Init) earlier so the overlay will work with Forward+?

**Comment by Gramps** [comment]
Hey @etha7!  Nope, there is nothing you can do to change this behavior.  Steam would have to be called before Vulkan initializes which means it would work in the editor itself (overlay rendering over top of the editor).  However, none of this matters as overlay can be called in your game once it is running from Steam.  You just won't be able to test overlay from an editor-run version of your game prior unless you were testing in Compatibility mode instead.

**Comment by etha7** [comment]
> Hey @etha7! Nope, there is nothing you can do to change this behavior. Steam would have to be called before Vulkan initializes which means it would work in the editor itself (overlay rendering over top of the editor). However, none of this matters as overlay can be called in your game once it is running from Steam. You just won't be able to test overlay from an editor-run version of your game prior unless you were testing in Compatibility mode instead.

Thanks so much for responding 😄 

Only last question: When you say it works when running from Steam, do you think it should also be working if I manually export to the correct path in the Steam folder, copy the steamAPI and Facepunch DLLs and run through Steam? Or do you think its necessary to actually publish the game to Steam first?

**Comment by Gramps** [comment]
As long as it runs from the Steam client, it should work.  The client will attempt to inject overlay on programs run through it.  There are some situations where this won't work but it should in this case.
