### ISSUE TITLE
[4.0 RC2+] - HTML5 Builds - Detect Game Controller On 1st Press Of Controller Button...

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#73556]
### Godot version

v4.0.rc2.official [d2699dc7a]

### System information

HTML5 Builds(Windows/Linux/macOS? PC Internet Browsers)

### Issue description

Hi,

I've seen the above used somewhere on the Internet.
It was a game controller test web application.
If the user pressed a button on the controller, the test app would detect it.

Jesse

### Steps to reproduce

N.A.

### Minimal reproduction project

N.A.

**Comment by BetaMaxHero** [comment]
https://gamepad-tester.com/

**Comment by KoBeWi** [comment]
So what is this issue about? The tool is already known and was linked in multiple issues (and I think in the documentation).

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
