### ISSUE TITLE
Grease Pencil to take notes in the editor

### ISSUE THREAD

**Issue by henriiquecampos** [godotengine/godot#7361]
Hey guys...I was thinking (inb4 here we go again) what if Godot had a Grease Pencil to write some notes in the scene. I really like to use it in Blender to take some notes about a specific thing.

and I think it would be awesome to have this in Godot to sketch some game bahaviours and systems, or note comment something someone did (good or bad).

It could be a node that only renders on editor. Is it viable?
![15723524_1140299556023729_7470708009920256826_o](https://cloud.githubusercontent.com/assets/10171059/21464215/b479d66e-c95d-11e6-807d-c9e626277c54.jpg)

**Comment by freemanfromgodotengine** [comment]
Is there another way to take notes in Blender?
I ask, because if it's the only way, then it's sure useful to be able to take notes at all in Blender.

As of Blender, I am a noob, but from my experience I noticed, that most of the time notes should be rather taken in code - something that mostly does not exist in Blender, unless you are creating python scripts, I guess, right? In Godot 2d and 3d views are just used to arrange visual elements in the scene.
When I really needed to remember specific thing in the visual scene editor in Godot, I just used label node, that I was able to see and delete whenever I wanted. 
One could even create a special parent for notes taking and put them all there, easy to find and delete.
But if someone will be willing to create grease pencil feature, probably some people will use it.

**Comment by henriiquecampos** [comment]
Yeah, but how about the overall design process? I mean, drawing gives much more freedom to artists take notes, highlight something, save a scene with notes of how an animator could animate the sprites. Or even game designers could take notes about a mechanic, so that a programmer opens the scene and implement the changes, or try to design the UI, et cetera. 

Notes in code is just to comment the code, how it works and stuff, artists are not intented to even open a script, scripting and coding is aimed to coders/programmers. With this kind of feature the team communication can have a much higher level, easing the rework time and making the workflow more fun by improving the usability and design process.

**Comment by bojidar-bg** [comment]
I don't know -- in all the time I've used blender so far (for lots of things actually, but mostly player around with cycles), I never found a single use of grease pencil (and when I did, it was not the best too to use -- guess I was overthinking it at the time).

**Comment by akien-mga** [comment]
I think it could be interesting, but it likely doesn't need to be implemented in the engine directly. It could be an editor plugin distributed in the asset library.

**Comment by groud** [comment]
Honestly it depends, I see that as a really powerful collaboration tool. By the day we integrate Git and all, it would be handy to have this built-in.

**Comment by akien-mga** [comment]
Well I also don't see much point in integrating "Git and all" out of the box when it can be done perfectly via plugins. What if you want to use Mercurial, or, more common in big video game studios, Perforce? Plugins is the way to go for all those.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
