### ISSUE TITLE
get_tiles_count on Scene Collection returns wrong number

### ISSUE THREAD

**Issue by Jeb187** [godotengine/godot#73645]
### Godot version

4.0 RC2

### System information

Kubuntu 22.10

### Issue description

The method get_tiles_count() does not return the right amount (always 1) of included scenes, when called on a Scene Collection Source.

It works alright when called on an Atlas Source, though.

### Steps to reproduce

1. Create TileMap Node
2. Create TileSet
3. Add Scene Collection to tileset
4. Add Scenes to Scene Collection
5. call get_tiles_count() on tileset
6. it always returns 1, no matter how many scenes were actually added to the Scene Collection

### Minimal reproduction project

[get_tiles_count.zip](https://github.com/godotengine/godot/files/10787283/get_tiles_count.zip)

**Comment by KoBeWi** [comment]
Seems unimplemented:
https://github.com/godotengine/godot/blob/9c960a8c2494eb826a557a7ffc96dd4547f9d31e/scene/resources/tile_set.cpp#L4731-L4733
I wonder if there is a reason.

**Comment by Jeb187** [comment]
As a workaround I use get_next_scene_tile_id() and subtract 1 from the returned value. 

But I'd prefere to use the proper method.

**Comment by groud** [comment]
This is the expected behavior. Those function are meant to be used to be able to iterate over all sources tiles and their alternatives. Since tiles scenes are indexed using the `alternative ID`, then the `get_tile_count` function should always return 1, and similarly, `TileSetScenesCollectionSource::get_tile_id` does always return `Vector2i(0,0)`

Here, it is `get_alternative_tiles_count` that should return the result you expect.
