### ISSUE TITLE
Improve ColorPicker to be like Photoshop's (Can switch vertical slider / gradient bg depending on selected color component)

### ISSUE THREAD

**Issue by chanon** [godotengine/godot#7366]
This is just a "nice to have" feature request.

The current ColorPicker is nice, but Photoshop's color picker has a few nice features I'd like to highlight.

(The following images are from Photoshop's color picker)

Here the gradient area selects Saturation and Brightness (Value) while the vertical slider selects Hue. This is similar to what Godot's ColorPicker looks like now.
Note that the vertical slider is selecting Hue because the H radio button is selected. .
![image](https://cloud.githubusercontent.com/assets/357737/21469949/74e9bd74-caa3-11e6-9720-d3d14c7ca6e3.png)

Now maybe I like the color but want to adjust the brightness a bit so I select the B radio button to adjust the color brightness on the vertical slider. The vertical slider lets me easily pick the brightness I want. I also have a nice Hue/Saturation gradient selection area to the left.
![image](https://cloud.githubusercontent.com/assets/357737/21469956/8875c464-caa3-11e6-8bcf-1b3fd2ac4de7.png)

I'm thinking maybe it needs more Red so I choose the R radio button to again adjust the vertical slider and see what adding more red to the color would do:
![image](https://cloud.githubusercontent.com/assets/357737/21469959/d68cd156-caa3-11e6-86d8-22a53f1d786b.png)

I find this flexibility extremely useful in helping to pick the right color.

Additionally Photoshop's color picker has the previous color (current) for easy comparison.

Of course the CMYK and Lab options aren't needed for game dev.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1 : the palette is in HSV only

**Comment by fire** [comment]
![2019-01-18_14-15-58](https://user-images.githubusercontent.com/32321/51415710-9b074780-1b2b-11e9-8e31-5d6f2e129ec0.png)

Here's an example from krita.

https://docs.krita.org/en/reference_manual/dockers/advanced_color_selector.html

My favourite model is HSY'.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
