### ISSUE TITLE
Control Nodes Flipped Horizontally Always 

### ISSUE THREAD

**Issue by M7MDNic** [godotengine/godot#73710]
### Godot version

4.0 rc3

### System information

Window 10, Vulkan API 1.2.162 - Forward Mobile, Intel - Intel(R) UHD Graphics

### Issue description

All the control nodes always flipped horizontally Like Label , TextEdit , VBoxContainer , HBoxContainer . I tried scaling it with -1
but It dosen't solve the problem 

### Steps to reproduce

I didn't add and code to node
<img width="721" alt="In Editor" src="https://user-images.githubusercontent.com/126022683/220459426-fc0aa274-b874-40a4-b518-d64d444bc781.png">
<img width="743" alt="In Game" src="https://user-images.githubusercontent.com/126022683/220459475-d59485fa-ffaa-4179-9256-999940a6c9f2.png">

### Minimal reproduction project

[TaskManager.zip](https://github.com/godotengine/godot/files/10797790/TaskManager.zip)

**Comment by akien-mga** [comment]
This is a feature for Right-To-Left language support, but here it seems to be used automatically without you having configured it. What's your system locale?

CC @bruvzg

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.rc 7e79aead9:

![image](https://user-images.githubusercontent.com/180032/220464099-2036a748-3f12-48a1-acf4-dd6aa1944c81.png)

Also, the MRP lacks a main scene defined – I assume it's `Task.tscn`?

**Comment by M7MDNic** [comment]
Yeah That Explain it My locale is Arabic

**Comment by M7MDNic** [comment]
Thank's for Replying

**Comment by M7MDNic** [comment]
> system locale is `en_US`):

Yes

**Comment by M7MDNic** [comment]
Is there a local setting in godot editor or I have to change my system local ?

**Comment by akien-mga** [comment]
You can change the "Layout Direction" property on the root control of your project to "Left to Right" instead of "Inherited". This will disable the feature.

![image](https://user-images.githubusercontent.com/4701338/220468643-89d9b897-d655-4119-9ea8-5d21cd809d2d.png)

Note that it's a bit confusing here as you designed your UI to follow Right to Left convention (edit button on the left, OK/add on the left, etc.), but technically for Godot it doesn't know your intent. So if you select the Right to Left mode, it will actually flip your UI back to Left to Right :)

If you want to translate the app to both English and Arabic, then you could make use of this feature to do auto-layout based on the language.

**Comment by M7MDNic** [comment]
> You can change the "Layout Direction" property on the root control of your project to "Left to Right" instead of "Inherited". This will disable the feature.
> 
> ![image](https://user-images.githubusercontent.com/4701338/220468643-89d9b897-d655-4119-9ea8-5d21cd809d2d.png)
> 
> Note that it's a bit confusing here as you designed your UI to follow Right to Left convention (edit button on the left, OK/add on the left, etc.), but technically for Godot it doesn't know your intent. So if you select the Right to Left mode, it will actually flip your UI back to Left to Right :)
> 
> If you want to translate the app to both English and Arabic, then you could make use of this feature to do auto-layout based on the language.

Thank so much you help me a lot
