### ISSUE TITLE
Use .csproj to determine if project can be build

### ISSUE THREAD

**Issue by squidink7** [godotengine/godot#73720]
### Godot version

4.0 rc 3

### System information

Arch Linux

### Issue description

since version 4.0 rc 2, Godot builds C# projects using the `.csproj` file rather than the Visual Studio `.sln`, and as .NET 6 also just uses the `.csproj` to manage a project, theres no need for a `.sln` in most game projects other than if you're using Visual Studio as an editor. However, Godot seems to require the `.sln` to exist in order to detect the .NET project and build it when need be, it doesn't even need to be valid (or at least contain a reference to the `.csproj`), it simply needs to exist. If the editor could remove this reliance on the `.sln` file to work, that would mean we can finally delete this unneeded, bringing us closer in line with modern .NET project structure.

### Steps to reproduce

Create a new C# project.
Build and run.
Rename `project.sln` to `project.oldsln`.
Reload current project.
Note that it no longer updates the build, but still uses the last successful build (can be updated manually by running `dotnet build` in the project dir).

### Minimal reproduction project

Any C# project with a script.

**Comment by raulsntos** [comment]
> 4.0 rc 5

I'm going to assume you meant RC 3 since that's the last one we released :slightly_smiling_face: 

The dotnet CLI doesn't need a solution file so I think it may make sense to lift this restriction in Godot too. But keep in mind it's not just used by Visual Studio; Visual Studio Code and JetBrains Rider can also use it and it can be convenient in multi-project scenarios.

I also wouldn't say that getting rid of the solution file brings us closer to modern .NET project structure. While it's true that solution files are not required, they are still useful to manage multiple projects and many IDEs use them. They are not going away any time soon.

**Comment by squidink7** [comment]
> I'm going to assume you meant RC 3 since that's the last one we released 🙂

Yes, typo, sorry.

> I also wouldn't say that getting rid of the solution file brings us closer to modern .NET project structure. While it's true that solution files are not required, they are still useful to manage multiple projects and many IDEs use them. They are not going away any time soon.

That's true, I've just never come across a .NET 5+ project with a solution file.

> Visual Studio Code and JetBrains Rider can also use it

I haven't had any experience with rider, but I haven't noticed a difference in VSCode with and without one, although I wouldn't be suprised if indeed it did play a role somewhere.

I'm

**Comment by raulsntos** [comment]
>  I haven't noticed a difference in VSCode with and without one

When there are multiple C# projects in the workspace, VSCode lets you select the project that will be used as target for the Omnisharp server but it defaults to the solution if there's one.

> Anyway, I'm not advocating to remove it, just make it optional as you said.

Yeah, I just wanted to make it clear so it's not misunderstood.

**Comment by silenuz** [comment]
Just wanted to add my two cents, as someone said Net solutions are'nt going anywhere however the current implementation of the Godot build process does not truly allow that naturally.  I'm currently working on a plugin in C# just to try and learn the Editor.

Yesterday everything was working fine in the Godot editor , today I rearranged it so it would be properly layed out as a standard solution.

![godot-solution](https://user-images.githubusercontent.com/13521146/222907662-26d9faf9-f1e1-4d2a-bcad-937e06f28af4.png)

The idea being that that later if I wanted to build a command line application or whatever I could leverage the library project and have minimum work.

So I added the new files and what not, not revelant.  Built it , fired up Godot, checked my plugin, it was working, so I went to add a quick GD.Print() in the built in editor, but when I went to rebuild the project I could no longer do so from the editor because there was no longer a Build button.  I had to switch back to the ide to build the project, and restart the editor to have the changes take effect.

![Screenshot 2023-03-04 092633](https://user-images.githubusercontent.com/13521146/222907997-82b09504-a97c-4e92-ac08-31776cc7bbc0.png)

**Comment by raulsntos** [comment]
@silenuz I can't say for sure if this is an issue without looking at your project structure, but as long as the `.csproj` for the Godot project is next to the `project.godot` file everything should work (and the _Build_ button should still show up).

Changing the location of the solution file is allowed but if you do make sure you also update it in the project settings:

![image](https://user-images.githubusercontent.com/3903059/222916050-8c28387f-774e-4be0-ba9c-8b4930b44eef.png)

**Comment by silenuz** [comment]
I can assure you the project file is there beside the godot project file.

Here's what the solution folder looks like:

![Screenshot 2023-03-04 120030](https://user-images.githubusercontent.com/13521146/222919014-bc7404b5-cd41-4fca-b757-5edf62232594.png)

Here's what the godot project folder looks like:

![Screenshot 2023-03-04 120105](https://user-images.githubusercontent.com/13521146/222919029-011f06a5-9b7f-4fa2-b0d3-51538f765779.png)

Note building the godot project from the command line works, so there's nothing wrong with the net project file.

Also I looked in the godot.project file and don't see anything related to the sln file.

```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=5

[application]

config/name="CsharpScenePlugin"
config/features=PackedStringArray("4.0", "C#", "Forward Plus")
config/icon="res://icon.svg"

[dotnet]

project/assembly_name="CsharpScenePlugin"

[editor_plugins]

enabled=PackedStringArray("res://addons/_kennyclass/plugin.cfg")
```

**Comment by raulsntos** [comment]
Make sure the _Advanced Settings_ toggle is enabled.

You should be able to also edit the `project.godot` file manually to add the `project/solution_directory` setting, I think this should be the value for your folder structure:

```
[dotnet]

project/assembly_name="CsharpScenePlugin"
project/solution_directory="res://.."
```

**Comment by silenuz** [comment]
Much Thanks

**Comment by MrJul** [comment]
> If you have an existing solution and add a Godot project to it, unless the existing solution is the same name as the Godot project there is no way to build the project from the Godot editor, as the build button is no longer visible.

Indeed, in appears the solution name must match the assembly name, which prevents having multiple Godot projects inside the same solution and still be able to build them from the editor, as well as opening the correct solution on double click on a .cs file.

Relevant code:

https://github.com/godotengine/godot/blob/ee865051367a78bf20f50500520af13ef8f1097b/modules/mono/editor/GodotTools/GodotTools/Internals/GodotSharpDirs.cs#L79

Would a PR adding a new setting `project/solution_name` be accepted? Defaulting to `assembly_name` if unset, for backwards compatibility. As far as I can see everything already uses `ProjectSlnPath` so changing how it's computed should be sufficient.

**Comment by raulsntos** [comment]
- Fixed by https://github.com/godotengine/godot/pull/78488.
