### ISSUE TITLE
Particles will not render the color correctly when using color ramp + color initial ramp

### ISSUE THREAD

**Issue by RPicster** [godotengine/godot#73872]
### Godot version

4.0.rc4

### System information

Win 10

### Issue description

When using a combination of these settings, only color_ramp will be used as a recompilation of the shader is not triggered.
![image](https://user-images.githubusercontent.com/9423774/221189343-2f0c5dcc-7422-4699-9293-c51fe7e594fb.png)

Deleting the ramp used in color_ramp and reassigning a new ramp will cause a recompilation and everything looks as it should.

### Steps to reproduce

- Create GPUParticle3D node and give it a basic setup
- Add a color_ramp
- Add a color_initial_ramp

### Minimal reproduction project

Makes no sense, when the project is closed and reopened, the shaders are recompiled.

**Comment by RyanGatts** [comment]
Still running into this in 4.1.2.stable.official
No combination of Color Ramp and Color Initial Ramp can be used together, Color Ramp's output always stomps Initial.

**Comment by clayjohn** [comment]
I can confirm that this is still a problem in 4.1.x. It has been fixed for 4.2 though, I confirmed that it is fixed as of Beta4!

I think it was fixed by https://github.com/godotengine/godot/pull/79527 which was a major change, which means it isn't suitable to be cherrypicked to 4.1.4 unfortunately.
