### ISSUE TITLE
Document licenses of thirdparty libraries and code snippets exhaustively

### ISSUE THREAD

**Issue by Alex-doc** [godotengine/godot#7388]
As you can see here: [minimax.h](https://github.com/godotengine/godot/blob/master/thirdparty/libmpcdec/mpc/minimax.h)
And on many other places around the code, Godot uses BSD and LGPL software without informing the users. 
I'm not a lawyer but I think while on source version might not be an issue, is totally not fair to distribute without at least a LICENSES file that lists those libraries.

I'd put this issue to a high priority since those people who made the libraries must have their credits given.
It might sound stupid, but tomorrow, the same thing could happen to me and you.

**Comment by bojidar-bg** [comment]
Given that `minimax.h` comes directly without modifications from the first commit to the repo, and has copyright of `1999-2004`, I guess that was way before anyone was thinking of GPL and similar licenses...

**Comment by Alex-doc** [comment]
Surely it's been a long time, and wasn't on purpose, but that's what it is.
The average user won't give a shout about the licenses and someone must credit those programmers.

**Comment by punto-** [comment]
We shouldn't be using LGPL anywhere, because we don't distribute any shared
objects. This file seems to be the only one that's LGPL in that library
(everything else is some sort of BSD), can we replace it? It's a bit silly,
it's all macros that probably already exist somewhere else in our code, and
they're pretty common anyway, but we don't want LGPL stuff. I assume we
looked up the license of Musepack back then and it came up as BSD and we
didn't see that file. Otherwise just remove it, with Opus it might not be
necessary any more.

I agree that we should maintain one big file with everything that needs to
be included for distribution, maybe put it in the exports, or somewhere
inside the binaries if it complies with all the licenses.

**Comment by est31** [comment]
Its a little bit confusing. The [website of musepack](https://www.musepack.net/index.php?pg=src) shows the license of libmpcdec as BSD, but when you download the tarball you will find precisely those header under the LGPL license. The advertised successor is licensed LGPL. I'm not sure what the authors intended. If the library is seen as keep-worthy, best would be probably to contact the author, and ask about the license, maybe to get written agreement that the files can be used under BSD as well, otherwise the library should just be removed.

**Comment by Alex-doc** [comment]
I agree about contacting the authors of libmpcdec.

About the other libs I've made a quick(and dirty) script to find licences: http://pastebin.com/Rh1EUgvK

This is what I've came up so far:
http://pastebin.com/2CuCtFXM 
It's far from perfect but it's something.
(Note the !!ISSUE marked libs are some I didn't understood the license)

**Comment by punto-** [comment]
Appirater should be removed, I don't think it was ever enabled..

**Comment by akien-mga** [comment]
For the reference: https://github.com/godotengine/godot/issues/6745#issuecomment-256144607

I don't think we should document the sublicenses of hidden headers of thirdparty libraries - we should give for each library the license(s) that upstream projects claim to have (what I've started in `thirdparty/README.md`), and if they did not do the legal legwork themselves to give credits where due (in the case of BSD or MIT licensed components), it's their problem.

Copylefted code hidden in a BSD licensed library is another issue though as it impacts us, so the file should be removed or the library altogether.

Then we also have some code that is not in `thirdparty/` and that was taken from thirdparty sources, especially some header-only libraries or code snippets from other projects that were adapted to Godot (SDL2, Bullet, minizip). I had started referencing them here: https://github.com/godotengine/godot/issues/5248

**Comment by akien-mga** [comment]
All right, starting to work on this for real now that most thirdparty code has been properly moved to the `thirdparty/` directory.

I'll use @Alex-doc's work as well as the nice [licensecheck](http://search.cpan.org/~jonass/App-Licensecheck/bin/licensecheck) tool to try to get something exhaustive.

**Comment by akien-mga** [comment]
For the reference re: the above discussions, Appirater was dropped from master and 2.1, and libmpcdec was dropped from master.

**Comment by akien-mga** [comment]
Here's the first part: [copyright.txt](https://github.com/godotengine/godot/files/981199/copyright.txt)

It lists the copyright and licensing info for all Godot files minus (for now, will be added later) the `thirdparty/` directory, using Debian's machine readable debian/copyright standard format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#copyright-field

For thirdparty libraries I'll use a similar syntax, but I won't go into the details of every single file of the thirdparty code. For libraries, I'll stick to the "main" license and copyright advertised by the upstream project - it's their job to go further down.

**Comment by akien-mga** [comment]
Here's an updated version with all thirdparty content documented: 
[copyright.txt](https://github.com/godotengine/godot/files/981211/copyright.txt)

It's not the prettiest or the most readable output, but for such a boring job as listing licensing details for every single file in the code repo, it does the job :)

We'll see if we can provide a human-readable version of it that could be used e.g. to go with distributed games, or an HTML page on our website that game developers could link to.
