### ISSUE TITLE
can_instantiate: Cannot instance script because the associated class could not be found (Project name contains invalid characters like `#`, `;`, `'`)

### ISSUE THREAD

**Issue by MaciejCzekonski** [godotengine/godot#73932]
### Godot version

4.0RC5 Mono

### System information

Windows 10

### Issue description

I've seen this issue posted before and closed despite never being fixed

### Steps to reproduce

- create project
- create new scene with CharacterBody2D, let's call it "Player"
- add AnimatedSprite2D and CollosionObject2D to it as children
- create another scene and set it as main scene
- create new script that inherits from CharacterBody2D and attach by drag and drop to Player
- drag and drop Player scene to main scene
- run

### Minimal reproduction project

[Game2.zip](https://github.com/godotengine/godot/files/10831734/Game2.zip)

**Comment by akien-mga** [comment]
I don't see any error with the minimal reproduction project, it seems to work fine.
I've tried running it as is, removing the player scene from the main scene to re-add it following the steps to reproduce, but didn't get any error. I suspected it might raise an error when instantiating a scene with a yet-uncompiled C# script but it seems to work fine for me even if I don't compile.

**Comment by Zireael07** [comment]
I suspect OP is referring to #71735

**Comment by MaciejCzekonski** [comment]
After moving the whole godot folder (exe and project folder) up in the folder tree the issue stopped, maybe if the project is too deep (as in C:\Folder\Folder\Folder\Fodler) godot freaks out

**Comment by Calinou** [comment]
> After moving the whole godot folder (exe and project folder) up in the folder tree the issue stopped, maybe if the project is too deep (as in C:\Folder\Folder\Folder\Fodler) godot freaks out

This sounds like an issue with path lengths longer than 260 characters (which is a Windows limitation). Can you post the full path here? If you have to redact a name, redact it so that the final string length is identical (i.e. replace every character with a `x`).

**Comment by CordellierPaul** [comment]
Hi ! I'm having the exact same problem on the first stable 4.0 version and the path name is very small for me, i don't think that's the issue.

Because it seems hard to reproduce, I'm gonna say more details about what I'm using and maybe this will help : 
- Windows 11
- no graphics card, an 11th gen intel core i5
- Godot x64 for C#

I tried recreating another godot project and the bug was still here. I tried using external editors (without addons) and it still didn't worked. I followed a lot of tutorials as best as i could, .NET 6 is installed but I am still blocked.

Hope this helps !

(if my sencences sounds wierd, it's because i'm not a native english speaker lol)

**Comment by Atem1995** [comment]
I encountered the same problem at first, but after I reset the project, the problem did not appear; I think not only the cs file name should be consistent with the class name, but also the project name should not contain special symbols.I suggest looking at the following configuration. If other different configurations appear, there may be unknown problems that cause this error.
![捕获](https://user-images.githubusercontent.com/52338846/222351122-0b97a396-76d0-4cba-b01b-1be5591eea16.PNG)

**Comment by CordellierPaul** [comment]
> I think not only the cs file name should be consistent with the class name, but also the project name should not contain special symbols.

That fixed the bug for me! The project and the main file names for the godot project had the character "#" in it. As soon as I renamed them, the bug disappeared. The .sln and .scproj files can have that character though.

Thank you!

**Comment by Atem1995** [comment]
you are welcome.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "godotengine/godot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月2日(星期四) 晚上8:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [godotengine/godot] can_instantiate: Cannot instance script because the associated class could not be found. (Issue #73932)





  
I think not only the cs file name should be consistent with the class name, but also the project name should not contain special symbols.
  
That fixed the bug for me! The project and the main file names for the godot project had the character "#" in it. As soon as I renamed them, the bug disappeared. The .sln and .scproj files can have that character though.
 
Thank you!

**Comment by saierXP** [comment]
I found that this error occurs in these cases:

- project path contains a pound(#) 

- project name contains special character like ` ' ; , `

![image](https://user-images.githubusercontent.com/45038185/222724782-a4443d3f-efe3-48ac-8594-9ebc3562474c.png)
```
can_instantiate: Cannot instance script because the associated class could not be found. Script: 'res://Node2D.cs'. Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly (it's case-sensitive).
```
The error message does not give a hint about the above situation. And the editor does not give hints or warnings elsewhere.

**Comment by raulsntos** [comment]
:thinking: Interesting, when the project is named `TestHasPound#`, the C# script is stored in our map with the path `res://../TestHasPound#/Main.cs` instead of `res://Main.cs` which suggests it may be a bug in our ScriptPathAttributeGenerator.

So I looked into this, our generators use the `<GodotProjectDir>` property in C# projects defined by Godot.NET.Sdk. MSBuild has some special characters that need to be escaped (such as `;`). When retrieving these values from our generators, we get the wrong value possibly due to incorrect escaping/unescaping. It seems to be an upstream issue: https://github.com/dotnet/roslyn/issues/51692.

It may be possible to work around it by encoding the path with Base64 like they do in https://github.com/dotnet/sdk/pull/16858.

**Comment by NaturalMary63** [comment]
I was having the same problem.  My project was in a folder I'd named "Godot_TestGame" (since I'm brand new to Godot and learning it).  After reading all this, I closed the program, renamed the folder "GodotTestGame" and when I reopened the project it worked as expected without any issues.  This is a weird bug to have, imho, when even a simple underscore messes up the path.

**Comment by raulsntos** [comment]
@NaturalMary63 I was unable to reproduce your issue on Godot 4.2.2. Please open a new issue and upload the broken project as well as the steps to create the broken project.
