### ISSUE TITLE
'track_set_enabled' breaks method tracks, if enabling/disabling a method track 

### ISSUE THREAD

**Issue by LakshayaG73** [godotengine/godot#73931]
### Godot version

v4.0.rc.custom_build [ba5a70ccc]

### System information

Windows 11

### Issue description

if using track_set_enabled to enable/disable method tracks, all method tracks get broken and start getting called twice, provided the next animation in the list is 'looping' 

### Steps to reproduce

1 - create two animations, A(looping) and B in animation player
2 - create separate call method animation tracks in both animations
3 - have animation B call method 'B', and upon ending, switch to animation A, which loops
4 - in the same function that changes the animation, enable the call/method track in A before playing the same
5 - the call method track from B will be called again

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@LakshayaG73 Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
