### ISSUE TITLE
SSS Transmission visual bug

### ISSUE THREAD

**Issue by DoItForGrandpa** [godotengine/godot#73946]
### Godot version

4.0 RC5

### System information

Windows 11, Vulkan

### Issue description

When using transmission but going above the max value to get the desired results I end up having visual problems with the material. 

Skin Without SSS;
![image](https://user-images.githubusercontent.com/100494538/221376413-3084bea3-7537-4af6-9892-6f9f058c2a0d.png)
Skin With SSS;
![image](https://user-images.githubusercontent.com/100494538/221376417-bdc19614-8718-4eae-b1da-7afe6543c2fa.png)
Visual Issues:
![image](https://user-images.githubusercontent.com/100494538/221376423-23c96af3-3231-42dc-a36c-7837bdd3ebf1.png)
![image](https://user-images.githubusercontent.com/100494538/221376427-3fdc10fb-5397-4269-881f-880e6b03acdd.png)

This is not a custom mesh problem, using the default sphere it has this bright visual issue as well;
![image](https://user-images.githubusercontent.com/100494538/221376460-8c5f307a-9799-4b26-a4a7-0dcfe8b15a87.png)

This seems to be on the other side of the sun/light source that ends up having this issue.

### Steps to reproduce

1. Create a new scene
2. Create a new instanced mesh and assign a new material to it
3. Set up the material SSS like so;
![image](https://user-images.githubusercontent.com/100494538/221376514-43f467a7-ae17-4c2a-80d7-801cf243a4e4.png)

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
I'm not sure that a transmittance depth of 500 is a reasonable value. The defined range in the editor is 0.001 to 8. When you go that far outside of the reasonable range I think you have to expect some problems to occur. On our end, the way of "fixing" this type of bug is to clamp the range so you cannot type in a value greater than 8, would that be preferable for you?

**Comment by ParasiteSt** [comment]
I am not sure how to go forward if it is clamped at 8 since if you have something up higher like 100-500 you get transmission to bleed through a lot more like so ;
![image](https://user-images.githubusercontent.com/100494538/221378697-17f77a92-ffa8-4ffd-b2ff-b6c842e59438.png)
But if you have it clamped to 8 you get nearly 0 bleeding effect which is used for cartoony skin, and candle wax, etc.
![image](https://user-images.githubusercontent.com/100494538/221378731-326188a0-44f6-416b-8e18-0b7b31de981e.png)

**Comment by ParasiteSt** [comment]
But in all honesty I feel the best approach is to clamp it to 8 since anything over it starting at about 30 you get these artifacts. @clayjohn thanks for the quick response on this. Since this is based on a universal material that should suit most needs, I feel that my need is more custom and I will go that route with it.
