### ISSUE TITLE
StreamPeerTCP get_status() not returning correctly

### ISSUE THREAD

**Issue by 7hedubz** [godotengine/godot#74033]
### Godot version

4.0 RC5 & 3.5.1
EDIT - Upon further testing this result is in all current Release Candidates, 1-5

### System information

WIN 10

### Issue description

When connecting to an external TCP Socket (in a python script) the get_status() function returns the integer 1 for  [all 4.0 RC's]

and properly returns 2 in 3.5.1. 

The python script properly returns `f"Connection from {addr} accepted"` in both instances

### Steps to reproduce

Run the Python script, Run Godot with script attached to main scene.

All code is the same for all versions of Godot. Python being ran on 3.11.0 but should be almost exactly the same with all versions 3.0+

### Minimal reproduction project

[zzz.zip](https://github.com/godotengine/godot/files/10837824/zzz.zip)

**Comment by fengjiongmax** [comment]
This is due to a change of behavior in the function `StreamPeerTCP::get_status()`, in version 3.5, when calling the function, the engine will check the status of the socket, and then call `poll` it if it's in `STATUS_CONNECTING` , and in version 4.0, status check was removed.
So you can try call `poll()` on the `StreamPeerTCP` object before getting the status so it's updated.
[4.0 StreamPeerTCP::get_status](https://github.com/godotengine/godot/blob/6ef2f358c741c993b5cdc9680489e2c4f5da25cc/core/io/stream_peer_tcp.cpp#L244-L246)
[3.5 StreamPeerTCP::get_status](https://github.com/godotengine/godot/blob/3.5/core/io/stream_peer_tcp.cpp#L235-L258)

It was changed in PR #59582

**Comment by 7hedubz** [comment]
Will get around to properly checking that and marking sisue as resolved shortly, I appreciate the look that you've had at this for me.
