### ISSUE TITLE
Draw issue with focus in UI elements (Compatibility renderer)

### ISSUE THREAD

**Issue by rm-code** [godotengine/godot#74115]
### Godot version

4.0.rc6.mono.official

### System information

macOS 12.0.1

### Issue description

Just a minor visual issue.

When opening an empty directory the focus highlight is drawn incorrectly. It looks like the UI is drawing a smaller rectangle within the main rect:
<img width="1058" alt="Bildschirmfoto 2023-02-28 um 14 13 31" src="https://user-images.githubusercontent.com/11627131/221868794-7450606d-e758-4104-8f33-182d9779d7f8.png">

This behavior also changes when you hover over other items in the view, so I'm not sure if this a general issue with the focus highlighting or just an issue in the directory view:
<img width="1052" alt="Bildschirmfoto 2023-02-28 um 14 32 54" src="https://user-images.githubusercontent.com/11627131/221869308-4756f26e-cda2-4057-be1e-7439030895dc.png">

### Steps to reproduce

1. New Project
2. Browse
3. Create Folder
4. Click or Tab to set focus on the empty directory view

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
I confirm this. Note that the bug is reproduced not in all dialogs.

Project Manager - Scan:
![](https://user-images.githubusercontent.com/47700418/221914036-90619435-7e27-45ed-a964-e93c65019eda.png)

Open Scene:
![](https://user-images.githubusercontent.com/47700418/221914224-27041ffb-123b-4c0b-8ed9-95169a1e4e38.png)

**Comment by rm-code** [comment]
The issue isn't limited to the file dialogues. Here is an example of the issue on a non-empty UI screen:

<img width="877" alt="Bildschirmfoto 2023-03-05 um 14 18 26" src="https://user-images.githubusercontent.com/11627131/222962925-e21442ca-dce2-4bbf-9da5-b7eb71dbae85.png">

**Comment by a690089735** [comment]
downloading the export template

> When I was downloading the export template, I accidentally clicked on the bottom box and it started flashing. If I clicked a few more times, it would flash faster

https://github.com/godotengine/godot/assets/34900141/73cf9186-f021-42d4-8fbc-88e29f0e08ce

**Comment by dardasaba6** [comment]
Also experiencing this in 4.1 RC1 on Linux Mint:
![Screenshot from 2023-06-29 16-28-04](https://github.com/godotengine/godot/assets/125468288/55ae15d9-2894-4ca9-9b1e-d7ccab859136)
![Screenshot from 2023-06-29 16-31-57](https://github.com/godotengine/godot/assets/125468288/62dcfc25-661c-44c0-b99a-6dd5badd179b)
![Screenshot from 2023-06-29 16-32-23](https://github.com/godotengine/godot/assets/125468288/adb51cd5-e5f9-4724-bef6-4dcbb492f4ef)

**Comment by dalexeev** [comment]
* See also #79652.

![](https://github.com/godotengine/godot/assets/47700418/3e3b7313-26f0-475e-9dfb-4146ce6d2a36)

**Comment by dalexeev** [comment]
As stated in #71213, the bug is reproducible with the **Compatibility renderer**. I confirm that the bug is reproducible in 4.1.1 and the current master in Compatibility mode.

**Comment by WhalesState** [comment]
A question, isn't the issue related to Editor Inspector draw notification ?
![image](https://github.com/godotengine/godot/assets/53877170/ddd1b8cb-dadb-4323-bfe6-82da2e098c30)

**Comment by lawnjelly** [comment]
An MRP would probably really help investigate this, if someone can get it to trigger in a simple project. Speaking from experience debugging the GUI in 3.x, there is a lot going on, so the first step is usually to simplify it down to the bare minimum draw items to create the bug. It probably just needs some GUI control.

It could be a problem in the GLES3 backend, or the GUI code (even if Vulkan is behaving ok).

**Comment by dalexeev** [comment]
> An MRP would probably really help investigate this

This is an editor issue. Steps to reproduce:

1. Create a new project.
2. Select Compatibility renderer and restart the editor.
3. Open Project Settings and click on `ItemList`/`Tree` in any tab.

<details>
<summary>One more screenshot</summary>

![](https://github.com/godotengine/godot/assets/47700418/d8b007d0-62cb-4220-9ac1-cadc261a8371)

</details>

**Comment by WhalesState** [comment]
I have tried to add a breakpoint inside `draw_rect` and `draw_stylebox` functions in `CanvasItem` and `RenderingServer` equivalent functions with no luck on identifying where's the code that is responsible to focus the Editor's UI, also since there are no other's issue related to `TreeItem` then we can identify this as an Editor only issue, the issue Mostly happens with the calculation of the Control's position and size, and the appearance of another focus rect means that it was meant to focus both the Current Panel and the Current pressed UI element at same time. if it works with two focus rects in vulkan correctly then we need to use #ifdef to make Opengl3 behave differently else if it only shows one focus rect in vulkan then we need to identify why the other rect is drawing again and to fix this issue.

**Comment by HolySkyMin** [comment]
Here is MRP of the problem, which is reproduced in-game.
[MRP.zip](https://github.com/godotengine/godot/files/12499923/MRP.zip)

The problem seems to arise when `ItemList` and `Tree` (there may be more, but at least not `Button` and `LineEdit`) are inside non-main `Window`. As seen in video, focused graphic in main window is also be shown in another window. (You can even see that bugged graphic moves smoothly if you're lucky enough(?))

https://github.com/godotengine/godot/assets/30334834/f3d80d34-5feb-4540-a244-df112e0f680f

**Comment by WhalesState** [comment]
> Here is MRP of the problem, which is reproduced in-game. [MRP.zip](https://github.com/godotengine/godot/files/12499923/MRP.zip)
> 
> The problem seems to arise when `ItemList` and `Tree` (there may be more, but at least not `Button` and `LineEdit`) are inside non-main `Window`. As seen in video, focus graphic in main window is also being shown in another window. (You can even see that bugged graphic moves smoothly if you're lucky enough(?))
> 
>  weird_window.mp4

Tested this, it's only `Tree` which is causing this issue.

**Comment by WhalesState** [comment]
https://github.com/godotengine/godot/assets/53877170/45a4d4a3-7a2b-489a-9a2b-2ac35de2c5b7

**Comment by WhalesState** [comment]
check this
![image](https://github.com/godotengine/godot/assets/53877170/f9a388bb-8c0d-4439-9702-f3dad003a3c6)

after commenting the focus line, it appears to be drawing an extra panel.
![image](https://github.com/godotengine/godot/assets/53877170/310192d1-af3a-425f-9d6d-035bfd7a2c43)

**Comment by HolySkyMin** [comment]
Investigated this more and these are what I found out:

- This problem occurs at `Tree`, empty `ItemList` and empty `RichTextLabel`.
  - `ItemList` and `RichTextLabel` with contents doesn't seems to have problem.
  - `Tree`, however, behaves way more stranger. With contents, it draws another focus stylebox where `ScrollBar` was last visible when it gets resized.
- The problem is that focus stylebox is being drawn twice, first one is 'proper' drawing while second one is 'wrong'.

  ![image](https://github.com/godotengine/godot/assets/30334834/75803ce0-7082-441a-ae4b-31c5747cd83a)

  When they are empty, for some reason, it seems that when drawing focus graphic they grab main window's focused control and draw another stylebox from its position. Sometimes even the main window control's position update is applied(it happens so rerely that I couldn't record it).

  Another possible drawing position is their `ScrollBar` position.

  https://github.com/godotengine/godot/assets/30334834/57d54c48-caf7-4cdd-a812-0bf4c02375c2

  See the flickering? It's switching frame by frame between two states above! (This happens randomly so I don't know why)

  https://github.com/godotengine/godot/assets/30334834/c98e77ad-39e2-4ab3-be56-be6382fd9c23

  And `Tree` behaves like this...

These all are found in sub `Window`, but maybe it could arise even in main window when they can be resized.

Looking into the code, I found that only these controls call `RenderingServer::canvas_item_add_clip_ignore()` when drawing their focus stylebox. Maybe this could be reason?

**Comment by WhalesState** [comment]
> Looking into the code, I found that only these controls call `RenderingServer::canvas_item_add_clip_ignore()` when drawing their focus stylebox. Maybe this could be reason?

I can say yes, and those lines are needed because the ScrollContainer will clip the focus stylebox, what we can do is adding a MarginContainer inside the ScrollContainer so we can have some margins to draw the focus stylebox to avoid using those lines.

like this:
![image](https://github.com/godotengine/godot/assets/53877170/b945f78b-b799-450a-a2fc-4f89e73fdf5b)

**Comment by HolySkyMin** [comment]
> I can say yes, and those lines are needed because the `ScrollContainer` will clip the focus stylebox,

I agree. It definitely needs, and I couldn't find any logic mistakes in GUI side codes. Logically it's just adding `CLIP_IGNORE` command on and off before and after `POLYGON` command to the renderer(may be wrong considering my shallow knowledge about whole codes), and other renderers are doing this well.

So I think `RenderingServer::canvas_item_add_clip_ignore()` seems to be malfunctioning in this case. I hope someone else take a look into that because I don't have enough knowledge about rendering.

**Comment by WhalesState** [comment]
> So I think `RenderingServer::canvas_item_add_clip_ignore()` and related rendering code seems to be malfunctioning in this case. I hope someone else take a look into that because I don't have enough knowledge about rendering.

Maybe the first draw call of the Panel before applying it's local Style Boxes and position is polluting the other draw calls, if there's another way to clean the GL renderer before drawing again then it will be a good fix or we add custom content margins for Scroll Container and we allow the users to change it freely.

**Comment by filipworksdev** [comment]
Hi everyone. I am on Windows 10 and integrated Iris Xe 96EU GPU. I use Compatibility OpenGL backend. I started seeing this happen after I added a Tree into the hud.  To me it seems to happen when Tree overlaps another control. It seems to draw a border around the last overlappign control. Also strangely 3D rendering/Camera seems to affect this because the lines vanish when I point the camera in specific direction in game.
