### ISSUE TITLE
Godot 4 RC6 Animated textures crash the game and the editor.

### ISSUE THREAD

**Issue by strellydev** [godotengine/godot#74125]
### Godot version

4.0 RC6

### System information

Windows 10

### Issue description

I'm working on porting a medium size game from 3.5 to 4.0. In there, I have a menu with a small 32x32 animated icon that uses an animated texture with 6 frames.

Whenever I close the menu with that icon showing, the game crashes, if I hide the icon it works perfectly.

It seems to have to do with a shader I use to change the icon color, however I use that same shader in many places and this is the only instance of the problem.

Forgot to mention, I have another animated texture in a minigame and when the minigame ends, the game also crashes, said texture is part of a progress bar that uses a red tint, but it also crashes when resetting the tint.

IMPORTANT:
Turns out even trying to close a scene that has the animated textures on screen crashes the whole editor.

### Steps to reproduce

Use queue_free() on something that has an animated texture with a shader/part of a progress bar showing on screen.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@strellydev Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by dalexeev** [comment]
`AnimatedTexture` [was supposed to be removed](https://github.com/godotengine/godot/pull/65609#issuecomment-1250366441) in 4.0, but for some reason that didn't happen. Maybe later we will deprecate it.

**Comment by strellydev** [comment]
Wait, really? And there won't be any substitute?

**Comment by dalexeev** [comment]
I think that we will not remove `AnimatedTexture`, it will just remain deprecated. In this case, the bug will be fixed over time. But due to the `AnimatedTexture` status, you should consider alternatives:

* `Sprite2D`, `Sprite3D` or `TextureRect`. You can use `AnimationPlayer` or `Tween` for animation.
* `AnimatedSprite2D` or `AnimatedSprite3D`.
* `TileMap` supports animation.
* `CanvasItem.draw_animation_slice()` (and `CanvasItem.draw_end_animation()`). It can be useful for custom controls.
* Animation via shader (you mentioned that you are using a shader).

**Comment by strellydev** [comment]
I've been trying to create a small project that reproduces the bug with no success, so I guess it must be something else causing it, sorry. I'll close this.
