### ISSUE TITLE
Vulkan mobile: fog does not affect plain color skies even at fog_affect_sky = 1.

### ISSUE THREAD

**Issue by jcarlosrc** [godotengine/godot#74187]
### Godot version

4.0 Stable

### System information

Ubuntu 22.04

### Issue description

Setting fog_affect_sky = 1 do not have the desired effect when using a Color sky mode. It works properly if we use a procedural sky or the forward+ renderer.

![Screenshot from 2023-03-03 16-50-53](https://user-images.githubusercontent.com/8985409/222870514-0195c4cb-bbca-4e9b-bb6a-6e2a568d2f7b.png)

### Steps to reproduce

Add a sky with a plain color mode like the Clear Color default option. Enable fog and set fog_affect_sky value to 1. Sky is still not affected by fog. 

### Minimal reproduction project
[mobile_fog_sky_bug.zip](https://github.com/godotengine/godot/files/10887265/mobile_fog_sky_bug.zip)

**Comment by clayjohn** [comment]
What renderer are you using?

**Comment by Calinou** [comment]
@jcarlosrc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

**Comment by jcarlosrc** [comment]
> What renderer are you using?
Vulkan mobile.

**Comment by jcarlosrc** [comment]
> @jcarlosrc Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

I think the issue is only creating a default plain color sky and adding fog but here it goes.

[mobile_fog_sky_bug.zip](https://github.com/godotengine/godot/files/10886365/mobile_fog_sky_bug.zip)


![Screenshot from 2023-03-03 16-50-53](https://user-images.githubusercontent.com/8985409/222836667-ae9aa2b7-0d62-4799-b65e-8e700233dbbf.png)

**Comment by LRFLEW** [comment]
I encountered this bug while investigating another issue, so I can confirm this still exists in 4.1.1. Here's another minimal reproduction project (just in case): [SkyTest.zip](https://github.com/godotengine/godot/files/12135821/SkyTest.zip)

I actually happened to find the source of the bug before identifying the bug in the editor. The issue, as it turns out, is very straightforward:
https://github.com/godotengine/godot/blob/a22f495a3cdc5e48e8b2482d0838503d11baf45a/servers/rendering/renderer_rd/forward_mobile/render_forward_mobile.cpp#L803-L826
Uncommenting the commented lines resolves this issue. Why were those lines were commented in the first place? Git blame shows these lines have been commented out since the introduction of the mobile render in #47059, so this isn't a regression or anything.
