### ISSUE TITLE
Dragging a texture from the "FileSystem" resources pane on the left onto a "TestCube" node in the scene explorer should create a default material and assign the texture [prototyping essential]

### ISSUE THREAD

**Issue by etc0de** [godotengine/godot#7418]
**Operating system or device - Godot version:**
Fedora 25 x64 - v2.1.1.stable.official

**Issue description** (what happened, and what was expected):
Dragging a texture from the "FileSystem" resources pane on the left onto a "TestCube" node in the scene explorer should create a default material and assign the texture immediately. This is required for fast prototyping, because right now it seems I am expected to first create or assign a Material manually which is way too tedious to do for every test block.

**Steps to reproduce:**
(feature request)

**Link to minimal example project** (optional but very welcome):

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
