### ISSUE TITLE
[Godot 4.0] Camera2D renders the position of the previous frame.

### ISSUE THREAD

**Issue by luckyabsoluter** [godotengine/godot#74203]
### Godot version

4.0.stable.official (92bee43ad)

### System information

Windows 10, Mobile

### Issue description

[Godot 4.0] Camera2D renders the position of the previous frame.
Therefore, when Camera moves, sub-nodes moved on screen.
It is reproducted on Windows and Android.

### Steps to reproduce

# Setting
![image](https://user-images.githubusercontent.com/80892490/222315405-1e4f9b1b-cfc0-465e-8c91-d29d0d5f7c5c.png)
![image](https://user-images.githubusercontent.com/80892490/222315597-08942e80-578e-410f-9029-76f5c08a55a2.png)
# Test 1
``` GDScript
extends Camera2D

func _process(delta):
	position.x += 500
```
![image](https://user-images.githubusercontent.com/80892490/222315696-59eee31e-0e78-4d59-8b1d-97605f0853c2.png)

# Test 2

``` GDScript
extends Camera2D

var b = true
func _process(delta):
	if b :
		position.x += 500
	b = !b
```
![녹화_2023_03_02_11_32_07_920](https://user-images.githubusercontent.com/80892490/222315978-1e2e2651-12f4-4152-b977-a8059efe39af.gif)

# Test 3
``` GDScript
extends Camera2D

func _ready():
	position.x += 500
```
![image](https://user-images.githubusercontent.com/80892490/222316562-678d5a51-2645-4c23-8379-6d6de94360b6.png)

# Test 4
``` GDScript
extends Camera2D

func _ready():
	position.x += 500
	process_mode = Node.PROCESS_MODE_DISABLED
```
![image](https://user-images.githubusercontent.com/80892490/222316650-8f44ee5b-74d4-406c-8398-fdbba50e79ae.png)

### Minimal reproduction project

[camera render position issue reproduction project.zip](https://github.com/godotengine/godot/files/10867070/camera.render.position.issue.reproduction.project.zip)

**Comment by AdamGaskins** [comment]
I don't know enough to say this is the same issue as #28492, but the same solution (adding `force_update_scroll()`) worked for me. So to fix Test 1 above:

```gdscript
extends Camera2D

func _process(delta):
	position.x += 500
        force_update_scroll() # adding this line fixes the delay
```

**Comment by phantomdesvin** [comment]
I have the same issue. The force_update_scroll() workarround worked for the lerp, but not for the tweens.

**Comment by thygrrr** [comment]
Here's a reproduction project from me that cycles through all VSYNC modes.
[jittery-vsync-bug-repro.zip](https://github.com/godotengine/godot/files/13259418/jittery-vsync-bug-repro.zip)

Just hit play, it will cycle through each with 5 seconds in between each switch.

Result (tested on 60 and 120 Hz display, the bug is consistent)
- VSYNC_DISABLED: smooth ✅ 
- VSYNC_ENABLED: judders ❌ 
- VSYNC_ADAPTIVE: judders ❌ (frequency varies - perhaps wrong complement of frame time fraction used?)
- VSYNC_MAILBOX: smooth ✅ 

There are 2 objects because I had one of them calculate its own delta time from microseconds, suspecting a delta time issue - there is one, but it is unrelated to the visual judder.

## (Windows) Video of VSYNC_ENABLED, judder visible
(recorded at 8x slow motion on 120 Hz display, note the peculiar motion at 3 and 6 seconds, which almost seems like the object is jumping forward and back again; it may be an optical illusion caused by a simple frame skip, but read my theory at the end of the post)

https://github.com/godotengine/godot/assets/8904620/397d1df2-dc21-4b54-b33d-3f207c22f9f4

## (Windows) Video of VSYNC_MAILBOX, very smooth
(also 8x slow motion & 120 Hz, looks similar for VSYNC_DISABLED, including that there is never any discernible tearing which would be expected: Thus, VSYNC_DISABLED may erroneously be using a fence/semaphore somewhere in the render process or driver. However, G-Sync is turned off, and there's also no tearing on my second monitor, which is a 60 Hz non-VRR model)

https://github.com/godotengine/godot/assets/8904620/f2fd5163-07b0-4bb2-a11e-46f214497290

Interestingly, the engine-delta object (using delta from _process) will start lagging in the vsync and adaptive vsync modes (I would expect it to be ahead, or equal), yet it will mysteriously catch up when mailbox is on, or vsync is disabled. I cannot explain this, if there was a discrepancy introduced during the vsync mode switches, that error would just stay and accumulate, not go away again. (due to how the code is written - time just accumulates individually for each object, and is never reset)

You also can't record this with the builtin recorder, because that messes with delta as well.

There's also a slight amount of drift you may observe over time, which probably shouldn't be there in a perceptible fashion, either.

Not a bug: If you move the window, put it on another screen, or anything that causes delta to get frozen vs. the wall clock / Time.usec value, then it will go totally out of sync - one might argue that there either the delta or usec value is wrong in that case. This is probably due to _provess delta being clamped to a maximum value, so works as expected.

## Theory?
Perhaps an out-of-order image is submitted to the swap chain. That might explain the weird "back & forth" jitter one seems to perceive. If the "back & forth" is an optical illusion (and is only a "lag/skip" judder with catchup), then the theory would be that an image simply isn't submitted to the swap chain at all, or doesn't make it through presentation. Either assumption could also begin to explain why the wallclock (custom delta ) dependent object also jitters.

**Comment by 5ro4** [comment]
Still happening in Godot 4.2.1
