### ISSUE TITLE
Setting handle mode on bezier curve from the inspector does nothing

### ISSUE THREAD

**Issue by MrEliptik** [godotengine/godot#74224]
### Godot version

4.0.stable

### System information

Windows 10, Forward+, GTX 1070 driver 528.49

### Issue description

When trying to edit the handle mode of a bezier cruve key from the inspector tab, the mode doesn't change. It works fine when right clicking on the key and setting the handle mode from here though. 

https://user-images.githubusercontent.com/24484962/222379540-29d71b6d-ff0c-4a21-9905-9750d0581fda.mp4

### Steps to reproduce

On an animation track using a bezier curve, select a key and try to change the handle mode from the inspector tab

### Minimal reproduction project

N/A

**Comment by romlok** [comment]
For further information, from my recent experience hitting this in 4.1, when this happens Godot's outputs the error:

> core/object/undo_redo.cpp:334 - Error calling UndoRedo method operation '_bezier_track_set_key_handle_mode': 'AnimationTrackKeyEdit::_bezier_track_set_key_handle_mode': Method not found

Additionally, when changing the handle mode through the right-click menu (which does indeed work), the following error is output, twice in a row (once for each handle, maybe?):

> UndoRedo history mismatch: expected 0, got 10.
> UndoRedo history mismatch: expected 0, got 10.

**Comment by MBoqui** [comment]
It seems the bezier setter in `AnimationTrackKeyEdit::_set()` is trying to add `AnimationTrackEditor::_bezier_track_set_key_handle_mode()` on the UndoRedo but passes itself as parameter?

https://github.com/godotengine/godot/blob/c12d63556b5c1da03a00dd4c45c40e60bd8d68c2/editor/animation_track_editor.cpp#L309-L310

My hypothesis:
(not sure about this, some confirmation from someone more knowledgeable of the engine would be nice)

The call to `Animation::bezier_track_set_key_handle_mode()` cannot be made directly in `AnimationTrackKeyEdit::_set()` like the other properties because it is not bound in `Animation::_bind_methods()` and the `UndoRedo` needs a bound method . And I suppose it is not bound because `Animation::bezier_track_set_key_handle_mode()` only exists if `TOOLS_ENABLED` and that is why `AnimationTrackEditor::_bezier_track_set_key_handle_mode()` exists as a wrapper.

https://github.com/godotengine/godot/blob/c12d63556b5c1da03a00dd4c45c40e60bd8d68c2/scene/resources/animation.h#L441-L444

I have not tested this, but seems like removing that `TOOLS_ENABLED`, binding `Animation::bezier_track_set_key_handle_mode()` and removing `AnimationTrackEditor::_bezier_track_set_key_handle_mode()` would be the cleanest approach for the problem. But I don't know why that `TOOLS_ENABLED` is there or why the method is not bound.
Another solution would be to just fix the wrong reference I mentioned above, calling it from `AnimationTrackEditor` or copying the method to `AnimationTrackKeyEdit`.

By the way, `AnimationTrackMultiKeyEdit` has the same problem.
