### ISSUE TITLE
GpuParticle3D Missbehave (position, scale, color)

### ISSUE THREAD

**Issue by ciptakelvin** [godotengine/godot#74249]
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

GpuParticle3D scale, color not working on process material.
Emitting position at Global Position Vector3(0,0,0) first frame

### Steps to reproduce

1. Add GpuParticle3D
2. Create basic process material
3. Process material scale, color adjustment

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Do you have [vertex_color_use_as_albedo](https://docs.godotengine.org/en/latest/classes/class_basematerial3d.html#class-basematerial3d-property-vertex-color-use-as-albedo) enabled in the material used to render the particles?

Please see https://docs.godotengine.org/en/latest/classes/class_particleprocessmaterial.html#class-particleprocessmaterial-property-color

**Comment by Calinou** [comment]
For the scale property to work (if billboarding is enabled), Billboard must be set to **Particle Billboard** and **Billboard Keep Scale** property must also be enabled on the StandardMaterial3D used by the particles mesh.

> Emitting position at Global Position Vector3(0,0,0) first frame

See https://github.com/godotengine/godot/issues/72650.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version, with **Vertex Color > Use As Albedo** and **Billboard Keep Scale** enabled on the BaseMaterial3D used by the mesh rendered in the particles node.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
