### ISSUE TITLE
Justifying text in RichTextLabel

### ISSUE THREAD

**Issue by VoidSpirit1978** [godotengine/godot#74359]
### Godot version

4.0 Stable

### System information

Windows 7

### Issue description

Using BBCodes in RichTextLabel and setting text justifying to "fill" i have a justified text in single-line paragraphs although this line must be justified as last. Also words delimited by '-' have a unnecessary space
![RichTextLabel](https://user-images.githubusercontent.com/126967156/222907858-e636da01-6b64-4b29-b5c8-365ebca534c0.png)

### Steps to reproduce

Create RichTextLabel, set BBCodes on, enter short text with [fill]...[/fill] tags. If text has single line described effect will appear

### Minimal reproduction project

N/A

**Comment by shadowfox87** [comment]
This isn't yet fixed. If the first line of a sentence is short and then you have a line break, that sentence should not be justified because then the words will just have a lot of space between them. Thus, it should be able to detect line breaks and justify the paragraph after the line break. We should be able to specify which parts of the text we want left/right aligned and what should be justified. You can do this in any word editing software so we should be able to the same. The key here is able to detect the line breaks.

**Comment by Calinou** [comment]
@shadowfox87 Please open a new issue with a minimal reproduction project attached.
