### ISSUE TITLE
Project Settings UI improvement idea

### ISSUE THREAD

**Issue by Keetz** [godotengine/godot#7437]
Just an idea to improve the property list in Project Settings i got when writing #7435

It would be nice to separate the properties in two categories:

- Standard/Built in properties
- Custom properties

I am thinking of something similar to how Input Map actions are shown.
![project_settings](https://cloud.githubusercontent.com/assets/6707330/21683399/7eb63166-d359-11e6-9486-674292daeeaa.png)

Where the "ui_accept" would just be a header, "Properties", and "ui_select" would be "Custom Properties" and the keys are how the properties should be listed.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1

**Comment by Calinou** [comment]
See also #22099.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
