### ISSUE TITLE
Fix suggested by STATIC_CALLED_ON_INSTANCE warning is incorrect

### ISSUE THREAD

**Issue by Pennycook** [godotengine/godot#74397]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Steam OS Holo, Steam Deck

### Issue description

The STATIC_CALLED_ON_INSTANCE warning includes a suggested fix, which only applies when the static function is defined in the base class.  Attempting to follow the suggestion blindly (which novice programmers may do) causes an error.

**Test.gd**:
```gdscript
extends Node

static func foo():
	pass

func _process(delta):
	foo()
```

The warning printed by Godot in the case above is as follows, even though `Node.foo()` doesn't exist:
```
W 0:00:00:0454   The function 'foo()' is a static function but was called from an instance. Instead, it should be directly called from the type: 'Node.foo()'.
  <GDScript Error>STATIC_CALLED_ON_INSTANCE
  <GDScript Source>Test.gd:7
```

It's not clear to me what the correct fix is in this case, because the script doesn't provide a class name.  But it's worth noting that the STATIC_CALLED_ON_INSTANCE warning is unchanged by defining a `class_name`.

I suspect this may be a case where it's hard to print an accurate and reliable suggestion.  Maybe it would be better to phrase it as an example, instead, and not try to detect the base class?
```
W 0:00:00:0454   The function 'foo()' is a static function but was called from an instance. Instead, it should be directly called from the type, for example: 'Type.foo()'.
  <GDScript Error>STATIC_CALLED_ON_INSTANCE
  <GDScript Source>Test.gd:7
```

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by thornySoap** [comment]
Without a `class_name` one would probably have to do `preload("res://path/to/class.gd").foo()`.

**Comment by over-vault** [comment]
Still present in 4.0.1. It uses the base class even if `class_name` is provided

**Comment by TomCatFort** [comment]
This is quite problematic if the script in question does not have a `class_name` set.
Without `class_name`, there is no good way to refer to the class itself.
Using `preload("res://path/to/class.gd")` feels very hack like to me.
Maybe this could be solved by introducing a keyword to refer to the class itself, something like `Self.foo()` maybe.

But looks like, at least this warning can be ignored on the project settings level:
`debug/gdscript/warnings/static_called_on_instance`

**Comment by TomCatFort** [comment]
> It doesn't seem like there's any good way to tell a developer how to fix their code.

Does the code actually needs fixing in the first place?
The code you posted in your original comment works correctly.
The engine correctly identifies the static function, and calls it successfully.

Why is it even a warning to call a static function without specifying the type?
Especially as the type does not always exists, and forcing the type to be present can not be correctly done for all valid cases.
As I stated before, the `preload` seems like a hack, and the extra resource paths introduced makes refactoring more difficult if the script is moved in the file system.
And adding a `class_name` needlessly pollutes the global namespace, which I would say is even worse.

If the type can not be specified, and any solution leads to a worse code, then issuing the warning itself is actually the problem.
This could be solved by the following ways:
 - Introduce a way to always be able to refer to the type of the current class (E.g.: `Self` keyword).
   But introducing a new keyword is not an easy task, and it would probably needs a dedicated discussion on it.
 - Do not issue the warning if the correct type can not be specified.
   This leads to the question: Why do we want the developer to use the type if available, otherwise being OK with it.
 - Remove this warning type altogether.


> Does anybody see a problem with that? If not, I'll open a PR.

This would make the situation better but the underlying issues would still remain.
The developer would try to look for a good solution while there is none, wasting time and energy, leading to bad user experience.

**Comment by craigostrin** [comment]
I just ran into this and I'm also confused why it's an error in the first place.

My situation is basically:

**Foo.gd** (autoload)

```
extends Node

static func foo():
	pass
```

**Bar.gd**
```
extends Node

func _ready():
    Foo.foo()
```

It seems to work as intended. And it's not like I need a `class_name` because that's what the autoload is already doing. So what's the point of the error?

**Comment by Pennycook** [comment]
> Does the code actually needs fixing in the first place? The code you posted in your original comment works correctly. The engine correctly identifies the static function, and calls it successfully.
> 
> Why is it even a warning to call a static function without specifying the type? 

I think it is bad practice.  The code works, but because the function is static it could be doing something that the user did not intend.  Maybe the developer is calling the static function for every instance of an object (but the developer who wrote the class intended for them to call it once), or the developer thinks they're modifying an instance (but they're not).

I think this is why it is a warning and not an error -- Godot is encouraging the developer to take a second look at the line, not necessarily to correct it.  The warnings about integer division, etc, have similar behavior.

This is why I'm focusing on what the warning says rather than why it exists.  I agree that developers should take a second look at code that calls static functions from an instance.  But following the advice in a warning shouldn't make the situation worse, and definitely shouldn't lead to an error -- that's a bad user experience.

> This would make the situation better but the underlying issues would still remain. The developer would try to look for a good solution while there is none, wasting time and energy, leading to bad user experience.

I disagree that there is no good solution.  I agree there is no _universally_ good solution, but there are solutions.  Adding a `class_name` or using `@warning_ignore` might be good solutions, depending on the codebase.


> It seems to work as intended. And it's not like I need a class_name because that's what the autoload is already doing. So what's the point of the error?

@craigostrin: It's not an error, it's a warning.  You don't have to fix it unless you want to.

I personally think in your case the warning might be helpful.  If all the functions in `Foo` are static, then you might not need an autoload.  If there's only one instance of `Foo` in the scene tree, the function probably doesn't need to be `static`.  I don't think these features are the same: `static` makes functions available without an instance of the class, and autoload automatically adds an instance of the class to every scene.

**Comment by awardell** [comment]
At some point this issue has worsened. Now, if you do this to try to appease the warnings:
```
class_name NameOfClass
extends Node

static func foo():
	pass

func _process(delta):
	NameOfClass.foo()
```

you get this fun compiler error:
`res://name_of_class.gd:9 - Compile Error: Identifier not found: NameOfClass`

Is this a bug of it's own or expected? Someone tell me. But it makes the warnings extra annoying.

No idea when it sprung up, but I'm on v4.2.beta.custom_build [09946f79b]

Anyways, honestly, the warning should be done away with for classes calling their own static functions. No other language that I know of spits a warning if you do that. It's generally actually the expected usage.

>The code works, but because the function is static it could be doing something that the user did not intend

What, exactly, can a static function do that an instance function cannot? I understand warning or even disallowing static functions called from instance variables: the user probably intended to do something to or retrieve some value from the instance. But calling a static function from its own class without a qualifier? What danger could that even pose if a programmer thought they were calling an instanced function? It will likely still do exactly what they intended, unless the static function was very poorly designed and documented in the first place.
