### ISSUE TITLE
export enum as flags not possible in 4.0 stable

### ISSUE THREAD

**Issue by Byteron** [godotengine/godot#74418]
### Godot version

4.0 stable

### System information

Windows 11

### Issue description

In Godot 3 it was possible to export enums as flags.
This does not seem to be possible anymore in Godot 4
![image](https://user-images.githubusercontent.com/24433899/222946111-79be31a2-e443-4d0a-9d11-2b7607b50bd6.png)

### Steps to reproduce

-

### Minimal reproduction project

-

**Comment by nonchip** [comment]
meta note: possible dupe of #71234, where it was decided this should be a proposal despite technically qualifying as a regression (`export(Enum, FLAGS)` existed).

my 2 cents:

the exports are actually fine, analogous `@export var name: Enum` and `@export_enum("option1",...)`.
but to make behaviour as expected, we ideally should have:

* a new `enum_flags` keyword, that just defaults to powers-of-two instead of incrementing.
* `@export var name: Enum` working as before, *but* either detecting whether the enum was created with `enum_flags`, or whether it only consists of powers-of-two, and then generating flag checkboxes instead of a one-choice dropdown
* `@export_flags("flag1",...)` working as before

**Comment by Byteron** [comment]
I saw the bit about this being a feature proposal.
However, given that 1) this was already possible in 3.5 and 2) this IS possible in Godot 4 when using C#, this indeed rather seems to be a regression to me.
![image](https://user-images.githubusercontent.com/24433899/222946727-4b51396c-bf3e-4062-b18c-d526e1d02d79.png)

![image](https://user-images.githubusercontent.com/24433899/222946698-5e423dba-ec9a-466e-87aa-b484bd7bce8d.png)

**Comment by YuriSizov** [comment]
This is indeed a duplicate of the linked issue. The reason why it should be a proposal is because it needs a qualified suggestion for the new syntax. The old syntax is gone, and in the new one this feature was not implemented. But there are several ways to do it, so a good proposal should be created that can argue which way should be used and why.

Note that the engine supports flags differently now, and GDScript is more aware of enums too. Flags should provide type safety, for example, and not just filter the inspector widget. So this needs to be implemented as a new feature, with the new system in mind.

You can still use the verbose path of get property list in any scripting language.

**Comment by JJBocanegra** [comment]
> You can still use the verbose path of get property list in any scripting language.

@YuriSizov Can you provide with an example? I'm a beginner with Godot and GDScript and I'm trying to understand how to do this in Godot 4.0

**Comment by dalexeev** [comment]
See [Advanced exports](https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/gdscript_exports.html#advanced-exports) (this option is still applicable in 4.0).

**Comment by nonchip** [comment]
@YuriSizov 
> Note that the engine supports flags differently now, and GDScript is more aware of enums too. Flags should provide type safety, for example

could you maybe elaborate on that? i don't see a `Variant.Type.TYPE_ENUM/FLAG` for example (and property hints don't have anything to do with types after all), the current version of what @dalexeev linked doesn't seem to help with the problem at hand (it's just a *more* complicated way of abusing `@export_flags` by declaring the same unnecessary hints *more* manually), and also https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#enums (and the compiler, for that matter) still seem to disagree that enums are anything more than an `int` with some named constants and *sometimes* a hint if exported correctly (which this is essentially about)?
or was that part of a possible "requested" feature of "redesign enums/flags" as opposed to the regression fix of "just follow the already established patterns to their conclusion and allow to @export all enums"?

**Comment by dalexeev** [comment]
* See also https://github.com/godotengine/godot/issues/71234#issuecomment-1430763393

There are several options for how this can be implemented: as a separate annotation, as an annotation parameter, as a new enum syntax, etc.

This is not a bug. Yes, this is lost in the transition 3 -> 4, but it cannot be restored in the old form. Therefore, a feature proposal is needed.

**Comment by YuriSizov** [comment]
@JJBocanegra I am talking about using `_get_property_list`, an advanced mechanism for defining class properties. It can be used to export more stuff to the inspector too using a low-level syntax, which is much more powerful and versatile. See the link from @dalexeev's comment for how to use it.

You would want to define a property with the `PROPERTY_HINT_FLAGS` hint, and you will need to convert your enum to a string dynamically, so it looks something like this `"Fill:1,Expand:2,Shrink Center:4,Shrink End:8"` in the hint string. I have [this method](https://github.com/YuriSizov/godot-pathways/blob/master/addons/pathways/utils/ExportUtils.gd) for achieving this in 3.x, but it may not work with 4.0. Should be still possible to do something similar, though, so it's all done dynamically and not manually.

**Comment by RudyFisher7** [comment]
I see this is old but is this really not going to be a thing? It seems weird that 3.5 had this then 4.x doesn't. It would be very useful to be able to just export an enum as bitflags in the editor.

**Comment by ArtyIF** [comment]
There is a pattern I use in my project where having an ability to export enum as flags is useful. I have a typed dictionary which has NodePaths for keys and bitflags as values. Currently, they're implemented like this:

```gdscript
enum WheelFlag {
	Steer = 1 << 0,
	Drive = 1 << 1,
	Handbrake = 1 << 2,
}
@export_custom(PROPERTY_HINT_DICTIONARY_TYPE, "22/26:CarWheelSuspension;2/6:Steer,Drive,Handbrake") var wheel_flags: Dictionary[NodePath, WheelFlag] = {}
```

There's a hard-to-read hint string where I have to duplicate the flag values to. Also, I have to use NodePath instead of the desired object type directly, otherwise either the editor crashes or the keys are saved weirdly.

Instead, if I were to be able to tag the enum as flags similar to how it's possible in C#, I could do something like this:

```gdscript
@export_flags enum WheelFlag {
	Steer = 1 << 0,
	Drive = 1 << 1,
	Handbrake = 1 << 2,
}
@export var wheel_flags: Dictionary[CarWheelSuspension, WheelFlag] = {}
```

This code is much more readable, and I can use the desired type directly, which will be stored in the scene file as a NodePath, without any hint string shenanigans.

**Comment by dalexeev** [comment]
> There's a hard-to-read hint string where I have to duplicate the flag values to.

You can assign the hint string to a constant and reuse it, since annotation arguments support constant expressions.

As for exporting flag bitmasks, I would suggest the following:

```gdscript
enum WheelFlag {
    Steer = 1 << 0,
    Drive = 1 << 1,
    Handbrake = 1 << 2,
}

@export var single_item: WheelFlag
@export var bitmask: BitField[WheelFlag]
@export var bitmasks: Array[BitField[WheelFlag]]
@export var bitmask_map: Dictionary[KeyType, BitField[WheelFlag]]
```

**Comment by lolpie244** [comment]
I think a possible and easy workaround is to use `Array[Flag]`:

<img width="625" height="214" alt="Image" src="https://github.com/user-attachments/assets/2eff899a-27a1-4b2c-8f25-7691b1461731" />

```gdscript
enum Flags {
	WALL = 1 << 0,
	WALKABLE = 1 << 1,
}

@export var properties: Array[Tile.Flags] = []
var _flags: int = 0

func _ready():
    for property in properties:
        _flags |= property
```

**Comment by djwebsystems** [comment]
I like ArtyIF's proposal.  Alternatively, `@enum_flags()` currently takes a variable number of strings.  Could we just add an overload that takes an `enum` type?  Something like:

```gdscript
enum Fruit {
	NONE = 0x00,
	APPLES = 0x01,
	ORANGES = 0x02,
	PINEAPPLES = 0x04
}

@export_flags(Fruit) var selected_fruit
```

**Comment by djwebsystems** [comment]
In hind sight, I see issues if the flag values in my proposal are not a power of two.  I suppose it could be enforce by Godot?
