### ISSUE TITLE
ResourceLoader.has() uses localized paths, but Resource.set_path()/take_over_path() don't.

### ISSUE THREAD

**Issue by Ovnuniarchos** [godotengine/godot#7442]
On commit 0f7af4ea51744cda23c4d3c7481f9c332973d1d4 this is still true.
When setting the path for a resource, the path does not get localized, making future calls to has() return false unless the path is localized before setting.
Is this correct behaviour?

**Comment by bojidar-bg** [comment]
Related to #6153?

**Comment by Calinou** [comment]
Can anyone still reproduce this in Godot 3.2.1 or 3.2.2beta4?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug.

PS: If no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
