### ISSUE TITLE
Focus focus color is replaced by font hover color

### ISSUE THREAD

**Issue by rafaelcastrocouto** [godotengine/godot#74489]
### Godot version

v4.0.stable.official [92bee43ad]

### System information

Windows 10

### Issue description

Focus color (and styles) should always override hover colors (and styles)
I was expecting 4.0 to fix this since the 'Theme overrides' panel has been updated but the hover color still will replace the focus color. This creates confusion when changing focus and is definitely an accessibility issue.

### Steps to reproduce

1. create a button
1. add a custom focus color 
1. add a custom hover color 
1. run and check the behavior

### Minimal reproduction project

https://github.com/rafaelcastrocouto/RichTextLabel

zip file: [RichTextLabel-main.zip](https://github.com/godotengine/godot/files/10898447/RichTextLabel-main.zip)

**Comment by rafaelcastrocouto** [comment]
Seems like the problem lies on the button.cpp file, I'll try my best to make a PR to fix this.
https://github.com/godotengine/godot/blob/master/scene/gui/button.cpp#L130

**Comment by YuriSizov** [comment]
Please make a proposal if you think the current rendering logic of control nodes need to be updated, explaining your use case.

I am also not sure what the theme overrides section has to do with anything.

**Comment by rafaelcastrocouto** [comment]
The case is the same that lead to the addition of new states in 4.0 (like hover_pressed). There are cases where focused + hovered need their own styles (specially when the button has no background).

The theme override panel is the fatest way to check this behavior without getting into 'theme territory'.

If you don't understand you could just ask, or wait in silence and check a possible future PR, but u went straight to closing it, really? That's beyond rude, I mean, not even waiting for some feedback or an attempt of a solution.

I have no idea why you would go on with this behavior but that sure is way too far from the open source mentality.

If the issue had a negative feedback your attitude would make sense but this .. OMFG.

**Comment by YuriSizov** [comment]
I asked you to open a proposal because this is not something that fits a bug report.

The part I didn't understand is not relevant to the proposed change. You can do the same in Godot 3 and theme overrides there. Nothing changed about it, so I was confused why you thought there were any changes.

**Comment by YuriSizov** [comment]
I'm sure you can "win" this verbal argument, but I'm still asking you to follow the procedures of this project. Opening a [proposal](https://github.com/godotengine/godot-proposals) does not in any way diminish the issue at hand, but it allows you to explain in a more formal way why this matters and what steps are needed to improve the situation. And you can still make a PR if you so desire.

Following instructions of open source maintainers helps us keep the workflows of the project organized and actionable. Listening to feedback from maintainers helps you make successful contributions. My request was simple, but requests made during the review process can be much more complex, so I would urge you to find it in yourself to cooperate with us instead of creating a pointless conflict. Thank you for your understanding.

**Comment by rafaelcastrocouto** [comment]
1. This is not about making a PR, anyone can do it at any time and that is common knowledge;
1. This is not about following the procedures of this project since this is not a feature proposal and the [guidelines](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md) are pretty clear about it;
1. This is not about creating a proposal, I would do it happily as I've done before (although it would make little sense to create a proposal asking if we should follow basic accessibility standards);
1. This is not about organizing the "workflow" of the project since making a proposal issue would result in exactly the same environment for discussions.
1. This is not about winning an argument, imho we all lost here when a single person decides to take action without understanding the context and harshly pushes away new contributors. 
 
This is about empathy, about treating others with respect, about not being rude and about not taking decisions without the minimal community participation. You might close a bunch of issues every day but some of us spend a couple of hours making sure we are not making a mistake ourselves, and creating clear projects to assure it's an issue and going through the code to try to spot where it can be fixed.

I'm not claiming that I'm "right" and this issue should be fixed, I'm claiming that u handled this the worse way I can expect from an open source project member.

I'm unsubscribing from this issue so there's no reason to waste your time with a response, instead go back through your [own thoughts](https://humnom.net/thoughts.html?id=5ed130ed-tone-of-your-writing-voice) and try to be mindful not only about your tone, but also about your attitudes.

**Comment by akien-mga** [comment]
So, it was made clear to you that the current behavior is _not considered a bug_, and thus your proposal to change the current behavior is... a proposal. The guidelines you linked make it clear that proposals should be filed in https://github.com/godotengine/godot-proposals/issues

The issue was therefore closed, not to silence you, but to encourage opening one that follows our guidelines. You may not agree with our guidelines, and it's totally fine if you don't want to do this extra work, but we're the ones defining what workflow lets us handle one of the absolute most active repositories on GitHub, not you.

Sure, @YuriSizov could have worded his first comment a bit better to clarify why the current behavior is expected and why what you report is therefore not a bug. Sometimes we can't afford to spend too much time on each issue though, and we believe that a quick answer that redirects you in the correct direction is better than no answer because we're too busy.

Now, since you're starting to dig up writings from a contributor on their personal blog to try to make an argument against them, and this is toxic behavior clearly against our [Code of Conduct](https://godotengine.org/code-of-conduct), I decided to exclude you from further interactions in the @godotengine organization for 1 week.
