### ISSUE TITLE
Consistent order of Property sections in the Inspector view

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#7450]
We spend a lot of time looking for the value we need to change in the Inspector because the order is changing depending on the Node you select. So if you want to change the Opacity it's placed on top in Node2d but in the Label node its at the bottom. It cost time when you have to look in different places for the values you need. In Cocos Creator and Unity they have placed "the most important" properties at the top and they never move. 

**Solution: We suggest to always have the transform and opacity properties at the top in the inspector**

Example:
![godotconsistentui](https://cloud.githubusercontent.com/assets/24936603/21721076/dcafefaa-d426-11e6-8cbb-9afa2a2f2fc4.jpg)

/Sorry for bulk adding issues, but we have been collecting a bit :)

**Comment by uldall** [comment]
I think what this suggests is to reverse the ordering of the sections. I.e. have "Node" at the top, "CanvasItem" second and so on. I think this makes a lot of sense.

**Comment by ClikCode** [comment]
I think they were only suggesting:

**Comment by jesperkondrup** [comment]
Yes, Uldall is right, it's the order of properties that should stay the same.

The example below is from Cocos Creator. I really like how the Node properties stays on top for all types of nodes. So you always have "the most important" properties in the same place and you don't have to look for them in different places. This saves a lot of time, especially when animating.

![godotnodeplacement](https://cloud.githubusercontent.com/assets/24936603/22154493/10572732-df2c-11e6-8c1e-3ecd9d64729d.jpg)

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1

IMO the upper properties are more specialised (by class inheritance) and deserve their place at the top

**Comment by jesperkondrup** [comment]
Yes it's still relevant in 3.1

**Comment by akien-mga** [comment]
For the reference, I prefer the order as it is now. The node's most specialized parent classes (and especially the node's main class) should be towards the top, as they include the values that one most needs to interact with for most node types.

Properties like transform and visibility are the exception that confirms the rule, but I wouldn't reverse the order just for their sake.

Still, if there's a lot of support for such a proposal in the proposals repo, it could be added as an editor setting I guess.

----

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
