### ISSUE TITLE
TextureRect resets rect_rotation under container after visibility change

### ISSUE THREAD

**Issue by RikKargones** [godotengine/godot#74602]
### Godot version

Godot 3.5.1 Stable

### System information

Windows 7

### Issue description

Issue described in title. Maybe it's intended (because Containers control it's childs), but looks buggy.

### Steps to reproduce

1) Make scene with any Container and TextureRect under this Container:

> Container
> -TextureRect

2) Add texture to TextureRect.
3) Add any code to rotate and hide/show TextureRect.
4) In-game, rotate TextureRect and then hide it.
5) Show TextureRect and see results.

### Minimal reproduction project

Archive contains project files (not folder with them!), make sure to unpack into empty folder.
[BUGGER.zip](https://github.com/godotengine/godot/files/10920495/BUGGER.zip)

**Comment by YuriSizov** [comment]
That's normal and expected behavior. Containers control position and size of their children, that's their main purpose. Rotation and scale are reset in the process. If you want to animate controls under containers, you need to do use intermediate controls as children of containers and anchor points for other nodes.
