### ISSUE TITLE
Incorrect font rendering despite disabling Subpixel Positioning

### ISSUE THREAD

**Issue by 20milliliter** [godotengine/godot#74694]
### Godot version

4.0.stable

### System information

Windows 10, Forward+, NVIDIA Studio 527.56

### Issue description

A pixel font is being rendered incorrectly despite disabling Subpixel Positioning. (#70327)

![image](https://user-images.githubusercontent.com/107726700/224184845-44ddd330-612d-4bf6-b890-3b71bcf37f13.png)
*image is exact size

### Steps to reproduce

The minimal reproduction project shows various sizes of the font, comparing their appearance in engine and how they are supposed to look (via a keep size texture rect containing an image created seperately).

The left column shows the text in engine, the right shows the texture rects.
The font sizes from top to bottom are 12, 16, 24, 32, and 36.

### Minimal reproduction project

[Bug.zip](https://github.com/godotengine/godot/files/10937180/Bug.zip)

**Comment by xahon** [comment]
I have an issue with font rendering as well.
On the left is rendered text in Godot (10px size) and on the right default Windows 10 font viewer
![image](https://user-images.githubusercontent.com/18731681/226298541-ffe7b25f-fe18-4fd1-ad38-6940b85d4443.png)

I've tried different import options. I use these options now because it looks the best of all other setting sets
![image](https://user-images.githubusercontent.com/18731681/226298938-af269053-7a12-4573-b5c3-cac9756fbb75.png)

The UI control and all it's parents are not scaled (1, 1, 1)

---

Here is an SDF approach. On the left is how it looks like in the editor, on the right how it looks in the game

![image](https://user-images.githubusercontent.com/18731681/226306129-183d2b72-6920-4f52-b20a-c6bb8d820d93.png)

I've tried different MSDF settings, it still looks awful

It worth noting that I use fixed viewport size and window override. Both have the same aspect ratio.

**Comment by Calinou** [comment]
This is not a bug; this occurs because you're displaying the font at a non-integer multiple. Pixel art fonts **must** be displayed at a multiple of the size they were designed for to look correct.

For example, if I enable antialiasing, notice how all fonts turn blurry *except* the ones that are a multiple of the intended size (16 and 32):

![image](https://github.com/godotengine/godot/assets/180032/a1f48518-f6e0-42db-bd34-e8f295d24df2)

Unifont is designed for size 16.

**Comment by thornySoap** [comment]
But isn't the size correct?:

![Screenshot 2023-05-15 17:28:07](https://github.com/godotengine/godot/assets/115401023/4b2b696d-3b61-4f38-ba00-53d69b92aa49)

**Comment by thornySoap** [comment]
@Calinou this is with stretch mode disabled:

![Screenshot 2023-05-15 17:28:07](https://github.com/godotengine/godot/assets/115401023/23272888-19a1-4c75-9a6c-1be497ce5d7d)

[test.zip](https://github.com/godotengine/godot/files/11479977/test.zip)

**Comment by Calinou** [comment]
@thornySoap You have subpixel positioning set to **Auto** in the Import dock. Set it to disabled, click **Reimport** then use **Scene > Reload Saved Scene**.

**Comment by thornySoap** [comment]
@Calinou thank you yery much. Sorry for having annoyed you with that 😣

**Comment by 20milliliter** [comment]
>Unifont is designed for size 16.

@Calinou How do you know? 
Why does other software disagree with you?

![image](https://github.com/godotengine/godot/assets/107726700/cf98aa9f-1d0e-4591-9842-781ea86031e6)
![image](https://github.com/godotengine/godot/assets/107726700/1158422a-81b7-4037-b129-ba5685808554)

**Comment by Calinou** [comment]
12 pt is different from 16px :)

Different software uses different coventions for font sizes, so it's best to try different font sizes until you find one that looks "right".

**Comment by 20milliliter** [comment]
What convention does Godot use?

**Comment by 20milliliter** [comment]
> Different software uses different coventions for font sizes

TIL. Very unintuitive.
@Calinou Mention of this should also be included in your PR, I feel.

**Comment by Calinou** [comment]
> @Calinou Mention of this should also be included in your PR, I feel.

Done :slightly_smiling_face:

**Comment by 20milliliter** [comment]
Great, thanks so much.
