### ISSUE TITLE
The complete value should be visible in the property box.

### ISSUE THREAD

**Issue by jesperkondrup** [godotengine/godot#7479]
Often I find that I am not able to see the complete value in the some what small property box when I have to edit the value. Even if I change the inspector window to a very large size, the property box does not scale along with window, so I still can't see all the numbers. Unity and Cocos Creator have very large property boxes which makes it easier to edit the values.

**Solution: The property box should be larger and perhaps look at the size of the inspector, so it can scale along with it.** 

This solution would also fix the tiny issue that you cannot drag select the complete value in the property box if you select from right to left.

![godotvalueboxes](https://cloud.githubusercontent.com/assets/24936603/21760897/c9295cca-d64f-11e6-9067-812a184a91a4.jpg)

**Comment by bojidar-bg** [comment]
I think this is a duplicate of the problem in #7133, even if it proposes a different solution.

**Comment by Noshyaar** [comment]
Still reproducible/relevant in 3.1 master 48890b1

**Comment by jesperkondrup** [comment]
Still relevant in 3.1

**Comment by MelvinWM** [comment]
@jesperkondrup I believe this issue is no longer relevant in the most recent version of 3.1, see for instance:

![godot_inspector_2019-03-14_example1](https://user-images.githubusercontent.com/26661991/54446185-aac79480-4746-11e9-8933-ff3a9eabf164.png)

and

![godot_inspector_2019-03-14_example2](https://user-images.githubusercontent.com/26661991/54446187-aac79480-4746-11e9-92e9-7ef142d22e5c.png)

. Can you confirm?

**Comment by jesperkondrup** [comment]
@MelvinWM yes it seems like you are right :)
