### ISSUE TITLE
RigidBody in character mode 

### ISSUE THREAD

**Issue by Desagiato** [godotengine/godot#74815]
### Godot version

3.5.1

### System information

Ubuntu 22.04

### Issue description

can't move with move and slide or add force, i can move in with set translation but it don't collide , there is someone that have create some custom move and slide for doing that?

### Steps to reproduce

we set the rigidbody on character mode in order to continue to detect collisions (with kinematic body it doesn't work)
mode=RigidBody.MODE_CHARACTER

### Minimal reproduction project

just set rigidbody to character and try to move and slide it

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/65808.

With Lock Rotation options, do you even need to switch to character mode?

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
