### ISSUE TITLE
Dictionary syntax error assumes LUA knowledge

### ISSUE THREAD

**Issue by QbieShay** [godotengine/godot#74821]
### Godot version

4.0 stable

### System information

Fedora, RX 590

### Issue description

I made a dictionary, and instead of using `:` to separate between key and value, i accidentally used `=`.
The error message was not clear at all `Parse Error: Expected identifier or string as LUA-style dictionary key.` 

I don't think assuming that people know how dictionaries are made in LUA is reasonable. And if this is not about LUA the programming language, i don't even know what this is about :D

I think this error should be replaced with something of the sort "Please use `:` as separator instead of `=` in your dictionary"

### Steps to reproduce

Paste this code in a script:

```

var dict = {
	1 = "lala"
}
```

Observe the error message
![image](https://user-images.githubusercontent.com/7917475/224549538-38ea25aa-ba75-431e-868b-0733a53b90ad.png)

### Minimal reproduction project

see above

**Comment by adamscott** [comment]
> I think this error should be replaced with something of the sort "Please use `:` as separator instead of `=` in your dictionary"

[GDScript supports both styles](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#dictionary). So it would be a breaking change to ask the user to use `:` as separator instead of `=`. But yeah, it's pretty enigmatic for newcomers and for people who doesn't know about the Lua-style.
