### ISSUE TITLE
Signal parameter type is always considered Object in signal connection dialog in C# (but not in GDScript)

### ISSUE THREAD

**Issue by ChloePrime** [godotengine/godot#74862]
### Godot version

4.0-stable_mono_win64

### System information

Windows 11 22H2

### Issue description

> 
![Script](https://user-images.githubusercontent.com/43518523/224719220-9ab4a56c-2e9c-4c1b-bebe-d62eb23e372b.png)
![Bug](https://user-images.githubusercontent.com/43518523/224719256-34436394-6d89-4a2e-a588-f9f11ae06ea1.png)
Expected: The parameter type of OnChildEnteredTree (underlined) in the dialog is Node, not Object.

### Steps to reproduce

1. Write a public (signal listener) C# function with a Node parameter.
2. Build .NET project.
3. Try to connect some suitable signal (e.g. "child_entered_tree") to that function, and it won't appear in the Pick dialog if `Compatible Methods Only` is on.

### Minimal reproduction project

[SignalParamBug.zip](https://github.com/godotengine/godot/files/10958019/SignalParamBug.zip)

**Comment by Calinou** [comment]
This works in GDScript in comparison (tested in 4.0.stable on Linux):

![image](https://user-images.githubusercontent.com/180032/226740665-457b162d-9f01-48fc-b17d-4ac3c9518f35.png)

**Comment by raulsntos** [comment]
It's true that C# is not reporting the correct parameter types for script methods. However, I feel like this particular example should work because the method parameter type (`Object`) is less specific than the signal parameter type (`Node`). Since a `Node` can be casted to `Object`, it should be considered a compatible method in my opinion.

I think the issue is that the method filter in the _Select Method_ dialog is only comparing exact class names:

https://github.com/godotengine/godot/blob/fa268be823b97095245f731ad59335a935e6b0ba/editor/connections_dialog.cpp#L306

It should probably also check if the signal parameter type (`E->get().class_name`) is a derived type from the method parameter type (`F->get().class_name`).

As for the C# issue, when the dialog retrieves the `MethodInfo` list from a CSharpScript, the `PropertyInfo`s we create for the method parameters don't set the `PropertyInfo.class_name` which is what's being used here for the comparison.

https://github.com/godotengine/godot/blob/fa268be823b97095245f731ad59335a935e6b0ba/modules/mono/csharp_script.cpp#L2320-L2323

This dictionary is populated in C# by calling the `GetGodotMethodList` method that is generated for every Godot type by the ScriptMethodsGenerator.
