### ISSUE TITLE
Scene cannot connect to any of its methods in GODOT 4 .NET after upgrading my Godot 3 project 

### ISSUE THREAD

**Issue by fahadTheTechIdea** [godotengine/godot#74864]
### Godot version

4 stable

### System information

windows 11

### Issue description

Scene cannot connect to any of its methods in GODOT 4 .NET , after upgrading my Godot 3 project any idea's I think the Scene 
I think it cannot see the C# script file.
if Detach and Add a GD Script file it works fine.

cannot see the C# script at all E 0:00:02:0190 emit_signalp: Error calling from signal 'pressed' to callable: 'Control(OptionMenuControl.cs)::onNewButton_pressed': Method not found. <C++ Source> core/object/object.cpp:1058 @ emit_signalp()

### Steps to reproduce

upgraded a godot 3  mono c# project

### Minimal reproduction project

[minimalproject.zip](https://github.com/godotengine/godot/files/10958360/minimalproject.zip)

**Comment by RedworkDE** [comment]
1. The project does not contain a C# project, create it with the `Tools > C# > Create C# Solution` menu item
2. The C# code references various missing code and thus does not compile, hopefully just an issue with your MRP
3. And the only actual bug I found: the `config/use_hidden_project_data_directory` project settings must be enabled for C# projects and things break otherwise.

**Comment by AThousandShips** [comment]
Closing as per above and due to lack of response, if you provide the requested information this can be reopened
