### ISSUE TITLE
magins in new tscn files

### ISSUE THREAD

**Issue by GrandFunkR** [godotengine/godot#7486]
**Operating system or device - Godot version:**
linux - godot 3.0-alpha

**Issue description** (what happened, and what was expected):
opening an existing project with latest godot, margins are lost
I saw that in the new tscn files  margins are referred as:
margin_top
margin_left
...

So I changed every 
margin/
to:
margin_ 

in my tscn files
and this seems to works

**Steps to reproduce:**
open an existing project with latest godot, margins are lost

**Link to minimal example project** (optional but very welcome):

**Comment by reduz** [comment]
Yes, this is intended, opening existing projects in HEAD is not expected to
work

On Jan 9, 2017 6:28 PM, "GrandFunkR" <notifications@github.com> wrote:

*Operating system or device - Godot version:*
linux - godot 3.0-alpha

*Issue description* (what happened, and what was expected):
opening an existing project with latest godot, margins are lost
I saw that in the new tscn files margins are referred as:
margin_top
margin_left
...

So I changed every
margin/
to:
margin_

in my tscn files
and this seems to works

*Steps to reproduce:*
open an existing project with latest godot, margins are lost

*Link to minimal example project* (optional but very welcome):

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/7486>, or mute the thread

**Comment by GrandFunkR** [comment]
ok I'll close this issue
