### ISSUE TITLE
CSGBox's handle is literally a single pixel

### ISSUE THREAD

**Issue by bplx** [godotengine/godot#74878]
### Godot version

4.0.stable.official

### System information

Debian 12 (Bookworm), Intel integrated graphics on 10th gen Intel Core 17-10750H

### Issue description

![image](https://user-images.githubusercontent.com/74569315/224821285-bc522c02-2054-4481-895e-9001fd6dea9c.png)
Here's the issue. There's not much more to say about it... i started up Godot, put down a CSGBox and hunted for the handles until i found this issue.

This issue also occurs running on dedicated graphics on my laptop (NVIDIA GeForce RTX 2070 with Max-Q Design)

### Steps to reproduce

Open a new project 
Add a CSGBox
Look for the handles
Can't find them.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
What are your gizmo visibility settings in the **Perspective** menu and in the **View > Gizmos** menu at the top of the 3D editor?

**Comment by Calinou** [comment]
I can't reproduce this on 4.0.stable (Linux, GeForce RTX 4090 with NVIDIA 525.89.02):

![image](https://user-images.githubusercontent.com/180032/225475370-44fd1d75-07c5-4c67-a946-8a19ea107ec6.png)

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
