### ISSUE TITLE
AnimationTree blocks property of linked animation in AnimationPlayer

### ISSUE THREAD

**Issue by Alzzary** [godotengine/godot#74952]
### Godot version

4.0 Stable

### System information

Windows 10 Pro 64bits 

### Issue description

When trying to key a node's property in an animation belonging to an AnimationPlayer node, if the animation player is linked to an AnimationTree, the property will remain locked and impossible to to change either by code or from the GUI. 

### Steps to reproduce

Create a Node2D.
Add the following nodes as child :
AnimationTree
AnimationPlayer
Marker2D (for the example). 

In the AnimationPlayer, create an animation, then select the Marker2D node and key one of its properties like rotation
In the AnimationTree, Link the AnimationTree to the AnimationPlayer, then mark it active. 
Add as tree root an AnimationNodeBlendTree
In the AnimationNodeBlendTree, add the animation you created in the AnimationPlayer and link it to the output.

You now can't change your Marker2D's rotation (or any other property).
You can however key without problem any child node. 

### Minimal reproduction project

[New Game Project.zip](https://github.com/godotengine/godot/files/10983856/New.Game.Project.zip)

**Comment by mikhaelmartin** [comment]
Solved by https://github.com/godotengine/godot/pull/80813. There is deterministic property implemented since Godot 4.2.

AnimationTree's deterministic is defaulted to true. If i set it to false, i can change rotation by code or in editor inspector. But the current active animation should also not have any track controlling the property.

I personally think editor should pushed a warning if we try editing property by code when it is actually controlled by AnimationPlayer/AnimationTree. or simply make deterministic defaulted to false
