### ISSUE TITLE
Less aggressive error highlighting ?

### ISSUE THREAD

**Issue by DriNeo** [godotengine/godot#7502]
Godot main devs works currently on the editor and GDscript usability, maybe it's the time to submit my proposal.

I found the error highlighting during text edition a bit disturbing.
I suggest to highlight only the number line column, this column is always visible. I painted this zone in the following image.

![highlightproposal](https://cloud.githubusercontent.com/assets/12350741/21866630/58012de0-d84b-11e6-8b93-a0bdbeac3afc.png)

**Comment by neikeq** [comment]
I don't know... this can be confused with a breakpoint.

**Comment by akien-mga** [comment]
I think it's fine that error highlighting is aggressive, as errors need to be fix right away since they prevent compilation and code completion.

On the other hand it's true that when the error is on the line you are still in the middle of writing, it's a bit too much. Suggestions welcome on how to improve this use case specifically without changing general error display in another section of the code. :)

**Comment by bojidar-bg** [comment]
Well, maybe we can highlight the line in some color inbetween the "current line" color and the "error line" color?

**Comment by DriNeo** [comment]
@akien-mga: I'm totally agree with the dynamic highlighting system, it's very useful.

To make this "softer" an alternative might be to just remove the highlighting if the cursor is moved or if anything is entered in the failed line. The highlighting will come back after one second of standby.

**Comment by BBric** [comment]
A larger lines numbers column for let the place to small icons, and in this case for example a classical exclamation mark in a red circle.

**Comment by Noshyaar** [comment]
This is how it looks in 3.0
![image](https://user-images.githubusercontent.com/26753932/38567426-65ca2154-3d10-11e8-85cf-8a0612104575.png)

Still an issue. Highlight of the text in that area is almost indistinguishable.
![image](https://user-images.githubusercontent.com/26753932/38567476-887e945a-3d10-11e8-9bd9-b4a0469f358d.png)

**Comment by volzhs** [comment]
![screenshot from 2018-04-11 00-59-01](https://user-images.githubusercontent.com/8281454/38568425-96d1e3fa-3d23-11e8-9b68-68b6d6eac327.png)

I got this result with selection color alpha = 1.0 (custom color though)
it seems to be indistinguishable with overlapping 3 colors with alpha.

**Comment by nikhilCad** [comment]
I like the way vscode does it. Not aggressive, but still catches attention.
![sasca](https://user-images.githubusercontent.com/47214394/81142787-25c4bd80-8f8e-11ea-9769-7314172ced42.png)

**Comment by Calinou** [comment]
@nikhilCad I did something similar in #35962, though I still kept the whole-line error highlighting as it makes it much easier to spot the error while you're in a hurry.

**Comment by DriNeo** [comment]
IMO the Calinou PR may fix this issue.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
