### ISSUE TITLE
[3.5.1 Stable Mono] Comparison is false when comparing colors created through Color.Color8(...) and new Color(...) for the same color

### ISSUE THREAD

**Issue by Xascoria** [godotengine/godot#75031]
### Godot version

3.5.1 Stable Mono

### System information

N/A

### Issue description

Because of floats comparison, the same colors that's created by `Color.Color8()` and `new Color()` will be considered different.

### Steps to reproduce

```Java
var color1 = Color.Color8(25, 54, 63);
var color2 = new Color(0.098039f,0.211765f,0.247059f);

GD.Print(color1); //0.09803922,0.2117647,0.2470588,1
GD.Print(color2); //0.098039,0.211765,0.247059,1
GD.Print(color1 == color2); //False
```

### Minimal reproduction project

N/A

**Comment by lawnjelly** [comment]
The two colors are not exactly the same, therefore the result of exact comparison is false.

To compare two colors for approximate equality, use `Color::is_equal_approx()`.

**Comment by Xascoria** [comment]
> The two colors are not exactly the same, therefore the result of exact comparison is false.
> 
> To compare two colors for approximate equality, use `Color::is_equal_approx()`.

This makes no sense, RGB colors are supposed to be discrete, the implementation should take that into account, not the other way around

**Comment by lawnjelly** [comment]
> This makes no sense, RGB colors are supposed to be discrete, the implementation should take that into account, not the other way around

RGB just refers to the components being red, green and blue. The assumption that it is stored as discrete values is incorrect. These days it is more and more common to see RGB values stored as float, especially during graphics pipelines where calculations are often in linear space, and makes possible HDR, tonemapping and overbright values, and prevents the degradation of the signal due to bucket error.

Historically you may have been more likely to come across the format RGB8 or RBGA8 (usually sRGB which refers to the mapping of the discrete values to linear), this was often used in images and frame buffers for compression and to save on bandwidth, but this is gradually becoming less and less common. There are quite a few other formats, movies are often stored as H265 which can be 10 bit, etc. Before RGB8, palettized 8 bit images were common, and before that, 4 bit or 2 or 1 bit with separate color attributes were common in the 80s.

In Godot `Color` is stored with 4 floats, red, green, blue and alpha.

What may be the source of confusion is that the expression `var color1 = Color.Color8(25, 54, 63);` does not create an RGB8, it approximately converts the RGB8 values to floating point color (with no gamma conversion, so the color space of both will be the same).

https://en.wikipedia.org/wiki/Color_space
