### ISSUE TITLE
If control is scaled, Pivot wrongly changes control's position.

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#75081]
### Godot version

3.5.2

### System information

Windows 11

### Issue description

I have a control that I wish to animate the scale from 0 to 0.7.
In it's resting state, the control is always at 0.7 scale.
It must be animated from the center and so I have changed the Pivot offset to the center.

However, by doing so, the control's position actually changes.  Here is a picture of the control with pivot in the middle.  Notice that the Position of the control is 0,0.
![Untitled-1](https://user-images.githubusercontent.com/26915986/226139943-d5fbe200-5eb4-4bbb-9a8b-c919c0af6f26.png)

This presents a major problem if I am trying to move the control by it's position.  If I want to move the control to the upper lefthand corner, (0, 0) won't work.

None of these problems occur if the control is scaled to 1.  Once I scale the control to anything else, Pivot will always visually give a false position.

### Steps to reproduce

Create control, 
scale to 0.7
change the pivot location

control moves even though position doesn't change

### Minimal reproduction project

[Pivot.zip](https://github.com/godotengine/godot/files/11009602/Pivot.zip)

**Comment by lawnjelly** [comment]
This seems to just be the definition of the pivot point. If you place it at offset 200,200, it scales and rotates around the pivot point, rather than the x,y position.

If I understand your needs correctly, you want to rotate the box around a centre, and have control over the central position. To do this you can create a `Node2D`, hang the `LineEdit` from the control, set the pivot offset to 200, 200, the position of the `LineEdit` to -200,200, and then move the position using the parent node.

Let us know if this solves the issue.

**Comment by ondesic** [comment]
Thank you for the response.  That makes sense.  It is a little more complicated than moving the position to match the 200,200 offset though.  I had to pull out some math. to make it work.  The 200 is in the middle of the control. at 0.7 scale the new size of the control is 280px.  Half is 140. 200 - 140 is 60.  Setting the LineEdit to -60,-60 puts it at 0.

If a user has a control at a constant scale of 0.7 AND it is movable, this calculation has to be done everytime.  I wish there was a property could be selected that treats the scale as if it is (1,1) and does the calculations behind the scenes.

**Comment by lawnjelly** [comment]
Closing as this doesn't appear to be a bug, and is not currently planned to be addressed (but feel free to make a proposal).
