### ISSUE TITLE
Area2D and Area3D don't trigger the mouse_entered and mouse_exited when dragging from a Control

### ISSUE THREAD

**Issue by IvanIG3** [godotengine/godot#75120]
### Godot version

4.0.stable

### System information

Windows 10

### Issue description

The Area2D and the Area3D do not trigger the signals mouse_entered and mouse_exited if the mouse is dragging from inside a Control. But, a Control triggers the signals mouse_entered and mouse_exited when dragging from another Control.
I don't know if this is intended, or it is a bug, but I think that the two nodes should behave the same.

https://user-images.githubusercontent.com/54667250/226214034-cd57654b-3bcf-4700-8cc3-e6ce256b03df.mp4

### Steps to reproduce

Execute the project below. When hovering the "Area" and the "Control", the color_rect turns red. But if dragging from the "Drag", only the "Control" turns red.

### Minimal reproduction project

[MouseInputTest.zip](https://github.com/godotengine/godot/files/11012484/MouseInputTest.zip)

**Comment by Sauermann** [comment]
Drag&Drop operations currently works by maintaining focus on the Control, that initially started the D&D-operation.
This focus prevents Area2D from receiving these InputEvents, so it works as expected.
I would have to dig deeper into the code to tell, if it is feasible to make this work.
But since Godot doesn't support Drag&Drop from a Control onto an Area2D, I don't know, if it makes sense.

**Comment by IvanIG3** [comment]
Do you know if there is a way to workaround this behavior? Maybe by telling the Control to lose this focus on click someway? Thanks!

**Comment by KoBeWi** [comment]
As a workaround you can manually poll the mouse position and check if it overlaps.

**Comment by IvanIG3** [comment]
This issue has changed with version 4,1 and 4.1.1.

Now Area2D and Area3D trigger the mouse_entered and mouse_exited signals if the mouse is dragging from inside a Control. But, if a Control is over an Area, no matter if the Control has the mouse_filter on Stop, the Area will capture the mouse. Is this ok?

https://github.com/godotengine/godot/assets/54667250/9fdf4598-b5fe-4cc5-ab3a-3e5f6110aaec

**Comment by Sauermann** [comment]
> But, if a Control is over an Area, no matter if the Control has the mouse_filter on Stop, the Area will capture the mouse. Is this ok?

That is not ok and a regression from #78017.
I have updated #79443 to fix this problem: while the mouse cursor is over the Control, the Area2D should not receive any events.

**Comment by Sauermann** [comment]
The mentioned fix got included in [Godot 4.2 dev-2](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-2/).
@IvanIG3 it would help, if you could provide feedback, if the problem is resolved for you in 4.2 dev-2.

**Comment by IvanIG3** [comment]
I've tested the 4.2 dev-2. Now the Control blocks the Area when it's over it. But, if I release the mouse button when I'm hovering the Control, the Area ignores the Control and captures the mouse.


https://github.com/godotengine/godot/assets/54667250/d4cd07c7-cddb-49fb-b19f-dc383cfd439d

**Comment by Sauermann** [comment]
@IvanIG3 thanks for testing, but unfortunately I can't replicate the behavior, that you are describing in v4.2.dev2.official [da81ca62a] on Linux X11 Xfce and on Windows 10.

My procedure for testing:
1. download and start the MRP of the opening post
2. in the Editor, reposition the right Control, so that it overlaps with the middle Area2D
3. run project
4. drag from left Control
5. release in the intersection area of middle Area2D and right Control

After step 5, for me the Area2D is not filled with red color.

Is it possible, that we use different project files?

**Comment by IvanIG3** [comment]
@Sauermann Ah yes, you are right. I had something messed up with the project. I downloaded the MRP and tested it again and it works fine now. Sorry for the confusion.

**Comment by Sauermann** [comment]
@IvanIG3 thanks for the clarification. Just to double check I would like to get confirmation from you, if you consider the original problem to be solved now, so that this issue can be closed now.

**Comment by IvanIG3** [comment]
Yes, the original problem is solved now and the issue can be closed.
