### ISSUE TITLE
Game window is broken when pressing play

### ISSUE THREAD

**Issue by CaptainReptiles** [godotengine/godot#75143]
### Godot version

4.0 Stable

### System information

Windows 10

### Issue description

As of Godot 4 Stable my game window has been broken when I press play. It'll show the smaller window, but it's completely black and I can't see anything. Yes, I have a camera for my game and it was working before Godot updated to 4.0.

### Steps to reproduce

Simply pressing play and getting a black screen on the debug window

### Minimal reproduction project

N/A

**Comment by YuriSizov** [comment]
Thanks for your report. We need a reproduction project or more detailed explanation of your setup, these steps are insufficient.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
