### ISSUE TITLE
Using @warning_ignore to ignore "shadowed_global_identifier" still issues warning(s)

### ISSUE THREAD

**Issue by cobrapitz** [godotengine/godot#75208]
### Godot version

Godot 4.0.1.stable

### System information

Windows 10, Forward+

### Issue description

Example code:

```gdscript
@warning_ignore("shadowed_global_identifier")
static func print_debug(msg: String):
```

the warning is ignored by pressing [ignore] in the warnings panel.

pressing it multiple times results in:
```gdscript
@warning_ignore("shadowed_global_identifier", "shadowed_global_identifier")
```

### Steps to reproduce

Shadowing a global function with a method of script:

```gdscript
@warning_ignore("shadowed_global_identifier")
static func print_debug(msg: String):
```

### Minimal reproduction project

```gdscript
@warning_ignore("shadowed_global_identifier")
static func print_debug(msg: String):
    pass
```

**Comment by jpcerrone** [comment]
This issue seems to only be happening on the top level scope of a script.
These two top-level declarations show the warning in the panel:
```
@warning_ignore("shadowed_global_identifier")
func print_debug():
    pass
```
```
@warning_ignore("shadowed_global_identifier")
var print_debug
```

While the warning_ignore annotation seems to work properly on a functions inner scope, like so:
```
func foo():
    @warning_ignore("shadowed_global_identifier")
    var print_debug
```
This last case doesn't show the warning in the panel when the annotation is applied.
