### ISSUE TITLE
The Collada "-lod:dist" import flag does not work.

### ISSUE THREAD

**Issue by EzraT** [godotengine/godot#7523]
**Operating system or device - Godot version:**
Godot v2.1.1.stable.official
Ubuntu Gnome 16.04 - x86_64
NVIDIA GeForce GTX570 - Driver version: 367.57

**Issue description** (what happened, and what was expected):

The "-lod" import flag does not work.
When importing a .DAE file containing objects with -lod<somedistance> in their names, Godot is supposed to automatically set Range begin to whatever number is at "-lodxxx", and according to the importer code, it is also supposed to set Range end to 100000.
It currently does not do any of these things, for as far as I can see.
[Link to Q&A post](https://godotengine.org/qa/11606/how-use-the-lod-dist-import-flag-in-the-import-3d-scene-window)

**Steps to reproduce:**
1. Create a scene in blender and include objects named like this: some_mesh-lod10 etc.
2. Export the scene with the Better Collada Exporter, and import to Godot 2.1.1.
3. Open the imported scene in the Godot editor and check the Range begin and Range end properties.

**Comment by bojidar-bg** [comment]
It is actually `-lod.dist`, due to a bug with the current implementation (e.g. `tree-lod.6`) :disappointed:

**Comment by EzraT** [comment]
I changed my object names to what you described, (Cylinder-lod.10 etc in this case), but it's still not working.

**Comment by bojidar-bg** [comment]
![image](https://cloud.githubusercontent.com/assets/5276727/21954845/16b28d80-da66-11e6-8389-6f8b8e81d7fd.png)
Here is my scene in blender with was working AFAIK.

**Comment by EzraT** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/781121/21954894/d234e3e4-da5e-11e6-8dfb-7eb247a20ee7.png)

I restructured my blender scene the same way you did and re-imported again, but still no go.
Could you attach the .blend file you used?

**Comment by bojidar-bg** [comment]
@EzraT Ok, that's weird, probably my blend didn't work either then.

**Comment by AshSamir** [comment]
i have the same issue, same version but under windows.

**Comment by wombatstampede** [comment]
The problem/error is that _teststr(name,"lod") is used in editor_scene_import_plugin.cpp.
_teststr only checks for "-lod" at the end of the name and will return false if a parameter value is added.

But there's a workaround:
Use "$" instead of "-"
Because teststr_ accepts the string anywhere in the name if "$" is used.

Name the meshes like this:

any_parent_mesh_name
  any_child_name$lod:20

This is verified with godot 2.1.4. There can be any or no char between lod and the value. So these are also valid:
name$lod20
name$lod.20

Import won't support multiple lod levels. So just one parent and a lod child. (Except you write your own import script)

**Comment by EzraT** [comment]
@wombatstampede Thanks for the clarification; I think I'll just setup my LOD levels manually in my 2.1 projects if thats the case.

**Comment by Calinou** [comment]
Closing, as the LOD system will be reimplemented from scratch in Godot 4.0: https://github.com/godotengine/godot-proposals/issues/692
