### ISSUE TITLE
Cannot assign resource properties in inspector when editing an instantiated C# custom resource with GetEditorInterface().EditResource()

### ISSUE THREAD

**Issue by wscalf** [godotengine/godot#75363]
### Godot version

4.0.1

### System information

Linux Mint 20.3 Cinnamon

### Issue description

I'm working on a custom node editor that lets me connect states in a state machine and edit the details of each state in the inspector. Each state is a custom resource (defined in C#), and I have a plugin that adds a main window editor and all that good stuff, and when I click on a state, I use GetEditorInterface().EditResource() back in the plugin to open the state object in the inspector for editing.

But then if I drag and drop any resources onto resource properties, I get something like this (taken from repro project, type names vary from actual project):
  modules/mono/glue/runtime_interop.cpp:1303 - System.InvalidCastException: Unable to cast object of type 'Godot.Resource' to type 'Inner'.
     at Outer.SetGodotClassPropertyValue(godot_string_name& name, godot_variant& value) in /home/kooshy/Projects/Prototypes/ResourceAssignRepro/Godot.SourceGenerators/Godot.SourceGenerators.ScriptPropertiesGenerator/Outer_ScriptProperties.generated.cs:line 13
     at Godot.Bridge.CSharpInstanceBridge.Set(IntPtr godotObjectGCHandle, godot_string_name* name, godot_variant* value) in /root/godot/modules/mono/glue/GodotSharp/GodotSharp/Core/Bridge/CSharpInstanceBridge.cs:line 57

This does not happen when opening the objects in the inspector by double-clicking on a .tres file or when loading the resource from the project filesystem (GD.Load) and passing it into EditResource, which may suggest a difference between resources that have previously been saved and those that have not. It also does not affect custom resources defined in GDScript, which behave normally even when instantiated and edited programmatically from my C# plugin. These cases were excluded from the repro project for brevity.

### Steps to reproduce

* Load the 'plugin' plugin from project settings
* Note the inspector is now editing an 'Outer' resource (Outer.cs)
* Drag and drop Inner.tres from the FileSystem pane to the "Inner" property in the Inspector

Expected result: the 'Inner' property of the 'Outer' object is set to the dropped resource
Actual result: See above error in the Output pane

### Minimal reproduction project

[ResourceAssignRepro.zip](https://github.com/godotengine/godot/files/11072294/ResourceAssignRepro.zip)

**Comment by Calinou** [comment]
Support for first-class C# resources isn't implemented yet – it's only implemented for GDScript.

**Comment by raulsntos** [comment]
This should work in 4.0 too, it doesn't need global classes. The problem is you are instantiating `Outer` in a plugin which means it's running in the editor, and every script that runs in the editor needs to be a Tool script. Add the `[Tool]` attribute to the `Outer` and `Inner` classes.

The reason why it works when editing the `.tres` files is that, when editing these files, the scripts are not actually instantiated, instead Godot creates a placeholder to edit them. Since they are not instantiated, no C# code is running and there's no assignment to the `Inner` property in C#, so the types don't matter (you could in fact assign the wrong resource type and it won't complain until it tries to instantiate it when running the game).

**Comment by wscalf** [comment]
Ah, okay! That all tracks:

In 4.0: using the [Tool] attribute on any resource types added by plugins addresses the casting error
In 4.1: [GlobalClass] fixes _all_ the things

I think this issue can be closed. :)
