### ISSUE TITLE
Cannot call Callable in a draw method (because no way to set_object on Callable?)

### ISSUE THREAD

**Issue by OmarShehata** [godotengine/godot#75376]
### Godot version

v4.0.1.stable.official [cacf49999]

### System information

Windows 11

### Issue description

If you try to pass a lambda/callable to be used inside a draw function, you get the error below. As far as I can tell, this is because the object that the callable is attached to is NOT the class that is calling the _draw function, so Godot doesn't recognize that it's actually being called inside `_draw` ?

```
 Drawing is only allowed inside NOTIFICATION_DRAW, _draw() function or 'draw' signal.
  <C++ Error>    Condition "!drawing" is true.
  <C++ Source>   scene/main/canvas_item.cpp:599 @ draw_rect()
````

### Steps to reproduce

```gdscript
class CustomDrawNode extends Node2D:
	var draw_func:Callable
	
	func _init(custom_draw_func:Callable):
		draw_func = custom_draw_func

	func _draw():
		draw_func.call()

# Then instantiate this as follows
var custom_draw_node = CustomDrawNode.new(func(): draw_rect(Rect2(0.0, 0.0, 100.0, 100.0), Color.GREEN)
	)
add_child(custom_draw_node)
```

I think to fix this I would want to do something like 

```gdscript
draw_func.set_object(self)
```

so that the passed in `custom_draw_func` can be called with the `CustomDrawNode` as its self? 

### Minimal reproduction project

N/A

Can be reproduced completely with the snippet above.

**Comment by kleonc** [comment]
> If you try to pass a lambda/callable to be used inside a draw function, you get the error below. As far as I can tell, this is because the object that the callable is attached to is NOT the class that is calling the _draw function, so Godot doesn't recognize that it's actually being called inside `_draw` ?

You're kinda right. This is because the object that the callable is attached to is NOT the object (a CanvasItem) that is currently [within its drawing routine](https://github.com/godotengine/godot/blob/9b0bee860f4d53614c218d28c9c32f88cf8b5cff/scene/main/canvas_item.cpp#L133-L139) (`NOTIFICATION_DRAW` / `draw` signal / `_draw` method). So the error itself is correct, the error message not really (as it's not just about being called inside `_draw`, but rather about being called inside `_draw` of the specific CanavasItem, the one currently being drawn (the [`current_item_drawn`](https://github.com/godotengine/godot/blob/9b0bee860f4d53614c218d28c9c32f88cf8b5cff/scene/main/canvas_item.cpp#L134))).

The error messages like:
https://github.com/godotengine/godot/blob/9b0bee860f4d53614c218d28c9c32f88cf8b5cff/scene/main/canvas_item.cpp#L599

can be improved for cases when `current_item_drawn != nullptr && current_item_drawn != this` as for them the execution is actually "inside NOTIFICATION_DRAW, _draw() function or 'draw' signal", just not of the proper CanvasItem.

---

> ### Steps to reproduce
> 
> ```gdscript
> class CustomDrawNode extends Node2D:
> 	var draw_func:Callable
> 	
> 	func _init(custom_draw_func:Callable):
> 		draw_func = custom_draw_func
> 
> 	func _draw():
> 		draw_func.call()
> 
> # Then instantiate this as follows
> var custom_draw_node = CustomDrawNode.new(func(): draw_rect(Rect2(0.0, 0.0, 100.0, 100.0), Color.GREEN)
> 	)
> add_child(custom_draw_node)
> ```

Currently you'd need to pass the drawing CanvasItem as the Callable's argument. Like so:
```gdscript
class CustomDrawNode extends Node2D:
	var draw_func: Callable
	
	func _init(custom_draw_func: Callable):
		draw_func = custom_draw_func

	func _draw():
		draw_func.call(self)

# Then instantiate this as follows
var custom_draw_node = CustomDrawNode.new(
	func(ci: CanvasItem):
		ci.draw_rect(Rect2(0.0, 0.0, 100.0, 100.0), Color.GREEN)
)
add_child(custom_draw_node)
```

I'd say this is expected.

---

> I think to fix this I would want to do something like
> 
> ```gdscript
> draw_func.set_object(self)
> ```
> 
> so that the passed in `custom_draw_func` can be called with the `CustomDrawNode` as its self?

To me this sounds more like a material for [a proposal](https://github.com/godotengine/godot-proposals).

**Comment by kleonc** [comment]
Marking as bug because of the incorrect / confusing error message.

**Comment by OmarShehata** [comment]
> draw_func.call(self)

Ah yeah, that works perfectly well for my use case! I was kind of stuck on this pattern because in JavaScript, given a function you can say "call it with this object as the 'self' (or `this`) param" ([link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call#parameters)) but didn't think to just explicitly pass the obj I want to apply it to.

Thank you very much for the explanation @kleonc !

**Comment by AThousandShips** [comment]
To replace the owner of a callable you can also do:
```gdscript
callable_new = Callable(target, callable_old.get_method()).bindv(callable_old.get_bound_arguments())
```

**Comment by AThousandShips** [comment]
To replace the owner of a callable you can also do:
```gdscript
callable_new = Callable(target, callable_old.get_method()).bindv(callable_old.get_bound_arguments())
```

**Comment by AThousandShips** [comment]
To replace the owner of a callable you can also do:
```gdscript
callable_new = Callable(target, callable_old.get_method()).bindv(callable_old.get_bound_arguments())
```

**Comment by kleonc** [comment]
> To replace the owner of a callable you can also do:
> 
> ```gdscript
> callable_new = Callable(target, callable_old.get_method()).bindv(callable_old.get_bound_arguments())
> ```

This won't always work. It should work e.g. when `callable_old` is not a lambda and the type (including scripts) of `target` and `callable_old.get_object()` match (so the given method could be found by name both in `target` and in `callable_old.get_object()`). But won't work in general case, e.g. for the use case mentioned by the OP.

**Comment by AThousandShips** [comment]
True! Forgot about lambdas
