### ISSUE TITLE
"FBX2glTF is required for importing FBX files. Please download it and provide a valid path to the binary:  Path to FBX2glTF exectubale is empty."

### ISSUE THREAD

**Issue by mrfisty** [godotengine/godot#75442]
### Godot version

v4.0 stable.official [92bee43ad]

### System information

Windows 11

### Issue description

I can't recall what asset I tried to import, but even after closing Godot, this alert window keeps popping up every few seconds (sometimes it doesn't come up for a few minutes if I'm actively doing things in the editor) interrupting my ability to work with the engine. 

I don't even need whatever asset it was that I was trying to import. 

[Screenshot of the alert window.](https://i.imgur.com/fQLZCBU.png)

### Steps to reproduce

Not sure, try to import import an incompatible FBX file?

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
As the dialog shows, you need to download and setup FBX2glTF to be able to import FBX files. If you don't need it, the best is to remove the FBX files from your project so it doesn't try to import them.

You can also disable FBX import in the project settings though in 4.0.stable the usability of this dialog makes it tricky, as it keeps popping up. This should be fixed in 4.0.1.stable which lets you disable FBX import from this dialog the first time it shows.
