### ISSUE TITLE
Option button (and popup node) do not work as intended in viewport

### ISSUE THREAD

**Issue by MinaRashad** [godotengine/godot#75497]
### Godot version

4.0.stable.official

### System information

Windows 10 AMD ryzen 7

### Issue description

The popup window appears in the main viewport rather than the sub viewport.
See image below:

![image](https://user-images.githubusercontent.com/39602891/228908619-199239b2-9828-469c-98c7-54944ae98767.png)

### Steps to reproduce

Make a GUI in 3d clone, put option button with several options

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
@MinaRashad Please upload a [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) to make this easier to troubleshoot.

You most likely need to enable **Embed Subwindows** on the viewport, so that popups aren't separate windows and are part of the same viewport instead.

**Comment by MinaRashad** [comment]
Thanks you were right!
I had no idea that popups are classified as separate windows
