### ISSUE TITLE
confusing performance between gdscript and c#

### ISSUE THREAD

**Issue by TomerconDevelopers** [godotengine/godot#75539]
### Godot version

4.0.1 stable

### System information

system: windows 10, ryzen 6 3600, rx 590, 16gb RAM, android device: OPPO A57, CPH2387, android version 12

### Issue description

I did a small test to measure performance between c# and gdscript

process: Instantiate a child scene in loop then add instantiated scene as child of a node.
(actual purpose it to building cells for an inventory in my game)

gdscript code:
![image](https://user-images.githubusercontent.com/62302722/229207553-a396193b-242d-4f03-850a-a14bdc751f13.png)

c# code:
![image](https://user-images.githubusercontent.com/62302722/229207706-f99302e3-b81b-472b-8184-55dd56fde17a.png)

Result:
loop count 40
c# - 8ms
gd- 6ms

loop count 1000
c#- 167ms
gd- 150ms

loop count 10000
c#-4212ms
gd-1538ms

According to my test result, gdscript is faster.
But if you search the topic in internet, Even official docs saying that c# is faster.

The reason for this test:

My aim is to develop a large scale survival game which involves various type of game mechanics such.
1. player able to place objects such as floor,wall, and furniture.
2. different enemy systems 
3. crafting system. player able to craft different items in different machines and able to track its progress (timer)
4. procedurally generated terrain system

Im confused whether gdscript can handle this game mechanics because my target platform is mobile devices, so decent performance is my first priority.
If gdscript can handle the performance, then im very happy with it because personally i don't like too much coding.
Also using gdscript i can easily maintain my code (thanks to contributors for this super easy language)
Many article suggest that you can use both language in a project. But if we stick on a single language,its more easy to maintain code. And if i hire more programmers later, then its easy to provide training in only on language.

(Note that its not a problem of the engine, i am posting this here to get best suggestions and replies from the peoples who contributing the engine code, because im seriously working on my project any wrong result will destroy future of my project.
Im also interested to contribute to engine code, but c++ is like a hell for me. So im testing the engine in all ways i can possible.)

### Steps to reproduce

create a project, instantiate some scenes via code,

### Minimal reproduction project

none

**Comment by YuriSizov** [comment]
> But if you search the topic in internet, Even official docs saying that c# is faster.

Well, who are you going to believe, "The Internet", or your own personal experience and some actual testing? 🙃 

Jokes aside, there is a lot of nuance to the performance that gets lost when you try to put it into a nice box "Which language would be faster?" Because a fair and correct answer would be "It depends". With GDScript you get tighter engine integration, so less overhead when calling into the engine API, but the language itself can be slower as it is executed in a virtual machine and it's not a very optimized one, at least at the moment. We generally consider GDScript to be "fast enough" for most scenarios, even in Godot 3. But the runtime got faster in Godot 4, with more room to improve too.

With C# and .NET you get a faster runtime by itself, but you get more overhead when calling into the engine API, because it's a third-party language and it needs to hook into our executable in a more generic way. So you may count to 1 million faster in pure C# than in "pure" GDScript, but in practice, as your real life code will inevitably use a lot of engine APIs, it evens out. So do your own testing, just like you did.

I would also recommend coming with these questions to our [community platforms](https://godotengine.org/community/), such as Discord. GitHub is not a support forum, and it's not exactly an issue to report that GDScript is actually pretty fast :) So I'm going to close your report.
