### ISSUE TITLE
No runtime errors when running a script with a syntax error (Unexpected "identifier" in class body)

### ISSUE THREAD

**Issue by isson0926** [godotengine/godot#75545]
### Godot version

 Godot Engine v4.0.1.stable.official.cacf49999

### System information

Windows 10,  Vulkan API 1.3.205 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeFor ce RTX 3080

### Issue description

Creates coding in an external text editor.

Run the script as follows.

godot_console.exe --ext gd

![31](https://user-images.githubusercontent.com/7263243/229255150-896db8e0-2116-4385-b585-99be4bdf7df9.png)
![32](https://user-images.githubusercontent.com/7263243/229255155-6f888f1d-1965-4833-94c5-45b34ebe3015.png)

### Steps to reproduce

no code

### Minimal reproduction project

[test_script.zip](https://github.com/godotengine/godot/files/11128000/test_script.zip)

**Comment by Calinou** [comment]
What does your `godot_console --ext gd` script do?

**Comment by isson0926** [comment]
I make a mistake. it's from nodemon --watch "./" --exec "cls & godot_console.exe --position 3300,50" --ext gd,gdshader.  you can ignore it(--ext gd for nodemon flag).

**Comment by isson0926** [comment]
I make a mistake. it's from nodemon --watch "./" --exec "cls & godot_console.exe --position 3300,50" --ext gd,gdshader. you can ignore it(--ext gd for nodemon flag).

**Comment by dalexeev** [comment]
I tested it and I think the bug is related to `GDScriptCache`. The `GDScript::reload()` method is not called under some conditions and therefore parser errors are not displayed.

Note that we also need to avoid unnecessary console spam when editing scripts.

https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/modules/gdscript/gdscript.cpp#L2699-L2701

https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/modules/gdscript/gdscript.cpp#L755-L756

https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/modules/gdscript/gdscript_cache.cpp#L306

https://github.com/godotengine/godot/blob/cdd2313ba27d0a2600a18e849b4c5d1fd6a6e351/modules/gdscript/gdscript_cache.cpp#L71-L73

* See also #79041.

CC @adamscott

**Comment by radlotus** [comment]
how to fix?
