### ISSUE TITLE
.gltf import not working with Blender 3.5 gltf export.

### ISSUE THREAD

**Issue by cosmoddd** [godotengine/godot#75621]
### Godot version

4.0.2 rc1

### System information

Windows 11 Vulkan

### Issue description

Blender 3.5 has substantially re-written how it exports GLTF files.  Unfortunately, Godot doesn't seem to know how to import these files and every time I export a file in Blender 3.5, it results in a blank scene in Godot and a lot of error text.  Rolling back to Blender 3.4 resolves the issue.  Also exporting in .glb works.  

However, I rely on the GLTF format in order to further edit the textures and materials post-import.  

### Steps to reproduce

1) Export a mesh as GLTF in Blender using Blender 3.5.
2) Attempt to import the mesh.  Notice Godot spits out a lot of errors in its console.
3) Double click on the mesh and see that it has scene outline but no visible meshes.

### Minimal reproduction project

This issue is reproducible in default blank project.

[GLTF IMPORT BUG.zip](https://github.com/godotengine/godot/files/11143234/GLTF.IMPORT.BUG.zip)

**Comment by fire** [comment]
Can you provide a sample? From your description even a blender 3.5 gltf default cube will fail.

**Comment by fire** [comment]
Will test with 4.0.2 rc1 after it finishes downloading a 45kb/s ... [cube.zip](https://github.com/godotengine/godot/files/11143010/cube.zip)

**Comment by capnm** [comment]
I haven't seen any new *.gltf related bugs after switching from blender4 to 5 ...

**Comment by fire** [comment]
I cannot recreate your case.

![image](https://user-images.githubusercontent.com/32321/229646058-1ee494c3-9d19-462e-a045-fa4675369f6b.png)

[New Game Project.zip](https://github.com/godotengine/godot/files/11143095/New.Game.Project.zip)

**Comment by cosmoddd** [comment]
Didn't mean to close the issue.

**Comment by fire** [comment]
Blender cannot import the gltf.

It is not a valid gltf file.

**Comment by cosmoddd** [comment]
When I export as .gltf, I'm choosing the default settings.  

![2023-04-03 21_14_08-Blender_  E__Cosmo D_test desktop_GLTF IMPORT BUG_test source blend](https://user-images.githubusercontent.com/9627628/229660968-cfb4cc19-09b5-40d3-b30a-44ef1de76593.png)
![2023-04-03 21_15_28-Blender File View](https://user-images.githubusercontent.com/9627628/229661198-f36eae4f-1650-4271-bf39-903090e3ed4d.png)


Seems like Blender simply isn't outputting the bin.  That probably means it's a bug on Blender's side, correct?  Other folks had had success outputting .bin in 3.5?

**Comment by capnm** [comment]
I guess it's because you also put the blender file in godot's folder.
I exported your blender file to another project and it works as expected:

![image](https://user-images.githubusercontent.com/4047289/229661376-0ecbac64-c1a9-4df6-bf29-57d2ba0edc12.png)

Read blend: /.../godot/tmp/GLTF_IMPORT_BUG_75621/test source.blend
00:57:22 | INFO: Draco mesh compression is available, use library at .../blender-3.5.0-linux-x64/3.5/python/lib/python3.10/site-packages/libextern_draco.so
01:01:19 | INFO: Starting glTF 2.0 export
01:01:19 | INFO: Extracting primitive: Cube.001
01:01:19 | INFO: Primitives created: 1
01:01:19 | INFO: Finished glTF 2.0 export in 0.00655364990234375 s

![image](https://user-images.githubusercontent.com/4047289/229661549-aff924f5-263e-472f-90bf-7c31b73e0939.png)

**Comment by cosmoddd** [comment]
I think I figured it out - if you export .gltf with spaces in the filename, it exports the bin, but uses "%20" as a character instead of spaces.  I think it's right to assume this issue is on Blender's side - will file it there.
