### ISSUE TITLE
Tooltip with physics running on separate thread bug

### ISSUE THREAD

**Issue by AlCappaccino** [godotengine/godot#75727]
### Godot version

4.0.2-stable

### System information

Windows 10

### Issue description

When running physics on a separate thread the tooltip of a control node may cause a crash when you play audio from an AudioStreamPlayer2D node at the same time as the tooltip would try to appear.

Error message:
```
Godot Engine v4.0.2.stable.official.7a0977ce2 - https://godotengine.org
Vulkan API 1.1.95 - Forward Mobile - Using Vulkan Device #0: NVIDIA - GeForce GT 750M
 
USER ERROR: Space state is inaccessible right now, wait for iteration or physics process notification.
   at: space_get_direct_state (servers/physics_2d/godot_physics_server_2d.cpp:282)

```

### Steps to reproduce

Run the project in the attached file, press spacebar to play audio stream while moving cursor to show tooltip of the icon on screen -> crashes

### Minimal reproduction project

[godot-tooltip-bug.zip](https://github.com/godotengine/godot/files/11164009/godot-tooltip-bug.zip)

**Comment by smix8** [comment]
Properly because the AudioStreamPlayer2D (and 3D for that matter) has no check if the returned PhysicsDirectSpaceState is actually valid. Since you can't access a physics space outside of sync phase while physics runs threaded it is returned null which crashes.

**Comment by AlCappaccino** [comment]
Turns out I had changed the AudioStreamPlayer2D into a normal AudioStreamPlayer which does not cause bug, if you change it back to AudioStreamPlayer2D it should crash, sorry for sending wrong project.

**Comment by smix8** [comment]
As in my original post the crash is due to the physicspace returning null. The reason why it is happening is because the Viewport updates which triggers AudioServer updates for listeners which triggers the update panning functions on the AudioStreamPlayers which should never trigger outside of the physics update.

The AudioStreamPlayer2D (and 3D for that matter) has no check if the returned PhysicsDirectSpaceState is actually valid. Since you can't access a physics space outside of sync phase while physics runs threaded it is returned null which crashes.

This is apparently an old issue but for whatever reason the fix from https://github.com/godotengine/godot/pull/61417 was added for the AudioStreamPlayer3D only but never to the AudioStreamPlayer2D.
