### ISSUE TITLE
extends BASE in path form lead suggestion about super extra quote appeared

### ISSUE THREAD

**Issue by jzq740176597** [godotengine/godot#75774]
### Godot version

4.0.2.stable

### System information

window10,forward+

### Issue description

![](https://i.postimg.cc/sXJvX6YG/4-7-2023-2-31-56-PM.jpg)

> extends "../DmUtils/tween_panel.gd"
> 
> """gd"""
> func _ready() -> void:
> ____"super"   # Suggestions willl extra quote added!

### Steps to reproduce

1. foo BASE.gd
2. another subclass extends it (extends "../folder/BASE.gd")
3. type subclass callback say: _ready(): TYPE super THEN "super" appeared

### Minimal reproduction project

none

**Comment by HolonProduction** [comment]
The issue only happens on lines that existed before the path was entered in the first line, since it is a problem with updating the delimiter cache. When you type the opening quote all lines will be marked as inside this string. But when closing the quotes the lines below aren't updated. Ig when you only create the lines afterwards they can't stay in the corrupted intermediate state.
