### ISSUE TITLE
Attempting to add a Ceil Vector2 to a visual shader will crash the engine.

### ISSUE THREAD

**Issue by Bits360** [godotengine/godot#75790]
### Godot version

4.0.2 Stable

### System information

Windows 10, RTX 2060, Bug occurs on all backends.

### Issue description

Attempting to add a Ceil Vector2 to a visual shader will immediately crash the engine.
All other ceils work fine, and so does changing one to a Ceil Vector2, Only crashes when trying to directly create one from the right click menu.

### Steps to reproduce

1: Create new visual shader, or just open a preexisting one.
2: Try to add a Vector2 ceil

### Minimal reproduction project

N/A

**Comment by komugi1211s** [comment]
This issue exists as of 4.1. 

seems like it's caused by the registered Ceil (vector2) function missing a type specifier as opposed to vector3 or vector4 version, which has corresponding type specifier OP_TYPE_VECTOR(3/4) as a member:

https://github.com/godotengine/godot/blob/c151d3231f8e5d207f64055c60c70967dd5351b5/editor/plugins/visual_shader_editor_plugin.cpp#L5934
