### ISSUE TITLE
Wildcards in function arguments

### ISSUE THREAD

**Issue by bojidar-bg** [godotengine/godot#7599]
Given that we now have `TK_WILDCARD` in GDScript, and _ is officially banned as a variable ( @karroffel  ), I would like to request to be able to write this:
```gdscript
func handler(_, _):
  pass # Might actually complete this function one day
```
Instead of:
```gdscript
func handler(discard = null, discard2 = null):
  pass # Might actually complete this function one day
```

**Comment by karroffel** [comment]
It's not merged yet btw.. 😄

**Comment by bojidar-bg** [comment]
@karroffel My bad -- anyway, I guess it would be merged given the community response on that other issue...

**Comment by karroffel** [comment]
I still need reduz consent 😄

**Comment by ClikCode** [comment]
The PR #7583 has been merged by Akien a day ago. So this is a valid issue now.

**Comment by jjay** [comment]
I'm for pythonic
```gdscript
func handler(*args):
  pass
```
or even
```gdscript
func handler(*_):
    pass
````
in case of wildcard.

**Comment by reduz** [comment]
I prefer pythonic if we need to add this feature too

**Comment by bojidar-bg** [comment]
I'm not speaking about varagrs, I'm speaking about using `_` as a parameter name, to make an ignored value. i.e. for stuff like `func do_stuff(_, second_param)` over `func do_stuff(something_not_going_to_be_used, second_param)`

**Comment by karroffel** [comment]
I think it's worth adding. It's making use of the new token and if (ever 😢) the lambda PR gets merged then this
```gdscript
var x = func(x,_): x
```
looks a lot sexier than
```gdscript
var x = func(x, y): x
```
because it's clear from the argument list that only the first param will be used.

I might take a look at how easy it is to implement that.

**Comment by Calinou** [comment]
Note that you can avoid the warning with discarded arguments by leading the parameter name with an underscore (e.g. `_arg_name` instead of `arg_name`).

___

Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
