### ISSUE TITLE
Saving duplicates my Folder reference 

### ISSUE THREAD

**Issue by walidsantos** [godotengine/godot#76021]
### Godot version

4.0.2 (latest)

### System information

Windows 10,  Intel(R)HD Graphics Family, 20.19.15.5171,  GLES3

### Issue description

If i save my scene the folder duplicates ,i think there is bug on editor. Because i checked my game files if it really duplicates the folder . But it didn't.  

https://user-images.githubusercontent.com/53328867/231726981-4526bbe0-067d-4482-9af6-a203f938603f.mp4

### Steps to reproduce

Crtl + S 
Also when deleting the folder all duplicated folders is deleted too.

### Minimal reproduction project

N/A

**Comment by daredloco** [comment]
I can reproduce this problem, it seems to happen if the folder name is uppercase, it would then create an exact copy of the folder in lowercase. It **wont** happen if the folder name is all lowercase.

OS: Windows 10, Vulkan
Version: v4.0.2.stable.mono.official [7a0977ce2]

**Comment by KoBeWi** [comment]
Yeah I just tested and it's the case. The editor should either fix path input casing or don't allow using wrong path.

**Comment by jamesfoxbr** [comment]
The problem disappear after I moved one of the files from one of the folders to the other. The only file did not was duplicated between folders

**Comment by AirDinghy** [comment]
I am still seeing this problem in 4.2.1 
Was there anyway to figure out what file is causing the issue?

**Comment by TheSofox** [comment]
Okay, so the repo steps are:
1. Create a folder, and create a scene in that folder.
2. Save scene
3. Delete Folder, push through the warning dialog.
4. Create a new folder with the same name BUT DIFFERENT CASE to the previous folder in the same location.
5. Save the scene again

Expected: Either you're given a warning that the original location doesn't exist, or the scene gets saved to the new folder with the same name even thought it has a different case (ie. NewFolder/NEWFOLDER/newfolder/etc.)

Actual: You now have two folders with the same name but different case in the Godot filesystem. Both folders seem to have the same contents.

I've tracked the core problem to `editor\editor_node.cpp`

In `EditorNode::_menu_option_confirm(int p_option, bool p_confirmed)` unders `case FILE_SAVE_SCENE` when a scene is saved, they check if the directory exists. This check is case insensitive, so it may appear that the folder that the Scene "remembers" being in still exists, however the the folders the Scene remembers may have a different case, and somehow this pops up later down the chain when the Scene is saved.

**Comment by TheSofox** [comment]
I think I've narrowed the problem down to `bool EditorFileSystem::_find_file` in `editor\editor_file_system.cpp` specifically a line of code that goes `if (fs->get_subdir(j)->get_name() == path[i])`

**Comment by TheSofox** [comment]
I found a much easier way to duplicate this. Instead of deleting and making folders, you simply rename the folder that the resource is in in your OS File Manager (OS being Windows or Mac, as this issue isn't in Linux) and save the file again in the editor.

I've found a way to prevent the folders from being duplicated, so fixing this specific bug, but I've observed a related problem.

While I've ensured that the folder isn't duplicated, the open scene and open scripts still have their location set to be a slightly different place. After renaming the folder, you can then open up the same file and instead of it recognising its already open, it just opens it up again. This means you can have the exact same resource opened up multiple times:

![image](https://github.com/godotengine/godot/assets/3089525/bdab0a92-fc03-417d-acb1-f056ad6ea482)
![image](https://github.com/godotengine/godot/assets/3089525/c62139a4-940d-4f6a-8173-eec2cacb7460)

**Comment by TheSofox** [comment]
Okay, I've created a PR to deal with the specific bug listed in this report; namely duplicated folders.

More widespread handling of Godot case should be a separate bug.
