### ISSUE TITLE
Error reordering Input Maps

### ISSUE THREAD

**Issue by felaugmar** [godotengine/godot#76177]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 10

### Issue description

Following **Steps to reproduce**, these are the printed lines:
```
Request for nonexistent project setting: ProjectSettings.
Request for nonexistent project setting: script.
```

### Steps to reproduce

1. Go to **Project Settings** -> **Input Map**;
2. Create at least two custom input maps;
3. Move one input map up or down in the list dragging it;
4. The order will change;
5. Two error lines will be printed in the **Output**.

### Minimal reproduction project

N/A

**Comment by jpcerrone** [comment]
I found out what causes both of these errors, I have some fix proposals but they'll probably need to be reviewed by someone with more knowledge of the engine than I have. Here's what I've found:

The problem happens inside the [`ProjectSettingsEditor::_action_reordered()`](https://github.com/godotengine/godot/blob/20ed51a9129f97bb8d001262155fb3ccfc1e3c89/editor/project_settings_editor.cpp#LL437C7-L437C7) function. This method starts by getting a list of all the project settings with `ProjectSettings::get_singleton()->get_property_list(&props);` and then iterating through them to find the user defined input ones. The issue arises because, to determine whether each setting of the list is a built-in and so not a user defined one, a call is made to `ProjectSettings::get_singleton()->is_builtin_setting(prop.name)` . In its first line this function asserts if the setting can be found in a list it has of the available project settings. Since it doesn't find either "ProjectSettings" or "script" it produces an error in both of those cases.

While both of these properties aren't really modifyable project settings, and aren't in fact returned by the function from `ProjectSettings` called by `ProjectSettings::get_singleton()->get_property_list(&props);`, they do get added to the list that's returned from it, each of them in some place in the `Object::get_property_list()` call that wraps the `ProjectSettings` one, and that's what produces the errors.

#### Where "script" gets added:

The `Object::get_property_list()` function adds the "script" property in this line [object.cpp#L507](https://github.com/godotengine/godot/blob/20ed51a9129f97bb8d001262155fb3ccfc1e3c89/core/object/object.cpp#L507). This property seems to be required by nodes that can have scripts attached to them. One thing that could be done is to add an exception for the "script" property when we're getting the Project Settings, like there seems to be for `Script` classes:
```gdscript
if (!is_class("Script") && !is_class("ProjectSettings")) {
	p_list->push_back(PropertyInfo(Variant::OBJECT, "script", PROPERTY_HINT_RESOURCE_TYPE, "Script", PROPERTY_USAGE_DEFAULT | PROPERTY_USAGE_NEVER_DUPLICATE));
}
```
This change works, it removes the `Request for nonexistent project setting: script.` error message.

#### Where "ProjectSettings" gets added:

Before handling the virtual call to `get_property_list()`, the Object class always adds the name of the class as a property to the returned list of any `get_property_list()` call in this line:  [object.h#L480](https://github.com/godotengine/godot/blob/20ed51a9129f97bb8d001262155fb3ccfc1e3c89/core/object/object.h#L480) . This in our case is the `ProjectSettings` class name being added. Removing this line makes it so that the class name never gets added as the property of an object and solves the issue. The `Request for nonexistent project setting: ProjectSettings.` error doesn't show up anymore.

I'm not so sure about this one since I don't know if the class name as a property is used by any other classes, so changing it might have unintended consecuences in other parts of the engine.
A different way to fix the error might be to, inside the `ProjectSettings::get_property_list()` function, remove the "ProjectSettings" element from the list that it'll return by calling `p_list->erase(PropertyInfo(Variant::NIL, get_class_static(), PROPERTY_HINT_NONE, String(), PROPERTY_USAGE_CATEGORY));` right at the begginig of it. This also fixes the error.

Let me know what you think of these changes! I'll create a draft PR in the meantime with the changes I proposed.
