### ISSUE TITLE
When Changing instance_count for MultiMeshInstance2D, All Instances Transform Gets Reset

### ISSUE THREAD

**Issue by Moonzel** [godotengine/godot#76180]
### Godot version

v4.0.stable.mono.official [92bee43ad]

### System information

Windows 11, AMD Radeon(TM) Graphics, AMD Ryzen 7 5800H

### Issue description

When the instance_count is changed at all after the node has been instantiated, the transform for every instance is changed to the default. This makes it difficult to move instances on their own, without pooling. I expect it to not set each instances transform, and just leave it as it was before changing the instance_count. 

### Steps to reproduce

1. Create a MultiMeshInstance2D
2. Change the MultiMesh's instance_count (after the ready function)
3. Attempt to set the transform_2d of a certain instance
4. Watch it reset

### Minimal reproduction project

[MultiMesh Issue.zip](https://github.com/godotengine/godot/files/11254649/MultiMesh.Issue.zip)

**Comment by clayjohn** [comment]
This is intended behaviour currently. Please see the docs: https://docs.godotengine.org/en/latest/classes/class_multimesh.html#class-multimesh-property-instance-count

There is a proposal to change the current behaviour so that you can change ``instance_count`` without resetting the instance buffer https://github.com/godotengine/godot-proposals/issues/412

For now, the current workaround is to set ``instance_count`` to some reasonably high number, then adjust ``visible_instance_count`` as needed.
