### ISSUE TITLE
Separate signal-waiting from coroutine calls

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#7618]
It doesn't make sense for coroutines to both be able to yield to their caller and "yield" to a signal; there should be one thing that has control of the coroutine. I am pretty sure there isn't any use case for using both in the same method, but maybe someone can come up with one. Currently there can't be one, since yielding to a signal doesn't work when the yielding method is called from another method, but maybe there could be some way to use it if that limitation was fixed somehow.

There should be one method for signal-waiting, and another one for yielding as a coroutine. If these are separated, the yield (for coroutines) should be able to pass a value to the calling resume/original call somehow, to request things from the caller.

**Comment by raymoo** [comment]
Still relevant, as yield is still used for both waiting on a caller and on a signal.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
