### ISSUE TITLE
Toggling top-level does not update 2D editor viewport

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#76205]
### Godot version

4.0.2

### System information

Windows 10 x64

### Issue description

https://user-images.githubusercontent.com/2223172/232775581-ad40bacc-b051-4d71-87fb-ffad3f60be2f.mp4

### Steps to reproduce

1. Add Sprite2D
2. Toggle its `top_level`
3. Notice how the gizmo rectangle stays in the old position until you hover 2D editor

### Minimal reproduction project

N/A

**Comment by ryevdokimov** [comment]
IMO it shouldn't move at all. Due to this bug, and because it's jarring. Especially once you start adding rotation and scale, the item could just teleport completely out of the viewport and could be difficult to find.  

It should, stay in place and update transform relative to global, which is what this PR for 3D is doing: [https://github.com/godotengine/godot/pull/87100](https://github.com/godotengine/godot/pull/87100)

**Comment by ryevdokimov** [comment]
I added two different solutions that should solve this problem depending on timeframes, compatibility, or general direction the Godot team wants to approach this. If you have time to review it, it would be appreciated it.
