### ISSUE TITLE
Linux editor 3d clip distance + fov settings not working

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#7623]
**Operating system or device - Godot version:**
Ubuntu 16.04
godot 2.2 + 2.1

**Issue description:**
Changing the fov or the clip distances in the editor do not work under linux. Looks fine under windows...

**Steps to reproduce:**
Make a 2kmx2km scene in blender. import. Try changing the clip planes or fov. They dont update...

**Comment by Gibbz** [comment]
I found a work around is to open the scene. Then click view > settings and change the values in there. Still I would expect the editor setting to be a global so I dont need to do this for each scene.

**Comment by akien-mga** [comment]
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.
