### ISSUE TITLE
OptionButton does not allow middle mouse scrolling

### ISSUE THREAD

**Issue by hunterczech** [godotengine/godot#76289]
### Godot version

3.6.beta1

### System information

Windows 11, GLES3

### Issue description

OptionButton no longer supports mouse scrolling which is problem with longer lists.

Everything worked fine in 3.5

### Steps to reproduce

1) Create OptionButton
2) Put in like 120 items
3) Press F5
4) Select OptionButton and try to scroll it

### Minimal reproduction project

N/A

**Comment by lawnjelly** [comment]
Looking for possible candidates:
#66711

**Comment by rsubtil** [comment]
This is likely due to the maximum height not being set automatically (the scrolling behavior is now handled by the ScrollContainer containing the popup). This is how it's done on 4.0:

https://github.com/godotengine/godot/blob/6101240231600c871f5c5473872532c68ea3268c/scene/gui/popup_menu.cpp#L120-L123

However there's no `get_usable_parent_rect()` equivalent on 3.x. Knowing that there are no separate windows on this version, maybe it's enough to just fetch the editor window's height and use that?

**Comment by lawnjelly** [comment]
> Knowing that there are no separate windows on this version, maybe it's enough to just fetch the editor window's height and use that?

Yes, that sounds sensible, can you make a PR to fix?

**Comment by akien-mga** [comment]
Fixed by #77691.
