### ISSUE TITLE
OpenGL: Blend modes other than Mix don't work unless Depth Draw Mode is set to Never

### ISSUE THREAD

**Issue by decacis** [godotengine/godot#76334]
### Godot version

v4.1.dev1.official [db1302637]

### System information

Windows 10, Compatibility, NVIDIA GeForce GTX 1050 Ti (528.24)

### Issue description

Setting the blend mode to something besides mix behaves the same as mix. This is the same whether is a ShaderMaterial or a StandarMaterial3D.

![Blend-Add](https://user-images.githubusercontent.com/6643844/233757918-79725cfc-eb03-4c48-8a31-bcaca180600c.gif)

I think this should have been fixed by #75968 unless I misunderstood the PR, and it does seem to be included in this version (4.1 dev1). It does work if you set the **Depth Draw Mode** to **Never** though.

### Steps to reproduce

- Add a MeshInstance3D with a mesh of any type
- Add a StandarMaterial3D
- Set the blend mode to add (or any other than mix)
- It won't work unless you set the depth draw mode to Never

### Minimal reproduction project

[BlendAdd.zip](https://github.com/godotengine/godot/files/11300080/BlendAdd.zip)

**Comment by clayjohn** [comment]
Tagged as "good first issue" for clarity, this is a good first issue for someone with a little bit of OpenGL experience

**Comment by allenwp** [comment]
This is a good first issue :) I was able to determine the problem by comparing the OpenGL renderer with the forward mobile and forward clustered renderers. It seems that the following was omitted in OpenGL's `set_code(const String &p_code)` function for `BLEND_MODE_ADD`, `BLEND_MODE_SUB`, and `BLEND_MODE_MUL`:

`uses_blend_alpha = true; //force alpha used because of blend`

I'll have a PR to fix this issue soon, but will need to go over the contribution guidelines first.

**Comment by allenwp** [comment]
I have noticed that the OpenGL `Subtract` blend mode doesn't work no matter what other draw modes are selected. This appears to be because it was using `GL_FUNC_REVERSE_SUBTRACT` instead of `GL_FUNC_SUBTRACT`. I will include this fix in my PR as well to address all of the "Blend modes other than Mix don't work" cases.
