### ISSUE TITLE
Input Map keys are not converted by the project converter tool

### ISSUE THREAD

**Issue by edgeofaverage** [godotengine/godot#76336]
### Godot version

4.0.2.stable

### System information

Windows 10

### Issue description

Input Map values I had added and set were unset when I migrated to version 4.0.2.  Notably only keyboard mappings reset changed to "(Unset)" while mouse mappings remained.  Both "Key" and "Physical key" get reset, can reproduce test manually.

### Steps to reproduce

Migrate project from 3.4.4-stable to 4.0.2-stable.

### Minimal reproduction project

N/A -- Steps are creating project in 3.4.4 and adding function to input map and assigning key/physical key (both are unset), then running "Convert Full Project" to begin editting in 4.0.2.

**Comment by Daniel-da-Silva** [comment]
I have the same issue. Godot 3.5.2 -> 4.0.2.
[Thought this was just left out.](https://github.com/godotengine/godot-proposals/issues/6736)

**Comment by akien-mga** [comment]
That's weird, because this was implemented by @Maran23 in https://github.com/godotengine/godot/pull/71753. There must be a bug in the conversion logic.

**Comment by Maran23** [comment]
Yes, can confirm that. I just had a look and the conversion looks good, just for some reason the keycode is lost somehow?
![image](https://user-images.githubusercontent.com/66004280/234687997-5c2807af-c1e6-4a55-9abb-ecb3ff336e5f.png)

**Comment by Maran23** [comment]
Ok, the issue is very weird. 
When converting the project using the executable file, e.g. Godot 4.0.2, all keycodes are set to 0, see also above.
But if you actually use the console command `--convert-3to4`, everything looks good and when starting the project all keys are there and fine. 
Interestingly Godot asked me if I want to convert the project, although I did already via the `--convert-3to4` command.

So: Conversion still works, but something is breaking the keycodes after? it. Something that does not run when using the `--convert-3to4` command.
