### ISSUE TITLE
Error about input event in project manager at every launch

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#76384]
### Godot version

4.1 24cb43a

### System information

Windows 10 x64

### Issue description

Every time I launch Godot, I'm greeted with this in my console:
```
ERROR: Resource file not found: res://InputEventKey_7cuxk.
   at: (core\io\resource_loader.cpp:227)
```
Seems to be only happening in Project Manager and comes from this:
![](https://chat.godotengine.org/file-upload/udqZP8NQfogp4rjRL/Clipboard%20-%2021%20kwietnia%202023%2022:24)
It's part of my `editor_settings-4.tres`. I didn't test, but I think it applies to any shortcut that you customize. For some reason ResourceLoader tries to load it as a project resource, while it's a sub-resource.

Does not happen in 4.0.2.

### Steps to reproduce

1. Open Godot 4.1 project manager
2. Check the console

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
When parsing the SubResource, `VariantParser` needs a non-null `ResourceParser`:

https://github.com/godotengine/godot/blob/ae4d469ca2695141c1b944df6c45ce9631522103/core/variant/variant_parser.cpp#L975-L1006

Otherwise, it seems to fallback to assuming it's Resource and calls `Resource::load` on it:

https://github.com/godotengine/godot/blob/ae4d469ca2695141c1b944df6c45ce9631522103/core/variant/variant_parser.cpp#L1006-L1026

The reason why `ResourceParser` is null seems to be this line in main introduced by https://github.com/godotengine/godot/pull/75219:

https://github.com/godotengine/godot/blob/f7374e2db76e24003b185394b1e1044eb00fbad5/main/main.cpp#L2055

This code is just parsing the editor settings to look for 2 enum settings so it won't care about SubResources. We could ignore SubResource if `ResourceParser` is null, but this would also silence the error for other cases where it may be valid.

**Comment by akien-mga** [comment]
Could be worth bisecting if someone has a fast computer :)

**Comment by raulsntos** [comment]
Are you sure it doesn't happen before **dev 3**? The commit in OP seems to be part of **dev 2**. I think this was a consequence of https://github.com/godotengine/godot/pull/75219 which I believe was added in **dev 1**.

Keep in mind the issue only happens if you have custom shortcuts so maybe you didn't find the issue before **dev 3** because you weren't using custom shortcuts.

**Comment by akien-mga** [comment]
> I think this was a consequence of #75219 which I believe was added in **dev 1**.

CC @bruvzg
