### ISSUE TITLE
Add focus tracking and confined mouse mode to OSX

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#7647]
These features have been implemented for X11 and Windows in 1005a56.

They should likely be implemented in OSX too (and Haiku?).

**Comment by akien-mga** [comment]
Poke @BastiaanOlij :P

**Comment by BastiaanOlij** [comment]
I'll have a look what I can do over the weekend :)

**Comment by BastiaanOlij** [comment]
Hey @akien-mga , I'm trying to make sense of how the different behaviours are meant to be.

OSX already by default handles the focus properly, when focus moves away from the Godot app it automatically disables sending the app mouse events so I don't think there is any need to do more there so I'm guessing this is purely about adding support for MOUSE_MODE_CONFINED?

So if I understand correctly MOUSE_MODE_VISIBLE is normal mouse behaviour, so is MOUSE_MODE_HIDDEN but simply with the mouse cursor hidden and MOUSE_MODE_CAPTURED simply means you're not moving/showing the mouse cursor at all but reacting to deltas (I'm guessing what happens when you press say ALT in the editor to move your view around?)

So MOUSE_MODE_CONFINED, would be just normal mouse behaviour but ensuring it can't leave the confines of the Godot window?

**Comment by reduz** [comment]
@BastiaanOlij yes exactly, in most OSs this is done by forcing the actual mouse pointer to the center of the screen every time it moves, but feeding a virtual position to the engine to make it believe it can move around infinitely

**Comment by akien-mga** [comment]
Bump, if we don't implement this for 3.0 we need to make sure the documentation reflects it. We can also make the platforms where it's not implemented trigger an error message when MOUSE_MODE_CONFINED is used (as done already for Javascript).

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by jamie-pate** [comment]
Still broken on 3.2.3
https://github.com/godotengine/godot/pull/40054#issuecomment-698491215

**Comment by akien-mga** [comment]
Please open a bug report with a reproduction project.

**Comment by jamie-pate** [comment]
Done!
https://github.com/godotengine/godot/issues/42321
