### ISSUE TITLE
Warning emitted when opening any project: "Attempting to access theme items too early; prefer NOTIFICATION_POSTINITIALIZE and NOTIFICATION_THEME_CHANGED"

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#76509]
### Godot version

4.1.dev (240ed28291ae87f06f7bcaa66e3d08530f210bf2)

### System information

Mageia 9, Linux

### Issue description

Since a few days, I've seen this warning show up in the console when editing a project with Godot 4.1.dev:
```
WARNING: Attempting to access theme items too early; prefer NOTIFICATION_POSTINITIALIZE and NOTIFICATION_THEME_CHANGED
     at: get_theme_icon (scene/gui/control.cpp:2433)
```

It doesn't happen in 4.1.dev1 (db1302637), so it's a recent regression introduced between db1302637 and 240ed28291.

### Steps to reproduce

- Create new project
- Open it
- Check console

### Minimal reproduction project

n/a

**Comment by MisterMoresco** [comment]
I have this in 4.5 stable.  I don't know what triggers it or how to solve it, but I did notice (possibly unrelated) graphical glitches when resizing the window with this dark theme, like parts of the corners disappear or the file menu at the top disappears altogether.

<img width="1019" height="349" alt="Image" src="https://github.com/user-attachments/assets/35b8760b-2fb2-42c1-ba5e-108613e60843" />

<img width="1456" height="105" alt="Image" src="https://github.com/user-attachments/assets/f5e1c667-bed2-4673-abf1-e9d12c1c0620" />

WARNING: scene/gui/control.cpp:2987 - Attempting to access theme items too early in GameView; prefer NOTIFICATION_POSTINITIALIZE and NOTIFICATION_THEME_CHANGED

**Comment by caleskog** [comment]
I get the same warning. Though, I haven't seen any graphical glitches in the editor.

<img width="1084" height="159" alt="Image" src="https://github.com/user-attachments/assets/88891da7-26f3-4a8d-a540-2bc6031ced86" />

**Comment by MisterMoresco** [comment]
> I get the same warning. Though, I haven't seen any graphical glitches in the editor.
> <img alt="Image" width="1084" height="159" src="https://private-user-images.githubusercontent.com/104908965/500687328-88891da7-26f3-4a8d-a540-2bc6031ced86.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMwMDgyMjYsIm5iZiI6MTc2MzAwNzkyNiwicGF0aCI6Ii8xMDQ5MDg5NjUvNTAwNjg3MzI4LTg4ODkxZGE3LTI2ZjMtNGE4ZC1hNTQwLTJiYzYwMzFjZWQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExM1QwNDI1MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NWQyZDAzMjE1OGMwMThjZjhlNzlmZjM3Nzc2NGE5ZDdkYmYyZDc5YzdmZWM0MjFjODczMzMwMDk0MmE3YWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gzScVNjLtFhJPQtsYtLzEEVu2rxtXtBcJNN2ZKTZUrg">

Could be a slightly different issue but same error is showing.  I've since tried 4.6dev3, it has a new theme built-in.  Error still shows (I think the line changed because control.cpp changed in size, but I don't know)

WARNING: scene/gui/control.cpp:3025 - Attempting to access theme items too early in GameView; prefer NOTIFICATION_POSTINITIALIZE and NOTIFICATION_THEME_CHANGED

I had some editor_theme.tres in my project's root folder, so I deleted that.  I tried disabling all visible layers in my scene like is reported at this link below, but it didn't clear the error.  I'm no longer seeing graphical glitches, could be the changes in 4.6dev3 which cleared that up, my graphics driver is the same.  

https://github.com/godotengine/godot/issues/111751#issuecomment-3524690477
