### ISSUE TITLE
TabContainer : ERROR signal is already connected ; when setting all_tabs_in_front to true in editor

### ISSUE THREAD

**Issue by bsil78** [godotengine/godot#76578]
### Godot version

4.0.2.stable

### System information

Windows 10

### Issue description

When I set all_tabs_in_front is a TabContainer, immediately (and then each time scene is loaded), there is  3 errors pushed telling a signal is already connected.

Disabling the feature remove errors.

Here are exact errors : 

-   Signal 'size_flags_changed' is already connected to given callable 'Container::queue_sort' in that object.
-   Signal 'minimum_size_changed' is already connected to given callable 'Container::_child_minsize_changed' in that object.
-   Signal 'visibility_changed' is already connected to given callable 'Container::_child_minsize_changed' in that object.

And stack trace when running scene :

E 0:00:02:0143   connect: Signal 'size_flags_changed' is already connected to given callable 'Container::queue_sort' in that object.
  <Erreur C++>   Method/function failed. Returning: ERR_INVALID_PARAMETER
  <Source C++>   core/object/object.cpp:1270 @ connect()
Pointing to : [object.cpp#L1270](https://github.com/godotengine/godot/blob/7a0977ce2c558fe6219f0a14f8bd4d05aea8f019/core/object/object.cpp#L1270)

It does not seem blocking anything but it could help to find some important flaws and message seems strange though.

### Steps to reproduce

Just instanciate a TabContainer control as base node and activate the all_tabs_in_front feature by clicking in editor

### Minimal reproduction project

Here is content of a minimal tab_container.tscn file to reproduce 
[gd_scene format=3 uid="uid://dh3nybprc67cg"]

[node name="TabContainer" type="TabContainer"]
offset_right = 40.0
offset_bottom = 40.0
all_tabs_in_front = true

**Comment by adamscott** [comment]
Please join a Minimal reproduction project in your issue description. The "minimal" in "minimal reproduction project" doesn't go to the exact lines of a file, :laughing:.

To cite [CONTRIBUTING.md](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md)
> To speed up our work, **please upload a minimal project** that isolates
and reproduces the issue. This is always the **best way for us to fix it**.
We recommend attaching a ZIP file with the minimal project directly to the bug report,
by drag and dropping the file in the GitHub edition field. This ensures the file
can remain available for a long period of time. Only use third-party file hosts
if your ZIP file isn't accepted by GitHub because it's too large.

**Comment by AThousandShips** [comment]
Should be due to this line:
https://github.com/godotengine/godot/blob/master/scene/gui/tab_container.cpp#L595

It doesn't propagate the removal of the tab bar which disconnects this signal in `Container`

**Comment by bsil78** [comment]
Thanx a lot !
