### ISSUE TITLE
Debugger breakpoints do nothing in the Android editor

### ISSUE THREAD

**Issue by Booklight12** [godotengine/godot#76583]
### Godot version

all of Android

### System information

Android

### Issue description

godot's debugger is certainly powerful, but it doesn't work well on Android.

### Steps to reproduce

Create a new project, then create a new script, put a breakpoint in the script, and try to run it.it doesn't work.

### Minimal reproduction project

null

**Comment by m4gr3d** [comment]
@Booklight12 Can you provide a recording of the issue you're running into? 

I am unable to repro the issue you described and have been able to successfully use the debugger with its full functionality in the Android editor.

**Comment by Booklight12** [comment]
Here, print after the breakpoint is still executing。
[here](https://github.com/Booklight12/text/blob/main/Screenrecorder-2023-05-30-12-30-35-986.mp4)

**Comment by Booklight12** [comment]
This version, by the way, does not close the debug window even if a code error occurs.

**Comment by m4gr3d** [comment]
@Booklight12 Tested with Godot 4.2 beta 4 on a Google Pixel 5 and Galaxy Tab S8 and the issue is no longer reproducible.

Do note however that debugging is not `officially` supported on smaller screens because they lack the screen real estate to show both the debugger and the running project at the same time.
As a result, this gives the impression that the running project is frozen, because it's blocked by the debugger but the user is unable to access the debugger to resume it.
