### ISSUE TITLE
CharacterBody2D stops receiving the velocity when is grounded

### ISSUE THREAD

**Issue by HiveBug** [godotengine/godot#76666]
### Godot version

4.0.2 Stable

### System information

Xubuntu 20.04 (Linux),Compatibility

### Issue description

I'm experiencing a very strange bug. I'm passing my velocity through a component, but when the object is on the ground, after a while, it stops moving, stops receiving the velocity. However, when I jump, the velocity is applied again.

### Steps to reproduce

Create a velocity component
extends

var velocity := Vector2.ZERO

func acceleration_to(move_direction: Vector2) -> void:
	velocity.x = lerpf(velocity.x, move_direction.x * 500.0, 0.4)
	velocity.y += 3000.0 * get_physics_process_delta_time()

func move() -> void:
	owner.velocity = velocity
	owner.move_and_slide()

Call on player script
func _physics_process(delta: float) -> void:
	$VelocityComponent.acceleration_to(Vector2(Input.get_axis("ui_left", "ui_right"), 1.0))
	$VelocityComponent.move()

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/11369452/bug.zip)

**Comment by AhNesh** [comment]
Hi,

In velocity_component, the velocity property is never zeroed, so the y component keeps increasing every frame. When this value has become sufficiently large (50 000) and because up_direction on player is (0, -1) (down), so much of the movement is into the ground that move_and_slide doesn't slide anymore.

Jumping isn't in the MRP, but I guess when you jump you set the y component to an upwards value, effectively resetting the y component of velocity. 

Removing the `+=` on line 8 in velocity_component seems to fix the problem
`velocity.y = 3000.0 * get_physics_process_delta_time()`

**Comment by HiveBug** [comment]
But on line 8 apply gravity, maybe check if not on floor ?

**Comment by AhNesh** [comment]
Ahh, I see. You can take advantage of the fact that `move_and_slide()` modifies `owner.velocity` to the actual velocity after handling collisions and sliding. If you update velocity_component's velocity with `owner.velocity` after `move_and_slide()`, it will reset y velocity when on the floor but keep it when in the air, and keep x velocity as long as player is not running into a wall.

So `move()` becomes
```GDScript
func move() -> void:
owner.velocity = velocity
owner.move_and_slide()
velocity = owner.velocity
```

Should work with jump as well.

**Comment by HiveBug** [comment]
Thank you

**Comment by Calinou** [comment]
Closing, as this isn't a bug.
