### ISSUE TITLE
GridMap Updates Only Once After Re-Export

### ISSUE THREAD

**Issue by SolarLune** [godotengine/godot#767]
So this is kind of an edge case, but GridMaps using a MeshLibrary file only update once after overwriting that MeshLibrary file with a new one. After this, you have to restart Godot for the changes to happen. To describe my process in more detail:

1) Import a scene of tiles and convert it to a MeshLibrary.
2) Create a GridMap and use the MeshLibrary as the theme.
3) Reimport the scene of tiles and convert it to a MeshLibrary, not merging it with the previous MeshLibrary file, but overwriting it.
4) Check the GridMap, and it should update with the new tiles.
5) Repeat 3 and 4, but the GridMap no longer updates with new tiles.

This being a weird situation, if necessary I can provide a video showing the problem in action. Thanks.

**Comment by akien-mga** [comment]
Is this issue still valid in the current master branch?

**Comment by akien-mga** [comment]
Ping. Can anyone confirm this bug?

**Comment by akien-mga** [comment]
I can't reproduce this in the current master branch, so I guess it has been fixed somehow.

**Comment by ludorverr** [comment]
The Mesh Library doesn't like being overwritten.
**Godot version:** Godot Engine v3.1.beta2.official

-new project, choose 3D Scene Root Node
-from the filesystem drag meshes into scene (tested .obj and .escn)
-Convert to mesh library (tested all three extensions)
Take note of the resulting meshlibrary-file's filesize
-Remove or add meshes to the scene
-Convert to mesh library, overwrite old mesh library file
The filesize will remain the same.

I had unwanted entries in the Gridmap that I was unable to remove. Re-converting the meshlibrary and reloading it in the Gridmap did nothing. The problem was solved by deleting the meshlibrary-file and saving a new one then loading it back in the Gridmap.
SolarLune mentioned restarting Godot might do something, but nope, I am unable to overwrite mesh libraries.
