### ISSUE TITLE
Shaders behave inconsistently

### ISSUE THREAD

**Issue by Booklight12** [godotengine/godot#76777]
### Godot version

4.x

### System information

Android Windows

### Issue description

The godot shader behaves differently in 2d and 3d. Here I used the same noise map and visual shader structure, but only the 3d shader is in the loop.

### Steps to reproduce

Create a shader.

### Minimal reproduction project

I'll add this option in the comments.

**Comment by Booklight12** [comment]
[Example](https://github.com/Booklight12/text/blob/main/Example.zip)

**Comment by Chaosus** [comment]
This is because the Texture2D lack the repeat parameter for the texture. You can fix it by passing the texture parameter with noise texture to sampler port:

![image](https://user-images.githubusercontent.com/3036176/236620006-9faf711d-2859-40d3-af37-90ac47544d0e.png)

Here is fixed version of this project - [FixedExample.zip](https://github.com/godotengine/godot/files/11412150/FixedExample.zip)

**Comment by Booklight12** [comment]
Yes, it did after testing
