### ISSUE TITLE
Mouse to Tilemap grid coordinate display

### ISSUE THREAD

**Issue by Zentropic** [godotengine/godot#76801]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Windows 11, AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz

### Issue description

  In the 3.x versions of Godot, the current tilemap grid cell position of the mouse was displayed but this seems to have disappeared in 4.x.  Is there any reason why this information isn't being displayed anymore ?  Furthermore, it would also be extremely useful if the mouse position was displayed regardless of whether a tilemap was being edited or not.  In 3.x I had this capability with a plug-in but is there any reason why it shouldn't just be built into the Editor ?

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Tracked in godotengine/godot-proposals#5792

**Comment by kleonc** [comment]
> In the 3.x versions of Godot, the current tilemap grid cell position of the mouse was displayed but this seems to have disappeared in 4.x. Is there any reason why this information isn't being displayed anymore ?

I guess the reason is it was never reimplemented. :upside_down_face: There's already a PR for it though: #68800. Since it's being tracked by https://github.com/godotengine/godot-proposals/issues/5792, I'll close this issue.

>Furthermore, it would also be extremely useful if the mouse position was displayed regardless of whether a tilemap was being edited or not. In 3.x I had this capability with a plug-in but is there any reason why it shouldn't just be built into the Editor ?

That's a material for a proposal, it doesn't belong here (this is a bug tracker). It's already proposed/tracked in https://github.com/godotengine/godot-proposals/issues/3007.
