### ISSUE TITLE
Z-index for the Button node? Or... all Control Nodes?

### ISSUE THREAD

**Issue by Qws** [godotengine/godot#7692]
Why is there no z-index for the Button node, Panel node and I believe all Control Nodes?

When I press on the button in my game, a panel should be sliding from out of camera view into the camera view. The panel should be beneath the button on Z-Index. But instead it overlaps the button.

But for some reason it doesn't has Z-index option. And from the other controls I've seen, none actually do... is there a particle reason for it?

I'm using Godot 2.1.2 Stable.

**Comment by reduz** [comment]
GUI, like most 2D in Godot, is displayed on tree-order. No index is
provided.

**Comment by Hinsbart** [comment]
Note that you can still set the z-index for controls manually: `some_control.set("z", index)`.

**Comment by AlexHolly** [comment]
I tried `some_control.set("z", index)` it looks like it has no effect I tried 2.1.2 stable and 3.0

I am using Sprites that have a z-index > 0 and the UI should be on top of the sprite but it looks like the z-index from control is 0 and there is no way to change it.

![image](https://user-images.githubusercontent.com/4741886/26851962-de76ab78-4b0c-11e7-85ca-2d4868a82521.png)

```
extends Control

func _ready():
	set("z", 2)
	$WindowDialog.popup()

```
![image](https://user-images.githubusercontent.com/4741886/26852299-25f9cc0e-4b0e-11e7-995d-cd3284292c25.png)



I could probably solve this somehow with all sprites having a z-index<0 but it looks more like a missing feature or bug.

**Comment by jahd2602** [comment]
> GUI, like most 2D in Godot, is displayed on tree-order. No index is provided.

Sprites are displayed on tree-order, but they have z-index that we can change to fine-tune without too many complications. GUI controls should also have that option.

**Comment by henriquelalves** [comment]
Giving my two cents here, but z-index should be a CanvasItem property, not a Node2D one (that way it would be editor configurable for both Control and Node2D).

**Comment by swarnimarun** [comment]
Has anything progressed o this topic?
And I like the idea of Z-Index being property of Canvas_Item. But the problem seems to be of the fact that z-index doesn't work in 3D but Controls work in 3D so how should it implemented.

**Comment by MrHoothoot** [comment]
This would be a nice feature. It adds more flexibility.

**Comment by reduz** [comment]
The reason why Z-Index is not exposed in controls is because it won't work
as you expect it to. The control may be displayed on top of other controls,
but as input is handled strictly in tree order,  your control won't get
input by being on top of other controls.

If you want it to appear on top of others, use set_toplevel() instead, and
your control will not depend on the parent controls, as well as appearing
on top.

**Comment by eligt** [comment]
@reduz Is input handling the only reason for such limitation? I personally use lots of Labels and other controls exclusively for their display function while all input is handled higher up in a root node (as that's the only level at which input state becomes relevant). Unless there's a different way to display text that I'm missing, then I think it's quite cumbersome to limit z-sorting of UI elements just because of Input handling as 90% of use cases will be for display-only.

**Comment by raffomania** [comment]
So, given the following Tree:
```
SpriteControl
  Sprite
GUIControl
```
When I set a z-index > 0 on `Sprite`, as well as `Z as relative` to `true`, `Sprite` still draws over children of `GUIControl`. 

Given that Controls are drawn in tree order, shouldn't `GUIControl` draw over all children of `SpriteControl`, if they have `Z as relative` set to `true`?

**Comment by deepmax** [comment]
> So, given the following Tree:
> 
> ```
> SpriteControl
>   Sprite
> GUIControl
> ```
> 
> When I set a z-index > 0 on `Sprite`, as well as `Z as relative` to `true`, `Sprite` still draws over children of `GUIControl`.
> 
> Given that Controls are drawn in tree order, shouldn't `GUIControl` draw over all children of `SpriteControl`, if they have `Z as relative` set to `true`?

Is there any workaround for this?

**Comment by Zylann** [comment]
Hello, here is a use case:
![image](https://user-images.githubusercontent.com/1311555/48667140-ba500d00-eac7-11e8-858e-85f643a8a68f.png)

I need this because I want the size of my background to adjust with the width of the label.

**Comment by AlexHolly** [comment]
Like this maybe?
![image](https://user-images.githubusercontent.com/4741886/48669181-3ade3000-eaff-11e8-9770-19696c1254d0.png)

**Comment by razcore-art** [comment]
I see this is a long-standing discussion. I'll throw my 2 cents in cause I also found it unintuitive that you can't z-order Controls given they're supposed to be visual elements, apart from Containers. I understand that the reason is input handling. @reduz couldn't we then handle input in z-order and if same z-order in tree order?

I was doing something that requires this sort of layout, but I want to then place some nodes on top of others visually. It makes sense to me that they receive input on the visual order too (z-order) more so than tree order, if they were to have a z-order property.
![image](https://user-images.githubusercontent.com/1177508/51424059-5df59080-1bd1-11e9-881b-41981fadb00d.png)

This is the node setup:
![image](https://user-images.githubusercontent.com/1177508/51424077-95fcd380-1bd1-11e9-8bea-20e50bc88466.png)

When I do say this:
```gdscript
func _ready() -> void:
	get_child(3).set_as_toplevel(true)
```

It messes it up so that's not an option
![image](https://user-images.githubusercontent.com/1177508/51424084-b9c01980-1bd1-11e9-832e-9476cb035e69.png)

As a workaround I see if I set `TextureRect`s' `show_behind_parent` to `true` and then proceed to set one to `false` it visually does the job, so I guess that works, but then as I understand it, the input will still be processed in reverse tree order, I really think these properties should be considered for input.
![image](https://user-images.githubusercontent.com/1177508/51424114-2b986300-1bd2-11e9-9d2d-f4bdfd19efd9.png)

**Comment by KoBeWi** [comment]
If you put Control under Node2D, it will inherit its Z-index. That should be anough in most cases, UI is supposed to go on separate CanvasLayer anyways.

**Comment by sethboyles** [comment]
One issue with the z-index being tied to tree order is that for the various Containers, display position is also tied to tree order.  Meaning if you have a Control that moves out of the bounds of its parent Container (say, in an animation), you have to no way of controlling which bordering elements it goes over or under, it will always go over elements to the left and under elements to the right (or above and below).

The Node2D solution doesn't work here, because then you lose the formatting of the Container.

**Comment by Calinou** [comment]
Closing in favor of https://github.com/godotengine/godot-proposals/issues/839, as feature proposals are now tracked on the Godot proposals repository.
