### ISSUE TITLE
C# Export attribute error

### ISSUE THREAD

**Issue by lh472266503** [godotengine/godot#76953]
### Godot version

v4.1.dev.mono.custom_build [f717cc0a3]

### System information

Windows 10, Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti, Intel i5-8300H

### Issue description

When I use the "Export" attribute to export variables in C#, regardless of whether they are of type "Node" or "Resource", the creation dialog in the inspector in the editor is always the one for creating a "Resource", and it contains all "Resource" types instead of the matching ones.
![@178RCSD21_F0FHMZIUQ{R7](https://github.com/godotengine/godot/assets/60731523/ef00f757-8db7-4e14-880c-74ce0900e5c4)
![image](https://github.com/godotengine/godot/assets/60731523/20758324-cf13-43f2-a89c-61c82da8500e)

### Steps to reproduce

"Open the "Test" scene in the "Demo" project, which contains two "Export" variables - one is of type "Texture2D" and the other is of type "Node". Please check and create them in the inspector of the editor interface."

### Minimal reproduction project

[Demo.zip](https://github.com/godotengine/godot/files/11453248/Demo.zip)

**Comment by raulsntos** [comment]
This was caused by https://github.com/godotengine/godot/pull/69988 when adding a new member to the `PropertyHint` enum made the `PROPERTY_HINT_NODE_TYPE` change its value from 34 to 35.

The C# source generator that generates the property info that is retrieved by the inspector is still generating 34 because the enum wasn't updated in the C# side.

This kind of change breaks compatibility, because libraries that were compiled against an older version of GodotSharp will use the old enum values. So I think the fix would be to move the new enum member to the end of the enum to prevent breaking compatibility while we still can before the 4.1 release.
