### ISSUE TITLE
Color Widget's HSV mode doesn't update the hue properly when saturation is 0.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#76968]
### Godot version

4.0.2

### System information

Ubuntu 22.04.1 LTS

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/4bd89bb0-f4d9-4aa9-8846-0a728e97e1bc)

Notice how the hue is on the blue color, but the saturation is insists on remaining red.

If I change the saturation a little bit, the correct value will apply. But if I adjust the value or the alpha, the blue hue will be punched out and become red again.

### Steps to reproduce

Go to a ColorPicker in the editor (say, the modulate property of Node2D), open the color picker, and copy the above configuration in the HSV tab.

### Minimal reproduction project

N/A

**Comment by KoBeWi** [comment]
Slider colors are taken directly from the picker's color, not from other sliders. Hue is undefined if saturation is 0.

**Comment by dinoplane** [comment]
However, the hue seems to reset back to red when saturation is put to 0... I personally wouldn't want the hue value to change.

**Comment by dinoplane** [comment]
I wanna see if I could tackle this one cuz it looks kinda funky.

**Comment by dinoplane** [comment]
Upon further investigation, a way to reproduce this issue better is to: 
1. Click a random location on the slider (say saturation) that is not on the endpoints of the slider. Let go of the mouse.
2. Click and drag the slider to 0.
3. The bug will appear like so.

It seems there might be some weirder business going on too. When dragging from a non endpoint value to an endpoint, the `_set_pick_color ` function is called twice.

Below: I placed print statements in `_value_changed` and `_set_pick_color`
![image](https://github.com/godotengine/godot/assets/46456372/bef3d791-107d-44f3-b86d-94331a40bad7)

![image](https://github.com/godotengine/godot/assets/46456372/c816a812-db18-4daa-8993-162bbdca3b39)

Here is what happens when I set the saturation slider to 1:

![image](https://github.com/godotengine/godot/assets/46456372/6853c514-fc1a-4f3f-b9ea-6f35d469660b)

Here is what happens when I set saturation to 0:

![image](https://github.com/godotengine/godot/assets/46456372/ba6e3a91-1e81-4072-9fc5-9fcf176d81b3)

As one can see... _set_pick_color is called twice...

**Comment by dinoplane** [comment]
I can also reproduce the "calling `_set_pick_color` twice" behavior sometimes by double clicking the slider...
