### ISSUE TITLE
`OS.has_feature("linux")` returns false on linux

### ISSUE THREAD

**Issue by bend-n** [godotengine/godot#76990]
### Godot version

c80a2b4fe

### System information

ArchLinux x11

### Issue description

```gdscript
OS.has_feature("linux")
```
returns false.
This is a problem because:
- its a regression
- [documentation](https://docs.godotengine.org/en/stable/tutorials/export/feature_tags.html#default-features) tells you it works
- it works on other platforms
- it breaks gdextension, where you specify libs with feature tags: `linux.release.x86_64 = "res://lib.so"`

Regression introduced somewhere between bd1bc68..6980b2b
<sup>Causes [gdext#270](https://github.com/godot-rust/gdext/issues/270)</sup>

**Comment by bruvzg** [comment]
In 4.x it's `linuxbsd` not `linux`.

**Comment by bend-n** [comment]
Thats not what the docs say:
![image](https://github.com/godotengine/godot/assets/70787919/20f9296c-2401-40ff-9337-4f6eb8eb9b6b)

**Comment by bend-n** [comment]
Also, this hasnt been the behaviour of 4.x until recently, when did it change?

**Comment by bruvzg** [comment]
> Also, this hasnt been the behaviour of 4.x until recently, when did it change?

Seems like you are right, it is a recent and probably unintentional breaking change from https://github.com/godotengine/godot/pull/76540.

**Comment by bend-n** [comment]
Seems to be fixed by #76974

**Comment by aaronfranke** [comment]
To be clear, Linux and BSD libraries/executables/etc are not automatically compatible. They are just similar platforms so they can be compiled from mostly the same codebase (thus the name LinuxBSD). It is necessary for `OS.has_feature()` to support distinguishing between Linux and BSD (and probably also between the different BSDs). So the behavior that #76974 is restoring is necessary to support this.

**Comment by aaronfranke** [comment]
@dalexeev [Those are already added.](https://github.com/godotengine/godot/blob/master/platform/linuxbsd/os_linuxbsd.cpp#L202-L214)

**Comment by dalexeev** [comment]
I mean

<details>
<summary>this list</summary>

![](https://github.com/godotengine/godot/assets/47700418/ba412640-c5ab-4f89-88b1-c3bda81f222f)

</details>

**Comment by akien-mga** [comment]
I don't think we need to, BSD platforms are second class citizens as we don't provide official export templates for them. Users who compile their own export templates for one or more BSD platform can add the relevant feature tags manually which should Just Work™.

**Comment by dalexeev** [comment]
Okay, although I would add `linuxbsd` and `bsd` to the list (without the `*bsd` sub-options). **But `bsd` must include all BSDs, not just others than the 3 main ones.**

I think it makes sense to refresh [the page](https://docs.godotengine.org/en/stable/tutorials/export/feature_tags.html) because it doesn't mention `*bsd` sub-options.

By the way, the list of platforms is using the wrong name, I guess it should be Linux/BSD.

![](https://github.com/godotengine/godot/assets/47700418/9027e165-f806-4ed7-b5cb-ac0198aeb96d)

**Comment by akien-mga** [comment]
> Okay, although I would add `linuxbsd` and `bsd` to the list (without the `*bsd` sub-options). **But `bsd` must include all BSDs, not just others than the 3 main ones.**

That's right, I thought that's what it did, but after #76974 it's not the case. Should be extended further to also accept the `bsd` feature tag for FreeBSD, OpenBSD and NetBSD.

> By the way, the list of platforms is using the wrong name, I guess it should be Linux/BSD.

It's tricky because technically the export templates it will use by default are for Linux (X11, but hopefully soon Wayland too so indeed the `/X11` part could be removed). But indeed if you want to target say FreeBSD, you'd likely start by adding a "Linux/X11" preset and then customize it to use custom export templates.

**Comment by dalexeev** [comment]
I think the solution is to add the following code to `OS_LinuxBSD::_check_internal_feature_support()`:

```cpp
#ifndef __linux__
    if (p_feature == "bsd") {
        return true;
    }
#endif
```
