### ISSUE TITLE
Expose collision resolution bias in editor for rigid bodies/collision shapes

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#7700]
It would be very useful to extend the PhysicsServer interface and rigid bodies to expose a custom bias for collision resolution and add a global property with the default bias factor for the project. In fact I had to change it in the PhysicsServerSW implementation to have small bodies not to sink inside polygonal collision shapes.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
