### ISSUE TITLE
Parallelize rigid body islands resolution

### ISSUE THREAD

**Issue by m4nu3lf** [godotengine/godot#7702]
**Operating system or device - Godot version:**
Godot 2 - 3.0

**Issue description:**
![parallelizable_code](https://cloud.githubusercontent.com/assets/5478365/22528782/a7d5757e-e8cc-11e6-8b44-7ab7436f6f56.png)
In this loop each iteration is indipended from each other. I think this is a good opportunity to parallelize the physics engine. We could have a number of worker threads (tunable by the user thorugh a project property or through a new method of the PhysicsServer interface) and dispatch the islands to the different threads trying to balance the number of constraints each worker thread will process.

This should give a big speed up for cases when we have many ragdolls, as the task of solving multiple ragdolls can be spread among different cores/hw threads.

**Comment by reduz** [comment]
indeed, physics work in general was planned for godot 3.1

**Comment by m4nu3lf** [comment]
Cool, If I can carve some time and efforts out of my spare time I could participate, but I'm not sure I will be able to, so for now I'm just creating these issues so that the things I've noticed don't get forgotten.

**Comment by madmiraal** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
