### ISSUE TITLE
Connecting to a WebSocket Server from the browser fails

### ISSUE THREAD

**Issue by FoggyFella** [godotengine/godot#77059]
### Godot version

4.0.2 stable

### System information

Windows 10, NVIDIA 1060, Vulkan Mobile

### Issue description

Connecting to a WebSocket Server from inside browser fails with the error:
```WebSocket connection to 'wss://myserveriphere:8888/' failed: WebSocket is closed before the connection is established.```

I can connect to the server just fine from a windows build. I am using itch.io to host this game on the web, could something on itch be blocking my connection?

### Steps to reproduce

Here is the code I use for server/client logic:

```gdscript
func create_game(server:bool):
	var peer = WebSocketMultiplayerPeer.new()
	if server:
		var err = peer.create_server(8888)
		if err == OK:
			print("created server")
			multiplayer.multiplayer_peer = peer
			multiplayer.peer_connected.connect(player_connected)
			multiplayer.peer_disconnected.connect(player_disconnected)
		else:
			push_error("Error creating server: " + str(err))
	else:
		var url = "wss://myserveriphere:8888"
		var err = peer.create_client(url)
		if err == OK:
			print("created client")
			multiplayer.multiplayer_peer = peer
		else:
			push_error("Error creating client: " + str(err))
```
Also I uploaded a reproduction project.

### Minimal reproduction project

[WebMultiplayer.zip](https://github.com/godotengine/godot/files/11471687/WebMultiplayer.zip)

**Comment by Faless** [comment]
So, I was not able to reproduce the issue you describe, but I was able to reproduce something similar, which I think it's what you are facing.

Your code is starting a websocket server on port `8888` **without TLS**, but you are connecting to it **using TLS** (i.e. `wss` and not `ws`).
In this scenario, the connection will fail, printing the error you describe on the browser, and silently on the desktop (you could listen for `multiplayer.connection_failed` signal on the godot side to catch this event).

You probably need to use `wss` on the web, since the page on itch is `https` (and browsers will refuse non secure connections). More so, you will need a valid TLS certificate for browsers to allow the connection to happen (you can get free TLS certs via https://letsencrypt.org/ ).

There are then 2 ways to make the websocket server use TLS:
1. Use it directly via `TLSOptions.server(load("/path/to/server.key"), load("/path/to/server.crt"))`
2. Use it via proxy, letting letsencrypt configure your web server for TLS, then configure it to proxy your local server.

E.g. for nginx:

```
        location / {
                if ($http_upgrade = "websocket") {
                        proxy_pass http://localhost:8888;
                }
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
```

**Comment by FoggyFella** [comment]
@Faless Thank you so much! I figured out how to get TLS certificates and it all seems to be working just fine.
