### ISSUE TITLE
New project with C# (Mono Editor) in Godot 4.1dev2 doesnt compile.

### ISSUE THREAD

**Issue by Kirbyrawr** [godotengine/godot#77068]
### Godot version

4.1.0-dev.2

### System information

Microsoft Windows 11 Pro Version 10.0.22621 compilation 22621, CPU Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 2001 Mhz, 4 main cores, 8 logic processor, 16GB RAM

### Issue description

In a new project, created from zero with only one script in it (a non modified c# script) using Godot 4.1.0-dev2, when you press build it gives you weird errors about NET Standard.

As extra information i can say that using 4.0.1 worked properly with the same NET SDK
4.0.3RC2 also works ok.

Please check the image below:
![imagen](https://github.com/godotengine/godot/assets/3259762/501b6fee-539c-4cfb-8ce2-0328ac2ca0be)

### Steps to reproduce

- Download 4.1dev2 with mono.
- Create new project.
- Create a new c# script.
- Having NET 6 installed, try to compile.

Also tried upgrading a previous working project.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11472258/Test.zip)

**Comment by Kirbyrawr** [comment]
> Tested locally on my Linux system, I can't reproduce the issue.
> 
> The SDK you're missing should be downloaded automatically from https://www.nuget.org/packages/Godot.NET.Sdk/4.1.0-dev.2
> Were you connected to the Internet?

Hi @akien-mga, i was connected to internet for sure. When it happened i tried the version 4.0.3RC2 and it worked alright, however this version was still not working.

As proof of it i can say that i wrote this issue when testing it in the same computer.

**Comment by raulsntos** [comment]
Are you able to restore packages from outside Godot? Running the command `dotnet restore` from a console.

If you are still unable to restore the Godot.NET.Sdk, it may be an issue with your NuGet configuration. Try adding a new `NuGet.config` file to the project (same folder that contains the `project.godot` file). You can create this configuration file with the `dotnet new nugetconfig` command, it should contain this configuration:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```

Then try restoring packages again. If it still doesn't work, can you share the contents of the NuGet configuration file at `%APPDATA%/NuGet/NuGet.Config`? Also any files that may exist in the `%APPDATA%/NuGet/config` directory.

Also, are you using the [Azure Artifacts Credential Provider](https://github.com/Microsoft/artifacts-credprovider)?

---

> As you can see is trying to find something of NET Standard of a version that doesn't exist when in reality it should be using NET 6 or 7

I don't think this means anything since .NET Standard version **0.0** is not a valid version, it's likely .NET couldn't resolve the package and doesn't have the TFM information so [`NuGetFramework`](https://github.com/dotnet/dotnet/blob/f560e950381f5c2670ee56df89821db4660edd5f/src/nuget-client/src/NuGet.Core/NuGet.Frameworks/NuGetFramework.cs) prints that by default.

**Comment by Kirbyrawr** [comment]
Closing due to being fixed in new versions
