### ISSUE TITLE
Parser bug when trying to access attribute inside method call with variant type argument

### ISSUE THREAD

**Issue by snailrhymer** [godotengine/godot#77066]
### Godot version

v4.0.2.stable.official [7a0977ce2]

### System information

Pop!_OS 22.04 LTS

### Issue description

`Parser bug (please report): Trying to check compatibility of unset value type`

happens whenever a `.` is used to access a variable's attribute as part of an expression for an argument with explicit type "Variant".

See reproduction steps for an example with a user-defined function, but the bug also happens with e.g. `Array.count()` or `Dictionary.has()`.

### Steps to reproduce

In a new script, define a new function:

```
func my_function(safe_argument, bad_argument:Variant):
    pass
```

then in e.g. `_ready()` start typing out a call to `my_function` where the argument will be an attribute of some variable:

```
func _ready():
    my_function(safe_variable.property, bad_variable.property)
```

The parser bug will occur when the `.` character is typed after `bad_variable`.

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
Same in v4.1.dev.custom_build [fb10f45ef].

**Comment by KhalilBenGaied** [comment]
i suggest to adjust the previous code to the following : 
func _ready():
    var safe_property = safe_variable.property
    var bad_property = bad_variable.property
    my_function(safe_property, bad_property)
--------------------------------------------------------
This approach  bypass the bug in the parser by first storing the properties you want to pass into a variable, and then passing these variables into the function instead of directly using the properties as arguments.

This way, you're not trying to pass an attribute of a variable directly as a function argument  in the same line, which is what seems to be triggering the parser bug, by   splitting it into multiple steps, the parser won't try to infer the type of an attribute of a variable and pass it as a function argument in the same operation, which can help you avoid the bug 
i hope this helped in the process of figuring this out or fixing it i'm waiting for your feedback.
