### ISSUE TITLE
LightmapGI: Dynamic objects don't update immediately after baking lightmaps or (re)loading a scene

### ISSUE THREAD

**Issue by DearthDev** [godotengine/godot#77167]
### Godot version

4.0 dev

### System information

Windows 10

### Issue description

When dynamic objects are baked, they will not receive global illumination from lightmap captures until they are updated by means such as toggling their dynamic status or by moving them. This issue seems to stem from the pairing code, which is not being executed on the instances following the baking process.

### Steps to reproduce

1. Add objects to a scene with their global illumination mode set to dynamic.
2. Bake a lightmap.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
I can confirm this on 4.2.beta da0b1eb12 (Linux, GeForce RTX 4090 with NVIDIA 535.113.01).

**Comment by SpockBauru** [comment]
I can confirm that it's still an issue on both 4.3 stable and 4.4dev2. In addition, the issue also happens if a character have the animation disabled.

Another way to trigger the issue is to hide/show the LightmapGI node. Test steps on the video:
1) Hide/Show LightmapGI in order to trigger the bug.
1) Enabling the animation fixes the bug on the character.
1) Moving the capsule manually also fix the bug.

https://github.com/user-attachments/assets/3e9a0c4c-4c88-4eea-8680-33c4e38e877d

Test scene:

[LightProbeEnableTest.zip](https://github.com/user-attachments/files/16400932/LightProbeEnableTest.zip)

System Info:
`Godot v4.4.dev2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.5186) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)`

**Comment by Calinou** [comment]
I've made an MRP with additional scenarios for updating dynamic objects. If the rendering is happening correctly, the torus should be tinted red instead of having the environment lighting applied to it.

**Minimal reproduction project:** [test_lightmapgi_dynamic_object_update.zip](https://github.com/user-attachments/files/17414285/test_lightmapgi_dynamic_object_update.zip)

Run the project and press the on-screen keys to (un)load the LightmapGI, the LightmapGIData, toggle the LightmapGI's visibility and the dynamic object's visibility. If this bug is fully fixed, the lighting on the dynamic object should always be rendered whenever the lightmaps are visible on static objects, without needing to toggle the dynamic object's visibility.

**Comment by Lamoot** [comment]
As a user that's been recently learning about Godot's Lightmap GI, it'll be very nice once this issue is fixed.

It's a source of some frustration when trying to figure out whether I was missing something, I didn't read the documentation properly, or Godot is not working as intended.

Thank you for looking into it :saluting_face:

**Comment by Jamsers** [comment]
Just a heads up ya'll, this bug seems to have returned in the latest 4.5.beta3 (and possibly earlier, I've only tested beta3). You can easily confirm this with the [#96165 MRP](https://github.com/user-attachments/files/16762796/lightmap_broken.zip)

My system info:
`Godot v4.5.beta3 - Ubuntu 24.04.2 LTS 24.04 on Wayland - Wayland display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU - AMD Ryzen 5 5600H with Radeon Graphics (12 threads) - 14.48 GiB memory`

**Comment by Calinou** [comment]
> Just a heads up ya'll, this bug seems to have returned in the latest 4.5.beta3 (and possibly earlier, I've only tested beta3). You can easily confirm this with the [#96165 MRP](https://github.com/user-attachments/files/16762796/lightmap_broken.zip)

That project uses physical light units. Dynamic object lighting appears broken no matter where the object is (when it's within LightmapGI bounds), even if you move it in the editor after reloading the scene. This is a separate issue which is tracked in https://github.com/godotengine/godot/issues/88168.

This is the case both on 4.4.1.stable and 4.5.beta3, even after rebaking lightmaps in each.
