### ISSUE TITLE
All ExtResource ids change after saving (4.1 regression)

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#77172]
### Godot version

v4.1.dev.custom_build [a8453cb33]

### System information

Windows 11, Core i5-12400F, RX 6600

### Issue description

in recent custom 4.1 builds it is regening every ext id on every save even if just one simple file

	[gd_scene load_steps=2 format=3 uid="uid://bj3w1run711x7"]

	[ext_resource type="Texture2D" uid="uid://c082xolc76p8n" path="res://icon.svg" id="1_ftki2"]

	[node name="Node2D" type="Node2D"]

	[node name="Sprite2D" type="Sprite2D" parent="."]
	position = Vector2(351, 294)
	texture = ExtResource("1_ftki2")

can use a script like this save all files and regen all ext ids in project

	@tool
	extends EditorScript

	func listFiles(path: String, extensions: Array = []) -> Array:
		var list := []
		for dir in DirAccess.get_directories_at(path):
			if not dir.begins_with("."):
				list.append_array(listFiles(path + dir + "/", extensions))
		for file in DirAccess.get_files_at(path):
			var ext := file.split(".")[-1]
			if not file.begins_with(".") and ext != "import":
				if extensions.is_empty() or ext in extensions:
					list.append(path + file)
		return list

	func _run() -> void:
		for file in listFiles("res://", ["tscn", "tres"]):
			ResourceSaver.save(load(file))

in 4.0.2 this script does not regen every ext id in the project each time it is run (just when needed) but in latest 4.1 it does
but just ctrl+s works'nt too

thanks

thought it was related to this but maybe not
https://github.com/godotengine/godot/issues/76693

### Steps to reproduce

- make new scene with ext resource (new control, new sprite, set texture to icon)
1 - save, stage changes
2 - goto 1

or can use script on any project to see that it applies to everything, everywhere, all at once

### Minimal reproduction project

n/a

**Comment by DevanOBoyle** [comment]
I'm interested in tackling this issue.

**Comment by AThousandShips** [comment]
Note that these are ExtResource IDs not SubResource IDs which are non-external, this seems to be handled here:
https://github.com/godotengine/godot/blob/da21cb7042b09de24964b9bd5a1a8e1d93ab4b8b/scene/resources/resource_format_text.cpp#L1971
And here:
https://github.com/godotengine/godot/blob/da21cb7042b09de24964b9bd5a1a8e1d93ab4b8b/scene/resources/resource_format_text.cpp#L1859

**Comment by vmedea** [comment]
i've noticed this running recent builds of master as well, it makes git history hard to read due to the noise on every save. If it's useful i could bisect it to find what commit introduced this behavior.

**Comment by vmedea** [comment]
I narrowed it down to: 8983b20ccd2f8a91d87789f2c0dd90f4e31b8b2c

**Comment by KoBeWi** [comment]
This issue makes the current version unusable for people using VCS.

**Comment by Mitten-O** [comment]
I'm not sure if this is related, but 
I'm adding this as a comment here, because googling my problem led me here, and will likely others.

When I recently loaded a project created with some older version of Godot, all the uids my tres files used to refer to .import files were mismatched with the uids in the import files themselves.
The error was `Condition !unique_ids.has(p_id) is true. Returning: String()` in that version of Godot, but is better in current master.
If I made any change to tres file in Godot and saved it, the UID was automatically fixed, but there were hundreds of them, so
I made this script to fix the uids: https://gitlab.com/-/snippets/4809468
It may be a useful place to start if somebody runs into a similar situation.
