### ISSUE TITLE
Build from source crash when finish the "scons platform=linuxbsd target=template_release production=yes"

### ISSUE THREAD

**Issue by ryugold777** [godotengine/godot#77253]
### Godot version

4.1

### System information

Arch Linux

### Issue description

When finish compile from the source "scons platform=linuxbsd target=template_release production=yes" freezes my all system! I have to turn off and turn on every time when finish.

### Steps to reproduce

scons platform=linuxbsd target=template_release production=yes

### Minimal reproduction project

no project

**Comment by akien-mga** [comment]
The `production=yes` flag enables LTO (`lto=full`), which stands for Link Time Optimization and requires a lot of RAM to optimize the whole binary while linking. If your system doesn't have a lot of RAM available, this can indeed lead to freezes.

Your best bet is to turn off LTO (you can try `use_llvm=yes lto=thin` to build with LLVM instead of GCC, and it's lighter ThinLTO).

**Comment by ryugold777** [comment]
4gb ram is not enough? When I was with ubuntu everything was very well.
