### ISSUE TITLE
Add CanvasItem property that would disable buffer cleaning on each _draw() call

### ISSUE THREAD

**Issue by TeddyDD** [godotengine/godot#7728]
Currently Node or Control is cleaned on each _draw() call so you have to redraw whole thing.

When implementing custom drawing via _draw() it's not always optimal to redraw whole Node / Control. Disabling buffer cleaning in CanvasItem would allow to draw on top of prevous buffer and manually clean and redraw whole Node / Control when required.

**Comment by avencherus** [comment]
I'd also be interested in this for messing around with effects that involve drawing repeatedly without clearing the canvas.  At the moment it takes a some working around.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
