### ISSUE TITLE
Subtract blend mode produces different results with different renderers

### ISSUE THREAD

**Issue by allenwp** [godotengine/godot#77448]
### Godot version

master commit 2ab0f17 and later

### System information

Windows 11 NVIDIA 980 Ti

### Issue description

When working on #76334 I noticed that the RenderingDevice abstraction uses a different blend mode for `BLEND_MODE_SUB` than the OpenGL driver. RenderingDevice uses `BLEND_OP_SUBTRACT` while OpenGL uses `GL_FUNC_REVERSE_SUBTRACT`.

In Godot 3, OpenGL uses `GL_FUNC_REVERSE_SUBTRACT` just like Godot 4's OpenGL driver.

**RenderingDevice Abstraction:**
https://github.com/godotengine/godot/blob/b7032b5ecf8ac247e01acd5e54c9028c0dfe52df/servers/rendering/renderer_rd/forward_mobile/scene_shader_forward_mobile.cpp#L221-L222

https://github.com/godotengine/godot/blob/b7032b5ecf8ac247e01acd5e54c9028c0dfe52df/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L210-L211

https://github.com/godotengine/godot/blob/b7032b5ecf8ac247e01acd5e54c9028c0dfe52df/servers/rendering/renderer_rd/renderer_canvas_render_rd.cpp#L2124-L2125

**OpenGL**:
https://github.com/godotengine/godot/blob/4c677c88e918e22ad696f225d189124444f9665e/drivers/gles3/rasterizer_scene_gles3.cpp#L2177

https://github.com/godotengine/godot/blob/4c677c88e918e22ad696f225d189124444f9665e/drivers/gles3/rasterizer_canvas_gles3.cpp#L738

This results in a different blend result when using the Subtract blend mode in different renderers:

**Forward+:**
![Forward+](https://github.com/godotengine/godot/assets/17506573/de952b4d-e3d7-4101-a167-1460d54bd7b9)

**Mobile:**
![Mobile](https://github.com/godotengine/godot/assets/17506573/1d0ee962-8fa8-42b3-96d2-a6c45dc1c36e)

**Compatibility:**
![Compatibility](https://github.com/godotengine/godot/assets/17506573/639f6400-5b65-4552-8ba2-7c1cfb81ee12)

There appear to be some (relatively) minor differences between the Forward+ and Mobile renderers, but the difference to the OpenGL renderer is substantial because of the different blend mode function that is used.

### Steps to reproduce

1. Create some objects, such as canvas items or 3D meshes.
2. Create a material for these objects and change its blend mode to Subtract.
3. Change the renderer and note that it appears different based on the renderer.

**Important note:**
If you are testing with a Godot 4 version earlier than master commit 2ab0f17, you must also set the Depth Draw Mode to Never as described in #76334 to correctly see the Subtract blend mode.

### Minimal reproduction project

[blend-subtract.zip](https://github.com/godotengine/godot/files/11557632/blend-subtract.zip)

**Comment by BastiaanOlij** [comment]
This is likely a result of the OpenGL renderer being based on the Godot 3 renderer and may just be an oversight. @clayjohn whats your take on this?

**Comment by clayjohn** [comment]
> This is likely a result of the OpenGL renderer being based on the Godot 3 renderer and may just be an oversight. @clayjohn whats your take on this?

I think the Vulkan renderer mistakenly uses ``BLEND_OP_SUBTRACT`` instead of ``BLEND_OP_REVERSE_SUBTRACT`` For reference, ``BLEND_OP_SUBTRACT`` takes the pixel's color subtracts the background color from it and then sets the background color to the result. 

I.e. if you want to write a white pixel to a grey background with ``BLEND_OP_SUBTRACT`` you get (1, 1, 1) - (0.5, 0.5, 0.5) = (0.5, 0.5, 0.5) while with ``BLEND_OP_REVERSE_SUBTRACT`` you get (0.5, 0.5, 0.5) - (1, 1, 1,) = (0, 0, 0). My expectation is that a blend subtract mode would subtract a given color _from_ the background rather than the other way around. 

To illustrate, here is a simple example with a white background and a middle grey square on top. In Vulkan the white background is subtracted from the grey resulting in all black where they intersect

![Screenshot from 2023-05-24 17-24-00](https://github.com/godotengine/godot/assets/16521339/8b415e10-5b3f-48b5-b4ea-44ec005a18a2)

In OpenGL the grey is subtracted from the white so the final result is still grey

![Screenshot from 2023-05-24 17-24-37](https://github.com/godotengine/godot/assets/16521339/d47a53bb-9901-4525-8d11-f2eec0d76963)

**Comment by allenwp** [comment]
Given that the Subtract blend mode in Godot has historically (pre-4.0) mapped to `GL_FUNC_REVERSE_SUBTRACT`, I would expect equivalent behaviour from the new 4.0 renderers.

I think it would be good to know if there was a deliberate choice and use case that prompted the change in subtract blend mode behaviour. If not, then it might make most sense to change the new 4.0 renderers to `BLEND_OP_REVERSE_SUBTRACT` sooner rather than later…

**Comment by allenwp** [comment]
After reading @clayjohn's comments about what he would expect for the behaviour of a "subtract" blend mode, I became curious what the expected behaviour would be for a user who is not at all familiar with graphics API's `SUBTRACT` vs. `REVERSE_SUBTRACT`... As a way of determining what this might be for graphics artists, I tried out the Photoshop "Subtract" blend mode and found it to be the same as `REVERSE_SUBTRACT` in OpenGL/Vulkan:

**Photoshop:**
![image](https://github.com/godotengine/godot/assets/17506573/38895c87-63a9-4d1e-945b-2e600948ae75)

**Godot 3 (or OpenGL driver in Godot 4):**
![image](https://github.com/godotengine/godot/assets/17506573/e10d7e25-5803-4a26-a9fb-5cc1c86a203f)

I can immediately think of some use cases for the `REVERSE_SUBTRACT` style blend mode, such as a weird ghost object that is sapping away light from its (background) environment. It is harder for me to think of a use case where the background should be subtracted from the foreground object, as in the case with `SUBTRACT`.
