### ISSUE TITLE
Ability to view invisible/hidden nodes in editor

### ISSUE THREAD

**Issue by ElfEars** [godotengine/godot#7745]
In the editor, i would appreciate the ability to view all invisible/hidden nodes (by "Invisible/Hidden", i mean visual nodes (Sprites, Meshes etc.) that have been hidden by their node properties) without actually affecting their node properties, thus making it easy to return to normal (Preferably from the edit tab in the toolbar).

EDIT: It would also be appreciated as a debug option to see the invisible/hidden nodes ingame

This would be handy in so many situations as having to manually set nodes to visible to edit them is kinda annoying when working with invisible nodes.

For instance in a game I am working on, i use invisible tiles with an x texture to form walls, having to constantly set these visible and invisible to edit them and ensure they do not show up ingame is a pain!

There are many other examples that come to mind where this would be useful, plus it's a seemingly very small addition so there should be few conflicts with other features

**Comment by eon-s** [comment]
This sounds interesting but I would like to hide nodes in the editor to live edit some stuff while getting the whole visible scene running too.

Maybe an editor option to alter the visibility button behavior to editor only, debug only or both?

**Comment by ElfEars** [comment]
I was also going to suggest a debug option for seeing invisible nodes ingame but I thought that would fall under a different feature request (because when you report bugs you are encouraged to report each bug under a different issue, even if they are similar)

I was waiting to see if other people shared my interest in this feature before I posted it though

**Comment by reduz** [comment]
you already have this feature in the debugger

**Comment by ElfEars** [comment]
> you already have this feature in the debugger

Is this in 3.0, I can't seem to find it in 2.1.2?

If you are talking about the remote inspector, I was asking for a way to mass show invisible nodes, sorry if I didn't make that clearer

**Comment by reduz** [comment]
yes, it's in 2.x

![image](https://cloud.githubusercontent.com/assets/6265307/22690865/7292823c-ed16-11e6-8fc0-60e637131972.png)

**Comment by ElfEars** [comment]
Ah, again though.. I was asking for a way to show **all** invisible nodes, not just individual ones...
(once again, sorry if i didn't make this clear enough)

**Comment by reduz** [comment]
That is all the nodes in the running game, there are no invisible nodes

**Comment by ElfEars** [comment]
OH... once again... sorry for my vague vocabulary..

When i said "Invisible nodes" i meant visual nodes (sprites, models etc) that have been hidden by their node properties...

**Comment by KoBeWi** [comment]
Related: #2945

**Comment by aaronfranke** [comment]
Another option is to save more nodes as scenes, then only hide the scene instance. This lets you edit the hidden nodes without changing them, by opening them in their own editor tab.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
