### ISSUE TITLE
Mobile launcher app for data.pck games

### ISSUE THREAD

**Issue by guppy42** [godotengine/godot#7748]
Since all your game can be put in a data file ( data.pak ) with no change to the binary would it not make sense to have a official Godot meta launcher for the supported mobile OS'es.

And by meta launcher I mean an app already on the appstore(s) that can 'catch' .godot files ( renamed ,pak files ) from a browser and save/launch them.

For professional games that obviously wont do, but it would be a massive boon to hobbyists that are just getting started as it would be a lower barrier to entry to try mobile development.

In case your wondering; it can be done, and shouldn't violate the ToS of the stores as Minecraft already does this with it's .mcworld files ( which contains both data and code )

**Operating system or device - Godot version:**
Android/iOS/Blackberry - 3.0 ?

**Issue description:**
Mobile development has a barrier to entry so high it may well deter people from ever trying

**Steps to reproduce:**
Make a game and decide that it would be a good fit for mobile

**Comment by bojidar-bg** [comment]
A few points:
1. First of all, there is already FDroid for FOSS games (e.g. Minilens). Not usable for closed-source games though.
2. There are some other alternative stores, though most are probably ugly to work it.
3. Because we have `Globals.load_resource_pack`, we can have the application to be written in Godot. If it is opensource, we might actually host it on FDroid.

As a side note, keep in mind that those applications would have just as much permissions as the meta-app itself, plus would have a partly shared user:// path. Just for the record, I'm slightly sceptical of such an idea though.
Finally, you don't need any app store license to develop for android, though you might need a developer license from apple if you want to develop for iOS.

**Comment by guppy42** [comment]
The main issue with with the alternative stores is the need to enable 'unkown sources' ( android ) or jailbreak ( iOS ).

if you just want to show your friends/familie/followers your latest work that's a bit much to ask of them.

If you want to make a free ( if not opensource ) game paying 100 USD anually ( and buying a mac ) is a tad much to target iOS. 

as for permissions; I though gdscript was pretty much a sandbox ? ( I'm rather new to godot, so maybe I have this wrong )

my own interest in this is teaching my son game making - and at least round these parts all kinds of school age have a apple branded tablet, but usually not access to a computer. so a 'data.pck launcher' would really make it easier for them so share their work with each other.

**Comment by bojidar-bg** [comment]
@guppy42 Well, no, Godotian apps can use all kinds of permission, and no, GDScript is not sandboxed in any way (yeah, basically, you can distribute a virus through a gdscript that is set to autorun in the editor. really.)

**Comment by punto-** [comment]
Doesnt' this violate the iOS terms? you can't make an app that downloads
and executes code

**Comment by guppy42** [comment]
@punto- I think that refers to binary code, interpreted code/script would be considered "data" and is 'safe' because it can't do anything the interpreter doesn't allow. So the functionality can be vetted on interpreter level.

but then again it's apple so..

**Comment by punto-** [comment]
As far as I know, this is the reason why Apple has rejected 3rd party
browsers for so long, because they download and execute code. It's also
what started the controversy about interpreted code a few years ago, people
misunderstood that it meant you couldn't have scripts in your game, but it
was about downloading it after installing the app.

**Comment by guppy42** [comment]
Well that seems fairly definitive :(
