### ISSUE TITLE
`.obj` files are not exported with the project

### ISSUE THREAD

**Issue by tavurth** [godotengine/godot#77570]
### Godot version

4.0.rc3.official.7e79aead9

### System information

Mac OS.

### Issue description

When attempting to export `.obj` files they are not included in the export package.

```gdscript
extends CenterContainer

var files_to_load: Array = [
	"res://floor.obj2",
	"res://floor.obj",
]

func _ready():
	for file in files_to_load:
		if not len(FileAccess.get_file_as_bytes(file)):
			$Label.set_text("It didn't work!")
```

<img width="926" alt="Screenshot 2023-05-28 at 17 08 26" src="https://github.com/godotengine/godot/assets/100964/2072d486-9a73-42b8-b07c-278cf4991931">

Yet works fine from in the editor.

### Steps to reproduce

Download project below.

Run the project in the editor, you should see this:

<img width="688" alt="Screenshot 2023-05-28 at 17 04 12" src="https://github.com/godotengine/godot/assets/100964/8ed01a80-5f32-40e7-9673-9b92bc59feca">

Export the project (Win or Mac)

Run the exported project, you will see this

<img width="688" alt="Screenshot 2023-05-28 at 17 04 49" src="https://github.com/godotengine/godot/assets/100964/5ec8a87e-0339-44ee-81f3-3263d5941d36">

### Minimal reproduction project

[obj-export-bug.zip](https://github.com/godotengine/godot/files/11584259/obj-export-bug.zip)

**Comment by tavurth** [comment]
Even renaming the file `floor.obj` to `test.test` and it still does not work:

```gdscript
extends CenterContainer

var files_to_load: Array = [
	"res://test.test",
]

func _ready():
	for file in files_to_load:
		if not len(FileAccess.get_file_as_bytes(file)):
			$Label.set_text("It didn't work!")
```

**Comment by tavurth** [comment]
# Production
<img width="688" alt="Screenshot 2023-05-28 at 17 14 41" src="https://github.com/godotengine/godot/assets/100964/60a76d03-a154-4ce0-b526-d26d007cc12a">

# Debug
<img width="688" alt="Screenshot 2023-05-28 at 17 15 05" src="https://github.com/godotengine/godot/assets/100964/cf10c1f7-07f6-4f15-8e76-fcf4ea6ae2f2">

**Comment by tavurth** [comment]
For me current workaround for this is to:

Create copy of all `.obj` files as `.oobj`

Then rename when I'm copying it across during export.

<img width="1044" alt="Screenshot 2023-05-28 at 19 29 25" src="https://github.com/godotengine/godot/assets/100964/eea7d1a8-44b1-4793-afb6-37f300bc38a1">

**Comment by tavurth** [comment]
Does anyone have an idea where to start looking to fix this?

I had a look and could not see any reference to `.obj` directly in the source which could be affecting this 🤔

**Comment by kleonc** [comment]
In the MRP `floor.obj` is being imported as a mesh:
![Godot_v4 0 3-stable_win64_x4MFCCjW0I](https://github.com/godotengine/godot/assets/9283098/14095b34-26e3-42b3-824c-ba04c8c6a6e3)
hence what's stored in the exported `.pck` is such imported mesh, the original `.obj` file is not preserved (you can find such imported file is your project dir too, something like `.godot/imported/floor.obj-e1216168bbe7f702b624c18b212cc69c.mesh`). You can obtain such imported Resource like any other Resource using [`load`](https://docs.godotengine.org/en/4.0/classes/class_%40gdscript.html#class-gdscript-method-load), [`ResourceLoader.load`](https://docs.godotengine.org/en/4.0/classes/class_resourceloader.html#class-resourceloader-method-load), etc., these methods will take care of remapping from the original filepath to the actual imported resource path (so e.g. `load("res://floor.obj")` would work in the exported project as the path would be remapped to the relevant `.mesh` file exported within the `.pck`).

By using `FileAccess` directly there's no remapping happening, hence the original file is found when running from the project dir (as `"res://"` refers to the project dir and the file is in there), and not found when running the exported project (as `"res://"` refers to the exported `.pck` lacking the file).

Changing import setting for the file to keep it as is:
![3f5hyxaJeP](https://github.com/godotengine/godot/assets/9283098/6b2988dd-2c16-4923-a888-d557597ee959)
would make the original file be included in the exported `.pck` (instead of the imported `.mesh` one) and hence it would be found when using `FileAccess` directly for the original path.


I'd say everything seems to be working correctly in here, don't see a bug.

Note that these filters:
![Godot_v4 0 3-stable_win64_k1k9gpxPEF](https://github.com/godotengine/godot/assets/9283098/d6de61c0-d445-4e1d-979b-390041c773e6)
are for **non-resource files**. And because `.obj` files are handled by one of the (default) `ResourceImporter`s such files are considered resource files. Meaning adding `*.obj` filter in there is irrelevant, such files will be handled by the relevant importer anyway (so they won't be even compared against these filters).

**Comment by tavurth** [comment]
@kleonc Hmm I see, thank you that makes good sense 👍 

I was a little surprised when the `.obj` was not exported but the `.mtl` was.

Since there is an `import -> export` process going on, I guess that we have a `FileMapping` from `a -> b` and this is why `load` works where `FileAccess` does not.

Since this issue is probably mostly specific to my game, I will close this issue. Unless you can think of some way we could easily improve it?

**Comment by kleonc** [comment]
> Since this issue is probably mostly specific to my game, I will close this issue. Unless you can think of some way we could easily improve it?

Maybe it could be detected whether the file extensions used within the filters for non-resource files are recognizable by some ResourceImporters and in such case a warning/note could be shown? :thinking: E.g. something like:

*Note: ResourceImporter(s) handling `.obj`(, `.other_extension`, ...) files detected. Such files will be imported according to per file import settings. These filters will not affect them.*

Not sure how easy/feasible doing so would be.
