### ISSUE TITLE
Nodes names on the scene tree removes the number(s) zero(es) "0" if there is another number on its right side (no matter what is on its left side)

### ISSUE THREAD

**Issue by rubenjavier** [godotengine/godot#7758]
Linux Ubuntu 16.04 LTS
Godot 3.0 from master 2017 feb 07

When I create a new node on a scene tree an try to name it "somename01", Godot 3 now rename it like "somename1", this works correctly on Godot 2.x branch

**Steps to reproduce:**
create a new scene, add a node with the "+" button over the scene tree, a Sprite will do, call it "spr_dog01", and the node will be renamed by Godot as "spr_dog1"

This is really inconvenient for a large number of assets where you order them adding zeroes on the name so the asset number eleven isnt within the other first ten
bad practice:
spr_1
spr_11
spr_2
good practice:
spr_01
spr_02
...
spr_10
spr_11

NOTE: this is happening on the tree, but when I create new animations on the AnimationPlayer, I can still call them "idle_01" with the zeroes

Thanks in advance

**Comment by hpvb** [comment]
I've looked at the current behavior and the previous behavior and I find them both a little lacking. I propose the following (taking into account the CamelCase vs snake_case setting in the editor of course)

When adding a new node the following will happen
* Check if there are other nodes with the same basename on the same level already.
 * If so check to see if the last characters of the exiting names end with numbers.
  * If so check the size of the number in absolute characters, and check the highest number.
  * Add the new node using the next highest number, with the same number of characters as before (if possible).
 * If not just add a '1' at the end.

This will lead to the following behavior in practice: 
Adding a new node like Node 0001 will result in subsequent nodes being named Node 0002 instead of Node 2 (as in 2.1.2)
Adding a new node at overflow will basically keep the current behavior so Node 99 + 1 is Node 100. 

All of these things will apply for adding new nodes and duplicating nodes.

@bojidar-bg @akien-mga Thoughts?

**Comment by hubbyist** [comment]
May an additional check needed when adding 100th node to a sequence of node01-node99 to pad all nodes with additional zero to make sequence node001-node100.

**Comment by rubenjavier** [comment]
I wasnt talking about behaviour or an improvement
This post its about an actual bug, if you name a node "spr_dog01", the node will be renamed by Godot as "spr_dog1". The editor its now changing the names of the nodes by itself, and in previous versions it didnt.

**Comment by hpvb** [comment]
@rubenjavier I realize that, but this is the same code. Implementing this will in the process also fix your issue.

**Comment by RandomShaper** [comment]
I implemented this "revision of serial naming behavior", as I called it. I didn't think about zero padding. When I have time for it I'll try to implement @hpvb's suggestion.

Anyway, @rubenjavier, for nodes in the tree currently you would get
```
spr_1
spr_2
spr_11
```

Where are you getting a sorted list from?

**Comment by hpvb** [comment]
@RandomShaper I'll happily implement this behavior myself. I was just looking for consensus on how it's supposed to work. But if you're already familiar with the codepaths feel free :)

**Comment by rubenjavier** [comment]
thanks @RandomShaper, the "bad-practice" sort order example is the one I get on the filesystem folder (linux/windows) if I have to rename my assets without zero padding, I name the real assets (for example pngs or audio files) with zeropadding), and the nodes that use them the same way to keep some order

**Comment by reduz** [comment]
@RandomShaper Just reminding you of implementing the fix
