### ISSUE TITLE
Godot engine is actively fighting against making more secure enviroments without using C++

### ISSUE THREAD

**Issue by RadiantUwU** [godotengine/godot#77611]
### Godot version

4.0.3 [5222a99f5]

### System information

-OS: Android
-Godot Version:4.0.3 [5222a99f5]

### Issue description

Every single time, you are trying to limit functionality to scripts, the engine is actively trying to fight you on it, it really does **not** want to cooperate, it always just fails. c

My goal objective was to limit FileAccess and OS singletons, that way i can enable object serialization and also allow mods to be loaded in safely. Unlike other scripting languages (for example Lua) where it's as straight forward as literally wiping it from the global enviroment, you cannot do this in GDScript.

`register_singleton()` **will not** propagate singleton changes to GDScript, which means you cannot do anything.

`(FileAccess as Object).set_script(load("res://test.gd"))` will also not work, since FileAccess's real base (`GDScriptNativeClass`) is **unreachable** and **hidden**, making anything fail.

Setting script would be quite nice, as you can limit the programmers from running `set_script(null)` by overriding the function, and then you can override `open()` to make a whitelist of what files can be accessed and when.

All i want to do is add security, and it always fails. Private variables were never implemented. The least thing you can do is to create a function to get the stack trace to a string instead of just making it print. That would allow developers to atleast check what function is calling and from where, and would allow them to implement it.

### Steps to reproduce

Attempt to access `GDScriptNative` from the global scope will result in an error.

### Minimal reproduction project

[project.zip](https://github.com/godotengine/godot/files/11592306/project.zip)
(created with tar -cf)

**Comment by AThousandShips** [comment]
`FileAccess` isn't derived from `GDNativeClass`, you're using the name of the class, which is handled by this, `FileAccess` is `RefCounted`

**Comment by dalexeev** [comment]
GDScript is currently not suitable for implementing secure mods. Artificial restrictions like the one you suggested or #61831 does NOT provide security, these restrictions are very easy to bypass (if you know Godot). Source code validation can be tricky to bypass, but it's a fairly complex and unreliable approach.

A possible solution could be to implement your own simple language or command interpreter, if you don't need complex features and high performance. But you must understand exactly what you are doing in order to prevent security breaches.

There is also a third-party [Godot LuaAPI](https://github.com/WeaselGames/godot_luaAPI) module. It's in early development and I haven't tried it, so don't take it as a recommendation, just let you know if you're interested.

See also godotengine/godot-proposals#5010.

**Comment by RadiantUwU** [comment]
> GDScript is currently not suitable for implementing secure mods. Artificial restrictions like the one you suggested or #61831 does NOT provide security, these restrictions are very easy to bypass (if you know Godot). Source code validation can be tricky to bypass, but it's a fairly complex and unreliable approach.
> 
> A possible solution could be to implement your own simple language or command interpreter, if you don't need complex features and high performance. But you must understand exactly what you are doing in order to prevent security breaches.
> 
> There is also a third-party [Godot LuaAPI](https://github.com/WeaselGames/godot_luaAPI) module. It's in early development and I haven't tried it, so don't take it as a recommendation, just let you know if you're interested.
> 
> See also [godotengine/godot-proposals#5010](https://github.com/godotengine/godot-proposals/issues/5010).

This is exactly what i was looking for, thank you.
