### ISSUE TITLE
Script name tooltips are oversized

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#77787]
### Godot version

4.1 db5113d

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/2223172/ee391a0d-44b7-4a35-bfa5-40d47af75f65)
Notice the empty space to the right. I actually have a worse case in my project, but I couldn't reproduce it outside:
![](https://chat.godotengine.org/file-upload/X3RMM5A9gN7RZEizo/Clipboard%20-%202%20czerwca%202023%2022:54)
Regression from #77651
CC @Rindbee 

### Steps to reproduce

1. Add a new script
2. Name it `;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;.gd`
3. Hover its name in the Script Editor

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
The first call to `_update_minimum_size()` usually happens when the control is first visible in the tree. This might be a bit late for `Label`. The (minimum) size cache needs to be recalculated after the text is modified and the theme is changed.


https://github.com/godotengine/godot/blob/17bfccc5943c130e4c40ad00983655bb9422f124/scene/main/viewport.cpp#L1489

https://github.com/godotengine/godot/blob/17bfccc5943c130e4c40ad00983655bb9422f124/scene/main/viewport.cpp#L1523
