### ISSUE TITLE
Improve MultiplayerSynchronizer editor UX to prevent setting both Sync and Watch

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#77896]
### Godot version

4.1.dev4

### System information

Windows 10 Godot 4.1.dev4

### Issue description

The watched property in the Multiplayer Synchronizer node is supposed to pass the variable through the network only when it changes, but as I use the network profiler, it is evidently not working as intended

### Steps to reproduce

Open 2 debug instances on the project I will give, use the network profiler and you will see the variable does not change, although it goes up to 780b/s on the network

### Minimal reproduction project

[minimalproject.zip](https://github.com/godotengine/godot/files/11659414/minimalproject.zip)

**Comment by Calinou** [comment]
cc @Faless

**Comment by AThousandShips** [comment]
In the future make sure to follow the instructions and exclude the `.godot` folder, it helps with size and security

**Comment by Faless** [comment]
This seems to be a usability issue, opening the project, I found the following config:

![also_sync](https://github.com/godotengine/godot/assets/1687918/ca4cb9f1-ca16-472b-8073-5329a3650dcb)

I.e. the variable is configured for both `sync` and `watch`.

To skip the constant synchronization `sync` should be disabled:

![only_watch](https://github.com/godotengine/godot/assets/1687918/9d5a1ccf-6ad0-4370-b54b-93bc2ca3c2b4)

I think we should improve the editor UX so that setting a variable to both `sync` and `watch` is not possible (or shows a warning).

**Comment by agrimminck** [comment]
Oh my! I am such a fool, sorry for the bad post, and thanks for your answers!

**Comment by agrimminck** [comment]
> In the future make sure to follow the instructions and exclude the `.godot` folder, it helps with size and security, also your script files are broken due to indentation errors, causing it not to run correctly, and you have autoloads that aren't included, it's important to clean up your MRP

It is not broken due to identation errors, I use spaces instead of tabs

Sorry for not erasing the .godot file and not cleaning the autoloads 🤒😬

**Comment by akien-mga** [comment]
Reopening this issue to handle the identified UX improvement that we should do.
