### ISSUE TITLE
sky.gdshader does not accept vec4 array from gdscript

### ISSUE THREAD

**Issue by direfish** [godotengine/godot#77970]
### Godot version

4.0.3

### System information

Windows10

### Issue description

sky shader accepts uniform vec3, vec4, vec3 array, but not vec4 array

### Steps to reproduce

simply pass Vector4 to uniform vec4[] from gdscript

### Minimal reproduction project

gdscript

sky_material.set_shader_parameter("v3",Vector3(1,0.8,0.5)) - v
sky_material.set_shader_parameter("v4",Vector4(1,0.8,0.5,0.2)) - v
sky_material.set_shader_parameter("v3a",[Vector3(1,0.8,0.5)]) - v
sky_material.set_shader_parameter("v4a",[Vector4(1,0.8,0.5,0.2)]) - x

sky gdshader

uniform vec3 v3;
uniform vec4 v4;
uniform vec3 v3a[1];
uniform vec4 v4a[1];

void sky(){
    COLOR.r = v4a[0].w
}

**Comment by bitsawer** [comment]
Yes, this will be fixed by https://github.com/godotengine/godot/pull/74937. Probably the closest duplicate would be https://github.com/godotengine/godot/issues/64051, similar reason and workaround, just different types.

Currently the only working way for setting vec4 array is to use flattened PackedFloat32Array with set_shader_parameter(), so each vec4 you want to set would be 4 floats in the packed array.
