### ISSUE TITLE
Deleting OBJ file in FileSystem dock doesn't remove the corresponding MTL file

### ISSUE THREAD

**Issue by sanyi12** [godotengine/godot#77999]
### Godot version

4.0.3

### System information

Windows 10, RTX3070

### Issue description

When you delete an obj file in the editor, the file gets deleted but not the mtl. This results in many unnecessary files - unused data blocks. 

### Steps to reproduce

import any .obj file and delete it inside Godot. 

### Minimal reproduction project

not needed

**Comment by akien-mga** [comment]
Currently Godot has no way to track that a given MTL file is related only to a given OBJ, and no logic in place to delete the MTL if the OBJ is deleted.

This could possibly be added, but there are some issues to consider:
- As far as I know, a MTL file can be used by multiple OBJ files. So it would need some form of dependency tracking so it doesn't remove MTL files shared between multiple OBJ files, unless all those OBJ files are being deleted.
- There's just no system in place to delete multiple files when the user asked to delete a single one. Since the MTL files don't show in the FileSystem dock, this can be unexpected and confusing.

**Comment by sanyi12** [comment]
if you can make the mtl visible then you can consider closing this issue. Thank you for your kind explanations everyone.

**Comment by Calinou** [comment]
> if you can make the mtl visible then you can consider closing this issue. Thank you for your kind explanations everyone.

If you add `,mtl` at the end of **Docks > FileSystem > Textfile Extensions** in the Editor Settings, MTL files should appear in the FileSystem dock in 4.0 and later:

![image](https://github.com/godotengine/godot/assets/180032/b7a8c4c9-5ce2-4b4d-832a-745e75626ee3)
