### ISSUE TITLE
Vector based SDF

### ISSUE THREAD

**Issue by codeape** [godotengine/godot#7806]
First of all, I do not want to remove the current font system (I will get to that later). However, with all new fancy stuff like Virtual Reality headsets and 4K monitors etc. I was thinking that one problem encountered is the display quality of text. Then I remembered a project that I found 2 years ago, GLyphy: https://github.com/behdad/glyphy

See this video if you want to know more about how GLyphy works:
http://vimeo.com/behdad/glyphy

Most other projects sample the SDF into a texture. This has all the usual problems that sampling has. Ie. it distorts the outline and is low quality. GLyphy instead represents the SDF using actual vectors submitted to the GPU. This results in very high quality rendering, though at a much higher runtime cost.

I do not see why godot should remove the bitmap based font system (it has less runtime costs and works well) but a vector based SDF (GLyphy) could complement this for projects that need better display quality of text.

**Comment by Zylann** [comment]
Do you mean mesh-based glyphs instead of bitmap-based?

**Comment by codeape** [comment]
- Well, a mesh is a collection of vertices, so yes.
- Glyphy support TTF fonts
- SDF is not a font format. SDF stand for Signed Distance Field and is a mathematical function used for determine the distance of a given point x from the boundary.

Glad someone liked the ide :)

**Comment by akien-mga** [comment]
You mean like https://github.com/godotengine/godot-demo-projects/tree/2.1/2d/sdf_font ? :)

**Comment by codeape** [comment]
@akien-mga Ok that is SDF, however godot uses bitmaps and not vectors/meshes sent to the GPU (as I understand it). The vector part was the point of this.

**Comment by buckle2000** [comment]
Hi everyone! Is there a way to get vertices of a font glyph?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
