### ISSUE TITLE
Missing Obstacle Avoidance Method

### ISSUE THREAD

**Issue by ATryder** [godotengine/godot#78062]
### Godot version

4.1 Beta-1

### System information

Manjaro

### Issue description

In order to use dynamic obstacles in NavigationServer the documentation states one must assign a radius, as opposed to vertecies, with a call to `NavigationServer3D.obstacle_set_radius(obstacle_rid, radius)`, but that method does not exist.

### Steps to reproduce

Open a new script and type `NavigationServer3D.obstacle_set_radius()`

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Can you please link to the documentation where it says this? There's several navigation documentation pages and information

**Comment by AThousandShips** [comment]
This method doesn't exist (any more) so the documentation is probably out of date, unsure

**Comment by smix8** [comment]
For now you can use `NavigationServer3D.agent_set_radius($NavigationObstacle3D.get_agent_rid(), radius)`.

The radius using part of the NavigationObstacle is actually a NavigationAgent RID. What happened was that during development the fake_agent that uses the radius was removed from the obstacle. Later, due to popular demand the fake_agent was re-added to the obstacle without re-adding the obstacle_set_radius() function. So it is actually the function that is now missing while the documentation is "correct". Will prepare a patch to re-add with the next 4.1 beta.
