### ISSUE TITLE
Crash opening visual shader editor for specific shader

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#78080]
### Godot version

4.1.beta1

### System information

macOS 13.3.1 mobile renderer

### Issue description

Trying to open and edit one of my visual shaders now consistently crashes Godot 4.1beta1. 

The shader was made and edited fine in earlier versions of Godot 4 and I'm not certain what is special with this shader (attached below for investigation). Opening and editing other visual shaders works fine for me. The only thing I can think of that this shader uses that other do not is the gradient node, though as I can't open it I'm not sure what else might be going on in it.

### Steps to reproduce

Open the attached visual shader (in any project)

### Minimal reproduction project

[ConnectBlendShader.tres.zip](https://www.lostminds.com/godot/ConnectBlendShader.tres.zip)

**Comment by bitsawer** [comment]
Can confirm. In the future though, try to give a complete, minimal project instead of a single .tres files, it makes it easier and faster to test and see what is wrong.

I debugged it and it blows up on this line:

https://github.com/godotengine/godot/blob/37d1dfef9d81aade27ab0c56fc6b6f12f6a08045/editor/plugins/curve_editor_plugin.cpp#L982

because curve is NULL. Patching it to add NULL check like this:

```cpp
Ref<Curve> curve = curve_editor_rect->get_curve();
if (curve.is_valid()) {
    // Set snapping settings based on the curve's meta.
    snap_button->set_pressed(curve->get_meta("_snap_enabled", false));
    snap_count_edit->set_value(curve->get_meta("_snap_count", DEFAULT_SNAP));
}
```

makes it not-crash again, but not sure if there is something deeper here. @MewPurPur did some great work with curve editor refactoring https://github.com/godotengine/godot/pull/74959, they might have a better understanding about this. Possible regression?

**Comment by lostminds** [comment]
Thanks @bitsawer , will add a full project next time. I tested making a new blank project and adding just this file and as it crashed when trying to open it there as well I figured it was enough to reproduce with just the shader file.
