### ISSUE TITLE
Dictionary weirdly empty while using GDScript's new static variables

### ISSUE THREAD

**Issue by hydroper** [godotengine/godot#78121]
### Godot version

4.1beta1

### System information

Windows 11, gl_compatibility

### Issue description

I'm creating an enum class using static variables. I'm taking this approach for a few reasons and I know there are other ways of achieving the same, but anyway Godot is acting weird. Here's a simple example reproducing the bug (using Godot 4.1's `static var`):

```gdscript
func _ready():
    var e = SomeE.X
    print(SomeE.from(e.value_of())) # null, HOW?
```

Here's `SomeE` definition:

```gdscript
class_name SomeE

static var X: SomeE = SomeE.new(0)
static var Y: SomeE = SomeE.new(1)

static var _from: Dictionary = {}
var _value: int

func _init(value: int):
    _from[value] = self
    self._value = value
    print(_from.get(value)) # not null

static func from(value: int) -> SomeE:
    return _from.get(value)

func value_of() -> int:
    return self._value
```

It prints:

```
<RefCounted#-9223372011303074616>
<RefCounted#-9223372011286297399>
<null>
```

The last `print()` from `_ready` is yielding null, but should not.

### Steps to reproduce

1. Create a 2D scene and attach the above code to the script.
2. Create a `some_e.gd` script with the above `SomeE` definition.
3. Debug the project

### Minimal reproduction project

N/A

**Comment by hydroper** [comment]
It looks like the `Dictionary` is initialized twice by the engine, but putting this at the top of `_init` worked:

```gdscript
_from = _from if _from != null else {}
```

**Comment by ajreckof** [comment]
This feels like it was closed a bit too quick as there is something fishy here.
So I tried to debug what is happening and the actual problem is that var are initialised on their order of appeareance ie this is not linked to static members. Which means X and Y are initialised fine and then `_from` is initialised and remake the dictionnary empty. Therefore the solution here is to initialise first the dictionnary and then X and Y.

Here is a smaller file not using static members and using only file that show the same behaviour : 
```gdscript
extends Node

var X = new_value(0)
var Y = new_value(1)

var _from: Dictionary = {} 

func new_value(value: int):
	var new_node = Node.new()
	_from[value] = new_node
	return new_node

func _ready() -> void:
	print(_from)
```

I don't think we have documented this anywhere even though this seems logic it would be great to have a note in the [GDScript reference page](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html) and / or have a warning whenever we access a variable not yet initialised stating that you should avoid modifying this value as it any modification might be erased by initialisation.

**Comment by dalexeev** [comment]
> It looks like the `Dictionary` is initialized twice by the engine, but it worked by:
> 
>     * Removing `= {}` from `_from`'s field definition
> 
>     * Putting this at the top of `_init`:

Yes, it is true. First, variables with static types are initialized, then assignments are made (from top to bottom, skipping `@onready` variables), then `_init()` is called.

https://github.com/godotengine/godot/blob/a3c49ad2f0120f41789836a523698db0d4a9f0f2/modules/gdscript/gdscript_compiler.cpp#L2051-L2053

The following options work correctly:

```gdscript
var _from: Dictionary = {} # Direct order.
var X = new_value(0)
var Y = new_value(1)
```

```gdscript
var X = new_value(0)
var Y = new_value(1)
var _from: Dictionary # No assignment.
```

I'm not sure if there is an easy way to fix this. It may be possible to initialize variables with function calls last, but unexpected behavior is still possible.

**Comment by dalexeev** [comment]
> I don't think we have documented this anywhere even though this seems logic it would be great to have a note in the [GDScript reference page](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html)

See godotengine/godot-docs#7507.
