### ISSUE TITLE
_set method for a String property triggered too much times, when in Resource property's embedded inspector, and text changes fast

### ISSUE THREAD

**Issue by coderbloke** [godotengine/godot#78185]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 11

### Issue description

See screen recording below.
~~I type in a String property which is within a PROPERTY_USAGE_ARRAY / EditorInspectorArray.~~
I type in a String property which is within a Resource property's (DataflowGraph.Function: DataflowFunction) embedded inspector
When I type slowly in a String property. 1 char change -> 1 trigger of _set method
When I type faster, 1 char change -> Triggers _set method for all char changes since the last typing
When I again type slow, 1 char change -y 1 trigger again
~~End of recording: Not observed for String property, which is not in array property.~~
End of recording: Not observed for String property, which is the property of the outer Resource (DataflowGraph)

![Godot_v4 0 3-stable_win64_IUxJEFQh2q](https://github.com/godotengine/godot/assets/75695649/ba5e735c-4e66-4b6a-ad85-7165ef5c5161)

### Steps to reproduce

Get project from attached ZIP.
Open res://addons/dataflow_engine/test_dataflow_graph.tres in Inspector
Do what you read/see in issue description.

### Minimal reproduction project

[Project.zip](https://github.com/godotengine/godot/files/11735719/Project.zip)

**Comment by AThousandShips** [comment]
Please clarify what you are expecting, and what this expectation is based on

**Comment by coderbloke** [comment]
Expectation is, that one change in text, should trigger one call of _set method,<br>
and not repeat setting all values since I last typed slowly.
It's based on my sense and the behavior when you type slow. :)

**Comment by AThousandShips** [comment]
> Not observed for String property, which is not in array property.

I can't replicate that it *doesn't* happen on the `Title` property

I'm not familiar enough with the setup of some of these properties, could be a configuration error on property navigation there, someone else more familiar with that willl have to weigh in

**Comment by CncealDVRflectN** [comment]
Hi! I was able to reproduce this behaviour on my machine running Windows 11. I've used Visual Studio 17.6.2 to build the engine from 2 commits: https://github.com/godotengine/godot/commit/eb86dabee07e8dfce3b06cbd557b50b74afd3d6c and https://github.com/godotengine/godot/commit/9b4d367621a087635c9b3585ba1a8018859161f4.

On the older commit (https://github.com/godotengine/godot/commit/eb86dabee07e8dfce3b06cbd557b50b74afd3d6c) I had some pretty strange and non-deterministic behaviour. The bug stopped reproducing after I enabled verbose logging and added a log inside the for loop in the `UndoRedo::create_action` method:
```c++
...
for (List<Operation>::Element *E : to_remove) {
	if (E->get().name == "node_0/visuals/title")
		print_verbose("delete from creation");

	// Delete all object references
	E->get().delete_reference();
	E->erase();
}
...
```

After I updated to the newer commit (https://github.com/godotengine/godot/commit/9b4d367621a087635c9b3585ba1a8018859161f4) this behaviour changed and the bug could be reproduced with any debug logs I wrote (so it became more stable in reproduction).

Back to the bug itself. It seems that in my case, some of the "do" operations in `UndoRedo` have the `force_keep_in_merge_ends` flag set to `true` and some to `false` when they are created in `add_do_...` methods. I checked the usage of this flag and as far as I understand it used mainly for "undo" operations (there are no any explicit assignments outside `add_undo_...` methods). So I assumed that the desired default value for this flag is 'false'. So I added an explicit initializer for it:
```c++
...
struct Operation {
	enum Type {
		TYPE_METHOD,
		TYPE_PROPERTY,
		TYPE_REFERENCE
	} type;

	bool force_keep_in_merge_ends = false;
	Ref<RefCounted> ref;
	ObjectID object;
	StringName name;
	Callable callable;
	Variant value;

	void delete_reference();
};
...
```

It seems to have fixed the bug. But I have little experience with C++, with the engine itself (it's the first time I debugging those sources) and in general I have not worked with Godot much, so I can be wrong and this fix can break something else. Should I create a PR?

**Comment by CncealDVRflectN** [comment]
I finally have time to finalize my research of this issue. And I found another behaviour that I think also hints at undefined behaviour. I wasn't able to reproduce this problem when building the engine without `vsproj` and `dev_build` flags. But with them enabled, the issue still exists in the latest (at the time of writing) commit (https://github.com/godotengine/godot/commit/c83f912bcb33d441b90afe36bad38880acbe5f15).

After a quick search for default member initialization in C++ I think that is what happens. `Operation` is created uninitialized in the `add_do_property` method. Then some of its members are initialized, but not the `force_keep_in_merge_ends` flag, so it stays uninitialized. And since it is not initialized, in some environments you might be "lucky" and it'll get some non-zero memory part so it'll be interpreted as `true`.

If this is the case, then to fix the issue we need to add an explicit initialization of the `force_keep_in_merge_ends` flag either in the definition of  the `Operation` structure or wherever it's created. I'll add it to the definition and create a PR in a few minutes.
