### ISSUE TITLE
Game stops taking input and player cannot move, and no mouse capturing.

### ISSUE THREAD

**Issue by LionLight95-SYSERROR** [godotengine/godot#78320]
### Godot version

Godot v4.0.3 Stable

### System information

Windows 10 - Godot v4.0.3.stable - Vulkan (Forward+)

### Issue description

When I run my game, using F5 or F6 (I presume compiling the game won't work, either), It doesn't capture my mouse or inputs, everything in my script is set up correctly, but for some reason out of nowhere it just stops accepting input. It happens on other projects too.

### Steps to reproduce

I just wrote some code and it stopped, then when I removed the code. It still didn't work.

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
This is unfortunately not enough information to do much investigation on, if you can work out more information please do but otherwise we're unlikely to be able to help you

**Comment by DreamHollow** [comment]
Sorry, this isn't very helpful without more information about what you were doing at the time of the bug.

If you had a copy of the original code, or if you could provide information on your Godot settings, that might be useful.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no [minimal reproduction project](https://github.com/godotengine/godot/blob/master/CONTRIBUTING.md#provide-a-simple-example-project) was included in the original bug report, please upload one as well to ease troubleshooting.
