### ISSUE TITLE
Skeleton: Doesn't re-draw in the editor until node is selected.

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#7837]
**Operating system or device - Godot version:**
Linux - godot master

**Steps to reproduce:**
- Move the parent of a skeleton
- Notice the editor helpers for the skeleton don't apply the new translation until the skeleton has been selected in the SceneTree dock.

![skel](https://cloud.githubusercontent.com/assets/8281916/23096532/1365e6fc-f61f-11e6-9b8d-a8dfd08a41e2.gif)

**Comment by reduz** [comment]
I think this issue may have duplicates, as it applies to all gizmos. If anyone wants to check feel welcome

**Comment by ApachOC** [comment]
Checked, and yes this issue applies to multiple gizmos.
The issue appears to be caused by node not receiving transform notifications, and as a result not updating its gizmo.

Affected nodes are:
*  Skeleton
*  CollisionShape
*  CollisionPolygon
*  RayCast
*  VehicleWheel
*  Position3D
*  AudioStreamPlayer3D
*  Path

This issue also seems to be a duplicate of #8910.
