### ISSUE TITLE
Some 2D nodes aren't visible: canvas_item_add_triangle_array() doesn't work

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7840]
Tested on Godot 3.0 master 5e3fc7d06956dcda8b50cd4f028c83cf967f7223
Windows 10 64 bits

All nodes using `VisualServer::canvas_item_add_triangle_array` can't be seen.
I thought backface culling was on, so I tried inverting index order in Line2D, but no luck.

![image](https://cloud.githubusercontent.com/assets/1311555/23097887/6dec0860-f640-11e6-9f9d-2276c9b511e0.png)

**Comment by bojidar-bg** [comment]
Can confirm with some Shape2D nodes.

**Comment by JosephCatrambone** [comment]
Adding another confirmation to the choir.  Has this been narrowed down to canvas_item_add_triangle_array or does it perhaps pass some unexpected arguments to canvas_item_add_polygon?

**Comment by jmoon1506** [comment]
Seems like the default vertex array object (the name zero) became deprecated in GLES 3.3. The _draw_polygon function binds data using VertexAttribPointer, which now fails because the default VAO is no longer there. Binding a non-default VAO also seems to fails because VertexAttribPointer then cannot specify client-side data.

```
void RasterizerCanvasGLES3::_draw_polygon(int p_vertex_count, const int *p_indices, const Vector2 *p_vertices, const Vector2 *p_uvs, const Color *p_colors, const RID &p_texture, bool p_singlecolor) {
	...
	***glBindVertexArray(data.canvas_quad_array)*** // attempt to bind non-default VAO
	glEnableVertexAttribArray(VS::ARRAY_VERTEX);
	glVertexAttribPointer(VS::ARRAY_VERTEX, 2, GL_FLOAT, false, sizeof(Vector2), p_vertices);
	if (do_colors) {

		glEnableVertexAttribArray(VS::ARRAY_COLOR);
		glVertexAttribPointer(VS::ARRAY_COLOR, 4, GL_FLOAT, false, sizeof(Color), p_colors);
	} else {
		glDisableVertexAttribArray(VS::ARRAY_COLOR);
	}

	if (texture && p_uvs) {

		glEnableVertexAttribArray(VS::ARRAY_TEX_UV);
		glVertexAttribPointer(VS::ARRAY_TEX_UV, 2, GL_FLOAT, false, sizeof(Vector2), p_uvs);
	} else {
		glDisableVertexAttribArray(VS::ARRAY_TEX_UV);
	}

	if (p_indices) {
		glDrawElements(GL_TRIANGLES, p_vertex_count, GL_UNSIGNED_INT, p_indices);
	} else {
		glDrawArrays(GL_TRIANGLES, 0, p_vertex_count);
	}
	...
```

ERROR: _gl_debug_print: GL ERROR: Source: OpenGL        Type: Error     ID: 2100        Severity: High  Message: glVertexAttribPointer failed because it is not allowed to specify a client-side vertex or element array when a non-default vertex array object is bound (GL_INVALID_OPERATION)
   At: drivers\gles3\rasterizer_gles3.cpp:123

Any ideas? I'm not at all an expert on OpenGL, so I'm hoping someone can point out flaws with this.

https://www.opengl.org/discussion_boards/showthread.php/170467-VAO-is-evil

**Comment by reduz** [comment]
polygons are now drawn, so closing this
