### ISSUE TITLE
Create dialog does not show global classes from addons inside subfolders

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [godotengine/godot#78400]
### Godot version

4.1.beta1.mono

### System information

Godot v4.1.beta1.mono - macOS 13.3.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

The new `GlobalClass` attribute for registering global types in C# (#72619) does not seem to work in nested addons, i.e. addons that are placed within a subfolder of the `addons` directory (`res://addons/**/<addon>`).
Placing addons inside of subfolders is supported accroding to #43734

Edit: as confirmed by @raulsntos the same problem is present for GDScript.

#### Detailed showcase of the problem

Given the following project:
![image](https://github.com/godotengine/godot/assets/11772241/44741d42-d9c4-49bf-8a85-7cb4e0629a87)

Where the `CustomProjectNode.cs`, `CustomAddonNode.cs`, and `CustomSubfolderAddonNode.cs` are implemented like this: 
```c#
using Godot;

namespace Addon;

[GlobalClass]
public partial class CustomAddonNode : Node
{
    // Called when the node enters the scene tree for the first time.
    public override void _Ready()
    {
    }

    // Called every frame. 'delta' is the elapsed time since the previous frame.
    public override void _Process(double delta)
    {
    }
}
```

And both addons are enabled in the project settings, the `CustomSubfolderAddonNode` does not show up when adding a new node:
![image](https://github.com/godotengine/godot/assets/11772241/d7a9b5d2-0f2b-4b36-8943-3c757e0fd0b0)

### Steps to reproduce

1. Create a new project
2. Create a new C# addon
3. Create a node with the `GlobalClass` attribute
4. Move the folder containing the addon to a subfolder inside of `addons`
5. Compile the C# project
6. Enable the addon inside the project settings
7. Try to add the custom node to a scene. The node does not show up in the search

### Minimal reproduction project

[GlobalClassTest.zip](https://github.com/godotengine/godot/files/11781466/GlobalClassTest.zip)

**Comment by raulsntos** [comment]
In the MRP you have uploaded, you can see in `.godot/global_script_class_cache.cfg` that the 3 classes are recognized and have been added to the list of global classes.

This feels like the issue is in the Editor code that determines which classes should be added to the dialog. To confirm I have ported the MRP to GDScript and I am able to reproduce this so it doesn't seem exclusive to C#. This is why we usually ask users to provide a GDScript MRP even for C# issues, it allow us to confirm if it's a C# issue or if the issue may be somewhere else.

The issue is likely in this condition in the create_dialog:

https://github.com/godotengine/godot/blob/a83eb16fba5bb3da086b41cbd79e6f95b09eb8ee/editor/create_dialog.cpp#L158

**GDScript MRP**:  [GlobalClassTestGDScript.zip](https://github.com/godotengine/godot/files/11782193/GlobalClassTestGDScript.zip)

**Comment by FreshlyBrewedCode** [comment]
Thank you for pointing that out. I did not think of porting to GDScript.
Also, I just checked and it is the same problem occurs when creating instances of custom resources. I assume that would also be covered by the line you mentioned above since it is using the same dialog?

btw should we rename the issue?

**Comment by raulsntos** [comment]
> Also, I just checked and the same problem occurs when creating instances of custom resources. I assume that would also be covered by the line you mentioned above since it is using the same dialog?

Yes, it's likely the same cause.

> btw should we rename the issue?

Oh yeah, feel free to rename it to something more appropiate now that we know it's also happening with GDScript's `class_name`.
