### ISSUE TITLE
Properties with Node references are not initialized correctly in editor

### ISSUE THREAD

**Issue by TinkerWorX** [godotengine/godot#78421]
### Godot version

v4.0.3.stable.mono.official [5222a99f5]

### System information

Windows 11 - Compatibility

### Issue description

When inside the _Ready override, exported properties with references to nodes are initialized differently in the editor compared to the game, meaning you can't have initialization logic that depend on those properties show correctly in the editor.

### Steps to reproduce

Launch the attached project. Open the "world.tscn" object and look at the log, the log will say
```
this.Node.Name: null
```
Run the project, and look at the log while the game is running
```
this.Node.Name: Child
```

### Minimal reproduction project

[_ReadyBug.zip](https://github.com/godotengine/godot/files/11782764/_ReadyBug.zip)

**Comment by theraot** [comment]
This one more duplicate of https://github.com/godotengine/godot/issues/74050 (https://github.com/godotengine/godot/issues/74141, https://github.com/godotengine/godot/issues/77685)

The fix is part of Godot 4.1 (in beta 2 at the time of writing).

Apparently won't be cherry-picked for Godot 4.0: https://github.com/godotengine/godot/pull/76389#issuecomment-1594876002

**Comment by TinkerWorX** [comment]
Much appreciated @theraot, I tried searching, but it was hard to find the right terms. I will close this.
