### ISSUE TITLE
camera parameter of VisibilityNotifier3D enter_camera and exit_camera signal is boolean not Object

### ISSUE THREAD

**Issue by earlroxas13** [godotengine/godot#7843]
**Operating system or device - Godot version:**
Godot version: 2.1 (from official website download)
OS: Windows 8.1

**Issue description:**

So, in my project i use VisibilityNotifier (3D) Node, and when i use the signal enter camera and exit camera the camera parameter of the signal is boolean, but according to [this](http://docs.godotengine.org/en/stable/classes/class_visibilitynotifier.html) it should be an Object not boolean. This is the sreenshot:

**Steps to reproduce:**
![67paiac](https://cloud.githubusercontent.com/assets/8316851/23098783/b6a8e142-f689-11e6-8fe0-9c27c22bf77b.jpg)
![211feys](https://cloud.githubusercontent.com/assets/8316851/23098789/ccbc186e-f689-11e6-9d8c-634244d6c8e5.jpg)
![tuy84jn](https://cloud.githubusercontent.com/assets/8316851/23098791/daa84902-f689-11e6-88dc-014d6cb20ca6.jpg)

**Comment by bojidar-bg** [comment]
Here is the code responsible for emitting the signal: [`scene/3d/visibility_notifier.cpp:44`](https://github.com/godotengine/godot/blob/5dbf1809c6e3e905b94b8764e99491e608122261/scene/3d/visibility_notifier.cpp#L44)
```c++
void VisibilityNotifier::_enter_camera(Camera *p_camera) {

	ERR_FAIL_COND(cameras.has(p_camera));
	cameras.insert(p_camera);
	if (cameras.size() == 1) {
		emit_signal(SceneStringNames::get_singleton()->screen_entered);
		_screen_enter();
	}
	emit_signal(SceneStringNames::get_singleton()->camera_entered, p_camera);
//	^^^^^^^^^^^ here
}
```
(In 2.x, the line is the same, except that it is `camera_enter` instead of `camera_entered`)
In this case `p_camera` should be of type `Camera*`, so it is pretty weird that it gets cast to `TYPE_BOOL` Variant...

**Comment by bojidar-bg** [comment]
Also, could confirm.

**Comment by RodZill4** [comment]
It seems casting the camera to (const Object*) in the emit_signal call (to match the correct Variant constructor) fixes the problem.
