### ISSUE TITLE
Light cast on wrong side of imported mesh

### ISSUE THREAD

**Issue by wjagodfrey** [godotengine/godot#78502]
### Godot version

4.0.3

### System information

MacOS 12.3, Intel i9, AMD Radeon Pro 5500M

### Issue description

I'm importing a simple mesh exported to `.glb` from Blender. All transforms are applied and normals double checked. Light is being projected on the wrong sides. When I rotate the cube, the side that the light is projected on changes. It almost behaves like it's 4D :P

This appears in-game and in inspector:

<img width="862" alt="image" src="https://github.com/godotengine/godot/assets/5732688/8bd7007a-2bb9-4cfb-aac7-31604062f2d1">
<img width="793" alt="image" src="https://github.com/godotengine/godot/assets/5732688/82d0b3f6-c8bb-4bf9-bdf5-6692d697c0de">

I've attached a reproduction repo below. It contains the original `.blend` file, and a test scene.

### Steps to reproduce

* Checkout the repo linked below
* Open `main.tscn`
* Rotate the crate
* Observe the way light falls on the wrong side of the crate, while the standard `BoxMesh` is totally fine.

If you can't replicate let me know and I'll provide a test scene.

### Minimal reproduction project

Repro repo can be found [here](https://github.com/wjagodfrey/godot-4-lighting-direction-issue).

### Edit:
Note that I've disabled shadows on both boxes to show the issue more clearly.

**Comment by clayjohn** [comment]
How did you originally import the crate file into your scene? When I drag and drop the .glb or the .blend file they work correctly, but I can confirm that the existing crate has it normals messed up

![Screenshot from 2023-06-22 19-23-30](https://github.com/godotengine/godot/assets/16521339/00101c84-5373-490f-9150-bdd0411c6b05)

Looking at the ``crate.tscn`` file I can see that you have saved the crate's mesh data into the tscn file, so it appears that it has been manipulated beyond simply importing the .glb. 

It would be helpful for you to write up what steps you took to get to this state so that we can identify where the mesh got broken

**Comment by Zireael07** [comment]
>  I can see that you have saved the crate's mesh data into the tscn file

This is usually unintended (we already have an issue about this bloating the tscn) and b) usually the result of clicking Local to scene on a mesh iirc

**Comment by wjagodfrey** [comment]
That must have been the case. I rebuilt the whole node with `New Inherited Scene` and it works perfectly. Thank you!
