### ISSUE TITLE
"Could not resolve SDK" error when upgrading existing project from 4.0.2 to 4.1.0-beta3

### ISSUE THREAD

**Issue by FilipLundby** [godotengine/godot#78527]
### Godot version

4.1.0-beta3

### System information

Windows 10

### Issue description

This error occurs after upgrading to 4.1.0 beta3 and then starting the game.

    
    Running:  "C:\Program Files\dotnet\dotnet.EXE" build C:/development/Source.csproj -c Debug -v normal "-l:GodotTools.BuildLogger.GodotBuildLogger,C:/Program Files (x86)/Godot/Godot_v4.1-beta3_mono_win64/GodotSharp/Tools\GodotTools.BuildLogger.dll;C:/Users/Me/AppData/Roaming/Godot/mono/build_logs\07ed28eee9dffd3d07de56609dd59619_Debug" -p:GodotTargetPlatform=windows
    MSBuild version 17.5.0+6f08c67f3 for .NET
    Build started 21/06/2023 18.31.22.
    X.509 certificate chain validation will use the default trust store selected by .NET.
    X.509 certificate chain validation will use the default trust store selected by .NET.
    Restoring packages for C:\Users\Me\AppData\Local\Temp\NuGetScratch\503e249c92ed455193b3aae55b946c5c\7b677cd4575b4c1f88a836d3be835faa.proj...
      CACHE https://api.nuget.org/v3-flatcontainer/godot.net.sdk/index.json
         0>C:\development\Source.csproj : error : Could not resolve SDK "Godot.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
    C:\development\Source.csproj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
    C:\development\Source.csproj : error :   Unable to find package Godot.NET.Sdk with version (= 4.1.0-beta.3)
    C:\development\Source.csproj : error :   - Found 48 version(s) in nuget.org [ Nearest version: 4.1.0-dev.1 ]
    C:\development\Source.csproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Godot.NET.Sdk" because directory "C:\Program Files\dotnet\sdk\7.0.202\Sdks\Godot.NET.Sdk\Sdk" did not exist.
         1>Project "C:\development\Source.csproj" on node 1 (Restore target(s)).
         1>C:\development\Source.csproj : error MSB4236: The SDK 'Godot.NET.Sdk/4.1.0-beta.3' specified could not be found.
         1>Done Building Project "C:\development\Source.csproj" (Restore target(s)) -- FAILED.
    
    Build FAILED.
    
             C:\development\Source.csproj : error : Could not resolve SDK "Godot.NET.Sdk". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
           C:\development\Source.csproj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
           C:\development\Source.csproj : error :   Unable to find package Godot.NET.Sdk with version (= 4.1.0-beta.3)
           C:\development\Source.csproj : error :   - Found 48 version(s) in nuget.org [ Nearest version: 4.1.0-dev.1 ]
           C:\development\Source.csproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Godot.NET.Sdk" because directory "C:\Program Files\dotnet\sdk\7.0.202\Sdks\Godot.NET.Sdk\Sdk" did not exist.
    
    
           "C:\development\Source.csproj" (Restore target) (1) ->
             C:\development\Source.csproj : error MSB4236: The SDK 'Godot.NET.Sdk/4.1.0-beta.3' specified could not be found.
    
        0 Warning(s)
        2 Error(s)
    
    Time Elapsed 00:00:00.57

### Steps to reproduce

1. Create a project in Godot .NET v4.0.2 add a scene and a basic script.
2. Press play and verify that the game starts.
3. Close down the editor and open the project in Godot .NET v4.1.0-beta3
4. Press play - the error occurs.

### Minimal reproduction project

[UpgradeDemo-4.0.2-to-4.1.0.beta3.zip](https://github.com/godotengine/godot/files/11821452/UpgradeDemo-4.0.2-to-4.1.0.beta3.zip)

**Comment by QueenOfSquiggles** [comment]
I can attest to this bug as well. It's popping up for me: Manjaro KDE (Linux) using Godot 4.1.beta3.mono.

**Comment by akien-mga** [comment]
Yeah I was teaching @YuriSizov how to do the release but we missed this step :D

Fixed!

**Comment by granitrocky** [comment]
I don't want to open a new ticket since this seems like a simple fix, but it looks like this happened again for 4.2.0-beta. Looks like the default string in the `.csproj` is using `4.2.0-beta`, and the nuget package is `4.2.0-beta.4`

**Comment by Visne** [comment]
This is still an issue on 4.2.0

**Comment by YuriSizov** [comment]
If you are using custom builds, they are labeled as `beta` by default (or as `alpha`, `dev`, or `rc`, depending on the state of each release). See the `version.py` file. There are no official packages for `4.2.0-beta`, because that's not a valid release identifier, and we cannot build a nuget package for every commit in the development branch.

You can change your `version.py` file to use `beta1` as a version status, or you could build nuget packages locally instead of getting them from the public repository (cc @raulsntos).

**Comment by raulsntos** [comment]
Godot automatically changes the SDK of opened projects to match the engine's version because it's the only version that we can guarantee works. But, as explained by @YuriSizov, we don't publish unnumbered versions.

Custom builds of the engine need to use a local NuGet repository as explained in the .NET module [README.md](https://github.com/godotengine/godot/blob/7f884b4e0017368e193d96f425aac6c2d8a86eb0/modules/mono/README.md#how-to-deal-with-nuget-packages).

Using a different version (like changing `version.py` or manually changing the version in the `.csproj`) may result in issues if the API changed or there's a mismatch in the struct of function pointers used by the module for interop. So I wouldn't recommend it, unless you really know what you are doing.

**Comment by Visne** [comment]
I don't really understand why Godot looks for `Godot.NET.Sdk/4.2.0-beta` instead of `Godot.NET.Sdk/4.2.0-beta.1` even though unnumbered versions aren't published.

**Comment by raulsntos** [comment]
The only versions of Godot that should look for an unnumbered version should be custom builds. Did you build Godot from source? If not, where did you download Godot from?

**Comment by Visne** [comment]
I built it with [this AUR package](https://aur.archlinux.org/packages/godot-mono-git). Apologies for not making that clear earlier. Looking at the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=godot-mono-git) though, it doesn't look like it differs from just building from source.

**Comment by raulsntos** [comment]
I'm not very familiar with the AUR. I'd recommend to use https://github.com/godotengine/godot-build-scripts with tagged releases, but I guess since the package name ends with `-git`, it's meant to use the latest master. In that case, I guess the PKGBUILD should create the local NuGet repository and push the packages (using `--push-nupkgs-local`).

**Comment by Visne** [comment]
I will suggest it to the author of the package. Thanks for the help!

**Comment by HurricanePootis** [comment]
> I'm not very familiar with the AUR. I'd recommend to use https://github.com/godotengine/godot-build-scripts with tagged releases, but I guess since the package name ends with `-git`, it's meant to use the latest master. In that case, I guess the PKGBUILD should create the local NuGet repository and push the packages (using `--push-nupkgs-local`).

Hello, package maintainer here thanks for the suggestion! Currently testing this right now

**Comment by raulsntos** [comment]
@HurricanePootis The nupkgs-local needs to persist in the system so that users can retrieve the packages when building Godot projects.

**Comment by FabioLolix** [comment]
Where should be installed nupkgs-local ? Under $HOME is not a welcome option for AUR/Arch packages

**Comment by HurricanePootis** [comment]
> @HurricanePootis The nupkgs-local needs to persist in the system so that users can retrieve the packages when building Godot projects.

I can't think of a way to create a local NuGet package while building godot, and then have it installed, and have godot to point towards it.

**Comment by raulsntos** [comment]
I don't know how PKGBUILD works, but creating a local NuGet source can be done with the following command:

```bash
dotnet nuget add source ~/MyLocalNuGetSource --name MyLocalNuGetSource
```

This creates a source with the path `~/MyLocalNuGetSource`. The path can be anything as long as the user has read/write permissions in that directory. This configuration is written to the user [NuGet configuration](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) (usually in `~/.nuget/NuGet/NuGet.Config`).

Then, when building the Godot assemblies, make sure to specify the local NuGet source with the `--push-nupkgs-local` option (this copies the built NuGet packages to the specified local source):

```bash
./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin --push-nupkgs-local ~/MyLocalNuGetSource
```

You can check the list of registered sources with:

```bash
dotnet nuget list source
```

This lists the sources that NuGet will use when restoring packages. The local NuGet source with the copied packages must be registered so that users can build Godot projects, it will be used to retrieve the packages that were built by `build_assemblies.py`.

---

What steps are you struggling with? If using the dotnet CLI to setup the local NuGet repository for the user installation is not possible, perhaps you can write a custom NuGet configuration file.

Any additional files in `~/.nuget/NuGet/config/` will be used for the NuGet configuration. For example, you can create a file in `~/.nuget/NuGet/config/MyAdditionalConfig.Config` that contains the configuration that registers the local NuGet source:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="MyLocalNuGetSource" value="/home/user/MyLocalNuGetSource" />
  </packageSources>
</configuration>
```

**Comment by HurricanePootis** [comment]
> I don't know how PKGBUILD works, but creating a local NuGet source can be done with the following command:
> 
> ```shell
> dotnet nuget add source ~/MyLocalNuGetSource --name MyLocalNuGetSource
> ```
> 
> This creates a source with the path `~/MyLocalNuGetSource`. The path can be anything as long as the user has read/write permissions in that directory. This configuration is written to the user [NuGet configuration](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses) (usually in `~/.nuget/NuGet/NuGet.Config`).
> 
> Then, when building the Godot assemblies, make sure to specify the local NuGet source with the `--push-nupkgs-local` option (this copies the built NuGet packages to the specified local source):
> 
> ```shell
> ./modules/mono/build_scripts/build_assemblies.py --godot-output-dir ./bin --push-nupkgs-local ~/MyLocalNuGetSource
> ```
> 
> You can check the list of registered sources with:
> 
> ```shell
> dotnet nuget list source
> ```
> 
> This lists the sources that NuGet will use when restoring packages. The local NuGet source with the copied packages must be registered so that users can build Godot projects, it will be used to retrieve the packages that were built by `build_assemblies.py`.
> 
> What steps are you struggling with? If using the dotnet CLI to setup the local NuGet repository for the user installation is not possible, perhaps you can write a custom NuGet configuration file.
> 
> Any additional files in `~/.nuget/NuGet/config/` will be used for the NuGet configuration. For example, you can create a file in `~/.nuget/NuGet/config/MyAdditionalConfig.Config` that contains the configuration that registers the local NuGet source:
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     <add key="MyLocalNuGetSource" value="/home/user/MyLocalNuGetSource" />
>   </packageSources>
> </configuration>
> ```

The problem is that a PKGBUILD isn't supposed to create files in the user's home folder. It is supposed to create a `*.pkg.tar.zst` file that has the entire program built with anything that it needs to run, that can be installed on any system afterwards. It's not proper to touch anything from the user's `~`, which makes creating a local a NuGET repo that is also portable, that godot will look to, hard.

**Comment by raulsntos** [comment]
I see, I don't think it's possible to setup a local NuGet source then. Can PKGBUILD add patches on top of the git sources? If so, you could add code to Godot that configures the custom NuGet source when opening the editor or something like that.

When building Godot, the packages are created and included in the PKGBUILD output. If you know where the packages will be stored after installation, then you can have the Godot editor check the user's NuGet configuration and if the custom source doesn't exist, create it and add it. The custom source would just point to the directory where the packages are stored.

In Godot we've modified the user's NuGet configuration in the past and that lead to more problems that it solved, so I wouldn't recommend this approach, but it seems like it might be the only option for your use case.
