### ISSUE TITLE
C# Type Checks failing in editor, works in game

### ISSUE THREAD

**Issue by TinkerWorX** [godotengine/godot#78668]
### Godot version

v4.1.beta2.mono.official [a2575cba4]

### System information

Windows 11 - Compatibility

### Issue description

I need to detect the type of child nods to show custom node configuration warnings, but this doesn't work in the editor, instead it's returning a generic parent type. In game it works as expected.

### Steps to reproduce

Open the attached project, open the Scene file and move the node with the name "Child" to be the child of the "Father" node. The log will show the following text:
```
Child type is: Godot.Node2D
```
Now launch the game, the log will show the following text:
```
Child type is: Child
```
I would expect it to always show Child.

### Minimal reproduction project

[ChildTypeBug.zip](https://github.com/godotengine/godot/files/11859677/ChildTypeBug.zip)

**Comment by raulsntos** [comment]
This is expected behavior. In the editor, classes without the `[Tool]` attribute don't exist so they can't be instantiated, instead the editor will make an instance of the closest native type (in this case: `Node2D`). If you want to use the `Child` type in code running in the editor make sure to add the `[Tool]` attribute to it.

**Comment by TinkerWorX** [comment]
Just be sure I understand, you're saying the child also needs the tool attribute then? Because the parent already has it.

**Comment by TinkerWorX** [comment]
I confirmed the above was the case. With tool attribute added to my child, it works as expected. Thanks!
