### ISSUE TITLE
PopupMenu report runtime error when set accelerator

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#78737]
### Godot version

v4.1.beta3.official [ada712e06]

### System information

Windows 10, 64bit

### Issue description

I want set my `File/New` menu's accelerator to `Ctrl+N`, and the docs say:
![image](https://github.com/godotengine/godot/assets/35988767/c68bed9e-a17b-43c4-a684-147b65505959)
And then run, everything work but I found it report runtime warning:
![image](https://github.com/godotengine/godot/assets/35988767/ea3105c1-460a-499b-8e6e-5811073859f0)

### Steps to reproduce

/

### Minimal reproduction project

[MenuTest.zip](https://github.com/godotengine/godot/files/11878762/MenuTest.zip)

**Comment by AThousandShips** [comment]
Does this go away if you follow the suggestion?

**Comment by CsloudX** [comment]
> Does this go away if you follow the suggestion?

Does I use wrong way with`menu.set_item_accelerator(1,KEY_O|KEY_MASK_CTRL)` ?
If it is and I want set accelerator with `Ctrl+O`, How should I do?

**Comment by AThousandShips** [comment]
This is probably due to an incorrect configuration for keys, but it's difficult to say exactly how to set them up internally as they're not exactly a bitmask and not exactly an enum, will investigate further, to avoid this you can add:
`@warning_ignore("int_as_enum_without_cast", "int_as_enum_without_match")`
Before the line you're doing this in, as a workaround

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/40836 and https://github.com/godotengine/godot/issues/69265.

**Comment by CsloudX** [comment]
It like was fixed in 4.2 dev3
