### ISSUE TITLE
emitted particles are rotating along with the sprite

### ISSUE THREAD

**Issue by nictaylr** [godotengine/godot#7876]
i have made a KinematicBody in godot: hierarchy like this:
- KinematicBody
  - Particle2D
  - Sprite

But the problem is when the whole body rotates, ALL The emitted particles do too! This is very confusing, how i can solve?

**Comment by eon-s** [comment]
I don't know what effect you want to get, it could be the local space option on the Particles2D, or something else.

**Comment by freemanfromgodotengine** [comment]
There is no bug here. It's logical. Because your particle node is a childnode to the KinematicBody parent node, whatever you do with the parent, affects the child.
What you want to do is to make Particles2D  a child to a different parent (node2d for example) that follows position of your KinematicBody.

**Comment by nictaylr** [comment]
o K, thanks that i will try
