### ISSUE TITLE
Android: modifying Unique Name can produce un-parsable package

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#7877]
Tested on Godot 2.1.2
Windows 10 64 bits

After helping someone to export for Android, I realized after 2 hours of fiddling he put "Something_Test" in the Package / Unique Name property.
This caused the package to still export fine, apparently without reported errors, but once on Android the OS just says "Cannot parse package".

Changing the setting back to "org.godotengine.$genname" fixed it.
![image](https://cloud.githubusercontent.com/assets/1311555/23240246/b2251920-f96c-11e6-9a28-fba2ab5337f5.png)

But what is actually the meaning of this property? It doesn't look like a unique name, but an identifier that has to comply to some rules.
If this is not a bug, there should be documentation or editor checks for that kind of property, because the guy I helped could never have figured this out himself, and me neither if he didn't sent the whole project that I diff-tested line by line :'D

Edit: it must be an Android requirement, like "org.stuff.thing" or "com.yolo.foo" I guess. But again, no info about that unless the user already knows about Android development.

**Comment by volzhs** [comment]
in my opinion, game developer should study about the platform which (s)he wants to publish.
I don't want to know, but I want to make it work is non-sense.
But, in this case, we could give some hint about it.

**Comment by Zylann** [comment]
I agree, I know the basics of exporting to Android using a one-click-deploy engine (Unity or here Godot), I know how to get the SDK and install the right tools, check permissions etc. The "Cannot parse package" is often due to package not being signed. That was also the case, but when I fixed it the error persisted. In fact, is there any way the exporter can report informative errors before getting the generic "Cannot parse package"? Because, for example the signing problem is printed in normal color somewhere in the console, instead of being shown in an error log in the editor (or even in red in the console).

**Comment by freemanfromgodotengine** [comment]
Yes, learning about the platforms is necessary to avoid small and big problems later.
I would recommend to anyone who wants to develop mobile games in Godot to first play a little with the dedicated IDE for each platform - XCode for iOS and Android Studio for Android. It is probably enough to just set and start a simple project a couple of times, read some tips IDE gives etc., to know how things work for each platform from the inside. In case of making games for iOS in Godot developer will need this know-how anyway.

As to Android's application id (the subject above) , Google says:

> Every Android app has a unique application ID that looks like a Java package name, such as com.example.myapp. This ID uniquely identifies your app on the device and in Google Play Store. If you want to upload a new version of your app, the application ID (and the certificate you sign it with) must be the same as the original APK—if you change the application ID, Google Play Store treats the APK as a completely different app. So once you publish your app, you should never change the application ID. 

For more info check: https://developer.android.com/studio/build/application-id.html

Lack of this knowledge may lead to problems with publishing the game, updating it and even wasting completely good app's name, that will not be available anymore **ever**, because of the application id stupid mistakes done in Godot's export settings, so yes, like @volzhs said, 
> game developer should study about the platform which (s)he wants to publish.

**Comment by Zylann** [comment]
Indeed this happened mainly because the guy I was helping was new to game development, so I helped him and discovered this. But my point is more that, if Godot can detect such things at export time (which it seems to do already), can it do that with an easy-to-spot error log? Because at the moment export looks like a fire-and-forget process. Or is it not possible at the moment?

**Comment by akien-mga** [comment]
See also #23172.

**Comment by akien-mga** [comment]
Fixed by #23320.
