### ISSUE TITLE
Shader preprocessor #if and #else highlighted with wrong color

### ISSUE THREAD

**Issue by Kinwailo** [godotengine/godot#78799]
### Godot version

4.0.3

### System information

Win7

### Issue description

#if and #else highlighted with the color same as if and else shader statement:

![image](https://github.com/godotengine/godot/assets/28286958/c2d58151-d6d2-4305-b4da-36e76e316caf)

### Steps to reproduce

1. Create shader
2. Add #if and #else

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Syntax highlighting keywords in CodeEdit can't contain symbols like `#`, so this is a limitation we can't fix.

**Comment by bitsawer** [comment]
We could probably change the preprocessor keywords to use control flow keyword colors, that way they would be at least consistent. Currently they mix control flow and normal shader keyword colors because they conflict with normal shader keywords, which can look a bit weird. I'll probably make a PR at some point, this has been bugging me a bit, too. It's a simple change, looks like this:

![colors](https://github.com/godotengine/godot/assets/22456603/cf4177c8-4267-4711-9888-133d87de0c9e)

Long term solution would be to create an improved syntax highlighter as Calinou said, but there tends to more important tasks at hand currently.
