### ISSUE TITLE
MacOS crash when trying to Run project with corrupted custom icon (.icns)

### ISSUE THREAD

**Issue by mr-dreich** [godotengine/godot#78819]
### Godot version

v4.1.rc1.official [1f9e540f1]

### System information

Godot v4.1.rc1 - macOS 13.3.1 - Vulkan (Mobile) - dedicated AMD Radeon Pro 5300M - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 Threads)

### Issue description

Here is the [MacOS error report](https://pastebin.com/0SBBpCc6) and the [Terminal output](https://pastebin.com/RTB98aYF) when running my project from the terminal.

I have tested this on a new and clean project with only a Node2D as the root and a Sprite2D as a child, and the project Runs fine, so it has to be something I have done. I have no Shaders, no Particles, and the only thing left is trying to write to the user:// folder, but I have commented those out and it still crashes. My project currently consists of Control nodes, this project is mainly UI focused.

Oddly enough, I can build for iOS just fine, but when trying to export for MacOS it does the exact same crash, with the same error log. I only use my Macbook when I'm not at home, I usually use my desktop, which is running Windows 11 and it works just fine.

pycbouh over on Reddit had me try different versions and I went all the way back to 4.1 dev 4 and still the same issue.

### Steps to reproduce

After selecting my project and the Editor opens, I click the Run button and it crashes back to the Editor. Usually no error in console, and sometimes MacOS will provide an error popup.

### Minimal reproduction project

I would like to supply a reproduction project, but this project isn't something I am comfortable giving out publicly.

**Comment by akien-mga** [comment]
Thanks for the report and the testing done so far!

Without a reliable way to reproduce it on our side, we'll be reliant on more testing from you to help narrow down what causes the issue, if you're willing.

I'm not sure exactly how to debug things yet, but these are things you could try (or confirm if already tried) to help us narrow it down:

- You mentioned "I went all the way back to 4.1 dev 4 and still the same issue." Does it mean that you tried 4.1 dev 3 and it worked fine (i.e. the issue started in dev 4), or you didn't test earlier builds? If the latter, could you test dev 3, dev 2 and dev 1 too, to pinpoint the first one where the bug starts?

- The macOS report and terminal output don't provide enough information because the Godot binary we provide doesn't include debug symbols by default. There's still at least a hint that it might be a crash of the Vulkan (MoltenVK) renderer, though this could be a false positive. To narrow it down, you could:
  * Check whether running your project with OpenGL works around the issue. You can change this in the Project Settings by changing "Rendering Method" to "GL Compatibility".
  * Compile Godot from source with `scons debug_symbols=yes` to have debug symbols, and use that compiled binary to run your project and see if you get more details when it crashes. Here's the [relevant documentation](https://docs.godotengine.org/en/latest/contributing/development/compiling/compiling_for_macos.html) if you want to try that.

- Since you mention that other projects don't fail, and exporting your project to iOS also works fine, this may suggest something specific to the configuration of your macOS export preset in the Export menu. Or it could be some cached data that somehow messes things up. To test that, could you:
  * Temporarily move/rename the `export_presets.cfg` file so that it no longer uses whatever you have configured in it for macOS, and see if the project runs OK.
  * Temporarily move/rename the `res://.godot` folder to force reimporting assets and re-creating cached editor data and shaders, and see if the project runs OK.
  * Temporarily move/rename the folder `~/Library/Application Support/Godot/projects/<project name>-<hash>/`, and see if the project runs OK.
  * Temporarily move/rename the folder `~/Library/Application Support/Godot/app_userdata/<project name>/`, and see if the project runs OK.
  * All these "temporarily" are because if one of them fixes the issue, it could be useful to still have access to the old bad data to compare them and see how the engine could solve the problem of using such bad data.

**Comment by mr-dreich** [comment]
Thank you for your very thorough reply!

But yes, I tried my project with all the version back to dev4, and tried dev3, dev2, and dev1, this morning, still the same error. 

I have completely removed those directories and had Godot create fresh ones before I made this report and it didn't fix anything sadly.

I also have tried running my project with every renderer. Forward+, Mobile, and Compatibility. Still the same error.

The last test I'll need to try is compile from source with debug symbols like you said, which will have to wait, as I am getting ready to leave for work.

**Comment by mr-dreich** [comment]
I have finally got time to build from source on my Macbook, here is the [MacOS Crash Report](https://pastebin.com/ry9E2q7Z).

I would be willing to upload my project if someone wanted to peek at it, I just don't want it public as I don't know where I am going with this and if I do release it for purchase, I don't want the source floating around.

**Comment by akien-mga** [comment]
Thanks, that's very helpful! According to the log, it's crashing on this line:

https://github.com/godotengine/godot/blob/46424488edc341b65467ee7fd3ac423e4d49ad34/main/main.cpp#L3225

So it's crashing when setting the window icon. Is it a custom icon, and if so can you share it?

CC @bruvzg

**Comment by mr-dreich** [comment]
I do have a custom icon set, I used an online generator to create one based on my PNG icon I created. I cleared that and it seems to be working now. Whats strange, is that was so early on in the project, that it would have been working back then and at some point stopped working.

**Comment by akien-mga** [comment]
Great! That should be fixable, but also doesn't sound too critical for 4.1 anymore since most users shouldn't have a corrupted custom icon.
