### ISSUE TITLE
Import .blend files through Assimp

### ISSUE THREAD

**Issue by rredesigns** [godotengine/godot#7883]
I was looking at Skyline engine features and I saw it can import a lot of formats, .blend files included, by using Assimp. 

Considering Blender is also FOSS, it might be a good idea to create a tighter integration with it for the asset pipeline, at least makes a lot of sense to me. Also, the Collada exporter is so bugy sometimes that maybe it would be best to just use the blend files.

Animation is so much more pleasant inside Blender that this could be a killer feature. 

Is it possible to implement and translate Blender objects properties to Godot's properties system from a blend file?

**Comment by toger5** [comment]
seems like this is the plan:
https://docs.google.com/spreadsheets/d/1kaSAVoaeYJ70U19MuePJhB4f-6PLSuX-nQ_uBII3_KI/edit#gid=0

**Comment by rredesigns** [comment]
All I see is an export plugin. We already have one, but that's not what I had in mind.

**Comment by Hinsbart** [comment]
@rredesigns  Well the current exporting workflow is just the collada one, which you said yourself, is a bit buggy. That's because it does two conversion steps using a sub-optimal format...
(`blender -> export dae`, `godot -> import dae as scene`).
By just doing `blender -> export to tscn`, we can avoid a lot of trouble and focus on bringing that scene data into godot in the best possible way :P
So, while conceptually different from what you have in mind, I think in the end it roughly serves the same purpose. This approach is also likely to be far easier to implement than trying to parse `*.blend`s from within godot.

Regarding the use of Assimp: I think I've read somewhere (so don't quote me on this) that assimp importing probably won't be accepted in the core, but anyone interested in this can of course just write a module.

**Comment by rredesigns** [comment]
Well, converting .blend to .scn is pretty much the whole concept. If it's done inside or outside the engine would make no difference, I hope. 

I was expecting someday to be able to use Blender's shapekeys though. I don't know if that will be doable but it would allow to expand the engine's capabilities a lot. I already used it (with great succes) as a motion graphics presentation tool. My class mates were all crazy about Godot, but unfortunately is like 5 times harder to animate in it.

I will be waiting for better integration with Blender anyway, seems like the logical way to go. :D

**Comment by toger5** [comment]
@rredesigns I though the export plugin means exporting to tech directly with advanced merging. because it would make no sense to list it if it would be a improved colada exporter.

**Comment by set-killer** [comment]
@rredesigns You can use the blender's shape keys with the Better Collada exporter:
https://github.com/godotengine/collada-exporter

**Comment by rredesigns** [comment]
I knew about skeletal animation, and exported successfully that way (although some models were all messed up after export).

I didn't know about shapekeys though. How does Godot handle those?

**Comment by set-killer** [comment]
@rredesigns  When exporting with the Better collada exporter there is an option on the side panel which says:

```Shape Keys``` with additional explanation of ```Export shape keys for selected objects.```.

By default this options is disabled so you have to enable it. After that you export your things to .dae and when you import them into Godot you will see an Animation Player added to your node tree. And with the animation player you can play the imported animations.

So after all its pretty much the same as the skeletal animations, just click on the ```Shape Keys``` before exporting...

**Comment by reduz** [comment]
Importing .blend files directly will never work, the only way to obtain the
information correctly is by baking it upon export to collada, fbx or
another format.

**Comment by rredesigns** [comment]
@set-killer I can't see the shape key option in the export panel. I have the add-on from the official download provided in Godot's website, and [this](http://i.xomf.com/ymlgs.png) is all I get.

Still, the model doesn't hold together inside godot, it's faces twist in weird ways.

**Comment by reduz** [comment]
Model is probably not well done

**Comment by reduz** [comment]
Try disabling apply modifiers and see if it helps

**Comment by rredesigns** [comment]
@reduz Hola Juan!

Nope. It doesn't help at all. About the previous comment, I don't think there's a way to model badly [this](http://i.xomf.com/ypryf.png) model. And [this](http://i.xomf.com/fxlcc.png) is how it looks inside Godot.

**Comment by reduz** [comment]
Several much more complex models with skeletons, blend shapes, shape keys,
etc. were exported without issue, so either something has to be fixed in
that one for it to work, or it uses an unsupported feature that breaks at
export, or a non compatible export setting, don't really now.
For 3.1 will eventually work on FBX import and a direct to Godot exporter
for blender, to avoid these kind of things.

**Comment by rredesigns** [comment]
That sounds terrific. 

I used this simple, unrigged cilinder just to leave out the possibilities of glitches due to complex skinning and other stuff. I did manage to import rigged models with no problems, is just particularly shape keys that are an issue, which is super useful for motion graphics (and yeah, I know Godot is not meant for that, but it does the job ;) ).

**Comment by reduz** [comment]
Godot 3.0 should work great for motion graphics :)
Other than that I'm really not sure, but hope can improve the import
options for 3.1

**Comment by set-killer** [comment]
@rredesigns With that version of the exporter that you got, it exports the shape keys no matter what options you have checked. But if you update the exporter from the current git master branch you will see [this option](http://pasteall.org/pic/show.php?id=113748), where you can choose if you want to export the shape keys or not.

Back on the topic:
Blender regularly changes the format of their .blend files. If you try to open old (really old) .blend files with newer Blender you may encounter problems. And actually this is normal, because Blender continuously adds new features and extends the old ones. So which versions of the Blenders format are we going to support? Also imagine a situation where you create your assets with the latest version of Blender, which is not yet supported from the Godot's importer. That would be a problem, that could be described as "Waiting for (newer) Godot" :)

So to sums the things up:

> Importing .blend files directly will never work...

**Comment by Anutrix** [comment]
Any updates? Is this still relevant?

**Comment by Calinou** [comment]
I'm not sure if this is still relevant now that we have the [Godot Blender Exporter](https://github.com/godotengine/godot-blender-exporter).

**Comment by akien-mga** [comment]
This likely won't happen, as even though we added parts of Assimp to the engine for FBX support, we're actually going to remove some of it and focus only on our own Assimp-derived FBX import pipeline.

For importing from Blender, the recommended workflows are glTF 2.0 (which is actively being worked on in both Blender and Godot to ensure the best compatibility) and the Godot ESCN exporter for Blender (albeit it needs an update for the latest Blender patch releases).
