### ISSUE TITLE
NavigationServer2D map_get_path with multiple Navigation Map is not updated

### ISSUE THREAD

**Issue by Delectus98** [godotengine/godot#78856]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10 - Godot 4.0.3 - Vulkan

### Issue description

Using multiple navigation map with the singleton NavigationServer2D can only provide path from the first Navigation RID used even if a new Navigation RID is provided in NavigationServer2D.map_get_path(<RID here>, ...);

In my example I use two different TileMaps with their own Navigation map (TileMap.get_navigation_map(0)).

### Steps to reproduce

Create two tilemaps within a tree structure:

    TileMap1
    TileMap2

Populate TileMap1 with tiles where a path can be created.
Add obstacles to TileMap2 where the path should be blocked.

Set point A and point B (Vector2) on TileMap1, where the tiles allow free movement.
Set point A and point B (Vector2) on TileMap2, where the tiles represent walls.

For debugging purposes, draw a line representing the path using NavigationServer2D.

Next, utilize NavigationServer2D with TileMap1 to find a path from point A to B:

    NavigationServer2D.map_get_path(tilemap1.get_navigation(0), A, B, true/false);

    A clear and valid path should be visible.

Subsequently, employ NavigationServer2D with TileMap2 to find a path from point A to B:

    NavigationServer2D.map_get_path(tilemap2.get_navigation(0), A, B, true/false);

    The expected outcome is to observe the same path as TileMap1, despite TileMap2 containing only walls.

### Minimal reproduction project

[Test.zip](https://github.com/godotengine/godot/files/11910784/Test.zip)

**Comment by smix8** [comment]
The Layer0 of a TileMap by default always joins the World2D default navigation map.

Since that is the only layer you are using all your navigation polygons end up on the same navigation map.

If you want separate navigation maps for the separate TileMaps you need to set them to different maps.

Only TileMap Layer1+ create new and unique navigation maps because those maps do not exist by default.

**Comment by Delectus98** [comment]
Ok thanks you !

For those who wants a solution, here a simple project that can make it work :

[Test.zip](https://github.com/godotengine/godot/files/11923698/Test.zip)

Brief explaination : 
- Add two tilemaps
- Duplicate tile_set.tres and attach different tileset to every tilemap
Tilemap 1
![image](https://github.com/godotengine/godot/assets/33693052/5c102fce-d03d-4f44-9dfb-15d6acb87316)
Tilemap 2
![image](https://github.com/godotengine/godot/assets/33693052/18bdb570-f2a0-43bd-8b83-c8febb6e83a6)

**Comment by smix8** [comment]
Closing because I don't see anything actionable here left and there has been no reply in 3+ weeks.

The `TileMap.get_navigation_map()` function has this documented that the TileMap layer0 uses the default World2D navigation map while all other layers use new navigation maps. You can override those map with the `TileMap.set_navigation_map()` function. That two or more TileMaps inside the same World2D all use the shared default map has been also explained if it was not obvious from this.

Feel free to reply if you think some additional information should be added to the already existing documentation or other reasons this should be kept open.
