### ISSUE TITLE
Easier procedural post-processing for AnimationPlayer

### ISSUE THREAD

**Issue by RandomShaper** [godotengine/godot#7895]
Things to discuss here:
- Adding a `update()` or `process()` method to `AnimationPlayer`.
- Adding some way of post-processing the animation after each tick without getting cumulative results and other potential problems. API design, philosophy, etc.

This is what @SaracenOne and me said during the conversation that motivated this feature proposal:

> One thing I noticed from seeing this is that it would seem we should add a 'manual' process mode to control exactly when the AnimationPlayer advances for the sake of adding procedural animation. I'll look into adding that in later.
> 
> Do you mean a mode in which the animation would have to be told to be updated by code instead of doing it in the process callbacks?
> 
> Yeah, basically where you manually call the 'advance' method to move the animations forward. By doing that, you can then add in extra bits of procedural animation through code on top of conventional animation for things like head rotation, IK, ect.
> 
> Some random thoughts to consider:
> - Currently in order to post-process animations I'm adding a node after the
> animator so it gets processed after the former has updated. This could be
> considered a standard way of doing it or instead just a hack so it's
> advisable to add some explicit functionality to the player. Maybe a
> post-process callback could serve.
> - Furthermore, for 2D animations you need just rotation most of the time.
> So a downside of the hacky approach is that when you need to tweak
> positions in realtime (for instance, to keep your character's feet on the
> ground while blending between crouch and stand), your animations must
> include tracks for position to ensure adjustments don't accumulate, even if
> they have just one key for the initial value.
> It would be much better if the player featured a flag or something you
> could enable for getting post-processing reset on every tick.
> - Exposing an update() method may be useful; i.e., a shortcut for
> player.seek(player.get_current_animation_pos(), true)
>

**Comment by karroffel** [comment]
I actually like this proposal, seems very powerful and not that hard to implement. 

On the other hand - I have no clue about the animation code in Godot 😄

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
