### ISSUE TITLE
Vulkan: Screen space reflections weirdly rotated with orthogonal cameras

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79002]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Mac Ventura - Vulkan API 1.2.231 - Forward+ - Apple M1

### Issue description

SSR doesn't appear correctly with orthographic cameras, the reflections are rotated around seemingly inverse to the camera.

There's a similar issue #49204, however the previous one is for Godot 3.5 and the workarounds no longer work. The editor camera no longer works properly, and neither does moving the camera far away. I believe this may be a different (though likely related) problem. Hopefully this is okay.

Screenshot:
<img width="595" alt="Screenshot 2023-07-03 at 4 50 23 PM" src="https://github.com/godotengine/godot/assets/138056014/7c97a30b-a0ab-429e-b8b5-1db86978798e">

Best regards.

### Steps to reproduce

1. Switch editor to orthographic mode and rotate the camera around, reflections are weird (in previous issue the editor camera was unaffected)
3. Preview `OrthoCamera` -- this is set to use the previous workaround of moving the camera far away, however this doesn't seem to work anymore

### Minimal reproduction project

[SSRTest.zip](https://github.com/godotengine/godot/files/11941716/SSRTest.zip)

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/49204.

**Comment by farfalk** [comment]
This still happens in 4.3beta2
![immagine](https://github.com/godotengine/godot/assets/9095842/6b1c8729-1efb-412a-b9d0-26ff34475b9b)

**Comment by mertkasar** [comment]
Also suffering this issue in my project. Reproducible in every **v4.x.x** release.

Using negative camera space positions solves the wrong reflection rotations in orthogonal cameras. Turns out the rotations were actually reversed: 
```glsl
return vec3(-(screen_pos.xy * params.proj_info.xy + params.proj_info.zw), z);
```
[_original line↗_](https://github.com/godotengine/godot/blob/26d1577f3985363faab48a65e9a0d9eed0e26d86/servers/rendering/renderer_rd/shaders/effects/screen_space_reflection_inc.glsl#L23)

However, issue #49204 from branch **3.x** appeared here, too. Reflections gain perspective in orthographic cameras as the z-position of the camera lowers. Here is a minimal reproduction of this in a custom build with the fix above:
<img width="420" alt="ssao_on" src="https://github.com/godotengine/godot/assets/2726562/7e703197-6f49-4d68-8158-ff2332a93fec">
_(in-game camera sits at z:25)_

Whereas the expected behavior is much more like this:
<img width="420" alt="ssao_on" src="https://github.com/godotengine/godot/assets/2726562/6540aa00-08a3-43b3-adbf-39f1af2e63f3">
_(orthogonal editor camera, which probably sits at much greater z)_

**MRP:**
[ssr_orthographic_mrp.zip](https://github.com/user-attachments/files/16164439/ssr_orthographic_mrp.zip)

@Geometror's workaround mentioned in the other issue can also be applied here once this issue is fixed. But still, reflections in an orthogonal camera should be… orthographic, I guess 😅 Perspective can be omitted entirely for SSR with orthogonal cameras.

**Comment by Calinou** [comment]
> Using negative camera space positions solves the wrong reflection rotations in orthogonal cameras. Turns out the rotations were actually reversed:

Can you open a pull request for this?
