### ISSUE TITLE
WorldEnvironment canvas mode problem with PointLight2D

### ISSUE THREAD

**Issue by mralizadeh** [godotengine/godot#79001]
### Godot version

v4.1.rc2.official [46424488e], v4.0.3.stable.official [5222a99f5]

### System information

Windows 10, GTX 660 Ti

### Issue description

When using canvas mode of WorldEnvironment with PointLight2D, light texture has problem.

(This problem not seen in v3.5.1.stable.official [6fed1ffa3])

Using Canvas mode:
![111p](https://github.com/godotengine/godot/assets/36473297/12874833-2d93-4e64-9f60-9fffb0e17c23)

Using other mode:
![111w](https://github.com/godotengine/godot/assets/36473297/c4768810-84a4-4bb3-b72b-e2f5a72eda40)

### Steps to reproduce

- Create a 2d scene
- Add a Sprite2D and some dark texture for background
- Add a PointLight2D, set some radial gradient as texture
- Add a CanvasModulate, set a dark color (for better viewing issue)
- Add a WorldEnvironment, create environemnt (there is no problem with light)
- Set Mode to Canvas to see the problem!

![222p](https://github.com/godotengine/godot/assets/36473297/62fd2143-95d1-4160-a92c-d553a1ac7952)

### Minimal reproduction project

[problem_project.zip](https://github.com/godotengine/godot/files/11941358/problem_project.zip)

**Comment by Calinou** [comment]
Does this occur when using the Forward+ or Compatibility rendering methods?

**Comment by mralizadeh** [comment]
Update:

The problem is seen when Rendering Method is mobile:

![333p](https://github.com/godotengine/godot/assets/36473297/3465850c-c9e0-4dcb-b770-490516ffd7e5)

**Comment by mralizadeh** [comment]
> Does this occur when using the Forward+ or Compatibility rendering methods?

No, only in mobile mode.

**Comment by karpov-kir** [comment]
Hey! Have you found a workaround for that? I've spent a lot of time trying to fix it but without success. I haven't found anything that could help in the documentation. I've also tried to set all [project settings](https://docs.godotengine.org/en/4.2/classes/class_projectsettings.html) tagged `.mobile` to match normal ones but without success.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/87894.

Try switching to the Compatibility rendering method, as it provides greater precision despite using the same color format since it always works in sRGB colorspace (as opposed to the Mobile rendering method working in linear colorspace).

**Comment by karpov-kir** [comment]
@Calinou, thank you! I cannot confirm if Compatibility rendering method fixes the problem since once I switch the mode to Compatibility the engine does not start anymore and crashes.

Regarding the issue, you've linked. I've also tried to use "HDR 2D" like mentioned in the issue but in Mobile rendering method. The original problem still persists:

<details>
<summary>Mobile rendering without "HDR 2D":</summary>

<img width="1079" alt="image" src="https://github.com/godotengine/godot/assets/85180621/d0791745-929f-4436-80e6-75f497e8f8d4">
</details>

<details>
<summary>Mobile rendering with "2D HDR":</summary>

<img width="1110" alt="image" src="https://github.com/godotengine/godot/assets/85180621/6ad3af4a-637e-43d7-bb35-962a9a87b64d">
</details>

<details>
<summary>Forward+ rendering without "2D HDR":</summary>

<img width="1067" alt="image" src="https://github.com/godotengine/godot/assets/85180621/99560853-8814-4f8f-933e-ca5ca5957f56">
</details>

The current issue has been consolidated to the other issue and closed, but it seems like the problem is different as far as I understand, because the solution from the other issue does not apply to the current one.

**Comment by Ivorforce** [comment]
In case that's any help, I can confirm with the mobile renderer I also get bands even with 2D hdr and debanding enabled.

forward+:
![SCR-20240208-thaw](https://github.com/godotengine/godot/assets/2308167/fb234918-3b5e-460c-ad84-0bbe48a0bc45)

mobile:
![SCR-20240208-tgvx](https://github.com/godotengine/godot/assets/2308167/69ba34ad-f505-49ac-bb5e-e6ff863b51a8)
