### ISSUE TITLE
Can't open filters in non-exclusive FileDialog

### ISSUE THREAD

**Issue by L4Vo5** [godotengine/godot#79052]
### Godot version

v4.1.rc3.official [cdd2313ba]

### System information

Godot v4.1.rc3 - Windows 10.0.19045 - Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 Threads)

### Issue description

Trying to open the filters (file types) menu in a non-exclusive FileDialog makes it automatically close and brings up the following error in the console/debugger:
```
ERROR: Condition "!windows.has(p_window)" is true. Returning: Rect2i()
   at: window_get_popup_safe_rect (platform/windows/display_server_windows.cpp:2426)
```
This seems to have been broken somewhere between 4.1 beta 2 and beta 3.

### Steps to reproduce

- Create a FileDialog
- Untick the "Exclusive" box
- Make it visible / pop it up / etc
- Try opening the `All Files (*)` menu

### Minimal reproduction project

[dialog_test.zip](https://github.com/godotengine/godot/files/11955537/dialog_test.zip)

**Comment by Sauermann** [comment]
For future reference, please also include the `godot.project`-file in the MRP. The `.tscn`-is usually not enough, because it lacks project-specific information.

When testing this with embedded windows enabled, I can confirm the problem. (#78476 addresses part of this problem, but I doubt, that it is enough to solve it)
When testing this with embedded windows disabled, the FileDialog simply closes after clicking on `All Files (*)`.

**Comment by L4Vo5** [comment]
> For future reference, please also include the `godot.project`-file in the MRP. The `.tscn`-file is usually not enough, because it lacks project-specific information.
Oh, I tested it on a blank project, so I didn't think that file would matter.

Thanks for the workaround!
