### ISSUE TITLE
Exporting nullable Node in C# does not show the node selector inspector

### ISSUE THREAD

**Issue by Fabien2S** [godotengine/godot#79071]
### Godot version

v4.1.rc3.mono.official [cdd2313ba]

### System information

Godot v4.1.rc3.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3179) - 12th Gen Intel(R) Core(TM) i5-12600KF (16 Threads)

### Issue description

When exporting a nullable Node field (`Node?` with [Nullable reference types](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references) enabled), the inspector does not show the node selector.

- Exporting Node-derived classes such as `Node3D?` works as intended.
- Removing the `?` works as intended.
- **ONLY** `Node?` causes the bug afaik

The bug is probably tied to the source generator, as the `PropertyHint` changes in the `GetGodotPropertyList` method based on the type:
- `Node?` : `properties.Add(new([...], hint: (global::Godot.PropertyHint)0, [...]));`
- `Node` : `properties.Add(new([...], hint: (global::Godot.PropertyHint)34, [...]));`
- `Node3D?` : `properties.Add(new([...], hint: (global::Godot.PropertyHint)34, [...]));`

![image](https://github.com/godotengine/godot/assets/18100602/c94d25eb-2e31-4e97-99ed-1a6f9f8780b9)
![image](https://github.com/godotengine/godot/assets/18100602/5348a6af-5b75-4c62-a205-5f51a2e0e30d)

### Steps to reproduce

1. Create a C# script and assign it to a Node
2. Build the project
3. Notice the node selector inspector not available

### Minimal reproduction project

Add the following script
```csharp
public partial class TestScript : Node
{
    [Export] private Node? _node
}
 ```

**Comment by AThousandShips** [comment]
I'm not sure nullable like this is supported

CC @raulsntos

**Comment by Fabien2S** [comment]
I think this is causes by [this](https://github.com/godotengine/godot/blob/d28f9afdc63714cffa0df2fb5e749bf1bc6666ac/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptPropertiesGenerator.cs#L556) if statement.
I cannot test it, but I think [this](https://github.com/godotengine/godot/blob/d28f9afdc63714cffa0df2fb5e749bf1bc6666ac/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ExtensionMethods.cs#L40C24-L40C24) exact statement maybe the culprite as `symbol.ToString()` may includes the nullability in the final string

**Comment by raulsntos** [comment]
> I'm not sure nullable like this is supported

A nullable reference type in C# is the same type, it's just used for null flow analysis. Therefore, the type should be exported the same way in the inspector. Nullable value types are indeed not supported, since the `System.Nullable` type can't be marshalled as a `Variant`, Godot struct types can't be null in Core either[^1].

> I think this is causes by [this](https://github.com/godotengine/godot/blob/d28f9afdc63714cffa0df2fb5e749bf1bc6666ac/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptPropertiesGenerator.cs#L556) if statement.
I cannot test it, but I think [this](https://github.com/godotengine/godot/blob/d28f9afdc63714cffa0df2fb5e749bf1bc6666ac/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ExtensionMethods.cs#L40) exact statement may be the culprite as `symbol.ToString()` may includes the nullability in the final string

You are correct, comparing symbols using the string representation is usually not a good idea unless we are very explicit about it.

[^1]: This may change in the future, see https://github.com/godotengine/godot/pull/76843.

**Comment by Zireael07** [comment]
Probably worth documenting somewhere in the C# support docs page?
