### ISSUE TITLE
[4.1] SubViewport, InputEvent Pressed and Area3D

### ISSUE THREAD

**Issue by kevinloustau** [godotengine/godot#79128]
### Godot version

v4.1.stable.official [970459615]

### System information

Windows 11

### Issue description

Hi,

After updating my project from godot 4.0.3 to 4.1, I noticed the SubViewport **blocks** the Input Events _**event pressed**_ on my Area3D. 

I made a small Godot project to test the issue with:
- two cubes rotating when we interact with their Area3D with the signal **_input_event_**. 
- one is in front of the camera
- the other is from the SubViewport, 

if the SubViewport is visible, only the content in the viewport receives the **event pressed**.
Important to note the _**mouse_entered**_ signal works well.

I made a video to demonstrate the issue (the godot project is avalaible below):
https://drive.google.com/file/d/1gBgL_zsX0A8Y4mFQ0AwpIv0NDygISj_k/view?usp=sharing

### Steps to reproduce

- Create a 3D scene, insert a mesh with an Area3D, 
- Create a SubViewport and place another mesh using Area3D 
- For the two Area3D, connect the signal input_event to a script, and get feedback on the InputEventMouseButton and  event.pressed

Area3D code: 
```python
func _on_input_event(camera, event, position, normal, shape_idx):
	if event is InputEventMouseButton:
		if event.pressed:
			self.rotate(Vector3.UP,deg_to_rad(45));

func _on_mouse_entered():
	print("Mouse enter on: ", self.name)
```

### Minimal reproduction project

[SubViewportAndMouseArea.zip](https://github.com/godotengine/godot/files/11972134/SubViewportAndMouseArea.zip)

**Comment by Sauermann** [comment]
> I noticed the SubViewport blocks the Input Events event pressed

It is more precise, that the `SubViewportContainer` blocks the Input Events. Mouse clicks on `Control`-Nodes always accept the event, when their mouse-filter is set to `PASS`. So it is expected, that `SubViewportContainer` as a `Control`-Node does the same. This was an inconsistency in the previous version, which lead to multiple problems and got fixed in #57894.

What you want to achieve is no longer possible with `SubViewportContainer` but you can use `Area2D` instead.
Here is a demo-project to showcase one possible way, how this can be done: [SubViewportAndMouseAreaWithChanges.zip](https://github.com/godotengine/godot/files/11975240/SubViewportAndMouseAreaWithChanges.zip)

**Comment by kevinloustau** [comment]
Thank you @Sauermann for the explanations, I implemented what you showcase in the demo-project, and it is working perfectly!

**Comment by Sauermann** [comment]
I am glad to hear that. Closing this issue accordingly.

**Comment by gitbill2143** [comment]
I don't like to download zips, could someone give an explanation of how to convert from subviewportcontainer to an Area2D?

**Comment by oldnote** [comment]
Enabling `SubViewport -> Physics -> physics_object_picking = true` fixed this issue for me.

[Kudos to this post](https://forum.godotengine.org/t/when-using-3d-nodes-as-child-of-subviewport-how-to-get-the-input-events/64426/5)
