### ISSUE TITLE
RefCounted does not automatically free if it has a cyclic reference

### ISSUE THREAD

**Issue by IvanIG3** [godotengine/godot#79154]
### Godot version

4.1

### System information

Windows 10

### Issue description

RefCounted objects does not free with a cyclic reference. For example, in this case:

- RefCounted A has a reference to RefCounted B.
- RefCounted B has a reference to RefCounted A.

These objects will not free automatically, no matter if there isn't any other object referencing them. And they cannot be manually freed.

### Steps to reproduce

Open the MRP an run it. Open the Debbugger -> Monitors menu. See how the "Objects" counter increase over time.

### Minimal reproduction project

[RefCountedTest.zip](https://github.com/godotengine/godot/files/11981648/RefCountedTest.zip)

**Comment by dalexeev** [comment]
This is intentional. Currently there is no garbage collector in GDScript, please check the links:

* [GDScript reference - Memory management](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#memory-management)
* [WeakRef](https://docs.godotengine.org/en/stable/classes/class_weakref.html)
