### ISSUE TITLE
ItemList - ability to set size on a specific icon in the item list - without affecting the size of the other icons

### ISSUE THREAD

**Issue by blurymind** [godotengine/godot#7924]
Ability to set individual size on item list icons. Right now when I import images with different sizes, itemlist creates a preview thumbnail for each that has a different size.

However after I implemented a zoom slider, I quickly realized that godot doesnt seem to have an ability to set a new size to each thumbnail in the itemlist that is relative to its old/original size when created.

The function ItemList.set_**fixed**_icon_size(icon_size) sets all thumbnails in the list to be the same size - as a result blurring horribly the more low res ones!

Using ItemList.set_icon_scale() has the same effect unfortunately - making all icons the same size.

Can we please get something like
**itemList.set_icon_size(item_index,icon_size)**
in godot?

Btw I am storing their original size in the metadata, so there is no need for get_icon_size.
Having this feature will also allow me to implement a function that resets the zoom size to the original size

**Comment by blurymind** [comment]
A function to resize icons relative to their initial size would also be able - that way it wont be required to loop through them.

I kind of expected set_icon_scale to do that. Can we consider it a bug - as it is just making all icons the same size, but it should be making them all relative to their original size when created?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
