### ISSUE TITLE
Window is not resizable with the borderless property enabled

### ISSUE THREAD

**Issue by Swarkin** [godotengine/godot#79329]
### Godot version

v4.1.stable.official

### System information

Windows 10

### Issue description

A window is not resizable with the borderless property enabled even though it should be.
I was trying to recreate a UI similar to the one in discord or steam, where there is no native windows window border and title bar. Those are however resizable normally.

### Steps to reproduce

1. Enable Borderless
2. Enable Resizable

### Minimal reproduction project

n/a

**Comment by felaugmar** [comment]
This behavior is expected.

If you want to easily simulate the behavior, anchor `Controls` at the Window's borders and corners and simulate the resizing yourself, with "click pressed", "mouse moved" and "click released".

**Comment by AThousandShips** [comment]
Indeed, borderless removes decoration which means you will have to provide resizing yourself, AFAICT

**Comment by Swarkin** [comment]
How do apps like steam do it then? They also remove window decorations

**Comment by AThousandShips** [comment]
They ass their own code I'm assuming

**Comment by Swarkin** [comment]
>Discord don't even bother with that, handles appears inside the window (looks good too).

I guess I could do it like that as well, thanks!

**Comment by Calinou** [comment]
Reopening, as this should be documented in the class reference.

**Comment by Schneidex69** [comment]
Hey,

I added it myself for Windows.
As a template of how it can work, I looked at the code from https://github.com/melak47/BorderlessWindow.

Attached is the zip with the display_server_windows .h / .cpp 
and a readme for the path.

You have to compile it yourself with the source code I used the stable 4.2.1

I have also rounded the corners of the window as otherwise it somehow always rounds the corners at the top and not at the bottom as soon as you resize the window.

[display_server_windows.zip](https://github.com/godotengine/godot/files/14017858/display_server_windows.zip)
