### ISSUE TITLE
Unexpected behavior on SpriteFrames animation FPS config

### ISSUE THREAD

**Issue by stephannv** [godotengine/godot#79445]
### Godot version

v4.1.stable.official.970459615

### System information

Vulkan API 1.2.231 - Forward Mobile - Using Vulkan Device #0: Apple - Apple M1 Max

### Issue description

When changing a specific animation (eg. animation_a) FPS if you click on another animation name (eg. animation_b), the new FPS value is assigned to both animations.

### Steps to reproduce

- Create two animations
- Select one animation
- Click on FPS input and change to a new value
- Click on another animation name
- Now both animation with have the same FPS value.

https://github.com/godotengine/godot/assets/3025661/89c406ac-a98b-4285-a586-831e9e9a5e13

### Minimal reproduction project

Doesn't need a specific project, just create a new project and a new AnimatedSprite2D and assign new sprite frames and follow above steps.

**Comment by Miguel0312** [comment]
I am trying to solve this bug and the the relevant class is SpriteFramesEditor defined in the file sprite_frames_editor_plugin.h.

The problem is due to a value_changed signal emitted with the old value of the anim_speed field.

For some reason this signal is emitted after the _updated_library function is executed but still with the old value, but I can't find out what is triggering this signal. If anyone has an idea why this is the case, I would appreciate an explanation.
