### ISSUE TITLE
StateMachine transition `Sync` not working when using looped animations

### ISSUE THREAD

**Issue by jordanlis** [godotengine/godot#79505]
### Godot version

v4.1.1.rc1.official [e709ad4d6]

### System information

windows 10

### Issue description

Synced transitions are not working correctly when using looped animations

### Steps to reproduce

1. Set up an animationplayer with 2 basic animations
2. Set up transitions in "sync" mode and uncheck "reset", loop the animation in the animation player
![image](https://github.com/godotengine/godot/assets/68544949/c4613880-ccbb-4484-8361-522073b6cb6e)
![image](https://github.com/godotengine/godot/assets/68544949/ba8844d8-8e26-4aec-a2e4-0bcf264cb01c)
4. Play animation 1 in the animation tree
5. While animation 1 is playing, play animation 2 in the animation

Currently : 
Transition are not synced
![looped_animation_not_syncing](https://github.com/godotengine/godot/assets/68544949/3f1045b8-b6c5-4ef5-8afb-adc7fb9fbf0e)

Expected : 
The transition are synced
You can test is by desactivating the looped animation --> it works correctly as expected
![animation_syncing_correclty](https://github.com/godotengine/godot/assets/68544949/c9a78985-8696-468e-bfcb-7a46d4e1b983)

### Minimal reproduction project

[test_project_synced_animation.zip](https://github.com/godotengine/godot/files/12061948/test_project_synced_animation.zip)

**Comment by AThousandShips** [comment]
* Duplicate/related: #79208

**Comment by TokageItLab** [comment]
This is a different problem from #79208. It is simply a bug.

I expect the main cause is that the loop time is not being retrieved correctly due to the PR #75759 for rework. However, even before the rework, the behavior seems vague for the saying "Sync".

I looked into it, and found that it only performs a seek on one frame at the moment of transition, and since it does not process the actual child Nodes outside of the transition. So it is not really a Sync, but just a "Seek on Transition".

There may be a way to make it seek correctly. However, rather than looking for a way to do so, it would be correct implementation of "Sync" to handle delta time for all possible transition nodes.

FYI, there is a workaround that is currently available that places a BlendTree in the StateMachine and connects some animations to a Sync-enabled NodeTransition to get the correct Sync behavior.

**Comment by wagnerfs** [comment]
I digged through the code to check this behavior and apparently, looped animations don't keep track of the animation's `pos_current` because internally, it just checks if the animation is a looping type, if it is it just forces `pos_current`to always be zero, I guess this was done to prevent transitioning to nodes at the end of a loop? It makes sense why the animation progress on looped animations are always static and maxed out.

I guess the problem is `_transition_to_next_recursive` is being used for both forced transitions (when you meet a condition do skip or hit play manually) and automatic "animation ended" transitions.

I'll probably give it a go patching it this week.
