### ISSUE TITLE
Using Fog Sun Scatter property on Windows 10 (QEMU) freezes system

### ISSUE THREAD

**Issue by juzikaster** [godotengine/godot#79509]
### Godot version

v4.1-stable (latest from website)

### System information

Windows 10 (QEMU) Godot_v4.1-stable_win64 Forward+ Vulkan

### Issue description

I am using Shadow Cloud for development which is done using QEMU virtualization, so it's may be a problem with hardware virtualization

I can't capture video due to OBS crash after unfreezing

After 3 minute frezze i got this errors in console.
![2023-07-15_20-17](https://github.com/godotengine/godot/assets/97132044/e0b452ae-59c9-4353-bdd2-1bdb8bb966f4)

### Steps to reproduce

1. Create WorldEnvironment
2. Enable fog
3. Set any value to Sun Scatter property

### Minimal reproduction project

Blank project with 3D scene and WorldEnvironment

**Comment by clayjohn** [comment]
Reminds me of https://github.com/godotengine/godot/issues/70015

We could have a similar issue creeping back in

**Comment by juzikaster** [comment]
So I did some digging, i used project from #70015 and it has Sun Scatter enabled and my system didn't hang but in WorldEnvironment Background set to Sky, i tried changing it to Color and Custom Color and my system froze. So it seems like Backgroud Color/Custom Color may be issue here. I tried changing it to Sky in my project and nothing happend.

**Comment by clayjohn** [comment]
There is a good chance the issue is in our ``setup_sky()`` function which is responsible for passing the DirectionalLight3D information to the shader. 


When not using a sky resource, we sometimes have to do a sky background pass to draw the fog. Doing so relies on the DirectionalLight3D info being sent to the shader. However, setup sky, hides most settings behind this condition:
https://github.com/godotengine/godot/blob/b8ed596769d2114797015833ce86f86ee872ecfa/servers/rendering/renderer_rd/environment/sky.cpp#L1035

Which means the lights only get added if there is an actual sky to use. 

The fix will be to remove this section of code:
https://github.com/godotengine/godot/blob/b8ed596769d2114797015833ce86f86ee872ecfa/servers/rendering/renderer_rd/environment/sky.cpp#L1089-L1185

And put it behind another check like ``if (sky || render_fog)``

**Comment by ParsleighScumble** [comment]
I can reproduce this on Ubuntu, so I'll go ahead and take a shot at fixing it.

**Comment by Ybaedbaenn** [comment]
https://github.com/godotengine/godot/pull/79795

**Comment by ParsleighScumble** [comment]
#79812 is the fix I came up with. The other PR seems like it won't compile.

**Comment by AThousandShips** [comment]
It will compile, it just has formatting errors, please look at the checks before assuming it doesn't work

**Comment by ParsleighScumble** [comment]
OK. I'll keep it in mind in the future.

**Comment by clayjohn** [comment]
> In the future please discuss things before opening an alternative, at minimum to save yourself needless work
> 
> In this case the other PR seems to not be the solution, but we prefer dialog and communication when approaching issues and solutions

For reference, ParsleighScumble actually commented first to say that they would work on this issue. So in this case it was totally fine for them to open the PR

**Comment by ParsleighScumble** [comment]
Please use she/her for me.

One thing - I saw affect_sky fog property doesn't do anything to the clear color in GLES3. Should I fix that before we merge this?

**Comment by Calinou** [comment]
> One thing - I saw affect_sky fog property doesn't do anything to the clear color in GLES3. Should I fix that before we merge this?

Yes, I believe the clear color should be treated as a "sky" for the purposes of **Fog Sky Affect**.
