### ISSUE TITLE
Callables of static methods are not valid if accessed via the class's name

### ISSUE THREAD

**Issue by jtnicholl** [godotengine/godot#79521]
### Godot version

v4.1.stable.official [970459615], v4.1.1.rc1.official [e709ad4d6]

### System information

Ubuntu 23.04

### Issue description

4.1 introduced support for using static methods as callables. However, if the callable is accessed via the class's name, it is considered invalid. This makes using static methods from other classes as callables very difficult.

### Steps to reproduce

```gdscript
class_name Test extends Node

static func static_func() -> void:
	pass

func _ready() -> void:
	print(Test.static_func.is_valid()) # prints false
	print(static_func.is_valid()) # prints true
```

### Minimal reproduction project

[ClassNameCallables.zip](https://github.com/godotengine/godot/files/12062908/ClassNameCallables.zip)

**Comment by dalexeev** [comment]
```gdscript
class_name Test extends Node

static func static_func() -> String:
    return "static_func()"

func test_callable(c: Callable) -> void:
    print("object=%-32s is_standard=%-5s is_valid=%-5s result=%s" % [
            c.get_object(), c.is_standard(), c.is_valid(), c.call()])

func _ready() -> void:
    test_callable(Test.static_func)
    test_callable(Test.new().static_func)
    test_callable(static_func)
```

```
object=<GDScript#-9223372010329996131>  is_standard=true  is_valid=false result=static_func()
object=<Node#26843546782>               is_standard=true  is_valid=true  result=static_func()
object=Node:<Node#26776437914>          is_standard=true  is_valid=true  result=static_func()
```

In the case of a static method call on a class, the base object is the script. The problem is here:

https://github.com/godotengine/godot/blob/a7583881af5477cd73110cc859fecf7ceaf39bd7/core/variant/callable.cpp#L124-L130

https://github.com/godotengine/godot/blob/a7583881af5477cd73110cc859fecf7ceaf39bd7/core/object/object.cpp#L631-L643

These methods cannot be overridden:

https://github.com/godotengine/godot/blob/a7583881af5477cd73110cc859fecf7ceaf39bd7/core/object/object.h#L817-L818

I'm not sure if we should add the ability to override/customize the methods. We don't have `_get_method_list()` like `_get_property_list()`. This is a question for @godotengine/core. Probably the easiest way to solve this is to add a `CallableCustom` wrapper.
