### ISSUE TITLE
`RootStateMachine` does not calculate the remaining time until the transiton to `End` state actually occurs

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#79537]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) 

### Issue description

I found that, the fade out in one shot node is not working with a State Machine.
I made two node, one for animation node and one for state machine as below:

![圖片](https://github.com/godotengine/godot/assets/24987226/79f22547-e690-4675-9810-4abd1feb59d4)

And made two character scene as below:
![圖片](https://github.com/godotengine/godot/assets/24987226/395d7e38-e7ba-4c88-88f3-f5e7332ebe1e)

The left one use pure animation node, while the right one is using state machine node.

You can see when blend out, they play different behaviour

![圖片](https://github.com/godotengine/godot/assets/24987226/5f732a53-7d7c-4bb0-a381-6224fc26ef4a)
The above is the internal of the state machine

I have attached a minimal reproduction project.
When you hit play, you can press "z" key to see how the animation is blending out for the two nodes.

The bug is, there is no blending out when connecting state machine with one shot, even I have set blend out time in one shot node.

Thanks

### Steps to reproduce

Open the minimal project, hit play, press z key.

The two character using the same anim tree, except one connecting a animation node with one shot node;
the another one connecting a state machine node with the one shot node.

It may related to this issue: #66495 

### Minimal reproduction project

[SM_Blending_Test_upload.zip](https://github.com/godotengine/godot/files/12063665/SM_Blending_Test_upload.zip)

**Comment by TokageItLab** [comment]
Setting a fade to EndTransiton in the StateMachine will process fadeing correctly.

This behavior depends on the fact that the remaining time in the StateMachine is not "determined" until the transition to EndState is initiated. If the transition to EndState is branching, it cannot be determined if the StateMachine is really finished.

Alternatively, the fade can be done by setting the StateMachine type to Nested and disconnecting to the EndState. This is because NestedStateMachine considers a dead end to be an end. However, in this case, the transition to StartState is not performed.

In this case, there are two possible improvements:

- Add an option to RootStateMachine to consider a dead end as an end.
- Calculate the remaining time if there is only one connection to the EndState.

The latter is probably preferred for consistency of RootStateMachine.
