### ISSUE TITLE
TileMap doesn't update in the editor when self_modulate is changed

### ISSUE THREAD

**Issue by Hinsbart** [godotengine/godot#7956]
**Godot version:**
master  (532f6d4)

**Issue description:**
The editor doesn't re-draw `TileMap`s when the `self_modulate` property is changed in the inspector.

**Comment by bojidar-bg** [comment]
I'm not sure if modifying `self_modulate` or `modulate` should call `update` on the affected nodes, since it would make them a few orders of magnitude slower.

Maybe we can have some internal `VisualServer::canvas_item_inherit_modulate()`, which we would apply on the children items of the TileMap, instead of having to reinvent the wheel there?

**Comment by reduz** [comment]
This is not a bug. Tilemap creates sub-canvas items so the only way to do changes to it is via modulate.

**Comment by bojidar-bg** [comment]
Note: this issue is now tracked in #31413. Originally, it was mentioned in #7954, but never linked directly.
