### ISSUE TITLE
Can't modify any nodes when using await or a seperate thread C#

### ISSUE THREAD

**Issue by ZachAR3** [godotengine/godot#79671]
### Godot version

4.1.1.stable.mono

### System information
Arch linux: Zen Kernel 6.3 Ryzen 5900x Nvidia RTX 2080TI 11GB (proprietary drivers)

### Issue description

When updating from 4.0 to 4.1 my entire C# project is broken due to thread safety issues. Anything that calls a thread after awaiting or inside of 
```
await Task.Run(async () =>
			{
                         // Do stuff
                         });
```
Gives me errors about "This function in thise node ,,,, can only be accessed from the main thread". It seems GDScript can use `Thread.set_thread_safety_checks_enabled(false)` as a work around for these bogus checks, but I can't find an equivalent in C# other than calling everything as deferred which is ridiculous and a pain since no IDE's can autocomplete or properly change that if a variable name is modified as it is a string. Highly related to this issue, but concerened about the C# elements #78149 

### Steps to reproduce

Create a C# script and use await, then attempt to modify a nodes property.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
AFAIK this is working as intended, the scene APIs are not thread-safe, see the [_Thread-safe APIs_](https://docs.godotengine.org/en/4.1/tutorials/performance/thread_safe_apis.html) documentation page.
- These thread guards were added in https://github.com/godotengine/godot/pull/75901.

>  It seems GDScript can use `Thread.set_thread_safety_checks_enabled(false)` as a work around for these bogus checks, but I can't find an equivalent in C#

Most of the C# API is generated from ClassDB, so if the `Thread` type has a `set_thread_safety_checks_enabled` method then it should be available in C# too. Look for `GodotThread.SetThreadSafetyChecksEnabled`.

> [...] other than calling everything as deferred which is ridiculous and a pain since no IDE's can autocomplete or properly change that if a variable name is modified as it is a string.

You don't have to use `GodotObject.CallDeferred` (but if you are, consider using the `MethodName` static class which contains a cached `StringName` to avoid creating it from a `string` every time), you can also use `Callable.CallDeferred` so you can use a C# lambda:

```csharp
Callable.From(() =>
{
	// This will be executed in the main thread.
}).CallDeferred();
```

You can also await the next process frame and that should continue in the main thread because of Godot's synchronization context:

```csharp
await ToSignal(GetTree(), SceneTree.SignalName.ProcessFrame);
```

**Comment by ZachAR3** [comment]
> 

Strange, well I appreciate the various options you have layed out! I will close the issue since you said it is designed this way.
