### ISSUE TITLE
2d, set_rot(PI), PI not equal get_rot()

### ISSUE THREAD

**Issue by allkhor** [godotengine/godot#7971]
**Operating system or device - Godot version:**
Xubuntu 16.04.2 LTS x86_64 , Godot version: 2.1.2 cc265d5 

**Issue description:**

Example:
```
func _ready():
	set_rot(PI)
	print(PI == get_rot())
	print("%.15f" % PI)
	print("%.15f" % get_rot())

Output:
False 
3.141592653590000
3.141592741013000
```
I expect to see equality, somewhere there is a loss of precision.

**Comment by akien-mga** [comment]
That's not a bug, see https://en.wikipedia.org/wiki/Single-precision_floating-point_format and #7913.

**Comment by akien-mga** [comment]
Though I'm told `set_rot(PI); print(PI == get_rot())` should maybe work, reopening for discussion.

**Comment by karroffel** [comment]
`Variant` stores all floating point numbers as `double`.

`PI` is defined as a double. If you were to write

```GDscript
var x = PI
print(x == PI)
```
It should print "true".

That's because PI is a double and x represents a Variant. No information should be lost.

Unless someone performs arithmetic operations on the value, the representation in memory won't change and comparison will always succeed.

Now here's the tricky part.

The signatures are `void set_rot(float)` and `float get_rot()`. 

If you set the rotation to a value with double precision, only single precision will be used because these functions can't operate on double values.

That effectively means that you're not passing `PI` to those functions but *the nearest float representation*. You will also receive the *nearest float representation* as this is what you set it to.

This is not a problem with faulty math operations or storage errors: this is just the singe precision nature of most of the methods in Godot class API.

**Comment by allkhor** [comment]
@karroffel, Thank you for the detailed answer.

**Comment by bojidar-bg** [comment]
As a side note, comparing any kind of floating-point numbers with `==` is bad in general, since it leads to oddities like this one more often than not. The usual way of doing it is:
```
const EPS = 0.0001 # Or even less, if you want...
print(abs(get_rot() - PI) <= EPS)
```

Maybe we should open another issue for supporting a helper like `float::approximately_equals(x, epsilon)`?

**Comment by karroffel** [comment]
@bojidar-bg this is usually called "delta compare". It would be nice to have this. Make just make it a builtin function in GDScript? Would be rather simple

**Comment by akien-mga** [comment]
I tend to think that the explicit code is simple enough and more explicit (as well as something every programmer should be or become familiar with).

If people consider delta compare too tedious, that's a good incentive for them.to learn how to use integers as much as possible when doing math operations in their scripts.

Just my opinion though, if many think a helper would be a good addition, why not.
