### ISSUE TITLE
"No loader found for resource `.po`" when editing PO file

### ISSUE THREAD

**Issue by ghost** [godotengine/godot#79728]
### Godot version

v4.0.3.stable.official [5222a99f5]

### System information

Windows 10

### Issue description

When `.po` files are edited, the following error is printed to the output when returning to the editor window.

**No loader found for resource: res:/path_to.po.**

### Steps to reproduce

Issue description.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This is a known issue when editing files that are valid resources in the script editor. I'm not sure how it could be avoided.

**Comment by felaugmar** [comment]
I've used an external editor (not the **built-in script editor**).

**Comment by LunaCapra** [comment]
I encountered this issue but surprisingly with `.mo` files, rather than `.po` files.
I'm editing and generating these files with [POEdit](https://poedit.net/).

This was tested in and still occurs in `v4.3.dev6.official [89850d553]`
The full error looks like this:
![image](https://github.com/godotengine/godot/assets/50772474/bd7cb586-62fe-4d42-b184-0f039785b779)

I'm also attaching a reproduction project to make it easier to test.
[no_loader.zip](https://github.com/godotengine/godot/files/15209438/no_loader.zip)
