### ISSUE TITLE
SubViewport rendered as ViewportTexture doesn't receive InputEvents

### ISSUE THREAD

**Issue by ascripter** [godotengine/godot#79827]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce 940MX (NVIDIA; 31.0.15.1654) - Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 Threads)

### Issue description

When projecting a SubViewport as a texture (i.e. tested with ViewportTexture for Sprite2D and Sprite3D), and the scene inside the SubViewport contains any Control elements, they are not accessible / don't receive any InputEvents.

Explicitly forcing them to get the focus via Control.grab_focus() seems to work, but then any input is just ignored. Tried it with and without SubViewport.handle_input_locally, as well with callback-scripts that reside in nodes inside and outside the SubViewport.

### Steps to reproduce

The attached project has two buttons, the "outer" is a child of the main node, while the "inner" is projected as a Sprite2D's texture. The inner button can't be pressed, no matter how I try it.

### Minimal reproduction project

[viewport_test.zip](https://github.com/godotengine/godot/files/12138874/viewport_test.zip)

**Comment by AThousandShips** [comment]
I'm not sure this is supposed to work, they should be in a `SubViewportContainer` to have access to this functionality AFAIK

**Comment by Sauermann** [comment]
You can find a rationale for the current behavior in https://github.com/godotengine/godot/issues/9950#issuecomment-318841555

So you have two options:

1. Use a `SubViewportContainer`, which automatically sends events to its child `SubViewports`.
2. Implement InputEvent-propagation based on your individual requirements from `Sprite2D`. (In the post above you find a link for how to do this in a 3D-application)

I would like to close this issue, since the current behavior is expected and also documented in https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html

**Comment by Sauermann** [comment]
If you need the functionality for 2D/3D in an automated way, you could give a thumbs-up to the proposal https://github.com/godotengine/godot-proposals/issues/6524
