### ISSUE TITLE
SubViewport consumes mouse Input when physics_object_picking is true in 4.1 but not 4.0

### ISSUE THREAD

**Issue by martimmatias** [godotengine/godot#79897]
### Godot version

4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.3667) - 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz (16 Threads)

### Issue description

Starting in Godot 4.1, a SubViewport with physics_object_picking set to true (and handle_input_locally set to false) will mark mouse events (clicks and motion) as handled even if there are no nodes being picked or any nodes to pick from.

In my use case, I have a node (sibling of SubViewportContainer) with a script attached which defines the _unhandled_input function. In Godot 4.0, the event is passed to this node. In Godot 4.1 and 4.1.1 however, the event is handled by the viewport (or its container?).

### Steps to reproduce

1. Create a scene with a similar structure to this:
![image](https://github.com/godotengine/godot/assets/4275520/41d9161e-8d29-443e-8304-6eb13534cd94)

2. On the SubViewport, set physics_object_picking set to true and handle_input_locally set to false.
3. Resize the subviewport container (not to the full size of the screen). Feel free to add a ColorRect or some other node outside the viewport to tell where the viewport starts and ends.
4. Attach this script to a sibling of SubViewportContainer:
```gdscript
extends Node

func _unhandled_input(event):
	print(event)
```

5. Try this in Godot 4.0 and 4.1. The print instruction is never reached in Godot 4.1 (and 4.1.1).

### Minimal reproduction project

[HandleInputLocallyTest.zip](https://github.com/godotengine/godot/files/12164530/HandleInputLocallyTest.zip)

**Comment by Sauermann** [comment]
Thank you for your report. This change was introduced as a bugfix in #77595, so what you want to achieve now has to be done in a different way.

If you want to access *_unhandled_input* in the Node, then you have multiple options. Here are two ways of how to do that:
1. Move `Node` inside the SubViewport, so that `Node._unhandled_input` gets called before Physics Picking
2. Change SubViewportContainer to an `Area2D` with a `CollisionShape2D`

For the second case, here is a demo-project of how to do that: [HandleInputLocallyChanged.zip](https://github.com/godotengine/godot/files/12165276/HandleInputLocallyChanged.zip).
