### ISSUE TITLE
Create Varying window crash

### ISSUE THREAD

**Issue by NotN33d3d** [godotengine/godot#79906]
### Godot version

4.1.stable

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 SUPER (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 2600 Six-Core Processor (12 Threads)

### Issue description

Whenever I press the button that by default says "float" on the create varying window in the visual shader editor, the window immediately closes thus not allowing me to create a varying.

### Steps to reproduce

Open the visual shader editor, select Manage Varyings. Create New Varying. Then select the button that reads Float.

### Minimal reproduction project

Can be reproduced within 30 seconds on my machine. 3D Plane -> Material -> Visual Shader Editor -> Manage Varyings

**Comment by bitsawer** [comment]
Does it actually crash Godot? What is the error message? I can repro the popup dialog issue, but not the crash.

The dialog issue seems to be in 4.1 stable release, but this seems fixed in current master at 202e4b2c1e7f8b25738b93d0e4d5066453d3edf3. However, in current master if single window mode is enabled, every time you open any popup including "Editor Settings", "Project Settings" or the "Add Varying" or "Remove Varying" popup dialogs, an error is printed in the output:

`scene\main\viewport.cpp:3499 - Condition "index == -1" is true. Returning: Rect2i()`

Still, despite the error message, all functionality seems to work and nothing seems to be wrong otherwise. This seems to be very similar to https://github.com/godotengine/godot/issues/76480#issuecomment-1632990267, including different error messages in 4.1 and current master.

cc @Sauermann, in case you have some insight.
