### ISSUE TITLE
Collisions on 3d model are frustrating and broken

### ISSUE THREAD

**Issue by ElGatton** [godotengine/godot#80014]
### Godot version

4.1.1

### System information

windows 11

### Issue description

Creating collisions for a fps, I wasted hours creating, recreating and creating collisions again for the character to then see everything blow up for ANY reason. collision shapes bug by losing their structure. The animation player seems to have some merit in the bug. It's really frustrating and makes it IMPOSSIBLE to use Godot 4.1.1. unless you want to waste hours working on practically nothing.

### Steps to reproduce

Take a 3d model with at least 5/6 animations. create a physical skeleton and put 3d collision shapes on it. Now use the animation tree and animation player and in no time, totally random your collisions will be scattered to the four corners of the planet.
![start](https://github.com/godotengine/godot/assets/106838359/bd75f51b-d3f8-4c6d-8a43-d7998af9d7c8)
![2](https://github.com/godotengine/godot/assets/106838359/2f4da350-8467-4e48-8ecf-07cacb7c15ad)
![3](https://github.com/godotengine/godot/assets/106838359/9be276c5-4f00-4402-85c7-7e6846
![4](https://github.com/godotengine/godot/assets/106838359/b1992f57-ad6b-434e-9595-32a8963b9f68)
d5f885)

FINAL RESULT 
![5](https://github.com/godotengine/godot/assets/106838359/6c911218-6f66-4b91-967d-1c94fce1d555)

### Minimal reproduction project

same as above, take a model, make a physical 3d skeleton and attack the collisions. Now add an anim player with 4/5 animations and finally an anim tree with an animation node state machine

**Comment by AThousandShips** [comment]
Please provide an MRP, these steps are *not* simple:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.
