### ISSUE TITLE
Strange behavior of omnilights Mobile Renderer Godot 4.1, sometimes they light up sometimes they don't.

### ISSUE THREAD

**Issue by CHIESOFTWARE** [godotengine/godot#80133]
### Godot version

4,1 stable 

### System information

Operating System: Ubuntu Studio 22.04 KDE Plasma Version: 5.24.7 KDE Frameworks Version: 5.92.0 Qt Version: 5.15.3 Kernel Version: 5.15.0-78-lowlatency (64-bit) Graphics Platform: X11 Processors: 12 × Intel® Core™ i5-10500H CPU @ 2.50GHz Memory: 15.4 GiB of RAM Graphics Processor: Mesa Intel® UHD Graphics  VULKAN 1.3.204 Envidia Gforce GTX 1650 max-Q

### Issue description

Lights are simply placed with or without distance fade using the mobile renderer and sometimes they illuminate the area correctly and sometimes they do not illuminate anything. You also see behavior where they appear to light up and then flicker or light up the area when the camera is very close without illuminating darker colored surfaces very much.

Using forward plus everything works normal.

### Steps to reproduce

Change rendering to mobile
Place several lights as omnilights or spotlights
Use remote fade to see the problem more easily
Walk away and approach the lights until you see the error

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/12233184/test.zip)

**Comment by clayjohn** [comment]
I don't think this is a bug. To me this looks like you are just bumping up against the Mobile renderers 8 lights per surface limitation.

The Mobile renderer can only display up to 8 lights per mesh. Since your ground mesh is one giant mesh, you are only able to see the nearest 8 lights at a time. So in certain camera angles you see lights flicker in and out. This is expected behaviour. 

Take a look at the docs on lights and shadows, in particular the section on light limits https://docs.godotengine.org/en/latest/tutorials/3d/lights_and_shadows.html#light-number-limits

That being said, it is a little unclear if there is more to your issue. The MRP is super hard to reproduce any issue at all. It might be helpful for you to read the above doc, then try to scale down your MRP to see if there is a bug here that I am not seeing. 

As a rule of thumb, an MRP is a test case where you can reliably reproduce the bug just by running the project.

**Comment by CHIESOFTWARE** [comment]
I have been testing and I think you are right, I will keep testing by changing some big objects for some objects made with smaller parts.
