### ISSUE TITLE
`LayoutMode` not exported in Editor

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#80209]
### Godot version

v4.1.stable.official [970459615]

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3667) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

The `enum` for `layout_mode` is not exported into the Editor. For example, if I have a `Label`:
```
label.layout_mode = LAYOUT_MODE_POSITION
```

I get the error:
```
Identifier "LAYOUT_MODE_POSITION" not declared in the current scope.
```

That `enum` is defined [here](https://github.com/godotengine/godot/blob/master/scene/gui/control.h#L130).

Note also that you can get the following errors trying to access it:
```
Identifier "LayoutMode" not declared in the current scope.
```

And:
```
Cannot find member "LayoutMode" in base "Control".
```

### Steps to reproduce

See above

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
That property is internal, not for use in scripting

**Comment by AThousandShips** [comment]
I'm not sure, but this is specifically for use in the editor, probably with a combination of the different methods in `Control` like `set_*_preset`

**Comment by acgc99** [comment]
You can set the anchor preset via `set_anchors_preset` but it is ignored if you don't set the `layout_mode` to `LAYOUT_MODE_ANCHORS`.

You can do some testing with:
```
printt(a.layout_mode, a.anchors_preset)
a.set_anchors_preset(Control.PRESET_BOTTOM_LEFT)
printt(a.layout_mode, a.anchors_preset)
```
where `a` is a `Control` node. If you set via the Inspector its `layout_mode` to `LAYOUT_MODE_ANCHORS`, `set_anchor_preset` works, but otherwise not. Therefore I think we need a way to set the `layout_mode` via code.

**Comment by dalexeev** [comment]
> Therefore, how can I set the layout mode of a node from a script?

`layout_mode` is a "fake" property, it's evaluated from other properties and the control's parent. This property was added mostly to make it easier for users to understand the system of anchors, containers, and size flags. See #69860.

**Comment by acgc99** [comment]
I still think that my idea would simplify code, for example, when creating a custom complex node for a plugin. The children nodes have to be instantiated via code and therefore their `layout_mode` being available from code would simplify things.

I though to use the `layout_mode` first on the plugin I'm doing now, but I ended up using a `HBoxContainer`. Containers have some advantages, but it also requested me to use `custom_minimum_size` for children nodes, creating some bugs when resizing from the editor viewport (can't shrink nodes once they have been stretched, using `size` would solve this, but it cannot be done in a container).

**Comment by YuriSizov** [comment]
There is no "layout mode" as a state of a node. It's an editor-only helper, as mentioned above. There is no behavior associated with it other than editor-only logic that makes sure things are properly restricted in the UI.

So it should not and could not be used to control how node's properties are set.

> when creating a custom complex node for a plugin. The children nodes have to be instantiated via cod

That's not correct. You can instantiate custom scenes, configured in the editor, when adding UI to your plugin. You don't need to create anything in code.

**Comment by ckdarby** [comment]
@YuriSizov I might be mistake, but I feel like this is kind of is a stance of just forcing down the throat of the community to do it the way that Godot intends it to be used.

Let's say I am implementing a plugin that is used for tooltips. I'd like the user to be able to child a control node and in the editor easily see that the mouse_entered & mouse_exited are on top of the control based upon the size.

It would look something like this:
```
| TextureRect2
  -> TooltipPal
```

This functionality is very easy in the editor, just set layout mode as anchors and anchor to be full rect.

The option that sounds to be given from your advice, is to simply create a custom scene with the gdscript of the custom node type is added to the child. The issue is the user in the editor won't see this at all.

This leads us down the rabbit hole using @tool to basically hack this into the editor via resizing based upon the parent size() and such. This is really silly.

**Comment by AThousandShips** [comment]
This isn't an opinion, it's how it works, it's not a real property and doesn't work, you are free to open a proposal to change this, but it's not a bug, it's simply not something that works this way and it isn't designed to be used by scripts, and was intended to not be accessible to code like this, but it is due to an issue in the way properties are exposed, as already explained

Please be constructive and don't accuse people of things that aren't true, this isn't something "forced" on anyone

**Comment by ckdarby** [comment]
@AThousandShips I am removing my original comment as I don't feel safe continuing the discussion after describing the feeling of stance and then being accused of accusing others of things that weren't being said.

I will keep this in mind moving forward, and any modification of code behaviour, even just simply continuing a discussion about the existing, will be moved to proposals instead.

**Comment by AThousandShips** [comment]
Now you're accusing me of accusing you... Yes let's just move on
