### ISSUE TITLE
Bug with shader and color

### ISSUE THREAD

**Issue by smatiz** [godotengine/godot#80261]
### Godot version

4.1.1

### System information

Windows 11

### Issue description

**with this shader**
if(UV.x > 0.5)ALBEDO = vec3(0.2, 0.3, 0.8);
else ALBEDO = abs(colorEmpty.rgb );
**and this gdscript**
$MeshInstance3D.material_override.set_shader_parameter("colorEmpty", Color(0.2, 0.3, 0.8))
**I got 2 different colors**
![2023_08_04_16_55_34_](https://github.com/godotengine/godot/assets/6281415/4c48b4cb-f052-457c-8d68-a623415fd447)

### Steps to reproduce

**progress.gd :**

extends Node3D

func _ready():
$MeshInstance3D.material_override.set_shader_parameter("colorEmpty", Color(0.2, 0.3, 0.8))

**shader:**

shader_type spatial;

uniform vec4 colorEmpty;

void fragment()
{
if(UV.x > 0.5)ALBEDO = vec3(0.2, 0.3, 0.8);
else ALBEDO = abs(colorEmpty.rgb );

}

**scene**

[gd_scene load_steps=6 format=3 uid="uid://cc0umri7ybott"]

[ext_resource type="Script" path="res://Progress.gd" id="1_3kb6r"]
[ext_resource type="Shader" path="res://box_progress.gdshader" id="2_b0e74"]

[sub_resource type="ShaderMaterial" id="ShaderMaterial_erl4x"]
render_priority = 0
shader = ExtResource("2_b0e74")
shader_parameter/colorEmpty = null

[sub_resource type="QuadMesh" id="QuadMesh_t2los"]

[sub_resource type="Environment" id="Environment_83blf"]
background_mode = 1
ambient_light_source = 2
ambient_light_color = Color(1, 1, 1, 1)
reflected_light_source = 1

[node name="Node3D" type="Node3D"]
script = ExtResource("1_3kb6r")

[node name="MeshInstance3D" type="MeshInstance3D" parent="."]
material_override = SubResource("ShaderMaterial_erl4x")
mesh = SubResource("QuadMesh_t2los")

[node name="Camera3D" type="Camera3D" parent="."]
transform = Transform3D(1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1.16659)
environment = SubResource("Environment_83blf")
projection = 1
current = true

### Minimal reproduction project

[GODOT_TEST.zip](https://github.com/godotengine/godot/files/12262047/GODOT_TEST.zip)

**Comment by bitsawer** [comment]
Thanks for the report! This behavior is not a bug, but an intended color conversion. Depending on renderer (Vulkan, OpenGL) and config (2D, 3D) the colors can be in linear or SRGB color space. In this case `Color(0.2, 0.3, 0.8)` will go though color conversion when setting the uniform parameter. There are a few ways to change this, for example use Vector3 instead of Color:

`$MeshInstance3D.material_override.set_shader_parameter("colorEmpty", Vector3(0.2, 0.3, 0.8))`

It's not always a good idea to hardcode color values in shader code unless you know that you will always use linear or SRGB colors. You can also use OUTPUT_IS_SRGB shader constant if needed. You can also try to use `source_color` annotation, see https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/shading_language.html
