### ISSUE TITLE
Getting selected nodes in signal("selection_changed")-fired function results in endless loop

### ISSUE THREAD

**Issue by CharlesWoodhill** [godotengine/godot#8026]
**Operating system or device - Godot version:**
win - current master

Issue:
Calling get_selected_node_list in "selection_changed"-signalled function results in endless loop.

as seen below get_selected_node_list calls update(), 
but update fires selection_changed,
which again fires update();

EDIT:
this fixed it for me, but i dont have tested it much:

```
void EditorSelection::update() {

	_update_nl();

	if (!changed)
		return;
        //////////////////////////////////////////////
	changed = false; 
	emit_signal("selection_changed");
        //////////////////////////////////////////////
}
```
original source:
```
void EditorSelection::update() {

	_update_nl();

	if (!changed)
		return;
	emit_signal("selection_changed");
	changed = false;
}

List<Node *> &EditorSelection::get_selected_node_list() {

	if (changed)
		update();
	else
		_update_nl();
	return selected_node_list;
}
```

**Comment by akien-mga** [comment]
> Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

As there was no update since the previous post, we close this issue.

If it is still relevant in the way it was described and discussed above, please comment to ask for it to be reevaluated. If it is only partly relevant, or if the original issue has changed, it would be better to open a new issue (potentially referring to this one) focused on the current state.
