### ISSUE TITLE
Can't run any scenes in project. Error with _populate_class_members()

### ISSUE THREAD

**Issue by DemonBismuth** [godotengine/godot#80389]
### Godot version

4.0rc6

### System information

Windows 10

### Issue description

I keep getting this error when I try to run the project in the main or any scene.

> E 0:00:00:0817   _populate_class_members: Condition "!base->is_valid() && !base->reloading" is true. Returning: ERR_BUG
  <C++ Source>   modules/gdscript/gdscript_compiler.cpp:2318 @ _populate_class_members()

My user logs all look the same too. They're only these lines

> Godot Engine v4.0.rc6.official.0cd148313 - https://godotengine.org
Vulkan API 1.3.236 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1060 6GB
USER ERROR: Condition "!base->is_valid() && !base->reloading" is true. Returning: ERR_BUG
   at: _populate_class_members (modules/gdscript/gdscript_compiler.cpp:2318)

I found a similar issue mentioned below. However, it has not helped me solve my issue. It's possible this is a cyclic reference error, but I cannot seem to find it. I've been removing explicit typing throughout and have not seen any noticeable difference, and the error message itself is unhelpful in locating the cause of this.
#69213 

quick edit: forgot to mention, I also tried deleting the .godot folder and re-importing everything by the suggestion of a friend, to no avail.

### Steps to reproduce

Project under NDA and too large to upload.

### Minimal reproduction project

See above

**Comment by dalexeev** [comment]
> 4.0rc6

This is an unsupported version. Have you checked the current stable releases (4.0.4, 4.1.1)?

> Project under NDA and too large to upload.

In difficult cases and/or for large projects, you can try the following algorithm to isolate the problem and create an MRP:

Make a copy of the project and iteratively remove parts that are probably not relevant to the problem. Check after each iteration to see if the problem is still reproducible. If it remains, try removing something else. If it disappeared, go back to the previous step and try to remove something else. Keep doing this until the project is small enough or it's clear what's causing the problem.

Yes, this is a longer and more difficult way, but it is not always possible to find and fix a bug without the ability to reproduce it. I'm not asking you to use this algorithm right now, just a warning that sometimes an error message may not be enough to find the bug cause without an MRP and Steps to reproduce.

**Comment by DemonBismuth** [comment]
Feel embarrassed for making a whole post for this. Found a small separate file I forgot about, commented out its functions, and things worked again. Was able to find the culprit within that file
