### ISSUE TITLE
A way to save and load groups of visual script nodes

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8046]
When working with visual scripts there are two options, make all from scratch or copy-paste a group of nodes from another visual script (meaning that the script must be added and opened in the editor).

I was thinking that having templates could be useful for generic things like input handling or character movement and more complex but commonly used operations, some kind of "visual snippet".
These templates could work just like copy-paste, but copied/pasted to/from files instead.

Something like this may increase a lot the usability of visual scripting.

--------
I don't know if I was clear on the request but, just in case, the basic idea is:
- Save the selected Visual Script nodes to disk (like a copy operation).
- Load saved nodes from disk and add them to the current Visual Script function (like a paste operation)
--------

ps: if these templates/snippets could be added to a customizable section on the available nodes list, even better, but as files could be enough.

**Comment by fire** [comment]
I'll close https://github.com/godotengine/godot/issues/6072#issuecomment-513129273 in favour of this issue as the tracking bug.

> As mentioned in the gsoc status report we're working on group visual script node. This is the ability to save groups of visual script nodes as resources and then import as a node.

> https://godotengine.org/article/gsoc-2019-progress-report-1-part-1

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
