### ISSUE TITLE
Label has a gettable line_height property - what about RichTextLabel?

### ISSUE THREAD

**Issue by jackmakesthings** [godotengine/godot#8049]
**Operating system or device - Godot version:**
Godot 2.1 stable, but applies to the current master branch too.

**Issue description:**

Label has a convenient `line_height` property and `get_line_height` method; is there a specific reason RichTextLabel doesn't? I could see this being a little tricky since there's no guarantee every line will have the same height (ie, if the font is different or if an image is inserted, it might take up more vertical space), but it'd be nice if we could get either the height of a given line in the RTL, or the "default" line-height based on the RTL's normal-styled-text font options.

For context: I came across this while playing with the [Godot TIE addon](https://github.com/henriquelalves/GodotTIE), which adds a lot of cool functionality to a dialog-style interface. It uses labels for all its text; I wanted to try using RichTextLabels to gain access to multiple font styles, bbcode parsing, etc. But the addon uses `Label.get_line_height()`, so I was hoping to find an equivalent that works with RichTextLabel. Is this a reasonable request, or are there technical limitations?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
