### ISSUE TITLE
Multiple mouse cursors support

### ISSUE THREAD

**Issue by raymoo** [godotengine/godot#8052]
This is very low priority even for me as the issue-poster, but it could be cool I guess to support. This is not a duplicate of #8028 because in X11 multitouch events are separate from multiple cursors.

**Operating system or device - Godot version:**
i3 + X11 + Debian + systemd + GNU + Linux / Godot 2.1.2

**Issue description:**

I enabled two mouse cursors on my desktop and started messing with the buttons in the Godot editor, leaving a button stuck in the depressed state.

**Steps to reproduce:**
1) Attach two mice to the computer
2) Follow the directions in https://ao2.it/en/blog/2010/01/19/poor-mans-multi-touch-using-multiple-mice-xorg to enable multiple cursors (no need to remap buttons though)
2.5) Open the Godot editor to some project
3) Move the cursors so that one is over the "stop" button and one is not over any button
4) Click and hold the cursor that is over the button
5) Click and release the cursor that is not over the button
6) Release the cursor that is over the button

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
