### ISSUE TITLE
Call Func Track blocks transform Object when AnimationTreePlayer is playing in editor

### ISSUE THREAD

**Issue by RandomNumber4** [godotengine/godot#8053]
[I have created an example that shows this behavior.](https://github.com/godotengine/godot/files/849788/AnimationTreePlayer_lock_Object.zip)

When added to the animation test2 in example Call Func Track and AnimationTreePlayer is playing in editor transform player object is reset and blocked in game.
Call Func Track in root node blocks movement, body node blocks rotate.
If delete both track from test2 animation or stop playing AnimationTreePlayer in editor control is back in the game. In some cases stop playing AnimationTreePlayer in editor does not solve the problem.

In editor player object is blocked too when AnimationTreePlayer is playing.

I added to the example a cube that moves with keys WSAD, space jump and mouse rotate.
I hope that this example will help because otherwise I can not explain it.

**Comment by kubecz3k** [comment]
AnimationTreePlayer will be reworked for 3.0, would be good to test this when that happens.

**Comment by RandomNumber4** [comment]
I'm glad to hear it

**Comment by kubecz3k** [comment]
I'm in the process of revisiting old issues. Still happens in 3.0.2. 
In fact I independently came across this issue in my project couple days ago, and I opened new issue. I will close this one as a duplicate since I believe my description is a little better. Feel free to add your comment to https://github.com/godotengine/godot/issues/18084 if I missed some information.
