### ISSUE TITLE
Immersive mode no longer works on android, both the notification bar and the navigation bar are still visible.

### ISSUE THREAD

**Issue by overTheRocks** [godotengine/godot#80574]
___

***Bugsquad note:** This issue has been confirmed several times already. No need to confirm it further.*

___

### Godot version

v4.2.dev2.official [da81ca62a]

### System information

Windows 11 - Vulkan (Forward+)

### Issue description

Immersive mode seems to no longer works on android, both the notification bar and the navigation bar are still visible. The pinhole cutout is has also gained a black bar.

Tried creating a completely blank project and the problem still arises.

Godot 4.2 dev 2:
![Screenshot_20230813-015546](https://github.com/godotengine/godot/assets/34485270/450b8891-463a-429a-9d4f-5ee7166b8ecd)

Godot 4.1:
![Screenshot_20230813-015227](https://github.com/godotengine/godot/assets/34485270/aad6e35c-6c8a-4cb3-8b17-243facb335ad)

I am using a Pixel 7 with Android 13

### Steps to reproduce

Export to android

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
Can you reproduce this in [4.2.dev3](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-3/) and [4.2.dev1](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-1/)?

**Comment by overTheRocks** [comment]
> Can you reproduce this in [4.2.dev3](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-3/) and [4.2.dev1](https://godotengine.org/article/dev-snapshot-godot-4-2-dev-1/)?

Created two new projects and tried them with both 4.2.dev1 and 4.2.dev3 both create the same problem.

**Comment by MinikPLayer** [comment]
Bug still exists in 4.2.dev4. 
Replacing export templates with templates from 4.1 fixes the problem (but probably introduces more by itself, so shouldn't be a fix - just a clue)

**Comment by SmallKi** [comment]
Bug still exists in 4.2 dev5

**Comment by SmallKi** [comment]
It seems that reading command lines from '_cl_' file in 'Godot.kt'() has some problems?  or the ‘OnCreate’(Godot.kt:180) function is not executed totally? 
I'm not an expert at android development, so I can just give some clues..

Here is my workaround: 
1. open res://android/build/src/com/godot/game/GodotApp.java
2. replace content with:
 `package com.godot.game;

import org.godotengine.godot.GodotActivity;
import android.view.View;

import android.os.Bundle;

/**
 * Template activity for Godot Android builds.
 * Feel free to extend and modify this class for your custom logic.
 */
public class GodotApp extends GodotActivity {
	@Override
	public void onCreate(Bundle savedInstanceState) {
		setTheme(R.style.GodotAppMainTheme);
		super.onCreate(savedInstanceState);
		View decorView = getWindow().getDecorView();
		int flags = View.SYSTEM_UI_FLAG_LAYOUT_STABLE | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION | View.SYSTEM_UI_FLAG_FULLSCREEN | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
		decorView.setSystemUiVisibility(flags);
	}
}`  

3. export the project from editor again.

**Comment by MTareqAzim** [comment]
Through a whole bunch of trial and error, I found that the `commandLineFlags` don't properly get read and applied. The `OnCreate()` in `Godot.kt` tries to get the flags using `getCommandLine()`.
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L199
`getCommandLine()` then tries to get the flags from `parseCommandLine()`.
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L863-L870
`parseCommandLine()` then does a try-catch and encounters an exception at getting the Activity.
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L872-L875
And just returns an empty list.
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/platform/android/java/lib/src/org/godotengine/godot/Godot.kt#L901-L904

If you bypass the command line settings and paste the immersive code inside the `onCreate()` try block, it properly sets up immersive mode. So the structure of the setup is good, having all the code in `Godot.kt`, as opposed to my previous comment that assumed the proper View isn't getting the values set.

However, I can't seem to figure out how to get it to parse the `commandLineFlags` properly. I said I used trial and error to figure this out, recompiling the templates and exporting my own build to my android device. Because of that, I was only able to roughly find where the problem lies, but I can't say for sure. For instance, why would it fail at `requireActivity()` in `parseCommandLine()` (code past that point wouldn't run and the catch block code would run) but not in `OnCreate()` that also has a try-catch block, uses `requireActivity()`, and runs just before that code?

If someone who could properly debug Android builds takes a look at this, I would appreciate it. I am once again putting this in the back burner while I work on my own game.

**Comment by Zamir7** [comment]
godot 4.2 beta 3, immersive on don't work. Status bar is visible/

**Comment by Sam-Smith-1974-09-13** [comment]
Hi, this bug is holding up our release of our game to Google Play.  Will this bug fix be in upcoming Godot Engine version 4.2 Release Candidate 1 ?  -Sam

**Comment by akien-mga** [comment]
The fix was merged two days ago in the `master` branch, which means it will be in the next 4.2 beta build (all dev builds for the next feature release are made from the `master` branch).
