### ISSUE TITLE
Provide macOS .dmg images for the Godot editor

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#8058]
Official Godot releases could be bundled in `.dmg` images. It allows for a fancier installation interface as seen in [this blog post](https://asmaloney.com/2013/07/howto/packaging-a-mac-os-x-application-using-a-dmg/). It may also be more familiar than extracting a `.zip` file, at least for some users.

Some nice design for the install background is needed too.

Just like for Windows, providing guidance or scripts for packaging Godot projects for macOS may be useful.

**Comment by TierraDelFuego** [comment]
This would be a good feature to have as it would provide a way to fix this issue when exporting from linux to macosx: https://github.com/godotengine/godot/issues/527

For building macosx dmg from linux there are a few different ways to go:
https://stackoverflow.com/questions/286419/how-to-build-a-dmg-mac-os-x-file-on-a-non-mac-platform

Here's one way:
https://github.com/hamstergene/libdmg-hfsplus

Another:
hfsplus-tools

And another:

- mkdir -p dmgdir/progname.app/Contents/{MacOS,Resources}
- ...copy your PkgInfo, Info.plist to Contents...
- ...copy your .icns to Resources...
- ...copy your other things to where you expect them to go...
- genisoimage -V progname -D -R -apple -no-pad -o progname.dmg dmgdir 

> 
> If you want to be really fancy, you can steal the .DS_Store file from a DMG made on a 
> Mac with a volume name progname and app bundle called progname.app (i.e., matching > what you want to create off the Mac) where you've put a background in 
> .background/background.png and a symbolic link to /Applications in the root dir, and put > that in dmgdir along with your own a symbolic link to /Applications.

And another that runs on macosx only:
https://gist.github.com/asmaloney/55d96a8c3558b2f92cb3

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
