### ISSUE TITLE
Functions accept typed arrays and cannot inherit conversions

### ISSUE THREAD

**Issue by CodeLazier** [godotengine/godot#80586]
### Godot version

4.2 dev3

### System information

Win10 Vulkan

### Issue description

```gdscript
extends Node2D

class A:
    func say()->void:
        print('A')

class B extends A:
    func say()->void:
        print('B')
		
func test(a:A)->void:
    a.say()
	
func test_arr(a:Array[A])->void:
    for _a in a:
        _a.say()

func _ready() -> void:
    test(B.new())
    var _b:Array[B]=[B.new(),B.new()]
    # Implicit type conversion,run error
    test_arr(_b)
    # Explicit type conversion
    test_arr(_b as Array[A]) 
	
    #only stupid manual conversion
    var _a:Array[A]=[]
    for i in _b:
        _a.append(i)

    test_arr(_a)


```

### Steps to reproduce

see description

### Minimal reproduction project

None

**Comment by dalexeev** [comment]
I don't think this issue is correct. Arrays are passed by reference, so they cannot be "converted". A new array must be created, which can lead to large memory consumption in case of large arrays. Also, element types must be **equal**, supertypes are not supported (because there is no read-only attribute in the type system).

What you perceive as a conversion is just a non-obvious behavior that we added for convenience. This only works for literals and constant expressions. We treat an untyped literal as typed, depending on the context. We should probably add a warning about this after we add [typed array constructor](https://github.com/godotengine/godot/pull/71336).

See also godotengine/godot-proposals#7364 and [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays):

![](https://github.com/godotengine/godot/assets/47700418/20055ddf-8f4b-4dbc-83e6-2bc13b26e8d3)

**Comment by CodeLazier** [comment]
Maybe this is not a bug, but it is definitely a big flaw in the type system in terms of usage. At least there are methods or functions that support conversion, or syntactic sugar, otherwise it would be too stupid and boring to convert manually.

**Comment by dalexeev** [comment]
> At least there are methods or functions that support conversion, or syntactic sugar, otherwise it would be too stupid and boring to convert manually.

Instead of a loop:

> ```gdscript
>     #only stupid manual conversion
>     var _a:Array[A]=[]
>     for i in _b:
>         _a.append(i)
> 
>     test_arr(_a)
> ```

You can use the [`assign()`](https://docs.godotengine.org/en/stable/classes/class_array.html#class-array-method-assign) method:

```gdscript
    var _a: Array[A] = []
    _a.assign(_b)
    test_arr(_a)
```

After #71336 you will be able to do:

```gdscript
    test_arr(Array[A](_b))
```

**Comment by CodeLazier** [comment]
looks good, #71336 more in line with my expectations.

Thanks for the clarification.
