### ISSUE TITLE
Add Gradient support in environment fog

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8060]
The ability to add different gradient colors for global fog allows for some awesome lighting/artistic techniques.

![v3h7lu6](https://cloud.githubusercontent.com/assets/1642015/24048706/96abdcb2-0b21-11e7-97b0-7d96ffae47d4.png)

Could we replace the "solid" color in Fog parameters with a colorramp?

**Comment by Zylann** [comment]
That implies that the shader implementing the fog would have support for gradients, and the only general way I know is doing a texture fetch on a generated texture. Would be nice if people not using a gradient to not have to pay the performance impact (if there is).

**Comment by nunodonato** [comment]
@Zylann in the current 2.x code, the code passed to the shader is the fog begin and end color, which then is interpolated according to the depth. 

cant we just change the begin and end color being passed to the shader, according to the color steps in the color ramp? in the shader side of things, there would be no difference.

just a thought, but perhaps there are better ways

**Comment by Zylann** [comment]
It would work, only for two colors unfortunately. But that's better than nothing, and for no cost^^

**Comment by nunodonato** [comment]
well, two colors is what the current implementation does :)

**Comment by Zylann** [comment]
It's also possible to make a multi-coloured fog with a ColorRamp already, by making custom shaders shared by every object in the game world, and turning off the default fog.

I'm not saying it doesn't, but you said adding ColorRamp. ColorRamp is a resource allowing any gradient to be created, so you probably meant to have two color properties instead.

**Comment by nunodonato** [comment]
making custom shaders for every object in a big 3d game is nuts :) no, I meant a colorramp, to allow multiple gradients between two colors

**Comment by Zylann** [comment]
Well... then you need a different fog shader in Godot code that uses a texture fetch, or a generated set of interpolations between colors.

Having a shader on many objects in a big 3D game is pretty common, btw^^
They are often shared between them so there is no need to create one per object. But I agree it's a big hassle in the case of fog, because fog is basically everywhere xD

**Comment by nunodonato** [comment]
adding this, for reference: https://forum.unity3d.com/threads/colorful-fog-a-fog-effect-with-more-coloring-options.351082/

**Comment by n-pigeon** [comment]
Height based fog *drooooool* (fog with sky colors <3)

**Comment by Zylann** [comment]
I wonder if fog could use GI probes or be affected by shadows? But that would be a separate issue^^

**Comment by nunodonato** [comment]
for more reference, uncharted 4 http://advances.realtimerendering.com/other/2016/naughty_dog/NaughtyDog_TechArt_Final.pdf

using a texture for fog seems to be a viable option too

**Comment by n-pigeon** [comment]
This topic is also related to - #8668

**Comment by reduz** [comment]
right now i don't really want to spend an extra texture on this, BUT I am thinking of adding something like "global" shaders, where you can create a shader that mixes with all the active shaders in the scene.. this would allow a ton of amazing effects, not just this.

**Comment by reduz** [comment]
as such i'm kicking it to 3.1

**Comment by Chaosus** [comment]
Re-kicking to 3.2, as we are at the feature freezing state

**Comment by aaronfranke** [comment]
The name of this proposal needs to be changed in accordance with https://github.com/godotengine/godot/pull/25821

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
