### ISSUE TITLE
Dedicated material editor

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#8069]
With Godot 3 support for PBR materials, being able to create, edit, visualize materials and shaders will become much more relevant than what it is now.

In the current version, working a lot in materials and shaders feels cramped due to the interface of the editor. There are too many panels and divisions, especially when you are working in the visual graph editor (regardless of being able to zoom or not).

I'd like to propose for consideration a better UI for a dedicated material/shader editor, much like UE4 has. Could be a dedicated window, or a "editor view"(not sure if this is the right term), much like we have now 2d/3d/script/asset lib.

![maxresdefault](https://cloud.githubusercontent.com/assets/1642015/24072128/b0e3a6f6-0bd9-11e7-9307-8660976296e8.jpg)

From this material editor, we should be able to create and save new materials or shaders, without having to select or create any object first, as well as open previously saved materials to view and edit.

Having a dedicated and improved preview pane would also be great. It could allow to quickly view textures, but also to preview the material in a small 3d window (which would allow for different kinds of preview objects like cube, sphere, plane).

Anyone willing to discuss this further? :)

**Comment by eon-s** [comment]
It will be like using the central panel as shader editor (text or node based) instead of the bottom one, and the preview could be placed on the shader resource tab too because the main scene is on another view.

I like it, this layout could be a problem to preview some screen shaders though, unless a preview option is a view of the current scene.

**Comment by fire** [comment]
https://godotengine.org/article/major-update-for-visual-shader-in-godot-3-2 Can you check if this 3.2 feature does what you want?

**Comment by Calinou** [comment]
As for making procedural textures, the Godot-based tool [Material Maker](https://rodzilla.itch.io/material-maker) might suit your needs too.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
