### ISSUE TITLE
Expose call_multilevel to scripting

### ISSUE THREAD

**Issue by mablin7** [godotengine/godot#8070]
I'm working on the framework of my game in Godot, and I use script inheritance, and function overriding a lot. And in order to call a function both in the children and the parent scripts, you would have to use `call_multilevel`, which is not yet exposed to GDScript.
I was about to make a PR, but then I thought it would be better to first make sure others would need this too

**Comment by bojidar-bg** [comment]
Was thinking of this today as well. It is sometimes useful to do a multilevel call of some functions.

I was wondering if it wouldn't it be better if we make it a flag on the function instead:
```gdscript
func test():
  pass
func call_test():
  call_multilevel("test")
# ----- OR -----
multilevel func test():
  pass
func call_test():
  test()
```

**Comment by akien-mga** [comment]
> `multilevel func test():`

![ETOOMANYKEYWORDS](https://i.imgflip.com/20xrv3.jpg)

**Comment by magyar123** [comment]
Yeah i also think a keyword would be unnecessary. It doesn't have to be overcomplicated.

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
