### ISSUE TITLE
Vector2 literals with swapped signs

### ISSUE THREAD

**Issue by eska014** [godotengine/godot#8081]
**Operating system or device - Godot version:**
FreeBSD, 9061d6f8ce8c393653204b7565d7af3fe0c3c084

**Issue description:**
```
func _init():
	Vector2(3, -2)
	print(Vector2(-3, 2))
```
This code prints `(3, -2)`. Expected is `(-3, 2)`.
Doesn't occur in 2.1.2

**Comment by bojidar-bg** [comment]
Sounds related to #7815, can someone bisect?

**Comment by bojidar-bg** [comment]
I tested this right before #7815 and right after #7815 (on 36986531afe3996de05640ff02088d18b24d409c and 903a3aa5f0e128abb1fb752c10b343b34af8f799), and I can confirm that the issue is caused by it.

Testing script:
```gdscript
func _ready():
  print(Vector3(-1, 0, 1))
  print(Vector3(1, 0, -1))
```

Pre-#7815 output:
```
(-1, 0, 1)
(1, 0, -1)
```
Post-#7815 output:
```
(-1, 0, 1)
(-1, 0, 1)
```

@hpvb Are you going to be able to look into this?

**Comment by hpvb** [comment]
I found the issue, I'll make a PR asap. The problem is that I also switched to a different hashing algo for non-floats. 

I don't even remember why I did that.

**Comment by hpvb** [comment]
Seems that that function in the hash code wasn't used because it was broken. Whoops?
