### ISSUE TITLE
ImageTexture3D serialization bug

### ISSUE THREAD

**Issue by Mohamed-Kr** [godotengine/godot#80866]
### Godot version

4.1 stable and 4.2.dev3

### System information

Godot v4.1.stable - Windows 10.0.22621 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9621) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When I create a ImageTexture3D, populate it and then save it I obtain a 1x1x1 Lum8 pink texture instead of the one I created (I think it is properly created beacause it behaves well when I use it in a custom shader).

This happens whether 
- it is running as tool or not 
- I try to save in a res or in a tres file
- I put flags in the `ResourceSaver.save` function or not

and it don't give errors.

And when It is in a shader uniform in editor, working properly - If I save the scene and reopen it, there's pink where the texture is involved and the 1x1x1 in the uniform field.

### Steps to reproduce

- Create a project and a scene
- Give the root the script below
- Close the scene and reopen it to make sure that `@tool` takes effect
- Try running the scene or checking the `save` boolean field in the inspector 
- Check if the `ImageTexture3D` got saved properly in the FileSystem Dock

```
@tool
extends Node

@export var save := false :
	set(v) :
		ResourceSaver.save(_get_grad_tex(), "res://tex3D.res")
		ResourceSaver.save(_get_grad_tex(), "res://tex3D.tres")

func _ready() -> void :
	if Engine.is_editor_hint() : return
	ResourceSaver.save(_get_grad_tex(), "res://tex3D.tres")
	ResourceSaver.save(_get_grad_tex(), "res://tex3D.res")

func _get_grad_tex() -> ImageTexture3D:
	var res := ImageTexture3D.new()
	var imgs : Array[Image] = [] 
	for i in 10 :
		var img := Image.create(10, 10, false, Image.FORMAT_RGB8)
		imgs.push_back(img)
	for x in 10 :
		for z in 10 :
			for y in 10 :
				imgs[z].set_pixel(x, y, Color(x/10., y/10., z/10.))
	res.create(Image.FORMAT_RGB8, 10, 10, 10, false, imgs )
	return res
```

### Minimal reproduction project

N/A

**Comment by clayjohn** [comment]
Looks like we need to port https://github.com/godotengine/godot/pull/71394 to ImageTexture3D as well

**Comment by jsjtxietian** [comment]
@clayjohn  The code here posted here don't work on the mrp because this code regarding mimmaps in set_image:
```
if (img->get_width() != new_width || img->get_height() != new_height) {
	new_mipmaps = true;
	if (new_depth == 0) {
		new_depth = i;
	}
}
```

I guess we don't need to calculate the depth this way, just use p_images.size() is ok? 

But the mipmap needs more work here. The code do not allow the individual image has mipmap, but when you create a texture3d with mipmap, `get_data` will fail because `texture_owner` is null (But this is not related to the serilization code here, just a bug I found)

After fixing this, the code works well like the image below, but still will triger two errors because of some resource init code will read the texture array's info before it actually deserilize it. 

![image](https://github.com/godotengine/godot/assets/8315986/ec02b072-5966-4f68-8b6b-b3e210e35da0)

Also we may not need `ERR_FAIL_COND_MSG(img->get_format() != new_format, "All images must share the same format");` since `validate_3d_image` will do all the check for us.

I'm happy to continue digging if you allow me to continue based on your work :)

**Comment by jsjtxietian** [comment]
The code still triger two errors in editor console because of some resource init code will read the texture array's info before it actually deserilize it.

These two errors come from:
ResourceLoaderText::load() 's Variant get_value = resource->get(assign, &is_get_valid); will eventually call its `_get_images` and `get_data`, but the texture3d is not inited with its data yet ;  after it, the `_set_image` will be called at `resource->set(assign, value)` and it will be inited correctly.
