### ISSUE TITLE
Mobile renderer gives a black screen in certain scenarios

### ISSUE THREAD

**Issue by Mohamed-Kr** [godotengine/godot#80871]
### Godot version

4.2.dev3

### System information

Godot v4.2.dev3 - Windows 10.0.22621 - Vulkan (Mobile) - integrated Intel(R) Iris(R) Plus Graphics (Intel Corporation; 27.20.100.9621) - Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 Threads)

### Issue description

When visualizing any mesh in the Inspector while using the mobile renderer (the other renderers don't have this issue), it gives a black square and spams the error `Draw command lacks indices, but pipeline format does not use vertices.`. It throws the error only when a concerned mesh is being rendered, it stops when i deselect the node.

I also have a project where the whole screen turned black, in editor and in builds but I can't reproduce it, I tried everything I was doing in my other project I thought may have caused it :
- Using a populated `ArrayMesh`
- Putting a custom shader on it
- using `render_mode world_vertex_coords, unshaded, shadows_disabled;`
- editing `VERTEX` and `NORMAL` in `vertex`
- using varyings
- using global uniforms
- using uniform sampler2D with a noise texture in it
- having a PlaneMesh with ~1M triangle with the custom shader on it
But it seems that none of this causes the black screen.

### Steps to reproduce

Click on any Node that causes a Mesh to be previewed in its inspector - for example a MeshInstance3D with a material in `material_override` or simply a Meshinstance3D that has a Mesh in its `mesh` field.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot/issues/67234.

**Comment by Mohamed-Kr** [comment]
I'm using the default stretch mode, `disabled`.

**Comment by BastiaanOlij** [comment]
Make sure you test this on master, seems like the same issue I fixed a few days ago but was present in dev3

**Comment by jeffreyfq** [comment]
I had the same issue, I recompiled the engine ~a week ago, after this, the engine was running fine on my linux notebook.
But I still had the same issue on an android device (PICO 4 VR).

I tested today again, (probably I made a mistake while updating the android export template).
It works now:
- On then notebook all (gl_compatibility, mobile, forward_plus) can be used.
- On the PICO 4 (android VR device): gl_compatibility and mobile work fine. forward_plus still has some problems (rendering seems to work but  somehow the collision does not work and the character starts to fall down ...)

Assuming you have the source via git (master branch), I did this:
```
git pull
export ANDROID_NDK_ROOT=/home/.....wherever the android sdk is ... /Android/Sdk/ndk/25.1.8937393/
export ANDROID_SDK_ROOT=/home/.....wherever the android sdk is ... /Android/Sdk/
scons platform=android target=template_debug arch=armv7
scons platform=android target=template_debug arch=arm64v8
cd platform/android/java
./gradlew generateGodotTemplates
cd ../../..
scons platform=android target=template_release arch=armv7
scons platform=android target=template_release arch=arm64v8
./gradlew generateGodotTemplates
cd ../../..
```
After this the updates binaries are in the ```bin``` folder. Be aware that my configuration takes the .aar files, not the apk ones. You then have to update your project, e.g. overwrite the debug and release files (in my case the aar-ones)  in the `android/build/libs/debug/` and `android/build/libs/release` folder of your project. Also update the android export template, e.g. in my case it was in `$HOME/.local/share/godot/export_templates/4.2.dev/`


Not sure, as I don't know so much about the details, but maybe interesting for @BastiaanOlij  :  I think you are very much involved in the VR support, as I wrote above, I updated my PICO 4 VR recently to the new Firmware and the vulkan renderer (at least `mobile` seems to work fine, `forward_plus` seems to almost work ). Also the XRToolbox is quite fancy, as it is really easy to set up. I was able to set up a scene walk/beam around and pick and throw objects (even though my 3d-engine-knowledge is quite limited)

**Comment by BastiaanOlij** [comment]
@jeffreyfq compiling from source for Android when you're using the newer android build setup is a bit of a PITA because it's easy to get it wrong and accidentally run with an older build.

Best is always to delete your android folder in your project, and reinstall the template but now select the android_sources.zip file build when you compiled the engine. Better than trying to move files around and missing some of the other changes applied to the system.

Also keep in mind that the loaders setup changed but seeing you have it working I'm assuming you already made the needed changes.

**Comment by jeffreyfq** [comment]
@BastiaanOlij Thank you for the information, I was not aware that I can use the `android_sources.zip` file as template as it includes the binaries. I will change this.

**Comment by BastiaanOlij** [comment]
yeah basically if you don't have templates installed and you select `Install Android Build Templates` you get an option to select a file, you just select the `android_source.zip` created when running gradlew and it installs the new template.
This includes your new binaries, but also any changes to the manifest file and some other stuff that is different with the template approach.

**Comment by lostminds** [comment]
I'm getting something that may be this same issue on 4.2dev3 in a Mobile renderer project: 
On my computers (M2 and intel macOS 13.5.1) I have some 3d scenes that now just render black in editor, spamming the `"Draw command lacks indices, but pipeline format does not use vertices"` error each frame. I've been unable to pin down what is causing it since the same assets and shaders render in other scenes. Stretch mode is disabled.
But when running the game I just get one or two such errors initially, but then the 3d scenes render with no problem. When exporting however, the same issue (the 3D scene rendering just black, while the UI renders as expected) seems to be present on some newer iOS devices. On my iPhone XS it works fine, but on a newer iPhone 13 Pro the game 3d scene renders black.

**Comment by BastiaanOlij** [comment]
@lostminds that one should be fixed, just need to compile from master

**Comment by Calinou** [comment]
Alright, closing then :slightly_smiling_face:
