### ISSUE TITLE
[Android][C#] Failed to initialize godot plugins error 

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#80885]
### Godot version

4.2.dev.mono.custom_build.8e0346bad

### System information

macOS

### Issue description

An error is thrown when running an Android project that was exporting with a C# plugin enabled.
The error is not fatal per se, but gives no indication of what the underlying issue is.

```
godot                   com.godot.game                       E  USER ERROR: .NET: GodotPlugins initialization failed
godot                   com.godot.game                       E     at: initialize (modules/mono/mono_gd/gd_mono.cpp:431)
```

### Steps to reproduce

1) Create a C# plugin
2) Create an EditorExportPlugin (maybe be unrelated)
3) Enable the plugin in the project settings
4) Export to Android
5) Run the Android Studio solution
6) Notice the error thrown even tho the game does not crash

### Minimal reproduction project

[CSPlugin.zip](https://github.com/godotengine/godot/files/12406664/CSPlugin.zip)

**Comment by raulsntos** [comment]
That error is printed when the initialize method[^1] method return false. This method always returns true, unless there was an exception and in this case the exception is printed to the console with `Console.Error.WriteLine`, I'm not sure where this is printed when running the Android Studio solution (maybe logcat?).

[^1]: If we're in the editor, the initialization method is `GodotPlugins.Main.InitializeFromEngine`. \
Otherwise, it's `GodotPlugins.Game.Main.InitializeFromGameProject`.

**Comment by duarteroso** [comment]
Caused by #80904
