### ISSUE TITLE
Broken warning popup after creating a C# plugin

### ISSUE THREAD

**Issue by duarteroso** [godotengine/godot#80883]
### Godot version

4.2.dev.mono.custom_build.8e0346bad

### System information

macOS

### Issue description

After finishing the creating a plugin using the `Create New Plugin` flow, a warning popup appear all red making it impossible to know what the warning is about.

### Steps to reproduce

1) Go to Project Settings
2) Under the Plugins tab, create a new plugin
3) Fill up the detail (I created a C# script)
4) A warnning should appear after closing the creation window

Looking at the console, this could be the warning
`Another resource is loaded from path 'res://addons/my_other_plugin/OtherPlugin.cs' (possible cyclic resource inclusion).`

![image](https://github.com/godotengine/godot/assets/11413364/1455f0a1-b27f-40ca-8c8b-cba636f37217)

### Minimal reproduction project

[CSPlugin.zip](https://github.com/godotengine/godot/files/12406521/CSPlugin.zip)

**Comment by raulsntos** [comment]
You probably had the `Active now?` option checked. In this case, the warning should look like this:

![image](https://github.com/godotengine/godot/assets/3903059/a0e45913-0005-4864-a99b-932605cd04c7)

This is because C# scripts needs to be built before the plugin can be activated, so the `Active now?` option should always be unchecked for C# plugins. This is mentioned in the [_Making plugins_](https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#doc-making-plugins) documentation page.

---

This seems to be a rendering issue. I can reproduce it in Linux with v4.1.stable.mono.official [970459615] but not with 4.0.

![image](https://github.com/godotengine/godot/assets/3903059/e96b4f32-95cb-4046-bc00-63e801d66758)

**Comment by duarteroso** [comment]
’’‘
This is because C# scripts needs to be built before the plugin can be activated, so the Active now? option should always be unchecked for C# plugins. This is mentioned in the Making plugins documentation page
’’‘

Would it make sense to hide it if C# is selected?
Feels like a better UX if there is no case for the option to ever be enabled when C# is selected.

**Comment by Calinou** [comment]
> Would it make sense to hide it if C# is selected?

Yes, I agree the checkbox should be unchecked and disabled when you set the language to C#. A warning should also be displayed below to mention that the option isn't available for C# plugins.
