### ISSUE TITLE
Method track shows lines between keys

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#80924]
### Godot version

4.2 dev3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

If you have a Method Track with multiple calls to the same method, they are joined together and makes things unreadable:
![image](https://github.com/godotengine/godot/assets/2223172/a2ab8446-28a1-440b-b0d5-5049f5d705b4)
The horizontal line shouldn't be used here. I think it might be a regression.

### Steps to reproduce

1. Add AnimationPlayer
2. Add a Method Track (with Add Track button)
3. Add some key to the track
4. Add another key with the same method

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
I think I can see where the bug is.

When drawing keyframes, the editor will call `draw_key_link`, and it will decide whether to draw a line based on the comparison below. Unfortunately, for method track , `track_get_key_value` will return a dictionary with methods and args, "multiple calls to the same method" is same in this comparison.
```
Variant current = animation->track_get_key_value(get_track(), p_index);
Variant next = animation->track_get_key_value(get_track(), p_index + 1);
if (current != next) {
	return;
}
```

For a quick fix I guess I can add a if here and if it's a method track then return. Any suggestions ?
