### ISSUE TITLE
renaming a folder and pressing `enter` enters the folder

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#80940]
### Godot version

4.1.1

### System information

linux

### Issue description

[simplescreenrecorder-2023-08-23_19.45.00.webm](https://github.com/godotengine/godot/assets/71937306/95f761ff-8589-4612-8916-ec76603284bf)

as you can see, renaming a folder and then pressing the `enter` key to confirm both confirms and navigate inside the folder..

### Steps to reproduce

1. FileSystem in split mode
2. rename a folder in the bottom view and confirm by pressing `enter`

### Minimal reproduction project

any

**Comment by coumcashier** [comment]
Hi [mieldepoche](https://github.com/mieldepoche)

I think this is because we update the current_path after the rename operation.

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/editor/filesystem_dock.cpp#L1742-L1752

the rescan triggers FileSystemList to update eventually
https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/editor/filesystem_dock.cpp#L470

**Comment by coumcashier** [comment]
maybe we can use a different callback here that does not change current_path

https://github.com/godotengine/godot/blob/6758a7f8c07d1f4c8ec4f052ded6d26402967ebe/editor/filesystem_dock.cpp#L3461

**Comment by coumcashier** [comment]
I would like to work on this issue if the above is correct
