### ISSUE TITLE
Editor FileSystem defaults to unfolded folder structure 

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#8096]
**Operating system or device - Godot version:**
Godot 2.1.2 official. Windows 10 x64 pro

**Issue description:**

The FileSystem folder structure defaults to unfolded.

**Steps to reproduce:**
In the editor look under the filesystem. Navigating away causes the folder structure to unfold. 

**Link to minimal example project:**
It's kind of annoying when looking for assets and everything is unfolded no matter how many times I refold all the folders.

**Comment by TwoOfDiamonds** [comment]
The problem is that FileSystemDock recreates the whole tree when using backwards or forwards navigation. One workaround would be to store the collapsed/expanded structure of the tree and remake it aftewards unfolding the path that we navigated to as well as all the other paths that were previously unfolded.

**Comment by Krakean** [comment]
Is this still actual? Can't reproduce.

**Comment by akien-mga** [comment]
Closing as fixed then, probably by one of @MillionOstrich's PRs.
