### ISSUE TITLE
Paste Value can empty an array depending on right-click location

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot#80974]
### Godot version

4.2.dev 6758a7f8c

### System information

Godot v4.2.dev (6758a7f8c) - Fedora Linux 38 (KDE Plasma) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (nvidia; 535.98) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

- *Related to https://github.com/godotengine/godot/issues/75124.*

**Paste Value** on an exported Array property can empty the array depending on right-click location:

https://github.com/godotengine/godot/assets/180032/e9cf313b-bb09-4712-95cd-f53481fa33e4

### Steps to reproduce

- Create a script with an exported array property.
- Save the scene (and script) and select the node.
- Add 3 items to the array with any type (`int` is used in this example).
- Set non-default values for each item.
- Right-click an item and choose **Copy Value**.
- Aim to the left of the item's name (near the drag-and-drop reorder icon), right-click another item and choose **Paste Value**.
- Notice how the array's size is reset to 0 and all values are lost (this can be undone).

### Minimal reproduction project

[test_array_paste_value_empty.zip](https://github.com/godotengine/godot/files/12433905/test_array_paste_value_empty.zip)

**Comment by ajreckof** [comment]
I think this encompass two different issue.
First that you are able to call the popup menu of the whole array where you shouldn't. Second that pasting an int to an array will wipe out the array this seems probably legitimate since there is no way to convert an int but it does so while spouting a lot of errors and preventing you from using the `PropertyEditor`. The second part is strange as it is happening even when the property is typed and shouldn't be able to hold an int at all :(.
