### ISSUE TITLE
Comparing two Vector2 will only check if the x is true

### ISSUE THREAD

**Issue by Schwegg** [godotengine/godot#80982]
### Godot version

4.0.3 stable

### System information

Windows 10 64 bit - Godot 4.0.3 Stable - Vulkan (Forward+)

### Issue description

Comparing a Vector2 to another Vector2 returns true if only the x comparison is true/false, ignoring the y comparison.

### Steps to reproduce

Compare a Vector2 to another Vector2.
`
print( "true" if global_mouse_position > Vector2( 200, 200 ) else "false" );
`

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/12435922/example.zip)

**Comment by dalexeev** [comment]
It's [documented](https://docs.godotengine.org/en/stable/classes/class_vector2.html#class-vector2-operator-gt-vector2). This behavior is chosen so that the vectors can be ordered in a unique way ([lexicographic order](https://en.wikipedia.org/wiki/Lexicographic_order)) when sorting, for example for binary search. If comparing both components (as you suggest), such ordering is not possible.

**Comment by AcatXIo** [comment]
**Since people might search for a workaround here:**

One possible approach, if one wants to check a condition for both `x` and `y` components at once, is:
```gdscript
print("true" if (global_mouse_position.x > 200 and global_mouse_position.y > 200) else "false");
```
However, for bounds checking (more specifically checking if a given point is inside of a given rectangle), using something like the [has_point() method of Rect2 class](https://docs.godotengine.org/en/stable/classes/class_rect2.html#class-rect2-method-has-point), might be more appropriate.

**If you would like a more detailed answer to your specific problem, please ask on the [community channels](https://docs.godotengine.org/en/stable/community/channels.html) instead.**
