### ISSUE TITLE
int treated as float when loading from JSON file

### ISSUE THREAD

**Issue by bitbrain** [godotengine/godot#81035]
### Godot version

4.1.stable.official

### System information

Windows 11

### Issue description

Storing an `int` into a `Dictionary` works as expected and the type is preserved:
```gdscript
var dict = {"int":42}
print(dict["int"] is int) # outputs 'true'
```
However, when storing this dictionary to disk (as json) and then reloading it, converts it into a `float` for some reason. Given a json file called `test.json`:
```json
{"int":42}
```
...and loading it like this:
```gdscript
var file = FileAccess.open("res://test.json", FileAccess.READ)
var json = JSON.new()
if file != null:
   var text = file.get_as_text()
   json.parse(text)
   file.close()
   var data = json.get_data() as Dictionary

   print(data["int"] is int) # outputs 'false'
   print(data["float"] is float) # outputs 'true'
```
In JSON world, everything is just a number [and numbers are always floating point](https://www.w3schools.com/js/js_numbers.asp) but from a Godot perspective this can lead to bugs and is not intuitive, as types in Godot exist. So I'd at least expect some logic of "if stored number has floating points -> treat as float, otherwise treat as int"

### Steps to reproduce

1. Open MRP
2. Run MRP

### Minimal reproduction project

[wrong-parsing.zip](https://github.com/godotengine/godot/files/12447685/wrong-parsing.zip)

**Comment by TheDuriel** [comment]
https://docs.godotengine.org/en/stable/classes/class_json.html#class-json-method-stringify

> Note: If full_precision is true, when stringifying floats, the unreliable digits are stringified in addition to the reliable digits to guarantee exact decoding.

The parser already handles int and float detection. You need to generate compatible json however.

**Comment by TheDuriel** [comment]
The issue with changing the behavior, is that it will then turn floats into ints when you don't want it to.

**Comment by AThousandShips** [comment]
So changing the parsed type would only affect what type it ends up being in GDScript, not the precision, as we really shouldn't break with the JSON standard so massively that we store plain int values IMO

This is simply the reality of the JSON standard IMO, it is even documented in the `stringify` method, but not in the `parse` one or the header which might be good to add

**Comment by YuriSizov** [comment]
So, to conclude discussion on and off the platform. Integers do not exist in the JSON spec. Every numeric value is treated as a float by design. Any change on the Godot side would break expectation and break compatibility with the standard. Some servers, for example, can truncate round floating point numbers in JSON, just to save a bit on the traffic. So for the same field you can get `12.3` and `10`. If we treat them differently, it would be incorrect on every level.

With that said, the issue for Godot users encoding Godot objects to JSON and then decoding them is understandable. It was suggested we add some kind of runtime warning to indicate that there can be loss of type when doing so. But the problem is that this will quickly become annoying if the developer is aware of the issue and is okay with the situation. And there won't be an easy way to disable such a warning in an arbitrary method (we have ways to disable GDScript VM warnings, but not warnings in arbitrary API methods). As such, this won't be a suitable solution.

I think the docs are the best area where this issue can be solved. As noted above, there are already mentions of this behavior in the documentation. Perhaps, we are missing it in a few places where it can still be added.

JSON is generally not the best format to use to preserve Godot's resource information. It's good for interop with other consumers, servers, clients, frameworks, etc. But for this interop we need to adhere to the spec. For Godot users who still want to use JSON inside of the engine I'd suggest someone looking into a plugin that allows to decode JSONs according to some JSON schema format that would make sure specific fields are treated as certain Godot types and converted as needed.

Since there is no bug, I think this can be closed. But feel free to open documentation PRs if there is anything missing that is worth describing.
