### ISSUE TITLE
Built-in function for converting unit vector to euler angles vector

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8110]
Built in function to convert direction vector to euler angles for Vector3 type.

Example situation:
We have normal vector of some surface or collision point and we want to rotate other object to match that normal direction.

**Comment by tagcup** [comment]
Can you be a little bit more specific?

**Comment by n-pigeon** [comment]
@tagcup sorry. Edited first post.

**Comment by tagcup** [comment]
A rotation/orientation cannot be represented a vector: it's a matrix. (Yes, `get_euler` will return you an array of 3-angles, but that's not a vector in the 3D spatial space representing coordinates of a vector, it's just an array of numbers).

It seems you're referring to a plane or a particular face of a cube, where it's normal can be used to determine it's orientation. But this requires special conventions and will work for only certain simple geometries.

Either way, you can use the existing functions to rotate/reorient objects in any way you want. I think this discussion belongs to Q&A rather than issue tracker.

**Comment by tagcup** [comment]
I'm trying to finalize a write up about rotations and related math stuff (been busy recently), but that should hopefully clarify that XYZ Euler angles is just a parameterization of rotations (among [many other alternatives](https://en.wikipedia.org/wiki/Rotation_formalisms_in_three_dimensions)), and those 3 parameters do not form a meaningful vector in the 3D space. The return value of `get_euler` is a `Vector3` rather than a general number array for reasons related to convenience and performance.

A solution to your problem could be something like this. Let's say you have a function which gives the orientation of your object with respect to a particular plane (determined by your convention) as a vector, and you have another direction you want to turn to. These two vectors define a new plane, and you want to rotate your object around the normal vector of this plane, by the angle between them.

I'm not sure if you want to do this but you can the original basis and the rotated basis, form a `Quat` out of them, and interpolate them using `slerp` for example.

**Comment by n-pigeon** [comment]
@tagcup yup I'm aware, that euler angles are not meaningful vector (they are just stored in Vec3).

Maybe I shouldn't add that I see this conversion in Vector3 class, maybe GDScript math would be better.

When I said vector to euler conversion I was thinking about. Converting Vectors direction to euler angles based on plane of projection (specified by UP vector?) (something similar to look_at?)


What I wanted to do for example is to get collision normal and orient my 3D arrow model to match this normal in 3D space (small function for debug).
I tried this method: https://www.opengl.org/discussion_boards/showthread.php/159883-converting-a-3D-vector-into-three-euler-angles
but something went wrong probably and I didn't spend more time to try make it work for now (maybe today).

I will try write up my findings about that. I think it could be beneficial to have something like this in Godot.

**Comment by tagcup** [comment]
Yes, but I don't see why it warrants a special function, it's doable with available functions. What I described in my previous post should work.

**Comment by n-pigeon** [comment]
Thank you for help. I will try tackle this somehow. I just really have hard time with it ^^' I will try to play a bit with axis angles on basis and try to understand it.

Thx :)

**Comment by tagcup** [comment]
Euler angle parameterization isn't really suited for this kind of transformations. You really need to use axis-angle parameterization.
This is becoming like a Q&A more and more, but here it goes:

```gdscript
var axis  = from.cross(to).normalized()
var angle = from.angle_to(to)

# for rotating the object directly
var rotated_transform = object.get_transform.rotated(axis, angle)

# for smooth interpolation
var q_from = Quat(object.get_transform().basis)
var q_to = Quat(rotated_transform)

# interpolation parameter t is varied between 0 and 1
var q_intermediate = q_from.slerp(q_to, t)
# ...
```

In any case, I don't see any reason to add a new function for this specific use case.

**Comment by tagcup** [comment]
That being said, while not useful for this particular use case, there will be some additional functions for Basis in before 3.0 (`set_euler`, `get_axis_and_angle`, `get_rotation`). These functions exist on the C++ side, they just need to be exposed to GDScript.

**Comment by n-pigeon** [comment]
Closing. I made it work with @tagcup help on IRC :)

Solution notes:
https://snag.gy/p3m1UN.jpg

<tagcup> n is the current orientation of the top surface, m is the target direction
<tagcup> these two vectors, n and m form a plane (the bottom part of the image)
<tagcup> n.cross(m).normalized() gives you a vector that is perpendicular to these two vectors
<tagcup> if you rotate the cube around that axis by phi, the top part of the cube will be oriented along m
<tagcup> you can get phi by using n.angle_to(m)

**Comment by iLUVE69** [comment]
Thanks for this dude, i was stuck in a similar problem.

**Comment by Zireael07** [comment]
Trick worth documenting IMHO

**Comment by ell1e** [comment]
@SirPigeonz is the final snippet you ended up using available under some liberal licensing like CC0, by any chance? Euler vectors can describe a meaningful rotation of a 1,0,0 forward vector to any rotational vector as described by the vectors, but as pointed out before it can be interpreted in different ways. To match the way that `Basis.look_at(...).get_euler()` works, it would be nice if a canonical reverse function was available even if at least as some snippet somewhere.
