### ISSUE TITLE
[3.0] Basis gets broken when rotating a Camera

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8113]
Tested on Godot 3.0 master
Windows 10 64 bits

I tested my 3D debug camera, and after attempting to fix it for the new rotation convention, I've come to a point where it works, but shortly breaks completely by logging an endless stream of errors in the console.

This is the code:

```gdscript
set_rotation(Vector3(0, deg2rad(_yaw), 0))
rotate(get_transform().basis.x, -deg2rad(_pitch)) # rotate around local axis
```

And the errors:

```
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::orthonormalize: Condition ' determinant() == 0 ' is true.
   At: core\math\matrix3.cpp:74
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::invert: Condition ' det == 0 ' is true.
   At: core\math\matrix3.cpp:65
ERROR: Basis::invert: Condition ' det == 0 ' is true.
```

Repro project: 
[BasisBreak.zip](https://github.com/godotengine/godot/files/863274/BasisBreak.zip)

Launch the game, start looking around. Shortly, the camera will break and Godot will log errors on every frame.
It tends to happen when exceeding 90 degrees from the initial point of view.

**Comment by eon-s** [comment]
I was able to look around many times but, when looking up, the camera returned to the center and starting throwing that error.

In remote inspector, all the transform values on the camera are 0 when the error hit.

**Comment by tagcup** [comment]
Axis-angle rotations require that the axis is a normalized vector, meaning the code should be:

```gdscript
set_rotation(Vector3(0, deg2rad(_yaw), 0))
rotate(get_transform().basis.x.normalized(), -deg2rad(_pitch)) # rotate around local axis
```

This is not a bug, but I think we can do better. I'm planning to go through the math library to add checks for malformed inputs. Also need to document these...

**Comment by Zylann** [comment]
Do you mean Basis.x can be not normalized? I didnt't expect that from a Basis to be honest^^

**Comment by tagcup** [comment]
> Basis.x can be not normalized? (especially coming from a Transform)?

The name Basis might be misleading (RotScale might have been a better choice). It is a multiplication of a rotation and a scaling matrix, meaning, yes, it is not necessarily an orthogonal matrix.

Apart from explicit scaling, precision issues can also affect the orthogonality. Precision errors accumulate, leading to large deviation. For pure rotation matrices, it can be possible to do renormalization, but again, we don't know *a priori* that a Basis is pure rotation in general.

I tested the BasisBreak with normalizing yesterday, and it was working fine, so that appears to be the issue here.

Also, I realized that using a vector whose length is different from 1 can be used for scaling the object, so maybe it doesn't necessarily warrant a warning, but this might be confusing to some.

**Comment by eon-s** [comment]
Maybe we need those forward, right and up vectors...

**Comment by tagcup** [comment]
> Maybe we need those forward, right and up vectors...

?? Can you be more specific?

**Comment by eon-s** [comment]
@tagcup something like `basis.forward` for a normalized z vector, right for x and up for y, that may reduce confusion and keep the basis as it is now.

**Comment by tagcup** [comment]
There is a function for normalizing vectors,so I don't see much point in adding 3 more functions which do nothing more than normalization, so I think this is best handled in documentation.. I'll soon submit a PR for this, which will also raise a warning whenever the axis isn't normalized.

**Comment by reduz** [comment]
Does not basis have an orthonirmalize function?

**Comment by tagcup** [comment]
It does, but we wouldn't want to reset the scaling (which might be set explicitly by the user) in general, right?

**Comment by tagcup** [comment]
Ah, maybe you mean, if they want normalized forward. right, up vectors, they can simply get an orthonormalized copy of the basis, and use its components for this purpose?

**Comment by Zylann** [comment]
> The name Basis might be misleading (RotScale might have been a better choice). It is a multiplication of a rotation and a scaling matrix, meaning, yes, it is not necessarily an orthogonal matrix.

Which is why I didn't agree when Basis was choosen to rename Matrix3, which I believe was a confusion-free name ^^"

**Comment by tagcup** [comment]
> Which is why I didn't agree when Basis was choosen to rename Matrix3, which I believe was a general confusion-free name ^^"

I might've been the trigger for the change :D I was worried about some assumptions made in Matrix3 (namely, certain assumptions made about invertibility of the matrix) and was thinking maybe we should drop these assumptions and make Matrix3 general, as in GL(3,R), at the cost of some performance, and @reduz went the other way, because Matrix3 is meant to be used by Transform, rather than being a general linear algebra object, and he chose Basis as the new name.

It's a bit tricky actually, because it depends on how you define your basis; you can have a nontrivial metric tensor (which can represent stretching for example, as in scaling), and you can talk about covariant or contravariant vectors. Of course, calling it RotScale might have made it understandable.

> Also I see then there is one more step to go through in order to get directional vectors, so I agree specialized forward, up and right properties would be much simpler to use.

Those would be functions, and they'd just be calling normalized(), so,to me, it looks unnecessary.

**Comment by cooperra** [comment]
I just had a similar problem in 2.1.3 when misusing rotate(), except instead of a crash, my object shrank, which was very unexpected.

I would have expected auto-normalization, a warning, or an error, but not scaling.

Example:
Repeatedly call `rotate(Vector3(0.2,0,0), 0.05)` and watch your object spin and shrink.

Let me know if I should create a separate issue for this instead of piggybacking off this one. (I hesitate since they have the same root cause.)

**Comment by tagcup** [comment]
That's a precision issue. Switching to 64-bit floats should alleviate the problem to an extent. A nicer solution in the core would be to use a quaternion (which can be renormalized) for orientation and a 3-vector for scaling.

Until then, as a workaround, you can use orthonormalize function to renormalize it (if your object doesn't have a scale).

I think it would be nice to make a separate issue for this one.

**Comment by tagcup** [comment]
Actually, you can also use built-in quaternions for that already as a workaround.
