### ISSUE TITLE
Pressing space when entering the name of an editor layout confirm the save dialog

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81161]
### Godot version

4.1.1

### System information

linux

### Issue description

[simplescreenrecorder-2023-08-30_15.01.51.webm](https://github.com/godotengine/godot-proposals/assets/71937306/537d92b9-4f98-4fe6-adf4-71297be0471a)

I guess this wasn't the case before since I could save a layout named "2 monitors".

### Steps to reproduce

press space

### Minimal reproduction project

none

**Comment by jsjtxietian** [comment]
Related to #77297
Before it the `_line_gui_input` only accepts `Enter` and `Escape`, but now it utilizes key mapping `ui_accept` which contains `Space` key as well.

**Comment by puchik** [comment]
Kind of a weird one because it's obviously not great behaviour but it's still not optimal to hardcode the enter key and/or break consistency. 

Maybe the best solution is to leave the `ui_accept` as its mapping but exclude the space key (i.e., "if `ui_accept` and not `Space`"). 

The only downside to that is it'll break if `ui_accept` is _only_ `Space`, but that's kind of an unusual decision 😛 I think "hijacking" the space bar input in this use case makes sense
