### ISSUE TITLE
Changing any project setting sets the current scene as modified

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8117]
Tested on Godot 3.0 c37fad650f92845a6f59740fea2fea1b46f56db1
Windows 10 64 bits

Minor bug: save the current scene, then go to Project Settings, change the main scene (even when choosing the same one), close Project Settings. Notice the current scene is now marked as modified (*).
I didn't expect that because the setting I changed doesn't modify the scene, it only modifies godot.cfg.

**Comment by bojidar-bg** [comment]
I have seen this in 2.x too, AFAIR.

**Comment by nunodonato** [comment]
On a quick look, this seems to happen because godot decides the scene is modified when the scene version is different from the global undo_redo version (I hope I got this right)

Perhaps changing the main scene in the editor settings doesnt need to affect the undo/redo system (I wouldn't expect it to). This actually  happens if you change **anything** in the editor settings, not just the main scene.

Perhaps a new issue for undo/redo would be nice, it would be great if the undo/redo system was local to the open scene. It's very annoying to press undo and have the editor jump to a different tab.

**Comment by bojidar-bg** [comment]
> Perhaps a new issue for undo/redo would be nice, ...

Or maybe an old issue for undo/redo would suffice? E.g. like #6797 or #3511..

**Comment by reduz** [comment]
the only way i can imagine of fixing this is tagging undo redo operations as global somehow, so a bit more complex check can be implemented: 

For example: going up or down towards the last save version, check if any modification is not global..

**Comment by reduz** [comment]
if anyone volunteers, great, otherwise will kick to 3.1

**Comment by reduz** [comment]
too difficult to fix, if even possible, kicking to 3.2

**Comment by akien-mga** [comment]
This happens when changing any project setting, not just the main scene.

**Comment by akien-mga** [comment]
This seems fixed in 4.0 beta 2.
