### ISSUE TITLE
 NavigationServer3D.set_debug_enabled(true) has no visible effect

### ISSUE THREAD

**Issue by Wiggan** [godotengine/godot#81204]
### Godot version

4.1.stable

### System information

Windows10, AMD Ryzen 9 5900X, NVIDIA GeForce RTX 3060 Ti, driver version 30.0.15.1179, forward+.

### Issue description

When I call NavigationServer3D.set_debug_enabled(true) in editor or debug build, nothing happens.
According to the docs it should have the same effect as enabling "Visible Navigation".
Checking this box during gameplay has also no effect.

### Steps to reproduce

Have a navigation region, add a script which calls NavigationServer3D.set_debug_enabled(true), nothing happens.

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
You can not change debug at runtime because the nodes that display the debug do not react to it.

The NavigationServer debug can be toggled but it is only read by nodes when they are loaded / enter the scene.
The ""Visible Navigation" is only read once at game boot, you can not toggle it at all.

**Comment by gatomesa** [comment]
I still have this problem for NavigationServer2D in 4.2.2.

**Comment by akien-mga** [comment]
@smix8 Maybe my 4.2.2 cherrypick wasn't sufficient to fix the issue for the 4.2 branch?

**Comment by smix8** [comment]
@akien-mga
This might need a few other changes as there are old quirks in Godot 4.2 why this is likely not working, e.g. the old call_deferred() function did not work with the override server, needed to be changed to newer callable_mp(). There were a few other function changes in the navigation regions that render the debug as well. The PR here was only the final pr after everything else was fixed with other PRs.
