### ISSUE TITLE
HTML5 export when opening in Browser gives Erro: features required to run Godot projects on the Web are missing

### ISSUE THREAD

**Issue by RDaneelOlivav** [godotengine/godot#81207]
### Godot version

4.1.1 stable tag

### System information

Ubuntu 20, NVidia 1680, 32 GB RAM

### Issue description

WHen starting the game HTML5 in a browser with python HTTP server, gives this errors:

```
  Error
  The following features required to run Godot projects on the Web are missing:
  Secure Context - Check web server configuration (use HTTPS)
  Cross Origin Isolation - Check web server configuration (send correct headers)
  SharedArrayBuffer - Check web server configuration (send correct headers)
```

![godoterror](https://github.com/godotengine/godot/assets/4933774/b8068ec8-b258-4e4e-88bf-c0edabf8b0c1)

Is this to be set somewhere that I'm not aware of?

### Steps to reproduce

`python3 -m http.server`

And open the ai_realm.html

### Minimal reproduction project

[HTML5.zip](https://github.com/godotengine/godot/files/12490104/HTML5.zip)

**Comment by Morpheu5** [comment]
Secure Context is generally given by using HTTPS, which I'm not sure how to do with Python's HTTP server. You could try to deploy your project on a proper web server and use a SSL certificate (self-signed may be acceptable, depending on use case).

The other two features depend on the server setting a couple of headers, as explained [here](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_web.html) (I think there's even a solution for using Python, there).

HTH.

**Comment by Calinou** [comment]
Closing per the above comment. You need to send the appropriate headers as mentioned in the error message. See [serve.py](https://github.com/godotengine/godot/blob/master/platform/web/serve.py) for an example of a Python script that does this.

**Comment by opyate** [comment]
> Secure Context is generally given by using HTTPS, which I'm not sure how to do with Python's HTTP server.

I made a web server which automatically creates secure certificates/keys for local TLS.

https://gist.github.com/opyate/6e5fcabc6f41474d248613c027373856

> You need to send the appropriate headers as mentioned in the error message

@Calinou it's not just about headers, but also about "Secure Context", so TLS is needed. If you want, I can create a PR which updates the provided serve.py with something a bit more developer-friendly (i.e. creates the cert/key automatically).

**Comment by DearFox** [comment]
<s>Are there any issues regarding the server that runs Godot for testing web games?
You can set it up from localhost to 0.0.0.0 so that everyone on your local network can access it, but the game will still give an error due to the lack of https

It seems to me that using a python server is not a solution to the problem, but a crutch.</s>

In fact, you can use godot to run your web game on a local network! And you don't need python or anything else to do this.

1) Open "Editor Settings" > "Export" > "Web"
<img width="805" height="656" alt="Image" src="https://github.com/user-attachments/assets/05fcf28f-5e3e-4992-852b-20f297919b63" />

2) Change the "HTTP Host" parameter to "0.0.0.0" (this will open a connection to the local server from any devices on your local network, just keep this in mind).

3) Turn on "Use TLS"
<img width="804" height="658" alt="Image" src="https://github.com/user-attachments/assets/469f1d2b-1b02-4c7b-9ddd-72e60385cf7c" />

4) Start the server in godot, or restart it if it was already running.
<img width="308" height="137" alt="Image" src="https://github.com/user-attachments/assets/ae1d1ef9-5ef7-44db-bb84-d68b68aac063" />

The browser will complain about the site using an unknown SSL, but you can accept the risk and the game will work. I was able to test my game on a phone this way, and it worked. Just keep in mind that you must specify "tmp_js_export.html" in the URL.
For example, my PC has a local IP address "192.168.0.10", so I should open "`https://192.168.0.10:8060/tmp_js_export.html`".
