### ISSUE TITLE
Mipmap bias slider in the project settings no longer has any effect

### ISSUE THREAD

**Issue by AlfonsoGrimaldo** [godotengine/godot#81214]
### Godot version

v4.2.dev.custom_build [549fcce5f]

### System information

Windows 10, Vulkan, GTX 960 537.13

### Issue description

https://github.com/godotengine/godot/assets/48926464/2be7d140-97c9-4b6d-9c82-0d741401393a

### Steps to reproduce

I think the video shows enough.

### Minimal reproduction project

N/A

**Comment by Calinou** [comment]
This checks out with what I reported while testing [FSR 2](https://github.com/godotengine/godot/pull/81197). That PR may have fixed the issue, I haven't checked yet.

**Comment by AlfonsoGrimaldo** [comment]
@Calinou I specifically realized it while testing that PR.
FSR 2 Scaling 33%
![screenshot1](https://github.com/godotengine/godot/assets/48926464/b5f125cf-88a7-494c-b347-2116f9b538d5)

**Comment by Calinou** [comment]
It almost looks like positive mipmap LDO bias is being applied instead of negative LOD bias.

**Comment by DarioSamo** [comment]
I get the feeling it's not exactly a positive bias but rather it's not really doing anything.

I'll verify what sampler it's retrieving exactly for rendering.

**Comment by AThousandShips** [comment]
Does it work after a restart?

**Comment by DarioSamo** [comment]
RenderDoc shows it's just picking the sampler with no mipmap bias.

The problem is the renderer picks the uniform bindings of the default samplers that have no bias applied.

There's a _custom_ set shared with other things, but frankly that design seems prone to problems as the viewports can't apply their own mipmap bias individually.

Perhaps material storage should be able to create samplers on demand with the bias required by the renderer.
