### ISSUE TITLE
[3.0] - Ideas

### ISSUE THREAD

**Issue by berserk82** [godotengine/godot#8124]
Please, add some AI facility such as: neural networks, behaviour trees. These should not be full implementations, but allow these to be implemented in scripting with ease.
Also, I don't know if terrains are still used today, but it would be cool to see them in.
Finally, physics should be enhanced with fluids and soft bodies.

Please, share your toughts.

**Comment by eon-s** [comment]
3.0 is too close, maybe 3.1...

AI, there are infinite ways to implement in Godot, more now with DLScript because we can implement existing external libraries that may be more efficient.

Terrains, yes, there are some terrain tools I would love to see in the core, I will like to see GridMap at the level of TileMap too.

I believe soft bodies are planned for later and fluid physics will be nice to see, at least something like LiquidFun.

--------------------

For 3.0 we need a official way to centralize tutorials and tutorial requests, maybe linked to the asset lib or internal help...

**Comment by bojidar-bg** [comment]
@berserk82 BTW, with that issue title, you are basically asking to get it closed...

Would you mind to:
1) Search existing issues (I'm absolutely sure there are some for softbodies and terrains) for the requests you have, and comment/:+1: them,
2) Remove those point that were covered by them for this issue,
3) Leave only one point in here, and
4) Open other issues for the leftover points?

That way, we can keep the discussion focused, and also, give developers to just hit "Close issue" after a  day's worth of hard work, sit back, and relax.

P.S. Please check ["I have a great idea that will make Godot better, What do you think?" in the well-hidden FAQ](http://docs.godotengine.org/en/latest/reference/faq.html#i-have-a-great-idea-that-will-make-godot-better-what-do-you-think) too, since it is probable that some parts of this issue would fall under it.

**Comment by kubecz3k** [comment]
I think @bojidar-bg comment was detailed enough, I will archive this issue. However you might continue loose discussion here if you want :)

**Comment by kubecz3k** [comment]
As a sidenote: Godot devs are totally aware of the fact that these things exists in some other engines and they totally will implement them for sure at some point of time. Furthermore some of those are already considered for 3.1 :)

**Comment by berserk82** [comment]
Thanks for your 2 cents.
I just wanted to know exactly what I knew.

**Comment by berserk82** [comment]
May I know which of these are considered for 3.1?
