### ISSUE TITLE
Movie mode recording in 2D HDR is not as good as expected.

### ISSUE THREAD

**Issue by scgm0** [godotengine/godot#81301]
### Godot version

v4.2.dev.mono.custom_build [75de1ca76]

### System information

Godot v4.2.dev.mono (75de1ca76) - Arch Linux #0~20230903.g20dcd95 SMP PREEMPT_DYNAMIC Sun Sep  3 05:16:45 UTC - Wayland - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1650 (nvidia; 535.104.05) - Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 Threads)

### Issue description

2D HDR on, no restarting:
![图片](https://github.com/godotengine/godot/assets/52148221/0be6373a-d839-4403-90ca-7d5c8ac2e8f0)
2D HDR on, restarting:
![图片](https://github.com/godotengine/godot/assets/52148221/113a5e35-d375-4261-ae66-b7422cd8365e)
Movie mode recording output:
![图片](https://github.com/godotengine/godot/assets/52148221/2f87de24-e730-4217-9d16-d9c776056855)
(I have run out of Deepl translations, please understand...)

### Steps to reproduce

1. Turn on 2D HDR, and simply configure the scene to highlight the 2D HDR effect.
2. Record video with movie mode.

### Minimal reproduction project

N/A

**Comment by torcado194** [comment]
I've confirmed this on v4.2.dev3.official [013e8e3af]

I tried looking into a solution to this for a few days but couldn't get anything working. 
My guess is that this is due to the tonemapping godot does on the output, as mentioned [here](https://docs.godotengine.org/en/stable/tutorials/3d/high_dynamic_range.html): 
> Godot does not support high dynamic range output yet. It can only perform lighting in HDR and tonemap the result to a low dynamic range image.

... the issue being that this tonemapping is done for the window viewport but *not* for the texture sent into the `movie_writer`, but I'm not sure.

----

In the meantine, you can work around this issue by using a shader to manually convert from linear to sRGB space for movie mode only:

```glsl
shader_type canvas_item;
global uniform bool MOVIE;
uniform sampler2D screen_texture : hint_screen_texture;

void fragment() {
	COLOR = texture(screen_texture, SCREEN_UV);
	if(MOVIE){
		COLOR.rgb = pow(COLOR.rgb, vec3(1.0/2.2));
	}
}
```

(this will cause the displayed image to be incorrect, but the recorded movie will be closer to the intended result) 

| without workaround | with workaround |
| :---------------------: | :------------------: |
| ![image](https://github.com/godotengine/godot/assets/9218934/aaeddddb-d294-4b22-a4d9-41c1b495240b) (correct) display in-editor | ![image](https://github.com/godotengine/godot/assets/9218934/a5c35af7-f32c-454f-8baa-82a30e15ca07) display while recording movie |
| ![image](https://github.com/godotengine/godot/assets/9218934/01e3a3c3-7c20-48ce-8184-d43aa3422b40) movie recording without workaround | ![image](https://github.com/godotengine/godot/assets/9218934/f305c540-2675-4b4e-86df-c3ef0d8e70ba) movie recording with workaround |


----

Here's an MRP with the issue and the workaround:

[hdr-movie-mode-mrp.zip](https://github.com/godotengine/godot/files/12566281/hdr-movie-mode-mrp.zip)

**Comment by torcado194** [comment]
reason for issue confirmed here (I believe)
https://github.com/godotengine/godot/issues/82351#issuecomment-1735493143

**Comment by clayjohn** [comment]
This is essentially the same issue as https://github.com/godotengine/godot/issues/82351

**Comment by Calinou** [comment]
It should be possible for MovieWriter to automatically perform the linear-to-sRGB conversion depending on whether 2D HDR is enabled. Relevant code is here: https://github.com/Calinou/godot/blob/0a8d64d54de3279ab3cad9b831b2551b4881d9a5/servers/movie_writer/movie_writer.cpp#L172-L196

**Comment by torcado194** [comment]
@Calinou I couldn't figure out what methods to use to convert a texture from linear to sRGB, if any exist. There are automatic conversion methods in `Color`, and some shaders with sRGB conversion options, but nothing for textures that I could find. I saw that some TextureStorage methods have an `srgb` parameter, such as `TextureStorage::texture_get_rd_texture`, but I couldn't get that working in that callback, and even if I did it doesn't seem like it would do what I'm looking for.

If you have any pointers there, that would be appreciated!

**Comment by Calinou** [comment]
You will probably need to loop over the image's individual pixels and convert them to sRGB.

**Comment by torcado194** [comment]
Hm, alright. I would be worried about performance at that point, perhaps a shader is the best solution for now. Though, I haven't tested it.
Thank you for the input!

**Comment by h0lley** [comment]
I think rendering a video in sRGB color space is by far the more common and expected use case.

we've been trying out movie maker mode recently to render a trailer.
despite movie maker mode seemingly being ideal application for that, we gave up on using it because our game uses 2D HDR and the results where unexpected.

alternatively to automatic conversion, a warning hint when enabling movie mode combined with a link to docs explaining how to convert your video could be a satisfactory solution, too.
