### ISSUE TITLE
Flickering when moving past sprites with camera zoomed in

### ISSUE THREAD

**Issue by ArcFutahito** [godotengine/godot#8131]
Godot v 2.1.2. x64 Linux Kubuntu 16.10

When using camera zoom in 2D and moving character all static sprites start to flicker. 

Example project: [Bad Zoom.tar.gz](https://github.com/godotengine/godot/files/867207/Bad.Zoom.tar.gz)

**Comment by eon-s** [comment]
Using Gnome here...

I don't notice any flicker but the classic old stutter, what is weird is it affects the static sprite instead of the moving one.

**Comment by ArcFutahito** [comment]
Whatever you call it, it's pretty bad. I was drawing my sprites with intention to zoom in camera so this one is game breaker for me =\

**Comment by eon-s** [comment]
@ArcFutahito is like this #2043 ?
You see the same effect in maximized window and fullscreen? (in my case, maximized reduce bad visual the effect)

**Comment by ArcFutahito** [comment]
It's more of a graphical glitch. You see pixels not moving properly, if that makes sense to you.

**Comment by DenisComtesse** [comment]
Runs perfectly smooth for me (Godot 2.1.2, Xubuntu 16.10). No flickering, no stuttering. The only thing I notice is a certain moiré-effect, because of the strong patterns in the background sprites. If this is what you mean with "flickering", it's perfectly normal if you zoom in sprites with such patterns. It can be reduced by setting the filter flag for the sprite, so it scales more smoothly when you zoom in.

**Comment by ArcFutahito** [comment]
This moire effect is there no matter how strong the pattern is. Even just having a plain sprite, you see it's borders go all over the place.

**Comment by DenisComtesse** [comment]
Can't confirm that. I have just tested the Platformer demo, which uses pixel art. I changed the camera zoom and changed the window size, and it all looks fine.

**Comment by eon-s** [comment]
Forgot that I was using nouveau drivers, changed to the proprietary ones and the motion is perfect (at least on X11 with Gnome Shell).

**Comment by ArcFutahito** [comment]
@DenisComtesse So hard to record it without codecs smoothing it all out. https://www.youtube.com/watch?v=XZrQOT7McyA
If you look very closely you can actually see pixels shift not only on tiles but on trees too

**Comment by DenisComtesse** [comment]
Sorry, but this is absolutely normal. If you zoom into pixel art without filtering it, you get slightly uneven pixel sizes, because there's no such thing as half pixels. This is simple maths, the pixels just can't all be of the same size (unless you zoom at integer levels like x2, x3, x4...).  
If you zoom in so that your original pixels in theory should be 2.5x2.5 pixels big, you'll end up with some pixels being 2x2, others being 2x3, 3x2 or 3x3.
The only thing you can do about it is use the filter, which gives a more uniform result, also blurs the pixels a little - that's a matter of taste: smoothness vs. sharper pixels.
And the only thing the Godot developers could do about this is offer more filtering options (not sure what Godot uses and if there are better options?). But it's not a bug, it's just how things work.

**Comment by ArcFutahito** [comment]
Even when zooming in with values like 0.6 this flickering is present.

**Comment by DenisComtesse** [comment]
Of course it is. Setting the zoom to 0.5 will result in a nice even 2x2 pixel size (if you don't change the scale of your sprites), 0.25 will give you 4x4 pixels, 0.1 will give you 10x10 etc.
But if you set the zoom to 0.6 everything will be scales by 1/0.6 = 1.6666..., so you will always have uneven pixels. Once again, try setting the filter flag for your textures if you want to avoid it.

**Comment by ArcFutahito** [comment]
Oh my god I'm such a moron. You are totally right and I was a complete idiot all along. For some reason I was thinking that even values would work but that's totally not how math works.

Scaling I don't really need so there's no problem. Thank you so much.
