### ISSUE TITLE
Addon is empty after downloading from asset lib

### ISSUE THREAD

**Issue by IceflowRE** [godotengine/godot#81311]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.3667) - AMD Ryzen 9 7900X 12-Core Processor (24 Threads)

### Issue description

This [addon](https://godotengine.org/asset-library/asset/1989) is shown as empty when downloaded via the editor. If downloading from the website everything works fine and there is content in the zip file.
![image](https://github.com/godotengine/godot/assets/10883690/259f114a-6ac0-4dd2-b71f-75c35d91ba85)

The asset uses `Custom` as repository host, linking with URL to `https://github.com/kenyoni-software/godot-addons/releases/download/hide_private_properties-1.0.1/hide_private_properties-1_0_1.zip`

### Steps to reproduce

Go to the Asset Lib and download [Hide Private Properties](https://godotengine.org/asset-library/asset/1989).

### Minimal reproduction project

N/A

**Comment by IceflowRE** [comment]
Might be related https://github.com/godotengine/godot/issues/75712

**Comment by YuriSizov** [comment]
> Might be related #75712

Indeed, it's the same issue. Basically, we expect the ZIP to follow a certain structure which generated ZIPs do follow. It needs to have a root folder inside of it, which contains the actual contents. And your ZIP has its content at the top level instead. So the parser logic breaks.

I'm going to close this as a duplicate, but thanks for an example!

**Comment by YuriSizov** [comment]
Actually, I've tested this a bit more, and the issue seems to be different. For your archive the our ZIP library cannot extract folders as individual records. It only extracts full paths to files in them. For ZIPs downloaded from GitHub, for example, folders are extracted as individual records, and it's done in order (so folders are guaranteed to be before the files in them).

I'm going to reopen this report.
