### ISSUE TITLE
Area3D doesn't detect any bodies if it's fully inside them

### ISSUE THREAD

**Issue by CammiePone** [godotengine/godot#81316]
### Godot version

4.1.1

### System information

Windows 10

### Issue description

When an Area3D is fully inside another object, it doesn't detect as overlapping with that object. It's actually causing a bit of a problem when trying to detect if a rigidbody is on the ground.

### Steps to reproduce

Create an Area3D, attach a script to it, and print from `_process` or `_physics_process` `get_overlapping_bodies()`
Put it partially inside an object, and it'll print that object no problem
Put it all the way inside, and it'll print nothing

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please provide a minimal reproduction project to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the above required information this can be reopened

**Comment by dicemaster5** [comment]
I'm currently having this issue too.
Area3D.has_overlapping_bodies() seems to only detect when it intersects with a collider and never when the Area3D is completely inside a collider.

Moving an Area3D inside of a collider with no intersecting edges, and then checking has_overlapping_bodies() always returns false from my testing.

It would be great if this issue could be re-opened for further testing and inspection by the community.

**Comment by ScatteredComet** [comment]
Hi,

I was experiencing this issue too during developing a game. I copy pasted the scene into a new project and the area3d is still broken. Interestingly, a seemingly identical setup created in the fresh project does not have the same issue.

---

Here is the MRP

[area3d-no-detection-when-enclosed-to-zip.zip](https://github.com/user-attachments/files/20882860/area3d-no-detection-when-enclosed-to-zip.zip)

My system info is as follows:
Godot v4.4.1.stable.mono - Pop!_OS 22.04 LTS on X11 - X11 display driver, Multi-window, 1 monitor - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 XT (RADV NAVI23) - AMD Ryzen 5 5600 6-Core Processor (12 threads)

---

Steps to use MRP:

1. turn on visiblecollisionshapes in the debug tab (this is NOT necessary for the bug, but it allows us to visually see whats occuring)
2. set main scene to workingareas & run. An object will fall into an area3d. Each frame GetOverlappingBodies() will be printed from the area3d, and the output is as expected
3. set main scene to brokenareas & run. The same events will occur, but once the area3d is fully enclosed within the area3d, GetOverlappingAreas() will print nothing.

---

The issue seems to be present with both csharp and gdscript (the above MRP uses gdscript)

If things aren't working as expected or anything doesn't make sense let me know and I will do some more digging.

**Comment by BenBlueeeee** [comment]
for some reason i cant edit my comment to include the zip, here it is

[area3d-no-detection-when-enclosed.zip](https://github.com/user-attachments/files/20882785/area3d-no-detection-when-enclosed.zip)

**Comment by ScatteredComet** [comment]
i just tested the zip on my machine, and it still showed the broken behaviour, so i assume the issue is not anything to do with the .godot folder etc. I looked superficially at the contents of the 2 scene files "WorkingAreas" and "BrokenAreas", but am yet to find a cause.

**Comment by ScatteredComet** [comment]
i think i found it:

in "BrokenAreas.tscn"
- cntrl+f and replace "ConvexPolygonShape3D" -> "ConcavePolygonShape3D"
- cntrl+f and replace "data" -> "points"

this fixes the broken scene and the GetOverlappingBodies() then works as intended in BrokenAreas.tscn.

---

so i guess some questions would be

- does it make sense that having an area3d with a convexpolygonshape would break things?
- how did i manage to create a scene that has one?

I dont think I can remember how I managed to create this given area3d which is a shame. Perhaps some check can be done to make sure this situation doesn't arise? That would probably be a bodge though, it would be nice to be able to reproduce this issue in the editor from a fresh project (unlike what I did of copy pasting a broken scene). But at least we have an idea for how to fix it.

**Comment by ScatteredComet** [comment]
maybe my fix was slightly wrong actually, but I think its something to do with changing convex <-> concave and data <-> points

**Comment by ScatteredComet** [comment]
I now believe all of this is intended behaviour

https://docs.godotengine.org/en/stable/classes/class_convexpolygonshape3d.html

> ConvexPolygonShape3D is solid, which means it detects collisions from objects that are fully inside it, unlike [ConcavePolygonShape3D](https://docs.godotengine.org/en/stable/classes/class_concavepolygonshape3d.html#class-concavepolygonshape3d) which is hollow. This makes it more suitable for both detection and physics.

Maybe OP had a different bug, but it sounds like it could just be that the collisionshape generated was of the incorrect type.
