### ISSUE TITLE
Zooming in the script editor freezes the editor

### ISSUE THREAD

**Issue by Chaosus** [godotengine/godot#81397]
### Godot version

8449592d92eaeef990f5502b419d491ee3eeb7a6

### System information

Windows 11

### Issue description

Zooming in the script editor on an empty script freezes the entire editor for a few seconds, but if the file is large then it freezes for 4-5 seconds (which is unacceptable). Looks like a recent regression.

### Steps to reproduce

Just zoom in/out on the large script file.

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
I run an test with around a gdscript with around 200 lines, zoom in and out for a while, this is intel vtune's report of my test:

![image](https://github.com/godotengine/godot/assets/8315986/f3f53888-db71-4126-899c-5fa47895b937)

It seems `Control::set_theme` is the hotspot here.

**Comment by bruvzg** [comment]
Seems like something is wrong with theme propagation:

<img width="1186" alt="Screenshot 2023-09-07 at 10 01 50" src="https://github.com/godotengine/godot/assets/7645683/a241f2a3-d8d8-4573-9014-8616ff8b1597">

But bisects to the https://github.com/godotengine/godot/pull/79166 (I guess can be fixed by reintroducing checks as recursive), but theme propagation probably do excessive font updates as well.

**Comment by Chaosus** [comment]
Fixed by https://github.com/godotengine/godot/pull/81406
