### ISSUE TITLE
Path3D - Handle Tilt untouchable

### ISSUE THREAD

**Issue by AntohaRDNS** [godotengine/godot#81412]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Windows10 - Vulkan 

### Issue description

When editing Path 3D, the handle tilt of the selected control point is not selectable -  when trying to select it from one side of the circle gizmo, but on the other side it can be selected

### Steps to reproduce

1. Create Path3D Node
2. Add control points
3. Select one control point
4. Select "Select Control Points" Tool
5. Try to tweak Handle Tilt from one side, then from other side

### Minimal reproduction project

[HandleTiltTest.zip](https://github.com/godotengine/godot/files/12549020/HandleTiltTest.zip)

**Comment by bitsawer** [comment]
I can repro this, looks like this is a pretty new feature added in https://github.com/godotengine/godot/pull/80329, so maybe some usability tweaks are still needed. Currently the tilt handle adjustment is also pretty finicky depending on the view angle.

**Comment by Calinou** [comment]
> Currently the tilt handle adjustment is also pretty finicky depending on the view angle.

More generally, it's also difficult to grasp the actual depth of the point/curve tangent/tilt handle you're grabbing. I suppose drawing 3 axis-aligned lines that follow the selected point could help here, with the lines being drawn twice (one mostly opaque line, one mostly transparent line with depth test disabled).

**Comment by Nitricswight** [comment]
there are also issues with selecting the control points from top down because the tilt handles get in the way. Maybe an option with the "mirror handle" options to hide the tilt handles?

**Comment by daddyolympus** [comment]
Selecting the control points from top down is indeed impossible.

**Comment by Antonio89743** [comment]
This is still a problem and it's quite annoying. If you're dealing with a shape that is pretty symmetrical just using the bottom up view is fine, but if the shape isn't symmetrical and you need to look at the top of the shape you can't simply use the top down view and drag the points to your liking since it results in you messing with the tilt instead. 
A work around is to temporarily go into bottom up view and from there drag out the control points just so that they aren't in the same spot as tilt control points, only then shifting to top down view and moving the points as you like, and you have to do this always, manually and for every single point you want to use. 
Honestly, why not have separate controls, say shift + drag allows you to handle in/out points while middle mouse button while dragging controls tilt.

**Comment by Snaiel** [comment]
The following pr resolves the problems discussed in this issue right?
- https://github.com/godotengine/godot/pull/89847

**Comment by Calinou** [comment]
This is indeed resolved as of 4.3.beta2:

https://github.com/godotengine/godot/assets/180032/f125606b-a005-4ffa-a6a9-233c49560149
