### ISSUE TITLE
Add node odd behaviour

### ISSUE THREAD

**Issue by GhoulFool** [godotengine/godot#81413]
### Godot version

4.1.1.stable.official [bd6af8e0e]

### System information

Windows 7

### Issue description

![image](https://github.com/godotengine/godot/assets/25694861/12797458-4382-40c7-b5bd-918ed613f025)

In adding Area node 2d  the list of matches added an existing node of my own to list. Not sure why. haven't been able to replicate this. Did grab a screenshot and thought I'd bring it to people attention.

### Steps to reproduce

N/A

### Minimal reproduction project

N/A

**Comment by Zireael07** [comment]
Without a minimal reproduction project the team will be unable to help you.

Did you use class_name in that script?

**Comment by AThousandShips** [comment]
Please provide a minimal reproduction project:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the above required information this can be reopened
