### ISSUE TITLE
Can't access node by %UniqueName after .reparent()

### ISSUE THREAD

**Issue by KoB-Kirito** [godotengine/godot#81480]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Godot v4.2.dev4 - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3623) - Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 Threads)

### Issue description

After reparenting a node, you can't access it anymore by it's unique name %.
I would expect the unique name to still point to the node.

### Steps to reproduce

- Make node accessable by unique name
- Reparent node at runtime `reparent()`
- Try to access by unique name

### Minimal reproduction project

N/A

**Comment by AThousandShips** [comment]
Please provide a minimal reproduction project to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by KoB-Kirito** [comment]
[unique_reparent.zip](https://github.com/godotengine/godot/files/12565595/unique_reparent.zip)

**Comment by Mickeon** [comment]
At the end of the day, `reparent()` removes the child and adds it to the new parent. It's a combination of `remove()` and `add_child()`. Because of this, the node's `owner` is set to **null**. The node's `unique_name_in_owner` is still **true**, but not that doesn't matter. Manually setting the owner back to what it was fixes the issue.

I am not sure if it can be classified as a bug, because I'm struggling to think of occasions where you'd NOT want the owner to be kept when reparenting.

##### Below is yet another, more vented opinion.
This rather feels like a flaw of a multitude of stuff about Unique Nodes/Names. The implementation, lack of proper documentation, use of arbitrary exceptions all around the codebase. The underlying base of this has been somewhat shoddy, I always felt.

**Comment by KoB-Kirito** [comment]
Whatever the underlying mechanism. Logically you just move the node inside the tree.

**Comment by KoBeWi** [comment]
I think `reparent()` should try to keep the `owner`.
