### ISSUE TITLE
uppercase letters in filenames cause code to not work properly

### ISSUE THREAD

**Issue by midiidev** [godotengine/godot#81520]
### Godot version

4.1.1

### System information

Godot v4.1.1.stable unknown - Arch Linux #1 ZEN SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:00:40 +0000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (nvidia; 535.104.05) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Having a script with an uppercase letter in its filename causes the code to "half run." Everything seemingly works up until the `move_and_slide()` function in the character code. 

### Steps to reproduce

1. new Godot project
1. create a 3D node as well as a child with something for the player to stand on (maybe a CSGBox3D)
1. create a basic character as another child of the 3D node (name it "Player")
1. add the default script to the player (`res://scripts/Player.gd`)
1. run it (the player will not move)
1. rename the file to be `player.gd`
1. the player should move now

### Minimal reproduction project

[FPS Tutorial.tar.gz](https://github.com/godotengine/godot/files/12569815/FPS.Tutorial.tar.gz)

**Comment by jtiai** [comment]
By inspecting provided project there are couple for possible culprits:

In world there is CSGBox3D which uses generated collider and that shape is scaled. Instead of scaling using size parameters in CSGBox3D group fixes partially the problem.

Player seemed to have very sharp edged capsule liked (more like crystal shape) changing it also capsule seemed to have a difference. I guess that the main problem is the first one.

**Comment by Zireael07** [comment]
Letter casing shouldn't have an effect on scripting. @jtiai is likely right that it's ab unrelated physics issue and casing is a red herring

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this issue on the latest Godot version.
