### ISSUE TITLE
Using C# and Visual Studio Code produces weird references in the VSCode editor

### ISSUE THREAD

**Issue by LordBrkica** [godotengine/godot#81585]
### Godot version

4.1.1 stable

### System information

Windows 11

### Issue description

The problem is maybe not related to Godot directly, but Visual Studio Code is an open source tool used by a lot of people so I decided to post it here anyway.

The problem is in intelissense, it generates references to files I do not use.

Please see image below:
![image](https://github.com/godotengine/godot/assets/51578785/0f796356-3000-4066-80bc-de9fb10bb5a4)

So there is a variable called "_velocity" and I use it once. There is 1 real reference to this variable in my code.

But as can be seen from the image, there are 4 additional reference to "_velocity" in some _\Godot.SourceGenerators\blabla..._ files.

This applies to almost every variable that I have not just "_velocity", so if I add a new varible to class I will get the same behaviour:
![image](https://github.com/godotengine/godot/assets/51578785/0a8250b8-e460-40b3-bdf4-4e42c9db3e89)

I assume those files do not concern us directly but are rather used by the engine itself.

Is there a way to disable the references to those files ?

I tried via VScode Preferences->Settings-> files.exclude but I failed to get rid of them.

### Steps to reproduce

See above.

### Minimal reproduction project

N/A

**Comment by raulsntos** [comment]
> I assume those files do not concern us directly but are rather used by the engine itself.

Yeah, that generated source code is used to communicate with the engine. But the code is still part of your project, even if it's generated, and you still have access to it. So the references are just as real as references in your own code.

> Is there a way to disable the references to those files ?

Not that I know of, but it's a common request (see https://github.com/godotengine/godot/issues/77128). This would be VSCode's responsibility though, they should already be able to differentiate between generated and non-generated files.

I'll close this issue since there's nothing we can do on our side.
