### ISSUE TITLE
Incorrect Node3D transform when moving and rotating with the gizmo in local space if parent node's coordinates are not in (0,0,0)

### ISSUE THREAD

**Issue by raccoon-path** [godotengine/godot#81604]
### Godot version

v4.2.dev4.official [549fcce5f]

### System information

Windows 10 - Godot v4.2.dev4.official - Vulkan (Forward+) editor

### Issue description

Version **4.2-dev4** introduced incorrect behavior when transforming nodes in local space (Node "jumps" to unwanted position). In the previous version everything works correctly.

https://github.com/godotengine/godot/assets/97123013/d098cfc9-6a34-4674-b042-2ef74f4a46b8

### Steps to reproduce

1. Create any **Node3D**
3. Add any child **Node3D**
4. Move parent node away from **(0,0,0)** or/and rotate it
5. Enable **"use local space"**
6. Try to move child node with gizmo and see undesired behavior when transforming

### Minimal reproduction project

[translate_localspace_editor_bug.zip](https://github.com/godotengine/godot/files/12593837/translate_localspace_editor_bug.zip)

**Comment by AThousandShips** [comment]
Looks related to:
* https://github.com/godotengine/godot/issues/80685

Will take a look

**Comment by kleonc** [comment]
Since this is a regression introduced in 4.2.dev4 the question should be what caused it.

Looking at the changes since 4.2.dev3 I suspect it's caused by #58389 (haven't tested though). cc @rcorre
Specifically the `Node3DEditorViewport::apply_transform` method factored out in there seems to be not replacing the previously existing code one-to-one, there are small discrepancies:
https://github.com/godotengine/godot/blob/5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8/editor/plugins/node_3d_editor_plugin.cpp#L4635-L4642
vs original:

- When scaling (this seems one to one):
https://github.com/godotengine/godot/blob/7df393312fa8eab98231f2c335366a1ef6205367/editor/plugins/node_3d_editor_plugin.cpp#L4695-L4702
- When translating (no `if (!local_coords)` check (likely the exact cause of this issue), last arg differencies for `_compute_transform` calls):
https://github.com/godotengine/godot/blob/7df393312fa8eab98231f2c335366a1ef6205367/editor/plugins/node_3d_editor_plugin.cpp#L4798-L4803
- When rotating (last arg differencies for `_compute_transform` calls):
https://github.com/godotengine/godot/blob/7df393312fa8eab98231f2c335366a1ef6205367/editor/plugins/node_3d_editor_plugin.cpp#L4900-L4907

**Comment by AThousandShips** [comment]
Will look at restoring parity, thank you!

**Comment by kleonc** [comment]
> Will look at restoring parity, thank you!

Note it might be the case that some of the dicrepancies in the pre-#58389 code might have been a result of patching things separately etc. By any chance I'm not saying these parts need to be reverted to the previous state, maybe unifying them like it's done now is the way to go. I just have no idea if/what could have been broken by the mentioned changes. :upside_down_face:

**Comment by AThousandShips** [comment]
The current change fixes the bug but will see if there's other issues with that

**Comment by AThousandShips** [comment]
The last arg for the translation case doesn't affect anything as the orthogonal arg is unused there
