### ISSUE TITLE
Android Gradle Build fails with error "Attempting to parent and popup a dialog that already has a parent."

### ISSUE THREAD

**Issue by joyhillgames** [godotengine/godot#81613]
### Godot version

4.1.1 (tested with 4.2 dev 4 as well)

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

Getting following error output when trying to export Android gradle build. Non-custom builds work just fine.

```
Attempting to parent and popup a dialog that already has a parent.
0 param: --xr_mode_regular
1 param: --use_immersive
  editor/export/editor_export_platform.h:178 - Export: Building of Android project failed, check output for the error. Alternatively visit docs.godotengine.org for Android build documentation.
```

Followed instructions precisely in official documentary. JDK and Android studio installed with necessary packages. Tested with JDK11 and JDK20. Happens on both.

### Steps to reproduce

- Take necessary steps for Android export described [here](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html)

- Create Android export template and tick "use gradle build" and try to export.

### Minimal reproduction project

N/A

**Comment by manake** [comment]
### Godot version
4.1.1.stable

### System information
- Windows 11
- Android Studio Giraffe
- SDK Platform v34 (latest)
- Command line tools v11.0 (latest)
- CMake 3.22.1 (latest)
- Android Emulator 32.1.15 (latest)
- Android SDK Platform-Tools 34.0.4 (latest)
- Intel x86 Emulator Accelerator (HAXM installer) (latest)
- Open JDK delivered by Unity 2023.1.12f1/Editor/Data/PlaybackEngines/AndroidPlayer/OpenJDK/keytool.exe

### Issue description
1. I just want to **export an Android project for Android Studio** (NOT build APK).
2. But I'm getting the same error as OP.
3. My project is completely empty.

<img width="1626" alt="godot" src="https://github.com/godotengine/godot/assets/6874031/b39b6b99-3642-4fe9-a3e7-ff39f44fe37e">

**Comment by heptadecimall** [comment]
> ### Godot version
> 4.1.1 (tested with 4.2 dev 4 as well)
> 
> ### System information
> Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated AMD Radeon RX 6700 XT (Advanced Micro Devices, Inc.; 31.0.12027.9001) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)
> 
> ### Issue description
> Getting following error output when trying to export Android gradle build. Non-custom builds work just fine.
> 
> ```
> Attempting to parent and popup a dialog that already has a parent.
> 0 param: --xr_mode_regular
> 1 param: --use_immersive
>   editor/export/editor_export_platform.h:178 - Export: Building of Android project failed, check output for the error. Alternatively visit docs.godotengine.org for Android build documentation.
> ```
> 
> Followed instructions precisely in official documentary. JDK and Android studio installed with necessary packages. Tested with JDK11 and JDK20. Happens on both.
> 
> ### Steps to reproduce
> * Take necessary steps for Android export described [here](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_android.html)
> * Create Android export template and tick "use gradle build" and try to export.
> 
> ### Minimal reproduction project
> N/A

I do have this issues yesterday...so i fix it already this morning...what i do is (godot 4.1.1):
- I setup the JAVA_HOME to  jdk 11 directory
- I download the latest android sdk platform 34
- set the android sdk path at godot export editor setting
- restart the engine and bom..build success

**Comment by YuriSizov** [comment]
Note that the "Attempting to parent and popup a dialog that already has a parent." message is a red herring. It's just an editor issue when trying to show you the error, but it's not the error itself. Your logs show that it fails at first without "Attempting to parent and popup a dialog that already has a parent.", but subsequent failures show this message (which makes sense for this error).

The issue is with building of the Android project, though I'm not sure where you can find the exact cause of it.

**Comment by manake** [comment]
Sure, I know.

It seems `gradlew <command>` is failing to execute because it presumably gets wrong parameters in https://github.com/godotengine/godot/blob/master/platform/android/export/export_plugin.cpp#L3021

This error is completely blocking my work.
It's a very core/essential functionality that is not working.
I installed GoDot for the first time ever 2 days ago, with only one goal, of testing how Gradle project export looks. If it looks good (if `GoDot <-> Android Studio` bridge exists for example, like it does in Unity, etc.) then I could be using GoDot.

What happens next?
Is this going to be assigned some "priority" and "milestone"?
Will someone have a look at it soon? In 1 week? In 1 month?
Or should I better try to debug it myself?

**Comment by Calinou** [comment]
> Is this going to be assigned some "priority" and "milestone"?

In open source, people work on what they want to work on :slightly_smiling_face: 

There is no ETA for resolving this issue, as contributors work on a best-effort basis. If you need something to be resolved now, you need to look into resolving it yourself. This is also the best way to learn.

**Comment by mo-vi** [comment]
I got this fixed doing @heptadecimall mentioned.

The problem was that JAVA_HOME was not set correctly

On windows 10/11 search for "View advanced system settings", click Environment variables and then under "User variables for YOUR_USERNAME" check that JAVA_HOME value is ok.

If you downloaded OpenJDK11 from the link of Godot documentation, the path should be C:\Program Files\Eclipse Adoptium\jdk-11.0.20.101-hotspot\ (minor version may differ)

**Comment by joyhillgames** [comment]
OP here. I got it working. Don't know what exactly solved it since I did so many things. I uninstalled Unity, JDK and Android Studio and started from the beginning. I installed JDK 11, latest Android Studio with latest versions of required packages. Then it started working.

**Comment by KilianSteenman** [comment]
Sorry for bumping this old issue, but it would be so helpful if the window that performs the build execution didn't get closed when an error occurs. This makes it impossible to debug issues properly.
