### ISSUE TITLE
Debugging from .NET editor outputs error message when host fxr directory does not exist at expected location

### ISSUE THREAD

**Issue by wlsnmrk** [godotengine/godot#81677]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - SteamOS holo - Vulkan (Forward+) - integrated AMD Custom GPU 0405 (RADV VANGOGH) () - AMD Custom APU 0405 (8 Threads)

### Issue description

I have .NET 7 installed in `~/.dotnet` (default installation location of the current Microsoft `dotnet-install.sh` script). It's on the PATH. Godot Mono, when launched, does not show errors about .NET or hostfxr as the Project Manager comes up, and opens and loads .NET projects without issues.

When debugging any project (with or without .NET elements) from the Godot editor, it builds, launches, and runs correctly. The project can be exported and run as a separate executable with no apparent errors. However, during debugging, in the debugger's error output, the following error appears:
![hostfxr_error_expanded](https://github.com/godotengine/godot/assets/23439518/e251c3f4-dca7-4507-ac3a-717cbb77d6bd)

If I create an empty directory at the indicated location (i.e., `sudo mkdir -p /usr/share/dotnet/host/fxr`), the error no longer appears.

I'm not sure if this is a duplicate of/related to #70510.

### Steps to reproduce

Somewhat speculative, but:
* Have .NET installed somewhere that does not create the `/usr/share/dotnet/host/fxr` directory, but put it on the PATH so Godot will run
* Open a project
* Start Godot's debugger

### Minimal reproduction project

Any runnable project - create an empty node, set it as the main scene, and debug.

**Comment by raulsntos** [comment]
The path `~/.dotnet` is not one of the standard install locations[^1]. Also, please keep in mind that the `dotnet-install.sh` script is not meant to be used to setup a development environment[^2], it's intended for CI scenarios.

However, if the standard hostfxr resolution fails, Godot will fall back to the location of the `dotnet` CLI (if it can find it in the PATH).

Due to the way the hostfxr resolution is implemented, if it fails to find hostfxr in the standard install locations it will print an error, even if it can still find it in the fallback location. This sounds like a duplicate of #70510. If hostfxr was found, everything should still work correctly and the printed error can be ignored.

[^1]: See https://github.com/dotnet/designs/blob/main/accepted/2020/install-locations.md#host-behavior-for-30.
[^2]: Read the purpose section of the `dotnet-install` script documentation: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#purpose

**Comment by wlsnmrk** [comment]
Thanks very much for the pointers. I hadn't seen that reference page for the install script, and had interpreted the remark, "The dotnet-install scripts are used for automation and non-admin installs of the SDK and Runtime," on the [scripted-installation directions](https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#scripted-install) to mean that it was applicable both to automation scenarios and to more general non-admin installations.

Will close as duplicate/not applicable.
