### ISSUE TITLE
Fatal crash when using non zero Sun Scatter in Fog on a WorldEnvironment node in a basic scene.

### ISSUE THREAD

**Issue by SamHaskell** [godotengine/godot#81696]
### Godot version

4.1.1.stable.mono

### System information

Godot v4.1.1.stable.mono - macOS 13.5.2 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

Using the WorldEnvironment node and enabling fog with a non-zero value for Sun Scatter results in instant Vulkan Device Loss upon running the scene, and a rapid accumulation of memory allocations until the application quickly runs out of memory.

Sometimes this has the effect of causing the editor to completely hand too, although this has been more difficult to reproduce.

### Steps to reproduce

Create a new project.
Choose Forward+
Create an empty 3D scene and attach a Camera3D node and WorldEnvironment node.
Create a new environment resource in the WorldEnvironment node.
Enable Fog, and set the Sun Scatter parameter to some non-zero value.
Hit Run Current Scene / Run Project.

### Minimal reproduction project

N/A

**Comment by bitsawer** [comment]
Thanks for the report. I can repro this with 4.1.1 but not with 4.2 dev4 or current master, so looks like it has been fixed in master. Closing as completed. You can try the latest 4.2 dev4 release https://godotengine.org/article/dev-snapshot-godot-4-2-dev-4/#downloads If it still crashes with that, feel free to comment or re-open this issue.
