### ISSUE TITLE
Looped animations can't transition automatically in state machine

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#81715]
### Godot version

5f1e56ff26be4070496aa51095b9ac2f2b4f4ed8

### System information

Windows 11

### Issue description

The state machines AnimationNodeAnimations appears to have broken in several ways. Firstly, the AtEnd transition no longer works for animations marked as looping or ping-pong, and the progress bar for the animation always appears as 'complete' regardless of its state. The regression seems to have crept in as part of this overhaul to the animation system (991e6e90ba43a09c93e2abcd31972ad156feca00).

The font colouring also appears to be broken in the master build, but this appears to be a seperate and much more recent issue.

### Steps to reproduce

Create an AnimationTree with a state machine, creation an AnimationPlayer with one or more looped animations, add one of these to the AnimationTree state machine and create an AtEnd transition to another node. The animation will never execute the transtion.

### Minimal reproduction project

[animation_test_1.zip](https://github.com/godotengine/godot/files/12625929/animation_test_1.zip)

**Comment by SaracenOne** [comment]
https://github.com/godotengine/godot/pull/79400
Workaround by @TokageItLab, need to review

**Comment by TokageItLab** [comment]
As mentioned in https://github.com/godotengine/godot/pull/79400#issuecomment-1722083981, this is not a bug exactly, but rather an expected behavior to avoid unsemantic transitions. To solve this completely, the user should be able to arbitrarily define the remaining time of the upstream AnimationNode such as commented in https://github.com/godotengine/godot/pull/57959#issuecomment-1118971746, but a proposal may be needed.
