### ISSUE TITLE
Can't create a new material by dragging a shader on user-exported properties if they're not *specifically* `ShaderMaterial`s

### ISSUE THREAD

**Issue by mieldepoche** [godotengine/godot#81722]
### Godot version

4.1.1

### System information

linux

### Issue description

[simplescreenrecorder-2023-09-16_07.31.44.webm](https://github.com/godotengine/godot/assets/71937306/6ebd1c7c-0b0f-49b8-93ff-908ae1758d52)

as you can see, I can't automatically create a new `ShaderMaterial` by dropping a shader on a material slot when the material slot is one I exported from a script, unless I set the export type to `ShaderMaterial` specifically (not showcased in video).

### Steps to reproduce

```gdscript
@export var wont_work: Material
@export var will_work: ShaderMaterial
```

and then drop a `Shader` resource on both of those in the inspector.

### Minimal reproduction project

the script above and an empty `.gdshader` file

**Comment by jsjtxietian** [comment]
Is this expected or a bug?  

The export property's base_type in editor_resource_picker is `Material` for won't work and `ShaderMaterial` for will work, but the 
GeometryInstance3D's material field's base_type is `BaseMaterial3D,ShaderMaterial`. 

And in `_get_allowed_types` , for a `ShaderMaterial`,  it will insert a `Shader` to allowed_types, but for `Material` it won't do so. That's why we can't drag a shader directly to the exported material property.

https://github.com/godotengine/godot/blob/571cd0eb791b37e9a8adda9f909251138170f6b7/editor/editor_resource_picker.cpp#L624-L632

https://github.com/godotengine/godot/blob/571cd0eb791b37e9a8adda9f909251138170f6b7/editor/editor_resource_picker.cpp#L680-L689
