### ISSUE TITLE
Control toolbar, "align with expand" checkbox does not set/unset the flag for container sizing

### ISSUE THREAD

**Issue by tokengamedev** [godotengine/godot#81726]
### Godot version

4.2.dev.4

### System information

Windows 11

### Issue description

In the control toolbar when you toggle the checkbox "align with expand", it does not set/unset the expand flag in the container sizing

### Steps to reproduce

https://github.com/godotengine/godot/assets/84369217/18a3cf33-c0b9-436d-bb48-7d3890a539eb

### Minimal reproduction project

If required I will provide it

**Comment by YuriSizov** [comment]
This checkbox modifies how buttons above it behave, but it doesn't set anything by itself. You need to use one of the above modes after toggling it. (it works like a tool that you apply to nodes, not as a shortcut to a specific property).

**Comment by tokengamedev** [comment]
This is awkward interaction, and counterintuitive as already the value for horizontal or vertical is set. Then why other buttons has to be pressed again, after the checkbox is set.  Toggling the value should enable the expand. Do you think I push this into proposal then, if this was the intended behaviour

**Comment by YuriSizov** [comment]
Expand is a part of that value, it's additive to other flags. Replacing that part of the toolbar with a button that is supposed to set expand only can lead to unexpected results when you have multiple nodes selected.

I believe there is a PR for what you ask for already, though.

**Comment by tokengamedev** [comment]
That is fine. In 3.x it was completely open for combinations, but didn't face any issues because when you do stupid combinations you get stupid results. It is ok. 
In 4.x it is more restrictive and expand option is available, if it makes sense based on control and container structure. I kind of disagreed initially, but it made sense when I played around. 
I don't think that is the issue here.
The issue here is the way expand flag is set, the ux of the action.
The size flags are separate from expand flag, so they should be able to set independently.
Regarding PR and proposal I was asking if what I reported is intended behavior. Then we can close the issue and open a proposal to discuss and if needed to be implemented.

**Comment by YuriSizov** [comment]
> The size flags are separate from expand flag

They aren't though. It's just that expand has no sense without one of the other flags. So in the UI we present them as two distinct groups. But you can't set just expand, or rather just expand is the same as "shrink begin + expand". In 3 we didn't explicitly expose "shrink begin" as it's just the default behavior where no other flag is set, so it looked like you can set to just "expand", but that wasn't a correct way to represent the behavior.

The behavior of the toolbar is intended, yes. That's why the checkbox is called "Align with expand" and not just "Expand". It refers to the fact that you are going to use the alignment tool with the expand flag set to "On". 

Here's the PR that suggests we change it: https://github.com/godotengine/godot/pull/65258

**Comment by YuriSizov** [comment]
Expand doesn't depend on size flags. Expand **is** one of the size flags. It just doesn't have any use standalone.

**Comment by tokengamedev** [comment]
What I have been trying to say is, it is a usability issue. 
It does not matter which flag is for what. Internally (in code) all permutations have to be handled. 

Currently I stopped using the toolbar altogether, rather I am using the inspector.
