### ISSUE TITLE
Shader Parameters Depth Min/Max Layers Freezes Godot if you go below 0

### ISSUE THREAD

**Issue by CigamPower** [godotengine/godot#81753]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Ti Laptop GPU (NVIDIA; 31.0.15.3734) - 12th Gen Intel(R) Core(TM) i9-12900H (20 Threads)

### Issue description

I was testing a static and dynamic material from material maker. When going into the dynamic test material, in its shader parameters, I was testing out different values, and reducing the min or max layers to below 0 will freeze godot. At 0 value it is fine, but as soon as you click to go below zero it freezes. Not sure if that should be disabled to prevent going below 0, or what to do for that.

### Steps to reproduce

In the MRP goto:
crater-dynamic-test
mesh
material
shader parameters
depth min or max layers and reduce to below 0 on one of them

https://github.com/godotengine/godot/assets/43964088/4ab472ff-e841-4aed-b6aa-0ca7db591457

### Minimal reproduction project

MRP: [crater-test.zip](https://github.com/godotengine/godot/files/12641424/crater-test.zip)

**Comment by bitsawer** [comment]
I checked the shader and setting those parameters cause the shader to go into a while loop that takes too long to execute and driver/GPU usually causes the device to be lost / reset. What happens depends on your OS, GPU and driver, but usually it's not usually easy to recover from. On Windows, you might hit TDR: https://learn.microsoft.com/en-us/windows-hardware/drivers/display/timeout-detection-and-recovery Even if Godot could recover from it, it will repeat the same again soon as the shader will be tried again. Adding logic to try to guess if we are in some kind of reset loop because of a bad material shader is not very practical, either.

There's not much Godot can do about it, you'll have to be careful when writing shaders that have loops or similar dynamic control flows. To boil this issue into a more simpler code, this shader code can cause a Vulkan device loss (or worse) in many systems:

```glsl
void vertex() {
    while (true) {}
}
```

Closing as this is not really actionable from Godot side of things. Some documentation warns about this already (like https://docs.godotengine.org/en/latest/tutorials/shaders/compute_shaders.html) and it's something shader programmers should be expected to know and guard against. Material Maker could add more validation to the parameters inside the shader or when setting them, but that can have a significant performance cost.
