### ISSUE TITLE
SpotLight3D causes clustering artifacts with large light angle and small camera far plane

### ISSUE THREAD

**Issue by Fabien2S** [godotengine/godot#81772]
### Godot version

v4.1.1.stable.mono.official [bd6af8e0e]

### System information

Godot v4.1.1.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3713) - 12th Gen Intel(R) Core(TM) i5-12600KF (16 Threads)

### Issue description

- This issue persist in 4.2dev4
- Does not require a WorldEnvironment node
- Probably not related to #78500, as this issue occurs without volumetric fog

With a Camera3D far plane of `4000` (default value)
![image](https://github.com/godotengine/godot/assets/18100602/6cc5a71a-645d-48be-a373-8250df201052)

With a Camera3D far plane of `100`
![image](https://github.com/godotengine/godot/assets/18100602/68b74da4-b0c2-4775-9a18-c14fc5ef7ddd)

### Steps to reproduce

- Camera3D must be "behind" the SpotLight3D
- Camera3D far plane must be small (tested with `100m`)
- SpotLight3D angle must be large (tested with 75°)

### Minimal reproduction project

[MRP.zip](https://github.com/godotengine/godot/files/12641633/MRP.zip)

**Comment by viksl** [comment]
Can you test with this please?
https://github.com/godotengine/godot/pull/80992

**Comment by Roboticy3** [comment]
I have a similar problem on my project! there's a situation where the clipping plane needs to be close and it causes the same artifacts. I hope I can find the time to add a demo project later, but I'm using directional lights and getting the same issue.

I experimented with changing the sky and environment parameters, because I thought that would be the issue, but apparently not. 

Graphics code in general is definitely spooky and or haunted. No shade to Godot, I use Blender too and thats just how it is sometimes. Keeping the far plane above 100 is my best fix so far.

### System Information
Godot v4.1.1 stable. Linux Mint Vera, AMD Ryzen 3 (Picasso) dual-core, integrated graphics.

**Comment by Roboticy3** [comment]
Ok, here's a demo project. It looks like the lighting bug happens on geometry within a certain range between the camera and the far plane.

WASD to move the camera, up/down arrows to move the far plane further/closer, current far plane prints to debug. Hold left click to rotate the cube.

It's probably a lighting optimization that breaks under these conditions, and you can achieve the same bug with any light source.

I'd like to not have to worry about this too.

[godot81772.zip](https://github.com/godotengine/godot/files/12862817/godot81772.zip)

**Comment by jcostello** [comment]
I experienced the same problem in the TPSDemo
