### ISSUE TITLE
TabBar: mouse events crash when tab size changes depending on hover state

### ISSUE THREAD

**Issue by wouldntsavezion** [godotengine/godot#81836]
### Godot version

4.2 dev 4

### System information

Godot v4.2.dev4 - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.3699) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)

### Issue description

The game crashes entirely with no log/feedback when just moving the mouse from a tab to another when the size between the tabs isn't the same.

It seems to depend on what style is different. Adding margins (mrp) breaks it, so does adding a border, but the skew or shadows don't etc.

### Steps to reproduce

Just move the mouse from one tab to another, moving in/out of the same tab is fine.

https://github.com/godotengine/godot/assets/17103048/a06729dc-4d6a-4bcd-9792-1af289f69411

### Minimal reproduction project

[mrp.zip](https://github.com/godotengine/godot/files/12643956/mrp.zip)

**Comment by adeneve** [comment]
This looks to be a stack overflow happening due to 'TabBar::_update_hover() ' calling 'TabBar::_update_cache()', which calls 'TabBar::_update_hover()'... and so on repeatedly.

 It looks like the root cause of this, and the reason this doesn't happen on other tab bars, is because the width of the tab changes when you hover/select it. If it is unacceptable for the hover width to be different than the 'unselected' width, then perhaps the fix is simply enforcing that all these tab styles have equal width. However, having different widths for tab styles might be 'acceptable', I am not sure.

 I found a way to stop this error by simply checking if the mouse was moved by keeping track of the last mouse position. If the mouse wasn't moved, then we might be able to return early from 'update_hover'. However, even with a fix like that, when you move the mouse in-between tabs horizontally there is a weird behavior as the tab styles seem to oscillate when you have past a certain threshold. Another possible fix may be to add some more careful checks of all the tab styles, then maybe use the Max() width of all the styles to reference the tabs. I will look into that later unless someone else finds a solution before then.

**Comment by Patedam** [comment]
One solution i tried was to check the hover style boundaries before going into hover.

https://github.com/godotengine/godot/assets/15082019/11fadf53-94c8-4113-939c-b7a04c0530ca

**Comment by YeldhamDev** [comment]
I'm attempting to fix the issue, but there's a problem: I'm completely unable to actually trigger the issue on my end. Me and the OP use different OSes (GNU/Linux and Windows), so maybe the UI input is being handled differently between them?

**Comment by Patedam** [comment]
Posted one potential fix tell me what you think about it @YeldhamDev 
To repro you can trace inside update hover and move from one tab to another it should be stuck in an infinite loop
