### ISSUE TITLE
Can't input in a decimal (.) in SpinBox when update_on_text_changed = true

### ISSUE THREAD

**Issue by Alyxsqrd** [godotengine/godot#81989]
### Godot version

v4.2.dev5.mono.official [e3e2528ba]

### System information

Godot v4.2.dev5.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 Threads)

### Issue description

If you have a SpinBox that has the "Update on Text Changed" property enabled, it is impossible to type in a decimal value as it will always ignore the period key whenever the user is typing in a number by hand.

### Steps to reproduce

1. Create a new SpinBox node
2. Enable the "Update on Text Changed" property
3. Run the current scene (press F6)
4. Type in any decimal number into the text box (such as 3.14)

Note: you can also reproduce the issue by setting `update_on_text_changed = true` on the SpinBox via GDScript or C#.

### Minimal reproduction project

N/A

**Comment by adeneve** [comment]
At first I was going to say, perhaps changing the step from 1 -> 0.01 in the range will fix this, but it does not because as soon as you hit the '.' key, the update logic is called and '3.' gets reset to '3'. perhaps a code change can be made in SpinBox::_text_changed, if the input contains a period character '.', located at the end of the string, simply return prematurely without doing anything. From my simple testing this seems to work. Let me know what you guys think of this solution. 

void SpinBox::_text_changed(const String &p_string) {
       // start of new code
	if (p_string.ends_with("."))
		return;
      // end of new code
	int cursor_pos = line_edit->get_caret_column();

**Comment by adeneve** [comment]
I have confirmed on my end, [#80699](https://github.com/godotengine/godot/pull/80699) seems to fix this as well. Should be good to close my PR and use that one instead 👍.

**Comment by Alyxsqrd** [comment]
Agreed, #80699 has fixed this issue! Looking forward to a merge.

**Comment by Crystalwarrior** [comment]
This problem came back in Godot 4.3 in some form, not even sure if it's the same issue or a new one

https://github.com/user-attachments/assets/c0184b89-79c1-44f2-ac40-8b8ad80e2a49
