### ISSUE TITLE
Vector math reflect() function is wrong?

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8201]
I'm not math specialist but I think Vector reflect() math is wrong'ish.

When I'v checked the Godot source, code looked like this:

Vector2 Vector2::reflect(const Vector2 &p_vec) const {
	return p_vec - *this * this->dot(p_vec) * 2.0;
}

It produced results that don't look like correct vector reflection.

Shouldn't formula be:
-(vec - vec.dot(normal) * 2 * normal)

**Comment by tagcup** [comment]
Seems like it was originally written the other way around (intentionally?) with the wrong sign: `-a.reflect(b)` reflects b around a. Thanks once again for reporting these issues. Yes, assuming that `p_vec` is normalized. I'll submit a PR to replace it with

```cpp
Vector2 Vector2::reflect(const Vector2 &p_n) const {
	ERR_FAIL_COND(p_n.is_normalized() == false);
	return 2.0 * p_n* this->dot(p_n)  - *this;
}
```

and update the docs that `p_n` must be normalized, and review potentially affected code. I'm hoping I can go over all the math library before 3.0.

**Comment by tagcup** [comment]
Same problem in `Vector3::reflect`.

**Comment by tagcup** [comment]
The documentation also needs to be rewritten:

> Vector2 reflect ( Vector2 vec )
> Like “slide”, but reflects the Vector instead of continuing along the wall.

[Reflection](https://en.wikipedia.org/wiki/Reflection_(mathematics)) is a mathematical operation which has nothing to do with walls or sliding.

Mathematically speaking, the name of `Vector2::slide` opaque to me (I understand the [context](http://docs.godotengine.org/en/stable/tutorials/2d/kinematic_character_2d.html), but still), which simply deletes one component of a vector along a normal (`v - (v.n)n`), and to me the current form reads "the other way around": `n.slide(v)` rather than `v.slide(n)`.

**Comment by tagcup** [comment]
I think this is actually the reflection that *does* involve "walls": think of the direction of a beam of light being reflected from a surface: `n.reflect(direction)`, or a ball bouncing off from a surface.

I think we should first talk to @reduz about this. `slide` and `reflect` are all defined in such context, but `reflect` at least conflicts with mathematical reflection. We can add a proper reflection function, and rename one of those. We can discuss about ordering (`n.reflect(v)` versus `v.reflect(n)`).

**Comment by hubbyist** [comment]
I think "reflect light according to wall" or "reflect that vector according to this normal" is the intuitive way of arrangement. So `v.reflect(n)` or `v.slide(n)` is better IMO.

**Comment by n-pigeon** [comment]
@tagcup thx for checking it out.

I also agree with @hubbyist v.slide(n) and v.reflect_wall(n) look more intuitive.
