### ISSUE TITLE
Small probability to appear screen jitter

### ISSUE THREAD

**Issue by zhagsenkk** [godotengine/godot#82167]
### Godot version

4.1.1

### System information

Win 11,CPU amd5600,GPU 5700xt,mobile rendering mode

### Issue description

It will be ok in most moment when playing the game in the debug mode. Small probability it will be like in the video, grass picture of the background will appear jitter.But when I start the ScreenToGif tool, it will be ok.
The videos' time is bad, just see. Pay attention to the grass picture's' edge in first video.

https://github.com/godotengine/godot/assets/10054853/08f93117-3912-4c7f-aa31-4f19084accbb

https://github.com/godotengine/godot/assets/10054853/45dafcd6-a23c-4e7f-98d0-83beb9cc0bd6

### Steps to reproduce

Start the game again and again, small probability it will be like in the video.

### Minimal reproduction project

[Survivors Clone.zip](https://github.com/godotengine/godot/files/12705659/Survivors.Clone.zip)

**Comment by ghmart** [comment]
Hi, zhagsenkk!

It's hard to tell exactly where the problem lies when it is occuring randomly, so here several hints for you to explore:

First thing I would do is to somehow limit the use of Area2Ds. Even in small amount they can be ridiculously expensive by monitoring each other. In one of my projects I got rid of huge lag by simply turning off player's sword hit area when it wasn't used. Though I didn't digged too deep into your project. You know better if all Area2Ds are tuned properly or not.

Have you tried to use VisibleOnScreenNotifier2D node instead of using timers to free bullets?

Have you tried to use delta in player's physics_process?
Other modes of V-Sync? Maybe use Enabled instead of Adaptive?

You could try to play with "Project settings -> General -> Physics -> Common -> Physics Jitter Fix" and other settings in that group.

Is there a jitter when you in full-screen mode?
Does it behaves differently in Forward+ and Compatibility modes? By the way, is your video driver up to date?

Will jitter persist if you don't print anything each frame to the console?

In extreme cases when there are too many enemies / bullets (which is not the case with your project, of course) I would use object pooling (for both enemies and bullets) instead of add_child / queue free. As well as for audio effects.

You could also try to use development version of Godot (4.2 dev 5, for example) (backup project first!!!)

Cheers!

**Comment by dalexeev** [comment]
* See godotengine/godot-docs/issues/7774.

**Comment by Calinou** [comment]
Please go through the [Fixing jitter, stutter and input lag](https://docs.godotengine.org/en/stable/tutorials/rendering/jitter_stutter.html) documentation.

**Comment by dalexeev** [comment]
* Closing in favor of godotengine/godot-docs#7774, as this is not an engine issue. Let me know if the information did not help you.

See also: 
* godotengine/godot-proposals#6389
* #82829
