### ISSUE TITLE
Light2D texture ignored when using canvasitem light shader

### ISSUE THREAD

**Issue by M5tern** [godotengine/godot#82183]
### Godot version

4.1.1-stable

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 30.0.15.1295) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

Canvasitem light shader process ignores light2d textures and only uses their bounding box to determine if a pixel is lit or not. In this example the light is circular, but it's treated as square when covering the object using a shader.

![godot light shader](https://github.com/godotengine/godot/assets/100398638/f7a7545d-c878-47b9-b068-c93b1462a1a3)

### Steps to reproduce

Make a PointLight2D. Overlap it with a Sprite2D with this shader as material:

```
shader_type canvas_item;
render_mode blend_mix;

void light()
{LIGHT = texture(TEXTURE,UV);}
```

### Minimal reproduction project

[LightTestProject.zip](https://github.com/godotengine/godot/files/12706257/LightTestProject.zip)

**Comment by bitsawer** [comment]
Does changing the light shader to this help? LIGHT is both input and output and you overwrite it completely instead of modifying it.

```glsl
void light()
{
	LIGHT = LIGHT * texture(TEXTURE,UV);
}
```

**Comment by M5tern** [comment]
> Does changing the light shader to this help? LIGHT is both input and output and you overwrite it completely instead of modifying it.

It doesn't. The light() function works just like fragment(), but for pixels that are lit up. It clearly only partially works, since only pixels inside the light's bounding box are affected. Using the light_only render mode (as seen on the grass in the example pic) does accurately work as intended, but that forces all unshaded pixels to be invisible, which is very limiting.

**Comment by jsjtxietian** [comment]
Looks like the altas is wrong：
![image](https://github.com/godotengine/godot/assets/8315986/ebfbe674-5adf-4953-9bab-2c51f4144103)

**Comment by jsjtxietian** [comment]
The root cause seems like the name `TEXTURE` is not treated well when inside light function, or let's say it will make user confuse.

As you see the left is the normal one with the default shader (correct version) , right is the provided custom shader (the broken one). 

![image](https://github.com/godotengine/godot/assets/8315986/1cd20ec0-0543-4d8f-846b-08fb8fd95cfa)

The left uses `vec4 light_color = textureLod(atlas_texture, tex_uv_atlas, 0.0);` to sample light texture and it's correctly set as the light  texture:

![image](https://github.com/godotengine/godot/assets/8315986/bd6bfbbf-79d4-4070-a7c3-daeba6df9603)

The right uses `light=texture(color_texture, uv);` in `light_compute` and `color_texture` is the item's own color texture:

![image](https://github.com/godotengine/godot/assets/8315986/17611407-4fdf-4959-aee6-97b1d780b6d0)

**Comment by clayjohn** [comment]
The shader appears to work as intended. ``TEXTURE`` is the same texture used in the fragment function. It is not the light's texture. Light shader's don't expose the light's texture instead they expose the light's color per-pixel with ``LIGHT_COLOR``. 

``LIGHT = texture(TEXTURE,UV);`` will do exactly as the OP shows, it mixes the color of the CanvasItem's texture with itself (in the region of the light). 

There isn't a bug here. The docs on CanvasItem shaders also explain this nicely https://docs.godotengine.org/en/latest/tutorials/shaders/shader_reference/canvas_item_shader.html#light-built-ins

**Comment by M5tern** [comment]
Even if you use LIGHT = LIGHT_COLOR, the behavior is the same (light texture is not correctly taken into account). The "region of the light" is a rectangle that ignores the shape of the light texture. This cannot possibly be intended behavior.

**Comment by M5tern** [comment]
For posterity, here is the solution:

`LIGHT = texture(TEXTURE,UV) * LIGHT_COLOR;`

This will give the correct desired behavior.
