### ISSUE TITLE
NavigationServer MapGetPath returns empty path in C#, but equivalent works in GDScript

### ISSUE THREAD

**Issue by edwardr** [godotengine/godot#82209]
### Godot version

Godot_v4.1.1-stable_mono_win64

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 Threads)

### Issue description

NavigationServer2D's MapGetPath is returning an empty path while a very comparable GDScript version using map_get_path returns the expected coordinates.

The GDScript version logs one error:

```
update_polygons: Navigation map synchronization error. Attempted to update a navigation region with a navigation mesh that uses a different `cell_size` than the `cell_size` set on the navigation map.
  <C++ Source>   modules/navigation/nav_region.cpp:118 @ update_polygons()
```
While the C# version logs two; the above as well as this:

```
sync: Navigation map synchronization error. Attempted to merge a navigation mesh polygon edge with another already-merged edge. This is usually caused by crossing edges, overlapping polygons, or a mismatch of the NavigationMesh / NavigationPolygon baked 'cell_size' and navigation map 'cell_size'.
  <C++ Source>   modules/navigation/nav_map.cpp:845 @ sync()
```

I have made previous attempts to change the various cell_sizes just in case to no avail.

### Steps to reproduce

With the MRP, you can switch the Node2 script from TestingNavigation.cs and TestingNavigation.gd to see the distinctions. With the GDScript attached, the path will properly print to the console while the C# version prints an empty path.

### Minimal reproduction project

[Navserver Path Issue.zip](https://github.com/godotengine/godot/files/12707191/Navserver.Path.Issue.zip)

**Comment by smix8** [comment]
I don't encounter any errors in the GDScript version of this project.
I dont have a CSharp setup to test so maybe the CSharp ppl can fill in the blanks.

Those errors should be unrelated to the used language as they are triggered by a mismatch of NavigationMesh cell size and navigation map cell size as well as navigation mesh placement on the map.

The first error is caused by the `NavigationMesh` resource property `cell_size` not being the same as the navigation map cell size. By default the NavigationPolygon and the 2D navigation map both use 1 pixel as cell size so there is no reason for this to trigger if you did not change this cell size manually. You can change the navigation map cell_size in the ProjectSettings in the navigation section (Advanced Settings) for the default navigation map or you can use the `NavigationServer.map_set_cell_size()` API function to change it for any map.

The second error is because the actual rasterization of the navigation mesh vertices and edges failed when the navigation map tried to sync the map. Caused by too many vertices and their edgekeys falling into the same grid cells. This is commonly caused by duplicated edges, or edges that are too close to each other, or edges that intersect each other. Those edges can be from the same navigation mesh but also from other navigation meshes, e.g. because they partly overlap. Since you only have a single navigation mesh in the scene that has 2 correct looking polygons this should not trigger either.

**Comment by smix8** [comment]
I looked at your CSharp script and you are creating a new navigation map with the NavigationServer API in an async function without updating the cell_size for this newly created navigation map.

New navigation maps created with the server API are "neutral" between 2D and 3D. New maps are init with a cell_size of 0.25. You need to update the cell_size of a new map once so it matches your 2D pixel cell size else you will likely trigger those errors.

**Comment by edwardr** [comment]
Thanks @smix8. Forcing the newly created map to int 1 instead of float resolves the cell_size error. I am still seeing the empty path and the navmesh merge error with C# version.

**Comment by raulsntos** [comment]
I took a quick look at the MRP. When you set the transform for the region, in GDScript you are using `Transform2D()` and in C# you are using `new Transform2D()`. These are **not** equivalent, GDScript's constructor creates an identity transform, but in C# it creates a zero transform. If you want the identity transform in C#, use `Transform2D.Identity`.

Please, read the [ _C# API differences to GDScript_](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_differences.html) documentation page to find out about all the differences that you need to know when translating code between GDScript and C#.

**Comment by edwardr** [comment]
Made the `Transform2D.Identity` update and that resolved the console error, but the map path is still empty.

**Comment by edwardr** [comment]
Uploading a simplified version of the MRP that corrects the above listed issues. This one has no errors but MapGetPath still returns an empty path.
[navserver-path-issue-2.zip](https://github.com/godotengine/godot/files/12753326/navserver-path-issue-2.zip)

**Comment by smix8** [comment]
The `NavigationServer2D.map_get_path()` function returns a `PackedVector2Array` instead of a normal `Array`.

According to docs C# needs to handle those PackedArrays differently. Maybe that is the source of the issue.
https://docs.godotengine.org/en/latest/tutorials/scripting/c_sharp/c_sharp_collections.html#godot-collections

**Comment by raulsntos** [comment]
Yes, for `Packed*Array`s, we use normal C# arrays in the C# API. This means that `NavigationServer2D.MapGetPath` returns a `Vector2[]`.

In your MRP you are printing the `Vector2[]` directly, but C# arrays don't implement `ToString` so it's only printing the type name, that doesn't mean the array is empty though. If you convert the array to `Variant` before printing it, it will use the `Variant.ToString` implementation which will actually print the contents of the array:

```csharp
var path = NavigationServer2D.MapGetPath(NavigationAgent.GetNavigationMap(), startPosition, endPosition, optimize: true);
GD.Print((Variant)path);
```

**Comment by edwardr** [comment]
Confirming that is the issue and it is indeed working as expected @raulsntos @smix8. Will close the issue; thanks for helping with this.
