### ISSUE TITLE
.values() and .keys() sorts by the key's alphabetical order instead of the dictionary's order.

### ISSUE THREAD

**Issue by Deadstay** [godotengine/godot#82234]
### Godot version

4.1.1 .NET

### System information

Godot_v4.1.1-stable_mono_win64

### Issue description

When making a dictionary and exporting it to the hierarchy, doing D.values() or D.keys() sorts the keys by it's alphabetical order instead of the pre-set one. This means if the second key of your dictionary is false, the table shall sort alphabetically, however the values shall remain at the same position, so the second key of your dictionary ONCE it's sorted alphabetically will be false.

### Steps to reproduce

@export var dictionary = {
	"a": true, 
	"d": false, 
	"b": true,
	"c": true, 
}

print(dictionary.keys()) -- Returns (a, b, c, d)
print(dictionary.values()) -- Returns (true, true, true, false)
print(dictionary.values()[2]) -- Returns back true
print(dictionary.values()[4]) -- Returns back false

### Minimal reproduction project

N/A
```[tasklist]
### Tasks
```

**Comment by SaNeOr** [comment]
I tried it. It's the preset order.

Did I miss some step?

**Comment by Deadstay** [comment]
I'm not sure. When i changed the preset order to alphabetically, it changed to its original present order? Maybe it has to do with the way dictionaries are exported.

**Comment by AThousandShips** [comment]
Cannot confirm this, please provide more detailed steps and a minimal reproduction project to show this bug:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the above required information this can be reopened
