### ISSUE TITLE
X11: `is_action_pressed` returns incorrect value when key was pressed during scene loading

### ISSUE THREAD

**Issue by eldidou** [godotengine/godot#82262]
### Godot version

Godot_v4.2-dev4_linux.x86_64

### System information

Ubuntu 22.04 Vulkan Forward+

### Issue description

If an action is pressed during the loading of a scene, even if the key is released, `is_action_pressed()` will always consider it pressed afterward.
The behavior is the same for `is_action_pressed` and `get_vector`, `get_axis`. On the other hand `is_key_pressed` is working as expected.
On `4.2-dev4` and `4.2-dev5`, I was able to reproduce it relatively easily (50% of the time). I could not with `4.2-dev3` or earlier or with `4.1`.
I've seen it during the first loading of a scene as well as during a `reload_current_scene()`.

### Steps to reproduce

- map an input to a key
- launch a scene
- while the scene is still launching, pressed the action key
- after the scene is launched, release the key
- print the `is_action_pressed` and `is_key_pressed`, it the issue occurs, they are not consistent

note: On a minimal project the scene is loading fast, so it's easy to miss the time window.

### Minimal reproduction project

[action_pressed_bug.zip](https://github.com/godotengine/godot/files/12709597/action_pressed_bug.zip)

**Comment by echowarp** [comment]
New to this, but from my testing  is a one shot at the beginning of the press, but and  are continuously triggered, but I don't think this is clearly spelled out in the documentation.

Continuously True:
- `Input.is_action_pressed()`
- `Input.is_key_pressed()` 
- `InputEvent.is_action()`

One-shot at start:
- `Input.is_action_just_pressed()`
- `InputEvent.is_action_pressed()`

I wonder if something is mixed up between Input and InputEvent since the event version of `is_action_pressed()` is single-pass while the identically named other version is continuous.
It makes sense that perhaps a one-shot version might be ignored on scene load because it needs to see the transition from released to pressed.

**Comment by rsubtil** [comment]
> I wonder if something is mixed up between Input and InputEvent since the event version of is_action_pressed() is single-pass while the identically named other version is continuous.

This is because InputEvents only exist on `_input` callbacks, which are only triggered on input changes, and not continuously like in `_process` (check [this](https://docs.godotengine.org/en/stable/tutorials/inputs/input_examples.html#events-versus-polling) for more info).

**Comment by rsubtil** [comment]
Bisected to ad1abca66886986a031e6aa042dd4894a3b96a80 https://github.com/godotengine/godot/pull/80859 (cc @KoBeWi)

**Comment by KoBeWi** [comment]
Can't reproduce in dev5 and later. Tested on Windows.

**Comment by rsubtil** [comment]
Haven't had the chance to test on a Windows machine yet, but when running it on Linux under Wine I can't reproduce either. So it seems that this is a Linux-specific issue.

**Comment by akien-mga** [comment]
Confirmed reproducible as of 4.2-beta5 / e5bacbc4716ce5b54bc2ab8b3053cd5e22ffe446.
