### ISSUE TITLE
TouchScreenButton with is_action_just_pressed() bug

### ISSUE THREAD

**Issue by RoboLampDev** [godotengine/godot#82396]
### Godot version

4.1.2.rc1

### System information

Godot v4.1.2.rc1 - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Vega 8 Graphics () - AMD Ryzen 3 2200G with Radeon Vega Graphics (4 Threads)

### Issue description

	if Input.is_action_just_pressed("ui_accept") and is_on_floor():     
  this form with "just" don't work on mobile (android)
i don't know why but when you try it in pc with mouse emulate touch it works fine but when you export the project to the mobile it don't work although is_action_pressed() works fine idk why the one with "just" don't work with TouchScreenButton on mobile please fix that

### Steps to reproduce

`if Input.is_action_just_pressed("ui_accept") and is_on_floor():
		velocity.y = JUMP_VELOCITY`

its a basic form of jump when you add  TouchScreenButton and assign it with  ui_accept and try it it only works in pc not actually on the mobile i cant just the Button dont work
things to note :
-TouchScreenButton work with  is_action_pressed() on mobile but is_action_just_pressed() don't work
-is_action_just_pressed() work fine in pc when you click with the mouse but it don't work on mobile
-It only work on mobile if you make a signals for pressed and released for  TouchScreenButton 

### Minimal reproduction project

![image](https://github.com/godotengine/godot/assets/146053254/de0ebc7f-ece1-4a5b-b6bb-6ebd67ff3ad1)

**Comment by RoboLampDev** [comment]
I think it's not a duplicate it's just similar in things doesn't work on
mobile properly , i hope this will be fixed and thanks for the response

Best regards
RoboLamp Dev

**Comment by ErezShahaf** [comment]
Hey, can you please upload a minimal reproduction project? (upload the project, not an image) 
I'd love to see what you did there and investigate it.

**Comment by RoboLampDev** [comment]
Sure, no problem. ​
here it is . i also included apk file so you can install it on your mobile and test it
https://drive.google.com/file/d/11mMZFGXq7ahLPzTiTHSFZq39r0WzEyWj/view?usp=drive_link

**Comment by Alex2782** [comment]
@RoboLampDev 
please adjust your "minimal reproduction project" in the first post here at Github (remove screenshot). For your Google Drive share a permission is necessary.

**Comment by Jedzkie** [comment]
I'm experiencing the same issue.

Here's my minimal project: [TouchScreenButtonBugMobile.zip](https://github.com/godotengine/godot/files/12843497/TouchScreenButtonBugMobile.zip)

@Alex2782 @ErezShahaf

**Comment by Alex2782** [comment]
> I'm experiencing the same issue.
> 
> Here's my minimal project: [TouchScreenButtonBugMobile.zip](https://github.com/godotengine/godot/files/12843497/TouchScreenButtonBugMobile.zip)

`v4.2.dev6.official` [57a6813bb]
I couldn't reproduce the problem, maybe already fixed?

exported APK (20 MB): [TouchScreenButton.apk](https://drive.google.com/file/d/1GN0HiFgSMFRJLLQjYQVTfxdBsDksATjT/view?usp=sharing)

Small error I could find, however, now and then the counter was not increased, but most of the time it was.
I could first check if TouchScreenButton always detects touch event at all.

``` gdscript
func _physics_process(_delta : float) -> void:
	if Input.is_action_just_pressed('touch_me'):
		pressed_count += 1
		$Label.text = 'Pressed: %s' % pressed_count
```


Docs: `is_action_just_pressed`

Note: Due to keyboard ghosting, is_action_just_pressed() may return false even if one of the action's keys is pressed. See Input examples in the documentation for more information.

**Comment by Jedzkie** [comment]
> > I'm experiencing the same issue.
> > Here's my minimal project: [TouchScreenButtonBugMobile.zip](https://github.com/godotengine/godot/files/12843497/TouchScreenButtonBugMobile.zip)
> 
> `v4.2.dev6.official` [[57a6813](https://github.com/godotengine/godot/commit/57a6813bb8bc2417ddef1058d422a91f0c9f753c)] I couldn't reproduce the problem, maybe already fixed?
> 
> exported APK (20 MB, my Google Drive-Account): [TouchScreenButton.apk](https://drive.google.com/file/d/1GN0HiFgSMFRJLLQjYQVTfxdBsDksATjT/view?usp=sharing)
> 
> Small error I could find, however, now and then the counter was not increased, but most of the time it was. I could first check if TouchScreenButton always detects touch event at all.
> 
> ```gdscript
> func _physics_process(_delta : float) -> void:
> 	if Input.is_action_just_pressed('touch_me'):
> 		pressed_count += 1
> 		$Label.text = 'Pressed: %s' % pressed_count
> ```

I tried your exported apk, and the touch event is still not working.

**Comment by Alex2782** [comment]
on Android 13 Samsung tablet it works 90%, where did you test?

![image](https://github.com/godotengine/godot/assets/41921395/6b06c37a-936e-463f-a47f-b24538f9250c)

**Comment by Jedzkie** [comment]
> on Android 13 Samsung tablet it works 90%, where did you test?
> 
> ![image](https://user-images.githubusercontent.com/41921395/274110672-6b06c37a-936e-463f-a47f-b24538f9250c.png)

Tested in my xiaomi mi max 2 and samsung galaxy note 8

**Comment by Alex2782** [comment]
on my Pixel 4a it doesn't work either, I think the button is too small.
 I'll try to debug it in the next days when I find time

**Comment by Jedzkie** [comment]
> on my Pixel 4a it doesn't work either, I think the button is too small. I'll try to debug it in the next days when I find time

Alright man. One thing I notice that if you use `_process` instead of `_physics_process`. The `Input.is_action_just_pressed` works.

**Comment by Alex2782** [comment]
new "APK" (old file replaced), bigger button does not work either (`_physics_process`)

**Comment by Jedzkie** [comment]
I just tested in `v4.0-alpha1`, it's not working either. Maybe we must look what commit broke it.

**Comment by Jedzkie** [comment]
I think this might help.
https://github.com/godotengine/godot/issues/58562#issuecomment-1064022996

**Comment by Alex2782** [comment]
On my tablet (Samsung SM-T870) I can always reproduce the problem with 30 fps.
`Engine.max_fps = 30`
If I do not adjust the `max_fps` (default) then it works 40% of the time. 

following condition is always `false` because `Engine::get_singleton()->get_physics_frames()` is 1 frame ahead
https://github.com/godotengine/godot/blob/51f81e1c88499f04d2ebdcc0be0b34e73f5e90eb/core/input/input.cpp#L306


**print_line / logcat debug**

```logcat
2023-10-13 17:43:07.759 18401-18445 godot  I  Input::action_press -> action.pressed_physics_frame: 38
2023-10-13 17:43:07.760 18401-18445 godot  I  Engine::get_singleton()->_physics_frames++;
2023-10-13 17:43:07.959 18401-18445 godot  I  pressed_physics_frame: 38 get_physics_frames: 39
```

**fps config**
``` gdscript
	Engine.max_physics_steps_per_frame = 1
	Engine.max_fps = 5
```

**Comment by ChickensioDev** [comment]
> > on my Pixel 4a it doesn't work either, I think the button is too small. I'll try to debug it in the next days when I find time
> 
> Alright man. One thing I notice that if you use `_process` instead of `_physics_process`. The `Input.is_action_just_pressed` works.

this is exactly what im facing too

**Comment by Jedzkie** [comment]
Thank you for fixing this issue @Alex2782

**Comment by luiscesjr** [comment]
I'm facing a similar issue right now on 4.2.2 Mono. I did not test this further into 4.3 beta since this is closed since Nov 2023 I figured it will probably be the same there.
I am play testing this on my PC, did not try yet on mobile to see if it would have a different result.

What happens is, I just set a new action on the Input settings and added it to my button as follows:

![image](https://github.com/user-attachments/assets/5e24f2bc-ed2a-45ce-b2c3-a938ca05c861)
(Don't mind the physical key there, it's just for testing)

And here is my Touch Screen Button:

![image](https://github.com/user-attachments/assets/30c766f8-7915-4bb4-b8e1-643fe1054610)


And here is my simple code:

![image](https://github.com/user-attachments/assets/305c1ce9-dafb-49ed-989c-f608030e404e)

This print is unreachable. Either with pressed or just pressed it won't happen at all. 
This happens both in Physics process and in Process.

First I found out about this issue when  searching for my problem: https://github.com/godotengine/godot/issues/58562

To further test this I created a clean project, made a simple scene like this:

![image](https://github.com/user-attachments/assets/6b608c63-a912-47f4-92e7-f60e0ac368d5)

And the script attached should do this:

![image](https://github.com/user-attachments/assets/34fbdc72-cbcc-4fc6-a3e6-de1b813624b8)

But this also did not work, and did not print anything at all.

I'm not sure I missed anything, but I guess that's all!
