### ISSUE TITLE
OS.get_unique_id() returns empty string on Web target

### ISSUE THREAD

**Issue by kxn** [godotengine/godot#82439]
### Godot version

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.21001.45002) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.21001.45002) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

OS.get_unique_id() returns empty string

there is an error in developer console as well

<img width="499" alt="1695812788144" src="https://github.com/godotengine/godot/assets/2174436/2267b15a-c0a8-4db9-84a1-5971922237a4">

### Steps to reproduce

func _ready():
	print(OS.get_unique_id())

### Minimal reproduction project

not needed

**Comment by akien-mga** [comment]
Indeed `OS.get_unique_id()` is not implemented in `platform/web/os_web.cpp`, so it falls back to the default implementation in `core/os/os.cpp` which is just:
```cpp
String OS::get_unique_id() const {
	ERR_FAIL_V("");
}
```

I vaguely remember that getting a unique ID on Web may not be possible by design, as it's considered a security issue to let websites identify and thus track users like this. But there should be a proper override that makes this clear, possibly by printing a more explicit error, and maybe a non-unique fallback value.

**Comment by AThousandShips** [comment]
This is also [documented](https://docs.godotengine.org/en/latest/classes/class_os.html#class-os-method-get-unique-id)

**Comment by kxn** [comment]
> Indeed `OS.get_unique_id()` is not implemented in `platform/web/os_web.cpp`, so it falls back to the default implementation in `core/os/os.cpp` which is just:
> 
> ```c++
> String OS::get_unique_id() const {
> 	ERR_FAIL_V("");
> }
> ```
> 
> I vaguely remember that getting a unique ID on Web may not be possible by design, as it's considered a security issue to let websites identify and thus track users like this. But there should be a proper override that makes this clear, possibly by printing a more explicit error, and maybe a non-unique fallback value.

Agree that a non-unique fallback value would be better, e.g a random uuid
