### ISSUE TITLE
Possible bug with Threading + HTTPClient

### ISSUE THREAD

**Issue by vicguedez** [godotengine/godot#8252]
**Operating system or device - Godot version:**
Windows 10 x86 - Godot version 2.1.3 rc1

**Issue description:**
I want to make http requests in a non-blocking way, I made a small class that uses threads and the httpclient class. 
The request works sometimes yes and sometimes not, for example, a request that is processed fast will most likely come throu, but when requests start to take longer, it gets resolved but the game freezes.

Im using this to talk to a json api. And I will need to make multiple requests, so it cannot block the main thread.

**Steps to reproduce:**
I load the script as a singleton and use this code.

request.connect("127.0.0.1", 80)
var values = {"email": "example@live.com","password": "notsecurepassword"}
var login_request = request.post("/login", values)

**Files**
[request.zip](https://github.com/godotengine/godot/files/891870/request.zip)

**Comment by lukaskotik** [comment]
It seems the same to as https://github.com/godotengine/godot/issues/7881

As I understand it, Faless has some solution to this. 
From my point of view with this bug the `HTTPClient` is useless because I can hardly imagine a situation when the client is used in the main thread.

**Comment by vicguedez** [comment]
Ok, so I tried to use the HTTPClient without threading but it still can't resolve a second request. This needs to be fixed :S

**Comment by vicguedez** [comment]
After a bit of logging the setps from the api, it is clear that if you make a request that is successfull and make a second request, the request will not reach the api server. I don't think creating a new HTTPClient every time or closing the connection is a good solution - also I haven't test that works, yet.

**Comment by vicguedez** [comment]
After tinkering with the HTTPRequest node and lots of trial and error, I discovered my classs works if I dont add the content-length header.

**Comment by Faless** [comment]
> After tinkering with the HTTPRequest node and lots of trial and error, I discovered my classs works if I dont add the content-length header.

**This is not a bug**

Here you are copying the reference of the array, not the array, so, the second request will have the `Content-Length:` header twice, which most web servers does not like (tested with Nginx) replying as per RFC with a 400 bad request:
```
	var headers = default_headers
	headers.append("Content-Type: application/x-www-form-urlencoded") 
	headers.append("Content-Length: " + length)
```
Fix it like this and it will work:
```
	var headers = []
	for h in default_headers:
		headers.append(h)
	
	headers.append("Content-Type: application/x-www-form-urlencoded") 
	headers.append("Content-Length: " + length)
```

Additionally the game gets locked because you are calling T.wait_to_finish() which as per documentation locks the function until the thread finishes:
```
func post(path, parameters):
	T.start(self, "_post", [path, parameters])
	
	return T.wait_to_finish()
```
You will want to use `Thread.is_active()` to know when the thread has finished and only then call `wait_to_finish()` but be careful not to making new requests until the previous one has finished (use queues with mutex, or maybe a worker thread).

This can be closed @bojidar-bg
