### ISSUE TITLE
Locked PDB file blocks GDExtension compilation when Editor is launched within debugging

### ISSUE THREAD

**Issue by kkolyan** [godotengine/godot#82536]
### Godot version

v4.2.dev (4c3dc2636)

### System information

Godot v4.2.dev (4c3dc2636) - Windows 10.0.19042 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti (NVIDIA; 31.0.15.3713) - Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 Threads)

### Issue description

When Godot Editor is launched within debugging session, it locks PDB file, preventing GDextension compilation

Very similar issue with DLL blocking was fixed recently in this PR: https://github.com/godotengine/godot/pull/80188. That works fine when Editor launched without debugger, but with debugger it also blocks PDB. Could we copy it the same way?

### Steps to reproduce

1. checkout godot master branch
2. compile it with `scons dev_build=yes debug_symbols=yes platform=windows compiledb=yes -j8`
3. get some gdextension. dodge-the-creeps example from gdext is fine, then `git clone https://github.com/godot-rust/gdext.git && cd gdext/examples/dodge-the-creeps/rust`
4. compile this gdextension `cargo build --package dodge-the-creeps --lib`
5. start editor with attached debugger (I used CLion) `path_to_godot_working_copy\bin\godot.windows.editor.x86_64.exe --editor --path ../godot` (that's path from `rust` dir to `gdext/examples/dodge-the-creeps/godot`)
6. wait for scene loading. it should load fine.
6. open `./src/player.rs` (`gdext/examples/dodge-the-creeps/rust/src/player.rs`) in any texty editor and append following line to the end: `impl Player { fn hello() {} }`
7. again compile cargo build --package dodge-the-creeps --lib --features custom-godot
8. get error: `note: LINK : fatal error LNK1201: error writing to program database 'C:\dev\reload_lab\gdext\target\debug\deps\dodge_the_creeps.pdb'; check for insufficient disk space, invalid path, or insufficient privilege`

### Minimal reproduction project

N/A

**Comment by jsjtxietian** [comment]
Ah I remembered that Casey Muratori solved this problem by passing the some pdb related parameter to cl (%random%  to make pdf has a random name everytime) when recompiling dll. When vs loads the new DLL, it loads the new PDB file as well.

**Comment by dsnopek** [comment]
I don't use Visual Studio (just the command line tools sometimes), so I don't know much about how .pdb files work. Would it be enough to just copy the .pdb file the same as we do with the .dll file (adding `~` in front of it)? Or, would that cause problems because Visual Studio won't know how to find the .pdb file? How does Visual Studio know how to find the .pdb file associated with a .dll?

If VS is finding the .pdb file simply by looking for a file named just like the .dll, such that copying it would work, I think it'd be fine for Godot to copy it if it's present. But I don't know if there's more to it than that.

**Comment by vnen** [comment]
> Would it be enough to just copy the .pdb file the same as we do with the .dll file (adding `~` in front of it)?

I don't think that would help, AFAIK the PDB path is part of the binary so this would only work if we somehow patched the DLL, which I don't think it is feasible.

I'm not sure what the solution for this would be, if there's even anything that Godot can do about it.

**Comment by dsnopek** [comment]
Perhaps then this is a documentation thing for folks using Visual Studio?

The code snippets folks posted above seem to configure Visual Studio to use a random name for the .pdb file on each compile. Perhaps putting those in the docs somewhere would be sufficient?

(Do those .pdb files with random names get cleaned up eventually, though? Or, does the directory slowly fill up with more and more .pdb files? If so, those code snippets may need some additional improvements, perhaps attempting to clean up all the .pdb files that aren't locked?)

**Comment by DmitriySalnikov** [comment]
As vnen said, the path to the PDB is written inside the DLL.
![image](https://github.com/godotengine/godot/assets/7782218/da840f82-d129-4bf4-b92e-5fecd1a5d803)
Therefore, simply renaming them via Godot will not work. You need to change the build scripts.

I [solved this](https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/e0007bb6bcafbd00436153163f9d5dbb4f4aebf5/lib_utils.py#L61) at the `scons` script level for `godot-cpp`. I think something similar needs to be implemented when building `gdext`.

I can make these changes to the example project in `godot-cpp` (and maybe we need to update the script from the [documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_cpp_example.html#compiling-the-plugin)).

**Comment by kone9** [comment]
> As vnen said, the path to the PDB is written inside the DLL. ![image](https://private-user-images.githubusercontent.com/7782218/289382735-da840f82-d129-4bf4-b92e-5fecd1a5d803.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDE3MjEsIm5iZiI6MTcwMjI0MTQyMSwicGF0aCI6Ii83NzgyMjE4LzI4OTM4MjczNS1kYTg0MGY4Mi1kMTI5LTRiZjQtYjkyZS01ZmVjZDFhNWQ4MDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTBUMjA1MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY4ZTAwOWYyZWVkODUyOGI1MDRkNGEzMzg0MmE2NzUxMGQ2OGVmZjRhNDRmYzA1YjhiYTU1MGU0YThiNTc2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7asxDMaaZ1v4MnKIOaZKOtuxGmpAAqFHa2Lld4OkDyE) Therefore, simply renaming them via Godot will not work. You need to change the build scripts.
> 
> I [solved this](https://github.com/DmitriySalnikov/godot_debug_draw_3d/blob/e0007bb6bcafbd00436153163f9d5dbb4f4aebf5/lib_utils.py#L61) at the `scons` script level for `godot-cpp`. I think something similar needs to be implemented when building `gdext`.
> 
> I can make these changes to the example project in `godot-cpp` (and maybe we need to update the script from the [documentation](https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_cpp_example.html#compiling-the-plugin)).

Here you have a correctly working Scontructor rewritten by you, thank you very much.
https://gitlab.com/kone9/godot-engine-4.2-template-gdextension-with-vscode-windows-11/-/blob/main/SConstruct?ref_type=heads


and here a template with preconfigured Vscode.
https://gitlab.com/kone9/godot-engine-4.2-template-gdextension-with-vscode-windows-11

**Comment by vnen** [comment]
I thought just occurred to me that the Windows API has some stuff to handle the PE format (which includes DLLs), so it might be possible to actually patch the copied DLL and change its PDB. This is kind of like how rcedit works, though itself doesn't provide anything about PDB. I'm not sure if it is a regular resource string, but if it is then it's possible to edit.

Naturally, this would be Windows only since it relies on the Windows API, but this problem happens only on Windows anyway.

I'll try to test this later.

**Comment by DmitriySalnikov** [comment]
The path to the PDB is stored somewhere at the end of the file with the label `RSDS`. https://godevtool.com/Other/pdb.htm
I have checked several of my C++ and C# DLLs and even Rust DLLs and in them the label `RSDS` is either present only once or missing.

---

It looks like you can safely replace the name of the PDB by editing the DLL file. The debugger finds the PDB by its new name and blocks it.
![image](https://github.com/godotengine/godot/assets/7782218/f9a59a4f-fe0c-40f7-86e3-938462372459)
![image](https://github.com/godotengine/godot/assets/7782218/a6fbaf3d-52b1-49c4-a620-dd9b266b8cd1)

But most likely you cannot change the length of the original string, usually this should not be a problem. And I do not know what is between the `RSDS` and the path string, and whether the size of this gap can vary ([found this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.symbols.dkmpdbfileid?view=visualstudiosdk-2022)).

Also, information about `RSDS` can be obtained via `dumpbin /headers <path-to-dll> | findstr RSDS`

**Comment by vnen** [comment]
I tested and it's not included in the resources, so my original idea can't really work.

However, as @DmitriySalnikov points out, this information is in the headers of the DLL. We can do a similar thing to figure out where the specific header is and patch it. I've found [this project](https://sourceforge.net/projects/debugdir/) which removes the PDB path and I believe something similar can be done to replace it instead.

This is a complex approach, but I think it's safer than trying to patch the binary directly at some arbitrary address.

**Comment by DmitriySalnikov** [comment]
I made my project to test the idea of replacing the `PDB` path inside the `DLL` (and `EXE`..) https://github.com/DmitriySalnikov/RenameAndCopyPDB
[Action](https://github.com/DmitriySalnikov/RenameAndCopyPDB/actions/runs/7233717821)

This project copies the `DLL` with the prefix `~` and also creates new `PDB`s up to `*_999.pdb` and deletes old files except the newest one based on the time of change. Supports UTF (tested with the name `libdd3d.windows.editor.x86_64_юникод_çã.dll` ).

Limitations:
* The bitness of the `DLL` should be like that of the program.
* The length of the `PDB` string inside the `DLL` must be greater than 8 characters to use the prefix and 4 additional characters. This should not be a problem because an absolute path is usually specified.

Testing:

https://github.com/godotengine/godot/assets/7782218/e057a5c5-f2f3-4946-a917-33e485d5335a

Is it worth trying to port this to Godot?

**Comment by dsnopek** [comment]
@DmitriySalnikov:

> Is it worth trying to port this to Godot?

The code in your test project doesn't seem overly large or complex. Personally, I think it'd be worth try to port to Godot.

This feature is only useful to MSVC users, but it seems like the impact would be minimal, both as far as code maintenance (since it looks pretty simple) and performance (since this only needs to be attempted once per reloadable GDExtension on editor startup), so I'd be for it.

**Comment by DmitriySalnikov** [comment]
@kkolyan can you check if #87117 fixes your problem?
