### ISSUE TITLE
[Suggestion] Add get_drag_data as a signal

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#8255]
`get_drag_data` apparently only works if you attach a script to a Control inherited node.  I'm suggesting the ability to use `get_drag_data` as a signal, example:

`control.connect("get_drag_data", self, "FunctionName")`

Very useful for dynamically created UI elements! Instead of attaching a `.gd` script to 64 Inventory boxes, we can just  connect a signal.  Not sure about performance, but I think it'd be nicer to work with

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
