### ISSUE TITLE
NavigationAgent2D does not avoid NavigationObstacle2D

### ISSUE THREAD

**Issue by coder137** [godotengine/godot#82562]
### Godot version

4.2-dev5

### System information

Windows10

### Issue description

NavigationAgent2D does not avoid NavigationObstacle2D (static or dynamic)

### Steps to reproduce

1. Created a dynamic obstacle (by setting the radius tab)
2. Created a static obstacle (by adding vertices in the clockwise direction)
3. Make 2 NavigationAgent2D agents move from point A to B, adding the obstacle in the middle
4. Agents do not route around the obstacle
5. **This is not reproducible all the time**

### Minimal reproduction project

[Tilemap.zip](https://github.com/godotengine/godot/files/12773112/Tilemap.zip)

## Other issues seen with the same project

- [ ] NavigationAgent2D sometimes tries to avoid dynamic NavigationObstacle2D, but can get stuck behind it
- [ ] Moving from one NavigationRegion2D to the other (when edge is connected) can cause NavigationAgent2D to slow down or get stuck

![image](https://github.com/godotengine/godot/assets/10407715/21778c77-b0fb-4a57-b235-459acfb0221a)

**Comment by smix8** [comment]
> Agents do not route around the obstacle

The NavigationObstacle2D has scaled visuals from the inherited Node2D scale.
The actual obstacle on the navigation map created with this radius / those vertices is tiny and so it is mostly ignored by the agents.

Agents do not "route" in the sense of planning a different path around the obstacle.
The obstacle pushes back the avoidance velocity of the agent.

If the navigation path points through the obstacle, because there is still navigation mesh below it, there is only so much the avoidance can do to make agents "route" around it.

**Comment by coder137** [comment]
Thanks for the explanation, That makes sense.
Closing this issue
