### ISSUE TITLE
Automatically cast parameter throws "Cannot convert argument 1 from Object to Object" error

### ISSUE THREAD

**Issue by fuelyourdev** [godotengine/godot#82572]
### Godot version

v4.1.1.stable.official

### System information

Windows 10

### Issue description

In the [documentation for static typing](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/static_typing.html#typed-or-dynamic-stick-to-one-style) it states:

> You're free to replace, e.g. the `CollisionObject2D`, with your own type, to cast parameters automatically:
> 
> ```
> func _on_area_entered(bullet: Bullet) -> void:
>    if not bullet:
>        return
>
>    take_damage(bullet.damage)
> ```
> The `bullet` variable could hold any `CollisionObject2D` here, but we make sure it is our `Bullet`, a node we created for our project. If it's anything else, like an `Area2D`, or any node that doesn't extend `Bullet`, the `bullet` variable will be `null`.

In testing this myself I created a Player class:

```
extends CharacterBody2D

class_name Player

...

func game_over():
	get_tree().reload_current_scene()

...
```

And a spike class that would detect the player and call the `game_over` method:

```
extends Area2D

func _on_body_entered(player: Player) -> void:
	if not player:
		return
	player.game_over()
```

Now this method detects the player collision and calls the game over method just as expected. But when it collides with something else (In my case specifically, it was overlapping slightly with the TileMap, and was getting a collision from it when the level was loaded), then it would throw the following error:

```
E 0:00:00:0818   emit_signalp: Error calling from signal 'body_entered' to callable: 'Area2D(Spikes.gd)::_on_body_entered': Cannot convert argument 1 from Object to Object.
  <C++ Source>   core/object/object.cpp:1082 @ emit_signalp()
```

Now ultimately it simply ignores the error and game keeps going and nothing is broken, but I believe that is is a bug that it is throwing this error at all considering what's written in the documentation. But this runs the risk of false errors clogging up the output, making it difficult to spot real errors

Also note that if I instead follow the other example from the documentation making use of the `as` casting:

```
extends Area2D

func _on_body_entered(body: Node2D) -> void:
	var player := body as Player
	if not player:
		return
	player.game_over()
```

Then I get no error. Based off of the documentation I would have expected the same from the auto-casted parameters.

I've [found old, closed issues](https://github.com/godotengine/godot/issues/26047) that seem to be related, but nothing that is currently open. So I'm creating this issue to report it.

### Steps to reproduce

Player.gd
```
extends CharacterBody2D

class_name Player

...

func game_over():
	get_tree().reload_current_scene()

...
```

Spike.gd
```
extends Area2D

func _on_body_entered(player: Player) -> void:
	if not player:
		return
	player.game_over()
```

Have spike collide with something other than the player (for instance, a TileMap).

### Minimal reproduction project

N/A

**Comment by dalexeev** [comment]
Perhaps this is a bug in the documentation, not in GDScript. But it's worth checking how it works in 3.x. Personally, I prefer the current behavior, silent error suppression where you might accidentally specify a wrong subtype is not good.

**Comment by fuelyourdev** [comment]
I went ahead and created the same simple project in both Godot v3.5.3.stable.official and Godot v4.1.1.stable.official. I've attached both projects. In both projects, the spike overlaps the tilemap, so the scenario occurs immediately after running.

The Godot 3.5 project works exactly as I would expect based on the documentation. There is no error thrown, and from the print statement we can see that the `_on_body_entered` method was called with a `null` player parameter, exactly like the documentation states.

The Godot 4.1 project, on the other hand, throws the aforementioned error, and never enters the function, as demonstrated by the lack of the print statement in the logs.

[AutoCastParams_3_5.zip](https://github.com/godotengine/godot/files/12774206/AutoCastParams_3_5.zip)
[AutoCastParams_4_1.zip](https://github.com/godotengine/godot/files/12774207/AutoCastParams_4_1.zip)

So while I can see your point of view, I don't agree with it. I don't expect features to throw errors when they are used as documented and intended. I could perhaps understand a warning, if the feature isn't the best recommended way, or if you need the user to exercise caution when using it, especially if there's an official way to acknowledge and ignore the warning (like the `@ignore` in Java or something similar). But not a full out error, especially when the error message isn't the especially clear on what it expects from the user to fix it.

**Comment by fuelyourdev** [comment]
Adding some screenshots for easy reference

v3.5.3.stable
![image](https://github.com/godotengine/godot/assets/49111720/d8bc7def-8725-4865-9921-6e7386077133)

v4.1.1.stable
![image](https://github.com/godotengine/godot/assets/49111720/65698197-d017-4ae2-8acc-21248fab1ece)
![image](https://github.com/godotengine/godot/assets/49111720/66c6e390-ff7c-464e-9226-0ce090d1a035)

**Comment by dalexeev** [comment]
> So while I can see your point of view, I don't agree with it. I don't expect features to throw errors when they are used as documented and intended.

The problem is that in 3.x this affects not only functions like `_on_body_entered()`, but any functions. For example:

```gdscript
func f(x: Node2D) -> void:
    print(x)

func _ready() -> void:
    var t = Node.new()
    f(t)
```

In 3.x this code just prints "Null" without any error/warning. In 4.x this results in a runtime error "Invalid type in function 'f' in base 'Node (node.gd)'. The Object-derived class of argument 1 (Node) is not a subclass of the expected argument class.".

Regardless of what the documentation says, I'm sure many users who prefer static typing will say that 4.x behavior is more correct than 3.x behavior. Because that's how statically typed languages basically work, and it makes it easier for you to find errors. You don't have to wonder why a variable is unexpectedly `null`, sometimes in a completely different place.

> I don't expect features to throw errors when they are used as documented and intended.

I don't think it was really intentional. Static typing was introduced to GDScript in Godot 3.1 and was added on top of the existing implementation. Some things are bugs, some are would be difficult to implement. This is why GDScript was largely rewritten for release 4.0.

The documentation simply reflects that state, regardless of the reasons why we arrived at it. Documentation is always updated with some delay and may itself have errors. Not everything written in the documentation is actual and/or intended behavior.

> I could perhaps understand a warning

Currently there are no runtime warnings in GDscript, only errors. Warnings are generated by the parser and static analyzer, so this cannot be handled/ignored using the warning system.

Also note that type hints (what you write after `:` or `->`) are **not** a type cast. We have a type cast operator `as`, which behaves exactly as you'd expect (silently casting objects to `null` if the runtime type doesn't match). If we wanted to have this feature for function parameters in the language, I would prefer a separate syntax like:

```gdscript
func f(param as Node2D, optional_param as Node3D = null) -> void:
    pass
```

But this is proposal material, I'm not sure this feature is a good idea and good code style.

So, I believe this is outdated documentation and not a GDScript bug.

**Comment by fuelyourdev** [comment]
> The problem is that in 3.x this affects not only functions like _on_body_entered(), but any functions.

I absolutely agree with you on the example given here and expected functionality of functions in general. 

> I'm sure many users who prefer static typing will say that 4.x behavior is more correct than 3.x behavior. Because that's how statically typed languages basically work, and it makes it easier for you to find errors.

As someone that has used statically typed languages for majority of my career (mainly Java), I can't fully agree with this. It very much depends on the scenario. Let me see if I can explain.

So most languages don't have methods that are automatically called by a system outside your control, except for the initial entry point (i.e. `main` in Java), so a direct comparison there doesn't work. 

But where these kinds of methods do show up is in frameworks, and that's where I'll be drawing my comparisons from.

In java one of the most popular frameworks is Spring, and it does give you the ability to define methods that will then be called by the framework. It will look up the methods you defined via reflection and then populate the method parameters based on the data available in the system and the rules that you've defined for the method

The most common scenario involves taking user input (frequently in JSON), and automatically mapping that to specific classes that are then passed to the controller methods as parameters.

In this framework, if something isn't present in the JSON, then that comes through as a null parameter to the controller method. This is how end users can pass in optional parameters. If we want to ensure that a user always passes in that parameter, the we can use the `@NotNull` annotation, and if the data is missing, then at that point the framework would throw a runtime exception, which we would catch and return to the end user to let them know they need to fix the data in their call.

Also the framework will automatically take the data given and transform/cast the data into the class defined in the method signature. No special casting syntax required (outside perhaps some annotations to provide extra context as needed). So `method(param : Type)` is perfectly acceptable in the context of statically typed languages, no need for a special `method(param as Type)` syntax.

So based off of this I'd say that there is a very large precedent for this kind of functionality in the world of statically typed languages.

So let's take a step back into the world of Godot. Under what circumstances would a programmer choose to make the parameter more specific than the `Node2D` given by the method definition (or `CollisionObject2D` stated in the documentation)? Only two scenarios come to mind: either it's programmer error, or the programmer intentionally only wants to process signals with that specific type, with the intention to ignore others (syntactic sugar, essentially).

Let's start by looking at the programmer error scenario. In this scenario the programmer mistakenly makes the parameter type too specific such that the method can no longer handle all possible types and will cause errors. This is the current scenario for Godot 4.1, and the position that you are advocating for, so far as my understanding goes. Under this scenario, the programmer should not make the type more specific than what the signal allows for, and the fix for the error is for the user to change their code away from the more specific (`Player`) to the more generic (`Node2D`).

This is one way to go, and isn't wrong per se, but I'd argue that if this is the intended direction,  then this should be a syntax error, not a runtime error. We know up front what the acceptable types are, and could give the user an error as soon as they write it. This is far better than a runtime error that may or may not occur depending on circumstances. So I'd argue that even if this is the intended path, that there is still a bug here due to the error not being caught earlier.  (I mean, that's the whole point of statically typed languages, right? )

Now let's explore the path of the syntactic sugar feature. Under this path, it becomes shorthand for filtering signals that the user doesn't care about while automatically casting the ones that they do care about. There's technically two ways to go about adding such a feature. 

One is send signals that don't match the type through as null. This is what Godot 3.5 does. It works. It saves you the type cast, but you do still have to null check. It's an acceptable implementation.

The other is for the framework to determine that the signal type does not match the parameter type, and then intentionally choose to not call the method in that scenario. This would allow the syntactic sugar to also eliminate the null check, allowing for even cleaner code. If I were intentionally implementing this feature, this is the way that I would choose to go.

As it stands, Godot 4.1 kind of does this, but not because it's intelligently choosing to do so. It instead attempts to make the call,  fails hard, then picks itself up and keeps going. It likely would be fairly straightforward to add it in this way to Godot 4.1 just by adding a couple of checks prior to making the call. Honestly, this is what my vote personally would be for (for what that's worth).

I ultimately would be fine with any of the three above options (syntax error immediately reported to user, syntactic sugar using nulls, or syntactic sugar filtering calls).

What I'd be less fine with is leaving it as a runtime error, because it gives more potential to hide bugs, making fixes more difficult in the long run. (Note that this could be acceptable in the short term, so long as the syntax error check is in the long term plans.)

I'd also be very much against any scenario where we end up saying "it's a feature, you just have to ignore the errors that it throws", especially if there is no way catch the error or to explicitly mark the error as ignored.  Errors should always indicate something needs to be fixed (either in the game or in Godot itself), errors should never be something to be ignored. A properly functioning system should not have it's logs clogged with constantly incoming errors.

Hopefully I was able to make these points clear and understandable.

**Comment by dalexeev** [comment]
I think there is some misunderstanding about how this works, why in some cases there are compile time errors/warnings, and in other cases errors occur only at runtime. In any case, I think that most will agree that there should be an error here at least in runtime, if it cannot be detected during compilation. 3.x behavior is worse because there is no error at all. Only the `as` operator has this semantics. And therefore the operator should be used very carefully.

When overriding a method, you cannot specify a more specific parameter type; this will result in a compile time error. Godot requires you to specify an equal type for a parameter or you can not specify the type. (Plus recently we added support for contravariant parameter types and covariant return type.)

However, methods like `_on_body_entered()` are not overrides of existing methods, they are definitions of new methods that can have any signature. Also signals (both in core and in GDScript) are not really typed, the types are just metadata. When connecting/emitting a signal, the compliance of the number and types of its parameters with the method signature is not checked. This cannot be checked at compile time, the script does not know which scene it is attached to, connections are part of scenes, not scripts.

Also, when calling a method, the static analyzer checks the types of the arguments passed and generates compile time errors if possible. But if the passed parameter is untyped or is a supertype, then you only get `UNSAFE_*` warnings (disabled by default) and a runtime error if the actual type does not match.

**Comment by fuelyourdev** [comment]
I mean, there are a number of assumptions in your response. Under the assumption that it is a bug and not a feature/syntactic sugar, then yes, absolutly a runtime exception is better than nothing.

Now of course that is stil inferior to any error that would give that information sooner, such as a syntax error. Now as you've shared, with these being methods that are defined separately and then hooked into signals, a syntax error specifically might not be the appropriate method here, but other options could be possible. 

Possibly when hooking a method to a signal, it won't allow you to hook into a method that has an incorrect type, for instance.

Now of course, just because a suggestion like the above is possible, that won't necessarily mean that it's practical or worth the time investment. (As you mentioned, the information on the signal is metadata, which may likely complicate any such implementation.)

Under such conditions, then sure, a runtime exception is acceptable. Not ideal by any means, but good enough considering the tradeoffs.

Under these circumstances, it then does become important to ensure that the documentation is properly up to date, since the exception is less reliable. This is of course the fix that you've suggested, to update the documentation.

This is, of course, all under the assumption that auto cast parameters are a bug, not a feature. I still don't necessarily agree with that assumption, but I don't expect to change your mind on that point, so I'll stop talking to that point. I've already expressed my opinion on it, and I'll leave it at that.
