### ISSUE TITLE
get_current_play_position() always returns 0 for all looping animations

### ISSUE THREAD

**Issue by lullabyist** [godotengine/godot#82581]
### Godot version

Godot v4.1.1.stable

### System information

Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.3713) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

When $AnimationTree["parameters/playback"].get_current_play_position() is called during playback of any animation that is set to loop, it always returns 0. This makes it impossible to track animation progress or intercept animations mid-cycle through code.

I have a complex project that has a looping walk cycles that require continuous step tracking, so animations can be queued against the player's left or right foot. To do this, I need to call get_current_play_position() every frame to know when the legs switch over. In 3.5, this function works as expected, and I cannot port my project over to 4 between this and #75825.

### Steps to reproduce

1. Open minimal reproduction project.
2. Run it once and observe as console continuously returns 0 for the looped idle animation.
3. Uncomment line 11: state_machine.travel("jump"), to travel to an unlooped animation.
4. Run again, observe get_current_play_position() now prints values in console from 0 to 0.5.

### Minimal reproduction project

[get_current_play_position() returns 0.zip](https://github.com/godotengine/godot/files/12774473/get_current_play_position.returns.0.zip)

**Comment by jsjtxietian** [comment]
Confirmed.

Looks like godot will return a huge number for a looped anim —— `return is_looping ? HUGE_LENGTH : anim_size - cur_time;` 
Looks like it's by design. Although I still think it's a bug.

**Comment by TokageItLab** [comment]
HUGE_LENGTH is not related. The current_position should not have been allowed to be acquired in the first place.

**Comment by lullabyist** [comment]
@TokageItLab Please stop closing my issues without so much as a discussion. It's really frustrating, you did the same with #75843 which now is back to normal in 4.1.

**Comment by TokageItLab** [comment]
Isn't this the same with https://github.com/godotengine/godot/issues/23629#issuecomment-1001020829? I have been asked that many times and I remember there was no published method to get the playback position of a particular node.

**Comment by AThousandShips** [comment]
This method [does exist](https://docs.godotengine.org/en/stable/classes/class_animationnodestatemachineplayback.html#class-animationnodestatemachineplayback-method-get-current-play-position) though and has since at least 3.4

**Comment by TokageItLab** [comment]
Ah I see, so StateMachine has its own  time. Sorry for my misunderstood.

But this probably doesn't get the correct time due to (or even before) the reworking by https://github.com/godotengine/godot/pull/75759. When it transitions without a reset, it does not remember the original length of the state because the current time is zero at the moment of transition.

For example, if you leave at 2s in a 10s state and come back to that state without resetting, you will be recognized as being at 0s in an 8s state.

Also, in looping, the current time could be an illegal value due to the infinite length of the current loop due to HUGE_LENGTH.

I believe in order to make those time retrieve properly, it must be necessary to have each Node have the correct time, as mentioned in the comment https://github.com/godotengine/godot-proposals/issues/7867#issuecomment-1734847806. In any case, there is currently no semantic way to get the time of any AnimationNode.

**Comment by lullabyist** [comment]
In 3.5 the playback position always resets to 0 after every loop. So getting a value from 0 to 1 which can then be put to use is simple as `$AnimationTree["parameters/playback"].get_current_play_position()/$AnimationTree["parameters/playback"].get_current_length()`

It's so silly that in 4 even the bar in the UI doesn't loop.
![loop-godot35](https://github.com/godotengine/godot/assets/9658355/8eca76ea-6613-4a3a-8384-2c5eaae30893)
![loop-godot41](https://github.com/godotengine/godot/assets/9658355/e4f595ad-ccd3-4121-b14e-8c0ecaa380ab)

**Comment by lullabyist** [comment]
Unfortunately, this means Godot 4's AnimationTree is immature for any game with a moderately complex state machine. Even with whatever suboptimal code 3.5 may have had, it was extremely reliable for my project.

The workflow I'm describing isn't niche, just one that would become a problem fairly late into development, once animation seams start getting stitched together. I don't mind sticking to 3.5 for now, but I think it should be noted in [the docs](https://docs.godotengine.org/en/stable/classes/class_animationnodestatemachineplayback.html#class-animationnodestatemachineplayback-method-get-current-play-position) that the get_current_play_position function is non-functional, if only to deter anyone that might start a project in 4 expecting it to work.

**Comment by elXill** [comment]
@lullabyist  I want to do this as well, get name of the animation and frame, to see how transitions going for debuging/checking purposes. While getting them from engine would be best, I have a "bad" solution for this which is using animation_started and animation_finished signals and counting frames inbetween from _physics_process. I will play around with this more later on but for now it doesn't look bad.. You may wanna try to use it like that if your project doesn't need to be too precise.

**Comment by TokageItLab** [comment]
> suboptimal code 3.5 may have had, it was extremely reliable for my project

As I mentioned above, the current AnimationNode is not linked to any Animation resource other than AnimationNodeAnimation (e.g., NodeBlend2, NodeStateMachine and etc), so it is not possible to get the exact elapsed time for a specific animation.

The 3.x method may work to some extent, but you should be aware that it does not "directly" retrieve the animation's time. It would be working on the unstable scaffolding of the constraint that the AnimationStateMachine "force to reset any State". But this scaffold has already fallen.

I agree that StateMachine is still not mature, but counting elapsed time on the restriction of forced resets as in 3.x, is completely useless in some cases due to the behavior of forced resets.

> While getting them from engine would be best, I have a "bad" solution for this which is using animation_started and animation_finished signals and counting frames inbetween from _physics_process.

While this approach may work to some extent, it has the restriction that it is not possible to distinguish between them in the case of multiple same animations.

A fundamental problem with the current AnimationTree is that the only time information propagated downstream is "remaining time" and "seeked or not". This means, when "animation length" or "current time" is needed, there is no way to retrieve them downstream, and the only way is to _estimate_ them from the "remaining time" and "seeked" information although it is unsafe.

For animation length, there is also a lack of "selectivity" as to which length should be prioritized when blending short animations and long animations. Currently, the longer animations are basically forced to take precedence, and we prioritize the "looping or not" over the "remaining time" by using HUGE_LENGTH.

Ideally, they should have been propagated separately, but the current AnimationTree cannot, so to stabilize something is forced to sacrifice something. This is why huge refactoring is needed and why this problem is so hard to solve.

**Comment by lullabyist** [comment]
Thank you so much @TokageItLab
