### ISSUE TITLE
3.0 - (API name change) vec.normalized() should be named vec.normalize() ?

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8267]
More of a feedback for API than bug. :)

Current name is past tense, looks more like a check, than a command to do something.

**Comment by akien-mga** [comment]
Well actually you could expect `vec.normalize()` to normalize (and thus modify) `vec`, which it does not. Instead, it gives you a *normalized* copy of `vec`, so you have to use e.g. `var vec2 = vec.normalized()`. That's how I understand it at least.

**Comment by Zylann** [comment]
Aren't the two variants available? I think they make sense.

**Comment by hubbyist** [comment]
get_normalised_copy() may be a more explanatory name may be?

**Comment by toger5** [comment]
i think using past is pretty commen for non mutating functions. it makes sense to me. I didnt made the reseaech but isnt that kind of naming used all over the API? if we switch to: get_normalized_copy we have to change it everywhere.

Although thinking about it: i actually like the get keyword. It makes clear that it returns a new vec and as a consequence it is obvious that the source vector is not touched. the copy part though is kind of redundant and makes it too long in my opinion.

What about a property based approach: (this is always my favoeite)
var a = Vec2()
var a_n = a.normalized
Its basically the same than before bit since we are acessing a property its more obvious that it doesnt change the vector a.

**Comment by n-pigeon** [comment]
Maybe problem is that other non mutating functions are not in past tense.
For example in Vector3: slide(), reflect(), floor(), inverse()
They just give me new Vec3. I know that because there is return type in docs.

Vector3 	inverse ( )
Vector3 	reflect ( Vector3 by )
Vector3 	slide ( Vector3 by )

There are non mutating functions that are in past tense:

Vector3 	rotated ( Vector3 axis, float phi )
Vector3 	snapped ( float by )

But what to do with math type functions like:

Vector3 	abs ( )
Vector3 	ceil ( )
Vector3 	cross ( Vector3 b )
Vector3 	floor ( )
Vector3 	inverse ( )

Any idea how or should we clean this up?

**Comment by hubbyist** [comment]
There is just one char between `rotated` and `rotate`. If copying data is an special behavior, then `_copy` or `_clone` suffix for exceptional functions will make distinction clear both in code and in convention I think.

**Comment by bojidar-bg** [comment]
Well, there is no `.rotate()` anyway, so that's a non-issue.

**Comment by reduz** [comment]
Naming is correct, because in GDScript Vector3 is an atomic type. there is
no .normalize() , only .normalized() as it returns a value.

**Comment by n-pigeon** [comment]
I think it's clear now why it's called .normalized() and that it is correct. I think it can be closed :)
