### ISSUE TITLE
SystemFont can't load PingFang SC

### ISSUE THREAD

**Issue by abcjjy** [godotengine/godot#82703]
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.1.1.stable - macOS 13.4.0 - Vulkan (Mobile) - dedicated AMD Radeon Pro 560X - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

PingFang SC is listed in the font names and can be added. However, the preview displays PingFang HK and the PingFang HK font is actually used for rendering.

<img width="382" alt="图片" src="https://github.com/godotengine/godot/assets/1791493/9c207a55-98bb-4f20-8f16-d3143a9945d2">
<img width="312" alt="图片" src="https://github.com/godotengine/godot/assets/1791493/e0bc8441-0b18-4e5a-88e0-b4f5c2b59b92">

### Steps to reproduce

Create a system font, choose PingFang SC. This font is the default font for Chinese on Mac and iOS.

### Minimal reproduction project

Trival

**Comment by bruvzg** [comment]
The reason is - this is the same font file with multiple fonts, the correct index is not selected automatically (which is a bug).

As a workaround, you can make a font variation and select index manually (`2` in case of SC variant).

<img width="300" alt="Screenshot 2023-10-03 at 07 59 59" src="https://github.com/godotengine/godot/assets/7645683/1a7f498d-b7fc-430e-989f-447000bb6cb6">
