### ISSUE TITLE
GDExtension - failure to reload classes

### ISSUE THREAD

**Issue by zornigwolf** [godotengine/godot#82738]
### Godot version

4.2.dev.master

### System information

Windows 11 - Godot v4.2.dev.custom_build

### Issue description

When rebuilding the library again, classes are not reloaded. For gdextension, at the very beginning, when moving the libraries bin directory "libgdexample.windows.template_debug.x86_64" and "libgdexample.windows.template_release.x86_64" for gdexample.gdextension everything works as expected, but after rebuilding the libraries they are not connected.

### Steps to reproduce

Step 1: Download code from https://github.com/godotengine/godot/archive/refs/heads/master.zip.
Step 2: Compile the downloaded Godot v4.2 via scons for the Windows platform.
Step 3: Compile the gdextension libraries exactly as shown in the example: https://docs.godotengine.org/en/latest/tutorials/scripting/gdextension/gdextension_cpp_example.html
Step 4: Create a new project in the engine exe file compiled in step 2.
Step 5: Open the root of this project in Explorer and move the libraries created in step 3 there. As a result of our actions, an accessible GDExample node should appear and the picture that we added to the scene will begin to move.
Step 6: In the file "register_types.cpp" comment out the line //ClassDB::register_class<GDExample>(); We return to step 3 and compile the library with these changes.
Step 7: First, copy the files from the project's bin folder to any folder on your desktop (for example, "old"). Then we copy the libraries created after step 6 into the bin folder of our project with replacement. After this, the image stops moving and the GDExample node disappears, since we commented out the class<GDExample> and so far everything seems to be working correctly.
Step 8: Now copy the libraries from the "old" folder (which we created in step 7) to the project's bin folder with replacement. After this, the fun begins - nothing happens. Although now in our project there are libraries with the uncommented line "ClassDB::register_class<GDExample>(); " The picture does not move and the GDExample node is still not in the list. At the moment this can only be corrected by restarting the engine.

### Minimal reproduction project

N/A

**Comment by Remi123** [comment]
I'm not exactly sure if related, but I have an error message stating that my extension is un-reloadable, but I can reload without problem.

```
Godot Engine v4.2.dev6.official.57a6813bb - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080 Ti

ERROR: Extension marked as reloadable, but attempted to register class 'MotionFeature' which doesn't support reloading. Perhaps your language binding don't support it? Reloading disabled for this extension.
   at: _register_extension_class_internal (core/extension/gdextension.cpp:431)
```

**Comment by NEROXI** [comment]
![image](https://github.com/godotengine/godot/assets/39343424/3d3b8aeb-befb-4f2f-b84d-e1d1132b7866)

I have the same problem. The class is loaded only on the first change.
In some cases, when building **Godot-cpp** via **CMake**, the engine began to load the library and crashed. No crash logs were created, the only thing I could get was a Stack Trace in CMD.
**OS**: Windows 11
**Tested on all graphics settings**.

**Comment by dsnopek** [comment]
@zornigwolf:

Hm, a class completely going away on reload, and then coming back on a later reload isn't (currently) supported. If a class doesn't come back in a successful reload, then all the tracking data for it is discarded (and any existing instances are converted to whatever their Godot native parent class is). I guess we could keep the tracking data around so long as we're aware of any instances that still exist? We just don't want to keep it "forever", because then memory usage will continue to grow until the editor is restarted. I'll spend some time thinking about this.

@NEROXI:

This seems like it could be a different issue. What version or commit of godot-cpp are you using? Which compiler are you using to compile your extension?

@Remi123:

> I have an error message stating that my extension is un-reloadable, but I can reload without problem

This is really suprising - if you're seeing that message, it should be disabling reload. Are you using godot-cpp? If so, what version or commit? However, this is also probably a different issue.

**Comment by zornigwolf** [comment]
@dsnopek 
Thank you for attention. The problem in this case is not the loss of data registered for the node. I don't receive any error notifications in my case. At the moment, the problem I encountered is that after the first replacement of libraries in the bin folder, data from the added dll libraries stops being added to godot. Perhaps if you follow the suggested steps you will get a similar result. If you need more details, please tell me what you might need.

**Comment by zornigwolf** [comment]
I suspect the problem may be hidden in this piece of code:
https://github.com/godotengine/godot/blob/42425baa59956dc9d1e22341fe5e5d7f8fad5067/core/extension/gdextension.cpp#L913
Perhaps this can help somehow.
p_extension->update_last_modified_time(MAX(
             FileAccess::get_modified_time(library_path),
             FileAccess::get_modified_time(p_path)));

**Comment by zornigwolf** [comment]
If you change the creation date of the dll libraries to a more recent one in the meta data (for example, by fictitiously editing the file using Notepad), then the changes are loaded correctly and the classes are replaced in the engine.
It might be better to track dll changes using MD5 instead of tracking the creation date of the dlls. But I’m a newbie and I could be wrong, please be understanding)).

**Comment by dsnopek** [comment]
@zornigwolf:

> Perhaps if you follow the suggested steps you will get a similar result.

The thing is, part of what you're describing in the steps to reproduce is something that is known not to be supported - which is what I was attempting to explain in my previous comment.

Specifically, it's this:

> Step 6: In the file "register_types.cpp" comment out the line //ClassDB::register_class(); We return to step 3 and compile the library with these changes.

If you successfully reload a GDExtension, and the new version has completely removed a class, then all instances of that class will be converted to whatever their native base class is. In this case, the `GDExample` class descends from `Sprite2D`, so after the reload, the node will be converted to a `Sprite2D`, and all the tracking information that connected that node to `GDExample` is discarded.

So when you do this step:

> Step 8: Now copy the libraries from the "old" folder (which we created in step 7) to the project's bin folder with replacement. After this, the fun begins - nothing happens. Although now in our project there are libraries with the uncommented line "ClassDB::register_class(); "

The node won't turn back into `GDExample`, it will stay as a `Sprite2D`, because we don't have that tracking information anymore. You could right click the node and select "Change Type" and turn it back into a `GDExample`, but that isn't going to happen automatically.

Like I said in my previous comment:

> I guess we could keep the tracking data around so long as we're aware of any instances that still exist? We just don't want to keep it "forever", because then memory usage will continue to grow until the editor is restarted.

So, we could consider a change, however, I worry that keeping that data around too long is just going to seem like a memory leak. :-)

**Comment by dsnopek** [comment]
> If you change the creation date of the dll libraries to a more recent one in the meta data (for example, by fictitiously editing the file using Notepad), then the changes are loaded correctly and the classes are replaced in the engine.
> It might be better to track dll changes using MD5 instead of tracking the creation date of the dlls. But I’m a newbie and I could be wrong, please be understanding)).
> The problem probably occurs when replacing a more recent dll file with an older one.

Ah, ok, so maybe the problem is that you're on Windows, and you're copying old files per these steps:

> Step 7: First, copy the files from the project's bin folder to any folder on your desktop (for example, "old")
> ...
> Step 8: Now copy the libraries from the "old" folder (which we created in step 7) to the project's bin folder with replacement.

I'm on Linux, and if you copy files, the new copies will have a newer modification date. According to Google, if you copy files on Windows, they will retain their old modification date. :-/

An MD5 hash would work, but I'd worry that it could be a relatively slow check. Perhaps rather than checking if the modification date is newer, we could keep the exact modification dates and check if they are different?

**Comment by zornigwolf** [comment]
@dsnopek

**Comment by zornigwolf** [comment]
I believe that this ticket can be closed, since such an error occurs quite rarely and not for everyone. In my case, I will probably correct the source code for MD5 checking and compile the engine with this change. If I have time :-) Or I will continue to rebuild the dll library to update the creation date. Thank you for your time and work done!

**Comment by dsnopek** [comment]
> I believe that this ticket can be closed, since such an error occurs quite rarely and not for everyone.

I think it still makes sense to try and fix this issue via something like this idea:

> Perhaps rather than checking if the modification date is newer, we could keep the exact modification dates and check if they are different?

That would match how the editor presently checks if resources need to be imported by checking if the modification date has _changed_ (ie not checking if it's newer, just that it's different) on _both_ the file itself and the `*.import` file (ie not trying to combine them into a single modification time like we're doing for GDExtension reloading right now).

I think it'd be a relatively simple change? I'll try to find some time to make a PR for it :-)

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/84315 which should fix the issue with copying files on Windows not causing a reload.
