### ISSUE TITLE
Godot crashes after 1 Gb memory usage is reached

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8279]
Tested on af282b56feb8d84049f911dd1d91d82bd2211727

When running my voxel module, I reached 1 Gb of memory allocated by Godot. Then everytime, Godot crashes with this message:
```
ERROR: All memory pool allocations are in use.
   At: d:\projets\info\godot\engine\godot_fork\core\dvector.h:525
```
Is there a way to get past this limitation? My computer has 4 Gb to spare, and I don't see an option to increase this limit.

Note: I didn't test in 2.x.

**Comment by tagcup** [comment]
[This line](https://github.com/godotengine/godot/blob/af282b56feb8d84049f911dd1d91d82bd2211727/core/dvector.h#L74)?

**Comment by bojidar-bg** [comment]
No, [this line](https://github.com/godotengine/godot/blob/af282b56feb8d84049f911dd1d91d82bd2211727/core/dvector.h#L525).

**Comment by tagcup** [comment]
No, I'm referring to the question "Is there a way to get past this limitation?"

**Comment by Zylann** [comment]
The error is to be expected if Godot actually handles a memory limit. However that limit is too low for desktop computers :/

**Comment by tagcup** [comment]
Should it be made into a build setting?

**Comment by Zylann** [comment]
Eventually, though I would expect it to work in editor too

**Comment by tagcup** [comment]
Ah, yes, I meant something like an export option, from the editor.

I'm just guessing but maybe it's because an error message is better than platform-dependent behaviour. In [Linux](https://www.kernel.org/doc/Documentation/vm/overcommit-accounting), malloc won't fail for example, and yet the process can crash when you try to access the memory.

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by Zylann** [comment]
This issue happened before we find a bad leak in PoolVectors, so I assume that was the cause.

**Comment by kubecz3k** [comment]
@Zylann well I will close for now in such case. If you will find anything suspicious we will reopen.

**Comment by Ranoller** [comment]
I don´t know how i arrive to this closed issue, but at 01/09/2018 the 1GB limitation (at least in editor) is still present. I let this for googling-githubing purposes.

**Comment by Zylann** [comment]
@Ranoller do you have a repro suite?

**Comment by Ranoller** [comment]
@Zylann 

follow 
https://github.com/godotengine/godot/issues/21393
https://github.com/godotengine/godot/issues/9815

I don´t have a shareable minimal project, only my game, but this 1GB crash is reproducible only doing preloads in any script, it´s not necessary play project, only writing preloads and look task manager, once 1GB editor will crash anywhere....   I say 1GB crash but it´s different in 32 and 64 bit versions and different if you crash editor or if you crash game in runtime: crashing godot appending to an array "0" in runtime allow to allocate 2GB in 64 bit and 512 MB in 32 bit... this test is old (the preload test it´s my project from 2.0 and my project from 3.0 and both crash, last test i did was 8 days ago (first link).

I wil do a test for share because this issues are significant...

**Comment by Ranoller** [comment]
@Zylann 

There is the test:
https://github.com/Ranoller/Godot_crash_memory_test

In my system (64bit) it´s until 2.2 GB of memory that godot crash. I didn´t test that in 32 because i don´t have in home any computer with 32 bit system and i´m in holidays.

**Comment by Ranoller** [comment]
Ok, my test it´s wrong. I investigate the main cause of the 2,2GB of godot crash and i find that an app can´t allocate more that this amount in a single array in windows (windows limit)... so i did more test and godot allocate 4,6,8,10 GB if any array doesn´t have more that 2.2GB... so problems with preloads, etc... will be others that memory allocating.... 

I will actualize my test anyway to have a real example to test if godot can eat your entire memory without    leave any crumbs.

**Comment by olehpatrushev** [comment]
Got the same error on Godot 3.3.3 with Ubuntu 20.04 LTS during a navmesh baking (for large mesh).

**Comment by Calinou** [comment]
> Got the same error on Godot 3.3.3 with Ubuntu 20.04 LTS during a navmesh baking (for large mesh).

This is being tracked in https://github.com/godotengine/godot/issues/37154.
