### ISSUE TITLE
When using a Node exported through a Resource, you can not listen to its signals.

### ISSUE THREAD

**Issue by SwatDoge** [godotengine/godot#82809]
### Godot version

4.1.1.stable

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.3168) - 12th Gen Intel(R) Core(TM) i9-12900K (24 Threads)

### Issue description

With the code below, if you select a node and a signal name, it will await the execution of the signal correctly.

```GDScript
@export var signal_node: Node
@export var signal_name: String = ""

func _ready():
   await signal_node[signal_name]
   print("Signal happened!")
```

If I now move these exports to a Resource class, the code will no longer work:

```GDScript
class_name SignalInput
extends Resource

@export var node: Node
@export var name: String = ""
```

```GDScript
@export var signal_input: SignalInput

func _ready():
   await signal_input.node[signal_input.name]
   print("This will never show up")
```

### Steps to reproduce

```GDScript
# SignalInput.gd
class_name SignalInput
extends Resource

@export var node: Node
@export var name: String = ""

```

```GDScript
# main.gd
extends Control

@export var signal_input: SignalInput ## (Node: Set to a timer node, Name: "timeout")

@onready var timer = $Timer

func _ready():
	await signal_input.node[signal_input.name] ## await timer.timeout
	print("[Method 1] Resource signal, will not appear") ## this should never run
```

### Minimal reproduction project

[source.zip](https://github.com/godotengine/godot/files/12807026/source.zip)

**Comment by dalexeev** [comment]
I think this is not a bug, but rather an limitation. Exported nodes are [serialized as `NodePath`s](https://github.com/godotengine/godot/pull/62185), not as objects. In the case of resources, you cannot access an outer node, this makes little sense since several nodes can use the same resource. So I think we should document the limitation, and also add an error/warning to GDScript if a non-`Node` derived class exports nodes.

**Comment by aXu-AP** [comment]
I also encountered this limitation, ended up working around it by having the resource's owner pass a reference to the tree for resource to actually get the nodes. The exported values have to be NodePaths like in good old days.

I didn't get yet around to make an issue for it, but if you debug what's actually going on, it seems that your Resource creates just `Node.new()` instead of getting the actual node - that's why no errors are raised when trying to connect the signal.
