### ISSUE TITLE
Godot 4.1.2 crashes on multiple screens when saving files

### ISSUE THREAD

**Issue by KiSetsuFu-PuLiN** [godotengine/godot#83005]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Windows 10 - Godot v4.1.2.stable

### Issue description

When the Godot editor is in an external screen and attempts to save a file, the editor will become unresponsive and freeze.[](url)

### Steps to reproduce

0. My computer is Dell G7 notebook with RTX2060, and an external display is connected, with its layout as indicated by "2" in the following figure. My laptop's screen is the main screen and marked as "1" in the following image.
![{C895B16A-AC83-4AC2-A60E-14CE8D7A7D63} png](https://github.com/godotengine/godot/assets/74347594/ca24f388-6f0e-495b-9f07-c2b593414419)
1. Double  click `*.godot` file to open the Godot Editor window, or just open the Godot engine project manager window by start Godot Editor directly.
2. Drag the window onto the external screen "2".
3. Press Ctrl+s to attempt to save a file.
4. Then the window will become unresponsive.

### Minimal reproduction project

This situation can occur in any project, even in the Godot engine project manager, when pressing Ctrl+s while the project manager is on external screen.

**Comment by Zireael07** [comment]
It's lkely not a crash, it's probably the saving popup displaying on a wrong monitor or in a place offset too much.

**Comment by HaydaRinna** [comment]
Similar problem happens with me but with Add Node interface instead of the Save interface.

What Zireael said is probably correct but once you click anywhere while the invisible popup is still open, it becomes impossible to ever interact with the popup window, forcing you to end task.

When I click "Add Node" while the Editor window is on the Screen 2, Screen 1 will flash for a moment and the editor window will become unresponsive. The window can still be resized and everything in the UI will update correctly so it's hard to call it a crash or freeze but there is no way to interact with anything.

I think I found kind of a workaround:

1. While the Godot Editor is on the main monitor, do the action that freezes the Editor. The window should open normally.
2. Carry the popup window to "Screen 2"
3. Close the  popup window
4. Carry the Editor to Screen 2
5. Opening the same popup window will work now.

This is still a serious bug, once you open a window within the engine and it is invisible and you click on the Editor or any other running program, there is no other way of focusing the now invisible window.

I'm also on Win10, Godot ver. 4.1.2

**Comment by KiSetsuFu-PuLiN** [comment]
> It's lkely not a crash, it's probably the saving popup displaying on a wrong monitor or in a place offset too much.

Yes, this is my first time submitting an issue, and my description is not accurate. The program did not crash, but it was unresponsive.

**Comment by HaydaRinna** [comment]
I might have found a more reliable solution.
In Editor Settings > Interface > Editor
Enabling "Single Window Mode" might permanently fix the issue.

**Comment by KiSetsuFu-PuLiN** [comment]
Not reproduced in v4.3.stable.steam [77dcf97d8]

---

> Similar problem happens with me but with Add Node interface instead of the Save interface.

After repeating this step, the problem did not recur too.
