### ISSUE TITLE
Lock icon in editor backwards

### ISSUE THREAD

**Issue by GeneralProtectionFault** [godotengine/godot#83010]
### Godot version

4.1.2.stable.mono

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

In a typical 2D scene, the lock icon shows "closed" when the node is unlocked, and "open" when the node is locked.  The icon next to the node in the scene tree and over the node itself show correctly.

### Steps to reproduce

Simply create a 2D scene, and a typical situation w/ child nodes, such as a StaticBody2D with a CollisionShape2D/Sprite2D child (a situation you would want to lock the children so you can drag the object around from the parent).  The lock icon is already showing "locked" at the top of the scene view, and clicking on it will further show the mismatch, the icon in the scene view will incorrectly show a "unlocked" state after locking the node (and the scene tree icon and the icon that appears over the node in the 2D view will show a "locked" icon correctly).

### Minimal reproduction project

N/A

**Comment by kleonc** [comment]
I think this is intentional. The icon in the scene tree dock shows the status of the node. The icon in the toolbar shows the action which will be performed by pressing such button. So e.g. when a node is locked the available action is unlocking it (the opposite of the current status).

What's kinda inconsistent though is that clicking the status icon in the scene tree dock also performs the opposite action.
![j6l4ts8zbV](https://github.com/godotengine/godot/assets/9283098/67e8c9e7-3c4a-46c1-8c0f-7026c63ed8e2)
![GIlRNSfbRR](https://github.com/godotengine/godot/assets/9283098/aeb5e77b-0d9a-471d-b7c1-c7dc8c06214b)
![OeaV4jOk1F](https://github.com/godotengine/godot/assets/9283098/c63c9823-017a-4d82-bac6-c17a6e21c24f)

**Comment by GeneralProtectionFault** [comment]
Yeah I thought that might be possible but it's highly unintuitive., particularly, as in that screenshot, the icons serve a different function in different parts of the editor, and you have to hover over like that in order to determine that.  That essentially defeats the purpose of having an icon to begin with, which would be to indicate without words.

**Comment by KoBeWi** [comment]
Seems like no one else had this problem, so this can be closed.
