### ISSUE TITLE
Bug in AnimationPlayer and Keys disappearing 

### ISSUE THREAD

**Issue by ondesic** [godotengine/godot#8306]
**Operating system or device - Godot version:**
Win 10
Godot 2.1.2

**Issue description:**

*Select "Animation" tab.  
Key symbol next to properties in the inspector are toggling off while in the AnimationPlayer.

**Steps to reproduce:**
Keys appear next to all properties in the inspector.
*Next select either "Output", "Debugger" or "Texture Region" tab.
Keys are still showing next to the properties in the inspector.
*Now go back to the Animation tab by selecting it.
The Keys next to the properties are now toggled off when they should be on.

Subsequently, you have to select another node to turn the keys back on.

**Link to minimal example project:**

**Comment by DualMatrix** [comment]
Tested in master, seems to be fixed.

**Comment by golddotasksquestions** [comment]
This bug seems to be back in Godot 3.2.stable (Win) when trying to animate Texture Region.

**Steps to reproduce:**
1. Create new scene
2. Add Sprite and set texture. 
3. Enable region. Draw a region or chose autosclice in the bottom TextureRegion panel.
4. Add AnimationPlayer and create a New Anim
5. Make sure you have the AnimationPlayer Node selected, so key symbol is visible next to properties
6. Click the Sprite node
7. Wonder where the keys went.

![region_animation_bug](https://user-images.githubusercontent.com/47016402/74091853-e97fdf00-4abc-11ea-802c-486277110546.gif)
