### ISSUE TITLE
Animation Capture tracks don't work anymore

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#83166]
### Godot version

4.2 dev6

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Capture tracks no longer blend the properties. The final value is reached immediately.

https://github.com/godotengine/godot/assets/2223172/cf401330-7f51-492d-8b9b-37c0465ff531

### Steps to reproduce

1. Add AnimationPlayer
2. Add Animation1
3. Add Animation2 with capture track
4. Play Animation1 then Animation2

### Minimal reproduction project

[bgu.tscn.txt](https://github.com/godotengine/godot/files/12874161/bgu.tscn.txt)
works correctly in dev5, but not 6

**Comment by TokageItLab** [comment]
This issue is just come to the surface of a latent bug same as https://github.com/godotengine/godot/issues/82949.

https://github.com/godotengine/godot/issues/48432
https://github.com/godotengine/godot/issues/55110

**Comment by Calinou** [comment]
I can confirm this on 4.2.beta da0b1eb12 (Linux). This can be reproduced in https://github.com/godotengine/tps-demo by aiming with the right-mouse button (the camera smoothing transition is broken and snaps instantly to the final position).

This broke between 4.2.dev5 and 4.2.dev6. I bisected the regression to 1b95827d3ef244de322b0c16deb49fefe48ed1a1.

**Comment by YuriSizov** [comment]
So from what I can see, https://github.com/godotengine/godot/pull/80813 removed every bit of implementation of the capture update mode. For the most part it used to work like continuous mode, and this is still true because many checks in code are `NOT UPDATE_DISCRETE`. However, `AnimationPlayer` used to have a dedicated branch for the capture mode in `_animation_process_animation`. `AnimationTree` had no special code.

Now there is no special code in the `AnimationMixer` either, so the mode basically doesn't exist.

**Comment by TokageItLab** [comment]
As was reported a long time ago in https://github.com/godotengine/godot/issues/55110, it would be quite difficult to support it correctly at this stage, since AnimationTree cannot recognize that playback has resumed in the middle of a playback. Also I don't have any idea yet if it is possible to include such information about the start of playback in the https://github.com/godotengine/godot-proposals/issues/8083 refactor.

**Comment by TokageItLab** [comment]
I sent a proposal https://github.com/godotengine/godot-proposals/issues/8513.

**Comment by golddotasksquestions** [comment]
I just want to say: Ever since I learned about Capture Mode in the AnimationPlayer, years ago, I use it a lot.
I planned on using 4.2 for a new project and not having Capture Mode, or [a dynamic animation mode](https://github.com/godotengine/godot-proposals/issues/8513#issuecomment-1826784305) for the AnimationPlayer would probably make me reconsider.

**Comment by AThousandShips** [comment]
Please don't bump issues without contributing significant new information. Use the :+1: reaction button on the first post instead.

**Comment by golddotasksquestions** [comment]
@AThousandShips 

"I need this feature which has been removed for my upcoming project" I cannot express with a 👍 reaction button. A thumbs-up is just a general approval and can mean all kings of things. 

You know I have been with this community for years, testing and reporting issues regularly. So "Please don't bump issues with useless reminders."

**Comment by AThousandShips** [comment]
You needing this does not constitute important information for the bug, it does not affect solving it or furthering the process

Please, since you have been part of the community for years you should understand this

**Comment by YuriSizov** [comment]
I've unhidden your original comment to stop this pointless debate, but I would say that @AThousandShips is correct here. We've already identified the issue, we've established its importance and the animation team is looking for a solution. Stating that you personally need this resolved doesn't actually help in any way at this point.

Upvoting, however, does. As it's a quick and easy way for us to notice what affects most users rather than specific users.

In any case, I don't think there is more to be said about this, so let's leave the comments to the discussion about possible solutions.

**Comment by Kalto-Mate** [comment]
Glad to know the issue is tracked. In the meantime if anyone is trying to use this system to interpolate extremely simple "animations" with very few values, like a moving or rotating platform: look into tweens. Uglier, but you should get the job done with them.

**Comment by hunterloftis** [comment]
Given that this has been broken for several months at this point, and has probably caused many cumulative hours of frustration with Godot, it would be a good idea to:

1. Document the current breakage so future users don't also have to wind up here after time wasted debugging, then googling. Perhaps something like https://github.com/godotengine/godot-docs/pull/8764
2. Remove "capture" from the drop-down of animation mode options
