### ISSUE TITLE
Event Configuration in Input Mapping confusing Controller Triggers with Horizontal Right Axis

### ISSUE THREAD

**Issue by LouitLA** [godotengine/godot#83178]
### Godot version

4.1.2 4.2.dev.6

### System information

Windows 11 -  Godot v4.1.2 stable - Compatibility render - Controller

### Issue description

Controller: Xbox One S, latest firmware. (I don't have other controller to test)

In the event configuration, when I try to select the triggers by pressing them, Godot interprets it as if I’m using the right axis (the side depends on which side I press, left or right).

This only happens in the event configuration part of the input map menu. In the game, both the axis and triggers work as intended.

Screenshots:

input captured:
![image](https://github.com/godotengine/godot/assets/110429198/d927e3bc-8b9c-457b-9874-3b94b509fee4)

Input that I actually pressed:
![image](https://github.com/godotengine/godot/assets/110429198/26b76ee9-a72e-4421-94b0-fcf7d57925c0)

### Steps to reproduce

- Go to Project Settings and select Input Map
![image](https://github.com/godotengine/godot/assets/110429198/6266c458-e570-44c9-b956-6ca598545a33)

- Add an event to any action you created
![image](https://github.com/godotengine/godot/assets/110429198/d8712eae-7809-4dd6-bd17-075a2acc6b10)

- Instead of seraching choose filter by input and press any of the triggers using a controller (I only tested with the Xbox One S controller in the lastest firmware)
![image](https://github.com/godotengine/godot/assets/110429198/26566a31-d123-4514-8080-de960a45ed25)

### Minimal reproduction project

any project

**Comment by emanvidmaker** [comment]
I also encountered this bug and got more info.
My Xbox PowerA wired controller, has exact issue as LouitLA described except mine also confuses the inputs in game and in editor. Something it did not do when i ran the exact same project on my windows boot. The same bug was also found when i made a new unmodified project. 

I also tested with my ps4 controller, and  it was unaffected by the bug, and working as intended. 

As extra source of precaution I tested the Xbox  controller on steam and it was not confusing the axis; However it did label it as an Xbox one controller.  **so it narrows it down the source to a Godot issue with Xbox One Controllers.**  

---
# GODOT Version 
v4.2.2.stable.official [15073afe3]
# System information
Linux (Pop!_OS 22.04 LTS, 64-bit, Gnome v42.9, windowing system X11)  - v4.2.2.stable.official - Forward+ 
## Controler
[Enhanced Wired Controller for Xbox Series X|S - Metallic Red Camo](https://www.powera.com/p/xbox/xbox-series-xs/controllers/wired/enhanced-wired-controller-for-xbox-metallic-red-camo-1518910-02/) This exact one

**Comment by emanvidmaker** [comment]
Update: issue still present in v4.3.beta1.official [a4f2ea91a]

I believe its caused by unsuported SDL bindings 
since in my case the controler was supported for windows and not for linux.
meaning the `core/input/gamecontrollerdb.txt` 's linux section is missing my controler
  
I have a potential fix
A) adding the bindings for my controller to `core/input/gamecontrollerdb.txt`
B) updating `core/input/gamecontrollerdb.txt` to match its latest version,  [gabomdq/SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) 

il give A) a shot and report back

**Comment by emanvidmaker** [comment]
I fixed the issue my end. **The bug is caused by missing bindings on** `core/input/gamecontrollerdb.txt` // [gabomdq/SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB)
I added my bindings from steam to `gamecontrollerdb.txt` , recompiled and it worked.

Now that fix only would fix my controler, belive theres a generic xbox controler thats causing the issue with the xbox one, controlers. 

@LouitLA if you could follow the following instructions and send me the bindings for your xbox controlers and any other, to verify that that's the case.
 _from [mdqinc/SDL_GameControllerDB](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/README.md)_
> ### [Steam](http://store.steampowered.com)
In Steam's Big Picture mode, configure your gamepad. Then look in `[steam_installation_directory]/config/config.vdf` in your Steam installation directory for the `SDL_GamepadBind` entry. It is one of the last entries, it will look something like this:

```
"SDL_GamepadBind"		"030000004c050000c405000000010000,PS4 Controller,platform:Windows,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,"
```

config.vdf is a text file so open it with notepad and scroll down untill find  "SDL_GamepadBind" and send me all strings that look like that since there might be multiple for the same controler but difrent configs

**Comment by emanvidmaker** [comment]
Im going to PR my bindings to godot and to https://github.com/mdqinc/SDL_GameControllerDB and go from there

**Comment by LouitLA** [comment]
@emanvidmaker here are my bindings` taken from the steam

``` 	"SDL_GamepadBind"		"03000000de280000ff11000001000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b8,lefttrigger:+a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:-a2,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Windows,
03000000de280000ff11000000000000,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b4,leftstick:b8,lefttrigger:+a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:-a2,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Windows,
03000000de280000ff11000000007701,Steam Virtual Gamepad,a:b0,b:b1,back:b6,dpdown:b12,dpleft:b13,dpright:b11,dpup:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a4,leftx:a1,lefty:a0~,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a2~,start:b7,x:b2,y:b3,platform:Windows,"
```

**Comment by emanvidmaker** [comment]
interesting I think i know whats happening then , steam doesn't know your controller so its using the virtual thing, but before we continue, @LouitLA  did you do a input test on steam to see if the issue affects steam? and do you use/launch godot from the steam app?

**Comment by LouitLA** [comment]
I don't use the steam version of Godot, but even not recognizing the controller it's working properly
