### ISSUE TITLE
Colliders will drag each other

### ISSUE THREAD

**Issue by Az-qianchen** [godotengine/godot#83182]
### Godot version

godot-4.2-dev6

### System information

WIn 11

### Issue description

When the player is below and close to the enemy, enemy movement speed will become the player movement speed.
print safe_velocity to get the correct result
This situation will not occur when the player is above the enemy

![tmp6A80](https://github.com/godotengine/godot/assets/52212525/36a985c6-1d75-48a3-b1d1-55c15d32413a)

https://github.com/godotengine/godot/assets/52212525/e059a796-4179-48e4-bb6e-12ccbe7bbe7f

### Steps to reproduce

Use the left mouse button or WASD to move the character
An error occurred after moving under the enemy character and getting close to it.

### Minimal reproduction project

[NavigationRegion2D_bug.zip](https://github.com/godotengine/godot/files/12878160/NavigationRegion2D_bug.zip)

**Comment by Az-qianchen** [comment]
My guess is that move_and_slide() brings wrong collision sliding?

**Comment by Az-qianchen** [comment]
> Neither do they convert stuff to local or multiply by physics engine tick.

Is there any other problem possibility, I changed the code from the documentation to increase the refresh time to 1 second but the problem still exists
![tmp5CE4](https://github.com/godotengine/godot/assets/52212525/ec338e1d-52fa-473f-b584-3cef0785d6fe)


https://github.com/godotengine/godot/assets/52212525/b5ea0d0b-c9b9-4f11-aecc-f0882b1c4f42

**Comment by smix8** [comment]
In your project set the NavigationAgent2D `max_speed` to the same max speed value that you use in your script.
Also reduce the NavigationAgent2D `time_horizon_agents` to 0.1-0.3 since your speed is slow.

I did not encounter anything other than physics collision shape sliding after fixing that. The capsule of your agent shapes get stuck on the obstacle collision regularly.

**Comment by Az-qianchen** [comment]
![tmp8CD](https:github.com/godotengine/godot/assets/52212525/e5f4ace1-0a79-409b-95b3-b3cff5042dfd)
Sorry, but I made changes and it seems there is still a problem. I tried changing the values ​​to be more extreme, but the problem still exists.
Can you reproduce this problem in the original reproduction project I provided?
Is a system or Godot version problem ?

**Comment by smix8** [comment]
As said the main problem left is the physics collision. The speed increase is because the two collision shapes are sliding and getting stuck against each other dragging each other. The capsule collision shape is also too large for the navigation mesh margin so your agent gets stuck on the obstacles as well.

**Comment by Az-qianchen** [comment]
Thanks, this can be solved，but even  use the simplest RectangleShape or CircleShape as CollisionShape, Will still have such a problem

**Comment by aboveyunhai** [comment]
@smix8  I think you misunderstand his problem. A lot of people (including me) faced the same trouble due to the default  (select all) of the moving platform.

When two objects collides each other and treat each other as moving platform, if one is on top of another one, the bottom (as moving platform) will drag the one on top, which causes the weird dragging issue as the video shows.

@Az-qianchen  unselect the layer your character and enemy in layer 1, since they aren't moving platform, which can solve your problem.
![image](https://github.com/godotengine/godot/assets/35160613/0e6dc8b9-40be-4512-8431-f2433dca0243)

**Comment by Az-qianchen** [comment]
@aboveyunhai
In my testing, unselect the floor layer seemed to solve the left and right dragging problem, but the downward dragging problem still existed.

https://github.com/godotengine/godot/assets/52212525/9e558d5c-bc34-400b-9d4f-1d7c6cab4453

**Comment by aboveyunhai** [comment]
@Az-qianchen  I'm new to godot, so don't take my word as truth, when a collider is on top of another collider, `move_and_slide` will apply `snapping` while attaching, which will take your velocity into account somehow, so the initial speed becomes so fast that felt like a stuck happening as your player move away as the floor, I feel like it could be a bug, whether from your code or the engine itself, or I didn't fully understand the method or the collision concept. 
I didn't have the bottom stuck issue when I remove the floor layer in another sample project.
At the mean time, set`Snapping length` to `0` can solve your issue, but it might not be what you want, it can cause other issues, or you might need to write your own `move_and_slide`  function. 

![image](https://github.com/godotengine/godot/assets/35160613/ce3e6e58-77cb-4389-84cc-5ccd5825f84d)

**Comment by Az-qianchen** [comment]
@aboveyunhai
Thanks, I think this will solve the problem, I will close with comment
