### ISSUE TITLE
`RTLD_DEEPBIND` breaks sanitizer builds

### ISSUE THREAD

**Issue by Bromeon** [godotengine/godot#83212]
### Godot version

4.2-dev (7f4e700bf7e207afae076451ae5c5dcbb112109a)

### System information

Linux CI

### Issue description

Change https://github.com/godotengine/godot/pull/82973 introduces a regression for a downstream memory-sanitizer job.

[Here](https://github.com/godot-rust/gdext/actions/runs/6488178925/job/17630440541#step:3:472) is an example of such a failed job, the error is:

```
==2646==You are trying to dlopen a /home/runner/.../debug/libitest.so shared library 
with RTLD_DEEPBIND flag which is incompatible with sanitizer runtime 
(see https://github.com/google/sanitizers/issues/611 for details).

If you want to run /home/runner/work/gdext/gdext/itest/godot/../../target/debug/libitest.so library 
under sanitizers please remove RTLD_DEEPBIND from dlopen flags.
```

While Godot CI runs sanitizer builds as well, I don't think they include GDExtension.

---

It would be nice if `scons` could be configured to not pass `RTLD_DEEPBIND` to `dlopen()`.
Or maybe even better, automatically disable that behavior if any of the sanitizer flags is passed to `scons`.

Since the code has this check, it might even be enough to pass `RTLD_DEEPBIND=0` as a global `#define`?
https://github.com/godotengine/godot/blob/b1371806ad3907c009458ea939bd4b810f9deb21/drivers/unix/os_unix.cpp#L84-L86

---

### Steps to reproduce

Build Godot master with:
```bash
scons platform=linuxbsd target=editor dev_build=yes use_asan=yes use_ubsan=yes use_lsan=yes use_llvm=yes linker=lld
```
Load it with ASan/LSan environment variables, in a project that has a GDExtension.

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
I don't think this should be a compile option, I think this is pointed at the fact that `RTLD_DEEPBIND` may not be a safe option to use for all dynamic library loading.

This should maybe be an option in the GDExtension library's config, so users can opt-in to this behavior, and we keep the safe default.

**Comment by Bromeon** [comment]
> This should maybe be an option in the GDExtension library's config, so users can opt-in to this behavior, and we keep the safe default.

Good idea! That would also allow different extensions with different settings.

---

Incidental to this, regarding sanitizer builds: in order to retain stacktraces in Rust code, it's necessary to _not unload_ the dynamic library. A longer explanation can be seen in https://github.com/godot-rust/gdext/pull/133.

I worked around this by applying a patch that removes these 3 lines:

https://github.com/godotengine/godot/blob/b1371806ad3907c009458ea939bd4b810f9deb21/drivers/unix/os_unix.cpp#L664-L666


It looks like this was encountered in the past by Godot users as well: https://github.com/godotengine/godot/issues/46140#issuecomment-780850702

It's relatively specific, but it might be something to think about if sanitizer builds + GDExtension are an officially supported setup.

**Comment by dsnopek** [comment]
> I don't think this should be a compile option, I think this is pointed at the fact that `RTLD_DEEPBIND` may not be a safe option to use for all dynamic library loading.

Sanitizer builds are a pretty specific use case, and you already have to compile Godot with a special compile option to enable them, so I think making this a compile-time decision makes sense. Although, I'd argue it shouldn't be a new option, I think if you use any of the san options when building Godot, it should automatically disable `RTLD_DEEPBIND`.

> This should maybe be an option in the GDExtension library's config, so users can opt-in to this behavior, and we keep the safe default.

I don't agree with this.

What happens without `RTLD_DEEPBIND` is super weird and unexpected (and Linux-specific), and I don't think any developer is going to know that they need to enable this.

To be clear, what happens without this option, is that Linux's dynamic linker with link any symbol in the GDExtension (defined or undefined) to a symbol in the main Godot executable with the same name. So, if you make a GDExtension, that has a class called `Object`, even though your version of `Object` is compiled into the GDExtension and was fully defined at compile/link time, the dynamic link will re-link all references to the `Object` in the Godot executable.

Nobody ever wants this behavior :-)

I think it only comes up in sanitizer builds, because those builds are probably replacing `malloc()` or other system-level functions, and when you dynamically load a library, it needs that library to also use it's replacement `malloc()`, etc.

So, again, I think it's sanitizer builds that are special here.

**Comment by akien-mga** [comment]
So what should we do here? Special case it for builds with sanitizers enabled? We have the `SANITIZERS_ENABLED` define that could be used for that.

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/84210 which should disable `RTLD_DEEPBIND` in sanitizer builds
