### ISSUE TITLE
RemoteTransform2D projects wrong position

### ISSUE THREAD

**Issue by markdibarry** [godotengine/godot#83297]
### Godot version

4.2.beta

### System information

Windows 10

### Issue description

I assume the main use-case of `RemoteTransform2D` is to have another node match the transform of the `RemoteTransform2D`'s parent node. When `RemoteTransform2D` has `use_global_coordinates` set to `false`, however, the position sent to the controlled node will be the `RemoteTransform2D`'s local position, which makes sense, I guess, but that will always be `(0,0)`. This could be the expected behavior, but I can't imagine when it'd ever be useful, so please correct me if I'm wrong. 

### Steps to reproduce

1. Make a sprite.
2. Make a second sprite with a `RemoteTransform2D` child and move it anywhere on screen.
3. Select the first sprite as the `RemoteTransform2D`'s target.
4. Set `use_global_coordinates` to false.

### Minimal reproduction project

N/A

**Comment by Rindbee** [comment]
There seems to be something strange here.

When `use_global_coordinates` is `true`, it will notify `NOTIFICATION_TRANSFORM_CHANGED`; when `use_global_coordinates` is `false`, it will not.

https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/2d/remote_transform_2d.cpp#L68-L72

https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/2d/remote_transform_2d.cpp#L88-L92

Here, `get_global_transform()` seems to be a necessary condition for notify `NOTIFICATION_TRANSFORM_CHANGED`.

**Comment by markdibarry** [comment]
@Rindbee I'm not sure, but that may be unrelated. I think it's more that `RemoteTransform2D` just happens to work with its main use case but its logic isn't designed that way.

When you want a `CanvasItem` elsewhere in the scene tree to move along with another `CanvasItem`, you add a `RemoteTransform2D` node as a child and set a target. When you update the parent's `global_position`, the `RemoteTransform2D`'s `global_position` also updates, and will match (unless it's offset). However, when you have it set to local, updating the parent's position does nothing for the `RemoteTransform2D`, because its `position` is still whatever it is relative to the parent (99% of the time `0,0`), when the behavior you're looking for is to send the `position` of its parent; the thing you're trying to have the target follow.

Even before your PR, the target will get the local position changes to the `RemoteTransform2D`, it's just it'd never actually change unless you were directly altering the `RemoteTransform2D`'s `position` from a script, which is the exact situation the node was made to avoid. You could just alter the target's `position` directly.

**Comment by kleonc** [comment]
> I assume the main use-case of `RemoteTransform2D` is to have another node match the transform of the `RemoteTransform2D`'s parent node.

@markdibarry This seems to be a wrong assumption. According to the docs (and to the source code) RemoteTransform2D is supposed to propagate its own transform to the target node, not the transform of RemoteTransform2D's parent.

Given that's indeed intended by design, I see no bug in here.

So in the MRP you'd rather want the sprite to be a child of RemoteTransform2D, and you'd move the RemoteTransform2D (instead of its child sprite) so its `transform` would be propagated to the other sprite.

---

Changing RemoteTransform2D to propagate the parent's transform instead would be a compatibility breaking change. But I guess what could be done is adding a bool like `propagate_parent_transform` (false by default for compat) which would make the RemoteTransform2D behave as you've assumed it to behave. But something like this is a material for a proposal, not for a bugfix.

**Comment by markdibarry** [comment]
@kleonc Yeah, I guess that's the part I was confused about. I threw this in as an issue because, as far as I can glean, it works exactly as it says, I just can't imagine a scenario where the intended design would ever be useful without completely negating the need for the node in the first place. I honestly only use this node to do quick mock ups for things, and would never use it for an actual system, so it's not a high priority for me, but I was playing around with a `SubViewport` and needed to switch to local `position`, and was confused at how literally it behaved. It reminds me of that Daffy Duck bit where he uses a disintegration pistol and the pistol disintegrates. Like, yep, that makes total sense, but not helpful.

I totally agree: it *does* do what it says it does, but if it's intended to be used with `RemoteTransform2D` as the parent of the object to follow, I cannot find one example out there of it being used this way even as far back as Godot 2... and I imagine would make things very problematic to do so, especially if the child is a `CharacterBody2D` or anything with logic in it. The `global_transform` works perfectly for how every example I have found uses it, but it just kinda happens to work, if it's not intended to work like that at all. I think you're right about it needing a compatibility property, but it's just funny how useless it is in its current state despite doing exactly as it says.

**Comment by rpahut** [comment]
> This seems to be a wrong assumption. According to the docs (and to the source code) 

I would have to disagree. As it stands, the global coordinates checkbox in RemoteTransform2D is useless, as checking it off results in zero local transformations to communicate, and without a way to cast local coordinates the node remains functionally incomplete. Pointing to the docs and source code as a source of truth is hardly justifiable, since one is documenting, and another causes the current, seemingly invalid, state of things.

Perhaps @TwistedTwigleg can shed some light on how one is expected to use the flag but really, the reported is a valid issue and it needs some sort of resolution.
