### ISSUE TITLE
blend-file import does not import vertex colors

### ISSUE THREAD

**Issue by thmasn** [godotengine/godot#83310]
### Godot version

4.1.1 stable-official
blender version 3.6.3

### System information

macOS 13.5.2 (22G91)

### Issue description

this issue is similar to[ https://github.com/godotengine/godot/issues/73056](73056), but no longer on the blender side as of blender 3.5

- vertex colors from .blend files are not imported.
- weirdly, when exporting from blender as .glb, godot shows them correctly.

left: .glb import, right: .blend import
<img width="553" alt="Bildschirmfoto 2023-10-14 um 09 53 57" src="https://github.com/godotengine/godot/assets/20150151/10e37a12-58f4-41be-8e67-703e58245122">

### Steps to reproduce

- create a blender file
- create an object with vertex colors (face corner type)
- save the blender file in a godot project and add to a scene
- there are no vertex colors present
- export the blender file as .glb
- in the glb export there are vertex colors present

### Minimal reproduction project

[vertexcolorexample.zip](https://github.com/godotengine/godot/files/12903509/vertexcolorexample.zip)

**Comment by thmasn** [comment]
it seems the only issue was that the color checkbox in import settings was off.
not sure if this is a default, or i removed the ckeckbox...
<img width="266" alt="Bildschirmfoto 2023-10-15 um 11 57 47" src="https://github.com/godotengine/godot/assets/20150151/0447c4bb-7846-4b67-8f86-c8f1226e440e">

but i think the issue can be closed.

**Comment by cottatheripper** [comment]
Ran into a similar problem with Blender 4.1.1 and godot 4.2.1. Commenting here because google brought me here so many times when troubleshooting this, so others with the same problem might find this comment.  When using automatic blend-file import, vertex colors were not being imported. The solution ended up being to use the vertex color attribute as an input ANYWHERE in the material in Blender before exporting, basically to "tell" blender that you are using vertex colors. I think this is because, by default gltf exporter now only exports vertex colors if they are actually used in the shader.

**Comment by Calinou** [comment]
@cottatheripper I suggest opening an issue on https://github.com/godotengine/godot-docs to track this, so it can be documented in the Importing 3D scenes documentation. You could also open a pull request that edits https://github.com/godotengine/godot-docs/blob/master/tutorials/assets_pipeline/importing_3d_scenes/available_formats.rst directly 🙂
