### ISSUE TITLE
dont work on specific laptop

### ISSUE THREAD

**Issue by Luigi654** [godotengine/godot#83328]
### Godot version

4.1.2 stable

### System information

windows 10, ram 4gb, intel HD graphics 400, intel celeron N3060

### Issue description

![imagen](https://github.com/godotengine/godot/assets/86989568/73b97626-c67a-45d5-90a0-412d6de49136)
dont work at startup

### Steps to reproduce

open the program

### Minimal reproduction project

.

**Comment by darksylinc** [comment]
Hi

Braswell GPU is too old for Godot.

Things you can try:

1. Update your [drivers to latest](https://www.intel.com/content/www/us/en/support/detect.html) (Try this first!)
2. Try Linux, AFAIK there are Vulkan drivers for Braswell on Linux (if you do this, disable MSAA because there is a known issue with MSAA on Braswell GPUs and Godot).
3. If you can build Godot by yourself from source code, you could post the callstack of where it is crashing, it may help us workaround whatever OpenGL driver bug we triggered that caused it to crash.

Cheers

**Comment by Chaosus** [comment]
Sadly, we cannot fix every problem with old hardware or drivers. As an addition to speaker above: You can also try to use the previous Godot version, which has a fully capable OpenGL renderer. I suppose this issue is resolved, otherwise it may stall forever, so closed.
