### ISSUE TITLE
Code editor toggle comment doesn't uncomment if there's a different amount of #'s

### ISSUE THREAD

**Issue by aXu-AP** [godotengine/godot#83331]
### Godot version

v4.2.beta1.official [b1371806a]

### System information

Windows 10

### Issue description

Toggle comment adds more comment delimiters when there's different amount of delimiters, even if all the lines are commented.

Current behavior:
![comment](https://github.com/godotengine/godot/assets/1621768/d908181c-a2ee-48ad-9d79-6cf5524fa7d3)

Expected behavior (from v4.2.dev6.official [57a6813bb]):
![comment_old](https://github.com/godotengine/godot/assets/1621768/343699a8-ede7-446c-bd6f-166f02cf5885)

Regression likely happened in #81486

### Steps to reproduce

Open script editor. Comment some lines. Then select bigger area enclosing some of the commented lines, and toggle comment twice or more.

### Minimal reproduction project

N/A

**Comment by aXu-AP** [comment]
I might fix this next week if I have time, but feel free to work on this if you want. Shouldn't be hard to fix.

**Comment by Lunarisnia** [comment]
I would love to try and fix this, can I get assigned to this issue?

**Comment by aXu-AP** [comment]
Just go ahead, issues aren't usually assigned 👍

**Comment by Lunarisnia** [comment]
https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/editor/code_editor.cpp#L1504

https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/gui/code_edit.cpp#L1912-L1915

https://github.com/godotengine/godot/blob/a574c0296b38d5f786f249b12e6251e562c528cc/scene/gui/code_edit.cpp#L2939-L2963

From my investigation. The issue seems to root from the function `CodeEdit::is_in_comment` returning `2` instead of `3` when there is a multiple comment delimiter in a line causing `delimiters[delimiter_idx].start_key` to return `##` instead of `#` which cause the error. CMIIW

 This issue can also be reproduced by simply adding multiple comment delimiter in a line then using the In-line comment shortcut:
 Example:
 ```
 # Try using the inline comment shortcut on this line below
 ##var l1
 ```
