### ISSUE TITLE
Visible Collision Shapes on tanks frame rate

### ISSUE THREAD

**Issue by Morokiane** [godotengine/godot#83354]
### Godot version

4.2.Beta 1

### System information

Windows 11

### Issue description

When visible collision shapes is turned on from the Debug menu will tank the frame rate. On small levels it is fine, but on larger levels it lags and drops frames. Opens this same project back up in 4.1 to make sure I didn't do something wrong and it ran fine in that version. Here is a video of it happening, my small start area is fine then in the larger level the frame rate drops. The red numbers in the top middle is the frame rate.

https://github.com/godotengine/godot/assets/4334870/ef733e3c-75b2-4ce8-8d26-947cd58a7326

### Steps to reproduce

Load a large level with tilemap and visible collision shapes on run the game.

### Minimal reproduction project

n/a

**Comment by kleonc** [comment]
> ### Steps to reproduce
> 
> Load a large level with tilemap and visible collision shapes on run the game.

Couldn't reproduce, tested a simple case (but with lots of tiles) and got similar fps in both `v4.1.2.stable.official` and `v4.2.beta1.official`. I've tried also with Y-sorting enabled (as this has changed between the versions) but then as expected `v4.2.beta1.official` performed better than `v4.1.2.stable.official`.

> ### Minimal reproduction project
> 
> n/a

So please provide a minimal reproduction project.

**Comment by Calinou** [comment]
What CPU and graphics card model do you have?

**Comment by Morokiane** [comment]
> What CPU and graphics card model do you have?

AMD Ryzen 7 5800HS and Nvidia Geforce RTX 3060 Laptop GPU. I also tried this on M1 Mac with the same results. 16GB RAM on the both.

**Comment by Calinou** [comment]
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no minimal reproduction project was included in the original bug report, please upload one as well to ease troubleshooting.
