### ISSUE TITLE
Can use 'make local' on nodes inherited from another scene

### ISSUE THREAD

**Issue by SaracenOne** [godotengine/godot#83385]
### Godot version

a574c0296b38d5f786f249b12e6251e562c528cc

### System information

Windows 11

### Issue description

The 'make local' button is permitted on nodes even when the node is inherited from another scene. This should not be allowed.

### Steps to reproduce

- Create a scene
- Create another scene an instance the first scene as a child
- Create a third scene inherted from the second scene
- Select 'make local' on the instantiated scene

### Minimal reproduction project

N/A

**Comment by golddotasksquestions** [comment]
I don't understand this issue and can't replicate or find any unintended behaviour by following the steps. 

It's not properly explained either. "This should not be allowed" is not an explanation for what or why something undesired/unexpected is occurring. What exactly is the problem here?

Why should I not "Make Local" on Inherited scenes? I don't see the option in 4.2 Beta1 anyway:
![image](https://github.com/godotengine/godot/assets/47016402/a5d2ce57-7aee-4481-a17e-1a130eb8f64d)
![image](https://github.com/godotengine/godot/assets/47016402/dbae4056-3ea1-407b-ae18-882056920908)
The child of the inherited scene has that option, but why would making this local be a problem at all? It does not affect the scene we inherited from (scene_B)
![image](https://github.com/godotengine/godot/assets/47016402/3e6fa398-a8c7-4026-91eb-9995ab45b04c)
