### ISSUE TITLE
gui_get_focus_owner() not returning the Node in focus

### ISSUE THREAD

**Issue by FlowLightGames** [godotengine/godot#83464]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3713) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

when trying to get the current control node in focus with get_viewport().gui_get_focus_owner()
it only returns the correct node when the focused is not the child of a subviewport or window

### Steps to reproduce

what doesnt work:
Scene tree:
Control 
[↳]Subviewportcontainer
    [↳Subviewport
       [↳Control.grab_focus() 

then call
get_viewport().gui_get_focus_owner() returns null
even get_tree().root.gui_get_focus_owner() returns null

but if the Control.grab_focus() node is not child of a viewport/window node it works as intended

**Comment by Calinou** [comment]
@FlowLightGames Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by FlowLightGames** [comment]
[Small.zip](https://github.com/godotengine/godot/files/12921693/Small.zip)

**Comment by FlowLightGames** [comment]
just realized the order of the script objects is wrong in the sample project. so it doesnt work because the subviewport != viewport gotten in the script function call. 
![image](https://github.com/godotengine/godot/assets/75386913/07a9e3af-5d39-4c80-a79a-8fb0725adef3)
this is what doesnt work in my project tree if that helps. ill try again replicating the bug in a samller project

**Comment by FlowLightGames** [comment]
problem was godot not grabbing focus on a item in the vboxcontainer that i added in the same frame
