### ISSUE TITLE
Exported properties: cannot set two groups with same name under different categories

### ISSUE THREAD

**Issue by acgc99** [godotengine/godot#83662]
### Godot version

v4.1.2.stable.official [399c9dc39]

### System information

Godot v4.1.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.3758) - Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 Threads)

### Issue description

When you try to set two`@export_group` with same name but under different `@export_category`, the group on the second category is fused into the group on the first category.

### Steps to reproduce

Just attach this script to a `Control` (or any node):
```
extends Control


@export_category("Label")
@export_group("Strings")
@export var text: String
@export_category("RichTextLabel")
@export_group("Strings")
@export var rich_text: String
```

![image](https://github.com/godotengine/godot/assets/96864661/dac4e678-9480-40f9-9c34-4a840dd336e0)

### Minimal reproduction project

[bug.zip](https://github.com/godotengine/godot/files/13051987/bug.zip)

**Comment by Mickeon** [comment]
This is intentional. Due of the implementation, groups, subgroups and categories technically qualify as "properties", and you _shouldn't_ have two or more properties with the same name.
One may argue it needs to be documented better, or better yet, let out a warning on the `@export_*` annotation in this situation.
