### ISSUE TITLE
Skeleton3D.SetBonePoseRotation stopped working on 4.1.2

### ISSUE THREAD

**Issue by devOneto** [godotengine/godot#83676]
### Godot version

Godot v4.1.2

### System information

Godot v4.1.2.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - integrated Intel(R) UHD Graphics 770 (Intel Corporation; 31.0.101.4575) - 13th Gen Intel(R) Core(TM) i5-13600K (20 Threads)

### Issue description

The function SetBonePoseRotation of Skeleton3D was working on the version 4.0.3 but it stopped working on 4.1.2.

### Steps to reproduce

1) Create a new Godot Project.
2) Create a new 3D Scene.
3) Add a camera to see the results.
4) Add a 3D model ( must have bones for animation) ( I got mine from Mixamo )
5) Make the Model a Local Scene.
6) Add a script with the reference for the Skeleton3D. ( I've tested with c# and gdscript )
7) Try to use the SetBonePoseRotation function of Skeleton3D class to set a new rotation for some bone.
8) Expected: the bone should rotate like it's on 4.0.3

### Minimal reproduction project

[BugReportSetBonePoseRotation.zip](https://github.com/godotengine/godot/files/13054576/BugReportSetBonePoseRotation.zip)

**Comment by bitsawer** [comment]
In the project, both AnimationPlayer and AnimationTree are set to active and seem to override the skelton pose you set programmatically. Disabling or removing them allows the code to set and retain the pose.

There is also a chance this issue is a duplicate of https://github.com/godotengine/godot/issues/77548. This was fixed in the linked PR linked to that issue, so the current behavior you are seeing is probably the correct one although it is different from the old one.

**Comment by devOneto** [comment]
@bitsawer Thanks a lot. Reading the #77548 I could understand the point and finally implement the desired functionality.
