### ISSUE TITLE
draw_line (DrawLine) causes Segmentation fault on Debian11 VM

### ISSUE THREAD

**Issue by erupikus** [godotengine/godot#83767]
### Godot version

v4.1.1.stable.mono.official.bd6af8e0e

### System information

Godot v4.1.1.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

using draw_line (DrawLine) causes Segmentation fault (SEGFAULT) on Debian11 VM

using draw_circle (DrawCirle) works as expected.

### Steps to reproduce

setup project on windows like on screenshot:
![image](https://github.com/godotengine/godot/assets/50503057/89f192da-c7cf-4973-b2bc-599ac5b910eb)

Create 2D project. Add another Node2D as child of root Node2D and add Camera2D. Create a C# script that overrides _Draw method and in it place code:
```
DrawLine(new Vector2(-10, -10), new Vector2(10, 10), Colors.Red, 10f);
```
Attach this script to child Node2D and export it on linux x86_64 and run on Debian11 VM (Linux debian11 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux)

### Minimal reproduction project

[segfault_on_linux_drawline.zip](https://github.com/godotengine/godot/files/13062629/segfault_on_linux_drawline.zip)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.2 (only the latest patch version is supported)

**Comment by erupikus** [comment]
Sadly i still get segfault on draw_line:

mac@debian11:~/Lines_game$ ./DrawMe.x86_64 
Godot Engine v4.1.2.stable.mono.official.399c9dc39 - https://godotengine.org
Vulkan API 1.0.2 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 11.0.1, 256 bits)
WARNING: lavapipe is not a conformant vulkan implementation, testing use only.
Segmentation fault

**Comment by AThousandShips** [comment]
That's some information that would have been good to have in the original report, seems lavapipe related then

**Comment by rsubtil** [comment]
You did not include any scripts with your reproduction project BTW. From what I tested on GDScript, seems to work without issue. Might indeed be a lavapipe issue as @AThousandShips said.

**Comment by erupikus** [comment]
Sorry for not including that :( . Shall i still inlcude scripts/other logs? and what should be next steps if any?

**Comment by AThousandShips** [comment]
Do provide a functional MRP so this can be tested better

**Comment by erupikus** [comment]
sure:
[segfault_on_linux_drawline_godot_4.1.2.zip](https://github.com/godotengine/godot/files/13064121/segfault_on_linux_drawline_godot_4.1.2.zip)

**Comment by rsubtil** [comment]
I've tested it now and can't reproduce the issue, so seems likely that the issue is in the software renderer.

You can try getting a debug build of Godot by going into any running action and downloading the compiled artifact (like [this one](https://github.com/godotengine/godot/actions/runs/6605348059), scroll down to the artifacts area, then download `linux-editor-mono`). That build should produce a detailed stacktrace indicating where it is crashing, which you should then post here.

**Comment by akien-mga** [comment]
That's a lavapipe bug - but mainly the problem is the use of Debian 11, whose version of mesa/lavapipe is way too old. Those drivers are not usable in production as they say, and the crash can't be fixed.

Updating mesa / using a newer distro should solve it.

I tested on Mageia 9 with Mesa 23.1.7, and the MRP works fine with llvmpipe (new name of lavapipe in the old mesa).

```
Godot Engine v4.1.stable.mono.official.970459615 - https://godotengine.org
Vulkan API 1.3.246 - Forward+ - Using Vulkan Device #0: Unknown - llvmpipe (LLVM 15.0.6, 256 bits)
```

**Comment by erupikus** [comment]
thanks for your help!

**Comment by Calinou** [comment]
- Related to https://github.com/godotengine/godot-proposals/issues/8071.
