### ISSUE TITLE
Thumbnails not visible in filesystem dock

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8377]
Unless it's hidden behind a new editor setting, thumbnails (including image thumbnails) aren't visible in filesystem dock in the current master (which were [apparently](8355) there in 2.1).

**Comment by reduz** [comment]
Ah yeah.. need to enable threading support for these to work.. right now
VisualServerWrapMT is not implemented..

On Apr 12, 2017 5:51 PM, "Ferenc Arn" <notifications@github.com> wrote:

Unless it's hidden behind a new editor setting, thumbnails (including image
thumbnails) aren't visible in filesystem dock in the current master (which
were apparently <http://8355> there in 2.1).

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8377>, or mute the thread

**Comment by tagcup** [comment]
Fixed by 612ab8f
