### ISSUE TITLE
Names of nodes with custom icon gets truncated too early

### ISSUE THREAD

**Issue by peterhoglund** [godotengine/godot#83801]
### Godot version

4.2 beta 1

### System information

MacOS 11.7.4

### Issue description

When using a custom icon on a node (of type Node in this case) by using `@icon("path/")` the name in the Scene tree gets truncated too early, leaving a few hundred pixels empty on the right side before the icons.

If I remove the icon the name is no longer truncated like this.

<img width="288" alt="image" src="https://github.com/godotengine/godot/assets/522470/3414415b-a3ca-449e-9bd1-8d0d3a0e0881">

### Steps to reproduce

Create a Node node. In code assign a custom icon. Reduce the width of the scene tree dock in the editor.

### Minimal reproduction project

-

**Comment by chybby** [comment]
I was looking into this today, looks like the text is being truncated based on the size of the icon's texture, not the size of the icon. Should be able to get a fix working today.

**Comment by chybby** [comment]
> @chybby Great! I also noticed that the custom icon in the Signals list is the true image size and not scaled down to fit the category title height. Might be related?

I don't think that's directly related. Do you mean here?

![godot windows editor dev x86_64_cFDyjfJakT](https://github.com/godotengine/godot/assets/1632314/bf363ed9-f064-4f0d-9d90-50d0e0971208)

Because it looks like it's working for me.

I did find some other places that uses the full image size however:

Recently edited objects history:

![godot windows editor dev x86_64_4YADIV8U03](https://github.com/godotengine/godot/assets/1632314/057ffc12-4b89-4d64-8560-9e1fd3ba5b28)

In the Search Help dialog:

![godot windows editor dev x86_64_rgFNOkijyN](https://github.com/godotengine/godot/assets/1632314/a1ef26fb-01f4-4a17-804b-edc9bb81984e)

**Comment by peterhoglund** [comment]
> I don't think that's directly related. Do you mean here?

Yes, this is what it looks like to me. I'm on 4.2 beta 1.
<img width="285" alt="image" src="https://github.com/godotengine/godot/assets/522470/cc582eb8-2421-4bee-b590-46183d5a0da4">

**Comment by chybby** [comment]
Ah, that was fixed by #83447

**Comment by peterhoglund** [comment]
Super, thanks!
