### ISSUE TITLE
Continuous animation of `Polygon2D` points no longer works. (Animation Player)

### ISSUE THREAD

**Issue by komdog** [godotengine/godot#83841]
### Godot version

v4.2 beta2 [f8818f85e]

### System information

Windows 11 - v4.2.beta2.official - Compatibility

### Issue description

In version 4.2 dev3, I could animate the points of a Polygon 2D in the animation player using the `continuous` update mode. This no longer works the way it used to. The polygon will remain on the initial frame, no matter how many keyframes are added. I've noticed that when setting the update mode to discrete, the points will still animate but return to the initial shape if no keyframes are present at the current spot in the timeline.

### Steps to reproduce

1. Create a Polygon2D and an Animation player.
2. Animate two keyframes with different Polygon2D points.
3. Set the animation update mode to continuous.
4. See Issue.

### Minimal reproduction project

[polygon_2d_animation_player_issue.zip](https://github.com/godotengine/godot/files/13070401/polygon_2d_animation_player_issue.zip)

**Comment by vyshliy** [comment]
Can confirm issue. Also discovered this when animating a polygon, but the same thing happens when trying to animate any PackedVector2Array.

In version 4.1.1 the animation was played in the continuous mode, but only with linear interpolation. Cubic was broken completely:  it made polygon invisible and removed array data.

**Comment by TokageItLab** [comment]
May be fixed by https://github.com/godotengine/godot-proposals/issues/8085.
