### ISSUE TITLE
Some 2D drawing specific methods I'm missing

### ISSUE THREAD

**Issue by RayKoopa** [godotengine/godot#8385]
**Operating system or device - Godot version:**
3.0 master

**Issue description:**
Can someone tell me if we already have the following helper functions? They're super useful for UI drawing and save a lot of duplicate code. If not, can I implement them, and if yes, is there a favorized place for such?
- Inflating / deflating `Rect2` structures. If you have a margin (4,4,4,4) and a rect (0,0,100,100), calling `inflate(4,4,4,4)` extends it to (-4,-4,104,104). You can also pass negative numbers to deflate. Idea stolen from .NET `System.Drawing.Rectangle`. Useful for expand margins etc.
- Font drawing is given a `Point2`, but the origin of the resulting text always seems to be bottom-left. Add parameters to `font->draw` to accept center- or right-aligning, also vertically. Needed this quite some time when centering text in rectangles (text in `WindowDialog` titlebar or on tabs), especially since the font ascents and descents are annoying to work with. S. [here](https://github.com/Syroot/XRay/blob/master/src/Syroot.XRay/Video/Font.cs#L154) for some implementation idea in C# (which also fits text into a rectangle).
- "right" and "bottom" properties on Rect2, which basically just return `pos.x + size.x ` or `pos.y + size.y`.

**Comment by hubbyist** [comment]
Ideas can not be stolen, they are bulletproof. :smile:

**Comment by magyar123** [comment]
Not sure about your first point, but isn't [this](http://docs.godotengine.org/en/stable/classes/class_rect2.html#class-rect2-grow) what you are looking for? And what are those margins? We you talking about the margins in controls? Those have nothing to do with the Rect2 structures.
And 👍 for the 3rd point

**Comment by RayKoopa** [comment]
@magyar123 Yeah, and you have to add margins manually to expand or shrink a Rect2 to respect them. That's a common task when drawing GUI stuff and aligning things, and this is what bullet 1 is for.

**Comment by magyar123** [comment]
But [Rect2.grow](http://docs.godotengine.org/en/stable/classes/class_rect2.html#class-rect2-grow) does exactly this.

**Comment by magyar123** [comment]
I think you can even pass in negative value. Since it takes a float

**Comment by RayKoopa** [comment]
Yeah, but that's by all sides, but it's required for up to all four sides at times.

**Comment by magyar123** [comment]
Oh I see now 😊 Sorry didn't got it for the first time

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
