### ISSUE TITLE
Throwing Error: invert: Condition "det == 0" is true.  core/math/basis.cpp:47 @ invert()

### ISSUE THREAD

**Issue by Sammyueru** [godotengine/godot#83854]
### Godot version

4.1.2

### System information

Windows 10 Godot 4.1.2 Mono

### Issue description

Debugger throwing:
```
E 0:00:01:0720   invert: Condition "det == 0" is true.
  <C++ Source>   core/math/basis.cpp:47 @ invert()
```
Every frame

### Steps to reproduce

I think it might have something to do with have physical bones from what I've seen but I have "Animate Physical Bones" set to false

### Minimal reproduction project

![image](https://github.com/godotengine/godot/assets/60794497/3b3cfcd2-a1b1-4e88-a9ce-b4969e1a7150)
![image](https://github.com/godotengine/godot/assets/60794497/52c5bbe1-e3ff-463a-a4c4-b01aea8ba1f8)
![image](https://github.com/godotengine/godot/assets/60794497/477d17a3-c080-447c-9686-69c7859fd2b2)
![image](https://github.com/godotengine/godot/assets/60794497/93712c0a-60e6-42c6-b3db-2778f6eae7aa)
![image](https://github.com/godotengine/godot/assets/60794497/ee4a007c-9e79-4e12-bc5a-5cd2f53f1660)
![image](https://github.com/godotengine/godot/assets/60794497/3a2b1b1b-981b-4dd0-8ad0-2ada10cee821)
![image](https://github.com/godotengine/godot/assets/60794497/20eee2ab-5cc6-4f84-9f5e-c2b935bc6687)

**Comment by Sammyueru** [comment]
> Seems related to:
> 
> * [Skeleton2D and Bone2D throwing error "core/math/transform_2d.cpp:51 - Condition "det == 0" is true." #83558](https://github.com/godotengine/godot/issues/83558)

Shoot it is related to that.

**Comment by AThousandShips** [comment]
Please provide an actual minimal reproduction project to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by martinfelis** [comment]
![image](https://github.com/godotengine/godot/assets/470116/783755b2-a7be-468b-ad86-b57f88cd0300)

The rotation is invalid. The first three columns of the transform represent the rotation. To have no rotation you need ones on the diagoals everything else 0.

This is indeed the same problem as in https://github.com/godotengine/godot/issues/83558

**Comment by GreatRedBird** [comment]
Sorry to ask again, but can you write in more detail? I’m doing a 2D project, where exactly should I put 1? I've already tried all the options, but I still don't understand what the point is.
![image](https://github.com/godotengine/godot/assets/65868341/ad94c734-1b42-4a63-83d4-e359c79bbc6d)

**Comment by AThousandShips** [comment]
In `xx` and `yy`
