### ISSUE TITLE
MovieWriter drops FPS from 60 to 10

### ISSUE THREAD

**Issue by lovesuper** [godotengine/godot#83864]
### Godot version

4.1.1

### System information

Windows 11 / Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3070 Laptop GPU

### Issue description

When enabled MovieWriter drops game FPS from 60 to 10-12. My Godot MovieWriter settings is default (except file path of cource).

### Steps to reproduce

Enable MovieWriter and start the game. Watch your FPS drops down to 10.

### Minimal reproduction project

[platformer.zip](https://github.com/godotengine/godot/files/13079359/platformer.zip)
This is just a standard Godot Example 3D Platformer.

**Comment by Calinou** [comment]
This is expected, as MovieWriter needs to wait for each frame to be saved (which can take a while due to MJPEG or worse, PNG compression). The GPU also needs to wait for the CPU for each frame as frame data needs to be gathered on the CPU for each frame, which also incurs a significant slowdown.

Closing, as this is already tracked in https://github.com/godotengine/godot-proposals/issues/4751.
