### ISSUE TITLE
Android activity launchMode should set to "singleTask"

### ISSUE THREAD

**Issue by kxn** [godotengine/godot#83924]
### Godot version

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.22011.4008) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### System information

Godot v4.1.1.stable - Windows 10.0.22621 - Vulkan (Compatibility) - AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.22011.4008) - Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz (16 Threads)

### Issue description

Currently it sets to "singleInstance", which causes black screen when

1:  The game integrates SDK that have another activity, e.g  ads sdk
2:  The user switched the game to background while the full screen activity is on top. e.g, a reward ad is being played
3:  Android system had determined to kill the game activity (onDestroy was called)
4:  The user switched the game back to foreground

I'm not familiar with Android development, so I took a look at an Unity built apk with ads sdk, and I noticed the launchMode is "singleTask". I changed apk built by Godot to "singleTask", and the issue went away.

It seems singleTask doesn't cause any other problem, at least in my project. So it might be good to change this in Godot export template as well.

### Steps to reproduce

as stated in issue description

### Minimal reproduction project

Can't provide because it need my ads sdk key :(

**Comment by akien-mga** [comment]
CC @m4gr3d

**Comment by kxn** [comment]
> @kxn Can you test with using `singleInstancePerTask` instead of `singleTask` and see if that fixes the issue.

Seems working fine, too.

Out of curiosity, what's the difference between the three? why do we prefer singleInstancePerTask over singleTask?

Thanks

**Comment by kxn** [comment]
> > @kxn Can you test with using `singleInstancePerTask` instead of `singleTask` and see if that fixes the issue.
> 
> Seems working fine, too.
> 
> Out of curiosity, what's the difference between the three? why do we prefer singleInstancePerTask over singleTask?
> 
> Update: I've just checked apks built by Unreal Engine 4.27, it is singleTask as well.

To clarify a little bit， I had tested "singleInstancePerTask"  in previous post, it was working fine.  The rest of the post is just my own curiosity, not  a blocking issue.

**Comment by m4gr3d** [comment]
> > @kxn Can you test with using `singleInstancePerTask` instead of `singleTask` and see if that fixes the issue.
> 
> Seems working fine, too.
> 
> Out of curiosity, what's the difference between the three? why do we prefer singleInstancePerTask over singleTask?
> 
> Update: I've just checked apks built by Unreal Engine 4.27, it is singleTask as well.

@kxn To provide some context, Android organizes Activities into groups called [Tasks](https://developer.android.com/guide/components/activities/tasks-and-back-stack), and the `launchMode` attribute influences how Activities are launched into these tasks:
- `singleInstance` causes the Activity to always be launched into its own task, and doesn't allow any other Activities into that task. So in your scenario, the Activity from the SDK was launched into another task causing the task holding the Godot Activity to be terminated by the system (note that in general immediate termination is not the norm as the system can hold multiple tasks at the same time, so you may need to check your device settings to ensure that it's not limiting how many tasks can run in the background).
- `singleTask` causes the Activity to be launched into its own task, unless there's an existing task with the same [taskAffinity](https://developer.android.com/guide/components/activities/tasks-and-back-stack.html#Affinities). Unlike `singleInstance`, `singleTask` allows other Activities in the same task so it's also a solution for your issue.
- `singleInstancePerTask` causes the Activity to always be launched into its own task, but like `singleTask` admits other Activities into that task. So it also addresses your issue because now the Activity from the SDK can run into the same task as the Godot Activity. Given the similarities with `singleTask`, it's selected for future-proofing because it'll allow to support  non-embedded [Godot Window](https://docs.godotengine.org/en/stable/classes/class_window.html) on Android for Godot 4.3.

For more details, feel free to take a look at:
- https://developer.android.com/guide/components/activities/tasks-and-back-stack.html#TaskLaunchModes
- https://developer.android.com/guide/topics/manifest/activity-element#lmode
