### ISSUE TITLE
UNSAFE_CAST warning on dictionary field accessors

### ISSUE THREAD

**Issue by rcorre** [godotengine/godot#84027]
### Godot version

4.1.2.stable.arch_linux

### System information

Linux 6.5.8-arch1-1

### Issue description

```
extends Node

class Thing:
	pass

func _ready() -> void:
	var d := {"one": Thing.new()}

	# (UNSAFE_CAST): The value is cast to "Thing" but has an unknown type.
	var w := d.one as Thing
	var x := d["one"] as Thing

	# OK
	var y := d.get("one") as Thing
	var z := (d.one as Variant) as Thing
```

Conceptually all of these statements seem the same, but it's odd that the first two warn of an unsafe cast and the latter two do not. It seems that the builtin accessors do not return a `Variant`, but I'm not sure what they do return. Is there any way to make these consistent?

### Steps to reproduce

See above code.

### Minimal reproduction project

[example.zip](https://github.com/godotengine/godot/files/13183481/example.zip)

**Comment by dreed-sd** [comment]
Is it intended that this change makes casting any variant a warning? For example, getting a setting out of ClientSettings and casting to a boolean is now considered an unsafe cast warning. Sure it's potentially an invalid cast, but you literally have no choice if you want to read a boolean out of settings. This seems to make working with types and APIs that use Variant extremely cumbersome.

```
	if _client_settings.has_setting(DEV_ALWAYS_ON_TOP_KEY):
                 # next line causes a unsafe cast warning
		var always_on_top: bool = _client_settings.retrieve_setting(DEV_ALWAYS_ON_TOP_KEY) as bool
		set_window_on_top_state(always_on_top)
```

**Comment by akien-mga** [comment]
CC @dalexeev 

Intuitively, I would say that indeed casting a Variant to anything other than Variant is "unsafe", so the warning is correct.
Its usefulness is dubious on the other hand in this situation, and I agree there's no good alternative to what you're doing.

Maybe `UNSAFE_CAST` should be split into two warnings:
- `UNSAFE_CAST` with Variant casts excluded
- `UNSAFE_CAST_VARIANT` to check Variant casts (disabled by default)

Or outright excluding Variant casts from the check, and documenting it?

**Comment by dalexeev** [comment]
@akien-mga Alternatively, we could make the `as` operator safe for built-in types too. That is, silently returning the default value for the type if the cast is not possible. This would make the `as` behavior similar to [`type_convert()`](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-type-convert) instead of deprecated [`convert()`](https://docs.godotengine.org/en/stable/classes/class_%40gdscript.html#class-gdscript-method-convert).

Of course, this would break compatibility in some sense, but it would not change any existing valid behavior. This would simply make acceptable what is currently causing an error.

This is bad for debugging in the sense of hiding the error, but in my opinion it fits better with the behavior of the `as` operator on objects. In many languages, type casting operations assume that the programmer understands what they are doing. Type casting is not something that should be used thoughtlessly.

**Comment by mihe** [comment]
Looking at the issue as reported, the question in my mind is why is `Dictionary.operator[]` (and the magic dot property access I guess) returning an untyped `Variant` (`is_hard_type() == false`) rather than an annotated (`is_hard_type() == true`) one?

Wouldn't changing that to return an annotated `Variant` (if at all possible) along with restoring the old behavior of `UNSAFE_CAST` similarly resolve the inconsistency reported here?

**Comment by dalexeev** [comment]
* @mihe It's another issue, see #83718.

**Comment by mihe** [comment]
@dalexeev Ah, gotcha.

Would you object if I suggested that #84043 be reverted and that we instead consider #83718 (once subscript resolution is addressed) to be the fix for this instead?

**Comment by dalexeev** [comment]
@mihe As I said, these are different issues. The `UNSAFE_CAST` warning exists solely for built-in type casts. If we do as I suggested above, then `UNSAFE_CAST` will never be produced and will become deprecated. However, this has nothing to do with hard/weak `Variant` type inference for arrays and dictionaries.

**Comment by mihe** [comment]
> The `UNSAFE_CAST` warning exists solely for built-in type casts. If we do as I suggested above, then `UNSAFE_CAST` will never be produced and will become deprecated.

@dalexeev Right, sorry, I wasn't suggesting that reverting was preferable to what you suggested necessarily, but rather perhaps better suited for the short term, seeing as how this new behavior of `UNSAFE_CAST` is now headed for 4.3. If that's not the case then I'll be quiet.

> However, this has nothing to do with hard/weak `Variant` type inference for arrays and dictionaries.

I don't quite follow. From what I understand `my_dict.get("some_key")` currently returns a hard variant, and `my_dict["some_key"]` currently returns a weak variant, assuming that `my_dict` is a hard-typed dictionary, which would explain why `my_dict.get("some_key") as Whatever` now triggers `UNSAFE_CAST` when it didn't before, since the `!op_type.is_hard_type()` check was removed in #84043.

Wouldn't that mean that making it so that `my_dict["some_key"]` (and `my_dict.some_key`) returns a hard variant instead would then resolve the inconsistency reported in this issue by not triggering `UNSAFE_CAST` in any of the four cases seen in this issue's description, assuming of course that #84043 is reverted first.

**Comment by dalexeev** [comment]
> but rather perhaps better suited for the short term, seeing as how this new behavior of `UNSAFE_CAST` is now headed for 4.3

I'm not sure about this. If we really want to do as I suggested above, then there is a chance that we will have time to implement this for 4.3. But while we are not sure about this, I think that the current behavior is more correct than the previous one. The lack of warning in some cases was a bug. Alternatively, you can disable this warning or use `type_convert()` instead, if you are casting to a built-in type (except typed arrays, `type_convert()` does not work with them).

> Wouldn't that mean that making it so that `my_dict["some_key"]` (and `my_dict.some_key`) returns a hard variant instead (#83718) would then resolve the inconsistency reported in this issue by not triggering `UNSAFE_CAST` in any of the four cases seen in this issue's description

`UNSAFE_CAST` should be produced for any `Variant`, **both hard and weak**. Hard `Variant` still means that the expression can be a built-in type, so we will get the same runtime error as in the case of weak `Variant`.

**Comment by dreed-sd** [comment]
There are some good thoughts in this thread about improvements, should there be a new issue created?

**Comment by mihe** [comment]
Perhaps the change to the `as` operator mentioned [here](https://github.com/godotengine/godot/issues/84027#issuecomment-2078975758) could be made into a proposal/PR? That seemed like a reasonable suggestion to me.
