### ISSUE TITLE
GPU Particles 2D/3D in compatibility rendering sometimes don't emit on 4.2

### ISSUE THREAD

**Issue by WagnerGFX** [godotengine/godot#84072]
### Godot version

v4.2.beta3

### System information

Godot v4.2.beta3 - Windows 10.0.19045 - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 1650 (NVIDIA; 31.0.15.4592) - Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 Threads)

### Issue description

Some of the GPU Particles nodes seem to not emit, while others do.
- This changes every time I re-open the editor, scenes or run the project.
- Duplicating the particle nodes makes the new one work in the editor, but running or reopening the scene starts the issue again.
- The issue still happens when using opengl3_angle on GL Compatibility
- This does not seem to happen on 4.1.2

https://github.com/godotengine/godot/assets/16827309/79f6b47e-51b9-410e-ae65-075adc65a484

### Steps to reproduce

The reproduction project has "main_2d" and "main_3d" scenes that show the issue, even in the editor.
You can re-open and/or run the project multiple times to see how the issue changes every time.

### Minimal reproduction project

[GPUParticles Compatibility.zip](https://github.com/godotengine/godot/files/13192388/GPUParticles.Compatibility.zip)

**Comment by akien-mga** [comment]
I can confirm the bug. Note that the particle effect looks different in 4.1.2-stable and 4.2-beta3 (like in the video), but that seems due to a separate regression which was since fixed (4.1.2-stable and 4.x master behave similarly, aside from this bug of randomly not emitting).

Seemed typically like uninitialized memory usage, found the bug, I'll make a PR.
