### ISSUE TITLE
BPTC and ASTC texture compression support

### ISSUE THREAD

**Issue by elasota** [godotengine/godot#8418]
BPTC is a baseline feature of D3D11, so it's pretty widely available on PC now, and consoles support it as well.  ASTC support on PC is limited to Intel, and on mobile is limited to Tegra and Mali, but support for it will likely improve over time.

Regardless, both share a design challenge: They permit size/quality tradeoffs that break the assumption that there is a single optimal VRAM-compressed format for an image.  ASTC does this by having configurable block sizes, and BPTC does this by being higher quality than DXT1 on RGB-only data, but at twice the size (unlike DXT5, which has no quality advantage over DXT1 on RGB).

So, it would make sense to apply a quality option to images exported to VRAM formats in addition to lossy.  For BPTC, this would mean switching to DXT1 for RGB below some threshold.  For ASTC, it would mean using larger block sizes at lower quality.

**Comment by elasota** [comment]
I have a BPTC implementation using FasTC on a 2.1 fork that just adds it as a checkbox option in the Windows exporter and uses the Compress Extra flag to switch RGB to DXT1, but it'll need some additional port work for master due to format changes.  I can open a PR if you want.

**Comment by Calinou** [comment]
ASTC is supported in OpenGL ES 3.2, but I heard it was only supported by NVIDIA (a few months ago). From a quick look, [the open source drivers don't seem to support it either](https://mesamatrix.net/). So, a fallback is absolutely needed in case it is implemented.

**Comment by endragor** [comment]
ASTC is supported not only by Mali, but also by Adreno GPUs launched since late 2014. Most mid- and high- end Android devices today support it. But of course you need fallback to ETC to support lower end devices. And even ETC2 is not supported by all the Android devices used today.

**Comment by reduz** [comment]
BPTC is supported, but we are missing mainly a BC6H compressor.
ASTC is great but very unsupported yet

**Comment by elasota** [comment]
Re-upping this.  I have a newer BPTC integration ready to go for master, including BC6H, but need some feedback on some feature design:

- Rename "Compress" HDR Mode import option with "LDR Fallback", add "RGBE Fallback" that generates an RGBE9995 texture, which ensures that the texture is always HDR regardless of platform.
- Add "fallback" pseudo-feature that's considered supported on any platform.  (Less messy than adding another feature just for the fallbacks, which use a baseline format).
- Add a method to platform exporters to resolve feature priorities when multiple are present, and add "no BPTC fallbacks" option to PC exports.  That should allow developers to exclude S3TC and RGBE fallbacks when they're okay with requiring D3D11 hardware.
- Add support for HDR texture mipmap generation (right now this is bugged and produces black mipmaps).

Also need to fix a bug with texture_get_data crashing when BPTC isn't supported, due to it using the texture's format (which isn't the same as the decompressed format) to determine the data size, which makes the output buffer too small.

I can open a PR if that sounds good, otherwise feedback would be appreciated.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
