### ISSUE TITLE
When set as "render target", viewport blocks input for children nodes

### ISSUE THREAD

**Issue by tr0q** [godotengine/godot#8419]
Godot 2.1.3
(can be quickly tested with the "3d in 2d" demo)
Set up viewport as render target, add child with script that uses _input or _unhandled_input and try print event - nothing will happen. With "render target" disabled this issue won't appear.

**Comment by SolarMongoose** [comment]
This might be sort of by design?

Viewports have a method called "input(local_event)"
http://docs.godotengine.org/en/stable/classes/class_viewport.html#class-viewport-input
(and there's also one for "unhandled_input(local_event)"
which just... propogates the event...

So the simplest way to use it would be
```
extends Viewport


func _ready():
	set_process_input(true)
	set_process_unhandled_input(true)


func _input(event):
	input(event)


func _unhandled_input(event):
	unhandled_input(event)
```

Which should be enough if you only need key/button presses.
If you need mouse or screen touch events then you'll probably need to do some sort of position correction on the events to make them work right.

**Comment by tr0q** [comment]
> So the simplest way to use it would be
> 
> extends Viewport
> 
> 
> func _ready():
> 	set_process_input(true)
> 	set_process_unhandled_input(true)
> 
> 
> func _input(event):
> 	input(event)
> 
> 
> func _unhandled_input(event):
> 	unhandled_input(event)

Doesn't work for me, children still doesn't receive input.

**Comment by SolarMongoose** [comment]
Oops. I thought I had made it work like that, but you're right, it doesn't.

Turns out the way I had gotten it to work was by catching the input in a _different_ node (specifically the ViewportSprite I was displaying the viewport on, if that's important).

So you `set_process_input(true)` in this _other_ node, then call
`get_node("path/to/Viewport").input(event)`

Tried in 2.1.3. Should work. Hope I helped... at all.

**Comment by tr0q** [comment]
Thanks, it works. But I wonder why it has to be like this.

**Comment by reduz** [comment]
It is by design. imagine you draw 2D or an UI over an object in 3D.. it is
up to you on how to send input coordinates to it.

For regular uses (just a sub viewport in 2D), you put the viewport as child
of a Control (or ViewportContainer in 3.0) and eventd are forwarded
automatically.

**Comment by kubecz3k** [comment]
I'm revisiting old issues, closing since this is not a bug.

**Comment by jonSP12** [comment]
It has something to do with camera...
It only works if the camera zoom is at maximum size ( default 1280x720 )

If the camera is somewere in the level follwing the player... or zoomed at 0.5, the button coordinates inside the viewPort get passed somwere around the topLeft corner
