### ISSUE TITLE
Drawing a StyleBox that was set in the theme in _draw() draws a default StyleBox instead

### ISSUE THREAD

**Issue by robbertzzz** [godotengine/godot#84259]
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Windows 11

### Issue description

I'm not entirely sure where the exact issue is, but it's a regression in 4.2 (4.1.2 doesn't have this issue). Drawing a StyleBox in _draw, when using a type variation from a Theme, draws a default StyleBox with no background and a white border. Drawing a StyleBox from an exported variable works correctly, so it's related to the use of a Theme.

In the attached screenshot you can see the incorrect default StyleBox that is drawn in the viewport and the one that should be drawn in the Inspector.

![image](https://github.com/godotengine/godot/assets/7684647/032aaf27-7cdc-475e-ac01-f5e1f19d875f)

### Steps to reproduce

See attached reproduction project below. The script with the _draw() function is running in tool mode, so the issue will be immediately apparent upon opening the project. The issue persists when running the game.

### Minimal reproduction project

[stylebox issue.zip](https://github.com/godotengine/godot/files/13219289/stylebox.issue.zip)

**Comment by nickyfoo** [comment]
Trying to look into this rn!

**Comment by YuriSizov** [comment]
Your type variation doesn't have a base type. It needs to have one to work, because type variations extend one of the existing types.

Do this and it will draw the expected stylebox:
![image](https://github.com/godotengine/godot/assets/11782833/6671700e-f6ed-4126-ac22-dc2b50b6446e)

**Comment by nickyfoo** [comment]
I've narrowed it down to `scene/theme/theme_owner.cpp`, namely [this line](https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/scene/theme/theme_owner.cpp#L226).

Because in the sample the `StyleBoxDrawer` doesn't inherit from native types, this check fails and it doesn't pick `StyleBoxDrawer` up as a type dependency.

There are now two options:
- We could fix this with by removing the check ` && owner_theme->get_type_variation_base(type_variation) != StringName()`, but I think we may not want that, especially because of [the comment in line 219](https://github.com/godotengine/godot/blob/5ee983188de97ae027f9b9c1443438063f708a7e/scene/theme/theme_owner.cpp#L219) that states we want all variations to derive from native types.
- In that case, I'd suggest to make `StyleBoxDrawer` derive from `Control` in the theme editor, which works fine as a workaround. 
![image](https://github.com/godotengine/godot/assets/67411893/e5b5d242-bae2-46b4-8737-9f52ac6b63c2)

We should further update documentation on variations to explicitly state that your variations MUST derive from a native base class if that is the case.

Would appreciate if one of the more experienced contributors weigh in on what my next steps should be!

**Comment by YuriSizov** [comment]
> We should further update documentation on variations to explicitly state that your variations MUST derive from a native base class if that is the case.

Documentation already explains that you should set up a base type: https://docs.godotengine.org/en/stable/tutorials/ui/gui_theme_type_variations.html#creating-a-type-variation

**Comment by nickyfoo** [comment]
Ah I see, when reading it I think I interpreted the prompt "Filter the list of types or create a new custom type" to mean that an empty base type was a valid base type as well 😅 

Thanks for the vote of confidence!

**Comment by robbertzzz** [comment]
Interestingly, any "base type" works. Why can't this field be left empty if that's the case?

![image](https://github.com/godotengine/godot/assets/7684647/77a7a082-4f72-4351-b11d-062567178ef1)

**Comment by YuriSizov** [comment]
> Why can't this field be left empty if that's the case?

Because there is no expected scenario where a _variation_ of something doesn't have any base something. To be clear, you need to use the specific type you are going to use this variation on. I suggested "Control" because that's the node that you're using it on. But if you plan to use it on, say, Panel, then it should be "Panel" as the base type.

Theme type variations are not a way to define completely arbitrary custom theme types. They are a way to extend existing types with subtypes.

**Comment by robbertzzz** [comment]
@YuriSizov No I get that, but the base type I entered doesn't exist and yet the override still works. Sounds to me like we don't need the base type and leaving the field blank has been disabled without any reason to do so.

The reason I opened this report was for a custom Container I created. I didn't include it because it wasn't necessary for a minimal repro project. Container does not show up in the list of base types, nor does Control, so your solution is not intuitive to the user. If functionally the base type is not needed, I would say the requirement for the field to not be empty should not exist.

**Comment by YuriSizov** [comment]
> Container does not show up in the list of base types, nor does Control

That's not intended and should be fixed.

**Comment by robbertzzz** [comment]
Alright, clear. So lastly then, should there be a bug report for this still working with non-existent class names?

**Comment by YuriSizov** [comment]
> should there be a bug report for this still working with non-existent class names?

Sure. Although it may be not worth it to fix it in the end (checking for existing classes can add up, and here it's not critical). As you suggest, checking for empty names is not necessarily needed either, but it's a pretty good indication that the variation has not bee set up correctly. So a cheap check that hints at a potential issue is fine, whereas a more expensive check may be too much.

But it's always good to keep track of things, so feel free to open an issue!
