### ISSUE TITLE
Node3D children using top_level in different position in-editor vs. runtime

### ISSUE THREAD

**Issue by donn-xx** [godotengine/godot#84290]
### Godot version

v4.2.beta3.official [e8d57afae]

### System information

Godot v4.2.beta3 - Ubuntu 22.04.3 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 535.113.01) - Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 Threads)

### Issue description

UPDATE:
I was mistaken about the Sphere. It also moves to a different position when running. Overall, it's confusing that stuff is not in the same position between the editor and runtime.

This image shows how in the editor, the position of things is different to when the game runs. This seems a bit weird to me.
At first I thought it was any child of a Node3D, so I added a MeshInstance sphere (set as top_level) and it works fine! So, it's only the MultimeshInstance nodes that go a bit haywire. 
![image](https://github.com/godotengine/godot/assets/392218/3b39aadb-9f76-428d-a66b-dc7385fbbec3)

### Steps to reproduce

- Put a Multimesh node in a Node3D and set it as top_level. 
- Move the parent around in the editor and compare that to
- Running the scene.

I made a small repo, see below for the project.

### Minimal reproduction project

Repo here:
https://gitlab.com/dbat/top-level-issue

**Comment by rsburke4** [comment]
It looks like the issue was with global transforms being applied locally when a tree is entered. The PR https://github.com/godotengine/godot/pull/84643 should fix that, with the additional change that position info should update immediately between local and global transform upon checking the top_level box. This prevents the game from running with outdated information, which previously only updated when the object was moved again.
