### ISSUE TITLE
Incorrect UndoRedo when duplicating nodes at different depths.

### ISSUE THREAD

**Issue by MewPurPur** [godotengine/godot#84333]
### Godot version

Godot v4.2.beta3 - Pop!_OS 22.04 LTS - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) () - 12th Gen Intel(R) Core(TM) i5-1235U (12 Threads)

### System information

^

### Issue description

![image](https://github.com/godotengine/godot/assets/85438892/5b4fe953-7afc-41de-8dd3-d785a17344c5)

When duplicating these nodes, I get:

![image](https://github.com/godotengine/godot/assets/85438892/77809bb3-1f7d-441e-b766-b008d5607ce6)

When I undo, it deletes the new nodes one by one. The second undo lands me here:

![image](https://github.com/godotengine/godot/assets/85438892/979f69a4-c585-440c-8da9-b1ac8807e58a)

Note that the node is now Node3, rather than Node2.

Quite a few unexpected behaviors are going on. I don't know what the functionality here should be, but since undo is failing to land me at my initial place, something is definitely wrong here.

I also had this crash on me while working on a project, but couldn't reproduce it while testing for the bug report.

### Steps to reproduce

Clarified above

### Minimal reproduction project

N/A

**Comment by TheSofox** [comment]
Firstly, can someone tell us whether this is the expected behavior for the initial behaviour of duplicating two nodes at different levels in the hierarcy? I would have thought the duplicated nodes would appear at the same level of the node they are duplicating from. Hence, if you select nodes at 3 different levels, duplicating will put new nodes on each of those 3 levels. If the current Godot behaviour for this is wrong, it needed to be fixed first (possibly with a separate bug report) before we tackle the undo/redo aspect.

**Comment by MewPurPur** [comment]
> I would have thought the duplicated nodes would appear at the same level of the node they are duplicating from.

This would be my assumption too.

**Comment by TheSofox** [comment]
I'd honestly recommend you file a separate bug report for nodes not being duplicated property in the first place. Keep the issues separate. Only when that's fixed/addressed can we focus on the Undo behaviour.

**Comment by TheSofox** [comment]
Just gotta mention I was ultimately wrong about my last comment. When I was fixing this bug in my PR I discovered that the two issues were in fact closely connected and fixing one fixed the other. In any event, it's all fixed and merged now so that's good.
