### ISSUE TITLE
node children draw out of order

### ISSUE THREAD

**Issue by romulox-x** [godotengine/godot#844]
I can't upload an example project for this at the moment, because the hosting service is failing for some reason.  But it's very simple.  Add a Node2D as a root node.  Add to this two children: a Node, and a Sprite.  To the Node, add a sprite child.  Though the Node and its sprite child come first in the tree, the sprite draws on top of the original sprite.

**Comment by her001** [comment]
I have a real example for this: https://github.com/her001/robins-rescue-godot/tree/1acbdacfb6c8558a185aa20123d1c76b491ad81a

Run the project, click "New Game," then right click to open the inventory, then press escape to pause. The pause menu will have the inventory and a cursor, because those are contained in a plain "Node" type node. If you switch the node type in the ui.xscn to a control, z-ordering works as expected.

**Comment by akien-mga** [comment]
I can confirm this bug by following the procedure described in the first comment.

**Comment by reduz** [comment]
I'll give it a check as soon as I can!

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by reduz** [comment]
This is fixed (or at least, irrelevant now), as this code was entirely rewritten in 3.0
