### ISSUE TITLE
Arrays in default arguments can be modified

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#84407]
### Godot version

4.2 beta4

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 30.0.15.1403) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

If a method has a default argument of type array, you can modify that array and the new content will be displayed in autocompletion tooltip. Easy to test with `OS.execute()` and an EditorScript.

https://github.com/godotengine/godot/assets/2223172/e6f90930-a046-425f-be1f-492a143b82c8

`OS.execute()` has an argument used for passing output. It defaults to empty array. If you don't pass the argument, the output will be inserted into the default array, which then shows in autocompletion.

### Steps to reproduce

1. Create EditorScript
2. Run `OS.execute()` with Godot as executable and no other arguments (`OS.execute("godot_console", [])`)
3. Observe the completion popup

### Minimal reproduction project

N/A

**Comment by chocola-mint** [comment]
Fixing this doesn't seem trivial at all. I've tried explicitly duplicating default values in all possible call sites, yet to no avail.

There is however a workaround, though. Instead of using `Array()` as the default value, we could use a read-only array (marked with `Array::make_read_only()`), and in the method implementation, use `Array:is_read_only()` to check and avoid modifying the array. A quick search in the codebase suggests that `OS::execute` is currently the only bound method that breaks this rule, so the amount of modification wouldn't be too much.

What do you think?

**Comment by dalexeev** [comment]
Looks like #92888 fixed it, doesn't it? СС @Hilderin

**Comment by Hilderin** [comment]
Totally, #92888 fixes this issue.
