### ISSUE TITLE
Errors don't provide enough context to fix

### ISSUE THREAD

**Issue by Deozaan** [godotengine/godot#84432]
### Godot version

v4.2.beta4-GodotSteamMultiplayer.custom_build [e07b3ee25]

### System information

Windows 10

### Issue description

When testing my project in the editor, I get several errors in the form of:

```
E 0:00:57:0386   GodotPhysicsServer2D::area_set_shape_disabled: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
  <C++ Error>    Condition "area->get_space() && flushing_queries" is true.
  <C++ Source>   servers\physics_2d\godot_physics_server_2d.cpp:355 @ GodotPhysicsServer2D::area_set_shape_disabled()
````

I understand I'm supposed to change something to use `call_deferred`, but I don't know what. There's not enough context in the error to tell me specifically what part of my code is causing this error.

My expectation is that an error should tell me specifically what line in my code is causing the error. Otherwise, its usefulness to me is limited.

### Steps to reproduce

Not sure because the error isn't specific enough. Maybe try disabling (or `queue_free`?) some physics shape/node during `_process` or `_physics_process` and get the error.

### Minimal reproduction project

Should be fairly trivial to reproduce.

**Comment by smix8** [comment]
You need to provide more information or an MRP.

The error is pretty clear that the PhysicsServer is locked for state changes because it is doing updates.

What should be called with call_deferred() is the node or object function that starts the disabled chain in your custom script.

All points to unsafe and unsupported thread use because in a normal loop triggering that error point would be an achievement while it is very easy to trigger with unsafe and unsupported thread use on Nodes / SceneTree / PhysicsServer.

**Comment by Deozaan** [comment]
> All points to unsafe and unsupported thread use because in a normal loop triggering that error point would be an achievement

I'm surprised by that statement. I've been getting errors like this a lot. Much of the time it's right after I implement a feature so it's easy to know that the code I just wrote is causing the error. But sometimes I'm not the one who wrote the code and I don't know what's causing it.

But the code doesn't do anything custom with threads that the engine isn't doing automatically/by default. It just uses `_process` or `_physics_process`. Or it's probably something happening as a result of a `body_entered` or `area_entered` signal. In other words, my guess is that it is something in reaction to collision. Or possibly it's in response to a timer's `timeout` signal. As I said, I really can't tell where it's happening because the error doesn't tell me.

**Comment by Deozaan** [comment]
I found it. It's happening due to an `add_child` call, which is happening in response to a `body_entered` signal.

**Comment by smix8** [comment]
Calling add_child() with a CollisionShape based node will trigger shape owner updates, one of them is the area_set_shape_disabled() call from your error.

In general since Area updates are done by the physics space processing which is always done while the PhysicsServer is locked it is not safe to do immediate physics manipulations in that same signal function callback. This in includes adding or editing physics based nodes in the SceneTree.

If you do the add_child() with your next _physics_process() you should be safe because that gets called directly after the PhysicsServer unlocked from flush_queries(). You can also use _process() or call_deferred() but that adds a delay and might miss some physics iteration(s).

**Comment by Deozaan** [comment]
I don't really understand. I'm not trying to disable any shapes. I'm instantiating a scene whose root node is an Area2D (which has a CollisionShape2D child node).

But aside from that, why can't the error tell me it was my `add_child` call which was the problem?

> If you do the add_child() with your next _physics_process() you should be safe because that gets called directly after the PhysicsServer unlocked from flush_queries().

How should such a thing be done? The thing that comes to mind is to set a bool in signal callbacks in order to execute something in the next _physics_process() loop. But that feels like a kludge to me.

**Comment by skcalanderson2** [comment]
I have a related issue. If you watch this Youtube [video](https://youtu.be/FmIo8iBV1W8?t=3498), where a guy is making a Asteroids type game, he gets that deferred error, but on the 4.2 beta 4, the same code does not generate an error, however the signal that is in the line above does not get connected properly. So there is some strange behavior surrounding the add_child method when called from an emitted signal.

**Comment by Deozaan** [comment]
Here's another example of an error that doesn't really help me:

> E 0:04:39:0397   Node::get_node: Node not found: "Main/Players/Player1/Harpoon2" (relative to "/root").
>  <C++ Error>    Method/function failed. Returning: nullptr
>  <C++ Source>   scene\main\node.cpp:1639 @ Node::get_node()

Where in my code am I trying to get this node that can't be found? This error message needs to tell me which line of _my_ code this error is occurring at. It's really hard to fix errors when the errors don't provide enough context in the stack trace to let me know what part of my code is causing them.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/963, as this is the only way to resolve this issue entirely.
