### ISSUE TITLE
Scene gets corrupted when a script file referenced inside an array is moved or renamed

### ISSUE THREAD

**Issue by igorcmoura** [godotengine/godot#84498]
### Godot version

v4.2.beta4.official [93cdacbb0]

### System information

Godot v4.2.beta4 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz (16 Threads)

### Issue description

When a script that is referenced inside an Array in a scene is moved or renamed, the old reference remains corrupting the scene.

### Steps to reproduce

- Open the project.
- Rename `sample_resource.gd` to something else or move it to a folder.
- Try opening the `sample_scene.tscn`

Since `sample_scene.tscn` contains a reference to `sample_resource.gd` that was not moved, it will be corrupted:
```gdresource
resources = Array[Resource("res://sample_resource.gd")]([ExtResource("2_gl06r")])
```

### Minimal reproduction project

[MoveScriptIssue.zip](https://github.com/godotengine/godot/files/13272842/MoveScriptIssue.zip)

**Comment by AThousandShips** [comment]
Please provide an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by igorcmoura** [comment]
Thank you for the reply!
I updated the issue with the MRP.
