### ISSUE TITLE
Metallic workflow textures aren't stored efficiently

### ISSUE THREAD

**Issue by tagcup** [godotengine/godot#8459]
In the current implementation, metallic workflow uses R and A components of the image, for which only 16BPP space is required. However, they are stored as 32BPP RGBA images after they are imported.

**Comment by reduz** [comment]
Yeah, I think shaders should also have hint_red and hint_rg.. so it knows
how to compress on import better..

On Apr 19, 2017 9:12 PM, "Ferenc Arn" <notifications@github.com> wrote:

In the current implementation, metallic workflow uses R and A components of
the image, for which only 16BPP space is required. However, they are stored
as 32BPP RGBA images after they are imported.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8459>, or mute the thread

**Comment by tagcup** [comment]
It would work with ETC2/EAC, but is there a RG mode for S3TC?

**Comment by tagcup** [comment]
We should also be using R for ambient occlusion and all other single-channel textures (subsurf scattering, ...).

**Comment by tagcup** [comment]
An alternative would be to merge single- and double-channel textures into one, such that they're RGB or RGBX (meaning alpha channel is used for data not related to opacity).

**Comment by tagcup** [comment]
This is probably fixed now but can @reduz confirm this?

**Comment by reduz** [comment]
this is fixed now, SpatialMaterial uses a texture for each channel, but you can assign where to read from, closing
