### ISSUE TITLE
TileMap performance degradation on MacOS using ANGLE

### ISSUE THREAD

**Issue by Knight-XAura** [godotengine/godot#84591]
### Godot version

v4.2.beta5.official [4c96e9676]

### System information

Godot v4.2.beta5 - macOS 14.0.0 - GLES3 (Compatibility) - ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Version 14.0 (Build 23A344)) - Apple M1 (8 Threads)

### Issue description

MacOS seems to have very bad TileMap performance on very small (8 tiles) tile sets. I opened same project on my lower end Windows 10 machine and it ran perfectly. Once running game seems to run fine, it's only in the editor this issue seems to occur and I've noticed it in all the Betas I worked on this project in which was Beta 2. If I use the Stable 4.1.3 that was just released the performance issue doesn't exist. This is only since Version 4.2. I know some changes came with the system and may have greatly affected performance on the MacOS systems, but not Windows. Linux is unknown. 

### Steps to reproduce

Create a project with a TileMap and then attach any size tile set. Select the TileMap tab at the bottom and watch the editor feel like it's gonna come to a halt. 

### Minimal reproduction project

N/A

**Comment by Veradictus** [comment]
Encountering this issue as well, 4.1 ran perfectly fine on MacOS, moved to Godot 4.2 beta 6 and it's absolutely atrocious. I cannot even run the game anymore and it ends up crashing. I need the 4.2 version because of per-tile flipping.

**Comment by Calinou** [comment]
@Knight-XAura @Veradictus Can you try following the same steps on 4.2 dev/beta releases? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.2/).

**Comment by Knight-XAura** [comment]
It's the Rendered. Disabled in Beta 5 (sorry it's what I had already) and it works AMAZING

**Comment by tudor07** [comment]
Can confirm `opengl13` fixed the issue on `macOS 14.1.1`

**Comment by gamenerds** [comment]
While changing to opengl13 fixed the editor lag, it makes the game crash on launch for me (M1 MBP, doesn't matter if tilemap has few or no tiles). We need some real solution to this.

**Comment by akien-mga** [comment]
You both mentioned `opengl13` which doesn't exist, make sure you're using `opengl3`.

**Comment by clayjohn** [comment]
I spent some time looking into this today as we would like to eventually enable the Metal ANGLE eventually. I tracked the issue down to this line:
https://github.com/godotengine/godot/blob/a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0/scene/resources/2d/tile_set.cpp#L1561

This issues a draw call for each tile using a mesh with the PRIMITIVE_LINE_STRIP primitive. Line drawing is discouraged by Metal and meshes can't be batched together by Godot. This creates a perfect storm of performance problems resulting in the tilemap grid overwhelming the GPU. 

The solution will be to rewrite that function to use the line drawing API instead of the mesh drawing API. It shouldn't be a lot of work, but it isn't worth doing unless we re-enable the Metal ANGLE backend (which is currently on ice due to unrelated driver bugs)
