### ISSUE TITLE
RayCast3D doesn't update collision point when calling force_raycast_update()

### ISSUE THREAD

**Issue by Musicgun47** [godotengine/godot#84642]
### Godot version

4.1.3.stable

### System information

Windows 11, Intel Core i7

### Issue description

When updating a RayCast3D node's position via script, getting the collision point after calling force_raycast_update() returns the same point as prior to moving the node. 

### Steps to reproduce

Run sample project
Press Space
Results are printed to console.

### Minimal reproduction project

[RayCast Bug.zip](https://github.com/godotengine/godot/files/13302785/RayCast.Bug.zip)

**Comment by Musicgun47** [comment]
Have done some additional testing and it appears that this only occurs if the raycast doesn't hit anything from the new position. So get_collision_point() returns the point of collision from the last time it collided with anything even if it no longer is. Possibly intended behaviour, but if so, could use some clarification in the documentation to reflect this.

**Comment by kleonc** [comment]
You should be checking `RayCast3D.is_colliding()` before obtaining the collision point. It correctly returns false after force updating in the MRP. So no bug in here.

The position is indeed not changed when no longer colliding (the same for RayCast2D):
https://github.com/godotengine/godot/blob/d1381bbca264794eb3ba470789217ab6f5c91d3f/scene/3d/ray_cast_3d.cpp#L233-L246
I don't see a reason why it would need to be changed, there's no Vector3 value which would indicate there's no collision, the default `Vector3(0, 0, 0)` can be a valid collision point. That's why there's `collided` boolean stored (obtainable with `is_colliding` method).

But sure some notes could be added to the docs.
