### ISSUE TITLE
Godot v4.2.beta.mono editor freezes when quitting.

### ISSUE THREAD

**Issue by AwesomeJuniorMiss** [godotengine/godot#84728]
### Godot version

v4.2.beta.mono.custom_build

### System information

Windows 10 - Godot v4.2.beta.mono.custom_build - Vulkan (Forward+)

### Issue description

Godot editor freezes everytime I close it. So I have to terminate its process from task manager.

### Steps to reproduce

Open any project and close Godot editor.

### Minimal reproduction project

Any project, even empty project.

**Comment by zaevi** [comment]
More detail:

When freezes it prints:
```
ERROR: Condition "!EditorSettings::get_singleton() || !EditorSettings::get_singleton()->has_setting(p_setting)" is true)
   at: _EDITOR_GET (editor\editor_settings.cpp:1140)
```

I found it is called from `EditorExportPlatformAndroid::get_adb_path()` and it tried to get `export/android/android_sdk_path` settings (seems in other thread). But at this time EditorSettings has been freed.

**Comment by thygrrr** [comment]
The messages are often emitted in an endless loop, as if the Editor tries to wrap some work up and just can't.

It did not happen around changeset 3e7f638d7b574785f521beafaf52a6ad95be016f `clayjohn/editor-headless-scan` and started happening with later updates to master.

The bug happens both for the Mono and (I think, not 100% sure) Vanilla versions, both the console and non-console executables.

This bug actually happens to me on any quit since a while. It even happens when aborting the process with Ctrl-C (which normally cleanly closes the editor). It will then, even though the prompt is back and interactive, start spamming the console with these errors (see screenshot)

If the editor is running jobified, e.g. with `godot.windows.editor.x86_64.mono.exe --editor &` in PowerShell, then the editor will just hard hang on exit (no output); window turns grey and unresponsive.

`Stop-Process -name godot.windows.editor.x86_64.mono.exe` works as expected, but that's a hard and immediate termination almost like a `kill -9`

Terminating with the new "End Task from taskbar" Windows 11 developer feature gives this Windows 2000 era dialog:
![image](https://github.com/godotengine/godot/assets/8904620/9631c3d8-2568-46fe-be07-7e9783c7b88d)
followed by the newer Windows 10 style dialog 
![image](https://github.com/godotengine/godot/assets/8904620/7818d088-87af-4000-8301-b79819f84243)


![image](https://github.com/godotengine/godot/assets/8904620/3e735e30-33f5-4249-9367-e8ff0b18a2db)

I'll try to bisect this to narrow down the changeset. It's getting super annoying, because it causes the editor to hang on exit; and sometimes an editor-spawned engine, as well.

**Comment by thygrrr** [comment]
Going through all these bisects, I noticed there also seems to be a somewhat longer editor startup time associated with this or a nearby changeset. (I was able to guess from the startup duration whether the hang on exit was going to happen)

In non-editor run mode, the extra time is spent waiting in the logo screen of the application.

**Comment by thygrrr** [comment]
```git
f3e96a85485f68ee8c3e669e4bb6c910762a9130 is the first bad commit
commit f3e96a85485f68ee8c3e669e4bb6c910762a9130
Author: Pedro J. Estébanez <pedrojrulez@gmail.com>
Date:   Thu Nov 9 12:29:47 2023 +0100

    Make languages bookkeeping thread-safe

 core/object/script_language.cpp    | 34 +++++++++++++++++++++++++++-------
 core/object/script_language.h      |  7 ++++---
 core/object/worker_thread_pool.cpp |  9 +++++++++
 core/object/worker_thread_pool.h   |  1 +
 4 files changed, 41 insertions(+), 10 deletions(-)
```

**Comment by akien-mga** [comment]
Yes it was already bisected above, and there's an open PR fixing it: https://github.com/godotengine/godot/pull/84847
