### ISSUE TITLE
Editor could remember which workspace was used/opened across scenes.

### ISSUE THREAD

**Issue by AxDSan** [godotengine/godot#8472]
**Operating system or device - Godot version:**
Windows 10 x64 - Godot 2.1.3 (Latest)

**Issue description:**
Whenever I open a workspace and I switch scenes it doesn't gets saved and the editor won't remember which one I had opened before on a previous scene, e.g. I open the 2D Workspace on Scene A on Tab A, I switch to Scene B on Tab B and open the Script Workspace, I switch back to Scene A on Tab A and the Workspace currently selected will be the one I had previously selected on Scene B on Tab B, so I have to manually change Workspace across tabs or scenes.

**Steps to reproduce:**
1. Create a new Scene, let's call it Scene A
2. Create a new Scene, let's call it Scene B
3. On Scene A, open the 2D Workspace.
4. On Scene B, open the Script Workspace.
5. While on Scene B, Switch to Scene A, the Workspace from Scene B will still be selected.
6. On Scene A, Switch Workspace to 2D.
7. While on Scene A, Switch to Scene B, the Workspace from Scene A will still be selected.

Here's a more visual description: https://puu.sh/vqAIA/9e7085820a.mp4

**Link to minimal example project:**
N/A

**Comment by gaudecker** [comment]
It seems that if the workspace is 2D or 3D it keeps that, otherwise it checks if there are more 2D or 3D nodes in the scene and changes workspace based on that.

You can see the implementation here:
https://github.com/godotengine/godot/blob/b63c506ad8499ff5ac1fd8f76296112a1274717d/editor/editor_node.cpp#L2791-L2841

I too thought that tabs needed to remember their context, but the more I think about it, tabs are really just different scenes and have nothing to do with code (or asset library) so it doesn't make sense to tie them to any other workspace than 2D or 3D.

What I would like is to get rid of the global workspaces and have different kind of tabs, e.g.:

- 1 tab per script file
- 1 tab per scene (can be in both 2D or 3D modes)
- 1 tab per asset lib (probably possibly in its own dialog)

But that is entirely different problem and much more work to implement.

**Comment by starry-abyss** [comment]
The caveat is there is a script mode for scenes too (useful from time to time), and if one scene is switched to it currently, then the other ones are screwed.

I agree about workspaces, current ones aren't helpful very much. They should better be per activity and act as overall layout changers like in Qt Creator (UI design, programming, debugging) plus more (level design, animation, etc), ideally in a way that user can create, share and install them (user can rearrange layouts already, so there is a starting point).

But I still want to implement this functionality first (likely after 3.1 release madness settles), because it's my struggle in a concrete project I'm working on.

**Comment by AxDSan** [comment]
Yup, that’s my exact point. And it also was a struggle for me too working
on a project, where constant switching between tabs/workspaces I expected
this behavior but it was not implemented. Thanks for jumping in!

**Comment by Calinou** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
