### ISSUE TITLE
ERROR: .NET: Failed to load project assembly.

### ISSUE THREAD

**Issue by Rehrok** [godotengine/godot#84765]
### Godot version

v4.2.beta5.mono.official [4c96e9676]

### System information

Godot v4.2.beta5.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Laptop GPU (NVIDIA; 31.0.15.2756) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

I can no longer build the project assembly inside the editor.  Inspector fields don't update.  The problem started yesterday and does not seem to be tied to code changes, since I have tested it with previous, stable commits of my project.  The problem persists across multiple versions of the editor (include the latest stable version).

The console output related to the error is here:
```
Godot Engine v4.2.beta5.mono.official.4c96e9676 - https://godotengine.org
OpenGL API 3.3.0 NVIDIA 527.56 - Compatibility - Using Device: NVIDIA - NVIDIA GeForce RTX 3080 Laptop GPU

Editing project: C:/Work/Godot/Terra
Godot Engine v4.2.beta5.mono.official.4c96e9676 - https://godotengine.org
Vulkan API 1.3.224 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3080 Laptop GPU

System.TypeLoadException: Could not load type 'Terra.Actor' from assembly 'Terra, Version=1.0.0.0, Culture=neutral, Pub.   at System.Reflection.RuntimeAssembly.GetTypeCore(QCallAssembly assembly, String typeName, ReadOnlySpan`1 nestedTypeN)   at System.Reflection.RuntimeAssembly.GetTypeCore(String typeName, ReadOnlySpan`1 nestedTypeNames, Boolean throwOnErr)   at System.Reflection.TypeNameParser.GetTypeFromDefaultAssemblies(String typeName, ReadOnlySpan`1 nestedTypeNames)
   at System.Reflection.TypeNameParser.GetType(String typeName, ReadOnlySpan`1 nestedTypeNames, String assemblyNameIfAn)   at System.Reflection.TypeNameParser.Parse()
   at System.Reflection.TypeNameParser.GetTypeHelper(Char* pTypeName, RuntimeAssembly requestingAssembly, Boolean throw)   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCt)   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, I)   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken)   at Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(Assembly assembly) in /root/godot/modules/mono/glue/Godo2   at GodotPlugins.Main.LoadProjectAssembly(Char* nAssemblyPath, godot_string* outLoadedAssemblyPath) in /root/godot/mo4ERROR: Script does not inherit from Node: res://scripts/nodes/GraphicsSettings.cs.
   at: (editor/editor_autoload_settings.cpp:424)
WARNING: Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings.     at: _editor_init (modules/gltf/register_types.cpp:63)
ERROR: Invalid node name for submenu, the following characters are not allowed:
. : @ / " %
   at: (scene/gui/popup_menu.cpp:1490)
ERROR: Resource file not found: res://rogue_tiles_15x15_512.png (expected type: )
   at: (core/io/resource_loader.cpp:279)
Unloading assembly load context...
Assembly load context unloaded successfully.
System.TypeLoadException: Could not load type 'Terra.Actor' from assembly 'Terra, Version=1.0.0.0, Culture=neutral, Pub.   at System.Reflection.RuntimeAssembly.<GetTypeCore>g____PInvoke|26_0(QCallAssembly __assembly_native, Byte* __typeNam)   at System.Reflection.RuntimeAssembly.GetTypeCore(QCallAssembly assembly, String typeName, ReadOnlySpan`1 nestedTypeN)   at System.Reflection.RuntimeAssembly.GetTypeCore(String typeName, ReadOnlySpan`1 nestedTypeNames, Boolean throwOnErr)   at System.Reflection.TypeNameParser.GetTypeFromDefaultAssemblies(String typeName, ReadOnlySpan`1 nestedTypeNames)
   at System.Reflection.TypeNameParser.GetType(String typeName, ReadOnlySpan`1 nestedTypeNames, String assemblyNameIfAn)   at System.Reflection.TypeNameParser.NamespaceTypeName.ResolveType(TypeNameParser& parser, String containingAssemblyI)   at System.Reflection.TypeNameParser.Parse()
   at System.Reflection.TypeNameParser.GetTypeHelper(Char* pTypeName, RuntimeAssembly requestingAssembly, Boolean throw)   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCt)   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, I)   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken)   at Godot.Bridge.ScriptManagerBridge.LookupScriptsInAssembly(Assembly assembly) in /root/godot/modules/mono/glue/Godo2   at GodotPlugins.Main.LoadProjectAssembly(Char* nAssemblyPath, godot_string* outLoadedAssemblyPath) in /root/godot/mo4ERROR: .NET: Failed to load project assembly.
   at: reload_project_assemblies (modules/mono/mono_gd/gd_mono.cpp:538)
Unloading assembly load context...
Assembly load context unloaded successfully.
```

The C# project builds successfully in Visual Studio 2022.  `Terra.Actor` is pure struct with no interesting properties.  `GraphicsSettings` does inherit from `Node`.  The problem may have started when I tried to rename that file while it was included in the auto load list.

### Steps to reproduce

The error occurs immediately on project load.  Hopefully someone familiar with the error can suggest a solution, without requiring a  project (but I'm creating one regardless).

### Minimal reproduction project

I'll start creating a minimal reproduction project now.

**Comment by ArtyIF** [comment]
Everything works fine for me, except for the "Invalid node name for submenu" error and the Project/Tools/C#/Generate Solution entry missing.

**Comment by Rehrok** [comment]
I uninstalled/re-installed all the dot net requirements, rolled back to a prior stable point, and switched to v4.1.3.  One of those actions fixed the issue.  This was alarming and I completely blocked me for multiple days, but I don't want to try and recreate the issue now that it works on my machine.  The issue doesn't seem to be very common, since I couldn't find anyone else with the issue.  My only guess is that it is tied to the auto load script.

**Comment by dninemfive** [comment]
i see that this issue is closed, but i'm getting this error too. Should i make a new issue for it, or should this one be reopened?

Regardless, i looked at the source code, and i believe the error is thrown by `GDMono::_try_load_project_assembly()` ([snippet](https://github.com/godotengine/godot/blob/master/modules/mono/mono_gd/gd_mono.cpp#L449-L462)) when `GDMono::_load_project_assembly()` ([snippet](https://github.com/godotengine/godot/blob/master/modules/mono/mono_gd/gd_mono.cpp#L476-L496)) is `false`. i'm not great with C++, but it looks like it could fail either if the assembly path does not exist or if `plugin_callbacks.LoadProjectAssemblyCallback()` returns false. i wasn't able to track down where exactly `LoadProjectAssemblyCallback()` is defined so i can't speculate as to how that could fail.

It seems to be related to me futzing with assembly names, since i've renamed the project a few times since creating the Godot project. i'll try to verify whether the assembly is named properly and report back if that fixes it.

**Comment by Chaosed0** [comment]
It seems that if you open Godot through the terminal (whether you use the console version or simply call `godot --path <path> --editor` through the command line), you will obtain access to the actual exception which occurs when loading the assembly. In my case, it helped me figure out that I was opening a project which required the Spine version of Godot.

I know this is not relevant to the issue, but as this remains the top Google search result for "failed to load project assembly", I figured it would be helpful to post here.

**Comment by ScatteredComet** [comment]
I've just encountered this issue and I believe for me it was due to having another godot project within my project.

I have 2 submodules in my main game's repo (one of them is another godot project)

On my main PC usually when I boot the parent directory godot says something like "Detected another project.godot at res://addons/name-of-submodule. The folder will be ignored."

But when i git cloned the parent directory to my new PC (and then git submodule update --init --recursive), godot would refuse to open (and say "failed to load project assembly" when running --verbose)

So what I did was remove the submodule files locally, open the godot project, then restore the submodule files whilst godot was open. Now godot seems to be perfectly happy opening / closing the project.

So I guess that there is some check that's done on startup that can fail if there are mutliple project.godot's present? And presumably it must be dependent on something within the .godot folder (as that isn't committed to my git repo?)

If people are interested I can try to make a MRP

**Comment by Skyppid** [comment]
I experience this issue at the moment. It's hella frustrating.

All I can recall I did before it failed was fiddling around with the .csproj file. For some scenes I have the script in my Scenes folder which wasn't (at least I didn't see it) showing up in Rider. So I added it first with a `<Compile Include=...` entry. This led to errors as it added the same files multiple times. So I used `<Folder Include=...>` instead. Rider accepted it. Builds in Rider work. I eventually reverted it as I realized Rider finds it even without that.

Nonetheless ever since Godot fails with these errors in Output:

>   ERROR: Failed to create an autoload, script 'res://Code/Core/Globals/GlobalSignals.cs' is not compiling.
>   ERROR: Failed to create an autoload, script 'res://Code/Core/Globals/GlobalStateManager.cs' is not compiling.
> --- GDScript language server started on port 6005 ---
>   ERROR: modules/mono/mono_gd/gd_mono.cpp:801 - .NET: Failed to load project assembly.
>   ERROR: modules/mono/mono_gd/gd_mono.cpp:801 - .NET: Failed to load project assembly.
>   ERROR: modules/mono/mono_gd/gd_mono.cpp:801 - .NET: Failed to load project assembly.
>   ERROR: modules/mono/mono_gd/gd_mono.cpp:775 - .NET: Giving up on assembly reloading. Please restart the editor if unloading was failing.

I don't get it. I reverted everything, Rider doesn't complain. I tried deleting the mono folder and a lot more and nothing works. It keeps on failing. My whole project is bricked now.


I really love Godot and try to like it, but ever since I started my project I spent 80% of the time fighting against the way it works with C#. If this continues I guess I have to go back to Unity :(

**Comment by Suwit2** [comment]
Note: Apologies in advance for any language awkwardness—English is not my native language, so I had Gemini Flash translate this for me.

[FIX] "Failed to create an autoload, script 'res://...' is not compiling" in Godot 4.x (Mono/C#)
The Problem:
When you delete the .godot folder, switch engine versions, or pull a fresh repo, Godot throws is not compiling for C# Autoloads on startup. This happens because the C++ Editor checks the Autoload registry before MSBuild finishes generating and reloading the C# assembly into memory.

The 100% Working Fix:

Clear Autoloads: Open project.godot in a text editor and temporarily remove all entries under [autoload], then save.

Open Godot Editor: The errors will disappear completely.

Build Assembly: Click the Hammer icon (Build) in the top-right corner to let MSBuild generate fresh C# .dll assemblies.

Reload Engine: Go to Project > Reload Current Project to force the C++ Core to reload the new assemblies into RAM.

Re-add Autoloads: Go to Project Settings > Globals and re-add your C# scripts. Everything will register smoothly without errors!

good luck


try to write  by myself 
1. remove all  autoload    in project> Project Setting > Global s
2. save  and rebuild   (don't forget it)
3.  menu : Project> Reload Current Project 
4.  add  all your  script to autoload again  .
