### ISSUE TITLE
Edit Menu's Skeleton's Sub Menu closes too soon

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#8487]
**Operating system or device - Godot version:**
2.1.2

**Issue description:**
The unhover state actually works fine when you don't click on it.

However, if you do click on it, it seems like the height changes (decreases) and the unhover state activates just a tad bit too soon:

https://i.gyazo.com/b231efec6edd7f1c8225d69840d881fb.mp4

e: This is why sometimes when you go to edit->skeletons->make bones really fast the menu poofs lol

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
