### ISSUE TITLE
WorkerThreadPool leaks memory and occasionally crashes

### ISSUE THREAD

**Issue by j-zeppenfeld** [godotengine/godot#84888]
### Godot version

v4.2.beta6.official [64150060f]

### System information

Godot v4.2.beta6 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA RTX A2000 Laptop GPU (NVIDIA; 31.0.15.2737) - 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 Threads)

### Issue description

Adding tasks to the WorkerThreadPool leaks memory and occasionally crashes.

While the memory leak is very reproducible, the crash only occurs very sporadically.

Running the same tasks using dedicated threads or a custom thread pool does not leak memory.

This is not a regression, the same behavior occurs all the way back to v4.0.2.stable.official [7a0977ce2] and presumably earlier.

### Steps to reproduce

```gdscript
extends Node2D

func work(data: Array):
	pass

func _process(delta: float):
	if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
		var data = []
		data.resize(1000)
		data.fill(0)
		WorkerThreadPool.add_task(work.bind(data))
```
Run a scene containing a node with this script, view the static memory monitor in the Debugger pane, then click the mouse in the game window and watch the memory usage ramp up.

### Minimal reproduction project

Trivial to reproduce without a dedicated project.

**Comment by akien-mga** [comment]
Confirmed in 4.2-beta6 on Linux.

**Comment by bitsawer** [comment]
You have to wait for WorkerThreadPool tasks at some point so that WorkerThreadPool has a chance to clean up any used resources. In this case, use `WorkerThreadPool.wait_for_task_completion()`. This seems to work without leaks:

```gdscript
extends Node2D

func work(data: Array):
    pass

func _process(delta: float):
    if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
        var data = []
        data.resize(1000)
        data.fill(0)
        var task = WorkerThreadPool.add_task(work.bind(data))
        WorkerThreadPool.wait_for_task_completion(task)

```

However, the documentation doesn't directly mention this, so I'll add a documentation tag. Both `WorkerThreadPool.add_group_task()` and `WorkerThreadPool.add_task()` documentation should mention that every task should be waited at some point so that any allocated resources can be cleaned up.

I can't repro the crashing, which might be worth making a separate issue if you can repro it. Maybe you have to wait a lot longer for operating system thread, mutex etc. resources to reach their process limit or something like that? The limits tend to be quite high, so in normal use WorkerThreadPool should not crash very easily.

**Comment by jsjtxietian** [comment]
Tested using Godot v4.2.beta (64150060f) - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads), it didn't crash too but the memory leak is obvious. I guess the crash may related to OS or something else.

**Comment by BrianBHuynh** [comment]
Asking for clarification here, by "every task should be waited at some point" does the task of waiting (WorkerThreadPool.wait_for_task_completion()) itself clear up the resources, or would waiting enough time (i.e not a wait function) make the threads clearup resources ? I'm wondering because having a function which pauses the thread that calls this method seems to negate the benefit of using that thread if the following code does not depend on the task being completed (i.e saving a file)
