### ISSUE TITLE
RefCounted bound by Callable do not unreference when multithreading using WorkerThreadPool

### ISSUE THREAD

**Issue by Motioneer** [godotengine/godot#84899]
### Godot version

v4.1.3.stable.custom_build [fc7920185]

### System information

Godot v4.1.3.stable (fc7920185) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 Ti (NVIDIA; 31.0.15.2756) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Hello!

I dug down in an issue hanging my game and I suspect this is not intended behaviour.
All code from the minimal reproduction project:
### Behaviour
The Issue occurs when a WorkerThreadPool task has a bound RefCounted parameter:
```gdscript
var ref_counted := RefCounted.new()

func _process(delta: float) -> void:
	prints("References:", ref_counted.get_reference_count())
	var id = WorkerThreadPool.add_task(_task.bind(ref_counted))

func _task(ref_counted: RefCounted) -> void:
	pass
```

**The reference count of that parameter is increased, but never decreased.**

Output:
```shell
References: 1
References: 2
References: 3
References: 4
References: 5
References: 6
References: 7
References: 8
References: 9
References: 10
```

I suspect this is also what happens in regular threads, as described here: 
#82513 

### Significance

This is a problem if you run a lot of WorkerThreadPool tasks or pass around a lot of objects. 
Any RefCounted created for a task and then bound, will persist in memory alongside, apparently, the task itself as a HashMapElement. 

<img width="663" alt="leaking_objects" src="https://github.com/godotengine/godot/assets/10763179/94062728-df49-49a5-ade8-57ff6854fca2">

Apart from the memory leak itself being an issue, in the context of WorkerThreadPool it could hang the application.

I couldn't verify this, but if the task is kept in, what I presume a WorkerThreadPool lookup hashmap, the hashmap will grow to a problematic size. Sadly my C++ skills have reached their limit and I am just guessing at this point.

### Solution
A workaround to this is to manually unreference the RefCounted parameter. 
BUT if this is a bug, and gets fixed, this workaround will create unexpected behaviour!
```gdscript
var ref_counted := RefCounted.new()

func _process(delta: float) -> void:
	prints("References:", ref_counted.get_reference_count())
	var id = WorkerThreadPool.add_task(_task.bind(ref_counted))

func _task(ref_counted: RefCounted) -> void:
	# Enable this manual unreferencing to stop the leaking.
	ref_counted.unreference()
```
Output:
```shell
References: 1
References: 1
References: 1
References: 1
```

### Steps to reproduce

See both scenes in the attached project, for reference and object leaking.
Or execute the code above.

### Minimal reproduction project

[reference_and_object_leaking.zip](https://github.com/godotengine/godot/files/13351725/ref_sample.zip)

**Comment by Motioneer** [comment]
I think #84888 might also be caused by this.

**Comment by synalice** [comment]
Interestingly enough, in your scene _"leaking_object.tscn"_ adding `ref_counted.unreference()` doesn't actually solve the issue. The number of references grows by one each time either way.

```gdscript
extends Node2D

 
func _process(delta: float) -> void:
	var ref_counted := RefCounted.new()
	
	prints("References before task added:", ref_counted.get_reference_count())

	var id = WorkerThreadPool.add_task(
			func():
				ref_counted
				ref_counted.unreference()
	)

	prints("References after task added:", ref_counted.get_reference_count())
```

**Comment by Motioneer** [comment]
@synalice are you sure you have actually switched scenes and run the current scene? Because the count in that scene should not increase, only leak memory.

**Comment by synalice** [comment]
> @synalice are you sure you have switched scenes and run the current scene? Because the count in that scene should not increase, only the memory should leak, since we are creating a new object each frame.

Yep, I did. I was accidentally pressing F5 and not F6 to run a scene. Please delete your comment, this is too embarrassing (；′⌒`)

**Comment by Motioneer** [comment]
Right, I'm not a C++ programmer, but is it possible that WorkerThreadPool dosn't actually ever remove finished tasks from the hashmap, except when wait_for_task_completion is called on the task id?

'worker_thread_pool.cpp'  writes the tasks with its ids as key to the  'tasks' hashmap:

```cpp
WorkerThreadPool::TaskID WorkerThreadPool::_add_task(const Callable &p_callable, void (*p_func)(void *), void *p_userdata, BaseTemplateUserdata *p_template_userdata, bool p_high_priority, const String &p_description) {
   ...
	tasks.insert(id, task);
```
But the task only gets erased here, which is only ever called if done so explicitly by the user:
```cpp
Error WorkerThreadPool::wait_for_task_completion(TaskID p_task_id) {
   ...
       tasks.erase(p_task_id);
```

If I do so in the sample project.... the references don't accumulate any more.

```GDScript
var ref_counted := RefCounted.new()

func _process(delta: float) -> void:
	
	prints("References:", ref_counted.get_reference_count())

	var id = WorkerThreadPool.add_task(_task.bind(ref_counted))
	WorkerThreadPool.wait_for_task_completion(id)

func _task(ref_counted: RefCounted) -> void:
	pass
```

Can someone confirm this?

**Comment by Motioneer** [comment]
From the looks of it, this also messes with is_task_completed, since it looks up the task id in the hashmap.

This code prints 'true':
```GDScript
var ref_counted := RefCounted.new()
var id: int

func _ready()-> void:
	id = WorkerThreadPool.add_task(_task.bind(ref_counted))

func _process(delta):
	prints(WorkerThreadPool.is_task_completed(id)) # TRUE

func _task(ref_counted: RefCounted) -> void:
	pass
```
Adding is_task_completed now prints 'false':

```GDScript
var ref_counted := RefCounted.new()
var id: int

func _ready()-> void:
	id = WorkerThreadPool.add_task(_task.bind(ref_counted))
	WorkerThreadPool.wait_for_task_completion(id)

func _process(delta):
	prints(WorkerThreadPool.is_task_completed(id)) # FALSE

func _task(ref_counted: RefCounted) -> void:
	pass
```

**Comment by j-zeppenfeld** [comment]
Sounds like the same restrictions as for threads apply, namely:

[Thread:](https://docs.godotengine.org/en/stable/classes/class_thread.html)
> Warning:
>To ensure proper cleanup without crashes or deadlocks, when a Thread's reference count reaches zero and it is therefore destroyed, the following conditions must be met:
>* It must not have any [Mutex](https://docs.godotengine.org/en/stable/classes/class_mutex.html#class-mutex) objects locked.
>* It must not be waiting on any [Semaphore](https://docs.godotengine.org/en/stable/classes/class_semaphore.html#class-semaphore) objects.
>* [wait_to_finish](https://docs.godotengine.org/en/stable/classes/class_thread.html#class-thread-method-wait-to-finish) should have been called on it.

If this is intended to apply to WorkerThreadPool as well it would be rather unfortunate, since that would require the user to track and wait for task ids, which would pretty much eliminate the ease of use of WorkerThreadPool (fire and forget).

**Comment by bitsawer** [comment]
Seems to be similar to https://github.com/godotengine/godot/issues/84888, which was linked previously. And yes, every created WorkerThreadPool task must be waited at some point so that any task-specific allocated resources can be freed: https://github.com/godotengine/godot/issues/84888#issuecomment-1811706807. So this is a documentation issue. 

As for having to manually track and wait task id's, in some situations it might be possible for WorkerThreadPool to automatically free these resources when the task callback function has returned, but that would need a new API call and it would be easy to accidentally run into some thread race conditions.

**Comment by synalice** [comment]
> And yes, every created WorkerThreadPool task must be waited at some point so that any task-specific allocated resources can be freed

Why would you need to call `WorkerThreadPool.wait_for_task_completion` manually at all? I understand this now an API _"problem"_, but why was it created like this at all? What are the situations where you **don't** immediately call `WorkerThreadPool.wait_for_task_completion` after calling `WorkerThreadPool.add_task`?

**Comment by j-zeppenfeld** [comment]
> What are the situations where you **don't** immediately call `WorkerThreadPool.wait_for_task_completion` after calling `WorkerThreadPool.add_task`?

I think this may be one of the reasons people don't think threads improve performance. If you launch a thread and then immediately block until the thread completes, you may as well do the work of the thread directly, without incurring all the overhead to launch a thread.

In order to improve performance the thread must be allowed to run in the background. This requires storing the task (or thread) id and periodically checking if it has completed using is_task_completed (or is_alive for threads). As far as I know there is no signal available for this, so it must be polled.

Only once is_task_completed returns true should wait_for_task_completion be called in order to avoid blocking the main thread.

I would have hoped that WorkerThreadPool handles this automatically (so that it ["can be used for simple multithreading"](https://docs.godotengine.org/en/stable/classes/class_workerthreadpool.html#description), unfortunately this does not appear to be the case.

**Comment by Motioneer** [comment]
> I would have hoped that WorkerThreadPool handles this automatically

Would it make senese to add a flag for that to happen automatically?

Something like:
````GDScript
add_task ( Callable action, bool high_priority=false, String description="", bool free_after_completion=false )
````

**Comment by j-zeppenfeld** [comment]
> Would it make senese to add a flag for that to happen automatically?
I would really expect this to happen automatically. is_task_completed and wait_for_task_completion could simply return true/return immediately if the task has already been cleaned up (i.e., the task id is no longer found in the tasks hashmap).

**Comment by synalice** [comment]
> Would it make senese to add a flag for that to happen automatically?

Not the _flag hell_, please. This behavior needs to be default for `WorkerThreadPool` to be easy to use as it is intended to be.

I think there is even a way to do it without breaking backwards compatibility.

> is_task_completed and wait_for_task_completion could simply return true/return immediately if the task has already been cleaned up (i.e., the task id is no longer found in the tasks hashmap).

Yes, this.

**Comment by bitsawer** [comment]
>What are the situations where you don't immediately call WorkerThreadPool.wait_for_task_completion after calling WorkerThreadPool.add_task?

There are plenty of scenarios like that, many used inside Godot itself. For example writing Vulkan pipeline cache into a file, scene culling, navigation mesh generation, resource loading etc. Probably more. One feature of manual task id management is to maximize parallelism when managing concurrent tasks and this is best done manually by the programmer who writes and understands the code. 

The problem with not manually managing task id lifetimes also becomes apparent for example when the application is closing or if the calling node is deleted from the scene tree while running a task. Without waiting, the threaded code will become very difficult to manage, because there is no longer any reliable way to sync the task state safely. For example, how will the task thread communicate its results to a node or object that might have been already freed? The waiting is there to also guard against these problems so a programmer can choose how to react to these situations.

If you think there is a way to impove the API, it's always to make a proposal and see if the idea is workable: https://github.com/godotengine/godot-proposals/issues.
