### ISSUE TITLE
GDNative reference passing doesn't seem to work

### ISSUE THREAD

**Issue by Zylann** [godotengine/godot#8490]
Godot master, Windows 10 64 bits

Passing a reference to a GDNative class to the method of another GDNative class doesn't work.

I created two C++ classes in a GDNative library, with the following setup, simplified:

```cpp
class A : public Reference {

	void _init() {
		m_seed = 131183;
	}

	int get_seed() {
		return m_seed;
	}

	int m_seed;
};

class B : public Reference {

	void set_a(A * a) {
		a->reference();
		m_a = a;
	}

	A * m_a;
};
```

And used in GDScript the following way:

```gdscript
func _ready():
	var a = A.new()
	var b = B.new()
	b.set_a(a)
```

Problem: when the reference to A comes into B, it points to some kind of "ghost" instance where `seed` is 0, not 131183. In my actual project I also have a pointer in that class which makes it crash because it's garbage.

**Comment by sheepandshepherd** [comment]
I ported your example to D to check those bindings, but didn't have any issues with References. The A pointer and seed were correct in both GDScript and `set_a`, so this bug may be specific to the C++ bindings or fixed since then.

Incidentally, this helped me find errors in the D bindings before I got it to work, so maybe something similar is broken in C++: I had an incorrect type cast resulting in `a`'s Reference "owner" being passed to set_a instead of the A itself. (Variant always stores the owner, not the GDNative script's pointer - I can't tell if C++ bindings' [_arg_cast](https://github.com/GodotNativeTools/cpp_bindings/blob/master/include/core/Godot.hpp#L74) accounts for that.)

If you update this to the newer C++ bindings (with inheritance changed to `class A : public GodotScript<Reference>`), could you print the pointers of `a` and `a->owner` in both A::_init and B::set_a, to make sure they're not getting mixed up?

Also, does this happen if A and B are `GodotScript<Object>` instead of `GodotScript<Reference>`?

**Comment by Zylann** [comment]
I need to try it again with the new updates

**Comment by karroffel** [comment]
@Zylann did you have a chance to check this out?

**Comment by akien-mga** [comment]
What's the status on this issue? Fixed, or to move to 3.1?

**Comment by karroffel** [comment]
This works, it's just not implemented in the C++ bindings properly

**Comment by Zylann** [comment]
It's "working" once you understand all the boilerplate to write in C^^ but that issue is initially for C++

**Comment by akien-mga** [comment]
So should this issue be moved to the C++ bindings repo?

**Comment by karroffel** [comment]
Yes, will close here and try to fix it in the bindings.
