### ISSUE TITLE
Exporter saves Particles2D as Node2D on 3.x scene file

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8494]
**Ubuntu 17.04 - Godot version: 2.1.3**

**Issue description:**
The exporter turns Particles2D into Node2D on the scene file.

It was expected to have them saved as Particles2D.

**Steps to reproduce:**
Export to 3.0 a 2.x project with particles (like the demo) and then open the tscn file with a text editor.

**Comment by akien-mga** [comment]
Yes, that's due to this line: https://github.com/godotengine/godot/blob/f9bde9ddf7e6dac8bbd365da0164be7df19dbeae/editor/editor_export_godot3.cpp#L490

Those conversions were added for features which were not implemented yet (like Particles2D) or obsolete and needing more conversion work (e.g. audio stuff). But I'm not sure that removing the line about Particles2D would fix the issue though, there might be more conversion work necessary to port 2.x particles to 3.0.

**Comment by reduz** [comment]
that line is gone, so this issue is too
