### ISSUE TITLE
in a right to left language in Godot the Ui gets reversed, and its hard to work.

### ISSUE THREAD

**Issue by theBSH** [godotengine/godot#84998]
### Godot version

4.1.2

### System information

Godot v4.1.2.stable.mono - Windows 11 22h2 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

in a right to left language (in my case Persian) the Ui gets inverted and i know it should be like that but you just cant work i will leave a screen shot so  you can see
![Screenshot 2023-11-16 042657](https://github.com/godotengine/godot/assets/118190096/76f0849d-945d-407b-b450-391c65c01f0e)

### Steps to reproduce

change the language to Persian

### Minimal reproduction project

N/A

**Comment by akien-mga** [comment]
#85000 will add an option to disable this behavior and force left-to-right UI direction.

For now in 4.1.x and 4.2 you'll have to set the locale to English (or any other LTR language) to disable this behavior.

Could you provide more info on what are the issues you have with the right-to-left UI mirroring? The screenshot isn't necessarily obvious for users who are not used to right-to-left languages.

Would you find the right-to-left UI mirroring good if everything was fully translated in Persian? Because currently the project settings shown in the screenshots are not translated, because the Persian translation is very incomplete: https://hosted.weblate.org/projects/godot-engine/-/fa/

Or would you prefer the UI following left-to-right conventions even if all the text was in Persian?

**Comment by theBSH** [comment]
this would certainly fix the issue.
as for if I would use right to left if it was fully translated, I would say no, we got so used to this layout long ago even before Godot , apps like blender steam and ... were always left to right so I just can't see myself getting used to right to left.
although not a single man can translate a whole app I am trying my best and with this fix ill certainly have more motivation.
