### ISSUE TITLE
Some GI effects (VoxelGI, LightmapGI, SDFGI, SSR) prevent 3D rendering and spam Vulkan errors if XR shaders are enabled

### ISSUE THREAD

**Issue by dreadpon** [godotengine/godot#84999]
### Godot version

v4.2.beta.custom_build [ce9901ef5]

### System information

Godot v4.2.beta (ce9901ef5) - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

When enabling `xr/shaders/enabled` in `ProjectSettings` some GI/lightning effects cause 3D rendering artifacts and severe error spam. I tested most of the available effects (VoxelGI, LightmapGI, Reflection Probe, SDFGI, SSIL, SSR, SSAO) and 4 of them (VoxelGI, LightmapGI, SDFGI, SSR) cause these issues.

Tested on Godot 4.2.beta 5 and v4.2.beta.custom_build [ce9901ef5] on 2 different machines (Windows 10 PC + Windows 11 Laptop)

Issues below might be related but I'm not 100% sure:
- https://github.com/godotengine/godot/issues/73403
- https://github.com/godotengine/godot/issues/84841

I also used a custom build as I thought maybe this PR would solve the issue
- https://github.com/godotengine/godot/pull/84883

It didn't (and seems to be about a slightly different problem)

Below is the comparison between problematic effects

### Base scene, no effects (sky + Directional light)
![image](https://github.com/godotengine/godot/assets/35217125/eff88047-aff5-46cb-ada3-31c57885d842)

### VoxelGI
![image](https://github.com/godotengine/godot/assets/35217125/8a8e2ab8-ae1f-48ce-8696-2158132c1b6d)
No 3D output, just the environment. Errors spammed:
```
ERROR: Mismatch fragment shader output mask (0) and framebuffer color output mask (3) when binding both in render pipeline.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:6143)
ERROR: Condition "pipeline.is_null()" is true. Returning: RID()
	at: _generate_version (servers/rendering/renderer_rd/pipeline_cache_rd.cpp:61)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
	at:	(drivers/vulkan/rendering_device_vulkan.cpp:7443)
ERROR: No render pipeline was set before attempting to draw.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:7460)
```

### LightmapGI
![image](https://github.com/godotengine/godot/assets/35217125/58ada3c0-d3ee-43bd-b32d-0279422adeba)
Partial render, black meshes. Errors spammed:
```
ERROR: Mismatch fragment shader output mask (0) and framebuffer color output mask (1) when binding both in render pipeline.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:6143)
ERROR: Condition "pipeline.is_null()" is true. Returning: RID()
	at: _generate_version (servers/rendering/renderer_rd/pipeline_cache_rd.cpp:61)
ERROR: The vertex format used to create the pipeline does not match the vertex format bound.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:7467)
```

### SDFGI
![image](https://github.com/godotengine/godot/assets/35217125/3c76b8ac-4a38-44e4-a9df-8f53719acebd)
Render _seems_ fine. Errors spammed:
```
ERROR: Desired set (1) not used by shader.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:5437)
ERROR: Condition "rid.is_null()" is true. Returning: rid
	at: _allocate_from_uniforms (./servers/rendering/renderer_rd/uniform_set_cache_rd.h:129)
ERROR: Parameter "uniform_set" is null.
	at: draw_list_bind_uniform_set (drivers/vulkan/rendering_device_vulkan.cpp:7336)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
	at: (drivers/vulkan/rendering_device_vulkan.cpp:7443)
```

### SSR
![image](https://github.com/godotengine/godot/assets/35217125/473d571f-5bfe-40d6-92f2-35b55bba4787)
Partial render, black meshes. Errors spammed:
```
ERROR: Mismatch fragment shader output mask (0) and framebuffer color output mask (3) when binding both in render pipeline.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:6143)
ERROR: Condition "pipeline.is_null()" is true. Returning: RID()
	at: _generate_version (servers/rendering/renderer_rd/pipeline_cache_rd.cpp:61)
ERROR: This render pipeline requires (0) bytes of push constant data, supplied: (16)
	at: (drivers/vulkan/rendering_device_vulkan.cpp:7443)
ERROR: No render pipeline was set before attempting to draw.
	at: (drivers/vulkan/rendering_device_vulkan.cpp:7460)
```

### Steps to reproduce

1. Download the reproduction project
2. If `xr/shaders/enabled` is disabled, enable it
3. Launch the project
4. Select any of the problematic scenes (VoxelGI, LightmapGI, SDFGI, SSR) to observe rendering artifacts and error spam in console
5. Optionally, disable `xr/shaders/enabled` and test the scenes again, with no problems this time

### Minimal reproduction project

[vulkan_xr_shader_errors.zip](https://github.com/godotengine/godot/files/13387852/vulkan_xr_shader_errors.zip)

**Comment by BastiaanOlij** [comment]
I'm out this weekend so not sure how much time I have to deep dive into this however this seems similar to an issue we worked around earlier in the week.

It is important to know that all enabling XR shaders does, is compile _extra_ variants. These extra variants are only used when stereo rendering is enabled, in normal rendering nothing should change, the same shader code should be used, the same pipeline setup. So that we're getting error all of a sudden in this area is weird.

My hypothesis is that we broke caching somehow and that we're loading the wrong variants from cache. One easy thing to try is after enabling XR shaders, delete the shader cache (`.godot/shader_cache`) and restart Godot, it should rebuild the shader cache anew with the proper variants. If things work properly after that we know it's the cache that no longer handles disabled variants correctly.

cc @clayjohn

**Comment by clayjohn** [comment]
The error indicates that this is an issue with the shader permutation, or with our shader reflection system. 

The shader is reporting an output mask of 0 (meaning there is no output) while the the framebuffer has two outputs (mask of 3). 

I don't think the issue is with the SPIRV reflection as that hasn't changed in a long time. Rough bisecting points to Dev3 which is when we introduced that shader compile groups (which aligns with this being an issue only for ADVANCED_MULTIVIEW shaders).
