### ISSUE TITLE
3.0 Shaders - Allow combining written shaders with visual ones?

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8507]
(actually written with written also xD)
This is probably more topic for a discussion, than an issue (there is no visual shaders in 3.0 yet :D)

Would it be possible to combine written shaders with visual ones (written also)? For example useful in scenario like this one:
1. Technical Artist wrote Uber Shader that is used for most of the assets in current production. It has all shading features props in this production need. (Wet Surface, Rain, Wind Effect, Under Water Effect, Normal Sharpening and such)
2. There is Enviro Texture Artist that wants shader that mixes textures in cool way and he wants to send them for production main Uber Shader that Tech Artist made.

Would that be possible? It's basically making two shaders communicate data between them.

I assume there might be technical limitations or drawbacks, but I'm not an expert :B

**Comment by bojidar-bg** [comment]
BTW, related to #146.

**Comment by n-pigeon** [comment]
Yes, I think #146 is very related.

**Comment by Chaosus** [comment]
Partially this issue was fixed by introduced Expression nodes in 3.2. The missing parts are global declarations such as functions, constants and varyings..

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
