### ISSUE TITLE
HasMultiplayerPeer is always true in Godot C#

### ISSUE THREAD

**Issue by MartSchilt** [godotengine/godot#85131]
### Godot version

4.1.3.stable

### System information

Godot v4.1.3.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 SUPER (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Using C# with Godot 4.1.3 I get the following:
I setup a peer-to-peer connection using Godot's 'Multiplayer' class (MultiplayerAPI) and call the method HasPeers(). This should return true if there are any peers connected. Right now this always returns true.

I only want this to return true if there are peers connected (so not only yourself).
I fixed this locally in my code by changing it to "Multiplayer.GetPeers().Length > 0"

### Steps to reproduce

Create a ENetMultiplayerPeer and then call Multiplayer.HasPeers()

### Minimal reproduction project

N/A

**Comment by ShlomiRex** [comment]
`ENetMultiplayerPeer` doesn't have functions `HasPeers()` or `GetPeers()` or is it just me?
https://docs.godotengine.org/en/stable/classes/class_enetmultiplayerpeer.html

**Comment by AThousandShips** [comment]
`MultiplayerAPI` has `get_peers` and `has_multiplayer_peer`

**Comment by AThousandShips** [comment]
Please provide a minimal reproduction project:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available. 

And please make sure it's specific to C#

**Comment by MartSchilt** [comment]
[HasMultiplayerPeer Bug.zip](https://github.com/godotengine/godot/files/13418837/HasMultiplayerPeer.Bug.zip)

**Comment by AThousandShips** [comment]
This is because there's always a default `OfflineMultiplayerPeer`, see [here](https://docs.godotengine.org/en/stable/classes/class_offlinemultiplayerpeer.html#class-offlinemultiplayerpeer)

**Comment by MartSchilt** [comment]
But why doesn't it then show up in the list of peers from GetPeers?

Also the documentation states that "It mimics the behavior of a server with no peers connected" meaning that there are no peers, so I would expect HasMultiplayerPeers to return false

**Comment by AThousandShips** [comment]
It isn't `has_multiplayer_peers` it's `has_multiplayer_peer`, it isn't about connected peers, but the peer on your end

**Comment by MartSchilt** [comment]
Well if that is the desired functionality, I will close this issue
