### ISSUE TITLE
AnimatedSprite2D's animation does not play properly if the previous set animation wasn't set to looping

### ISSUE THREAD

**Issue by inhalt120g** [godotengine/godot#85203]
### Godot version

v4.1.3.stable.official [f06b6836a]

### System information

Godot v4.1.3.stable - macOS 14.1.1 - Vulkan (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

Animated sprite's animation stops playing

### Steps to reproduce

To reproduce it, launch the attached project. The animation will stop playing after the first AnimationPlayer's loop.

Here is how the AnimationPlayer is set:
![image](https://github.com/godotengine/godot/assets/106015575/92709783-dc3d-43e3-b51a-5b50f7adc616)
The first keyframe is pointing to a looping animation of a AnimatedSprite2D, the other keyframe is pointing to a non looping animation of the same AnimatedSprite2D. This sequence of both animations is meant to repeat. If you launch the project, it will play only once and then stop even when the first (looping) animation is meant to play.

If both animations in the AnimatedSprite2D are set to loop, the animation playing does not break.

### Minimal reproduction project

[engage bug 02.zip](https://github.com/godotengine/godot/files/13433221/engage.bug.02.zip)

**Comment by kleonc** [comment]
This is expected behavior / not a bug. Changing the value of `AnimatedSprite2D.animation` doesn't change the playing state of the AnimatedSprite2D.

What happens in the provided MRP is:
1. The AnimatedSprite2D autoplays a looped animation. Hence it starts as playing.
2. After `3.5` seconds its `animation` is changed to a non-looped animation with `1.0` second duration (5 frames at 5 FPS with no non-default per frame durations).
3. Hence at `4.5` seconds into the animation the AnimatedSprite2D finishes playing its assigned non-looped animation (its `animation` is still set to the non-looped animation but it's no longer playing).
4. At `5.0` seconds the AnimatedSprite2D 's `animation` is changed back to the looped one animation. But AnimatedSprite2D remains stopped because changing `animation` doesn't affect the playing state.

![Godot_v4 1 3-stable_win64_eogYNdfbAW](https://github.com/godotengine/godot/assets/9283098/888f6895-2a2d-4746-8eb1-f4626eafb2a7)


This could be mentioned in the docs of `AnimatedSprite2D.animation`.

**Comment by inhalt120g** [comment]
"changing animation doesn't affect the playing state" can't be true, because obviously the non-looped animation did just that (it affected the playing state). If what you're saying is true, than the non looping animation from 3.5 to would be looping (since it'd just inherit the playing state from the previous animation).

**Comment by kleonc** [comment]
>"changing animation doesn't affect the playing state" can't be true, because obviously the non-looped animation did just that (it affected the playing state). If what you're saying is true, than the non looping animation set to start from 3.5 to 5 would be looping (since it'd just inherit the playing state from the previous animation).

There's some misunderstanding caused by me being not super precise / fully true. By _"playing state"_ I meant the value of `playing` boolean, which in GDScript is obtainable with `AnimatedSprite2D.is_playing()`. _"Playing state"_ is indeed not the best term to refer to it, my bad.
https://github.com/godotengine/godot/blob/fa4a65387ea41506ecc519fc61a06da110dce51c/scene/2d/animated_sprite_2d.h#L43

My claim also wasn't super precise because `AnimatedSprite2D::set_animation` can change the value of `playing` boolean. However, only in cases when the passed new animation is invalid (e.g. such animation doesn't exist in the SpriteFrames resource assigned to the AnimatedSprite2D), in such cases it will call `AnimatedSprite2D::stop()` which will result in setting `playing = false`.

So what I've said is true assuming that _"playing state"_ means _"the value of `is_playing()`"_ and that you're setting `AnimatedSprite2D.animation` to a valid animation. That's what I meant, a little bad wording by me. Hope now I'm clear.

To further clarify: setting `AnimatedSprite2D.animation` is a separate thing from the animation being processed. So e.g. by saying _"setting `AnimatedSprite2D.animation` doesn't change the value of `playing` boolean"_ I'm not saying anything about what will happen later (during animation processing).

**Comment by inhalt120g** [comment]
Then how do you explain this: in a scene with two animated sprites, I run the same scene three times. I don't change anything in the scene, just stop it and run it again. The animations are the same, the looping settings are the same.

So it's the same scene run three times. The sprites stop looping every time after different amount of loops.
00:00 - 00:11 The first time, they stop looping after 4 loops.
00:15 - 00:22 The second time they stop looping after 2 loops
00:30 - 00:32: the third time they stop looping after one loop

[engage bug 02.zip](https://github.com/godotengine/godot/files/13471602/engage.bug.02.zip)

And here is the video:
https://archive.org/download/ShowFlowFleetingWorld/画面収録%202023-11-27%2016.12.49.mov
You can see in the video that I'm not even touching any settings. I even went and right clicked on the spritesheets of each AnimatedSprite2D and made sure they're unique (and even recreated the Animation player from scratch for each of them) just in case. But it still behaves like that.

**Comment by kleonc** [comment]
> Then how do you explain this: (...)

The processing happens in steps, it's not continous. Meaning when you have a keyframes at timestamps: `0.0`, `1.0` and the looped animation has `2.0` duration, it doesn't mean that the animation parts from `0.0` to `1.0` and from `1.0` to `2.0` will each last exactly `1.0` seconds.
(In your previous example when it was `1.5` vs `1.0` seconds it wasn't as process-frame-time dependent as it's with this `1.0` vs `1.0` example.)

You could e.g. attach such script to your `green animation` node to observe that the AnimatedSprite2D's animations are being played for **approx** 1 second:
```gdscript
extends AnimationPlayer

@onready var animated_sprite: AnimatedSprite2D = get_parent()

func _ready() -> void:
	for s: Signal in [
		animated_sprite.animation_finished,
		animated_sprite.animation_looped,
		animated_sprite.animation_changed,
	]:
		s.connect(func():
			print("[%5d] %s: %s" % [
				Engine.get_process_frames(),
				animated_sprite.name,
				s.get_name()
			]))

const EPS := 0.002
func _process(delta: float) -> void:
	var pos := current_animation_position
	var close_enough := false
	for t in [0.0, 1.0, 2.0]:
		if abs(pos - t) <= EPS:
			close_enough = true
			break
	if close_enough:
		print("[%5d] current_animation_position = %.6f  %s" % [
			Engine.get_process_frames(),
			current_animation_position,
			animated_sprite.animation
		])
```

<details><summary>Here's an example output for when the green AnimatedSprite2D stopped at the 4th execution of the AnimationPlayer's animation (click to unfold):</summary>
<p>

```
[  253] green: animation_looped
[  579] green: animation_looped
[  934] green: animation_looped
[ 1292] current_animation_position = 0.998275  green looping
[ 1293] current_animation_position = 0.998925  green looping
[ 1294] current_animation_position = 0.999557  green looping
[ 1295] green: animation_looped
[ 1295] green: animation_changed
[ 1295] current_animation_position = 1.000190  green non looping
[ 1296] current_animation_position = 1.000817  green non looping
[ 1297] current_animation_position = 1.001440  green non looping
[ 2772] current_animation_position = 1.998202  green non looping
[ 2773] current_animation_position = 1.998835  green non looping
[ 2774] current_animation_position = 1.999455  green non looping
[ 2775] green: animation_changed
[ 2775] current_animation_position = 0.000095  green looping
[ 2776] current_animation_position = 0.000725  green looping
[ 2777] current_animation_position = 0.001353  green looping
[ 2778] current_animation_position = 0.001978  green looping
[ 3137] green: animation_looped
[ 3484] green: animation_looped
[ 3843] green: animation_looped
[ 4201] current_animation_position = 0.998491  green looping
[ 4202] current_animation_position = 0.999150  green looping
[ 4203] current_animation_position = 0.999772  green looping
[ 4204] green: animation_looped
[ 4204] green: animation_changed
[ 4204] current_animation_position = 1.000558  green non looping
[ 4205] current_animation_position = 1.001225  green non looping
[ 4206] current_animation_position = 1.001703  green non looping
[ 5712] current_animation_position = 1.998334  green non looping
[ 5713] current_animation_position = 1.998968  green non looping
[ 5714] current_animation_position = 1.999642  green non looping
[ 5715] green: animation_changed
[ 5715] current_animation_position = 0.000256  green looping
[ 5716] current_animation_position = 0.000971  green looping
[ 5717] current_animation_position = 0.001615  green looping
[ 6060] green: animation_looped
[ 6408] green: animation_looped
[ 6769] green: animation_looped
[ 7128] current_animation_position = 0.998493  green looping
[ 7129] current_animation_position = 0.999146  green looping
[ 7130] current_animation_position = 0.999770  green looping
[ 7131] green: animation_looped
[ 7131] green: animation_changed
[ 7131] current_animation_position = 1.000394  green non looping
[ 7132] current_animation_position = 1.001042  green non looping
[ 7133] current_animation_position = 1.001663  green non looping
[ 8644] current_animation_position = 1.998171  green non looping
[ 8645] current_animation_position = 1.998813  green non looping
[ 8646] current_animation_position = 1.999440  green non looping
[ 8647] green: animation_changed
[ 8647] current_animation_position = 0.000065  green looping
[ 8648] current_animation_position = 0.000712  green looping
[ 8649] current_animation_position = 0.001346  green looping
[ 8650] current_animation_position = 0.001987  green looping
[ 9006] green: animation_looped
[ 9339] green: animation_looped
[ 9698] green: animation_looped
[10056] current_animation_position = 0.998413  green looping
[10057] current_animation_position = 0.999063  green looping
[10058] current_animation_position = 0.999678  green looping
[10059] green: animation_looped
[10059] green: animation_changed
[10059] current_animation_position = 1.000323  green non looping
[10060] current_animation_position = 1.000972  green non looping
[10061] current_animation_position = 1.001579  green non looping
[11572] current_animation_position = 1.998485  green non looping
[11573] current_animation_position = 1.999110  green non looping
[11574] current_animation_position = 1.999715  green non looping
[11575] green: animation_finished
[11575] green: animation_changed
[11575] current_animation_position = 0.000366  green looping
[11576] current_animation_position = 0.001151  green looping
[11577] current_animation_position = 0.001621  green looping
```


</p>
</details>

As expected when `green non looping` is processed for not less than a second it finishes/stops:
| [last frame<br>`green looping`<br>was processed] | [last frame<br>`green non looping`<br>was processed] | `green non looping` processing time |
|--------|--------|--------|
| [ 1294] | [ 2774] | 1.999455 - 0.999557 < 1.0 |
| [ 4203] | [ 5714] | 1.999642 - 0.999772 < 1.0 |
| [ 7130] | [ 8646] | 1.999440 - 0.999770 < 1.0 |
| [10058] | [11574] | 1.999715 - 0.999678 > 1.0 |

---

> And here is the video:
> [https://archive.org/download/ShowFlowFleetingWorld/画面収録%202023-11-27%2016.12.49.mov](https://archive.org/download/ShowFlowFleetingWorld/%E7%94%BB%E9%9D%A2%E5%8F%8E%E9%8C%B2%202023-11-27%2016.12.49.mov)

Regarding why your red sprite kept playing in last example: you've turned off `red animation` AnimationPlayer's autoplay, hence this animation was never run. The red AnimatedSprite2D was still set to autoplay the `red looping` animation though, hence it was playing continously.

---

Not sure why do you keep trying to show it's not the issue with your animation. If you want for the AnimatedSprite2D's animations to keep playing then fix your AnimationPlayer's animation to actually play these animations (instead of only changing `AnimatedSprite2D.animation` which doesn't start the animation on its own).
![Godot_v4 2-rc2_win64_AS7kqnOGub](https://github.com/godotengine/godot/assets/9283098/1fbb952e-a1b7-4cc4-a9a3-8f155c0a1f86)

**Comment by inhalt120g** [comment]
Appreciate the reply.

> Regarding why your red sprite kept playing in last example: you've turned off red animation AnimationPlayer's autoplay, hence this animation was never run. The red AnimatedSprite2D was still set to autoplay the red looping animation though, hence it was playing continously.

After all the experimenting I must have made a mistake of packing the file an iteration or a few after what I thought I'm packing or something, which is mistake.

> Not sure why do you keep trying to show it's not the issue with your animation.

I simply think there's nothing wrong with the animations, that's why :) 

What you're saying is that changing the animation simply isn't starting the animation. To me this looks like a malfunction, not starting the animation "properly" upon changing it is like as if an integral part of the animation were ignored (imagine if the FPS setting of the animation were just inherited from the previous animation, or the texture from the previous animation were used… that's what this looks like to me) and that I have to use `play()` for that. If that's how it works fair enough. In my project I already solved it in some other way and it works great, so I'll close this. Thank you!

**Comment by mkraenz** [comment]
Hi, ran into this issue as well and got really frustrated. In particular, it is quite difficult to debug a setup with animation trees + anim player + anim sprites.

Thanks to this issue, I finally solved it using the call method track as shown in [this comment](https://github.com/godotengine/godot/issues/85203#issuecomment-1827715450). 
I'm just adding an image to show the full solution (in particular, where to set arguments for a call method track) for future readers. 

So eventually, for my tiny 2D platformer, I'm now only using `call method track` set to `AnimationSprite2D.play(..)` with `Args[0]` set to the animation name, and `property track` on `flip_h`

![2023-12-20_10-06](https://github.com/godotengine/godot/assets/8503034/7d433168-3fc8-4d9b-a4c9-475872af1adc)

**Comment by Pixelstyx** [comment]
This thread and accompanying explanation took far longer to find than it should have. I spent half the day debugging my game before realizing that I needed to reassert to the animator to play an animation, as due to the existence of 'Autoplay on Load' and the 'Loop Animation' toggle it only became a factor upon implementing my first non-looping animation.

While optimal in that it doesn't automatically force the animator to start playing again every time the animation is changed, the SpriteFrames interface for this feature feels vague at best and counterintuitive at worst. We can already set the animation property to a default value in the inspector for AnimatedSprite2D, so why is it overridden by setting a different animation to 'Autoplay on Load' in the SpriteFrames window? I feel that the better implementation would be to set the default animation exclusively in the AnimatedSprite2D and have 'Autoplay on Load' be a toggle that simply affects whether or not the animator is active when first loaded but is not tied to a particular animation. 

In fact, why is that setting even in the SpriteFrames window and not the AnimatedSprite2D interface in the Inspector? It's a properly of AnimatedSprite2D after all, not SpriteFrames, and yet they are set separately from one another

Or, at the very least, pretty please update the documentation like kleonc suggested [here](https://github.com/godotengine/godot/issues/85203#issuecomment-1822631935) to be more clear about the matter. You can realize the issue if you read between the lines, but that's generally not a great solution for most people new to the engine (like myself).

There also seems to be a similar feature proposal [here](https://github.com/godotengine/godot-proposals/issues/3911), but I feel as though it doesn't strike the core of the issue (which is that the function of designating a specific animation to autoplay rather than toggling whether the default animation autoplays doesn't make much sense).
