### ISSUE TITLE
global_shader_variables/buffer_size set too high in new Compatibility project

### ISSUE THREAD

**Issue by lostminds** [godotengine/godot#85374]
### Godot version

4.2.rc2

### System information

macOS 14.1

### Issue description

Creating a new Compatibility project the default setting for rendering/limits/global_shader_variables/buffer_size is set to 65536, but apparently this is too high for Compatibility renderer limits, because you get a warning when running:

```
W 0:00:00:0093   MaterialStorage: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 16384
  <C++ Source>   drivers/gles3/storage/material_storage.cpp:1114 @ MaterialStorage()
```

### Steps to reproduce

Create a new blank Compatibility project, with an empty scene and run it and see the warning

### Minimal reproduction project

Just create a new project from the project manager as I think the issue is the default value for new  Compatibility projects.

**Comment by jsjtxietian** [comment]
Yes, the `max_uniform_buffer_size` is read from GL using `glGetInteger64v(GL_MAX_UNIFORM_BLOCK_SIZE, &max_uniform_buffer_size);`, if it's smaller than the project setting's value (default is 65536) it will give a warning. Is there anything we can do other than just ignore the warning ?

**Comment by Jakub-Doucek** [comment]
In version: 4.2.1 the default value is 16384
But on iOS device I'm getting the warning anyway
`USER WARNING: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 16384`

The warning is probably ok, because the limit is for some reason really small. And that's what I see as the main problem. 3D models need to have a very small polycount. The same device has no problem with the Vulkan renderer.

**Comment by jsjtxietian** [comment]
Can we define "rendering/limits/global_shader_variables/buffer_size" based on OS and rendering method? If so we can give it seperate definition.

**Comment by jsjtxietian** [comment]
> split the uniforms up into multiple UBOs internally, or use a SSBO internally

Yeah that includes more work, and potentially less performant if SSBO is used.

**Comment by clayjohn** [comment]
SSBOs aren't supported in OpenGL 3.3, nor can we use multiple UBOs for the global buffer. So we are kinda stuck with the low limit for compatibility devices.

**Comment by Jakub-Doucek** [comment]
My understanding of these low-level rendering things is limited, but I don't believe it can't be done.  Especially since it works in version 3.5. So I see it as a regression bug.

Tested on: iPhone 13 Pro Max - iOS 17.1.2 (21B101)

I created a simple project with a 3D scene and imported two models (in Godot 4 they are in AssetLib)

### Godot 3.5
![Screenshot 2024-01-05 at 8 00 25](https://github.com/godotengine/godot/assets/8873388/60dc3da5-f042-4bd2-8e57-d454ef3df119)
iPhone screenshot:
![IMG_7B993A0EE8DD-1](https://github.com/godotengine/godot/assets/8873388/d4c88630-bb59-4a7e-9df8-823040c1a2a0)
log:
```
*********** main.m
running app main
Path: /var/containers/Bundle/Application/C6A87A44-043A-4569-BADF-F11E52848509/render_test.app
godot_iphone /var/containers/Bundle/Application/C6A87A44-043A-4569-BADF-F11E52848509/render_test.app/render_test
cwd /private/var/containers/Bundle/Application/C6A87A44-043A-4569-BADF-F11E52848509/render_test.app
os created
setting data dir to /var/mobile/Containers/Data/Application/0B717A00-97AA-42CF-892E-64DB3D6894DF/Documents from /var/mobile/Containers/Data/Application/0B717A00-97AA-42CF-892E-64DB3D6894DF/Documents
setup 0
Setting up an OpenGL ES 3.0 context. Based on Project Settings "rendering/quality/driver/driver_name"
failed to make complete framebuffer object 8cd6
Failed to create frame buffer!
******** setting up keyboard input view
******** adding observer for keyboard show/hide
start animation!
ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:249) - AudioOutputUnitStart failed, code: -50
Godot Engine v3.5.stable.official.991bb6ac7 - https://godotengine.org
OpenGL ES 3.0 Renderer: Apple A15 GPU
Async. shader compilation: OFF
ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:249) - AudioOutputUnitStart failed, code: -50
Godot Engine v3.5.stable.official.991bb6ac7 - https://godotengine.org
OpenGL ES 3.0 Renderer: Apple A15 GPU
Async. shader compilation: OFF
 

******** stop animation!
Audio interruption began
start animation!
******** stop animation!
Audio interruption began
```

### Godot 4.2.1
![Screenshot 2024-01-05 at 8 07 30](https://github.com/godotengine/godot/assets/8873388/b9dc8c74-6def-4663-a707-6506c783b96d)
iPhone screenshot:
![IMG_91B794DC6153-1](https://github.com/godotengine/godot/assets/8873388/c0fe2d55-f9e7-4cd9-a74c-b484bc9ffa56)
log:
```
USER ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:251)
USER ERROR: AudioOutputUnitStart failed, code: -50
   at: start (drivers/coreaudio/audio_driver_coreaudio.cpp:251)
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Setting up an OpenGL ES 3.0 context.
USER WARNING: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 16384
   at: MaterialStorage (drivers/gles3/storage/material_storage.cpp:1114)
USER WARNING: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of: 16384
   at: MaterialStorage (drivers/gles3/storage/material_storage.cpp:1 114)
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
OpenGL API OpenGL ES 3.0 Metal - 99 - Compatibility - Using Device: Apple Inc. - Apple A15 GPU
OpenGL API OpenGL ES 3.0 Metal - 99 - Compatibility - Using Device: Apple Inc. - Apple A15 GPU
 

USER WARNING: Icon not supported by this display server.
   at: set_icon (servers/display_server.cpp:577)
USER WARNING: Icon not supported by this display server.
   at: set_icon (servers/display_server.cpp:577)
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...
DrawView: 506 error
Audio interruption began
Audio interruption began
```

**Comment by Jakub-Doucek** [comment]
I apologize for the misunderstanding. I have investigated the problem further and found that it is probably not related to the `exceeds maximum uniform buffer size` warning at all. 
It helped to reduce the polycount and I saw the warning, so I thought it was because of that.
But it was fixed probably just because I re-exported the model without animations. 

The model doesn't seem to render if it has bones attached.  So it's an unrelated issue. It still occurs in 4.3.dev1 version.

**Comment by clayjohn** [comment]
@Jakub-Doucek Indeed, 3.5 doesn't support global shader uniforms, and you don't appear to be using them in your project anyway, so your issue isn't related at all.

**Comment by lostminds** [comment]
I just tested this in 4.2.1 to see if it was still an issue and when creating a new Compatibility project and running it I'm no longer getting the warning. However, when checking the project settings `rendering/limits/global_shader_variables/buffer_size` is still 65536, so the default hasn't changed. 

Can anyone confirm if this mean the issue is now solved so I can close this issue (that the Compatibility renderer now supports this buffer size?) or is there some other change that just causes the warning not to show even if the limit is still there?

**Comment by Calinou** [comment]
I think you got this warning 4.2.rc2 because it was using ANGLE by default on macOS, but this is no longer the case. If you edit project settings to use the `opengl3_angle` rendering driver (not rendering method), you will probably see that warning again.

**Comment by lostminds** [comment]
> If you edit project settings to use the `opengl3_angle` rendering driver (not rendering method), you will probably see that warning again.

I see, that may be the case. However, it seems I can't use the Angle OpenGL drivers anymore (They used to work). Changing the project setting to used Angle and restarting I get the following error and get switched back to native OpenGL again:

```
_get_gldisplay_id: Condition "eglGetError() != 0x3000" is true. Returning: -1
  <C++ Source>   drivers/egl/egl_manager.cpp:63 @ _get_gldisplay_id()
 DisplayServerMacOS: Your video card drivers seem not to support the required Metal version, switching to native OpenGL.
  <C++ Source>   platform/macos/display_server_macos.mm:4529 @ DisplayServerMacOS()
```
Not sure what's going on there, but it seems unlikely the graphics card doesn't support the required Metal version (unless it's some old outdated Metal version) as it's quite a new M2 mac. And I did use the angle driver briefly back when that was the default on mac.

**Comment by clayjohn** [comment]
> > If you edit project settings to use the `opengl3_angle` rendering driver (not rendering method), you will probably see that warning again.
> 
> I see, that may be the case. However, it seems I can't use the Angle OpenGL drivers anymore (They used to work). Changing the project setting to used Angle and restarting I get the following error and get switched back to native OpenGL again:
> 
> ```
> _get_gldisplay_id: Condition "eglGetError() != 0x3000" is true. Returning: -1
>   <C++ Source>   drivers/egl/egl_manager.cpp:63 @ _get_gldisplay_id()
>  DisplayServerMacOS: Your video card drivers seem not to support the required Metal version, switching to native OpenGL.
>   <C++ Source>   platform/macos/display_server_macos.mm:4529 @ DisplayServerMacOS()
> ```
> 
> Not sure what's going on there, but it seems unlikely the graphics card doesn't support the required Metal version (unless it's some old outdated Metal version) as it's quite a new M2 mac. And I did use the angle driver briefly back when that was the default on mac.

It turns out this is an issue with our build scripts. We are using the wrong version of ANGLE in official builds. At any rate, the angle build has a few issues that we are still working on while we fixed several issues in the native opengl backend that make it perform better

**Comment by clayjohn** [comment]
Bad news, while looking into a related issue I realized that our validation here was wrong. The setting sets the total number of uniforms that can be used by the buffer, but we treated the total number of uniforms as if were the total number of _bytes_. So even after validation, we only reduced the size of the buffer to 16384, which then allocated a buffer with a size of 16384 * 16. The actual limit for mobile devices is 1024 items. :( For desktop devices the limit is 4096.

This is unfortunately a huge limitation. If users need more than 1024 items, we will have to use a texture instead of a uniform buffer. If we do so, the limit can be removed, but using the global buffer (and per-instance buffer) will become much more expensive at draw time.

**Comment by lostminds** [comment]
> The setting sets the total number of uniforms that can be used by the buffer, but we treated the total number of uniforms as if were the total number of _bytes_. ... This is unfortunately a huge limitation.

Considering the size of the values I also guessed these were sizes in bytes rather than number of uniforms. It's probably my lack of imagination, but to me 1024 global shader uniforms (where you can use 256 in a single draw call?) seems like quite a lot to me. So I wouldn't see it as such a big limitation even if the number is much smaller. 

Considering all projects have a setting for this that is likely using the old `buffer_size` default values that will now be too high, I think this will mostly be an issue about warnings about that. To most users it'll be a number they don't understand (and doesn't have a description) that is now suddenly allowed a much smaller number and has to be changed. To avoid confusion about this after 4.3 update perhaps you could simply replace `buffer_size` with a new better named `max_items` setting, with a description to explain what this number means and with new correct defaults based on renderer for the project?

**Comment by lostminds** [comment]
Just noticed in 4.3beta2 we now get a warning that the setting is too high and that it will fall back to 4096 (running on desktop) after https://github.com/godotengine/godot/pull/92568. However, the default value if you go into Project settings and reset it to default is still 65536. So I'm guessing this should be changed to 4096 for desktop projects and 1024 for mobile to avoid this warning for all new projects?

**Comment by clayjohn** [comment]
> However, the default value if you go into Project settings and reset it to default is still 65536. So I'm guessing this should be changed to 4096 for desktop projects and 1024 for mobile to avoid this warning for all new projects?

Not exactly, this same setting is used by all renderers. On the Mobile and Forward+ renderer the default of 65536 is fine. Changing the limit for everyone to 4096 will break compatibility. For the Compatibility renderer its fine because using more than the number supported by the device wouldn't have worked anyway, but for the other backends its a problem. 

I suspect that we should do the following:
1. Suppress the warning for now and only warn if a user tries actually uses more variables than the limit
2. Investigate another method to provide global shader variables that isn't limited to so few items (either using a texture, or paging uniform buffers)

**Comment by lostminds** [comment]
> 1. Suppress the warning for now and only warn if a user tries actually uses more variables than the limit

Is there some benefit to setting this setting to anything lower than the max allowed? If not, perhaps the setting could just be removed and the max allowed always be used if the engine would instead correctly validate the number of variables actually used and block/warn if there were too many to be supported.

**Comment by patwork** [comment]
You would lose the possibility to save GPU memory by manually changing the setting to some small value.

Realistically, **most** (desktop) GPUs will return GL_MAX_UNIFORM_BLOCK_SIZE  = 65536, but there are some exceptions:

https://stackoverflow.com/questions/47932609/uniform-buffer-size-on-nvidia-gpus

> As I researched this problem, I found GL_MAX_UNIFORM_BLOCK_SIZE variable which returns ~500MB on the AMD and 65.54 kB on both Nvidia chips.

**Comment by terrybader** [comment]
Getting similar with no value shown

WARNING: Project setting "rendering/limits/global_shader_variables/buffer_size" exceeds maximum uniform buffer size of:.
     at: MaterialStorage (drivers/gles3/storage/material_storage.cpp:1115)

**Comment by clayjohn** [comment]
> > 1. Suppress the warning for now and only warn if a user tries actually uses more variables than the limit
> 
> Is there some benefit to setting this setting to anything lower than the max allowed? If not, perhaps the setting could just be removed and the max allowed always be used if the engine would instead correctly validate the number of variables actually used and block/warn if there were too many to be supported.

For the compatibility renderer (especially on web and low end devices) shader compile time is faster with a lower limit. 

For the RD renderers, the maximum size can be several mbs, so the limit helps to save memory.

**Comment by clayjohn** [comment]
It looks like we already provide an error when we attempt to use too many. 

https://github.com/godotengine/godot/blob/374807f427eec5ee7caebfc509a158fe715a6bfe/drivers/gles3/storage/material_storage.cpp#L1791

https://github.com/godotengine/godot/blob/374807f427eec5ee7caebfc509a158fe715a6bfe/drivers/gles3/storage/material_storage.cpp#L2002

We can just improve the error message so that it specifies the hardware maximum

**Comment by TheGiraffe3** [comment]
Unpin this?
