### ISSUE TITLE
Scene buttons do not update on theme editor font size change.

### ISSUE THREAD

**Issue by OrlanRod** [godotengine/godot#85408]
### Godot version

4.1.3 stable

### System information

Windows 11 64 bit

### Issue description

Buttons that are inside a scene, do not update their font sizes in editor. But if a add a new button after the changes made, they are not affected by this problem. 

### Steps to reproduce

- Create a project and add a button to control scene.
- Add a global theme resources to Godot and edit the font size in the theme editor.
-Observe no changes are made to button's font size in the editor.

### Minimal reproduction project

![Screenshot 2023-11-26 193125](https://github.com/godotengine/godot/assets/21212571/05661280-14e5-40e7-bde0-c5dc4b86a05a)

**Comment by AThousandShips** [comment]
Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed), or if you are not on 4.1 specifically, please write the actual version you are on

**Comment by OrlanRod** [comment]
> Can you please try this with a supported version, like 4.1.3 (only the latest patch version is supported, and it might already be fixed), or if you are not on 4.1 specifically, please write the actual version you are on

Yes the latest stable, corrected my original post. 4.1.3 stable

**Comment by YuriSizov** [comment]
> * Add a global theme resources to Godot and edit the font size in the theme editor.

In Godot 4.1 and prior changes to global themes to not propagate to controls. You need to refresh the scene manually to see the changes. This is fixed in 4.2 (you can give RC2 a try to check for yourself), and changes to global themes now correctly update affected controls on the fly (in editor and in projects).

Unfortunately, this change depends on a bigger enhancement done in 4.2, so the fix cannot be backported to a 4.1.x patch release. I recommend upgrading to 4.2 if and when you have a chance.
