### ISSUE TITLE
Normal Map Disabled With Detail Active

### ISSUE THREAD

**Issue by WickedInsignia** [godotengine/godot#85413]
### Godot version

4.2 RC 2

### System information

Windows 11, Nvidia RTX4070ti, AMD Ryzen7700x

### Issue description

Activating Detail in a Standard Material disables standard Normal Map entirely regardless of Blend Mode.

### Steps to reproduce

Activate Detail in a Standard Material on any mesh with a Normal Map.

### Minimal reproduction project

[Tangent_Issues_NormalMapVer.zip](https://github.com/godotengine/godot/files/13469758/Tangent_Issues_NormalMapVer.zip)

**Comment by clayjohn** [comment]
I'm assuming the problem is that enabling detail without having any of the textures is impacting the normal_map. @WickedInsignia Can you confirm that that is your problem? I.e. you want to use detail for adding detail to the albedo, but not the normal map?

Assuming that I am correct about the issue, the problem comes from these two lines:
https://github.com/godotengine/godot/blob/eda44bfe109d7f15c5a965db2d65c8a17ce4b7d0/scene/resources/material.cpp#L1518-L1519

This is used if detail is enabled, even if there is no detail normal map used. Meaning that the normal map property gets changed needlessly. 

The solution is to wrap these lines in a check if the detail normal map texture is valid. If the detail normal map texture is not valid, then the lines shouldn't be included.

**Comment by WickedInsignia** [comment]
@clayjohn it happens regardless of whether I have a normal map or albedo in their respective slots under Detail when it is activated.
My intent in my own projects was to add normal detail over the existing normal map using triplanar or a UV2. This object has no UV2 and that setting isn't active in the shader, but it has happened to other meshes I've tested with a UV2.

Hopefully that answers your question since I'm not entirely clear on that first paragraph.

**Comment by clayjohn** [comment]
> @clayjohn it happens regardless of whether I have a normal map or albedo in their respective slots under Detail when it is activated. My intent in my own projects was to add normal detail over the existing normal map using triplanar or a UV2. This object has no UV2 and that setting isn't active in the shader, but it has happened to other meshes I've tested with a UV2.
> 
> Hopefully that answers your question since I'm not entirely clear on that first paragraph.

Well, my confusion comes from the fact that the MRP has nothing to do with the reported issue. The MRP only contains a mesh with a normal_map. It doesn't have a mesh with a normal_map _and_ a detail_texture with a detail_normal_texture. Without a detail_texture, its expected that the detail added will look incorrect (similar to how enabling normal_map without a normal_map texture messes things up). 

So I am trying to figure out what your issue is. Based on your report and MRP I can see potentially three things:
1. You want to use a detail albedo texture without a detail normal texture (thats what I asked about in my last comment)
2. You want to use both a detail albedo texture _and_ a detail normal texture, but its broken (the MRP doesn't show this)
3. You are frustrated that enabling detail changes the look of your mesh _until_ you set proper detail and detail_normal textures (again, the MRP doesn't show this, but it is expected behaviour)

Maybe some background will be helpful. If you enable "detail" on your material, you need to set a detail_texture. The detail texture will be used to add detail and the alpha channel of the detail texture is used to blend between the existing albedo/normal_map and the detail albedo/normal_map. If you don't set a texture, you will get a plain white texture instead. That can be problematic in two ways:
1. A white texture will turn your mesh white
2. Since the alpha channel of then white texture is 1, and it is used to calculate the blending, the detail_normal_map will totally override the regular normal_map. Since the detail_normal_map is also a plain white texture, you get bogus normals. 

Could you provide an MRP that fully illustrates the problem you are having?

Also, could you explain the steps that you take? Including what you expect and what happens? Clearly more information is needed.

**Comment by Calinou** [comment]
> Could you provide an MRP that fully illustrates the problem you are having?

@WickedInsignia Bump :slightly_smiling_face:

**Comment by Calinou** [comment]
Closing due to lack of response. Please comment if you can still reproduce this bug on the latest Godot version.

PS: Since no minimal reproduction project was included in the original bug report, please upload one as well to ease troubleshooting.

**Comment by WickedInsignia** [comment]
My misunderstanding came from what @clayjohn pointed out, which is that a mask is required.
This didn't seem natural to me since in Unity no mask is required for detail textures to blend, it's optional. Godot's proposed system didn't make any sense regardless of specific comparisons, so I presumed that wasn't how it was supposed to work.
The reason I didn't include a detail normal in the MRP was because simply activating the Detail feature disabled my main normal map, regardless of whether a detail normal was present. This was odd behavior since I expected the absence of a mask wouldn't affect the main normal.

Some industry usage background: Detail maps are most commonly used to fill in detail at a higher frequency when the main texture can't reach the desired texel density, or when more micro-level detail is required. This is the expected usage and what I was trying to replicate.

To my understanding, if I want a detail normal map to blend with the main normal map in Godot I need to set the Detail Mask to 50% grey. This reduces both normal map's strength by half, so I need to double the normal map intensity by two. This isn't very intuitive but at least at that point it's functioning as intended.
An issue I've come across on top of this is that there's no way to scale the detail textures without affecting the main maps. Usually you would scale detail textures down by 1/4th or more so they repeat at a high frequency across the mesh, to create a higher level of detail. That isn't possible in Godot's Standard Material without the use of UV2, which presents an issue if lightmapping is needed.

I would've written some proposals to improve this system but my last experiences with contributing to Godot and specifically the character attacks from the lead dev have encouraged me to step away indefinitely.

**Comment by Calinou** [comment]
>  An issue I've come across on top of this is that there's no way to scale the detail textures without affecting the main maps. Usually you would scale detail textures down by 1/4th or more so they repeat at a high frequency across the mesh, to create a higher level of detail. That isn't possible in Godot's Standard Material without the use of UV2, which presents an issue if lightmapping is needed.

I have a [proposal](https://github.com/godotengine/godot-proposals/issues/3499) and [pull request](https://github.com/godotengine/godot/pull/54651) for this, but they haven't gotten much community support.

**Comment by WickedInsignia** [comment]
If a 2+ year old PR for a very common industry standard feature is left to collect dust on the shelf, as I've seen happen with many features that Godot's art pipeline could heavily benefit from, perhaps my proposal for better public-facing prioritization and roadmapping wasn't misplaced.
This isn't a community support issue, it's a core team prioritization issue. If community demand actually mattered, we'd have a native terrain editor as of 6 years ago.

Excuse the ramblings of a jaded user but I would say I'm glad this is in the pipe if I didn't already know how long it will stay there.
