### ISSUE TITLE
When moving a NavigationRegion2D the NavigationServer2D does not update.

### ISSUE THREAD

**Issue by xylr117z4** [godotengine/godot#85545]
### Godot version

4.2.stable, 4.2.stable.mono

### System information

Godot v4.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (Advanced Micro Devices, Inc.; 31.0.22011.4008) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

According to the "Using NavigationRegions" documentation https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationregions.html

"While changing the transform of a NavigationRegion node does update the region position on the NavigationServer, changing the scale does not."

This is true in 4.1.1.stable
However it is not working in 4.2.stable

Using either a RemoteTransform Node or setting the transform of the region directly.
Does not update the NavigationServer.

I'm using specifically the .Net release of 4.1.1.stable and 4.2.stable
But my scripts are in GDscript, doubt that matters, but just in case.

### Steps to reproduce

Create a scene with a NavigationRegion2D.
Add a NavigationPolygon
Add a script which moves the NavigationRegion2D using it's .position variable.
To see the lack of update connect NavigationServer2D.map_changed to any print function.

In 4.1.1 this will emit/print every physics frame in which the map changes.
In 4.2 this will emit/print once on the first frame.

### Minimal reproduction project

In the minimal reproduction project you can use the arrow keys to move the NavigationRegion2D around the screen.
The console will print out when NavigationServer2D.map_changed is emitted.

[NavigationRegionUpdateBug.zip](https://github.com/godotengine/godot/files/13514279/NavigationRegionUpdateBug.zip)

**Comment by xylr117z4** [comment]
Just tried using NavigationServer2D.region_set_transform()
NavigationServer2D will emit map_changed however, it does not appear that the region's position actually changes.
It's not reflected with Debug>Show Navigation, nor while printing the region's position.

**Comment by smix8** [comment]
The NavigationRegion2D transform notification is currently broken. See pr https://github.com/godotengine/godot/pull/85258 that fixes it.

The debug visuals are part of the node, so any change that is done on the server-only will not be shown with the debug. E.g. moving the region with the NavigationServer API will not move the debug. A lot of the debug in Godot is currently node-based and has the same issue because the node updates are usually one-way tickets to the server and not the other way. See proposal https://github.com/godotengine/godot-proposals/issues/7208 that wants to change this.

**Comment by smix8** [comment]
Yes it is basically a duplicate, that linked issue about the not updating edge connections has the same problem that the transform notification does not work for the NavigationRegion2D.
