### ISSUE TITLE
An animation replaces other animation.

### ISSUE THREAD

**Issue by juliano-CN** [godotengine/godot#85573]
### Godot version

4.1.1

### System information

Godot v4.1.1.stable - Windows 10.0.19045 - Vulkan (Compatibility) - NVIDIA GeForce MX110 () - Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 Threads)

### Issue description

I have three animations in my platform game. The texture of the 'jump animation' is to be replaced by the 'idle animation'.

### Steps to reproduce

Just run the project and observe the animations, especially the transition from the 'jump animation' to the 'idle animation'. You can also replace the texture in the 'idle animation' with the 'jump sprite sheet.png' texture located in the sprite folder and wait.

### Minimal reproduction project

[magician game.zip](https://github.com/godotengine/godot/files/13518053/magician.game.zip)

**Comment by rakkarage** [comment]
Set the `hframes=8` on the `Sprite2D` instead of in the animation.
It is set to 4 on sprite and other numbers in animations, so it is like animating the number of frames.
That is why each frame looks like two frames wide.
Then you can remove all those other animation tracks and just keep the `frame` one.
If i understand the problem correctly.

**Comment by KoBeWi** [comment]
You shouldn't be changing `texture:load_path` in your animation, it's breaking your textures. The animations display correctly when you remove the `load_path` track.
