### ISSUE TITLE
Add "node" to signal's Add Extra Call Argument in GUI!

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#8557]
**Operating system or device - Godot version:**
V2.1.2

**Issue description:**
This is weird because programmatically we can just do:

`control.connect("mouse_enter", self, "MouseEnterFunction", [control])`

then
```
func MouseEnterFunction(node):
    print(node)
```

which works fine.

However... when connecting signals through the GUI:

![image](https://cloud.githubusercontent.com/assets/10387670/25475210/daec94be-2aea-11e7-9ecd-a92891be05c7.png)

There is no option to pass the node itself! Only types.

**Comment by reduz** [comment]
Thats for fixed values, for dynamic stuff including self just connect
manually

On Apr 27, 2017 10:44 AM, "Dillybob92" <notifications@github.com> wrote:

*Operating system or device - Godot version:*
V2.1.2

*Issue description:*
This is weird because programmatically we can just do:

control.connect("mouse_enter", self, "MouseEnterFunction", [control])

then

func _MouseEnterFunction(node):
    print(node)

which works fine.

However... when connecting signals through the GUI:

[image: image]
<https://cloud.githubusercontent.com/assets/10387670/25475210/daec94be-2aea-11e7-9ecd-a92891be05c7.png>

There is no option to pass the node itself! Only types.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8557>, or mute the thread

**Comment by Dillybob92** [comment]
i mean you're not wrong.. i just wouldn't use the gui then if i had to do it manually lol.

i think edit signal feature could be really good too. Godot has the power (already does) to become an insane application tool, just not for games but for native application & ui development.  It's very underrated and the more gui tool features the better.

**Comment by blurymind** [comment]
It would be very cool if we can also pass parameters to the function/method we are triggering
Without this, the feature to edit connections in the editor is only half functional imo

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
