### ISSUE TITLE
NavigationRegion2D bakes collisions only from first layer of Tilemap

### ISSUE THREAD

**Issue by Giometric** [godotengine/godot#85588]
### Godot version

4.2.stable

### System information

Godot v4.2.stable - macOS 14.1.1 - Vulkan (Mobile) - dedicated AMD Radeon Pro 560X - Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 Threads)

### Issue description

When using NavigationRegion2D's "Bake NavigationPolygon" feature, it should take into account any collision shapes within the region's boundaries. With separate collider objects, such as StaticBody2D, this works as expected. However, when baking with a Tilemap that has tiles with collision, only tiles in the first layer will have any effect on the resulting navigation mesh. Even if painting the same tiles with the same collision shape, any of the tiles painted on a layer other than the first layer will have no effect.

<img width="674" alt="image" src="https://github.com/godotengine/godot/assets/4956530/80644f8b-79fb-4cb0-89b0-0b6a5b837a79">

### Steps to reproduce

Create a TileSet resource to use in the Tilemap which has at least one tile defined that includes collision geometry (with at least one Physics Layer defined that the solid tiles will use). In a new scene, create a NavigationRegion2D (default settings are fine), and a Tilemap as a child of this NavigationRegion2D. On the Tilemap, use the created TileSet, and make sure there are at least 2 layers. Paint some solid-collision tiles into the Tilemap on both layers, leaving some empty spaces that would be 'navigable', then create a shape for the NavigationRegion2D that encompasses all the painted tiles.
Then, select the NavigationRegion2D, and click "Bake NavigationPolygon" to bake the navigation mesh. Observe that only the solid tiles painted into the first layer of the Tilemap will have any effect on the baked mesh.

### Minimal reproduction project

N/A

**Comment by smix8** [comment]
That is an expected limitation of the TileMap. See https://github.com/godotengine/godot/issues/83967 for more info.

**Comment by Giometric** [comment]
I don't totally understand; I get why you wouldn't want to use the navigation polygons from more than one tilemap, as those overlapping would be bad, but why would having overlapping colliders not work? If I dropped a number of StaticBody2Ds into my scene, and some of them had overlapping shapes, I would expect the navigation mesh bake to still work. Why would using overlapping colliders from a tilemap be different?

**Comment by smix8** [comment]
Overlapping cells with shapes that makes polygons "nested" inside each other will trigger polygon hole calculation. That can make polygons flip sides and turn into holes and vice versa. It makes the entire result unpredictable for users the more shapes are involved. See https://github.com/godotengine/godot/issues/85122 where the user stacked polygons by using TileMap and the result turned out not as the user intended.

As mentioned in the linked issue one solution could be that the TileMap adds options so users can define how they intend to mix and match the TileMap Layers and the TileMap can then combine those internally. Whatever the solution might be, the ball is in the TileMap court to provide both a user GUI as well as a single "layer" with no stacked and / or nested polygons for the parser of the navigation mesh baking process.

Overlapping physics collision in general, while not immediately treating you with bugs, will run at degraded performance. All those shapes are still inside the same physic space and bvh cell tree section. The physics_layers only allow the physics to skip some of their calculations.

**Comment by Giometric** [comment]
Yeah, for the nav polygons I do understand and it makes sense why we don't want to overlap them at all, as it would be a case of producing unintended / broken results almost guaranteed. For collisions, "it might be slow if you do it wrong" IMO isn't totally the same; the feature of Tilemaps to create collisions, which happen to be useful for baking navigation meshes, has nothing to do with the feature of Tilemaps to create navigation polygons.
Closing this as it sounds like it won't be fixed anytime soon and is easily worked around anyway. I'll look into opening up some issues on the documentation soon, as none of these caveats or limitations are mentioned there as far as I could tell. (for example, the "Navigation enabled" checkbox on every Tilemap layer, which appears to have no effect at all, if we can only use the first layer anyway why is it there?)
