### ISSUE TITLE
godot 4 keeps on freezing when i add a child to parent

### ISSUE THREAD

**Issue by GODCHUBBY** [godotengine/godot#85587]
### Godot version

4.1

### System information

window 10

### Issue description

i cant even close the window when it freezes

### Steps to reproduce

i open my godot 4 project then when ever i want to add a child to a node it freezes

### Minimal reproduction project

godot 4 keeps on freezing when i add a child to parent

**Comment by GODCHUBBY** [comment]
someone help me

**Comment by akien-mga** [comment]
Can you try Godot 4.2?

**Comment by Sauermann** [comment]
Can you please provide more details? Without a description of how to replicate the issue it is extremely difficult to debug this. Perhaps you could provide the console output, if possible.

**Comment by Jan-PieterInghels** [comment]
I am here because I have the exact same issue.
Using 4.2.1.stable.
It's a rare occurence but it seems like once it happens in a project, the engine will hard freeze every time a child node is added without exception.
System reboot did nothing to solve the issue. Not sure if I am allowed to upload my project somewhere?

**Comment by Sauermann** [comment]
Thank you for the report. Consolidating this as a duplicate with #83855.
Please continue the discussion in that bugreport.
