### ISSUE TITLE
Texture Repeat doesn't work in 3D

### ISSUE THREAD

**Issue by JustTab** [godotengine/godot#85641]
### Godot version

Steam version (Stable 4.2, Build ID 12837360)

### System information

Windows 10 22H2 - Godot V4.2 Stable - Vulkan

### Issue description

I know this has probably been answered a million times before, but i have been looking to solve this issue for days, to find no answer anywhere to my problem. Basically, the Repeat option under Filtering in a material does not work in any way. I know i can just use the scaling settings in the material, but that applies it to every texture, and no, Triplanar/World Triplanar does not work. If I don't understand this setting correctly, please tell me.

### Steps to reproduce

Make a Material (.tres). apply the No filtering Mipmapped (because that's what i used, but realistically any option would probably work) and the repeat settings under Filtering in the Material. Apply this material to any mesh, and voila, no repeating textures.

### Minimal reproduction project

[test.zip](https://github.com/godotengine/godot/files/13533230/test.zip)

**Comment by clayjohn** [comment]
Taking a look at the MRP, and there doesn't appear to be a bug. 

The MRP has repeat enabled, but it is just a plain CSGBox with a default StandardMaterial. Textures will not repeat with a default CSBox since the UVs on the box only go from 0-1. The "repeat" setting controls what happens with UVs outside the 0-1 range. I.e. if the UV goes to 2 "repeat" tells the material to repeat the texture instead of clamping it. 

Try setting the UV1 scale to 2 and then enabling and disabling repeat and you will see how it works.

**Comment by JustTab** [comment]
But there's no way for a material to repeat based on world coordinates?

**Comment by JustTab** [comment]
Nvm im just gonna use Triplanar.
