### ISSUE TITLE
Tilemap Collision not colliding with player in 4.2

### ISSUE THREAD

**Issue by feendrache** [godotengine/godot#85680]
### Godot version

4.2

### System information

Windows 11, Godot 4.2

### Issue description

Collisions provided by Tilemaps are not stopping the Player.
I ported my game from 4.1 and the tilemap collisions, working in 4.1 simply stopped working in 4.2

Navmesh Baking registers the colliders provided by the tilemap, the player just doesn't collide with it/isn'T stopped by it

### Steps to reproduce

Create a Tilemap with a Tileset that has collisions set and a Player and run around, my player can simply pass the collisions of the tilemap

### Minimal reproduction project

n/a

**Comment by AThousandShips** [comment]
Please provide a minimum reproduction project to help with testing, as this could be a configuration error:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by feendrache** [comment]
i created a minimal project, but it works just fine...
collisions with the tilemaps are working, the tilemap and player settings are the same for the layers and masks... so still no clue why it doesn't work for the old project

**Comment by feendrache** [comment]
ok, so i have my layered tilemap that'S providing the art
and i have an additional tilemap that contains the collision... a tileset with setup collisions. 
Collision Layers on tilemap: 1 and mask 1
collision layers on playe3: 2 and mask 1,2 and some others

it worked just fine in 4.1 and the same setup works in my mini-blank project

**Comment by feendrache** [comment]
funny thing: when i bake my navmesh it is recognising the collision on the tilemap... just the player is acting like it's not there

**Comment by feendrache** [comment]
ok, i checked and rechecked and rechecked again but i have no clue why the two items are not colliding... staticbodys with a collider have no problem blocking the player having the same settings for the collision layers and masks... 

Someone an idea where and what i can check?

**Comment by bs-mwoerner** [comment]
I vaguely remember having some weird TileMap behavior the other day (forgot what it was unfortunately) and then noticing "Collision Animatable" was enabled on that TileMap. Disabling it fixed whatever issue I was having. I think the collisions were still there, just not where I expected them to be.

**Comment by ErraticUnicorn** [comment]
I seem to be having a similar issue where my tilemap collisions work when testing the scene but when my game loads the scene with the tilemap my player does not collide with any tilemap collision. 🤔

**Comment by ErraticUnicorn** [comment]
Downgrading back to 4.1 fixes my issue.

**Comment by nicopujia** [comment]
@feendrache hello, I'm just having a very similar issue. The only different thing is that the collisions exist but in a different place, like if they had moved (however, when I run the game with collisions visible they are drawn where they should be, even though they really aren't there). 

But the really strange thing that is happening to me, besides the main problem, is that **when I resize the game window, it just works normally**.

Here is a video showing the problem:
https://github.com/godotengine/godot/assets/86862867/e7d3cd43-b5bb-47f1-a930-37e7d2f5d5f7

Does this also happens to you?

**Comment by ErraticUnicorn** [comment]
I have attempted to set up a new project using my tileset in 4.1 and upgrading it to 4.2 but was unable to replicate the issue. Resizing the window does not fix my issue either. Happy to hop on a call to show off the issue I am experiencing, I am a member of the discord :)

**Comment by nicopujia** [comment]
Sure, I am `nicopujia` on discord. Send me a message so we can organize a call. I'll probably see the message at night (I live in Argentina, you can see what time it is here in my GitHub profile)

**Comment by bs-mwoerner** [comment]
I tried unsuccessfully to come up with a minimal reproduction project. It's not obvious to me what causes this. I noticed, however, that when it occurs, I can fix the collisions by just doing `tilemap.position = tilemap.position` on all tilemaps after adding them to the scene. I wonder if this is related to the changes in dae6416. There is some processing that happens on `DIRTY_FLAGS_TILE_MAP_XFORM` but not on `DIRTY_FLAGS_TILE_MAP_IN_TREE`. I don't know enough about the system to tell whether this might be a factor, though.

**Comment by feendrache** [comment]
i cannot come up with a repro project too... and my tilemaps are not added per code, they already are there, so ... they should be loaded... i currently work with all my tilemaps set to visible but the modulate alpha set to zero

**Comment by bs-mwoerner** [comment]
I've now got a MRP for my particular case, although that's a different scenario from what you describe. Still, if we're lucky, the root cause may be related.

What I've found now:
If the tile map is the child of another node and you remove that node from the scene _before the first physics frame_, that tile map's collisions will not work the first time it is added back into the scene. Collisions will work if the tilemap is removed and added again after that.

Minimal reproduction project:
[TileMapTree.zip](https://github.com/godotengine/godot/files/13628110/TileMapTree.zip)
- Use the cursor keys to move the character.
- Press Enter to add the tile map back to the scene. The character will not collide with the tile map.
- Press Enter twice more to remove and add the tile map once more. Collisions will work now.

I'm removing the tile map in `_ready()` here, which I believe was not possible before Godot 4.2. In my own project, I used `call_deferred` to get the same effect (probably still runs before the first physics frame).

Adding
```gdscript
$TileMaps/TileMap.position = $TileMaps/TileMap.position
```
right after
```gdscript
add_child(tilemaps)
```
makes collisions work right away.

**Comment by katian** [comment]
so strange, i need to do : 
TileMap.Position = TileMap.Position;
and collisions works
thanks @bs-mwoerner

**Comment by feendrache** [comment]
Just to mention it: i still have this problem... just found my own bug report to get a solution for me :D

**Comment by Shibusuke** [comment]
I also have this exact problem in the latest 4.2 as of writing, and the solve (TileMap.position = TileMap.position) after adding it to the tree is indeed the only way I have found to fix collision.

For context, I:
- Have two scenes, both of which use the same tile set to create two tile map nodes. Each scene has a unique layout. 
- When the game runs, the first scene becomes the active scene where the player can move around. Works fine.
- The second scene is preloaded in the background using the threaded loading method in ResourceManager
- When the player enters an Area2D near the "exit" to the first scene, a script retrieves the preloaded second scene from  ResourceManager, instantiates it, updates its position to align with being next to the exit from the first scene, and adds it as a child (also tested adding it as a sibling). 
- At this point, collision in the second scene will always fail. Collision in the first scene continues to work. Walking into the second scene causes the player to fall into the void. Same tile map, same collision setup, collision visibility checked in the debugger (collision is, visually at least, in the correct location).
- If I call run TileMap.position = TileMap.position in the second scene at least one frame after the second scene is added, collision will then work (I didn't have time to test without waiting a frame due to how my project is set up).

So I think this bug should be reopened.
