### ISSUE TITLE
Color changes when opening color picker

### ISSUE THREAD

**Issue by Jummit** [godotengine/godot#85743]
### Godot version

v4.3.dev.custom_build [d76c1d0e5]

### System information

Linux

### Issue description

When opening the color picker by clicking on a color property the color changes slightly.

### Steps to reproduce

* Click on a property with value `Color(.5, .5, .5) ` in the inspector
* Click away
* Open the color picker again
* See the color change to Color(0.502, 0.502, 0.502) in the "RAW" tab

### Minimal reproduction project

[ColorChangeBug.zip](https://github.com/godotengine/godot/files/13545089/ColorChangeBug.zip)

**Comment by Chaosus** [comment]
I think it's simply due to floating-point precision loss, it's okay and should not have influence on the color result.

**Comment by bs-mwoerner** [comment]
I'm a bit on the edge whether I'd see this as a bug. When the Color Picker opens, it converts the current color value to HTML, then parses that HTML back. This effectively quantizes the color to 8 bits (0.502 being the closest representable value to 0.5). While this is probably not a very relevant issue, as most applications will be happy with an 8-bit resolution for literal color parameters, it still feels a bit weird that just opening the editor for a property loses half of the current value's resolution and gives the scene a "changed" status.

This does not seem to affect colors with components above 1.0, because those don't have an HTML representation.
