### ISSUE TITLE
Running project from command line launches editor or project manager

### ISSUE THREAD

**Issue by jonri** [godotengine/godot#85771]
### Tested versions

- Reproduced in Godot Engine v4.2.stable.arch_linux
- Reproduced in Godot Engine v4.1.2.stable.official.399c9dc39 (MacOS M1)

### System information

Godot Engine v4.2.stable.arch_linux, v4.1.2.stable.official.399c9dc39

### Issue description

Running `godot -h` lists the following usage options to run a project or scene directly from the command line:
`Usage: godot [options] [path to scene or 'project.godot' file]`

If I have a project located at `/home/me/MyGame`, I get the following results:

**Command:** `godot /home/me/MyGame/project.godot`
**Expected result:** The project should directly launch
**Actual result:** The editor launches with MyGame loaded (as if I had passed `-e`)

**Command:** `godot /home/me/MyGame/main.tscn`
**Expected result:** The main scene should directly launch
**Actual result:** The project manager is launched

**Command:** `godot --path /home/me/MyGame/`
**Expected result:** The project should directly launch
**Actual result:** Success!

**Command:** `cd /home/me/MyGame; godot project.godot`
**Expected result:** The project should directly launch
**Actual result:** The editor launches with MyGame loaded (as if I had passed `-e`)

**Command:** `cd /home/me/MyGame; godot main.tscn`
**Expected result:** The main scene should directly launch
**Actual result:** Success!

**Summary:**
- Launching a project directly with project.godot on the command line appears to be broken
- Launching a scene directly only works when your working directory is at the project root

### Steps to reproduce

Run the above test cases on any Godot project

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Changing any of these behaviors may be considered compatibility-breaking given how many people rely on the existing behavior for automation, but nonetheless:

> **Command:** godot /home/me/MyGame/project.godot
> **Expected result:** The project should directly launch
> **Actual result:** The editor launches with MyGame loaded (as if I had passed -e)

This is intended behavior, so that file assocations open the editor instead of running the project directly. This allows associating `.godot` files with Godot so you can double-click them to open a project in the editor, without going through the project manager.

> **Command:** godot /home/me/MyGame/main.tscn
> **Expected result:** The main scene should directly launch
> **Actual result:** The project manager is launched

This doesn't automatically scan upwards for a `project.godot` file (to avoid ambiguity when you have nested projects), so you must specify `--path /home/me/MyGame` in addition to the path to the `.tscn` file (which can be relative to the project root).

> **Command:** cd /home/me/MyGame; godot project.godot
> **Expected result:** The project should directly launch
> **Actual result:** The editor launches with MyGame loaded (as if I had passed -e)

Same as the first point I raised.

**Comment by Calinou** [comment]
> Unless this sounds off-base, I'll take this over to the godot-docs repo for some improvements.

Feel free to open a PR on godot-docs' `master` branch for this :slightly_smiling_face:
