### ISSUE TITLE
Godot 4.1.3 when creating global variable creates a node of global variable in created root node

### ISSUE THREAD

**Issue by VladislavBenich** [godotengine/godot#85786]
### Tested versions

Tested only on 1.4.3

### System information

Godot v4.1.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 27.20.15002.118) - AMD Ryzen 7 5700U with Radeon Graphics (16 Threads)

### Issue description

When I created global variable for my character scene I run debug and see 2 character but must be 1
The name of second (unneeded character) is just like global variable name and it was created in root scene with my main scene and unneeded character node
When I deleted global variable it worked fine

### Steps to reproduce

1) Create main and second scene as a child
2) Create global variable for child node
3) Look on "remote" nodes

### Minimal reproduction project (MRP)

[test-project.zip](https://github.com/godotengine/godot/files/13561352/test-project.zip)

**Comment by YuriSizov** [comment]
Please upload a minimal reproduction project.

**Comment by kleonc** [comment]
> When I created global variable for my character scene I run debug and see 2 character but must be 1

You've added an autoloaded script, hence this results in (auto)creating a node. This is intentional, expected, and documented. Quoting [the docs](https://docs.godotengine.org/en/4.2/tutorials/scripting/singletons_autoload.html#autoload):
>When autoloading a script, a [Node](https://docs.godotengine.org/en/4.2/classes/class_node.html#class-node) will be created and the script will be attached to it. This node will be added to the root viewport before any other scenes are loaded.

The second character is part of your main scene.

![u00bjOfZFi](https://github.com/godotengine/godot/assets/9283098/c7fbf5e9-2dd6-4f7a-af8b-55cf48cbbad3)


It works properly, no bug in here. Closing.
