### ISSUE TITLE
NavigationRegion2D doesn't take into account tiles with collision on other layers besides the first one

### ISSUE THREAD

**Issue by sotirissmix** [godotengine/godot#85798]
### Tested versions

Reproducible in 4.2.stable

### System information

Windows 11 - Godot v4.2.stable - Vulkan(Forward+/Mobile)

### Issue description

When using the NavigationRegion2D, the NavigationPolygon that is baked is incorrect.

### Steps to reproduce

1. Create a 2D scene
2. Add NavigationRegion2D
3. Add NavigationPolygon to NavigationRegion2D
4. Add TileMap (add a tileset, any will do as long as it has some tiles with PhysicsLayer painted in) child node to NavigationRegion2D
5. Add a second layer to the TileMap
6. Paint on first layer a region with tiles that have collision
7. Paint on the second layer a region with tiles that have collision
8. Bake NavigationPolygon

### Minimal reproduction project (MRP)

[TileMapNavTest.zip](https://github.com/godotengine/godot/files/13568676/TileMapNavTest.zip)

Just select the NavigationRegion2D and press Bake NavigationPolygon

**Comment by smix8** [comment]
That is an expected limitation of the TileMap. See e.g. https://github.com/godotengine/godot/issues/85588 and https://github.com/godotengine/godot/issues/83967 for more info / discussion.

**Comment by wareya** [comment]
I don't think this is an acceptable limitation.

If I have, for example, a base layer with ground tiles and unwalkable pits, and then another layer above that with fence tiles, it doesn't make sense to want to assemble navigation from only the collisions associated with the pits, ignoring the fences. This also makes it so that any colliding tiles need to be on the first layer; you can't dedicate it to background details, with the "game world" on the second layer. At the very least, it should be possible to explicitly request using multiple different physics layers when generating the navigation polygons in code.

The only workaround I can think of is using the first layer for invisible collision-only tiles, with none of the visible tiles having any physics information, which gives me bad Godot 3 flashbacks and is generally awful.

**Comment by smix8** [comment]
> I don't think this is an acceptable limitation.

I dont think so either but the ball is in the TileMap's court to fix this and lift the limitation by providing verified source geometry with non-conflicting polygons.

A lot of users already do the TileMap's job by adding the polygons to the source geometry object in scripts from their different layers. When users do this in scripts they know how they want and can mix and match their layers but no automation can read a users mind on this when not even the TIleMap knows.

**Comment by akien-mga** [comment]
Fixed by #85856.
