### ISSUE TITLE
VehicleWheel3D wheel_roll_influence documentation is wrong

### ISSUE THREAD

**Issue by thmasn** [godotengine/godot#85805]
### Tested versions

godot 4.1 and 4.2 stable
both integrated 3D physics, and Jolt physics

### System information

MacOs

### Issue description

the description and tooltip for `VehicleWheel3D.wheel_roll_influence` currently states:
`This value affects the roll of your vehicle. If set to 1.0 for all wheels, your vehicle will be prone to rolling over, while a value of 0.0 will resist body roll.`
but my testing seems to indicate the opposite is the case: a higher value results in less body roll.

i am unsure if:
A) the tooltip describes the desired behaviour, and the code creates a wrong result, or
B) the code is correct, and the tooltip is wrong.
the way physics work, i would assume that wheel_roll_influence is a multiplier of the gyroscopic force stabilizing a wheel when rotating, so my guess would be B). but since i cannot find the code handling this, i cannot confirm if this is it.

either way, it is a very confusing issue to have when starting to create vehicles in godot.

### Steps to reproduce

create a basic vehicle, then set the `wheel_roll_influence` to different values, and try out how the car handles.
it seems a low value makes the vehicle prone to rolling over, while a high value makes the vehicle more stable, and less likely to roll over.

### Minimal reproduction project (MRP)

see the minimal reproduction project:
[vehicleBodyTest 2.zip](https://github.com/godotengine/godot/files/13577619/vehicleBodyTest.2.zip)
[video of MRP](https://youtu.be/lP00s9nDl4Q)
- it includes a basic VehicleBody3D, with simple `arrow key` controls.
- the `wheel_roll_influence` can be changed by pressing the keys `1` and `2`.
- the `R` key will reset the car to the start.

**Comment by AThousandShips** [comment]
This is in the documentation, which the tooltip uses

**Comment by Zireael07** [comment]
IIRC (I'm the person who ported the relevant code from Bullet vehicle implementation) it's a plain multiplier, so the docs are wrong

**Comment by Zireael07** [comment]
I can't confirm or deny how it works - I haven't a clue, I just copied the relevant lines from the Bullet implementation

**Comment by thmasn** [comment]
in the [bullet docs](https://javadoc.jmonkeyengine.org/v3.5.0-beta4/com/jme3/bullet/objects/PhysicsVehicle.html)
the description of `setRollInfluence` is also a bit ambivalent:

> Reduces the rolling torque applied from the wheels that cause the vehicle to roll over. This is a bit of a hack, but it's quite effective. 0.0 = no roll, 1.0 = physical behaviour. If m_frictionSlip is too high, you'll need to reduce this to stop the vehicle rolling over. You should also try lowering the vehicle's centre of mass

> rollInfluence - the desired roll-influence factor (0→no roll torque, 1→realistic behavior, default=1)

i will try to make sense of the code and propose an edit of the documentation

**Comment by Tligtvoet** [comment]
Hi @thmasn, I did some digging into roll influence and this is my understanding. 
It seems to be that a higher roll_influence [set to 1.0] means that the wheel's resistance to lateral forces are stronger, thus making the vehicle more stable and less prone to body roll. Conversely, a lower roll_influence [set to 0.1] would mean less resistance to the lateral forces, which makes the vehicle more susceptible to rolling.

**Comment by qwofford** [comment]
> This is in the documentation, which the tooltip uses

I'm working on a PR for this. It appears that updating the xml default value does not also update the default in the editor GUI. I changed the XML default to 1.0, so that wheels will be more stable by default. However, when I build the editor and create a new default value, it still uses the old value of 0.1 (unstable wheel). Can you offer a hint as to how default values are consumed by the editor UI when a new VehicleWheel3D asset is initialized?

**Comment by AThousandShips** [comment]
You need to change the default in the code for the node, this is in `scene/3d/vehicle_body_3d.cpp`, changing the default value shouldn't be done though as it breaks compatibility, that's not part of this bug, that's something you need to open a [proposal](https://github.com/godotengine/godot-proposals) for changing that

**Comment by qwofford** [comment]
That makes sense. I will not attempt to change defaults in this PR. 

I'd like to follow up for the sake of learning. Although I will not propose changes to the defaults, I do have some confusion about how I would effectively change defaults, and how the changed defaults are appearing in documentation.

### Confusion 1, cont'd: Where are default values in Inspection window defined?
I see where the roll influence property getters and setters are defined and bound to the VehicleWheel3D class:
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/scene/3d/vehicle_body_3d.cpp#L284

But I do not see where default values are consumed. I found a merged PR that suggested, maybe, that default values are coming from the XML documentation itself: https://github.com/godotengine/godot/pull/29380. Specifically, I'm looking at the  `core/class_db.cpp` changes associated with this PR.

### Confusion 2: Troubleshooting incomplete documentation updates.
The changes I made to the VehicleWheel3D xml file have correctly updated the tooltip text. Thank you for that hint. Similarly, if I `make rst` in the `./doc` directory I can see the generated rst files do indeed update to show the text for this bug fix that I expected which include a default roll influence of 1.0 and the corrected descriptive text. However, not all of the documentation has updated.

When I build and open the editor, and open the example project provided (vehicleBodyTest), I can expand the Wheel property menus and see "Roll Influence" in the Inspector window. I can right click and select "Open Documentation" which opens new documentation in the Script window. Inside this script window I see this:
![Screenshot from 2023-12-31 11-42-36](https://github.com/godotengine/godot/assets/10124523/747d1246-b602-431e-a3b6-29362f0f17ec)
However, my VehicleWheel3D xml file looks like this:
![Screenshot from 2023-12-31 11-43-24](https://github.com/godotengine/godot/assets/10124523/e69fb78e-c7b4-4d12-841a-a6387506644d)
This is unexpected because the text in the first screenshot matches my changes, but the default setting does not.

I would like to understand where this "Open Documentation" content comes from. I see some hints that `get_singleton().goto_help()` might point me to the correct documentation, but I don't see where the `base_path` is set:
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/editor/editor_inspector.cpp#L951-L953

**Comment by AThousandShips** [comment]
My bad it's in the `.h` file, here:
https://github.com/godotengine/godot/blob/13a0d6e9b253654f5cc2a44f3d0b3cae10440443/scene/3d/vehicle_body_3d.h#L71

**Comment by AThousandShips** [comment]
Did you rebuild the editor?
