### ISSUE TITLE
Godot 4.2 is unable to preload resources that DO exist.

### ISSUE THREAD

**Issue by Bloxxel64** [godotengine/godot#85809]
### Tested versions

This issue did not occur before i upgraded to 4.2.

### System information

Linux Mint on GD 4.2 stable

### Issue description

When attempting to instantiate a scene through code, you first have to preload it, but for some reason godot is saying that it does not exist:

```
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	var roomnum = randi() % 3
	
	var rooms = [preload("res://scenes/rooms/emptyrooms/Empty1.tscn"), preload("res://scenes/rooms/emptyrooms/Empty1.tscn"), preload("res://scenes/rooms/emptyrooms/Empty3.tscn")]
	
	var dospawn = rooms[roomnum].instantiate()
	add_child(dospawn)
	print(roomnum)
```

![image](https://github.com/godotengine/godot/assets/70494679/48d87bcc-8489-4850-9cb8-7e3d573dacb4)

![image](https://github.com/godotengine/godot/assets/70494679/27512035-b359-48f1-ad3a-c5f07e2ee00c)

### Steps to reproduce

Download the project, open it, and debug run it.

### Minimal reproduction project (MRP)

[project.zip](https://github.com/godotengine/godot/files/13573892/project.zip)

**Comment by rsubtil** [comment]
The error message is really cryptic and unhelpful. It seems the issue is due to a loading cycle. On `base.tscn` you load the `inst.gd` script with loads that same scene:
```gdscript
extends Node2D


# Called when the node enters the scene tree for the first time.
func _ready():
	var baller = preload("res://base.tscn")
	add_child(baller)
```

If you comment/remove that `_ready` function, the scene loads normally again.

> This issue did not occur before i upgraded to 4.2.

Did you upgrade from any 4.x version, or earlier from 3.x?

**Comment by Bloxxel64** [comment]
> The error message is really cryptic and unhelpful. It seems the issue is due to a loading cycle. On `base.tscn` you load the `inst.gd` script with loads that same scene:
> 
im sorry im not really sure what details i need to provide.
> ```gdscript
> extends Node2D
> 
> 
> # Called when the node enters the scene tree for the first time.
> func _ready():
> 	var baller = preload("res://base.tscn")
> 	add_child(baller)
> ```
well im a dumbass, the code is incorrect.
> 
> If you comment/remove that `_ready` function, the scene loads normally again.
ill... try that...

**Comment by rsubtil** [comment]
> im sorry im not really sure what details i need to provide.

I meant that the error Godot gives is not clear; it wasn't about your report :slightly_smiling_face:

I don't know if your scenario is supposed to work or not, but since you mentioned that it has happened since you ported this code to 4.2, this might be a regression. What was the previous Godot version you were using?

**Comment by Bloxxel64** [comment]
> > im sorry im not really sure what details i need to provide.
> 
> I meant that the error Godot gives is not clear; it wasn't about your report 🙂
> 
> I don't know if your scenario is supposed to work or not, but since you mentioned that it has happened since you ported this code to 4.2, this might be a regression. What was the previous Godot version you were using?

the project is only from 4.1, but i only got errors when i upgraded to 4.2, incidentally. sometimes godot will say the scenes are corrupted when i try to open them for some reason

**Comment by francescarpi** [comment]
Hi.

I've got the same issue on _v4.2.stable.official [46dc27791]_

With the "preload" line, an error raises when Godot starting. Line 140 of "bug.tscn" references the "bug.gd" script. 

<img width="991" alt="image" src="https://github.com/godotengine/godot/assets/287872/5407c148-ef26-4e50-a078-ae0900ebbb41">

If I comment the line, error message disappear.

**Comment by francescarpi** [comment]
Changing `preload` for `load` works well. Seen in this other reported issue 
 
https://github.com/godotengine/godot/issues/85081#issuecomment-1847899547

**Comment by WhalesState** [comment]
Using the MRP, I have found that you are preloading `base.tscn` inside `base.tscn` and adding it as a child without instantiating it.

from the variable name i think you just wants to add the other scene `ball.tscn` to the `base.tscn` as a child, so this code should work fine without raising any issues.

Update the `inst.gd` script and reload the project from `Project` menu.

```gdscript
func _ready():
	var baller = preload("res://ball.tscn").instantiate()
	add_child(baller)
```

If I'm wrong and you want to preload the same scene inside itself, then you can try other methods like `self.duplicate()` for example, since the packed scene is already loaded.
