### ISSUE TITLE
Linear keyframe interpolation not working for Control anchor offsets

### ISSUE THREAD

**Issue by estroBiologist** [godotengine/godot#85858]
### Tested versions

- Reproducible in: v4.2.stable.official [46dc27791]
- Not reproducible in: v4.1.3.stable

### System information

Godot v4.2.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (Advanced Micro Devices, Inc.; 31.0.21023.2010) - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

Starting with Godot 4.2, changing a Control node's anchor offsets with an AnimationPlayer node results in the offsets "snapping" to the keyframes, as if Nearest interpolation were used. 

This only applies to the Linear Interpolation Mode; Cubic still works as expected.

![resize_interp_fail](https://github.com/godotengine/godot/assets/26508550/a10a973f-afdc-45f2-986c-594aa3cdc9dc)

I encountered this regression when upgrading my project from 4.1.3 to 4.2. Minimum reproduction project provided below.

### Steps to reproduce

- Create a Control node with a Custom anchor preset.
- Create an AnimationPlayer track for one or more of its anchor offsets, with the Continuous update mode and Linear interpolation.
- Add keyframes to track(s)
- Play animation (either in the editor or in-game)

### Minimal reproduction project (MRP)

[ControlResize.zip](https://github.com/godotengine/godot/files/13589517/ControlResize.zip)

**Comment by bs-mwoerner** [comment]
The linear interpolation refuses to interpolate between the two keys because one is a float and the other is an integer.
```
tracks/1/keys = {
"times": PackedFloat32Array(0, 0.5),
"transitions": PackedFloat32Array(1, 1),
"update": 0,
"values": [0.0, -50]
}
```
So the questions that come to mind are:
1. How did this happen?
2. Should the linear interpolation be more lenient when asked to interpolate between scalar values that require a type cast?

Do you remember how you created that animation? Did you, for example, animate the anchors first and then change the tracks to offset?

In any case, you can fix this particular animation by selecting the two keyframes on the left and changing their value to 1 and back to 0. This will set them to an integer 0 and the linear interpolation will be happy.
