### ISSUE TITLE
Node.set_owner is shallow

### ISSUE THREAD

**Issue by CrazyGuy108** [godotengine/godot#8598]
**Operating system or device - Godot version:**
Ubuntu 16.04 on an amd64, Godot 2.1.3 stable.

**Issue description:**

I'm trying to make a tool script that doesn't just create a new node, but also a second node as a child of the first one. When I run this script, only the first node is created, not the second node.
**EDIT:** after looking at other examples like tilesethelper, I found out that this doesn't work because `Node.set_owner` is shallow and doesn't account for an ownership hierarchy.

**Steps to reproduce:**
1. Create a Node, which I will call `test` for reference.
2. Add the following script to it:
```
tool
extends Node

export(bool) var reset = false setget _on_reset

func _on_reset(value):
	if (value):
		reset = false
		for child in get_children():
			child.free()
		var new_node = Node.new()
		add_child(new_node)
		new_node.set_owner(self)
		new_node.set_name("new_node")
		var new_sprite = Sprite.new()
		new_node.add_child(new_sprite)
		new_sprite.set_owner(new_node)
		new_sprite.set_name("new_sprite")
		new_sprite.set_texture(preload("res://icon.png")) # or whatever image you want
```
3. Click the `Reset` checkbox to run the script. In the scene tree you can see that `new_node` was created but it doesn't have a child called `new_sprite`. However, in the editor viewport (not when playing the scene), the sprite is being drawn on the screen!

**Link to minimal example project:**

[tool-script-can't-create-a-node-hierarchy.zip](https://github.com/godotengine/godot/files/967027/tool-script-can.t-create-a-node-hierarchy.zip)

**Comment by bojidar-bg** [comment]
I think you are mistaking how `set_owner` works. It is not the same as `set_parent`. Here is an example:
```go
[main.tscn]
- A : Node(parent = null, owner = null)
  - B : Node(parent = A, owner = A)
    - C : Node(parent = B, owner = A)
  - D : Node(parent = A, owner = A, scene = PackedScene("sub.tscn"))
    - E : Node(parent = D, owner = D)
       - F : Node(parent = E, owner = D)
[sub.tscn]
- D : Node(parent = null, owner = null)
  - E : Node(parent = D, owner = D)
     - F : Node(parent = E, owner = D)
```
When the editor attempts to save `main.tscn`, it would get it's root node (A), and then go through all children which have it as their "owner" (B, C, D), and then serialise those along with the root to a scene.

What you are doing works only because `self` is the scene's root, and thus the first `set_owner` makes a "normal" node. But, when you set the `new_sprite`'s owner to `new_node`, it considers `new_sprite` as something which is not "owned" by the _scene_, and therefore, not something to be saved in the scene.

**Comment by CrazyGuy108** [comment]
I see, thanks for clarifying that. I did `new_sprite.set_owner(self)` and it worked.
