### ISSUE TITLE
Memory leak when rendering Skeleton3D

### ISSUE THREAD

**Issue by Ragueel** [godotengine/godot#85998]
### Tested versions

- Reproducible in 4.2 stable
- Not reproducible in 4.2.1-rc

### System information

Godot v4.2.stable.mono - Windows 11 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3699) - AMD Ryzen 7 3800X 8-Core Processor (16 Threads)

### Issue description

Whenever a Camera3D renders a Skeleton3D with animations memory seems to grow.

![image](https://github.com/godotengine/godot/assets/28916549/6d2dbb64-409a-4a41-830e-dd522fee6e8a)

Project structure:

![image](https://github.com/godotengine/godot/assets/28916549/a454e470-295f-4216-9239-4be375070091)

The issue also happens inside the editor, which means whenever the editor is rendering a Skeleton3D it also leaks memory.

### Steps to reproduce

- Clone the project
- Open the project with 4.2.stable
- Run the project
- Open the Debugger->Monitors
- Observer the memory leak 

### Minimal reproduction project (MRP)

Example project:

[https://github.com/Ragueel/godot_bug_sample_project](https://github.com/Ragueel/godot_bug_sample_project)

**Comment by bitsawer** [comment]
Seems to be fixed in 4.2.1 rc1 as the edit in the main post also mentions. I also tested on current master at b94eb58d35b3dd8a9f522bc90df0db73862ef326 and this seems fixed. For posterity it might be interesting to bisect which commit fixed this (and see if it was an animation or rendering issue), but it is not required. Closing as completed.
