### ISSUE TITLE
Custom editor theme paths (how to install editor themes)

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8605]
I'm always having issues installing custom themes. I don't know if I'm doing something wrong or if installing is just really cumbersome.
A theme created in the editor has res:// paths to the resources (images) it uses. when I set a custom editor theme the resources are only there if they are part of the current project I'm working on...
OR
if I adapt every singe url in the theme file... (that works with a install script but I just want to choose the theme and it should work!!)

*feature I'm asking for*
It would be nice if the exported themes would allow for relative paths so I can package them into a Folder and the editor would find the theme png's for every project!

Another cool approach would be to save themes as packaged files with all the recources in it. Than the packed folder could be read loaded as the theme and shared. (again with relative paths in the theme file)

**Comment by ArcFutahito** [comment]
I second that.

**Comment by Zephilinox** [comment]
have you tried editing the theme file directly and modifying the paths? if that works then it's just a matter of the file dialog not allowing you to do it

**Comment by ArcFutahito** [comment]
The problem with icons is that you gotta do them either in res:// (which means you gotta put it in every res://) or provide absolute path in the system (which is OS dependent), otherwise it won't work.

Having theme:// point to somewhere like .godot/themes/%current_active_theme% would be so damn good.

**Comment by Zephilinox** [comment]
have you tried user://

**Comment by ArcFutahito** [comment]
Oh... Ohh @toger5 I think I didn't. Completely forgot it even exists. That might be actually a thing.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
