### ISSUE TITLE
Multiple Custom Themes

### ISSUE THREAD

**Issue by toger5** [godotengine/godot#8606]
Disclaimer: This is really low priority.

Allowing for stacking themes would be really nice to use a custom theme and override the styles where  users are not satisfied with. or keeping one personal preference (the same background color than your oparating systems window color...) always as the top of the stack and switching theme from time to time

**Comment by Zephilinox** [comment]
@riirii mentioned something about a theme manager, and after the few changes I had to make it doesn't seem infeasible to have the ability to switch out diffetent built in themes (though I'm not sure about reloading the theme without restarting).

I'm not sure I understand why being able to stack themes makes sense though when you can already partially change the editor theme yourself? Unless I misunderstood

**Comment by reduz** [comment]
This is already supported, you can make a theme that overrides something
from the default one but not all

**Comment by toger5** [comment]
I'm proposing multiple themes stacked. So I can select multiple custom themes and their priority:

example:
myBgTheme: just has a style box to override the background to the color of my window of the operating system.
myFavoriteCustomTheme: has almost all style boxes
defaultTheme: just provides everything missing mostly the icons.

**Comment by eon-s** [comment]
You mean like different levels of fallback themes?

**Comment by Zylann** [comment]
Making a theme should be as simple as creating one in Godot in a folder for a game, then be able to share this folder/package to anyone to install easily without relying on extra tools (currently it's in user:// I think?). Yes, it requires download, but if it's just about putting files in a folder it's really easy (just like anyone can change how a Linux env is themed by browsing a gallery / aka assetlib). Then a user can choose using the file chooser in the editor settings.

Making a theme is a lot more than just editing PNGs though (if you do, I hope you have time for it), because you could have SVGs to convert so that your theme supports HiDPI. I don't know how .tres themes support that, but it should be possible to have easy-to-use tools for theme creation, because while Godot's theme editor does its job at assigning what-goes-where, it doesn't cover the part where people actually draw the UI.

Imagine it could be like a tool opening one SVG file with all elements in it, in a sort of mosaic so you don't mess with thousand files one by one.
Elements would share some variables like CSS so changing main colors is easy (does SVG support that?). Then one can disable some elements (like icons or some buttons, needs to categorize stuff) to keep the default ones, or adjust others, and be able to click on a button that exports all PNGs in all sizes and generates the appropriate .TRES file. Such a tool doesn't need to be in Godot, I don't believe Godot needs to change about this, it just supports "custom theme" to override default, that's all. 
A creation tool rather than raw image editing would make theme creation a lot easier and faster for average users. Now maybe such a tool supporting all this exists, maybe it's called Inkscape^^

**Comment by toger5** [comment]
@Dillybob92 yea the stacking itself is supported. But im not talking about themea fpr projexts, instead i mean themes for the editor.
Its not really a core change, i just want an option to add another (so in total two coustom themes) theme to override some of the editor styles.

**Comment by Zylann** [comment]
@toger5 themes for the editor are the same as themes for games. The only difference is how you tell it to load yours. I mean, you can litterally create a .tres theme only changing a few bits, then load it in the editor, and will override only what you need. If it's about background color, however, you'll have to change more than just a "color" field because that's just how it works, all backgrounds are textures.

**Comment by toger5** [comment]
@Zylann Yea you are right. they are almost the same. but what I'm asking for is something different.
The support for adding ONE custom theme which than overrides some styles is there. But I want TWO or more custom themes so ppl can use one created by the community and add their own theme (with only a couple of style changes) on top of that. Sorry if I didn't made it obvious what I'm asking for.

In terms of implementation I want the custom theme settings property to be a list which than override each other where they have style boxes. The idea being: coustomTheme, some changes to icons (in another theme because I really like them), New icons for nodes because I prefer them to be black white, another really small theme which just fixes input fields to be round instead of squared because that is not the case in my favourite custom theme...
 

There is actually a slight difference between editor theme and "normal" .tres themes for games. The editor theme can include editor specific thinks too. after volzh's update for example there is a new style box for the main view "EditorStyle" "EditorPanel" (I think). And you can change every single icon in an editor theme.

**Comment by Calinou** [comment]
I'll close this due to the lack of clear use cases. Please [open a proposal](https://github.com/godotengine/godot-proposals) if you still feel a need for this feature.
