### ISSUE TITLE
[Usablility] Add support for tooltip to have `stay on hover` ability

### ISSUE THREAD

**Issue by jsjtxietian** [godotengine/godot#86110]
### Tested versions

Current master.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3619) - 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 Threads)

### Issue description

I would be nice if I can hover over the tooltip to read it, click the link on it, especially for long descriptions.

For example, when I hover over reflectionprobe's update mode, I see something in the tooltip that I'm interested in and want to click that to learn more, but now it's not possbile to do so. I do realize that I can right click on the property and enter the doc there but that's a little unintuitive compared to my suggestion.

<img width="542" alt="8aed92f74eaaa285bb8bd145a4f39bac" src="https://github.com/godotengine/godot/assets/8315986/6dde048e-823c-4b03-bf97-e2373806a52d">

I did a quick search and did not find any similar proposal, but I might be careless, if there's similar ones feel free to close this one :)

### Steps to reproduce

Open any inspector and hover on the property to see the tooltip, move your mouse to the tooltip, notice that the tooltip disappears as soon as the mouse leaves the property area.

### Minimal reproduction project (MRP)

N/A

**Comment by Kakiroi** [comment]
With this, we can perhaps get nested tool tip too. 
For this to work properly, tool tip popup panel must have mouse pass through size bigger than panel itself. But problem is, since the popup panel consumes the mouse input, it triggers mouse exit on the control node you were originally hovering(which frees tool tip panel). Obviously you can't just set popup panel to not take mouse input, since then you can't interact with the tool tip. So maybe we should find a way to sync input area between hovering control node and all the tool tip panel. Maybe it can check whether the mouse point is within combined rects of all children, but not sure popup panel and control node works well on this situation. 
Another thing is how much offset vector does it consider when spawning tool tip. Perhaps on some situation, the offset might be too high for mouse to reach without triggering mouse exit on hovering node. Either this should be configurable on project setting, or have virtual method which user can pass vector length.

**Comment by AThousandShips** [comment]
I agree with this feature, but feature proposals belong [here](https://github.com/godotengine/godot-proposals) please open one there instead 🙂

**Comment by Calinou** [comment]
There's already an open discussion: https://github.com/godotengine/godot-proposals/discussions/7679
