### ISSUE TITLE
Wrong display order of meshes with alpha and vertex positions modified

### ISSUE THREAD

**Issue by ABEC-projects** [godotengine/godot#86124]
### Tested versions

4.2.1

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) and  Forward Mobile- integrated Intel(R) UHD Graphics 630 (Intel Corporation; 31.0.101.2125) - Intel(R) Core(TM) i5-9400T CPU @ 1.80GHz (6 Threads)

### Issue description

I tried making shell grass using some plane Mesh Instance 3d. I spawned them with the same transform and changed their height using shader and instance uniform. I also made meshes with lower height have darker color, so it's more obvious which layer is which, and made some parts of mesh look transparent. But when I instantiate and add these meshes to node tree in all at once, the lowest of these, which should mostly be covered, is actually visible. This happens if followed conditions are not met: ALPHA should be modified, original planes should overlap or be very close to each other (about 0.00000001m). It's also more noticeable when all of meshes were created at the same time but can still appear without this condition if there's enough meshes. And the last note, if you turn visibility of some top layers off and on, bottom layers starts displaying normally.
![image](https://github.com/godotengine/godot/assets/70073993/2577944f-0094-4c4b-ba22-167da2559fc1)

https://github.com/godotengine/godot/assets/70073993/d5345a3b-01c9-4b5b-aeac-7ad4d4e44468

### Steps to reproduce

*Create a ``MeshInstance3D`` scene
*Add a ``ShaderMaterial`` to this ``MeshInstance3D`` (in my case it's plane, i have not tested it with other meshes forms)
*Make this shader modify ``ALPHA `` somehow (``ALPHA`` = 1. also works), set every vertex positions to a ``instance uniform`` and color (you need to modify color to distinguish one plane from another).
*Make some copies of this scene in the same place with slightly different ``instance uniform``
*Set up a camera and run project

### Minimal reproduction project (MRP)

[AlphaBug.zip](https://github.com/godotengine/godot/files/13663531/AlphaBug.zip)

**Comment by ABEC-projects** [comment]
This is the first time I opened an issue on github and I'm quiet new to godot, so I hope I explained everything right.

**Comment by clayjohn** [comment]
Welcome to the wild world of 3D graphics! You are running into the limitations of transparent object rendering. 

We have a helpful section in the docs that explains the limitations of using transparency (i.e. writing to ALPHA):
https://docs.godotengine.org/en/latest/tutorials/3d/3d_rendering_limitations.html#transparency-sorting

Transparent objects need to be drawn in back-to-front order so that further transparent objects can be visible through closer transparent objects. This sorting happens on the CPU and it is based on the transform of the MeshInstance3D. In most cases this works quite well and you don't notice anything at all. But in some cases it fails. This is a case where it fails. 

Because you are setting the objects position in the shader, the CPU has no knowledge of what order to draw the meshes in. It ends up drawing them in the order it receives them. From the perspective of the engine, all the layers are at the same position, so it doesn't matter which is drawn first. 

To correct transparency sorting issues, you have a few options:
1. Don't use transparency: in this case, alpha is always 1.0, so there is no reason to use it at all.
2. Modify the position of the MeshInstance3D instead of shifting the vertices in the vertex shader. 
3. If you _have_ to use transparency and can't assign the position to each MeshInstance3D, then you can also use [``render_priority``](https://docs.godotengine.org/en/latest/classes/class_material.html#class-material-property-render-priority) or the [``sorting_offset``](https://docs.godotengine.org/en/latest/classes/class_visualinstance3d.html#class-visualinstance3d-property-sorting-offset). ``render_priority`` tells the renderer what absolute order to render transparent objects in (i.e. object A should always be rendered before object B). ``sorting_offset`` tricks the renderer into thinking an object is closer or further away and can be used to tweak the results of sorting to ensure that certain objects are treated as being closer or further than other objects.

**Comment by ABEC-projects** [comment]
@clayjohn Thanks for the explanation. This was just an example, in my project I actually wanted to make some parts of this plains transparent. But I actually found out about ``discard`` keyword like 30 minutes ago. I think I should actually reading docs before diving into something)
P.S. This is what I was trying to make
![image](https://github.com/godotengine/godot/assets/70073993/8b4041ef-7e87-4804-a51c-a3af4995f81f)
