### ISSUE TITLE
Mirrored UVs break normal mapping

### ISSUE THREAD

**Issue by Arnklit** [godotengine/godot#86131]
### Tested versions

Reproducible in 4.2.1

### System information

Windows 11, Vulkan, Forward+

### Issue description

Having mirrored UVs break normal mapping. I would expect Godot to correctly take mirrored UVs into account like other 3d software does. Not only does it not do that. it creates some very strange normal artifacts in the middle of polygons that I can't explain.

Here is a cube that has been mirrored and had an open gl normal map with a "bump" sphere shape applied to it in Blender:

Model:
![image](https://github.com/godotengine/godot/assets/4955051/5e7ced96-f22d-4c06-9ae1-0ae4864c8acd)

With mirror modifier:
![image](https://github.com/godotengine/godot/assets/4955051/d066f922-fa7d-47fe-b78b-edb582846c59)

Normals work as expected:
https://github.com/godotengine/godot/assets/4955051/9b4a85bc-8656-4f7d-b9ec-d590dc0e1822

Here the box is imported as gltf into Godot:
https://github.com/godotengine/godot/assets/4955051/384aafbb-9760-4a66-968d-9b3bc014ca6c

As you can see the normals are not acting correctly when mirrored and there is for some reaons a strange artifact running down the middle of a polygon where no edge exist.
![image](https://github.com/godotengine/godot/assets/4955051/919f07b1-2f34-46f2-91a5-75289eacf645)
![image](https://github.com/godotengine/godot/assets/4955051/f6d0ef5f-56d1-43f0-a6d7-9fddd26ec146)

### Steps to reproduce

Open the MRP and observe the issue.

### Minimal reproduction project (MRP)

[mirror_uv_normalmap_issue.zip](https://github.com/godotengine/godot/files/13665636/mirror_uv_normalmap_issue.zip)

**Comment by clayjohn** [comment]
It looks like you are relying on Godot to generate the tangents with this model. 

Have you tried exporting from blender with tangents included? Blender removes tangents by default. 

The trouble here is that to generate tangents from an existing normal-mapped image, you need to rely on the UVs, but if the UVs behave in an unexpected way, then the thirdparty lib we rely on to generate tangents breaks down. 

When doing normal mapping, you should always use the tangents from your 3DCC instead of relying on Godot to generate them at import time.

**Comment by Arnklit** [comment]
So importing the tangents, does make the weird error in the middle of the polygon clear, but the normals are still incorrect.
https://github.com/godotengine/godot/assets/4955051/96e3b8d5-1fbe-4fed-a9b0-a58438ec7971

**Comment by Arnklit** [comment]
copy of the project where the gltf has tangents included.
[mirror_uv_normalmap_issue2.zip](https://github.com/godotengine/godot/files/13665788/mirror_uv_normalmap_issue2.zip)

**Comment by clayjohn** [comment]
I'm still thinking this is an export issue rather than an import issue. 

Here are the tangents visualized from the new test scene:

![image](https://github.com/godotengine/godot/assets/16521339/e317b7d9-b683-4879-8a9e-bed0250a2b09)

And the UVs:
![Screenshot from 2023-12-13 15-04-16](https://github.com/godotengine/godot/assets/16521339/049c2e34-2632-4420-b4b9-735539ae3b5b)

Notice how the UVs are continuous, but the tangents are not? Its clear that the tangents are causing the normal map to get flipped (because that's what tangents do). 

I guess we need to see if other engines load this model more successfully or not. Its tough to test as the GLB doesn't include normal mapping. I'll see if I can find something to load it into

**Comment by Arnklit** [comment]
I'll try and do some additional testing as well tomorrow.

**Comment by Arnklit** [comment]
Here is another example that I would expect to work that is maybe a bit clearer.
I sculpted some symetrical detail into the blender monkey and baked the detail onto a low res model. 
On the model on right I deleted half the model and mirrored it. This could make a lot of sense in a game asset with a symetrical model so I only use half the texture space. As you can see this works as expected in Blender.
![image](https://github.com/godotengine/godot/assets/4955051/6712de9c-7583-4067-86d8-7bc171a628e5)

In Godot it breaks even when I include the tangents.
![image](https://github.com/godotengine/godot/assets/4955051/bfffe109-894f-4f85-945e-c477495dab5c)
https://github.com/godotengine/godot/assets/4955051/5bdaae43-79cb-42d4-ac06-252949df97c7

Here is the model. it has the texture embedded so it should load right up in Godot.
[mirror_suzanne.zip](https://github.com/godotengine/godot/files/13671300/mirror_suzanne.zip)

I'll try and test it in another engine now.

**Comment by Arnklit** [comment]
Here is a screenshot from Unity using this model. As you can see it handles the mirrored uvs correctly. 
![image](https://github.com/godotengine/godot/assets/4955051/1fbd29b8-eca7-4224-af08-88a75664bb29)

**Comment by Arnklit** [comment]
I just did another test with .obj and there the normal map looks fine on the mirrored uvs. So this appears to be an issue with the gltf import.

**Comment by clayjohn** [comment]
I tested the second GLB cube in the Threejs online editor and it appeared to render correctly. So this is likely something in our importer. It could be a combination issue with our importer and Blender's exporter, but if it works in ThreeJS, it should work in Godot.

**Comment by fire** [comment]
I wonder what happens when we export glb and compare it in blender.

**Comment by lyuma** [comment]
Is this related to the `w` component of the tangent vector?

**Comment by clayjohn** [comment]
> Is this related to the `w` component of the tangent vector?

It could be. But AFAIK we handle it correctly (according to the GLTF spec)

**Comment by Calinou** [comment]
Additional MRP by @stanleysweet: https://github.com/godotengine/godot/files/13932776/materials.zip

**Comment by donmccurdy** [comment]
Note that there are two official glTF sample models meant for testing this situation:

- https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/NormalTangentTest
- https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/NormalTangentMirrorTest

Might be worth checking those, to isolate whether the issue is Blender-related or Godot-specific.

**Comment by Arnklit** [comment]
Ah that's great @donmccurdy . I didn't really know how to proceed with this. I'll test those and report back.

**Comment by Arnklit** [comment]
Thanks @StanleySweet ... well that seems pretty definitively wrong.

**Comment by clayjohn** [comment]
The same GLTF looks correct in 3.5.3

![Screenshot from 2024-01-15 09-09-31](https://github.com/godotengine/godot/assets/16521339/25459f37-b835-4c35-9f95-b3616c26b1d2)

The GLTF page indicates that this could be an issue with flipping the y-channel https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/NormalTangentMirrorTest#problem-flipped-y-axis-or-flipped-green-channel

But we have an import setting for that and it doesn't appear to fully resolve the issue either.

**Comment by StanleySweet** [comment]
> Thanks @StanleySweet ... well that seems pretty definitively wrong.

Indeed.

>  But we have an import setting for that and it doesn't appear to fully resolve the issue either.

Indeed. Was there any commits affecting the computation in 4 ? Maybe it's correct for OpenGL but not Vulkan?

**Comment by clayjohn** [comment]
> > Thanks @StanleySweet ... well that seems pretty definitively wrong.
> 
> Indeed.
> 
> > But we have an import setting for that and it doesn't appear to fully resolve the issue either.
> 
> Indeed. Was there any commits affecting the computation in 4 ? Maybe it's correct for OpenGL but not Vulkan?

The shader code appears to be the same between all backends in 4.x and 3.x. So this is most likely a texture import issue (or a mesh import issue with the tangents)

Oddly enough, flipping the y channel is enough to fix the v mirror a u mirror cases, but it breaks the "normal" case

**Comment by StanleySweet** [comment]
So maybe the tangent computing code was changed ?

**Comment by jitspoe** [comment]
So I also had this issue, which I posted about here: https://github.com/godotengine/godot/issues/71221#issuecomment-1893056645

and I was able to resolve it by force disabling compression on the mesh import.  The weird thing is I have a lot of meshes that are mirrored that don't have this issue, so I don't have to always disable compression.

**Comment by StanleySweet** [comment]
@jitspoe can you take a screenshot ? I couldn't find the option? Maybe it's different between `*.glb` and `*.gltf`

**Comment by Arnklit** [comment]
I assume it's this one.
![image](https://github.com/godotengine/godot/assets/4955051/862255fc-6d30-4719-8cec-ceb9c077d29e)

**Comment by jitspoe** [comment]
Yeah, that's the one.  Try checking that "Force Disable Compression" and disabling the export of tangents on the gltf file.  In the past I've had broken tangents with the blender exporter and disabling them and using the "Ensure Tangents" on import seemed to fix it.
![image](https://github.com/godotengine/godot/assets/7751182/6ad342f0-ba13-4749-bdbc-d9ea9c44b887)

Actually, seems that's off by default and you might have already tried it.  What version of blender are you using, by the way?

**Comment by Arnklit** [comment]
it makes no difference at all in my tests to force disable the compression. Neither with exported tangents or without. I'm using latest Blender 4.0.2.

**Comment by StanleySweet** [comment]
Same 4.0.2 as well and turning it off an on again didn't change anything. Also I would assume the GLTF files from the Khronos group would be okay ?

**Comment by jitspoe** [comment]
Yeah, fair.  Wonder why it fixed the issue for me.  Also, based on https://github.com/godotengine/godot/issues/71221, it might not be specific to mirrored UV's, especially since it doesn't seem to consistently happen on mirrored UV's.  I also had a bizarre issue with a skeletal mesh where the normals would flip while animating: https://github.com/godotengine/godot/issues/81446 so it might not even be an import/export thing, but something that happens at render time, though I suspect that also had something to do with compression.  I wonder if somewhere, some code is trying to do a cross product with 2 vectors that are facing the same way and it just picks an arbitrary direction for the tangent or binormal...

**Comment by StanleySweet** [comment]
I haven't tested if it happens on OBJ files as well. Not having normal maps is kind of a deal breaker --'

**Comment by jitspoe** [comment]
So I took the suzanne mirrored gltf file, imported it into blender, then put that .blend file in the godot project and disabled the tangent on import (which disables it on gltf export) and enabled force disable compression, and it seems to have imported correctly.

(Grey is the gltf file, white is the blender import):

![image](https://github.com/godotengine/godot/assets/7751182/05fca3ae-8f8d-4004-9b98-c96e9c462177)

And this is with tangents on for the blender file:

![image](https://github.com/godotengine/godot/assets/7751182/fd26a78c-116f-4770-b1a6-6e0c30af2d77)

So it seems it's definitely broken importing gltf files with tangents.  I'm guessing there might be a coordinate system conversion issue, like Y up vs Z up type of thing for the tangents, maybe?

**Comment by donmccurdy** [comment]
Possibly a relevant discussion in three.js here:

https://github.com/mrdoob/three.js/issues/11438#issuecomment-507003995

When loading glTF files _without_ vertex tangents, we flip the Y component of the normal scale. When loading glTF files _with_ vertex tangents, this step is skipped.

https://github.com/mrdoob/three.js/blob/b031efee9a5304854c843d2d242cf07e38630f1f/examples/jsm/loaders/GLTFLoader.js#L3403-L3409

**Comment by StanleySweet** [comment]
Any pointers to where the code handling that is in godot ?

**Comment by jitspoe** [comment]
I think this might be more than just a gltf import issue.  I have my own custom BSP importer that I wrote which creates meshes with SurfaceTool, and I simply call `surf_tool.generate_tangents()`.  I had some textures with inverted normals, fliped the UV's, reimported, and it fixed them.  Since disabling compression fixed the issue with the other imports, I was trying to figure out how to disable compression with the SurfTool.  The compression flags passed in are 0, which seems to be no compression?  I'm not entirely sure, though.  Would be interesting if disabling compression fixed it if it's enabled.

**Comment by StanleySweet** [comment]
I tried to Force disable compression with the meshes provided by the Khronos group but it doesn't fix the issue at all.


I also get this warning when not exporting GLTF tangents:

```
servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp:3725 - Attempting to use a shader that requires tangents with a mesh that doesn't contain tangents. 
Ensure that meshes are imported with the 'ensure_tangents' option. 
If creating your own meshes, add an `ARRAY_TANGENT` array (when using ArrayMesh) or call `generate_tangents()` (when using SurfaceTool). (User)
```

**Comment by jitspoe** [comment]
Right, if the gltf file has tangents in it, Godot will use those (but it seems there is an inversion issue with mirrored UVs).  You have to export a GLTF file without tangents *and* disable the compression.

**Comment by StanleySweet** [comment]
Then I get a warning about the mesh having no tangents and the normals are still inside out :/

**Comment by jitspoe** [comment]
Did you enable ensure tangents on import?

**Comment by StanleySweet** [comment]
Didn't check. Will try again today and let you know :)

**Comment by StanleySweet** [comment]
Okay so I tested this a bit more. In all cases Ensure tangents is enabled.

Export from Blender with no tangents => Broken in Godot
Export from Blender with no tangents => Disable Compression in Godot => Works in Godot

Export from Blender with tangents => Broken in Godot
Export from Blender with tangents => Disable Compression in Godot => Broken in Godot
