### ISSUE TITLE
Pack Mode: Pack into archive file (*.zip) --> Add support for password protection?

### ISSUE THREAD

**Issue by supercom32** [godotengine/godot#8614]
Hi Everyone,

I noted that in the "Pack Mode" options for exporting a project, you can choose "Pack into archive file (.zip)" as one of the targets. Would it be possible to add password protection as well to this archive as a feature? The reason being, it would be helpful in deterring cheaters, modders, etc. 

I suppose the "Pack into executable" and "Pack into binary file (.pck)" option provide slightly better protection against cheaters and moddification, but I'm not sure by how much? Probably still better than a standard ZIP file which can be opened and tampered with via any modern archive program?

**Comment by Zephilinox** [comment]
there's an encryption option, though you need to compile godot from source to use it. A password for a zip  sounds nice

**Comment by supercom32** [comment]
Yep, you can indeed encrypt your GDScript if you re-compile godot. Too bad there isn't an easier way to do this that wouldn't require compiling it. 

As for the password protected ZIP feature, I'm sure we're all aware that you won't stop a determined individual from getting what he/she wants. However, being able to distribute something that would at least stop script-kiddies would be pretty neat indeed!

**Comment by vnen** [comment]
How and where would the password be stored so the executable can play the game?

**Comment by supercom32** [comment]
This idea is just off-the-cuff, but I assume if "load_resource_pack" could accept a password argument, you'd just provide it there. And in turn, your GDScript would be encrypted, so it wouldn't be trivial for someone to look at it. Or, perhaps the key could simply be the one you provide when you compile Godot, so the same key that is used to encrypt your GDScript is used for opening any ZIP archive containers?

**Comment by ArcFutahito** [comment]
I'm pretty sure you'd be able to log the password when unpacking if this would be the case.

**Comment by supercom32** [comment]
Ah, I suppose you could run everything in a VM and watch for the key to appear when it gets revealed in memory, but by that point you've already achieved your objective. That is, you've stopped the average Joe-nobody (who only knows how to use an off-the-shelf, do-it-all-for-you, tool) from modifying or editing your files. 

It's like compiling your own version and encrypting your GDScripts (which you can currently do). The key has to come with the treasure chest, so anyone smart enough will be able to snuff  it out. It's just a matter of making it hard enough that the average users can't do it, and those who can, likely won't care.

**Comment by ArcFutahito** [comment]
Yeah, some basic scum repellent would be indeed nice. I'm pretty sure it would still create a single point of failure but that can probably be somewhat mitigated by several compression algorithms

**Comment by eon-s** [comment]
What about some way to detect package integrity? a checksum, signature.
Maybe some of this may need a custom module or via GDNative.

**Comment by supercom32** [comment]
Some kind of built in integrity check would be awesome. Though I must admit, I still like the idea of having some kind of basic asset protection to complement it. Even if it the protection was simple, as long as it's unique enough (per application) that you couldn't just go "Ah, it's just a proprietary packing format. Just read the file specs from the repos and write an unpacker", that would be good. 

That's why I suggested password protected ZIP, since even if the file format is known the password could be personalized and could act as a simple deterrent unique to each application. I would think this would be easy to do, since you don't even need to protect the password as long as your GDScripts are encrypted to begin with. Just pass it to "load_resource_pack" (If enhanced for password support) and go!

**Comment by reduz** [comment]
It's easy to extend encryption to the pck, but it will just make loading
assets much slower.. so not quite sure if this is desired. A checksum is
kinda easy to defeat, too.

**Comment by ArcFutahito** [comment]
How about just some unusual compression that's not supported by common archiving tools?

**Comment by ArcFutahito** [comment]
Actually, thinking about it, that's how almost everyone does it. At least I never encountered encrypted resources during romhacking. Just homegrown compression.

**Comment by reduz** [comment]
Whathever we add, it will make loading slower, sad fact of life :/ I don't
think there is an easy way of doing this.. the simplest and most efficient
is still encrypting scripts.. which forces people to look for the cipher in
the binary..

**Comment by ArcFutahito** [comment]
Well, yeah, sure, uncompressing would make stuff more taxing, but unlike encryption you get an extra benefit of having your game take up less space. 
Besides, it's not like games don't already pack up their stuff like that (at least on consoles).

**Comment by ArcFutahito** [comment]
http://www.oberhumer.com/opensource/lzo/
Something like this for example. But not recognizable by every damn archival tool in the world xD

**Comment by akien-mga** [comment]
Well .pck is already a custom (zip-derived) format AFAIK, and you can encrypt your scripts. What more is needed?

**Comment by ArcFutahito** [comment]
Pck actually compresses stuff? Huh, I didn't know that since packages get bigger than original files.

**Comment by akien-mga** [comment]
Well I don't know if .pck compresses stuff, but probably just as much as .zip (i.e. mostly none :D).

**Comment by eon-s** [comment]
Extending the script encryption to some selected scenes may help, but the "pro" way to protect your game may be a custom build with modules.

**Comment by supercom32** [comment]
Ah, some pretty good points made all around! In regards to the 'speed' of encrypting assets, I kind of feel that rather than make that choice, it should be up to the user to decide. Not all applications will be super large or intensive, and for some people the trade-off might be worth while.

In addition, I really like eon-s idea that perhaps the ability to make some encryption to "key" scenes/files/assets could be done. It really strikes a balance for performance, while covering some key components essential to the operation of the program. 

Question, while we're on the subject: Does bundling everything in the executable simply cause an *.pck to be appended to the end of it? Or is the internal structure totally different? Is the contents still compressed?

PS: Assuming encryption was added, how much slower loading are we talking about? Because on most modern computers running LUKS encryption, or another form of full disk encryption, I never really notice much of a performance problem.

**Comment by Calinou** [comment]
`.pck` does not compress, but `.zip` does. So, if you want the fastest loading possible, you should favor `.pck` over `.zip` (but `.zip` compression is plenty fast for most use cases). Note that while generic archive managers can't open `.pck` files (it's a custom format made for Godot), it would be easy to extract them (and possibly re-create them) by writing a custom utility.

**Comment by punto-** [comment]
If you can control what happens with your zip file, you can archive (ie not
compress) certain files

**Comment by ArcFutahito** [comment]
If files are just strung together then you probably don't even need a utility, you can just open hex editor and look up file headers.

**Comment by eon-s** [comment]
Another option, add full pck encryption but allow encrypted and unencrypted pcks (I wonder if this can be done on 2 already), so assets can be unencrypted while scenes and scripts are protected (to prevent loading them on other Godot projects).

**Comment by rraallvv** [comment]
I came here because of [this video](https://www.youtube.com/watch?v=FdNXTFD59Tw&feature=youtu.be), that shows a tool that supports out-of-the-box decompression for Godot package files.

I just wanted to point out that there is a [tool](https://en.wikipedia.org/wiki/TrueCrypt) that can be used to access encrypted virtual volumes on-the-fly. It's multi-platform, open source, fast and don't require additional space, although active development has stoped.

Maybe someone want to pick up on that, to add that kind of thing to Godot.

**Comment by Calinou** [comment]
> So, I just wanted to point out that there is a tool that can be used to access encrypted virtual volumes on-the-fly. It's multi-platform, open source, and fast, and don't even require additional space, although active development has stoped.

Neither TrueCrypt nor its fork VeraCrypt are under an FSF-approved or OSI-approved license. Additionally, I think they would be too large to be embedded into a game engine.

**Comment by rraallvv** [comment]
I just found [this website](https://quixdb.github.io/squash-benchmark/unstable/) with some very interesting charts comparing the most commonly used compression algorithms.

In particular for an assets container one might be interested in looking at fastlz, lz4 and yalz77. For instance lz4 is faster than fastlz, although it's compression ratio might be lower depending on the type of the files added to the container. Also yalz77 has the fastest decompression speed of the three, with a similar compression ratio to the other two algorithms, although it's compression speed is the slowest.

I'm implementing an custom assets container format using lz4 and AES in C# for a separate project, also I will try yalz77 to see which one is faster with the assets I'm using, since a small compression time isn't a requirement for that project.

Maybe we could add both lz4 and yalz77 as alternatives to fastlz for network communication and stuff to Godot, or maybe as a alternative to the zip format for exported packages. What do you think guys?

I haven't published yet a repository for my custom assets container format using lz4 and AES, but if anyone want to experiment with it just let me know. Cheers!

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
