### ISSUE TITLE
Unable to switch disabled check on instantiate CollisionShape2D

### ISSUE THREAD

**Issue by asalazar516** [godotengine/godot#86148]
### Tested versions

v4.1 to v4.2

### System information

Windows 10 godot v.4.2 stable

### Issue description

I am having an issue on Godot 4.2, I upgraded my project from 4.1 to 4.2, and I noticed I am unable to switch my disabled check on CollisionShape2D. Is there a way, to fix this that I can change it. I noticed that I can duplicate my player and will be able to switch it, but checking if I don't need to start over again.

![CollisionShape](https://github.com/godotengine/godot/assets/26031647/7ef6dd37-5d55-47b7-8a17-9fd02cee8e27)

### Steps to reproduce

- Create a CharacterBody2D in v4.1
- Make a separate hitbox node.
- In Hitbox node, add a CollisionShape2D node as a child
- Instantiate node to CharacterBody scene
- Upgrade project to v4.2
- Try to enable Disabled check

### Minimal reproduction project (MRP)

[testDisabledCharacterBody2D.zip](https://github.com/godotengine/godot/files/13668969/testDisabledCharacterBody2D.zip)

**Comment by bs-mwoerner** [comment]
In your `AnimationPlayer` node, go to the `RESET` animation and set the the Update Mode for the `CollisionShape2D:disabled` track to `Discrete`. If that `RESET` animation was created before Godot 4.2, it will probably have an update mode of `Continuous`, which seems to break things in 4.2.

I came across the same problem just recently with an AudioStreamPlayer that suddenly repeated the first few milliseconds of audio over and over. It sounded like a hanging audio system, but actually was just the AnimationPlayer starting the playback again and again after reaching the single keyframe setting `Playing` to `true`. This, too, was an animation that was originally created before 4.2 and the problem could be fixed by going into `RESET` and changing the Update Mode for the property there.

**Comment by asalazar516** [comment]
I see. Yeah, clearing the `RESET` animation allowed me to check the `CollisionShape2D :disabled` track for the `AnimationPlayer` node. Thank you for the tip, @bs-mwoerner!
