### ISSUE TITLE
Mobile app project in Godot crashes when i re-bake a navigationregion3d at runtime

### ISSUE THREAD

**Issue by aligmayu** [godotengine/godot#86190]
### Tested versions

I AM WORKING IN GODOT 4.2 STABLE VERSION

### System information

I AM USING UBUNTU 22.04.3 LTS

### Issue description

![BUG REPORT PIC](https://github.com/godotengine/godot/assets/73648009/1e497e05-db8e-491d-a8ad-1ab6bc329abc)

I am trying to update a navregion3d by calling the bake_navigation_mesh() function at runtime and it works with no problem when i run it on the engine itself. But crashes when i run it on a real android phone. I have done a lot of troubleshooting and now i am certain that the re-baking of the navregion causes it to crash. The project i am working on is a 3D RTS mobile game where there is a mechanic of dropping of buildings on a map so i have to update the navregion3d as soon as i added the new building on the scene. I dont know what to do anymore, I think it is a bug since it works when debugging only in the engine itself but crashes when ran on a real android device.I saw someone with the same problem on the internet but not solved. PLease forgive my noobness i am an innocent noob.=C

### Steps to reproduce

		if BUILDING_DROP_AREA_OBSTRUCTION.is_empty():
			#DROP THE BUILDING
			new_spawned_object.position = camera_raycast_result.position
			new_spawned_object.clear_state()
			new_spawned_object.get_staticbody_3D().collision_layer = 1
			new_spawned_object.get_staticbody_3D_for_unit_collision().collision_layer = 1
			camera_raycast_result = module_camera.get_vector3_from_camera_raycast(camera, event.position)
			building_collider_id = camera_raycast_result.collider_id
			spawned_object_id = new_spawned_object.get_instance_id()
			nav_region.bake_navigation_mesh()
		else:
			nav_region.remove_child(new_spawned_object)

### Minimal reproduction project (MRP)

N/A

**Comment by smix8** [comment]
Please test:

1.) Bake with `nav_region.bake_navigation_mesh(false)` to bake single-threaded.

If this stops the crashes your mobile hardware likely has thread problems. Nothing the navigation mesh baking can do about that.

2.) Increase the `cell_size` and `cell_height` of your `NavigationMesh`, or reduce the overall size, complexity and scale of your level source geometry.

If this does stop the crashes after a certain point lowering / increasing those numbers you likely are running out of memory on mobile because you are creating too many voxels.

3.) Replace every use of a visual `Mesh` in your parsed source geometry with e.g. a physics shape. So no `MeshInstance3D` node, no `MultiMeshInstance3D` node, no `CSG` nodes. Nothing that involves the `RenderingServer`.

If this does stop the crashes you likely have corrupted Mesh data on mobile. There is an endless stream of bugs on mobile on certain hardware devices where the RenderingServer returns corrupted mesh data. The navigation mesh parsing process does not verify the entire mesh received from RenderingServer as that would cost too much performance. It expects a mesh data directly returned from the RenderingServer to make sense and not be corrupted.

**Comment by Calinou** [comment]
> The navigation mesh parsing process does not verify the entire mesh received from RenderingServer as that would cost too much performance.

Could this be done on debug builds so we can surface human-readable errors?

**Comment by smix8** [comment]
First step is that OP provides something tangible like an error log or MRP to narrow down the cause.

The "Godot part" already has checks and errors for broken meshes.
Everything that happens later in the thirdparty lib has not and can not easily be added.

A lot of similar crash reports in the past have turned out to be hardware memory problems or user errors (e.g. unsafe threading, changing scenes or deleting objects while the parsing runs, ...).

**Comment by aligmayu** [comment]
Good day my mentors. Thank you for taking time on responding to my problem. I was expecting some insulting response cause i may be asking stupid things hehe, but you are kind people. You are all right about the problem, it is a performance(hardware) problem. I discovered the problem is coming from my 3d assets, I exaggerated them as a noob I didn't know that it would impact the project so much they were too complex from the size to the amount of vertexes etc. I tried simpler with just enough mesh complexity and it works perfectly. No wonder the game is struggling when i try to run it on mobile device, i am only getting maybe 20 or lower in fps so the moment a re-bake the navmesh I guess the device cant take no more and crashes. Maraming salamat po!

**Comment by aligmayu** [comment]
Hello, I just wanna add, I think I found a better work around for this in case someone runs into this problem. Just go to your navigationregion3D -> Geometry and change from mehsintances to static colliders. it fixed the problem instantly. I honestly don't know why this is. Thank you!
