### ISSUE TITLE
Multi-pass post-processing shaders

### ISSUE THREAD

**Issue by seadra** [godotengine/godot#862]
There are many effects that require multiple passes, each time with a different shader, either finally combining the outputs into a final one, or using the output of one pass as input to the next one.

A lot of 3D engines out there supports this in some form. Unity has the concept of [Pass](http://docs.unity3d.com/Manual/ShaderTut2.html).

Right now, it is impossible to do multiple passes with godot, so we are restricted to "simple" stuff that can only involve a single pass.
Please add passes to godot!

**Comment by akien-mga** [comment]
What's the status on this issue @reduz? I guess the work on 2D shaders for 1.1 (IIRC) somehow addresses this issue?

**Comment by akien-mga** [comment]
I'm not an expert on the topic, but I guess this PR more or less addresses this issue? #4084

**Comment by reduz** [comment]
Rendering engine rewrite for 3.0 will address these I think

**Comment by seadra** [comment]
Any updates about post processing shaders? Planned for 3.1, maybe?

**Comment by reduz** [comment]
Yeah, layers / stencil / custom postprocessing has been pushed to 3.1

**Comment by seadra** [comment]
Still, the fact that it's on the roadmap is awesome! Thanks!

**Comment by Chaosus** [comment]
Well, Godot have shader passes now, post-processing is a subject of another issue(as well as other specific feature request). _Closed by bugsquad_

**Comment by seadra** [comment]
@Chaosus This issue is about multipass *post-processing* shaders, not multiplass material shaders. So can you please not close this issue?

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by Anutrix** [comment]
Any updates?

**Comment by samdze** [comment]
Why can't we extend the issue to generic multi-pass shaders support like Unity does?

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
