### ISSUE TITLE
Dictionary which runs a function in a key's value may run the function when accessing the value of an unrelated key

### ISSUE THREAD

**Issue by joshcoppola** [godotengine/godot#86228]
### Tested versions

Issue appears in both 4.2.1 and 4.1 stable

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 Ti (NVIDIA; 31.0.15.4617) - AMD Ryzen 7 5800X 8-Core Processor (16 Threads)

### Issue description

Dictionaries seem to be running some functions attached to the value of a key when a value from an entirely different key is accessed. It's hard to explain in words, example code below.

### Steps to reproduce

Here's my code:

```
var my_dict = {
    0: "foo %s" % return_placeholder_text(),
    1: "bar"
}

func return_placeholder_text() -> String:
    print("baz")
    return "placeholder string"

func _ready() -> void:
    print(my_dict[1])
```

I expect only "bar" to be printed since I am looking up a value in the dict that does not call `return_placeholder_text()`. However, I see this output:

```
baz
bar
```

### Minimal reproduction project (MRP)

[gdscript_dictionary_issue_minimal_reproduce.zip](https://github.com/godotengine/godot/files/13691640/gdscript_dictionary_issue_minimal_reproduce.zip)

**Comment by bobemoe** [comment]
i think this is expected behaviour, `return_placeholder_text()` is being called when the dictionary is initialized, not when a value is being accessed.

just `bar` is being correctly printed when you call `print(my_dict[1])`

add some more debug prints to help yourself understand, like:

```
func _ready() -> void:
    print("before")
    print(my_dict[1])
    print(my_dict[0])
    print(my_dict[1])
    print(my_dict[0])
    print("after")
```

if you want  `return_placeholder_text()` to be called only and every time you access that value you'll need a different approach

**Comment by joshcoppola** [comment]
Thanks, that must be it@

**Comment by joshcoppola** [comment]
Accidentally used the wrong close issue gesture
