### ISSUE TITLE
Set Animation Save Paths fails on animations containing "|" characters

### ISSUE THREAD

**Issue by LegitSuperfall** [godotengine/godot#86279]
### Tested versions

Tested in 4.1.3, 4.2, 4.2.1
Seems to work fine in 4,1,3 but not in 4.2 or 4.2.1

### System information

Windows 10, Godot 4.2

### Issue description

I imported a few animations from blender (from mixamo) and godot doesn't let me change anything about them.
I know i'm supposed to enable save to file. i did that, but it doesn't seem to work. I tried restarting godot between every step because who knows, but still
I do have to restart it at least one in any version. After importing, i can't open a new inherited scene without a restart. Theres a red x as an icon in the filesystem window

I hope it's something simple that im doing wrong but i don't think so

### Steps to reproduce

Just import the 'zombie' glb, restart godot, open inherited scene, then open scene (still the glb one), go to the meshes tab, and on each mesh enable save to file

I believe that is what i'm supposed to do, right?
After doing all of that, i still can't even change the name of the animations in the animations tools from that bottom menu

### Minimal reproduction project (MRP)

In the file i already imported the glb and followed all the steps, but ill include the glb separately in case i'm doing something out of order or something. Maybe someone can figure that out

Nevermind? The zipped folder is 56mb. idk if im doing something wrong, but maybe 25mb is too small for something like this no?

I guess ill just include the animation glb

[Zombie.zip](https://github.com/godotengine/godot/files/13698344/Zombie.zip)

**Comment by fire** [comment]
@SaracenOne maybe we could make the steps easier to discover

**Comment by LegitSuperfall** [comment]
> @SaracenOne maybe we could make the steps easier to discover

How would we go about doing that
Seems like im just following the correct steps, no?
I forgot to mention that im pretty new to this. I followed a tutorial

Relevant section is between 1:20 and 2:55
https://youtu.be/iV710Vm5qm0?list=PLQZiuyZoMHcgqP-ERsVE4x4JSFojLdcBZ

**Comment by LegitSuperfall** [comment]
I don't want to pester or anything, but can someone tell me if i'm doing something wrong? did something change on 4.2?
I really want to get back to making my game

**Comment by LegitSuperfall** [comment]
Thank you for answering.

You mean like discord or something?
I thought here was where i was supposed to report bugs

**Comment by AThousandShips** [comment]
I mean to ask questions for faster fixing, and either that or the forum, you don't have to ask there, but getting a response here or some help within 24 hours is far from guaranteed, and it's normal and reasonable to get a few days at least until someone has time to help you here, we have a number of people mostly volunteers who do work here, so people work at their ability

So you can wait for a response here, or try get answers elsewhere if you are in a rush

**Comment by LegitSuperfall** [comment]
Oh i see. I guess i was just trying to find out if it was a know bug, but it doesn't seem like it
I guess ill just use 4.1 for now

Thank you for your time

**Comment by lyuma** [comment]
![image](https://github.com/godotengine/godot/assets/39946030/b91e6abf-aa40-46ca-9a10-bfd39644f69d)
The first part with the "X" is addressed by #85922. Unfortunately, the bugfix barely missed the cutoff for the 4.2.1 patch release and will not be there until 4.2.2. That said, this bug only affects files whose names begin with names that sort alphabetically after the word "res": Therefore, as a workaround, avoid glb names which starts with letters between "r" and "z" case-insensitive.)

After renaming it to Qombie and trying again, I encountered the actual bug here:
![image](https://github.com/godotengine/godot/assets/39946030/83b94f2d-4547-400c-b011-7eb9063fd1e1)
The animation actions from blender contain a vertical bar "|", and when `Set Animation Save Paths` is used in the actions menu, this leads to file paths such as the following:
```
res://Armature_002|mixamo_com|Layer0.res
```
which is not a legal file path on Windows.
When the import is attempted again, it attempts to save to this file and fails, leading to an import error.
![image](https://github.com/godotengine/godot/assets/39946030/5b7398b2-1aff-4af3-ab38-da39014e68b7)
I finally opened the advanced dialog on "Qombie.glb" one last time, manually removed the vertical bars from the import paths one by one, and was able to confirm that the import now succeeds!
![image](https://github.com/godotengine/godot/assets/39946030/07108426-0ac1-402b-a4c1-6eda90e34412)

Thanks for the detailed report, and I will look into how to best address this in 4.3 (and maybe backport into 4.2)
