### ISSUE TITLE
Crash with cpuparticles2D?.

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#86323]
### Tested versions

v3.6.beta3.official [21ab700f2]

### System information

w10 64

### Issue description

The crash happens when I run a project and when I stop it and focus the editor, the scene tab in the editor contains a cpuparticles2D node.

If the active scene in the editor does not have a cpuparticles2D, the crash does not happen. So it looks like something related to the cpuparticles2d node

--verbose does not log anything.
The cmd terminal doesn't log anything either.

I need a way to get more information about what is happening, --verbose and cmd do not log the error.

The crash simply happens when you run, sometimes it is necessary to run repeatedly until the crash occurs.

https://github.com/godotengine/godot/assets/19652075/ce80df2b-9b3f-4b17-9cfb-4e8fd97ad6ad

### Steps to reproduce

Just run the project, wait 5/10 seconds, repeat until the crack happens and the editor suddenly closes.
You may have to run it multiple times or maybe just once.

### Minimal reproduction project (MRP)

[Test.zip](https://github.com/godotengine/godot/files/13713894/Test.zip)

**Comment by lawnjelly** [comment]
I haven't been able to reproduce so far with current 3.x in debug, and the 3.6 beta 3 (on Linux).
Am not 100% sure on the instructions, I'm just running the project then closing it repeatedly.

Will try with asan and see if it flags anything...

**Comment by Torguen** [comment]
Yes, just run it, wait 5/10 seconds and if nothing happens, run it again and so on repeatedly.

I would like to try a way to get more information but cmd and verbose don't report anything.

**Comment by lawnjelly** [comment]
Also would be helpful to know when the bug started happening (is it a regression?). Does it reproduce in beta 2 / 1 or in 3.5?

It could well be a regression from the 2D physics interpolation code.

**Comment by Torguen** [comment]
For some reason I can't reproduce the crash today.
I have tried with 3.5 and 3.6 beta 3 (again) but the crack does not occur... I have no idea why the crash does not occur now.

Yesterday it happened often, even after crashing when the editor was closed, if I started it again it immediately closed without even loading the test project.

**Comment by lawnjelly** [comment]
This could simply be a PC / GPU configuration issue. In particular I have heard that if OS updates graphics drivers but does not reboot, strange behaviour can result.

Maybe you can watch for repeat for a few days and if no problems arise we can close issue and just watch for further reports.

**Comment by Torguen** [comment]
Ok, this crack happens to me often, several times a week but I have no way to track it down for more information.
I think there is an opengl program that gets information about what happens with opengl, I don't know, maybe it could provide some information and I could use it when the crack happens to me again. I don't remember the name of that program and the Google results are disparate, I don't really know how to search for it.

**Comment by lawnjelly** [comment]
If this is an ongoing problem, then as said earlier, we need to first identify whether the problem is _new_ (called a regression).

If only you can reproduce it, it would be helpful if you can bisect when the crashes started. Did they occur with 3.5, 3.5.1, 3.5.2? With 3.6 beta 1, 2 etc?

Did you change your hardware / drivers / OS at any point? Did the crashes occur before / after any changes? What GPU do you have and driver version?

Additionally if you can run a debug build you can get more info during a crash. You can either look at the instructions to compile from source, or look for an existing debug build from @Calinou 's:
https://github.com/Calinou/godot-debug-builds/releases

As it is we don't have a lot to go on here, so there is very little we can do our side until we get further info.

Also we have to consider that we will get some reports that are simply GPU driver bugs. If a report is coming from only one PC configuration and is not reproducible by others, this can lead to a wasted dev time, so we normally are cautious until a bug can be reproduced on multiple systems.

**Comment by Torguen** [comment]
This appears to be a bug with the video card drivers.
A faulty installation or a bug in the latest drivers published by nvidia for my card.

The thing is, I uninstalled the current version and installed the previous version of the drivers and now it works.
I can't know if it is due to a bug in the latest version of the drivers or a faulty installation of that same version.

The point is that now it seems that no crash is occurring anymore.

**Comment by lawnjelly** [comment]
I guess for now it makes sense to close this, as based on information so far, it seems most likely to be driver issue.

We can reopen if we get further reports / more info (there have been changes to CPUParticles in 3.6, so it is _not outside possibility_ that it could be something our side triggering the driver issue).
