### ISSUE TITLE
Parallax background mirrors late on mobile aspect ratio.

### ISSUE THREAD

**Issue by theBSH** [godotengine/godot#86337]
### Tested versions

4.2 mono

### System information

Godot v4.2.stable.mono - Windows 10.0.22621 - GLES3 (Compatibility) - NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 Threads)

### Issue description

got this issue when porting my game to mobile the parallax background mirrors late bks it still thinks the aspect ratio is 16:9.
made this video to show case it (you don't need a mobile to reproduce):

https://github.com/godotengine/godot/assets/118190096/0ce96310-a844-4580-8bab-279170829886

### Steps to reproduce

watch the video

### Minimal reproduction project (MRP)

[mirroringlate_problem.zip](https://github.com/godotengine/godot/files/13719576/mirroringlate_problem.zip)

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/27160.

This occurs because ParallaxBackground can only draw 2 copies of the image at most. You start seeing the copy on the right when the copy on the left no longer has to be drawn.

To resolve this, use an image with a wider aspect ratio (I suggest 21:9) or draw parallax manually using a Sprite2D and region properties.
