### ISSUE TITLE
CSGMesh with PrismMesh set to 0 height Crashes

### ISSUE THREAD

**Issue by GiftedR** [godotengine/godot#86356]
### Tested versions

- Reproducible in 4.2.1.stable
- Reproducible in 4.1.stable
- Reproducible in 3.5.1.stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.4629) - 12th Gen Intel(R) Core(TM) i7-12700K (20 Threads)

### Issue description

It might be niche, however creating a new CSGMesh3D with a new PrismMesh and setting the height/y value to 0 causes Godot to crash. I found this by trying to do math in the height box and it defaulting to 0.
Expected: Create a flat prism

### Steps to reproduce

Works with any project:
- Open or Create a new Scene
- Create a new CSGMesh3D
- Select PrismMesh as mesh type
- Set Height Value / Y value to 0
- Godot Crashes

### Minimal reproduction project (MRP)

N/A

**Comment by rburing** [comment]
It's segfaulting somewhere in here:

https://github.com/godotengine/godot/blob/c28a091a09c39ed45931cd7830ae418d369fd9e6/modules/csg/csg_shape.cpp#L430

Probably MikkTSpace doesn't like the input surface.

**Comment by jsjtxietian** [comment]
Seems like the `MergeVertsFast` call recursion endlessly untill stack overflow.

![image](https://github.com/godotengine/godot/assets/8315986/14bb4f6c-e4e9-4758-918c-23be38168f81)

And seems like because there's already `nan` in float computing.

**Comment by LeoBelda** [comment]
It seems that the `nan` values are originating from divisions by 0 in `PrismMesh::_create_mesh_array`
https://github.com/godotengine/godot/blob/c8c483cf57a768110fce57e509f9b855e69d34b7/scene/resources/primitive_meshes.cpp#L1481
https://github.com/godotengine/godot/blob/c8c483cf57a768110fce57e509f9b855e69d34b7/scene/resources/primitive_meshes.cpp#L1576

Protecting those divisions fixes the crash, but since we are relying on a `y` ratio to calculate `scale`, it leeds to incorrect vertices for what you would expect from a 'flat' prism:
![flatprism](https://github.com/godotengine/godot/assets/24794294/4879e1d2-79ff-4b04-97b4-593de9f8c157)
Vertices that should be in the middle are squashed to the side because of the `x` coordinate calculation

I think I have a solution, will try to send a PR later today
