### ISSUE TITLE
RigidBody with polygon shape has weird physics.

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8638]
**Godot version: Master f527a6946**

**Issue description:**
RigicBody2D nodes with polygon shapes have some weird physics.

![brknrigid1](https://cloud.githubusercontent.com/assets/10215987/25660034/db00530a-2fe0-11e7-9fed-b033a7d275ed.gif)

![brknrigid2](https://cloud.githubusercontent.com/assets/10215987/25660037/e01c118a-2fe0-11e7-8aac-d5505b4d881b.gif)

**Steps to reproduce:**
Try the example project with visible collision shapes enabled (can't draw polygons not even with _draw yet).
Modify the polygon keeping the lower vertex position and the result is always the same.

**Link to minimal example project:**
[brokenrigid.zip](https://github.com/godotengine/godot/files/973284/brokenrigid.zip)
Added an extra rigid body for a more strange effect.

**Comment by bojidar-bg** [comment]
Related to #7136, was potentially fixed for 3D in #7426.

Basically, the center of mass is assumed to be at the Rigidbody2D's origin, which is why those shapes don't fall nicely. So, if you move the ColisionPolygon2D a bit to the left, it all works.

Additionally, there seems to be some unrelated problem of the rigidbody going to sleep even in some unstable positions because its velocity becomes too small for a moment. If you disable "can sleep", it should be a bit better.

**Comment by eon-s** [comment]
@bojidar-bg I see, will close this because is clearly a center of mass issue.

I've seen some sleep related problems with simple shapes a couple of months ago, I'll check if can be reproduced again and open another issue for that.
