### ISSUE TITLE
`textureQueryLevels()` returns `1` instead of `0` when the texture is unassigned

### ISSUE THREAD

**Issue by reptofrog** [godotengine/godot#86402]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Fedora 39, GNOME 45.2 Wayland

### Issue description

`textureQueryLevels()` returns `1` instead of `0` when the texture is unassigned.

In the docs, the following is stated:
```
If the texture is unassigned to a sampler, 0 is returned.
```

![image](https://github.com/godotengine/godot/assets/36744029/aaf47c0a-11a9-427f-ac9c-318901c5e583)

### Minimal reproduction project (MRP)

[textureQueryLevelsBug.zip](https://github.com/godotengine/godot/files/13745622/textureQueryLevelsBug.zip)

**Comment by bitsawer** [comment]
If I remember right, Godot always internally assigns a texture even to an empty sampler as reading from an empty sampler is undefined and an easy mistake to make for a beginner (it's also a nasty portability gotcha as different drivers do different things). You can control what kind of default texture gets assigned by using `hint_default_white`, `hint_default_black` and `hint_default_transparent`. But naturally as these seemingly empty samplers actually have a default texture assigned, `textureQueryLevels()` will return 1 instead of 0.

**Comment by clayjohn** [comment]
> If I remember right, Godot always internally assigns a texture even to an empty sampler as reading from an empty sampler is undefined and an easy mistake to make for a beginner (it's also a nasty portability gotcha as different drivers do different things). You can control what kind of default texture gets assigned by using `hint_default_white`, `hint_default_black` and `hint_default_transparent`. But naturally as these seemingly empty samplers actually have a default texture assigned, `textureQueryLevels()` will return 1 instead of 0.

Ya, that's exactly right. It looks like our description is copy pasted from the official GLSL docs. We can just remove that entire sentence
