### ISSUE TITLE
Mouse Filter Stop on parent swallows on_mouse_exited()

### ISSUE THREAD

**Issue by dobin** [godotengine/godot#86445]
### Tested versions

4.1 up to 4.2.1

### System information

Godot v4.2.1.stable - Windows 10.0.22631 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.4601) - AMD Ryzen 9 7900 12-Core Processor (24 Threads)

### Issue description

When i add a Area2D Icon (with TextureRect and CollisionShape2D as children) on top of another Area2D Slot (same layout), and set the Mouse Filter on the underlying Slot from "pass" to "block", it will swallow the "Mouse Exited" event of the Icon on top of it. 

![ezgif com-video-to-gif-converted](https://github.com/godotengine/godot/assets/3250886/9a6897db-0ec3-447a-8ad7-bce2504c7ee0)

This is a bit inuntuitive, as the Icon has not been modified, but breaks if other elements are behind/under it. Or does this work as intended? Probably related to [#84547](https://github.com/godotengine/godot/pull/84547)

### Steps to reproduce

Main.tscn:
* Slot
* icon

slot.tscn:
* TextureRect
* CollisionShape2D

icon.tscn:
* TextureRect
* CollisionShape2D

Put Icon partially over Slot. Test with mouse pass/block on the Slot.tscn. 

### Minimal reproduction project (MRP)

[uitest.zip](https://github.com/godotengine/godot/files/13754170/uitest.zip)

**Comment by Sauermann** [comment]
Area2D mouse entered / mouse exited is done as part of physics picking.
Since physics processing happens after processing the Gui (Control nodes), and the Control node is set to stop mouse events, they will not be 

For the order of input event processing I would like to refer you to https://docs.godotengine.org/en/latest/tutorials/inputs/inputevent.html

Mixing Control nodes with Area2D nodes is in most cases not a good idea. I would suggest to stay either with Area2D nodes or alternatively stay with Control nodes.

**Comment by dobin** [comment]
Got ya, that explains it well and clears my confusion. The inputevent site i consult regularly, but it is not easy to digest :-)
