### ISSUE TITLE
A strange line in 3d rendering export android

### ISSUE THREAD

**Issue by Desagiato** [godotengine/godot#86469]
### Tested versions

v3.5.3

### System information

Windows 10 exported for android

### Issue description

![Screenshot_2023-12-23-13-03-23-385_com Onirosoftworks 1](https://github.com/godotengine/godot/assets/114653399/13a4bc59-1592-4020-b50f-63914a757489)

### Steps to reproduce

simple export of my project

### Minimal reproduction project (MRP)

Just export for android

**Comment by Calinou** [comment]
@Desagiato Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

Also, which Android device model did you test this on? Which Android version is it running?

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by Desagiato** [comment]
[Uploading Nuovo Progetto di Gioco.zip…]()

the version of andorid is 12

**Comment by Zireael07** [comment]
The upload didn't finish, just FYI
