### ISSUE TITLE
False positive "Not all code paths return a value" error in `while true` loops

### ISSUE THREAD

**Issue by mphe** [godotengine/godot#86521]
### Tested versions

- Reproducible in: 4.2+

### System information

Arch

### Issue description

The GDScript analyzer does not take constant expressions into account when scanning for code paths that do not return a value.

### Steps to reproduce

The following code snippet yields an "Not all code paths return a value" error.
It also happens when changing `while` to `if`.

```gdscript

func foo() -> int:
    while true:
        return 0
```

### Minimal reproduction project (MRP)

[bug_code_paths.zip](https://github.com/godotengine/godot/files/13771350/bug_code_paths.zip)

**Comment by dalexeev** [comment]
This is because the analyzer does not check for `break`s and always-true conditions. In both cases, the error is not false positive:

```gdscript
func foo() -> int:
    while unknown():
        return 0
```

```gdscript
func foo() -> int:
    while true:
        if unknown():
            break
        return 0
```


The [halting problem](https://en.wikipedia.org/wiki/Halting_problem) is generally unsolvable.

**Comment by mphe** [comment]
> This is because the analyzer does not check for `break`s, always-true, and always-false conditions.

Well, that is exactly what I said. The analyzer does not check for constant expressions.

>  In both cases, the error is not false positive:

Of course it is not false positive when there are expressions of unknown result.
However, in my example there are only constant expressions that can be evaluated and checked statically.
In these cases, the analyzer yields false positives.

**Comment by dalexeev** [comment]
We have a similar [issue](https://github.com/godotengine/godot-proposals/issues/8530) with type narrowing. There is no clear answer as to whether a static analyzer should be that smart or whether we would prefer an [explicit syntax](https://github.com/godotengine/godot-proposals/issues/6941) for this. The situation is similar here; for the current level of static analysis in GDScript this is more of a limitation (and feature proposal material) rather than a bug. I agree that this could potentially be fixed, but it will also likely be more difficult to maintain.

As a workaround, you can use `return <default value>`:

```gdscript
func foo() -> int:
    while true:
        return 1
    return 0 # Will never be executed, just to suppress the error.
```

**Comment by daveTheOldCoder** [comment]
One solution would be an annotation that suppresses the error.
@warning_ignore("not_all_code_paths_return_a_value")

That might require changing the error to a warning.

**Comment by vnen** [comment]
This isn't a bug, GDScript simply does not do this sort of static analysis, as @dalexeev said. Whether it should or not could warrant a discussion, but it should be done on the [proposals repository](https://github.com/godotengine/godot-proposals/) (either as a proposal or a discussion).

**Comment by daveTheOldCoder** [comment]
"This isn't a bug, GDScript simply does not do this sort of static analysis,"

If GDScript can't do that sort of analysis, then it's producing a false error message. I call that a bug.

**Comment by dalexeev** [comment]
@daveTheOldCoder This is definitely a false positive error, but that doesn't mean it's a bug in our terminology. Personally, I support this, but since we are talking about a higher level of static analysis, the issue should be qualified as a proposal.

This is just a formality, the "feature" status does not mean a refusal to implement it, and the "bug" status does not guarantee a fix within a certain time frame. Please open a feature request or discussion in [godotengine/godot-proposals](https://github.com/godotengine/godot-proposals) instead, and then we can continue to constructively discuss the feature. Thanks!
