### ISSUE TITLE
DirectionalLight3D times the number of draw calls x5 on the Compatibility renderer

### ISSUE THREAD

**Issue by hakro** [godotengine/godot#86614]
### Tested versions

4.2.1

### System information

Godot v4.2.1.stable - Ubuntu 22.04 - X11 - GLES3 (Compatibility) - Mesa Intel(R) Graphics (RPL-P) () - 13th Gen Intel(R) Core(TM) i7-13700H (20 Threads)

### Issue description

This might or might not be normal.
But enabling shadows on a `DirectionalLight3D`, makes the number of draw call jump by 5 time on Compatibility renderer.

In comparison, it only doubles on the Mobile Renderer, and even less than that on Forward+

### Steps to reproduce

Just setup a simple scene with either primitive meshes, or GLB models, and a DirectionalLight3D
Draw calls seem reasonable when shadows are disabled.
Open the "Monitors" tab, check the "Total Draw Calls" checkbox, and observe the variations in the different renderers.
The differences between OpenGL (x5) and Vulkan (x2) are pretty noticeable.

https://github.com/godotengine/godot/assets/3624853/828d5fc4-fc04-466f-a3bf-ac63851fb19d

### Minimal reproduction project (MRP)

No need.
Any empty projects with primitive meshes and a DirectionalLight3D will be enough.

**Comment by jsjtxietian** [comment]
In my test, with vulkan godot still will have 5 draw calls in total :

![image](https://github.com/godotengine/godot/assets/8315986/4bf44c15-6ffd-432a-8dd8-a2213aa6605c)

In Compatibility :

![image](https://github.com/godotengine/godot/assets/8315986/43717259-f8b7-4991-9882-2d4a0034df5e)

If os is not related (mine is windows), then IMHO the problem lies in batching mechanism is different in forward+ and compatibilty.

**Comment by Calinou** [comment]
This is expected, as DirectionalLight3D with shadows enabled uses the **PSSM 4 Splits** shadow mode by default. If an object has to be drawn in all 4 splits (because it's so large relative to the splits), then it has to be drawn 5 times in total (one in each shadow split, and once for the final rendering).

**Comment by Zireael07** [comment]
Looks like something that needs to be documented better

**Comment by jsjtxietian** [comment]
> If an object has to be drawn in all 4 splits (because it's so large relative to the splits), then it has to be drawn 5 times in total (one in each shadow split, and once for the final rendering).

Yes PSSM will cut it into splits to render, but I'm curious why the difference between forward+ and compatibility and is there something we can do?

**Comment by Calinou** [comment]
> Yes PSSM will cut it into splits to render, but I'm curious why the difference between forward+ and compatibility and is there something we can do?

Forward+/Mobile feature automatic instancing of static MeshInstance3Ds, while Compatibility doesn't have this.

Also, Mobile doesn't use a depth prepass while Forward+ and Compatibility do. This reduces in a lower draw call count as opaque meshes aren't drawn a second time to avoid shading pixels twice.

**Comment by jsjtxietian** [comment]
Is this the right place to mention the drawcall increase behaviour? https://docs.godotengine.org/en/latest/tutorials/3d/lights_and_shadows.html#directional-light

**Comment by Calinou** [comment]
> Is this the right place to mention the drawcall increase behaviour? [docs.godotengine.org/en/latest/tutorials/3d/lights_and_shadows.html#directional-light](https://docs.godotengine.org/en/latest/tutorials/3d/lights_and_shadows.html#directional-light)

Probably, yes.

**Comment by clayjohn** [comment]
There are two sources of additional draw calls in the compatibility renderer:
1. Draw calls from rendering shadows
2. Draw calls from rendering additive passes

In the video from the OP, the cause of the additional draw calls is that all the objects are getting drawn into all 4 splits of the shadow map. So you get one draw call per shadow split and one more for rendering the object. 

When multiple shadows lights are in the scene you can also get additional draw calls when an object is touched by 2 or more lights with shadows enabled. This is because we use multipass rendering for lights with shadows in the compatibility renderer. The base pass can only render 1 light with shadows, so multiple draw calls are used when their are multiple shadowed lights. The other renderers don't do this, so in some cases, they will show fewer draw calls
