### ISSUE TITLE
Camera Smoothing causes jittering in Player again

### ISSUE THREAD

**Issue by Wladastic** [godotengine/godot#86634]
### Tested versions

- Reproducable in 4.2

### System information

Windows 10, Mac OS 14.2 Godot 4.2.stable.official

### Issue description

Issue was already fixed in Godot 3.x but reappeared:
https://github.com/godotengine/godot/issues/43800

It is essentially the same issue as before, when moving the player and having camera Position Smoothing enabled, it jitters the whole screen when following the Player.

### Steps to reproduce

Camera on 1920x1080,
Stretch: Viewport, keep_height, scale: 1.0, scale mode: fractional

Character Body 2D for Player with AnimatedSprite2D and AnimationPlayer/AnimationTree.
When I move slow around 150 velocity it is fine, when above 400, then it appears like the Character body is jittering back and forth.

### Minimal reproduction project (MRP)

Will look for some youtube videos where this was also mentioned (recent video of around 4 weeks ago)

**Comment by Calinou** [comment]
This will occur if your monitor's refresh rate or FPS cap differs from the physics FPS defined in the Project Settings. As a workaround, set the Camera2D's process callback property to **Physics** instead of **Idle**. A proper solution is to use physics interpolation, which hasn't been implemented in 4.x yet (and not in 2D yet either). Use https://github.com/lawnjelly/smoothing-addon/tree/4.x in the meantime.

Also note that https://github.com/godotengine/godot/issues/84137 can make this issue more noticeable, even if workarounds or physics interpolation are used.

Closing in favor of https://github.com/godotengine/godot-proposals/issues/6389.
