### ISSUE TITLE
Tileset collisions: The expanded polygon drawing tool can get stuck in a state where modifications are ignored.

### ISSUE THREAD

**Issue by louis-vinchon** [godotengine/godot#86720]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 Ti (NVIDIA; 31.0.15.3699) - Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 Threads)

### Issue description

When trying to draw collision polygons on 2D tiles, there has been two situations that put the **expanded editor** in a state where no further modifications are "registered": modifications will still show normally in the editor itself, but when saving and closing the editor, your last changes will be lost.

The two scenarios:
- Draw a polygon of any shape.
- Use the `clear` option.

Any further node addition / move / deletion will be ignored.

### Steps to reproduce

1. Create a tileset atlas with a texture.
2. Add a physics layer.
3. In the tileset editor at the bottom, got to `Physics > Physics Layer 0`, select a tile, and select the `Expand editor` option:
   ![s1](https://github.com/godotengine/godot/assets/45244201/85b9f421-d502-47c3-a9f8-8536c4592af1)
4. Trigger one of the two cases:
   - Draw any shape. Once the shape is "closed", no more modifications will take effect. Illustrated below: I drew a triangle, and then modified it to be a square.
     ![s3](https://github.com/godotengine/godot/assets/45244201/6daa7d20-27df-4b5b-bbf8-01ccd48164b2)
   - Use the `clear` option. No more modifications will take effect. Illustrated below: I cleared an existing polygon and drew a new one.
     ![s2](https://github.com/godotengine/godot/assets/45244201/9a4c5e21-bc4f-4ba2-a1a8-01bd16030364)

Saving has no effect.

### Minimal reproduction project (MRP)

[mrp_tilset_poly_editor_bug.zip](https://github.com/godotengine/godot/files/13812986/mrp_tilset_poly_editor_bug.zip)

**Comment by StylianosGakis** [comment]
I can confirm that I am also experiencing this with version: v4.2.2.stable.mono.official [15073afe3]
for macOS

**Comment by b-basa** [comment]
I was going to open a similar issue.

I can add a couple of points to this.
Adding/removing a polygon the first time in the expanded editor works correctly.
Any modifications after that does not work.

I have been debugging the engine and I narrowed it down to the reparenting of the expanded area.
The following code is expanding the editor

Adding the expanded editor -> https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_editor.cpp#L753
Removing the expanded editor -> https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_editor.cpp#L783

The following debug values are from removal of the expanded container, I checked there to see the original parents signal map because it looked like something was not emitted/received right.

"multiple_properties_changed' seems to be the one informing others about new polygons.
![image](https://github.com/user-attachments/assets/4e57207f-b1ce-4a8a-b2ac-0e43d8b3470f)

I have been trying to fix it in a nice way for the last 2 days.
If any developer can suggest a solution I can implement, I would be happy to create a pull request!

@KoBeWi maybe?

**Comment by b-basa** [comment]
I was going to open a similar issue.

I can add a couple of points to this.
Adding/removing a polygon the first time in the expanded editor works correctly.
Any modifications after that does not work.

I have been debugging the engine and I narrowed it down to the reparenting of the expanded area.
The following code is expanding the editor

Adding the expanded editor -> https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_editor.cpp#L753
Removing the expanded editor -> https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_editor.cpp#L783

The following debug values are from removal of the expanded container, I checked there to see the original parents signal map because it looked like something was not emitted/received right.

"multiple_properties_changed' and "polygons changed" seems to be important for new polygons.
![image](https://github.com/user-attachments/assets/42833928-5734-4bae-a6c3-8774691a3dc7)

I was trying solutions similar to these
https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_set_atlas_source_editor.cpp#L2890
https://github.com/godotengine/godot/blob/master/editor/plugins/tiles/tile_data_editors.cpp#L883

Or this 
![image](https://github.com/user-attachments/assets/30012b0e-70db-4d21-b78b-fb9180ef6c00)

If any developer can suggest a solution I can implement, I would be happy to create a pull request!
@KoBeWi maybe?

**Comment by KoBeWi** [comment]
Reparenting does not affect signal connections.
