### ISSUE TITLE
Script autocomplete is only autocompleting with file paths

### ISSUE THREAD

**Issue by CowThing** [godotengine/godot#8674]
**Operating system or device - Godot version:**
Windows 10 64bit - Godot 3 29768010126edda76229c5b14c85e7d72f1880f4

**Issue description:**
If there is a `preload()` after the code you're typing, the autocomplete will look like this:
![Not correct](http://i.imgur.com/HsEczoG.png)
If the `preload()` is before the code you're typing it will autocomplete correctly.

**Steps to reproduce:**
```GDScript
# Type code here, incorrect autocomplete
var test = preload("res://icon.png")
# Type code here, correct autocomplete
```

**Comment by bojidar-bg** [comment]
Probably an artefact of #8444, CC @magyar123

**Comment by magyar123** [comment]
Uhh. Sorry about that. I'm making a PR as soon as possible. This is what happens if you don't test your commits enough.

**Comment by bojidar-bg** [comment]
@magyar123 If you'd like, I can fix it as well... should I?

**Comment by magyar123** [comment]
That would be great, as currently I'm not near my computer.

@magyar123 <https://github.com/magyar123> If you'd like, I can fix it as
well... should I?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8674#issuecomment-299722965>,
or mute the thread
