### ISSUE TITLE
UI - Button does not keep his position, structure nested in different scenes [.NET]

### ISSUE THREAD

**Issue by DevMimas** [godotengine/godot#86821]
### Tested versions

v4.2.1.stable.mono.official

### System information

Windows 10 - Godot Engine v4.2.1.stable.mono.official.b09f793f5 - Vulkan API 1.3.260 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3060

### Issue description

The following scenario:
- Picture 1 Structure of the scene "`Startmenu`" // Is a container node
- Startmenu still contains a scene `StartmenuIcon`
- Startmenu is linked to the `Desktop` scene.

Picture 1 - Setup in `desktop` scene:

![grafik](https://github.com/godotengine/godot/assets/44207756/70a82b6c-eac2-4505-b03d-00fb6ba1db71)

Picture 2 - The white box is the button in the top left-hand corner. Is in `project execute` mode.

 ![grafik](https://github.com/godotengine/godot/assets/44207756/33fd93cc-0b52-48ba-a717-d339a349382e)

Picture 3: - In the `StartmenuIcon` scene, the position is in the correct place.

![grafik](https://github.com/godotengine/godot/assets/44207756/9fa24897-61f5-4add-b270-574a9a0f62da)

## Problem
The button in `StartmenuIcon` always jumps to the upper left corner only in the desktop scene. The position setting is not correctly adopted by the main scene.

Or is this due to the structure of the scenes?
I have already tried 10 times to adjust the position data in each scene. But the button always goes to Pos 0, 0. The position of the button is reset to Pos 0, 0 in the `desktop` scene after `project execute` mode.

### Steps to reproduce

Please see pictures

### Minimal reproduction project (MRP)

[TestProjectUI.zip](https://github.com/godotengine/godot/files/13847131/TestProjectUI.zip)

**Comment by AThousandShips** [comment]
Please add a minimum reproduction project, this is very specific and is hard to test without that as very little of the actual details are available, such as properties on the different nodes
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- If the reproduction steps are not project dependent (e.g. the bug is visible in a brand new project), you can write "N/A" in the field.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by DevMimas** [comment]
@AThousandShips Okay thank you. What is MRP and how do I get that?

**Comment by AThousandShips** [comment]
Read the instructions right there :)

**Comment by DevMimas** [comment]
@AThousandShips I have now added a test project with the UI.

To be honest, the structure is very strange (because we are still beginners). But we will definitely design the structure of the UI differently and build it better. But maybe I have found a bug that could have an effect on other parts. Or there are other ideas to prevent certain things, display a warning or something similar. We will see. Thanks for your support.

**Comment by rsubtil** [comment]
There are a few issues with your project. The `StartmenuIcon` control does not define a minimum size, so when you add it to a `Container` node, it gets collapsed and occupies no space. The inner button is anchored to be at the center of the area, but since there's no area at all, it implicitly means it will be moved to the corner. `Container` nodes will resize your nodes arbitrarily, so if you want a minimum size, you need to specify it additionally:

https://github.com/godotengine/godot/assets/6501975/4d26c215-7fef-4206-abfb-cfbf43a3dea8

Another issue is that there's a lot of small changes on `Editable Children` enabled nodes. This makes it difficult to troubleshoot such issues as it overrides any changes on the source scene. I had to disable and re-enable all of these and delete the `.godot` folder in order for changes in the original scenes to propagate to other nodes, so I'd avoid relying too much on this feature.

Lastly, do not mix `Control` and `Node2D` nodes, as they are fundamentally different. In this context, `Node2D` objects will not move/scale properly with changes in the UI, and cannot "ask" for minimum size either. For displaying assets, the equivalent in your button would be `TextureRect`:

![image](https://github.com/godotengine/godot/assets/6501975/a18c791c-509d-4752-91ad-bd60d1544a09)

**Comment by DevMimas** [comment]
Thank you for your help and quick support.
The issue has been resolved and I am now closing it.
