### ISSUE TITLE
OneShot ignores fade out time when combined with TimeScale

### ISSUE THREAD

**Issue by reyma24** [godotengine/godot#87009]
### Tested versions
4.1-dev2, **4.1-dev3**

I tested different versions and it breaks in **v4.1.dev3.official [a67d37f7c]**.
This is probably the change that broke it: https://github.com/godotengine/godot/pull/74190#issue-1605714905

### System information

Godot v4.2.1.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 31.0.15.4629) - Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 Threads)

### Issue description

When combining a OneShot node with a TimeScale node (with values higher than 1) in a BlendTree, the OneShot node ignores the specified fade out time, resulting in the animation "snapping" at the end.

https://github.com/godotengine/godot/assets/90044741/cf714171-4573-46bc-bc2f-68a0e4b3ec3f

_TimeScale = 1 -> Works fine_
_TimeScale = 1.5 -> Animation snaps at the end_

This exact setup worked fine in Godot 3.

### Steps to reproduce

Create a BlendTree with a looping animation and a OneShot node. Combine the OneShot animation with a TimeScale and set it to a value higher than 1. (See the video above)

### Minimal reproduction project (MRP)

[TimeScaleBug.zip](https://github.com/godotengine/godot/files/13875290/TimeScaleBug.zip)

**Comment by TokageItLab** [comment]
I'm working on a huge rework of AnimationTree for https://github.com/godotengine/godot-proposals/issues/8083 right now, but the original fade implementations of OneShot, Transition and StateMachine are pretty hacky to begin with because they don't take original delta into account but using result of `current - prev`, so it will have to be recreated.
