### ISSUE TITLE
Memory Leak when using change_scene_to_file and change_scene_to_packed

### ISSUE THREAD

**Issue by TheSokka** [godotengine/godot#87065]
### Tested versions

Reproducible in 4.1.3.stable.mono

### System information

Godot v4.1.3.stable.mono - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 SUPER (NVIDIA; 31.0.15.3667) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

I seem to have caught a memory leak issue that persists throughout my whole project after scene_load_from_file. Unsure if this is just a project or the engine itself, but I know 100% it isn’t my code causing this issue. Some obvious indicators are the objects graph, progressively growing each scene load from file. Including the slight increase in memory.
![image](https://github.com/godotengine/godot/assets/59793089/ae400501-d359-42df-a31c-934cf2107273)

### Steps to reproduce

In C#, call method GetTree().ChangeSceneToFile("AnyScene")

### Minimal reproduction project (MRP)

This can be done in any project right off the bat, just switch your scene and it doesn't dispose previous code properly.

**Comment by Mickeon** [comment]
Can you try reproducing this in 4.2 or, better yet, [4.3 dev 1](https://godotengine.org/article/dev-snapshot-godot-4-3-dev-1/)?

**Comment by YuriSizov** [comment]
Please try to reduce your project to an MRP, so it can be debugged properly. It would also help if you could try to recreate the scenario with GDScript, since there may be issues with how C# scripts are disposed of.

Under the hood these two methods don't do anything you couldn't do yourself with loading and instantiating a scene, and then removing old node and adding another. So it's probably not specific to these methods, but we would need an MRP to check.

**Comment by bs-mwoerner** [comment]
Can't reproduce in 4.3 dev 1 with GDScript or in 4.1.3 or 4.2.1 with C#.
```C#
public partial class Scene1 : Node2D
{
    public override void _Process(double delta)
        => GetTree().ChangeSceneToFile("res://Scene2.tscn");
}
```
```C#
public partial class Scene2 : Node2D
{
    public override void _Process(double delta)
        => GetTree().ChangeSceneToFile("res://Scene1.tscn");
}
```
![grafik](https://github.com/godotengine/godot/assets/35597337/5ab50b6d-8080-4d11-bc03-751734f44ec9)
Hovering around 1240 in 4.2.1 and around 1190 in 4.1.3.

**Comment by liamhendricks** [comment]
I am also seeing this issue. I'm using GDScript in 4.2.2 on Ubuntu. Here's what it looks like in my current project:
![Screenshot from 2024-05-31 15-31-45](https://github.com/godotengine/godot/assets/4118773/3cd0280f-9398-417d-a1d2-7c04a1e2b2ee) Each bump in memory is after a call to `change_scene_to_packed()`. No idea if it is caused by my code or not, but my investigation led me here so I figured I would add my report as well.

Side note: my project has a bunch of orphaned nodes that are just for object pooling, that is not the problem and you can see the orphans do not rise.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if someone provides an MRP this can be reopened
