### ISSUE TITLE
Clicking (or dragging) the OS window while setting the position of a RigidBody, moves the RigidBody

### ISSUE THREAD

**Issue by golddotasksquestions** [godotengine/godot#87092]
### Tested versions

Reproduceable in Godot 4.2.1 stable, Godot 4.3. dev2

### System information

Windows 10, Nvidea RTX 1080, Forward+

### Issue description

When clicking the Window (like when you want to drag it somewhere else on your screen) while the scene is running, the RigidBody3D will suddenly jump down on the y axis, while it's position is set on the x axis with the code below:

```gdscript
extends Node3D

func _process(delta):
	$RigidBody3D.global_position.x += delta 
```

https://github.com/godotengine/godot/assets/47016402/aafcdaf2-c8e8-4f82-9eeb-2d8bbd885777

I have also tested this with StaticBody3D and CharacterBody3D and only RigigBody3D behaves like that.

### Steps to reproduce

1. Set the global position of a RigidBody3D, 
2. Click the game window while the scene is running.

### Minimal reproduction project (MRP)

[click_window_rigidbody_bug.zip](https://github.com/godotengine/godot/files/13909619/click_window_rigidbody_bug.zip)

**Comment by rsubtil** [comment]
I don't think it's a bug. Setting the position of a `RigidBody` on every frame is [not supported](https://docs.godotengine.org/en/stable/tutorials/physics/rigid_body.html). 

For this particular scenario, I think this is due to lag spikes caused by the window movement, which causes physics ticks to run more than one time per frame in order to catch up. With that, and because this object has gravity, it gets applied on such ticks, making the cube fall down slightly. If you set the **Max Physics Steps per Frame** to 1, this doesn't occur anymore, at least in my setup:
![image](https://github.com/godotengine/godot/assets/6501975/fe9ea18b-34cb-4035-8d18-a5cc12e78970)

Using `_physics_process` it shows the expected movement more clearly:

https://github.com/godotengine/godot/assets/6501975/cef91b6f-542c-46ec-8289-9e4a22421482

**Comment by AThousandShips** [comment]
Indeed, this is not supported and that is clearly documented 🙂

**Comment by golddotasksquestions** [comment]
@rsubtil 

Thanks, your explanation does make a lot of sense.

**Comment by golddotasksquestions** [comment]
@rsubtil

Thanks, your explanation does make a lot of sense.
