### ISSUE TITLE
Array.clear() clears export values for the entire scene instead of just the current Node

### ISSUE THREAD

**Issue by SecurityRisk** [godotengine/godot#87193]
### Tested versions

- Reproducible in 4.2.1

### System information

Windows 11, Godot 4.2.1

### Issue description

When using an array inside of a Node, if that array is `clear()`'ed it will clear all array's of all subsequent instantiations of the scene instead of just the object it is `clear()`'ed on. I'm not sure if this is expected or if it's expected to act similarly to setting the array to `[]`

### Steps to reproduce

Create a Node and attach a script to it
In the script export an array `@export var array_of_things = []`
Assign anything to the array in the scene view of the Node
Create the Node inside of the game loop
The value of `array_of_things` will be whatever you assigned in the scene view
Run `array_of_things.clear()` at some point
Any subsequent instantiated instance of the Node will automatically have its `array_of_things` be empty even though the scene originally contained values inside of the array

However, if you were to set the array to `[]` instead of using `clear()` it will properly only affect the current object you called it on instead of influencing all subsequent instantiated objects

### Minimal reproduction project (MRP)

Here is an example project that proves this point. https://github.com/SecurityRisk/Godot-Clear-Test

**Comment by bs-mwoerner** [comment]
Since your `node.tscn` scene file overwrites the script's default value for the `array_of_things` parameter with an array, every new instance of the scene will be initialized with a reference to this same array and thus any change to that array will be seen by all scene instances. If you want each scene instance to have its own copy of the array, either
- Set the default value in code (`@export var array_of_things:Array[String] = ["One", "Two"]`) and do not override that default value with an array defined in the scene file, or
- have each node create its own copy of the initial array in its `_ready` function: `array_of_things = array_of_things.duplicate()`.

Unlike calling the array's `clear()` method, setting the parameter to `[]` does not modify the current array but replaces it with a new, empty array.

**Comment by SecurityRisk** [comment]
I see, so it's a matter of the `array_of_things` is a reference. Calling `clear()` simply updates the reference by removing all the elements in the array thus making the reference point to an empty array. Whereas, setting the array to a new empty array updates the pointer for that object, which in turn, only changes that specific object's array and not the overall scene.

I figured when I ran `instantiate()` it would deep copy all variables including non-primitives so new memory addresses were created for all variables including other objects. I'll assume all non-primitives are references going forward so I'll need to `duplicate()` if I need to modify any Objects without disturbing the initial references
