### ISSUE TITLE
AccessViolation when debugging a C# Console app or Unit tests

### ISSUE THREAD

**Issue by dotlogix** [godotengine/godot#87276]
### Tested versions

4.3.dev, 4.2.x

### System information

Windows 11, Godot 4.3-dev, Vulkan, Jetbrains Rider, .Net 8/7/6

### Issue description

When debugging unit tests using the GodotSharp library the application crashes instantly with this access violation exception:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Godot.NativeInterop.NativeFuncs.godotsharp_string_new_with_utf16_chars(Godot.NativeInterop.godot_string ByRef, Char*)
   at Godot.NativeInterop.Marshaling.ConvertStringToNative(System.String)
   at Godot.NativeInterop.NativeFuncs.godotsharp_string_name_new_from_string(System.String)
   at Godot.StringName..ctor(System.String)
   at Godot.StringName.op_Implicit(System.String)
   at Godot.Engine..cctor()
   at Program.<Main>$(System.String[])
```

### Steps to reproduce

Create a console application or a unit test project.
Reference GodotSharp
Console.Log(new Vector3(0,0,0))

Try to debug it.

### Minimal reproduction project (MRP)

[GodotAccessViolation.zip](https://github.com/godotengine/godot/files/13956175/GodotAccessViolation.zip)

**Comment by raulsntos** [comment]
I'm unable to reproduce the issue with the provided MRP.

Judging from the stack trace, it looks you are trying to use API that requires interop with the Godot engine. It's fine to use the GodotSharp package in a standalone C# application as long as you don't use API that requires interop. Otherwise, I'd recommend to create a Godot project so the Godot engine is the entry point.

You can have a Godot project with a main scene that has a node with a C# script attached that launches a Test runner, then all the Godot API should be available.

**Comment by dotlogix** [comment]
Thanks for checking on this so quickly.

Unfortunately the StackTrace is from the console app I shared as a test project.
I do not use any API other than Vector3I. I still get this error.

Running the app works fine, but as soon as I add a breakpoint it instantly crashes with the provided StackTrace. It could be related to the Rider IDE trying to capture additional Context. I am using I haven't tested with VS Studio.

**Comment by dotlogix** [comment]
Related to this issue on Rider seems like it is an issue in the IDE not with Godot itself.
https://youtrack.jetbrains.com/issue/RIDER-102751/Rider-crashes-in-nunit-test-even-when-stopping-at-first-line-of-test
