### ISSUE TITLE
Shader language - enum hints for uniforms

### ISSUE THREAD

**Issue by n-pigeon** [godotengine/godot#8738]
Godot 3.x

Would be great to have `enums` or something similar for `uniforms` in shader lang.
So it would be easier to add switchable functionality, instead documenting for user which `int` does what.

**Comment by nunodonato** [comment]
wont this encourage the use of If statements? branching is discouraged in shaders

**Comment by n-pigeon** [comment]
@nunodonato
Hmmm I didn't though about it. Maybe.
It's waste of processing power, but 3.0 already supports `if` statements. 

**Question is, do we make it smarter than user. Or there is no need to make interface for it harder to use, when somebody decides to use it.**

We can always write in new shader tutorial to be aware of using `if`. Usually it can be avoided using scripting. For example changing shader in node, not shader code in shader itself, although compiling multiple shaders also slows things down.

**Comment by nunodonato** [comment]
@n-pigeon actually, you can do a sort of branching in shaders, but you shouldn't use ifs. Usually you mix() 2 variables based on a 3rd one which is the "conditional". 
Consider a splatmap, for example. Based on the color of the map, you paint different textures, but you never use IFs to decide.

I think @reduz said that the new shader language would also include a few helper functions to make comparing things easier.

**Comment by n-pigeon** [comment]
@nunodonato
Thats how you mix shaders and there will also be na `if`.
`if texMask:
    col1
else:
    col2
`

` if texMask * cusotmBlend:
    col1
else:
    col2
`

`if / enum` would be more for changing shader behaviors more globally by Inspector.
Sometimes you have to use `if`, trick is to figure out how not to :P

**Comment by n-pigeon** [comment]
Well there is (probably it's part of GLSL) mix() you can use it for blending. It also probably uses some sort of if (although probably )

**Comment by n-pigeon** [comment]
Ups. Accidentally closed xD

**Comment by reduz** [comment]
kicking to 3.1, low priority

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
