### ISSUE TITLE
Cannot override bone Transform in code when using AnimationTree, even Deterministic = false 

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#87428]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.stable - Windows 10.0.19045 - Vulkan (Forward+)

### Issue description

When using AnimationTree, I cannot override the bone transform in code.
Everytime it seems the AnimationTree will reset my overrided bone transform, 
even I have checked Deterministic = false option, as stated in #87400 .

### Steps to reproduce

Import a animated model and set up AnimationTree node and active it, also check Deterministic = false option .

write a script to override bone transform, like below:

```
func _physics_process(delta):
	test.get_node("Armature/Skeleton3D").set_bone_global_pose_override(b_idx, Transform3D(), 1)
```

No any effect.

### Minimal reproduction project (MRP)

[bone_transform_override.zip](https://github.com/godotengine/godot/files/14000021/bone_transform_override.zip)

**Comment by TokageItLab** [comment]
You should use `set_bone_pose_rotation()`. Also, as a specification, it cannot be overridden while the animation is playing. We are planning something like Bone Modification that can be blended with animation by reworking IK, but it is still in the planning stage.

**Comment by nagasawamaki** [comment]
> You should use `set_bone_pose_rotation()`. Also, as a specification, it cannot be overridden while the animation is playing although Deterministic = false. We are planning something like Bone Modification that can be blended with animation by reworking IK, but it is still in the planning stage.

I have changed the function from `test.get_node("Armature/Skeleton3D").set_bone_global_pose_override(b_idx, Transform3D(), 1)` to `test.get_node("Armature/Skeleton3D").set_bone_pose_rotation(b_idx, Quaternion())` but still no any effect.

Do you mean currently I cannot change the bone rotation by code when using with animationTree?

**Comment by TokageItLab** [comment]
See above

> Also, as a specification, it cannot be overridden while the animation is playing although Deterministic = false. We are planning something like Bone Modification that can be blended with animation by reworking IK, but it is still in the planning stage.

**Comment by KMouratidis** [comment]
@nagasawamaki does it work if you do the override in `_process` instead?

**Comment by TokageItLab** [comment]
Oh, indeed, the main problem is that the CallbackModeProcess of the AnimationMixer does not match the process of the script.

However, even if they do match, it is not safe because the order in which the animation values are applied depends on the node order or process_priority as @KMouratidis said.

**Comment by KMouratidis** [comment]
> See above. Animation values are applied after gdscript process().

That doesn't sound right to me. 

All internal code should be called **before** GDScript, as seen here: https://github.com/godotengine/godot/blob/70ca65914345971dccb80e8b68846f38c2739769/scene/main/scene_tree.cpp#L934-L948

And if I'm not mistaken, the actual updates DO happen in process/physics process, as seen here: https://github.com/godotengine/godot/blob/70ca65914345971dccb80e8b68846f38c2739769/scene/animation/animation_player.cpp#L242-L260

So maybe the reason why it works in `_process` but not in `_physics_process` is because the order is:

1. Physics process internal: `AnimationPlayer` / `AnimationTree` sets bone data
2. Physics process gdscript: player overrides bone data
3. Process internal: `AnimationPlayer` / `AnimationTree` sets bone data, overriding the user's override
4. Process gdscript: overrides in here work

This explains why `set_bone_global_pose_override` in `_physics_process` doesn't work but `_process` works.

As for the reason this doesn't apply to `set_bone_pose_rotation` unless you set `process_priority`, I'm still unable to understand.

**Comment by TokageItLab** [comment]
set_bone_global_pose_override - bone_pose_override was implemented to ignore process order for BoneModifications that need to be applied after Animation like IK or PhysicsBone hack, but the problem here would be that even if it did, it would not ignore the order for rendering server with skinning. I'm writing a proposal now to deprecate bone_pose_override in the future and instead have a cleaner control over process order.

**Comment by nagasawamaki** [comment]
@KMouratidis Thanks! It works when I put the code inside `_process`. And thanks for your detailed explanation about the running order inside Godot.

@TokageItLab Got it. Hope your proposal will be implemented soon. Thanks.
