### ISSUE TITLE
Inherited scenes produce errors in editor when "editable_children" is true.

### ISSUE THREAD

**Issue by bhottovy** [godotengine/godot#87424]
### Tested versions

Reproducible in mono 4.3.dev2

### System information

Windows 11 Intel(R) Core(TM) i7-12700H CPU @ 2.30GHz

### Issue description

When a base scene (containing at least one child) is inherited and the inherited scene is instanced inside of a parent scene and has 'editable_children' = true then saving the parent scene or selecting one of the editable children inside of this instanced node spams the output with this error:

![image](https://github.com/godotengine/godot/assets/17091612/d38aaddc-2e60-45aa-994c-9924e6e5de53)

This error does not happen when the base scene does not have any children.

Seems to happen regardless of node types.

### Steps to reproduce

1. Create a base scene and add at least 1 child node.
![image](https://github.com/godotengine/godot/assets/17091612/3dd24694-463d-4fde-8ef2-aa765f4ea38b)
2. Create a new inherited scene from the base scene.
![image](https://github.com/godotengine/godot/assets/17091612/eb9d2c92-a601-4538-8b4c-086ff8e6dfac)
3. Create a new 'parent' scene and instance the inherited scene inside of it. Set the 'editable_children' of the instance to true.
![image](https://github.com/godotengine/godot/assets/17091612/19347e7b-3149-4fe0-9932-ce3cab6f6e3a)
4. Now either selecting the child node inside of the inherited instance or saving the parent scene will spam the previous error to the console.
![image](https://github.com/godotengine/godot/assets/17091612/33190fc1-0d05-4f86-bd69-a6fbded351ea)
![image](https://github.com/godotengine/godot/assets/17091612/349173e2-004a-4553-a48d-c8acb6d18951)

### Minimal reproduction project (MRP)

[BugReportMRP.zip](https://github.com/godotengine/godot/files/13999604/BugReportMRP.zip)

**Comment by sketchyfun** [comment]
I'm not sure if it's related (although I am getting the exact same error spam as the original post), but I've also noticed that inherited scenes with editable children enabled can end up having their resources duplicated and saved as part of the parent scene instead of using the original resource path of the instanced scene. Here's an example of a SpriteFrames resource on my player scene

 
![2024-02-24 22_02_36-(_) stage9 tscn - Ex-Zodiac - Godot Engine](https://github.com/godotengine/godot/assets/10464013/6ce28b08-85b8-4ac5-88eb-95f6fc0217fd)

And then after I click the little reset icon next to the SpriteFrames resource, it resets back to what's stored in the instanced scene

![2024-02-24 22_09_10-stage9 tscn - Ex-Zodiac - Godot Engine](https://github.com/godotengine/godot/assets/10464013/dc9804b1-a54f-4708-ac7d-41cbfd6afa46)

I've only been noticing this recently, so I thought it might coincide with this, but if you'd rather I open a separate ticket for it, I can
