### ISSUE TITLE
set_bone_global_pose_override quite slow

### ISSUE THREAD

**Issue by wagnerfs** [godotengine/godot#87484]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Windows 10 - Forward+

### Use case

We use these a lot for things like making the head bone look at objects, jiggle physics like tail and hair, etc.

### Issue description

It might be related to https://github.com/godotengine/godot/issues/84970
using a couple set_bone_global_pose_override per frame absurdly consumes the physics time for no reason

FPS at 1600+ without touching the bones.
![image](https://github.com/godotengine/godot/assets/106078/33b7bf47-289d-4cef-8821-f00c44b41feb)

Same scene running the code below on around 40 bones total per armature

```gdscript
func _process(delta: float) -> void:
	for i in skeleton_3d.get_bone_count():
		var parent_idx = skeleton_3d.get_bone_parent(i)
		if parent_idx < 0: continue
		
		var global_pose = skeleton_3d.get_bone_global_pose(parent_idx) * skeleton_3d.get_bone_pose(i)
		skeleton_3d.set_bone_global_pose_override(i, global_pose, 1.0, true)
```

![image](https://github.com/godotengine/godot/assets/106078/a4a1e0ae-be9e-4bda-96a1-12df09cbb34c)

Might have something to do with every new set_bone_global_pose_override a full bone structure refresh is requested

### Steps to reproduce

Just use set_bone_global_pose_override enough times

### Minimal reproduction project (MRP)

[set_bone_global_pose_override.zip](https://github.com/godotengine/godot/files/14014595/set_bone_global_pose_override.zip)

**Comment by smix8** [comment]
I don't see any increase in physics frame, just process frame.

Physics is unrelated to the skeleton updated except if you attach physics objects like physics bones or have collision attached in other ways directly to the skeleton bone transforms.

Now the spike in process frame is very noticeable with a good reason.

The problem is that your are making the skeleton dirty on every single override function call to the setter while also immediatly requesting global bone transform data from a getter that can not be returned correctly without a skeleton update. Effectively forcing  39 full skeleton and skin updates due to the loop.

The performant way to handle this is to cache all the bone transforms first in an array (or any other skeleton info that you need for your procedual stuff), then do all the bone updates or any other transform calculations that you need to do with the cached data and not calling transform getters between that require recalculations of the entire skeleton to return the correct value.

Note that in the example the parent global pose multi with the bone pose is the same as just the bone global pose and the root bone should just return its on pose transform so part of the calculations are likely redundant in your script. I know it is just a quick example script but if you have similar code in your project you might want to double-check to also gain some performance there.

```gdscript
func _process(delta: float) -> void:
	
	var bone_cache: Array[Transform3D] = []
	bone_cache.resize(skeleton_3d.get_bone_count())

	for i in skeleton_3d.get_bone_count():
		bone_cache[i] = skeleton_3d.get_bone_global_pose(i)
	
	for i in skeleton_3d.get_bone_count():
		skeleton_3d.set_bone_global_pose_override(i, bone_cache[i], 1.0, true)
```

**Comment by wagnerfs** [comment]
@smix8 that does change everything, I didn't know it was specific for that call.
Thanks, that does change everything, closing since it's not a bug, but that'd be interesting to have in the docs.
Also, knowing that, wouldn't it be nicer to be able to trigger a bone chain instead of a full armature update?
