### ISSUE TITLE
Tapping Q and E while GridMap node is selected and right-click is pressed down triggers floor change in Editor

### ISSUE THREAD

**Issue by maxbobse** [godotengine/godot#87487]
### Tested versions

4.2.1

### System information

Godot v4.2.1.stable - macOS 14.1.0 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

In the Godot Editor, select the GridMap node in the tree and switch to 3D view. Now click and hold the right mouse button to rotate the camera in the editor. Now tap the Q and E buttons to move the camera up and down. You will notice that it is also changing the active floor of the Gridmap by -1 and +1.

### Steps to reproduce

see above

### Minimal reproduction project (MRP)

[gridMapCameraIssue.zip](https://github.com/godotengine/godot/files/14015826/gridMapCameraIssue.zip)

**Comment by Nodragem** [comment]
yes, Q and E are the Gridmap's shortcut for changing the floor. The solution will be to disable these shortcuts when navigating.

**Comment by maxbobse** [comment]
Is that something that I can change in Godot myself or does it require a bugfix?

**Comment by Nodragem** [comment]
it will probably require a bugfix as we don't want default shortcuts to conflict.
But meanwhile you can simply change the shorcuts here:
![image](https://github.com/user-attachments/assets/2bc73a01-30ee-4e78-afe9-8f27c65804c7)

Note also, that the issue you are facing only happens when you select a Gridmap and did not select a mesh viewer. Once you have a mesh selected, right-click does not activate the `Freelook mode` anymore, it activates the `erase mode` of Gridmap.

I am working on updating the Gridmap interface, and I am actually thinking to move the erase mode to a shortcut key rather than right-click.
