### ISSUE TITLE
exporting to android problem

### ISSUE THREAD

**Issue by Vrx8** [godotengine/godot#8758]
so.. i cant register to forum and the discord stuff.. it never send me any verification code.. i also got ban from irc for no reason and the developer community is a bit dead..  anyone know why it never send me the verification code ? 

main issue :
so i cant export to android.. this is the error..

WARNING: The jar will be treated as unsigned, because it is signed with a weak
algorithm that is now disabled by the security property:

  jdk.jar.disabledAlgorithms=MD2, MD5, RSA keySize < 1024

i already set the keysize to 2048 using -keysize command still not working..
i use this command to create debug key:

keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999

and this..

keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000

and this..

keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -sigalg SHA1withRSA -keysize 4096 -validity 10000 -keysize 2048

none of them are working

it looks like java disable it.. i search it on google on how to activate it.. none of them are working or make sense.. i use the newest version of godot i also try to create the debug key using android studio.. but there is no keytool program there.. i already try to use timestamp stuff.. not working.. i already set the username and pass to androiddebugkey and android.. still not working.. getting the same error..

**Comment by Phil889** [comment]
oh yea.. do anyone cant login to the QnA forum too ? i created an account in the past.. but i decided to make a new one.. and i never get the verification code .. that is the reason i post here steam community is just confusing..

**Comment by RandomShaper** [comment]
Android Studio will generate a debug key for you. Look for it in .android/debug.keystore under your home dir (Linux) or your user directory on Windows. If it's not there, run any project in debug mode and it should generate it then.

Make sure your export settings point to the key file you or Android Studio has created.

**Comment by akien-mga** [comment]
Did you manage to export?

Check your spam folder for confirmation emails after registering to any service, such emails are often misrouted by some email providers.

**Comment by eon-s** [comment]
That "weak signature" error may not be the problem (I got it too).

**Comment by Phil889** [comment]
oh yeah, i managed to export my games, seems like it will work without the
jarsigner at all.

but i dont know if im able to upload it to playstore with that problem,
because you need a signed apk if you want to upload it there.

 but that is ok for now because im not planning to upload any game to
the playstore anytime soon.

**Comment by RandomShaper** [comment]
This might need to be checked, but if a debug export (or one-click deploy) is able to run, the weak signature issue doesn't really matter to you.

As long as your release build (actual export) is signed with a valid developer certificate, Google Play will be happy.

**Comment by eon-s** [comment]
Are you using jdk/openjdk 9? I have problems with jarsigner in that one.

**Comment by efarms** [comment]
I had the same problem. The issue is that Godot has the Signature algorithm: MD5withRSA hard coded. It doesn't matter what you have in your key-chain it will always come out as MD5withRSA. This is now considered weak by Google/Android and is not allowed.  I am going to submit a request for the kind people at Godot Engine to get around to fixing this problem. Perhaps default the Signature algorithm to: SHA256with RSA. For now, I will use a workaround. The only workaround that I have found is to comment out the MD5 restriction from the java.security file located at:
C:\Users\Edwin\Desktop\android-studio\jre\jre\lib\security\java.security

[java.security.txt](https://github.com/godotengine/godot/files/1596889/java.security.txt)

You can read about the issue in the following two links: 

https://guardianproject.info/2015/12/29/how-to-migrate-your-android-apps-signing-key/

https://www.bleepingcomputer.com/news/security/oracle-to-block-jar-files-signed-with-md5-starting-with-april-2017/

If you have any question please email and we'll chat,

Cheers,  Edwin ...

**Comment by juanpaexpedite** [comment]
Just in case you find it useful, I have that error and it is on how the key is created, using the following version C:\Program Files\ojdkbuild\java-1.9.0-openjdk-1.9.0.4-1\bin works even having another java installed
![image](https://user-images.githubusercontent.com/5947026/39290569-ef278e78-4927-11e8-8a9f-75643704fd03.png)
