### ISSUE TITLE
GPUParticles3D Emitter Velocity scales with FPS above 60 when movement is done in physics_process 

### ISSUE THREAD

**Issue by CBerry22** [godotengine/godot#87662]
### Tested versions

Reproducible in 4.2.1 & 4.2.2 RC1

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 31.0.15.4584) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

### Issue description

When a GPUParticles3D node is a child of a Rigidbody3D with Inherit_Velocity_Ratio set to a value higher than 0, the amount of velocity that gets added scales with FPS.

60 FPS behaves as expecting, but running at 120+ FPS makes the particles fling off into the distance and behave erratically.

### Steps to reproduce

Prerequisites; have a monitor with a refresh rate higher than 60hz, or disable VSync in your GPU settings and in the Godot project.

1. Create a Rigidbody3D, apply force to make it move
2. Create a child GPUParticles3D node with Inherit_Velocity_Ratio set to 1.0
3. Run the project at an uncapped FPS and then at 60 FPS, there is a noticeable difference in behaviour.

### Minimal reproduction project (MRP)

[Inherit Velocity MRP.zip](https://github.com/godotengine/godot/files/14074611/Inherit.Velocity.MRP.zip)

**Comment by CBerry22** [comment]
Upon some further experimentation it's not so much to do with Rigidbody3D as it is to do with movement from _physics_process.

Moving a Node3D via translate within _physics_process produces different particle velocity to the same logic running in _process when ran at frame rates higher than 60 fps. 

Here's an updated MRP to demonstrate this:
[Updated Inherit Velocity MRP.zip](https://github.com/godotengine/godot/files/14075571/Updated.Inherit.Velocity.MRP.zip)

**Comment by michal2229** [comment]
For me in this setup (GPUParticles3D node is a child of a RigidBody3D with Inherit_Velocity_Ratio set to 1), particles are behaving erratically even at fixed 60fps. Reproducible on 4.2 and 4.3.beta.

**Comment by Calinou** [comment]
This probably has to do with movement not happening on every rendered frame when movement is done in `_physics_process()`, so the velocity goes from this (as seen by the particle system):

> 2 2 2 2 2 2 2

To something like this:

> 4 0 4 0 4 0 4 0 4 0

To resolve this, there are two solutions:

- Enable [physics interpolation](https://github.com/godotengine/godot-proposals/issues/2753), and make sure the ParticleProcessMaterial uses the interpolated velocity as a basis for the initial velocity. Physics interpolation is available in 2D in 4.3, and it'll be available in 3D in a future 4.x release.
- Make the inherited velocity an *average* of the recent linear velocity of the parent (e.g. over the last 5 rendered frames), instead of the current linear velocity of the parent. regardless of whether physics interpolation is used. This is ultimately a more reliable solution that won't require physics interpolation to work, albeit it means the exact velocity may be slightly delayed from what you see.

cc @QbieShay

**Comment by QbieShay** [comment]
I don't think they should average the 5  last rendered frames: often you use inherited velocity with projectiles or trails, and this will just make particles spawn in front of the character. Is there no way to calculate the velocity uniform in physics process instead?

**Comment by Calinou** [comment]
Emitter velocity is set here:

https://github.com/godotengine/godot/blob/9425535602a526a1b021838a7d021a5d75a62574/scene/2d/gpu_particles_2d.cpp#L713-L722

It looks like it's easy to move this to `NOTIFICATION_INTERNAL_PHYSICS_PROCESS` so that the velocity is only updated once per physics frame, which would make more sense to me.

However, doing so it doesn't fix the issue:

### Velocity update in process (`master`)

*Both videos are rendered at 120 FPS with 60 physics ticks per second. The issue is not present when the rendered FPS is equal or lower to the physics tick rate.*

https://github.com/godotengine/godot/assets/180032/7f660e0a-5b55-477f-b400-873a9fdcadbc

### Velocity update in physics process

https://github.com/godotengine/godot/assets/180032/56568a44-ecfb-4630-9b26-5348f6eab6dc

Maybe updating velocity at the GPUParticles3D' `fixed_fps` rate will help?
