### ISSUE TITLE
Error getting image file from URL

### ISSUE THREAD

**Issue by elvisish** [godotengine/godot#87691]
### Tested versions

3.5.3

### System information

Windows 10

### Issue description

I get an error that just says:
```
 editor/plugins/asset_library_editor_plugin.cpp:828 - Error getting image file from URL: https://raw.githubusercontent.com/HexagonNico/Godot3-FiniteStateMachine/main/icon.svg
```
I didn't even go to the AssetLib and it warned me. According to https://github.com/godotengine/godot/issues/29502#issuecomment-700609294 this is intended, so this bug report is related to that.

### Steps to reproduce

Use godot, it should appear.

### Minimal reproduction project (MRP)

N/A

**Comment by brcontainer** [comment]
404 error:

![image](https://github.com/godotengine/godot/assets/4368952/d1e4e277-c6ad-444e-b533-7affbecb1d99)

It's not a Godot bug, the plugin author changed the repository path to `HexagonNico/Godot-FiniteStateMachine`

> I didn't even go to the AssetLib and it warned me

I'm using Godot v3.5.3.stable.official [6c814135b] and this warning does not appear for me. Because it is a plugin, probably some project on your machine is using it and perhaps that is why it is issuing this warning.

👍

**Comment by YuriSizov** [comment]
Indeed, this is not a Godot bug, and it should only appear when you open the Asset Library tab (because it doesn't load anything until you do). IMO these errors should be hidden normally and only appear in verbose mode, since they really useful to end users. For 4.x I made https://github.com/godotengine/godot/pull/87628, a similarly spirited PR can be created for 3.x.
