### ISSUE TITLE
GPUParticles3D lag spike on first instance

### ISSUE THREAD

**Issue by Midrule** [godotengine/godot#87891]
### Tested versions

4.2.1 Stable

### System information

Windows 10, i7-7700k, RTX2060, 16GB

### Issue description

When emitting a particle for the first time. It'll cause the whole game to pause for a brief moment. This seems to only happen once the first time. But this issue is consistent for all particles used. It seems to be a caching issue, but I'm not sure why it would be this severe. Some particles are super simple, others not, but they all cause this seem stutter. 

I've tested this on multiple different PCs, low + high end. And they all have this same issue, both in builds and editor. Changing the shadow filter quality settings seems to reset it in a way where if I had it on high for example, putting it to any of the other options will restart the process, having all the particles stutter on first instance, and then be completely fine every other time. 

Profiler doesn't seem to show anything specific, but the spikes are pretty obvious.

Running a test, I only triggered half of them, and reloaded the project. The ones I triggered previously were fine but the new ones stuttered. I've been told Godot 4 should cache particles on load but not sure if its just not working here or what not. I've tried manually caching them on load but it seems to make no difference, but I'll mess around with it more...

For the nodes themselves. Some are attached to the player while some are just in the scene tree. I've tried using @onready referencing, accessing as special name, and using restart() instead of emitting == true. 

In the video you can see 3 spikes in the video. The first when the dust clouds pop up, the 2nd when the orange stars and circles pop up and the last when going into the water. This is a stripped down version for this issue, but this same thing happens with any particles as mentioned earlier.

In case its an issue with my project itself. I tried to keep it mostly intact while still being stripped down. Maybe its the way its referenced or something with the drawpass/procress material? Hard to tell

![image](https://github.com/godotengine/godot/assets/59895191/2306ae73-dfd9-434e-8baa-457c947691a0)
![image](https://github.com/godotengine/godot/assets/59895191/06e4b22b-bf21-4b96-9539-412f2b52f9f9)

https://github.com/godotengine/godot/assets/59895191/e83f2171-c16e-45f2-85f9-6c33f2d5a2c6

### Steps to reproduce

Trigger GPUParticles3D node for the first time, one shot or regular.

### Minimal reproduction project (MRP)

[Github Demo.zip](https://github.com/godotengine/godot/files/14150553/Github.Demo.zip)

**Comment by DonKapot** [comment]
I had a similar issue with 2d particles, just solved it with changing mode from Compatibility to Forward+. Maybe it's your case?

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/61233.

As a workaround, display all particles within the view frustum for a single frame when the project starts. (This can be done while a solid ColorRect is shown to hide the particles.)

**Comment by Midrule** [comment]
> I had a similar issue with 2d particles (same 4.2.1 version), just solved it with changing mode from Compatibility to Forward+. Maybe it's your case?

Nah i'm using forward+ so this isn't it

**Comment by Midrule** [comment]
> Thanks for the report! Consolidating in #61233.
> 
> As a workaround, display all particles within the view frustum for a single frame when the project starts. (This can be done while a solid ColorRect is shown to hide the particles.)

Thanks for the answer, as mentioned I tried to to this before but I never tried to make sure they were within the view frustum. It is annoying to have to do this for everything but at least it's a largely known issue in general

**Comment by matheusnicolas** [comment]
I was facing the same issue in 4.3 stable using compatibility mode. Thanks for the comments, folks! I created a Node2D, attached the particles, and it emits once at the scene's instantiation, working fine!

**Comment by Silvanuz** [comment]
I have the exact same problem with GPUParticle2D on Forward+

**Comment by TranquilMarmot** [comment]
For anybody else coming here, this is because `GPUParticles3D`/`GPUParticles2D` create a _compute shader_ that runs on the GPU to calculate particle positions. When you change the `ParticleProcessMaterial` in the editor, you're actually changing parameters in the compute shader - you can even see this if you choose "Convert to Shader Material" under the `ParticleProcessMaterial`.

While the "Shader Baker" export setting / shader precompiler will compile shaders, they only do so for draw passes and will skip over compute shaders.

To get around this, I ended up with:
- Have an `@export var particle_effect_scenes: Array[PackedScene] = []` on my loading screen
- When loading, loop through all of those scenes, `.instantiate()` them, grab all of the `GPUParticles3D` and make a fake copy with the same `ProcessMaterial`
- For each material, set `emitting = true` and call `RenderingServer.particles_request_process(compiler.get_base())` to force it to process at least once
(see also the PR above in somebody else's project that mentions this issue)

Huge pain but worth it to not have the game freeze for many seconds for every new player. Honestly not sure that `GPUParticles3D` are worth it for most effects unless you're doing something with a _lot_ of particles. `CPUParticles3D` will not have this issue since it does not have to compile a compute shader for the GPU.
