### ISSUE TITLE
Signals' `.connect()` function's argument (callable) is not type-checked if it is accessed via `self.`.

### ISSUE THREAD

**Issue by elenakrittik** [godotengine/godot#87944]
### Tested versions

Reproducible in stable 4.2.1 and freshly-built v4.3.dev.custom_build [b4e2a24c1]. In 3.x, only the first line raises an error, which looks like an other issue, so i think this ticket shall only be responsible for 4.x.

### System information

Godot v4.3.dev (b4e2a24c1) - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5123) - AMD Ryzen 7 5800X 8-Core Processor (8 Threads)

### Issue description

When doing `some_signal.connect(my_local_callable)`, Godot checks if `my_local_callable` exists in current scope, and if it does not, raises an error. However, when doing `some_signal.connect(self.my_local_callable)`, Godot does not raise an error even if `my_local_callable` is not defined on base `Self` (or any of it's ancestors).

### Steps to reproduce

Create an empty project, create a script, then paste the following and observe the above-described behaviour.
```gdscript
extends Node

var argument: String = "bar"

signal sig

func _ready() -> void:
	# external signals are broken
	get_tree().create_timer(1).timeout.connect(_foo) # error, good
	get_tree().create_timer(1).timeout.connect(self._foo) # no error?

	# as well as locally-defined ones
	sig.connect(_foo) # error, good
	sig.connect(self._foo) # no error?

	# regular functions still type check properly, so it's an issue
	# with signals specifically
	self.bar(argument) # error, good
	self.bar(self.argument) # error, good

func bar(_arg: int) -> void:
	pass
```

Alternatively, open the MRP provided below.

### Minimal reproduction project (MRP)

[gdscriptselftypebug.zip](https://github.com/godotengine/godot/files/14156978/gdscriptselftypebug.zip)

**Comment by dalexeev** [comment]
It's not about signals and `connect()`, and not even so much about `self` itself. The reason is that `_foo` does not exist in the current class or its ancestors. However, it may exist in the descendants. Although it's not documented (as far as I know), `self` allows you to ignore non-existent properties/methods, just like you would if you used `set()`, `get()`, `call()`.

For example, here the analyzer reports errors regardless of the use of `self`, since the `_foo` property is guaranteed not to be `Callable`:

<details>
<summary>Screenshot</summary>

![](https://github.com/godotengine/godot/assets/47700418/f3127b39-5f51-41f8-b53d-a048f2de3975)

</details>

You can also enable [`UNSAFE_*` warnings](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/static_typing.html#warning-system) if you want stricter behavior:

<details>
<summary>Screenshots</summary>

![](https://github.com/godotengine/godot/assets/47700418/8f8d33ec-d2ea-4091-80cb-44772c6d4978)

![](https://github.com/godotengine/godot/assets/47700418/8d1a1d58-37c9-415c-ab87-0587741007e0)

</details>

**Comment by elenakrittik** [comment]
Oooh, that makes sense, thanks! I can understand this being useful behaviour in some cases, but i imagine most of the time this being accidental. I obviously don't have any data on how much people intentionally look through safe-lines to find "unsafeties", but i think it would be correct to say that more people consider and fix warnings. As such, apart from documenting this feature, do you think changing the default for `UNSAFE_*_ACCESS` rules to `warning` would make sense (and if so, would it require a proposal)?

**Comment by dalexeev** [comment]
> As such, apart from documenting this feature, do you think changing the default for `UNSAFE_*_ACCESS` rules to `warning` would make sense (and if so, would it require a proposal)?

The problem is that users of dynamic GDScript would receive a lot of warnings, some of which are false positives, and the analyzer could potentially infer a soft type without requiring a hard type. This is why the warnings is ignored by default.

In my opinion, we should first improve the static analyzer (this is a complex task) to reduce the number of false positive warnings in dynamic scenarios, then we can consider enabling these warnings by default.

**Comment by elenakrittik** [comment]
> > As such, apart from documenting this feature, do you think changing the default for `UNSAFE_*_ACCESS` rules to `warning` would make sense (and if so, would it require a proposal)?
> 
> The problem is that users of dynamic GDScript would receive a lot of warnings, some of which are false positives, and the analyzer could potentially infer a soft type without requiring a hard type. This is why the warnings is ignored by default.
> 
> In my opinion, we should first improve the static analyzer (this is a complex task) to reduce the number of false positive warnings in dynamic scenarios, then we can consider enabling these warnings by default.

Alright, thank you! I think i'll try adding a small bit of documentation on this tooic soon. Should this issue be moved/re-opened on godot-docs repo?

**Comment by dalexeev** [comment]
> Should this issue be moved/re-opened on godot-docs repo?

No, not required, as far as I know. In practice, we often link issues from other repositories.
