### ISSUE TITLE
MeshDataTool: OBJ file not imported correctly.

### ISSUE THREAD

**Issue by ravengrim** [godotengine/godot#87947]
### Tested versions

Reproducable in: 4.1.2.stable and 4.2.1.stable. Older versions not checked.

### System information

Godot v4.1.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2070 (NVIDIA; 31.0.15.3667) - AMD Ryzen 7 3700X 8-Core Processor (16 Threads)

### Issue description

The OBJ file in the example specifies five vertices, but when I create a MeshDataTool from it, the MeshDataTool duplicates some of the vertices. I set optimize_mesh to false in the OBJ import settings, so I had expected it would create the mesh exactly as specified in the OBJ file. 

### Steps to reproduce

Get the minimal reproduction project and run the project. Compare the console output with the content of the OBJ file.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14157329/MRP.zip) (C#)

**Comment by lawnjelly** [comment]
See #75279.

**Comment by clayjohn** [comment]
The .obj file in the MRP has 5 vertex positions, but it uses them to create 7 different triangles (what OBJ calls "faces"). When Godot imports the mesh, it converts that to a format that the engine can actually use for rendering.

When you create a MeshDataTool from a surface, it keeps all the data from the surface, even if its redundant. Which means it needs to have enough data to reconstruct the 7 triangles (i.e. 21 vertices), so that's what it does. By the time you reach the MeshDataTool you are already many layers removed from the original .obj file so you can't expect the MeshDataTool to return data identical to what the .obj contains

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/75279.

**Comment by ravengrim** [comment]
> The .obj file in the MRP has 5 vertex positions, but it uses them to create 7 different triangles (what OBJ calls "faces"). When Godot imports the mesh, it converts that to a format that the engine can actually use for rendering.

Thanks for the clarification! I must admit, I didn't even notice the strange arrangements of faces in the OBJ file, as I was too focused on the vertices. If I understand it correctly, the mesh contains faces that use the same vertex multiple times. I don't understand why this happens on the blender export, but it's a whole different issue. Thanks!
