### ISSUE TITLE
ScrollContainer creates 2 scrollable areas for single child container

### ISSUE THREAD

**Issue by svencan** [godotengine/godot#87974]
### Tested versions

- Only tested in 4.2.1.stable

### System information

Windows 11, Godot 4.2.1.stable

### Issue description

Setup: 
ScrollContainer has a PanelContainer as a child, which has a VBoxContainer with 2 RichTextLabel.

Expected Result:
The PanelContainer is scrollable.

Actual Result:
The two RichTextLabel are scrollable independantly.

### Steps to reproduce

The MRP contains 3 test cases (test_1.tscn, test_2.tscn, test_3.tscn) with different configurations to attempt 1 scrollable area. The ScrollContainer creates 2 scrollable areas (children count of VBoxContainer) even if I use a PanelContainer as a wrapper (test_2.tscn) or save the PanelContainer as a scene (test_3.tscn).

### Minimal reproduction project (MRP)

MRP: [ScrollContainerBug.zip](https://github.com/godotengine/godot/files/14166850/ScrollContainerBug.zip)

**Comment by rsubtil** [comment]
`RichTextLabel` nodes have an internal scroller that's enabled by default. In order to disable this behvaior, you need to enable `Fit Content`, which forces the label to grow according to the text size.
![image](https://github.com/godotengine/godot/assets/6501975/74c238b8-ebeb-4d27-b63c-ea85f7154bf7)

**Comment by svencan** [comment]
WHOOPSIE my bad.
To be fair this is kind of unexpected behaviour by default.

Thank you.
