### ISSUE TITLE
Yellow atlas source warning exclamation mark is REALLY hard to see in light mode

### ISSUE THREAD

**Issue by PinkSerenity** [godotengine/godot#87987]
### Tested versions

- Reproducible in v4.2.1.stable.official [b09f793f5], v4.3.dev2.official [352434668]

### System information

Windows 10.0.22631 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 4080 Laptop GPU (NVIDIA; 31.0.15.4633) - 13th Gen Intel(R) Core(TM) i9-13900HX (32 Threads)

### Issue description

When there is an issue with the tiles of an atlas source, a yellow exclamation mark will warn the user about it. When hovering, it might show useful information, like "The current atlas source has tiles outside the texture" or something like that. Unfortunately, it is really hard to see in light mode:
<img width="331" alt="image" src="https://github.com/godotengine/godot/assets/41524896/e07f29be-c050-4af5-a345-768ae55743be">
While you certainly notice that it's there if you know about it, when I wondered why I'm getting so many errors I tried debugging for at least an hour before I learned of its existence online.

### Steps to reproduce

1. Set your Editor to light mode
2. Create a tile texture, a tileSet and an atlas source loading the texture.
3. Add tiles to the atlas source.
4. Edit the texture and remove some tiles.

### Minimal reproduction project (MRP)

[Exclamation.zip](https://github.com/godotengine/godot/files/14170756/Exclamation.zip)

**Comment by rsubtil** [comment]
A similar yellow warning icon (for node and script warnings) is handled properly in this scenario:

| Dark Theme | Light Theme |
|-|-|
|![image](https://github.com/godotengine/godot/assets/6501975/7a4fa471-0cbe-49b6-abdc-b046cef988c6) | ![image](https://github.com/godotengine/godot/assets/6501975/52bde2c1-deed-40e6-9e34-302f49eceeaa) |

However, for some reason, this particular icon (`StatusWarning.svg`) is being ignored, so no color conversion is allowed: https://github.com/godotengine/godot/blob/36e943b6b20cb7a8a89bc30489c4a81c3e149d74/editor/themes/editor_color_map.cpp#L174

**Comment by rsubtil** [comment]
So, this (and other icons) were added to the exception list in https://github.com/godotengine/godot/pull/15817. The node warning was also added on this PR, but was removed with https://github.com/godotengine/godot/pull/51220 due to the similar visibility issue.

So it seems safe to remove this icon from the list as well. It should also fix a couple of other scenarios:
![image](https://github.com/godotengine/godot/assets/6501975/220c8ec2-bd24-4e48-a63b-f6d3ec968b2c)
![image](https://github.com/godotengine/godot/assets/6501975/7481d35c-608b-48e3-a5fd-358666b23df5)
![image](https://github.com/godotengine/godot/assets/6501975/0e544f18-6afd-4749-91e9-4c7034a949ba)

**Comment by RobProductions** [comment]
To extend off of this, the "Debugger" tab font color is now also impossible to read for me on v4.3.dev (current master) 
![image](https://github.com/godotengine/godot/assets/11141862/b0965bd7-edb1-4b08-81a7-03a3a18a74e9)

Not sure if the colors have changed since 4.2 as it seems a little brighter than the screenshots you have above

**Comment by rsubtil** [comment]
@RobProductions I've just tested it on the latest commit (5f05e2b9b1a3fedcdd7ecb2ab976a2687fd6f19a), before and after applying #88058, and I can't reproduce that. Can you try out the CI build (https://github.com/godotengine/godot/actions/runs/7949675459) and see if it still occurs? And if yes, provide more details about your setup/settings?
