### ISSUE TITLE
C# Doesn't work at all in Godot's C# version

### ISSUE THREAD

**Issue by Caferino** [godotengine/godot#88004]
### Tested versions

Reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Pop!_OS 22.04 LTS with .NET 8.0.101 - v4.2.1.stable.mono.official Forward+

### Issue description

Have been struggling with getting C# to work in a brand new project. There is no actual answer that solves this online, I have explored the other github issues, asked in discord, in the youtube video of the tutorial where it works just fine but not in my machine and I can't find why. Have done everything: editing $Paths in bash, trying .NET 6.0.26 first, then 8.0.101, all alone, no conflict between them. None works, I get the same errors:
![Screenshot from 2024-02-05 19-16-12](https://github.com/godotengine/godot/assets/31547371/7a4052cf-38f1-4666-8027-a8a80b26a2e2)
![Screenshot from 2024-02-05 19-15-43](https://github.com/godotengine/godot/assets/31547371/3b42fdeb-2768-4c17-8393-cfdfb528e58f)

### Steps to reproduce

Starting the project with C# being used in it.

Doesn't matter if the file, node and class are named exactly the same, it won't work. For example:

> using Godot;
> using System;
> 
> [Tool]
> public partial class Chunk : StaticBody3D 
> {
> 	// Unecessary code
> }

I genuinely think the conclusion is that there is just no way to fix this for some users with weird laptops like me, it's a very, very niche problem, there's not really anything that has worked out there, I probably need a new distro or an entire new machine; have dealt with so many unsolved issues like these before, it's too much.

Chunk.tscn, Chunk.cs and Chunk are the names set, yet, it says I should verify that no matter what.

### Minimal reproduction project (MRP)

[MRP.zip](https://github.com/godotengine/godot/files/14173857/MRP.zip)

**Comment by Caferino** [comment]
Think something weird is going on with that, because when the command is ran, this is the output:
>caferino@caferino:~$ dotnet --list-sdks
>8.0.101 [/home/caferino/.dotnet/sdk]

Digged into that and found out that Godot is exclusively searching for the ".dotnet" folder in /usr/share instead of /home/caferino where it was originally installed following the instructions in Microsoft's website.

Encountered that error after deciding to delete all the .NET versions installed in the machine while struggling with the same error, but for version '6.0.26', and fixed it by either creating a symbolic link that connected the .dotnet folder inside /usr/share.

Your suggestion reminded me that there is a "Environment Variables" field in `dotnet --info`:

> caferino@caferino:~$ dotnet --INFO
> Host:
>   Version:      8.0.1
>   Architecture: x64
>   Commit:       bf5e279d92
> 
> .NET SDKs installed:
>   8.0.101 [/home/caferino/.dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 8.0.1 [/home/caferino/.dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 8.0.1 [/home/caferino/.dotnet/shared/Microsoft.NETCore.App]
> 
> Environment variables:
>   DOTNET_ROOT       [/home/caferino/.dotnet/sdk]
> 
> global.json file:
>   Not found

It was empty at first, but added one by adding this line in ~/.bashrc (`nano ~/.bashrc`):
export PATH="$PATH:$HOME/dotnet"   # Had to manually add this one too to use dotnet commands in my terminals
export DOTNET_ROOT=/home/caferino/.dotnet/sdk 


I am coming after doing a lot of different combinations to see if it could be this the issue:
- Trying DOTNET_ROOT = `/home/caferino/.dotnet/sdk`, `/home/caferino/dotnet/sdk`, `/usr/share/dotnet/sdk `, `/user/share/dotnet/sdk` to no avail yet
- Removed the '.' in the folder's name
- Using symbolic link or copying the entire dotnet folder and pasting it in usr/share, also editing the Paths accordingly for both, using '.dotnet' and 'dotnet' as the folder's name...

Still no luck, but feels close now, maybe, I will keep trying combinations regarding this, maybe I missed one in specific..

**Comment by nongvantinh** [comment]
No, your attempt will not yield meaningful results. Look at the source code. There is a function called `FindDotNetExe` which will call `OS.PathWhich("dotnet")`. It will search for the path to `dotnet` in the `PATH` environment variable.

Because you are only exporting the path instead of adding it to the variable, your exported path will only have an effect in your current terminal. However, Godot uses an internal process, so it will not be able to find `dotnet` in the `PATH` environment variable.

Open your `/etc/environment` file and append your `dotnet` path to it. Afterwards, you might need to reboot your device or use the command `source /etc/environment` for the changes to take effect.

**Comment by nongvantinh** [comment]
I'd suggest you solve it properly using the programmer's approach. Instead of guessing infinite reasons that could cause the error, you should debug your Godot binary to see what is lacking on your device.

While I was fixing bugs in the engine, I wrote a small Python script that compiles the mono version of the engine. There are also some configurations to debug the code using Visual Studio Code. However, it has only been tested on my Windows 11 laptop. For you, you will need to tweak some parameters.

Here is the script and my configurations. You can modify it to suit your needs and trace the error yourself.
[mono_compile.zip](https://github.com/godotengine/godot/files/14174770/mono_compile.zip)

**Comment by raulsntos** [comment]
> Digged into that and found out that Godot is exclusively searching for the ".dotnet" folder in /usr/share instead of /home/caferino where it was originally installed following the instructions in Microsoft's website.

The official Microsoft recommendation is to use your distro's [package manager](https://learn.microsoft.com/en-us/dotnet/core/install/linux#packages) to install the .NET SDK, but it sounds like you used the [script installer](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script#purpose) which is only meant to be used in CI and not to setup a dev environment.

If you used the script installer, you have to do some additional configuration as described in the Microsoft documentation. But I still encourage you to consider installing the .NET SDK using your distro's package manager.

For Pop OS you should be following the instructions for [Ubuntu](https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu), since Pop OS is an Ubuntu derivative. In Pop OS 22.04, you should be able to get it from the included feed so all you need to do is:

```
sudo apt-get update && \
  sudo apt-get install -y dotnet-sdk-8.0
```

**Comment by Caferino** [comment]
Thank you so much to both of you, the issue has been **solved**! Thank you, @nongvantinh, for the script you shared with me, I've never done something like this before: writing a script or using python to debug a big program, I'm still a big newbie in a lot of software, but I will learn how to use it, it's cool and I want to know how to debug Godot and customize it someday, no matter how long it takes, weeks or years.

---
### I'm going to share my steps in case someone else needs them:

> 
> ```
> sudo apt-get update && \
>   sudo apt-get install -y dotnet-sdk-8.0
> ```
At first, using this command felt odd because I believe it installed the ".dotnet" folder (maybe hallucinated), but with these errors:
> Reading state information... Done
> E: Unable to locate package dotnet-sdk-8.0
> E: Couldn't find any package by glob 'dotnet-sdk-8.0'
> E: Couldn't find any package by regex 'dotnet-sdk-8.0'

I ignored them because I saw the .dotnet folder and thought it was going to be fine. I did try installing dotnet with the script yesterday, before posting here, but gave up due to the extra configurations needed as the website suggested. However, today, after removing everything .NET related and executing it again, it worked flawlessly and the error in Godot kissed my machine goodbye. Followed this response as complement to this: https://stackoverflow.com/questions/77498786/unable-to-locate-package-dotnet-sdk-8-0

After deleting old stuff and still seeing the errors above, was told that the Microsoft's repository was missing in my machine, so it had to be added first with:
> wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
> sudo dpkg -i packages-microsoft-prod.deb
> rm packages-microsoft-prod.deb

And then run these, which adds 'dotnet-host' too, which I think is also needed because it seemed to carry hostfxr, an important file for Godot:
> sudo apt-get update
> sudo apt-get install -y dotnet-host
> sudo apt-get install -y dotnet-sdk-8.0

---
Now, only the C# "Make sure the script exists and contains a class definition with a name that matches the filename of the script exactly" error persists. Thought that maybe it was going to get fixed by connecting the SDK properly, but not yet. I am going to investigate that one further before seeking help, didn't knew it was going to be a separate issue, my bad for that. This is also my very first issue ever in Github lol, I will "Close with comment", but not sure if that's the best etiquette here, I'll give it a shot.
