### ISSUE TITLE
Allow update/import of assets without opening editor

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8803]
**Operating system or device - Godot version:**
ubuntu + arch

**Issue description:**
It would be extremely handy and time saving to have a way to check for updated assets before loading the game, or even during the game.
Such as a commandline argument.
This would save having to open the editor just to update the textures/meshes etc.
Having blender open, the editor and the game, gets tedious switching back and forth between them all.

**Comment by reduz** [comment]
this would be useful, but itś quite some work, kicking to 3.1

**Comment by akien-mga** [comment]
Moving to the next milestone as 3.1 is now feature frozen.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
