### ISSUE TITLE
LOD is not working (also for particles)

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#8806]
_bugsquadedit: issue was opened when the newest commit was: 787dad5ac4341a90ecf135884d8ca71bdbd5d252_

---------------
**Operating system or device - Godot version:**
arch + ubuntu

**Issue description:**
Make a particle system, add some lod. Test ingame and youll notice its always visible...

**Comment by nunodonato** [comment]
LODs are not working for anything

**Comment by reduz** [comment]
sorry, will fix in 3.1 as the lod system is complex and we kinda ran out of time

**Comment by supagu** [comment]
Hey Guys,

Just wondering if any work has been done on this one yet?

**Comment by avrame** [comment]
Yeah, LODs don't seem to be working for me either.

**Comment by reduz** [comment]
LOD will be properly rewritten in 3.2

**Comment by valdemar-const** [comment]
> LOD will be properly rewritten in 3.2

![image](https://user-images.githubusercontent.com/34628355/50706103-ede1f900-106d-11e9-9d05-a6aa051bcbee.png)

**Comment by Toshiwoz** [comment]
Another happy user that will be even happier with LOD (and terrain?) implemented.

**Comment by Antokolos** [comment]
Hi, guys, maybe someone can point me to the 3.0.X version where LOD system is not broken yet?
Unfortunately it is not very good for us to wait for Godot 3.2, which I think will be released not earlier than 2020 :)

**Comment by Calinou** [comment]
I don't think LOD is available in 3.0.x. There's a [pull request](https://github.com/godotengine/godot/pull/20489) that implemented LOD for an earlier version of 3.1 (before it even was in alpha), but it won't be merged as a more robust implementation should be written for 3.2.

**Comment by Antokolos** [comment]
@Calinou , thanks, got it! Well, we'll try to make our game without LODs then )
Just a note for Godot core developers: I like the engine very much and I value the hard work that you've done so far, but pushing issues like this one or this: https://github.com/godotengine/godot/issues/13954 or this: https://github.com/godotengine/godot/issues/9786 to 3.2 is very sad. IMO you should concentrate on fixing the things that are CRITICAL for any 3D game before implementing anything else, I think a lot of people will agree with this.
At the time being I am forced to create ugly hacks in scripts, just because the game will be too unoptimized and slow otherwise.

**Comment by supagu** [comment]
What I did in my game just this last week was made a special node: LODGroup which has some ranges setup and switches children based on distance from camera. This is sufficient for what I need, this is how Unity seems to do it.

**Comment by Antokolos** [comment]
@supagu , thanks for the advice! Looks like a good solution for this problem.

**Comment by clayjohn** [comment]
Im am closing this in favour of godotengine/godot-proposals#692 which has the most up-to-date discussion.

It is better to keep all the discussion in one place.

FYI LOD is planned for 4.x now. It is a very important feature and we want to make sure we do it right.
