### ISSUE TITLE
The app crashes on Android when using SHA256 from System.Security.Cryptography

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#88098]
### Tested versions

Godot Engine v4.2.stable.mono.official.46dc27791

### System information

Windows 11 Pro

### Issue description

When testing my app on Windows 11 Pro, everything functions properly. However, when exporting it to an Android device, it crashes.

### Steps to reproduce

Simply calling `SHA256 sha256 = SHA256.Create();` in the code and exporting it to an Android device will crash the app.

### Minimal reproduction project (MRP)

[crashSHA256.zip](https://github.com/godotengine/godot/files/14209424/crashSHA256.zip)

**Comment by akien-mga** [comment]
This is probably the same root cause as #84559.

**Comment by raulsntos** [comment]
Thanks for the report, I'll close it to consolidate in https://github.com/godotengine/godot/issues/84559 because I think they're the same issue.

Currently .NET Android exports use the `linux-bionic` runtime identifier which doesn't support the JNI that is required for crypto APIs. This means that you have to provide the OpenSSL library yourself, if you are able to package libssl.so and libcrypto.so into the APK it should fix your issue.

There's a new PR that changes the way Android exports work to use the `android` runtime identifier instead. This allows us to use the JNI for crypto support, so it should fix the issue without having to manually provide libssl.so and libcrypto.so.
- https://github.com/godotengine/godot/pull/88803
