### ISSUE TITLE
Object count skyrockets using TileMap runtime updates.

### ISSUE THREAD

**Issue by DuneTruffle** [godotengine/godot#88166]
### Tested versions

produced in v4.2.1.stable.mono.official [b09f793f5]

### System information

windows 11 - v4.2.1.stable.mono.official [b09f793f5]

### Issue description

object count and memory consumption sky rockets when hiding and showing the tilemap after the scene is run

### Steps to reproduce

1. open project
2. run scene
3. hide and show the Tilemap in the editor while the scene is running
4. observe object count skyrocketing

### Minimal reproduction project (MRP)

[minimum reproduce.zip](https://github.com/godotengine/godot/files/14227817/minimum.reproduce.zip)

**Comment by lavish123409** [comment]
I am trying to reproduce the issue on my machine.
![image](https://github.com/godotengine/godot/assets/57138717/abf95e74-216e-4eba-b4d7-fe1252a073eb)

I do not know where to see the object count in it. Like the object inside tilemap is constant (i.e., Settlement Camera) in the Remote area, so I am confused where to look for it.

**Comment by Zireael07** [comment]
The object count is in the debugger tab

**Comment by kleonc** [comment]
@DuneTruffle From the [`bug_report` template](https://github.com/godotengine/godot/blob/4e990cd7e51d17cf24f854cc33b2715eaa27200f/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L70):

>   - **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

Here's a simplified GDScript version of the script from the MRP:
```gdscript
extends TileMap

func _ready() -> void:
	var mapDimensions: int = 16
	for y in mapDimensions:
		for x in mapDimensions:
			set_cell(0, Vector2i(x, y), 0, Vector2i(0, 0))

func _use_tile_data_runtime_update(layer, coords):
	return true

func _tile_data_runtime_update(layer, coords, tile_data):
	pass
```
The issue still happens:
![dev x86_64_QKx73iiyU0](https://github.com/godotengine/godot/assets/9283098/8873ef85-e246-45c7-ad36-40ecfe2eb3a5)

So using C# is unrelated in this case.

Same in a release-export:
![qpnmnCbIyo](https://github.com/godotengine/godot/assets/9283098/39688667-6363-4b92-b1ec-66bd30bbbd49)
```gdscript
func _process(delta):
	%Label.text = "%d" % [Performance.get_monitor(Performance.OBJECT_COUNT)]

func _on_button_pressed():
	visible = !visible
```

So not an editor issue.

Can reproduce since v4.2.dev5.official [e3e2528ba] (doesn't happen in 4.0.x, 4.1.x).
So likely a regression from #81070. cc @groud
