### ISSUE TITLE
OS.get_resource_dir() no longer part of OS

### ISSUE THREAD

**Issue by supagu** [godotengine/godot#8833]
**Godot version:**
Master branch.

Looks like OS.get_resource_dir() is no longer bound for use in gdscript which I am using.

**Comment by akien-mga** [comment]
You say "no longer", but was it ever bound? I don't see it in the 2.1 documentation either: http://docs.godotengine.org/en/stable/classes/class_os.html

**Comment by reduz** [comment]
Remember that It's a function only useful for editor tools at most, and
should never be used in-game, as it's not portable

On May 19, 2017 10:46 AM, "Rémi Verschelde" <notifications@github.com>
wrote:

You say "no longer", but was it ever bound? I don't see it in the 2.1
documentation either: http://docs.godotengine.org/
en/stable/classes/class_os.html

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/8833#issuecomment-302707159>,
or mute the thread

**Comment by supagu** [comment]
yeah i use it with OS.execute for some internal tools (I do not think this translates res:// type paths if i recall, but i may be wrong on this recollection). It must have been exposed at some stage, maybe in an earlier version of godot 3 as its in my code. If you don't want to expose it that is also alright, I have a work around that exposes it through my own C++ plugin.

**Comment by reduz** [comment]
closing, this function is kind of misleading, prefer not to expose unless we get more requests
