### ISSUE TITLE
Scons does not build when passing arguments that contain `scons vsproj=yes` 

### ISSUE THREAD

**Issue by nongvantinh** [godotengine/godot#88388]
### Tested versions

Current master branch at: a9bb8509f2faac81bdb995c6c89a5347372f3498

### System information

Windows 11 Pro

### Issue description

When Invoke scons with `vsproj=yes` it does not execute the build step :

```
PS D:\VisualStudios\godot> scons platform=windows dev_build=yes dev_mode=yes  module_mono_enabled=yes vsproj=yes
scons: Reading SConscript files ...
Auto-detected 16 CPU cores available for build parallelism. Using 15 cores by default. You can override it with the -j argument.
Found MSVC version 14.3, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
NOTE: Developer build, with debug optimization level and debug symbols (unless overridden).
Regenerating godot.vcxproj.filters
PS D:\VisualStudios\godot>
```

### Steps to reproduce

 scons platform=windows dev_build=yes dev_mode=yes  module_mono_enabled=yes vsproj=yes

### Minimal reproduction project (MRP)

[git clone ](https://github.com/godotengine/godot.git)

**Comment by akien-mga** [comment]
This is intended, the `vscode` logic was changed in https://github.com/godotengine/godot/pull/84885 to only generate the solution, so you can then build in Visual Studio.

If you still want it to also build after generating the solution, there's a `vsproj_gen_only=no` option you can use. Or just re-run the command without `vsproj` if you intend to compile on the command line instead of in VS.
