### ISSUE TITLE
Editor Setting `text_editor/appearance/lines/word_wrap` set to "Boundary" ignores tabulation

### ISSUE THREAD

**Issue by Torguen** [godotengine/godot#88478]
### Tested versions

v4.3.dev3.official [36e943b6b]

### System information

w10 64

### Issue description
This does not happen in 3.x
As you can see in this image, the "Boundary" option does not respect the indentation and the text is "unboxed".

![Captura4](https://github.com/godotengine/godot/assets/19652075/219f4694-e95c-4076-9b47-e6aa726fae42)

In this image you can see what I mean:

![Captura5](https://github.com/godotengine/godot/assets/19652075/d61dc234-ff50-410e-ac32-9cb4543ef7f4)

### Steps to reproduce

See the image

### Minimal reproduction project (MRP)

...

**Comment by Torguen** [comment]
With all due respect, friend, but what is the discussion?
In 3.x it always worked well, now in 4 that happens, what should be discussed?.

**Comment by Mickeon** [comment]
This is not marked as a "bug" because @AThousandShips (probably) feels like that's subjective.
This is a "discussion" because the "fix" may not as simple as imagined. It may break other things in the editor that display similarly, hence it's worth discussing and threading carefully.

What you refer to is a big vague in both the name and description of this. I assume you mean "Editor Setting `text_editor/appearance/lines/word_wrap` set to "Boundary" ignores tabulation", which when put that way, definitely sounds good, especially if it worked that way in 3.x.

**Comment by Torguen** [comment]
Well what can I say?
I believe that the correct behavior is what it has in version 3.x.
If that behavior can be implemented in version 4 then I think it is correct.

**Comment by AThousandShips** [comment]
Marked as a discussion because of the phrasing of the issue, now it's more clear :) just based it on what seemed you be your view, hard to know
