### ISSUE TITLE
3D | PathFollow | Condition ' det==0 ' is true

### ISSUE THREAD

**Issue by wf192** [godotengine/godot#8848]
**Operating system or device - Godot version:**
O.S.: Ubuntu 16.04 LTS
Godot: Godot Engine v2.1.3.stable.official

**Issue description:**
Path follow can't watch downwards; the mesh or whatever you move, dissappears.

**Steps to reproduce:**
The Curve3D on the parent path, must have 2 or more 3D points with Z,X equal axis, Y can be different.

**Link to minimal example project:**
Attached
[GodotBUg.zip](https://github.com/godotengine/godot/files/1016428/GodotBUg.zip)

**Comment by eon-s** [comment]
Only happens with rotation mode XY and XYZ, editing current curve too.

The remote inspector shows scale `(0,0,1)` on the PathFollow.

**Comment by tagcup** [comment]
I couldn't reproduce this on 3.0, is there anything special that needs to be done to trigger this?
I'm seeing `Scale: (1,1,1)` in the remote inspector

**Comment by eon-s** [comment]
@tagcup This is exported for 3, I have modified it a bit trying other ways to set the points, this uses a resource file for the curve.

[pathbug.zip](https://github.com/godotengine/godot/files/1019763/pathbug.zip)

Scale on PathFollow shows (-0,-0,-1)

**Comment by tagcup** [comment]
Godot assumes that Basis of objects are orthonormalizable matrices.
In the file you attached, the Transform of the PathFollow node is set to
`transform = Transform( 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 )`
This is a singular matrix, which is not invertible. See the documentation of Basis for details.

**Comment by tagcup** [comment]
The property editor can be improved to prevent users from entering invalid transforms I guess.

**Comment by eon-s** [comment]
@tagcup yes, happened once on 2.1.3 too, no idea how triggered it to modify the transform on the scene but stayed broken affecting the children, really weird.

**Comment by tagcup** [comment]
Maybe there is something wrong with the curve data?

**Comment by eon-s** [comment]
@tagcup but why works fine without rotation or only Y rotation? 
The rotation method (XY and XYZ) is breaking the curve?

**Comment by eon-s** [comment]
I have not noticed this on 2.1.3 but on 3, setting rotation from none/Y to XY/XYZ changes the scale to `(-0,-0,-1)` directly on the inspector.

**Comment by tagcup** [comment]
I can check it, but the current `PathFollow::_update_transform` doesn't make much sense to me.

Can anyone know hows Path is supposed to work can confirm whether this is true or not?
We have a vector field (Curve3D) on a 1D path embedded in 3D space, and the way PathFollow works is that the object that moves along this path should also rotate itself the same way the vector field (as defined in Curve3D) rotates.

If that is true, this vector field (in the `curvetest.tres` you attached) is malformed

```
PoolVector3Array( 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -10, 0 )
```

because such a thing can only vector in a normalized vector field, whereas here, most of the vectors are just null vectors except for the last one which isn't normalized.

For sure we can normalize the input to make things easy for the users, but we can't really normalize a null vector.

**Comment by tagcup** [comment]
A few things I'm not clear about:

* what does "look-at axis" mean exactly?
* what is offset for?
* is tilt the angle of rotation between two neighboring vectors in the Curve3D?

**Comment by eon-s** [comment]
@tagcup if it is like the 2D curve, that array is something like in, out, point, in, out, point (if I'm not confused with that structure), the equivalent to a new curve with point 0 on (0,0,0) and 1 on (0,-10,0), all in and out on (0,0,0), is really fun when you have to edit curves resources manually (not).

You can remove the curve from the path and replace it with

```
	var curve = Curve3D.new()
	
	curve.add_point(Vector3(0,0,0),Vector3(0,0,0),Vector3(0,0,0),0)
	curve.add_point(Vector3(0,-10,0),Vector3(0,0,0),Vector3(0,0,0),1)
	path_node.set_curve(curve)
```

The result (error) is the same.

-------------------

I cannot help more on the implementation, just can mention that offset is the distance from 0 on the baked curve and tilt seems to be used for a soft rotation between points.

**Comment by tagcup** [comment]
Yes, I understand that part. But my questions are about how is that data is supposed to be used as the object follows the curve

**Comment by tagcup** [comment]
> The result (error) is the same.

It gives errors about baking

> ERROR: interpolate_baked: No points in Curve3D
   At: scene/resources/curve.cpp:1054.
ERROR: interpolate_baked_tilt: No tilts in Curve3D
   At: scene/resources/curve.cpp:1098.

**Comment by eon-s** [comment]
Cleaned a bit the project, just a few lines on path (godot 3 style) and process once (throws 25 errors).

[pathbug2.zip](https://github.com/godotengine/godot/files/1020420/pathbug2.zip)

Errors here (not latest build):

> ERROR: orthonormalize: Condition ' determinant() == 0 ' is true.
>    At: core/math/matrix3.cpp:77.
> mesege
> ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Undefined behaviorID: 131222	Severity: Medium	Message: Program undefined behavior warning: Sampler object 0 has depth compare enabled. It is being used with depth texture 142, by a program that samples it with a regular sampler. This is undefined beahvior.
>    At: drivers/gles3/rasterizer_gles3.cpp:123.
> ERROR: invert: Condition ' det == 0 ' is true.
>    At: core/math/matrix3.cpp:66.
> 

Then continue with the last 2 lines (22 times I suppose).

**Comment by eon-s** [comment]
Here is the correct project
[pathbug2-fixed.zip](https://github.com/godotengine/godot/files/1020436/pathbug2-fixed.zip)

**Comment by tagcup** [comment]
It probably got lost among many other errors, you can try PR #8870. But anyway, curve baking stuff doesn't matter, I can simply edit curvetest.tres manually.

**Comment by eon-s** [comment]
With the PR mentioned above and the last project example, the pathfollow does not work (offset does not change), and got just one error on any mode:

> ERROR: set: Condition ' determinant() == 0 ' is true.
>    At: core/math/matrix3.h:149.

But may not be related, is hard to test more because I can't type on that build...

**Comment by tagcup** [comment]
Anyway, unless somebody can tell me the answers [to these questions](https://github.com/godotengine/godot/issues/8848#issuecomment-303228107), I can't be much of a help.

**Comment by tagcup** [comment]
I pushed an update to that PR, and rebased it against the current master (in which the input is working  hopefully, otherwise you can edit the .tscn file manually).

Some things that need to be answered:

* Not using `tilt`. Not sure what `tilt` represents. A rotation angle, with respect to which axis? Even in the current code, it is only used for `ROTATION_XYZ`, so I think `tilt` stuff is broken in the current tip. Can I just ignore it?
* Assumes `ROTATION_Y` refers to the global Y-axis.
* I assumed `ROTATION_Y` means rotate only along the Y-axis.
* `ROTATION_XY` is ignored in the current tip, the PR handles it.
* I assumed `Curve3D::interpolate_baked` can extrapolate, needs checking

The new implementation performs a parallel transport along the curve, and also doesn't suffer from det == 0 kind of issues. You can still get that kind of errors if you have a node with invalid transform (for which you either need to edit the .tscn file or fix in the editor, if you have such bad nodes remaining from old runs), what I'm saying is that it's not PathFollow shouldn't lead to such problems anymore.

**Comment by tagcup** [comment]
Pushed another update to the PR, I handled tilt assuming that it's a rotation around the tangent vector.

**Comment by eon-s** [comment]
Ok... I have made some mistakes between the many crashes, but finally managed to test it correctly and seems ok.

Just got a 

> ERROR: set: Condition ' determinant() == 0 ' is true.
>    At: core/math/matrix3.h:149.

But seems to happen on any scene on this build

-------------

I'm not sure what to expect from the rotation restrictions, I hope @reduz can shed some light on that.

**Comment by tagcup** [comment]
Ah, yes, I'd like to do that too, if @reduz gives a green signal to the `PathFollow` PR. That'd be a compatibility breaking change, of course, so it should be done before 3.0.

**Comment by tagcup** [comment]
> But seems to happen on any scene on this build,

I think I caused that with a typo, sorry! Updated the PR.

**Comment by tagcup** [comment]
By the way, is it just me or is the curve editor gone? I don't remember seeing an issue for that.

**Comment by tagcup** [comment]
OK, found the issue: [here](https://github.com/godotengine/godot/blob/master/servers/physics/body_sw.cpp#L48), `_inv_inertia` is zero, which then leads to a infinitely large inertia tensor, while still assuming that inertia tensor is an orthogonal matrix (which is of course not).

I'm not much familiar with Godot's physics code yet (@reduz maybe?) so I don't know what that object with infinite mass represents, but for sure it's not related to PathFollow stuff.

**Comment by tagcup** [comment]
Almost forgot about this, I need to submit a PR to implement parallel transport for PathFollow2D
