### ISSUE TITLE
Build failure on several platforms after InputEvent changes

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#8849]
**Operating system or device - Godot version:**
Windows, iOS, OSX, maybe others - 5b3709d

**Issue description:**
The massive refactor of InputEvent into a series of objects broke the compilation on at least Windows, iOS and OSX according to Travis: https://travis-ci.org/godotengine/godot/builds/234395343

Most likely all non-X11 platforms need fixing, as @reduz only made sure his development platform was compiling and running fine (and given the amount of code that had to be changed, we can't blame him :)).

**Comment by RebelliousX** [comment]
In windows at least, travis build shows error in:
line 71 `InputModifierState mod_state` because reduz deleted the structure `InputModifierState`
```
	struct KeyEvent {

		InputModifierState mod_state;
		UINT uMsg;
		WPARAM wParam;
		LPARAM lParam;
	};
```

The deleted struct is in file `input_event.h` line 140, and I believe it was replaced with `class InputEventWithModifiers : public InputEvent ` in line 173. So a quick rename of all occurrences might fix the issue.

I could be wrong though, I can't test right now.

**Comment by reduz** [comment]
I tried to fix most platforms but didn't test..

**Comment by toger5** [comment]
I might can check osx. `Ev.get_factor() = something` seems to be wrong.
Or i dont know enough about cpp...

**Comment by reduz** [comment]
likely needs to be replaced by set_factor()

**Comment by akien-mga** [comment]
OSX fixed by #8853. You can check that PR to see what likely needs to be done in the other platforms.

**Comment by akien-mga** [comment]
Windows fixed by #8876 and iOS fixed by #8877.

**Comment by akien-mga** [comment]
Left to review:
- [ ] Android
- [ ] Javascript
- [ ] UWP

**Comment by eska014** [comment]
#9271 fixes the JavaScript platform

**Comment by akien-mga** [comment]
All main platforms were fixed, the rest will be fixed as soon as someone has a look at them.
