### ISSUE TITLE
C#: Reloading unregistered CSharpScript makes it embedded in scene.

### ISSUE THREAD

**Issue by zaevi** [godotengine/godot#88543]
### Tested versions

v4.3.0.dev.mono.custom_build [a92921ae4]

Not reproducible on 4.2.1.

### System information

Godot v4.3.0.dev.mono (a92921ae4) - Windows 10.0.22621 - Vulkan (Mobile) - dedicated NVIDIA GeForce RTX 2050 () - 12th Gen Intel(R) Core(TM) i5-12500H (16 Threads)

### Issue description

If a C# script is not registered (or not build) and is reloaded after external modification, it loses its `resource_path` and can be embedded in scene.

Related to https://github.com/godotengine/godot/issues/88160#issuecomment-1940465237

Edit: I didn't change anything about external settings like `dotnet/editor/external_editor`. It's all by default.

### Steps to reproduce

1. New project, new scene.
2. Attach new C# script and save. Don't build now and keep the build-in script editor open.
3. Modify the script on external editor.
4. Turn to editor and the Reload dialog will be shown. Click `Reload`.
5. The script become `[unsaved]` and if you save now, it will turn like `res://Main.tscn::CSharpScript_tlpw1`

(If build in step 2, you won't have this issue)

### Minimal reproduction project (MRP)

N/A

**Comment by zaevi** [comment]
https://github.com/godotengine/godot/assets/12966814/367ade35-1a94-46a3-bab1-3ecb14718b22

**Comment by zaevi** [comment]
Confirmed that it's #85504 that takes over the CSharpScript's path.

When build-in ScriptEditor reloads a script, it loads an extra script (with `CACHE_MODE_IGNORE`) and copy its `source_code` to current script:

https://github.com/godotengine/godot/blob/0246230e2b7c542f003c3c53cffc22dedc0c9c50/editor/plugins/script_editor_plugin.cpp#L2642-L2649

After #85504, the extra CSharpScript takes over the path, and the correct C# script lose its path:

https://github.com/godotengine/godot/blob/0246230e2b7c542f003c3c53cffc22dedc0c9c50/modules/mono/csharp_script.cpp#L2854

**Comment by raulsntos** [comment]
This check was supposed to stop that from happening:

https://github.com/godotengine/godot/blob/0246230e2b7c542f003c3c53cffc22dedc0c9c50/modules/mono/csharp_script.cpp#L2851

The intention is to prevent new scripts to take over existing scripts unless they share the same path. If the current script's path is empty, a new script with a path should be allowed to take over but not the other way around. I guess the check is insufficient to achieve this.

**Comment by nongvantinh** [comment]
The PR is a correct fix, but it seems there are a few additional corner cases that need to be addressed.
@zaevi, are you currently working on this? If not, I can handle this case.

**Comment by zaevi** [comment]
> The PR is a correct fix, but it seems there are a few additional corner cases that need to be addressed. @zaevi, are you currently working on this? If not, I can handle this case.

I'm not. Just do it👍

**Comment by nongvantinh** [comment]
https://github.com/godotengine/godot/blob/4b543ddbf813ad77fc37f96c1a6d7359261ddc7c/core/io/resource.cpp#L70-L73

During the takeover operation, the `path_cache` of the current resource has been removed. Consequently, any reference to the old resource that attempts to access its `path_cache` discovers that it no longer exists, causing any reference to this resource thinking this is a "new unsaved resource".

According to @raulsntos's understanding, these two resources(C# script) should be the same instance. However, in this case, they are two different instances sharing the same `path`. This is the hidden bug he is referring to.

**Comment by nongvantinh** [comment]
https://github.com/godotengine/godot/blob/b15105a3585c29c8448f3d2dc8fe20a578a2b41b/modules/mono/csharp_script.cpp#L2838-L2843


It appears that the line `NativeFuncs.godotsharp_internal_new_csharp_script(outScript);` within the `GetOrCreateScriptBridgeForPath` method always executes. This results in a new instance being created, which the takeover operation then uses instead of the old one. Is this behavior expected or normal?

CC @raulsntos

**Comment by raulsntos** [comment]
> It appears that the line `NativeFuncs.godotsharp_internal_new_csharp_script(outScript);` within the `GetOrCreateScriptBridgeForPath` method always executes. This results in a new instance being created, which the takeover operation then uses instead of the old one. @raulsntos Is this behavior expected?

The method `GetOrCreateScriptBridgeForPath` should never create a new script if one already exists for the same path. As the name implies, it **gets** the existent script for the given path, and only if a script doesn't exist it **creates** a new one.

However, `NativeFuncs.godotsharp_internal_new_csharp_script(outScript);` should only be executed if a script does **not** exist. It can still be called the first time when a Script instance doesn't exist yet, but then the Script should be reloaded to register it.

Basically the process works as follows:

```mermaid
flowchart TD
    Root[GetOrCreateScriptBridgeForPath] --> |Try to get C# Type for the given path| HasType{Found Type?}
    HasType -->|Yes| GetOrCreateForType[GetOrCreateScriptBridgeForType]
    HasType --> |No| NewScript[NativeFuncs.godotsharp_internal_new_csharp_script]
    NewScript --> ReturnsNewScript[Returns a new empty Script instance.]
    GetOrCreateForType --> |Try to get existent Script for the given Type| HasScript{Found Script?}
    HasScript --> |Yes| ReturnScript[NativeFuncs.godotsharp_ref_new_from_ref_counted_ptr]
    HasScript --> |No| CreateScriptForType[CreateScriptBridgeForType]
    ReturnScript --> ReturnsExistentScript[Returns the existent Script.]
    CreateScriptForType --> NewScript2[NativeFuncs.godotsharp_internal_new_csharp_script]
    NewScript2 --> ReloadScript[NativeFuncs.godotsharp_internal_reload_registered_script]
    ReloadScript --> ReturnsReloadedScript[Returns a new Script that is then reloaded.]

    HasType:::question
    HasScript:::question
    ReturnsNewScript:::finish
    ReturnsExistentScript:::finish
    ReturnsReloadedScript:::finish

    classDef question stroke:#f00
    classDef finish stroke:#0f0
```

- `Found Type?` should always find the type because every C# Type is registered in the path bimap, the only exception is generic types because they have to be constructed first so they are registered at runtime. So, we should never return an empty new Script.
- `Found Script?` should find the script if it exists, otherwise it creates a new one and calls `CSharpScript::reload` on it which registers it.
