### ISSUE TITLE
Shader Material Error On Mobile but fine in Desktop

### ISSUE THREAD

**Issue by fian46** [godotengine/godot#88578]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Android 13 Mobile Renderer

### Issue description

```
shader_type canvas_item;
render_mode unshaded;

uniform sampler2D gradient;
uniform float mix_amount = 1.0;

void fragment(){
	vec4 input_color = texture(TEXTURE, UV);
	float greyscale_value = dot(input_color.rgb, vec3(0.299, 0.587, 0.114));
	vec3 sampled_color = texture(gradient, vec2(greyscale_value, 0.0)).rgb;

	COLOR.rgb = mix(input_color.rgb, sampled_color, mix_amount);
	COLOR.a = input_color.a;
}
```

I have this shader in my sprite. it working fine in desktop but in my phone the color is wrong and sometimes the sprite is not visible at all. the problem is appear after couple minute of testing in my android phone. the error is appear in debugger after i turn on network debugging in editor

![image](https://github.com/godotengine/godot/assets/13792627/6e44f45e-2996-4ccb-80ee-8c5a558184ef)

![image](https://github.com/godotengine/godot/assets/13792627/c1fb6a01-2664-4bb6-8e0c-918be958bc91)

this is the color it supposed to

![image](https://github.com/godotengine/godot/assets/13792627/cd578716-f5ed-4fdb-86ec-c44a1d6ef593)

but this is in my phone
![WhatsApp Image 2024-02-20 at 11 28 58 AM](https://github.com/godotengine/godot/assets/13792627/7ab7dfef-7f99-427b-bc11-5f52cacb3606)

### Steps to reproduce

````
shader_type canvas_item;
render_mode unshaded;

uniform sampler2D gradient;
uniform float mix_amount = 1.0;

void fragment(){
	vec4 input_color = texture(TEXTURE, UV);
	float greyscale_value = dot(input_color.rgb, vec3(0.299, 0.587, 0.114));
	vec3 sampled_color = texture(gradient, vec2(greyscale_value, 0.0)).rgb;

	COLOR.rgb = mix(input_color.rgb, sampled_color, mix_amount);
	COLOR.a = input_color.a;
}
````

use this shader in any sprite, and spawn many of it. it will produce wrong color or broken sprite after a while

### Minimal reproduction project (MRP)

N.A

**Comment by Calinou** [comment]
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

The shader you posted requires a few uniforms to defined, so it doesn't suffice on its own to reproduce the issue.

That said, the issue is likely that shader precision is decreased on mobile for performance reasons, so you'll need to add "highp" precision qualifier in front of some variables/uniforms for your shader to render correctly on mobile. Only add this precision qualifier when you actually need it to avoid unnecessarily harming performance. Note that this precision hint has no effect on desktop platforms.

**Comment by fian46** [comment]
[mrp_shader_bug.zip](https://github.com/godotengine/godot/files/14353161/mrp_shader_bug.zip)

**Comment by fian46** [comment]
only broken in some android device not all device or desktop

**Comment by fian46** [comment]
note this problem not exist if i use the rendering to Compatibility. but compatibility is stuttering all the time on android if there is sprite with shader is appear in screen but the stuttering and lag is big . note the game is for mobile.

**Comment by fian46** [comment]
![image](https://github.com/godotengine/godot/assets/13792627/ef1cc102-ebce-428f-a04d-797a3ef3e4cc)
hey i have found the work around. maybe the mobile device is not happy with this high number of setting in this section. i cutting it in half solve the error. i am sure this information must be put in documentation somewhere or make the number automatic detection if the number make the device not happy. 

the error says cannot allocate descriptor so maybe the device is not as good as desktop.

but i hope this setting is automatic by the engine because there is many android device out there and it is hard to pointing the ideal setup for running it smoothly.
