### ISSUE TITLE
GDScript standalone

### ISSUE THREAD

**Issue by lordoffox** [godotengine/godot#8859]
Is there any way to use GDScript embed in C++ host.

So we can use same GDScript both client and server.

**Comment by nunodonato** [comment]
This is a issue tracker, used to track bugs and the engine's development.

You can place questions in many places like the Q&A, reddit, irc, discord, etc. Please check https://godotengine.org/community

**Comment by linkpy** [comment]
Like nunodonato said, this is an issue tracker, it's not the place for that kind of question.

But your best bet is to use Godot and starts with a script (instead of a scene). The script must extend SceenTree, this way u can use the engine like a script engine.

You can have more information here : http://docs.godotengine.org/en/stable/learning/editor/command_line_tutorial.html#running-a-script .

**Comment by lordoffox** [comment]
Thanks for the answer.
