### ISSUE TITLE
NavigationAgent2D: velocity_computed always comes out (0,0)

### ISSUE THREAD

**Issue by ichthyoidoc** [godotengine/godot#88648]
### Tested versions

Issue found in 4.2.1.stable

### System information

Godot v4.2.1.stable - macOS 13.6.2 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Trying to use NavigationAgent2D with avoidance enabled to move a Characterbody2D. Navigation works fine without avoidance enabled (e.g. CharacterBody2D moves fine in a NavigationRegion). 

With avoidance enabled:

1) I've connected the NavigationAgent's velocity_computed signal to my script:
<img width="725" alt="Screenshot 2024-02-21 at 11 23 06 AM" src="https://github.com/godotengine/godot/assets/36090654/8d7ccc4a-da63-49aa-a095-a97bbe863997">

2) I've set the needed velocity with set_velocity:
<img width="828" alt="Screenshot 2024-02-21 at 11 23 54 AM" src="https://github.com/godotengine/godot/assets/36090654/d5fb7b00-d61d-496e-b9de-c8ba77436a89">

3) I've created a function to receive the computed velocity:
<img width="828" alt="Screenshot 2024-02-21 at 11 25 06 AM" src="https://github.com/godotengine/godot/assets/36090654/a1fc2d5e-3ab8-448d-84ad-71f073a2763a">

4) As you can see from the print outputs, the velocity is being set, but after computation it is always (0,0):
<img width="1018" alt="Screenshot 2024-02-21 at 11 27 11 AM" src="https://github.com/godotengine/godot/assets/36090654/1e5cf7f7-16d2-4921-83c8-b62a9be2e798">
(the two (-80.70443, -59.04909) are from set_velocity, while the (0,0) is from the safe_velocity after velocity_computed)

What is strange is that a previous project I made with these exact configurations worked, so I don't exactly know why the safe_velocity in this case constantly comes out to be (0,0). There is NOTHING ELSE affecting the navigationagent's velocity.

### Steps to reproduce

Listed above

### Minimal reproduction project (MRP)

n/a, see above

**Comment by smix8** [comment]
> What is strange is that a previous project I made with these exact configurations worked

Needs more context or MRP as this is likely a misconfiguration issue from the node or scene.

**Comment by ichthyoidoc** [comment]
Thanks for the quick reply. But I'll close this topic, since I've moved on from using NavigationAgent and just implemented my own navigation through AStarGrid (which is much better for what I was needing).

The good news is that I wasn't able to replicate the issue in any other setting. So hopefully it wasn't an actual bug and, like you said, a misconfiguration issue.

**Comment by NickToony** [comment]
I believe this issue is due to not setting a `target_position`. I've been tripped up by this a couple times actually. I think this could be made clearer in the docs, as currently:

1. The docs for this property indicate this field is responsible for requesting a new path from the NavigationServer.
https://docs.godotengine.org/en/stable/classes/class_navigationagent2d.html#class-navigationagent2d-property-target-position
2. Avoidance docs clearly state the two systems (pathfinding and avoidance) are separate. This suggests you shouldn't need to set a target destination, only a velocity.
https://docs.godotengine.org/en/4.0/tutorials/navigation/navigation_using_agent_avoidance.html

Should `target_position` be documented as required for avoidance, or is that a bug? I'd lean towards bug if it's unnecessarily generating a path.

I've included a MRP. Just uncomment the indicated line and see that agents will start behaving.

[brokennavigation.zip](https://github.com/godotengine/godot/files/14501533/brokennavigation.zip)
Godot 4.2.1 / Windows 10

Let me know if you'd prefer a new issue.

**Comment by ichthyoidoc** [comment]
Yes, that does seem to fix it on your project. However, in mine, the target_position was actually set beforehand as well.

**Comment by ichthyoidoc** [comment]
After working in my project, I'm convinced that there is something wrong with the velocity compute, because, prior to using avoidance/velocity_compute, navigation actually works. But once I use velocity_computed, passing in a velocity to that method, the safe velocity computed is always (0,0). Something seems to be interrupting the NavigationAgent's ability to compute velocity, and I don't know what it could be.

**Comment by smix8** [comment]
That `target_position` needs to be first set before the agent does anything was added because too many users had issues with their freshly spawned agents moving to the world origin. That is a consequence of the default or any none set position being always Vector3.ZERO.

**Comment by growingbrain** [comment]
Godot Version: v4.2.1.stable.official [b09f793f5]
OS: Windows 11

My example probably won't help much, but I've been having the same issue.

I am also having this issue.  I've been working on solving it for a few months.  I have 4 main players and you can switch between them.  So if only one 'real' player is using a controller, the other 3 player are using navigation2d.  The issue does not always happen when I switch between players, so I've tried to debug and test to see what circumstances cause it with no success.  It seems random, almost like my init_nav function calls something that cannot be called during certain 'times'; hard to say exactly.

My issue is that when my 'velocity_computed' is called the safe or calculated_velocity as shown below is (0, 0).  I've debugged this extensively and I am setting a non-zero navigation agent velocity (i.e. nav_agent.set_velocity(...)).

I figured this was probably something I am doing when switching players and re-initializing the navigation in the init_nav function.

velocity_computed callback function output:
calculated_velocity = (0, 0)
velocity = (0, 0)
position = (63.6714, 293.4947)
global_position = (63.6714, 293.4947)
nav_agent.target_position = (172.0747, 268.0079)
nav_agent.distance_to_target() = 111.359069824219
get_position_delta() = (0, 0)
get_real_velocity() = (0, 0)
nav_agent.is_navigation_finished() = false
nav_agent.is_target_reachable() = true

init_nav function (called when switching players):
```
func init_nav():
set_velocity(Vector2.ZERO)

nav_agent.set_max_speed(character_speed_multiplier)
nav_agent.set_radius(nav_agent_radius)

nav_agent.set_avoidance_enabled(true)
	
nav_agent.set_target_desired_distance(2.0) #10.0 is default value
nav_agent.set_path_desired_distance(4.0) #20.0 is default value

nav_agent.set_path_max_distance(4.0) #default is 100.0, testing to see if this fixing final point reaching issue 7/7/2023

nav_agent.set_velocity(Vector2.ZERO)
nav_agent.set_velocity_forced(Vector2.ZERO) # resets the Nav internal velocity, needed when teleporting
	
nav_destination = self.global_position
next_nav_position = self.global_position

nav_agent.set_target_position(nav_destination)

# NOTE: I've tried to always allow navigation to be enabled, and never pause, but that did not fix this either.
if ai_player_enabled or Global.mouse_point_click_select_enabled:
	enable_nav_callbacks()
	unpause_nav()
else:
	disable_nav_callbacks()
	pause_nav()
```

```
func unpause_nav():
	NavigationServer2D.agent_set_paused(nav_agent, false)

func pause_nav():
	NavigationServer2D.agent_set_paused(nav_agent, true)
```

```
# NOTE: I only call disable_nav when the level is finished, since it was not working correctly to disable avoidance.
func disable_nav():
	nav_agent.set_avoidance_enabled(false)
	
	## NOTE: ONLY remove callbacks when removing player from memory.
	disable_nav_callbacks()
```

```
func disable_nav_callbacks():
	if nav_agent.is_connected("velocity_computed", Callable(self, "character_velocity_computed")):
		nav_agent.disconnect("path_changed", Callable(self, "character_path_changed"))
		nav_agent.disconnect("target_reached", Callable(self, "character_target_reached"))
		nav_agent.disconnect("navigation_finished", Callable(self, "character_navigation_finished"))
		nav_agent.disconnect("velocity_computed", Callable(self, "character_velocity_computed"))

func enable_nav_callbacks():
	if not nav_agent.is_connected("velocity_computed", Callable(self, "character_velocity_computed")):
		nav_agent.connect("path_changed", Callable(self, "character_path_changed"))
		nav_agent.connect("target_reached", Callable(self, "character_target_reached"))
		nav_agent.connect("navigation_finished", Callable(self, "character_navigation_finished"))
		nav_agent.connect("velocity_computed", Callable(self, "character_velocity_computed"))
```

NOTE: In the picture the girl in the lower left bottom corner should be moving toward the other players.
![Screenshot 2024-04-16 162428](https://github.com/godotengine/godot/assets/128189986/99d9f02f-9e36-4a10-923b-425b1b5b88d5)

I will re-test when a newer stable version than Godot 4.2.1 is available.
Thanks!

**Comment by marsonfire** [comment]
I had this problem, and I fixed it by setting the Navigation Agent's velocity in **_physics_process** instead of the CharacterBody's velocity. The original post seems to be using a CharacterBody, so I think we had the same issue. I am in 3D though.

In the **_on_velocity_computed** signal that is called, I am setting the Character Body's velocity instead of the Navigation Agent's velocity. 

If I change where the Nav Agent or CharacterBody get their velocity set, the agent doesn't work and safe_velocity is 0 every time. Not sure if that's expected or not. Perhaps I am misunderstanding how the safe_velocity and navigation agent velocity are supposed to be used with a CharacterBody.

It's a basic setup, mostly following the basic Godot docs for agent set up. Notice that the docs (at the bottom of the page) are actually setting the navigation agent velocity, not the character body's in the physics process. In the signal call, they are setting the character body's velocity, not the navigation agent. 
https://docs.godotengine.org/en/stable/tutorials/navigation/navigation_using_navigationagents.html

This is all in the same script that is controlling the enemy movement.

This is all I do for the the velocity being set in my code. This is in **_physics_process**
```
var velocity : Vector3 = currentPosition.direction_to(nextPosition) * movementStats.moveSpeed
navAgent.velocity = velocity
``` 
Connected signal:
```
func _on_navigation_agent_velocity_computed(safe_velocity: Vector3) -> void:
characterBody.velocity = safe_velocity
```

**Comment by smix8** [comment]
Closing as the documentation has working agent script examples.
