### ISSUE TITLE
Dotnet: Enabling [Include Debug Symbols] improves performance greatly for exported game

### ISSUE THREAD

**Issue by Benardus** [godotengine/godot#88657]
### Tested versions

Reproducible in v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3623) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

When exporting a game written in C# the performance (general FPS) is much greater when the Dotnet option [Include Debug Symbols] is enabled in the **Standard Windows Desktop Preset** This should not be the case as debug symbols should not impact performance, but I have suspiscion that this option does more than it says. The difference is wild, 10-20 fps more.

### Steps to reproduce

Export with the option enabled and without and then compare. My project is 1GB, the difference gets more pronounced with the size of the project. It would 

### Minimal reproduction project (MRP)

The very nature of this bug needs a big project to show an increasing performance loss. So no. I suggest just looking at the actionable code accompanying "Include Debug Symbols"on the standard Windows Desktop Preset.

**Comment by Benardus** [comment]
It was pretty hard and frustrating work to discover this niche bug. We are not looking for an emote response as it doesn't feel very professional. We will spend our time on creating something great, instead of improving this tool. Do with this report what you will. We'll just release with debug symbols if necessary.

**Comment by akien-mga** [comment]
A couple of users reacting to a report with :eyes: or :confused: because they're curious/confused as to why debug symbols would **improve** performance (which goes against common sense), doesn't strike me as a reason to ragequit and abandon a bug report 5 hours after reporting it, before any .NET maintainer has had any time to read it.

But that's your call. Without a reproduction project it might indeed be difficult to debug so I won't reopen it if you're not interested in being involved further, I respect that decision.

---

I've had a quick look at the logic around the "Include Debug Symbols" option (in `modules/mono/editor/GodotTools/GodotTools/Export/ExportPlugin.cs` and `modules/mono/editor/GodotTools/GodotTools/Build/BuildManager.cs`).

The bool argument seems properly passed to
```
        private static BuildInfo CreatePublishBuildInfo(
            string configuration,
            string platform,
            string runtimeIdentifier,
            string publishOutputDir,
            bool includeDebugSymbols = true
        )
        {
            var buildInfo = new BuildInfo(GodotSharpDirs.ProjectSlnPath, GodotSharpDirs.ProjectCsProjPath, configuration,
                runtimeIdentifier, publishOutputDir, restore: true, rebuild: false, onlyClean: false);

            if (!includeDebugSymbols)
            {
                buildInfo.CustomProperties.Add("DebugType=None");
                buildInfo.CustomProperties.Add("DebugSymbols=false");
            }

            buildInfo.CustomProperties.Add($"GodotTargetPlatform={platform}");

            if (Internal.GodotIsRealTDouble())
                buildInfo.CustomProperties.Add("GodotFloat64=true");

            return buildInfo;
        }
```
And thus `includeDebugSymbols` being `true` would prevent passing `DebugType=None` and `DebugSymbols=false` to dotnet, which I assume (not familiar with .NET) would mean having a debug build with debug symbols by default.

So from a quick look I don't spot any obvious reason for a build to have more performance with debug symbols enabled.
