### ISSUE TITLE
Scene minimap for 2D editor

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#8868]
A minimap for 2D editor could be really useful for games with big levels.

This is the way it is on Tiled:
![tiledcapture](https://cloud.githubusercontent.com/assets/10215987/26321803/b0e62b44-3efe-11e7-8748-2793faaf17ab.png)

But on Godot it will need to be configurable on extents and zoom, not limited to tilemaps (because is just one of many ways to make levels).

Could look like this:
![minigodotmap](https://cloud.githubusercontent.com/assets/10215987/26321837/da515cf6-3efe-11e7-816a-fb2371e627db.png)
Or use the bottom panel to make it less intrusive and allow minimaps for huge levels,

This may be possible to do with plugins but I'm not good with viewports (and failed miserably trying :sweat_smile: ) so I can't be sure.

**Comment by Zylann** [comment]
I personally never needed such a feature, zooming out generally does the job. If this gets in it should be togglable in Editor Settings.

**Comment by Zireael07** [comment]
+1 for this being toggleable.

**Comment by kubecz3k** [comment]
I'm not sure but for me this one looks like a perfect candidate for plugin, not the core. (It should  easy to write such plugin, assuming we would be able to fetch editor viewport from the plugin)

**Comment by kubecz3k** [comment]
You would need basically to just `Viewport.get_texture()` and then apply this texture to `Sprite`

**Comment by Zylann** [comment]
If I were to make a minimap, I would first assume that the map is huge enough to need such a map. Which mean I would not even use a viewport. Instead, I would associate a color to each tile / grid location in the scene, and plot one pixel inside a minimap texture. Less accurate than an actual render, but a lot cheaper :D Then it can stay in sync with a basic rolling update. Just throwing ideas^^

**Comment by Zylann** [comment]
Tiles would be the base of the thing, if the user needs special markers it can be added on top of it

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
