### ISSUE TITLE
When ever I launch godot with --verbose it keeps displaying this error

### ISSUE THREAD

**Issue by yennox** [godotengine/godot#88743]
### Tested versions

Godot Engine v4.2.1.stable.arch_linux - https://godotengine.org

### System information

OS: Manjaro Linux x86_64, CPU: Intel i3-10100 (8) @ 4.300GHz, GPU: Intel CometLake-S GT2 [UHD Graphics 630], Memory: 11639MiB / 15699MiB

### Issue description

Godot Engine v4.2.1.stable.arch_linux - https://godotengine.org
Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
OpenGL API 4.6 (Core Profile) Mesa 23.3.5-manjaro1.1 - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics 630 (CML GT2)
 
ERROR: Resource file not found: res://deepnest (expected type: )
   at: _load (core/io/resource_loader.cpp:279)

also sometimes but rarely godot closes with no warning and it doesn't save anything.

### Steps to reproduce

godot --verbos

### Minimal reproduction project (MRP)

N/A

**Comment by Calinou** [comment]
Which message are you referring to? This one?

```
 Inconsistent value (1) for DRI_PRIME. Should be < 1 (GPU devices count). Using: 0
```

Or this one?

```
ERROR: Resource file not found: res://deepnest (expected type: )
at: _load (core/io/resource_loader.cpp:279)
```

The latter may be due to your editor settings referencing a file that doesn't exist. Try removing your `editor_settings-4.tres` file in the [editor settings folder](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html#editor-data-paths) while the editor is closed to reinitialize all settings to their default values.

PS: The option name is `--verbose`, not `--verbos` :slightly_smiling_face:

**Comment by yennox** [comment]
That worked deleting editor_settings-4.tres did it thanks alot!!!

**Comment by MikeAsterios** [comment]
What about the first error? I have that, my Godot wont use the gpu
