### ISSUE TITLE
Unable to emulate mouse movement by send InputEventMouseMotion to Input.ParseInputEvent？

### ISSUE THREAD

**Issue by gnenux** [godotengine/godot#88764]
### Tested versions

- Reproducible in: 4.2.1.stable.mono

### System information

Windows11 Vulkan API 1.3.260 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1080

### Issue description

I want to simulate mouse operation with a gamepad, such as using the left joystick to control mouse movement, as shown in the code below.
```csharp
	public override void _PhysicsProcess(double delta)
	{
		base._PhysicsProcess(delta);

		var _emuMouseAxis = new Vector2(Input.GetJoyAxis(0, JoyAxis.LeftX), Input.GetJoyAxis(0, JoyAxis.LeftY));
		if (!_emuMouseAxis.IsZeroApprox())
		{
			// Input.WarpMouse(GetViewport().GetMousePosition() + _emuMouseAxis * EmuMouseSpeed);

			var _inputEventMouseMotion = new InputEventMouseMotion();
			_inputEventMouseMotion.Device = 0;
			_inputEventMouseMotion.WindowId = 0;

			var _relativeExact = _emuMouseAxis * EmuMouseSpeed;
			var _relative = new Vector2I(Mathf.RoundToInt(_relativeExact.X), Mathf.RoundToInt(_relativeExact.Y));

			_inputEventMouseMotion.GlobalPosition = GetViewport().GetMousePosition() + _relative;
			_inputEventMouseMotion.Position = _inputEventMouseMotion.GlobalPosition;
			_inputEventMouseMotion.Relative = _relative;
			_inputEventMouseMotion.Velocity = _relativeExact * 60f;

			Input.ParseInputEvent(_inputEventMouseMotion);
			// GetViewport().PushInput(_inputEventMouseMotion);
		}
	}
```
But it doesn't seem to work, the mouse cursor doesn't move.
If you use **Input.WarpMouse**, the mouse cursor moves normally.
Is there something wrong with my usage?

### Steps to reproduce

Please refer to the attached file and the above code.

### Minimal reproduction project (MRP)

[InputEventMouseMotionTest.zip](https://github.com/godotengine/godot/files/14392811/InputEventMouseMotionTest.zip)

**Comment by AThousandShips** [comment]
The mouse cursor isn't controlled by this, you need to use `WrapMouse` for this, there's no bug here, the `ParseInputEvent` method just handles how the engine processes the events, it isn't in control over the cursor, that's handled by the OS, that's why you need to use that method

A note should be added to the method clarifying this as it's not entirely clear that this method doesn't do this (though it does say it handles sending custom input events *to* the game engine, not the operating system)
