### ISSUE TITLE
Request: WORLD_NORMAL for vertex shader.

### ISSUE THREAD

**Issue by K9Crunch** [godotengine/godot#8882]
**Feature Request:**
Would be very nice to have simplified vertex access to the world space normal when writing shaders.
So we can have: NORMAL, SRC_NORMAL, WORLD_NORMAL.

One great use for the world space normal is dynamic landscape/enviroment texturing and dynamic model texture interaction with the landscape/enviroment.

**Comment by harraps** [comment]
What is the current way to get the world position and world normal of a vertex ?
I've tried multiple things and nothing seems to work...

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
