### ISSUE TITLE
Materials with normal maps cut illumination from certain angles

### ISSUE THREAD

**Issue by Laks0** [godotengine/godot#88836]
### Tested versions

- Reproducible in: v4.2.1.stable.arch_linux, Godot 4.3-dev3, Godot 3.5.3 stable

### System information

Godot v4.2.1.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 - Tty - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (nvidia; 545.29.06) - Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 Threads)

### Issue description

Any 3d mesh that has a material with a normal map is having this problem where light sources can only light from some angles. It happens with every kind of light source and with every image on the normal map texture, I've tried it with blank images and with a placeholder texture. Normal maps seem to work alright otherwise. I could reproduce the same issue in Godot 3.

https://github.com/godotengine/godot/assets/35859490/1bbed6c9-b753-4449-8ddd-c740b44bc3f1

### Steps to reproduce

- Create a MeshInstance3D object, with a plane mesh
- Assign it a StandardMaterial3D with normal_enabled on, and assign normal_texture any texture
- Add a light source

### Minimal reproduction project (MRP)

[Normal_Map.zip](https://github.com/godotengine/godot/files/14397692/Normal_Map.zip)

**Comment by clayjohn** [comment]
Just a heads up, the MRP doesn't have a normal map. A normal map is required for normal mapping to work correctly. 

To be clear, you can't just use any texture as a normal_map and expect it to work. In particular, in your MRP you are using a placeholder texture as a normal map. A placeholder texture is not a texture and should not be expected to look acceptable in any situation (it is only used for faking a texture when running on a server). 

From looking at your video it looks like there is an issue with your normal map, but I can't confirm that because it wasn't included in your MRP. Could you upload a new MRP that reproduces your issue and contains all the elements needed to reproduce the issue?

**Comment by Laks0** [comment]
Oh, I've tried it with plain PNGs with different values of gray (from white to black in all pixels), but if that doesn't make sense either maybe I'm misunderstanding how normal maps work. Here's the same project but with the normal map set to the one we're using in the game, generated in blender:
[Normal_Map.zip](https://github.com/godotengine/godot/files/14411084/Normal_Map.zip)
