### ISSUE TITLE
Segfault editting TreeItem immediately after re-adding to Tree.

### ISSUE THREAD

**Issue by OffsetMOSFET** [godotengine/godot#88889]
### Tested versions

Godot 4.2.2

### System information

Ubuntu 22.04.4 LTS 64-bit

### Issue description

Clicking to edit a TreeNode after moving it causes a segfault (signal 11). Selecting another TreeNode will prevent this from happening.

### Steps to reproduce

Remove the item from the tree; add the item to the tree; click on the item to edit it.

### Minimal reproduction project (MRP)

paste onto a Tree node:

```
extends Tree

var not_crash_item:TreeItem
var crash_item:TreeItem


func _init():
	hide_root = true
	set_anchors_preset(Control.PRESET_FULL_RECT)


func _ready():
	var root := create_item()
	
	not_crash_item = create_item(root)
	not_crash_item.set_editable(0, true)
	
	crash_item = create_item(root)
	crash_item.set_editable(0, true)

	crash_item.select(0)
	get_root().remove_child(crash_item)
	get_root().add_child(crash_item)
	not_crash_item.set_text(0, "click to prevent crash")
	crash_item.set_text(0, "click to crash")

```

**Comment by OffsetMOSFET** [comment]
Calling .deselect before the node is removed also avoids this crash.

**Comment by akien-mga** [comment]
CC @KoBeWi @Sauermann

**Comment by mihe** [comment]
As far as I can tell the issue seems to be that the `selected` property of the cells in `selected_item` isn't set to `false` when `selected_item` is cleared as part of removing it from the tree. This then leads to `selected_item` not being set again (and thus left at `nullptr`) when you click the item after having re-added it.

Adding this code above [this line](https://github.com/godotengine/godot/blob/a586e860e5fc382dec4ad9a0bec72f7c6684f020/scene/gui/tree.cpp#L123) fixes the issue:

```cpp
for (int i = 0; i < tree->selected_item->cells.size(); i++) {
    tree->selected_item->cells.write[i].selected = false;
}
```

There might be a cleaner solution though.

**Comment by mihe** [comment]
I made it into a PR, in case it happens to be the preferable solution in this case: #88917.
