### ISSUE TITLE
C# `precision=double` compiler error - wrong epsilon variable

### ISSUE THREAD

**Issue by TCROC** [godotengine/godot#88993]
### Tested versions

v4.3.dev.mono.custom_build.df78c0636

### System information

Pop OS 22.04

### Issue description

Looks like the MathfEx.cs class was refactored.  For 64 bit / double builds, Epsilon should be pointing to EpsilonD instead of what I presume was the old _epsilonD.

https://github.com/godotengine/godot/blob/df78c0636d79c9545a283e0e2a926d623998cc27/modules/mono/glue/GodotSharp/GodotSharp/Core/MathfEx.cs#L32

### Steps to reproduce

Do a 64 bit C# build of godot 

### Minimal reproduction project (MRP)

NA

**Comment by TCROC** [comment]
Really simple fix.  I put in a PR for it.  Do we have a CI that checks 64 bit C# builds?  If so, I'm curious how it missed this.  And if not, I can open another issue to add one in as an enhancement.

I'd be glad to contribute it as we depend on that stability :)

**Comment by raulsntos** [comment]
> Do we have a CI that checks 64 bit C# builds?

No. The only .NET-enabled builds we do in CI are the Linux editor and the Linux template, both using single precision. We have a double precision build but that one doesn't enable the .NET module.

We try to cover most configurations in the matrix of builds we do in CI, but we can't cover every possible combination since the bigger the matrix the more resources it requires and the longer it takes to complete.

**Comment by TCROC** [comment]
Makes sense. Should we added the .NET module to the double precision build? I don't expect it would increase the build time too significantly. And it would prevent adding an additional CI as it would just add on to the existing CI.
