### ISSUE TITLE
Wrong grouping of Godot instances on Windows

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#89068]
### Tested versions

Regression from #85905

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

When running Godot editor from multiple executables, they are grouped under one task bar icon. Previously each executable (at least from different versions) had its own group.
I also noticed that running project makes a new task bar instance, while previously it went with editor.
Console wrapper is still separate.

For some reason it's a regression from #85905, while it claims to have done the opposite. Maybe it's Windows 10/11 difference? idk

### Steps to reproduce

0. Be on Windows
1. Run Godot
2. Run other Godot

### Minimal reproduction project (MRP)

N/A

**Comment by jsjtxietian** [comment]
> When running Godot editor from multiple executables, they are grouped under one task bar icon.

Maybe it's related to the OS ( I'm on Windows 10.0.19045)? 

I'm testing with current master version along with 4.2.1, for me it works as expected, godot with same version gets grouped and different version has its own group. 

> running project makes a new task bar instance , while previously it went with editor.

Yes current master has this behaviour while 4.2.1 went with the editor.

**Comment by theraot** [comment]
Apparently※ Windows guesses from the executable name and the process what to group toghether. Unless you provide the AppIds, in which case you need to manage it.

※: Going by this: https://devblogs.microsoft.com/oldnewthing/20120820-00/?p=6813

Thus, if you want the editor and its project to be grouped toghether, they should share AppId, which the code from https://github.com/godotengine/godot/pull/85905 does not do.

To fix this, I believe Godot should take its AppId from the opened project if it has any, so Godot and the game launched from it are grouped.

I do not see what was the issue that https://github.com/godotengine/godot/pull/85905 was fixing. Was it trying to remove all grouping?

---

For me, testing on Godot 3.4 beta1, on Windows 10, all Godot instances are grouped, and the games launched from them are separate, which makes sense to me given the source code... Because Godot is taking the editor AppId from its version number (so they are all equal, and ger grouped), while the game is taking its AppId from its application name and version configured in project settings (so these differ).

**Comment by KoBeWi** [comment]
Closing as intended. The instances are now grouped based on engine version instead of executable, so multiple executables with the same version (most prominently master and newest dev release) will be grouped together.
It's different than the old behavior, but not strictly worse.
