### ISSUE TITLE
Toggling TileMap layer's `enabled` does not update the layer list

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#89199]
### Tested versions

4.3 dev4
It's probably recent.

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/a4a84a68-2e61-4f14-8e7f-0633dc84c40f

### Steps to reproduce

1. Add TileMap
2. Add one more layer
3. Disable a layer
4. Open layer popup
5. The disabled layer is normally selectable

### Minimal reproduction project (MRP)

N/A

**Comment by groud** [comment]
This should be solved by https://github.com/godotengine/godot/pull/89179 in a bit of a different way. Since disabled/hidden layers will be selectable in the scene dock anyway, I plan to have this message instead:
![Screenshot_20240306_124506](https://github.com/godotengine/godot/assets/6093119/5f4839f0-eccb-4b1f-86ba-35980eb8d4ce)

**Comment by groud** [comment]
@KoBeWi can you still reproduce this one ?

**Comment by KoBeWi** [comment]
*Technically* yes, but the editor now properly handles disabled layers, so it's no longer a problem. This can be closed.
