### ISSUE TITLE
Mobile virtual keyboard wont show if fullscreen

### ISSUE THREAD

**Issue by PeterMarques** [godotengine/godot#89221]
### Tested versions

3.x

### System information

android

### Issue description

.If in fullscreen, and a box is selected, the keyboard wont appear. 

### Steps to reproduce

.

### Minimal reproduction project (MRP)

.

**Comment by PeterMarques** [comment]
as stated in https://github.com/godotengine/godot/issues/89220 ipadOS open fullscreen.

And it does not shows a keyboard either.

**Comment by Calinou** [comment]
@PeterMarques Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened

**Comment by PeterMarques** [comment]
I am using a soft gdscript keyboard, ...because. 
But, this should not be closed either. Its a reported behaviour. The lack of a test project is no reason to ignore/dismiss a bug.

**Comment by AThousandShips** [comment]
This report doesn't have sufficient information, and none was provided when prompted, so nothing else can be done, and no reason to keep it open

So please provide more information, and fill out more details, preferably an MRP, and this can be reopened
