### ISSUE TITLE
Collision detection not working on x+ axis with slow player speed when nested scenes/glb are used.

### ISSUE THREAD

**Issue by BrahRah** [godotengine/godot#89245]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Linux Mint 21 (Vanessa) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (nvidia; 535.154.05) - AMD Ryzen 5 1600 Six-Core Processor (12 Threads)

### Issue description

I've made a level wrap around that teleports the player to the other side of the bounds. When the player moves out of the bounds on the x+ axis it only works with a speed of 8 to 11. 8 also often fails.

I've made two mrps.
This mrp is the one with nested scenes and the glb, it shows the issue:

https://github.com/godotengine/godot/assets/40721994/a964f8fe-6b6e-4f1c-a4c5-d6fd786adb27

This one is the mrp without nested scenes/glb and the issue is not there:

https://github.com/godotengine/godot/assets/40721994/49942e58-c356-43ac-bcf7-e7cb6263b320

Both use the same code.

### Steps to reproduce

1. open one of the provided mrps.
2. run the project
3. press left and right arrow keys on the keyboard to move, press num + and - to increase and decrease speed
4. move to the right (x+)

### Minimal reproduction project (MRP)

[Tracktor Game mrp.zip](https://github.com/godotengine/godot/files/14523385/Tracktor.Game.mrp.zip)
[x+ mrp no issue.zip](https://github.com/godotengine/godot/files/14523389/x%2B.mrp.no.issue.zip)

**Comment by Nazarwadim** [comment]
There is no Godot bug here. The bug is in your code.
In line `39` `LevelBorder.cs`
``` c#
if (Mathf.Abs(playerPosition.X) > areaSize.X / 2)
{
```
if the global position of the player on the x-axis is greater than the size of the box divided by two. This is where the error occurs. In the `level_01` scene, you changed the position `Farmland`. Therefore, the player's global x-axis position was less than the size of the box divided by 2. 
So, a simple solution to this problem is to put node `Farmland` at `position 0 0 0` in the `level_01` scene. But it would be much better to use 4 Area3Ds separately.

**Comment by BrahRah** [comment]
> There is no Godot bug here. The bug is in your code. In line `39` `LevelBorder.cs`
> 
> ```cs
> if (Mathf.Abs(playerPosition.X) > areaSize.X / 2)
> {
> ```
> 
> if the global position of the player on the x-axis is greater than the size of the box divided by two. This is where the error occurs. In the `level_01` scene, you changed the position `Farmland`. Therefore, the player's global x-axis position was less than the size of the box divided by 2. So, a simple solution to this problem is to put node `Farmland` at `position 0 0 0` in the `level_01` scene. But it would be much better to use 4 Area3Ds separately.

That makes no sense to me. Can you explain why the farmland has to be at 000 for the collision detection to work at different movement speeds? If it was offset I'd understand but why the different speeds?

**Comment by Nazarwadim** [comment]
![image](https://github.com/godotengine/godot/assets/116561933/40b940a0-af08-4479-81f5-570e321310a2)
Because if the speed is low, then we can't change the position in a physical frame by the distance we moved the box. 

Just as an example, the edge along the x-axis of the box is 45 and the box `Size.X / 2 = 50`. Our position in the physical frame before Area detects -> Player.Position.X = 44. So when player is at low speed, then at the moment of calling `OnAreaBodyExited` our position will be 46 (for example). And when we are at high speed, it will be 55.

**Comment by BrahRah** [comment]
ahh I'll have to remember that then. thx closing it now
