### ISSUE TITLE
Condition  "p_height" <= 0 | | p_height > 16384" is true

### ISSUE THREAD

**Issue by calveryscout** [godotengine/godot#89294]
### Tested versions

Whenever i hit play from my menu screens into game screen i get this error

### System information

Godot 4.0

### Issue description

![17099266188988257394259234961004](https://github.com/godotengine/godot/assets/162745314/2a61b994-df1b-48ac-b35c-3494290c736a)

### Steps to reproduce

I dont know how to reproduce it randomly happened and only when i use a camera node

### Minimal reproduction project (MRP)

.

**Comment by AThousandShips** [comment]
Please try to find some way to replicate it, otherwise we can't do anything to help, please ask in the [forums](https://forum.godotengine.org/) with help for that, this is the place where you should make reports for bugs you know how to cause or where you have some more details :)

**Comment by Mickeon** [comment]
The only possible source of this error is in `drivers/gles3/storage/texture_storage.cpp` in the  `TextureStorage::texture_set_size_override` method.

There is still no way to figure anything out with this information, we cannot do anything with this issue.
Please provide a Minimal Reproduction project, code examples, screenshots that are not photographs, etc. Also, since you are using `4.0`, try using one of the latest versions of Godot (`4.2.1`) to see if the issue still occurs.

**Comment by calveryscout** [comment]
Yes that is the thing that pops up

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
