### ISSUE TITLE
Incorrect Normals from Spin Tool Section of Blender Model

### ISSUE THREAD

**Issue by PatDubbie** [godotengine/godot#89401]
### Tested versions

4.2.1-stable

### System information

Godot v4.2.1.stable - Windows 10.0.22621 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.23013.1023) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Sections created with spin tool appear correct in blender regardless of shading:
![image](https://github.com/godotengine/godot/assets/134224970/e3427535-235b-4665-a96b-ace811294fc1)

But when exporting to godot, the sections that are created with spin tool as well as sections that are extruded from those previously created with spin tool (Upper straight section in blender screenshot, labeled in godot screenshot) have incorrect normals despite having an identical profile. The straight pipe shows expected behavior, as does the straight section of the elbow pipe that was created by modifying the straight pipe in blender. The opposite straight section was extruded from the section after generating the bend using spin tool at 90 degrees.
![image](https://github.com/godotengine/godot/assets/134224970/d922fccb-0202-40f5-a748-64c472be8657)

### Steps to reproduce

Create cylinder geometry in blender. Use spin tool to create additional geometry. Export using obj or glb format, with or without triangulate meshes selected, with export normals selected.
Obj export settings:
![image](https://github.com/godotengine/godot/assets/134224970/ae3d2403-b028-435e-81e2-1702ee63ad41)
Glb export settings (default if not shown):
![image](https://github.com/godotengine/godot/assets/134224970/1932a3cb-3d16-4dd8-9daf-ee7bc33edb19)

### Minimal reproduction project (MRP)

[SpinToolNormalBugRepro.zip](https://github.com/godotengine/godot/files/14565233/SpinToolNormalBugRepro.zip)

**Comment by PatDubbie** [comment]
Note that recalculating normals in blender has no impact on the result

**Comment by clayjohn** [comment]
Thank you for the report

Testing locally I can reproduce this issue in 4.2.1. Luckily, it has been fixed already in the 4.3 branch and the fix will be cherrypicked for 4.2.2! So you won't have to wait long before it is available

For now, you can work around the issue by disabling mesh compression in the mesh import settings. 

![Screenshot from 2024-03-11 15-59-50](https://github.com/godotengine/godot/assets/16521339/fa825557-3755-4305-b4d1-a53b9dbe06ae)
![Screenshot from 2024-03-11 15-59-44](https://github.com/godotengine/godot/assets/16521339/a0edf676-2ea4-45c0-a97f-20676c637aad)


Closing as fixed by https://github.com/godotengine/godot/pull/88738

**Comment by PatDubbie** [comment]
God bless, thank you!
