### ISSUE TITLE
Problem with adding figures FBX On the Android device in godot 

### ISSUE THREAD

**Issue by Sorshx** [godotengine/godot#89427]
### Tested versions

4.2.1

### System information

Mobile / Android 

### Issue description

It is nothing to add Modling FBX On the Android device in godot It does not appear in Godot's stereo format files FBX There are no Godot files in the list. I hope there is a solution to this problem 

### Steps to reproduce

To download the steps on the phone only 
1-Open a new project 
2-Add a figure In its formula FBX
3-Go to Godot and look at the file list 
There the error is that the stereo file does not exist 

### Minimal reproduction project (MRP)

Thank you

**Comment by Sorshx** [comment]
The problem is in the Godot menu, the file is not found FBX

**Comment by Zireael07** [comment]
In that case it's likely because in Godot 4 fbx support requires an additional piece of software which may not exist/be unacessible in Android

**Comment by akien-mga** [comment]
I'm not sure I fully understood the bug report, some of it might have been lost it translation.

Based on Zireael's comments, is this correct?
- You're using the Godot editor on Android
- You want to import an FBX model in the editor
- That doesn't work

If so, Zireael is correct, in Godot 4.2 importing FBX files is done via the [FBX2glTF](https://godotengine.org/fbx-import/) command line tool, which only supports Windows, macOS and Linux. So it's not possible to import FBX files on Android currently.

Luckily, this will be fixed in Godot 4.3 thanks to the integration of the ufbx library: #81746.

So assuming I understood correctly, this is resolved in 4.3. Let me know if we misunderstood the issue.

**Comment by Sorshx** [comment]
شكرا لك ❤

**Comment by Zireael07** [comment]
@Sorshx عفواً
