### ISSUE TITLE
Regression in ParallaxBackground

### ISSUE THREAD

**Issue by filkata** [godotengine/godot#89563]
### Tested versions

Reproducible in 4.3 dev5, not observed in 4.2 stable

### System information

Windows 10, Godot 4.3 dev5, Nvidia 3060 12 GB

### Issue description

I want to have an infinite scrolling parallax background with 2 layers that move at different speed when the camera is moved and that also respect the zoom level of the camera. I achieved this with ```ParallaxBackground``` and sprites set to repeat to be several times larger than the viewport.
On 4.3 dev5 zooming in causes the top or both layers to dissapear.

### Steps to reproduce

In the attached project you can click and drag around with the mouse to move the camera and the parallax background respectively.
Use the mouse wheel to zoom in and out and notice how one or both layers will not display.

### Minimal reproduction project (MRP)

[BgBug.zip](https://github.com/godotengine/godot/files/14623191/BgBug.zip)

**Comment by markdibarry** [comment]
I see what you mean. Your project had a lot of errors and the issue was hard to replicate, so I altered it significantly to show the problem more clearly. All you need to do now is scroll a bit to the right and zoom in (it's now interpolated). I'll look into this this week, but here's the project if someone else can figure it out first:
[BGBug.zip](https://github.com/godotengine/godot/files/14623523/BGBug.zip)

**Comment by Mickeon** [comment]
I can see the issue.
<img src=https://i.gyazo.com/02cdadbbdde5e832d93a7e6b25c74ea9.gif>

**Comment by markdibarry** [comment]
I was able to fix it by changing `parallax_layer.cpp`'s mirroring update. I think because `ParallaxBackground` is a `CanvasLayer` and zoom isn't supported, `ParallaxBackground` scales the `ParallaxLayer`s *themselves* (weird, right?). This required the size after scaling to be presented to the renderer up front. The new render method doesn't need that hack since `Parallax2D` is a `Node2D`, but `ParallaxLayer` was still taking the zoom scale into account for the old nodes.

![image](https://github.com/godotengine/godot/assets/21325943/b004479e-882c-442f-a7f9-df8936922dc8)

I'd like to get further testing, because I'd hate for this to cause another regression, since my original PR didn't actually change any `ParallaxBackground` or `ParallaxLayer` code.

https://github.com/godotengine/godot/assets/21325943/a05d6792-4323-4e9f-82f7-887360a3c690

**Comment by filkata** [comment]
Would love to help with testing as the actual setup I discovered the is a bit more complicated than the example.

**Comment by markdibarry** [comment]
I'll make a PR and request that it wait for further testing. I'm pretty confident about your scenario, but I want to try out a few other odd cases with zooming since the old parallax duo does some pretty wacky things.

**Comment by markdibarry** [comment]
@filkata Once the checks pass, you can download an artifact from the PR and try it out. Let me know if you find anything else, and thanks for the quick catch!

**Comment by filkata** [comment]
@markdibarry Can I get some instructions on how to get the artifact from the pull request? Have not done this ever yet.

**Comment by kleonc** [comment]
> Can I get some instructions on how to get the artifact from the pull request? Have not done this ever yet.

@filkata See [here](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html#downloading-a-compiled-build).

**Comment by markdibarry** [comment]
I did some further testing comparing between versions and it seems this does fix the regression. Unfortunately, the original behavior is not the most ideal since every time you update the scale, you need to reset the `mirroring` property or it's off. It also seems that `ParallaxLayer` never fully supported scaling besides the zoom feature and scrolling will break if you alter it manually. It's not hard to fix, but that should be in a separate PR. I encountered this issue as well in `Parallax2D`, so I'll make a quick PR to fix that too.
