### ISSUE TITLE
Can't see script editor scrollbar if it has a white background

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#8958]
**Operating system or device - Godot version:**
3.0 master on Linux

![2017-05-27_13-42-49](https://cloud.githubusercontent.com/assets/1115700/26521234/db5df670-42e3-11e7-90b6-7f50af81f0e7.png)

**Comment by toger5** [comment]
three options: 
 - auto generate color which is contrasting to the script editor bg
 - or another color setting for the scroll bar
 - a theme defined container for the scroll bar which overlays over the script editor. (this might be good solution since that would also fix the weird looking focus frame for the 3d view)

**Comment by toger5** [comment]
I changed the background. If ppl think that is a legit solution I can create a PR:

**Comment by Zylann** [comment]
Why have a light script editor with a dark theme for the rest?

**Comment by toger5** [comment]
It still should be supported I guess. I like the allow any cool choice for the script editor independent of the rest of the theme.

**Comment by hickop** [comment]
@Zylann I'd prefer a working light theme for everything for sure

**Comment by akien-mga** [comment]
If not done already, the scrollbar background could be made dependant on the configurable editor theme colors.

**Comment by hickop** [comment]
Fixed thanks to awesome white theme !
