### ISSUE TITLE
ERROR: Overflow in RID validator

### ISSUE THREAD

**Issue by gilzamir18** [godotengine/godot#89602]
### Tested versions

This error occurred after I exported a 3D experiment using physics that runs without interaction (a simulation) for an extended period. The target platform was Linux Ubuntu 22.04, updated up to the date of this post. The following data was reported in the terminal:

```
Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti
 
ERROR: Overflow in RID validator
   at: _allocate_rid (./core/templates/rid_owner.h:120)

================================================================
handle_crash: Program crashed with signal 4
Engine version: Godot Engine v4.2.1.stable.mono.official (b09f793f564a6c95dc76acc654b390e68441bd01)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /home/gilzamir/tmpbin/data_Emobit_linuxbsd_x86_64/libcoreclr.so(+0x4de1a7) [0x77d28b4de1a7] (??:0)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x77d2d5642520] (??:0)
[3] /home/gilzamir/tmpbin/Demo1.x86_64() [0xe5cb77] (??:0)
[4] /home/gilzamir/tmpbin/Demo1.x86_64() [0x26ca800] (??:0)
[5] /home/gilzamir/tmpbin/Demo1.x86_64() [0x20dd699] (??:0)
[6] [0x77d21274be93] (??:0)
-- END OF BACKTRACE --
===============================
```

### System information

Godot Engine v4.2.1.stable.mono.official.b09f793f5 - https://godotengine.org Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce GTX 1050 Ti

### Issue description

I performed a simulation by exporting it to Linux. I ran the simulation for approximately three hours when the error occurred and interrupted it. There is no user interaction in the simulation.

### Steps to reproduce

* Create a project using version 4.2.1 for .NET.
* Create a 3D scene by adding a RigidBody object that moves randomly within a plane surrounded by walls. Model the walls using StaticBody3D, CollisionShape (Cube type), and a MeshInstance (Cube3D).
* From a specific position of the RigidBody, continuously emit 62 x 3 rays.
* Draw the rays using the following code (autoloaded):

```
using System.Collections.Generic;
using System.Diagnostics;
using Godot;

class Line
{
	public int id;
	public Color color;
	public float thickness;
	public Vector2 a;
	public Vector2 b;
	public float originSize;
	public Color originColor;
	public Line(int id, Vector2 a, Vector2 b, Color c, Color oc, float th, float originSize = 10)
	{
		this.id = id;
		this.a = a;
		this.b = b;
		this.color = c;
		this.originColor = oc;
		this.thickness = th;
		this.originSize = originSize;
	}
}


partial class LineDrawer: Node2D
{
	public List<Line> lines;
	public Camera3D Camera_Node;

	public override void _Ready()
	{
		Camera_Node = GetViewport().GetCamera3D();
		lines = new List<Line>();
		SetProcess(true);
	}


	public void Redraw()
	{
		QueueRedraw();
	}

    public override void _Draw()
	{
		foreach(Line line in lines)
		{
			if (line.originSize > 0)
			{
				DrawCircle(line.b, line.originSize*0.5f, line.originColor);
			}
			DrawLine(line.a, line.b, line.color, line.thickness);
			if (line.originSize > 0)
			{
				DrawCircle(line.a, line.originSize, line.originColor);
			}
		}
	}

	public void Draw_Line3D(int id, Vector3 vector_a, Vector3 vector_b, Color color, Color originColor, float thickness, float originSize)
	{
		foreach(Line line in lines)
		{
			if (line.id == id)
			{
				line.color = color;
				line.a = Camera_Node.UnprojectPosition(vector_a);
				line.b = Camera_Node.UnprojectPosition(vector_b);
				line.thickness = thickness;
				line.originColor = originColor;
				line.originSize = originSize;
				return;
			}
		}

		var new_line = new Line(id, new Vector2(), new Vector2(), color, originColor, thickness, originSize);
		new_line.id = id;
		new_line.color = color;
		new_line.a = Camera_Node.UnprojectPosition(vector_a);
		new_line.b = Camera_Node.UnprojectPosition(vector_b);
		new_line.thickness = thickness;
		lines.Add(new_line);
	}
		
	public void Remove_Line(int id)
	{
			int i = 0;
			bool found = false;
			Line removed = null;
			foreach(Line line in lines)
			{
				if (line.id == id)
				{
					found = true;
					removed = line;
					break;
				}
				i += 1;
			}	
			if (found)
				lines.Remove(removed);
	}
}

```
* Run the simulation during 3 or more hours.

### Minimal reproduction project (MRP)

I already described it above.

**Comment by AThousandShips** [comment]
This is done by design as reusing RIDs is not safe, unsure what is generating RIDs here though so that needs to be investigated

Please upload a project to make this easier to test

**Comment by gilzamir18** [comment]
Thanks. My project is more than 250 MB. It's a lot of files. I will try to create a reduced version of the project that causes the same error. I don't know when, because my time is limited. But soon, I will return.

**Comment by AThousandShips** [comment]
So looking at some of the rendering code this *could* be due to how the renderer allocates RIDs when drawing polygons, which also includes circles, but that still seems extreme in this case, but it depends on how your scene is set up

That is a larger problem that might not be easy to solve, however I'd say that even with that in normal usage this shouldn't be an issue, and that it sounds like you're doing something not quite right in your code

So the basic issue might be here that you draw a lot of circles all the time, you should probably update the rendering only when you need it, and in this case I'd suggest not using circles at all, if you need this specific case I'd suggest instead drawing a circle sprite for the ends, instead of a circle, this is going to be better performance wise anyway, alternatively you could use a mesh of a circle directly and draw it, that shouldn't allocate any data as far as I know, this would mean a lot better performance, and reduce the risk of this

So while there *might* be some issue underlying this and that the engine might handle its resources better, this sounds like it's not a bug as such, but unsupported usage, but that would depend on more details from your project, 3 hours is still not necessarily going to add a lot of data, though it depends entirely on how much data you have in your scene, but adding 63 x 3 lines (each with two circles) does mean a *lot* of stuff is drawn, so I'd suggest changing how you do things here, if nothing else because it sounds extremely inefficient :)

**Comment by gilzamir18** [comment]
Indeed, that's exactly what you said. And the error originates precisely in the LineDrawer class. I reran my experiment without this class; it's a training using reinforcement learning. Notice that the cyan line represents the experiment running without the LineDrawer (which I used for debugging), while the dark line is the experiment that encountered the issue. Note that the experiment without LineDrawer continued beyond 600K, whereas the one with LineDrawer was the one that encountered the bug I posted here. The only difference between the two codes is the use of LineDrawer. I think this thread can be closed. Thank you very much for the interaction.

![image](https://github.com/godotengine/godot/assets/54516662/f662a75d-ed44-4b90-9606-033ee36e4c76)
