### ISSUE TITLE
Using Freelook and Zoom at the same time changes zoom max and min values

### ISSUE THREAD

**Issue by suptoasty** [godotengine/godot#8961]
**Operating system or device - Godot version:**
Linux Mint 18.1 - Godot 3.0 custom build

**Issue description:**

When you hold down the RMB and Scroll, the extent that you can zoom changes.
This also changes the speed at which you can zoom.

**Steps to reproduce:**
1) Go to a 3d scene with something to look at as a reference point
2) hold down the right mouse button and scroll until you are to the minimum value for zoom the very helpful scroll bar in the scene view should not be filled
3) let go of the right mouse button
4) keep using the scroll wheel

**Comment by Zylann** [comment]
This is by design. Using the mouse wheel and RMB increases your speed because it decreases zoom. 
The semantic behind it is the following:
- Zooming out increase panning speed and freelook speed (including when you are using freelook)
- Zooming in decreases panning speed and freelook speed
They are linked together.

**Comment by HummusSamurai** [comment]
@Zylann I was going to file an issue yesterday as well, but I now understand the controls after reading your explanation.

However, would it be possible to place the two visual scrollbars in different positions?
It had seemed to me that the difference between them was a bug.

You could possible place it horizontally to differentiate it from the normal mode scroll bar. Or you could add a text hint box somewhere that says "FreeLook Enabled: Scroll to change movement sensitivity" or something like that. Just basically anything to guide users without having to Google the controls.

**Comment by Zylann** [comment]
@HummusSamurai It took me a little while to settle on this: there is only one conceptual value to indicate, which is the size of your reference frame. It can be interpreted in freelook as a speed, and in normal mode as a zoom, but it's the same source value for both, which is why there is only one bar.
Currently freelook behaves like a mix between Unity and Blender.
You should try it to :)

I'm not sure if adding text is a good solution, I don't want to clutter the viewport if possible^^

**Comment by suptoasty** [comment]
@Zylann Should I close the issue or leave it open for discussion?

**Comment by HummusSamurai** [comment]
@zylann I had tried when I posted, and I think there could be a teeny visual helper to be able to tell what's happening.

Don't get me wrong, I love the controls and the changes they produce, I just would prefer if there was a hint to help the user realise what's happening and what's changing. (aka I don't want anything to change other than visual helpers).

**Comment by suptoasty** [comment]
I realize the usefulness of this design after using it for a while. Being able to control zoom speed and to basically navigate by toggling between orbit, zoom, and freelook is awesome. CLOSING ISSUE.
