### ISSUE TITLE
Engine doesn't open certain scenes when you click them to open in version 4.2.2 rc1 Error "Failed to instantiate scene" at: (scene/resources/packed_scene.cpp:141)

### ISSUE THREAD

**Issue by ringbearer14325** [godotengine/godot#89624]
### Tested versions

4.2.2 rc1

### System information

Windows 10 Pro Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz   2.20 GHz Ram 16.0 GB

### Issue description

I'm making an RPG game and it has a lot of scenes of maps with tile sets. Some of those tile sets when you try to open them, especially when you first start the engine, the scene won't open. The error that appears reads "Scene/file "blank" appears to be invalid/corrupt". 

ERROR: Failed to instantiate scene state of "res://World/TownOfValenz/TownofVelez.tscn", node count is 0. Make sure the PackedScene resource is valid.
   at: (scene/resources/packed_scene.cpp:141)

### Steps to reproduce

1. Open any one scene in a large game with lots of tile set scenes.
2. Click in the file system window at the bottom left corner of the screen. 

### Minimal reproduction project (MRP)

[New Game Project2.zip](https://github.com/godotengine/godot/files/14629141/New.Game.Project2.zip)

**Comment by akien-mga** [comment]
The steps to reproduce are a bit too generic, it's hard to confirm the bug with it.
The MRP also includes scenes which can't be opened due to missing dependencies (assets have been removed, etc.) so it doesn't reproduce that bug specifically, but only the fact that scenes with broken dependencies trigger another error.

Can you still reproduce the issue with 4.2.2-rc2 and 4.3-dev5? There have been several improvements recently regarding this kind of "corrupt scene" issues.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
