### ISSUE TITLE
Custom action keys/buttons are not saved

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#8969]
**Operating system or device - Godot version:**
3.0 master Linux

**Steps to reproduce:**
- Create new action in project and attribute some keys/buttons to it
- Save and close project
- When reopening project all keys/buttons for action are gone

**Comment by ficoos** [comment]
It's a regression from the removal of InputEvent as a built in type. When it was removed the serialization was removed and now it in `VariantWriter::write` it falls to the case of `Variant::OBJECT` that assumes a Resource with a path, InputEvent is not such a Resource so it emits `null` as a fallback.

I don't have time to fix this, just putting it here to make the life of whoever fixes this easier.

**Comment by mcanders** [comment]
I'm currently taking a stab at this.  I have keyboard mapping working again.  I just need to implement and test the other input types.

**Comment by mcanders** [comment]
I was just about to submit a pull request ([see my branch here](https://github.com/mcanders/godot/tree/mcanders/InputMapFix)) when I discovered that @reduz probably sort of fixed this in his "Added .hdr format support" commit.  His approach serializes all object properties instead of hand selecting them.  Its more generic, but it also fills config files with a lot more cruft:

Old approach (used in my branch):
```
test=[
InputEvent(KEY65,C)
]
```

New:
```
[input]

test=[ Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","alt":false,"shift":false,"control":true,"meta":false,"command":true,"pressed":false,"scancode":65,"unicode":0,"echo":false,"script":null)
 ]
```
I can see this destroying the legibility of large input maps.

I attempted to test loading and saving input maps with his new approach, but I hit a couple of problems:
1)  The new function "get_fallback_environment()" introduced in the hdr commit segfaulted when I saved the input map config, but it still wrote the input map to my project file (so thats probably a separate issue)
2) Attempting to start godot with the new config resulted in the error: "error: Expected property name as string"


Provided the new approach actually works, I like the idea of generically handling Variant:OBJECT and the more human readable shift/control/meta/alt (vs S/C/M/A).  But it would also be nice to preserve the terseness of the original format.

**Comment by mcanders** [comment]
Some follow up:
1) The Object parser in variant_parser currently has the following issues:
    * It attempts to read the property name twice, which causes the parsing to error out.  removing the second get_token results in a successful parse
    * the output variable "value" is not being set after a successful parse
2) I fixed the problems in (1) and Object loading no longer fails, but the parsed InputEvent objects still aren't added to the input map because the conversion from Variant:OBJECT -> Ref&lt;InputEvent&gt; is failing (input_event.is_null() returns false).  
    * I have verified that the type in "Object *obj = ClassDB::instance(type)"  is correct (InputEventKey, InputEventJoypadButton, etc). 
    * I have also verified that Object's properties are being set to the correct values from the InputEvents.  ex: the Object property "scancode" is set to a Variant::INT with a value of 65

Does anyone have a clue what could be going wrong in the conversion?  I'm less familiar with that section of the code.

**Comment by ficoos** [comment]
Varaint is one of the more horrible parts of Godot.

When [creating a Variant from an Object*](https://github.com/godotengine/godot/blob/5b3709d3096df737b8bb2344446be818b0389bfe/core/variant.cpp#L2273) no Reference is created only the `objData.obj` is assigned and not `objData.ref`. When you [cast to Ref](https://github.com/godotengine/godot/blob/5b3709d3096df737b8bb2344446be818b0389bfe/core/variant.cpp#L1731) it's assumed that for all objects a ref is valid (which is not the case).

You can also see the horrible const violation and notice that actually casting from\to object (from a technical C++ perspective) shouldn't be possible and only RefPtr should be since the value is the Ref and not the object.

&lt;rant&gt;
I actually tried to remove the Object conversion but then the code compiles but crashes randomly since Object has an implicit cast to bool (why?) and this causes the template magic to assume that all assignments from Object -> Variant should create a bool variant. This means it's impossible to have the compiler check and modify all the places that convert from\to Object.
&lt;/rant&gt;

**Comment by mcanders** [comment]
Ok I'm pretty sure everything is working now.  This line did the trick:

```cpp
// value is the variant output variable from parse_value()
value = REF(obj->cast_to<Reference>());
```

Thanks for the assistance!  That last comment was hugely helpful.  I should have a pr out soon.
