### ISSUE TITLE
Autoplay animation starts from last editor state

### ISSUE THREAD

**Issue by honix** [godotengine/godot#8976]
New objects with autoplay animation _**renders their first frame with state i leaved in editor**_. Next frames draws according autoplay animation. I think it is bad behavior.

For example i want my scene to smooth alpha intro. If i leave animation editor somewhere in the middle, new instances will flicker a frame. To fix this i will put time marker right to the start (where alpha is 0). It is uncomfortable to do: i must do this with every autoplay animation. But when i want to edit scene i will make it visible by dragging time marker, and then pop it to start when i'm done.

I think autoplay animation will start and draw the first frame as it in animation 0 frame.

**Link to minimal example project:** shows flickering and fixed version of same animation
[test-anim.zip](https://github.com/godotengine/godot/files/1034456/test-anim.zip) (Godot 3.0 project)

ps: this issue meets at any versions of Godot

**Comment by puppetmaster-** [comment]
there is also a problem with unfortunately changing a scene and saving it.
I don't know if its possible to rewind each animation before saving (scene) or playing (scene/project).

**Comment by HummusSamurai** [comment]
Note that this is extra tiresome when using multiple animation that transition into each other, as they will _all_ need to be rewound to get back to the initial point.

**Comment by bojidar-bg** [comment]
The rewinding discussion should go to #812, as it is unrelated to the original post.

This issue is, as the OP mentioned, about the problem that autoplay animations are waiting a whole frame before updating the values.

Tagging as junior job, as all that has to be done is calling `_animation_process(0)` around [line 203](https://github.com/godotengine/godot/blob/master/scene/animation/animation_player.cpp#L203) (after the call to `play()`).
