### ISSUE TITLE
`NOTIFICATION_TRANSLATION_CHANGED` gets sent at wrong times

### ISSUE THREAD

**Issue by Kiisu-Master** [godotengine/godot#89804]
### Tested versions

- Reproducible in 4.3.dev4, 4.3.dev5
- Not reproducible in 4.3.dev3

Likely due to #87530 (@YeldhamDev)

### System information

Windows 10

### Issue description

The notification `NOTIFICATION_TRANSLATION_CHANGED` now gets emit when ~~creating nodes~~ nodes enter the tree. 

It happens before the node is ready, which leads to crashes in one of the most common use case: you hook something like `update_ui()` to it. Generally the function to update UI will set a bunch of text on other nodes, but as the node just got created and its children aren't ready, it will lead to crashes. This also creates duplicate calls to the `update_ui`, because in most uses `_ready` would already take care of initial setup call.

### Steps to reproduce

- Create a scene with node that listens on `_notification` for `NOTIFICATION_TRANSLATION_CHANGED`. (print something or put a breakpoint)
- The notification will happen when running project, even when locale did not change.

### Minimal reproduction project (MRP)

[Translation changed bug MRP.zip](https://github.com/godotengine/godot/files/14731563/Translation.changed.bug.MRP.zip)

**Comment by AThousandShips** [comment]
This is by design, and it matters, the translation isn't known until it enters the tree so having this emitted is necessary, how else would you know what the configured translation for the tree is?

This should maybe be documented better though

**Comment by Kiisu-Master** [comment]
> This is by design, and it matters, the translation isn't known until it enters the tree so having this emitted is necessary, how else would you know what the configured translation for the tree is?

- The notification is sent when node enters tree. That is incorrect time to send notification, as the translation didn't change.
- The node doesn't need to know that it entered tree by receiving the `NOTIFICATION_TRANSLATION_CHANGED`.
- The node does not receive info about the locale from the notification,  and it doesn't need to. It would in most cases just use `tr()` to retranslate all text after translation changed.

> >This also creates duplicate calls to the update_ui, because in most uses _ready would already take care of initial setup call.

> The solution to that is to just do those on the translation notification though, right?

Using the translation notification instead of  `_ready` for initialization seems crazy to me.

In my opinion the notification should only be sent when setting the locale, not when node enters tree. That would be how it worked before 4.3.dev4.

**Comment by AThousandShips** [comment]
> The notification is sent when node enters tree. That is incorrect time to send notification, as the translation didn't change.

How would you know?

> Using the translation notification instead of _ready for initialization seems crazy to me.

Well that's your opinion, and it's different from the people developing this feature :)

**Comment by Kiisu-Master** [comment]
> > The notification is sent when node enters tree. That is incorrect time to send notification, as the translation didn't change.
> 
> How would you know?

Well, as i am the one who wrote the code of the MRP , i know it will never change the translation, nor does it even have any translations in the project.

> > Using the translation notification instead of _ready for initialization seems crazy to me.
> 
> Well that's your opinion, and it's different from the people developing this feature :)
 
Uhhh

**Comment by AThousandShips** [comment]
> Well, as i am the one who wrote the code of the MRP , i know it will never change the translation, nor does it even have any translations in the project.

So you don't care about this notification... So your use case isn't relevant

**Comment by Kiisu-Master** [comment]
> > Well, as i am the one who wrote the code of the MRP , i know it will never change the translation, nor does it even have any translations in the project.
> 
> So you don't care about this notification... So your use case isn't relevant, why are you even using the notification if you're not using translation?

No i just made a MRP. I discovered the problem in [GodSVG ](https://github.com/MewPurPur/GodSVG)when opening in 4.3 dev. It will currently crash due to this when you click on the settings button. This doesn't happen in 4.2 or 4.3.dev3.

> How would you know that your node is configured for the current locale?

It just entered the tree and used the currently set locale to translate everything. The notification is generally only used to update nodes when they are already in the tree.

**Comment by AThousandShips** [comment]
> It just entered the tree and used the currently set locale to translate everything. The notification is generally only used to update nodes when they are already in the tree.

That's inefficient though, why not just use the single notification, that's much more efficient, you're only considering this an issue because you're used to one method, it makes a lot of sense and improves a lot of code, avoids duplication of code, etc.

You really don't see the value of this?

But as I said already, you need to adjust your code to how the engine works, that's what happens with compatibility breakage :) so the crash isn't a bug with this, it's because your code isn't fixed to adjust to how the engine works, please try updating your code so it works

**Comment by MewPurPur** [comment]
> That's inefficient though, why not just use the single notification

How would the code of the MRP need to change?

**Comment by AThousandShips** [comment]
To adjust to translation specially, handle it in a safe way, I don't see why you change the translation of another node, it should do that itself?

**Comment by KoBeWi** [comment]
`NOTIFICATION_TRANSLATION_CHANGED` now fires consistently with `NOTIFICATION_THEME_CHANGED` - when node enters tree. This is the first occasion when a translation/theme can be consistently fetched, hence you are supposed to use it to update your theming and strings that don't use auto-translation.

Note however that these notifications are mostly used internally, where nodes are created from code instead of being part of an instantiated scene. Hence there is discrepancy between core usage and how would users typically use it. You should use these notifications only on the current nodes, nodes created from script inside `_init()`, and if you want to use it on child nodes created in the editor, you need to wait until ready signal.

We should document this if it isn't mentioned already.
