### ISSUE TITLE
Error: Couldn't load project data at path ".". Is the .pck file missing?

### ISSUE THREAD

**Issue by wpbirney** [godotengine/godot#89825]
### Tested versions

- Reproducible in: fe01776f05b1787b28b4a270d53037a3c25f4ca2
- Introduced in: 5e6adb4a2dd947432e59ca00b6d046a68c534e10

### System information

Godot v4.3.dev (fe01776f0) - Void #1 SMP PREEMPT_DYNAMIC Fri Mar  8 01:01:43 UTC 2024 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) () - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

Getting `Error: Couldn't load project data at path ".". Is the .pck file missing?` when running a build of the engine in same directory as the same named pck. Same error when using --main-pack.

`git revert 5e6adb4a2dd947432e59ca00b6d046a68c534e10` fixes the issue

### Steps to reproduce

- Make an empty project on linux with a master build of godot
- add a main scene and attach a script with a class_name
- export the pck
- copy the godot binary to the same location and rename to match pck
- run

### Minimal reproduction project (MRP)

N/A

**Comment by wpbirney** [comment]
I dug into this a little today and noticed that after 5a6adb4 my exported pck from the editor no longer contains `res://project.binary` which is causing the issue.

**Comment by wpbirney** [comment]
https://github.com/godotengine/godot/commit/5e6adb4a2dd947432e59ca00b6d046a68c534e10#diff-a64507e1723f451757967d0bcb08c8e8999bc77b5d4863e9c71133432140b17fR1798

changing this to `true` made my pck's exported via the editor have all the required files again.

**Comment by akien-mga** [comment]
CC @ogapo @mihe

**Comment by ogapo** [comment]
Sounds like the way you are exporting (or an error in the code) is creating a non-main PCK rather than a runnable one. My understanding is that in the export dialog "Export Project"  makes a full PCK (with the project file and icons and such) and "Export PCK/Zip" is intended to make content-only PCKs (suitable for DLC). 

Source (assuming I'm interpreting correctly) https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html

Are you doing Export Project?

**Comment by akien-mga** [comment]
> My understanding is that in the export dialog "Export Project" makes a full PCK (with the project file and icons and such) and "Export PCK/Zip" is intended to make content-only PCKs (suitable for DLC).
> 
> Source (assuming I'm interpreting correctly) https://docs.godotengine.org/en/stable/tutorials/export/exporting_projects.html

That's a misinterpretation, "Export PCK/Zip" should (at least by default) export the exact same PCK file that "Export Project" would.

> Export PCK/ZIP: Export the project resources as a PCK or ZIP package. This is not a playable build, it only exports the project data without a Godot executable.

With such a PCK, you can run Godot with `godot --main-pack data.pck` and it should run fine.

**Comment by mihe** [comment]
I'll admit to having missed this use-case as well, but I see now that it's also quite clearly spelled out under "Export approaches" on the ["Exporting for dedicated servers"](https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_dedicated_servers.html) page:

> Export a PCK file only, preferably for the platform that matches the platform that will host the server. Place this PCK file in the same folder as an export template binary, rename the binary to have the same name as the PCK (minus the file extension), then run the binary.

This is somewhat of a quick kneejerk fix, and largely untested, but it seemed like a straight-forward and reasonable compromise: #89928

Let me know what you think in the PR.

**Comment by aaronfranke** [comment]
I can confirm that this is not working. Specifically it is not able to find `project.godot` or `project.binary` inside the PCK.

![pck-error](https://github.com/godotengine/godot/assets/1646875/3e86a856-f455-4d3e-8efe-a80935cf0175)

**Comment by hsandt** [comment]
I got this issue while doing normal Exports (no separate pck export, and it should produce same pck as commented above anyway), but only when using certain names for folders and binary, such as: `v4.2.1 - Dialogic project Linux build crash on start (compile error)/v4.2.1 - Dialogic project Linux build crash on start (compile error).x86_64` but not when I remove 1 character. Sometimes the error would occur anyway at first but not after exporting more files with different names in the same folder, making it very hard to grasp.

I checked the file commits for the fix but I don't see an obvious cause of how path usage affects the result. Should I just trust that this fix will also fix these particular export path naming?

In fact, I got a copy of Godot 4.3 dev 6 and just tried it, I cannot repro - but at the same time Godot 4.3 now generates fully hyphenated project path names by default for extra safety, so it's hard to tell.

I cannot switch version right now (middle of jam, need something stable), so I'll just avoid long export path names.

**Comment by TheWarmWaffle** [comment]
I got this bug when compiling using `target=template_debug` on godot-4.3 windows, getting rid of that parameter generated a working godot.

**Comment by egwynn** [comment]
> I got this bug when compiling using `target=template_debug` on godot-4.4 windows, getting rid of that parameter generated a working godot.

Same here but on macOS.

```
$ scons platform=macos arch=x86_64 debug_symbols=yes target=template_debug
# [ truncated ]

$ ./bin/godot.macos.template_debug.x86_64 --version
4.5.dev.custom_build.e45cc6809

$ ./bin/godot.macos.template_debug.x86_64 -s example.gd --headless
Error: Couldn't load project data at path ".". Is the .pck file missing?
If you've renamed the executable, the associated .pck file should also be renamed to match the executable's name (without the extension).

$ echo $?
1

$ scons platform=macos arch=x86_64 debug_symbols=yes
# [ truncated ]

$ ./bin/godot.macos.editor.x86_64 -s example.gd --headless
Godot Engine v4.5.dev.custom_build.e45cc6809 - https://godotengine.org
$ echo $?
0
```

**Comment by akien-mga** [comment]
This issue was a temporary regression during the 4.3 release cycle, which has long been fixed. Please don't comment on it as new reports are not related.

The error message you see is not a bug usually - it's a sign that you're running an export template which can't find the project data pck file. The export template isn't intended to be run standalone. That's likely the issue with @TheWarmWaffle's report on https://github.com/godotengine/godot/issues/89825#issuecomment-2298357238.

For @hsandt's report in https://github.com/godotengine/godot/issues/89825#issuecomment-2133705435, it might have been related to the bug being fixed here since you tested around the same time, and claim it's fixed in 4.3-dev6 (which is when this bug got fixed, after being introduced in 4.3-dev5). If you can still reproduce the issue though, please open a dedicated bug report.

For @egwynn's report in https://github.com/godotengine/godot/issues/89825#issuecomment-2954512874, this is a separate bug. The problem seems to be that the `--script` option doesn't work as expected in export templates. I think I've seen a bug report about this in the past but couldn't find it again.

**Comment by egwynn** [comment]
@akien-mga ok let me know if you think I should open a new issue about my experience.

**Comment by akien-mga** [comment]
@egwynn I went ahead and opened an issue myself with some debugging info: https://github.com/godotengine/godot/issues/107318
