### ISSUE TITLE
await bug

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#89876]
### Tested versions

v4.3.dev5.mono.official [89f70e98d]

### System information

Godot v4.3.dev5.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 5GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/af32a9ba-7de0-4f75-a502-6aff651af156)
It not print the "---sssss"

### Steps to reproduce

Please run the MRP

### Minimal reproduction project (MRP)

[await_test.zip](https://github.com/godotengine/godot/files/14741158/await_test.zip)

**Comment by 1419427247** [comment]
This behavior arises due to the fact that class A inherits from a system with reference counting. When the function execution terminates, any instances of class A will be automatically destructed. The solution to prevent this premature destruction would be to re-define 'a' as a member variable within the class definition itself.

**Comment by AThousandShips** [comment]
This is indeed the case, I'd say it's intended and the lifetime shouldn't be extended here

**Comment by KoBeWi** [comment]
Related #65884

**Comment by CsloudX** [comment]
Oh, I see.
