### ISSUE TITLE
GDScript Analyzer cannot correctly resolve C# arguments methods.

### ISSUE THREAD

**Issue by ZerxZ** [godotengine/godot#89924]
### Tested versions

v4.3.dev5.mono.official.89f70e98d

### System information

Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 Laptop GPU (NVIDIA; 31.0.15.5123) - 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 Threads)

### Issue description

It runs correctly in version 4.2.1, but errors occur starting from version 4.3.
If this segment of source code is removed, runs normally.
https://github.com/godotengine/godot/blob/7d151c83811f8ac8873439826c16d88c83aba12f/modules/gdscript/gdscript_analyzer.cpp#L3307

CSharp:
```csharp
using Godot;
using System;

public partial class GlobalDotnetScript : Node
{
    public static void SayHi(int a, int b, int c, int d, int e, int f)
    {
        GD.Print($"[GlobalDotnetScript] SayHi: {a}, {b}, {c}, {d}, {e}, {f}");
    }

    public void SayHello(int a, int b, int c, int d, int e, int f)
    {
        GD.Print($"[GlobalDotnetScript] SayHello: {a}, {b}, {c}, {d}, {e}, {f}");
    }
    public static void SayHi()
    {
        GD.Print($"[GlobalDotnetScript] SayHi!");
    }

    public void SayHello()
    {
        GD.Print($"[GlobalDotnetScript] SayHello!");
    }
}
```
GDScript:
```gdscript
extends Node

const GlobalDotnetScript = preload("res://GlobalDotnetScript.cs");

func _ready() -> void:
	GlobalDotnetScript.SayHi(1,2,3,4,5,6);
	var node =GlobalDotnetScript.new();
	add_child(node);
	node.SayHello(1,2,3,4,5,6)
	# Parse Error: Too few arguments for "SayHello()" call. Expected at least 6 but received 0.
	node.SayHello();
	# Parse Error: Too few arguments for "SayHi()" call. Expected at least 6 but received 0.
	GlobalDotnetScript.SayHi();
```

### Steps to reproduce

1. Open the project.
2. Open the 'test_node.tscn' scene and run it.

### Minimal reproduction project (MRP)

[csharp-test-method.zip](https://github.com/godotengine/godot/files/14764056/csharp-test-method.zip)

**Comment by dalexeev** [comment]
* See #85703.

I think that this is not a regression, since GDScript was not previously aware of the other languages. Probably the problem is that the Godot API (`MethodInfo`) does not work correctly with method overloads (only built-in constructors and operators). So this is probably a question for the @godotengine/dotnet.

**Comment by roookeee** [comment]
Giving my 2 cents because I dove into the C# binding recently:

https://github.com/godotengine/godot/pull/85703/ was implemented by calling `get_method_info(string)` which only does [a lookup by name](https://github.com/godotengine/godot/blob/7d151c83811f8ac8873439826c16d88c83aba12f/modules/mono/csharp_script.cpp#L2636), disregarding any kind of parameter count checks.

Technically speaking `MethodInfo` contains [the argument count information](https://github.com/godotengine/godot/blob/7d151c83811f8ac8873439826c16d88c83aba12f/core/object/object.h#L225) which could be used for looking up the correct overloadb by name and parameter count.

Please note that same argument count overloading by type will not work as that is currently not handled by the C# binding.
