### ISSUE TITLE
mod negative should be positive

### ISSUE THREAD

**Issue by theromis** [godotengine/godot#89930]
### Tested versions

4.3-dev5

### System information

Linux

### Issue description

-11 % 7 = 3
but gdsctipt gives: -4
https://math.stackexchange.com/questions/2179579/how-can-i-find-a-mod-with-negative-number

### Steps to reproduce

print("mod: ", -11 % 7)

### Minimal reproduction project (MRP)

[mod-example.zip](https://github.com/godotengine/godot/files/14766274/mod-example.zip)

**Comment by a-johnston** [comment]
Sounds like you want to use `posmod` instead of `%`. See the note in the gdscript reference about `%`.

**Comment by theromis** [comment]
@a-johnston sorry can't find, just compared python behavior, but sounds like python `%` is `posmod` in gdscript, if this is correct sorry for creating issue.

**Comment by a-johnston** [comment]
From the <https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html> description for the `%` operator:
> Note: These operators have the same behavior as C++, which may be unexpected for users coming from Python, JavaScript, etc. See a detailed note after the table.

and then later after the table:

> [..]
For negative values, the % operator and fmod() use [truncation](https://en.wikipedia.org/wiki/Truncation) instead of rounding towards negative infinity. This means that the remainder has a sign. If you need the remainder in a mathematical sense, use the [posmod()](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-posmod) and [fposmod()](https://docs.godotengine.org/en/stable/classes/class_%40globalscope.html#class-globalscope-method-fposmod) functions instead.

**Comment by theromis** [comment]
Any way, my bad sorry, but at least might be helpful to meta + click on % to get description what is this operation and other alternatives especially for python stuff.

**Comment by TokageItLab** [comment]
This is a common problem in computer math. In some languages, the results may even vary depending on the compiler, but in gdscript, the results should be consistent with posmod.
