### ISSUE TITLE
Scene without changes got saved (give some unexpected behaviors)

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#8994]
**Operating system or device - Godot version:**
Window 7, v2.1.3.stable.official

**Issue description:**
Scene without changes got saved.
Example: When editor setting "Auto Save Before Running" is on it give some unexpected behaviors. 
![scene_got_saved_also_when noting_has_changed](https://cloud.githubusercontent.com/assets/10463138/26560555/da5560b2-44b7-11e7-8bba-eec27183e60a.gif)

For me is OK when playing around with animation, godot don't see it has change.

**Link to minimal example project:**
[issue_save_and_animationplayer.gz](https://github.com/godotengine/godot/files/1036867/issue_save_and_animationplayer.gz)

**Comment by eon-s** [comment]
The AnimationPlayer should reset on load or keep the saved position on the track?

**Comment by puppetmaster-** [comment]
I think it's a kind of a philosophy.. but for me it should be
no change = no save

Also with fold / unfold there is no change indicator (*) and state got saved.
 ![image](https://cloud.githubusercontent.com/assets/10463138/26606019/8e57340e-4590-11e7-98f4-aff7216bf1d4.png)

**Comment by Zylann** [comment]
On huge scenes, saving while not modified is an annoyance because it pops a modal progress bar that can last for a few seconds depending on how big the scene is (typical example: terrains, including gridmap and tilemaps). For this reason I also disabled Ctrl+S for scenes because it made the script editor a pain to work with^^"

**Comment by kubecz3k** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about its current status here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by aaronfranke** [comment]
Is this only a problem with AnimationPlayer? If so, that should be added to the title.

> Also with fold / unfold there is no change indicator (*) and state got saved.

This is going to be removed in the future AFAIK. https://github.com/godotengine/godot/issues/15982 https://github.com/godotengine/godot/issues/20994

**Comment by akien-mga** [comment]
This issue is not so clear to me, I don't see any bug in the OP's GIF.

It didn't seem to be about the same thing as what @Zylann then commented about from Ctrl+S saving scenes and not only scripts, possibly leading to progress bars while saving the scene. It's a separate issue and should likely be discussed in a proposal on [godot-proposals](https://github.com/godotengine/godot-proposals) if this should be changed.
