### ISSUE TITLE
Vulkan Mobile: Mesh Flickering in VR on Quest 3

### ISSUE THREAD

**Issue by szybre** [godotengine/godot#89985]
### Tested versions

Reproducible in Godot 4.2.1.stable

### System information

Windows 10 / Oculus Quest 3 Android OS, XR2 Gen2 processor, Vulkan (Mobile) renderer

### Issue description

After a couple of seconds of the game running natively on Meta Quest 3, all meshes and shadows start flickering. This issue wasn't happening before disabling glow in the WorldEnvimoement node, which increased FPS. Further performance optimizations, like baking the lights, seemed to have worsened the problem. I suspect the more FPS the game runs on, the faster and worse it glitches.

https://github.com/godotengine/godot/assets/74175210/bbfff011-fdd5-42f1-b4cb-5a4418a9102c

### Steps to reproduce

Download the demo included below and export it for your Quest device
The bug should occur on its own after a little bit of time

### Minimal reproduction project (MRP)

The file is too big for GitHub, so I had to share it through Google Drive
https://drive.google.com/file/d/1C3jSADayxaEMJkqjGh7-FmBzPASskql_/view?usp=sharing

This is the most basic Godot VR project with the ability to export for the Quest family of devices. Inside you can find a lot of stacked cube meshes that demonstrate very well these artifacts.

**Comment by AThousandShips** [comment]
Can you please try in [4.2.2.rc2](https://godotengine.org/article/release-candidate-godot-4-1-4-and-4-2-2-rc-2/)?

**Comment by szybre** [comment]
The bug still appears after re-exporting the game using 4.2.2.rc2

https://github.com/godotengine/godot/assets/74175210/96bfb5c2-7c91-418b-afdd-2b4a983ee400

**Comment by Psychophylaxis2** [comment]
I can confirm this issue. I get the same effect on Quest 3 in my application. It appears to get worse as more complex meshes are added to a scene.

**Comment by aloiscochard** [comment]
I can also confirm this issue. I tried different rendering pipeline without seeing any difference, also note that the flickering is gain worse (or it is simply more noticable?) when using passthrough.

**Comment by BStbck** [comment]
I have the same problem on Quest 3 with the mobile renderer using Godot 4.2.2. For me the problem completely disappears when switching to the compatibility renderer.

**Comment by eelcor** [comment]
Any progress on this topic? It is also apparent in 4.3 beta 1. It seems to get worse when using large meshes. In the forums the flickering is also mentioned. https://forum.godotengine.org/t/grey-flickering-in-vr-on-quest-3/54447 

Any thing I can do?

Kind regards,
Eelco

**Comment by Psychophylaxis2** [comment]
I can confirm the issue remains on Godot 4.3 Beta 2 with the 3.0.0 Beta2 vendor library and visible in the OpenXR Tools Demo scenes. Quest 3 firmware 67.0.0.458.356.614892285

**Comment by RevoluPowered** [comment]
Reported to meta as I am having the same issue, godotengine dev chat discussions have revealed the most likely cause is a driver issue.

https://communityforums.atmeta.com/t5/Quest-Development/Standalone-Vulkan-in-headset-not-working-correctly-Huge/m-p/1213491#M10147

**Comment by szybre** [comment]
Great that this issue is known, but as long as it exists, making oculus games is impossible.

**Comment by RevoluPowered** [comment]
The driver issue is flagging a warning every time the flickering occurs, it looks like the same frequency
```
Android 19421 20:48:20 vk_core.cpp(4739) Warning [0] The following warning was triggered: VKDBGUTILWARN003. Please refer to the Adreno Game Developer Guide for more information: https://developer.qualcomm.com/sites/default/files/docs/adreno-gpu/snapdragon-game-toolkit/learn_guides.html
```

Taken from the meta quest render doc app.

I am working on solving this problem, I am installing the snapdragon tools as per the manual here it recommends this because I can find the sub pass specifically that is failing.

Relevant docs are here:
- https://developer.qualcomm.com/sites/default/files/docs/adreno-gpu/snapdragon-game-toolkit/learn_guides.html

I am working on this for the mirror right now and hope I can find a fix for the problem if I can I'll submit a PR and a patch to unblock things.

**Comment by GaelFG-Anderon** [comment]
@clayjohn I just tried a an export based on your pull request on my 'true' full scale project and the improvement on quest3 is amazing even with the passthrought activated (where there was a lot of flickering, even more than with pure vr rendering)  :

https://github.com/user-attachments/assets/66856153-69ff-4506-b0a7-dd208d6d6178

Comparaison with nearly identical project state on godot 4.3.beta2 : 

https://github.com/user-attachments/assets/db695d27-20f8-4713-ba40-1a63fb54d1e0

Thanks a lot and congrats to all of you by the way, I followed some conversations and this bug seems very obscure :p
I will made more extensive testing and will report if some glitches are still spotted.

**Comment by eelcor** [comment]
Does this mean the "fix" will be applied to the next beta/release
candidate? It would be great!

Kind regards,
Eelco

Op ma 15 jul 2024 om 14:10 schreef GaelFG-Anderon ***@***.***

**Comment by clayjohn** [comment]
> Does this mean the "fix" will be applied to the next beta/release candidate? It would be great! 

That's the plan! We would like to include this fix in RC1

**Comment by eelcor** [comment]
And is the fix implemented in RC1? I can't see it in the release notes.

Kind regards,
Eelco

Op wo 17 jul 2024 om 07:03 schreef Clay John ***@***.***>:

**Comment by akien-mga** [comment]
@eelcor It is, see https://godotengine.github.io/godot-interactive-changelog/#4.3-rc1

>  Use a spec constant to control whether the MultiMesh branch is used in the vertex shader (GH-94289).
