### ISSUE TITLE
ResourceLoader.load_threaded_get_status always returns [0] progress

### ISSUE THREAD

**Issue by DarkMessiah** [godotengine/godot#90076]
### Tested versions

- Reproducible in: 4.2.2rc2, 4.3.dev5
- Not reproducible in: 4.2.1.stable

### System information

Godot v4.2.2.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4070 Ti (NVIDIA; 31.0.15.5186) - 13th Gen Intel(R) Core(TM) i7-13700K (24 Threads)

### Issue description

The same problem as here https://github.com/godotengine/godot/issues/56882, which returned after https://github.com/godotengine/godot/pull/87711, I guess.
ResourceLoader.load_threaded_get_status always return progress with [0] and returns [1] at the end.

**4.2.1**

https://github.com/godotengine/godot/assets/1756388/536ec4ea-b7e9-4345-b5c1-87757354f8cf

4.2.1 also has a bug, that after 49% it drops to 41%

**4.2.2 and 4.3.dev**

https://github.com/godotengine/godot/assets/1756388/4e1ab051-1a30-46c8-92ac-4644c90646e6

### Steps to reproduce

1) Load packed scene with ResourceLoader.load_threaded_request
2) Try to get progress with ResourceLoader.load_threaded_get_status
3) Progress always [0]

### Minimal reproduction project (MRP)

[resource-loader-bug.zip](https://github.com/godotengine/godot/files/14817027/resource-loader-bug.zip)

1) Extract project
2) Copy `Bistro_v5_2` to the project (https://developer.nvidia.com/orca/amazon-lumberyard-bistro)
3) Press load

**Comment by ajreckof** [comment]
I'm looking into it but most likely the sub loading tasks are not properly registered hence you only see the progress on the main loading taks which goes from 0 to 1 once all dependency are loaded because there is little to nothing to do on the main loading task.

**Comment by AlexOtsuka** [comment]
https://github.com/godotengine/godot/pull/87711 is the cause of the regression.

This is the call to `_load()` resulting from calling `load_threaded_request()`:

`Ref<Resource> res = _load(load_task.remapped_path, load_task.remapped_path != load_task.local_path ? load_task.local_path : String(), load_task.type_hint, load_task.cache_mode, &load_task.error, load_task.use_sub_threads, &load_task.progress);`

What's relevant here is the ternary condition, which is the value pass in `p_original_path`:

`load_task.remapped_path != load_task.local_path ? load_task.local_path : String()`

When the condition is false, which at least in the editor, is almost always, we're pushing an empty string into `load_paths_stack`, and inserting an empty string in the `sub_tasks` HashSet over and over (which given that it's a HashSet, doesn't even do anything anymore after the first time).

By reverting the changes from https://github.com/godotengine/godot/pull/87711, the MRP behaves exactly like it does in 4.2.1, with the exception that it stops at 49% for a while instead of jumping back to 41%, which I assume still happens but is masked by the `ThreadLoadTask.max_reported_progress` value. I have no idea whether this works in an exported build, as I haven't had the time to test it.

I'm not sure the assumption in the PR that `p_path` can be the path to the imported file in .godot is true. Both `load_threaded_request()` and `load_threaded_status()` should normally be called using the exact same `String` value as their path argument. Furthermore, the first thing `_load_start()` does is call `_validate_local_path()`. Both `p_path` and `p_original_path` in `_load()` should originate from that validated local path value anyway.

If there is a counter-example MRP of the https://github.com/godotengine/godot/pull/87711 working as intended, I'd love to take a look at it as it doesn't really make sense to me.

**Comment by ajreckof** [comment]
I agree with what has been state above to elaborate a bit more there is two thing first instead of just using `p_original_path` it should check if it is empty and use `p_path` if it is the case this is already what is happening a few line below for the call to load on the plugin so this looks more like an oversight.

The second part is a bit harder because when you look at a original path you will see there is a nested resource inside the .fbx that is a .scn rendering the fbx which has an original path set to the exact same file(whhich is dfinitly ok) correcting the first error will make a crash because of this (task being a subtask of itself -> infinite loop). One way to fix that would be to check that it is different before setting not 100% sure this is okay but will try and make a PR so that people can try.

**Comment by AlexOtsuka** [comment]
> I agree with what has been state above to elaborate a bit more there is two thing first instead of just using `p_original_path` it should check if it is empty and use `p_path` if it is the case this is already what is happening a few line below for the call to load on the plugin so this looks more like an oversight.
> 
> The second part is a bit harder because when you look at a original path you will see there is a nested resource inside the .fbx that is a .scn rendering the fbx which has an original path set to the exact same file(whhich is dfinitly ok) correcting the first error will make a crash because of this (task being a subtask of itself -> infinite loop). One way to fix that would be to check that it is different before setting not 100% sure this is okay but will try and make a PR so that people can try.

Yeah, this fix was the first thing I tried as well, and I couldn't avoid running into the stack overflow crash no matter how I approached it. As you said, nested resources need to be accounted for.

**Comment by ajreckof** [comment]
> Yeah, this fix was the first thing I tried as well, and I couldn't avoid running into the stack overflow crash no matter how I approached it. As you said, nested resources need to be accounted for.

I tried to look but it seems if there is a nested resource during import it will extract the resource and create an actual file for it hence the only real nested resource is the one which is the dual (equivalent of the resource in a format natie to the engine).

> Edit: just saw your PR, I can imagine it working. I'll test it as soon as I have the time.

Thanks

**Comment by conde2** [comment]
I'm having the same problem, ResourceLoader.LoadThreadedGetStatus always showing 0 to me.

![image](https://github.com/godotengine/godot/assets/2137569/927505ee-b2ba-4cbb-9edc-317d37c546f4)


```C#

            // Construct the path to the scene file
            var scenePath = $"res://instances/{instanceName.ToSnakeCase()}/{instanceName.ToPascalCase()}.tscn";

            var error = ResourceLoader.LoadThreadedRequest(scenePath);
            GD.PrintErr($"Loading scene: {scenePath} {error}");
            var percentageReport = new Godot.Collections.Array();

            double percentage;
            ResourceLoader.ThreadLoadStatus loadingStatus;
            do
            {
                loadingStatus = ResourceLoader.LoadThreadedGetStatus(scenePath, percentageReport);
                if (loadingStatus == ResourceLoader.ThreadLoadStatus.Failed)
                {
                    GD.PrintErr($"Failed to load scene at path: {scenePath}");
                    ClientNotification.ShowNotification($"Failed to load scene at path: {scenePath}", GameNotificationType.Error);
                    return;
                }

                percentage = percentageReport[0].As<double>();
                GD.PrintErr($"Loading scene: loading: {loadingStatus} scene: {scenePath} percentage: {percentage} {percentageReport}");
            } while (loadingStatus == ResourceLoader.ThreadLoadStatus.InProgress);
```
