### ISSUE TITLE
Double Precision with CSharp?

### ISSUE THREAD

**Issue by nbstrong** [godotengine/godot#90184]
### Tested versions

- 4.2.1-stable

### System information

Windows 11

### Issue description

I should be building godot with precision=double and module_mono_enabled=yes. And yet, when I try to build my csharp project, it thinks that Vector3's are floats.

`Operator '*' cannot be applied to operands of type 'Vector3' and 'double'`

### Steps to reproduce

Here is my build script:

```
# Set the nuget source
dotnet nuget remove source MyLocalNugetSource
dotnet nuget locals all --clear
dotnet nuget add source "$(pwd)/MyLocalNugetSource" --name MyLocalNugetSource

# Build godot
scons platform=windows target=editor production=yes module_mono_enabled=yes precision=double
scons platform=windows target=template_debug production=yes module_mono_enabled=yes precision=double
scons platform=windows target=template_release production=yes module_mono_enabled=yes precision=double

# Generate the mono glue
bin/godot.windows.editor.double.x86_64.mono.exe --headless --generate-mono-glue ./modules/mono/glue

# Build the mono assemblies
modules/mono/build_scripts/build_assemblies.py --godot-output-dir=./bin --precision=double --godot-platform=windows --push-nupkgs-local $(pwd)/MyLocalNugetSource
```

### Minimal reproduction project (MRP)

Can upload if necessary but hope I am just being stupid.

**Comment by raulsntos** [comment]
You mention that the tested version is `4.2.1-stable`. In that case I suspect .NET is just getting the package from NuGet.org because the package version will match the one we distribute. Make sure your local NuGet feed takes precedence over NuGet.org.

Alternatively, modify the [`version.py`](https://github.com/godotengine/godot/blob/4.2.1-stable/version.py) file so the package version doesn't match any of the versions available from NuGet.org, for example change the status to `dev` or `custom`.

**Comment by nbstrong** [comment]
That appears to have been the issue.

I was building in Linux cross-compiling to Windows.
I needed to add the local feed for Nuget to the Windows side, clear the cache, and then rebuild the project to make it recognize Vector3 as doubles.

My assumption was that the Nuget procedure in the build script was limited to building the engine only.

**Comment by raulsntos** [comment]
Closing as resolved.
