### ISSUE TITLE
macOS - Editor text renders incorrectly when a high-DPI display is connected

### ISSUE THREAD

**Issue by samuelfine** [godotengine/godot#90201]
### Tested versions

- Reproducible in v4.3.dev5.official [89f70e98d] 
- NOT reproducible in v4.1.2.stable.official [399c9dc39]

### System information

macOS Sonoma 14.3.1 (23D60), iPadOS 17.3.1

### Issue description

I'm running Godot v4.3.dev5.official [89f70e98d] on an M1 Mac Mini with two monitors attached (standard DPI), and the Godot Editor displays as expected. However, when I connect my iPad Pro with a high DPI display to "extend" my desktop, then relaunch Godot (on one of the monitors with a standard DPI display, not the iPad), all Editor text displays aliased like there is some sort of scaling occurring.

Editor (Godot 4.3.dev5) on a standard DPI display **without** an iPad connected:
![editor-no-ipad](https://github.com/godotengine/godot/assets/695568/7f9a9f20-e124-476d-95e3-f094fe36b0cd)

Editor (Godot 4.1.2) on the same standard DPI display **with** an iPad connected:
![editor-ipad](https://github.com/godotengine/godot/assets/695568/c17f663d-df7d-4668-bb2a-b92c54488996)

### Steps to reproduce

1. Connect a high DPI (Retina) iPad to your computer running macOS.
2. Open System Settings, go to Displays, and click the + icon dropdown to the right side.
3. Select your iPad under the "Mirror or extend to" list.
4. Launch Godot, observe text rendering issues

### Minimal reproduction project (MRP)

Any project. Tested with a brand new project.

**Comment by Calinou** [comment]
cc @bruvzg

**Comment by ajreckof** [comment]
related to #89019

**Comment by lostminds** [comment]
For reference I've been using the 4.3 dev builds on a M2 Mac with two hiDPI monitors (but no standardDPI monitors) extensively with no issues. So it might be that the issue is related to the mix of monitors with different display-scales?

In this case (and maybe #89019) it looks like the problems are related to connecting displays with a different DPI scaling compared to the main display. So perhaps it could be that some rendering/backing code is getting the resolution scale of the main screen, while some other rendering/window code is getting the resolution scale of the screen the editor window is on (or for some reason the wrong screen)? A way to test it could be to see if makes a difference what monitor you place the editor window on, and test trying to set both monitors to use the same resolution scale or switch which one is the main display.

**Comment by caimantilla** [comment]
I can confirm this behavior. Godot will always be configured for the high-DPI display, with no way to force proper display on the low-DPI one.

**Comment by Calinou** [comment]
This likely needs https://github.com/godotengine/godot/pull/86022 to be addressed. Can anyone here [test that PR locally](https://docs.godotengine.org/en/latest/contributing/workflow/testing_pull_requests.html) and see if it works on their end?

**Comment by TinyMatt** [comment]
I'm happy to report that I've just build and run the mentioned PR ( #86022 ) and it seems to be working just fine on external low-DPI monitor

I've tested it with `M1` mac and `Mobile renderer`
