### ISSUE TITLE
[idea] OS-less deploy

### ISSUE THREAD

**Issue by alexwbc** [godotengine/godot#9026]
This is not an original idea. It comes from the good 'ol '80; if you still don't know what I am talking about, take a [look at this](https://en.wikipedia.org/wiki/List_of_PC_booter_games)

Now, maybe "OSless" is not the correct definition for it; since there should be always a pack of software for kernel, services and drivers to run any game; but it gives pretty much the core idea of what's all about.

Obviously we talk about something that's already here: Linux's binaries of Godot... and the very bare needs Godot Engine needs to run. I am talking about the Kernel, X11, OpenGL, networking (for updates and stuff) and the input service (for keyboard, mouse, joypad etc)... everything else scraped away in order to have achieve the fastest "reboot PC directly in game"
no CUPS and its drivers, no server/services (that are not strictly related to the game engine/network)  like webcam support, dvb-t etc... hell, it doesn't even need to support other filesytems other than EXT4 and other /dev/sd* partitions and devices (also this is supposed to increase safety by sandboxing as much as possible).

**But on which media? 3.5 floppies?**
First, let me tell you something: inside my PC desktop there's NO internal Hard Disk. Everything I do on my Lubuntu runs from a USB3 pendrive (64GB)... and from there I can do everything... also I am able to pick up my usb drive and bring with me my "desktop experience" on virtually any other 64bit PC. From said pendrive I can run any virtualised Windows machine from 3.1 all the way up to 8 (10 untested due to personal disinterest).
With the world completely gone "mobile" internal disks are a structural obsolescence kept up by convenience: the only way Microsoft can claim "ownership" on your pc.

You can make your own Desktop Linux persistent USB3 pendrive... and boot the same experience on virtually any PC: bring on your old PC with integrated Intel HD and play at lower setting at  720p, or give it a try on your shiny new battlestation with a powerful R9 390X @4k at Ultra settings. Fully re-distributable open source drivers from AMD and Intel.
No need to reinstall, no need cloud storage to bring your save games
One simple usb key to boot your machine and seamlessly continue play anywhere lays a pc around.

**What's good for?**
...for developer: it's an easy and convenient way to quickly test your game on the bare hardware of random PC around the world. Deploy your game on a 2inch 32GB pen drive... and go around (with given permission) and try to boot your game anywhere. A friend of yours just bought a Nvidia GTX 2048Ti? Go there and boot your game; you can even go in a repair shop and (after asking kindly) test your game. If you're competent enough, you can even integrate your own hardware DRM ([with Namco style encryption](https://medium.com/@dropkickshell/system-n2-exposed-5395436c824d) ) and sell your game as physical usb keys.
...for gamers: plug key, play the game. Finish playing? Put the key in your pocket: the saved games  and the *whole thing* is physically there. No one can peek in the stuff you play/do any more. Lan party? You need to bring your rig only if **there are not** PC already there. If your Lan party already got PCs... you just need the key with (all) your Godot game(s).

**The OS "less" part:**
Well... obviously there's still a kernel and a collection of packages: technically still an OS, but keeping in mind there's almost "no operating" since it will be cut out all the features not related to the game runtime and safety. Good quality usb3 flash disk are capable to read at speed of 100MB/sec. It would take about ~7 seconds to transfer a common Ubuntu iso in the RAM: and this would include lot of unused stuff. A very bare bone reduced ARM Linux (with busybox) can [boot in ~300ms](http://www.makelinux.com/emb/fastboot/) 
[cut because it's too long otherwise]

**Comment by akien-mga** [comment]
No way, we're not OS developers. You *really* underestimate the work needed to make a Linux kernel boot, and that's very much out of our scope.

Find a project that already proposes what you have in mind, and run Godot on their platform. Not the other way around.

**Comment by nunodonato** [comment]
I dont get the benefits of this at all.

For developers: yes I want my friend with his news GTX 2048 to test my game, but in his OS with his drivers, not in my sandboxed environment which no one else will use to play it

For gamers: who is going to reboot an OS to play a game? people play games while they are doing other stuff, plus, integration with platforms like steam, teamspeak, discord, etc...

this sounds like a funny pet project, not in anyway something to be taken seriously. sorry my honest opinion :)

**Comment by LikeLakers2** [comment]
I personally see a couple benefits, though they're more for specific needs rather than general use.

1. Arcade cabinets, at least for testing purposes. You provide a simple laptop or desktop computer, hook up the controls to it (probably through USB), boot it up with the USB drive inserted and it just boots straight into your game. Though I'm sure this could be solved by testing locally on the development computer, nothing beats testing it on the hardware you're thinking you're gonna use in the end.

2. As the original poster suggested, playing it on a arbitrary computer. Maybe you're sure the hardware is good enough, maybe this is for a presentation, but you found out last time you tested that it's complaining that it can't find some DLL or SO file! Though the obvious solution would be to report this to whoever manages that computer, sometimes that would take far too long. Rebooting into an install of Linux that you know it works on would be useful here.

3. Drive imaging (or whatever the term is)? This might be a stretch, but if someone can find a way to image an internal hard drive with exactly whatever is on a flash drive, this would make setting up demo units (for AAA games) a bit less cumbersome.


This would probably be better off as an external asset/program, though. However, I can definitely see the uses for it -- there's just not a big enough use that warrants including it in Godot by default. But I'd like to see someone make it happen, because those can be selling points (even though we aren't *selling* Godot, ha).

**Comment by punto-** [comment]
Why put X11 in it? just go for OpenGL directly to the screen, or switch to
text mode console for maintenance

**Comment by punto-** [comment]
On the topic of arcade machines and booting every time you play a game,
that's what old consoles used to do, they would just more or less boot into
your game image. Since there was no virtual memory, there was no point of
adding a "multitasking" OS, everything was on your game, including the
things that look like they were coming from an OS (like the confirmation
screen for the "home" button, the "game media was removed" warning, etc).
The feature of an OS running background tasks that assist your game, like a
notification client, a "real" home menu, etc, is fairly new.

What if you run in kernel mode, no virtualization? XD

**Comment by alexwbc** [comment]
@akien-mga the use of recycled stuff it's really what I am talking about. The best candidate here is PuppyLinux and it's many derivative; that's absolutely true that attempt to build a Linux from scratch/zero ground would be insane, but if you get your hand on something *already done* and trim even down to reduce need of maintaining it begin to be doable. Also, I do agree that such work can't be undertake by with people already busy with the core: it's not convenient and even not useful since are completely different tasks; but maybe something within the community? Godot's audience it's among developers anyway!

@nunodonato 
[for developer]... and so the services, misconfiguration, and/or malaware that overload the system, the bloatware that comes with any brand shiny new PC (you made few examples on the gamers paragraph, unupdated system or some other random issues that can fake the whole testing propose. I am talking about a system tailored on the *bare-metal power* of the machine.
[for gamers] you're talking as exclusion: as having one option restrict you to use the other one.
1) plug the key > press power button > play
2) key unplugged > press power button > wait for your desktop
these two options coexist, the only thing you **can't do** is to differentiate your "wait for your desktop" experience (you need to format/reinstall)... but you can have different usb keys on your physical bookshelf (like you got DVD cases for movies and such) to switch your experience in anything you want. It's not about *exclusion* but *inclusion* of one option that has potential of many.

@LikeLakers2 
1. It depends greatly on Linux's driver quality and availability. I've used one fantasy GTX as example which show the greatest example of quality GPU driver for Linux; but I don't know how much "distributable" those proprietary driver can be, since you mention arcade cabinets: yeah, it would be cool to have two shiny new GTX1080Ti (SLi) arcade (*potentially*, on the eyecandy side, you could beat any AAA title since they are expected to run on averange of RX560/GTX1070 at best). But on the Arcade side I was thinking to something more cheap... like the UdooX86 (Intel SoC board: 89€).
You'll need the udoo board(89€)+cabinet (100~500€?) and a monitor (120€~200€?) to complete such machine and run [something like Skyrim](https://www.youtube.com/watch?v=JTzwYwzNbgU). I know Intel's igpu/soc are not the best for gaming, but in term of drivers (open source and fully distributable with Linux kernel) gives the best *bang for buck*.

3. On Linux you just a "dd" command and a /dev/sd\* target (maybe on OSX due to it's UNIX origins too?); I think that's something possible on Windows too (a tool that safetly "burn" partitions on usb flash disk), definitely there's [dd for windows](http://www.chrysocome.net/dd). What's /dev/sde for Linux is "\\.\e" (the e: drive)

@punto- 
I am not sure if you can install GPU drivers without X11.Anyway, the switch to different tty (ctrl+alt+f1) would be a natural place for a minimal UI with audio/stuff control

**Comment by akien-mga** [comment]
Won't be done by Godot developers, so I'd propose you move the discussion to a separate community location (forum/reddit post, new github repo). Let's keep issues on the godotengine/godot GitHub repository focused on... the engine.

**Comment by agameraaron** [comment]
If you want to do this, I suggest posting your idea in the forums and seeing who is on board. What you basically want to do is create your own distro focused on booting a godot project. I think I'd be down for that, but this may not be the place to do it.
