### ISSUE TITLE
Allow path auto-completion for single-quote delimited strings in the editor (for node paths and file paths)

### ISSUE THREAD

**Issue by HummusSamurai** [godotengine/godot#9056]
**Operating system or device - Godot version:**
Fedora 25 - Godot 3.0 master

**Issue description:**
Auto-Completion of path strings in the editor is limited to double quotes, which require an unnecessary trip to the Shift key. With the addition of the scalar ($) symbol as syntactic sugar, this inconvenience has become much more pronounced.

As far as I know GDScript does not distinguish between single and double quotes for strings (e.g. literals in bash and char data types in C). This is the pull request [that added single quotes](https://github.com/godotengine/godot/pull/823/files), and it seems to handle the two equally.

The discussion from [this solved issue](https://github.com/godotengine/godot/issues/468) makes me think this is just an oversight and should be at least added for consistency.

**Steps to reproduce:**
`get_node('Spatial')` works as intended, but the editor does not provide completion suggestions for the path.

**Link to minimal example project:**
n/a

**Comment by mhilbrunner** [comment]
This isn't as simple as I had hoped.

Currently the list of possible completions contains them with hardcoded double quotes.
So if you got two nodes, `node_a` and `node_b`, and type `get_node('node`, the list of possible matches is:
- `"."`
- `"a"`
- `"b"`

Now, that results in the following issues:
1. When string matching, `'something` will never match `"something` so no match is ever found
2. Using completion will always use double quotes currently, even if you used single quotes

The fix for both of those would be to generate all candidates twice, once with single, once with double quotes. That is quite ugly, however.

The saner option would probably be to remove quotes from candidates entirely, don't add them in the first place, so that the list looks like:
- `.`
- `a`
- `b`

Then we only need handling in `TextEdit::_update_completion_candidates()` to strip quotes from input before any comparison is done and remember what type of quotes was used in the input and add those to the completion result.

@akien-mga Thoughts?

**Comment by HummusSamurai** [comment]
@mhilbrunner Personally I think that's a great idea, go for it!

It seems efficient and It'll be hard to think of anythng better.

**Comment by akien-mga** [comment]
Go for the sane option, we don't need the quotes in the candidates.

**Comment by mhilbrunner** [comment]
Okay, I missed that you actually need the quotes:
1. If not using `$` but e.g. completing `get_node(`, you want it completed to `get_node("something"`, not `get_node(something`
2. Node names can contain spaces

So I found some middle ground, which makes this as easy as it should have been... didn't know why I didn't think of this at first:

1. Everything remains as it is, candidates still are quoted (those quotes are removed for $ automatically if possible already)
2. If the input contains single quotes, double quoted candidates are instead output with single quotes instead

Simple, clean. :) Will send a PR.

**Comment by mhilbrunner** [comment]
Demo:
![Autocomplete](https://i.imgur.com/tzPxpGi.gif)

**Comment by HummusSamurai** [comment]
YES
