### ISSUE TITLE
In C#, Randfn() deals with doubles instead of floats, contrary to documentation and other RNG functions

### ISSUE THREAD

**Issue by Grix** [godotengine/godot#90628]
### Tested versions

v4.2.stable.mono.official [46dc27791]

### System information

Godot v4.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.5161) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

Just noticed this minor discrepancy. [Documentation for GD.Randfn()](https://docs.godotengine.org/en/stable/classes/class_randomnumbergenerator.html#class-randomnumbergenerator-method-randfn) described the function as **float Randfn(float mean, float deviation)**. This is also true for intellisense documentation, and it matches the float use of Randf().

But in practice, it is incorrect. Both the return value and the two parameters for this function are actually doubles, not floats. Either the function, or the documentation, should be corrected. 

If the internal function deals with floats then maybe there is a slight performance gain from fixing the function rather than the documentation to avoid a cast, but maybe this would also cause too many issues by breaking compatibility. 

**EDIT after comment**: It seems double is the intended type, but then the discrepancy is actually in Randf() instead, which does return a float and not a double like Randfn() does.

### Steps to reproduce

Call GD.Randfn() and verify with the debugger or other means that the return value is double and that the parameters are doubles. 

### Minimal reproduction project (MRP)

![devenv_d4oAb8wIG2](https://github.com/godotengine/godot/assets/1517713/b14073d7-14e9-4835-942e-f5d83b13e3ec)

No MRP because it is trivial, but here is a screenshot of the actual function signature as VS sees it.

**Comment by AThousandShips** [comment]
`float` in GDScript is `double`, this is documented in a number of places, this is standard (in fact it should have been clarified if it *didn't* use 64 bits)

**Comment by Grix** [comment]
> `float` in GDScript is `double`, this is documented in a number of places, this is standard (in fact it should have been clarified if it _didn't_ use 64 bits)

I see, but then why do the Randf() function actually still return a float and not a double? Something isn't very consistent.

**Comment by AThousandShips** [comment]
I don't know, the GDScript one doesn't, so might be an error in the C# code

**Comment by raulsntos** [comment]
No, the C# method `Randf` is correct, it's exposing `Math::randf` which returns `float`:

https://github.com/godotengine/godot/blob/c69851b89983aee288c575d1242604ee80cf33de/modules/mono/glue/runtime_interop.cpp#L1253-L1255

https://github.com/godotengine/godot/blob/c69851b89983aee288c575d1242604ee80cf33de/core/math/math_funcs.h#L553

I don't know if this is the same method that GDScript uses, but I don't think changing it now is worth breaking compatibility.

What @AThousandShips said about GDScript `float` being 64-bit is correct though, it's just that if the method is defined with 32-bit types then some metadata is added so languages like C# can use the _correct_ type. `Randfn` is exposing `Math::randfn` which uses `double`:

https://github.com/godotengine/godot/blob/c69851b89983aee288c575d1242604ee80cf33de/core/math/math_funcs.h#L554

And just to be clear, the class reference in the documentation will always say `float` because that's the name of the type and the _bitness_ is just metadata.

**Comment by Grix** [comment]
@raulsntos 
Thanks for the info. So since it seems intended (or even if it wasn't intended it probably shouldn't be changed) then I will close this issue if no one objects. Or at least edit the whole title and description so that the only thing still being pointed out is how Math::randfn and Math::randf for some reason have different bitness.
