### ISSUE TITLE
The computation of NoiseTexture2D blocking the main thread

### ISSUE THREAD

**Issue by RitualVacant** [godotengine/godot#90661]
### Tested versions

v4.2.1.stable.mono.official [b09f793f5]

### System information

Godot v4.2.1.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5123) - 12th Gen Intel(R) Core(TM) i7-12700 (20 Threads)

## 
I found in my C# project that when I change the noise in NoiseTexture2D it causes the game screen to freeze for a few seconds. But I noticed in the official documentation that NoiseTexture2D uses Threads to generate the texture data internally, which as I understand it doesn't block the main thread when calculating the texture. I wait until NoiseTexture2D emit signal Changed before applying NoiseTexutre2D to the game screen.
## 
I tried to check the godot source code, I changed the code in the function _update_texture in line 198 of noise_texture_2d.cpp, 
### before
```cpp
void NoiseTexture2D::_update_texture() {
	bool use_thread = true;
	if (first_time) {
		use_thread = false;
		first_time = false;
	}
	if (use_thread) {
		if (!noise_thread.is_started()) {
			noise_thread.start(_thread_function, this);
			regen_queued = false;
		} else {
			regen_queued = true;
		}

	} else {
		Ref<Image> new_image = _generate_texture();
		_set_texture_image(new_image);
	}
	update_queued = false;
}
```
### after:
```cpp
void NoiseTexture2D::_update_texture() {
	bool use_thread = true;
	if (first_time) {
		// use_thread = false;
		first_time = false;
	} else {
		use_thread = false;
	}

	if (use_thread) {
		if (!noise_thread.is_started()) {
			noise_thread.start(_thread_function, this);
			regen_queued = false;
		} else {
			regen_queued = true;
		}

	} else {
		Ref<Image> new_image = _generate_texture();
		_set_texture_image(new_image);
	}
	update_queued = false;
}
```
shouldn't a new thread be used to compute the texture when it's the first time. And after compiling it and running my C# project, then the game doesn't lag anymore, Is this a problem with my code or understanding, or is it a bug in the engine, thank you very much for your answers. I tried to reproduce the problem I had in my C# project with GDScript.

### Steps to reproduce

run and click set material buttom, game will freeze.

### Minimal reproduction project (MRP)

[Issues.zip](https://github.com/godotengine/godot/files/14970563/Issues.zip)

**Comment by huwpascoe** [comment]
It's not a bug, it's by design.

If threading is to truly enabled from the first frame, the texture still needs to be created even if the data isn't ready. What should the texture's initial data be if the noise is still calculating? Solid black? Undefined?

**Comment by clayjohn** [comment]
Further to huwpascoe's point, I think it is important to think about different ways that NoiseTexture2D is used and how we can cater to different uses. Most users will assign the texture to a material, edit it in the editor, and then load it at runtime. Once it is loaded, they may tweak the texture, in which case it should update on the background because it can be slow. 

Importantly though, when the object that uses the texture appears, they will want the texture to be ready. 

This differs from your use-case which appears to be generating textures at run time. When you create the NoiseTexture2D in script, then it makes a lot more sense to wait for the texture to be updated in the background before actually putting it into the scene. 

For now, the easy workaround will be for you to create as many noise textures you need at load time and then update them in the background when needed.

**Comment by RitualVacant** [comment]
Thank you very much for your answers!
