### ISSUE TITLE
Translations GetText - Fallback from language with country code to language without a country code not working

### ISSUE THREAD

**Issue by AlixBarreaux** [godotengine/godot#90677]
### Tested versions

**Reproducible in:**
Godot Engine v4.2.1.stable.official.b09f793f5
Godot Engine v4.1.3.stable.official.f06b6836a

### System information

Godot v4.2.1.stable - Debian GNU/Linux 12 (bookworm) 12 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 6GB (nvidia) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

### Issue description

When setting a **locale** `fr` with a **country code** `CH` this locale + country code combination `fr_CH` in the TranslationServer works if the .mo file for `fr_CH` is present.

However if it's not present but the .mo files for `fr_CA` **AND** `fr` (_without_ a country code) are present it will fall back to `fr_CA` or whatever `fr_` + a country code.
This is not  what I expect.

I  expect the locale + country code `fr_CH` (`CH` in this case but it can be  any country code) to fall back to the same locale without any country code appended to it, just `fr`
If the .mo file for `fr` is not found then it should take the first .mo file for `fr` + whatever country code.
If none is found it should fall back to the fallback set in project settings. (locale + country code) 

### Steps to reproduce

Create a label scene, set its text in English in the editor.
Attach a script to it and in the `_ready()` function put this in: `print("Locale used: ", TranslationServer.get_locale())`
Go in Project Settings and toggle advanced settings.
Then:
Project Settings  -> Localization -> POT Generation -> Generate POT

Outside of Godot with Poedit (or whatever you want) create the getText translation files for:
French, French (Belgium), French (Canadian) .
In the newly opened window, fill in the text value with something related to the file to distinguish which specific language you are using when running the game later on.
Save it.

Project Settings -> Localization -> Translations -> Add -> Add your .mo files you just created.
Project Settings -> Internationalization -> Locale -> test -> This field should be empty by default.
Launch the label scene.
The text in the label should be your English text you have initially set in the editor and the print statement says: `Language used: en_US`
Project Settings -> Internationalization -> Locale -> test -> set it to `fr_CH` (You should NOT have created the getText files for _French (Switzerland)_, it must not be imported into the project)
The text in the label is the value from the **French Canadian** (fr_CA) .mo file, instead of the expected one which is French **French Switzerland** (fr_CH) and the print statement says: `Language used: fr_CH`

### Minimal reproduction project (MRP)

[language-fallback.zip](https://github.com/godotengine/godot/files/14972565/language-fallback.zip)

**Comment by dbnicholson** [comment]
I'm pretty sure this is a regression from 945645410905e8b23228965e29c2be274cb12645, which made a subtle [change](https://github.com/godotengine/godot/commit/945645410905e8b23228965e29c2be274cb12645#diff-985565fb1f983acb2d87dbe8931c929d0f46fdecb1d99a31e495b151c0f52186R380) from `score > best_score` to `score >= best_score`. Since the list of locales tested has the country-less locale first, a locale with a country that follows will become the used locale because they have the same `score` of 1.

You can test this in the editor without providing any translations since it also affects `es` vs `es_AR` and `pt` vs `pt_BR`, which are all provided by the editor. For example, if you run the editor with the locale `es_ES`, it will pick `es_AR` since that gets tested after `es`. IMO, the country-less `es` locale is a better fit than `es_AR`. Here's a simple editor script I used on Linux to test with various `LANG` environment variable settings, which sets the OS locale:

```
@tool
extends EditorScript

func _run():
	var lang = OS.get_locale()
	var locale = TranslationServer.get_locale()
	var tool_locale = TranslationServer.get_tool_locale()
	print("OS locale: %s" % lang)
	print("locale: %s" % locale)
	print("tool locale: %s" % tool_locale)
```

Here's the output for unaltered 4.4-dev3 with `LANG=es_ES.utf-8` on Linux:

```
OS locale: es_ES
locale: es_AR
tool locale: es_AR
```

Now I make the following change to godot master:

```
diff --git a/editor/editor_settings.cpp b/editor/editor_settings.cpp
index 12a7c3a2ff..2cef463672 100644
--- a/editor/editor_settings.cpp
+++ b/editor/editor_settings.cpp
@@ -398,7 +398,7 @@ void EditorSettings::_load_defaults(Ref<ConfigFile> p_extra_config) {
                        lang_hint += locale;
 
                        int score = TranslationServer::get_singleton()->compare_locales(host_lang, locale);
-                       if (score > 0 && score >= best_score) {
+                       if (score > 0 && score > best_score) {
                                best = locale;
                                best_score = score;
                        }
```

Here's the test again with the above change:

```
OS locale: es_ES
locale: es
tool locale: es
```

**Comment by dbnicholson** [comment]
It's pretty fragile to depend on the order of the locales, so it would probably be better if `TranslationServer::compare_locales` was improved so that a country-less locale had a higher score than a locale with a mismatched country. This all happens [here](https://github.com/godotengine/godot/blob/c6c464cf9ae56e8b68620af65125dd980d0e8122/core/string/translation_server.cpp#L254).

I'm not really sure the best way to handle it. Perhaps what you'd do is set a bare language match score to 5. For additional elements that match, increase the score with a bound at 9 since 10 represents an exact match. For additional elements that don't match, reduce the score with a bound at 1 since 0 represents no language match.
