### ISSUE TITLE
GridMap always visible even when set not visible

### ISSUE THREAD

**Issue by SuperUserNameMan** [godotengine/godot#907]
hi again again,
Still using the November 13 version, windows 64.
GridMaps seems not to respond the Visibility parameter, neitheir into the editor nor when the scene is played.
They remain always visible, even when the parent node is set to invisible.

**Comment by akien-mga** [comment]
Hi, is this issue still valid in 1.1 or in the current master branch?

**Comment by neikeq** [comment]
I just tested in the current master branch. It seems to be still valid (both in editor and game). You can check it with the _Platformer 3D_ demo (_stage.xml_ scene).

**Comment by zoiba** [comment]
This bug is still here in 2.0 beta. The ability of hiding Gridmaps is quite important when building large levels.

**Comment by akien-mga** [comment]
Setting "by default" to the 2.1 milestone, but if reduz or someone else wants to try to fix it for 2.0, it can of course be re-prioritized.

**Comment by akien-mga** [comment]
Not critical for the upcoming 2.1, so moving to the next milestone.

**Comment by HummusSamurai** [comment]
Wow this is old.

**Comment by reduz** [comment]
\o/

On Sep 6, 2017 6:49 AM, "Rémi Verschelde" <notifications@github.com> wrote:

Closed #907 <https://github.com/godotengine/godot/issues/907> via f43a0ef
<https://github.com/godotengine/godot/commit/f43a0ef3270737d2b526480ecb0f1337ece9e041>
.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/907#event-1236492590>, or mute
the thread

**Comment by jamesdkay** [comment]
A probably related bug remains: although GridMaps can now be made visible or hidden, they do not become hidden when you hide their parent.

**Comment by TheUltimateAbsol** [comment]
If you bake a lightmap in 3.2.3, this issue will pop up again
