### ISSUE TITLE
AnimationPlaybackTracks no longer functioning as intended

### ISSUE THREAD

**Issue by antourenein** [godotengine/godot#90864]
### Tested versions

- Reproducible on 4.3.dev.gh [2efbc6bfb]
- Reproducible on 4.2.2-rc3 and 4.2.2-stable
- Not reproducible on 4.2.2-rc2 and before
### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 31.0.15.5186) - 12th Gen Intel(R) Core(TM) i7-12700H (20 Threads)

### Issue description

While in-editor seeking of AnimationPlaybackTracks now works as it should, actually playing the animation that uses an AnimationPlaybackTrack no longer plays the referenced animation properly. It also does not seem to work when running the project with this animation setup.

https://github.com/godotengine/godot/assets/79013106/0cb57735-d74a-4169-8af8-8e3e84cce395

### Steps to reproduce

1. Create an AnimationPlayer
2. Create any animation
3. Create another AnimationPlayer
4. Insert AnimationPlaybackTrack and reference the animation in step 2

### Minimal reproduction project (MRP)

This is project in the video, it has the steps above already done.

[AnimPlaybackTrackBug.zip](https://github.com/godotengine/godot/files/15028056/AnimPlaybackTrackBug.zip)

**Comment by sketchyfun** [comment]
The problem seems to be in scene/animation/animation_mixer.cpp at line 1611

 `a->track_get_key_indices_in_range(i, time, delta, &to_play, looped_flag)`
 
 doesn't seem to return anything if the clip lands at 0 seconds on the timeline. I don't really have time to dig any deeper, but hopefully that give someone a starting point

**Comment by TokageItLab** [comment]
> The problem seems to be in scene/animation/animation_mixer.cpp at line 1611

It is not related since immediately after playback it never goes through line 1661.

This is actually due to some missing processing that should be taken into account for the internal seek (meaning immediately after playback). I have sent https://github.com/godotengine/godot/pull/90960 to fix that, so please check it if possible.
