### ISSUE TITLE
Shaders do not automatically inherit the default texture filter types from project settings, nor do they import image texture settings.

### ISSUE THREAD

**Issue by AlonJu** [godotengine/godot#91105]
### Tested versions

done in "v4.0.stable.official [92bee43ad]"

### System information

Windows 8.1 64 bit, Compatiblity Renderer

### Issue description

Textures used by shaders don't seem to inherit the settings set by the import and project settings. It seems that it is compressing the palette texture internally whenever it is sampled. Is it fixed in later versions of godot?
![photo_2024-04-24_05-17-47](https://github.com/godotengine/godot/assets/49595151/0ec048d0-c032-4ada-ae2c-06c2c1db2105)
![photo_2024-04-24_05-16-27](https://github.com/godotengine/godot/assets/49595151/0ee7d44c-e95d-49b6-b8b9-98646cf97bd9)

Ihttps://files.catbox.moe/w7rpp4.png

https://files.catbox.moe/iu6c4n.png

### Steps to reproduce

import a texture, change the texture settings, and try to use it in the shader. Removing the "filter_neareast" hint is what changes the settings to is default

### Minimal reproduction project (MRP)

https://files.catbox.moe/x6cwbs.zip
```[tasklist]
### Tasks
```

**Comment by clayjohn** [comment]
The project settings only create a default for CanvasItem textures, not for custom shaders. For custom shaders you always  have to specify the filter and repeat settings that you want. 

That being said, this particular bug was actually fixed a long time ago (in 4.0.1) Upgrading to any other version of Godot 4 will make the issue go away! In general we recommend users not stick to Godot 4.0-stable as it has many bugs that have long since been solved. I recommend using 4.2.2 if you can, or 4.04 if you prefer to stick to to the 4.0 major release.
