### ISSUE TITLE
Sprite Flicker in Animation Tree

### ISSUE THREAD

**Issue by forager-pixel** [godotengine/godot#91115]
### Tested versions

Reproducible in 4.3.dev5.official [89f70e98d], and 4.2.1.stable.official [b09f793f5]

### System information

Godot v4.3.dev5 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1070 (NVIDIA; 31.0.15.3699) - AMD Ryzen 5 5600X 6-Core Processor (12 Threads)

### Issue description

In my scene, I have a frog that transitions from idle to jump. Both states utilize an animation tree with a state machine as the tree root. When each state is entered, the code travels to the corresponding state in the animation tree. For some reason in the middle of the jump animation the sprite flickers. If I solely use the animation player I don't have issues with the sprite changing. In 4.3.dev5, it is a very quick flicker to the idle sprite frames. It is **not visible in the recording**, but I definitely see it from the debug window.

https://github.com/godotengine/godot/assets/99606581/616b7c48-eb2f-4951-8b0f-8115edd1132e

 In 4.2.1.stable, the sprite changes to the idle frames for a longer duration and is visible in recording:

https://github.com/godotengine/godot/assets/99606581/e842029d-04b7-44c7-9b3c-ac711cbe60ba

### Steps to reproduce

Open SpriteFlickerAnimationTree project, press play from the editor. Hit spacebar to make the character jump. It'll enter the jump state which then should show a visible flickering between sprites.

### Minimal reproduction project (MRP)

[SpriteFlickerAnimationTree.zip](https://github.com/godotengine/godot/files/15097141/SpriteFlickerAnimationTree.zip)

**Comment by TokageItLab** [comment]
The problem is caused by the multiple application of an AnimationPlayer after the AnimationTree; deactivating the second AnimationPlayer does not cause the problem.

![image](https://github.com/godotengine/godot/assets/61938263/79c48248-a189-4e03-8e20-4bdb5f2bdea0)

The change in behavior in 4.3.dev is due to a change in the handling of UpdateMode.Discrete.

Discrete in 4.2 means that CallbackModeDiscrete in 4.3 is Dominant.
The default in 4.3 is ForceContinuous, which is suitable for blending; This means that during blending, Discrete/int is treated as Contiunous/float, and after blending, the values are rounded back to int.

If you want the same behavior as in 4.2 with proper behavior, deactivate the second AnimationPlayer and set CallbackModeDiscrete to Dominant.

![image](https://github.com/godotengine/godot/assets/61938263/e2be037c-9681-4565-9103-ad9d995bc44e)

**Comment by forager-pixel** [comment]
But, the issue is that what I see in Godot 4.2 isn't what should be happening either. If I am in the jump state and I've designated a single set of sprites, without crossfade or a blend node, why does blending matter? I am just genuinely confused as to how this process works. It switches back to the idle frames before the character is grounded, which it shouldn't.

**Comment by TokageItLab** [comment]
So we added the ForceContinuous option in Godot 4.3 and made it the default so that anyone don't face the same problems you encountered in 4.2. If that is more ideal for you, just use ForceContinuous. Many users are not aware of the difference between Continuous + Nearest + int and Discrete + int.

What is happening in 4.2 is due to the behavior of the Discrete track: if it has a weight of even 0.01 when blended, it is applied with a weight of 1.0. This would be appropriate for keys like replacing resources, etc., but inappropriate for changing int values in many cases.

**Comment by forager-pixel** [comment]
But can you help me understand - to blend requires 2 values.. if I have a state with only 1 value for the sprite, what exactly could it be blending between? I'd expect no blending to occur, discrete or not, when I have a track that isn't targetting the same property across two separate tracks. Yet, I get this (with the animation player disabled, and force continuous because that is the only one that gets approximately close to what I actually intended):  

https://github.com/godotengine/godot/assets/99606581/2f6df58d-ca3a-4373-85b9-571590fc6f03

**Comment by TokageItLab** [comment]
I am not sure about what you are saying and the desired behavior, but I expect it probably has to do with the Deterministic option. If you want the AnimationTree to transition in the same state as the AnimationPlayer, just set the Deterministic option to false.

![image](https://github.com/godotengine/godot/assets/61938263/3a978693-2098-4426-bd49-404b05380dfe)

**Comment by forager-pixel** [comment]
What I see with deterministic set to false:

https://github.com/godotengine/godot/assets/99606581/c1559462-2060-4016-8f0e-a69e14a7078c

**Comment by TokageItLab** [comment]
> The problem is caused by the duplicated application of an AnimationPlayer after the AnimationTree; deactivating the AnimationPlayer does not cause the problem.

**Comment by forager-pixel** [comment]
What do you mean by duplicated application of the animation player?

**Comment by forager-pixel** [comment]
It is deactivated though..

https://github.com/godotengine/godot/assets/99606581/bf13fe97-231e-477f-9201-43ec0e2ea30e

**Comment by forager-pixel** [comment]
If I'm not making sense, then I suppose we can just put this to rest. But I really don't understand the underlying mechanism for blending it to the idle sprites. By the time I'm in the jump state, there should be no keys whatsoever pointing to the idle sprites. It's a single animation with 1 set of sprites. What I expect regardless of continuous or discrete, is that it switches to the jump sprites, and while it's in that state, since I didn't specify any other sprites, it should keep those sprites. Why would tracks from the idle animation still have any weight if they exist in an entirely different state? In my use case all I want from the animation tree is to mix animations that do not intersect in properties. The blending, while useful in some scenarios, is far less important to me. It seems I'd have a better chance using two animation players than the tree.

If you take one last look at this I'll provide my more convoluted project where I'm actually recording the past few videos:
[SpriteFlickerMoreComplicated.zip](https://github.com/godotengine/godot/files/15111794/SpriteFlickerMoreComplicated.zip)

**Comment by TokageItLab** [comment]
Looking more closely, it seems that the problem is that the Jump state is a nested StateMachine in Root mode, and since Start and End have no state, the reset animation is applied by the Transition's Reset to End.

![image](https://github.com/godotengine/godot/assets/61938263/3e78558b-0aac-4c0a-ab0a-008f7d877b9a)

There are three solutions to this:

1. Use Root with Disable Reset in Transition to End
![image](https://github.com/godotengine/godot/assets/61938263/f74f5bbf-8678-4dfa-baa0-8cee94013bb5)

2. Use Grouped
![image](https://github.com/godotengine/godot/assets/61938263/0b97ff42-7ab9-4c7e-8c61-143f063a3e28)

**Comment by forager-pixel** [comment]
I can see there's much I need to learn. But, I'm still having no luck with the three options.
Here's my attempts for all of them:

https://github.com/godotengine/godot/assets/99606581/62ba43b5-b864-49ba-8645-d646175c4193


https://github.com/godotengine/godot/assets/99606581/09b58c26-6648-472f-b38f-614cff8a2415


https://github.com/godotengine/godot/assets/99606581/db9c4943-fa17-4886-8e59-471f55f87253

**Comment by TokageItLab** [comment]
If the above information does not fix the problem, one possibility is that the state transition is being performed in an incorrect manner.

Just looking at the code for a moment, it may be that during a Jump, it is trying to preserve the Jump state by transitioning to a non-jump state in one frame and then immediately returning to the Jump state.

**Comment by forager-pixel** [comment]
Alright, quickly coming back to this. I think your initial assumption was right. It looks like the animation player is becoming active when I run the scene. But, it is inactive in the editor. So, it's a separate issue, but I dont have anything in the code that makes the player active.. :/ 

https://github.com/godotengine/godot/assets/99606581/b41b8c90-30fc-41bf-b6a6-8d2f3861709a

**Comment by forager-pixel** [comment]
Will do. Thanks for your time today.

**Comment by LeeWannacott** [comment]
@TokageItLab I got sprite flicker with `Deterministic` set to Off. Where as it goes away when it is set to `On`.  Which is fine apart from Deterministic set to off is the default? I'm using AnimationPlayer not AnimationTree although they both inherit from AnimationMixer anyway...

It doesn't seem to be an issue with 3D characters, where blending is fine, but 2D that use spritesheets it has severe flickers now. Is it possible you picked the wrong default? (Godot 4.3 beta 1).

**Comment by TokageItLab** [comment]
@LeeWannacott What I want you to know is that AnimationTree has had a number of issues raised about unintended resets in animation transitions in StateMachine when it adopted Deterministic in 4.0.

I believe that now that Deterministic is an option, those problems are gone, but the option is still unknown to many users, and I expect that if AnimationPlayer suddenly makes Deterministic the default, it will cause similar confusion and a lot of issues will be raised. So I don't think this default will change during 4.x.

If necessary, we may consider setting the default in the project settings if there are other Classes that do the same thing (selecting default by project setting).

**Comment by LeeWannacott** [comment]
@TokageItLab Okay not the end of the world; I guess no matter what option you take someone will have issues, I'll just change it on my AnimationPlayers that are for 2D (I'm not using AnimationTrees.)
