### ISSUE TITLE
Sliding off Edges When Modifying Collisions

### ISSUE THREAD

**Issue by Roblouisck** [godotengine/godot#91272]
### Tested versions
v4.2.2.stable.official [15073afe3]

### Issue description
Hey, I'm making a 3d jump game and having an issue solving this. I've tried using 2 collisions and disabing 1, changing them to rectangles instead of capsules, and several other things such as using raycasts pointing down and disabling gravity near the edge.

I  haven't seen ANY working fps controller online that handles *crouch jumping* without this slipping issue. Anyone have ideas on how I can fix this so that players can both reach higher ledges when crouch jumping, but not be subject to slipping down when they release crouch?

Note: This only happens when crouching jumping. When doing a normal crouch and releasing the player never slides off the edge. This has to do with changing and resetting the collision size & y position of the player in the animation, both of which cause a slide when reset near an edge.

Example of why it's a problem in my game:
https://www.youtube.com/watch?v=2z0M4nyLzWU

Showing the animations:
https://www.youtube.com/watch?v=wiZpAYfJF5I

### Steps to reproduce
Download any fps controller that has crouch jumping or check my zip to see my code.

### Minimal reproduction project (MRP)

[jump_king_MRP.zip](https://github.com/godotengine/godot/files/15140901/jump_king_MRP.zip)

**Comment by yosoyfreeman** [comment]
Hi! Your animations are constantly changing the relative position of the feet in relation with the player. Specifically, your character is extending down when it uncrouches, forcing the body to be resolved against the border of the wall. 

I don't see anything wrong in here and i can confirm that this is not a problem if the collision shape remains in an expected position (Which is usually with the button part at the origin)

**Comment by Roblouisck** [comment]
@yosoyfreeman Hey! Thanks for the response. I need to change the y position of the collider to allow players to clear more air when crouch jumping than than when simply jumping.

If the same y position is kept for the collider for both air_crouch and air_crouch_reset then there won't be a difference between a normal jump and a crouch jump in terms of air cleared.

If the y position of the collision can't be moved at all, we also can't change the collision shape on the y axis either because it shrinks and expands in both directions, which also causes clipping and slipping. 

Is there another way to implement this that I'm missing? I tried using 2 collisions (feet and standing) but it had the same issue.

**Comment by yosoyfreeman** [comment]
Hi! I'm sorry i didn't explained properly. The Y position change should be done by moving the whole character by the same amount it crouched this frame, so what is kept in position is the whole player, not the collision shape.

**Comment by yosoyfreeman** [comment]
You can check my source style character controller in here, which includes this in this file: https://codeberg.org/YoSoyFreeman/LiblastCharacterController/src/branch/main/character_components/scenes/crouch_character_component.gd

**Comment by Roblouisck** [comment]
Thank you for the clarification, I will try that tomorrow and get back to you. 

I tried to open your code but seems the test_scenes folder is missing (Cannot open file 'res://test_scenes/test_scene_1/test_scene_1.tscn'.). 

Do you have a working demo I can try?  Would love to test what you have tomorrow when I look at the code.

**Comment by Roblouisck** [comment]
Are these bugs still present in the code or were you able to solve these? I ran into the same issues.

```
#BUG: IF you are crouch, jumo, and uncrouch just before touching the floor you get stuck crouched.
#BUG: Add safe margin to the crouch check. start by checking a little up, then compensate casting a little less.
#BUG: Now character gets stuck under stuff...
```

**Comment by yosoyfreeman** [comment]
That code is part of the Character system i made for liblast, but i had to pause all the development because move and slide was just unable to work reliably. I spend this months working on a full new character system and movement algorithm implementation that i have working most of the time but the godot physics api (regardless of the physics engine used) is just not enough to create the kind of movement you would see in source or unreal, so after quite a lot of time of mashing my head i had to stop it. The project was meant to provide a more modern approach to character controllers in godot, including crouching and uncrounching both grounded and on air, proper collision resolution etc.

So i fear i can not provide you with the final version, as i don't think that with the tools godot provide it can be achieved in a solid way. 

If it helps you, the fix for the problem you said its already implemented in that file.

If you see, it will check if it would collide with the floor after extending, if that is the case, we first snapping to the floor and then do a check up instead, to see if we can uncrouch. If not, the character remains crouched. That fixes it.

I hope that helps. There is definetly a lot of problems right now, but this is doable, it is just complex by the nature of manipulating the space a kinematic body occupies, you have to put a lot of safeguards that can not be evident at first glance.

But for the sake of keeping the repo organized and clean, i can say that this is not indeed a bug.
