### ISSUE TITLE
Particles which only have a velocity but no acceleration don't collide properly 

### ISSUE THREAD

**Issue by derkork** [godotengine/godot#91346]
### Tested versions

v4.2.2.stable.mono.official [15073afe3]

### System information

Godot v4.2.2.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 31.0.15.5222) - AMD Ryzen 9 7950X3D 16-Core Processor (32 Threads)

### Issue description

When a particle system has no set acceleration then the collision does not work unless particle speeds are high. See this video:

https://github.com/godotengine/godot/assets/327257/fc2a90f9-32ba-46cc-9e88-5bb2279ff6d7

The left particle system has no initial velocity and only set gravity to -5. The right particle system has an initial velocity of 3.  In both particle systems the particles have visually similar speeds, yet their collision behaviour is totally different. With a velocity of 3 the particles will just stick on the surface. Only if I increase the velocity the particles will actually behave similarly to the particle system with acceleration.

### Steps to reproduce

Check the `particles.tscn` in the attached example project. Both particle systems are set up exactly the same, except that the left one uses acceleration while the right one uses velocity.

### Minimal reproduction project (MRP)

[collision_reproducer.zip](https://github.com/godotengine/godot/files/15159121/collision_reproducer.zip)

**Comment by derkork** [comment]
Here is another example. Note how the particles collide with the box when I use radial acceleration, but go right through the box when I use radial velocity.


https://github.com/godotengine/godot/assets/327257/711f119d-6632-47a4-8070-1ae86bede66c

**Comment by Aman-Anas** [comment]
I believe this is normal behavior - In the first example, the velocity emitter had Gravity set to 0, and a negative initial velocity: So when a particle collides with the box, it gets deflected - but there's no continuous force pushing it down the sides. Enabling gravity allows it to slide down the sides of the box as usual.

In the second example, it seems to be caused by setting a positive animated velocity - as the particle reaches the box, the collision should impart a 'reverse force' and prevent it from going through (and should set velocity to 0ish), but the animated minimum velocity forces the particle to keep moving through the box.  Animating directional velocity using the directional velocity curve also causes this issue.

I think for good collisions you need to be using the "velocity limit" curve to allow the particles to be stopped by collisions while still limiting its maximum velocity.

**Comment by clayjohn** [comment]
The root of this issue is the same as https://github.com/godotengine/godot/issues/87221

We currently have a part of the particle shader that removes the velocity of the particle if the length of the velocity is less than 3 and it collides with a surface. https://github.com/godotengine/godot/pull/87320 removes that section of code which will fix this issue as a result
