### ISSUE TITLE
"ERROR: EditorSettings not instantiated yet." when running `--doctool` or `--generate-mono-glue`

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#91510]
### Tested versions

- Reproducible in 4.3.dev (03e6fbb010c3546593bd91a0dabc045a9882705a)
- Reproducible in 4.3.dev5
- Not reproducible in 4.3.dev4 or earlier, including 4.2.2.stable

### System information

Fedora Linux 40 (KDE Plasma) - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 7600M XT (RADV NAVI33) () - AMD Ryzen 7 7840HS w/ Radeon 780M Graphics (16 Threads)

### Issue description

When running `--doctool` or `--generate-mono-glue` (and possibly other command line tools), these errors are printed:
```
ERROR: EditorSettings not instantiated yet.
   at: ED_SHORTCUT_OVERRIDE_ARRAY (./editor/editor_settings.cpp:1658)
ERROR: EditorSettings not instantiated yet.
   at: ED_SHORTCUT_OVERRIDE_ARRAY (./editor/editor_settings.cpp:1658)
```

### Steps to reproduce

- `godot --doctool`

### Minimal reproduction project (MRP)

n/a

**Comment by AThousandShips** [comment]
I suspect this is caused by the dummy instantiation of some class that declares a shortcut in its constructor, but the singleton isn't assigned when not creating it properly

We could just assign the singleton when creating the dummy editor settings in the documentation generation, and dotnet generation, but will try see if I can find what class is documented and also uses shortcuts

**Comment by AThousandShips** [comment]
Found it, will make a fix
