### ISSUE TITLE
Visual lag with UWP

### ISSUE THREAD

**Issue by nunodonato** [godotengine/godot#9168]
**Operating system or device - Godot version:** Windows. Tested with both Godot 2.2 and 2.1.3(git)

**Issue description:**
There is a small delay between input and what is shown on the screen. It seems like the render is lagging behind (0.5sec maybe).
I know its not related with input because I can hear the sound fx when a key is pressed right away, it is the image that is delayed.

Tested with ANGLE and Godot in release mode for x64.

**Comment by nunodonato** [comment]
@vnen  I managed to solve this by using the ANGLE dlls via NuGet Packager, instead of the ones built as described in the docs. There is no more lag.

**Comment by nunodonato** [comment]
tested with 2.1.4 export template, huge lag on the xbox

**Comment by nunodonato** [comment]
just a short update, I'm testing things again with the latest beta of 2.1.4
on my system and with my game(didnt test others) the lag remains, except if I use the ANGLE dll's provided via the NuGet Packager

**Comment by vnen** [comment]
This is quite odd. The NuGet ANGLE is built from the Microsoft fork, the same one I linked on the docs. I have no idea what could be different.

**Comment by nunodonato** [comment]
I tested the dlls in the official export template, just to make sure it was not my build's problem. The lag was still there. Yes, it's odd indeed :/

**Comment by akien-mga** [comment]
Maybe NuGet's binaries are better optimized?

**Comment by akien-mga** [comment]
We have now entered release freeze for Godot 3.0 and want to focus only on release critical issues for that milestone. Therefore, we're moving this issue to the 3.1 milestone, though a fix may be made available for a 3.0.x maintenance release after it has been tested in the master branch during 3.1 development. If you consider that this issue is critical enough to warrant blocking the 3.0 release until fixed, please comment so that we can assess it more in-depth.

**Comment by nunodonato** [comment]
@akien-mga please note this was reported in the 2.x branch. I dont know if its valid in v3

**Comment by vnen** [comment]
For 3.0 I'm still struggling to make 3D work. When (if) I manage to do it, this should be tested again. But for now let's keep it only for 2.1.

**Comment by akien-mga** [comment]
The 2.1 branch is no longer actively worked on by engine developers, unless critical fixes are needed for current games in production. As such we are now closing non-critical bug reports affecting only the 2.1 branch.

Please comment if this was incorrectly triaged and is still relevant in 3.x versions.

**Comment by mediaexplorer74** [comment]
> **Operating system or device - Godot version:** Windows. Tested with both Godot 2.2 and 2.1.3(git)
> 
> **Issue description:** There is a small delay between input and what is shown on the screen. It seems like the render is lagging behind (0.5sec maybe). I know its not related with input because I can hear the sound fx when a key is pressed right away, it is the image that is delayed.
> 
> Tested with ANGLE and Godot in release mode for x64.

Hello,
can you provide to me some simple sample of Godot name created with C#, UWP and MS Angle?

**Comment by panreyes** [comment]
Hello from 2023 :D

This issue is still happening, at least in Godot 3.5, but I managed to solve it by replacing the DLLs (libGLESv2.dll, libEGL.dll) from the template by the ones in this NuGET package:
https://www.nuget.org/api/v2/package/ANGLE.WindowsStore/2.1.13

My 2D Godot 3.5 game is running on an Xbox Series S (UWP) flawlessly and without lag! 🥳
