### ISSUE TITLE
Shaders don't apply correctly on Label/RichTextLabel

### ISSUE THREAD

**Issue by TermalSlime** [godotengine/godot#91719]
### Tested versions

- Reproducible in: 4.3-dev6, 4.2.2-stable, 4.1.4-stable

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19044 - GLES3 (Compatibility) - dedicated NVIDIA GeForce GTX 980 (NVIDIA; 31.0.15.5186) - AMD Ryzen 5 3600 6-Core Processor (12 Threads)

### Issue description

when apply shader on Label/RichTextLabel that uses UV, text is not shaded correctly
![изображение](https://github.com/godotengine/godot/assets/94103211/167047df-7298-4ce8-b225-c6ab5928ead8)

### Steps to reproduce

make Label/RichTextLabel with some text and apply material with this shader:
```
shader_type canvas_item;

uniform vec4 start_color: source_color;
uniform vec4 end_color: source_color;

vec4 lerp(vec4 start, vec4 end, float t)
{
	vec4 ret;
	ret.r = (start.r + (end.r - start.r) * t);
	ret.g = (start.g + (end.g - start.g) * t);
	ret.b = (start.b + (end.b - start.b) * t);
	ret.a = (start.a + (end.a - start.a) * t);
	
	return ret;
}

void fragment() {
	COLOR = vec4(lerp(start_color, end_color, UV.x).rgb, texture(TEXTURE, UV).a);
}
```
and in ```Shader Parameters``` set ```Start Color``` to red and ```End Color``` to green

### Minimal reproduction project (MRP)

[text_bug.zip](https://github.com/godotengine/godot/files/15251582/text_bug.zip)

**Comment by ghmart** [comment]
That is possibly because the shader uses glyphs' UVs, not label's.
Found https://github.com/godotengine/godot/issues/23210. Maybe this is what you want.

Applied workaround to your shader and got this:

![gradient](https://github.com/godotengine/godot/assets/7192155/7076fc00-0965-4f7f-a88e-b71d960623f2)

~~~
shader_type canvas_item;

uniform vec4 start_color: source_color;
uniform vec4 end_color: source_color;

uniform float width;
varying vec2 full_uv;

void vertex()
{
	full_uv = VERTEX.xy;
}


vec4 lerp(vec4 start, vec4 end, float t)
{
	vec4 ret;
	ret.r = (start.r + (end.r - start.r) * t);
	ret.g = (start.g + (end.g - start.g) * t);
	ret.b = (start.b + (end.b - start.b) * t);
	ret.a = (start.a + (end.a - start.a) * t);
	
	return ret;
}

void fragment() {
	COLOR = vec4(lerp(start_color, end_color, full_uv.x / width).rgb, texture(TEXTURE, UV).a);
}

~~~

The "width" uniform = 1152 for your scene obviously.

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/23210.
