### ISSUE TITLE
Sprite3D flickers and ripples as it moves, most obviously in low resolutions

### ISSUE THREAD

**Issue by wetbadger** [godotengine/godot#91819]
### Tested versions

4.2.2.stable.official

### System information

Linux Mint

### Issue description

I expected Sprite3D not to ripple and flicker, but smoothly transition from small to large, like DOOM sprites or other games with 3d sprites. Moving and scaling 2d sprites doesn't have this flickering issue.

I've pretty much tried all settings related to sprite scaling and moving and nothing fixes it. I am pretty sure it happens because, for the sprite not to ripple, it has to move by exactly 1 pixel. This is no problem in 2d, but in 3d it might look right at a very specific distance, but moving out of the "sweet spot" (closer or farther from the camera) means the movement will be more than or less than 1 pixel. There is some math involved in keeping the sprite moving by whole pixels. I don't know if it's something I can cook up in gdscript or if it is more involved. I'm not sure if this is a bug or a feature request. 

### Steps to reproduce

Set your window to low resolution. Create a sprite3D that isn't blurred and move it around.

### Minimal reproduction project (MRP)

https://github.com/wetbadger/FlickeringSprites (click on ground to move)

**Comment by Calinou** [comment]
This is the nature of rendering sprites with nearest-neighbor filtering at a low resolution. You have two solutions to avoid this:

- Render at a high resolution then downsample. This can be done by increasing **Scaling 3D > Scale** to `2.0` in the Project Settings. This also provides high-quality antialiasing. In 4.3, this is supported in all rendering methods. In 4.2, this is only supported in Forward+ and Mobile.
- Use the `canvas_items` stretch mode instead of `viewport`, so that 3D renders at the window size instead of a lower size.

> but smoothly transition from small to large, like DOOM sprites or other games with 3d sprites

Vanilla Doom actually handles this really poorly due to its 320×200 resolution. If you find sprite scaling to be smooth there, it's because source ports generally render at the native resolution (or at least a resolution that's higher than vanilla).

**Comment by wetbadger** [comment]
Thank you for the elaborate explanation.

My intuition tells me there is a mathematical way to solve this. At each distance you would have to calculate a matrix on which the pixels "line up" with the viewport resolution. At least distance and FOV factor into this. Then, each frame, adjust the position of the sprite slightly so that the pixels align with this matrix. How to calculate these matrices though?
