### ISSUE TITLE
Blending/Animating String or StringName tracks cause odd interpolation

### ISSUE THREAD

**Issue by takanan** [godotengine/godot#91867]
### Tested versions

- Reproducible in: v4.3.dev6.official [64520fe67], v4.3.dev5.official [c9c17d6ca]
- Not reproducible in: v4.2.2

### System information

Godot v4.3.dev6 - Arch Linux #1 SMP PREEMPT_DYNAMIC Tue, 07 May 2024 21:35:54 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (nvidia; 550.78) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

- Blending two animations with each having a single keyframe of String/StringName, it interpolates in a weird way.
  - [blending_two_string_keyframes.webm](https://github.com/godotengine/godot/assets/1814284/ac72f97a-fbf4-463d-994c-0f63c289e425)
  - Those will occur regardless setting keyframes to discrete update mode or nearest interpolation mode.
  - ~~Especially blending with Add2, it will show broken text. Might be showing something internal memory things, which is not good.~~
    - No security issues for interpolating Strings

- Also just animating a String/StringName track with continuous update mode AND linear interpolation causes same issue.
  - [animating_between_two_string_keyframes.webm](https://github.com/godotengine/godot/assets/1814284/b98ccc8a-a460-49ea-8e30-a1fd6566c941)

### Steps to reproduce

- Create any node which has String or StringName property
- Create two animations of the property
- Blend those two animations on AnimationTree with any blending methods (e.g. Add2, Blend2, OneShot with fadein/fadeout time, ...)

### Minimal reproduction project (MRP)

N/A

**Comment by Protowalker** [comment]
There's no memory safety issues happening here; it's intentional, it's trying to interpolate between the two strings and find a string that's somewhere in the middle. https://github.com/godotengine/godot/blob/bdc0316217940a8ccc80ce536547d42e6477adf4/scene/resources/animation.cpp#L6016 Not sure when that would be desired, but it looks like it's not a bug.

**Comment by takanan** [comment]
I've looked the provided part of code and there is no security issue (reading out of memory boundary). Thank you for the indication. Treating string as float array and interpolating it is fancy and I like that.

Although, a string property track being interpolated even it's set to discrete update mode and nearest interpolation is a bug to me.

For example, AnimatedSprite2D:animation has StringName type. If you have two animations each changes the property, and blend them on AnimationTree, despite the track is set to discrete and nearest, you will get error messages like this every time it's being blended (which is expected error message).
![Screenshot_20240513_200431](https://github.com/godotengine/godot/assets/1814284/474941fe-e8e6-4ad8-9086-cef996fade97)

**Comment by Protowalker** [comment]
As far as I can tell, this behavior happens for any property track, not just string properties, correct? If so, this seems less like a bug more like a design decision. Personally I think it makes sense for a blend node to just interpolate between whatever the two values of a track would be in the two source animations. Maybe the docs could be more explicit?

**Comment by takanan** [comment]
A track with discrete update or nearest interpolation for String/StringName will be properly interpolated like a binary inbetween keyframes. But for blending on AnimationTree, it will be interpolated fancy way.

Is this a design decision?
For me it's just incoherent.

**Comment by takanan** [comment]
> this behavior happens for any property track, not just string properties
I don't have enough time for exhaustive test to prove this, but I guess so. Confirmed enums are also interpolated as they treated as integer.

I'm not dev so I don't know if this is desired behavior or not, but if so, please add document on animation section to not use discrete property for AnimationTree. Since any discrete property is forced being interpolated otherwise its inbetween value is unintentionally used (e.g. Node:process_mode from Inherit=0, Paused=1, WhenPaused=2, Always=3 to Disabled=4).

**Comment by TokageItLab** [comment]
The change in behavior in 4.3.dev is due to a change in the handling of UpdateMode.Discrete.

"All tracks are Discrete" in 4.2 means that CallbackModeDiscrete in 4.3 is Dominant. The default in 4.3 is ForceContinuous, which is suitable for blending; This means that during blending, Discrete/int is treated as Contiunous/float, and after blending, the values are rounded back to int. (And I am sorting out the documentation on this now.)

If you want the same behavior as in 4.2 with proper behavior, deactivate the second AnimationPlayer and set CallbackModeDiscrete to Dominant.

![image](https://github.com/godotengine/godot/assets/61938263/e2be037c-9681-4565-9103-ad9d995bc44e)

I am preparing a migration document for this and will close this issue after publishing it.

**Comment by takanan** [comment]
This is little bit complicated so I try to clear it for myself.
- A discrete property
  - value like StringName or Enum flags where interpolation is not preferable
- An animation track with discrete update mode
  - property is updated only on keyframes

If I set AnimationTree:CallbackMode to Dominant, an animation track with Discrete update mode doesn't keep updated in blending (#90897) because its nature of "only update on keyframes". In order to keep updating properties on animation blending, continuous update mode must be applied.

I have a discrete property that I want to use in animation blending and keep it being updated, my only option is create a track for the property with Continuous update mode with Nearest interpolation. But as I reported, this is not work since the property is getting linearly interpolated in blending process. So, the problem is Nearest interpolation is not working in animation blending. Am I correct?

**Comment by TokageItLab** [comment]
InterpolationType defines the interpolation when the animation is played back. Rotation properties reference it as a Hack for special cases, but otherwise InterpolationType, whether int, String and others, has no effect on blending.

There is no implementation in the current AnimationTree that switches between two properties with a threshold of 0.5. If you want to do that, you currently have to use Disctrete. See also https://github.com/godotengine/godot-proposals/issues/8085.

For that reason, such as Resource (and other non-interpolatable type) property is forced to blend in Disctrete mode, even when using Continuous mode.

Another possible option would be BlendSpace, since it has a Discrete “blend” mode that you could use.

![image](https://github.com/godotengine/godot/assets/61938263/81e49839-3c63-415e-935d-5db70aaeeb0c)

**Comment by TokageItLab** [comment]
Closed by https://github.com/godotengine/godot-website/pull/851
