### ISSUE TITLE
no tween_complete signal is emit by method tween.interpolate_callback

### ISSUE THREAD

**Issue by alexzheng** [godotengine/godot#9187]
**Operating system or device - Godot version:**
ALL

**Issue description:**
func _on_tween_complete(obj, key, tween):
	print("free", obj, key)
	tween.queue_free()
	
func call_delay(delay, object, method, arg0=null,arg1=null,arg2=null,arg3=null,arg4=null):
	var tween = Tween.new()
	tween.interpolate_callback(object, delay, method, arg0, arg1, arg2, arg3, arg4)
	add_child(tween)
	tween.start()
	tween.connect("tween_complete", self, "_on_tween_complete", [tween])

_on_tween_complete will not call
there is no way to free the tween object

**Steps to reproduce:**

**Link to minimal example project:**

**Comment by bojidar-bg** [comment]
The signal is supposed to be emitted on [`scene/animation/tween.cpp:613-619`](https://github.com/godotengine/godot/blob/b7a2a40b8e3515a359788ec8ad34e8667109a4c1/scene/animation/tween.cpp#L613):
```cpp
if (data.finish) {
	_apply_tween_value(data, data.final_val);
	emit_signal("tween_completed", object, data.key);
	// not repeat mode, remove completed action
	if (!repeat)
		call_deferred("_remove", object, data.key, true);
}
```

Unfortunatelly, because of [`tween.cpp:605`](https://github.com/godotengine/godot/blob/b7a2a40b8e3515a359788ec8ad34e8667109a4c1/scene/animation/tween.cpp#L605), this is never going to get called.

I think what should be done is moving lines 608-611 inside the switch (with curly braces around them):
```cpp
Variant result = _run_equation(data);
emit_signal("tween_step", object, data.key, data.elapsed, result);

_apply_tween_value(data, result);
```

Then we should change the `continue` to another `break` statement, and potentially put the INTER_CALLBACK case's code in curly braces as well.

Also, (current) lines 602-603 should be removed, so we don't duplicate code:
```cpp
if (!repeat)
	call_deferred("_remove", object, data.key, true);
```
