### ISSUE TITLE
== comparison operator not working as I thought it should work. what the heck is happening??

### ISSUE THREAD

**Issue by cleconte987** [godotengine/godot#91913]
### Tested versions

Godot 3.5

### System information

Linux Ubuntu 22.04

### Issue description

Comparison operator == super weird behavior testing 1.0 == 1.0 in certain conditions not working

### Steps to reproduce

You can download the following minimal reproducible project to test

### Minimal reproduction project (MRP)

[project.tar.gz](https://github.com/godotengine/godot/files/15297862/project.tar.gz)

**Comment by lvcivs** [comment]
Which release are you using exactly? I tried opening with 3.5.3stable and it wouldn't open.

I then copied your code into a new project and it prints: 
```
yes2
end
```
… which is correct, no? I suspect you wanted to add `0.01`  in the loop, and start with `my_float` set to `0.0`? If you try that, it will not print `yes` despite both being 1.0, which is probably the reason for your post. But it's expected behaviour. You should generally not check for equality on floats, read the answer to this forum post: https://forum.godotengine.org/t/problem-comparing-floats/30620

**Comment by cleconte987** [comment]
Wahh forgot about this sh** oh my god.
Thank you for your help.

**Comment by cleconte987** [comment]
But I think this should trigger at least a warning

**Comment by Chaosus** [comment]
> But I think this should trigger at least a warning

See https://github.com/godotengine/godot/pull/55142, it's queued for merging

**Comment by cleconte987** [comment]
Cool
