### ISSUE TITLE
bytes_to_var conversion issues

### ISSUE THREAD

**Issue by giddycodedev** [godotengine/godot#91915]
### Tested versions

Reproducible in:
- Godot v4.2.2.stable
- Godot v4.3.dev6

### System information

Godot v4.2.2.stable - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4080 (NVIDIA; 31.0.15.5222) - 13th Gen Intel(R) Core(TM) i9-13900K (32 Threads)

### Issue description

Looks like we cannot rely on bytes_to_var conversions. I have observed an issue while converting bytes from the storage buffers back to the primitives in GDScript. Initially, I thought this could only be related to compute shaders. However, this isn't the case. In the attached project, we can also see that a PackedVector2Array converted to a PackedByteArray couldn't be converted back to its original type, PackedFloat32Array.

This issue can be worked around, although readability of the code suffers. 
Wondering if [this pr](https://github.com/godotengine/godot/pull/76075) would resolve this issue.

Basically, I would expect to see data rather than nulls in below output.

```gdscript
INPUT ARRAY      : [1, 2]
INPUT BYTES      : [0, 0, 128, 63, 0, 0, 0, 64]
SIZE IN BYTES    : 8
Input data                : [1, 2]
Output bytes              : [154, 153, 57, 64, 154, 153, 185, 64]
Output bytes size         : 8
Output data               : [2.90000009536743, 5.80000019073486]
Output data using generic : <null>
Output vec bytes              : [102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65]
Output vec bytes size         : 16
Output vec data using generic : <null>
Confirmation receiving valid data from the compute storage buffer
Vec2 Godot to Bytes           : [102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65]
Output vec data using generic : <null>
```
### Steps to reproduce

Basically run the attached project and take a look at the printed messages.

### Minimal reproduction project (MRP)

[BytesToVar.zip](https://github.com/godotengine/godot/files/15297252/BytesToVar.zip)

**Comment by kleonc** [comment]
`bytes_to_var` is supposed to convert back the data coming from `var_to_bytes`. The difference compared to `PackedVector2Array.to_byte_array` is that `var_to_bytes` includes also some data about what's serialized in the buffer, which allows it to be properly deserialized later (see [Binary serialization API](https://docs.godotengine.org/en/4.2/tutorials/io/binary_serialization_api.html) for more details about the format used).

```gdscript
@tool
extends EditorScript

func _run() -> void:
	var vec2_array: PackedVector2Array = [Vector2(9.9,9.9), Vector2(9.9,9.9)]
	var vec2_array_to_byte_array: PackedByteArray = vec2_array.to_byte_array()
	var vec2_array_var_to_bytes: PackedByteArray = var_to_bytes(vec2_array)
	print(vec2_array_to_byte_array)
	print(vec2_array_var_to_bytes)
```
Output:
```
[102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65]
[35, 0, 0, 0, 2, 0, 0, 0, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65]
```
As you can see above `var_to_bytes`'s output also includes the data type (`35, 0,` part, `TYPE_PACKED_VECTOR2_ARRAY == 35`), some additional flags (`0, 0,` part, no flags), and the length of the array (`2, 0, 0, 0,` part). This data tells how further data should be interpreted (and how much of it, as the serialized `PackedVector2Array` could be only a part of the whole buffer, e.g. it could be just an element of an Array passed to `var_to_bytes` etc.).

For converting a pure data buffer like `[102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65]` to a `PackedVector2Array` there would indeed need to be a method assuming such input format (so e.g. length could be deduced from the input size because of the assumed format).

> Wondering if [this pr](https://github.com/godotengine/godot/pull/76075) would resolve this issue.

So yes, #76075 would resolve this issue as it adds exactly such method to `PackedByteArray`.

---

So I think there's nothing to be done about this issue as this is not a bug and there's already https://github.com/godotengine/godot-proposals/issues/8139 about adding the needed method?

**Comment by kleonc** [comment]
> For converting a pure data buffer like `[102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65, 102, 102, 30, 65]` to a `PackedVector2Array` there would indeed need to be a method assuming such input format (so e.g. length could be deduced from the input size because of the assumed format).

But note that until after such dedicated method would be added you could of course manually decode a `PackedByteArray` assuming whatever format you want, e.g. specifically for decoding the result of `PackedVector2Array.to_byte_array`:
```gdscript
func bytes_to_packed_vector2_array(bytes: PackedByteArray) -> PackedVector2Array:
	if bytes.size() % 8 != 0:
		return []
	var result: PackedVector2Array = []
	var count: int = bytes.size() / 8
	result.resize(count)
	for i in count:
		result[i] = Vector2(bytes.decode_float(i * 8), bytes.decode_float(i * 8 + 4))
	return result
```
