### ISSUE TITLE
stencil shadow support

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#9193]
Would love to see stencil shadow support in godot 3.0. 
I know its not a common technique these days, but its great for getting crisp shadows. 
I would love to use them in the project Im working on currently.
Also the stencil voumes only need to be generated at load time for static objects.

**Comment by Gibbz** [comment]
Also figure the same technique could be used to generate godray/light shafts and other effects

**Comment by supagu** [comment]
I was playing ARMA3 and I recon they use it there in combination with shadow maps

**Comment by reduz** [comment]
Not going to happen because

1)  it's not a magic technique and it requieres a considerable amount of
manual labor from the art side.
2)  it's extremely inefficient
3)  Crisp shadows are not realistic anyway, shadow maps are closer to IRL.
4)  Godot 3.0 has a really nice way to adjust shadow map resolution
depending on distance and usage
5)  You can use contact shadows in 3.0, which become really crisp near the
shadow-object contact.
