### ISSUE TITLE
Hang Attempting to import stl as mesh

### ISSUE THREAD

**Issue by Careknight** [godotengine/godot#9200]
Windows 7 64bit. Godot Version : 2.1.3

User Case: 
Exporting a file from blender and importing a file into godot.

Steps:
1. Launch Godot and open a project.
2. Click "Import" , "Mesh".
3. Open file browser for "Source Mesh(es)"
4. Select all file types.
5. Select .stl file. 
6. Click "Open".
7. Open Select Path browser.
![image](https://user-images.githubusercontent.com/21026917/27203400-a0f56c4a-521d-11e7-95cb-15aa496be9cb.png)
7.note: I did not seem to be able to select a sensible output path, screen shot attached.
8. Click "Import".

The program will stop responding at this point.
I required task manager to kill.

What I would expect:
- Block the selection of the .stl file.

**Comment by bojidar-bg** [comment]
You are supposed to select only .obj (wavefront) files. But hanging on invalid input doesn't sound good either..

**Comment by bojidar-bg** [comment]
For anyone wanting to try fixing this, the while loop in [`…/editor_mesh_import_plugin.cpp:405 (2.1)`](https://github.com/godotengine/godot/blob/2.1/editor/io_plugins/editor_mesh_import_plugin.cpp#L405) 
can only end on line [`:517`](https://github.com/godotengine/godot/blob/2.1/editor/io_plugins/editor_mesh_import_plugin.cpp#L517), and the whole looks like this:

```cpp
int has_index_data = false;

while (true) {
	String l = f->get_line().strip_edges();

	…
	
	if (l.begins_with("o ") || f->eof_reached()) { //new surface or done

		if (has_index_data) {
			//new object/surface

			…

			if (f->eof_reached())
				break;
		}

		if (l.begins_with("o ")) //name
			name = l.substr(2, l.length()).strip_edges();
	}
}
```
The `break` would be reached only when `l.begins_with("o ") || f->eof_reached()` is true and `has_index_data` is true. Since the whole imported file is invalid (as it isn't .obj), `has_index_data` would be always false.

I guess the `break` if should be moved down after the `if (l.begins_with("o "))`.

**Comment by aswinmohanme** [comment]
I am working on this right now.

**Comment by aswinmohanme** [comment]
Shouldn't this issue be closed now ?

**Comment by akien-mga** [comment]
Yes.
