### ISSUE TITLE
Cursor Shape never changing under Linux (in-game & in editor)

### ISSUE THREAD

**Issue by petterthowsen** [godotengine/godot#92040]
### Tested versions

4.2.2 Stable, 4.2.1 Stable

### System information

Linux Mint 21.3 Cinnamon, kernel 6.5.0-14-generic

### Issue description

I recently said bye to windows and installed Linux Mint and noticed that the cursor shape never changes. This is true for both the editor and running games.

I.E, when hovering over certain elements where the cursor should change, it doesn't change. It's just stays as the default arrow shape.

### Steps to reproduce

Launch the editor. Move mouse over vertical or horizontal splitter/draggable thingy or anything that usually changes the mouse cursor.

### Minimal reproduction project (MRP)

N/A

**Comment by 4X3L82** [comment]
Fellow Linux-user here (without this issue (KDE5 & 6 + Godot 4.2 & 4.3dev1-6)).

Does the mouse cursor change in other programs? For example in a text editor do you get the "writing cursor", or the vertical or horizontal splitter, etc.

Did you use flatpaks to install Godot? Because this might be a [relevant issue](https://github.com/linuxmint/cinnamon/issues/11868) then.

**Comment by 4X3L82** [comment]
Then I think you fall under the issue I posted above.

What if you [download Godot from the official site](https://godotengine.org/download/linux/) and run that one? Does the problem persist?

**Comment by petterthowsen** [comment]
I reinstalled "Godots" by a mistake haha but when O opened godot again, now I have cursors! No idea what happened.
