### ISSUE TITLE
Subviewport is duplicating itself when screen shader is used

### ISSUE THREAD

**Issue by starblinky** [godotengine/godot#92058]
### Tested versions

Reproducible in v4.2.2.stable.official [15073afe3] and v4.3 -dev6 beta

### System information

Mac OS Sonoma 14.4.1 (23E224)

### Issue description

When using a screen-shader in a SubViewPort there is a double image. The SubViewPort will draw the original texture (pre-shader) and then draw AGAIN with the shader effect on top. 

<img width="184" alt="Screenshot 2024-05-17 at 12 09 30 PM" src="https://github.com/godotengine/godot/assets/51274080/6ed80aa4-1048-420e-91c3-17ca81285669">

If you select "Transparent Background" the original texture (pre-shader) no longer shows. But now the background is no longer transparent. I can work around this by setting the grey colour alpha to 0 within a shader, but this isn't ideal solution for me. 

### Steps to reproduce

<img width="270" alt="Screenshot 2024-05-17 at 12 03 00 PM" src="https://github.com/godotengine/godot/assets/51274080/e87148bc-d7ef-41fd-9201-0776a210c931">

Shader code:
```
shader_type canvas_item;

uniform sampler2D tex : repeat_enable;
uniform sampler2D SCREEN_TEXTURE: hint_screen_texture, filter_linear_mipmap;
void fragment() {

	vec4 noiseTex = texture(tex, UV + TIME * 0.2);
	vec4 mainTex = texture(SCREEN_TEXTURE, SCREEN_UV + noiseTex.r);

	COLOR = mainTex;
}

```

Create a Noise Texture for the shader: 

<img width="485" alt="Screenshot 2024-05-17 at 12 20 13 PM" src="https://github.com/godotengine/godot/assets/51274080/5ba9ab48-48c8-4c73-95fd-2ab2e98f7564">

### Minimal reproduction project (MRP)

[DuplicationBug for Github.zip](https://github.com/godotengine/godot/files/15356385/DuplicationBug.for.Github.zip)

**Comment by Chaosus** [comment]
I guess you should disable 'Transparent BG' on the SubViewport to achieve desired effect.

**Comment by clayjohn** [comment]
Thank you for your report. I have tested locally and confirmed that this is the expected behaviour for what you are doing. 

Screen reading textures simply copy the screen below them. When you use them to draw, they are just drawing over top the thing they just copied. Godot doesn't clear the area underneath. 

When you use an opaque viewport with this shader you can obscure the old texture with the background color. But when using a transparent background, it is more obvious that the second sprite is simply drawing over the first sprite. 

If you change your background to something other than flat gray, you would notice this same problem even using an opaque viewport. 

Based on your description, it sounds like what you actually need is a second Viewport. Instead of using a screen reading shader you can pass the results of the Viewport to a custom shader using a ViewportTexture.
