### ISSUE TITLE
Add Vector.set_length(length) and (optionally) Vector.add_length(length)

### ISSUE THREAD

**Issue by noidexe** [godotengine/godot#9206]
`Vector.set_length(float lenght)` would be just syntactic sugar for doing `myvector = myvector.normalized() * length`
`Vector.add_length(float increment)` would be just syntactic sugar for doing `myvector = myvector.normalized() * (myvector.length() + increment)`

It's not a huge annoyance but coming from Phaser I miss not having an equivalent to Phaser.Point.setMagnitude()

**Comment by toger5** [comment]
I like the set_length function. `add_length` feels like too much for me... than we could have all kinds of functions like. `multiply_length()`, `subtract_length()` ... *okay I'm getting ridiculous*...
Maybe a nicer solution would be to make a length property:
than this is possible
`vector.length += 10` `vector.length = 3` `print(vector.length)` `vector.length *= 3`

**Comment by akien-mga** [comment]
> Maybe a nicer solution would be to make a length property:
than this is possible
vector.length += 10 vector.length = 3 print(vector.length) vector.length *= 3

That's not possible with cartesian vectors which are represented by (x,y) coordinates. For a set length, you can have an infinite number of (x,y) combinations. What you propose would work only if we changed the inner representation of vectors to polar (r, theta), but I don't see that happening.

On the other hand a `set_length()` as mentioned above would be doable. But there would not be direct access to a `length` attribute, since it's a calculated attribute.

**Comment by toger5** [comment]
Of course the behaviour of `length` has to be documented properly. But if the length attribute has no influence on the direction of the vector there is only one solution for the resulting vector after changing the length attribute.

**Comment by bojidar-bg** [comment]
Well, you can do any operation on length as long as you represent the vector as magnitude + direction. To get the direction we use `.normalized()`, and the magnitude is `.length()`.
If we have `.set_length()`, then `.OP_length(x) == .set_length(length() OP x)`
(where OP is some operator, as in `add_length = set_length(length() + x)`).

What wouldn't work as well would be multiplying the length by 0 and then adding some amount (it would remain 0). Everything else would work a charm.

I think having length as a property isn't too weird either, consider that:
```gdscript
var x = Vector2(1, 0)
x.length = 7 # Invoke the setter
print(x.length) # Invoke getter, obviously 7
x.length = x.length * 3 # Invoke both setter and getter
x.length *= 3 # Equivalent operation
```

The only issue I can see with this is that calculating length (as well as setting it) involves a potentially slow square root operation, so it might be better as a function.

**Comment by Serenitor** [comment]
I was also pretty perplexed when I could't find a set_length helper method in the docs. In my mind it should be a standard, and I'd be using it all the time.

however when looking at the existing methods, it becomes clear that the original intention was to not have any methods that transform the vector in place, but only those that return a new vector with the transformation applied to it.

it would be weird to have one single method - e.g. set_length - that transforms directly. In that scenario, we should also have `set_rotation()`, `normalize()`, and more.

here's an example of a set of methods from a vector lib I've written a while back:

- `angle()`          returns angle in radians
- `setAngle()`     sets angle from radians in place
- `degree()`        returns angle in degres
- `setDegree()`     sets angle from degress in place
- `length()`         returns length
- `lengthSq()`         returns length squared
- `setLength()`         sets length in place
- `multiplyLength`    multiplies length in place (apparently I've had a need for that more frequently than adding to the length, but I also don't think that I'd be important)
- `normal()`         returns normalized vector
- `normalize()`         normalizes vector in place
- `clamped()`         returns clamped vector
- `clamp()`         clamps vector in place

that worked very well for me, but I imagine we'll want to stick to functions that return only.

then it shouldn't be `set_length()`, but ... well, any kind of of adjective that refers to length. `magnified()` perhaps? seems like the reason this function is currently missing is because it's so hard to come up with a decent name lol.

also, `myvector.normalized() * length` does not work on `Vector.ZERO`, i.e. vectors that do not yet have a length. Instead, what `magnified()` should do instead is (pseudo code incoming):
```
    angle = arctan2(vec.y, vec.x)
    vec.x = cos(angle) * length
    vec.y = sin(angle) * length
```

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
