### ISSUE TITLE
A "center" option for interactive shapes

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9218]
Drawing lines (Line2D), polygons (Polygon2D) and curves (Path2D) on the editor can lead to the figure being displaced from the node center and sometimes is hard to re-position them.

A (scene editor) way to center the figure to the origin of the node could be really useful.

ps: This "center" (or arbitrary "displace") option could be part of Vector arrays too to make it more generic but I don't know if there are plans to give extra functions to these kind of arrays.

**Comment by Zylann** [comment]
Note: the editors for these three nodes are not generic at all, they are very similar but their common parts is copy/pasted

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
