### ISSUE TITLE
Autocompletion sometimes fails inside method calls

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92226]
### Tested versions

4.3 dev6

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

Sometimes the autocompletion fails to appear. Usually it happens when doing `some_method(` and it's broken inside the parentheses. However it seems to have some convoluted conditions, because it happens only in very specific scripts/spots.

Here's example of such script:
```GDScript
@tool
extends EditorScript

func _run() -> void:
	for world in DirAccess.get_directories_at("res://Maps"):
		for scene in DirAccess.get_files_at("res://Maps/%s" % world):
			if scene.get_extension() == "tscn":
				process_scene("res://Maps/%s/%s" % [world, scene])
		
		for scene in DirAccess.get_files_at("res://Maps/%s/Interiors" % world):
			if scene.get_extension() == "tscn":
				process_scene("res://Maps/%s/Interiors/%s" % [world, scene])

func process_scene(path: String):
	EditorInterface.open_scene_from_path(path)
	var tile_map := get_scene().get_node_or_null(^"TileMap") as TileMap
	#print(get_
	
	if not tile_map:
		return
	
	print("Processing %s" % path)
	EditorInterface.get_selection().clear()
	EditorInterface.get_selection().add_node(tile_map)
	
	get_scene().get_tree().get_nodes_in_group(&"map_tools").front().menu_option(7)
	EditorInterface.save_scene()
	unreference()
```
If you uncomment the `#print(get_` line and try to autocomplete something (in my case it was `get_scene()`), nothing will appear.

### Steps to reproduce

1. Open the above script in script editor 
2. Uncomment line 17
3. Put caret at the end and press Ctrl+Space

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
I did some tests with lastest master b947c53dd and actually is very easy to reproduce, this happens in any place that has a if statment after, also if you don't complete the code and let the print function parentesis open will show the error: "Expected else after ternary operator condition" so maybe the problem is the editor wrongly thinking you're doing a ternary operation. If you close the print parenthesis the auto completation will works and no error will appear


https://github.com/godotengine/godot/assets/44306054/e56bc989-8ce9-45fc-ba7c-ade1b7dfb082

**Comment by HolonProduction** [comment]
I looked into that a bit further. Turns out, having the right completion context for call arguments only works through a [hack in the parser](https://github.com/godotengine/godot/blob/705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427/modules/gdscript/gdscript_parser.cpp#L3191) at the moment. As mentioned before the parser tries to parse a ternary and is therefore on an different code path than the hack.

The nature of that hack is to bypass the force parameter when pushing an completion context. Setting this parameter to true in the right places would fix the issue. However after asking in the contributor chat, it seems as if no one knows why we need the force parameter at all (or more precise why it should be false in any case). So I'd suggest removing it and relying only on the cursor position to determine whether the context should be updated.
