### ISSUE TITLE
godot fails to export on ios

### ISSUE THREAD

**Issue by maurosorrentino** [godotengine/godot#92396]
### Tested versions

4.2.1, 4.2.2 .NET

### System information

macOS Sonoma version 14.3, M1 chip macbook pro 14inch from 2021

### Issue description

when exporting on ios I keep getting 
`MSB3073: The command ""clang" some paths
`

I tried to fix it like you said in the documentation
`xcode-select -p (to check)
sudo xcode-select -switch /Applications/Xcode.app (to fix)
`

I did setup xcode, the SDK is in the right place as I checked by going in that directory and the command above, the path is 
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk`

I tried to run the app anyway on my ipad but it doesn't work

am I missing something or is it a bug?

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by LeonardoDemartino** [comment]
The actual error for this is:

ld: Assertion failed: (false && "compact unwind compressed function offset doesn't fit in 24 bits"), function operator(), file Layout.cpp, line 6026.


It is related to newer versions of XCode (15.1 and newer) that requires the "-ld64" or "-ld_classic" flags in the linker flags.

Same issue here:
https://github.com/ChainSafe/web3.unity/issues/686

I'm having the same issue so I'm downgrading to XCode 15.0 since we can't edit the commandline used by godot when building the xcode project.

**Comment by maurosorrentino** [comment]
thanks @LeonardoDemartino

**Comment by LeonardoDemartino** [comment]
Could you please share your full error log @maurosorrentino ?

**Comment by maurosorrentino** [comment]
@LeonardoDemartino I don't have it anymore, it was a long time ago. There is also an issue when exporting to Android which I raised, will go back to Godot hopefully in a few months. I would like to thank you though for your hard work, is very much appreciated!! :)

**Comment by AThousandShips** [comment]
Without further details this is not likely to be possible to fix, closing and if you provide necessary information this can be reopened
