### ISSUE TITLE
Cannot export to Mac

### ISSUE THREAD

**Issue by TwistedTwigleg** [godotengine/godot#9243]
![mac_export_issue_picture](https://user-images.githubusercontent.com/25082678/27256051-f6dfb1cc-5378-11e7-92dc-f18c207f5d9c.png)
**Operating system or device - Godot version:**
Linux Ubuntu 16.4 - Daily build from fixnum.org (June 8th and June 17th)

**Issue description:**

You cannot export any project to Mac. There is no option in the drop down and I couldn't find anyway to make a preset through editing the configuration file.

Exporting to Linux and linking custom the custom template to the Mac template doesn't produce a working export.

**Steps to reproduce:**
Open the export menu and look at the available options.

**Comment by vnen** [comment]
The exporter code has changed and not all platforms had their exporters ported to the new format yet.

**Comment by TwistedTwigleg** [comment]
My apologizes! I didn't realize the Mac exporter hasn't been ported yet and thought maybe it was just a bug on Linux.

Should I close or delete this issue?

**Comment by vnen** [comment]
No need to close, it serves as a reminder to port the Mac exporter code.

**Comment by BastiaanOlij** [comment]
@vnen , any pointers on where this code is, I've not looked at it before but if I know where to look I can try my hand at getting them to work on OSX and iOS

**Comment by vnen** [comment]
@BastiaanOlij that's the right place.

**Comment by BastiaanOlij** [comment]
@vnen yeah found it :) But looks like a new subclass of EditorExportPlatform needs to be created and by the looks of things these are now moved to editor/editor_export.h, strange choice, makes more sense to me to have them in the platform location..

I'll see if I can try and create the actual application bundle from Godot itself instead of relying on a zip file so that we can just include the compiled executables in our templates. That allows for building a proper plist as well.

**Comment by vnen** [comment]
It should stay on `platform/osx/export/export.cpp` (see the Android one). For Windows/Linux is a bit different because both use `EditorExportPlatformPC` as base.

**Comment by BastiaanOlij** [comment]
@vnen that does make far more sense to me.
