### ISSUE TITLE
TextureRect load image at runtime

### ISSUE THREAD

**Issue by ratzycon** [godotengine/godot#92502]
### Tested versions

v4.2.2.stable.official [15073afe3]

### System information

Windows 10 - v4.2.2.stable.official [15073afe3]

### Issue description

Loading an image into TextureRect at runtime does not appear to work if following suggested procedures 
(for example provided by chatGPT and other places)

```gdscript
# this doesn't work, nothing shows up, silent fail
var image = Image.new()
image.load("res://2B.png")
var tex = ImageTexture.new()
tex.create_from_image(image)
$TextureRect.texture = tex
```

```gdscript
# this works, image shows up at runtime
var image = Image.new()
image.load("res://2B.png")
var tex = ImageTexture.create_from_image(image)
$TextureRect.texture = tex
```

![load_texture_from_png](https://github.com/godotengine/godot/assets/111074889/267873e3-cd7b-4e2b-b554-2dfa8f95ab48)
![load_texture_from_png3](https://github.com/godotengine/godot/assets/111074889/683f55c5-bbf7-4dc5-9cd0-bd4c8312b2f9)

### Steps to reproduce

uncomment / comment out respective lines in the example
run to see only 1 of them displays the image

### Minimal reproduction project (MRP)

[TextureRect_image.zip](https://github.com/godotengine/godot/files/15477669/TextureRect_image.zip)

**Comment by theraot** [comment]
The method [`create_from_image`](https://docs.godotengine.org/en/stable/classes/class_imagetexture.html#class-imagetexture-method-create-from-image) is documented to be static.

So the line `tex.create_from_image(image)` is calling an static method as an instance method. *This is a warning, not an error, and it can be disabled from project settings.*

Plus, `create_from_image` does not modify the current isntance (because, again, it is static), instead it returns.

This is the example from the documentation:

```GDScript
var image = Image.load_from_file("res://icon.svg")
var texture = ImageTexture.create_from_image(image)
$Sprite2D.texture = texture
```

**Comment by ratzycon** [comment]
i suspected the function had changed to a static, and the limitation of gdscript doesn't easily indicate this or have an utility function on the instance object - or perhaps it was always static
for some reason coding llm's has not picked this up yet, unless directly mentioning it is static
if this is the intended way, this can be closed,

**Comment by theraot** [comment]
Yes, this changed. Godot 3.x didn't use statics, because GDScript didn't support them. The following is the example from the Godot 3.5 documentation:

```GDScript
var texture = ImageTexture.new()
var image = Image.new()
image.load("res://icon.png")
texture.create_from_image(image)
$Sprite.texture = texture
```

---

About better showing this... You can go to Project Settings -> General -> Debug -> GDScript and change "Static Called On Instance" from Warn to Error.

There is also proposal for squiggly underlines: https://github.com/godotengine/godot-proposals/issues/1005 but it has not been implemented at the time of writting. You may also post a proposal on https://github.com/godotengine/godot-proposals/issues if you another idea of what to do about this, or open a discussion on https://github.com/godotengine/godot-proposals/discussions

---

With that said, I believe there is still an issue here. The autocomplete not only includes the static method while accesing an instance, it does so without any indication that you might be accesing an static method.

I assume it makes sense to keep them because they are available, even if that is not the intended way to use them. So, perhaps giving different icons to static members would suffice.

**Comment by timothyqiu** [comment]
LLM is language model, not knowledge model :P

By the way, as the warning said, this won't work in the exported project (because `2B.png` the file won't be exported):

```gdscript
var image = Image.new()
image.load("res://2B.png")
```

Instead, you can load the image directly:

```gdscript
$TextureRect.texture = load("res://2B.png")
```

**Comment by ratzycon** [comment]
> LLM is language model, not knowledge model :P
> 
> By the way, as the warning said, this won't work in the exported project (because `2B.png` the file won't be exported):
> 
> ```gdscript
> var image = Image.new()
> image.load("res://2B.png")
> ```
> 
> Instead, you can load the image directly:
> 
> ```gdscript
> $TextureRect.texture = load("res://2B.png")
> ```

thanks, yea the example was just a quick hack, in the actual code I convert output from stable diffusion to texture

I'm kind of new to Godot and still learning gdscript, which is why i was using chatgpt for a few examples (as i expect many will)
besides being language models, LLM's are also encoding knowledge - whether that knowledge is accurate is another matter 📦 not exactly sure what can be done to push llm's to stop proposing deprecated code

the warning is great, changing it to error helps too
I guess C# just doesn't display the statics on the instance at all
the change will not break old code besides giving warnings, but might just no longer work (sometimes it's better to break)

it's fine as a static, but it feel a bit like it can't decide if OOP is preferred pattern or not
thinking as oop you might think, 1. create a new() image object, 2. load the image data into it - instead we have static return a new object. which could raise a couple of questions:
is  the object a pure value/data type? 
what happens if we were referencing the previous object elsewhere etc

what you think, do we leave it open for a bit or close it?

**Comment by ratzycon** [comment]
> > what happens if we were referencing the previous object elsewhere etc
> 
> You can still update the texture and keep references, use [`set_image`](https://docs.godotengine.org/en/stable/classes/class_imagetexture.html#class-imagetexture-method-set-image), and [`set_data`](https://docs.godotengine.org/en/stable/classes/class_image.html#class-image-method-set-data) for image, different methods for different purposes
> 
> Using static constrictor methods _is_ OOP

ah, I see, so in that case i would use it as this 
(reusing the ImageTexture container with set_image)

```gdscript
var image = Image.new()
image.load("res://2B.png")
var tex = ImageTexture.new()
tex.set_image(image)
$TextureRect.texture = tex
```

**Comment by ratzycon** [comment]
closing the issue. thank you all <3
