### ISSUE TITLE
Inspector Window not casting as float in float forms

### ISSUE THREAD

**Issue by Racer911dash1** [godotengine/godot#92595]
### Tested versions

Tested with `v4.2.2.stable.official [15073afe3]` and `v4.3.beta1.official [a4f2ea91a]`. Happens on both occasions

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti (NVIDIA; 31.0.15.5212) - Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 Threads)

### Issue description

Expected result: Dividing any number by 2 in a float form, even if casted as an int, should result in a number typed as a float.
Actual result: Dividing an int with an int results in an int.

https://github.com/godotengine/godot/assets/102369191/fafe4d4d-8a47-43b6-866c-5b294ce84014

It sounds stupid on paper to expect a float when dividing with ints, however these forms are typed as float. So it would naturally be expected that there won't be any ints in there. While it can easily by circumvented by casting one of the numbers as a float, it is more convenient for the user to have all numbers be typed as a float, even if they are written as ints.

### Steps to reproduce

1. Select any Node with a float form.
2. Insert an int and divide by an int (e.g. `1 / 2`)
3. Output becomes a rounded down int

### Minimal reproduction project (MRP)

No reproduction project needed. Any node with a float form will do

**Comment by AThousandShips** [comment]
You need to enter it as `1 / 2.0`, this is by design, see:
* https://github.com/godotengine/godot/issues/25856
* https://github.com/godotengine/godot/issues/49579

Etc.

There are proposals relating to this, consolidating there as this is not a bug:
* https://github.com/godotengine/godot-proposals/issues/5344
* https://github.com/godotengine/godot-proposals/issues/1888
