### ISSUE TITLE
editor ignores the option "run/output/always_close_output_on_stop"

### ISSUE THREAD

**Issue by marcosdon** [godotengine/godot#92604]
### Tested versions

- reproducible in: v4.3.beta1.official [a4f2ea91a]

### System information

Godot v4.3.beta1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 (NVIDIA; 31.0.15.5244) - AMD Ryzen 5 2600X Six-Core Processor (12 Threads)

### Issue description

The editor ignores the option "run/output/always_close_output_on_stop" and always keeps the output panel open after stopping the game,

### Steps to reproduce

Set the option to true, run the game, and stop the game

### Minimal reproduction project (MRP)

[output_panel_test.zip](https://github.com/user-attachments/files/15518235/output_panel_test.zip)

**Comment by akien-mga** [comment]
I believe this is because https://github.com/godotengine/godot/pull/91033 removed this option and unified it into a new, more flexible one.

Godot doesn't automatically remove obsolete editor settings from your config, so it's still visible in your settings, but not actually used. If you click the revert button it should be removed.

**Comment by marcosdon** [comment]
It worked! Thanks. I'm not sure if the issue should simply be closed or marked irrelevant or another option...

**Comment by akien-mga** [comment]
It can be closed, and then we typically mark it as `archived` to mean this was not an actual bug. But it's still useful for other users who might search those keywords if they face the same issue.
