### ISSUE TITLE
Regex fails to return an object under a certain condition

### ISSUE THREAD

**Issue by wyattbiker** [godotengine/godot#92660]
### Tested versions

v4.3.dev5.official [c9c17d6ca]

### System information

Linux Kubuntu 23.04 KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8

### Issue description

The RegEx pattern below should not crash the application. It should return an object. Instead it returns null.
The pattern in this case is to match a Semver. So 4.5.6 should return 3 groups, and 4.5.X should return 2 groups. Instead the latter one crashes and returns nothing.

Pattern r" (?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+) "	

Version 3.4.9 SomeApp  -- gives 3 groups matches full
Version 3.4 SomeApp -- gives 2 groups
Version 3.4.X SomeApp -- returns null object

See code below

### Steps to reproduce

```gdscript
extends Control
const pattern=r" (?:(\d+)\.)?(?:(\d+)\.)?(\*|\d+) "	

func _ready():
	
	var ver:=[	"Version 3.4.9 SomeApp", \
				"Version 3.4 SomeApp", \
				"Version 3.4.X SomeApp"]
				
	var regex = RegEx.new()
	regex.compile(pattern)
	
	# crashes on the 3rd item above
	for each_ver in ver:
		var version_match=regex.search(each_ver)
		var groups=version_match.get_group_count()
		print(each_ver, groups)

```

Link to regex101 online evaluator [Link](https://regex101.com/r/L8M0Zf/4)

### Minimal reproduction project (MRP)

see code above. create a Control node and attack script above and run it.

**Comment by aaronp64** [comment]
I think regex.search returning null is expected here.  The pattern in the gdscript example requires a space after a "*" character or a number, which doesn't appear in "Version 3.4.X SomeApp".  The linked regex101 example doesn't include the space at the end - adding it will cause it to also not match "Version 3.4.X SomeApp".  Maybe `.` (or specific characters you're looking for) instead of `\*` would work for the last group?

**Comment by wyattbiker** [comment]
Noted. Thank you!. Closing.

**Comment by wyattbiker** [comment]
Noted. Thank you!. Closing.
