### ISSUE TITLE
How can i know the error in godot 3 on mobile?

### ISSUE THREAD

**Issue by NoorShroom** [godotengine/godot#92686]
### Tested versions

I use godot 3 for mobile (I download it from play store)

### System information

Redmi 12C - godot 3

### Issue description

I am really tierd using godot on my phone,
when i test my project and it has error, I can't know the error,Because godot crashes when testing it, mobile users you understand me. Please i really wanna help.

### Steps to reproduce

---

### Minimal reproduction project (MRP)

--

**Comment by matheusmdx** [comment]
For debug android crashes you need to use adb logcat, and an advice, here is to report bugs, you need to explain what is happening, the steps, show how to reproduce, this report looks more a forum post asking for help than a bug report so take care or mods will just close your issue

**Comment by Calinou** [comment]
Please upload a minimal reproduction project[^1] to make this easier to troubleshoot.

[^1]: A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).<br><br>Drag and drop a ZIP archive to upload it. **Do not select another field until the project is done uploading.**<br><br>**Note for C# users:** If your issue is *not* Mono-specific, please upload a minimal reproduction project written in GDScript or VisualScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a Mono setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
