### ISSUE TITLE
Hot Reload broken in Godot 4.3 beta 1

### ISSUE THREAD

**Issue by m4gr3d** [godotengine/godot#92695]
### Tested versions

- Reproducible in Godot 4.3 beta 1
- Not reproducible in Godot 4.3 dev 6

### System information

Tested and reproduced on Windows 11 and Android 14

### Issue description

Hot reload no longer works when running a project with `Synchronize scene changes` and `Synchronize script changes` enabled.

### Steps to reproduce

- Create a project 
- Enable `Synchronize scene changes` and `Synchronize script changes`
- Run the project and in the editor window toggle the visibility of node elements
- Notice that in Godot 4.3 beta 1, the running project is not updated, while it's in Godot 4.3 dev 6

### Minimal reproduction project (MRP)

N/A: affects all projects

**Comment by matheusmdx** [comment]
Bisecting points to #92350 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/fd87a35f-0917-487a-82b9-17b422568d27)

**Comment by akien-mga** [comment]
CC @4d49 @KoBeWi

**Comment by matheusmdx** [comment]
Ok, i did some experiments here and what is happening:

First, hot reloading doesn't entire fails to work, if you change the properties in the inspector they will apply in game as expected. but if you drag and drop, rotate, change visibility, etc, outside the inspector, the hot reload fails


https://github.com/godotengine/godot/assets/44306054/1b539e94-aa59-4318-9798-6947bee4d697

<br>
<br>

Before #92350 `UndoRedo` used the `Callable.get_method()` as the `do/undo_op.name`  and static_cast<String> only as fallback for custom callables:

https://github.com/godotengine/godot/blob/83b916bb00eb8cac4584143a80f5cfad7ce1e908/core/object/undo_redo.cpp#L162-L166

But thats made #90430 happens because lambdas raise a error if `Callable.get_method()` is used, so #92350 now checks for `Callable.is_custom()` and if is true, do a static cast to string of the callable as the `do/undo_op.name` instead the `Callable.get_method()` result

https://github.com/godotengine/godot/blob/705b7a0b0bd535c95e4e8fb439f3d84b3fb4f427/core/object/undo_redo.cpp#L162-L167

And as you can see in the video above, all the callables return true for `is_custom()` (the lines that start with "4") and that fails to work with hot reloading when the callable is from a Node  (why i don't know)

<br>

That callables hot reload using the static cast result (the callables from editing properties from inspector):

Callable: EditorInspector::emit_signal
Get method result: emit_signal
Static cast result: EditorInspector::emit_signal

Callable: EditorInspector::_edit_request_change
Get method result: _edit_request_change
Static cast result: EditorInspector::_edit_request_change

<br>

That callables fail to hot reload using the static cast result (the callables from drag and drop, click the eye buton in scene tree, etc)

Callable: Node2D::set_visible
Get method result: set_visible
Static cast result: Node2D::set_visible

Callable: ColorRect::_edit_set_state
Get method result: _edit_set_state
Static cast result: ColorRect::_edit_set_state

<br>

So the options to solve this problem is:

1: Downgrade the error emited by `Callable.get_method()`  when is called from a lambda to a warning and return `StringName()`, so we can revert #92350 
2: Fix the problem that make the node callables fail, after all the editor ones work as expected
3: If `Callable.is_custom()` is wrongly returning true when wasn't to be, fix that

If none of the above can be done, i have a totally not workaround solution:  
```
	String callable_string = static_cast<String>(p_callable);
	// The lambda static cast result is lambda_name(lambda) or 
	// <anonymous lambda>(lambda) so...
	if (p_callable.is_custom() && callable_string.count("(lambda") != 0) {
		do_op.name = callable_string;
	} else {
		do_op.name = p_callable.get_method();
	}
	// You can question my methods, but can't question my results, that works after all!
```

Probably this has another (better) solutions but that is what my limited knowledge allowed me to get, at least to give some direction of what is happening

**Comment by 4d49** [comment]
Hello. First of all, I would like to apologize that my fix led to such a serious problem 😥

I've been researching the problem for a while and have come to some conclusions. The problem really is my fix. Debugger uses the method names from `UndoRedo` to call methods in the application instance. And my fix broke that... Sorry.

If we call `bind` on a `Callable` object, it starts to be considered as `custom`. So as a possible solution we can add a check if `Callable` is binded.

```c++
if (p_callable.is_custom()) {
	const CallableCustomBind *bind = dynamic_cast<CallableCustomBind *>(p_callable.get_custom());
	// Check if CallableCustom is bind.
	if (bind != nullptr) {
		do_op.name = bind->get_method();
	} else {
		do_op.name = static_cast<String>(p_callable);
	}
} else {
	do_op.name = p_callable.get_method();
}
```

**Comment by KoBeWi** [comment]
What if we add something like `is_named()` or `has_name()` to Callable? 🤔

**Comment by 4d49** [comment]
Also I think the `get_method` function should be pure virtual functions like the other functions in the `CallableCustom` class.
https://github.com/godotengine/godot/blob/83b916bb00eb8cac4584143a80f5cfad7ce1e908/core/variant/callable.cpp#L440-L442

This function is overridden in almost all inherited classes except `ManagedCallable`.

**Comment by 4d49** [comment]
> What if we add something like `is_named()` or `has_name()` to Callable? 🤔

I also think it would be nice to add an `is_binded` method to `Callable`.

**Comment by akien-mga** [comment]
Thanks for the investigation!

For now I'll revert #92350 which seems to be the safer approach for 4.3.

We can then explore the other approach to keep the improvement from #92350 while addressing the regression in a new PR, for 4.4.
