### ISSUE TITLE
AnimationTree: BlendSpace2D blending sync not working correctly

### ISSUE THREAD

**Issue by jclc** [godotengine/godot#92730]
### Tested versions

- Reproducible in: v4.3.beta1.official [a4f2ea91a]

### System information

Linux - Godot 4.3 beta 1 - Vulkan (Forward+)

### Issue description

I have a 3D rig with running animations that I am blending together with a BlendSpace2D. In 4.2 this worked but after upgrading to 4.3 beta 1 this has been completely broken.

None of the sync or loop options are respected, instead moving from one blend triangle to another will always reset the animation in the newly activated blend positions.

What it's more or less supposed to look like:
![blend-expected](https://github.com/godotengine/godot/assets/10243558/489035bb-2f33-4381-a06b-399481b77aa9)

After moving the blend position to the right and back to the previous position, this is what it might look like:
![blend-bugged](https://github.com/godotengine/godot/assets/10243558/65701cd6-ea50-48cb-8c12-094fe08e195d)

I've tried using the Sync option and all of the custom timeline options, but none of them seem to fix this.

Here's what the blend space looks like:
![blend-space](https://github.com/godotengine/godot/assets/10243558/b4827e10-0449-4e91-8851-d146a95f9967)

### Steps to reproduce

Add an AnimationTree node and link it with an AnimationPlayer node with at least 4 animations. Create blend positions like the shown with the top 2 triangles in the image above. Configure them to synchronise animations, then move the blending position between the triangles and observe non-synchronised behaviour.

### Minimal reproduction project (MRP)

[blendspace2d-issue.zip](https://github.com/user-attachments/files/15536880/blendspace2d-issue.zip)
Issue can be demonstrated by running the project and running diagonally forward and switching directions. After landing from a jump the blended animations are in sync as they're supposed to be, but will be skewed the moment you move in the other direction.

**Comment by TokageItLab** [comment]
Sorry, it is my mistake in refactoring as https://github.com/godotengine/godot/pull/87171.
I sent a fix https://github.com/godotengine/godot/pull/92739, please check it if you can.

**Comment by FacuDellaRosa** [comment]
Hello. I am still reproducing this bug, I'm using the latest Godot 4.3 version, and I also tried it in version 4.2 and is still blending animations wrong. I think the problem still is becouse of different length of the animations. Anyone else still have this problem?

**Comment by TokageItLab** [comment]
@FacuDellaRosa Make sure that your all animation lengths to be blended are aligned and that the syncs of the Nodes before and after the BlendSpace are not broken.

**Comment by FacuDellaRosa** [comment]
@TokageItLab Oh I understad... I thought the Sync checkbox would handle those length differences automatically... Ok, thank you for the response!

**Comment by Cthutq295** [comment]
I have simillar issue and it exists since 4.2.2. Character animations and some point stop blending correctly.
So, basically if I rotate my character slowly without changing moving direction you can see that at some point blending breaks (0:19) and once i stop moving (or start running with SHIFT) and start moving again (without changing movement and look direction) animation will start working fine. You can also see in the output log that blend position doesn't change at all, so it can't be that I pass incorrect blending position values.
 https://github.com/user-attachments/assets/3ac06f94-6f8b-48e3-9517-2b307284baeb
[ReproductionProject.zip](https://github.com/user-attachments/files/17892791/ReproductionProject.zip)

**Comment by TokageItLab** [comment]
@Cthutq295 The Sync option is disabled in MRP, is it also disabled in the video and is that intentional?
![Image](https://github.com/user-attachments/assets/e86b10b3-503d-4d1e-ae9f-953ac96c1585)

As long as the animation lengths are consistent and there is no problem with the timing of the first foot, just the Sync option should solve the problem. Otherwise, the CustomTimeline option should be used to adjust the length of the animation and the offset to adjust the timing of the first foot, but basically the existing features provide a solution.

![Image](https://github.com/user-attachments/assets/c58a5f72-7436-453b-a34d-ef235e886e7c)
