### ISSUE TITLE
compile arch86 for iOS failed (etc2comp build issue)

### ISSUE THREAD

**Issue by bartalluyn** [godotengine/godot#9273]
**Operating system or device - Godot version:**

MacOS Sierra

**Issue description:**

When compiling with 

scons p=iphone arch=x86 target=debug

the following errors were produced 

please advise

thanks

thirdparty/etc2comp/Etc.h:38:8: error: no type named 'shared_ptr' in namespace 'std'
                std::shared_ptr<unsigned char> paucEncodingBits;
                ~~~~~^
thirdparty/etc2comp/Etc.h:38:18: error: expected member name or ';' after declaration specifiers
                std::shared_ptr<unsigned char> paucEncodingBits;
                ~~~~~~~~~~~~~~~^
thirdparty/etc2comp/Etc.cpp:99:25: error: no member named 'paucEncodingBits' in 'Etc::RawImage'
                        a_pMipmapImages[mip].paucEncodingBits = std::shared_ptr<unsigned char>(image.GetEncodingBits(), [](unsigned char *p) { delete[] p; });
                        ~~~~~~~~~~~~~~~~~~~~ ^
thirdparty/etc2comp/Etc.cpp:99:49: error: no member named 'shared_ptr' in namespace 'std'
                        a_pMipmapImages[mip].paucEncodingBits = std::shared_ptr<unsigned char>(image.GetEncodingBits(), [](unsigned char *p) { delete[] p; });
                                                                ~~~~~^
thirdparty/etc2comp/Etc.cpp:99:69: error: expected '(' for function-style cast or type construction
                        a_pMipmapImages[mip].paucEncodingBits = std::shared_ptr<unsigned char>(image.GetEncodingBits(), [](unsigned char *p) { delete[] p; });
                                                                                ~~~~~~~~ ^
5 errors generated.
**Steps to reproduce:**

just compile with args mentioned

**Link to minimal example project:**
<!-- Optional but very welcome. You can drag and drop a zip archive to upload it. -->

**Comment by BastiaanOlij** [comment]
Hey @bartalluyn , 

Is this for Godot 2.1? I'll see if I can reproduce the same here

**Comment by vnen** [comment]
Must be master, etc2comp is not present in 2.1.

**Comment by BastiaanOlij** [comment]
@vnen well that could explain it. It currently only compiles for 64bit and doesn't even run at the moment, still hoping we get there soon because I want to start on ARKit support.

At this time I'm not even sure if we can keep 32bit support, we're starting to use APIs that are only available in the later versions of the OS which only run on the 64 bit devices. Though I did recently learned this put iPhone 5C's at risk (last of the 32bit iPhones). 
iPhone 5, and iPhone 5S are both 64bit phones as are anything after that.

Pretty sure Apple will start dropping support for the 5 soon anyway with iOS 11 coming out end of the year and probably an iPhone 8 next year and iPhone 4's don't even run the latest iOS.

**Comment by bartalluyn** [comment]
Hi,
I took the 2.1 branch, and that indeed did the trick.  Everything went well, but when I copied over the executable and changed the executable name in the pList it told me I didn't have permissions.  Any idea here?

**Comment by akien-mga** [comment]
CC @tagcup, I guess the C+11 definition doesn't work in some cases/with some compilers.

**Comment by vnen** [comment]
Wait, I think etc2comp is only needed in tools builds. It should be disabled for iOS.

**Comment by tagcup** [comment]
@akien-mga Yeah, seems that way, although just like @vnen said, this is similar to Android situation and etc2comp should be disabled for iOS
