### ISSUE TITLE
Debugger window has massive delay after resize/move, and then alt-tabbed back and forth.

### ISSUE THREAD

**Issue by hydescarf** [godotengine/godot#92759]
### Tested versions

- Reproducible: 4.3.dev6, 4.3.beta1
- Non-reproducible: 4.2.2, 4.3.dev5

### System information

Windows 11

### Issue description

(Probably need a better title)
If you run the scene in the Editor (F5/F6), everything's working as usual. But the moment you move or resize (and sometimes just idling), then focus/alt-tab back to Editor and then back to Running Scene, the delay starts. (See video for better conveying)

Notice on the on-screen key pressed, and the movement (and console output) on the scene.

https://github.com/godotengine/godot/assets/56707567/2e3daffd-2e4e-457e-9024-e9ca34a76c32

This was tested on both Windows 10 (old laptop spec) & 11 (rather modern pc spec), and only happens after 4.3.dev6.

### Steps to reproduce

1. Create a script with left/right movement for a Sprite2D. (or anything else I assume)
2. Run the scene and move. (working as usual)
3. Move or resize the window, then focus on Editor, then refocus back on the Running Scene.
4. Move the sprite again. (delay occurs)

(Pressing on a button also does the same thing, so it's not related to the keyboard itself)

### Minimal reproduction project (MRP)

N/A, since it also happens on new project.

**Comment by matheusmdx** [comment]
Bisecting points to #91361 as the culprit:

![image](https://github.com/godotengine/godot/assets/44306054/98f8771c-6ea2-4d79-960f-2a7c5286ec4b)

Also, this is issue was similar to #92307 so i used the same steps to try reproduce and worked (i wasn't able to reproduce that issue before) so that explains why #92307 was so hard to replicate, the same method works to easily reproduce #92304 and #92305 but using alt+tab to focus another window. The funny part is pr #92742 that was made to fix #92304 and #92305 (and these two was already fixed by #92415) actually fixes this issue and #92307

**Comment by hydescarf** [comment]
Interesting. I was thinking of linking #92304 to this as I had the same problem, but was unable to reproduce it through moving the debugger windows & alt-tabbing. (Though it works if it's between Editor and other applications)
Also as mentioned in the first post, idling the debugger while coding sometimes may cause the issue as well, but I didn't actively try to replicate that and could be misremembering.

Commenting these in, just in case. Hopefully that fix will cover that as well.
