### ISSUE TITLE
Signal can't be connected to variable setter.

### ISSUE THREAD

**Issue by addmix** [godotengine/godot#92782]
### Tested versions

4.2.2 stable

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 31.0.22023.1014) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

Signals can't be connected to setter functions.

NodeA has signal `bool_signal`, which has the parameter value, which is a bool.
NodeB has variable `my_bool`, static typed as bool, with a setter.

When attempting to connect NodeA's `bool_signal` to NodeB's `my_bool_setter` function, the warning "Method name must be a valid identifier." is given.

![image](https://github.com/godotengine/godot/assets/38119387/8dfd15c4-fc43-45b0-8e4c-61d3a295945e)

![image](https://github.com/godotengine/godot/assets/38119387/eab0c89b-764d-41d7-8ff1-77198fa70cb9)

### Steps to reproduce

Create a signal with a type declaration.
Create variable with a setter.
Attempt to connect signal to setter.

### Minimal reproduction project (MRP)

[minimal.zip](https://github.com/user-attachments/files/15579927/minimal.zip)

**Comment by AThousandShips** [comment]
You probably need to make the setter a separate method, like so:
```gdscript
var my_bool : bool = false:
	set = set_my_bool

func set_my_bool(x):
	my_bool = x
```

**Comment by addmix** [comment]
Would be nice to avoid the boilerplate, but definitely odd that it lists the setter as if it were a real function. I feel like I remember at one point in the 4.0 alpha you could call these setters and getters like normal functions, so maybe it's not far from the realm of possibility?

**Comment by AThousandShips** [comment]
You can call them with `call` but not directly as they're treated like an annotation, I don't know if it's intentional that they are accessible, or if the restriction on method names in the connection is too strict

**Comment by dalexeev** [comment]
I think inline setters/getters were not intended to be listed in `get_method_list()` and be invokable via `call()`. However, for historical reasons this is the case, you can do `call("@my_var_setter", 123)`. Now we have the following options:

1\. Break compatibility.
1.1. Skip `@methods` in `get_[script_]method_list()` and `callp()`. Make sure that the runtime is not broken.
1.2. Move inline setters/getters from `member_functions` to a separate hashmap, similar to how `implicit_initializer` and several other special functions are stored in separate variables rather than in `member_functions`. Make sure that the compiler and runtime are not broken.
2\. Keep compatibility.
2.1. Hide `@methods` in the editor (Connection Dialog and Method Selector).
2.2. Allow `@methods` in the editor even though they are not valid identifiers.
