### ISSUE TITLE
godot 4.2.2  performance in big tileSet

### ISSUE THREAD

**Issue by MAXFROMCODE** [godotengine/godot#92788]
### Tested versions

4.2.2 stable

### System information

win11 godot 4.2.2 stable cpu-amd 8845hs gpu 780m

### Issue description

if start godot with nothing ,open a tile_set (has many tile),godot will has low fps;
but if start godot 4.2.1 and close 4.1.1,then start godot 4.2.2,the tileset will be ok；
one more thing godot has low fps ,gpu-copy will has data,
godot is ok,gpu-cop is 0,my pc is win 11 ,cpu is amd 8845hs gpu is 780m
i upload my use png i hope it will be useful
ok:
![1717582917528](https://github.com/godotengine/godot/assets/142991584/97c3d4a6-5b5b-4285-9101-bdcfd922b7b0)
low fps :
![1717583010617](https://github.com/godotengine/godot/assets/142991584/25e7088a-2b68-4a25-8d80-d435958e6868)

### Steps to reproduce

1、start godot 4.2.2 and create a tileset has a many tile png ;
2、godot has low fps
3、open 4.2.1 and close 4.2.1, then start 4.2.2;
4、tileset will be ok

### Minimal reproduction project (MRP)

![1717583010617](https://github.com/godotengine/godot/assets/142991584/5c5477da-975f-4c68-bd44-a90969452fad)

**Comment by MAXFROMCODE** [comment]
sorry ,i upload a wrong tile png ,i dont's know can i upload this png without author‘s permission，but i think other tile png is  same.because my other big tile png is same

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by MAXFROMCODE** [comment]
[demo.zip](https://github.com/user-attachments/files/15603285/demo.zip)
this is a demo with a tileset

**Comment by MAXFROMCODE** [comment]
suggest try more times,it's in my pc (amd 8845hs godot4.2.2,it has low fps)

**Comment by Calinou** [comment]
I can't reproduce this on 4.2.2 or 4.3.beta1 with the following specs:

<details open>

<summary>PC specifications</summary>

- **CPU:** Intel Core i9-13900K
- **GPU:** NVIDIA GeForce RTX 4090
- **RAM:** 64 GB (2×32 GB DDR5-5800 C30)
- **SSD:** Solidigm P44 Pro 2 TB
- **OS:** Linux (Fedora 39)
</details>

Can you reproduce this after switching the project to use the **Compatibility** rendering method in the top-right corner of the editor?
