### ISSUE TITLE
CanvasModulate color too bright when using 2D HDR

### ISSUE THREAD

**Issue by reimgrab** [godotengine/godot#92796]
### Tested versions

Reproducible in 4.2.2
Not reproducible in 3.x

### System information

Godot v4.2.2.stable.mono - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (nvidia; 535.171.04) - Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 Threads)

### Issue description

When using a CanvasModulate with 2D HDR enabled the modulate color is too bright.
Modulate color 1, 1, 1, 255:
![cm](https://github.com/godotengine/godot/assets/11878694/2084cd97-1824-4acc-83c1-7446d4062428)

The color should be converted to linear space to get similar results to a CanvasModulate without 2D HDR enabled.

### Steps to reproduce

-Add Sprite to project
-Add CanvasModulate to project
-Set modulate color to anything besides pure black or white
-Compare 2D HDR enabled to disabled

### Minimal reproduction project (MRP)

[cm_mrp.zip](https://github.com/user-attachments/files/15586703/cm_mrp.zip)

**Comment by Calinou** [comment]
Can you test the latest `master` branch, now that https://github.com/godotengine/godot/pull/92444 was merged?

**Comment by reimgrab** [comment]
Not fixed in v4.3.beta.custom_build [e96ad5af9].

**Comment by Calinou** [comment]
cc @clayjohn

**Comment by clayjohn** [comment]
As the OP says, the canvas_modulate just needs to be converted to linear in `canvas_render_items()` before it is passed to the shader

**Comment by feiyue-z** [comment]
I tried to convert the values in CanvasModulate from sRGB to linear but then I got this seemingly weird result.
I'm new to the project and I'm not quite sure if this is the expected behavior:
2D HDR **off**
<img width="1782" alt="Screenshot 2024-06-25 at 7 00 18 PM" src="https://github.com/godotengine/godot/assets/144282960/04ef3382-5269-4aa9-a224-fedc7b101162">
2D HDR **on**
<img width="1782" alt="Screenshot 2024-06-25 at 6 58 32 PM" src="https://github.com/godotengine/godot/assets/144282960/a4737d14-8bbb-4136-b46e-d569e001ef5d">

**Comment by reimgrab** [comment]
Have you restarted the editor after switching to HDR?
