### ISSUE TITLE
Script editor wrongly replaces and quotes non-ASCII letters

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#92899]
### Tested versions

4.3 beta1 and earlier

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

https://github.com/godotengine/godot/assets/2223172/735a81e3-5bf7-419e-991e-32af57003fbd

The non-ASCII letters are replaced with `_`, while they make a valid identifier. Also the path is quoted, but it works without the quote.

### Steps to reproduce

1. Have a node with some accented letters in name, like `bułka`
2. Drag and drop it to script editor while holding Ctrl
3. The line ends up as `@onready var bu_ka = $"bułka"`
4. Change it to `@onready var bułka = $bułka`
5. It still works, so the identifier processing was unnecessary

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
This is because `validate_identifier()` is used.

https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/editor/plugins/script_text_editor.cpp#L1939-L1952

https://github.com/godotengine/godot/blob/5833f597865c773fae3ee09fc4e31d4a243f812d/core/string/ustring.cpp#L4469-L4490
