### ISSUE TITLE
NavigationRegion2D polygon baking stacks 'visually' and 'Clear NavigationPolygon' is not working

### ISSUE THREAD

**Issue by pmoosi** [godotengine/godot#92987]
### Tested versions

- Reproducible in v4.3.beta.mono.custom_build [bb5f75496] and v4.3.beta1.official [a4f2ea91a]
- Not reproducible in v4.2.2

### System information

Godot v4.3.beta.mono (bb5f75496) - Ubuntu 22.04.4 LTS 22.04 - Wayland - Vulkan (Forward+) - integrated AMD Unknown (RADV RENOIR) () - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

I encountered a minor bug while trying to bake the navigation polygon of a NavigationRegion2D in the Editor. 
When baking, the navigation polygon is added instead of replaced. This seems to be only visual since a scene reload displays it normally. 
Also, the 'Clear NavigationPolygon' button does not do anything anymore (maybe also only 'visually'). It feels like that might be related.

### Steps to reproduce

In the MRP select the NavigationRegion2D and click on 'Bake NavigationPolygon' multiple times. Every time a new layer is added. Clicking 'Clear NavigationPolygon' does nothing.

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/15775881/mrp.zip)

**Comment by smix8** [comment]
There are 2 issues.

The regression is that the recently added mesh debug does not clear the canvas item in all cases.

An older issue is that NavigationPolygon does not trigger its changed signal under all conditions.

The problem is that there is a tangle-web of signal related issues with this legacy NavigationPolygon resource. Adding changed signals to most functions that do alter the resource is actually a problem for both performance and even more horrendous bugs.
