### ISSUE TITLE
Can't reopen signals panel immediately after connecting a signal

### ISSUE THREAD

**Issue by anniryynanen** [godotengine/godot#92996]
### Tested versions

- Reproduces in v4.3.beta1.official [a4f2ea91a]
- Doesn't reproduce in v4.3.dev6.official [89850d553]

### System information

Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 31.0.24027.1012) - AMD Ryzen 7 5700X3D 8-Core Processor (16 Threads)

### Issue description

After a signal is connected, the signals panel becomes empty. This I'm used to, but when I try to reopen it for the same node by clicking it in the scene tree, nothing happens. I can only reopen the signals panel for the same node after unselecting and reselecting it.

On a side note, why does the signals panel forget the node after connecting a signal? If it's not necessary, it'd be nice if it didn't.

### Steps to reproduce

- Select a node in the scene tree
- Open the signals panel
- Connect any signal
- Try reopen the same signals panel by clicking the same node in the scene tree

### Minimal reproduction project (MRP)

N/A

**Comment by matheusmdx** [comment]
> On a side note, why does the signals panel forget the node after connecting a signal? If it's not necessary, it'd be nice if it didn't.

This is also a regression, the editor was like that in godot 4.2.1

<br>

The culprit from this issue is #91435 and the signal tab hiding after connect a siginal culprit is commit 8633f7bc from pr #87589:

![image](https://github.com/godotengine/godot/assets/44306054/6deab77a-2da2-4e56-8acd-4d4823152c8c)

![Captura 2024-06-12 07-15-21-813231](https://github.com/godotengine/godot/assets/44306054/8d4f2609-81d5-4fe9-a718-7ca5f185ba07)
