### ISSUE TITLE
NinePatchRect doesn't seem to work at all

### ISSUE THREAD

**Issue by TheLegoSensei** [godotengine/godot#93002]
### Tested versions

v4.2.2.stable.official [15073afe3], v4.1.1.stable.official [bd6af8e0e]

### System information

Godot v4.2.2.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce 940M (NVIDIA; 31.0.15.5123) - Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 Threads)

### Issue description

the NinePatchRect simply doesn't seem to do it's job at all, expecting behavior like it worked in Godot v3.5.3.stable.official [6c814135b]. it can fill the center but the edges are just gone. I first noticed it in the compatability renderer and tried switching to forward plus and it was still happening. 

### Steps to reproduce

create a NinePatchRect node, set it's region, and grab it's handles to move it around, on my machine I don't see the edges like I'd expect from Godot 3.x

### Minimal reproduction project (MRP)

[NinePatchTest.zip](https://github.com/user-attachments/files/15779271/NinePatchTest.zip)

**Comment by aaronp64** [comment]
It looks like the sample project doesn't show the edges because the region rect only includes the center of the image.  The region rect represents the full area that gets used, so in this case it should be the full image ((0, 0, 16, 16), or just (0, 0, 0, 0) and let it default to the full image).  The patch margin fields below the region rect can then control how much of the region rect represents the sides, looks like 5 for all in this case.

The region editor display feels a little confusing in this case, with the default margins all at 0, since it looks like it's dividing the area around the rect instead of inside it

**Comment by TheLegoSensei** [comment]
oh I see now! sorry for reporting an issue when it was user error.
