### ISSUE TITLE
duplicate(true) losses reference to custom data type

### ISSUE THREAD

**Issue by GitHubPiotr** [godotengine/godot#93065]
### Tested versions

Tested on Godot 4.3beta1

### System information

Windows 10, Forward+

### Issue description

Hi, 
I'm not sure it's a bug but when I tried to assign duplicated custom class to varaible with the same type I got error:

![x3](https://github.com/godotengine/godot/assets/60047367/bdaafcb6-0791-4691-94c2-f138ad0e1c58)

Error occurs only with true parameter.

### Steps to reproduce

1. Create a custom class
![x1](https://github.com/godotengine/godot/assets/60047367/1605685e-c4f7-4dd3-82cd-4af7433ec570)
2. Create new object of the custom class (with typing) and assign it to another variable(with the same type) using duplicate(true)
![x2](https://github.com/godotengine/godot/assets/60047367/8363c18b-e8f8-4adb-acfa-46ae975a9293)
3. Run the project

### Minimal reproduction project (MRP)

[test.zip](https://github.com/user-attachments/files/15796542/test.zip)

**Comment by aaronp64** [comment]
It looks like `Node.duplicate` takes an int (based on `DuplicateFlags` enum) rather than bool, so `duplicate(true)` is the same as calling `duplicate(DuplicateFlags.DUPLICATE_SIGNALS)`  The default argument is 15, which includes `DuplicateFlags.DUPLICATE_SCRIPTS`.  Without `DuplicateFlags.DUPLICATE_SCRIPTS`, the script information won't be copied to the duplicated node, so it won't be a `MyCustomClass`.

**Comment by AThousandShips** [comment]
Closing as per the above, if you still are having problems when using the method with the correct argument please open a new issue
