### ISSUE TITLE
static type arrya cannot understand extends(subclass)

### ISSUE THREAD

**Issue by AkiYama-Ryou** [godotengine/godot#93063]
### Tested versions

godot 4.2.2 statble

### System information

windows 10

### Issue description

**godot support OOP, so we can extend class :But it seem like gotdot cannot understand class in container**

Im not sure is this a feature?

### Steps to reproduce

I have class A and B. Class B extend from A.
var a:A
var b:B
a=b
**but this cannot pass:**
var a:Array[A]
var b:Array[B]
a=b
error:Value of type "Array[B]" cannot be assigned to a variable of type "Array[A]"

### Minimal reproduction project (MRP)

N/A

**Comment by dalexeev** [comment]
See:

* [GDScript reference - Typed arrays](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_basics.html#typed-arrays)
* #83876
* godotengine/godot-proposals#7364

![](https://github.com/godotengine/godot/assets/47700418/f75cea69-5544-40df-b111-f798cdb32901)

This is not a bug. Arrays are passed by reference; they do not copy the entire content. Otherwise you would get:

```gdscript
var a: Array[Node2D]
var b: Array[Node]
b = a # Now `b` refers to the same array as `a`.
b.append(Label.new()) # Valid, `Label` is a subtype of `Node`.
print(a[0]) # Invalid, `Label` is **not** a subtype of `Node2D`.
```

Probably the only way this would work is if the GDScript supported [`read`/`write` qualifiers](https://github.com/godotengine/godot-proposals/discussions/7364#discussioncomment-6576975). But it's too difficult.

Thanks for the contribution nonetheless!

**Comment by AkiYama-Ryou** [comment]
Thank you for explaining.
