### ISSUE TITLE
Restarting game freezes entire system

### ISSUE THREAD

**Issue by SeanRamey** [godotengine/godot#93109]
### Tested versions

This is for 4.3.beta1.

### System information

Godot v4.3.beta1 - EndeavourOS #1 SMP PREEMPT_DYNAMIC Fri, 31 May 2024 15:14:45 +0000 - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2080 SUPER (nvidia; 550.78) - Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 Threads)

### Issue description

When I click the restart game button while the game is running, it completely freezes my entire system until the game restarts. It also shuts down recording with software like OBS. I tried to make a video, but the last thing recorded is right when the system freezes.

Also of note is that I upgraded my game from 4.2.2 to 4.3.beta1.

https://github.com/godotengine/godot/assets/3057229/41d66bb9-5b57-4c0d-82ab-520dbbeff68f

### Steps to reproduce

Start game, then restart it.

### Minimal reproduction project (MRP)

I don't have one as of yet.

**Comment by matheusmdx** [comment]
I can't reproduce the issue here with the projects i have so probably is something specific in your game, without a mrp will be hard do something

**Comment by AThousandShips** [comment]
Indeed please upload an MRP:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available. 

Also your video is broken for at least me

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
