### ISSUE TITLE
ERROR: The Image width specified (0 pixels) must be greater than 0 pixels.

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#93151]
### Tested versions

v4.3.dev6.mono.official [89850d553]

### System information

Godot v4.3.dev6.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 5GB (NVIDIA; 31.0.15.3623) - AMD Ryzen 9 3900X 12-Core Processor (24 Threads)

### Issue description

It report error when start project:
![image](https://github.com/godotengine/godot/assets/35988767/f2b4a7bd-abbb-4c9c-9210-3d67e8c745c6)
Note: it only report in the console, the Editor's output no error print.

### Steps to reproduce

just start the MRP.

### Minimal reproduction project (MRP)

[ddstest.zip](https://github.com/user-attachments/files/15834737/ddstest.zip)

Other steps:
1. create a project.
2. import a dds file.
3. create altastexture.
4. set atlastexture.texture with the dds
5. restart project with console

**Comment by AThousandShips** [comment]
Please try with [beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/) to make sure it's still present

**Comment by CsloudX** [comment]
> Please try with [beta1](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-1/) to make sure it's still present

Yes, it's still present.
![image](https://github.com/godotengine/godot/assets/35988767/a4bbe589-5375-4bdb-acee-8a65a7937825)

Note: for big project(about 2000 files). the Editor's output window will report this error too.

**Comment by akien-mga** [comment]
Confirmed in current `master` (680e489189796af2c34f06df49e19b17dec5c6fc) with the MRP.

You can solve it by actually giving a non-zero sized region to the AtlasTexture:

![image](https://github.com/godotengine/godot/assets/4701338/4f792224-b0df-4261-88dd-f883013ff6a8)

Which is probably what you'd want in this scenario anyway.

The problem is a UX issue, that the AtlasTexture is created with an empty region which triggers an error.

It's not specific to using a DDS file, the same happens with using `icon.svg` as the Atlas texture.

**Comment by CsloudX** [comment]
IMO, 2 tasks need to do:
1. it report error only in console, no in the output.
2. the error not make sense which file has error, need enhence.
