### ISSUE TITLE
Rotating a Sprite2D in the AnimationPlayer in v4.3.beta1 from 0 to 360 does not work

### ISSUE THREAD

**Issue by viraya** [godotengine/godot#93163]
### Tested versions

Reproduce in v 4.3.beta1. 
It does work in 4.2.2

### System information

Windows 11 - Godot 4.3.beta1

### Issue description

Sprite does not rotate from 0 to 360 degrees using the AnimationPlayer.

### Steps to reproduce

Using a Node2D with a Sprite2D and an AnimationPlayer as a child add the rotation as a track to the AnimationPlayer.
Add a tkey for the start and the end for lets say 0.5 seconds. 

Start key = 0 degrees
End key = 360 degrees.
Set replay true

Expectation: Rotates in circles.
Result: Stands still.

### Minimal reproduction project (MRP)

[MRP422.zip](https://github.com/user-attachments/files/15839003/MRP422.zip)
[MRP431.zip](https://github.com/user-attachments/files/15839004/MRP431.zip)

**Comment by viraya** [comment]
To work around this you can add a key in the middle on 180 degrees and set the last one to -360 degrees.

**Comment by AThousandShips** [comment]
I believe this is expected behavior as it will take the shortest path between the two values, and therefore not move at all, 360 degrees and 0 degrees are the same rotation 

Just to confirm does it also happen with, for example 359 degrees?

**Comment by viraya** [comment]
When using anything from 181 to 359 it will rotate the total amount in the opposite direction so 355 would be like a 5 degrees momvement in the opposite direction. 181 would be 179 in the opposite direction.

**Comment by viraya** [comment]
Not sure if this has to be a seperate issue but when you set the roation to anything but interpolation mode it just starts rotating uncontrolably.

**Comment by kleonc** [comment]
> Reproduce in v 4.3.beta1.
> It does work in 4.2.2

The behavior between the provided MRPs differs because of different interpolation modes:

[MRP422.zip](https://github.com/user-attachments/files/15839003/MRP422.zip)|[MRP431.zip](https://github.com/user-attachments/files/15839004/MRP431.zip)
-|-
![Godot_v4 2 2-stable_win64_cjT83SPuh0](https://github.com/godotengine/godot/assets/9283098/fcc20ff2-8346-4572-a7fd-25c537d64714)|![Godot_v4 3-beta1_win64_y1Jf7z2fRx](https://github.com/godotengine/godot/assets/9283098/bf9af6af-8eaf-408e-95cf-e125de8acc29)

Meaning both provided MRPs test the behavior for different settings, and hence different results are expected.

- For "linear" animating from 0 to 360 resulting in full circle rotation is correct.
- For "linear angle" animating from 0 to 360 resulting in no rotation is correct.

So I don't see incorrect behavior here.

---

What has changed between the versions is the default interpolation mode when creating the track for the `rotation` property. As in the MRPs:
- in v4.2.2.stable.official [15073afe3] it's "linear",
- in v4.3.beta1.official [a4f2ea91a] it's "linear angle".

It's changed since v4.3.dev2.official [352434668], seems intentinally introduced by #86630. @TokageItLab
