### ISSUE TITLE
LSP behaves differently in Neovim than other editors (Godot IDE and VS Code) 

### ISSUE THREAD

**Issue by zeljkobekcic** [godotengine/godot#93224]
### Tested versions

- Reproducible in 4.1.4, 4.2.2, 4.3.beta.1

### System information

Godot v4.1.4.stable - macOS 13.4.1 - Vulkan (Forward+) - integrated Apple M1 Pro - Apple M1 Pro (8 Threads)

### Issue description

The Godot LSP behaves incorrectly in Neovim. VS Code and the Godot IDE on the other hand work as expected.

The following video shows a screen recording of the tutorial and what the LSP provides me. This has been recorded with Godot 4.2.2. .

https://github.com/godotengine/godot/assets/10364991/08f19123-0429-4d50-9deb-54bcee42c2ab

Here for comparison VS Code

https://github.com/godotengine/godot/assets/10364991/427d846c-bcf4-4e17-ae83-e393e21ffe7f

This is how I setup my LSP: 

```
require('lspconfig').gdscript.setup({})
```

The complete logs from the neovim LSP are here:

[lsp.log](https://github.com/user-attachments/files/15857502/lsp.log)

### Steps to reproduce

1. Setup LSP for nvim as I did.
2. Start Godot and navigate to project
3. Open files in neovim and start typing existing variables and observe completions

### Minimal reproduction project (MRP)

This is the tutorial project.

[GodotTest2.zip](https://github.com/user-attachments/files/15857505/GodotTest2.zip)

**Comment by dalexeev** [comment]
Are you sure this is a GDScript LSP issue and not a Neovim issue? As far as I know, we provide the same LSP for all IDEs/editors. Only the built-in editor can make big differences since it does not use LSP. The VS Code plugin uses the same LSP, but probably does some extra processing for better integration with Godot.

**Comment by zeljkobekcic** [comment]
Hey, I was not sure where to post this. I started in the NeoVim reddit community but I cam to the conclusion that I might find an answer to this problem here.

Other people have a similar issue, see here: https://www.reddit.com/r/neovim/comments/1c2bhcs/godotgdscript_in_neovim_with_lsp_and_debugging_in/ (the first two comments).

I apologize if this is not the appropriate place for this issue. Then I would move on the the Godot reddit community.

Also I would like to add that:

> It seems to never include the top match until I manually retrigger.
> -- take from one of the reddit comments

This is also true for me.

I will once more try to understand and break down the LSP debug log which I provided.

**Comment by gsthnz** [comment]
@zeljkobekcic thanks for opening this, I'm finding the same issue, but I did not test with VSCode.

Are you using nvim-cmp? I did test with coq_nvim instead and the problem didn't happen! So it's likely an issue with nvim-cmp!

**Comment by gsthnz** [comment]
@zeljkobekcic quick update: I tried the nvim-cmp recommended minimal editor config for opening new issues and the problem does not happen!

Here's the config that I tried, on a gdscript related issue: https://github.com/hrsh7th/nvim-cmp/issues/1119

It's likely some config mistep, not a plugin or LSP issue!

**Comment by gsthnz** [comment]
> It's likely some config mistep, not a plugin or LSP issue!

I was able to track the issue down in my personal config to the use of `noinsert` in the `completion.completeopt` in nvim-cmp configs!

**Comment by zeljkobekcic** [comment]
@gsthnz, Thank you for your input. I was able to pin point the issue. First of all, I am using [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim) as a base for my nvim config.

My `comletion.completeopt` setting was defined as follows:

```lua
      completion = { completeopt = 'menu,menuone,noinsert' }, -- before and incorrect
```

Only not setting the `completion` results into correct completion suggestions. I will have to understand how `nvim-cmp` now interacts with the input and why it's so different for this LSP.

From my side this issue is not related to Godot at all. 
Apologies for any confusion.

**Comment by drzbida** [comment]
What you've done is to to set completeopt to noselect, which should not be required and work as expected without it. By using noselect you just make it so the best matching entry is not automatically selected, but if you select it yourself (without confirming) and continue typing it can be seen that the issue persists. This is for sure not an issue with nvim-cmp, but with gdscript LSP itself, as this problem is not present in dozens of other LSPs I've tried + the issue can't be found anywhere on the nvim cmp repo for other languages, which makes it tremendously unlikely to be a nvim-cmp issue as it is a very basic usecase.

**Comment by AT120** [comment]
Hi! I think the problem is that godot lsp server, in response to `completionItem/resolve`, sends fields `filterText` and `sortText` as empty strings instead of omitting them. 
<details>
<summary>lsp request </summary>

```lua
{
  id = 11,
  jsonrpc = "2.0",
  method = "completionItem/resolve",
  params = {
    data = {
      context = {
        triggerCharacter = "<null>",
        triggerKind = 1
      },
      position = {
        character = 36,
        line = 15
      },
      textDocument = {
        uri = "file:///home/at/Projects/4inarow/ball.gd"
      }
    },
    insertText = "RED",
    kind = 21,
    label = "RED"
  }
}
```
</details>

<details>
<summary>lsp response </summary>

```lua
{
  id = 11,
  jsonrpc = "2.0",
  result = {
    data = {
      context = {
        triggerCharacter = "<null>",
        triggerKind = 1
      },
      position = {
        character = 36,
        line = 15
      },
      textDocument = {
        uri = "file:///home/at/Projects/4inarow/ball.gd"
      }
    },
    deprecated = false,
    detail = "",
    documentation = {
      kind = "markdown",
      value = "\tconst Color.RED = Color(1, 0, 0, 1)\n\nRed color.\n\n"
    },
    filterText = "",
    insertText = "RED",
    kind = 21,
    label = "RED",
    preselect = false,
    sortText = ""
  }
}
```
</details>


To verify that, I tried commenting out these lines
https://github.com/godotengine/godot/blob/568589c9d8c763bfb3a4348174d53b42d7c59f21/modules/gdscript/language_server/godot_lsp.h#L1043-L1044
After that completions in neovim started to behave correctly. Completions in vscode and internal godot editor also seemed to be working fine.

I'm not sure how to implement proper fix, but hope this helps!

**Comment by HolonProduction** [comment]
It would be great if someone with a neovim setup could confirm that #96725 fixes this.

**Comment by AT120** [comment]
Yes, https://github.com/godotengine/godot/pull/96725 fixes the issue, completions in neovim now work as expected

**Comment by Tr1bute** [comment]
I'd just like to add to this that this was fixed for me by removing all the "completeopt" options in cmp.setup, so that it becomes default:

```
      cmp.setup {
        snippet = {
          expand = function(args)
            luasnip.lsp_expand(args.body)
          end,
        },
        completion = {},
```

**Comment by solitudealma** [comment]
> I'd just like to add to this that this was fixed for me by removing all the "completeopt" options in cmp.setup, so that it becomes default:我想补充一点，这是通过删除 cmp.setup 中的所有“completeopt”选项为我解决的，以便它成为默认值：
> 
> ```
>       cmp.setup {
>         snippet = {
>           expand = function(args)
>             luasnip.lsp_expand(args.body)
>           end,
>         },
>         completion = {},
> ```

will window.completion have an impact?
