### ISSUE TITLE
Disabling physics interpolation on TileMapLayer enables it 4.3.beta1

### ISSUE THREAD

**Issue by PauliusMM** [godotengine/godot#93237]
### Tested versions

4.3.beta1

### System information

Windows 11

### Issue description

While testing I saw some weird behavior with TileMapLayer, it seems disabling physics interpolation enables it, what is more weird the TileMapLayer is not even moving, as it is made visible and invisible

https://github.com/godotengine/godot/assets/12417513/5ac3336d-3c37-4a1b-92d3-c2aee8aa8af2

### Steps to reproduce

Create a project
Enable project wide Physics interpolation
Create a TileMapLayer
Add tileset
Disable TileMapLayer physics interpolation
Try making it visible/invisible

### Minimal reproduction project (MRP)

Project for reproducing: [new-game-project.zip](https://github.com/user-attachments/files/15859138/new-game-project.zip)

**Comment by rburing** [comment]
The issue is not present in Godot 3.5.3: [new-game-project-3.zip](https://github.com/user-attachments/files/15859915/new-game-project-3.zip)

So I must have made a mistake in porting the feature to 4.x, and/or overlooked some difference between 3.x and 4.x. At first glance I don't find the source of the bug. cc @lawnjelly

**Comment by lawnjelly** [comment]
@rburing If physics interpolation is off for the `TilemapLayer` you need to tell the server this, e.g. when creating the canvas item.

You probably also want to respond to `Node::_physics_interpolated_changed()` in order to be able to flip this on the fly, but this will do to get started.

```
// Check if the material or the z_index changed.
if (prev_ci == RID() || prev_material != mat || prev_z_index != tile_z_index) {
	// If so, create a new CanvasItem.
	ci = rs->canvas_item_create();
	...
	if (!is_physics_interpolated_and_enabled()) {
		rs->canvas_item_set_interpolated(ci, false);
	}
```
I may not do this absolutely correctly in 3.x actually (even though the bug is not seen there), I might check whether that needs tidying up.
