### ISSUE TITLE
It like GDExtension not support GDVIRTUAL_BIND

### ISSUE THREAD

**Issue by CsloudX** [godotengine/godot#93289]
### Tested versions

4.2

### System information

win10

### Issue description

![image](https://github.com/godotengine/godot/assets/35988767/ccf8a1b5-48c7-4eb9-80a7-f4321b3b9cdc)

### Steps to reproduce

none

### Minimal reproduction project (MRP)

none

**Comment by AThousandShips** [comment]
Please provide more details, this is not enough to go by

**Comment by akien-mga** [comment]
This is likely an issue with your XKeyboardHook code, and not a Godot bug.

I can't read the Chinese errors but this kind of chain reaction with nonsensical errors looks like what happens when including problematic headers like `Windows.h`, which define and shadow macros used by Godot code, breaking the parsing of the file.

**Comment by CsloudX** [comment]
I'm just want use `GDVIRTUAL_BIND` macro in gdextension.

**Comment by akien-mga** [comment]
It's provided already, and present in the example project.
```
include/godot_cpp/classes/wrapped.hpp
490:#define GDVIRTUAL_BIND(m_name, ...) ::godot::ClassDB::add_virtual_method(get_class_static(), _gdvirtual_##m_name##_get_method_info(), ::godot::snarray(__VA_ARGS__));

test/src/example.cpp
240:    GDVIRTUAL_BIND(_do_something_virtual, "name", "value");
```
