### ISSUE TITLE
ImmediateMesh surface_add_vertex fails to inherit parent coordinate space or top_level property

### ISSUE THREAD

**Issue by kevzettler** [godotengine/godot#93323]
### Tested versions

v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - macOS 12.4.0 - GLES3 (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

I'm trying to build a "bullet tracing" effect. I have a Node3D that I use as the `spawn_point` and then another Node3D I use as the `target_point`. I then have separate scenes that I instantiate at runtime to create projectiles and create them at the `spawn_point` and move them to the `target_point`.  One scene is just a "Basic" `MeshInstance3D` that renders a sphere and moves the sphere from `spawn_point` to `target_point`. The "Basic" scene behaves as expected meshes are created at the spawn point and move towards the target point.

The other is a 'bullet trail' scene. This scene has a MeshInstance3D with a `ImmediateMesh` set for the `mesh` property.  This scene uses the same `spawn_point` and `target_point` to draw vertices for the `ImmediateMesh` The expectation is that the `ImmediateMesh` draws a line from the `spawn_point` to the `target_point`. A line is drawn but it is not from the same coordinate points as the Basic version. The line is like offset in some unexpected coordinatespace. 

Both implementation use the `top_level = true` on the meshes that are created with the expectation that the `spawn_point` and `target_point` are in global space

### Steps to reproduce

I have built an isolated reproduction project. reproduction repo at https://github.com/kevzettler/top_level_immediateMesh
have also attached a zip vile

Can open it and run it. You can see basic meshes on a loop created at the spawn point and moving towards target point. You will also see the immediateMesh line that is drawn offset to the left side of the spawn and target.

![bug](https://github.com/godotengine/godot/assets/126209/e738331f-ef4e-4dc0-b4a4-24bfe4a1f670)

Its a bit hard to see in this gif but there is a line rendered to the left. Its possible I'm missing something looking for any alternative suggestions.

### Minimal reproduction project (MRP)

[top_level_immediateMesh.zip](https://github.com/user-attachments/files/15892297/top_level_immediateMesh.zip)

**Comment by clayjohn** [comment]
I took a look at your MRP. This issue comes from how you are creating the mesh and then moving the mesh right after. As far as I can tell `top_level` isn't causing an issue here. 

First, let's walk through what your code is doing. 

```
func _on_timer_timeout():
	var new_trail = trail_scene.instantiate()
	new_trail.target_point = target_point.global_position
	add_child(new_trail)
	new_trail.global_transform.origin = spawn_point.global_transform.origin
```

First you are creating a new trail. The trail ignores its parent, so it will use its own transform only and will not inherit the transform of its parent. The trail is given a target point (in global space). Then the trail node is moved to the spawn point. Since the trail is set as `top_level` its local origin (`position`) is directly set to `spawn_point.global_transform.origin`.

Next, the ImmediateMesh updates as follows:

```
func _process(delta):
	mesh.clear_surfaces()
	mesh.surface_begin(Mesh.PRIMITIVE_LINES, material)
	mesh.surface_add_vertex(position)
	mesh.surface_add_vertex(target_point)
	mesh.surface_end()  
```
This creates a mesh (in local space) from the spawn meshes position (i.e. `spawn_point.global_transform.origin`) to the target point. 

Then finally, the mesh is drawn. Meshes are drawn by applying the MeshInstances transform to all vertices. In this case the vertices are further offset by the position of the TrailMesh node. So, in effect, you are doubling the position. 

The first vertex will get drawn at `target_point.global_position + spawn_point.global_transform.origin` while the second vertex will get drawn at `spawn_point.global_transform.origin + spawn_point.global_transform.origin`

I think what you intended to do was draw the mesh in global space. Which would require you to not have a local transform on the TrailMesh. 

The following code works for that purpose:
```
var new_trail = trail_scene.instantiate()
new_trail.target_point = target_point.global_position
new_trail.origin_point = spawn_point.global_transform.origin #note the addition of the origin point
add_child(new_trail)
```

```
@export var material: Material = null
@export var target_point: Vector3
@export var origin_point: Vector3

func _process(delta):
	mesh.clear_surfaces()
	mesh.surface_begin(Mesh.PRIMITIVE_LINES, material)
	mesh.surface_add_vertex(origin_point) #use origin point instead of position
	mesh.surface_add_vertex(target_point)
	mesh.surface_end()   
```
![Screenshot from 2024-06-18 14-25-35](https://github.com/godotengine/godot/assets/16521339/fe7f781b-ef39-4bec-9214-ad5b8b28170e)
