### ISSUE TITLE
GL error spam when using a viewport (Sampler object 0 is bound to non-depth texture 0) [nvidia]

### ISSUE THREAD

**Issue by hickop** [godotengine/godot#9335]
**Operating system or device - Godot version:**
3.0 master Linux
GTX 770 with nvidia driver 381.22

**Issue description:**
Spam of "mesege" in output window and this error in debug:
```
ERROR: _gl_debug_print: GL ERROR: Source: OpenGL	Type: Undefined behaviorID: 131222	Severity: Medium	Message: Program undefined behavior warning: Sampler object 0 is bound to non-depth texture 0, yet it is used with a program that uses a shadow sampler. This is undefined behavior.
```

**Steps to reproduce:**
- Create a simple scene with a viewport containing a 3D scene

**Link to minimal example project:**
[viewport-test.zip](https://github.com/godotengine/godot/files/1098479/viewport-test.zip)

**Comment by hickop** [comment]
Not happening with Intel device on mesa 17.1.3.
related to #9434 ?

**Comment by ol-smaug** [comment]
I am receiving these errors also, Godot 3.0 built from source several days ago.
Windows 7 64-bit, Nvidia driver version 382.05

If I hide the ViewportContainer in my scene, the messages stop appearing (until the container is shown again).

**Comment by rubenjavier** [comment]
@hickop @akien-mga @reduz 
Im having the same issue on Windows and Linux with Nvidia cards

In this post from stackoverflow they say the cause is because the shader is compiled exposing unused samplers:
https://stackoverflow.com/questions/29801145/undefined-behaviour-with-unused-shadow-samplers

Im using a directional light over a mesh with no shadows with a SpatialMaterial, so maybe the SpatialMaterial need some ifdef to account for shadow/noshadow light?

On the link above they also recommend to cache the different versions of the shader and do the shader switching at runtime in the CPU and not the GPU

Or should we not use SpatialMaterial for production and just convert the SpatialMaterial to a shader and edit it?

**Comment by rubenjavier** [comment]
@hickop @akien-mga @reduz 
Found whats causing the problem, its the "Shadow Atlas" option from the viewport, if you leave the Size at 0 (no texture shadows), the GL error spams, if you set it at some value, 1 for example, even if you are not using shadows, then the GL error dissapears

So, the ifdef on the shader must take into account the "Shadow Atlas" "Size" value, in case of a viewport
and not use/expose unused shadow samplers
