### ISSUE TITLE
GLB assets configured with "Decompose Convex" colliders now loading with "Trimesh"

### ISSUE THREAD

**Issue by Malcolmnixon** [godotengine/godot#93501]
### Tested versions

Godot 4.3-beta2

### System information

Windows 11, gl_compatibility, NVidia RTX 3070 TI

### Issue description

I have numerous asset libraries constructed with Godot 4.2 and containing GLB files configured with different physics colliders, including:
* Simple Convex
* Box
* Decompose Convex
* Manually Constructed Colliders

In Godot 4.3-beta.2 all the "Decompose Convex" GLB files are instead coming in with Trimesh colliders.

### Steps to reproduce

1. Open/Create Godot 4.2 Project
2. Add GLB file
3. Configure GLB file for Decompose Convex physics body
4. Close project and clear .godot folder
5. Reopen project in Godot 4.3-beta2
6. Observe GLB has physics body of Trimesh

### Minimal reproduction project (MRP)

N/A

**Comment by Malcolmnixon** [comment]
This appears to have been caused by https://github.com/godotengine/godot/pull/89461 which switched the default physics shape type from Decompose Convex to Trimesh. The comment stated it should not break compatibility as the shape_type should have been serialized.

At least for Godot 4.2 that isn't the case and the `physics/shape_type = 0` line is not written to the file. It is written for Godot 4.3; but that does no good for earlier projects.

**Comment by BastiaanOlij** [comment]
Just to add some more info to this for people wanting to reproduce why this is an issue.

Clone: https://github.com/Malcolmnixon/KayKitDungeon
Check out commit d8f6476c9e1bb80523489a7d10b59d1f701cc061 (the current master we've manually hacked the `physics/shape_type` setting in there.

Looking at the file behind the scenes, we can see that files where `shape_type` is non-zero, but files that have the `shape_type` set to 0 are missing. For instance `bottle_A_brown.gltf` which is one of the shapes that users can pick up:

![image](https://github.com/godotengine/godot/assets/1945449/4f3bff8c-a226-4ebe-956b-301ac01eabfe)

Opening this up in Godot 4.2.2 we can verify that the asset is correctly setup:

![image](https://github.com/godotengine/godot/assets/1945449/e252a360-3676-46d6-8e00-836e5fd8db5d)

Saving this asset with a different shape type, I can see the shape type being added to the `.import` file, changing it back to `Decompose Convex`, the entry is removed from the file.
The assumption @reduz made that this is saved in earlier versions is thus false.

Opening this project in Godot 4.3 beta 2, the setting is still not saved in the `.import` file, but we can now see that it's using:
![image](https://github.com/godotengine/godot/assets/1945449/18e09f3c-4d69-4be2-bc99-502e46c9440e)

Now here it gets a bit tricky as to why we're making a big deal of it. In Godot XR we make it possible for the player to pick these objects up and throw them around. We need them as RigidBody3Ds.
So:

- we inherit a scene (`addons/godot-xr-tools/objects/pickable.tscn`) that has all the logic that allows picking up objects,
- we add our GLB to this scene
- we copy our shape to our collision shape node for our rigidbody
- and we disable the static body. 

And we get this wonderful warning:
![image](https://github.com/godotengine/godot/assets/1945449/19c07cb4-438c-4aa8-a245-3ce6326de1e2)

So the collision shape that we have now set as the default, has a big warning that it won't work for rigidbodies. We don't know the fallout of this yet, but I've seen an uptick of support questions on the discord about pickable objects no longer working in XR tools and am wondering if this is the root cause.

At the very least the default needs to be returned so that we get consistent behaviour.

**Comment by fire** [comment]
Approved the fix.
