### ISSUE TITLE
Lack of translation in some places of the editor

### ISSUE THREAD

**Issue by JekSun97** [godotengine/godot#93641]
### Tested versions

Occurs in Godot 4.3 beta2.
Doesn't happen in Godot 4.2.2

### System information

Godot v4.3.beta2 - Windows 10.0.19045 - Vulkan (Mobile) - dedicated Radeon RX 560 Series (Advanced Micro Devices, Inc.; 31.0.14001.45012) - Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 Threads)

### Issue description

I noticed that the translation was missing in some places in the editor, namely:
-File system
-Output

And also the top menu:
Project->Project Settings
Project->Export...
Editor->Editor Docks
Editor->Editor Docks->FileSystem

![22](https://github.com/godotengine/godot/assets/130399274/cb943e34-8645-4c84-a396-bd731f227bec)

### Steps to reproduce

Open the editor and change the localization to any other than English

### Minimal reproduction project (MRP)

N/A

**Comment by smix8** [comment]
Those labels are all marked to receive translations, if available, so not an engine bug.

Missing translations are not really tracked as issues as translations are done 100% by the community on Weblate with varying success depending on the language.

You can check the translation status of a langue here https://hosted.weblate.org/projects/godot-engine/godot/
You can find more information about Godot translation works here https://docs.godotengine.org/en/latest/contributing/documentation/editor_and_docs_localization.html

The translations are only occasionally synced with the main repo, usually before releases.

So through alpha and beta expect a lot of default english on things that got changed because the translations are not really synced in that time. If no one from the community provides translation for certain strings they will obviously still stay default english on release.

**Comment by KoBeWi** [comment]
There was a bug in early beta that erased some translations. They have to be re-translated (the strings are already available again).

**Comment by JekSun97** [comment]
Thank you, I understand, I thought translations for 4.3 automatically inherit translations from 4.2, and here it’s all about the TR() function
