### ISSUE TITLE
Root Motion Track setting from script from instantiated scene

### ISSUE THREAD

**Issue by scotmcp** [godotengine/godot#93689]
### Tested versions

Godot v4.2.2.stable.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti () - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### System information

Godot v4.2.2.stable.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti () - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

I am attempting to set Root Motion Track from script from instantiated scene

Although I seem able to set Root Motion Track, it doesn't appear to do anything.

The player object is animating just fine...Root Node assigns properly, but Root Motion Track seems not to.

I have currently named it %GeneralSkeleton as you can see in the image, but I have tried with both with and without the %. I have also tried to name the actual bone that the root is attached to, this also makes no difference.

![image](https://github.com/godotengine/godot/assets/79280460/265b3c17-ea82-4e4a-b679-630de816e56c)

### Steps to reproduce

I don't really know if this is a bug or that I am doing something incorrectly.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please ask support questions in the [forums](https://forum.godotengine.org/) if you're unsure if something is a bug

If after confirming it is a bug over there please upload an MRP:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by AThousandShips** [comment]
It's not even been a day yet, so no need to rush, I'd say to wait until you have a response on the forums, otherwise you'll need to make an MRP, without an MRP the chances of getting any help are very small as there's very little information here, someone might still be able to identify a bug, but this isn't a support forum, this is for reporting bugs, so if you're looking for help then the forums are the proper place, if you're looking to help identify and fixing a bug this is the right place

**Comment by scotmcp** [comment]
Yeah that's cool, I was hoping one might notice a procedural error on my part if it's not a bug.

**Comment by scotmcp** [comment]
I figured out what the problem is...it's the wording of the root_motion_track property in the documentation. 


The path to the Animation track used for root motion. Paths must be valid scene-tree paths to a node, and must be specified _starting from the parent node of the node that will reproduce the animation_. To specify a track that controls properties or bones, append its name after the path, separated by ":". For example, "character/skeleton:ankle" or "character/mesh:transform/local".

The italic part should read _starting from the root_node assigned_. I'll submit an edit and work with the documentation team to improve that wording.

Thank you

**Comment by scotmcp** [comment]
Documentation edit submitted
