### ISSUE TITLE
Non-selectable TreeItem returned from `Tree::get_selected()`

### ISSUE THREAD

**Issue by Naros** [godotengine/godot#93756]
### Tested versions

4.3.beta2, 4.2.2-stable

### System information

Windows 11, Linux Wayland

### Issue description

Clicking anywhere in the `Tree` control triggers a `nothing_selected` event, and the `Tree` has a selected item, which is actually a `TreeItem` that was explicitly created without being selectable.

### Steps to reproduce

Create a Tree and add an item hierarchy, as shown in this screenshot, connecting handlers to the `item_selected` and `item_activated`, and `nothing_selected` signals.

![image](https://github.com/godotengine/godot/assets/3255568/371cf2a4-29c5-4666-be40-8a75164ed7c7)

All parent nodes should be explicitly set with `set_selectable(0, false)`.  The only one that is left the default of selectable is the most descendant node, in this case `Get Self`.  

1. Select `Get Self`
2. Click on `Variables` to collapse and expand the tree.
3. Selection on `Get Self` appears to have disappeared & the tree has no selection.
4. Click anywhere below the `Get Self` in the remaining `Tree` widget's rendered area.
5. The `nothing_selected` signal is raised and the `Tree` get_selected method returns the `Variables` item.

In this use case, I would have expected that the `Tree->get_selected()` method should have returned `null`, but instead returns a pointer to the `TreeItem` related to `Variables`, which is marked as not selectable.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
