### ISSUE TITLE
Can't add property to MultiplayerSynchronizer via code right after it spawns

### ISSUE THREAD

**Issue by agrimminck** [godotengine/godot#93844]
### Tested versions

4.3.beta2

### System information

Windows 11 - Godot 4.3.beta2 - Forward+

### Issue description

I need to add properties to my MultiplayerSynchronizer via code, but if I do it after the MultiplayerSpawner spawns the object, it does not take effect and spams errors

### Steps to reproduce

Create 2 debug sessions, server and client. After the client connects, the server spawns an entity and the errors starts to spam.
I made the code very simple.

### Minimal reproduction project (MRP)

[minimal-project.zip](https://github.com/user-attachments/files/16060789/minimal-project.zip)

**Comment by hakro** [comment]
The problem is in the line : 
`$MultiplayerSynchronizer.replication_config.add_property(^"position")` in `entity.gd`

It's trying to fine a node called `position`. But in your case, you're looking for the property inside the current node, so you need to be more specific, like this : 
`$MultiplayerSynchronizer.replication_config.add_property(^".:position")` in `entity.gd`

This `.:position` means : look for the `position` property inside the current node.

**Comment by agrimminck** [comment]
Thank you! The documentation should be changed then. It says 
```
Despite their name, node paths may also point to a property:

^"position"            # Points to this object's position.

```
I will close this issue. Farewell!

**Comment by agrimminck** [comment]
Hello there again, it indeed worked, but it does not when there are more than 1 client. Here's the new minimal project with the correction to the property path. This time you just have to open 3 debug sessions, one server and two clients and this error will appear:
```
E 0:00:06:0744   entity.gd:4 @ _ready(): Condition "properties.find(p_path)" is true.
  <C++ Source>   modules/multiplayer/scene_replication_config.cpp:123 @ add_property()
  <Stack Trace>  entity.gd:4 @ _ready()

```
[minimal project.zip](https://github.com/user-attachments/files/16091962/minimal.project.zip)

**Comment by hakro** [comment]
> Thank you! The documentation in the NodePath section should be changed then. It says

Thank you for pointing this out. The documentation has been updated, and will be available in the next beta.

> Hello there again, it indeed worked, but it does not when there is more than 1 client. Here's the new minimal project with the correction to the property path. This time you just have to open 3 debug sessions, one server and two clients and this error will appear:

This seems to be a different issue. In fact, it's working as it should be. I tried moving the entities from the server, and everything is synced fine on the 2 different clients.

The error message you're seeing, is likely because the server is using the same `SceneReplicationConfig` resource. And so for the second client, it's trying to add the `position` property that was already added for the first client. In the screenshot below, you can see that both resources have the same ID

![Screenshot_20240704_132515](https://github.com/godotengine/godot/assets/3624853/ce0d6ceb-b11d-42cb-8ce4-358ab4ebd2b4)

I don't know if reusing the same config resource is intended here.

Meanwhile, if the error message is really bothering you, you can just add the property only if it's not there already. Something along the line of : 

```
	if not $MultiplayerSynchronizer.replication_config.has_property(^".:position"):
		$MultiplayerSynchronizer.replication_config.add_property(^".:position")
```

**Comment by agrimminck** [comment]
Thank, it worked just as you said, nevertheless I found another error when I try instantiating a child scene of the entity, I will open a new issue as this one is closed already.
