### ISSUE TITLE
TextureCubemapRD can't be sampled as a cubemap

### ISSUE THREAD

**Issue by woodbyte** [godotengine/godot#93915]
### Tested versions

- Reproducible in: v4.2.2.stable.official [15073afe3]

### System information

Windows 10 - Godot v4.2.2.stable - Vulkan (Forward+) - dedicated

### Issue description

Assigning a TextureCubemapRD to a samplerCube shader uniform and reading from it always returns black. Reading it as a sampler2DArray works fine, but requires the user to manually convert the cubemap direction vector to texture space (uv and face index).

### Steps to reproduce

Run the MRP and observe that the center object is indeed black:
- There is a menu to switch cubemap generation to use a standard Cubemap instead. This is slow but a good reference of what it should look like.
- You can also toggle between accessing the TextureCubemapRD as either a samplerCube or a sampler2DArray. The latter works and is a viable workaround until the issue is fixed.

### Minimal reproduction project (MRP)

[TextureCubemapRDSamplingTest.zip](https://github.com/user-attachments/files/16091060/TextureCubemapRDSamplingTest.zip)

**Comment by jadeharley2** [comment]
Can be fixed by changing: [texture_rd.cpp#L200](https://github.com/godotengine/godot/blob/c6c464cf9ae56e8b68620af65125dd980d0e8122/scene/resources/texture_rd.cpp#L200)
from:
```
ERR_FAIL_COND(tf.texture_type != RD::TEXTURE_TYPE_2D_ARRAY);
```
to:
```
ERR_FAIL_COND(tf.texture_type != RD::TEXTURE_TYPE_2D_ARRAY && tf.texture_type != RD::TEXTURE_TYPE_CUBE && tf.texture_type != RD::TEXTURE_TYPE_CUBE_ARRAY);
```

and [texture_storage.cpp#L1676](https://github.com/godotengine/godot/blob/f4af8201bac157b9d47e336203d3e8a8ef729de2/servers/rendering/renderer_rd/storage_rd/texture_storage.cpp#L1676)
from:
```
case RD::TEXTURE_TYPE_2D_ARRAY: {
```
to:
```
case RD::TEXTURE_TYPE_2D_ARRAY: 
case RD::TEXTURE_TYPE_CUBE: 
case RD::TEXTURE_TYPE_CUBE_ARRAY: {
```
tested on v4.4.dev.custom_build (fork from commit: f4af8201bac157b9d47e336203d3e8a8ef729de2)
![image](https://github.com/user-attachments/assets/caffaf6d-1b11-4686-8f06-6ef6a5cdbbee)

**Comment by clayjohn** [comment]
@jadeharley2 That seems correct, do you mind opening a pull request with those changes?
