### ISSUE TITLE
Using Resource to load custom class not working.

### ISSUE THREAD

**Issue by bleedweedsuz** [godotengine/godot#93954]
### Tested versions

Godot v4.3.beta1.official
Godot v4.2.2 stable

### System information

Mac OS 14.5 (23F79)

### Issue description

I tried to save and load custom class array using Resource.save and load it didn't work. It work for simple variable but not work for custom class array. Please look into code and MRP. 
May be i miss something in document, any guide or suggestion would be helpful or this can be bug.
Thank you.

### Steps to reproduce

For test i wrote small code

Simple custom class which hold two variable 
```
extends Resource
class_name PLayerInfo
@export var life: int = 100
@export var name: String = ""
func _init(life: int, name: String) -> void:
	self.life = life
	self.name = name
```

just a wrapper to hold PlayerInfo array
```
extends Resource
class_name ResInfo
@export var playerArray: Array[PLayerInfo] = []
```

buttons to save and load
```
extends Control

func _on_button_pressed() -> void:
	var resInfo = ResInfo.new()
	resInfo.playerArray.append(PLayerInfo.new(1, "a"))
	resInfo.playerArray.append(PLayerInfo.new(2, "b"))
	resInfo.playerArray.append(PLayerInfo.new(3, "c"))
	ResourceSaver.save(resInfo, "res://abc.tres")
	print("Saved")

func _on_button_2_pressed() -> void:
	var data = ResourceLoader.load("res://abc.tres", "", ResourceLoader.CACHE_MODE_IGNORE)
	if data && data is ResInfo:
		print("Array Size::", str((data as ResInfo).playerArray.size()))
	else:
		print("File not found")
```

Log data:
Saved <--- this one after saving data
Array Size::0 <-- this one does not load data array size:0

abc.tres file: this clearly indicate that array is added in the file
```
[gd_resource type="Resource" script_class="ResInfo" load_steps=6 format=3]

[ext_resource type="Script" path="res://PlayerInfo.gd" id="1_7vu0o"]
[ext_resource type="Script" path="res://ResInfo.gd" id="2_2l7g2"]

[sub_resource type="Resource" id="Resource_fxfkl"]
script = ExtResource("1_7vu0o")
life = 1
name = "a"

[sub_resource type="Resource" id="Resource_a03ln"]
script = ExtResource("1_7vu0o")
life = 2
name = "b"

[sub_resource type="Resource" id="Resource_7b11r"]
script = ExtResource("1_7vu0o")
life = 3
name = "c"

[resource]
script = ExtResource("2_2l7g2")
playerArray = Array[ExtResource("1_7vu0o")]([SubResource("Resource_fxfkl"), SubResource("Resource_a03ln"), SubResource("Resource_7b11r")])
```

i also tried
ResourceLoader.load("res://abc.tres")
 ResourceLoader.load("res://abc.tres", "", ResourceLoader.CACHE_MODE_REPLACE)
 no success
 
 
 for simple variable it works but for array with custom class does not work.
 
 for more code please look into MRP

### Minimal reproduction project (MRP)

[resloader.zip](https://github.com/user-attachments/files/16102455/resloader.zip)

**Comment by Hilderin** [comment]
I think I found the problem about arrays in resources and your project.

The problem was caused by your `_init` with more then zero parameters. At runtime, when loading Resource, Godot starts by creating the resource and the script. It cannot pass parameters to the constructor because Godot does not known what to use. Godot always use `_init` without any parameters on `ResourceLoader.load`.

With parameters:
![image](https://github.com/godotengine/godot/assets/81109165/61301a49-0022-48bf-9c64-27323a45fb08)

If you remove the parameters in `_init`:
![image](https://github.com/godotengine/godot/assets/81109165/40eb6a41-76ef-4259-8525-cdd16f4ecb77)

Your other option is to be sure that all the parameters in `_init` method have a default value:
![image](https://github.com/godotengine/godot/assets/81109165/90d4fa1d-0356-4ddf-95a9-849425228e2d)


I don't known if this is documented or if it should be documented somewhere??

**Comment by bleedweedsuz** [comment]
The culprit was indeed _init() without parameter, it does expect the default args.
I did look into the engine code, ([Link](https://github.com/godotengine/godot/blob/20ba2f00bd9199b675176a8e1ac151f96bfb5cfa/modules/gdscript/gdscript.cpp#L187C3-L187C60)) right here this line did check the init with parameter with default value.
There is no info in the documentation too.
I also forgot to look into the debugger editor window (my bad).

Thank you for your suggestion.
