### ISSUE TITLE
copy of is_wow64() function is dead code

### ISSUE THREAD

**Issue by jamie-pate** [godotengine/godot#94156]
### Tested versions

code issue, likely causes a bug in `get_default_installation_dir()` of [modules/mono/editor/hostfxr_resolver.cpp](https://github.com/godotengine/godot/blame/master/modules/mono/editor/hostfxr_resolver.cpp#L136)

### System information

Godot v4.3.beta2 - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Forward+) - integrated Intel(R) Graphics (ADL GT2) - 12th Gen Intel(R) Core(TM) i7-12700H (14 Threads)

### Issue description

BOOL is_wow64() occurs twice and both occurrences are logically invalid. They will always return false.

```
BOOL wow64 = FALSE;
...
		if (!fnIsWow64Process(GetCurrentProcess(), &wow64)) {
			wow64 = FALSE;
return wow64;
```			

The version here should probably be fixed, but I don't use mono, so it would not be simple for me to verify...
https://github.com/godotengine/godot/blame/master/modules/mono/editor/hostfxr_resolver.cpp#L136

This version is never used afaict and if so, it is dead code should just be removed...
https://github.com/godotengine/godot/blob/master/platform/windows/os_windows.cpp#L1643

### Steps to reproduce

read the source code? :D

### Minimal reproduction project (MRP)

:dagger: 
![682658](https://github.com/godotengine/godot/assets/682658/87850e5b-9239-47fb-a764-c238cd7420aa)

**Comment by raulsntos** [comment]
What makes you think that `is_wow64` always returns `FALSE`? I guess it's because you never see the `wow64` variable being assigned `TRUE` explicitly.

If you take a look at the `fnIsWow64Process` invocation, you'll see that the `wow64` variable is passed by reference. This is because it's an **out** parameter and the method may write to it, so `wow64` may be set to `TRUE`.

See the [`IsWow64Process` documentation](https://learn.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process) for more information.

**Comment by jamie-pate** [comment]
ok, you are right, bonehead assumption... my win32fu is very rusty :D

the 2nd copy of the function is still dead code, i guess it could just be removed but it makes me wonder what other dead code is lurking...
