### ISSUE TITLE
FOG writing in shaders fails with Compatibility renderer unless enabled via WorldEnvironment

### ISSUE THREAD

**Issue by Zorochase** [godotengine/godot#94183]
### Tested versions

4.2.2, 4.3.beta3

### System information

Windows 11, Compatibility

### Issue description

Writing to `FOG` in a shader works fine in Forward+ and Mobile, regardless of whether there is a WorldEnvironment node with fog enabled in the scene. This leads me to believe writing to `FOG` is intended to entirely override fog from any WorldEnvironment node. However, with the Compatibility renderer, writing to `FOG` *only* works if there *is* a WorldEnvironment node with fog enabled.

### Steps to reproduce

Add a node, like a MeshInstance3D, to a scene. Add a ShaderMaterial to it and give that a shader which writes to `FOG` in the `fragment` function. If you're using the Forward+ or Mobile renderers, you should see the fog color of the node change. However, with the Compatibility renderer, you'll need to add a WorldEnvironment node, give it an Environment resource, and enable fog; only then will you see the fog color change to what you instructed it to in the shader.

### Minimal reproduction project (MRP)

[Fog Shader Compatibility Issue MRP.zip](https://github.com/user-attachments/files/16167137/Fog.Shader.Compatibility.Issue.MRP.zip)

**Comment by clayjohn** [comment]
The problem here is we use a pre-processor macro `DISABLE_FOG` to tell the shader when to not render fog
https://github.com/godotengine/godot/blob/ff8a2780ee777c2456ce42368e1065774c7c4c3f/drivers/gles3/rasterizer_scene_gles3.cpp#L2571-L2573

`DISABLE_FOG` should stop fog from being calculated, it shouldn't stop custom fog from being used. 

What makes this complicated is that there is also a `FOG_DISABLED` macro which should disable _all sources of fog_ Including custom fog. It seems that in the compatibility renderer we are using both `DISABLE_FOG` and `FOG_DISABLED` in places where on `FOG_DISABLED` should be used

We need to go through the shader and clean up places where `DISABLE_FOG` shouldn't be used:

https://github.com/godotengine/godot/blob/ff8a2780ee777c2456ce42368e1065774c7c4c3f/drivers/gles3/shaders/scene.glsl#L1919-L1928

**Comment by rothej** [comment]
Going to take a crack at this

**Comment by rothej** [comment]
OK I've drilled it down, I'll try implementing fixes tomorrow but I'm 95% sure someone familiar w the repo can take one look at this and know what the issue is. Current code works in all modes, with and without the world node, aside from these changes:

From `scene.glsl`, line 1923:
```//#ifndef DISABLE_FOG // debug - this breaks compatibility mode w no World node
	//if (scene_data.fog_enabled) { // debug - same issue as above 
	frag_color.rgb = mix(frag_color.rgb, fog.rgb, fog.a);
	//}
//#endif // !DISABLE_FOG
```

`scene.glsl`, line 2134:
```
//#ifndef DISABLE_FOG // debug - uncommenting this makes compatibility mode have 3 red sides, 3 white sides
	//if (scene_data.fog_enabled) { // debug - same issue here
	additive_light_color *= (1.0 - fog.a);
	//}
//#endif // !DISABLE_FOG
```

**Comment by rothej** [comment]
OK I've drilled it down, I'll try implementing fixes tomorrow but I'm 95% sure someone familiar w the repo can take one look at this and know what the issue is. Current code works in all modes, with and without the world node, aside from these changes:

From `scene.glsl`, line 1923:
```
#ifndef FOG_DISABLED
	fog.xy = unpackHalf2x16(fog_rg);
	fog.zw = unpackHalf2x16(fog_ba);

//#ifndef DISABLE_FOG // debug - this breaks compatibility mode w no World node
	//if (scene_data.fog_enabled) { // debug - same issue as above 
	frag_color.rgb = mix(frag_color.rgb, fog.rgb, fog.a);
	//}
//#endif // !DISABLE_FOG
#endif // !FOG_DISABLED // Commenting out FOG_DISABLED and leaving the if statement in does not fix.
```

`scene.glsl`, line 2134:
```
//#ifndef FOG_DISABLED
	fog.xy = unpackHalf2x16(fog_rg);
	fog.zw = unpackHalf2x16(fog_ba);

//#ifndef DISABLE_FOG // debug - uncommenting this makes compatibility mode have 3 red sides, 3 white sides
	if (scene_data.fog_enabled) { // debug - same issue here
	additive_light_color *= (1.0 - fog.a);
	}
//#endif // !DISABLE_FOG
//#endif // !FOG_DISABLED // same issue if you uncomment scene_data but comment this. DISABLE_FOG remains commented out.
```
