### ISSUE TITLE
Lightmap bake freezes the editor at "Determining optimal atlas size" when trying to bake certain geometry

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#94216]
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

Godot v4.3.beta3 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

Editor freezes at "Determining optimal atlas size" completely and can only be closed by killing the process. The cube in this scene is missing its bottom face. Such geometry is fine in general (i.e the platform is missing the bottom face too, and it bakes fine on its own), however in this particular configuration where there's also a cube above it crashes. Note that the cube doesn't have to touch the platform for it to crash

<img width="979" alt="image" src="https://github.com/godotengine/godot/assets/60579014/775873a8-f1b4-46ba-8a78-0fe32176adb6">

### Steps to reproduce

Open the MRP and bake

### Minimal reproduction project (MRP)

[MRP_determining_optimal_atlas_size.zip](https://github.com/user-attachments/files/16177810/MRP_determining_optimal_atlas_size.zip)

**Comment by SpockBauru** [comment]
Tested here and the MRP also freezes on Windows 11:
`Godot v4.3.beta3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.5612) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)`

**Comment by BlueCube3310** [comment]
Possibly related to #63423.

**Comment by BlueCube3310** [comment]
This seems to have been a hidden issue, only triggered in specific cases (Usually when the size of a single mesh's UV map was usable to fit into the whole atlas - the algorithm would try to add infinite layers to the image to have a clean layer to pack the mesh's UVs, but the layer would always turn out too small).  #91601 exaggerated this issue since it padded smaller images and made them too big to fit into the atlas.
