### ISSUE TITLE
Selecting text with drag sometimes instantly select all text to previous caret position

### ISSUE THREAD

**Issue by Giganzo** [godotengine/godot#94211]
### Tested versions

Godot v4.3.beta2
Godot v4.3.beta3 

### System information

Godot v4.3.beta3 - Fedora Linux 39 (KDE Plasma) - X11 - Vulkan (Forward+) - nvidia; 555.58.02

### Issue description

Selecting text with drag sometimes instantly select all text to previous caret position.

First thought my mouse button was going bad, but don't seem to happen in 4.2.2 

Also don't think I have seen this on windows.

Could it be related to?: https://github.com/godotengine/godot/issues/94077

### Steps to reproduce

Place your caret somewhere in the code.
Then try to select some text at another place.

### Minimal reproduction project (MRP)

N/A

**Comment by alvinhochun** [comment]
Does this happen with 4.3 beta 1?
Perhaps an X11 version of #93078 (possible regression by #92424)?

**Comment by Giganzo** [comment]
> Does this happen with 4.3 beta 1? 

I haven't been able to reproduce it in beta 1 when testing now

**Comment by kitbdev** [comment]
It looks like this is happening because an `InputEventMouseMotion` with a mouse mask is sent before an `InputEventMouseButton` pressed event, same as #93078 as mentioned above.
- Fixing this should also fix https://github.com/godotengine/godot/issues/94077
- Probably caused by #92424

- Fixing it is not as simple as https://github.com/godotengine/godot/pull/93105, some logic in `DisplayServerX11` needs to change to make sure mouse motion does not have the mask set before the mouse pressed event.

This applies to all Controls, but I could make a workaround just for TextEdit if needed.

**Comment by akien-mga** [comment]
CC @bruvzg
