### ISSUE TITLE
Lightmap bake fails when trying to bake for the second time to the same path

### ISSUE THREAD

**Issue by passivestar** [godotengine/godot#94214]
### Tested versions

v4.3.beta3.official [82cedc83c]

### System information

Godot v4.3.beta3 - macOS 14.5.0 - Vulkan (Forward+) - integrated Apple M1 Max - Apple M1 Max (10 Threads)

### Issue description

<img width="1157" alt="image" src="https://github.com/godotengine/godot/assets/60579014/9f204a2b-2982-4022-9452-6de5b2e8b924"><br>

Baking for the first time succeeds, but when trying to bake for the second time to the same file it fails with
```
Another resource is loaded from path 'res://node_3d.lmbake' (possible cyclic resource inclusion).
```

Restarting the editor solves the problem

### Steps to reproduce

1. Open the MRP
2. Delete LightmapGI node
3. Add a new LightmapGI node
4. Click bake, choose the same `lmbake` path and agree to overwrite

Note: sometimes it also fails without deleting the node and just clicking bake on the same node twice is enough, but steps above reproduce it more reliably

### Minimal reproduction project (MRP)

[MRP_another_resource_loaded.zip](https://github.com/user-attachments/files/16177561/MRP_another_resource_loaded.zip)

**Comment by viksl** [comment]
I can confirm lightmap does brake on multiple occasions on windows 11 in godot 4.3 [383a6e4ef285fddcb0e1cbe28a20332c7e5a815b].

It also freezes when I bake then change the probe count up to the max and try baking again.

**Comment by SpockBauru** [comment]
Tested all way back to 4.0.0 and @passivestar's file path issue was also reproducible there.

Couldn't reproduce @viksl issue with the probes, it takes a long time to bake but is finished eventually.

`Godot v4.0.stable.official and Godot v4.3.beta3 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.5612) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads) - 32GB RAM`

**Comment by viksl** [comment]
@SpockBauru I doublechecked but it freezes for me every time without any resolution. It always starts at 26% for me and never moves. Godot becomes unresponsive, it always happens to me if I select the 32 subdiv (all the other subdivs work for me just fine) - even without doing what this report mentions, simply just starting a freash project with 32 subdiv lightmapGI and and box mesh then hitting bake lightmaps and that's the end for me forever.
(I'm on win11, intel i5 13600kf, rtx 4070, 32gb ram so I don't think it's just long because my hw isn't enough)

I've double checked the processes and performance meters and both my gpu and cpu are unused during the bake step (not processing just idle 1%).

Though since it doesn't need the same step as this report it's probably a different issue?
