### ISSUE TITLE
Option to expand inspector sections by default

### ISSUE THREAD

**Issue by eon-s** [godotengine/godot#9427]
**Godot version: Master 36548a3fa**

**Issue description:**
The new collapsible sections on the inspector are cool, but all start collapsed and if you need to find a specific property you need to remember to which class it belongs or expand all, every time (depending on the volatility of the user's memory).
This may not help new users either.

An option for having sections expanded by default on the inspector could be useful.

**Comment by toger5** [comment]
What about an expand all button.

Right now Godot keeps track of the state (what was opened) which is pretty cool.
It even does that when restarting the editor. So you have to think of closed more like: `closed as the initial state` instead of `closed as default`
I think this behaviour should not be changed since, as I said it's cool as it allows you to recognise which node you are working on easier when it is in the same stat. The categories you are working on are opened...
I don't know about initial state being open since that makes it less clean. although you could argue initial state open is good because you have to open one section anyways so it saves you clicks.

But I think having the option to quickly open or close everything would be cool.
all **closed** to find what you are searching for.
all **open** to get an overview what is possible.

**Comment by homer666** [comment]
I really like that idea. I'd imagine they'd be placed inside the "Object properties" menu (the gear icon), or maybe even as its own icon in that row that toggles between "Expand all" and "Collapse all".

**Comment by toger5** [comment]
What about just double clicking an expandable header? Of course this is more like in pro feature than. but really good to use.
I also like the button next to the search/gear since the search also is a "help to navigate the inspector" feature, so collapse all and expand all would fit. I think it could be one button. as soon as one field is open it switches to `collapse all`. if all are collapsed it shows `expand all`

**Comment by Betogcc** [comment]
I've been using Godot for several years now. Huge fan and found this thread from the facebook section. I'm currently porting our game from love2d (around 10k loc), it's not much, but GDScript makes it relatively easy and our team has only a few people.  And we LOVE Godot and have been using it daily ever since.

With that said, a couple team members tried out the new 3.0 editor and were curious about the inspector fields. We've been looking in the settings to see if there was an option to permanently have them expanded but with no prevail! So glad I found this thread, we are definitely in favor of it, thank you!

**Comment by reduz** [comment]
I'm still thinking, besides adding an option to uncollapse, making the
search box always present would be useful

**Comment by darkcoderrises** [comment]
Hi, can I work on this?

**Comment by Noshyaar** [comment]
@darkcoderrises Please go ahead. :) No need to ask.
