### ISSUE TITLE
Single underscore node name is ignored when using the $ get_node() shorthand

### ISSUE THREAD

**Issue by zhyrin0** [godotengine/godot#94310]
### Tested versions

4.3.beta1, 4.3.beta3

### System information

Linux Mint 21.3 (Virginia)

### Issue description

When working with $ shorthand node paths in gdscript, a single underscore node name gets ignored.  
Example:
```
SceneRoot
\- _
   \- Node
\- Sibling
   \- _
      \- Node
```
Here, `$_/Node` gets recognised as `/Node`, `$Sibling/_/Node` gets recognised as `Sibling/Node`.

### Steps to reproduce

- Create a scene
- Add a child, name it `_`
- Add a grandchild
- In gdscript, try accessing the grandchild with the $ get_node() shorthand, such as `$_/<Grandchildname>`

### Minimal reproduction project (MRP)

[bugreport_underscore_nodename_absolute_path.zip](https://github.com/user-attachments/files/16202146/bugreport_underscore_nodename_absolute_path.zip)

**Comment by HolonProduction** [comment]
Regression from #87634 or b4d0a09f15c60c88bbf516d2f6dcdb451dcad9c7 to be more precise.

Also probably related, the following script:
```swift
extends Node

func _init() -> void:
	self._
```
Triggers a leftover `print_line` which says "Empty identifier found.". Haven't looked into it in depth but the common point between `parse_identifier` and `parse_get_node` seems to be `previous.get_identifier();` which I suspect is empty in this cases for some reason, instead of containing `_`.
