### ISSUE TITLE
allow preload of "self script" in script (with warning about circular reference)

### ISSUE THREAD

**Issue by mikica1986vee** [godotengine/godot#944]
Suppose we have "MyScript.gd". Allow the following in "MyScript.gd":

``` GDScript
const MyName_For_MyScript = preload("MyScript.gd")
var MyInnerClass = MyName_For_MyScript.MyInnerClass
```

**Comment by akien-mga** [comment]
Er, how would that work? Can you really preload something in itself?

**Comment by mikica1986vee** [comment]
You can in 1.0 :) 

I didn't check this in a while, but somewhere around 1.1 gdscript compiler started to complain when preloading itself in script.

As to where this is usefull, think state machines with states as inner classes. 

There is a way to do something similar (get_outter() I believe), but not in a "const safe" way.

I'll have to go through all examples I had. "New " way and "self preload" are not equivalent.

**Comment by akien-mga** [comment]
This still looks a bit weird to me (at least quite hard to read, so I'm not sure it would be a good idea to even support it even if it might be useful in some very specific cases as described above), but I'll let @reduz comment on it :)

**Comment by bojidar-bg** [comment]
Ok, I think I know why we have to support it alongside `get_script`:

Imagine that I have a `entity.gd` and `player.gd` (and I really do, but anyway..), and that `player.gd` extends `entity.gd`. Then, if I want to check if the entity has collided with another entity, I might just do:
````gd
# entity.gd
func _body_enter(body):
    if body extends get_script():
        print("Collided with another entity!")
````
... which works as long as `!self extends preload("player.gd")`, since if it does, `get_script() == preload("player.gd")`, which is clearly not what I want.

It would be nice to support either preloading self, or just make a GDScript way to get the "self' script.

**Comment by akien-mga** [comment]
Do you mean that ``if body extends preload("res://entity.gd")`` would not work currently?

**Comment by bojidar-bg** [comment]
Yes, it would make a parse-time error.

**Comment by neikeq** [comment]
@bojidar-bg I can confirm that. I had that problem some months ago. A work around is to put the preload call in another script:

``` GDScript
# entity.gd
func _body_enter(body):
    if body extends preload("aux_preload.gd").preload_player_gd():
        print("Collided with another entity!")
```

``` GDScript
# aux_preload.gd
static func preload_player_gd():
    return preload("player.gd")
```

As you can see, it's not very clean :)

**Comment by bojidar-bg** [comment]
BTW, there are a few other workarounds, like `load("filename")` or making a class that extends it and overrides some `get_blablabla_script()` function.

**Comment by bojidar-bg** [comment]
I think a `get_self_script()` or `get_current_script()` or `this_script` in `@GDScript` might do it.

**Comment by akien-mga** [comment]
First of all thank you for your report and sorry for the delay.

We released Godot 3.0 in January 2018 after 18 months of work, fixing many old issues either directly, or by obsoleting/replacing the features they were referring to.

We still have hundreds of issues whose relevance/reproducibility needs to be checked against the [current stable version](https://godotengine.org/download), and that's where you can help us.
**Could you check if the issue that you described initially is still relevant/reproducible in Godot 3.0 or any newer version, and comment about it here?**

For bug reports, please also make sure that the issue contains detailed steps to reproduce the bug and, if possible, a zipped project that can be used to reproduce it right away. This greatly speeds up debugging and bugfixing tasks for our contributors.

Our Bugsquad will review this issue more in-depth in 15 days, and potentially close it if its relevance could not be confirmed.

Thanks in advance.

*Note: This message is being copy-pasted to many "stale" issues (90+ days without activity). It might happen that it is not meaningful for this specific issue or appears oblivious of the issue's context, if so please comment to notify the Bugsquad about it.*

**Comment by bojidar-bg** [comment]
Well, this is still valid in 3.0, yes.

**Comment by letheed** [comment]
A solution to this could be to introduce `Self` that refers to the current class.

It's a tad weird that "Entity.gd" needs to `preload("Entity.gd")` to have access to it.

```gdscript
# Entity.gd
func _body_enter(body):
    if body is Self:
        print("Collided with another entity!")
```

This side-steps the issue of `get_script` returning `Player` in "Player.gd" if "Player.gd" extends "Entity.gd".

I think it would also be a more elegant answer to #19345 :

```gdscript
class Example:
    var _data = []

    func duplicate():
        var copy = Self.new()
        copy._data = _data.duplicate()
        return copy
```

**Comment by letheed** [comment]
Or just let a class call itself in itself. `Entity` be defined inside "Entity.gd" and Example be defined inside `class Example`.

**Comment by Cygon** [comment]
This is one of the only features I'm missing in GDscript right now. Forward declarations allowing bidirectional references between script classes.

Image this simple game framework, for example:

![actor-framework](https://user-images.githubusercontent.com/3613175/51935593-8584fe00-2406-11e9-88ae-0784010dc408.png)

An "actor" references a current "move" which acts like a state in a state machine. The "move" wants to hold a reference to the actor in order to assign another move or look up properties of the actor (jump height, running speed, etc.).

Same problem with the "move repository" and the "moves" -- the repository wants to store reusable move instances, the moves need to access the repository to get at other moves they wish to switch to.

Easy to execute with C# or C++, but GDscript (with optional static typing) cannot deal with this unless you fall back to variants (dynamic typing) in one direction to break circular references.

**Comment by vnen** [comment]
@Cygon there are some insights about this in #21461. I already plan to work in this in the near future.

OTOH I don't really want to make preloading the same script possible, so this issue could be closed IMO. With new abilities of GDScript this wouldn't be needed anyway.

**Comment by akien-mga** [comment]
I agree with @vnen that supporting self-preloading would not be a good idea. I don't see a use case for it apart from giving headaches to the GDScript VM :P

@Cygon's use case seems indeed closer to what is described in #21461. It would be better to move/paste the relevant discussion there (or maybe in another -- clearer -- issue about (implicit?) forward declarations).
