### ISSUE TITLE
root window.size_changed is not emitted when Stretch Mode is set to "viewport"

### ISSUE THREAD

**Issue by Efra-EMX** [godotengine/godot#94495]
### Tested versions

- Reproducible in: v4.3.beta3.official [82cedc83c], v4.2.2.stable.official [15073afe3], v4.0.stable.official [92bee43ad]

### System information

Godot v4.3.beta3 - Linux Mint 21.3 (Virginia) - X11 - GLES3 (Compatibility) - KABINI (, LLVM 15.0.7, DRM 2.50, 5.15.0-112-generic) - AMD E2-7015 APU with AMD Radeon R2 Graphics (2 Threads)

### Issue description

In the project settings, if **stretch mode** (_display/window/stretch/mode_) is set to **viewport**, the **root window** (_get_tree().root_) will not emit its **size_changed** signal.

This doesn't happen when **stretch mode** is set to **disabled** or **canvas_items**. It also **only happens to the root window** specifically, as children windows will still emit their **size_changed** signal normally even when their **content_scale_mode** is set to **viewport**.

Tested and reproducible in v4.3.beta3, v4.2.2.stable, and v4.0.stable.

https://github.com/user-attachments/assets/79dd5c9d-747f-4d5f-927a-e0be3202c24e

### Steps to reproduce

1. Create a new project
2. Make a new script that connects with **get_tree().root.size_changed** signal. For example:
```
func _ready():
	get_tree().root.size_changed.connect(on_window_size_changed)

func on_window_size_changed():
	print("Window resized")

```
3. Run the project and try resizing the game window. The signal should emit and execute the connected Callable normally.
4. Close the game.
5. Go to **Project Settings > Display > WIndow > Stretch > Mode** and set it to **viewport**
6. Run the project again and try resizing the game window. Now the signal doesn't emit and execute the connected Callable anymore.

### Minimal reproduction project (MRP)

[window-signal-mrp.zip](https://github.com/user-attachments/files/16278726/window-signal-mrp.zip)

**Comment by etacarinaea** [comment]
> if stretch mode (display/window/stretch/mode) is set to viewport, the root window (get_tree().root) will not emit its size_changed signal.

This only happens when `display/window/stretch/mode` is set to `viewport` ***and*** `display/window/stretch/aspect` is set to `keep` (but I assume this also happens with `keep_width`/`keep_height` when the height/width isn't being changed). When `aspect` is set to `ignore` or `expand`, the `size_changed` signal will be emitted when the window is resized through the window manager.

> only happens to the root window

This does also happen for child windows with the same attributes, although both components of the `content_scale_size` vector need to be non-zero, otherwise the viewport will be resized. Also, setting `content_scale_size` on a window will emit the `size_changed` signal, even with the attributes set as above.

I'm wondering if this is technically a bug or if it's actually "working as intended" since the stretch mode tooltip mentions that "the size of the root `Viewport`  is set precisely to the base size" and "finally, this viewport is scaled to fit the screen", so I guess the base size (I assume that means `content_scale_size`) of the viewport never really changes when the aspect ratio is kept. But the `size` attribute changes, so it would make sense that the `size_changed` signal is emitted, unless it really is only supposed to emit when the base size is changed, but then there should be two signals imo, `size_changed` for the `size` and `content_scale_size_changed` for the `content_scale_size`.

I can reproduce this on both Linux and Windows:
<details>
<summary>System information</summary>

> Godot v4.3.beta3 - Arch Linux SMP PREEMPT_DYNAMIC Fri, 12 Jul 2024 00:06:53 +0000 - Tty - GLES3 (Compatibility) - AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 18.1.8, DRM 3.57, 6.9.9-arch1-1) - AMD Ryzen 5 3600X 6-Core Processor (12 Threads)

> Godot v4.3.beta3 - Windows 10.0.22631 - GLES3 (Compatibility) - Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.3889) - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 Threads)
</details>

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot-proposals/issues/8788, as this is intended behavior (the viewport size does not actually change when resizing the window). Therefore, implementing a notification for this is feature proposal territory.
