### ISSUE TITLE
Animation does not play after set input name of Transition in AnimationTree

### ISSUE THREAD

**Issue by kyushu** [godotengine/godot#94607]
### Tested versions

Godot v4.3.beta3.gdscript

### System information

Window11 - Godot v4.3 beta3 Vulkan 1.3.280 - Forward+ NVIDIA GeForce RTX 4090 Laptop GPU

### Issue description

when i play attack1,2,3 animations according to the following animation tree and code, the animation will be played several times then it stops playing the animation.

![螢幕擷取畫面 2024-07-22 123542](https://github.com/user-attachments/assets/7ea2949b-9300-47e9-97e8-821efbdfeddb)

```
_anim_tree.set("parameters/attack_trans/transition_request", attack_enable_name)
_anim_tree.set("parameters/attack_shot/request", AnimationNodeOneShot.ONE_SHOT_REQUEST_FIRE)

```

i have set animation call method to notify the animation is finished, when animation is finished, i run the above code to play one of attack1, 2, 3 animations again. but it will stop playing animation after i have run this loop several times. 

here is my log, i print which name i set to transition_request and "attack_animation_end" will be printed when animation is finished

```
attack_enable_name: attack2
attack_animation_end

attack_enable_name: attack3
attack_animation_end

attack_enable_name: attack1
attack_animation_end

attack_enable_name: attack3 <--- do not play animation
```

### Steps to reproduce

1. create animation tree like i post
2. add animation call method to notify animation is finished
3. when animation is finished, you can set input of Transition to choose animation and trigger one shot to player the animation
4. after random times, trigger one shot to player animation will fail.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
