### ISSUE TITLE
Code autocomplete text for default constructed Callable is incorrect (extra "null" string)

### ISSUE THREAD

**Issue by hsandt** [godotengine/godot#94658]
### Tested versions

- Reproducible in 	v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.2.1.stable - Ubuntu 22.04.4 LTS 22.04 - X11 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 860M (nvidia; 535.161.07) - Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 Threads)

### Issue description

When passing a default parameter Callable to default-constructed object:

```gd
static func test(callback: Callable = Callable()):
	test() # autocomplete after (
```

The autocomplete popup hints default parameter:

> callback: Callable = Callablenull::null

![image](https://github.com/user-attachments/assets/e7de05fb-8669-4e30-938c-1dcfaec28253)

This looks odd, and should probably be just `Callable::null`

Note that said object is in fact not null, as Callable is not nullable, so it's more like an empty Callable. But this is not the issue here, if you really call this `Callable::null` internally, it's fine.

### Steps to reproduce

Type:

```gd
static func test(callback: Callable = Callable()):
	test(
```

And wait for autocomplete, or ctrl+space to display it again if you missed it (note that closing bracket generally appears automatically when typing, not copy-pasting, but it doesn't matter.

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Can you please confirm with 4.2.2, or even better [4.3.beta3](https://godotengine.org/article/dev-snapshot-godot-4-3-beta-3/) to get an idea where this currently occurs

Please make bug reports with a [supported version](https://docs.godotengine.org/en/latest/about/release_policy.html#release-support-timeline), 4.2.1 is not supported and a lot of bugs have been fixed since 4.2.1
