### ISSUE TITLE
navigation3d bug

### ISSUE THREAD

**Issue by yythlj** [godotengine/godot#94670]
### Tested versions

4.3.beta2 windows10

### System information

windows10 godot4.3.beta2 

### Issue description

a agent's navigation never avoidance other agent

The paths calculated by the navigation agent will never consider the situation of other agents in between.

Even if obstacle avoidance is enabled, it is useless.

As long as there is a movable agent blocking the way in the middle, the agents behind will never be able to pass through, without knowing to take a detour and go the long way around.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/4d78c926-65f7-43b1-a176-b1c5cf344aca)
![image](https://github.com/user-attachments/assets/c91002f4-8f3d-45ca-8db2-52aa51b6c72f)
![image](https://github.com/user-attachments/assets/a0129979-a234-473b-9efc-0d77f2786163)
![image](https://github.com/user-attachments/assets/36bb32e9-b922-435a-8b77-7b4c8ff17408)

### Minimal reproduction project (MRP)

NA

**Comment by AThousandShips** [comment]
Avoidance is separate from pathing, so it isn't really designed to handle these kind of cases where you block a large area with agents, see [here](https://docs.godotengine.org/en/latest/tutorials/navigation/navigation_using_navigationagents.html#navigationagent-avoidance) and some of the notes there

**Comment by yythlj** [comment]
and there has a error on start(I just use a very simple, box mesh 2048 x 2048 for navigation)

ERROR: Navigation map synchronization error. Attempted to merge a navigation mesh polygon edge with another already-merg
ed edge. This is usually caused by crossing edges, overlapping polygons, or a mismatch of the NavigationMesh / Navigatio
nPolygon baked 'cell_size' and navigation map 'cell_size'. If you're certain none of above is the case, change 'navigati
on/3d/merge_rasterizer_cell_scale' to 0.001.

**Comment by AThousandShips** [comment]
Then you should probably fix that error, try following the instructions for that

**Comment by smix8** [comment]
What was already mentioned.

RVO avoidance does not affect or care about the navigation mesh and pathfinding because RVO avoidance operates only with agent velocities. You can use RVO avoidance without a single navigation mesh in your game just by giving agents velocities. RVO avoidance is a system for basic collision avoidance with other moving agents. It is definitely not a path planner and the documentation is rather clear on that.

Both navigation mesh pathfinding and avoidance are certainly not crowd planners or simulators that require a completely different data struct to be even somehow supportable. A navigation mesh focuses on covering as much geometry surface as efficiently as possible for pathfinding while for a crowd and detour planner wants the extact opposite. E.g. a high resolution grid so agents can actually occupy space on the map. It is a completely different system requirement that adds a lot of memory and computation cost and is not supported by the NavigationServer.

**Comment by smix8** [comment]
Closing as that the avoidance does not affect the pathfinding and therefor paths is documented in the navigation agent doc.
