### ISSUE TITLE
animation tree animation node error

### ISSUE THREAD

**Issue by yythlj** [godotengine/godot#94732]
### Tested versions

4.3.beta2

### System information

windows10 4.3.beta2

### Issue description

I want to change the animationnode's animation during runtime.
it seem no use

### Steps to reproduce
```
action_anim_node = anim_tree.tree_root.get_node("Action")

func transition_action_anim(anim, tmlen=0, loop=1, blend_amt=1):
	if tmlen == 0:
		tmlen = AnimData.GetAnimTimeLen(anim)
	anim_tree.set("parameters/Mix/blend_amount", blend_amt)
	action_anim_node.set_animation(anim)
	action_anim_node.set_timeline_length(tmlen)
	action_anim_node.set_loop_mode(loop)
	#anim_tree.set("parameters/Action/current_position", 0)
```

![image](https://github.com/user-attachments/assets/b72f1706-86b5-4e78-adc5-962373d2e1f7)

### Minimal reproduction project (MRP)

![image](https://github.com/user-attachments/assets/84fbdebf-a390-4306-af27-c3974c42f12b)

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
