### ISSUE TITLE
Parallax2D autoscroll does not use scroll_scale

### ISSUE THREAD

**Issue by sdhawk** [godotengine/godot#94759]
### Tested versions

- Reproducible in: v4.3.rc1.mono.official [e343dbbcc] (and probably any version with Parallax2D)

### System information

Windows 10 - v4.3.rc1.mono.official - Vulkan (Forward+)

### Issue description

When using Parallax2D's autoscroll feature, it doesn't take scroll_scale into account.

Example: If you have a Parallax2D with 0.5 scroll_scale and a Parallax2D with 1.0 scroll_scale and set them both to 30 autoscroll, they both scroll at 30. You would expect the end result to be 15 and 30 respectively.

### Steps to reproduce

- Create two Parallax2D nodes, add a Sprite2D using icon.svg to each and offset the y of one of them so you can see both side-by-side. Set both Parallax2D's repeat_size x to the sprite's width. Give one an x scroll_scale of 0.5 and the other 1.0.
- Set both Parallax2D's x autoscroll to 30
- They both scroll at the same speed despite differing scroll_scales

### Minimal reproduction project (MRP)

[parallax-autoscroll-scale.zip](https://github.com/user-attachments/files/16384056/parallax-autoscroll-scale.zip)

**Comment by akien-mga** [comment]
CC @markdibarry

**Comment by markdibarry** [comment]
This was by design, but maybe we can do a better job with the documentation. When we originally worked on this, I asked around for what would be the preferred behavior for auto-scroll. The consensus was that it'd be most user-friendly to have `autoscroll` measured in pixels per second. We discussed having it change based on `scroll_scale`, but there would be two problems:
* We wouldn't be able to label it as `px/s`, because that wouldn't be accurate
* It would be difficult for users to calculate and test the actual speed they want to see

I imagine there may be a few scenarios where a user would prefer it to scale (though I can't think of any at the moment), but if you have a suggestion on how to support both in a user friendly way, I'd definitely give you a hand if you make a proposal!

**Comment by sdhawk** [comment]
In my case we have a background that scrolls with the camera as well as by itself at a slower speed when the camera isn't moving (specifically, floating/drifting rocks). So it was a natural expectation to retain the parallax effect for them when standing still. 

Working around it isn't particularly difficult, it just requires applying the scale to autoscroll, but it does mean adjusting scale requires changing two values every time.

**Comment by markdibarry** [comment]
I get it. I worry that it's already getting kinda busy with the amount of options, but if you make a proposal for a flag, I'll make a PR. Should be easy enough and wouldn't be breaking if we leave it disabled by default. We can let the community decide!

**Comment by sdhawk** [comment]
Bloat is a legitimate concern. I think a key mental difference is that each Parallax2D has its own autoscroll speed now, while my old work around was using ParallaxBackground's offset to apply a single speed to multiple layers at once (which I believe was applying scale, though I'd have to verify). For now I'll stew on it before posting a proposal.
