### ISSUE TITLE
Transition from end of a looping animation plays the first frame of the loop

### ISSUE THREAD

**Issue by krdluzni** [godotengine/godot#94768]
### Tested versions

- Reproducible in: v4.3.rc1.official [e343dbbcc], v4.3.beta3.official [82cedc83c], v4.3.beta2.official [b75f0485b], v4.3.beta1.official [a4f2ea91a], v4.3.dev6.official [89850d553].
- Not reproducible in: v4.3.dev5.official [89f70e98d] ***

*** Note: 4.3.dev5.official predates the addition of break_loop_at_end which is needed to reproduce this issue.

### System information

Godot v4.3.rc1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 31.0.15.5123) - AMD Ryzen 9 7950X 16-Core Processor (32 Threads)

### Issue description

When using Break Loop At End to transition from the end of a looping animation to the next animation in a state machine, the first frame of the previous looping animation is run even if the Xfade Time is 0. This includes calling methods via method tracks in the animation.

### Steps to reproduce

1. Open MRP.
2. Run project.
3. Watch the cube animate along a square path.
4. See that the cube jumps back up to the start of the right-hand edge of the square path before animating along the bottom. See also that the method track calls print_tree from the start of the downward movement animation when this occurs.

Note: These steps assume you don't end up seeing https://github.com/godotengine/godot/issues/94767 instead, which is another issue with Break Loop At End functionality.

### Minimal reproduction project (MRP)

[anim_tree_loop_print.zip](https://github.com/user-attachments/files/16385893/anim_tree_loop_print.zip)

**Comment by TokageItLab** [comment]
This is a problem that depends on the key get method on the Animation class side where the end of the loop animation is replaced by the first key.

For non-looping animations, the last frame is processed even when remain time is 0 because the end key needs to be processed, but I think this has a bad effect when break_loop_at_end is combined with a looping animation.

break_loop_at_end does not override the animation's loop setting, but judges it to be the end when the remaining time is 0 or right after the loop. We may need to change the animation class so that it can internally override the loop setting for stable operation.
