### ISSUE TITLE
process_confirm_path: Invalid packet received. Size too small.

### ISSUE THREAD

**Issue by scotmcp** [godotengine/godot#94769]
### Tested versions

Godot v4.3.rc1.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### System information

Godot v4.3.rc1.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

E 0:00:01:0455   process_confirm_path: Invalid packet received. Size too small.
  <C++ Error>    Condition "p_packet_len != 6" is true.
  <C++ Source>   modules/multiplayer/scene_cache_interface.cpp:138 @ process_confirm_path()

This issue occurs on the client peer after the connection is establish, after the first RPC is sent, but before the RPC checksum is returned. This is not causing an issue for the running game, but it IS producing the error.

This error occurs in 4.3rc1, it does NOT occur in 4.2.2

### Steps to reproduce

Setup client and server and RPCs. Run.

### Minimal reproduction project (MRP)

My project involves 3 interdependent server projects and a client project...not really possible to reduce the project to a minimal project.

**Comment by Faless** [comment]
> My project involves 3 interdependent server projects and a client project...not really possible to reduce the project to a minimal project.

Please make sure you are running the same godot version on all the 3 servers and the client, the multiplayer protocol has changed between Godot 4.2 and 4.3 .

**Comment by scotmcp** [comment]
> > My project involves 3 interdependent server projects and a client project...not really possible to reduce the project to a minimal project.
> 
> Please make sure you are running the same godot version on all the 3 servers and the client, the multiplayer protocol has changed between Godot 4.2 and 4.3 .

You guys changed network protocol between minor versions?

**Comment by Faless** [comment]
> You guys changed network protocol between minor versions?

Yes, and will likely change again (not in patch releases though). Godot versioning is not exactly "semver".

In general, we don't guarantee runtime multiplayer compatibility between different engine versions (though again, we always maintain network compatibilities in patch releases compatibility unless it's required by a security fix).

There is a proposal (https://github.com/godotengine/godot-proposals/issues/3533) about adding a way to handle version mismatches which might be worth implementing going forward.

**Comment by scotmcp** [comment]
> Yes, and will likely change again (not in patch releases though). Godot versioning is not exactly "semver".
> 

For standalone features of course....but this is interconnection. You don't do that. :)

it's called tech locking when you do this and it's generally considered undesirable because it has what are called downstream negative impacts.

Lets say I build a godot server that provides services for many games....I have 1 game that was built with godot 4.3...Now I have to update the server too....uh oh....now all the other games that connect to this server are throwing errors, so now I have to update ALL of those games, and push those updates to all clients.

This is not a good thing to do....

**Comment by Faless** [comment]
> Lets say I build a godot server that provides services for many games...

That's simply not how the Godot high level multiplayer work, it is not among its design goals.

The multiplayer API is designed to support one game at a time, you can have "rooms" in the server (e.g. if you want multiple "matches" in the same instance, though the overhead is rarely worth it), but the server and clients must share at least part of the scene tree, and script RPCs must matches.

It's a protocol for multiplayer games (game logic synchronization), not for your backend infrastructure (there are much better protocols for that, like HTTP).

> If you MUST make an update like this between minor versions, you really should ensure backwards compatibility.

I disagree, keeping backwards compatibility on the high level multiplayer protocol would add a lot of overhead over time, which means worse network performance, and higher bandwidth usage, which are the number one priority.

Note that the only thing you need to do, is re-export your game with the new version, and release an update for your game. It is quite expected that you cannot play on a server hosting a new version of a game with an outdated client.

> I would suggest this is a release blocker...

I disagree... Again, the protocol is not meant (and never was) to be compatible across different Godot versions.

I agree this should be noted in the release notes, which is why the PR that made the changes (https://github.com/godotengine/godot/pull/90027) has the "breaks compat" flag.

**Comment by scotmcp** [comment]
Yeah I see it, I just wish I had known about that conversion or I would have participated in it.

Realize that in the technical world, use case our side of design principles is developed by users, not developers...developers can design a thing, but users figure out the ways to use it.

I can make a strong argument why Godot DOES work the way I said and that is WAS designed to work that way (for instance, supporting multiple interfaces, and concurrent clients, servers, and mixing clients and servers on a single runtime. When these things are _availaible_ to the user base, you can bet your user base is going to find ways to use them, and you can't say that's not how Godot works...because quite simply, it does work that way and it does it very very well.

You can (and I have) built application gateways and server clustering in to Godot using MultiPlayerAPI....just because it wasn't envisioned to be used that way, doesn't mean it shouldn't be used that way.
