### ISSUE TITLE
Lightmap Probes do not apply until dynamic object moves or updates in some way.

### ISSUE THREAD

**Issue by Braxtogoo** [godotengine/godot#94825]
### Tested versions

- Reproducible in: v4.3.rc1.official [e343dbbcc], v4.3.beta3.official [82cedc83c], v4.2.2.stable.official [15073afe3]

### System information

Godot v4.3.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 31.0.15.3742) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

This issue is likely related to or at least an addition to #77167 however I've noticed that in addition to the probes not applying after baking, it's also when first opening a scene and on play, requiring the dynamic objects to be wiggled to show the lightmap probe's effects.

Dynamic Sphere right after baking, opening the scene, or pressing play:
![image](https://github.com/user-attachments/assets/16fa10a5-5eda-421f-aec5-4acd9ac04cd6)

Dynamic Sphere after wiggling it a bit, note this shows another issue from #94824:
![image](https://github.com/user-attachments/assets/13a51550-d181-4f7e-a4df-036296aec58c)

### Steps to reproduce

- Make a basic scene with static and dynamic geometry, emissive objects, static or dynamic lights, Lightmap probes, and a LightmapGI node.
- Configure LightmapGI node, make sure all static geometry has a UV2 and adequate space on the lightmap, turn off preview light and world environment if you don't have your own.
- Bake lightmap.
- Observe.

### Minimal reproduction project (MRP)

- Open project.
- Turn off preview directional light.
- Observe.

You can see the probe effect suddenly pop in when wiggling the sphere. Additionally I added a camera so you can see it in run time, wiggling the sphere with the remote property inspector panel will have the same effect as the editor.

[Lightmap_Probes_Not_Applying.zip](https://github.com/user-attachments/files/16397920/Lightmap_Probes_Not_Applying.zip)

**Comment by SpockBauru** [comment]
I can confirm this bug on my end, objects with `gi_mode` set to `Dynamic` that doesn't move will not apply probe data when you run the scene. In addition, if an character have the animation disabled, the issue also happens.

Tested on the following tunnel scene with a character and a static capsule:

[LightProbeEnableTest.zip](https://github.com/user-attachments/files/16400932/LightProbeEnableTest.zip)

Another way to trigger the issue is to hide/show the LightmapGI node as shown in the video. Test steps on the video:
1) Hide/Show LightmapGI in order to trigger the bug.
1) Enabling the animation fixes the bug on the character.
1) Moving the capsule manually also fix the bug.


https://github.com/user-attachments/assets/07a6a3f6-d968-4970-98a6-f4a01e8d0708

System Info:
`Godot v4.3.rc1 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.5612) - 12th Gen Intel(R) Core(TM) i7-12700KF (20 Threads)`

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/godotengine/godot/issues/77167.
