### ISSUE TITLE
Obj import: messing up order of surface names, missing first, generating last.

### ISSUE THREAD

**Issue by OlivierVanHoutte** [godotengine/godot#94924]
### Tested versions

- Reproducable: 4.3.rc1 and v4.2.2.stable.official [15073afe3]
- Not Reproducable: v4.2.1.stable.official [b09f793f5]

### System information

Godot v4.3.rc1 - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 2060 (NVIDIA; 31.0.15.3742) - AMD Ryzen 7 4800H with Radeon Graphics (16 Threads)

### Issue description

When importing an obj with mtl files, the surface naming order is offset by one. 
The first surface name is skipped. 
The last surface name is generated based on the obj name.

In the example the names change from
- left (red) --> right 
- right  (green) --> cube

![image](https://github.com/user-attachments/assets/53d3cefc-084f-4bc5-8ebe-db1cbfbb5c3a)
![image](https://github.com/user-attachments/assets/4226f93e-c6b0-4190-8527-787888243ace)

OBJ materials are still assigned correctly. 
It's only the names that seem to be wrong.

![image](https://github.com/user-attachments/assets/c4d0144f-2230-4ad2-aef9-dc4636b1dab9)

### Steps to reproduce

Create an obj with 1 or more surfaces using mtl (in blender).
Import this object.
Check the surface names.

### Minimal reproduction project (MRP)

[MinimalProject.zip](https://github.com/user-attachments/files/16416625/MinimalProject.zip)
Bug reproduceable in brand new project.

**Comment by clayjohn** [comment]
Most likely a regression from https://github.com/godotengine/godot/pull/86365 I can see that surface names are assigned using `mesh->get_surface_count() - 1` but https://github.com/godotengine/godot/pull/86365 adds a new surface after assigning the surface name instead of before. So the new surface name overrides the surface before the one being added.

Code here:

https://github.com/godotengine/godot/blame/0e9caa2d9cb20737f8dcf08b75fcf2a78d980569/editor/import/3d/resource_importer_obj.cpp#L427-L452
