### ISSUE TITLE
Double Clicking Does Not Open External Text Editor When Godot "Script Editor" Is Disabled.

### ISSUE THREAD

**Issue by RingoutRingers** [godotengine/godot#94936]
### Tested versions

v4.2.2.stable

### System information

Godot v4.2.2.stable.mono - Windows 10.0.19045 - Vulkan (Forward+) - integrated AMD Radeon(TM) Graphics (Advanced Micro Devices, Inc.; 31.0.12044.59001) - AMD Ryzen 5 4500U with Radeon Graphics (6 Threads)

### Issue description

Normally, while an external text editor is set, double clicking on text files inside the FileSystem opens them with the external editor. However, when "ScriptEditor" is disabled from the Editor Feature Profile menu, double clicking on the text files in the file system doubles nothing.

### Steps to reproduce

- Go to: Editor Settings > Text Editor > External
- Set "Use External Editor" to on and specify file path.
- On the top left corner, go to the Editor dropdown, and click "Manage Editor Features"
- Disable "Script Editor" under your current profile (or make a new profile, and click "Make Current")
- Double click any text file in the file system.

### Minimal reproduction project (MRP)

N / A

**Comment by AThousandShips** [comment]
Thank you for reporting, consolidating in:
* https://github.com/godotengine/godot/issues/59758

See there for more details, if you think something was missed about this and it's not the same issue, please comment here and it can be reopened

**Comment by RingoutRingers** [comment]
You are correct. It is the same issue.

**Comment by EdmarDev** [comment]
> You are correct. It is the same issue. This is in a different version of the editor, but the problem is the same.

Is it really? I found this issue because for me, even without disabling the Script Editor, double clicking a .txt or .json file while having an external editor set up will not open it in any editor. If I manually switch to the Script Editor I can see the file, but it won't switch to the Script Editor on double click like it does without an external editor. I could not get .txt and .json files to open in vscode with any settings. 

Is this behavior different for you? I've tested in godot 4.3 and 4.2.1
