### ISSUE TITLE
Project manager prevents screensaver/powersaving from starting

### ISSUE THREAD

**Issue by scotmcp** [godotengine/godot#95020]
### Tested versions

Godot v4.3.rc1.mono - Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### System information

Linux Mint 21.3 (Virginia) - X11 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4060 Ti - AMD Ryzen 7 5700X 8-Core Processor (16 Threads)

### Issue description

Running Godot including an empty project or even just the project manager prevents the screensaver from starting and therefore also prevents monitor powersaving.

This behavior was not present in 4.0.x, 4.1.x nor 4.2.x .... just 4.3 versions.

### Steps to reproduce

For faster results, set screensaver to lowest time to start
start godot and wait.

### Minimal reproduction project (MRP)

A new empty project or even just opening the project manager is enough.

**Comment by TheColorRed** [comment]
I'm on 4.2.2, and I believe that I have seen this problem.

**Comment by RedMser** [comment]
Screen staying on depends on the `display/window/energy_saving/keep_screen_on` project setting. It is supposed to be overridden to `false` for the editor.

I can confirm the Project Manager keeps screen on (likely since it does not count as editor). But any project - including newly created ones, and those created in 4.0 - turns off screen as intended. Tested on Windows by running `powercfg /requests` in admin powershell.

Some regression might have been caused by https://github.com/godotengine/godot/pull/85678

**Comment by akien-mga** [comment]
Yeah #85678 would have changed behavior here, previously it would override `keep_screen_on` for anything running from an editor binary (`TOOLS_ENABLED`), which includes the editor itself, the project manager, or running the project from the editor or directly from the command line using the editor binary (`editor` feature).

Now it's only overriding it for `editor_hint`, which is running the actual editor application, and that no longer includes the project manager.

We should maybe include the PM in `_is_editor` @KoBeWi ?
Or change this one back to `.editor` but that means also disabling `keep_screen_on` for running a project directly with a `TOOLS_ENABLED` build.

**Comment by KoBeWi** [comment]
> We should maybe include the PM in _is_editor

Well I remember being surprised that PM isn't considered editor already. Maybe there is a reason for that.

Alternatively there is `screen_set_keep_on()` method in DisplayServer, which we could just call manually.

**Comment by akien-mga** [comment]
I think the setting override is nice to have, as this is a behavior that users might want to tweak.

For example, while testing the Android editor, I found it really frustrating that it would sleep on my relatively fast phone sleep timer. If I used it more regularly I'd likely toggle that setting off so that the editor does prevent from sleeping.

**Comment by KoBeWi** [comment]
Well, it can be set based on the setting. Still manually.

**Comment by Calinou** [comment]
> For example, while testing the Android editor, I found it really frustrating that it would sleep on my relatively fast phone sleep timer. If I used it more regularly I'd likely toggle that setting off so that the editor does prevent from sleeping.

This editor-specific behavior should be governed by an editor setting, not the current project's setting.
