### ISSUE TITLE
Severe regression in asset import speeds

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#95104]
### Tested versions

- Reproducible in: v4.3.rc2
- Not reproducible in: v4.2.2.stable

### System information

Godot v4.3.rc2 - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6070) - AMD Ryzen 5 5600H with Radeon Graphics (12 Threads)

### Issue description

First off, I will say that it feels like pretty much *everything* is slower in 4.3. Even simple things like changing project settings. But this one is the most egregious - it completely annihilates iteration speed.

4.2 import times:

https://github.com/user-attachments/assets/fd566595-1e3f-426a-b07f-d63618c941ab

4.3 import times:

https://github.com/user-attachments/assets/c84fd29b-e299-4774-8214-62e40d83ae88

It applies to all kinds of assets - so even something like creating a new material involves wait times of up to a minute.

### Steps to reproduce

I have not confirmed yet, but the issue seems to only show up on large projects.

On [Crater-Province-Level](https://github.com/Jamsers/Crater-Province-Level), to reproduce the video example:

- Open project in Godot
- Open `Asset Sources/Model/Tunnel_All.blend` in Blender
- Export as glTF to `Models/Tunnel_All.glb`
- Switch back to Godot window and wait until scene window is responsive again

### Minimal reproduction project (MRP)

Crater-Province-Level:
[`test-4.2`](https://github.com/Jamsers/Crater-Province-Level/tree/test-4.2) branch

**Comment by Calinou** [comment]
Can you test all pre-releases between 4.2.2 and 4.3.rc2 to bisect the regression? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.3/).

Make sure to remove the `.godot/` folder between each test.

**Comment by Jamsers** [comment]
[#93877](https://github.com/godotengine/godot/issues/93877) was actually my first guess, but disabling (editor) vsync and enabling continuous update didn't seem to help, so I reported this separate issue.

I'll try to bisect soon when I have the time.

**Comment by Jamsers** [comment]
Sorry having a tough time bisecting cause I'm running into [#89312](https://github.com/godotengine/godot/issues/89312), I'll try to rejigger the test projects and try again

**Comment by Jamsers** [comment]
Finished bisecting. The regression was introduced with commit [846bafd](https://github.com/godotengine/godot/commit/846bafd47fc3902f41aec532164ed8bd73ff9e83).

**Comment by akien-mga** [comment]
That's #92279, CC @SaracenOne @lyuma @fire.

**Comment by fire** [comment]
TODO: get a profile to see what is slow

**Comment by lyuma** [comment]
If this is related to that commit, it should be caused by the code to handle refreshing the open scenes, not the editor scene import system 

can you verify if import is fast when there are no scenes open (close all scenes before saving the glb, and see how long until the editor is responsive)

That way we can rule out the core import system and focus instead on optimizing refreshing the open scenes.

**Comment by Jamsers** [comment]
Just tested, import is *blazing* fast when all scenes are closed. Also noticed while testing that closing and opening a scene is really slow, especially big scenes.

**Comment by Hilderin** [comment]
I'll do some debugging on that. On my computer I see way worst performance problem then @Jamsers with the MRP. Just opening a scene could take 1 min. and reimporting takes almost 2-3 min. On a debug build, it's even a lot worst.

**Comment by Hilderin** [comment]
So far, I found 2 main problems:
- When opening the scene, the it takes 40 sec to request gizmos. When I comment `Node3DEditor::_request_gizmo` and `Node3DEditor::_request_gizmo`, it's down to 25 secs and the Editor is way more responsive right after the scene is loaded.
- There are definitively some regression caused by #94093. Currently, preload_reimporting_with_path_in_edited_scenes take 9 sec and update_node_reference_modification_table_for_node 9 sec when reimporting. I'll look into the performance for reload the scene when reimporting.

**Comment by Hilderin** [comment]
I think I'm on the right track, finally, the major issues were from e57312d and #90531.
- e57312d caused an iteration on all node in the scene to find every modifications with update_node_reference_modification_table_for_node.
- #90531 caused a removal and an add of the scenes on the reimport process.

I need to retest a lot of things from #94093 to see if I did not break anything and check how to fix e57312d and #90531 another way before creating a PR.

https://github.com/user-attachments/assets/a4f00d9b-0be0-48d7-8bb5-69dd86db3dae
