### ISSUE TITLE
Allow Godot 3.0 UI to be used as theme for game projects

### ISSUE THREAD

**Issue by ol-smaug** [godotengine/godot#9516]
**Operating system or device - Godot version:**
Windows 7 64-bit - Godot 3.0

**Issue description:**
Currently, when creating a game project with Godot 3.0, the old Godot theme is used for any UI components within your project. It would be great if there was an option to use the new Godot 3.0 theme for your project. This would especially benefit application-type projects or games that are more UI-oriented.

**Comment by toger5** [comment]
I also like the idea. But as far as I'm concerns the editor theme became part of the tools. So it is not even part of the compiled engine (without editor).
It still should be possible to just save the theme since it is available as a resource in the editor.
But you are right, it still should be an option. 
My proposal would be to add a preset function in the theme popup. (when selecting a theme in the Inspector). There would be a list with presets. for now only the 3.0 theme and the normal theme. But in the future ppl could also add themes to their installed godot so they also can use their own favourite theme in every project without selecting it in the file browser all the time. (like the code snippets)

**Comment by Hinsbart** [comment]
Implemented in #12718.

**Comment by toger5** [comment]
the theme editor bg is still the old color which is kind of funny ;)
