### ISSUE TITLE
Can't begin a text selection outside the bounds of a `RichTextLabel`

### ISSUE THREAD

**Issue by eviltrout** [godotengine/godot#95298]
### Tested versions

- Reproducible in Godot 4.2.2 stable
- Reproducible in Godot 4.3-rc3

### System information

Windows 11 Pro - Godot 4.3-rc3

### Issue description

If you click and start to select text from the outside of a `RichTextLabel` it does not begin selecting. You must start selecting _within_ the boundary.

![cant-select](https://github.com/user-attachments/assets/95e98b95-d8ea-40ea-9547-56605f781eb6)

In other GUIs, such as web browsers, selection can begin in the margins, which is useful because otherwise getting the first few characters is very challenging.

![good-select-example](https://github.com/user-attachments/assets/cb6a0ba4-f01b-472f-925a-835a1e90b36a)

--- 
One thing I tried is to add an `[indent]` around the text using BBCode, and it allows you begin selecting outside of the line, but always begins with the beginning of the paragraph, not the current line you're on, which also is confusing to a user:

![cant-select-indent](https://github.com/user-attachments/assets/4dacc6ab-7f3b-4d1a-a8f4-efac82edeca7)

### Steps to reproduce

1. Add a selectable `RichTextLabel` with text in it, and position it in a window manually or via `MarginContainer`
2. Run the project
3. Try to select text by clicking outside the rich text label and dragging your mouse into it. Nothing will happen.

### Minimal reproduction project (MRP)

[drag-example.zip](https://github.com/user-attachments/files/16552438/drag-example.zip)

**Comment by bruvzg** [comment]
`[indent]` bug should be fixed by https://github.com/godotengine/godot/pull/95301 (and should also work when selecting from a content margin added by `StyleBox`).

Selecting from outside of control is a pretty strange thing to expect. I would not consider it a bug (web page act as a single control, so it's not the same, browser won't start selection if you are dragging from a menu bar for example).

Maybe open a proposal at https://github.com/godotengine/godot-proposals/ to see if it's a desired behavior.

**Comment by eviltrout** [comment]
Because #95301 allow this to work with a content margin this issue is no longer necessary, because I can add a content margin to the RichTextLabel and that allows the user to begin selecting before the letter and is very user friendly. Thank you.
