### ISSUE TITLE
OpenXR composition layers perform sRGB conversion on android, when color space is already sRGB

### ISSUE THREAD

**Issue by decacis** [godotengine/godot#95313]
### Tested versions

- Tested on v4.3-rc2

### System information

Oculus Quest 2, Compatibility GL

### Issue description

When using the new composition layers in VR, it seems like the Quest performs sRGB conversion when it shouldn't. This only happens on android (Meta Quest 2) and it works correctly on PC. I don't know if this happens with other headsets or even with other Quest devices.

| What it looks like | What it should look like |
|-------------------|--------------------------|
| ![Xiaosaurus-Bouncy-Regular](https://github.com/user-attachments/assets/8359c4de-baee-425d-81de-97b4ac8ec668) | ![Amethystsunbird-Forked-Darkolivegreen](https://github.com/user-attachments/assets/5283757e-7067-4b4c-816e-874ad80a5a4d) |

I can more or less confirm this is the issue because I wrote a shader that essentially reverts the sRGB conversion, and with that shader it looks ok. Shader:

```
shader_type canvas_item;
render_mode unshaded;

uniform sampler2D screen : source_color, hint_screen_texture, filter_linear, repeat_enable;


void fragment() {
	vec4 screen_texture = texture(screen, SCREEN_UV);
	screen_texture.rgb = pow(screen_texture.rgb, vec3(1.0 / 0.45));
	COLOR = screen_texture;
}
```

And here's a video of me enabling/disabling the shader:

https://github.com/user-attachments/assets/29f1a763-b280-4b2e-96e9-71d58392b4a5

### Steps to reproduce

- Create a SubViewport with a simple `TextureRect` with an image as a child.
- Create a `OpenXRCompositionLayerQuad`

### Minimal reproduction project (MRP)

The issue is easily reproducible, and adding the vendors plugin would make the project too big to upload.

**Comment by akien-mga** [comment]
CC @godotengine/xr

**Comment by decacis** [comment]
Not sure if this is relevant, but in #74892 at the end it says:

> Note that these changes only effect the 3D render pipeline. The use cases where this is needed don't render 2D elements to the viewport that is effected by this.

But now with composition layers, this changed (I think?)

**Comment by dsnopek** [comment]
Thanks for the report!

This will be a little tricky to solve. The changes in #74892 work by enabling/disabling the hardware sRGB conversion before/after the XR viewport is rendered, which we can do because there's functions called on the primary `XRInterface` before/after the XR viewport is rendered. We don't presently have any hooks that call into `XRInterface` when any other viewports are being rendered, so we don't have a good place to do the same thing for the 2D viewports that are rendered to the composition layers.

I wonder if we could add a function to `RendererTextureStorage` like `render_target_set_srgb_conversion(bool p_enable)` that we could use on the render targets for the viewports being used by composition layers? Then the OpenGL renderer could look for that flag and do `glDisable(GL_FRAMEBUFFER_SRGB)`.

I don't know if that's an actually good idea, but I may test it later to see if it would at least work.

**Comment by BastiaanOlij** [comment]
@dsnopek, hmm I had forgotten we did this as part of the special logic when the XR flag is set, which is not the case here off course as it's a normal render buffer we render too.

The problem is that this feels so hacky. Godot itself was written where it does all sRGB conversions itself and where the render target is a normal GL_RGBA8 buffer. No hardware conversions are thus done but it also means the hardware thinks we have linear color data in that buffer, not sRGB, which doesn't matter to Godot because we control the output.
But when giving that buffer to OpenXR, we get an unwanted sRGB conversion.

That is why we use an GL_SRGB8_ALPHA8, but now when we write to it,  we do an sRGB conversion AND the hardware does an sRGB conversion, and we end up doubling up, hence the issue Decasis is seeing.

A nicer option really would be if we could just rely on the hardware sRGB conversion and skip the sRGB conversion in the shader, but that has a lot of impact.
Also I have no idea what this would do to the 2D pipeline which entirely relies on doing everything in sRGB space, and where we are doing this all ourselves.

**Comment by dsnopek** [comment]
I've been spending some time looking into this, and it seems to me that we should always be using `glDisable(GL_FRAMEBUFFER_SRGB)` in Godot's OpenGL renderer, unconditionally.

Let me explain:

- OpenGL will only do the linear to sRGB conversion enabled via `glEnable(GL_FRAMEBUFFER_SRGB)` on FBO's that have a color attachment which uses an sRGB internal format. So, it will do the conversion on `GL_SRGB8_ALPHA8`, but _not_ on `GL_RGBA8`
- Godot's renderer doesn't normally use any sRGB internal formats for render buffers, because we do the linear to sRGB conversion ourselves in our shaders
- OpenXR is only using `GL_SRGB8_ALPHA8` in OpenXR, because if we don't, the OpenXR compositor will assume the content is linear, and it'll do another linear to sRGB conversion. So, we're forced to use that as the internal format, in order to signal that we're giving it sRGB data
- It should be safe to do `glDisable(GL_FRAMEBUFFER_SRGB)` unconditionally, because Godot's OpenGL renderer isn't even relying on that anyway (as explained above in my second point in this list)

As a test, I've just put this code into `drivers/gles3/storage/config.cpp`:

```
#ifndef GL_FRAMEBUFFER_SRGB
#define GL_FRAMEBUFFER_SRGB 0x8DB9
#endif

glDisable(GL_FRAMEBUFFER_SRGB);
```

... and it fixes the composition layer colors without seeming to cause any additional problems in other contexts.

I'll try and find the right place to put that (`config.cpp` was just for a quick test), and make a PR for further discussion/testing.
