### ISSUE TITLE
more flexibile camera placment methods

### ISSUE THREAD

**Issue by Gibbz** [godotengine/godot#9550]
I havent found a way to freecam an in editor camera. This is by far the best way to position and animate cameras by actually looking through them in the fps view. Then locking them in place once your happy with the shot.

Also would be great to have some kind of safe frame preview for framing shots.

Maybe a way to snap a camera to the current view also would be a handy addition with that.

**Comment by Gibbz** [comment]
Also would be amazing to have a target look camera!!!

**Comment by eon-s** [comment]
Something like that "align selection with view" option in the "perspective" menu?

**Comment by nunodonato** [comment]
related: #20248

**Comment by dodgyville** [comment]
Would love to see this implemented. For light objects too. Related: #12083

**Comment by rhulha** [comment]
> Also would be amazing to have a target look camera!!!

I wrote a plugin that can snap the camera to a scene object.
Check it out here: https://github.com/rhulha/godotengine_snap_cam_plugin

**Comment by tinmanjuggernaut** [comment]
As I noted on closed duplicate #20248:

> It would be very nice to have a fly mode for the previewed camera that sets its position and rotation (like Blender's shift+f when looking through a camera). I think that the controls to move the editor camera should automatically work on the look-through camera once they check the Preview box. That seamless transition is what is expected by at least a few people on this thread.

**Comment by dodgyville** [comment]
Free roam for cameras and spotlights when in preview mode for those objects is my #1 missing feature in godot by a mile. It's almost impossible to place the camera and lights exactly where I want them without it.

**Comment by Calinou** [comment]
@dodgyville Please don't bump issues without contributing significant new information; use the :+1: reaction button on the first post instead.

**Comment by dodgyville** [comment]
Sorry, I thought you were merging all the free roam object jiras into this one.

**Comment by Calinou** [comment]
@dodgyville This is indeed what I'm doing, but what I mean here is that you shouldn't bump issues in the hope to get them implemented faster (it doesn't work anyway).

**Comment by dodgyville** [comment]
I'm glad you bumped these jiras actually. I've been thinking a lot about this issue. Have we considered code bounties? I could chip in for this feature to be finally fixed.

**Comment by Calinou** [comment]
@dodgyville We don't have an official bounty system, but you're free to propose a bounty on your own. Still, in this case, we don't make any warranty about the code being mergeable as-is :slightly_smiling_face:

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!

**Comment by golddotasksquestions** [comment]
For those interested, I created a proposal for this feature here: https://github.com/godotengine/godot-proposals/issues/3297
