### ISSUE TITLE
4.3 can't open Vulkan Mobile project (Windows 10 with HD Graphics 5500)

### ISSUE THREAD

**Issue by vector3cat** [godotengine/godot#95627]
### Tested versions

- Reproducible in: 4.3-stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - Intel(R) HD Graphics 5500 (Intel Corporation; 20.19.15.4963) - Intel(R) Core(TM) i5-5300 CPU @ 2.30GHz (4 Threads)

### Issue description

the problem is that after updating to 4.3, opening a project will cause godot to stop responding in my vulkan(mobile) pc and if i check the cmd console there will be a lot of errors showing up infinitely
the bug has appeared in 4.3 and if i go back to 4.2.2 and use it with the proper .bat file for opengl, there wont be any problems.

### Steps to reproduce

open godot 4.3-stable, open your project

### Minimal reproduction project (MRP)

the project i opened was a new project, so there wasnt anything in it and the bug can be reproducible with an empty, new project

**Comment by AThousandShips** [comment]
Please show the errors that you are getting

**Comment by akien-mga** [comment]
> Intel(R) HD Graphics 5500 (Intel Corporation; 20.19.15.4963)

This issue is very likely an Intel driver bug, but sadly they no longer support your hardware.

I would suggest trying to update your Intel graphics drivers to the latest version from Intel, which seems to be this 15.40.48.5171 from 2021: https://www.intel.com/content/www/us/en/download/18369/intel-graphics-driver-for-windows-15-40.html

The number is lower than your 20.19.15.4963, but Intel versioning is a mess, apparently that version is from 2018: https://drivers.softpedia.com/get/GRAPHICS-BOARD/INTEL/Intel-HD-Graphics-Driver-20-19-15-4963.shtml

Aside from this, you can also test previous dev/beta/RC snapshots from https://godotengine.org/download/archive/ to pinpoint where the regression happened, so we can see if it could be worked around. But it's very likely part of some major Vulkan renderer changes which caused it to run into this Intel driver bug, which we can't fix ourselves.

**Comment by vector3cat** [comment]
thanks guys
the problem was actually the graphics card as you all mentioned!
