### ISSUE TITLE
Can't drag things between monitors anymore since 4.3

### ISSUE THREAD

**Issue by desastreger** [godotengine/godot#95639]
### Tested versions

4.3 stable

### System information

Windows 10 - 4.3 stable - Forward+

### Issue description

Updated to 4.3 and now I can't drag nodes between monitors.  I have my setup as in the image (central editor in the middle and filesystem, scene and Node Inspectors on the left monitor) and if I have nodes in my scene inspector that I want to drag to my script in the central monitor it won't take many times.  I saw this mentioned on Reddit as well.

Same happens if I have an object in the filesystem into a node in the node inspector.

![image](https://github.com/user-attachments/assets/a27172a2-a982-48cb-a69b-d09ab6225c24)
(screenshot is on 4.2.1 because I had to revert to continue working)

### Steps to reproduce

Drag node from scene inspector in one monitor to code editor on a different monitor

### Minimal reproduction project (MRP)

N/A

**Comment by AeioMuch** [comment]
From my tests, the problem in 4.3 compared to 4.2.2 is that the detached dock window must first have the focus when you initiate the drag, or it will not work, does not matter if it is between different monitors or not. To be clear, to make it work you must first click the dock window, then start the drag. Second issue that also affect 4.2.2 is that the drag preview that follow the mouse cursor is not working between windows either.

**Comment by Calinou** [comment]
@desastreger Can you try following the same steps on 4.3 dev/beta/RCs to determine when the regression started? You can download them [here](https://downloads.tuxfamily.org/godotengine/4.3/).

**Comment by tetrapod00** [comment]
Since window focus matters, I thought I would test this to see if anything was different https://github.com/godotengine/godot/pull/95606.

In 4.3.stable:
- When Scene tab is attached, drag and drop to Script tab **works**.
- With floating Scene window on the same display as Script tab: drag and drop **works**.
- With floating Scene window on another display, Scene window **focused**: drag and drop **works**.
- With floating Scene window on another display, Scene window **unfocused**: drag and drop **does not work**. No reference to a node is placed in the scripting editor. Also, releasing LMB on the main display does not actually end the dragging action. This is still visible:

![fE8Hu9zNfr](https://github.com/user-attachments/assets/073e2dea-b942-433b-9d32-dcc235d7fab3)

With the artifact from this PR:
**Same behavior** in all cases.

Specs: Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1660 Ti with Max-Q Design (NVIDIA; 32.0.15.5612) - AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx (8 Threads)

**Comment by AeioMuch** [comment]
Bisected to https://github.com/godotengine/godot/commit/12fda2fc13426799bd4376c1fbd99b179c685559 (https://github.com/godotengine/godot/pull/91361)
cc @RandomShaper

**Comment by Hilderin** [comment]
I'm able to reproduce on only one monitor. Windows 11 Godot 4.3 rc3

If Destination has focus before draging, it's working but the cursor is incorrect when the drag&drop could be completed.

https://github.com/user-attachments/assets/3e6ddc7c-a584-47ba-8219-e5bd6b33c434

**Comment by kitbdev** [comment]
- related https://github.com/godotengine/godot/pull/67531
