### ISSUE TITLE
PhysicalBoneSimulator3D scaling PhysicalBone3D childrens based on root node scaling

### ISSUE THREAD

**Issue by moongdevstudio** [godotengine/godot#95679]
### Tested versions

Bug occurs in 4.3 stable, doesn't appear in 4.2.2 stable (previous version I used on my project)

### System information

Godot v4.3.stable (https://github.com/godotengine/godot/commit/77dcf97d82cbfe4e4615475fa52ca03da645dbd8) - Windows 11- Vulkan (Forward+) -  NVIDIA GeForce RTX 3080 13700K

### Issue description

So I  was porting my old ragdoll node from 4.2 using the new PhysicalBoneSimulator3D node and I noticed a weird behaviour. My root node (Node3D) is scaled to 2 on all axis (and it used to work well in 4.2) and somehow the PhysicalBone3D children of the bone simulator node are getting automatically scaled based on the value of the root node

And what's even weirder is that it's not even trying to scale it up to 2 but instead dividing by 2. If I set my root node scaling to 4 all my physicalbone3D will have a 0.25 x,y,z scaling. Obviously this also change the size of the collisionshape under the physicalbone3D which makes the ragdoll works bad when scaling.

I cannot modify the scaling manually as it seem to be forced at the value based on root scaling.

### Steps to reproduce

put a Skeleton3D under a Node3d node, add up a SkeletonModifier3D node, fill it with a few PhysicalBone3D nodes and try changing the scaling values of the Root Node3D. You will see the scaling value of each physicalbone3D get divided by the amount of scaling you have set up

### Minimal reproduction project (MRP)

None

**Comment by TokageItLab** [comment]
I have tested the scaling of a parent node that contains a PhysicalBone as a child, and while the behavior is different between 4.3 and later and prior 4.2, but I have confirmed that both are not working correctly.

Without scaling:

https://github.com/user-attachments/assets/9c59a617-9019-4966-8afa-de4ec24a3c62

In prior to 4.2, when the simulation is started, Skeleton ignores the parent scaling and tries to go back to the original scaling:

https://github.com/user-attachments/assets/49134a72-3ebf-46e1-ac0e-703672a66d16

In 4.3 and later, it still tries to maintain the bone lengths, but each tries to revert to its original scaling, so it is still not working correctly:

https://github.com/user-attachments/assets/945dec70-62a4-4f36-9d51-7b458f83e6ee

I assume the reason is that the Collision Resource Scaling is not affected by the Node Scale, but **the Node Scale with Collision is not recommended for 2D or 3D in the first place**. See also https://docs.godotengine.org/en/stable/tutorials/physics/troubleshooting_physics_issues.html#scaled-physics-bodies-or-collision-shapes-do-not-collide-correctly.

Although the prior 4.2 behavior may indeed be better in that it does not model look broken, 4.3 is more correct in that it keeps the length. However, since both are not working correctly, I conclude that it is not worth the effort to change the behavior back to 4.2. Instead, an effort should be made to ensure that the correct scale is maintained.

**Comment by moongdevstudio** [comment]
Ok thanks I did try a few things and managed to "fix" the issue at least on my end.

This is not ideal but basically what i'm doing is manually rescaling the collisionshape after initiating the bone simulation. 

I used to set the size of the main node using a global_transform when initiating it but it caused a bunch of scaling issues too so now i'm just setting it beforehand and adjusting the collision shapes size manually.

I wasn't aware of the issue with scaled nodes as I've used many and usually it was working fine, i'll try not to use those until a fix is out.
