### ISSUE TITLE
With fading, root motion does not correctly extract local position by rotation accumulator

### ISSUE THREAD

**Issue by vaner-org** [godotengine/godot#95688]
### Tested versions

Reproducible in any 4.x

### System information

Godot v4.3.stable - Windows 10.0.19044 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.5612) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

The root motion accumulator system, while a huge step up from 3.5, is still unable to address crossfading.

# The problem

When a character is crossfading from one animation to another, they will often transition in such a way that undesired diagonal or negative movement is created from using the blended root rotation accumulator of the two animations against their blended root motion. Practically speaking, only a root-aligned movement vector needs to be considered.

Allow me to explain.

I have a 90 degree walk start, in two directions.

Left            |  Right
:-------------------------:|:-------------------------:
![left](https://github.com/user-attachments/assets/376a4a64-71b0-42fd-9101-4d7746720e4f) | ![right](https://github.com/user-attachments/assets/1e02df5d-f669-49f9-995c-b31923efab28)

Taking the right animation for instance, because the animation ends with the root motion accumulator facing -X, while my normal walk cycle starts facing -Y (+Z in Godot), what ends up happening is diagonal drift when xfading the two.

To demonstrate this, I have slowed down the start animation with a TimeScale while keeping the walk cycle at normal speed to exaggerate the effect of this drift.

No xfade:

https://github.com/user-attachments/assets/310bcf7d-38bb-48f8-9b5f-323121856774

0.2 xfade:

https://github.com/user-attachments/assets/f0ffa2f5-63e2-4818-a7c9-7eeb49df96d6

Here is how I handle my root motion, for my Auto-Rig Pro character in Blender for a root bone with a Z-up, Y-forward orientation.

```
root_movement = $AnimationTree.get_root_motion_position() / delta
root_rotation = $AnimationTree.get_root_motion_rotation()

if abs(root_rotation.get_euler().z) > 0:
	rotate_y(root_rotation.get_euler().z)

# root direction in animation space
var root_rotation_accumulator = animation_tree.get_root_motion_rotation_accumulator()
	
# rotating the movement vector to be in root's local space
var root_aligned_movement_vector = -root_movement.rotated(Vector3.UP, -root_rotation_accumulator.get_euler().y)
	
# rotating vector to be in global space
var vel: Vector3 = global_basis.get_rotation_quaternion() * root_aligned_movement_vector

DebugDraw3D.draw_line(global_position, global_position + vel, Color.RED)
```

I came up with this independently of the documentation but from my testing should yield an identical result to [the documented method.](https://github.com/godotengine/godot/issues/90402#issuecomment-2044050212)

# The solution

1. Either correctly interpret, or let us define the forward direction of the root bone in AnimationMixer.

![Godot_v4 3-stable_win64_lRwkMSHG2q - Copy](https://github.com/user-attachments/assets/897bc404-6940-4886-b9e1-c751b5d6d3cc)

Since the current get_root_motion_position()/get_root_motion_rotation() operates under "global" space,

2. Provide a way to get the neutralized root motion position and rotation vectors in the LOCAL space of the root bone, so that crossfading becomes possible without errors. This would mean that for a simple animation like my turn, each frame of get_root_motion_local_position would be largely towards the bone's forward axis, and each get_root_motion_local_rotation would be entirely on the bone's up axis.

Using these "local" values in root motion code would allow for identical results with smooth crossfades. In my mind, this seems to be the most straightforward way to address this, @TokageItLab might have a better idea.

### Steps to reproduce

Download the project, play it, press WASD to move at a 90 degree angle from the facing direction and observe the drift.
Then, open AnimationTree > move > start and change the fadeout time to 0. Try again, and observe lack of drift.

### Minimal reproduction project (MRP)

[root_motion_drift_MRP.zip](https://github.com/user-attachments/files/16644543/root_motion_drift_MRP.zip)

**Comment by TokageItLab** [comment]
I remember this matter being pointed out in the past as another issue. The problem is simpler: there is no actual Transform there in root motion dwlta.

Consider the case of a 90deg rotation without a move, the actual total delta of the root motion is short of 90deg due to the crossfade.

It is the same for translation: if the root motion moves 1m and there is a crossfade, the total actual delta will be less than 1m.

I wonder if other game engines handle it correctly. If so, there may be a solution by making some changes to the delta calculation process, but I don't know, I haven't researched it in detail. It would be helpful to make a survey comparing the root motion system in several engine/environments.

**Comment by lullabyist** [comment]
> Consider the case of a 90deg rotation without a move, the actual total delta of the root motion is short of 90deg due to the crossfade.
> 
> It is the same for translation: if the root motion moves 1m and there is a crossfade, the total actual delta will be less than 1m.

Even with duration accounted for and a perfect handoff via xfade, we would still get drift. Consider this:

![root_motion_issue](https://github.com/user-attachments/assets/ab21fbc1-e9bc-49dd-b1a8-20c53576308e)

Even though the blend should treat the crossfade region as the exact same thing while keeping movement vector intact, it doesn't, because:

with get_root_motion returning position and rotation world space:

1. animation A's root motion accumulator points to -X while animation B's root motion accumulator points to +Z, and
2. A's root motion position delta returns (-0.1, 0, 0) and B's returns (0,0,0.1) for the entire duration of the crossfade, with our only way of neutralizing these two being an already skewed (blended) root motion accumulator.

So, we would move diagonally, between +Z and -X, during the crossfade. That's the issue.

Accumulator was a step in the right direction but all that was really needed was just returning a movement delta that treated the root bone's axes as (0,0,0).

**Comment by TokageItLab** [comment]
I see the essence of the problem now.

Node3D's transform performs rotation after position as specification (also consistent with glTF), but CharacterBody's velocity performs position after rotation, so it is necessary to get the local position by accumulator.

However, if there is fading, the sum of the root motion delta and the root motion accumulator delta will be different, this is exactly what the problem is.

I am not sure if this problem can be solved by simply calculating the delta of the root motion position in local space, taking into account the rotation, but I will investigate later.

**Comment by lullabyist** [comment]
> I am not sure if this problem can be solved by simply calculating the delta of the root motion position in local space before blending, taking into account the rotation, but I will investigate later.

I appreciate it. Please test against my minimal reproduction project as this problem is a little tricky to highlight in ordinary use.

**Comment by TokageItLab** [comment]
I sent https://github.com/godotengine/godot/pull/99394, please check if it helps and calculates correctly.
