### ISSUE TITLE
getting $AnimationTree[parameters/AnimationNodeName/current_position] when the node is OneShot and with fadeout time will reset the position when fadeout start

### ISSUE THREAD

**Issue by nagasawamaki** [godotengine/godot#95899]
### Tested versions

Godot v4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) 

### Issue description

getting `$AnimationTree[parameters/AnimationNodeName/current_position]` when the node is OneShot and with fadeout time will reset the position when fadeout start

in 4.2.2 I call `$AnimationTree[parameters/AnimationNodeName/time]` and it works fine

### Steps to reproduce

- create a OneShot node with fadeout time set

- request the oneshot node to active

- print $AnimationTree[parameters/AnimationNodeName/current_position]

- the position will be reset when fadeout start

**Comment by TokageItLab** [comment]
You should clarify what you mean by the position being reset.

Do you mean that the animation that is playing is actually visually reset? Or do you mean that the time to retrieve is in a state you do not want it to be in?

If the former, it is a bug, but if the latter, it is the intended behavior; It provides the same behavior as a StateMachine.
Since the OneShot state is transitioned to the next state immediately after the fadeout starts, it will return the time of the AnimationNode connected to the in port, not the shot port. In that case, you should consider calculating the time you want by `[parameters/AnimationNodeOneShot/fade_out_remaining]` etc.

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
