### ISSUE TITLE
looped animations give unexpected results

### ISSUE THREAD

**Issue by adolson** [godotengine/godot#959]
If you loop an animation and use the continuous interpolation mode, after the last keyframe in a track, things get wonky. If you have a keyframe at the very end of the animation's length, the value will loop back to 0 immediately. If you have a keyframe earlier, it'll count down from that keyframe back to the first keyframe in the track.

I've never seen a loop behave like this before. I tested this in v0.99.3653-pre-beta from January 3rd, and get the same behavior, so this isn't a regression, by the look of it.

Here's a video showing how to reproduce this, in case it's not clear what I'm saying: http://youtu.be/Ti0OBfWR4a8

I can't see why anyone in their right mind would WANT this behavior to happen automatically, since they could simply keyframe back down at the end of the animation. But those of us who don't want this behavior don't have any option unless we want to insert keyframes for EVERY value... Which is simply making things far more tedious than need be. Even extending the animation a bit, inserting a duplicate keyframe there, then setting the length back to the desired value doesn't prevent this from happening (keyframe past length is just ignored, as would logically be expected).

**Comment by Cybolic** [comment]
Argh, so this is why my animation looks strange! I stumbled on to this bug report through a Google search, not even looking for the issue; up until now I had just assumed I was a lousy animator.
Can we please have a toggle for this behaviour?

**Comment by reduz** [comment]
it does not interpolate back unless it is set to looping
you mean looping without interpolating back? i guess it could be made
optional

**Comment by Cybolic** [comment]
I don't mind interpolating back (though I think it should be optional), my issue is when for example the last keyframe is set to frame 10, but it actually plays frame 0.

**Comment by adolson** [comment]
If there is a frame keyframe at the very end of the animation track, the
expected behavior is that it won't interpolate when it loops, so it should
disable automatically in those cases. However, I'd prefer it as an option
anyhow, because I can see other use cases where interpolation is only
desired inside the iteration and not between loops.

**Comment by adolson** [comment]
Will this be fixed in 1.2?

**Comment by akien-mga** [comment]
What's the status on this issue? I actually never noticed it, I guess I'll have to check my animations to see if they are not actually behaving as I intended them to (though I think I have a keyframe at the very end of each animation so I might be exempt from this bug/feature).

**Comment by adolson** [comment]
I haven't had time to test recently. I did try opening a project but there are too many changes so I'd have to find some time to specifically do some testing in the current version. However, as several of the comments stated, it didn't matter if you had a keyframe at the end, the buggy look still persisted. Some animations it was a lot more noticeable than others, though. That being said, @reduz said it's not a bug, it's by design. So the question is, has he added any options to how looping / interpolation happens?

**Comment by vnen** [comment]
I think I noticed some weird behavior on animations though I attributed it to myself as a no-artist that I am. From what I can tell, it seems that the keyframe at the end of the animations seems to be ignored (does it make any difference?). The interpolation should happen, as it's a nice feature, but it's not natural in the way it's working last time I checked.

**Comment by Dillybob92** [comment]
> it does not interpolate back unless it is set to looping
you mean looping without interpolating back? i guess it could be made
optional

@reduz See my bug report here as well #4681

I sincerely ask you, please give us an option to disable the resetting back to frame 0 on loop. Take this spritesheet we have for our game:

![image](https://cloud.githubusercontent.com/assets/10387670/15312040/8f6b7c5c-1bb5-11e6-8a0f-724d8c066f11.png)

When looping is enabled on continuous, as you can see via my screen screenshot on my issue (second one), it gets reset back to zero **right before** it's done animating. This makes it so the loop is not looped correctly, it's basically creating an illusion of a second frame that lasts for milliseconds (that is detectable by the human eye, and makes the loop not fluid). 

I have hundreds of sprites that are like this and will use the continuation method. I have fell in love with Godot now, and to see that this bug was reported almost 2 years now and not fixed worries me. I ask you, please accept a PR that implements an option to disable this, thank you.

--Nick

**Comment by adolson** [comment]
If there were a PR to merge, I'm sure it would be in by now. My PR, which I closed, fixed the problem completely. But in doing so, it removed this faulty behavior, which Juan wants to keep for some reason. So I closed it.

**Comment by slapin** [comment]
Any links to the discussion for reference?

**Comment by adolson** [comment]
Scroll up?

**Comment by punto-** [comment]
Can you try this branch? https://github.com/punto-/godot/tree/floor (the
only change should be 1 line in variant_op.cpp, but I don't know how up to
date it is with master).

The idea is that the current time offset on a looping animation should be
"time modulo length", so a keyframe at the very end of the timeline and a
keyframe at the very beginning are essentially at the same time, which is
0. If your last keyframe is in the middle of the animation, it will
interpolate with the next one, which is the first one if the animation
loops, but that shouldn't be an issue, you can just duplicate that keyframe
at the end if you don't want it to interpolate looping. So if there's a
bug, it would be interpolating those 2 keyframes that are at the same point
in time.

This patch removes the rounding in int interpolation, which will cause the
1st and last frame of your sprite to be shorter than the rest, maybe that's
the issue here?

**Comment by punto-** [comment]
BTW with this patch, your last keyframe has to be the number of frames in
the sprite, so if there's 20 frames, the last keyframe should be 20, which
is an invalid frame, but the idea is that the last frame will stay at 19
(because it's not rounding anymore), and when it gets to the end it loops
back to 0.

**Comment by Cybolic** [comment]
Seeing as the problem with merging adolson's fix seems to be that the current behaviour is also wanted, I adapted the code into a toggle button, so everyone can be happy :)

**Comment by akien-mga** [comment]
Reopening as the fix was actually reverted. This should be fixed once and for all for 3.0, we can now break compatibility all we want.

**Comment by reduz** [comment]
This was fixed already for the never released 2.2, as you can now select the loop mode per track:
![image](https://user-images.githubusercontent.com/6265307/28976311-c0eaa430-7913-11e7-8dbd-969d3e69015c.png)
closing..

**Comment by Dillybob1992** [comment]
Not entirely sure what's going on, but I think a PR might have changed the sprite's animation that is in continous mode. See here: https://www.facebook.com/groups/godotengine/permalink/1187554944714431/

I remember this problem being fixed, so I searched github and thought it could have been #12898, however am not really sure now.

In any event, when looping is enabled, and if the animation track is set to continous mode, it still skips the last frame.

See [this](https://i.gyazo.com/c740d75c448bd2b7893fbe3600c873e0.png), it's set at frame index 3 (which is frame 4).

Then, when you play it:
![](https://i.gyazo.com/623763904d985888e0ee09ee25994c84.gif) Changing to wrapped or clamp mode has no effect.

**Comment by lverona** [comment]
In the Facebook post, referenced by Dillybob1992 we talk of two workarounds:
1. Add a useless frame and keyframe to this last useless frame. Then looping will be correct.
2. Add more length to the animation or move the last node to a moment in time before the end of the animation. For instance, if I have 4 frames over a second, the last node should be at 0.75. This will give even time to each frame.

What seems to be happening is this.

1. Our expectation is that when you keyframe frame 0 and then frame 3, Godot should understand this as the length of the animation being evenly divided between the four frames.

2. In reality, Godot _keyframes a switch to a frame_. Which means that when we keyframe the last frame by the end of the length of the animation, it does exactly that - switches to last frame at the last milisecond. In looped mode it probably means that the switch just never shows up.

Before fixing this situation, I would seriously think about what Godot does and how is the current behavior used in other animation cases. Maybe, our expectations are actually not reasonable. Or maybe this is indeed a special case that needs to be handled automatically.

**Comment by vnen** [comment]
Note that problem is with *integers*. If you are animating a floating point value, doesn't really matter if it got to 1.0 or to 0.999. But with integers it matters if it got to 10 or to 9. The "evenly divided" works great for integers, but I'm not sure if it'll look good for floating point values.

**Comment by RandomShaper** [comment]
I think workaround 2 in @Iverona's comment is the right thing to do.
It seems some users find confusing how integral values are animated along continuous time, but once you get it it makes full sense.
Maybe a quick tip about this could be added to the docs.

**Comment by lverona** [comment]
And am I correct in understanding that if I need several separate animations, then I actually need a single sprite sheet that I have to animate, which has columns and rows? I.e., it is not possible to add several textures to one sprite?

**Comment by RandomShaper** [comment]
As far as I know you can switch between spritesheets by setting keys for the texture property.

If after auto-atlasing on export they end up in the same image resource, the penalty at runtime should be negiglible.
