### ISSUE TITLE
Button icon's are getting clipped

### ISSUE THREAD

**Issue by Morfeuszz** [godotengine/godot#95911]
### Tested versions

- Reproducible in: v4.3.beta3.mono.official [82cedc83c], v4.3.stable.mono.official [77dcf97d8]
- Not reproducible in: v4.3.beta2.mono.official [b75f0485b]

### System information

Godot v4.3.beta3.mono - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1080 (NVIDIA; 31.0.15.5244) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

Since beta3 icons with custom margins (negative values in this case) started getting clipped, not sure if this was intended change as i couldn't find anything in changelog.

I can achieve same effect by setting content margins on the button itself (which probably is better solution anyway), but just reporting in case if it really is regression

(Beta2)
![image](https://github.com/user-attachments/assets/c7b1c0f7-2c3f-4ddf-802c-675a67ca437a)

(Beta3)
![image](https://github.com/user-attachments/assets/52025c91-7a50-471f-9558-374a2e127203)

### Steps to reproduce

- Create new button
- Assign icon and set it's margins that exceed 'content area' of the button

### Minimal reproduction project (MRP)
- [mrp.zip](https://github.com/user-attachments/files/16697345/mrp.zip)

**Comment by kleonc** [comment]
> ### Steps to reproduce
>   * Create new button
>   * Assign icon and set it's margins that exceed 'content area' of the button

That's not a detailed description. I'm _guessing_ that you're meaning assigning an `AtlasTexture` as `Button`'s `icon` and modifying `AtlasTexture.margin`?

If yes, that must be a regression from #93828. But without knowing full details of your setup I can be only guessing whether it's your setup which is incorrect, or whether I've broken some valid use case with that PR. :upside_down_face:

So please provide all the details (values for such margins, texture details, etc.; also note that e.g. saying _"margins"_ isn't clear, there are many different margins across the engine).

But preferably upload an MRP so no clarification will be needed (minimal reproduction project you were asked for in the issue template).

https://github.com/godotengine/godot/blob/5ca419e32c58e671284b3b7f91257179657d9114/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L64-L70

**Comment by Morfeuszz** [comment]
> That's not a detailed description. I'm guessing that you're meaning assigning an AtlasTexture as Button's icon and modifying AtlasTexture.margin?

Ah yeah sorry for confusion, that's what i used. 
I added MRP to the original post

**Comment by kleonc** [comment]
So yes, the change in the behavior is caused by #93828. Not so sure about calling it a regression, as I would say you were kinda abusing an undocumented implementation details.

Conceptually it's hard to expect a texture reporting 14x12 size (which was the case before #93828 too) to be rendering as 14x15.

v4.2.2.stable.official [15073afe3]|v4.3.stable.official [77dcf97d8]
-|-
![Godot_v4 2 2-stable_win64_sHHbXwRTAn](https://github.com/user-attachments/assets/43c24d90-c291-4379-bd88-533755db9691)|![Godot_v4 3-stable_win64_lMyAxBDB6l](https://github.com/user-attachments/assets/7de3ffb6-8e68-4bba-ae02-80fe3da35397)



Knowing AtlasTexture's code I'd say it was never written with negative margins in mind. Code seems to assume positive values without checking for negatives, and how it works for them is kinda a happy coincidence. E.g. you can obtain a texture with a negative size (hence the conclusion that negative margin was simply never considered as a valid value; same for `AtlasTexture.region`).
https://github.com/godotengine/godot/blob/5ca419e32c58e671284b3b7f91257179657d9114/scene/resources/atlas_texture.cpp#L51

v4.2.2.stable.official [15073afe3]|v4.3.stable.official [77dcf97d8]
-|-
![2mXlFCgoD2](https://github.com/user-attachments/assets/7721b142-1671-4f3a-a4ef-1011b032cc9c)|![rfukYjCi7A](https://github.com/user-attachments/assets/e77a0d38-1741-4985-95cf-512fe946db5b)

Originally `AtlasTexure.margin` is meant to determine the transparent margin around the `AtlasTexure.region`, so big sprites with big transparent borders could be packed together more efficiently, without needlessly storing all the transparent borders' pixels. And also so only the middle non-fully-transparent part (`region`) would be used for rendering the given conceptually bigger texture. E.g.:
![TYz7Dk37qi](https://github.com/user-attachments/assets/96e283b5-18a0-4c01-a24b-15612481c340)


So, it working like that in a Button was, again, kinda a happy coincidence. E.g. if Button would be calling `Texture2D::draw_rect_region` instead of `Texture2D::draw_rect` on the exact same AtlasTexture then it wouldn't work the same way even before #93828 (which made them work consistenly in that manner).

If you're saying you can achieve the same effect with content margins (from some StyleBoxes I guess :upside_down_face:), then the change is probably not an issue.

Have to say though, I'm happy to finally see someone utilizing negative margins in AtlasTexture. Whenever looking at its code / changing something in there, I was wondering whether the negative margins should be straight up disallowed or said to be invalid in the docs etc. Hesitated about doing so, I guess there was a reason...

But while I do see how negative margins could be utilized for some workarounds, I don't think allowing a texture to render bigger than its reported size makes sense design-wise. This seems like an inconsistency which asks for bugs/problems somewhere further along the way.

**Comment by Morfeuszz** [comment]
Thanks for thorough investigation!

I knew its a bit hacky solution, but hey it worked as i wanted so i just left it as is without looking for another solution.
I already fixed everything using `StyleBox.ContentMargin` so its absolutely not an issue to me.

Disallowing use cases like that would for sure be beneficial (if possible), like in this example everything worked fine until something else got patched up. Causing a bit of extra work and confusion to fix it and investigate.
Though i imagine it's not as simple because just straight up blocking it might block some other creative use cases.

Anyway, thank you again for your time and help
