### ISSUE TITLE
Multiple Animation Trees cause only the latest one created to work - Godot 4.3

### ISSUE THREAD

**Issue by adrianznur** [godotengine/godot#95968]
### Tested versions

-Reproducible in 4.3
-Not reproducible in any earlier versions

### System information

MACOS Sonoma 14 - Godot 4.3 - Vulkan 1.2.283 - Forward+

### Issue description

Having multiple animationtrees that are dependent on either the same animationplayer (Or have the same root node) causes only one to work if both of them are set to active.

**NOTE: Not entirely sure if the issue stems from both trees being dependent on the same player, as I haven't tested having them on 2 different animationplayers. But the issue always happens as long as both of them are active.**

Before 4.3, you could have multiple animationtrees with the same animationplayer and have them both be active and play multiple animations at the same time, I assume this was intended as it made animating multiple parts of a character much easier.

The animations have worked fine in 4.2 and earlier in my experience, although I was not able to test this in a backup copy of 4.2.2 after after converting my project to 4.3, because attempting to revert it to 4.2.2 caused a lot of main files to become corrupt with the "Error while parsing" issue. The project now only works in 4.3 after being converted.

### Steps to reproduce

-A possible scenario for this is having a Characterbody2d, and then adding 2 sprites to it (For example, an upper body sprite and a lower body sprite). Set them up as a sprite sheet. 

-Then, add an animationplayer that has animations for both sprites.

-After that, add 2 separate animation trees, one for each sprite's animations. Set them both as state machines, and have their animationplayer as the same one.

-Set them both to active, and in script, use get("parameters/playback") and .travel("") to traverse the animation trees via conditions.

-You will most likely be able to see that the tree you set up latest only plays its animations, while the other one doesn't.

### Minimal reproduction project (MRP)

N/A

**Comment by adrianznur** [comment]
Coming back now to add: I just tested by putting 2 animationplayers (1 for each sprite) and separating the animations, animation player tracks, and animation trees, and all works fine. The source of the problem was that both animation trees were dependent on the same animationplayer.

Still, this is an inconvenience from 4.2.2 which allowed multiple trees to be attached to the same player. Maybe it'd be worth looking into, since at least for me, letting multiple trees be rooted to one player saves a lot of hassle and memory as compared to having to make a separate player for every little sprite and doubling the amount of nodes for animations.

**Comment by TokageItLab** [comment]
You must send MRP as it is not clear what you mean.

BTW, if you mean a case where two separate AnimationTrees play different animations based on the same animation player, but with different trackpaths for each, I think if you disable the Deterministic option and set the AnimationTree's CallbackModeDiscrete to Dominant or Recessive, the two AnimationTrees would work.

![image](https://github.com/user-attachments/assets/44ed4796-bcb7-4e05-809a-8c3b3fe3ad8c)

![image](https://github.com/user-attachments/assets/8fbbd620-547f-47ab-b9ee-128bd04fed77)

See also https://godotengine.org/article/migrating-animations-from-godot-4-0-to-4-3/#callbackmodediscrete.

If you mean any other case, we cannot tell without MRP. In any case, if multiple AnimationMixers animate the same property on the same object, there should be no bug there just see the issue title, since it is the intended behavior that only the last AnimationMixer is processed.
