### ISSUE TITLE
TLS handshake error: -27648 when accessing the AssetLib (using system mbedTLS 3.6.0 on Arch Linux)

### ISSUE THREAD

**Issue by MegaDutcher** [godotengine/godot#96103]
### Tested versions

v4.3.stable.arch_linux

### System information

Godot v4.3.stable unknown - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Mon Jun 10 09:44:22 UTC 2024 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (RADV NAVI31) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)

### Issue description

When clicking AssetLib I get "Failed to get repository configuration." with a retry button underneath.
In the Output i get "modules/mbedtls/stream_peer_mbedtls.cpp:89 - TLS handshake error: -27648", this just gets printed again if I click the retry button.

### Steps to reproduce

Launch Godot -> click AssetLib.

### Minimal reproduction project (MRP)

n/a

**Comment by MegaDutcher** [comment]
It seems [IGN-Styly](https://github.com/IGN-Styly) is having the same issue here...https://github.com/godotengine/godot/issues/85953
Where he was told to make a new issue, there seemingly isn't one for this...so I made a new one.

**Comment by zarno** [comment]
Also running v4.3.stable.arch_linux. 
![Screenshot_20240830_211008](https://github.com/user-attachments/assets/b479797d-5038-4e6a-bda3-2c0b5cf677d5)
Log produced error from --verbose at

```
EditorSettings: Save OK!
/usr/src/debug/mbedtls/mbedtls/library/ssl_tls13_generic.c:1651: 0x55673d470e18: Perform PSA-based ECDH/FFDH computation.
/usr/src/debug/mbedtls/mbedtls/library/ssl_tls13_generic.c:1689: 0x55673d470e18: psa_generate_key() returned -27648 (-0x6c00)
ERROR: TLS handshake error: -27648
   at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:89)
mbedtls error: returned -0x6c00

```

**Comment by zarno** [comment]
Also noting can ping IPV4/6 FWIW 
```
    ~/.ssh  ping -4 godotengine.org                                                                                                                                                           ✔  14m 53s  

PING godotengine.org (104.21.36.120) 56(84) bytes of data.
64 bytes from 104.21.36.120: icmp_seq=1 ttl=56 time=18.5 ms
64 bytes from 104.21.36.120: icmp_seq=2 ttl=56 time=22.1 ms
64 bytes from 104.21.36.120: icmp_seq=3 ttl=56 time=20.5 ms
64 bytes from 104.21.36.120: icmp_seq=4 ttl=56 time=20.8 ms
^C
--- godotengine.org ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 18.536/20.506/22.142/1.291 ms
    ~/.ssh  ping -6 godotengine.org                                                                                                                                                                ✔  3s  

PING godotengine.org (2606:4700:3036::ac43:c1fd) 56 data bytes
64 bytes from 2606:4700:3036::ac43:c1fd: icmp_seq=1 ttl=56 time=20.8 ms
64 bytes from 2606:4700:3036::ac43:c1fd: icmp_seq=2 ttl=56 time=23.8 ms
64 bytes from 2606:4700:3036::ac43:c1fd: icmp_seq=3 ttl=56 time=23.6 ms
64 bytes from 2606:4700:3036::ac43:c1fd: icmp_seq=4 ttl=56 time=21.4 ms
^C
--- godotengine.org ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3007ms
rtt min/avg/max/mdev = 20.798/22.375/23.793/1.318 ms
```

**Comment by Okxa** [comment]
Export template mirror list also fails to load (with the same error):

![image](https://github.com/user-attachments/assets/10b3b52e-9d73-4ae9-a17d-770108103711)

```
/usr/src/debug/mbedtls/mbedtls/library/ssl_tls13_generic.c:1651: 0x624c25c7ee18: Perform PSA-based ECDH/FFDH computation.
/usr/src/debug/mbedtls/mbedtls/library/ssl_tls13_generic.c:1689: 0x624c25c7ee18: psa_generate_key() returned -27648 (-0x6c00)
ERROR: TLS handshake error: -27648
   at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:89)
mbedtls error: returned -0x6c00
```

System info:
`Godot v4.3.stable unknown - Arch Linux #1 SMP PREEMPT_DYNAMIC Thu, 15 Aug 2024 00:25:30 +0000 - X11 - Vulkan (Forward+) - dedicated AMD Radeon RX 5700 XT (RADV NAVI10) - AMD Ryzen 9 5950X 16-Core Processor (32 Threads)`

**Comment by MegaDutcher** [comment]
With version 4.3.3 (extra repo) the issue seems to be resolved...

**Comment by akien-mga** [comment]
The issue was worked around in Arch Linux by using the builtin version of mbedtls provided by Godot, but the bug itself is not fixed. Needs more investigation to see if it's a reproducible when building Godot against system provided mbedtls, or what configuration Arch Linux uses for their package that makes it incompatible with Godot.

**Comment by akien-mga** [comment]
Tested on Fedora 40 with the system provided mbedtls 2.28.8 and it seems to work fine.
I then compiled the (currently only being tested in rawhide) 3.6.1 version, and it still works fine.

So I finally tested building 3.6.0, and this one does exhibit the issue. So it's an upstream mbedtls bug which has been fixed already. Arch Linux should be able to fix the issue by updating their mbedtls package from 3.6.0 to 3.6.1 (which also fixes security issues so it's something they ought to do sooner than later anyway).

I don't have an Arch Linux SSO account, but if one of you does, it would be good to mention that on https://gitlab.archlinux.org/archlinux/packaging/packages/godot/-/issues/3 so that the godot and mbedtls maintainers there are aware.

**Comment by Nikitf777** [comment]
I have this issue again on Arch Linux with Godot 4.4.1 stable, as well as a person in the comments on Arch Linux GitLab:
https://gitlab.archlinux.org/archlinux/packaging/packages/godot/-/issues/3#note_280934.

mbedtls version is 3.6.4.

**Comment by ArekKubinski** [comment]
Godot Engine v4.4.1.stable.arch_linux - https://godotengine.org
glx: failed to create dri3 screen
failed to load driver: nouveau
OpenGL API 4.6 (Core Profile) Mesa 25.0.5-arch1.1 - Compatibility - Using Device: Intel - Mesa Intel(R) UHD Graphics 620 (WHL GT2)

ERROR: TLS handshake error: -27648
   at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:88)
mbedtls error: returned -0x6c00

ERROR: TLS handshake error: -27648
   at: _do_handshake (modules/mbedtls/stream_peer_mbedtls.cpp:88)
mbedtls error: returned -0x6c00

The issue is still present (please ignore my problems with graphic drivers ;w;)

**Comment by rxn7** [comment]
still present.
