### ISSUE TITLE
Animation editor breaks if snapping is set to more than 1 second

### ISSUE THREAD

**Issue by UnfavorableEnhancer** [godotengine/godot#96159]
### Tested versions

- Reproducible in: 4.3.stable, 4.4.dev1
- Not reproducible in: 4.2.1.stable, 4.2.2.stable

### System information

Windows 11 - Godot v4.3.stable - Vulcan (Forward+)

### Issue description

When snap value is set to more than 1 second animation editor just breaks.
- If snap value is higher than 1 second and equal or less than 2 seconds, then animation keys continue to snap to 1 second, ignoring that value is actually higher
- If snap value is higher than 2 seconds, then animation editor just refuses to create new keys when you try to make them by right clicking on animation track and selecting "Insert key..." option. 
- And you're no longer able to move any animation keys if snapping is set to more than 2 seconds.

### Steps to reproduce

- 1.) Create AnimationPlayer node and some Sprite or ColorRect node inside scene
- 2.) Add new animation and make some simple animation with created Sprite/ColorRect
- 3.) Set snap value to higher than 2 seconds
- 4.) Try to move existing animation keys or create new key via "Insert key..." right-click option

### Minimal reproduction project (MRP)

[animation_test.zip](https://github.com/user-attachments/files/16760572/animation_test.zip)

**Comment by object71** [comment]
I found an issue with the `_update_snap_unit` function which tries to round the fraction part of a number to a nice value like 0.033 to 0.0333333333333(3). But this code causes an error with values that are above 2 since the calculation creates a +Inf step value. I will correct it and create a pull request soon.

**Comment by TokageItLab** [comment]
As additional information, I remember originally implementing this due to a problem with not being able to snap to 1.0 s at 1s in https://github.com/godotengine/godot/pull/92670. So it may be necessary to separate the decimal and integer parts of the process to prevent the accumulation of fractional errors.

**Comment by object71** [comment]
I checked and this is the only place I could find it as a calculation. I got the point and already implmeented the fix by introducing a modf function that splits the fraction and integer and then preserves the accumulation logic with the rounding but only on the fraction.
