### ISSUE TITLE
Godot's GLB Importer in MacOSX adds "_2" suffix randomly to bone names, it doesn't in Windows

### ISSUE THREAD

**Issue by brantkings** [godotengine/godot#96248]
### Tested versions

Did it in 4.3 in MacOSX

### System information

MacOSX - Godot 4.3

### Issue description

Needed to open my project in MacOSX so I can export my project for iOS. Turns out many instances of my code's Skeleton3D.find_bone() didn't work, because, in MacOSX, the importer randomly added the "_2" in some bones while Windows didn't.

Keep in mind that this happened throughout a lot of crashes while I was importing the whole project.

### Steps to reproduce

Open a project with .glb with Skeletons and bones files in Windows, then try to open it in MacOSX.

### Minimal reproduction project (MRP)

Here's is my project with two .glb files that were culprits of this. I think they both do the "_2" for different reasons.
[glbimporterexample.zip](https://github.com/user-attachments/files/16789120/glbimporterexample.zip)

I got the inherited scene of the .glb from the project that crashed a bunch of times while importing.

**Comment by aaronfranke** [comment]
Can't reproduce on macOS 14.6.1 arm64 with Godot 4.3 stable.

The "brawny" scene does not have any "_2" suffix on any bone or node.

<img width="540" alt="Screenshot 2024-08-28 at 9 37 49 PM" src="https://github.com/user-attachments/assets/de0f03ec-1b6d-4647-910e-11212ee4bf07">

The "robotocopter" scene has a "_2" bone, but this is expected because otherwise the name would be the same as a node (which is not allowed), and the same thing also happens on Windows 11 arm64.

<img width="540" alt="Screenshot 2024-08-28 at 11 27 03 PM" src="https://github.com/user-attachments/assets/b67c2007-87d6-4a0a-a152-1beb629600b0">

**Comment by brantkings** [comment]
oh sorry! On Brawny's main skeleton it really does not happen, but it happens on one of the skeletons of the arms (which are named in the same way in Blender, which is confusing)

**Comment by aaronfranke** [comment]
@brantkings Try reimporting using the button in the "Import" dock.

**Comment by brantkings** [comment]
@aaronfranke yeah, the Windows version also added the "_2" on the third Brawny's skeleton... but isn't that still kinda weird? Are the bones internally under the same parent?

**Comment by aaronfranke** [comment]
@brantkings The glTF importer ensures that names are unique in the scene, regardless of being under the same parent.
