### ISSUE TITLE
Compatibility renderer 3D MSAA not working on MacOS

### ISSUE THREAD

**Issue by jrrmt** [godotengine/godot#96275]
### Tested versions

- Reproduced in 4.3-stable

### System information

Godot v4.3.stable - macOS 14.6.1 - GLES3 (Compatibility) - Apple M1 - Apple M1 (8 Threads)

### Issue description

When setting 3D MSAA on a project, there is no effect and I get the following error on the Debugger:

```
W 0:00:01:0419   configure: MSAA is not supported on this device.
  <C++ Source>   drivers/gles3/storage/render_scene_buffers_gles3.cpp:181 @ configure()
```

I narrowed it down to the `GL_EXT_framebuffer_multisample` flag not being available in the system OpenGL.

I should add that it does work if I use the web export, which checks for  the `GL_MAX_SAMPLES` property. I am not sure if something similar would be possible on native MacOS.

### Steps to reproduce

- Open a project with 3D MSAA enabled on MacOS with the Compatibility renderer.
- Run and/or check Debugger output and verify MSAA is not working.

### Minimal reproduction project (MRP)

[msaa-mac.zip](https://github.com/user-attachments/files/16797608/msaa-mac.zip)

**Comment by clayjohn** [comment]
This seems to be a problem with how we detect support for MSAA. On desktop and mobile we check for `GL_EXT_framebuffer_multisample` which is an OpenGL 1 extension that was later incorporated into core OpenGL 3. 

I suspect that this was an error from basing our code off of the GLES2 code in Godot 3.x, which does need to check for extension support. Notably, however, it explicitly looks for `GL_APPLE_framebuffer_multisample` which is the Apple version of `GL_EXT_framebuffer_multisample`.

https://github.com/godotengine/godot/blob/01c78d87fea331c978d7ba8a2d5edb379564bdde/drivers/gles2/rasterizer_storage_gles2.cpp#L6390

This issue can be fixed by setting `msaa_supported` to `true` on all non-web platforms instead of checking for the extension:
https://github.com/godotengine/godot/blob/61598c5c88d95b96811d386cb20d714c35f4c6d7/drivers/gles3/storage/config.cpp#L124
