### ISSUE TITLE
Inspector scrolls away from focused item automatically

### ISSUE THREAD

**Issue by rick551a** [godotengine/godot#96489]
### Tested versions

4.3 stable mono

### System information

Win10, Nvidia

### Issue description

When clicking a checkbox the inspector scrolls up, away from the clicked item

https://github.com/user-attachments/assets/7d15a09e-57a9-470d-aab1-d54d4c6a18a6

See video clip for example,
Whenever I click 'Fog' inside the WorldEnvironment, the inspector scrolls back up to the top each time i click it.
Very annoying, as I have to scroll back down to 'Fog' again to press it again

This did not happen in 3.5, the focus remained on item (just tested  it)

### Steps to reproduce

Create a WorldEnvironment -> New Environment
Expand a few options ,so the inspector height is long.
Click an option near the end (like 'Fog') and watch the inspector scroll back up when you click it

### Minimal reproduction project (MRP)

None

**Comment by aXu-AP** [comment]
To be more accurate, this happens when:
* Toggled property opens up new options, making the inspector longer/shorter
* The inspector is currently scrolled further down past a certain point
My guess is that while the inspector is reloading, it is temporarily shorter and the scrollbar adjusts to the new size limiting the max value.

**Comment by matheusmdx** [comment]
Bisecting points to #78960 as the culprit, @kleonc

![image](https://github.com/user-attachments/assets/4e9957cd-9b7b-4b6e-836f-f9f2fd7d6c98)

<br>

We already had a similar issue caused by this pr but with `OptionButton` instead, #91287
