### ISSUE TITLE
AnimationPlayer continuously set values of properties defined in Property Track

### ISSUE THREAD

**Issue by stesproject** [godotengine/godot#96531]
### Tested versions

- Reproducible in: 4.3.stable, 4.4.dev

### System information

Windows 11

### Issue description

Setting the value of an exported property in an animation, continuously set the property value in an infinite loop, even if the animation is not the currently playing animation and even if the AnimationTree is totally empty (with a brand new Tree Root). It's enough to just have one single animation in your animation library that sets the property at least once.
The same thing does not happen if I set the same property using a "Call Method Track" for calling a method that sets the property, so it seems that the issue is with the "Property Track".
The behaviour is visible defining a setter in the variable and printing something to the console.

### Steps to reproduce

- Create a new Node (I tested with a Node2D)
- Add a script to the node
- In the script, export a variable (eg: `@export var test = false`)
- Define a setter to the variable and call the "print('whatever you want')" method in the setter (it will be useful to validate this issue)
- Add an AnimationPlayer
- Add an AnimationTree and set these properties:
- anim_player: select the previously created AnimationPlayer
- tree_root: create a New AnimationNodeStateMachine. You can keep the state machine empty (do not add any of the animations we are going to create)
- Select the AnimationPlayer and add 2 animations (eg: "idle" and "walk")
- Set "idle" as the default animation
- Add a Property Track to the "walk" animation that sets at least once the variable declared in our previously created script
- Run the project
- Notice how the console is spammed with whatever we wrote in the print method

### Minimal reproduction project (MRP)

[animation-spam.zip](https://github.com/user-attachments/files/16850394/animation-spam.zip)

**Comment by TokageItLab** [comment]
See https://godotengine.org/article/migrating-animations-from-godot-4-0-to-4-3/#callbackmodediscrete

**Comment by aaaddd4747** [comment]
~~I would like to request this issue be re-opened and labeled as a bug. I encountered this bug in a new Godot 4.6 project. This time with 3D animations. Setting any property on any node prevents any script from being able to update that value as it is constantly overwritten by whatever the animation wants to do regardless of if it is playing and regardless of update mode as TokageItLab suggested. This is bizarre and counterintuitive behavior.~~

~~The animation continuously setting the value while the animation is playing is an obvious and expected behavior of course; but when the animation is **_not_** playing, why is it modifying the values? Why is it doing anything at all?~~

I tried to use the workaround the OP mentioned, but in my case I do indeed want continuous interpolation, and you cannot interpolate a function call.

For now I have created my own workaround where I export the value I wish to modify from a script, animate that exported value value, and apply that value depending on if the animation is active from the script. ~~This method is clunky, dumb, and tedious, but it does at least bandage the issue until a real fix can be made.~~

On further investigation, to my own surprise, this is not a bug but a consequence of blending animations in an AnimationNodeBlendTree, where even at 0 it must apply an effect, even if that value is not set by the other animation. I am leaving the rest of the comment stricken out for context, and posting my workaround here to aid anyone who was as confused as I was and hopefully save them a few hours of their time.
