### ISSUE TITLE
Label uses mouse filter "ignore" by default, other Controls use "stop"

### ISSUE THREAD

**Issue by akien-mga** [godotengine/godot#9657]
**Operating system or device - Godot version:**
Mageia 6 x86_64, master 2e73be9

**Issue description:**
Some signals of Control nodes seem not to be emitted as they should, namely (tested so far, might be more broken):
- Control.gui_input
- Control.mouse_entered
- Control.mouse_exited

**Steps to reproduce:**
See attached demo.

**Link to minimal example project:**
[test_signals.zip](https://github.com/godotengine/godot/files/1150392/test_signals.zip)

**Comment by kubecz3k** [comment]
Downloaded project, it seems problem is somewhere else, after changing Mouse->filter to `stop` or `pass` from `ignore` signals are emitted:
![control_filter_change](https://user-images.githubusercontent.com/6129594/28279761-d539f99a-6b21-11e7-9932-5db097271e6c.gif)
It seems the problem is that `Control.filter` is not converted correctly.

**Comment by groud** [comment]
Isn't that related to #7622 ?

**Comment by akien-mga** [comment]
At least for Label it seems to be on purpose: https://github.com/godotengine/godot/blob/db3b05d/scene/gui/label.cpp#L681
So it would more be a documentation issue than a bug.

**Comment by akien-mga** [comment]
CC @godotengine/documentation, someone should document the mouse-related stuff in `Control.xml` to make this clearer.
