### ISSUE TITLE
Tooltip sometimes appears at old mouse position

### ISSUE THREAD

**Issue by KoBeWi** [godotengine/godot#96707]
### Tested versions

4.4 dev 5675c76
Not reproducible in 4.3

### System information

Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1060 (NVIDIA; 31.0.15.4633) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

### Issue description

If you move cursor before hovering over something with tooltip, the tooltip can appear at older mouse position.

https://github.com/user-attachments/assets/27982e1e-b547-422b-a14b-cae7c34d26c1

### Steps to reproduce

1. Hover scene tree node while moving your cursor fast

### Minimal reproduction project (MRP)

N/A

**Comment by Giganzo** [comment]
Looks like this happens after https://github.com/godotengine/godot/pull/95846 ?

**Comment by aXu-AP** [comment]
It seems to me that this bit has a little logic problem:
https://github.com/godotengine/godot/blob/5675c76461e197d3929a1142cfb84ab1a76ac9dd/scene/main/viewport.cpp#L1936-L1941
The intent is that if the mouse has moved 5 pixels reset the tooltip timer. However, `mm->get_relative()` gets the relative motion to the last inputevent, not in relation to where the timer was started. So it means like 5 pixels per frame (or however often inputevent are triggered).
So the actual bug is a bit more severe, tooltip appears even if the mouse is in steady motion.
![tooltip](https://github.com/user-attachments/assets/166e2ce2-6062-4f89-a3ab-1e3d87c56dd2)

I think solution to this would be either use the initial version of #95846 (check that relative motion != zero), or if we really want that 5 px leeway, save the starting position. But I think zero movement is good enough, the situation is different from doubleclicking, since to show tooltip you can just not touch the mouse (vs accessibility problem of doubleclicking without moving mouse).
