### ISSUE TITLE
Specific light shader works in Godot 3 but not Godot 4

### ISSUE THREAD

**Issue by FireCatMagic** [godotengine/godot#96704]
### Tested versions

3.5.3-stable
4.4-dev1

### System information

Godot v4.4.dev unknown - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4050 Laptop GPU (NVIDIA; 32.0.15.6070) - 13th Gen Intel(R) Core(TM) i5-13500HX (20 Threads)

### Issue description

The shader I am using for this is an edited version of the project here: https://github.com/paddy-exe/Godot-RealTimeCaustics

I stripped away some of its features to leave just the light projection, and as you see here it works perfectly in Godot 3
![Godot_v3 5 3-stable_win64_ZCE1jm3VR1](https://github.com/user-attachments/assets/3d460f13-2649-4e19-8c45-cfde80c28dfb)

But then issues arise when trying to use this shader in Godot 4.
I did the following steps to convert it:
`depth_test_disable`->`depth_test_disabled`
Added 
`uniform sampler2D DEPTH_TEXTURE: hint_depth_texture, filter_linear_mipmap;`
and
`uniform sampler2D SCREEN_TEXTURE: hint_screen_texture, filter_linear_mipmap;`
Then the project converter seemed to converte the rest for me, such as the matrix builtin names
Despite that, the shader doesn't work.

![godot windows editor x86_64_18cTSokgSM](https://github.com/user-attachments/assets/d4586832-f8f5-4ee8-afb3-87014e710ecb)

Then this shader doesn't do anything at all when used in godot 4, despite being converted properly.

The expected behavior is that the shader would work the same as it does in Godot 3 due to the shader being the same

### Steps to reproduce

1. Test the projects above
2. Notice the same shader works in Godot 3 but not Godot 4

### Minimal reproduction project (MRP)

[3.0.zip](https://github.com/user-attachments/files/16921122/3.0.zip)

[4.0.zip](https://github.com/user-attachments/files/16921119/4.0.zip)

**Comment by tetrapod00** [comment]
Shaders are not expected to convert cleanly between version 3 and version 4. Especially this shader, which makes several assumptions about godot coordinate spaces and uses a lot of manual matrix math.

I helped another user convert this shader from 3 to 4 a while back. The steps were not trivial IIRC. I can try to find the converted shader and post it to github, tomorrow or the next day.

**Comment by tetrapod00** [comment]
Also, sorry for the ping, but @paddy-exe maybe you have a converted version already? If not, I've done most the work already and can try to clean it up as a PR to https://github.com/paddy-exe/Godot-RealTimeCaustics.

**Comment by paddy-exe** [comment]
> Also, sorry for the ping, but @paddy-exe maybe you have a converted Godot 4.x version already? If not, I've done much of the work already and can try to clean it up as a PR to https://github.com/paddy-exe/Godot-RealTimeCaustics.

I haven't worked on this project for a while now and have no 4.x version myself. If you do, I would appreciate a PR👍🏻

**Comment by FireCatMagic** [comment]
> I don't think shaders are expected to always convert cleanly between version 3 and version 4. Especially this shader, which IIRC makes several assumptions about godot coordinate spaces and uses a lot of manual matrix math. You can find some information about converting shaders [here](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html#updating-shaders), but don't expect it to do all the work for you for this shader.
> 
> I helped another user convert this shader from 3 to 4 a while back. The steps were not trivial IIRC. I can try to find the converted shader and post it to github, tomorrow or the next day.
> 
> Edit: here's the version that I converted that seems to work, but I didn't fully understand the changes even at the time. And I might have changed some of the scene setup in addition to the code. I'll take another look at this in the next few days.
> 
> [caustics_42.txt](https://github.com/user-attachments/files/16921244/caustics_42.txt)
> 
> From skimming the shader again, I think one thing that changed between 3.x (which uses opengl) and 4.x Forward+ (which uses vulkan) is that NDC space changed from opengl NDC `(-1,-1,-1) to (1,1,1)` to vulkan NDC `(-1,-1,0) to (1,1,1)`. This shader might also be affected by the [reverse-z changes](https://godotengine.org/article/introducing-reverse-z/) that happened between version 4.2 and 4.3, so the shader I posted might not work in 4.3.

That fixed it - but only in the vulkan renderers. I am still using 4.4-dev1
![godot windows editor x86_64_hbbAG2y9cU](https://github.com/user-attachments/assets/4f4b5bd4-e749-4eb7-8497-c2553565d56e)

When used in Compatibility, it behaves like this:
![godot windows editor x86_64_l2KMCY6nok](https://github.com/user-attachments/assets/97ace69f-edde-4934-9d19-98835a446955)


I'm not knowledgeable enough in shaders to know if any of this is a bug or if I'm just stupid. This issue got marked "regression" and "bug", so idk

**Comment by tetrapod00** [comment]
In the shader I uploaded, there's a line:
`vec3 ndc = vec3(SCREEN_UV * 2.0 - 1.0, depth); // CHANGED - the original shader had: vec3(SCREEN_UV, depth) * 2.0 - 1.0`
I think you can change that back to:
`vec3 ndc = vec3(SCREEN_UV, depth) * 2.0 - 1.0;`

The original 3.x shader assumes opengl normalized device coordinates (NDC), and reconstructs the NDC from screen_uv and depth. Since the range of depth changes from [-1,-1] in opengl to [0,1] in vulkan, we need to change which of SCREEN_UV and depth are remapped from [-1,-1] to [0,1].

Anyway, Compatibility in 4.x still uses opengl NDC, so the 3.x form of that line should still work.

There's a shader built-in variable `OUTPUT_IS_SRGB` that should be a proxy for opengl/vulkan, which you should be able to use to check which renderer you're using from within the shader. But the name of the variable does not actually support that use case, so it may break in the future.

**Comment by tetrapod00** [comment]
As for resolution of this issue as far as Godot is concerned, I don't know if we can automatically change shaders that use NDC space or any code that does manual clip space calculations? 

Potential docs changes:
- We could add some mention of the change in NDC to [Upgrading to Godot 4 / Updating Shaders](https://docs.godotengine.org/en/stable/tutorials/migrating/upgrading_to_godot_4.html#updating-shaders). Since NDC does vary even within 4.x, it should probably be documented elsewhere, too. NDC is partially documented on[ Advanced Postprocessing](https://docs.godotengine.org/en/stable/tutorials/shaders/advanced_postprocessing.html) already. I'd also like to add some docs for coordinate spaces and NDC with https://github.com/godotengine/godot-docs/pull/9757.
- We could add a disclaimer to `Upgrading to Godot 4 / Updating Shaders` that more complex shaders will need some manual work. This does feel similar to the reverse-z change within 4.x, in terms of breaking changes that are sufficiently complex we can't support.
- I still have not looked closely at the converted shader again, but IIRC there were also some changes to light() needed that might have been from the default lighting model changing, or default `render_mode`s changing. Those may also merit another comment in the docs.

**Comment by tetrapod00** [comment]
@FireCatMagic I got around to testing out the exact MRP you posted. In the version 4.0 you posted, tested on 4.3 (the downgrade shouldn't matter in this case), only two changes are needed for Forward+:
- Convert the NDC construction as mentioned
- Change `ALBEDO = vec3(0.0);` to `ALBEDO = vec3(1.0);`. The lighting model between 3.x and 4.x, and this is the best way I've found to preserve the additive caustics using the lighting function.

4.3 Forward+:
![Godot_v4 3-stable_win64_UMNj8UNQz6](https://github.com/user-attachments/assets/1b398bf7-1108-40da-a4e0-51f361b41375)

For Compatibility:
- Leave the NDC calculation as it was in 3.x.
- Change `ALBEDO = vec3(0.0);` to `ALBEDO = vec3(1.0);`. 

4.3 Compatibility:
![Godot_v4 3-stable_win64_hh2CBHftM1](https://github.com/user-attachments/assets/fef204d2-1d28-4ebf-8fd6-80a258cd916e)

Compatibility does look different, even with the correct NDC calculation. I may try to fix it as a PR to the original repo later: https://github.com/paddy-exe/Godot-RealTimeCaustics.
