### ISSUE TITLE
"Using present mode: Enabled" spam

### ISSUE THREAD

**Issue by Withaust** [godotengine/godot#96739]
### Tested versions

4.3 stable

### System information

Windows 10 Godot 4.3 stable Vulkan

### Issue description

Currently, every single time when you open another subwindow
stuff like these tabs for example:
![image](https://github.com/user-attachments/assets/8faf2084-b5e1-435c-9c4b-30c297a9ad49)
engine would print `Using present mode: XXX`.
While actively working on the project your entire console could easily be filled with these messages:
![image](https://github.com/user-attachments/assets/a03fb094-901a-4e55-8fca-706511e7ed67)

### Steps to reproduce

^^^

### Minimal reproduction project (MRP)

...

**Comment by AThousandShips** [comment]
Comes from this line:
https://github.com/godotengine/godot/blob/d0dc3896ad6fe039e4ad0607d901c81197cb3a3b/drivers/vulkan/rendering_device_driver_vulkan.cpp#L2850

From:
* https://github.com/godotengine/godot/pull/87340

CC @DarioSamo

**Comment by DarioSamo** [comment]
Verbose is pretty much meant to print information excessively for debugging purposes and this is because every single pop-up creates a swap chain for presentation and therefore prints which presentation mode the swap chain is using. I'm not entirely sure what behavior is preferred here.

**Comment by Withaust** [comment]
This really boils down to the fact that some of the verbose only logging stuff was never supposed to be verbose only (for example, orphan string name printing), and so if you are using something like GDExtension for your game, you are essentially forced into a verbose printing mode if you want to catch some of the issues that the engine has. I see what you mean by this, but you also have to understand the issue that I have at hand as well, and why I am voicing concerns about this spam.

**Comment by Jowan-Spooner** [comment]
I just noticed this and am in support of limiting or removing this message. It happens on any popup opening (including menus, dropdowns, tooltips and right-clicks) in the engine. I feel this is too much. Of course I cannot judge how important this information is but it feels a bit redundant/excessive because I have not yet seen it say something else.

Also the wording is kinda confusing/ambiguous. The first time I noticed it I had absolutely no clue where it came from. The message doesn't really convey that is has something to do with Windows/Popups.
