### ISSUE TITLE
Disabling "emulate mouse from touch" in android editor makes it unusable upon restart

### ISSUE THREAD

**Issue by ohboh** [godotengine/godot#96784]
### Tested versions

Godot 4.3.0 stable [Android]

### System information

Android 13 (Xiaomi Poco F3) - Godot 4.3 stable

### Issue description

After disabling "emulate mouse from touch" in project settings and restarting the editor, it becomes impossible to use the editor with touch.

### Steps to reproduce

1. Disable "emulate mouse from touch" in project settings
2. Exit Godot editor and remove from recents
3. Re-open the editor and open your project

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
CC @m4gr3d 

It's logical that disabling mouse emulation would prevent using it - the solution here is to connect a mouse and re-enable it, if using mouse emulation was needed.

That being said it's a bug that the *project setting* impacts the editor, so this needs to be changed so that the editor has its own control over the use of mouse emulation from touch.

And to get out of this kind of situation, there should probably be an easy way to reset editor settings if users disable it by mistake (or we prevent disabling it altogether).

**Comment by ohboh** [comment]
Also, it's odd that prior to restarting the editor, the setting only applies to the project and does not impact the editor itself (which is how it should be).
