### ISSUE TITLE
Gui theme textures should have a name for Debugger -> Video Memory 

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#9679]
**Operating system or device - Godot version:**
2.1.3

Not sure if this an issue but I'm pretty sure it is. I've seen this for about 2 years now but never really reported because.. I don't know lol

Anyway:
![image](https://user-images.githubusercontent.com/10387670/28292087-6fac49a8-6b02-11e7-90a1-85927823164f.png)

Is this intended, what exactly are the unnamed textures and where are they coming from? :O

**Comment by kubecz3k** [comment]
Could you test on current master branch? Also are you able to provide some kind of minimal example project in which this issue can be observed? Thanks.

**Comment by reduz** [comment]
This is ok, it's probably the default GUI theme textures. We could name
them so you know what they are..

**Comment by kubecz3k** [comment]
yeah that's probably a good idea to avoid confusion

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
