### ISSUE TITLE
[4.4 Dev 2 - Quest 3] Enabling `xr/openxr/enabled.editor` in OpenXR causes flatscreen editor to update at 1fps on Quest 3

### ISSUE THREAD

**Issue by JD-The-65th** [godotengine/godot#96831]
### Tested versions

- Reproducible in 4.4 dev 2

### System information

Godot v4.4.dev2 - Android - OpenGL ES 3 (Compatibility) - Adreno (TM) 740 -  (6 Threads)

### Issue description

In both Compatibility and Mobile renderer, setting ```enabled.editor``` to true in OpenXR settings causes the flatscreen editor to update at 1fps, but the XR player continues at normal speed.

### Steps to reproduce

1. Install Godot 4.4 dev 2 on Quest 3
2. Make a new project
3. Set ```enabled.editor``` to true in OpenXR Project settings
4. Restart the Editor.
5. Observe.

### Minimal reproduction project (MRP)

No MRP needed.

**Comment by BastiaanOlij** [comment]
cc @m4gr3d @dsnopek

**Comment by dsnopek** [comment]
I am able to reproduce this.

However, I feel like `xr/openxr/enabled.editor` shouldn't need to be enabled in order to launch XR apps from the editor, yet it seems to be in my testing. I'm not sure what changed since I last tested PR https://github.com/godotengine/godot/pull/96624, but I'm digging into it.

**Comment by dsnopek** [comment]
I just posted PR https://github.com/godotengine/godot/pull/96868 which fixes launching XR apps without enabling `xr/openxr/enabled.editor`. It doesn't fix the flatscreen editor updating at 1FPS, but it removes the need to enable `xr/openxr/enabled` in the first place
