### ISSUE TITLE
[Godot 4.4.dev2] 3D performance regressions [VoxelGI]

### ISSUE THREAD

**Issue by xsellier** [godotengine/godot#96953]
### Tested versions

- 4.4.dev-1
- 4.4.dev-2

### System information

Debian GNU/Linux trixie/sid x86_64 - Vulkan Forward +

### Issue description

Get 40 FPS on Godot 4.4.dev2 while I get a solid 60 FPS using Godot 4.4.dev1
There's only 2 physical objects in 2D, and 6 in 3D.

Vulkan renderer (Forward+)
![image](https://github.com/user-attachments/assets/c7c2f53c-5548-407c-91dd-50ca8795c913)

Compatibility (OpenGL, no stutter, 60 FPS):
![image](https://github.com/user-attachments/assets/9652372f-8566-4962-a1b6-6614921d607b)

### Steps to reproduce

1. Create a simple project with a VoxelGI node
2. Load it using Godot 4.4.dev1 enjoy 60 FPS
3. Load the very same project using Godot 4.4.dev2 get stuttering and ~40 FPS ich.

### Workaround

1. Disable VoxelGI

### Minimal reproduction project (MRP)

N/A

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to test, "create a simple project" isn't a trivial task to replicate the results and it helps a lot to have something to immediately see the results you're experiencing:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by xsellier** [comment]
Just create any 3D project add a VoxelGI node, and you're good to go.

**Comment by AThousandShips** [comment]
I can't replicate with just a VoxelGI node so please upload an MRP to clarify the conditions

**Comment by xsellier** [comment]
Sorry I don't have time to create a MRP for this issue. I'd rather stop using VoxelGI. 
Thank you for helping.

**Comment by akien-mga** [comment]
Likewise, with just a VoxelGI node, on Linux with AMD Radeon RX 7600M XT, and enabling "Update Continuously" in the editor to be able to go above 145 FPS, I get:
- 4.3.stable: 620 FPS
- 4.4.dev2: 630 FPS

**Comment by AThousandShips** [comment]
> Sorry I don't have time to create a MRP for this issue. I'd rather stop using VoxelGI.

That's unfortunate, good luck!

**Comment by xsellier** [comment]
I closed this ticket a bit too soon.
would it be useful if I share with you a debug binary of the project? So you can investigate?

**Comment by AThousandShips** [comment]
That wouldn't really be useful I'm afraid, an MRP would be required to test with and confirm any fix

**Comment by Saul2022** [comment]
This is confusing, you say you have 60 fps on 4.4. Dev 1 but there you are using the compatibility renderer, meanwhile in 4.4 dev 2 you are using forward+? Might it just be because voxel gi is unsupported on compatibilty renderer( and also consider that compatibility has cheaper default sethings for stuff like shadows, that might cause it)..

**Comment by AThousandShips** [comment]
Closing due to lack of response, if an MRP is added this can be reopened
