### ISSUE TITLE
Reordering properties from #93779 unsets editor set custom properties for [Tool] nodes.

### ISSUE THREAD

**Issue by pmoosi** [godotengine/godot#96983]
### Tested versions

- Reproducible in 4.4 after #93779

### System information

Godot v4.4.dev.mono (40d8d82b8) - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - integrated AMD Radeon Graphics (RADV RENOIR) - AMD Ryzen 7 5800H with Radeon Graphics (16 Threads)

### Issue description

The reordering done by #93779 seems to unset the custom properties set via the editor for `[Tool]` annotated scripts.

### Steps to reproduce

Create some node, attach a C# script with some custom property and annotate it with `[Tool]`.

After building, set the property in the editor. When reloading the scene, it will be unset/set to the default value. 

### Minimal reproduction project (MRP)

[mrp.zip](https://github.com/user-attachments/files/17002599/mrp.zip)

**Comment by AThousandShips** [comment]
Please upload an MRP to make this easier to confirm and test

**Comment by pmoosi** [comment]
Just added one.

**Comment by raulsntos** [comment]
Looks like https://github.com/godotengine/godot/pull/93779 reintroduced https://github.com/godotengine/godot/issues/54414. The `script` property must always be serialized before all the script's custom properties because, until we reach the `script` property, custom properties will be unrecognized.

cc @hayahane
