### ISSUE TITLE
Adding `@tool` removes `@export` `reset` buttons?

### ISSUE THREAD

**Issue by rakkarage** [godotengine/godot#97025]
### Tested versions

- reproduced in v4.4.dev.custom_build [6681f2563]
- reproduced in v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.dev (6681f2563) - Ubuntu 24.04.1 LTS 24.04 - Wayland - Vulkan (Forward+) - dedicated AMD Radeon RX 6600 (RADV NAVI23) - 12th Gen Intel(R) Core(TM) i5-12400F (12 Threads)

### Issue description

```
extends Control

@export var my_value = 0
@export var my_scene: NodePath # yes bad name, np
```

This simple code works and reset shows. Even after `Project->Reload Current Project`.

But once you add `@tool` to top and `Project->Reload Current Project` reset buttons gone.

Thanks.

### Steps to reproduce

- export value
- change value to show reset button
  - reload to ensure
- add `@tool`
  - reload to test
 

### Minimal reproduction project (MRP)

https://github.com/rakkarage/test_reset

**Comment by CreatedBySeb** [comment]
Reproduced on Godot v4.4.dev (6681f2563) - macOS 14.6.1 - Metal (Mobile) - integrated Apple M1 (Apple7) - Apple M1 (8 Threads)

Additional things of interest:

* If you have a tool script inheriting from a non-tool script, then reset is also broken for exported properties of the non-tool script on reload, but not for built in classes like Node2D
* The problem goes away consistently if you navigate to another scene and back
* The issue seems to be occurring in `GDScript::get_property_default_value` returning false with no default rather than true with one
  * Both `member_default_values_cache` and `base_cache` appear to be uninitialised on project load, however when you navigate to another scene and back both are initialised with the expected values *(I had my tool script inheriting from a non-tool script)*
  * When using a non-tool script, `member_default_values_cache` is initialised on project load *(my non-tool script did not inherit from another script, so base_cache was not initialised in either case which I believe is correct)*
  * This indicates there is likely some difference between how the tool scripts are being loaded on project load or when loading a scene, which is causing the problem
  * The only place `member_default_values_cache` seems to be set/updated is here: https://github.com/godotengine/godot/blob/6681f2563b99e14929a8acb27f4908fece398ef1/modules/gdscript/gdscript.cpp#L558-L566 so the difference is likely to be somewhere here

This is where I've gotten to so far, my guess is that it is to do with one of the conditions earlier in the same function or whether the function is being called. I may come back to this in a little bit, but I have to get some other things done so I thought I'd leave my notes in case anyone looks at this in the mean time.

**Comment by AThousandShips** [comment]
Can't replicate with the given instructions in 4.4 [6daa6a851]

The `control.tscn` scene works just fine, did you miss some further instructions?

**Comment by rakkarage** [comment]
happens in:
v4.4.dev.custom_build [6681f2563]

not in, maybe was fixed in last few days?
v4.4.dev.custom_build [a75bacebe]

thanks.
