### ISSUE TITLE
AMD FSR 2.2 Small Visual Artefacts

### ISSUE THREAD

**Issue by skami48** [godotengine/godot#97084]
### Tested versions

Test in godot 4.3.stable.mono.official.77dcf97d8

### System information

Godot v4.3.stable.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated AMD Radeon RX 7900 XTX (Advanced Micro Devices, Inc.; 32.0.11037.4004) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

using an amd gpu AMD Radeon RX 7900 XTX , in the godot TPS Exemple there is some artefacts on the player with FSR 2.2 on FSR 1 everything is Fine

https://github.com/user-attachments/assets/65f35ab0-8cad-4e6f-8a1c-77b492da7ed1

![Capture d'écran 2024-09-16 190025](https://github.com/user-attachments/assets/74db2bfd-096d-445d-9dc6-bc50b66efb8f)

### Steps to reproduce

Start the TPS exemple with an amd gpu and FSR 2.2 ON
There is the configuration
![Capture d'écran 2024-09-16 190529](https://github.com/user-attachments/assets/6e006369-2d7a-4e2e-bd07-6f5d5cf479f9)

### Minimal reproduction project (MRP)

https://github.com/godotengine/tps-demo
(Master Branch)

**Comment by Calinou** [comment]
This is because skeleton movement in the TPS demo isn't interpolated (it follows the **Physics Ticks per Second** project setting), so the mismatch between rendered FPS and skeleton movement creates artifacts.

This ghosting was fixed by https://github.com/godotengine/godot/pull/95705 which will be in 4.3.1, although skeleton movement is still not interpolated.
