### ISSUE TITLE
ScrollContainer cannot correctly clip the Button focus style.

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#97149]
### Tested versions

I tested versions 4.1 to 4.4, and they all have the same issue.

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

![9@RHYISUWOZ1NP2XF%W0DZA](https://github.com/user-attachments/assets/db306105-6941-4c7c-a2f4-183b38bffca8)
![MM `S}E 7J{O6Y26`DMOUD5](https://github.com/user-attachments/assets/2d3e6e23-5ef7-485c-b711-fa91e531f2e2)

### Steps to reproduce

See the image above.

### Minimal reproduction project (MRP)

[ctl_scn.zip](https://github.com/user-attachments/files/17046007/ctl_scn.zip)

**Comment by AThousandShips** [comment]
I'd say you need some margins around your content, just putting a plain button gets very cramped in a container like this

**Comment by kleonc** [comment]
>ScrollContainer cannot correctly clip the Button focus style.

In the presented example the ScrollContainer correctly clips the child contents to its bounding rect, I don't see any bug in here.

---

Note that the default `focus` StyleBoxFlat used by the Button has positive expand margins, that's why it's exceeding Button's rect (these margins are meant to be not taken into account for minimum size calculations).

```gdscript
extends Button

func _ready() -> void:
	var focus: StyleBox = get_theme_stylebox("focus")
	for p in f.get_property_list():
		print("%-30s = %s" % [p.name, focus.get(p.name)])
```
![Godot_v4 3-stable_win64_pU0Sl7JdR0](https://github.com/user-attachments/assets/31dbf499-fbdf-405f-87d4-b1ed2eb65867)

E.g. setting them to `0` makes such focus-border fit within the Button's rect (and hence within the parent VBoxContainer's/ScrollContainer's rects as well).

```gdscript
extends Button

func _ready() -> void:
	var f: StyleBoxFlat = get_theme_stylebox("focus")
	f.expand_margin_bottom = 0
	f.expand_margin_left = 0
	f.expand_margin_right = 0
	f.expand_margin_top = 0
```
![Godot_v4 3-stable_win64_HTs42IsKfm](https://github.com/user-attachments/assets/ab0a0248-238f-4b7f-9c16-6a7be5dbcf4b)

**Comment by WhalesState** [comment]
You can use a `MarginContainer` as a child for each `ScrollContainer` to provide some margin for it's own children or to create a `Theme` for the project to override the `focus` style boxes.

**Comment by KoBeWi** [comment]
btw you can change `clip_contents` from the inspector.

**Comment by WhalesState** [comment]
> btw you can change `clip_contents` from the inspector.

Maybe it's a bad idea for `ScrollContainer`.

**Comment by timothyqiu** [comment]
Maybe he means that the focus box should be clipped separately from the control itself. For example, a focus box like the one on the right side:

![image](https://github.com/user-attachments/assets/198054d3-716b-4ca3-a24b-1e4eb915f289)

We do have some controls that work like this. See https://github.com/godotengine/godot/issues/74670

**Comment by WhalesState** [comment]
Sounds like a feature and a bug, useful and yet can draw over other controls which will be annoying for most users.
Is this common for GUI in other engines to not allow clipping the focus border ?

**Comment by zedrun00** [comment]
> Note that the default `focus` StyleBoxFlat used by the Button has positive expand margins, that's why it's exceeding Button's rect (these margins are meant to be not taken into account for minimum size calculations).
