### ISSUE TITLE
Odd behavior with shaders drawing to DEPTH

### ISSUE THREAD

**Issue by 0x0ACB** [godotengine/godot#97226]
### Tested versions

4.3-stable

### System information

Windows 11, Vulkan

### Issue description

I am trying to create a shader that causes an object to only appear in the `DEPTH` buffer and not be visible on screen under certain conditions. However I am noticing some strange behavior.

This shader will always draw the object with a default albedo of white:
```
shader_type spatial;
render_mode depth_draw_always;

void fragment() 
{
	DEPTH = FRAGCOORD.z;
}
```

This shader will only draw to the `DEPTH` buffer:
```
shader_type spatial;
render_mode depth_draw_always;

void fragment() 
{
	DEPTH = 1.0;
}
```

However adding any write to `ALPHA` or `ALBEDO` will cause the object to appear in white again even if alpha is set to `0.0`.

I am currently using a secondary pass to actually shade the object if desired but it is kinda odd that anything other than `DEPTH = 1.0;` will cause the object to be rendered.

### Steps to reproduce

Test the provided shaders

### Minimal reproduction project (MRP)

```
shader_type spatial;
render_mode depth_draw_always;

void fragment() 
{
	DEPTH = FRAGCOORD.z;
}
```

```
shader_type spatial;
render_mode depth_draw_always;

void fragment() 
{
	DEPTH = 1.0;
}
```

**Comment by clayjohn** [comment]
Godot doesn't have an option for only writing to depth. When you create a shader that doesn't write to `ALBEDO` etc. The defaults are used (e.g. white for `ALBEDO`). 

When you set `DEPTH` to `1.0` you are aligning it directly with the near plane. So the pixels are getting discarded for being too close to the near plane. 

Ultimately this isn't a bug, so I'm going to close this bug report. I suspect that you have an effect in mind that isn't possible with Godot right now, so I suggest thinking a bit more about what you are trying to do and what is missing in Godot for you to do it, then open a [proposal](https://github.com/godotengine/godot-proposals) that clearly describes the effect you are trying to make and what you need exposed in order to make it.

**Comment by 0x0ACB** [comment]
The thing is that it is in fact possible. DEPTH = 1.0 does exactly what I want it to do
