### ISSUE TITLE
Keydown and cycle through itemlist based on first letter / findings

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#9724]
**Operating system or device - Godot version:**
2.13, and 3.0 stable (checked on both)

**Issue description:**
This would be a huge UX quality of life improvement I think!

For example:
![](https://i.gyazo.com/347fa22a38ae75e4ae8e22868f202fc5.gif)

When you press `s` it only goes **to the first** itemlist item  found.

If you press it a second time, I'm suggesting it should cycle to `StaticBody`, and so on, like this:

![](https://i.gyazo.com/c5e5ed06b32567e2d4a608550ea393af.gif)

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
