### ISSUE TITLE
Parallax2D glitches when changing the autoscroll value at runtime

### ISSUE THREAD

**Issue by LuisEscorza** [godotengine/godot#97605]
### Tested versions

- Reproducible in 4.3.stable

### System information

Windows 11 - NVIDIA GeForce GTX 1080 Ti - Intel Core i7-7700K CPU

### Issue description

When setting the `autoscroll` value of a `Parallax2D` at runtime, the layer kind of glitches(teleports) instead of just start scrolling faster or slower. My guess is that every time the autoscroll value changes, it recalculates the current offset based on the new value. The problem is that since autoscroll movement is unaffected by the scale values, we don't have a way to change the speed without making it look bad.  

### Steps to reproduce

- Add a `Parallax2D` node with a `Sprite2D` as a child.
- Change the `autoscroll` value at runtime.

### Minimal reproduction project (MRP)

[parallax2d_autroscroll_mrp.zip](https://github.com/user-attachments/files/17177124/parallax2d_autroscroll_mrp.zip)

**Comment by markdibarry** [comment]
This was intentional at first, because it was a choice between resetting whenever you update, or no way to reset at all. Last month we figured out a way to restructure things a bit to allow both by making it use `scroll_offset` internally. [This was merged](https://github.com/godotengine/godot/pull/96245) and is currently available in the 4.4 snapshots.

**Comment by LuisEscorza** [comment]
Oh that's awesome news, thank you! Sorry that I only looked up in the issues page, didn't realise this was already changed.. 😅
