### ISSUE TITLE
syntactic sugar: 'implements' for pseudo-interface simulation

### ISSUE THREAD

**Issue by willnationsdev** [godotengine/godot#9760]
It would be extremely convenient if there were a simple way to test whether a set of methods were implemented. I made the title "pseudo-interface" since there is no function overloading in GDScript. Currently you have to for-loop your way through comparisons of the method list and it looks quite ugly when all I really wanna know is whether object X contains a superset of the array of methods I'm passing it.

Bonus points if it could work with either an array of strings OR a Script resource:

    var MyInterfaceMethods = preload("res://MyInterface.gd").get_method_list()
    var hasSubsetOfMethods = true
    for method in MyInterfaceMethods:
        hasSubsetOfMethods &= has_method(method)
    if hasSubsetOfMethods:

becomes equivalent to...

    var MyInterface = preload("res://MyInterface.gd")
    if self implements MyInterface:

or...

    var MyInterfaceMethods = preload('res://MyInterface.gd").get_method_list()
    if self implements MyInterfaceMethods:

**Comment by Calinou** [comment]
I think this issue should be remade as a [proposal](https://github.com/godotengine/godot-proposals) if you still need it.

**Comment by willnationsdev** [comment]
Yeah, I think if I were to redesign this as a proposal, I'd make it more reliant on something like #24262 so that a name is bound to a cached collection of methods and you can perform static checks to see if something matches up with the group's interface. There's a plugin out there like that iirc.

**Comment by akien-mga** [comment]
Feature and improvement proposals for the Godot Engine are now being discussed and reviewed in a dedicated [**Godot Improvement Proposals (GIP)**](https://github.com/godotengine/godot-proposals) ([godotengine/godot-proposals](https://github.com/godotengine/godot-proposals)) issue tracker. The GIP tracker has a detailed issue template designed so that proposals include all the relevant information to start a productive discussion and help the community assess the validity of the proposal for the engine.

The main ([godotengine/godot](https://github.com/godotengine/godot)) tracker is now solely dedicated to bug reports and Pull Requests, enabling contributors to have a better focus on bug fixing work. Therefore, we are now closing all older feature proposals on the main issue tracker.

If you are interested in this feature proposal, please [**open a new proposal on the GIP tracker**](https://github.com/godotengine/godot-proposals/issues/new/choose) following the given issue template (after checking that it doesn't exist already). Be sure to reference this closed issue if it includes any relevant discussion (which you are also encouraged to summarize in the new proposal). Thanks in advance!
