### ISSUE TITLE
Launching Godot as administrator prevents loading project from mapped network drive.

### ISSUE THREAD

**Issue by CantyCanadian** [godotengine/godot#97643]
### Tested versions

- Reproductible in v.4.4.dev2.mono.official

### System information

Godot v4.4.dev2.mono - Windows 10.0.22631 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 4090 (NVIDIA; 32.0.15.6094) - AMD Ryzen 7 7800X3D 8-Core Processor (16 Threads)

### Issue description

If I launch Godot as administrator, only my attached drives (C/D) shows up and are available to load from. However, running without it allows me to load from all my mapped drives. Considering that Godot sometimes has issues with dotnet without administrator, and that I keep my local project copies off my PC, this is quite annoying.

![image](https://github.com/user-attachments/assets/07872c88-9c4a-4e3d-951f-96e3b923712f)
![image](https://github.com/user-attachments/assets/a54c735a-5f9c-49af-8700-43131f7df991)

### Steps to reproduce

1. Map a network drive to your computer using the "Map Network Drive..." feature in Windows.
![image](https://github.com/user-attachments/assets/b3654cab-fdfc-4300-b412-192632861eb0)

2. Attempt to load any project from the mapped drive.

### Minimal reproduction project (MRP)

Any default empty project should work.

**Comment by Jano1312** [comment]
As far as i know this is the expected behavior in Windows, running as admin means basically it runs as a different user.
It has nothing to do with Godot.

As a workaround you could make a batch file to mount the drives as admin, like described here: https://superuser.com/questions/1248629/how-do-i-mount-network-drive-as-adminstrator-windows-10-single-user-pc

But i thing you should try to fix the problem that dotnet don't work properly as normal user.

**Comment by CantyCanadian** [comment]
Oh, I wasn't aware of that. Thank you very much for the answer, I'll do just that!

As for the dotnet stuff, I realized my problem was probably unrelated to dotnet so I'm back to the drawing board.
