### ISSUE TITLE
Modifier Keys with custom Keyboard layout cancel code complete dialog

### ISSUE THREAD

**Issue by jano256** [godotengine/godot#97640]
### Tested versions

Reproducible in:
- 4.3.stable.arch_linux
- latest Git build (4.4, commit id 658270e742ea46d049b4f29a9762d9ee9c0734af)
- v3.6.stable.official [de2f0f147]

### System information

Arch Linux, KDE 6, Wayland, custom xkeyboard-config

### Issue description

I use a custom keyboard layout ([Neo Mine](https://www.neo-layout.org/Layouts/mine/)).
This layout has some special modifier keys for additional layers on the Keyboard.

In the script editor the layout work as it should, except some modifier keys cancel the code complete dialog (like pressing ESC).

The problematic keys are shown here as left M4 and right M3. 
![grafik](https://github.com/user-attachments/assets/76fc1ece-43aa-468a-882c-230a0cd4ea7a)

The left M4 is recognized by the godot hotkey configurator as "Section" key.
[Keyboard Event Viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html) shows this:
![grafik](https://github.com/user-attachments/assets/289754dc-7b01-410f-9aae-e083af29f04a)

The right M3 is recognized by the godot hotkey configurator as "Apostrophe" key.
[Keyboard Event Viewer](https://w3c.github.io/uievents/tools/key-event-viewer.html) shows this:
![grafik](https://github.com/user-attachments/assets/1c019de0-5103-431a-bb8f-341040b6e032)

I need the left M4 modifier key to have up/down arrows and enter in my "home zone" to choose and confirm from the code complete dialog. But like said, this is impossible due to the cancel with the M4 key.
![grafik](https://github.com/user-attachments/assets/d09a63f2-bcfe-4fd8-9f5f-afe085540668)

It would be great if godot would ignore these keys in the code complete dialog, or generally keys that don't input any key (except esc).
Or if i could tell godot which keys to ignore.

### Steps to reproduce

Install custom keymap with modifier keys on other positions than default

### Minimal reproduction project (MRP)

Any gdscript inside godot script editor works

**Comment by HolonProduction** [comment]
For some reason [any key event that has a unicode value from the C0 group (control characters) will cancel code completion](https://github.com/godotengine/godot/blob/e3213aaef5e0e72b8272e65d989d3d8222be17ca/scene/gui/code_edit.cpp#L571), this also includes the NUL character which is set for the events from this issue, since they don't produce any characters. So the issue is observable with a default keyboard layout and some control keys as well (e.g. on my keyboard: numlock or scrolllock). We should probably remove this behavior and only use the `ui_cancel` action to cancel completion.

**Comment by Jano1312** [comment]
Oh thanks for the quick response.
Just compiled your code changes and can confirm it solves my problem.
Thank you very much!
