### ISSUE TITLE
This engine is not gendered, please add it 😋😋😋 now

### ISSUE THREAD

**Issue by shadowcreeper-hash** [godotengine/godot#97689]
### Tested versions

[godot.4.2]butx

### System information

windows 10 

### Issue description

OS: [window10] :This engine is not gendered, please add it 😋😋😋 now

### Steps to reproduce

[print(This engine is not gendered, please add it 😋😋😋 now )]

### Minimal reproduction project (MRP)

[N/A]
[reme.zip](https://github.com/user-attachments/files/17206432/reme.zip)

**Comment by SuperTemich2005** [comment]
this is very funny and original.

And then we have people on twitter complaining about being banned on GitHub...

**Comment by shadowcreeper-hash** [comment]
> this is very funny and original.
> 
> And then we have people on twitter complaining about being banned on GitHub...
This is really, really important. Can we add Dick and pu$$y to the engine assets and label the engine's gender? Otherwise, I can't focus on coding.
By the way, I am a Chinese developer, and I greatly admire your policies 🤓🤓🤓🤓🤓☝☝☝☝☝

**Comment by Canadaduh** [comment]
I apologize for being off-topic because I have nothing else to contribute to godot and thus this isn't a really issue.

But, I would like to say that I probably think godot should just delete the tweet and apologize that they made a tweet about woke. I know It was originally intended to be a joke about game engines being woke, but it became worse as soon the community manager fucked things up. Due to this, you'll need fix the problem that it is apparently causing. So many people pointed out the community manager and yet no one cares.

I hope we make peace, sort everything out, I apologize if my English is bad.

**Comment by CoreTaxxe** [comment]
> ### Tested versions
> 
> [godot.4.2]butx
> ### System information
> 
> windows 10
> ### Issue description
> 
> OS: [window10] :This engine is not gendered, please add it 😋😋😋 now
> ### Steps to reproduce
> 
> [print(This engine is not gendered, please add it 😋😋😋 now )]
> ### Minimal reproduction project (MRP)
> 
> [N/A] [reme.zip](https://github.com/user-attachments/files/17206432/reme.zip)

Very funny and mature.

**Comment by shadowcreeper-hash** [comment]
> > ### Tested versions
> > [godot.4.2]butx
> > ### System information
> > windows 10
> > ### Issue description
> > OS: [window10] :This engine is not gendered, please add it 😋😋😋 now
> > ### Steps to reproduce
> > [print(This engine is not gendered, please add it 😋😋😋 now )]
> > ### Minimal reproduction project (MRP)
> > [N/A] [reme.zip](https://github.com/user-attachments/files/17206432/reme.zip)
> 
> Very funny and mature.

☝🤓thanks
