### ISSUE TITLE
Can't build with `ninja` option when `ninja` Python module is missing

### ISSUE THREAD

**Issue by dustdfg** [godotengine/godot#97729]
### Tested versions

master

### System information

Debian testing; SCons 4.5.2; Python 3.12.6; ninja 1.12

### Issue description

When I run `scons ninja="yes"` I get an error:

```

scons: *** Failed to import ninja, attempt normal SCons build.
File "/storage/git_build/godot/SConstruct", line 1079, in <module>
```

`scons -h` says:

```
ninja: Use the ninja backend for faster rebuilds (yes|no)
    default: False
    actual: False

ninja_auto_run: Run ninja automatically after generating the ninja file (yes|no)
    default: True
    actual: True

ninja_file: Path to the generated ninja file
    default: build.ninja
    actual: build.ninja
```
It looks like it must generate the ninja file and then run ninja but it doesn't generate anything except error

### Steps to reproduce

N/A

### Minimal reproduction project (MRP)

N/A

**Comment by akien-mga** [comment]
It seems to fail importing the Python module for `ninja`, you might be missing it.
From a quick search I didn't find a Python module in Debian's `ninja-build` package (though it suggests python3), and I don't see it elsewhere. Maybe they don't package it?

`pip install ninja` should solve it.

We should probably abort instead of falling back to a normal build if the `ninja` module is not found.

**Comment by dustdfg** [comment]
`pip install ninja` worked. Thanks!
