### ISSUE TITLE
Ctrl + mouse middle button zoom doesn't work in 4.4 dev2, 3

### ISSUE THREAD

**Issue by Re-drem** [godotengine/godot#97732]
### Tested versions

Reproduciable in 4.4dev2, 4.4dev3

### System information

Windows 10 - Godot v4.4dev(2, 3) - Vulkan/d3d12 Forward+

### Issue description

In the title

### Steps to reproduce

Press Ctrl and middle mouse button (scrollwheel) and move mouse up and down. In 4.4dev2, 3 it doesn't work but in every other version it does

### Minimal reproduction project (MRP)

[sddfddfgdfgd.zip](https://github.com/user-attachments/files/17230735/sddfddfgdfgd.zip)

**Comment by AThousandShips** [comment]
Where is this functionality? Is it general or area specific?

**Comment by Re-drem** [comment]
you can use it in 3D mode in the editor to zoom in. it's more precise than using scroll wheel by itself

**Comment by EAinsley** [comment]
New navigation setting was updated by merging this pr: #85331 . Now the key is ctrl + shift + middle mouse. You can view the settings at Editor > Editor Settings >Editors > 3D > Navigation Scheme. Although I didn't see a choice to change the zoom back to ctrl + middle mouse.

**Comment by RobProductions** [comment]
Hmm... This might have been an old workaround I put in for the ordering issues mentioned in #85331 , since middle mouse was also used to pan and rotate which might have created conflicts with the logic since it was no longer checked in a hardcoded order. I ended up fixing the ordering issues before it got merged but might have forgotten to restore this, apologies if that's the case.

Although you can restore it by customizing the "Viewport Zoom Modifiers" in `Shortcuts`, it's probably better to leave the Godot preset buttons the way they were in 4.3. Since the logic should be able to handle this now I'll get a PR ready to correct that, thanks for reporting it!
