### ISSUE TITLE
[4.4.dev3] .editorconfig file gets created in Godot project root directory

### ISSUE THREAD

**Issue by FoxyFox909** [godotengine/godot#97796]
### Tested versions

v4.4.dev3.official [f4af8201b]

### System information

Windows 10

### Issue description

An `.editorconfig` file is created in the root directory of new projects. Also occurs when opening existing projects from earlier versions. The file will be generated. If deleted, the file will be re-generated next time Godot opens that project.

### Steps to reproduce

Open Godot, create a new project. Open the new project's directory. Observe `.editorconfig` file in the project's root directory.

### Minimal reproduction project (MRP)

N/A

**Comment by timothyqiu** [comment]
See also https://github.com/godotengine/godot/pull/97270

**Comment by FoxyFox909** [comment]
Yeah, that would be useful. I honestly couldn't even be sure if `.editorconfig` being generated was intentional. EditorConfig doesn't support GDScript, it seems.

**Comment by bruvzg** [comment]
> I honestly couldn't even be sure if .editorconfig being generated was intentional

`.editorconfig` was added specifically for Visual Studio, since it's incapable of correctly detecting UTF-8 file encoding without BOM (and use BOM is discouraged by Unicode and essentially only used by VS) and was corrupting any opened file with non-Latin comments/code. Mostly relevant for .NET version, since it's commonly used with external IDE. It should not have any practical effect on other IDEs, since most use UTF-8 by default. Also, should not have any effect if you have you own version of `.editorconfig`, Godot won't overwrite it.
