### ISSUE TITLE
No method to convert a Vector3 of euler angles to a direction Vector3

### ISSUE THREAD

**Issue by hikari-no-yume** [godotengine/godot#9784]
This can be done by hand, but it would be convenient if it did not need to be.

The particular use-case I had was zooming in/out a camera, where it would be convenient to do it this way with a hypothetical `.as_direction()` method:

```GDscript
translate(get_rotation().as_direction() * zoom_factor)
```

I found an alternative solution (`translate(project_local_ray_normal(get_viewport().get_rect().size/2) * zoom_factor)`), but such a method could be useful in other contexts, like moving other objects around.

**Comment by bojidar-bg** [comment]
Shouldn't it be a method of Spatial / Transform?

**Comment by kubecz3k** [comment]
well in that particular use case you should get forward vector of `camera` with `get_transform().basis.z`

**Comment by bojidar-bg** [comment]
@kubecz3k Yea, but this is not very intuitive, in case someone doesn't have an idea how transforms work...

**Comment by tagcup** [comment]
Quick note about terminology: Euler angles don't form a vector actually, it's just an array of 3 numbers.

Basis::get_axis_angle is on my todo list, which would return an axis (a unit vector with 2 independent parameters) and an angle, but since functions can't return 2 values in gdscript (no references or tuples), I haven't implement this yet.

I can submit a PR for C++ implementation using reference parameters to return the value if you think that's an acceptable API but I don't know how this can be exposed to gdscript nicely without creating new objects like dictionaries.

**Comment by tagcup** [comment]
About your particular problem, as others have pointed out, columns of basis matrix are local basis vectors "painted" on the object, that rotate and scale with it, expressed in the global coordinate system. So you basically just need to to pick the relevant column of your basis matrix and normalize it.

**Comment by tagcup** [comment]
About the inventiveness, in my opinion, anyone who's writing a 3D game should at least understand what the transform matrix is, in and out.

I'm a bit busy nowadays but I'll hopefully finish a guide related to 3D math before 3.0 release.

**Comment by RandomShaper** [comment]
@tagcup, you could have a look at how some helpers from `Geometry` are exposed through a bridge function. Not sure if that's what you are looking for; just my two cents.

**Comment by hikari-no-yume** [comment]
Yeah, the `basis` matrix is quite useful, I just used it for something else right now. Thanks!

**Comment by tagcup** [comment]
I almost forgot, `Basis::get_axis_angle()` is already in place in C++, it's just not not exposed to GDScript (yet).
