### ISSUE TITLE
WebSockets don't report the correct state after closing due to "message too big".

### ISSUE THREAD

**Issue by DjSapsan** [godotengine/godot#97899]
### Tested versions

Godot v4.4.dev2 - supports only TLS1.2 and fails because of lack of 1.3
Godot v4.4.dev (506d6e427) - a newly complied version that is supposed to add support for 1.3 but fails

### System information

Ubuntu 24.04.1 LTS 24.04 - X11 - OpenGL 3 (Compatibility) - NVIDIA GeForce RTX 2060 (nvidia; 550.107.02) - AMD Ryzen 9 5900X 12-Core Processor (24 Threads)

### Issue description

Can't load information from a server using WSS due to bad TLS1.3 support.
It doesn't work in any version, but this issue is intended for the latest attempts at adding full TLS1.3 support ([issue](https://github.com/godotengine/godot/pull/96394), [issue](https://github.com/godotengine/godot/issues/92101)).
So the problem now (as I understand it) is that server sends a lot of data, but Godot can't handle it all. After a short working period it shows errors of ZeroWindow and sometimes others. It means that the client (Godot app) can't receive data fast enough. A browser and Postman still loading the same data perfectly fine.
I think it has something to do with the buffers or maybe something else. How it happens is shown on the screenshot from Wireshark log. Otherwise it's probably working for smaller amount of data, but it's not enough.

![image](https://github.com/user-attachments/assets/d9766d95-492e-4862-b33a-e1ffe37e16c8).

It's not a problem on the server side, as the loading is working perfectly fine in the [browser](https://aoe2lobby.com/spectate) and in Postman tests.

<details>
 <summary>Creator of the server allowed to use it </summary>

![image](https://github.com/user-attachments/assets/37eb7a53-719f-42a8-889a-c7ea706a4a43)

</details>

### Steps to reproduce

Try to use WSS in any version in any way to load data from https://aoe2lobby.com/spectate.
WSS address: wss://aoe2lobby.com/ws/spectate/
Must have headers: var arrayHeaders = PackedStringArray([
	"Origin: https://aoe2lobby.com/ws/spectate",
])

Also, an alternative is not working in the same way - wss://aoe2recs.com/dashboard/api/

### Minimal reproduction project (MRP)

[bad WSS.zip](https://github.com/user-attachments/files/17270525/bad.WSS.zip)

**Comment by Faless** [comment]
The default URL (`wss://aoe2lobby.com/ws/spectate`) returns a 500 during the handshake, so there is something wrong with the server.

Trying the other url (`wss://aoe2recs.com/dashboard/api/`) I see it's sending a huge message (`172108`) which is more than the default max packet / buffer size (`65535` bytes).

After changing the [inbound_buffer_size](https://docs.godotengine.org/en/stable/classes/class_websocketpeer.html#class-websocketpeer-property-inbound-buffer-size) to something bigger (e.g. 1 MiB, `socket.inbound_buffer_size = (1 << 20) - 1`) it seems to work correctly.

In this scenario wslay (the library we use) should send `WSLAY_CODE_MESSAGE_TOO_BIG` (1009) to the server and close the connection. It appears that we are not correctly updating the internal state to transition to `STATE_CLOSING` or `STATE_CLOSED`.

In any case, the problem is that the inbound buffer is smaller than what the server sends. You should increase the inbound buffer of the socket.

**Comment by DjSapsan** [comment]
nice, after I increased the buffer to 1 MiB it's working now. Huge thanks, I never set it so large before

**Comment by DjSapsan** [comment]
@Faless sorry, does it support more than 1 MiB? I Increased it to hundreds of MB bit it's skipping the big load. It's just not disconnecting anymore and then periodically can recieve small updates.

![image](https://github.com/user-attachments/assets/eadc8282-81b8-41e1-9d9d-15ed2c3376ac)
