### ISSUE TITLE
[Suggestion] - Alpha transparency for cells?

### ISSUE THREAD

**Issue by Dillybob92** [godotengine/godot#9805]
**Operating system or device - Godot version:**
2.1.3 stable

**Issue description:**
After looking at the fog of war demo, it's nice. However, that got me thinking of `set_cell`

`void set_cell( int x, int y, int tile, bool flip_x=false, bool flip_y=false, bool transpose=false )`

maybe, add an optional parameter for alpha transparency? (0.00 to 1)

This way, you could create smooth fading out effects with fog (or whatever tile you choose). Or would this be too big of a performance issue?

**Comment by akien-mga** [comment]
*Bug triage note:* The original issue reporter closed all their issues before deleting their account. If you are affected by a similar issue/want a similar feature, please file a new ticket (referencing this one if it contains useful information) so that it can be further looked at and eventually resolved.
