### ISSUE TITLE
Double ColorRect with custom shader material hides underlying controls

### ISSUE THREAD

**Issue by smedelyan** [godotengine/godot#98060]
### Tested versions

Reproducible on:
- 4.2.2.stable (I have to stay on this version due to issues with migration to 4.3)
- 4.3.stable

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Mobile) - dedicated NVIDIA GeForce GTX 1660 (NVIDIA; 32.0.15.6590) - AMD Ryzen 7 2700X Eight-Core Processor (16 Threads)

### Issue description

It's hard to describe concisely, so instead I walk you through step by step.

Here's the scene. Two texture rects are here just to display some content.
![image](https://github.com/user-attachments/assets/00c491ee-767b-4d8c-a1b8-29d3dfbda74b)

`ColorRect`-s have custom shader material with shader (which is very simple blur). Both material and shader are made unique for these `ColorRect`-s:
![image](https://github.com/user-attachments/assets/7c51d424-87ea-4915-84da-e4adaac621d9)

When only one of `ColorRect`-s is visible, the result is OK and expected:
![image](https://github.com/user-attachments/assets/faa54671-188b-4e4c-9d24-758f0e578c7b)
![image](https://github.com/user-attachments/assets/77055122-8d7c-4176-8852-0506712edaa9)

However, when **both** are visible, this results in a weird artifact: the second `TextureRect` gets wiped out from the render completely. It's not visible anymore.
![image](https://github.com/user-attachments/assets/7ab9e303-4aad-41f7-bba3-6c7c716b2202)

Maybe this is something related to sharing screen texture in shader? Does it somehow gets "frozen" at some stage? However, this weird behavior only happens where 2 `ColorRect`-s overlap. If you resize the top `ColorRect` it starts showing part of the content behind it:
![image](https://github.com/user-attachments/assets/f047cead-e117-4ee1-8a73-3ca968449c41)

I also find weird result when I change alpha channel of that `ColorRect`:
![image](https://github.com/user-attachments/assets/d2f24716-8480-458e-81ab-257079f20eac)

However, I don't believe that changing color (including its alpha) of `ColorRect` should affect anything because it's render must be fully controlled by the supplied shader.

I would expect the result to be double blur applied:
1. First `ColorRect` blurs background
2. Second `ColorRect` blurs the result of p. 1 (including foreground `TextureRect`)

GIF demonstration attached below as well:
![demo](https://github.com/user-attachments/assets/17152b34-8086-4b2c-a666-488b4093949b)

### Steps to reproduce

Follow the steps in issue description. MRP's provided as well.

### Minimal reproduction project (MRP)

[weird_gui.zip](https://github.com/user-attachments/files/17329852/weird_gui.zip)

**Comment by Lielay9** [comment]
The `screen_texture` is reused between the ColorRects, and importantly, toggling the visibility affects when the snapshot of the underlying scene is created. When the first ColorRect is visible, the `screen_texture` only contains content before it in the tree i.e. the first TextureRect and the gray background color. The second TextureRect is not present in the `screen_texture` (I mean how could it? It hasn't been drawn yet) which is why it is covered by the second ColorRect that only contains the content present when the first was drawn. Creating a copy of the screen is a rather slow-process so it isn't done automatically (excluding the first time). To opt in for a new snapshot, you can insert a `BackBufferCopy` before the second `ColorRect`:

<img width="736" alt="Screenshot 2024-10-11 050030" src="https://github.com/user-attachments/assets/52c45450-8cf8-4596-a4e7-ba56b0dea7cc">


You can read more about this in the docs: https://docs.godotengine.org/en/stable/tutorials/shaders/screen-reading_shaders.html#behind-the-scenes

**Comment by smedelyan** [comment]
Got it, thanks! My bad not reading the docs well enough.
Btw, the issue can also be solved by placing each pair of `TextureRect` + `ColorRect` onto separate `CanvasLayer`
