### ISSUE TITLE
Arithmetic Expressions in Exported Floats Round to Nearest Integer

### ISSUE THREAD

**Issue by zurasuta** [godotengine/godot#98130]
### Tested versions

v4.3.stable.steam [77dcf97d8]

### System information

Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce GTX 980 Ti (NVIDIA; 32.0.15.5585) - Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 Threads)

### Issue description

I have the following exported variables:

```
@export var value : float
@export var defaulted_value : float = 0.0
@export var starting_at_half : float = 0.5
```
![image](https://github.com/user-attachments/assets/80e60fce-d64c-4a1b-bb4c-cd03f62e0a2c)

When I try to use any arithmetic expression to determine a value on their fields, like 1/2, 5/3 or 7/2, I expect to get 0.5, 1.666, and 3.5 respectively, but instead I get 0, 1, and 3, despite the variables being float types.

This is not an issue with the Default Float Step. It's by defaut, at 0.001, and when I print the values of the variables, they are indeed these rounded values. 

This also happens with @export_exp_easing(), and it happens to the three variables I have.

### Steps to reproduce

1. Export a float variable in a script.
2. Save the file or wait for the Inspector to update.
3. Put a fractional expression in its field that shouldn't give back a round number (i.e. 1/2, 1/3, 2/5, etc..).
4. Hit Enter.

### Minimal reproduction project (MRP)

[expressions.zip](https://github.com/user-attachments/files/17352580/expressions.zip)

**Comment by zurasuta** [comment]
Oh, this is embarrasing. I see in the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/evaluating_expressions.html) that it will only work (But it can work) as long as one of the numbers has a floating-point value. Is there a reason it's this way despite the variable being a float?

**Comment by zurasuta** [comment]
Oh, this is embarrasing. I see in the [documentation](https://docs.godotengine.org/en/stable/tutorials/scripting/evaluating_expressions.html) that it will only work (But it can work) as long as one of the numbers has a floating-point value. Is there a reason it's this way despite the variable being a float?

**Comment by AtlaStar** [comment]
@zurasuta it is to match the behavior of the underlying C\C++ the engine is written in; it has to do with type promotion.

Dividing an integer by an integer will always return an integer, which has no fractional part and thus returns the truncated value. So 1/2 will be 0, 4/3 will be 1, etc. Since no value is anything other than an integer no type promotion is required to occur, so it simply doesn't.

When you have something like 1.0 / 3, or 3/2.0, since one of those values is of a floating point type in the equation, the integer is implicitly promoted to the same type of floating point before division occurs. So 1.0 /3 becomes 1.0/3.0 implicitly, and 3/2.0 becomes 3.0/2.0, so float by float division occurs and a fractional value is returned.

**Comment by zurasuta** [comment]
@AtlaStar Thank you so much for explaining it to me! I might not fully understand but I appreciate it and I still think I get the gist of it. I'm not familiar with C and my knowledge of C++ is quite basic, so I didn't know about type promotion. Again, thank you.
