### ISSUE TITLE
Godot4 editor performance regressions when removing/moving 2D nodes

### ISSUE THREAD

**Issue by baboluoli** [godotengine/godot#98213]
### Tested versions

Reproducible in 4.3 stable, 3.5.3 stable works fine

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4887) - 12th Gen Intel(R) Core(TM) i7-1255U (12 Threads)

### Issue description

I have a 430 nodes big scene with a lot of houses that have say 8 tilemaps. This scene works completely fine in Godot3, no lag. I converted the scene to Godot4 and everytime I remove or add a node, I get a 4s lag. If I duplicate a house node (that has many tilemaps) say 40 times and then remove a node, I get significantly prolonged lag. There are no tool scripts. Doing the same thing in the Godot3 editor doesn't result in any noticeable lag.

Why is this relevant?

As a Godot 2D engine developer, I want to be able to create bigger scenes for bigger games productively and not limit my creativity.

Now, I get that there's a limit to the amount of nodes that Godot should support for most devs. Also Godot as an engine doesn't seem to care about performance that much (yet). But throughout versions the performance shouldn't worsen like that imo.

### Steps to reproduce

1. Add big enough nodes to the scene tree, with a lot of tilemaps
2. Duplicate them
3. Add a simple, new node (Node2D is enough)
4. See the freeze duration go up when moving or removing this node in the scene tree the more tilemap container nodes you add.

### Minimal reproduction project (MRP)

[laggyeditorgames.zip](https://github.com/user-attachments/files/17384719/laggyeditorgames.zip)

**Comment by firescaleVR** [comment]
It's not just you. There's been huge regressions since 4.2.2, my 3d scene freezes up for 7 seconds when adding/deleting any node and I get constant blue screen of death on 4.3. I don't know why no one else is talking about this. I'm sticking with 4.2.2/ testing other engines.

**Comment by YYF233333** [comment]
Tested on win10 i7-12700 GTX1050ti, adding a Node2D is almost instant, but duplicating subscene with lots of tilemaps is much slower compared to 3.5.

I've noticed this scene suffers fps drop when you moving the camera, while the GPU usage remains low. Switch to Compitability renderer solve this problem. Since you are using integrated GPU I'd recommand you check Compitability renderer to see if things go better.

**Comment by YYF233333** [comment]
> Adding a Node2D is almost instant for me too, but not removing or moving a Node2D.

Reproduced in my environment, so the problem is about remove node.

A quick profile below:

![image](https://github.com/user-attachments/assets/7960159f-2783-4dda-b784-38b0c532c2fe)

When you try to remove a node, the editor needs to check one by one whether other nodes needs to be renamed (seems related to undo/redo), during this it access the `property_list` of the node.

`TileSetAtlasSource::get_property_list` spent a lot of time formatting strings, which cause the lag.

![image](https://github.com/user-attachments/assets/22052377-6eeb-4778-a449-103ea523c216)

Related code: https://github.com/godotengine/godot/blob/af77100e394dcaca609b15bef815ed17475e51ed/scene/resources/2d/tile_set.cpp#L4933-L4955

**Comment by baboluoli** [comment]
Thank you, I updated to Godot 4.4 now. Adding a child looks fine now, it's a certain productivity boost. Though removing a child on my big 2d scene still takes 3s. Are there any other issues that track this? I'm scared of adding detail to my map

@Repiteo

**Comment by Calinou** [comment]
@baboluoli Please open a new issue with a minimal reproduction project attached.
