### ISSUE TITLE
Player animation won't play

### ISSUE THREAD

**Issue by BacqueV** [godotengine/godot#98366]
### Tested versions

- Godot 4.3-stable

### System information

Arch Linux - Godot 4.3.stable.arch_linux - Vulkan (Forward+)

### Issue description

i have only installed godot. added 2 scenes. 1 game and another is player. when i start debug it won't play the animation

```
E 0:00:02:0855   debug: Parameter "script_lang" is null.
  <Исходный код C++>core/debugger/remote_debugger.cpp:419 @ debug()
```

The source code on GitHub - https://github.com/godotengine/godot/blob/4.3-stable/core/debugger/remote_debugger.cpp#L419

### Steps to reproduce

add game scene and player
run game
pause the game
receive an error

### Minimal reproduction project (MRP)

simple godot project. there is nothing to say more

**Comment by AThousandShips** [comment]
Please provide an MRP to make this easier to test and fix:
- A small Godot project which reproduces the issue, with no unnecessary files included. Be sure to not include the `.godot` folder in the archive (but keep `project.godot`).
- Having an MRP is very important for contributors to be able to reproduce the bug in the same way that you are experiencing it. When testing a potential fix for the issue, contributors will use the MRP to validate that the fix is working as intended.
- Drag and drop a ZIP archive to upload it (max 10 MB). **Do not select another field until the project is done uploading.**
- **Note for C# users:** If your issue is *not* C#-specific, please upload a minimal reproduction project written in GDScript. This will make it easier for contributors to reproduce the issue locally as not everyone has a .NET setup available.

**Comment by BacqueV** [comment]
I noticed where the problem is. I didn't turn on autoplay. That's all

**Comment by BacqueV** [comment]
I mean, the animation didn't play because of autoplay, but "E 0:00:02:0855" still the same

**Comment by AThousandShips** [comment]
Closing due to lack of response, if you provide the requested information this can be reopened
