### ISSUE TITLE
Volumetric fog doesn't affect sky when sky is set to low luminance

### ISSUE THREAD

**Issue by Jamsers** [godotengine/godot#98640]
### Tested versions

- Reproducible in: v4.4.dev3.official [f4af8201b]
- Not reproducible in: v4.3.stable.official [77dcf97d8]

### System information

Godot v4.4.dev3 - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6603) - AMD Ryzen 5 5600H with Radeon Graphics (12 threads)

### Issue description

Volumetric fog doesn't affect sky when sky is set to low luminance.

![Screenshot (59)](https://github.com/user-attachments/assets/35e0f535-0a7a-494f-bba5-098ad0ed34e0)

![Screenshot (60)](https://github.com/user-attachments/assets/a05a54fa-c6c2-49df-a889-459489285c88)

![Screenshot (61)](https://github.com/user-attachments/assets/7bf0a16e-dceb-4b63-ab43-219493e826d2)

Regression was introduced with [578049b](https://github.com/godotengine/godot/commit/578049b7b9b9ba5d0ad02f89698a593c368ab7fc).

### Steps to reproduce

Can be reproduced in [Crater-Province-Level](https://github.com/Jamsers/Crater-Province-Level) by setting time of day to night.

### Minimal reproduction project (MRP)

[Crater-Province-Level](https://github.com/Jamsers/Crater-Province-Level)

**Comment by ArseniyMirniy** [comment]
I was probably wrong, they both affect the sky and here's the slider to adjust how much (check it):

![image](https://github.com/user-attachments/assets/133cbf24-4611-4349-85b0-1606d5eafca8)

**Comment by clayjohn** [comment]
I suspect that the fog is just getting darkened by the sky brightness rather than not being added. IIRC the sky brightness is multiplied at the end of the shader, so anything calculated will get brightened/darkened. 

What we need to do is separate the luminance calculation into two steps:
1. First multiply the sky by the sky brightness set by the user
2. Then multiply the sky by the luminance modifier (set internally depending on the renderer used)
