### ISSUE TITLE
NavigationServer3D.map_get_path return path too imprecise 

### ISSUE THREAD

**Issue by Miurg** [godotengine/godot#98953]
### Tested versions

- Reproducible in: v4.3.stable.official and v4.2.2-stable_mono

### System information

Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated AMD Radeon RX 7700 XT (Advanced Micro Devices, Inc.; 32.0.12019.1028) - AMD Ryzen 7 7700 8-Core Processor (16 Threads)

### Issue description

NavigationService3D returns incorrect path end on polygon edges in navigation mesh. And because of this all my pawns twitch at the edges of the polygons and sometimes don’t go where they should.
Cell size has no effect on this behavior.

https://github.com/user-attachments/assets/fe8fb836-bb38-4518-a54d-e1853c5ee337

![image](https://github.com/user-attachments/assets/903b270c-fcba-4d9f-a81c-ae8bb793043e)

### Steps to reproduce

1. Run the scene
2. Right mouse button to control
3. Walk around the scene, near the edges of the polygons in the navigation mesh

### Minimal reproduction project (MRP)

[reproduction-project(navigation edges).zip](https://github.com/user-attachments/files/17677149/reproduction-project.navigation.edges.zip)

**Comment by smix8** [comment]
I am not sure there is much else to be expected from similar navmesh layouts.

Some of those navmesh edges are just too long and slim. With such geometry like in the demo the basic core triangle functions alone will add so much float imprecision to cause problems.

You need to break up the navmesh edge layout, e.g. by tiling a world, to mitigate such precision issues.

In general there will always be a slight float difference between the input positions and the output positiosn when you query a path because things are remapped to the closest position on navmesh surface which also adds small float variance.
