### ISSUE TITLE
Shader flickering in 4.4-dev4

### ISSUE THREAD

**Issue by filkata** [godotengine/godot#99252]
### Tested versions

Reproducible in 4.4 dev4, not reproducible in 4.3 stable and 4.4 dev3

### System information

Godot v4.4.dev4 - Windows 10.0.19045 - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 (NVIDIA; 32.0.15.6094) - AMD Ryzen 5 1500X Quad-Core Processor (8 threads)

### Issue description

I am applying a shader to a Line2D node. The shader is a Voronoi edge shader based on https://iquilezles.org/articles/voronoilines/ and https://www.shadertoy.com/view/ldl3W8
The rendering method is Forward+

Before 4.4 dev4 it looks correct: 
![working](https://github.com/user-attachments/assets/a5534a99-5e6d-4bd9-9675-fd4430b9b5ef)

On 4.4 dev4 rapid flickering has appeared:
![broken](https://github.com/user-attachments/assets/9643c5a3-9600-40df-be4e-e6af14c12261)

### Steps to reproduce

Open the MRP with 4.4 dev4 and observe the issue. I have noticed that the static (non-animated) version where the regions do not move works - you can see it by commenting out lines 29 and 49, both are:
```point = 0.5 + 0.5*sin(TIME * frequency_road + 6.2831*point);```
so perhaps the issue is with this calculation

### Minimal reproduction project (MRP)

[shader_bug.zip](https://github.com/user-attachments/files/17758427/shader_bug.zip)

**Comment by clayjohn** [comment]
I get the same behaviour in dev3 and dev4, in both cases it is the same as what you have in dev4

**Comment by clayjohn** [comment]
Okay, I tracked down the issue. You have undefined behaviour in your shader, so its basically random what the GPU will end up doing. 

The `float d = dot(0.5*(mr+r), normalize(r-mr));` line introduces a division by 0 since `r` is the same as `mr`

You need to handle the case where `r` and `mr` are the same. How you do that will depend on what you want your shader to do. But simply setting `d` to `1.0` when `r` and `mr` are the same is enough to fix your MRP.

![image](https://github.com/user-attachments/assets/c07c5b87-f026-4216-937d-32592f5867ec)
