### ISSUE TITLE
Shader editor with invalid code prints many error messages, causing the editor to lag.

### ISSUE THREAD

**Issue by zedrun00** [godotengine/godot#99263]
### Tested versions

master[673f396677654220d7e1d5b6fb5ed3b50126b4e6]

### System information

win10 21H2,Vulkan API 1.2.0

### Issue description

https://github.com/user-attachments/assets/a17901d5-a2a5-498a-ad35-b7d331dd3bc1

### Steps to reproduce

look video

### Minimal reproduction project (MRP)

none

**Comment by akien-mga** [comment]
I can reproduce this with a custom dev build. It doesn't seem to have with 4.3.stable.
I believe I've seen @clayjohn mention that this only happens with dev builds recently.

IMO even for dev builds this is a significant usability issue that should be fixed.

**Comment by jadeharley2** [comment]
Same error in v4.4.dev5.official [9e6098432]
Erorr messages multiplied by every visible mesh with `ShaderMaterial` with error.
  (154724) Uniforms were never supplied for set (3) at the time of drawing, which are required by the pipeline.

**Comment by RPicster** [comment]
This is an absolutely brutal bug that makes writing shaders almost an impossible task.
As soon as you have an error by editing something the editor absolutely freezes from the error message spam.

**Comment by clayjohn** [comment]
Is this issue new in dev5?

**Comment by Lippanon** [comment]
> Is this issue new in dev5?

No. I'm seeing it too in v4.4.dev.custom_build [c6c464cf9].

**Comment by clayjohn** [comment]
This is a regression from https://github.com/godotengine/godot/pull/90400

Previously the `ShaderData` class would set its member `valid` to false when about to compile and then set it to `true` if compilation was successful (both shader compilation and setting up pipelines).

Then, when setting up geometry for drawing we checked if the `shader_data` of a material was valid, if not, we could fall back to the default material. 

Now instead of checking if `!shader_data->valid`, we do this: 

https://github.com/godotengine/godot/blob/aa8d9b83f66488dbb2c9c918e9016ef80f821fb4/servers/rendering/renderer_rd/forward_clustered/render_forward_clustered.cpp#L3984-L3986

https://github.com/godotengine/godot/blob/aa8d9b83f66488dbb2c9c918e9016ef80f821fb4/servers/rendering/renderer_rd/forward_clustered/scene_shader_forward_clustered.cpp#L435-L443

Which returns true after the first time a shader compilers successfully. I have a fix incoming
