### ISSUE TITLE
Setting AnimationTreePlayer unique for each sprite not working

### ISSUE THREAD

**Issue by michelveloso** [godotengine/godot#9926]
**Operating system or device - Godot version:**
On Windows 10 - v2.1.3.stable.official

**Issue description:**
I am trying to set the animation unique for each sprite, I looked in the forums but still nothing.
In the tool I have already set everything as "make unique", but no effect.
Has anyone ever experienced this?
Is it normal?

![image](https://user-images.githubusercontent.com/346317/28686886-27087e72-72e3-11e7-96a6-7deaaa57a858.png)

![image](https://user-images.githubusercontent.com/346317/28686910-396e42cc-72e3-11e7-919c-540a253f1dee.png)

![image](https://user-images.githubusercontent.com/346317/28686932-4bb7edf2-72e3-11e7-9c9b-7a0e931281a2.png)

Video Error
https://youtu.be/0I1FPSyMihI

**Comment by akien-mga** [comment]
`AnimationTreePlayer` is deprecated in Godot 3.1 and will be removed in Godot 3.2. It is replaced by `AnimationTree`, which was written from scratch and likely fixes/deprecates this issue.

If the issue is still relevant in some form with `AnimationTree` in Godot 3.1, please open a new issue about it (potentially linking this one if there is relevant discussion to keep track of).
