### ISSUE TITLE
improvement suggestions for godot(3) gui

### ISSUE THREAD

**Issue by puppetmaster-** [godotengine/godot#9931]
Suggestions for improvement

1) **[context menu to load ressource]** change click area after selecting (fix: #10238, #9052)
![context_menu_to_load_ressource](https://user-images.githubusercontent.com/10463138/28689931-ad6c15d0-7317-11e7-853f-74f035e0945d.gif)
**Suggestion:** click area should be same size before and after selecting
2) button too narrow to open the menu (fix #10006)
![image](https://user-images.githubusercontent.com/10463138/28690547-df651166-7319-11e7-9235-171bb7e44cc1.png)
3) red (error) message when pressed on [new project] button (confusing as novice)
![image](https://user-images.githubusercontent.com/10463138/28690796-d06dc4fe-731a-11e7-8cf5-cee029e13864.png)
**Suggestion:** Give hint that default project path is empty and can be set on editor setting
4) selecting script language don't change file extension(Path) automatic and give error message (fix #10006)
![script_file_extension](https://user-images.githubusercontent.com/10463138/28691348-ea9ba77c-731c-11e7-855b-4a65deae4bea.gif)
5) tree point behave different
![tree_points](https://user-images.githubusercontent.com/10463138/28691921-db18b2e8-731e-11e7-9467-ccb6c05cdbce.gif)
6) editor settings don't show icon to reset to default (PR: #11564)
![reset_icon](https://user-images.githubusercontent.com/10463138/28692365-8e2bf63c-7320-11e7-9f5c-4949e78fb91e.gif)

I hope there are not to much for one issue. Thanks for all the cool new g3 improvement.

**Comment by djrm** [comment]
about 1) i would prefere the menu to appear when the right mouse button is pressed (as contextual menu), let me take a look at most of this stuff.

**Comment by Zylann** [comment]
I would also suggest a change of icon for the "help":
![image](https://user-images.githubusercontent.com/1311555/28694521-57628062-732a-11e7-9fef-96ca9c6028ed.png)
It looks like a very small magnifying glass and some kind of... chain, but looking closer it actually says "DOC", not a good choice for a help icon IMO, maybe a question mark / book with bookmark / good old buoy would be better.

**Comment by Hinsbart** [comment]
Regarding 3.: I think that ideally, we'd have a "frist start" dialog, asking about the default project location. (#8134)

**Comment by toger5** [comment]
3 definitly has to be adressed, because choosijg a floder does not put the project intp the folde,instead it makes that folder the project.
With the auto importer this can have fatal reults when choosing the documents folder... All files will get imported/doplicated by godot
Maybe the logic ahould be changed to: location + project folder name.

**Comment by reduz** [comment]
Regarding #1 and #2, I think the option menu was made wider so in part this has improved. I need to make it so click happens on button release, so dragging the resource works again. About @djrm suggestion to use RMB, I think this is ok, but it's optional and should not remove the menu for discoverability reasons.

Regarding #3, feel free to fix it guys as you best see fit

#4 is a pain in the ass usability wise, this need to be fixed

#5 happens because for some reason the TreeItem is set as selectable, even though it has no benefit being selectable

#6 should not be too difficult...

**Comment by djrm** [comment]
i solved 4 a while back

**Comment by djrm** [comment]
i have a PR for 3, #10796

**Comment by djrm** [comment]
pr for **6** #11564

also about **5**, it has to be discussed, the reason for it being selectable is that on non default actions, you can press the name to modify it, disabling selection causes avoids the renaming of the action. An option would be to add a button to modify the name, or use double click to update it.

**Comment by djrm** [comment]
i think this can be finally closed, maybe open another issue for 5, since it needs discussion.
