### ISSUE TITLE
My problems with godot

### ISSUE THREAD

**Issue by LeonKuhne** [godotengine/godot#99365]
### Tested versions

- Every time I launch play I get a video driver fallback warning that cant be eliminated using flags or settings (ie changing to opengl3), I am on wayland perhaps this is why -- x11 is to be deprecated (imo). The logs do not show anything relevant
- The vertical scrolling speed in the UI is incredibly sensitive compared to my other apps and the setting 'navigation v scroll speed' doesn't do anything to it
- I should be able to see the remote scene (the fact that I cant feels like an architectural decision I strongly disagree with)
- I cant use vim in your built in editor, the godot doesn't support the integration it requires
- vscode doesnt provide lints/errors with any extensions I've found, but i can alt tab to lint with godots editor which is a pain
- The built in editor is horrible and should be an optional plugin that comes uninstalled by default
- You severly f'd up dictionaries by making them lists instead of hashmaps. This is just plain stupid and anyone with a programming background should clearly know why
- Greyboxing works well, I would love a minimalist version of this engine that focuses on just that

These rainbow haired kids are really starting to get to me with their incompetence. Am I the only dev using vim and linux, or am I the only dev using godot? Either way I think I'm too old for this engine... 

### System information

Complaints

### Issue description

NA

### Steps to reproduce

NA

### Minimal reproduction project (MRP)

NA

**Comment by PhairZ** [comment]
I understand your frustrations, but I think some of these issues might come down to misunderstandings or preferences rather than fundamental problems with Godot. It's worth remembering that Godot is an open-source project, so its development is driven by contributions from the community—not activists or some specific group.

Here's a response for some of your complaints:

> Every time I launch play I get a video driver fallback warning that cant be eliminated using flags or settings (ie changing to opengl3), I am on wayland perhaps this is why -- x11 is to be deprecated (imo). The logs do not show anything relevant

The video driver warning is likely tied to Wayland support, which is still maturing.

> The vertical scrolling speed in the UI is incredibly sensitive compared to my other apps and the setting 'navigation v scroll speed' doesn't do anything to it

If the setting doesn’t work, it could be worth filing a bug report. You may also contribute yourself as this is an open source community driven project.

> I cant use vim in your built in editor, the godot doesn't support the integration it requires

while Godot’s editor doesn’t natively support it, many devs use external tools like VS Code to great effect. And after all—workarounds exist, I'm pretty sure someone found some way to use vim with godot.

> You severly f'd up dictionaries by making them lists instead of hashmaps. This is just plain stupid and anyone with a programming background should clearly know why.

Dictionaries do function like hashmaps, but their behavior might differ from other languages. Languages do have their differences after all.


Godot thrives on user feedback and contributions, so if something isn’t working for you, there’s always room to collaborate or even fork the engine to suit your needs! 😊
