### ISSUE TITLE
C#: Callable.From() on async lambda throws a harmless exception

### ISSUE THREAD

**Issue by HeySora** [godotengine/godot#99435]
### Tested versions

- Reproducible in `v4.3.stable.mono.official` [77dcf97d8]

### System information

Godot v4.3.stable.mono - macOS 15.0.1 - Vulkan (Forward+) - integrated Apple M3 Max - Apple M3 Max (14 Threads)

### Issue description

Using an async lambda as a Callable throws a System.InvalidOperationException because it is attempting to convert the `System.Threading.Tasks.Task` to a Variant.

The code still runs fine, and no side-effects are present from that interaction, so I think the engine should treat a non-generic Task as a void value and not throw that exception.

I also checked that Godot gracefully handles this case internally, which is the case, as this Variant conversion is the very last thing that is done, and falls back to a default Variant value on failure.

https://github.com/godotengine/godot/blob/fd4c29a189e53a1e085df5b9b9a05cac9351b3ef/modules/mono/glue/GodotSharp/GodotSharp/Core/DelegateUtils.cs#L84-L94

https://github.com/godotengine/godot/blob/fd4c29a189e53a1e085df5b9b9a05cac9351b3ef/modules/mono/glue/GodotSharp/GodotSharp/Core/Callable.generics.cs#L279-L288

### Steps to reproduce

Calling this code from a `_Ready` function is enough to exhibit this issue.
```cs
Callable.From(async () =>
{
    GD.Print("Waiting for delay");
    await ToSignal(GetTree().CreateTimer(1), "timeout");
    GD.Print("Delay complete");
}).Call();
```

### Minimal reproduction project (MRP)

[MRP-CallableFromException.zip](https://github.com/user-attachments/files/17820004/MRP-CallableFromException.zip)

**Comment by raulsntos** [comment]
`Task` is not a [Variant-compatible type](https://docs.godotengine.org/en/stable/tutorials/scripting/c_sharp/c_sharp_variant.html#variant-compatible-types). Removing this check would mean you'd run into issues when trying to use the type as a `Variant` (i.e.: trying to use `Task` with some Godot API).

The exception only seems harmless to you because you are not using the `Variant` returned from the `Callable.Call` invocation. The value returned from the `Callable`'s delegate must be converted to `Variant` so it can be returned, but if the value can't be converted it throws. If the conversion didn't throw for incompatible values, we'd be potentially hiding a bug in your code.

Since you are not awaiting the returned `Task`, it sounds like you really just want an `async void` method here:

```csharp
Callable.From(async void () =>
{
    GD.Print("Waiting for delay");
    await ToSignal(GetTree().CreateTimer(1), "timeout");
    GD.Print("Delay complete");
}).Call();
```

**Comment by HeySora** [comment]
Oh wow; I completely forgot that async void lambdas were supported on .NET 6. Thank you for this solution, it's exactly what this use-case needs.
