### ISSUE TITLE
C#: Script Generator fails when using generics in a dictionary.

### ISSUE THREAD

**Issue by paulcnova** [godotengine/godot#99454]
### Tested versions

- Reproducible in: 4.4.dev4, 4.4.dev3, 4.4.dev2
- Not reproducible in: 4.3.stable, 4.4.dev1

### System information

Godot v4.4.dev4.mono - Windows 10.0.22631 - Multi-window, 1 monitor - Vulkan (Forward+) - integrated Intel(R) Iris(R) Xe Graphics (Intel Corporation; 31.0.101.4314) - 13th Gen Intel(R) Core(TM) i7-1360P (16 threads)

### Issue description

I migrated a project over to `4.4.dev4` when the project was using `4.3.stable`. It fail compilation and gave this error:

```
CS8785: Generator 'ScriptPropertiesGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Nullable object must have a value.' CSC(0,0)
```

I narrowed it down to a single property from a single C# file. It seems the script generator is having trouble with generics in dictionaries. The following code created the failure in compilation:

```csharp
public partial class SpatialHashMap<[MustBeVariant] T> : Resource
{
    [Export] public Dictionary<Vector3I, T> Data { get; set; }
}
```

### Steps to reproduce

1. Create a new `.cs` file
2. Add the code below into that file:

```csharp
using Godot;
using Godot.Collections;

public partial class SpatialHashMap<[MustBeVariant] T> : Resource
{
    [Export] public Dictionary<Vector3I, T> Data { get; set; } = new Dictionary<Vector3I, T>();
}
```

3. Build

### Minimal reproduction project (MRP)

N/A

**Comment by raulsntos** [comment]
Unbound generics are not supported in exported properties, this applies to every generic type (like `Godot.Collections.Array<T>`). However, Godot didn't support type hints for Dictionaries until 4.4 so that's why you are only running into this now. Before 4.4 we were exporting untyped Dictionaries in these cases, but now we try to generate the proper type hints and since the type is unbound we can't.

Related:
- https://github.com/godotengine/godot/issues/74960
- https://github.com/godotengine/godot/pull/92082
