### ISSUE TITLE
Attach script file window causes file to be over written.

### ISSUE THREAD

**Issue by vonflyhighace2** [godotengine/godot#9958]
**Operating system or device - Godot version:**
Godot 3.0 alpha
Windows 10
**Issue description:**
Using the attach script file menu creates a new script but does not load a script from disk. This could also lead to users over writing files if unaware.

**Steps to reproduce:**
Right click a node. Select attach script. select the path to the script to attach. Do not hit create else you will over write you file.

**Link to minimal example project:**

**Comment by qbradq** [comment]
Unable to reproduce

**Steps Tested**
Create a new scene
Add a node
Save scene as Node.tscn
Attach a script to the node, edit that script, save it as node.gd
Add a child node
Right-click on the new node, select "Attach Script"
Click on the folder icon to the right of the "Path" line edit
Select node.gd
Information box now changes to say "- Script valid" and "- Load existing script file"
Click the "Load" button

**Result**
node.gd is opened in the editor unaltered
node.gd is not altered on the disk
Behavior is as expected

**Build Information**
OS: OSX 10.12
Build Type: bin/godot.osx.tools.64
Commit: daad16b7c7a10f0f1ede92899573e9e354c9d2cd

**Comment by vonflyhighace2** [comment]
Doesn't look like your using the alpha1 build. Yours seem more recent this could have been fix in your build. Try with alpha1.
________________________________

**Comment by Hinsbart** [comment]
@vonflyhighace2 I also can't reproduce this using the alpha1 binary.

**Comment by qbradq** [comment]
@vonflyhighace2 That's why we check with the latest commit against master, to see if the issue still exists. It's sort of the first step to see if a programmer needs to take action. Thank you for the report!

**Comment by MrRevington** [comment]
Hi!

I can reproduce the issue on Windows 10 with latest runnable master build.
The problem seems to be this:
[https://github.com/godotengine/godot/blame/2dc4b035a8c1296934e7c053b90b30924461d62b/editor/script_create_dialog.cpp#L301](https://github.com/godotengine/godot/blame/2dc4b035a8c1296934e7c053b90b30924461d62b/editor/script_create_dialog.cpp#L301)

I think current_is_dir() should be dir_exists(p) because current_is_dir is only for items processed with the last get_next.

hth
