### ISSUE TITLE
Example of Good Commenting - Hello Mario Engine

### ISSUE THREAD

**Issue by P-Star7** [godotengine/godot#9962]
I know this isn't really a bug, but I think that this is important for Godot, more specifically its documentation and example projects
https://github.com/HelloFangaming/HelloMarioEngine
This engine written in Game Maker Language is very good at explaining all things written in the object code that aren't immediately obvious from the GameMaker UI (which means such as which parent the object has, which default sprite the object uses, and which mask the object has). For example, the code explains an object's behaviors such as setting the object's creation parameters in the Create event (such as facing direction, which state of the FSM it is in when starting, and which qualities it has such as immune to fireballs, can be stomped, etc.) Speaking of those, it also helped me understand finite state machines in the step events, too (such as how an object changes graphics and movement behavior when it changes to a state, such as throwing, jumping, etc., and how they have variables such as having one sprite when jumping but switch to another when they land). I'm sorry for my fuzzy instructions, because it's been a while since I used that engine due to not wanting to continue development on a project that wasn't GPL-friendly. What I mean to be taken away from this is that I really appreciate when projects do not assume knowledge of the student, and that seeing the same "you do this to x" explanation in each object helped me get the concepts in a general sense.

**Comment by reduz** [comment]
This was brought up many times, but you have to understand that Godot is
nearly a million lines of code and the internals use advanced programming
techniques that already require programmers to have a considerable
background before tackling many of it's subsystems.

That said, the exposed API should be as best documented and easy to use as
possible, so any feedback on improving this is welcome

On Jul 28, 2017 11:11 PM, "P-Star7" <notifications@github.com> wrote:

I know this isn't really a bug, but I think that this is important for
Godot, more specifically its documentation and example projects
https://github.com/HelloFangaming/HelloMarioEngine
This engine written in Game Maker Language is very good at explaining all
things written in the object code that aren't immediately obvious from the
GameMaker UI (which means such as which parent the object has, which
default sprite the object uses, and which mask the object has). For
example, the code explains an object's behaviors such as setting the
object's creation parameters in the Create event (such as facing direction,
which state of the FSM it is in when starting, and which qualities it has
such as immune to fireballs, can be stomped, etc.) Speaking of those, it
also helped me understand finite state machines in the step events, too
(such as how an object changes graphics and movement behavior when it
changes to a state, such as throwing, jumping, etc., and how they have
variables such as having one sprite when jumping but switch to another when
they land). I'm sorry for my fuzzy instructions, because it's been a while
since I used that engine due to not wanting to continue development on a
project that wasn't GPL-friendly. What I mean to be taken away from this is
that I really appreciate when projects do not assume knowledge of the
student, and that seeing the same "you do this to x" explanation in each
object helped me get the concepts in a general sense.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/godotengine/godot/issues/9962>, or mute the thread

**Comment by P-Star7** [comment]
Oh, sorry, what I meant was making a project IN Godot, not editing the engine itself. Hello Mario Engine helped me learn a lot about GML, the scripting language in GameMaker.

**Comment by P-Star7** [comment]
(Sorry, can't edit)
I've only used Hello Mario Engine in GameMaker instead of using a less-featured base or making a project from scratch, but it made me feel that, even if I couldn't completely replicate its systems, that I was equipped with the knowledge change player physics and actions, make new items, weapons and enemies, and generally all the other creative things that would be required for a platformer-type game, even though I didn't have much prior experience with GML. I hope that the platformer demo for Godot will be educational enough for me to feel the same about GDScript!

**Comment by vnen** [comment]
Don't get the point of this issue. Is it about the demo projects? If so, you should open an issue in their repository (https://github.com/godotengine/godot-demo-projects). If it's a lack of tutorials, you should post on the documentation repository (https://github.com/godotengine/godot-docs).

Do you want a fully commented project? I'm not sure how helpful that might be. There are tons of different game styles that Godot can handle, it's hard to provide useful commented project for every genre. Don't know the Hello Mario Engine or its code, nor how it presents to the user, but if you need something on Godot, you should be a bit more clear about what you want to see.

**Comment by eon-s** [comment]
If you can't add comments or the details you think documentation or projects need (understandable if you don't know much about the engine), try going to one of the other official communication channels to discuss about it.

There are many GM users lately and all could organize a new documentation section too, like the one for Unity users.

**Comment by P-Star7** [comment]
Oh yes, I agree with a "GM to Godot" section. A kind user helped me when I asked on the forums. I haven't used Godot yet because I'm waiting for the 3.0 version, so I'm sorry if what I said was confusing. I just meant to post this as an example of how to effectively include comments in a project in a way that helped me learn.

**Comment by akien-mga** [comment]
Discussion has stalled.
